Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_atifragshader.c File Reference
#include "main/glheader.h"
#include "main/macros.h"
#include "main/atifragshader.h"
#include "main/samplerobj.h"
#include "swrast/s_atifragshader.h"
#include "swrast/s_context.h"
Data Structures
struct atifs_machine
State for executing ATI fragment shader.
Macros
#define ATI_FS_INPUT_PRIMARY 0
#define ATI_FS_INPUT_SECONDARY 1
#define SETUP_SRC_REG(optype, i, x)
Functions
static void fetch_texel (struct gl_context *ctx, const GLfloat texcoord[4], GLfloat lambda, GLuint unit, GLfloat color[4])
Fetch a texel.
static void apply_swizzle (GLfloat values[4], GLuint swizzle)
static void apply_src_rep (GLint optype, GLuint rep, GLfloat *val)
static void apply_src_mod (GLint optype, GLuint mod, GLfloat *val)
static void apply_dst_mod (GLuint optype, GLuint mod, GLfloat *val)
static void write_dst_addr (GLuint optype, GLuint mod, GLuint mask, GLfloat *src, GLfloat *dst)
static void finish_pass (struct atifs_machine *machine)
static void handle_pass_op (struct atifs_machine *machine, struct atifs_setupinst *texinst, const SWspan *span, GLuint column, GLuint idx)
static void handle_sample_op (struct gl_context *ctx, struct atifs_machine *machine, struct atifs_setupinst *texinst, const SWspan *span, GLuint column, GLuint idx)
static void execute_shader (struct gl_context *ctx, const struct ati_fragment_shader *shader, struct atifs_machine *machine, const SWspan *span, GLuint column)
Execute the given fragment shader.
static void init_machine (struct gl_context *ctx, struct atifs_machine *machine, const struct ati_fragment_shader *shader, const SWspan *span, GLuint col)
Init fragment shader virtual machine state.
void _swrast_exec_fragment_shader (struct gl_context *ctx, SWspan *span)
Execute the current ATI shader program, operating on the given span.
Macro Definition Documentation
ATI_FS_INPUT_PRIMARY
#define ATI_FS_INPUT_PRIMARY 0
Referenced by execute_shader(), and init_machine().
ATI_FS_INPUT_SECONDARY
#define ATI_FS_INPUT_SECONDARY 1
Referenced by execute_shader(), and init_machine().
SETUP_SRC_REG
#define SETUP_SRC_REG (optype, i, x)
Value:
do {                                            \
   COPY_4V(src[optype][i], x);                  \
} while (0)
Referenced by execute_shader().
Function Documentation
_swrast_exec_fragment_shader()
void _swrast_exec_fragment_shader (struct gl_context * ctx, SWspan * span)
Execute the current ATI shader program, operating on the given span.
References sw_span::array, gl_context::ATIFragmentShader, sw_span_arrays::attribs, sw_span_arrays::ChanType, COPY_4V, gl_ati_fragment_shader_state::Current, sw_span::end, execute_shader(), GLuint, init_machine(), sw_span_arrays::mask, and atifs_machine::Registers.
Referenced by shade_texture_span().
apply_dst_mod()
static void apply_dst_mod (GLuint optype, GLuint mod, GLfloat * val) static
References F.
Referenced by write_dst_addr().
apply_src_mod()
static void apply_src_mod (GLint optype, GLuint mod, GLfloat * val) static
Referenced by execute_shader().
apply_src_rep()
static void apply_src_rep (GLint optype, GLuint rep, GLfloat * val) static
Referenced by execute_shader().
apply_swizzle()
static void apply_swizzle (GLfloat values[4], GLuint swizzle) static
References F.
Referenced by handle_pass_op(), and handle_sample_op().
execute_shader()
static void execute_shader (struct gl_context * ctx, const struct ati_fragment_shader * shader, struct atifs_machine * machine, const SWspan * span, GLuint column) static
Execute the given fragment shader.
NOTE: we do everything in single-precision floating point
Parameters
ctx - rendering context
shader - the shader to execute
machine - virtual machine state
span - the SWspan we're operating on
column - which pixel [i] we're operating on in the span
References apply_src_mod(), apply_src_rep(), atifs_instruction::ArgCount, atifragshader_src_register::argMod, atifragshader_src_register::argRep, ATI_FRAGMENT_SHADER_PASS_OP, ATI_FRAGMENT_SHADER_SAMPLE_OP, ATI_FS_INPUT_PRIMARY, ATI_FS_INPUT_SECONDARY, gl_context::ATIFragmentShader, ati_fragment_shader::Constants, atifragshader_dst_register::dstMask, atifragshader_dst_register::dstMod, atifs_instruction::DstReg, finish_pass(), gl_ati_fragment_shader_state::GlobalConstants, GLuint, handle_pass_op(), handle_sample_op(), atifragshader_dst_register::Index, atifragshader_src_register::Index, atifs_machine::Inputs, ati_fragment_shader::Instructions, ati_fragment_shader::LocalConstDef, MAX_NUM_FRAGMENT_REGISTERS_ATI, ati_fragment_shader::numArithInstr, ati_fragment_shader::NumPasses, atifs_instruction::Opcode, atifs_setupinst::Opcode, atifs_machine::Registers, SETUP_SRC_REG, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_instruction::SrcReg, and write_dst_addr().
Referenced by _swrast_exec_fragment_shader().
fetch_texel()
static void fetch_texel (struct gl_context * ctx, const GLfloat texcoord[4], GLfloat lambda, GLuint unit, GLfloat color[4]) static
Fetch a texel.
References gl_texture_unit::_Current, swrast, SWRAST_CONTEXT(), gl_context::Texture, SWcontext::TextureSample, and gl_texture_attrib::Unit.
Referenced by handle_sample_op().
finish_pass()
static void finish_pass (struct atifs_machine * machine) static
References COPY_4V, atifs_machine::PrevPassRegisters, and atifs_machine::Registers.
Referenced by execute_shader().
handle_pass_op()
static void handle_pass_op (struct atifs_machine * machine, struct atifs_setupinst * texinst, const SWspan * span, GLuint column, GLuint idx) static
References apply_swizzle(), sw_span::array, sw_span_arrays::attribs, COPY_4V, GLuint, atifs_machine::PrevPassRegisters, atifs_machine::Registers, atifs_setupinst::src, and atifs_setupinst::swizzle.
Referenced by execute_shader().
handle_sample_op()
static void handle_sample_op (struct gl_context * ctx, struct atifs_machine * machine, struct atifs_setupinst * texinst, const SWspan * span, GLuint column, GLuint idx) static
References apply_swizzle(), sw_span::array, sw_span_arrays::attribs, COPY_4V, F, fetch_texel(), GLuint, atifs_machine::PrevPassRegisters, atifs_machine::Registers, atifs_setupinst::src, and atifs_setupinst::swizzle.
Referenced by execute_shader().
init_machine()
static void init_machine (struct gl_context * ctx, struct atifs_machine * machine, const struct ati_fragment_shader * shader, const SWspan * span, GLuint col) static
Init fragment shader virtual machine state.
References sw_span::array, ATI_FS_INPUT_PRIMARY, ATI_FS_INPUT_SECONDARY, sw_span_arrays::attribs, COPY_4V, atifs_machine::Inputs, and atifs_machine::Registers.
Referenced by _swrast_exec_fragment_shader().
write_dst_addr()
static void write_dst_addr (GLuint optype, GLuint mod, GLuint mask, GLfloat * src, GLfloat * dst) static
References apply_dst_mod(), and ATI_FRAGMENT_SHADER_COLOR_OP.
Referenced by execute_shader().