Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_aaline.h File Reference
Functions
void _swrast_choose_aa_line_function (struct gl_context *ctx)
Function Documentation
_swrast_choose_aa_line_function()
void _swrast_choose_aa_line_function (struct gl_context * ctx)
References gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, _swrast_use_fragment_program(), gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_light_attrib::Enabled, gl_context::Fog, gl_context::Light, gl_context::Line, SWcontext::Line, gl_light_attrib::Model, gl_line_attrib::SmoothFlag, swrast, SWRAST_CONTEXT(), and gl_context::Texture.
Referenced by _swrast_choose_line().