Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_atifragshader.h File Reference
#include "s_span.h"
Functions
void _swrast_exec_fragment_shader (struct gl_context *ctx, SWspan *span)
Execute the current ATI shader program, operating on the given span.
Function Documentation
_swrast_exec_fragment_shader()
void _swrast_exec_fragment_shader (struct gl_context * ctx, SWspan * span)
Execute the current ATI shader program, operating on the given span.
References sw_span::array, gl_context::ATIFragmentShader, sw_span_arrays::attribs, sw_span_arrays::ChanType, COPY_4V, gl_ati_fragment_shader_state::Current, sw_span::end, execute_shader(), GLuint, init_machine(), sw_span_arrays::mask, and atifs_machine::Registers.
Referenced by shade_texture_span().