Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_aaline.c File Reference
#include "c99_math.h"
#include "main/glheader.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/teximage.h"
#include "swrast/s_aaline.h"
#include "swrast/s_context.h"
#include "swrast/s_span.h"
#include "swrast/swrast.h"
#include "s_aalinetemp.h"
Data Structures
struct LineInfo
Macros
#define SUB_PIXEL 4
#define SOLVE_PLANE(X, Y, PLANE) ((PLANE[3] + PLANE[0] * (X) + PLANE[1] * (Y)) / -PLANE[2])
#define NAME(x) aa_rgba_##x
#define DO_Z
#define NAME(x) aa_general_rgba_##x
#define DO_Z
#define DO_ATTRIBS
Typedefs
typedef void(* plot_func) (struct gl_context *ctx, struct LineInfo *line, int ix, int iy)
Functions
static void compute_plane (GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z0, GLfloat z1, GLfloat plane[4])
static void constant_plane (GLfloat value, GLfloat plane[4])
static GLfloat solve_plane (GLfloat x, GLfloat y, const GLfloat plane[4])
static GLfloat solve_plane_recip (GLfloat x, GLfloat y, const GLfloat plane[4])
static GLchan solve_plane_chan (GLfloat x, GLfloat y, const GLfloat plane[4])
static GLfloat compute_lambda (const GLfloat sPlane[4], const GLfloat tPlane[4], GLfloat invQ, GLfloat width, GLfloat height)
static void make_sample_table (GLint xSamples, GLint ySamples, GLfloat samples[][2])
static GLfloat compute_coveragef (const struct LineInfo *info, GLint winx, GLint winy)
static void segment (struct gl_context *ctx, struct LineInfo *line, plot_func plot, GLfloat t0, GLfloat t1)
void _swrast_choose_aa_line_function (struct gl_context *ctx)
Macro Definition Documentation
DO_ATTRIBS
#define DO_ATTRIBS
DO_Z [1/2]
#define DO_Z
DO_Z [2/2]
#define DO_Z
NAME [1/2]
#define NAME (x) aa_rgba_##x
Referenced by line().
NAME [2/2]
#define NAME (x) aa_general_rgba_##x
SOLVE_PLANE
#define SOLVE_PLANE (X, Y, PLANE) ((PLANE[3] + PLANE[0] * (X) + PLANE[1] * (Y)) / -PLANE[2])
SUB_PIXEL
#define SUB_PIXEL 4
Referenced by compute_coveragef().
Typedef Documentation
plot_func
typedef void(* plot_func) (struct gl_context *ctx, struct LineInfo *line, int ix, int iy)
Function Documentation
_swrast_choose_aa_line_function()
void _swrast_choose_aa_line_function (struct gl_context * ctx)
References gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, _swrast_use_fragment_program(), gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_light_attrib::Enabled, gl_context::Fog, gl_context::Light, gl_context::Line, SWcontext::Line, gl_light_attrib::Model, gl_line_attrib::SmoothFlag, swrast, SWRAST_CONTEXT(), and gl_context::Texture.
Referenced by _swrast_choose_line().
compute_coveragef()
static GLfloat compute_coveragef (const struct LineInfo * info, GLint winx, GLint winy) static
References area, LineInfo::ex0, LineInfo::ex1, LineInfo::ex2, LineInfo::ex3, LineInfo::ey0, LineInfo::ey1, LineInfo::ey2, LineInfo::ey3, F, make_sample_table(), LineInfo::qx0, LineInfo::qx1, LineInfo::qx2, LineInfo::qx3, LineInfo::qy0, LineInfo::qy1, LineInfo::qy2, LineInfo::qy3, SUB_PIXEL, and x.
Referenced by for(), if(), and plot().
compute_lambda()
static GLfloat compute_lambda (const GLfloat sPlane[4], const GLfloat tPlane[4], GLfloat invQ, GLfloat width, GLfloat height) inline static
References F.
Referenced by plot().
compute_plane()
static void compute_plane (GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z0, GLfloat z1, GLfloat plane[4]) static
References F, LineInfo::x0, and LineInfo::y0.
Referenced by if(), and line().
constant_plane()
static void constant_plane (GLfloat value, GLfloat plane[4]) inline static
Referenced by line().
make_sample_table()
static void make_sample_table (GLint xSamples, GLint ySamples, GLfloat samples[][2]) static
References LineInfo::dx, LineInfo::dy, and x.
Referenced by compute_coveragef().
segment()
static void segment (struct gl_context * ctx, struct LineInfo * line, plot_func plot, GLfloat t0, GLfloat t1) static
References LineInfo::dx, dxdy, LineInfo::dy, LineInfo::ex0, LineInfo::ex1, LineInfo::ex2, LineInfo::ex3, LineInfo::ey0, LineInfo::ey1, LineInfo::ey2, LineInfo::ey3, F, LineInfo::halfWidth, iy, line(), LineInfo::qx0, LineInfo::qx1, LineInfo::qx2, LineInfo::qx3, LineInfo::qy0, LineInfo::qy1, LineInfo::qy2, LineInfo::qy3, LineInfo::x0, LineInfo::x1, LineInfo::xAdj, LineInfo::y0, LineInfo::y1, and LineInfo::yAdj.
Referenced by line().
solve_plane()
static GLfloat solve_plane (GLfloat x, GLfloat y, const GLfloat plane[4]) inline static
Referenced by for(), if(), and plot().
solve_plane_chan()
static GLchan solve_plane_chan (GLfloat x, GLfloat y, const GLfloat plane[4]) inline static
References CHAN_MAX, CHAN_MAXF, and F.
Referenced by for(), if(), and plot().
solve_plane_recip()
static GLfloat solve_plane_recip (GLfloat x, GLfloat y, const GLfloat plane[4]) inline static
References F.
Referenced by plot().