Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_aatriangle.h File Reference
Functions
void _swrast_set_aa_triangle_function (struct gl_context *ctx)
Function Documentation
_swrast_set_aa_triangle_function()
void _swrast_set_aa_triangle_function (struct gl_context * ctx)
References gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, _swrast_use_fragment_program(), general_aa_tri(), gl_context::Polygon, rgba_aa_tri(), gl_polygon_attrib::SmoothFlag, swrast, SWRAST_CONTEXT(), gl_context::Texture, and SWcontext::Triangle.
Referenced by _swrast_choose_triangle().