Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_aatriangle.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/state.h"
#include "s_aatriangle.h"
#include "s_context.h"
#include "s_span.h"
#include "s_aatritemp.h"
Macros
#define CONSTANT_PLANE(VALUE, PLANE)
#define SOLVE_PLANE(X, Y, PLANE) ((PLANE[3] + PLANE[0] * (X) + PLANE[1] * (Y)) / -PLANE[2])
#define POS(a, b) (0.5+a*4+b)/16
#define DO_Z
#define DO_Z
#define DO_ATTRIBS
Functions
static void compute_plane (const GLfloat v0[], const GLfloat v1[], const GLfloat v2[], GLfloat z0, GLfloat z1, GLfloat z2, GLfloat plane[4])
static void constant_plane (GLfloat value, GLfloat plane[4])
static GLfloat solve_plane (GLfloat x, GLfloat y, const GLfloat plane[4])
static GLchan solve_plane_chan (GLfloat x, GLfloat y, const GLfloat plane[4])
static GLfloat plane_dx (const GLfloat plane[4])
static GLfloat plane_dy (const GLfloat plane[4])
static GLfloat compute_coveragef (const GLfloat v0[3], const GLfloat v1[3], const GLfloat v2[3], GLint winx, GLint winy)
static void rgba_aa_tri (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
static void general_aa_tri (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_set_aa_triangle_function (struct gl_context *ctx)
Macro Definition Documentation
CONSTANT_PLANE
#define CONSTANT_PLANE (VALUE, PLANE)
Value:
do {                                    \
   PLANE[0] = 0.0F;                     \
   PLANE[1] = 0.0F;                     \
   PLANE[2] = -1.0F;                    \
   PLANE[3] = VALUE;                    \
} while (0)
DO_ATTRIBS
#define DO_ATTRIBS
DO_Z [1/2]
#define DO_Z
DO_Z [2/2]
#define DO_Z
POS
#define POS (a, b) (0.5+a*4+b)/16
Referenced by compute_coveragef().
SOLVE_PLANE
#define SOLVE_PLANE (X, Y, PLANE) ((PLANE[3] + PLANE[0] * (X) + PLANE[1] * (Y)) / -PLANE[2])
Function Documentation
_swrast_set_aa_triangle_function()
void _swrast_set_aa_triangle_function (struct gl_context * ctx)
References gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, _swrast_use_fragment_program(), general_aa_tri(), gl_context::Polygon, rgba_aa_tri(), gl_polygon_attrib::SmoothFlag, swrast, SWRAST_CONTEXT(), gl_context::Texture, and SWcontext::Triangle.
Referenced by _swrast_choose_triangle().
compute_coveragef()
static GLfloat compute_coveragef (const GLfloat v0[3], const GLfloat v1[3], const GLfloat v2[3], GLint winx, GLint winy) static
References F, POS, and x.
compute_plane()
static void compute_plane (const GLfloat v0[], const GLfloat v1[], const GLfloat v2[], GLfloat z0, GLfloat z1, GLfloat z2, GLfloat plane[4]) inline static
constant_plane()
static void constant_plane (GLfloat value, GLfloat plane[4]) inline static
general_aa_tri()
static void general_aa_tri (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
Referenced by _swrast_set_aa_triangle_function().
plane_dx()
static GLfloat plane_dx (const GLfloat plane[4]) inline static
Referenced by if().
plane_dy()
static GLfloat plane_dy (const GLfloat plane[4]) inline static
Referenced by if().
rgba_aa_tri()
static void rgba_aa_tri (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
Referenced by _swrast_set_aa_triangle_function().
solve_plane()
static GLfloat solve_plane (GLfloat x, GLfloat y, const GLfloat plane[4]) inline static
References F.
solve_plane_chan()
static GLchan solve_plane_chan (GLfloat x, GLfloat y, const GLfloat plane[4]) inline static
References CHAN_MAX, CHAN_MAXF, and F.