Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_blend.h File Reference
#include "main/glheader.h"
#include "s_span.h"
Functions
void _swrast_blend_span (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span)
Apply the blending operator to a span of pixels.
void _swrast_choose_blend_func (struct gl_context *ctx, GLenum chanType)
Analyze current blending parameters to pick fastest blending function.
Function Documentation
_swrast_blend_span()
void _swrast_blend_span (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span)
Apply the blending operator to a span of pixels.
We can handle horizontal runs of pixels (spans) or arrays of x/y pixel coordinates.
References _swrast_get_dest_rgba(), sw_span::array, sw_span::arrayMask, SWcontext::BlendFunc, sw_span_arrays::ChanType, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, sw_span::end, sw_span_arrays::mask, sw_span_arrays::rgba, SPAN_RGBA, swrast, SWRAST_CONTEXT(), and SWRAST_MAX_WIDTH.
Referenced by _swrast_write_rgba_span().
_swrast_choose_blend_func()
void _swrast_choose_blend_func (struct gl_context * ctx, GLenum chanType)
Analyze current blending parameters to pick fastest blending function.
Result: the ctx->Color.BlendFunc pointer is updated.
References gl_colorbuffer_attrib::Blend, blend_add(), blend_general(), blend_max(), blend_min(), blend_modulate(), blend_noop(), blend_replace(), blend_transparency_float(), blend_transparency_ubyte(), blend_transparency_ushort(), SWcontext::BlendFunc, gl_context::Color, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_validate_blend_func().