Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_bitmap.c File Reference
glBitmap rendering.
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/condrender.h"
#include "main/image.h"
#include "main/macros.h"
#include "main/pbo.h"
#include "s_context.h"
#include "s_span.h"
Functions
void _swrast_Bitmap (struct gl_context *ctx, GLint px, GLint py, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
Render a bitmap.
Detailed Description
glBitmap rendering.
Author
Brian Paul
Function Documentation
_swrast_Bitmap()
void _swrast_Bitmap (struct gl_context * ctx, GLint px, GLint py, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * bitmap)
Render a bitmap.
Called via ctx->Driver.Bitmap() All parameter error checking will have been done before this is called.
References _mesa_check_conditional_render(), _mesa_image_address2d(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _swrast_Bitmap(), _swrast_span_default_attribs(), _swrast_validate_derived(), _swrast_write_rgba_span(), sw_span::array, sw_span::arrayMask, sw_span::end, GLuint, INIT_SPAN(), gl_pixelstore_attrib::LsbFirst, sw_span_arrays::mask, gl_context::NewState, gl_context::RenderMode, gl_pixelstore_attrib::SkipPixels, span, SPAN_MASK, SPAN_XY, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, swrast_render_finish(), swrast_render_start(), sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_Bitmap().