Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_blit.c File Reference
#include "main/glheader.h"
#include "main/condrender.h"
#include "main/image.h"
#include "main/macros.h"
#include "main/format_unpack.h"
#include "main/format_pack.h"
#include "s_context.h"
Macros
#define ABS(X) ((X) < 0 ? -(X) : (X))
#define RESAMPLE(NAME, PIXELTYPE, SIZE)
Generate a row resampler function for GL_NEAREST mode.
#define LERP(T, A, B) ((A) + (T) * ((B) - (A)))
Functions
static void blit_nearest (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield buffer)
Resamplers for 1, 2, 4, 8 and 16-byte pixels.
static GLfloat lerp_2d (GLfloat a, GLfloat b, GLfloat v00, GLfloat v10, GLfloat v01, GLfloat v11)
static void resample_linear_row_ub (GLint srcWidth, GLint dstWidth, const GLvoid *srcBuffer0, const GLvoid *srcBuffer1, GLvoid *dstBuffer, GLboolean flip, GLfloat rowWeight)
Bilinear interpolation of two source rows.
static void resample_linear_row_float (GLint srcWidth, GLint dstWidth, const GLvoid *srcBuffer0, const GLvoid *srcBuffer1, GLvoid *dstBuffer, GLboolean flip, GLfloat rowWeight)
Bilinear interpolation of two source rows.
static void blit_linear (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1)
Bilinear filtered blit (color only, non-integer values).
void _swrast_BlitFramebuffer (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Software fallback for glBlitFramebufferEXT().
Macro Definition Documentation
ABS
#define ABS (X) ((X) < 0 ? -(X) : (X))
Referenced by blit_linear(), and blit_nearest().
LERP
#define LERP (T, A, B) ((A) + (T) * ((B) - (A)))
Referenced by lerp_2d().
RESAMPLE
#define RESAMPLE (NAME, PIXELTYPE, SIZE)
Generate a row resampler function for GL_NEAREST mode.
Function Documentation
_swrast_BlitFramebuffer()
void _swrast_BlitFramebuffer (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Software fallback for glBlitFramebufferEXT().
References _mesa_check_conditional_render(), _mesa_clip_blit(), _swrast_validate_derived(), blit_linear(), blit_nearest(), SWRAST_CONTEXT(), and swrast_fast_copy_pixels().
blit_linear()
static void blit_linear (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1) static
Bilinear filtered blit (color only, non-integer values).
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorReadBuffer, gl_framebuffer::_ColorReadBufferIndex, _mesa_error(), _mesa_get_format_bytes(), _mesa_get_format_datatype(), _mesa_get_format_max_bits(), _mesa_get_srgb_format_linear(), _mesa_pack_float_rgba_row(), _mesa_pack_ubyte_rgba_row(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_rgba_row(), gl_framebuffer::_NumColorDrawBuffers, ABS, gl_framebuffer::Attachment, gl_context::Driver, F, gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, dd_function_table::MapRenderbuffer, gl_renderbuffer_attachment::Renderbuffer, resample_linear_row_float(), resample_linear_row_ub(), gl_renderbuffer_attachment::Texture, dd_function_table::UnmapRenderbuffer, and gl_renderbuffer::Width.
Referenced by _swrast_BlitFramebuffer().
blit_nearest()
static void blit_nearest (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield buffer) static
Resamplers for 1, 2, 4, 8 and 16-byte pixels.
Blit color, depth or stencil with GL_NEAREST filtering.
References _mesa_error(), _mesa_get_format_bytes(), _mesa_pack_float_rgba_row(), _mesa_pack_float_z_row(), _mesa_pack_ubyte_stencil_row(), _mesa_pack_uint_z_row(), _mesa_problem(), _mesa_unpack_float_z_row(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_stencil_row(), _mesa_unpack_uint_z_row(), ABS, BUFFER_DEPTH, BUFFER_STENCIL, F, gl_renderbuffer::Format, gl_renderbuffer::Height, MAX_PIXEL_BYTES, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, void, and gl_renderbuffer::Width.
Referenced by _swrast_BlitFramebuffer().
lerp_2d()
static GLfloat lerp_2d (GLfloat a, GLfloat b, GLfloat v00, GLfloat v10, GLfloat v01, GLfloat v11) inline static
References LERP.
Referenced by resample_linear_row_float(), and resample_linear_row_ub().
resample_linear_row_float()
static void resample_linear_row_float (GLint srcWidth, GLint dstWidth, const GLvoid * srcBuffer0, const GLvoid * srcBuffer1, GLvoid * dstBuffer, GLboolean flip, GLfloat rowWeight) static
Bilinear interpolation of two source rows.
floating point pixels.
References ACOMP, BCOMP, F, GCOMP, lerp_2d(), and RCOMP.
Referenced by blit_linear().
resample_linear_row_ub()
static void resample_linear_row_ub (GLint srcWidth, GLint dstWidth, const GLvoid * srcBuffer0, const GLvoid * srcBuffer1, GLvoid * dstBuffer, GLboolean flip, GLfloat rowWeight) static
Bilinear interpolation of two source rows.
GLubyte pixels.
References ACOMP, BCOMP, F, GCOMP, lerp_2d(), and RCOMP.
Referenced by blit_linear().