Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_clear.c File Reference
#include "main/glheader.h"
#include "main/accum.h"
#include "main/condrender.h"
#include "main/format_pack.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "s_context.h"
#include "s_depth.h"
#include "s_stencil.h"
Macros
#define SIMPLE_TYPE_CLEAR(TYPE)
#define MULTI_WORD_CLEAR(TYPE, N)
Functions
static void clear_rgba_buffer (struct gl_context *ctx, struct gl_renderbuffer *rb, const GLubyte colorMask[4])
Clear an rgba color buffer with masking if needed.
static void clear_color_buffers (struct gl_context *ctx)
Clear the front/back/left/right/aux color buffers.
void _swrast_Clear (struct gl_context *ctx, GLbitfield buffers)
Called via the device driver's ctx->Driver.Clear() function if the device driver can't clear one or more of the buffers itself.
Macro Definition Documentation
MULTI_WORD_CLEAR
#define MULTI_WORD_CLEAR (TYPE, N)
Referenced by clear_rgba_buffer().
SIMPLE_TYPE_CLEAR
#define SIMPLE_TYPE_CLEAR (TYPE)
Value:
do {                                                                 \
      TYPE pixel, pixelMask;                                            \
      _mesa_pack_float_rgba_row(rb->Format, 1, clearColor, &pixel);     \
      if (doMasking) {                                                  \
         _mesa_pack_colormask(rb->Format, colorMask, &pixelMask);       \
         pixel &= pixelMask;                                            \
         pixelMask = ~pixelMask;                                        \
      }                                                                 \
      for (i = 0; i < height; i++) {                                    \
         TYPE *row = (TYPE *) map;                                      \
         if (doMasking) {                                               \
            for (j = 0; j < width; j++) {                               \
               row[j] = (row[j] & pixelMask) | pixel;                   \
            }                                                           \
         }                                                              \
         else {                                                         \
            for (j = 0; j < width; j++) {                               \
               row[j] = pixel;                                          \
            }                                                           \
         }                                                              \
         map += rowStride;                                              \
      }                                                                 \
   } while (0)
Referenced by clear_rgba_buffer().
Function Documentation
_swrast_Clear()
void _swrast_Clear (struct gl_context * ctx, GLbitfield buffers)
Called via the device driver's ctx->Driver.Clear() function if the device driver can't clear one or more of the buffers itself.
Parameters
buffers bitfield of BUFFER_BIT_* values indicating which renderbuffers are to be cleared.
all if GL_TRUE, clear whole buffer, else clear specified region.
References _mesa_check_conditional_render(), _mesa_clear_accum_buffer(), gl_framebuffer::_NumColorDrawBuffers, _swrast_clear_depth_buffer(), _swrast_clear_depth_stencil_buffer(), _swrast_clear_stencil_buffer(), _swrast_validate_derived(), gl_framebuffer::Attachment, BUFFER_BIT_ACCUM, BUFFER_BIT_AUX0, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_DEPTH, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_BIT_STENCIL, BUFFER_BITS_COLOR, BUFFER_DEPTH, BUFFER_STENCIL, clear_color_buffers(), gl_context::DrawBuffer, gl_renderbuffer_attachment::Renderbuffer, and SWRAST_CONTEXT().
clear_color_buffers()
static void clear_color_buffers (struct gl_context * ctx) static
Clear the front/back/left/right/aux color buffers.
This function is usually only called if the device driver can't clear its own color buffers for some reason (such as with masking).
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, clear_rgba_buffer(), gl_context::Color, gl_colorbuffer_attrib::ColorMask, gl_context::DrawBuffer, and GLuint.
Referenced by _swrast_Clear().
clear_rgba_buffer()
static void clear_rgba_buffer (struct gl_context * ctx, struct gl_renderbuffer * rb, const GLubyte colorMask[4]) static
Clear an rgba color buffer with masking if needed.
References _mesa_error(), _mesa_get_format_bytes(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_colorbuffer_attrib::ClearColor, gl_context::Color, gl_context::DrawBuffer, gl_context::Driver, gl_color_union::f, gl_renderbuffer::Format, GLuint, GLushort, if(), dd_function_table::MapRenderbuffer, MULTI_WORD_CLEAR, SIMPLE_TYPE_CLEAR, dd_function_table::UnmapRenderbuffer, and x.
Referenced by clear_color_buffers().