Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_context.h File Reference
Software rasterization context and private types.
#include "main/compiler.h"
#include "main/mtypes.h"
#include "main/texcompress.h"
#include "program/prog_execute.h"
#include "swrast.h"
#include "s_fragprog.h"
#include "s_span.h"
Data Structures
struct swrast_texture_image
Subclass of gl_texture_image.
struct swrast_renderbuffer
Subclass of gl_renderbuffer with extra fields needed for software rendering.
struct SWcontext
Per-context state that's private to the software rasterizer module.
Macros
#define ALPHATEST_BIT 0x001
Alpha-test pixels.
#define BLEND_BIT 0x002
Blend pixels.
#define DEPTH_BIT 0x004
Depth-test pixels.
#define FOG_BIT 0x008
Fog pixels.
#define LOGIC_OP_BIT 0x010
Apply logic op in software.
#define CLIP_BIT 0x020
Scissor or window clip pixels.
#define STENCIL_BIT 0x040
Stencil pixels.
#define MASKING_BIT 0x080
Do glColorMask or glIndexMask.
#define MULTI_DRAW_BIT 0x400
Write to more than one color-.
#define OCCLUSION_BIT 0x800
GL_HP_occlusion_test enabled.
#define TEXTURE_BIT 0x1000
Texturing really enabled.
#define FRAGPROG_BIT 0x2000
Fragment program enabled.
#define ATIFRAGSHADER_BIT 0x4000
ATI Fragment shader enabled.
#define CLAMPING_BIT 0x8000
Clamp colors to [0,1].
#define _SWRAST_NEW_RASTERMASK
#define RGBA_PIXEL_SIZE(TYPE)
Size of an RGBA pixel, in bytes, for given datatype.
#define FIXED_FRAC_BITS 11
#define FIXED_SHIFT FIXED_FRAC_BITS
#define FIXED_ONE (1 << FIXED_SHIFT)
#define FIXED_HALF (1 << (FIXED_SHIFT-1))
#define FIXED_FRAC_MASK (FIXED_ONE - 1)
#define FIXED_INT_MASK (~FIXED_FRAC_MASK)
#define FIXED_EPSILON 1
#define FIXED_SCALE ((float) FIXED_ONE)
#define FIXED_DBL_SCALE ((double) FIXED_ONE)
#define FloatToFixed(X) (IROUND((X) * FIXED_SCALE))
#define FixedToDouble(X) ((X) * (1.0 / FIXED_DBL_SCALE))
#define IntToFixed(I) ((I) << FIXED_SHIFT)
#define FixedToInt(X) ((X) >> FIXED_SHIFT)
#define FixedToUns(X) (((unsigned int)(X)) >> FIXED_SHIFT)
#define FixedCeil(X) (((X) + FIXED_ONE - FIXED_EPSILON) & FIXED_INT_MASK)
#define FixedFloor(X) ((X) & FIXED_INT_MASK)
#define FixedToFloat(X) ((X) * (1.0F / FIXED_SCALE))
#define PosFloatToFixed(X) FloatToFixed(X)
#define SignedFloatToFixed(X) FloatToFixed(X)
#define ChanToFixed(X) (X)
#define FixedToChan(X) (X)
#define ATTRIB_LOOP_BEGIN
For looping over fragment attributes in the pointe, line triangle rasterizers.
#define ATTRIB_LOOP_END } }
Typedefs
typedef void(* texture_sample_func) (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
typedef void(* blend_func) (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
typedef void(* swrast_point_func) (struct gl_context *ctx, const SWvertex *)
typedef void(* swrast_line_func) (struct gl_context *ctx, const SWvertex *, const SWvertex *)
typedef void(* swrast_tri_func) (struct gl_context *ctx, const SWvertex *, const SWvertex *, const SWvertex *)
typedef void(* validate_texture_image_func) (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
typedef void(* FetchTexelFunc) (const struct swrast_texture_image *texImage, GLint col, GLint row, GLint img, GLfloat *texelOut)
Fetch a texel from texture image at given position.
Functions
static struct swrast_texture_image * swrast_texture_image (struct gl_texture_image *img)
cast wrapper
static const struct swrast_texture_image * swrast_texture_image_const (const struct gl_texture_image *img)
cast wrapper
static struct swrast_renderbuffer * swrast_renderbuffer (struct gl_renderbuffer *img)
cast wrapper
void _swrast_validate_derived (struct gl_context *ctx)
void _swrast_update_texture_samplers (struct gl_context *ctx)
static SWcontext * SWRAST_CONTEXT (struct gl_context *ctx)
Return SWcontext for the given struct gl_context.
static const SWcontext * CONST_SWRAST_CONTEXT (const struct gl_context *ctx)
const version of above
static void swrast_render_start (struct gl_context *ctx)
Called prior to framebuffer reading/writing.
static void swrast_render_finish (struct gl_context *ctx)
Called after framebuffer reading/writing.
void _swrast_span_render_start (struct gl_context *ctx)
called via swrast->Driver.SpanRenderStart()
void _swrast_span_render_finish (struct gl_context *ctx)
called via swrast->Driver.SpanRenderFinish()
void _swrast_map_textures (struct gl_context *ctx)
Map all textures for reading prior to software rendering.
void _swrast_unmap_textures (struct gl_context *ctx)
Unmap all textures for reading prior to software rendering.
unsigned int _swrast_teximage_slice_height (struct gl_texture_image *texImage)
void _swrast_map_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
void _swrast_unmap_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
void _swrast_map_renderbuffers (struct gl_context *ctx)
Map the renderbuffers we'll use for tri/line/point rendering.
void _swrast_unmap_renderbuffers (struct gl_context *ctx)
Unmap renderbuffers after rendering.
static GLubyte * _swrast_pixel_address (struct gl_renderbuffer *rb, GLint x, GLint y)
Return the address of a pixel value in a mapped renderbuffer.
Detailed Description
Software rasterization context and private types.
Author
Keith Whitwell keith.nosp@m.w@vm.nosp@m.ware..nosp@m.com
Macro Definition Documentation
_SWRAST_NEW_RASTERMASK
#define _SWRAST_NEW_RASTERMASK
Value:
(_NEW_BUFFERS|  \
                                _NEW_SCISSOR|   \
                                _NEW_COLOR|     \
                                _NEW_DEPTH|     \
                                _NEW_FOG|       \
                                _NEW_PROGRAM|   \
                                _NEW_STENCIL|   \
                                _NEW_TEXTURE|   \
                                _NEW_VIEWPORT|  \
                                _NEW_DEPTH)
Referenced by _swrast_validate_derived().
ATTRIB_LOOP_BEGIN
#define ATTRIB_LOOP_BEGIN
Value:
{                                                     \
      GLuint a;                                          \
      for (a = 0; a < swrast->_NumActiveAttribs; a++) {  \
         const GLuint attr = swrast->_ActiveAttribs[a];
For looping over fragment attributes in the pointe, line triangle rasterizers.
Referenced by for(), if(), interpolate_active_attribs(), large_point(), line(), NAME(), pixel_point(), plot(), smooth_point(), and sprite_point().
ATTRIB_LOOP_END
#define ATTRIB_LOOP_END } }
Referenced by for(), if(), interpolate_active_attribs(), large_point(), line(), NAME(), pixel_point(), plot(), smooth_point(), and sprite_point().
ChanToFixed
#define ChanToFixed (X) (X)
Referenced by large_point(), NAME(), smooth_point(), and sprite_point().
FIXED_DBL_SCALE
#define FIXED_DBL_SCALE ((double) FIXED_ONE)
FIXED_EPSILON
#define FIXED_EPSILON 1
Referenced by NAME().
FIXED_FRAC_BITS
#define FIXED_FRAC_BITS 11
FIXED_FRAC_MASK
#define FIXED_FRAC_MASK (FIXED_ONE - 1)
FIXED_HALF
#define FIXED_HALF (1 << (FIXED_SHIFT-1))
Referenced by NAME().
FIXED_INT_MASK
#define FIXED_INT_MASK (~FIXED_FRAC_MASK)
FIXED_ONE
#define FIXED_ONE (1 << FIXED_SHIFT)
Referenced by NAME().
FIXED_SCALE
#define FIXED_SCALE ((float) FIXED_ONE)
Referenced by NAME().
FIXED_SHIFT
#define FIXED_SHIFT FIXED_FRAC_BITS
Referenced by NAME().
FixedCeil
#define FixedCeil (X) (((X) + FIXED_ONE - FIXED_EPSILON) & FIXED_INT_MASK)
Referenced by NAME().
FixedFloor
#define FixedFloor (X) ((X) & FIXED_INT_MASK)
Referenced by NAME().
FixedToChan
#define FixedToChan (X) (X)
Referenced by interpolate_int_colors().
FixedToDouble
#define FixedToDouble (X) ((X) * (1.0 / FIXED_DBL_SCALE))
FixedToFloat
#define FixedToFloat (X) ((X) * (1.0F / FIXED_SCALE))
Referenced by _swrast_alpha_test(), interpolate_float_colors(), and NAME().
FixedToInt
#define FixedToInt (X) ((X) >> FIXED_SHIFT)
Referenced by _swrast_alpha_test(), _swrast_span_interpolate_z(), interpolate_int_colors(), and NAME().
FixedToUns
#define FixedToUns (X) (((unsigned int)(X)) >> FIXED_SHIFT)
FloatToFixed
#define FloatToFixed (X) (IROUND((X) * FIXED_SCALE))
Referenced by _swrast_span_default_attribs(), large_point(), NAME(), smooth_point(), and sprite_point().
IntToFixed
#define IntToFixed (I) ((I) << FIXED_SHIFT)
Referenced by _swrast_span_default_attribs().
PosFloatToFixed
#define PosFloatToFixed (X) FloatToFixed(X)
RGBA_PIXEL_SIZE
#define RGBA_PIXEL_SIZE (TYPE)
Value:
((TYPE == GL_UNSIGNED_BYTE) ? 4 * sizeof(GLubyte) :      \
          ((TYPE == GL_UNSIGNED_SHORT) ? 4 * sizeof(GLushort)     \
           : 4 * sizeof(GLfloat)))
Size of an RGBA pixel, in bytes, for given datatype.
SignedFloatToFixed
#define SignedFloatToFixed (X) FloatToFixed(X)
Referenced by NAME().
Typedef Documentation
blend_func
typedef void(* blend_func) (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
FetchTexelFunc
typedef void(* FetchTexelFunc) (const struct swrast_texture_image *texImage, GLint col, GLint row, GLint img, GLfloat *texelOut)
Fetch a texel from texture image at given position.
swrast_line_func
typedef void(* swrast_line_func) (struct gl_context *ctx, const SWvertex *, const SWvertex *)
swrast_point_func
typedef void(* swrast_point_func) (struct gl_context *ctx, const SWvertex *)
swrast_tri_func
typedef void(* swrast_tri_func) (struct gl_context *ctx, const SWvertex *, const SWvertex *, const SWvertex *)
texture_sample_func
typedef void(* texture_sample_func) (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
validate_texture_image_func
typedef void(* validate_texture_image_func) (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
Function Documentation
_swrast_map_renderbuffers()
void _swrast_map_renderbuffers (struct gl_context * ctx)
Map the renderbuffers we'll use for tri/line/point rendering.
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::DrawBuffer, find_renderbuffer_colortype(), GLuint, map_attachment(), and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _swrast_span_render_start(), and swrast_render_finish().
_swrast_map_texture()
void _swrast_map_texture (struct gl_context * ctx, struct gl_texture_object * texObj)
References gl_texture_object::BaseLevel, swrast_texture_image::Buffer, gl_context::Driver, GLuint, gl_texture_image::Height, gl_texture_object::Image, swrast_texture_image::ImageSlices, dd_function_table::MapTextureImage, MAX_TEXTURE_LEVELS, swrast_texture_image::RowStride, swrast_texture_image(), gl_texture_object::Target, texture_slices(), and gl_texture_image::Width.
Referenced by _swrast_map_textures(), and swrast_render_finish().
_swrast_map_textures()
void _swrast_map_textures (struct gl_context * ctx)
Map all textures for reading prior to software rendering.
References gl_texture_unit::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, _swrast_map_texture(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_span_render_start(), and swrast_render_finish().
_swrast_pixel_address()
static GLubyte* _swrast_pixel_address (struct gl_renderbuffer * rb, GLint x, GLint y) inline static
Return the address of a pixel value in a mapped renderbuffer.
References _mesa_get_format_bytes(), gl_renderbuffer::Format, gl_renderbuffer::Height, swrast_renderbuffer::Map, swrast_renderbuffer::RowStride, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by _swrast_depth_bounds_test(), _swrast_depth_test_span(), _swrast_put_row(), _swrast_read_depth_span_float(), _swrast_read_rgba_span(), _swrast_read_stencil_span(), _swrast_stencil_and_ztest_span(), _swrast_write_stencil_span(), _swrast_write_zoomed_z_span(), draw_depth_stencil_pixels(), fast_draw_depth_stencil(), get_row(), get_s8_values(), get_values(), get_z32_values(), NAME(), put_s8_values(), put_values(), and put_z32_values().
_swrast_span_render_finish()
void _swrast_span_render_finish (struct gl_context * ctx)
called via swrast->Driver.SpanRenderFinish()
References _swrast_unmap_renderbuffers(), and _swrast_unmap_textures().
Referenced by _swrast_CreateContext(), and swrast_render_finish().
_swrast_span_render_start()
void _swrast_span_render_start (struct gl_context * ctx)
called via swrast->Driver.SpanRenderStart()
References _swrast_map_renderbuffers(), and _swrast_map_textures().
Referenced by _swrast_CreateContext(), and swrast_render_finish().
_swrast_teximage_slice_height()
unsigned int _swrast_teximage_slice_height (struct gl_texture_image * texImage)
References gl_texture_image::Height, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by _swrast_alloc_texture_image_buffer(), and swrast_render_finish().
_swrast_unmap_renderbuffers()
void _swrast_unmap_renderbuffers (struct gl_context * ctx)
Unmap renderbuffers after rendering.
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::DrawBuffer, GLuint, gl_renderbuffer_attachment::Renderbuffer, and unmap_attachment().
Referenced by _swrast_span_render_finish(), and swrast_render_finish().
_swrast_unmap_texture()
void _swrast_unmap_texture (struct gl_context * ctx, struct gl_texture_object * texObj)
References gl_texture_object::BaseLevel, swrast_texture_image::Buffer, gl_context::Driver, GLuint, gl_texture_object::Image, swrast_texture_image::ImageSlices, MAX_TEXTURE_LEVELS, swrast_texture_image(), gl_texture_object::Target, texture_slices(), and dd_function_table::UnmapTextureImage.
Referenced by _swrast_unmap_textures(), and swrast_render_finish().
_swrast_unmap_textures()
void _swrast_unmap_textures (struct gl_context * ctx)
Unmap all textures for reading prior to software rendering.
References gl_texture_unit::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, _swrast_unmap_texture(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_span_render_finish(), and swrast_render_finish().
_swrast_update_texture_samplers()
void _swrast_update_texture_samplers (struct gl_context * ctx)
References gl_texture_unit::_Current, _mesa_update_fetch_functions(), _swrast_choose_texture_sample_func(), GLuint, swrast, SWRAST_CONTEXT(), gl_context::Texture, SWcontext::TextureSample, and gl_texture_attrib::Unit.
Referenced by _swrast_validate_derived().
_swrast_validate_derived()
void _swrast_validate_derived (struct gl_context * ctx)
References _NEW_COLOR, _NEW_DEPTH, _NEW_FOG, _NEW_HINT, _NEW_LIGHT, _NEW_POLYGON, _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, _NEW_TEXTURE, _swrast_invalidate_state(), _SWRAST_NEW_RASTERMASK, _SWRAST_NEW_TEXTURE_ENV_MODE, _swrast_update_active_attribs(), _swrast_update_deferred_texture(), _swrast_update_fog_hint(), _swrast_update_fog_state(), _swrast_update_fragment_program(), _swrast_update_polygon(), _swrast_update_rasterflags(), _swrast_update_specular_vertex_add(), _swrast_update_texture_env(), _swrast_update_texture_samplers(), SWcontext::InvalidateState, SWcontext::NewState, SWcontext::StateChanges, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_Bitmap(), _swrast_BlitFramebuffer(), _swrast_Clear(), _swrast_CopyPixels(), _swrast_DrawPixels(), _swrast_validate_blend_func(), _swrast_validate_line(), _swrast_validate_point(), and _swrast_validate_triangle().
CONST_SWRAST_CONTEXT()
static const SWcontext* CONST_SWRAST_CONTEXT (const struct gl_context * ctx) inline static
const version of above
References gl_context::swrast_context.
Referenced by _swrast_fog_rgba_span().
SWRAST_CONTEXT()
static SWcontext* SWRAST_CONTEXT (struct gl_context * ctx) inline static
Return SWcontext for the given struct gl_context.
References gl_context::swrast_context.
Referenced by _swrast_add_spec_terms_line(), _swrast_add_spec_terms_point(), _swrast_add_spec_terms_triangle(), _swrast_allow_pixel_fog(), _swrast_allow_vertex_fog(), _swrast_Bitmap(), _swrast_blend_span(), _swrast_BlitFramebuffer(), _swrast_choose_aa_line_function(), _swrast_choose_blend_func(), _swrast_choose_line(), _swrast_choose_point(), _swrast_choose_triangle(), _swrast_Clear(), _swrast_CopyPixels(), _swrast_culltriangle(), _swrast_DestroyContext(), _swrast_DrawPixels(), _swrast_feedback_line(), _swrast_flush(), _swrast_GetDeviceDriverReference(), _swrast_invalidate_state(), _swrast_InvalidateState(), _swrast_Line(), _swrast_Point(), _swrast_Quad(), _swrast_render_finish(), _swrast_render_primitive(), _swrast_render_start(), _swrast_ResetLineStipple(), _swrast_set_aa_triangle_function(), _swrast_SetFacing(), _swrast_span_default_attribs(), _swrast_stencil_and_ztest_span(), _swrast_texture_span(), _swrast_Triangle(), _swrast_update_active_attribs(), _swrast_update_deferred_texture(), _swrast_update_fog_hint(), _swrast_update_fog_state(), _swrast_update_polygon(), _swrast_update_rasterflags(), _swrast_update_specular_vertex_add(), _swrast_update_texture_env(), _swrast_update_texture_samplers(), _swrast_validate_blend_func(), _swrast_validate_derived(), _swrast_validate_line(), _swrast_validate_point(), _swrast_validate_triangle(), _swrast_write_rgba_span(), _swrast_write_stencil_span(), add_specular(), compute_stipple_mask(), do_stencil_test(), fast_draw_rgba_pixels(), fetch_texel(), fetch_texel_deriv(), fetch_texel_lod(), for(), if(), interpolate_active_attribs(), large_point(), line(), NAME(), pixel_point(), plot(), run_program(), smooth_point(), sprite_point(), swrast_render_finish(), swrast_render_start(), texture_combine(), and zoom_span().
swrast_render_finish()
static void swrast_render_finish (struct gl_context * ctx) inline static
Called after framebuffer reading/writing.
References _swrast_map_renderbuffers(), _swrast_map_texture(), _swrast_map_textures(), _swrast_span_render_finish(), _swrast_span_render_start(), _swrast_teximage_slice_height(), _swrast_unmap_renderbuffers(), _swrast_unmap_texture(), _swrast_unmap_textures(), SWcontext::Driver, swrast_device_driver::SpanRenderFinish, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_Bitmap(), _swrast_CopyPixels(), _swrast_DrawPixels(), and draw_rgba_pixels().
swrast_render_start()
static void swrast_render_start (struct gl_context * ctx) inline static
Called prior to framebuffer reading/writing.
For drivers that rely on swrast for fallback rendering, this is the driver's opportunity to map renderbuffers and textures.
References SWcontext::Driver, swrast_device_driver::SpanRenderStart, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_Bitmap(), _swrast_CopyPixels(), _swrast_DrawPixels(), and draw_rgba_pixels().
swrast_renderbuffer()
static struct swrast_renderbuffer* swrast_renderbuffer (struct gl_renderbuffer * img) static
cast wrapper
Referenced by _swrast_CopyPixels(), _swrast_map_soft_renderbuffer(), _swrast_pixel_address(), _swrast_read_rgba_span(), fast_draw_depth_stencil(), find_renderbuffer_colortype(), get_s8_values(), get_z32_values(), map_attachment(), map_readbuffer(), put_z32_values(), soft_renderbuffer_delete(), soft_renderbuffer_storage(), unmap_attachment(), and update_wrapper().
swrast_texture_image()
static struct swrast_texture_image* swrast_texture_image (struct gl_texture_image * img) static
cast wrapper
Referenced by _mesa_update_fetch_functions(), _swrast_alloc_texture_image_buffer(), _swrast_free_texture_image_buffer(), _swrast_init_texture_image(), _swrast_map_teximage(), _swrast_map_texture(), _swrast_unmap_texture(), and update_wrapper().
swrast_texture_image_const()
static const struct swrast_texture_image* swrast_texture_image_const (const struct gl_texture_image * img) static
cast wrapper
Referenced by _swrast_choose_texture_sample_func(), _swrast_choose_triangle(), fetch_texel_deriv(), interpolate_texcoords(), linear_texel_locations(), nearest_texel_location(), opt_sample_rgb_2d(), opt_sample_rgba_2d(), sample_1d_array_linear(), sample_1d_array_nearest(), sample_1d_linear(), sample_1d_nearest(), sample_2d_array_linear(), sample_2d_array_nearest(), sample_2d_ewa(), sample_2d_linear(), sample_2d_linear_repeat(), sample_2d_nearest(), sample_3d_linear(), sample_3d_nearest(), sample_depth_texture(), sample_lambda_2d(), sample_lambda_2d_aniso(), sample_linear_2d(), sample_linear_rect(), and sample_nearest_rect().