Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_copypix.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/condrender.h"
#include "main/macros.h"
#include "main/blit.h"
#include "main/pixeltransfer.h"
#include "main/imports.h"
#include "s_context.h"
#include "s_depth.h"
#include "s_span.h"
#include "s_stencil.h"
#include "s_zoom.h"
Functions
static GLboolean regions_overlap (GLint srcx, GLint srcy, GLint dstx, GLint dsty, GLint width, GLint height, GLfloat zoomX, GLfloat zoomY)
Determine if there's overlap in an image copy.
static void copy_rgba_pixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLint width, GLint height, GLint destx, GLint desty)
RGBA copypixels.
static void scale_and_bias_z (struct gl_context *ctx, GLuint width, const GLfloat depth[], GLuint z[])
Convert floating point Z values to integer Z values with pixel transfer's Z scale and bias.
static void copy_depth_pixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLint width, GLint height, GLint destx, GLint desty)
static void copy_stencil_pixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLint width, GLint height, GLint destx, GLint desty)
GLboolean swrast_fast_copy_pixels (struct gl_context *ctx, struct gl_framebuffer *srcFb, struct gl_framebuffer *dstFb, GLint srcX, GLint srcY, GLsizei width, GLsizei height, GLint dstX, GLint dstY, GLenum type)
Try to do a fast 1:1 blit with memcpy.
static struct gl_renderbuffer * map_readbuffer (struct gl_context *ctx, GLenum type)
Find/map the renderbuffer that we'll be reading from.
void _swrast_CopyPixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint destx, GLint desty, GLenum type)
Do software-based glCopyPixels.
Function Documentation
_swrast_CopyPixels()
void _swrast_CopyPixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint destx, GLint desty, GLenum type)
Do software-based glCopyPixels.
By time we get here, all parameters will have been error-checked.
References gl_context::_ImageTransferState, _mesa_check_conditional_render(), _mesa_problem(), _swrast_validate_derived(), copy_depth_pixels(), copy_rgba_pixels(), copy_stencil_pixels(), gl_context::DrawBuffer, gl_context::Driver, swrast_renderbuffer::Map, map_readbuffer(), SWcontext::NewState, gl_context::Pixel, gl_context::ReadBuffer, swrast, SWRAST_CONTEXT(), swrast_fast_copy_pixels(), swrast_render_finish(), swrast_render_start(), swrast_renderbuffer(), dd_function_table::UnmapRenderbuffer, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
copy_depth_pixels()
static void copy_depth_pixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLint width, GLint height, GLint destx, GLint desty) static
References _mesa_error(), _swrast_read_depth_span_float(), _swrast_span_default_attribs(), _swrast_write_rgba_span(), _swrast_write_zoomed_depth_span(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, BUFFER_DEPTH, gl_context::DrawBuffer, sw_span::end, INIT_SPAN(), gl_context::Pixel, gl_context::ReadBuffer, regions_overlap(), gl_renderbuffer_attachment::Renderbuffer, scale_and_bias_z(), span, SPAN_Z, sw_span::x, sw_span::y, sw_span_arrays::z, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_CopyPixels().
copy_rgba_pixels()
static void copy_rgba_pixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLint width, GLint height, GLint destx, GLint desty) static
RGBA copypixels.
References gl_framebuffer::_ColorReadBuffer, gl_context::_ImageTransferState, _mesa_apply_rgba_transfer_ops(), _mesa_error(), _swrast_read_rgba_span(), _swrast_span_default_attribs(), _swrast_write_rgba_span(), _swrast_write_zoomed_rgba_span(), sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, sw_span_arrays::attribs, CHAN_TYPE, sw_span_arrays::ChanType, gl_context::DrawBuffer, sw_span::end, GLuint, INIT_SPAN(), gl_context::Pixel, gl_context::ReadBuffer, regions_overlap(), span, SPAN_RGBA, SWRAST_MAX_WIDTH, sw_span::x, sw_span::y, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_CopyPixels().
copy_stencil_pixels()
static void copy_stencil_pixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLint width, GLint height, GLint destx, GLint desty) static
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _swrast_read_stencil_span(), _swrast_write_stencil_span(), _swrast_write_zoomed_stencil_span(), gl_framebuffer::Attachment, BUFFER_STENCIL, gl_context::DrawBuffer, gl_context::Pixel, gl_context::ReadBuffer, regions_overlap(), gl_renderbuffer_attachment::Renderbuffer, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_CopyPixels().
map_readbuffer()
static struct gl_renderbuffer* map_readbuffer (struct gl_context * ctx, GLenum type) static
Find/map the renderbuffer that we'll be reading from.
The swrast_render_start() function only maps the drawing buffers, not the read buffer.
References gl_framebuffer::_ColorReadBufferIndex, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Height, swrast_renderbuffer::Map, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, swrast_renderbuffer::RowStride, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by _swrast_CopyPixels().
regions_overlap()
static GLboolean regions_overlap (GLint srcx, GLint srcy, GLint dstx, GLint dsty, GLint width, GLint height, GLfloat zoomX, GLfloat zoomY) static
Determine if there's overlap in an image copy.
This test also compensates for the fact that copies are done from bottom to top and overlaps can sometimes be handled correctly without making a temporary image copy.
Returns
GL_TRUE if the regions overlap, GL_FALSE otherwise.
References _mesa_regions_overlap(), and F.
Referenced by copy_depth_pixels(), copy_rgba_pixels(), and copy_stencil_pixels().
scale_and_bias_z()
static void scale_and_bias_z (struct gl_context * ctx, GLuint width, const GLfloat depth[], GLuint z[]) static
Convert floating point Z values to integer Z values with pixel transfer's Z scale and bias.
References gl_framebuffer::_DepthMax, gl_framebuffer::_DepthMaxF, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_context::DrawBuffer, GLuint, and gl_context::Pixel.
Referenced by copy_depth_pixels().
swrast_fast_copy_pixels()
GLboolean swrast_fast_copy_pixels (struct gl_context * ctx, struct gl_framebuffer * srcFb, struct gl_framebuffer * dstFb, GLint srcX, GLint srcY, GLsizei width, GLsizei height, GLint dstX, GLint dstY, GLenum type)
Try to do a fast 1:1 blit with memcpy.
Returns
GL_TRUE if successful, GL_FALSE otherwise.
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_format_bytes(), _mesa_is_format_packed_depth_stencil(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Xmax, gl_framebuffer::_Ymax, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, gl_framebuffer::Height, dd_function_table::MapRenderbuffer, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::UnmapRenderbuffer, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _swrast_BlitFramebuffer(), and _swrast_CopyPixels().