Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_context.c File Reference
#include "main/imports.h"
#include "main/bufferobj.h"
#include "main/mtypes.h"
#include "main/samplerobj.h"
#include "main/teximage.h"
#include "program/prog_parameter.h"
#include "program/prog_statevars.h"
#include "swrast.h"
#include "s_blend.h"
#include "s_context.h"
#include "s_lines.h"
#include "s_points.h"
#include "s_span.h"
#include "s_texfetch.h"
#include "s_triangle.h"
#include "s_texfilter.h"
Macros
#define _SWRAST_NEW_DERIVED
#define _SWRAST_NEW_TRIANGLE
#define _SWRAST_NEW_LINE
#define _SWRAST_NEW_POINT
#define _SWRAST_NEW_TEXTURE_SAMPLE_FUNC _NEW_TEXTURE
#define _SWRAST_NEW_TEXTURE_ENV_MODE _NEW_TEXTURE
#define _SWRAST_NEW_BLEND_FUNC _NEW_COLOR
#define SWRAST_DEBUG 0
#define SWRAST_DEBUG_VERTICES 0
Functions
static void _swrast_update_rasterflags (struct gl_context *ctx)
Recompute the value of swrast->_RasterMask, etc.
static void _swrast_update_polygon (struct gl_context *ctx)
Examine polygon cull state to compute the _BackfaceCullSign field.
static void _swrast_update_fog_hint (struct gl_context *ctx)
Update the _PreferPixelFog field to indicate if we need to compute fog blend factors (from the fog coords) per-fragment.
static void _swrast_update_texture_env (struct gl_context *ctx)
Update the swrast->_TextureCombinePrimary flag.
static void _swrast_update_deferred_texture (struct gl_context *ctx)
Determine if we can defer texturing/shading until after Z/stencil testing.
static void _swrast_update_fog_state (struct gl_context *ctx)
Update swrast->_FogColor and swrast->_FogEnable values.
static void _swrast_update_fragment_program (struct gl_context *ctx, GLbitfield newState)
Update state for running fragment programs.
static void _swrast_update_specular_vertex_add (struct gl_context *ctx)
See if we can do early diffuse+specular (primary+secondary) color add per vertex instead of per-fragment.
static void _swrast_validate_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Stub for swrast->Triangle to select a true triangle function after a state change.
static void _swrast_validate_line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
Called via swrast->Line.
static void _swrast_validate_point (struct gl_context *ctx, const SWvertex *v0)
Called via swrast->Point.
static void _swrast_validate_blend_func (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Called via swrast->BlendFunc.
static void _swrast_sleep (struct gl_context *ctx, GLbitfield new_state)
static void _swrast_invalidate_state (struct gl_context *ctx, GLbitfield new_state)
void _swrast_update_texture_samplers (struct gl_context *ctx)
static void _swrast_update_active_attribs (struct gl_context *ctx)
Update swrast->_ActiveAttribs, swrast->_NumActiveAttribs, swrast->_ActiveAtttribMask.
void _swrast_validate_derived (struct gl_context *ctx)
void _swrast_Quad (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2, const SWvertex *v3)
void _swrast_Triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_Line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
void _swrast_Point (struct gl_context *ctx, const SWvertex *v0)
void _swrast_InvalidateState (struct gl_context *ctx, GLbitfield new_state)
void _swrast_ResetLineStipple (struct gl_context *ctx)
void _swrast_SetFacing (struct gl_context *ctx, GLuint facing)
Indicates front/back facing for subsequent points/lines when drawing unfilled polygons.
void _swrast_allow_vertex_fog (struct gl_context *ctx, GLboolean value)
void _swrast_allow_pixel_fog (struct gl_context *ctx, GLboolean value)
static void init_program_native_limits (struct gl_program_constants *prog)
Initialize native program limits by copying the logical limits.
GLboolean _swrast_CreateContext (struct gl_context *ctx)
void _swrast_DestroyContext (struct gl_context *ctx)
struct swrast_device_driver * _swrast_GetDeviceDriverReference (struct gl_context *ctx)
void _swrast_flush (struct gl_context *ctx)
void _swrast_render_primitive (struct gl_context *ctx, GLenum prim)
void _swrast_span_render_start (struct gl_context *ctx)
called via swrast->Driver.SpanRenderStart()
void _swrast_span_render_finish (struct gl_context *ctx)
called via swrast->Driver.SpanRenderFinish()
void _swrast_render_start (struct gl_context *ctx)
void _swrast_render_finish (struct gl_context *ctx)
void _swrast_print_vertex (struct gl_context *ctx, const SWvertex *v)
Macro Definition Documentation
_SWRAST_NEW_BLEND_FUNC
#define _SWRAST_NEW_BLEND_FUNC _NEW_COLOR
Referenced by _swrast_invalidate_state().
_SWRAST_NEW_DERIVED
#define _SWRAST_NEW_DERIVED
Value:
(_SWRAST_NEW_RASTERMASK |       \
                             _NEW_PROGRAM_CONSTANTS |   \
                             _NEW_TEXTURE |             \
                             _NEW_HINT |                \
                             _NEW_POLYGON )
_SWRAST_NEW_LINE
#define _SWRAST_NEW_LINE
Value:
(_SWRAST_NEW_DERIVED |          \
                          _NEW_RENDERMODE|              \
                          _NEW_LINE|                    \
                          _NEW_TEXTURE|                 \
                          _NEW_LIGHT|                   \
                          _NEW_FOG|                     \
                          _NEW_DEPTH |                  \
                          _MESA_NEW_SEPARATE_SPECULAR)
Referenced by _swrast_CreateContext().
_SWRAST_NEW_POINT
#define _SWRAST_NEW_POINT
Value:
(_SWRAST_NEW_DERIVED |  \
                           _NEW_RENDERMODE |            \
                           _NEW_POINT |                 \
                           _NEW_TEXTURE |               \
                           _NEW_LIGHT |                 \
                           _NEW_FOG |                   \
                           _MESA_NEW_SEPARATE_SPECULAR)
Referenced by _swrast_CreateContext().
_SWRAST_NEW_TEXTURE_ENV_MODE
#define _SWRAST_NEW_TEXTURE_ENV_MODE _NEW_TEXTURE
Referenced by _swrast_validate_derived().
_SWRAST_NEW_TEXTURE_SAMPLE_FUNC
#define _SWRAST_NEW_TEXTURE_SAMPLE_FUNC _NEW_TEXTURE
Referenced by _swrast_invalidate_state().
_SWRAST_NEW_TRIANGLE
#define _SWRAST_NEW_TRIANGLE
Value:
(_SWRAST_NEW_DERIVED |          \
                              _NEW_RENDERMODE|                  \
                              _NEW_POLYGON|                     \
                              _NEW_DEPTH|                       \
                              _NEW_STENCIL|                     \
                              _NEW_COLOR|                       \
                              _NEW_TEXTURE|                     \
                              _SWRAST_NEW_RASTERMASK|           \
                              _NEW_LIGHT|                       \
                              _NEW_FOG |                        \
                              _MESA_NEW_SEPARATE_SPECULAR)
Referenced by _swrast_CreateContext().
SWRAST_DEBUG
#define SWRAST_DEBUG 0
Referenced by _swrast_allow_pixel_fog(), _swrast_allow_vertex_fog(), _swrast_CreateContext(), _swrast_DestroyContext(), _swrast_InvalidateState(), _swrast_Line(), _swrast_Point(), _swrast_Quad(), _swrast_ResetLineStipple(), and _swrast_Triangle().
SWRAST_DEBUG_VERTICES
#define SWRAST_DEBUG_VERTICES 0
Referenced by _swrast_print_vertex().
Function Documentation
_swrast_allow_pixel_fog()
void _swrast_allow_pixel_fog (struct gl_context * ctx, GLboolean value)
References _mesa_debug(), _NEW_HINT, SWcontext::AllowPixelFog, SWcontext::InvalidateState, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_allow_vertex_fog()
void _swrast_allow_vertex_fog (struct gl_context * ctx, GLboolean value)
References _mesa_debug(), _NEW_HINT, SWcontext::AllowVertexFog, SWcontext::InvalidateState, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_CreateContext()
GLboolean _swrast_CreateContext (struct gl_context * ctx)
References _mesa_debug(), _swrast_choose_line(), _swrast_choose_point(), _swrast_choose_triangle(), _swrast_DestroyContext(), _SWRAST_NEW_LINE, _SWRAST_NEW_POINT, _SWRAST_NEW_TRIANGLE, _swrast_sleep(), _swrast_span_render_finish(), _swrast_span_render_start(), _swrast_validate_blend_func(), _swrast_validate_line(), _swrast_validate_point(), _swrast_validate_triangle(), SWcontext::AllowPixelFog, SWcontext::AllowVertexFog, sw_span::array, sw_span_arrays::attribs, SWcontext::BlendFunc, SWcontext::buf1, SWcontext::buf2, SWcontext::buf3, SWcontext::buf4, CHAN_TYPE, sw_span_arrays::ChanType, SWcontext::choose_line, SWcontext::choose_point, SWcontext::choose_triangle, gl_context::Const, SWcontext::Driver, sw_span::end, sw_span::facing, GLuint, init_program_native_limits(), SWcontext::InvalidateLineMask, SWcontext::InvalidatePointMask, SWcontext::InvalidateState, SWcontext::InvalidateTriangleMask, SWcontext::Line, gl_constants::Max3DTextureLevels, gl_constants::MaxCubeTextureLevels, gl_constants::MaxRenderbufferSize, gl_constants::MaxTextureLevels, gl_constants::MaxViewportHeight, gl_constants::MaxViewportWidth, SWcontext::NewState, SWcontext::Point, SWcontext::PointSpan, sw_span::primitive, gl_constants::Program, sw_span_arrays::rgba, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SWcontext::SpanArrays, swrast_device_driver::SpanRenderFinish, swrast_device_driver::SpanRenderStart, SWcontext::stencil_temp, swrast, gl_context::swrast_context, SWRAST_DEBUG, SWRAST_MAX_WIDTH, SWcontext::TextureSample, and SWcontext::Triangle.
_swrast_DestroyContext()
void _swrast_DestroyContext (struct gl_context * ctx)
References _mesa_debug(), SWcontext::buf1, SWcontext::buf2, SWcontext::buf3, SWcontext::buf4, SWcontext::SpanArrays, SWcontext::stencil_temp, swrast, gl_context::swrast_context, SWRAST_CONTEXT(), SWRAST_DEBUG, SWcontext::TexelBuffer, and SWcontext::ZoomedArrays.
Referenced by _swrast_CreateContext().
_swrast_flush()
void _swrast_flush (struct gl_context * ctx)
References _swrast_write_rgba_span(), sw_span::end, SWcontext::PointSpan, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_render_finish(), and _swrast_render_primitive().
_swrast_GetDeviceDriverReference()
struct swrast_device_driver* _swrast_GetDeviceDriverReference (struct gl_context * ctx)
References SWcontext::Driver, swrast, and SWRAST_CONTEXT().
_swrast_invalidate_state()
static void _swrast_invalidate_state (struct gl_context * ctx, GLbitfield new_state) static
References _SWRAST_NEW_BLEND_FUNC, _SWRAST_NEW_TEXTURE_SAMPLE_FUNC, _swrast_sleep(), _swrast_validate_blend_func(), _swrast_validate_line(), _swrast_validate_point(), _swrast_validate_triangle(), SWcontext::BlendFunc, GLuint, SWcontext::InvalidateLineMask, SWcontext::InvalidatePointMask, SWcontext::InvalidateState, SWcontext::InvalidateTriangleMask, SWcontext::Line, SWcontext::NewState, SWcontext::Point, SWcontext::StateChanges, swrast, SWRAST_CONTEXT(), SWcontext::TextureSample, and SWcontext::Triangle.
Referenced by _swrast_validate_derived().
_swrast_InvalidateState()
void _swrast_InvalidateState (struct gl_context * ctx, GLbitfield new_state)
References _mesa_debug(), SWcontext::InvalidateState, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_Line()
void _swrast_Line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1)
References _mesa_debug(), _swrast_print_vertex(), SWcontext::Line, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_Point()
void _swrast_Point (struct gl_context * ctx, const SWvertex * v0)
References _mesa_debug(), _swrast_print_vertex(), SWcontext::Point, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_print_vertex()
void _swrast_print_vertex (struct gl_context * ctx, const SWvertex * v)
References gl_texture_unit::_Current, _mesa_debug(), SWvertex::attrib, SWvertex::color, gl_context::Const, GLuint, gl_constants::MaxTextureCoordUnits, SWvertex::pointSize, SWRAST_DEBUG_VERTICES, gl_context::Texture, gl_texture_attrib::Unit, and VARYING_SLOT_CI.
Referenced by _swrast_Line(), _swrast_Point(), _swrast_Quad(), and _swrast_Triangle().
_swrast_Quad()
void _swrast_Quad (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2, const SWvertex * v3)
References _mesa_debug(), _swrast_print_vertex(), SWRAST_CONTEXT(), SWRAST_DEBUG, and SWcontext::Triangle.
_swrast_render_finish()
void _swrast_render_finish (struct gl_context * ctx)
References _swrast_flush(), gl_query_state::CurrentOcclusionObject, SWcontext::Driver, gl_context::Query, gl_query_object::Result, swrast_device_driver::SpanRenderFinish, swrast, SWRAST_CONTEXT(), and gl_query_object::Target.
_swrast_render_primitive()
void _swrast_render_primitive (struct gl_context * ctx, GLenum prim)
References _swrast_flush(), SWcontext::Primitive, swrast, and SWRAST_CONTEXT().
_swrast_render_start()
void _swrast_render_start (struct gl_context * ctx)
References SWcontext::Driver, sw_span::end, SWcontext::PointSpan, swrast_device_driver::SpanRenderStart, swrast, and SWRAST_CONTEXT().
_swrast_ResetLineStipple()
void _swrast_ResetLineStipple (struct gl_context * ctx)
References _mesa_debug(), SWcontext::StippleCounter, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_SetFacing()
void _swrast_SetFacing (struct gl_context * ctx, GLuint facing)
Indicates front/back facing for subsequent points/lines when drawing unfilled polygons.
Needed for two-side stencil.
References facing, SWcontext::PointLineFacing, and SWRAST_CONTEXT().
_swrast_sleep()
static void _swrast_sleep (struct gl_context * ctx, GLbitfield new_state) static
References void.
Referenced by _swrast_CreateContext(), and _swrast_invalidate_state().
_swrast_span_render_finish()
void _swrast_span_render_finish (struct gl_context * ctx)
called via swrast->Driver.SpanRenderFinish()
References _swrast_unmap_renderbuffers(), and _swrast_unmap_textures().
Referenced by _swrast_CreateContext(), and swrast_render_finish().
_swrast_span_render_start()
void _swrast_span_render_start (struct gl_context * ctx)
called via swrast->Driver.SpanRenderStart()
References _swrast_map_renderbuffers(), and _swrast_map_textures().
Referenced by _swrast_CreateContext(), and swrast_render_finish().
_swrast_Triangle()
void _swrast_Triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References _mesa_debug(), _swrast_print_vertex(), SWRAST_CONTEXT(), SWRAST_DEBUG, and SWcontext::Triangle.
_swrast_update_active_attribs()
static void _swrast_update_active_attribs (struct gl_context * ctx) static
Update swrast->_ActiveAttribs, swrast->_NumActiveAttribs, swrast->_ActiveAtttribMask.
References SWcontext::_ActiveAttribMask, SWcontext::_ActiveAttribs, gl_fragment_program_state::_Current, gl_ati_fragment_shader_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, SWcontext::_InterpMode, SWcontext::_NumActiveAttribs, _swrast_use_fragment_program(), gl_context::ATIFragmentShader, BITFIELD64_BIT, gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_light_attrib::Enabled, gl_context::Fog, gl_context::FragmentProgram, GLuint, gl_program::info, gl_context::Light, gl_light_attrib::Model, gl_light_attrib::ShadeModel, swrast, SWRAST_CONTEXT(), and gl_context::Texture.
Referenced by _swrast_validate_derived().
_swrast_update_deferred_texture()
static void _swrast_update_deferred_texture (struct gl_context * ctx) static
Determine if we can defer texturing/shading until after Z/stencil testing.
This potentially allows us to skip texturing/shading for lots of fragments.
References gl_fragment_program_state::_Current, SWcontext::_DeferredTexture, _swrast_use_fragment_program(), gl_colorbuffer_attrib::AlphaEnabled, gl_context::Color, gl_query_state::CurrentOcclusionObject, gl_context::FragmentProgram, gl_program::info, gl_context::Query, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_validate_derived().
_swrast_update_fog_hint()
static void _swrast_update_fog_hint (struct gl_context * ctx) static
Update the _PreferPixelFog field to indicate if we need to compute fog blend factors (from the fog coords) per-fragment.
References SWcontext::_PreferPixelFog, _swrast_use_fragment_program(), SWcontext::AllowPixelFog, SWcontext::AllowVertexFog, gl_hint_attrib::Fog, gl_context::Hint, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_validate_derived().
_swrast_update_fog_state()
static void _swrast_update_fog_state (struct gl_context * ctx) static
Update swrast->_FogColor and swrast->_FogEnable values.
References gl_fragment_program_state::_Current, SWcontext::_FogEnabled, _swrast_use_fragment_program(), gl_fog_attrib::Enabled, gl_context::Fog, gl_context::FragmentProgram, swrast, SWRAST_CONTEXT(), gl_program::Target, and void.
Referenced by _swrast_validate_derived().
_swrast_update_fragment_program()
static void _swrast_update_fragment_program (struct gl_context * ctx, GLbitfield newState) static
Update state for running fragment programs.
Basically, load the program parameters with current state values.
References gl_fragment_program_state::_Current, _swrast_use_fragment_program(), gl_context::FragmentProgram, and gl_program::Parameters.
Referenced by _swrast_validate_derived().
_swrast_update_polygon()
static void _swrast_update_polygon (struct gl_context * ctx) static
Examine polygon cull state to compute the _BackfaceCullSign field.
_BackfaceCullSign will be 0 if no culling, -1 if culling back-faces, and 1 if culling front-faces. The Polygon FrontFace state also factors in.
References SWcontext::_BackfaceCullSign, SWcontext::_BackfaceSign, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, F, gl_polygon_attrib::FrontFace, gl_context::Polygon, and SWRAST_CONTEXT().
Referenced by _swrast_validate_derived().
_swrast_update_rasterflags()
static void _swrast_update_rasterflags (struct gl_context * ctx) static
Recompute the value of swrast->_RasterMask, etc.
according to the current context. The _RasterMask field can be easily tested by drivers to determine certain basic GL state (does the primitive need stenciling, logic-op, fog, etc?).
References gl_stencil_attrib::_Enabled, gl_ati_fragment_shader_state::_Enabled, SWcontext::_FogEnabled, gl_texture_attrib::_MaxEnabledTexImageUnit, gl_framebuffer::_NumColorDrawBuffers, SWcontext::_RasterMask, _swrast_use_fragment_program(), gl_colorbuffer_attrib::AlphaEnabled, ALPHATEST_BIT, gl_context::ATIFragmentShader, ATIFRAGSHADER_BIT, BLEND_BIT, gl_colorbuffer_attrib::BlendEnabled, gl_colorbuffer_attrib::ClampFragmentColor, CLAMPING_BIT, CLIP_BIT, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_context::Const, gl_query_state::CurrentOcclusionObject, gl_context::Depth, DEPTH_BIT, gl_context::DrawBuffer, gl_scissor_attrib::EnableFlags, FOG_BIT, FRAGPROG_BIT, GLuint, gl_viewport_attrib::Height, gl_framebuffer::Height, LOGIC_OP_BIT, MASKING_BIT, gl_constants::MaxDrawBuffers, MULTI_DRAW_BIT, OCCLUSION_BIT, gl_context::Query, gl_context::Scissor, gl_context::Stencil, STENCIL_BIT, swrast, SWRAST_CONTEXT(), gl_depthbuffer_attrib::Test, gl_context::Texture, TEXTURE_BIT, gl_context::ViewportArray, gl_viewport_attrib::Width, gl_framebuffer::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
Referenced by _swrast_validate_derived().
_swrast_update_specular_vertex_add()
static void _swrast_update_specular_vertex_add (struct gl_context * ctx) static
See if we can do early diffuse+specular (primary+secondary) color add per vertex instead of per-fragment.
References gl_ati_fragment_shader_state::_Enabled, gl_texture_attrib::_MaxEnabledTexImageUnit, _swrast_use_fragment_program(), gl_context::ATIFragmentShader, gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_light_attrib::Enabled, gl_context::Fog, gl_context::Light, gl_light_attrib::Model, SWcontext::SpecularVertexAdd, swrast, SWRAST_CONTEXT(), and gl_context::Texture.
Referenced by _swrast_validate_derived().
_swrast_update_texture_env()
static void _swrast_update_texture_env (struct gl_context * ctx) static
Update the swrast->_TextureCombinePrimary flag.
References gl_texture_unit::_CurrentCombine, gl_tex_env_combine_state::_NumArgsRGB, SWcontext::_TextureCombinePrimary, gl_context::Const, GLuint, gl_constants::MaxTextureUnits, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, swrast, SWRAST_CONTEXT(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_validate_derived().
_swrast_update_texture_samplers()
void _swrast_update_texture_samplers (struct gl_context * ctx)
References gl_texture_unit::_Current, _mesa_update_fetch_functions(), _swrast_choose_texture_sample_func(), GLuint, swrast, SWRAST_CONTEXT(), gl_context::Texture, SWcontext::TextureSample, and gl_texture_attrib::Unit.
Referenced by _swrast_validate_derived().
_swrast_validate_blend_func()
static void _swrast_validate_blend_func (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Called via swrast->BlendFunc.
Examine GL state to choose a blending function, then call it.
References _swrast_choose_blend_func(), _swrast_validate_derived(), SWcontext::BlendFunc, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_CreateContext(), and _swrast_invalidate_state().
_swrast_validate_derived()
void _swrast_validate_derived (struct gl_context * ctx)
References _NEW_COLOR, _NEW_DEPTH, _NEW_FOG, _NEW_HINT, _NEW_LIGHT, _NEW_POLYGON, _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, _NEW_TEXTURE, _swrast_invalidate_state(), _SWRAST_NEW_RASTERMASK, _SWRAST_NEW_TEXTURE_ENV_MODE, _swrast_update_active_attribs(), _swrast_update_deferred_texture(), _swrast_update_fog_hint(), _swrast_update_fog_state(), _swrast_update_fragment_program(), _swrast_update_polygon(), _swrast_update_rasterflags(), _swrast_update_specular_vertex_add(), _swrast_update_texture_env(), _swrast_update_texture_samplers(), SWcontext::InvalidateState, SWcontext::NewState, SWcontext::StateChanges, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_Bitmap(), _swrast_BlitFramebuffer(), _swrast_Clear(), _swrast_CopyPixels(), _swrast_DrawPixels(), _swrast_validate_blend_func(), _swrast_validate_line(), _swrast_validate_point(), and _swrast_validate_triangle().
_swrast_validate_line()
static void _swrast_validate_line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1) static
Called via swrast->Line.
Examine current GL state and choose a software line routine. Then call it.
References _swrast_add_spec_terms_line(), _swrast_validate_derived(), SWcontext::choose_line, SWcontext::Line, SWcontext::SpecLine, SWcontext::SpecularVertexAdd, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_CreateContext(), and _swrast_invalidate_state().
_swrast_validate_point()
static void _swrast_validate_point (struct gl_context * ctx, const SWvertex * v0) static
Called via swrast->Point.
Examine current GL state and choose a software point routine. Then call it.
References _swrast_add_spec_terms_point(), _swrast_validate_derived(), SWcontext::choose_point, SWcontext::Point, SWcontext::SpecPoint, SWcontext::SpecularVertexAdd, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_CreateContext(), and _swrast_invalidate_state().
_swrast_validate_triangle()
static void _swrast_validate_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
Stub for swrast->Triangle to select a true triangle function after a state change.
References _swrast_add_spec_terms_triangle(), _swrast_validate_derived(), SWcontext::choose_triangle, SWcontext::SpecTriangle, SWcontext::SpecularVertexAdd, swrast, SWRAST_CONTEXT(), and SWcontext::Triangle.
Referenced by _swrast_CreateContext(), and _swrast_invalidate_state().
init_program_native_limits()
static void init_program_native_limits (struct gl_program_constants * prog) static
Initialize native program limits by copying the logical limits.
See comments in init_program_limits() in context.c
References gl_program_constants::MaxAddressRegs, gl_program_constants::MaxAluInstructions, gl_program_constants::MaxAttribs, gl_program_constants::MaxInstructions, gl_program_constants::MaxNativeAddressRegs, gl_program_constants::MaxNativeAluInstructions, gl_program_constants::MaxNativeAttribs, gl_program_constants::MaxNativeInstructions, gl_program_constants::MaxNativeParameters, gl_program_constants::MaxNativeTemps, gl_program_constants::MaxNativeTexIndirections, gl_program_constants::MaxNativeTexInstructions, gl_program_constants::MaxParameters, gl_program_constants::MaxTemps, gl_program_constants::MaxTexIndirections, and gl_program_constants::MaxTexInstructions.
Referenced by _swrast_CreateContext().