Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_drawpix.c File Reference
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/colormac.h"
#include "main/condrender.h"
#include "main/context.h"
#include "main/format_pack.h"
#include "main/format_utils.h"
#include "main/glformats.h"
#include "main/image.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/pack.h"
#include "main/pbo.h"
#include "main/pixeltransfer.h"
#include "main/state.h"
#include "s_context.h"
#include "s_span.h"
#include "s_stencil.h"
#include "s_zoom.h"
Functions
static void fast_draw_rgb_ubyte_pixels (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Handle a common case of drawing GL_RGB/GL_UNSIGNED_BYTE into a MESA_FORMAT_XRGB888 or MESA_FORMAT_ARGB888 renderbuffer.
static void fast_draw_rgba_ubyte_pixels (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Handle a common case of drawing GL_RGBA/GL_UNSIGNED_BYTE into a MESA_FORMAT_ARGB888 or MESA_FORMAT_xRGB888 renderbuffer.
static void fast_draw_generic_pixels (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Handle a common case of drawing a format/type combination that exactly matches the renderbuffer format.
static GLboolean fast_draw_rgba_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *userUnpack, const GLvoid *pixels)
Try to do a fast and simple RGB(a) glDrawPixels.
static void draw_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
static void draw_depth_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
static void draw_rgba_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Draw RGBA image.
static void fast_draw_depth_stencil (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Draw depth+stencil values into a MESA_FORAMT_Z24_S8 or MESA_FORMAT_Z24_UNORM_S8_UINT renderbuffer.
static void draw_depth_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
This is a bit different from drawing GL_DEPTH_COMPONENT pixels.
void _swrast_DrawPixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Execute software-based glDrawPixels.
Function Documentation
_swrast_DrawPixels()
void _swrast_DrawPixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels)
Execute software-based glDrawPixels.
By time we get here, all error checking will have been done.
References _mesa_check_conditional_render(), _mesa_map_pbo_source(), _mesa_set_vp_override(), _mesa_unmap_pbo_source(), _mesa_update_state(), gl_vertex_program_state::_Overriden, _swrast_validate_derived(), draw_depth_pixels(), draw_depth_stencil_pixels(), draw_rgba_pixels(), draw_stencil_pixels(), gl_context::NewState, SWcontext::NewState, swrast, SWRAST_CONTEXT(), swrast_render_finish(), swrast_render_start(), and gl_context::VertexProgram.
draw_depth_pixels()
static void draw_depth_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
References gl_framebuffer::_DepthMax, _mesa_image_address2d(), _mesa_unpack_depth_span(), _swrast_span_default_attribs(), _swrast_write_rgba_span(), _swrast_write_zoomed_depth_span(), sw_span::array, sw_span::arrayMask, gl_pixel_attrib::DepthBias, gl_config::depthBits, gl_pixel_attrib::DepthScale, gl_context::DrawBuffer, sw_span::end, GLuint, GLushort, INIT_SPAN(), gl_context::Pixel, span, SPAN_Z, gl_pixelstore_attrib::SwapBytes, SWRAST_MAX_WIDTH, gl_framebuffer::Visual, sw_span::x, sw_span::y, sw_span_arrays::z, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_DrawPixels().
draw_depth_stencil_pixels()
static void draw_depth_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
This is a bit different from drawing GL_DEPTH_COMPONENT pixels.
The only per-pixel operations that apply are depth scale/bias, stencil offset/shift, GL_DEPTH_WRITEMASK and GL_STENCIL_WRITEMASK, and pixel zoom. Also, only the depth buffer and stencil buffers are touched, not the color buffer(s).
References gl_context::_ImageTransferState, _mesa_clip_drawpixels(), _mesa_error(), _mesa_image_address2d(), _mesa_pack_uint_z_row(), _mesa_unpack_depth_span(), _mesa_unpack_stencil_span(), _swrast_pixel_address(), _swrast_write_stencil_span(), _swrast_write_zoomed_stencil_span(), _swrast_write_zoomed_z_span(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Depth, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, fast_draw_depth_stencil(), gl_renderbuffer::Format, GLuint, gl_depthbuffer_attrib::Mask, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_Z24_UNORM_S8_UINT, gl_context::Pixel, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, gl_stencil_attrib::WriteMask, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_DrawPixels().
draw_rgba_pixels()
static void draw_rgba_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
Draw RGBA image.
References gl_framebuffer::_ColorDrawBuffers, gl_context::_ImageTransferState, _mesa_apply_rgba_transfer_ops(), _mesa_error(), _mesa_format_convert(), _mesa_format_from_format_and_type(), _mesa_get_format_datatype(), _mesa_image_address2d(), _mesa_image_image_stride(), _mesa_image_row_stride(), _mesa_sizeof_packed_type(), _mesa_swap_bytes_2d_image(), _mesa_unpack_color_index_to_rgba_ubyte(), gl_framebuffer::_NumColorDrawBuffers, _swrast_span_default_attribs(), _swrast_write_rgba_span(), _swrast_write_zoomed_rgba_span(), sw_span::array, sw_span::arrayAttribs, arrayMask, sw_span::arrayMask, sw_span_arrays::attribs, CHAN_TYPE, sw_span_arrays::ChanType, gl_colorbuffer_attrib::ClampFragmentColor, gl_context::Color, gl_context::DrawBuffer, sw_span::end, fast_draw_rgba_pixels(), gl_renderbuffer::Format, if(), IMAGE_CLAMP_BIT, INIT_SPAN(), sw_span::interpMask, gl_context::Pixel, RGBA32_FLOAT, span, SPAN_RGBA, gl_pixelstore_attrib::SwapBytes, SWRAST_MAX_WIDTH, swrast_render_finish(), swrast_render_start(), sw_span::x, sw_span::y, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_DrawPixels().
draw_stencil_pixels()
static void draw_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
References gl_context::_ImageTransferState, _mesa_error(), _mesa_image_address2d(), _mesa_unpack_stencil_span(), _swrast_write_stencil_span(), _swrast_write_zoomed_stencil_span(), gl_context::Pixel, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_DrawPixels().
fast_draw_depth_stencil()
static void fast_draw_depth_stencil (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
Draw depth+stencil values into a MESA_FORAMT_Z24_S8 or MESA_FORMAT_Z24_UNORM_S8_UINT renderbuffer.
No masking, zooming, scaling, etc.
References _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_pack_uint_24_8_depth_stencil_row(), _swrast_pixel_address(), gl_framebuffer::Attachment, BUFFER_DEPTH, gl_context::DrawBuffer, gl_renderbuffer::Format, GLuint, gl_renderbuffer_attachment::Renderbuffer, swrast_renderbuffer::RowStride, and swrast_renderbuffer().
Referenced by draw_depth_stencil_pixels().
fast_draw_generic_pixels()
static void fast_draw_generic_pixels (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
Handle a common case of drawing a format/type combination that exactly matches the renderbuffer format.
References _mesa_error(), _mesa_get_format_bytes(), _mesa_image_address2d(), _mesa_image_row_stride(), gl_context::Driver, gl_renderbuffer::Format, dd_function_table::MapRenderbuffer, gl_context::Pixel, dd_function_table::UnmapRenderbuffer, and gl_pixel_attrib::ZoomY.
Referenced by fast_draw_rgba_pixels().
fast_draw_rgb_ubyte_pixels()
static void fast_draw_rgb_ubyte_pixels (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
Handle a common case of drawing GL_RGB/GL_UNSIGNED_BYTE into a MESA_FORMAT_XRGB888 or MESA_FORMAT_ARGB888 renderbuffer.
References _mesa_error(), _mesa_image_address2d(), _mesa_image_row_stride(), gl_context::Driver, GLuint, dd_function_table::MapRenderbuffer, PACK_COLOR_8888, gl_context::Pixel, dd_function_table::UnmapRenderbuffer, and gl_pixel_attrib::ZoomY.
Referenced by fast_draw_rgba_pixels().
fast_draw_rgba_pixels()
static GLboolean fast_draw_rgba_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * userUnpack, const GLvoid * pixels) static
Try to do a fast and simple RGB(a) glDrawPixels.
Return: GL_TRUE if success, GL_FALSE if slow path must be used instead
References gl_framebuffer::_ColorDrawBuffers, gl_texture_attrib::_EnabledCoordUnits, gl_context::_ImageTransferState, _mesa_clip_drawpixels(), _mesa_format_matches_format_and_type(), gl_framebuffer::_NumColorDrawBuffers, SWcontext::_RasterMask, CLIP_BIT, gl_context::DrawBuffer, fast_draw_generic_pixels(), fast_draw_rgb_ubyte_pixels(), fast_draw_rgba_ubyte_pixels(), gl_renderbuffer::Format, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, gl_context::Pixel, gl_pixelstore_attrib::SwapBytes, swrast, SWRAST_CONTEXT(), gl_context::Texture, gl_context::Unpack, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by draw_rgba_pixels().
fast_draw_rgba_ubyte_pixels()
static void fast_draw_rgba_ubyte_pixels (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
Handle a common case of drawing GL_RGBA/GL_UNSIGNED_BYTE into a MESA_FORMAT_ARGB888 or MESA_FORMAT_xRGB888 renderbuffer.
References _mesa_error(), _mesa_image_address2d(), _mesa_image_row_stride(), gl_context::Driver, GLuint, dd_function_table::MapRenderbuffer, PACK_COLOR_8888, gl_context::Pixel, dd_function_table::UnmapRenderbuffer, and gl_pixel_attrib::ZoomY.
Referenced by fast_draw_rgba_pixels().