Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_depth.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/formats.h"
#include "main/format_unpack.h"
#include "main/format_pack.h"
#include "main/macros.h"
#include "main/imports.h"
#include "s_context.h"
#include "s_depth.h"
#include "s_span.h"
Macros
#define Z_TEST(COMPARE)
Functions
static GLuint depth_test_span16 (struct gl_context *ctx, GLuint n, GLushort zbuffer[], const GLuint zfrag[], GLubyte mask[])
Do depth test for an array of 16-bit Z values.
static GLuint depth_test_span32 (struct gl_context *ctx, GLuint n, GLuint zbuffer[], const GLuint zfrag[], GLubyte mask[])
Do depth test for an array of 32-bit Z values.
void _swrast_depth_clamp_span (struct gl_context *ctx, SWspan *span)
Clamp fragment Z values to the depth near/far range (glDepthRange()).
static void get_z32_values (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint count, const GLint x[], const GLint y[], GLuint zbuffer[])
Get array of 32-bit z values from the depth buffer.
static void put_z32_values (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint count, const GLint x[], const GLint y[], const GLuint zvalues[], const GLubyte mask[])
Put an array of 32-bit z values into the depth buffer.
GLuint _swrast_depth_test_span (struct gl_context *ctx, SWspan *span)
Apply depth (Z) buffer testing to the span.
GLboolean _swrast_depth_bounds_test (struct gl_context *ctx, SWspan *span)
GL_EXT_depth_bounds_test extension.
void _swrast_read_depth_span_float (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint n, GLint x, GLint y, GLfloat depth[])
Read a span of depth values from the given depth renderbuffer, returning the values as GLfloats.
void _swrast_clear_depth_buffer (struct gl_context *ctx)
Clear the given z/depth renderbuffer.
void _swrast_clear_depth_stencil_buffer (struct gl_context *ctx)
Clear both depth and stencil values in a combined depth+stencil buffer.
Macro Definition Documentation
Z_TEST
#define Z_TEST (COMPARE)
Value:
do {                                      \
      GLuint i;                              \
      for (i = 0; i < n; i++) {              \
         if (mask[i]) {                      \
            if (COMPARE) {                   \
               /* pass */                    \
               if (write) {                  \
                  zbuffer[i] = zfrag[i];     \
               }                             \
               passed++;                     \
            }                                \
            else {                           \
               /* fail */                    \
               mask[i] = 0;                  \
            }                                \
         }                                   \
      }                                      \
   } while (0)
Referenced by depth_test_span16(), and depth_test_span32().
Function Documentation
_swrast_clear_depth_buffer()
void _swrast_clear_depth_buffer (struct gl_context * ctx)
Clear the given z/depth renderbuffer.
If the buffer is a combined depth+stencil buffer, only the Z bits will be touched.
References _mesa_error(), _mesa_get_format_name(), _mesa_pack_float_z_row(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Attachment, BUFFER_DEPTH, gl_depthbuffer_attrib::Clear, gl_context::Depth, gl_context::DrawBuffer, gl_context::Driver, for(), gl_renderbuffer::Format, GLuint, GLushort, if(), dd_function_table::MapRenderbuffer, gl_depthbuffer_attrib::Mask, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_X8_UINT_Z24_UNORM, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::UnmapRenderbuffer, and x.
Referenced by _swrast_Clear().
_swrast_clear_depth_stencil_buffer()
void _swrast_clear_depth_stencil_buffer (struct gl_context * ctx)
Clear both depth and stencil values in a combined depth+stencil buffer.
References _mesa_error(), _mesa_get_format_name(), _mesa_pack_float_z_row(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_depthbuffer_attrib::Clear, gl_stencil_attrib::Clear, gl_context::Depth, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, gl_config::stencilBits, dd_function_table::UnmapRenderbuffer, gl_framebuffer::Visual, gl_stencil_attrib::WriteMask, and x.
Referenced by _swrast_Clear().
_swrast_depth_bounds_test()
GLboolean _swrast_depth_bounds_test (struct gl_context * ctx, SWspan * span)
GL_EXT_depth_bounds_test extension.
Discard fragments depending on whether the corresponding Z-buffer values are outside the depth bounds test range. Note: we test the Z buffer values, not the fragment Z values!
Returns
GL_TRUE if any fragments pass, GL_FALSE if no fragments pass
References _mesa_unpack_uint_z_row(), _swrast_pixel_address(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, gl_depthbuffer_attrib::BoundsMax, gl_depthbuffer_attrib::BoundsMin, BUFFER_DEPTH, gl_context::Depth, gl_context::DrawBuffer, sw_span::end, gl_renderbuffer::Format, get_z32_values(), GLuint, sw_span_arrays::mask, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, gl_renderbuffer_attachment::Renderbuffer, SPAN_XY, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_write_rgba_span().
_swrast_depth_clamp_span()
void _swrast_depth_clamp_span (struct gl_context * ctx, SWspan * span)
Clamp fragment Z values to the depth near/far range (glDepthRange()).
This is used when GL_ARB_depth_clamp/GL_DEPTH_CLAMP is turned on. In that case, vertexes are not clipped against the near/far planes so rasterization will produce fragment Z values outside the usual [0,1] range.
References gl_framebuffer::_DepthMaxF, sw_span::array, gl_context::DrawBuffer, sw_span::end, gl_viewport_attrib::Far, GLuint, if(), gl_viewport_attrib::Near, gl_context::ViewportArray, and sw_span_arrays::z.
Referenced by _swrast_write_rgba_span().
_swrast_depth_test_span()
GLuint _swrast_depth_test_span (struct gl_context * ctx, SWspan * span)
Apply depth (Z) buffer testing to the span.
Returns
approx number of pixels that passed (only zero is reliable)
References _mesa_get_format_bits(), _mesa_get_format_bytes(), _mesa_get_format_datatype(), _mesa_get_format_name(), _mesa_get_pack_uint_z_func(), _mesa_problem(), _mesa_unpack_uint_z_row(), _swrast_pixel_address(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, BUFFER_DEPTH, depth_test_span16(), depth_test_span32(), gl_context::DrawBuffer, sw_span::end, gl_renderbuffer::Format, get_z32_values(), GLuint, sw_span_arrays::mask, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, put_z32_values(), gl_renderbuffer_attachment::Renderbuffer, SPAN_XY, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, sw_span::y, and sw_span_arrays::z.
Referenced by _swrast_stencil_and_ztest_span(), and _swrast_write_rgba_span().
_swrast_read_depth_span_float()
void _swrast_read_depth_span_float (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint n, GLint x, GLint y, GLfloat depth[])
Read a span of depth values from the given depth renderbuffer, returning the values as GLfloats.
This function does clipping to prevent reading outside the depth buffer's bounds.
References _mesa_unpack_float_z_row(), _swrast_pixel_address(), for(), gl_renderbuffer::Format, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by copy_depth_pixels().
depth_test_span16()
static GLuint depth_test_span16 (struct gl_context * ctx, GLuint n, GLushort zbuffer[], const GLuint zfrag[], GLubyte mask[]) static
Do depth test for an array of 16-bit Z values.
Parameters
zbuffer array of Z buffer values (16-bit)
zfrag array of fragment Z values (use 16-bit in 32-bit uint)
mask which fragments are alive, killed afterward
Returns
number of fragments which pass the test.
References _mesa_problem(), gl_context::Depth, gl_depthbuffer_attrib::Func, GLuint, gl_depthbuffer_attrib::Mask, and Z_TEST.
Referenced by _swrast_depth_test_span().
depth_test_span32()
static GLuint depth_test_span32 (struct gl_context * ctx, GLuint n, GLuint zbuffer[], const GLuint zfrag[], GLubyte mask[]) static
Do depth test for an array of 32-bit Z values.
Parameters
zbuffer array of Z buffer values (32-bit)
zfrag array of fragment Z values (use 32-bits in 32-bit uint)
mask which fragments are alive, killed afterward
Returns
number of fragments which pass the test.
References _mesa_problem(), gl_context::Depth, gl_depthbuffer_attrib::Func, GLuint, gl_depthbuffer_attrib::Mask, and Z_TEST.
Referenced by _swrast_depth_test_span().
get_z32_values()
static void get_z32_values (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint count, const GLint x[], const GLint y[], GLuint zbuffer[]) static
Get array of 32-bit z values from the depth buffer.
With clipping. Note: the returned values are always in the range [0, 2^32-1].
References _mesa_get_format_bytes(), _mesa_unpack_uint_z_row(), _swrast_pixel_address(), gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, MESA_FORMAT_Z_UNORM32, swrast_renderbuffer::RowStride, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by _swrast_depth_bounds_test(), and _swrast_depth_test_span().
put_z32_values()
static void put_z32_values (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint count, const GLint x[], const GLint y[], const GLuint zvalues[], const GLubyte mask[]) static
Put an array of 32-bit z values into the depth buffer.
Note: the z values are always in the range [0, 2^32-1].
References _mesa_get_format_bytes(), _mesa_get_pack_uint_z_func(), _swrast_pixel_address(), gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, MESA_FORMAT_Z_UNORM32, swrast_renderbuffer::RowStride, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by _swrast_depth_test_span().