Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_feedback.h File Reference
#include "swrast.h"
Functions
void _swrast_feedback_point (struct gl_context *ctx, const SWvertex *v)
void _swrast_feedback_line (struct gl_context *ctx, const SWvertex *v1, const SWvertex *v2)
void _swrast_feedback_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_select_point (struct gl_context *ctx, const SWvertex *v)
void _swrast_select_line (struct gl_context *ctx, const SWvertex *v1, const SWvertex *v2)
void _swrast_select_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Function Documentation
_swrast_feedback_line()
void _swrast_feedback_line (struct gl_context * ctx, const SWvertex * v1, const SWvertex * v2)
References feedback_vertex(), gl_context::Light, gl_light_attrib::ShadeModel, SWcontext::StippleCounter, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_choose_line().
_swrast_feedback_point()
void _swrast_feedback_point (struct gl_context * ctx, const SWvertex * v)
References feedback_vertex().
Referenced by _swrast_choose_point().
_swrast_feedback_triangle()
void _swrast_feedback_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References _swrast_culltriangle(), feedback_vertex(), gl_context::Light, and gl_light_attrib::ShadeModel.
Referenced by _swrast_choose_triangle().
_swrast_select_line()
void _swrast_select_line (struct gl_context * ctx, const SWvertex * v1, const SWvertex * v2)
References gl_framebuffer::_DepthMaxF, _mesa_update_hitflag(), SWvertex::attrib, and gl_context::DrawBuffer.
Referenced by _swrast_choose_line().
_swrast_select_point()
void _swrast_select_point (struct gl_context * ctx, const SWvertex * v)
References gl_framebuffer::_DepthMaxF, _mesa_update_hitflag(), SWvertex::attrib, and gl_context::DrawBuffer.
Referenced by _swrast_choose_point().
_swrast_select_triangle()
void _swrast_select_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References gl_framebuffer::_DepthMaxF, _mesa_update_hitflag(), _swrast_culltriangle(), SWvertex::attrib, and gl_context::DrawBuffer.
Referenced by _swrast_choose_triangle().