Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_fog.h File Reference
#include "main/glheader.h"
#include "s_span.h"
Functions
GLfloat _swrast_z_to_fogfactor (struct gl_context *ctx, GLfloat z)
Used to convert current raster distance to a fog factor in [0,1].
void _swrast_fog_rgba_span (const struct gl_context *ctx, SWspan *span)
Apply fog to a span of RGBA pixels.
Function Documentation
_swrast_fog_rgba_span()
void _swrast_fog_rgba_span (const struct gl_context * ctx, SWspan * span)
Apply fog to a span of RGBA pixels.
The fog value are either in the span->array->fog array or interpolated from the fog/fogStep values. They fog values are either fog coordinates (Z) or fog blend factors. _PreferPixelFog should be in sync with that state!
References SWcontext::_FogEnabled, _mesa_problem(), SWcontext::_PreferPixelFog, sw_span::array, sw_span::arrayMask, sw_span_arrays::attribs, BCOMP, BLEND_FOG, sw_span_arrays::ChanType, gl_fog_attrib::Color, CONST_SWRAST_CONTEXT(), gl_fog_attrib::Density, gl_fog_attrib::End, EXP2_FOG, EXP_FOG, F, gl_context::Fog, FOG_LOOP, GCOMP, GLushort, LINEAR_FOG, gl_fog_attrib::Mode, RCOMP, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, gl_fog_attrib::Start, and swrast.
Referenced by _swrast_write_rgba_span().
_swrast_z_to_fogfactor()
GLfloat _swrast_z_to_fogfactor (struct gl_context * ctx, GLfloat z)
Used to convert current raster distance to a fog factor in [0,1].
References _mesa_problem(), gl_fog_attrib::Density, gl_fog_attrib::End, F, gl_context::Fog, gl_fog_attrib::Mode, and gl_fog_attrib::Start.
Referenced by _swrast_span_default_attribs().