Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_lines.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/macros.h"
#include "s_aaline.h"
#include "s_context.h"
#include "s_feedback.h"
#include "s_lines.h"
#include "s_span.h"
#include "s_linetemp.h"
Macros
#define NAME simple_no_z_rgba_line
#define INTERP_RGBA
#define RENDER_SPAN(span) _swrast_write_rgba_span(ctx, &span);
#define NAME rgba_line
#define INTERP_RGBA
#define INTERP_Z
#define RENDER_SPAN(span)
#define NAME general_line
#define INTERP_RGBA
#define INTERP_Z
#define INTERP_ATTRIBS
#define RENDER_SPAN(span)
#define USE(lineFunc) swrast->Line = lineFunc
Functions
static void compute_stipple_mask (struct gl_context *ctx, GLuint len, GLubyte mask[])
static void draw_wide_line (struct gl_context *ctx, SWspan *span, GLboolean xMajor)
void _swrast_add_spec_terms_line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
void _swrast_choose_line (struct gl_context *ctx)
Determine which line drawing function to use given the current rendering context.
Macro Definition Documentation
INTERP_ATTRIBS
#define INTERP_ATTRIBS
INTERP_RGBA [1/3]
#define INTERP_RGBA
INTERP_RGBA [2/3]
#define INTERP_RGBA
INTERP_RGBA [3/3]
#define INTERP_RGBA
INTERP_Z [1/2]
#define INTERP_Z
INTERP_Z [2/2]
#define INTERP_Z
NAME [1/3]
#define NAME simple_no_z_rgba_line
NAME [2/3]
#define NAME rgba_line
NAME [3/3]
#define NAME general_line
RENDER_SPAN [1/3]
#define RENDER_SPAN (span) _swrast_write_rgba_span(ctx, &span);
Referenced by NAME().
RENDER_SPAN [2/3]
#define RENDER_SPAN (span)
Value:
if (ctx->Line.StippleFlag) {                                    \
      span.arrayMask |= SPAN_MASK;                              \
      compute_stipple_mask(ctx, span.end, span.array->mask);    \
   }                                                            \
   if (ctx->Line.Width > 1.0) {                                 \
      draw_wide_line(ctx, &span, (GLboolean)(dx > dy));         \
   }                                                            \
   else {                                                       \
      _swrast_write_rgba_span(ctx, &span);                      \
   }
RENDER_SPAN [3/3]
#define RENDER_SPAN (span)
Value:
if (ctx->Line.StippleFlag) {                                    \
      span.arrayMask |= SPAN_MASK;                              \
      compute_stipple_mask(ctx, span.end, span.array->mask);    \
   }                                                            \
   if (ctx->Line.Width > 1.0) {                                 \
      draw_wide_line(ctx, &span, (GLboolean)(dx > dy));         \
   }                                                            \
   else {                                                       \
      _swrast_write_rgba_span(ctx, &span);                      \
   }
USE
#define USE (lineFunc) swrast->Line = lineFunc
Referenced by _swrast_choose_line().
Function Documentation
_swrast_add_spec_terms_line()
void _swrast_add_spec_terms_line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1)
References SWvertex::attrib, CHAN_TO_FLOAT, SWvertex::color, COPY_CHAN4, SWcontext::SpecLine, SWRAST_CONTEXT(), and UNCLAMPED_FLOAT_TO_CHAN.
Referenced by _swrast_validate_line().
_swrast_choose_line()
void _swrast_choose_line (struct gl_context * ctx)
Determine which line drawing function to use given the current rendering context.
Please update the summary flag _SWRAST_NEW_LINE if you add or remove tests to this code.
References gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, _swrast_choose_aa_line_function(), _swrast_feedback_line(), _swrast_select_line(), _swrast_use_fragment_program(), gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_context::Depth, gl_light_attrib::Enabled, gl_context::Fog, gl_context::Light, gl_context::Line, SWcontext::Line, gl_light_attrib::Model, gl_context::RenderMode, gl_line_attrib::SmoothFlag, gl_line_attrib::StippleFlag, swrast, SWRAST_CONTEXT(), gl_depthbuffer_attrib::Test, gl_context::Texture, USE, and gl_line_attrib::Width.
Referenced by _swrast_CreateContext().
compute_stipple_mask()
static void compute_stipple_mask (struct gl_context * ctx, GLuint len, GLubyte mask[]) static
References GLuint, gl_context::Line, SWcontext::StippleCounter, gl_line_attrib::StippleFactor, gl_line_attrib::StipplePattern, swrast, and SWRAST_CONTEXT().
draw_wide_line()
static void draw_wide_line (struct gl_context * ctx, SWspan * span, GLboolean xMajor) static
References _swrast_write_rgba_span(), sw_span::array, gl_context::Const, sw_span::end, GLuint, gl_context::Line, gl_constants::MaxLineWidth, gl_constants::MinLineWidth, SWRAST_MAX_WIDTH, gl_line_attrib::Width, x, sw_span_arrays::x, and sw_span_arrays::y.