Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_lines.h File Reference
#include "swrast.h"
Functions
void _swrast_choose_line (struct gl_context *ctx)
Determine which line drawing function to use given the current rendering context.
void _swrast_add_spec_terms_line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
Function Documentation
_swrast_add_spec_terms_line()
void _swrast_add_spec_terms_line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1)
References SWvertex::attrib, CHAN_TO_FLOAT, SWvertex::color, COPY_CHAN4, SWcontext::SpecLine, SWRAST_CONTEXT(), and UNCLAMPED_FLOAT_TO_CHAN.
Referenced by _swrast_validate_line().
_swrast_choose_line()
void _swrast_choose_line (struct gl_context * ctx)
Determine which line drawing function to use given the current rendering context.
Please update the summary flag _SWRAST_NEW_LINE if you add or remove tests to this code.
References gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, _swrast_choose_aa_line_function(), _swrast_feedback_line(), _swrast_select_line(), _swrast_use_fragment_program(), gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_context::Depth, gl_light_attrib::Enabled, gl_context::Fog, gl_context::Light, gl_context::Line, SWcontext::Line, gl_light_attrib::Model, gl_context::RenderMode, gl_line_attrib::SmoothFlag, gl_line_attrib::StippleFlag, swrast, SWRAST_CONTEXT(), gl_depthbuffer_attrib::Test, gl_context::Texture, USE, and gl_line_attrib::Width.
Referenced by _swrast_CreateContext().