Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_logic.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/macros.h"
#include "s_context.h"
#include "s_logic.h"
#include "s_span.h"
Macros
#define LOGIC_OP_LOOP(MODE, MASKSTRIDE)
We do all logic ops on 4-byte GLuints.
Functions
static void logicop_uint1 (struct gl_context *ctx, GLuint n, GLuint src[], const GLuint dest[], const GLubyte mask[])
static void logicop_uint2 (struct gl_context *ctx, GLuint n, GLuint src[], const GLuint dest[], const GLubyte mask[])
static void logicop_uint4 (struct gl_context *ctx, GLuint n, GLuint src[], const GLuint dest[], const GLubyte mask[])
void _swrast_logicop_rgba_span (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span)
Apply the current logic operator to a span of RGBA pixels.
Macro Definition Documentation
LOGIC_OP_LOOP
#define LOGIC_OP_LOOP (MODE, MASKSTRIDE)
We do all logic ops on 4-byte GLuints.
Depending on bytes per pixel, the mask array elements correspond to 1, 2 or 4 GLuints.
Referenced by logicop_uint1(), logicop_uint2(), and logicop_uint4().
Function Documentation
_swrast_logicop_rgba_span()
void _swrast_logicop_rgba_span (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span)
Apply the current logic operator to a span of RGBA pixels.
We can handle horizontal runs of pixels (spans) or arrays of x/y pixel coordinates.
References _swrast_get_dest_rgba(), sw_span::array, sw_span::arrayMask, sw_span_arrays::attribs, sw_span_arrays::ChanType, sw_span::end, GLuint, logicop_uint1(), logicop_uint2(), logicop_uint4(), sw_span_arrays::mask, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, and SWRAST_MAX_WIDTH.
Referenced by _swrast_write_rgba_span().
logicop_uint1()
static void logicop_uint1 (struct gl_context * ctx, GLuint n, GLuint src[], const GLuint dest[], const GLubyte mask[]) inline static
References gl_context::Color, LOGIC_OP_LOOP, and gl_colorbuffer_attrib::LogicOp.
Referenced by _swrast_logicop_rgba_span().
logicop_uint2()
static void logicop_uint2 (struct gl_context * ctx, GLuint n, GLuint src[], const GLuint dest[], const GLubyte mask[]) inline static
References gl_context::Color, LOGIC_OP_LOOP, and gl_colorbuffer_attrib::LogicOp.
Referenced by _swrast_logicop_rgba_span().
logicop_uint4()
static void logicop_uint4 (struct gl_context * ctx, GLuint n, GLuint src[], const GLuint dest[], const GLubyte mask[]) inline static
References gl_context::Color, LOGIC_OP_LOOP, and gl_colorbuffer_attrib::LogicOp.
Referenced by _swrast_logicop_rgba_span().