Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_masking.c File Reference
#include "main/glheader.h"
#include "main/macros.h"
#include "s_context.h"
#include "s_masking.h"
#include "s_span.h"
Functions
void _swrast_mask_rgba_span (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span, GLuint buf)
Apply the color mask to a span of rgba values.
Function Documentation
_swrast_mask_rgba_span()
void _swrast_mask_rgba_span (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span, GLuint buf)
Apply the color mask to a span of rgba values.
References _swrast_get_dest_rgba(), ACOMP, sw_span::array, sw_span::arrayMask, sw_span_arrays::attribs, BCOMP, sw_span_arrays::ChanType, gl_context::Color, gl_colorbuffer_attrib::ColorMask, sw_span::end, for(), GCOMP, GLuint, GLushort, RCOMP, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, and SWRAST_MAX_WIDTH.
Referenced by _swrast_write_rgba_span().