Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_points.h File Reference
#include "swrast.h"
Functions
void _swrast_choose_point (struct gl_context *ctx)
Examine current state to determine which point drawing function to use.
void _swrast_add_spec_terms_point (struct gl_context *ctx, const SWvertex *v0)
Add specular color to primary color, draw point, restore original primary color.
Function Documentation
_swrast_add_spec_terms_point()
void _swrast_add_spec_terms_point (struct gl_context * ctx, const SWvertex * v0)
Add specular color to primary color, draw point, restore original primary color.
References SWvertex::attrib, CHAN_TO_FLOAT, SWvertex::color, COPY_CHAN4, SWcontext::SpecPoint, SWRAST_CONTEXT(), and UNCLAMPED_FLOAT_TO_CHAN.
Referenced by _swrast_validate_point().
_swrast_choose_point()
void _swrast_choose_point (struct gl_context * ctx)
Examine current state to determine which point drawing function to use.
References gl_point_attrib::_Attenuated, _swrast_feedback_point(), _swrast_select_point(), F, large_point(), gl_point_attrib::MaxSize, gl_point_attrib::MinSize, pixel_point(), gl_context::Point, SWcontext::Point, gl_vertex_program_state::PointSizeEnabled, gl_point_attrib::PointSprite, gl_context::RenderMode, gl_point_attrib::Size, smooth_point(), gl_point_attrib::SmoothFlag, sprite_point(), swrast, SWRAST_CONTEXT(), and gl_context::VertexProgram.
Referenced by _swrast_CreateContext().