Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_renderbuffer.h File Reference
#include "main/glheader.h"
Functions
struct gl_renderbuffer * _swrast_new_soft_renderbuffer (struct gl_context *ctx, GLuint name)
Allocate a software-based renderbuffer.
void _swrast_map_soft_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **out_map, GLint *out_stride)
void _swrast_unmap_soft_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
void _swrast_set_renderbuffer_accessors (struct gl_renderbuffer *rb)
void _swrast_add_soft_renderbuffers (struct gl_framebuffer *fb, GLboolean color, GLboolean depth, GLboolean stencil, GLboolean accum, GLboolean alpha, GLboolean aux)
Create/attach software-based renderbuffers to the given framebuffer.
Function Documentation
_swrast_add_soft_renderbuffers()
void _swrast_add_soft_renderbuffers (struct gl_framebuffer * fb, GLboolean color, GLboolean depth, GLboolean stencil, GLboolean accum, GLboolean alpha, GLboolean aux)
Create/attach software-based renderbuffers to the given framebuffer.
This is a helper routine for device drivers. Drivers can just as well call the individual mesa_add*_renderbuffer() routines directly.
References gl_config::accumAlphaBits, gl_config::accumBlueBits, gl_config::accumGreenBits, gl_config::accumRedBits, add_accum_renderbuffer(), add_aux_renderbuffers(), add_color_renderbuffers(), add_depth_renderbuffer(), add_depth_stencil_renderbuffer(), add_stencil_renderbuffer(), gl_config::alphaBits, gl_config::blueBits, gl_config::depthBits, gl_config::doubleBufferMode, gl_config::greenBits, gl_config::numAuxBuffers, gl_config::redBits, gl_config::stencilBits, gl_config::stereoMode, gl_framebuffer::Visual, and void.
_swrast_map_soft_renderbuffer()
void _swrast_map_soft_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte ** out_map, GLint * out_stride)
References _mesa_get_format_bytes(), swrast_renderbuffer::Buffer, gl_renderbuffer::Format, swrast_renderbuffer(), and gl_renderbuffer::Width.
_swrast_new_soft_renderbuffer()
struct gl_renderbuffer* _swrast_new_soft_renderbuffer (struct gl_context * ctx, GLuint name)
Allocate a software-based renderbuffer.
This is called via the ctx->Driver.NewRenderbuffer() function when the user creates a new renderbuffer. This would not be used for hardware-based renderbuffers.
References _mesa_init_renderbuffer(), gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, CALLOC_STRUCT, gl_renderbuffer::Delete, soft_renderbuffer_delete(), and soft_renderbuffer_storage().
Referenced by add_accum_renderbuffer(), add_aux_renderbuffers(), add_depth_renderbuffer(), add_depth_stencil_renderbuffer(), and add_stencil_renderbuffer().
_swrast_set_renderbuffer_accessors()
void _swrast_set_renderbuffer_accessors (struct gl_renderbuffer * rb)
_swrast_unmap_soft_renderbuffer()
void _swrast_unmap_soft_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb)