Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_renderbuffer.c File Reference
#include "main/glheader.h"
#include "main/imports.h"
#include "main/context.h"
#include "main/fbobject.h"
#include "main/formats.h"
#include "main/mtypes.h"
#include "main/renderbuffer.h"
#include "swrast/s_context.h"
#include "swrast/s_renderbuffer.h"
Functions
static GLboolean soft_renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLuint width, GLuint height)
Functions for allocating/managing software-based renderbuffers.
static void soft_renderbuffer_delete (struct gl_context *ctx, struct gl_renderbuffer *rb)
Called via gl_renderbuffer::Delete()
void _swrast_map_soft_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **out_map, GLint *out_stride)
void _swrast_unmap_soft_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
struct gl_renderbuffer * _swrast_new_soft_renderbuffer (struct gl_context *ctx, GLuint name)
Allocate a software-based renderbuffer.
static GLboolean add_color_renderbuffers (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint rgbBits, GLuint alphaBits, GLboolean frontLeft, GLboolean backLeft, GLboolean frontRight, GLboolean backRight)
Add software-based color renderbuffers to the given framebuffer.
static GLboolean add_depth_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint depthBits)
Add a software-based depth renderbuffer to the given framebuffer.
static GLboolean add_stencil_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint stencilBits)
Add a software-based stencil renderbuffer to the given framebuffer.
static GLboolean add_depth_stencil_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
static GLboolean add_accum_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint redBits, GLuint greenBits, GLuint blueBits, GLuint alphaBits)
Add a software-based accumulation renderbuffer to the given framebuffer.
static GLboolean add_aux_renderbuffers (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint colorBits, GLuint numBuffers)
Add a software-based aux renderbuffer to the given framebuffer.
void _swrast_add_soft_renderbuffers (struct gl_framebuffer *fb, GLboolean color, GLboolean depth, GLboolean stencil, GLboolean accum, GLboolean alpha, GLboolean aux)
Create/attach software-based renderbuffers to the given framebuffer.
static void map_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, gl_buffer_index buffer)
static void unmap_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, gl_buffer_index buffer)
static void find_renderbuffer_colortype (struct gl_renderbuffer *rb)
Determine what type to use (ubyte vs.
void _swrast_map_renderbuffers (struct gl_context *ctx)
Map the renderbuffers we'll use for tri/line/point rendering.
void _swrast_unmap_renderbuffers (struct gl_context *ctx)
Unmap renderbuffers after rendering.
Function Documentation
_swrast_add_soft_renderbuffers()
void _swrast_add_soft_renderbuffers (struct gl_framebuffer * fb, GLboolean color, GLboolean depth, GLboolean stencil, GLboolean accum, GLboolean alpha, GLboolean aux)
Create/attach software-based renderbuffers to the given framebuffer.
This is a helper routine for device drivers. Drivers can just as well call the individual mesa_add*_renderbuffer() routines directly.
References gl_config::accumAlphaBits, gl_config::accumBlueBits, gl_config::accumGreenBits, gl_config::accumRedBits, add_accum_renderbuffer(), add_aux_renderbuffers(), add_color_renderbuffers(), add_depth_renderbuffer(), add_depth_stencil_renderbuffer(), add_stencil_renderbuffer(), gl_config::alphaBits, gl_config::blueBits, gl_config::depthBits, gl_config::doubleBufferMode, gl_config::greenBits, gl_config::numAuxBuffers, gl_config::redBits, gl_config::stencilBits, gl_config::stereoMode, gl_framebuffer::Visual, and void.
_swrast_map_renderbuffers()
void _swrast_map_renderbuffers (struct gl_context * ctx)
Map the renderbuffers we'll use for tri/line/point rendering.
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::DrawBuffer, find_renderbuffer_colortype(), GLuint, map_attachment(), and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _swrast_span_render_start(), and swrast_render_finish().
_swrast_map_soft_renderbuffer()
void _swrast_map_soft_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte ** out_map, GLint * out_stride)
References _mesa_get_format_bytes(), swrast_renderbuffer::Buffer, gl_renderbuffer::Format, swrast_renderbuffer(), and gl_renderbuffer::Width.
_swrast_new_soft_renderbuffer()
struct gl_renderbuffer* _swrast_new_soft_renderbuffer (struct gl_context * ctx, GLuint name)
Allocate a software-based renderbuffer.
This is called via the ctx->Driver.NewRenderbuffer() function when the user creates a new renderbuffer. This would not be used for hardware-based renderbuffers.
References _mesa_init_renderbuffer(), gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, CALLOC_STRUCT, gl_renderbuffer::Delete, soft_renderbuffer_delete(), and soft_renderbuffer_storage().
Referenced by add_accum_renderbuffer(), add_aux_renderbuffers(), add_depth_renderbuffer(), add_depth_stencil_renderbuffer(), and add_stencil_renderbuffer().
_swrast_unmap_renderbuffers()
void _swrast_unmap_renderbuffers (struct gl_context * ctx)
Unmap renderbuffers after rendering.
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::DrawBuffer, GLuint, gl_renderbuffer_attachment::Renderbuffer, and unmap_attachment().
Referenced by _swrast_span_render_finish(), and swrast_render_finish().
_swrast_unmap_soft_renderbuffer()
void _swrast_unmap_soft_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb)
add_accum_renderbuffer()
static GLboolean add_accum_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint redBits, GLuint greenBits, GLuint blueBits, GLuint alphaBits) static
Add a software-based accumulation renderbuffer to the given framebuffer.
This is a helper routine for device drivers when creating a window system framebuffer (not a user-created render/framebuffer). Once this function is called, you can basically forget about this renderbuffer; core Mesa will handle all the buffer management and rendering!
References _mesa_add_renderbuffer(), _mesa_error(), _mesa_problem(), _swrast_new_soft_renderbuffer(), gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_ACCUM, gl_renderbuffer::InternalFormat, gl_renderbuffer_attachment::Renderbuffer, and soft_renderbuffer_storage().
Referenced by _swrast_add_soft_renderbuffers().
add_aux_renderbuffers()
static GLboolean add_aux_renderbuffers (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint colorBits, GLuint numBuffers) static
Add a software-based aux renderbuffer to the given framebuffer.
This is a helper routine for device drivers when creating a window system framebuffer (not a user-created render/framebuffer). Once this function is called, you can basically forget about this renderbuffer; core Mesa will handle all the buffer management and rendering!
NOTE: color-index aux buffers not supported.
References _mesa_add_renderbuffer(), _mesa_error(), _mesa_problem(), _swrast_new_soft_renderbuffer(), gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_AUX0, GLuint, gl_renderbuffer::InternalFormat, MAX_AUX_BUFFERS, gl_renderbuffer_attachment::Renderbuffer, and soft_renderbuffer_storage().
Referenced by _swrast_add_soft_renderbuffers().
add_color_renderbuffers()
static GLboolean add_color_renderbuffers (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint rgbBits, GLuint alphaBits, GLboolean frontLeft, GLboolean backLeft, GLboolean frontRight, GLboolean backRight) static
Add software-based color renderbuffers to the given framebuffer.
This is a helper routine for device drivers when creating a window system framebuffer (not a user-created render/framebuffer). Once this function is called, you can basically forget about this renderbuffer; core Mesa will handle all the buffer management and rendering!
References _mesa_add_renderbuffer(), _mesa_error(), _mesa_problem(), gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_BACK_LEFT, BUFFER_BACK_RIGHT, BUFFER_FRONT_LEFT, BUFFER_FRONT_RIGHT, gl_context::Driver, gl_renderbuffer::InternalFormat, MAX_COLOR_ATTACHMENTS, dd_function_table::NewRenderbuffer, gl_renderbuffer::RefCount, gl_renderbuffer_attachment::Renderbuffer, and soft_renderbuffer_storage().
Referenced by _swrast_add_soft_renderbuffers().
add_depth_renderbuffer()
static GLboolean add_depth_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint depthBits) static
Add a software-based depth renderbuffer to the given framebuffer.
This is a helper routine for device drivers when creating a window system framebuffer (not a user-created render/framebuffer). Once this function is called, you can basically forget about this renderbuffer; core Mesa will handle all the buffer management and rendering!
References _mesa_add_renderbuffer(), _mesa_error(), _mesa_problem(), _swrast_new_soft_renderbuffer(), gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_DEPTH, gl_renderbuffer::InternalFormat, gl_renderbuffer_attachment::Renderbuffer, and soft_renderbuffer_storage().
Referenced by _swrast_add_soft_renderbuffers().
add_depth_stencil_renderbuffer()
static GLboolean add_depth_stencil_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb) static
References _mesa_add_renderbuffer(), _mesa_error(), _swrast_new_soft_renderbuffer(), gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer::InternalFormat, gl_renderbuffer_attachment::Renderbuffer, and soft_renderbuffer_storage().
Referenced by _swrast_add_soft_renderbuffers().
add_stencil_renderbuffer()
static GLboolean add_stencil_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint stencilBits) static
Add a software-based stencil renderbuffer to the given framebuffer.
This is a helper routine for device drivers when creating a window system framebuffer (not a user-created render/framebuffer). Once this function is called, you can basically forget about this renderbuffer; core Mesa will handle all the buffer management and rendering!
References _mesa_add_renderbuffer(), _mesa_error(), _mesa_problem(), _swrast_new_soft_renderbuffer(), gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_STENCIL, gl_renderbuffer::InternalFormat, gl_renderbuffer_attachment::Renderbuffer, and soft_renderbuffer_storage().
Referenced by _swrast_add_soft_renderbuffers().
find_renderbuffer_colortype()
static void find_renderbuffer_colortype (struct gl_renderbuffer * rb) static
Determine what type to use (ubyte vs.
float) for span colors for the given renderbuffer. See also _swrast_write_rgba_span().
References _mesa_get_format_datatype(), _mesa_get_format_max_bits(), swrast_renderbuffer::ColorType, gl_renderbuffer::Format, GLuint, and swrast_renderbuffer().
Referenced by _swrast_map_renderbuffers().
map_attachment()
static void map_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, gl_buffer_index buffer) static
References gl_framebuffer::Attachment, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, GLuint, gl_renderbuffer::Height, gl_texture_image::Height, gl_texture_object::Image, swrast_renderbuffer::Map, dd_function_table::MapRenderbuffer, dd_function_table::MapTextureImage, gl_renderbuffer_attachment::Renderbuffer, swrast_renderbuffer::RowStride, swrast_renderbuffer(), gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_texture_image::Width, gl_renderbuffer::Width, and gl_renderbuffer_attachment::Zoffset.
Referenced by _swrast_map_renderbuffers().
soft_renderbuffer_delete()
static void soft_renderbuffer_delete (struct gl_context * ctx, struct gl_renderbuffer * rb) static
Called via gl_renderbuffer::Delete()
References _mesa_delete_renderbuffer(), swrast_renderbuffer::Buffer, and swrast_renderbuffer().
Referenced by _swrast_new_soft_renderbuffer().
soft_renderbuffer_storage()
static GLboolean soft_renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLuint width, GLuint height) static
Functions for allocating/managing software-based renderbuffers.
Also, routines for reading/writing software-based renderbuffer data as ubytes, ushorts, uints, etc. This is a software fallback for the gl_renderbuffer->AllocStorage function. Device drivers will typically override this function for the buffers which it manages (typically color buffers, Z and stencil). Other buffers (like software accumulation and aux buffers) which the driver doesn't manage can be handled with this function.
This one multi-purpose function can allocate stencil, depth, accum, color or color-index buffers!
References gl_renderbuffer::_BaseFormat, _mesa_base_fbo_format(), _mesa_error(), _mesa_get_format_bytes(), swrast_renderbuffer::Buffer, gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, gl_renderbuffer::Name, swrast_renderbuffer::RowStride, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by _swrast_new_soft_renderbuffer(), add_accum_renderbuffer(), add_aux_renderbuffers(), add_color_renderbuffers(), add_depth_renderbuffer(), add_depth_stencil_renderbuffer(), and add_stencil_renderbuffer().
unmap_attachment()
static void unmap_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, gl_buffer_index buffer) static
References gl_framebuffer::Attachment, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, GLuint, gl_texture_object::Image, swrast_renderbuffer::Map, gl_renderbuffer_attachment::Renderbuffer, swrast_renderbuffer(), gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, dd_function_table::UnmapRenderbuffer, dd_function_table::UnmapTextureImage, and gl_renderbuffer_attachment::Zoffset.
Referenced by _swrast_unmap_renderbuffers().