Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_stencil.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/format_pack.h"
#include "main/format_unpack.h"
#include "main/core.h"
#include "main/stencil.h"
#include "s_context.h"
#include "s_depth.h"
#include "s_stencil.h"
#include "s_span.h"
Macros
#define STENCIL_OP(NEW_VAL)
#define STENCIL_TEST(FUNC)
Functions
static GLint get_stencil_offset (mesa_format format)
Compute/return the offset of the stencil value in a pixel.
static GLubyte clamp (GLint val)
Clamp the stencil value to [0, 255].
static void apply_stencil_op (const struct gl_context *ctx, GLenum oper, GLuint face, GLuint n, GLubyte stencil[], const GLubyte mask[], GLint stride)
Apply the given stencil operator to the array of stencil values.
static GLboolean do_stencil_test (struct gl_context *ctx, GLuint face, GLuint n, GLubyte stencil[], GLubyte mask[], GLint stride)
Apply stencil test to an array of stencil values (before depth buffering).
static void compute_pass_fail_masks (GLuint n, const GLubyte origMask[], const GLubyte newMask[], GLubyte passMask[], GLubyte failMask[])
Compute the zpass/zfail masks by comparing the pre- and post-depth test masks.
static void get_s8_values (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint count, const GLint x[], const GLint y[], GLubyte stencil[])
Get 8-bit stencil values from random locations in the stencil buffer.
static void put_s8_values (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint count, const GLint x[], const GLint y[], const GLubyte stencil[])
Put 8-bit stencil values at random locations into the stencil buffer.
GLboolean _swrast_stencil_and_ztest_span (struct gl_context *ctx, SWspan *span)
/return GL_TRUE = one or more fragments passed, GL_FALSE = all fragments failed.
void _swrast_read_stencil_span (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint n, GLint x, GLint y, GLubyte stencil[])
Return a span of stencil values from the stencil buffer.
void _swrast_write_stencil_span (struct gl_context *ctx, GLint n, GLint x, GLint y, const GLubyte stencil[])
Write a span of stencil values to the stencil buffer.
void _swrast_clear_stencil_buffer (struct gl_context *ctx)
Clear the stencil buffer.
Macro Definition Documentation
STENCIL_OP
#define STENCIL_OP (NEW_VAL)
Value:
if (invmask == 0) {                                                      \
      for (i = j = 0; i < n; i++, j += stride) {                            \
         if (mask[i]) {                                                     \
            GLubyte s = stencil[j];                                         \
            (void) s;                                                       \
            stencil[j] = (GLubyte) (NEW_VAL);                               \
         }                                                                  \
      }                                                                     \
   }                                                                        \
   else {                                                                   \
      for (i = j = 0; i < n; i++, j += stride) {                            \
         if (mask[i]) {                                                     \
            GLubyte s = stencil[j];                                         \
            stencil[j] = (GLubyte) ((invmask & s) | (wrtmask & (NEW_VAL))); \
         }                                                                  \
      }                                                                     \
   }
Referenced by apply_stencil_op().
STENCIL_TEST
#define STENCIL_TEST (FUNC)
Value:
for (i = j = 0; i < n; i++, j += stride) {     \
      if (mask[i]) {                              \
         s = (GLubyte) (stencil[j] & valueMask);  \
         if (FUNC) {                              \
            /* stencil pass */                    \
            fail[i] = 0;                          \
         }                                        \
         else {                                   \
            /* stencil fail */                    \
            fail[i] = 1;                          \
            mask[i] = 0;                          \
         }                                        \
      }                                           \
      else {                                      \
         fail[i] = 0;                             \
      }                                           \
   }
Referenced by do_stencil_test().
Function Documentation
_swrast_clear_stencil_buffer()
void _swrast_clear_stencil_buffer (struct gl_context * ctx)
Clear the stencil buffer.
If the buffer is a combined depth+stencil buffer, only the stencil bits will be touched.
References _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_name(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Attachment, BUFFER_STENCIL, gl_stencil_attrib::Clear, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_S8_UINT, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, gl_config::stencilBits, dd_function_table::UnmapRenderbuffer, gl_framebuffer::Visual, gl_stencil_attrib::WriteMask, and x.
Referenced by _swrast_Clear().
_swrast_read_stencil_span()
void _swrast_read_stencil_span (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint n, GLint x, GLint y, GLubyte stencil[])
Return a span of stencil values from the stencil buffer.
Used for glRead/CopyPixels Input: n - how many pixels x,y - location of first pixel Output: stencil - the array of stencil values
References _mesa_unpack_ubyte_stencil_row(), _swrast_pixel_address(), gl_renderbuffer::Format, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by copy_stencil_pixels().
_swrast_stencil_and_ztest_span()
GLboolean _swrast_stencil_and_ztest_span (struct gl_context * ctx, SWspan * span)
/return GL_TRUE = one or more fragments passed, GL_FALSE = all fragments failed.
References gl_stencil_attrib::_BackFace, _mesa_get_format_bytes(), _swrast_depth_test_span(), _swrast_pixel_address(), apply_stencil_op(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, SWcontext::buf1, SWcontext::buf2, SWcontext::buf3, SWcontext::buf4, BUFFER_DEPTH, BUFFER_STENCIL, compute_pass_fail_masks(), gl_context::Depth, do_stencil_test(), gl_context::DrawBuffer, sw_span::end, sw_span::facing, gl_renderbuffer::Format, get_s8_values(), get_stencil_offset(), GLuint, if(), sw_span_arrays::mask, put_s8_values(), gl_renderbuffer_attachment::Renderbuffer, SPAN_XY, gl_context::Stencil, SWcontext::stencil_temp, swrast, SWRAST_CONTEXT(), gl_depthbuffer_attrib::Test, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, sw_span::y, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Referenced by _swrast_write_rgba_span().
_swrast_write_stencil_span()
void _swrast_write_stencil_span (struct gl_context * ctx, GLint n, GLint x, GLint y, const GLubyte stencil[])
Write a span of stencil values to the stencil buffer.
This function applies the stencil write mask when needed. Used for glDraw/CopyPixels Input: n - how many pixels x, y - location of first pixel stencil - the array of stencil values
References _mesa_pack_ubyte_stencil_row(), _mesa_unpack_ubyte_stencil_row(), _swrast_pixel_address(), gl_framebuffer::Attachment, SWcontext::buf1, SWcontext::buf2, BUFFER_STENCIL, gl_context::DrawBuffer, gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, SWcontext::stencil_temp, gl_config::stencilBits, swrast, SWRAST_CONTEXT(), gl_framebuffer::Visual, gl_renderbuffer::Width, and gl_stencil_attrib::WriteMask.
Referenced by _swrast_write_zoomed_stencil_span(), copy_stencil_pixels(), draw_depth_stencil_pixels(), and draw_stencil_pixels().
apply_stencil_op()
static void apply_stencil_op (const struct gl_context * ctx, GLenum oper, GLuint face, GLuint n, GLubyte stencil[], const GLubyte mask[], GLint stride) static
Apply the given stencil operator to the array of stencil values.
Don't touch stencil[i] if mask[i] is zero.
Parameters
n number of stencil values
oper the stencil buffer operator
face 0 or 1 for front or back face operation
stencil array of stencil values (in/out)
mask array [n] of flag: 1=apply operator, 0=don't apply operator
stride stride between stencil values
References _mesa_problem(), clamp(), GLuint, gl_context::Stencil, STENCIL_OP, and gl_stencil_attrib::WriteMask.
Referenced by _swrast_stencil_and_ztest_span(), and do_stencil_test().
clamp()
static GLubyte clamp (GLint val) inline static
Clamp the stencil value to [0, 255].
Referenced by apply_stencil_op().
compute_pass_fail_masks()
static void compute_pass_fail_masks (GLuint n, const GLubyte origMask[], const GLubyte newMask[], GLubyte passMask[], GLubyte failMask[]) inline static
Compute the zpass/zfail masks by comparing the pre- and post-depth test masks.
References GLuint.
Referenced by _swrast_stencil_and_ztest_span().
do_stencil_test()
static GLboolean do_stencil_test (struct gl_context * ctx, GLuint face, GLuint n, GLubyte stencil[], GLubyte mask[], GLint stride) static
Apply stencil test to an array of stencil values (before depth buffering).
For the values that fail, we'll apply the GL_STENCIL_FAIL operator to the stencil values.
Parameters
face 0 or 1 for front or back-face polygons
n number of pixels in the array
stencil array of [n] stencil values (in/out)
mask array [n] of flag: 0=skip the pixel, 1=stencil the pixel, values are set to zero where the stencil test fails.
stride stride between stencil values
Returns
GL_FALSE = all pixels failed, GL_TRUE = zero or more pixels passed.
References _mesa_problem(), apply_stencil_op(), SWcontext::buf2, gl_stencil_attrib::FailFunc, gl_stencil_attrib::Function, GLuint, gl_context::Stencil, SWcontext::stencil_temp, STENCIL_TEST, swrast, SWRAST_CONTEXT(), and gl_stencil_attrib::ValueMask.
Referenced by _swrast_stencil_and_ztest_span().
get_s8_values()
static void get_s8_values (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint count, const GLint x[], const GLint y[], GLubyte stencil[]) static
Get 8-bit stencil values from random locations in the stencil buffer.
References _mesa_get_format_bytes(), _mesa_unpack_ubyte_stencil_row(), _swrast_pixel_address(), gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, MESA_FORMAT_S_UINT8, swrast_renderbuffer::RowStride, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by _swrast_stencil_and_ztest_span().
get_stencil_offset()
static GLint get_stencil_offset (mesa_format format) static
Compute/return the offset of the stencil value in a pixel.
For example, if the format is Z24+S8, the position of the stencil bits within the 4-byte pixel will be either 0 or 3.
References _mesa_get_format_bits(), _mesa_get_format_bytes(), _mesa_pack_ubyte_stencil_row(), _mesa_problem(), and MAX_PIXEL_BYTES.
Referenced by _swrast_stencil_and_ztest_span().
put_s8_values()
static void put_s8_values (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint count, const GLint x[], const GLint y[], const GLubyte stencil[]) static
Put 8-bit stencil values at random locations into the stencil buffer.
References _mesa_get_pack_ubyte_stencil_func(), _swrast_pixel_address(), gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by _swrast_stencil_and_ztest_span().