Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_stencil.h File Reference
#include "main/mtypes.h"
#include "s_span.h"
Functions
GLboolean _swrast_stencil_and_ztest_span (struct gl_context *ctx, SWspan *span)
/return GL_TRUE = one or more fragments passed, GL_FALSE = all fragments failed.
void _swrast_read_stencil_span (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint n, GLint x, GLint y, GLubyte stencil[])
Return a span of stencil values from the stencil buffer.
void _swrast_write_stencil_span (struct gl_context *ctx, GLint n, GLint x, GLint y, const GLubyte stencil[])
Write a span of stencil values to the stencil buffer.
void _swrast_clear_stencil_buffer (struct gl_context *ctx)
Clear the stencil buffer.
Function Documentation
_swrast_clear_stencil_buffer()
void _swrast_clear_stencil_buffer (struct gl_context * ctx)
Clear the stencil buffer.
If the buffer is a combined depth+stencil buffer, only the stencil bits will be touched.
References _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_name(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Attachment, BUFFER_STENCIL, gl_stencil_attrib::Clear, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_S8_UINT, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, gl_config::stencilBits, dd_function_table::UnmapRenderbuffer, gl_framebuffer::Visual, gl_stencil_attrib::WriteMask, and x.
Referenced by _swrast_Clear().
_swrast_read_stencil_span()
void _swrast_read_stencil_span (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint n, GLint x, GLint y, GLubyte stencil[])
Return a span of stencil values from the stencil buffer.
Used for glRead/CopyPixels Input: n - how many pixels x,y - location of first pixel Output: stencil - the array of stencil values
References _mesa_unpack_ubyte_stencil_row(), _swrast_pixel_address(), gl_renderbuffer::Format, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by copy_stencil_pixels().
_swrast_stencil_and_ztest_span()
GLboolean _swrast_stencil_and_ztest_span (struct gl_context * ctx, SWspan * span)
/return GL_TRUE = one or more fragments passed, GL_FALSE = all fragments failed.
References gl_stencil_attrib::_BackFace, _mesa_get_format_bytes(), _swrast_depth_test_span(), _swrast_pixel_address(), apply_stencil_op(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, SWcontext::buf1, SWcontext::buf2, SWcontext::buf3, SWcontext::buf4, BUFFER_DEPTH, BUFFER_STENCIL, compute_pass_fail_masks(), gl_context::Depth, do_stencil_test(), gl_context::DrawBuffer, sw_span::end, sw_span::facing, gl_renderbuffer::Format, get_s8_values(), get_stencil_offset(), GLuint, if(), sw_span_arrays::mask, put_s8_values(), gl_renderbuffer_attachment::Renderbuffer, SPAN_XY, gl_context::Stencil, SWcontext::stencil_temp, swrast, SWRAST_CONTEXT(), gl_depthbuffer_attrib::Test, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, sw_span::y, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Referenced by _swrast_write_rgba_span().
_swrast_write_stencil_span()
void _swrast_write_stencil_span (struct gl_context * ctx, GLint n, GLint x, GLint y, const GLubyte stencil[])
Write a span of stencil values to the stencil buffer.
This function applies the stencil write mask when needed. Used for glDraw/CopyPixels Input: n - how many pixels x, y - location of first pixel stencil - the array of stencil values
References _mesa_pack_ubyte_stencil_row(), _mesa_unpack_ubyte_stencil_row(), _swrast_pixel_address(), gl_framebuffer::Attachment, SWcontext::buf1, SWcontext::buf2, BUFFER_STENCIL, gl_context::DrawBuffer, gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, SWcontext::stencil_temp, gl_config::stencilBits, swrast, SWRAST_CONTEXT(), gl_framebuffer::Visual, gl_renderbuffer::Width, and gl_stencil_attrib::WriteMask.
Referenced by _swrast_write_zoomed_stencil_span(), copy_stencil_pixels(), draw_depth_stencil_pixels(), and draw_stencil_pixels().