Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_span.h File Reference
#include "main/config.h"
#include "main/glheader.h"
#include "main/mtypes.h"
#include "swrast/s_chan.h"
#include "swrast/swrast.h"
Data Structures
struct sw_span_arrays
struct sw_span
The SWspan structure describes the colors, Z, fogcoord, texcoords, etc for either a horizontal run or an array of independent pixels.
Macros
#define SPAN_RGBA 0x01
interpMask and arrayMask
#define SPAN_Z 0x02
interpMask and arrayMask
#define SPAN_FLAT 0x04
interpMask: flat shading?
#define SPAN_XY 0x08
array.x[], y[] valid?
#define SPAN_MASK 0x10
was array.mask[] filled in by caller?
#define SPAN_LAMBDA 0x20
array.lambda[] valid?
#define SPAN_COVERAGE 0x40
array.coverage[] valid?
#define INIT_SPAN(S, PRIMITIVE)
Typedefs
typedef struct sw_span_arrays SWspanarrays
typedef struct sw_span SWspan
The SWspan structure describes the colors, Z, fogcoord, texcoords, etc for either a horizontal run or an array of independent pixels.
Functions
void _swrast_span_default_attribs (struct gl_context *ctx, SWspan *span)
Set default fragment attributes for the span using the current raster values.
void _swrast_span_interpolate_z (const struct gl_context *ctx, SWspan *span)
Fill in the span.zArray array from the span->z, zStep values.
GLfloat _swrast_compute_lambda (GLfloat dsdx, GLfloat dsdy, GLfloat dtdx, GLfloat dtdy, GLfloat dqdx, GLfloat dqdy, GLfloat texW, GLfloat texH, GLfloat s, GLfloat t, GLfloat q, GLfloat invQ)
Compute mipmap LOD from partial derivatives.
void _swrast_write_rgba_span (struct gl_context *ctx, SWspan *span)
Apply all the per-fragment operations to a span.
void _swrast_read_rgba_span (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint n, GLint x, GLint y, GLvoid *rgba)
Read float RGBA pixels from a renderbuffer.
void _swrast_put_row (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum datatype, GLuint count, GLint x, GLint y, const void *values, const GLubyte *mask)
Put row of colors into renderbuffer.
void * _swrast_get_dest_rgba (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span)
Get RGBA pixels from the given renderbuffer.
Macro Definition Documentation
INIT_SPAN
#define INIT_SPAN (S, PRIMITIVE)
Value:
do {                                            \
   (S).primitive = (PRIMITIVE);                 \
   (S).interpMask = 0x0;                        \
   (S).arrayMask = 0x0;                         \
   (S).arrayAttribs = 0x0;                      \
   (S).end = 0;                                 \
   (S).leftClip = 0;                            \
   (S).facing = 0;                              \
   (S).array = SWRAST_CONTEXT(ctx)->SpanArrays; \
} while (0)
Typedef Documentation
SWspan
typedef struct sw_span SWspan
The SWspan structure describes the colors, Z, fogcoord, texcoords, etc for either a horizontal run or an array of independent pixels.
We can either specify a base/step to indicate interpolated values, or fill in explicit arrays of values. The interpMask and arrayMask bitfields indicate which attributes are active interpolants or arrays, respectively.
It would be interesting to experiment with multiprocessor rasterization with this structure. The triangle rasterizer could simply emit a stream of these structures which would be consumed by one or more span-processing threads which could run in parallel.
SWspanarrays
typedef struct sw_span_arrays SWspanarrays
Arrays of fragment values.
These will either be computed from the span x/xStep values or filled in by glDraw/CopyPixels, etc. These arrays are separated out of sw_span to conserve memory.
Function Documentation
_swrast_compute_lambda()
GLfloat _swrast_compute_lambda (GLfloat dsdx, GLfloat dsdy, GLfloat dtdx, GLfloat dtdy, GLfloat dqdx, GLfloat dqdy, GLfloat texW, GLfloat texH, GLfloat s, GLfloat t, GLfloat q, GLfloat invQ)
Compute mipmap LOD from partial derivatives.
This the ideal solution, as given in the OpenGL spec.
References _swrast_compute_lambda(), and x.
Referenced by _swrast_compute_lambda(), fetch_texel_deriv(), and interpolate_texcoords().
_swrast_get_dest_rgba()
void* _swrast_get_dest_rgba (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span)
Get RGBA pixels from the given renderbuffer.
Used by blending, logicop and masking functions.
Returns
pointer to the colors we read.
References sw_span::array, sw_span::arrayMask, sw_span_arrays::attribs, sw_span_arrays::ChanType, sw_span::end, get_row(), get_values(), SPAN_XY, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_blend_span(), _swrast_logicop_rgba_span(), and _swrast_mask_rgba_span().
_swrast_put_row()
void _swrast_put_row (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum datatype, GLuint count, GLint x, GLint y, const void * values, const GLubyte * mask)
Put row of colors into renderbuffer.
References _mesa_get_format_bytes(), _mesa_pack_float_rgba_row(), _mesa_pack_ubyte_rgba_row(), _swrast_pixel_address(), gl_renderbuffer::Format, and GLuint.
Referenced by _swrast_write_rgba_span().
_swrast_read_rgba_span()
void _swrast_read_rgba_span (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint n, GLint x, GLint y, GLvoid * rgba)
Read float RGBA pixels from a renderbuffer.
Clipping will be done to prevent reading ouside the buffer's boundaries.
Parameters
rgba the returned colors
References gl_renderbuffer::_BaseFormat, _mesa_problem(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_rgba_row(), _swrast_pixel_address(), gl_renderbuffer::Format, gl_renderbuffer::Height, swrast_renderbuffer::Map, swrast_renderbuffer(), void, and gl_renderbuffer::Width.
Referenced by copy_rgba_pixels().
_swrast_span_default_attribs()
void _swrast_span_default_attribs (struct gl_context * ctx, SWspan * span)
Set default fragment attributes for the span using the current raster values.
Used prior to glDraw/CopyPixels and glBitmap.
References gl_framebuffer::_DepthMaxF, gl_ati_fragment_shader_state::_Enabled, SWcontext::_PreferPixelFog, _swrast_use_fragment_program(), _swrast_z_to_fogfactor(), sw_span::alpha, sw_span::alphaStep, gl_context::ATIFragmentShader, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, gl_fog_attrib::ColorSumEnabled, gl_context::Const, COPY_4V, gl_context::Current, gl_config::depthBits, gl_context::DrawBuffer, gl_light_attrib::Enabled, F, FloatToFixed, gl_context::Fog, GLuint, sw_span::green, sw_span::greenStep, sw_span::interpMask, IntToFixed, gl_context::Light, gl_constants::MaxTextureCoordUnits, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_current_attrib::RasterSecondaryColor, gl_current_attrib::RasterTexCoords, sw_span::red, sw_span::redStep, SPAN_RGBA, SPAN_Z, swrast, SWRAST_CONTEXT(), UNCLAMPED_FLOAT_TO_CHAN, gl_framebuffer::Visual, sw_span::z, and sw_span::zStep.
Referenced by _swrast_Bitmap(), copy_depth_pixels(), copy_rgba_pixels(), draw_depth_pixels(), and draw_rgba_pixels().
_swrast_span_interpolate_z()
void _swrast_span_interpolate_z (const struct gl_context * ctx, SWspan * span)
Fill in the span.zArray array from the span->z, zStep values.
References sw_span::array, sw_span::arrayMask, gl_config::depthBits, gl_context::DrawBuffer, sw_span::end, FixedToInt, GLuint, sw_span::interpMask, SPAN_Z, gl_framebuffer::Visual, sw_span_arrays::z, sw_span::z, and sw_span::zStep.
Referenced by _swrast_write_rgba_span(), and shade_texture_span().
_swrast_write_rgba_span()
void _swrast_write_rgba_span (struct gl_context * ctx, SWspan * span)
Apply all the per-fragment operations to a span.
This now includes texturing (_swrast_write_texture_span() is history). This function may modify any of the array values in the span. span->interpMask and span->arrayMask may be changed but will be restored to their original values before returning.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorDrawBuffers, gl_fragment_program_state::_Current, SWcontext::_DeferredTexture, gl_ati_fragment_shader_state::_Enabled, gl_stencil_attrib::_Enabled, gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, gl_framebuffer::_NumColorDrawBuffers, _swrast_alpha_test(), _swrast_blend_span(), _swrast_depth_bounds_test(), _swrast_depth_clamp_span(), _swrast_depth_test_span(), _swrast_fog_rgba_span(), _swrast_logicop_rgba_span(), _swrast_mask_rgba_span(), _swrast_put_row(), _swrast_span_interpolate_z(), _swrast_stencil_and_ztest_span(), _swrast_use_fragment_program(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, add_specular(), gl_colorbuffer_attrib::AlphaEnabled, apply_aa_coverage(), sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, gl_context::ATIFragmentShader, sw_span_arrays::attribs, gl_colorbuffer_attrib::BlendEnabled, gl_depthbuffer_attrib::BoundsTest, sw_span_arrays::ChanType, clamp_colors(), gl_colorbuffer_attrib::ClampFragmentColor, clip_span(), gl_context::Color, gl_lightmodel::ColorControl, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_fog_attrib::ColorSumEnabled, swrast_renderbuffer::ColorType, convert_color_type(), gl_query_state::CurrentOcclusionObject, gl_context::Depth, gl_config::depthBits, gl_transform_attrib::DepthClamp, gl_context::DrawBuffer, gl_light_attrib::Enabled, sw_span::end, gl_context::Fog, gl_context::FragmentProgram, GLuint, gl_program::info, sw_span::interpMask, interpolate_active_attribs(), interpolate_int_colors(), gl_context::Light, sw_span_arrays::mask, gl_light_attrib::Model, gl_context::Polygon, sw_span::primitive, put_values(), gl_context::Query, gl_query_object::Result, sw_span_arrays::rgba, sw_span_arrays::rgba8, shade_texture_span(), SPAN_COVERAGE, SPAN_MASK, SPAN_RGBA, SPAN_XY, SPAN_Z, SWcontext::SpecularVertexAdd, gl_context::Stencil, stipple_polygon_span(), gl_polygon_attrib::StippleFlag, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, gl_depthbuffer_attrib::Test, gl_context::Texture, gl_context::Transform, gl_framebuffer::Visual, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_Bitmap(), _swrast_flush(), copy_depth_pixels(), copy_rgba_pixels(), draw_depth_pixels(), draw_rgba_pixels(), draw_wide_line(), for(), if(), large_point(), line(), pixel_point(), plot(), smooth_point(), sprite_point(), and zoom_span().