Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_texture.c File Reference
#include "main/context.h"
#include "main/fbobject.h"
#include "main/teximage.h"
#include "main/texobj.h"
#include "swrast/swrast.h"
#include "swrast/s_context.h"
Functions
struct gl_texture_image * _swrast_new_texture_image (struct gl_context *ctx)
Functions for mapping/unmapping texture images.
void _swrast_delete_texture_image (struct gl_context *ctx, struct gl_texture_image *texImage)
Free a swrast_texture_image (a subclass of gl_texture_image).
static unsigned int texture_slices (const struct gl_texture_image *texImage)
unsigned int _swrast_teximage_slice_height (struct gl_texture_image *texImage)
GLboolean _swrast_alloc_texture_image_buffer (struct gl_context *ctx, struct gl_texture_image *texImage)
Called via ctx->Driver.AllocTextureImageBuffer()
GLboolean _swrast_init_texture_image (struct gl_texture_image *texImage)
Code that overrides ctx->Driver.AllocTextureImageBuffer may use this to initialize the fields of swrast_texture_image without allocating the image buffer or initializing RowStride or the contents of ImageSlices.
void _swrast_free_texture_image_buffer (struct gl_context *ctx, struct gl_texture_image *texImage)
Called via ctx->Driver.FreeTextureImageBuffer()
static void check_map_teximage (const struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h)
Error checking for debugging only.
void _swrast_map_teximage (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a 2D slice of a texture image into user space.
void _swrast_unmap_teximage (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice)
void _swrast_map_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
void _swrast_unmap_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
void _swrast_map_textures (struct gl_context *ctx)
Map all textures for reading prior to software rendering.
void _swrast_unmap_textures (struct gl_context *ctx)
Unmap all textures for reading prior to software rendering.
Function Documentation
_swrast_alloc_texture_image_buffer()
GLboolean _swrast_alloc_texture_image_buffer (struct gl_context * ctx, struct gl_texture_image * texImage)
Called via ctx->Driver.AllocTextureImageBuffer()
References _mesa_align_malloc(), _mesa_format_image_size(), _mesa_format_row_stride(), _swrast_init_texture_image(), _swrast_teximage_slice_height(), swrast_texture_image::Buffer, GLuint, swrast_texture_image::ImageSlices, swrast_texture_image::RowStride, swrast_texture_image(), gl_texture_image::TexFormat, texture_slices(), and gl_texture_image::Width.
_swrast_delete_texture_image()
void _swrast_delete_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free a swrast_texture_image (a subclass of gl_texture_image).
Called via ctx->Driver.DeleteTextureImage().
References _mesa_delete_texture_image().
_swrast_free_texture_image_buffer()
void _swrast_free_texture_image_buffer (struct gl_context * ctx, struct gl_texture_image * texImage)
Called via ctx->Driver.FreeTextureImageBuffer()
References _mesa_align_free(), swrast_texture_image::Buffer, swrast_texture_image::ImageSlices, and swrast_texture_image().
_swrast_init_texture_image()
GLboolean _swrast_init_texture_image (struct gl_texture_image * texImage)
Code that overrides ctx->Driver.AllocTextureImageBuffer may use this to initialize the fields of swrast_texture_image without allocating the image buffer or initializing RowStride or the contents of ImageSlices.
Returns GL_TRUE on success, GL_FALSE on memory allocation failure.
References swrast_texture_image::_IsPowerOfTwo, gl_texture_image::Depth, gl_texture_image::Depth2, swrast_texture_image::DepthScale, gl_texture_image::Height, gl_texture_image::Height2, swrast_texture_image::HeightScale, swrast_texture_image::ImageSlices, swrast_texture_image(), gl_texture_object::Target, gl_texture_image::TexObject, texture_slices(), gl_texture_image::Width, gl_texture_image::Width2, and swrast_texture_image::WidthScale.
Referenced by _swrast_alloc_texture_image_buffer().
_swrast_map_teximage()
void _swrast_map_teximage (struct gl_context * ctx, struct gl_texture_image * texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte ** mapOut, GLint * rowStrideOut)
Map a 2D slice of a texture image into user space.
(x,y,w,h) defines a region of interest (ROI). Reading/writing texels outside of the ROI is undefined.
Parameters
texImage the texture image
slice the 3D image slice or array texture slice
x,y,w,h region of interest
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT
mapOut returns start of mapping of region of interest
rowStrideOut returns row stride (in bytes)
References _mesa_format_row_stride(), _mesa_get_format_block_size(), _mesa_get_format_bytes(), swrast_texture_image::Buffer, check_map_teximage(), GLuint, swrast_texture_image::ImageSlices, swrast_texture_image(), gl_texture_image::TexFormat, and gl_texture_image::Width.
_swrast_map_texture()
void _swrast_map_texture (struct gl_context * ctx, struct gl_texture_object * texObj)
References gl_texture_object::BaseLevel, swrast_texture_image::Buffer, gl_context::Driver, GLuint, gl_texture_image::Height, gl_texture_object::Image, swrast_texture_image::ImageSlices, dd_function_table::MapTextureImage, MAX_TEXTURE_LEVELS, swrast_texture_image::RowStride, swrast_texture_image(), gl_texture_object::Target, texture_slices(), and gl_texture_image::Width.
Referenced by _swrast_map_textures(), and swrast_render_finish().
_swrast_map_textures()
void _swrast_map_textures (struct gl_context * ctx)
Map all textures for reading prior to software rendering.
References gl_texture_unit::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, _swrast_map_texture(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_span_render_start(), and swrast_render_finish().
_swrast_new_texture_image()
struct gl_texture_image* _swrast_new_texture_image (struct gl_context * ctx)
Functions for mapping/unmapping texture images.
Allocate a new swrast_texture_image (a subclass of gl_texture_image). Called via ctx->Driver.NewTextureImage().
References CALLOC_STRUCT, and void.
_swrast_teximage_slice_height()
unsigned int _swrast_teximage_slice_height (struct gl_texture_image * texImage)
References gl_texture_image::Height, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by _swrast_alloc_texture_image_buffer(), and swrast_render_finish().
_swrast_unmap_teximage()
void _swrast_unmap_teximage (struct gl_context * ctx, struct gl_texture_image * texImage, GLuint slice)
_swrast_unmap_texture()
void _swrast_unmap_texture (struct gl_context * ctx, struct gl_texture_object * texObj)
References gl_texture_object::BaseLevel, swrast_texture_image::Buffer, gl_context::Driver, GLuint, gl_texture_object::Image, swrast_texture_image::ImageSlices, MAX_TEXTURE_LEVELS, swrast_texture_image(), gl_texture_object::Target, texture_slices(), and dd_function_table::UnmapTextureImage.
Referenced by _swrast_unmap_textures(), and swrast_render_finish().
_swrast_unmap_textures()
void _swrast_unmap_textures (struct gl_context * ctx)
Unmap all textures for reading prior to software rendering.
References gl_texture_unit::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, _swrast_unmap_texture(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_span_render_finish(), and swrast_render_finish().
check_map_teximage()
static void check_map_teximage (const struct gl_texture_image * texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h) static
Error checking for debugging only.
References gl_texture_image::Height, gl_texture_object::Target, gl_texture_image::TexObject, texture_slices(), and gl_texture_image::Width.
Referenced by _swrast_map_teximage().
texture_slices()
static unsigned int texture_slices (const struct gl_texture_image * texImage) static
References gl_texture_image::Depth, gl_texture_image::Height, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by _swrast_alloc_texture_image_buffer(), _swrast_init_texture_image(), _swrast_map_texture(), _swrast_unmap_texture(), and check_map_teximage().