Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_texrender.c File Reference
#include "main/context.h"
#include "main/fbobject.h"
#include "main/macros.h"
#include "main/teximage.h"
#include "main/renderbuffer.h"
#include "swrast/swrast.h"
#include "swrast/s_context.h"
#include "swrast/s_texfetch.h"
Functions
static void delete_texture_wrapper (struct gl_context *ctx, struct gl_renderbuffer *rb)
static void update_wrapper (struct gl_context *ctx, struct gl_renderbuffer_attachment *att)
Update the renderbuffer wrapper for rendering to a texture.
void _swrast_render_texture (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Called when rendering to a texture image begins, or when changing the dest mipmap level, cube face, etc.
void _swrast_finish_render_texture (struct gl_context *ctx, struct gl_renderbuffer *rb)
Function Documentation
_swrast_finish_render_texture()
void _swrast_finish_render_texture (struct gl_context * ctx, struct gl_renderbuffer * rb)
References void.
_swrast_render_texture()
void _swrast_render_texture (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att)
Called when rendering to a texture image begins, or when changing the dest mipmap level, cube face, etc.
This is a fallback routine for software render-to-texture.
Called via the glRenderbufferTexture1D/2D/3D() functions and elsewhere (such as glTexImage2D).
The image we're rendering into is att->Texture->Image[att->CubeMapFace][att->TextureLevel]; It'll never be NULL.
Parameters
fb the framebuffer object the texture is being bound to
att the fb attachment point of the texture
See also
_mesa_FramebufferRenderbuffer_sw
References gl_renderbuffer::Delete, delete_texture_wrapper(), gl_renderbuffer_attachment::Renderbuffer, update_wrapper(), and void.
delete_texture_wrapper()
static void delete_texture_wrapper (struct gl_context * ctx, struct gl_renderbuffer * rb) static
References gl_renderbuffer::RefCount.
Referenced by _swrast_render_texture().
update_wrapper()
static void update_wrapper (struct gl_context * ctx, struct gl_renderbuffer_attachment * att) static
Update the renderbuffer wrapper for rendering to a texture.
For example, update the width, height of the RB based on the texture size, update the internal format info, etc.
References _mesa_get_srgb_format_linear(), swrast_texture_image::Base, swrast_renderbuffer::Buffer, gl_renderbuffer::Format, GLuint, swrast_texture_image::ImageSlices, gl_renderbuffer_attachment::Renderbuffer, swrast_renderbuffer(), swrast_texture_image(), gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, void, and gl_renderbuffer_attachment::Zoffset.
Referenced by _swrast_render_texture().