Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_texfilter.c File Reference
#include "c99_math.h"
#include "main/glheader.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/samplerobj.h"
#include "main/teximage.h"
#include "main/texobj.h"
#include "s_context.h"
#include "s_texfilter.h"
Macros
#define FRAC(f) ((f) - IFLOOR(f))
#define LERP(T, A, B) ((A) + (T) * ((B) - (A)))
Linear interpolation macro.
#define REMAINDER(A, B) (((A) + (B) * 1024) % (B))
Used for GL_REPEAT wrap mode.
#define I0BIT 1
#define I1BIT 2
#define J0BIT 4
#define J1BIT 8
#define K0BIT 16
#define K1BIT 32
#define WEIGHT_LUT_SIZE 1024
Functions
static GLfloat lerp_2d (GLfloat a, GLfloat b, GLfloat v00, GLfloat v10, GLfloat v01, GLfloat v11)
Do 2D/biliner interpolation of float values.
static GLfloat lerp_3d (GLfloat a, GLfloat b, GLfloat c, GLfloat v000, GLfloat v100, GLfloat v010, GLfloat v110, GLfloat v001, GLfloat v101, GLfloat v011, GLfloat v111)
Do 3D/trilinear interpolation of float values.
static void lerp_rgba (GLfloat result[4], GLfloat t, const GLfloat a[4], const GLfloat b[4])
Do linear interpolation of colors.
static void lerp_rgba_2d (GLfloat result[4], GLfloat a, GLfloat b, const GLfloat t00[4], const GLfloat t10[4], const GLfloat t01[4], const GLfloat t11[4])
Do bilinear interpolation of colors.
static void lerp_rgba_3d (GLfloat result[4], GLfloat a, GLfloat b, GLfloat c, const GLfloat t000[4], const GLfloat t100[4], const GLfloat t010[4], const GLfloat t110[4], const GLfloat t001[4], const GLfloat t101[4], const GLfloat t011[4], const GLfloat t111[4])
Do trilinear interpolation of colors.
static void linear_texel_locations (GLenum wrapMode, const struct gl_texture_image *img, GLint size, GLfloat s, GLint *i0, GLint *i1, GLfloat *weight)
Used to compute texel locations for linear sampling.
static GLint nearest_texel_location (GLenum wrapMode, const struct gl_texture_image *img, GLint size, GLfloat s)
Used to compute texel location for nearest sampling.
static void linear_repeat_texel_location (GLuint size, GLfloat s, GLint *i0, GLint *i1, GLfloat *weight)
static GLint clamp_rect_coord_nearest (GLenum wrapMode, GLfloat coord, GLint max)
Do clamp/wrap for a texture rectangle coord, GL_NEAREST filter mode.
static void clamp_rect_coord_linear (GLenum wrapMode, GLfloat coord, GLint max, GLint *i0out, GLint *i1out, GLfloat *weight)
As above, but GL_LINEAR filtering.
static GLint tex_array_slice (GLfloat coord, GLsizei size)
Compute slice/image to use for 1D or 2D array texture.
static void nearest_texcoord (const struct gl_sampler_object *samp, const struct gl_texture_object *texObj, GLuint level, const GLfloat texcoord[4], GLint *i, GLint *j, GLint *k)
Compute nearest integer texcoords for given texobj and coordinate.
static void linear_texcoord (const struct gl_sampler_object *samp, const struct gl_texture_object *texObj, GLuint level, const GLfloat texcoord[4], GLint *i0, GLint *i1, GLint *j0, GLint *j1, GLint *slice, GLfloat *wi, GLfloat *wj)
Compute linear integer texcoords for given texobj and coordinate.
static GLint linear_mipmap_level (const struct gl_texture_object *tObj, GLfloat lambda)
For linear interpolation between mipmap levels N and N+1, this function computes N.
static GLint nearest_mipmap_level (const struct gl_texture_object *tObj, GLfloat lambda)
Compute the nearest mipmap level to take texels from.
static void compute_min_mag_ranges (const struct gl_sampler_object *samp, GLuint n, const GLfloat lambda[], GLuint *minStart, GLuint *minEnd, GLuint *magStart, GLuint *magEnd)
The lambda[] array values are always monotonic.
static void get_border_color (const struct gl_sampler_object *samp, const struct gl_texture_image *img, GLfloat rgba[4])
When we sample the border color, it must be interpreted according to the base texture format.
static void apply_depth_mode (GLenum depthMode, GLfloat z, GLfloat texel[4])
Put z into texel according to GL_DEPTH_MODE.
static GLboolean is_depth_texture (const struct gl_texture_object *tObj)
Is the given texture a depth (or depth/stencil) texture?
static void sample_1d_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s) using GL_NEAREST filter.
static void sample_1d_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s) using GL_LINEAR filter.
static void sample_1d_nearest_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_1d_linear_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_1d_nearest_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_1d_linear_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_nearest_1d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 1D texture, nearest filtering for both min/magnification.
static void sample_linear_1d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 1D texture, linear filtering for both min/magnification.
static void sample_lambda_1d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 1D texture, using lambda to choose between min/magnification.
static void sample_2d_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[])
Return the texture sample for coordinate (s,t) using GL_NEAREST filter.
static void sample_2d_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[])
Return the texture sample for coordinate (s,t) using GL_LINEAR filter.
static void sample_2d_linear_repeat (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[])
As above, but we know WRAP_S == REPEAT and WRAP_T == REPEAT.
static void sample_2d_nearest_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_linear_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_nearest_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_linear_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_linear_mipmap_linear_repeat (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_nearest_2d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 2D texture, nearest filtering for both min/magnification.
static void sample_linear_2d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 2D texture, linear filtering for both min/magnification.
static void opt_sample_rgb_2d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Optimized 2-D texture sampling: S and T wrap mode == GL_REPEAT GL_NEAREST min/mag filter No border, RowStride == Width, Format = GL_RGB.
static void opt_sample_rgba_2d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Optimized 2-D texture sampling: S and T wrap mode == GL_REPEAT GL_NEAREST min/mag filter No border RowStride == Width, Format = GL_RGBA.
static void sample_lambda_2d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 2D texture, using lambda to choose between min/magnification.
static void create_filter_table (void)
Creates the look-up table used to speed-up EWA sampling.
static void sample_2d_ewa (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, const GLfloat texcoord[4], const GLfloat dudx, const GLfloat dvdx, const GLfloat dudy, const GLfloat dvdy, const GLint lod, GLfloat rgba[])
Elliptical weighted average (EWA) filter for producing high quality anisotropic filtered results.
static void sample_2d_footprint (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, const GLfloat texcoord[4], const GLfloat dudx, const GLfloat dvdx, const GLfloat dudy, const GLfloat dvdy, const GLint lod, GLfloat rgba[])
Anisotropic filtering using footprint assembly as outlined in the EXT_texture_filter_anisotropic spec: http://www.opengl.org/registry/specs/EXT/texture_filter_anisotropic.txt Faster than EWA but has less quality (more aliasing effects)
static GLuint texture_unit_index (const struct gl_context *ctx, const struct gl_texture_object *tObj)
Returns the index of the specified texture object in the gl_context texture unit array.
static void sample_lambda_2d_aniso (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda_iso[], GLfloat rgba[][4])
Sample 2D texture using an anisotropic filter.
static void sample_3d_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s,t,r) using GL_NEAREST filter.
static void sample_3d_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s,t,r) using GL_LINEAR filter.
static void sample_3d_nearest_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_3d_linear_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_3d_nearest_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_3d_linear_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_nearest_3d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 3D texture, nearest filtering for both min/magnification.
static void sample_linear_3d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 3D texture, linear filtering for both min/magnification.
static void sample_lambda_3d (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 3D texture, using lambda to choose between min/magnification.
static const struct gl_texture_image ** choose_cube_face (const struct gl_texture_object *texObj, const GLfloat texcoord[4], GLfloat newCoord[4])
Choose one of six sides of a texture cube map given the texture coord (rx,ry,rz).
static void sample_nearest_cube (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_linear_cube (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_cube_nearest_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_cube_linear_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_cube_nearest_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_cube_linear_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_lambda_cube (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample cube texture, using lambda to choose between min/magnification.
static void sample_nearest_rect (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_linear_rect (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_lambda_rect (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample Rect texture, using lambda to choose between min/magnification.
static void sample_2d_array_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s,t,r) using GL_NEAREST filter.
static void sample_2d_array_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s,t,r) using GL_LINEAR filter.
static void sample_2d_array_nearest_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_array_linear_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_array_nearest_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_2d_array_linear_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_nearest_2d_array (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 2D Array texture, nearest filtering for both min/magnification.
static void sample_linear_2d_array (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 2D Array texture, linear filtering for both min/magnification.
static void sample_lambda_2d_array (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 2D Array texture, using lambda to choose between min/magnification.
static void sample_1d_array_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s,t,r) using GL_NEAREST filter.
static void sample_1d_array_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_image *img, const GLfloat texcoord[4], GLfloat rgba[4])
Return the texture sample for coordinate (s,t,r) using GL_LINEAR filter.
static void sample_1d_array_nearest_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_1d_array_linear_mipmap_nearest (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_1d_array_nearest_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_1d_array_linear_mipmap_linear (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4])
static void sample_nearest_1d_array (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 1D Array texture, nearest filtering for both min/magnification.
static void sample_linear_1d_array (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 1D Array texture, linear filtering for both min/magnification.
static void sample_lambda_1d_array (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
Sample 1D Array texture, using lambda to choose between min/magnification.
static GLfloat shadow_compare (GLenum function, GLfloat coord, GLfloat depthSample)
Compare texcoord against depth sample.
static GLfloat shadow_compare4 (GLenum function, GLfloat coord, GLfloat depth00, GLfloat depth01, GLfloat depth10, GLfloat depth11, GLfloat wi, GLfloat wj)
Compare texcoord against four depth samples.
static int choose_depth_texture_level (const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLfloat lambda)
Choose the mipmap level to use when sampling from a depth texture.
static void sample_depth_texture (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat texel[][4])
Sample a shadow/depth texture.
static void null_sample_func (struct gl_context *ctx, const struct gl_sampler_object *samp, const struct gl_texture_object *tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4])
We use this function when a texture object is in an "incomplete" state.
texture_sample_func _swrast_choose_texture_sample_func (struct gl_context *ctx, const struct gl_texture_object *t, const struct gl_sampler_object *sampler)
Choose the texture sampling function for the given texture object.
Variables
static GLfloat * weightLut = NULL
Macro Definition Documentation
FRAC
#define FRAC (f) ((f) - IFLOOR(f))
Referenced by clamp_rect_coord_linear(), linear_repeat_texel_location(), linear_texel_locations(), sample_1d_array_linear_mipmap_linear(), sample_1d_array_nearest_mipmap_linear(), sample_1d_linear_mipmap_linear(), sample_1d_nearest_mipmap_linear(), sample_2d_array_linear_mipmap_linear(), sample_2d_array_nearest_mipmap_linear(), sample_2d_linear_mipmap_linear(), sample_2d_linear_mipmap_linear_repeat(), sample_2d_nearest_mipmap_linear(), sample_3d_linear_mipmap_linear(), sample_3d_nearest_mipmap_linear(), sample_cube_linear_mipmap_linear(), and sample_cube_nearest_mipmap_linear().
I0BIT
#define I0BIT 1
Referenced by sample_1d_array_linear(), sample_1d_linear(), sample_2d_array_linear(), sample_2d_linear(), sample_3d_linear(), sample_depth_texture(), and sample_linear_rect().
I1BIT
#define I1BIT 2
Referenced by sample_1d_array_linear(), sample_1d_linear(), sample_2d_array_linear(), sample_2d_linear(), sample_3d_linear(), sample_depth_texture(), and sample_linear_rect().
J0BIT
#define J0BIT 4
Referenced by sample_2d_array_linear(), sample_2d_linear(), sample_3d_linear(), sample_depth_texture(), and sample_linear_rect().
J1BIT
#define J1BIT 8
Referenced by sample_2d_array_linear(), sample_2d_linear(), sample_3d_linear(), sample_depth_texture(), and sample_linear_rect().
K0BIT
#define K0BIT 16
Referenced by sample_1d_array_linear(), and sample_3d_linear().
K1BIT
#define K1BIT 32
Referenced by sample_3d_linear().
LERP
#define LERP (T, A, B) ((A) + (T) * ((B) - (A)))
Linear interpolation macro.
Referenced by lerp_2d(), lerp_3d(), and lerp_rgba().
REMAINDER
#define REMAINDER (A, B) (((A) + (B) * 1024) % (B))
Used for GL_REPEAT wrap mode.
Using A % B doesn't produce the right results for A<0. Casting to A to be unsigned only works if B is a power of two. Adding a bias to A (which is a multiple of B) avoids the problems with A < 0 (for reasonable A) without using a conditional.
Referenced by linear_texel_locations(), and nearest_texel_location().
WEIGHT_LUT_SIZE
#define WEIGHT_LUT_SIZE 1024
Referenced by create_filter_table(), and sample_2d_ewa().
Function Documentation
_swrast_choose_texture_sample_func()
texture_sample_func _swrast_choose_texture_sample_func (struct gl_context * ctx, const struct gl_texture_object * t, const struct gl_sampler_object * sampler)
Choose the texture sampling function for the given texture object.
References swrast_texture_image::_IsPowerOfTwo, _mesa_problem(), gl_texture_image::Border, is_depth_texture(), gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_BGR_UNORM8, gl_sampler_object::MinFilter, null_sample_func(), opt_sample_rgb_2d(), opt_sample_rgba_2d(), sample_depth_texture(), sample_lambda_1d(), sample_lambda_1d_array(), sample_lambda_2d(), sample_lambda_2d_aniso(), sample_lambda_2d_array(), sample_lambda_3d(), sample_lambda_cube(), sample_lambda_rect(), sample_linear_1d(), sample_linear_1d_array(), sample_linear_2d(), sample_linear_2d_array(), sample_linear_3d(), sample_linear_cube(), sample_linear_rect(), sample_nearest_1d(), sample_nearest_1d_array(), sample_nearest_2d(), sample_nearest_2d_array(), sample_nearest_3d(), sample_nearest_cube(), sample_nearest_rect(), swrast_texture_image_const(), gl_texture_object::Target, gl_texture_image::TexFormat, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_update_texture_samplers().
apply_depth_mode()
static void apply_depth_mode (GLenum depthMode, GLfloat z, GLfloat texel[4]) static
Put z into texel according to GL_DEPTH_MODE.
References _mesa_problem(), and F.
Referenced by sample_cube_linear_mipmap_linear(), sample_cube_linear_mipmap_nearest(), sample_cube_nearest_mipmap_linear(), sample_cube_nearest_mipmap_nearest(), sample_depth_texture(), sample_linear_cube(), and sample_nearest_cube().
choose_cube_face()
static const struct gl_texture_image** choose_cube_face (const struct gl_texture_object * texObj, const GLfloat texcoord[4], GLfloat newCoord[4]) static
Choose one of six sides of a texture cube map given the texture coord (rx,ry,rz).
Return pointer to corresponding array of texture images.
References F, FACE_NEG_X, FACE_NEG_Y, FACE_NEG_Z, FACE_POS_X, FACE_POS_Y, FACE_POS_Z, GLuint, and gl_texture_object::Image.
Referenced by sample_cube_linear_mipmap_linear(), sample_cube_linear_mipmap_nearest(), sample_cube_nearest_mipmap_linear(), sample_cube_nearest_mipmap_nearest(), sample_linear_cube(), and sample_nearest_cube().
choose_depth_texture_level()
static int choose_depth_texture_level (const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLfloat lambda) static
Choose the mipmap level to use when sampling from a depth texture.
References gl_texture_object::_MaxLevel, gl_texture_object::BaseLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, and gl_sampler_object::MinLod.
Referenced by sample_depth_texture().
clamp_rect_coord_linear()
static void clamp_rect_coord_linear (GLenum wrapMode, GLfloat coord, GLint max, GLint * i0out, GLint * i1out, GLfloat * weight) static
As above, but GL_LINEAR filtering.
References _mesa_problem(), F, and FRAC.
Referenced by linear_texcoord(), and sample_linear_rect().
clamp_rect_coord_nearest()
static GLint clamp_rect_coord_nearest (GLenum wrapMode, GLfloat coord, GLint max) static
Do clamp/wrap for a texture rectangle coord, GL_NEAREST filter mode.
References _mesa_problem(), and F.
Referenced by nearest_texcoord(), and sample_nearest_rect().
compute_min_mag_ranges()
static void compute_min_mag_ranges (const struct gl_sampler_object * samp, GLuint n, const GLfloat lambda[], GLuint * minStart, GLuint * minEnd, GLuint * magStart, GLuint * magEnd) static
The lambda[] array values are always monotonic.
Either the whole span will be minified, magnified, or split between the two. This function determines the subranges in [0, n-1] that are to be minified or magnified.
References GLuint, gl_sampler_object::MagFilter, and gl_sampler_object::MinFilter.
Referenced by sample_lambda_1d(), sample_lambda_1d_array(), sample_lambda_2d(), sample_lambda_2d_array(), sample_lambda_3d(), sample_lambda_cube(), and sample_lambda_rect().
create_filter_table()
static void create_filter_table (void) static
Creates the look-up table used to speed-up EWA sampling.
References GLuint, WEIGHT_LUT_SIZE, and weightLut.
Referenced by sample_lambda_2d_aniso().
get_border_color()
static void get_border_color (const struct gl_sampler_object * samp, const struct gl_texture_image * img, GLfloat rgba[4]) static
When we sample the border color, it must be interpreted according to the base texture format.
Ex: if the texture base format it GL_ALPHA, we return (0,0,0,BorderAlpha).
References gl_texture_image::_BaseFormat, gl_sampler_object::BorderColor, COPY_4V, and gl_color_union::f.
Referenced by sample_1d_array_linear(), sample_1d_array_nearest(), sample_1d_linear(), sample_1d_nearest(), sample_2d_array_linear(), sample_2d_array_nearest(), sample_2d_linear(), sample_2d_nearest(), sample_3d_linear(), sample_3d_nearest(), sample_linear_rect(), and sample_nearest_rect().
is_depth_texture()
static GLboolean is_depth_texture (const struct gl_texture_object * tObj) static
Is the given texture a depth (or depth/stencil) texture?
References _mesa_texture_base_format().
Referenced by _swrast_choose_texture_sample_func(), sample_cube_linear_mipmap_linear(), sample_cube_linear_mipmap_nearest(), sample_cube_nearest_mipmap_linear(), sample_cube_nearest_mipmap_nearest(), sample_linear_cube(), and sample_nearest_cube().
lerp_2d()
static GLfloat lerp_2d (GLfloat a, GLfloat b, GLfloat v00, GLfloat v10, GLfloat v01, GLfloat v11) inline static
Do 2D/biliner interpolation of float values.
v00, v10, v01 and v11 are typically four texture samples in a square/box. a and b are the horizontal and vertical interpolants. It's important that this function is inlined when compiled with optimization! If we find that's not true on some systems, convert to a macro.
References LERP.
Referenced by lerp_rgba_2d(), and shadow_compare4().
lerp_3d()
static GLfloat lerp_3d (GLfloat a, GLfloat b, GLfloat c, GLfloat v000, GLfloat v100, GLfloat v010, GLfloat v110, GLfloat v001, GLfloat v101, GLfloat v011, GLfloat v111) static
Do 3D/trilinear interpolation of float values.
See also
lerp_2d
References LERP.
Referenced by lerp_rgba_3d().
lerp_rgba()
static void lerp_rgba (GLfloat result[4], GLfloat t, const GLfloat a[4], const GLfloat b[4]) static
Do linear interpolation of colors.
References LERP.
Referenced by sample_1d_array_linear(), sample_1d_array_linear_mipmap_linear(), sample_1d_array_nearest_mipmap_linear(), sample_1d_linear(), sample_1d_linear_mipmap_linear(), sample_1d_nearest_mipmap_linear(), sample_2d_array_linear_mipmap_linear(), sample_2d_array_nearest_mipmap_linear(), sample_2d_linear_mipmap_linear(), sample_2d_linear_mipmap_linear_repeat(), sample_2d_nearest_mipmap_linear(), sample_3d_linear_mipmap_linear(), sample_3d_nearest_mipmap_linear(), sample_cube_linear_mipmap_linear(), and sample_cube_nearest_mipmap_linear().
lerp_rgba_2d()
static void lerp_rgba_2d (GLfloat result[4], GLfloat a, GLfloat b, const GLfloat t00[4], const GLfloat t10[4], const GLfloat t01[4], const GLfloat t11[4]) static
Do bilinear interpolation of colors.
References lerp_2d().
Referenced by sample_2d_array_linear(), sample_2d_linear(), sample_2d_linear_repeat(), and sample_linear_rect().
lerp_rgba_3d()
static void lerp_rgba_3d (GLfloat result[4], GLfloat a, GLfloat b, GLfloat c, const GLfloat t000[4], const GLfloat t100[4], const GLfloat t010[4], const GLfloat t110[4], const GLfloat t001[4], const GLfloat t101[4], const GLfloat t011[4], const GLfloat t111[4]) static
Do trilinear interpolation of colors.
References GLuint, and lerp_3d().
Referenced by sample_3d_linear().
linear_mipmap_level()
static GLint linear_mipmap_level (const struct gl_texture_object * tObj, GLfloat lambda) static
For linear interpolation between mipmap levels N and N+1, this function computes N.
References gl_texture_object::_MaxLambda, gl_texture_object::BaseLevel, and F.
Referenced by sample_1d_array_linear_mipmap_linear(), sample_1d_array_nearest_mipmap_linear(), sample_1d_linear_mipmap_linear(), sample_1d_nearest_mipmap_linear(), sample_2d_array_linear_mipmap_linear(), sample_2d_array_nearest_mipmap_linear(), sample_2d_linear_mipmap_linear(), sample_2d_linear_mipmap_linear_repeat(), sample_2d_nearest_mipmap_linear(), sample_3d_linear_mipmap_linear(), sample_3d_nearest_mipmap_linear(), sample_cube_linear_mipmap_linear(), and sample_cube_nearest_mipmap_linear().
linear_repeat_texel_location()
static void linear_repeat_texel_location (GLuint size, GLfloat s, GLint * i0, GLint * i1, GLfloat * weight) static
References FRAC.
Referenced by sample_2d_linear_repeat().
linear_texcoord()
static void linear_texcoord (const struct gl_sampler_object * samp, const struct gl_texture_object * texObj, GLuint level, const GLfloat texcoord[4], GLint * i0, GLint * i1, GLint * j0, GLint * j1, GLint * slice, GLfloat * wi, GLfloat * wj) static
Compute linear integer texcoords for given texobj and coordinate.
NOTE: only used for depth texture sampling.
References clamp_rect_coord_linear(), gl_texture_image::Depth, gl_texture_image::Height, gl_texture_object::Image, linear_texel_locations(), gl_texture_object::Target, tex_array_slice(), gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_depth_texture().
linear_texel_locations()
static void linear_texel_locations (GLenum wrapMode, const struct gl_texture_image * img, GLint size, GLfloat s, GLint * i0, GLint * i1, GLfloat * weight) static
Used to compute texel locations for linear sampling.
Input: wrapMode = GL_REPEAT, GL_CLAMP, GL_CLAMP_TO_EDGE, GL_CLAMP_TO_BORDER s = texcoord in [0,1] size = width (or height or depth) of texture Output: i0, i1 = returns two nearest texel indexes weight = returns blend factor between texels
References swrast_texture_image::_IsPowerOfTwo, _mesa_problem(), F, FRAC, REMAINDER, and swrast_texture_image_const().
Referenced by linear_texcoord(), sample_1d_array_linear(), sample_1d_linear(), sample_2d_array_linear(), sample_2d_linear(), and sample_3d_linear().
nearest_mipmap_level()
static GLint nearest_mipmap_level (const struct gl_texture_object * tObj, GLfloat lambda) static
Compute the nearest mipmap level to take texels from.
References gl_texture_object::_MaxLambda, gl_texture_object::_MaxLevel, gl_texture_object::BaseLevel, and F.
Referenced by sample_1d_array_linear_mipmap_nearest(), sample_1d_array_nearest_mipmap_nearest(), sample_1d_linear_mipmap_nearest(), sample_1d_nearest_mipmap_nearest(), sample_2d_array_linear_mipmap_nearest(), sample_2d_array_nearest_mipmap_nearest(), sample_2d_linear_mipmap_nearest(), sample_2d_nearest_mipmap_nearest(), sample_3d_linear_mipmap_nearest(), sample_3d_nearest_mipmap_nearest(), sample_cube_linear_mipmap_nearest(), and sample_cube_nearest_mipmap_nearest().
nearest_texcoord()
static void nearest_texcoord (const struct gl_sampler_object * samp, const struct gl_texture_object * texObj, GLuint level, const GLfloat texcoord[4], GLint * i, GLint * j, GLint * k) static
Compute nearest integer texcoords for given texobj and coordinate.
NOTE: only used for depth texture sampling.
References clamp_rect_coord_nearest(), gl_texture_image::Depth, gl_texture_image::Height, gl_texture_object::Image, nearest_texel_location(), gl_texture_object::Target, tex_array_slice(), gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_depth_texture().
nearest_texel_location()
static GLint nearest_texel_location (GLenum wrapMode, const struct gl_texture_image * img, GLint size, GLfloat s) static
Used to compute texel location for nearest sampling.
References swrast_texture_image::_IsPowerOfTwo, _mesa_problem(), F, REMAINDER, and swrast_texture_image_const().
Referenced by nearest_texcoord(), sample_1d_array_nearest(), sample_1d_nearest(), sample_2d_array_nearest(), sample_2d_nearest(), and sample_3d_nearest().
null_sample_func()
static void null_sample_func (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
We use this function when a texture object is in an "incomplete" state.
When a fragment program attempts to sample an incomplete texture we return black (see issue 23 in GL_ARB_fragment_program spec). Note: fragment programs don't observe the texture enable/disable flags.
References ACOMP, BCOMP, GCOMP, GLuint, RCOMP, and void.
Referenced by _swrast_choose_texture_sample_func().
opt_sample_rgb_2d()
static void opt_sample_rgb_2d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Optimized 2-D texture sampling: S and T wrap mode == GL_REPEAT GL_NEAREST min/mag filter No border, RowStride == Width, Format = GL_RGB.
References swrast_texture_image::_IsPowerOfTwo, ACOMP, BCOMP, gl_texture_image::Border, GCOMP, GLuint, gl_texture_image::Height, swrast_texture_image::ImageSlices, MESA_FORMAT_BGR_UNORM8, RCOMP, swrast_texture_image_const(), gl_texture_image::TexFormat, UBYTE_TO_FLOAT, void, gl_texture_image::Width, gl_texture_image::WidthLog2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_2d().
opt_sample_rgba_2d()
static void opt_sample_rgba_2d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Optimized 2-D texture sampling: S and T wrap mode == GL_REPEAT GL_NEAREST min/mag filter No border RowStride == Width, Format = GL_RGBA.
References swrast_texture_image::_IsPowerOfTwo, ACOMP, BCOMP, gl_texture_image::Border, GCOMP, GLuint, gl_texture_image::Height, swrast_texture_image::ImageSlices, MESA_FORMAT_A8B8G8R8_UNORM, RCOMP, swrast_texture_image_const(), gl_texture_image::TexFormat, UBYTE_TO_FLOAT, void, gl_texture_image::Width, gl_texture_image::WidthLog2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_2d().
sample_1d_array_linear()
static void sample_1d_array_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s,t,r) using GL_LINEAR filter.
References gl_texture_image::Border, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height, I0BIT, I1BIT, K0BIT, lerp_rgba(), linear_texel_locations(), swrast_texture_image_const(), tex_array_slice(), gl_texture_image::Width2, and gl_sampler_object::WrapS.
Referenced by sample_1d_array_linear_mipmap_linear(), sample_1d_array_linear_mipmap_nearest(), sample_lambda_1d_array(), and sample_linear_1d_array().
sample_1d_array_linear_mipmap_linear()
static void sample_1d_array_linear_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_1d_array_linear().
Referenced by sample_lambda_1d_array().
sample_1d_array_linear_mipmap_nearest()
static void sample_1d_array_linear_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_1d_array_linear().
Referenced by sample_lambda_1d_array().
sample_1d_array_nearest()
static void sample_1d_array_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s,t,r) using GL_NEAREST filter.
References swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height, nearest_texel_location(), swrast_texture_image_const(), tex_array_slice(), void, gl_texture_image::Width, gl_texture_image::Width2, and gl_sampler_object::WrapS.
Referenced by sample_1d_array_nearest_mipmap_linear(), sample_1d_array_nearest_mipmap_nearest(), sample_lambda_1d_array(), and sample_nearest_1d_array().
sample_1d_array_nearest_mipmap_linear()
static void sample_1d_array_nearest_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_1d_array_nearest().
Referenced by sample_lambda_1d_array().
sample_1d_array_nearest_mipmap_nearest()
static void sample_1d_array_nearest_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_1d_array_nearest().
Referenced by sample_lambda_1d_array().
sample_1d_linear()
static void sample_1d_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s) using GL_LINEAR filter.
References gl_texture_image::Border, swrast_texture_image::FetchTexel, get_border_color(), I0BIT, I1BIT, lerp_rgba(), linear_texel_locations(), swrast_texture_image_const(), gl_texture_image::Width2, and gl_sampler_object::WrapS.
Referenced by sample_1d_linear_mipmap_linear(), sample_1d_linear_mipmap_nearest(), sample_lambda_1d(), and sample_linear_1d().
sample_1d_linear_mipmap_linear()
static void sample_1d_linear_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_1d_linear().
Referenced by sample_lambda_1d().
sample_1d_linear_mipmap_nearest()
static void sample_1d_linear_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_1d_linear().
Referenced by sample_lambda_1d().
sample_1d_nearest()
static void sample_1d_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s) using GL_NEAREST filter.
References gl_texture_image::Border, swrast_texture_image::FetchTexel, get_border_color(), nearest_texel_location(), swrast_texture_image_const(), gl_texture_image::Width, gl_texture_image::Width2, and gl_sampler_object::WrapS.
Referenced by sample_1d_nearest_mipmap_linear(), sample_1d_nearest_mipmap_nearest(), sample_lambda_1d(), and sample_nearest_1d().
sample_1d_nearest_mipmap_linear()
static void sample_1d_nearest_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_1d_nearest().
Referenced by sample_lambda_1d().
sample_1d_nearest_mipmap_nearest()
static void sample_1d_nearest_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_1d_nearest().
Referenced by sample_lambda_1d().
sample_2d_array_linear()
static void sample_2d_array_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s,t,r) using GL_LINEAR filter.
References gl_texture_image::Border, gl_sampler_object::BorderColor, COPY_4V, gl_texture_image::Depth, gl_color_union::f, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height2, I0BIT, I1BIT, J0BIT, J1BIT, lerp_rgba_2d(), linear_texel_locations(), swrast_texture_image_const(), tex_array_slice(), gl_texture_image::Width2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_2d_array_linear_mipmap_linear(), sample_2d_array_linear_mipmap_nearest(), sample_lambda_2d_array(), and sample_linear_2d_array().
sample_2d_array_linear_mipmap_linear()
static void sample_2d_array_linear_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_2d_array_linear().
Referenced by sample_lambda_2d_array().
sample_2d_array_linear_mipmap_nearest()
static void sample_2d_array_linear_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_2d_array_linear().
Referenced by sample_lambda_2d_array().
sample_2d_array_nearest()
static void sample_2d_array_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s,t,r) using GL_NEAREST filter.
References gl_texture_image::Depth, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height, gl_texture_image::Height2, nearest_texel_location(), swrast_texture_image_const(), tex_array_slice(), void, gl_texture_image::Width, gl_texture_image::Width2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_2d_array_nearest_mipmap_linear(), sample_2d_array_nearest_mipmap_nearest(), sample_lambda_2d_array(), and sample_nearest_2d_array().
sample_2d_array_nearest_mipmap_linear()
static void sample_2d_array_nearest_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_2d_array_nearest().
Referenced by sample_lambda_2d_array().
sample_2d_array_nearest_mipmap_nearest()
static void sample_2d_array_nearest_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_2d_array_nearest().
Referenced by sample_lambda_2d_array().
sample_2d_ewa()
static void sample_2d_ewa (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, const GLfloat texcoord[4], const GLfloat dudx, const GLfloat dvdx, const GLfloat dudy, const GLfloat dvdy, const GLint lod, GLfloat rgba[]) static
Elliptical weighted average (EWA) filter for producing high quality anisotropic filtered results.
Based on the Higher Quality Elliptical Weighted Avarage Filter published by Paul S. Heckbert in his Master's Thesis "Fundamentals of Texture Mapping and Image Warping" (1989)
References A, B, F, gl_texture_image::Height2, swrast_texture_image::HeightScale, gl_texture_object::Image, sample_2d_linear(), sample_2d_nearest(), swrast_texture_image_const(), WEIGHT_LUT_SIZE, weightLut, gl_texture_image::Width2, and swrast_texture_image::WidthScale.
Referenced by sample_lambda_2d_aniso().
sample_2d_footprint()
static void sample_2d_footprint (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, const GLfloat texcoord[4], const GLfloat dudx, const GLfloat dvdx, const GLfloat dudy, const GLfloat dvdy, const GLint lod, GLfloat rgba[]) static
Anisotropic filtering using footprint assembly as outlined in the EXT_texture_filter_anisotropic spec: http://www.opengl.org/registry/specs/EXT/texture_filter_anisotropic.txt Faster than EWA but has less quality (more aliasing effects)
References GLuint, gl_texture_image::Height2, gl_texture_object::Image, sample_2d_linear(), and gl_texture_image::Width2.
Referenced by sample_lambda_2d_aniso().
sample_2d_linear()
static void sample_2d_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[]) static
Return the texture sample for coordinate (s,t) using GL_LINEAR filter.
New sampling code contributed by Lynn Quam quam@.nosp@m.ai.s.nosp@m.ri.co.nosp@m.m.
References gl_texture_image::Border, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height2, I0BIT, I1BIT, J0BIT, J1BIT, lerp_rgba_2d(), linear_texel_locations(), swrast_texture_image_const(), gl_texture_image::Width2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_2d_ewa(), sample_2d_footprint(), sample_2d_linear_mipmap_linear(), sample_2d_linear_mipmap_nearest(), sample_cube_linear_mipmap_linear(), sample_cube_linear_mipmap_nearest(), sample_lambda_2d_aniso(), sample_linear_2d(), and sample_linear_cube().
sample_2d_linear_mipmap_linear()
static void sample_2d_linear_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_2d_linear().
Referenced by sample_lambda_2d().
sample_2d_linear_mipmap_linear_repeat()
static void sample_2d_linear_mipmap_linear_repeat (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), sample_2d_linear_repeat(), gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_lambda_2d().
sample_2d_linear_mipmap_nearest()
static void sample_2d_linear_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_2d_linear().
Referenced by sample_lambda_2d().
sample_2d_linear_repeat()
static void sample_2d_linear_repeat (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[]) static
As above, but we know WRAP_S == REPEAT and WRAP_T == REPEAT.
We don't have to worry about the texture border.
References swrast_texture_image::_IsPowerOfTwo, gl_texture_image::Border, swrast_texture_image::FetchTexel, gl_texture_image::Height2, lerp_rgba_2d(), linear_repeat_texel_location(), swrast_texture_image_const(), void, gl_texture_image::Width2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_2d_linear_mipmap_linear_repeat(), and sample_linear_2d().
sample_2d_nearest()
static void sample_2d_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[]) static
Return the texture sample for coordinate (s,t) using GL_NEAREST filter.
References gl_texture_image::Border, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height, gl_texture_image::Height2, nearest_texel_location(), swrast_texture_image_const(), void, gl_texture_image::Width, gl_texture_image::Width2, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_2d_ewa(), sample_2d_nearest_mipmap_linear(), sample_2d_nearest_mipmap_nearest(), sample_cube_nearest_mipmap_linear(), sample_cube_nearest_mipmap_nearest(), sample_nearest_2d(), and sample_nearest_cube().
sample_2d_nearest_mipmap_linear()
static void sample_2d_nearest_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_2d_nearest().
Referenced by sample_lambda_2d().
sample_2d_nearest_mipmap_nearest()
static void sample_2d_nearest_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_2d_nearest().
Referenced by sample_lambda_2d().
sample_3d_linear()
static void sample_3d_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s,t,r) using GL_LINEAR filter.
References gl_texture_image::Border, gl_texture_image::Depth2, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height2, I0BIT, I1BIT, J0BIT, J1BIT, K0BIT, K1BIT, lerp_rgba_3d(), linear_texel_locations(), swrast_texture_image_const(), gl_texture_image::Width2, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_3d_linear_mipmap_linear(), sample_3d_linear_mipmap_nearest(), sample_lambda_3d(), and sample_linear_3d().
sample_3d_linear_mipmap_linear()
static void sample_3d_linear_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_3d_linear().
Referenced by sample_lambda_3d().
sample_3d_linear_mipmap_nearest()
static void sample_3d_linear_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_3d_linear().
Referenced by sample_lambda_3d().
sample_3d_nearest()
static void sample_3d_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_image * img, const GLfloat texcoord[4], GLfloat rgba[4]) static
Return the texture sample for coordinate (s,t,r) using GL_NEAREST filter.
References gl_texture_image::Depth, gl_texture_image::Depth2, swrast_texture_image::FetchTexel, get_border_color(), gl_texture_image::Height, gl_texture_image::Height2, nearest_texel_location(), swrast_texture_image_const(), void, gl_texture_image::Width, gl_texture_image::Width2, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by sample_3d_nearest_mipmap_linear(), sample_3d_nearest_mipmap_nearest(), sample_lambda_3d(), and sample_nearest_3d().
sample_3d_nearest_mipmap_linear()
static void sample_3d_nearest_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, FRAC, GLuint, gl_texture_object::Image, lerp_rgba(), linear_mipmap_level(), and sample_3d_nearest().
Referenced by sample_lambda_3d().
sample_3d_nearest_mipmap_nearest()
static void sample_3d_nearest_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References GLuint, gl_texture_object::Image, nearest_mipmap_level(), and sample_3d_nearest().
Referenced by sample_lambda_3d().
sample_cube_linear_mipmap_linear()
static void sample_cube_linear_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, apply_depth_mode(), choose_cube_face(), gl_texture_object::DepthMode, FRAC, GLuint, is_depth_texture(), lerp_rgba(), linear_mipmap_level(), and sample_2d_linear().
Referenced by sample_lambda_cube().
sample_cube_linear_mipmap_nearest()
static void sample_cube_linear_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References apply_depth_mode(), choose_cube_face(), gl_texture_object::DepthMode, GLuint, is_depth_texture(), nearest_mipmap_level(), and sample_2d_linear().
Referenced by sample_lambda_cube().
sample_cube_nearest_mipmap_linear()
static void sample_cube_nearest_mipmap_linear (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References gl_texture_object::_MaxLevel, apply_depth_mode(), choose_cube_face(), gl_texture_object::DepthMode, FRAC, GLuint, is_depth_texture(), lerp_rgba(), linear_mipmap_level(), and sample_2d_nearest().
Referenced by sample_lambda_cube().
sample_cube_nearest_mipmap_nearest()
static void sample_cube_nearest_mipmap_nearest (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoord[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References apply_depth_mode(), choose_cube_face(), gl_texture_object::DepthMode, GLuint, is_depth_texture(), nearest_mipmap_level(), and sample_2d_nearest().
Referenced by sample_lambda_cube().
sample_depth_texture()
static void sample_depth_texture (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat texel[][4]) static
Sample a shadow/depth texture.
This function is incomplete. It doesn't check for minification vs. magnification, etc.
References gl_texture_image::_BaseFormat, apply_depth_mode(), gl_texture_image::Border, gl_sampler_object::BorderColor, choose_depth_texture_level(), gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_texture_image::Depth, gl_texture_object::DepthMode, gl_color_union::f, F, swrast_texture_image::FetchTexel, GLuint, gl_texture_image::Height, I0BIT, I1BIT, if(), gl_texture_object::Image, J0BIT, J1BIT, linear_texcoord(), gl_sampler_object::MagFilter, nearest_texcoord(), shadow_compare(), shadow_compare4(), swrast_texture_image_const(), gl_texture_object::Target, and gl_texture_image::Width.
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_1d()
static void sample_lambda_1d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 1D texture, using lambda to choose between min/magnification.
References _mesa_problem(), compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, sample_1d_linear(), sample_1d_linear_mipmap_linear(), sample_1d_linear_mipmap_nearest(), sample_1d_nearest(), sample_1d_nearest_mipmap_linear(), and sample_1d_nearest_mipmap_nearest().
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_1d_array()
static void sample_lambda_1d_array (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 1D Array texture, using lambda to choose between min/magnification.
References _mesa_problem(), compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, sample_1d_array_linear(), sample_1d_array_linear_mipmap_linear(), sample_1d_array_linear_mipmap_nearest(), sample_1d_array_nearest(), sample_1d_array_nearest_mipmap_linear(), and sample_1d_array_nearest_mipmap_nearest().
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_2d()
static void sample_lambda_2d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 2D texture, using lambda to choose between min/magnification.
References swrast_texture_image::_IsPowerOfTwo, _mesa_format_row_stride(), _mesa_problem(), gl_texture_image::Border, compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_BGR_UNORM8, gl_sampler_object::MinFilter, opt_sample_rgb_2d(), opt_sample_rgba_2d(), swrast_texture_image::RowStride, sample_2d_linear_mipmap_linear(), sample_2d_linear_mipmap_linear_repeat(), sample_2d_linear_mipmap_nearest(), sample_2d_nearest_mipmap_linear(), sample_2d_nearest_mipmap_nearest(), sample_linear_2d(), sample_nearest_2d(), swrast_texture_image_const(), gl_texture_image::TexFormat, gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_2d_aniso()
static void sample_lambda_2d_aniso (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda_iso[], GLfloat rgba[][4]) static
Sample 2D texture using an anisotropic filter.
NOTE: the const GLfloat lambda_iso[] parameter does NOT contain the lambda float array but a "hidden" SWspan struct which is required by this function but is not available in the texture_sample_func signature. See _swrast_texture_span(struct gl_context *ctx, SWspan *span) on how this function is called.
References gl_texture_object::_MaxLevel, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, gl_context::Const, create_filter_table(), F, GLuint, swrast_texture_image::HeightScale, gl_texture_object::Image, sw_span::leftClip, gl_texture_unit::LodBias, gl_sampler_object::LodBias, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_constants::MaxTextureLodBias, gl_sampler_object::MinLod, sample_2d_ewa(), sample_2d_footprint(), sample_2d_linear(), span, swrast_texture_image_const(), gl_context::Texture, texture_unit_index(), gl_texture_attrib::Unit, void, weightLut, and swrast_texture_image::WidthScale.
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_2d_array()
static void sample_lambda_2d_array (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 2D Array texture, using lambda to choose between min/magnification.
References _mesa_problem(), compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, sample_2d_array_linear(), sample_2d_array_linear_mipmap_linear(), sample_2d_array_linear_mipmap_nearest(), sample_2d_array_nearest(), sample_2d_array_nearest_mipmap_linear(), and sample_2d_array_nearest_mipmap_nearest().
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_3d()
static void sample_lambda_3d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 3D texture, using lambda to choose between min/magnification.
References _mesa_problem(), compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, sample_3d_linear(), sample_3d_linear_mipmap_linear(), sample_3d_linear_mipmap_nearest(), sample_3d_nearest(), sample_3d_nearest_mipmap_linear(), and sample_3d_nearest_mipmap_nearest().
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_cube()
static void sample_lambda_cube (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample cube texture, using lambda to choose between min/magnification.
References _mesa_problem(), compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, sample_cube_linear_mipmap_linear(), sample_cube_linear_mipmap_nearest(), sample_cube_nearest_mipmap_linear(), sample_cube_nearest_mipmap_nearest(), sample_linear_cube(), and sample_nearest_cube().
Referenced by _swrast_choose_texture_sample_func().
sample_lambda_rect()
static void sample_lambda_rect (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample Rect texture, using lambda to choose between min/magnification.
References compute_min_mag_ranges(), GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, sample_linear_rect(), and sample_nearest_rect().
Referenced by _swrast_choose_texture_sample_func().
sample_linear_1d()
static void sample_linear_1d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 1D texture, linear filtering for both min/magnification.
References GLuint, sample_1d_linear(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_linear_1d_array()
static void sample_linear_1d_array (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 1D Array texture, linear filtering for both min/magnification.
References GLuint, sample_1d_array_linear(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_linear_2d()
static void sample_linear_2d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 2D texture, linear filtering for both min/magnification.
References swrast_texture_image::_IsPowerOfTwo, gl_texture_image::Border, GLuint, sample_2d_linear(), sample_2d_linear_repeat(), swrast_texture_image_const(), void, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_2d().
sample_linear_2d_array()
static void sample_linear_2d_array (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 2D Array texture, linear filtering for both min/magnification.
References GLuint, sample_2d_array_linear(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_linear_3d()
static void sample_linear_3d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 3D texture, linear filtering for both min/magnification.
References GLuint, sample_3d_linear(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_linear_cube()
static void sample_linear_cube (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References apply_depth_mode(), gl_texture_object::BaseLevel, choose_cube_face(), gl_texture_object::DepthMode, GLuint, is_depth_texture(), sample_2d_linear(), and void.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_cube().
sample_linear_rect()
static void sample_linear_rect (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References clamp_rect_coord_linear(), swrast_texture_image::FetchTexel, get_border_color(), GLuint, gl_texture_image::Height, I0BIT, I1BIT, gl_texture_object::Image, J0BIT, J1BIT, lerp_rgba_2d(), swrast_texture_image_const(), void, gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_rect().
sample_nearest_1d()
static void sample_nearest_1d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 1D texture, nearest filtering for both min/magnification.
References GLuint, sample_1d_nearest(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_nearest_1d_array()
static void sample_nearest_1d_array (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 1D Array texture, nearest filtering for both min/magnification.
References GLuint, sample_1d_array_nearest(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_nearest_2d()
static void sample_nearest_2d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 2D texture, nearest filtering for both min/magnification.
References GLuint, sample_2d_nearest(), and void.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_2d().
sample_nearest_2d_array()
static void sample_nearest_2d_array (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 2D Array texture, nearest filtering for both min/magnification.
References GLuint, sample_2d_array_nearest(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_nearest_3d()
static void sample_nearest_3d (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
Sample 3D texture, nearest filtering for both min/magnification.
References GLuint, sample_3d_nearest(), and void.
Referenced by _swrast_choose_texture_sample_func().
sample_nearest_cube()
static void sample_nearest_cube (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References apply_depth_mode(), gl_texture_object::BaseLevel, choose_cube_face(), gl_texture_object::DepthMode, GLuint, is_depth_texture(), sample_2d_nearest(), and void.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_cube().
sample_nearest_rect()
static void sample_nearest_rect (struct gl_context * ctx, const struct gl_sampler_object * samp, const struct gl_texture_object * tObj, GLuint n, const GLfloat texcoords[][4], const GLfloat lambda[], GLfloat rgba[][4]) static
References clamp_rect_coord_nearest(), swrast_texture_image::FetchTexel, get_border_color(), GLuint, gl_texture_image::Height, gl_texture_object::Image, swrast_texture_image_const(), void, gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_choose_texture_sample_func(), and sample_lambda_rect().
shadow_compare()
static GLfloat shadow_compare (GLenum function, GLfloat coord, GLfloat depthSample) static
Compare texcoord against depth sample.
Return 1.0 or 0.0 value.
References _mesa_problem().
Referenced by sample_depth_texture().
shadow_compare4()
static GLfloat shadow_compare4 (GLenum function, GLfloat coord, GLfloat depth00, GLfloat depth01, GLfloat depth10, GLfloat depth11, GLfloat wi, GLfloat wj) static
Compare texcoord against four depth samples.
References _mesa_problem(), and lerp_2d().
Referenced by sample_depth_texture().
tex_array_slice()
static GLint tex_array_slice (GLfloat coord, GLsizei size) static
Compute slice/image to use for 1D or 2D array texture.
Referenced by linear_texcoord(), nearest_texcoord(), sample_1d_array_linear(), sample_1d_array_nearest(), sample_2d_array_linear(), and sample_2d_array_nearest().
texture_unit_index()
static GLuint texture_unit_index (const struct gl_context * ctx, const struct gl_texture_object * tObj) static
Returns the index of the specified texture object in the gl_context texture unit array.
References gl_texture_unit::_Current, gl_texture_attrib::_EnabledCoordUnits, gl_context::Const, for(), GLuint, gl_constants::MaxTextureUnits, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by sample_lambda_2d_aniso().
Variable Documentation
weightLut
GLfloat* weightLut = NULL static
Referenced by create_filter_table(), sample_2d_ewa(), and sample_lambda_2d_aniso().