Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_triangle.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/state.h"
#include "main/samplerobj.h"
#include "main/teximage.h"
#include "program/prog_instruction.h"
#include "s_aatriangle.h"
#include "s_context.h"
#include "s_feedback.h"
#include "s_span.h"
#include "s_triangle.h"
#include "s_tritemp.h"
Macros
#define NAME flat_rgba_triangle
#define INTERP_Z 1
#define SETUP_CODE
#define RENDER_SPAN(span) _swrast_write_rgba_span(ctx, &span);
#define NAME smooth_rgba_triangle
#define INTERP_Z 1
#define INTERP_RGB 1
#define INTERP_ALPHA 1
#define SETUP_CODE
#define RENDER_SPAN(span) _swrast_write_rgba_span(ctx, &span);
#define NAME simple_textured_triangle
#define INTERP_INT_TEX 1
#define S_SCALE twidth
#define T_SCALE theight
#define SETUP_CODE
#define RENDER_SPAN(span)
#define NAME simple_z_textured_triangle
#define INTERP_Z 1
#define DEPTH_TYPE DEFAULT_SOFTWARE_DEPTH_TYPE
#define INTERP_INT_TEX 1
#define S_SCALE twidth
#define T_SCALE theight
#define SETUP_CODE
#define RENDER_SPAN(span)
#define NAME general_triangle
#define INTERP_Z 1
#define INTERP_RGB 1
#define INTERP_ALPHA 1
#define INTERP_ATTRIBS 1
#define RENDER_SPAN(span) _swrast_write_rgba_span(ctx, &span);
#define NAME occlusion_zless_16_triangle
#define INTERP_Z 1
#define SETUP_CODE
#define RENDER_SPAN(span)
#define USE(triFunc) swrast->Triangle = triFunc;
Functions
GLboolean _swrast_culltriangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Test if a triangle should be culled.
static void nodraw_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_add_spec_terms_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_choose_triangle (struct gl_context *ctx)
Macro Definition Documentation
DEPTH_TYPE
#define DEPTH_TYPE DEFAULT_SOFTWARE_DEPTH_TYPE
Referenced by NAME().
INTERP_ALPHA [1/2]
#define INTERP_ALPHA 1
INTERP_ALPHA [2/2]
#define INTERP_ALPHA 1
INTERP_ATTRIBS
#define INTERP_ATTRIBS 1
INTERP_INT_TEX [1/2]
#define INTERP_INT_TEX 1
INTERP_INT_TEX [2/2]
#define INTERP_INT_TEX 1
INTERP_RGB [1/2]
#define INTERP_RGB 1
INTERP_RGB [2/2]
#define INTERP_RGB 1
INTERP_Z [1/5]
#define INTERP_Z 1
INTERP_Z [2/5]
#define INTERP_Z 1
INTERP_Z [3/5]
#define INTERP_Z 1
INTERP_Z [4/5]
#define INTERP_Z 1
INTERP_Z [5/5]
#define INTERP_Z 1
NAME [1/6]
#define NAME flat_rgba_triangle
NAME [2/6]
#define NAME smooth_rgba_triangle
NAME [3/6]
#define NAME simple_textured_triangle
NAME [4/6]
#define NAME simple_z_textured_triangle
NAME [5/6]
#define NAME general_triangle
NAME [6/6]
#define NAME occlusion_zless_16_triangle
RENDER_SPAN [1/6]
#define RENDER_SPAN (span) _swrast_write_rgba_span(ctx, &span);
RENDER_SPAN [2/6]
#define RENDER_SPAN (span) _swrast_write_rgba_span(ctx, &span);
RENDER_SPAN [3/6]
#define RENDER_SPAN (span)
Value:
GLuint i;                                                               \
   GLubyte (*rgba)[4] = swrast->SpanArrays->rgba8;                      \
   span.intTex[0] -= FIXED_HALF; /* off-by-one error? */                \
   span.intTex[1] -= FIXED_HALF;                                        \
   for (i = 0; i < span.end; i++) {                                     \
      GLint s = FixedToInt(span.intTex[0]) & smask;                     \
      GLint t = FixedToInt(span.intTex[1]) & tmask;                     \
      GLint pos = (t << twidth_log2) + s;                               \
      pos = pos + pos + pos;  /* multiply by 3 */                       \
      rgba[i][RCOMP] = texture[pos+2];                                  \
      rgba[i][GCOMP] = texture[pos+1];                                  \
      rgba[i][BCOMP] = texture[pos+0];                                  \
      rgba[i][ACOMP] = 0xff;                                            \
      span.intTex[0] += span.intTexStep[0];                             \
      span.intTex[1] += span.intTexStep[1];                             \
   }                                                                    \
   _swrast_put_row(ctx, rb, GL_UNSIGNED_BYTE, span.end,                 \
                   span.x, span.y, rgba, NULL);
RENDER_SPAN [4/6]
#define RENDER_SPAN (span)
Value:
GLuint i;                                                               \
   GLubyte (*rgba)[4] = swrast->SpanArrays->rgba8;                      \
   GLubyte *mask = swrast->SpanArrays->mask;                            \
   span.intTex[0] -= FIXED_HALF; /* off-by-one error? */                \
   span.intTex[1] -= FIXED_HALF;                                        \
   for (i = 0; i < span.end; i++) {                                     \
      const GLuint z = FixedToDepth(span.z);                            \
      if (z < zRow[i]) {                                                \
         GLint s = FixedToInt(span.intTex[0]) & smask;                  \
         GLint t = FixedToInt(span.intTex[1]) & tmask;                  \
         GLint pos = (t << twidth_log2) + s;                            \
         pos = pos + pos + pos;  /* multiply by 3 */                    \
         rgba[i][RCOMP] = texture[pos+2];                               \
         rgba[i][GCOMP] = texture[pos+1];                               \
         rgba[i][BCOMP] = texture[pos+0];                               \
         rgba[i][ACOMP] = 0xff;                                         \
         zRow[i] = z;                                                   \
         mask[i] = 1;                                                   \
      }                                                                 \
      else {                                                            \
         mask[i] = 0;                                                   \
      }                                                                 \
      span.intTex[0] += span.intTexStep[0];                             \
      span.intTex[1] += span.intTexStep[1];                             \
      span.z += span.zStep;                                             \
   }                                                                    \
   _swrast_put_row(ctx, rb, GL_UNSIGNED_BYTE,                           \
                   span.end, span.x, span.y, rgba, mask);
RENDER_SPAN [5/6]
#define RENDER_SPAN (span) _swrast_write_rgba_span(ctx, &span);
RENDER_SPAN [6/6]
#define RENDER_SPAN (span)
Value:
{                                                                    \
      GLuint i;                                                         \
      const GLushort *zRow = (const GLushort *)                         \
         _swrast_pixel_address(rb, span.x, span.y);                     \
      for (i = 0; i < span.end; i++) {                                  \
         GLuint z = FixedToDepth(span.z);                               \
         if (z < zRow[i]) {                                             \
            q->Result++;                                                \
         }                                                              \
         span.z += span.zStep;                                          \
      }                                                                 \
   }
S_SCALE [1/2]
#define S_SCALE twidth
Referenced by NAME().
S_SCALE [2/2]
#define S_SCALE twidth
SETUP_CODE [1/5]
#define SETUP_CODE
Value:
assert(ctx->Texture._EnabledCoordUnits == 0);\
   assert(ctx->Light.ShadeModel==GL_FLAT);      \
   span.interpMask |= SPAN_RGBA;                \
   span.red = ChanToFixed(v2->color[0]);        \
   span.green = ChanToFixed(v2->color[1]);      \
   span.blue = ChanToFixed(v2->color[2]);       \
   span.alpha = ChanToFixed(v2->color[3]);      \
   span.redStep = 0;                            \
   span.greenStep = 0;                          \
   span.blueStep = 0;                           \
   span.alphaStep = 0;
Referenced by NAME().
SETUP_CODE [2/5]
#define SETUP_CODE
Value:
{                                               \
      /* texturing must be off */               \
      assert(ctx->Texture._EnabledCoordUnits == 0);     \
      assert(ctx->Light.ShadeModel==GL_SMOOTH); \
   }
SETUP_CODE [3/5]
#define SETUP_CODE
Value:
struct gl_renderbuffer *rb = ctx->DrawBuffer->_ColorDrawBuffers[0];     \
   const struct gl_texture_object *obj =                                \
      ctx->Texture.Unit[0].CurrentTex[TEXTURE_2D_INDEX];                \
   const struct gl_texture_image *texImg =                              \
      _mesa_base_tex_image(obj);                                        \
   const struct swrast_texture_image *swImg =                           \
      swrast_texture_image_const(texImg);                               \
   const GLfloat twidth = (GLfloat) texImg->Width;                      \
   const GLfloat theight = (GLfloat) texImg->Height;                    \
   const GLint twidth_log2 = texImg->WidthLog2;                         \
   const GLubyte *texture = (const GLubyte *) swImg->ImageSlices[0];    \
   const GLint smask = texImg->Width - 1;                               \
   const GLint tmask = texImg->Height - 1;                              \
   assert(texImg->TexFormat == MESA_FORMAT_BGR_UNORM8);                 \
   if (!rb || !texture) {                                               \
      return;                                                           \
   }
SETUP_CODE [4/5]
#define SETUP_CODE
Value:
struct gl_renderbuffer *rb = ctx->DrawBuffer->_ColorDrawBuffers[0];     \
   const struct gl_texture_object *obj =                                \
      ctx->Texture.Unit[0].CurrentTex[TEXTURE_2D_INDEX];                \
   const struct gl_texture_image *texImg =                              \
      _mesa_base_tex_image(obj);                                        \
   const struct swrast_texture_image *swImg =                           \
      swrast_texture_image_const(texImg);                               \
   const GLfloat twidth = (GLfloat) texImg->Width;                      \
   const GLfloat theight = (GLfloat) texImg->Height;                    \
   const GLint twidth_log2 = texImg->WidthLog2;                         \
   const GLubyte *texture = (const GLubyte *) swImg->ImageSlices[0];    \
   const GLint smask = texImg->Width - 1;                               \
   const GLint tmask = texImg->Height - 1;                              \
   assert(texImg->TexFormat == MESA_FORMAT_BGR_UNORM8);                 \
   if (!rb || !texture) {                                               \
      return;                                                           \
   }
SETUP_CODE [5/5]
#define SETUP_CODE
Value:
struct gl_renderbuffer *rb =                                         \
      ctx->DrawBuffer->Attachment[BUFFER_DEPTH].Renderbuffer;           \
   struct gl_query_object *q = ctx->Query.CurrentOcclusionObject;       \
   assert(ctx->Depth.Test);                                             \
   assert(!ctx->Depth.Mask);                                            \
   assert(ctx->Depth.Func == GL_LESS);                                  \
   assert(rb->Format == MESA_FORMAT_Z_UNORM16);                               \
   if (!q) {                                                            \
      return;                                                           \
   }
T_SCALE [1/2]
#define T_SCALE theight
Referenced by NAME().
T_SCALE [2/2]
#define T_SCALE theight
USE
#define USE (triFunc) swrast->Triangle = triFunc;
Referenced by _swrast_choose_triangle().
Function Documentation
_swrast_add_spec_terms_triangle()
void _swrast_add_spec_terms_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References SWvertex::attrib, CHAN_TO_FLOAT, SWvertex::color, COPY_CHAN4, SWcontext::SpecTriangle, SWRAST_CONTEXT(), and UNCLAMPED_FLOAT_TO_CHAN.
Referenced by _swrast_validate_triangle().
_swrast_choose_triangle()
void _swrast_choose_triangle (struct gl_context * ctx)
References gl_texture_unit::_Current, gl_stencil_attrib::_Enabled, gl_ati_fragment_shader_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, swrast_texture_image::_IsPowerOfTwo, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_format_row_stride(), SWcontext::_RasterMask, gl_texture_object::_Swizzle, _swrast_feedback_triangle(), _swrast_select_triangle(), _swrast_set_aa_triangle_function(), _swrast_use_fragment_program(), gl_context::ATIFragmentShader, gl_framebuffer::Attachment, gl_texture_image::Border, BUFFER_DEPTH, gl_context::Color, gl_lightmodel::ColorControl, gl_colorbuffer_attrib::ColorMask, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_query_state::CurrentOcclusionObject, gl_texture_unit::CurrentTex, gl_context::Depth, DEPTH_BIT, gl_config::depthBits, gl_context::DrawBuffer, gl_texture_unit::EnvMode, gl_renderbuffer::Format, gl_depthbuffer_attrib::Func, gl_context::Hint, gl_context::Light, gl_sampler_object::MagFilter, gl_depthbuffer_attrib::Mask, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_NONE, MESA_FORMAT_Z_UNORM16, gl_sampler_object::MinFilter, gl_light_attrib::Model, nodraw_triangle(), gl_hint_attrib::PerspectiveCorrection, gl_context::Polygon, gl_context::Query, gl_renderbuffer_attachment::Renderbuffer, gl_context::RenderMode, swrast_texture_image::RowStride, gl_texture_unit::Sampler, gl_texture_object::Sampler, gl_light_attrib::ShadeModel, gl_polygon_attrib::SmoothFlag, gl_context::Stencil, gl_polygon_attrib::StippleFlag, swrast, SWRAST_CONTEXT(), swrast_texture_image_const(), gl_texture_object::Target, gl_depthbuffer_attrib::Test, gl_texture_image::TexFormat, gl_context::Texture, TEXTURE_2D_INDEX, TEXTURE_BIT, SWcontext::Triangle, gl_texture_attrib::Unit, USE, gl_framebuffer::Visual, gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_CreateContext().
_swrast_culltriangle()
GLboolean _swrast_culltriangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
Test if a triangle should be culled.
Used for feedback and selection mode.
Returns
GL_TRUE if the triangle is to be culled, GL_FALSE otherwise.
References SWcontext::_BackfaceCullSign, SWcontext::_BackfaceSign, SWvertex::attrib, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_feedback_triangle(), and _swrast_select_triangle().
nodraw_triangle()
static void nodraw_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
References void.
Referenced by _swrast_choose_triangle().