Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_tritemp.h File Reference
Macros
#define MAX_GLUINT 0xffffffffu
#define CLAMP_INTERPOLANT(CHANNEL, CHANNELSTEP, LEN)
Functions
static void NAME (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Macro Definition Documentation
CLAMP_INTERPOLANT
#define CLAMP_INTERPOLANT (CHANNEL, CHANNELSTEP, LEN)
Value:
do {                                                            \
   GLfixed endVal = span.CHANNEL + (LEN) * span.CHANNELSTEP;    \
   if (endVal < 0) {                                            \
      span.CHANNEL -= endVal;                                   \
   }                                                            \
   if (span.CHANNEL < 0) {                                      \
      span.CHANNEL = 0;                                         \
   }                                                            \
} while (0)
Referenced by NAME().
MAX_GLUINT
#define MAX_GLUINT 0xffffffffu
Referenced by NAME().
Function Documentation
NAME()
static void NAME (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
References SWcontext::_BackfaceCullSign, SWcontext::_BackfaceSign, gl_framebuffer::_DepthMaxF, SWcontext::_InterpMode, _swrast_pixel_address(), ACOMP, sw_span::alpha, sw_span::alphaStep, area, gl_framebuffer::Attachment, SWvertex::attrib, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, BCOMP, bf, sw_span::blue, sw_span::blueStep, BUFFER_DEPTH, ChanToFixed, CLAMP_INTERPOLANT, SWvertex::color, DEPTH_TYPE, gl_config::depthBits, gl_context::DrawBuffer, dxdy, sw_span::end, F, sw_span::facing, FIXED_EPSILON, FIXED_HALF, FIXED_ONE, FIXED_SCALE, FIXED_SHIFT, FixedCeil, FixedFloor, FixedToFloat, FixedToInt, FloatToFixed, GCOMP, GLuint, sw_span::green, sw_span::greenStep, INIT_SPAN(), sw_span::interpMask, sw_span::intTex, sw_span::intTexStep, IS_INF_OR_NAN, gl_context::Light, MAX_GLUINT, RCOMP, sw_span::red, sw_span::redStep, RENDER_SPAN, gl_renderbuffer_attachment::Renderbuffer, S_SCALE, SETUP_CODE, gl_light_attrib::ShadeModel, SignedFloatToFixed, span, SPAN_FLAT, SPAN_RGBA, SPAN_Z, SUB_PIXEL_BITS, swrast, SWRAST_CONTEXT(), T_SCALE, gl_framebuffer::Visual, vMax, vMid, vMin, void, gl_framebuffer::Width, sw_span::x, sw_span::y, sw_span::z, and sw_span::zStep.