Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_texfetch.c File Reference
Texel fetch/store functions.
#include "main/macros.h"
#include "main/texcompress.h"
#include "main/texcompress_fxt1.h"
#include "main/texcompress_s3tc.h"
#include "main/texcompress_rgtc.h"
#include "main/texcompress_etc.h"
#include "main/teximage.h"
#include "main/samplerobj.h"
#include "s_context.h"
#include "s_texfetch.h"
#include "util/format_rgb9e5.h"
#include "util/format_r11g11b10f.h"
#include "util/format_srgb.h"
#include "s_texfetch_tmp.h"
Macros
#define DIM 1
#define DIM 2
#define DIM 3
#define FETCH_FUNCS(NAME)
#define FETCH_NULL(NAME)
#define FETCH_COMPRESSED(NAME)
Functions
static void fetch_compressed (const struct swrast_texture_image *swImage, GLint i, GLint j, GLint k, GLfloat *texel)
All compressed texture texel fetching is done though this function.
static void fetch_null_texelf (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
Null texel fetch function.
static void set_fetch_functions (const struct gl_sampler_object *samp, struct swrast_texture_image *texImage, GLuint dims)
Initialize the texture image's FetchTexel methods.
void _mesa_update_fetch_functions (struct gl_context *ctx, GLuint unit)
Variables
struct {
mesa_format Name
FetchTexelFunc Fetch1D
FetchTexelFunc Fetch2D
FetchTexelFunc Fetch3D
} texfetch_funcs []
Table to map MESA_FORMAT_ to texel fetch/store funcs.
Detailed Description
Texel fetch/store functions.
Author
Gareth Hughes
Macro Definition Documentation
DIM [1/3]
#define DIM 1
DIM [2/3]
#define DIM 2
DIM [3/3]
#define DIM 3
FETCH_COMPRESSED
#define FETCH_COMPRESSED (NAME)
Value:
{                            \
      MESA_FORMAT_ ## NAME,     \
      fetch_compressed,         \
      fetch_compressed,         \
      fetch_compressed          \
   }
FETCH_FUNCS
#define FETCH_FUNCS (NAME)
Value:
{                            \
      MESA_FORMAT_ ## NAME,     \
      fetch_texel_1d_ ## NAME,  \
      fetch_texel_2d_ ## NAME,  \
      fetch_texel_3d_ ## NAME,  \
   }
FETCH_NULL
#define FETCH_NULL (NAME)
Value:
{                            \
      MESA_FORMAT_ ## NAME,     \
      NULL,                     \
      NULL,                     \
      NULL                      \
   }
Function Documentation
_mesa_update_fetch_functions()
void _mesa_update_fetch_functions (struct gl_context * ctx, GLuint unit)
References gl_texture_unit::_Current, _mesa_get_texture_dimensions(), GLuint, gl_texture_object::Image, MAX_TEXTURE_LEVELS, set_fetch_functions(), swrast_texture_image(), gl_texture_object::Target, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_update_texture_samplers().
fetch_compressed()
static void fetch_compressed (const struct swrast_texture_image * swImage, GLint i, GLint j, GLint k, GLfloat * texel) static
All compressed texture texel fetching is done though this function.
Basically just call a core-Mesa texel fetch function.
References _mesa_get_format_block_size(), _mesa_get_format_bytes(), swrast_texture_image::Base, swrast_texture_image::FetchCompressedTexel, GLuint, swrast_texture_image::ImageSlices, swrast_texture_image::RowStride, and gl_texture_image::TexFormat.
fetch_null_texelf()
static void fetch_null_texelf (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
Null texel fetch function.
Have to have this so the FetchTexel function pointer is never NULL.
References _mesa_warning(), ACOMP, BCOMP, GCOMP, RCOMP, and void.
set_fetch_functions()
static void set_fetch_functions (const struct gl_sampler_object * samp, struct swrast_texture_image * texImage, GLuint dims) static
Initialize the texture image's FetchTexel methods.
References _mesa_get_compressed_fetch_func(), _mesa_get_format_color_encoding(), _mesa_get_srgb_format_linear(), swrast_texture_image::Base, swrast_texture_image::FetchCompressedTexel, swrast_texture_image::FetchTexel, MESA_FORMAT_COUNT, Name, gl_sampler_object::sRGBDecode, texfetch_funcs, and gl_texture_image::TexFormat.
Referenced by _mesa_update_fetch_functions().
Variable Documentation
Fetch1D
FetchTexelFunc Fetch1D
Fetch2D
FetchTexelFunc Fetch2D
Fetch3D
FetchTexelFunc Fetch3D
Name
mesa_format Name
Referenced by set_fetch_functions().
texfetch_funcs
struct { ... } texfetch_funcs[]
Table to map MESA_FORMAT_ to texel fetch/store funcs.
Referenced by set_fetch_functions().