Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_texfetch.h File Reference
#include "swrast/s_context.h"
Functions
void _mesa_update_fetch_functions (struct gl_context *ctx, GLuint unit)
Function Documentation
_mesa_update_fetch_functions()
void _mesa_update_fetch_functions (struct gl_context * ctx, GLuint unit)
References gl_texture_unit::_Current, _mesa_get_texture_dimensions(), GLuint, gl_texture_object::Image, MAX_TEXTURE_LEVELS, set_fetch_functions(), swrast_texture_image(), gl_texture_object::Target, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _swrast_update_texture_samplers().