Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_triangle.h File Reference
#include "swrast.h"
Functions
GLboolean _swrast_culltriangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Test if a triangle should be culled.
void _swrast_choose_triangle (struct gl_context *ctx)
void _swrast_add_spec_terms_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Function Documentation
_swrast_add_spec_terms_triangle()
void _swrast_add_spec_terms_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References SWvertex::attrib, CHAN_TO_FLOAT, SWvertex::color, COPY_CHAN4, SWcontext::SpecTriangle, SWRAST_CONTEXT(), and UNCLAMPED_FLOAT_TO_CHAN.
Referenced by _swrast_validate_triangle().
_swrast_choose_triangle()
void _swrast_choose_triangle (struct gl_context * ctx)
References gl_texture_unit::_Current, gl_stencil_attrib::_Enabled, gl_ati_fragment_shader_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, swrast_texture_image::_IsPowerOfTwo, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_format_row_stride(), SWcontext::_RasterMask, gl_texture_object::_Swizzle, _swrast_feedback_triangle(), _swrast_select_triangle(), _swrast_set_aa_triangle_function(), _swrast_use_fragment_program(), gl_context::ATIFragmentShader, gl_framebuffer::Attachment, gl_texture_image::Border, BUFFER_DEPTH, gl_context::Color, gl_lightmodel::ColorControl, gl_colorbuffer_attrib::ColorMask, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_query_state::CurrentOcclusionObject, gl_texture_unit::CurrentTex, gl_context::Depth, DEPTH_BIT, gl_config::depthBits, gl_context::DrawBuffer, gl_texture_unit::EnvMode, gl_renderbuffer::Format, gl_depthbuffer_attrib::Func, gl_context::Hint, gl_context::Light, gl_sampler_object::MagFilter, gl_depthbuffer_attrib::Mask, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_NONE, MESA_FORMAT_Z_UNORM16, gl_sampler_object::MinFilter, gl_light_attrib::Model, nodraw_triangle(), gl_hint_attrib::PerspectiveCorrection, gl_context::Polygon, gl_context::Query, gl_renderbuffer_attachment::Renderbuffer, gl_context::RenderMode, swrast_texture_image::RowStride, gl_texture_unit::Sampler, gl_texture_object::Sampler, gl_light_attrib::ShadeModel, gl_polygon_attrib::SmoothFlag, gl_context::Stencil, gl_polygon_attrib::StippleFlag, swrast, SWRAST_CONTEXT(), swrast_texture_image_const(), gl_texture_object::Target, gl_depthbuffer_attrib::Test, gl_texture_image::TexFormat, gl_context::Texture, TEXTURE_2D_INDEX, TEXTURE_BIT, SWcontext::Triangle, gl_texture_attrib::Unit, USE, gl_framebuffer::Visual, gl_texture_image::Width, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_CreateContext().
_swrast_culltriangle()
GLboolean _swrast_culltriangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
Test if a triangle should be culled.
Used for feedback and selection mode.
Returns
GL_TRUE if the triangle is to be culled, GL_FALSE otherwise.
References SWcontext::_BackfaceCullSign, SWcontext::_BackfaceSign, SWvertex::attrib, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_feedback_triangle(), and _swrast_select_triangle().