Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_zoom.h File Reference
#include "main/mtypes.h"
#include "s_span.h"
Functions
void _swrast_write_zoomed_rgba_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span, const GLvoid *rgba)
void _swrast_write_zoomed_rgb_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span, const GLvoid *rgb)
void _swrast_write_zoomed_depth_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span)
void _swrast_write_zoomed_stencil_span (struct gl_context *ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLubyte stencil[])
Zoom/write stencil values.
void _swrast_write_zoomed_z_span (struct gl_context *ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLuint *zVals)
Zoom/write 32-bit Z values.
Function Documentation
_swrast_write_zoomed_depth_span()
void _swrast_write_zoomed_depth_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span)
References sw_span::array, sw_span_arrays::z, and zoom_span().
Referenced by copy_depth_pixels(), and draw_depth_pixels().
_swrast_write_zoomed_rgb_span()
void _swrast_write_zoomed_rgb_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span, const GLvoid * rgb)
References zoom_span().
_swrast_write_zoomed_rgba_span()
void _swrast_write_zoomed_rgba_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span, const GLvoid * rgba)
References zoom_span().
Referenced by copy_rgba_pixels(), and draw_rgba_pixels().
_swrast_write_zoomed_stencil_span()
void _swrast_write_zoomed_stencil_span (struct gl_context * ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLubyte stencil[])
Zoom/write stencil values.
No per-fragment operations are applied.
References _swrast_write_stencil_span(), compute_zoomed_bounds(), gl_context::Pixel, SWRAST_MAX_WIDTH, unzoom_x(), y1, and gl_pixel_attrib::ZoomX.
Referenced by copy_stencil_pixels(), draw_depth_stencil_pixels(), and draw_stencil_pixels().
_swrast_write_zoomed_z_span()
void _swrast_write_zoomed_z_span (struct gl_context * ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLuint * zVals)
Zoom/write 32-bit Z values.
No per-fragment operations are applied.
References _mesa_pack_uint_z_row(), _swrast_pixel_address(), gl_framebuffer::Attachment, BUFFER_DEPTH, compute_zoomed_bounds(), gl_context::DrawBuffer, gl_renderbuffer::Format, GLuint, gl_context::Pixel, gl_renderbuffer_attachment::Renderbuffer, SWRAST_MAX_WIDTH, unzoom_x(), y1, and gl_pixel_attrib::ZoomX.
Referenced by draw_depth_stencil_pixels().