Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_zoom.c File Reference
#include "main/glheader.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/format_pack.h"
#include "s_context.h"
#include "s_span.h"
#include "s_stencil.h"
#include "s_zoom.h"
Functions
static GLboolean compute_zoomed_bounds (struct gl_context *ctx, GLint imageX, GLint imageY, GLint spanX, GLint spanY, GLint width, GLint *x0, GLint *x1, GLint *y0, GLint *y1)
Compute the bounds of the region resulting from zooming a pixel span.
static GLint unzoom_x (GLfloat zoomX, GLint imageX, GLint zx)
Convert a zoomed x image coordinate back to an unzoomed x coord.
static void zoom_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span, const GLvoid *src, GLenum format)
Helper function called from _swrast_write_zoomed_rgba/rgb/ index/depth_span().
void _swrast_write_zoomed_rgba_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span, const GLvoid *rgba)
void _swrast_write_zoomed_rgb_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span, const GLvoid *rgb)
void _swrast_write_zoomed_depth_span (struct gl_context *ctx, GLint imgX, GLint imgY, const SWspan *span)
void _swrast_write_zoomed_stencil_span (struct gl_context *ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLubyte stencil[])
Zoom/write stencil values.
void _swrast_write_zoomed_z_span (struct gl_context *ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLuint *zVals)
Zoom/write 32-bit Z values.
Function Documentation
_swrast_write_zoomed_depth_span()
void _swrast_write_zoomed_depth_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span)
References sw_span::array, sw_span_arrays::z, and zoom_span().
Referenced by copy_depth_pixels(), and draw_depth_pixels().
_swrast_write_zoomed_rgb_span()
void _swrast_write_zoomed_rgb_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span, const GLvoid * rgb)
References zoom_span().
_swrast_write_zoomed_rgba_span()
void _swrast_write_zoomed_rgba_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span, const GLvoid * rgba)
References zoom_span().
Referenced by copy_rgba_pixels(), and draw_rgba_pixels().
_swrast_write_zoomed_stencil_span()
void _swrast_write_zoomed_stencil_span (struct gl_context * ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLubyte stencil[])
Zoom/write stencil values.
No per-fragment operations are applied.
References _swrast_write_stencil_span(), compute_zoomed_bounds(), gl_context::Pixel, SWRAST_MAX_WIDTH, unzoom_x(), y1, and gl_pixel_attrib::ZoomX.
Referenced by copy_stencil_pixels(), draw_depth_stencil_pixels(), and draw_stencil_pixels().
_swrast_write_zoomed_z_span()
void _swrast_write_zoomed_z_span (struct gl_context * ctx, GLint imgX, GLint imgY, GLint width, GLint spanX, GLint spanY, const GLuint * zVals)
Zoom/write 32-bit Z values.
No per-fragment operations are applied.
References _mesa_pack_uint_z_row(), _swrast_pixel_address(), gl_framebuffer::Attachment, BUFFER_DEPTH, compute_zoomed_bounds(), gl_context::DrawBuffer, gl_renderbuffer::Format, GLuint, gl_context::Pixel, gl_renderbuffer_attachment::Renderbuffer, SWRAST_MAX_WIDTH, unzoom_x(), y1, and gl_pixel_attrib::ZoomX.
Referenced by draw_depth_stencil_pixels().
compute_zoomed_bounds()
static GLboolean compute_zoomed_bounds (struct gl_context * ctx, GLint imageX, GLint imageY, GLint spanX, GLint spanY, GLint width, GLint * x0, GLint * x1, GLint * y0, GLint * y1) static
Compute the bounds of the region resulting from zooming a pixel span.
The resulting region will be entirely inside the window/scissor bounds so no additional clipping is needed.
Parameters
imageX,imageY position of the mage being drawn (gl WindowPos)
spanX,spanY position of span being drawing
width number of pixels in span
x0,x1 returned X bounds of zoomed region [x0, x1)
y0,y1 returned Y bounds of zoomed region [y0, y1)
Returns
GL_TRUE if any zoomed pixels visible, GL_FALSE if totally clipped
References gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_context::DrawBuffer, gl_context::Pixel, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by _swrast_write_zoomed_stencil_span(), _swrast_write_zoomed_z_span(), and zoom_span().
unzoom_x()
static GLint unzoom_x (GLfloat zoomX, GLint imageX, GLint zx) inline static
Convert a zoomed x image coordinate back to an unzoomed x coord.
'zx' is screen position of a pixel in the zoomed image, who's left edge is at 'imageX'. return corresponding x coord in the original, unzoomed image. This can use this for unzooming X or Y values.
References F, and x.
Referenced by _swrast_write_zoomed_stencil_span(), _swrast_write_zoomed_z_span(), and zoom_span().
zoom_span()
static void zoom_span (struct gl_context * ctx, GLint imgX, GLint imgY, const SWspan * span, const GLvoid * src, GLenum format) static
Helper function called from _swrast_write_zoomed_rgba/rgb/ index/depth_span().
References _mesa_problem(), _swrast_write_rgba_span(), sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, sw_span_arrays::attribs, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, sw_span_arrays::ChanType, compute_zoomed_bounds(), COPY_4V, sw_span::end, GLuint, GLushort, sw_span::green, sw_span::greenStep, if(), INIT_SPAN(), sw_span::interpMask, gl_context::Pixel, sw_span::primitive, sw_span::red, sw_span::redStep, sw_span_arrays::rgba, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, SPAN_XY, SPAN_Z, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, unzoom_x(), sw_span::x, sw_span::y, y1, sw_span_arrays::z, sw_span::z, SWcontext::ZoomedArrays, gl_pixel_attrib::ZoomX, and sw_span::zStep.
Referenced by _swrast_write_zoomed_depth_span(), _swrast_write_zoomed_rgb_span(), and _swrast_write_zoomed_rgba_span().