Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
swrast_device_driver Struct Reference
The driver interface for the software rasterizer.
#include <swrast.h>
Data Fields
void(* SpanRenderStart)(struct gl_context *ctx)
void(* SpanRenderFinish)(struct gl_context *ctx)
Detailed Description
The driver interface for the software rasterizer.
XXX this may go away. We may move these functions to ctx->Driver.RenderStart, RenderEnd.
Field Documentation
SpanRenderFinish
void(* swrast_device_driver::SpanRenderFinish) (struct gl_context *ctx)
Referenced by _swrast_CreateContext(), _swrast_render_finish(), and swrast_render_finish().
SpanRenderStart
void(* swrast_device_driver::SpanRenderStart) (struct gl_context *ctx)
Referenced by _swrast_CreateContext(), _swrast_render_start(), and swrast_render_start().
The documentation for this struct was generated from the following file:
swrast.h