Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
swrast.h File Reference
Public interface to the software rasterization functions.
#include "main/mtypes.h"
#include "swrast/s_chan.h"
Data Structures
struct SWvertex
Data-structure to handle vertices in the software rasterizer.
struct swrast_device_driver
The driver interface for the software rasterizer.
Macros
#define TRIANGLE_WALK_DOUBLE 0
If non-zero use GLdouble for walking triangle edges, for better accuracy.
#define DEFAULT_SOFTWARE_DEPTH_BITS 16
Bits per depth buffer value (max is 32).
#define DEFAULT_SOFTWARE_DEPTH_TYPE GLushort
Depth buffer data type.
#define SWRAST_MAX_WIDTH 16384
Max image/surface/texture size.
#define SWRAST_MAX_HEIGHT 16384
#define VARYING_SLOT_CI VARYING_SLOT_COL0
Functions
GLboolean _swrast_CreateContext (struct gl_context *ctx)
void _swrast_DestroyContext (struct gl_context *ctx)
struct swrast_device_driver * _swrast_GetDeviceDriverReference (struct gl_context *ctx)
void _swrast_Bitmap (struct gl_context *ctx, GLint px, GLint py, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
Render a bitmap.
void _swrast_CopyPixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLint destx, GLint desty, GLsizei width, GLsizei height, GLenum type)
GLboolean swrast_fast_copy_pixels (struct gl_context *ctx, struct gl_framebuffer *srcFb, struct gl_framebuffer *dstFb, GLint srcX, GLint srcY, GLsizei width, GLsizei height, GLint dstX, GLint dstY, GLenum type)
Try to do a fast 1:1 blit with memcpy.
void _swrast_DrawPixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Execute software-based glDrawPixels.
void _swrast_BlitFramebuffer (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Software fallback for glBlitFramebufferEXT().
void _swrast_Clear (struct gl_context *ctx, GLbitfield buffers)
Called via the device driver's ctx->Driver.Clear() function if the device driver can't clear one or more of the buffers itself.
void _swrast_ResetLineStipple (struct gl_context *ctx)
void _swrast_SetFacing (struct gl_context *ctx, GLuint facing)
Indicates front/back facing for subsequent points/lines when drawing unfilled polygons.
void _swrast_Point (struct gl_context *ctx, const SWvertex *v)
void _swrast_Line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
void _swrast_Triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_Quad (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2, const SWvertex *v3)
void _swrast_flush (struct gl_context *ctx)
void _swrast_render_primitive (struct gl_context *ctx, GLenum mode)
void _swrast_render_start (struct gl_context *ctx)
void _swrast_render_finish (struct gl_context *ctx)
struct gl_texture_image * _swrast_new_texture_image (struct gl_context *ctx)
Functions for mapping/unmapping texture images.
void _swrast_delete_texture_image (struct gl_context *ctx, struct gl_texture_image *texImage)
Free a swrast_texture_image (a subclass of gl_texture_image).
GLboolean _swrast_alloc_texture_image_buffer (struct gl_context *ctx, struct gl_texture_image *texImage)
Called via ctx->Driver.AllocTextureImageBuffer()
GLboolean _swrast_init_texture_image (struct gl_texture_image *texImage)
Code that overrides ctx->Driver.AllocTextureImageBuffer may use this to initialize the fields of swrast_texture_image without allocating the image buffer or initializing RowStride or the contents of ImageSlices.
void _swrast_free_texture_image_buffer (struct gl_context *ctx, struct gl_texture_image *texImage)
Called via ctx->Driver.FreeTextureImageBuffer()
void _swrast_map_teximage (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a 2D slice of a texture image into user space.
void _swrast_unmap_teximage (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice)
void _swrast_InvalidateState (struct gl_context *ctx, GLbitfield new_state)
void _swrast_allow_vertex_fog (struct gl_context *ctx, GLboolean value)
void _swrast_allow_pixel_fog (struct gl_context *ctx, GLboolean value)
void _swrast_print_vertex (struct gl_context *ctx, const SWvertex *v)
void _swrast_eject_texture_images (struct gl_context *ctx)
void _swrast_render_texture (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Called when rendering to a texture image begins, or when changing the dest mipmap level, cube face, etc.
void _swrast_finish_render_texture (struct gl_context *ctx, struct gl_renderbuffer *rb)
Detailed Description
Public interface to the software rasterization functions.
Author
Keith Whitwell keith.nosp@m.w@vm.nosp@m.ware..nosp@m.com
Macro Definition Documentation
DEFAULT_SOFTWARE_DEPTH_BITS
#define DEFAULT_SOFTWARE_DEPTH_BITS 16
Bits per depth buffer value (max is 32).
DEFAULT_SOFTWARE_DEPTH_TYPE
#define DEFAULT_SOFTWARE_DEPTH_TYPE GLushort
Depth buffer data type.
SWRAST_MAX_HEIGHT
#define SWRAST_MAX_HEIGHT 16384
SWRAST_MAX_WIDTH
#define SWRAST_MAX_WIDTH 16384
Max image/surface/texture size.
Referenced by _swrast_Bitmap(), _swrast_blend_span(), _swrast_CreateContext(), _swrast_logicop_rgba_span(), _swrast_mask_rgba_span(), _swrast_texture_span(), _swrast_write_rgba_span(), _swrast_write_zoomed_stencil_span(), _swrast_write_zoomed_z_span(), copy_rgba_pixels(), draw_depth_pixels(), draw_rgba_pixels(), draw_wide_line(), get_texel_array(), if(), large_point(), pixel_point(), plot(), and zoom_span().
TRIANGLE_WALK_DOUBLE
#define TRIANGLE_WALK_DOUBLE 0
If non-zero use GLdouble for walking triangle edges, for better accuracy.
VARYING_SLOT_CI
#define VARYING_SLOT_CI VARYING_SLOT_COL0
Referenced by _swrast_print_vertex().
Function Documentation
_swrast_alloc_texture_image_buffer()
GLboolean _swrast_alloc_texture_image_buffer (struct gl_context * ctx, struct gl_texture_image * texImage)
Called via ctx->Driver.AllocTextureImageBuffer()
References _mesa_align_malloc(), _mesa_format_image_size(), _mesa_format_row_stride(), _swrast_init_texture_image(), _swrast_teximage_slice_height(), swrast_texture_image::Buffer, GLuint, swrast_texture_image::ImageSlices, swrast_texture_image::RowStride, swrast_texture_image(), gl_texture_image::TexFormat, texture_slices(), and gl_texture_image::Width.
_swrast_allow_pixel_fog()
void _swrast_allow_pixel_fog (struct gl_context * ctx, GLboolean value)
References _mesa_debug(), _NEW_HINT, SWcontext::AllowPixelFog, SWcontext::InvalidateState, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_allow_vertex_fog()
void _swrast_allow_vertex_fog (struct gl_context * ctx, GLboolean value)
References _mesa_debug(), _NEW_HINT, SWcontext::AllowVertexFog, SWcontext::InvalidateState, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_Bitmap()
void _swrast_Bitmap (struct gl_context * ctx, GLint px, GLint py, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * bitmap)
Render a bitmap.
Called via ctx->Driver.Bitmap() All parameter error checking will have been done before this is called.
References _mesa_check_conditional_render(), _mesa_image_address2d(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _swrast_Bitmap(), _swrast_span_default_attribs(), _swrast_validate_derived(), _swrast_write_rgba_span(), sw_span::array, sw_span::arrayMask, sw_span::end, GLuint, INIT_SPAN(), gl_pixelstore_attrib::LsbFirst, sw_span_arrays::mask, gl_context::NewState, gl_context::RenderMode, gl_pixelstore_attrib::SkipPixels, span, SPAN_MASK, SPAN_XY, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, swrast_render_finish(), swrast_render_start(), sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_Bitmap().
_swrast_BlitFramebuffer()
void _swrast_BlitFramebuffer (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Software fallback for glBlitFramebufferEXT().
References _mesa_check_conditional_render(), _mesa_clip_blit(), _swrast_validate_derived(), blit_linear(), blit_nearest(), SWRAST_CONTEXT(), and swrast_fast_copy_pixels().
_swrast_Clear()
void _swrast_Clear (struct gl_context * ctx, GLbitfield buffers)
Called via the device driver's ctx->Driver.Clear() function if the device driver can't clear one or more of the buffers itself.
Parameters
buffers bitfield of BUFFER_BIT_* values indicating which renderbuffers are to be cleared.
all if GL_TRUE, clear whole buffer, else clear specified region.
References _mesa_check_conditional_render(), _mesa_clear_accum_buffer(), gl_framebuffer::_NumColorDrawBuffers, _swrast_clear_depth_buffer(), _swrast_clear_depth_stencil_buffer(), _swrast_clear_stencil_buffer(), _swrast_validate_derived(), gl_framebuffer::Attachment, BUFFER_BIT_ACCUM, BUFFER_BIT_AUX0, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_DEPTH, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_BIT_STENCIL, BUFFER_BITS_COLOR, BUFFER_DEPTH, BUFFER_STENCIL, clear_color_buffers(), gl_context::DrawBuffer, gl_renderbuffer_attachment::Renderbuffer, and SWRAST_CONTEXT().
_swrast_CopyPixels()
void _swrast_CopyPixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLint destx, GLint desty, GLsizei width, GLsizei height, GLenum type)
_swrast_CreateContext()
GLboolean _swrast_CreateContext (struct gl_context * ctx)
References _mesa_debug(), _swrast_choose_line(), _swrast_choose_point(), _swrast_choose_triangle(), _swrast_DestroyContext(), _SWRAST_NEW_LINE, _SWRAST_NEW_POINT, _SWRAST_NEW_TRIANGLE, _swrast_sleep(), _swrast_span_render_finish(), _swrast_span_render_start(), _swrast_validate_blend_func(), _swrast_validate_line(), _swrast_validate_point(), _swrast_validate_triangle(), SWcontext::AllowPixelFog, SWcontext::AllowVertexFog, sw_span::array, sw_span_arrays::attribs, SWcontext::BlendFunc, SWcontext::buf1, SWcontext::buf2, SWcontext::buf3, SWcontext::buf4, CHAN_TYPE, sw_span_arrays::ChanType, SWcontext::choose_line, SWcontext::choose_point, SWcontext::choose_triangle, gl_context::Const, SWcontext::Driver, sw_span::end, sw_span::facing, GLuint, init_program_native_limits(), SWcontext::InvalidateLineMask, SWcontext::InvalidatePointMask, SWcontext::InvalidateState, SWcontext::InvalidateTriangleMask, SWcontext::Line, gl_constants::Max3DTextureLevels, gl_constants::MaxCubeTextureLevels, gl_constants::MaxRenderbufferSize, gl_constants::MaxTextureLevels, gl_constants::MaxViewportHeight, gl_constants::MaxViewportWidth, SWcontext::NewState, SWcontext::Point, SWcontext::PointSpan, sw_span::primitive, gl_constants::Program, sw_span_arrays::rgba, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SWcontext::SpanArrays, swrast_device_driver::SpanRenderFinish, swrast_device_driver::SpanRenderStart, SWcontext::stencil_temp, swrast, gl_context::swrast_context, SWRAST_DEBUG, SWRAST_MAX_WIDTH, SWcontext::TextureSample, and SWcontext::Triangle.
_swrast_delete_texture_image()
void _swrast_delete_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free a swrast_texture_image (a subclass of gl_texture_image).
Called via ctx->Driver.DeleteTextureImage().
References _mesa_delete_texture_image().
_swrast_DestroyContext()
void _swrast_DestroyContext (struct gl_context * ctx)
References _mesa_debug(), SWcontext::buf1, SWcontext::buf2, SWcontext::buf3, SWcontext::buf4, SWcontext::SpanArrays, SWcontext::stencil_temp, swrast, gl_context::swrast_context, SWRAST_CONTEXT(), SWRAST_DEBUG, SWcontext::TexelBuffer, and SWcontext::ZoomedArrays.
Referenced by _swrast_CreateContext().
_swrast_DrawPixels()
void _swrast_DrawPixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels)
Execute software-based glDrawPixels.
By time we get here, all error checking will have been done.
References _mesa_check_conditional_render(), _mesa_map_pbo_source(), _mesa_set_vp_override(), _mesa_unmap_pbo_source(), _mesa_update_state(), gl_vertex_program_state::_Overriden, _swrast_validate_derived(), draw_depth_pixels(), draw_depth_stencil_pixels(), draw_rgba_pixels(), draw_stencil_pixels(), gl_context::NewState, SWcontext::NewState, swrast, SWRAST_CONTEXT(), swrast_render_finish(), swrast_render_start(), and gl_context::VertexProgram.
_swrast_eject_texture_images()
void _swrast_eject_texture_images (struct gl_context * ctx)
_swrast_finish_render_texture()
void _swrast_finish_render_texture (struct gl_context * ctx, struct gl_renderbuffer * rb)
References void.
_swrast_flush()
void _swrast_flush (struct gl_context * ctx)
References _swrast_write_rgba_span(), sw_span::end, SWcontext::PointSpan, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_render_finish(), and _swrast_render_primitive().
_swrast_free_texture_image_buffer()
void _swrast_free_texture_image_buffer (struct gl_context * ctx, struct gl_texture_image * texImage)
Called via ctx->Driver.FreeTextureImageBuffer()
References _mesa_align_free(), swrast_texture_image::Buffer, swrast_texture_image::ImageSlices, and swrast_texture_image().
_swrast_GetDeviceDriverReference()
struct swrast_device_driver* _swrast_GetDeviceDriverReference (struct gl_context * ctx)
References SWcontext::Driver, swrast, and SWRAST_CONTEXT().
_swrast_init_texture_image()
GLboolean _swrast_init_texture_image (struct gl_texture_image * texImage)
Code that overrides ctx->Driver.AllocTextureImageBuffer may use this to initialize the fields of swrast_texture_image without allocating the image buffer or initializing RowStride or the contents of ImageSlices.
Returns GL_TRUE on success, GL_FALSE on memory allocation failure.
References swrast_texture_image::_IsPowerOfTwo, gl_texture_image::Depth, gl_texture_image::Depth2, swrast_texture_image::DepthScale, gl_texture_image::Height, gl_texture_image::Height2, swrast_texture_image::HeightScale, swrast_texture_image::ImageSlices, swrast_texture_image(), gl_texture_object::Target, gl_texture_image::TexObject, texture_slices(), gl_texture_image::Width, gl_texture_image::Width2, and swrast_texture_image::WidthScale.
Referenced by _swrast_alloc_texture_image_buffer().
_swrast_InvalidateState()
void _swrast_InvalidateState (struct gl_context * ctx, GLbitfield new_state)
References _mesa_debug(), SWcontext::InvalidateState, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_Line()
void _swrast_Line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1)
References _mesa_debug(), _swrast_print_vertex(), SWcontext::Line, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_map_teximage()
void _swrast_map_teximage (struct gl_context * ctx, struct gl_texture_image * texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte ** mapOut, GLint * rowStrideOut)
Map a 2D slice of a texture image into user space.
(x,y,w,h) defines a region of interest (ROI). Reading/writing texels outside of the ROI is undefined.
Parameters
texImage the texture image
slice the 3D image slice or array texture slice
x,y,w,h region of interest
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT
mapOut returns start of mapping of region of interest
rowStrideOut returns row stride (in bytes)
References _mesa_format_row_stride(), _mesa_get_format_block_size(), _mesa_get_format_bytes(), swrast_texture_image::Buffer, check_map_teximage(), GLuint, swrast_texture_image::ImageSlices, swrast_texture_image(), gl_texture_image::TexFormat, and gl_texture_image::Width.
_swrast_new_texture_image()
struct gl_texture_image* _swrast_new_texture_image (struct gl_context * ctx)
Functions for mapping/unmapping texture images.
Allocate a new swrast_texture_image (a subclass of gl_texture_image). Called via ctx->Driver.NewTextureImage().
References CALLOC_STRUCT, and void.
_swrast_Point()
void _swrast_Point (struct gl_context * ctx, const SWvertex * v)
References _mesa_debug(), _swrast_print_vertex(), SWcontext::Point, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_print_vertex()
void _swrast_print_vertex (struct gl_context * ctx, const SWvertex * v)
References gl_texture_unit::_Current, _mesa_debug(), SWvertex::attrib, SWvertex::color, gl_context::Const, GLuint, gl_constants::MaxTextureCoordUnits, SWvertex::pointSize, SWRAST_DEBUG_VERTICES, gl_context::Texture, gl_texture_attrib::Unit, and VARYING_SLOT_CI.
Referenced by _swrast_Line(), _swrast_Point(), _swrast_Quad(), and _swrast_Triangle().
_swrast_Quad()
void _swrast_Quad (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2, const SWvertex * v3)
References _mesa_debug(), _swrast_print_vertex(), SWRAST_CONTEXT(), SWRAST_DEBUG, and SWcontext::Triangle.
_swrast_render_finish()
void _swrast_render_finish (struct gl_context * ctx)
References _swrast_flush(), gl_query_state::CurrentOcclusionObject, SWcontext::Driver, gl_context::Query, gl_query_object::Result, swrast_device_driver::SpanRenderFinish, swrast, SWRAST_CONTEXT(), and gl_query_object::Target.
_swrast_render_primitive()
void _swrast_render_primitive (struct gl_context * ctx, GLenum mode)
References _swrast_flush(), SWcontext::Primitive, swrast, and SWRAST_CONTEXT().
_swrast_render_start()
void _swrast_render_start (struct gl_context * ctx)
References SWcontext::Driver, sw_span::end, SWcontext::PointSpan, swrast_device_driver::SpanRenderStart, swrast, and SWRAST_CONTEXT().
_swrast_render_texture()
void _swrast_render_texture (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att)
Called when rendering to a texture image begins, or when changing the dest mipmap level, cube face, etc.
This is a fallback routine for software render-to-texture.
Called via the glRenderbufferTexture1D/2D/3D() functions and elsewhere (such as glTexImage2D).
The image we're rendering into is att->Texture->Image[att->CubeMapFace][att->TextureLevel]; It'll never be NULL.
Parameters
fb the framebuffer object the texture is being bound to
att the fb attachment point of the texture
See also
_mesa_FramebufferRenderbuffer_sw
References gl_renderbuffer::Delete, delete_texture_wrapper(), gl_renderbuffer_attachment::Renderbuffer, update_wrapper(), and void.
_swrast_ResetLineStipple()
void _swrast_ResetLineStipple (struct gl_context * ctx)
References _mesa_debug(), SWcontext::StippleCounter, SWRAST_CONTEXT(), and SWRAST_DEBUG.
_swrast_SetFacing()
void _swrast_SetFacing (struct gl_context * ctx, GLuint facing)
Indicates front/back facing for subsequent points/lines when drawing unfilled polygons.
Needed for two-side stencil.
References facing, SWcontext::PointLineFacing, and SWRAST_CONTEXT().
_swrast_Triangle()
void _swrast_Triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References _mesa_debug(), _swrast_print_vertex(), SWRAST_CONTEXT(), SWRAST_DEBUG, and SWcontext::Triangle.
_swrast_unmap_teximage()
void _swrast_unmap_teximage (struct gl_context * ctx, struct gl_texture_image * texImage, GLuint slice)
swrast_fast_copy_pixels()
GLboolean swrast_fast_copy_pixels (struct gl_context * ctx, struct gl_framebuffer * srcFb, struct gl_framebuffer * dstFb, GLint srcX, GLint srcY, GLsizei width, GLsizei height, GLint dstX, GLint dstY, GLenum type)
Try to do a fast 1:1 blit with memcpy.
Returns
GL_TRUE if successful, GL_FALSE otherwise.
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_format_bytes(), _mesa_is_format_packed_depth_stencil(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Xmax, gl_framebuffer::_Ymax, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLuint, gl_renderbuffer::Height, gl_framebuffer::Height, dd_function_table::MapRenderbuffer, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::UnmapRenderbuffer, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _swrast_BlitFramebuffer(), and _swrast_CopyPixels().