Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ss_triangle.c File Reference
#include "c99_math.h"
#include "main/glheader.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "tnl/t_context.h"
#include "ss_triangle.h"
#include "ss_context.h"
#include "ss_tritmp.h"
Macros
#define SS_OFFSET_BIT 0x1
#define SS_TWOSIDE_BIT 0x2
#define SS_UNFILLED_BIT 0x4
#define SS_MAX_TRIFUNC 0x8
#define SS_COLOR(a, b) UNCLAMPED_FLOAT_TO_RGBA_CHAN(a,b)
#define SS_SPEC(a, b) COPY_4V(a,b)
#define SS_IND(a, b) (a = b)
#define IND (0)
#define TAG(x) x##_rgba
#define IND (SS_OFFSET_BIT)
#define TAG(x) x##_offset_rgba
#define IND (SS_TWOSIDE_BIT)
#define TAG(x) x##_twoside_rgba
#define IND (SS_OFFSET_BIT|SS_TWOSIDE_BIT)
#define TAG(x) x##_offset_twoside_rgba
#define IND (SS_UNFILLED_BIT)
#define TAG(x) x##_unfilled_rgba
#define IND (SS_OFFSET_BIT|SS_UNFILLED_BIT)
#define TAG(x) x##_offset_unfilled_rgba
#define IND (SS_TWOSIDE_BIT|SS_UNFILLED_BIT)
#define TAG(x) x##_twoside_unfilled_rgba
#define IND (SS_OFFSET_BIT|SS_TWOSIDE_BIT|SS_UNFILLED_BIT)
#define TAG(x) x##_offset_twoside_unfilled_rgba
Typedefs
typedef void(* swsetup_edge_render_prim_tri) (struct gl_context *ctx, const GLubyte *ef, GLuint e0, GLuint e1, GLuint e2, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Functions
static void _swsetup_edge_render_line_tri (struct gl_context *ctx, const GLubyte *ef, GLuint e0, GLuint e1, GLuint e2, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
static void _swsetup_edge_render_point_tri (struct gl_context *ctx, const GLubyte *ef, GLuint e0, GLuint e1, GLuint e2, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
static void _swsetup_render_tri (struct gl_context *ctx, GLuint e0, GLuint e1, GLuint e2, GLuint facing, swsetup_edge_render_prim_tri render)
void _swsetup_trifuncs_init (struct gl_context *ctx)
static void swsetup_points (struct gl_context *ctx, GLuint first, GLuint last)
static void swsetup_line (struct gl_context *ctx, GLuint v0, GLuint v1)
void _swsetup_choose_trifuncs (struct gl_context *ctx)
Variables
static tnl_triangle_func tri_tab [SS_MAX_TRIFUNC]
static tnl_quad_func quad_tab [SS_MAX_TRIFUNC]
Macro Definition Documentation
IND [1/8]
#define IND (0)
Referenced by init(), quadfunc(), and triangle().
IND [2/8]
#define IND (SS_OFFSET_BIT)
IND [3/8]
#define IND (SS_TWOSIDE_BIT)
IND [4/8]
#define IND (SS_OFFSET_BIT|SS_TWOSIDE_BIT)
IND [5/8]
#define IND (SS_UNFILLED_BIT)
IND [6/8]
#define IND (SS_OFFSET_BIT|SS_UNFILLED_BIT)
IND [7/8]
#define IND (SS_TWOSIDE_BIT|SS_UNFILLED_BIT)
IND [8/8]
#define IND (SS_OFFSET_BIT|SS_TWOSIDE_BIT|SS_UNFILLED_BIT)
SS_COLOR
#define SS_COLOR (a, b) UNCLAMPED_FLOAT_TO_RGBA_CHAN(a,b)
Referenced by triangle().
SS_IND
#define SS_IND (a, b) (a = b)
SS_MAX_TRIFUNC
#define SS_MAX_TRIFUNC 0x8
SS_OFFSET_BIT
#define SS_OFFSET_BIT 0x1
Referenced by _swsetup_choose_trifuncs(), and triangle().
SS_SPEC
#define SS_SPEC (a, b) COPY_4V(a,b)
Referenced by triangle().
SS_TWOSIDE_BIT
#define SS_TWOSIDE_BIT 0x2
Referenced by _swsetup_choose_trifuncs(), and triangle().
SS_UNFILLED_BIT
#define SS_UNFILLED_BIT 0x4
Referenced by _swsetup_choose_trifuncs(), quadfunc(), and triangle().
TAG [1/8]
#define TAG (x) x##_rgba
Referenced by init(), and quadfunc().
TAG [2/8]
#define TAG (x) x##_offset_rgba
TAG [3/8]
#define TAG (x) x##_twoside_rgba
TAG [4/8]
#define TAG (x) x##_offset_twoside_rgba
TAG [5/8]
#define TAG (x) x##_unfilled_rgba
TAG [6/8]
#define TAG (x) x##_offset_unfilled_rgba
TAG [7/8]
#define TAG (x) x##_twoside_unfilled_rgba
TAG [8/8]
#define TAG (x) x##_offset_twoside_unfilled_rgba
Typedef Documentation
swsetup_edge_render_prim_tri
typedef void(* swsetup_edge_render_prim_tri) (struct gl_context *ctx, const GLubyte *ef, GLuint e0, GLuint e1, GLuint e2, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
Function Documentation
_swsetup_choose_trifuncs()
void _swsetup_choose_trifuncs (struct gl_context * ctx)
References gl_vertex_program_state::_Current, gl_stencil_attrib::_TestTwoSide, gl_polygon_attrib::BackMode, TNLcontext::Driver, gl_stencil_attrib::Enabled, gl_light_attrib::Enabled, gl_polygon_attrib::FrontMode, GLuint, gl_context::Light, tnl_device_driver::Line, gl_light_attrib::Model, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, tnl_device_driver::Points, gl_context::Polygon, tnl_device_driver::Quad, quad_tab, tnl_device_driver::Render, SS_OFFSET_BIT, SS_TWOSIDE_BIT, SS_UNFILLED_BIT, gl_context::Stencil, swsetup_line(), swsetup_points(), TNL_CONTEXT, tri_tab, tnl_device_driver::Triangle, gl_lightmodel::TwoSide, gl_vertex_program_state::TwoSideEnabled, and gl_context::VertexProgram.
Referenced by _swsetup_RenderStart().
_swsetup_edge_render_line_tri()
static void _swsetup_edge_render_line_tri (struct gl_context * ctx, const GLubyte * ef, GLuint e0, GLuint e1, GLuint e2, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
References _swrast_Line(), SScontext::render_prim, and SWSETUP_CONTEXT.
Referenced by triangle().
_swsetup_edge_render_point_tri()
static void _swsetup_edge_render_point_tri (struct gl_context * ctx, const GLubyte * ef, GLuint e0, GLuint e1, GLuint e2, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2) static
References _swrast_flush(), and _swrast_Point().
Referenced by triangle().
_swsetup_render_tri()
static void _swsetup_render_tri (struct gl_context * ctx, GLuint e0, GLuint e1, GLuint e2, GLuint facing, swsetup_edge_render_prim_tri render) static
References _swrast_SetFacing(), SWvertex::attrib, SWvertex::color, COPY_4V, COPY_CHAN4, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, vertex_buffer::EdgeFlag, gl_context::Light, gl_context::Polygon, gl_light_attrib::ShadeModel, SWSETUP_CONTEXT, TNL_CONTEXT, and SScontext::verts.
Referenced by triangle().
_swsetup_trifuncs_init()
void _swsetup_trifuncs_init (struct gl_context * ctx)
References void.
Referenced by _swsetup_CreateContext().
swsetup_line()
static void swsetup_line (struct gl_context * ctx, GLuint v0, GLuint v1) static
References _swrast_Line(), and SWSETUP_CONTEXT.
Referenced by _swsetup_choose_trifuncs().
swsetup_points()
static void swsetup_points (struct gl_context * ctx, GLuint first, GLuint last) static
References _swrast_Point(), vertex_buffer::ClipMask, vertex_buffer::Elts, GLuint, SWSETUP_CONTEXT, and TNL_CONTEXT.
Referenced by _swsetup_choose_trifuncs().
Variable Documentation
quad_tab
tnl_quad_func quad_tab[SS_MAX_TRIFUNC] static
Referenced by _swsetup_choose_trifuncs(), and init().
tri_tab
tnl_triangle_func tri_tab[SS_MAX_TRIFUNC] static
Referenced by _swsetup_choose_trifuncs(), and init().