Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ss_context.c File Reference
#include "main/glheader.h"
#include "main/imports.h"
#include "main/macros.h"
#include "tnl/tnl.h"
#include "tnl/t_context.h"
#include "tnl/t_pipeline.h"
#include "tnl/t_vertex.h"
#include "swrast_setup.h"
#include "ss_context.h"
#include "ss_triangle.h"
Macros
#define _SWSETUP_NEW_RENDERINDEX (_NEW_POLYGON|_NEW_LIGHT|_NEW_PROGRAM)
#define VARYING_EMIT_STYLE EMIT_4F
#define SWZ ((SWvertex *)0)
Helper macros for setup_vertex_format()
#define SWOffset(MEMBER) (((char *)&(SWZ->MEMBER)) - ((char *)SWZ))
#define EMIT_ATTR(ATTR, STYLE, MEMBER)
Functions
GLboolean _swsetup_CreateContext (struct gl_context *ctx)
void _swsetup_DestroyContext (struct gl_context *ctx)
static void _swsetup_RenderPrimitive (struct gl_context *ctx, GLenum mode)
static void setup_vertex_format (struct gl_context *ctx)
Tell the tnl module how to build SWvertex objects for swrast.
static void _swsetup_RenderStart (struct gl_context *ctx)
Prepare to render a vertex buffer.
static void _swsetup_RenderFinish (struct gl_context *ctx)
void _swsetup_InvalidateState (struct gl_context *ctx, GLuint new_state)
void _swsetup_Wakeup (struct gl_context *ctx)
void _swsetup_Translate (struct gl_context *ctx, const void *vertex, SWvertex *dest)
Populate a swrast SWvertex from an attrib-style vertex.
Macro Definition Documentation
_SWSETUP_NEW_RENDERINDEX
#define _SWSETUP_NEW_RENDERINDEX (_NEW_POLYGON|_NEW_LIGHT|_NEW_PROGRAM)
Referenced by _swsetup_RenderStart().
EMIT_ATTR
#define EMIT_ATTR (ATTR, STYLE, MEMBER)
Value:
do {                                            \
   map[e].attrib = (ATTR);                      \
   map[e].format = (STYLE);                     \
   map[e].offset = SWOffset(MEMBER);            \
   e++;                                         \
} while (0)
Referenced by setup_vertex_format().
SWOffset
#define SWOffset (MEMBER) (((char *)&(SWZ->MEMBER)) - ((char *)SWZ))
SWZ
#define SWZ ((SWvertex *)0)
Helper macros for setup_vertex_format()
VARYING_EMIT_STYLE
#define VARYING_EMIT_STYLE EMIT_4F
Referenced by setup_vertex_format().
Function Documentation
_swsetup_CreateContext()
GLboolean _swsetup_CreateContext (struct gl_context * ctx)
References _swsetup_trifuncs_init(), _tnl_init_vertices(), gl_context::Const, gl_constants::MaxArrayLockSize, SScontext::NewState, and gl_context::swsetup_context.
_swsetup_DestroyContext()
void _swsetup_DestroyContext (struct gl_context * ctx)
References _tnl_free_vertices(), gl_context::swsetup_context, and SWSETUP_CONTEXT.
_swsetup_InvalidateState()
void _swsetup_InvalidateState (struct gl_context * ctx, GLuint new_state)
References _tnl_invalidate_vertex_state(), SScontext::NewState, and SWSETUP_CONTEXT.
Referenced by _swsetup_Wakeup().
_swsetup_RenderFinish()
static void _swsetup_RenderFinish (struct gl_context * ctx) static
References _swrast_render_finish().
Referenced by _swsetup_Wakeup().
_swsetup_RenderPrimitive()
static void _swsetup_RenderPrimitive (struct gl_context * ctx, GLenum mode) static
References _swrast_render_primitive(), and SWSETUP_CONTEXT.
Referenced by _swsetup_Wakeup().
_swsetup_RenderStart()
static void _swsetup_RenderStart (struct gl_context * ctx) static
Prepare to render a vertex buffer.
Called via tnl->Driver.Render.Start.
References _NEW_PROGRAM, _swrast_render_start(), _swrast_SetFacing(), _swsetup_choose_trifuncs(), _SWSETUP_NEW_RENDERINDEX, vertex_buffer::AttribPtr, SScontext::last_index_bitset, vertex_buffer::NdcPtr, SScontext::NewState, setup_vertex_format(), SWSETUP_CONTEXT, TNL_CONTEXT, and TNLcontext::vb.
Referenced by _swsetup_Wakeup().
_swsetup_Translate()
void _swsetup_Translate (struct gl_context * ctx, const void * vertex, SWvertex * dest)
Populate a swrast SWvertex from an attrib-style vertex.
XXX try to limit these loops someday
References _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_COLOR1, _TNL_ATTRIB_FOG, _TNL_ATTRIB_GENERIC0, _TNL_ATTRIB_POINTSIZE, _TNL_ATTRIB_POS, _TNL_ATTRIB_TEX0, _tnl_get_attr(), TNLcontext::_WindowMap, SWvertex::attrib, SWvertex::color, gl_context::Const, GLuint, GLmatrix::m, gl_constants::MaxTextureCoordUnits, gl_constants::MaxVarying, SWvertex::pointSize, TNL_CONTEXT, and UNCLAMPED_FLOAT_TO_RGBA_CHAN.
_swsetup_Wakeup()
void _swsetup_Wakeup (struct gl_context * ctx)
References _swrast_ResetLineStipple(), _swsetup_InvalidateState(), _swsetup_RenderFinish(), _swsetup_RenderPrimitive(), _swsetup_RenderStart(), _tnl_build_vertices(), _tnl_copy_pv(), _tnl_interp(), _tnl_invalidate_vertices(), _tnl_need_projected_coords(), _tnl_render_tab_elts, _tnl_render_tab_verts, _tnl_RenderClippedLine(), _tnl_RenderClippedPolygon(), tnl_device_driver::BuildVertices, tnl_device_driver::ClippedLine, tnl_device_driver::ClippedPolygon, TNLcontext::clipspace, tnl_device_driver::CopyPV, TNLcontext::Driver, tnl_device_driver::Finish, tnl_device_driver::Interp, SScontext::last_index_bitset, tnl_device_driver::Multipass, tnl_device_driver::PrimitiveNotify, tnl_device_driver::PrimTabElts, tnl_device_driver::PrimTabVerts, tnl_device_driver::Render, tnl_device_driver::ResetLineStipple, tnl_device_driver::Start, SWSETUP_CONTEXT, TNL_CONTEXT, tnl_clipspace::vertex_buf, and SScontext::verts.
setup_vertex_format()
static void setup_vertex_format (struct gl_context * ctx) static
Tell the tnl module how to build SWvertex objects for swrast.
We'll build the map[] array with that info and pass it to _tnl_install_attrs().
References gl_fragment_program_state::_Current, gl_ati_fragment_shader_state::_Enabled, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_COLOR1, _TNL_ATTRIB_FOG, _TNL_ATTRIB_GENERIC, _TNL_ATTRIB_GENERIC0, _TNL_ATTRIB_POINTSIZE, _TNL_ATTRIB_POS, _TNL_ATTRIB_TEX, _TNL_ATTRIB_TEX0, _tnl_install_attrs(), _TNL_NUM_GENERIC, _TNL_NUM_TEX, TNLcontext::_WindowMap, gl_context::ATIFragmentShader, tnl_attr_map::attrib, BITFIELD64_BIT, BITFIELD64_RANGE, CHAN_TYPE, gl_context::Const, EMIT_1F, EMIT_4CHAN_4F_RGBA, EMIT_4F, EMIT_4F_VIEWPORT, EMIT_ATTR, gl_context::FragmentProgram, SScontext::intColors, SScontext::last_index_bitset, GLmatrix::m, MAX_TEXTURE_COORD_UNITS, gl_constants::MaxVarying, TNLcontext::render_inputs_bitset, gl_context::RenderMode, SWSETUP_CONTEXT, TNL_CONTEXT, and VARYING_EMIT_STYLE.
Referenced by _swsetup_RenderStart().