Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ss_triangle.h File Reference
Functions
void _swsetup_trifuncs_init (struct gl_context *ctx)
void _swsetup_choose_trifuncs (struct gl_context *ctx)
Function Documentation
_swsetup_choose_trifuncs()
void _swsetup_choose_trifuncs (struct gl_context * ctx)
References gl_vertex_program_state::_Current, gl_stencil_attrib::_TestTwoSide, gl_polygon_attrib::BackMode, TNLcontext::Driver, gl_stencil_attrib::Enabled, gl_light_attrib::Enabled, gl_polygon_attrib::FrontMode, GLuint, gl_context::Light, tnl_device_driver::Line, gl_light_attrib::Model, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, tnl_device_driver::Points, gl_context::Polygon, tnl_device_driver::Quad, quad_tab, tnl_device_driver::Render, SS_OFFSET_BIT, SS_TWOSIDE_BIT, SS_UNFILLED_BIT, gl_context::Stencil, swsetup_line(), swsetup_points(), TNL_CONTEXT, tri_tab, tnl_device_driver::Triangle, gl_lightmodel::TwoSide, gl_vertex_program_state::TwoSideEnabled, and gl_context::VertexProgram.
Referenced by _swsetup_RenderStart().
_swsetup_trifuncs_init()
void _swsetup_trifuncs_init (struct gl_context * ctx)
References void.
Referenced by _swsetup_CreateContext().