Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
swrast_setup.h File Reference
#include "swrast/swrast.h"
Functions
GLboolean _swsetup_CreateContext (struct gl_context *ctx)
void _swsetup_DestroyContext (struct gl_context *ctx)
void _swsetup_InvalidateState (struct gl_context *ctx, GLuint new_state)
void _swsetup_Wakeup (struct gl_context *ctx)
void _swsetup_Translate (struct gl_context *ctx, const void *vertex, SWvertex *dest)
Populate a swrast SWvertex from an attrib-style vertex.
Function Documentation
_swsetup_CreateContext()
GLboolean _swsetup_CreateContext (struct gl_context * ctx)
References _swsetup_trifuncs_init(), _tnl_init_vertices(), gl_context::Const, gl_constants::MaxArrayLockSize, SScontext::NewState, and gl_context::swsetup_context.
_swsetup_DestroyContext()
void _swsetup_DestroyContext (struct gl_context * ctx)
References _tnl_free_vertices(), gl_context::swsetup_context, and SWSETUP_CONTEXT.
_swsetup_InvalidateState()
void _swsetup_InvalidateState (struct gl_context * ctx, GLuint new_state)
References _tnl_invalidate_vertex_state(), SScontext::NewState, and SWSETUP_CONTEXT.
Referenced by _swsetup_Wakeup().
_swsetup_Translate()
void _swsetup_Translate (struct gl_context * ctx, const void * vertex, SWvertex * dest)
Populate a swrast SWvertex from an attrib-style vertex.
XXX try to limit these loops someday
References _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_COLOR1, _TNL_ATTRIB_FOG, _TNL_ATTRIB_GENERIC0, _TNL_ATTRIB_POINTSIZE, _TNL_ATTRIB_POS, _TNL_ATTRIB_TEX0, _tnl_get_attr(), TNLcontext::_WindowMap, SWvertex::attrib, SWvertex::color, gl_context::Const, GLuint, GLmatrix::m, gl_constants::MaxTextureCoordUnits, gl_constants::MaxVarying, SWvertex::pointSize, TNL_CONTEXT, and UNCLAMPED_FLOAT_TO_RGBA_CHAN.
_swsetup_Wakeup()
void _swsetup_Wakeup (struct gl_context * ctx)
References _swrast_ResetLineStipple(), _swsetup_InvalidateState(), _swsetup_RenderFinish(), _swsetup_RenderPrimitive(), _swsetup_RenderStart(), _tnl_build_vertices(), _tnl_copy_pv(), _tnl_interp(), _tnl_invalidate_vertices(), _tnl_need_projected_coords(), _tnl_render_tab_elts, _tnl_render_tab_verts, _tnl_RenderClippedLine(), _tnl_RenderClippedPolygon(), tnl_device_driver::BuildVertices, tnl_device_driver::ClippedLine, tnl_device_driver::ClippedPolygon, TNLcontext::clipspace, tnl_device_driver::CopyPV, TNLcontext::Driver, tnl_device_driver::Finish, tnl_device_driver::Interp, SScontext::last_index_bitset, tnl_device_driver::Multipass, tnl_device_driver::PrimitiveNotify, tnl_device_driver::PrimTabElts, tnl_device_driver::PrimTabVerts, tnl_device_driver::Render, tnl_device_driver::ResetLineStipple, tnl_device_driver::Start, SWSETUP_CONTEXT, TNL_CONTEXT, tnl_clipspace::vertex_buf, and SScontext::verts.