Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
backend.c File Reference
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "backend.h"
Data Structures
struct backend_desc
Macros
#define ARRAY_SIZE(a) (sizeof(a)/sizeof((a)[0]))
Functions
static const void * load_backend (const struct backend_desc *backend)
static const struct backend_desc * find_backend (const char *name)
struct gbm_device * _gbm_create_device (int fd)
Variables
const struct gbm_backend gbm_dri_backend
static const struct backend_desc backends []
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (a) (sizeof(a)/sizeof((a)[0]))
Referenced by _gbm_create_device(), and find_backend().
Function Documentation
_gbm_create_device()
struct gbm_device* _gbm_create_device (int fd)
References ARRAY_SIZE, gbm_backend::create_device, find_backend(), and load_backend().
Referenced by gbm_create_device().
find_backend()
static const struct backend_desc* find_backend (const char * name) static
References ARRAY_SIZE.
Referenced by _gbm_create_device().
load_backend()
static const void* load_backend (const struct backend_desc * backend) static
References backend_desc::builtin.
Referenced by _gbm_create_device().
Variable Documentation
backends
const struct backend_desc backends[] static
Initial value:
= {
   { "gbm_dri.so", &gbm_dri_backend },
}
gbm_dri_backend
const struct gbm_backend gbm_dri_backend