Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
backend.h File Reference
#include "gbmint.h"
Functions
struct gbm_device * _gbm_create_device (int fd)
Function Documentation
_gbm_create_device()
struct gbm_device* _gbm_create_device (int fd)
References ARRAY_SIZE, gbm_backend::create_device, find_backend(), and load_backend().
Referenced by gbm_create_device().