Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gbm.c File Reference
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <sys/stat.h>
#include <unistd.h>
#include <errno.h>
#include "gbm.h"
#include "gbmint.h"
#include "backend.h"
Functions
GBM_EXPORT int gbm_device_get_fd (struct gbm_device *gbm)
Returns the file description for the gbm device.
GBM_EXPORT const char * gbm_device_get_backend_name (struct gbm_device *gbm)
Get the backend name for the given gbm device.
GBM_EXPORT int gbm_device_is_format_supported (struct gbm_device *gbm, uint32_t format, uint32_t usage)
Test if a format is supported for a given set of usage flags.
GBM_EXPORT void gbm_device_destroy (struct gbm_device *gbm)
Destroy the gbm device and free all resources associated with it.
GBM_EXPORT struct gbm_device * gbm_create_device (int fd)
Create a gbm device for allocating buffers.
GBM_EXPORT uint32_t gbm_bo_get_width (struct gbm_bo *bo)
Get the width of the buffer object.
GBM_EXPORT uint32_t gbm_bo_get_height (struct gbm_bo *bo)
Get the height of the buffer object.
GBM_EXPORT uint32_t gbm_bo_get_stride (struct gbm_bo *bo)
Get the stride of the buffer object.
GBM_EXPORT uint32_t gbm_bo_get_stride_for_plane (struct gbm_bo *bo, int plane)
Get the stride for the given plane.
GBM_EXPORT uint32_t gbm_bo_get_format (struct gbm_bo *bo)
Get the format of the buffer object.
GBM_EXPORT uint32_t gbm_bo_get_offset (struct gbm_bo *bo, int plane)
Get the offset for the data of the specified plane.
GBM_EXPORT struct gbm_device * gbm_bo_get_device (struct gbm_bo *bo)
Get the gbm device used to create the buffer object.
GBM_EXPORT union gbm_bo_handle gbm_bo_get_handle (struct gbm_bo *bo)
Get the handle of the buffer object.
GBM_EXPORT int gbm_bo_get_fd (struct gbm_bo *bo)
Get a DMA-BUF file descriptor for the buffer object.
GBM_EXPORT int gbm_bo_get_plane_count (struct gbm_bo *bo)
Get the number of planes for the given bo.
GBM_EXPORT union gbm_bo_handle gbm_bo_get_handle_for_plane (struct gbm_bo *bo, int plane)
Get the handle for the specified plane of the buffer object.
GBM_EXPORT uint64_t gbm_bo_get_modifier (struct gbm_bo *bo)
Get the chosen modifier for the buffer object.
GBM_EXPORT int gbm_bo_write (struct gbm_bo *bo, const void *buf, size_t count)
Write data into the buffer object.
GBM_EXPORT void gbm_bo_set_user_data (struct gbm_bo *bo, void *data, void(*destroy_user_data)(struct gbm_bo *, void *))
Set the user data associated with a buffer object.
GBM_EXPORT void * gbm_bo_get_user_data (struct gbm_bo *bo)
Get the user data associated with a buffer object.
GBM_EXPORT void gbm_bo_destroy (struct gbm_bo *bo)
Destroys the given buffer object and frees all resources associated with it.
GBM_EXPORT struct gbm_bo * gbm_bo_create (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage)
Allocate a buffer object for the given dimensions.
GBM_EXPORT struct gbm_bo * gbm_bo_create_with_modifiers (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t *modifiers, const unsigned int count)
GBM_EXPORT struct gbm_bo * gbm_bo_import (struct gbm_device *gbm, uint32_t type, void *buffer, uint32_t usage)
Create a gbm buffer object from an foreign object.
GBM_EXPORT void * gbm_bo_map (struct gbm_bo *bo, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t flags, uint32_t *stride, void **map_data)
Map a region of a gbm buffer object for cpu access.
GBM_EXPORT void gbm_bo_unmap (struct gbm_bo *bo, void *map_data)
Unmap a previously mapped region of a gbm buffer object.
GBM_EXPORT struct gbm_surface * gbm_surface_create (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags)
Allocate a surface object.
GBM_EXPORT struct gbm_surface * gbm_surface_create_with_modifiers (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t *modifiers, const unsigned int count)
GBM_EXPORT void gbm_surface_destroy (struct gbm_surface *surf)
Destroys the given surface and frees all resources associated with it.
GBM_EXPORT struct gbm_bo * gbm_surface_lock_front_buffer (struct gbm_surface *surf)
Lock the surface's current front buffer.
GBM_EXPORT void gbm_surface_release_buffer (struct gbm_surface *surf, struct gbm_bo *bo)
Release a locked buffer obtained with gbm_surface_lock_front_buffer()
GBM_EXPORT int gbm_surface_has_free_buffers (struct gbm_surface *surf)
Return whether or not a surface has free (non-locked) buffers.
Function Documentation
gbm_bo_create()
GBM_EXPORT struct gbm_bo* gbm_bo_create (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage)
Allocate a buffer object for the given dimensions.
Parameters
gbm The gbm device returned from gbm_create_device()
width The width for the buffer
height The height for the buffer
format The format to use for the buffer
usage The union of the usage flags for this buffer
Returns
A newly allocated buffer that should be freed with gbm_bo_destroy() when no longer needed. If an error occurs during allocation NULL will be returned and errno set.
See also
enum gbm_bo_format for the list of formats
enum gbm_bo_flags for the list of usage flags
References gbm_device::bo_create, and GBM_EXPORT.
gbm_bo_create_with_modifiers()
GBM_EXPORT struct gbm_bo* gbm_bo_create_with_modifiers (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t * modifiers, const unsigned int count)
References gbm_device::bo_create, and GBM_EXPORT.
gbm_bo_destroy()
GBM_EXPORT void gbm_bo_destroy (struct gbm_bo * bo)
Destroys the given buffer object and frees all resources associated with it.
Parameters
bo The buffer object
References gbm_device::bo_destroy, gbm_bo::destroy_user_data, gbm_bo::gbm, GBM_EXPORT, and gbm_bo::user_data.
gbm_bo_get_device()
GBM_EXPORT struct gbm_device* gbm_bo_get_device (struct gbm_bo * bo)
Get the gbm device used to create the buffer object.
Parameters
bo The buffer object
Returns
Returns the gbm device with which the buffer object was created
References gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_fd()
GBM_EXPORT int gbm_bo_get_fd (struct gbm_bo * bo)
Get a DMA-BUF file descriptor for the buffer object.
This function creates a DMA-BUF (also known as PRIME) file descriptor handle for the buffer object. Each call to gbm_bo_get_fd() returns a new file descriptor and the caller is responsible for closing the file descriptor.
Parameters
bo The buffer object
Returns
Returns a file descriptor referring to the underlying buffer or -1 if an error occurs.
References gbm_device::bo_get_fd, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_format()
GBM_EXPORT uint32_t gbm_bo_get_format (struct gbm_bo * bo)
Get the format of the buffer object.
The format of the pixels in the buffer.
Parameters
bo The buffer object
Returns
The format of buffer object, on of the GBM_FORMAT_* codes
References gbm_bo::format, and GBM_EXPORT.
gbm_bo_get_handle()
GBM_EXPORT union gbm_bo_handle gbm_bo_get_handle (struct gbm_bo * bo)
Get the handle of the buffer object.
This is stored in the platform generic union gbm_bo_handle type. However the format of this handle is platform specific.
Parameters
bo The buffer object
Returns
Returns the handle of the allocated buffer object
References GBM_EXPORT.
gbm_bo_get_handle_for_plane()
GBM_EXPORT union gbm_bo_handle gbm_bo_get_handle_for_plane (struct gbm_bo * bo, int plane)
Get the handle for the specified plane of the buffer object.
This function gets the handle for any plane associated with the BO. When dealing with multi-planar formats, or formats which might have implicit planes based on different underlying hardware it is necessary for the client to be able to get this information to pass to the DRM.
Parameters
bo The buffer object
plane the plane to get a handle for
See also
gbm_bo_get_handle()
References GBM_EXPORT.
gbm_bo_get_height()
GBM_EXPORT uint32_t gbm_bo_get_height (struct gbm_bo * bo)
Get the height of the buffer object.
Parameters
bo The buffer object
Returns
The height of the allocated buffer object
References GBM_EXPORT, and gbm_bo::height.
gbm_bo_get_modifier()
GBM_EXPORT uint64_t gbm_bo_get_modifier (struct gbm_bo * bo)
Get the chosen modifier for the buffer object.
This function returns the modifier that was chosen for the object. These properties may be generic, or platform/implementation dependent.
Parameters
bo The buffer object
Returns
Returns the selected modifier (chosen by the implementation) for the BO.
See also
gbm_bo_create_with_modifiers() where possible modifiers are set
gbm_surface_create_with_modifiers() where possible modifiers are set
define DRM_FORMAT_MOD_* in drm_fourcc.h for possible modifiers
References gbm_device::bo_get_modifier, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_offset()
GBM_EXPORT uint32_t gbm_bo_get_offset (struct gbm_bo * bo, int plane)
Get the offset for the data of the specified plane.
Extra planes, and even the first plane, may have an offset from the start of the buffer object. This function will provide the offset for the given plane to be used in various KMS APIs.
Parameters
bo The buffer object
Returns
The offset
References gbm_device::bo_get_offset, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_plane_count()
GBM_EXPORT int gbm_bo_get_plane_count (struct gbm_bo * bo)
Get the number of planes for the given bo.
Parameters
bo The buffer object
Returns
The number of planes
References gbm_device::bo_get_planes, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_stride()
GBM_EXPORT uint32_t gbm_bo_get_stride (struct gbm_bo * bo)
Get the stride of the buffer object.
This is calculated by the backend when it does the allocation in gbm_bo_create()
Parameters
bo The buffer object
Returns
The stride of the allocated buffer object in bytes
References gbm_bo_get_stride_for_plane(), and GBM_EXPORT.
gbm_bo_get_stride_for_plane()
GBM_EXPORT uint32_t gbm_bo_get_stride_for_plane (struct gbm_bo * bo, int plane)
Get the stride for the given plane.
Parameters
bo The buffer object
plane for which you want the stride
See also
gbm_bo_get_stride()
References gbm_device::bo_get_stride, gbm_bo::gbm, and GBM_EXPORT.
Referenced by gbm_bo_get_stride().
gbm_bo_get_user_data()
GBM_EXPORT void* gbm_bo_get_user_data (struct gbm_bo * bo)
Get the user data associated with a buffer object.
Parameters
bo The buffer object
Returns
Returns the user data associated with the buffer object or NULL if no data was associated with it
See also
gbm_bo_set_user_data()
References GBM_EXPORT, and gbm_bo::user_data.
gbm_bo_get_width()
GBM_EXPORT uint32_t gbm_bo_get_width (struct gbm_bo * bo)
Get the width of the buffer object.
Parameters
bo The buffer object
Returns
The width of the allocated buffer object
References GBM_EXPORT, and gbm_bo::width.
gbm_bo_import()
GBM_EXPORT struct gbm_bo* gbm_bo_import (struct gbm_device * gbm, uint32_t type, void * buffer, uint32_t usage)
Create a gbm buffer object from an foreign object.
This function imports a foreign object and creates a new gbm bo for it. This enabled using the foreign object with a display API such as KMS. Currently three types of foreign objects are supported, indicated by the type argument:
GBM_BO_IMPORT_WL_BUFFER GBM_BO_IMPORT_EGL_IMAGE GBM_BO_IMPORT_FD
The gbm bo shares the underlying pixels but its life-time is independent of the foreign object.
Parameters
gbm The gbm device returned from gbm_create_device()
gbm The type of object we're importing
gbm Pointer to the external object
usage The union of the usage flags for this buffer
Returns
A newly allocated buffer object that should be freed with gbm_bo_destroy() when no longer needed. On error, NULL is returned and errno is set.
See also
enum gbm_bo_flags for the list of usage flags
References gbm_device::bo_import, and GBM_EXPORT.
gbm_bo_map()
GBM_EXPORT void* gbm_bo_map (struct gbm_bo * bo, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t flags, uint32_t * stride, void ** map_data)
Map a region of a gbm buffer object for cpu access.
This function maps a region of a gbm bo for cpu read and/or write access.
Parameters
bo The buffer object
x The X (top left origin) starting position of the mapped region for the buffer
y The Y (top left origin) starting position of the mapped region for the buffer
width The width of the mapped region for the buffer
height The height of the mapped region for the buffer
flags The union of the GBM_BO_TRANSFER_* flags for this buffer
stride Ptr for returned stride in bytes of the mapped region
map_data Returned opaque ptr for the mapped region
Returns
Address of the mapped buffer that should be unmapped with gbm_bo_unmap() when no longer needed. On error, NULL is returned and errno is set.
See also
enum gbm_bo_transfer_flags for the list of flags
References gbm_device::bo_map, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_set_user_data()
GBM_EXPORT void gbm_bo_set_user_data (struct gbm_bo * bo, void * data, void(*)(struct gbm_bo *, void *) destroy_user_data)
Set the user data associated with a buffer object.
Parameters
bo The buffer object
data The data to associate to the buffer object
destroy_user_data A callback (which may be NULL) that will be called prior to the buffer destruction
References gbm_bo::destroy_user_data, GBM_EXPORT, and gbm_bo::user_data.
gbm_bo_unmap()
GBM_EXPORT void gbm_bo_unmap (struct gbm_bo * bo, void * map_data)
Unmap a previously mapped region of a gbm buffer object.
This function unmaps a region of a gbm bo for cpu read and/or write access.
Parameters
bo The buffer object
map_data opaque ptr returned from prior gbm_bo_map
References gbm_device::bo_unmap, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_write()
GBM_EXPORT int gbm_bo_write (struct gbm_bo * bo, const void * buf, size_t count)
Write data into the buffer object.
If the buffer object was created with the GBM_BO_USE_WRITE flag, this function can be used to write data into the buffer object. The data is copied directly into the object and it's the responsibility of the caller to make sure the data represents valid pixel data, according to the width, height, stride and format of the buffer object.
Parameters
bo The buffer object
buf The data to write
count The number of bytes to write
Returns
Returns 0 on success, otherwise -1 is returned an errno set
References gbm_device::bo_write, gbm_bo::gbm, and GBM_EXPORT.
gbm_create_device()
GBM_EXPORT struct gbm_device* gbm_create_device (int fd)
Create a gbm device for allocating buffers.
The file descriptor passed in is used by the backend to communicate with platform for allocating the memory. For allocations using DRI this would be the file descriptor returned when opening a device such as /dev/dri/card0
Parameters
fd The file descriptor for a backend specific device
Returns
The newly created struct gbm_device. The resources associated with the device should be freed with gbm_device_destroy() when it is no longer needed. If the creation of the device failed NULL will be returned.
References _gbm_create_device(), gbm_device::dummy, gbm_create_device(), GBM_EXPORT, gbm_device::refcount, and gbm_device::stat.
Referenced by gbm_create_device().
gbm_device_destroy()
GBM_EXPORT void gbm_device_destroy (struct gbm_device * gbm)
Destroy the gbm device and free all resources associated with it.
Parameters
gbm The device created using gbm_create_device()
References gbm_device::destroy, GBM_EXPORT, and gbm_device::refcount.
gbm_device_get_backend_name()
GBM_EXPORT const char* gbm_device_get_backend_name (struct gbm_device * gbm)
Get the backend name for the given gbm device.
Returns
The backend name string - this belongs to the device and must not be freed
References GBM_EXPORT, and gbm_device::name.
gbm_device_get_fd()
GBM_EXPORT int gbm_device_get_fd (struct gbm_device * gbm)
Returns the file description for the gbm device.
Returns
The fd that the struct gbm_device was created with
References gbm_device::fd, and GBM_EXPORT.
gbm_device_is_format_supported()
GBM_EXPORT int gbm_device_is_format_supported (struct gbm_device * gbm, uint32_t format, uint32_t usage)
Test if a format is supported for a given set of usage flags.
Parameters
gbm The created buffer manager
format The format to test
usage A bitmask of the usages to test the format against
Returns
1 if the format is supported otherwise 0
See also
enum gbm_bo_flags for the list of flags that the format can be tested against
enum gbm_bo_format for the list of formats
References GBM_EXPORT, and gbm_device::is_format_supported.
gbm_surface_create()
GBM_EXPORT struct gbm_surface* gbm_surface_create (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags)
Allocate a surface object.
Parameters
gbm The gbm device returned from gbm_create_device()
width The width for the surface
height The height for the surface
format The format to use for the surface
Returns
A newly allocated surface that should be freed with gbm_surface_destroy() when no longer needed. If an error occurs during allocation NULL will be returned.
See also
enum gbm_bo_format for the list of formats
References GBM_EXPORT, and gbm_device::surface_create.
gbm_surface_create_with_modifiers()
GBM_EXPORT struct gbm_surface* gbm_surface_create_with_modifiers (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t * modifiers, const unsigned int count)
References GBM_EXPORT, and gbm_device::surface_create.
gbm_surface_destroy()
GBM_EXPORT void gbm_surface_destroy (struct gbm_surface * surf)
Destroys the given surface and frees all resources associated with it.
All buffers locked with gbm_surface_lock_front_buffer() should be released prior to calling this function.
Parameters
surf The surface
References gbm_surface::gbm, GBM_EXPORT, and gbm_device::surface_destroy.
gbm_surface_has_free_buffers()
GBM_EXPORT int gbm_surface_has_free_buffers (struct gbm_surface * surf)
Return whether or not a surface has free (non-locked) buffers.
Before starting a new frame, the surface must have a buffer available for rendering. Initially, a gbm surface will have a free buffer, but after one or more buffers have been locked (
See also
gbm_surface_lock_front_buffer()), the application must check for a free buffer before rendering.
If a surface doesn't have a free buffer, the application must return a buffer to the surface using gbm_surface_release_buffer() and after that, the application can query for free buffers again.
Parameters
surf The surface
Returns
1 if the surface has free buffers, 0 otherwise
References gbm_surface::gbm, and gbm_device::surface_has_free_buffers.
gbm_surface_lock_front_buffer()
GBM_EXPORT struct gbm_bo* gbm_surface_lock_front_buffer (struct gbm_surface * surf)
Lock the surface's current front buffer.
Lock rendering to the surface's current front buffer until it is released with gbm_surface_release_buffer().
This function must be called exactly once after calling eglSwapBuffers. Calling it before any eglSwapBuffer has happened on the surface or two or more times after eglSwapBuffers is an error. A new bo representing the new front buffer is returned. On multiple invocations, all the returned bos must be released in order to release the actual surface buffer.
Parameters
surf The surface
Returns
A buffer object that should be released with gbm_surface_release_buffer() when no longer needed. The implementation is free to reuse buffers released with gbm_surface_release_buffer() so this bo should not be destroyed using gbm_bo_destroy(). If an error occurs this function returns NULL.
References gbm_surface::gbm, GBM_EXPORT, and gbm_device::surface_lock_front_buffer.
gbm_surface_release_buffer()
GBM_EXPORT void gbm_surface_release_buffer (struct gbm_surface * surf, struct gbm_bo * bo)
Release a locked buffer obtained with gbm_surface_lock_front_buffer()
Returns the underlying buffer to the gbm surface. Releasing a bo will typically make gbm_surface_has_free_buffer() return 1 and thus allow rendering the next frame, but not always. The implementation may choose to destroy the bo immediately or reuse it, in which case the user data associated with it is unchanged.
Parameters
surf The surface
bo The buffer object
References gbm_surface::gbm, GBM_EXPORT, and gbm_device::surface_release_buffer.