Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gbm.h File Reference
Generic Buffer Manager.
#include <stddef.h>
#include <stdint.h>
Data Structures
union gbm_bo_handle
Abstraction representing the handle to a buffer allocated by the manager.
struct gbm_import_fd_data
Macros
#define __GBM__ 1
#define __gbm_fourcc_code(a, b, c, d)
#define GBM_FORMAT_BIG_ENDIAN (1<<31) /* format is big endian instead of little endian */
#define GBM_FORMAT_C8 __gbm_fourcc_code('C', '8', ' ', ' ') /* [7:0] C */
#define GBM_FORMAT_R8 __gbm_fourcc_code('R', '8', ' ', ' ') /* [7:0] R */
#define GBM_FORMAT_GR88 __gbm_fourcc_code('G', 'R', '8', '8') /* [15:0] G:R 8:8 little endian */
#define GBM_FORMAT_RGB332 __gbm_fourcc_code('R', 'G', 'B', '8') /* [7:0] R:G:B 3:3:2 */
#define GBM_FORMAT_BGR233 __gbm_fourcc_code('B', 'G', 'R', '8') /* [7:0] B:G:R 2:3:3 */
#define GBM_FORMAT_XRGB4444 __gbm_fourcc_code('X', 'R', '1', '2') /* [15:0] x:R:G:B 4:4:4:4 little endian */
#define GBM_FORMAT_XBGR4444 __gbm_fourcc_code('X', 'B', '1', '2') /* [15:0] x:B:G:R 4:4:4:4 little endian */
#define GBM_FORMAT_RGBX4444 __gbm_fourcc_code('R', 'X', '1', '2') /* [15:0] R:G:B:x 4:4:4:4 little endian */
#define GBM_FORMAT_BGRX4444 __gbm_fourcc_code('B', 'X', '1', '2') /* [15:0] B:G:R:x 4:4:4:4 little endian */
#define GBM_FORMAT_ARGB4444 __gbm_fourcc_code('A', 'R', '1', '2') /* [15:0] A:R:G:B 4:4:4:4 little endian */
#define GBM_FORMAT_ABGR4444 __gbm_fourcc_code('A', 'B', '1', '2') /* [15:0] A:B:G:R 4:4:4:4 little endian */
#define GBM_FORMAT_RGBA4444 __gbm_fourcc_code('R', 'A', '1', '2') /* [15:0] R:G:B:A 4:4:4:4 little endian */
#define GBM_FORMAT_BGRA4444 __gbm_fourcc_code('B', 'A', '1', '2') /* [15:0] B:G:R:A 4:4:4:4 little endian */
#define GBM_FORMAT_XRGB1555 __gbm_fourcc_code('X', 'R', '1', '5') /* [15:0] x:R:G:B 1:5:5:5 little endian */
#define GBM_FORMAT_XBGR1555 __gbm_fourcc_code('X', 'B', '1', '5') /* [15:0] x:B:G:R 1:5:5:5 little endian */
#define GBM_FORMAT_RGBX5551 __gbm_fourcc_code('R', 'X', '1', '5') /* [15:0] R:G:B:x 5:5:5:1 little endian */
#define GBM_FORMAT_BGRX5551 __gbm_fourcc_code('B', 'X', '1', '5') /* [15:0] B:G:R:x 5:5:5:1 little endian */
#define GBM_FORMAT_ARGB1555 __gbm_fourcc_code('A', 'R', '1', '5') /* [15:0] A:R:G:B 1:5:5:5 little endian */
#define GBM_FORMAT_ABGR1555 __gbm_fourcc_code('A', 'B', '1', '5') /* [15:0] A:B:G:R 1:5:5:5 little endian */
#define GBM_FORMAT_RGBA5551 __gbm_fourcc_code('R', 'A', '1', '5') /* [15:0] R:G:B:A 5:5:5:1 little endian */
#define GBM_FORMAT_BGRA5551 __gbm_fourcc_code('B', 'A', '1', '5') /* [15:0] B:G:R:A 5:5:5:1 little endian */
#define GBM_FORMAT_RGB565 __gbm_fourcc_code('R', 'G', '1', '6') /* [15:0] R:G:B 5:6:5 little endian */
#define GBM_FORMAT_BGR565 __gbm_fourcc_code('B', 'G', '1', '6') /* [15:0] B:G:R 5:6:5 little endian */
#define GBM_FORMAT_RGB888 __gbm_fourcc_code('R', 'G', '2', '4') /* [23:0] R:G:B little endian */
#define GBM_FORMAT_BGR888 __gbm_fourcc_code('B', 'G', '2', '4') /* [23:0] B:G:R little endian */
#define GBM_FORMAT_XRGB8888 __gbm_fourcc_code('X', 'R', '2', '4') /* [31:0] x:R:G:B 8:8:8:8 little endian */
#define GBM_FORMAT_XBGR8888 __gbm_fourcc_code('X', 'B', '2', '4') /* [31:0] x:B:G:R 8:8:8:8 little endian */
#define GBM_FORMAT_RGBX8888 __gbm_fourcc_code('R', 'X', '2', '4') /* [31:0] R:G:B:x 8:8:8:8 little endian */
#define GBM_FORMAT_BGRX8888 __gbm_fourcc_code('B', 'X', '2', '4') /* [31:0] B:G:R:x 8:8:8:8 little endian */
#define GBM_FORMAT_ARGB8888 __gbm_fourcc_code('A', 'R', '2', '4') /* [31:0] A:R:G:B 8:8:8:8 little endian */
#define GBM_FORMAT_ABGR8888 __gbm_fourcc_code('A', 'B', '2', '4') /* [31:0] A:B:G:R 8:8:8:8 little endian */
#define GBM_FORMAT_RGBA8888 __gbm_fourcc_code('R', 'A', '2', '4') /* [31:0] R:G:B:A 8:8:8:8 little endian */
#define GBM_FORMAT_BGRA8888 __gbm_fourcc_code('B', 'A', '2', '4') /* [31:0] B:G:R:A 8:8:8:8 little endian */
#define GBM_FORMAT_XRGB2101010 __gbm_fourcc_code('X', 'R', '3', '0') /* [31:0] x:R:G:B 2:10:10:10 little endian */
#define GBM_FORMAT_XBGR2101010 __gbm_fourcc_code('X', 'B', '3', '0') /* [31:0] x:B:G:R 2:10:10:10 little endian */
#define GBM_FORMAT_RGBX1010102 __gbm_fourcc_code('R', 'X', '3', '0') /* [31:0] R:G:B:x 10:10:10:2 little endian */
#define GBM_FORMAT_BGRX1010102 __gbm_fourcc_code('B', 'X', '3', '0') /* [31:0] B:G:R:x 10:10:10:2 little endian */
#define GBM_FORMAT_ARGB2101010 __gbm_fourcc_code('A', 'R', '3', '0') /* [31:0] A:R:G:B 2:10:10:10 little endian */
#define GBM_FORMAT_ABGR2101010 __gbm_fourcc_code('A', 'B', '3', '0') /* [31:0] A:B:G:R 2:10:10:10 little endian */
#define GBM_FORMAT_RGBA1010102 __gbm_fourcc_code('R', 'A', '3', '0') /* [31:0] R:G:B:A 10:10:10:2 little endian */
#define GBM_FORMAT_BGRA1010102 __gbm_fourcc_code('B', 'A', '3', '0') /* [31:0] B:G:R:A 10:10:10:2 little endian */
#define GBM_FORMAT_YUYV __gbm_fourcc_code('Y', 'U', 'Y', 'V') /* [31:0] Cr0:Y1:Cb0:Y0 8:8:8:8 little endian */
#define GBM_FORMAT_YVYU __gbm_fourcc_code('Y', 'V', 'Y', 'U') /* [31:0] Cb0:Y1:Cr0:Y0 8:8:8:8 little endian */
#define GBM_FORMAT_UYVY __gbm_fourcc_code('U', 'Y', 'V', 'Y') /* [31:0] Y1:Cr0:Y0:Cb0 8:8:8:8 little endian */
#define GBM_FORMAT_VYUY __gbm_fourcc_code('V', 'Y', 'U', 'Y') /* [31:0] Y1:Cb0:Y0:Cr0 8:8:8:8 little endian */
#define GBM_FORMAT_AYUV __gbm_fourcc_code('A', 'Y', 'U', 'V') /* [31:0] A:Y:Cb:Cr 8:8:8:8 little endian */
#define GBM_FORMAT_NV12 __gbm_fourcc_code('N', 'V', '1', '2') /* 2x2 subsampled Cr:Cb plane */
#define GBM_FORMAT_NV21 __gbm_fourcc_code('N', 'V', '2', '1') /* 2x2 subsampled Cb:Cr plane */
#define GBM_FORMAT_NV16 __gbm_fourcc_code('N', 'V', '1', '6') /* 2x1 subsampled Cr:Cb plane */
#define GBM_FORMAT_NV61 __gbm_fourcc_code('N', 'V', '6', '1') /* 2x1 subsampled Cb:Cr plane */
#define GBM_FORMAT_YUV410 __gbm_fourcc_code('Y', 'U', 'V', '9') /* 4x4 subsampled Cb (1) and Cr (2) planes */
#define GBM_FORMAT_YVU410 __gbm_fourcc_code('Y', 'V', 'U', '9') /* 4x4 subsampled Cr (1) and Cb (2) planes */
#define GBM_FORMAT_YUV411 __gbm_fourcc_code('Y', 'U', '1', '1') /* 4x1 subsampled Cb (1) and Cr (2) planes */
#define GBM_FORMAT_YVU411 __gbm_fourcc_code('Y', 'V', '1', '1') /* 4x1 subsampled Cr (1) and Cb (2) planes */
#define GBM_FORMAT_YUV420 __gbm_fourcc_code('Y', 'U', '1', '2') /* 2x2 subsampled Cb (1) and Cr (2) planes */
#define GBM_FORMAT_YVU420 __gbm_fourcc_code('Y', 'V', '1', '2') /* 2x2 subsampled Cr (1) and Cb (2) planes */
#define GBM_FORMAT_YUV422 __gbm_fourcc_code('Y', 'U', '1', '6') /* 2x1 subsampled Cb (1) and Cr (2) planes */
#define GBM_FORMAT_YVU422 __gbm_fourcc_code('Y', 'V', '1', '6') /* 2x1 subsampled Cr (1) and Cb (2) planes */
#define GBM_FORMAT_YUV444 __gbm_fourcc_code('Y', 'U', '2', '4') /* non-subsampled Cb (1) and Cr (2) planes */
#define GBM_FORMAT_YVU444 __gbm_fourcc_code('Y', 'V', '2', '4') /* non-subsampled Cr (1) and Cb (2) planes */
#define GBM_BO_IMPORT_WL_BUFFER 0x5501
#define GBM_BO_IMPORT_EGL_IMAGE 0x5502
#define GBM_BO_IMPORT_FD 0x5503
Enumerations
enum gbm_bo_format { GBM_BO_FORMAT_XRGB8888, GBM_BO_FORMAT_ARGB8888 }
Format of the allocated buffer.
enum gbm_bo_flags {
GBM_BO_USE_SCANOUT = (1 << 0), GBM_BO_USE_CURSOR = (1 << 1), GBM_BO_USE_CURSOR_64X64 = GBM_BO_USE_CURSOR, GBM_BO_USE_RENDERING = (1 << 2),
GBM_BO_USE_WRITE = (1 << 3), GBM_BO_USE_LINEAR = (1 << 4)
}
Flags to indicate the intended use for the buffer - these are passed into gbm_bo_create().
enum gbm_bo_transfer_flags { GBM_BO_TRANSFER_READ = (1 << 0), GBM_BO_TRANSFER_WRITE = (1 << 1), GBM_BO_TRANSFER_READ_WRITE = (GBM_BO_TRANSFER_READ | GBM_BO_TRANSFER_WRITE) }
Flags to indicate the type of mapping for the buffer - these are passed into gbm_bo_map().
Functions
int gbm_device_get_fd (struct gbm_device *gbm)
Returns the file description for the gbm device.
const char * gbm_device_get_backend_name (struct gbm_device *gbm)
Get the backend name for the given gbm device.
int gbm_device_is_format_supported (struct gbm_device *gbm, uint32_t format, uint32_t usage)
Test if a format is supported for a given set of usage flags.
void gbm_device_destroy (struct gbm_device *gbm)
Destroy the gbm device and free all resources associated with it.
struct gbm_device * gbm_create_device (int fd)
Create a gbm device for allocating buffers.
struct gbm_bo * gbm_bo_create (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags)
Allocate a buffer object for the given dimensions.
struct gbm_bo * gbm_bo_create_with_modifiers (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t *modifiers, const unsigned int count)
struct gbm_bo * gbm_bo_import (struct gbm_device *gbm, uint32_t type, void *buffer, uint32_t usage)
Create a gbm buffer object from an foreign object.
void * gbm_bo_map (struct gbm_bo *bo, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t flags, uint32_t *stride, void **map_data)
Map a region of a gbm buffer object for cpu access.
void gbm_bo_unmap (struct gbm_bo *bo, void *map_data)
Unmap a previously mapped region of a gbm buffer object.
uint32_t gbm_bo_get_width (struct gbm_bo *bo)
Get the width of the buffer object.
uint32_t gbm_bo_get_height (struct gbm_bo *bo)
Get the height of the buffer object.
uint32_t gbm_bo_get_stride (struct gbm_bo *bo)
Get the stride of the buffer object.
uint32_t gbm_bo_get_stride_for_plane (struct gbm_bo *bo, int plane)
Get the stride for the given plane.
uint32_t gbm_bo_get_format (struct gbm_bo *bo)
Get the format of the buffer object.
uint32_t gbm_bo_get_offset (struct gbm_bo *bo, int plane)
Get the offset for the data of the specified plane.
struct gbm_device * gbm_bo_get_device (struct gbm_bo *bo)
Get the gbm device used to create the buffer object.
union gbm_bo_handle gbm_bo_get_handle (struct gbm_bo *bo)
Get the handle of the buffer object.
int gbm_bo_get_fd (struct gbm_bo *bo)
Get a DMA-BUF file descriptor for the buffer object.
uint64_t gbm_bo_get_modifier (struct gbm_bo *bo)
Get the chosen modifier for the buffer object.
int gbm_bo_get_plane_count (struct gbm_bo *bo)
Get the number of planes for the given bo.
union gbm_bo_handle gbm_bo_get_handle_for_plane (struct gbm_bo *bo, int plane)
Get the handle for the specified plane of the buffer object.
int gbm_bo_write (struct gbm_bo *bo, const void *buf, size_t count)
Write data into the buffer object.
void gbm_bo_set_user_data (struct gbm_bo *bo, void *data, void(*destroy_user_data)(struct gbm_bo *, void *))
Set the user data associated with a buffer object.
void * gbm_bo_get_user_data (struct gbm_bo *bo)
Get the user data associated with a buffer object.
void gbm_bo_destroy (struct gbm_bo *bo)
Destroys the given buffer object and frees all resources associated with it.
struct gbm_surface * gbm_surface_create (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags)
Allocate a surface object.
struct gbm_surface * gbm_surface_create_with_modifiers (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t *modifiers, const unsigned int count)
int gbm_surface_needs_lock_front_buffer (struct gbm_surface *surface)
struct gbm_bo * gbm_surface_lock_front_buffer (struct gbm_surface *surface)
Lock the surface's current front buffer.
void gbm_surface_release_buffer (struct gbm_surface *surface, struct gbm_bo *bo)
Release a locked buffer obtained with gbm_surface_lock_front_buffer()
int gbm_surface_has_free_buffers (struct gbm_surface *surface)
Return whether or not a surface has free (non-locked) buffers.
void gbm_surface_destroy (struct gbm_surface *surface)
Destroys the given surface and frees all resources associated with it.
Detailed Description
Generic Buffer Manager.
Macro Definition Documentation
__GBM__
#define __GBM__ 1
__gbm_fourcc_code
#define __gbm_fourcc_code (a, b, c, d)
Value:
((uint32_t)(a) | ((uint32_t)(b) << 8) | \
                              ((uint32_t)(c) << 16) | ((uint32_t)(d) << 24))
GBM_BO_IMPORT_EGL_IMAGE
#define GBM_BO_IMPORT_EGL_IMAGE 0x5502
GBM_BO_IMPORT_FD
#define GBM_BO_IMPORT_FD 0x5503
GBM_BO_IMPORT_WL_BUFFER
#define GBM_BO_IMPORT_WL_BUFFER 0x5501
GBM_FORMAT_ABGR1555
#define GBM_FORMAT_ABGR1555 __gbm_fourcc_code('A', 'B', '1', '5') /* [15:0] A:B:G:R 1:5:5:5 little endian */
GBM_FORMAT_ABGR2101010
#define GBM_FORMAT_ABGR2101010 __gbm_fourcc_code('A', 'B', '3', '0') /* [31:0] A:B:G:R 2:10:10:10 little endian */
GBM_FORMAT_ABGR4444
#define GBM_FORMAT_ABGR4444 __gbm_fourcc_code('A', 'B', '1', '2') /* [15:0] A:B:G:R 4:4:4:4 little endian */
GBM_FORMAT_ABGR8888
#define GBM_FORMAT_ABGR8888 __gbm_fourcc_code('A', 'B', '2', '4') /* [31:0] A:B:G:R 8:8:8:8 little endian */
GBM_FORMAT_ARGB1555
#define GBM_FORMAT_ARGB1555 __gbm_fourcc_code('A', 'R', '1', '5') /* [15:0] A:R:G:B 1:5:5:5 little endian */
GBM_FORMAT_ARGB2101010
#define GBM_FORMAT_ARGB2101010 __gbm_fourcc_code('A', 'R', '3', '0') /* [31:0] A:R:G:B 2:10:10:10 little endian */
GBM_FORMAT_ARGB4444
#define GBM_FORMAT_ARGB4444 __gbm_fourcc_code('A', 'R', '1', '2') /* [15:0] A:R:G:B 4:4:4:4 little endian */
GBM_FORMAT_ARGB8888
#define GBM_FORMAT_ARGB8888 __gbm_fourcc_code('A', 'R', '2', '4') /* [31:0] A:R:G:B 8:8:8:8 little endian */
GBM_FORMAT_AYUV
#define GBM_FORMAT_AYUV __gbm_fourcc_code('A', 'Y', 'U', 'V') /* [31:0] A:Y:Cb:Cr 8:8:8:8 little endian */
GBM_FORMAT_BGR233
#define GBM_FORMAT_BGR233 __gbm_fourcc_code('B', 'G', 'R', '8') /* [7:0] B:G:R 2:3:3 */
GBM_FORMAT_BGR565
#define GBM_FORMAT_BGR565 __gbm_fourcc_code('B', 'G', '1', '6') /* [15:0] B:G:R 5:6:5 little endian */
GBM_FORMAT_BGR888
#define GBM_FORMAT_BGR888 __gbm_fourcc_code('B', 'G', '2', '4') /* [23:0] B:G:R little endian */
GBM_FORMAT_BGRA1010102
#define GBM_FORMAT_BGRA1010102 __gbm_fourcc_code('B', 'A', '3', '0') /* [31:0] B:G:R:A 10:10:10:2 little endian */
GBM_FORMAT_BGRA4444
#define GBM_FORMAT_BGRA4444 __gbm_fourcc_code('B', 'A', '1', '2') /* [15:0] B:G:R:A 4:4:4:4 little endian */
GBM_FORMAT_BGRA5551
#define GBM_FORMAT_BGRA5551 __gbm_fourcc_code('B', 'A', '1', '5') /* [15:0] B:G:R:A 5:5:5:1 little endian */
GBM_FORMAT_BGRA8888
#define GBM_FORMAT_BGRA8888 __gbm_fourcc_code('B', 'A', '2', '4') /* [31:0] B:G:R:A 8:8:8:8 little endian */
GBM_FORMAT_BGRX1010102
#define GBM_FORMAT_BGRX1010102 __gbm_fourcc_code('B', 'X', '3', '0') /* [31:0] B:G:R:x 10:10:10:2 little endian */
GBM_FORMAT_BGRX4444
#define GBM_FORMAT_BGRX4444 __gbm_fourcc_code('B', 'X', '1', '2') /* [15:0] B:G:R:x 4:4:4:4 little endian */
GBM_FORMAT_BGRX5551
#define GBM_FORMAT_BGRX5551 __gbm_fourcc_code('B', 'X', '1', '5') /* [15:0] B:G:R:x 5:5:5:1 little endian */
GBM_FORMAT_BGRX8888
#define GBM_FORMAT_BGRX8888 __gbm_fourcc_code('B', 'X', '2', '4') /* [31:0] B:G:R:x 8:8:8:8 little endian */
GBM_FORMAT_BIG_ENDIAN
#define GBM_FORMAT_BIG_ENDIAN (1<<31) /* format is big endian instead of little endian */
GBM_FORMAT_C8
#define GBM_FORMAT_C8 __gbm_fourcc_code('C', '8', ' ', ' ') /* [7:0] C */
GBM_FORMAT_GR88
#define GBM_FORMAT_GR88 __gbm_fourcc_code('G', 'R', '8', '8') /* [15:0] G:R 8:8 little endian */
GBM_FORMAT_NV12
#define GBM_FORMAT_NV12 __gbm_fourcc_code('N', 'V', '1', '2') /* 2x2 subsampled Cr:Cb plane */
GBM_FORMAT_NV16
#define GBM_FORMAT_NV16 __gbm_fourcc_code('N', 'V', '1', '6') /* 2x1 subsampled Cr:Cb plane */
GBM_FORMAT_NV21
#define GBM_FORMAT_NV21 __gbm_fourcc_code('N', 'V', '2', '1') /* 2x2 subsampled Cb:Cr plane */
GBM_FORMAT_NV61
#define GBM_FORMAT_NV61 __gbm_fourcc_code('N', 'V', '6', '1') /* 2x1 subsampled Cb:Cr plane */
GBM_FORMAT_R8
#define GBM_FORMAT_R8 __gbm_fourcc_code('R', '8', ' ', ' ') /* [7:0] R */
GBM_FORMAT_RGB332
#define GBM_FORMAT_RGB332 __gbm_fourcc_code('R', 'G', 'B', '8') /* [7:0] R:G:B 3:3:2 */
GBM_FORMAT_RGB565
#define GBM_FORMAT_RGB565 __gbm_fourcc_code('R', 'G', '1', '6') /* [15:0] R:G:B 5:6:5 little endian */
GBM_FORMAT_RGB888
#define GBM_FORMAT_RGB888 __gbm_fourcc_code('R', 'G', '2', '4') /* [23:0] R:G:B little endian */
GBM_FORMAT_RGBA1010102
#define GBM_FORMAT_RGBA1010102 __gbm_fourcc_code('R', 'A', '3', '0') /* [31:0] R:G:B:A 10:10:10:2 little endian */
GBM_FORMAT_RGBA4444
#define GBM_FORMAT_RGBA4444 __gbm_fourcc_code('R', 'A', '1', '2') /* [15:0] R:G:B:A 4:4:4:4 little endian */
GBM_FORMAT_RGBA5551
#define GBM_FORMAT_RGBA5551 __gbm_fourcc_code('R', 'A', '1', '5') /* [15:0] R:G:B:A 5:5:5:1 little endian */
GBM_FORMAT_RGBA8888
#define GBM_FORMAT_RGBA8888 __gbm_fourcc_code('R', 'A', '2', '4') /* [31:0] R:G:B:A 8:8:8:8 little endian */
GBM_FORMAT_RGBX1010102
#define GBM_FORMAT_RGBX1010102 __gbm_fourcc_code('R', 'X', '3', '0') /* [31:0] R:G:B:x 10:10:10:2 little endian */
GBM_FORMAT_RGBX4444
#define GBM_FORMAT_RGBX4444 __gbm_fourcc_code('R', 'X', '1', '2') /* [15:0] R:G:B:x 4:4:4:4 little endian */
GBM_FORMAT_RGBX5551
#define GBM_FORMAT_RGBX5551 __gbm_fourcc_code('R', 'X', '1', '5') /* [15:0] R:G:B:x 5:5:5:1 little endian */
GBM_FORMAT_RGBX8888
#define GBM_FORMAT_RGBX8888 __gbm_fourcc_code('R', 'X', '2', '4') /* [31:0] R:G:B:x 8:8:8:8 little endian */
GBM_FORMAT_UYVY
#define GBM_FORMAT_UYVY __gbm_fourcc_code('U', 'Y', 'V', 'Y') /* [31:0] Y1:Cr0:Y0:Cb0 8:8:8:8 little endian */
GBM_FORMAT_VYUY
#define GBM_FORMAT_VYUY __gbm_fourcc_code('V', 'Y', 'U', 'Y') /* [31:0] Y1:Cb0:Y0:Cr0 8:8:8:8 little endian */
GBM_FORMAT_XBGR1555
#define GBM_FORMAT_XBGR1555 __gbm_fourcc_code('X', 'B', '1', '5') /* [15:0] x:B:G:R 1:5:5:5 little endian */
GBM_FORMAT_XBGR2101010
#define GBM_FORMAT_XBGR2101010 __gbm_fourcc_code('X', 'B', '3', '0') /* [31:0] x:B:G:R 2:10:10:10 little endian */
GBM_FORMAT_XBGR4444
#define GBM_FORMAT_XBGR4444 __gbm_fourcc_code('X', 'B', '1', '2') /* [15:0] x:B:G:R 4:4:4:4 little endian */
GBM_FORMAT_XBGR8888
#define GBM_FORMAT_XBGR8888 __gbm_fourcc_code('X', 'B', '2', '4') /* [31:0] x:B:G:R 8:8:8:8 little endian */
GBM_FORMAT_XRGB1555
#define GBM_FORMAT_XRGB1555 __gbm_fourcc_code('X', 'R', '1', '5') /* [15:0] x:R:G:B 1:5:5:5 little endian */
GBM_FORMAT_XRGB2101010
#define GBM_FORMAT_XRGB2101010 __gbm_fourcc_code('X', 'R', '3', '0') /* [31:0] x:R:G:B 2:10:10:10 little endian */
GBM_FORMAT_XRGB4444
#define GBM_FORMAT_XRGB4444 __gbm_fourcc_code('X', 'R', '1', '2') /* [15:0] x:R:G:B 4:4:4:4 little endian */
GBM_FORMAT_XRGB8888
#define GBM_FORMAT_XRGB8888 __gbm_fourcc_code('X', 'R', '2', '4') /* [31:0] x:R:G:B 8:8:8:8 little endian */
GBM_FORMAT_YUV410
#define GBM_FORMAT_YUV410 __gbm_fourcc_code('Y', 'U', 'V', '9') /* 4x4 subsampled Cb (1) and Cr (2) planes */
GBM_FORMAT_YUV411
#define GBM_FORMAT_YUV411 __gbm_fourcc_code('Y', 'U', '1', '1') /* 4x1 subsampled Cb (1) and Cr (2) planes */
GBM_FORMAT_YUV420
#define GBM_FORMAT_YUV420 __gbm_fourcc_code('Y', 'U', '1', '2') /* 2x2 subsampled Cb (1) and Cr (2) planes */
GBM_FORMAT_YUV422
#define GBM_FORMAT_YUV422 __gbm_fourcc_code('Y', 'U', '1', '6') /* 2x1 subsampled Cb (1) and Cr (2) planes */
GBM_FORMAT_YUV444
#define GBM_FORMAT_YUV444 __gbm_fourcc_code('Y', 'U', '2', '4') /* non-subsampled Cb (1) and Cr (2) planes */
GBM_FORMAT_YUYV
#define GBM_FORMAT_YUYV __gbm_fourcc_code('Y', 'U', 'Y', 'V') /* [31:0] Cr0:Y1:Cb0:Y0 8:8:8:8 little endian */
GBM_FORMAT_YVU410
#define GBM_FORMAT_YVU410 __gbm_fourcc_code('Y', 'V', 'U', '9') /* 4x4 subsampled Cr (1) and Cb (2) planes */
GBM_FORMAT_YVU411
#define GBM_FORMAT_YVU411 __gbm_fourcc_code('Y', 'V', '1', '1') /* 4x1 subsampled Cr (1) and Cb (2) planes */
GBM_FORMAT_YVU420
#define GBM_FORMAT_YVU420 __gbm_fourcc_code('Y', 'V', '1', '2') /* 2x2 subsampled Cr (1) and Cb (2) planes */
GBM_FORMAT_YVU422
#define GBM_FORMAT_YVU422 __gbm_fourcc_code('Y', 'V', '1', '6') /* 2x1 subsampled Cr (1) and Cb (2) planes */
GBM_FORMAT_YVU444
#define GBM_FORMAT_YVU444 __gbm_fourcc_code('Y', 'V', '2', '4') /* non-subsampled Cr (1) and Cb (2) planes */
GBM_FORMAT_YVYU
#define GBM_FORMAT_YVYU __gbm_fourcc_code('Y', 'V', 'Y', 'U') /* [31:0] Cb0:Y1:Cr0:Y0 8:8:8:8 little endian */
Enumeration Type Documentation
gbm_bo_flags
enum gbm_bo_flags
Flags to indicate the intended use for the buffer - these are passed into gbm_bo_create().
The caller must set the union of all the flags that are appropriate
See also
Use gbm_device_is_format_supported() to check if the combination of format and use flags are supported
Enumerator
GBM_BO_USE_SCANOUT
Buffer is going to be presented to the screen using an API such as KMS.
GBM_BO_USE_CURSOR
Buffer is going to be used as cursor.
GBM_BO_USE_CURSOR_64X64
Deprecated.
GBM_BO_USE_RENDERING
Buffer is to be used for rendering - for example it is going to be used as the storage for a color buffer.
GBM_BO_USE_WRITE
Buffer can be used for gbm_bo_write.
This is guaranteed to work with GBM_BO_USE_CURSOR, but may not work for other combinations.
GBM_BO_USE_LINEAR
Buffer is linear, i.e.
not tiled.
gbm_bo_format
enum gbm_bo_format
Format of the allocated buffer.
Enumerator
GBM_BO_FORMAT_XRGB8888
RGB with 8 bits per channel in a 32 bit value.
GBM_BO_FORMAT_ARGB8888
ARGB with 8 bits per channel in a 32 bit value.
gbm_bo_transfer_flags
enum gbm_bo_transfer_flags
Flags to indicate the type of mapping for the buffer - these are passed into gbm_bo_map().
The caller must set the union of all the flags that are appropriate.
These flags are independent of the GBM_BO_USE_* creation flags. However, mapping the buffer may require copying to/from a staging buffer.
See also: pipe_transfer_usage
Enumerator
GBM_BO_TRANSFER_READ
Buffer contents read back (or accessed directly) at transfer create time.
GBM_BO_TRANSFER_WRITE
Buffer contents will be written back at unmap time (or modified as a result of being accessed directly).
GBM_BO_TRANSFER_READ_WRITE
Read/modify/write.
Function Documentation
gbm_bo_create()
struct gbm_bo* gbm_bo_create (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage)
Allocate a buffer object for the given dimensions.
Parameters
gbm The gbm device returned from gbm_create_device()
width The width for the buffer
height The height for the buffer
format The format to use for the buffer
usage The union of the usage flags for this buffer
Returns
A newly allocated buffer that should be freed with gbm_bo_destroy() when no longer needed. If an error occurs during allocation NULL will be returned and errno set.
See also
enum gbm_bo_format for the list of formats
enum gbm_bo_flags for the list of usage flags
References gbm_device::bo_create, and GBM_EXPORT.
gbm_bo_create_with_modifiers()
struct gbm_bo* gbm_bo_create_with_modifiers (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t * modifiers, const unsigned int count)
References gbm_device::bo_create, and GBM_EXPORT.
gbm_bo_destroy()
void gbm_bo_destroy (struct gbm_bo * bo)
Destroys the given buffer object and frees all resources associated with it.
Parameters
bo The buffer object
References gbm_device::bo_destroy, gbm_bo::destroy_user_data, gbm_bo::gbm, GBM_EXPORT, and gbm_bo::user_data.
gbm_bo_get_device()
struct gbm_device* gbm_bo_get_device (struct gbm_bo * bo)
Get the gbm device used to create the buffer object.
Parameters
bo The buffer object
Returns
Returns the gbm device with which the buffer object was created
References gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_fd()
int gbm_bo_get_fd (struct gbm_bo * bo)
Get a DMA-BUF file descriptor for the buffer object.
This function creates a DMA-BUF (also known as PRIME) file descriptor handle for the buffer object. Each call to gbm_bo_get_fd() returns a new file descriptor and the caller is responsible for closing the file descriptor.
Parameters
bo The buffer object
Returns
Returns a file descriptor referring to the underlying buffer or -1 if an error occurs.
References gbm_device::bo_get_fd, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_format()
uint32_t gbm_bo_get_format (struct gbm_bo * bo)
Get the format of the buffer object.
The format of the pixels in the buffer.
Parameters
bo The buffer object
Returns
The format of buffer object, on of the GBM_FORMAT_* codes
References gbm_bo::format, and GBM_EXPORT.
gbm_bo_get_handle()
union gbm_bo_handle gbm_bo_get_handle (struct gbm_bo * bo)
Get the handle of the buffer object.
This is stored in the platform generic union gbm_bo_handle type. However the format of this handle is platform specific.
Parameters
bo The buffer object
Returns
Returns the handle of the allocated buffer object
References GBM_EXPORT.
gbm_bo_get_handle_for_plane()
union gbm_bo_handle gbm_bo_get_handle_for_plane (struct gbm_bo * bo, int plane)
Get the handle for the specified plane of the buffer object.
This function gets the handle for any plane associated with the BO. When dealing with multi-planar formats, or formats which might have implicit planes based on different underlying hardware it is necessary for the client to be able to get this information to pass to the DRM.
Parameters
bo The buffer object
plane the plane to get a handle for
See also
gbm_bo_get_handle()
References GBM_EXPORT.
gbm_bo_get_height()
uint32_t gbm_bo_get_height (struct gbm_bo * bo)
Get the height of the buffer object.
Parameters
bo The buffer object
Returns
The height of the allocated buffer object
References GBM_EXPORT, and gbm_bo::height.
gbm_bo_get_modifier()
uint64_t gbm_bo_get_modifier (struct gbm_bo * bo)
Get the chosen modifier for the buffer object.
This function returns the modifier that was chosen for the object. These properties may be generic, or platform/implementation dependent.
Parameters
bo The buffer object
Returns
Returns the selected modifier (chosen by the implementation) for the BO.
See also
gbm_bo_create_with_modifiers() where possible modifiers are set
gbm_surface_create_with_modifiers() where possible modifiers are set
define DRM_FORMAT_MOD_* in drm_fourcc.h for possible modifiers
References gbm_device::bo_get_modifier, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_offset()
uint32_t gbm_bo_get_offset (struct gbm_bo * bo, int plane)
Get the offset for the data of the specified plane.
Extra planes, and even the first plane, may have an offset from the start of the buffer object. This function will provide the offset for the given plane to be used in various KMS APIs.
Parameters
bo The buffer object
Returns
The offset
References gbm_device::bo_get_offset, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_plane_count()
int gbm_bo_get_plane_count (struct gbm_bo * bo)
Get the number of planes for the given bo.
Parameters
bo The buffer object
Returns
The number of planes
References gbm_device::bo_get_planes, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_get_stride()
uint32_t gbm_bo_get_stride (struct gbm_bo * bo)
Get the stride of the buffer object.
This is calculated by the backend when it does the allocation in gbm_bo_create()
Parameters
bo The buffer object
Returns
The stride of the allocated buffer object in bytes
References gbm_bo_get_stride_for_plane(), and GBM_EXPORT.
gbm_bo_get_stride_for_plane()
uint32_t gbm_bo_get_stride_for_plane (struct gbm_bo * bo, int plane)
Get the stride for the given plane.
Parameters
bo The buffer object
plane for which you want the stride
See also
gbm_bo_get_stride()
References gbm_device::bo_get_stride, gbm_bo::gbm, and GBM_EXPORT.
Referenced by gbm_bo_get_stride().
gbm_bo_get_user_data()
void* gbm_bo_get_user_data (struct gbm_bo * bo)
Get the user data associated with a buffer object.
Parameters
bo The buffer object
Returns
Returns the user data associated with the buffer object or NULL if no data was associated with it
See also
gbm_bo_set_user_data()
References GBM_EXPORT, and gbm_bo::user_data.
gbm_bo_get_width()
uint32_t gbm_bo_get_width (struct gbm_bo * bo)
Get the width of the buffer object.
Parameters
bo The buffer object
Returns
The width of the allocated buffer object
References GBM_EXPORT, and gbm_bo::width.
gbm_bo_import()
struct gbm_bo* gbm_bo_import (struct gbm_device * gbm, uint32_t type, void * buffer, uint32_t usage)
Create a gbm buffer object from an foreign object.
This function imports a foreign object and creates a new gbm bo for it. This enabled using the foreign object with a display API such as KMS. Currently three types of foreign objects are supported, indicated by the type argument:
GBM_BO_IMPORT_WL_BUFFER GBM_BO_IMPORT_EGL_IMAGE GBM_BO_IMPORT_FD
The gbm bo shares the underlying pixels but its life-time is independent of the foreign object.
Parameters
gbm The gbm device returned from gbm_create_device()
gbm The type of object we're importing
gbm Pointer to the external object
usage The union of the usage flags for this buffer
Returns
A newly allocated buffer object that should be freed with gbm_bo_destroy() when no longer needed. On error, NULL is returned and errno is set.
See also
enum gbm_bo_flags for the list of usage flags
References gbm_device::bo_import, and GBM_EXPORT.
gbm_bo_map()
void* gbm_bo_map (struct gbm_bo * bo, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t flags, uint32_t * stride, void ** map_data)
Map a region of a gbm buffer object for cpu access.
This function maps a region of a gbm bo for cpu read and/or write access.
Parameters
bo The buffer object
x The X (top left origin) starting position of the mapped region for the buffer
y The Y (top left origin) starting position of the mapped region for the buffer
width The width of the mapped region for the buffer
height The height of the mapped region for the buffer
flags The union of the GBM_BO_TRANSFER_* flags for this buffer
stride Ptr for returned stride in bytes of the mapped region
map_data Returned opaque ptr for the mapped region
Returns
Address of the mapped buffer that should be unmapped with gbm_bo_unmap() when no longer needed. On error, NULL is returned and errno is set.
See also
enum gbm_bo_transfer_flags for the list of flags
References gbm_device::bo_map, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_set_user_data()
void gbm_bo_set_user_data (struct gbm_bo * bo, void * data, void(*)(struct gbm_bo *, void *) destroy_user_data)
Set the user data associated with a buffer object.
Parameters
bo The buffer object
data The data to associate to the buffer object
destroy_user_data A callback (which may be NULL) that will be called prior to the buffer destruction
References gbm_bo::destroy_user_data, GBM_EXPORT, and gbm_bo::user_data.
gbm_bo_unmap()
void gbm_bo_unmap (struct gbm_bo * bo, void * map_data)
Unmap a previously mapped region of a gbm buffer object.
This function unmaps a region of a gbm bo for cpu read and/or write access.
Parameters
bo The buffer object
map_data opaque ptr returned from prior gbm_bo_map
References gbm_device::bo_unmap, gbm_bo::gbm, and GBM_EXPORT.
gbm_bo_write()
int gbm_bo_write (struct gbm_bo * bo, const void * buf, size_t count)
Write data into the buffer object.
If the buffer object was created with the GBM_BO_USE_WRITE flag, this function can be used to write data into the buffer object. The data is copied directly into the object and it's the responsibility of the caller to make sure the data represents valid pixel data, according to the width, height, stride and format of the buffer object.
Parameters
bo The buffer object
buf The data to write
count The number of bytes to write
Returns
Returns 0 on success, otherwise -1 is returned an errno set
References gbm_device::bo_write, gbm_bo::gbm, and GBM_EXPORT.
gbm_create_device()
struct gbm_device* gbm_create_device (int fd)
Create a gbm device for allocating buffers.
The file descriptor passed in is used by the backend to communicate with platform for allocating the memory. For allocations using DRI this would be the file descriptor returned when opening a device such as /dev/dri/card0
Parameters
fd The file descriptor for a backend specific device
Returns
The newly created struct gbm_device. The resources associated with the device should be freed with gbm_device_destroy() when it is no longer needed. If the creation of the device failed NULL will be returned.
References _gbm_create_device(), gbm_device::dummy, gbm_create_device(), GBM_EXPORT, gbm_device::refcount, and gbm_device::stat.
Referenced by gbm_create_device().
gbm_device_destroy()
void gbm_device_destroy (struct gbm_device * gbm)
Destroy the gbm device and free all resources associated with it.
Parameters
gbm The device created using gbm_create_device()
References gbm_device::destroy, GBM_EXPORT, and gbm_device::refcount.
gbm_device_get_backend_name()
const char* gbm_device_get_backend_name (struct gbm_device * gbm)
Get the backend name for the given gbm device.
Returns
The backend name string - this belongs to the device and must not be freed
References GBM_EXPORT, and gbm_device::name.
gbm_device_get_fd()
int gbm_device_get_fd (struct gbm_device * gbm)
Returns the file description for the gbm device.
Returns
The fd that the struct gbm_device was created with
References gbm_device::fd, and GBM_EXPORT.
gbm_device_is_format_supported()
int gbm_device_is_format_supported (struct gbm_device * gbm, uint32_t format, uint32_t usage)
Test if a format is supported for a given set of usage flags.
Parameters
gbm The created buffer manager
format The format to test
usage A bitmask of the usages to test the format against
Returns
1 if the format is supported otherwise 0
See also
enum gbm_bo_flags for the list of flags that the format can be tested against
enum gbm_bo_format for the list of formats
References GBM_EXPORT, and gbm_device::is_format_supported.
gbm_surface_create()
struct gbm_surface* gbm_surface_create (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags)
Allocate a surface object.
Parameters
gbm The gbm device returned from gbm_create_device()
width The width for the surface
height The height for the surface
format The format to use for the surface
Returns
A newly allocated surface that should be freed with gbm_surface_destroy() when no longer needed. If an error occurs during allocation NULL will be returned.
See also
enum gbm_bo_format for the list of formats
References GBM_EXPORT, and gbm_device::surface_create.
gbm_surface_create_with_modifiers()
struct gbm_surface* gbm_surface_create_with_modifiers (struct gbm_device * gbm, uint32_t width, uint32_t height, uint32_t format, const uint64_t * modifiers, const unsigned int count)
References GBM_EXPORT, and gbm_device::surface_create.
gbm_surface_destroy()
void gbm_surface_destroy (struct gbm_surface * surf)
Destroys the given surface and frees all resources associated with it.
All buffers locked with gbm_surface_lock_front_buffer() should be released prior to calling this function.
Parameters
surf The surface
References gbm_surface::gbm, GBM_EXPORT, and gbm_device::surface_destroy.
gbm_surface_has_free_buffers()
int gbm_surface_has_free_buffers (struct gbm_surface * surf)
Return whether or not a surface has free (non-locked) buffers.
Before starting a new frame, the surface must have a buffer available for rendering. Initially, a gbm surface will have a free buffer, but after one or more buffers have been locked (
See also
gbm_surface_lock_front_buffer()), the application must check for a free buffer before rendering.
If a surface doesn't have a free buffer, the application must return a buffer to the surface using gbm_surface_release_buffer() and after that, the application can query for free buffers again.
Parameters
surf The surface
Returns
1 if the surface has free buffers, 0 otherwise
References gbm_surface::gbm, and gbm_device::surface_has_free_buffers.
gbm_surface_lock_front_buffer()
struct gbm_bo* gbm_surface_lock_front_buffer (struct gbm_surface * surf)
Lock the surface's current front buffer.
Lock rendering to the surface's current front buffer until it is released with gbm_surface_release_buffer().
This function must be called exactly once after calling eglSwapBuffers. Calling it before any eglSwapBuffer has happened on the surface or two or more times after eglSwapBuffers is an error. A new bo representing the new front buffer is returned. On multiple invocations, all the returned bos must be released in order to release the actual surface buffer.
Parameters
surf The surface
Returns
A buffer object that should be released with gbm_surface_release_buffer() when no longer needed. The implementation is free to reuse buffers released with gbm_surface_release_buffer() so this bo should not be destroyed using gbm_bo_destroy(). If an error occurs this function returns NULL.
References gbm_surface::gbm, GBM_EXPORT, and gbm_device::surface_lock_front_buffer.
gbm_surface_needs_lock_front_buffer()
int gbm_surface_needs_lock_front_buffer (struct gbm_surface * surface)
gbm_surface_release_buffer()
void gbm_surface_release_buffer (struct gbm_surface * surf, struct gbm_bo * bo)
Release a locked buffer obtained with gbm_surface_lock_front_buffer()
Returns the underlying buffer to the gbm surface. Releasing a bo will typically make gbm_surface_has_free_buffer() return 1 and thus allow rendering the next frame, but not always. The implementation may choose to destroy the bo immediately or reuse it, in which case the user data associated with it is unchanged.
Parameters
surf The surface
bo The buffer object
References gbm_surface::gbm, GBM_EXPORT, and gbm_device::surface_release_buffer.