Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gbm_device Struct Reference
The device used for the memory allocation.
#include <gbmint.h>
Data Fields
struct gbm_device *(* dummy)(int)
int fd
const char * name
unsigned int refcount
struct stat stat
void(* destroy)(struct gbm_device *gbm)
int(* is_format_supported)(struct gbm_device *gbm, uint32_t format, uint32_t usage)
struct gbm_bo *(* bo_create)(struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage, const uint64_t *modifiers, const unsigned int count)
struct gbm_bo *(* bo_import)(struct gbm_device *gbm, uint32_t type, void *buffer, uint32_t usage)
void *(* bo_map)(struct gbm_bo *bo, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t flags, uint32_t *stride, void **map_data)
void(* bo_unmap)(struct gbm_bo *bo, void *map_data)
int(* bo_write)(struct gbm_bo *bo, const void *buf, size_t data)
int(* bo_get_fd)(struct gbm_bo *bo)
int(* bo_get_planes)(struct gbm_bo *bo)
union gbm_bo_handle(* bo_get_handle)(struct gbm_bo *bo, int plane)
uint32_t(* bo_get_stride)(struct gbm_bo *bo, int plane)
uint32_t(* bo_get_offset)(struct gbm_bo *bo, int plane)
uint64_t(* bo_get_modifier)(struct gbm_bo *bo)
void(* bo_destroy)(struct gbm_bo *bo)
struct gbm_surface *(* surface_create)(struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags, const uint64_t *modifiers, const unsigned count)
struct gbm_bo *(* surface_lock_front_buffer)(struct gbm_surface *surface)
void(* surface_release_buffer)(struct gbm_surface *surface, struct gbm_bo *bo)
int(* surface_has_free_buffers)(struct gbm_surface *surface)
void(* surface_destroy)(struct gbm_surface *surface)
Detailed Description
The device used for the memory allocation.
The members of this structure should be not accessed directly
Field Documentation
bo_create
struct gbm_bo*(* gbm_device::bo_create) (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage, const uint64_t *modifiers, const unsigned int count)
Referenced by gbm_bo_create(), and gbm_bo_create_with_modifiers().
bo_destroy
void(* gbm_device::bo_destroy) (struct gbm_bo *bo)
Referenced by gbm_bo_destroy().
bo_get_fd
int(* gbm_device::bo_get_fd) (struct gbm_bo *bo)
Referenced by gbm_bo_get_fd().
bo_get_handle
union gbm_bo_handle(* gbm_device::bo_get_handle) (struct gbm_bo *bo, int plane)
bo_get_modifier
uint64_t(* gbm_device::bo_get_modifier) (struct gbm_bo *bo)
Referenced by gbm_bo_get_modifier().
bo_get_offset
uint32_t(* gbm_device::bo_get_offset) (struct gbm_bo *bo, int plane)
Referenced by gbm_bo_get_offset().
bo_get_planes
int(* gbm_device::bo_get_planes) (struct gbm_bo *bo)
Referenced by gbm_bo_get_plane_count().
bo_get_stride
uint32_t(* gbm_device::bo_get_stride) (struct gbm_bo *bo, int plane)
Referenced by gbm_bo_get_stride_for_plane().
bo_import
struct gbm_bo*(* gbm_device::bo_import) (struct gbm_device *gbm, uint32_t type, void *buffer, uint32_t usage)
Referenced by gbm_bo_import().
bo_map
void*(* gbm_device::bo_map) (struct gbm_bo *bo, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t flags, uint32_t *stride, void **map_data)
Referenced by gbm_bo_map().
bo_unmap
void(* gbm_device::bo_unmap) (struct gbm_bo *bo, void *map_data)
Referenced by gbm_bo_unmap().
bo_write
int(* gbm_device::bo_write) (struct gbm_bo *bo, const void *buf, size_t data)
Referenced by gbm_bo_write().
destroy
void(* gbm_device::destroy) (struct gbm_device *gbm)
Referenced by gbm_device_destroy().
dummy
struct gbm_device*(* gbm_device::dummy) (int)
Referenced by gbm_create_device().
fd
int gbm_device::fd
Referenced by gbm_device_get_fd().
is_format_supported
int(* gbm_device::is_format_supported) (struct gbm_device *gbm, uint32_t format, uint32_t usage)
Referenced by gbm_device_is_format_supported().
name
const char* gbm_device::name
Referenced by gbm_device_get_backend_name().
refcount
unsigned int gbm_device::refcount
Referenced by gbm_create_device(), and gbm_device_destroy().
stat
struct stat gbm_device::stat
Referenced by gbm_create_device().
surface_create
struct gbm_surface*(* gbm_device::surface_create) (struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags, const uint64_t *modifiers, const unsigned count)
Referenced by gbm_surface_create(), and gbm_surface_create_with_modifiers().
surface_destroy
void(* gbm_device::surface_destroy) (struct gbm_surface *surface)
Referenced by gbm_surface_destroy().
surface_has_free_buffers
int(* gbm_device::surface_has_free_buffers) (struct gbm_surface *surface)
Referenced by gbm_surface_has_free_buffers().
surface_lock_front_buffer
struct gbm_bo*(* gbm_device::surface_lock_front_buffer) (struct gbm_surface *surface)
Referenced by gbm_surface_lock_front_buffer().
surface_release_buffer
void(* gbm_device::surface_release_buffer) (struct gbm_surface *surface, struct gbm_bo *bo)
Referenced by gbm_surface_release_buffer().
The documentation for this struct was generated from the following file:
gbmint.h