Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_context.c File Reference
#include "main/glheader.h"
#include "main/imports.h"
#include "main/context.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/light.h"
#include "math/m_translate.h"
#include "math/m_xform.h"
#include "main/state.h"
#include "main/viewport.h"
#include "util/simple_list.h"
#include "tnl.h"
#include "t_context.h"
#include "t_pipeline.h"
#include "vbo/vbo.h"
Functions
GLboolean _tnl_CreateContext (struct gl_context *ctx)
void _tnl_DestroyContext (struct gl_context *ctx)
void _tnl_InvalidateState (struct gl_context *ctx, GLuint new_state)
void _tnl_wakeup (struct gl_context *ctx)
void _tnl_need_projected_coords (struct gl_context *ctx, GLboolean mode)
Drivers call this function to tell the TCL module whether or not it wants Normalized Device Coords (NDC) computed.
void _tnl_allow_vertex_fog (struct gl_context *ctx, GLboolean value)
void _tnl_allow_pixel_fog (struct gl_context *ctx, GLboolean value)
Function Documentation
_tnl_allow_pixel_fog()
void _tnl_allow_pixel_fog (struct gl_context * ctx, GLboolean value)
References gl_fragment_program_state::_Current, TNLcontext::_DoVertexFog, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_hint_attrib::Fog, gl_context::FragmentProgram, gl_context::Hint, and TNL_CONTEXT.
_tnl_allow_vertex_fog()
void _tnl_allow_vertex_fog (struct gl_context * ctx, GLboolean value)
References gl_fragment_program_state::_Current, TNLcontext::_DoVertexFog, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_hint_attrib::Fog, gl_context::FragmentProgram, gl_context::Hint, and TNL_CONTEXT.
_tnl_CreateContext()
GLboolean _tnl_CreateContext (struct gl_context * ctx)
References gl_vertex_program_state::_MaintainTnlProgram, _math_init_transformation(), _math_init_translate(), _math_matrix_ctr(), TNLcontext::_ShineTabList, _tnl_default_pipeline, _tnl_draw_prims(), _tnl_install_pipeline(), _tnl_render_tab_elts, _tnl_render_tab_verts, _tnl_validate_shine_tables(), _tnl_vp_pipeline, TNLcontext::_WindowMap, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_context::Const, TNLcontext::Driver, GLuint, MALLOC_STRUCT, MAX_CLIPPED_VERTICES, gl_constants::MaxArrayLockSize, TNLcontext::NeedNdcCoords, tnl_device_driver::NotifyMaterialChange, TNLcontext::nr_blocks, tnl_device_driver::PrimTabElts, tnl_device_driver::PrimTabVerts, tnl_shine_tab::refcount, tnl_device_driver::Render, tnl_shine_tab::shininess, vertex_buffer::Size, gl_context::swtnl_context, TNLcontext::vb, vbo_set_draw_func(), and gl_context::VertexProgram.
_tnl_DestroyContext()
void _tnl_DestroyContext (struct gl_context * ctx)
References _math_matrix_dtr(), TNLcontext::_ShineTabList, _tnl_destroy_pipeline(), TNLcontext::_WindowMap, gl_context::swtnl_context, and TNL_CONTEXT.
_tnl_InvalidateState()
void _tnl_InvalidateState (struct gl_context * ctx, GLuint new_state)
References gl_point_attrib::_Attenuated, gl_vertex_program_state::_Current, gl_fragment_program_state::_Current, gl_framebuffer::_DepthMaxF, TNLcontext::_DoVertexFog, gl_texture_attrib::_EnabledCoordUnits, _math_matrix_viewport(), _mesa_get_viewport_xform(), _NEW_BUFFERS, _NEW_HINT, _NEW_PROGRAM, _NEW_VIEWPORT, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_COLOR1, _TNL_ATTRIB_EDGEFLAG, _TNL_ATTRIB_FOG, _TNL_ATTRIB_GENERIC, _TNL_ATTRIB_POINTSIZE, _TNL_ATTRIB_POS, _TNL_ATTRIB_TEX, _TNL_ATTRIB_TEX0, TNLcontext::_WindowMap, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_polygon_attrib::BackMode, BITFIELD64_BIT, gl_context::Const, gl_context::DrawBuffer, gl_fog_attrib::Enabled, gl_hint_attrib::Fog, gl_context::Fog, gl_context::FragmentProgram, gl_polygon_attrib::FrontMode, GLuint, gl_context::Hint, gl_program::info, gl_constants::MaxTextureCoordUnits, tnl_pipeline::new_state, TNLcontext::pipeline, gl_context::Point, gl_vertex_program_state::PointSizeEnabled, gl_context::Polygon, TNLcontext::render_inputs_bitset, gl_context::RenderMode, gl_context::Texture, TNL_CONTEXT, and gl_context::VertexProgram.
Referenced by _tnl_wakeup().
_tnl_need_projected_coords()
void _tnl_need_projected_coords (struct gl_context * ctx, GLboolean mode)
Drivers call this function to tell the TCL module whether or not it wants Normalized Device Coords (NDC) computed.
I.e. whether we should "Divide-by-W". Software renders will want that.
References TNLcontext::NeedNdcCoords, and TNL_CONTEXT.
_tnl_wakeup()
void _tnl_wakeup (struct gl_context * ctx)
References _mesa_update_color_material(), _tnl_InvalidateState(), gl_current_attrib::Attrib, gl_light_attrib::ColorMaterialEnabled, gl_context::Current, and gl_context::Light.