Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_pipeline.h File Reference
#include "main/mtypes.h"
#include "t_context.h"
Functions
void _tnl_run_pipeline (struct gl_context *ctx)
void _tnl_destroy_pipeline (struct gl_context *ctx)
void _tnl_install_pipeline (struct gl_context *ctx, const struct tnl_pipeline_stage **stages)
void _tnl_RenderClippedPolygon (struct gl_context *ctx, const GLuint *elts, GLuint n)
void _tnl_RenderClippedLine (struct gl_context *ctx, GLuint ii, GLuint jj)
Variables
const struct tnl_pipeline_stage _tnl_vertex_transform_stage
const struct tnl_pipeline_stage _tnl_normal_transform_stage
const struct tnl_pipeline_stage _tnl_lighting_stage
const struct tnl_pipeline_stage _tnl_fog_coordinate_stage
const struct tnl_pipeline_stage _tnl_texgen_stage
const struct tnl_pipeline_stage _tnl_texture_transform_stage
const struct tnl_pipeline_stage _tnl_point_attenuation_stage
const struct tnl_pipeline_stage _tnl_vertex_program_stage
Public description of this pipeline stage.
const struct tnl_pipeline_stage _tnl_render_stage
const struct tnl_pipeline_stage * _tnl_default_pipeline []
const struct tnl_pipeline_stage * _tnl_vp_pipeline []
tnl_render_func _tnl_render_tab_elts []
tnl_render_func _tnl_render_tab_verts []
Function Documentation
_tnl_destroy_pipeline()
void _tnl_destroy_pipeline (struct gl_context * ctx)
References tnl_pipeline_stage::destroy, GLuint, tnl_pipeline::nr_stages, TNLcontext::pipeline, tnl_pipeline::stages, and TNL_CONTEXT.
Referenced by _tnl_DestroyContext().
_tnl_install_pipeline()
void _tnl_install_pipeline (struct gl_context * ctx, const struct tnl_pipeline_stage ** stages)
References tnl_pipeline_stage::create, GLuint, MAX_PIPELINE_STAGES, tnl_pipeline::new_state, tnl_pipeline::nr_stages, TNLcontext::pipeline, tnl_pipeline::stages, and TNL_CONTEXT.
Referenced by _tnl_CreateContext().
_tnl_RenderClippedLine()
void _tnl_RenderClippedLine (struct gl_context * ctx, GLuint ii, GLuint jj)
References TNLcontext::Driver, tnl_device_driver::Line, tnl_device_driver::Render, and TNL_CONTEXT.
_tnl_RenderClippedPolygon()
void _tnl_RenderClippedPolygon (struct gl_context * ctx, const GLuint * elts, GLuint n)
References TNLcontext::Driver, vertex_buffer::Elts, GLuint, PRIM_BEGIN, PRIM_END, tnl_device_driver::PrimTabElts, tnl_device_driver::Render, TNL_CONTEXT, and TNLcontext::vb.
_tnl_run_pipeline()
void _tnl_run_pipeline (struct gl_context * ctx)
References gl_vertex_program_state::_MaintainTnlProgram, _tnl_notify_pipeline_output_change(), _tnl_UpdateFixedFunctionProgram(), check_input_changes(), check_output_changes(), vertex_buffer::Count, END_FAST_MATH, GLuint, tnl_pipeline::input_changes, tnl_pipeline::new_state, tnl_pipeline::nr_stages, TNLcontext::pipeline, tnl_pipeline_stage::run, tnl_pipeline::stages, START_FAST_MATH, TNL_CONTEXT, tnl_pipeline_stage::validate, TNLcontext::vb, and gl_context::VertexProgram.
Variable Documentation
_tnl_default_pipeline
const struct tnl_pipeline_stage* _tnl_default_pipeline[]
Referenced by _tnl_CreateContext().
_tnl_fog_coordinate_stage
const struct tnl_pipeline_stage _tnl_fog_coordinate_stage
_tnl_lighting_stage
const struct tnl_pipeline_stage _tnl_lighting_stage
_tnl_normal_transform_stage
const struct tnl_pipeline_stage _tnl_normal_transform_stage
_tnl_point_attenuation_stage
const struct tnl_pipeline_stage _tnl_point_attenuation_stage
_tnl_render_stage
const struct tnl_pipeline_stage _tnl_render_stage
_tnl_render_tab_elts
tnl_render_func _tnl_render_tab_elts[]
Referenced by _tnl_CreateContext().
_tnl_render_tab_verts
tnl_render_func _tnl_render_tab_verts[]
Referenced by _tnl_CreateContext().
_tnl_texgen_stage
const struct tnl_pipeline_stage _tnl_texgen_stage
_tnl_texture_transform_stage
const struct tnl_pipeline_stage _tnl_texture_transform_stage
_tnl_vertex_program_stage
const struct tnl_pipeline_stage _tnl_vertex_program_stage
Public description of this pipeline stage.
_tnl_vertex_transform_stage
const struct tnl_pipeline_stage _tnl_vertex_transform_stage
_tnl_vp_pipeline
const struct tnl_pipeline_stage* _tnl_vp_pipeline[]
Referenced by _tnl_CreateContext().