Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_pipeline.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "t_context.h"
#include "t_pipeline.h"
#include "t_vp_build.h"
#include "t_vertex.h"
Macros
#define START_FAST_MATH(x) x = 0
START/END_FAST_MATH macros:
#define END_FAST_MATH(x) (void)(x)
Functions
void _tnl_install_pipeline (struct gl_context *ctx, const struct tnl_pipeline_stage **stages)
void _tnl_destroy_pipeline (struct gl_context *ctx)
static GLuint check_input_changes (struct gl_context *ctx)
static GLuint check_output_changes (struct gl_context *ctx)
void _tnl_run_pipeline (struct gl_context *ctx)
Variables
const struct tnl_pipeline_stage * _tnl_default_pipeline []
const struct tnl_pipeline_stage * _tnl_vp_pipeline []
Macro Definition Documentation
END_FAST_MATH
#define END_FAST_MATH (x) (void)(x)
Referenced by _tnl_run_pipeline().
START_FAST_MATH
#define START_FAST_MATH (x) x = 0
START/END_FAST_MATH macros:
START_FAST_MATH: Set x86 FPU to faster, 32-bit precision mode (and save original mode to a temporary). END_FAST_MATH: Restore x86 FPU to original mode.
Referenced by _tnl_run_pipeline().
Function Documentation
_tnl_destroy_pipeline()
void _tnl_destroy_pipeline (struct gl_context * ctx)
References tnl_pipeline_stage::destroy, GLuint, tnl_pipeline::nr_stages, TNLcontext::pipeline, tnl_pipeline::stages, and TNL_CONTEXT.
Referenced by _tnl_DestroyContext().
_tnl_install_pipeline()
void _tnl_install_pipeline (struct gl_context * ctx, const struct tnl_pipeline_stage ** stages)
References tnl_pipeline_stage::create, GLuint, MAX_PIPELINE_STAGES, tnl_pipeline::new_state, tnl_pipeline::nr_stages, TNLcontext::pipeline, tnl_pipeline::stages, and TNL_CONTEXT.
Referenced by _tnl_CreateContext().
_tnl_run_pipeline()
void _tnl_run_pipeline (struct gl_context * ctx)
References gl_vertex_program_state::_MaintainTnlProgram, _tnl_notify_pipeline_output_change(), _tnl_UpdateFixedFunctionProgram(), check_input_changes(), check_output_changes(), vertex_buffer::Count, END_FAST_MATH, GLuint, tnl_pipeline::input_changes, tnl_pipeline::new_state, tnl_pipeline::nr_stages, TNLcontext::pipeline, tnl_pipeline_stage::run, tnl_pipeline::stages, START_FAST_MATH, TNL_CONTEXT, tnl_pipeline_stage::validate, TNLcontext::vb, and gl_context::VertexProgram.
check_input_changes()
static GLuint check_input_changes (struct gl_context * ctx) static
References _TNL_LAST_MAT, vertex_buffer::AttribPtr, GLuint, tnl_pipeline::input_changes, tnl_pipeline::last_attrib_size, tnl_pipeline::last_attrib_stride, TNLcontext::pipeline, GLvector4f::size, GLvector4f::stride, TNL_CONTEXT, and TNLcontext::vb.
Referenced by _tnl_run_pipeline().
check_output_changes()
static GLuint check_output_changes (struct gl_context * ctx) static
References TNLcontext::Driver, GLuint, TNLcontext::pipeline, TNL_CONTEXT, and TNLcontext::vb.
Referenced by _tnl_run_pipeline().
Variable Documentation
_tnl_default_pipeline
const struct tnl_pipeline_stage* _tnl_default_pipeline[]
Initial value:
= {
   &_tnl_vertex_transform_stage,
   &_tnl_normal_transform_stage,
   &_tnl_lighting_stage,
   &_tnl_texgen_stage,
   &_tnl_texture_transform_stage,
   &_tnl_point_attenuation_stage,
   &_tnl_vertex_program_stage,
   &_tnl_fog_coordinate_stage,
   &_tnl_render_stage,
   NULL
}
Referenced by _tnl_CreateContext().
_tnl_vp_pipeline
const struct tnl_pipeline_stage* _tnl_vp_pipeline[]
Initial value:
= {
   &_tnl_vertex_program_stage,
   &_tnl_render_stage,
   NULL
}
Referenced by _tnl_CreateContext().