Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_vb_vertex.c File Reference
#include "main/glheader.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "math/m_xform.h"
#include "util/bitscan.h"
#include "t_context.h"
#include "t_pipeline.h"
Data Structures
struct vertex_stage_data
Macros
#define VERTEX_STAGE_DATA(stage) ((struct vertex_stage_data *)stage->privatePtr)
#define USER_CLIPTEST(NAME, SZ)
Functions
static void usercliptab (struct gl_context *, GLvector4f *, GLubyte *, GLubyte *, GLubyte *)
void tnl_clip_prepare (struct gl_context *ctx)
static GLboolean run_vertex_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static GLboolean init_vertex_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void dtr (struct tnl_pipeline_stage *stage)
Variables
const struct tnl_pipeline_stage _tnl_vertex_transform_stage
Macro Definition Documentation
USER_CLIPTEST
#define USER_CLIPTEST (NAME, SZ)
VERTEX_STAGE_DATA
#define VERTEX_STAGE_DATA (stage) ((struct vertex_stage_data *)stage->privatePtr)
Referenced by dtr(), and init_vertex_stage().
Function Documentation
dtr()
static void dtr (struct tnl_pipeline_stage * stage) static
References _mesa_align_free(), _mesa_vector4f_free(), vertex_stage_data::clip, vertex_stage_data::clipmask, vertex_stage_data::eye, init_vertex_stage(), tnl_pipeline_stage::privatePtr, vertex_stage_data::proj, tnl_pipeline_stage::run, and VERTEX_STAGE_DATA.
init_vertex_stage()
static GLboolean init_vertex_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References _mesa_align_malloc(), _mesa_vector4f_alloc(), vertex_stage_data::clip, vertex_stage_data::clipmask, GLvector4f::data, vertex_stage_data::eye, GLuint, tnl_pipeline_stage::privatePtr, vertex_stage_data::proj, vertex_buffer::Size, TNL_CONTEXT, and VERTEX_STAGE_DATA.
Referenced by dtr().
run_vertex_stage()
static GLboolean run_vertex_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, _mesa_clip_np_tab, _mesa_clip_tab, _mesa_vector4f_clean_elem(), gl_context::_ModelProjectMatrix, gl_context::_NeedEyeCoords, _TNL_ATTRIB_POS, vertex_stage_data::andmask, vertex_buffer::AttribPtr, vertex_stage_data::clip, CLIP_FRUSTUM_BITS, vertex_buffer::ClipAndMask, vertex_stage_data::clipmask, vertex_buffer::ClipMask, vertex_buffer::ClipOrMask, gl_transform_attrib::ClipPlanesEnabled, vertex_buffer::ClipPtr, vertex_buffer::Count, gl_transform_attrib::DepthClamp, vertex_stage_data::eye, vertex_buffer::EyePtr, MATRIX_IDENTITY, gl_context::ModelviewMatrixStack, vertex_buffer::NdcPtr, vertex_stage_data::ormask, tnl_pipeline_stage::privatePtr, vertex_stage_data::proj, GLvector4f::size, tnl_clip_prepare(), TNL_CONTEXT, gl_matrix_stack::Top, gl_context::Transform, TransformRaw, GLmatrix::type, usercliptab(), and gl_context::VertexProgram.
tnl_clip_prepare()
void tnl_clip_prepare (struct gl_context * ctx)
References gl_transform_attrib::DepthClamp, init_c_cliptest(), and gl_context::Transform.
Referenced by do_ndc_cliptest(), and run_vertex_stage().
usercliptab()
static void usercliptab (struct gl_context * , GLvector4f * , GLubyte * , GLubyte * , GLubyte *) static
Referenced by run_vertex_stage().
Variable Documentation
_tnl_vertex_transform_stage
const struct tnl_pipeline_stage _tnl_vertex_transform_stage
Initial value:
=
{
   "modelview/project/cliptest/divide",
   NULL,
   init_vertex_stage,
   dtr,
   NULL,
   run_vertex_stage
}