Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_vb_fog.c File Reference
#include "c99_math.h"
#include "main/glheader.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "math/m_xform.h"
#include "t_context.h"
#include "t_pipeline.h"
Data Structures
struct fog_stage_data
Macros
#define FOG_STAGE_DATA(stage) ((struct fog_stage_data *)stage->privatePtr)
#define FOG_EXP_TABLE_SIZE 256
#define FOG_MAX (10.0F)
#define EXP_FOG_MAX .0006595F
#define FOG_INCR (FOG_MAX/FOG_EXP_TABLE_SIZE)
#define NEG_EXP(result, narg)
Functions
static void init_static_data (void)
Initialize the exp_table[] lookup table for approximating exp().
static void compute_fog_blend_factors (struct gl_context *ctx, GLvector4f *out, const GLvector4f *in)
Compute per-vertex fog blend factors from fog coordinates by evaluating the GL_LINEAR, GL_EXP or GL_EXP2 fog function.
static GLboolean run_fog_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static GLboolean alloc_fog_data (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void free_fog_data (struct tnl_pipeline_stage *stage)
Variables
static GLfloat exp_table [FOG_EXP_TABLE_SIZE]
static GLfloat inited = 0
const struct tnl_pipeline_stage _tnl_fog_coordinate_stage
Macro Definition Documentation
EXP_FOG_MAX
#define EXP_FOG_MAX .0006595F
FOG_EXP_TABLE_SIZE
#define FOG_EXP_TABLE_SIZE 256
Referenced by init_static_data().
FOG_INCR
#define FOG_INCR (FOG_MAX/FOG_EXP_TABLE_SIZE)
Referenced by init_static_data().
FOG_MAX
#define FOG_MAX (10.0F)
FOG_STAGE_DATA
#define FOG_STAGE_DATA (stage) ((struct fog_stage_data *)stage->privatePtr)
Referenced by alloc_fog_data(), free_fog_data(), and run_fog_stage().
NEG_EXP
#define NEG_EXP (result, narg)
Value:
do {                                                                    \
   GLfloat f = (GLfloat) (narg * (1.0F / FOG_INCR));                    \
   GLint k = (GLint) f;                                                 \
   if (k > FOG_EXP_TABLE_SIZE-2)                                        \
      result = (GLfloat) EXP_FOG_MAX;                                   \
   else                                                                 \
      result = exp_table[k] + (f-k)*(exp_table[k+1]-exp_table[k]);      \
} while (0)
Referenced by compute_fog_blend_factors().
Function Documentation
alloc_fog_data()
static GLboolean alloc_fog_data (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References _mesa_vector4f_alloc(), FOG_STAGE_DATA, fog_stage_data::fogcoord, init_static_data(), inited, tnl_pipeline_stage::privatePtr, vertex_buffer::Size, TNL_CONTEXT, and TNLcontext::vb.
compute_fog_blend_factors()
static void compute_fog_blend_factors (struct gl_context * ctx, GLvector4f * out, const GLvector4f * in) static
Compute per-vertex fog blend factors from fog coordinates by evaluating the GL_LINEAR, GL_EXP or GL_EXP2 fog function.
Fog coordinates are distances from the eye (typically between the near and far clip plane distances). Note that fogcoords may be negative, if eye z is source absolute value must be taken earlier. Fog blend factors are in the range [0,1].
References _mesa_problem(), GLvector4f::count, GLvector4f::data, gl_fog_attrib::Density, gl_fog_attrib::End, F, gl_context::Fog, GLuint, gl_fog_attrib::Mode, NEG_EXP, GLvector4f::start, gl_fog_attrib::Start, GLvector4f::stride, and STRIDE_F.
Referenced by run_fog_stage().
free_fog_data()
static void free_fog_data (struct tnl_pipeline_stage * stage) static
References _mesa_vector4f_free(), FOG_STAGE_DATA, fog_stage_data::fogcoord, and tnl_pipeline_stage::privatePtr.
init_static_data()
static void init_static_data (void) static
Initialize the exp_table[] lookup table for approximating exp().
References exp_table, FOG_EXP_TABLE_SIZE, FOG_INCR, and inited.
Referenced by alloc_fog_data().
run_fog_stage()
static GLboolean run_fog_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, TNLcontext::_DoVertexFog, _mesa_dotprod_tab, _mesa_vector4f_clean_elem(), gl_context::_NeedEyeCoords, _TNL_ATTRIB_FOG, _TNL_ATTRIB_POS, vertex_buffer::AttribPtr, compute_fog_blend_factors(), GLvector4f::count, vertex_buffer::Count, GLvector4f::data, gl_fog_attrib::Enabled, vertex_buffer::EyePtr, gl_context::Fog, FOG_STAGE_DATA, fog_stage_data::fogcoord, gl_fog_attrib::FogCoordinateSource, GLuint, GLmatrix::m, gl_context::ModelviewMatrixStack, GLvector4f::size, GLvector4f::start, GLvector4f::stride, STRIDE_F, TNL_CONTEXT, gl_matrix_stack::Top, TNLcontext::vb, and gl_context::VertexProgram.
Variable Documentation
_tnl_fog_coordinate_stage
const struct tnl_pipeline_stage _tnl_fog_coordinate_stage
Initial value:
=
{
   "build fog coordinates",
   NULL,
   alloc_fog_data,
   free_fog_data,
   NULL,
   run_fog_stage
}
exp_table
GLfloat exp_table[FOG_EXP_TABLE_SIZE] static
Referenced by init_static_data().
inited
GLfloat inited = 0 static
Referenced by alloc_fog_data(), and init_static_data().