Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_vb_light.c File Reference
#include "c99_math.h"
#include "main/glheader.h"
#include "main/light.h"
#include "main/macros.h"
#include "main/imports.h"
#include "util/simple_list.h"
#include "main/mtypes.h"
#include "math/m_translate.h"
#include "util/bitscan.h"
#include "t_context.h"
#include "t_pipeline.h"
#include "tnl.h"
#include "t_vb_lighttmp.h"
Data Structures
struct material_cursor
Information for updating current material attributes from vertex color, for GL_COLOR_MATERIAL.
struct light_stage_data
Data private to this pipeline stage.
Macros
#define LIGHT_TWOSIDE 0x1
#define LIGHT_MATERIAL 0x2
#define MAX_LIGHT_FUNC 0x4
#define LIGHT_STAGE_DATA(stage) ((struct light_stage_data *)(stage->privatePtr))
#define TAG(x) x
#define IDX (0)
#define TAG(x) x##_twoside
#define IDX (LIGHT_TWOSIDE)
#define TAG(x) x##_material
#define IDX (LIGHT_MATERIAL)
#define TAG(x) x##_twoside_material
#define IDX (LIGHT_TWOSIDE|LIGHT_MATERIAL)
Typedefs
typedef void(* light_func) (struct gl_context *ctx, struct vertex_buffer *VB, struct tnl_pipeline_stage *stage, GLvector4f *input)
Functions
static void validate_shine_table (struct gl_context *ctx, GLuint side, GLfloat shininess)
void _tnl_validate_shine_tables (struct gl_context *ctx)
static void update_materials (struct gl_context *ctx, struct light_stage_data *store)
In the case of colormaterial, the effected material attributes should already have been bound to point to the incoming color data, prior to running the pipeline.
static GLuint prepare_materials (struct gl_context *ctx, struct vertex_buffer *VB, struct light_stage_data *store)
Prepare things prior to running the lighting stage.
static GLfloat lookup_shininess (const struct gl_context *ctx, GLuint face, GLfloat dp)
static void init_lighting_tables (void)
static GLboolean run_lighting (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void validate_lighting (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static GLboolean init_lighting (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void dtr (struct tnl_pipeline_stage *stage)
Variables
static light_func _tnl_light_tab [MAX_LIGHT_FUNC]
static light_func _tnl_light_fast_tab [MAX_LIGHT_FUNC]
static light_func _tnl_light_fast_single_tab [MAX_LIGHT_FUNC]
static light_func _tnl_light_spec_tab [MAX_LIGHT_FUNC]
const struct tnl_pipeline_stage _tnl_lighting_stage
Macro Definition Documentation
IDX [1/4]
#define IDX (0)
Referenced by init_light_tab(), light_fast_rgba(), light_fast_rgba_single(), light_rgba(), and light_rgba_spec().
IDX [2/4]
#define IDX (LIGHT_TWOSIDE)
IDX [3/4]
#define IDX (LIGHT_MATERIAL)
IDX [4/4]
#define IDX (LIGHT_TWOSIDE|LIGHT_MATERIAL)
LIGHT_MATERIAL
#define LIGHT_MATERIAL 0x2
Referenced by light_fast_rgba(), and run_lighting().
LIGHT_STAGE_DATA
#define LIGHT_STAGE_DATA (stage) ((struct light_stage_data *)(stage->privatePtr))
Referenced by dtr(), init_lighting(), light_fast_rgba(), light_fast_rgba_single(), light_rgba(), light_rgba_spec(), run_lighting(), and validate_lighting().
LIGHT_TWOSIDE
#define LIGHT_TWOSIDE 0x1
Referenced by light_fast_rgba(), light_fast_rgba_single(), light_rgba(), light_rgba_spec(), and run_lighting().
MAX_LIGHT_FUNC
#define MAX_LIGHT_FUNC 0x4
TAG [1/4]
#define TAG (x) x
Referenced by init_light_tab().
TAG [2/4]
#define TAG (x) x##_twoside
TAG [3/4]
#define TAG (x) x##_material
TAG [4/4]
#define TAG (x) x##_twoside_material
Typedef Documentation
light_func
typedef void(* light_func) (struct gl_context *ctx, struct vertex_buffer *VB, struct tnl_pipeline_stage *stage, GLvector4f *input)
Function Documentation
_tnl_validate_shine_tables()
void _tnl_validate_shine_tables (struct gl_context * ctx)
References TNLcontext::_ShineTable, gl_material::Attrib, gl_context::Light, MAT_ATTRIB_BACK_SHININESS, MAT_ATTRIB_FRONT_SHININESS, gl_light_attrib::Material, tnl_shine_tab::shininess, TNL_CONTEXT, and validate_shine_table().
Referenced by _tnl_CreateContext(), prepare_materials(), and update_materials().
dtr()
static void dtr (struct tnl_pipeline_stage * stage) static
References _mesa_vector4f_free(), light_stage_data::Input, LIGHT_STAGE_DATA, light_stage_data::LitColor, light_stage_data::LitSecondary, and tnl_pipeline_stage::privatePtr.
init_lighting()
static GLboolean init_lighting (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References _mesa_vector4f_alloc(), GLuint, init_lighting_tables(), light_stage_data::Input, LIGHT_STAGE_DATA, light_stage_data::LitColor, light_stage_data::LitSecondary, tnl_pipeline_stage::privatePtr, GLvector4f::size, material_cursor::size, vertex_buffer::Size, TNL_CONTEXT, and TNLcontext::vb.
init_lighting_tables()
static void init_lighting_tables (void) static
References init_light_tab().
Referenced by init_lighting().
lookup_shininess()
static GLfloat lookup_shininess (const struct gl_context * ctx, GLuint face, GLfloat dp) inline static
References TNLcontext::_ShineTable, SHINE_TABLE_SIZE, tnl_shine_tab::shininess, tnl_shine_tab::tab, and TNL_CONTEXT.
Referenced by light_fast_rgba(), light_fast_rgba_single(), light_rgba(), and light_rgba_spec().
prepare_materials()
static GLuint prepare_materials (struct gl_context * ctx, struct vertex_buffer * VB, struct light_stage_data * store) static
Prepare things prior to running the lighting stage.
Return number of material attributes which will track vertex color.
References gl_light_attrib::_ColorMaterialBitmask, _mesa_update_material(), _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_MAT_FRONT_AMBIENT, _TNL_FIRST_MAT, _TNL_LAST_MAT, _tnl_validate_shine_tables(), gl_material::Attrib, vertex_buffer::AttribPtr, gl_light_attrib::ColorMaterialEnabled, material_cursor::current, GLuint, gl_context::Light, light_stage_data::mat, light_stage_data::mat_bitmask, light_stage_data::mat_count, gl_light_attrib::Material, material_cursor::ptr, GLvector4f::size, material_cursor::size, GLvector4f::start, GLvector4f::stride, and material_cursor::stride.
Referenced by run_lighting().
run_lighting()
static GLboolean run_lighting (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, _math_trans_4f(), _mesa_vector4f_clean_elem(), gl_context::_NeedEyeCoords, _TNL_ATTRIB_POS, vertex_buffer::AttribPtr, vertex_buffer::Count, GLvector4f::data, gl_light_attrib::Enabled, vertex_buffer::EyePtr, GLuint, light_stage_data::Input, gl_context::Light, light_stage_data::light_func_tab, LIGHT_MATERIAL, LIGHT_STAGE_DATA, LIGHT_TWOSIDE, gl_light_attrib::Model, prepare_materials(), GLvector4f::size, GLvector4f::stride, TNL_CONTEXT, gl_lightmodel::TwoSide, TNLcontext::vb, and gl_context::VertexProgram.
update_materials()
static void update_materials (struct gl_context * ctx, struct light_stage_data * store) static
In the case of colormaterial, the effected material attributes should already have been bound to point to the incoming color data, prior to running the pipeline.
This function copies the vertex's color to the material attributes which are tracking glColor. It's called per-vertex in the lighting loop.
References _mesa_update_material(), _tnl_validate_shine_tables(), COPY_CLEAN_4V, material_cursor::current, GLuint, light_stage_data::mat, light_stage_data::mat_bitmask, light_stage_data::mat_count, material_cursor::ptr, material_cursor::size, material_cursor::stride, and STRIDE_F.
Referenced by light_fast_rgba(), light_fast_rgba_single(), light_rgba(), and light_rgba_spec().
validate_lighting()
static void validate_lighting (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, gl_light_attrib::_EnabledLights, gl_light_attrib::_NeedVertices, _tnl_light_fast_single_tab, _tnl_light_fast_tab, _tnl_light_spec_tab, _tnl_light_tab, gl_lightmodel::ColorControl, gl_light_attrib::Enabled, gl_context::Light, LIGHT_STAGE_DATA, gl_light_attrib::Model, TNL_CONTEXT, and gl_context::VertexProgram.
validate_shine_table()
static void validate_shine_table (struct gl_context * ctx, GLuint side, GLfloat shininess) static
References TNLcontext::_ShineTable, TNLcontext::_ShineTabList, F, tnl_shine_tab::refcount, SHINE_TABLE_SIZE, tnl_shine_tab::shininess, tnl_shine_tab::tab, TNL_CONTEXT, and x.
Referenced by _tnl_validate_shine_tables().
Variable Documentation
_tnl_light_fast_single_tab
light_func _tnl_light_fast_single_tab[MAX_LIGHT_FUNC] static
Referenced by init_light_tab(), and validate_lighting().
_tnl_light_fast_tab
light_func _tnl_light_fast_tab[MAX_LIGHT_FUNC] static
Referenced by init_light_tab(), and validate_lighting().
_tnl_light_spec_tab
light_func _tnl_light_spec_tab[MAX_LIGHT_FUNC] static
Referenced by init_light_tab(), and validate_lighting().
_tnl_light_tab
light_func _tnl_light_tab[MAX_LIGHT_FUNC] static
Referenced by init_light_tab(), and validate_lighting().
_tnl_lighting_stage
const struct tnl_pipeline_stage _tnl_lighting_stage
Initial value:
=
{
   "lighting",
   NULL,
   init_lighting,
   dtr,
   validate_lighting,
   run_lighting
}