Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_vb_normals.c File Reference
#include "main/glheader.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "math/m_xform.h"
#include "t_context.h"
#include "t_pipeline.h"
Data Structures
struct normal_stage_data
Macros
#define NORMAL_STAGE_DATA(stage) ((struct normal_stage_data *)stage->privatePtr)
Functions
static GLboolean run_normal_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void validate_normal_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
Examine current GL state and set the store->NormalTransform pointer to point to the appropriate normal transformation routine.
static GLboolean alloc_normal_data (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
Allocate stage's private data (storage for transformed normals).
static void free_normal_data (struct tnl_pipeline_stage *stage)
Free stage's private data.
Variables
const struct tnl_pipeline_stage _tnl_normal_transform_stage
Macro Definition Documentation
NORMAL_STAGE_DATA
#define NORMAL_STAGE_DATA (stage) ((struct normal_stage_data *)stage->privatePtr)
Referenced by alloc_normal_data(), free_normal_data(), run_normal_stage(), and validate_normal_stage().
Function Documentation
alloc_normal_data()
static GLboolean alloc_normal_data (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
Allocate stage's private data (storage for transformed normals).
References _mesa_vector4f_alloc(), normal_stage_data::normal, NORMAL_STAGE_DATA, tnl_pipeline_stage::privatePtr, vertex_buffer::Size, TNL_CONTEXT, and TNLcontext::vb.
free_normal_data()
static void free_normal_data (struct tnl_pipeline_stage * stage) static
Free stage's private data.
References _mesa_vector4f_free(), normal_stage_data::normal, NORMAL_STAGE_DATA, and tnl_pipeline_stage::privatePtr.
run_normal_stage()
static GLboolean run_normal_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References _math_matrix_is_general_scale(), gl_context::_ModelViewInvScale, _TNL_ATTRIB_NORMAL, vertex_buffer::AttribPtr, GLvector4f::count, gl_context::ModelviewMatrixStack, normal_stage_data::normal, NORMAL_STAGE_DATA, vertex_buffer::NormalLengthPtr, normal_stage_data::NormalTransform, GLvector4f::stride, TNL_CONTEXT, and gl_matrix_stack::Top.
validate_normal_stage()
static void validate_normal_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
Examine current GL state and set the store->NormalTransform pointer to point to the appropriate normal transformation routine.
References gl_vertex_program_state::_Current, gl_texture_attrib::_GenFlags, _math_matrix_has_rotation(), _mesa_normal_tab, gl_context::_ModelViewInvScale, gl_context::_NeedEyeCoords, gl_light_attrib::Enabled, GLuint, gl_context::Light, gl_context::ModelviewMatrixStack, NORM_NORMALIZE, NORM_RESCALE, NORM_TRANSFORM, NORM_TRANSFORM_NO_ROT, NORMAL_STAGE_DATA, gl_transform_attrib::Normalize, normal_stage_data::NormalTransform, gl_transform_attrib::RescaleNormals, TEXGEN_NEED_NORMALS, gl_context::Texture, gl_matrix_stack::Top, gl_context::Transform, and gl_context::VertexProgram.
Variable Documentation
_tnl_normal_transform_stage
const struct tnl_pipeline_stage _tnl_normal_transform_stage
Initial value:
=
{
   "normal transform",
   NULL,
   alloc_normal_data,
   free_normal_data,
   validate_normal_stage,
   run_normal_stage
}