Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_vb_texgen.c File Reference
#include "main/glheader.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "math/m_xform.h"
#include "t_context.h"
#include "t_pipeline.h"
Data Structures
struct texgen_stage_data
Macros
#define TEXGEN_STAGE_DATA(stage) ((struct texgen_stage_data *)stage->privatePtr)
#define VEC_SIZE_FLAGS (VEC_SIZE_1|VEC_SIZE_2|VEC_SIZE_3|VEC_SIZE_4)
#define TEXGEN_NEED_M (TEXGEN_SPHERE_MAP)
#define TEXGEN_NEED_F
Typedefs
typedef void(* texgen_func) (struct gl_context *ctx, struct texgen_stage_data *store, GLuint unit)
typedef void(* build_m_func) (GLfloat f[][3], GLfloat m[], const GLvector4f *normal, const GLvector4f *eye)
typedef void(* build_f_func) (GLfloat *f, GLuint fstride, const GLvector4f *normal_vec, const GLvector4f *eye)
Functions
static void build_m3 (GLfloat f[][3], GLfloat m[], const GLvector4f *normal, const GLvector4f *eye)
static void build_m2 (GLfloat f[][3], GLfloat m[], const GLvector4f *normal, const GLvector4f *eye)
static void build_f3 (GLfloat *f, GLuint fstride, const GLvector4f *normal, const GLvector4f *eye)
static void build_f2 (GLfloat *f, GLuint fstride, const GLvector4f *normal, const GLvector4f *eye)
static void texgen_reflection_map_nv (struct gl_context *ctx, struct texgen_stage_data *store, GLuint unit)
static void texgen_normal_map_nv (struct gl_context *ctx, struct texgen_stage_data *store, GLuint unit)
static void texgen_sphere_map (struct gl_context *ctx, struct texgen_stage_data *store, GLuint unit)
static void texgen (struct gl_context *ctx, struct texgen_stage_data *store, GLuint unit)
static GLboolean run_texgen_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void validate_texgen_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static GLboolean alloc_texgen_data (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
static void free_texgen_data (struct tnl_pipeline_stage *stage)
Variables
static GLuint all_bits [5]
static build_m_func build_m_tab [5]
static build_f_func build_f_tab [5]
const struct tnl_pipeline_stage _tnl_texgen_stage
Macro Definition Documentation
TEXGEN_NEED_F
#define TEXGEN_NEED_F
Value:
(TEXGEN_SPHERE_MAP        | \
                                  TEXGEN_REFLECTION_MAP_NV)
Referenced by texgen().
TEXGEN_NEED_M
#define TEXGEN_NEED_M (TEXGEN_SPHERE_MAP)
Referenced by texgen().
TEXGEN_STAGE_DATA
#define TEXGEN_STAGE_DATA (stage) ((struct texgen_stage_data *)stage->privatePtr)
Referenced by alloc_texgen_data(), free_texgen_data(), run_texgen_stage(), and validate_texgen_stage().
VEC_SIZE_FLAGS
#define VEC_SIZE_FLAGS (VEC_SIZE_1|VEC_SIZE_2|VEC_SIZE_3|VEC_SIZE_4)
Referenced by texgen(), texgen_normal_map_nv(), texgen_reflection_map_nv(), and texgen_sphere_map().
Typedef Documentation
build_f_func
typedef void(* build_f_func) (GLfloat *f, GLuint fstride, const GLvector4f *normal_vec, const GLvector4f *eye)
build_m_func
typedef void(* build_m_func) (GLfloat f[][3], GLfloat m[], const GLvector4f *normal, const GLvector4f *eye)
texgen_func
typedef void(* texgen_func) (struct gl_context *ctx, struct texgen_stage_data *store, GLuint unit)
Function Documentation
alloc_texgen_data()
static GLboolean alloc_texgen_data (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References _mesa_vector4f_alloc(), gl_context::Const, GLuint, gl_constants::MaxTextureCoordUnits, tnl_pipeline_stage::privatePtr, vertex_buffer::Size, texgen_stage_data::texcoord, TEXGEN_STAGE_DATA, texgen_stage_data::tmp_f, texgen_stage_data::tmp_m, and TNL_CONTEXT.
build_f2()
static void build_f2 (GLfloat * f, GLuint fstride, const GLvector4f * normal, const GLvector4f * eye) static
References COPY_2V, GLvector4f::count, GLuint, GLvector4f::start, GLvector4f::stride, and STRIDE_F.
build_f3()
static void build_f3 (GLfloat * f, GLuint fstride, const GLvector4f * normal, const GLvector4f * eye) static
References COPY_3V, GLvector4f::count, GLuint, GLvector4f::start, GLvector4f::stride, and STRIDE_F.
build_m2()
static void build_m2 (GLfloat f[][3], GLfloat m[], const GLvector4f * normal, const GLvector4f * eye) static
References COPY_2V, GLvector4f::count, F, GLuint, GLvector4f::start, GLvector4f::stride, and STRIDE_F.
build_m3()
static void build_m3 (GLfloat f[][3], GLfloat m[], const GLvector4f * normal, const GLvector4f * eye) static
References COPY_3V, GLvector4f::count, F, for(), GLuint, GLvector4f::start, GLvector4f::stride, and STRIDE_F.
free_texgen_data()
static void free_texgen_data (struct tnl_pipeline_stage * stage) static
References _mesa_vector4f_free(), GLvector4f::data, GLuint, MAX_TEXTURE_COORD_UNITS, tnl_pipeline_stage::privatePtr, texgen_stage_data::texcoord, TEXGEN_STAGE_DATA, texgen_stage_data::tmp_f, and texgen_stage_data::tmp_m.
run_texgen_stage()
static GLboolean run_texgen_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, gl_texture_attrib::_TexGenEnabled, vertex_buffer::AttribPtr, gl_context::Const, GLuint, gl_constants::MaxTextureCoordUnits, TEXGEN_STAGE_DATA, gl_texture_unit::TexGenEnabled, texgen_stage_data::TexgenFunc, gl_context::Texture, TNL_CONTEXT, gl_texture_attrib::Unit, and gl_context::VertexProgram.
texgen()
static void texgen (struct gl_context * ctx, struct texgen_stage_data * store, GLuint unit) static
References gl_texture_unit::_GenFlags, _mesa_copy_tab, _mesa_dotprod_tab, _mesa_problem(), _TNL_ATTRIB_NORMAL, _TNL_ATTRIB_POS, all_bits, vertex_buffer::AttribPtr, build_f_tab, build_m_tab, GLvector4f::count, vertex_buffer::Count, GLvector4f::data, gl_texgen::EyePlane, vertex_buffer::EyePtr, F, GLvector4f::flags, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GLuint, gl_texgen::Mode, gl_texgen::ObjectPlane, Q_BIT, R_BIT, S_BIT, GLvector4f::size, GLvector4f::start, GLvector4f::stride, STRIDE_F, T_BIT, texgen_stage_data::texcoord, TEXGEN_NEED_F, TEXGEN_NEED_M, gl_texture_unit::TexGenEnabled, texgen_stage_data::TexgenSize, gl_context::Texture, texgen_stage_data::tmp_f, texgen_stage_data::tmp_m, TNL_CONTEXT, gl_texture_attrib::Unit, TNLcontext::vb, and VEC_SIZE_FLAGS.
Referenced by validate_texgen_stage().
texgen_normal_map_nv()
static void texgen_normal_map_nv (struct gl_context * ctx, struct texgen_stage_data * store, GLuint unit) static
References _mesa_copy_tab, _TNL_ATTRIB_NORMAL, vertex_buffer::AttribPtr, GLvector4f::count, vertex_buffer::Count, GLvector4f::flags, for(), GLuint, GLvector4f::size, GLvector4f::start, GLvector4f::stride, STRIDE_F, texgen_stage_data::texcoord, TNL_CONTEXT, VEC_SIZE_3, and VEC_SIZE_FLAGS.
Referenced by validate_texgen_stage().
texgen_reflection_map_nv()
static void texgen_reflection_map_nv (struct gl_context * ctx, struct texgen_stage_data * store, GLuint unit) static
References _mesa_copy_tab, _TNL_ATTRIB_NORMAL, vertex_buffer::AttribPtr, build_f_tab, GLvector4f::count, vertex_buffer::Count, vertex_buffer::EyePtr, GLvector4f::flags, GLvector4f::size, GLvector4f::start, GLvector4f::stride, texgen_stage_data::texcoord, TNL_CONTEXT, VEC_SIZE_3, and VEC_SIZE_FLAGS.
Referenced by validate_texgen_stage().
texgen_sphere_map()
static void texgen_sphere_map (struct gl_context * ctx, struct texgen_stage_data * store, GLuint unit) static
References _mesa_copy_tab, _TNL_ATTRIB_NORMAL, all_bits, vertex_buffer::AttribPtr, build_m_tab, GLvector4f::count, vertex_buffer::Count, vertex_buffer::EyePtr, GLvector4f::flags, GLuint, GLvector4f::size, GLvector4f::start, texgen_stage_data::texcoord, texgen_stage_data::tmp_f, texgen_stage_data::tmp_m, TNL_CONTEXT, VEC_SIZE_2, and VEC_SIZE_FLAGS.
Referenced by validate_texgen_stage().
validate_texgen_stage()
static void validate_texgen_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, gl_texture_unit::_GenFlags, gl_texture_attrib::_TexGenEnabled, gl_context::Const, GLuint, gl_constants::MaxTextureCoordUnits, Q_BIT, R_BIT, S_BIT, T_BIT, texgen(), TEXGEN_NORMAL_MAP_NV, texgen_normal_map_nv(), TEXGEN_REFLECTION_MAP_NV, texgen_reflection_map_nv(), TEXGEN_SPHERE_MAP, texgen_sphere_map(), TEXGEN_STAGE_DATA, gl_texture_unit::TexGenEnabled, texgen_stage_data::TexgenFunc, texgen_stage_data::TexgenSize, gl_context::Texture, gl_texture_attrib::Unit, and gl_context::VertexProgram.
Variable Documentation
_tnl_texgen_stage
const struct tnl_pipeline_stage _tnl_texgen_stage
Initial value:
=
{
   "texgen",
   NULL,
   alloc_texgen_data,
   free_texgen_data,
   validate_texgen_stage,
   run_texgen_stage
}
all_bits
GLuint all_bits[5] static
Initial value:
= {
   0,
   VEC_SIZE_1,
   VEC_SIZE_2,
   VEC_SIZE_3,
   VEC_SIZE_4,
}
Referenced by texgen(), and texgen_sphere_map().
build_f_tab
build_f_func build_f_tab[5] static
Initial value:
= {
   NULL,
   NULL,
   build_f2,
   build_f3,
   build_f3
}
Referenced by texgen(), and texgen_reflection_map_nv().
build_m_tab
build_m_func build_m_tab[5] static
Initial value:
= {
   NULL,
   NULL,
   build_m2,
   build_m3,
   build_m3
}
Referenced by texgen(), and texgen_sphere_map().