Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_vb_lighttmp.h File Reference
Macros
#define NR_SIDES 1
Functions
static void TAG() light_rgba_spec (struct gl_context *ctx, struct vertex_buffer *VB, struct tnl_pipeline_stage *stage, GLvector4f *input)
static void TAG() light_rgba (struct gl_context *ctx, struct vertex_buffer *VB, struct tnl_pipeline_stage *stage, GLvector4f *input)
static void TAG() light_fast_rgba_single (struct gl_context *ctx, struct vertex_buffer *VB, struct tnl_pipeline_stage *stage, GLvector4f *input)
static void TAG() light_fast_rgba (struct gl_context *ctx, struct vertex_buffer *VB, struct tnl_pipeline_stage *stage, GLvector4f *input)
static void TAG() init_light_tab (void)
Macro Definition Documentation
NR_SIDES
#define NR_SIDES 1
Function Documentation
init_light_tab()
static void TAG() init_light_tab (void) static
References _tnl_light_fast_single_tab, _tnl_light_fast_tab, _tnl_light_spec_tab, _tnl_light_tab, IDX, light_fast_rgba(), light_fast_rgba_single(), light_rgba(), light_rgba_spec(), TAG, and void.
Referenced by init_lighting_tables().
light_fast_rgba()
static void TAG() light_fast_rgba (struct gl_context * ctx, struct vertex_buffer * VB, struct tnl_pipeline_stage * stage, GLvector4f * input) static
References gl_light_attrib::_BaseColor, gl_light_attrib::_EnabledLights, gl_light::_h_inf_norm, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_NORMAL, gl_light::_VP_inf_norm, ACC_3V, ACC_SCALE_SCALAR_3V, gl_material::Attrib, vertex_buffer::AttribPtr, vertex_buffer::BackfaceColorPtr, COPY_3V, GLvector4f::count, vertex_buffer::Count, GLvector4f::data, F, GLuint, IDX, gl_light_attrib::Light, gl_context::Light, LIGHT_MATERIAL, LIGHT_STAGE_DATA, LIGHT_TWOSIDE, light_stage_data::LitColor, lookup_shininess(), MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_FRONT_DIFFUSE, gl_light_attrib::Material, GLvector4f::stride, STRIDE_F, update_materials(), and void.
Referenced by init_light_tab().
light_fast_rgba_single()
static void TAG() light_fast_rgba_single (struct gl_context * ctx, struct vertex_buffer * VB, struct tnl_pipeline_stage * stage, GLvector4f * input) static
References gl_light_attrib::_BaseColor, gl_light_attrib::_EnabledLights, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_NORMAL, ACC_3V, ACC_SCALE_SCALAR_3V, gl_material::Attrib, vertex_buffer::AttribPtr, vertex_buffer::BackfaceColorPtr, COPY_3V, GLvector4f::count, vertex_buffer::Count, GLvector4f::data, F, GLuint, IDX, gl_context::Light, gl_light_attrib::Light, LIGHT_STAGE_DATA, LIGHT_TWOSIDE, light_stage_data::LitColor, lookup_shininess(), MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_FRONT_DIFFUSE, gl_light_attrib::Material, GLvector4f::stride, STRIDE_F, update_materials(), and void.
Referenced by init_light_tab().
light_rgba()
static void TAG() light_rgba (struct gl_context * ctx, struct vertex_buffer * VB, struct tnl_pipeline_stage * stage, GLvector4f * input) static
References gl_light_attrib::_BaseColor, gl_light::_CosCutoff, gl_light_attrib::_EnabledLights, gl_context::_EyeZDir, gl_light::_Flags, gl_light::_h_inf_norm, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, gl_light::_NormSpotDirection, gl_light::_Position, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_NORMAL, gl_light::_VP_inf_norm, gl_light::_VP_inf_spot_attenuation, ACC_3V, ACC_SCALE_SCALAR_3V, gl_material::Attrib, vertex_buffer::AttribPtr, vertex_buffer::BackfaceColorPtr, gl_light::ConstantAttenuation, COPY_3V, vertex_buffer::Count, GLvector4f::data, F, GLuint, IDX, gl_context::Light, gl_light_attrib::Light, LIGHT_POSITIONAL, LIGHT_SPOT, LIGHT_STAGE_DATA, LIGHT_TWOSIDE, gl_light::LinearAttenuation, light_stage_data::LitColor, gl_lightmodel::LocalViewer, lookup_shininess(), MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_FRONT_DIFFUSE, gl_light_attrib::Material, gl_light_attrib::Model, gl_light::QuadraticAttenuation, SELF_SCALE_SCALAR_3V, gl_light::SpotExponent, GLvector4f::stride, STRIDE_F, SUB_3V, and update_materials().
Referenced by init_light_tab().
light_rgba_spec()
static void TAG() light_rgba_spec (struct gl_context * ctx, struct vertex_buffer * VB, struct tnl_pipeline_stage * stage, GLvector4f * input) static
References gl_light_attrib::_BaseColor, gl_light::_CosCutoff, gl_light_attrib::_EnabledLights, gl_context::_EyeZDir, gl_light::_Flags, gl_light::_h_inf_norm, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, gl_light::_NormSpotDirection, gl_light::_Position, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_COLOR1, _TNL_ATTRIB_NORMAL, gl_light::_VP_inf_norm, gl_light::_VP_inf_spot_attenuation, ACC_3V, ACC_SCALE_SCALAR_3V, gl_material::Attrib, vertex_buffer::AttribPtr, vertex_buffer::BackfaceColorPtr, vertex_buffer::BackfaceSecondaryColorPtr, gl_light::ConstantAttenuation, COPY_3V, vertex_buffer::Count, GLvector4f::data, F, GLuint, IDX, gl_context::Light, gl_light_attrib::Light, LIGHT_POSITIONAL, LIGHT_SPOT, LIGHT_STAGE_DATA, LIGHT_TWOSIDE, gl_light::LinearAttenuation, light_stage_data::LitColor, light_stage_data::LitSecondary, gl_lightmodel::LocalViewer, lookup_shininess(), MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_FRONT_DIFFUSE, gl_light_attrib::Material, gl_light_attrib::Model, gl_light::QuadraticAttenuation, SELF_SCALE_SCALAR_3V, gl_light::SpotExponent, GLvector4f::stride, STRIDE_F, SUB_3V, update_materials(), and ZERO_3V.
Referenced by init_light_tab().