Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_binding_tables.c File Reference
State atoms which upload the "binding table" for each shader stage.
#include "main/mtypes.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
Functions
void brw_upload_binding_table (struct brw_context *brw, uint32_t packet_name, const struct brw_stage_prog_data *prog_data, struct brw_stage_state *stage_state)
Upload a shader stage's binding table as indirect state.
const struct brw_tracked_state brw_vs_binding_table
const struct brw_tracked_state brw_wm_binding_table
const struct brw_tracked_state brw_tcs_binding_table
const struct brw_tracked_state brw_tes_binding_table
const struct brw_tracked_state brw_gs_binding_table
static void brw_vs_upload_binding_table (struct brw_context *brw)
State atoms which upload the binding table for a particular shader stage.
static void brw_upload_wm_binding_table (struct brw_context *brw)
Upload the PS binding table.
static void brw_tcs_upload_binding_table (struct brw_context *brw)
Upload the TCS binding table (if tessellation stages are active).
static void brw_tes_upload_binding_table (struct brw_context *brw)
Upload the TES binding table (if TES is active).
static void brw_gs_upload_binding_table (struct brw_context *brw)
Upload the GS binding table (if GS is active).
const struct brw_tracked_state brw_binding_table_pointers
const struct brw_tracked_state gen6_binding_table_pointers
static void gen4_upload_binding_table_pointers (struct brw_context *brw)
State atoms which emit 3DSTATE packets to update the binding table pointers.
static void gen6_upload_binding_table_pointers (struct brw_context *brw)
(Sandybridge Only) Upload the binding table pointers for all shader stages.
Detailed Description
State atoms which upload the "binding table" for each shader stage.
Binding tables map a numeric "surface index" to the SURFACE_STATE structure for a currently bound surface. This allows SEND messages (such as sampler or data port messages) to refer to a particular surface by number, rather than by pointer.
The binding table is stored as a (sparse) array of SURFACE_STATE entries; surface indexes are simply indexes into the array. The ordering of the entries is entirely left up to software; see the SURF_INDEX_* macros in brw_context.h to see our current layout.
Function Documentation
brw_gs_upload_binding_table()
static void brw_gs_upload_binding_table (struct brw_context * brw) static
Upload the GS binding table (if GS is active).
References _3DSTATE_BINDING_TABLE_POINTERS_GS, brw_context::base, brw_upload_binding_table(), brw_context::geometry_program, brw_context::gs, and brw_stage_state::prog_data.
brw_tcs_upload_binding_table()
static void brw_tcs_upload_binding_table (struct brw_context * brw) static
Upload the TCS binding table (if tessellation stages are active).
References _3DSTATE_BINDING_TABLE_POINTERS_HS, brw_context::base, brw_upload_binding_table(), brw_stage_state::prog_data, brw_context::tcs, and brw_context::tess_eval_program.
brw_tes_upload_binding_table()
static void brw_tes_upload_binding_table (struct brw_context * brw) static
Upload the TES binding table (if TES is active).
References _3DSTATE_BINDING_TABLE_POINTERS_DS, brw_context::base, brw_upload_binding_table(), brw_stage_state::prog_data, brw_context::tes, and brw_context::tess_eval_program.
brw_upload_binding_table()
void brw_upload_binding_table (struct brw_context * brw, uint32_t packet_name, const struct brw_stage_prog_data * prog_data, struct brw_stage_state * stage_state)
Upload a shader stage's binding table as indirect state.
This copies brw_stage_state::surf_offset[] into the indirect state section of the batchbuffer (allocated by brw_state_batch()).
References ADVANCE_BATCH, BEGIN_BATCH, brw_stage_state::bind_bo_offset, brw_context::bo, brw_emit_buffer_surface_state(), BRW_NEW_BINDING_TABLE_POINTERS, brw_state_batch(), brw_context::ctx, brw_context::gen, gl_context::NewDriverState, OUT_BATCH, brw_context::shader_time, and brw_stage_state::surf_offset.
Referenced by brw_gs_upload_binding_table(), brw_state_dirty(), brw_tcs_upload_binding_table(), brw_tes_upload_binding_table(), brw_upload_wm_binding_table(), and brw_vs_upload_binding_table().
brw_upload_wm_binding_table()
static void brw_upload_wm_binding_table (struct brw_context * brw) static
Upload the PS binding table.
References _3DSTATE_BINDING_TABLE_POINTERS_PS, brw_context::base, brw_upload_binding_table(), brw_stage_state::prog_data, and brw_context::wm.
brw_vs_upload_binding_table()
static void brw_vs_upload_binding_table (struct brw_context * brw) static
State atoms which upload the binding table for a particular shader stage.
Upload the VS binding table.
References _3DSTATE_BINDING_TABLE_POINTERS_VS, brw_context::base, brw_upload_binding_table(), brw_stage_state::prog_data, and brw_context::vs.
gen4_upload_binding_table_pointers()
static void gen4_upload_binding_table_pointers (struct brw_context * brw) static
State atoms which emit 3DSTATE packets to update the binding table pointers.
(Gen4-5) Upload the binding table pointers for all shader stages.
The binding table pointers are relative to the surface state base address, which points at the batchbuffer containing the streamed batch state.
References _3DSTATE_BINDING_TABLE_POINTERS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_stage_state::bind_bo_offset, OUT_BATCH, brw_context::vs, and brw_context::wm.
gen6_upload_binding_table_pointers()
static void gen6_upload_binding_table_pointers (struct brw_context * brw) static
(Sandybridge Only) Upload the binding table pointers for all shader stages.
The binding table pointers are relative to the surface state base address, which points at the batchbuffer containing the streamed batch state.
References _3DSTATE_BINDING_TABLE_POINTERS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_stage_state::bind_bo_offset, brw_context::bind_bo_offset, brw_context::ff_gs, GEN6_BINDING_TABLE_MODIFY_GS, GEN6_BINDING_TABLE_MODIFY_PS, GEN6_BINDING_TABLE_MODIFY_VS, brw_context::gs, OUT_BATCH, brw_context::prog_active, brw_context::vs, and brw_context::wm.
Variable Documentation
brw_binding_table_pointers
const struct brw_tracked_state brw_binding_table_pointers
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_BINDING_TABLE_POINTERS |
             BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = gen4_upload_binding_table_pointers,
}
brw_gs_binding_table
const struct brw_tracked_state brw_gs_binding_table
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GS_CONSTBUF |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_SURFACES,
   },
   .emit = brw_gs_upload_binding_table,
}
brw_tcs_binding_table
const struct brw_tracked_state brw_tcs_binding_table
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_DEFAULT_TESS_LEVELS |
             BRW_NEW_SURFACES |
             BRW_NEW_TCS_CONSTBUF |
             BRW_NEW_TCS_PROG_DATA,
   },
   .emit = brw_tcs_upload_binding_table,
}
brw_tes_binding_table
const struct brw_tracked_state brw_tes_binding_table
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_SURFACES |
             BRW_NEW_TES_CONSTBUF |
             BRW_NEW_TES_PROG_DATA,
   },
   .emit = brw_tes_upload_binding_table,
}
brw_vs_binding_table
const struct brw_tracked_state brw_vs_binding_table
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VS_CONSTBUF |
             BRW_NEW_VS_PROG_DATA |
             BRW_NEW_SURFACES,
   },
   .emit = brw_vs_upload_binding_table,
}
brw_wm_binding_table
const struct brw_tracked_state brw_wm_binding_table
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FS_PROG_DATA |
             BRW_NEW_SURFACES,
   },
   .emit = brw_upload_wm_binding_table,
}
gen6_binding_table_pointers
const struct brw_tracked_state gen6_binding_table_pointers
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_BINDING_TABLE_POINTERS |
             BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = gen6_upload_binding_table_pointers,
}