Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_pipe_control.c File Reference
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "intel_fbo.h"
Functions
static void gen8_add_cs_stall_workaround_bits (uint32_t *flags)
According to the latest documentation, any PIPE_CONTROL with the "Command Streamer Stall" bit set must also have another bit set, with five different options:
static uint32_t gen7_cs_stall_every_four_pipe_controls (struct brw_context *brw, uint32_t flags)
void brw_emit_pipe_control_flush (struct brw_context *brw, uint32_t flags)
Emit a PIPE_CONTROL with various flushing flags.
void brw_emit_pipe_control_write (struct brw_context *brw, uint32_t flags, drm_intel_bo *bo, uint32_t offset, uint32_t imm_lower, uint32_t imm_upper)
Emit a PIPE_CONTROL that writes to a buffer object.
void brw_emit_depth_stall_flushes (struct brw_context *brw)
Restriction [DevSNB, DevIVB]:
void gen7_emit_vs_workaround_flush (struct brw_context *brw)
From the Ivybridge PRM, Volume 2 Part 1, Section 3.2 (VS Stage Input): "A PIPE_CONTROL with Post-Sync Operation set to 1h and a depth stall needs to be sent just prior to any 3DSTATE_VS, 3DSTATE_URB_VS, 3DSTATE_CONSTANT_VS, 3DSTATE_BINDING_TABLE_POINTER_VS, 3DSTATE_SAMPLER_STATE_POINTER_VS command.
void gen7_emit_cs_stall_flush (struct brw_context *brw)
Emit a PIPE_CONTROL command for gen7 with the CS Stall bit set.
void brw_emit_post_sync_nonzero_flush (struct brw_context *brw)
Emits a PIPE_CONTROL with a non-zero post-sync operation, for implementing two workarounds on gen6.
void brw_emit_mi_flush (struct brw_context *brw)
int brw_init_pipe_control (struct brw_context *brw, const struct gen_device_info *devinfo)
void brw_fini_pipe_control (struct brw_context *brw)
Function Documentation
brw_emit_depth_stall_flushes()
void brw_emit_depth_stall_flushes (struct brw_context * brw)
Restriction [DevSNB, DevIVB]:
Prior to changing Depth/Stencil Buffer state (i.e. any combination of 3DSTATE_DEPTH_BUFFER, 3DSTATE_CLEAR_PARAMS, 3DSTATE_STENCIL_BUFFER, 3DSTATE_HIER_DEPTH_BUFFER) SW must first issue a pipelined depth stall (PIPE_CONTROL with Depth Stall bit set), followed by a pipelined depth cache flush (PIPE_CONTROL with Depth Flush Bit set), followed by another pipelined depth stall (PIPE_CONTROL with Depth Stall bit set), unless SW can otherwise guarantee that the pipeline from WM onwards is already flushed (e.g., via a preceding MI_FLUSH).
References brw_emit_pipe_control_flush(), brw_context::gen, PIPE_CONTROL_DEPTH_CACHE_FLUSH, and PIPE_CONTROL_DEPTH_STALL.
Referenced by blorp_exec(), brw_depth_writes_enabled(), brw_emit_depth_stencil_hiz(), emit_depth_packets(), gen6_emit_depth_stencil_hiz(), and gen7_emit_depth_stencil_hiz().
brw_emit_mi_flush()
void brw_emit_mi_flush (struct brw_context * brw)
References ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH_BLT, BLT_RING, brw_emit_pipe_control_flush(), brw_context::gen, MI_FLUSH_DW, OUT_BATCH, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_INSTRUCTION_INVALIDATE, PIPE_CONTROL_NO_WRITE, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE, PIPE_CONTROL_VF_CACHE_INVALIDATE, and intel_batchbuffer::ring.
Referenced by brw_begin_perf_query(), brw_copy_buffer_subdata(), brw_depth_writes_enabled(), brw_emit_prim(), brw_end_perf_query(), brw_fence_insert_locked(), brw_finish_batch(), brw_render_cache_set_check_flush(), brw_save_primitives_written_counters(), brw_unmap_buffer(), emit_pipeline_stat(), gen6_upload_urb(), gen7_pause_transform_feedback(), hsw_pause_transform_feedback(), intel_get_tex_sub_image(), intel_miptree_set_alpha_to_one(), intel_texture_barrier(), intelEmitCopyBlit(), intelEmitImmediateColorExpandBlit(), intelReadPixels(), save_prim_start_values(), tally_prims_written(), write_primitives_generated(), write_xfb_overflow_streams(), and write_xfb_primitives_written().
brw_emit_pipe_control_flush()
void brw_emit_pipe_control_flush (struct brw_context * brw, uint32_t flags)
Emit a PIPE_CONTROL with various flushing flags.
The caller is responsible for deciding what flags are appropriate for the given generation.
References _3DSTATE_PIPE_CONTROL, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_post_sync_nonzero_flush(), brw_context::gen, gen7_cs_stall_every_four_pipe_controls(), gen8_add_cs_stall_workaround_bits(), OUT_BATCH, PIPE_CONTROL_CACHE_FLUSH_BITS, PIPE_CONTROL_CACHE_INVALIDATE_BITS, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, and PIPE_CONTROL_VF_CACHE_INVALIDATE.
Referenced by brw_blend_barrier(), brw_blorp_resolve_color(), brw_depth_writes_enabled(), brw_emit_depth_stall_flushes(), brw_emit_mi_flush(), brw_emit_post_sync_nonzero_flush(), brw_emit_select_pipeline(), brw_fast_clear_depth(), brw_finish_batch(), brw_memory_barrier(), brw_render_cache_set_check_flush(), brw_write_timestamp(), do_single_blorp_clear(), gen8_hiz_exec(), gen8_write_pma_stall_bits(), hsw_result_to_gpr0(), intel_texture_barrier(), set_predicate_for_result(), setup_l3_config(), and upload_vs_state().
brw_emit_pipe_control_write()
void brw_emit_pipe_control_write (struct brw_context * brw, uint32_t flags, drm_intel_bo * bo, uint32_t offset, uint32_t imm_lower, uint32_t imm_upper)
Emit a PIPE_CONTROL that writes to a buffer object.
flags should contain one of the following items:
PIPE_CONTROL_WRITE_IMMEDIATE
PIPE_CONTROL_WRITE_TIMESTAMP
PIPE_CONTROL_WRITE_DEPTH_COUNT
References _3DSTATE_PIPE_CONTROL, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, gen7_cs_stall_every_four_pipe_controls(), gen8_add_cs_stall_workaround_bits(), OUT_BATCH, OUT_RELOC, OUT_RELOC64, and PIPE_CONTROL_GLOBAL_GTT_WRITE.
Referenced by brw_depth_writes_enabled(), brw_emit_post_sync_nonzero_flush(), brw_write_depth_count(), brw_write_timestamp(), gen7_emit_cs_stall_flush(), gen7_emit_vs_workaround_flush(), gen8_hiz_exec(), and set_query_availability().
brw_emit_post_sync_nonzero_flush()
void brw_emit_post_sync_nonzero_flush (struct brw_context * brw)
Emits a PIPE_CONTROL with a non-zero post-sync operation, for implementing two workarounds on gen6.
From section 1.4.7.1 "PIPE_CONTROL" of the Sandy Bridge PRM volume 2 part 1:
[DevSNB-C+{W/A}] Before any depth stall flush (including those produced by non-pipelined state commands), software needs to first send a PIPE_CONTROL with no bits set except Post-Sync Operation != 0.
[Dev-SNB{W/A}]: Before a PIPE_CONTROL with Write Cache Flush Enable =1, a PIPE_CONTROL with any non-zero post-sync-op is required.
And the workaround for these two requires this workaround first:
[Dev-SNB{W/A}]: Pipe-control with CS-stall bit set must be sent BEFORE the pipe-control with a post-sync op and no write-cache flushes.
And this last workaround is tricky because of the requirements on that bit. From section 1.4.7.2.3 "Stall" of the Sandy Bridge PRM volume 2 part 1:
"1 of the following must also be set:
 - Render Target Cache Flush Enable ([12] of DW1)
 - Depth Cache Flush Enable ([0] of DW1)
 - Stall at Pixel Scoreboard ([1] of DW1)
 - Depth Stall ([13] of DW1)
 - Post-Sync Operation ([13] of DW1)
 - Notify Enable ([8] of DW1)"
The cache flushes require the workaround flush that triggered this one, so we can't use it. Depth stall would trigger the same. Post-sync nonzero is what triggered this second workaround, so we can't use that one either. Notify enable is IRQs, which aren't really our business. That leaves only stall at scoreboard.
References brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), PIPE_CONTROL_CS_STALL, PIPE_CONTROL_STALL_AT_SCOREBOARD, PIPE_CONTROL_WRITE_IMMEDIATE, and brw_context::workaround_bo.
Referenced by blorp_exec(), brw_depth_writes_enabled(), brw_emit_pipe_control_flush(), brw_upload_initial_gpu_state(), and brw_upload_pipeline_state().
brw_fini_pipe_control()
void brw_fini_pipe_control (struct brw_context * brw)
References brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), and intelDestroyContext().
brw_init_pipe_control()
int brw_init_pipe_control (struct brw_context * brw, const struct gen_device_info * devinfo)
References brw_context::bufmgr, brw_context::pipe_controls_since_last_cs_stall, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
gen7_cs_stall_every_four_pipe_controls()
static uint32_t gen7_cs_stall_every_four_pipe_controls (struct brw_context * brw, uint32_t flags) static
References brw_context::gen, brw_context::is_haswell, PIPE_CONTROL_CS_STALL, and brw_context::pipe_controls_since_last_cs_stall.
Referenced by brw_emit_pipe_control_flush(), and brw_emit_pipe_control_write().
gen7_emit_cs_stall_flush()
void gen7_emit_cs_stall_flush (struct brw_context * brw)
Emit a PIPE_CONTROL command for gen7 with the CS Stall bit set.
References brw_emit_pipe_control_write(), PIPE_CONTROL_CS_STALL, PIPE_CONTROL_WRITE_IMMEDIATE, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), brw_emit_select_pipeline(), gen7_emit_push_constant_state(), and upload_gs_state().
gen7_emit_vs_workaround_flush()
void gen7_emit_vs_workaround_flush (struct brw_context * brw)
From the Ivybridge PRM, Volume 2 Part 1, Section 3.2 (VS Stage Input): "A PIPE_CONTROL with Post-Sync Operation set to 1h and a depth stall needs to be sent just prior to any 3DSTATE_VS, 3DSTATE_URB_VS, 3DSTATE_CONSTANT_VS, 3DSTATE_BINDING_TABLE_POINTER_VS, 3DSTATE_SAMPLER_STATE_POINTER_VS command.
Only one PIPE_CONTROL needs to be sent before any combination of VS associated 3DSTATE."
References brw_emit_pipe_control_write(), brw_context::gen, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_WRITE_IMMEDIATE, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), gen6_upload_vs_push_constants(), gen7_emit_sampler_state_pointers_xs(), gen7_upload_urb(), and upload_vs_state().
gen8_add_cs_stall_workaround_bits()
static void gen8_add_cs_stall_workaround_bits (uint32_t * flags) static
According to the latest documentation, any PIPE_CONTROL with the "Command Streamer Stall" bit set must also have another bit set, with five different options:
Render Target Cache Flush
Depth Cache Flush
Stall at Pixel Scoreboard
Post-Sync Operation
Depth Stall
DC Flush Enable
I chose "Stall at Pixel Scoreboard" since we've used it effectively in the past, but the choice is fairly arbitrary.
References PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DATA_CACHE_FLUSH, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_STALL_AT_SCOREBOARD, PIPE_CONTROL_WRITE_DEPTH_COUNT, PIPE_CONTROL_WRITE_IMMEDIATE, and PIPE_CONTROL_WRITE_TIMESTAMP.
Referenced by brw_emit_pipe_control_flush(), and brw_emit_pipe_control_write().