Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_ff_gs.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "main/transformfeedback.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_util.h"
#include "brw_state.h"
#include "brw_ff_gs.h"
#include "util/ralloc.h"
Functions
void brw_codegen_ff_gs_prog (struct brw_context *brw, struct brw_ff_gs_prog_key *key)
static bool brw_ff_gs_state_dirty (const struct brw_context *brw)
static void brw_ff_gs_populate_key (struct brw_context *brw, struct brw_ff_gs_prog_key *key)
void brw_upload_ff_gs_prog (struct brw_context *brw)
void gen6_brw_upload_ff_gs_prog (struct brw_context *brw)
Function Documentation
brw_codegen_ff_gs_prog()
void brw_codegen_ff_gs_prog (struct brw_context * brw, struct brw_ff_gs_prog_key * key)
References brw_context::base, BRW_CACHE_FF_GS_PROG, brw_ff_gs_lines(), brw_ff_gs_quad_strip(), brw_ff_gs_quads(), brw_upload_cache(), brw_context::cache, intel_screen::devinfo, brw_context::ff_gs, brw_ff_gs_compile::func, brw_context::gen, gen6_sol_program(), GLuint, brw_ff_gs_compile::key, brw_ff_gs_compile::nr_regs, brw_ff_gs_prog_key::primitive, brw_ff_gs_compile::prog_data, brw_stage_state::prog_data, brw_context::prog_data, brw_context::prog_offset, brw_context::screen, brw_context::vs, and brw_ff_gs_compile::vue_map.
Referenced by brw_upload_ff_gs_prog().
brw_ff_gs_populate_key()
static void brw_ff_gs_populate_key (struct brw_context * brw, struct brw_ff_gs_prog_key * key) static
References gl_context::_Shader, brw_ff_gs_prog_key::attrs, brw_context::base, gl_transform_feedback_output::ComponentOffset, brw_context::ctx, gl_pipeline_object::CurrentProgram, brw_context::gen, gl_context::Light, brw_ff_gs_prog_key::need_gs_prog, brw_ff_gs_prog_key::num_transform_feedback_bindings, gl_transform_feedback_info::NumOutputs, gl_transform_feedback_output::OutputRegister, gl_transform_feedback_info::Outputs, brw_ff_gs_prog_key::primitive, brw_context::primitive, brw_stage_state::prog_data, gl_light_attrib::ProvokingVertex, brw_ff_gs_prog_key::pv_first, gl_program::sh, gl_light_attrib::ShadeModel, brw_ff_gs_prog_key::transform_feedback_bindings, brw_ff_gs_prog_key::transform_feedback_swizzles, and brw_context::vs.
Referenced by brw_upload_ff_gs_prog().
brw_ff_gs_state_dirty()
static bool brw_ff_gs_state_dirty (const struct brw_context * brw) static
References _NEW_LIGHT, BRW_NEW_PRIMITIVE, BRW_NEW_TRANSFORM_FEEDBACK, BRW_NEW_VS_PROG_DATA, and brw_state_dirty().
Referenced by brw_upload_ff_gs_prog().
brw_upload_ff_gs_prog()
void brw_upload_ff_gs_prog (struct brw_context * brw)
References BRW_CACHE_FF_GS_PROG, brw_codegen_ff_gs_prog(), brw_ff_gs_populate_key(), brw_ff_gs_state_dirty(), BRW_NEW_FF_GS_PROG_DATA, brw_search_cache(), brw_context::cache, brw_context::ctx, brw_context::ff_gs, brw_ff_gs_prog_key::need_gs_prog, gl_context::NewDriverState, brw_context::prog_active, brw_context::prog_data, and brw_context::prog_offset.
Referenced by brw_upload_programs(), and gen6_brw_upload_ff_gs_prog().
gen6_brw_upload_ff_gs_prog()
void gen6_brw_upload_ff_gs_prog (struct brw_context * brw)
References brw_upload_ff_gs_prog().
Referenced by brw_upload_gs_prog().