Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip_line.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "program/program.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_clip.h"
Functions
static void brw_clip_line_alloc_regs (struct brw_clip_compile *c)
static void clip_and_emit_line (struct brw_clip_compile *c)
void brw_emit_line_clip (struct brw_clip_compile *c)
Function Documentation
brw_clip_line_alloc_regs()
static void brw_clip_line_alloc_regs (struct brw_clip_compile * c) static
References brw_clip_compile::clipdistance_offset, brw_clip_prog_data::curb_read_length, brw_clip_compile::dp1, brw_clip_compile::ff_sync, brw_clip_compile::first_tmp, brw_clip_compile::fixed_planes, brw_clip_compile::func, GLuint, brw_clip_compile::key, brw_clip_compile::last_tmp, brw_clip_compile::nr_regs, brw_clip_prog_key::nr_userclip, brw_clip_compile::plane_equation, brw_clip_compile::planemask, brw_clip_compile::prog_data, brw_clip_compile::R0, brw_clip_compile::reg, brw_clip_compile::t, brw_clip_compile::t1, brw_clip_prog_data::total_grf, brw_clip_prog_data::urb_read_length, brw_clip_compile::vertex, and brw_clip_compile::vertex_src_mask.
Referenced by brw_emit_line_clip().
brw_emit_line_clip()
void brw_emit_line_clip (struct brw_clip_compile * c)
References brw_clip_copy_flatshaded_attributes(), brw_clip_init_ff_sync(), brw_clip_line_alloc_regs(), clip_and_emit_line(), brw_clip_prog_key::contains_flat_varying, brw_clip_compile::key, and brw_clip_prog_key::pv_first.
Referenced by brw_clip_have_varying(), and compile_clip_prog().
clip_and_emit_line()
static void clip_and_emit_line (struct brw_clip_compile * c) static
References brw_clip_emit_vue(), brw_clip_init_clipmask(), brw_clip_init_planes(), brw_clip_interp_vertex(), brw_clip_kill_thread(), brw_clip_plane0_address(), brw_clip_plane_stride(), brw_clip_compile::clipdistance_offset, brw_clip_compile::dp1, brw_clip_compile::func, GLuint, brw_clip_compile::key, brw_clip_prog_key::nr_userclip, brw_clip_compile::plane_equation, brw_clip_compile::planemask, brw_clip_compile::R0, brw_clip_compile::reg, brw_clip_compile::t, brw_clip_compile::t1, brw_clip_compile::vertex, brw_clip_compile::vertex_src_mask, and brw_clip_compile::vue_map.
Referenced by brw_emit_line_clip().