Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_tex_layout.c File Reference
#include "intel_mipmap_tree.h"
#include "brw_context.h"
#include "main/macros.h"
#include "main/glformats.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_MIPTREE
Functions
static unsigned int intel_horizontal_texture_alignment_unit (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t layout_flags)
static unsigned int intel_vertical_texture_alignment_unit (struct brw_context *brw, const struct intel_mipmap_tree *mt)
static void gen9_miptree_layout_1d (struct intel_mipmap_tree *mt)
static void brw_miptree_layout_2d (struct intel_mipmap_tree *mt)
unsigned brw_miptree_get_horizontal_slice_pitch (const struct brw_context *brw, const struct intel_mipmap_tree *mt, unsigned level)
unsigned brw_miptree_get_vertical_slice_pitch (const struct brw_context *brw, const struct intel_mipmap_tree *mt, unsigned level)
static void align_cube (struct intel_mipmap_tree *mt)
bool gen9_use_linear_1d_layout (const struct brw_context *brw, const struct intel_mipmap_tree *mt)
static void brw_miptree_layout_texture_array (struct brw_context *brw, struct intel_mipmap_tree *mt)
static void brw_miptree_layout_texture_3d (struct brw_context *brw, struct intel_mipmap_tree *mt)
static uint32_t brw_miptree_choose_tiling (struct brw_context *brw, const struct intel_mipmap_tree *mt, uint32_t layout_flags)
Helper function for intel_miptree_create().
static void intel_miptree_set_total_width_height (struct brw_context *brw, struct intel_mipmap_tree *mt)
static void intel_miptree_set_alignment (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t layout_flags)
bool brw_miptree_layout (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t layout_flags)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_MIPTREE
Function Documentation
align_cube()
static void align_cube (struct intel_mipmap_tree * mt) static
Referenced by brw_miptree_layout_texture_3d(), and brw_miptree_layout_texture_array().
brw_miptree_choose_tiling()
static uint32_t brw_miptree_choose_tiling (struct brw_context * brw, const struct intel_mipmap_tree * mt, uint32_t layout_flags) static
Helper function for intel_miptree_create().
References _mesa_get_format_base_format(), brw_context::format_supported_as_render_target, brw_context::gen, and MESA_FORMAT_S_UINT8.
Referenced by brw_miptree_layout().
brw_miptree_get_horizontal_slice_pitch()
unsigned brw_miptree_get_horizontal_slice_pitch (const struct brw_context * brw, const struct intel_mipmap_tree * mt, unsigned level)
References brw_context::gen.
Referenced by update_texture_image_param().
brw_miptree_get_vertical_slice_pitch()
unsigned brw_miptree_get_vertical_slice_pitch (const struct brw_context * brw, const struct intel_mipmap_tree * mt, unsigned level)
References _mesa_get_format_base_format(), _mesa_is_depth_or_stencil_format(), and brw_context::gen.
Referenced by brw_miptree_layout_texture_array(), and update_texture_image_param().
brw_miptree_layout()
bool brw_miptree_layout (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t layout_flags)
References _mesa_get_format_block_size(), brw_miptree_choose_tiling(), brw_context::gen, intel_miptree_set_alignment(), and intel_miptree_set_total_width_height().
Referenced by intel_miptree_create_layout().
brw_miptree_layout_2d()
static void brw_miptree_layout_2d (struct intel_mipmap_tree * mt) static
References _mesa_get_format_block_size(), intel_miptree_set_level_info(), and x.
Referenced by brw_miptree_layout_texture_array(), and intel_miptree_set_total_width_height().
brw_miptree_layout_texture_3d()
static void brw_miptree_layout_texture_3d (struct brw_context * brw, struct intel_mipmap_tree * mt) static
References _mesa_get_format_block_size(), align_cube(), intel_miptree_set_image_offset(), intel_miptree_set_level_info(), and x.
Referenced by intel_miptree_set_total_width_height().
brw_miptree_layout_texture_array()
static void brw_miptree_layout_texture_array (struct brw_context * brw, struct intel_mipmap_tree * mt) static
References align_cube(), brw_miptree_get_vertical_slice_pitch(), brw_miptree_layout_2d(), brw_context::gen, gen9_miptree_layout_1d(), gen9_use_linear_1d_layout(), and intel_miptree_set_image_offset().
Referenced by intel_miptree_set_total_width_height().
gen9_miptree_layout_1d()
static void gen9_miptree_layout_1d (struct intel_mipmap_tree * mt) static
References intel_miptree_set_level_info(), and x.
Referenced by brw_miptree_layout_texture_array(), and intel_miptree_set_total_width_height().
gen9_use_linear_1d_layout()
bool gen9_use_linear_1d_layout (const struct brw_context * brw, const struct intel_mipmap_tree * mt)
References _mesa_get_format_base_format(), and brw_context::gen.
Referenced by brw_depth_writes_enabled(), brw_miptree_layout_texture_array(), and intel_miptree_set_total_width_height().
intel_horizontal_texture_alignment_unit()
static unsigned int intel_horizontal_texture_alignment_unit (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t layout_flags) static
+-------------------------------------------------------------------—+ | | alignment unit width ("i") | | Surface Property |--------------------------—| | | 915 | 965 | ILK | SNB | IVB | +-------------------------------------------------------------------—+ | YUV 4:2:2 format | 8 | 4 | 4 | 4 | 4 | | BC1-5 compressed format (DXTn/S3TC) | 4 | 4 | 4 | 4 | 4 | | FXT1 compressed format | 8 | 8 | 8 | 8 | 8 | | Depth Buffer (16-bit) | 4 | 4 | 4 | 4 | 8 | | Depth Buffer (other) | 4 | 4 | 4 | 4 | 4 | | Separate Stencil Buffer | N/A | N/A | 8 | 8 | 8 | | All Others | 4 | 4 | 4 | 4 | 4 | +-------------------------------------------------------------------—+
On IVB+, non-special cases can be overridden by setting the SURFACE_STATE "Surface Horizontal Alignment" field to HALIGN_4 or HALIGN_8.
References brw_context::gen, and MESA_FORMAT_Z_UNORM16.
Referenced by intel_miptree_set_alignment().
intel_miptree_set_alignment()
static void intel_miptree_set_alignment (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t layout_flags) static
From the "Alignment Unit Size" section of various specs, namely:
Gen3 Spec: "Memory Data Formats" Volume, Section 1.20.1.4
i965 and G45 PRMs: Volume 1, Section 6.17.3.4.
Ironlake and Sandybridge PRMs: Volume 1, Part 1, Section 7.18.3.4
BSpec (for Ivybridge and slight variations in separate stencil)
References _mesa_get_format_base_format(), _mesa_get_format_block_size(), _mesa_is_depth_or_stencil_format(), brw_context::gen, intel_horizontal_texture_alignment_unit(), intel_vertical_texture_alignment_unit(), and MESA_FORMAT_S_UINT8.
Referenced by brw_miptree_layout().
intel_miptree_set_total_width_height()
static void intel_miptree_set_total_width_height (struct brw_context * brw, struct intel_mipmap_tree * mt) static
References brw_miptree_layout_2d(), brw_miptree_layout_texture_3d(), brw_miptree_layout_texture_array(), DBG, brw_context::gen, gen9_miptree_layout_1d(), and gen9_use_linear_1d_layout().
Referenced by brw_miptree_layout().
intel_vertical_texture_alignment_unit()
static unsigned int intel_vertical_texture_alignment_unit (struct brw_context * brw, const struct intel_mipmap_tree * mt) static
+-------------------------------------------------------------------—+ | | alignment unit height ("j") | | Surface Property |--------------------------—| | | 915 | 965 | ILK | SNB | IVB | +-------------------------------------------------------------------—+ | BC1-5 compressed format (DXTn/S3TC) | 4 | 4 | 4 | 4 | 4 | | FXT1 compressed format | 4 | 4 | 4 | 4 | 4 | | Depth Buffer | 2 | 2 | 2 | 4 | 4 | | Separate Stencil Buffer | N/A | N/A | N/A | 4 | 8 | | Multisampled (4x or 8x) render target | N/A | N/A | N/A | 4 | 4 | | All Others | 2 | 2 | 2 | * | * | +-------------------------------------------------------------------—+
Where "*" means either VALIGN_2 or VALIGN_4 depending on the setting of the SURFACE_STATE "Surface Vertical Alignment" field.
References _mesa_get_format_base_format(), brw_context::gen, and MESA_FORMAT_RGB_FLOAT32.
Referenced by intel_miptree_set_alignment().