Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip_point.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "program/program.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_clip.h"
Functions
void brw_emit_point_clip (struct brw_clip_compile *c)
Function Documentation
brw_emit_point_clip()
void brw_emit_point_clip (struct brw_clip_compile * c)
References brw_clip_init_ff_sync(), brw_clip_kill_thread(), and brw_clip_tri_alloc_regs().
Referenced by brw_clip_have_varying(), and compile_clip_prog().