Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_util.c File Reference
#include "brw_util.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
Functions
GLuint brw_translate_blend_equation (GLenum mode)
GLuint brw_translate_blend_factor (GLenum factor)
uint32_t get_hw_prim_for_gl_prim (int mode)
Variables
static const GLuint prim_to_hw_prim [GL_TRIANGLE_STRIP_ADJACENCY+1]
Function Documentation
brw_translate_blend_equation()
GLuint brw_translate_blend_equation (GLenum mode)
References BRW_BLENDFUNCTION_ADD, BRW_BLENDFUNCTION_MAX, BRW_BLENDFUNCTION_MIN, BRW_BLENDFUNCTION_REVERSE_SUBTRACT, BRW_BLENDFUNCTION_SUBTRACT, and GLuint.
Referenced by gen6_upload_blend_state(), and upload_cc_unit().
brw_translate_blend_factor()
GLuint brw_translate_blend_factor (GLenum factor)
References BRW_BLENDFACTOR_CONST_ALPHA, BRW_BLENDFACTOR_CONST_COLOR, BRW_BLENDFACTOR_DST_ALPHA, BRW_BLENDFACTOR_DST_COLOR, BRW_BLENDFACTOR_INV_CONST_ALPHA, BRW_BLENDFACTOR_INV_CONST_COLOR, BRW_BLENDFACTOR_INV_DST_ALPHA, BRW_BLENDFACTOR_INV_DST_COLOR, BRW_BLENDFACTOR_INV_SRC1_ALPHA, BRW_BLENDFACTOR_INV_SRC1_COLOR, BRW_BLENDFACTOR_INV_SRC_ALPHA, BRW_BLENDFACTOR_INV_SRC_COLOR, BRW_BLENDFACTOR_ONE, BRW_BLENDFACTOR_SRC1_ALPHA, BRW_BLENDFACTOR_SRC1_COLOR, BRW_BLENDFACTOR_SRC_ALPHA, BRW_BLENDFACTOR_SRC_ALPHA_SATURATE, BRW_BLENDFACTOR_SRC_COLOR, BRW_BLENDFACTOR_ZERO, and GLuint.
Referenced by gen6_upload_blend_state(), and upload_cc_unit().
get_hw_prim_for_gl_prim()
uint32_t get_hw_prim_for_gl_prim (int mode)
References prim_to_hw_prim.
Referenced by brw_depth_writes_enabled(), brw_set_prim(), and gen6_set_prim().
Variable Documentation
prim_to_hw_prim
const GLuint prim_to_hw_prim[GL_TRIANGLE_STRIP_ADJACENCY+1] static
Initial value:
= {
   [GL_POINTS] =_3DPRIM_POINTLIST,
   [GL_LINES] = _3DPRIM_LINELIST,
   [GL_LINE_LOOP] = _3DPRIM_LINELOOP,
   [GL_LINE_STRIP] = _3DPRIM_LINESTRIP,
   [GL_TRIANGLES] = _3DPRIM_TRILIST,
   [GL_TRIANGLE_STRIP] = _3DPRIM_TRISTRIP,
   [GL_TRIANGLE_FAN] = _3DPRIM_TRIFAN,
   [GL_QUADS] = _3DPRIM_QUADLIST,
   [GL_QUAD_STRIP] = _3DPRIM_QUADSTRIP,
   [GL_POLYGON] = _3DPRIM_POLYGON,
   [GL_LINES_ADJACENCY] = _3DPRIM_LINELIST_ADJ,
   [GL_LINE_STRIP_ADJACENCY] = _3DPRIM_LINESTRIP_ADJ,
   [GL_TRIANGLES_ADJACENCY] = _3DPRIM_TRILIST_ADJ,
   [GL_TRIANGLE_STRIP_ADJACENCY] = _3DPRIM_TRISTRIP_ADJ,
}
Referenced by get_hw_prim_for_gl_prim().