Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_vs_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "main/macros.h"
Functions
static void brw_upload_vs_unit (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_vs_unit
Function Documentation
brw_upload_vs_unit()
static void brw_upload_vs_unit (struct brw_context * brw) static
References brw_context::base, brw_context::batch, thread1::binding_table_entry_count, intel_batchbuffer::bo, BRW_FLOATING_POINT_IEEE_754, BRW_FLOATING_POINT_NON_IEEE_754, BRW_NEW_GEN4_UNIT_STATE, brw_program_reloc(), brw_state_batch(), thread3::const_urb_entry_read_length, thread3::const_urb_entry_read_offset, brw_context::ctx, brw_context::curbe, intel_screen::devinfo, thread3::dispatch_grf_start_reg, thread1::floating_point_mode, brw_context::gen, thread0::grf_reg_count, if(), brw_context::is_g4x, thread0::kernel_start_pointer, brw_vs_unit_state::max_threads, gl_context::NewDriverState, brw_vs_unit_state::nr_urb_entries, brw_context::nr_vs_entries, brw_stage_state::per_thread_scratch, thread2::per_thread_scratch_space, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_vs_unit_state::sampler_count, brw_stage_state::sampler_count, brw_stage_state::sampler_offset, brw_vs_unit_state::sampler_state_pointer, brw_stage_state::scratch_bo, thread2::scratch_space_base_pointer, brw_context::screen, thread1::single_program_flow, brw_stage_state::state_offset, brw_vs_unit_state::stats_enable, brw_vs_unit_state::thread0, brw_vs_unit_state::thread1, brw_vs_unit_state::thread2, brw_vs_unit_state::thread3, brw_vs_unit_state::thread4, brw_context::urb, brw_vs_unit_state::urb_entry_allocation_size, thread3::urb_entry_read_length, thread3::urb_entry_read_offset, brw_context::vs, brw_vs_unit_state::vs5, brw_vs_unit_state::vs6, brw_vs_unit_state::vs_enable, brw_context::vs_start, and brw_context::vsize.
Variable Documentation
brw_vs_unit
const struct brw_tracked_state brw_vs_unit
Initial value:
= {
   .dirty = {
      .mesa  = 0,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_CURBE_OFFSETS |
               BRW_NEW_PROGRAM_CACHE |
               BRW_NEW_SAMPLER_STATE_TABLE |
               BRW_NEW_URB_FENCE |
               BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_upload_vs_unit,
}