Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip_util.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "program/program.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_clip.h"
Macros
#define W 3
Functions
struct brw_reg get_tmp (struct brw_clip_compile *c)
static void release_tmp (struct brw_clip_compile *c, struct brw_reg tmp)
static struct brw_reg make_plane_ud (GLuint x, GLuint y, GLuint z, GLuint w)
void brw_clip_init_planes (struct brw_clip_compile *c)
void brw_clip_project_position (struct brw_clip_compile *c, struct brw_reg pos)
static void brw_clip_project_vertex (struct brw_clip_compile *c, struct brw_indirect vert_addr)
void brw_clip_interp_vertex (struct brw_clip_compile *c, struct brw_indirect dest_ptr, struct brw_indirect v0_ptr, struct brw_indirect v1_ptr, struct brw_reg t0, bool force_edgeflag)
void brw_clip_emit_vue (struct brw_clip_compile *c, struct brw_indirect vert, enum brw_urb_write_flags flags, GLuint header)
void brw_clip_kill_thread (struct brw_clip_compile *c)
struct brw_reg brw_clip_plane0_address (struct brw_clip_compile *c)
struct brw_reg brw_clip_plane_stride (struct brw_clip_compile *c)
void brw_clip_copy_flatshaded_attributes (struct brw_clip_compile *c, GLuint to, GLuint from)
void brw_clip_init_clipmask (struct brw_clip_compile *c)
void brw_clip_ff_sync (struct brw_clip_compile *c)
void brw_clip_init_ff_sync (struct brw_clip_compile *c)
Macro Definition Documentation
W
#define W 3
Referenced by brw_clip_project_position().
Function Documentation
brw_clip_copy_flatshaded_attributes()
void brw_clip_copy_flatshaded_attributes (struct brw_clip_compile * c, GLuint to, GLuint from)
References brw_clip_compile::func, brw_clip_prog_key::interp_mode, brw_clip_compile::key, brw_clip_compile::reg, brw_clip_compile::vertex, and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_clip_tri_flat_shade(), and brw_emit_line_clip().
brw_clip_emit_vue()
void brw_clip_emit_vue (struct brw_clip_compile * c, struct brw_indirect vert, enum brw_urb_write_flags flags, GLuint header)
References brw_clip_ff_sync(), brw_clip_compile::func, brw_clip_compile::nr_regs, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_clip_tri_emit_polygon(), clip_and_emit_line(), emit_lines(), and emit_points().
brw_clip_ff_sync()
void brw_clip_ff_sync (struct brw_clip_compile * c)
References brw_clip_compile::ff_sync, brw_clip_compile::func, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_emit_vue(), brw_clip_have_varying(), and brw_clip_kill_thread().
brw_clip_init_clipmask()
void brw_clip_init_clipmask (struct brw_clip_compile * c)
References brw_clip_compile::func, get_tmp(), brw_clip_compile::key, brw_clip_prog_key::nr_userclip, brw_clip_compile::planemask, brw_clip_compile::R0, brw_clip_compile::reg, and release_tmp().
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), brw_emit_unfilled_clip(), and clip_and_emit_line().
brw_clip_init_ff_sync()
void brw_clip_init_ff_sync (struct brw_clip_compile * c)
References brw_clip_compile::ff_sync, brw_clip_compile::func, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_line_clip(), brw_emit_point_clip(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_clip_init_planes()
void brw_clip_init_planes (struct brw_clip_compile * c)
References brw_clip_compile::fixed_planes, brw_clip_compile::func, brw_clip_compile::key, make_plane_ud(), brw_clip_prog_key::nr_userclip, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_unfilled_clip(), clip_and_emit_line(), and do_clip_tri().
brw_clip_interp_vertex()
void brw_clip_interp_vertex (struct brw_clip_compile * c, struct brw_indirect dest_ptr, struct brw_indirect v0_ptr, struct brw_indirect v1_ptr, struct brw_reg t0, bool force_edgeflag)
References brw_clip_project_vertex(), brw_clip_prog_key::contains_noperspective_varying, brw_clip_compile::func, get_tmp(), GLuint, brw_clip_prog_key::interp_mode, brw_clip_compile::key, release_tmp(), and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_clip_tri(), and clip_and_emit_line().
brw_clip_kill_thread()
void brw_clip_kill_thread (struct brw_clip_compile * c)
References brw_clip_ff_sync(), brw_clip_compile::func, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_clip_test(), brw_emit_point_clip(), brw_emit_tri_clip(), brw_emit_unfilled_clip(), check_nr_verts(), clip_and_emit_line(), and cull_direction().
brw_clip_plane0_address()
struct brw_reg brw_clip_plane0_address (struct brw_clip_compile * c)
Referenced by brw_clip_have_varying(), brw_clip_tri(), and clip_and_emit_line().
brw_clip_plane_stride()
struct brw_reg brw_clip_plane_stride (struct brw_clip_compile * c)
Referenced by brw_clip_have_varying(), brw_clip_tri(), and clip_and_emit_line().
brw_clip_project_position()
void brw_clip_project_position (struct brw_clip_compile * c, struct brw_reg pos)
References brw_clip_compile::func, and W.
Referenced by brw_clip_have_varying(), brw_clip_project_vertex(), and compute_tri_direction().
brw_clip_project_vertex()
static void brw_clip_project_vertex (struct brw_clip_compile * c, struct brw_indirect vert_addr) static
References brw_clip_project_position(), brw_clip_compile::func, get_tmp(), GLuint, release_tmp(), and brw_clip_compile::vue_map.
Referenced by brw_clip_interp_vertex().
get_tmp()
struct brw_reg get_tmp (struct brw_clip_compile * c)
Referenced by brw_clip_have_varying(), brw_clip_init_clipmask(), brw_clip_interp_vertex(), brw_clip_project_vertex(), brw_clip_test(), and compute_tri_direction().
make_plane_ud()
static struct brw_reg make_plane_ud (GLuint x, GLuint y, GLuint z, GLuint w) static
References GLuint, and x.
Referenced by brw_clip_init_planes().
release_tmp()
static void release_tmp (struct brw_clip_compile * c, struct brw_reg tmp) static
References brw_clip_compile::last_tmp.
Referenced by brw_clip_init_clipmask(), brw_clip_interp_vertex(), and brw_clip_project_vertex().