Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_program.c File Reference
#include <pthread.h>
#include "main/imports.h"
#include "program/prog_parameter.h"
#include "program/prog_print.h"
#include "program/prog_to_nir.h"
#include "program/program.h"
#include "program/programopt.h"
#include "tnl/tnl.h"
#include "util/ralloc.h"
#include "compiler/glsl/ir.h"
#include "compiler/glsl/glsl_to_nir.h"
#include "brw_program.h"
#include "brw_context.h"
#include "compiler/brw_nir.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
Data Structures
struct shader_times
Functions
static bool brw_nir_lower_uniforms (nir_shader *nir, bool is_scalar)
nir_shader * brw_create_nir (struct brw_context *brw, const struct gl_shader_program *shader_prog, struct gl_program *prog, gl_shader_stage stage, bool is_scalar)
static unsigned get_new_program_id (struct intel_screen *screen)
static struct gl_program * brwNewProgram (struct gl_context *ctx, GLenum target, GLuint id, bool is_arb_asm)
static void brwDeleteProgram (struct gl_context *ctx, struct gl_program *prog)
static GLboolean brwProgramStringNotify (struct gl_context *ctx, GLenum target, struct gl_program *prog)
static void brw_memory_barrier (struct gl_context *ctx, GLbitfield barriers)
static void brw_blend_barrier (struct gl_context *ctx)
void brw_get_scratch_bo (struct brw_context *brw, drm_intel_bo **scratch_bo, int size)
void brw_alloc_stage_scratch (struct brw_context *brw, struct brw_stage_state *stage_state, unsigned per_thread_size, unsigned thread_count)
Reserve enough scratch space for the given stage to hold per_thread_size bytes times the given thread_count.
void brwInitFragProgFuncs (struct dd_function_table *functions)
void brw_init_shader_time (struct brw_context *brw)
static int compare_time (const void *a, const void *b)
static void print_shader_time_line (const char *stage, const char *name, int shader_num, uint64_t time, uint64_t total)
static void brw_report_shader_time (struct brw_context *brw)
static void brw_collect_shader_time (struct brw_context *brw)
void brw_collect_and_report_shader_time (struct brw_context *brw)
int brw_get_shader_time_index (struct brw_context *brw, struct gl_program *prog, enum shader_time_shader_type type, bool is_glsl_sh)
Chooses an index in the shader_time buffer and sets up tracking information for our printouts.
void brw_destroy_shader_time (struct brw_context *brw)
void brw_stage_prog_data_free (const void *p)
void brw_dump_arb_asm (const char *stage, struct gl_program *prog)
void brw_setup_tex_for_precompile (struct brw_context *brw, struct brw_sampler_prog_key_data *tex, struct gl_program *prog)
uint32_t brw_assign_common_binding_table_offsets (const struct gen_device_info *devinfo, const struct gl_program *prog, struct brw_stage_prog_data *stage_prog_data, uint32_t next_binding_table_offset)
Sets up the starting offsets for the groups of binding table entries common to all pipeline stages.
Function Documentation
brw_alloc_stage_scratch()
void brw_alloc_stage_scratch (struct brw_context * brw, struct brw_stage_state * stage_state, unsigned per_thread_size, unsigned thread_count)
Reserve enough scratch space for the given stage to hold per_thread_size bytes times the given thread_count.
References brw_context::bufmgr, brw_stage_state::per_thread_scratch, and brw_stage_state::scratch_bo.
Referenced by brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), and key_debug().
brw_assign_common_binding_table_offsets()
uint32_t brw_assign_common_binding_table_offsets (const struct gen_device_info * devinfo, const struct gl_program * prog, struct brw_stage_prog_data * stage_prog_data, uint32_t next_binding_table_offset)
Sets up the starting offsets for the groups of binding table entries common to all pipeline stages.
Unused groups are initialized to 0xd0d0d0d0 to make it obvious that they're unused but also make sure that addition of small offsets to them will trigger some of our asserts that surface indices are < BRW_MAX_SURFACES.
References BRW_MAX_SSBO, BRW_MAX_SURFACES, BRW_MAX_UBO, gl_program::info, gl_program::nir, and gl_program::SamplersUsed.
Referenced by assign_cs_binding_table_offsets(), assign_fs_binding_table_offsets(), assign_gs_binding_table_offsets(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), and brw_codegen_vs_prog().
brw_blend_barrier()
static void brw_blend_barrier (struct gl_context * ctx) static
References brw_context(), brw_emit_pipe_control_flush(), gl_context::Extensions, brw_context::gen, gl_extensions::MESA_shader_framebuffer_fetch, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, and PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE.
Referenced by brwInitFragProgFuncs().
brw_collect_and_report_shader_time()
void brw_collect_and_report_shader_time (struct brw_context * brw)
References brw_collect_shader_time(), brw_report_shader_time(), get_time(), brw_context::report_time, and brw_context::shader_time.
Referenced by brw_new_batch(), intelDestroyContext(), and key_debug().
brw_collect_shader_time()
static void brw_collect_shader_time (struct brw_context * brw) static
References brw_context::bo, brw_context::cumulative, brw_context::num_entries, shader_times::reset, brw_context::shader_time, shader_times::time, and shader_times::written.
Referenced by brw_collect_and_report_shader_time().
brw_create_nir()
nir_shader* brw_create_nir (struct brw_context * brw, const struct gl_shader_program * shader_prog, struct gl_program * prog, gl_shader_stage stage, bool is_scalar)
References brw_nir_lower_uniforms(), intel_screen::compiler, gl_context::Const, brw_context::ctx, glsl_to_nir(), gl_program::info, gl_shader_compiler_options::NirOptions, gl_program::Parameters, brw_context::screen, gl_constants::ShaderCompilerOptions, and void.
Referenced by brw_link_shader(), and brwProgramStringNotify().
brw_destroy_shader_time()
void brw_destroy_shader_time (struct brw_context * brw)
References brw_context::bo, and brw_context::shader_time.
Referenced by intelDestroyContext(), and key_debug().
brw_dump_arb_asm()
void brw_dump_arb_asm (const char * stage, struct gl_program * prog)
References gl_program::Id.
Referenced by brw_codegen_vs_prog(), and brw_codegen_wm_prog().
brw_get_scratch_bo()
void brw_get_scratch_bo (struct brw_context * brw, drm_intel_bo ** scratch_bo, int size)
References brw_context::bufmgr.
Referenced by brw_emit_null_surface_state(), and key_debug().
brw_get_shader_time_index()
int brw_get_shader_time_index (struct brw_context * brw, struct gl_program * prog, enum shader_time_shader_type type, bool is_glsl_sh)
Chooses an index in the shader_time buffer and sets up tracking information for our printouts.
Note that this holds on to references to the underlying programs, which may change their lifetimes compared to normal operation.
References gl_program::Id, brw_context::ids, gl_program::info, brw_context::names, brw_context::num_entries, brw_context::shader_time, and brw_context::types.
Referenced by brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), and key_debug().
brw_init_shader_time()
void brw_init_shader_time (struct brw_context * brw)
References brw_context::bo, brw_context::bufmgr, brw_context::cumulative, brw_context::ids, brw_context::max_entries, brw_context::names, brw_context::shader_time, and brw_context::types.
Referenced by brwCreateContext(), and key_debug().
brw_memory_barrier()
static void brw_memory_barrier (struct gl_context * ctx, GLbitfield barriers) static
References brw_context(), brw_emit_pipe_control_flush(), brw_context::gen, brw_context::is_haswell, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DATA_CACHE_FLUSH, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_NO_WRITE, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE, and PIPE_CONTROL_VF_CACHE_INVALIDATE.
Referenced by brwInitFragProgFuncs().
brw_nir_lower_uniforms()
static bool brw_nir_lower_uniforms (nir_shader * nir, bool is_scalar) static
Referenced by brw_create_nir().
brw_report_shader_time()
static void brw_report_shader_time (struct brw_context * brw) static
References brw_context::bo, compare_time(), brw_context::cumulative, brw_context::ids, brw_context::names, brw_context::num_entries, print_shader_time_line(), shader_times::reset, brw_context::shader_time, ST_CS, ST_FS16, ST_FS8, ST_GS, ST_TCS, ST_TES, ST_VS, shader_times::time, brw_context::types, and shader_times::written.
Referenced by brw_collect_and_report_shader_time().
brw_setup_tex_for_precompile()
void brw_setup_tex_for_precompile (struct brw_context * brw, struct brw_sampler_prog_key_data * tex, struct gl_program * prog)
References brw_context::gen, brw_context::is_haswell, gl_program::SamplersUsed, and gl_program::ShadowSamplers.
Referenced by brw_cs_precompile(), brw_fs_precompile(), brw_gs_precompile(), brw_tcs_precompile(), brw_tes_precompile(), and brw_vs_precompile().
brw_stage_prog_data_free()
void brw_stage_prog_data_free (const void * p)
Referenced by brw_clear_cache().
brwDeleteProgram()
static void brwDeleteProgram (struct gl_context * ctx, struct gl_program * prog) static
References brw_context(), brw_context::compute_program, brw_context::fragment_program, brw_context::geometry_program, brw_context::tess_ctrl_program, brw_context::tess_eval_program, and brw_context::vertex_program.
Referenced by brwInitFragProgFuncs().
brwInitFragProgFuncs()
void brwInitFragProgFuncs (struct dd_function_table * functions)
References _tnl_program_string(), dd_function_table::BlendBarrier, brw_blend_barrier(), brw_link_shader(), brw_memory_barrier(), brwDeleteProgram(), brwNewProgram(), brwProgramStringNotify(), dd_function_table::DeleteProgram, dd_function_table::LinkShader, dd_function_table::MemoryBarrier, dd_function_table::NewProgram, and dd_function_table::ProgramStringNotify.
Referenced by brw_init_driver_functions(), and key_debug().
brwNewProgram()
static struct gl_program* brwNewProgram (struct gl_context * ctx, GLenum target, GLuint id, bool is_arb_asm) static
References brw_context(), get_new_program_id(), brw_program::id, brw_program::program, and brw_context::screen.
Referenced by brwInitFragProgFuncs().
brwProgramStringNotify()
static GLboolean brwProgramStringNotify (struct gl_context * ctx, GLenum target, struct gl_program * prog) static
References _tnl_program_string(), gl_program::arb, brw_context(), brw_create_nir(), brw_fs_precompile(), BRW_NEW_FRAGMENT_PROGRAM, BRW_NEW_VERTEX_PROGRAM, brw_program(), brw_program_const(), brw_vs_precompile(), intel_screen::compiler, brw_context::ctx, brw_context::fragment_program, get_new_program_id(), brw_program::id, gl_context::NewDriverState, gl_program::nir, brw_program::program, brw_context::screen, and brw_context::vertex_program.
Referenced by brwInitFragProgFuncs().
compare_time()
static int compare_time (const void * a, const void * b) static
Referenced by brw_report_shader_time().
get_new_program_id()
static unsigned get_new_program_id (struct intel_screen * screen) static
References intel_screen::program_id.
Referenced by brwNewProgram(), and brwProgramStringNotify().
print_shader_time_line()
static void print_shader_time_line (const char * stage, const char * name, int shader_num, uint64_t time, uint64_t total) static
Referenced by brw_report_shader_time().