Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_blorp.h File Reference
#include "blorp/blorp.h"
#include "intel_mipmap_tree.h"
#include "program/prog_instruction.h"
Functions
void brw_blorp_init (struct brw_context *brw)
void brw_blorp_blit_miptrees (struct brw_context *brw, struct intel_mipmap_tree *src_mt, unsigned src_level, unsigned src_layer, mesa_format src_format, int src_swizzle, struct intel_mipmap_tree *dst_mt, unsigned dst_level, unsigned dst_layer, mesa_format dst_format, float src_x0, float src_y0, float src_x1, float src_y1, float dst_x0, float dst_y0, float dst_x1, float dst_y1, GLenum filter, bool mirror_x, bool mirror_y, bool decode_srgb, bool encode_srgb)
Note: if the src (or dst) is a 2D multisample array texture on Gen7+ using INTEL_MSAA_LAYOUT_UMS or INTEL_MSAA_LAYOUT_CMS, src_layer (dst_layer) is the physical layer holding sample 0.
void brw_blorp_copy_miptrees (struct brw_context *brw, struct intel_mipmap_tree *src_mt, unsigned src_level, unsigned src_logical_layer, struct intel_mipmap_tree *dst_mt, unsigned dst_level, unsigned dst_logical_layer, unsigned src_x, unsigned src_y, unsigned dst_x, unsigned dst_y, unsigned src_width, unsigned src_height)
bool brw_blorp_clear_color (struct brw_context *brw, struct gl_framebuffer *fb, GLbitfield mask, bool partial_clear, bool encode_srgb)
void brw_blorp_resolve_color (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned level, unsigned layer)
void intel_hiz_exec (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Perform a HiZ or depth resolve operation.
void gen6_blorp_exec (struct blorp_batch *batch, const struct blorp_params *params)
void gen7_blorp_exec (struct blorp_batch *batch, const struct blorp_params *params)
void gen75_blorp_exec (struct blorp_batch *batch, const struct blorp_params *params)
void gen8_blorp_exec (struct blorp_batch *batch, const struct blorp_params *params)
void gen9_blorp_exec (struct blorp_batch *batch, const struct blorp_params *params)
Function Documentation
brw_blorp_blit_miptrees()
void brw_blorp_blit_miptrees (struct brw_context * brw, struct intel_mipmap_tree * src_mt, unsigned src_level, unsigned src_layer, mesa_format src_format, int src_swizzle, struct intel_mipmap_tree * dst_mt, unsigned dst_level, unsigned dst_layer, mesa_format dst_format, float src_x0, float src_y0, float src_x1, float src_y1, float dst_x0, float dst_y0, float dst_x1, float dst_y1, GLenum filter, bool mirror_x, bool mirror_y, bool decode_srgb, bool encode_srgb)
Note: if the src (or dst) is a 2D multisample array texture on Gen7+ using INTEL_MSAA_LAYOUT_UMS or INTEL_MSAA_LAYOUT_CMS, src_layer (dst_layer) is the physical layer holding sample 0.
So, for example, if src_mt->num_samples == 4, then logical layer n corresponds to src_layer == 4*n.
References _mesa_get_format_color_encoding(), _mesa_get_format_name(), _mesa_get_srgb_format_linear(), brw_context::blorp, blorp_surf_for_miptree(), brw_blorp_to_isl_format(), DBG, brw_context::gen, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_R_FLOAT32, physical_to_logical_layer(), and swizzle_to_scs().
Referenced by brw_blorp_copytexsubimage(), do_blorp_blit(), intel_miptree_updownsample(), and intel_update_r8stencil().
brw_blorp_clear_color()
bool brw_blorp_clear_color (struct brw_context * brw, struct gl_framebuffer * fb, GLbitfield mask, bool partial_clear, bool encode_srgb)
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, do_single_blorp_clear(), intel_renderbuffer(), and intel_renderbuffer::need_downsample.
Referenced by brw_clear().
brw_blorp_copy_miptrees()
void brw_blorp_copy_miptrees (struct brw_context * brw, struct intel_mipmap_tree * src_mt, unsigned src_level, unsigned src_logical_layer, struct intel_mipmap_tree * dst_mt, unsigned dst_level, unsigned dst_logical_layer, unsigned src_x, unsigned src_y, unsigned dst_x, unsigned dst_y, unsigned src_width, unsigned src_height)
References _mesa_get_format_name(), brw_context::blorp, blorp_surf_for_miptree(), and DBG.
Referenced by copy_miptrees().
brw_blorp_init()
void brw_blorp_init (struct brw_context * brw)
References BDW_MOCS_PTE, BDW_MOCS_WB, brw_context::blorp, brw_blorp_lookup_shader(), brw_blorp_upload_shader(), intel_screen::compiler, brw_context::gen, gen6_blorp_exec(), gen75_blorp_exec(), gen7_blorp_exec(), GEN7_MOCS_L3, gen8_blorp_exec(), gen9_blorp_exec(), brw_context::is_haswell, brw_context::isl_dev, brw_context::screen, SKL_MOCS_PTE, and SKL_MOCS_WB.
Referenced by brwCreateContext().
brw_blorp_resolve_color()
void brw_blorp_resolve_color (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned level, unsigned layer)
References _mesa_get_srgb_format_linear(), brw_context::blorp, blorp_surf_for_miptree(), brw_blorp_to_isl_format(), brw_emit_pipe_control_flush(), DBG, brw_context::gen, PIPE_CONTROL_CS_STALL, and PIPE_CONTROL_RENDER_TARGET_FLUSH.
Referenced by intel_miptree_all_slices_resolve_color(), and intel_miptree_resolve_color().
gen6_blorp_exec()
void gen6_blorp_exec (struct blorp_batch * batch, const struct blorp_params * params)
Referenced by brw_blorp_init().
gen75_blorp_exec()
void gen75_blorp_exec (struct blorp_batch * batch, const struct blorp_params * params)
Referenced by brw_blorp_init().
gen7_blorp_exec()
void gen7_blorp_exec (struct blorp_batch * batch, const struct blorp_params * params)
Referenced by brw_blorp_init().
gen8_blorp_exec()
void gen8_blorp_exec (struct blorp_batch * batch, const struct blorp_params * params)
Referenced by brw_blorp_init().
gen9_blorp_exec()
void gen9_blorp_exec (struct blorp_batch * batch, const struct blorp_params * params)
Referenced by brw_blorp_init().
intel_hiz_exec()
void intel_hiz_exec (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Perform a HiZ or depth resolve operation.
For an overview of HiZ ops, see the following sections of the Sandy Bridge PRM, Volume 1, Part 2:
7.5.3.1 Depth Buffer Clear
7.5.3.2 Depth Buffer Resolve
7.5.3.3 Hierarchical Depth Buffer Resolve
References DBG, brw_context::gen, gen6_blorp_hiz_exec(), and gen8_hiz_exec().
Referenced by brw_fast_clear_depth(), intel_miptree_all_slices_resolve(), and intel_miptree_slice_resolve().