Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_conditional_render.c File Reference
Support for conditional rendering based on query objects (GL_NV_conditional_render, GL_ARB_conditional_render_inverted) on Gen7+.
#include "main/imports.h"
#include "main/condrender.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
Functions
static void set_predicate_enable (struct brw_context *brw, bool value)
static void set_predicate_for_overflow_query (struct brw_context *brw, struct brw_query_object *query, int stream_start, int count)
static void set_predicate_for_occlusion_query (struct brw_context *brw, struct brw_query_object *query)
static void set_predicate_for_result (struct brw_context *brw, struct brw_query_object *query, bool inverted)
static void brw_begin_conditional_render (struct gl_context *ctx, struct gl_query_object *q, GLenum mode)
static void brw_end_conditional_render (struct gl_context *ctx, struct gl_query_object *q)
void brw_init_conditional_render_functions (struct dd_function_table *functions)
brw_conditional_render.c
bool brw_check_conditional_render (struct brw_context *brw)
Detailed Description
Support for conditional rendering based on query objects (GL_NV_conditional_render, GL_ARB_conditional_render_inverted) on Gen7+.
Function Documentation
brw_begin_conditional_render()
static void brw_begin_conditional_render (struct gl_context * ctx, struct gl_query_object * q, GLenum mode) static
References brw_query_object::Base, brw_context(), can_do_mi_math_and_lrr(), brw_context::predicate, gl_query_object::Ready, gl_query_object::Result, brw_context::screen, set_predicate_enable(), set_predicate_for_result(), brw_context::supported, and gl_query_object::Target.
Referenced by brw_init_conditional_render_functions().
brw_check_conditional_render()
bool brw_check_conditional_render (struct brw_context * brw)
References _mesa_check_conditional_render(), BRW_PREDICATE_STATE_DONT_RENDER, can_do_mi_math_and_lrr(), gl_query_state::CondRenderQuery, brw_context::ctx, brw_context::predicate, gl_context::Query, brw_context::screen, brw_context::state, brw_context::supported, and gl_query_object::Target.
Referenced by brw_draw_prims().
brw_end_conditional_render()
static void brw_end_conditional_render (struct gl_context * ctx, struct gl_query_object * q) static
References brw_context(), BRW_PREDICATE_STATE_RENDER, brw_context::predicate, and brw_context::state.
Referenced by brw_init_conditional_render_functions().
brw_init_conditional_render_functions()
void brw_init_conditional_render_functions (struct dd_function_table * functions)
brw_conditional_render.c
References dd_function_table::BeginConditionalRender, brw_begin_conditional_render(), brw_end_conditional_render(), and dd_function_table::EndConditionalRender.
Referenced by brw_init_driver_functions().
set_predicate_enable()
static void set_predicate_enable (struct brw_context * brw, bool value) static
References BRW_PREDICATE_STATE_DONT_RENDER, BRW_PREDICATE_STATE_RENDER, brw_context::predicate, and brw_context::state.
Referenced by brw_begin_conditional_render().
set_predicate_for_occlusion_query()
static void set_predicate_for_occlusion_query (struct brw_context * brw, struct brw_query_object * query) static
References brw_query_object::bo, brw_load_register_mem64(), MI_PREDICATE_SRC0, and MI_PREDICATE_SRC1.
Referenced by set_predicate_for_result().
set_predicate_for_overflow_query()
static void set_predicate_for_overflow_query (struct brw_context * brw, struct brw_query_object * query, int stream_start, int count) static
References brw_load_register_imm64(), brw_load_register_reg64(), HSW_CS_GPR, hsw_overflow_result_to_gpr0(), MI_PREDICATE_SRC0, and MI_PREDICATE_SRC1.
Referenced by set_predicate_for_result().
set_predicate_for_result()
static void set_predicate_for_result (struct brw_context * brw, struct brw_query_object * query, bool inverted) static
References ADVANCE_BATCH, brw_query_object::Base, BEGIN_BATCH, brw_query_object::bo, brw_emit_pipe_control_flush(), BRW_PREDICATE_STATE_USE_BIT, GEN7_MI_PREDICATE, MAX_VERTEX_STREAMS, MI_PREDICATE_COMBINEOP_SET, MI_PREDICATE_COMPAREOP_SRCS_EQUAL, MI_PREDICATE_LOADOP_LOAD, MI_PREDICATE_LOADOP_LOADINV, OUT_BATCH, PIPE_CONTROL_FLUSH_ENABLE, brw_context::predicate, set_predicate_for_occlusion_query(), set_predicate_for_overflow_query(), brw_context::state, and gl_query_object::Target.
Referenced by brw_begin_conditional_render().