Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip_unfilled.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "program/program.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_clip.h"
Functions
static void compute_tri_direction (struct brw_clip_compile *c)
static void cull_direction (struct brw_clip_compile *c)
static void copy_bfc (struct brw_clip_compile *c)
static void compute_offset (struct brw_clip_compile *c)
static void merge_edgeflags (struct brw_clip_compile *c)
static void apply_one_offset (struct brw_clip_compile *c, struct brw_indirect vert)
static void emit_lines (struct brw_clip_compile *c, bool do_offset)
static void emit_points (struct brw_clip_compile *c, bool do_offset)
static void emit_primitives (struct brw_clip_compile *c, GLuint mode, bool do_offset)
static void emit_unfilled_primitives (struct brw_clip_compile *c)
static void check_nr_verts (struct brw_clip_compile *c)
void brw_emit_unfilled_clip (struct brw_clip_compile *c)
Function Documentation
apply_one_offset()
static void apply_one_offset (struct brw_clip_compile * c, struct brw_indirect vert) static
References brw_clip_compile::func, GLuint, brw_clip_compile::offset, brw_clip_compile::reg, and brw_clip_compile::vue_map.
Referenced by emit_lines(), and emit_points().
brw_emit_unfilled_clip()
void brw_emit_unfilled_clip (struct brw_clip_compile * c)
References brw_clip_have_varying(), brw_clip_init_clipmask(), brw_clip_init_ff_sync(), brw_clip_init_planes(), brw_clip_kill_thread(), brw_clip_tri(), brw_clip_tri_alloc_regs(), brw_clip_tri_flat_shade(), brw_clip_tri_init_vertices(), check_nr_verts(), CLIP_CULL, compute_offset(), compute_tri_direction(), brw_clip_prog_key::contains_flat_varying, copy_bfc(), brw_clip_prog_key::copy_bfc_ccw, brw_clip_prog_key::copy_bfc_cw, cull_direction(), emit_unfilled_primitives(), brw_clip_prog_key::fill_ccw, brw_clip_prog_key::fill_cw, brw_clip_compile::func, brw_clip_compile::key, merge_edgeflags(), brw_clip_compile::need_direction, brw_clip_prog_key::nr_userclip, brw_clip_prog_key::offset_ccw, brw_clip_prog_key::offset_cw, brw_clip_compile::planemask, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), and compile_clip_prog().
check_nr_verts()
static void check_nr_verts (struct brw_clip_compile * c) static
References brw_clip_kill_thread(), brw_clip_compile::func, brw_clip_compile::nr_verts, and brw_clip_compile::reg.
Referenced by brw_emit_unfilled_clip().
compute_offset()
static void compute_offset (struct brw_clip_compile * c) static
References brw_clip_compile::dir, brw_clip_compile::func, brw_clip_compile::key, brw_clip_compile::offset, brw_clip_prog_key::offset_clamp, brw_clip_prog_key::offset_factor, brw_clip_prog_key::offset_units, and brw_clip_compile::reg.
Referenced by brw_emit_unfilled_clip().
compute_tri_direction()
static void compute_tri_direction (struct brw_clip_compile * c) static
References brw_clip_project_position(), brw_clip_compile::dir, brw_clip_compile::func, get_tmp(), GLuint, brw_clip_compile::reg, brw_clip_compile::tmp1, brw_clip_compile::vertex, and brw_clip_compile::vue_map.
Referenced by brw_emit_unfilled_clip().
copy_bfc()
static void copy_bfc (struct brw_clip_compile * c) static
References brw_clip_have_varying(), brw_clip_prog_key::copy_bfc_ccw, brw_clip_compile::dir, brw_clip_compile::func, GLuint, brw_clip_compile::key, brw_clip_compile::reg, brw_clip_compile::vertex, and brw_clip_compile::vue_map.
Referenced by brw_emit_unfilled_clip().
cull_direction()
static void cull_direction (struct brw_clip_compile * c) static
References brw_clip_kill_thread(), CLIP_CULL, brw_clip_compile::dir, brw_clip_prog_key::fill_ccw, brw_clip_prog_key::fill_cw, brw_clip_compile::func, GLuint, brw_clip_compile::key, and brw_clip_compile::reg.
Referenced by brw_emit_unfilled_clip().
emit_lines()
static void emit_lines (struct brw_clip_compile * c, bool do_offset) static
References apply_one_offset(), brw_clip_emit_vue(), brw_clip_compile::func, brw_clip_compile::inlist, brw_clip_compile::loopcount, brw_clip_compile::nr_verts, brw_clip_compile::reg, and brw_clip_compile::vue_map.
Referenced by emit_primitives().
emit_points()
static void emit_points (struct brw_clip_compile * c, bool do_offset) static
References apply_one_offset(), brw_clip_emit_vue(), brw_clip_compile::func, brw_clip_compile::inlist, brw_clip_compile::loopcount, brw_clip_compile::nr_verts, brw_clip_compile::reg, and brw_clip_compile::vue_map.
Referenced by emit_primitives().
emit_primitives()
static void emit_primitives (struct brw_clip_compile * c, GLuint mode, bool do_offset) static
References brw_clip_tri_emit_polygon(), CLIP_CULL, CLIP_FILL, CLIP_LINE, CLIP_POINT, emit_lines(), and emit_points().
Referenced by emit_unfilled_primitives().
emit_unfilled_primitives()
static void emit_unfilled_primitives (struct brw_clip_compile * c) static
References CLIP_CULL, brw_clip_compile::dir, emit_primitives(), brw_clip_prog_key::fill_ccw, brw_clip_prog_key::fill_cw, brw_clip_compile::func, brw_clip_compile::key, brw_clip_prog_key::offset_ccw, brw_clip_prog_key::offset_cw, and brw_clip_compile::reg.
Referenced by brw_emit_unfilled_clip().
merge_edgeflags()
static void merge_edgeflags (struct brw_clip_compile * c) static
References brw_clip_compile::func, PRIM_MASK, brw_clip_compile::R0, brw_clip_compile::reg, brw_clip_compile::vertex, and brw_clip_compile::vue_map.
Referenced by brw_emit_unfilled_clip().