Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_tes_surface_state.c File Reference
#include "main/mtypes.h"
#include "program/prog_parameter.h"
#include "main/shaderapi.h"
#include "brw_context.h"
#include "brw_state.h"
Functions
static void brw_upload_tes_pull_constants (struct brw_context *brw)
static void brw_upload_tes_ubo_surfaces (struct brw_context *brw)
static void brw_upload_tes_abo_surfaces (struct brw_context *brw)
static void brw_upload_tes_image_surfaces (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_tes_pull_constants
const struct brw_tracked_state brw_tes_ubo_surfaces
const struct brw_tracked_state brw_tes_abo_surfaces
const struct brw_tracked_state brw_tes_image_surfaces
Function Documentation
brw_upload_tes_abo_surfaces()
static void brw_upload_tes_abo_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_abo_surfaces(), brw_stage_state::prog_data, brw_context::tes, and brw_context::tess_eval_program.
brw_upload_tes_image_surfaces()
static void brw_upload_tes_image_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_image_surfaces(), brw_stage_state::prog_data, brw_context::tes, and brw_context::tess_eval_program.
brw_upload_tes_pull_constants()
static void brw_upload_tes_pull_constants (struct brw_context * brw) static
References _mesa_shader_write_subroutine_indices(), brw_context::base, BRW_NEW_TES_CONSTBUF, brw_upload_pull_constants(), brw_context::ctx, if(), brw_stage_state::prog_data, brw_program::program, brw_context::tes, and brw_context::tess_eval_program.
brw_upload_tes_ubo_surfaces()
static void brw_upload_tes_ubo_surfaces (struct brw_context * brw) static
References gl_context::_Shader, brw_context::base, brw_upload_ubo_surfaces(), brw_context::ctx, gl_pipeline_object::CurrentProgram, brw_stage_state::prog_data, and brw_context::tes.
Variable Documentation
brw_tes_abo_surfaces
const struct brw_tracked_state brw_tes_abo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_ATOMIC_BUFFER |
             BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_TES_PROG_DATA,
   },
   .emit = brw_upload_tes_abo_surfaces,
}
brw_tes_image_surfaces
const struct brw_tracked_state brw_tes_image_surfaces
Initial value:
= {
   .dirty = {
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_IMAGE_UNITS |
             BRW_NEW_TESS_PROGRAMS |
             BRW_NEW_TES_PROG_DATA,
   },
   .emit = brw_upload_tes_image_surfaces,
}
brw_tes_pull_constants
const struct brw_tracked_state brw_tes_pull_constants
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_TES_PROG_DATA |
             BRW_NEW_TESS_PROGRAMS,
   },
   .emit = brw_upload_tes_pull_constants,
}
brw_tes_ubo_surfaces
const struct brw_tracked_state brw_tes_ubo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_TES_PROG_DATA |
             BRW_NEW_UNIFORM_BUFFER,
   },
   .emit = brw_upload_tes_ubo_surfaces,
}