Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_program.h File Reference
#include "compiler/brw_compiler.h"
Functions
bool brw_do_channel_expressions (struct exec_list *instructions)
bool brw_do_vector_splitting (struct exec_list *instructions)
struct nir_shader * brw_create_nir (struct brw_context *brw, const struct gl_shader_program *shader_prog, struct gl_program *prog, gl_shader_stage stage, bool is_scalar)
void brw_setup_tex_for_precompile (struct brw_context *brw, struct brw_sampler_prog_key_data *tex, struct gl_program *prog)
void brw_populate_sampler_prog_key_data (struct gl_context *ctx, const struct gl_program *prog, struct brw_sampler_prog_key_data *key)
bool brw_debug_recompile_sampler_key (struct brw_context *brw, const struct brw_sampler_prog_key_data *old_key, const struct brw_sampler_prog_key_data *key)
uint32_t brw_assign_common_binding_table_offsets (const struct gen_device_info *devinfo, const struct gl_program *prog, struct brw_stage_prog_data *stage_prog_data, uint32_t next_binding_table_offset)
Sets up the starting offsets for the groups of binding table entries common to all pipeline stages.
void brw_stage_prog_data_free (const void *prog_data)
void brw_dump_arb_asm (const char *stage, struct gl_program *prog)
bool brw_vs_precompile (struct gl_context *ctx, struct gl_program *prog)
bool brw_tcs_precompile (struct gl_context *ctx, struct gl_shader_program *shader_prog, struct gl_program *prog)
bool brw_tes_precompile (struct gl_context *ctx, struct gl_shader_program *shader_prog, struct gl_program *prog)
bool brw_gs_precompile (struct gl_context *ctx, struct gl_program *prog)
bool brw_fs_precompile (struct gl_context *ctx, struct gl_program *prog)
bool brw_cs_precompile (struct gl_context *ctx, struct gl_program *prog)
GLboolean brw_link_shader (struct gl_context *ctx, struct gl_shader_program *prog)
void brw_upload_tcs_prog (struct brw_context *brw)
void brw_tcs_populate_key (struct brw_context *brw, struct brw_tcs_prog_key *key)
void brw_upload_tes_prog (struct brw_context *brw)
void brw_tes_populate_key (struct brw_context *brw, struct brw_tes_prog_key *key)
Function Documentation
brw_assign_common_binding_table_offsets()
uint32_t brw_assign_common_binding_table_offsets (const struct gen_device_info * devinfo, const struct gl_program * prog, struct brw_stage_prog_data * stage_prog_data, uint32_t next_binding_table_offset)
Sets up the starting offsets for the groups of binding table entries common to all pipeline stages.
Unused groups are initialized to 0xd0d0d0d0 to make it obvious that they're unused but also make sure that addition of small offsets to them will trigger some of our asserts that surface indices are < BRW_MAX_SURFACES.
References BRW_MAX_SSBO, BRW_MAX_SURFACES, BRW_MAX_UBO, gl_program::info, gl_program::nir, and gl_program::SamplersUsed.
Referenced by assign_cs_binding_table_offsets(), assign_fs_binding_table_offsets(), assign_gs_binding_table_offsets(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), and brw_codegen_vs_prog().
brw_create_nir()
struct nir_shader* brw_create_nir (struct brw_context * brw, const struct gl_shader_program * shader_prog, struct gl_program * prog, gl_shader_stage stage, bool is_scalar)
References brw_nir_lower_uniforms(), intel_screen::compiler, gl_context::Const, brw_context::ctx, glsl_to_nir(), gl_program::info, gl_shader_compiler_options::NirOptions, gl_program::Parameters, brw_context::screen, gl_constants::ShaderCompilerOptions, and void.
Referenced by brw_link_shader(), and brwProgramStringNotify().
brw_cs_precompile()
bool brw_cs_precompile (struct gl_context * ctx, struct gl_program * prog)
References brw_context::base, brw_codegen_cs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_context::cs, brw_program::id, brw_stage_state::prog_data, and brw_stage_state::prog_offset.
Referenced by brw_shader_precompile().
brw_debug_recompile_sampler_key()
bool brw_debug_recompile_sampler_key (struct brw_context * brw, const struct brw_sampler_prog_key_data * old_key, const struct brw_sampler_prog_key_data * key)
References key_debug(), and MAX_SAMPLERS.
Referenced by brw_gs_debug_recompile(), brw_tcs_debug_recompile(), brw_tes_debug_recompile(), brw_vs_debug_recompile(), and brw_wm_debug_recompile().
brw_do_channel_expressions()
bool brw_do_channel_expressions (struct exec_list * instructions)
References channel_expressions_predicate(), do_expression_flattening(), ir_channel_expressions_visitor::progress, and visit_list_elements().
Referenced by process_glsl_ir().
brw_do_vector_splitting()
bool brw_do_vector_splitting (struct exec_list * instructions)
References variable_entry::components, debug, ir_vector_reference_visitor::ht, if(), variable_entry::mem_ctx, variable_entry::var, visit_list_elements(), and variable_entry::whole_vector_access.
Referenced by process_glsl_ir().
brw_dump_arb_asm()
void brw_dump_arb_asm (const char * stage, struct gl_program * prog)
References gl_program::Id.
Referenced by brw_codegen_vs_prog(), and brw_codegen_wm_prog().
brw_fs_precompile()
bool brw_fs_precompile (struct gl_context * ctx, struct gl_program * prog)
References _mesa_bitcount_64(), brw_context::base, BITFIELD64_BIT, brw_codegen_wm_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), intel_screen::devinfo, gl_context::Extensions, brw_context::gen, brw_program::id, gl_program::info, gl_extensions::MESA_shader_framebuffer_fetch, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::screen, and brw_context::wm.
Referenced by brw_shader_precompile(), and brwProgramStringNotify().
brw_gs_precompile()
bool brw_gs_precompile (struct gl_context * ctx, struct gl_program * prog)
References brw_context::base, brw_codegen_gs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_context::gs, brw_program::id, brw_stage_state::prog_data, and brw_stage_state::prog_offset.
Referenced by brw_shader_precompile().
brw_link_shader()
GLboolean brw_link_shader (struct gl_context * ctx, struct gl_shader_program * prog)
References gl_shader_program::_LinkedShaders, _mesa_copy_linked_program_data(), _mesa_print_ir(), _mesa_update_shader_textures_used(), gl_context::_Shader, brw_context(), brw_create_nir(), brw_shader_precompile(), build_program_resource_list(), intel_screen::compiler, gl_pipeline_object::Flags, GLSL_DUMP, gl_linked_shader::ir, gl_shader_program::Name, gl_program::nir, gl_shader_program::NumShaders, gl_program::Parameters, brw_context::precompile, process_glsl_ir(), gl_linked_shader::Program, brw_context::screen, gl_shader_program::SeparateShader, gl_shader_program::Shaders, gl_linked_shader::shadow_samplers, gl_program::ShadowSamplers, gl_shader::Source, gl_linked_shader::Stage, gl_shader::Stage, and unify_interfaces().
Referenced by brwInitFragProgFuncs().
brw_populate_sampler_prog_key_data()
void brw_populate_sampler_prog_key_data (struct gl_context * ctx, const struct gl_program * prog, struct brw_sampler_prog_key_data * key)
References gl_texture_image::_BaseFormat, gl_texture_unit::_Current, gl_texture_object::_Swizzle, gl_texture_object::BaseLevel, brw_context(), brw_get_texture_swizzle(), intel_image_format::components, gl_texture_object::DepthMode, brw_context::gen, gen6_gather_workaround(), GL_TEXTURE_EXTERNAL_OES, gl_texture_object::Image, intel_texture_object(), gl_texture_image::InternalFormat, brw_context::is_haswell, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, intel_texture_object::mt, gl_program::nir, intel_texture_object::planar_format, gl_program::SamplersUsed, gl_program::SamplerUnits, gl_texture_object::Target, gl_context::Texture, gl_texture_attrib::Unit, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by brw_cs_populate_key(), brw_gs_populate_key(), brw_tcs_populate_key(), brw_tes_populate_key(), brw_vs_populate_key(), and brw_wm_populate_key().
brw_setup_tex_for_precompile()
void brw_setup_tex_for_precompile (struct brw_context * brw, struct brw_sampler_prog_key_data * tex, struct gl_program * prog)
References brw_context::gen, brw_context::is_haswell, gl_program::SamplersUsed, and gl_program::ShadowSamplers.
Referenced by brw_cs_precompile(), brw_fs_precompile(), brw_gs_precompile(), brw_tcs_precompile(), brw_tes_precompile(), and brw_vs_precompile().
brw_stage_prog_data_free()
void brw_stage_prog_data_free (const void * prog_data)
Referenced by brw_clear_cache().
brw_tcs_populate_key()
void brw_tcs_populate_key (struct brw_context * brw, struct brw_tcs_prog_key * key)
References brw_populate_sampler_prog_key_data(), brw_context::ctx, brw_context::gen, brw_program::id, gl_program::info, gl_tess_ctrl_program_state::patch_vertices, brw_program::program, brw_context::tess_ctrl_program, brw_context::tess_eval_program, and gl_context::TessCtrlProgram.
Referenced by brw_upload_tcs_prog().
brw_tcs_precompile()
bool brw_tcs_precompile (struct gl_context * ctx, struct gl_shader_program * shader_prog, struct gl_program * prog)
References gl_shader_program::_LinkedShaders, brw_context::base, brw_codegen_tcs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_context::gen, brw_program::id, gl_program::info, gl_program::nir, brw_stage_state::prog_data, brw_stage_state::prog_offset, gl_linked_shader::Program, and brw_context::tcs.
Referenced by brw_shader_precompile().
brw_tes_populate_key()
void brw_tes_populate_key (struct brw_context * brw, struct brw_tes_prog_key * key)
References brw_populate_sampler_prog_key_data(), brw_context::ctx, gl_program::info, brw_program::program, brw_context::tess_ctrl_program, and brw_context::tess_eval_program.
Referenced by brw_upload_tes_prog().
brw_tes_precompile()
bool brw_tes_precompile (struct gl_context * ctx, struct gl_shader_program * shader_prog, struct gl_program * prog)
References gl_shader_program::_LinkedShaders, brw_context::base, brw_codegen_tes_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_program::id, gl_program::nir, brw_stage_state::prog_data, brw_stage_state::prog_offset, gl_linked_shader::Program, and brw_context::tes.
Referenced by brw_shader_precompile().
brw_upload_tcs_prog()
void brw_upload_tcs_prog (struct brw_context * brw)
References _NEW_TEXTURE, brw_context::base, BRW_CACHE_TCS_PROG, brw_codegen_tcs_prog(), BRW_NEW_PATCH_PRIMITIVE, BRW_NEW_TESS_PROGRAMS, brw_search_cache(), brw_state_dirty(), brw_tcs_populate_key(), brw_context::cache, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::tcs, brw_context::tess_ctrl_program, brw_context::tess_eval_program, and void.
Referenced by brw_upload_tess_programs().
brw_upload_tes_prog()
void brw_upload_tes_prog (struct brw_context * brw)
References _NEW_TEXTURE, brw_context::base, BRW_CACHE_TES_PROG, brw_codegen_tes_prog(), BRW_NEW_TESS_PROGRAMS, brw_search_cache(), brw_state_dirty(), brw_tes_populate_key(), brw_context::cache, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::tes, brw_context::tess_eval_program, and void.
Referenced by brw_upload_tess_programs().
brw_vs_precompile()
bool brw_vs_precompile (struct gl_context * ctx, struct gl_program * prog)
References brw_context::base, brw_codegen_vs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_program::id, gl_program::info, brw_stage_state::prog_data, brw_stage_state::prog_offset, and brw_context::vs.
Referenced by brw_shader_precompile(), and brwProgramStringNotify().