Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_curbe.c File Reference
Push constant handling for gen4/5.
#include "compiler/nir/nir.h"
#include "main/context.h"
#include "main/macros.h"
#include "main/enums.h"
#include "program/prog_parameter.h"
#include "program/prog_print.h"
#include "program/prog_statevars.h"
#include "util/bitscan.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "brw_util.h"
Functions
static void calculate_curbe_offsets (struct brw_context *brw)
Partition the CURBE between the various users of constant values.
void brw_upload_cs_urb_state (struct brw_context *brw)
Uploads the CS_URB_STATE packet.
static void brw_upload_constant_buffer (struct brw_context *brw)
Gathers together all the uniform values into a block of memory to be uploaded into the CURBE, then emits the state packet telling the hardware the new location.
Variables
const struct brw_tracked_state brw_curbe_offsets
static const GLfloat fixed_plane [6][4]
const struct brw_tracked_state brw_constant_buffer
Detailed Description
Push constant handling for gen4/5.
Push constants are constant values (such as GLSL uniforms) that are pre-loaded into a shader stage's register space at thread spawn time. On gen4 and gen5, we create a blob in memory containing all the push constants for all the stages in order. At CMD_CONST_BUFFER time that blob is loaded into URB space as a constant URB entry (CURBE) so that it can be accessed quickly at thread setup time. Each individual fixed function unit's state (brw_vs_state.c for example) tells the hardware which subset of the CURBE it wants in its register space, and we calculate those areas here under the BRW_NEW_CURBE_OFFSETS state flag. The brw_urb.c allocation will control how many CURBEs can be loaded into the hardware at once before a pipeline stall occurs at CMD_CONST_BUFFER time.
On gen6+, constant handling becomes a much simpler set of per-unit state. See gen6_upload_vec4_push_constants() in gen6_vs_state.c for that code.
Function Documentation
brw_upload_constant_buffer()
static void brw_upload_constant_buffer (struct brw_context * brw) static
Gathers together all the uniform values into a block of memory to be uploaded into the CURBE, then emits the state packet telling the hardware the new location.
References _3DSTATE_GLOBAL_DEPTH_OFFSET_CLAMP, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_select_clip_planes(), brw_context::clip_size, brw_context::clip_start, gl_transform_attrib::ClipPlanesEnabled, CMD_CONST_BUFFER, brw_context::ctx, brw_context::curbe, brw_context::curbe_bo, brw_context::curbe_offset, fixed_plane, brw_context::fragment_program, brw_context::gen, GLuint, gl_program::info, intel_upload_space(), brw_context::is_g4x, OUT_BATCH, OUT_RELOC, gl_program::Parameters, brw_stage_state::prog_data, brw_context::total_size, gl_context::Transform, brw_context::vertex_program, brw_context::vs, brw_context::vs_size, brw_context::vs_start, brw_context::wm, brw_context::wm_size, and brw_context::wm_start.
brw_upload_cs_urb_state()
void brw_upload_cs_urb_state (struct brw_context * brw)
Uploads the CS_URB_STATE packet.
Just like brw_vs_state.c and brw_wm_state.c define a URB entry size and number of entries for their stages, constant buffers do so using this state packet. Having multiple CURBEs in the URB at the same time allows the hardware to avoid a pipeline stall between primitives using different constant buffer contents.
References ADVANCE_BATCH, BEGIN_BATCH, CMD_CS_URB_STATE, brw_context::csize, brw_context::nr_cs_entries, OUT_BATCH, and brw_context::urb.
Referenced by key_debug(), and upload_psp_urb_cbs().
calculate_curbe_offsets()
static void calculate_curbe_offsets (struct brw_context * brw) static
Partition the CURBE between the various users of constant values.
If the users all fit within the previous allocatation, we avoid changing the layout because that means reuploading all unit state and uploading new constant buffers.
References _mesa_bitcount(), brw_context::base, BRW_NEW_CURBE_OFFSETS, brw_context::clip_size, brw_context::clip_start, gl_transform_attrib::ClipPlanesEnabled, brw_context::ctx, brw_context::curbe, GLuint, gl_context::NewDriverState, brw_stage_state::prog_data, brw_context::total_size, gl_context::Transform, brw_context::vs, brw_context::vs_size, brw_context::vs_start, brw_context::wm, brw_context::wm_size, and brw_context::wm_start.
Variable Documentation
brw_constant_buffer
const struct brw_tracked_state brw_constant_buffer
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw  = BRW_NEW_BATCH |
              BRW_NEW_BLORP |
              BRW_NEW_CURBE_OFFSETS |
              BRW_NEW_FRAGMENT_PROGRAM |
              BRW_NEW_FS_PROG_DATA |
              BRW_NEW_PSP |
              BRW_NEW_URB_FENCE |
              BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_upload_constant_buffer,
}
brw_curbe_offsets
const struct brw_tracked_state brw_curbe_offsets
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TRANSFORM,
      .brw  = BRW_NEW_CONTEXT |
              BRW_NEW_BLORP |
              BRW_NEW_FS_PROG_DATA |
              BRW_NEW_VS_PROG_DATA,
   },
   .emit = calculate_curbe_offsets
}
fixed_plane
const GLfloat fixed_plane[6][4] static
Initial value:
= {
   { 0,    0,   -1, 1 },
   { 0,    0,    1, 1 },
   { 0,   -1,    0, 1 },
   { 0,    1,    0, 1 },
   {-1,    0,    0, 1 },
   { 1,    0,    0, 1 }
}
Referenced by brw_upload_constant_buffer().