Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_wm_surface_state.c File Reference
#include "compiler/nir/nir.h"
#include "main/context.h"
#include "main/blend.h"
#include "main/mtypes.h"
#include "main/samplerobj.h"
#include "main/shaderimage.h"
#include "main/teximage.h"
#include "program/prog_parameter.h"
#include "program/prog_instruction.h"
#include "main/framebuffer.h"
#include "main/shaderapi.h"
#include "isl/isl.h"
#include "intel_mipmap_tree.h"
#include "intel_batchbuffer.h"
#include "intel_tex.h"
#include "intel_fbo.h"
#include "intel_buffer_objects.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_wm.h"
Enumerations
enum { INTEL_RENDERBUFFER_LAYERED = 1 << 0, INTEL_AUX_BUFFER_DISABLED = 1 << 1 }
Functions
static void brw_emit_surface_state (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t flags, GLenum target, struct isl_view view, uint32_t mocs, uint32_t *surf_offset, int surf_index, unsigned read_domains, unsigned write_domains)
uint32_t brw_update_renderbuffer_surface (struct brw_context *brw, struct gl_renderbuffer *rb, uint32_t flags, unsigned unit, uint32_t surf_index)
GLuint translate_tex_target (GLenum target)
uint32_t brw_get_surface_tiling_bits (uint32_t tiling)
uint32_t brw_get_surface_num_multisamples (unsigned num_samples)
int brw_get_texture_swizzle (const struct gl_context *ctx, const struct gl_texture_object *t)
Compute the combination of DEPTH_TEXTURE_MODE and EXT_texture_swizzle swizzling.
static unsigned swizzle_to_scs (GLenum swizzle, bool need_green_to_blue)
Convert an swizzle enumeration (i.e.
static unsigned brw_find_matching_rb (const struct gl_framebuffer *fb, const struct intel_mipmap_tree *mt)
static bool brw_texture_view_sane (const struct brw_context *brw, const struct intel_mipmap_tree *mt, const struct isl_view *view)
static bool brw_disable_aux_surface (const struct brw_context *brw, const struct intel_mipmap_tree *mt, const struct isl_view *view)
void brw_update_texture_surface (struct gl_context *ctx, unsigned unit, uint32_t *surf_offset, bool for_gather, uint32_t plane)
void brw_emit_buffer_surface_state (struct brw_context *brw, uint32_t *out_offset, drm_intel_bo *bo, unsigned buffer_offset, unsigned surface_format, unsigned buffer_size, unsigned pitch, bool rw)
void brw_update_buffer_texture_surface (struct gl_context *ctx, unsigned unit, uint32_t *surf_offset)
void brw_create_constant_surface (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint32_t size, uint32_t *out_offset)
Create the constant buffer surface.
void brw_create_buffer_surface (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint32_t size, uint32_t *out_offset)
Create the buffer surface.
void brw_update_sol_surface (struct brw_context *brw, struct gl_buffer_object *buffer_obj, uint32_t *out_offset, unsigned num_vector_components, unsigned stride_dwords, unsigned offset_dwords)
Set up a binding table entry for use by stream output logic (transform feedback).
static void brw_upload_wm_pull_constants (struct brw_context *brw)
static void brw_emit_null_surface_state (struct brw_context *brw, unsigned width, unsigned height, unsigned samples, uint32_t *out_offset)
Creates a null renderbuffer surface.
static uint32_t gen4_update_renderbuffer_surface (struct brw_context *brw, struct gl_renderbuffer *rb, uint32_t flags, unsigned unit, uint32_t surf_index)
Sets up a surface state structure to point at the given region.
void brw_update_renderbuffer_surfaces (struct brw_context *brw, const struct gl_framebuffer *fb, uint32_t render_target_start, uint32_t *surf_offset)
Construct SURFACE_STATE objects for renderbuffers/draw buffers.
static void update_renderbuffer_surfaces (struct brw_context *brw)
static void update_renderbuffer_read_surfaces (struct brw_context *brw)
static void update_stage_texture_surfaces (struct brw_context *brw, const struct gl_program *prog, struct brw_stage_state *stage_state, bool for_gather, uint32_t plane)
static void brw_update_texture_surfaces (struct brw_context *brw)
Construct SURFACE_STATE objects for enabled textures.
static void brw_update_cs_texture_surfaces (struct brw_context *brw)
void brw_upload_ubo_surfaces (struct brw_context *brw, struct gl_program *prog, struct brw_stage_state *stage_state, struct brw_stage_prog_data *prog_data)
static void brw_upload_wm_ubo_surfaces (struct brw_context *brw)
static void brw_upload_cs_ubo_surfaces (struct brw_context *brw)
void brw_upload_abo_surfaces (struct brw_context *brw, const struct gl_program *prog, struct brw_stage_state *stage_state, struct brw_stage_prog_data *prog_data)
static void brw_upload_wm_abo_surfaces (struct brw_context *brw)
static void brw_upload_cs_abo_surfaces (struct brw_context *brw)
static void brw_upload_cs_image_surfaces (struct brw_context *brw)
static uint32_t get_image_format (struct brw_context *brw, mesa_format format, GLenum access)
static void update_default_image_param (struct brw_context *brw, struct gl_image_unit *u, unsigned surface_idx, struct brw_image_param *param)
static void update_buffer_image_param (struct brw_context *brw, struct gl_image_unit *u, unsigned surface_idx, struct brw_image_param *param)
static void update_texture_image_param (struct brw_context *brw, struct gl_image_unit *u, unsigned surface_idx, struct brw_image_param *param)
static void update_image_surface (struct brw_context *brw, struct gl_image_unit *u, GLenum access, unsigned surface_idx, uint32_t *surf_offset, struct brw_image_param *param)
void brw_upload_image_surfaces (struct brw_context *brw, const struct gl_program *prog, struct brw_stage_state *stage_state, struct brw_stage_prog_data *prog_data)
static void brw_upload_wm_image_surfaces (struct brw_context *brw)
void gen4_init_vtable_surface_functions (struct brw_context *brw)
void gen6_init_vtable_surface_functions (struct brw_context *brw)
static void brw_upload_cs_work_groups_surface (struct brw_context *brw)
Variables
uint32_t tex_mocs []
uint32_t rb_mocs []
const struct brw_tracked_state brw_wm_pull_constants
const struct brw_tracked_state brw_renderbuffer_surfaces
const struct brw_tracked_state gen6_renderbuffer_surfaces
const struct brw_tracked_state brw_renderbuffer_read_surfaces
const struct brw_tracked_state brw_texture_surfaces
const struct brw_tracked_state brw_cs_texture_surfaces
const struct brw_tracked_state brw_wm_ubo_surfaces
const struct brw_tracked_state brw_cs_ubo_surfaces
const struct brw_tracked_state brw_wm_abo_surfaces
const struct brw_tracked_state brw_cs_abo_surfaces
const struct brw_tracked_state brw_cs_image_surfaces
const struct brw_tracked_state brw_wm_image_surfaces
const struct brw_tracked_state brw_cs_work_groups_surface
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
INTEL_RENDERBUFFER_LAYERED
INTEL_AUX_BUFFER_DISABLED
Function Documentation
brw_create_buffer_surface()
void brw_create_buffer_surface (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint32_t size, uint32_t * out_offset)
Create the buffer surface.
Shader buffer variables will be read from / write to this buffer with Data Port Read/Write instructions/messages.
References brw_emit_buffer_surface_state().
Referenced by brw_get_index_type(), and brw_upload_ubo_surfaces().
brw_create_constant_surface()
void brw_create_constant_surface (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint32_t size, uint32_t * out_offset)
Create the constant buffer surface.
Vertex/fragment shader constants will be read from this buffer with Data Port Read instructions/messages.
References brw_emit_buffer_surface_state().
Referenced by brw_get_index_type(), brw_upload_pull_constants(), and brw_upload_ubo_surfaces().
brw_disable_aux_surface()
static bool brw_disable_aux_surface (const struct brw_context * brw, const struct intel_mipmap_tree * mt, const struct isl_view * view) static
References gl_framebuffer::_NumColorDrawBuffers, brw_find_matching_rb(), brw_context::ctx, brw_context::draw_aux_buffer_disabled, gl_context::DrawBuffer, intel_miptree_has_color_unresolved(), and intel_miptree_is_lossless_compressed().
Referenced by brw_update_texture_surface().
brw_emit_buffer_surface_state()
void brw_emit_buffer_surface_state (struct brw_context * brw, uint32_t * out_offset, drm_intel_bo * bo, unsigned buffer_offset, unsigned surface_format, unsigned buffer_size, unsigned pitch, bool rw)
References brw_context::batch, intel_batchbuffer::bo, brw_state_batch(), brw_context::gen, brw_context::isl_dev, and tex_mocs.
Referenced by brw_create_buffer_surface(), brw_create_constant_surface(), brw_update_buffer_texture_surface(), brw_upload_abo_surfaces(), brw_upload_binding_table(), brw_upload_cs_state(), brw_upload_cs_work_groups_surface(), and update_image_surface().
brw_emit_null_surface_state()
static void brw_emit_null_surface_state (struct brw_context * brw, unsigned width, unsigned height, unsigned samples, uint32_t * out_offset) static
Creates a null renderbuffer surface.
This is used when the shader doesn't write to any color output. An FB write to target 0 will still be emitted, because that's how the thread is terminated (and computed depth is returned), so we need to have the hardware discard the target 0 color output..
References brw_context::batch, intel_batchbuffer::bo, brw_get_scratch_bo(), brw_get_surface_num_multisamples(), brw_state_batch(), BRW_SURFACE_2D, BRW_SURFACE_FORMAT_SHIFT, BRW_SURFACE_HEIGHT_SHIFT, BRW_SURFACE_NULL, BRW_SURFACE_PITCH_SHIFT, BRW_SURFACE_TILED, BRW_SURFACE_TILED_Y, BRW_SURFACE_TYPE_SHIFT, BRW_SURFACE_WIDTH_SHIFT, BRW_SURFACE_WRITEDISABLE_A_SHIFT, BRW_SURFACE_WRITEDISABLE_B_SHIFT, BRW_SURFACE_WRITEDISABLE_G_SHIFT, BRW_SURFACE_WRITEDISABLE_R_SHIFT, brw_context::gen, brw_context::multisampled_null_render_target_bo, and brw_context::wm.
Referenced by gen4_init_vtable_surface_functions().
brw_emit_surface_state()
static void brw_emit_surface_state (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t flags, GLenum target, struct isl_view view, uint32_t mocs, uint32_t * surf_offset, int surf_index, unsigned read_domains, unsigned write_domains) static
References brw_context::batch, intel_batchbuffer::bo, brw_state_batch(), intel_screen::devinfo, get_isl_dim_layout(), get_isl_surf_dim(), brw_context::has_surface_tile_offset, INTEL_AUX_BUFFER_DISABLED, intel_miptree_get_aux_isl_surf(), intel_miptree_get_isl_clear_color(), intel_miptree_get_isl_surf(), intel_miptree_get_tile_offsets(), intel_miptree_sample_with_hiz(), brw_context::isl_dev, and brw_context::screen.
Referenced by brw_update_renderbuffer_surface(), brw_update_texture_surface(), update_image_surface(), and update_renderbuffer_read_surfaces().
brw_find_matching_rb()
static unsigned brw_find_matching_rb (const struct gl_framebuffer * fb, const struct intel_mipmap_tree * mt) static
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, intel_renderbuffer(), and intel_renderbuffer::mt.
Referenced by brw_disable_aux_surface(), and brw_texture_view_sane().
brw_get_surface_num_multisamples()
uint32_t brw_get_surface_num_multisamples (unsigned num_samples)
References BRW_SURFACE_MULTISAMPLECOUNT_1, and BRW_SURFACE_MULTISAMPLECOUNT_4.
Referenced by brw_emit_null_surface_state(), and gen4_update_renderbuffer_surface().
brw_get_surface_tiling_bits()
uint32_t brw_get_surface_tiling_bits (uint32_t tiling)
References BRW_SURFACE_TILED, and BRW_SURFACE_TILED_Y.
Referenced by gen4_update_renderbuffer_surface().
brw_get_texture_swizzle()
int brw_get_texture_swizzle (const struct gl_context * ctx, const struct gl_texture_object * t)
Compute the combination of DEPTH_TEXTURE_MODE and EXT_texture_swizzle swizzling.
References gl_texture_image::_BaseFormat, gl_texture_object::_IsIntegerFormat, _mesa_get_format_bits(), _mesa_get_format_datatype(), gl_texture_object::_Swizzle, gl_texture_object::BaseLevel, gl_texture_object::DepthMode, gl_texture_object::Image, gl_texture_image::InternalFormat, and gl_texture_image::TexFormat.
Referenced by brw_populate_sampler_prog_key_data(), and brw_update_texture_surface().
brw_texture_view_sane()
static bool brw_texture_view_sane (const struct brw_context * brw, const struct intel_mipmap_tree * mt, const struct isl_view * view) inline static
References gl_framebuffer::_NumColorDrawBuffers, brw_find_matching_rb(), brw_context::ctx, intel_screen::devinfo, brw_context::draw_aux_buffer_disabled, gl_context::DrawBuffer, intel_miptree_has_color_unresolved(), intel_miptree_is_lossless_compressed(), and brw_context::screen.
Referenced by brw_update_texture_surface().
brw_update_buffer_texture_surface()
void brw_update_buffer_texture_surface (struct gl_context * ctx, unsigned unit, uint32_t * surf_offset)
References gl_texture_object::_BufferObjectFormat, gl_texture_unit::_Current, _mesa_get_format_bytes(), _mesa_get_format_name(), _mesa_problem(), intel_buffer_object::Base, brw_context(), brw_emit_buffer_surface_state(), brw_isl_format_for_mesa_format(), gl_texture_object::BufferObject, gl_texture_object::BufferOffset, gl_texture_object::BufferSize, gl_context::Const, intel_buffer_object(), intel_bufferobj_buffer(), gl_constants::MaxTextureBufferSize, MESA_FORMAT_RGBA_FLOAT32, gl_buffer_object::Size, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_get_index_type(), and brw_update_texture_surface().
brw_update_cs_texture_surfaces()
static void brw_update_cs_texture_surfaces (struct brw_context * brw) static
References brw_context::base, BRW_NEW_SURFACES, brw_context::compute_program, brw_context::cs, brw_context::ctx, brw_context::gen, gl_context::NewDriverState, gl_program::nir, and update_stage_texture_surfaces().
brw_update_renderbuffer_surface()
uint32_t brw_update_renderbuffer_surface (struct brw_context * brw, struct gl_renderbuffer * rb, uint32_t flags, unsigned unit, uint32_t surf_index)
References _mesa_get_format_name(), _mesa_get_render_format(), _mesa_problem(), brw_emit_surface_state(), brw_render_target_supported(), brw_context::ctx, brw_context::format_supported_as_render_target, brw_context::gen, GLuint, INTEL_AUX_BUFFER_DISABLED, intel_rb_format(), intel_renderbuffer(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, rb_mocs, and brw_context::render_target_format.
Referenced by gen6_init_vtable_surface_functions(), gen7_init_vtable_surface_functions(), and gen8_init_vtable_surface_functions().
brw_update_renderbuffer_surfaces()
void brw_update_renderbuffer_surfaces (struct brw_context * brw, const struct gl_framebuffer * fb, uint32_t render_target_start, uint32_t * surf_offset)
Construct SURFACE_STATE objects for renderbuffers/draw buffers.
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, brw_context::draw_aux_buffer_disabled, brw_context::emit_null_surface_state, GLuint, INTEL_AUX_BUFFER_DISABLED, intel_renderbuffer(), INTEL_RENDERBUFFER_LAYERED, brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by update_renderbuffer_surfaces().
brw_update_sol_surface()
void brw_update_sol_surface (struct brw_context * brw, struct gl_buffer_object * buffer_obj, uint32_t * out_offset, unsigned num_vector_components, unsigned stride_dwords, unsigned offset_dwords)
Set up a binding table entry for use by stream output logic (transform feedback).
buffer_size_minus_1 must be less than BRW_MAX_NUM_BUFFER_ENTRIES.
References brw_context::batch, intel_batchbuffer::bo, BRW_MAX_NUM_BUFFER_ENTRIES, brw_state_batch(), BRW_SURFACE_BUFFER, BRW_SURFACE_DEPTH_SHIFT, BRW_SURFACE_FORMAT_SHIFT, BRW_SURFACE_HEIGHT_SHIFT, BRW_SURFACE_MIPLAYOUT_SHIFT, BRW_SURFACE_MIPMAPLAYOUT_BELOW, BRW_SURFACE_PITCH_SHIFT, BRW_SURFACE_RC_READ_WRITE, BRW_SURFACE_TYPE_SHIFT, BRW_SURFACE_WIDTH_SHIFT, intel_buffer_object(), intel_bufferobj_buffer(), and gl_buffer_object::Size.
Referenced by brw_get_index_type(), and gen6_update_sol_surfaces().
brw_update_texture_surface()
void brw_update_texture_surface (struct gl_context * ctx, unsigned unit, uint32_t * surf_offset, bool for_gather, uint32_t plane)
References gl_texture_unit::_Current, intel_texture_object::_Format, intel_texture_object::_MaxLevel, brw_context::base, gl_texture_object::BaseLevel, brw_context(), brw_disable_aux_surface(), brw_emit_surface_state(), brw_get_texture_swizzle(), brw_texture_view_sane(), brw_update_buffer_texture_surface(), brw_context::ctx, gl_texture_object::DepthMode, brw_context::gen, gl_texture_object::Image, gl_texture_object::Immutable, INTEL_AUX_BUFFER_DISABLED, intel_texture_object(), brw_context::is_haswell, MESA_FORMAT_S_UINT8, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_object::mt, gl_texture_object::NumLayers, gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, brw_stage_state::surf_offset, swizzle(), swizzle_to_scs(), gl_texture_object::Target, tex_mocs, gl_context::Texture, translate_tex_format(), gl_texture_attrib::Unit, and brw_context::wm.
Referenced by update_stage_texture_surfaces().
brw_update_texture_surfaces()
static void brw_update_texture_surfaces (struct brw_context * brw) static
Construct SURFACE_STATE objects for enabled textures.
References brw_context::base, BRW_NEW_SURFACES, brw_context::ctx, brw_context::fragment_program, gl_program::fs, brw_context::gen, brw_context::geometry_program, brw_context::gs, gl_context::NewDriverState, gl_program::nir, brw_context::tcs, brw_context::tes, brw_context::tess_ctrl_program, brw_context::tess_eval_program, update_stage_texture_surfaces(), brw_context::vertex_program, brw_context::vs, and brw_context::wm.
brw_upload_abo_surfaces()
void brw_upload_abo_surfaces (struct brw_context * brw, const struct gl_program * prog, struct brw_stage_state * stage_state, struct brw_stage_prog_data * prog_data)
References gl_context::AtomicBufferBindings, intel_buffer_object::Base, brw_emit_buffer_surface_state(), BRW_NEW_SURFACES, gl_atomic_buffer_binding::BufferObject, brw_context::ctx, gl_program::info, intel_buffer_object(), intel_bufferobj_buffer(), gl_context::NewDriverState, gl_atomic_buffer_binding::Offset, gl_program::sh, gl_buffer_object::Size, and brw_stage_state::surf_offset.
Referenced by brw_get_index_type(), brw_upload_cs_abo_surfaces(), brw_upload_gs_abo_surfaces(), brw_upload_tcs_abo_surfaces(), brw_upload_tes_abo_surfaces(), brw_upload_vs_abo_surfaces(), and brw_upload_wm_abo_surfaces().
brw_upload_cs_abo_surfaces()
static void brw_upload_cs_abo_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_abo_surfaces(), brw_context::compute_program, brw_context::cs, and brw_stage_state::prog_data.
brw_upload_cs_image_surfaces()
static void brw_upload_cs_image_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_image_surfaces(), brw_context::compute_program, brw_context::cs, and brw_stage_state::prog_data.
brw_upload_cs_ubo_surfaces()
static void brw_upload_cs_ubo_surfaces (struct brw_context * brw) static
References gl_context::_Shader, brw_context::base, brw_upload_ubo_surfaces(), brw_context::cs, brw_context::ctx, gl_pipeline_object::CurrentProgram, and brw_stage_state::prog_data.
brw_upload_cs_work_groups_surface()
static void brw_upload_cs_work_groups_surface (struct brw_context * brw) static
References gl_context::_Shader, brw_context::base, brw_emit_buffer_surface_state(), BRW_NEW_SURFACES, brw_context::compute, brw_context::cs, brw_context::ctx, gl_pipeline_object::CurrentProgram, GLuint, intel_upload_data(), gl_context::NewDriverState, brw_context::num_work_groups, brw_context::num_work_groups_bo, brw_context::num_work_groups_offset, brw_stage_state::prog_data, and brw_stage_state::surf_offset.
brw_upload_image_surfaces()
void brw_upload_image_surfaces (struct brw_context * brw, const struct gl_program * prog, struct brw_stage_state * stage_state, struct brw_stage_prog_data * prog_data)
References _NEW_PROGRAM_CONSTANTS, BRW_NEW_SURFACES, brw_context::ctx, gl_context::ImageUnits, gl_program::info, gl_context::NewDriverState, brw_context::NewGLState, gl_program::sh, brw_stage_state::surf_offset, and update_image_surface().
Referenced by brw_get_index_type(), brw_upload_cs_image_surfaces(), brw_upload_gs_image_surfaces(), brw_upload_tcs_image_surfaces(), brw_upload_tes_image_surfaces(), brw_upload_vs_image_surfaces(), and brw_upload_wm_image_surfaces().
brw_upload_ubo_surfaces()
void brw_upload_ubo_surfaces (struct brw_context * brw, struct gl_program * prog, struct brw_stage_state * stage_state, struct brw_stage_prog_data * prog_data)
References gl_uniform_buffer_binding::AutomaticSize, gl_shader_storage_buffer_binding::AutomaticSize, brw_create_buffer_surface(), brw_create_constant_surface(), BRW_NEW_SURFACES, gl_shader_storage_buffer_binding::BufferObject, gl_uniform_buffer_binding::BufferObject, brw_context::ctx, brw_context::emit_null_surface_state, gl_program::info, intel_buffer_object(), intel_bufferobj_buffer(), gl_context::NewDriverState, gl_shared_state::NullBufferObj, gl_shader_storage_buffer_binding::Offset, gl_uniform_buffer_binding::Offset, gl_program::sh, gl_context::ShaderStorageBufferBindings, gl_context::Shared, gl_uniform_buffer_binding::Size, gl_shader_storage_buffer_binding::Size, gl_buffer_object::Size, brw_stage_state::surf_offset, gl_context::UniformBufferBindings, and brw_context::vtbl.
Referenced by brw_get_index_type(), brw_upload_cs_ubo_surfaces(), brw_upload_gs_ubo_surfaces(), brw_upload_tcs_ubo_surfaces(), brw_upload_tes_ubo_surfaces(), brw_upload_vs_ubo_surfaces(), and brw_upload_wm_ubo_surfaces().
brw_upload_wm_abo_surfaces()
static void brw_upload_wm_abo_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_abo_surfaces(), brw_context::fragment_program, brw_stage_state::prog_data, and brw_context::wm.
brw_upload_wm_image_surfaces()
static void brw_upload_wm_image_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_image_surfaces(), brw_context::fragment_program, brw_stage_state::prog_data, and brw_context::wm.
brw_upload_wm_pull_constants()
static void brw_upload_wm_pull_constants (struct brw_context * brw) static
References _mesa_shader_write_subroutine_indices(), brw_context::base, BRW_NEW_SURFACES, brw_upload_pull_constants(), brw_context::ctx, brw_context::fragment_program, brw_stage_state::prog_data, brw_program::program, and brw_context::wm.
brw_upload_wm_ubo_surfaces()
static void brw_upload_wm_ubo_surfaces (struct brw_context * brw) static
References gl_pipeline_object::_CurrentFragmentProgram, gl_context::_Shader, brw_context::base, brw_upload_ubo_surfaces(), brw_context::ctx, brw_stage_state::prog_data, and brw_context::wm.
gen4_init_vtable_surface_functions()
void gen4_init_vtable_surface_functions (struct brw_context * brw)
References brw_emit_null_surface_state(), brw_context::emit_null_surface_state, gen4_update_renderbuffer_surface(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext(), and gen6_init_vtable_surface_functions().
gen4_update_renderbuffer_surface()
static uint32_t gen4_update_renderbuffer_surface (struct brw_context * brw, struct gl_renderbuffer * rb, uint32_t flags, unsigned unit, uint32_t surf_index) static
Sets up a surface state structure to point at the given region.
While it is only used for the front/back buffer currently, it should be usable for further buffers when doing ARB_draw_buffer support.
References gl_colorbuffer_attrib::_AdvancedBlendMode, _mesa_get_format_name(), _mesa_get_render_format(), _mesa_problem(), gl_config::alphaBits, brw_context::batch, gl_colorbuffer_attrib::BlendEnabled, intel_batchbuffer::bo, brw_get_surface_num_multisamples(), brw_get_surface_tiling_bits(), brw_state_batch(), BRW_SURFACE_2D, BRW_SURFACE_BLEND_ENABLED, BRW_SURFACE_FORMAT_SHIFT, BRW_SURFACE_HEIGHT_SHIFT, BRW_SURFACE_PITCH_SHIFT, BRW_SURFACE_TYPE_SHIFT, BRW_SURFACE_VERTICAL_ALIGN_ENABLE, BRW_SURFACE_WIDTH_SHIFT, BRW_SURFACE_WRITEDISABLE_A_SHIFT, BRW_SURFACE_WRITEDISABLE_B_SHIFT, BRW_SURFACE_WRITEDISABLE_G_SHIFT, BRW_SURFACE_WRITEDISABLE_R_SHIFT, BRW_SURFACE_X_OFFSET_SHIFT, BRW_SURFACE_Y_OFFSET_SHIFT, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, brw_context::ctx, gl_context::DrawBuffer, brw_context::format_supported_as_render_target, brw_context::gen, brw_context::has_surface_tile_offset, gl_renderbuffer::Height, INTEL_AUX_BUFFER_DISABLED, intel_rb_format(), intel_renderbuffer(), intel_renderbuffer_get_tile_offsets(), INTEL_RENDERBUFFER_LAYERED, intel_renderbuffer_move_to_temp(), intel_renderbuffer::mt, brw_context::render_target_format, gl_renderbuffer::TexImage, gl_framebuffer::Visual, and gl_renderbuffer::Width.
Referenced by gen4_init_vtable_surface_functions().
gen6_init_vtable_surface_functions()
void gen6_init_vtable_surface_functions (struct brw_context * brw)
References brw_update_renderbuffer_surface(), gen4_init_vtable_surface_functions(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext().
get_image_format()
static uint32_t get_image_format (struct brw_context * brw, mesa_format format, GLenum access) static
References brw_isl_format_for_mesa_format(), intel_screen::devinfo, and brw_context::screen.
Referenced by update_image_surface().
swizzle_to_scs()
static unsigned swizzle_to_scs (GLenum swizzle, bool need_green_to_blue) static
Convert an swizzle enumeration (i.e.
SWIZZLE_X) to one of the Gen7.5+ "Shader Channel Select" enumerations (i.e. HSW_SCS_RED). The mappings are
SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_W, SWIZZLE_ZERO, SWIZZLE_ONE 0 1 2 3 4 5 4 5 6 7 0 1 SCS_RED, SCS_GREEN, SCS_BLUE, SCS_ALPHA, SCS_ZERO, SCS_ONE
which is simply adding 4 then modding by 8 (or anding with 7).
We then may need to apply workarounds for textureGather hardware bugs.
References HSW_SCS_BLUE, and HSW_SCS_GREEN.
Referenced by brw_update_texture_surface().
translate_tex_target()
GLuint translate_tex_target (GLenum target)
References BRW_SURFACE_1D, BRW_SURFACE_2D, BRW_SURFACE_3D, BRW_SURFACE_CUBE, and GL_TEXTURE_EXTERNAL_OES.
Referenced by gen6_emit_depth_stencil_hiz(), gen7_emit_depth_stencil_hiz(), and gen8_emit_depth_stencil_hiz().
update_buffer_image_param()
static void update_buffer_image_param (struct brw_context * brw, struct gl_image_unit * u, unsigned surface_idx, struct brw_image_param * param) static
References gl_image_unit::_ActualFormat, _mesa_get_format_bytes(), gl_texture_object::BufferObject, gl_texture_object::BufferSize, gl_buffer_object::Size, gl_image_unit::TexObj, and update_default_image_param().
Referenced by update_image_surface().
update_default_image_param()
static void update_default_image_param (struct brw_context * brw, struct gl_image_unit * u, unsigned surface_idx, struct brw_image_param * param) static
Referenced by update_buffer_image_param(), update_image_surface(), and update_texture_image_param().
update_image_surface()
static void update_image_surface (struct brw_context * brw, struct gl_image_unit * u, GLenum access, unsigned surface_idx, uint32_t * surf_offset, struct brw_image_param * param) static
References gl_image_unit::_ActualFormat, gl_image_unit::_Layer, _mesa_get_format_bytes(), _mesa_is_image_unit_valid(), intel_buffer_object::Base, brw_context::base, brw_context::bo, brw_emit_buffer_surface_state(), brw_emit_surface_state(), intel_buffer_object::buffer, gl_texture_object::BufferObject, gl_texture_object::BufferOffset, brw_context::ctx, brw_context::emit_null_surface_state, brw_context::gen, get_image_format(), INTEL_AUX_BUFFER_DISABLED, intel_buffer_object(), intel_miptree_has_color_unresolved(), intel_texture_object(), gl_image_unit::Layered, gl_image_unit::Level, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_object::mt, gl_buffer_object::Size, brw_stage_state::surf_offset, gl_texture_object::Target, tex_mocs, gl_image_unit::TexObj, update_buffer_image_param(), update_default_image_param(), update_texture_image_param(), brw_context::vtbl, and brw_context::wm.
Referenced by brw_upload_image_surfaces().
update_renderbuffer_read_surfaces()
static void update_renderbuffer_read_surfaces (struct brw_context * brw) static
References gl_framebuffer::_ColorDrawBuffers, _mesa_get_render_format(), gl_framebuffer::_NumColorDrawBuffers, brw_context::base, brw_emit_surface_state(), BRW_NEW_SURFACES, brw_context::ctx, intel_screen::devinfo, brw_context::draw_aux_buffer_disabled, gl_context::DrawBuffer, brw_context::emit_null_surface_state, gl_context::Extensions, brw_context::fragment_program, brw_context::gen, gl_program::info, INTEL_AUX_BUFFER_DISABLED, intel_rb_format(), intel_renderbuffer(), intel_renderbuffer::layer_count, gl_extensions::MESA_shader_framebuffer_fetch, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::NewDriverState, brw_stage_state::prog_data, brw_context::render_target_format, brw_context::screen, brw_stage_state::surf_offset, tex_mocs, brw_context::vtbl, and brw_context::wm.
update_renderbuffer_surfaces()
static void update_renderbuffer_surfaces (struct brw_context * brw) static
References brw_context::base, BRW_NEW_SURFACES, brw_update_renderbuffer_surfaces(), brw_context::ctx, gl_context::DrawBuffer, gl_context::NewDriverState, brw_stage_state::prog_data, brw_stage_state::surf_offset, and brw_context::wm.
update_stage_texture_surfaces()
static void update_stage_texture_surfaces (struct brw_context * brw, const struct gl_program * prog, struct brw_stage_state * stage_state, bool for_gather, uint32_t plane) static
References gl_texture_unit::_Current, brw_update_texture_surface(), brw_context::ctx, brw_stage_state::prog_data, gl_program::SamplersUsed, gl_program::SamplerUnits, brw_stage_state::surf_offset, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_update_cs_texture_surfaces(), and brw_update_texture_surfaces().
update_texture_image_param()
static void update_texture_image_param (struct brw_context * brw, struct gl_image_unit * u, unsigned surface_idx, struct brw_image_param * param) static
References gl_image_unit::_Layer, brw_miptree_get_horizontal_slice_pitch(), brw_miptree_get_vertical_slice_pitch(), brw_context::has_swizzling, intel_miptree_get_image_offset(), intel_texture_object(), gl_image_unit::Layered, gl_image_unit::Level, intel_texture_object::mt, gl_texture_object::Target, gl_image_unit::TexObj, and update_default_image_param().
Referenced by update_image_surface().
Variable Documentation
brw_cs_abo_surfaces
const struct brw_tracked_state brw_cs_abo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_ATOMIC_BUFFER |
             BRW_NEW_BLORP |
             BRW_NEW_BATCH |
             BRW_NEW_CS_PROG_DATA,
   },
   .emit = brw_upload_cs_abo_surfaces,
}
brw_cs_image_surfaces
const struct brw_tracked_state brw_cs_image_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE | _NEW_PROGRAM,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CS_PROG_DATA |
             BRW_NEW_IMAGE_UNITS
   },
   .emit = brw_upload_cs_image_surfaces,
}
brw_cs_texture_surfaces
const struct brw_tracked_state brw_cs_texture_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_COMPUTE_PROGRAM,
   },
   .emit = brw_update_cs_texture_surfaces,
}
brw_cs_ubo_surfaces
const struct brw_tracked_state brw_cs_ubo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CS_PROG_DATA |
             BRW_NEW_UNIFORM_BUFFER,
   },
   .emit = brw_upload_cs_ubo_surfaces,
}
brw_cs_work_groups_surface
const struct brw_tracked_state brw_cs_work_groups_surface
Initial value:
= {
   .dirty = {
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CS_PROG_DATA |
             BRW_NEW_CS_WORK_GROUPS
   },
   .emit = brw_upload_cs_work_groups_surface,
}
brw_renderbuffer_read_surfaces
const struct brw_tracked_state brw_renderbuffer_read_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_FRAGMENT_PROGRAM |
             BRW_NEW_FS_PROG_DATA,
   },
   .emit = update_renderbuffer_read_surfaces,
}
brw_renderbuffer_surfaces
const struct brw_tracked_state brw_renderbuffer_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FS_PROG_DATA,
   },
   .emit = update_renderbuffer_surfaces,
}
brw_texture_surfaces
const struct brw_tracked_state brw_texture_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FRAGMENT_PROGRAM |
             BRW_NEW_FS_PROG_DATA |
             BRW_NEW_GEOMETRY_PROGRAM |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_TESS_PROGRAMS |
             BRW_NEW_TCS_PROG_DATA |
             BRW_NEW_TES_PROG_DATA |
             BRW_NEW_TEXTURE_BUFFER |
             BRW_NEW_VERTEX_PROGRAM |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_update_texture_surfaces,
}
brw_wm_abo_surfaces
const struct brw_tracked_state brw_wm_abo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_ATOMIC_BUFFER |
             BRW_NEW_BLORP |
             BRW_NEW_BATCH |
             BRW_NEW_FS_PROG_DATA,
   },
   .emit = brw_upload_wm_abo_surfaces,
}
brw_wm_image_surfaces
const struct brw_tracked_state brw_wm_image_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FRAGMENT_PROGRAM |
             BRW_NEW_FS_PROG_DATA |
             BRW_NEW_IMAGE_UNITS
   },
   .emit = brw_upload_wm_image_surfaces,
}
brw_wm_pull_constants
const struct brw_tracked_state brw_wm_pull_constants
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FRAGMENT_PROGRAM |
             BRW_NEW_FS_PROG_DATA,
   },
   .emit = brw_upload_wm_pull_constants,
}
brw_wm_ubo_surfaces
const struct brw_tracked_state brw_wm_ubo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FS_PROG_DATA |
             BRW_NEW_UNIFORM_BUFFER,
   },
   .emit = brw_upload_wm_ubo_surfaces,
}
gen6_renderbuffer_surfaces
const struct brw_tracked_state gen6_renderbuffer_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP,
   },
   .emit = update_renderbuffer_surfaces,
}
rb_mocs
uint32_t rb_mocs[]
Initial value:
= {
   [7] = GEN7_MOCS_L3,
   [8] = BDW_MOCS_PTE,
   [9] = SKL_MOCS_PTE,
}
Referenced by brw_update_renderbuffer_surface().
tex_mocs
uint32_t tex_mocs[]
Initial value:
= {
   [7] = GEN7_MOCS_L3,
   [8] = BDW_MOCS_WB,
   [9] = SKL_MOCS_WB,
}
Referenced by brw_emit_buffer_surface_state(), brw_update_texture_surface(), update_image_surface(), and update_renderbuffer_read_surfaces().