Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_misc_state.c File Reference
#include "intel_batchbuffer.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
#include "main/framebuffer.h"
#include "main/fbobject.h"
#include "main/glformats.h"
Functions
static void upload_drawing_rect (struct brw_context *brw)
static void upload_pipelined_state_pointers (struct brw_context *brw)
Upload pointers to the per-stage state.
static void upload_psp_urb_cbs (struct brw_context *brw)
uint32_t brw_depthbuffer_format (struct brw_context *brw)
static void brw_get_depthstencil_tile_masks (struct intel_mipmap_tree *depth_mt, uint32_t depth_level, uint32_t depth_layer, struct intel_mipmap_tree *stencil_mt, uint32_t *out_tile_mask_x, uint32_t *out_tile_mask_y)
Returns the mask of how many bits of x and y must be handled through the depthbuffer's draw offset x and y fields.
static struct intel_mipmap_tree * get_stencil_miptree (struct intel_renderbuffer *irb)
void brw_workaround_depthstencil_alignment (struct brw_context *brw, GLbitfield clear_mask)
void brw_emit_depthbuffer (struct brw_context *brw)
void brw_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
static void upload_polygon_stipple (struct brw_context *brw)
Polygon stipple packet.
static void upload_polygon_stipple_offset (struct brw_context *brw)
Polygon stipple offset packet.
static void upload_line_stipple (struct brw_context *brw)
Line stipple packet.
void brw_emit_select_pipeline (struct brw_context *brw, enum brw_pipeline pipeline)
void brw_upload_invariant_state (struct brw_context *brw)
Misc invariant state packets.
void brw_upload_state_base_address (struct brw_context *brw)
Define the base addresses which some state is referenced from.
Variables
const struct brw_tracked_state brw_drawing_rect
const struct brw_tracked_state brw_psp_urb_cbs
const struct brw_tracked_state brw_depthbuffer
const struct brw_tracked_state brw_polygon_stipple
const struct brw_tracked_state brw_polygon_stipple_offset
const struct brw_tracked_state brw_line_stipple
const struct brw_tracked_state brw_invariant_state
Function Documentation
brw_depthbuffer_format()
uint32_t brw_depthbuffer_format (struct brw_context * brw)
References brw_depth_format(), BRW_DEPTHFORMAT_D32_FLOAT, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, intel_get_renderbuffer(), intel_rb_format(), MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, and intel_renderbuffer::mt.
Referenced by brw_emit_depthbuffer(), brw_state_dirty(), gen8_emit_depth_stencil_hiz(), and upload_sf_state().
brw_emit_depth_stencil_hiz()
void brw_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References _3DSTATE_CLEAR_PARAMS, _3DSTATE_DEPTH_BUFFER, _3DSTATE_HIER_DEPTH_BUFFER, _3DSTATE_STENCIL_BUFFER, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_depth_stall_flushes(), BRW_TILEWALK_YMAJOR, brw_context::depthstencil, brw_context::gen, GEN5_DEPTH_CLEAR_VALID, brw_context::hiz_offset, brw_context::is_g4x, OUT_BATCH, OUT_RELOC, and brw_context::stencil_offset.
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
brw_emit_depthbuffer()
void brw_emit_depthbuffer (struct brw_context * brw)
References _mesa_is_format_packed_depth_stencil(), swrast_renderbuffer::Base, intel_renderbuffer::Base, brw_context::bo, brw_depthbuffer_format(), BRW_DEPTHFORMAT_D32_FLOAT, brw_render_cache_set_check_flush(), BRW_SURFACE_2D, BRW_SURFACE_NULL, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, brw_context::depth_mt, brw_context::depth_offset, brw_context::depthstencil, gl_context::DrawBuffer, brw_context::emit_depth_stencil_hiz, brw_context::gen, brw_context::has_separate_stencil, gl_renderbuffer::Height, intel_get_renderbuffer(), intel_renderbuffer_has_hiz(), MESA_FORMAT_S_UINT8, brw_context::stencil_mt, brw_context::tile_x, brw_context::tile_y, brw_context::vtbl, and gl_renderbuffer::Width.
Referenced by brw_depth_writes_enabled().
brw_emit_select_pipeline()
void brw_emit_select_pipeline (struct brw_context * brw, enum brw_pipeline pipeline)
References _3DSTATE_CC_STATE_POINTERS, ADVANCE_BATCH, BEGIN_BATCH, BRW_COMPUTE_PIPELINE, brw_emit_pipe_control_flush(), BRW_NEW_CC_STATE, BRW_RENDER_PIPELINE, CMD_3D_PRIM, CMD_PIPELINE_SELECT_965, CMD_PIPELINE_SELECT_GM45, brw_context::ctx, brw_context::gen, gen7_emit_cs_stall_flush(), brw_context::is_g4x, brw_context::is_haswell, MI_FLUSH, gl_context::NewDriverState, OUT_BATCH, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DATA_CACHE_FLUSH, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_INSTRUCTION_INVALIDATE, PIPE_CONTROL_NO_WRITE, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_STATE_CACHE_INVALIDATE, and PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE.
Referenced by brw_select_pipeline(), brw_state_dirty(), and brw_upload_invariant_state().
brw_get_depthstencil_tile_masks()
static void brw_get_depthstencil_tile_masks (struct intel_mipmap_tree * depth_mt, uint32_t depth_level, uint32_t depth_layer, struct intel_mipmap_tree * stencil_mt, uint32_t * out_tile_mask_x, uint32_t * out_tile_mask_y) static
Returns the mask of how many bits of x and y must be handled through the depthbuffer's draw offset x and y fields.
The draw offset x/y field of the depthbuffer packet is unfortunately shared between the depth, hiz, and stencil buffers. Because it can be hard to get all 3 to agree on this value, we want to do as much drawing offset adjustment as possible by moving the base offset of the 3 buffers, which is restricted to tile boundaries.
For each buffer, the remainder must be applied through the x/y draw offset. This returns the worst-case mask of the low bits that have to go into the packet. If the 3 buffers don't agree on the drawing offset ANDed with this mask, then we're in trouble.
References intel_get_tile_masks(), intel_miptree_level_has_hiz(), and MESA_FORMAT_S_UINT8.
Referenced by brw_workaround_depthstencil_alignment().
brw_upload_invariant_state()
void brw_upload_invariant_state (struct brw_context * brw)
Misc invariant state packets.
References _3DSTATE_AA_LINE_PARAMETERS, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_select_pipeline(), BRW_RENDER_PIPELINE, CMD_STATE_SIP, brw_context::gen, GEN4_3DSTATE_VF_STATISTICS, GM45_3DSTATE_VF_STATISTICS, brw_context::is_g4x, brw_context::last_pipeline, and OUT_BATCH.
Referenced by brw_state_dirty(), and brw_upload_initial_gpu_state().
brw_upload_state_base_address()
void brw_upload_state_base_address (struct brw_context * brw)
Define the base addresses which some state is referenced from.
This allows us to avoid having to emit relocations for the objects, and is actually required for binding table pointers on gen6.
Surface state base address covers binding table pointers and surface state objects, but not the surfaces that the surface state objects point to.
References ADVANCE_BATCH, brw_context::batch, BDW_MOCS_WB, BEGIN_BATCH, brw_cache::bo, intel_batchbuffer::bo, BRW_NEW_STATE_BASE_ADDRESS, brw_context::cache, CMD_STATE_BASE_ADDRESS, brw_context::ctx, brw_context::gen, GEN7_MOCS_L3, gl_context::NewDriverState, OUT_BATCH, OUT_RELOC, OUT_RELOC64, SKL_MOCS_WB, and intel_batchbuffer::state_base_address_emitted.
Referenced by blorp_exec(), brw_state_dirty(), and brw_upload_pipeline_state().
brw_workaround_depthstencil_alignment()
void brw_workaround_depthstencil_alignment (struct brw_context * brw, GLbitfield clear_mask)
References _mesa_get_format_base_format(), brw_get_depthstencil_tile_masks(), BUFFER_BIT_DEPTH, BUFFER_BIT_STENCIL, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, brw_context::depth_mt, brw_context::depth_offset, brw_context::depthstencil, intel_renderbuffer::draw_x, intel_renderbuffer::draw_y, gl_context::DrawBuffer, brw_context::gen, get_stencil_miptree(), brw_context::has_surface_tile_offset, brw_context::hiz_offset, intel_get_renderbuffer(), intel_miptree_get_aligned_offset(), intel_miptree_get_image_offset(), intel_miptree_reference(), intel_renderbuffer_has_hiz(), intel_renderbuffer_move_to_temp(), intel_renderbuffer_set_draw_offset(), MESA_FORMAT_S_UINT8, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, brw_context::stencil_mt, brw_context::stencil_offset, brw_context::tile_x, and brw_context::tile_y.
Referenced by brw_clear(), and brw_try_draw_prims().
get_stencil_miptree()
static struct intel_mipmap_tree* get_stencil_miptree (struct intel_renderbuffer * irb) static
References intel_renderbuffer::mt.
Referenced by brw_workaround_depthstencil_alignment().
upload_drawing_rect()
static void upload_drawing_rect (struct brw_context * brw) static
References _3DSTATE_DRAWING_RECTANGLE, ADVANCE_BATCH, BEGIN_BATCH, brw_context::ctx, gl_context::DrawBuffer, and OUT_BATCH.
upload_line_stipple()
static void upload_line_stipple (struct brw_context * brw) static
Line stipple packet.
References _3DSTATE_LINE_STIPPLE_PATTERN, ADVANCE_BATCH, BEGIN_BATCH, brw_context::ctx, brw_context::gen, gl_context::Line, OUT_BATCH, gl_line_attrib::StippleFactor, gl_line_attrib::StippleFlag, and gl_line_attrib::StipplePattern.
upload_pipelined_state_pointers()
static void upload_pipelined_state_pointers (struct brw_context * brw) static
Upload pointers to the per-stage state.
The state pointers in this packet are all relative to the general state base address set by CMD_STATE_BASE_ADDRESS, which is 0.
References _3DSTATE_PIPELINED_POINTERS, ADVANCE_BATCH, brw_context::base, brw_context::batch, BEGIN_BATCH, intel_batchbuffer::bo, BRW_NEW_PSP, brw_context::cc, brw_context::clip, brw_context::ctx, brw_context::ff_gs, brw_context::gen, MI_FLUSH, gl_context::NewDriverState, OUT_BATCH, OUT_RELOC, brw_context::prog_active, brw_context::sf, brw_stage_state::state_offset, brw_context::state_offset, brw_context::vs, and brw_context::wm.
Referenced by upload_psp_urb_cbs().
upload_polygon_stipple()
static void upload_polygon_stipple (struct brw_context * brw) static
Polygon stipple packet.
References _3DSTATE_POLY_STIPPLE_PATTERN, ADVANCE_BATCH, BEGIN_BATCH, brw_context::ctx, gl_context::DrawBuffer, GLuint, OUT_BATCH, gl_context::Polygon, gl_context::PolygonStipple, and gl_polygon_attrib::StippleFlag.
upload_polygon_stipple_offset()
static void upload_polygon_stipple_offset (struct brw_context * brw) static
Polygon stipple offset packet.
References _3DSTATE_POLY_STIPPLE_OFFSET, ADVANCE_BATCH, BEGIN_BATCH, brw_context::ctx, gl_context::DrawBuffer, OUT_BATCH, gl_context::Polygon, and gl_polygon_attrib::StippleFlag.
upload_psp_urb_cbs()
static void upload_psp_urb_cbs (struct brw_context * brw) static
References brw_upload_cs_urb_state(), brw_upload_urb_fence(), and upload_pipelined_state_pointers().
Variable Documentation
brw_depthbuffer
const struct brw_tracked_state brw_depthbuffer
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP,
   },
   .emit = brw_emit_depthbuffer,
}
brw_drawing_rect
const struct brw_tracked_state brw_drawing_rect
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CONTEXT,
   },
   .emit = upload_drawing_rect
}
brw_invariant_state
const struct brw_tracked_state brw_invariant_state
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CONTEXT,
   },
   .emit = brw_upload_invariant_state
}
brw_line_stipple
const struct brw_tracked_state brw_line_stipple
Initial value:
= {
   .dirty = {
      .mesa = _NEW_LINE,
      .brw = BRW_NEW_CONTEXT,
   },
   .emit = upload_line_stipple
}
brw_polygon_stipple
const struct brw_tracked_state brw_polygon_stipple
Initial value:
= {
   .dirty = {
      .mesa = _NEW_POLYGON |
              _NEW_POLYGONSTIPPLE,
      .brw = BRW_NEW_CONTEXT,
   },
   .emit = upload_polygon_stipple
}
brw_polygon_stipple_offset
const struct brw_tracked_state brw_polygon_stipple_offset
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_POLYGON,
      .brw = BRW_NEW_CONTEXT,
   },
   .emit = upload_polygon_stipple_offset
}
brw_psp_urb_cbs
const struct brw_tracked_state brw_psp_urb_cbs
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FF_GS_PROG_DATA |
             BRW_NEW_GEN4_UNIT_STATE |
             BRW_NEW_STATE_BASE_ADDRESS |
             BRW_NEW_URB_FENCE,
   },
   .emit = upload_psp_urb_cbs,
}