Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_blorp.c File Reference
#include "main/context.h"
#include "main/teximage.h"
#include "main/blend.h"
#include "main/fbobject.h"
#include "main/renderbuffer.h"
#include "main/glformats.h"
#include "brw_blorp.h"
Functions
static bool brw_blorp_lookup_shader (struct blorp_context *blorp, const void *key, uint32_t key_size, uint32_t *kernel_out, void *prog_data_out)
static bool brw_blorp_upload_shader (struct blorp_context *blorp, const void *key, uint32_t key_size, const void *kernel, uint32_t kernel_size, const struct brw_stage_prog_data *prog_data, uint32_t prog_data_size, uint32_t *kernel_out, void *prog_data_out)
void brw_blorp_init (struct brw_context *brw)
static void apply_gen6_stencil_hiz_offset (struct isl_surf *surf, struct intel_mipmap_tree *mt, uint32_t lod, uint32_t *offset)
static void blorp_surf_for_miptree (struct brw_context *brw, struct blorp_surf *surf, struct intel_mipmap_tree *mt, bool is_render_target, uint32_t safe_aux_usage, unsigned *level, unsigned start_layer, unsigned num_layers, struct isl_surf tmp_surfs[2])
static enum isl_format brw_blorp_to_isl_format (struct brw_context *brw, mesa_format format, bool is_render_target)
static enum isl_channel_select swizzle_to_scs (GLenum swizzle)
Convert an swizzle enumeration (i.e.
static unsigned physical_to_logical_layer (struct intel_mipmap_tree *mt, unsigned physical_layer)
void brw_blorp_blit_miptrees (struct brw_context *brw, struct intel_mipmap_tree *src_mt, unsigned src_level, unsigned src_layer, mesa_format src_format, int src_swizzle, struct intel_mipmap_tree *dst_mt, unsigned dst_level, unsigned dst_layer, mesa_format dst_format, float src_x0, float src_y0, float src_x1, float src_y1, float dst_x0, float dst_y0, float dst_x1, float dst_y1, GLenum filter, bool mirror_x, bool mirror_y, bool decode_srgb, bool encode_srgb)
Note: if the src (or dst) is a 2D multisample array texture on Gen7+ using INTEL_MSAA_LAYOUT_UMS or INTEL_MSAA_LAYOUT_CMS, src_layer (dst_layer) is the physical layer holding sample 0.
void brw_blorp_copy_miptrees (struct brw_context *brw, struct intel_mipmap_tree *src_mt, unsigned src_level, unsigned src_layer, struct intel_mipmap_tree *dst_mt, unsigned dst_level, unsigned dst_layer, unsigned src_x, unsigned src_y, unsigned dst_x, unsigned dst_y, unsigned src_width, unsigned src_height)
static struct intel_mipmap_tree * find_miptree (GLbitfield buffer_bit, struct intel_renderbuffer *irb)
static int blorp_get_texture_swizzle (const struct intel_renderbuffer *irb)
static void do_blorp_blit (struct brw_context *brw, GLbitfield buffer_bit, struct intel_renderbuffer *src_irb, mesa_format src_format, struct intel_renderbuffer *dst_irb, mesa_format dst_format, GLfloat srcX0, GLfloat srcY0, GLfloat srcX1, GLfloat srcY1, GLfloat dstX0, GLfloat dstY0, GLfloat dstX1, GLfloat dstY1, GLenum filter, bool mirror_x, bool mirror_y)
static bool try_blorp_blit (struct brw_context *brw, const struct gl_framebuffer *read_fb, const struct gl_framebuffer *draw_fb, GLfloat srcX0, GLfloat srcY0, GLfloat srcX1, GLfloat srcY1, GLfloat dstX0, GLfloat dstY0, GLfloat dstX1, GLfloat dstY1, GLenum filter, GLbitfield buffer_bit)
bool brw_blorp_copytexsubimage (struct brw_context *brw, struct gl_renderbuffer *src_rb, struct gl_texture_image *dst_image, int slice, int srcX0, int srcY0, int dstX0, int dstY0, int width, int height)
GLbitfield brw_blorp_framebuffer (struct brw_context *brw, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
static bool set_write_disables (const struct intel_renderbuffer *irb, const GLubyte *color_mask, bool *color_write_disable)
static unsigned irb_logical_mt_layer (struct intel_renderbuffer *irb)
static bool do_single_blorp_clear (struct brw_context *brw, struct gl_framebuffer *fb, struct gl_renderbuffer *rb, unsigned buf, bool partial_clear, bool encode_srgb)
bool brw_blorp_clear_color (struct brw_context *brw, struct gl_framebuffer *fb, GLbitfield mask, bool partial_clear, bool encode_srgb)
void brw_blorp_resolve_color (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned level, unsigned layer)
static void gen6_blorp_hiz_exec (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
void intel_hiz_exec (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Perform a HiZ or depth resolve operation.
Function Documentation
apply_gen6_stencil_hiz_offset()
static void apply_gen6_stencil_hiz_offset (struct isl_surf * surf, struct intel_mipmap_tree * mt, uint32_t lod, uint32_t * offset) static
References intel_miptree_get_aligned_offset(), and MESA_FORMAT_S_UINT8.
Referenced by blorp_surf_for_miptree().
blorp_get_texture_swizzle()
static int blorp_get_texture_swizzle (const struct intel_renderbuffer * irb) static
References gl_renderbuffer::_BaseFormat, swrast_renderbuffer::Base, and intel_renderbuffer::Base.
Referenced by brw_blorp_copytexsubimage(), and do_blorp_blit().
blorp_surf_for_miptree()
static void blorp_surf_for_miptree (struct brw_context * brw, struct blorp_surf * surf, struct intel_mipmap_tree * mt, bool is_render_target, uint32_t safe_aux_usage, unsigned * level, unsigned start_layer, unsigned num_layers, struct isl_surf tmp_surfs[2]) static
References apply_gen6_stencil_hiz_offset(), brw_context::gen, intel_miptree_get_aux_isl_surf(), intel_miptree_get_isl_clear_color(), intel_miptree_get_isl_surf(), intel_miptree_has_color_unresolved(), intel_miptree_resolve_color(), intel_miptree_slice_resolve_depth(), intel_miptree_slice_set_needs_hiz_resolve(), intel_miptree_used_for_rendering(), MESA_FORMAT_S_UINT8, and brw_context::num_samples.
Referenced by brw_blorp_blit_miptrees(), brw_blorp_copy_miptrees(), brw_blorp_resolve_color(), do_single_blorp_clear(), and gen6_blorp_hiz_exec().
brw_blorp_blit_miptrees()
void brw_blorp_blit_miptrees (struct brw_context * brw, struct intel_mipmap_tree * src_mt, unsigned src_level, unsigned src_layer, mesa_format src_format, int src_swizzle, struct intel_mipmap_tree * dst_mt, unsigned dst_level, unsigned dst_layer, mesa_format dst_format, float src_x0, float src_y0, float src_x1, float src_y1, float dst_x0, float dst_y0, float dst_x1, float dst_y1, GLenum filter, bool mirror_x, bool mirror_y, bool decode_srgb, bool encode_srgb)
Note: if the src (or dst) is a 2D multisample array texture on Gen7+ using INTEL_MSAA_LAYOUT_UMS or INTEL_MSAA_LAYOUT_CMS, src_layer (dst_layer) is the physical layer holding sample 0.
So, for example, if src_mt->num_samples == 4, then logical layer n corresponds to src_layer == 4*n.
References _mesa_get_format_color_encoding(), _mesa_get_format_name(), _mesa_get_srgb_format_linear(), brw_context::blorp, blorp_surf_for_miptree(), brw_blorp_to_isl_format(), DBG, brw_context::gen, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_R_FLOAT32, physical_to_logical_layer(), and swizzle_to_scs().
Referenced by brw_blorp_copytexsubimage(), do_blorp_blit(), intel_miptree_updownsample(), and intel_update_r8stencil().
brw_blorp_clear_color()
bool brw_blorp_clear_color (struct brw_context * brw, struct gl_framebuffer * fb, GLbitfield mask, bool partial_clear, bool encode_srgb)
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, do_single_blorp_clear(), intel_renderbuffer(), and intel_renderbuffer::need_downsample.
Referenced by brw_clear().
brw_blorp_copy_miptrees()
void brw_blorp_copy_miptrees (struct brw_context * brw, struct intel_mipmap_tree * src_mt, unsigned src_level, unsigned src_layer, struct intel_mipmap_tree * dst_mt, unsigned dst_level, unsigned dst_layer, unsigned src_x, unsigned src_y, unsigned dst_x, unsigned dst_y, unsigned src_width, unsigned src_height)
References _mesa_get_format_name(), brw_context::blorp, blorp_surf_for_miptree(), and DBG.
Referenced by copy_miptrees().
brw_blorp_copytexsubimage()
bool brw_blorp_copytexsubimage (struct brw_context * brw, struct gl_renderbuffer * src_rb, struct gl_texture_image * dst_image, int slice, int srcX0, int srcY0, int dstX0, int dstY0, int width, int height)
References gl_context::_ImageTransferState, _mesa_get_format_base_format(), _mesa_get_format_bits(), gl_framebuffer::Attachment, blorp_get_texture_swizzle(), brw_blorp_blit_miptrees(), BUFFER_STENCIL, brw_context::ctx, gl_texture_image::Face, gl_renderbuffer::Format, brw_context::format_supported_as_render_target, brw_context::gen, gl_renderbuffer::Height, intel_prepare_render(), intel_renderbuffer(), intel_texture_image(), gl_texture_image::Level, MESA_FORMAT_Z24_UNORM_X8_UINT, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_renderbuffer::mt, intel_texture_image::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_texture_image::TexFormat, and gl_texture_image::TexObject.
Referenced by brw_get_index_type(), and intelCopyTexSubImage().
brw_blorp_framebuffer()
GLbitfield brw_blorp_framebuffer (struct brw_context * brw, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
References brw_context::gen, and try_blorp_blit().
Referenced by brw_get_index_type(), and intel_blit_framebuffer().
brw_blorp_init()
void brw_blorp_init (struct brw_context * brw)
References BDW_MOCS_PTE, BDW_MOCS_WB, brw_context::blorp, brw_blorp_lookup_shader(), brw_blorp_upload_shader(), intel_screen::compiler, brw_context::gen, gen6_blorp_exec(), gen75_blorp_exec(), gen7_blorp_exec(), GEN7_MOCS_L3, gen8_blorp_exec(), gen9_blorp_exec(), brw_context::is_haswell, brw_context::isl_dev, brw_context::screen, SKL_MOCS_PTE, and SKL_MOCS_WB.
Referenced by brwCreateContext().
brw_blorp_lookup_shader()
static bool brw_blorp_lookup_shader (struct blorp_context * blorp, const void * key, uint32_t key_size, uint32_t * kernel_out, void * prog_data_out) static
References BRW_CACHE_BLORP_PROG, brw_search_cache(), and brw_context::cache.
Referenced by brw_blorp_init().
brw_blorp_resolve_color()
void brw_blorp_resolve_color (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned level, unsigned layer)
References _mesa_get_srgb_format_linear(), brw_context::blorp, blorp_surf_for_miptree(), brw_blorp_to_isl_format(), brw_emit_pipe_control_flush(), DBG, brw_context::gen, PIPE_CONTROL_CS_STALL, and PIPE_CONTROL_RENDER_TARGET_FLUSH.
Referenced by intel_miptree_all_slices_resolve_color(), and intel_miptree_resolve_color().
brw_blorp_to_isl_format()
static enum isl_format brw_blorp_to_isl_format (struct brw_context * brw, mesa_format format, bool is_render_target) static
References brw_isl_format_for_mesa_format(), brw_context::format_supported_as_render_target, MESA_FORMAT_NONE, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, and brw_context::render_target_format.
Referenced by brw_blorp_blit_miptrees(), and brw_blorp_resolve_color().
brw_blorp_upload_shader()
static bool brw_blorp_upload_shader (struct blorp_context * blorp, const void * key, uint32_t key_size, const void * kernel, uint32_t kernel_size, const struct brw_stage_prog_data * prog_data, uint32_t prog_data_size, uint32_t * kernel_out, void * prog_data_out) static
References BRW_CACHE_BLORP_PROG, brw_upload_cache(), and brw_context::cache.
Referenced by brw_blorp_init().
do_blorp_blit()
static void do_blorp_blit (struct brw_context * brw, GLbitfield buffer_bit, struct intel_renderbuffer * src_irb, mesa_format src_format, struct intel_renderbuffer * dst_irb, mesa_format dst_format, GLfloat srcX0, GLfloat srcY0, GLfloat srcX1, GLfloat srcY1, GLfloat dstX0, GLfloat dstY0, GLfloat dstX1, GLfloat dstY1, GLenum filter, bool mirror_x, bool mirror_y) static
References blorp_get_texture_swizzle(), brw_blorp_blit_miptrees(), gl_context::Color, brw_context::ctx, find_miptree(), intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, intel_renderbuffer::need_downsample, and gl_colorbuffer_attrib::sRGBEnabled.
Referenced by try_blorp_blit().
do_single_blorp_clear()
static bool do_single_blorp_clear (struct brw_context * brw, struct gl_framebuffer * fb, struct gl_renderbuffer * rb, unsigned buf, bool partial_clear, bool encode_srgb) static
References _mesa_get_format_color_encoding(), _mesa_get_srgb_format_linear(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, brw_context::blorp, blorp_surf_for_miptree(), brw_emit_pipe_control_flush(), brw_is_color_fast_clear_compatible(), brw_meta_convert_fast_clear_color(), brw_meta_set_fast_clear_color(), gl_colorbuffer_attrib::ClearColor, gl_context::Color, gl_colorbuffer_attrib::ColorMask, brw_context::ctx, DBG, gl_color_union::f, gl_renderbuffer::Height, INTEL_FAST_CLEAR_STATE_CLEAR, intel_miptree_alloc_non_msrt_mcs(), intel_miptree_get_fast_clear_state(), intel_miptree_is_lossless_compressed(), intel_miptree_set_fast_clear_state(), intel_renderbuffer(), irb_logical_mt_layer(), intel_renderbuffer::layer_count, gl_framebuffer::MaxNumLayers, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_renderbuffer::Name, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, brw_context::render_target_format, set_write_disables(), and y1.
Referenced by brw_blorp_clear_color().
find_miptree()
static struct intel_mipmap_tree* find_miptree (GLbitfield buffer_bit, struct intel_renderbuffer * irb) static
References intel_renderbuffer::mt.
Referenced by do_blorp_blit(), and try_blorp_blit().
gen6_blorp_hiz_exec()
static void gen6_blorp_hiz_exec (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op) static
References brw_context::blorp, blorp_surf_for_miptree(), and intel_miptree_level_has_hiz().
Referenced by intel_hiz_exec().
intel_hiz_exec()
void intel_hiz_exec (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Perform a HiZ or depth resolve operation.
For an overview of HiZ ops, see the following sections of the Sandy Bridge PRM, Volume 1, Part 2:
7.5.3.1 Depth Buffer Clear
7.5.3.2 Depth Buffer Resolve
7.5.3.3 Hierarchical Depth Buffer Resolve
References DBG, brw_context::gen, gen6_blorp_hiz_exec(), and gen8_hiz_exec().
Referenced by brw_fast_clear_depth(), intel_miptree_all_slices_resolve(), and intel_miptree_slice_resolve().
irb_logical_mt_layer()
static unsigned irb_logical_mt_layer (struct intel_renderbuffer * irb) static
References intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and physical_to_logical_layer().
Referenced by do_single_blorp_clear().
physical_to_logical_layer()
static unsigned physical_to_logical_layer (struct intel_mipmap_tree * mt, unsigned physical_layer) static
Referenced by brw_blorp_blit_miptrees(), and irb_logical_mt_layer().
set_write_disables()
static bool set_write_disables (const struct intel_renderbuffer * irb, const GLubyte * color_mask, bool * color_write_disable) static
References gl_renderbuffer::_BaseFormat, _mesa_base_format_component_count(), swrast_renderbuffer::Base, and intel_renderbuffer::Base.
Referenced by do_single_blorp_clear().
swizzle_to_scs()
static enum isl_channel_select swizzle_to_scs (GLenum swizzle) static
Convert an swizzle enumeration (i.e.
SWIZZLE_X) to one of the Gen7.5+ "Shader Channel Select" enumerations (i.e. HSW_SCS_RED). The mappings are
SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_W, SWIZZLE_ZERO, SWIZZLE_ONE 0 1 2 3 4 5 4 5 6 7 0 1 SCS_RED, SCS_GREEN, SCS_BLUE, SCS_ALPHA, SCS_ZERO, SCS_ONE
which is simply adding 4 then modding by 8 (or anding with 7).
We then may need to apply workarounds for textureGather hardware bugs.
Referenced by brw_blorp_blit_miptrees().
try_blorp_blit()
static bool try_blorp_blit (struct brw_context * brw, const struct gl_framebuffer * read_fb, const struct gl_framebuffer * draw_fb, GLfloat srcX0, GLfloat srcY0, GLfloat srcX1, GLfloat srcY1, GLfloat dstX0, GLfloat dstY0, GLfloat dstX1, GLfloat dstY1, GLenum filter, GLbitfield buffer_bit) static
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_ColorReadBuffer, gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::Attachment, swrast_renderbuffer::Base, intel_renderbuffer::Base, brw_meta_mirror_clip_and_scissor(), BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, do_blorp_blit(), find_miptree(), gl_renderbuffer::Format, intel_prepare_render(), intel_renderbuffer(), MESA_FORMAT_NONE, MESA_FORMAT_Z24_UNORM_X8_UINT, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by brw_blorp_framebuffer().