Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_state_upload.c File Reference
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "brw_program.h"
#include "drivers/common/meta.h"
#include "intel_batchbuffer.h"
#include "intel_buffers.h"
#include "brw_vs.h"
#include "brw_ff_gs.h"
#include "brw_gs.h"
#include "brw_wm.h"
#include "brw_cs.h"
#include "main/framebuffer.h"
Data Structures
struct dirty_bit_map
Macros
#define DEFINE_BIT(name) {name, #name, 0}
Functions
static void brw_upload_initial_gpu_state (struct brw_context *brw)
static const struct brw_tracked_state * brw_get_pipeline_atoms (struct brw_context *brw, enum brw_pipeline pipeline)
static void brw_copy_pipeline_atoms (struct brw_context *brw, enum brw_pipeline pipeline, const struct brw_tracked_state **atoms, int num_atoms)
void brw_init_state (struct brw_context *brw)
void brw_destroy_state (struct brw_context *brw)
static bool check_state (const struct brw_state_flags *a, const struct brw_state_flags *b)
static void accumulate_state (struct brw_state_flags *a, const struct brw_state_flags *b)
static void xor_states (struct brw_state_flags *result, const struct brw_state_flags *a, const struct brw_state_flags *b)
static void brw_update_dirty_count (struct dirty_bit_map *bit_map, uint64_t bits)
static void brw_print_dirty_count (struct dirty_bit_map *bit_map)
static void brw_upload_tess_programs (struct brw_context *brw)
static void brw_upload_programs (struct brw_context *brw, enum brw_pipeline pipeline)
static void merge_ctx_state (struct brw_context *brw, struct brw_state_flags *state)
static void check_and_emit_atom (struct brw_context *brw, struct brw_state_flags *state, const struct brw_tracked_state *atom)
static void brw_upload_pipeline_state (struct brw_context *brw, enum brw_pipeline pipeline)
void brw_upload_render_state (struct brw_context *brw)
static void brw_pipeline_state_finished (struct brw_context *brw, enum brw_pipeline pipeline)
void brw_render_state_finished (struct brw_context *brw)
Clear dirty bits to account for the fact that the state emitted by brw_upload_render_state() has been committed to the hardware.
void brw_upload_compute_state (struct brw_context *brw)
void brw_compute_state_finished (struct brw_context *brw)
Variables
static const struct brw_tracked_state * gen4_atoms []
static const struct brw_tracked_state * gen6_atoms []
static const struct brw_tracked_state * gen7_render_atoms []
static const struct brw_tracked_state * gen7_compute_atoms []
static const struct brw_tracked_state * gen8_render_atoms []
static const struct brw_tracked_state * gen8_compute_atoms []
static struct dirty_bit_map mesa_bits []
static struct dirty_bit_map brw_bits []
Macro Definition Documentation
DEFINE_BIT
#define DEFINE_BIT (name) {name, #name, 0}
Function Documentation
accumulate_state()
static void accumulate_state (struct brw_state_flags * a, const struct brw_state_flags * b) static
References brw_state_flags::brw, and brw_state_flags::mesa.
Referenced by brw_upload_pipeline_state().
brw_compute_state_finished()
void brw_compute_state_finished (struct brw_context * brw)
References BRW_COMPUTE_PIPELINE, and brw_pipeline_state_finished().
Referenced by brw_dispatch_compute_common(), and brw_state_dirty().
brw_copy_pipeline_atoms()
static void brw_copy_pipeline_atoms (struct brw_context * brw, enum brw_pipeline pipeline, const struct brw_tracked_state ** atoms, int num_atoms) static
References brw_state_flags::brw, brw_get_pipeline_atoms(), brw_tracked_state::dirty, brw_tracked_state::emit, brw_state_flags::mesa, and brw_context::num_atoms.
Referenced by brw_init_state().
brw_destroy_state()
void brw_destroy_state (struct brw_context * brw)
References brw_destroy_caches().
Referenced by brw_state_dirty(), and intelDestroyContext().
brw_get_pipeline_atoms()
static const struct brw_tracked_state* brw_get_pipeline_atoms (struct brw_context * brw, enum brw_pipeline pipeline) static
References BRW_COMPUTE_PIPELINE, BRW_NUM_PIPELINES, BRW_RENDER_PIPELINE, brw_context::compute_atoms, and brw_context::render_atoms.
Referenced by brw_copy_pipeline_atoms(), and brw_upload_pipeline_state().
brw_init_state()
void brw_init_state (struct brw_context * brw)
References BRW_COMPUTE_PIPELINE, brw_copy_pipeline_atoms(), brw_init_caches(), BRW_NEW_ATOMIC_BUFFER, BRW_NEW_CONSERVATIVE_RASTERIZATION, BRW_NEW_DEFAULT_TESS_LEVELS, BRW_NEW_IMAGE_UNITS, BRW_NEW_RASTERIZER_DISCARD, BRW_NEW_TEXTURE_BUFFER, BRW_NEW_TRANSFORM_FEEDBACK, BRW_NEW_UNIFORM_BUFFER, BRW_NUM_PIPELINES, BRW_NUM_STATE_BITS, BRW_RENDER_PIPELINE, brw_upload_initial_gpu_state(), brw_context::compute_atoms, brw_context::ctx, gl_context::DriverFlags, brw_context::gen, brw_context::last_pipeline, gl_driver_flags::NewAtomicBuffer, gl_driver_flags::NewDefaultTessLevels, gl_context::NewDriverState, brw_context::NewGLState, gl_driver_flags::NewImageUnits, gl_driver_flags::NewIntelConservativeRasterization, gl_driver_flags::NewRasterizerDiscard, gl_driver_flags::NewShaderStorageBuffer, gl_driver_flags::NewTextureBuffer, gl_driver_flags::NewTransformFeedback, gl_driver_flags::NewTransformFeedbackProg, gl_driver_flags::NewUniformBuffer, brw_context::pma_stall_bits, and brw_context::render_atoms.
Referenced by brw_state_dirty(), and brwCreateContext().
brw_pipeline_state_finished()
static void brw_pipeline_state_finished (struct brw_context * brw, enum brw_pipeline pipeline) inline static
References brw_state_flags::brw, BRW_NUM_PIPELINES, brw_context::ctx, brw_state_flags::mesa, gl_context::NewDriverState, brw_context::NewGLState, brw_context::pipelines, and brw_context::state.
Referenced by brw_compute_state_finished(), and brw_render_state_finished().
brw_print_dirty_count()
static void brw_print_dirty_count (struct dirty_bit_map * bit_map) static
References dirty_bit_map::bit, dirty_bit_map::count, and dirty_bit_map::name.
Referenced by brw_upload_pipeline_state().
brw_render_state_finished()
void brw_render_state_finished (struct brw_context * brw)
Clear dirty bits to account for the fact that the state emitted by brw_upload_render_state() has been committed to the hardware.
This is a separate call from brw_upload_render_state() because it's possible that after the call to brw_upload_render_state(), we will discover that we've run out of aperture space, and need to rewind the batch buffer to the state it had before the brw_upload_render_state() call.
References brw_pipeline_state_finished(), and BRW_RENDER_PIPELINE.
Referenced by brw_state_dirty(), and brw_try_draw_prims().
brw_update_dirty_count()
static void brw_update_dirty_count (struct dirty_bit_map * bit_map, uint64_t bits) static
References dirty_bit_map::bit, and dirty_bit_map::count.
Referenced by brw_upload_pipeline_state().
brw_upload_compute_state()
void brw_upload_compute_state (struct brw_context * brw)
References BRW_COMPUTE_PIPELINE, and brw_upload_pipeline_state().
Referenced by brw_dispatch_compute_common(), and brw_state_dirty().
brw_upload_initial_gpu_state()
static void brw_upload_initial_gpu_state (struct brw_context * brw) static
References _3DSTATE_WM_CHROMAKEY, _3DSTATE_WM_HZ_OP, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_post_sync_nonzero_flush(), brw_upload_invariant_state(), brw_context::gen, GEN7_CACHE_MODE_1, gen8_emit_3dstate_sample_pattern(), GEN9_PARTIAL_RESOLVE_DISABLE_IN_VC, brw_context::hw_ctx, MI_LOAD_REGISTER_IMM, OUT_BATCH, and REG_MASK.
Referenced by brw_init_state().
brw_upload_pipeline_state()
static void brw_upload_pipeline_state (struct brw_context * brw, enum brw_pipeline pipeline) inline static
References gl_fragment_program_state::_Current, gl_tess_ctrl_program_state::_Current, gl_geometry_program_state::_Current, gl_tess_eval_program_state::_Current, gl_vertex_program_state::_Current, gl_compute_program_state::_Current, accumulate_state(), brw_state_flags::brw, brw_emit_post_sync_nonzero_flush(), brw_get_pipeline_atoms(), BRW_NEW_COMPUTE_PROGRAM, BRW_NEW_FRAGMENT_PROGRAM, BRW_NEW_GEOMETRY_PROGRAM, BRW_NEW_META_IN_PROGRESS, BRW_NEW_NUM_SAMPLES, BRW_NEW_TESS_PROGRAMS, BRW_NEW_VERTEX_PROGRAM, BRW_NUM_STATE_BITS, brw_print_dirty_count(), BRW_RENDER_PIPELINE, brw_select_pipeline(), brw_update_dirty_count(), brw_upload_programs(), brw_upload_state_base_address(), check_and_emit_atom(), check_state(), brw_context::compute_program, gl_context::ComputeProgram, brw_context::ctx, brw_tracked_state::dirty, gl_context::DrawBuffer, brw_context::fragment_program, gl_context::FragmentProgram, brw_context::gen, brw_context::geometry_program, gl_context::GeometryProgram, merge_ctx_state(), brw_state_flags::mesa, brw_context::meta_in_progress, gl_context::NewDriverState, brw_context::NewGLState, brw_context::num_atoms, brw_context::num_samples, brw_context::pipelines, brw_context::state, brw_context::tess_ctrl_program, brw_context::tess_eval_program, gl_context::TessCtrlProgram, gl_context::TessEvalProgram, brw_context::vertex_program, gl_context::VertexProgram, and xor_states().
Referenced by brw_upload_compute_state(), and brw_upload_render_state().
brw_upload_programs()
static void brw_upload_programs (struct brw_context * brw, enum brw_pipeline pipeline) inline static
References brw_context::base, BRW_COMPUTE_PIPELINE, BRW_NEW_VIEWPORT_COUNT, BRW_NEW_VUE_MAP_GEOM_OUT, BRW_RENDER_PIPELINE, brw_upload_clip_prog(), brw_upload_cs_prog(), brw_upload_ff_gs_prog(), brw_upload_gs_prog(), brw_upload_sf_prog(), brw_upload_tess_programs(), brw_upload_vs_prog(), brw_upload_wm_prog(), brw_context::clip, gl_context::Const, brw_context::ctx, brw_context::gen, brw_context::geometry_program, brw_context::gs, gl_constants::MaxViewports, gl_context::NewDriverState, brw_stage_state::prog_data, brw_context::tes, brw_context::tess_eval_program, brw_context::viewport_count, brw_context::vs, and brw_context::vue_map_geom_out.
Referenced by brw_upload_pipeline_state().
brw_upload_render_state()
void brw_upload_render_state (struct brw_context * brw)
References BRW_RENDER_PIPELINE, and brw_upload_pipeline_state().
Referenced by brw_state_dirty(), and brw_try_draw_prims().
brw_upload_tess_programs()
static void brw_upload_tess_programs (struct brw_context * brw) inline static
References brw_context::base, brw_upload_tcs_prog(), brw_upload_tes_prog(), brw_stage_state::prog_data, brw_context::tcs, brw_context::tes, and brw_context::tess_eval_program.
Referenced by brw_upload_programs().
check_and_emit_atom()
static void check_and_emit_atom (struct brw_context * brw, struct brw_state_flags * state, const struct brw_tracked_state * atom) inline static
References check_state(), brw_tracked_state::dirty, brw_tracked_state::emit, and merge_ctx_state().
Referenced by brw_upload_pipeline_state().
check_state()
static bool check_state (const struct brw_state_flags * a, const struct brw_state_flags * b) static
References brw_state_flags::brw, and brw_state_flags::mesa.
Referenced by brw_upload_pipeline_state(), and check_and_emit_atom().
merge_ctx_state()
static void merge_ctx_state (struct brw_context * brw, struct brw_state_flags * state) inline static
References brw_state_flags::brw, brw_context::ctx, brw_state_flags::mesa, gl_context::NewDriverState, and brw_context::NewGLState.
Referenced by brw_upload_pipeline_state(), and check_and_emit_atom().
xor_states()
static void xor_states (struct brw_state_flags * result, const struct brw_state_flags * a, const struct brw_state_flags * b) static
References brw_state_flags::brw, and brw_state_flags::mesa.
Referenced by brw_upload_pipeline_state().
Variable Documentation
brw_bits
struct dirty_bit_map brw_bits[] static
gen4_atoms
const struct brw_tracked_state* gen4_atoms[] static
gen6_atoms
const struct brw_tracked_state* gen6_atoms[] static
gen7_compute_atoms
const struct brw_tracked_state* gen7_compute_atoms[] static
Initial value:
=
{
   &gen7_l3_state,
   &brw_cs_image_surfaces,
   &gen7_cs_push_constants,
   &brw_cs_pull_constants,
   &brw_cs_ubo_surfaces,
   &brw_cs_abo_surfaces,
   &brw_cs_texture_surfaces,
   &brw_cs_work_groups_surface,
   &brw_cs_samplers,
   &brw_cs_state,
}
gen7_render_atoms
const struct brw_tracked_state* gen7_render_atoms[] static
gen8_compute_atoms
const struct brw_tracked_state* gen8_compute_atoms[] static
Initial value:
=
{
   &gen7_l3_state,
   &brw_cs_image_surfaces,
   &gen7_cs_push_constants,
   &brw_cs_pull_constants,
   &brw_cs_ubo_surfaces,
   &brw_cs_abo_surfaces,
   &brw_cs_texture_surfaces,
   &brw_cs_work_groups_surface,
   &brw_cs_samplers,
   &brw_cs_state,
}
gen8_render_atoms
const struct brw_tracked_state* gen8_render_atoms[] static
mesa_bits
struct dirty_bit_map mesa_bits[] static