Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip.h File Reference
#include "brw_context.h"
#include "compiler/brw_eu.h"
Data Structures
struct brw_clip_prog_key
struct brw_clip_compile
Macros
#define MAX_VERTS (3+6+8)
#define CLIP_LINE 0
#define CLIP_POINT 1
#define CLIP_FILL 2
#define CLIP_CULL 3
#define PRIM_MASK (0x1f)
Functions
static bool brw_clip_have_varying (struct brw_clip_compile *c, GLuint varying)
True if the given varying is one of the outputs of the vertex shader.
void brw_emit_unfilled_clip (struct brw_clip_compile *c)
void brw_emit_tri_clip (struct brw_clip_compile *c)
void brw_emit_line_clip (struct brw_clip_compile *c)
void brw_emit_point_clip (struct brw_clip_compile *c)
void brw_clip_tri_init_vertices (struct brw_clip_compile *c)
void brw_clip_tri_flat_shade (struct brw_clip_compile *c)
void brw_clip_tri (struct brw_clip_compile *c)
void brw_clip_tri_emit_polygon (struct brw_clip_compile *c)
void brw_clip_tri_alloc_regs (struct brw_clip_compile *c, GLuint nr_verts)
void brw_clip_interp_vertex (struct brw_clip_compile *c, struct brw_indirect dest_ptr, struct brw_indirect v0_ptr, struct brw_indirect v1_ptr, struct brw_reg t0, bool force_edgeflag)
void brw_clip_init_planes (struct brw_clip_compile *c)
void brw_clip_emit_vue (struct brw_clip_compile *c, struct brw_indirect vert, enum brw_urb_write_flags flags, GLuint header)
void brw_clip_kill_thread (struct brw_clip_compile *c)
struct brw_reg brw_clip_plane_stride (struct brw_clip_compile *c)
struct brw_reg brw_clip_plane0_address (struct brw_clip_compile *c)
void brw_clip_copy_flatshaded_attributes (struct brw_clip_compile *c, GLuint to, GLuint from)
void brw_clip_init_clipmask (struct brw_clip_compile *c)
struct brw_reg get_tmp (struct brw_clip_compile *c)
void brw_clip_project_position (struct brw_clip_compile *c, struct brw_reg pos)
void brw_clip_ff_sync (struct brw_clip_compile *c)
void brw_clip_init_ff_sync (struct brw_clip_compile *c)
Macro Definition Documentation
CLIP_CULL
#define CLIP_CULL 3
Referenced by brw_emit_unfilled_clip(), brw_upload_clip_prog(), cull_direction(), emit_primitives(), and emit_unfilled_primitives().
CLIP_FILL
#define CLIP_FILL 2
Referenced by brw_upload_clip_prog(), and emit_primitives().
CLIP_LINE
#define CLIP_LINE 0
Referenced by brw_upload_clip_prog(), and emit_primitives().
CLIP_POINT
#define CLIP_POINT 1
Referenced by brw_upload_clip_prog(), and emit_primitives().
MAX_VERTS
#define MAX_VERTS (3+6+8)
PRIM_MASK
#define PRIM_MASK (0x1f)
Referenced by brw_clip_tri_flat_shade(), brw_clip_tri_init_vertices(), and merge_edgeflags().
Function Documentation
brw_clip_copy_flatshaded_attributes()
void brw_clip_copy_flatshaded_attributes (struct brw_clip_compile * c, GLuint to, GLuint from)
References brw_clip_compile::func, brw_clip_prog_key::interp_mode, brw_clip_compile::key, brw_clip_compile::reg, brw_clip_compile::vertex, and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_clip_tri_flat_shade(), and brw_emit_line_clip().
brw_clip_emit_vue()
void brw_clip_emit_vue (struct brw_clip_compile * c, struct brw_indirect vert, enum brw_urb_write_flags flags, GLuint header)
References brw_clip_ff_sync(), brw_clip_compile::func, brw_clip_compile::nr_regs, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_clip_tri_emit_polygon(), clip_and_emit_line(), emit_lines(), and emit_points().
brw_clip_ff_sync()
void brw_clip_ff_sync (struct brw_clip_compile * c)
References brw_clip_compile::ff_sync, brw_clip_compile::func, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_emit_vue(), brw_clip_have_varying(), and brw_clip_kill_thread().
brw_clip_have_varying()
static bool brw_clip_have_varying (struct brw_clip_compile * c, GLuint varying) inline static
True if the given varying is one of the outputs of the vertex shader.
References brw_clip_prog_key::attrs, BITFIELD64_BIT, brw_clip_copy_flatshaded_attributes(), brw_clip_emit_vue(), brw_clip_ff_sync(), brw_clip_init_clipmask(), brw_clip_init_ff_sync(), brw_clip_init_planes(), brw_clip_interp_vertex(), brw_clip_kill_thread(), brw_clip_plane0_address(), brw_clip_plane_stride(), brw_clip_project_position(), brw_clip_tri(), brw_clip_tri_alloc_regs(), brw_clip_tri_emit_polygon(), brw_clip_tri_flat_shade(), brw_clip_tri_init_vertices(), brw_emit_line_clip(), brw_emit_point_clip(), brw_emit_tri_clip(), brw_emit_unfilled_clip(), get_tmp(), GLuint, and brw_clip_compile::key.
Referenced by brw_emit_unfilled_clip(), and copy_bfc().
brw_clip_init_clipmask()
void brw_clip_init_clipmask (struct brw_clip_compile * c)
References brw_clip_compile::func, get_tmp(), brw_clip_compile::key, brw_clip_prog_key::nr_userclip, brw_clip_compile::planemask, brw_clip_compile::R0, brw_clip_compile::reg, and release_tmp().
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), brw_emit_unfilled_clip(), and clip_and_emit_line().
brw_clip_init_ff_sync()
void brw_clip_init_ff_sync (struct brw_clip_compile * c)
References brw_clip_compile::ff_sync, brw_clip_compile::func, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_line_clip(), brw_emit_point_clip(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_clip_init_planes()
void brw_clip_init_planes (struct brw_clip_compile * c)
References brw_clip_compile::fixed_planes, brw_clip_compile::func, brw_clip_compile::key, make_plane_ud(), brw_clip_prog_key::nr_userclip, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_unfilled_clip(), clip_and_emit_line(), and do_clip_tri().
brw_clip_interp_vertex()
void brw_clip_interp_vertex (struct brw_clip_compile * c, struct brw_indirect dest_ptr, struct brw_indirect v0_ptr, struct brw_indirect v1_ptr, struct brw_reg t0, bool force_edgeflag)
References brw_clip_project_vertex(), brw_clip_prog_key::contains_noperspective_varying, brw_clip_compile::func, get_tmp(), GLuint, brw_clip_prog_key::interp_mode, brw_clip_compile::key, release_tmp(), and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_clip_tri(), and clip_and_emit_line().
brw_clip_kill_thread()
void brw_clip_kill_thread (struct brw_clip_compile * c)
References brw_clip_ff_sync(), brw_clip_compile::func, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_clip_test(), brw_emit_point_clip(), brw_emit_tri_clip(), brw_emit_unfilled_clip(), check_nr_verts(), clip_and_emit_line(), and cull_direction().
brw_clip_plane0_address()
struct brw_reg brw_clip_plane0_address (struct brw_clip_compile * c)
Referenced by brw_clip_have_varying(), brw_clip_tri(), and clip_and_emit_line().
brw_clip_plane_stride()
struct brw_reg brw_clip_plane_stride (struct brw_clip_compile * c)
Referenced by brw_clip_have_varying(), brw_clip_tri(), and clip_and_emit_line().
brw_clip_project_position()
void brw_clip_project_position (struct brw_clip_compile * c, struct brw_reg pos)
References brw_clip_compile::func, and W.
Referenced by brw_clip_have_varying(), brw_clip_project_vertex(), and compute_tri_direction().
brw_clip_tri()
void brw_clip_tri (struct brw_clip_compile * c)
References brw_clip_interp_vertex(), brw_clip_plane0_address(), brw_clip_plane_stride(), brw_clip_compile::clipdistance_offset, brw_clip_compile::dp, brw_clip_compile::dpPrev, brw_clip_compile::func, GLuint, brw_clip_compile::inlist, brw_clip_compile::key, load_clip_distance(), brw_clip_compile::loopcount, brw_clip_compile::nr_regs, brw_clip_prog_key::nr_userclip, brw_clip_compile::nr_verts, brw_clip_compile::outlist, brw_clip_compile::plane_equation, brw_clip_compile::planemask, brw_clip_compile::reg, brw_clip_compile::t, brw_clip_compile::vertex, brw_clip_compile::vertex_src_mask, and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_emit_unfilled_clip(), and do_clip_tri().
brw_clip_tri_alloc_regs()
void brw_clip_tri_alloc_regs (struct brw_clip_compile * c, GLuint nr_verts)
References brw_clip_compile::clipdistance_offset, brw_clip_prog_data::curb_read_length, brw_clip_compile::dir, brw_clip_prog_key::do_unfilled, brw_clip_compile::dp, brw_clip_compile::dpPrev, brw_clip_compile::ff_sync, brw_clip_compile::first_tmp, brw_clip_compile::fixed_planes, brw_clip_compile::freelist, brw_clip_compile::func, GLuint, brw_clip_compile::inlist, brw_clip_compile::key, brw_clip_compile::last_tmp, brw_clip_compile::loopcount, brw_clip_compile::nr_regs, brw_clip_prog_key::nr_userclip, brw_clip_compile::nr_verts, brw_clip_compile::offset, brw_clip_compile::outlist, brw_clip_compile::plane_equation, brw_clip_compile::planemask, brw_clip_compile::prog_data, brw_clip_compile::R0, brw_clip_compile::reg, brw_clip_compile::t, brw_clip_compile::tmp1, brw_clip_prog_data::total_grf, brw_clip_prog_data::urb_read_length, brw_clip_compile::vertex, brw_clip_compile::vertex_src_mask, and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_emit_point_clip(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_clip_tri_emit_polygon()
void brw_clip_tri_emit_polygon (struct brw_clip_compile * c)
References brw_clip_emit_vue(), brw_clip_compile::func, brw_clip_compile::inlist, brw_clip_compile::loopcount, brw_clip_compile::nr_verts, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), and emit_primitives().
brw_clip_tri_flat_shade()
void brw_clip_tri_flat_shade (struct brw_clip_compile * c)
References brw_clip_copy_flatshaded_attributes(), brw_clip_compile::func, brw_clip_compile::key, brw_clip_compile::loopcount, PRIM_MASK, brw_clip_prog_key::pv_first, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_clip_tri_init_vertices()
void brw_clip_tri_init_vertices (struct brw_clip_compile * c)
References brw_clip_compile::dir, brw_clip_compile::func, brw_clip_compile::inlist, brw_clip_compile::loopcount, brw_clip_compile::need_direction, brw_clip_compile::nr_verts, brw_clip_compile::outlist, PRIM_MASK, brw_clip_compile::R0, brw_clip_compile::reg, and brw_clip_compile::vertex.
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_emit_line_clip()
void brw_emit_line_clip (struct brw_clip_compile * c)
References brw_clip_copy_flatshaded_attributes(), brw_clip_init_ff_sync(), brw_clip_line_alloc_regs(), clip_and_emit_line(), brw_clip_prog_key::contains_flat_varying, brw_clip_compile::key, and brw_clip_prog_key::pv_first.
Referenced by brw_clip_have_varying(), and compile_clip_prog().
brw_emit_point_clip()
void brw_emit_point_clip (struct brw_clip_compile * c)
References brw_clip_init_ff_sync(), brw_clip_kill_thread(), and brw_clip_tri_alloc_regs().
Referenced by brw_clip_have_varying(), and compile_clip_prog().
brw_emit_tri_clip()
void brw_emit_tri_clip (struct brw_clip_compile * c)
References brw_clip_init_clipmask(), brw_clip_init_ff_sync(), brw_clip_kill_thread(), brw_clip_test(), brw_clip_tri_alloc_regs(), brw_clip_tri_emit_polygon(), brw_clip_tri_flat_shade(), brw_clip_tri_init_vertices(), BRW_CLIPMODE_KERNEL_CLIP, BRW_CLIPMODE_NORMAL, brw_clip_prog_key::clip_mode, brw_clip_prog_key::contains_flat_varying, do_clip_tri(), brw_clip_compile::func, brw_clip_compile::key, maybe_do_clip_tri(), brw_clip_prog_key::nr_userclip, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), and compile_clip_prog().
brw_emit_unfilled_clip()
void brw_emit_unfilled_clip (struct brw_clip_compile * c)
References brw_clip_have_varying(), brw_clip_init_clipmask(), brw_clip_init_ff_sync(), brw_clip_init_planes(), brw_clip_kill_thread(), brw_clip_tri(), brw_clip_tri_alloc_regs(), brw_clip_tri_flat_shade(), brw_clip_tri_init_vertices(), check_nr_verts(), CLIP_CULL, compute_offset(), compute_tri_direction(), brw_clip_prog_key::contains_flat_varying, copy_bfc(), brw_clip_prog_key::copy_bfc_ccw, brw_clip_prog_key::copy_bfc_cw, cull_direction(), emit_unfilled_primitives(), brw_clip_prog_key::fill_ccw, brw_clip_prog_key::fill_cw, brw_clip_compile::func, brw_clip_compile::key, merge_edgeflags(), brw_clip_compile::need_direction, brw_clip_prog_key::nr_userclip, brw_clip_prog_key::offset_ccw, brw_clip_prog_key::offset_cw, brw_clip_compile::planemask, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), and compile_clip_prog().
get_tmp()
struct brw_reg get_tmp (struct brw_clip_compile * c)
Referenced by brw_clip_have_varying(), brw_clip_init_clipmask(), brw_clip_interp_vertex(), brw_clip_project_vertex(), brw_clip_test(), and compute_tri_direction().