Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_sampler_state.c File Reference
This file contains code for emitting SAMPLER_STATE structures, which specifies filter modes, wrap modes, border color, and so on.
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "intel_mipmap_tree.h"
#include "main/macros.h"
#include "main/samplerobj.h"
#include "util/half_float.h"
Functions
static void gen7_emit_sampler_state_pointers_xs (struct brw_context *brw, struct brw_stage_state *stage_state)
Emit a 3DSTATE_SAMPLER_STATE_POINTERS_{VS,HS,GS,DS,PS} packet.
void brw_emit_sampler_state (struct brw_context *brw, uint32_t *ss, uint32_t batch_offset_for_sampler_state, unsigned min_filter, unsigned mag_filter, unsigned mip_filter, unsigned max_anisotropy, unsigned address_rounding, unsigned wrap_s, unsigned wrap_t, unsigned wrap_r, unsigned base_level, unsigned min_lod, unsigned max_lod, int lod_bias, unsigned shadow_function, bool non_normalized_coordinates, uint32_t border_color_offset)
Emit a SAMPLER_STATE structure, given all the fields.
static uint32_t translate_wrap_mode (struct brw_context *brw, GLenum wrap, bool using_nearest)
static bool wrap_mode_needs_border_color (unsigned wrap_mode)
Return true if the given wrap mode requires the border color to exist.
static bool has_component (mesa_format format, int i)
static void upload_default_color (struct brw_context *brw, const struct gl_sampler_object *sampler, mesa_format format, GLenum base_format, bool is_integer_format, bool is_stencil_sampling, uint32_t *sdc_offset)
Upload SAMPLER_BORDER_COLOR_STATE.
static void brw_update_sampler_state (struct brw_context *brw, GLenum target, bool tex_cube_map_seamless, GLfloat tex_unit_lod_bias, mesa_format format, GLenum base_format, const struct gl_texture_object *texObj, const struct gl_sampler_object *sampler, uint32_t *sampler_state, uint32_t batch_offset_for_sampler_state)
Sets the sampler state for a single unit based off of the sampler key entry.
static void update_sampler_state (struct brw_context *brw, int unit, uint32_t *sampler_state, uint32_t batch_offset_for_sampler_state)
static void brw_upload_sampler_state_table (struct brw_context *brw, struct gl_program *prog, struct brw_stage_state *stage_state)
static void brw_upload_fs_samplers (struct brw_context *brw)
static void brw_upload_vs_samplers (struct brw_context *brw)
static void brw_upload_gs_samplers (struct brw_context *brw)
static void brw_upload_tcs_samplers (struct brw_context *brw)
static void brw_upload_tes_samplers (struct brw_context *brw)
static void brw_upload_cs_samplers (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_fs_samplers
const struct brw_tracked_state brw_vs_samplers
const struct brw_tracked_state brw_gs_samplers
const struct brw_tracked_state brw_tcs_samplers
const struct brw_tracked_state brw_tes_samplers
const struct brw_tracked_state brw_cs_samplers
Detailed Description
This file contains code for emitting SAMPLER_STATE structures, which specifies filter modes, wrap modes, border color, and so on.
Function Documentation
brw_emit_sampler_state()
void brw_emit_sampler_state (struct brw_context * brw, uint32_t * ss, uint32_t batch_offset_for_sampler_state, unsigned min_filter, unsigned mag_filter, unsigned mip_filter, unsigned max_anisotropy, unsigned address_rounding, unsigned wrap_s, unsigned wrap_t, unsigned wrap_r, unsigned base_level, unsigned min_lod, unsigned max_lod, int lod_bias, unsigned shadow_function, bool non_normalized_coordinates, uint32_t border_color_offset)
Emit a SAMPLER_STATE structure, given all the fields.
References brw_context::batch, intel_batchbuffer::bo, BRW_MAPFILTER_ANISOTROPIC, BRW_SAMPLER_LOD_PRECLAMP_ENABLE, brw_context::gen, GEN6_SAMPLER_MIN_MAG_NOT_EQUAL, GEN6_SAMPLER_NON_NORMALIZED_COORDINATES, GEN7_SAMPLER_EWA_ANISOTROPIC_ALGORITHM, GEN7_SAMPLER_NON_NORMALIZED_COORDINATES, and SET_FIELD.
Referenced by brw_update_sampler_state().
brw_update_sampler_state()
static void brw_update_sampler_state (struct brw_context * brw, GLenum target, bool tex_cube_map_seamless, GLfloat tex_unit_lod_bias, mesa_format format, GLenum base_format, const struct gl_texture_object * texObj, const struct gl_sampler_object * sampler, uint32_t * sampler_state, uint32_t batch_offset_for_sampler_state) static
Sets the sampler state for a single unit based off of the sampler key entry.
References gl_texture_object::_IsIntegerFormat, gl_texture_object::BaseLevel, BRW_ADDRESS_ROUNDING_ENABLE_R_MAG, BRW_ADDRESS_ROUNDING_ENABLE_R_MIN, BRW_ADDRESS_ROUNDING_ENABLE_U_MAG, BRW_ADDRESS_ROUNDING_ENABLE_U_MIN, BRW_ADDRESS_ROUNDING_ENABLE_V_MAG, BRW_ADDRESS_ROUNDING_ENABLE_V_MIN, BRW_ANISORATIO_16, BRW_ANISORATIO_2, brw_emit_sampler_state(), BRW_MAPFILTER_ANISOTROPIC, BRW_MAPFILTER_LINEAR, BRW_MAPFILTER_NEAREST, BRW_MIPFILTER_LINEAR, BRW_MIPFILTER_NEAREST, BRW_MIPFILTER_NONE, BRW_TEXCOORDMODE_CLAMP, BRW_TEXCOORDMODE_CUBE, BRW_TEXCOORDMODE_WRAP, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, brw_context::gen, intel_translate_shadow_compare_func(), brw_context::is_haswell, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_texture_object::MinLevel, gl_sampler_object::MinLod, gl_texture_object::StencilSampling, translate_wrap_mode(), upload_default_color(), wrap_mode_needs_border_color(), gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by update_sampler_state().
brw_upload_cs_samplers()
static void brw_upload_cs_samplers (struct brw_context * brw) static
References brw_context::base, brw_upload_sampler_state_table(), brw_context::compute_program, brw_context::cs, and if().
brw_upload_fs_samplers()
static void brw_upload_fs_samplers (struct brw_context * brw) static
References brw_context::base, brw_upload_sampler_state_table(), brw_context::fragment_program, gl_program::fs, and brw_context::wm.
brw_upload_gs_samplers()
static void brw_upload_gs_samplers (struct brw_context * brw) static
References brw_context::base, brw_upload_sampler_state_table(), brw_context::geometry_program, brw_context::gs, and if().
brw_upload_sampler_state_table()
static void brw_upload_sampler_state_table (struct brw_context * brw, struct gl_program * prog, struct brw_stage_state * stage_state) static
References gl_texture_unit::_Current, BRW_NEW_SAMPLER_STATE_TABLE, brw_state_batch(), brw_context::ctx, brw_context::gen, gen7_emit_sampler_state_pointers_xs(), gl_context::NewDriverState, brw_stage_state::sampler_count, brw_stage_state::sampler_offset, gl_program::SamplersUsed, gl_program::SamplerUnits, brw_stage_state::stage, gl_context::Texture, gl_texture_attrib::Unit, and update_sampler_state().
Referenced by brw_upload_cs_samplers(), brw_upload_fs_samplers(), brw_upload_gs_samplers(), brw_upload_tcs_samplers(), brw_upload_tes_samplers(), and brw_upload_vs_samplers().
brw_upload_tcs_samplers()
static void brw_upload_tcs_samplers (struct brw_context * brw) static
References brw_context::base, brw_upload_sampler_state_table(), if(), brw_context::tcs, and brw_context::tess_ctrl_program.
brw_upload_tes_samplers()
static void brw_upload_tes_samplers (struct brw_context * brw) static
References brw_context::base, brw_upload_sampler_state_table(), if(), brw_context::tes, and brw_context::tess_eval_program.
brw_upload_vs_samplers()
static void brw_upload_vs_samplers (struct brw_context * brw) static
References brw_context::base, brw_upload_sampler_state_table(), brw_context::vertex_program, and brw_context::vs.
gen7_emit_sampler_state_pointers_xs()
static void gen7_emit_sampler_state_pointers_xs (struct brw_context * brw, struct brw_stage_state * stage_state) static
Emit a 3DSTATE_SAMPLER_STATE_POINTERS_{VS,HS,GS,DS,PS} packet.
References _3DSTATE_SAMPLER_STATE_POINTERS_DS, _3DSTATE_SAMPLER_STATE_POINTERS_GS, _3DSTATE_SAMPLER_STATE_POINTERS_HS, _3DSTATE_SAMPLER_STATE_POINTERS_PS, _3DSTATE_SAMPLER_STATE_POINTERS_VS, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, gen7_emit_vs_workaround_flush(), brw_context::is_baytrail, brw_context::is_haswell, OUT_BATCH, brw_stage_state::sampler_offset, and brw_stage_state::stage.
Referenced by brw_upload_sampler_state_table().
has_component()
static bool has_component (mesa_format format, int i) static
References _mesa_format_has_color_component(), and _mesa_is_format_color_format().
Referenced by upload_default_color().
translate_wrap_mode()
static uint32_t translate_wrap_mode (struct brw_context * brw, GLenum wrap, bool using_nearest) static
References BRW_TEXCOORDMODE_CLAMP, BRW_TEXCOORDMODE_CLAMP_BORDER, BRW_TEXCOORDMODE_MIRROR, BRW_TEXCOORDMODE_MIRROR_ONCE, BRW_TEXCOORDMODE_WRAP, brw_context::gen, and GEN8_TEXCOORDMODE_HALF_BORDER.
Referenced by brw_update_sampler_state().
update_sampler_state()
static void update_sampler_state (struct brw_context * brw, int unit, uint32_t * sampler_state, uint32_t batch_offset_for_sampler_state) static
References gl_texture_image::_BaseFormat, gl_texture_unit::_Current, gl_texture_object::BaseLevel, brw_update_sampler_state(), brw_context::ctx, gl_texture_attrib::CubeMapSeamless, gl_texture_object::Image, gl_texture_unit::LodBias, gl_texture_object::Target, gl_texture_image::TexFormat, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_upload_sampler_state_table().
upload_default_color()
static void upload_default_color (struct brw_context * brw, const struct gl_sampler_object * sampler, mesa_format format, GLenum base_format, bool is_integer_format, bool is_stencil_sampling, uint32_t * sdc_offset) static
Upload SAMPLER_BORDER_COLOR_STATE.
References _mesa_get_format_bits(), gen5_sampler_default_color::b, gl_sampler_object::BorderColor, brw_state_batch(), gl_color_union::f, gen5_sampler_default_color::f, float_as_int(), brw_context::gen, has_component(), gen5_sampler_default_color::hf, gl_color_union::i, brw_context::is_haswell, MESA_FORMAT_S_UINT8, gen5_sampler_default_color::s, gen5_sampler_default_color::ub, gl_color_union::ui, UNCLAMPED_FLOAT_TO_SHORT, UNCLAMPED_FLOAT_TO_UBYTE, UNCLAMPED_FLOAT_TO_USHORT, and gen5_sampler_default_color::us.
Referenced by brw_update_sampler_state().
wrap_mode_needs_border_color()
static bool wrap_mode_needs_border_color (unsigned wrap_mode) static
Return true if the given wrap mode requires the border color to exist.
References BRW_TEXCOORDMODE_CLAMP_BORDER, and GEN8_TEXCOORDMODE_HALF_BORDER.
Referenced by brw_update_sampler_state().
Variable Documentation
brw_cs_samplers
const struct brw_tracked_state brw_cs_samplers
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_COMPUTE_PROGRAM,
   },
   .emit = brw_upload_cs_samplers,
}
brw_fs_samplers
const struct brw_tracked_state brw_fs_samplers
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_FRAGMENT_PROGRAM,
   },
   .emit = brw_upload_fs_samplers,
}
brw_gs_samplers
const struct brw_tracked_state brw_gs_samplers
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GEOMETRY_PROGRAM,
   },
   .emit = brw_upload_gs_samplers,
}
brw_tcs_samplers
const struct brw_tracked_state brw_tcs_samplers
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_TESS_PROGRAMS,
   },
   .emit = brw_upload_tcs_samplers,
}
brw_tes_samplers
const struct brw_tracked_state brw_tes_samplers
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_TESS_PROGRAMS,
   },
   .emit = brw_upload_tes_samplers,
}
brw_vs_samplers
const struct brw_tracked_state brw_vs_samplers
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VERTEX_PROGRAM,
   },
   .emit = brw_upload_vs_samplers,
}