Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_draw.h File Reference
#include "main/mtypes.h"
#include "intel_bufmgr.h"
Macros
#define EMIT_VERTEX_BUFFER_STATE(...)
Functions
uint32_t * brw_emit_vertex_buffer_state (struct brw_context *brw, unsigned buffer_nr, drm_intel_bo *bo, unsigned start_offset, unsigned end_offset, unsigned stride, unsigned step_rate, uint32_t *__map)
Emit a VERTEX_BUFFER_STATE entry (part of 3DSTATE_VERTEX_BUFFERS).
void brw_draw_prims (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *unused_tfb_object, unsigned stream, struct gl_buffer_object *indirect)
void brw_draw_init (struct brw_context *brw)
void brw_draw_destroy (struct brw_context *brw)
void brw_prepare_shader_draw_parameters (struct brw_context *)
GLboolean brw_handle_primitive_restart (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, struct gl_buffer_object *indirect)
Check if primitive restart is enabled, and if so, handle it properly.
Macro Definition Documentation
EMIT_VERTEX_BUFFER_STATE
#define EMIT_VERTEX_BUFFER_STATE (...)
Value:
__map = \
   brw_emit_vertex_buffer_state(__VA_ARGS__, __map)
Referenced by brw_emit_vertices(), and gen8_emit_vertices().
Function Documentation
brw_draw_destroy()
void brw_draw_destroy (struct brw_context * brw)
References brw_vertex_buffer::bo, brw_vertex_element::buffer, brw_context::buffers, brw_context::enabled, brw_context::ib, brw_context::nr_buffers, brw_context::nr_enabled, and brw_context::vb.
Referenced by intelDestroyContext().
brw_draw_init()
void brw_draw_init (struct brw_context * brw)
References brw_draw_prims(), brw_vertex_element::buffer, brw_context::ctx, vbo_context::draw_prims, brw_context::inputs, brw_context::nr_buffers, brw_context::nr_enabled, and brw_context::vb.
Referenced by brwCreateContext().
brw_draw_prims()
void brw_draw_prims (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object * unused_tfb_object, unsigned stream, struct gl_buffer_object * indirect)
References gl_array_attrib::_DrawArrays, _mesa_enum_to_string(), _swsetup_Wakeup(), _tnl_draw_prims(), _tnl_wakeup(), gl_context::Array, brw_check_conditional_render(), brw_context(), brw_handle_primitive_restart(), brw_try_draw_prims(), gl_context::RenderMode, vbo_all_varyings_in_vbos(), and vbo_get_minmax_indices().
Referenced by brw_draw_init(), and brw_handle_primitive_restart().
brw_emit_vertex_buffer_state()
uint32_t* brw_emit_vertex_buffer_state (struct brw_context * brw, unsigned buffer_nr, drm_intel_bo * bo, unsigned start_offset, unsigned end_offset, unsigned stride, unsigned step_rate, uint32_t * __map)
Emit a VERTEX_BUFFER_STATE entry (part of 3DSTATE_VERTEX_BUFFERS).
References BDW_MOCS_WB, BRW_VB0_ACCESS_INSTANCEDATA, BRW_VB0_ACCESS_VERTEXDATA, BRW_VB0_INDEX_SHIFT, BRW_VB0_PITCH_SHIFT, brw_context::ctx, brw_context::gen, GEN6_VB0_ACCESS_INSTANCEDATA, GEN6_VB0_ACCESS_VERTEXDATA, GEN6_VB0_INDEX_SHIFT, GEN7_MOCS_L3, GEN7_VB0_ADDRESS_MODIFYENABLE, OUT_BATCH, OUT_RELOC, OUT_RELOC64, and SKL_MOCS_WB.
brw_handle_primitive_restart()
GLboolean brw_handle_primitive_restart (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, struct gl_buffer_object * indirect)
Check if primitive restart is enabled, and if so, handle it properly.
In some cases the support will be handled in software. When available hardware will handle primitive restart.
References gl_array_attrib::_PrimitiveRestart, gl_context::Array, brw_context(), brw_draw_prims(), can_cut_index_handle_prims(), brw_context::enable_cut_index, brw_context::in_progress, brw_context::prim_restart, and vbo_sw_primitive_restart().
Referenced by brw_draw_prims().
brw_prepare_shader_draw_parameters()
void brw_prepare_shader_draw_parameters (struct brw_context *)
References brw_context::base, brw_context::draw, brw_context::draw_id_bo, brw_context::draw_id_offset, brw_context::draw_params_bo, brw_context::draw_params_offset, brw_context::gl_drawid, intel_upload_data(), brw_context::params, brw_stage_state::prog_data, and brw_context::vs.
Referenced by brw_emit_vertices(), and gen8_emit_vertices().