Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_reset.c File Reference
#include "main/context.h"
#include "brw_context.h"
Functions
GLenum brw_get_graphics_reset_status (struct gl_context *ctx)
Query information about GPU resets observed by this context.
void brw_check_for_reset (struct brw_context *brw)
Function Documentation
brw_check_for_reset()
void brw_check_for_reset (struct brw_context * brw)
References _mesa_set_context_lost_dispatch(), brw_context::ctx, brw_context::hw_ctx, and brw_context::reset_count.
Referenced by brw_get_index_type(), and do_flush_locked().
brw_get_graphics_reset_status()
GLenum brw_get_graphics_reset_status (struct gl_context * ctx)
Query information about GPU resets observed by this context.
Called via dd_function_table::GetGraphicsResetStatus.
References brw_context(), brw_context::hw_ctx, and brw_context::reset_count.
Referenced by brw_get_index_type(), and brwCreateContext().