Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_gs_surface_state.c File Reference
#include "main/mtypes.h"
#include "program/prog_parameter.h"
#include "main/shaderapi.h"
#include "brw_context.h"
#include "brw_state.h"
Functions
static void brw_upload_gs_pull_constants (struct brw_context *brw)
static void brw_upload_gs_ubo_surfaces (struct brw_context *brw)
static void brw_upload_gs_abo_surfaces (struct brw_context *brw)
static void brw_upload_gs_image_surfaces (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_gs_pull_constants
const struct brw_tracked_state brw_gs_ubo_surfaces
const struct brw_tracked_state brw_gs_abo_surfaces
const struct brw_tracked_state brw_gs_image_surfaces
Function Documentation
brw_upload_gs_abo_surfaces()
static void brw_upload_gs_abo_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_abo_surfaces(), brw_context::geometry_program, brw_context::gs, and brw_stage_state::prog_data.
brw_upload_gs_image_surfaces()
static void brw_upload_gs_image_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_image_surfaces(), brw_context::geometry_program, brw_context::gs, and brw_stage_state::prog_data.
brw_upload_gs_pull_constants()
static void brw_upload_gs_pull_constants (struct brw_context * brw) static
References _mesa_shader_write_subroutine_indices(), brw_context::base, BRW_NEW_GS_CONSTBUF, brw_upload_pull_constants(), brw_context::ctx, brw_context::geometry_program, brw_context::gs, if(), brw_stage_state::prog_data, and brw_program::program.
brw_upload_gs_ubo_surfaces()
static void brw_upload_gs_ubo_surfaces (struct brw_context * brw) static
References gl_context::_Shader, brw_context::base, brw_upload_ubo_surfaces(), brw_context::ctx, gl_pipeline_object::CurrentProgram, brw_context::gs, and brw_stage_state::prog_data.
Variable Documentation
brw_gs_abo_surfaces
const struct brw_tracked_state brw_gs_abo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_ATOMIC_BUFFER |
             BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GS_PROG_DATA,
   },
   .emit = brw_upload_gs_abo_surfaces,
}
brw_gs_image_surfaces
const struct brw_tracked_state brw_gs_image_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GEOMETRY_PROGRAM |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_IMAGE_UNITS,
   },
   .emit = brw_upload_gs_image_surfaces,
}
brw_gs_pull_constants
const struct brw_tracked_state brw_gs_pull_constants
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GEOMETRY_PROGRAM |
             BRW_NEW_GS_PROG_DATA,
   },
   .emit = brw_upload_gs_pull_constants,
}
brw_gs_ubo_surfaces
const struct brw_tracked_state brw_gs_ubo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_UNIFORM_BUFFER,
   },
   .emit = brw_upload_gs_ubo_surfaces,
}