Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_state_batch.c File Reference
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "main/imports.h"
#include "util/hash_table.h"
#include "util/ralloc.h"
Functions
uint32_t brw_state_batch_size (struct brw_context *brw, uint32_t offset)
void * brw_state_batch (struct brw_context *brw, int size, int alignment, uint32_t *out_offset)
Allocates a block of space in the batchbuffer for indirect state.
Function Documentation
brw_state_batch()
void* brw_state_batch (struct brw_context * brw, int size, int alignment, uint32_t * out_offset)
Allocates a block of space in the batchbuffer for indirect state.
We don't want to allocate separate BOs for every bit of indirect state in the driver. It means overallocating by a significant margin (4096 bytes, even if the object is just a 20-byte surface state), and more buffers to walk and count for aperture size checking.
However, due to the restrictions imposed by the aperture size checking performance hacks, we can't have the batch point at a separate indirect state buffer, because once the batch points at it, no more relocations can be added to it. So, we sneak these buffers in at the top of the batchbuffer.
References brw_context::batch, intel_batchbuffer::bo, intel_batchbuffer_flush, intel_batchbuffer::map, intel_batchbuffer::reserved_space, intel_batchbuffer::state_batch_offset, intel_batchbuffer::state_batch_sizes, and USED_BATCH.
Referenced by blorp_alloc_binding_table(), blorp_alloc_dynamic_state(), blorp_alloc_vertex_buffer(), brw_emit_buffer_surface_state(), brw_emit_null_surface_state(), brw_emit_surface_state(), brw_gs_upload_binding_table(), brw_update_sol_surface(), brw_upload_binding_table(), brw_upload_cc_vp(), brw_upload_clip_unit(), brw_upload_cs_push_constants(), brw_upload_cs_state(), brw_upload_gs_unit(), brw_upload_sampler_state_table(), brw_upload_vs_unit(), brw_upload_wm_unit(), gen4_update_renderbuffer_surface(), gen6_upload_blend_state(), gen6_upload_color_calc_state(), gen6_upload_depth_stencil_state(), gen6_upload_push_constants(), gen6_upload_scissor_state(), gen6_upload_sf_and_clip_viewports(), gen7_emit_null_surface_state(), gen7_upload_sf_clip_viewport(), gen8_allocate_surface_state(), gen8_upload_blend_state(), gen8_upload_sf_clip_viewport(), upload_cc_unit(), upload_clip_vp(), upload_default_color(), upload_sf_unit(), and upload_sf_vp().
brw_state_batch_size()
uint32_t brw_state_batch_size (struct brw_context * brw, uint32_t offset)
References brw_context::batch, and intel_batchbuffer::state_batch_sizes.
Referenced by intel_batchbuffer_require_space().