Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_formatquery.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "main/context.h"
#include "main/formatquery.h"
#include "main/glformats.h"
Functions
static size_t brw_query_samples_for_format (struct gl_context *ctx, GLenum target, GLenum internalFormat, int samples[16])
void brw_query_internal_format (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint *params)
Function Documentation
brw_query_internal_format()
void brw_query_internal_format (struct gl_context * ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint * params)
References _mesa_query_internal_format_default(), brw_query_samples_for_format(), and brw_context::num_samples.
Referenced by brw_depth_writes_enabled(), and brw_init_driver_functions().
brw_query_samples_for_format()
static size_t brw_query_samples_for_format (struct gl_context * ctx, GLenum target, GLenum internalFormat, int samples[16]) static
References brw_context(), brw_context::gen, and void.
Referenced by brw_query_internal_format().