Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_vs_surface_state.c File Reference
#include "main/mtypes.h"
#include "program/prog_parameter.h"
#include "main/shaderapi.h"
#include "brw_context.h"
#include "brw_state.h"
#include "intel_buffer_objects.h"
Functions
void brw_upload_pull_constants (struct brw_context *brw, GLbitfield64 brw_new_constbuf, const struct gl_program *prog, struct brw_stage_state *stage_state, const struct brw_stage_prog_data *prog_data)
Creates a temporary BO containing the pull constant data for the shader stage, and the SURFACE_STATE struct that points at it.
static void brw_upload_vs_pull_constants (struct brw_context *brw)
static void brw_upload_vs_ubo_surfaces (struct brw_context *brw)
static void brw_upload_vs_abo_surfaces (struct brw_context *brw)
static void brw_upload_vs_image_surfaces (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_vs_pull_constants
const struct brw_tracked_state brw_vs_ubo_surfaces
const struct brw_tracked_state brw_vs_abo_surfaces
const struct brw_tracked_state brw_vs_image_surfaces
Function Documentation
brw_upload_pull_constants()
void brw_upload_pull_constants (struct brw_context * brw, GLbitfield64 brw_new_constbuf, const struct gl_program * prog, struct brw_stage_state * stage_state, const struct brw_stage_prog_data * prog_data)
Creates a temporary BO containing the pull constant data for the shader stage, and the SURFACE_STATE struct that points at it.
Pull constants are GLSL uniforms (and other constant data) beyond what we could fit as push constants, or that have variable-index array access (which is easiest to support using pull constants, and avoids filling register space with mostly-unused data).
Compare this path to brw_curbe.c for gen4/5 push constants, and gen6_vs_state.c for gen6+ push constants.
References brw_create_constant_surface(), brw_context::ctx, intel_upload_space(), gl_context::NewDriverState, gl_program::Parameters, and brw_stage_state::surf_offset.
Referenced by brw_upload_cs_pull_constants(), brw_upload_gs_pull_constants(), brw_upload_tcs_pull_constants(), brw_upload_tes_pull_constants(), brw_upload_vs_pull_constants(), and brw_upload_wm_pull_constants().
brw_upload_vs_abo_surfaces()
static void brw_upload_vs_abo_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_abo_surfaces(), brw_stage_state::prog_data, brw_context::vertex_program, and brw_context::vs.
brw_upload_vs_image_surfaces()
static void brw_upload_vs_image_surfaces (struct brw_context * brw) static
References brw_context::base, brw_upload_image_surfaces(), brw_stage_state::prog_data, brw_context::vertex_program, and brw_context::vs.
brw_upload_vs_pull_constants()
static void brw_upload_vs_pull_constants (struct brw_context * brw) static
References _mesa_shader_write_subroutine_indices(), brw_context::base, BRW_NEW_VS_CONSTBUF, brw_upload_pull_constants(), brw_context::ctx, brw_stage_state::prog_data, brw_program::program, brw_context::vertex_program, and brw_context::vs.
brw_upload_vs_ubo_surfaces()
static void brw_upload_vs_ubo_surfaces (struct brw_context * brw) static
References gl_context::_Shader, brw_context::base, brw_upload_ubo_surfaces(), brw_context::ctx, gl_pipeline_object::CurrentProgram, brw_stage_state::prog_data, and brw_context::vs.
Variable Documentation
brw_vs_abo_surfaces
const struct brw_tracked_state brw_vs_abo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_ATOMIC_BUFFER |
             BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_upload_vs_abo_surfaces,
}
brw_vs_image_surfaces
const struct brw_tracked_state brw_vs_image_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TEXTURE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_IMAGE_UNITS |
             BRW_NEW_VERTEX_PROGRAM |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_upload_vs_image_surfaces,
}
brw_vs_pull_constants
const struct brw_tracked_state brw_vs_pull_constants
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VERTEX_PROGRAM |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_upload_vs_pull_constants,
}
brw_vs_ubo_surfaces
const struct brw_tracked_state brw_vs_ubo_surfaces
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_UNIFORM_BUFFER |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_upload_vs_ubo_surfaces,
}