Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_tcs.c File Reference
Tessellation control shader state upload code.
#include "brw_context.h"
#include "compiler/brw_nir.h"
#include "brw_program.h"
#include "brw_state.h"
#include "program/prog_parameter.h"
#include "nir_builder.h"
Functions
static nir_shader * create_passthrough_tcs (void *mem_ctx, const struct brw_compiler *compiler, const nir_shader_compiler_options *options, const struct brw_tcs_prog_key *key)
static void brw_tcs_debug_recompile (struct brw_context *brw, struct gl_program *prog, const struct brw_tcs_prog_key *key)
static bool brw_codegen_tcs_prog (struct brw_context *brw, struct brw_program *tcp, struct brw_program *tep, struct brw_tcs_prog_key *key)
void brw_tcs_populate_key (struct brw_context *brw, struct brw_tcs_prog_key *key)
void brw_upload_tcs_prog (struct brw_context *brw)
bool brw_tcs_precompile (struct gl_context *ctx, struct gl_shader_program *shader_prog, struct gl_program *prog)
Detailed Description
Tessellation control shader state upload code.
Function Documentation
brw_codegen_tcs_prog()
static bool brw_codegen_tcs_prog (struct brw_context * brw, struct brw_program * tcp, struct brw_program * tep, struct brw_tcs_prog_key * key) static
References _mesa_problem(), brw_context::base, brw_context::batch, brw_alloc_stage_scratch(), brw_assign_common_binding_table_offsets(), BRW_CACHE_TCS_PROG, brw_get_shader_time_index(), brw_nir_setup_glsl_uniforms(), brw_tcs_debug_recompile(), brw_upload_cache(), brw_context::cache, brw_program::compiled_once, intel_screen::compiler, gl_context::Const, create_passthrough_tcs(), brw_context::ctx, for(), get_time(), gl_program::info, intel_batchbuffer::last_bo, linking_failure, gl_program::nir, gl_shader_compiler_options::NirOptions, gl_tess_ctrl_program_state::patch_default_inner_level, gl_tess_ctrl_program_state::patch_default_outer_level, brw_context::perf_debug, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_program::program, brw_context::screen, gl_program::sh, gl_constants::ShaderCompilerOptions, ST_TCS, brw_context::tcs, and gl_context::TessCtrlProgram.
Referenced by brw_tcs_precompile(), and brw_upload_tcs_prog().
brw_tcs_debug_recompile()
static void brw_tcs_debug_recompile (struct brw_context * brw, struct gl_program * prog, const struct brw_tcs_prog_key * key) static
References BRW_CACHE_TCS_PROG, brw_debug_recompile_sampler_key(), brw_find_previous_compile(), brw_context::cache, gl_program::Id, and key_debug().
Referenced by brw_codegen_tcs_prog().
brw_tcs_populate_key()
void brw_tcs_populate_key (struct brw_context * brw, struct brw_tcs_prog_key * key)
References brw_populate_sampler_prog_key_data(), brw_context::ctx, brw_context::gen, brw_program::id, gl_program::info, gl_tess_ctrl_program_state::patch_vertices, brw_program::program, brw_context::tess_ctrl_program, brw_context::tess_eval_program, and gl_context::TessCtrlProgram.
Referenced by brw_upload_tcs_prog().
brw_tcs_precompile()
bool brw_tcs_precompile (struct gl_context * ctx, struct gl_shader_program * shader_prog, struct gl_program * prog)
References gl_shader_program::_LinkedShaders, brw_context::base, brw_codegen_tcs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_context::gen, brw_program::id, gl_program::info, gl_program::nir, brw_stage_state::prog_data, brw_stage_state::prog_offset, gl_linked_shader::Program, and brw_context::tcs.
Referenced by brw_shader_precompile().
brw_upload_tcs_prog()
void brw_upload_tcs_prog (struct brw_context * brw)
References _NEW_TEXTURE, brw_context::base, BRW_CACHE_TCS_PROG, brw_codegen_tcs_prog(), BRW_NEW_PATCH_PRIMITIVE, BRW_NEW_TESS_PROGRAMS, brw_search_cache(), brw_state_dirty(), brw_tcs_populate_key(), brw_context::cache, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::tcs, brw_context::tess_ctrl_program, brw_context::tess_eval_program, and void.
Referenced by brw_upload_tess_programs().
create_passthrough_tcs()
static nir_shader* create_passthrough_tcs (void * mem_ctx, const struct brw_compiler * compiler, const nir_shader_compiler_options * options, const struct brw_tcs_prog_key * key) static
References BITFIELD64_BIT.
Referenced by brw_codegen_tcs_prog().