Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_link.cpp File Reference
#include "brw_context.h"
#include "compiler/brw_nir.h"
#include "brw_program.h"
#include "compiler/glsl/ir.h"
#include "compiler/glsl/ir_optimization.h"
#include "compiler/glsl/program.h"
#include "program/program.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/uniforms.h"
Functions
static bool brw_shader_precompile (struct gl_context *ctx, struct gl_shader_program *sh_prog)
Performs a compile of the shader stages even when we don't know what non-orthogonal state will be set, in the hope that it reflects the eventual NOS used, and thus allows us to produce link failures.
static void brw_lower_packing_builtins (struct brw_context *brw, exec_list *ir)
static void process_glsl_ir (struct brw_context *brw, struct gl_shader_program *shader_prog, struct gl_linked_shader *shader)
static void unify_interfaces (struct shader_info **infos)
GLboolean brw_link_shader (struct gl_context *ctx, struct gl_shader_program *shProg)
Function Documentation
brw_link_shader()
GLboolean brw_link_shader (struct gl_context * ctx, struct gl_shader_program * shProg)
References gl_shader_program::_LinkedShaders, _mesa_copy_linked_program_data(), _mesa_print_ir(), _mesa_update_shader_textures_used(), gl_context::_Shader, brw_context(), brw_create_nir(), brw_shader_precompile(), build_program_resource_list(), intel_screen::compiler, gl_pipeline_object::Flags, GLSL_DUMP, gl_linked_shader::ir, gl_shader_program::Name, gl_program::nir, gl_shader_program::NumShaders, gl_program::Parameters, brw_context::precompile, process_glsl_ir(), gl_linked_shader::Program, brw_context::screen, gl_shader_program::SeparateShader, gl_shader_program::Shaders, gl_linked_shader::shadow_samplers, gl_program::ShadowSamplers, gl_shader::Source, gl_linked_shader::Stage, gl_shader::Stage, and unify_interfaces().
Referenced by brwInitFragProgFuncs().
brw_lower_packing_builtins()
static void brw_lower_packing_builtins (struct brw_context * brw, exec_list * ir) static
References brw_context::gen, LOWER_PACK_HALF_2x16, lower_packing_builtins(), and LOWER_UNPACK_HALF_2x16.
Referenced by process_glsl_ir().
brw_shader_precompile()
static bool brw_shader_precompile (struct gl_context * ctx, struct gl_shader_program * sh_prog) static
Performs a compile of the shader stages even when we don't know what non-orthogonal state will be set, in the hope that it reflects the eventual NOS used, and thus allows us to produce link failures.
References gl_shader_program::_LinkedShaders, brw_cs_precompile(), brw_fs_precompile(), brw_gs_precompile(), brw_tcs_precompile(), brw_tes_precompile(), brw_vs_precompile(), and gl_linked_shader::Program.
Referenced by brw_link_shader().
process_glsl_ir()
static void process_glsl_ir (struct brw_context * brw, struct gl_shader_program * shader_prog, struct gl_linked_shader * shader) static
References _mesa_print_ir(), gl_context::_Shader, BIT_COUNT_TO_MATH, brw_do_channel_expressions(), brw_do_vector_splitting(), brw_lower_packing_builtins(), intel_screen::compiler, gl_context::Const, brw_context::ctx, DFREXP_DLDEXP_TO_ARITH, DIV_TO_MUL_RCP, do_common_optimization(), do_lower_texture_projection(), do_mat_op_to_vec(), do_vec_index_to_cond_assign(), EXP_TO_EXP2, EXTRACT_TO_SHIFTS, gl_pipeline_object::Flags, brw_context::gen, GLSL_DUMP, INSERT_TO_SHIFTS, gl_linked_shader::ir, LOG_TO_LOG2, lower_blend_equation_advanced(), lower_if_to_cond_assign(), lower_instructions(), lower_noise(), lower_offset_arrays(), lower_quadop_vector(), lower_vector_insert(), gl_shader_program::Name, gl_constants::NativeIntegers, reparent_ir(), REVERSE_TO_SHIFTS, brw_context::screen, gl_constants::ShaderCompilerOptions, gl_linked_shader::Stage, SUB_TO_ADD_NEG, and validate_ir_tree().
Referenced by brw_link_shader().
unify_interfaces()
static void unify_interfaces (struct shader_info ** infos) static
Referenced by brw_link_shader().