Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_ff_gs_emit.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "program/program.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_ff_gs.h"
Functions
static void brw_ff_gs_alloc_regs (struct brw_ff_gs_compile *c, GLuint nr_verts, bool sol_program)
Allocate registers for GS.
static void brw_ff_gs_initialize_header (struct brw_ff_gs_compile *c)
Set up the initial value of c->reg.header register based on c->reg.R0.
static void brw_ff_gs_overwrite_header_dw2 (struct brw_ff_gs_compile *c, unsigned dw2)
Overwrite DWORD 2 of c->reg.header with the given immediate unsigned value.
static void brw_ff_gs_overwrite_header_dw2_from_r0 (struct brw_ff_gs_compile *c)
Overwrite DWORD 2 of c->reg.header with the primitive type from c->reg.R0.
static void brw_ff_gs_offset_header_dw2 (struct brw_ff_gs_compile *c, int offset)
Apply an additive offset to DWORD 2 of c->reg.header.
static void brw_ff_gs_emit_vue (struct brw_ff_gs_compile *c, struct brw_reg vert, bool last)
Emit a vertex using the URB_WRITE message.
static void brw_ff_gs_ff_sync (struct brw_ff_gs_compile *c, int num_prim)
Send an FF_SYNC message to ensure that all previously spawned GS threads have finished sending primitives down the pipeline, and to allocate a URB entry for the first output vertex.
void brw_ff_gs_quads (struct brw_ff_gs_compile *c, struct brw_ff_gs_prog_key *key)
void brw_ff_gs_quad_strip (struct brw_ff_gs_compile *c, struct brw_ff_gs_prog_key *key)
void brw_ff_gs_lines (struct brw_ff_gs_compile *c)
void gen6_sol_program (struct brw_ff_gs_compile *c, struct brw_ff_gs_prog_key *key, unsigned num_verts, bool check_edge_flags)
Generate the geometry shader program used on Gen6 to perform stream output (transform feedback).
Function Documentation
brw_ff_gs_alloc_regs()
static void brw_ff_gs_alloc_regs (struct brw_ff_gs_compile * c, GLuint nr_verts, bool sol_program) static
Allocate registers for GS.
If sol_program is true, then:
The thread will be spawned with the "SVBI Payload Enable" bit set, so GRF 1 needs to be set aside to hold the streamed vertex buffer indices.
The thread will need to use the destination_indices register.
References brw_ff_gs_compile::destination_indices, GLuint, brw_ff_gs_compile::header, brw_ff_gs_compile::nr_regs, brw_ff_gs_compile::prog_data, brw_ff_gs_compile::R0, brw_ff_gs_compile::reg, brw_ff_gs_compile::SVBI, brw_ff_gs_compile::temp, brw_ff_gs_prog_data::total_grf, brw_ff_gs_prog_data::urb_read_length, and brw_ff_gs_compile::vertex.
Referenced by brw_ff_gs_lines(), brw_ff_gs_quad_strip(), brw_ff_gs_quads(), and gen6_sol_program().
brw_ff_gs_emit_vue()
static void brw_ff_gs_emit_vue (struct brw_ff_gs_compile * c, struct brw_reg vert, bool last) static
Emit a vertex using the URB_WRITE message.
Use the contents of c->reg.header for the message header, and the registers starting at vert for the vertex data.
If last is true, then this is the last vertex, so no further URB space should be allocated, and this message should end the thread.
If last is false, then a new URB entry will be allocated, and its handle will be stored in DWORD 0 of c->reg.header for use in the next URB_WRITE message.
References brw_ff_gs_compile::func, brw_ff_gs_compile::header, brw_ff_gs_compile::nr_regs, brw_ff_gs_compile::reg, and brw_ff_gs_compile::temp.
Referenced by brw_ff_gs_lines(), brw_ff_gs_quad_strip(), brw_ff_gs_quads(), and gen6_sol_program().
brw_ff_gs_ff_sync()
static void brw_ff_gs_ff_sync (struct brw_ff_gs_compile * c, int num_prim) static
Send an FF_SYNC message to ensure that all previously spawned GS threads have finished sending primitives down the pipeline, and to allocate a URB entry for the first output vertex.
Only needed on Ironlake+.
This function modifies c->reg.header: in DWORD 1, it stores num_prim (which is needed by the FF_SYNC message), and in DWORD 0, it stores the handle to the allocated URB entry (which will be needed by the URB_WRITE meesage that follows).
References brw_ff_gs_compile::func, brw_ff_gs_compile::header, brw_ff_gs_compile::reg, and brw_ff_gs_compile::temp.
Referenced by brw_ff_gs_lines(), brw_ff_gs_quad_strip(), brw_ff_gs_quads(), and gen6_sol_program().
brw_ff_gs_initialize_header()
static void brw_ff_gs_initialize_header (struct brw_ff_gs_compile * c) static
Set up the initial value of c->reg.header register based on c->reg.R0.
The following information is passed to the GS thread in R0, and needs to be included in the first URB_WRITE or FF_SYNC message sent by the GS:
DWORD 0 [31:0] handle info (Gen4 only)
DWORD 5 [7:0] FFTID
DWORD 6 [31:0] Debug info
DWORD 7 [31:0] Debug info
This function sets up the above data by copying by copying the contents of R0 to the header register.
References brw_ff_gs_compile::func, brw_ff_gs_compile::header, brw_ff_gs_compile::R0, and brw_ff_gs_compile::reg.
Referenced by brw_ff_gs_lines(), brw_ff_gs_quad_strip(), brw_ff_gs_quads(), and gen6_sol_program().
brw_ff_gs_lines()
void brw_ff_gs_lines (struct brw_ff_gs_compile * c)
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_overwrite_header_dw2(), brw_ff_gs_compile::func, brw_ff_gs_compile::reg, and brw_ff_gs_compile::vertex.
Referenced by brw_codegen_ff_gs_prog().
brw_ff_gs_offset_header_dw2()
static void brw_ff_gs_offset_header_dw2 (struct brw_ff_gs_compile * c, int offset) static
Apply an additive offset to DWORD 2 of c->reg.header.
This is used to set/unset the "PrimStart" and "PrimEnd" flags appropriately for each vertex.
References brw_ff_gs_compile::func, brw_ff_gs_compile::header, and brw_ff_gs_compile::reg.
Referenced by gen6_sol_program().
brw_ff_gs_overwrite_header_dw2()
static void brw_ff_gs_overwrite_header_dw2 (struct brw_ff_gs_compile * c, unsigned dw2) static
Overwrite DWORD 2 of c->reg.header with the given immediate unsigned value.
In URB_WRITE messages, DWORD 2 contains the fields PrimType, PrimStart, PrimEnd, Increment CL_INVOCATIONS, and SONumPrimsWritten, many of which we need to be able to update on a per-vertex basis.
References brw_ff_gs_compile::func, brw_ff_gs_compile::header, and brw_ff_gs_compile::reg.
Referenced by brw_ff_gs_lines(), brw_ff_gs_quad_strip(), and brw_ff_gs_quads().
brw_ff_gs_overwrite_header_dw2_from_r0()
static void brw_ff_gs_overwrite_header_dw2_from_r0 (struct brw_ff_gs_compile * c) static
Overwrite DWORD 2 of c->reg.header with the primitive type from c->reg.R0.
When the thread is spawned, GRF 0 contains the primitive type in bits 4:0 of DWORD 2. URB_WRITE messages need the primitive type in bits 6:2 of DWORD 2. So this function extracts the primitive type field, bitshifts it appropriately, and stores it in c->reg.header.
References brw_ff_gs_compile::func, brw_ff_gs_compile::header, brw_ff_gs_compile::R0, and brw_ff_gs_compile::reg.
Referenced by gen6_sol_program().
brw_ff_gs_quad_strip()
void brw_ff_gs_quad_strip (struct brw_ff_gs_compile * c, struct brw_ff_gs_prog_key * key)
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_overwrite_header_dw2(), brw_ff_gs_compile::func, brw_ff_gs_prog_key::pv_first, brw_ff_gs_compile::reg, and brw_ff_gs_compile::vertex.
Referenced by brw_codegen_ff_gs_prog().
brw_ff_gs_quads()
void brw_ff_gs_quads (struct brw_ff_gs_compile * c, struct brw_ff_gs_prog_key * key)
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_overwrite_header_dw2(), brw_ff_gs_compile::func, brw_ff_gs_prog_key::pv_first, brw_ff_gs_compile::reg, and brw_ff_gs_compile::vertex.
Referenced by brw_codegen_ff_gs_prog().
gen6_sol_program()
void gen6_sol_program (struct brw_ff_gs_compile * c, struct brw_ff_gs_prog_key * key, unsigned num_verts, bool check_edge_flags)
Generate the geometry shader program used on Gen6 to perform stream output (transform feedback).
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_offset_header_dw2(), brw_ff_gs_overwrite_header_dw2_from_r0(), BRW_GS_EDGE_INDICATOR_0, BRW_GS_EDGE_INDICATOR_1, brw_ff_gs_compile::destination_indices, brw_ff_gs_compile::func, brw_ff_gs_compile::header, brw_ff_gs_prog_key::num_transform_feedback_bindings, brw_ff_gs_compile::prog_data, brw_ff_gs_prog_key::pv_first, brw_ff_gs_compile::R0, brw_ff_gs_compile::reg, brw_ff_gs_compile::SVBI, brw_ff_gs_prog_data::svbi_postincrement_value, brw_ff_gs_compile::temp, brw_ff_gs_prog_key::transform_feedback_bindings, brw_ff_gs_prog_key::transform_feedback_swizzles, brw_ff_gs_compile::vertex, and brw_ff_gs_compile::vue_map.
Referenced by brw_codegen_ff_gs_prog().