Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_wm_state.c File Reference
#include "intel_batchbuffer.h"
#include "intel_fbo.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_wm.h"
#include "compiler/nir/nir.h"
Functions
bool brw_color_buffer_write_enabled (struct brw_context *brw)
static void brw_upload_wm_unit (struct brw_context *brw)
Setup wm hardware state.
Variables
const struct brw_tracked_state brw_wm_unit
Function Documentation
brw_color_buffer_write_enabled()
bool brw_color_buffer_write_enabled (struct brw_context * brw)
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, BITFIELD64_BIT, gl_context::Color, gl_colorbuffer_attrib::ColorMask, brw_context::ctx, gl_context::DrawBuffer, brw_context::fragment_program, and gl_program::info.
Referenced by brw_upload_wm_unit(), gen8_upload_ps_blend(), gen8_upload_ps_extra(), and upload_wm_state().
brw_upload_wm_unit()
static void brw_upload_wm_unit (struct brw_context * brw) static
Setup wm hardware state.
See page 225 of Volume 2
References _3DSTATE_GLOBAL_DEPTH_OFFSET_CLAMP, ADVANCE_BATCH, gl_colorbuffer_attrib::AlphaEnabled, brw_context::base, brw_context::batch, BEGIN_BATCH, thread1::binding_table_entry_count, BITFIELD64_BIT, intel_batchbuffer::bo, brw_color_buffer_write_enabled(), BRW_FLOATING_POINT_IEEE_754, BRW_FLOATING_POINT_NON_IEEE_754, BRW_NEW_GEN4_UNIT_STATE, brw_program_reloc(), brw_state_batch(), BUFFER_DEPTH, gl_context::Color, thread3::const_urb_entry_read_length, thread3::const_urb_entry_read_offset, brw_context::ctx, brw_context::curbe, thread1::depth_coef_urb_read_offset, brw_wm_unit_state::depth_offset, intel_screen::devinfo, thread3::dispatch_grf_start_reg, gl_context::DrawBuffer, brw_wm_unit_state::early_depth_test, brw_wm_unit_state::enable_16_pix, brw_wm_unit_state::enable_8_pix, thread1::floating_point_mode, brw_context::fragment_program, brw_context::gen, brw_wm_unit_state::global_depth_offset_constant, brw_wm_unit_state::global_depth_offset_scale, thread0::grf_reg_count, brw_wm_unit_state::grf_reg_count_2, if(), gl_program::info, intel_get_renderbuffer(), thread0::kernel_start_pointer, brw_wm_unit_state::kernel_start_pointer_2, brw_wm_unit_state::legacy_global_depth_bias, brw_wm_unit_state::legacy_line_rast, gl_context::Line, brw_wm_unit_state::line_aa_region_width, brw_wm_unit_state::line_endcap_aa_region_width, brw_wm_unit_state::line_stipple, brw_wm_unit_state::max_threads, gl_context::NewDriverState, brw_context::offset_clamp, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetUnits, OUT_BATCH, OUT_BATCH_F, brw_stage_state::per_thread_scratch, thread2::per_thread_scratch_space, gl_context::Polygon, brw_wm_unit_state::polygon_stipple, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_wm_unit_state::program_computes_depth, brw_wm_unit_state::program_uses_depth, brw_wm_unit_state::program_uses_killpixel, brw_wm_unit_state::sampler_count, brw_stage_state::sampler_count, brw_stage_state::sampler_offset, brw_wm_unit_state::sampler_state_pointer, brw_stage_state::scratch_bo, thread2::scratch_space_base_pointer, brw_context::screen, brw_stage_state::state_offset, brw_wm_unit_state::stats_enable, brw_context::stats_wm, gl_polygon_attrib::StippleFlag, gl_line_attrib::StippleFlag, brw_wm_unit_state::thread0, brw_wm_unit_state::thread1, brw_wm_unit_state::thread2, brw_wm_unit_state::thread3, brw_wm_unit_state::thread_dispatch_enable, thread3::urb_entry_read_length, thread3::urb_entry_read_offset, brw_context::wm, brw_wm_unit_state::wm4, brw_wm_unit_state::wm5, brw_wm_unit_state::wm9, and brw_context::wm_start.
Variable Documentation
brw_wm_unit
const struct brw_tracked_state brw_wm_unit
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR |
              _NEW_LINE |
              _NEW_POLYGON |
              _NEW_POLYGONSTIPPLE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CURBE_OFFSETS |
             BRW_NEW_FRAGMENT_PROGRAM |
             BRW_NEW_FS_PROG_DATA |
             BRW_NEW_PROGRAM_CACHE |
             BRW_NEW_SAMPLER_STATE_TABLE |
             BRW_NEW_STATS_WM,
   },
   .emit = brw_upload_wm_unit,
}