Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_fs_channel_expressions.cpp File Reference
#include "brw_program.h"
#include "compiler/glsl/ir.h"
#include "compiler/glsl/ir_expression_flattening.h"
#include "compiler/glsl_types.h"
Data Structures
class ir_channel_expressions_visitor
Functions
static bool channel_expressions_predicate (ir_instruction *ir)
bool brw_do_channel_expressions (exec_list *instructions)
Function Documentation
brw_do_channel_expressions()
bool brw_do_channel_expressions (exec_list * instructions)
References channel_expressions_predicate(), do_expression_flattening(), ir_channel_expressions_visitor::progress, and visit_list_elements().
Referenced by process_glsl_ir().
channel_expressions_predicate()
static bool channel_expressions_predicate (ir_instruction * ir) static
References expr().
Referenced by brw_do_channel_expressions().