Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "main/framebuffer.h"
Functions
static void upload_clip_vp (struct brw_context *brw)
static void brw_upload_clip_unit (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_clip_unit
Function Documentation
brw_upload_clip_unit()
static void brw_upload_clip_unit (struct brw_context * brw) static
References brw_clip_unit_state::api_mode, brw_context::batch, intel_batchbuffer::bo, BRW_CLIP_API_DX, BRW_CLIP_API_OGL, BRW_CLIP_NDCSPACE, BRW_FLOATING_POINT_NON_IEEE_754, BRW_NEW_GEN4_UNIT_STATE, brw_program_reloc(), brw_state_batch(), brw_context::clip, brw_clip_unit_state::clip5, brw_clip_unit_state::clip6, brw_clip_unit_state::clip_mode, brw_context::clip_start, gl_transform_attrib::ClipDepthMode, brw_clip_unit_state::clipper_viewport_state_ptr, gl_transform_attrib::ClipPlanesEnabled, thread3::const_urb_entry_read_length, thread3::const_urb_entry_read_offset, brw_context::ctx, brw_context::curbe, gl_transform_attrib::DepthClamp, thread3::dispatch_grf_start_reg, gl_context::DrawBuffer, brw_clip_unit_state::floating_point_mode, brw_context::gen, thread0::grf_reg_count, brw_clip_unit_state::guard_band_enable, gl_viewport_attrib::Height, brw_context::is_g4x, thread0::kernel_start_pointer, brw_clip_unit_state::max_threads, brw_clip_unit_state::negative_w_clip_test, gl_context::NewDriverState, brw_context::nr_clip_entries, brw_clip_unit_state::nr_urb_entries, brw_context::prog_data, brw_context::prog_offset, brw_clip_unit_state::single_program_flow, brw_context::state_offset, brw_clip_unit_state::stats_enable, brw_clip_unit_state::thread0, brw_clip_unit_state::thread1, brw_clip_unit_state::thread3, brw_clip_unit_state::thread4, brw_ff_gs_prog_data::total_grf, gl_context::Transform, upload_clip_vp(), brw_context::urb, brw_clip_unit_state::urb_entry_allocation_size, thread3::urb_entry_read_length, thread3::urb_entry_read_offset, brw_ff_gs_prog_data::urb_read_length, brw_clip_unit_state::userclip_enable_flags, brw_clip_unit_state::userclip_must_clip, brw_clip_unit_state::vertex_position_space, brw_clip_unit_state::viewport_xmax, brw_clip_unit_state::viewport_xmin, brw_clip_unit_state::viewport_xy_clip_enable, brw_clip_unit_state::viewport_ymax, brw_clip_unit_state::viewport_ymin, brw_clip_unit_state::viewport_z_clip_enable, gl_context::ViewportArray, brw_context::vp_offset, brw_context::vsize, gl_viewport_attrib::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
upload_clip_vp()
static void upload_clip_vp (struct brw_context * brw) static
References brw_state_batch(), brw_context::clip, brw_context::ctx, gl_viewport_attrib::Height, gl_context::ViewportArray, brw_context::vp_offset, gl_viewport_attrib::Width, brw_clipper_viewport::xmax, brw_clipper_viewport::xmin, brw_clipper_viewport::ymax, and brw_clipper_viewport::ymin.
Referenced by brw_upload_clip_unit().
Variable Documentation
brw_clip_unit
const struct brw_tracked_state brw_clip_unit
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_TRANSFORM |
               _NEW_VIEWPORT,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_CLIP_PROG_DATA |
               BRW_NEW_CURBE_OFFSETS |
               BRW_NEW_PROGRAM_CACHE |
               BRW_NEW_URB_FENCE,
   },
   .emit = brw_upload_clip_unit,
}