Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_vs.c File Reference
#include "main/compiler.h"
#include "main/context.h"
#include "brw_context.h"
#include "brw_vs.h"
#include "brw_util.h"
#include "brw_state.h"
#include "program/prog_print.h"
#include "program/prog_parameter.h"
#include "compiler/brw_nir.h"
#include "brw_program.h"
#include "util/ralloc.h"
Functions
gl_clip_plane * brw_select_clip_planes (struct gl_context *ctx)
Decide which set of clip planes should be used when clipping via gl_Position or gl_ClipVertex.
GLbitfield64 brw_vs_outputs_written (struct brw_context *brw, struct brw_vs_prog_key *key, GLbitfield64 user_varyings)
static void brw_vs_debug_recompile (struct brw_context *brw, struct gl_program *prog, const struct brw_vs_prog_key *key)
static bool brw_codegen_vs_prog (struct brw_context *brw, struct brw_program *vp, struct brw_vs_prog_key *key)
static bool brw_vs_state_dirty (const struct brw_context *brw)
void brw_vs_populate_key (struct brw_context *brw, struct brw_vs_prog_key *key)
void brw_upload_vs_prog (struct brw_context *brw)
bool brw_vs_precompile (struct gl_context *ctx, struct gl_program *prog)
Function Documentation
brw_codegen_vs_prog()
static bool brw_codegen_vs_prog (struct brw_context * brw, struct brw_program * vp, struct brw_vs_prog_key * key) static
References _mesa_problem(), brw_context::base, brw_context::batch, brw_alloc_stage_scratch(), brw_assign_common_binding_table_offsets(), BRW_CACHE_VS_PROG, brw_dump_arb_asm(), brw_get_shader_time_index(), brw_nir_setup_arb_uniforms(), brw_nir_setup_glsl_uniforms(), brw_select_clip_planes(), brw_upload_cache(), brw_vs_debug_recompile(), brw_vs_outputs_written(), brw_context::cache, brw_program::compiled_once, intel_screen::compiler, brw_context::ctx, intel_screen::devinfo, get_time(), GLuint, gl_program::info, gl_program::is_arb_asm, intel_batchbuffer::last_bo, linking_failure, gl_program::nir, brw_context::perf_debug, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_program::program, brw_context::screen, gl_program::sh, ST_VS, and brw_context::vs.
Referenced by brw_upload_vs_prog(), and brw_vs_precompile().
brw_select_clip_planes()
gl_clip_plane* brw_select_clip_planes (struct gl_context * ctx)
Decide which set of clip planes should be used when clipping via gl_Position or gl_ClipVertex.
References gl_transform_attrib::_ClipUserPlane, gl_context::_Shader, gl_pipeline_object::CurrentProgram, gl_transform_attrib::EyeUserPlane, and gl_context::Transform.
Referenced by brw_codegen_vs_prog(), brw_upload_constant_buffer(), and key_debug().
brw_upload_vs_prog()
void brw_upload_vs_prog (struct brw_context * brw)
References brw_context::base, BRW_CACHE_VS_PROG, brw_codegen_vs_prog(), brw_search_cache(), brw_vs_populate_key(), brw_vs_state_dirty(), brw_context::cache, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::vertex_program, void, and brw_context::vs.
Referenced by brw_upload_programs().
brw_vs_debug_recompile()
static void brw_vs_debug_recompile (struct brw_context * brw, struct gl_program * prog, const struct brw_vs_prog_key * key) static
References BRW_CACHE_VS_PROG, brw_debug_recompile_sampler_key(), brw_find_previous_compile(), brw_context::cache, gl_program::Id, and key_debug().
Referenced by brw_codegen_vs_prog().
brw_vs_outputs_written()
GLbitfield64 brw_vs_outputs_written (struct brw_context * brw, struct brw_vs_prog_key * key, GLbitfield64 user_varyings)
References BITFIELD64_BIT, and brw_context::gen.
Referenced by brw_codegen_vs_prog().
brw_vs_populate_key()
void brw_vs_populate_key (struct brw_context * brw, struct brw_vs_prog_key * key)
References gl_light_attrib::_ClampVertexColor, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, brw_context::attrib_wa_flags, gl_polygon_attrib::BackMode, brw_populate_sampler_prog_key_data(), gl_transform_attrib::ClipPlanesEnabled, gl_point_attrib::CoordReplace, brw_context::ctx, gl_polygon_attrib::FrontMode, brw_context::gen, brw_program::id, gl_program::info, brw_context::is_haswell, gl_context::Light, gl_context::Point, gl_point_attrib::PointSprite, gl_context::Polygon, brw_program::program, gl_context::Transform, brw_context::vb, and brw_context::vertex_program.
Referenced by brw_upload_vs_prog().
brw_vs_precompile()
bool brw_vs_precompile (struct gl_context * ctx, struct gl_program * prog)
References brw_context::base, brw_codegen_vs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_program::id, gl_program::info, brw_stage_state::prog_data, brw_stage_state::prog_offset, and brw_context::vs.
Referenced by brw_shader_precompile(), and brwProgramStringNotify().
brw_vs_state_dirty()
static bool brw_vs_state_dirty (const struct brw_context * brw) static
References _NEW_BUFFERS, _NEW_LIGHT, _NEW_POINT, _NEW_POLYGON, _NEW_TEXTURE, _NEW_TRANSFORM, BRW_NEW_VERTEX_PROGRAM, BRW_NEW_VS_ATTRIB_WORKAROUNDS, and brw_state_dirty().
Referenced by brw_upload_vs_prog().