Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_primitive_restart.c File Reference
#include "main/imports.h"
#include "main/bufferobj.h"
#include "main/varray.h"
#include "vbo/vbo.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_draw.h"
#include "intel_batchbuffer.h"
Functions
static bool can_cut_index_handle_restart_index (struct gl_context *ctx, const struct _mesa_index_buffer *ib)
Check if the hardware's cut index support can handle the primitive restart index value (pre-Haswell only).
static bool can_cut_index_handle_prims (struct gl_context *ctx, const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib)
Check if the hardware's cut index support can handle the primitive restart case.
GLboolean brw_handle_primitive_restart (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, struct gl_buffer_object *indirect)
Check if primitive restart is enabled, and if so, handle it properly.
static void haswell_upload_cut_index (struct brw_context *brw)
Variables
const struct brw_tracked_state haswell_cut_index
Function Documentation
brw_handle_primitive_restart()
GLboolean brw_handle_primitive_restart (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, struct gl_buffer_object * indirect)
Check if primitive restart is enabled, and if so, handle it properly.
In some cases the support will be handled in software. When available hardware will handle primitive restart.
References gl_array_attrib::_PrimitiveRestart, gl_context::Array, brw_context(), brw_draw_prims(), can_cut_index_handle_prims(), brw_context::enable_cut_index, brw_context::in_progress, brw_context::prim_restart, and vbo_sw_primitive_restart().
Referenced by brw_draw_prims().
can_cut_index_handle_prims()
static bool can_cut_index_handle_prims (struct gl_context * ctx, const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib) static
Check if the hardware's cut index support can handle the primitive restart case.
References brw_context(), can_cut_index_handle_restart_index(), brw_context::gen, and brw_context::is_haswell.
Referenced by brw_handle_primitive_restart().
can_cut_index_handle_restart_index()
static bool can_cut_index_handle_restart_index (struct gl_context * ctx, const struct _mesa_index_buffer * ib) static
Check if the hardware's cut index support can handle the primitive restart index value (pre-Haswell only).
References gl_context::Array, gl_array_attrib::PrimitiveRestartFixedIndex, gl_array_attrib::RestartIndex, and _mesa_index_buffer::type.
Referenced by can_cut_index_handle_prims().
haswell_upload_cut_index()
static void haswell_upload_cut_index (struct brw_context * brw) static
References _3DSTATE_VF, _mesa_primitive_restart_index(), gl_array_attrib::_PrimitiveRestart, ADVANCE_BATCH, gl_context::Array, BEGIN_BATCH, brw_context::ctx, brw_context::gen, HSW_CUT_INDEX_ENABLE, brw_context::ib, brw_context::is_haswell, OUT_BATCH, gl_array_attrib::RestartIndex, and _mesa_index_buffer::type.
Variable Documentation
haswell_cut_index
const struct brw_tracked_state haswell_cut_index
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_TRANSFORM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_INDEX_BUFFER,
   },
   .emit = haswell_upload_cut_index,
}