Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_object_purgeable.c File Reference
The driver implementation of the GL_APPLE_object_purgeable extension.
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/bufferobj.h"
#include "brw_context.h"
#include "intel_buffer_objects.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
Functions
static GLenum intel_buffer_purgeable (drm_intel_bo *buffer)
static GLenum intel_buffer_object_purgeable (struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
static GLenum intel_texture_object_purgeable (struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
static GLenum intel_render_object_purgeable (struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
static int intel_bo_unpurgeable (drm_intel_bo *buffer)
static GLenum intel_buffer_object_unpurgeable (struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
static GLenum intel_texture_object_unpurgeable (struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
static GLenum intel_render_object_unpurgeable (struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
void brw_init_object_purgeable_functions (struct dd_function_table *functions)
Detailed Description
The driver implementation of the GL_APPLE_object_purgeable extension.
Function Documentation
brw_init_object_purgeable_functions()
void brw_init_object_purgeable_functions (struct dd_function_table * functions)
References dd_function_table::BufferObjectPurgeable, dd_function_table::BufferObjectUnpurgeable, intel_buffer_object_purgeable(), intel_buffer_object_unpurgeable(), intel_render_object_purgeable(), intel_render_object_unpurgeable(), intel_texture_object_purgeable(), intel_texture_object_unpurgeable(), dd_function_table::RenderObjectPurgeable, dd_function_table::RenderObjectUnpurgeable, dd_function_table::TextureObjectPurgeable, and dd_function_table::TextureObjectUnpurgeable.
Referenced by brw_init_driver_functions().
intel_bo_unpurgeable()
static int intel_bo_unpurgeable (drm_intel_bo * buffer) static
Referenced by intel_buffer_object_unpurgeable(), intel_render_object_unpurgeable(), and intel_texture_object_unpurgeable().
intel_buffer_object_purgeable()
static GLenum intel_buffer_object_purgeable (struct gl_context * ctx, struct gl_buffer_object * obj, GLenum option) static
References intel_buffer_object::buffer, intel_buffer_object(), and intel_buffer_purgeable().
Referenced by brw_init_object_purgeable_functions().
intel_buffer_object_unpurgeable()
static GLenum intel_buffer_object_unpurgeable (struct gl_context * ctx, struct gl_buffer_object * obj, GLenum option) static
References intel_buffer_object::buffer, intel_bo_unpurgeable(), intel_buffer_object(), and void.
Referenced by brw_init_object_purgeable_functions().
intel_buffer_purgeable()
static GLenum intel_buffer_purgeable (drm_intel_bo * buffer) static
Referenced by intel_buffer_object_purgeable(), intel_render_object_purgeable(), and intel_texture_object_purgeable().
intel_render_object_purgeable()
static GLenum intel_render_object_purgeable (struct gl_context * ctx, struct gl_renderbuffer * obj, GLenum option) static
References intel_buffer_purgeable(), intel_renderbuffer(), intel_renderbuffer::mt, and void.
Referenced by brw_init_object_purgeable_functions().
intel_render_object_unpurgeable()
static GLenum intel_render_object_unpurgeable (struct gl_context * ctx, struct gl_renderbuffer * obj, GLenum option) static
References intel_bo_unpurgeable(), intel_miptree_release(), intel_renderbuffer(), intel_renderbuffer::mt, and void.
Referenced by brw_init_object_purgeable_functions().
intel_texture_object_purgeable()
static GLenum intel_texture_object_purgeable (struct gl_context * ctx, struct gl_texture_object * obj, GLenum option) static
References intel_buffer_purgeable(), intel_texture_object(), intel_texture_object::mt, and void.
Referenced by brw_init_object_purgeable_functions().
intel_texture_object_unpurgeable()
static GLenum intel_texture_object_unpurgeable (struct gl_context * ctx, struct gl_texture_object * obj, GLenum option) static
References intel_bo_unpurgeable(), intel_miptree_release(), intel_texture_object(), intel_texture_object::mt, and void.
Referenced by brw_init_object_purgeable_functions().