Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_fs_vector_splitting.cpp File Reference
#include "brw_program.h"
#include "main/imports.h"
#include "compiler/glsl/ir.h"
#include "compiler/glsl/ir_rvalue_visitor.h"
#include "compiler/glsl_types.h"
#include "util/hash_table.h"
Data Structures
class variable_entry
class ir_vector_reference_visitor
class ir_vector_splitting_visitor
Functions
bool brw_do_vector_splitting (exec_list *instructions)
Variables
static bool debug = false
Function Documentation
brw_do_vector_splitting()
bool brw_do_vector_splitting (exec_list * instructions)
References variable_entry::components, debug, ir_vector_reference_visitor::ht, if(), variable_entry::mem_ctx, variable_entry::var, visit_list_elements(), and variable_entry::whole_vector_access.
Referenced by process_glsl_ir().
Variable Documentation
debug
bool debug = false static
Referenced by brw_do_vector_splitting().