Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip_tri.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "program/program.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_clip.h"
Functions
static void release_tmps (struct brw_clip_compile *c)
void brw_clip_tri_alloc_regs (struct brw_clip_compile *c, GLuint nr_verts)
void brw_clip_tri_init_vertices (struct brw_clip_compile *c)
void brw_clip_tri_flat_shade (struct brw_clip_compile *c)
static void load_clip_distance (struct brw_clip_compile *c, struct brw_indirect vtx, struct brw_reg dst, GLuint hpos_offset, int cond)
Loads the clip distance for a vertex into dst, and ends with a comparison of it to zero with the condition cond.
void brw_clip_tri (struct brw_clip_compile *c)
void brw_clip_tri_emit_polygon (struct brw_clip_compile *c)
static void do_clip_tri (struct brw_clip_compile *c)
static void maybe_do_clip_tri (struct brw_clip_compile *c)
static void brw_clip_test (struct brw_clip_compile *c)
void brw_emit_tri_clip (struct brw_clip_compile *c)
Function Documentation
brw_clip_test()
static void brw_clip_test (struct brw_clip_compile * c) static
References brw_clip_kill_thread(), brw_clip_compile::func, get_tmp(), GLuint, brw_clip_compile::loopcount, brw_clip_compile::planemask, brw_clip_compile::reg, release_tmps(), brw_clip_compile::vertex, and brw_clip_compile::vue_map.
Referenced by brw_emit_tri_clip().
brw_clip_tri()
void brw_clip_tri (struct brw_clip_compile * c)
References brw_clip_interp_vertex(), brw_clip_plane0_address(), brw_clip_plane_stride(), brw_clip_compile::clipdistance_offset, brw_clip_compile::dp, brw_clip_compile::dpPrev, brw_clip_compile::func, GLuint, brw_clip_compile::inlist, brw_clip_compile::key, load_clip_distance(), brw_clip_compile::loopcount, brw_clip_compile::nr_regs, brw_clip_prog_key::nr_userclip, brw_clip_compile::nr_verts, brw_clip_compile::outlist, brw_clip_compile::plane_equation, brw_clip_compile::planemask, brw_clip_compile::reg, brw_clip_compile::t, brw_clip_compile::vertex, brw_clip_compile::vertex_src_mask, and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_emit_unfilled_clip(), and do_clip_tri().
brw_clip_tri_alloc_regs()
void brw_clip_tri_alloc_regs (struct brw_clip_compile * c, GLuint nr_verts)
References brw_clip_compile::clipdistance_offset, brw_clip_prog_data::curb_read_length, brw_clip_compile::dir, brw_clip_prog_key::do_unfilled, brw_clip_compile::dp, brw_clip_compile::dpPrev, brw_clip_compile::ff_sync, brw_clip_compile::first_tmp, brw_clip_compile::fixed_planes, brw_clip_compile::freelist, brw_clip_compile::func, GLuint, brw_clip_compile::inlist, brw_clip_compile::key, brw_clip_compile::last_tmp, brw_clip_compile::loopcount, brw_clip_compile::nr_regs, brw_clip_prog_key::nr_userclip, brw_clip_compile::nr_verts, brw_clip_compile::offset, brw_clip_compile::outlist, brw_clip_compile::plane_equation, brw_clip_compile::planemask, brw_clip_compile::prog_data, brw_clip_compile::R0, brw_clip_compile::reg, brw_clip_compile::t, brw_clip_compile::tmp1, brw_clip_prog_data::total_grf, brw_clip_prog_data::urb_read_length, brw_clip_compile::vertex, brw_clip_compile::vertex_src_mask, and brw_clip_compile::vue_map.
Referenced by brw_clip_have_varying(), brw_emit_point_clip(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_clip_tri_emit_polygon()
void brw_clip_tri_emit_polygon (struct brw_clip_compile * c)
References brw_clip_emit_vue(), brw_clip_compile::func, brw_clip_compile::inlist, brw_clip_compile::loopcount, brw_clip_compile::nr_verts, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), and emit_primitives().
brw_clip_tri_flat_shade()
void brw_clip_tri_flat_shade (struct brw_clip_compile * c)
References brw_clip_copy_flatshaded_attributes(), brw_clip_compile::func, brw_clip_compile::key, brw_clip_compile::loopcount, PRIM_MASK, brw_clip_prog_key::pv_first, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_clip_tri_init_vertices()
void brw_clip_tri_init_vertices (struct brw_clip_compile * c)
References brw_clip_compile::dir, brw_clip_compile::func, brw_clip_compile::inlist, brw_clip_compile::loopcount, brw_clip_compile::need_direction, brw_clip_compile::nr_verts, brw_clip_compile::outlist, PRIM_MASK, brw_clip_compile::R0, brw_clip_compile::reg, and brw_clip_compile::vertex.
Referenced by brw_clip_have_varying(), brw_emit_tri_clip(), and brw_emit_unfilled_clip().
brw_emit_tri_clip()
void brw_emit_tri_clip (struct brw_clip_compile * c)
References brw_clip_init_clipmask(), brw_clip_init_ff_sync(), brw_clip_kill_thread(), brw_clip_test(), brw_clip_tri_alloc_regs(), brw_clip_tri_emit_polygon(), brw_clip_tri_flat_shade(), brw_clip_tri_init_vertices(), BRW_CLIPMODE_KERNEL_CLIP, BRW_CLIPMODE_NORMAL, brw_clip_prog_key::clip_mode, brw_clip_prog_key::contains_flat_varying, do_clip_tri(), brw_clip_compile::func, brw_clip_compile::key, maybe_do_clip_tri(), brw_clip_prog_key::nr_userclip, brw_clip_compile::R0, and brw_clip_compile::reg.
Referenced by brw_clip_have_varying(), and compile_clip_prog().
do_clip_tri()
static void do_clip_tri (struct brw_clip_compile * c) static
References brw_clip_init_planes(), and brw_clip_tri().
Referenced by brw_emit_tri_clip(), and maybe_do_clip_tri().
load_clip_distance()
static void load_clip_distance (struct brw_clip_compile * c, struct brw_indirect vtx, struct brw_reg dst, GLuint hpos_offset, int cond) inline static
Loads the clip distance for a vertex into dst, and ends with a comparison of it to zero with the condition cond.
If using a fixed plane, the distance is dot(hpos, plane).
If using a user clip plane, the distance is directly available in the vertex.
References brw_clip_compile::clipdistance_offset, brw_clip_compile::func, brw_clip_compile::plane_equation, brw_clip_compile::reg, and brw_clip_compile::vertex_src_mask.
Referenced by brw_clip_tri().
maybe_do_clip_tri()
static void maybe_do_clip_tri (struct brw_clip_compile * c) static
References do_clip_tri(), brw_clip_compile::func, brw_clip_compile::planemask, and brw_clip_compile::reg.
Referenced by brw_emit_tri_clip().
release_tmps()
static void release_tmps (struct brw_clip_compile * c) static
References brw_clip_compile::first_tmp, and brw_clip_compile::last_tmp.
Referenced by brw_clip_test().