Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_queryobj.c File Reference
Support for query objects (GL_ARB_occlusion_query, GL_ARB_timer_query, GL_EXT_transform_feedback, and friends).
#include "main/imports.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
Functions
uint64_t brw_timebase_scale (struct brw_context *brw, uint64_t gpu_timestamp)
uint64_t brw_raw_timestamp_delta (struct brw_context *brw, uint64_t time0, uint64_t time1)
void brw_write_timestamp (struct brw_context *brw, drm_intel_bo *query_bo, int idx)
Emit PIPE_CONTROLs to write the current GPU timestamp into a buffer.
void brw_write_depth_count (struct brw_context *brw, drm_intel_bo *query_bo, int idx)
Emit PIPE_CONTROLs to write the PS_DEPTH_COUNT register into a buffer.
static void brw_queryobj_get_results (struct gl_context *ctx, struct brw_query_object *query)
Wait on the query object's BO and calculate the final result.
static struct gl_query_object * brw_new_query_object (struct gl_context *ctx, GLuint id)
The NewQueryObject() driver hook.
static void brw_delete_query (struct gl_context *ctx, struct gl_query_object *q)
The DeleteQuery() driver hook.
static void brw_begin_query (struct gl_context *ctx, struct gl_query_object *q)
Gen4-5 driver hook for glBeginQuery().
static void brw_end_query (struct gl_context *ctx, struct gl_query_object *q)
Gen4-5 driver hook for glEndQuery().
static void brw_wait_query (struct gl_context *ctx, struct gl_query_object *q)
The Gen4-5 WaitQuery() driver hook.
static void brw_check_query (struct gl_context *ctx, struct gl_query_object *q)
The Gen4-5 CheckQuery() driver hook.
static void ensure_bo_has_space (struct gl_context *ctx, struct brw_query_object *query)
Ensure there query's BO has enough space to store a new pair of values.
void brw_emit_query_begin (struct brw_context *brw)
Record the PS_DEPTH_COUNT value (for occlusion queries) just before primitive drawing.
void brw_emit_query_end (struct brw_context *brw)
Called at batchbuffer flush to get an ending PS_DEPTH_COUNT (for non-hardware context platforms).
void brw_query_counter (struct gl_context *ctx, struct gl_query_object *q)
Driver hook for glQueryCounter().
static uint64_t brw_get_timestamp (struct gl_context *ctx)
Read the TIMESTAMP register immediately (in a non-pipelined fashion).
bool brw_is_query_pipelined (struct brw_query_object *query)
Is this type of query written by PIPE_CONTROL?
void brw_init_common_queryobj_functions (struct dd_function_table *functions)
void gen4_init_queryobj_functions (struct dd_function_table *functions)
Detailed Description
Support for query objects (GL_ARB_occlusion_query, GL_ARB_timer_query, GL_EXT_transform_feedback, and friends).
The hardware provides a PIPE_CONTROL command that can report the number of fragments that passed the depth test, or the hardware timer. They are appropriately synced with the stage of the pipeline for our extensions' needs.
Function Documentation
brw_begin_query()
static void brw_begin_query (struct gl_context * ctx, struct gl_query_object * q) static
Gen4-5 driver hook for glBeginQuery().
Initializes driver structures and emits any GPU commands required to begin recording data for the query.
References brw_query_object::Base, brw_query_object::bo, brw_context(), BRW_NEW_STATS_WM, brw_write_timestamp(), brw_context::bufmgr, brw_context::ctx, brw_context::gen, brw_query_object::last_index, gl_context::NewDriverState, brw_context::obj, brw_context::query, brw_context::stats_wm, and gl_query_object::Target.
Referenced by gen4_init_queryobj_functions().
brw_check_query()
static void brw_check_query (struct gl_context * ctx, struct gl_query_object * q) static
The Gen4-5 CheckQuery() driver hook.
Checks whether a query result is ready yet. If not, flushes. This is the backing for glGetQueryObjectiv()'s QUERY_RESULT_AVAILABLE pname.
References brw_query_object::Base, brw_context::batch, brw_query_object::bo, intel_batchbuffer::bo, brw_context(), brw_queryobj_get_results(), brw_context::gen, intel_batchbuffer_flush, and gl_query_object::Ready.
Referenced by gen4_init_queryobj_functions().
brw_delete_query()
static void brw_delete_query (struct gl_context * ctx, struct gl_query_object * q) static
The DeleteQuery() driver hook.
References brw_query_object::bo.
Referenced by brw_init_common_queryobj_functions().
brw_emit_query_begin()
void brw_emit_query_begin (struct brw_context * brw)
Record the PS_DEPTH_COUNT value (for occlusion queries) just before primitive drawing.
In a pre-hardware context world, the single PS_DEPTH_COUNT register is shared among all applications using the GPU. However, our query value needs to only include fragments generated by our application/GL context.
To accommodate this, we record PS_DEPTH_COUNT at the start and end of each batchbuffer (technically, the first primitive drawn and flush time). Subtracting each pair of values calculates the change in PS_DEPTH_COUNT caused by a batchbuffer. Since there is no preemption inside batches, this is guaranteed to only measure the effects of our current application.
Adding each of these differences (in case drawing is done over many batches) produces the final expected value.
In a world with hardware contexts, PS_DEPTH_COUNT is saved and restored as part of the context state, so this is unnecessary, and skipped.
References brw_context::begin_emitted, brw_query_object::bo, brw_write_depth_count(), brw_context::ctx, ensure_bo_has_space(), brw_context::hw_ctx, brw_query_object::last_index, brw_context::obj, and brw_context::query.
Referenced by brw_emit_vertices(), and brw_end_query().
brw_emit_query_end()
void brw_emit_query_end (struct brw_context * brw)
Called at batchbuffer flush to get an ending PS_DEPTH_COUNT (for non-hardware context platforms).
See the explanation in brw_emit_query_begin().
References brw_context::begin_emitted, brw_query_object::bo, brw_write_depth_count(), brw_context::hw_ctx, brw_query_object::last_index, brw_context::obj, and brw_context::query.
Referenced by brw_end_query(), and brw_finish_batch().
brw_end_query()
static void brw_end_query (struct gl_context * ctx, struct gl_query_object * q) static
Gen4-5 driver hook for glEndQuery().
Emits GPU commands to record a final query value, ending any data capturing. However, the final result isn't necessarily available until the GPU processes those commands. brw_queryobj_get_results() processes the captured data to produce the final result.
References brw_query_object::Base, brw_query_object::bo, brw_context(), brw_emit_query_begin(), brw_emit_query_end(), BRW_NEW_STATS_WM, brw_write_timestamp(), brw_context::ctx, brw_context::gen, gl_context::NewDriverState, brw_context::obj, brw_context::query, brw_context::stats_wm, and gl_query_object::Target.
Referenced by gen4_init_queryobj_functions().
brw_get_timestamp()
static uint64_t brw_get_timestamp (struct gl_context * ctx) static
Read the TIMESTAMP register immediately (in a non-pipelined fashion).
This is used to implement the GetTimestamp() driver hook.
References brw_context(), brw_timebase_scale(), brw_context::bufmgr, gl_context::Const, intel_screen::hw_has_timestamp, gl_constants::QueryCounterBits, brw_context::screen, gl_constants::Timestamp, and TIMESTAMP.
Referenced by brw_init_common_queryobj_functions().
brw_init_common_queryobj_functions()
void brw_init_common_queryobj_functions (struct dd_function_table * functions)
References brw_delete_query(), brw_get_timestamp(), brw_new_query_object(), dd_function_table::DeleteQuery, dd_function_table::GetTimestamp, and dd_function_table::NewQueryObject.
Referenced by brw_init_driver_functions().
brw_is_query_pipelined()
bool brw_is_query_pipelined (struct brw_query_object * query)
Is this type of query written by PIPE_CONTROL?
References brw_query_object::Base, and gl_query_object::Target.
Referenced by hsw_store_query_result(), and set_query_availability().
brw_new_query_object()
static struct gl_query_object* brw_new_query_object (struct gl_context * ctx, GLuint id) static
The NewQueryObject() driver hook.
Allocates and initializes a new query object.
References gl_query_object::Active, brw_query_object::Base, gl_query_object::Id, gl_query_object::Ready, and gl_query_object::Result.
Referenced by brw_init_common_queryobj_functions().
brw_query_counter()
void brw_query_counter (struct gl_context * ctx, struct gl_query_object * q)
Driver hook for glQueryCounter().
This handles GL_TIMESTAMP queries, which perform a pipelined read of the current GPU time. This is unlike GL_TIME_ELAPSED, which measures the time while the query is active.
References brw_query_object::bo, brw_context(), brw_write_timestamp(), brw_context::bufmgr, brw_query_object::flushed, and gl_query_object::Target.
Referenced by gen4_init_queryobj_functions(), and gen6_query_counter().
brw_queryobj_get_results()
static void brw_queryobj_get_results (struct gl_context * ctx, struct brw_query_object * query) static
Wait on the query object's BO and calculate the final result.
References brw_query_object::Base, brw_context::batch, brw_query_object::bo, intel_batchbuffer::bo, brw_context(), brw_raw_timestamp_delta(), brw_timebase_scale(), gl_context::Const, brw_context::gen, intel_batchbuffer_flush, brw_query_object::last_index, brw_context::perf_debug, gl_constants::QueryCounterBits, gl_query_object::Result, gl_query_object::Target, and gl_constants::Timestamp.
Referenced by brw_check_query(), brw_wait_query(), and ensure_bo_has_space().
brw_raw_timestamp_delta()
uint64_t brw_raw_timestamp_delta (struct brw_context * brw, uint64_t time0, uint64_t time1)
References intel_screen::hw_has_timestamp, and brw_context::screen.
Referenced by brw_queryobj_get_results(), and gen6_queryobj_get_results().
brw_timebase_scale()
uint64_t brw_timebase_scale (struct brw_context * brw, uint64_t gpu_timestamp)
References intel_screen::devinfo, and brw_context::screen.
Referenced by brw_get_timestamp(), brw_queryobj_get_results(), and gen6_queryobj_get_results().
brw_wait_query()
static void brw_wait_query (struct gl_context * ctx, struct gl_query_object * q) static
The Gen4-5 WaitQuery() driver hook.
Wait for a query result to become available and return it. This is the backing for glGetQueryObjectiv() with the GL_QUERY_RESULT pname.
References brw_query_object::Base, brw_context(), brw_queryobj_get_results(), and gl_query_object::Ready.
Referenced by gen4_init_queryobj_functions().
brw_write_depth_count()
void brw_write_depth_count (struct brw_context * brw, drm_intel_bo * query_bo, int idx)
Emit PIPE_CONTROLs to write the PS_DEPTH_COUNT register into a buffer.
References brw_emit_pipe_control_write(), brw_context::gen, brw_context::gt, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_STALL, and PIPE_CONTROL_WRITE_DEPTH_COUNT.
Referenced by brw_emit_query_begin(), brw_emit_query_end(), gen6_begin_query(), and gen6_end_query().
brw_write_timestamp()
void brw_write_timestamp (struct brw_context * brw, drm_intel_bo * query_bo, int idx)
Emit PIPE_CONTROLs to write the current GPU timestamp into a buffer.
References brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), brw_context::gen, brw_context::gt, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_STALL_AT_SCOREBOARD, and PIPE_CONTROL_WRITE_TIMESTAMP.
Referenced by brw_begin_query(), brw_end_query(), brw_query_counter(), gen6_begin_query(), and gen6_end_query().
ensure_bo_has_space()
static void ensure_bo_has_space (struct gl_context * ctx, struct brw_query_object * query) static
Ensure there query's BO has enough space to store a new pair of values.
If not, gather the existing BO's results and create a new buffer of the same size.
References brw_query_object::bo, brw_context(), brw_queryobj_get_results(), brw_context::bufmgr, brw_context::gen, and brw_query_object::last_index.
Referenced by brw_emit_query_begin().
gen4_init_queryobj_functions()
void gen4_init_queryobj_functions (struct dd_function_table * functions)
References dd_function_table::BeginQuery, brw_begin_query(), brw_check_query(), brw_end_query(), brw_query_counter(), brw_wait_query(), dd_function_table::CheckQuery, dd_function_table::EndQuery, dd_function_table::QueryCounter, and dd_function_table::WaitQuery.
Referenced by brw_init_driver_functions().