Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_state.h File Reference
#include "brw_context.h"
Macros
#define BRW_BATCH_STRUCT(brw, s) intel_batchbuffer_data(brw, (s), sizeof(*(s)), RENDER_RING)
Functions
static bool brw_state_dirty (const struct brw_context *brw, GLuint mesa_flags, uint64_t brw_flags)
void brw_upload_binding_table (struct brw_context *brw, uint32_t packet_name, const struct brw_stage_prog_data *prog_data, struct brw_stage_state *stage_state)
Upload a shader stage's binding table as indirect state.
void brw_upload_invariant_state (struct brw_context *brw)
Misc invariant state packets.
uint32_t brw_depthbuffer_format (struct brw_context *brw)
void brw_upload_state_base_address (struct brw_context *brw)
Define the base addresses which some state is referenced from.
void gen8_write_pma_stall_bits (struct brw_context *brw, uint32_t pma_stall_bits)
void brw_upload_render_state (struct brw_context *brw)
void brw_render_state_finished (struct brw_context *brw)
Clear dirty bits to account for the fact that the state emitted by brw_upload_render_state() has been committed to the hardware.
void brw_upload_compute_state (struct brw_context *brw)
void brw_compute_state_finished (struct brw_context *brw)
void brw_init_state (struct brw_context *brw)
void brw_destroy_state (struct brw_context *brw)
void brw_emit_select_pipeline (struct brw_context *brw, enum brw_pipeline pipeline)
static void brw_select_pipeline (struct brw_context *brw, enum brw_pipeline pipeline)
void brw_upload_cache (struct brw_cache *cache, enum brw_cache_id cache_id, const void *key, GLuint key_sz, const void *data, GLuint data_sz, const void *aux, GLuint aux_sz, uint32_t *out_offset, void *out_aux)
bool brw_search_cache (struct brw_cache *cache, enum brw_cache_id cache_id, const void *key, GLuint key_size, uint32_t *inout_offset, void *inout_aux)
Returns the buffer object matching cache_id and key, or NULL.
const void * brw_find_previous_compile (struct brw_cache *cache, enum brw_cache_id cache_id, unsigned program_string_id)
void brw_program_cache_check_size (struct brw_context *brw)
void brw_init_caches (struct brw_context *brw)
void brw_destroy_caches (struct brw_context *brw)
void brw_print_program_cache (struct brw_context *brw)
void * brw_state_batch (struct brw_context *brw, int size, int alignment, uint32_t *out_offset)
Allocates a block of space in the batchbuffer for indirect state.
uint32_t brw_state_batch_size (struct brw_context *brw, uint32_t offset)
void gen4_init_vtable_surface_functions (struct brw_context *brw)
uint32_t brw_get_surface_tiling_bits (uint32_t tiling)
uint32_t brw_get_surface_num_multisamples (unsigned num_samples)
uint32_t brw_isl_format_for_mesa_format (mesa_format mesa_format)
GLuint translate_tex_target (GLenum target)
GLuint translate_tex_format (struct brw_context *brw, mesa_format mesa_format, GLenum srgb_decode)
int brw_get_texture_swizzle (const struct gl_context *ctx, const struct gl_texture_object *t)
Compute the combination of DEPTH_TEXTURE_MODE and EXT_texture_swizzle swizzling.
void brw_emit_buffer_surface_state (struct brw_context *brw, uint32_t *out_offset, drm_intel_bo *bo, unsigned buffer_offset, unsigned surface_format, unsigned buffer_size, unsigned pitch, bool rw)
void brw_update_texture_surface (struct gl_context *ctx, unsigned unit, uint32_t *surf_offset, bool for_gather, uint32_t plane)
uint32_t brw_update_renderbuffer_surface (struct brw_context *brw, struct gl_renderbuffer *rb, uint32_t flags, unsigned unit, uint32_t surf_index)
void brw_update_renderbuffer_surfaces (struct brw_context *brw, const struct gl_framebuffer *fb, uint32_t render_target_start, uint32_t *surf_offset)
Construct SURFACE_STATE objects for renderbuffers/draw buffers.
void gen7_check_surface_setup (uint32_t *surf, bool is_render_target)
void gen7_init_vtable_surface_functions (struct brw_context *brw)
void gen8_upload_ps_state (struct brw_context *brw, const struct brw_stage_state *stage_state, const struct brw_wm_prog_data *prog_data, uint32_t fast_clear_op)
void gen8_upload_ps_extra (struct brw_context *brw, const struct brw_wm_prog_data *prog_data)
void gen7_upload_3dstate_so_decl_list (struct brw_context *brw, const struct brw_vue_map *vue_map)
Outputs the 3DSTATE_SO_DECL_LIST command.
void gen8_upload_3dstate_so_buffers (struct brw_context *brw)
void gen8_init_vtable_surface_functions (struct brw_context *brw)
void brw_emit_sampler_state (struct brw_context *brw, uint32_t *sampler_state, uint32_t batch_offset_for_sampler_state, unsigned min_filter, unsigned mag_filter, unsigned mip_filter, unsigned max_anisotropy, unsigned address_rounding, unsigned wrap_s, unsigned wrap_t, unsigned wrap_r, unsigned base_level, unsigned min_lod, unsigned max_lod, int lod_bias, unsigned shadow_function, bool non_normalized_coordinates, uint32_t border_color_offset)
Emit a SAMPLER_STATE structure, given all the fields.
void gen6_upload_wm_state (struct brw_context *brw, const struct brw_wm_prog_data *prog_data, const struct brw_stage_state *stage_state, bool multisampled_fbo, bool dual_source_blend_enable, bool kill_enable, bool color_buffer_write_enable, bool msaa_enabled, bool line_stipple_enable, bool polygon_stipple_enable, bool statistic_enable)
void calculate_attr_overrides (const struct brw_context *brw, uint16_t *attr_overrides, uint32_t *point_sprite_enables, uint32_t *urb_entry_read_length, uint32_t *urb_entry_read_offset)
Create the mapping from the FS inputs we produce to the previous pipeline stage (GS or VS) outputs they source from.
void gen6_init_vtable_surface_functions (struct brw_context *brw)
void brw_upload_pull_constants (struct brw_context *brw, GLbitfield64 brw_new_constbuf, const struct gl_program *prog, struct brw_stage_state *stage_state, const struct brw_stage_prog_data *prog_data)
Creates a temporary BO containing the pull constant data for the shader stage, and the SURFACE_STATE struct that points at it.
void gen7_upload_constant_state (struct brw_context *brw, const struct brw_stage_state *stage_state, bool active, unsigned opcode)
void brw_upload_clip_prog (struct brw_context *brw)
void brw_upload_sf_prog (struct brw_context *brw)
bool brw_is_drawing_points (const struct brw_context *brw)
bool brw_is_drawing_lines (const struct brw_context *brw)
void gen7_restore_default_l3_config (struct brw_context *brw)
Hack to restore the default L3 configuration.
static bool use_state_point_size (const struct brw_context *brw)
void brw_calculate_guardband_size (const struct gen_device_info *devinfo, uint32_t fb_width, uint32_t fb_height, float m00, float m11, float m30, float m31, float *xmin, float *xmax, float *ymin, float *ymax)
Variables
const struct brw_tracked_state brw_blend_constant_color
const struct brw_tracked_state brw_cc_vp
const struct brw_tracked_state brw_cc_unit
const struct brw_tracked_state brw_clip_unit
const struct brw_tracked_state brw_vs_pull_constants
const struct brw_tracked_state brw_tcs_pull_constants
const struct brw_tracked_state brw_tes_pull_constants
const struct brw_tracked_state brw_gs_pull_constants
const struct brw_tracked_state brw_wm_pull_constants
const struct brw_tracked_state brw_cs_pull_constants
const struct brw_tracked_state brw_constant_buffer
const struct brw_tracked_state brw_curbe_offsets
const struct brw_tracked_state brw_invariant_state
const struct brw_tracked_state brw_fs_samplers
const struct brw_tracked_state brw_gs_unit
const struct brw_tracked_state brw_line_stipple
const struct brw_tracked_state brw_binding_table_pointers
const struct brw_tracked_state brw_depthbuffer
const struct brw_tracked_state brw_polygon_stipple_offset
const struct brw_tracked_state brw_polygon_stipple
const struct brw_tracked_state brw_recalculate_urb_fence
const struct brw_tracked_state brw_sf_unit
const struct brw_tracked_state brw_sf_vp
const struct brw_tracked_state brw_vs_samplers
const struct brw_tracked_state brw_tcs_samplers
const struct brw_tracked_state brw_tes_samplers
const struct brw_tracked_state brw_gs_samplers
const struct brw_tracked_state brw_cs_samplers
const struct brw_tracked_state brw_cs_texture_surfaces
const struct brw_tracked_state brw_vs_ubo_surfaces
const struct brw_tracked_state brw_vs_abo_surfaces
const struct brw_tracked_state brw_vs_image_surfaces
const struct brw_tracked_state brw_tcs_ubo_surfaces
const struct brw_tracked_state brw_tcs_abo_surfaces
const struct brw_tracked_state brw_tcs_image_surfaces
const struct brw_tracked_state brw_tes_ubo_surfaces
const struct brw_tracked_state brw_tes_abo_surfaces
const struct brw_tracked_state brw_tes_image_surfaces
const struct brw_tracked_state brw_gs_ubo_surfaces
const struct brw_tracked_state brw_gs_abo_surfaces
const struct brw_tracked_state brw_gs_image_surfaces
const struct brw_tracked_state brw_vs_unit
const struct brw_tracked_state brw_renderbuffer_surfaces
const struct brw_tracked_state brw_renderbuffer_read_surfaces
const struct brw_tracked_state brw_texture_surfaces
const struct brw_tracked_state brw_wm_binding_table
const struct brw_tracked_state brw_gs_binding_table
const struct brw_tracked_state brw_tes_binding_table
const struct brw_tracked_state brw_tcs_binding_table
const struct brw_tracked_state brw_vs_binding_table
const struct brw_tracked_state brw_wm_ubo_surfaces
const struct brw_tracked_state brw_wm_abo_surfaces
const struct brw_tracked_state brw_wm_image_surfaces
const struct brw_tracked_state brw_cs_ubo_surfaces
const struct brw_tracked_state brw_cs_abo_surfaces
const struct brw_tracked_state brw_cs_image_surfaces
const struct brw_tracked_state brw_wm_unit
const struct brw_tracked_state brw_psp_urb_cbs
const struct brw_tracked_state brw_drawing_rect
const struct brw_tracked_state brw_indices
const struct brw_tracked_state brw_vertices
const struct brw_tracked_state brw_index_buffer
const struct brw_tracked_state brw_cs_state
const struct brw_tracked_state gen7_cs_push_constants
const struct brw_tracked_state gen6_binding_table_pointers
const struct brw_tracked_state gen6_blend_state
const struct brw_tracked_state gen6_clip_state
const struct brw_tracked_state gen6_sf_and_clip_viewports
const struct brw_tracked_state gen6_color_calc_state
const struct brw_tracked_state gen6_depth_stencil_state
const struct brw_tracked_state gen6_gs_state
const struct brw_tracked_state gen6_gs_push_constants
const struct brw_tracked_state gen6_gs_binding_table
const struct brw_tracked_state gen6_multisample_state
const struct brw_tracked_state gen6_renderbuffer_surfaces
const struct brw_tracked_state gen6_sampler_state
const struct brw_tracked_state gen6_scissor_state
const struct brw_tracked_state gen6_sol_surface
const struct brw_tracked_state gen6_sf_state
const struct brw_tracked_state gen6_sf_vp
const struct brw_tracked_state gen6_urb
const struct brw_tracked_state gen6_viewport_state
const struct brw_tracked_state gen6_vs_push_constants
const struct brw_tracked_state gen6_vs_state
const struct brw_tracked_state gen6_wm_push_constants
const struct brw_tracked_state gen6_wm_state
const struct brw_tracked_state gen7_depthbuffer
const struct brw_tracked_state gen7_ds_state
const struct brw_tracked_state gen7_gs_state
const struct brw_tracked_state gen7_tcs_push_constants
const struct brw_tracked_state gen7_hs_state
const struct brw_tracked_state gen7_l3_state
const struct brw_tracked_state gen7_ps_state
const struct brw_tracked_state gen7_push_constant_space
const struct brw_tracked_state gen7_sbe_state
const struct brw_tracked_state gen7_sf_clip_viewport
const struct brw_tracked_state gen7_sf_state
const struct brw_tracked_state gen7_sol_state
const struct brw_tracked_state gen7_te_state
const struct brw_tracked_state gen7_tes_push_constants
const struct brw_tracked_state gen7_urb
const struct brw_tracked_state gen7_vs_state
const struct brw_tracked_state gen7_wm_state
const struct brw_tracked_state haswell_cut_index
const struct brw_tracked_state gen8_blend_state
const struct brw_tracked_state gen8_ds_state
const struct brw_tracked_state gen8_gs_state
const struct brw_tracked_state gen8_hs_state
const struct brw_tracked_state gen8_index_buffer
const struct brw_tracked_state gen8_multisample_state
const struct brw_tracked_state gen8_pma_fix
const struct brw_tracked_state gen8_ps_blend
const struct brw_tracked_state gen8_ps_extra
const struct brw_tracked_state gen8_ps_state
const struct brw_tracked_state gen8_wm_depth_stencil
const struct brw_tracked_state gen8_wm_state
const struct brw_tracked_state gen8_raster_state
const struct brw_tracked_state gen8_sbe_state
const struct brw_tracked_state gen8_sf_state
const struct brw_tracked_state gen8_sf_clip_viewport
const struct brw_tracked_state gen8_vertices
const struct brw_tracked_state gen8_vf_topology
const struct brw_tracked_state gen8_vs_state
const struct brw_tracked_state brw_cs_work_groups_surface
Macro Definition Documentation
BRW_BATCH_STRUCT
#define BRW_BATCH_STRUCT (brw, s) intel_batchbuffer_data(brw, (s), sizeof(*(s)), RENDER_RING)
Referenced by brw_upload_urb_fence().
Function Documentation
brw_calculate_guardband_size()
void brw_calculate_guardband_size (const struct gen_device_info * devinfo, uint32_t fb_width, uint32_t fb_height, float m00, float m11, float m30, float m31, float * xmin, float * xmax, float * ymin, float * ymax)
Referenced by gen6_upload_sf_and_clip_viewports(), gen7_upload_sf_clip_viewport(), gen8_upload_sf_clip_viewport(), and use_state_point_size().
brw_compute_state_finished()
void brw_compute_state_finished (struct brw_context * brw)
References BRW_COMPUTE_PIPELINE, and brw_pipeline_state_finished().
Referenced by brw_dispatch_compute_common(), and brw_state_dirty().
brw_depthbuffer_format()
uint32_t brw_depthbuffer_format (struct brw_context * brw)
References brw_depth_format(), BRW_DEPTHFORMAT_D32_FLOAT, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, intel_get_renderbuffer(), intel_rb_format(), MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, and intel_renderbuffer::mt.
Referenced by brw_emit_depthbuffer(), brw_state_dirty(), gen8_emit_depth_stencil_hiz(), and upload_sf_state().
brw_destroy_caches()
void brw_destroy_caches (struct brw_context * brw)
References brw_destroy_cache(), and brw_context::cache.
Referenced by brw_destroy_state(), and brw_select_pipeline().
brw_destroy_state()
void brw_destroy_state (struct brw_context * brw)
References brw_destroy_caches().
Referenced by brw_state_dirty(), and intelDestroyContext().
brw_emit_buffer_surface_state()
void brw_emit_buffer_surface_state (struct brw_context * brw, uint32_t * out_offset, drm_intel_bo * bo, unsigned buffer_offset, unsigned surface_format, unsigned buffer_size, unsigned pitch, bool rw)
References brw_context::batch, intel_batchbuffer::bo, brw_state_batch(), brw_context::gen, brw_context::isl_dev, and tex_mocs.
Referenced by brw_create_buffer_surface(), brw_create_constant_surface(), brw_update_buffer_texture_surface(), brw_upload_abo_surfaces(), brw_upload_binding_table(), brw_upload_cs_state(), brw_upload_cs_work_groups_surface(), and update_image_surface().
brw_emit_sampler_state()
void brw_emit_sampler_state (struct brw_context * brw, uint32_t * sampler_state, uint32_t batch_offset_for_sampler_state, unsigned min_filter, unsigned mag_filter, unsigned mip_filter, unsigned max_anisotropy, unsigned address_rounding, unsigned wrap_s, unsigned wrap_t, unsigned wrap_r, unsigned base_level, unsigned min_lod, unsigned max_lod, int lod_bias, unsigned shadow_function, bool non_normalized_coordinates, uint32_t border_color_offset)
Emit a SAMPLER_STATE structure, given all the fields.
References brw_context::batch, intel_batchbuffer::bo, BRW_MAPFILTER_ANISOTROPIC, BRW_SAMPLER_LOD_PRECLAMP_ENABLE, brw_context::gen, GEN6_SAMPLER_MIN_MAG_NOT_EQUAL, GEN6_SAMPLER_NON_NORMALIZED_COORDINATES, GEN7_SAMPLER_EWA_ANISOTROPIC_ALGORITHM, GEN7_SAMPLER_NON_NORMALIZED_COORDINATES, and SET_FIELD.
Referenced by brw_update_sampler_state().
brw_emit_select_pipeline()
void brw_emit_select_pipeline (struct brw_context * brw, enum brw_pipeline pipeline)
References _3DSTATE_CC_STATE_POINTERS, ADVANCE_BATCH, BEGIN_BATCH, BRW_COMPUTE_PIPELINE, brw_emit_pipe_control_flush(), BRW_NEW_CC_STATE, BRW_RENDER_PIPELINE, CMD_3D_PRIM, CMD_PIPELINE_SELECT_965, CMD_PIPELINE_SELECT_GM45, brw_context::ctx, brw_context::gen, gen7_emit_cs_stall_flush(), brw_context::is_g4x, brw_context::is_haswell, MI_FLUSH, gl_context::NewDriverState, OUT_BATCH, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DATA_CACHE_FLUSH, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_INSTRUCTION_INVALIDATE, PIPE_CONTROL_NO_WRITE, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_STATE_CACHE_INVALIDATE, and PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE.
Referenced by brw_select_pipeline(), brw_state_dirty(), and brw_upload_invariant_state().
brw_find_previous_compile()
const void* brw_find_previous_compile (struct brw_cache * cache, enum brw_cache_id cache_id, unsigned program_string_id)
References get_program_string_id(), brw_cache::items, brw_cache_item::next, and brw_cache::size.
Referenced by brw_gs_debug_recompile(), brw_select_pipeline(), brw_tcs_debug_recompile(), brw_tes_debug_recompile(), brw_vs_debug_recompile(), and brw_wm_debug_recompile().
brw_get_surface_num_multisamples()
uint32_t brw_get_surface_num_multisamples (unsigned num_samples)
References BRW_SURFACE_MULTISAMPLECOUNT_1, and BRW_SURFACE_MULTISAMPLECOUNT_4.
Referenced by brw_emit_null_surface_state(), and gen4_update_renderbuffer_surface().
brw_get_surface_tiling_bits()
uint32_t brw_get_surface_tiling_bits (uint32_t tiling)
References BRW_SURFACE_TILED, and BRW_SURFACE_TILED_Y.
Referenced by gen4_update_renderbuffer_surface().
brw_get_texture_swizzle()
int brw_get_texture_swizzle (const struct gl_context * ctx, const struct gl_texture_object * t)
Compute the combination of DEPTH_TEXTURE_MODE and EXT_texture_swizzle swizzling.
References gl_texture_image::_BaseFormat, gl_texture_object::_IsIntegerFormat, _mesa_get_format_bits(), _mesa_get_format_datatype(), gl_texture_object::_Swizzle, gl_texture_object::BaseLevel, gl_texture_object::DepthMode, gl_texture_object::Image, gl_texture_image::InternalFormat, and gl_texture_image::TexFormat.
Referenced by brw_populate_sampler_prog_key_data(), and brw_update_texture_surface().
brw_init_caches()
void brw_init_caches (struct brw_context * brw)
References brw_cache::bo, brw_cache::brw, brw_context::bufmgr, brw_context::cache, brw_context::has_llc, brw_cache::items, brw_cache::n_items, and brw_cache::size.
Referenced by brw_init_state(), and brw_select_pipeline().
brw_init_state()
void brw_init_state (struct brw_context * brw)
References BRW_COMPUTE_PIPELINE, brw_copy_pipeline_atoms(), brw_init_caches(), BRW_NEW_ATOMIC_BUFFER, BRW_NEW_CONSERVATIVE_RASTERIZATION, BRW_NEW_DEFAULT_TESS_LEVELS, BRW_NEW_IMAGE_UNITS, BRW_NEW_RASTERIZER_DISCARD, BRW_NEW_TEXTURE_BUFFER, BRW_NEW_TRANSFORM_FEEDBACK, BRW_NEW_UNIFORM_BUFFER, BRW_NUM_PIPELINES, BRW_NUM_STATE_BITS, BRW_RENDER_PIPELINE, brw_upload_initial_gpu_state(), brw_context::compute_atoms, brw_context::ctx, gl_context::DriverFlags, brw_context::gen, brw_context::last_pipeline, gl_driver_flags::NewAtomicBuffer, gl_driver_flags::NewDefaultTessLevels, gl_context::NewDriverState, brw_context::NewGLState, gl_driver_flags::NewImageUnits, gl_driver_flags::NewIntelConservativeRasterization, gl_driver_flags::NewRasterizerDiscard, gl_driver_flags::NewShaderStorageBuffer, gl_driver_flags::NewTextureBuffer, gl_driver_flags::NewTransformFeedback, gl_driver_flags::NewTransformFeedbackProg, gl_driver_flags::NewUniformBuffer, brw_context::pma_stall_bits, and brw_context::render_atoms.
Referenced by brw_state_dirty(), and brwCreateContext().
brw_is_drawing_lines()
bool brw_is_drawing_lines (const struct brw_context * brw)
References gl_polygon_attrib::BackMode, brw_context::base, brw_context::ctx, gl_polygon_attrib::FrontMode, brw_context::gs, gl_context::Polygon, brw_context::primitive, brw_stage_state::prog_data, and brw_context::tes.
Referenced by upload_clip_state().
brw_is_drawing_points()
bool brw_is_drawing_points (const struct brw_context * brw)
References gl_polygon_attrib::BackMode, brw_context::base, brw_context::ctx, gl_polygon_attrib::FrontMode, brw_context::gs, gl_context::Polygon, brw_context::primitive, brw_stage_state::prog_data, and brw_context::tes.
Referenced by calculate_attr_overrides(), and upload_clip_state().
brw_isl_format_for_mesa_format()
uint32_t brw_isl_format_for_mesa_format (mesa_format mesa_format)
References MESA_FORMAT_A16L16_UNORM, MESA_FORMAT_A1B5G5R5_UNORM, MESA_FORMAT_A1R5G5B5_UNORM, MESA_FORMAT_A4R4G4B4_UNORM, MESA_FORMAT_A8B8G8R8_SNORM, MESA_FORMAT_A8B8G8R8_SRGB, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_SNORM, MESA_FORMAT_A8L8_SRGB, MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_A8R8G8B8_SRGB, MESA_FORMAT_A8R8G8B8_UNORM, MESA_FORMAT_A_FLOAT16, MESA_FORMAT_A_FLOAT32, MESA_FORMAT_A_SINT16, MESA_FORMAT_A_SINT32, MESA_FORMAT_A_SINT8, MESA_FORMAT_A_SNORM16, MESA_FORMAT_A_SNORM8, MESA_FORMAT_A_UINT16, MESA_FORMAT_A_UINT32, MESA_FORMAT_A_UINT8, MESA_FORMAT_A_UNORM16, MESA_FORMAT_A_UNORM8, MESA_FORMAT_B10G10R10A2_UINT, MESA_FORMAT_B10G10R10A2_UNORM, MESA_FORMAT_B10G10R10X2_UNORM, MESA_FORMAT_B2G3R3_UNORM, MESA_FORMAT_B4G4R4A4_UNORM, MESA_FORMAT_B4G4R4X4_UNORM, MESA_FORMAT_B5G5R5A1_UNORM, MESA_FORMAT_B5G5R5X1_UNORM, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_BGR_SRGB8, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, MESA_FORMAT_BPTC_RGBA_UNORM, MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM, MESA_FORMAT_COUNT, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_G16R16_UNORM, MESA_FORMAT_G8R8_UNORM, MESA_FORMAT_I_FLOAT16, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_I_SINT16, MESA_FORMAT_I_SINT32, MESA_FORMAT_I_SINT8, MESA_FORMAT_I_SNORM16, MESA_FORMAT_I_SNORM8, MESA_FORMAT_I_UINT16, MESA_FORMAT_I_UINT32, MESA_FORMAT_I_UINT8, MESA_FORMAT_I_UNORM16, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L16A16_UNORM, MESA_FORMAT_L4A4_UNORM, MESA_FORMAT_L8A8_SNORM, MESA_FORMAT_L8A8_SRGB, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_FLOAT16, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_L_SINT16, MESA_FORMAT_L_SINT32, MESA_FORMAT_L_SINT8, MESA_FORMAT_L_SNORM16, MESA_FORMAT_L_SNORM8, MESA_FORMAT_L_SRGB8, MESA_FORMAT_L_UINT16, MESA_FORMAT_L_UINT32, MESA_FORMAT_L_UINT8, MESA_FORMAT_L_UNORM16, MESA_FORMAT_L_UNORM8, MESA_FORMAT_LA_FLOAT16, MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_LA_SINT16, MESA_FORMAT_LA_SINT32, MESA_FORMAT_LA_SINT8, MESA_FORMAT_LA_SNORM16, MESA_FORMAT_LA_UINT16, MESA_FORMAT_LA_UINT32, MESA_FORMAT_LA_UINT8, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R16G16_SNORM, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R5G6B5_UNORM, MESA_FORMAT_R8G8_SNORM, MESA_FORMAT_R8G8_UNORM, MESA_FORMAT_R8G8B8A8_SNORM, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_R9G9B9E5_FLOAT, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_RGTC1_SNORM, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_SNORM16, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_RGTC2_SNORM, MESA_FORMAT_RG_RGTC2_UNORM, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGB_SINT16, MESA_FORMAT_RGB_SINT32, MESA_FORMAT_RGB_SINT8, MESA_FORMAT_RGB_SNORM16, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGB_UNORM8, MESA_FORMAT_RGBA_ASTC_10x10, MESA_FORMAT_RGBA_ASTC_10x5, MESA_FORMAT_RGBA_ASTC_10x6, MESA_FORMAT_RGBA_ASTC_10x8, MESA_FORMAT_RGBA_ASTC_12x10, MESA_FORMAT_RGBA_ASTC_12x12, MESA_FORMAT_RGBA_ASTC_4x4, MESA_FORMAT_RGBA_ASTC_5x4, MESA_FORMAT_RGBA_ASTC_5x5, MESA_FORMAT_RGBA_ASTC_6x5, MESA_FORMAT_RGBA_ASTC_6x6, MESA_FORMAT_RGBA_ASTC_8x5, MESA_FORMAT_RGBA_ASTC_8x6, MESA_FORMAT_RGBA_ASTC_8x8, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBA_UNORM16, MESA_FORMAT_RGBX_FLOAT16, MESA_FORMAT_RGBX_FLOAT32, MESA_FORMAT_RGBX_SINT16, MESA_FORMAT_RGBX_SINT32, MESA_FORMAT_RGBX_SINT8, MESA_FORMAT_RGBX_SNORM16, MESA_FORMAT_RGBX_UINT16, MESA_FORMAT_RGBX_UINT32, MESA_FORMAT_RGBX_UINT8, MESA_FORMAT_RGBX_UNORM16, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x8, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x12, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_UINT_Z24_UNORM, MESA_FORMAT_X8B8G8R8_SNORM, MESA_FORMAT_X8B8G8R8_SRGB, MESA_FORMAT_X8B8G8R8_UNORM, MESA_FORMAT_X8R8G8B8_SRGB, MESA_FORMAT_X8R8G8B8_UNORM, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, and MESA_FORMAT_Z_UNORM32.
Referenced by brw_blorp_to_isl_format(), brw_init_surface_formats(), brw_is_color_fast_clear_compatible(), brw_update_buffer_texture_surface(), get_image_format(), intel_miptree_supports_non_msrt_fast_clear(), intel_texture_view_requires_resolve(), and translate_tex_format().
brw_print_program_cache()
void brw_print_program_cache (struct brw_context * brw)
References brw_cache::bo, brw_context::cache, cache_name(), intel_screen::devinfo, brw_context::has_llc, brw_cache::items, brw_cache_item::next, brw_cache_item::offset, brw_context::screen, brw_cache_item::size, and brw_cache::size.
Referenced by brw_select_pipeline().
brw_program_cache_check_size()
void brw_program_cache_check_size (struct brw_context * brw)
References brw_clear_cache(), brw_context::cache, and brw_cache::n_items.
Referenced by brw_dispatch_compute_common(), brw_select_pipeline(), and brw_try_draw_prims().
brw_render_state_finished()
void brw_render_state_finished (struct brw_context * brw)
Clear dirty bits to account for the fact that the state emitted by brw_upload_render_state() has been committed to the hardware.
This is a separate call from brw_upload_render_state() because it's possible that after the call to brw_upload_render_state(), we will discover that we've run out of aperture space, and need to rewind the batch buffer to the state it had before the brw_upload_render_state() call.
References brw_pipeline_state_finished(), and BRW_RENDER_PIPELINE.
Referenced by brw_state_dirty(), and brw_try_draw_prims().
brw_search_cache()
bool brw_search_cache (struct brw_cache * cache, enum brw_cache_id cache_id, const void * key, GLuint key_size, uint32_t * inout_offset, void * inout_aux)
Returns the buffer object matching cache_id and key, or NULL.
References brw_cache::brw, brw_cache_item::cache_id, brw_context::ctx, GLuint, brw_cache_item::hash, hash_key(), brw_cache_item::key, brw_cache_item::key_size, gl_context::NewDriverState, brw_cache_item::offset, and search_cache().
Referenced by brw_blorp_lookup_shader(), brw_select_pipeline(), brw_upload_clip_prog(), brw_upload_cs_prog(), brw_upload_ff_gs_prog(), brw_upload_gs_prog(), brw_upload_sf_prog(), brw_upload_tcs_prog(), brw_upload_tes_prog(), brw_upload_vs_prog(), and brw_upload_wm_prog().
brw_select_pipeline()
static void brw_select_pipeline (struct brw_context * brw, enum brw_pipeline pipeline) inline static
References brw_destroy_caches(), brw_emit_select_pipeline(), brw_find_previous_compile(), brw_init_caches(), BRW_NUM_PIPELINES, brw_print_program_cache(), brw_program_cache_check_size(), brw_search_cache(), brw_upload_cache(), GLuint, and brw_context::last_pipeline.
Referenced by blorp_exec(), and brw_upload_pipeline_state().
brw_state_batch()
void* brw_state_batch (struct brw_context * brw, int size, int alignment, uint32_t * out_offset)
Allocates a block of space in the batchbuffer for indirect state.
We don't want to allocate separate BOs for every bit of indirect state in the driver. It means overallocating by a significant margin (4096 bytes, even if the object is just a 20-byte surface state), and more buffers to walk and count for aperture size checking.
However, due to the restrictions imposed by the aperture size checking performance hacks, we can't have the batch point at a separate indirect state buffer, because once the batch points at it, no more relocations can be added to it. So, we sneak these buffers in at the top of the batchbuffer.
References brw_context::batch, intel_batchbuffer::bo, intel_batchbuffer_flush, intel_batchbuffer::map, intel_batchbuffer::reserved_space, intel_batchbuffer::state_batch_offset, intel_batchbuffer::state_batch_sizes, and USED_BATCH.
Referenced by blorp_alloc_binding_table(), blorp_alloc_dynamic_state(), blorp_alloc_vertex_buffer(), brw_emit_buffer_surface_state(), brw_emit_null_surface_state(), brw_emit_surface_state(), brw_gs_upload_binding_table(), brw_update_sol_surface(), brw_upload_binding_table(), brw_upload_cc_vp(), brw_upload_clip_unit(), brw_upload_cs_push_constants(), brw_upload_cs_state(), brw_upload_gs_unit(), brw_upload_sampler_state_table(), brw_upload_vs_unit(), brw_upload_wm_unit(), gen4_update_renderbuffer_surface(), gen6_upload_blend_state(), gen6_upload_color_calc_state(), gen6_upload_depth_stencil_state(), gen6_upload_push_constants(), gen6_upload_scissor_state(), gen6_upload_sf_and_clip_viewports(), gen7_emit_null_surface_state(), gen7_upload_sf_clip_viewport(), gen8_allocate_surface_state(), gen8_upload_blend_state(), gen8_upload_sf_clip_viewport(), upload_cc_unit(), upload_clip_vp(), upload_default_color(), upload_sf_unit(), and upload_sf_vp().
brw_state_batch_size()
uint32_t brw_state_batch_size (struct brw_context * brw, uint32_t offset)
References brw_context::batch, and intel_batchbuffer::state_batch_sizes.
Referenced by intel_batchbuffer_require_space().
brw_state_dirty()
static bool brw_state_dirty (const struct brw_context * brw, GLuint mesa_flags, uint64_t brw_flags) inline static
References brw_compute_state_finished(), brw_depthbuffer_format(), brw_destroy_state(), brw_emit_select_pipeline(), brw_init_state(), brw_render_state_finished(), brw_upload_binding_table(), brw_upload_compute_state(), brw_upload_invariant_state(), brw_upload_render_state(), brw_upload_state_base_address(), brw_context::ctx, gen8_write_pma_stall_bits(), gl_context::NewDriverState, and brw_context::NewGLState.
Referenced by brw_ff_gs_state_dirty(), brw_gs_state_dirty(), brw_upload_clip_prog(), brw_upload_cs_prog(), brw_upload_sf_prog(), brw_upload_tcs_prog(), brw_upload_tes_prog(), brw_vs_state_dirty(), and brw_wm_state_dirty().
brw_update_renderbuffer_surface()
uint32_t brw_update_renderbuffer_surface (struct brw_context * brw, struct gl_renderbuffer * rb, uint32_t flags, unsigned unit, uint32_t surf_index)
References _mesa_get_format_name(), _mesa_get_render_format(), _mesa_problem(), brw_emit_surface_state(), brw_render_target_supported(), brw_context::ctx, brw_context::format_supported_as_render_target, brw_context::gen, GLuint, INTEL_AUX_BUFFER_DISABLED, intel_rb_format(), intel_renderbuffer(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, rb_mocs, and brw_context::render_target_format.
Referenced by gen6_init_vtable_surface_functions(), gen7_init_vtable_surface_functions(), and gen8_init_vtable_surface_functions().
brw_update_renderbuffer_surfaces()
void brw_update_renderbuffer_surfaces (struct brw_context * brw, const struct gl_framebuffer * fb, uint32_t render_target_start, uint32_t * surf_offset)
Construct SURFACE_STATE objects for renderbuffers/draw buffers.
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, brw_context::draw_aux_buffer_disabled, brw_context::emit_null_surface_state, GLuint, INTEL_AUX_BUFFER_DISABLED, intel_renderbuffer(), INTEL_RENDERBUFFER_LAYERED, brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by update_renderbuffer_surfaces().
brw_update_texture_surface()
void brw_update_texture_surface (struct gl_context * ctx, unsigned unit, uint32_t * surf_offset, bool for_gather, uint32_t plane)
References gl_texture_unit::_Current, intel_texture_object::_Format, intel_texture_object::_MaxLevel, brw_context::base, gl_texture_object::BaseLevel, brw_context(), brw_disable_aux_surface(), brw_emit_surface_state(), brw_get_texture_swizzle(), brw_texture_view_sane(), brw_update_buffer_texture_surface(), brw_context::ctx, gl_texture_object::DepthMode, brw_context::gen, gl_texture_object::Image, gl_texture_object::Immutable, INTEL_AUX_BUFFER_DISABLED, intel_texture_object(), brw_context::is_haswell, MESA_FORMAT_S_UINT8, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_object::mt, gl_texture_object::NumLayers, gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, brw_stage_state::surf_offset, swizzle(), swizzle_to_scs(), gl_texture_object::Target, tex_mocs, gl_context::Texture, translate_tex_format(), gl_texture_attrib::Unit, and brw_context::wm.
Referenced by update_stage_texture_surfaces().
brw_upload_binding_table()
void brw_upload_binding_table (struct brw_context * brw, uint32_t packet_name, const struct brw_stage_prog_data * prog_data, struct brw_stage_state * stage_state)
Upload a shader stage's binding table as indirect state.
This copies brw_stage_state::surf_offset[] into the indirect state section of the batchbuffer (allocated by brw_state_batch()).
References ADVANCE_BATCH, BEGIN_BATCH, brw_stage_state::bind_bo_offset, brw_context::bo, brw_emit_buffer_surface_state(), BRW_NEW_BINDING_TABLE_POINTERS, brw_state_batch(), brw_context::ctx, brw_context::gen, gl_context::NewDriverState, OUT_BATCH, brw_context::shader_time, and brw_stage_state::surf_offset.
Referenced by brw_gs_upload_binding_table(), brw_state_dirty(), brw_tcs_upload_binding_table(), brw_tes_upload_binding_table(), brw_upload_wm_binding_table(), and brw_vs_upload_binding_table().
brw_upload_cache()
void brw_upload_cache (struct brw_cache * cache, enum brw_cache_id cache_id, const void * key, GLuint key_sz, const void * data, GLuint data_sz, const void * aux, GLuint aux_sz, uint32_t * out_offset, void * out_aux)
References brw_cache_item::aux_size, brw_cache::bo, brw_cache::brw, brw_alloc_item_data(), brw_lookup_prog(), brw_cache_item::cache_id, CALLOC_STRUCT, brw_context::ctx, GLuint, brw_context::has_llc, brw_cache_item::hash, hash_key(), brw_cache::items, brw_cache_item::key, brw_cache_item::key_size, brw_cache::n_items, gl_context::NewDriverState, brw_cache_item::next, brw_cache_item::offset, rehash(), brw_cache_item::size, and brw_cache::size.
Referenced by brw_blorp_upload_shader(), brw_codegen_cs_prog(), brw_codegen_ff_gs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), brw_select_pipeline(), compile_clip_prog(), and compile_sf_prog().
brw_upload_clip_prog()
void brw_upload_clip_prog (struct brw_context * brw)
References gl_polygon_attrib::_FrontBit, gl_framebuffer::_MRD, _NEW_BUFFERS, _NEW_LIGHT, _NEW_POLYGON, _NEW_TRANSFORM, brw_clip_prog_key::attrs, gl_polygon_attrib::BackMode, brw_context::base, BRW_CACHE_CLIP_PROG, BRW_CLIPMODE_CLIP_NON_REJECTED, BRW_CLIPMODE_KERNEL_CLIP, BRW_CLIPMODE_NORMAL, BRW_CLIPMODE_REJECT_ALL, BRW_NEW_BLORP, BRW_NEW_FS_PROG_DATA, BRW_NEW_REDUCED_PRIMITIVE, BRW_NEW_VUE_MAP_GEOM_OUT, brw_search_cache(), brw_state_dirty(), brw_context::cache, brw_context::clip, CLIP_CULL, CLIP_FILL, CLIP_LINE, brw_clip_prog_key::clip_mode, CLIP_POINT, gl_transform_attrib::ClipPlanesEnabled, compile_clip_prog(), brw_clip_prog_key::contains_flat_varying, brw_clip_prog_key::contains_noperspective_varying, brw_clip_prog_key::copy_bfc_ccw, brw_clip_prog_key::copy_bfc_cw, brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, brw_clip_prog_key::do_unfilled, gl_context::DrawBuffer, brw_clip_prog_key::fill_ccw, brw_clip_prog_key::fill_cw, gl_polygon_attrib::FrontMode, brw_context::gen, GLuint, brw_clip_prog_key::interp_mode, gl_context::Light, gl_light_attrib::Model, brw_clip_prog_key::nr_userclip, brw_clip_prog_key::offset_ccw, brw_clip_prog_key::offset_clamp, brw_clip_prog_key::offset_cw, brw_clip_prog_key::offset_factor, brw_clip_prog_key::offset_units, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, gl_context::Polygon, brw_clip_prog_key::primitive, brw_stage_state::prog_data, brw_context::prog_data, brw_context::prog_offset, gl_light_attrib::ProvokingVertex, brw_clip_prog_key::pv_first, brw_context::reduced_primitive, gl_context::Transform, gl_lightmodel::TwoSide, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by brw_upload_programs().
brw_upload_compute_state()
void brw_upload_compute_state (struct brw_context * brw)
References BRW_COMPUTE_PIPELINE, and brw_upload_pipeline_state().
Referenced by brw_dispatch_compute_common(), and brw_state_dirty().
brw_upload_invariant_state()
void brw_upload_invariant_state (struct brw_context * brw)
Misc invariant state packets.
References _3DSTATE_AA_LINE_PARAMETERS, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_select_pipeline(), BRW_RENDER_PIPELINE, CMD_STATE_SIP, brw_context::gen, GEN4_3DSTATE_VF_STATISTICS, GM45_3DSTATE_VF_STATISTICS, brw_context::is_g4x, brw_context::last_pipeline, and OUT_BATCH.
Referenced by brw_state_dirty(), and brw_upload_initial_gpu_state().
brw_upload_pull_constants()
void brw_upload_pull_constants (struct brw_context * brw, GLbitfield64 brw_new_constbuf, const struct gl_program * prog, struct brw_stage_state * stage_state, const struct brw_stage_prog_data * prog_data)
Creates a temporary BO containing the pull constant data for the shader stage, and the SURFACE_STATE struct that points at it.
Pull constants are GLSL uniforms (and other constant data) beyond what we could fit as push constants, or that have variable-index array access (which is easiest to support using pull constants, and avoids filling register space with mostly-unused data).
Compare this path to brw_curbe.c for gen4/5 push constants, and gen6_vs_state.c for gen6+ push constants.
References brw_create_constant_surface(), brw_context::ctx, intel_upload_space(), gl_context::NewDriverState, gl_program::Parameters, and brw_stage_state::surf_offset.
Referenced by brw_upload_cs_pull_constants(), brw_upload_gs_pull_constants(), brw_upload_tcs_pull_constants(), brw_upload_tes_pull_constants(), brw_upload_vs_pull_constants(), and brw_upload_wm_pull_constants().
brw_upload_render_state()
void brw_upload_render_state (struct brw_context * brw)
References BRW_RENDER_PIPELINE, and brw_upload_pipeline_state().
Referenced by brw_state_dirty(), and brw_try_draw_prims().
brw_upload_sf_prog()
void brw_upload_sf_prog (struct brw_context * brw)
References gl_polygon_attrib::_FrontBit, _NEW_BUFFERS, _NEW_HINT, _NEW_LIGHT, _NEW_POINT, _NEW_POLYGON, _NEW_PROGRAM, _NEW_TRANSFORM, gl_vertex_program_state::_TwoSideEnabled, brw_sf_prog_key::attrs, brw_context::base, BITFIELD64_BIT, BRW_CACHE_SF_PROG, BRW_NEW_BLORP, BRW_NEW_FS_PROG_DATA, BRW_NEW_REDUCED_PRIMITIVE, BRW_NEW_VUE_MAP_GEOM_OUT, brw_search_cache(), brw_state_dirty(), brw_context::cache, gl_transform_attrib::ClipPlanesEnabled, compile_sf_prog(), brw_sf_prog_key::contains_flat_varying, gl_point_attrib::CoordReplace, brw_context::ctx, brw_sf_prog_key::do_point_coord, brw_sf_prog_key::do_point_sprite, brw_sf_prog_key::do_twoside_color, gl_context::DrawBuffer, gl_light_attrib::Enabled, brw_context::fragment_program, brw_sf_prog_key::frontface_ccw, gl_program::info, brw_sf_prog_key::interp_mode, gl_context::Light, gl_light_attrib::Model, gl_context::Point, brw_sf_prog_key::point_sprite_coord_replace, gl_point_attrib::PointSprite, gl_context::Polygon, brw_sf_prog_key::primitive, brw_stage_state::prog_data, brw_context::prog_data, brw_context::prog_offset, brw_context::reduced_primitive, brw_context::sf, SF_LINES, SF_POINTS, SF_TRIANGLES, SF_UNFILLED_TRIS, brw_sf_prog_key::sprite_origin_lower_left, gl_point_attrib::SpriteOrigin, gl_context::Transform, gl_lightmodel::TwoSide, brw_sf_prog_key::userclip_active, gl_context::VertexProgram, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by brw_upload_programs().
brw_upload_state_base_address()
void brw_upload_state_base_address (struct brw_context * brw)
Define the base addresses which some state is referenced from.
This allows us to avoid having to emit relocations for the objects, and is actually required for binding table pointers on gen6.
Surface state base address covers binding table pointers and surface state objects, but not the surfaces that the surface state objects point to.
References ADVANCE_BATCH, brw_context::batch, BDW_MOCS_WB, BEGIN_BATCH, brw_cache::bo, intel_batchbuffer::bo, BRW_NEW_STATE_BASE_ADDRESS, brw_context::cache, CMD_STATE_BASE_ADDRESS, brw_context::ctx, brw_context::gen, GEN7_MOCS_L3, gl_context::NewDriverState, OUT_BATCH, OUT_RELOC, OUT_RELOC64, SKL_MOCS_WB, and intel_batchbuffer::state_base_address_emitted.
Referenced by blorp_exec(), brw_state_dirty(), and brw_upload_pipeline_state().
calculate_attr_overrides()
void calculate_attr_overrides (const struct brw_context * brw, uint16_t * attr_overrides, uint32_t * point_sprite_enables, uint32_t * urb_entry_read_length, uint32_t * urb_entry_read_offset)
Create the mapping from the FS inputs we produce to the previous pipeline stage (GS or VS) outputs they source from.
References gl_vertex_program_state::_TwoSideEnabled, brw_context::base, brw_is_drawing_points(), gl_point_attrib::CoordReplace, brw_context::ctx, brw_context::fragment_program, get_attr_override(), gl_program::info, gl_context::Point, gl_point_attrib::PointSprite, brw_stage_state::prog_data, gl_context::VertexProgram, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by upload_sbe(), upload_sbe_state(), and upload_sf_state().
gen4_init_vtable_surface_functions()
void gen4_init_vtable_surface_functions (struct brw_context * brw)
References brw_emit_null_surface_state(), brw_context::emit_null_surface_state, gen4_update_renderbuffer_surface(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext(), and gen6_init_vtable_surface_functions().
gen6_init_vtable_surface_functions()
void gen6_init_vtable_surface_functions (struct brw_context * brw)
References brw_update_renderbuffer_surface(), gen4_init_vtable_surface_functions(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext().
gen6_upload_wm_state()
void gen6_upload_wm_state (struct brw_context * brw, const struct brw_wm_prog_data * prog_data, const struct brw_stage_state * stage_state, bool multisampled_fbo, bool dual_source_blend_enable, bool kill_enable, bool color_buffer_write_enable, bool msaa_enabled, bool line_stipple_enable, bool polygon_stipple_enable, bool statistic_enable)
References _3DSTATE_CONSTANT_PS, _3DSTATE_WM, ADVANCE_BATCH, BEGIN_BATCH, intel_screen::devinfo, GEN6_CONSTANT_BUFFER_0_ENABLE, GEN6_WM_16_DISPATCH_ENABLE, GEN6_WM_8_DISPATCH_ENABLE, GEN6_WM_BARYCENTRIC_INTERPOLATION_MODE_SHIFT, GEN6_WM_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN6_WM_COMPUTED_DEPTH, GEN6_WM_DISPATCH_ENABLE, GEN6_WM_DISPATCH_START_GRF_SHIFT_0, GEN6_WM_DISPATCH_START_GRF_SHIFT_2, GEN6_WM_DUAL_SOURCE_BLEND_ENABLE, GEN6_WM_FLOATING_POINT_MODE_ALT, GEN6_WM_KILL_ENABLE, GEN6_WM_LINE_AA_WIDTH_1_0, GEN6_WM_LINE_END_CAP_AA_WIDTH_0_5, GEN6_WM_LINE_STIPPLE_ENABLE, GEN6_WM_MAX_THREADS_SHIFT, GEN6_WM_MSDISPMODE_PERPIXEL, GEN6_WM_MSDISPMODE_PERSAMPLE, GEN6_WM_MSRAST_OFF_PIXEL, GEN6_WM_MSRAST_ON_PATTERN, GEN6_WM_NUM_SF_OUTPUTS_SHIFT, GEN6_WM_OMASK_TO_RENDER_TARGET, GEN6_WM_POLYGON_STIPPLE_ENABLE, GEN6_WM_POSOFFSET_NONE, GEN6_WM_POSOFFSET_SAMPLE, GEN6_WM_SAMPLER_COUNT_SHIFT, GEN6_WM_STATISTICS_ENABLE, GEN6_WM_USES_SOURCE_DEPTH, GEN6_WM_USES_SOURCE_W, OUT_BATCH, OUT_RELOC, brw_stage_state::per_thread_scratch, brw_stage_state::prog_offset, brw_stage_state::push_const_offset, brw_stage_state::push_const_size, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, and brw_context::screen.
Referenced by upload_wm_state().
gen7_check_surface_setup()
void gen7_check_surface_setup (uint32_t * surf, bool is_render_target)
References GEN7_SURFACE_ARYSPC_LOD0, GEN7_SURFACE_MSFMT_DEPTH_STENCIL, GEN7_SURFACE_MSFMT_MSS, GEN7_SURFACE_MULTISAMPLECOUNT_1, GEN7_SURFACE_MULTISAMPLECOUNT_4, GEN7_SURFACE_MULTISAMPLECOUNT_8, GET_FIELD, INTEL_MASK, and void.
Referenced by gen7_emit_null_surface_state().
gen7_init_vtable_surface_functions()
void gen7_init_vtable_surface_functions (struct brw_context * brw)
References brw_update_renderbuffer_surface(), brw_context::emit_null_surface_state, gen7_emit_null_surface_state(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext().
gen7_restore_default_l3_config()
void gen7_restore_default_l3_config (struct brw_context * brw)
Hack to restore the default L3 configuration.
This will be called at the end of every batch in order to reset the L3 configuration to the default values for the time being until the kernel is fixed. Until kernel commit 6702cf16e0ba8b0129f5aa1b6609d4e9c70bc13b (included in v4.1) we would set the MI_RESTORE_INHIBIT bit when submitting batch buffers for the default context used by the DDX, which meant that any context state changed by the GL would leak into the DDX, the assumption being that the DDX would initialize any state it cares about manually. The DDX is however not careful enough to program an L3 configuration explicitly, and it makes assumptions about it (URB size) which won't hold and cause it to misrender if we let our L3 set-up to leak into the DDX.
Since v4.1 of the Linux kernel the default context is saved and restored normally, so it's far less likely for our L3 programming to interfere with other contexts – In fact restoring the default L3 configuration at the end of the batch will be redundant most of the time. A kind of state leak is still possible though if the context making assumptions about L3 state is created immediately after our context was active (e.g. without the DDX default context being scheduled in between) because at present the DRM doesn't fully initialize the contents of newly created contexts and instead sets the MI_RESTORE_INHIBIT flag causing it to inherit the state from the last active context.
It's possible to realize such a scenario if, say, an X server (or a GL application using an outdated non-L3-aware Mesa version) is started while another GL application is running and happens to have modified the L3 configuration, or if no X server is running at all and a GL application using a non-L3-aware Mesa version is started after another GL application ran and modified the L3 configuration – The latter situation can actually be reproduced easily on IVB in our CI system.
References can_do_pipelined_register_writes(), brw_context::config, intel_screen::devinfo, brw_context::l3, brw_context::screen, setup_l3_config(), and update_urb_size().
Referenced by brw_finish_batch().
gen7_upload_3dstate_so_decl_list()
void gen7_upload_3dstate_so_decl_list (struct brw_context * brw, const struct brw_vue_map * vue_map)
Outputs the 3DSTATE_SO_DECL_LIST command.
The data output is a series of 64-bit entries containing a SO_DECL per stream. We only have one stream of rendering coming out of the GS unit, so we only emit stream 0 (low 16 bits) SO_DECLs.
References _3DSTATE_SO_DECL_LIST, ADVANCE_BATCH, BEGIN_BATCH, BRW_MAX_SOL_BUFFERS, gl_transform_feedback_output::ComponentOffset, brw_context::ctx, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_output::DstOffset, MAX_PROGRAM_OUTPUTS, MAX_VERTEX_STREAMS, gl_transform_feedback_output::NumComponents, gl_transform_feedback_info::NumOutputs, OUT_BATCH, gl_transform_feedback_output::OutputBuffer, gl_transform_feedback_output::OutputRegister, gl_transform_feedback_info::Outputs, gl_transform_feedback_object::program, gl_program::sh, SO_DECL_COMPONENT_MASK_SHIFT, SO_DECL_HOLE_FLAG, SO_DECL_OUTPUT_BUFFER_SLOT_SHIFT, SO_DECL_REGISTER_INDEX_SHIFT, SO_NUM_ENTRIES_0_SHIFT, SO_NUM_ENTRIES_1_SHIFT, SO_NUM_ENTRIES_2_SHIFT, SO_NUM_ENTRIES_3_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_0_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_1_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_2_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_3_SHIFT, gl_transform_feedback_output::StreamId, and gl_context::TransformFeedback.
Referenced by upload_sol_state().
gen7_upload_constant_state()
void gen7_upload_constant_state (struct brw_context * brw, const struct brw_stage_state * stage_state, bool active, unsigned opcode)
References ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH, intel_batchbuffer::bo, BRW_NEW_SURFACES, brw_context::ctx, brw_context::gen, GEN7_MOCS_L3, gl_context::NewDriverState, OUT_BATCH, OUT_RELOC64, brw_stage_state::push_const_offset, and brw_stage_state::push_const_size.
Referenced by gen6_upload_gs_push_constants(), gen6_upload_vs_push_constants(), gen6_upload_wm_push_constants(), gen7_upload_tcs_push_constants(), and gen7_upload_tes_push_constants().
gen8_init_vtable_surface_functions()
void gen8_init_vtable_surface_functions (struct brw_context * brw)
References brw_update_renderbuffer_surface(), brw_context::emit_null_surface_state, gen8_emit_null_surface_state(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext().
gen8_upload_3dstate_so_buffers()
void gen8_upload_3dstate_so_buffers (struct brw_context * brw)
References _3DSTATE_SO_BUFFER, ADVANCE_BATCH, BDW_MOCS_WB, BEGIN_BATCH, gl_transform_feedback_object::Buffers, brw_context::ctx, gl_transform_feedback_state::CurrentObject, brw_context::gen, GEN8_SO_BUFFER_ENABLE, GEN8_SO_BUFFER_OFFSET_ADDRESS_ENABLE, GEN8_SO_BUFFER_OFFSET_WRITE_ENABLE, intel_buffer_object(), intel_bufferobj_buffer(), gl_transform_feedback_object::Offset, brw_transform_feedback_object::offset_bo, OUT_BATCH, OUT_RELOC64, gl_transform_feedback_object::Size, SKL_MOCS_WB, SO_BUFFER_INDEX_SHIFT, gl_context::TransformFeedback, and brw_transform_feedback_object::zero_offsets.
Referenced by upload_sol_state().
gen8_upload_ps_extra()
void gen8_upload_ps_extra (struct brw_context * brw, const struct brw_wm_prog_data * prog_data)
References _3DSTATE_PS_EXTRA, ADVANCE_BATCH, BEGIN_BATCH, brw_color_buffer_write_enabled(), BRW_PCICMS_DEPTH, BRW_PSICMS_INNER, BRW_PSICMS_NORMAL, brw_context::ctx, brw_context::gen, GEN8_PSX_ATTRIBUTE_ENABLE, GEN8_PSX_COMPUTED_DEPTH_MODE_SHIFT, GEN8_PSX_KILL_ENABLE, GEN8_PSX_OMASK_TO_RENDER_TARGET, GEN8_PSX_PIXEL_SHADER_VALID, GEN8_PSX_SHADER_HAS_UAV, GEN8_PSX_SHADER_IS_PER_SAMPLE, GEN8_PSX_SHADER_USES_INPUT_COVERAGE_MASK, GEN8_PSX_USES_SOURCE_DEPTH, GEN8_PSX_USES_SOURCE_W, GEN9_PSX_SHADER_COMPUTES_STENCIL, GEN9_PSX_SHADER_NORMAL_COVERAGE_MASK_SHIFT, GEN9_PSX_SHADER_PULLS_BARY, gl_context::IntelConservativeRasterization, and OUT_BATCH.
Referenced by upload_ps_extra().
gen8_upload_ps_state()
void gen8_upload_ps_state (struct brw_context * brw, const struct brw_stage_state * stage_state, const struct brw_wm_prog_data * prog_data, uint32_t fast_clear_op)
References _3DSTATE_PS, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, GEN7_PS_16_DISPATCH_ENABLE, GEN7_PS_8_DISPATCH_ENABLE, GEN7_PS_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN7_PS_DISPATCH_START_GRF_SHIFT_0, GEN7_PS_DISPATCH_START_GRF_SHIFT_2, GEN7_PS_FLOATING_POINT_MODE_ALT, GEN7_PS_POSOFFSET_NONE, GEN7_PS_POSOFFSET_SAMPLE, GEN7_PS_PUSH_CONSTANT_ENABLE, GEN7_PS_VECTOR_MASK_ENABLE, HSW_PS_MAX_THREADS_SHIFT, OUT_BATCH, OUT_RELOC64, brw_stage_state::per_thread_scratch, brw_stage_state::prog_offset, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, and SET_FIELD.
Referenced by upload_ps_state().
gen8_write_pma_stall_bits()
void gen8_write_pma_stall_bits (struct brw_context * brw, uint32_t pma_stall_bits)
References gl_stencil_attrib::_WriteEnabled, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_pipe_control_flush(), brw_context::ctx, GEN7_CACHE_MODE_1, GEN8_HIZ_PMA_MASK_BITS, MI_LOAD_REGISTER_IMM, OUT_BATCH, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, brw_context::pma_stall_bits, and gl_context::Stencil.
Referenced by blorp_exec(), brw_state_dirty(), gen8_emit_pma_stall_workaround(), and gen8_hiz_exec().
translate_tex_format()
GLuint translate_tex_format (struct brw_context * brw, mesa_format mesa_format, GLenum srgb_decode)
It is possible to process these formats using the LDR Profile or the Full Profile mode of the hardware. Because, it isn't possible to determine if an HDR or LDR texture is being rendered, we can't determine which mode to enable in the hardware. Therefore, to handle all cases, always default to Full profile unless we are processing sRGBs, which are incompatible with this mode.
References _mesa_get_srgb_format_linear(), brw_isl_format_for_mesa_format(), brw_context::ctx, gl_context::Extensions, brw_context::gen, GEN9_SURFACE_ASTC_HDR_FORMAT_BIT, GLuint, brw_context::is_g4x, gl_extensions::KHR_texture_compression_astc_hdr, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA_ASTC_10x10, MESA_FORMAT_RGBA_ASTC_10x5, MESA_FORMAT_RGBA_ASTC_10x6, MESA_FORMAT_RGBA_ASTC_10x8, MESA_FORMAT_RGBA_ASTC_12x10, MESA_FORMAT_RGBA_ASTC_12x12, MESA_FORMAT_RGBA_ASTC_4x4, MESA_FORMAT_RGBA_ASTC_5x4, MESA_FORMAT_RGBA_ASTC_5x5, MESA_FORMAT_RGBA_ASTC_6x5, MESA_FORMAT_RGBA_ASTC_6x6, MESA_FORMAT_RGBA_ASTC_8x5, MESA_FORMAT_RGBA_ASTC_8x6, MESA_FORMAT_RGBA_ASTC_8x8, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, and MESA_FORMAT_Z_UNORM16.
Referenced by brw_update_texture_surface(), and intel_miptree_get_isl_surf().
translate_tex_target()
GLuint translate_tex_target (GLenum target)
References BRW_SURFACE_1D, BRW_SURFACE_2D, BRW_SURFACE_3D, BRW_SURFACE_CUBE, and GL_TEXTURE_EXTERNAL_OES.
Referenced by gen6_emit_depth_stencil_hiz(), gen7_emit_depth_stencil_hiz(), and gen8_emit_depth_stencil_hiz().
use_state_point_size()
static bool use_state_point_size (const struct brw_context * brw) inline static
References gl_point_attrib::_Attenuated, brw_calculate_guardband_size(), brw_context::ctx, gl_context::Point, gl_vertex_program_state::PointSizeEnabled, gl_context::VertexProgram, and brw_context::vue_map_geom_out.
Referenced by upload_sf(), and upload_sf_state().
Variable Documentation
brw_binding_table_pointers
const struct brw_tracked_state brw_binding_table_pointers
brw_blend_constant_color
const struct brw_tracked_state brw_blend_constant_color
brw_cc_unit
const struct brw_tracked_state brw_cc_unit
brw_cc_vp
const struct brw_tracked_state brw_cc_vp
brw_clip_unit
const struct brw_tracked_state brw_clip_unit
brw_constant_buffer
const struct brw_tracked_state brw_constant_buffer
brw_cs_abo_surfaces
const struct brw_tracked_state brw_cs_abo_surfaces
brw_cs_image_surfaces
const struct brw_tracked_state brw_cs_image_surfaces
brw_cs_pull_constants
const struct brw_tracked_state brw_cs_pull_constants
brw_cs_samplers
const struct brw_tracked_state brw_cs_samplers
brw_cs_state
const struct brw_tracked_state brw_cs_state
brw_cs_texture_surfaces
const struct brw_tracked_state brw_cs_texture_surfaces
brw_cs_ubo_surfaces
const struct brw_tracked_state brw_cs_ubo_surfaces
brw_cs_work_groups_surface
const struct brw_tracked_state brw_cs_work_groups_surface
brw_curbe_offsets
const struct brw_tracked_state brw_curbe_offsets
brw_depthbuffer
const struct brw_tracked_state brw_depthbuffer
brw_drawing_rect
const struct brw_tracked_state brw_drawing_rect
brw_fs_samplers
const struct brw_tracked_state brw_fs_samplers
brw_gs_abo_surfaces
const struct brw_tracked_state brw_gs_abo_surfaces
brw_gs_binding_table
const struct brw_tracked_state brw_gs_binding_table
brw_gs_image_surfaces
const struct brw_tracked_state brw_gs_image_surfaces
brw_gs_pull_constants
const struct brw_tracked_state brw_gs_pull_constants
brw_gs_samplers
const struct brw_tracked_state brw_gs_samplers
brw_gs_ubo_surfaces
const struct brw_tracked_state brw_gs_ubo_surfaces
brw_gs_unit
const struct brw_tracked_state brw_gs_unit
brw_index_buffer
const struct brw_tracked_state brw_index_buffer
brw_indices
const struct brw_tracked_state brw_indices
brw_invariant_state
const struct brw_tracked_state brw_invariant_state
brw_line_stipple
const struct brw_tracked_state brw_line_stipple
brw_polygon_stipple
const struct brw_tracked_state brw_polygon_stipple
brw_polygon_stipple_offset
const struct brw_tracked_state brw_polygon_stipple_offset
brw_psp_urb_cbs
const struct brw_tracked_state brw_psp_urb_cbs
brw_recalculate_urb_fence
const struct brw_tracked_state brw_recalculate_urb_fence
brw_renderbuffer_read_surfaces
const struct brw_tracked_state brw_renderbuffer_read_surfaces
brw_renderbuffer_surfaces
const struct brw_tracked_state brw_renderbuffer_surfaces
brw_sf_unit
const struct brw_tracked_state brw_sf_unit
brw_sf_vp
const struct brw_tracked_state brw_sf_vp
brw_tcs_abo_surfaces
const struct brw_tracked_state brw_tcs_abo_surfaces
brw_tcs_binding_table
const struct brw_tracked_state brw_tcs_binding_table
brw_tcs_image_surfaces
const struct brw_tracked_state brw_tcs_image_surfaces
brw_tcs_pull_constants
const struct brw_tracked_state brw_tcs_pull_constants
brw_tcs_samplers
const struct brw_tracked_state brw_tcs_samplers
brw_tcs_ubo_surfaces
const struct brw_tracked_state brw_tcs_ubo_surfaces
brw_tes_abo_surfaces
const struct brw_tracked_state brw_tes_abo_surfaces
brw_tes_binding_table
const struct brw_tracked_state brw_tes_binding_table
brw_tes_image_surfaces
const struct brw_tracked_state brw_tes_image_surfaces
brw_tes_pull_constants
const struct brw_tracked_state brw_tes_pull_constants
brw_tes_samplers
const struct brw_tracked_state brw_tes_samplers
brw_tes_ubo_surfaces
const struct brw_tracked_state brw_tes_ubo_surfaces
brw_texture_surfaces
const struct brw_tracked_state brw_texture_surfaces
brw_vertices
const struct brw_tracked_state brw_vertices
brw_vs_abo_surfaces
const struct brw_tracked_state brw_vs_abo_surfaces
brw_vs_binding_table
const struct brw_tracked_state brw_vs_binding_table
brw_vs_image_surfaces
const struct brw_tracked_state brw_vs_image_surfaces
brw_vs_pull_constants
const struct brw_tracked_state brw_vs_pull_constants
brw_vs_samplers
const struct brw_tracked_state brw_vs_samplers
brw_vs_ubo_surfaces
const struct brw_tracked_state brw_vs_ubo_surfaces
brw_vs_unit
const struct brw_tracked_state brw_vs_unit
brw_wm_abo_surfaces
const struct brw_tracked_state brw_wm_abo_surfaces
brw_wm_binding_table
const struct brw_tracked_state brw_wm_binding_table
brw_wm_image_surfaces
const struct brw_tracked_state brw_wm_image_surfaces
brw_wm_pull_constants
const struct brw_tracked_state brw_wm_pull_constants
brw_wm_ubo_surfaces
const struct brw_tracked_state brw_wm_ubo_surfaces
brw_wm_unit
const struct brw_tracked_state brw_wm_unit
gen6_binding_table_pointers
const struct brw_tracked_state gen6_binding_table_pointers
gen6_blend_state
const struct brw_tracked_state gen6_blend_state
gen6_clip_state
const struct brw_tracked_state gen6_clip_state
gen6_color_calc_state
const struct brw_tracked_state gen6_color_calc_state
gen6_depth_stencil_state
const struct brw_tracked_state gen6_depth_stencil_state
gen6_gs_binding_table
const struct brw_tracked_state gen6_gs_binding_table
gen6_gs_push_constants
const struct brw_tracked_state gen6_gs_push_constants
gen6_gs_state
const struct brw_tracked_state gen6_gs_state
gen6_multisample_state
const struct brw_tracked_state gen6_multisample_state
gen6_renderbuffer_surfaces
const struct brw_tracked_state gen6_renderbuffer_surfaces
gen6_sampler_state
const struct brw_tracked_state gen6_sampler_state
gen6_scissor_state
const struct brw_tracked_state gen6_scissor_state
gen6_sf_and_clip_viewports
const struct brw_tracked_state gen6_sf_and_clip_viewports
gen6_sf_state
const struct brw_tracked_state gen6_sf_state
gen6_sf_vp
const struct brw_tracked_state gen6_sf_vp
gen6_sol_surface
const struct brw_tracked_state gen6_sol_surface
gen6_urb
const struct brw_tracked_state gen6_urb
gen6_viewport_state
const struct brw_tracked_state gen6_viewport_state
gen6_vs_push_constants
const struct brw_tracked_state gen6_vs_push_constants
gen6_vs_state
const struct brw_tracked_state gen6_vs_state
gen6_wm_push_constants
const struct brw_tracked_state gen6_wm_push_constants
gen6_wm_state
const struct brw_tracked_state gen6_wm_state
gen7_cs_push_constants
const struct brw_tracked_state gen7_cs_push_constants
gen7_depthbuffer
const struct brw_tracked_state gen7_depthbuffer
See also
brw_context.state.depth_region
gen7_ds_state
const struct brw_tracked_state gen7_ds_state
gen7_gs_state
const struct brw_tracked_state gen7_gs_state
gen7_hs_state
const struct brw_tracked_state gen7_hs_state
gen7_l3_state
const struct brw_tracked_state gen7_l3_state
Referenced by blorp_exec().
gen7_ps_state
const struct brw_tracked_state gen7_ps_state
gen7_push_constant_space
const struct brw_tracked_state gen7_push_constant_space
gen7_sbe_state
const struct brw_tracked_state gen7_sbe_state
gen7_sf_clip_viewport
const struct brw_tracked_state gen7_sf_clip_viewport
gen7_sf_state
const struct brw_tracked_state gen7_sf_state
gen7_sol_state
const struct brw_tracked_state gen7_sol_state
gen7_tcs_push_constants
const struct brw_tracked_state gen7_tcs_push_constants
gen7_te_state
const struct brw_tracked_state gen7_te_state
gen7_tes_push_constants
const struct brw_tracked_state gen7_tes_push_constants
gen7_urb
const struct brw_tracked_state gen7_urb
gen7_vs_state
const struct brw_tracked_state gen7_vs_state
gen7_wm_state
const struct brw_tracked_state gen7_wm_state
gen8_blend_state
const struct brw_tracked_state gen8_blend_state
gen8_ds_state
const struct brw_tracked_state gen8_ds_state
gen8_gs_state
const struct brw_tracked_state gen8_gs_state
gen8_hs_state
const struct brw_tracked_state gen8_hs_state
gen8_index_buffer
const struct brw_tracked_state gen8_index_buffer
gen8_multisample_state
const struct brw_tracked_state gen8_multisample_state
gen8_pma_fix
const struct brw_tracked_state gen8_pma_fix
gen8_ps_blend
const struct brw_tracked_state gen8_ps_blend
gen8_ps_extra
const struct brw_tracked_state gen8_ps_extra
gen8_ps_state
const struct brw_tracked_state gen8_ps_state
gen8_raster_state
const struct brw_tracked_state gen8_raster_state
gen8_sbe_state
const struct brw_tracked_state gen8_sbe_state
gen8_sf_clip_viewport
const struct brw_tracked_state gen8_sf_clip_viewport
gen8_sf_state
const struct brw_tracked_state gen8_sf_state
gen8_vertices
const struct brw_tracked_state gen8_vertices
gen8_vf_topology
const struct brw_tracked_state gen8_vf_topology
gen8_vs_state
const struct brw_tracked_state gen8_vs_state
gen8_wm_depth_stencil
const struct brw_tracked_state gen8_wm_depth_stencil
gen8_wm_state
const struct brw_tracked_state gen8_wm_state
haswell_cut_index
const struct brw_tracked_state haswell_cut_index