Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_cs.h File Reference
Functions
void brw_upload_cs_prog (struct brw_context *brw)
Function Documentation
brw_upload_cs_prog()
void brw_upload_cs_prog (struct brw_context * brw)
References gl_compute_program_state::_Current, _NEW_TEXTURE, brw_context::base, BRW_CACHE_CS_PROG, brw_codegen_cs_prog(), brw_cs_populate_key(), BRW_NEW_COMPUTE_PROGRAM, brw_search_cache(), brw_state_dirty(), brw_context::cache, brw_context::compute_program, gl_context::ComputeProgram, brw_context::cs, brw_context::ctx, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_stage_state::sampler_count, gl_program::SamplersUsed, and void.
Referenced by brw_upload_programs().