Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_cs.c File Reference
#include "util/ralloc.h"
#include "brw_context.h"
#include "brw_cs.h"
#include "brw_wm.h"
#include "intel_mipmap_tree.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "compiler/brw_nir.h"
#include "brw_program.h"
#include "compiler/glsl/ir_uniform.h"
Functions
static void assign_cs_binding_table_offsets (const struct gen_device_info *devinfo, const struct gl_program *prog, struct brw_cs_prog_data *prog_data)
static bool brw_codegen_cs_prog (struct brw_context *brw, struct brw_program *cp, struct brw_cs_prog_key *key)
static void brw_cs_populate_key (struct brw_context *brw, struct brw_cs_prog_key *key)
void brw_upload_cs_prog (struct brw_context *brw)
bool brw_cs_precompile (struct gl_context *ctx, struct gl_program *prog)
Function Documentation
assign_cs_binding_table_offsets()
static void assign_cs_binding_table_offsets (const struct gen_device_info * devinfo, const struct gl_program * prog, struct brw_cs_prog_data * prog_data) static
References brw_assign_common_binding_table_offsets().
Referenced by brw_codegen_cs_prog().
brw_codegen_cs_prog()
static bool brw_codegen_cs_prog (struct brw_context * brw, struct brw_program * cp, struct brw_cs_prog_key * key) static
References _mesa_problem(), assign_cs_binding_table_offsets(), brw_context::base, brw_context::batch, brw_alloc_stage_scratch(), BRW_CACHE_CS_PROG, brw_get_shader_time_index(), brw_nir_setup_glsl_uniforms(), brw_upload_cache(), brw_context::cache, brw_program::compiled_once, intel_screen::compiler, gl_context::Const, brw_context::cs, brw_context::ctx, intel_screen::devinfo, get_time(), GLuint, gl_program::info, brw_context::is_haswell, intel_batchbuffer::last_bo, linking_failure, gl_program_constants::MaxTextureImageUnits, gl_program::nir, brw_context::perf_debug, brw_stage_state::prog_data, brw_stage_state::prog_offset, gl_constants::Program, brw_program::program, brw_context::screen, gl_program::sh, ST_CS, and intel_screen::subslice_total.
Referenced by brw_cs_precompile(), and brw_upload_cs_prog().
brw_cs_populate_key()
static void brw_cs_populate_key (struct brw_context * brw, struct brw_cs_prog_key * key) static
References brw_populate_sampler_prog_key_data(), brw_context::compute_program, brw_context::ctx, and brw_program::id.
Referenced by brw_upload_cs_prog().
brw_cs_precompile()
bool brw_cs_precompile (struct gl_context * ctx, struct gl_program * prog)
References brw_context::base, brw_codegen_cs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_context::cs, brw_program::id, brw_stage_state::prog_data, and brw_stage_state::prog_offset.
Referenced by brw_shader_precompile().
brw_upload_cs_prog()
void brw_upload_cs_prog (struct brw_context * brw)
References gl_compute_program_state::_Current, _NEW_TEXTURE, brw_context::base, BRW_CACHE_CS_PROG, brw_codegen_cs_prog(), brw_cs_populate_key(), BRW_NEW_COMPUTE_PROGRAM, brw_search_cache(), brw_state_dirty(), brw_context::cache, brw_context::compute_program, gl_context::ComputeProgram, brw_context::cs, brw_context::ctx, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_stage_state::sampler_count, gl_program::SamplersUsed, and void.
Referenced by brw_upload_programs().