Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_meta_util.c File Reference
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_fbo.h"
#include "brw_meta_util.h"
#include "brw_state.h"
#include "main/blend.h"
#include "main/fbobject.h"
#include "util/format_srgb.h"
Functions
static void fixup_mirroring (bool *mirror, float *coord0, float *coord1)
Helper function for handling mirror image blits.
static bool compute_pixels_clipped (float x0, float y0, float x1, float y1, float min_x, float min_y, float max_x, float max_y, float *clipped_x0, float *clipped_y0, float *clipped_x1, float *clipped_y1)
Compute the number of pixels to clip for each side of a rect.
static void clip_coordinates (bool mirror, float *src, float *dst0, float *dst1, float clipped_src0, float clipped_dst0, float clipped_dst1, float scale, bool isLeftOrBottom)
Clips a coordinate (left, right, top or bottom) for the src or dst rect (whichever requires the largest clip) and adjusts the coordinate for the other rect accordingly.
bool brw_meta_mirror_clip_and_scissor (const struct gl_context *ctx, const struct gl_framebuffer *read_fb, const struct gl_framebuffer *draw_fb, GLfloat *srcX0, GLfloat *srcY0, GLfloat *srcX1, GLfloat *srcY1, GLfloat *dstX0, GLfloat *dstY0, GLfloat *dstX1, GLfloat *dstY1, bool *mirror_x, bool *mirror_y)
bool brw_is_color_fast_clear_compatible (struct brw_context *brw, const struct intel_mipmap_tree *mt, const union gl_color_union *color)
Determine if fast color clear supports the given clear color.
union gl_color_union brw_meta_convert_fast_clear_color (const struct brw_context *brw, const struct intel_mipmap_tree *mt, const union gl_color_union *color)
Convert the given color to a bitfield suitable for ORing into DWORD 7 of SURFACE_STATE (DWORD 12-15 on SKL+).
bool brw_meta_set_fast_clear_color (struct brw_context *brw, union gl_color_union *curr_color, const union gl_color_union *new_color)
Function Documentation
brw_is_color_fast_clear_compatible()
bool brw_is_color_fast_clear_compatible (struct brw_context * brw, const struct intel_mipmap_tree * mt, const union gl_color_union * color)
Determine if fast color clear supports the given clear color.
Fast color clear can only clear to color values of 1.0 or 0.0. At the moment we only support floating point, unorm, and snorm buffers.
References _mesa_format_has_color_component(), _mesa_get_format_name(), _mesa_get_render_format(), _mesa_get_srgb_format_linear(), _mesa_is_format_integer_color(), brw_isl_format_for_mesa_format(), gl_context::Color, brw_context::ctx, gl_color_union::f, brw_context::gen, brw_context::render_target_format, and gl_colorbuffer_attrib::sRGBEnabled.
Referenced by do_single_blorp_clear().
brw_meta_convert_fast_clear_color()
union gl_color_union brw_meta_convert_fast_clear_color (const struct brw_context * brw, const struct intel_mipmap_tree * mt, const union gl_color_union * color)
Convert the given color to a bitfield suitable for ORing into DWORD 7 of SURFACE_STATE (DWORD 12-15 on SKL+).
References _mesa_format_has_color_component(), _mesa_get_format_base_format(), _mesa_get_srgb_format_linear(), _mesa_is_format_integer_color(), gl_color_union::f, gl_color_union::i, and gl_color_union::ui.
Referenced by do_single_blorp_clear().
brw_meta_mirror_clip_and_scissor()
bool brw_meta_mirror_clip_and_scissor (const struct gl_context * ctx, const struct gl_framebuffer * read_fb, const struct gl_framebuffer * draw_fb, GLfloat * srcX0, GLfloat * srcY0, GLfloat * srcX1, GLfloat * srcY1, GLfloat * dstX0, GLfloat * dstY0, GLfloat * dstX1, GLfloat * dstY1, bool * mirror_x, bool * mirror_y)
References gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, clip_coordinates(), compute_pixels_clipped(), fixup_mirroring(), gl_framebuffer::Height, and gl_framebuffer::Width.
Referenced by try_blorp_blit().
brw_meta_set_fast_clear_color()
bool brw_meta_set_fast_clear_color (struct brw_context * brw, union gl_color_union * curr_color, const union gl_color_union * new_color)
References gl_color_union::f, brw_context::gen, GEN7_SURFACE_CLEAR_COLOR_SHIFT, and gl_color_union::i.
Referenced by do_single_blorp_clear().
clip_coordinates()
static void clip_coordinates (bool mirror, float * src, float * dst0, float * dst1, float clipped_src0, float clipped_dst0, float clipped_dst1, float scale, bool isLeftOrBottom) inline static
Clips a coordinate (left, right, top or bottom) for the src or dst rect (whichever requires the largest clip) and adjusts the coordinate for the other rect accordingly.
Parameters
mirror true if mirroring is required
src the source rect coordinate (for example srcX0)
dst0 the dst rect coordinate (for example dstX0)
dst1 the opposite dst rect coordinate (for example dstX1)
clipped_src0 number of pixels to clip from the src coordinate
clipped_dst0 number of pixels to clip from the dst coordinate
clipped_dst1 number of pixels to clip from the opposite dst coordinate
scale the src vs dst scale involved for that coordinate
isLeftOrBottom true if we are clipping the left or bottom sides of the rect.
Referenced by brw_meta_mirror_clip_and_scissor().
compute_pixels_clipped()
static bool compute_pixels_clipped (float x0, float y0, float x1, float y1, float min_x, float min_y, float max_x, float max_y, float * clipped_x0, float * clipped_y0, float * clipped_x1, float * clipped_y1) inline static
Compute the number of pixels to clip for each side of a rect.
Parameters
x0 The rect's left coordinate
y0 The rect's bottom coordinate
x1 The rect's right coordinate
y1 The rect's top coordinate
min_x The clipping region's left coordinate
min_y The clipping region's bottom coordinate
max_x The clipping region's right coordinate
max_y The clipping region's top coordinate
clipped_x0 The number of pixels to clip from the left side
clipped_y0 The number of pixels to clip from the bottom side
clipped_x1 The number of pixels to clip from the right side
clipped_y1 The number of pixels to clip from the top side
Returns
false if we clip everything away, true otherwise
Referenced by brw_meta_mirror_clip_and_scissor().
fixup_mirroring()
static void fixup_mirroring (bool * mirror, float * coord0, float * coord1) inline static
Helper function for handling mirror image blits.
If coord0 > coord1, swap them and invert the "mirror" boolean.
Referenced by brw_meta_mirror_clip_and_scissor().