Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_ff_gs.h File Reference
#include "brw_context.h"
#include "compiler/brw_eu.h"
Data Structures
struct brw_ff_gs_prog_key
struct brw_ff_gs_compile
Macros
#define MAX_GS_VERTS (4)
Functions
void brw_ff_gs_quads (struct brw_ff_gs_compile *c, struct brw_ff_gs_prog_key *key)
void brw_ff_gs_quad_strip (struct brw_ff_gs_compile *c, struct brw_ff_gs_prog_key *key)
void brw_ff_gs_lines (struct brw_ff_gs_compile *c)
void gen6_sol_program (struct brw_ff_gs_compile *c, struct brw_ff_gs_prog_key *key, unsigned num_verts, bool check_edge_flag)
Generate the geometry shader program used on Gen6 to perform stream output (transform feedback).
void gen6_brw_upload_ff_gs_prog (struct brw_context *brw)
void brw_upload_ff_gs_prog (struct brw_context *brw)
void brw_codegen_ff_gs_prog (struct brw_context *brw, struct brw_ff_gs_prog_key *key)
Macro Definition Documentation
MAX_GS_VERTS
#define MAX_GS_VERTS (4)
Function Documentation
brw_codegen_ff_gs_prog()
void brw_codegen_ff_gs_prog (struct brw_context * brw, struct brw_ff_gs_prog_key * key)
References brw_context::base, BRW_CACHE_FF_GS_PROG, brw_ff_gs_lines(), brw_ff_gs_quad_strip(), brw_ff_gs_quads(), brw_upload_cache(), brw_context::cache, intel_screen::devinfo, brw_context::ff_gs, brw_ff_gs_compile::func, brw_context::gen, gen6_sol_program(), GLuint, brw_ff_gs_compile::key, brw_ff_gs_compile::nr_regs, brw_ff_gs_prog_key::primitive, brw_ff_gs_compile::prog_data, brw_stage_state::prog_data, brw_context::prog_data, brw_context::prog_offset, brw_context::screen, brw_context::vs, and brw_ff_gs_compile::vue_map.
Referenced by brw_upload_ff_gs_prog().
brw_ff_gs_lines()
void brw_ff_gs_lines (struct brw_ff_gs_compile * c)
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_overwrite_header_dw2(), brw_ff_gs_compile::func, brw_ff_gs_compile::reg, and brw_ff_gs_compile::vertex.
Referenced by brw_codegen_ff_gs_prog().
brw_ff_gs_quad_strip()
void brw_ff_gs_quad_strip (struct brw_ff_gs_compile * c, struct brw_ff_gs_prog_key * key)
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_overwrite_header_dw2(), brw_ff_gs_compile::func, brw_ff_gs_prog_key::pv_first, brw_ff_gs_compile::reg, and brw_ff_gs_compile::vertex.
Referenced by brw_codegen_ff_gs_prog().
brw_ff_gs_quads()
void brw_ff_gs_quads (struct brw_ff_gs_compile * c, struct brw_ff_gs_prog_key * key)
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_overwrite_header_dw2(), brw_ff_gs_compile::func, brw_ff_gs_prog_key::pv_first, brw_ff_gs_compile::reg, and brw_ff_gs_compile::vertex.
Referenced by brw_codegen_ff_gs_prog().
brw_upload_ff_gs_prog()
void brw_upload_ff_gs_prog (struct brw_context * brw)
References BRW_CACHE_FF_GS_PROG, brw_codegen_ff_gs_prog(), brw_ff_gs_populate_key(), brw_ff_gs_state_dirty(), BRW_NEW_FF_GS_PROG_DATA, brw_search_cache(), brw_context::cache, brw_context::ctx, brw_context::ff_gs, brw_ff_gs_prog_key::need_gs_prog, gl_context::NewDriverState, brw_context::prog_active, brw_context::prog_data, and brw_context::prog_offset.
Referenced by brw_upload_programs(), and gen6_brw_upload_ff_gs_prog().
gen6_brw_upload_ff_gs_prog()
void gen6_brw_upload_ff_gs_prog (struct brw_context * brw)
References brw_upload_ff_gs_prog().
Referenced by brw_upload_gs_prog().
gen6_sol_program()
void gen6_sol_program (struct brw_ff_gs_compile * c, struct brw_ff_gs_prog_key * key, unsigned num_verts, bool check_edge_flag)
Generate the geometry shader program used on Gen6 to perform stream output (transform feedback).
References brw_ff_gs_alloc_regs(), brw_ff_gs_emit_vue(), brw_ff_gs_ff_sync(), brw_ff_gs_initialize_header(), brw_ff_gs_offset_header_dw2(), brw_ff_gs_overwrite_header_dw2_from_r0(), BRW_GS_EDGE_INDICATOR_0, BRW_GS_EDGE_INDICATOR_1, brw_ff_gs_compile::destination_indices, brw_ff_gs_compile::func, brw_ff_gs_compile::header, brw_ff_gs_prog_key::num_transform_feedback_bindings, brw_ff_gs_compile::prog_data, brw_ff_gs_prog_key::pv_first, brw_ff_gs_compile::R0, brw_ff_gs_compile::reg, brw_ff_gs_compile::SVBI, brw_ff_gs_prog_data::svbi_postincrement_value, brw_ff_gs_compile::temp, brw_ff_gs_prog_key::transform_feedback_bindings, brw_ff_gs_prog_key::transform_feedback_swizzles, brw_ff_gs_compile::vertex, and brw_ff_gs_compile::vue_map.
Referenced by brw_codegen_ff_gs_prog().