Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_util.h File Reference
#include "brw_context.h"
#include "main/framebuffer.h"
Functions
GLuint brw_translate_blend_factor (GLenum factor)
GLuint brw_translate_blend_equation (GLenum mode)
GLenum brw_fix_xRGB_alpha (GLenum function)
Modify blend function to force destination alpha to 1.0.
static uint32_t brw_get_line_width (struct brw_context *brw)
Function Documentation
brw_fix_xRGB_alpha()
GLenum brw_fix_xRGB_alpha (GLenum function)
Modify blend function to force destination alpha to 1.0.
If function specifies a blend function that uses destination alpha, replace it with a function that hard-wires destination alpha to 1.0. This is used when rendering to xRGB targets.
Referenced by gen6_upload_blend_state(), gen8_upload_blend_state(), gen8_upload_ps_blend(), and upload_cc_unit().
brw_get_line_width()
static uint32_t brw_get_line_width (struct brw_context * brw) inline static
References _mesa_is_multisample_enabled(), gl_context::Const, brw_context::ctx, gl_context::Line, gl_constants::MaxLineWidth, gl_line_attrib::SmoothFlag, and gl_line_attrib::Width.
Referenced by upload_sf(), and upload_sf_state().
brw_translate_blend_equation()
GLuint brw_translate_blend_equation (GLenum mode)
References BRW_BLENDFUNCTION_ADD, BRW_BLENDFUNCTION_MAX, BRW_BLENDFUNCTION_MIN, BRW_BLENDFUNCTION_REVERSE_SUBTRACT, BRW_BLENDFUNCTION_SUBTRACT, and GLuint.
Referenced by gen6_upload_blend_state(), and upload_cc_unit().
brw_translate_blend_factor()
GLuint brw_translate_blend_factor (GLenum factor)
References BRW_BLENDFACTOR_CONST_ALPHA, BRW_BLENDFACTOR_CONST_COLOR, BRW_BLENDFACTOR_DST_ALPHA, BRW_BLENDFACTOR_DST_COLOR, BRW_BLENDFACTOR_INV_CONST_ALPHA, BRW_BLENDFACTOR_INV_CONST_COLOR, BRW_BLENDFACTOR_INV_DST_ALPHA, BRW_BLENDFACTOR_INV_DST_COLOR, BRW_BLENDFACTOR_INV_SRC1_ALPHA, BRW_BLENDFACTOR_INV_SRC1_COLOR, BRW_BLENDFACTOR_INV_SRC_ALPHA, BRW_BLENDFACTOR_INV_SRC_COLOR, BRW_BLENDFACTOR_ONE, BRW_BLENDFACTOR_SRC1_ALPHA, BRW_BLENDFACTOR_SRC1_COLOR, BRW_BLENDFACTOR_SRC_ALPHA, BRW_BLENDFACTOR_SRC_ALPHA_SATURATE, BRW_BLENDFACTOR_SRC_COLOR, BRW_BLENDFACTOR_ZERO, and GLuint.
Referenced by gen6_upload_blend_state(), and upload_cc_unit().