Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_sf_state.c File Reference
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/fbobject.h"
#include "main/viewport.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_sf.h"
Functions
static void upload_sf_vp (struct brw_context *brw)
static void upload_sf_unit (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_sf_vp
const struct brw_tracked_state brw_sf_unit
Function Documentation
upload_sf_unit()
static void upload_sf_unit (struct brw_context * brw) static
References gl_point_attrib::_Attenuated, gl_polygon_attrib::_FrontBit, brw_sf_unit_state::aa_enable, brw_sf_unit_state::aa_line_distance_mode, brw_context::batch, intel_batchbuffer::bo, BRW_CULLMODE_BACK, BRW_CULLMODE_BOTH, BRW_CULLMODE_FRONT, BRW_CULLMODE_NONE, BRW_FLOATING_POINT_NON_IEEE_754, BRW_FRONTWINDING_CCW, BRW_FRONTWINDING_CW, BRW_NEW_GEN4_UNIT_STATE, brw_program_reloc(), BRW_RASTRULE_LOWER_RIGHT, BRW_RASTRULE_UPPER_RIGHT, brw_state_batch(), gl_context::Const, brw_context::ctx, brw_sf_unit_state::cull_mode, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, brw_sf_unit_state::dest_org_hbias, brw_sf_unit_state::dest_org_vbias, thread3::dispatch_grf_start_reg, gl_context::DrawBuffer, gl_scissor_attrib::EnableFlags, thread1::floating_point_mode, brw_sf_unit_state::front_winding, brw_context::gen, thread0::grf_reg_count, thread0::kernel_start_pointer, gl_context::Light, gl_context::Line, brw_sf_unit_state::line_endcap_aa_region_width, brw_sf_unit_state::line_last_pixel_enable, brw_sf_unit_state::line_width, brw_sf_unit_state::linestrip_pv, brw_sf_unit_state::max_threads, gl_constants::MaxLineWidth, gl_point_attrib::MaxSize, gl_point_attrib::MinSize, gl_context::NewDriverState, brw_context::nr_sf_entries, brw_sf_unit_state::nr_urb_entries, gl_context::Point, brw_sf_unit_state::point_rast_rule, brw_sf_unit_state::point_size, gl_vertex_program_state::PointSizeEnabled, gl_point_attrib::PointSprite, gl_context::Polygon, brw_context::prog_data, brw_context::prog_offset, gl_light_attrib::ProvokingVertex, gl_context::Scissor, brw_sf_unit_state::scissor, brw_context::sf, brw_sf_unit_state::sf5, brw_sf_unit_state::sf6, brw_sf_unit_state::sf7, brw_sf_unit_state::sf_viewport_state_offset, brw_context::sfsize, gl_point_attrib::Size, gl_line_attrib::SmoothFlag, brw_sf_unit_state::sprite_point, brw_context::state_offset, brw_sf_unit_state::stats_enable, brw_sf_unit_state::thread0, brw_sf_unit_state::thread1, brw_sf_unit_state::thread3, brw_sf_unit_state::thread4, brw_ff_gs_prog_data::total_grf, brw_sf_unit_state::trifan_pv, brw_sf_unit_state::tristrip_pv, brw_context::urb, brw_sf_unit_state::urb_entry_allocation_size, thread3::urb_entry_read_length, thread3::urb_entry_read_offset, brw_ff_gs_prog_data::urb_read_length, brw_sf_unit_state::use_point_size_state, gl_context::VertexProgram, brw_sf_unit_state::viewport_transform, brw_context::vp_offset, and gl_line_attrib::Width.
upload_sf_vp()
static void upload_sf_vp (struct brw_context * brw) static
References gl_framebuffer::_HasAttachments, _mesa_get_viewport_xform(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, BRW_NEW_SF_VP, brw_state_batch(), brw_context::ctx, gl_context::DrawBuffer, gl_framebuffer::Height, brw_sf_viewport::m00, brw_sf_viewport::m11, brw_sf_viewport::m22, brw_sf_viewport::m30, brw_sf_viewport::m31, brw_sf_viewport::m32, gl_context::NewDriverState, brw_sf_viewport::scissor, brw_context::sf, brw_sf_viewport::viewport, brw_context::vp_offset, brw_sf_viewport::xmax, brw_sf_viewport::xmin, brw_sf_viewport::ymax, and brw_sf_viewport::ymin.
Variable Documentation
brw_sf_unit
const struct brw_tracked_state brw_sf_unit
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LIGHT |
               _NEW_LINE |
               _NEW_POINT |
               _NEW_POLYGON |
               _NEW_PROGRAM |
               _NEW_SCISSOR,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_PROGRAM_CACHE |
               BRW_NEW_SF_PROG_DATA |
               BRW_NEW_SF_VP |
               BRW_NEW_URB_FENCE,
   },
   .emit = upload_sf_unit,
}
brw_sf_vp
const struct brw_tracked_state brw_sf_vp
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_SCISSOR |
               _NEW_VIEWPORT,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP,
   },
   .emit = upload_sf_vp
}