Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_context.c File Reference
#include "compiler/nir/nir.h"
#include "main/api_exec.h"
#include "main/context.h"
#include "main/fbobject.h"
#include "main/extensions.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/points.h"
#include "main/version.h"
#include "main/vtxfmt.h"
#include "main/texobj.h"
#include "main/framebuffer.h"
#include "vbo/vbo_context.h"
#include "drivers/common/driverfuncs.h"
#include "drivers/common/meta.h"
#include "utils.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_blorp.h"
#include "brw_draw.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "intel_pixel.h"
#include "intel_image.h"
#include "intel_tex.h"
#include "intel_tex_obj.h"
#include "swrast_setup/swrast_setup.h"
#include "tnl/tnl.h"
#include "tnl/t_pipeline.h"
#include "util/ralloc.h"
#include "util/debug.h"
#include "isl/isl.h"
#include "pci_ids/i965_pci_ids.h"
Macros
#define CHIPSET(id, symbol, str) case id: chipset = str; break;
#define flushFront(screen) ((screen)->image.loader ? (screen)->image.loader->flushFrontBuffer : (screen)->dri2.loader->flushFrontBuffer)
Functions
static const char * get_bsw_model (const struct intel_screen *screen)
const char * brw_get_renderer_string (const struct intel_screen *screen)
static const GLubyte * intel_get_string (struct gl_context *ctx, GLenum name)
static void intel_viewport (struct gl_context *ctx)
static void intel_update_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
static bool intel_disable_rb_aux_buffer (struct brw_context *brw, const drm_intel_bo *bo)
static bool intel_texture_view_requires_resolve (struct brw_context *brw, struct intel_texture_object *intel_tex)
static void intel_update_state (struct gl_context *ctx, GLuint new_state)
static void intel_flush_front (struct gl_context *ctx)
static void intel_glFlush (struct gl_context *ctx)
static void intel_finish (struct gl_context *ctx)
static void brw_init_driver_functions (struct brw_context *brw, struct dd_function_table *functions)
static void brw_initialize_context_constants (struct brw_context *brw)
static void brw_initialize_cs_context_constants (struct brw_context *brw)
static void brw_process_driconf_options (struct brw_context *brw)
Process driconf (drirc) options, setting appropriate context flags.
GLboolean brwCreateContext (gl_api api, const struct gl_config *mesaVis, __DRIcontext *driContextPriv, unsigned major_version, unsigned minor_version, uint32_t flags, bool notify_reset, unsigned *dri_ctx_error, void *sharedContextPrivate)
void intelDestroyContext (__DRIcontext *driContextPriv)
GLboolean intelUnbindContext (__DRIcontext *driContextPriv)
static void intel_gles3_srgb_workaround (struct brw_context *brw, struct gl_framebuffer *fb)
Fixes up the context for GLES23 with our default-to-sRGB-capable behavior on window system framebuffers.
GLboolean intelMakeCurrent (__DRIcontext *driContextPriv, __DRIdrawable *driDrawPriv, __DRIdrawable *driReadPriv)
void intel_resolve_for_dri2_flush (struct brw_context *brw, __DRIdrawable *drawable)
static unsigned intel_bits_per_pixel (const struct intel_renderbuffer *rb)
static void intel_query_dri2_buffers (struct brw_context *brw, __DRIdrawable *drawable, __DRIbuffer **buffers, int *buffer_count)
Query DRI2 to obtain a DRIdrawable's buffers.
static void intel_process_dri2_buffer (struct brw_context *brw, __DRIdrawable *drawable, __DRIbuffer *buffer, struct intel_renderbuffer *rb, const char *buffer_name)
Assign a DRI buffer's DRM region to a renderbuffer.
static void intel_update_image_buffers (struct brw_context *brw, __DRIdrawable *drawable)
static void intel_update_dri2_buffers (struct brw_context *brw, __DRIdrawable *drawable)
void intel_update_renderbuffers (__DRIcontext *context, __DRIdrawable *drawable)
void intel_prepare_render (struct brw_context *brw)
intel_prepare_render should be called anywhere that curent read/drawbuffer state is required.
static void intel_update_image_buffer (struct brw_context *intel, __DRIdrawable *drawable, struct intel_renderbuffer *rb, __DRIimage *buffer, enum __DRIimageBufferMask buffer_type)
Query DRI image loader to obtain a DRIdrawable's buffers.
Variables
const char *const brw_vendor_string = "Intel Open Source Technology Center"
Macro Definition Documentation
CHIPSET
#define CHIPSET (id, symbol, str) case id: chipset = str; break;
flushFront
#define flushFront (screen) ((screen)->image.loader ? (screen)->image.loader->flushFrontBuffer : (screen)->dri2.loader->flushFrontBuffer)
Referenced by intel_flush_front().
Function Documentation
brw_get_renderer_string()
const char* brw_get_renderer_string (const struct intel_screen * screen)
References intel_screen::deviceID, get_bsw_model(), and void.
Referenced by brw_query_renderer_string(), and intel_get_string().
brw_init_driver_functions()
static void brw_init_driver_functions (struct brw_context * brw, struct dd_function_table * functions) static
References dd_function_table::BeginTransformFeedback, brw_begin_transform_feedback(), brw_delete_transform_feedback(), brw_end_transform_feedback(), brw_get_transform_feedback_vertex_count(), brw_init_common_queryobj_functions(), brw_init_compute_functions(), brw_init_conditional_render_functions(), brw_init_object_purgeable_functions(), brw_init_syncobj_functions(), brw_new_transform_feedback(), brw_pause_transform_feedback(), brw_query_internal_format(), brw_resume_transform_feedback(), brwInitFragProgFuncs(), can_do_mi_math_and_lrr(), dd_function_table::DeleteTransformFeedback, brw_context::driContext, dd_function_table::EndTransformFeedback, dd_function_table::Finish, dd_function_table::Flush, brw_context::gen, gen4_init_queryobj_functions(), gen6_get_sample_position(), gen6_init_queryobj_functions(), gen7_begin_transform_feedback(), gen7_end_transform_feedback(), gen7_pause_transform_feedback(), gen7_resume_transform_feedback(), dd_function_table::GetSamplePosition, dd_function_table::GetString, dd_function_table::GetTransformFeedbackVertexCount, hsw_begin_transform_feedback(), hsw_end_transform_feedback(), hsw_init_queryobj_functions(), hsw_pause_transform_feedback(), hsw_resume_transform_feedback(), intel_finish(), intel_get_string(), intel_glFlush(), intel_update_state(), intel_viewport(), intelInitBufferFuncs(), intelInitBufferObjectFuncs(), intelInitClearFuncs(), intelInitCopyImageFuncs(), intelInitPixelFuncs(), intelInitTextureCopyImageFuncs(), intelInitTextureFuncs(), intelInitTextureImageFuncs(), intelInitTextureSubImageFuncs(), brw_context::is_haswell, dd_function_table::NewTransformFeedback, dd_function_table::PauseTransformFeedback, dd_function_table::QueryInternalFormat, dd_function_table::ResumeTransformFeedback, brw_context::screen, dd_function_table::UpdateState, and dd_function_table::Viewport.
Referenced by brwCreateContext().
brw_initialize_context_constants()
static void brw_initialize_context_constants (struct brw_context * brw) static
References _mesa_extension_override_enables, gl_constants::AlwaysUseGetTransformFeedbackVertexCount, gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES2, gl_extensions::ARB_compute_shader, BRW_MAX_ABO, BRW_MAX_IMAGES, BRW_MAX_SOL_BUFFERS, BRW_MAX_SSBO, BRW_MAX_TEX_UNIT, BRW_MAX_UBO, can_do_mi_math_and_lrr(), intel_screen::compiler, gl_context::Const, brw_context::ctx, brw_context::gen, GEN6_NUM_VIEWPORTS, gen6_set_sample_maps(), gl_constants::GLSLTessLevelsAsInputs, gl_program_constants::HighInt, intel_supported_msaa_modes(), brw_context::is_g4x, brw_context::is_haswell, gl_constants::LineWidthGranularity, gl_constants::LowerTCSPatchVerticesIn, gl_constants::LowerTESPatchVerticesIn, gl_constants::Max, gl_constants::Max3DTextureLevels, MAX_ATOMIC_COUNTERS, MAX_IMAGE_UNITS, MAX_TEXTURE_LEVELS, MAX_VERTEX_STREAMS, gl_program_constants::MaxAluInstructions, gl_constants::MaxArrayTextureLayers, gl_program_constants::MaxAtomicBuffers, gl_program_constants::MaxAtomicCounters, gl_constants::MaxClipPlanes, gl_constants::MaxColorTextureSamples, gl_constants::MaxCombinedAtomicBuffers, gl_constants::MaxCombinedImageUniforms, gl_constants::MaxCombinedShaderOutputResources, gl_constants::MaxCombinedShaderStorageBlocks, gl_constants::MaxCombinedTextureImageUnits, gl_constants::MaxCombinedUniformBlocks, gl_program_constants::MaxCombinedUniformComponents, gl_constants::MaxComputeWorkGroupSize, gl_constants::MaxCubeTextureLevels, gl_constants::MaxDepthTextureSamples, gl_constants::MaxDrawBuffers, gl_constants::MaxDualSourceDrawBuffers, gl_program_constants::MaxEnvParams, gl_constants::MaxFramebufferHeight, gl_constants::MaxFramebufferLayers, gl_constants::MaxFramebufferSamples, gl_constants::MaxFramebufferWidth, gl_constants::MaxImageSamples, gl_program_constants::MaxImageUniforms, gl_constants::MaxImageUnits, gl_program_constants::MaxInputComponents, gl_constants::MaxIntegerSamples, gl_constants::MaxLineWidth, gl_constants::MaxLineWidthAA, gl_program_constants::MaxNativeAddressRegs, gl_program_constants::MaxNativeAluInstructions, gl_program_constants::MaxNativeAttribs, gl_program_constants::MaxNativeInstructions, gl_program_constants::MaxNativeParameters, gl_program_constants::MaxNativeTemps, gl_program_constants::MaxNativeTexIndirections, gl_program_constants::MaxNativeTexInstructions, gl_program_constants::MaxOutputComponents, gl_constants::MaxPointSize, gl_constants::MaxPointSizeAA, gl_constants::MaxProgramTextureGatherComponents, gl_constants::MaxProgramTextureGatherOffset, gl_constants::MaxRenderbufferSize, gl_constants::MaxSamples, gl_program_constants::MaxShaderStorageBlocks, gl_constants::MaxShaderStorageBufferBindings, gl_program_constants::MaxTexIndirections, gl_program_constants::MaxTexInstructions, gl_constants::MaxTextureBufferSize, gl_constants::MaxTextureCoordUnits, gl_program_constants::MaxTextureImageUnits, gl_constants::MaxTextureLevels, gl_constants::MaxTextureLodBias, gl_constants::MaxTextureMaxAnisotropy, gl_constants::MaxTextureMbytes, gl_constants::MaxTextureRectSize, gl_constants::MaxTextureUnits, gl_constants::MaxTransformFeedbackBuffers, gl_constants::MaxTransformFeedbackInterleavedComponents, gl_constants::MaxTransformFeedbackSeparateComponents, gl_program_constants::MaxUniformBlocks, gl_constants::MaxUniformBlockSize, gl_constants::MaxUniformBufferBindings, gl_program_constants::MaxUniformComponents, gl_constants::MaxVarying, gl_constants::MaxVertexStreams, gl_constants::MaxViewportHeight, gl_constants::MaxViewports, gl_constants::MaxViewportWidth, gl_constants::Min, gl_constants::MinLineWidth, gl_constants::MinLineWidthAA, gl_constants::MinPointSize, gl_constants::MinPointSizeAA, gl_constants::MinProgramTextureGatherOffset, gl_constants::NativeIntegers, gl_constants::NoPrimitiveBoundingBoxOutput, brw_context::optionCache, gl_constants::PointSizeGranularity, gl_constants::PrimitiveRestartForPatches, gl_constants::Program, gl_constants::QuadsFollowProvokingVertexConvention, gl_constants::QueryCounterBits, brw_context::screen, gl_constants::ShaderCompilerOptions, gl_constants::ShaderStorageBufferOffsetAlignment, gl_constants::StripTextureBorder, gl_constants::TextureBufferOffsetAlignment, gl_constants::Timestamp, gl_constants::UniformBooleanTrue, gl_constants::UniformBufferOffsetAlignment, gl_constants::VertexID_is_zero_based, gl_constants::ViewportBounds, and gl_constants::ViewportSubpixelBits.
Referenced by brwCreateContext().
brw_initialize_cs_context_constants()
static void brw_initialize_cs_context_constants (struct brw_context * brw) static
References gl_context::Const, brw_context::ctx, intel_screen::devinfo, intel_screen::eu_total, brw_context::is_cherryview, gl_constants::MaxComputeSharedMemorySize, gl_constants::MaxComputeWorkGroupInvocations, gl_constants::MaxComputeWorkGroupSize, brw_context::screen, and intel_screen::subslice_total.
Referenced by brwCreateContext().
brw_process_driconf_options()
static void brw_process_driconf_options (struct brw_context * brw) static
Process driconf (drirc) options, setting appropriate context flags.
intelInitExtensions still pokes at optionCache directly, in order to avoid advertising various extensions. No flags are set, so it makes sense to continue doing that there.
References gl_constants::AllowGLSLExtensionDirectiveMidShader, gl_constants::AllowHigherCompatVersion, brw_context::always_flush_batch, brw_context::always_flush_cache, brw_context::bufmgr, intel_screen::compiler, gl_context::Const, brw_context::ctx, brw_context::disable_throttling, gl_constants::DisableGLSLLineContinuations, DRI_CONF_BO_REUSE_ALL, DRI_CONF_BO_REUSE_DISABLED, brw_context::driContext, brw_context::dual_color_blend_by_location, gl_constants::ForceGLSLAbsSqrt, gl_constants::ForceGLSLExtensionsWarn, gl_constants::ForceGLSLVersion, brw_context::gen, gl_constants::GLSLZeroInit, brw_context::has_hiz, brw_context::has_separate_stencil, intel_screen::optionCache, brw_context::optionCache, brw_context::precompile, and brw_context::screen.
Referenced by brwCreateContext().
brwCreateContext()
GLboolean brwCreateContext (gl_api api, const struct gl_config * mesaVis, __DRIcontext * driContextPriv, unsigned major_version, unsigned minor_version, uint32_t flags, bool notify_reset, unsigned * dri_ctx_error, void * sharedContextPrivate)
References gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _mesa_compute_version(), _mesa_init_point(), _mesa_initialize_context(), _mesa_initialize_dispatch_tables(), _mesa_initialize_vbo_vtxfmt(), _swrast_allow_pixel_fog(), _swrast_allow_vertex_fog(), _swrast_CreateContext(), _swsetup_CreateContext(), _tnl_CreateContext(), _tnl_run_pipeline(), _vbo_CreateContext(), API_OPENGL_CORE, API_OPENGLES2, brw_context::base, brw_context::batch, brw_blorp_init(), brw_draw_init(), brw_emit_depth_stencil_hiz(), brw_get_graphics_reset_status(), brw_init_driver_functions(), brw_init_performance_queries(), brw_init_pipe_control(), brw_init_shader_time(), brw_init_state(), brw_init_surface_formats(), brw_initialize_context_constants(), brw_initialize_cs_context_constants(), BRW_PREDICATE_STATE_RENDER, brw_process_driconf_options(), intel_screen::bufmgr, brw_context::bufmgr, brw_context::clip, gl_context::Const, gl_constants::ContextFlags, brw_context::ctx, intel_screen::devinfo, brw_context::driContext, brw_context::emit_depth_stencil_hiz, brw_context::enable_cut_index, brw_context::enabled, gl_context::Extensions, gl_context::FragmentProgram, brw_context::gen, gen4_init_vtable_surface_functions(), gen6_emit_depth_stencil_hiz(), gen6_init_vtable_surface_functions(), gen7_emit_depth_stencil_hiz(), gen7_init_vtable_surface_functions(), gen8_emit_depth_stencil_hiz(), gen8_init_vtable_surface_functions(), dd_function_table::GetGraphicsResetStatus, brw_context::gs, brw_context::gs_present, brw_context::gt, brw_context::has_compr4, intel_screen::has_context_reset_notification, brw_context::has_hiz, brw_context::has_llc, brw_context::has_negative_rhw_bug, brw_context::has_pln, brw_context::has_separate_stencil, brw_context::has_surface_tile_offset, brw_context::has_swizzling, brw_context::hw_ctx, intel_screen::hw_has_swizzling, brw_context::in_progress, intel_batchbuffer_init(), intel_fbo_init(), gl_extensions::INTEL_performance_query, intelDestroyContext(), intelInitExtensions(), brw_context::is_baytrail, brw_context::is_broxton, brw_context::is_cherryview, brw_context::is_g4x, brw_context::is_haswell, brw_context::isl_dev, intel_screen::max_gtt_map_object_size, brw_context::max_gtt_map_object_size, brw_context::must_use_separate_stencil, brw_context::needs_unlit_centroid_workaround, brw_context::perf_debug, brw_context::predicate, brw_context::prim_restart, gl_constants::ResetStrategy, gl_constants::RobustAccess, brw_context::screen, brw_context::sf, brw_context::size, brw_stage_state::stage, brw_context::state, gl_context::swrast_context, brw_context::tcs, brw_context::tes, TNL_CONTEXT, brw_context::urb, vbo_always_unmap_buffers(), vbo_use_buffer_objects(), gl_context::VertexProgram, brw_context::viewport_count, brw_context::viewport_transform_enable, brw_context::vs, brw_context::vtbl, and brw_context::wm.
get_bsw_model()
static const char* get_bsw_model (const struct intel_screen * screen) static
References intel_screen::eu_total.
Referenced by brw_get_renderer_string().
intel_bits_per_pixel()
static unsigned intel_bits_per_pixel (const struct intel_renderbuffer * rb) static
References _mesa_get_format_bytes(), intel_process_dri2_buffer(), intel_query_dri2_buffers(), intel_rb_format(), and intel_update_image_buffers().
Referenced by intel_query_dri2_buffers().
intel_disable_rb_aux_buffer()
static bool intel_disable_rb_aux_buffer (struct brw_context * brw, const drm_intel_bo * bo) static
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, brw_context::ctx, brw_context::draw_aux_buffer_disabled, gl_context::DrawBuffer, intel_renderbuffer(), and intel_renderbuffer::mt.
Referenced by intel_texture_view_requires_resolve(), and intel_update_state().
intel_finish()
static void intel_finish (struct gl_context * ctx) static
References brw_context::batch, brw_context(), intel_glFlush(), and intel_batchbuffer::last_bo.
Referenced by brw_init_driver_functions().
intel_flush_front()
static void intel_flush_front (struct gl_context * ctx) static
References brw_context(), gl_context::DrawBuffer, brw_context::driContext, intel_screen::driScrnPriv, flushFront, brw_context::front_buffer_dirty, intel_batchbuffer_flush, intel_resolve_for_dri2_flush(), and brw_context::screen.
Referenced by intel_glFlush(), and intel_query_dri2_buffers().
intel_get_string()
static const GLubyte* intel_get_string (struct gl_context * ctx, GLenum name) static
References brw_context(), brw_get_renderer_string(), brw_vendor_string, and brw_context::screen.
Referenced by brw_init_driver_functions().
intel_gles3_srgb_workaround()
static void intel_gles3_srgb_workaround (struct brw_context * brw, struct gl_framebuffer * fb) static
Fixes up the context for GLES23 with our default-to-sRGB-capable behavior on window system framebuffers.
Desktop GL is fairly reasonable in its handling of sRGB: You can ask if your renderbuffer can do sRGB encode, and you can flip a switch that does sRGB encode if the renderbuffer can handle it. You can ask specifically for a visual where you're guaranteed to be capable, but it turns out that everyone just makes all their ARGB8888 visuals capable and doesn't offer incapable ones, because there's no difference between the two in resources used. Applications thus get built that accidentally rely on the default visual choice being sRGB, so we make ours sRGB capable. Everything sounds great...
But for GLES2/3, they decided that it was silly to not turn on sRGB encode for sRGB renderbuffers you made with the GL_EXT_texture_sRGB equivalent. So they removed the enable knob and made it "if the renderbuffer is sRGB capable, do sRGB encode". Then, for your window system renderbuffers, you can ask for sRGB visuals and get sRGB encode, or not ask for sRGB visuals and get no sRGB encode (assuming that both kinds of visual are available). Thus our choice to support sRGB by default on our visuals for desktop would result in broken rendering of GLES apps that aren't expecting sRGB encode.
Unfortunately, renderbuffer setup happens before a context is created. So in intel_screen.c we always set up sRGB, and here, if you're a GLES2/3 context (without an sRGB visual, though we don't have sRGB visuals exposed yet), we go turn that back off before anyone finds out.
References _mesa_get_srgb_format_linear(), gl_framebuffer::Attachment, BUFFER_COUNT, brw_context::ctx, gl_renderbuffer::Format, gl_renderbuffer_attachment::Renderbuffer, gl_config::sRGBCapable, and gl_framebuffer::Visual.
Referenced by intelMakeCurrent().
intel_glFlush()
static void intel_glFlush (struct gl_context * ctx) static
References brw_context(), intel_batchbuffer_flush, intel_flush_front(), and brw_context::need_flush_throttle.
Referenced by brw_init_driver_functions(), and intel_finish().
intel_prepare_render()
void intel_prepare_render (struct brw_context * brw)
intel_prepare_render should be called anywhere that curent read/drawbuffer state is required.
References _mesa_is_front_buffer_drawing(), brw_context::ctx, gl_context::DrawBuffer, brw_context::driContext, brw_context::front_buffer_dirty, and intel_update_renderbuffers().
Referenced by brw_blorp_copytexsubimage(), brw_clear(), brw_try_draw_prims(), do_blit_bitmap(), do_blit_copypixels(), do_blit_drawpixels(), intel_blit_framebuffer_with_blitter(), intel_copy_texsubimage(), intel_map_renderbuffer(), intelDrawBuffer(), intelMakeCurrent(), intelReadBuffer(), intelReadPixels(), and try_blorp_blit().
intel_process_dri2_buffer()
static void intel_process_dri2_buffer (struct brw_context * brw, __DRIdrawable * drawable, __DRIbuffer * buffer, struct intel_renderbuffer * rb, const char * buffer_name) static
Assign a DRI buffer's DRM region to a renderbuffer.
This is called from intel_update_renderbuffers().
Note:
DRI buffers whose attachment point is DRI2BufferStencil or DRI2BufferDepthStencil are handled as special cases.
Parameters
buffer_name is a human readable name, such as "dri2 front buffer", that is passed to drm_intel_bo_gem_create_from_name().
See also
intel_update_renderbuffers()
References _mesa_is_front_buffer_drawing(), swrast_renderbuffer::Base, intel_renderbuffer::Base, brw_context::bufmgr, intel_renderbuffer_upsample(), intel_update_winsys_renderbuffer_miptree(), intel_renderbuffer::mt, gl_renderbuffer::NumSamples, and intel_renderbuffer::singlesample_mt.
Referenced by intel_bits_per_pixel(), and intel_update_dri2_buffers().
intel_query_dri2_buffers()
static void intel_query_dri2_buffers (struct brw_context * brw, __DRIdrawable * drawable, __DRIbuffer ** buffers, int * buffer_count) static
Query DRI2 to obtain a DRIdrawable's buffers.
To determine which DRI buffers to request, examine the renderbuffers attached to the drawable's framebuffer. Then request the buffers with DRI2GetBuffers() or DRI2GetBuffersWithFormat().
This is called from intel_update_renderbuffers().
Parameters
drawable Drawable whose buffers are queried.
buffers [out] List of buffers returned by DRI2 query.
buffer_count [out] Number of buffers returned.
See also
intel_update_renderbuffers()
DRI2GetBuffers()
DRI2GetBuffersWithFormat()
References _mesa_is_front_buffer_drawing(), _mesa_is_front_buffer_reading(), BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, brw_context::ctx, intel_screen::driScrnPriv, brw_context::front_buffer_dirty, intel_batchbuffer_flush, intel_bits_per_pixel(), intel_flush_front(), intel_get_renderbuffer(), and brw_context::screen.
Referenced by intel_bits_per_pixel(), and intel_update_dri2_buffers().
intel_resolve_for_dri2_flush()
void intel_resolve_for_dri2_flush (struct brw_context * brw, __DRIdrawable * drawable)
References BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, brw_context::gen, intel_get_renderbuffer(), intel_miptree_resolve_color(), intel_renderbuffer_downsample(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by intel_dri2_flush_with_flags(), and intel_flush_front().
intel_texture_view_requires_resolve()
static bool intel_texture_view_requires_resolve (struct brw_context * brw, struct intel_texture_object * intel_tex) static
References intel_texture_object::_Format, _mesa_get_format_name(), brw_isl_format_for_mesa_format(), intel_screen::devinfo, brw_context::gen, intel_disable_rb_aux_buffer(), intel_miptree_is_lossless_compressed(), intel_texture_object::mt, and brw_context::screen.
Referenced by intel_update_state().
intel_update_dri2_buffers()
static void intel_update_dri2_buffers (struct brw_context * brw, __DRIdrawable * drawable) static
References BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, intel_get_renderbuffer(), intel_process_dri2_buffer(), and intel_query_dri2_buffers().
Referenced by intel_update_renderbuffers().
intel_update_framebuffer()
static void intel_update_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb) static
References gl_framebuffer::_NumSamples, brw_context(), gl_framebuffer::DefaultGeometry, intel_quantize_num_samples(), gl_framebuffer::NumSamples, and brw_context::screen.
Referenced by intel_update_state().
intel_update_image_buffer()
static void intel_update_image_buffer (struct brw_context * intel, __DRIdrawable * drawable, struct intel_renderbuffer * rb, __DRIimage * buffer, enum __DRIimageBufferMask buffer_type) static
Query DRI image loader to obtain a DRIdrawable's buffers.
To determine which DRI buffers to request, examine the renderbuffers attached to the drawable's framebuffer. Then request the buffers from the image loader
This is called from intel_update_renderbuffers().
Parameters
drawable Drawable whose buffers are queried.
buffers [out] List of buffers returned by DRI2 query.
buffer_count [out] Number of buffers returned.
See also
intel_update_renderbuffers()
References _mesa_is_front_buffer_drawing(), swrast_renderbuffer::Base, intel_renderbuffer::Base, intel_renderbuffer_upsample(), intel_update_winsys_renderbuffer_miptree(), intel_renderbuffer::mt, gl_renderbuffer::NumSamples, and intel_renderbuffer::singlesample_mt.
Referenced by intel_update_image_buffers().
intel_update_image_buffers()
static void intel_update_image_buffers (struct brw_context * brw, __DRIdrawable * drawable) static
References _mesa_is_front_buffer_drawing(), _mesa_is_front_buffer_reading(), BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, intel_screen::driScrnPriv, intel_get_renderbuffer(), intel_rb_format(), intel_update_image_buffer(), ret(), and brw_context::screen.
Referenced by intel_bits_per_pixel(), and intel_update_renderbuffers().
intel_update_renderbuffers()
void intel_update_renderbuffers (__DRIcontext * context, __DRIdrawable * drawable)
References brw_context::ctx, intel_screen::driScrnPriv, intel_update_dri2_buffers(), intel_update_image_buffers(), and brw_context::screen.
Referenced by intel_prepare_render(), and intelSetTexBuffer2().
intel_update_state()
static void intel_update_state (struct gl_context * ctx, GLuint new_state) static
References gl_framebuffer::_ColorDrawBuffers, gl_texture_unit::_Current, gl_fragment_program_state::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_get_srgb_format_linear(), _mesa_lock_context_textures(), _mesa_unlock_context_textures(), _NEW_BUFFERS, gl_framebuffer::_NumColorDrawBuffers, gl_context::_Shader, _swrast_InvalidateState(), _vbo_InvalidateState(), intel_texture_object::base, brw_context::bo, brw_context(), brw_render_cache_set_check_flush(), BUFFER_DEPTH, gl_context::Color, gl_pipeline_object::CurrentProgram, brw_context::draw_aux_buffer_disabled, gl_context::DrawBuffer, gl_context::Extensions, gl_context::FragmentProgram, brw_context::gen, gl_context::ImageUnits, gl_program::info, intel_disable_rb_aux_buffer(), intel_get_renderbuffer(), intel_miptree_all_slices_resolve_color(), intel_miptree_all_slices_resolve_depth(), intel_miptree_all_slices_resolve_hiz(), intel_miptree_is_lossless_compressed(), intel_miptree_resolve_color(), intel_miptree_sample_with_hiz(), intel_renderbuffer(), intel_renderbuffer_resolve_hiz(), intel_texture_object(), intel_texture_view_requires_resolve(), intel_update_framebuffer(), intel_update_r8stencil(), intel_renderbuffer::layer_count, MESA_FORMAT_S_UINT8, gl_extensions::MESA_shader_framebuffer_fetch, intel_texture_object::mt, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, brw_context::NewGLState, gl_context::ReadBuffer, gl_program::sh, gl_colorbuffer_attrib::sRGBEnabled, gl_texture_object::StencilSampling, gl_context::swrast_context, gl_image_unit::TexObj, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_init_driver_functions().
intel_viewport()
static void intel_viewport (struct gl_context * ctx) static
References brw_context(), gl_context::DrawBuffer, and brw_context::driContext.
Referenced by brw_init_driver_functions().
intelDestroyContext()
void intelDestroyContext (__DRIcontext * driContextPriv)
References _mesa_free_context_data(), _swrast_DestroyContext(), _swsetup_DestroyContext(), _tnl_DestroyContext(), _vbo_DestroyContext(), brw_context::base, brw_context::batch, brw_context::blorp, brw_collect_and_report_shader_time(), brw_destroy_shader_time(), brw_destroy_state(), brw_draw_destroy(), brw_fini_pipe_control(), brw_context::ctx, brw_context::curbe, brw_context::curbe_bo, brw_context::gen, brw_context::gs, brw_context::hw_ctx, intel_batchbuffer_free(), brw_context::optionCache, brw_context::report_time, brw_stage_state::scratch_bo, brw_context::shader_time, gl_context::swrast_context, brw_context::tcs, brw_context::tes, brw_context::throttle_batch, brw_context::vs, and brw_context::wm.
Referenced by brwCreateContext().
intelMakeCurrent()
GLboolean intelMakeCurrent (__DRIcontext * driContextPriv, __DRIdrawable * driDrawPriv, __DRIdrawable * driReadPriv)
References _mesa_flush(), _mesa_get_incomplete_framebuffer(), _mesa_make_current(), brw_context(), brw_context::ctx, if(), intel_gles3_srgb_workaround(), intel_prepare_render(), and gl_context::ViewportInitialized.
intelUnbindContext()
GLboolean intelUnbindContext (__DRIcontext * driContextPriv)
References _mesa_make_current().
Variable Documentation
brw_vendor_string
const char* const brw_vendor_string = "Intel Open Source Technology Center"
Referenced by brw_query_renderer_string(), and intel_get_string().