Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_nir_uniforms.cpp File Reference
#include "compiler/brw_nir.h"
#include "compiler/glsl/ir_uniform.h"
Functions
static void brw_nir_setup_glsl_builtin_uniform (nir_variable *var, const struct gl_program *prog, struct brw_stage_prog_data *stage_prog_data, bool is_scalar)
static void setup_vec4_uniform_value (const gl_constant_value **params, const gl_constant_value *values, unsigned n)
static void brw_setup_image_uniform_values (gl_shader_stage stage, struct brw_stage_prog_data *stage_prog_data, unsigned param_start_index, const gl_uniform_storage *storage)
static void brw_nir_setup_glsl_uniform (gl_shader_stage stage, nir_variable *var, const struct gl_program *prog, struct brw_stage_prog_data *stage_prog_data, bool is_scalar)
void brw_nir_setup_glsl_uniforms (nir_shader *shader, const struct gl_program *prog, struct brw_stage_prog_data *stage_prog_data, bool is_scalar)
void brw_nir_setup_arb_uniforms (nir_shader *shader, struct gl_program *prog, struct brw_stage_prog_data *stage_prog_data)
Function Documentation
brw_nir_setup_arb_uniforms()
void brw_nir_setup_arb_uniforms (nir_shader * shader, struct gl_program * prog, struct brw_stage_prog_data * stage_prog_data)
References gl_program::Parameters.
Referenced by brw_codegen_vs_prog(), and brw_codegen_wm_prog().
brw_nir_setup_glsl_builtin_uniform()
static void brw_nir_setup_glsl_builtin_uniform (nir_variable * var, const struct gl_program * prog, struct brw_stage_prog_data * stage_prog_data, bool is_scalar) static
References gl_program::Parameters, and swizzle().
Referenced by brw_nir_setup_glsl_uniforms().
brw_nir_setup_glsl_uniform()
static void brw_nir_setup_glsl_uniform (gl_shader_stage stage, nir_variable * var, const struct gl_program * prog, struct brw_stage_prog_data * stage_prog_data, bool is_scalar) static
References gl_uniform_storage::array_elements, brw_setup_image_uniform_values(), gl_uniform_storage::builtin, gl_uniform_storage::name, gl_program::sh, gl_uniform_storage::storage, and gl_uniform_storage::type.
Referenced by brw_nir_setup_glsl_uniforms().
brw_nir_setup_glsl_uniforms()
void brw_nir_setup_glsl_uniforms (nir_shader * shader, const struct gl_program * prog, struct brw_stage_prog_data * stage_prog_data, bool is_scalar)
References brw_nir_setup_glsl_builtin_uniform(), and brw_nir_setup_glsl_uniform().
Referenced by brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), and brw_codegen_wm_prog().
brw_setup_image_uniform_values()
static void brw_setup_image_uniform_values (gl_shader_stage stage, struct brw_stage_prog_data * stage_prog_data, unsigned param_start_index, const gl_uniform_storage * storage) static
References gl_uniform_storage::array_elements, gl_opaque_uniform_index::index, gl_uniform_storage::opaque, and setup_vec4_uniform_value().
Referenced by brw_nir_setup_glsl_uniform().
setup_vec4_uniform_value()
static void setup_vec4_uniform_value (const gl_constant_value ** params, const gl_constant_value * values, unsigned n) static
Referenced by brw_setup_image_uniform_values().