Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_performance_query.c File Reference
Implementation of the GL_INTEL_performance_query extension.
#include <limits.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <xf86drm.h>
#include <i915_drm.h>
#include "main/hash.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/performance_query.h"
#include "util/bitset.h"
#include "util/ralloc.h"
#include "util/hash_table.h"
#include "util/list.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_performance_query.h"
#include "brw_oa_hsw.h"
#include "intel_batchbuffer.h"
Data Structures
struct brw_oa_sample_buf
Periodic OA samples are read() into these buffer structures via the i915 perf kernel interface and appended to the brw->perfquery.sample_buffers linked list.
struct brw_perf_query_object
i965 representation of a performance query object.
Macros
#define FILE_DEBUG_FLAG DEBUG_PERFMON
#define MAX_OA_REPORT_COUNTERS 62
#define I915_PERF_OA_SAMPLE_SIZE
#define STATS_BO_SIZE 4096
#define STATS_BO_END_OFFSET_BYTES (STATS_BO_SIZE / 2)
#define MAX_STAT_COUNTERS (STATS_BO_END_OFFSET_BYTES / 8)
#define MI_RPC_BO_SIZE 4096
#define MI_RPC_BO_END_OFFSET_BYTES (MI_RPC_BO_SIZE / 2)
Functions
static struct brw_perf_query_object * brw_perf_query (struct gl_perf_query_object *o)
Downcasting convenience macro.
static bool brw_is_perf_query_ready (struct gl_context *ctx, struct gl_perf_query_object *o)
static void dump_perf_query_callback (GLuint id, void *query_void, void *brw_void)
static void dump_perf_queries (struct brw_context *brw)
static struct brw_oa_sample_buf * get_free_sample_buf (struct brw_context *brw)
static void reap_old_sample_buffers (struct brw_context *brw)
static void free_sample_bufs (struct brw_context *brw)
static void brw_get_perf_query_info (struct gl_context *ctx, unsigned query_index, const char **name, GLuint *data_size, GLuint *n_counters, GLuint *n_active)
Driver hook for glGetPerfQueryInfoINTEL().
static void brw_get_perf_counter_info (struct gl_context *ctx, unsigned query_index, unsigned counter_index, const char **name, const char **desc, GLuint *offset, GLuint *data_size, GLuint *type_enum, GLuint *data_type_enum, GLuint64 *raw_max)
Driver hook for glGetPerfCounterInfoINTEL().
static void snapshot_statistics_registers (struct brw_context *brw, struct brw_perf_query_object *obj, uint32_t offset_in_bytes)
Emit MI_STORE_REGISTER_MEM commands to capture all of the pipeline statistics for the performance query object.
static void emit_mi_report_perf_count (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset_in_bytes, uint32_t report_id)
Emit an MI_REPORT_PERF_COUNT command packet.
static void add_to_unaccumulated_query_list (struct brw_context *brw, struct brw_perf_query_object *obj)
Add a query to the global list of "unaccumulated queries.".
static void drop_from_unaccumulated_query_list (struct brw_context *brw, struct brw_perf_query_object *obj)
Remove a query from the global list of unaccumulated queries once after successfully accumulating the OA reports associated with the query in accumulate_oa_reports() or when discarding unwanted query results.
static uint64_t timebase_scale (struct brw_context *brw, uint32_t u32_time_delta)
static void accumulate_uint32 (const uint32_t *report0, const uint32_t *report1, uint64_t *accumulator)
static void add_deltas (struct brw_context *brw, struct brw_perf_query_object *obj, const uint32_t *start, const uint32_t *end)
Given pointers to starting and ending OA snapshots, add the deltas for each counter to the results.
static bool inc_n_oa_users (struct brw_context *brw)
static void dec_n_oa_users (struct brw_context *brw)
static void discard_all_queries (struct brw_context *brw)
static bool read_oa_samples (struct brw_context *brw)
static void accumulate_oa_reports (struct brw_context *brw, struct brw_perf_query_object *obj)
Accumulate raw OA counter values based on deltas between pairs of OA reports.
static bool open_i915_perf_oa_stream (struct brw_context *brw, int metrics_set_id, int report_format, int period_exponent, int drm_fd, uint32_t ctx_id)
static void close_perf (struct brw_context *brw)
static bool brw_begin_perf_query (struct gl_context *ctx, struct gl_perf_query_object *o)
Driver hook for glBeginPerfQueryINTEL().
static void brw_end_perf_query (struct gl_context *ctx, struct gl_perf_query_object *o)
Driver hook for glEndPerfQueryINTEL().
static void brw_wait_perf_query (struct gl_context *ctx, struct gl_perf_query_object *o)
static int get_oa_counter_data (struct brw_context *brw, struct brw_perf_query_object *obj, size_t data_size, uint8_t *data)
static int get_pipeline_stats_data (struct brw_context *brw, struct brw_perf_query_object *obj, size_t data_size, uint8_t *data)
static void brw_get_perf_query_data (struct gl_context *ctx, struct gl_perf_query_object *o, GLsizei data_size, GLuint *data, GLuint *bytes_written)
Driver hook for glGetPerfQueryDataINTEL().
static struct gl_perf_query_object * brw_new_perf_query_object (struct gl_context *ctx, unsigned query_index)
static void brw_delete_perf_query (struct gl_context *ctx, struct gl_perf_query_object *o)
Driver hook for glDeletePerfQueryINTEL().
static struct brw_perf_query_info * append_query_info (struct brw_context *brw)
static void add_stat_reg (struct brw_perf_query_info *query, uint32_t reg, uint32_t numerator, uint32_t denominator, const char *name, const char *description)
static void add_basic_stat_reg (struct brw_perf_query_info *query, uint32_t reg, const char *name)
static void init_pipeline_statistic_query_registers (struct brw_context *brw)
static bool read_file_uint64 (const char *file, uint64_t *val)
static void enumerate_sysfs_metrics (struct brw_context *brw, const char *sysfs_dev_dir)
static bool read_sysfs_drm_device_file_uint64 (struct brw_context *brw, const char *sysfs_dev_dir, const char *file, uint64_t *value)
static bool init_oa_sys_vars (struct brw_context *brw, const char *sysfs_dev_dir)
static bool get_sysfs_dev_dir (struct brw_context *brw, char *path_buf, int path_buf_len)
static unsigned brw_init_perf_query_info (struct gl_context *ctx)
void brw_init_performance_queries (struct brw_context *brw)
Detailed Description
Implementation of the GL_INTEL_performance_query extension.
Currently there are two possible counter sources exposed here:
On Gen6+ hardware we have numerous 64bit Pipeline Statistics Registers that we can snapshot at the beginning and end of a query.
On Gen7.5+ we have Observability Architecture counters which are covered in separate document from the rest of the PRMs. It is available at: https://01.org/linuxgraphics/documentation/driver-documentation-prms => 2013 Intel Core Processor Family => Observability Performance Counters (This one volume covers Sandybridge, Ivybridge, Baytrail, and Haswell, though notably we currently only support OA counters for Haswell+)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PERFMON
I915_PERF_OA_SAMPLE_SIZE
#define I915_PERF_OA_SAMPLE_SIZE
Value:
(8 +   /* drm_i915_perf_record_header */ \
                                  256)  /* OA counter report */
MAX_OA_REPORT_COUNTERS
#define MAX_OA_REPORT_COUNTERS 62
MAX_STAT_COUNTERS
#define MAX_STAT_COUNTERS (STATS_BO_END_OFFSET_BYTES / 8)
Referenced by add_stat_reg(), and init_pipeline_statistic_query_registers().
MI_RPC_BO_END_OFFSET_BYTES
#define MI_RPC_BO_END_OFFSET_BYTES (MI_RPC_BO_SIZE / 2)
Referenced by accumulate_oa_reports(), and brw_end_perf_query().
MI_RPC_BO_SIZE
#define MI_RPC_BO_SIZE 4096
Referenced by brw_begin_perf_query().
STATS_BO_END_OFFSET_BYTES
#define STATS_BO_END_OFFSET_BYTES (STATS_BO_SIZE / 2)
Referenced by brw_end_perf_query(), and get_pipeline_stats_data().
STATS_BO_SIZE
#define STATS_BO_SIZE 4096
Referenced by brw_begin_perf_query().
Function Documentation
accumulate_oa_reports()
static void accumulate_oa_reports (struct brw_context * brw, struct brw_perf_query_object * obj) static
Accumulate raw OA counter values based on deltas between pairs of OA reports.
Accumulation starts from the first report captured via MI_REPORT_PERF_COUNT (MI_RPC) by brw_begin_perf_query() until the last MI_RPC report requested by brw_end_perf_query(). Between these two reports there may also some number of periodically sampled OA reports collected via the i915 perf interface - depending on the duration of the query.
These periodic snapshots help to ensure we handle counter overflow correctly by being frequent enough to ensure we don't miss multiple overflows of a counter between snapshots.
References add_deltas(), brw_perf_query_object::base, brw_oa_sample_buf::buf, DBG, dec_n_oa_users(), discard_all_queries(), drop_from_unaccumulated_query_list(), foreach_list_typed_from, gl_perf_query_object::Id, brw_oa_sample_buf::len, brw_oa_sample_buf::link, MI_RPC_BO_END_OFFSET_BYTES, o, brw_perf_query_object::oa, brw_context::perfquery, read_oa_samples(), gl_perf_query_object::Ready, brw_context::sample_buffers, and timebase_scale().
Referenced by get_oa_counter_data().
accumulate_uint32()
static void accumulate_uint32 (const uint32_t * report0, const uint32_t * report1, uint64_t * accumulator) static
Referenced by add_deltas().
add_basic_stat_reg()
static void add_basic_stat_reg (struct brw_perf_query_info * query, uint32_t reg, const char * name) static
References add_stat_reg().
Referenced by init_pipeline_statistic_query_registers().
add_deltas()
static void add_deltas (struct brw_context * brw, struct brw_perf_query_object * obj, const uint32_t * start, const uint32_t * end) static
Given pointers to starting and ending OA snapshots, add the deltas for each counter to the results.
References accumulate_uint32(), brw_perf_query_object::oa, brw_perf_query_info::oa_format, and brw_perf_query_object::query.
Referenced by accumulate_oa_reports().
add_stat_reg()
static void add_stat_reg (struct brw_perf_query_info * query, uint32_t reg, uint32_t numerator, uint32_t denominator, const char * name, const char * description) static
References brw_perf_query_info::counters, brw_perf_query_counter::data_type, brw_pipeline_stat::denominator, brw_perf_query_counter::desc, MAX_STAT_COUNTERS, brw_perf_query_info::n_counters, brw_perf_query_counter::name, brw_pipeline_stat::numerator, brw_perf_query_counter::offset, brw_perf_query_counter::pipeline_stat, brw_pipeline_stat::reg, brw_perf_query_counter::size, and brw_perf_query_counter::type.
Referenced by add_basic_stat_reg(), and init_pipeline_statistic_query_registers().
add_to_unaccumulated_query_list()
static void add_to_unaccumulated_query_list (struct brw_context * brw, struct brw_perf_query_object * obj) static
Add a query to the global list of "unaccumulated queries.".
Queries are tracked here until all the associated OA reports have been accumulated via accumulate_oa_reports() after the end MI_REPORT_PERF_COUNT has landed in query->oa.bo.
References brw_context::perfquery, brw_context::unaccumulated, brw_context::unaccumulated_array_size, and brw_context::unaccumulated_elements.
Referenced by brw_begin_perf_query().
append_query_info()
static struct brw_perf_query_info* append_query_info (struct brw_context * brw) static
References brw_context::n_queries, brw_context::perfquery, and brw_context::queries.
Referenced by enumerate_sysfs_metrics(), and init_pipeline_statistic_query_registers().
brw_begin_perf_query()
static bool brw_begin_perf_query (struct gl_context * ctx, struct gl_perf_query_object * o) static
Driver hook for glBeginPerfQueryINTEL().
References gl_perf_query_object::Active, add_to_unaccumulated_query_list(), brw_context(), brw_emit_mi_flush(), brw_perf_query(), brw_oa_sample_buf::buf, brw_context::bufmgr, close_perf(), brw_context::current_oa_format, brw_context::current_oa_metrics_set_id, DBG, intel_screen::driScrnPriv, dump_perf_queries(), emit_mi_report_perf_count(), exec_node_data, brw_context::hw_ctx, gl_perf_query_object::Id, inc_n_oa_users(), brw_perf_query_info::kind, brw_oa_sample_buf::link, MI_RPC_BO_SIZE, brw_context::n_active_oa_queries, brw_context::n_active_pipeline_stats_queries, brw_context::n_oa_users, brw_context::next_query_start_report_id, brw_perf_query_object::oa, OA_COUNTERS, brw_perf_query_info::oa_format, brw_perf_query_info::oa_metrics_set_id, brw_context::oa_stream_fd, open_i915_perf_oa_stream(), brw_context::perfquery, brw_perf_query_object::pipeline_stats, PIPELINE_STATS, brw_perf_query_object::query, gl_perf_query_object::Ready, brw_oa_sample_buf::refcount, brw_context::sample_buffers, brw_context::screen, snapshot_statistics_registers(), STATS_BO_SIZE, and gl_perf_query_object::Used.
Referenced by brw_init_performance_queries().
brw_delete_perf_query()
static void brw_delete_perf_query (struct gl_context * ctx, struct gl_perf_query_object * o) static
Driver hook for glDeletePerfQueryINTEL().
References gl_perf_query_object::Active, brw_context(), brw_perf_query(), close_perf(), DBG, dec_n_oa_users(), drop_from_unaccumulated_query_list(), free_sample_bufs(), gl_perf_query_object::Id, brw_perf_query_info::kind, brw_context::n_query_instances, brw_perf_query_object::oa, OA_COUNTERS, brw_context::perfquery, brw_perf_query_object::pipeline_stats, PIPELINE_STATS, brw_perf_query_object::query, gl_perf_query_object::Ready, and gl_perf_query_object::Used.
Referenced by brw_init_performance_queries().
brw_end_perf_query()
static void brw_end_perf_query (struct gl_context * ctx, struct gl_perf_query_object * o) static
Driver hook for glEndPerfQueryINTEL().
References brw_context(), brw_emit_mi_flush(), brw_perf_query(), DBG, emit_mi_report_perf_count(), gl_perf_query_object::Id, brw_perf_query_info::kind, MI_RPC_BO_END_OFFSET_BYTES, brw_context::n_active_oa_queries, brw_context::n_active_pipeline_stats_queries, brw_perf_query_object::oa, OA_COUNTERS, brw_context::perfquery, PIPELINE_STATS, brw_perf_query_object::query, snapshot_statistics_registers(), and STATS_BO_END_OFFSET_BYTES.
Referenced by brw_init_performance_queries().
brw_get_perf_counter_info()
static void brw_get_perf_counter_info (struct gl_context * ctx, unsigned query_index, unsigned counter_index, const char ** name, const char ** desc, GLuint * offset, GLuint * data_size, GLuint * type_enum, GLuint * data_type_enum, GLuint64 * raw_max) static
Driver hook for glGetPerfCounterInfoINTEL().
References brw_context(), brw_perf_query_info::counters, brw_perf_query_counter::data_type, brw_perf_query_counter::desc, brw_perf_query_counter::name, brw_perf_query_counter::offset, brw_context::perfquery, brw_context::queries, brw_perf_query_counter::raw_max, brw_perf_query_counter::size, and brw_perf_query_counter::type.
Referenced by brw_init_performance_queries().
brw_get_perf_query_data()
static void brw_get_perf_query_data (struct gl_context * ctx, struct gl_perf_query_object * o, GLsizei data_size, GLuint * data, GLuint * bytes_written) static
Driver hook for glGetPerfQueryDataINTEL().
References brw_context(), brw_is_perf_query_ready(), brw_perf_query(), DBG, dump_perf_queries(), get_oa_counter_data(), get_pipeline_stats_data(), gl_perf_query_object::Id, brw_perf_query_info::kind, OA_COUNTERS, PIPELINE_STATS, brw_perf_query_object::query, and gl_perf_query_object::Ready.
Referenced by brw_init_performance_queries().
brw_get_perf_query_info()
static void brw_get_perf_query_info (struct gl_context * ctx, unsigned query_index, const char ** name, GLuint * data_size, GLuint * n_counters, GLuint * n_active) static
Driver hook for glGetPerfQueryInfoINTEL().
References brw_context(), brw_perf_query_info::data_size, brw_perf_query_info::kind, brw_context::n_active_oa_queries, brw_context::n_active_pipeline_stats_queries, brw_perf_query_info::n_counters, brw_perf_query_info::name, OA_COUNTERS, brw_context::perfquery, PIPELINE_STATS, and brw_context::queries.
Referenced by brw_init_performance_queries().
brw_init_perf_query_info()
static unsigned brw_init_perf_query_info (struct gl_context * ctx) static
References brw_context(), brw_oa_sample_buf::buf, enumerate_sysfs_metrics(), brw_context::free_sample_buffers, get_free_sample_buf(), get_sysfs_dev_dir(), init_oa_sys_vars(), init_pipeline_statistic_query_registers(), brw_context::is_haswell, brw_oa_sample_buf::link, brw_context::n_queries, brw_context::next_query_start_report_id, brw_context::oa_metrics_table, brw_context::oa_stream_fd, brw_context::perfquery, brw_context::sample_buffers, brw_context::unaccumulated, brw_context::unaccumulated_array_size, and brw_context::unaccumulated_elements.
Referenced by brw_init_performance_queries().
brw_init_performance_queries()
void brw_init_performance_queries (struct brw_context * brw)
References dd_function_table::BeginPerfQuery, brw_begin_perf_query(), brw_delete_perf_query(), brw_end_perf_query(), brw_get_perf_counter_info(), brw_get_perf_query_data(), brw_get_perf_query_info(), brw_init_perf_query_info(), brw_is_perf_query_ready(), brw_new_perf_query_object(), brw_wait_perf_query(), brw_context::ctx, dd_function_table::DeletePerfQuery, gl_context::Driver, dd_function_table::EndPerfQuery, dd_function_table::GetPerfCounterInfo, dd_function_table::GetPerfQueryData, dd_function_table::GetPerfQueryInfo, dd_function_table::InitPerfQueryInfo, dd_function_table::IsPerfQueryReady, dd_function_table::NewPerfQueryObject, and dd_function_table::WaitPerfQuery.
Referenced by brw_get_index_type(), and brwCreateContext().
brw_is_perf_query_ready()
static bool brw_is_perf_query_ready (struct gl_context * ctx, struct gl_perf_query_object * o) static
References brw_context::batch, intel_batchbuffer::bo, brw_context(), brw_perf_query(), brw_perf_query_info::kind, brw_perf_query_object::oa, OA_COUNTERS, brw_perf_query_object::pipeline_stats, PIPELINE_STATS, brw_perf_query_object::query, and gl_perf_query_object::Ready.
Referenced by brw_get_perf_query_data(), brw_init_performance_queries(), and dump_perf_query_callback().
brw_new_perf_query_object()
static struct gl_perf_query_object* brw_new_perf_query_object (struct gl_context * ctx, unsigned query_index) static
References brw_perf_query_object::base, brw_context(), brw_context::n_query_instances, brw_context::perfquery, brw_context::queries, and brw_perf_query_object::query.
Referenced by brw_init_performance_queries().
brw_perf_query()
static struct brw_perf_query_object* brw_perf_query (struct gl_perf_query_object * o) static
Downcasting convenience macro.
Referenced by brw_begin_perf_query(), brw_delete_perf_query(), brw_end_perf_query(), brw_get_perf_query_data(), brw_is_perf_query_ready(), and brw_wait_perf_query().
brw_wait_perf_query()
static void brw_wait_perf_query (struct gl_context * ctx, struct gl_perf_query_object * o) static
References brw_context::batch, brw_perf_query_object::bo, intel_batchbuffer::bo, brw_context(), brw_perf_query(), intel_batchbuffer_flush, brw_perf_query_info::kind, brw_perf_query_object::oa, OA_COUNTERS, brw_context::perf_debug, brw_perf_query_object::pipeline_stats, PIPELINE_STATS, brw_perf_query_object::query, and gl_perf_query_object::Ready.
Referenced by brw_init_performance_queries().
close_perf()
static void close_perf (struct brw_context * brw) static
References brw_context::oa_stream_fd, and brw_context::perfquery.
Referenced by brw_begin_perf_query(), and brw_delete_perf_query().
dec_n_oa_users()
static void dec_n_oa_users (struct brw_context * brw) static
References DBG, brw_context::n_oa_users, brw_context::oa_stream_fd, and brw_context::perfquery.
Referenced by accumulate_oa_reports(), brw_delete_perf_query(), and discard_all_queries().
discard_all_queries()
static void discard_all_queries (struct brw_context * brw) static
References dec_n_oa_users(), drop_from_unaccumulated_query_list(), brw_perf_query_object::oa, brw_context::perfquery, brw_context::unaccumulated, and brw_context::unaccumulated_elements.
Referenced by accumulate_oa_reports().
drop_from_unaccumulated_query_list()
static void drop_from_unaccumulated_query_list (struct brw_context * brw, struct brw_perf_query_object * obj) static
Remove a query from the global list of unaccumulated queries once after successfully accumulating the OA reports associated with the query in accumulate_oa_reports() or when discarding unwanted query results.
References brw_oa_sample_buf::buf, exec_node_data, brw_oa_sample_buf::link, brw_perf_query_object::oa, brw_context::perfquery, reap_old_sample_buffers(), brw_oa_sample_buf::refcount, brw_context::unaccumulated, and brw_context::unaccumulated_elements.
Referenced by accumulate_oa_reports(), brw_delete_perf_query(), and discard_all_queries().
dump_perf_queries()
static void dump_perf_queries (struct brw_context * brw) static
References _mesa_HashWalk(), brw_context::ctx, DBG, dump_perf_query_callback(), brw_context::n_active_oa_queries, brw_context::n_oa_users, gl_perf_query_state::Objects, gl_context::PerfQuery, and brw_context::perfquery.
Referenced by brw_begin_perf_query(), and brw_get_perf_query_data().
dump_perf_query_callback()
static void dump_perf_query_callback (GLuint id, void * query_void, void * brw_void) static
References gl_perf_query_object::Active, brw_is_perf_query_ready(), DBG, brw_perf_query_info::kind, o, brw_perf_query_object::oa, OA_COUNTERS, brw_perf_query_object::pipeline_stats, PIPELINE_STATS, brw_perf_query_object::query, gl_perf_query_object::Ready, and gl_perf_query_object::Used.
Referenced by dump_perf_queries().
emit_mi_report_perf_count()
static void emit_mi_report_perf_count (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset_in_bytes, uint32_t report_id) static
Emit an MI_REPORT_PERF_COUNT command packet.
This asks the GPU to write a report of the current OA counter values into at the given offset and containing the given which we can cross-reference when parsing the report.
References ADVANCE_BATCH, BEGIN_BATCH, GEN6_MI_REPORT_PERF_COUNT, OUT_BATCH, and OUT_RELOC.
Referenced by brw_begin_perf_query(), and brw_end_perf_query().
enumerate_sysfs_metrics()
static void enumerate_sysfs_metrics (struct brw_context * brw, const char * sysfs_dev_dir) static
References append_query_info(), brw_oa_sample_buf::buf, DBG, brw_oa_sample_buf::len, brw_perf_query_info::oa_metrics_set_id, brw_context::oa_metrics_table, brw_context::perfquery, and read_file_uint64().
Referenced by brw_init_perf_query_info().
free_sample_bufs()
static void free_sample_bufs (struct brw_context * brw) static
References brw_oa_sample_buf::buf, foreach_list_typed_safe, brw_context::free_sample_buffers, brw_oa_sample_buf::link, and brw_context::perfquery.
Referenced by brw_delete_perf_query().
get_free_sample_buf()
static struct brw_oa_sample_buf* get_free_sample_buf (struct brw_context * brw) static
References brw_oa_sample_buf::buf, exec_node_data, brw_context::free_sample_buffers, brw_oa_sample_buf::len, brw_oa_sample_buf::link, brw_context::perfquery, and brw_oa_sample_buf::refcount.
Referenced by brw_init_perf_query_info(), and read_oa_samples().
get_oa_counter_data()
static int get_oa_counter_data (struct brw_context * brw, struct brw_perf_query_object * obj, size_t data_size, uint8_t * data) static
References accumulate_oa_reports(), brw_perf_query_info::counters, brw_perf_query_counter::data_type, brw_perf_query_info::n_counters, brw_perf_query_object::oa, brw_perf_query_counter::oa_counter_read_float, brw_perf_query_counter::oa_counter_read_uint64, brw_perf_query_counter::offset, brw_perf_query_object::query, and brw_perf_query_counter::size.
Referenced by brw_get_perf_query_data().
get_pipeline_stats_data()
static int get_pipeline_stats_data (struct brw_context * brw, struct brw_perf_query_object * obj, size_t data_size, uint8_t * data) static
References brw_perf_query_info::counters, brw_pipeline_stat::denominator, brw_perf_query_info::n_counters, brw_pipeline_stat::numerator, brw_perf_query_counter::pipeline_stat, brw_perf_query_object::pipeline_stats, brw_perf_query_object::query, and STATS_BO_END_OFFSET_BYTES.
Referenced by brw_get_perf_query_data().
get_sysfs_dev_dir()
static bool get_sysfs_dev_dir (struct brw_context * brw, char * path_buf, int path_buf_len) static
References DBG, intel_screen::driScrnPriv, brw_oa_sample_buf::len, and brw_context::screen.
Referenced by brw_init_perf_query_info().
inc_n_oa_users()
static bool inc_n_oa_users (struct brw_context * brw) static
References brw_context::n_oa_users, brw_context::oa_stream_fd, and brw_context::perfquery.
Referenced by brw_begin_perf_query().
init_oa_sys_vars()
static bool init_oa_sys_vars (struct brw_context * brw, const char * sysfs_dev_dir) static
References intel_screen::devinfo, brw_context::is_haswell, brw_context::perfquery, read_sysfs_drm_device_file_uint64(), brw_context::screen, and brw_context::sys_vars.
Referenced by brw_init_perf_query_info().
init_pipeline_statistic_query_registers()
static void init_pipeline_statistic_query_registers (struct brw_context * brw) static
References add_basic_stat_reg(), add_stat_reg(), append_query_info(), CL_INVOCATION_COUNT, CL_PRIMITIVES_COUNT, brw_perf_query_info::counters, CS_INVOCATION_COUNT, brw_perf_query_info::data_size, DS_INVOCATION_COUNT, brw_context::gen, GEN6_SO_NUM_PRIMS_WRITTEN, GEN6_SO_PRIM_STORAGE_NEEDED, GEN7_SO_NUM_PRIMS_WRITTEN, GEN7_SO_PRIM_STORAGE_NEEDED, GS_INVOCATION_COUNT, GS_PRIMITIVES_COUNT, HS_INVOCATION_COUNT, IA_PRIMITIVES_COUNT, IA_VERTICES_COUNT, brw_context::is_haswell, brw_perf_query_info::kind, MAX_STAT_COUNTERS, brw_perf_query_info::n_counters, brw_perf_query_info::name, PIPELINE_STATS, PS_DEPTH_COUNT, PS_INVOCATION_COUNT, and VS_INVOCATION_COUNT.
Referenced by brw_init_perf_query_info().
open_i915_perf_oa_stream()
static bool open_i915_perf_oa_stream (struct brw_context * brw, int metrics_set_id, int report_format, int period_exponent, int drm_fd, uint32_t ctx_id) static
References brw_context::current_oa_format, brw_context::current_oa_metrics_set_id, DBG, brw_context::oa_stream_fd, and brw_context::perfquery.
Referenced by brw_begin_perf_query().
read_file_uint64()
static bool read_file_uint64 (const char * file, uint64_t * val) static
References brw_oa_sample_buf::buf.
Referenced by enumerate_sysfs_metrics(), and read_sysfs_drm_device_file_uint64().
read_oa_samples()
static bool read_oa_samples (struct brw_context * brw) static
References brw_oa_sample_buf::buf, DBG, brw_context::free_sample_buffers, get_free_sample_buf(), brw_oa_sample_buf::len, brw_oa_sample_buf::link, brw_context::oa_stream_fd, brw_context::perfquery, and brw_context::sample_buffers.
Referenced by accumulate_oa_reports().
read_sysfs_drm_device_file_uint64()
static bool read_sysfs_drm_device_file_uint64 (struct brw_context * brw, const char * sysfs_dev_dir, const char * file, uint64_t * value) static
References brw_oa_sample_buf::buf, DBG, brw_oa_sample_buf::len, and read_file_uint64().
Referenced by init_oa_sys_vars().
reap_old_sample_buffers()
static void reap_old_sample_buffers (struct brw_context * brw) static
References brw_oa_sample_buf::buf, exec_node_data, foreach_list_typed_safe, brw_context::free_sample_buffers, brw_oa_sample_buf::link, brw_context::perfquery, and brw_context::sample_buffers.
Referenced by drop_from_unaccumulated_query_list().
snapshot_statistics_registers()
static void snapshot_statistics_registers (struct brw_context * brw, struct brw_perf_query_object * obj, uint32_t offset_in_bytes) static
Emit MI_STORE_REGISTER_MEM commands to capture all of the pipeline statistics for the performance query object.
References brw_store_register_mem64(), brw_perf_query_info::counters, brw_perf_query_counter::data_type, brw_perf_query_info::n_counters, brw_perf_query_counter::pipeline_stat, brw_perf_query_object::pipeline_stats, brw_perf_query_object::query, and brw_pipeline_stat::reg.
Referenced by brw_begin_perf_query(), and brw_end_perf_query().
timebase_scale()
static uint64_t timebase_scale (struct brw_context * brw, uint32_t u32_time_delta) static
References brw_context::perfquery, and brw_context::sys_vars.
Referenced by accumulate_oa_reports().