Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_wm.c File Reference
#include "brw_context.h"
#include "brw_wm.h"
#include "brw_state.h"
#include "main/enums.h"
#include "main/formats.h"
#include "main/fbobject.h"
#include "main/samplerobj.h"
#include "main/framebuffer.h"
#include "program/prog_parameter.h"
#include "program/program.h"
#include "intel_mipmap_tree.h"
#include "intel_image.h"
#include "compiler/brw_nir.h"
#include "brw_program.h"
#include "util/ralloc.h"
Functions
static void assign_fs_binding_table_offsets (const struct gen_device_info *devinfo, const struct gl_program *prog, const struct brw_wm_prog_key *key, struct brw_wm_prog_data *prog_data)
static void brw_wm_debug_recompile (struct brw_context *brw, struct gl_program *prog, const struct brw_wm_prog_key *key)
static bool brw_codegen_wm_prog (struct brw_context *brw, struct brw_program *fp, struct brw_wm_prog_key *key, struct brw_vue_map *vue_map)
All Mesa program -> GPU code generation goes through this function.
bool brw_debug_recompile_sampler_key (struct brw_context *brw, const struct brw_sampler_prog_key_data *old_key, const struct brw_sampler_prog_key_data *key)
static uint8_t gen6_gather_workaround (GLenum internalformat)
void brw_populate_sampler_prog_key_data (struct gl_context *ctx, const struct gl_program *prog, struct brw_sampler_prog_key_data *key)
static bool brw_wm_state_dirty (const struct brw_context *brw)
void brw_wm_populate_key (struct brw_context *brw, struct brw_wm_prog_key *key)
void brw_upload_wm_prog (struct brw_context *brw)
bool brw_fs_precompile (struct gl_context *ctx, struct gl_program *prog)
Function Documentation
assign_fs_binding_table_offsets()
static void assign_fs_binding_table_offsets (const struct gen_device_info * devinfo, const struct gl_program * prog, const struct brw_wm_prog_key * key, struct brw_wm_prog_data * prog_data) static
References brw_assign_common_binding_table_offsets(), and gl_program::nir.
Referenced by brw_codegen_wm_prog().
brw_codegen_wm_prog()
static bool brw_codegen_wm_prog (struct brw_context * brw, struct brw_program * fp, struct brw_wm_prog_key * key, struct brw_vue_map * vue_map) static
All Mesa program -> GPU code generation goes through this function.
Depending on the instructions used (i.e. flow control instructions) we'll use one of two code generators.
References _mesa_problem(), assign_fs_binding_table_offsets(), brw_context::base, brw_context::batch, brw_alloc_stage_scratch(), BRW_CACHE_FS_PROG, brw_dump_arb_asm(), brw_get_shader_time_index(), brw_nir_setup_arb_uniforms(), brw_nir_setup_glsl_uniforms(), brw_upload_cache(), brw_wm_debug_recompile(), brw_context::cache, brw_program::compiled_once, intel_screen::compiler, gl_context::Const, brw_context::ctx, intel_screen::devinfo, get_time(), GLuint, gl_program::info, gl_program::is_arb_asm, intel_batchbuffer::last_bo, linking_failure, gl_program_constants::MaxTextureImageUnits, gl_program::nir, brw_context::perf_debug, brw_stage_state::prog_data, brw_stage_state::prog_offset, gl_constants::Program, brw_program::program, brw_context::screen, gl_program::sh, ST_FS16, ST_FS8, brw_context::use_rep_send, and brw_context::wm.
Referenced by brw_fs_precompile(), and brw_upload_wm_prog().
brw_debug_recompile_sampler_key()
bool brw_debug_recompile_sampler_key (struct brw_context * brw, const struct brw_sampler_prog_key_data * old_key, const struct brw_sampler_prog_key_data * key)
References key_debug(), and MAX_SAMPLERS.
Referenced by brw_gs_debug_recompile(), brw_tcs_debug_recompile(), brw_tes_debug_recompile(), brw_vs_debug_recompile(), and brw_wm_debug_recompile().
brw_fs_precompile()
bool brw_fs_precompile (struct gl_context * ctx, struct gl_program * prog)
References _mesa_bitcount_64(), brw_context::base, BITFIELD64_BIT, brw_codegen_wm_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), intel_screen::devinfo, gl_context::Extensions, brw_context::gen, brw_program::id, gl_program::info, gl_extensions::MESA_shader_framebuffer_fetch, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::screen, and brw_context::wm.
Referenced by brw_shader_precompile(), and brwProgramStringNotify().
brw_populate_sampler_prog_key_data()
void brw_populate_sampler_prog_key_data (struct gl_context * ctx, const struct gl_program * prog, struct brw_sampler_prog_key_data * key)
References gl_texture_image::_BaseFormat, gl_texture_unit::_Current, gl_texture_object::_Swizzle, gl_texture_object::BaseLevel, brw_context(), brw_get_texture_swizzle(), intel_image_format::components, gl_texture_object::DepthMode, brw_context::gen, gen6_gather_workaround(), GL_TEXTURE_EXTERNAL_OES, gl_texture_object::Image, intel_texture_object(), gl_texture_image::InternalFormat, brw_context::is_haswell, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, intel_texture_object::mt, gl_program::nir, intel_texture_object::planar_format, gl_program::SamplersUsed, gl_program::SamplerUnits, gl_texture_object::Target, gl_context::Texture, gl_texture_attrib::Unit, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by brw_cs_populate_key(), brw_gs_populate_key(), brw_tcs_populate_key(), brw_tes_populate_key(), brw_vs_populate_key(), and brw_wm_populate_key().
brw_upload_wm_prog()
void brw_upload_wm_prog (struct brw_context * brw)
References brw_context::base, BRW_CACHE_FS_PROG, brw_codegen_wm_prog(), brw_search_cache(), brw_wm_populate_key(), brw_wm_state_dirty(), brw_context::cache, brw_context::fragment_program, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, void, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by brw_upload_programs().
brw_wm_debug_recompile()
static void brw_wm_debug_recompile (struct brw_context * brw, struct gl_program * prog, const struct brw_wm_prog_key * key) static
References BRW_CACHE_FS_PROG, brw_debug_recompile_sampler_key(), brw_find_previous_compile(), brw_context::cache, gl_program::Id, key_debug(), and brw_context::stats_wm.
Referenced by brw_codegen_wm_prog().
brw_wm_populate_key()
void brw_wm_populate_key (struct brw_context * brw, struct brw_wm_prog_key * key)
References gl_stencil_attrib::_BackFace, gl_colorbuffer_attrib::_ClampFragmentColor, gl_stencil_attrib::_Enabled, _mesa_bitcount_64(), _mesa_is_alpha_test_enabled(), _mesa_is_alpha_to_coverage_enabled(), gl_framebuffer::_NumColorDrawBuffers, gl_colorbuffer_attrib::_UsesDualSrc, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, gl_colorbuffer_attrib::AlphaRef, gl_polygon_attrib::BackMode, BITFIELD64_BIT, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, brw_depth_writes_enabled(), brw_populate_sampler_prog_key_data(), brw_program_const(), gl_context::Color, brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_context::Depth, gl_context::DrawBuffer, brw_context::dual_color_blend_by_location, gl_multisample_attrib::Enabled, gl_context::Extensions, brw_context::fragment_program, gl_hint_attrib::FragmentShaderDerivative, gl_polygon_attrib::FrontMode, brw_context::gen, GLuint, gl_context::Hint, brw_program::id, gl_program::info, gl_context::Light, gl_context::Line, gl_extensions::MESA_shader_framebuffer_fetch, gl_multisample_attrib::MinSampleShadingValue, gl_context::Multisample, gl_context::Polygon, brw_context::reduced_primitive, gl_multisample_attrib::SampleShading, gl_light_attrib::ShadeModel, gl_line_attrib::SmoothFlag, brw_context::stats_wm, gl_context::Stencil, gl_depthbuffer_attrib::Test, brw_context::vue_map_geom_out, and gl_stencil_attrib::WriteMask.
Referenced by brw_upload_wm_prog().
brw_wm_state_dirty()
static bool brw_wm_state_dirty (const struct brw_context * brw) static
References _NEW_BUFFERS, _NEW_COLOR, _NEW_DEPTH, _NEW_FRAG_CLAMP, _NEW_HINT, _NEW_LIGHT, _NEW_LINE, _NEW_MULTISAMPLE, _NEW_POLYGON, _NEW_STENCIL, _NEW_TEXTURE, BRW_NEW_FRAGMENT_PROGRAM, BRW_NEW_REDUCED_PRIMITIVE, BRW_NEW_STATS_WM, BRW_NEW_VUE_MAP_GEOM_OUT, and brw_state_dirty().
Referenced by brw_upload_wm_prog().
gen6_gather_workaround()
static uint8_t gen6_gather_workaround (GLenum internalformat) static
Referenced by brw_populate_sampler_prog_key_data().