Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_draw.c File Reference
#include <sys/errno.h>
#include "main/context.h"
#include "main/condrender.h"
#include "main/samplerobj.h"
#include "main/state.h"
#include "main/enums.h"
#include "main/macros.h"
#include "main/transformfeedback.h"
#include "main/framebuffer.h"
#include "tnl/tnl.h"
#include "vbo/vbo_context.h"
#include "swrast/swrast.h"
#include "swrast_setup/swrast_setup.h"
#include "drivers/common/meta.h"
#include "util/bitscan.h"
#include "brw_blorp.h"
#include "brw_draw.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
#include "brw_context.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "intel_buffer_objects.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_PRIMS
Functions
static void brw_set_prim (struct brw_context *brw, const struct _mesa_prim *prim)
static void gen6_set_prim (struct brw_context *brw, const struct _mesa_prim *prim)
static GLuint trim (GLenum prim, GLuint length)
The hardware is capable of removing dangling vertices on its own; however, prior to Gen6, we sometimes convert quads into trifans (and quad strips into tristrips), since pre-Gen6 hardware requires a GS to render quads.
static void brw_emit_prim (struct brw_context *brw, const struct _mesa_prim *prim, uint32_t hw_prim, struct brw_transform_feedback_object *xfb_obj, unsigned stream)
static void brw_merge_inputs (struct brw_context *brw, const struct gl_vertex_array *arrays[])
static void brw_postdraw_set_buffers_need_resolve (struct brw_context *brw)
Call this after drawing to mark which buffers need resolving.
static void brw_predraw_set_aux_buffers (struct brw_context *brw)
static void brw_try_draw_prims (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, bool index_bounds_valid, GLuint min_index, GLuint max_index, struct brw_transform_feedback_object *xfb_obj, unsigned stream, struct gl_buffer_object *indirect)
void brw_draw_prims (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *gl_xfb_obj, unsigned stream, struct gl_buffer_object *indirect)
void brw_draw_init (struct brw_context *brw)
void brw_draw_destroy (struct brw_context *brw)
Variables
static const GLenum reduced_prim [GL_POLYGON+1]
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PRIMS
Function Documentation
brw_draw_destroy()
void brw_draw_destroy (struct brw_context * brw)
References brw_vertex_buffer::bo, brw_vertex_element::buffer, brw_context::buffers, brw_context::enabled, brw_context::ib, brw_context::nr_buffers, brw_context::nr_enabled, and brw_context::vb.
Referenced by intelDestroyContext().
brw_draw_init()
void brw_draw_init (struct brw_context * brw)
References brw_draw_prims(), brw_vertex_element::buffer, brw_context::ctx, vbo_context::draw_prims, brw_context::inputs, brw_context::nr_buffers, brw_context::nr_enabled, and brw_context::vb.
Referenced by brwCreateContext().
brw_draw_prims()
void brw_draw_prims (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object * gl_xfb_obj, unsigned stream, struct gl_buffer_object * indirect)
References gl_array_attrib::_DrawArrays, _mesa_enum_to_string(), _swsetup_Wakeup(), _tnl_draw_prims(), _tnl_wakeup(), gl_context::Array, brw_check_conditional_render(), brw_context(), brw_handle_primitive_restart(), brw_try_draw_prims(), gl_context::RenderMode, vbo_all_varyings_in_vbos(), and vbo_get_minmax_indices().
Referenced by brw_draw_init(), and brw_handle_primitive_restart().
brw_emit_prim()
static void brw_emit_prim (struct brw_context * brw, const struct _mesa_prim * prim, uint32_t hw_prim, struct brw_transform_feedback_object * xfb_obj, unsigned stream) static
References _mesa_enum_to_string(), ADVANCE_BATCH, brw_context::always_flush_cache, _mesa_prim::base_instance, _mesa_prim::basevertex, BEGIN_BATCH, brw_emit_mi_flush(), brw_load_register_mem(), BRW_PREDICATE_STATE_USE_BIT, CMD_3D_PRIM, _mesa_prim::count, brw_context::ctx, DBG, gl_context::DrawIndirectBuffer, brw_context::gen, GEN4_3DPRIM_TOPOLOGY_TYPE_SHIFT, GEN4_3DPRIM_VERTEXBUFFER_ACCESS_RANDOM, GEN4_3DPRIM_VERTEXBUFFER_ACCESS_SEQUENTIAL, GEN7_3DPRIM_BASE_VERTEX, GEN7_3DPRIM_INDIRECT_PARAMETER_ENABLE, GEN7_3DPRIM_INSTANCE_COUNT, GEN7_3DPRIM_PREDICATE_ENABLE, GEN7_3DPRIM_START_INSTANCE, GEN7_3DPRIM_START_VERTEX, GEN7_3DPRIM_VERTEX_COUNT, GEN7_3DPRIM_VERTEXBUFFER_ACCESS_RANDOM, GEN7_3DPRIM_VERTEXBUFFER_ACCESS_SEQUENTIAL, GLuint, brw_context::ib, _mesa_prim::indexed, _mesa_prim::indirect_offset, intel_buffer_object(), intel_bufferobj_buffer(), _mesa_prim::is_indirect, MI_LOAD_REGISTER_IMM, _mesa_prim::mode, _mesa_prim::num_instances, OUT_BATCH, brw_context::predicate, brw_transform_feedback_object::prim_count_bo, _mesa_prim::start, brw_context::start_vertex_bias, brw_context::state, trim(), and brw_context::vb.
Referenced by brw_try_draw_prims().
brw_merge_inputs()
static void brw_merge_inputs (struct brw_context * brw, const struct gl_vertex_array * arrays[]) static
References gl_vertex_program_state::_Current, brw_context::attrib_wa_flags, brw_vertex_buffer::bo, BRW_NEW_VS_ATTRIB_WORKAROUNDS, brw_vertex_element::buffer, brw_context::buffers, brw_context::ctx, gl_vertex_array::Format, brw_context::gen, brw_vertex_element::glarray, GLuint, gl_program::info, brw_context::inputs, gl_vertex_array::Integer, brw_context::is_haswell, gl_context::NewDriverState, gl_vertex_array::Normalized, brw_context::nr_buffers, gl_vertex_array::Size, gl_vertex_array::Type, brw_context::vb, and gl_context::VertexProgram.
Referenced by brw_try_draw_prims().
brw_postdraw_set_buffers_need_resolve()
static void brw_postdraw_set_buffers_need_resolve (struct brw_context * brw) static
Call this after drawing to mark which buffers need resolving.
If the depth buffer was written to and if it has an accompanying HiZ buffer, then mark that it needs a depth resolve.
If the color buffer is a multisample window system buffer, then mark that it needs a downsample.
Also mark any render targets which will be textured as needing a render cache flush.
References gl_framebuffer::_ColorDrawBuffers, _mesa_is_front_buffer_drawing(), gl_framebuffer::_NumColorDrawBuffers, gl_stencil_attrib::_WriteEnabled, gl_extensions::ARB_stencil_texturing, gl_framebuffer::Attachment, brw_depth_writes_enabled(), brw_render_cache_set_add_bo(), BUFFER_BACK_LEFT, BUFFER_DEPTH, BUFFER_FRONT_LEFT, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, gl_context::Extensions, intel_get_renderbuffer(), intel_miptree_used_for_rendering(), intel_renderbuffer(), intel_renderbuffer_att_set_needs_depth_resolve(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, intel_renderbuffer::need_downsample, and gl_context::Stencil.
Referenced by brw_try_draw_prims().
brw_predraw_set_aux_buffers()
static void brw_predraw_set_aux_buffers (struct brw_context * brw) static
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, brw_context::ctx, gl_context::DrawBuffer, brw_context::gen, intel_miptree_is_lossless_compressed(), intel_miptree_resolve_color(), intel_renderbuffer(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by brw_try_draw_prims().
brw_set_prim()
static void brw_set_prim (struct brw_context * brw, const struct _mesa_prim * prim) static
References _mesa_enum_to_string(), gl_polygon_attrib::BackMode, BRW_NEW_PRIMITIVE, BRW_NEW_REDUCED_PRIMITIVE, _mesa_prim::count, brw_context::ctx, DBG, gl_polygon_attrib::FrontMode, get_hw_prim_for_gl_prim(), gl_context::Light, _mesa_prim::mode, gl_context::NewDriverState, gl_context::Polygon, brw_context::primitive, reduced_prim, brw_context::reduced_primitive, and gl_light_attrib::ShadeModel.
Referenced by brw_try_draw_prims().
brw_try_draw_prims()
static void brw_try_draw_prims (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, bool index_bounds_valid, GLuint min_index, GLuint max_index, struct brw_transform_feedback_object * xfb_obj, unsigned stream, struct gl_buffer_object * indirect) static
References gl_fragment_program_state::_Current, gl_tess_eval_program_state::_Current, gl_tess_ctrl_program_state::_Current, gl_vertex_program_state::_Current, gl_geometry_program_state::_Current, _mesa_update_state(), brw_context::always_flush_batch, brw_context::base, _mesa_prim::base_instance, brw_context::baseinstance, _mesa_prim::basevertex, brw_context::basevertex, brw_context::batch, intel_batchbuffer::bo, brw_context(), brw_emit_prim(), BRW_MAX_TEX_UNIT, brw_merge_inputs(), BRW_NEW_INDICES, BRW_NEW_VERTICES, brw_postdraw_set_buffers_need_resolve(), brw_predraw_set_aux_buffers(), brw_program_cache_check_size(), brw_render_state_finished(), brw_set_prim(), brw_upload_render_state(), brw_validate_textures(), brw_workaround_depthstencil_alignment(), intel_buffer_object::buffer, brw_context::ctx, brw_context::draw, _mesa_prim::draw_id, brw_context::draw_id_bo, brw_context::draw_params_bo, brw_context::draw_params_offset, gl_context::DrawIndirectBuffer, gl_context::FragmentProgram, brw_context::gen, gen6_set_prim(), gl_context::GeometryProgram, brw_context::gl_drawid, GLuint, brw_context::gs, brw_context::ib, brw_context::index_bounds_valid, _mesa_prim::indexed, _mesa_prim::indirect_offset, intel_batchbuffer_flush, intel_batchbuffer_require_space(), intel_batchbuffer_reset_to_saved(), intel_batchbuffer_save_state(), intel_buffer_object(), intel_prepare_render(), brw_context::max_index, brw_context::min_index, gl_context::NewDriverState, gl_context::NewState, brw_context::no_batch_wrap, _mesa_prim::num_instances, brw_context::num_instances, brw_context::params, brw_context::primitive, brw_stage_state::prog_data, RENDER_RING, ret(), brw_stage_state::sampler_count, gl_program::SamplersUsed, _mesa_prim::start, brw_context::tcs, brw_context::tes, gl_context::TessCtrlProgram, gl_context::TessEvalProgram, brw_context::vb, gl_context::VertexProgram, brw_context::vs, and brw_context::wm.
Referenced by brw_draw_prims().
gen6_set_prim()
static void gen6_set_prim (struct brw_context * brw, const struct _mesa_prim * prim) static
References _mesa_enum_to_string(), BRW_NEW_PATCH_PRIMITIVE, BRW_NEW_PRIMITIVE, brw_context::ctx, DBG, get_hw_prim_for_gl_prim(), GLuint, _mesa_prim::mode, gl_context::NewDriverState, gl_tess_ctrl_program_state::patch_vertices, brw_context::primitive, and gl_context::TessCtrlProgram.
Referenced by brw_try_draw_prims().
trim()
static GLuint trim (GLenum prim, GLuint length) static
The hardware is capable of removing dangling vertices on its own; however, prior to Gen6, we sometimes convert quads into trifans (and quad strips into tristrips), since pre-Gen6 hardware requires a GS to render quads.
This function manually trims dangling vertices from a draw call involving quads so that those dangling vertices won't get drawn when we convert to trifans/tristrips.
Referenced by brw_emit_prim().
Variable Documentation
reduced_prim
const GLenum reduced_prim[GL_POLYGON+1] static
Initial value:
= {
   [GL_POINTS] = GL_POINTS,
   [GL_LINES] = GL_LINES,
   [GL_LINE_LOOP] = GL_LINES,
   [GL_LINE_STRIP] = GL_LINES,
   [GL_TRIANGLES] = GL_TRIANGLES,
   [GL_TRIANGLE_STRIP] = GL_TRIANGLES,
   [GL_TRIANGLE_FAN] = GL_TRIANGLES,
   [GL_QUADS] = GL_TRIANGLES,
   [GL_QUAD_STRIP] = GL_TRIANGLES,
   [GL_POLYGON] = GL_TRIANGLES
}
Referenced by brw_set_prim().