Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_gs.h File Reference
#include <stdbool.h>
#include "brw_context.h"
Functions
void brw_upload_gs_prog (struct brw_context *brw)
void brw_gs_populate_key (struct brw_context *brw, struct brw_gs_prog_key *key)
Function Documentation
brw_gs_populate_key()
void brw_gs_populate_key (struct brw_context * brw, struct brw_gs_prog_key * key)
References brw_populate_sampler_prog_key_data(), brw_context::ctx, brw_context::geometry_program, brw_program::id, and brw_program::program.
Referenced by brw_upload_gs_prog().
brw_upload_gs_prog()
void brw_upload_gs_prog (struct brw_context * brw)
References brw_context::base, BRW_CACHE_GS_PROG, brw_codegen_gs_prog(), brw_gs_populate_key(), brw_gs_state_dirty(), BRW_NEW_TRANSFORM_FEEDBACK, brw_search_cache(), brw_context::cache, brw_context::ctx, brw_context::gen, gen6_brw_upload_ff_gs_prog(), brw_context::geometry_program, brw_context::gs, if(), gl_context::NewDriverState, brw_stage_state::prog_data, brw_stage_state::prog_offset, and void.
Referenced by brw_upload_programs().