Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_sf.h File Reference
#include "program/program.h"
#include "brw_context.h"
#include "compiler/brw_eu.h"
Data Structures
struct brw_sf_prog_key
struct brw_sf_compile
Macros
#define SF_POINTS 0
#define SF_LINES 1
#define SF_TRIANGLES 2
#define SF_UNFILLED_TRIS 3
Functions
void brw_emit_tri_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_line_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_point_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_point_sprite_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_anyprim_setup (struct brw_sf_compile *c)
Macro Definition Documentation
SF_LINES
#define SF_LINES 1
Referenced by brw_upload_sf_prog(), and compile_sf_prog().
SF_POINTS
#define SF_POINTS 0
Referenced by brw_upload_sf_prog(), and compile_sf_prog().
SF_TRIANGLES
#define SF_TRIANGLES 2
Referenced by brw_upload_sf_prog(), and compile_sf_prog().
SF_UNFILLED_TRIS
#define SF_UNFILLED_TRIS 3
Referenced by brw_upload_sf_prog(), compile_sf_prog(), do_flatshade_line(), do_flatshade_triangle(), and do_twoside_color().
Function Documentation
brw_emit_anyprim_setup()
void brw_emit_anyprim_setup (struct brw_sf_compile * c)
References alloc_regs(), brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), brw_emit_tri_setup(), BRW_SPRITE_POINT_ENABLE, brw_sf_compile::func, brw_sf_compile::nr_verts, and brw_sf_compile::tmp.
Referenced by compile_sf_prog().
brw_emit_line_setup()
void brw_emit_line_setup (struct brw_sf_compile * c, bool allocate)
References brw_sf_compile::a1_sub_a0, alloc_regs(), calculate_masks(), brw_sf_prog_key::contains_flat_varying, copy_z_inv_w(), do_flatshade_line(), brw_sf_compile::dx0, brw_sf_compile::dy0, brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_det, brw_sf_compile::inv_w, invert_det(), brw_sf_compile::key, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), brw_sf_compile::tmp, and brw_sf_compile::vert.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
brw_emit_point_setup()
void brw_emit_point_setup (struct brw_sf_compile * c, bool allocate)
References alloc_regs(), calculate_masks(), copy_z_inv_w(), brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_w, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), and brw_sf_compile::vert.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
brw_emit_point_sprite_setup()
void brw_emit_point_sprite_setup (struct brw_sf_compile * c, bool allocate)
References alloc_regs(), calculate_masks(), calculate_point_sprite_mask(), copy_z_inv_w(), brw_sf_compile::dx0, brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_w, brw_sf_compile::key, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), brw_sf_prog_key::sprite_origin_lower_left, brw_sf_compile::tmp, brw_sf_compile::vert, WRITEMASK_W, WRITEMASK_X, and WRITEMASK_Y.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
brw_emit_tri_setup()
void brw_emit_tri_setup (struct brw_sf_compile * c, bool allocate)
References brw_sf_compile::a1_sub_a0, brw_sf_compile::a2_sub_a0, alloc_regs(), calculate_masks(), brw_sf_prog_key::contains_flat_varying, copy_z_inv_w(), do_flatshade_triangle(), brw_sf_prog_key::do_twoside_color, do_twoside_color(), brw_sf_compile::dx0, brw_sf_compile::dx2, brw_sf_compile::dy0, brw_sf_compile::dy2, brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_det, brw_sf_compile::inv_w, invert_det(), brw_sf_compile::key, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), brw_sf_compile::tmp, and brw_sf_compile::vert.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().