Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_sync.c File Reference
Support for GL_ARB_sync and EGL_KHR_fence_sync.
#include <libsync.h>
#include "main/imports.h"
#include "brw_context.h"
#include "intel_batchbuffer.h"
Data Structures
struct brw_fence
struct brw_gl_sync
Functions
static void brw_fence_init (struct brw_context *brw, struct brw_fence *fence, enum brw_fence_type type)
static void brw_fence_finish (struct brw_fence *fence)
static bool MUST_CHECK brw_fence_insert_locked (struct brw_context *brw, struct brw_fence *fence)
static bool MUST_CHECK brw_fence_insert (struct brw_context *brw, struct brw_fence *fence)
static bool brw_fence_has_completed_locked (struct brw_fence *fence)
static bool brw_fence_has_completed (struct brw_fence *fence)
static bool brw_fence_client_wait_locked (struct brw_context *brw, struct brw_fence *fence, uint64_t timeout)
static bool brw_fence_client_wait (struct brw_context *brw, struct brw_fence *fence, uint64_t timeout)
Return true if the function successfully signals or has already signalled.
static void brw_fence_server_wait (struct brw_context *brw, struct brw_fence *fence)
static struct gl_sync_object * brw_gl_new_sync (struct gl_context *ctx, GLuint id)
static void brw_gl_delete_sync (struct gl_context *ctx, struct gl_sync_object *_sync)
static void brw_gl_fence_sync (struct gl_context *ctx, struct gl_sync_object *_sync, GLenum condition, GLbitfield flags)
static void brw_gl_client_wait_sync (struct gl_context *ctx, struct gl_sync_object *_sync, GLbitfield flags, GLuint64 timeout)
static void brw_gl_server_wait_sync (struct gl_context *ctx, struct gl_sync_object *_sync, GLbitfield flags, GLuint64 timeout)
static void brw_gl_check_sync (struct gl_context *ctx, struct gl_sync_object *_sync)
void brw_init_syncobj_functions (struct dd_function_table *functions)
static void * brw_dri_create_fence (__DRIcontext *ctx)
static void brw_dri_destroy_fence (__DRIscreen *dri_screen, void *_fence)
static GLboolean brw_dri_client_wait_sync (__DRIcontext *ctx, void *_fence, unsigned flags, uint64_t timeout)
static void brw_dri_server_wait_sync (__DRIcontext *ctx, void *_fence, unsigned flags)
static unsigned brw_dri_get_capabilities (__DRIscreen *dri_screen)
static void * brw_dri_create_fence_fd (__DRIcontext *dri_ctx, int fd)
static int brw_dri_get_fence_fd_locked (struct brw_fence *fence)
static int brw_dri_get_fence_fd (__DRIscreen *dri_screen, void *_fence)
Variables
const __DRI2fenceExtension intelFenceExtension
Detailed Description
Support for GL_ARB_sync and EGL_KHR_fence_sync.
GL_ARB_sync is implemented by flushing the current batchbuffer and keeping a reference on it. We can then check for completion or wait for completion using the normal buffer object mechanisms. This does mean that if an application is using many sync objects, it will emit small batchbuffers which may end up being a significant overhead. In other tests of removing gratuitous batchbuffer syncs in Mesa, it hasn't appeared to be a significant performance bottleneck, though.
Function Documentation
brw_dri_client_wait_sync()
static GLboolean brw_dri_client_wait_sync (__DRIcontext * ctx, void * _fence, unsigned flags, uint64_t timeout) static
References brw_fence::brw, and brw_fence_client_wait().
brw_dri_create_fence()
static void* brw_dri_create_fence (__DRIcontext * ctx) static
References brw_fence::brw, brw_fence_finish(), brw_fence_init(), brw_fence_insert_locked(), and brw_fence::BRW_FENCE_TYPE_BO_WAIT.
brw_dri_create_fence_fd()
static void* brw_dri_create_fence_fd (__DRIcontext * dri_ctx, int fd) static
References brw_fence::brw, brw_fence_finish(), brw_fence_init(), brw_fence_insert_locked(), brw_fence::BRW_FENCE_TYPE_SYNC_FD, intel_screen::has_exec_fence, brw_context::screen, and brw_fence::sync_fd.
brw_dri_destroy_fence()
static void brw_dri_destroy_fence (__DRIscreen * dri_screen, void * _fence) static
References brw_fence_finish().
brw_dri_get_capabilities()
static unsigned brw_dri_get_capabilities (__DRIscreen * dri_screen) static
References intel_screen::has_exec_fence.
brw_dri_get_fence_fd()
static int brw_dri_get_fence_fd (__DRIscreen * dri_screen, void * _fence) static
References brw_dri_get_fence_fd_locked(), and brw_fence::mutex.
brw_dri_get_fence_fd_locked()
static int brw_dri_get_fence_fd_locked (struct brw_fence * fence) static
References brw_fence::BRW_FENCE_TYPE_SYNC_FD, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_dri_get_fence_fd().
brw_dri_server_wait_sync()
static void brw_dri_server_wait_sync (__DRIcontext * ctx, void * _fence, unsigned flags) static
References brw_fence::brw, and brw_fence_server_wait().
brw_fence_client_wait()
static bool brw_fence_client_wait (struct brw_context * brw, struct brw_fence * fence, uint64_t timeout) static
Return true if the function successfully signals or has already signalled.
(This matches the behavior expected from __DRI2fence::client_wait_sync).
References brw_fence_client_wait_locked(), brw_fence::mutex, and ret().
Referenced by brw_dri_client_wait_sync(), and brw_gl_client_wait_sync().
brw_fence_client_wait_locked()
static bool brw_fence_client_wait_locked (struct brw_context * brw, struct brw_fence * fence, uint64_t timeout) static
References brw_fence::batch_bo, brw_fence::BRW_FENCE_TYPE_BO_WAIT, brw_fence::BRW_FENCE_TYPE_SYNC_FD, brw_fence::signalled, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_fence_client_wait().
brw_fence_finish()
static void brw_fence_finish (struct brw_fence * fence) static
References brw_fence::batch_bo, brw_fence::BRW_FENCE_TYPE_BO_WAIT, brw_fence::BRW_FENCE_TYPE_SYNC_FD, brw_fence::mutex, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_dri_create_fence(), brw_dri_create_fence_fd(), brw_dri_destroy_fence(), and brw_gl_delete_sync().
brw_fence_has_completed()
static bool brw_fence_has_completed (struct brw_fence * fence) static
References brw_fence_has_completed_locked(), brw_fence::mutex, and ret().
Referenced by brw_gl_check_sync().
brw_fence_has_completed_locked()
static bool brw_fence_has_completed_locked (struct brw_fence * fence) static
References brw_fence::batch_bo, brw_fence::BRW_FENCE_TYPE_BO_WAIT, brw_fence::BRW_FENCE_TYPE_SYNC_FD, brw_fence::signalled, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_fence_has_completed().
brw_fence_init()
static void brw_fence_init (struct brw_context * brw, struct brw_fence * fence, enum brw_fence_type type) static
References brw_fence::batch_bo, brw_fence::brw, brw_fence::BRW_FENCE_TYPE_BO_WAIT, brw_fence::BRW_FENCE_TYPE_SYNC_FD, brw_fence::mutex, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_dri_create_fence(), brw_dri_create_fence_fd(), and brw_gl_fence_sync().
brw_fence_insert()
static bool MUST_CHECK brw_fence_insert (struct brw_context * brw, struct brw_fence * fence) static
References brw_fence_insert_locked(), brw_fence::mutex, and ret().
Referenced by brw_fence_server_wait().
brw_fence_insert_locked()
static bool MUST_CHECK brw_fence_insert_locked (struct brw_context * brw, struct brw_fence * fence) static
References brw_context::batch, brw_fence::batch_bo, intel_batchbuffer::bo, brw_emit_mi_flush(), brw_fence::BRW_FENCE_TYPE_BO_WAIT, brw_fence::BRW_FENCE_TYPE_SYNC_FD, intel_batchbuffer_flush, intel_batchbuffer_flush_fence, brw_fence::signalled, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_dri_create_fence(), brw_dri_create_fence_fd(), brw_fence_insert(), and brw_gl_fence_sync().
brw_fence_server_wait()
static void brw_fence_server_wait (struct brw_context * brw, struct brw_fence * fence) static
References brw_fence_insert(), brw_fence::BRW_FENCE_TYPE_BO_WAIT, brw_fence::BRW_FENCE_TYPE_SYNC_FD, brw_fence::sync_fd, and brw_fence::type.
Referenced by brw_dri_server_wait_sync(), and brw_gl_server_wait_sync().
brw_gl_check_sync()
static void brw_gl_check_sync (struct gl_context * ctx, struct gl_sync_object * _sync) static
References brw_fence_has_completed(), brw_gl_sync::fence, brw_gl_sync::gl, and gl_sync_object::StatusFlag.
Referenced by brw_init_syncobj_functions().
brw_gl_client_wait_sync()
static void brw_gl_client_wait_sync (struct gl_context * ctx, struct gl_sync_object * _sync, GLbitfield flags, GLuint64 timeout) static
References brw_fence::brw, brw_context(), brw_fence_client_wait(), brw_gl_sync::fence, brw_gl_sync::gl, and gl_sync_object::StatusFlag.
Referenced by brw_init_syncobj_functions().
brw_gl_delete_sync()
static void brw_gl_delete_sync (struct gl_context * ctx, struct gl_sync_object * _sync) static
References brw_fence_finish(), and brw_gl_sync::fence.
Referenced by brw_init_syncobj_functions().
brw_gl_fence_sync()
static void brw_gl_fence_sync (struct gl_context * ctx, struct gl_sync_object * _sync, GLenum condition, GLbitfield flags) static
References brw_fence::brw, brw_context(), brw_fence_init(), brw_fence_insert_locked(), brw_fence::BRW_FENCE_TYPE_BO_WAIT, and brw_gl_sync::fence.
Referenced by brw_init_syncobj_functions().
brw_gl_new_sync()
static struct gl_sync_object* brw_gl_new_sync (struct gl_context * ctx, GLuint id) static
References brw_gl_sync::gl.
Referenced by brw_init_syncobj_functions().
brw_gl_server_wait_sync()
static void brw_gl_server_wait_sync (struct gl_context * ctx, struct gl_sync_object * _sync, GLbitfield flags, GLuint64 timeout) static
References brw_fence::brw, brw_context(), brw_fence_server_wait(), and brw_gl_sync::fence.
Referenced by brw_init_syncobj_functions().
brw_init_syncobj_functions()
void brw_init_syncobj_functions (struct dd_function_table * functions)
References brw_gl_check_sync(), brw_gl_client_wait_sync(), brw_gl_delete_sync(), brw_gl_fence_sync(), brw_gl_new_sync(), brw_gl_server_wait_sync(), dd_function_table::CheckSync, dd_function_table::ClientWaitSync, dd_function_table::DeleteSyncObject, dd_function_table::FenceSync, dd_function_table::NewSyncObject, and dd_function_table::ServerWaitSync.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
Variable Documentation
intelFenceExtension
const __DRI2fenceExtension intelFenceExtension
Initial value:
= {
   .base = { __DRI2_FENCE, 2 },
   .create_fence = brw_dri_create_fence,
   .destroy_fence = brw_dri_destroy_fence,
   .client_wait_sync = brw_dri_client_wait_sync,
   .server_wait_sync = brw_dri_server_wait_sync,
   .get_fence_from_cl_event = NULL,
   .get_capabilities = brw_dri_get_capabilities,
   .create_fence_fd = brw_dri_create_fence_fd,
   .get_fence_fd = brw_dri_get_fence_fd,
}