Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_draw_upload.c File Reference
#include "main/bufferobj.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/macros.h"
#include "main/glformats.h"
#include "brw_draw.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
Functions
static GLuint double_types (struct brw_context *brw, int size, GLboolean doubles)
static bool is_passthru_format (uint32_t format)
static int uploads_needed (uint32_t format)
static int upload_format_size (uint32_t upload_format)
static uint32_t downsize_format_if_needed (uint32_t format, int upload)
unsigned brw_get_vertex_surface_type (struct brw_context *brw, const struct gl_vertex_array *glarray)
Given vertex array type/size/format/normalized info, return the appopriate hardware surface type.
static void copy_array_to_vbo_array (struct brw_context *brw, struct brw_vertex_element *element, int min, int max, struct brw_vertex_buffer *buffer, GLuint dst_stride)
void brw_prepare_vertices (struct brw_context *brw)
void brw_prepare_shader_draw_parameters (struct brw_context *brw)
uint32_t * brw_emit_vertex_buffer_state (struct brw_context *brw, unsigned buffer_nr, drm_intel_bo *bo, unsigned start_offset, unsigned end_offset, unsigned stride, unsigned step_rate, uint32_t *__map)
Emit a VERTEX_BUFFER_STATE entry (part of 3DSTATE_VERTEX_BUFFERS).
static void brw_emit_vertices (struct brw_context *brw)
static void brw_upload_indices (struct brw_context *brw)
static void brw_emit_index_buffer (struct brw_context *brw)
Variables
static const GLuint double_types_float [5]
static const GLuint double_types_passthru [5]
static const GLuint float_types [5]
static const GLuint half_float_types [5]
static const GLuint fixed_point_types [5]
static const GLuint uint_types_direct [5]
static const GLuint uint_types_norm [5]
static const GLuint uint_types_scale [5]
static const GLuint int_types_direct [5]
static const GLuint int_types_norm [5]
static const GLuint int_types_scale [5]
static const GLuint ushort_types_direct [5]
static const GLuint ushort_types_norm [5]
static const GLuint ushort_types_scale [5]
static const GLuint short_types_direct [5]
static const GLuint short_types_norm [5]
static const GLuint short_types_scale [5]
static const GLuint ubyte_types_direct [5]
static const GLuint ubyte_types_norm [5]
static const GLuint ubyte_types_scale [5]
static const GLuint byte_types_direct [5]
static const GLuint byte_types_norm [5]
static const GLuint byte_types_scale [5]
const struct brw_tracked_state brw_vertices
const struct brw_tracked_state brw_indices
const struct brw_tracked_state brw_index_buffer
Function Documentation
brw_emit_index_buffer()
static void brw_emit_index_buffer (struct brw_context * brw) static
References ADVANCE_BATCH, BEGIN_BATCH, BRW_CUT_INDEX_ENABLE, brw_get_index_type(), CMD_INDEX_BUFFER, brw_context::enable_cut_index, GLuint, brw_context::ib, brw_context::is_haswell, OUT_BATCH, OUT_RELOC, brw_context::prim_restart, and _mesa_index_buffer::type.
brw_emit_vertex_buffer_state()
uint32_t* brw_emit_vertex_buffer_state (struct brw_context * brw, unsigned buffer_nr, drm_intel_bo * bo, unsigned start_offset, unsigned end_offset, unsigned stride, unsigned step_rate, uint32_t * __map)
Emit a VERTEX_BUFFER_STATE entry (part of 3DSTATE_VERTEX_BUFFERS).
References BDW_MOCS_WB, BRW_VB0_ACCESS_INSTANCEDATA, BRW_VB0_ACCESS_VERTEXDATA, BRW_VB0_INDEX_SHIFT, BRW_VB0_PITCH_SHIFT, brw_context::ctx, brw_context::gen, GEN6_VB0_ACCESS_INSTANCEDATA, GEN6_VB0_ACCESS_VERTEXDATA, GEN6_VB0_INDEX_SHIFT, GEN7_MOCS_L3, GEN7_VB0_ADDRESS_MODIFYENABLE, OUT_BATCH, OUT_RELOC, OUT_RELOC64, and SKL_MOCS_WB.
brw_emit_vertices()
static void brw_emit_vertices (struct brw_context * brw) static
References _3DSTATE_VERTEX_BUFFERS, _3DSTATE_VERTEX_ELEMENTS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_vertex_buffer::bo, brw_emit_query_begin(), brw_get_vertex_surface_type(), brw_prepare_shader_draw_parameters(), brw_prepare_vertices(), BRW_VE0_FORMAT_SHIFT, BRW_VE0_INDEX_SHIFT, BRW_VE0_SRC_OFFSET_SHIFT, BRW_VE0_VALID, BRW_VE1_COMPONENT_0_SHIFT, BRW_VE1_COMPONENT_1_SHIFT, BRW_VE1_COMPONENT_2_SHIFT, BRW_VE1_COMPONENT_3_SHIFT, BRW_VE1_COMPONENT_STORE_0, BRW_VE1_COMPONENT_STORE_1_FLT, BRW_VE1_COMPONENT_STORE_1_INT, BRW_VE1_COMPONENT_STORE_IID, BRW_VE1_COMPONENT_STORE_SRC, BRW_VE1_COMPONENT_STORE_VID, BRW_VE1_DST_OFFSET_SHIFT, brw_vertex_element::buffer, brw_context::buffers, downsize_format_if_needed(), brw_context::draw, brw_context::draw_id_bo, brw_context::draw_id_offset, brw_context::draw_params_bo, brw_context::draw_params_offset, EMIT_VERTEX_BUFFER_STATE, brw_context::enabled, brw_context::gen, GEN6_VE0_EDGE_FLAG_ENABLE, GEN6_VE0_INDEX_SHIFT, GEN6_VE0_VALID, brw_vertex_element::glarray, GLuint, brw_context::inputs, gl_vertex_array::Integer, brw_context::is_baytrail, brw_context::is_haswell, is_passthru_format(), brw_context::nr_buffers, brw_context::nr_enabled, brw_vertex_buffer::offset, brw_vertex_element::offset, OUT_BATCH, brw_stage_state::prog_data, gl_vertex_array::Size, brw_vertex_buffer::size, brw_vertex_buffer::step_rate, brw_vertex_buffer::stride, upload_format_size(), uploads_needed(), brw_context::vb, and brw_context::vs.
brw_get_vertex_surface_type()
unsigned brw_get_vertex_surface_type (struct brw_context * brw, const struct gl_vertex_array * glarray)
Given vertex array type/size/format/normalized info, return the appopriate hardware surface type.
Format will be GL_RGBA or possibly GL_BGRA for GLubyte[4] color arrays.
References _mesa_enum_to_string(), byte_types_direct, byte_types_norm, byte_types_scale, double_types(), gl_vertex_array::Doubles, fixed_point_types, float_types, gl_vertex_array::Format, brw_context::gen, GL_HALF_FLOAT_OES, half_float_types, int_types_direct, int_types_norm, int_types_scale, gl_vertex_array::Integer, brw_context::is_baytrail, brw_context::is_haswell, gl_vertex_array::Normalized, short_types_direct, short_types_norm, short_types_scale, gl_vertex_array::Size, brw_context::size, gl_vertex_array::Type, ubyte_types_direct, ubyte_types_norm, ubyte_types_scale, uint_types_direct, uint_types_norm, uint_types_scale, ushort_types_direct, ushort_types_norm, and ushort_types_scale.
Referenced by brw_emit_vertices(), gen8_emit_vertices(), and key_debug().
brw_prepare_shader_draw_parameters()
void brw_prepare_shader_draw_parameters (struct brw_context * brw)
References brw_context::base, brw_context::draw, brw_context::draw_id_bo, brw_context::draw_id_offset, brw_context::draw_params_bo, brw_context::draw_params_offset, brw_context::gl_drawid, intel_upload_data(), brw_context::params, brw_stage_state::prog_data, and brw_context::vs.
Referenced by brw_emit_vertices(), and gen8_emit_vertices().
brw_prepare_vertices()
void brw_prepare_vertices (struct brw_context * brw)
References gl_vertex_array::_ElementSize, _mesa_bitcount_64(), gl_polygon_attrib::BackMode, intel_buffer_object::Base, brw_context::base, brw_context::baseinstance, brw_context::basevertex, BITFIELD64_BIT, BITFIELD64_MASK, brw_vertex_buffer::bo, brw_vertex_element::buffer, gl_vertex_array::BufferObj, brw_context::buffers, copy_array_to_vbo_array(), brw_context::ctx, brw_context::enabled, gl_polygon_attrib::FrontMode, brw_context::gen, brw_vertex_element::glarray, GLuint, if(), brw_context::index_bounds_valid, brw_context::inputs, gl_vertex_array::InstanceDivisor, intel_buffer_object(), intel_bufferobj_buffer(), brw_vertex_element::is_dual_slot, brw_context::max_index, brw_context::min_index, brw_context::nr_buffers, brw_context::nr_enabled, brw_context::num_instances, brw_vertex_buffer::offset, brw_vertex_element::offset, gl_context::Polygon, brw_stage_state::prog_data, gl_vertex_array::Ptr, gl_buffer_object::Size, brw_vertex_buffer::size, brw_context::start_vertex_bias, brw_vertex_buffer::step_rate, brw_vertex_buffer::stride, gl_vertex_array::StrideB, brw_context::vb, and brw_context::vs.
Referenced by brw_emit_vertices(), brw_get_index_type(), and gen8_emit_vertices().
brw_upload_indices()
static void brw_upload_indices (struct brw_context * brw) static
References _mesa_sizeof_type(), BRW_NEW_INDEX_BUFFER, _mesa_index_buffer::count, brw_context::ctx, gl_context::Driver, GLuint, brw_context::ib, intel_buffer_object(), intel_bufferobj_buffer(), intel_upload_data(), MAP_INTERNAL, dd_function_table::MapBufferRange, gl_context::NewDriverState, _mesa_index_buffer::obj, _mesa_index_buffer::ptr, gl_buffer_object::Size, _mesa_index_buffer::type, and dd_function_table::UnmapBuffer.
copy_array_to_vbo_array()
static void copy_array_to_vbo_array (struct brw_context * brw, struct brw_vertex_element * element, int min, int max, struct brw_vertex_buffer * buffer, GLuint dst_stride) static
References gl_vertex_array::_ElementSize, brw_vertex_buffer::bo, brw_vertex_element::glarray, GLuint, intel_upload_data(), intel_upload_space(), brw_vertex_buffer::offset, gl_vertex_array::Ptr, brw_vertex_buffer::size, brw_context::size, brw_vertex_buffer::stride, and gl_vertex_array::StrideB.
Referenced by brw_prepare_vertices().
double_types()
static GLuint double_types (struct brw_context * brw, int size, GLboolean doubles) static
References double_types_float, and double_types_passthru.
Referenced by brw_get_vertex_surface_type().
downsize_format_if_needed()
static uint32_t downsize_format_if_needed (uint32_t format, int upload) static
References is_passthru_format().
Referenced by brw_emit_vertices().
is_passthru_format()
static bool is_passthru_format (uint32_t format) static
Referenced by brw_emit_vertices(), downsize_format_if_needed(), and uploads_needed().
upload_format_size()
static int upload_format_size (uint32_t upload_format) static
Referenced by brw_emit_vertices().
uploads_needed()
static int uploads_needed (uint32_t format) static
References is_passthru_format().
Referenced by brw_emit_vertices().
Variable Documentation
brw_index_buffer
const struct brw_tracked_state brw_index_buffer
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_INDEX_BUFFER,
   },
   .emit = brw_emit_index_buffer,
}
brw_indices
const struct brw_tracked_state brw_indices
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_INDICES,
   },
   .emit = brw_upload_indices,
}
brw_vertices
const struct brw_tracked_state brw_vertices
Initial value:
= {
   .dirty = {
      .mesa = _NEW_POLYGON,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VERTICES |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = brw_emit_vertices,
}
byte_types_direct
const GLuint byte_types_direct[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R8_SINT,
   ISL_FORMAT_R8G8_SINT,
   ISL_FORMAT_R8G8B8_SINT,
   ISL_FORMAT_R8G8B8A8_SINT
}
Referenced by brw_get_vertex_surface_type().
byte_types_norm
const GLuint byte_types_norm[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R8_SNORM,
   ISL_FORMAT_R8G8_SNORM,
   ISL_FORMAT_R8G8B8_SNORM,
   ISL_FORMAT_R8G8B8A8_SNORM
}
Referenced by brw_get_vertex_surface_type().
byte_types_scale
const GLuint byte_types_scale[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R8_SSCALED,
   ISL_FORMAT_R8G8_SSCALED,
   ISL_FORMAT_R8G8B8_SSCALED,
   ISL_FORMAT_R8G8B8A8_SSCALED
}
Referenced by brw_get_vertex_surface_type().
double_types_float
const GLuint double_types_float[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R64_FLOAT,
   ISL_FORMAT_R64G64_FLOAT,
   ISL_FORMAT_R64G64B64_FLOAT,
   ISL_FORMAT_R64G64B64A64_FLOAT
}
Referenced by double_types().
double_types_passthru
const GLuint double_types_passthru[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R64_PASSTHRU,
   ISL_FORMAT_R64G64_PASSTHRU,
   ISL_FORMAT_R64G64B64_PASSTHRU,
   ISL_FORMAT_R64G64B64A64_PASSTHRU
}
Referenced by double_types().
fixed_point_types
const GLuint fixed_point_types[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_SFIXED,
   ISL_FORMAT_R32G32_SFIXED,
   ISL_FORMAT_R32G32B32_SFIXED,
   ISL_FORMAT_R32G32B32A32_SFIXED,
}
Referenced by brw_get_vertex_surface_type().
float_types
const GLuint float_types[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_FLOAT,
   ISL_FORMAT_R32G32_FLOAT,
   ISL_FORMAT_R32G32B32_FLOAT,
   ISL_FORMAT_R32G32B32A32_FLOAT
}
Referenced by brw_get_vertex_surface_type().
half_float_types
const GLuint half_float_types[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_FLOAT,
   ISL_FORMAT_R16G16_FLOAT,
   ISL_FORMAT_R16G16B16_FLOAT,
   ISL_FORMAT_R16G16B16A16_FLOAT
}
Referenced by brw_get_vertex_surface_type().
int_types_direct
const GLuint int_types_direct[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_SINT,
   ISL_FORMAT_R32G32_SINT,
   ISL_FORMAT_R32G32B32_SINT,
   ISL_FORMAT_R32G32B32A32_SINT
}
Referenced by brw_get_vertex_surface_type().
int_types_norm
const GLuint int_types_norm[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_SNORM,
   ISL_FORMAT_R32G32_SNORM,
   ISL_FORMAT_R32G32B32_SNORM,
   ISL_FORMAT_R32G32B32A32_SNORM
}
Referenced by brw_get_vertex_surface_type().
int_types_scale
const GLuint int_types_scale[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_SSCALED,
   ISL_FORMAT_R32G32_SSCALED,
   ISL_FORMAT_R32G32B32_SSCALED,
   ISL_FORMAT_R32G32B32A32_SSCALED
}
Referenced by brw_get_vertex_surface_type().
short_types_direct
const GLuint short_types_direct[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_SINT,
   ISL_FORMAT_R16G16_SINT,
   ISL_FORMAT_R16G16B16_SINT,
   ISL_FORMAT_R16G16B16A16_SINT
}
Referenced by brw_get_vertex_surface_type().
short_types_norm
const GLuint short_types_norm[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_SNORM,
   ISL_FORMAT_R16G16_SNORM,
   ISL_FORMAT_R16G16B16_SNORM,
   ISL_FORMAT_R16G16B16A16_SNORM
}
Referenced by brw_get_vertex_surface_type().
short_types_scale
const GLuint short_types_scale[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_SSCALED,
   ISL_FORMAT_R16G16_SSCALED,
   ISL_FORMAT_R16G16B16_SSCALED,
   ISL_FORMAT_R16G16B16A16_SSCALED
}
Referenced by brw_get_vertex_surface_type().
ubyte_types_direct
const GLuint ubyte_types_direct[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R8_UINT,
   ISL_FORMAT_R8G8_UINT,
   ISL_FORMAT_R8G8B8_UINT,
   ISL_FORMAT_R8G8B8A8_UINT
}
Referenced by brw_get_vertex_surface_type().
ubyte_types_norm
const GLuint ubyte_types_norm[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R8_UNORM,
   ISL_FORMAT_R8G8_UNORM,
   ISL_FORMAT_R8G8B8_UNORM,
   ISL_FORMAT_R8G8B8A8_UNORM
}
Referenced by brw_get_vertex_surface_type().
ubyte_types_scale
const GLuint ubyte_types_scale[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R8_USCALED,
   ISL_FORMAT_R8G8_USCALED,
   ISL_FORMAT_R8G8B8_USCALED,
   ISL_FORMAT_R8G8B8A8_USCALED
}
Referenced by brw_get_vertex_surface_type().
uint_types_direct
const GLuint uint_types_direct[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_UINT,
   ISL_FORMAT_R32G32_UINT,
   ISL_FORMAT_R32G32B32_UINT,
   ISL_FORMAT_R32G32B32A32_UINT
}
Referenced by brw_get_vertex_surface_type().
uint_types_norm
const GLuint uint_types_norm[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_UNORM,
   ISL_FORMAT_R32G32_UNORM,
   ISL_FORMAT_R32G32B32_UNORM,
   ISL_FORMAT_R32G32B32A32_UNORM
}
Referenced by brw_get_vertex_surface_type().
uint_types_scale
const GLuint uint_types_scale[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R32_USCALED,
   ISL_FORMAT_R32G32_USCALED,
   ISL_FORMAT_R32G32B32_USCALED,
   ISL_FORMAT_R32G32B32A32_USCALED
}
Referenced by brw_get_vertex_surface_type().
ushort_types_direct
const GLuint ushort_types_direct[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_UINT,
   ISL_FORMAT_R16G16_UINT,
   ISL_FORMAT_R16G16B16_UINT,
   ISL_FORMAT_R16G16B16A16_UINT
}
Referenced by brw_get_vertex_surface_type().
ushort_types_norm
const GLuint ushort_types_norm[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_UNORM,
   ISL_FORMAT_R16G16_UNORM,
   ISL_FORMAT_R16G16B16_UNORM,
   ISL_FORMAT_R16G16B16A16_UNORM
}
Referenced by brw_get_vertex_surface_type().
ushort_types_scale
const GLuint ushort_types_scale[5] static
Initial value:
= {
   0,
   ISL_FORMAT_R16_USCALED,
   ISL_FORMAT_R16G16_USCALED,
   ISL_FORMAT_R16G16B16_USCALED,
   ISL_FORMAT_R16G16B16A16_USCALED
}
Referenced by brw_get_vertex_surface_type().