Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_context.h File Reference
#include <stdbool.h>
#include "main/macros.h"
#include "main/mtypes.h"
#include "brw_structs.h"
#include "compiler/brw_compiler.h"
#include "isl/isl.h"
#include "blorp/blorp.h"
#include <intel_bufmgr.h>
#include "common/gen_debug.h"
#include "intel_screen.h"
#include "intel_tex_obj.h"
#include "intel_resolve_map.h"
Data Structures
struct brw_state_flags
struct brw_program
Subclass of Mesa program.
struct brw_sf_prog_data
struct brw_clip_prog_data
struct brw_ff_gs_prog_data
struct brw_cache
struct brw_tracked_state
struct brw_vertex_buffer
struct brw_vertex_element
struct brw_query_object
struct intel_batchbuffer
struct brw_transform_feedback_object
struct brw_stage_state
Data shared between each programmable stage in the pipeline (vs, gs, and wm).
struct brw_perf_query_info
struct brw_context
brw_context is derived from gl_context.
Macros
#define BRW_NEW_FS_PROG_DATA (1ull << BRW_CACHE_FS_PROG)
BRW_NEW_*_PROG_DATA and BRW_NEW_*_PROGRAM are similar, but distinct.
#define BRW_NEW_BLORP_BLIT_PROG_DATA (1ull << BRW_CACHE_BLORP_PROG)
#define BRW_NEW_SF_PROG_DATA (1ull << BRW_CACHE_SF_PROG)
#define BRW_NEW_VS_PROG_DATA (1ull << BRW_CACHE_VS_PROG)
#define BRW_NEW_FF_GS_PROG_DATA (1ull << BRW_CACHE_FF_GS_PROG)
#define BRW_NEW_GS_PROG_DATA (1ull << BRW_CACHE_GS_PROG)
#define BRW_NEW_TCS_PROG_DATA (1ull << BRW_CACHE_TCS_PROG)
#define BRW_NEW_TES_PROG_DATA (1ull << BRW_CACHE_TES_PROG)
#define BRW_NEW_CLIP_PROG_DATA (1ull << BRW_CACHE_CLIP_PROG)
#define BRW_NEW_CS_PROG_DATA (1ull << BRW_CACHE_CS_PROG)
#define BRW_NEW_URB_FENCE (1ull << BRW_STATE_URB_FENCE)
#define BRW_NEW_FRAGMENT_PROGRAM (1ull << BRW_STATE_FRAGMENT_PROGRAM)
#define BRW_NEW_GEOMETRY_PROGRAM (1ull << BRW_STATE_GEOMETRY_PROGRAM)
#define BRW_NEW_TESS_PROGRAMS (1ull << BRW_STATE_TESS_PROGRAMS)
#define BRW_NEW_VERTEX_PROGRAM (1ull << BRW_STATE_VERTEX_PROGRAM)
#define BRW_NEW_CURBE_OFFSETS (1ull << BRW_STATE_CURBE_OFFSETS)
#define BRW_NEW_REDUCED_PRIMITIVE (1ull << BRW_STATE_REDUCED_PRIMITIVE)
#define BRW_NEW_PATCH_PRIMITIVE (1ull << BRW_STATE_PATCH_PRIMITIVE)
#define BRW_NEW_PRIMITIVE (1ull << BRW_STATE_PRIMITIVE)
#define BRW_NEW_CONTEXT (1ull << BRW_STATE_CONTEXT)
#define BRW_NEW_PSP (1ull << BRW_STATE_PSP)
#define BRW_NEW_SURFACES (1ull << BRW_STATE_SURFACES)
#define BRW_NEW_BINDING_TABLE_POINTERS (1ull << BRW_STATE_BINDING_TABLE_POINTERS)
#define BRW_NEW_INDICES (1ull << BRW_STATE_INDICES)
#define BRW_NEW_VERTICES (1ull << BRW_STATE_VERTICES)
#define BRW_NEW_DEFAULT_TESS_LEVELS (1ull << BRW_STATE_DEFAULT_TESS_LEVELS)
#define BRW_NEW_BATCH (1ull << BRW_STATE_BATCH)
Used for any batch entry with a relocated pointer that will be used by any 3D rendering.
#define BRW_NEW_INDEX_BUFFER (1ull << BRW_STATE_INDEX_BUFFER)
#define BRW_NEW_VS_CONSTBUF (1ull << BRW_STATE_VS_CONSTBUF)
#define BRW_NEW_TCS_CONSTBUF (1ull << BRW_STATE_TCS_CONSTBUF)
#define BRW_NEW_TES_CONSTBUF (1ull << BRW_STATE_TES_CONSTBUF)
#define BRW_NEW_GS_CONSTBUF (1ull << BRW_STATE_GS_CONSTBUF)
#define BRW_NEW_PROGRAM_CACHE (1ull << BRW_STATE_PROGRAM_CACHE)
#define BRW_NEW_STATE_BASE_ADDRESS (1ull << BRW_STATE_STATE_BASE_ADDRESS)
#define BRW_NEW_VUE_MAP_GEOM_OUT (1ull << BRW_STATE_VUE_MAP_GEOM_OUT)
#define BRW_NEW_VIEWPORT_COUNT (1ull << BRW_STATE_VIEWPORT_COUNT)
#define BRW_NEW_TRANSFORM_FEEDBACK (1ull << BRW_STATE_TRANSFORM_FEEDBACK)
#define BRW_NEW_RASTERIZER_DISCARD (1ull << BRW_STATE_RASTERIZER_DISCARD)
#define BRW_NEW_STATS_WM (1ull << BRW_STATE_STATS_WM)
#define BRW_NEW_UNIFORM_BUFFER (1ull << BRW_STATE_UNIFORM_BUFFER)
#define BRW_NEW_ATOMIC_BUFFER (1ull << BRW_STATE_ATOMIC_BUFFER)
#define BRW_NEW_IMAGE_UNITS (1ull << BRW_STATE_IMAGE_UNITS)
#define BRW_NEW_META_IN_PROGRESS (1ull << BRW_STATE_META_IN_PROGRESS)
#define BRW_NEW_PUSH_CONSTANT_ALLOCATION (1ull << BRW_STATE_PUSH_CONSTANT_ALLOCATION)
#define BRW_NEW_NUM_SAMPLES (1ull << BRW_STATE_NUM_SAMPLES)
#define BRW_NEW_TEXTURE_BUFFER (1ull << BRW_STATE_TEXTURE_BUFFER)
#define BRW_NEW_GEN4_UNIT_STATE (1ull << BRW_STATE_GEN4_UNIT_STATE)
#define BRW_NEW_CC_VP (1ull << BRW_STATE_CC_VP)
#define BRW_NEW_SF_VP (1ull << BRW_STATE_SF_VP)
#define BRW_NEW_CLIP_VP (1ull << BRW_STATE_CLIP_VP)
#define BRW_NEW_SAMPLER_STATE_TABLE (1ull << BRW_STATE_SAMPLER_STATE_TABLE)
#define BRW_NEW_VS_ATTRIB_WORKAROUNDS (1ull << BRW_STATE_VS_ATTRIB_WORKAROUNDS)
#define BRW_NEW_COMPUTE_PROGRAM (1ull << BRW_STATE_COMPUTE_PROGRAM)
#define BRW_NEW_CS_WORK_GROUPS (1ull << BRW_STATE_CS_WORK_GROUPS)
#define BRW_NEW_URB_SIZE (1ull << BRW_STATE_URB_SIZE)
#define BRW_NEW_CC_STATE (1ull << BRW_STATE_CC_STATE)
#define BRW_NEW_BLORP (1ull << BRW_STATE_BLORP)
#define BRW_NEW_CONSERVATIVE_RASTERIZATION (1ull << BRW_STATE_CONSERVATIVE_RASTERIZATION)
#define BRW_MAX_TEX_UNIT 32
Number of texture sampler units.
#define BRW_MAX_UBO 14
Max number of UBOs in a shader.
#define BRW_MAX_SSBO 12
Max number of SSBOs in a shader.
#define BRW_MAX_ABO 16
Max number of atomic counter buffer objects in a shader.
#define BRW_MAX_IMAGES 32
Max number of image uniforms in a shader.
#define BRW_MAX_SOL_BUFFERS 4
Maximum number of actual buffers used for stream output.
#define BRW_MAX_SURFACES
#define BATCH_SZ (8192*sizeof(uint32_t))
#define BRW_MAX_XFB_STREAMS 4
Enumerations
enum brw_pipeline { BRW_RENDER_PIPELINE, BRW_COMPUTE_PIPELINE, BRW_NUM_PIPELINES }
enum brw_cache_id {
BRW_CACHE_FS_PROG, BRW_CACHE_BLORP_PROG, BRW_CACHE_SF_PROG, BRW_CACHE_VS_PROG,
BRW_CACHE_FF_GS_PROG, BRW_CACHE_GS_PROG, BRW_CACHE_TCS_PROG, BRW_CACHE_TES_PROG,
BRW_CACHE_CLIP_PROG, BRW_CACHE_CS_PROG, BRW_MAX_CACHE
}
enum brw_state_id {
BRW_STATE_URB_FENCE = BRW_MAX_CACHE, BRW_STATE_FRAGMENT_PROGRAM, BRW_STATE_GEOMETRY_PROGRAM, BRW_STATE_TESS_PROGRAMS,
BRW_STATE_VERTEX_PROGRAM, BRW_STATE_CURBE_OFFSETS, BRW_STATE_REDUCED_PRIMITIVE, BRW_STATE_PATCH_PRIMITIVE,
BRW_STATE_PRIMITIVE, BRW_STATE_CONTEXT, BRW_STATE_PSP, BRW_STATE_SURFACES,
BRW_STATE_BINDING_TABLE_POINTERS, BRW_STATE_INDICES, BRW_STATE_VERTICES, BRW_STATE_DEFAULT_TESS_LEVELS,
BRW_STATE_BATCH, BRW_STATE_INDEX_BUFFER, BRW_STATE_VS_CONSTBUF, BRW_STATE_TCS_CONSTBUF,
BRW_STATE_TES_CONSTBUF, BRW_STATE_GS_CONSTBUF, BRW_STATE_PROGRAM_CACHE, BRW_STATE_STATE_BASE_ADDRESS,
BRW_STATE_VUE_MAP_GEOM_OUT, BRW_STATE_TRANSFORM_FEEDBACK, BRW_STATE_RASTERIZER_DISCARD, BRW_STATE_STATS_WM,
BRW_STATE_UNIFORM_BUFFER, BRW_STATE_ATOMIC_BUFFER, BRW_STATE_IMAGE_UNITS, BRW_STATE_META_IN_PROGRESS,
BRW_STATE_PUSH_CONSTANT_ALLOCATION, BRW_STATE_NUM_SAMPLES, BRW_STATE_TEXTURE_BUFFER, BRW_STATE_GEN4_UNIT_STATE,
BRW_STATE_CC_VP, BRW_STATE_SF_VP, BRW_STATE_CLIP_VP, BRW_STATE_SAMPLER_STATE_TABLE,
BRW_STATE_VS_ATTRIB_WORKAROUNDS, BRW_STATE_COMPUTE_PROGRAM, BRW_STATE_CS_WORK_GROUPS, BRW_STATE_URB_SIZE,
BRW_STATE_CC_STATE, BRW_STATE_BLORP, BRW_STATE_VIEWPORT_COUNT, BRW_STATE_CONSERVATIVE_RASTERIZATION,
BRW_NUM_STATE_BITS
}
enum shader_time_shader_type {
ST_NONE, ST_VS, ST_TCS, ST_TES,
ST_GS, ST_FS8, ST_FS16, ST_CS
}
enum brw_gpu_ring { UNKNOWN_RING, RENDER_RING, BLT_RING }
enum brw_predicate_state { BRW_PREDICATE_STATE_RENDER, BRW_PREDICATE_STATE_DONT_RENDER, BRW_PREDICATE_STATE_USE_BIT }
enum brw_query_kind { OA_COUNTERS, PIPELINE_STATS }
enum { DRI_CONF_BO_REUSE_DISABLED, DRI_CONF_BO_REUSE_ALL }
Functions
void intelInitClearFuncs (struct dd_function_table *functions)
const char * brw_get_renderer_string (const struct intel_screen *screen)
void intel_update_renderbuffers (__DRIcontext *context, __DRIdrawable *drawable)
void intel_prepare_render (struct brw_context *brw)
intel_prepare_render should be called anywhere that curent read/drawbuffer state is required.
void intel_resolve_for_dri2_flush (struct brw_context *brw, __DRIdrawable *drawable)
GLboolean brwCreateContext (gl_api api, const struct gl_config *mesaVis, __DRIcontext *driContextPriv, unsigned major_version, unsigned minor_version, uint32_t flags, bool notify_reset, unsigned *error, void *sharedContextPrivate)
void brw_meta_resolve_color (struct brw_context *brw, struct intel_mipmap_tree *mt)
void brw_workaround_depthstencil_alignment (struct brw_context *brw, GLbitfield clear_mask)
void brw_init_object_purgeable_functions (struct dd_function_table *functions)
void brw_init_common_queryobj_functions (struct dd_function_table *functions)
void gen4_init_queryobj_functions (struct dd_function_table *functions)
void brw_emit_query_begin (struct brw_context *brw)
Record the PS_DEPTH_COUNT value (for occlusion queries) just before primitive drawing.
void brw_emit_query_end (struct brw_context *brw)
Called at batchbuffer flush to get an ending PS_DEPTH_COUNT (for non-hardware context platforms).
void brw_query_counter (struct gl_context *ctx, struct gl_query_object *q)
Driver hook for glQueryCounter().
bool brw_is_query_pipelined (struct brw_query_object *query)
Is this type of query written by PIPE_CONTROL?
uint64_t brw_timebase_scale (struct brw_context *brw, uint64_t gpu_timestamp)
uint64_t brw_raw_timestamp_delta (struct brw_context *brw, uint64_t time0, uint64_t time1)
void gen6_init_queryobj_functions (struct dd_function_table *functions)
gen6_queryobj.c
void brw_write_timestamp (struct brw_context *brw, drm_intel_bo *bo, int idx)
Emit PIPE_CONTROLs to write the current GPU timestamp into a buffer.
void brw_write_depth_count (struct brw_context *brw, drm_intel_bo *bo, int idx)
Emit PIPE_CONTROLs to write the PS_DEPTH_COUNT register into a buffer.
void hsw_overflow_result_to_gpr0 (struct brw_context *brw, struct brw_query_object *query, int count)
hsw_queryobj.c
void hsw_init_queryobj_functions (struct dd_function_table *functions)
void brw_init_conditional_render_functions (struct dd_function_table *functions)
brw_conditional_render.c
bool brw_check_conditional_render (struct brw_context *brw)
void brw_load_register_mem (struct brw_context *brw, uint32_t reg, drm_intel_bo *bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
intel_batchbuffer.c
void brw_load_register_mem64 (struct brw_context *brw, uint32_t reg, drm_intel_bo *bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
void brw_store_register_mem32 (struct brw_context *brw, drm_intel_bo *bo, uint32_t reg, uint32_t offset)
void brw_store_register_mem64 (struct brw_context *brw, drm_intel_bo *bo, uint32_t reg, uint32_t offset)
void brw_load_register_imm32 (struct brw_context *brw, uint32_t reg, uint32_t imm)
void brw_load_register_imm64 (struct brw_context *brw, uint32_t reg, uint64_t imm)
void brw_load_register_reg (struct brw_context *brw, uint32_t src, uint32_t dest)
void brw_load_register_reg64 (struct brw_context *brw, uint32_t src, uint32_t dest)
void brw_store_data_imm32 (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint32_t imm)
void brw_store_data_imm64 (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint64_t imm)
void brw_validate_textures (struct brw_context *brw)
Finalizes all textures, completing any rendering that needs to be done to prepare them.
static bool key_debug (struct brw_context *brw, const char *name, int a, int b)
void brwInitFragProgFuncs (struct dd_function_table *functions)
void brw_get_scratch_bo (struct brw_context *brw, drm_intel_bo **scratch_bo, int size)
void brw_alloc_stage_scratch (struct brw_context *brw, struct brw_stage_state *stage_state, unsigned per_thread_size, unsigned thread_count)
Reserve enough scratch space for the given stage to hold per_thread_size bytes times the given thread_count.
void brw_init_shader_time (struct brw_context *brw)
int brw_get_shader_time_index (struct brw_context *brw, struct gl_program *prog, enum shader_time_shader_type type, bool is_glsl_sh)
Chooses an index in the shader_time buffer and sets up tracking information for our printouts.
void brw_collect_and_report_shader_time (struct brw_context *brw)
void brw_destroy_shader_time (struct brw_context *brw)
void brw_upload_urb_fence (struct brw_context *brw)
void brw_upload_cs_urb_state (struct brw_context *brw)
Uploads the CS_URB_STATE packet.
gl_clip_plane * brw_select_clip_planes (struct gl_context *ctx)
Decide which set of clip planes should be used when clipping via gl_Position or gl_ClipVertex.
unsigned brw_get_vertex_surface_type (struct brw_context *brw, const struct gl_vertex_array *glarray)
Given vertex array type/size/format/normalized info, return the appopriate hardware surface type.
static unsigned brw_get_index_type (GLenum type)
void brw_prepare_vertices (struct brw_context *brw)
void brw_init_surface_formats (struct brw_context *brw)
void brw_create_constant_surface (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint32_t size, uint32_t *out_offset)
Create the constant buffer surface.
void brw_create_buffer_surface (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint32_t size, uint32_t *out_offset)
Create the buffer surface.
void brw_update_buffer_texture_surface (struct gl_context *ctx, unsigned unit, uint32_t *surf_offset)
void brw_update_sol_surface (struct brw_context *brw, struct gl_buffer_object *buffer_obj, uint32_t *out_offset, unsigned num_vector_components, unsigned stride_dwords, unsigned offset_dwords)
Set up a binding table entry for use by stream output logic (transform feedback).
void brw_upload_ubo_surfaces (struct brw_context *brw, struct gl_program *prog, struct brw_stage_state *stage_state, struct brw_stage_prog_data *prog_data)
void brw_upload_abo_surfaces (struct brw_context *brw, const struct gl_program *prog, struct brw_stage_state *stage_state, struct brw_stage_prog_data *prog_data)
void brw_upload_image_surfaces (struct brw_context *brw, const struct gl_program *prog, struct brw_stage_state *stage_state, struct brw_stage_prog_data *prog_data)
bool brw_render_target_supported (struct brw_context *brw, struct gl_renderbuffer *rb)
uint32_t brw_depth_format (struct brw_context *brw, mesa_format format)
Convert a MESA_FORMAT to the corresponding BRW_DEPTHFORMAT enum.
void brw_init_performance_queries (struct brw_context *brw)
int brw_bo_map (struct brw_context *brw, drm_intel_bo *bo, int write_enable, const char *bo_name)
Map a buffer object; issue performance warnings if mapping causes stalls.
int brw_bo_map_gtt (struct brw_context *brw, drm_intel_bo *bo, const char *bo_name)
void intelInitExtensions (struct gl_context *ctx)
Initializes potential list of extensions if ctx == NULL, or actually enables extensions for a context.
int intel_translate_shadow_compare_func (GLenum func)
int intel_translate_compare_func (GLenum func)
int intel_translate_stencil_op (GLenum op)
int intel_translate_logic_op (GLenum opcode)
void brw_init_syncobj_functions (struct dd_function_table *functions)
struct gl_transform_feedback_object * brw_new_transform_feedback (struct gl_context *ctx, GLuint name)
void brw_delete_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void brw_begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
void brw_end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void brw_pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void brw_resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void brw_save_primitives_written_counters (struct brw_context *brw, struct brw_transform_feedback_object *obj)
Store the SO_NUM_PRIMS_WRITTEN counters for each stream (4 uint64_t values) to prim_count_bo.
void brw_compute_xfb_vertices_written (struct brw_context *brw, struct brw_transform_feedback_object *obj)
Compute the number of vertices written by this transform feedback operation.
GLsizei brw_get_transform_feedback_vertex_count (struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint stream)
GetTransformFeedbackVertexCount() driver hook.
void gen7_begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
void gen7_end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void gen7_pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void gen7_resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void hsw_begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
BeginTransformFeedback() driver hook.
void hsw_end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
EndTransformFeedback() driver hook.
void hsw_pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
PauseTransformFeedback() driver hook.
void hsw_resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
ResumeTransformFeedback() driver hook.
GLbitfield brw_blorp_framebuffer (struct brw_context *brw, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
bool brw_blorp_copytexsubimage (struct brw_context *brw, struct gl_renderbuffer *src_rb, struct gl_texture_image *dst_image, int slice, int srcX0, int srcY0, int dstX0, int dstY0, int width, int height)
unsigned gen6_determine_sample_mask (struct brw_context *brw)
void gen6_emit_3dstate_multisample (struct brw_context *brw, unsigned num_samples)
3DSTATE_MULTISAMPLE
void gen6_emit_3dstate_sample_mask (struct brw_context *brw, unsigned mask)
3DSTATE_SAMPLE_MASK
void gen6_get_sample_position (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint index, GLfloat *result)
void gen6_set_sample_maps (struct gl_context *ctx)
Sample index layout shows the numbering of slots in a rectangular grid of samples with in a pixel.
void gen8_emit_3dstate_multisample (struct brw_context *brw, unsigned num_samp)
3DSTATE_MULTISAMPLE
void gen8_emit_3dstate_sample_pattern (struct brw_context *brw)
3DSTATE_SAMPLE_PATTERN
void gen7_emit_push_constant_state (struct brw_context *brw, unsigned vs_size, unsigned hs_size, unsigned ds_size, unsigned gs_size, unsigned fs_size)
void gen6_upload_urb (struct brw_context *brw, unsigned vs_size, bool gs_present, unsigned gs_size)
When the GS is not in use, we assign the entire URB space to the VS.
void gen7_upload_urb (struct brw_context *brw, unsigned vs_size, bool gs_present, bool tess_present)
GLenum brw_get_graphics_reset_status (struct gl_context *ctx)
Query information about GPU resets observed by this context.
void brw_check_for_reset (struct brw_context *brw)
void brw_init_compute_functions (struct dd_function_table *functions)
static struct brw_context * brw_context (struct gl_context *ctx)
static struct brw_program * brw_program (struct gl_program *p)
static const struct brw_program * brw_program_const (const struct gl_program *p)
static uint32_t brw_program_reloc (struct brw_context *brw, uint32_t state_offset, uint32_t prog_offset)
static bool brw_depth_writes_enabled (const struct brw_context *brw)
void brw_emit_depthbuffer (struct brw_context *brw)
void brw_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
void gen6_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
void gen7_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
void gen8_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
void gen8_hiz_exec (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Emit packets to perform a depth/HiZ resolve or fast depth/stencil clear.
uint32_t get_hw_prim_for_gl_prim (int mode)
void gen6_upload_push_constants (struct brw_context *brw, const struct gl_program *prog, const struct brw_stage_prog_data *prog_data, struct brw_stage_state *stage_state)
Creates a streamed BO containing the push constants for the VS or GS on gen6+.
bool gen9_use_linear_1d_layout (const struct brw_context *brw, const struct intel_mipmap_tree *mt)
int brw_init_pipe_control (struct brw_context *brw, const struct gen_device_info *info)
void brw_fini_pipe_control (struct brw_context *brw)
void brw_emit_pipe_control_flush (struct brw_context *brw, uint32_t flags)
Emit a PIPE_CONTROL with various flushing flags.
void brw_emit_pipe_control_write (struct brw_context *brw, uint32_t flags, drm_intel_bo *bo, uint32_t offset, uint32_t imm_lower, uint32_t imm_upper)
Emit a PIPE_CONTROL that writes to a buffer object.
void brw_emit_mi_flush (struct brw_context *brw)
void brw_emit_post_sync_nonzero_flush (struct brw_context *brw)
Emits a PIPE_CONTROL with a non-zero post-sync operation, for implementing two workarounds on gen6.
void brw_emit_depth_stall_flushes (struct brw_context *brw)
Restriction [DevSNB, DevIVB]:
void gen7_emit_vs_workaround_flush (struct brw_context *brw)
From the Ivybridge PRM, Volume 2 Part 1, Section 3.2 (VS Stage Input): "A PIPE_CONTROL with Post-Sync Operation set to 1h and a depth stall needs to be sent just prior to any 3DSTATE_VS, 3DSTATE_URB_VS, 3DSTATE_CONSTANT_VS, 3DSTATE_BINDING_TABLE_POINTER_VS, 3DSTATE_SAMPLER_STATE_POINTER_VS command.
void gen7_emit_cs_stall_flush (struct brw_context *brw)
Emit a PIPE_CONTROL command for gen7 with the CS Stall bit set.
void brw_query_internal_format (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint *params)
Variables
const char *const brw_vendor_string
Macro Definition Documentation
BATCH_SZ
#define BATCH_SZ (8192*sizeof(uint32_t))
Referenced by _intel_batchbuffer_flush_fence(), intel_batchbuffer_init(), intel_batchbuffer_require_space(), intel_batchbuffer_reset(), and intel_init_bufmgr().
BRW_MAX_ABO
#define BRW_MAX_ABO 16
Max number of atomic counter buffer objects in a shader.
Referenced by brw_initialize_context_constants().
BRW_MAX_IMAGES
#define BRW_MAX_IMAGES 32
Max number of image uniforms in a shader.
Referenced by brw_initialize_context_constants().
BRW_MAX_SOL_BUFFERS
#define BRW_MAX_SOL_BUFFERS 4
Maximum number of actual buffers used for stream output.
Referenced by brw_initialize_context_constants(), and gen7_upload_3dstate_so_decl_list().
BRW_MAX_SSBO
#define BRW_MAX_SSBO 12
Max number of SSBOs in a shader.
Referenced by brw_assign_common_binding_table_offsets(), and brw_initialize_context_constants().
BRW_MAX_SURFACES
#define BRW_MAX_SURFACES
Value:
(BRW_MAX_DRAW_BUFFERS +                      \
                            BRW_MAX_TEX_UNIT * 2 + /* normal, gather */ \
                            BRW_MAX_UBO +                               \
                            BRW_MAX_SSBO +                              \
                            BRW_MAX_ABO +                               \
                            BRW_MAX_IMAGES +                            \
                            2 + /* shader time, pull constants */       \
                            1 /* cs num work groups */)
Referenced by brw_assign_common_binding_table_offsets(), and brw_gs_upload_binding_table().
BRW_MAX_TEX_UNIT
#define BRW_MAX_TEX_UNIT 32
Number of texture sampler units.
Referenced by brw_dispatch_compute_common(), brw_initialize_context_constants(), and brw_try_draw_prims().
BRW_MAX_UBO
#define BRW_MAX_UBO 14
Max number of UBOs in a shader.
Referenced by brw_assign_common_binding_table_offsets(), and brw_initialize_context_constants().
BRW_MAX_XFB_STREAMS
#define BRW_MAX_XFB_STREAMS 4
Referenced by brw_begin_transform_feedback(), gen7_begin_transform_feedback(), hsw_begin_transform_feedback(), hsw_pause_transform_feedback(), hsw_resume_transform_feedback(), save_prim_start_values(), and tally_prims_written().
BRW_NEW_ATOMIC_BUFFER
#define BRW_NEW_ATOMIC_BUFFER (1ull << BRW_STATE_ATOMIC_BUFFER)
Referenced by alloc_buffer_object(), and brw_init_state().
BRW_NEW_BATCH
#define BRW_NEW_BATCH (1ull << BRW_STATE_BATCH)
Used for any batch entry with a relocated pointer that will be used by any 3D rendering.
Referenced by brw_new_batch(), and emit_l3_state().
BRW_NEW_BINDING_TABLE_POINTERS
#define BRW_NEW_BINDING_TABLE_POINTERS (1ull << BRW_STATE_BINDING_TABLE_POINTERS)
Referenced by brw_gs_upload_binding_table(), and brw_upload_binding_table().
BRW_NEW_BLORP
#define BRW_NEW_BLORP (1ull << BRW_STATE_BLORP)
Referenced by blorp_exec(), brw_upload_clip_prog(), and brw_upload_sf_prog().
BRW_NEW_BLORP_BLIT_PROG_DATA
#define BRW_NEW_BLORP_BLIT_PROG_DATA (1ull << BRW_CACHE_BLORP_PROG)
BRW_NEW_CC_STATE
#define BRW_NEW_CC_STATE (1ull << BRW_STATE_CC_STATE)
Referenced by brw_emit_select_pipeline().
BRW_NEW_CC_VP
#define BRW_NEW_CC_VP (1ull << BRW_STATE_CC_VP)
Referenced by brw_upload_cc_vp().
BRW_NEW_CLIP_PROG_DATA
#define BRW_NEW_CLIP_PROG_DATA (1ull << BRW_CACHE_CLIP_PROG)
BRW_NEW_CLIP_VP
#define BRW_NEW_CLIP_VP (1ull << BRW_STATE_CLIP_VP)
Referenced by gen6_upload_sf_and_clip_viewports().
BRW_NEW_COMPUTE_PROGRAM
#define BRW_NEW_COMPUTE_PROGRAM (1ull << BRW_STATE_COMPUTE_PROGRAM)
Referenced by brw_upload_cs_prog(), and brw_upload_pipeline_state().
BRW_NEW_CONSERVATIVE_RASTERIZATION
#define BRW_NEW_CONSERVATIVE_RASTERIZATION (1ull << BRW_STATE_CONSERVATIVE_RASTERIZATION)
Referenced by brw_init_state().
BRW_NEW_CONTEXT
#define BRW_NEW_CONTEXT (1ull << BRW_STATE_CONTEXT)
Referenced by blorp_emit_urb_config(), brw_new_batch(), and gen7_upload_urb().
BRW_NEW_CS_PROG_DATA
#define BRW_NEW_CS_PROG_DATA (1ull << BRW_CACHE_CS_PROG)
BRW_NEW_CS_WORK_GROUPS
#define BRW_NEW_CS_WORK_GROUPS (1ull << BRW_STATE_CS_WORK_GROUPS)
Referenced by brw_dispatch_compute(), and brw_dispatch_compute_indirect().
BRW_NEW_CURBE_OFFSETS
#define BRW_NEW_CURBE_OFFSETS (1ull << BRW_STATE_CURBE_OFFSETS)
Referenced by calculate_curbe_offsets().
BRW_NEW_DEFAULT_TESS_LEVELS
#define BRW_NEW_DEFAULT_TESS_LEVELS (1ull << BRW_STATE_DEFAULT_TESS_LEVELS)
Referenced by brw_init_state().
BRW_NEW_FF_GS_PROG_DATA
#define BRW_NEW_FF_GS_PROG_DATA (1ull << BRW_CACHE_FF_GS_PROG)
Referenced by brw_upload_ff_gs_prog().
BRW_NEW_FRAGMENT_PROGRAM
#define BRW_NEW_FRAGMENT_PROGRAM (1ull << BRW_STATE_FRAGMENT_PROGRAM)
Referenced by brw_upload_pipeline_state(), brw_wm_state_dirty(), and brwProgramStringNotify().
BRW_NEW_FS_PROG_DATA
#define BRW_NEW_FS_PROG_DATA (1ull << BRW_CACHE_FS_PROG)
BRW_NEW_*_PROG_DATA and BRW_NEW_*_PROGRAM are similar, but distinct.
BRW_NEW_*_PROGRAM relates to the gl_shader_program/gl_program structures. When the currently bound shader program differs from the previous draw call, these will be flagged. They cover brw->{stage}_program and ctx->{Stage}Program->_Current.
BRW_NEW_*_PROG_DATA is flagged when the effective shaders change, from a driver perspective. Even if the same shader is bound at the API level, we may need to switch between multiple versions of that shader to handle changes in non-orthagonal state.
Additionally, multiple shader programs may have identical vertex shaders (for example), or compile down to the same code in the backend. We combine those into a single program cache entry.
BRW_NEW_*_PROG_DATA occurs when switching program cache entries, which covers the brw_*_prog_data structures, and brw->*.prog_offset.
Referenced by brw_upload_clip_prog(), and brw_upload_sf_prog().
BRW_NEW_GEN4_UNIT_STATE
#define BRW_NEW_GEN4_UNIT_STATE (1ull << BRW_STATE_GEN4_UNIT_STATE)
Referenced by brw_upload_clip_unit(), brw_upload_gs_unit(), brw_upload_vs_unit(), brw_upload_wm_unit(), upload_cc_unit(), and upload_sf_unit().
BRW_NEW_GEOMETRY_PROGRAM
#define BRW_NEW_GEOMETRY_PROGRAM (1ull << BRW_STATE_GEOMETRY_PROGRAM)
Referenced by brw_gs_state_dirty(), and brw_upload_pipeline_state().
BRW_NEW_GS_CONSTBUF
#define BRW_NEW_GS_CONSTBUF (1ull << BRW_STATE_GS_CONSTBUF)
Referenced by brw_upload_gs_pull_constants().
BRW_NEW_GS_PROG_DATA
#define BRW_NEW_GS_PROG_DATA (1ull << BRW_CACHE_GS_PROG)
BRW_NEW_IMAGE_UNITS
#define BRW_NEW_IMAGE_UNITS (1ull << BRW_STATE_IMAGE_UNITS)
Referenced by brw_init_state().
BRW_NEW_INDEX_BUFFER
#define BRW_NEW_INDEX_BUFFER (1ull << BRW_STATE_INDEX_BUFFER)
See also
brw.state.depth_region
Referenced by brw_upload_indices().
BRW_NEW_INDICES
#define BRW_NEW_INDICES (1ull << BRW_STATE_INDICES)
Referenced by brw_try_draw_prims().
BRW_NEW_META_IN_PROGRESS
#define BRW_NEW_META_IN_PROGRESS (1ull << BRW_STATE_META_IN_PROGRESS)
Referenced by brw_upload_pipeline_state().
BRW_NEW_NUM_SAMPLES
#define BRW_NEW_NUM_SAMPLES (1ull << BRW_STATE_NUM_SAMPLES)
Referenced by brw_upload_pipeline_state().
BRW_NEW_PATCH_PRIMITIVE
#define BRW_NEW_PATCH_PRIMITIVE (1ull << BRW_STATE_PATCH_PRIMITIVE)
Referenced by brw_upload_tcs_prog(), and gen6_set_prim().
BRW_NEW_PRIMITIVE
#define BRW_NEW_PRIMITIVE (1ull << BRW_STATE_PRIMITIVE)
Referenced by brw_ff_gs_state_dirty(), brw_set_prim(), and gen6_set_prim().
BRW_NEW_PROGRAM_CACHE
#define BRW_NEW_PROGRAM_CACHE (1ull << BRW_STATE_PROGRAM_CACHE)
Referenced by brw_cache_new_bo().
BRW_NEW_PSP
#define BRW_NEW_PSP (1ull << BRW_STATE_PSP)
Referenced by upload_pipelined_state_pointers().
BRW_NEW_PUSH_CONSTANT_ALLOCATION
#define BRW_NEW_PUSH_CONSTANT_ALLOCATION (1ull << BRW_STATE_PUSH_CONSTANT_ALLOCATION)
Referenced by gen7_allocate_push_constants().
BRW_NEW_RASTERIZER_DISCARD
#define BRW_NEW_RASTERIZER_DISCARD (1ull << BRW_STATE_RASTERIZER_DISCARD)
Referenced by brw_init_state(), gen6_begin_query(), and gen6_end_query().
BRW_NEW_REDUCED_PRIMITIVE
#define BRW_NEW_REDUCED_PRIMITIVE (1ull << BRW_STATE_REDUCED_PRIMITIVE)
Referenced by brw_set_prim(), brw_upload_clip_prog(), brw_upload_sf_prog(), and brw_wm_state_dirty().
BRW_NEW_SAMPLER_STATE_TABLE
#define BRW_NEW_SAMPLER_STATE_TABLE (1ull << BRW_STATE_SAMPLER_STATE_TABLE)
Referenced by brw_upload_sampler_state_table().
BRW_NEW_SF_PROG_DATA
#define BRW_NEW_SF_PROG_DATA (1ull << BRW_CACHE_SF_PROG)
BRW_NEW_SF_VP
#define BRW_NEW_SF_VP (1ull << BRW_STATE_SF_VP)
Referenced by gen6_upload_sf_and_clip_viewports(), and upload_sf_vp().
BRW_NEW_STATE_BASE_ADDRESS
#define BRW_NEW_STATE_BASE_ADDRESS (1ull << BRW_STATE_STATE_BASE_ADDRESS)
Referenced by brw_upload_state_base_address().
BRW_NEW_STATS_WM
#define BRW_NEW_STATS_WM (1ull << BRW_STATE_STATS_WM)
Referenced by brw_begin_query(), brw_end_query(), and brw_wm_state_dirty().
BRW_NEW_SURFACES
#define BRW_NEW_SURFACES (1ull << BRW_STATE_SURFACES)
Referenced by brw_update_cs_texture_surfaces(), brw_update_texture_surfaces(), brw_upload_abo_surfaces(), brw_upload_cs_pull_constants(), brw_upload_cs_work_groups_surface(), brw_upload_image_surfaces(), brw_upload_ubo_surfaces(), brw_upload_wm_pull_constants(), gen6_update_sol_surfaces(), gen7_upload_constant_state(), update_renderbuffer_read_surfaces(), and update_renderbuffer_surfaces().
BRW_NEW_TCS_CONSTBUF
#define BRW_NEW_TCS_CONSTBUF (1ull << BRW_STATE_TCS_CONSTBUF)
Referenced by brw_upload_tcs_pull_constants().
BRW_NEW_TCS_PROG_DATA
#define BRW_NEW_TCS_PROG_DATA (1ull << BRW_CACHE_TCS_PROG)
BRW_NEW_TES_CONSTBUF
#define BRW_NEW_TES_CONSTBUF (1ull << BRW_STATE_TES_CONSTBUF)
Referenced by brw_upload_tes_pull_constants().
BRW_NEW_TES_PROG_DATA
#define BRW_NEW_TES_PROG_DATA (1ull << BRW_CACHE_TES_PROG)
BRW_NEW_TESS_PROGRAMS
#define BRW_NEW_TESS_PROGRAMS (1ull << BRW_STATE_TESS_PROGRAMS)
Referenced by brw_upload_pipeline_state(), brw_upload_tcs_prog(), and brw_upload_tes_prog().
BRW_NEW_TEXTURE_BUFFER
#define BRW_NEW_TEXTURE_BUFFER (1ull << BRW_STATE_TEXTURE_BUFFER)
Referenced by alloc_buffer_object(), and brw_init_state().
BRW_NEW_TRANSFORM_FEEDBACK
#define BRW_NEW_TRANSFORM_FEEDBACK (1ull << BRW_STATE_TRANSFORM_FEEDBACK)
Referenced by brw_ff_gs_state_dirty(), brw_gs_state_dirty(), brw_init_state(), and brw_upload_gs_prog().
BRW_NEW_UNIFORM_BUFFER
#define BRW_NEW_UNIFORM_BUFFER (1ull << BRW_STATE_UNIFORM_BUFFER)
Referenced by alloc_buffer_object(), and brw_init_state().
BRW_NEW_URB_FENCE
#define BRW_NEW_URB_FENCE (1ull << BRW_STATE_URB_FENCE)
Referenced by recalculate_urb_fence().
BRW_NEW_URB_SIZE
#define BRW_NEW_URB_SIZE (1ull << BRW_STATE_URB_SIZE)
Referenced by blorp_emit_urb_config(), gen7_upload_urb(), and update_urb_size().
BRW_NEW_VERTEX_PROGRAM
#define BRW_NEW_VERTEX_PROGRAM (1ull << BRW_STATE_VERTEX_PROGRAM)
Referenced by brw_upload_pipeline_state(), brw_vs_state_dirty(), and brwProgramStringNotify().
BRW_NEW_VERTICES
#define BRW_NEW_VERTICES (1ull << BRW_STATE_VERTICES)
Referenced by brw_try_draw_prims().
BRW_NEW_VIEWPORT_COUNT
#define BRW_NEW_VIEWPORT_COUNT (1ull << BRW_STATE_VIEWPORT_COUNT)
Referenced by brw_upload_programs().
BRW_NEW_VS_ATTRIB_WORKAROUNDS
#define BRW_NEW_VS_ATTRIB_WORKAROUNDS (1ull << BRW_STATE_VS_ATTRIB_WORKAROUNDS)
Referenced by brw_merge_inputs(), and brw_vs_state_dirty().
BRW_NEW_VS_CONSTBUF
#define BRW_NEW_VS_CONSTBUF (1ull << BRW_STATE_VS_CONSTBUF)
Referenced by brw_upload_vs_pull_constants().
BRW_NEW_VS_PROG_DATA
#define BRW_NEW_VS_PROG_DATA (1ull << BRW_CACHE_VS_PROG)
Referenced by brw_ff_gs_state_dirty().
BRW_NEW_VUE_MAP_GEOM_OUT
#define BRW_NEW_VUE_MAP_GEOM_OUT (1ull << BRW_STATE_VUE_MAP_GEOM_OUT)
Referenced by brw_upload_clip_prog(), brw_upload_programs(), brw_upload_sf_prog(), and brw_wm_state_dirty().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DRI_CONF_BO_REUSE_DISABLED
DRI_CONF_BO_REUSE_ALL
brw_cache_id
enum brw_cache_id
Enumerator
BRW_CACHE_FS_PROG
BRW_CACHE_BLORP_PROG
BRW_CACHE_SF_PROG
BRW_CACHE_VS_PROG
BRW_CACHE_FF_GS_PROG
BRW_CACHE_GS_PROG
BRW_CACHE_TCS_PROG
BRW_CACHE_TES_PROG
BRW_CACHE_CLIP_PROG
BRW_CACHE_CS_PROG
BRW_MAX_CACHE
brw_gpu_ring
enum brw_gpu_ring
Enumerator
UNKNOWN_RING
RENDER_RING
BLT_RING
brw_pipeline
enum brw_pipeline
Enumerator
BRW_RENDER_PIPELINE
BRW_COMPUTE_PIPELINE
BRW_NUM_PIPELINES
brw_predicate_state
enum brw_predicate_state
Enumerator
BRW_PREDICATE_STATE_RENDER
BRW_PREDICATE_STATE_DONT_RENDER
BRW_PREDICATE_STATE_USE_BIT
brw_query_kind
enum brw_query_kind
Enumerator
OA_COUNTERS
PIPELINE_STATS
brw_state_id
enum brw_state_id
Enumerator
BRW_STATE_URB_FENCE
BRW_STATE_FRAGMENT_PROGRAM
BRW_STATE_GEOMETRY_PROGRAM
BRW_STATE_TESS_PROGRAMS
BRW_STATE_VERTEX_PROGRAM
BRW_STATE_CURBE_OFFSETS
BRW_STATE_REDUCED_PRIMITIVE
BRW_STATE_PATCH_PRIMITIVE
BRW_STATE_PRIMITIVE
BRW_STATE_CONTEXT
BRW_STATE_PSP
BRW_STATE_SURFACES
BRW_STATE_BINDING_TABLE_POINTERS
BRW_STATE_INDICES
BRW_STATE_VERTICES
BRW_STATE_DEFAULT_TESS_LEVELS
BRW_STATE_BATCH
BRW_STATE_INDEX_BUFFER
BRW_STATE_VS_CONSTBUF
BRW_STATE_TCS_CONSTBUF
BRW_STATE_TES_CONSTBUF
BRW_STATE_GS_CONSTBUF
BRW_STATE_PROGRAM_CACHE
BRW_STATE_STATE_BASE_ADDRESS
BRW_STATE_VUE_MAP_GEOM_OUT
BRW_STATE_TRANSFORM_FEEDBACK
BRW_STATE_RASTERIZER_DISCARD
BRW_STATE_STATS_WM
BRW_STATE_UNIFORM_BUFFER
BRW_STATE_ATOMIC_BUFFER
BRW_STATE_IMAGE_UNITS
BRW_STATE_META_IN_PROGRESS
BRW_STATE_PUSH_CONSTANT_ALLOCATION
BRW_STATE_NUM_SAMPLES
BRW_STATE_TEXTURE_BUFFER
BRW_STATE_GEN4_UNIT_STATE
BRW_STATE_CC_VP
BRW_STATE_SF_VP
BRW_STATE_CLIP_VP
BRW_STATE_SAMPLER_STATE_TABLE
BRW_STATE_VS_ATTRIB_WORKAROUNDS
BRW_STATE_COMPUTE_PROGRAM
BRW_STATE_CS_WORK_GROUPS
BRW_STATE_URB_SIZE
BRW_STATE_CC_STATE
BRW_STATE_BLORP
BRW_STATE_VIEWPORT_COUNT
BRW_STATE_CONSERVATIVE_RASTERIZATION
BRW_NUM_STATE_BITS
shader_time_shader_type
enum shader_time_shader_type
Enumerator
ST_NONE
ST_VS
ST_TCS
ST_TES
ST_GS
ST_FS8
ST_FS16
ST_CS
Function Documentation
brw_alloc_stage_scratch()
void brw_alloc_stage_scratch (struct brw_context * brw, struct brw_stage_state * stage_state, unsigned per_thread_size, unsigned thread_count)
Reserve enough scratch space for the given stage to hold per_thread_size bytes times the given thread_count.
References brw_context::bufmgr, brw_stage_state::per_thread_scratch, and brw_stage_state::scratch_bo.
Referenced by brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), and key_debug().
brw_begin_transform_feedback()
void brw_begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj)
References _3DSTATE_GS_SVB_INDEX, _mesa_compute_max_transform_feedback_vertices(), gl_context::_Shader, ADVANCE_BATCH, BEGIN_BATCH, brw_compute_xfb_vertices_written(), brw_context(), BRW_MAX_XFB_STREAMS, brw_save_primitives_written_counters(), gl_transform_feedback_state::CurrentObject, gl_pipeline_object::CurrentProgram, brw_context::gen, brw_transform_feedback_object::max_index, OUT_BATCH, brw_transform_feedback_object::primitive_mode, brw_transform_feedback_object::prims_generated, gl_program::sh, SVB_INDEX_SHIFT, and gl_context::TransformFeedback.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_blorp_copytexsubimage()
bool brw_blorp_copytexsubimage (struct brw_context * brw, struct gl_renderbuffer * src_rb, struct gl_texture_image * dst_image, int slice, int srcX0, int srcY0, int dstX0, int dstY0, int width, int height)
References gl_context::_ImageTransferState, _mesa_get_format_base_format(), _mesa_get_format_bits(), gl_framebuffer::Attachment, blorp_get_texture_swizzle(), brw_blorp_blit_miptrees(), BUFFER_STENCIL, brw_context::ctx, gl_texture_image::Face, gl_renderbuffer::Format, brw_context::format_supported_as_render_target, brw_context::gen, gl_renderbuffer::Height, intel_prepare_render(), intel_renderbuffer(), intel_texture_image(), gl_texture_image::Level, MESA_FORMAT_Z24_UNORM_X8_UINT, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_renderbuffer::mt, intel_texture_image::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_texture_image::TexFormat, and gl_texture_image::TexObject.
Referenced by brw_get_index_type(), and intelCopyTexSubImage().
brw_blorp_framebuffer()
GLbitfield brw_blorp_framebuffer (struct brw_context * brw, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
References brw_context::gen, and try_blorp_blit().
Referenced by brw_get_index_type(), and intel_blit_framebuffer().
brw_bo_map()
int brw_bo_map (struct brw_context * brw, drm_intel_bo * bo, int write_enable, const char * bo_name)
Map a buffer object; issue performance warnings if mapping causes stalls.
This matches the drm_intel_bo_map API, but takes an additional human-readable name for the buffer object to use in the performance debug message.
References get_time(), brw_context::perf_debug, and ret().
Referenced by brw_get_index_type(), brw_map_buffer_range(), gen6_queryobj_get_results(), intel_gettexsubimage_tiled_memcpy(), intel_miptree_map_raw(), intel_readpixels_tiled_memcpy(), and intel_texsubimage_tiled_memcpy().
brw_bo_map_gtt()
int brw_bo_map_gtt (struct brw_context * brw, drm_intel_bo * bo, const char * bo_name)
References get_time(), brw_context::perf_debug, and ret().
Referenced by brw_get_index_type(), intel_miptree_init_mcs(), and intel_miptree_map_raw().
brw_check_conditional_render()
bool brw_check_conditional_render (struct brw_context * brw)
References _mesa_check_conditional_render(), BRW_PREDICATE_STATE_DONT_RENDER, can_do_mi_math_and_lrr(), gl_query_state::CondRenderQuery, brw_context::ctx, brw_context::predicate, gl_context::Query, brw_context::screen, brw_context::state, brw_context::supported, and gl_query_object::Target.
Referenced by brw_draw_prims().
brw_check_for_reset()
void brw_check_for_reset (struct brw_context * brw)
References _mesa_set_context_lost_dispatch(), brw_context::ctx, brw_context::hw_ctx, and brw_context::reset_count.
Referenced by brw_get_index_type(), and do_flush_locked().
brw_collect_and_report_shader_time()
void brw_collect_and_report_shader_time (struct brw_context * brw)
References brw_collect_shader_time(), brw_report_shader_time(), get_time(), brw_context::report_time, and brw_context::shader_time.
Referenced by brw_new_batch(), intelDestroyContext(), and key_debug().
brw_compute_xfb_vertices_written()
void brw_compute_xfb_vertices_written (struct brw_context * brw, struct brw_transform_feedback_object * obj)
Compute the number of vertices written by this transform feedback operation.
References brw_transform_feedback_object::base, compute_vertices_written_so_far(), gl_transform_feedback_object::EndedAnytime, brw_transform_feedback_object::vertices_written, and brw_transform_feedback_object::vertices_written_valid.
Referenced by brw_begin_transform_feedback(), brw_get_index_type(), brw_get_transform_feedback_vertex_count(), and gen7_begin_transform_feedback().
brw_context()
static struct brw_context* brw_context (struct gl_context * ctx) static
References brw_context::ctx.
Referenced by brw_begin_conditional_render(), brw_begin_perf_query(), brw_begin_query(), brw_begin_transform_feedback(), brw_blend_barrier(), brw_buffer_data(), brw_buffer_subdata(), brw_check_query(), brw_clear(), brw_copy_buffer_subdata(), brw_cs_precompile(), brw_delete_perf_query(), brw_dispatch_compute(), brw_dispatch_compute_common(), brw_dispatch_compute_indirect(), brw_draw_prims(), brw_end_conditional_render(), brw_end_perf_query(), brw_end_query(), brw_end_transform_feedback(), brw_fast_clear_depth(), brw_flush_mapped_buffer_range(), brw_fs_precompile(), brw_get_buffer_subdata(), brw_get_graphics_reset_status(), brw_get_perf_counter_info(), brw_get_perf_query_data(), brw_get_perf_query_info(), brw_get_timestamp(), brw_get_transform_feedback_vertex_count(), brw_gl_client_wait_sync(), brw_gl_fence_sync(), brw_gl_server_wait_sync(), brw_gs_precompile(), brw_handle_primitive_restart(), brw_init_perf_query_info(), brw_is_perf_query_ready(), brw_link_shader(), brw_map_buffer_range(), brw_memory_barrier(), brw_new_perf_query_object(), brw_new_transform_feedback(), brw_pause_transform_feedback(), brw_populate_sampler_prog_key_data(), brw_query_counter(), brw_query_samples_for_format(), brw_queryobj_get_results(), brw_resume_transform_feedback(), brw_tcs_precompile(), brw_tes_precompile(), brw_try_draw_prims(), brw_unmap_buffer(), brw_update_buffer_texture_surface(), brw_update_texture_surface(), brw_vs_precompile(), brw_wait_perf_query(), brw_wait_query(), brwDeleteProgram(), brwNewProgram(), brwProgramStringNotify(), can_cut_index_handle_prims(), do_blit_bitmap(), do_blit_copypixels(), do_blit_drawpixels(), ensure_bo_has_space(), gen6_begin_query(), gen6_check_query(), gen6_end_query(), gen6_query_counter(), gen6_queryobj_get_results(), gen6_wait_query(), gen7_begin_transform_feedback(), gen7_end_transform_feedback(), gen7_pause_transform_feedback(), gen7_resume_transform_feedback(), hsw_begin_transform_feedback(), hsw_end_transform_feedback(), hsw_pause_transform_feedback(), hsw_result_to_gpr0(), hsw_resume_transform_feedback(), hsw_store_query_result(), intel_alloc_private_renderbuffer_storage(), intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_blit_framebuffer(), intel_blit_framebuffer_with_blitter(), intel_copy_image_sub_data(), intel_finish(), intel_flush_front(), intel_get_string(), intel_get_tex_sub_image(), intel_gettexsubimage_tiled_memcpy(), intel_glFlush(), intel_image_target_renderbuffer_storage(), intel_image_target_texture_2d(), intel_map_renderbuffer(), intel_map_texture_image(), intel_readpixels_tiled_memcpy(), intel_render_texture(), intel_renderbuffer_format(), intel_set_texture_storage_for_buffer_object(), intel_texsubimage_tiled_memcpy(), intel_texture_barrier(), intel_texture_view(), intel_unmap_renderbuffer(), intel_unmap_texture_image(), intel_update_framebuffer(), intel_update_state(), intel_validate_framebuffer(), intel_viewport(), intelCopyTexSubImage(), intelDrawBuffer(), intelDrawPixels(), intelInitExtensions(), intelMakeCurrent(), intelReadBuffer(), intelReadPixels(), and write_xfb_overflow_streams().
brw_create_buffer_surface()
void brw_create_buffer_surface (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint32_t size, uint32_t * out_offset)
Create the buffer surface.
Shader buffer variables will be read from / write to this buffer with Data Port Read/Write instructions/messages.
References brw_emit_buffer_surface_state().
Referenced by brw_get_index_type(), and brw_upload_ubo_surfaces().
brw_create_constant_surface()
void brw_create_constant_surface (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint32_t size, uint32_t * out_offset)
Create the constant buffer surface.
Vertex/fragment shader constants will be read from this buffer with Data Port Read instructions/messages.
References brw_emit_buffer_surface_state().
Referenced by brw_get_index_type(), brw_upload_pull_constants(), and brw_upload_ubo_surfaces().
brw_delete_transform_feedback()
void brw_delete_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References gl_transform_feedback_object::Buffers, brw_transform_feedback_object::offset_bo, and brw_transform_feedback_object::prim_count_bo.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_depth_format()
uint32_t brw_depth_format (struct brw_context * brw, mesa_format format)
Convert a MESA_FORMAT to the corresponding BRW_DEPTHFORMAT enum.
References BRW_DEPTHFORMAT_D16_UNORM, BRW_DEPTHFORMAT_D24_UNORM_S8_UINT, BRW_DEPTHFORMAT_D24_UNORM_X8_UINT, BRW_DEPTHFORMAT_D32_FLOAT, BRW_DEPTHFORMAT_D32_FLOAT_S8X24_UINT, brw_context::gen, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, and MESA_FORMAT_Z_UNORM16.
Referenced by brw_depthbuffer_format(), brw_get_index_type(), and gen8_hiz_exec().
brw_depth_writes_enabled()
static bool brw_depth_writes_enabled (const struct brw_context * brw) inline static
References brw_emit_depth_stall_flushes(), brw_emit_depth_stencil_hiz(), brw_emit_depthbuffer(), brw_emit_mi_flush(), brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), brw_emit_post_sync_nonzero_flush(), brw_fini_pipe_control(), brw_init_pipe_control(), brw_query_internal_format(), brw_context::ctx, gl_context::Depth, gl_depthbuffer_attrib::Func, gen6_emit_depth_stencil_hiz(), gen6_upload_push_constants(), gen7_emit_cs_stall_flush(), gen7_emit_depth_stencil_hiz(), gen7_emit_vs_workaround_flush(), gen8_emit_depth_stencil_hiz(), gen8_hiz_exec(), gen9_use_linear_1d_layout(), get_hw_prim_for_gl_prim(), gl_depthbuffer_attrib::Mask, and gl_depthbuffer_attrib::Test.
Referenced by brw_postdraw_set_buffers_need_resolve(), brw_wm_populate_key(), gen6_upload_depth_stencil_state(), gen7_emit_depth_stencil_hiz(), gen8_emit_depth_stencil_hiz(), gen8_upload_wm_depth_stencil(), pma_fix_enable(), and upload_cc_unit().
brw_destroy_shader_time()
void brw_destroy_shader_time (struct brw_context * brw)
References brw_context::bo, and brw_context::shader_time.
Referenced by intelDestroyContext(), and key_debug().
brw_emit_depth_stall_flushes()
void brw_emit_depth_stall_flushes (struct brw_context * brw)
Restriction [DevSNB, DevIVB]:
Prior to changing Depth/Stencil Buffer state (i.e. any combination of 3DSTATE_DEPTH_BUFFER, 3DSTATE_CLEAR_PARAMS, 3DSTATE_STENCIL_BUFFER, 3DSTATE_HIER_DEPTH_BUFFER) SW must first issue a pipelined depth stall (PIPE_CONTROL with Depth Stall bit set), followed by a pipelined depth cache flush (PIPE_CONTROL with Depth Flush Bit set), followed by another pipelined depth stall (PIPE_CONTROL with Depth Stall bit set), unless SW can otherwise guarantee that the pipeline from WM onwards is already flushed (e.g., via a preceding MI_FLUSH).
References brw_emit_pipe_control_flush(), brw_context::gen, PIPE_CONTROL_DEPTH_CACHE_FLUSH, and PIPE_CONTROL_DEPTH_STALL.
Referenced by blorp_exec(), brw_depth_writes_enabled(), brw_emit_depth_stencil_hiz(), emit_depth_packets(), gen6_emit_depth_stencil_hiz(), and gen7_emit_depth_stencil_hiz().
brw_emit_depth_stencil_hiz()
void brw_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References _3DSTATE_CLEAR_PARAMS, _3DSTATE_DEPTH_BUFFER, _3DSTATE_HIER_DEPTH_BUFFER, _3DSTATE_STENCIL_BUFFER, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_depth_stall_flushes(), BRW_TILEWALK_YMAJOR, brw_context::depthstencil, brw_context::gen, GEN5_DEPTH_CLEAR_VALID, brw_context::hiz_offset, brw_context::is_g4x, OUT_BATCH, OUT_RELOC, and brw_context::stencil_offset.
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
brw_emit_depthbuffer()
void brw_emit_depthbuffer (struct brw_context * brw)
References _mesa_is_format_packed_depth_stencil(), swrast_renderbuffer::Base, intel_renderbuffer::Base, brw_context::bo, brw_depthbuffer_format(), BRW_DEPTHFORMAT_D32_FLOAT, brw_render_cache_set_check_flush(), BRW_SURFACE_2D, BRW_SURFACE_NULL, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, brw_context::depth_mt, brw_context::depth_offset, brw_context::depthstencil, gl_context::DrawBuffer, brw_context::emit_depth_stencil_hiz, brw_context::gen, brw_context::has_separate_stencil, gl_renderbuffer::Height, intel_get_renderbuffer(), intel_renderbuffer_has_hiz(), MESA_FORMAT_S_UINT8, brw_context::stencil_mt, brw_context::tile_x, brw_context::tile_y, brw_context::vtbl, and gl_renderbuffer::Width.
Referenced by brw_depth_writes_enabled().
brw_emit_mi_flush()
void brw_emit_mi_flush (struct brw_context * brw)
References ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH_BLT, BLT_RING, brw_emit_pipe_control_flush(), brw_context::gen, MI_FLUSH_DW, OUT_BATCH, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_INSTRUCTION_INVALIDATE, PIPE_CONTROL_NO_WRITE, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE, PIPE_CONTROL_VF_CACHE_INVALIDATE, and intel_batchbuffer::ring.
Referenced by brw_begin_perf_query(), brw_copy_buffer_subdata(), brw_depth_writes_enabled(), brw_emit_prim(), brw_end_perf_query(), brw_fence_insert_locked(), brw_finish_batch(), brw_render_cache_set_check_flush(), brw_save_primitives_written_counters(), brw_unmap_buffer(), emit_pipeline_stat(), gen6_upload_urb(), gen7_pause_transform_feedback(), hsw_pause_transform_feedback(), intel_get_tex_sub_image(), intel_miptree_set_alpha_to_one(), intel_texture_barrier(), intelEmitCopyBlit(), intelEmitImmediateColorExpandBlit(), intelReadPixels(), save_prim_start_values(), tally_prims_written(), write_primitives_generated(), write_xfb_overflow_streams(), and write_xfb_primitives_written().
brw_emit_pipe_control_flush()
void brw_emit_pipe_control_flush (struct brw_context * brw, uint32_t flags)
Emit a PIPE_CONTROL with various flushing flags.
The caller is responsible for deciding what flags are appropriate for the given generation.
References _3DSTATE_PIPE_CONTROL, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_post_sync_nonzero_flush(), brw_context::gen, gen7_cs_stall_every_four_pipe_controls(), gen8_add_cs_stall_workaround_bits(), OUT_BATCH, PIPE_CONTROL_CACHE_FLUSH_BITS, PIPE_CONTROL_CACHE_INVALIDATE_BITS, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, and PIPE_CONTROL_VF_CACHE_INVALIDATE.
Referenced by brw_blend_barrier(), brw_blorp_resolve_color(), brw_depth_writes_enabled(), brw_emit_depth_stall_flushes(), brw_emit_mi_flush(), brw_emit_post_sync_nonzero_flush(), brw_emit_select_pipeline(), brw_fast_clear_depth(), brw_finish_batch(), brw_memory_barrier(), brw_render_cache_set_check_flush(), brw_write_timestamp(), do_single_blorp_clear(), gen8_hiz_exec(), gen8_write_pma_stall_bits(), hsw_result_to_gpr0(), intel_texture_barrier(), set_predicate_for_result(), setup_l3_config(), and upload_vs_state().
brw_emit_pipe_control_write()
void brw_emit_pipe_control_write (struct brw_context * brw, uint32_t flags, drm_intel_bo * bo, uint32_t offset, uint32_t imm_lower, uint32_t imm_upper)
Emit a PIPE_CONTROL that writes to a buffer object.
flags should contain one of the following items:
PIPE_CONTROL_WRITE_IMMEDIATE
PIPE_CONTROL_WRITE_TIMESTAMP
PIPE_CONTROL_WRITE_DEPTH_COUNT
References _3DSTATE_PIPE_CONTROL, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, gen7_cs_stall_every_four_pipe_controls(), gen8_add_cs_stall_workaround_bits(), OUT_BATCH, OUT_RELOC, OUT_RELOC64, and PIPE_CONTROL_GLOBAL_GTT_WRITE.
Referenced by brw_depth_writes_enabled(), brw_emit_post_sync_nonzero_flush(), brw_write_depth_count(), brw_write_timestamp(), gen7_emit_cs_stall_flush(), gen7_emit_vs_workaround_flush(), gen8_hiz_exec(), and set_query_availability().
brw_emit_post_sync_nonzero_flush()
void brw_emit_post_sync_nonzero_flush (struct brw_context * brw)
Emits a PIPE_CONTROL with a non-zero post-sync operation, for implementing two workarounds on gen6.
From section 1.4.7.1 "PIPE_CONTROL" of the Sandy Bridge PRM volume 2 part 1:
[DevSNB-C+{W/A}] Before any depth stall flush (including those produced by non-pipelined state commands), software needs to first send a PIPE_CONTROL with no bits set except Post-Sync Operation != 0.
[Dev-SNB{W/A}]: Before a PIPE_CONTROL with Write Cache Flush Enable =1, a PIPE_CONTROL with any non-zero post-sync-op is required.
And the workaround for these two requires this workaround first:
[Dev-SNB{W/A}]: Pipe-control with CS-stall bit set must be sent BEFORE the pipe-control with a post-sync op and no write-cache flushes.
And this last workaround is tricky because of the requirements on that bit. From section 1.4.7.2.3 "Stall" of the Sandy Bridge PRM volume 2 part 1:
"1 of the following must also be set:
 - Render Target Cache Flush Enable ([12] of DW1)
 - Depth Cache Flush Enable ([0] of DW1)
 - Stall at Pixel Scoreboard ([1] of DW1)
 - Depth Stall ([13] of DW1)
 - Post-Sync Operation ([13] of DW1)
 - Notify Enable ([8] of DW1)"
The cache flushes require the workaround flush that triggered this one, so we can't use it. Depth stall would trigger the same. Post-sync nonzero is what triggered this second workaround, so we can't use that one either. Notify enable is IRQs, which aren't really our business. That leaves only stall at scoreboard.
References brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), PIPE_CONTROL_CS_STALL, PIPE_CONTROL_STALL_AT_SCOREBOARD, PIPE_CONTROL_WRITE_IMMEDIATE, and brw_context::workaround_bo.
Referenced by blorp_exec(), brw_depth_writes_enabled(), brw_emit_pipe_control_flush(), brw_upload_initial_gpu_state(), and brw_upload_pipeline_state().
brw_emit_query_begin()
void brw_emit_query_begin (struct brw_context * brw)
Record the PS_DEPTH_COUNT value (for occlusion queries) just before primitive drawing.
In a pre-hardware context world, the single PS_DEPTH_COUNT register is shared among all applications using the GPU. However, our query value needs to only include fragments generated by our application/GL context.
To accommodate this, we record PS_DEPTH_COUNT at the start and end of each batchbuffer (technically, the first primitive drawn and flush time). Subtracting each pair of values calculates the change in PS_DEPTH_COUNT caused by a batchbuffer. Since there is no preemption inside batches, this is guaranteed to only measure the effects of our current application.
Adding each of these differences (in case drawing is done over many batches) produces the final expected value.
In a world with hardware contexts, PS_DEPTH_COUNT is saved and restored as part of the context state, so this is unnecessary, and skipped.
References brw_context::begin_emitted, brw_query_object::bo, brw_write_depth_count(), brw_context::ctx, ensure_bo_has_space(), brw_context::hw_ctx, brw_query_object::last_index, brw_context::obj, and brw_context::query.
Referenced by brw_emit_vertices(), and brw_end_query().
brw_emit_query_end()
void brw_emit_query_end (struct brw_context * brw)
Called at batchbuffer flush to get an ending PS_DEPTH_COUNT (for non-hardware context platforms).
See the explanation in brw_emit_query_begin().
References brw_context::begin_emitted, brw_query_object::bo, brw_write_depth_count(), brw_context::hw_ctx, brw_query_object::last_index, brw_context::obj, and brw_context::query.
Referenced by brw_end_query(), and brw_finish_batch().
brw_end_transform_feedback()
void brw_end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References brw_context(), brw_save_primitives_written_counters(), gl_transform_feedback_object::Paused, and brw_transform_feedback_object::vertices_written_valid.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_fini_pipe_control()
void brw_fini_pipe_control (struct brw_context * brw)
References brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), and intelDestroyContext().
brw_get_graphics_reset_status()
GLenum brw_get_graphics_reset_status (struct gl_context * ctx)
Query information about GPU resets observed by this context.
Called via dd_function_table::GetGraphicsResetStatus.
References brw_context(), brw_context::hw_ctx, and brw_context::reset_count.
Referenced by brw_get_index_type(), and brwCreateContext().
brw_get_index_type()
static unsigned brw_get_index_type (GLenum type) inline static
References brw_begin_transform_feedback(), brw_blorp_copytexsubimage(), brw_blorp_framebuffer(), brw_bo_map(), brw_bo_map_gtt(), brw_check_for_reset(), brw_compute_xfb_vertices_written(), brw_create_buffer_surface(), brw_create_constant_surface(), brw_delete_transform_feedback(), brw_depth_format(), brw_end_transform_feedback(), brw_get_graphics_reset_status(), brw_get_transform_feedback_vertex_count(), brw_init_compute_functions(), brw_init_performance_queries(), brw_init_surface_formats(), brw_init_syncobj_functions(), brw_new_transform_feedback(), brw_pause_transform_feedback(), brw_prepare_vertices(), brw_render_target_supported(), brw_resume_transform_feedback(), brw_save_primitives_written_counters(), brw_update_buffer_texture_surface(), brw_update_sol_surface(), brw_upload_abo_surfaces(), brw_upload_image_surfaces(), brw_upload_ubo_surfaces(), gen6_determine_sample_mask(), gen6_emit_3dstate_multisample(), gen6_emit_3dstate_sample_mask(), gen6_get_sample_position(), gen6_set_sample_maps(), gen6_upload_urb(), gen7_begin_transform_feedback(), gen7_emit_push_constant_state(), gen7_end_transform_feedback(), gen7_pause_transform_feedback(), gen7_resume_transform_feedback(), gen7_upload_urb(), gen8_emit_3dstate_multisample(), gen8_emit_3dstate_sample_pattern(), GLuint, hsw_begin_transform_feedback(), hsw_end_transform_feedback(), hsw_pause_transform_feedback(), hsw_resume_transform_feedback(), intel_translate_compare_func(), intel_translate_logic_op(), intel_translate_shadow_compare_func(), intel_translate_stencil_op(), and intelInitExtensions().
Referenced by brw_emit_index_buffer(), and gen8_emit_index_buffer().
brw_get_renderer_string()
const char* brw_get_renderer_string (const struct intel_screen * screen)
References intel_screen::deviceID, get_bsw_model(), and void.
Referenced by brw_query_renderer_string(), and intel_get_string().
brw_get_scratch_bo()
void brw_get_scratch_bo (struct brw_context * brw, drm_intel_bo ** scratch_bo, int size)
References brw_context::bufmgr.
Referenced by brw_emit_null_surface_state(), and key_debug().
brw_get_shader_time_index()
int brw_get_shader_time_index (struct brw_context * brw, struct gl_program * prog, enum shader_time_shader_type type, bool is_glsl_sh)
Chooses an index in the shader_time buffer and sets up tracking information for our printouts.
Note that this holds on to references to the underlying programs, which may change their lifetimes compared to normal operation.
References gl_program::Id, brw_context::ids, gl_program::info, brw_context::names, brw_context::num_entries, brw_context::shader_time, and brw_context::types.
Referenced by brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), and key_debug().
brw_get_transform_feedback_vertex_count()
GLsizei brw_get_transform_feedback_vertex_count (struct gl_context * ctx, struct gl_transform_feedback_object * obj, GLuint stream)
GetTransformFeedbackVertexCount() driver hook.
Returns the number of vertices written to a particular stream by the last Begin/EndTransformFeedback block. Used to implement DrawTransformFeedback().
References brw_compute_xfb_vertices_written(), brw_context(), gl_transform_feedback_object::EndedAnytime, and brw_transform_feedback_object::vertices_written.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_get_vertex_surface_type()
unsigned brw_get_vertex_surface_type (struct brw_context * brw, const struct gl_vertex_array * glarray)
Given vertex array type/size/format/normalized info, return the appopriate hardware surface type.
Format will be GL_RGBA or possibly GL_BGRA for GLubyte[4] color arrays.
References _mesa_enum_to_string(), byte_types_direct, byte_types_norm, byte_types_scale, double_types(), gl_vertex_array::Doubles, fixed_point_types, float_types, gl_vertex_array::Format, brw_context::gen, GL_HALF_FLOAT_OES, half_float_types, int_types_direct, int_types_norm, int_types_scale, gl_vertex_array::Integer, brw_context::is_baytrail, brw_context::is_haswell, gl_vertex_array::Normalized, short_types_direct, short_types_norm, short_types_scale, gl_vertex_array::Size, brw_context::size, gl_vertex_array::Type, ubyte_types_direct, ubyte_types_norm, ubyte_types_scale, uint_types_direct, uint_types_norm, uint_types_scale, ushort_types_direct, ushort_types_norm, and ushort_types_scale.
Referenced by brw_emit_vertices(), gen8_emit_vertices(), and key_debug().
brw_init_common_queryobj_functions()
void brw_init_common_queryobj_functions (struct dd_function_table * functions)
References brw_delete_query(), brw_get_timestamp(), brw_new_query_object(), dd_function_table::DeleteQuery, dd_function_table::GetTimestamp, and dd_function_table::NewQueryObject.
Referenced by brw_init_driver_functions().
brw_init_compute_functions()
void brw_init_compute_functions (struct dd_function_table * functions)
References brw_dispatch_compute(), brw_dispatch_compute_indirect(), dd_function_table::DispatchCompute, and dd_function_table::DispatchComputeIndirect.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_init_conditional_render_functions()
void brw_init_conditional_render_functions (struct dd_function_table * functions)
brw_conditional_render.c
References dd_function_table::BeginConditionalRender, brw_begin_conditional_render(), brw_end_conditional_render(), and dd_function_table::EndConditionalRender.
Referenced by brw_init_driver_functions().
brw_init_object_purgeable_functions()
void brw_init_object_purgeable_functions (struct dd_function_table * functions)
References dd_function_table::BufferObjectPurgeable, dd_function_table::BufferObjectUnpurgeable, intel_buffer_object_purgeable(), intel_buffer_object_unpurgeable(), intel_render_object_purgeable(), intel_render_object_unpurgeable(), intel_texture_object_purgeable(), intel_texture_object_unpurgeable(), dd_function_table::RenderObjectPurgeable, dd_function_table::RenderObjectUnpurgeable, dd_function_table::TextureObjectPurgeable, and dd_function_table::TextureObjectUnpurgeable.
Referenced by brw_init_driver_functions().
brw_init_performance_queries()
void brw_init_performance_queries (struct brw_context * brw)
References dd_function_table::BeginPerfQuery, brw_begin_perf_query(), brw_delete_perf_query(), brw_end_perf_query(), brw_get_perf_counter_info(), brw_get_perf_query_data(), brw_get_perf_query_info(), brw_init_perf_query_info(), brw_is_perf_query_ready(), brw_new_perf_query_object(), brw_wait_perf_query(), brw_context::ctx, dd_function_table::DeletePerfQuery, gl_context::Driver, dd_function_table::EndPerfQuery, dd_function_table::GetPerfCounterInfo, dd_function_table::GetPerfQueryData, dd_function_table::GetPerfQueryInfo, dd_function_table::InitPerfQueryInfo, dd_function_table::IsPerfQueryReady, dd_function_table::NewPerfQueryObject, and dd_function_table::WaitPerfQuery.
Referenced by brw_get_index_type(), and brwCreateContext().
brw_init_pipe_control()
int brw_init_pipe_control (struct brw_context * brw, const struct gen_device_info * info)
References brw_context::bufmgr, brw_context::pipe_controls_since_last_cs_stall, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
brw_init_shader_time()
void brw_init_shader_time (struct brw_context * brw)
References brw_context::bo, brw_context::bufmgr, brw_context::cumulative, brw_context::ids, brw_context::max_entries, brw_context::names, brw_context::shader_time, and brw_context::types.
Referenced by brwCreateContext(), and key_debug().
brw_init_surface_formats()
void brw_init_surface_formats (struct brw_context * brw)
References _mesa_get_format_bytes(), _mesa_is_format_integer_color(), brw_isl_format_for_mesa_format(), brw_context::ctx, intel_screen::devinfo, brw_context::format_supported_as_render_target, brw_context::gen, brw_context::is_g4x, brw_context::is_haswell, MESA_FORMAT_COUNT, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_NONE, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBX_FLOAT16, MESA_FORMAT_RGBX_FLOAT32, MESA_FORMAT_RGBX_UNORM16, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, brw_context::render_target_format, brw_context::screen, and gl_context::TextureFormatSupported.
Referenced by brw_get_index_type(), and brwCreateContext().
brw_init_syncobj_functions()
void brw_init_syncobj_functions (struct dd_function_table * functions)
References brw_gl_check_sync(), brw_gl_client_wait_sync(), brw_gl_delete_sync(), brw_gl_fence_sync(), brw_gl_new_sync(), brw_gl_server_wait_sync(), dd_function_table::CheckSync, dd_function_table::ClientWaitSync, dd_function_table::DeleteSyncObject, dd_function_table::FenceSync, dd_function_table::NewSyncObject, and dd_function_table::ServerWaitSync.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_is_query_pipelined()
bool brw_is_query_pipelined (struct brw_query_object * query)
Is this type of query written by PIPE_CONTROL?
References brw_query_object::Base, and gl_query_object::Target.
Referenced by hsw_store_query_result(), and set_query_availability().
brw_load_register_imm32()
void brw_load_register_imm32 (struct brw_context * brw, uint32_t reg, uint32_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_LOAD_REGISTER_IMM, and OUT_BATCH.
Referenced by shr_gpr0_by_2_bits(), and tally_prims_written().
brw_load_register_imm64()
void brw_load_register_imm64 (struct brw_context * brw, uint32_t reg, uint64_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_LOAD_REGISTER_IMM, and OUT_BATCH.
Referenced by calc_overflow_to_gpr0(), gpr0_to_bool(), keep_gpr0_lower_n_bits(), set_predicate(), and set_predicate_for_overflow_query().
brw_load_register_mem()
void brw_load_register_mem (struct brw_context * brw, uint32_t reg, drm_intel_bo * bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
intel_batchbuffer.c
References load_sized_register_mem().
Referenced by brw_emit_prim(), prepare_indirect_gpgpu_walker(), and tally_prims_written().
brw_load_register_mem64()
void brw_load_register_mem64 (struct brw_context * brw, uint32_t reg, drm_intel_bo * bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
References load_sized_register_mem().
Referenced by hsw_result_to_gpr0(), load_overflow_data_to_cs_gprs(), set_predicate(), set_predicate_for_occlusion_query(), and tally_prims_written().
brw_load_register_reg()
void brw_load_register_reg (struct brw_context * brw, uint32_t src, uint32_t dest)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, brw_context::is_haswell, MI_LOAD_REGISTER_REG, and OUT_BATCH.
Referenced by shr_gpr0_by_2_bits().
brw_load_register_reg64()
void brw_load_register_reg64 (struct brw_context * brw, uint32_t src, uint32_t dest)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, brw_context::is_haswell, MI_LOAD_REGISTER_REG, and OUT_BATCH.
Referenced by set_predicate_for_overflow_query(), and tally_prims_written().
brw_meta_resolve_color()
void brw_meta_resolve_color (struct brw_context * brw, struct intel_mipmap_tree * mt)
brw_new_transform_feedback()
struct gl_transform_feedback_object* brw_new_transform_feedback (struct gl_context * ctx, GLuint name)
References _mesa_init_transform_feedback_object(), brw_transform_feedback_object::base, brw_context(), brw_context::bufmgr, CALLOC_STRUCT, brw_transform_feedback_object::offset_bo, and brw_transform_feedback_object::prim_count_bo.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_pause_transform_feedback()
void brw_pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References brw_context(), and brw_save_primitives_written_counters().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_prepare_vertices()
void brw_prepare_vertices (struct brw_context * brw)
References gl_vertex_array::_ElementSize, _mesa_bitcount_64(), gl_polygon_attrib::BackMode, intel_buffer_object::Base, brw_context::base, brw_context::baseinstance, brw_context::basevertex, BITFIELD64_BIT, BITFIELD64_MASK, brw_vertex_buffer::bo, brw_vertex_element::buffer, gl_vertex_array::BufferObj, brw_context::buffers, copy_array_to_vbo_array(), brw_context::ctx, brw_context::enabled, gl_polygon_attrib::FrontMode, brw_context::gen, brw_vertex_element::glarray, GLuint, if(), brw_context::index_bounds_valid, brw_context::inputs, gl_vertex_array::InstanceDivisor, intel_buffer_object(), intel_bufferobj_buffer(), brw_vertex_element::is_dual_slot, brw_context::max_index, brw_context::min_index, brw_context::nr_buffers, brw_context::nr_enabled, brw_context::num_instances, brw_vertex_buffer::offset, brw_vertex_element::offset, gl_context::Polygon, brw_stage_state::prog_data, gl_vertex_array::Ptr, gl_buffer_object::Size, brw_vertex_buffer::size, brw_context::start_vertex_bias, brw_vertex_buffer::step_rate, brw_vertex_buffer::stride, gl_vertex_array::StrideB, brw_context::vb, and brw_context::vs.
Referenced by brw_emit_vertices(), brw_get_index_type(), and gen8_emit_vertices().
brw_program()
static struct brw_program* brw_program (struct gl_program * p) static
Referenced by brw_cs_precompile(), brw_fs_precompile(), brw_gs_precompile(), brw_tcs_precompile(), brw_tes_precompile(), brw_vs_precompile(), and brwProgramStringNotify().
brw_program_const()
static const struct brw_program* brw_program_const (const struct gl_program * p) static
Referenced by brw_wm_populate_key(), brwProgramStringNotify(), gen6_upload_gs_push_constants(), gen6_upload_vs_push_constants(), gen6_upload_wm_push_constants(), gen7_upload_tcs_push_constants(), and gen7_upload_tes_push_constants().
brw_program_reloc()
static uint32_t brw_program_reloc (struct brw_context * brw, uint32_t state_offset, uint32_t prog_offset) inline static
References brw_context::batch, brw_cache::bo, intel_batchbuffer::bo, brw_context::cache, and brw_context::gen.
Referenced by brw_upload_clip_unit(), brw_upload_gs_unit(), brw_upload_vs_unit(), brw_upload_wm_unit(), and upload_sf_unit().
brw_query_counter()
void brw_query_counter (struct gl_context * ctx, struct gl_query_object * q)
Driver hook for glQueryCounter().
This handles GL_TIMESTAMP queries, which perform a pipelined read of the current GPU time. This is unlike GL_TIME_ELAPSED, which measures the time while the query is active.
References brw_query_object::bo, brw_context(), brw_write_timestamp(), brw_context::bufmgr, brw_query_object::flushed, and gl_query_object::Target.
Referenced by gen4_init_queryobj_functions(), and gen6_query_counter().
brw_query_internal_format()
void brw_query_internal_format (struct gl_context * ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint * params)
References _mesa_query_internal_format_default(), brw_query_samples_for_format(), and brw_context::num_samples.
Referenced by brw_depth_writes_enabled(), and brw_init_driver_functions().
brw_raw_timestamp_delta()
uint64_t brw_raw_timestamp_delta (struct brw_context * brw, uint64_t time0, uint64_t time1)
References intel_screen::hw_has_timestamp, and brw_context::screen.
Referenced by brw_queryobj_get_results(), and gen6_queryobj_get_results().
brw_render_target_supported()
bool brw_render_target_supported (struct brw_context * brw, struct gl_renderbuffer * rb)
References gl_renderbuffer::_BaseFormat, _mesa_get_format_bytes(), _mesa_is_format_integer_color(), gl_renderbuffer::Format, brw_context::format_supported_as_render_target, brw_context::gen, GLuint, and gl_renderbuffer::NumSamples.
Referenced by brw_get_index_type(), brw_update_renderbuffer_surface(), and intel_validate_framebuffer().
brw_resume_transform_feedback()
void brw_resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References _3DSTATE_GS_SVB_INDEX, ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_save_primitives_written_counters(), compute_vertices_written_so_far(), brw_transform_feedback_object::max_index, OUT_BATCH, and SVB_INDEX_SHIFT.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_save_primitives_written_counters()
void brw_save_primitives_written_counters (struct brw_context * brw, struct brw_transform_feedback_object * obj)
Store the SO_NUM_PRIMS_WRITTEN counters for each stream (4 uint64_t values) to prim_count_bo.
If prim_count_bo is out of space, gather up the results so far into prims_generated[] and allocate a new buffer with enough space.
The number of primitives written is used to compute the number of vertices written to a transform feedback stream, which is required to implement DrawTransformFeedback().
References brw_emit_mi_flush(), brw_store_register_mem64(), gl_context::Const, brw_context::ctx, brw_context::gen, GEN6_SO_NUM_PRIMS_WRITTEN, GEN7_SO_NUM_PRIMS_WRITTEN, gl_constants::MaxVertexStreams, brw_transform_feedback_object::prim_count_bo, brw_transform_feedback_object::prim_count_buffer_index, and tally_prims_generated().
Referenced by brw_begin_transform_feedback(), brw_end_transform_feedback(), brw_get_index_type(), brw_pause_transform_feedback(), brw_resume_transform_feedback(), gen7_begin_transform_feedback(), gen7_end_transform_feedback(), gen7_pause_transform_feedback(), and gen7_resume_transform_feedback().
brw_select_clip_planes()
gl_clip_plane* brw_select_clip_planes (struct gl_context * ctx)
Decide which set of clip planes should be used when clipping via gl_Position or gl_ClipVertex.
References gl_transform_attrib::_ClipUserPlane, gl_context::_Shader, gl_pipeline_object::CurrentProgram, gl_transform_attrib::EyeUserPlane, and gl_context::Transform.
Referenced by brw_codegen_vs_prog(), brw_upload_constant_buffer(), and key_debug().
brw_store_data_imm32()
void brw_store_data_imm32 (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint32_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_DATA_IMM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by store_query_result_imm().
brw_store_data_imm64()
void brw_store_data_imm64 (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint64_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_DATA_IMM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by hsw_begin_transform_feedback(), and store_query_result_imm().
brw_store_register_mem32()
void brw_store_register_mem32 (struct brw_context * brw, drm_intel_bo * bo, uint32_t reg, uint32_t offset)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_REGISTER_MEM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by tally_prims_written().
brw_store_register_mem64()
void brw_store_register_mem64 (struct brw_context * brw, drm_intel_bo * bo, uint32_t reg, uint32_t offset)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_REGISTER_MEM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by brw_save_primitives_written_counters(), emit_pipeline_stat(), save_prim_start_values(), snapshot_statistics_registers(), write_primitives_generated(), write_xfb_overflow_streams(), and write_xfb_primitives_written().
brw_timebase_scale()
uint64_t brw_timebase_scale (struct brw_context * brw, uint64_t gpu_timestamp)
References intel_screen::devinfo, and brw_context::screen.
Referenced by brw_get_timestamp(), brw_queryobj_get_results(), and gen6_queryobj_get_results().
brw_update_buffer_texture_surface()
void brw_update_buffer_texture_surface (struct gl_context * ctx, unsigned unit, uint32_t * surf_offset)
References gl_texture_object::_BufferObjectFormat, gl_texture_unit::_Current, _mesa_get_format_bytes(), _mesa_get_format_name(), _mesa_problem(), intel_buffer_object::Base, brw_context(), brw_emit_buffer_surface_state(), brw_isl_format_for_mesa_format(), gl_texture_object::BufferObject, gl_texture_object::BufferOffset, gl_texture_object::BufferSize, gl_context::Const, intel_buffer_object(), intel_bufferobj_buffer(), gl_constants::MaxTextureBufferSize, MESA_FORMAT_RGBA_FLOAT32, gl_buffer_object::Size, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_get_index_type(), and brw_update_texture_surface().
brw_update_sol_surface()
void brw_update_sol_surface (struct brw_context * brw, struct gl_buffer_object * buffer_obj, uint32_t * out_offset, unsigned num_vector_components, unsigned stride_dwords, unsigned offset_dwords)
Set up a binding table entry for use by stream output logic (transform feedback).
buffer_size_minus_1 must be less than BRW_MAX_NUM_BUFFER_ENTRIES.
References brw_context::batch, intel_batchbuffer::bo, BRW_MAX_NUM_BUFFER_ENTRIES, brw_state_batch(), BRW_SURFACE_BUFFER, BRW_SURFACE_DEPTH_SHIFT, BRW_SURFACE_FORMAT_SHIFT, BRW_SURFACE_HEIGHT_SHIFT, BRW_SURFACE_MIPLAYOUT_SHIFT, BRW_SURFACE_MIPMAPLAYOUT_BELOW, BRW_SURFACE_PITCH_SHIFT, BRW_SURFACE_RC_READ_WRITE, BRW_SURFACE_TYPE_SHIFT, BRW_SURFACE_WIDTH_SHIFT, intel_buffer_object(), intel_bufferobj_buffer(), and gl_buffer_object::Size.
Referenced by brw_get_index_type(), and gen6_update_sol_surfaces().
brw_upload_abo_surfaces()
void brw_upload_abo_surfaces (struct brw_context * brw, const struct gl_program * prog, struct brw_stage_state * stage_state, struct brw_stage_prog_data * prog_data)
References gl_context::AtomicBufferBindings, intel_buffer_object::Base, brw_emit_buffer_surface_state(), BRW_NEW_SURFACES, gl_atomic_buffer_binding::BufferObject, brw_context::ctx, gl_program::info, intel_buffer_object(), intel_bufferobj_buffer(), gl_context::NewDriverState, gl_atomic_buffer_binding::Offset, gl_program::sh, gl_buffer_object::Size, and brw_stage_state::surf_offset.
Referenced by brw_get_index_type(), brw_upload_cs_abo_surfaces(), brw_upload_gs_abo_surfaces(), brw_upload_tcs_abo_surfaces(), brw_upload_tes_abo_surfaces(), brw_upload_vs_abo_surfaces(), and brw_upload_wm_abo_surfaces().
brw_upload_cs_urb_state()
void brw_upload_cs_urb_state (struct brw_context * brw)
Uploads the CS_URB_STATE packet.
Just like brw_vs_state.c and brw_wm_state.c define a URB entry size and number of entries for their stages, constant buffers do so using this state packet. Having multiple CURBEs in the URB at the same time allows the hardware to avoid a pipeline stall between primitives using different constant buffer contents.
References ADVANCE_BATCH, BEGIN_BATCH, CMD_CS_URB_STATE, brw_context::csize, brw_context::nr_cs_entries, OUT_BATCH, and brw_context::urb.
Referenced by key_debug(), and upload_psp_urb_cbs().
brw_upload_image_surfaces()
void brw_upload_image_surfaces (struct brw_context * brw, const struct gl_program * prog, struct brw_stage_state * stage_state, struct brw_stage_prog_data * prog_data)
References _NEW_PROGRAM_CONSTANTS, BRW_NEW_SURFACES, brw_context::ctx, gl_context::ImageUnits, gl_program::info, gl_context::NewDriverState, brw_context::NewGLState, gl_program::sh, brw_stage_state::surf_offset, and update_image_surface().
Referenced by brw_get_index_type(), brw_upload_cs_image_surfaces(), brw_upload_gs_image_surfaces(), brw_upload_tcs_image_surfaces(), brw_upload_tes_image_surfaces(), brw_upload_vs_image_surfaces(), and brw_upload_wm_image_surfaces().
brw_upload_ubo_surfaces()
void brw_upload_ubo_surfaces (struct brw_context * brw, struct gl_program * prog, struct brw_stage_state * stage_state, struct brw_stage_prog_data * prog_data)
References gl_uniform_buffer_binding::AutomaticSize, gl_shader_storage_buffer_binding::AutomaticSize, brw_create_buffer_surface(), brw_create_constant_surface(), BRW_NEW_SURFACES, gl_shader_storage_buffer_binding::BufferObject, gl_uniform_buffer_binding::BufferObject, brw_context::ctx, brw_context::emit_null_surface_state, gl_program::info, intel_buffer_object(), intel_bufferobj_buffer(), gl_context::NewDriverState, gl_shared_state::NullBufferObj, gl_shader_storage_buffer_binding::Offset, gl_uniform_buffer_binding::Offset, gl_program::sh, gl_context::ShaderStorageBufferBindings, gl_context::Shared, gl_uniform_buffer_binding::Size, gl_shader_storage_buffer_binding::Size, gl_buffer_object::Size, brw_stage_state::surf_offset, gl_context::UniformBufferBindings, and brw_context::vtbl.
Referenced by brw_get_index_type(), brw_upload_cs_ubo_surfaces(), brw_upload_gs_ubo_surfaces(), brw_upload_tcs_ubo_surfaces(), brw_upload_tes_ubo_surfaces(), brw_upload_vs_ubo_surfaces(), and brw_upload_wm_ubo_surfaces().
brw_upload_urb_fence()
void brw_upload_urb_fence (struct brw_context * brw)
References brw_context::batch, brw_urb_fence::bits0, brw_urb_fence::bits1, BRW_BATCH_STRUCT, brw_context::clip_start, brw_urb_fence::clp_fence, brw_urb_fence::clp_realloc, CMD_URB_FENCE, brw_urb_fence::cs_fence, brw_urb_fence::cs_realloc, brw_context::cs_start, brw_urb_fence::gs_fence, brw_urb_fence::gs_realloc, brw_context::gs_start, brw_urb_fence::header, brw_urb_fence::length, intel_batchbuffer::map_next, MI_NOOP, brw_urb_fence::opcode, brw_urb_fence::pad, brw_urb_fence::sf_fence, brw_urb_fence::sf_realloc, brw_context::sf_start, brw_context::size, brw_context::urb, USED_BATCH, brw_urb_fence::vfe_realloc, brw_urb_fence::vs_fence, and brw_urb_fence::vs_realloc.
Referenced by key_debug(), and upload_psp_urb_cbs().
brw_validate_textures()
void brw_validate_textures (struct brw_context * brw)
Finalizes all textures, completing any rendering that needs to be done to prepare them.
References gl_texture_unit::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, brw_context::ctx, intel_finalize_mipmap_tree(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_dispatch_compute_common(), and brw_try_draw_prims().
brw_workaround_depthstencil_alignment()
void brw_workaround_depthstencil_alignment (struct brw_context * brw, GLbitfield clear_mask)
References _mesa_get_format_base_format(), brw_get_depthstencil_tile_masks(), BUFFER_BIT_DEPTH, BUFFER_BIT_STENCIL, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, brw_context::depth_mt, brw_context::depth_offset, brw_context::depthstencil, intel_renderbuffer::draw_x, intel_renderbuffer::draw_y, gl_context::DrawBuffer, brw_context::gen, get_stencil_miptree(), brw_context::has_surface_tile_offset, brw_context::hiz_offset, intel_get_renderbuffer(), intel_miptree_get_aligned_offset(), intel_miptree_get_image_offset(), intel_miptree_reference(), intel_renderbuffer_has_hiz(), intel_renderbuffer_move_to_temp(), intel_renderbuffer_set_draw_offset(), MESA_FORMAT_S_UINT8, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, brw_context::stencil_mt, brw_context::stencil_offset, brw_context::tile_x, and brw_context::tile_y.
Referenced by brw_clear(), and brw_try_draw_prims().
brw_write_depth_count()
void brw_write_depth_count (struct brw_context * brw, drm_intel_bo * bo, int idx)
Emit PIPE_CONTROLs to write the PS_DEPTH_COUNT register into a buffer.
References brw_emit_pipe_control_write(), brw_context::gen, brw_context::gt, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_STALL, and PIPE_CONTROL_WRITE_DEPTH_COUNT.
Referenced by brw_emit_query_begin(), brw_emit_query_end(), gen6_begin_query(), and gen6_end_query().
brw_write_timestamp()
void brw_write_timestamp (struct brw_context * brw, drm_intel_bo * bo, int idx)
Emit PIPE_CONTROLs to write the current GPU timestamp into a buffer.
References brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), brw_context::gen, brw_context::gt, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_STALL_AT_SCOREBOARD, and PIPE_CONTROL_WRITE_TIMESTAMP.
Referenced by brw_begin_query(), brw_end_query(), brw_query_counter(), gen6_begin_query(), and gen6_end_query().
brwCreateContext()
GLboolean brwCreateContext (gl_api api, const struct gl_config * mesaVis, __DRIcontext * driContextPriv, unsigned major_version, unsigned minor_version, uint32_t flags, bool notify_reset, unsigned * error, void * sharedContextPrivate)
References gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _mesa_compute_version(), _mesa_init_point(), _mesa_initialize_context(), _mesa_initialize_dispatch_tables(), _mesa_initialize_vbo_vtxfmt(), _swrast_allow_pixel_fog(), _swrast_allow_vertex_fog(), _swrast_CreateContext(), _swsetup_CreateContext(), _tnl_CreateContext(), _tnl_run_pipeline(), _vbo_CreateContext(), API_OPENGL_CORE, API_OPENGLES2, brw_context::base, brw_context::batch, brw_blorp_init(), brw_draw_init(), brw_emit_depth_stencil_hiz(), brw_get_graphics_reset_status(), brw_init_driver_functions(), brw_init_performance_queries(), brw_init_pipe_control(), brw_init_shader_time(), brw_init_state(), brw_init_surface_formats(), brw_initialize_context_constants(), brw_initialize_cs_context_constants(), BRW_PREDICATE_STATE_RENDER, brw_process_driconf_options(), intel_screen::bufmgr, brw_context::bufmgr, brw_context::clip, gl_context::Const, gl_constants::ContextFlags, brw_context::ctx, intel_screen::devinfo, brw_context::driContext, brw_context::emit_depth_stencil_hiz, brw_context::enable_cut_index, brw_context::enabled, gl_context::Extensions, gl_context::FragmentProgram, brw_context::gen, gen4_init_vtable_surface_functions(), gen6_emit_depth_stencil_hiz(), gen6_init_vtable_surface_functions(), gen7_emit_depth_stencil_hiz(), gen7_init_vtable_surface_functions(), gen8_emit_depth_stencil_hiz(), gen8_init_vtable_surface_functions(), dd_function_table::GetGraphicsResetStatus, brw_context::gs, brw_context::gs_present, brw_context::gt, brw_context::has_compr4, intel_screen::has_context_reset_notification, brw_context::has_hiz, brw_context::has_llc, brw_context::has_negative_rhw_bug, brw_context::has_pln, brw_context::has_separate_stencil, brw_context::has_surface_tile_offset, brw_context::has_swizzling, brw_context::hw_ctx, intel_screen::hw_has_swizzling, brw_context::in_progress, intel_batchbuffer_init(), intel_fbo_init(), gl_extensions::INTEL_performance_query, intelDestroyContext(), intelInitExtensions(), brw_context::is_baytrail, brw_context::is_broxton, brw_context::is_cherryview, brw_context::is_g4x, brw_context::is_haswell, brw_context::isl_dev, intel_screen::max_gtt_map_object_size, brw_context::max_gtt_map_object_size, brw_context::must_use_separate_stencil, brw_context::needs_unlit_centroid_workaround, brw_context::perf_debug, brw_context::predicate, brw_context::prim_restart, gl_constants::ResetStrategy, gl_constants::RobustAccess, brw_context::screen, brw_context::sf, brw_context::size, brw_stage_state::stage, brw_context::state, gl_context::swrast_context, brw_context::tcs, brw_context::tes, TNL_CONTEXT, brw_context::urb, vbo_always_unmap_buffers(), vbo_use_buffer_objects(), gl_context::VertexProgram, brw_context::viewport_count, brw_context::viewport_transform_enable, brw_context::vs, brw_context::vtbl, and brw_context::wm.
brwInitFragProgFuncs()
void brwInitFragProgFuncs (struct dd_function_table * functions)
References _tnl_program_string(), dd_function_table::BlendBarrier, brw_blend_barrier(), brw_link_shader(), brw_memory_barrier(), brwDeleteProgram(), brwNewProgram(), brwProgramStringNotify(), dd_function_table::DeleteProgram, dd_function_table::LinkShader, dd_function_table::MemoryBarrier, dd_function_table::NewProgram, and dd_function_table::ProgramStringNotify.
Referenced by brw_init_driver_functions(), and key_debug().
gen4_init_queryobj_functions()
void gen4_init_queryobj_functions (struct dd_function_table * functions)
References dd_function_table::BeginQuery, brw_begin_query(), brw_check_query(), brw_end_query(), brw_query_counter(), brw_wait_query(), dd_function_table::CheckQuery, dd_function_table::EndQuery, dd_function_table::QueryCounter, and dd_function_table::WaitQuery.
Referenced by brw_init_driver_functions().
gen6_determine_sample_mask()
unsigned gen6_determine_sample_mask (struct brw_context * brw)
References _mesa_is_multisample_enabled(), brw_context::ctx, gl_context::Multisample, brw_context::num_samples, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleCoverageValue, gl_multisample_attrib::SampleMask, and gl_multisample_attrib::SampleMaskValue.
Referenced by brw_get_index_type(), upload_multisample_state(), and upload_ps_state().
gen6_emit_3dstate_multisample()
void gen6_emit_3dstate_multisample (struct brw_context * brw, unsigned num_samples)
3DSTATE_MULTISAMPLE
References _3DSTATE_MULTISAMPLE, ADVANCE_BATCH, BEGIN_BATCH, brw_multisample_positions_4x, brw_multisample_positions_8x, brw_context::gen, MS_NUMSAMPLES_1, MS_NUMSAMPLES_4, MS_NUMSAMPLES_8, MS_PIXEL_LOCATION_CENTER, and OUT_BATCH.
Referenced by brw_get_index_type(), and upload_multisample_state().
gen6_emit_3dstate_sample_mask()
void gen6_emit_3dstate_sample_mask (struct brw_context * brw, unsigned mask)
3DSTATE_SAMPLE_MASK
References _3DSTATE_SAMPLE_MASK, ADVANCE_BATCH, BEGIN_BATCH, and OUT_BATCH.
Referenced by brw_get_index_type(), and upload_multisample_state().
gen6_emit_depth_stencil_hiz()
void gen6_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References _3DSTATE_CLEAR_PARAMS, _3DSTATE_DEPTH_BUFFER, _3DSTATE_HIER_DEPTH_BUFFER, _3DSTATE_STENCIL_BUFFER, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_depth_stall_flushes(), BRW_SURFACE_2D, BRW_TILEWALK_YMAJOR, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, GEN5_DEPTH_CLEAR_VALID, intel_get_renderbuffer(), intel_miptree_get_aligned_offset(), intel_renderbuffer::layer_count, MESA_FORMAT_S_UINT8, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, OUT_BATCH, OUT_RELOC, gl_texture_object::Target, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and translate_tex_target().
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
gen6_get_sample_position()
void gen6_get_sample_position (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint index, GLfloat * result)
References brw_multisample_positions_16x, brw_multisample_positions_1x_2x, brw_multisample_positions_4x, and brw_multisample_positions_8x.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen6_init_queryobj_functions()
void gen6_init_queryobj_functions (struct dd_function_table * functions)
gen6_queryobj.c
References dd_function_table::BeginQuery, dd_function_table::CheckQuery, dd_function_table::EndQuery, gen6_begin_query(), gen6_check_query(), gen6_end_query(), gen6_query_counter(), gen6_wait_query(), dd_function_table::QueryCounter, and dd_function_table::WaitQuery.
Referenced by brw_init_driver_functions(), and hsw_init_queryobj_functions().
gen6_set_sample_maps()
void gen6_set_sample_maps (struct gl_context * ctx)
Sample index layout shows the numbering of slots in a rectangular grid of samples with in a pixel.
Sample number layout shows the rectangular grid of samples roughly corresponding to the real sample locations with in a pixel. Sample number layout matches the sample index layout in case of 2X and 4x MSAA, but they are different in case of 8X MSAA.
2X MSAA sample index / number layout
| 0 | 1 |
4X MSAA sample index / number layout
| 0 | 1 |
| 2 | 3 |
8X MSAA sample index layout 8x MSAA sample number layout
| 0 | 1 | | 5 | 2 |
| 2 | 3 | | 4 | 6 |
| 4 | 5 | | 0 | 3 |
| 6 | 7 | | 7 | 1 |
16X MSAA sample index layout 16x MSAA sample number layout
| 0 | 1 | 2 | 3 | |15 |10 | 9 | 7 |
| 4 | 5 | 6 | 7 | | 4 | 1 | 3 |13 |
| 8 | 9 |10 |11 | |12 | 2 | 0 | 6 |
|12 |13 |14 |15 | |11 | 8 | 5 |14 |
A sample map is used to map sample indices to sample numbers.
References gl_context::Const, gl_constants::SampleMap16x, gl_constants::SampleMap2x, gl_constants::SampleMap4x, and gl_constants::SampleMap8x.
Referenced by brw_get_index_type(), and brw_initialize_context_constants().
gen6_upload_push_constants()
void gen6_upload_push_constants (struct brw_context * brw, const struct gl_program * prog, const struct brw_stage_prog_data * prog_data, struct brw_stage_state * stage_state)
Creates a streamed BO containing the push constants for the VS or GS on gen6+.
Push constants are constant values (such as GLSL uniforms) that are pre-loaded into a shader stage's register space at thread spawn time.
Not all GLSL uniforms will be uploaded as push constants: The hardware has a limitation of 32 or 64 EU registers (256 or 512 floats) per stage to be uploaded as push constants, while GL 4.4 requires at least 1024 components to be usable for the VS. Plus, currently we always use pull constants instead of push constants when doing variable-index array access.
See brw_curbe.c for the equivalent gen4/5 code.
References brw_state_batch(), brw_context::ctx, gl_program::Parameters, brw_stage_state::push_const_offset, brw_stage_state::push_const_size, and brw_stage_state::stage.
Referenced by brw_depth_writes_enabled(), gen6_upload_gs_push_constants(), gen6_upload_vs_push_constants(), gen6_upload_wm_push_constants(), gen7_upload_tcs_push_constants(), and gen7_upload_tes_push_constants().
gen6_upload_urb()
void gen6_upload_urb (struct brw_context * brw, unsigned vs_size, bool gs_present, unsigned gs_size)
When the GS is not in use, we assign the entire URB space to the VS.
When the GS is in use, we split the URB space evenly between the VS and the GS. This is not ideal, but it's simple.
      URB size / 2                   URB size / 2
_____________-______________ _____________-______________ / \ / \ +----------------------------------------------------------—+ | Vertex Shader Entries | Geometry Shader Entries | +----------------------------------------------------------—+
Sandybridge GT1 has 32kB of URB space, while GT2 has 64kB. (See the Sandybridge PRM, Volume 2, Part 1, Section 1.4.7: 3DSTATE_URB.)
References _3DSTATE_URB, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_mi_flush(), intel_screen::devinfo, GEN6_URB_GS_ENTRIES_SHIFT, GEN6_URB_GS_SIZE_SHIFT, GEN6_URB_VS_ENTRIES_SHIFT, GEN6_URB_VS_SIZE_SHIFT, brw_context::gs_present, brw_context::nr_gs_entries, brw_context::nr_vs_entries, OUT_BATCH, brw_context::screen, brw_context::size, and brw_context::urb.
Referenced by blorp_emit_urb_config(), brw_get_index_type(), and upload_urb().
gen7_begin_transform_feedback()
void gen7_begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj)
References ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH, brw_compute_xfb_vertices_written(), brw_context(), BRW_MAX_XFB_STREAMS, brw_save_primitives_written_counters(), can_do_pipelined_register_writes(), brw_context::gen, GEN7_SO_WRITE_OFFSET, intel_batchbuffer_flush, MI_LOAD_REGISTER_IMM, intel_batchbuffer::needs_sol_reset, OUT_BATCH, brw_transform_feedback_object::primitive_mode, brw_transform_feedback_object::prims_generated, and brw_context::screen.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_emit_cs_stall_flush()
void gen7_emit_cs_stall_flush (struct brw_context * brw)
Emit a PIPE_CONTROL command for gen7 with the CS Stall bit set.
References brw_emit_pipe_control_write(), PIPE_CONTROL_CS_STALL, PIPE_CONTROL_WRITE_IMMEDIATE, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), brw_emit_select_pipeline(), gen7_emit_push_constant_state(), and upload_gs_state().
gen7_emit_depth_stencil_hiz()
void gen7_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References gl_stencil_attrib::_WriteEnabled, ADVANCE_BATCH, BEGIN_BATCH, brw_depth_writes_enabled(), brw_emit_depth_stall_flushes(), BRW_SURFACE_2D, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, GEN7_3DSTATE_CLEAR_PARAMS, GEN7_3DSTATE_DEPTH_BUFFER, GEN7_3DSTATE_HIER_DEPTH_BUFFER, GEN7_3DSTATE_STENCIL_BUFFER, GEN7_MOCS_L3, HSW_STENCIL_ENABLED, brw_context::hw_ctx, intel_get_renderbuffer(), brw_context::is_haswell, intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, brw_context::no_depth_or_stencil, OUT_BATCH, OUT_RELOC, gl_context::Stencil, gl_texture_object::Target, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and translate_tex_target().
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
gen7_emit_push_constant_state()
void gen7_emit_push_constant_state (struct brw_context * brw, unsigned vs_size, unsigned hs_size, unsigned ds_size, unsigned gs_size, unsigned fs_size)
References _3DSTATE_PUSH_CONSTANT_ALLOC_DS, _3DSTATE_PUSH_CONSTANT_ALLOC_GS, _3DSTATE_PUSH_CONSTANT_ALLOC_HS, _3DSTATE_PUSH_CONSTANT_ALLOC_PS, _3DSTATE_PUSH_CONSTANT_ALLOC_VS, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, gen7_emit_cs_stall_flush(), GEN7_PUSH_CONSTANT_BUFFER_OFFSET_SHIFT, brw_context::is_baytrail, brw_context::is_haswell, and OUT_BATCH.
Referenced by brw_get_index_type(), and gen7_allocate_push_constants().
gen7_emit_vs_workaround_flush()
void gen7_emit_vs_workaround_flush (struct brw_context * brw)
From the Ivybridge PRM, Volume 2 Part 1, Section 3.2 (VS Stage Input): "A PIPE_CONTROL with Post-Sync Operation set to 1h and a depth stall needs to be sent just prior to any 3DSTATE_VS, 3DSTATE_URB_VS, 3DSTATE_CONSTANT_VS, 3DSTATE_BINDING_TABLE_POINTER_VS, 3DSTATE_SAMPLER_STATE_POINTER_VS command.
Only one PIPE_CONTROL needs to be sent before any combination of VS associated 3DSTATE."
References brw_emit_pipe_control_write(), brw_context::gen, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_WRITE_IMMEDIATE, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), gen6_upload_vs_push_constants(), gen7_emit_sampler_state_pointers_xs(), gen7_upload_urb(), and upload_vs_state().
gen7_end_transform_feedback()
void gen7_end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References brw_context(), brw_save_primitives_written_counters(), gl_transform_feedback_object::Paused, and brw_transform_feedback_object::vertices_written_valid.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_pause_transform_feedback()
void gen7_pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_emit_mi_flush(), brw_save_primitives_written_counters(), brw_context::gen, GEN7_SO_WRITE_OFFSET, MI_STORE_REGISTER_MEM, brw_transform_feedback_object::offset_bo, OUT_BATCH, and OUT_RELOC.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_resume_transform_feedback()
void gen7_resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_save_primitives_written_counters(), brw_context::gen, GEN7_MI_LOAD_REGISTER_MEM, GEN7_SO_WRITE_OFFSET, brw_transform_feedback_object::offset_bo, OUT_BATCH, and OUT_RELOC.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_upload_urb()
void gen7_upload_urb (struct brw_context * brw, unsigned vs_size, bool gs_present, bool tess_present)
References _3DSTATE_URB_VS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, BRW_NEW_CONTEXT, BRW_NEW_URB_SIZE, brw_context::ctx, intel_screen::devinfo, brw_context::dsize, brw_context::gen, gen7_emit_vs_workaround_flush(), GEN7_URB_ENTRY_SIZE_SHIFT, GEN7_URB_STARTING_ADDRESS_SHIFT, brw_context::gs, brw_context::gs_present, brw_context::gsize, brw_context::gt, brw_context::hsize, brw_context::is_baytrail, brw_context::is_haswell, gl_context::NewDriverState, OUT_BATCH, brw_stage_state::prog_data, brw_context::screen, brw_context::size, brw_context::tcs, brw_context::tes, brw_context::tess_present, brw_context::urb, brw_context::vs, and brw_context::vsize.
Referenced by blorp_emit_urb_config(), brw_get_index_type(), and upload_urb().
gen8_emit_3dstate_multisample()
void gen8_emit_3dstate_multisample (struct brw_context * brw, unsigned num_samp)
3DSTATE_MULTISAMPLE
References ADVANCE_BATCH, BEGIN_BATCH, GEN8_3DSTATE_MULTISAMPLE, MS_PIXEL_LOCATION_CENTER, and OUT_BATCH.
Referenced by brw_get_index_type(), gen8_hiz_exec(), and upload_multisample_state().
gen8_emit_3dstate_sample_pattern()
void gen8_emit_3dstate_sample_pattern (struct brw_context * brw)
3DSTATE_SAMPLE_PATTERN
References _3DSTATE_SAMPLE_PATTERN, ADVANCE_BATCH, BEGIN_BATCH, brw_multisample_positions_16x, brw_multisample_positions_1x_2x, brw_multisample_positions_4x, brw_multisample_positions_8x, and OUT_BATCH.
Referenced by brw_get_index_type(), and brw_upload_initial_gpu_state().
gen8_emit_depth_stencil_hiz()
void gen8_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References gl_stencil_attrib::_WriteEnabled, brw_depth_writes_enabled(), brw_depthbuffer_format(), BRW_SURFACE_2D, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, emit_depth_packets(), brw_context::gen, intel_get_renderbuffer(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::Stencil, gl_texture_object::Target, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and translate_tex_target().
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
gen8_hiz_exec()
void gen8_hiz_exec (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Emit packets to perform a depth/HiZ resolve or fast depth/stencil clear.
See the "Optimized Depth Buffer Clear and/or Stencil Buffer Clear" section of the hardware documentation for details.
References _3DSTATE_DRAWING_RECTANGLE, _3DSTATE_WM_HZ_OP, _NEW_BUFFERS, _NEW_DEPTH, _NEW_MULTISAMPLE, ADVANCE_BATCH, BEGIN_BATCH, brw_context::bo, brw_depth_format(), brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), brw_render_cache_set_add_bo(), BRW_SURFACE_2D, emit_depth_packets(), brw_context::gen, gen8_emit_3dstate_multisample(), GEN8_WM_HZ_DEPTH_CLEAR, GEN8_WM_HZ_DEPTH_RESOLVE, GEN8_WM_HZ_FULL_SURFACE_DEPTH_CLEAR, GEN8_WM_HZ_HIZ_RESOLVE, gen8_write_pma_stall_bits(), brw_context::NewGLState, brw_context::num_samples, OUT_BATCH, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_WRITE_IMMEDIATE, SET_FIELD, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), and intel_hiz_exec().
gen9_use_linear_1d_layout()
bool gen9_use_linear_1d_layout (const struct brw_context * brw, const struct intel_mipmap_tree * mt)
References _mesa_get_format_base_format(), and brw_context::gen.
Referenced by brw_depth_writes_enabled(), brw_miptree_layout_texture_array(), and intel_miptree_set_total_width_height().
get_hw_prim_for_gl_prim()
uint32_t get_hw_prim_for_gl_prim (int mode)
References prim_to_hw_prim.
Referenced by brw_depth_writes_enabled(), brw_set_prim(), and gen6_set_prim().
hsw_begin_transform_feedback()
void hsw_begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj)
BeginTransformFeedback() driver hook.
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), BRW_MAX_XFB_STREAMS, brw_store_data_imm64(), brw_context::gen, GEN7_SO_WRITE_OFFSET, MI_LOAD_REGISTER_IMM, OUT_BATCH, brw_transform_feedback_object::prim_count_bo, brw_transform_feedback_object::primitive_mode, save_prim_start_values(), TALLY_OFFSET, and brw_transform_feedback_object::zero_offsets.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
hsw_end_transform_feedback()
void hsw_end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
EndTransformFeedback() driver hook.
References brw_context(), and tally_prims_written().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
hsw_init_queryobj_functions()
void hsw_init_queryobj_functions (struct dd_function_table * functions)
References gen6_init_queryobj_functions(), hsw_store_query_result(), and dd_function_table::StoreQueryResult.
Referenced by brw_init_driver_functions().
hsw_overflow_result_to_gpr0()
void hsw_overflow_result_to_gpr0 (struct brw_context * brw, struct brw_query_object * query, int count)
hsw_queryobj.c
References calc_overflow_to_gpr0(), and gpr0_to_bool().
Referenced by hsw_result_to_gpr0(), and set_predicate_for_overflow_query().
hsw_pause_transform_feedback()
void hsw_pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
PauseTransformFeedback() driver hook.
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_emit_mi_flush(), BRW_MAX_XFB_STREAMS, GEN7_SO_WRITE_OFFSET, brw_context::is_haswell, MI_STORE_REGISTER_MEM, brw_transform_feedback_object::offset_bo, OUT_BATCH, OUT_RELOC, and tally_prims_written().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
hsw_resume_transform_feedback()
void hsw_resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
ResumeTransformFeedback() driver hook.
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), BRW_MAX_XFB_STREAMS, GEN7_MI_LOAD_REGISTER_MEM, GEN7_SO_WRITE_OFFSET, brw_context::is_haswell, brw_transform_feedback_object::offset_bo, OUT_BATCH, OUT_RELOC, and save_prim_start_values().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
intel_prepare_render()
void intel_prepare_render (struct brw_context * brw)
intel_prepare_render should be called anywhere that curent read/drawbuffer state is required.
References _mesa_is_front_buffer_drawing(), brw_context::ctx, gl_context::DrawBuffer, brw_context::driContext, brw_context::front_buffer_dirty, and intel_update_renderbuffers().
Referenced by brw_blorp_copytexsubimage(), brw_clear(), brw_try_draw_prims(), do_blit_bitmap(), do_blit_copypixels(), do_blit_drawpixels(), intel_blit_framebuffer_with_blitter(), intel_copy_texsubimage(), intel_map_renderbuffer(), intelDrawBuffer(), intelMakeCurrent(), intelReadBuffer(), intelReadPixels(), and try_blorp_blit().
intel_resolve_for_dri2_flush()
void intel_resolve_for_dri2_flush (struct brw_context * brw, __DRIdrawable * drawable)
References BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, brw_context::gen, intel_get_renderbuffer(), intel_miptree_resolve_color(), intel_renderbuffer_downsample(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by intel_dri2_flush_with_flags(), and intel_flush_front().
intel_translate_compare_func()
int intel_translate_compare_func (GLenum func)
References BRW_COMPAREFUNCTION_ALWAYS, BRW_COMPAREFUNCTION_EQUAL, BRW_COMPAREFUNCTION_GEQUAL, BRW_COMPAREFUNCTION_GREATER, BRW_COMPAREFUNCTION_LEQUAL, BRW_COMPAREFUNCTION_LESS, BRW_COMPAREFUNCTION_NEVER, and BRW_COMPAREFUNCTION_NOTEQUAL.
Referenced by brw_get_index_type(), gen6_upload_blend_state(), gen6_upload_depth_stencil_state(), gen8_upload_blend_state(), and upload_cc_unit().
intel_translate_logic_op()
int intel_translate_logic_op (GLenum opcode)
References BRW_LOGICOPFUNCTION_AND, BRW_LOGICOPFUNCTION_AND_INVERTED, BRW_LOGICOPFUNCTION_AND_REVERSE, BRW_LOGICOPFUNCTION_CLEAR, BRW_LOGICOPFUNCTION_COPY, BRW_LOGICOPFUNCTION_COPY_INVERTED, BRW_LOGICOPFUNCTION_EQUIV, BRW_LOGICOPFUNCTION_INVERT, BRW_LOGICOPFUNCTION_NAND, BRW_LOGICOPFUNCTION_NOOP, BRW_LOGICOPFUNCTION_NOR, BRW_LOGICOPFUNCTION_OR, BRW_LOGICOPFUNCTION_OR_INVERTED, BRW_LOGICOPFUNCTION_OR_REVERSE, BRW_LOGICOPFUNCTION_SET, and BRW_LOGICOPFUNCTION_XOR.
Referenced by brw_get_index_type(), gen6_upload_blend_state(), gen8_upload_blend_state(), and upload_cc_unit().
intel_translate_shadow_compare_func()
int intel_translate_shadow_compare_func (GLenum func)
References BRW_COMPAREFUNCTION_ALWAYS, BRW_COMPAREFUNCTION_EQUAL, BRW_COMPAREFUNCTION_GEQUAL, BRW_COMPAREFUNCTION_GREATER, BRW_COMPAREFUNCTION_LEQUAL, BRW_COMPAREFUNCTION_LESS, BRW_COMPAREFUNCTION_NEVER, and BRW_COMPAREFUNCTION_NOTEQUAL.
Referenced by brw_get_index_type(), and brw_update_sampler_state().
intel_translate_stencil_op()
int intel_translate_stencil_op (GLenum op)
References BRW_STENCILOP_DECR, BRW_STENCILOP_DECRSAT, BRW_STENCILOP_INCR, BRW_STENCILOP_INCRSAT, BRW_STENCILOP_INVERT, BRW_STENCILOP_KEEP, BRW_STENCILOP_REPLACE, and BRW_STENCILOP_ZERO.
Referenced by brw_get_index_type(), gen6_upload_depth_stencil_state(), and upload_cc_unit().
intel_update_renderbuffers()
void intel_update_renderbuffers (__DRIcontext * context, __DRIdrawable * drawable)
References brw_context::ctx, intel_screen::driScrnPriv, intel_update_dri2_buffers(), intel_update_image_buffers(), and brw_context::screen.
Referenced by intel_prepare_render(), and intelSetTexBuffer2().
intelInitClearFuncs()
void intelInitClearFuncs (struct dd_function_table * functions)
References brw_clear(), and dd_function_table::Clear.
Referenced by brw_init_driver_functions().
intelInitExtensions()
void intelInitExtensions (struct gl_context * ctx)
Initializes potential list of extensions if ctx == NULL, or actually enables extensions for a context.
References _mesa_override_glsl_version(), gl_extensions::AMD_seamless_cubemap_per_texture, gl_extensions::AMD_vertex_shader_layer, gl_extensions::AMD_vertex_shader_viewport_index, gl_extensions::ANDROID_extension_pack_es31a, gl_extensions::ANGLE_texture_compression_dxt, gl_context::API, API_OPENGL_CORE, gl_extensions::APPLE_object_purgeable, gl_extensions::ARB_arrays_of_arrays, gl_extensions::ARB_base_instance, gl_extensions::ARB_blend_func_extended, gl_extensions::ARB_buffer_storage, gl_extensions::ARB_clear_texture, gl_extensions::ARB_clip_control, gl_extensions::ARB_color_buffer_float, gl_extensions::ARB_compute_shader, gl_extensions::ARB_conditional_render_inverted, gl_extensions::ARB_conservative_depth, gl_extensions::ARB_copy_image, gl_extensions::ARB_cull_distance, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_derivative_control, gl_extensions::ARB_draw_buffers_blend, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_indirect, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_enhanced_layouts, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_ES3_1_compatibility, gl_extensions::ARB_ES3_2_compatibility, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_explicit_uniform_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_layer_viewport, gl_extensions::ARB_fragment_program, gl_extensions::ARB_fragment_program_shadow, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_gpu_shader5, gl_extensions::ARB_gpu_shader_fp64, gl_extensions::ARB_gpu_shader_int64, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_instanced_arrays, gl_extensions::ARB_internalformat_query, gl_extensions::ARB_internalformat_query2, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_pipeline_statistics_query, gl_extensions::ARB_point_sprite, gl_extensions::ARB_post_depth_coverage, gl_extensions::ARB_query_buffer_object, gl_extensions::ARB_robust_buffer_access_behavior, gl_extensions::ARB_sample_shading, gl_extensions::ARB_seamless_cube_map, gl_extensions::ARB_shader_atomic_counter_ops, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_shader_bit_encoding, gl_extensions::ARB_shader_clock, gl_extensions::ARB_shader_draw_parameters, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shader_image_size, gl_extensions::ARB_shader_precision, gl_extensions::ARB_shader_stencil_export, gl_extensions::ARB_shader_storage_buffer_object, gl_extensions::ARB_shader_subroutine, gl_extensions::ARB_shader_texture_image_samples, gl_extensions::ARB_shader_texture_lod, gl_extensions::ARB_shader_viewport_layer_array, gl_extensions::ARB_shading_language_420pack, gl_extensions::ARB_shading_language_packing, gl_extensions::ARB_shadow, gl_extensions::ARB_stencil_texturing, gl_extensions::ARB_sync, gl_extensions::ARB_tessellation_shader, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_buffer_object_rgb32, gl_extensions::ARB_texture_buffer_range, gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_gather, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ARB_texture_multisample, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_query_levels, gl_extensions::ARB_texture_query_lod, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::ARB_texture_stencil8, gl_extensions::ARB_texture_view, gl_extensions::ARB_timer_query, gl_extensions::ARB_transform_feedback2, gl_extensions::ARB_transform_feedback3, gl_extensions::ARB_transform_feedback_instanced, gl_extensions::ARB_transform_feedback_overflow_query, gl_extensions::ARB_uniform_buffer_object, gl_extensions::ARB_vertex_attrib_64bit, gl_extensions::ARB_vertex_program, gl_extensions::ARB_vertex_shader, gl_extensions::ARB_vertex_type_10f_11f_11f_rev, gl_extensions::ARB_vertex_type_2_10_10_10_rev, gl_extensions::ARB_viewport_array, gl_extensions::ATI_separate_stencil, gl_extensions::ATI_texture_env_combine3, brw_context(), can_do_compute_dispatch(), can_do_mi_math_and_lrr(), can_do_pipelined_register_writes(), can_do_predicate_writes(), gl_context::Const, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_framebuffer_multisample, gl_extensions::EXT_framebuffer_multisample_blit_scaled, gl_extensions::EXT_framebuffer_sRGB, gl_extensions::EXT_gpu_program_parameters, gl_extensions::EXT_packed_float, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_polygon_offset_clamp, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_shader_integer_mix, gl_extensions::EXT_shader_samples_identical, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_env_dot3, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_timer_query, gl_extensions::EXT_transform_feedback, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, brw_context::gen, gl_constants::GLSLVersion, intel_screen::hw_has_timestamp, gl_extensions::INTEL_conservative_rasterization, gl_extensions::INTEL_performance_query, brw_context::is_baytrail, brw_context::is_g4x, brw_context::is_haswell, gl_extensions::KHR_blend_equation_advanced, gl_extensions::KHR_blend_equation_advanced_coherent, gl_extensions::KHR_robustness, gl_extensions::KHR_texture_compression_astc_ldr, gl_extensions::KHR_texture_compression_astc_sliced_3d, gl_constants::MaxComputeWorkGroupSize, gl_context::Mesa_DXTn, gl_extensions::MESA_pack_invert, gl_extensions::MESA_shader_framebuffer_fetch, gl_extensions::MESA_shader_framebuffer_fetch_non_coherent, gl_extensions::MESA_shader_integer_functions, gl_extensions::NV_conditional_render, gl_extensions::NV_primitive_restart, gl_extensions::NV_texture_barrier, gl_extensions::NV_texture_env_combine4, gl_extensions::NV_texture_rectangle, gl_extensions::OES_compressed_ETC1_RGB8_texture, gl_extensions::OES_copy_image, gl_extensions::OES_depth_texture_cube_map, gl_extensions::OES_draw_texture, gl_extensions::OES_EGL_image, gl_extensions::OES_EGL_image_external, gl_extensions::OES_geometry_shader, gl_extensions::OES_primitive_bounding_box, gl_extensions::OES_sample_variables, gl_extensions::OES_standard_derivatives, gl_extensions::OES_texture_buffer, gl_extensions::OES_texture_cube_map_array, gl_extensions::OES_texture_float, gl_extensions::OES_texture_float_linear, gl_extensions::OES_texture_half_float, gl_extensions::OES_texture_half_float_linear, gl_extensions::OES_viewport_array, brw_context::optionCache, brw_context::predicate, brw_context::screen, brw_context::supported, and gl_extensions::TDFX_texture_compression_FXT1.
Referenced by brw_get_index_type(), and brwCreateContext().
key_debug()
static bool key_debug (struct brw_context * brw, const char * name, int a, int b) inline static
References brw_state_flags::brw, brw_alloc_stage_scratch(), brw_collect_and_report_shader_time(), brw_destroy_shader_time(), brw_get_scratch_bo(), brw_get_shader_time_index(), brw_get_vertex_surface_type(), brw_init_shader_time(), brw_select_clip_planes(), brw_upload_cs_urb_state(), brw_upload_urb_fence(), and brwInitFragProgFuncs().
Referenced by brw_debug_recompile_sampler_key(), brw_tcs_debug_recompile(), brw_tes_debug_recompile(), brw_vs_debug_recompile(), and brw_wm_debug_recompile().
Variable Documentation
brw_vendor_string
const char* const brw_vendor_string
Referenced by brw_query_renderer_string(), and intel_get_string().