Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clip.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_util.h"
#include "brw_state.h"
#include "brw_clip.h"
#include "util/ralloc.h"
Macros
#define FRONT_UNFILLED_BIT 0x1
#define BACK_UNFILLED_BIT 0x2
Functions
static void compile_clip_prog (struct brw_context *brw, struct brw_clip_prog_key *key)
void brw_upload_clip_prog (struct brw_context *brw)
Macro Definition Documentation
BACK_UNFILLED_BIT
#define BACK_UNFILLED_BIT 0x2
FRONT_UNFILLED_BIT
#define FRONT_UNFILLED_BIT 0x1
Function Documentation
brw_upload_clip_prog()
void brw_upload_clip_prog (struct brw_context * brw)
References gl_polygon_attrib::_FrontBit, gl_framebuffer::_MRD, _NEW_BUFFERS, _NEW_LIGHT, _NEW_POLYGON, _NEW_TRANSFORM, brw_clip_prog_key::attrs, gl_polygon_attrib::BackMode, brw_context::base, BRW_CACHE_CLIP_PROG, BRW_CLIPMODE_CLIP_NON_REJECTED, BRW_CLIPMODE_KERNEL_CLIP, BRW_CLIPMODE_NORMAL, BRW_CLIPMODE_REJECT_ALL, BRW_NEW_BLORP, BRW_NEW_FS_PROG_DATA, BRW_NEW_REDUCED_PRIMITIVE, BRW_NEW_VUE_MAP_GEOM_OUT, brw_search_cache(), brw_state_dirty(), brw_context::cache, brw_context::clip, CLIP_CULL, CLIP_FILL, CLIP_LINE, brw_clip_prog_key::clip_mode, CLIP_POINT, gl_transform_attrib::ClipPlanesEnabled, compile_clip_prog(), brw_clip_prog_key::contains_flat_varying, brw_clip_prog_key::contains_noperspective_varying, brw_clip_prog_key::copy_bfc_ccw, brw_clip_prog_key::copy_bfc_cw, brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, brw_clip_prog_key::do_unfilled, gl_context::DrawBuffer, brw_clip_prog_key::fill_ccw, brw_clip_prog_key::fill_cw, gl_polygon_attrib::FrontMode, brw_context::gen, GLuint, brw_clip_prog_key::interp_mode, gl_context::Light, gl_light_attrib::Model, brw_clip_prog_key::nr_userclip, brw_clip_prog_key::offset_ccw, brw_clip_prog_key::offset_clamp, brw_clip_prog_key::offset_cw, brw_clip_prog_key::offset_factor, brw_clip_prog_key::offset_units, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, gl_context::Polygon, brw_clip_prog_key::primitive, brw_stage_state::prog_data, brw_context::prog_data, brw_context::prog_offset, gl_light_attrib::ProvokingVertex, brw_clip_prog_key::pv_first, brw_context::reduced_primitive, gl_context::Transform, gl_lightmodel::TwoSide, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by brw_upload_programs().
compile_clip_prog()
static void compile_clip_prog (struct brw_context * brw, struct brw_clip_prog_key * key) static
References BRW_CACHE_CLIP_PROG, brw_emit_line_clip(), brw_emit_point_clip(), brw_emit_tri_clip(), brw_emit_unfilled_clip(), brw_upload_cache(), brw_context::cache, brw_context::clip, brw_clip_prog_key::clip_mode, brw_clip_prog_data::clip_mode, intel_screen::devinfo, brw_clip_prog_key::do_unfilled, brw_clip_compile::func, GLuint, brw_clip_compile::key, brw_clip_compile::nr_regs, brw_clip_prog_key::primitive, brw_clip_compile::prog_data, brw_context::prog_data, brw_context::prog_offset, brw_context::screen, brw_clip_compile::vue_map, and brw_context::vue_map_geom_out.
Referenced by brw_upload_clip_prog().