Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_sf_emit.c File Reference
#include "main/macros.h"
#include "main/enums.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_util.h"
#include "brw_sf.h"
Functions
static int vert_reg_to_vue_slot (struct brw_sf_compile *c, GLuint reg, int half)
Determine the vue slot corresponding to the given half of the given register.
static int vert_reg_to_varying (struct brw_sf_compile *c, GLuint reg, int half)
Determine the varying corresponding to the given half of the given register.
static struct brw_reg get_vue_slot (struct brw_sf_compile *c, struct brw_reg vert, int vue_slot)
Determine the register corresponding to the given vue slot.
static struct brw_reg get_varying (struct brw_sf_compile *c, struct brw_reg vert, GLuint varying)
Determine the register corresponding to the given varying.
static bool have_attr (struct brw_sf_compile *c, GLuint attr)
static void copy_bfc (struct brw_sf_compile *c, struct brw_reg vert)
static void do_twoside_color (struct brw_sf_compile *c)
static void copy_flatshaded_attributes (struct brw_sf_compile *c, struct brw_reg dst, struct brw_reg src)
static int count_flatshaded_attributes (struct brw_sf_compile *c)
static void do_flatshade_triangle (struct brw_sf_compile *c)
static void do_flatshade_line (struct brw_sf_compile *c)
static void alloc_regs (struct brw_sf_compile *c)
static void copy_z_inv_w (struct brw_sf_compile *c)
static void invert_det (struct brw_sf_compile *c)
static bool calculate_masks (struct brw_sf_compile *c, GLuint reg, GLushort *pc, GLushort *pc_persp, GLushort *pc_linear)
static uint16_t calculate_point_sprite_mask (struct brw_sf_compile *c, GLuint reg)
static void set_predicate_control_flag_value (struct brw_codegen *p, struct brw_sf_compile *c, unsigned value)
void brw_emit_tri_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_line_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_point_sprite_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_point_setup (struct brw_sf_compile *c, bool allocate)
void brw_emit_anyprim_setup (struct brw_sf_compile *c)
Function Documentation
alloc_regs()
static void alloc_regs (struct brw_sf_compile * c) static
References brw_sf_compile::a1_sub_a0, brw_sf_compile::a2_sub_a0, brw_sf_compile::det, brw_sf_compile::dx0, brw_sf_compile::dx2, brw_sf_compile::dy0, brw_sf_compile::dy2, GLuint, brw_sf_compile::inv_det, brw_sf_compile::inv_w, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_attr_regs, brw_sf_compile::nr_verts, brw_sf_compile::prog_data, brw_sf_compile::pv, brw_sf_compile::tmp, brw_sf_prog_data::total_grf, brw_sf_compile::vert, and brw_sf_compile::z.
Referenced by brw_emit_anyprim_setup(), brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), and brw_emit_tri_setup().
brw_emit_anyprim_setup()
void brw_emit_anyprim_setup (struct brw_sf_compile * c)
References alloc_regs(), brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), brw_emit_tri_setup(), BRW_SPRITE_POINT_ENABLE, brw_sf_compile::func, brw_sf_compile::nr_verts, and brw_sf_compile::tmp.
Referenced by compile_sf_prog().
brw_emit_line_setup()
void brw_emit_line_setup (struct brw_sf_compile * c, bool allocate)
References brw_sf_compile::a1_sub_a0, alloc_regs(), calculate_masks(), brw_sf_prog_key::contains_flat_varying, copy_z_inv_w(), do_flatshade_line(), brw_sf_compile::dx0, brw_sf_compile::dy0, brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_det, brw_sf_compile::inv_w, invert_det(), brw_sf_compile::key, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), brw_sf_compile::tmp, and brw_sf_compile::vert.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
brw_emit_point_setup()
void brw_emit_point_setup (struct brw_sf_compile * c, bool allocate)
References alloc_regs(), calculate_masks(), copy_z_inv_w(), brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_w, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), and brw_sf_compile::vert.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
brw_emit_point_sprite_setup()
void brw_emit_point_sprite_setup (struct brw_sf_compile * c, bool allocate)
References alloc_regs(), calculate_masks(), calculate_point_sprite_mask(), copy_z_inv_w(), brw_sf_compile::dx0, brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_w, brw_sf_compile::key, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), brw_sf_prog_key::sprite_origin_lower_left, brw_sf_compile::tmp, brw_sf_compile::vert, WRITEMASK_W, WRITEMASK_X, and WRITEMASK_Y.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
brw_emit_tri_setup()
void brw_emit_tri_setup (struct brw_sf_compile * c, bool allocate)
References brw_sf_compile::a1_sub_a0, brw_sf_compile::a2_sub_a0, alloc_regs(), calculate_masks(), brw_sf_prog_key::contains_flat_varying, copy_z_inv_w(), do_flatshade_triangle(), brw_sf_prog_key::do_twoside_color, do_twoside_color(), brw_sf_compile::dx0, brw_sf_compile::dx2, brw_sf_compile::dy0, brw_sf_compile::dy2, brw_sf_compile::flag_value, brw_sf_compile::func, GLuint, GLushort, brw_sf_compile::inv_det, brw_sf_compile::inv_w, invert_det(), brw_sf_compile::key, brw_sf_compile::m1Cx, brw_sf_compile::m2Cy, brw_sf_compile::m3C0, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, set_predicate_control_flag_value(), brw_sf_compile::tmp, and brw_sf_compile::vert.
Referenced by brw_emit_anyprim_setup(), and compile_sf_prog().
calculate_masks()
static bool calculate_masks (struct brw_sf_compile * c, GLuint reg, GLushort * pc, GLushort * pc_persp, GLushort * pc_linear) static
References brw_sf_prog_key::interp_mode, brw_sf_compile::key, brw_sf_compile::nr_setup_regs, vert_reg_to_varying(), and vert_reg_to_vue_slot().
Referenced by brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), and brw_emit_tri_setup().
calculate_point_sprite_mask()
static uint16_t calculate_point_sprite_mask (struct brw_sf_compile * c, GLuint reg) static
References brw_sf_compile::key, brw_sf_prog_key::point_sprite_coord_replace, and vert_reg_to_varying().
Referenced by brw_emit_point_sprite_setup().
copy_bfc()
static void copy_bfc (struct brw_sf_compile * c, struct brw_reg vert) static
References brw_sf_compile::func, get_varying(), GLuint, and have_attr().
Referenced by do_twoside_color().
copy_flatshaded_attributes()
static void copy_flatshaded_attributes (struct brw_sf_compile * c, struct brw_reg dst, struct brw_reg src) static
References brw_sf_compile::func, get_vue_slot(), brw_sf_prog_key::interp_mode, brw_sf_compile::key, and brw_sf_compile::vue_map.
Referenced by do_flatshade_line(), and do_flatshade_triangle().
copy_z_inv_w()
static void copy_z_inv_w (struct brw_sf_compile * c) static
References brw_sf_compile::func, GLuint, brw_sf_compile::nr_verts, brw_sf_compile::vert, and brw_sf_compile::z.
Referenced by brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), and brw_emit_tri_setup().
count_flatshaded_attributes()
static int count_flatshaded_attributes (struct brw_sf_compile * c) static
References brw_sf_prog_key::interp_mode, brw_sf_compile::key, and brw_sf_compile::vue_map.
Referenced by do_flatshade_line(), and do_flatshade_triangle().
do_flatshade_line()
static void do_flatshade_line (struct brw_sf_compile * c) static
References copy_flatshaded_attributes(), count_flatshaded_attributes(), brw_sf_compile::func, GLuint, brw_sf_compile::key, brw_sf_prog_key::primitive, brw_sf_compile::pv, SF_UNFILLED_TRIS, and brw_sf_compile::vert.
Referenced by brw_emit_line_setup().
do_flatshade_triangle()
static void do_flatshade_triangle (struct brw_sf_compile * c) static
References copy_flatshaded_attributes(), count_flatshaded_attributes(), brw_sf_compile::func, GLuint, brw_sf_compile::key, brw_sf_prog_key::primitive, brw_sf_compile::pv, SF_UNFILLED_TRIS, and brw_sf_compile::vert.
Referenced by brw_emit_tri_setup().
do_twoside_color()
static void do_twoside_color (struct brw_sf_compile * c) static
References copy_bfc(), brw_sf_compile::det, brw_sf_prog_key::frontface_ccw, brw_sf_compile::func, GLuint, have_attr(), brw_sf_compile::key, brw_sf_compile::nr_verts, brw_sf_prog_key::primitive, SF_UNFILLED_TRIS, and brw_sf_compile::vert.
Referenced by brw_emit_tri_setup().
get_varying()
static struct brw_reg get_varying (struct brw_sf_compile * c, struct brw_reg vert, GLuint varying) static
Determine the register corresponding to the given varying.
References get_vue_slot(), and GLuint.
Referenced by copy_bfc().
get_vue_slot()
static struct brw_reg get_vue_slot (struct brw_sf_compile * c, struct brw_reg vert, int vue_slot) static
Determine the register corresponding to the given vue slot.
References GLuint, and sub().
Referenced by copy_flatshaded_attributes(), and get_varying().
have_attr()
static bool have_attr (struct brw_sf_compile * c, GLuint attr) static
References brw_sf_prog_key::attrs, BITFIELD64_BIT, and brw_sf_compile::key.
Referenced by copy_bfc(), and do_twoside_color().
invert_det()
static void invert_det (struct brw_sf_compile * c) static
References brw_sf_compile::det, brw_sf_compile::func, and brw_sf_compile::inv_det.
Referenced by brw_emit_line_setup(), and brw_emit_tri_setup().
set_predicate_control_flag_value()
static void set_predicate_control_flag_value (struct brw_codegen * p, struct brw_sf_compile * c, unsigned value) static
References brw_sf_compile::flag_value.
Referenced by brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), and brw_emit_tri_setup().
vert_reg_to_varying()
static int vert_reg_to_varying (struct brw_sf_compile * c, GLuint reg, int half) inline static
Determine the varying corresponding to the given half of the given register.
half=0 means the first half of a register, half=1 means the second half.
References vert_reg_to_vue_slot(), and brw_sf_compile::vue_map.
Referenced by calculate_masks(), and calculate_point_sprite_mask().
vert_reg_to_vue_slot()
static int vert_reg_to_vue_slot (struct brw_sf_compile * c, GLuint reg, int half) inline static
Determine the vue slot corresponding to the given half of the given register.
References brw_sf_compile::urb_entry_read_offset.
Referenced by calculate_masks(), and vert_reg_to_varying().