Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_compute.c File Reference
#include <sys/errno.h>
#include "main/condrender.h"
#include "main/mtypes.h"
#include "main/state.h"
#include "brw_context.h"
#include "brw_draw.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "brw_defines.h"
Functions
static void prepare_indirect_gpgpu_walker (struct brw_context *brw)
static void brw_emit_gpgpu_walker (struct brw_context *brw)
static void brw_dispatch_compute_common (struct gl_context *ctx)
static void brw_dispatch_compute (struct gl_context *ctx, const GLuint *num_groups)
static void brw_dispatch_compute_indirect (struct gl_context *ctx, GLintptr indirect)
void brw_init_compute_functions (struct dd_function_table *functions)
Function Documentation
brw_dispatch_compute()
static void brw_dispatch_compute (struct gl_context * ctx, const GLuint * num_groups) static
References brw_context(), brw_dispatch_compute_common(), BRW_NEW_CS_WORK_GROUPS, brw_context::compute, gl_context::NewDriverState, brw_context::num_work_groups, and brw_context::num_work_groups_bo.
Referenced by brw_init_compute_functions().
brw_dispatch_compute_common()
static void brw_dispatch_compute_common (struct gl_context * ctx) static
References _mesa_check_conditional_render(), _mesa_update_state(), brw_context::always_flush_batch, brw_context::batch, intel_batchbuffer::bo, brw_compute_state_finished(), brw_context(), brw_emit_gpgpu_walker(), BRW_MAX_TEX_UNIT, brw_program_cache_check_size(), brw_upload_compute_state(), brw_validate_textures(), intel_batchbuffer_flush, intel_batchbuffer_require_space(), intel_batchbuffer_reset_to_saved(), intel_batchbuffer_save_state(), gl_context::NewState, brw_context::no_batch_wrap, RENDER_RING, and ret().
Referenced by brw_dispatch_compute(), and brw_dispatch_compute_indirect().
brw_dispatch_compute_indirect()
static void brw_dispatch_compute_indirect (struct gl_context * ctx, GLintptr indirect) static
References brw_context(), brw_dispatch_compute_common(), BRW_NEW_CS_WORK_GROUPS, brw_context::compute, gl_context::DispatchIndirectBuffer, GLuint, intel_buffer_object(), intel_bufferobj_buffer(), gl_context::NewDriverState, brw_context::num_work_groups, brw_context::num_work_groups_bo, and brw_context::num_work_groups_offset.
Referenced by brw_init_compute_functions().
brw_emit_gpgpu_walker()
static void brw_emit_gpgpu_walker (struct brw_context * brw) static
References ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_context::compute, brw_context::cs, brw_context::gen, GEN7_GPGPU_INDIRECT_PARAMETER_ENABLE, GEN7_GPGPU_PREDICATE_ENABLE, GLuint, GPGPU_WALKER, MEDIA_STATE_FLUSH, brw_context::num_work_groups, brw_context::num_work_groups_bo, OUT_BATCH, prepare_indirect_gpgpu_walker(), brw_stage_state::prog_data, and SET_FIELD.
Referenced by brw_dispatch_compute_common().
brw_init_compute_functions()
void brw_init_compute_functions (struct dd_function_table * functions)
References brw_dispatch_compute(), brw_dispatch_compute_indirect(), dd_function_table::DispatchCompute, and dd_function_table::DispatchComputeIndirect.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
prepare_indirect_gpgpu_walker()
static void prepare_indirect_gpgpu_walker (struct brw_context * brw) static
References ADVANCE_BATCH, BEGIN_BATCH, brw_load_register_mem(), brw_context::compute, brw_context::gen, GEN7_GPGPU_DISPATCHDIMX, GEN7_GPGPU_DISPATCHDIMY, GEN7_GPGPU_DISPATCHDIMZ, GEN7_MI_PREDICATE, MI_LOAD_REGISTER_IMM, MI_PREDICATE_COMBINEOP_OR, MI_PREDICATE_COMBINEOP_SET, MI_PREDICATE_COMPAREOP_FALSE, MI_PREDICATE_COMPAREOP_SRCS_EQUAL, MI_PREDICATE_LOADOP_LOAD, MI_PREDICATE_LOADOP_LOADINV, MI_PREDICATE_SRC0, MI_PREDICATE_SRC1, brw_context::num_work_groups_bo, brw_context::num_work_groups_offset, and OUT_BATCH.
Referenced by brw_emit_gpgpu_walker().