Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_sf.c File Reference
#include "compiler/nir/nir.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/enums.h"
#include "main/fbobject.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_util.h"
#include "brw_sf.h"
#include "brw_state.h"
#include "util/ralloc.h"
Functions
static void compile_sf_prog (struct brw_context *brw, struct brw_sf_prog_key *key)
void brw_upload_sf_prog (struct brw_context *brw)
Function Documentation
brw_upload_sf_prog()
void brw_upload_sf_prog (struct brw_context * brw)
References gl_polygon_attrib::_FrontBit, _NEW_BUFFERS, _NEW_HINT, _NEW_LIGHT, _NEW_POINT, _NEW_POLYGON, _NEW_PROGRAM, _NEW_TRANSFORM, gl_vertex_program_state::_TwoSideEnabled, brw_sf_prog_key::attrs, brw_context::base, BITFIELD64_BIT, BRW_CACHE_SF_PROG, BRW_NEW_BLORP, BRW_NEW_FS_PROG_DATA, BRW_NEW_REDUCED_PRIMITIVE, BRW_NEW_VUE_MAP_GEOM_OUT, brw_search_cache(), brw_state_dirty(), brw_context::cache, gl_transform_attrib::ClipPlanesEnabled, compile_sf_prog(), brw_sf_prog_key::contains_flat_varying, gl_point_attrib::CoordReplace, brw_context::ctx, brw_sf_prog_key::do_point_coord, brw_sf_prog_key::do_point_sprite, brw_sf_prog_key::do_twoside_color, gl_context::DrawBuffer, gl_light_attrib::Enabled, brw_context::fragment_program, brw_sf_prog_key::frontface_ccw, gl_program::info, brw_sf_prog_key::interp_mode, gl_context::Light, gl_light_attrib::Model, gl_context::Point, brw_sf_prog_key::point_sprite_coord_replace, gl_point_attrib::PointSprite, gl_context::Polygon, brw_sf_prog_key::primitive, brw_stage_state::prog_data, brw_context::prog_data, brw_context::prog_offset, brw_context::reduced_primitive, brw_context::sf, SF_LINES, SF_POINTS, SF_TRIANGLES, SF_UNFILLED_TRIS, brw_sf_prog_key::sprite_origin_lower_left, gl_point_attrib::SpriteOrigin, gl_context::Transform, gl_lightmodel::TwoSide, brw_sf_prog_key::userclip_active, gl_context::VertexProgram, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by brw_upload_programs().
compile_sf_prog()
static void compile_sf_prog (struct brw_context * brw, struct brw_sf_prog_key * key) static
References BRW_CACHE_SF_PROG, brw_emit_anyprim_setup(), brw_emit_line_setup(), brw_emit_point_setup(), brw_emit_point_sprite_setup(), brw_emit_tri_setup(), brw_upload_cache(), brw_context::cache, intel_screen::devinfo, brw_sf_prog_key::do_point_coord, brw_sf_prog_key::do_point_sprite, brw_sf_compile::func, GLuint, brw_sf_compile::key, brw_sf_compile::nr_attr_regs, brw_sf_compile::nr_setup_regs, brw_sf_compile::nr_verts, brw_sf_prog_key::primitive, brw_sf_compile::prog_data, brw_context::prog_data, brw_context::prog_offset, brw_context::screen, brw_context::sf, SF_LINES, SF_POINTS, SF_TRIANGLES, SF_UNFILLED_TRIS, brw_sf_compile::urb_entry_read_offset, brw_sf_prog_data::urb_entry_size, brw_sf_prog_data::urb_read_length, brw_sf_compile::vue_map, and brw_context::vue_map_geom_out.
Referenced by brw_upload_sf_prog().