Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_clear.c File Reference
#include "main/mtypes.h"
#include "main/condrender.h"
#include "swrast/swrast.h"
#include "drivers/common/meta.h"
#include "intel_batchbuffer.h"
#include "intel_blit.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "brw_context.h"
#include "brw_blorp.h"
#include "brw_defines.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_BLIT
Functions
static void debug_mask (const char *name, GLbitfield mask)
static bool noop_scissor (struct gl_framebuffer *fb)
Returns true if the scissor is a noop (cuts out nothing).
static bool brw_fast_clear_depth (struct gl_context *ctx)
Implements fast depth clears on gen6+.
static void brw_clear (struct gl_context *ctx, GLbitfield mask)
Called by ctx->Driver.Clear.
void intelInitClearFuncs (struct dd_function_table *functions)
Variables
static const char * buffer_names []
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_BLIT
Function Documentation
brw_clear()
static void brw_clear (struct gl_context * ctx, GLbitfield mask) static
Called by ctx->Driver.Clear.
References _mesa_check_conditional_render(), _swrast_Clear(), gl_context::API, API_OPENGLES, brw_blorp_clear_color(), brw_context(), brw_fast_clear_depth(), brw_workaround_depthstencil_alignment(), BUFFER_BIT_DEPTH, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_BIT_STENCIL, BUFFER_BITS_COLOR, BUFFER_STENCIL, gl_context::Color, brw_context::ctx, DBG, debug_mask(), gl_context::DrawBuffer, gl_scissor_attrib::EnableFlags, brw_context::front_buffer_dirty, brw_context::gen, intel_get_renderbuffer(), intel_prepare_render(), intel_renderbuffer::mt, noop_scissor(), gl_context::Scissor, and gl_colorbuffer_attrib::sRGBEnabled.
Referenced by intelInitClearFuncs().
brw_fast_clear_depth()
static bool brw_fast_clear_depth (struct gl_context * ctx) static
Implements fast depth clears on gen6+.
Fast clears basically work by setting a flag in each of the subspans represented in the HiZ buffer that says "When you need the depth values for this subspan, it's the hardware's current clear value." Then later rendering can just use the static clear value instead of referencing memory.
The tricky part of the implementation is that you have to have the clear value that was used on the depth buffer in place for all further rendering, at least until a resolve to the real depth buffer happens.
References gl_framebuffer::_DepthMax, gl_framebuffer::Attachment, brw_context(), brw_emit_pipe_control_flush(), BUFFER_DEPTH, gl_depthbuffer_attrib::Clear, gl_context::Depth, gl_context::DrawBuffer, gl_scissor_attrib::EnableFlags, float_as_int(), brw_context::gen, intel_get_renderbuffer(), intel_hiz_exec(), intel_miptree_all_slices_resolve_depth(), intel_renderbuffer_att_set_needs_depth_resolve(), intel_renderbuffer_has_hiz(), intel_renderbuffer::layer_count, gl_framebuffer::MaxNumLayers, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, noop_scissor(), PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, and gl_context::Scissor.
Referenced by brw_clear().
debug_mask()
static void debug_mask (const char * name, GLbitfield mask) static
References BUFFER_COUNT, buffer_names, DBG, DEBUG_BLIT, and GLuint.
Referenced by brw_clear().
intelInitClearFuncs()
void intelInitClearFuncs (struct dd_function_table * functions)
References brw_clear(), and dd_function_table::Clear.
Referenced by brw_init_driver_functions().
noop_scissor()
static bool noop_scissor (struct gl_framebuffer * fb) static
Returns true if the scissor is a noop (cuts out nothing).
References gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Height, and gl_framebuffer::Width.
Referenced by brw_clear(), and brw_fast_clear_depth().
Variable Documentation
buffer_names
const char* buffer_names[] static
Initial value:
= {
   [BUFFER_FRONT_LEFT] = "front",
   [BUFFER_BACK_LEFT] = "back",
   [BUFFER_FRONT_RIGHT] = "front right",
   [BUFFER_BACK_RIGHT] = "back right",
   [BUFFER_DEPTH] = "depth",
   [BUFFER_STENCIL] = "stencil",
   [BUFFER_ACCUM] = "accum",
   [BUFFER_AUX0] = "aux0",
   [BUFFER_COLOR0] = "color0",
   [BUFFER_COLOR1] = "color1",
   [BUFFER_COLOR2] = "color2",
   [BUFFER_COLOR3] = "color3",
   [BUFFER_COLOR4] = "color4",
   [BUFFER_COLOR5] = "color5",
   [BUFFER_COLOR6] = "color6",
   [BUFFER_COLOR7] = "color7",
}
Referenced by debug_mask().