Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_gs.c File Reference
#include "brw_gs.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_ff_gs.h"
#include "compiler/brw_nir.h"
#include "brw_program.h"
#include "compiler/glsl/ir_uniform.h"
Functions
static void brw_gs_debug_recompile (struct brw_context *brw, struct gl_program *prog, const struct brw_gs_prog_key *key)
static void assign_gs_binding_table_offsets (const struct gen_device_info *devinfo, const struct gl_program *prog, struct brw_gs_prog_data *prog_data)
static bool brw_codegen_gs_prog (struct brw_context *brw, struct brw_program *gp, struct brw_gs_prog_key *key)
static bool brw_gs_state_dirty (const struct brw_context *brw)
void brw_gs_populate_key (struct brw_context *brw, struct brw_gs_prog_key *key)
void brw_upload_gs_prog (struct brw_context *brw)
bool brw_gs_precompile (struct gl_context *ctx, struct gl_program *prog)
Function Documentation
assign_gs_binding_table_offsets()
static void assign_gs_binding_table_offsets (const struct gen_device_info * devinfo, const struct gl_program * prog, struct brw_gs_prog_data * prog_data) static
References brw_assign_common_binding_table_offsets().
Referenced by brw_codegen_gs_prog().
brw_codegen_gs_prog()
static bool brw_codegen_gs_prog (struct brw_context * brw, struct brw_program * gp, struct brw_gs_prog_key * key) static
References _mesa_problem(), assign_gs_binding_table_offsets(), brw_context::base, brw_context::batch, brw_alloc_stage_scratch(), BRW_CACHE_GS_PROG, brw_get_shader_time_index(), brw_gs_debug_recompile(), brw_nir_setup_glsl_uniforms(), brw_upload_cache(), brw_context::cache, brw_program::compiled_once, intel_screen::compiler, intel_screen::devinfo, get_time(), brw_context::gs, gl_program::info, intel_batchbuffer::last_bo, gl_program::nir, brw_context::perf_debug, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_program::program, brw_context::screen, gl_program::sh, and ST_GS.
Referenced by brw_gs_precompile(), and brw_upload_gs_prog().
brw_gs_debug_recompile()
static void brw_gs_debug_recompile (struct brw_context * brw, struct gl_program * prog, const struct brw_gs_prog_key * key) static
References BRW_CACHE_GS_PROG, brw_debug_recompile_sampler_key(), brw_find_previous_compile(), brw_context::cache, and gl_program::Id.
Referenced by brw_codegen_gs_prog().
brw_gs_populate_key()
void brw_gs_populate_key (struct brw_context * brw, struct brw_gs_prog_key * key)
References brw_populate_sampler_prog_key_data(), brw_context::ctx, brw_context::geometry_program, brw_program::id, and brw_program::program.
Referenced by brw_upload_gs_prog().
brw_gs_precompile()
bool brw_gs_precompile (struct gl_context * ctx, struct gl_program * prog)
References brw_context::base, brw_codegen_gs_prog(), brw_context(), brw_program(), brw_setup_tex_for_precompile(), brw_context::gs, brw_program::id, brw_stage_state::prog_data, and brw_stage_state::prog_offset.
Referenced by brw_shader_precompile().
brw_gs_state_dirty()
static bool brw_gs_state_dirty (const struct brw_context * brw) static
References _NEW_TEXTURE, BRW_NEW_GEOMETRY_PROGRAM, BRW_NEW_TRANSFORM_FEEDBACK, and brw_state_dirty().
Referenced by brw_upload_gs_prog().
brw_upload_gs_prog()
void brw_upload_gs_prog (struct brw_context * brw)
References brw_context::base, BRW_CACHE_GS_PROG, brw_codegen_gs_prog(), brw_gs_populate_key(), brw_gs_state_dirty(), BRW_NEW_TRANSFORM_FEEDBACK, brw_search_cache(), brw_context::cache, brw_context::ctx, brw_context::gen, gen6_brw_upload_ff_gs_prog(), brw_context::geometry_program, brw_context::gs, if(), gl_context::NewDriverState, brw_stage_state::prog_data, brw_stage_state::prog_offset, and void.
Referenced by brw_upload_programs().