Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_wm.h File Reference
#include <stdbool.h>
#include "brw_context.h"
Functions
bool brw_color_buffer_write_enabled (struct brw_context *brw)
void brw_upload_wm_prog (struct brw_context *brw)
void brw_wm_populate_key (struct brw_context *brw, struct brw_wm_prog_key *key)
Function Documentation
brw_color_buffer_write_enabled()
bool brw_color_buffer_write_enabled (struct brw_context * brw)
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, BITFIELD64_BIT, gl_context::Color, gl_colorbuffer_attrib::ColorMask, brw_context::ctx, gl_context::DrawBuffer, brw_context::fragment_program, and gl_program::info.
Referenced by brw_upload_wm_unit(), gen8_upload_ps_blend(), gen8_upload_ps_extra(), and upload_wm_state().
brw_upload_wm_prog()
void brw_upload_wm_prog (struct brw_context * brw)
References brw_context::base, BRW_CACHE_FS_PROG, brw_codegen_wm_prog(), brw_search_cache(), brw_wm_populate_key(), brw_wm_state_dirty(), brw_context::cache, brw_context::fragment_program, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, void, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by brw_upload_programs().
brw_wm_populate_key()
void brw_wm_populate_key (struct brw_context * brw, struct brw_wm_prog_key * key)
References gl_stencil_attrib::_BackFace, gl_colorbuffer_attrib::_ClampFragmentColor, gl_stencil_attrib::_Enabled, _mesa_bitcount_64(), _mesa_is_alpha_test_enabled(), _mesa_is_alpha_to_coverage_enabled(), gl_framebuffer::_NumColorDrawBuffers, gl_colorbuffer_attrib::_UsesDualSrc, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, gl_colorbuffer_attrib::AlphaRef, gl_polygon_attrib::BackMode, BITFIELD64_BIT, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, brw_depth_writes_enabled(), brw_populate_sampler_prog_key_data(), brw_program_const(), gl_context::Color, brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_context::Depth, gl_context::DrawBuffer, brw_context::dual_color_blend_by_location, gl_multisample_attrib::Enabled, gl_context::Extensions, brw_context::fragment_program, gl_hint_attrib::FragmentShaderDerivative, gl_polygon_attrib::FrontMode, brw_context::gen, GLuint, gl_context::Hint, brw_program::id, gl_program::info, gl_context::Light, gl_context::Line, gl_extensions::MESA_shader_framebuffer_fetch, gl_multisample_attrib::MinSampleShadingValue, gl_context::Multisample, gl_context::Polygon, brw_context::reduced_primitive, gl_multisample_attrib::SampleShading, gl_light_attrib::ShadeModel, gl_line_attrib::SmoothFlag, brw_context::stats_wm, gl_context::Stencil, gl_depthbuffer_attrib::Test, brw_context::vue_map_geom_out, and gl_stencil_attrib::WriteMask.
Referenced by brw_upload_wm_prog().