Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_cc.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "main/macros.h"
#include "main/stencil.h"
#include "intel_batchbuffer.h"
Functions
static void brw_upload_cc_vp (struct brw_context *brw)
GLenum brw_fix_xRGB_alpha (GLenum function)
Modify blend function to force destination alpha to 1.0.
static void upload_cc_unit (struct brw_context *brw)
Creates a CC unit packet from the current blend state.
static void upload_blend_constant_color (struct brw_context *brw)
Variables
const struct brw_tracked_state brw_cc_vp
const struct brw_tracked_state brw_cc_unit
const struct brw_tracked_state brw_blend_constant_color
Function Documentation
brw_fix_xRGB_alpha()
GLenum brw_fix_xRGB_alpha (GLenum function)
Modify blend function to force destination alpha to 1.0.
If function specifies a blend function that uses destination alpha, replace it with a function that hard-wires destination alpha to 1.0. This is used when rendering to xRGB targets.
Referenced by gen6_upload_blend_state(), gen8_upload_blend_state(), gen8_upload_ps_blend(), and upload_cc_unit().
brw_upload_cc_vp()
static void brw_upload_cc_vp (struct brw_context * brw) static
References _3DSTATE_VIEWPORT_STATE_POINTERS_CC, ADVANCE_BATCH, BEGIN_BATCH, BRW_NEW_CC_VP, brw_state_batch(), brw_context::cc, brw_context::clip, brw_context::ctx, gl_transform_attrib::DepthClamp, gl_viewport_attrib::Far, brw_context::gen, brw_cc_viewport::max_depth, brw_cc_viewport::min_depth, gl_viewport_attrib::Near, gl_context::NewDriverState, OUT_BATCH, gl_context::Transform, brw_context::viewport_count, gl_context::ViewportArray, and brw_context::vp_offset.
upload_blend_constant_color()
static void upload_blend_constant_color (struct brw_context * brw) static
References _3DSTATE_BLEND_CONSTANT_COLOR, ADVANCE_BATCH, BEGIN_BATCH, gl_colorbuffer_attrib::BlendColorUnclamped, gl_context::Color, brw_context::ctx, OUT_BATCH, and OUT_BATCH_F.
upload_cc_unit()
static void upload_cc_unit (struct brw_context * brw) static
Creates a CC unit packet from the current blend state.
References gl_colorbuffer_attrib::_AdvancedBlendMode, gl_stencil_attrib::_BackFace, gl_stencil_attrib::_Enabled, gl_framebuffer::_NumColorDrawBuffers, gl_stencil_attrib::_TestTwoSide, brw_cc_unit_state::alpha_ref, brw_cc_unit_state::alpha_test, brw_cc_unit_state::alpha_test_format, brw_cc_unit_state::alpha_test_func, gl_config::alphaBits, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, gl_colorbuffer_attrib::AlphaRef, brw_context::batch, brw_cc_unit_state::bf_stencil_enable, brw_cc_unit_state::bf_stencil_fail_op, brw_cc_unit_state::bf_stencil_func, brw_cc_unit_state::bf_stencil_pass_depth_fail_op, brw_cc_unit_state::bf_stencil_pass_depth_pass_op, brw_cc_unit_state::bf_stencil_ref, brw_cc_unit_state::bf_stencil_test_mask, brw_cc_unit_state::bf_stencil_write_mask, gl_colorbuffer_attrib::Blend, brw_cc_unit_state::blend_enable, brw_cc_unit_state::blend_function, gl_colorbuffer_attrib::BlendEnabled, intel_batchbuffer::bo, BRW_ALPHATEST_FORMAT_UNORM8, brw_depth_writes_enabled(), brw_fix_xRGB_alpha(), BRW_NEW_GEN4_UNIT_STATE, brw_state_batch(), brw_translate_blend_equation(), brw_translate_blend_factor(), brw_context::cc, brw_cc_unit_state::cc0, brw_cc_unit_state::cc1, brw_cc_unit_state::cc2, brw_cc_unit_state::cc3, brw_cc_unit_state::cc4, brw_cc_unit_state::cc5, brw_cc_unit_state::cc6, brw_cc_unit_state::cc7, brw_cc_unit_state::cc_viewport_state_offset, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, brw_context::ctx, gl_context::Depth, brw_cc_unit_state::depth_test, brw_cc_unit_state::depth_test_function, brw_cc_unit_state::depth_write_enable, brw_cc_unit_state::dest_blend_factor, brw_cc_unit_state::dither_enable, gl_colorbuffer_attrib::DitherFlag, gl_context::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_stencil_attrib::FailFunc, gl_depthbuffer_attrib::Func, gl_stencil_attrib::Function, brw_cc_unit_state::ia_blend_enable, brw_cc_unit_state::ia_blend_function, brw_cc_unit_state::ia_dest_blend_factor, brw_cc_unit_state::ia_src_blend_factor, intel_translate_compare_func(), intel_translate_logic_op(), intel_translate_stencil_op(), gl_colorbuffer_attrib::LogicOp, brw_cc_unit_state::logicop_enable, brw_cc_unit_state::logicop_func, gl_context::NewDriverState, brw_cc_unit_state::src_blend_factor, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, brw_context::state_offset, brw_cc_unit_state::statistics_enable, brw_context::stats_wm, gl_context::Stencil, brw_cc_unit_state::stencil_enable, brw_cc_unit_state::stencil_fail_op, brw_cc_unit_state::stencil_func, brw_cc_unit_state::stencil_pass_depth_fail_op, brw_cc_unit_state::stencil_pass_depth_pass_op, brw_cc_unit_state::stencil_ref, brw_cc_unit_state::stencil_test_mask, brw_cc_unit_state::stencil_write_enable, brw_cc_unit_state::stencil_write_mask, gl_depthbuffer_attrib::Test, UNCLAMPED_FLOAT_TO_UBYTE, gl_stencil_attrib::ValueMask, gl_framebuffer::Visual, brw_context::vp_offset, gl_stencil_attrib::WriteMask, brw_cc_unit_state::x_dither_offset, brw_cc_unit_state::y_dither_offset, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Variable Documentation
brw_blend_constant_color
const struct brw_tracked_state brw_blend_constant_color
Initial value:
= {
   .dirty = {
      .mesa = _NEW_COLOR,
      .brw = BRW_NEW_CONTEXT |
             BRW_NEW_BLORP,
   },
   .emit = upload_blend_constant_color
}
brw_cc_unit
const struct brw_tracked_state brw_cc_unit
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR |
              _NEW_DEPTH |
              _NEW_STENCIL,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CC_VP |
             BRW_NEW_STATS_WM,
   },
   .emit = upload_cc_unit,
}
brw_cc_vp
const struct brw_tracked_state brw_cc_vp
Initial value:
= {
   .dirty = {
      .mesa = _NEW_TRANSFORM |
              _NEW_VIEWPORT,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VIEWPORT_COUNT,
   },
   .emit = brw_upload_cc_vp
}