Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_program_cache.c File Reference
This file implements a simple program cache for 965.
#include "main/imports.h"
#include "intel_batchbuffer.h"
#include "brw_state.h"
#include "brw_wm.h"
#include "brw_gs.h"
#include "brw_cs.h"
#include "brw_program.h"
#include "compiler/brw_eu.h"
Data Structures
struct brw_cache_item
Macros
#define FILE_DEBUG_FLAG DEBUG_STATE
Functions
static unsigned get_program_string_id (enum brw_cache_id cache_id, const void *key)
static GLuint hash_key (struct brw_cache_item *item)
static int brw_cache_item_equals (const struct brw_cache_item *a, const struct brw_cache_item *b)
static struct brw_cache_item * search_cache (struct brw_cache *cache, GLuint hash, struct brw_cache_item *lookup)
static void rehash (struct brw_cache *cache)
bool brw_search_cache (struct brw_cache *cache, enum brw_cache_id cache_id, const void *key, GLuint key_size, uint32_t *inout_offset, void *inout_aux)
Returns the buffer object matching cache_id and key, or NULL.
static void brw_cache_new_bo (struct brw_cache *cache, uint32_t new_size)
static const struct brw_cache_item * brw_lookup_prog (const struct brw_cache *cache, enum brw_cache_id cache_id, const void *data, unsigned data_size)
Attempts to find an item in the cache with identical data.
static uint32_t brw_alloc_item_data (struct brw_cache *cache, uint32_t size)
const void * brw_find_previous_compile (struct brw_cache *cache, enum brw_cache_id cache_id, unsigned program_string_id)
void brw_upload_cache (struct brw_cache *cache, enum brw_cache_id cache_id, const void *key, GLuint key_size, const void *data, GLuint data_size, const void *aux, GLuint aux_size, uint32_t *out_offset, void *out_aux)
void brw_init_caches (struct brw_context *brw)
static void brw_clear_cache (struct brw_context *brw, struct brw_cache *cache)
void brw_program_cache_check_size (struct brw_context *brw)
static void brw_destroy_cache (struct brw_context *brw, struct brw_cache *cache)
void brw_destroy_caches (struct brw_context *brw)
static const char * cache_name (enum brw_cache_id cache_id)
void brw_print_program_cache (struct brw_context *brw)
Detailed Description
This file implements a simple program cache for 965.
The consumers can query the hash table of programs using a cache_id and program key, and receive the corresponding program buffer object (plus associated auxiliary data) in return. Objects in the cache may not have relocations (pointers to other BOs) in them.
The inner workings are a simple hash table based on a CRC of the key data.
Replacement is not implemented. Instead, when the cache gets too big we throw out all of the cache data and let it get regenerated.
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_STATE
Function Documentation
brw_alloc_item_data()
static uint32_t brw_alloc_item_data (struct brw_cache * cache, uint32_t size) static
References brw_cache::bo, brw_cache::bo_used_by_gpu, brw_cache::brw, brw_cache_new_bo(), brw_context::has_llc, brw_cache::next_offset, brw_cache_item::offset, and brw_context::perf_debug.
Referenced by brw_upload_cache().
brw_cache_item_equals()
static int brw_cache_item_equals (const struct brw_cache_item * a, const struct brw_cache_item * b) static
References brw_cache_item::cache_id, brw_cache_item::hash, brw_cache_item::key, and brw_cache_item::key_size.
Referenced by search_cache().
brw_cache_new_bo()
static void brw_cache_new_bo (struct brw_cache * cache, uint32_t new_size) static
References brw_context::batch, brw_cache::bo, brw_cache::bo_used_by_gpu, brw_cache::brw, BRW_NEW_PROGRAM_CACHE, brw_context::bufmgr, brw_context::ctx, brw_context::has_llc, gl_context::NewDriverState, brw_cache::next_offset, and intel_batchbuffer::state_base_address_emitted.
Referenced by brw_alloc_item_data().
brw_clear_cache()
static void brw_clear_cache (struct brw_context * brw, struct brw_cache * cache) static
References brw_context::base, brw_state_flags::brw, BRW_CACHE_CS_PROG, BRW_CACHE_FS_PROG, BRW_CACHE_GS_PROG, BRW_CACHE_TCS_PROG, BRW_CACHE_TES_PROG, BRW_CACHE_VS_PROG, BRW_COMPUTE_PIPELINE, BRW_RENDER_PIPELINE, brw_stage_prog_data_free(), brw_cache_item::cache_id, brw_context::cs, brw_context::ctx, DBG, GLuint, brw_context::gs, intel_batchbuffer_flush, brw_cache::items, brw_cache_item::key, brw_cache_item::key_size, brw_state_flags::mesa, brw_cache::n_items, gl_context::NewDriverState, brw_context::NewGLState, brw_cache_item::next, brw_cache::next_offset, brw_context::pipelines, brw_stage_state::prog_data, brw_cache::size, brw_context::state, brw_context::tcs, brw_context::tes, brw_context::vs, and brw_context::wm.
Referenced by brw_destroy_cache(), and brw_program_cache_check_size().
brw_destroy_cache()
static void brw_destroy_cache (struct brw_context * brw, struct brw_cache * cache) static
References brw_cache::bo, brw_clear_cache(), DBG, brw_context::has_llc, brw_cache::items, and brw_cache::size.
Referenced by brw_destroy_caches().
brw_destroy_caches()
void brw_destroy_caches (struct brw_context * brw)
References brw_destroy_cache(), and brw_context::cache.
Referenced by brw_destroy_state(), and brw_select_pipeline().
brw_find_previous_compile()
const void* brw_find_previous_compile (struct brw_cache * cache, enum brw_cache_id cache_id, unsigned program_string_id)
References get_program_string_id(), brw_cache::items, brw_cache_item::next, and brw_cache::size.
Referenced by brw_gs_debug_recompile(), brw_select_pipeline(), brw_tcs_debug_recompile(), brw_tes_debug_recompile(), brw_vs_debug_recompile(), and brw_wm_debug_recompile().
brw_init_caches()
void brw_init_caches (struct brw_context * brw)
References brw_cache::bo, brw_cache::brw, brw_context::bufmgr, brw_context::cache, brw_context::has_llc, brw_cache::items, brw_cache::n_items, and brw_cache::size.
Referenced by brw_init_state(), and brw_select_pipeline().
brw_lookup_prog()
static const struct brw_cache_item* brw_lookup_prog (const struct brw_cache * cache, enum brw_cache_id cache_id, const void * data, unsigned data_size) static
Attempts to find an item in the cache with identical data.
References brw_cache::bo, brw_cache::brw, brw_cache_item::cache_id, brw_context::has_llc, brw_cache::items, brw_cache_item::next, brw_cache_item::offset, ret(), brw_cache_item::size, and brw_cache::size.
Referenced by brw_upload_cache().
brw_print_program_cache()
void brw_print_program_cache (struct brw_context * brw)
References brw_cache::bo, brw_context::cache, cache_name(), intel_screen::devinfo, brw_context::has_llc, brw_cache::items, brw_cache_item::next, brw_cache_item::offset, brw_context::screen, brw_cache_item::size, and brw_cache::size.
Referenced by brw_select_pipeline().
brw_program_cache_check_size()
void brw_program_cache_check_size (struct brw_context * brw)
References brw_clear_cache(), brw_context::cache, and brw_cache::n_items.
Referenced by brw_dispatch_compute_common(), brw_select_pipeline(), and brw_try_draw_prims().
brw_search_cache()
bool brw_search_cache (struct brw_cache * cache, enum brw_cache_id cache_id, const void * key, GLuint key_size, uint32_t * inout_offset, void * inout_aux)
Returns the buffer object matching cache_id and key, or NULL.
References brw_cache::brw, brw_cache_item::cache_id, brw_context::ctx, GLuint, brw_cache_item::hash, hash_key(), brw_cache_item::key, brw_cache_item::key_size, gl_context::NewDriverState, brw_cache_item::offset, and search_cache().
Referenced by brw_blorp_lookup_shader(), brw_select_pipeline(), brw_upload_clip_prog(), brw_upload_cs_prog(), brw_upload_ff_gs_prog(), brw_upload_gs_prog(), brw_upload_sf_prog(), brw_upload_tcs_prog(), brw_upload_tes_prog(), brw_upload_vs_prog(), and brw_upload_wm_prog().
brw_upload_cache()
void brw_upload_cache (struct brw_cache * cache, enum brw_cache_id cache_id, const void * key, GLuint key_size, const void * data, GLuint data_size, const void * aux, GLuint aux_size, uint32_t * out_offset, void * out_aux)
References brw_cache_item::aux_size, brw_cache::bo, brw_cache::brw, brw_alloc_item_data(), brw_lookup_prog(), brw_cache_item::cache_id, CALLOC_STRUCT, brw_context::ctx, GLuint, brw_context::has_llc, brw_cache_item::hash, hash_key(), brw_cache::items, brw_cache_item::key, brw_cache_item::key_size, brw_cache::n_items, gl_context::NewDriverState, brw_cache_item::next, brw_cache_item::offset, rehash(), brw_cache_item::size, and brw_cache::size.
Referenced by brw_blorp_upload_shader(), brw_codegen_cs_prog(), brw_codegen_ff_gs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), brw_select_pipeline(), compile_clip_prog(), and compile_sf_prog().
cache_name()
static const char* cache_name (enum brw_cache_id cache_id) static
References BRW_CACHE_CLIP_PROG, BRW_CACHE_CS_PROG, BRW_CACHE_FF_GS_PROG, BRW_CACHE_FS_PROG, BRW_CACHE_GS_PROG, BRW_CACHE_SF_PROG, BRW_CACHE_TCS_PROG, BRW_CACHE_TES_PROG, and BRW_CACHE_VS_PROG.
Referenced by brw_print_program_cache().
get_program_string_id()
static unsigned get_program_string_id (enum brw_cache_id cache_id, const void * key) static
References BRW_CACHE_CS_PROG, BRW_CACHE_FS_PROG, BRW_CACHE_GS_PROG, BRW_CACHE_TCS_PROG, BRW_CACHE_TES_PROG, BRW_CACHE_VS_PROG, and GLuint.
Referenced by brw_find_previous_compile().
hash_key()
static GLuint hash_key (struct brw_cache_item * item) static
References brw_cache_item::cache_id, GLuint, brw_cache_item::hash, brw_cache_item::key, and brw_cache_item::key_size.
Referenced by brw_search_cache(), and brw_upload_cache().
rehash()
static void rehash (struct brw_cache * cache) static
References GLuint, brw_cache_item::hash, brw_cache::items, brw_cache_item::next, brw_cache_item::size, and brw_cache::size.
Referenced by brw_upload_cache().
search_cache()
static struct brw_cache_item* search_cache (struct brw_cache * cache, GLuint hash, struct brw_cache_item * lookup) static
References brw_cache_item_equals(), brw_cache::items, brw_cache::n_items, brw_cache_item::next, and brw_cache::size.
Referenced by brw_search_cache().