Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_urb.c File Reference
Manages the division of the URB space between the various fixed-function units.
#include "intel_batchbuffer.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
Macros
#define VS 0
#define GS 1
#define CLP 2
#define SF 3
#define CS 4
Functions
static bool check_urb_layout (struct brw_context *brw)
static void recalculate_urb_fence (struct brw_context *brw)
void brw_upload_urb_fence (struct brw_context *brw)
Variables
struct {
GLuint min_nr_entries
GLuint preferred_nr_entries
GLuint min_entry_size
GLuint max_entry_size
} limits [CS+1]
const struct brw_tracked_state brw_recalculate_urb_fence
Detailed Description
Manages the division of the URB space between the various fixed-function units.
See the Thread Initiation Management section of the GEN4 B-Spec, and the individual *_STATE structures for restrictions on numbers of entries and threads.
Macro Definition Documentation
CLP
#define CLP 2
Referenced by recalculate_urb_fence().
CS
#define CS 4
Referenced by recalculate_urb_fence().
GS
#define GS 1
Referenced by recalculate_urb_fence().
SF
#define SF 3
Referenced by recalculate_urb_fence().
VS
#define VS 0
Referenced by recalculate_urb_fence().
Function Documentation
brw_upload_urb_fence()
void brw_upload_urb_fence (struct brw_context * brw)
References brw_context::batch, brw_urb_fence::bits0, brw_urb_fence::bits1, BRW_BATCH_STRUCT, brw_context::clip_start, brw_urb_fence::clp_fence, brw_urb_fence::clp_realloc, CMD_URB_FENCE, brw_urb_fence::cs_fence, brw_urb_fence::cs_realloc, brw_context::cs_start, brw_urb_fence::gs_fence, brw_urb_fence::gs_realloc, brw_context::gs_start, brw_urb_fence::header, brw_urb_fence::length, intel_batchbuffer::map_next, MI_NOOP, brw_urb_fence::opcode, brw_urb_fence::pad, brw_urb_fence::sf_fence, brw_urb_fence::sf_realloc, brw_context::sf_start, brw_context::size, brw_context::urb, USED_BATCH, brw_urb_fence::vfe_realloc, brw_urb_fence::vs_fence, and brw_urb_fence::vs_realloc.
Referenced by key_debug(), and upload_psp_urb_cbs().
check_urb_layout()
static bool check_urb_layout (struct brw_context * brw) static
References brw_context::clip_start, brw_context::cs_start, brw_context::csize, brw_context::gs_start, brw_context::nr_clip_entries, brw_context::nr_cs_entries, brw_context::nr_gs_entries, brw_context::nr_sf_entries, brw_context::nr_vs_entries, brw_context::sf_start, brw_context::sfsize, brw_context::size, brw_context::urb, brw_context::vs_start, and brw_context::vsize.
Referenced by recalculate_urb_fence().
recalculate_urb_fence()
static void recalculate_urb_fence (struct brw_context * brw) static
References brw_context::base, BRW_NEW_URB_FENCE, check_urb_layout(), brw_context::clip_start, CLP, brw_context::constrained, CS, brw_context::cs_start, brw_context::csize, brw_context::ctx, brw_context::curbe, brw_context::gen, GLuint, GS, brw_context::gs_start, brw_context::is_g4x, limits, min_entry_size, gl_context::NewDriverState, brw_context::nr_clip_entries, brw_context::nr_cs_entries, brw_context::nr_gs_entries, brw_context::nr_sf_entries, brw_context::nr_vs_entries, brw_stage_state::prog_data, brw_context::prog_data, SF, brw_context::sf, brw_context::sf_start, brw_context::sfsize, brw_context::size, brw_context::total_size, brw_context::urb, VS, brw_context::vs, brw_context::vs_start, and brw_context::vsize.
Variable Documentation
brw_recalculate_urb_fence
const struct brw_tracked_state brw_recalculate_urb_fence
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CURBE_OFFSETS |
             BRW_NEW_SF_PROG_DATA |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = recalculate_urb_fence
}
limits
const { ... } limits[CS+1]
Initial value:
= {
   { 16, 32, 1, 5 },
   { 4, 8,  1, 5 },
   { 5, 10,  1, 5 },
   { 1, 8,  1, 12 },
   { 1, 4,  1, 32 }
}
Referenced by recalculate_urb_fence().
max_entry_size
GLuint max_entry_size
min_entry_size
GLuint min_entry_size
Referenced by recalculate_urb_fence().
min_nr_entries
GLuint min_nr_entries
preferred_nr_entries
GLuint preferred_nr_entries