Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_vs.h File Reference
#include "brw_context.h"
Functions
GLbitfield64 brw_vs_outputs_written (struct brw_context *brw, struct brw_vs_prog_key *key, GLbitfield64 outputs_written)
void brw_upload_vs_prog (struct brw_context *brw)
void brw_vs_populate_key (struct brw_context *brw, struct brw_vs_prog_key *key)
Function Documentation
brw_upload_vs_prog()
void brw_upload_vs_prog (struct brw_context * brw)
References brw_context::base, BRW_CACHE_VS_PROG, brw_codegen_vs_prog(), brw_search_cache(), brw_vs_populate_key(), brw_vs_state_dirty(), brw_context::cache, if(), brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_context::vertex_program, void, and brw_context::vs.
Referenced by brw_upload_programs().
brw_vs_outputs_written()
GLbitfield64 brw_vs_outputs_written (struct brw_context * brw, struct brw_vs_prog_key * key, GLbitfield64 outputs_written)
References BITFIELD64_BIT, and brw_context::gen.
Referenced by brw_codegen_vs_prog().
brw_vs_populate_key()
void brw_vs_populate_key (struct brw_context * brw, struct brw_vs_prog_key * key)
References gl_light_attrib::_ClampVertexColor, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, brw_context::attrib_wa_flags, gl_polygon_attrib::BackMode, brw_populate_sampler_prog_key_data(), gl_transform_attrib::ClipPlanesEnabled, gl_point_attrib::CoordReplace, brw_context::ctx, gl_polygon_attrib::FrontMode, brw_context::gen, brw_program::id, gl_program::info, brw_context::is_haswell, gl_context::Light, gl_context::Point, gl_point_attrib::PointSprite, gl_context::Polygon, brw_program::program, gl_context::Transform, brw_context::vb, and brw_context::vertex_program.
Referenced by brw_upload_vs_prog().