Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_channel_expressions_visitor Class Reference
Public Member Functions
ir_channel_expressions_visitor ()
ir_visitor_status visit_leave (ir_assignment *)
ir_rvalue * get_element (ir_variable *var, unsigned int element)
void assign (ir_assignment *ir, int elem, ir_rvalue *val)
Data Fields
bool progress
void * mem_ctx
Constructor & Destructor Documentation
ir_channel_expressions_visitor()
ir_channel_expressions_visitor::ir_channel_expressions_visitor () inline
References assign(), get_element(), mem_ctx, progress, and visit_leave().
Member Function Documentation
assign()
void ir_channel_expressions_visitor::assign (ir_assignment * ir, int elem, ir_rvalue * val)
References mem_ctx.
Referenced by ir_channel_expressions_visitor(), and visit_leave().
get_element()
ir_rvalue * ir_channel_expressions_visitor::get_element (ir_variable * var, unsigned int element)
References mem_ctx.
Referenced by ir_channel_expressions_visitor(), and visit_leave().
visit_leave()
ir_visitor_status ir_channel_expressions_visitor::visit_leave (ir_assignment * ir)
References assign(), expr(), get_element(), ir_unop_cos, ir_unop_dFdx_coarse, ir_unop_dFdy, ir_unop_dFdy_fine, ir_unop_log, ir_unop_log2, mem_ctx, progress, and visit_continue.
Referenced by ir_channel_expressions_visitor().
Field Documentation
mem_ctx
void* ir_channel_expressions_visitor::mem_ctx
Referenced by assign(), get_element(), ir_channel_expressions_visitor(), and visit_leave().
progress
bool ir_channel_expressions_visitor::progress
Referenced by brw_do_channel_expressions(), ir_channel_expressions_visitor(), and visit_leave().
The documentation for this class was generated from the following file:
brw_fs_channel_expressions.cpp