Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_queryobj.c File Reference
Support for query objects (GL_ARB_occlusion_query, GL_ARB_timer_query, GL_EXT_transform_feedback, and friends) on platforms that support hardware contexts (Gen6+).
#include "main/imports.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
Functions
static void set_query_availability (struct brw_context *brw, struct brw_query_object *query, bool available)
static void write_primitives_generated (struct brw_context *brw, drm_intel_bo *query_bo, int stream, int idx)
static void write_xfb_primitives_written (struct brw_context *brw, drm_intel_bo *bo, int stream, int idx)
static void write_xfb_overflow_streams (struct gl_context *ctx, drm_intel_bo *bo, int stream, int count, int idx)
static bool check_xfb_overflow_streams (uint64_t *results, int count)
static int pipeline_target_to_index (int target)
static void emit_pipeline_stat (struct brw_context *brw, drm_intel_bo *bo, int stream, int target, int idx)
static void gen6_queryobj_get_results (struct gl_context *ctx, struct brw_query_object *query)
Wait on the query object's BO and calculate the final result.
static void gen6_begin_query (struct gl_context *ctx, struct gl_query_object *q)
Driver hook for glBeginQuery().
static void gen6_end_query (struct gl_context *ctx, struct gl_query_object *q)
Driver hook for glEndQuery().
static void flush_batch_if_needed (struct brw_context *brw, struct brw_query_object *query)
Flush the batch if it still references the query object BO.
static void gen6_wait_query (struct gl_context *ctx, struct gl_query_object *q)
The WaitQuery() driver hook.
static void gen6_check_query (struct gl_context *ctx, struct gl_query_object *q)
The CheckQuery() driver hook.
static void gen6_query_counter (struct gl_context *ctx, struct gl_query_object *q)
void gen6_init_queryobj_functions (struct dd_function_table *functions)
gen6_queryobj.c
Detailed Description
Support for query objects (GL_ARB_occlusion_query, GL_ARB_timer_query, GL_EXT_transform_feedback, and friends) on platforms that support hardware contexts (Gen6+).
Function Documentation
check_xfb_overflow_streams()
static bool check_xfb_overflow_streams (uint64_t * results, int count) static
Referenced by gen6_queryobj_get_results().
emit_pipeline_stat()
static void emit_pipeline_stat (struct brw_context * brw, drm_intel_bo * bo, int stream, int target, int idx) static
References brw_emit_mi_flush(), brw_store_register_mem64(), CL_INVOCATION_COUNT, CL_PRIMITIVES_COUNT, CS_INVOCATION_COUNT, DS_INVOCATION_COUNT, brw_context::gen, GS_INVOCATION_COUNT, GS_PRIMITIVES_COUNT, HS_INVOCATION_COUNT, IA_PRIMITIVES_COUNT, IA_VERTICES_COUNT, MAX_PIPELINE_STATISTICS, pipeline_target_to_index(), PS_INVOCATION_COUNT, and VS_INVOCATION_COUNT.
Referenced by gen6_begin_query(), and gen6_end_query().
flush_batch_if_needed()
static void flush_batch_if_needed (struct brw_context * brw, struct brw_query_object * query) static
Flush the batch if it still references the query object BO.
References brw_context::batch, brw_query_object::bo, intel_batchbuffer::bo, brw_query_object::flushed, and intel_batchbuffer_flush.
Referenced by gen6_check_query(), and gen6_wait_query().
gen6_begin_query()
static void gen6_begin_query (struct gl_context * ctx, struct gl_query_object * q) static
Driver hook for glBeginQuery().
Initializes driver structures and emits any GPU commands required to begin recording data for the query.
References brw_query_object::Base, brw_query_object::bo, brw_context(), BRW_NEW_RASTERIZER_DISCARD, brw_write_depth_count(), brw_write_timestamp(), brw_context::bufmgr, emit_pipeline_stat(), MAX_VERTEX_STREAMS, gl_context::NewDriverState, set_query_availability(), gl_query_object::Stream, gl_query_object::Target, write_primitives_generated(), write_xfb_overflow_streams(), and write_xfb_primitives_written().
Referenced by gen6_init_queryobj_functions().
gen6_check_query()
static void gen6_check_query (struct gl_context * ctx, struct gl_query_object * q) static
The CheckQuery() driver hook.
Checks whether a query result is ready yet. If not, flushes. This is the backing for glGetQueryObjectiv()'s QUERY_RESULT_AVAILABLE pname.
References brw_query_object::bo, brw_context(), flush_batch_if_needed(), and gen6_queryobj_get_results().
Referenced by gen6_init_queryobj_functions().
gen6_end_query()
static void gen6_end_query (struct gl_context * ctx, struct gl_query_object * q) static
Driver hook for glEndQuery().
Emits GPU commands to record a final query value, ending any data capturing. However, the final result isn't necessarily available until the GPU processes those commands. brw_queryobj_get_results() processes the captured data to produce the final result.
References brw_query_object::Base, brw_query_object::bo, brw_context(), BRW_NEW_RASTERIZER_DISCARD, brw_write_depth_count(), brw_write_timestamp(), emit_pipeline_stat(), brw_query_object::flushed, MAX_VERTEX_STREAMS, gl_context::NewDriverState, set_query_availability(), gl_query_object::Stream, gl_query_object::Target, write_primitives_generated(), write_xfb_overflow_streams(), and write_xfb_primitives_written().
Referenced by gen6_init_queryobj_functions().
gen6_init_queryobj_functions()
void gen6_init_queryobj_functions (struct dd_function_table * functions)
gen6_queryobj.c
References dd_function_table::BeginQuery, dd_function_table::CheckQuery, dd_function_table::EndQuery, gen6_begin_query(), gen6_check_query(), gen6_end_query(), gen6_query_counter(), gen6_wait_query(), dd_function_table::QueryCounter, and dd_function_table::WaitQuery.
Referenced by brw_init_driver_functions(), and hsw_init_queryobj_functions().
gen6_query_counter()
static void gen6_query_counter (struct gl_context * ctx, struct gl_query_object * q) static
References brw_context(), brw_query_counter(), and set_query_availability().
Referenced by gen6_init_queryobj_functions().
gen6_queryobj_get_results()
static void gen6_queryobj_get_results (struct gl_context * ctx, struct brw_query_object * query) static
Wait on the query object's BO and calculate the final result.
References brw_query_object::Base, brw_query_object::bo, brw_bo_map(), brw_context(), brw_raw_timestamp_delta(), brw_timebase_scale(), check_xfb_overflow_streams(), gl_context::Const, brw_context::gen, brw_context::is_haswell, MAX_VERTEX_STREAMS, gl_constants::QueryCounterBits, gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and gl_constants::Timestamp.
Referenced by gen6_check_query(), and gen6_wait_query().
gen6_wait_query()
static void gen6_wait_query (struct gl_context * ctx, struct gl_query_object * q) static
The WaitQuery() driver hook.
Wait for a query result to become available and return it. This is the backing for glGetQueryObjectiv() with the GL_QUERY_RESULT pname.
References brw_context(), flush_batch_if_needed(), and gen6_queryobj_get_results().
Referenced by gen6_init_queryobj_functions().
pipeline_target_to_index()
static int pipeline_target_to_index (int target) inline static
References MAX_PIPELINE_STATISTICS.
Referenced by emit_pipeline_stat().
set_query_availability()
static void set_query_availability (struct brw_context * brw, struct brw_query_object * query, bool available) inline static
References gl_extensions::ARB_query_buffer_object, brw_query_object::bo, brw_emit_pipe_control_write(), brw_is_query_pipelined(), brw_context::ctx, gl_context::Extensions, and PIPE_CONTROL_WRITE_IMMEDIATE.
Referenced by gen6_begin_query(), gen6_end_query(), and gen6_query_counter().
write_primitives_generated()
static void write_primitives_generated (struct brw_context * brw, drm_intel_bo * query_bo, int stream, int idx) static
References brw_emit_mi_flush(), brw_store_register_mem64(), CL_INVOCATION_COUNT, brw_context::gen, and GEN7_SO_PRIM_STORAGE_NEEDED.
Referenced by gen6_begin_query(), and gen6_end_query().
write_xfb_overflow_streams()
static void write_xfb_overflow_streams (struct gl_context * ctx, drm_intel_bo * bo, int stream, int count, int idx) static
References brw_context(), brw_emit_mi_flush(), brw_store_register_mem64(), brw_context::gen, GEN6_SO_NUM_PRIMS_WRITTEN, GEN6_SO_PRIM_STORAGE_NEEDED, GEN7_SO_NUM_PRIMS_WRITTEN, and GEN7_SO_PRIM_STORAGE_NEEDED.
Referenced by gen6_begin_query(), and gen6_end_query().
write_xfb_primitives_written()
static void write_xfb_primitives_written (struct brw_context * brw, drm_intel_bo * bo, int stream, int idx) static
References brw_emit_mi_flush(), brw_store_register_mem64(), brw_context::gen, GEN6_SO_NUM_PRIMS_WRITTEN, and GEN7_SO_NUM_PRIMS_WRITTEN.
Referenced by gen6_begin_query(), and gen6_end_query().