Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_constant_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "program/prog_parameter.h"
Functions
void gen7_upload_constant_state (struct brw_context *brw, const struct brw_stage_state *stage_state, bool active, unsigned opcode)
void gen6_upload_push_constants (struct brw_context *brw, const struct gl_program *prog, const struct brw_stage_prog_data *prog_data, struct brw_stage_state *stage_state)
Creates a streamed BO containing the push constants for the VS or GS on gen6+.
Function Documentation
gen6_upload_push_constants()
void gen6_upload_push_constants (struct brw_context * brw, const struct gl_program * prog, const struct brw_stage_prog_data * prog_data, struct brw_stage_state * stage_state)
Creates a streamed BO containing the push constants for the VS or GS on gen6+.
Push constants are constant values (such as GLSL uniforms) that are pre-loaded into a shader stage's register space at thread spawn time.
Not all GLSL uniforms will be uploaded as push constants: The hardware has a limitation of 32 or 64 EU registers (256 or 512 floats) per stage to be uploaded as push constants, while GL 4.4 requires at least 1024 components to be usable for the VS. Plus, currently we always use pull constants instead of push constants when doing variable-index array access.
See brw_curbe.c for the equivalent gen4/5 code.
References brw_state_batch(), brw_context::ctx, gl_program::Parameters, brw_stage_state::push_const_offset, brw_stage_state::push_const_size, and brw_stage_state::stage.
Referenced by brw_depth_writes_enabled(), gen6_upload_gs_push_constants(), gen6_upload_vs_push_constants(), gen6_upload_wm_push_constants(), gen7_upload_tcs_push_constants(), and gen7_upload_tes_push_constants().
gen7_upload_constant_state()
void gen7_upload_constant_state (struct brw_context * brw, const struct brw_stage_state * stage_state, bool active, unsigned opcode)
References ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH, intel_batchbuffer::bo, BRW_NEW_SURFACES, brw_context::ctx, brw_context::gen, GEN7_MOCS_L3, gl_context::NewDriverState, OUT_BATCH, OUT_RELOC64, brw_stage_state::push_const_offset, and brw_stage_state::push_const_size.
Referenced by gen6_upload_gs_push_constants(), gen6_upload_vs_push_constants(), gen6_upload_wm_push_constants(), gen7_upload_tcs_push_constants(), and gen7_upload_tes_push_constants().