Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_gs_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "main/shaderapi.h"
Functions
static void gen6_upload_gs_push_constants (struct brw_context *brw)
static void upload_gs_state_for_tf (struct brw_context *brw)
static void upload_gs_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_gs_push_constants
const struct brw_tracked_state gen6_gs_state
Function Documentation
gen6_upload_gs_push_constants()
static void gen6_upload_gs_push_constants (struct brw_context * brw) static
References _3DSTATE_CONSTANT_GS, _mesa_shader_write_subroutine_indices(), brw_context::base, brw_program_const(), brw_context::ctx, brw_context::gen, gen6_upload_push_constants(), gen7_upload_constant_state(), brw_context::geometry_program, brw_context::gs, brw_stage_state::prog_data, and brw_program::program.
upload_gs_state()
static void upload_gs_state (struct brw_context * brw) static
References _3DSTATE_CONSTANT_GS, _3DSTATE_GS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, intel_screen::devinfo, brw_context::enabled, brw_context::ff_gs, GEN6_CONSTANT_BUFFER_0_ENABLE, GEN6_GS_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN6_GS_DISPATCH_START_GRF_SHIFT, GEN6_GS_ENABLE, GEN6_GS_MAX_THREADS_SHIFT, GEN6_GS_RENDERING_ENABLE, GEN6_GS_REORDER, GEN6_GS_SAMPLER_COUNT_SHIFT, GEN6_GS_SO_STATISTICS_ENABLE, GEN6_GS_SPF_MODE, GEN6_GS_STATISTICS_ENABLE, GEN6_GS_SVBI_PAYLOAD_ENABLE, GEN6_GS_URB_ENTRY_READ_OFFSET_SHIFT, GEN6_GS_URB_READ_LENGTH_SHIFT, GEN6_GS_VECTOR_MASK_ENABLE, brw_context::geometry_program, brw_context::gs, gl_program::info, OUT_BATCH, OUT_RELOC, brw_stage_state::per_thread_scratch, brw_context::prog_active, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_stage_state::push_const_offset, brw_stage_state::push_const_size, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, brw_context::screen, and upload_gs_state_for_tf().
upload_gs_state_for_tf()
static void upload_gs_state_for_tf (struct brw_context * brw) static
References _3DSTATE_GS, ADVANCE_BATCH, BEGIN_BATCH, intel_screen::devinfo, brw_context::ff_gs, GEN6_GS_DISPATCH_START_GRF_SHIFT, GEN6_GS_ENABLE, GEN6_GS_MAX_THREADS_SHIFT, GEN6_GS_RENDERING_ENABLE, GEN6_GS_SO_STATISTICS_ENABLE, GEN6_GS_SPF_MODE, GEN6_GS_STATISTICS_ENABLE, GEN6_GS_SVBI_PAYLOAD_ENABLE, GEN6_GS_SVBI_POSTINCREMENT_ENABLE, GEN6_GS_SVBI_POSTINCREMENT_VALUE_SHIFT, GEN6_GS_URB_READ_LENGTH_SHIFT, GEN6_GS_VECTOR_MASK_ENABLE, OUT_BATCH, brw_context::prog_data, brw_context::prog_offset, brw_context::screen, brw_ff_gs_prog_data::svbi_postincrement_value, and brw_ff_gs_prog_data::urb_read_length.
Referenced by upload_gs_state().
Variable Documentation
gen6_gs_push_constants
const struct brw_tracked_state gen6_gs_push_constants
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_PROGRAM_CONSTANTS |
               _NEW_TRANSFORM,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_GEOMETRY_PROGRAM |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION,
   },
   .emit = gen6_upload_gs_push_constants,
}
gen6_gs_state
const struct brw_tracked_state gen6_gs_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_PROGRAM_CONSTANTS |
               _NEW_TRANSFORM,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FF_GS_PROG_DATA |
               BRW_NEW_GEOMETRY_PROGRAM |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION,
   },
   .emit = upload_gs_state,
}