Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_cc.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "intel_batchbuffer.h"
#include "main/macros.h"
#include "main/enums.h"
#include "main/glformats.h"
#include "main/stencil.h"
Functions
static void gen6_upload_blend_state (struct brw_context *brw)
static void gen6_upload_color_calc_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_blend_state
const struct brw_tracked_state gen6_color_calc_state
Function Documentation
gen6_upload_blend_state()
static void gen6_upload_blend_state (struct brw_context * brw) static
References _3DSTATE_BLEND_STATE_POINTERS, _3DSTATE_CC_STATE_POINTERS, gl_colorbuffer_attrib::_AdvancedBlendMode, gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorDrawBuffers, _mesa_base_format_has_channel(), _mesa_enum_to_string(), _mesa_get_format_datatype(), _mesa_is_multisample_enabled(), gl_framebuffer::_NumColorDrawBuffers, gl_colorbuffer_attrib::_UsesDualSrc, ADVANCE_BATCH, gen6_blend_state::alpha_test_enable, gen6_blend_state::alpha_test_func, gen6_blend_state::alpha_to_coverage, gen6_blend_state::alpha_to_coverage_dither, gen6_blend_state::alpha_to_one, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, BEGIN_BATCH, gl_colorbuffer_attrib::Blend, gen6_blend_state::blend0, gen6_blend_state::blend1, gen6_blend_state::blend_enable, gen6_blend_state::blend_func, brw_context::blend_state_offset, gl_colorbuffer_attrib::BlendEnabled, brw_fix_xRGB_alpha(), BRW_RENDERTARGET_CLAMPRANGE_FORMAT, brw_state_batch(), brw_translate_blend_equation(), brw_translate_blend_factor(), brw_context::cc, gen6_blend_state::clamp_range, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, brw_context::ctx, gen6_blend_state::dest_blend_factor, gen6_blend_state::dither_enable, gl_colorbuffer_attrib::DitherFlag, gl_context::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_renderbuffer::Format, brw_context::gen, gen6_blend_state::ia_blend_enable, gen6_blend_state::ia_blend_func, gen6_blend_state::ia_dest_blend_factor, gen6_blend_state::ia_source_blend_factor, intel_translate_compare_func(), intel_translate_logic_op(), gen6_blend_state::logic_op_enable, gen6_blend_state::logic_op_func, gl_colorbuffer_attrib::LogicOp, gl_context::Multisample, OUT_BATCH, gen6_blend_state::post_blend_clamp_enable, gen6_blend_state::pre_blend_clamp_enable, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, gen6_blend_state::source_blend_factor, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, gen6_blend_state::write_disable_a, gen6_blend_state::write_disable_b, gen6_blend_state::write_disable_g, gen6_blend_state::write_disable_r, gen6_blend_state::x_dither_offset, and gen6_blend_state::y_dither_offset.
gen6_upload_color_calc_state()
static void gen6_upload_color_calc_state (struct brw_context * brw) static
References _3DSTATE_CC_STATE_POINTERS, gl_stencil_attrib::_BackFace, ADVANCE_BATCH, gen6_color_calc_state::alpha_ref_fi, gen6_color_calc_state::alpha_test_format, gl_colorbuffer_attrib::AlphaRef, BEGIN_BATCH, gen6_color_calc_state::bf_stencil_ref, gl_colorbuffer_attrib::BlendColorUnclamped, BRW_ALPHATEST_FORMAT_UNORM8, brw_state_batch(), brw_context::cc, gen6_color_calc_state::cc0, gen6_color_calc_state::cc1, gl_context::Color, gen6_color_calc_state::constant_a, gen6_color_calc_state::constant_b, gen6_color_calc_state::constant_g, gen6_color_calc_state::constant_r, brw_context::ctx, brw_context::gen, OUT_BATCH, brw_context::state_offset, gl_context::Stencil, gen6_color_calc_state::stencil_ref, and UNCLAMPED_FLOAT_TO_UBYTE.
Variable Documentation
gen6_blend_state
const struct brw_tracked_state gen6_blend_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR |
              _NEW_MULTISAMPLE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = gen6_upload_blend_state,
}
gen6_color_calc_state
const struct brw_tracked_state gen6_color_calc_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_COLOR |
              _NEW_STENCIL,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CC_STATE |
             BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = gen6_upload_color_calc_state,
}