Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_viewport_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "main/viewport.h"
Functions
void brw_calculate_guardband_size (const struct gen_device_info *devinfo, uint32_t fb_width, uint32_t fb_height, float m00, float m11, float m30, float m31, float *xmin, float *xmax, float *ymin, float *ymax)
static void gen6_upload_sf_and_clip_viewports (struct brw_context *brw)
static void upload_viewport_state_pointers (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_sf_and_clip_viewports
const struct brw_tracked_state gen6_viewport_state
Function Documentation
brw_calculate_guardband_size()
void brw_calculate_guardband_size (const struct gen_device_info * devinfo, uint32_t fb_width, uint32_t fb_height, float m00, float m11, float m30, float m31, float * xmin, float * xmax, float * ymin, float * ymax)
Referenced by gen6_upload_sf_and_clip_viewports(), gen7_upload_sf_clip_viewport(), gen8_upload_sf_clip_viewport(), and use_state_point_size().
gen6_upload_sf_and_clip_viewports()
static void gen6_upload_sf_and_clip_viewports (struct brw_context * brw) static
References _mesa_get_viewport_xform(), brw_calculate_guardband_size(), BRW_NEW_CLIP_VP, BRW_NEW_SF_VP, brw_state_batch(), brw_context::clip, brw_context::ctx, intel_screen::devinfo, gl_context::DrawBuffer, gen6_sf_viewport::m00, gen6_sf_viewport::m11, gen6_sf_viewport::m22, gen6_sf_viewport::m30, gen6_sf_viewport::m31, gen6_sf_viewport::m32, gl_context::NewDriverState, brw_context::screen, brw_context::sf, brw_context::viewport_count, and brw_context::vp_offset.
upload_viewport_state_pointers()
static void upload_viewport_state_pointers (struct brw_context * brw) static
References _3DSTATE_VIEWPORT_STATE_POINTERS, ADVANCE_BATCH, BEGIN_BATCH, brw_context::cc, brw_context::clip, GEN6_CC_VIEWPORT_MODIFY, GEN6_CLIP_VIEWPORT_MODIFY, GEN6_SF_VIEWPORT_MODIFY, OUT_BATCH, brw_context::sf, and brw_context::vp_offset.
Variable Documentation
gen6_sf_and_clip_viewports
const struct brw_tracked_state gen6_sf_and_clip_viewports
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_VIEWPORT,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VIEWPORT_COUNT,
   },
   .emit = gen6_upload_sf_and_clip_viewports,
}
gen6_viewport_state
const struct brw_tracked_state gen6_viewport_state
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CC_VP |
             BRW_NEW_CLIP_VP |
             BRW_NEW_SF_VP |
             BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = upload_viewport_state_pointers,
}