Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_depthstencil.c File Reference
#include "intel_batchbuffer.h"
#include "intel_fbo.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
Functions
static void gen6_upload_depth_stencil_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_depth_stencil_state
Function Documentation
gen6_upload_depth_stencil_state()
static void gen6_upload_depth_stencil_state (struct brw_context * brw) static
References _3DSTATE_CC_STATE_POINTERS, _3DSTATE_DEPTH_STENCIL_STATE_POINTERS, gl_stencil_attrib::_BackFace, gl_stencil_attrib::_Enabled, gl_stencil_attrib::_TestTwoSide, gl_stencil_attrib::_WriteEnabled, ADVANCE_BATCH, BEGIN_BATCH, gen6_depth_stencil_state::bf_stencil_enable, gen6_depth_stencil_state::bf_stencil_fail_op, gen6_depth_stencil_state::bf_stencil_func, gen6_depth_stencil_state::bf_stencil_pass_depth_fail_op, gen6_depth_stencil_state::bf_stencil_pass_depth_pass_op, gen6_depth_stencil_state::bf_stencil_test_mask, gen6_depth_stencil_state::bf_stencil_write_mask, brw_depth_writes_enabled(), brw_state_batch(), BUFFER_DEPTH, brw_context::cc, brw_context::ctx, gl_context::Depth, brw_context::depth_stencil_state_offset, gen6_depth_stencil_state::depth_test_enable, gen6_depth_stencil_state::depth_test_func, gen6_depth_stencil_state::depth_write_enable, gl_context::DrawBuffer, gen6_depth_stencil_state::ds0, gen6_depth_stencil_state::ds1, gen6_depth_stencil_state::ds2, gl_stencil_attrib::FailFunc, gl_depthbuffer_attrib::Func, gl_stencil_attrib::Function, brw_context::gen, intel_get_renderbuffer(), intel_translate_compare_func(), intel_translate_stencil_op(), OUT_BATCH, gl_context::Stencil, gen6_depth_stencil_state::stencil_enable, gen6_depth_stencil_state::stencil_fail_op, gen6_depth_stencil_state::stencil_func, gen6_depth_stencil_state::stencil_pass_depth_fail_op, gen6_depth_stencil_state::stencil_pass_depth_pass_op, gen6_depth_stencil_state::stencil_test_mask, gen6_depth_stencil_state::stencil_write_enable, gen6_depth_stencil_state::stencil_write_mask, gl_depthbuffer_attrib::Test, gl_stencil_attrib::ValueMask, gl_stencil_attrib::WriteMask, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Variable Documentation
gen6_depth_stencil_state
const struct brw_tracked_state gen6_depth_stencil_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_DEPTH |
              _NEW_STENCIL,
      .brw  = BRW_NEW_BATCH |
              BRW_NEW_BLORP |
              BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = gen6_upload_depth_stencil_state,
}