Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_clip_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
#include "brw_util.h"
#include "intel_batchbuffer.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
Functions
bool brw_is_drawing_points (const struct brw_context *brw)
bool brw_is_drawing_lines (const struct brw_context *brw)
static void upload_clip_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_clip_state
Function Documentation
brw_is_drawing_lines()
bool brw_is_drawing_lines (const struct brw_context * brw)
References gl_polygon_attrib::BackMode, brw_context::base, brw_context::ctx, gl_polygon_attrib::FrontMode, brw_context::gs, gl_context::Polygon, brw_context::primitive, brw_stage_state::prog_data, and brw_context::tes.
Referenced by upload_clip_state().
brw_is_drawing_points()
bool brw_is_drawing_points (const struct brw_context * brw)
References gl_polygon_attrib::BackMode, brw_context::base, brw_context::ctx, gl_polygon_attrib::FrontMode, brw_context::gs, gl_context::Polygon, brw_context::primitive, brw_stage_state::prog_data, and brw_context::tes.
Referenced by calculate_attr_overrides(), and upload_clip_state().
upload_clip_state()
static void upload_clip_state (struct brw_context * brw) static
References _3DSTATE_CLIP, gl_polygon_attrib::_FrontBit, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_is_drawing_lines(), brw_is_drawing_points(), brw_context::clip, gl_transform_attrib::ClipDepthMode, gl_transform_attrib::ClipPlanesEnabled, brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_transform_attrib::DepthClamp, gl_context::DrawBuffer, brw_context::gen, GEN6_CLIP_API_D3D, GEN6_CLIP_API_OGL, GEN6_CLIP_ENABLE, GEN6_CLIP_FORCE_ZERO_RTAINDEX, GEN6_CLIP_GB_TEST, GEN6_CLIP_LINE_PROVOKE_SHIFT, GEN6_CLIP_MAX_POINT_WIDTH_SHIFT, GEN6_CLIP_MAX_VP_INDEX_MASK, GEN6_CLIP_MIN_POINT_WIDTH_SHIFT, GEN6_CLIP_MODE_NORMAL, GEN6_CLIP_MODE_REJECT_ALL, GEN6_CLIP_NON_PERSPECTIVE_BARYCENTRIC_ENABLE, GEN6_CLIP_STATISTICS_ENABLE, GEN6_CLIP_TRI_PROVOKE_SHIFT, GEN6_CLIP_TRIFAN_PROVOKE_SHIFT, GEN6_CLIP_XY_TEST, GEN6_CLIP_Z_TEST, GEN6_USER_CLIP_CLIP_DISTANCES_SHIFT, GEN7_CLIP_CULLMODE_BACK, GEN7_CLIP_CULLMODE_BOTH, GEN7_CLIP_CULLMODE_FRONT, GEN7_CLIP_CULLMODE_NONE, GEN7_CLIP_EARLY_CULL, GEN7_CLIP_WINDING_CCW, GEN8_CLIP_FORCE_USER_CLIP_DISTANCE_BITMASK, gl_context::Light, brw_context::meta_in_progress, OUT_BATCH, gl_context::Polygon, brw_context::primitive, brw_stage_state::prog_data, gl_light_attrib::ProvokingVertex, gl_context::RasterDiscard, gl_context::Transform, brw_context::viewport_count, brw_context::vs, and brw_context::wm.
Variable Documentation
gen6_clip_state
const struct brw_tracked_state gen6_clip_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LIGHT |
               _NEW_POLYGON |
               _NEW_TRANSFORM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_VS_PROG_DATA |
               BRW_NEW_META_IN_PROGRESS |
               BRW_NEW_PRIMITIVE |
               BRW_NEW_RASTERIZER_DISCARD |
               BRW_NEW_TES_PROG_DATA |
               BRW_NEW_VIEWPORT_COUNT,
   },
   .emit = upload_clip_state,
}