Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_wm_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
#include "brw_util.h"
#include "brw_wm.h"
#include "program/program.h"
#include "program/prog_parameter.h"
#include "program/prog_statevars.h"
#include "main/shaderapi.h"
#include "main/framebuffer.h"
#include "intel_batchbuffer.h"
Functions
static void gen6_upload_wm_push_constants (struct brw_context *brw)
void gen6_upload_wm_state (struct brw_context *brw, const struct brw_wm_prog_data *prog_data, const struct brw_stage_state *stage_state, bool multisampled_fbo, bool dual_source_blend_enable, bool kill_enable, bool color_buffer_write_enable, bool msaa_enabled, bool line_stipple_enable, bool polygon_stipple_enable, bool statistic_enable)
static void upload_wm_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_wm_push_constants
const struct brw_tracked_state gen6_wm_state
Function Documentation
gen6_upload_wm_push_constants()
static void gen6_upload_wm_push_constants (struct brw_context * brw) static
References _3DSTATE_CONSTANT_PS, _mesa_shader_write_subroutine_indices(), brw_context::base, brw_program_const(), brw_context::ctx, brw_context::fragment_program, brw_context::gen, gen6_upload_push_constants(), gen7_upload_constant_state(), brw_stage_state::prog_data, brw_program::program, and brw_context::wm.
gen6_upload_wm_state()
void gen6_upload_wm_state (struct brw_context * brw, const struct brw_wm_prog_data * prog_data, const struct brw_stage_state * stage_state, bool multisampled_fbo, bool dual_source_blend_enable, bool kill_enable, bool color_buffer_write_enable, bool msaa_enabled, bool line_stipple_enable, bool polygon_stipple_enable, bool statistic_enable)
References _3DSTATE_CONSTANT_PS, _3DSTATE_WM, ADVANCE_BATCH, BEGIN_BATCH, intel_screen::devinfo, GEN6_CONSTANT_BUFFER_0_ENABLE, GEN6_WM_16_DISPATCH_ENABLE, GEN6_WM_8_DISPATCH_ENABLE, GEN6_WM_BARYCENTRIC_INTERPOLATION_MODE_SHIFT, GEN6_WM_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN6_WM_COMPUTED_DEPTH, GEN6_WM_DISPATCH_ENABLE, GEN6_WM_DISPATCH_START_GRF_SHIFT_0, GEN6_WM_DISPATCH_START_GRF_SHIFT_2, GEN6_WM_DUAL_SOURCE_BLEND_ENABLE, GEN6_WM_FLOATING_POINT_MODE_ALT, GEN6_WM_KILL_ENABLE, GEN6_WM_LINE_AA_WIDTH_1_0, GEN6_WM_LINE_END_CAP_AA_WIDTH_0_5, GEN6_WM_LINE_STIPPLE_ENABLE, GEN6_WM_MAX_THREADS_SHIFT, GEN6_WM_MSDISPMODE_PERPIXEL, GEN6_WM_MSDISPMODE_PERSAMPLE, GEN6_WM_MSRAST_OFF_PIXEL, GEN6_WM_MSRAST_ON_PATTERN, GEN6_WM_NUM_SF_OUTPUTS_SHIFT, GEN6_WM_OMASK_TO_RENDER_TARGET, GEN6_WM_POLYGON_STIPPLE_ENABLE, GEN6_WM_POSOFFSET_NONE, GEN6_WM_POSOFFSET_SAMPLE, GEN6_WM_SAMPLER_COUNT_SHIFT, GEN6_WM_STATISTICS_ENABLE, GEN6_WM_USES_SOURCE_DEPTH, GEN6_WM_USES_SOURCE_W, OUT_BATCH, OUT_RELOC, brw_stage_state::per_thread_scratch, brw_stage_state::prog_offset, brw_stage_state::push_const_offset, brw_stage_state::push_const_size, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, and brw_context::screen.
Referenced by upload_wm_state().
upload_wm_state()
static void upload_wm_state (struct brw_context * brw) static
References _mesa_is_alpha_test_enabled(), _mesa_is_alpha_to_coverage_enabled(), gl_colorbuffer_attrib::_UsesDualSrc, brw_context::base, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, brw_color_buffer_write_enabled(), gl_context::Color, brw_context::ctx, gl_context::DrawBuffer, gl_multisample_attrib::Enabled, gen6_upload_wm_state(), gl_context::Line, gl_context::Multisample, gl_context::Polygon, brw_stage_state::prog_data, gl_polygon_attrib::StippleFlag, gl_line_attrib::StippleFlag, and brw_context::wm.
Variable Documentation
gen6_wm_push_constants
const struct brw_tracked_state gen6_wm_push_constants
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_PROGRAM_CONSTANTS,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_FRAGMENT_PROGRAM |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION,
   },
   .emit = gen6_upload_wm_push_constants,
}
gen6_wm_state
const struct brw_tracked_state gen6_wm_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_COLOR |
               _NEW_LINE |
               _NEW_MULTISAMPLE |
               _NEW_POLYGON |
               _NEW_PROGRAM_CONSTANTS,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION,
   },
   .emit = upload_wm_state,
}