Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_sf_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "compiler/nir/nir.h"
#include "main/macros.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "intel_batchbuffer.h"
Functions
static uint32_t get_attr_override (const struct brw_vue_map *vue_map, int urb_entry_read_offset, int fs_attr, bool two_side_color, uint32_t *max_source_attr)
Determine the appropriate attribute override value to store into the 3DSTATE_SF structure for a given fragment shader attribute.
void calculate_attr_overrides (const struct brw_context *brw, uint16_t *attr_overrides, uint32_t *point_sprite_enables, uint32_t *urb_entry_read_length, uint32_t *urb_entry_read_offset)
Create the mapping from the FS inputs we produce to the previous pipeline stage (GS or VS) outputs they source from.
static void upload_sf_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_sf_state
Function Documentation
calculate_attr_overrides()
void calculate_attr_overrides (const struct brw_context * brw, uint16_t * attr_overrides, uint32_t * point_sprite_enables, uint32_t * urb_entry_read_length, uint32_t * urb_entry_read_offset)
Create the mapping from the FS inputs we produce to the previous pipeline stage (GS or VS) outputs they source from.
References gl_vertex_program_state::_TwoSideEnabled, brw_context::base, brw_is_drawing_points(), gl_point_attrib::CoordReplace, brw_context::ctx, brw_context::fragment_program, get_attr_override(), gl_program::info, gl_context::Point, gl_point_attrib::PointSprite, brw_stage_state::prog_data, gl_context::VertexProgram, brw_context::vue_map_geom_out, and brw_context::wm.
Referenced by upload_sbe(), upload_sbe_state(), and upload_sf_state().
get_attr_override()
static uint32_t get_attr_override (const struct brw_vue_map * vue_map, int urb_entry_read_offset, int fs_attr, bool two_side_color, uint32_t * max_source_attr) static
Determine the appropriate attribute override value to store into the 3DSTATE_SF structure for a given fragment shader attribute.
The attribute override value contains two pieces of information: the location of the attribute in the VUE (relative to urb_entry_read_offset, see below), and a flag indicating whether to "swizzle" the attribute based on the direction the triangle is facing.
If an attribute is "swizzled", then the given VUE location is used for front-facing triangles, and the VUE location that immediately follows is used for back-facing triangles. We use this to implement the mapping from gl_FrontColor/gl_BackColor to gl_Color.
urb_entry_read_offset is the offset into the VUE at which the SF unit is being instructed to begin reading attribute data. It can be set to a nonzero value to prevent the SF unit from wasting time reading elements of the VUE that are not needed by the fragment shader. It is measured in 256-bit increments.
References ATTRIBUTE_0_CONST_SOURCE_SHIFT, ATTRIBUTE_0_OVERRIDE_W, ATTRIBUTE_0_OVERRIDE_X, ATTRIBUTE_0_OVERRIDE_Y, ATTRIBUTE_0_OVERRIDE_Z, ATTRIBUTE_CONST_0000, ATTRIBUTE_CONST_PRIM_ID, ATTRIBUTE_SWIZZLE_INPUTATTR_FACING, and ATTRIBUTE_SWIZZLE_SHIFT.
Referenced by calculate_attr_overrides().
upload_sf_state()
static void upload_sf_state (struct brw_context * brw) static
References _3DSTATE_SF, gl_polygon_attrib::_FrontBit, ADVANCE_BATCH, gl_polygon_attrib::BackMode, brw_context::base, BEGIN_BATCH, brw_get_line_width(), calculate_attr_overrides(), brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_context::DrawBuffer, gl_multisample_attrib::Enabled, gl_polygon_attrib::FrontMode, GEN6_SF_BACK_POINT, GEN6_SF_BACK_SOLID, GEN6_SF_BACK_WIREFRAME, GEN6_SF_CULL_BACK, GEN6_SF_CULL_BOTH, GEN6_SF_CULL_FRONT, GEN6_SF_CULL_NONE, GEN6_SF_FRONT_POINT, GEN6_SF_FRONT_SOLID, GEN6_SF_FRONT_WIREFRAME, GEN6_SF_GLOBAL_DEPTH_OFFSET_POINT, GEN6_SF_GLOBAL_DEPTH_OFFSET_SOLID, GEN6_SF_GLOBAL_DEPTH_OFFSET_WIREFRAME, GEN6_SF_LINE_AA_ENABLE, GEN6_SF_LINE_AA_MODE_TRUE, GEN6_SF_LINE_END_CAP_WIDTH_1_0, GEN6_SF_LINE_PROVOKE_SHIFT, GEN6_SF_LINE_WIDTH_SHIFT, GEN6_SF_MSRAST_ON_PATTERN, GEN6_SF_NUM_OUTPUTS_SHIFT, GEN6_SF_POINT_SPRITE_LOWERLEFT, GEN6_SF_POINT_SPRITE_UPPERLEFT, GEN6_SF_SCISSOR_ENABLE, GEN6_SF_STATISTICS_ENABLE, GEN6_SF_SWIZZLE_ENABLE, GEN6_SF_TRI_PROVOKE_SHIFT, GEN6_SF_TRIFAN_PROVOKE_SHIFT, GEN6_SF_URB_ENTRY_READ_LENGTH_SHIFT, GEN6_SF_URB_ENTRY_READ_OFFSET_SHIFT, GEN6_SF_USE_STATE_POINT_WIDTH, GEN6_SF_VIEWPORT_TRANSFORM_ENABLE, GEN6_SF_WINDING_CCW, gl_context::Light, gl_context::Line, gl_point_attrib::MaxSize, gl_point_attrib::MinSize, gl_context::Multisample, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, OUT_BATCH, OUT_BATCH_F, gl_context::Point, gl_context::Polygon, brw_stage_state::prog_data, gl_light_attrib::ProvokingVertex, brw_context::sf, gl_point_attrib::Size, gl_line_attrib::SmoothFlag, gl_point_attrib::SpriteOrigin, use_state_point_size(), brw_context::viewport_transform_enable, and brw_context::wm.
Variable Documentation
gen6_sf_state
const struct brw_tracked_state gen6_sf_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LIGHT |
               _NEW_LINE |
               _NEW_MULTISAMPLE |
               _NEW_POINT |
               _NEW_POLYGON |
               _NEW_PROGRAM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FRAGMENT_PROGRAM |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_PRIMITIVE |
               BRW_NEW_TES_PROG_DATA |
               BRW_NEW_VUE_MAP_GEOM_OUT,
   },
   .emit = upload_sf_state,
}