Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_urb.c File Reference
#include "main/macros.h"
#include "intel_batchbuffer.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
Functions
void gen6_upload_urb (struct brw_context *brw, unsigned vs_size, bool gs_present, unsigned gs_size)
When the GS is not in use, we assign the entire URB space to the VS.
static void upload_urb (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_urb
Function Documentation
gen6_upload_urb()
void gen6_upload_urb (struct brw_context * brw, unsigned vs_size, bool gs_present, unsigned gs_size)
When the GS is not in use, we assign the entire URB space to the VS.
When the GS is in use, we split the URB space evenly between the VS and the GS. This is not ideal, but it's simple.
      URB size / 2                   URB size / 2
_____________-______________ _____________-______________ / \ / \ +----------------------------------------------------------—+ | Vertex Shader Entries | Geometry Shader Entries | +----------------------------------------------------------—+
Sandybridge GT1 has 32kB of URB space, while GT2 has 64kB. (See the Sandybridge PRM, Volume 2, Part 1, Section 1.4.7: 3DSTATE_URB.)
References _3DSTATE_URB, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_mi_flush(), intel_screen::devinfo, GEN6_URB_GS_ENTRIES_SHIFT, GEN6_URB_GS_SIZE_SHIFT, GEN6_URB_VS_ENTRIES_SHIFT, GEN6_URB_VS_SIZE_SHIFT, brw_context::gs_present, brw_context::nr_gs_entries, brw_context::nr_vs_entries, OUT_BATCH, brw_context::screen, brw_context::size, and brw_context::urb.
Referenced by blorp_emit_urb_config(), brw_get_index_type(), and upload_urb().
upload_urb()
static void upload_urb (struct brw_context * brw) static
References brw_context::base, brw_context::ff_gs, gen6_upload_urb(), brw_context::geometry_program, brw_context::gs, brw_context::prog_active, brw_stage_state::prog_data, and brw_context::vs.
Variable Documentation
gen6_urb
const struct brw_tracked_state gen6_urb
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CONTEXT |
             BRW_NEW_FF_GS_PROG_DATA |
             BRW_NEW_GEOMETRY_PROGRAM |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = upload_urb,
}