Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_multisample_state.c File Reference
#include "intel_batchbuffer.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_multisample_state.h"
#include "main/framebuffer.h"
Functions
void gen6_get_sample_position (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint index, GLfloat *result)
void gen6_set_sample_maps (struct gl_context *ctx)
Sample index layout shows the numbering of slots in a rectangular grid of samples with in a pixel.
void gen6_emit_3dstate_multisample (struct brw_context *brw, unsigned num_samples)
3DSTATE_MULTISAMPLE
unsigned gen6_determine_sample_mask (struct brw_context *brw)
void gen6_emit_3dstate_sample_mask (struct brw_context *brw, unsigned mask)
3DSTATE_SAMPLE_MASK
static void upload_multisample_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_multisample_state
Function Documentation
gen6_determine_sample_mask()
unsigned gen6_determine_sample_mask (struct brw_context * brw)
References _mesa_is_multisample_enabled(), brw_context::ctx, gl_context::Multisample, brw_context::num_samples, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleCoverageValue, gl_multisample_attrib::SampleMask, and gl_multisample_attrib::SampleMaskValue.
Referenced by brw_get_index_type(), upload_multisample_state(), and upload_ps_state().
gen6_emit_3dstate_multisample()
void gen6_emit_3dstate_multisample (struct brw_context * brw, unsigned num_samples)
3DSTATE_MULTISAMPLE
References _3DSTATE_MULTISAMPLE, ADVANCE_BATCH, BEGIN_BATCH, brw_multisample_positions_4x, brw_multisample_positions_8x, brw_context::gen, MS_NUMSAMPLES_1, MS_NUMSAMPLES_4, MS_NUMSAMPLES_8, MS_PIXEL_LOCATION_CENTER, and OUT_BATCH.
Referenced by brw_get_index_type(), and upload_multisample_state().
gen6_emit_3dstate_sample_mask()
void gen6_emit_3dstate_sample_mask (struct brw_context * brw, unsigned mask)
3DSTATE_SAMPLE_MASK
References _3DSTATE_SAMPLE_MASK, ADVANCE_BATCH, BEGIN_BATCH, and OUT_BATCH.
Referenced by brw_get_index_type(), and upload_multisample_state().
gen6_get_sample_position()
void gen6_get_sample_position (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint index, GLfloat * result)
References brw_multisample_positions_16x, brw_multisample_positions_1x_2x, brw_multisample_positions_4x, and brw_multisample_positions_8x.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen6_set_sample_maps()
void gen6_set_sample_maps (struct gl_context * ctx)
Sample index layout shows the numbering of slots in a rectangular grid of samples with in a pixel.
Sample number layout shows the rectangular grid of samples roughly corresponding to the real sample locations with in a pixel. Sample number layout matches the sample index layout in case of 2X and 4x MSAA, but they are different in case of 8X MSAA.
2X MSAA sample index / number layout
| 0 | 1 |
4X MSAA sample index / number layout
| 0 | 1 |
| 2 | 3 |
8X MSAA sample index layout 8x MSAA sample number layout
| 0 | 1 | | 5 | 2 |
| 2 | 3 | | 4 | 6 |
| 4 | 5 | | 0 | 3 |
| 6 | 7 | | 7 | 1 |
16X MSAA sample index layout 16x MSAA sample number layout
| 0 | 1 | 2 | 3 | |15 |10 | 9 | 7 |
| 4 | 5 | 6 | 7 | | 4 | 1 | 3 |13 |
| 8 | 9 |10 |11 | |12 | 2 | 0 | 6 |
|12 |13 |14 |15 | |11 | 8 | 5 |14 |
A sample map is used to map sample indices to sample numbers.
References gl_context::Const, gl_constants::SampleMap16x, gl_constants::SampleMap2x, gl_constants::SampleMap4x, and gl_constants::SampleMap8x.
Referenced by brw_get_index_type(), and brw_initialize_context_constants().
upload_multisample_state()
static void upload_multisample_state (struct brw_context * brw) static
References gen6_determine_sample_mask(), gen6_emit_3dstate_multisample(), gen6_emit_3dstate_sample_mask(), and brw_context::num_samples.
Variable Documentation
gen6_multisample_state
const struct brw_tracked_state gen6_multisample_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_MULTISAMPLE,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CONTEXT |
             BRW_NEW_NUM_SAMPLES,
   },
   .emit = upload_multisample_state
}