Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_vs_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "program/prog_parameter.h"
#include "program/prog_statevars.h"
#include "main/shaderapi.h"
#include "intel_batchbuffer.h"
Functions
static void gen6_upload_vs_push_constants (struct brw_context *brw)
static void upload_vs_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen6_vs_push_constants
const struct brw_tracked_state gen6_vs_state
Function Documentation
gen6_upload_vs_push_constants()
static void gen6_upload_vs_push_constants (struct brw_context * brw) static
References _3DSTATE_CONSTANT_VS, _mesa_shader_write_subroutine_indices(), brw_context::base, brw_program_const(), brw_context::ctx, brw_context::gen, gen6_upload_push_constants(), gen7_emit_vs_workaround_flush(), gen7_upload_constant_state(), brw_context::is_baytrail, brw_context::is_haswell, brw_stage_state::prog_data, brw_program::program, brw_context::vertex_program, and brw_context::vs.
upload_vs_state()
static void upload_vs_state (struct brw_context * brw) static
References _3DSTATE_CONSTANT_VS, _3DSTATE_VS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_emit_pipe_control_flush(), intel_screen::devinfo, GEN6_CONSTANT_BUFFER_0_ENABLE, GEN6_VS_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN6_VS_DISPATCH_START_GRF_SHIFT, GEN6_VS_ENABLE, GEN6_VS_FLOATING_POINT_MODE_ALT, GEN6_VS_MAX_THREADS_SHIFT, GEN6_VS_SAMPLER_COUNT_SHIFT, GEN6_VS_STATISTICS_ENABLE, GEN6_VS_URB_ENTRY_READ_OFFSET_SHIFT, GEN6_VS_URB_READ_LENGTH_SHIFT, OUT_BATCH, OUT_RELOC, brw_stage_state::per_thread_scratch, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_INSTRUCTION_INVALIDATE, PIPE_CONTROL_STATE_CACHE_INVALIDATE, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_stage_state::push_const_offset, brw_stage_state::push_const_size, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, brw_context::screen, and brw_context::vs.
Variable Documentation
gen6_vs_push_constants
const struct brw_tracked_state gen6_vs_push_constants
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_PROGRAM_CONSTANTS |
               _NEW_TRANSFORM,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION |
               BRW_NEW_VERTEX_PROGRAM |
               BRW_NEW_VS_PROG_DATA,
   },
   .emit = gen6_upload_vs_push_constants,
}
gen6_vs_state
const struct brw_tracked_state gen6_vs_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_PROGRAM_CONSTANTS |
               _NEW_TRANSFORM,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION |
               BRW_NEW_VERTEX_PROGRAM |
               BRW_NEW_VS_PROG_DATA,
   },
   .emit = upload_vs_state,
}