Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_sol.c File Reference
Code to initialize the binding table entries used by transform feedback.
#include "main/bufferobj.h"
#include "main/macros.h"
#include "brw_context.h"
#include "intel_batchbuffer.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "main/transformfeedback.h"
Functions
static void gen6_update_sol_surfaces (struct brw_context *brw)
static void brw_gs_upload_binding_table (struct brw_context *brw)
Constructs the binding table for the WM surface state, which maps unit numbers to surface state objects.
struct gl_transform_feedback_object * brw_new_transform_feedback (struct gl_context *ctx, GLuint name)
void brw_delete_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
static void tally_prims_generated (struct brw_context *brw, struct brw_transform_feedback_object *obj)
Tally the number of primitives generated so far.
void brw_save_primitives_written_counters (struct brw_context *brw, struct brw_transform_feedback_object *obj)
Store the SO_NUM_PRIMS_WRITTEN counters for each stream (4 uint64_t values) to prim_count_bo.
static void compute_vertices_written_so_far (struct brw_context *brw, struct brw_transform_feedback_object *obj, uint64_t *vertices_written)
void brw_compute_xfb_vertices_written (struct brw_context *brw, struct brw_transform_feedback_object *obj)
Compute the number of vertices written by this transform feedback operation.
GLsizei brw_get_transform_feedback_vertex_count (struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint stream)
GetTransformFeedbackVertexCount() driver hook.
void brw_begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
void brw_end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void brw_pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void brw_resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Variables
const struct brw_tracked_state gen6_sol_surface
const struct brw_tracked_state gen6_gs_binding_table
Detailed Description
Code to initialize the binding table entries used by transform feedback.
Function Documentation
brw_begin_transform_feedback()
void brw_begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj)
References _3DSTATE_GS_SVB_INDEX, _mesa_compute_max_transform_feedback_vertices(), gl_context::_Shader, ADVANCE_BATCH, BEGIN_BATCH, brw_compute_xfb_vertices_written(), brw_context(), BRW_MAX_XFB_STREAMS, brw_save_primitives_written_counters(), gl_transform_feedback_state::CurrentObject, gl_pipeline_object::CurrentProgram, brw_context::gen, brw_transform_feedback_object::max_index, OUT_BATCH, brw_transform_feedback_object::primitive_mode, brw_transform_feedback_object::prims_generated, gl_program::sh, SVB_INDEX_SHIFT, and gl_context::TransformFeedback.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_compute_xfb_vertices_written()
void brw_compute_xfb_vertices_written (struct brw_context * brw, struct brw_transform_feedback_object * obj)
Compute the number of vertices written by this transform feedback operation.
References brw_transform_feedback_object::base, compute_vertices_written_so_far(), gl_transform_feedback_object::EndedAnytime, brw_transform_feedback_object::vertices_written, and brw_transform_feedback_object::vertices_written_valid.
Referenced by brw_begin_transform_feedback(), brw_get_index_type(), brw_get_transform_feedback_vertex_count(), and gen7_begin_transform_feedback().
brw_delete_transform_feedback()
void brw_delete_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References gl_transform_feedback_object::Buffers, brw_transform_feedback_object::offset_bo, and brw_transform_feedback_object::prim_count_bo.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_end_transform_feedback()
void brw_end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References brw_context(), brw_save_primitives_written_counters(), gl_transform_feedback_object::Paused, and brw_transform_feedback_object::vertices_written_valid.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_get_transform_feedback_vertex_count()
GLsizei brw_get_transform_feedback_vertex_count (struct gl_context * ctx, struct gl_transform_feedback_object * obj, GLuint stream)
GetTransformFeedbackVertexCount() driver hook.
Returns the number of vertices written to a particular stream by the last Begin/EndTransformFeedback block. Used to implement DrawTransformFeedback().
References brw_compute_xfb_vertices_written(), brw_context(), gl_transform_feedback_object::EndedAnytime, and brw_transform_feedback_object::vertices_written.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_gs_upload_binding_table()
static void brw_gs_upload_binding_table (struct brw_context * brw) static
Constructs the binding table for the WM surface state, which maps unit numbers to surface state objects.
References gl_context::_Shader, brw_context::base, brw_stage_state::bind_bo_offset, brw_context::bind_bo_offset, BRW_MAX_SURFACES, BRW_NEW_BINDING_TABLE_POINTERS, brw_state_batch(), brw_context::ctx, gl_pipeline_object::CurrentProgram, brw_context::ff_gs, brw_context::geometry_program, brw_context::gs, gl_context::NewDriverState, gl_transform_feedback_info::NumOutputs, brw_stage_state::prog_data, gl_program::sh, brw_stage_state::surf_offset, and brw_context::surf_offset.
brw_new_transform_feedback()
struct gl_transform_feedback_object* brw_new_transform_feedback (struct gl_context * ctx, GLuint name)
References _mesa_init_transform_feedback_object(), brw_transform_feedback_object::base, brw_context(), brw_context::bufmgr, CALLOC_STRUCT, brw_transform_feedback_object::offset_bo, and brw_transform_feedback_object::prim_count_bo.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_pause_transform_feedback()
void brw_pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References brw_context(), and brw_save_primitives_written_counters().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_resume_transform_feedback()
void brw_resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References _3DSTATE_GS_SVB_INDEX, ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_save_primitives_written_counters(), compute_vertices_written_so_far(), brw_transform_feedback_object::max_index, OUT_BATCH, and SVB_INDEX_SHIFT.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
brw_save_primitives_written_counters()
void brw_save_primitives_written_counters (struct brw_context * brw, struct brw_transform_feedback_object * obj)
Store the SO_NUM_PRIMS_WRITTEN counters for each stream (4 uint64_t values) to prim_count_bo.
If prim_count_bo is out of space, gather up the results so far into prims_generated[] and allocate a new buffer with enough space.
The number of primitives written is used to compute the number of vertices written to a transform feedback stream, which is required to implement DrawTransformFeedback().
References brw_emit_mi_flush(), brw_store_register_mem64(), gl_context::Const, brw_context::ctx, brw_context::gen, GEN6_SO_NUM_PRIMS_WRITTEN, GEN7_SO_NUM_PRIMS_WRITTEN, gl_constants::MaxVertexStreams, brw_transform_feedback_object::prim_count_bo, brw_transform_feedback_object::prim_count_buffer_index, and tally_prims_generated().
Referenced by brw_begin_transform_feedback(), brw_end_transform_feedback(), brw_get_index_type(), brw_pause_transform_feedback(), brw_resume_transform_feedback(), gen7_begin_transform_feedback(), gen7_end_transform_feedback(), gen7_pause_transform_feedback(), and gen7_resume_transform_feedback().
compute_vertices_written_so_far()
static void compute_vertices_written_so_far (struct brw_context * brw, struct brw_transform_feedback_object * obj, uint64_t * vertices_written) static
References gl_context::Const, brw_context::ctx, gl_constants::MaxVertexStreams, brw_transform_feedback_object::primitive_mode, brw_transform_feedback_object::prims_generated, tally_prims_generated(), and vertices_per_prim().
Referenced by brw_compute_xfb_vertices_written(), and brw_resume_transform_feedback().
gen6_update_sol_surfaces()
static void gen6_update_sol_surfaces (struct brw_context * brw) static
References brw_context::base, BRW_NEW_SURFACES, brw_update_sol_surface(), gl_transform_feedback_info::Buffers, gl_transform_feedback_object::Buffers, brw_context::ctx, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_output::DstOffset, brw_context::ff_gs, brw_context::geometry_program, brw_context::gs, gl_context::NewDriverState, gl_transform_feedback_output::NumComponents, gl_transform_feedback_info::NumOutputs, gl_transform_feedback_object::Offset, gl_transform_feedback_output::OutputBuffer, gl_transform_feedback_info::Outputs, gl_transform_feedback_object::program, gl_program::sh, gl_transform_feedback_buffer::Stride, brw_stage_state::surf_offset, brw_context::surf_offset, and gl_context::TransformFeedback.
tally_prims_generated()
static void tally_prims_generated (struct brw_context * brw, struct brw_transform_feedback_object * obj) static
Tally the number of primitives generated so far.
The buffer contains a series of pairs: (<start0, start1, start2, start3>, <end0, end1, end2, end3>) ; (<start0, start1, start2, start3>, <end0, end1, end2, end3>) ;
For each stream, we subtract the pair of values (end - start) to get the number of primitives generated during one section. We accumulate these values, adding them up to get the total number of primitives generated.
Note that we expose one stream pre-Gen7, so the above is just (start, end).
References brw_context::batch, intel_batchbuffer::bo, gl_context::Const, brw_context::ctx, intel_batchbuffer_flush, gl_constants::MaxVertexStreams, brw_context::perf_debug, brw_transform_feedback_object::prim_count_bo, brw_transform_feedback_object::prim_count_buffer_index, and brw_transform_feedback_object::prims_generated.
Referenced by brw_save_primitives_written_counters(), and compute_vertices_written_so_far().
Variable Documentation
gen6_gs_binding_table
const struct brw_tracked_state gen6_gs_binding_table
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_GEOMETRY_PROGRAM |
             BRW_NEW_VERTEX_PROGRAM |
             BRW_NEW_SURFACES,
   },
   .emit = brw_gs_upload_binding_table,
}
gen6_sol_surface
const struct brw_tracked_state gen6_sol_surface
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_TRANSFORM_FEEDBACK,
   },
   .emit = gen6_update_sol_surfaces,
}