Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen6_depth_state.c File Reference
#include "intel_batchbuffer.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "main/mtypes.h"
#include "main/fbobject.h"
#include "main/glformats.h"
Functions
void gen6_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
Function Documentation
gen6_emit_depth_stencil_hiz()
void gen6_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References _3DSTATE_CLEAR_PARAMS, _3DSTATE_DEPTH_BUFFER, _3DSTATE_HIER_DEPTH_BUFFER, _3DSTATE_STENCIL_BUFFER, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_depth_stall_flushes(), BRW_SURFACE_2D, BRW_TILEWALK_YMAJOR, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, GEN5_DEPTH_CLEAR_VALID, intel_get_renderbuffer(), intel_miptree_get_aligned_offset(), intel_renderbuffer::layer_count, MESA_FORMAT_S_UINT8, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, OUT_BATCH, OUT_RELOC, gl_texture_object::Target, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and translate_tex_target().
Referenced by brw_depth_writes_enabled(), and brwCreateContext().