Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_sol_state.c File Reference
Controls the stream output logic (SOL) stage of the gen7 hardware, which is used to implement GL_EXT_transform_feedback.
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "main/transformfeedback.h"
Functions
static void upload_3dstate_so_buffers (struct brw_context *brw)
void gen7_upload_3dstate_so_decl_list (struct brw_context *brw, const struct brw_vue_map *vue_map)
Outputs the 3DSTATE_SO_DECL_LIST command.
static bool query_active (struct gl_query_object *q)
static void upload_3dstate_streamout (struct brw_context *brw, bool active, const struct brw_vue_map *vue_map)
static void upload_sol_state (struct brw_context *brw)
void gen7_begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
void gen7_end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void gen7_pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void gen7_resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Variables
const struct brw_tracked_state gen7_sol_state
Detailed Description
Controls the stream output logic (SOL) stage of the gen7 hardware, which is used to implement GL_EXT_transform_feedback.
Function Documentation
gen7_begin_transform_feedback()
void gen7_begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj)
References ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH, brw_compute_xfb_vertices_written(), brw_context(), BRW_MAX_XFB_STREAMS, brw_save_primitives_written_counters(), can_do_pipelined_register_writes(), brw_context::gen, GEN7_SO_WRITE_OFFSET, intel_batchbuffer_flush, MI_LOAD_REGISTER_IMM, intel_batchbuffer::needs_sol_reset, OUT_BATCH, brw_transform_feedback_object::primitive_mode, brw_transform_feedback_object::prims_generated, and brw_context::screen.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_end_transform_feedback()
void gen7_end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References brw_context(), brw_save_primitives_written_counters(), gl_transform_feedback_object::Paused, and brw_transform_feedback_object::vertices_written_valid.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_pause_transform_feedback()
void gen7_pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_emit_mi_flush(), brw_save_primitives_written_counters(), brw_context::gen, GEN7_SO_WRITE_OFFSET, MI_STORE_REGISTER_MEM, brw_transform_feedback_object::offset_bo, OUT_BATCH, and OUT_RELOC.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_resume_transform_feedback()
void gen7_resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_save_primitives_written_counters(), brw_context::gen, GEN7_MI_LOAD_REGISTER_MEM, GEN7_SO_WRITE_OFFSET, brw_transform_feedback_object::offset_bo, OUT_BATCH, and OUT_RELOC.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
gen7_upload_3dstate_so_decl_list()
void gen7_upload_3dstate_so_decl_list (struct brw_context * brw, const struct brw_vue_map * vue_map)
Outputs the 3DSTATE_SO_DECL_LIST command.
The data output is a series of 64-bit entries containing a SO_DECL per stream. We only have one stream of rendering coming out of the GS unit, so we only emit stream 0 (low 16 bits) SO_DECLs.
References _3DSTATE_SO_DECL_LIST, ADVANCE_BATCH, BEGIN_BATCH, BRW_MAX_SOL_BUFFERS, gl_transform_feedback_output::ComponentOffset, brw_context::ctx, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_output::DstOffset, MAX_PROGRAM_OUTPUTS, MAX_VERTEX_STREAMS, gl_transform_feedback_output::NumComponents, gl_transform_feedback_info::NumOutputs, OUT_BATCH, gl_transform_feedback_output::OutputBuffer, gl_transform_feedback_output::OutputRegister, gl_transform_feedback_info::Outputs, gl_transform_feedback_object::program, gl_program::sh, SO_DECL_COMPONENT_MASK_SHIFT, SO_DECL_HOLE_FLAG, SO_DECL_OUTPUT_BUFFER_SLOT_SHIFT, SO_DECL_REGISTER_INDEX_SHIFT, SO_NUM_ENTRIES_0_SHIFT, SO_NUM_ENTRIES_1_SHIFT, SO_NUM_ENTRIES_2_SHIFT, SO_NUM_ENTRIES_3_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_0_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_1_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_2_SHIFT, SO_STREAM_TO_BUFFER_SELECTS_3_SHIFT, gl_transform_feedback_output::StreamId, and gl_context::TransformFeedback.
Referenced by upload_sol_state().
query_active()
static bool query_active (struct gl_query_object * q) static
References gl_query_object::Active.
Referenced by upload_3dstate_streamout().
upload_3dstate_so_buffers()
static void upload_3dstate_so_buffers (struct brw_context * brw) static
References _3DSTATE_SO_BUFFER, ADVANCE_BATCH, BEGIN_BATCH, gl_transform_feedback_object::Buffers, gl_transform_feedback_info::Buffers, brw_context::ctx, gl_transform_feedback_state::CurrentObject, intel_buffer_object(), intel_bufferobj_buffer(), gl_transform_feedback_object::Offset, OUT_BATCH, OUT_RELOC, gl_transform_feedback_object::program, gl_program::sh, gl_transform_feedback_object::Size, SO_BUFFER_INDEX_SHIFT, gl_transform_feedback_buffer::Stride, and gl_context::TransformFeedback.
Referenced by upload_sol_state().
upload_3dstate_streamout()
static void upload_3dstate_streamout (struct brw_context * brw, bool active, const struct brw_vue_map * vue_map) static
References _3DSTATE_STREAMOUT, ADVANCE_BATCH, BEGIN_BATCH, gl_transform_feedback_object::Buffers, gl_transform_feedback_info::Buffers, brw_context::ctx, gl_transform_feedback_state::CurrentObject, brw_context::gen, gl_context::Light, OUT_BATCH, gl_query_state::PrimitivesGenerated, gl_transform_feedback_object::program, gl_light_attrib::ProvokingVertex, gl_context::Query, query_active(), gl_context::RasterDiscard, SET_FIELD, gl_program::sh, SO_BUFFER_ENABLE, SO_FUNCTION_ENABLE, SO_RENDERING_DISABLE, SO_REORDER_TRAILING, SO_STATISTICS_ENABLE, gl_transform_feedback_buffer::Stride, and gl_context::TransformFeedback.
Referenced by upload_sol_state().
upload_sol_state()
static void upload_sol_state (struct brw_context * brw) static
References brw_context::ctx, brw_context::gen, gen7_upload_3dstate_so_decl_list(), gen8_upload_3dstate_so_buffers(), upload_3dstate_so_buffers(), upload_3dstate_streamout(), and brw_context::vue_map_geom_out.
Variable Documentation
gen7_sol_state
const struct brw_tracked_state gen7_sol_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_LIGHT,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_RASTERIZER_DISCARD |
               BRW_NEW_VUE_MAP_GEOM_OUT |
               BRW_NEW_TRANSFORM_FEEDBACK,
   },
   .emit = upload_sol_state,
}