Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_ds_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "main/shaderapi.h"
Functions
static void gen7_upload_tes_push_constants (struct brw_context *brw)
static void gen7_upload_ds_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen7_tes_push_constants
const struct brw_tracked_state gen7_ds_state
Function Documentation
gen7_upload_ds_state()
static void gen7_upload_ds_state (struct brw_context * brw) static
References _3DSTATE_DS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, intel_screen::devinfo, brw_context::enabled, GEN7_DS_COMPUTE_W_COORDINATE_ENABLE, GEN7_DS_ENABLE, GEN7_DS_MAX_THREADS_SHIFT, GEN7_DS_STATISTICS_ENABLE, HSW_DS_MAX_THREADS_SHIFT, brw_context::is_haswell, OUT_BATCH, OUT_RELOC, brw_stage_state::per_thread_scratch, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, brw_context::screen, SET_FIELD, brw_context::tes, and brw_context::tess_eval_program.
gen7_upload_tes_push_constants()
static void gen7_upload_tes_push_constants (struct brw_context * brw) static
References _3DSTATE_CONSTANT_DS, _mesa_shader_write_subroutine_indices(), brw_context::base, brw_program_const(), brw_context::ctx, gen6_upload_push_constants(), gen7_upload_constant_state(), brw_stage_state::prog_data, brw_program::program, brw_context::tes, and brw_context::tess_eval_program.
Variable Documentation
gen7_ds_state
const struct brw_tracked_state gen7_ds_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_TRANSFORM,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_TESS_PROGRAMS |
               BRW_NEW_TES_PROG_DATA,
   },
   .emit = gen7_upload_ds_state,
}
gen7_tes_push_constants
const struct brw_tracked_state gen7_tes_push_constants
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_PROGRAM_CONSTANTS,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_PUSH_CONSTANT_ALLOCATION |
               BRW_NEW_TESS_PROGRAMS |
               BRW_NEW_TES_PROG_DATA,
   },
   .emit = gen7_upload_tes_push_constants,
}