Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_viewport_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "main/viewport.h"
Functions
static void gen7_upload_sf_clip_viewport (struct brw_context *brw)
Variables
const struct brw_tracked_state gen7_sf_clip_viewport
Function Documentation
gen7_upload_sf_clip_viewport()
static void gen7_upload_sf_clip_viewport (struct brw_context * brw) static
References _3DSTATE_VIEWPORT_STATE_POINTERS_SF_CL, _mesa_get_viewport_xform(), ADVANCE_BATCH, BEGIN_BATCH, brw_calculate_guardband_size(), brw_state_batch(), brw_context::clip, brw_context::ctx, intel_screen::devinfo, gl_context::DrawBuffer, gen7_sf_clip_viewport::guardband, gen7_sf_clip_viewport::m00, gen7_sf_clip_viewport::m11, gen7_sf_clip_viewport::m22, gen7_sf_clip_viewport::m30, gen7_sf_clip_viewport::m31, gen7_sf_clip_viewport::m32, OUT_BATCH, brw_context::screen, brw_context::sf, gen7_sf_clip_viewport::viewport, brw_context::viewport_count, brw_context::vp_offset, gen7_sf_clip_viewport::xmax, gen7_sf_clip_viewport::xmin, gen7_sf_clip_viewport::ymax, and gen7_sf_clip_viewport::ymin.
Variable Documentation
gen7_sf_clip_viewport
const struct brw_tracked_state gen7_sf_clip_viewport
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_VIEWPORT,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VIEWPORT_COUNT,
   },
   .emit = gen7_upload_sf_clip_viewport,
}