Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_wm_state.c File Reference
#include <stdbool.h>
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
#include "brw_util.h"
#include "brw_wm.h"
#include "program/program.h"
#include "program/prog_parameter.h"
#include "program/prog_statevars.h"
#include "main/framebuffer.h"
#include "intel_batchbuffer.h"
Functions
static void upload_wm_state (struct brw_context *brw)
static void gen7_upload_ps_state (struct brw_context *brw, const struct brw_stage_state *stage_state, const struct brw_wm_prog_data *prog_data, bool enable_dual_src_blend, unsigned sample_mask, unsigned fast_clear_op)
static void upload_ps_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen7_wm_state
const struct brw_tracked_state gen7_ps_state
Function Documentation
gen7_upload_ps_state()
static void gen7_upload_ps_state (struct brw_context * brw, const struct brw_stage_state * stage_state, const struct brw_wm_prog_data * prog_data, bool enable_dual_src_blend, unsigned sample_mask, unsigned fast_clear_op) static
References _3DSTATE_PS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, intel_screen::devinfo, GEN7_PS_16_DISPATCH_ENABLE, GEN7_PS_8_DISPATCH_ENABLE, GEN7_PS_ATTRIBUTE_ENABLE, GEN7_PS_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN7_PS_DISPATCH_START_GRF_SHIFT_0, GEN7_PS_DISPATCH_START_GRF_SHIFT_2, GEN7_PS_DUAL_SOURCE_BLEND_ENABLE, GEN7_PS_FLOATING_POINT_MODE_ALT, GEN7_PS_OMASK_TO_RENDER_TARGET, GEN7_PS_POSOFFSET_NONE, GEN7_PS_POSOFFSET_SAMPLE, GEN7_PS_PUSH_CONSTANT_ENABLE, HSW_PS_MAX_THREADS_SHIFT, brw_context::is_haswell, IVB_PS_MAX_THREADS_SHIFT, OUT_BATCH, OUT_RELOC, brw_stage_state::per_thread_scratch, brw_stage_state::prog_offset, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, brw_context::screen, SET_FIELD, and brw_context::wm.
Referenced by upload_ps_state().
upload_ps_state()
static void upload_ps_state (struct brw_context * brw) static
References gl_colorbuffer_attrib::_UsesDualSrc, brw_context::base, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, gl_context::Color, brw_context::ctx, brw_context::fast_clear_op, gen6_determine_sample_mask(), gen7_upload_ps_state(), brw_context::is_haswell, brw_stage_state::prog_data, and brw_context::wm.
upload_wm_state()
static void upload_wm_state (struct brw_context * brw) static
References _3DSTATE_WM, _mesa_is_alpha_test_enabled(), _mesa_is_alpha_to_coverage_enabled(), ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_color_buffer_write_enabled(), brw_context::ctx, gl_context::DrawBuffer, gl_multisample_attrib::Enabled, GEN7_WM_BARYCENTRIC_INTERPOLATION_MODE_SHIFT, GEN7_WM_COMPUTED_DEPTH_MODE_SHIFT, GEN7_WM_DISPATCH_ENABLE, GEN7_WM_EARLY_DS_CONTROL_PREPS, GEN7_WM_EARLY_DS_CONTROL_PSEXEC, GEN7_WM_KILL_ENABLE, GEN7_WM_LINE_AA_WIDTH_1_0, GEN7_WM_LINE_END_CAP_AA_WIDTH_0_5, GEN7_WM_LINE_STIPPLE_ENABLE, GEN7_WM_MSDISPMODE_PERPIXEL, GEN7_WM_MSDISPMODE_PERSAMPLE, GEN7_WM_MSRAST_OFF_PIXEL, GEN7_WM_MSRAST_ON_PATTERN, GEN7_WM_POLYGON_STIPPLE_ENABLE, GEN7_WM_STATISTICS_ENABLE, GEN7_WM_USES_INPUT_COVERAGE_MASK, GEN7_WM_USES_SOURCE_DEPTH, GEN7_WM_USES_SOURCE_W, HSW_WM_UAV_ONLY, brw_context::is_haswell, gl_context::Line, gl_context::Multisample, OUT_BATCH, gl_context::Polygon, brw_stage_state::prog_data, gl_line_attrib::StippleFlag, gl_polygon_attrib::StippleFlag, and brw_context::wm.
Variable Documentation
gen7_ps_state
const struct brw_tracked_state gen7_ps_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_COLOR |
               _NEW_MULTISAMPLE,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_FS_PROG_DATA,
   },
   .emit = upload_ps_state,
}
gen7_wm_state
const struct brw_tracked_state gen7_wm_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_COLOR |
               _NEW_LINE |
               _NEW_MULTISAMPLE |
               _NEW_POLYGON,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_FS_PROG_DATA,
   },
   .emit = upload_wm_state,
}