Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_l3_state.c File Reference
#include "common/gen_l3_config.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
Functions
static struct gen_l3_weights get_pipeline_state_l3_weights (const struct brw_context *brw)
Calculate the desired L3 partitioning based on the current state of the pipeline.
static void setup_l3_config (struct brw_context *brw, const struct gen_l3_config *cfg)
Program the hardware to use the specified L3 configuration.
static void update_urb_size (struct brw_context *brw, const struct gen_l3_config *cfg)
Update the URB size in the context state for the specified L3 configuration.
static void emit_l3_state (struct brw_context *brw)
void gen7_restore_default_l3_config (struct brw_context *brw)
Hack to restore the default L3 configuration.
Variables
const struct brw_tracked_state gen7_l3_state
Function Documentation
emit_l3_state()
static void emit_l3_state (struct brw_context * brw) static
References BRW_NEW_BATCH, can_do_pipelined_register_writes(), brw_context::config, brw_context::ctx, intel_screen::devinfo, get_pipeline_state_l3_weights(), brw_context::l3, gl_context::NewDriverState, brw_context::screen, setup_l3_config(), and update_urb_size().
gen7_restore_default_l3_config()
void gen7_restore_default_l3_config (struct brw_context * brw)
Hack to restore the default L3 configuration.
This will be called at the end of every batch in order to reset the L3 configuration to the default values for the time being until the kernel is fixed. Until kernel commit 6702cf16e0ba8b0129f5aa1b6609d4e9c70bc13b (included in v4.1) we would set the MI_RESTORE_INHIBIT bit when submitting batch buffers for the default context used by the DDX, which meant that any context state changed by the GL would leak into the DDX, the assumption being that the DDX would initialize any state it cares about manually. The DDX is however not careful enough to program an L3 configuration explicitly, and it makes assumptions about it (URB size) which won't hold and cause it to misrender if we let our L3 set-up to leak into the DDX.
Since v4.1 of the Linux kernel the default context is saved and restored normally, so it's far less likely for our L3 programming to interfere with other contexts – In fact restoring the default L3 configuration at the end of the batch will be redundant most of the time. A kind of state leak is still possible though if the context making assumptions about L3 state is created immediately after our context was active (e.g. without the DDX default context being scheduled in between) because at present the DRM doesn't fully initialize the contents of newly created contexts and instead sets the MI_RESTORE_INHIBIT flag causing it to inherit the state from the last active context.
It's possible to realize such a scenario if, say, an X server (or a GL application using an outdated non-L3-aware Mesa version) is started while another GL application is running and happens to have modified the L3 configuration, or if no X server is running at all and a GL application using a non-L3-aware Mesa version is started after another GL application ran and modified the L3 configuration – The latter situation can actually be reproduced easily on IVB in our CI system.
References can_do_pipelined_register_writes(), brw_context::config, intel_screen::devinfo, brw_context::l3, brw_context::screen, setup_l3_config(), and update_urb_size().
Referenced by brw_finish_batch().
get_pipeline_state_l3_weights()
static struct gen_l3_weights get_pipeline_state_l3_weights (const struct brw_context * brw) static
Calculate the desired L3 partitioning based on the current state of the pipeline.
For now this simply returns the conservative defaults calculated by get_default_l3_weights(), but we could probably do better by gathering more statistics from the pipeline state (e.g. guess of expected URB usage and bound surfaces), or by using feed-back from performance counters.
References brw_stage_state::prog_data, gl_program::sh, and brw_stage_state::stage.
Referenced by emit_l3_state().
setup_l3_config()
static void setup_l3_config (struct brw_context * brw, const struct gen_l3_config * cfg) static
Program the hardware to use the specified L3 configuration.
References ADVANCE_BATCH, BEGIN_BATCH, brw_emit_pipe_control_flush(), can_do_hsw_l3_atomics(), brw_context::gen, GEN7_L3CNTLREG2, GEN7_L3CNTLREG2_SLM_ENABLE, GEN7_L3CNTLREG2_URB_LOW_BW, GEN7_L3CNTLREG3, GEN7_L3SQCREG1, GEN7_L3SQCREG1_CONV_C_UC, GEN7_L3SQCREG1_CONV_DC_UC, GEN7_L3SQCREG1_CONV_IS_UC, GEN7_L3SQCREG1_CONV_T_UC, GEN8_L3CNTLREG, GEN8_L3CNTLREG_SLM_ENABLE, HSW_L3SQCREG1_SQGHPCI_DEFAULT, HSW_ROW_CHICKEN3, HSW_ROW_CHICKEN3_L3_ATOMIC_DISABLE, HSW_SCRATCH1, HSW_SCRATCH1_L3_ATOMIC_DISABLE, brw_context::is_baytrail, brw_context::is_haswell, IVB_L3SQCREG1_SQGHPCI_DEFAULT, MI_LOAD_REGISTER_IMM, OUT_BATCH, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DATA_CACHE_FLUSH, PIPE_CONTROL_INSTRUCTION_INVALIDATE, PIPE_CONTROL_NO_WRITE, PIPE_CONTROL_STATE_CACHE_INVALIDATE, PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE, REG_MASK, brw_context::screen, SET_FIELD, and VLV_L3SQCREG1_SQGHPCI_DEFAULT.
Referenced by emit_l3_state(), and gen7_restore_default_l3_config().
update_urb_size()
static void update_urb_size (struct brw_context * brw, const struct gen_l3_config * cfg) static
Update the URB size in the context state for the specified L3 configuration.
References BRW_NEW_URB_SIZE, brw_context::ctx, intel_screen::devinfo, gl_context::NewDriverState, brw_context::screen, brw_context::size, and brw_context::urb.
Referenced by emit_l3_state(), and gen7_restore_default_l3_config().
Variable Documentation
gen7_l3_state
const struct brw_tracked_state gen7_l3_state
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CS_PROG_DATA |
             BRW_NEW_FS_PROG_DATA |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = emit_l3_state
}
Referenced by blorp_exec().