Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_cs_state.c File Reference
#include "util/ralloc.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_cs.h"
#include "brw_wm.h"
#include "intel_mipmap_tree.h"
#include "intel_batchbuffer.h"
#include "brw_state.h"
#include "program/prog_statevars.h"
#include "compiler/glsl/ir_uniform.h"
#include "main/shaderapi.h"
Functions
static void brw_upload_cs_state (struct brw_context *brw)
static void brw_upload_cs_push_constants (struct brw_context *brw, const struct gl_program *prog, const struct brw_cs_prog_data *cs_prog_data, struct brw_stage_state *stage_state)
Creates a region containing the push constants for the CS on gen7+.
static void gen7_upload_cs_push_constants (struct brw_context *brw)
static void brw_upload_cs_pull_constants (struct brw_context *brw)
Creates a new CS constant buffer reflecting the current CS program's constants, if needed by the CS program.
Variables
const struct brw_tracked_state brw_cs_state
const struct brw_tracked_state gen7_cs_push_constants
const struct brw_tracked_state brw_cs_pull_constants
Function Documentation
brw_upload_cs_pull_constants()
static void brw_upload_cs_pull_constants (struct brw_context * brw) static
Creates a new CS constant buffer reflecting the current CS program's constants, if needed by the CS program.
References _mesa_shader_write_subroutine_indices(), brw_context::base, BRW_NEW_SURFACES, brw_upload_pull_constants(), brw_context::compute_program, brw_context::cs, brw_context::ctx, brw_stage_state::prog_data, and brw_program::program.
brw_upload_cs_push_constants()
static void brw_upload_cs_push_constants (struct brw_context * brw, const struct gl_program * prog, const struct brw_cs_prog_data * cs_prog_data, struct brw_stage_state * stage_state) static
Creates a region containing the push constants for the CS on gen7+.
Push constants are constant values (such as GLSL uniforms) that are pre-loaded into a shader stage's register space at thread spawn time.
For other stages, see brw_curbe.c:brw_upload_constant_buffer for the equivalent gen4/5 code and gen6_vs_state.c:gen6_upload_push_constants for gen6+.
References brw_state_batch(), brw_context::ctx, gl_program::Parameters, brw_stage_state::push_const_offset, and brw_stage_state::push_const_size.
Referenced by gen7_upload_cs_push_constants().
brw_upload_cs_state()
static void brw_upload_cs_state (struct brw_context * brw) static
References ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_stage_state::bind_bo_offset, brw_context::bo, brw_emit_buffer_surface_state(), brw_state_batch(), brw_context::cs, intel_screen::devinfo, brw_context::gen, brw_context::is_haswell, MEDIA_CURBE_LOAD, MEDIA_INTERFACE_DESCRIPTOR_LOAD, MEDIA_VFE_STATE, OUT_BATCH, OUT_RELOC, OUT_RELOC64, brw_stage_state::per_thread_scratch, brw_stage_state::prog_data, brw_stage_state::prog_offset, brw_stage_state::push_const_offset, brw_stage_state::sampler_count, brw_stage_state::sampler_offset, brw_stage_state::scratch_bo, brw_context::screen, SET_FIELD, brw_context::shader_time, intel_screen::subslice_total, and brw_stage_state::surf_offset.
gen7_upload_cs_push_constants()
static void gen7_upload_cs_push_constants (struct brw_context * brw) static
References _mesa_shader_write_subroutine_indices(), brw_context::base, brw_upload_cs_push_constants(), brw_context::compute_program, brw_context::cs, brw_context::ctx, if(), brw_stage_state::prog_data, and brw_program::program.
Variable Documentation
brw_cs_pull_constants
const struct brw_tracked_state brw_cs_pull_constants
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_COMPUTE_PROGRAM |
             BRW_NEW_CS_PROG_DATA,
   },
   .emit = brw_upload_cs_pull_constants,
}
brw_cs_state
const struct brw_tracked_state brw_cs_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_CS_PROG_DATA |
             BRW_NEW_PUSH_CONSTANT_ALLOCATION |
             BRW_NEW_SAMPLER_STATE_TABLE |
             BRW_NEW_SURFACES,
   },
   .emit = brw_upload_cs_state
}
gen7_cs_push_constants
const struct brw_tracked_state gen7_cs_push_constants
Initial value:
= {
   .dirty = {
      .mesa = _NEW_PROGRAM_CONSTANTS,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_COMPUTE_PROGRAM |
             BRW_NEW_CS_PROG_DATA |
             BRW_NEW_PUSH_CONSTANT_ALLOCATION,
   },
   .emit = gen7_upload_cs_push_constants,
}