Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_misc_state.c File Reference
#include "main/mtypes.h"
#include "intel_batchbuffer.h"
#include "intel_mipmap_tree.h"
#include "intel_fbo.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
Functions
void gen7_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
Variables
const struct brw_tracked_state gen7_depthbuffer
Function Documentation
gen7_emit_depth_stencil_hiz()
void gen7_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References gl_stencil_attrib::_WriteEnabled, ADVANCE_BATCH, BEGIN_BATCH, brw_depth_writes_enabled(), brw_emit_depth_stall_flushes(), BRW_SURFACE_2D, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, GEN7_3DSTATE_CLEAR_PARAMS, GEN7_3DSTATE_DEPTH_BUFFER, GEN7_3DSTATE_HIER_DEPTH_BUFFER, GEN7_3DSTATE_STENCIL_BUFFER, GEN7_MOCS_L3, HSW_STENCIL_ENABLED, brw_context::hw_ctx, intel_get_renderbuffer(), brw_context::is_haswell, intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, brw_context::no_depth_or_stencil, OUT_BATCH, OUT_RELOC, gl_context::Stencil, gl_texture_object::Target, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and translate_tex_target().
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
Variable Documentation
gen7_depthbuffer
const struct brw_tracked_state gen7_depthbuffer
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_DEPTH |
              _NEW_STENCIL,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP,
   },
   .emit = brw_emit_depthbuffer,
}
See also
brw_context.state.depth_region