Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_urb.c File Reference
#include "main/macros.h"
#include "intel_batchbuffer.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "common/gen_l3_config.h"
Functions
static void gen7_allocate_push_constants (struct brw_context *brw)
The following diagram shows how we partition the URB:
void gen7_emit_push_constant_state (struct brw_context *brw, unsigned vs_size, unsigned hs_size, unsigned ds_size, unsigned gs_size, unsigned fs_size)
static void upload_urb (struct brw_context *brw)
void gen7_upload_urb (struct brw_context *brw, unsigned vs_size, bool gs_present, bool tess_present)
Variables
const struct brw_tracked_state gen7_push_constant_space
const struct brw_tracked_state gen7_urb
Function Documentation
gen7_allocate_push_constants()
static void gen7_allocate_push_constants (struct brw_context * brw) static
The following diagram shows how we partition the URB:
16kB or 32kB Rest of the URB space __________-__________ _________________-_________________ / \ / \ +----------------------------------------------------------—+ | VS/HS/DS/GS/FS Push | VS/HS/DS/GS URB | | Constants | Entries | +----------------------------------------------------------—+
Notably, push constants must be stored at the beginning of the URB space, while entries can be stored anywhere. Ivybridge and Haswell GT1/GT2 have a maximum constant buffer size of 16kB, while Haswell GT3 doubles this (32kB).
Ivybridge and Haswell GT1/GT2 allow push constants to be located (and sized) in increments of 1kB. Haswell GT3 requires them to be located and sized in increments of 2kB.
Currently we split the constant buffer space evenly among whatever stages are active. This is probably not ideal, but simple.
Ivybridge GT1 and Haswell GT1 have 128kB of URB space. Ivybridge GT2 and Haswell GT2 have 256kB of URB space. Haswell GT3 has 512kB of URB space.
See "Volume 2a: 3D Pipeline," section 1.8, "Volume 1b: Configurations", and the documentation for 3DSTATE_PUSH_CONSTANT_ALLOC_xS.
References BRW_NEW_PUSH_CONSTANT_ALLOCATION, brw_context::ctx, brw_context::gen, gen7_emit_push_constant_state(), brw_context::geometry_program, brw_context::gt, brw_context::is_haswell, gl_context::NewDriverState, and brw_context::tess_eval_program.
gen7_emit_push_constant_state()
void gen7_emit_push_constant_state (struct brw_context * brw, unsigned vs_size, unsigned hs_size, unsigned ds_size, unsigned gs_size, unsigned fs_size)
References _3DSTATE_PUSH_CONSTANT_ALLOC_DS, _3DSTATE_PUSH_CONSTANT_ALLOC_GS, _3DSTATE_PUSH_CONSTANT_ALLOC_HS, _3DSTATE_PUSH_CONSTANT_ALLOC_PS, _3DSTATE_PUSH_CONSTANT_ALLOC_VS, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, gen7_emit_cs_stall_flush(), GEN7_PUSH_CONSTANT_BUFFER_OFFSET_SHIFT, brw_context::is_baytrail, brw_context::is_haswell, and OUT_BATCH.
Referenced by brw_get_index_type(), and gen7_allocate_push_constants().
gen7_upload_urb()
void gen7_upload_urb (struct brw_context * brw, unsigned vs_size, bool gs_present, bool tess_present)
References _3DSTATE_URB_VS, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, BRW_NEW_CONTEXT, BRW_NEW_URB_SIZE, brw_context::ctx, intel_screen::devinfo, brw_context::dsize, brw_context::gen, gen7_emit_vs_workaround_flush(), GEN7_URB_ENTRY_SIZE_SHIFT, GEN7_URB_STARTING_ADDRESS_SHIFT, brw_context::gs, brw_context::gs_present, brw_context::gsize, brw_context::gt, brw_context::hsize, brw_context::is_baytrail, brw_context::is_haswell, gl_context::NewDriverState, OUT_BATCH, brw_stage_state::prog_data, brw_context::screen, brw_context::size, brw_context::tcs, brw_context::tes, brw_context::tess_present, brw_context::urb, brw_context::vs, and brw_context::vsize.
Referenced by blorp_emit_urb_config(), brw_get_index_type(), and upload_urb().
upload_urb()
static void upload_urb (struct brw_context * brw) static
References brw_context::base, gen7_upload_urb(), brw_context::gs, brw_stage_state::prog_data, brw_context::tes, and brw_context::vs.
Variable Documentation
gen7_push_constant_space
const struct brw_tracked_state gen7_push_constant_space
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_CONTEXT |
             BRW_NEW_GEOMETRY_PROGRAM |
             BRW_NEW_TESS_PROGRAMS,
   },
   .emit = gen7_allocate_push_constants,
}
gen7_urb
const struct brw_tracked_state gen7_urb
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_CONTEXT |
             BRW_NEW_URB_SIZE |
             BRW_NEW_GS_PROG_DATA |
             BRW_NEW_TCS_PROG_DATA |
             BRW_NEW_TES_PROG_DATA |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = upload_urb,
}