Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_wm_surface_state.c File Reference
#include "main/mtypes.h"
#include "main/blend.h"
#include "main/samplerobj.h"
#include "main/texformat.h"
#include "main/teximage.h"
#include "program/prog_parameter.h"
#include "program/prog_instruction.h"
#include "intel_mipmap_tree.h"
#include "intel_batchbuffer.h"
#include "intel_tex.h"
#include "intel_fbo.h"
#include "intel_buffer_objects.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_wm.h"
Functions
void gen7_check_surface_setup (uint32_t *surf, bool is_render_target)
static void gen7_emit_null_surface_state (struct brw_context *brw, unsigned width, unsigned height, unsigned samples, uint32_t *out_offset)
Creates a null surface.
void gen7_init_vtable_surface_functions (struct brw_context *brw)
Function Documentation
gen7_check_surface_setup()
void gen7_check_surface_setup (uint32_t * surf, bool is_render_target)
References GEN7_SURFACE_ARYSPC_LOD0, GEN7_SURFACE_MSFMT_DEPTH_STENCIL, GEN7_SURFACE_MSFMT_MSS, GEN7_SURFACE_MULTISAMPLECOUNT_1, GEN7_SURFACE_MULTISAMPLECOUNT_4, GEN7_SURFACE_MULTISAMPLECOUNT_8, GET_FIELD, INTEL_MASK, and void.
Referenced by gen7_emit_null_surface_state().
gen7_emit_null_surface_state()
static void gen7_emit_null_surface_state (struct brw_context * brw, unsigned width, unsigned height, unsigned samples, uint32_t * out_offset) static
Creates a null surface.
This is used when the shader doesn't write to any color output. An FB write to target 0 will still be emitted, because that's how the thread is terminated (and computed depth is returned), so we need to have the hardware discard the target 0 color output..
References brw_state_batch(), BRW_SURFACE_FORMAT_SHIFT, BRW_SURFACE_NULL, BRW_SURFACE_TYPE_SHIFT, gen7_check_surface_setup(), GEN7_SURFACE_TILING_Y, and SET_FIELD.
Referenced by gen7_init_vtable_surface_functions().
gen7_init_vtable_surface_functions()
void gen7_init_vtable_surface_functions (struct brw_context * brw)
References brw_update_renderbuffer_surface(), brw_context::emit_null_surface_state, gen7_emit_null_surface_state(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext().