Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen7_sf_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "main/macros.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "intel_batchbuffer.h"
Functions
static void upload_sbe_state (struct brw_context *brw)
static void upload_sf_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen7_sbe_state
const struct brw_tracked_state gen7_sf_state
Function Documentation
upload_sbe_state()
static void upload_sbe_state (struct brw_context * brw) static
References _3DSTATE_SBE, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, calculate_attr_overrides(), brw_context::ctx, gl_context::DrawBuffer, GEN6_SF_POINT_SPRITE_LOWERLEFT, GEN6_SF_POINT_SPRITE_UPPERLEFT, GEN7_SBE_NUM_OUTPUTS_SHIFT, GEN7_SBE_SWIZZLE_ENABLE, GEN7_SBE_URB_ENTRY_READ_LENGTH_SHIFT, GEN7_SBE_URB_ENTRY_READ_OFFSET_SHIFT, OUT_BATCH, gl_context::Point, brw_stage_state::prog_data, gl_point_attrib::SpriteOrigin, and brw_context::wm.
upload_sf_state()
static void upload_sf_state (struct brw_context * brw) static
References _3DSTATE_SF, gl_polygon_attrib::_FrontBit, ADVANCE_BATCH, gl_polygon_attrib::BackMode, BEGIN_BATCH, brw_depthbuffer_format(), brw_get_line_width(), brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_context::DrawBuffer, gl_multisample_attrib::Enabled, gl_polygon_attrib::FrontMode, GEN6_SF_BACK_POINT, GEN6_SF_BACK_SOLID, GEN6_SF_BACK_WIREFRAME, GEN6_SF_CULL_BACK, GEN6_SF_CULL_BOTH, GEN6_SF_CULL_FRONT, GEN6_SF_CULL_NONE, GEN6_SF_FRONT_POINT, GEN6_SF_FRONT_SOLID, GEN6_SF_FRONT_WIREFRAME, GEN6_SF_GLOBAL_DEPTH_OFFSET_POINT, GEN6_SF_GLOBAL_DEPTH_OFFSET_SOLID, GEN6_SF_GLOBAL_DEPTH_OFFSET_WIREFRAME, GEN6_SF_LINE_AA_ENABLE, GEN6_SF_LINE_AA_MODE_TRUE, GEN6_SF_LINE_END_CAP_WIDTH_1_0, GEN6_SF_LINE_PROVOKE_SHIFT, GEN6_SF_LINE_WIDTH_SHIFT, GEN6_SF_MSRAST_ON_PATTERN, GEN6_SF_SCISSOR_ENABLE, GEN6_SF_STATISTICS_ENABLE, GEN6_SF_TRI_PROVOKE_SHIFT, GEN6_SF_TRIFAN_PROVOKE_SHIFT, GEN6_SF_USE_STATE_POINT_WIDTH, GEN6_SF_VIEWPORT_TRANSFORM_ENABLE, GEN6_SF_WINDING_CCW, GEN7_SF_DEPTH_BUFFER_SURFACE_FORMAT_SHIFT, HSW_SF_LINE_STIPPLE_ENABLE, brw_context::is_haswell, gl_context::Light, gl_context::Line, gl_point_attrib::MaxSize, gl_point_attrib::MinSize, gl_context::Multisample, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, OUT_BATCH, OUT_BATCH_F, gl_context::Point, gl_context::Polygon, gl_light_attrib::ProvokingVertex, brw_context::sf, gl_point_attrib::Size, gl_line_attrib::SmoothFlag, gl_line_attrib::StippleFlag, use_state_point_size(), and brw_context::viewport_transform_enable.
Variable Documentation
gen7_sbe_state
const struct brw_tracked_state gen7_sbe_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LIGHT |
               _NEW_POINT |
               _NEW_POLYGON |
               _NEW_PROGRAM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FRAGMENT_PROGRAM |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_TES_PROG_DATA |
               BRW_NEW_PRIMITIVE |
               BRW_NEW_VUE_MAP_GEOM_OUT,
   },
   .emit = upload_sbe_state,
}
gen7_sf_state
const struct brw_tracked_state gen7_sf_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LIGHT |
               _NEW_LINE |
               _NEW_MULTISAMPLE |
               _NEW_POINT |
               _NEW_POLYGON |
               _NEW_PROGRAM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_PRIMITIVE |
               BRW_NEW_TES_PROG_DATA |
               BRW_NEW_VUE_MAP_GEOM_OUT,
   },
   .emit = upload_sf_state,
}