Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_multisample_state.c File Reference
#include "intel_batchbuffer.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_multisample_state.h"
Functions
void gen8_emit_3dstate_multisample (struct brw_context *brw, unsigned num_samples)
3DSTATE_MULTISAMPLE
void gen8_emit_3dstate_sample_pattern (struct brw_context *brw)
3DSTATE_SAMPLE_PATTERN
static void upload_multisample_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen8_multisample_state
Function Documentation
gen8_emit_3dstate_multisample()
void gen8_emit_3dstate_multisample (struct brw_context * brw, unsigned num_samples)
3DSTATE_MULTISAMPLE
References ADVANCE_BATCH, BEGIN_BATCH, GEN8_3DSTATE_MULTISAMPLE, MS_PIXEL_LOCATION_CENTER, and OUT_BATCH.
Referenced by brw_get_index_type(), gen8_hiz_exec(), and upload_multisample_state().
gen8_emit_3dstate_sample_pattern()
void gen8_emit_3dstate_sample_pattern (struct brw_context * brw)
3DSTATE_SAMPLE_PATTERN
References _3DSTATE_SAMPLE_PATTERN, ADVANCE_BATCH, BEGIN_BATCH, brw_multisample_positions_16x, brw_multisample_positions_1x_2x, brw_multisample_positions_4x, brw_multisample_positions_8x, and OUT_BATCH.
Referenced by brw_get_index_type(), and brw_upload_initial_gpu_state().
upload_multisample_state()
static void upload_multisample_state (struct brw_context * brw) static
References gen6_determine_sample_mask(), gen6_emit_3dstate_sample_mask(), gen8_emit_3dstate_multisample(), and brw_context::num_samples.
Variable Documentation
gen8_multisample_state
const struct brw_tracked_state gen8_multisample_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_MULTISAMPLE,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CONTEXT |
             BRW_NEW_NUM_SAMPLES,
   },
   .emit = upload_multisample_state
}