Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_depth_state.c File Reference
#include "intel_batchbuffer.h"
#include "intel_mipmap_tree.h"
#include "intel_fbo.h"
#include "intel_resolve_map.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "compiler/brw_eu_defines.h"
#include "brw_wm.h"
#include "main/framebuffer.h"
Functions
static void emit_depth_packets (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depthbuffer_format, uint32_t depth_surface_type, bool depth_writable, struct intel_mipmap_tree *stencil_mt, bool stencil_writable, bool hiz, uint32_t width, uint32_t height, uint32_t depth, uint32_t lod, uint32_t min_array_element)
Helper function to emit depth related command packets.
void gen8_emit_depth_stencil_hiz (struct brw_context *brw, struct intel_mipmap_tree *depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree *stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
static bool pma_fix_enable (const struct brw_context *brw)
Should we set the PMA FIX ENABLE bit?
void gen8_write_pma_stall_bits (struct brw_context *brw, uint32_t pma_stall_bits)
static void gen8_emit_pma_stall_workaround (struct brw_context *brw)
void gen8_hiz_exec (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Emit packets to perform a depth/HiZ resolve or fast depth/stencil clear.
Variables
const struct brw_tracked_state gen8_pma_fix
Function Documentation
emit_depth_packets()
static void emit_depth_packets (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depthbuffer_format, uint32_t depth_surface_type, bool depth_writable, struct intel_mipmap_tree * stencil_mt, bool stencil_writable, bool hiz, uint32_t width, uint32_t height, uint32_t depth, uint32_t lod, uint32_t min_array_element) static
Helper function to emit depth related command packets.
References ADVANCE_BATCH, BDW_MOCS_WB, BEGIN_BATCH, brw_emit_depth_stall_flushes(), brw_context::gen, GEN7_3DSTATE_CLEAR_PARAMS, GEN7_3DSTATE_DEPTH_BUFFER, GEN7_3DSTATE_HIER_DEPTH_BUFFER, GEN7_3DSTATE_STENCIL_BUFFER, HSW_STENCIL_ENABLED, brw_context::hw_ctx, brw_context::no_depth_or_stencil, OUT_BATCH, OUT_RELOC64, and SKL_MOCS_WB.
Referenced by gen8_emit_depth_stencil_hiz(), and gen8_hiz_exec().
gen8_emit_depth_stencil_hiz()
void gen8_emit_depth_stencil_hiz (struct brw_context * brw, struct intel_mipmap_tree * depth_mt, uint32_t depth_offset, uint32_t depthbuffer_format, uint32_t depth_surface_type, struct intel_mipmap_tree * stencil_mt, bool hiz, bool separate_stencil, uint32_t width, uint32_t height, uint32_t tile_x, uint32_t tile_y)
References gl_stencil_attrib::_WriteEnabled, brw_depth_writes_enabled(), brw_depthbuffer_format(), BRW_SURFACE_2D, BUFFER_DEPTH, BUFFER_STENCIL, brw_context::ctx, gl_context::DrawBuffer, emit_depth_packets(), brw_context::gen, intel_get_renderbuffer(), intel_renderbuffer::layer_count, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::Stencil, gl_texture_object::Target, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and translate_tex_target().
Referenced by brw_depth_writes_enabled(), and brwCreateContext().
gen8_emit_pma_stall_workaround()
static void gen8_emit_pma_stall_workaround (struct brw_context * brw) static
References brw_context::gen, GEN8_HIZ_NP_EARLY_Z_FAILS_DISABLE, GEN8_HIZ_NP_PMA_FIX_ENABLE, gen8_write_pma_stall_bits(), and pma_fix_enable().
gen8_hiz_exec()
void gen8_hiz_exec (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int layer, enum blorp_hiz_op op)
Emit packets to perform a depth/HiZ resolve or fast depth/stencil clear.
See the "Optimized Depth Buffer Clear and/or Stencil Buffer Clear" section of the hardware documentation for details.
References _3DSTATE_DRAWING_RECTANGLE, _3DSTATE_WM_HZ_OP, _NEW_BUFFERS, _NEW_DEPTH, _NEW_MULTISAMPLE, ADVANCE_BATCH, BEGIN_BATCH, brw_context::bo, brw_depth_format(), brw_emit_pipe_control_flush(), brw_emit_pipe_control_write(), brw_render_cache_set_add_bo(), BRW_SURFACE_2D, emit_depth_packets(), brw_context::gen, gen8_emit_3dstate_multisample(), GEN8_WM_HZ_DEPTH_CLEAR, GEN8_WM_HZ_DEPTH_RESOLVE, GEN8_WM_HZ_FULL_SURFACE_DEPTH_CLEAR, GEN8_WM_HZ_HIZ_RESOLVE, gen8_write_pma_stall_bits(), brw_context::NewGLState, brw_context::num_samples, OUT_BATCH, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_WRITE_IMMEDIATE, SET_FIELD, and brw_context::workaround_bo.
Referenced by brw_depth_writes_enabled(), and intel_hiz_exec().
gen8_write_pma_stall_bits()
void gen8_write_pma_stall_bits (struct brw_context * brw, uint32_t pma_stall_bits)
References gl_stencil_attrib::_WriteEnabled, ADVANCE_BATCH, BEGIN_BATCH, brw_emit_pipe_control_flush(), brw_context::ctx, GEN7_CACHE_MODE_1, GEN8_HIZ_PMA_MASK_BITS, MI_LOAD_REGISTER_IMM, OUT_BATCH, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_DEPTH_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, brw_context::pma_stall_bits, and gl_context::Stencil.
Referenced by blorp_exec(), brw_state_dirty(), gen8_emit_pma_stall_workaround(), and gen8_hiz_exec().
pma_fix_enable()
static bool pma_fix_enable (const struct brw_context * brw) static
Should we set the PMA FIX ENABLE bit?
To avoid unnecessary depth related stalls, we need to set this bit. However, there is a very complicated formula which governs when it is legal to do so. This function computes that.
See the documenation for the CACHE_MODE_1 register, bit 11.
References _mesa_is_alpha_test_enabled(), _mesa_is_alpha_to_coverage_enabled(), gl_stencil_attrib::_WriteEnabled, brw_context::base, brw_depth_writes_enabled(), BUFFER_DEPTH, brw_context::ctx, gl_context::Depth, gl_context::DrawBuffer, intel_get_renderbuffer(), intel_renderbuffer_has_hiz(), brw_stage_state::prog_data, gl_context::Stencil, gl_depthbuffer_attrib::Test, and brw_context::wm.
Referenced by gen8_emit_pma_stall_workaround().
Variable Documentation
gen8_pma_fix
const struct brw_tracked_state gen8_pma_fix
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR |
              _NEW_DEPTH |
              _NEW_MULTISAMPLE |
              _NEW_STENCIL,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_FS_PROG_DATA,
   },
   .emit = gen8_emit_pma_stall_workaround
}