Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_sol_state.c File Reference
Controls the stream output logic (SOL) stage of the gen8 hardware, which is used to implement GL_EXT_transform_feedback.
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "main/transformfeedback.h"
Functions
void gen8_upload_3dstate_so_buffers (struct brw_context *brw)
Detailed Description
Controls the stream output logic (SOL) stage of the gen8 hardware, which is used to implement GL_EXT_transform_feedback.
Function Documentation
gen8_upload_3dstate_so_buffers()
void gen8_upload_3dstate_so_buffers (struct brw_context * brw)
References _3DSTATE_SO_BUFFER, ADVANCE_BATCH, BDW_MOCS_WB, BEGIN_BATCH, gl_transform_feedback_object::Buffers, brw_context::ctx, gl_transform_feedback_state::CurrentObject, brw_context::gen, GEN8_SO_BUFFER_ENABLE, GEN8_SO_BUFFER_OFFSET_ADDRESS_ENABLE, GEN8_SO_BUFFER_OFFSET_WRITE_ENABLE, intel_buffer_object(), intel_bufferobj_buffer(), gl_transform_feedback_object::Offset, brw_transform_feedback_object::offset_bo, OUT_BATCH, OUT_RELOC64, gl_transform_feedback_object::Size, SKL_MOCS_WB, SO_BUFFER_INDEX_SHIFT, gl_context::TransformFeedback, and brw_transform_feedback_object::zero_offsets.
Referenced by upload_sol_state().