Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_draw_upload.c File Reference
#include "main/bufferobj.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/macros.h"
#include "brw_draw.h"
#include "brw_defines.h"
#include "brw_context.h"
#include "brw_state.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
Functions
static bool is_passthru_format (uint32_t format)
static void gen8_emit_vertices (struct brw_context *brw)
static void gen8_emit_index_buffer (struct brw_context *brw)
static void gen8_emit_vf_topology (struct brw_context *brw)
Variables
const struct brw_tracked_state gen8_vertices
const struct brw_tracked_state gen8_index_buffer
const struct brw_tracked_state gen8_vf_topology
Function Documentation
gen8_emit_index_buffer()
static void gen8_emit_index_buffer (struct brw_context * brw) static
References ADVANCE_BATCH, BDW_MOCS_WB, BEGIN_BATCH, brw_get_index_type(), CMD_INDEX_BUFFER, brw_context::gen, brw_context::ib, OUT_BATCH, OUT_RELOC64, SKL_MOCS_WB, and _mesa_index_buffer::type.
gen8_emit_vertices()
static void gen8_emit_vertices (struct brw_context * brw) static
References _3DSTATE_VERTEX_BUFFERS, _3DSTATE_VERTEX_ELEMENTS, _3DSTATE_VF_INSTANCING, _3DSTATE_VF_SGVS, ADVANCE_BATCH, gl_polygon_attrib::BackMode, brw_context::base, BEGIN_BATCH, brw_vertex_buffer::bo, brw_get_vertex_surface_type(), brw_prepare_shader_draw_parameters(), brw_prepare_vertices(), BRW_VE0_FORMAT_SHIFT, BRW_VE0_SRC_OFFSET_SHIFT, BRW_VE1_COMPONENT_0_SHIFT, BRW_VE1_COMPONENT_1_SHIFT, BRW_VE1_COMPONENT_2_SHIFT, BRW_VE1_COMPONENT_3_SHIFT, BRW_VE1_COMPONENT_NOSTORE, BRW_VE1_COMPONENT_STORE_0, BRW_VE1_COMPONENT_STORE_1_FLT, BRW_VE1_COMPONENT_STORE_1_INT, BRW_VE1_COMPONENT_STORE_SRC, brw_vertex_element::buffer, brw_context::buffers, brw_context::ctx, gl_vertex_array::Doubles, brw_context::draw, brw_context::draw_id_bo, brw_context::draw_id_offset, brw_context::draw_params_bo, brw_context::draw_params_offset, EMIT_VERTEX_BUFFER_STATE, brw_context::enabled, gl_polygon_attrib::FrontMode, GEN6_VE0_EDGE_FLAG_ENABLE, GEN6_VE0_INDEX_SHIFT, GEN6_VE0_VALID, GEN8_SGVS_ENABLE_INSTANCE_ID, GEN8_SGVS_ENABLE_VERTEX_ID, GEN8_SGVS_INSTANCE_ID_COMPONENT_SHIFT, GEN8_SGVS_INSTANCE_ID_ELEMENT_OFFSET_SHIFT, GEN8_SGVS_VERTEX_ID_COMPONENT_SHIFT, GEN8_SGVS_VERTEX_ID_ELEMENT_OFFSET_SHIFT, GEN8_VF_INSTANCING_ENABLE, brw_vertex_element::glarray, brw_context::inputs, gl_vertex_array::Integer, brw_vertex_element::is_dual_slot, is_passthru_format(), brw_context::nr_buffers, brw_context::nr_enabled, brw_vertex_buffer::offset, brw_vertex_element::offset, OUT_BATCH, gl_context::Polygon, brw_stage_state::prog_data, gl_vertex_array::Size, brw_vertex_buffer::size, brw_vertex_buffer::step_rate, brw_vertex_buffer::stride, brw_context::vb, and brw_context::vs.
gen8_emit_vf_topology()
static void gen8_emit_vf_topology (struct brw_context * brw) static
References _3DSTATE_VF_TOPOLOGY, ADVANCE_BATCH, BEGIN_BATCH, OUT_BATCH, and brw_context::primitive.
is_passthru_format()
static bool is_passthru_format (uint32_t format) static
Referenced by gen8_emit_vertices().
Variable Documentation
gen8_index_buffer
const struct brw_tracked_state gen8_index_buffer
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_INDEX_BUFFER,
   },
   .emit = gen8_emit_index_buffer,
}
gen8_vertices
const struct brw_tracked_state gen8_vertices
Initial value:
= {
   .dirty = {
      .mesa = _NEW_POLYGON,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_VERTICES |
             BRW_NEW_VS_PROG_DATA,
   },
   .emit = gen8_emit_vertices,
}
gen8_vf_topology
const struct brw_tracked_state gen8_vf_topology
Initial value:
= {
   .dirty = {
      .mesa = 0,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_PRIMITIVE,
   },
   .emit = gen8_emit_vf_topology,
}