Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_surface_state.c File Reference
#include "main/blend.h"
#include "main/mtypes.h"
#include "main/samplerobj.h"
#include "main/texformat.h"
#include "main/teximage.h"
#include "program/prog_parameter.h"
#include "program/prog_instruction.h"
#include "intel_mipmap_tree.h"
#include "intel_batchbuffer.h"
#include "intel_tex.h"
#include "intel_fbo.h"
#include "intel_buffer_objects.h"
#include "intel_image.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_wm.h"
#include "isl/isl.h"
Functions
static uint32_t * gen8_allocate_surface_state (struct brw_context *brw, uint32_t *out_offset)
static void gen8_emit_null_surface_state (struct brw_context *brw, unsigned width, unsigned height, unsigned samples, uint32_t *out_offset)
Creates a null surface.
void gen8_init_vtable_surface_functions (struct brw_context *brw)
Function Documentation
gen8_allocate_surface_state()
static uint32_t* gen8_allocate_surface_state (struct brw_context * brw, uint32_t * out_offset) static
References brw_state_batch().
Referenced by gen8_emit_null_surface_state().
gen8_emit_null_surface_state()
static void gen8_emit_null_surface_state (struct brw_context * brw, unsigned width, unsigned height, unsigned samples, uint32_t * out_offset) static
Creates a null surface.
This is used when the shader doesn't write to any color output. An FB write to target 0 will still be emitted, because that's how the thread is terminated (and computed depth is returned), so we need to have the hardware discard the target 0 color output..
References BRW_SURFACE_FORMAT_SHIFT, BRW_SURFACE_NULL, BRW_SURFACE_TYPE_SHIFT, gen8_allocate_surface_state(), GEN8_SURFACE_TILING_Y, and SET_FIELD.
Referenced by gen8_init_vtable_surface_functions().
gen8_init_vtable_surface_functions()
void gen8_init_vtable_surface_functions (struct brw_context * brw)
References brw_update_renderbuffer_surface(), brw_context::emit_null_surface_state, gen8_emit_null_surface_state(), brw_context::update_renderbuffer_surface, and brw_context::vtbl.
Referenced by brwCreateContext().