Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_blend_state.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "brw_wm.h"
#include "intel_batchbuffer.h"
#include "main/macros.h"
#include "main/enums.h"
#include "main/glformats.h"
Macros
#define blend_factor(x) brw_translate_blend_factor(x)
#define blend_eqn(x) brw_translate_blend_equation(x)
Functions
static void gen8_upload_blend_state (struct brw_context *brw)
static void gen8_upload_ps_blend (struct brw_context *brw)
Variables
const struct brw_tracked_state gen8_blend_state
const struct brw_tracked_state gen8_ps_blend
Macro Definition Documentation
blend_eqn
#define blend_eqn (x) brw_translate_blend_equation(x)
Referenced by gen8_upload_blend_state().
blend_factor
#define blend_factor (x) brw_translate_blend_factor(x)
Referenced by gen8_upload_blend_state(), and gen8_upload_ps_blend().
Function Documentation
gen8_upload_blend_state()
static void gen8_upload_blend_state (struct brw_context * brw) static
References _3DSTATE_BLEND_STATE_POINTERS, gl_colorbuffer_attrib::_AdvancedBlendMode, gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_IntegerBuffers, _mesa_base_format_has_channel(), _mesa_is_multisample_enabled(), gl_framebuffer::_NumColorDrawBuffers, gl_colorbuffer_attrib::_UsesDualSrc, ADVANCE_BATCH, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, BEGIN_BATCH, gl_colorbuffer_attrib::Blend, blend_eqn, blend_factor, brw_context::blend_state_offset, gl_colorbuffer_attrib::BlendEnabled, brw_fix_xRGB_alpha(), brw_state_batch(), brw_context::cc, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, brw_context::ctx, gl_colorbuffer_attrib::DitherFlag, gl_context::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GEN8_BLEND_ALPHA_TEST_ENABLE, GEN8_BLEND_ALPHA_TO_COVERAGE_DITHER_ENABLE, GEN8_BLEND_ALPHA_TO_COVERAGE_ENABLE, GEN8_BLEND_ALPHA_TO_ONE_ENABLE, GEN8_BLEND_COLOR_BUFFER_BLEND_ENABLE, GEN8_BLEND_COLOR_CLAMP_RANGE_RTFORMAT, GEN8_BLEND_COLOR_DITHER_ENABLE, GEN8_BLEND_INDEPENDENT_ALPHA_BLEND_ENABLE, GEN8_BLEND_LOGIC_OP_ENABLE, GEN8_BLEND_POST_BLEND_COLOR_CLAMP_ENABLE, GEN8_BLEND_PRE_BLEND_COLOR_CLAMP_ENABLE, GEN8_BLEND_WRITE_DISABLE_ALPHA, GEN8_BLEND_WRITE_DISABLE_BLUE, GEN8_BLEND_WRITE_DISABLE_GREEN, GEN8_BLEND_WRITE_DISABLE_RED, intel_translate_compare_func(), intel_translate_logic_op(), gl_colorbuffer_attrib::LogicOp, gl_context::Multisample, OUT_BATCH, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, SET_FIELD, gl_colorbuffer_attrib::SrcA, and gl_colorbuffer_attrib::SrcRGB.
gen8_upload_ps_blend()
static void gen8_upload_ps_blend (struct brw_context * brw) static
References _3DSTATE_PS_BLEND, gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_IntegerBuffers, _mesa_base_format_has_channel(), _mesa_is_multisample_enabled(), ADVANCE_BATCH, gl_colorbuffer_attrib::AlphaEnabled, BEGIN_BATCH, gl_colorbuffer_attrib::Blend, blend_factor, gl_colorbuffer_attrib::BlendEnabled, brw_color_buffer_write_enabled(), brw_fix_xRGB_alpha(), gl_context::Color, brw_context::ctx, gl_context::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GEN8_PS_BLEND_ALPHA_TEST_ENABLE, GEN8_PS_BLEND_ALPHA_TO_COVERAGE_ENABLE, GEN8_PS_BLEND_COLOR_BUFFER_BLEND_ENABLE, GEN8_PS_BLEND_HAS_WRITEABLE_RT, GEN8_PS_BLEND_INDEPENDENT_ALPHA_BLEND_ENABLE, gl_context::Multisample, OUT_BATCH, gl_multisample_attrib::SampleAlphaToCoverage, SET_FIELD, gl_colorbuffer_attrib::SrcA, and gl_colorbuffer_attrib::SrcRGB.
Variable Documentation
gen8_blend_state
const struct brw_tracked_state gen8_blend_state
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR |
              _NEW_MULTISAMPLE,
      .brw = BRW_NEW_BATCH |
             BRW_NEW_BLORP |
             BRW_NEW_STATE_BASE_ADDRESS,
   },
   .emit = gen8_upload_blend_state,
}
gen8_ps_blend
const struct brw_tracked_state gen8_ps_blend
Initial value:
= {
   .dirty = {
      .mesa = _NEW_BUFFERS |
              _NEW_COLOR |
              _NEW_MULTISAMPLE,
      .brw = BRW_NEW_BLORP |
             BRW_NEW_CONTEXT |
             BRW_NEW_FRAGMENT_PROGRAM,
   },
   .emit = gen8_upload_ps_blend
}