Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_sf_state.c File Reference
#include "compiler/nir/nir.h"
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_util.h"
#include "main/macros.h"
#include "main/fbobject.h"
#include "intel_batchbuffer.h"
Functions
static void upload_sbe (struct brw_context *brw)
static void upload_sf (struct brw_context *brw)
static void upload_raster (struct brw_context *brw)
Variables
const struct brw_tracked_state gen8_sbe_state
const struct brw_tracked_state gen8_sf_state
const struct brw_tracked_state gen8_raster_state
Function Documentation
upload_raster()
static void upload_raster (struct brw_context * brw) static
References _3DSTATE_RASTER, gl_polygon_attrib::_FrontBit, _mesa_is_multisample_enabled(), ADVANCE_BATCH, gl_polygon_attrib::BackMode, BEGIN_BATCH, brw_context::ctx, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_transform_attrib::DepthClamp, gl_context::DrawBuffer, gl_scissor_attrib::EnableFlags, gl_polygon_attrib::FrontMode, brw_context::gen, GEN6_SF_BACK_POINT, GEN6_SF_BACK_SOLID, GEN6_SF_BACK_WIREFRAME, GEN6_SF_FRONT_POINT, GEN6_SF_FRONT_SOLID, GEN6_SF_FRONT_WIREFRAME, GEN6_SF_GLOBAL_DEPTH_OFFSET_POINT, GEN6_SF_GLOBAL_DEPTH_OFFSET_SOLID, GEN6_SF_GLOBAL_DEPTH_OFFSET_WIREFRAME, GEN8_RASTER_API_MULTISAMPLE_ENABLE, GEN8_RASTER_CULL_BACK, GEN8_RASTER_CULL_BOTH, GEN8_RASTER_CULL_FRONT, GEN8_RASTER_CULL_NONE, GEN8_RASTER_FRONT_WINDING_CCW, GEN8_RASTER_LINE_AA_ENABLE, GEN8_RASTER_SCISSOR_ENABLE, GEN8_RASTER_SMOOTH_POINT_ENABLE, GEN8_RASTER_VIEWPORT_Z_CLIP_TEST_ENABLE, GEN9_RASTER_CONSERVATIVE_RASTERIZATION_ENABLE, GEN9_RASTER_VIEWPORT_Z_FAR_CLIP_TEST_ENABLE, GEN9_RASTER_VIEWPORT_Z_NEAR_CLIP_TEST_ENABLE, gl_context::IntelConservativeRasterization, gl_context::Line, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, OUT_BATCH, OUT_BATCH_F, gl_context::Point, gl_context::Polygon, gl_context::Scissor, gl_line_attrib::SmoothFlag, gl_point_attrib::SmoothFlag, and gl_context::Transform.
upload_sbe()
static void upload_sbe (struct brw_context * brw) static
References _3DSTATE_SBE, _3DSTATE_SBE_SWIZ, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, BITFIELD64_BIT, calculate_attr_overrides(), brw_context::ctx, gl_context::DrawBuffer, brw_context::fragment_program, brw_context::gen, GEN6_SF_POINT_SPRITE_LOWERLEFT, GEN6_SF_POINT_SPRITE_UPPERLEFT, GEN7_SBE_NUM_OUTPUTS_SHIFT, GEN7_SBE_SWIZZLE_ENABLE, GEN7_SBE_URB_ENTRY_READ_LENGTH_SHIFT, GEN8_SBE_FORCE_URB_ENTRY_READ_LENGTH, GEN8_SBE_FORCE_URB_ENTRY_READ_OFFSET, GEN8_SBE_URB_ENTRY_READ_OFFSET_SHIFT, GEN9_SBE_ACTIVE_COMPONENT_XYZW, gl_program::info, OUT_BATCH, gl_context::Point, brw_stage_state::prog_data, gl_point_attrib::SpriteOrigin, and brw_context::wm.
upload_sf()
static void upload_sf (struct brw_context * brw) static
References _3DSTATE_SF, _mesa_is_multisample_enabled(), ADVANCE_BATCH, BEGIN_BATCH, brw_get_line_width(), brw_context::ctx, brw_context::gen, GEN6_SF_LINE_AA_MODE_TRUE, GEN6_SF_LINE_END_CAP_WIDTH_1_0, GEN6_SF_LINE_PROVOKE_SHIFT, GEN6_SF_LINE_WIDTH_SHIFT, GEN6_SF_STATISTICS_ENABLE, GEN6_SF_TRI_PROVOKE_SHIFT, GEN6_SF_TRIFAN_PROVOKE_SHIFT, GEN6_SF_USE_STATE_POINT_WIDTH, GEN6_SF_VIEWPORT_TRANSFORM_ENABLE, GEN8_SF_SMOOTH_POINT_ENABLE, GEN9_SF_LINE_WIDTH_SHIFT, brw_context::is_cherryview, gl_context::Light, gl_context::Line, gl_point_attrib::MaxSize, gl_point_attrib::MinSize, OUT_BATCH, gl_context::Point, gl_point_attrib::PointSprite, gl_light_attrib::ProvokingVertex, brw_context::sf, gl_point_attrib::Size, gl_line_attrib::SmoothFlag, gl_point_attrib::SmoothFlag, use_state_point_size(), and brw_context::viewport_transform_enable.
Variable Documentation
gen8_raster_state
const struct brw_tracked_state gen8_raster_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LINE |
               _NEW_MULTISAMPLE |
               _NEW_POINT |
               _NEW_POLYGON |
               _NEW_SCISSOR |
               _NEW_TRANSFORM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_CONSERVATIVE_RASTERIZATION,
   },
   .emit = upload_raster,
}
gen8_sbe_state
const struct brw_tracked_state gen8_sbe_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS |
               _NEW_LIGHT |
               _NEW_POINT |
               _NEW_POLYGON |
               _NEW_PROGRAM,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FRAGMENT_PROGRAM |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_GS_PROG_DATA |
               BRW_NEW_TES_PROG_DATA |
               BRW_NEW_VUE_MAP_GEOM_OUT,
   },
   .emit = upload_sbe,
}
gen8_sf_state
const struct brw_tracked_state gen8_sf_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_LIGHT |
               _NEW_PROGRAM |
               _NEW_LINE |
               _NEW_MULTISAMPLE |
               _NEW_POINT,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_VUE_MAP_GEOM_OUT,
   },
   .emit = upload_sf,
}