Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gen8_ps_state.c File Reference
#include <stdbool.h>
#include "program/program.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "brw_wm.h"
#include "intel_batchbuffer.h"
Functions
void gen8_upload_ps_extra (struct brw_context *brw, const struct brw_wm_prog_data *prog_data)
static void upload_ps_extra (struct brw_context *brw)
static void upload_wm_state (struct brw_context *brw)
void gen8_upload_ps_state (struct brw_context *brw, const struct brw_stage_state *stage_state, const struct brw_wm_prog_data *prog_data, uint32_t fast_clear_op)
static void upload_ps_state (struct brw_context *brw)
Variables
const struct brw_tracked_state gen8_ps_extra
const struct brw_tracked_state gen8_wm_state
const struct brw_tracked_state gen8_ps_state
Function Documentation
gen8_upload_ps_extra()
void gen8_upload_ps_extra (struct brw_context * brw, const struct brw_wm_prog_data * prog_data)
References _3DSTATE_PS_EXTRA, ADVANCE_BATCH, BEGIN_BATCH, brw_color_buffer_write_enabled(), BRW_PCICMS_DEPTH, BRW_PSICMS_INNER, BRW_PSICMS_NORMAL, brw_context::ctx, brw_context::gen, GEN8_PSX_ATTRIBUTE_ENABLE, GEN8_PSX_COMPUTED_DEPTH_MODE_SHIFT, GEN8_PSX_KILL_ENABLE, GEN8_PSX_OMASK_TO_RENDER_TARGET, GEN8_PSX_PIXEL_SHADER_VALID, GEN8_PSX_SHADER_HAS_UAV, GEN8_PSX_SHADER_IS_PER_SAMPLE, GEN8_PSX_SHADER_USES_INPUT_COVERAGE_MASK, GEN8_PSX_USES_SOURCE_DEPTH, GEN8_PSX_USES_SOURCE_W, GEN9_PSX_SHADER_COMPUTES_STENCIL, GEN9_PSX_SHADER_NORMAL_COVERAGE_MASK_SHIFT, GEN9_PSX_SHADER_PULLS_BARY, gl_context::IntelConservativeRasterization, and OUT_BATCH.
Referenced by upload_ps_extra().
gen8_upload_ps_state()
void gen8_upload_ps_state (struct brw_context * brw, const struct brw_stage_state * stage_state, const struct brw_wm_prog_data * prog_data, uint32_t fast_clear_op)
References _3DSTATE_PS, ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, GEN7_PS_16_DISPATCH_ENABLE, GEN7_PS_8_DISPATCH_ENABLE, GEN7_PS_BINDING_TABLE_ENTRY_COUNT_SHIFT, GEN7_PS_DISPATCH_START_GRF_SHIFT_0, GEN7_PS_DISPATCH_START_GRF_SHIFT_2, GEN7_PS_FLOATING_POINT_MODE_ALT, GEN7_PS_POSOFFSET_NONE, GEN7_PS_POSOFFSET_SAMPLE, GEN7_PS_PUSH_CONSTANT_ENABLE, GEN7_PS_VECTOR_MASK_ENABLE, HSW_PS_MAX_THREADS_SHIFT, OUT_BATCH, OUT_RELOC64, brw_stage_state::per_thread_scratch, brw_stage_state::prog_offset, brw_stage_state::sampler_count, brw_stage_state::scratch_bo, and SET_FIELD.
Referenced by upload_ps_state().
upload_ps_extra()
static void upload_ps_extra (struct brw_context * brw) static
References brw_context::base, gen8_upload_ps_extra(), brw_stage_state::prog_data, and brw_context::wm.
upload_ps_state()
static void upload_ps_state (struct brw_context * brw) static
References brw_context::base, brw_context::fast_clear_op, gen8_upload_ps_state(), brw_stage_state::prog_data, and brw_context::wm.
upload_wm_state()
static void upload_wm_state (struct brw_context * brw) static
References _3DSTATE_WM, ADVANCE_BATCH, brw_context::base, BEGIN_BATCH, brw_context::ctx, GEN7_WM_BARYCENTRIC_INTERPOLATION_MODE_SHIFT, GEN7_WM_EARLY_DS_CONTROL_PREPS, GEN7_WM_EARLY_DS_CONTROL_PSEXEC, GEN7_WM_LINE_AA_WIDTH_1_0, GEN7_WM_LINE_END_CAP_AA_WIDTH_0_5, GEN7_WM_LINE_STIPPLE_ENABLE, GEN7_WM_POINT_RASTRULE_UPPER_RIGHT, GEN7_WM_POLYGON_STIPPLE_ENABLE, GEN7_WM_STATISTICS_ENABLE, gl_context::Line, OUT_BATCH, gl_context::Polygon, brw_stage_state::prog_data, gl_line_attrib::StippleFlag, gl_polygon_attrib::StippleFlag, and brw_context::wm.
Variable Documentation
gen8_ps_extra
const struct brw_tracked_state gen8_ps_extra
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_BUFFERS | _NEW_COLOR,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FRAGMENT_PROGRAM |
               BRW_NEW_FS_PROG_DATA |
               BRW_NEW_CONSERVATIVE_RASTERIZATION,
   },
   .emit = upload_ps_extra,
}
gen8_ps_state
const struct brw_tracked_state gen8_ps_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_MULTISAMPLE,
      .brw   = BRW_NEW_BATCH |
               BRW_NEW_BLORP |
               BRW_NEW_FS_PROG_DATA,
   },
   .emit = upload_ps_state,
}
gen8_wm_state
const struct brw_tracked_state gen8_wm_state
Initial value:
= {
   .dirty = {
      .mesa  = _NEW_LINE |
               _NEW_POLYGON,
      .brw   = BRW_NEW_BLORP |
               BRW_NEW_CONTEXT |
               BRW_NEW_FS_PROG_DATA,
   },
   .emit = upload_wm_state,
}