Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
genX_blorp_exec.c File Reference
#include <assert.h>
#include "intel_batchbuffer.h"
#include "intel_mipmap_tree.h"
#include "intel_fbo.h"
#include "brw_context.h"
#include "brw_state.h"
#include "blorp/blorp_genX_exec.h"
#include "brw_blorp.h"
Functions
static void * blorp_emit_dwords (struct blorp_batch *batch, unsigned n)
static uint64_t blorp_emit_reloc (struct blorp_batch *batch, void *location, struct blorp_address address, uint32_t delta)
static void blorp_surface_reloc (struct blorp_batch *batch, uint32_t ss_offset, struct blorp_address address, uint32_t delta)
static void * blorp_alloc_dynamic_state (struct blorp_batch *batch, uint32_t size, uint32_t alignment, uint32_t *offset)
static void blorp_alloc_binding_table (struct blorp_batch *batch, unsigned num_entries, unsigned state_size, unsigned state_alignment, uint32_t *bt_offset, uint32_t *surface_offsets, void **surface_maps)
static void * blorp_alloc_vertex_buffer (struct blorp_batch *batch, uint32_t size, struct blorp_address *addr)
static void blorp_flush_range (struct blorp_batch *batch, void *start, size_t size)
static void blorp_emit_urb_config (struct blorp_batch *batch, unsigned vs_entry_size)
void genX() blorp_exec (struct blorp_batch *batch, const struct blorp_params *params)
Function Documentation
blorp_alloc_binding_table()
static void blorp_alloc_binding_table (struct blorp_batch * batch, unsigned num_entries, unsigned state_size, unsigned state_alignment, uint32_t * bt_offset, uint32_t * surface_offsets, void ** surface_maps) static
References brw_state_batch(), and brw_context::num_entries.
blorp_alloc_dynamic_state()
static void* blorp_alloc_dynamic_state (struct blorp_batch * batch, uint32_t size, uint32_t alignment, uint32_t * offset) static
References brw_state_batch().
blorp_alloc_vertex_buffer()
static void* blorp_alloc_vertex_buffer (struct blorp_batch * batch, uint32_t size, struct blorp_address * addr) static
References brw_context::batch, intel_batchbuffer::bo, and brw_state_batch().
blorp_emit_dwords()
static void* blorp_emit_dwords (struct blorp_batch * batch, unsigned n) static
References brw_context::batch, intel_batchbuffer_advance(), intel_batchbuffer_begin(), intel_batchbuffer::map_next, and RENDER_RING.
blorp_emit_reloc()
static uint64_t blorp_emit_reloc (struct blorp_batch * batch, void * location, struct blorp_address address, uint32_t delta) static
References brw_context::batch, intel_batchbuffer_reloc(), and intel_batchbuffer::map.
blorp_emit_urb_config()
static void blorp_emit_urb_config (struct blorp_batch * batch, unsigned vs_entry_size) static
References BRW_NEW_CONTEXT, BRW_NEW_URB_SIZE, brw_context::ctx, gen6_upload_urb(), gen7_upload_urb(), gl_context::NewDriverState, brw_context::urb, and brw_context::vsize.
blorp_exec()
void genX() blorp_exec (struct blorp_batch * batch, const struct blorp_params * params)
References brw_context::always_flush_batch, brw_context::batch, intel_batchbuffer::bo, brw_emit_depth_stall_flushes(), brw_emit_post_sync_nonzero_flush(), BRW_NEW_BLORP, brw_render_cache_set_add_bo(), brw_render_cache_set_check_flush(), BRW_RENDER_PIPELINE, brw_select_pipeline(), brw_upload_state_base_address(), brw_context::ctx, brw_tracked_state::emit, gen7_l3_state, gen8_write_pma_stall_bits(), brw_context::ib, intel_batchbuffer_flush, intel_batchbuffer_require_space(), intel_batchbuffer_reset_to_saved(), intel_batchbuffer_save_state(), gl_context::NewDriverState, brw_context::no_depth_or_stencil, RENDER_RING, ret(), intel_batchbuffer::state_batch_offset, _mesa_index_buffer::type, USED_BATCH, and void.
blorp_flush_range()
static void blorp_flush_range (struct blorp_batch * batch, void * start, size_t size) static
blorp_surface_reloc()
static void blorp_surface_reloc (struct blorp_batch * batch, uint32_t ss_offset, struct blorp_address address, uint32_t delta) static
References brw_context::batch, intel_batchbuffer::bo, brw_context::bo, and intel_batchbuffer::map.