Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
hsw_queryobj.c File Reference
Support for query buffer objects (GL_ARB_query_buffer_object) on Haswell+.
#include "main/imports.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
Functions
static void mult_gpr0_by_80 (struct brw_context *brw)
static void keep_gpr0_lower_n_bits (struct brw_context *brw, uint32_t n)
static void shl_gpr0_by_30_bits (struct brw_context *brw)
static void shr_gpr0_by_2_bits (struct brw_context *brw)
static void gpr0_to_bool (struct brw_context *brw)
static void load_overflow_data_to_cs_gprs (struct brw_context *brw, struct brw_query_object *query, int idx)
static void calc_overflow_for_stream (struct brw_context *brw)
static void calc_overflow_to_gpr0 (struct brw_context *brw, struct brw_query_object *query, int count)
void hsw_overflow_result_to_gpr0 (struct brw_context *brw, struct brw_query_object *query, int count)
hsw_queryobj.c
static void hsw_result_to_gpr0 (struct gl_context *ctx, struct brw_query_object *query, struct gl_buffer_object *buf, intptr_t offset, GLenum pname, GLenum ptype)
static void store_query_result_imm (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, GLenum ptype, uint64_t imm)
static void set_predicate (struct brw_context *brw, drm_intel_bo *query_bo)
static void store_query_result_reg (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, GLenum ptype, uint32_t reg, const bool pipelined)
static void hsw_store_query_result (struct gl_context *ctx, struct gl_query_object *q, struct gl_buffer_object *buf, intptr_t offset, GLenum pname, GLenum ptype)
void hsw_init_queryobj_functions (struct dd_function_table *functions)
Detailed Description
Support for query buffer objects (GL_ARB_query_buffer_object) on Haswell+.
Function Documentation
calc_overflow_for_stream()
static void calc_overflow_for_stream (struct brw_context * brw) static
References ADVANCE_BATCH, BEGIN_BATCH, HSW_MI_MATH, MI_MATH_ALU0, MI_MATH_ALU2, and OUT_BATCH.
Referenced by calc_overflow_to_gpr0().
calc_overflow_to_gpr0()
static void calc_overflow_to_gpr0 (struct brw_context * brw, struct brw_query_object * query, int count) static
References brw_load_register_imm64(), calc_overflow_for_stream(), HSW_CS_GPR, and load_overflow_data_to_cs_gprs().
Referenced by hsw_overflow_result_to_gpr0().
gpr0_to_bool()
static void gpr0_to_bool (struct brw_context * brw) static
References ADVANCE_BATCH, BEGIN_BATCH, brw_load_register_imm64(), HSW_CS_GPR, HSW_MI_MATH, MI_MATH_ALU0, MI_MATH_ALU1, MI_MATH_ALU2, and OUT_BATCH.
Referenced by hsw_overflow_result_to_gpr0(), and hsw_result_to_gpr0().
hsw_init_queryobj_functions()
void hsw_init_queryobj_functions (struct dd_function_table * functions)
References gen6_init_queryobj_functions(), hsw_store_query_result(), and dd_function_table::StoreQueryResult.
Referenced by brw_init_driver_functions().
hsw_overflow_result_to_gpr0()
void hsw_overflow_result_to_gpr0 (struct brw_context * brw, struct brw_query_object * query, int count)
hsw_queryobj.c
References calc_overflow_to_gpr0(), and gpr0_to_bool().
Referenced by hsw_result_to_gpr0(), and set_predicate_for_overflow_query().
hsw_result_to_gpr0()
static void hsw_result_to_gpr0 (struct gl_context * ctx, struct brw_query_object * query, struct gl_buffer_object * buf, intptr_t offset, GLenum pname, GLenum ptype) static
References ADVANCE_BATCH, brw_query_object::Base, BEGIN_BATCH, brw_query_object::bo, brw_context(), brw_emit_pipe_control_flush(), brw_load_register_mem64(), brw_context::gen, gpr0_to_bool(), HSW_CS_GPR, HSW_MI_MATH, hsw_overflow_result_to_gpr0(), brw_context::is_haswell, keep_gpr0_lower_n_bits(), MAX_VERTEX_STREAMS, MI_MATH_ALU0, MI_MATH_ALU2, mult_gpr0_by_80(), OUT_BATCH, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_STALL_AT_SCOREBOARD, shr_gpr0_by_2_bits(), and gl_query_object::Target.
Referenced by hsw_store_query_result().
hsw_store_query_result()
static void hsw_store_query_result (struct gl_context * ctx, struct gl_query_object * q, struct gl_buffer_object * buf, intptr_t offset, GLenum pname, GLenum ptype) static
References brw_query_object::Base, brw_query_object::bo, brw_context(), brw_is_query_pipelined(), intel_buffer_object::buffer, HSW_CS_GPR, hsw_result_to_gpr0(), intel_buffer_object(), gl_query_object::Result, set_predicate(), store_query_result_imm(), store_query_result_reg(), and gl_query_object::Target.
Referenced by hsw_init_queryobj_functions().
keep_gpr0_lower_n_bits()
static void keep_gpr0_lower_n_bits (struct brw_context * brw, uint32_t n) static
References ADVANCE_BATCH, BEGIN_BATCH, brw_load_register_imm64(), HSW_CS_GPR, HSW_MI_MATH, MI_MATH_ALU0, MI_MATH_ALU2, and OUT_BATCH.
Referenced by hsw_result_to_gpr0(), and shl_gpr0_by_30_bits().
load_overflow_data_to_cs_gprs()
static void load_overflow_data_to_cs_gprs (struct brw_context * brw, struct brw_query_object * query, int idx) static
References brw_query_object::bo, brw_load_register_mem64(), and HSW_CS_GPR.
Referenced by calc_overflow_to_gpr0().
mult_gpr0_by_80()
static void mult_gpr0_by_80 (struct brw_context * brw) static
References ADVANCE_BATCH, BEGIN_BATCH, HSW_MI_MATH, MI_MATH_ALU0, MI_MATH_ALU2, and OUT_BATCH.
Referenced by hsw_result_to_gpr0().
set_predicate()
static void set_predicate (struct brw_context * brw, drm_intel_bo * query_bo) static
References ADVANCE_BATCH, BEGIN_BATCH, brw_load_register_imm64(), brw_load_register_mem64(), GEN7_MI_PREDICATE, MI_PREDICATE_COMBINEOP_SET, MI_PREDICATE_COMPAREOP_SRCS_EQUAL, MI_PREDICATE_LOADOP_LOADINV, MI_PREDICATE_SRC0, MI_PREDICATE_SRC1, and OUT_BATCH.
Referenced by hsw_store_query_result().
shl_gpr0_by_30_bits()
static void shl_gpr0_by_30_bits (struct brw_context * brw) static
References ADVANCE_BATCH, BEGIN_BATCH, HSW_MI_MATH, keep_gpr0_lower_n_bits(), MI_MATH_ALU0, MI_MATH_ALU2, o, and OUT_BATCH.
Referenced by shr_gpr0_by_2_bits().
shr_gpr0_by_2_bits()
static void shr_gpr0_by_2_bits (struct brw_context * brw) static
References brw_load_register_imm32(), brw_load_register_reg(), HSW_CS_GPR, and shl_gpr0_by_30_bits().
Referenced by hsw_result_to_gpr0().
store_query_result_imm()
static void store_query_result_imm (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, GLenum ptype, uint64_t imm) static
References brw_store_data_imm32(), and brw_store_data_imm64().
Referenced by hsw_store_query_result().
store_query_result_reg()
static void store_query_result_reg (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, GLenum ptype, uint32_t reg, const bool pipelined) static
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_REGISTER_MEM, MI_STORE_REGISTER_MEM_PREDICATE, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by hsw_store_query_result().