Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
hsw_sol.c File Reference
#include "brw_context.h"
#include "brw_state.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "main/transformfeedback.h"
Macros
#define TALLY_OFFSET (BRW_MAX_XFB_STREAMS * sizeof(uint32_t))
An implementation of the transform feedback driver hooks for Haswell and later hardware.
#define START_OFFSET (TALLY_OFFSET * 2)
Functions
static void save_prim_start_values (struct brw_context *brw, struct brw_transform_feedback_object *obj)
Store the SO_NUM_PRIMS_WRITTEN counters for each stream (4 uint64_t values) to prim_count_bo.
static void tally_prims_written (struct brw_context *brw, struct brw_transform_feedback_object *obj, bool finalize)
Compute the number of primitives written during our most recent transform feedback activity (the current SO_NUM_PRIMS_WRITTEN value minus the stashed "start" value), and add it to our running tally.
void hsw_begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
BeginTransformFeedback() driver hook.
void hsw_pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
PauseTransformFeedback() driver hook.
void hsw_resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
ResumeTransformFeedback() driver hook.
void hsw_end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
EndTransformFeedback() driver hook.
Macro Definition Documentation
START_OFFSET
#define START_OFFSET (TALLY_OFFSET * 2)
Referenced by save_prim_start_values(), and tally_prims_written().
TALLY_OFFSET
#define TALLY_OFFSET (BRW_MAX_XFB_STREAMS * sizeof(uint32_t))
An implementation of the transform feedback driver hooks for Haswell and later hardware.
This uses MI_MATH to compute the number of vertices written (for use by DrawTransformFeedback()) without any CPU<->GPU synchronization which could stall. We store several values in obj->prim_count_bo:
[4x 32-bit values]: Final Number of Vertices Written [4x 32-bit values]: Tally of Primitives Written So Far [4x 64-bit values]: Starting SO_NUM_PRIMS_WRITTEN Counter Snapshots
The first set of values is used by DrawTransformFeedback(), which copies one of them into the 3DPRIM_VERTEX_COUNT register and performs an indirect draw. The other values are just temporary storage.
Referenced by hsw_begin_transform_feedback(), and tally_prims_written().
Function Documentation
hsw_begin_transform_feedback()
void hsw_begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj)
BeginTransformFeedback() driver hook.
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), BRW_MAX_XFB_STREAMS, brw_store_data_imm64(), brw_context::gen, GEN7_SO_WRITE_OFFSET, MI_LOAD_REGISTER_IMM, OUT_BATCH, brw_transform_feedback_object::prim_count_bo, brw_transform_feedback_object::primitive_mode, save_prim_start_values(), TALLY_OFFSET, and brw_transform_feedback_object::zero_offsets.
Referenced by brw_get_index_type(), and brw_init_driver_functions().
hsw_end_transform_feedback()
void hsw_end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
EndTransformFeedback() driver hook.
References brw_context(), and tally_prims_written().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
hsw_pause_transform_feedback()
void hsw_pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
PauseTransformFeedback() driver hook.
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), brw_emit_mi_flush(), BRW_MAX_XFB_STREAMS, GEN7_SO_WRITE_OFFSET, brw_context::is_haswell, MI_STORE_REGISTER_MEM, brw_transform_feedback_object::offset_bo, OUT_BATCH, OUT_RELOC, and tally_prims_written().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
hsw_resume_transform_feedback()
void hsw_resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj)
ResumeTransformFeedback() driver hook.
References ADVANCE_BATCH, BEGIN_BATCH, brw_context(), BRW_MAX_XFB_STREAMS, GEN7_MI_LOAD_REGISTER_MEM, GEN7_SO_WRITE_OFFSET, brw_context::is_haswell, brw_transform_feedback_object::offset_bo, OUT_BATCH, OUT_RELOC, and save_prim_start_values().
Referenced by brw_get_index_type(), and brw_init_driver_functions().
save_prim_start_values()
static void save_prim_start_values (struct brw_context * brw, struct brw_transform_feedback_object * obj) static
Store the SO_NUM_PRIMS_WRITTEN counters for each stream (4 uint64_t values) to prim_count_bo.
References brw_emit_mi_flush(), BRW_MAX_XFB_STREAMS, brw_store_register_mem64(), GEN7_SO_NUM_PRIMS_WRITTEN, brw_transform_feedback_object::prim_count_bo, and START_OFFSET.
Referenced by hsw_begin_transform_feedback(), and hsw_resume_transform_feedback().
tally_prims_written()
static void tally_prims_written (struct brw_context * brw, struct brw_transform_feedback_object * obj, bool finalize) static
Compute the number of primitives written during our most recent transform feedback activity (the current SO_NUM_PRIMS_WRITTEN value minus the stashed "start" value), and add it to our running tally.
If finalize is true, also compute the number of vertices written (by multiplying by the number of vertices per primitive), and store that to the "final" location.
Otherwise, just overwrite the old tally with the new one.
References ADVANCE_BATCH, brw_transform_feedback_object::base, BEGIN_BATCH, brw_emit_mi_flush(), brw_load_register_imm32(), brw_load_register_mem(), brw_load_register_mem64(), brw_load_register_reg64(), BRW_MAX_XFB_STREAMS, brw_store_register_mem32(), GEN7_SO_NUM_PRIMS_WRITTEN, HSW_CS_GPR, HSW_MI_MATH, MI_MATH_ALU0, MI_MATH_ALU2, OUT_BATCH, gl_transform_feedback_object::Paused, brw_transform_feedback_object::prim_count_bo, brw_transform_feedback_object::primitive_mode, START_OFFSET, and TALLY_OFFSET.
Referenced by hsw_end_transform_feedback(), and hsw_pause_transform_feedback().