Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_mipmap_tree.c File Reference
#include <GL/gl.h>
#include <GL/internal/dri_interface.h>
#include "intel_batchbuffer.h"
#include "intel_mipmap_tree.h"
#include "intel_resolve_map.h"
#include "intel_tex.h"
#include "intel_blit.h"
#include "intel_fbo.h"
#include "brw_blorp.h"
#include "brw_context.h"
#include "brw_state.h"
#include "main/enums.h"
#include "main/fbobject.h"
#include "main/formats.h"
#include "main/glformats.h"
#include "main/texcompress_etc.h"
#include "main/teximage.h"
#include "main/streaming-load-memcpy.h"
#include "x86/common_x86_asm.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_MIPTREE
Functions
static void * intel_miptree_map_raw (struct brw_context *brw, struct intel_mipmap_tree *mt)
static void intel_miptree_unmap_raw (struct intel_mipmap_tree *mt)
static bool intel_miptree_alloc_mcs (struct brw_context *brw, struct intel_mipmap_tree *mt, GLuint num_samples)
static enum intel_msaa_layout compute_msaa_layout (struct brw_context *brw, mesa_format format, enum intel_aux_disable aux_disable)
Determine which MSAA layout should be used by the MSAA surface being created, based on the chip generation and the surface type.
bool intel_tiling_supports_non_msrt_mcs (const struct brw_context *brw, unsigned tiling)
bool intel_miptree_supports_non_msrt_fast_clear (struct brw_context *brw, const struct intel_mipmap_tree *mt)
For a single-sampled render target ("non-MSRT"), determine if an MCS buffer can be used.
bool intel_miptree_is_lossless_compressed (const struct brw_context *brw, const struct intel_mipmap_tree *mt)
bool intel_miptree_supports_lossless_compressed (struct brw_context *brw, const struct intel_mipmap_tree *mt)
mesa_format intel_depth_format_for_depthstencil_format (mesa_format format)
Determine depth format corresponding to a depth+stencil format, for separate stencil.
static struct intel_mipmap_tree * intel_miptree_create_layout (struct brw_context *brw, GLenum target, mesa_format format, GLuint first_level, GLuint last_level, GLuint width0, GLuint height0, GLuint depth0, GLuint num_samples, uint32_t layout_flags)
mesa_format intel_lower_compressed_format (struct brw_context *brw, mesa_format format)
Choose an appropriate uncompressed format for a requested compressed format, if unsupported.
static struct intel_mipmap_tree * miptree_create (struct brw_context *brw, GLenum target, mesa_format format, GLuint first_level, GLuint last_level, GLuint width0, GLuint height0, GLuint depth0, GLuint num_samples, uint32_t layout_flags)
struct intel_mipmap_tree * intel_miptree_create (struct brw_context *brw, GLenum target, mesa_format format, GLuint first_level, GLuint last_level, GLuint width0, GLuint height0, GLuint depth0, GLuint num_samples, uint32_t layout_flags)
struct intel_mipmap_tree * intel_miptree_create_for_bo (struct brw_context *brw, drm_intel_bo *bo, mesa_format format, uint32_t offset, uint32_t width, uint32_t height, uint32_t depth, int pitch, uint32_t layout_flags)
void intel_update_winsys_renderbuffer_miptree (struct brw_context *intel, struct intel_renderbuffer *irb, drm_intel_bo *bo, uint32_t width, uint32_t height, uint32_t pitch)
For a singlesample renderbuffer, this simply wraps the given BO with a miptree.
struct intel_mipmap_tree * intel_miptree_create_for_renderbuffer (struct brw_context *brw, mesa_format format, uint32_t width, uint32_t height, uint32_t num_samples)
void intel_miptree_reference (struct intel_mipmap_tree **dst, struct intel_mipmap_tree *src)
static void intel_miptree_hiz_buffer_free (struct intel_miptree_hiz_buffer *hiz_buf)
void intel_miptree_release (struct intel_mipmap_tree **mt)
void intel_get_image_dims (struct gl_texture_image *image, int *width, int *height, int *depth)
bool intel_miptree_match_image (struct intel_mipmap_tree *mt, struct gl_texture_image *image)
Can the image be pulled into a unified mipmap tree? This mirrors the completeness test in a lot of ways.
void intel_miptree_set_level_info (struct intel_mipmap_tree *mt, GLuint level, GLuint x, GLuint y, GLuint d)
void intel_miptree_set_image_offset (struct intel_mipmap_tree *mt, GLuint level, GLuint img, GLuint x, GLuint y)
void intel_miptree_get_image_offset (const struct intel_mipmap_tree *mt, GLuint level, GLuint slice, GLuint *x, GLuint *y)
void intel_get_tile_dims (uint32_t tiling, uint32_t cpp, uint32_t *tile_w, uint32_t *tile_h)
This function computes the tile_w (in bytes) and tile_h (in rows) of different tiling patterns.
void intel_get_tile_masks (uint32_t tiling, uint32_t cpp, uint32_t *mask_x, uint32_t *mask_y)
This function computes masks that may be used to select the bits of the X and Y coordinates that indicate the offset within a tile.
uint32_t intel_miptree_get_aligned_offset (const struct intel_mipmap_tree *mt, uint32_t x, uint32_t y)
Compute the offset (in bytes) from the start of the BO to the given x and y coordinate.
uint32_t intel_miptree_get_tile_offsets (const struct intel_mipmap_tree *mt, GLuint level, GLuint slice, uint32_t *tile_x, uint32_t *tile_y)
Rendering with tiled buffers requires that the base address of the buffer be aligned to a page boundary.
static void intel_miptree_copy_slice_sw (struct brw_context *brw, struct intel_mipmap_tree *dst_mt, struct intel_mipmap_tree *src_mt, int level, int slice, int width, int height)
static void intel_miptree_copy_slice (struct brw_context *brw, struct intel_mipmap_tree *dst_mt, struct intel_mipmap_tree *src_mt, int level, int face, int depth)
void intel_miptree_copy_teximage (struct brw_context *brw, struct intel_texture_image *intelImage, struct intel_mipmap_tree *dst_mt, bool invalidate)
Copies the image's current data to the given miptree, and associates that miptree with the image.
static void intel_miptree_init_mcs (struct brw_context *brw, struct intel_mipmap_tree *mt, int init_value)
static struct intel_miptree_aux_buffer * intel_mcs_miptree_buf_create (struct brw_context *brw, struct intel_mipmap_tree *mt, mesa_format format, unsigned mcs_width, unsigned mcs_height, uint32_t layout_flags)
bool intel_miptree_alloc_non_msrt_mcs (struct brw_context *brw, struct intel_mipmap_tree *mt, bool is_lossless_compressed)
static bool intel_miptree_level_enable_hiz (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t level)
Helper for intel_miptree_alloc_hiz() that sets mt->level[level].has_hiz.
static struct intel_miptree_hiz_buffer * intel_gen7_hiz_buf_create (struct brw_context *brw, struct intel_mipmap_tree *mt)
Helper for intel_miptree_alloc_hiz() that determines the required hiz buffer dimensions and allocates a bo for the hiz buffer.
static struct intel_miptree_hiz_buffer * intel_gen8_hiz_buf_create (struct brw_context *brw, struct intel_mipmap_tree *mt)
Helper for intel_miptree_alloc_hiz() that determines the required hiz buffer dimensions and allocates a bo for the hiz buffer.
static struct intel_miptree_hiz_buffer * intel_hiz_miptree_buf_create (struct brw_context *brw, struct intel_mipmap_tree *mt)
bool intel_miptree_wants_hiz_buffer (struct brw_context *brw, struct intel_mipmap_tree *mt)
bool intel_miptree_alloc_hiz (struct brw_context *brw, struct intel_mipmap_tree *mt)
bool intel_miptree_sample_with_hiz (struct brw_context *brw, struct intel_mipmap_tree *mt)
Can the miptree sample using the hiz buffer?
bool intel_miptree_level_has_hiz (struct intel_mipmap_tree *mt, uint32_t level)
Does the miptree slice have hiz enabled?
void intel_miptree_slice_set_needs_hiz_resolve (struct intel_mipmap_tree *mt, uint32_t level, uint32_t layer)
void intel_miptree_slice_set_needs_depth_resolve (struct intel_mipmap_tree *mt, uint32_t level, uint32_t layer)
void intel_miptree_set_all_slices_need_depth_resolve (struct intel_mipmap_tree *mt, uint32_t level)
static bool intel_miptree_slice_resolve (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t level, uint32_t layer, enum blorp_hiz_op need)
bool intel_miptree_slice_resolve_hiz (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t level, uint32_t layer)
bool intel_miptree_slice_resolve_depth (struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t level, uint32_t layer)
static bool intel_miptree_all_slices_resolve (struct brw_context *brw, struct intel_mipmap_tree *mt, enum blorp_hiz_op need)
bool intel_miptree_all_slices_resolve_hiz (struct brw_context *brw, struct intel_mipmap_tree *mt)
bool intel_miptree_all_slices_resolve_depth (struct brw_context *brw, struct intel_mipmap_tree *mt)
enum intel_fast_clear_state intel_miptree_get_fast_clear_state (const struct intel_mipmap_tree *mt, unsigned level, unsigned layer)
static void intel_miptree_check_color_resolve (const struct brw_context *brw, const struct intel_mipmap_tree *mt, unsigned level, unsigned layer)
void intel_miptree_set_fast_clear_state (const struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned level, unsigned first_layer, unsigned num_layers, enum intel_fast_clear_state new_state)
bool intel_miptree_has_color_unresolved (const struct intel_mipmap_tree *mt, unsigned start_level, unsigned num_levels, unsigned start_layer, unsigned num_layers)
void intel_miptree_used_for_rendering (const struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned level, unsigned start_layer, unsigned num_layers)
static bool intel_miptree_needs_color_resolve (const struct brw_context *brw, const struct intel_mipmap_tree *mt, int flags)
bool intel_miptree_resolve_color (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned level, unsigned start_layer, unsigned num_layers, int flags)
void intel_miptree_all_slices_resolve_color (struct brw_context *brw, struct intel_mipmap_tree *mt, int flags)
void intel_miptree_make_shareable (struct brw_context *brw, struct intel_mipmap_tree *mt)
Make it possible to share the BO backing the given miptree with another process or another miptree.
static intptr_t intel_offset_S8 (uint32_t stride, uint32_t x, uint32_t y, bool swizzled)
Get pointer offset into stencil buffer.
void intel_miptree_updownsample (struct brw_context *brw, struct intel_mipmap_tree *src, struct intel_mipmap_tree *dst)
void intel_update_r8stencil (struct brw_context *brw, struct intel_mipmap_tree *mt)
static void intel_miptree_map_gtt (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static void intel_miptree_unmap_gtt (struct intel_mipmap_tree *mt)
static void intel_miptree_map_blit (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static void intel_miptree_unmap_blit (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static void intel_miptree_map_s8 (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
"Map" a buffer by copying it to an untiled temporary using MOVNTDQA.
static void intel_miptree_unmap_s8 (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static void intel_miptree_map_etc (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static void intel_miptree_unmap_etc (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static void intel_miptree_map_depthstencil (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
Mapping function for packed depth/stencil miptrees backed by real separate miptrees for depth and stencil.
static void intel_miptree_unmap_depthstencil (struct brw_context *brw, struct intel_mipmap_tree *mt, struct intel_miptree_map *map, unsigned int level, unsigned int slice)
static struct intel_miptree_map * intel_miptree_attach_map (struct intel_mipmap_tree *mt, unsigned int level, unsigned int slice, unsigned int x, unsigned int y, unsigned int w, unsigned int h, GLbitfield mode)
Create and attach a map to the miptree at (level, slice).
static void intel_miptree_release_map (struct intel_mipmap_tree *mt, unsigned int level, unsigned int slice)
Release the map at (level, slice).
static bool can_blit_slice (struct intel_mipmap_tree *mt, unsigned int level, unsigned int slice)
static bool use_intel_mipree_map_blit (struct brw_context *brw, struct intel_mipmap_tree *mt, GLbitfield mode, unsigned int level, unsigned int slice)
void intel_miptree_map (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int slice, unsigned int x, unsigned int y, unsigned int w, unsigned int h, GLbitfield mode, void **out_ptr, ptrdiff_t *out_stride)
Parameter out_stride has type ptrdiff_t not because the buffer stride may exceed 32 bits but to diminish the likelihood subtle bugs in pointer arithmetic overflow.
void intel_miptree_unmap (struct brw_context *brw, struct intel_mipmap_tree *mt, unsigned int level, unsigned int slice)
enum isl_surf_dim get_isl_surf_dim (GLenum target)
enum isl_dim_layout get_isl_dim_layout (const struct gen_device_info *devinfo, uint32_t tiling, GLenum target)
enum isl_tiling intel_miptree_get_isl_tiling (const struct intel_mipmap_tree *mt)
void intel_miptree_get_isl_surf (struct brw_context *brw, const struct intel_mipmap_tree *mt, struct isl_surf *surf)
void intel_miptree_get_aux_isl_surf (struct brw_context *brw, const struct intel_mipmap_tree *mt, struct isl_surf *surf, enum isl_aux_usage *usage)
union isl_color_value intel_miptree_get_isl_clear_color (struct brw_context *brw, const struct intel_mipmap_tree *mt)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_MIPTREE
Function Documentation
can_blit_slice()
static bool can_blit_slice (struct intel_mipmap_tree * mt, unsigned int level, unsigned int slice) static
Referenced by use_intel_mipree_map_blit().
compute_msaa_layout()
static enum intel_msaa_layout compute_msaa_layout (struct brw_context * brw, mesa_format format, enum intel_aux_disable aux_disable) static
Determine which MSAA layout should be used by the MSAA surface being created, based on the chip generation and the surface type.
References _mesa_get_format_base_format(), _mesa_get_format_datatype(), and brw_context::gen.
Referenced by intel_miptree_create_layout().
get_isl_dim_layout()
enum isl_dim_layout get_isl_dim_layout (const struct gen_device_info * devinfo, uint32_t tiling, GLenum target)
References GL_TEXTURE_EXTERNAL_OES.
Referenced by brw_emit_surface_state(), and intel_miptree_get_isl_surf().
get_isl_surf_dim()
enum isl_surf_dim get_isl_surf_dim (GLenum target)
References GL_TEXTURE_EXTERNAL_OES.
Referenced by brw_emit_surface_state(), and intel_miptree_get_isl_surf().
intel_depth_format_for_depthstencil_format()
mesa_format intel_depth_format_for_depthstencil_format (mesa_format format)
Determine depth format corresponding to a depth+stencil format, for separate stencil.
References MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, and MESA_FORMAT_Z_FLOAT32.
Referenced by intel_miptree_create_layout(), and intel_texture_view().
intel_gen7_hiz_buf_create()
static struct intel_miptree_hiz_buffer* intel_gen7_hiz_buf_create (struct brw_context * brw, struct intel_mipmap_tree * mt) static
Helper for intel_miptree_alloc_hiz() that determines the required hiz buffer dimensions and allocates a bo for the hiz buffer.
References brw_context::bufmgr.
Referenced by intel_miptree_alloc_hiz().
intel_gen8_hiz_buf_create()
static struct intel_miptree_hiz_buffer* intel_gen8_hiz_buf_create (struct brw_context * brw, struct intel_mipmap_tree * mt) static
Helper for intel_miptree_alloc_hiz() that determines the required hiz buffer dimensions and allocates a bo for the hiz buffer.
References brw_context::bufmgr, and brw_context::gen.
Referenced by intel_miptree_alloc_hiz().
intel_get_image_dims()
void intel_get_image_dims (struct gl_texture_image * image, int * width, int * height, int * depth)
References gl_texture_image::Depth, gl_texture_image::Height, gl_texture_object::Target, gl_texture_image::TexObject, and gl_texture_image::Width.
Referenced by intel_alloc_texture_storage(), intel_finalize_mipmap_tree(), intel_miptree_create_for_teximage(), intel_miptree_match_image(), and intel_renderbuffer_move_to_temp().
intel_get_tile_dims()
void intel_get_tile_dims (uint32_t tiling, uint32_t cpp, uint32_t * tile_w, uint32_t * tile_h)
This function computes the tile_w (in bytes) and tile_h (in rows) of different tiling patterns.
If the BO is untiled, tile_w is set to cpp and tile_h is set to 1.
Referenced by intel_get_tile_masks(), and intelEmitCopyBlit().
intel_get_tile_masks()
void intel_get_tile_masks (uint32_t tiling, uint32_t cpp, uint32_t * mask_x, uint32_t * mask_y)
This function computes masks that may be used to select the bits of the X and Y coordinates that indicate the offset within a tile.
If the BO is untiled, the masks are set to 0.
References intel_get_tile_dims().
Referenced by brw_get_depthstencil_tile_masks(), and intel_miptree_get_tile_offsets().
intel_hiz_miptree_buf_create()
static struct intel_miptree_hiz_buffer* intel_hiz_miptree_buf_create (struct brw_context * brw, struct intel_mipmap_tree * mt) static
References brw_context::gen, intel_miptree_create(), and brw_context::num_samples.
Referenced by intel_miptree_alloc_hiz().
intel_lower_compressed_format()
mesa_format intel_lower_compressed_format (struct brw_context * brw, mesa_format format)
Choose an appropriate uncompressed format for a requested compressed format, if unsupported.
References brw_context::gen, brw_context::is_baytrail, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_R16G16_SNORM, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_R_SNORM16, and MESA_FORMAT_R_UNORM16.
Referenced by intel_texture_view(), and miptree_create().
intel_mcs_miptree_buf_create()
static struct intel_miptree_aux_buffer* intel_mcs_miptree_buf_create (struct brw_context * brw, struct intel_mipmap_tree * mt, mesa_format format, unsigned mcs_width, unsigned mcs_height, uint32_t layout_flags) static
References intel_miptree_release(), and miptree_create().
Referenced by intel_miptree_alloc_mcs().
intel_miptree_all_slices_resolve()
static bool intel_miptree_all_slices_resolve (struct brw_context * brw, struct intel_mipmap_tree * mt, enum blorp_hiz_op need) static
References foreach_list_typed_safe, intel_hiz_exec(), intel_resolve_map_remove(), and intel_resolve_map::link.
Referenced by intel_miptree_all_slices_resolve_depth(), and intel_miptree_all_slices_resolve_hiz().
intel_miptree_all_slices_resolve_color()
void intel_miptree_all_slices_resolve_color (struct brw_context * brw, struct intel_mipmap_tree * mt, int flags)
References brw_blorp_resolve_color(), foreach_list_typed_safe, INTEL_FAST_CLEAR_STATE_RESOLVED, intel_miptree_needs_color_resolve(), intel_resolve_map_remove(), and intel_resolve_map::link.
Referenced by copy_miptrees(), do_blit_bitmap(), intel_gettexsubimage_tiled_memcpy(), intel_miptree_make_shareable(), intel_miptree_map_raw(), intel_readpixels_tiled_memcpy(), intel_texsubimage_tiled_memcpy(), and intel_update_state().
intel_miptree_all_slices_resolve_depth()
bool intel_miptree_all_slices_resolve_depth (struct brw_context * brw, struct intel_mipmap_tree * mt)
References intel_miptree_all_slices_resolve().
Referenced by brw_fast_clear_depth(), copy_miptrees(), intel_miptree_make_shareable(), and intel_update_state().
intel_miptree_all_slices_resolve_hiz()
bool intel_miptree_all_slices_resolve_hiz (struct brw_context * brw, struct intel_mipmap_tree * mt)
References intel_miptree_all_slices_resolve().
Referenced by copy_miptrees(), and intel_update_state().
intel_miptree_alloc_hiz()
bool intel_miptree_alloc_hiz (struct brw_context * brw, struct intel_mipmap_tree * mt)
References brw_context::gen, intel_gen7_hiz_buf_create(), intel_gen8_hiz_buf_create(), intel_hiz_miptree_buf_create(), intel_miptree_level_enable_hiz(), intel_resolve_map::layer, intel_resolve_map::level, intel_resolve_map::link, and intel_resolve_map::need.
Referenced by intel_miptree_create_for_renderbuffer(), intel_renderbuffer_move_to_temp(), and intel_renderbuffer_update_wrapper().
intel_miptree_alloc_mcs()
static bool intel_miptree_alloc_mcs (struct brw_context * brw, struct intel_mipmap_tree * mt, GLuint num_samples) static
References brw_context::gen, INTEL_FAST_CLEAR_STATE_CLEAR, intel_mcs_miptree_buf_create(), intel_miptree_init_mcs(), intel_miptree_set_fast_clear_state(), MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UNORM8, and MESA_FORMAT_RG_UINT32.
Referenced by intel_miptree_create().
intel_miptree_alloc_non_msrt_mcs()
bool intel_miptree_alloc_non_msrt_mcs (struct brw_context * brw, struct intel_mipmap_tree * mt, bool is_lossless_compressed)
References brw_context::bufmgr, intel_miptree_get_isl_surf(), intel_miptree_init_mcs(), and brw_context::isl_dev.
Referenced by do_single_blorp_clear(), and intel_miptree_create().
intel_miptree_attach_map()
static struct intel_miptree_map* intel_miptree_attach_map (struct intel_mipmap_tree * mt, unsigned int level, unsigned int slice, unsigned int x, unsigned int y, unsigned int w, unsigned int h, GLbitfield mode) static
Create and attach a map to the miptree at (level, slice).
Return the attached map.
References intel_miptree_map::h, intel_miptree_map::mode, intel_miptree_map::w, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_map().
intel_miptree_check_color_resolve()
static void intel_miptree_check_color_resolve (const struct brw_context * brw, const struct intel_mipmap_tree * mt, unsigned level, unsigned layer) static
References brw_context::gen, and void.
Referenced by intel_miptree_resolve_color(), and intel_miptree_set_fast_clear_state().
intel_miptree_copy_slice()
static void intel_miptree_copy_slice (struct brw_context * brw, struct intel_mipmap_tree * dst_mt, struct intel_mipmap_tree * src_mt, int level, int face, int depth) static
References _mesa_get_format_block_size(), _mesa_get_format_name(), DBG, intel_miptree_blit(), intel_miptree_copy_slice_sw(), and intel_miptree_get_image_offset().
Referenced by intel_miptree_copy_teximage().
intel_miptree_copy_slice_sw()
static void intel_miptree_copy_slice_sw (struct brw_context * brw, struct intel_mipmap_tree * dst_mt, struct intel_mipmap_tree * src_mt, int level, int slice, int width, int height) static
References _mesa_get_format_name(), BRW_MAP_DIRECT_BIT, DBG, intel_miptree_map(), intel_miptree_unmap(), and brw_context::stencil_mt.
Referenced by intel_miptree_copy_slice().
intel_miptree_copy_teximage()
void intel_miptree_copy_teximage (struct brw_context * brw, struct intel_texture_image * intelImage, struct intel_mipmap_tree * dst_mt, bool invalidate)
Copies the image's current data to the given miptree, and associates that miptree with the image.
If invalidate is true, then the actual image data does not need to be copied, but the image still needs to be associated to the new miptree (this is set to true if we're about to clear the image).
References swrast_texture_image::Base, intel_texture_image::base, intel_texture_object::base, gl_texture_image::Depth, gl_texture_image::Face, GLuint, gl_texture_image::Height, intel_miptree_copy_slice(), intel_miptree_reference(), intel_texture_object(), gl_texture_image::Level, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by intel_finalize_mipmap_tree(), and intel_renderbuffer_move_to_temp().
intel_miptree_create()
struct intel_mipmap_tree* intel_miptree_create (struct brw_context * brw, GLenum target, mesa_format format, GLuint first_level, GLuint last_level, GLuint width0, GLuint height0, GLuint depth0, GLuint num_samples, uint32_t layout_flags)
References brw_context::bufmgr, brw_context::gen, intel_miptree_alloc_mcs(), intel_miptree_alloc_non_msrt_mcs(), intel_miptree_release(), intel_miptree_supports_lossless_compressed(), intel_miptree_supports_non_msrt_fast_clear(), intel_tiling_supports_non_msrt_mcs(), brw_context::max_gtt_map_object_size, and miptree_create().
Referenced by intel_alloc_texture_storage(), intel_finalize_mipmap_tree(), intel_hiz_miptree_buf_create(), intel_miptree_create_for_renderbuffer(), intel_miptree_create_for_teximage(), intel_miptree_create_layout(), intel_miptree_map_blit(), intel_renderbuffer_move_to_temp(), and intel_update_r8stencil().
intel_miptree_create_for_bo()
struct intel_mipmap_tree* intel_miptree_create_for_bo (struct brw_context * brw, drm_intel_bo * bo, mesa_format format, uint32_t offset, uint32_t width, uint32_t height, uint32_t depth, int pitch, uint32_t layout_flags)
References intel_miptree_create_layout(), and swizzle().
Referenced by create_mt_for_dri_image(), create_mt_for_planar_dri_image(), do_blit_drawpixels(), intel_image_target_renderbuffer_storage(), intel_set_texture_storage_for_buffer_object(), intel_update_winsys_renderbuffer_miptree(), and intelSetTexBuffer2().
intel_miptree_create_for_renderbuffer()
struct intel_mipmap_tree* intel_miptree_create_for_renderbuffer (struct brw_context * brw, mesa_format format, uint32_t width, uint32_t height, uint32_t num_samples)
References intel_miptree_alloc_hiz(), intel_miptree_create(), intel_miptree_release(), and intel_miptree_wants_hiz_buffer().
Referenced by intel_alloc_private_renderbuffer_storage(), intel_map_renderbuffer(), and intel_update_winsys_renderbuffer_miptree().
intel_miptree_create_layout()
static struct intel_mipmap_tree* intel_miptree_create_layout (struct brw_context * brw, GLenum target, mesa_format format, GLuint first_level, GLuint last_level, GLuint width0, GLuint height0, GLuint depth0, GLuint num_samples, uint32_t layout_flags) static
Parameters
for_bo Indicates that the caller is intel_miptree_create_for_bo(). If true, then do not create stencil_mt.
References _mesa_enum_to_string(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_get_format_name(), _mesa_is_format_compressed(), _mesa_problem(), brw_miptree_layout(), compute_msaa_layout(), DBG, brw_context::gen, brw_context::has_separate_stencil, intel_depth_format_for_depthstencil_format(), intel_miptree_create(), intel_miptree_release(), intel_miptree_supports_non_msrt_fast_clear(), intel_miptree_wants_hiz_buffer(), MESA_FORMAT_R_UINT32, MESA_FORMAT_S_UINT8, and brw_context::must_use_separate_stencil.
Referenced by intel_miptree_create_for_bo(), and miptree_create().
intel_miptree_get_aligned_offset()
uint32_t intel_miptree_get_aligned_offset (const struct intel_mipmap_tree * mt, uint32_t x, uint32_t y)
Compute the offset (in bytes) from the start of the BO to the given x and y coordinate.
For tiled BOs, caller must ensure that x and y are multiples of the tile size.
Referenced by apply_gen6_stencil_hiz_offset(), brw_workaround_depthstencil_alignment(), gen6_emit_depth_stencil_hiz(), and intel_miptree_get_tile_offsets().
intel_miptree_get_aux_isl_surf()
void intel_miptree_get_aux_isl_surf (struct brw_context * brw, const struct intel_mipmap_tree * mt, struct isl_surf * surf, enum isl_aux_usage * usage)
References brw_context::gen, intel_miptree_get_isl_surf(), intel_miptree_is_lossless_compressed(), and brw_context::isl_dev.
Referenced by blorp_surf_for_miptree(), and brw_emit_surface_state().
intel_miptree_get_fast_clear_state()
enum intel_fast_clear_state intel_miptree_get_fast_clear_state (const struct intel_mipmap_tree * mt, unsigned level, unsigned layer)
References intel_resolve_map::fast_clear_state, INTEL_FAST_CLEAR_STATE_RESOLVED, and intel_resolve_map_const_get().
Referenced by do_single_blorp_clear(), and intel_miptree_used_for_rendering().
intel_miptree_get_image_offset()
void intel_miptree_get_image_offset (const struct intel_mipmap_tree * mt, GLuint level, GLuint slice, GLuint * x, GLuint * y)
Referenced by brw_workaround_depthstencil_alignment(), intel_miptree_blit(), intel_miptree_copy(), intel_miptree_copy_slice(), intel_miptree_get_tile_offsets(), intel_miptree_map_depthstencil(), intel_miptree_map_gtt(), intel_miptree_map_s8(), intel_miptree_unmap_blit(), intel_miptree_unmap_depthstencil(), intel_miptree_unmap_etc(), intel_miptree_unmap_s8(), intel_renderbuffer_set_draw_offset(), and update_texture_image_param().
intel_miptree_get_isl_clear_color()
union isl_color_value intel_miptree_get_isl_clear_color (struct brw_context * brw, const struct intel_mipmap_tree * mt)
References _mesa_get_format_base_format(), _mesa_is_format_integer(), and brw_context::gen.
Referenced by blorp_surf_for_miptree(), and brw_emit_surface_state().
intel_miptree_get_isl_surf()
void intel_miptree_get_isl_surf (struct brw_context * brw, const struct intel_mipmap_tree * mt, struct isl_surf * surf)
References _mesa_get_format_base_format(), _mesa_get_format_block_size(), _mesa_is_cube_map_texture(), intel_screen::devinfo, brw_context::format_supported_as_render_target, brw_context::gen, get_isl_dim_layout(), get_isl_surf_dim(), intel_miptree_get_isl_tiling(), MESA_FORMAT_S_UINT8, brw_context::screen, and translate_tex_format().
Referenced by blorp_surf_for_miptree(), brw_emit_surface_state(), intel_miptree_alloc_non_msrt_mcs(), and intel_miptree_get_aux_isl_surf().
intel_miptree_get_isl_tiling()
enum isl_tiling intel_miptree_get_isl_tiling (const struct intel_mipmap_tree * mt)
References MESA_FORMAT_S_UINT8.
Referenced by get_blit_intratile_offset_el(), and intel_miptree_get_isl_surf().
intel_miptree_get_tile_offsets()
uint32_t intel_miptree_get_tile_offsets (const struct intel_mipmap_tree * mt, GLuint level, GLuint slice, uint32_t * tile_x, uint32_t * tile_y)
Rendering with tiled buffers requires that the base address of the buffer be aligned to a page boundary.
For renderbuffers, and sometimes with textures, we may want the surface to point at a texture image level that isn't at a page boundary.
This function returns an appropriately-aligned base offset according to the tiling restrictions, plus any required x/y offset from there.
References intel_get_tile_masks(), intel_miptree_get_aligned_offset(), intel_miptree_get_image_offset(), and x.
Referenced by brw_emit_surface_state(), create_mt_for_dri_image(), intel_renderbuffer_get_tile_offsets(), and intel_setup_image_from_mipmap_tree().
intel_miptree_has_color_unresolved()
bool intel_miptree_has_color_unresolved (const struct intel_mipmap_tree * mt, unsigned start_level, unsigned num_levels, unsigned start_layer, unsigned num_layers)
References intel_resolve_map_find_any().
Referenced by blorp_surf_for_miptree(), brw_disable_aux_surface(), brw_texture_view_sane(), and update_image_surface().
intel_miptree_hiz_buffer_free()
static void intel_miptree_hiz_buffer_free (struct intel_miptree_hiz_buffer * hiz_buf) static
References intel_miptree_release().
Referenced by intel_miptree_make_shareable(), and intel_miptree_release().
intel_miptree_init_mcs()
static void intel_miptree_init_mcs (struct brw_context * brw, struct intel_mipmap_tree * mt, int init_value) static
References brw_context::bo, brw_bo_map_gtt(), and ret().
Referenced by intel_miptree_alloc_mcs(), and intel_miptree_alloc_non_msrt_mcs().
intel_miptree_is_lossless_compressed()
bool intel_miptree_is_lossless_compressed (const struct brw_context * brw, const struct intel_mipmap_tree * mt)
References brw_context::gen.
Referenced by brw_disable_aux_surface(), brw_predraw_set_aux_buffers(), brw_texture_view_sane(), do_single_blorp_clear(), intel_miptree_get_aux_isl_surf(), intel_miptree_needs_color_resolve(), intel_miptree_used_for_rendering(), intel_texture_view_requires_resolve(), and intel_update_state().
intel_miptree_level_enable_hiz()
static bool intel_miptree_level_enable_hiz (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t level) static
Helper for intel_miptree_alloc_hiz() that sets mt->level[level].has_hiz.
Return true if and only if has_hiz was set.
References DBG, brw_context::gen, and brw_context::is_haswell.
Referenced by intel_miptree_alloc_hiz().
intel_miptree_level_has_hiz()
bool intel_miptree_level_has_hiz (struct intel_mipmap_tree * mt, uint32_t level)
Does the miptree slice have hiz enabled?
References intel_resolve_map::level.
Referenced by brw_get_depthstencil_tile_masks(), gen6_blorp_hiz_exec(), intel_miptree_sample_with_hiz(), intel_miptree_slice_set_needs_depth_resolve(), intel_miptree_slice_set_needs_hiz_resolve(), and intel_renderbuffer_has_hiz().
intel_miptree_make_shareable()
void intel_miptree_make_shareable (struct brw_context * brw, struct intel_mipmap_tree * mt)
Make it possible to share the BO backing the given miptree with another process or another miptree.
Fast color clears are unsafe with shared buffers, so we need to resolve and then discard the MCS buffer, if present. We also set the no_ccs flag to ensure that no MCS buffer gets allocated in the future.
HiZ is similarly unsafe with shared buffers.
References intel_miptree_all_slices_resolve_color(), intel_miptree_all_slices_resolve_depth(), and intel_miptree_hiz_buffer_free().
Referenced by intel_create_image_from_renderbuffer(), intel_setup_image_from_mipmap_tree(), and intelSetTexBuffer2().
intel_miptree_map()
void intel_miptree_map (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int slice, unsigned int x, unsigned int y, unsigned int w, unsigned int h, GLbitfield mode, void ** out_ptr, ptrdiff_t * out_stride)
Parameter out_stride has type ptrdiff_t not because the buffer stride may exceed 32 bits but to diminish the likelihood subtle bugs in pointer arithmetic overflow.
If you call this function and use out_stride, then you're doing pointer arithmetic on out_ptr. The type of out_stride doesn't prevent all bugs. The caller must still take care to avoid 32-bit overflow errors in all arithmetic expressions that contain buffer offsets and pixel sizes, which usually have type uint32_t or GLuint.
References BRW_MAP_DIRECT_BIT, intel_miptree_attach_map(), intel_miptree_map_blit(), intel_miptree_map_depthstencil(), intel_miptree_map_etc(), intel_miptree_map_gtt(), intel_miptree_map_s8(), intel_miptree_release_map(), intel_miptree_slice_resolve_depth(), intel_miptree_slice_set_needs_hiz_resolve(), MESA_FORMAT_NONE, MESA_FORMAT_S_UINT8, intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, and use_intel_mipree_map_blit().
Referenced by copy_image_with_memcpy(), intel_map_renderbuffer(), intel_map_texture_image(), and intel_miptree_copy_slice_sw().
intel_miptree_map_blit()
static void intel_miptree_map_blit (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References _mesa_get_format_name(), DBG, intel_miptree_map::h, intel_miptree_copy(), intel_miptree_create(), intel_miptree_map_raw(), intel_miptree_release(), intel_miptree_map::linear_mt, intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_map().
intel_miptree_map_depthstencil()
static void intel_miptree_map_depthstencil (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
Mapping function for packed depth/stencil miptrees backed by real separate miptrees for depth and stencil.
On gen7, and to support HiZ pre-gen7, we have to have the stencil buffer separate from the depth buffer. Yet at the GL API level, we have to expose packed depth/stencil textures and FBO attachments, and Mesa core expects to be able to map that memory for texture storage and glReadPixels-type operations. We give Mesa core that access by mallocing a temporary and copying the data between the actual backing store and the temporary.
References intel_miptree_map::buffer, DBG, intel_miptree_map::h, brw_context::has_swizzling, intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_unmap_raw(), intel_offset_S8(), MESA_FORMAT_Z_FLOAT32, intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, x, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_map().
intel_miptree_map_etc()
static void intel_miptree_map_etc (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References _mesa_format_image_size(), _mesa_format_row_stride(), intel_miptree_map::buffer, intel_miptree_map::h, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_NONE, MESA_FORMAT_R8G8B8X8_UNORM, intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, and intel_miptree_map::w.
Referenced by intel_miptree_map().
intel_miptree_map_gtt()
static void intel_miptree_map_gtt (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References _mesa_get_format_block_size(), _mesa_get_format_name(), DBG, intel_miptree_map::h, intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, x, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_map().
intel_miptree_map_raw()
static void * intel_miptree_map_raw (struct brw_context * brw, struct intel_mipmap_tree * mt) static
References brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_bo_map_gtt(), intel_batchbuffer_flush, and intel_miptree_all_slices_resolve_color().
Referenced by intel_miptree_map_blit(), intel_miptree_map_depthstencil(), intel_miptree_map_gtt(), intel_miptree_map_s8(), intel_miptree_unmap_blit(), intel_miptree_unmap_depthstencil(), intel_miptree_unmap_etc(), and intel_miptree_unmap_s8().
intel_miptree_map_s8()
static void intel_miptree_map_s8 (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
"Map" a buffer by copying it to an untiled temporary using MOVNTDQA.
References intel_miptree_map::buffer, DBG, intel_miptree_map::h, brw_context::has_swizzling, intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_unmap_raw(), intel_offset_S8(), intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, x, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_map().
intel_miptree_match_image()
bool intel_miptree_match_image (struct intel_mipmap_tree * mt, struct gl_texture_image * image)
Can the image be pulled into a unified mipmap tree? This mirrors the completeness test in a lot of ways.
Not sure whether I want to pass gl_texture_image here.
References swrast_texture_image::Base, intel_texture_image::base, GLuint, intel_get_image_dims(), intel_texture_image(), gl_texture_image::Level, MESA_FORMAT_NONE, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, gl_texture_image::NumSamples, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::TexObject.
Referenced by intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), and intel_finalize_mipmap_tree().
intel_miptree_needs_color_resolve()
static bool intel_miptree_needs_color_resolve (const struct brw_context * brw, const struct intel_mipmap_tree * mt, int flags) static
References intel_miptree_is_lossless_compressed().
Referenced by intel_miptree_all_slices_resolve_color(), and intel_miptree_resolve_color().
intel_miptree_reference()
void intel_miptree_reference (struct intel_mipmap_tree ** dst, struct intel_mipmap_tree * src)
References DBG, and intel_miptree_release().
Referenced by brw_workaround_depthstencil_alignment(), intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_bind_renderbuffer_tex_image(), intel_miptree_copy_teximage(), intel_renderbuffer_move_to_temp(), intel_renderbuffer_update_wrapper(), intel_set_texture_image_mt(), intel_set_texture_storage_for_buffer_object(), and intel_texture_view().
intel_miptree_release()
void intel_miptree_release (struct intel_mipmap_tree ** mt)
References DBG, GLuint, intel_miptree_hiz_buffer_free(), intel_resolve_map_clear(), and MAX_TEXTURE_LEVELS.
Referenced by create_mt_for_dri_image(), do_blit_drawpixels(), intel_alloc_private_renderbuffer_storage(), intel_alloc_texture_storage(), intel_delete_renderbuffer(), intel_finalize_mipmap_tree(), intel_free_texture_image_buffer(), intel_image_target_renderbuffer_storage(), intel_image_target_texture_2d(), intel_mcs_miptree_buf_create(), intel_miptree_create(), intel_miptree_create_for_renderbuffer(), intel_miptree_create_layout(), intel_miptree_hiz_buffer_free(), intel_miptree_map_blit(), intel_miptree_reference(), intel_miptree_unmap_blit(), intel_render_object_unpurgeable(), intel_renderbuffer_move_to_temp(), intel_texture_object_unpurgeable(), intel_unmap_renderbuffer(), intel_update_winsys_renderbuffer_miptree(), intelDeleteTextureObject(), and intelSetTexBuffer2().
intel_miptree_release_map()
static void intel_miptree_release_map (struct intel_mipmap_tree * mt, unsigned int level, unsigned int slice) static
Release the map at (level, slice).
Referenced by intel_miptree_map(), and intel_miptree_unmap().
intel_miptree_resolve_color()
bool intel_miptree_resolve_color (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned level, unsigned start_layer, unsigned num_layers, int flags)
References brw_blorp_resolve_color(), intel_resolve_map::fast_clear_state, brw_context::gen, INTEL_FAST_CLEAR_STATE_RESOLVED, intel_miptree_check_color_resolve(), intel_miptree_needs_color_resolve(), intel_resolve_map_get(), and intel_resolve_map_remove().
Referenced by blorp_surf_for_miptree(), brw_predraw_set_aux_buffers(), intel_miptree_blit(), intel_miptree_copy(), intel_resolve_for_dri2_flush(), and intel_update_state().
intel_miptree_sample_with_hiz()
bool intel_miptree_sample_with_hiz (struct brw_context * brw, struct intel_mipmap_tree * mt)
Can the miptree sample using the hiz buffer?
References brw_context::gen, intel_miptree_level_has_hiz(), and intel_resolve_map::level.
Referenced by brw_emit_surface_state(), and intel_update_state().
intel_miptree_set_all_slices_need_depth_resolve()
void intel_miptree_set_all_slices_need_depth_resolve (struct intel_mipmap_tree * mt, uint32_t level)
References intel_miptree_slice_set_needs_depth_resolve(), intel_resolve_map::layer, and intel_resolve_map::level.
Referenced by intel_renderbuffer_att_set_needs_depth_resolve().
intel_miptree_set_fast_clear_state()
void intel_miptree_set_fast_clear_state (const struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned level, unsigned first_layer, unsigned num_layers, enum intel_fast_clear_state new_state)
References INTEL_FAST_CLEAR_STATE_RESOLVED, intel_miptree_check_color_resolve(), and intel_resolve_map_set().
Referenced by do_single_blorp_clear(), intel_miptree_alloc_mcs(), and intel_miptree_used_for_rendering().
intel_miptree_set_image_offset()
void intel_miptree_set_image_offset (struct intel_mipmap_tree * mt, GLuint level, GLuint img, GLuint x, GLuint y)
References DBG.
Referenced by brw_miptree_layout_texture_3d(), and brw_miptree_layout_texture_array().
intel_miptree_set_level_info()
void intel_miptree_set_level_info (struct intel_mipmap_tree * mt, GLuint level, GLuint x, GLuint y, GLuint d)
References DBG.
Referenced by brw_miptree_layout_2d(), brw_miptree_layout_texture_3d(), and gen9_miptree_layout_1d().
intel_miptree_slice_resolve()
static bool intel_miptree_slice_resolve (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t level, uint32_t layer, enum blorp_hiz_op need) static
References intel_hiz_exec(), intel_resolve_map_get(), intel_resolve_map_remove(), and intel_resolve_map::need.
Referenced by intel_miptree_slice_resolve_depth(), and intel_miptree_slice_resolve_hiz().
intel_miptree_slice_resolve_depth()
bool intel_miptree_slice_resolve_depth (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t level, uint32_t layer)
References intel_miptree_slice_resolve().
Referenced by blorp_surf_for_miptree(), intel_miptree_blit(), intel_miptree_copy(), intel_miptree_map(), and intel_renderbuffer_resolve_depth().
intel_miptree_slice_resolve_hiz()
bool intel_miptree_slice_resolve_hiz (struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t level, uint32_t layer)
References intel_miptree_slice_resolve().
Referenced by intel_renderbuffer_resolve_hiz().
intel_miptree_slice_set_needs_depth_resolve()
void intel_miptree_slice_set_needs_depth_resolve (struct intel_mipmap_tree * mt, uint32_t level, uint32_t layer)
References intel_miptree_level_has_hiz(), and intel_resolve_map_set().
Referenced by intel_miptree_set_all_slices_need_depth_resolve(), and intel_renderbuffer_att_set_needs_depth_resolve().
intel_miptree_slice_set_needs_hiz_resolve()
void intel_miptree_slice_set_needs_hiz_resolve (struct intel_mipmap_tree * mt, uint32_t level, uint32_t layer)
References intel_miptree_level_has_hiz(), and intel_resolve_map_set().
Referenced by blorp_surf_for_miptree(), and intel_miptree_map().
intel_miptree_supports_lossless_compressed()
bool intel_miptree_supports_lossless_compressed (struct brw_context * brw, const struct intel_mipmap_tree * mt)
References _mesa_get_format_datatype(), _mesa_get_srgb_format_linear(), and intel_miptree_supports_non_msrt_fast_clear().
Referenced by intel_miptree_create().
intel_miptree_supports_non_msrt_fast_clear()
bool intel_miptree_supports_non_msrt_fast_clear (struct brw_context * brw, const struct intel_mipmap_tree * mt)
For a single-sampled render target ("non-MSRT"), determine if an MCS buffer can be used.
This doesn't (and should not) inspect any of the properties of the miptree's BO.
From the Ivy Bridge PRM, Vol2 Part1 11.7 "MCS Buffer for Render Target(s)", beneath the "Fast Color Clear" bullet (p326):
- Support is for non-mip-mapped and non-array surface types only.
And then later, on p327:
- MCS buffer for non-MSRT is supported only for RT formats 32bpp,
  64bpp, and 128bpp.
From the Skylake documentation, it is made clear that X-tiling is no longer supported:
- MCS and Lossless compression is supported for TiledY/TileYs/TileYf
non-MSRTs only.
References _mesa_get_format_base_format(), _mesa_get_srgb_format_linear(), brw_isl_format_for_mesa_format(), intel_screen::devinfo, brw_context::format_supported_as_render_target, brw_context::gen, and brw_context::screen.
Referenced by intel_miptree_create(), intel_miptree_create_layout(), intel_miptree_supports_lossless_compressed(), and intel_update_winsys_renderbuffer_miptree().
intel_miptree_unmap()
void intel_miptree_unmap (struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned int level, unsigned int slice)
References _mesa_get_format_name(), BRW_MAP_DIRECT_BIT, intel_miptree_map::buffer, DBG, intel_miptree_release_map(), intel_miptree_unmap_blit(), intel_miptree_unmap_depthstencil(), intel_miptree_unmap_etc(), intel_miptree_unmap_gtt(), intel_miptree_unmap_s8(), intel_miptree_map::linear_mt, MESA_FORMAT_NONE, MESA_FORMAT_S_UINT8, and intel_miptree_map::mode.
Referenced by copy_image_with_memcpy(), intel_miptree_copy_slice_sw(), intel_unmap_renderbuffer(), and intel_unmap_texture_image().
intel_miptree_unmap_blit()
static void intel_miptree_unmap_blit (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References _mesa_align_free(), _mesa_align_malloc(), _mesa_format_row_stride(), _mesa_get_format_name(), _mesa_streaming_load_memcpy(), intel_miptree_map::buffer, brw_context::ctx, DBG, intel_miptree_map::h, intel_miptree_copy(), intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_release(), intel_miptree_unmap_raw(), intel_miptree_map::linear_mt, intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_unmap().
intel_miptree_unmap_depthstencil()
static void intel_miptree_unmap_depthstencil (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References _mesa_get_format_name(), intel_miptree_map::buffer, DBG, intel_miptree_map::h, brw_context::has_swizzling, intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_unmap_raw(), intel_offset_S8(), MESA_FORMAT_Z_FLOAT32, intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, x, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_unmap().
intel_miptree_unmap_etc()
static void intel_miptree_unmap_etc (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References _mesa_etc1_unpack_rgba8888(), _mesa_unpack_etc2_format(), intel_miptree_map::buffer, intel_miptree_map::h, intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_unmap_raw(), MESA_FORMAT_ETC1_RGB8, intel_miptree_map::ptr, intel_miptree_map::stride, intel_miptree_map::w, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_unmap().
intel_miptree_unmap_gtt()
static void intel_miptree_unmap_gtt (struct intel_mipmap_tree * mt) static
References intel_miptree_unmap_raw().
Referenced by intel_miptree_unmap().
intel_miptree_unmap_raw()
static void intel_miptree_unmap_raw (struct intel_mipmap_tree * mt) static
Referenced by intel_miptree_map_depthstencil(), intel_miptree_map_s8(), intel_miptree_unmap_blit(), intel_miptree_unmap_depthstencil(), intel_miptree_unmap_etc(), intel_miptree_unmap_gtt(), and intel_miptree_unmap_s8().
intel_miptree_unmap_s8()
static void intel_miptree_unmap_s8 (struct brw_context * brw, struct intel_mipmap_tree * mt, struct intel_miptree_map * map, unsigned int level, unsigned int slice) static
References intel_miptree_map::buffer, intel_miptree_map::h, brw_context::has_swizzling, intel_miptree_get_image_offset(), intel_miptree_map_raw(), intel_miptree_unmap_raw(), intel_offset_S8(), intel_miptree_map::mode, intel_miptree_map::ptr, intel_miptree_map::w, x, intel_miptree_map::x, and intel_miptree_map::y.
Referenced by intel_miptree_unmap().
intel_miptree_updownsample()
void intel_miptree_updownsample (struct brw_context * brw, struct intel_mipmap_tree * src, struct intel_mipmap_tree * dst)
References brw_blorp_blit_miptrees(), and brw_context::stencil_mt.
Referenced by intel_renderbuffer_downsample(), and intel_renderbuffer_upsample().
intel_miptree_used_for_rendering()
void intel_miptree_used_for_rendering (const struct brw_context * brw, struct intel_mipmap_tree * mt, unsigned level, unsigned start_layer, unsigned num_layers)
References intel_resolve_map::fast_clear_state, INTEL_FAST_CLEAR_STATE_CLEAR, INTEL_FAST_CLEAR_STATE_UNRESOLVED, intel_miptree_get_fast_clear_state(), intel_miptree_is_lossless_compressed(), and intel_miptree_set_fast_clear_state().
Referenced by blorp_surf_for_miptree(), and brw_postdraw_set_buffers_need_resolve().
intel_miptree_wants_hiz_buffer()
bool intel_miptree_wants_hiz_buffer (struct brw_context * brw, struct intel_mipmap_tree * mt)
References brw_context::has_hiz, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, and MESA_FORMAT_Z_UNORM16.
Referenced by intel_miptree_create_for_renderbuffer(), intel_miptree_create_layout(), intel_renderbuffer_move_to_temp(), and intel_renderbuffer_update_wrapper().
intel_offset_S8()
static intptr_t intel_offset_S8 (uint32_t stride, uint32_t x, uint32_t y, bool swizzled) static
Get pointer offset into stencil buffer.
The stencil buffer is W tiled. Since the GTT is incapable of W fencing, we must decode the tile's layout in software.
See
PRM, 2011 Sandy Bridge, Volume 1, Part 2, Section 4.5.2.1 W-Major Tile Format.
PRM, 2011 Sandy Bridge, Volume 1, Part 2, Section 4.5.3 Tiling Algorithm
Even though the returned offset is always positive, the return type is signed due to commit e8b1c6d6f55f5be3bef25084fdd8b6127517e137 mesa: Fix return type of _mesa_get_format_bytes() (#37351)
Referenced by intel_miptree_map_depthstencil(), intel_miptree_map_s8(), intel_miptree_unmap_depthstencil(), and intel_miptree_unmap_s8().
intel_tiling_supports_non_msrt_mcs()
bool intel_tiling_supports_non_msrt_mcs (const struct brw_context * brw, unsigned tiling)
References brw_context::gen.
Referenced by intel_miptree_create(), and intel_update_winsys_renderbuffer_miptree().
intel_update_r8stencil()
void intel_update_r8stencil (struct brw_context * brw, struct intel_mipmap_tree * mt)
References brw_context::bo, brw_blorp_blit_miptrees(), brw_render_cache_set_check_flush(), for(), brw_context::gen, intel_miptree_create(), MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM8, and MESA_FORMAT_S_UINT8.
Referenced by intel_update_state().
intel_update_winsys_renderbuffer_miptree()
void intel_update_winsys_renderbuffer_miptree (struct brw_context * intel, struct intel_renderbuffer * irb, drm_intel_bo * bo, uint32_t width, uint32_t height, uint32_t pitch)
For a singlesample renderbuffer, this simply wraps the given BO with a miptree.
For a multisample renderbuffer, this wraps the window system's (singlesample) BO with a singlesample miptree attached to the intel_renderbuffer, then creates a multisample miptree attached to irb->mt that will contain the actual rendering (which is lazily resolved to irb->singlesample_mt).
References _mesa_get_format_base_format(), swrast_renderbuffer::Base, intel_renderbuffer::Base, gl_renderbuffer::Format, intel_miptree_create_for_bo(), intel_miptree_create_for_renderbuffer(), intel_miptree_release(), intel_miptree_supports_non_msrt_fast_clear(), intel_tiling_supports_non_msrt_mcs(), intel_renderbuffer::mt, intel_renderbuffer::need_downsample, gl_renderbuffer::NumSamples, and intel_renderbuffer::singlesample_mt.
Referenced by intel_process_dri2_buffer(), and intel_update_image_buffer().
miptree_create()
static struct intel_mipmap_tree* miptree_create (struct brw_context * brw, GLenum target, mesa_format format, GLuint first_level, GLuint last_level, GLuint width0, GLuint height0, GLuint depth0, GLuint num_samples, uint32_t layout_flags) static
References brw_context::bufmgr, intel_lower_compressed_format(), intel_miptree_create_layout(), MESA_FORMAT_NONE, and MESA_FORMAT_S_UINT8.
Referenced by intel_mcs_miptree_buf_create(), and intel_miptree_create().
use_intel_mipree_map_blit()
static bool use_intel_mipree_map_blit (struct brw_context * brw, struct intel_mipmap_tree * mt, GLbitfield mode, unsigned int level, unsigned int slice) static
References can_blit_slice(), brw_context::gen, brw_context::has_llc, and brw_context::max_gtt_map_object_size.
Referenced by intel_miptree_map().