Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_pixel.h File Reference
#include "main/mtypes.h"
Functions
void intelInitPixelFuncs (struct dd_function_table *functions)
bool intel_check_blit_fragment_ops (struct gl_context *ctx, bool src_alpha_is_one)
Check if any fragment operations are in effect which might effect glDraw/CopyPixels.
void intelReadPixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *pack, GLvoid *pixels)
void intelDrawPixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
void intelCopyPixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint destx, GLint desty, GLenum type)
void intelBitmap (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *pixels)
Function Documentation
intel_check_blit_fragment_ops()
bool intel_check_blit_fragment_ops (struct gl_context * ctx, bool src_alpha_is_one)
Check if any fragment operations are in effect which might effect glDraw/CopyPixels.
References gl_fragment_program_state::_Enabled, gl_stencil_attrib::_Enabled, gl_context::_ImageTransferState, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_update_state(), gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, gl_context::Color, gl_colorbuffer_attrib::ColorMask, DBG, gl_context::Depth, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, effective_func(), gl_fog_attrib::Enabled, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_context::Fog, gl_context::FragmentProgram, gl_context::NewState, gl_context::Pixel, gl_context::RenderMode, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, gl_context::Stencil, gl_depthbuffer_attrib::Test, gl_context::Texture, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by do_blit_bitmap(), and do_blit_drawpixels().
intelBitmap()
void intelBitmap (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * pixels)
References _mesa_check_conditional_render(), and do_blit_bitmap().
Referenced by intelInitPixelFuncs().
intelCopyPixels()
void intelCopyPixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint destx, GLint desty, GLenum type)
References _mesa_check_conditional_render(), DBG, and do_blit_copypixels().
Referenced by intelInitPixelFuncs().
intelDrawPixels()
void intelDrawPixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels)
References _mesa_check_conditional_render(), _swrast_DrawPixels(), brw_context(), gl_pixelstore_attrib::BufferObj, do_blit_drawpixels(), and brw_context::perf_debug.
Referenced by intelInitPixelFuncs().
intelInitPixelFuncs()
void intelInitPixelFuncs (struct dd_function_table * functions)
References dd_function_table::Bitmap, dd_function_table::CopyPixels, dd_function_table::DrawPixels, intelBitmap(), intelCopyPixels(), intelDrawPixels(), intelReadPixels(), and dd_function_table::ReadPixels.
Referenced by brw_init_driver_functions().
intelReadPixels()
void intelReadPixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * pack, GLvoid * pixels)
References _mesa_readpixels(), _mesa_update_state(), brw_context(), brw_emit_mi_flush(), gl_pixelstore_attrib::BufferObj, DBG, brw_context::front_buffer_dirty, intel_prepare_render(), intel_readpixels_tiled_memcpy(), gl_context::NewState, and brw_context::perf_debug.
Referenced by intelInitPixelFuncs().