Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_screen.c File Reference
#include <drm_fourcc.h>
#include <errno.h>
#include <time.h>
#include <unistd.h>
#include "main/context.h"
#include "main/framebuffer.h"
#include "main/renderbuffer.h"
#include "main/texobj.h"
#include "main/hash.h"
#include "main/fbobject.h"
#include "main/version.h"
#include "swrast/s_renderbuffer.h"
#include "util/ralloc.h"
#include "brw_defines.h"
#include "compiler/nir/nir.h"
#include "utils.h"
#include "xmlpool.h"
#include "intel_batchbuffer.h"
#include "intel_buffers.h"
#include "intel_bufmgr.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "intel_screen.h"
#include "intel_tex.h"
#include "intel_image.h"
#include "brw_context.h"
#include "i915_drm.h"
Data Structures
struct intel_buffer
Macros
#define DRM_FORMAT_MOD_INVALID ((1ULL<<56) - 1)
#define DRM_FORMAT_MOD_LINEAR 0
Enumerations
enum modifier_priority { MODIFIER_PRIORITY_INVALID = 0, MODIFIER_PRIORITY_LINEAR, MODIFIER_PRIORITY_X, MODIFIER_PRIORITY_Y }
Functions
double get_time (void)
For debugging purposes, this returns a time in seconds.
static void intel_dri2_flush_with_flags (__DRIcontext *cPriv, __DRIdrawable *dPriv, unsigned flags, enum __DRI2throttleReason reason)
static void intel_dri2_flush (__DRIdrawable *drawable)
Provides compatibility with loaders that only support the older (version 1-3) flush interface.
static void intel_image_warn_if_unaligned (__DRIimage *image, const char *func)
static struct intel_image_format * intel_image_format_lookup (int fourcc)
static boolean intel_lookup_fourcc (int dri_format, int *fourcc)
static __DRIimage * intel_allocate_image (struct intel_screen *screen, int dri_format, void *loaderPrivate)
static void intel_setup_image_from_mipmap_tree (struct brw_context *brw, __DRIimage *image, struct intel_mipmap_tree *mt, GLuint level, GLuint zoffset)
Sets up a DRIImage structure to point to a slice out of a miptree.
static __DRIimage * intel_create_image_from_name (__DRIscreen *dri_screen, int width, int height, int format, int name, int pitch, void *loaderPrivate)
static __DRIimage * intel_create_image_from_renderbuffer (__DRIcontext *context, int renderbuffer, void *loaderPrivate)
static __DRIimage * intel_create_image_from_texture (__DRIcontext *context, int target, unsigned texture, int zoffset, int level, unsigned *error, void *loaderPrivate)
static void intel_destroy_image (__DRIimage *image)
static uint64_t select_best_modifier (struct gen_device_info *devinfo, const uint64_t *modifiers, const unsigned count)
static __DRIimage * intel_create_image_common (__DRIscreen *dri_screen, int width, int height, int format, unsigned int use, const uint64_t *modifiers, unsigned count, void *loaderPrivate)
static __DRIimage * intel_create_image (__DRIscreen *dri_screen, int width, int height, int format, unsigned int use, void *loaderPrivate)
static __DRIimage * intel_create_image_with_modifiers (__DRIscreen *dri_screen, int width, int height, int format, const uint64_t *modifiers, const unsigned count, void *loaderPrivate)
static GLboolean intel_query_image (__DRIimage *image, int attrib, int *value)
static __DRIimage * intel_dup_image (__DRIimage *orig_image, void *loaderPrivate)
static GLboolean intel_validate_usage (__DRIimage *image, unsigned int use)
static __DRIimage * intel_create_image_from_names (__DRIscreen *dri_screen, int width, int height, int fourcc, int *names, int num_names, int *strides, int *offsets, void *loaderPrivate)
static __DRIimage * intel_create_image_from_fds (__DRIscreen *dri_screen, int width, int height, int fourcc, int *fds, int num_fds, int *strides, int *offsets, void *loaderPrivate)
static __DRIimage * intel_create_image_from_dma_bufs (__DRIscreen *dri_screen, int width, int height, int fourcc, int *fds, int num_fds, int *strides, int *offsets, enum __DRIYUVColorSpace yuv_color_space, enum __DRISampleRange sample_range, enum __DRIChromaSiting horizontal_siting, enum __DRIChromaSiting vertical_siting, unsigned *error, void *loaderPrivate)
static __DRIimage * intel_from_planar (__DRIimage *parent, int plane, void *loaderPrivate)
static int brw_query_renderer_integer (__DRIscreen *dri_screen, int param, unsigned int *value)
static int brw_query_renderer_string (__DRIscreen *dri_screen, int param, const char **value)
static int intel_get_param (struct intel_screen *screen, int param, int *value)
static bool intel_get_boolean (struct intel_screen *screen, int param)
static int intel_get_integer (struct intel_screen *screen, int param)
static void intelDestroyScreen (__DRIscreen *sPriv)
static GLboolean intelCreateBuffer (__DRIscreen *dri_screen, __DRIdrawable *driDrawPriv, const struct gl_config *mesaVis, GLboolean isPixmap)
This is called when we need to set up GL rendering to a new X window.
static void intelDestroyBuffer (__DRIdrawable *driDrawPriv)
static void intel_detect_sseu (struct intel_screen *screen)
static bool intel_init_bufmgr (struct intel_screen *screen)
static bool intel_detect_swizzling (struct intel_screen *screen)
static int intel_detect_timestamp (struct intel_screen *screen)
static bool intel_detect_pipelined_register (struct intel_screen *screen, int reg, uint32_t expected_value, bool reset)
Test if we can use MI_LOAD_REGISTER_MEM from an untrusted batchbuffer.
static bool intel_detect_pipelined_so (struct intel_screen *screen)
const int * intel_supported_msaa_modes (const struct intel_screen *screen)
Return array of MSAA modes supported by the hardware.
static __DRIconfig ** intel_screen_make_configs (__DRIscreen *dri_screen)
static void set_max_gl_versions (struct intel_screen *screen)
static __attribute__ ((__unused__))
Return the revision (generally the revid field of the PCI header) of the graphics device.
static void shader_debug_log_mesa (void *data, const char *fmt,...)
static void shader_perf_log_mesa (void *data, const char *fmt,...)
static const __DRIconfig ** intelInitScreen2 (__DRIscreen *dri_screen)
This is the driver specific part of the createNewScreen entry point.
static __DRIbuffer * intelAllocateBuffer (__DRIscreen *dri_screen, unsigned attachment, unsigned format, int width, int height)
static void intelReleaseBuffer (__DRIscreen *dri_screen, __DRIbuffer *buffer)
PUBLIC const __DRIextension ** __driDriverGetExtensions_i965 (void)
Variables
static const __DRIconfigOptionsExtension brw_config_options
static const __DRItexBufferExtension intelTexBufferExtension
static const struct __DRI2flushExtensionRec intelFlushExtension
static struct intel_image_format intel_image_formats []
const uint64_t priority_to_modifier []
static const __DRIimageExtension intelImageExtension
static const __DRI2rendererQueryExtension intelRendererQueryExtension
static const __DRIrobustnessExtension dri2Robustness
static const __DRIextension * screenExtensions []
static const __DRIextension * intelRobustScreenExtensions []
static const struct __DriverAPIRec brw_driver_api
static const struct __DRIDriverVtableExtensionRec brw_vtable
static const __DRIextension * brw_driver_extensions []
Macro Definition Documentation
DRM_FORMAT_MOD_INVALID
#define DRM_FORMAT_MOD_INVALID ((1ULL<<56) - 1)
Referenced by intel_create_image_common(), and select_best_modifier().
DRM_FORMAT_MOD_LINEAR
#define DRM_FORMAT_MOD_LINEAR 0
Referenced by intel_create_image_common(), and select_best_modifier().
Enumeration Type Documentation
modifier_priority
enum modifier_priority
Enumerator
MODIFIER_PRIORITY_INVALID
MODIFIER_PRIORITY_LINEAR
MODIFIER_PRIORITY_X
MODIFIER_PRIORITY_Y
Function Documentation
__attribute__()
static __attribute__ ((__unused__)) static
Return the revision (generally the revid field of the PCI header) of the graphics device.
XXX: This function is useful to keep around even if it is not currently in use. It is necessary for new platforms and revision specific workarounds or features. Please don't remove it so that we know it at least continues to build.
References ret().
__driDriverGetExtensions_i965()
PUBLIC const __DRIextension** __driDriverGetExtensions_i965 (void)
References brw_driver_api, and brw_driver_extensions.
brw_query_renderer_integer()
static int brw_query_renderer_integer (__DRIscreen * dri_screen, int param, unsigned int * value) static
References intel_screen::deviceID.
brw_query_renderer_string()
static int brw_query_renderer_string (__DRIscreen * dri_screen, int param, const char ** value) static
References brw_get_renderer_string(), and brw_vendor_string.
get_time()
double get_time (void)
For debugging purposes, this returns a time in seconds.
Referenced by brw_bo_map(), brw_bo_map_gtt(), brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), and brw_collect_and_report_shader_time().
intel_allocate_image()
static __DRIimage* intel_allocate_image (struct intel_screen * screen, int dri_format, void * loaderPrivate) static
References _mesa_get_format_base_format(), intel_image_format::dri_format, and MESA_FORMAT_NONE.
Referenced by intel_create_image_common(), intel_create_image_from_fds(), intel_create_image_from_name(), and intel_from_planar().
intel_create_image()
static __DRIimage* intel_create_image (__DRIscreen * dri_screen, int width, int height, int format, unsigned int use, void * loaderPrivate) static
References intel_create_image_common().
intel_create_image_common()
static __DRIimage* intel_create_image_common (__DRIscreen * dri_screen, int width, int height, int format, unsigned int use, const uint64_t * modifiers, unsigned count, void * loaderPrivate) static
References _mesa_get_format_bytes(), intel_screen::bufmgr, intel_screen::devinfo, DRM_FORMAT_MOD_INVALID, DRM_FORMAT_MOD_LINEAR, intel_allocate_image(), and select_best_modifier().
Referenced by intel_create_image(), and intel_create_image_with_modifiers().
intel_create_image_from_dma_bufs()
static __DRIimage* intel_create_image_from_dma_bufs (__DRIscreen * dri_screen, int width, int height, int fourcc, int * fds, int num_fds, int * strides, int * offsets, enum __DRIYUVColorSpace yuv_color_space, enum __DRISampleRange sample_range, enum __DRIChromaSiting horizontal_siting, enum __DRIChromaSiting vertical_siting, unsigned * error, void * loaderPrivate) static
References intel_create_image_from_fds(), and intel_image_format_lookup().
intel_create_image_from_fds()
static __DRIimage* intel_create_image_from_fds (__DRIscreen * dri_screen, int width, int height, int fourcc, int * fds, int num_fds, int * strides, int * offsets, void * loaderPrivate) static
References intel_image_format::buffer_index, intel_screen::bufmgr, intel_image_format::dri_format, intel_image_format::height_shift, intel_allocate_image(), intel_image_format_lookup(), intel_image_warn_if_unaligned(), intel_image_format::nplanes, and intel_image_format::planes.
Referenced by intel_create_image_from_dma_bufs().
intel_create_image_from_name()
static __DRIimage* intel_create_image_from_name (__DRIscreen * dri_screen, int width, int height, int format, int name, int pitch, void * loaderPrivate) static
References _mesa_get_format_bytes(), intel_screen::bufmgr, intel_allocate_image(), and MESA_FORMAT_NONE.
Referenced by intel_create_image_from_names().
intel_create_image_from_names()
static __DRIimage* intel_create_image_from_names (__DRIscreen * dri_screen, int width, int height, int fourcc, int * names, int num_names, int * strides, int * offsets, void * loaderPrivate) static
References intel_image_format::buffer_index, intel_create_image_from_name(), intel_image_format_lookup(), intel_image_format::nplanes, and intel_image_format::planes.
intel_create_image_from_renderbuffer()
static __DRIimage* intel_create_image_from_renderbuffer (__DRIcontext * context, int renderbuffer, void * loaderPrivate) static
References _mesa_error(), _mesa_lookup_renderbuffer(), brw_context::ctx, gl_renderbuffer::Format, gl_renderbuffer::Height, intel_miptree_make_shareable(), intel_renderbuffer(), gl_renderbuffer::InternalFormat, intel_renderbuffer::mt, gl_renderbuffer::NeedsFinishRenderTexture, and gl_renderbuffer::Width.
intel_create_image_from_texture()
static __DRIimage* intel_create_image_from_texture (__DRIcontext * context, int target, unsigned texture, int zoffset, int level, unsigned * error, void * loaderPrivate) static
References gl_texture_object::_BaseComplete, gl_texture_object::_MaxLevel, _mesa_lookup_texture(), _mesa_test_texobj_completeness(), gl_texture_object::_MipmapComplete, brw_context::ctx, gl_texture_image::Depth, GLuint, gl_texture_object::Image, intel_setup_image_from_mipmap_tree(), intel_texture_object(), gl_texture_image::InternalFormat, MESA_FORMAT_NONE, intel_texture_object::mt, gl_texture_object::Target, and gl_texture_image::TexFormat.
intel_create_image_with_modifiers()
static __DRIimage* intel_create_image_with_modifiers (__DRIscreen * dri_screen, int width, int height, int format, const uint64_t * modifiers, const unsigned count, void * loaderPrivate) static
References intel_create_image_common().
intel_destroy_image()
static void intel_destroy_image (__DRIimage * image) static
intel_detect_pipelined_register()
static bool intel_detect_pipelined_register (struct intel_screen * screen, int reg, uint32_t expected_value, bool reset) static
Test if we can use MI_LOAD_REGISTER_MEM from an untrusted batchbuffer.
Some combinations of hardware and kernel versions allow this feature, while others don't. Instead of trying to enumerate every case, just try and write a register and see if works.
References intel_screen::bufmgr, MI_BATCH_BUFFER_END, MI_LOAD_REGISTER_IMM, and MI_STORE_REGISTER_MEM.
Referenced by intel_detect_pipelined_so().
intel_detect_pipelined_so()
static bool intel_detect_pipelined_so (struct intel_screen * screen) static
References intel_screen::cmd_parser_version, intel_screen::devinfo, GEN7_SO_WRITE_OFFSET, and intel_detect_pipelined_register().
Referenced by intelInitScreen2().
intel_detect_sseu()
static void intel_detect_sseu (struct intel_screen * screen) static
References _mesa_warning(), intel_screen::devinfo, intel_screen::eu_total, intel_get_param(), ret(), and intel_screen::subslice_total.
Referenced by intelInitScreen2().
intel_detect_swizzling()
static bool intel_detect_swizzling (struct intel_screen * screen) static
References intel_screen::bufmgr.
Referenced by intelInitScreen2().
intel_detect_timestamp()
static int intel_detect_timestamp (struct intel_screen * screen) static
References intel_screen::bufmgr, and TIMESTAMP.
Referenced by intelInitScreen2().
intel_dri2_flush()
static void intel_dri2_flush (__DRIdrawable * drawable) static
Provides compatibility with loaders that only support the older (version 1-3) flush interface.
That includes libGL up to Mesa 9.0, and the X Server at least up to 1.13.
References intel_dri2_flush_with_flags().
intel_dri2_flush_with_flags()
static void intel_dri2_flush_with_flags (__DRIcontext * cPriv, __DRIdrawable * dPriv, unsigned flags, enum __DRI2throttleReason reason) static
References brw_context::ctx, FLUSH_VERTICES, intel_batchbuffer_flush, intel_resolve_for_dri2_flush(), brw_context::need_flush_throttle, and brw_context::need_swap_throttle.
Referenced by intel_dri2_flush().
intel_dup_image()
static __DRIimage* intel_dup_image (__DRIimage * orig_image, void * loaderPrivate) static
intel_from_planar()
static __DRIimage* intel_from_planar (__DRIimage * parent, int plane, void * loaderPrivate) static
References _mesa_warning(), intel_image_format::buffer_index, intel_image_format::dri_format, intel_image_format::height_shift, intel_allocate_image(), intel_image_warn_if_unaligned(), intel_image_format::nplanes, intel_image_format::planes, and intel_image_format::width_shift.
intel_get_boolean()
static bool intel_get_boolean (struct intel_screen * screen, int param) static
References intel_get_param().
Referenced by intel_init_bufmgr(), and intelInitScreen2().
intel_get_integer()
static int intel_get_integer (struct intel_screen * screen, int param) static
References intel_get_param().
Referenced by intelInitScreen2().
intel_get_param()
static int intel_get_param (struct intel_screen * screen, int param, int * value) static
References _mesa_warning(), intel_screen::driScrnPriv, and ret().
Referenced by intel_detect_sseu(), intel_get_boolean(), intel_get_integer(), and intelInitScreen2().
intel_image_format_lookup()
static struct intel_image_format* intel_image_format_lookup (int fourcc) static
Referenced by intel_create_image_from_dma_bufs(), intel_create_image_from_fds(), and intel_create_image_from_names().
intel_image_warn_if_unaligned()
static void intel_image_warn_if_unaligned (__DRIimage * image, const char * func) static
References _mesa_warning(), and swizzle().
Referenced by intel_create_image_from_fds(), and intel_from_planar().
intel_init_bufmgr()
static bool intel_init_bufmgr (struct intel_screen * screen) static
References BATCH_SZ, intel_screen::bufmgr, intel_screen::driScrnPriv, intel_get_boolean(), and intel_screen::no_hw.
Referenced by intelInitScreen2().
intel_lookup_fourcc()
static boolean intel_lookup_fourcc (int dri_format, int * fourcc) static
References intel_image_format::fourcc, and intel_image_format::planes.
Referenced by intel_query_image().
intel_query_image()
static GLboolean intel_query_image (__DRIimage * image, int attrib, int * value) static
References intel_lookup_fourcc().
intel_screen_make_configs()
static __DRIconfig** intel_screen_make_configs (__DRIscreen * dri_screen) static
References intel_screen::devinfo, GLX_NONE, GLX_SWAP_UNDEFINED_OML, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_UNORM, and MESA_FORMAT_B8G8R8X8_UNORM.
Referenced by intelInitScreen2().
intel_setup_image_from_mipmap_tree()
static void intel_setup_image_from_mipmap_tree (struct brw_context * brw, __DRIimage * image, struct intel_mipmap_tree * mt, GLuint level, GLuint zoffset) static
Sets up a DRIImage structure to point to a slice out of a miptree.
References intel_miptree_get_tile_offsets(), and intel_miptree_make_shareable().
Referenced by intel_create_image_from_texture().
intel_supported_msaa_modes()
const int* intel_supported_msaa_modes (const struct intel_screen * screen)
Return array of MSAA modes supported by the hardware.
The array is zero-terminated and sorted in decreasing order.
References intel_screen::devinfo.
Referenced by brw_initialize_context_constants(), and intel_quantize_num_samples().
intel_validate_usage()
static GLboolean intel_validate_usage (__DRIimage * image, unsigned int use) static
intelAllocateBuffer()
static __DRIbuffer* intelAllocateBuffer (__DRIscreen * dri_screen, unsigned attachment, unsigned format, int width, int height) static
References intel_buffer::base, intel_buffer::bo, and intel_screen::bufmgr.
intelCreateBuffer()
static GLboolean intelCreateBuffer (__DRIscreen * dri_screen, __DRIdrawable * driDrawPriv, const struct gl_config * mesaVis, GLboolean isPixmap) static
This is called when we need to set up GL rendering to a new X window.
References _mesa_add_renderbuffer(), _mesa_initialize_window_framebuffer(), _swrast_add_soft_renderbuffers(), gl_config::accumRedBits, gl_config::alphaBits, swrast_renderbuffer::Base, intel_renderbuffer::Base, BUFFER_BACK_LEFT, BUFFER_DEPTH, BUFFER_FRONT_LEFT, BUFFER_STENCIL, CALLOC_STRUCT, gl_config::depthBits, intel_screen::devinfo, gl_config::doubleBufferMode, intel_create_private_renderbuffer(), intel_create_renderbuffer(), intel_quantize_num_samples(), MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_R5G6B5_UNORM, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z_UNORM16, gl_config::redBits, gl_config::redMask, gl_config::samples, gl_config::sRGBCapable, gl_config::stencilBits, gl_framebuffer::Visual, and intel_screen::winsys_msaa_samples_override.
intelDestroyBuffer()
static void intelDestroyBuffer (__DRIdrawable * driDrawPriv) static
intelDestroyScreen()
static void intelDestroyScreen (__DRIscreen * sPriv) static
References intel_screen::bufmgr, and intel_screen::optionCache.
intelInitScreen2()
static const __DRIconfig** intelInitScreen2 (__DRIscreen * dri_screen) static
This is the driver specific part of the createNewScreen entry point.
Called when using DRI2.
Returns
the struct gl_config supported by this driver
References brw_config_options, intel_screen::bufmgr, intel_screen::cmd_parser_version, intel_screen::compiler, intel_screen::deviceID, intel_screen::devinfo, intel_screen::driScrnPriv, intel_screen::has_context_reset_notification, intel_screen::has_exec_fence, intel_screen::hw_has_swizzling, intel_screen::hw_has_timestamp, intel_detect_pipelined_so(), intel_detect_sseu(), intel_detect_swizzling(), intel_detect_timestamp(), intel_get_boolean(), intel_get_integer(), intel_get_param(), intel_init_bufmgr(), intel_quantize_num_samples(), intel_screen_make_configs(), intelRobustScreenExtensions, KERNEL_ALLOWS_COMPUTE_DISPATCH, KERNEL_ALLOWS_HSW_SCRATCH1_AND_ROW_CHICKEN3, KERNEL_ALLOWS_MI_MATH_AND_LRR, KERNEL_ALLOWS_PREDICATE_WRITES, KERNEL_ALLOWS_SOL_OFFSET_WRITES, intel_screen::kernel_features, intel_screen::max_gtt_map_object_size, intel_screen::optionCache, intel_screen::program_id, ret(), screenExtensions, set_max_gl_versions(), shader_debug_log_mesa(), shader_perf_log_mesa(), intel_screen::subslice_total, and intel_screen::winsys_msaa_samples_override.
intelReleaseBuffer()
static void intelReleaseBuffer (__DRIscreen * dri_screen, __DRIbuffer * buffer) static
References intel_buffer::bo.
select_best_modifier()
static uint64_t select_best_modifier (struct gen_device_info * devinfo, const uint64_t * modifiers, const unsigned count) static
References DRM_FORMAT_MOD_INVALID, DRM_FORMAT_MOD_LINEAR, MODIFIER_PRIORITY_INVALID, MODIFIER_PRIORITY_LINEAR, MODIFIER_PRIORITY_X, MODIFIER_PRIORITY_Y, and priority_to_modifier.
Referenced by intel_create_image_common().
set_max_gl_versions()
static void set_max_gl_versions (struct intel_screen * screen) static
References can_do_compute_dispatch(), can_do_mi_math_and_lrr(), can_do_pipelined_register_writes(), intel_screen::devinfo, and intel_screen::driScrnPriv.
Referenced by intelInitScreen2().
shader_debug_log_mesa()
static void shader_debug_log_mesa (void * data, const char * fmt, ...) static
References _mesa_gl_vdebug(), brw_context::ctx, GLuint, MESA_DEBUG_SEVERITY_NOTIFICATION, MESA_DEBUG_SOURCE_SHADER_COMPILER, and MESA_DEBUG_TYPE_OTHER.
Referenced by intelInitScreen2().
shader_perf_log_mesa()
static void shader_perf_log_mesa (void * data, const char * fmt, ...) static
References _mesa_gl_vdebug(), brw_context::ctx, GLuint, MESA_DEBUG_SEVERITY_MEDIUM, MESA_DEBUG_SOURCE_SHADER_COMPILER, MESA_DEBUG_TYPE_PERFORMANCE, and brw_context::perf_debug.
Referenced by intelInitScreen2().
Variable Documentation
brw_config_options
const __DRIconfigOptionsExtension brw_config_options static
Referenced by intelInitScreen2().
brw_driver_api
const struct __DriverAPIRec brw_driver_api static
Initial value:
= {
   .InitScreen           = intelInitScreen2,
   .DestroyScreen        = intelDestroyScreen,
   .CreateContext        = brwCreateContext,
   .DestroyContext       = intelDestroyContext,
   .CreateBuffer         = intelCreateBuffer,
   .DestroyBuffer        = intelDestroyBuffer,
   .MakeCurrent          = intelMakeCurrent,
   .UnbindContext        = intelUnbindContext,
   .AllocateBuffer       = intelAllocateBuffer,
   .ReleaseBuffer        = intelReleaseBuffer
}
Referenced by __driDriverGetExtensions_i965().
brw_driver_extensions
const __DRIextension* brw_driver_extensions[] static
Initial value:
= {
    &driCoreExtension.base,
    &driImageDriverExtension.base,
    &driDRI2Extension.base,
    &brw_vtable.base,
    &brw_config_options.base,
    NULL
}
Referenced by __driDriverGetExtensions_i965().
brw_vtable
const struct __DRIDriverVtableExtensionRec brw_vtable static
Initial value:
= {
   .base = { __DRI_DRIVER_VTABLE, 1 },
   .vtable = &brw_driver_api,
}
dri2Robustness
const __DRIrobustnessExtension dri2Robustness static
Initial value:
= {
   .base = { __DRI2_ROBUSTNESS, 1 }
}
intel_image_formats
struct intel_image_format intel_image_formats[] static
intelFlushExtension
const struct __DRI2flushExtensionRec intelFlushExtension static
Initial value:
= {
    .base = { __DRI2_FLUSH, 4 },
    .flush              = intel_dri2_flush,
    .invalidate         = dri2InvalidateDrawable,
    .flush_with_flags   = intel_dri2_flush_with_flags,
}
intelImageExtension
const __DRIimageExtension intelImageExtension static
Initial value:
= {
    .base = { __DRI_IMAGE, 14 },
    .createImageFromName                = intel_create_image_from_name,
    .createImageFromRenderbuffer        = intel_create_image_from_renderbuffer,
    .destroyImage                       = intel_destroy_image,
    .createImage                        = intel_create_image,
    .queryImage                         = intel_query_image,
    .dupImage                           = intel_dup_image,
    .validateUsage                      = intel_validate_usage,
    .createImageFromNames               = intel_create_image_from_names,
    .fromPlanar                         = intel_from_planar,
    .createImageFromTexture             = intel_create_image_from_texture,
    .createImageFromFds                 = intel_create_image_from_fds,
    .createImageFromDmaBufs             = intel_create_image_from_dma_bufs,
    .blitImage                          = NULL,
    .getCapabilities                    = NULL,
    .mapImage                           = NULL,
    .unmapImage                         = NULL,
    .createImageWithModifiers           = intel_create_image_with_modifiers,
}
intelRendererQueryExtension
const __DRI2rendererQueryExtension intelRendererQueryExtension static
Initial value:
= {
   .base = { __DRI2_RENDERER_QUERY, 1 },
   .queryInteger = brw_query_renderer_integer,
   .queryString = brw_query_renderer_string
}
intelRobustScreenExtensions
const __DRIextension* intelRobustScreenExtensions[] static
Initial value:
= {
    &intelTexBufferExtension.base,
    &intelFenceExtension.base,
    &intelFlushExtension.base,
    &intelImageExtension.base,
    &intelRendererQueryExtension.base,
    &dri2ConfigQueryExtension.base,
    &dri2Robustness.base,
    NULL
}
Referenced by intelInitScreen2().
intelTexBufferExtension
const __DRItexBufferExtension intelTexBufferExtension static
Initial value:
= {
   .base = { __DRI_TEX_BUFFER, 3 },
   .setTexBuffer        = intelSetTexBuffer,
   .setTexBuffer2       = intelSetTexBuffer2,
   .releaseTexBuffer    = NULL,
}
priority_to_modifier
const uint64_t priority_to_modifier[]
Initial value:
= {
   [MODIFIER_PRIORITY_INVALID] = DRM_FORMAT_MOD_INVALID,
   [MODIFIER_PRIORITY_LINEAR] = DRM_FORMAT_MOD_LINEAR,
   [MODIFIER_PRIORITY_X] = I915_FORMAT_MOD_X_TILED,
   [MODIFIER_PRIORITY_Y] = I915_FORMAT_MOD_Y_TILED,
}
Referenced by select_best_modifier().
screenExtensions
const __DRIextension* screenExtensions[] static
Initial value:
= {
    &intelTexBufferExtension.base,
    &intelFenceExtension.base,
    &intelFlushExtension.base,
    &intelImageExtension.base,
    &intelRendererQueryExtension.base,
    &dri2ConfigQueryExtension.base,
    NULL
}
Referenced by intelInitScreen2().