Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_upload.c File Reference
Batched upload via BOs.
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/bufferobj.h"
#include "brw_context.h"
#include "intel_blit.h"
#include "intel_buffer_objects.h"
#include "intel_batchbuffer.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
Macros
#define INTEL_UPLOAD_SIZE (64*1024)
Functions
void intel_upload_finish (struct brw_context *brw)
void * intel_upload_space (struct brw_context *brw, uint32_t size, uint32_t alignment, drm_intel_bo **out_bo, uint32_t *out_offset)
Interface for getting memory for uploading streamed data to the GPU.
void intel_upload_data (struct brw_context *brw, const void *data, uint32_t size, uint32_t alignment, drm_intel_bo **out_bo, uint32_t *out_offset)
Handy interface to upload some data to temporary GPU memory quickly.
Detailed Description
Batched upload via BOs.
Macro Definition Documentation
INTEL_UPLOAD_SIZE
#define INTEL_UPLOAD_SIZE (64*1024)
Referenced by intel_upload_space().
Function Documentation
intel_upload_data()
void intel_upload_data (struct brw_context * brw, const void * data, uint32_t size, uint32_t alignment, drm_intel_bo ** out_bo, uint32_t * out_offset)
Handy interface to upload some data to temporary GPU memory quickly.
References to this memory should not be retained across batch flushes.
References intel_upload_space().
Referenced by brw_prepare_shader_draw_parameters(), brw_upload_cs_work_groups_surface(), brw_upload_indices(), and copy_array_to_vbo_array().
intel_upload_finish()
void intel_upload_finish (struct brw_context * brw)
References brw_context::bo, brw_context::next_offset, and brw_context::upload.
Referenced by _intel_batchbuffer_flush_fence(), and intel_upload_space().
intel_upload_space()
void* intel_upload_space (struct brw_context * brw, uint32_t size, uint32_t alignment, drm_intel_bo ** out_bo, uint32_t * out_offset)
Interface for getting memory for uploading streamed data to the GPU.
In most cases, streamed data (for GPU state structures, for example) is uploaded through brw_state_batch(), since that interface allows relocations from the streamed space returned to other BOs. However, that interface has the restriction that the amount of space allocated has to be "small" (see estimated_max_prim_size in brw_draw.c).
This interface, on the other hand, is able to handle arbitrary sized allocation requests, though it will batch small allocations into the same BO for efficiency and reduced memory footprint.
Note
The returned pointer is valid only until intel_upload_finish(), which will happen at batch flush or the next intel_upload_space()/intel_upload_data().
Parameters
out_bo Pointer to a BO, which must point to a valid BO or NULL on entry, and will have a reference to the new BO containing the state on return.
out_offset Offset within the buffer object that the data will land.
References brw_context::bo, brw_context::bufmgr, brw_context::has_llc, intel_upload_finish(), INTEL_UPLOAD_SIZE, brw_context::next_offset, and brw_context::upload.
Referenced by brw_upload_constant_buffer(), brw_upload_pull_constants(), copy_array_to_vbo_array(), and intel_upload_data().