Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_buffer_objects.c File Reference
This provides core GL buffer object functionality.
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/bufferobj.h"
#include "brw_context.h"
#include "intel_blit.h"
#include "intel_buffer_objects.h"
#include "intel_batchbuffer.h"
Functions
int brw_bo_map (struct brw_context *brw, drm_intel_bo *bo, int write_enable, const char *bo_name)
Map a buffer object; issue performance warnings if mapping causes stalls.
int brw_bo_map_gtt (struct brw_context *brw, drm_intel_bo *bo, const char *bo_name)
static void mark_buffer_gpu_usage (struct intel_buffer_object *intel_obj, uint32_t offset, uint32_t size)
static void mark_buffer_inactive (struct intel_buffer_object *intel_obj)
static void alloc_buffer_object (struct brw_context *brw, struct intel_buffer_object *intel_obj)
Allocates a new drm_intel_bo to store the data for the buffer object.
static void release_buffer (struct intel_buffer_object *intel_obj)
static struct gl_buffer_object * brw_new_buffer_object (struct gl_context *ctx, GLuint name)
The NewBufferObject() driver hook.
static void brw_delete_buffer (struct gl_context *ctx, struct gl_buffer_object *obj)
The DeleteBuffer() driver hook.
static GLboolean brw_buffer_data (struct gl_context *ctx, GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage, GLbitfield storageFlags, struct gl_buffer_object *obj)
The BufferData() driver hook.
static void brw_buffer_subdata (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data, struct gl_buffer_object *obj)
The BufferSubData() driver hook.
static void brw_get_buffer_subdata (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *obj)
The GetBufferSubData() driver hook.
static void * brw_map_buffer_range (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *obj, gl_map_buffer_index index)
The MapBufferRange() driver hook.
static void brw_flush_mapped_buffer_range (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj, gl_map_buffer_index index)
The FlushMappedBufferRange() driver hook.
static GLboolean brw_unmap_buffer (struct gl_context *ctx, struct gl_buffer_object *obj, gl_map_buffer_index index)
The UnmapBuffer() driver hook.
drm_intel_bo * intel_bufferobj_buffer (struct brw_context *brw, struct intel_buffer_object *intel_obj, uint32_t offset, uint32_t size)
Gets a pointer to the object's BO, and marks the given range as being used on the GPU.
static void brw_copy_buffer_subdata (struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr read_offset, GLintptr write_offset, GLsizeiptr size)
The CopyBufferSubData() driver hook.
void intelInitBufferObjectFuncs (struct dd_function_table *functions)
Detailed Description
This provides core GL buffer object functionality.
Function Documentation
alloc_buffer_object()
static void alloc_buffer_object (struct brw_context * brw, struct intel_buffer_object * intel_obj) static
Allocates a new drm_intel_bo to store the data for the buffer object.
References intel_buffer_object::Base, BRW_NEW_ATOMIC_BUFFER, BRW_NEW_TEXTURE_BUFFER, BRW_NEW_UNIFORM_BUFFER, intel_buffer_object::buffer, brw_context::bufmgr, brw_context::ctx, mark_buffer_inactive(), gl_context::NewDriverState, gl_buffer_object::Size, USAGE_ATOMIC_COUNTER_BUFFER, USAGE_SHADER_STORAGE_BUFFER, USAGE_TEXTURE_BUFFER, USAGE_UNIFORM_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by brw_buffer_data(), brw_buffer_subdata(), brw_map_buffer_range(), and intel_bufferobj_buffer().
brw_bo_map()
int brw_bo_map (struct brw_context * brw, drm_intel_bo * bo, int write_enable, const char * bo_name)
Map a buffer object; issue performance warnings if mapping causes stalls.
This matches the drm_intel_bo_map API, but takes an additional human-readable name for the buffer object to use in the performance debug message.
References get_time(), brw_context::perf_debug, and ret().
Referenced by brw_get_index_type(), brw_map_buffer_range(), gen6_queryobj_get_results(), intel_gettexsubimage_tiled_memcpy(), intel_miptree_map_raw(), intel_readpixels_tiled_memcpy(), and intel_texsubimage_tiled_memcpy().
brw_bo_map_gtt()
int brw_bo_map_gtt (struct brw_context * brw, drm_intel_bo * bo, const char * bo_name)
References get_time(), brw_context::perf_debug, and ret().
Referenced by brw_get_index_type(), intel_miptree_init_mcs(), and intel_miptree_map_raw().
brw_buffer_data()
static GLboolean brw_buffer_data (struct gl_context * ctx, GLenum target, GLsizeiptrARB size, const GLvoid * data, GLenum usage, GLbitfield storageFlags, struct gl_buffer_object * obj) static
The BufferData() driver hook.
Implements glBufferData(), which recreates a buffer object's data store and populates it with the given data, if present.
Any data that was previously stored in the buffer object is lost.
Returns
true for success, false if out of memory
References alloc_buffer_object(), intel_buffer_object::Base, brw_context(), intel_buffer_object::buffer, intel_buffer_object(), MAP_INTERNAL, MAP_USER, gl_buffer_object::Mappings, gl_buffer_mapping::Pointer, release_buffer(), gl_buffer_object::Size, gl_buffer_object::StorageFlags, gl_buffer_object::Usage, and void.
Referenced by intelInitBufferObjectFuncs().
brw_buffer_subdata()
static void brw_buffer_subdata (struct gl_context * ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid * data, struct gl_buffer_object * obj) static
The BufferSubData() driver hook.
Implements glBufferSubData(), which replaces a portion of the data in a buffer object.
If the data range specified by (size + offset) extends beyond the end of the buffer or if data is NULL, no copy is performed.
References alloc_buffer_object(), intel_buffer_object::Base, brw_context::batch, intel_batchbuffer::bo, brw_context(), intel_buffer_object::buffer, brw_context::bufmgr, intel_buffer_object::gpu_active_end, intel_buffer_object::gpu_active_start, brw_context::has_llc, intel_batchbuffer_flush, intel_buffer_object(), intel_emit_linear_blit(), mark_buffer_inactive(), intel_buffer_object::prefer_stall_to_blit, and gl_buffer_object::Size.
Referenced by intelInitBufferObjectFuncs().
brw_copy_buffer_subdata()
static void brw_copy_buffer_subdata (struct gl_context * ctx, struct gl_buffer_object * src, struct gl_buffer_object * dst, GLintptr read_offset, GLintptr write_offset, GLsizeiptr size) static
The CopyBufferSubData() driver hook.
Implements glCopyBufferSubData(), which copies a portion of one buffer object's data to another. Independent source and destination offsets are allowed.
References brw_context(), brw_emit_mi_flush(), intel_buffer_object(), intel_bufferobj_buffer(), and intel_emit_linear_blit().
Referenced by intelInitBufferObjectFuncs().
brw_delete_buffer()
static void brw_delete_buffer (struct gl_context * ctx, struct gl_buffer_object * obj) static
The DeleteBuffer() driver hook.
Deletes a single OpenGL buffer object. Used by glDeleteBuffers().
References _mesa_buffer_unmap_all_mappings(), _mesa_delete_buffer_object(), intel_buffer_object::buffer, and intel_buffer_object().
Referenced by intelInitBufferObjectFuncs().
brw_flush_mapped_buffer_range()
static void brw_flush_mapped_buffer_range (struct gl_context * ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object * obj, gl_map_buffer_index index) static
The FlushMappedBufferRange() driver hook.
Implements glFlushMappedBufferRange(), which signifies that modifications have been made to a range of a mapped buffer, and it should be flushed.
This is only used for buffers mapped with GL_MAP_FLUSH_EXPLICIT_BIT.
Ideally we'd use a BO to avoid taking up cache space for the temporary data, but FlushMappedBufferRange may be followed by further writes to the pointer, so we would have to re-map after emitting our blit, which would defeat the point.
References gl_buffer_mapping::AccessFlags, brw_context(), intel_buffer_object::buffer, intel_buffer_object(), intel_emit_linear_blit(), intel_buffer_object::map_extra, gl_buffer_object::Mappings, mark_buffer_gpu_usage(), gl_buffer_mapping::Offset, and intel_buffer_object::range_map_bo.
Referenced by intelInitBufferObjectFuncs().
brw_get_buffer_subdata()
static void brw_get_buffer_subdata (struct gl_context * ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid * data, struct gl_buffer_object * obj) static
The GetBufferSubData() driver hook.
Implements glGetBufferSubData(), which copies a subrange of a buffer object into user memory.
References brw_context::batch, intel_batchbuffer::bo, brw_context(), intel_buffer_object::buffer, intel_batchbuffer_flush, intel_buffer_object(), and mark_buffer_inactive().
Referenced by intelInitBufferObjectFuncs().
brw_map_buffer_range()
static void* brw_map_buffer_range (struct gl_context * ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object * obj, gl_map_buffer_index index) static
The MapBufferRange() driver hook.
This implements both glMapBufferRange() and glMapBuffer().
The goal of this extension is to allow apps to accumulate their rendering at the same time as they accumulate their buffer object. Without it, you'd end up blocking on execution of rendering every time you mapped the buffer to put new data in.
We support it in 3 ways: If unsynchronized, then don't bother flushing the batchbuffer before mapping the buffer, which can save blocking in many cases. If we would still block, and they allow the whole buffer to be invalidated, then just allocate a new buffer to replace the old one. If not, and we'd block, and they allow the subrange of the buffer to be invalidated, then we can make a new little BO, let them write into that, and blit it into the real BO at unmap time.
References gl_buffer_mapping::AccessFlags, alloc_buffer_object(), brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_context(), intel_buffer_object::buffer, brw_context::bufmgr, gl_context::Const, brw_context::has_llc, intel_batchbuffer_flush, intel_buffer_object(), gl_buffer_mapping::Length, intel_buffer_object::map_extra, gl_buffer_object::Mappings, mark_buffer_inactive(), gl_constants::MinMapBufferAlignment, gl_buffer_mapping::Offset, brw_context::perf_debug, gl_buffer_mapping::Pointer, and intel_buffer_object::range_map_bo.
Referenced by intelInitBufferObjectFuncs().
brw_new_buffer_object()
static struct gl_buffer_object* brw_new_buffer_object (struct gl_context * ctx, GLuint name) static
The NewBufferObject() driver hook.
Allocates a new intel_buffer_object structure and initializes it.
There is some duplication between mesa's bufferobjects and our bufmgr buffers. Both have an integer handle and a hashtable to lookup an opaque structure. It would be nice if the handles and internal structure where somehow shared.
References _mesa_error_no_memory(), _mesa_initialize_buffer_object(), intel_buffer_object::Base, intel_buffer_object::buffer, and CALLOC_STRUCT.
Referenced by intelInitBufferObjectFuncs().
brw_unmap_buffer()
static GLboolean brw_unmap_buffer (struct gl_context * ctx, struct gl_buffer_object * obj, gl_map_buffer_index index) static
The UnmapBuffer() driver hook.
Implements glUnmapBuffer().
References gl_buffer_mapping::AccessFlags, brw_context(), brw_emit_mi_flush(), intel_buffer_object::buffer, intel_buffer_object(), intel_emit_linear_blit(), gl_buffer_mapping::Length, intel_buffer_object::map_extra, gl_buffer_object::Mappings, mark_buffer_gpu_usage(), gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, and intel_buffer_object::range_map_bo.
Referenced by intelInitBufferObjectFuncs().
intel_bufferobj_buffer()
drm_intel_bo* intel_bufferobj_buffer (struct brw_context * brw, struct intel_buffer_object * intel_obj, uint32_t offset, uint32_t size)
Gets a pointer to the object's BO, and marks the given range as being used on the GPU.
Anywhere that uses buffer objects in the pipeline should be using this to mark the range of the buffer that is being accessed by the pipeline.
References alloc_buffer_object(), intel_buffer_object::buffer, and mark_buffer_gpu_usage().
Referenced by brw_copy_buffer_subdata(), brw_dispatch_compute_indirect(), brw_emit_prim(), brw_prepare_vertices(), brw_update_buffer_texture_surface(), brw_update_sol_surface(), brw_upload_abo_surfaces(), brw_upload_indices(), brw_upload_ubo_surfaces(), do_blit_drawpixels(), gen8_upload_3dstate_so_buffers(), intel_set_texture_storage_for_buffer_object(), and upload_3dstate_so_buffers().
intelInitBufferObjectFuncs()
void intelInitBufferObjectFuncs (struct dd_function_table * functions)
References brw_buffer_data(), brw_buffer_subdata(), brw_copy_buffer_subdata(), brw_delete_buffer(), brw_flush_mapped_buffer_range(), brw_get_buffer_subdata(), brw_map_buffer_range(), brw_new_buffer_object(), brw_unmap_buffer(), dd_function_table::BufferData, dd_function_table::BufferSubData, dd_function_table::CopyBufferSubData, dd_function_table::DeleteBuffer, dd_function_table::FlushMappedBufferRange, dd_function_table::GetBufferSubData, dd_function_table::MapBufferRange, dd_function_table::NewBufferObject, and dd_function_table::UnmapBuffer.
Referenced by brw_init_driver_functions().
mark_buffer_gpu_usage()
static void mark_buffer_gpu_usage (struct intel_buffer_object * intel_obj, uint32_t offset, uint32_t size) static
References intel_buffer_object::gpu_active_end, and intel_buffer_object::gpu_active_start.
Referenced by brw_flush_mapped_buffer_range(), brw_unmap_buffer(), and intel_bufferobj_buffer().
mark_buffer_inactive()
static void mark_buffer_inactive (struct intel_buffer_object * intel_obj) static
References intel_buffer_object::gpu_active_end, and intel_buffer_object::gpu_active_start.
Referenced by alloc_buffer_object(), brw_buffer_subdata(), brw_get_buffer_subdata(), and brw_map_buffer_range().
release_buffer()
static void release_buffer (struct intel_buffer_object * intel_obj) static
References intel_buffer_object::buffer.
Referenced by brw_buffer_data().