Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_screen.h File Reference
#include <stdbool.h>
#include <sys/time.h>
#include <GL/internal/dri_interface.h>
#include "dri_util.h"
#include "intel_bufmgr.h"
#include "common/gen_device_info.h"
#include "i915_drm.h"
#include "xmlconfig.h"
Data Structures
struct intel_screen
Macros
#define KERNEL_ALLOWS_SOL_OFFSET_WRITES (1<<0)
#define KERNEL_ALLOWS_PREDICATE_WRITES (1<<1)
#define KERNEL_ALLOWS_MI_MATH_AND_LRR (1<<2)
#define KERNEL_ALLOWS_HSW_SCRATCH1_AND_ROW_CHICKEN3 (1<<3)
#define KERNEL_ALLOWS_COMPUTE_DISPATCH (1<<4)
Functions
void intelDestroyContext (__DRIcontext *driContextPriv)
GLboolean intelUnbindContext (__DRIcontext *driContextPriv)
PUBLIC const __DRIextension ** __driDriverGetExtensions_i965 (void)
GLboolean intelMakeCurrent (__DRIcontext *driContextPriv, __DRIdrawable *driDrawPriv, __DRIdrawable *driReadPriv)
double get_time (void)
For debugging purposes, this returns a time in seconds.
const int * intel_supported_msaa_modes (const struct intel_screen *screen)
Return array of MSAA modes supported by the hardware.
static bool can_do_pipelined_register_writes (const struct intel_screen *screen)
static bool can_do_hsw_l3_atomics (const struct intel_screen *screen)
static bool can_do_mi_math_and_lrr (const struct intel_screen *screen)
static bool can_do_compute_dispatch (const struct intel_screen *screen)
static bool can_do_predicate_writes (const struct intel_screen *screen)
Variables
const __DRI2fenceExtension intelFenceExtension
Macro Definition Documentation
KERNEL_ALLOWS_COMPUTE_DISPATCH
#define KERNEL_ALLOWS_COMPUTE_DISPATCH (1<<4)
Referenced by can_do_compute_dispatch(), and intelInitScreen2().
KERNEL_ALLOWS_HSW_SCRATCH1_AND_ROW_CHICKEN3
#define KERNEL_ALLOWS_HSW_SCRATCH1_AND_ROW_CHICKEN3 (1<<3)
Referenced by can_do_hsw_l3_atomics(), and intelInitScreen2().
KERNEL_ALLOWS_MI_MATH_AND_LRR
#define KERNEL_ALLOWS_MI_MATH_AND_LRR (1<<2)
Referenced by can_do_mi_math_and_lrr(), and intelInitScreen2().
KERNEL_ALLOWS_PREDICATE_WRITES
#define KERNEL_ALLOWS_PREDICATE_WRITES (1<<1)
Referenced by can_do_predicate_writes(), and intelInitScreen2().
KERNEL_ALLOWS_SOL_OFFSET_WRITES
#define KERNEL_ALLOWS_SOL_OFFSET_WRITES (1<<0)
Referenced by can_do_pipelined_register_writes(), and intelInitScreen2().
Function Documentation
__driDriverGetExtensions_i965()
PUBLIC const __DRIextension** __driDriverGetExtensions_i965 (void)
References brw_driver_api, and brw_driver_extensions.
can_do_compute_dispatch()
static bool can_do_compute_dispatch (const struct intel_screen * screen) inline static
References KERNEL_ALLOWS_COMPUTE_DISPATCH, and intel_screen::kernel_features.
Referenced by intelInitExtensions(), and set_max_gl_versions().
can_do_hsw_l3_atomics()
static bool can_do_hsw_l3_atomics (const struct intel_screen * screen) inline static
References KERNEL_ALLOWS_HSW_SCRATCH1_AND_ROW_CHICKEN3, and intel_screen::kernel_features.
Referenced by setup_l3_config().
can_do_mi_math_and_lrr()
static bool can_do_mi_math_and_lrr (const struct intel_screen * screen) inline static
References KERNEL_ALLOWS_MI_MATH_AND_LRR, and intel_screen::kernel_features.
Referenced by brw_begin_conditional_render(), brw_check_conditional_render(), brw_init_driver_functions(), brw_initialize_context_constants(), intelInitExtensions(), and set_max_gl_versions().
can_do_pipelined_register_writes()
static bool can_do_pipelined_register_writes (const struct intel_screen * screen) inline static
References KERNEL_ALLOWS_SOL_OFFSET_WRITES, and intel_screen::kernel_features.
Referenced by emit_l3_state(), gen7_begin_transform_feedback(), gen7_restore_default_l3_config(), intelInitExtensions(), and set_max_gl_versions().
can_do_predicate_writes()
static bool can_do_predicate_writes (const struct intel_screen * screen) inline static
References KERNEL_ALLOWS_PREDICATE_WRITES, and intel_screen::kernel_features.
Referenced by intelInitExtensions().
get_time()
double get_time (void)
For debugging purposes, this returns a time in seconds.
Referenced by brw_bo_map(), brw_bo_map_gtt(), brw_codegen_cs_prog(), brw_codegen_gs_prog(), brw_codegen_tcs_prog(), brw_codegen_tes_prog(), brw_codegen_vs_prog(), brw_codegen_wm_prog(), and brw_collect_and_report_shader_time().
intel_supported_msaa_modes()
const int* intel_supported_msaa_modes (const struct intel_screen * screen)
Return array of MSAA modes supported by the hardware.
The array is zero-terminated and sorted in decreasing order.
References intel_screen::devinfo.
Referenced by brw_initialize_context_constants(), and intel_quantize_num_samples().
intelDestroyContext()
void intelDestroyContext (__DRIcontext * driContextPriv)
References _mesa_free_context_data(), _swrast_DestroyContext(), _swsetup_DestroyContext(), _tnl_DestroyContext(), _vbo_DestroyContext(), brw_context::base, brw_context::batch, brw_context::blorp, brw_collect_and_report_shader_time(), brw_destroy_shader_time(), brw_destroy_state(), brw_draw_destroy(), brw_fini_pipe_control(), brw_context::ctx, brw_context::curbe, brw_context::curbe_bo, brw_context::gen, brw_context::gs, brw_context::hw_ctx, intel_batchbuffer_free(), brw_context::optionCache, brw_context::report_time, brw_stage_state::scratch_bo, brw_context::shader_time, gl_context::swrast_context, brw_context::tcs, brw_context::tes, brw_context::throttle_batch, brw_context::vs, and brw_context::wm.
Referenced by brwCreateContext().
intelMakeCurrent()
GLboolean intelMakeCurrent (__DRIcontext * driContextPriv, __DRIdrawable * driDrawPriv, __DRIdrawable * driReadPriv)
References _mesa_flush(), _mesa_get_incomplete_framebuffer(), _mesa_make_current(), brw_context(), brw_context::ctx, if(), intel_gles3_srgb_workaround(), intel_prepare_render(), and gl_context::ViewportInitialized.
intelUnbindContext()
GLboolean intelUnbindContext (__DRIcontext * driContextPriv)
References _mesa_make_current().
Variable Documentation
intelFenceExtension
const __DRI2fenceExtension intelFenceExtension