Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex_copy.c File Reference
#include "main/mtypes.h"
#include "main/enums.h"
#include "main/image.h"
#include "main/teximage.h"
#include "main/texobj.h"
#include "main/texstate.h"
#include "main/fbobject.h"
#include "drivers/common/meta.h"
#include "intel_screen.h"
#include "intel_mipmap_tree.h"
#include "intel_fbo.h"
#include "intel_tex.h"
#include "intel_blit.h"
#include "brw_context.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Functions
static bool intel_copy_texsubimage (struct brw_context *brw, struct intel_texture_image *intelImage, GLint dstx, GLint dsty, GLint slice, struct intel_renderbuffer *irb, GLint x, GLint y, GLsizei width, GLsizei height)
static void intelCopyTexSubImage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint slice, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height)
void intelInitTextureCopyImageFuncs (struct dd_function_table *functions)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Function Documentation
intel_copy_texsubimage()
static bool intel_copy_texsubimage (struct brw_context * brw, struct intel_texture_image * intelImage, GLint dstx, GLint dsty, GLint slice, struct intel_renderbuffer * irb, GLint x, GLint y, GLsizei width, GLsizei height) static
References gl_context::_ImageTransferState, swrast_renderbuffer::Base, swrast_texture_image::Base, intel_texture_image::base, intel_renderbuffer::Base, brw_context::ctx, gl_texture_image::Face, intel_miptree_blit(), intel_prepare_render(), gl_texture_image::InternalFormat, gl_texture_image::Level, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_renderbuffer::mt, intel_texture_image::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_renderbuffer::Name, gl_renderbuffer::NumSamples, gl_texture_image::NumSamples, ret(), and gl_texture_image::TexObject.
Referenced by intelCopyTexSubImage().
intelCopyTexSubImage()
static void intelCopyTexSubImage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint slice, struct gl_renderbuffer * rb, GLint x, GLint y, GLsizei width, GLsizei height) static
References brw_blorp_copytexsubimage(), brw_context(), intel_copy_texsubimage(), intel_renderbuffer(), intel_texture_image(), and brw_context::perf_debug.
Referenced by intelInitTextureCopyImageFuncs().
intelInitTextureCopyImageFuncs()
void intelInitTextureCopyImageFuncs (struct dd_function_table * functions)
References dd_function_table::CopyTexSubImage, and intelCopyTexSubImage().
Referenced by brw_init_driver_functions().