Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_pixel.c File Reference
#include "main/accum.h"
#include "main/enums.h"
#include "main/state.h"
#include "main/bufferobj.h"
#include "main/context.h"
#include "swrast/swrast.h"
#include "brw_context.h"
#include "intel_pixel.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Functions
static GLenum effective_func (GLenum func, bool src_alpha_is_one)
bool intel_check_blit_fragment_ops (struct gl_context *ctx, bool src_alpha_is_one)
Check if any fragment operations are in effect which might effect glDraw/CopyPixels.
void intelInitPixelFuncs (struct dd_function_table *functions)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Function Documentation
effective_func()
static GLenum effective_func (GLenum func, bool src_alpha_is_one) static
Referenced by intel_check_blit_fragment_ops().
intel_check_blit_fragment_ops()
bool intel_check_blit_fragment_ops (struct gl_context * ctx, bool src_alpha_is_one)
Check if any fragment operations are in effect which might effect glDraw/CopyPixels.
References gl_fragment_program_state::_Enabled, gl_stencil_attrib::_Enabled, gl_context::_ImageTransferState, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_update_state(), gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, gl_context::Color, gl_colorbuffer_attrib::ColorMask, DBG, gl_context::Depth, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, effective_func(), gl_fog_attrib::Enabled, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_context::Fog, gl_context::FragmentProgram, gl_context::NewState, gl_context::Pixel, gl_context::RenderMode, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, gl_context::Stencil, gl_depthbuffer_attrib::Test, gl_context::Texture, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by do_blit_bitmap(), and do_blit_drawpixels().
intelInitPixelFuncs()
void intelInitPixelFuncs (struct dd_function_table * functions)
References dd_function_table::Bitmap, dd_function_table::CopyPixels, dd_function_table::DrawPixels, intelBitmap(), intelCopyPixels(), intelDrawPixels(), intelReadPixels(), and dd_function_table::ReadPixels.
Referenced by brw_init_driver_functions().