Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_pixel_copy.c File Reference
#include "main/image.h"
#include "main/state.h"
#include "main/mtypes.h"
#include "main/condrender.h"
#include "main/fbobject.h"
#include "drivers/common/meta.h"
#include "brw_context.h"
#include "intel_buffers.h"
#include "intel_mipmap_tree.h"
#include "intel_pixel.h"
#include "intel_fbo.h"
#include "intel_blit.h"
#include "intel_batchbuffer.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Functions
static bool do_blit_copypixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint dstx, GLint dsty, GLenum type)
CopyPixels with the blitter.
void intelCopyPixels (struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint destx, GLint desty, GLenum type)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Function Documentation
do_blit_copypixels()
static bool do_blit_copypixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint dstx, GLint dsty, GLenum type) static
CopyPixels with the blitter.
Don't support zooming, pixel transfer, etc.
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_ColorReadBuffer, gl_stencil_attrib::_Enabled, gl_fragment_program_state::_Enabled, gl_context::_ImageTransferState, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_clip_to_region(), _mesa_update_state(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_colorbuffer_attrib::AlphaEnabled, gl_framebuffer::Attachment, gl_colorbuffer_attrib::BlendEnabled, brw_context(), BUFFER_DEPTH, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_query_state::CurrentOcclusionObject, DBG, gl_context::Depth, gl_context::DrawBuffer, gl_fog_attrib::Enabled, gl_context::Fog, gl_context::FragmentProgram, gl_framebuffer::Height, intel_batchbuffer_flush, intel_miptree_blit(), intel_prepare_render(), intel_renderbuffer(), gl_colorbuffer_attrib::LogicOp, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::Pixel, gl_context::Query, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_query_object::Result, gl_context::Stencil, gl_depthbuffer_attrib::Test, gl_context::Texture, gl_framebuffer::Width, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by intelCopyPixels().
intelCopyPixels()
void intelCopyPixels (struct gl_context * ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint destx, GLint desty, GLenum type)
References _mesa_check_conditional_render(), DBG, and do_blit_copypixels().
Referenced by intelInitPixelFuncs().