Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_batchbuffer.c File Reference
#include "intel_batchbuffer.h"
#include "intel_buffer_objects.h"
#include "intel_bufmgr.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "brw_state.h"
#include "common/gen_decoder.h"
#include "util/hash_table.h"
#include <xf86drm.h>
#include <i915_drm.h>
Functions
static void intel_batchbuffer_reset (struct intel_batchbuffer *batch, drm_intel_bufmgr *bufmgr, bool has_llc)
static bool uint_key_compare (const void *a, const void *b)
static uint32_t uint_key_hash (const void *key)
void intel_batchbuffer_init (struct intel_batchbuffer *batch, drm_intel_bufmgr *bufmgr, bool has_llc)
static void intel_batchbuffer_reset_and_clear_render_cache (struct brw_context *brw)
void intel_batchbuffer_save_state (struct brw_context *brw)
void intel_batchbuffer_reset_to_saved (struct brw_context *brw)
void intel_batchbuffer_free (struct intel_batchbuffer *batch)
void intel_batchbuffer_require_space (struct brw_context *brw, GLuint sz, enum brw_gpu_ring ring)
static void do_batch_dump (struct brw_context *brw)
static void brw_new_batch (struct brw_context *brw)
Called when starting a new batch buffer.
static void brw_finish_batch (struct brw_context *brw)
Called from intel_batchbuffer_flush before emitting MI_BATCHBUFFER_END and sending it off.
static void throttle (struct brw_context *brw)
static int do_flush_locked (struct brw_context *brw, int in_fence_fd, int *out_fence_fd)
int _intel_batchbuffer_flush_fence (struct brw_context *brw, int in_fence_fd, int *out_fence_fd, const char *file, int line)
The in_fence_fd is ignored if -1.
uint64_t intel_batchbuffer_reloc (struct intel_batchbuffer *batch, drm_intel_bo *buffer, uint32_t offset, uint32_t read_domains, uint32_t write_domain, uint32_t delta)
void intel_batchbuffer_data (struct brw_context *brw, const void *data, GLuint bytes, enum brw_gpu_ring ring)
static void load_sized_register_mem (struct brw_context *brw, uint32_t reg, drm_intel_bo *bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset, int size)
void brw_load_register_mem (struct brw_context *brw, uint32_t reg, drm_intel_bo *bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
intel_batchbuffer.c
void brw_load_register_mem64 (struct brw_context *brw, uint32_t reg, drm_intel_bo *bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
void brw_store_register_mem32 (struct brw_context *brw, drm_intel_bo *bo, uint32_t reg, uint32_t offset)
void brw_store_register_mem64 (struct brw_context *brw, drm_intel_bo *bo, uint32_t reg, uint32_t offset)
void brw_load_register_imm32 (struct brw_context *brw, uint32_t reg, uint32_t imm)
void brw_load_register_imm64 (struct brw_context *brw, uint32_t reg, uint64_t imm)
void brw_load_register_reg (struct brw_context *brw, uint32_t src, uint32_t dest)
void brw_load_register_reg64 (struct brw_context *brw, uint32_t src, uint32_t dest)
void brw_store_data_imm32 (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint32_t imm)
void brw_store_data_imm64 (struct brw_context *brw, drm_intel_bo *bo, uint32_t offset, uint64_t imm)
Function Documentation
_intel_batchbuffer_flush_fence()
int _intel_batchbuffer_flush_fence (struct brw_context * brw, int in_fence_fd, int * out_fence_fd, const char * file, int line)
The in_fence_fd is ignored if -1.
Otherwise this function takes ownership of the fd.
The out_fence_fd is ignored if NULL. Otherwise, the caller takes ownership of the returned fd.
References brw_context::batch, BATCH_SZ, intel_batchbuffer::bo, brw_finish_batch(), brw_new_batch(), do_flush_locked(), intel_batchbuffer_emit_dword(), intel_upload_finish(), MI_BATCH_BUFFER_END, MI_NOOP, brw_context::no_batch_wrap, intel_batchbuffer::reserved_space, ret(), intel_batchbuffer::state_batch_offset, brw_context::throttle_batch, and USED_BATCH.
brw_finish_batch()
static void brw_finish_batch (struct brw_context * brw) static
Called from intel_batchbuffer_flush before emitting MI_BATCHBUFFER_END and sending it off.
This function can emit state (say, to preserve registers that aren't saved between batches). All of this state MUST fit in the reserved space at the end of the batchbuffer. If you add more GPU state, increase the reserved space by updating the BATCH_RESERVED macro.
References _3DSTATE_CC_STATE_POINTERS, ADVANCE_BATCH, brw_context::batch, BEGIN_BATCH, brw_cache::bo_used_by_gpu, brw_emit_mi_flush(), brw_emit_pipe_control_flush(), brw_emit_query_end(), brw_context::cache, brw_context::cc, brw_context::gen, gen7_restore_default_l3_config(), brw_context::is_haswell, OUT_BATCH, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_RENDER_TARGET_FLUSH, RENDER_RING, intel_batchbuffer::ring, and brw_context::state_offset.
Referenced by _intel_batchbuffer_flush_fence().
brw_load_register_imm32()
void brw_load_register_imm32 (struct brw_context * brw, uint32_t reg, uint32_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_LOAD_REGISTER_IMM, and OUT_BATCH.
Referenced by shr_gpr0_by_2_bits(), and tally_prims_written().
brw_load_register_imm64()
void brw_load_register_imm64 (struct brw_context * brw, uint32_t reg, uint64_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_LOAD_REGISTER_IMM, and OUT_BATCH.
Referenced by calc_overflow_to_gpr0(), gpr0_to_bool(), keep_gpr0_lower_n_bits(), set_predicate(), and set_predicate_for_overflow_query().
brw_load_register_mem()
void brw_load_register_mem (struct brw_context * brw, uint32_t reg, drm_intel_bo * bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
intel_batchbuffer.c
References load_sized_register_mem().
Referenced by brw_emit_prim(), prepare_indirect_gpgpu_walker(), and tally_prims_written().
brw_load_register_mem64()
void brw_load_register_mem64 (struct brw_context * brw, uint32_t reg, drm_intel_bo * bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset)
References load_sized_register_mem().
Referenced by hsw_result_to_gpr0(), load_overflow_data_to_cs_gprs(), set_predicate(), set_predicate_for_occlusion_query(), and tally_prims_written().
brw_load_register_reg()
void brw_load_register_reg (struct brw_context * brw, uint32_t src, uint32_t dest)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, brw_context::is_haswell, MI_LOAD_REGISTER_REG, and OUT_BATCH.
Referenced by shr_gpr0_by_2_bits().
brw_load_register_reg64()
void brw_load_register_reg64 (struct brw_context * brw, uint32_t src, uint32_t dest)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, brw_context::is_haswell, MI_LOAD_REGISTER_REG, and OUT_BATCH.
Referenced by set_predicate_for_overflow_query(), and tally_prims_written().
brw_new_batch()
static void brw_new_batch (struct brw_context * brw) static
Called when starting a new batch buffer.
References brw_context::batch, intel_batchbuffer::bo, brw_collect_and_report_shader_time(), BRW_NEW_BATCH, BRW_NEW_CONTEXT, brw_context::ctx, brw_context::hw_ctx, brw_context::ib, intel_batchbuffer_reset_and_clear_render_cache(), gl_context::NewDriverState, and _mesa_index_buffer::type.
Referenced by _intel_batchbuffer_flush_fence().
brw_store_data_imm32()
void brw_store_data_imm32 (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint32_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_DATA_IMM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by store_query_result_imm().
brw_store_data_imm64()
void brw_store_data_imm64 (struct brw_context * brw, drm_intel_bo * bo, uint32_t offset, uint64_t imm)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_DATA_IMM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by hsw_begin_transform_feedback(), and store_query_result_imm().
brw_store_register_mem32()
void brw_store_register_mem32 (struct brw_context * brw, drm_intel_bo * bo, uint32_t reg, uint32_t offset)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_REGISTER_MEM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by tally_prims_written().
brw_store_register_mem64()
void brw_store_register_mem64 (struct brw_context * brw, drm_intel_bo * bo, uint32_t reg, uint32_t offset)
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, MI_STORE_REGISTER_MEM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by brw_save_primitives_written_counters(), emit_pipeline_stat(), save_prim_start_values(), snapshot_statistics_registers(), write_primitives_generated(), write_xfb_overflow_streams(), and write_xfb_primitives_written().
do_batch_dump()
static void do_batch_dump (struct brw_context * brw) static
Referenced by do_flush_locked(), and intel_batchbuffer_require_space().
do_flush_locked()
static int do_flush_locked (struct brw_context * brw, int in_fence_fd, int * out_fence_fd) static
References brw_context::batch, BLT_RING, intel_batchbuffer::bo, brw_check_for_reset(), gl_context::Const, brw_context::ctx, do_batch_dump(), brw_context::gen, brw_context::has_llc, brw_context::hw_ctx, intel_batchbuffer::map, intel_batchbuffer::needs_sol_reset, intel_screen::no_hw, RENDER_RING, gl_constants::ResetStrategy, ret(), intel_batchbuffer::ring, brw_context::screen, intel_batchbuffer::state_batch_offset, throttle(), and USED_BATCH.
Referenced by _intel_batchbuffer_flush_fence().
intel_batchbuffer_data()
void intel_batchbuffer_data (struct brw_context * brw, const void * data, GLuint bytes, enum brw_gpu_ring ring)
References brw_context::batch, intel_batchbuffer_require_space(), and intel_batchbuffer::map_next.
Referenced by intelEmitImmediateColorExpandBlit().
intel_batchbuffer_free()
void intel_batchbuffer_free (struct intel_batchbuffer * batch)
References intel_batchbuffer::bo, intel_batchbuffer::cpu_map, intel_batchbuffer::last_bo, and intel_batchbuffer::state_batch_sizes.
Referenced by intelDestroyContext().
intel_batchbuffer_init()
void intel_batchbuffer_init (struct intel_batchbuffer * batch, drm_intel_bufmgr * bufmgr, bool has_llc)
References BATCH_SZ, intel_batchbuffer::cpu_map, intel_batchbuffer_reset(), intel_batchbuffer::map, intel_batchbuffer::map_next, intel_batchbuffer::state_batch_sizes, uint_key_compare(), and uint_key_hash().
Referenced by brwCreateContext().
intel_batchbuffer_reloc()
uint64_t intel_batchbuffer_reloc (struct intel_batchbuffer * batch, drm_intel_bo * buffer, uint32_t offset, uint32_t read_domains, uint32_t write_domain, uint32_t delta)
References intel_batchbuffer::bo, ret(), and void.
Referenced by blorp_emit_reloc().
intel_batchbuffer_require_space()
void intel_batchbuffer_require_space (struct brw_context * brw, GLuint sz, enum brw_gpu_ring ring)
References _3DSTATE_BINDING_TABLE_POINTERS_DS, _3DSTATE_BINDING_TABLE_POINTERS_GS, _3DSTATE_BINDING_TABLE_POINTERS_HS, _3DSTATE_BINDING_TABLE_POINTERS_PS, _3DSTATE_BINDING_TABLE_POINTERS_VS, _3DSTATE_BLEND_STATE_POINTERS, _3DSTATE_CC_STATE_POINTERS, _3DSTATE_DEPTH_STENCIL_STATE_POINTERS, _3DSTATE_PIPELINED_POINTERS, _3DSTATE_SAMPLER_STATE_POINTERS_DS, _3DSTATE_SAMPLER_STATE_POINTERS_GS, _3DSTATE_SAMPLER_STATE_POINTERS_HS, _3DSTATE_SAMPLER_STATE_POINTERS_PS, _3DSTATE_SAMPLER_STATE_POINTERS_VS, _3DSTATE_SCISSOR_STATE_POINTERS, _3DSTATE_VIEWPORT_STATE_POINTERS, _3DSTATE_VIEWPORT_STATE_POINTERS_CC, _3DSTATE_VIEWPORT_STATE_POINTERS_SF_CL, brw_context::batch, BATCH_RESERVED, BATCH_SZ, intel_batchbuffer::bo, brw_state_batch_size(), intel_screen::devinfo, do_batch_dump(), brw_context::gen, intel_batchbuffer_flush, intel_batchbuffer_space(), intel_batchbuffer::map, NORMAL, RENDER_RING, ret(), intel_batchbuffer::ring, brw_context::screen, UNKNOWN_RING, and USED_BATCH.
Referenced by blorp_exec(), brw_dispatch_compute_common(), brw_try_draw_prims(), intel_batchbuffer_begin(), intel_batchbuffer_data(), intelEmitCopyBlit(), and intelEmitImmediateColorExpandBlit().
intel_batchbuffer_reset()
static void intel_batchbuffer_reset (struct intel_batchbuffer * batch, drm_intel_bufmgr * bufmgr, bool has_llc) static
References BATCH_RESERVED, BATCH_SZ, intel_batchbuffer::bo, intel_batchbuffer::last_bo, intel_batchbuffer::map, intel_batchbuffer::map_next, intel_batchbuffer::needs_sol_reset, intel_batchbuffer::reserved_space, intel_batchbuffer::ring, intel_batchbuffer::state_base_address_emitted, intel_batchbuffer::state_batch_offset, intel_batchbuffer::state_batch_sizes, and UNKNOWN_RING.
Referenced by intel_batchbuffer_init(), and intel_batchbuffer_reset_and_clear_render_cache().
intel_batchbuffer_reset_and_clear_render_cache()
static void intel_batchbuffer_reset_and_clear_render_cache (struct brw_context * brw) static
References brw_context::batch, brw_render_cache_set_clear(), brw_context::bufmgr, brw_context::has_llc, and intel_batchbuffer_reset().
Referenced by brw_new_batch().
intel_batchbuffer_reset_to_saved()
void intel_batchbuffer_reset_to_saved (struct brw_context * brw)
References brw_context::batch, intel_batchbuffer::bo, intel_batchbuffer::map_next, intel_batchbuffer::reloc_count, intel_batchbuffer::ring, intel_batchbuffer::saved, UNKNOWN_RING, and USED_BATCH.
Referenced by blorp_exec(), brw_dispatch_compute_common(), and brw_try_draw_prims().
intel_batchbuffer_save_state()
void intel_batchbuffer_save_state (struct brw_context * brw)
References brw_context::batch, intel_batchbuffer::bo, intel_batchbuffer::map_next, intel_batchbuffer::reloc_count, and intel_batchbuffer::saved.
Referenced by blorp_exec(), brw_dispatch_compute_common(), and brw_try_draw_prims().
load_sized_register_mem()
static void load_sized_register_mem (struct brw_context * brw, uint32_t reg, drm_intel_bo * bo, uint32_t read_domains, uint32_t write_domain, uint32_t offset, int size) static
References ADVANCE_BATCH, BEGIN_BATCH, brw_context::gen, GEN7_MI_LOAD_REGISTER_MEM, OUT_BATCH, OUT_RELOC, and OUT_RELOC64.
Referenced by brw_load_register_mem(), and brw_load_register_mem64().
throttle()
static void throttle (struct brw_context * brw) static
References brw_context::disable_throttling, intel_screen::driScrnPriv, brw_context::need_flush_throttle, brw_context::need_swap_throttle, brw_context::screen, and brw_context::throttle_batch.
Referenced by do_flush_locked().
uint_key_compare()
static bool uint_key_compare (const void * a, const void * b) static
Referenced by intel_batchbuffer_init().
uint_key_hash()
static uint32_t uint_key_hash (const void * key) static
Referenced by intel_batchbuffer_init().