Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex.h File Reference
#include "main/mtypes.h"
#include "main/formats.h"
#include "brw_context.h"
Functions
void intelInitTextureFuncs (struct dd_function_table *functions)
void intelInitTextureImageFuncs (struct dd_function_table *functions)
void intelInitTextureSubImageFuncs (struct dd_function_table *functions)
void intelInitTextureCopyImageFuncs (struct dd_function_table *functions)
void intelInitCopyImageFuncs (struct dd_function_table *functions)
void intelSetTexBuffer (__DRIcontext *pDRICtx, GLint target, __DRIdrawable *pDraw)
void intelSetTexBuffer2 (__DRIcontext *pDRICtx, GLint target, GLint format, __DRIdrawable *pDraw)
struct intel_mipmap_tree * intel_miptree_create_for_teximage (struct brw_context *brw, struct intel_texture_object *intelObj, struct intel_texture_image *intelImage, uint32_t layout_flags)
void intel_finalize_mipmap_tree (struct brw_context *brw, GLuint unit)
At rendering-from-a-texture time, make sure that the texture object has a miptree that can hold the entire texture based on BaseLevel/MaxLevel/filtering, and copy in any texture images that are stored in other miptrees.
bool intel_texsubimage_tiled_memcpy (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing, bool for_glTexImage)
A fast path for glTexImage and glTexSubImage.
bool intel_gettexsubimage_tiled_memcpy (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yofset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
A fast path for glGetTexImage.
Function Documentation
intel_finalize_mipmap_tree()
void intel_finalize_mipmap_tree (struct brw_context * brw, GLuint unit)
At rendering-from-a-texture time, make sure that the texture object has a miptree that can hold the entire texture based on BaseLevel/MaxLevel/filtering, and copy in any texture images that are stored in other miptrees.
References gl_texture_object::_BaseComplete, gl_texture_unit::_Current, intel_texture_object::_Format, intel_texture_object::_MaxLevel, _mesa_get_format_name(), swrast_texture_image::Base, intel_texture_image::base, intel_texture_object::base, gl_texture_object::BaseLevel, brw_context::ctx, brw_context::gen, GLuint, gl_texture_object::Image, gl_texture_object::Immutable, intel_get_image_dims(), intel_miptree_copy_teximage(), intel_miptree_create(), intel_miptree_match_image(), intel_miptree_release(), intel_texture_image(), intel_texture_object(), intel_update_max_level(), intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_object::Target, gl_texture_image::TexFormat, gl_context::Texture, gl_texture_attrib::Unit, intel_texture_object::validated_first_level, and intel_texture_object::validated_last_level.
Referenced by brw_validate_textures().
intel_gettexsubimage_tiled_memcpy()
bool intel_gettexsubimage_tiled_memcpy (struct gl_context * ctx, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing)
A fast path for glGetTexImage.
See also
intel_readpixels_tiled_memcpy()
References gl_texture_image::_BaseFormat, _mesa_image_row_stride(), gl_pixelstore_attrib::Alignment, brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_context(), gl_pixelstore_attrib::BufferObj, DBG, brw_context::has_llc, brw_context::has_swizzling, intel_batchbuffer_flush, intel_get_memcpy(), intel_miptree_all_slices_resolve_color(), intel_texture_image(), gl_pixelstore_attrib::Invert, gl_texture_image::Level, gl_pixelstore_attrib::LsbFirst, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_image::mt, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and tiled_to_linear().
Referenced by intel_get_tex_sub_image().
intel_miptree_create_for_teximage()
struct intel_mipmap_tree* intel_miptree_create_for_teximage (struct brw_context * brw, struct intel_texture_object * intelObj, struct intel_texture_image * intelImage, uint32_t layout_flags)
References _mesa_get_tex_max_num_levels(), swrast_texture_image::Base, intel_texture_image::base, intel_texture_object::base, DBG, gl_texture_object::GenerateMipmap, get_base_dim(), GL_TEXTURE_EXTERNAL_OES, GLuint, intel_get_image_dims(), intel_miptree_create(), gl_texture_image::Level, gl_sampler_object::MinFilter, intel_texture_object::mt, gl_texture_image::NumSamples, gl_texture_object::Sampler, gl_texture_object::Target, and gl_texture_image::TexFormat.
Referenced by intel_alloc_texture_image_buffer().
intel_texsubimage_tiled_memcpy()
bool intel_texsubimage_tiled_memcpy (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing, bool for_glTexImage)
A fast path for glTexImage and glTexSubImage.
Parameters
for_glTexImage Was this called from glTexImage or glTexSubImage?
This fast path is taken when the texture format is BGRA, RGBA, A or L and when the texture memory is X- or Y-tiled. It uploads the texture data by mapping the texture memory without a GTT fence, thus acquiring a tiled view of the memory, and then copying sucessive spans within each tile.
This is a performance win over the conventional texture upload path because it avoids the performance penalty of writing through the write-combine buffer. In the conventional texture upload path, texstore.c:store_texsubimage(), the texture memory is mapped through a GTT fence, thus acquiring a linear view of the memory, then each row in the image is memcpy'd. In this fast path, we replace each row's copy with a sequence of copies over each linear span in tile.
One use case is Google Chrome's paint rectangles. Chrome (as of version 21) renders each page as a tiling of 256x256 GL_BGRA textures. Each page's content is initially uploaded with glTexImage2D and damaged regions are updated with glTexSubImage2D. On some workloads, the performance gain of this fastpath on Sandybridge is over 5x.
References gl_context::_ImageTransferState, _mesa_image_row_stride(), gl_pixelstore_attrib::Alignment, dd_function_table::AllocTextureImageBuffer, brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_context(), gl_pixelstore_attrib::BufferObj, DBG, gl_context::Driver, brw_context::has_llc, brw_context::has_swizzling, intel_batchbuffer_flush, intel_get_memcpy(), intel_miptree_all_slices_resolve_color(), intel_texture_image(), gl_pixelstore_attrib::Invert, gl_texture_image::Level, linear_to_tiled(), gl_pixelstore_attrib::LsbFirst, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_image::mt, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::TexObject.
Referenced by intelTexImage(), and intelTexSubImage().
intelInitCopyImageFuncs()
void intelInitCopyImageFuncs (struct dd_function_table * functions)
References dd_function_table::CopyImageSubData, and intel_copy_image_sub_data().
Referenced by brw_init_driver_functions().
intelInitTextureCopyImageFuncs()
void intelInitTextureCopyImageFuncs (struct dd_function_table * functions)
References dd_function_table::CopyTexSubImage, and intelCopyTexSubImage().
Referenced by brw_init_driver_functions().
intelInitTextureFuncs()
void intelInitTextureFuncs (struct dd_function_table * functions)
References dd_function_table::AllocTextureImageBuffer, dd_function_table::AllocTextureStorage, dd_function_table::DeleteTexture, dd_function_table::DeleteTextureImage, dd_function_table::FreeTextureImageBuffer, intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_free_texture_image_buffer(), intel_map_texture_image(), intel_set_texture_storage_for_buffer_object(), intel_texture_barrier(), intel_texture_view(), intel_unmap_texture_image(), intelDeleteTextureImage(), intelDeleteTextureObject(), intelNewTextureImage(), intelNewTextureObject(), dd_function_table::MapTextureImage, dd_function_table::NewTextureImage, dd_function_table::NewTextureObject, dd_function_table::SetTextureStorageForBufferObject, dd_function_table::TextureBarrier, dd_function_table::TextureView, and dd_function_table::UnmapTextureImage.
Referenced by brw_init_driver_functions().
intelInitTextureImageFuncs()
void intelInitTextureImageFuncs (struct dd_function_table * functions)
References dd_function_table::BindRenderbufferTexImage, dd_function_table::CompressedTexSubImage, dd_function_table::EGLImageTargetTexture2D, dd_function_table::GetTexSubImage, intel_bind_renderbuffer_tex_image(), intel_get_tex_sub_image(), intel_image_target_texture_2d(), intelCompressedTexSubImage(), intelTexImage(), and dd_function_table::TexImage.
Referenced by brw_init_driver_functions().
intelInitTextureSubImageFuncs()
void intelInitTextureSubImageFuncs (struct dd_function_table * functions)
References intelTexSubImage(), and dd_function_table::TexSubImage.
Referenced by brw_init_driver_functions().
intelSetTexBuffer()
void intelSetTexBuffer (__DRIcontext * pDRICtx, GLint target, __DRIdrawable * pDraw)
References intelSetTexBuffer2().
intelSetTexBuffer2()
void intelSetTexBuffer2 (__DRIcontext * pDRICtx, GLint target, GLint format, __DRIdrawable * pDraw)
References _mesa_get_current_tex_object(), _mesa_get_tex_image(), swrast_renderbuffer::Base, intel_renderbuffer::Base, BUFFER_FRONT_LEFT, brw_context::ctx, gl_renderbuffer::Height, intel_get_renderbuffer(), intel_miptree_create_for_bo(), intel_miptree_make_shareable(), intel_miptree_release(), intel_set_texture_image_mt(), intel_update_renderbuffers(), MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_NONE, intel_renderbuffer::mt, and gl_renderbuffer::Width.
Referenced by intelSetTexBuffer().