Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_blit.c File Reference
#include "main/mtypes.h"
#include "main/blit.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/fbobject.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_blit.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "intel_batchbuffer.h"
#include "intel_mipmap_tree.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_BLIT
#define SET_BLITTER_TILING(...) __map = set_blitter_tiling(__VA_ARGS__, __map)
#define BEGIN_BATCH_BLT_TILED(n, dst_y_tiled, src_y_tiled)
#define ADVANCE_BATCH_TILED(dst_y_tiled, src_y_tiled)
Functions
static void intel_miptree_set_alpha_to_one (struct brw_context *brw, struct intel_mipmap_tree *mt, int x, int y, int width, int height)
Used to initialize the alpha value of an ARGB8888 miptree after copying into it from an XRGB8888 source.
static GLuint translate_raster_op (GLenum logicop)
static uint32_t br13_for_cpp (int cpp)
static uint32_t * set_blitter_tiling (struct brw_context *brw, bool dst_y_tiled, bool src_y_tiled, uint32_t *__map)
Emits the packet for switching the blitter from X to Y tiled or back.
static int blt_pitch (struct intel_mipmap_tree *mt)
bool intel_miptree_blit_compatible_formats (mesa_format src, mesa_format dst)
static void get_blit_intratile_offset_el (const struct brw_context *brw, struct intel_mipmap_tree *mt, uint32_t total_x_offset_el, uint32_t total_y_offset_el, uint32_t *base_address_offset, uint32_t *x_offset_el, uint32_t *y_offset_el)
static bool emit_miptree_blit (struct brw_context *brw, struct intel_mipmap_tree *src_mt, uint32_t src_x, uint32_t src_y, struct intel_mipmap_tree *dst_mt, uint32_t dst_x, uint32_t dst_y, uint32_t width, uint32_t height, bool reverse, GLenum logicop)
bool intel_miptree_blit (struct brw_context *brw, struct intel_mipmap_tree *src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, bool src_flip, struct intel_mipmap_tree *dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, bool dst_flip, uint32_t width, uint32_t height, GLenum logicop)
Implements a rectangular block transfer (blit) of pixels between two miptrees.
bool intel_miptree_copy (struct brw_context *brw, struct intel_mipmap_tree *src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, struct intel_mipmap_tree *dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, uint32_t src_width, uint32_t src_height)
static bool alignment_valid (struct brw_context *brw, unsigned offset, uint32_t tiling)
static uint32_t xy_blit_cmd (uint32_t src_tiling, uint32_t dst_tiling, uint32_t cpp)
bool intelEmitCopyBlit (struct brw_context *brw, GLuint cpp, int32_t src_pitch, drm_intel_bo *src_buffer, GLuint src_offset, uint32_t src_tiling, int32_t dst_pitch, drm_intel_bo *dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort src_x, GLshort src_y, GLshort dst_x, GLshort dst_y, GLshort w, GLshort h, GLenum logic_op)
bool intelEmitImmediateColorExpandBlit (struct brw_context *brw, GLuint cpp, GLubyte *src_bits, GLuint src_size, GLuint fg_color, GLshort dst_pitch, drm_intel_bo *dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort x, GLshort y, GLshort w, GLshort h, GLenum logic_op)
void intel_emit_linear_blit (struct brw_context *brw, drm_intel_bo *dst_bo, unsigned int dst_offset, drm_intel_bo *src_bo, unsigned int src_offset, unsigned int size)
Macro Definition Documentation
ADVANCE_BATCH_TILED
#define ADVANCE_BATCH_TILED (dst_y_tiled, src_y_tiled)
Value:
if (dst_y_tiled || src_y_tiled)                                   \
         SET_BLITTER_TILING(brw, false, false);                         \
      ADVANCE_BATCH()
Referenced by intel_miptree_set_alpha_to_one(), and intelEmitCopyBlit().
BEGIN_BATCH_BLT_TILED
#define BEGIN_BATCH_BLT_TILED (n, dst_y_tiled, src_y_tiled)
Value:
BEGIN_BATCH_BLT(n + ((dst_y_tiled || src_y_tiled) ? 14 : 0));     \
      if (dst_y_tiled || src_y_tiled)                                   \
         SET_BLITTER_TILING(brw, dst_y_tiled, src_y_tiled)
Referenced by intel_miptree_set_alpha_to_one(), and intelEmitCopyBlit().
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_BLIT
SET_BLITTER_TILING
#define SET_BLITTER_TILING (...) __map = set_blitter_tiling(__VA_ARGS__, __map)
Function Documentation
alignment_valid()
static bool alignment_valid (struct brw_context * brw, unsigned offset, uint32_t tiling) static
References brw_context::gen.
Referenced by intelEmitCopyBlit().
blt_pitch()
static int blt_pitch (struct intel_mipmap_tree * mt) static
Referenced by emit_miptree_blit().
br13_for_cpp()
static uint32_t br13_for_cpp (int cpp) static
References BR13_16161616, BR13_32323232, BR13_565, BR13_8, and BR13_8888.
Referenced by intel_miptree_set_alpha_to_one(), intelEmitCopyBlit(), and intelEmitImmediateColorExpandBlit().
emit_miptree_blit()
static bool emit_miptree_blit (struct brw_context * brw, struct intel_mipmap_tree * src_mt, uint32_t src_x, uint32_t src_y, struct intel_mipmap_tree * dst_mt, uint32_t dst_x, uint32_t dst_y, uint32_t width, uint32_t height, bool reverse, GLenum logicop) static
References blt_pitch(), brw_context::bo, get_blit_intratile_offset_el(), and intelEmitCopyBlit().
Referenced by intel_miptree_blit(), and intel_miptree_copy().
get_blit_intratile_offset_el()
static void get_blit_intratile_offset_el (const struct brw_context * brw, struct intel_mipmap_tree * mt, uint32_t total_x_offset_el, uint32_t total_y_offset_el, uint32_t * base_address_offset, uint32_t * x_offset_el, uint32_t * y_offset_el) static
References intel_miptree_get_isl_tiling(), and brw_context::isl_dev.
Referenced by emit_miptree_blit(), and intel_miptree_set_alpha_to_one().
intel_emit_linear_blit()
void intel_emit_linear_blit (struct brw_context * brw, drm_intel_bo * dst_bo, unsigned int dst_offset, drm_intel_bo * src_bo, unsigned int src_offset, unsigned int size)
References _mesa_problem(), brw_context::ctx, GLuint, and intelEmitCopyBlit().
Referenced by brw_buffer_subdata(), brw_copy_buffer_subdata(), brw_flush_mapped_buffer_range(), and brw_unmap_buffer().
intel_miptree_blit()
bool intel_miptree_blit (struct brw_context * brw, struct intel_mipmap_tree * src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, bool src_flip, struct intel_mipmap_tree * dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, bool dst_flip, uint32_t width, uint32_t height, GLenum logicop)
Implements a rectangular block transfer (blit) of pixels between two miptrees.
Our blitter can operate on 1, 2, or 4-byte-per-pixel data, with generous, but limited, pitches and sizes allowed.
The src/dst coordinates are relative to the given level/slice of the miptree.
If or is set, then the rectangle within that miptree will be inverted (including scanline order) when copying. This is common in GL when copying between window system and user-created renderbuffers/textures.
References _mesa_get_format_bits(), _mesa_get_format_name(), _mesa_get_srgb_format_linear(), emit_miptree_blit(), intel_miptree_blit_compatible_formats(), intel_miptree_get_image_offset(), intel_miptree_resolve_color(), intel_miptree_set_alpha_to_one(), and intel_miptree_slice_resolve_depth().
Referenced by do_blit_copypixels(), do_blit_drawpixels(), intel_blit_framebuffer_with_blitter(), intel_copy_texsubimage(), and intel_miptree_copy_slice().
intel_miptree_blit_compatible_formats()
bool intel_miptree_blit_compatible_formats (mesa_format src, mesa_format dst)
References _mesa_get_srgb_format_linear(), MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, and MESA_FORMAT_R8G8B8X8_UNORM.
Referenced by do_blit_drawpixels(), and intel_miptree_blit().
intel_miptree_copy()
bool intel_miptree_copy (struct brw_context * brw, struct intel_mipmap_tree * src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, struct intel_mipmap_tree * dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, uint32_t src_width, uint32_t src_height)
References _mesa_get_format_block_size(), _mesa_is_format_compressed(), emit_miptree_blit(), GLuint, intel_miptree_get_image_offset(), intel_miptree_resolve_color(), intel_miptree_slice_resolve_depth(), and MESA_FORMAT_S_UINT8.
Referenced by copy_miptrees(), intel_miptree_map_blit(), and intel_miptree_unmap_blit().
intel_miptree_set_alpha_to_one()
static void intel_miptree_set_alpha_to_one (struct brw_context * brw, struct intel_mipmap_tree * mt, int x, int y, int width, int height) static
Used to initialize the alpha value of an ARGB8888 miptree after copying into it from an XRGB8888 source.
This is very common with glCopyTexImage2D(). Note that the coordinates are relative to the start of the miptree, not relative to a slice within the miptree.
References ADVANCE_BATCH_TILED, brw_context::batch, BEGIN_BATCH_BLT_TILED, intel_batchbuffer::bo, br13_for_cpp(), brw_emit_mi_flush(), DBG, brw_context::gen, get_blit_intratile_offset_el(), intel_batchbuffer_flush, OUT_BATCH, OUT_RELOC, OUT_RELOC64, SET_FIELD, XY_BLT_WRITE_ALPHA, XY_COLOR_BLT_CMD, and XY_DST_TILED.
Referenced by intel_miptree_blit().
intelEmitCopyBlit()
bool intelEmitCopyBlit (struct brw_context * brw, GLuint cpp, int32_t src_pitch, drm_intel_bo * src_buffer, GLuint src_offset, uint32_t src_tiling, int32_t dst_pitch, drm_intel_bo * dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort src_x, GLshort src_y, GLshort dst_x, GLshort dst_y, GLshort w, GLshort h, GLenum logic_op)
References ADVANCE_BATCH_TILED, alignment_valid(), brw_context::batch, BEGIN_BATCH_BLT_TILED, BLT_RING, intel_batchbuffer::bo, br13_for_cpp(), brw_emit_mi_flush(), DBG, brw_context::gen, GLuint, intel_batchbuffer_flush, intel_batchbuffer_require_space(), intel_get_tile_dims(), OUT_BATCH, OUT_RELOC, OUT_RELOC64, SET_FIELD, translate_raster_op(), and xy_blit_cmd().
Referenced by emit_miptree_blit(), and intel_emit_linear_blit().
intelEmitImmediateColorExpandBlit()
bool intelEmitImmediateColorExpandBlit (struct brw_context * brw, GLuint cpp, GLubyte * src_bits, GLuint src_size, GLuint fg_color, GLshort dst_pitch, drm_intel_bo * dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort x, GLshort y, GLshort w, GLshort h, GLenum logic_op)
References ADVANCE_BATCH, BEGIN_BATCH_BLT, BLT_RING, br13_for_cpp(), brw_emit_mi_flush(), DBG, brw_context::gen, intel_batchbuffer_data(), intel_batchbuffer_require_space(), OUT_BATCH, OUT_RELOC, OUT_RELOC64, SET_FIELD, translate_raster_op(), XY_BLT_WRITE_ALPHA, XY_BLT_WRITE_RGB, XY_DST_TILED, XY_SETUP_BLT_CMD, XY_TEXT_BYTE_PACKED, and XY_TEXT_IMMEDIATE_BLIT_CMD.
Referenced by do_blit_bitmap().
set_blitter_tiling()
static uint32_t* set_blitter_tiling (struct brw_context * brw, bool dst_y_tiled, bool src_y_tiled, uint32_t * __map) static
Emits the packet for switching the blitter from X to Y tiled or back.
This has to be called in a single BEGIN_BATCH_BLT_TILED() / ADVANCE_BATCH_TILED(). This is because BCS_SWCTRL is saved and restored as part of the power context, not a render context, and if the batchbuffer was to get flushed between setting and blitting, or blitting and restoring, our tiling state would leak into other unsuspecting applications (like the X server).
References BCS_SWCTRL, BCS_SWCTRL_DST_Y, BCS_SWCTRL_SRC_Y, brw_context::gen, MI_FLUSH_DW, MI_LOAD_REGISTER_IMM, and OUT_BATCH.
translate_raster_op()
static GLuint translate_raster_op (GLenum logicop) static
References GLuint.
Referenced by intelEmitCopyBlit(), and intelEmitImmediateColorExpandBlit().
xy_blit_cmd()
static uint32_t xy_blit_cmd (uint32_t src_tiling, uint32_t dst_tiling, uint32_t cpp) static
References XY_BLT_WRITE_ALPHA, XY_BLT_WRITE_RGB, XY_DST_TILED, XY_SRC_COPY_BLT_CMD, and XY_SRC_TILED.
Referenced by intelEmitCopyBlit().