Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_state.c File Reference
#include "main/context.h"
#include "main/macros.h"
#include "main/enums.h"
#include "main/dd.h"
#include "intel_screen.h"
#include "brw_context.h"
#include "brw_defines.h"
Functions
int intel_translate_shadow_compare_func (GLenum func)
int intel_translate_compare_func (GLenum func)
int intel_translate_stencil_op (GLenum op)
int intel_translate_logic_op (GLenum opcode)
Function Documentation
intel_translate_compare_func()
int intel_translate_compare_func (GLenum func)
References BRW_COMPAREFUNCTION_ALWAYS, BRW_COMPAREFUNCTION_EQUAL, BRW_COMPAREFUNCTION_GEQUAL, BRW_COMPAREFUNCTION_GREATER, BRW_COMPAREFUNCTION_LEQUAL, BRW_COMPAREFUNCTION_LESS, BRW_COMPAREFUNCTION_NEVER, and BRW_COMPAREFUNCTION_NOTEQUAL.
Referenced by brw_get_index_type(), gen6_upload_blend_state(), gen6_upload_depth_stencil_state(), gen8_upload_blend_state(), and upload_cc_unit().
intel_translate_logic_op()
int intel_translate_logic_op (GLenum opcode)
References BRW_LOGICOPFUNCTION_AND, BRW_LOGICOPFUNCTION_AND_INVERTED, BRW_LOGICOPFUNCTION_AND_REVERSE, BRW_LOGICOPFUNCTION_CLEAR, BRW_LOGICOPFUNCTION_COPY, BRW_LOGICOPFUNCTION_COPY_INVERTED, BRW_LOGICOPFUNCTION_EQUIV, BRW_LOGICOPFUNCTION_INVERT, BRW_LOGICOPFUNCTION_NAND, BRW_LOGICOPFUNCTION_NOOP, BRW_LOGICOPFUNCTION_NOR, BRW_LOGICOPFUNCTION_OR, BRW_LOGICOPFUNCTION_OR_INVERTED, BRW_LOGICOPFUNCTION_OR_REVERSE, BRW_LOGICOPFUNCTION_SET, and BRW_LOGICOPFUNCTION_XOR.
Referenced by brw_get_index_type(), gen6_upload_blend_state(), gen8_upload_blend_state(), and upload_cc_unit().
intel_translate_shadow_compare_func()
int intel_translate_shadow_compare_func (GLenum func)
References BRW_COMPAREFUNCTION_ALWAYS, BRW_COMPAREFUNCTION_EQUAL, BRW_COMPAREFUNCTION_GEQUAL, BRW_COMPAREFUNCTION_GREATER, BRW_COMPAREFUNCTION_LEQUAL, BRW_COMPAREFUNCTION_LESS, BRW_COMPAREFUNCTION_NEVER, and BRW_COMPAREFUNCTION_NOTEQUAL.
Referenced by brw_get_index_type(), and brw_update_sampler_state().
intel_translate_stencil_op()
int intel_translate_stencil_op (GLenum op)
References BRW_STENCILOP_DECR, BRW_STENCILOP_DECRSAT, BRW_STENCILOP_INCR, BRW_STENCILOP_INCRSAT, BRW_STENCILOP_INVERT, BRW_STENCILOP_KEEP, BRW_STENCILOP_REPLACE, and BRW_STENCILOP_ZERO.
Referenced by brw_get_index_type(), gen6_upload_depth_stencil_state(), and upload_cc_unit().