Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_buffer_objects.h File Reference
#include "main/mtypes.h"
Data Structures
struct intel_buffer_object
Intel vertex/pixel buffer object, derived from Mesa's gl_buffer_object.
Functions
drm_intel_bo * intel_bufferobj_buffer (struct brw_context *brw, struct intel_buffer_object *obj, uint32_t offset, uint32_t size)
Gets a pointer to the object's BO, and marks the given range as being used on the GPU.
void intel_upload_data (struct brw_context *brw, const void *data, uint32_t size, uint32_t alignment, drm_intel_bo **out_bo, uint32_t *out_offset)
Handy interface to upload some data to temporary GPU memory quickly.
void * intel_upload_space (struct brw_context *brw, uint32_t size, uint32_t alignment, drm_intel_bo **out_bo, uint32_t *out_offset)
Interface for getting memory for uploading streamed data to the GPU.
void intel_upload_finish (struct brw_context *brw)
void intelInitBufferObjectFuncs (struct dd_function_table *functions)
static struct intel_buffer_object * intel_buffer_object (struct gl_buffer_object *obj)
Function Documentation
intel_buffer_object()
static struct intel_buffer_object* intel_buffer_object (struct gl_buffer_object * obj) static
Referenced by brw_buffer_data(), brw_buffer_subdata(), brw_copy_buffer_subdata(), brw_delete_buffer(), brw_dispatch_compute_indirect(), brw_emit_prim(), brw_flush_mapped_buffer_range(), brw_get_buffer_subdata(), brw_map_buffer_range(), brw_prepare_vertices(), brw_try_draw_prims(), brw_unmap_buffer(), brw_update_buffer_texture_surface(), brw_update_sol_surface(), brw_upload_abo_surfaces(), brw_upload_indices(), brw_upload_ubo_surfaces(), do_blit_drawpixels(), gen8_upload_3dstate_so_buffers(), hsw_store_query_result(), intel_buffer_object_purgeable(), intel_buffer_object_unpurgeable(), intel_set_texture_storage_for_buffer_object(), update_image_surface(), and upload_3dstate_so_buffers().
intel_bufferobj_buffer()
drm_intel_bo* intel_bufferobj_buffer (struct brw_context * brw, struct intel_buffer_object * intel_obj, uint32_t offset, uint32_t size)
Gets a pointer to the object's BO, and marks the given range as being used on the GPU.
Anywhere that uses buffer objects in the pipeline should be using this to mark the range of the buffer that is being accessed by the pipeline.
References alloc_buffer_object(), intel_buffer_object::buffer, and mark_buffer_gpu_usage().
Referenced by brw_copy_buffer_subdata(), brw_dispatch_compute_indirect(), brw_emit_prim(), brw_prepare_vertices(), brw_update_buffer_texture_surface(), brw_update_sol_surface(), brw_upload_abo_surfaces(), brw_upload_indices(), brw_upload_ubo_surfaces(), do_blit_drawpixels(), gen8_upload_3dstate_so_buffers(), intel_set_texture_storage_for_buffer_object(), and upload_3dstate_so_buffers().
intel_upload_data()
void intel_upload_data (struct brw_context * brw, const void * data, uint32_t size, uint32_t alignment, drm_intel_bo ** out_bo, uint32_t * out_offset)
Handy interface to upload some data to temporary GPU memory quickly.
References to this memory should not be retained across batch flushes.
References intel_upload_space().
Referenced by brw_prepare_shader_draw_parameters(), brw_upload_cs_work_groups_surface(), brw_upload_indices(), and copy_array_to_vbo_array().
intel_upload_finish()
void intel_upload_finish (struct brw_context * brw)
References brw_context::bo, brw_context::next_offset, and brw_context::upload.
Referenced by _intel_batchbuffer_flush_fence(), and intel_upload_space().
intel_upload_space()
void* intel_upload_space (struct brw_context * brw, uint32_t size, uint32_t alignment, drm_intel_bo ** out_bo, uint32_t * out_offset)
Interface for getting memory for uploading streamed data to the GPU.
In most cases, streamed data (for GPU state structures, for example) is uploaded through brw_state_batch(), since that interface allows relocations from the streamed space returned to other BOs. However, that interface has the restriction that the amount of space allocated has to be "small" (see estimated_max_prim_size in brw_draw.c).
This interface, on the other hand, is able to handle arbitrary sized allocation requests, though it will batch small allocations into the same BO for efficiency and reduced memory footprint.
Note
The returned pointer is valid only until intel_upload_finish(), which will happen at batch flush or the next intel_upload_space()/intel_upload_data().
Parameters
out_bo Pointer to a BO, which must point to a valid BO or NULL on entry, and will have a reference to the new BO containing the state on return.
out_offset Offset within the buffer object that the data will land.
References brw_context::bo, brw_context::bufmgr, brw_context::has_llc, intel_upload_finish(), INTEL_UPLOAD_SIZE, brw_context::next_offset, and brw_context::upload.
Referenced by brw_upload_constant_buffer(), brw_upload_pull_constants(), copy_array_to_vbo_array(), and intel_upload_data().
intelInitBufferObjectFuncs()
void intelInitBufferObjectFuncs (struct dd_function_table * functions)
References brw_buffer_data(), brw_buffer_subdata(), brw_copy_buffer_subdata(), brw_delete_buffer(), brw_flush_mapped_buffer_range(), brw_get_buffer_subdata(), brw_map_buffer_range(), brw_new_buffer_object(), brw_unmap_buffer(), dd_function_table::BufferData, dd_function_table::BufferSubData, dd_function_table::CopyBufferSubData, dd_function_table::DeleteBuffer, dd_function_table::FlushMappedBufferRange, dd_function_table::GetBufferSubData, dd_function_table::MapBufferRange, dd_function_table::NewBufferObject, and dd_function_table::UnmapBuffer.
Referenced by brw_init_driver_functions().