Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_extensions.c File Reference
#include "main/version.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_batchbuffer.h"
Functions
void intelInitExtensions (struct gl_context *ctx)
Initializes potential list of extensions if ctx == NULL, or actually enables extensions for a context.
Function Documentation
intelInitExtensions()
void intelInitExtensions (struct gl_context * ctx)
Initializes potential list of extensions if ctx == NULL, or actually enables extensions for a context.
References _mesa_override_glsl_version(), gl_extensions::AMD_seamless_cubemap_per_texture, gl_extensions::AMD_vertex_shader_layer, gl_extensions::AMD_vertex_shader_viewport_index, gl_extensions::ANDROID_extension_pack_es31a, gl_extensions::ANGLE_texture_compression_dxt, gl_context::API, API_OPENGL_CORE, gl_extensions::APPLE_object_purgeable, gl_extensions::ARB_arrays_of_arrays, gl_extensions::ARB_base_instance, gl_extensions::ARB_blend_func_extended, gl_extensions::ARB_buffer_storage, gl_extensions::ARB_clear_texture, gl_extensions::ARB_clip_control, gl_extensions::ARB_color_buffer_float, gl_extensions::ARB_compute_shader, gl_extensions::ARB_conditional_render_inverted, gl_extensions::ARB_conservative_depth, gl_extensions::ARB_copy_image, gl_extensions::ARB_cull_distance, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_derivative_control, gl_extensions::ARB_draw_buffers_blend, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_indirect, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_enhanced_layouts, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_ES3_1_compatibility, gl_extensions::ARB_ES3_2_compatibility, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_explicit_uniform_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_layer_viewport, gl_extensions::ARB_fragment_program, gl_extensions::ARB_fragment_program_shadow, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_gpu_shader5, gl_extensions::ARB_gpu_shader_fp64, gl_extensions::ARB_gpu_shader_int64, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_instanced_arrays, gl_extensions::ARB_internalformat_query, gl_extensions::ARB_internalformat_query2, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_pipeline_statistics_query, gl_extensions::ARB_point_sprite, gl_extensions::ARB_post_depth_coverage, gl_extensions::ARB_query_buffer_object, gl_extensions::ARB_robust_buffer_access_behavior, gl_extensions::ARB_sample_shading, gl_extensions::ARB_seamless_cube_map, gl_extensions::ARB_shader_atomic_counter_ops, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_shader_bit_encoding, gl_extensions::ARB_shader_clock, gl_extensions::ARB_shader_draw_parameters, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shader_image_size, gl_extensions::ARB_shader_precision, gl_extensions::ARB_shader_stencil_export, gl_extensions::ARB_shader_storage_buffer_object, gl_extensions::ARB_shader_subroutine, gl_extensions::ARB_shader_texture_image_samples, gl_extensions::ARB_shader_texture_lod, gl_extensions::ARB_shader_viewport_layer_array, gl_extensions::ARB_shading_language_420pack, gl_extensions::ARB_shading_language_packing, gl_extensions::ARB_shadow, gl_extensions::ARB_stencil_texturing, gl_extensions::ARB_sync, gl_extensions::ARB_tessellation_shader, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_buffer_object_rgb32, gl_extensions::ARB_texture_buffer_range, gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_gather, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ARB_texture_multisample, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_query_levels, gl_extensions::ARB_texture_query_lod, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::ARB_texture_stencil8, gl_extensions::ARB_texture_view, gl_extensions::ARB_timer_query, gl_extensions::ARB_transform_feedback2, gl_extensions::ARB_transform_feedback3, gl_extensions::ARB_transform_feedback_instanced, gl_extensions::ARB_transform_feedback_overflow_query, gl_extensions::ARB_uniform_buffer_object, gl_extensions::ARB_vertex_attrib_64bit, gl_extensions::ARB_vertex_program, gl_extensions::ARB_vertex_shader, gl_extensions::ARB_vertex_type_10f_11f_11f_rev, gl_extensions::ARB_vertex_type_2_10_10_10_rev, gl_extensions::ARB_viewport_array, gl_extensions::ATI_separate_stencil, gl_extensions::ATI_texture_env_combine3, brw_context(), can_do_compute_dispatch(), can_do_mi_math_and_lrr(), can_do_pipelined_register_writes(), can_do_predicate_writes(), gl_context::Const, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_framebuffer_multisample, gl_extensions::EXT_framebuffer_multisample_blit_scaled, gl_extensions::EXT_framebuffer_sRGB, gl_extensions::EXT_gpu_program_parameters, gl_extensions::EXT_packed_float, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_polygon_offset_clamp, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_shader_integer_mix, gl_extensions::EXT_shader_samples_identical, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_env_dot3, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_timer_query, gl_extensions::EXT_transform_feedback, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, brw_context::gen, gl_constants::GLSLVersion, intel_screen::hw_has_timestamp, gl_extensions::INTEL_conservative_rasterization, gl_extensions::INTEL_performance_query, brw_context::is_baytrail, brw_context::is_g4x, brw_context::is_haswell, gl_extensions::KHR_blend_equation_advanced, gl_extensions::KHR_blend_equation_advanced_coherent, gl_extensions::KHR_robustness, gl_extensions::KHR_texture_compression_astc_ldr, gl_extensions::KHR_texture_compression_astc_sliced_3d, gl_constants::MaxComputeWorkGroupSize, gl_context::Mesa_DXTn, gl_extensions::MESA_pack_invert, gl_extensions::MESA_shader_framebuffer_fetch, gl_extensions::MESA_shader_framebuffer_fetch_non_coherent, gl_extensions::MESA_shader_integer_functions, gl_extensions::NV_conditional_render, gl_extensions::NV_primitive_restart, gl_extensions::NV_texture_barrier, gl_extensions::NV_texture_env_combine4, gl_extensions::NV_texture_rectangle, gl_extensions::OES_compressed_ETC1_RGB8_texture, gl_extensions::OES_copy_image, gl_extensions::OES_depth_texture_cube_map, gl_extensions::OES_draw_texture, gl_extensions::OES_EGL_image, gl_extensions::OES_EGL_image_external, gl_extensions::OES_geometry_shader, gl_extensions::OES_primitive_bounding_box, gl_extensions::OES_sample_variables, gl_extensions::OES_standard_derivatives, gl_extensions::OES_texture_buffer, gl_extensions::OES_texture_cube_map_array, gl_extensions::OES_texture_float, gl_extensions::OES_texture_float_linear, gl_extensions::OES_texture_half_float, gl_extensions::OES_texture_half_float_linear, gl_extensions::OES_viewport_array, brw_context::optionCache, brw_context::predicate, brw_context::screen, brw_context::supported, and gl_extensions::TDFX_texture_compression_FXT1.
Referenced by brw_get_index_type(), and brwCreateContext().