Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_pixel_read.c File Reference
#include "main/enums.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/fbobject.h"
#include "main/image.h"
#include "main/bufferobj.h"
#include "main/readpix.h"
#include "main/state.h"
#include "main/glformats.h"
#include "drivers/common/meta.h"
#include "brw_context.h"
#include "intel_screen.h"
#include "intel_batchbuffer.h"
#include "intel_blit.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "intel_pixel.h"
#include "intel_buffer_objects.h"
#include "intel_tiled_memcpy.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Functions
static bool intel_readpixels_tiled_memcpy (struct gl_context *ctx, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *pack)
A fast path for glReadPixels.
void intelReadPixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *pack, GLvoid *pixels)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Function Documentation
intel_readpixels_tiled_memcpy()
static bool intel_readpixels_tiled_memcpy (struct gl_context * ctx, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * pack) static
A fast path for glReadPixels.
This fast path is taken when the source format is BGRA, RGBA, A or L and when the texture memory is X- or Y-tiled. It downloads the source data by directly mapping the memory without a GTT fence. This then needs to be de-tiled on the CPU before presenting the data to the user in the linear fasion.
This is a performance win over the conventional texture download path. In the conventional texture download path, the texture is either mapped through the GTT or copied to a linear buffer with the blitter before handing off to a software path. This allows us to avoid round-tripping through the GPU (in the case where we would be blitting) and do only a single copy operation.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorReadBuffer, gl_context::_ImageTransferState, _mesa_image_row_stride(), gl_pixelstore_attrib::Alignment, brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_context(), gl_pixelstore_attrib::BufferObj, DBG, gl_renderbuffer::Format, brw_context::has_llc, brw_context::has_swizzling, gl_renderbuffer::Height, intel_batchbuffer_flush, intel_get_memcpy(), intel_miptree_all_slices_resolve_color(), intel_renderbuffer(), gl_pixelstore_attrib::Invert, gl_pixelstore_attrib::LsbFirst, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_renderbuffer::Name, gl_renderbuffer::NumSamples, gl_context::ReadBuffer, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, and tiled_to_linear().
Referenced by intelReadPixels().
intelReadPixels()
void intelReadPixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * pack, GLvoid * pixels)
References _mesa_readpixels(), _mesa_update_state(), brw_context(), brw_emit_mi_flush(), gl_pixelstore_attrib::BufferObj, DBG, brw_context::front_buffer_dirty, intel_prepare_render(), intel_readpixels_tiled_memcpy(), gl_context::NewState, and brw_context::perf_debug.
Referenced by intelInitPixelFuncs().