Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_buffers.c File Reference
#include "brw_context.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "main/renderbuffer.h"
Functions
static void intelDrawBuffer (struct gl_context *ctx, GLenum mode)
static void intelReadBuffer (struct gl_context *ctx, GLenum mode)
void intelInitBufferFuncs (struct dd_function_table *functions)
Function Documentation
intelDrawBuffer()
static void intelDrawBuffer (struct gl_context * ctx, GLenum mode) static
References _mesa_is_front_buffer_drawing(), brw_context(), gl_context::DrawBuffer, brw_context::driContext, and intel_prepare_render().
Referenced by intelInitBufferFuncs().
intelInitBufferFuncs()
void intelInitBufferFuncs (struct dd_function_table * functions)
References dd_function_table::DrawBuffer, intelDrawBuffer(), intelReadBuffer(), and dd_function_table::ReadBuffer.
Referenced by brw_init_driver_functions().
intelReadBuffer()
static void intelReadBuffer (struct gl_context * ctx, GLenum mode) static
References _mesa_is_front_buffer_reading(), brw_context(), brw_context::driContext, intel_prepare_render(), and gl_context::ReadBuffer.
Referenced by intelInitBufferFuncs().