Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tiled_memcpy.c File Reference
#include <string.h>
#include "util/macros.h"
#include "brw_context.h"
#include "intel_tiled_memcpy.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
#define ALIGN_DOWN(a, b) ROUND_DOWN_TO(a, b)
#define ALIGN_UP(a, b) ALIGN(a, b)
Typedefs
typedef void(* tile_copy_fn) (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t linear_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy)
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3).
Functions
static uint32_t ror (uint32_t n, uint32_t d)
static uint32_t bswap32 (uint32_t n)
static void * rgba8_copy (void *dst, const void *src, size_t bytes)
Copy RGBA to BGRA - swap R and B.
static void * rgba8_copy_aligned_dst (void *dst, const void *src, size_t bytes)
Copy RGBA to BGRA - swap R and B, with the destination 16-byte aligned.
static void * rgba8_copy_aligned_src (void *dst, const void *src, size_t bytes)
Copy RGBA to BGRA - swap R and B, with the source 16-byte aligned.
static void linear_to_xtiled (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16)
Copy texture data from linear to X tile layout.
static void linear_to_ytiled (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16)
Copy texture data from linear to Y tile layout.
static void xtiled_to_linear (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16)
Copy texture data from X tile layout to linear.
static void ytiled_to_linear (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16)
Copy texture data from Y tile layout to linear.
static FLATTEN void linear_to_xtiled_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy)
Copy texture data from linear to X tile layout, faster.
static FLATTEN void linear_to_ytiled_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy)
Copy texture data from linear to Y tile layout, faster.
static FLATTEN void xtiled_to_linear_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy)
Copy texture data from X tile layout to linear, faster.
static FLATTEN void ytiled_to_linear_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy)
Copy texture data from Y tile layout to linear, faster.
void linear_to_tiled (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char *dst, const char *src, uint32_t dst_pitch, int32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from linear to tiled texture.
void tiled_to_linear (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char *dst, const char *src, int32_t dst_pitch, uint32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from tiled to linear texture.
bool intel_get_memcpy (mesa_format tiledFormat, GLenum format, GLenum type, mem_copy_fn *mem_copy, uint32_t *cpp)
Determine which copy function to use for the given format combination.
Variables
static const uint32_t xtile_width = 512
static const uint32_t xtile_height = 8
static const uint32_t xtile_span = 64
static const uint32_t ytile_width = 128
static const uint32_t ytile_height = 32
static const uint32_t ytile_span = 16
Macro Definition Documentation
ALIGN_DOWN
#define ALIGN_DOWN (a, b) ROUND_DOWN_TO(a, b)
Referenced by linear_to_tiled(), and tiled_to_linear().
ALIGN_UP
#define ALIGN_UP (a, b) ALIGN(a, b)
Referenced by linear_to_tiled(), and tiled_to_linear().
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Typedef Documentation
tile_copy_fn
typedef void(* tile_copy_fn) (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char *dst, const char *src, int32_t linear_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy)
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3).
These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
Function Documentation
bswap32()
static uint32_t bswap32 (uint32_t n) inline static
Referenced by rgba8_copy().
intel_get_memcpy()
bool intel_get_memcpy (mesa_format tiledFormat, GLenum format, GLenum type, mem_copy_fn * mem_copy, uint32_t * cpp)
Determine which copy function to use for the given format combination.
The only two possible copy functions which are ever returned are a direct memcpy and a RGBA <-> BGRA copy function. Since RGBA -> BGRA and BGRA -> RGBA are exactly the same operation (and memcpy is obviously symmetric), it doesn't matter whether the copy is from the tiled image to the untiled or vice versa. The copy function required is the same in either case so this function can be used.
Parameters
[in] tiledFormat The format of the tiled image
[in] format The GL format of the client data
[in] type The GL type of the client data
[out] mem_copy Will be set to one of either the standard library's memcpy or a different copy function that performs an RGBA to BGRA conversion
[out] cpp Number of bytes per channel
Returns
true if the format and type combination are valid
References MESA_FORMAT_A_UNORM8, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_L_UNORM8, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, and rgba8_copy().
Referenced by intel_gettexsubimage_tiled_memcpy(), intel_readpixels_tiled_memcpy(), and intel_texsubimage_tiled_memcpy().
linear_to_tiled()
void linear_to_tiled (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char * dst, const char * src, uint32_t dst_pitch, int32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from linear to tiled texture.
Divide the region given by X range [xt1, xt2) and Y range [yt1, yt2) into pieces that do not cross tile boundaries and copy each piece with a tile copy function (tile_copy_fn). The X range is in bytes, i.e. pixels * bytes-per-pixel. The Y range is in pixels (i.e. unitless). 'dst' is the start of the texture and 'src' is the corresponding address to copy from, though copying begins at (xt1, yt1).
References ALIGN_DOWN, ALIGN_UP, linear_to_xtiled_faster(), linear_to_ytiled_faster(), span, xtile_height, xtile_span, xtile_width, y1, ytile_height, ytile_span, and ytile_width.
Referenced by intel_texsubimage_tiled_memcpy().
linear_to_xtiled()
static void linear_to_xtiled (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16) inline static
Copy texture data from linear to X tile layout.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
The mem_copy parameters allow the user to specify an alternative mem_copy function that, for instance, may do RGBA -> BGRA swizzling. The first function must handle any memory alignment while the second function must only handle 16-byte alignment in whichever side (source or destination) is tiled.
References swizzle(), xtile_span, and xtile_width.
Referenced by linear_to_xtiled_faster().
linear_to_xtiled_faster()
static FLATTEN void linear_to_xtiled_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy) static
Copy texture data from linear to X tile layout, faster.
Same as linear_to_xtiled but faster, because it passes constant parameters for common cases, allowing the compiler to inline code optimized for those cases.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References linear_to_xtiled(), rgba8_copy(), rgba8_copy_aligned_dst(), xtile_height, and xtile_width.
Referenced by linear_to_tiled().
linear_to_ytiled()
static void linear_to_ytiled (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16) inline static
Copy texture data from linear to Y tile layout.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References swizzle(), x, ytile_height, and ytile_span.
Referenced by linear_to_ytiled_faster().
linear_to_ytiled_faster()
static FLATTEN void linear_to_ytiled_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t src_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy) static
Copy texture data from linear to Y tile layout, faster.
Same as linear_to_ytiled but faster, because it passes constant parameters for common cases, allowing the compiler to inline code optimized for those cases.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References linear_to_ytiled(), rgba8_copy(), rgba8_copy_aligned_dst(), ytile_height, and ytile_width.
Referenced by linear_to_tiled().
rgba8_copy()
static void* rgba8_copy (void * dst, const void * src, size_t bytes) inline static
Copy RGBA to BGRA - swap R and B.
References bswap32(), and ror().
Referenced by intel_get_memcpy(), linear_to_xtiled_faster(), linear_to_ytiled_faster(), rgba8_copy_aligned_dst(), rgba8_copy_aligned_src(), xtiled_to_linear_faster(), and ytiled_to_linear_faster().
rgba8_copy_aligned_dst()
static void* rgba8_copy_aligned_dst (void * dst, const void * src, size_t bytes) inline static
Copy RGBA to BGRA - swap R and B, with the destination 16-byte aligned.
References rgba8_copy().
Referenced by linear_to_xtiled_faster(), and linear_to_ytiled_faster().
rgba8_copy_aligned_src()
static void* rgba8_copy_aligned_src (void * dst, const void * src, size_t bytes) inline static
Copy RGBA to BGRA - swap R and B, with the source 16-byte aligned.
References rgba8_copy().
Referenced by xtiled_to_linear_faster(), and ytiled_to_linear_faster().
ror()
static uint32_t ror (uint32_t n, uint32_t d) inline static
Referenced by rgba8_copy().
tiled_to_linear()
void tiled_to_linear (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char * dst, const char * src, int32_t dst_pitch, uint32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from tiled to linear texture.
Divide the region given by X range [xt1, xt2) and Y range [yt1, yt2) into pieces that do not cross tile boundaries and copy each piece with a tile copy function (tile_copy_fn). The X range is in bytes, i.e. pixels * bytes-per-pixel. The Y range is in pixels (i.e. unitless). 'dst' is the start of the texture and 'src' is the corresponding address to copy from, though copying begins at (xt1, yt1).
References ALIGN_DOWN, ALIGN_UP, span, xtile_height, xtile_span, xtile_width, xtiled_to_linear_faster(), y1, ytile_height, ytile_span, ytile_width, and ytiled_to_linear_faster().
Referenced by intel_gettexsubimage_tiled_memcpy(), and intel_readpixels_tiled_memcpy().
xtiled_to_linear()
static void xtiled_to_linear (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16) inline static
Copy texture data from X tile layout to linear.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References swizzle(), xtile_span, and xtile_width.
Referenced by xtiled_to_linear_faster().
xtiled_to_linear_faster()
static FLATTEN void xtiled_to_linear_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy) static
Copy texture data from X tile layout to linear, faster.
Same as xtile_to_linear but faster, because it passes constant parameters for common cases, allowing the compiler to inline code optimized for those cases.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References rgba8_copy(), rgba8_copy_aligned_src(), xtile_height, xtile_width, and xtiled_to_linear().
Referenced by tiled_to_linear().
ytiled_to_linear()
static void ytiled_to_linear (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy, mem_copy_fn mem_copy_align16) inline static
Copy texture data from Y tile layout to linear.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References swizzle(), x, ytile_height, and ytile_span.
Referenced by ytiled_to_linear_faster().
ytiled_to_linear_faster()
static FLATTEN void ytiled_to_linear_faster (uint32_t x0, uint32_t x1, uint32_t x2, uint32_t x3, uint32_t y0, uint32_t y1, char * dst, const char * src, int32_t dst_pitch, uint32_t swizzle_bit, mem_copy_fn mem_copy) static
Copy texture data from Y tile layout to linear, faster.
Same as ytile_to_linear but faster, because it passes constant parameters for common cases, allowing the compiler to inline code optimized for those cases.
Each row from y0 to y1 is copied in three parts: [x0,x1), [x1,x2), [x2,x3). These ranges are in bytes, i.e. pixels * bytes-per-pixel. The first and last ranges must be shorter than a "span" (the longest linear stretch within a tile) and the middle must equal a whole number of spans. Ranges may be empty. The region copied must land entirely within one tile. 'dst' is the start of the tile and 'src' is the corresponding address to copy from, though copying begins at (x0, y0). To enable swizzling 'swizzle_bit' must be 1<<6, otherwise zero. Swizzling flips bit 6 in the copy destination offset, when certain other bits are set in it.
References rgba8_copy(), rgba8_copy_aligned_src(), ytile_height, ytile_width, and ytiled_to_linear().
Referenced by tiled_to_linear().
Variable Documentation
xtile_height
const uint32_t xtile_height = 8 static
Referenced by linear_to_tiled(), linear_to_xtiled_faster(), tiled_to_linear(), and xtiled_to_linear_faster().
xtile_span
const uint32_t xtile_span = 64 static
Referenced by linear_to_tiled(), linear_to_xtiled(), tiled_to_linear(), and xtiled_to_linear().
xtile_width
const uint32_t xtile_width = 512 static
Referenced by linear_to_tiled(), linear_to_xtiled(), linear_to_xtiled_faster(), tiled_to_linear(), xtiled_to_linear(), and xtiled_to_linear_faster().
ytile_height
const uint32_t ytile_height = 32 static
Referenced by linear_to_tiled(), linear_to_ytiled(), linear_to_ytiled_faster(), tiled_to_linear(), ytiled_to_linear(), and ytiled_to_linear_faster().
ytile_span
const uint32_t ytile_span = 16 static
Referenced by linear_to_tiled(), linear_to_ytiled(), tiled_to_linear(), and ytiled_to_linear().
ytile_width
const uint32_t ytile_width = 128 static
Referenced by linear_to_tiled(), linear_to_ytiled_faster(), tiled_to_linear(), and ytiled_to_linear_faster().