Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_pixel_bitmap.c File Reference
#include "main/blend.h"
#include "main/enums.h"
#include "main/image.h"
#include "main/colormac.h"
#include "main/condrender.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/pbo.h"
#include "main/bufferobj.h"
#include "main/state.h"
#include "main/texobj.h"
#include "main/context.h"
#include "main/fbobject.h"
#include "swrast/swrast.h"
#include "drivers/common/meta.h"
#include "brw_context.h"
#include "intel_screen.h"
#include "intel_batchbuffer.h"
#include "intel_blit.h"
#include "intel_fbo.h"
#include "intel_image.h"
#include "intel_buffers.h"
#include "intel_pixel.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_PIXEL
#define DY 32
#define DX 32
Functions
static const GLubyte * map_pbo (struct gl_context *ctx, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
static bool test_bit (const GLubyte *src, GLuint bit)
static void set_bit (GLubyte *dest, GLuint bit)
static GLuint get_bitmap_rect (GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap, GLuint x, GLuint y, GLuint w, GLuint h, GLubyte *dest, GLuint row_align, bool invert)
static int y_flip (struct gl_framebuffer *fb, int y, int height)
Returns the low Y value of the vertical range given, flipped according to whether the framebuffer is or not.
static bool do_blit_bitmap (struct gl_context *ctx, GLint dstx, GLint dsty, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
void intelBitmap (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *pixels)
Macro Definition Documentation
DX
#define DX 32
Referenced by do_blit_bitmap().
DY
#define DY 32
Referenced by do_blit_bitmap().
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Function Documentation
do_blit_bitmap()
static bool do_blit_bitmap (struct gl_context * ctx, GLint dstx, GLint dsty, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * bitmap) static
References gl_framebuffer::_ColorDrawBuffers, _mesa_clip_to_region(), _mesa_get_format_name(), _mesa_get_render_format(), _mesa_update_state(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, ADD_3V, brw_context(), gl_pixelstore_attrib::BufferObj, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, COPY_4V, gl_context::Current, gl_query_state::CurrentOcclusionObject, gl_context::Depth, gl_context::DrawBuffer, gl_context::Driver, DX, DY, F, get_bitmap_rect(), GLuint, intel_batchbuffer_flush, intel_check_blit_fragment_ops(), intel_miptree_all_slices_resolve_color(), intel_prepare_render(), intel_rb_format(), intel_renderbuffer(), intelEmitImmediateColorExpandBlit(), gl_colorbuffer_attrib::LogicOp, MAP_INTERNAL, map_pbo(), MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, intel_renderbuffer::mt, PACK_COLOR_565, PACK_COLOR_8888, gl_context::Query, gl_current_attrib::RasterColor, gl_current_attrib::RasterSecondaryColor, gl_query_object::Result, gl_depthbuffer_attrib::Test, UNCLAMPED_FLOAT_TO_UBYTE, dd_function_table::UnmapBuffer, and y_flip().
Referenced by intelBitmap().
get_bitmap_rect()
static GLuint get_bitmap_rect (GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * bitmap, GLuint x, GLuint y, GLuint w, GLuint h, GLubyte * dest, GLuint row_align, bool invert) static
References _mesa_image_address2d(), DBG, GLuint, gl_pixelstore_attrib::LsbFirst, set_bit(), gl_pixelstore_attrib::SkipPixels, and test_bit().
Referenced by do_blit_bitmap().
intelBitmap()
void intelBitmap (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * pixels)
References _mesa_check_conditional_render(), and do_blit_bitmap().
Referenced by intelInitPixelFuncs().
map_pbo()
static const GLubyte* map_pbo (struct gl_context * ctx, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * bitmap) static
References _mesa_error(), _mesa_validate_pbo_access(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and gl_buffer_object::Size.
Referenced by do_blit_bitmap().
set_bit()
static void set_bit (GLubyte * dest, GLuint bit) static
Referenced by get_bitmap_rect().
test_bit()
static bool test_bit (const GLubyte * src, GLuint bit) static
Referenced by get_bitmap_rect().
y_flip()
static int y_flip (struct gl_framebuffer * fb, int y, int height) inline static
Returns the low Y value of the vertical range given, flipped according to whether the framebuffer is or not.
References gl_framebuffer::Height.
Referenced by do_blit_bitmap().