Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex_validate.c File Reference
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/samplerobj.h"
#include "main/teximage.h"
#include "main/texobj.h"
#include "brw_context.h"
#include "intel_mipmap_tree.h"
#include "intel_blit.h"
#include "intel_tex.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Functions
static void intel_update_max_level (struct intel_texture_object *intelObj, struct gl_sampler_object *sampler)
Sets our driver-specific variant of tObj->_MaxLevel for later surface state upload.
void intel_finalize_mipmap_tree (struct brw_context *brw, GLuint unit)
At rendering-from-a-texture time, make sure that the texture object has a miptree that can hold the entire texture based on BaseLevel/MaxLevel/filtering, and copy in any texture images that are stored in other miptrees.
void brw_validate_textures (struct brw_context *brw)
Finalizes all textures, completing any rendering that needs to be done to prepare them.
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Function Documentation
brw_validate_textures()
void brw_validate_textures (struct brw_context * brw)
Finalizes all textures, completing any rendering that needs to be done to prepare them.
References gl_texture_unit::_Current, gl_texture_attrib::_MaxEnabledTexImageUnit, brw_context::ctx, intel_finalize_mipmap_tree(), gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by brw_dispatch_compute_common(), and brw_try_draw_prims().
intel_finalize_mipmap_tree()
void intel_finalize_mipmap_tree (struct brw_context * brw, GLuint unit)
At rendering-from-a-texture time, make sure that the texture object has a miptree that can hold the entire texture based on BaseLevel/MaxLevel/filtering, and copy in any texture images that are stored in other miptrees.
References gl_texture_object::_BaseComplete, gl_texture_unit::_Current, intel_texture_object::_Format, intel_texture_object::_MaxLevel, _mesa_get_format_name(), swrast_texture_image::Base, intel_texture_image::base, intel_texture_object::base, gl_texture_object::BaseLevel, brw_context::ctx, brw_context::gen, GLuint, gl_texture_object::Image, gl_texture_object::Immutable, intel_get_image_dims(), intel_miptree_copy_teximage(), intel_miptree_create(), intel_miptree_match_image(), intel_miptree_release(), intel_texture_image(), intel_texture_object(), intel_update_max_level(), intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_object::Target, gl_texture_image::TexFormat, gl_context::Texture, gl_texture_attrib::Unit, intel_texture_object::validated_first_level, and intel_texture_object::validated_last_level.
Referenced by brw_validate_textures().
intel_update_max_level()
static void intel_update_max_level (struct intel_texture_object * intelObj, struct gl_sampler_object * sampler) static
Sets our driver-specific variant of tObj->_MaxLevel for later surface state upload.
If we're only ensuring that there is storage for the first miplevel of a texture, then in texture setup we're going to have to make sure we don't allow sampling beyond level 0.
References gl_texture_object::_MaxLevel, intel_texture_object::_MaxLevel, gl_texture_object::_MipmapComplete, gl_texture_object::_RenderToTexture, intel_texture_object::base, gl_texture_object::BaseLevel, and gl_sampler_object::MinFilter.
Referenced by intel_finalize_mipmap_tree().