Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_fbo.h File Reference
#include <stdbool.h>
#include <assert.h>
#include "main/formats.h"
#include "main/macros.h"
#include "brw_context.h"
#include "intel_mipmap_tree.h"
#include "intel_screen.h"
Data Structures
struct intel_renderbuffer
Intel renderbuffer, derived from gl_renderbuffer.
Macros
#define INTEL_RB_CLASS 0x12345678
gl_renderbuffer is a base class which we subclass.
Functions
static struct intel_renderbuffer * intel_renderbuffer (struct gl_renderbuffer *rb)
Return a gl_renderbuffer ptr casted to intel_renderbuffer.
static struct intel_renderbuffer * intel_get_renderbuffer (struct gl_framebuffer *fb, gl_buffer_index attIndex)
Return the framebuffer attachment specified by attIndex.
static mesa_format intel_rb_format (const struct intel_renderbuffer *rb)
struct intel_renderbuffer * intel_create_renderbuffer (mesa_format format, unsigned num_samples)
Create a new intel_renderbuffer which corresponds to an on-screen window, not a user-created renderbuffer.
struct intel_renderbuffer * intel_create_private_renderbuffer (mesa_format format, unsigned num_samples)
Private window-system buffers (as opposed to ones shared with the display server created with intel_create_renderbuffer()) are most similar in their handling to user-created renderbuffers, but they have a resize handler that may be called at intel_update_renderbuffers() time.
struct gl_renderbuffer * intel_create_wrapped_renderbuffer (struct gl_context *ctx, int width, int height, mesa_format format)
void intel_fbo_init (struct brw_context *brw)
Do one-time context initializations related to GL_EXT_framebuffer_object.
void intel_renderbuffer_set_draw_offset (struct intel_renderbuffer *irb)
static uint32_t intel_renderbuffer_get_tile_offsets (struct intel_renderbuffer *irb, uint32_t *tile_x, uint32_t *tile_y)
bool intel_renderbuffer_has_hiz (struct intel_renderbuffer *irb)
Does the renderbuffer have hiz enabled?
void intel_renderbuffer_att_set_needs_depth_resolve (struct gl_renderbuffer_attachment *att)
bool intel_renderbuffer_resolve_hiz (struct brw_context *brw, struct intel_renderbuffer *irb)
Perform a HiZ resolve on the renderbuffer.
bool intel_renderbuffer_resolve_depth (struct brw_context *brw, struct intel_renderbuffer *irb)
Perform a depth resolve on the renderbuffer.
void intel_renderbuffer_move_to_temp (struct brw_context *brw, struct intel_renderbuffer *irb, bool invalidate)
void intel_renderbuffer_downsample (struct brw_context *brw, struct intel_renderbuffer *irb)
Downsample a winsys renderbuffer from mt to singlesample_mt.
void intel_renderbuffer_upsample (struct brw_context *brw, struct intel_renderbuffer *irb)
Upsample a winsys renderbuffer from singlesample_mt to mt.
void brw_render_cache_set_clear (struct brw_context *brw)
void brw_render_cache_set_add_bo (struct brw_context *brw, drm_intel_bo *bo)
void brw_render_cache_set_check_flush (struct brw_context *brw, drm_intel_bo *bo)
Emits an appropriate flush for a BO if it has been rendered to within the same batchbuffer as a read that's about to be emitted.
unsigned intel_quantize_num_samples (struct intel_screen *intel, unsigned num_samples)
Round up the requested multisample count to the next supported sample size.
Macro Definition Documentation
INTEL_RB_CLASS
#define INTEL_RB_CLASS 0x12345678
gl_renderbuffer is a base class which we subclass.
The Class field is used for simple run-time type checking.
Referenced by intel_create_renderbuffer(), intel_new_renderbuffer(), and intel_renderbuffer().
Function Documentation
brw_render_cache_set_add_bo()
void brw_render_cache_set_add_bo (struct brw_context * brw, drm_intel_bo * bo)
References brw_context::render_cache.
Referenced by blorp_exec(), brw_postdraw_set_buffers_need_resolve(), gen8_hiz_exec(), and intel_renderbuffer_get_tile_offsets().
brw_render_cache_set_check_flush()
void brw_render_cache_set_check_flush (struct brw_context * brw, drm_intel_bo * bo)
Emits an appropriate flush for a BO if it has been rendered to within the same batchbuffer as a read that's about to be emitted.
The GPU has separate, incoherent caches for the render cache and the sampler cache, along with other caches. Usually data in the different caches don't interact (e.g. we don't render to our driver-generated immediate constant data), but for render-to-texture in FBOs we definitely do. When a batchbuffer is flushed, the kernel will ensure that everything necessary is flushed before another use of that BO, but for reuse from different caches within a batchbuffer, it's all our responsibility.
References brw_emit_mi_flush(), brw_emit_pipe_control_flush(), brw_render_cache_set_clear(), brw_context::gen, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE, and brw_context::render_cache.
Referenced by blorp_exec(), brw_emit_depthbuffer(), intel_renderbuffer_get_tile_offsets(), intel_update_r8stencil(), and intel_update_state().
brw_render_cache_set_clear()
void brw_render_cache_set_clear (struct brw_context * brw)
References brw_context::render_cache.
Referenced by brw_render_cache_set_check_flush(), intel_batchbuffer_reset_and_clear_render_cache(), and intel_renderbuffer_get_tile_offsets().
intel_create_private_renderbuffer()
struct intel_renderbuffer* intel_create_private_renderbuffer (mesa_format format, unsigned num_samples)
Private window-system buffers (as opposed to ones shared with the display server created with intel_create_renderbuffer()) are most similar in their handling to user-created renderbuffers, but they have a resize handler that may be called at intel_update_renderbuffers() time.
Parameters
num_samples must be quantized.
References gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, intel_renderbuffer::Base, intel_alloc_private_renderbuffer_storage(), and intel_create_renderbuffer().
Referenced by intel_rb_format(), and intelCreateBuffer().
intel_create_renderbuffer()
struct intel_renderbuffer* intel_create_renderbuffer (mesa_format format, unsigned num_samples)
Create a new intel_renderbuffer which corresponds to an on-screen window, not a user-created renderbuffer.
Parameters
num_samples must be quantized.
References gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_get_format_base_format(), _mesa_init_renderbuffer(), gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, intel_renderbuffer::Base, CALLOC_STRUCT, gl_renderbuffer::ClassID, gl_renderbuffer::Delete, gl_renderbuffer::Format, intel_alloc_window_storage(), intel_delete_renderbuffer(), INTEL_RB_CLASS, gl_renderbuffer::InternalFormat, intel_renderbuffer::layer_count, and gl_renderbuffer::NumSamples.
Referenced by intel_create_private_renderbuffer(), intel_rb_format(), and intelCreateBuffer().
intel_create_wrapped_renderbuffer()
struct gl_renderbuffer* intel_create_wrapped_renderbuffer (struct gl_context * ctx, int width, int height, mesa_format format)
Referenced by intel_rb_format().
intel_fbo_init()
void intel_fbo_init (struct brw_context * brw)
Do one-time context initializations related to GL_EXT_framebuffer_object.
Hook in device driver functions.
References dd_function_table::BlitFramebuffer, brw_context::ctx, gl_context::Driver, dd_function_table::EGLImageTargetRenderbufferStorage, brw_context::gen, gen4_blit_framebuffer(), intel_blit_framebuffer(), intel_image_target_renderbuffer_storage(), intel_map_renderbuffer(), intel_new_renderbuffer(), intel_render_texture(), intel_unmap_renderbuffer(), intel_validate_framebuffer(), dd_function_table::MapRenderbuffer, dd_function_table::NewRenderbuffer, brw_context::render_cache, dd_function_table::RenderTexture, dd_function_table::UnmapRenderbuffer, and dd_function_table::ValidateFramebuffer.
Referenced by brwCreateContext(), and intel_rb_format().
intel_get_renderbuffer()
static struct intel_renderbuffer* intel_get_renderbuffer (struct gl_framebuffer * fb, gl_buffer_index attIndex) static
Return the framebuffer attachment specified by attIndex.
If the framebuffer lacks the specified attachment, then return null.
If the attached renderbuffer is a wrapper, then return wrapped renderbuffer.
References gl_framebuffer::Attachment, intel_renderbuffer(), and gl_renderbuffer_attachment::Renderbuffer.
Referenced by brw_clear(), brw_depthbuffer_format(), brw_emit_depthbuffer(), brw_fast_clear_depth(), brw_postdraw_set_buffers_need_resolve(), brw_upload_wm_unit(), brw_workaround_depthstencil_alignment(), gen6_emit_depth_stencil_hiz(), gen6_upload_depth_stencil_state(), gen7_emit_depth_stencil_hiz(), gen8_emit_depth_stencil_hiz(), gen8_upload_wm_depth_stencil(), intel_query_dri2_buffers(), intel_resolve_for_dri2_flush(), intel_update_dri2_buffers(), intel_update_image_buffers(), intel_update_state(), intel_validate_framebuffer(), intelSetTexBuffer2(), and pma_fix_enable().
intel_quantize_num_samples()
unsigned intel_quantize_num_samples (struct intel_screen * intel, unsigned num_samples)
Round up the requested multisample count to the next supported sample size.
References intel_supported_msaa_modes().
Referenced by intel_alloc_private_renderbuffer_storage(), intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_renderbuffer_get_tile_offsets(), intel_update_framebuffer(), intelCreateBuffer(), and intelInitScreen2().
intel_rb_format()
static mesa_format intel_rb_format (const struct intel_renderbuffer * rb) inline static
References swrast_renderbuffer::Base, intel_renderbuffer::Base, gl_renderbuffer::Format, intel_create_private_renderbuffer(), intel_create_renderbuffer(), intel_create_wrapped_renderbuffer(), intel_fbo_init(), and intel_renderbuffer_set_draw_offset().
Referenced by brw_depthbuffer_format(), brw_update_renderbuffer_surface(), do_blit_bitmap(), gen4_update_renderbuffer_surface(), intel_bits_per_pixel(), intel_update_image_buffers(), intel_validate_framebuffer(), and update_renderbuffer_read_surfaces().
intel_renderbuffer()
static struct intel_renderbuffer* intel_renderbuffer (struct gl_renderbuffer * rb) static
Return a gl_renderbuffer ptr casted to intel_renderbuffer.
NULL will be returned if the rb isn't really an intel_renderbuffer. This is determined by checking the ClassID.
References swrast_renderbuffer::Base, intel_renderbuffer::Base, gl_renderbuffer::ClassID, and INTEL_RB_CLASS.
Referenced by brw_blorp_clear_color(), brw_blorp_copytexsubimage(), brw_find_matching_rb(), brw_postdraw_set_buffers_need_resolve(), brw_predraw_set_aux_buffers(), brw_update_renderbuffer_surface(), brw_update_renderbuffer_surfaces(), do_blit_bitmap(), do_blit_copypixels(), do_blit_drawpixels(), do_single_blorp_clear(), gen4_update_renderbuffer_surface(), intel_alloc_private_renderbuffer_storage(), intel_bind_renderbuffer_tex_image(), intel_blit_framebuffer_with_blitter(), intel_copy_image_sub_data(), intel_create_image_from_renderbuffer(), intel_delete_renderbuffer(), intel_disable_rb_aux_buffer(), intel_get_renderbuffer(), intel_image_target_renderbuffer_storage(), intel_map_renderbuffer(), intel_readpixels_tiled_memcpy(), intel_render_object_purgeable(), intel_render_object_unpurgeable(), intel_render_texture(), intel_renderbuffer_att_set_needs_depth_resolve(), intel_unmap_renderbuffer(), intel_update_state(), intel_validate_framebuffer(), intelCopyTexSubImage(), try_blorp_blit(), and update_renderbuffer_read_surfaces().
intel_renderbuffer_att_set_needs_depth_resolve()
void intel_renderbuffer_att_set_needs_depth_resolve (struct gl_renderbuffer_attachment * att)
References intel_miptree_set_all_slices_need_depth_resolve(), intel_miptree_slice_set_needs_depth_resolve(), intel_renderbuffer(), gl_renderbuffer_attachment::Layered, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by brw_fast_clear_depth(), brw_postdraw_set_buffers_need_resolve(), and intel_renderbuffer_get_tile_offsets().
intel_renderbuffer_downsample()
void intel_renderbuffer_downsample (struct brw_context * brw, struct intel_renderbuffer * irb)
Downsample a winsys renderbuffer from mt to singlesample_mt.
If the miptree needs no downsample, then skip.
References intel_miptree_updownsample(), intel_renderbuffer::mt, intel_renderbuffer::need_downsample, and intel_renderbuffer::singlesample_mt.
Referenced by intel_map_renderbuffer(), intel_renderbuffer_get_tile_offsets(), and intel_resolve_for_dri2_flush().
intel_renderbuffer_get_tile_offsets()
static uint32_t intel_renderbuffer_get_tile_offsets (struct intel_renderbuffer * irb, uint32_t * tile_x, uint32_t * tile_y) inline static
References brw_render_cache_set_add_bo(), brw_render_cache_set_check_flush(), brw_render_cache_set_clear(), intel_miptree_get_tile_offsets(), intel_quantize_num_samples(), intel_renderbuffer_att_set_needs_depth_resolve(), intel_renderbuffer_downsample(), intel_renderbuffer_has_hiz(), intel_renderbuffer_move_to_temp(), intel_renderbuffer_resolve_depth(), intel_renderbuffer_resolve_hiz(), intel_renderbuffer_upsample(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by gen4_update_renderbuffer_surface().
intel_renderbuffer_has_hiz()
bool intel_renderbuffer_has_hiz (struct intel_renderbuffer * irb)
Does the renderbuffer have hiz enabled?
References intel_miptree_level_has_hiz(), intel_renderbuffer::mt, and intel_renderbuffer::mt_level.
Referenced by brw_emit_depthbuffer(), brw_fast_clear_depth(), brw_workaround_depthstencil_alignment(), intel_renderbuffer_get_tile_offsets(), intel_validate_framebuffer(), and pma_fix_enable().
intel_renderbuffer_move_to_temp()
void intel_renderbuffer_move_to_temp (struct brw_context * brw, struct intel_renderbuffer * irb, bool invalidate)
References swrast_renderbuffer::Base, swrast_texture_image::Base, intel_texture_image::base, intel_renderbuffer::Base, intel_get_image_dims(), intel_miptree_alloc_hiz(), intel_miptree_copy_teximage(), intel_miptree_create(), intel_miptree_reference(), intel_miptree_release(), intel_miptree_wants_hiz_buffer(), intel_renderbuffer_set_draw_offset(), intel_texture_image(), gl_texture_image::Level, intel_renderbuffer::mt, intel_texture_image::mt, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, and gl_texture_image::TexObject.
Referenced by brw_workaround_depthstencil_alignment(), gen4_update_renderbuffer_surface(), and intel_renderbuffer_get_tile_offsets().
intel_renderbuffer_resolve_depth()
bool intel_renderbuffer_resolve_depth (struct brw_context * brw, struct intel_renderbuffer * irb)
Perform a depth resolve on the renderbuffer.
It is safe to call this function on a renderbuffer without HiZ. In that case, the function is a no-op.
Returns
false if no resolve was needed
References intel_miptree_slice_resolve_depth(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by intel_renderbuffer_get_tile_offsets().
intel_renderbuffer_resolve_hiz()
bool intel_renderbuffer_resolve_hiz (struct brw_context * brw, struct intel_renderbuffer * irb)
Perform a HiZ resolve on the renderbuffer.
It is safe to call this function on a renderbuffer without HiZ. In that case, the function is a no-op.
Returns
false if no resolve was needed
References intel_miptree_slice_resolve_hiz(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by intel_renderbuffer_get_tile_offsets(), and intel_update_state().
intel_renderbuffer_set_draw_offset()
void intel_renderbuffer_set_draw_offset (struct intel_renderbuffer * irb)
References intel_renderbuffer::draw_x, intel_renderbuffer::draw_y, intel_miptree_get_image_offset(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by brw_workaround_depthstencil_alignment(), intel_rb_format(), intel_renderbuffer_move_to_temp(), and intel_renderbuffer_update_wrapper().
intel_renderbuffer_upsample()
void intel_renderbuffer_upsample (struct brw_context * brw, struct intel_renderbuffer * irb)
Upsample a winsys renderbuffer from singlesample_mt to mt.
The upsample is done unconditionally.
References intel_miptree_updownsample(), intel_renderbuffer::mt, intel_renderbuffer::need_downsample, and intel_renderbuffer::singlesample_mt.
Referenced by intel_process_dri2_buffer(), intel_renderbuffer_get_tile_offsets(), intel_unmap_renderbuffer(), and intel_update_image_buffer().