Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex_obj.h File Reference
#include "swrast/s_context.h"
Data Structures
struct intel_texture_object
struct intel_texture_image
intel_texture_image is a subclass of swrast_texture_image because we sometimes fall back to using the swrast module for software rendering.
Functions
static struct intel_texture_object * intel_texture_object (struct gl_texture_object *obj)
static struct intel_texture_image * intel_texture_image (struct gl_texture_image *img)
Function Documentation
intel_texture_image()
static struct intel_texture_image* intel_texture_image (struct gl_texture_image * img) static
Referenced by brw_blorp_copytexsubimage(), intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_bind_renderbuffer_tex_image(), intel_copy_image_sub_data(), intel_finalize_mipmap_tree(), intel_free_texture_image_buffer(), intel_gettexsubimage_tiled_memcpy(), intel_map_texture_image(), intel_miptree_match_image(), intel_render_texture(), intel_renderbuffer_move_to_temp(), intel_renderbuffer_update_wrapper(), intel_set_texture_image_mt(), intel_set_texture_storage_for_buffer_object(), intel_texsubimage_tiled_memcpy(), intel_texture_view(), intel_unmap_texture_image(), intelCopyTexSubImage(), intelTexImage(), and intelTexSubImage().
intel_texture_object()
static struct intel_texture_object* intel_texture_object (struct gl_texture_object * obj) static
Referenced by brw_populate_sampler_prog_key_data(), brw_update_texture_surface(), intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_bind_renderbuffer_tex_image(), intel_create_image_from_texture(), intel_finalize_mipmap_tree(), intel_image_target_texture_2d(), intel_miptree_copy_teximage(), intel_set_texture_image_mt(), intel_set_texture_storage_for_buffer_object(), intel_texture_object_purgeable(), intel_texture_object_unpurgeable(), intel_texture_view(), intel_update_state(), intelDeleteTextureObject(), update_image_surface(), and update_texture_image_param().