Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_resolve_map.c File Reference
#include "intel_resolve_map.h"
#include <stdlib.h>
Functions
void intel_resolve_map_set (struct exec_list *resolve_map, uint32_t level, uint32_t layer, unsigned need)
Set that the miptree slice at (level, layer) needs a resolve.
const struct intel_resolve_map * intel_resolve_map_find_any (const struct exec_list *resolve_map, uint32_t start_level, uint32_t num_levels, uint32_t start_layer, uint32_t num_layers)
Get an element from the map.
void intel_resolve_map_remove (struct intel_resolve_map *elem)
Remove and free an element from the map.
void intel_resolve_map_clear (struct exec_list *resolve_map)
Remove and free all elements of the map.
Function Documentation
intel_resolve_map_clear()
void intel_resolve_map_clear (struct exec_list * resolve_map)
Remove and free all elements of the map.
References foreach_in_list_safe.
Referenced by intel_miptree_release(), and intel_resolve_map_get().
intel_resolve_map_find_any()
const struct intel_resolve_map* intel_resolve_map_find_any (const struct exec_list * resolve_map, uint32_t start_level, uint32_t num_levels, uint32_t start_layer, uint32_t num_layers)
Get an element from the map.
Returns
null if element is not contained in map.
References foreach_list_typed, and intel_resolve_map::link.
Referenced by intel_miptree_has_color_unresolved(), intel_resolve_map_const_get(), and intel_resolve_map_get().
intel_resolve_map_remove()
void intel_resolve_map_remove (struct intel_resolve_map * elem)
Remove and free an element from the map.
References intel_resolve_map::link.
Referenced by intel_miptree_all_slices_resolve(), intel_miptree_all_slices_resolve_color(), intel_miptree_resolve_color(), intel_miptree_slice_resolve(), and intel_resolve_map_get().
intel_resolve_map_set()
void intel_resolve_map_set (struct exec_list * resolve_map, uint32_t level, uint32_t layer, unsigned need)
Set that the miptree slice at (level, layer) needs a resolve.
If a map element already exists with the given key, then the value is changed to the given value of need.
References foreach_list_typed, intel_resolve_map::layer, intel_resolve_map::level, intel_resolve_map::link, and intel_resolve_map::need.
Referenced by intel_miptree_set_fast_clear_state(), intel_miptree_slice_set_needs_depth_resolve(), and intel_miptree_slice_set_needs_hiz_resolve().