Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_pixel_draw.c File Reference
#include "main/enums.h"
#include "main/image.h"
#include "main/glformats.h"
#include "main/mtypes.h"
#include "main/condrender.h"
#include "main/fbobject.h"
#include "main/teximage.h"
#include "main/texobj.h"
#include "main/texstate.h"
#include "main/bufferobj.h"
#include "swrast/swrast.h"
#include "drivers/common/meta.h"
#include "brw_context.h"
#include "intel_screen.h"
#include "intel_blit.h"
#include "intel_buffers.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "intel_pixel.h"
#include "intel_buffer_objects.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Functions
static bool do_blit_drawpixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
void intelDrawPixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_PIXEL
Function Documentation
do_blit_drawpixels()
static bool do_blit_drawpixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels) static
References gl_framebuffer::_ColorDrawBuffers, _mesa_format_from_array_format(), _mesa_format_from_format_and_type(), _mesa_get_srgb_format_linear(), _mesa_image_offset(), _mesa_image_row_stride(), gl_framebuffer::_NumColorDrawBuffers, brw_context(), gl_pixelstore_attrib::BufferObj, gl_query_state::CurrentOcclusionObject, DBG, gl_context::DrawBuffer, GLuint, intel_buffer_object(), intel_bufferobj_buffer(), intel_check_blit_fragment_ops(), intel_miptree_blit(), intel_miptree_blit_compatible_formats(), intel_miptree_create_for_bo(), intel_miptree_release(), intel_prepare_render(), intel_renderbuffer(), gl_pixelstore_attrib::Invert, gl_pixelstore_attrib::LsbFirst, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::Query, gl_query_object::Result, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, and gl_pixelstore_attrib::SwapBytes.
Referenced by intelDrawPixels().
intelDrawPixels()
void intelDrawPixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * unpack, const GLvoid * pixels)
References _mesa_check_conditional_render(), _swrast_DrawPixels(), brw_context(), gl_pixelstore_attrib::BufferObj, do_blit_drawpixels(), and brw_context::perf_debug.
Referenced by intelInitPixelFuncs().