Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex_image.c File Reference
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/enums.h"
#include "main/bufferobj.h"
#include "main/context.h"
#include "main/formats.h"
#include "main/glformats.h"
#include "main/image.h"
#include "main/pbo.h"
#include "main/renderbuffer.h"
#include "main/texcompress.h"
#include "main/texgetimage.h"
#include "main/texobj.h"
#include "main/teximage.h"
#include "main/texstore.h"
#include "drivers/common/meta.h"
#include "intel_mipmap_tree.h"
#include "intel_buffer_objects.h"
#include "intel_batchbuffer.h"
#include "intel_tex.h"
#include "intel_blit.h"
#include "intel_fbo.h"
#include "intel_image.h"
#include "intel_tiled_memcpy.h"
#include "brw_context.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Functions
static unsigned get_base_dim (unsigned old_base_dim, unsigned new_level_dim, unsigned level)
struct intel_mipmap_tree * intel_miptree_create_for_teximage (struct brw_context *brw, struct intel_texture_object *intelObj, struct intel_texture_image *intelImage, uint32_t layout_flags)
static void intelTexImage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const void *pixels, const struct gl_pixelstore_attrib *unpack)
static void intel_set_texture_image_mt (struct brw_context *brw, struct gl_texture_image *image, GLenum internal_format, struct intel_mipmap_tree *mt)
static struct intel_mipmap_tree * create_mt_for_planar_dri_image (struct brw_context *brw, GLenum target, __DRIimage *image)
static struct intel_mipmap_tree * create_mt_for_dri_image (struct brw_context *brw, GLenum target, __DRIimage *image)
Binds a BO to a texture image, as if it was uploaded by glTexImage2D().
void intelSetTexBuffer2 (__DRIcontext *pDRICtx, GLint target, GLint texture_format, __DRIdrawable *dPriv)
static GLboolean intel_bind_renderbuffer_tex_image (struct gl_context *ctx, struct gl_renderbuffer *rb, struct gl_texture_image *image)
void intelSetTexBuffer (__DRIcontext *pDRICtx, GLint target, __DRIdrawable *dPriv)
static void intel_image_target_texture_2d (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLeglImageOES image_handle)
bool intel_gettexsubimage_tiled_memcpy (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
A fast path for glGetTexImage.
static void intel_get_tex_sub_image (struct gl_context *ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
static void flush_astc_denorms (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth)
static void intelCompressedTexSubImage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
void intelInitTextureImageFuncs (struct dd_function_table *functions)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Function Documentation
create_mt_for_dri_image()
static struct intel_mipmap_tree* create_mt_for_dri_image (struct brw_context * brw, GLenum target, __DRIimage * image) static
Binds a BO to a texture image, as if it was uploaded by glTexImage2D().
Used for GLX_EXT_texture_from_pixmap and EGL image extensions,
References _mesa_error(), brw_context::bo, brw_context::ctx, brw_context::has_surface_tile_offset, intel_miptree_create_for_bo(), intel_miptree_get_tile_offsets(), and intel_miptree_release().
Referenced by intel_image_target_texture_2d().
create_mt_for_planar_dri_image()
static struct intel_mipmap_tree* create_mt_for_planar_dri_image (struct brw_context * brw, GLenum target, __DRIimage * image) static
References brw_context::bo, intel_image_format::buffer_index, intel_image_format::dri_format, intel_image_format::height_shift, intel_miptree_create_for_bo(), intel_image_format::nplanes, intel_image_format::planes, and intel_image_format::width_shift.
Referenced by intel_image_target_texture_2d().
flush_astc_denorms()
static void flush_astc_denorms (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth) static
References _mesa_compute_compressed_pixelstore(), A, B, compressed_pixelstore::CopyBytesPerRow, compressed_pixelstore::CopyRowsPerSlice, compressed_pixelstore::CopySlices, gl_context::Driver, dd_function_table::MapTextureImage, R, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_context::Unpack.
Referenced by intelCompressedTexSubImage().
get_base_dim()
static unsigned get_base_dim (unsigned old_base_dim, unsigned new_level_dim, unsigned level) static
Referenced by intel_miptree_create_for_teximage().
intel_bind_renderbuffer_tex_image()
static GLboolean intel_bind_renderbuffer_tex_image (struct gl_context * ctx, struct gl_renderbuffer * rb, struct gl_texture_image * image) static
References _mesa_init_teximage_fields(), gl_renderbuffer::Format, gl_renderbuffer::Height, intel_miptree_reference(), intel_renderbuffer(), intel_texture_image(), intel_texture_object(), gl_renderbuffer::InternalFormat, intel_texture_object::mt, intel_renderbuffer::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_renderbuffer::NumSamples, gl_texture_image::NumSamples, gl_renderbuffer::TexImage, gl_texture_image::TexObject, and gl_renderbuffer::Width.
Referenced by intelInitTextureImageFuncs().
intel_get_tex_sub_image()
static void intel_get_tex_sub_image (struct gl_context * ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
References brw_context(), brw_emit_mi_flush(), gl_pixelstore_attrib::BufferObj, DBG, intel_gettexsubimage_tiled_memcpy(), gl_context::Pack, and brw_context::perf_debug.
Referenced by intelInitTextureImageFuncs().
intel_gettexsubimage_tiled_memcpy()
bool intel_gettexsubimage_tiled_memcpy (struct gl_context * ctx, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing)
A fast path for glGetTexImage.
See also
intel_readpixels_tiled_memcpy()
References gl_texture_image::_BaseFormat, _mesa_image_row_stride(), gl_pixelstore_attrib::Alignment, brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_context(), gl_pixelstore_attrib::BufferObj, DBG, brw_context::has_llc, brw_context::has_swizzling, intel_batchbuffer_flush, intel_get_memcpy(), intel_miptree_all_slices_resolve_color(), intel_texture_image(), gl_pixelstore_attrib::Invert, gl_texture_image::Level, gl_pixelstore_attrib::LsbFirst, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_image::mt, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and tiled_to_linear().
Referenced by intel_get_tex_sub_image().
intel_image_target_texture_2d()
static void intel_image_target_texture_2d (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj, struct gl_texture_image * texImage, GLeglImageOES image_handle) static
References _mesa_error(), _mesa_get_format_base_format(), brw_context(), create_mt_for_dri_image(), create_mt_for_planar_dri_image(), intel_screen::driScrnPriv, GL_TEXTURE_EXTERNAL_OES, intel_miptree_release(), intel_set_texture_image_mt(), intel_texture_object(), intel_texture_object::planar_format, and brw_context::screen.
Referenced by intelInitTextureImageFuncs().
intel_miptree_create_for_teximage()
struct intel_mipmap_tree* intel_miptree_create_for_teximage (struct brw_context * brw, struct intel_texture_object * intelObj, struct intel_texture_image * intelImage, uint32_t layout_flags)
References _mesa_get_tex_max_num_levels(), swrast_texture_image::Base, intel_texture_image::base, intel_texture_object::base, DBG, gl_texture_object::GenerateMipmap, get_base_dim(), GL_TEXTURE_EXTERNAL_OES, GLuint, intel_get_image_dims(), intel_miptree_create(), gl_texture_image::Level, gl_sampler_object::MinFilter, intel_texture_object::mt, gl_texture_image::NumSamples, gl_texture_object::Sampler, gl_texture_object::Target, and gl_texture_image::TexFormat.
Referenced by intel_alloc_texture_image_buffer().
intel_set_texture_image_mt()
static void intel_set_texture_image_mt (struct brw_context * brw, struct gl_texture_image * image, GLenum internal_format, struct intel_mipmap_tree * mt) static
References _mesa_init_teximage_fields(), intel_texture_image::base, brw_context::ctx, gl_context::Driver, dd_function_table::FreeTextureImageBuffer, intel_miptree_reference(), intel_texture_image(), intel_texture_object(), intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, swrast_texture_image::RowStride, and gl_texture_image::TexObject.
Referenced by intel_image_target_texture_2d(), and intelSetTexBuffer2().
intelCompressedTexSubImage()
static void intelCompressedTexSubImage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data) static
References _mesa_compressed_format_to_glenum(), _mesa_is_astc_format(), _mesa_is_srgb_format(), _mesa_store_compressed_texsubimage(), flush_astc_denorms(), brw_context::gen, and gl_texture_image::TexFormat.
Referenced by intelInitTextureImageFuncs().
intelInitTextureImageFuncs()
void intelInitTextureImageFuncs (struct dd_function_table * functions)
References dd_function_table::BindRenderbufferTexImage, dd_function_table::CompressedTexSubImage, dd_function_table::EGLImageTargetTexture2D, dd_function_table::GetTexSubImage, intel_bind_renderbuffer_tex_image(), intel_get_tex_sub_image(), intel_image_target_texture_2d(), intelCompressedTexSubImage(), intelTexImage(), and dd_function_table::TexImage.
Referenced by brw_init_driver_functions().
intelSetTexBuffer()
void intelSetTexBuffer (__DRIcontext * pDRICtx, GLint target, __DRIdrawable * dPriv)
References intelSetTexBuffer2().
intelSetTexBuffer2()
void intelSetTexBuffer2 (__DRIcontext * pDRICtx, GLint target, GLint texture_format, __DRIdrawable * dPriv)
References _mesa_get_current_tex_object(), _mesa_get_tex_image(), swrast_renderbuffer::Base, intel_renderbuffer::Base, BUFFER_FRONT_LEFT, brw_context::ctx, gl_renderbuffer::Height, intel_get_renderbuffer(), intel_miptree_create_for_bo(), intel_miptree_make_shareable(), intel_miptree_release(), intel_set_texture_image_mt(), intel_update_renderbuffers(), MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_NONE, intel_renderbuffer::mt, and gl_renderbuffer::Width.
Referenced by intelSetTexBuffer().
intelTexImage()
static void intelTexImage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLenum format, GLenum type, const void * pixels, const struct gl_pixelstore_attrib * unpack) static
References _mesa_enum_to_string(), _mesa_error(), _mesa_get_format_name(), _mesa_store_teximage(), dd_function_table::AllocTextureImageBuffer, DBG, gl_texture_image::Depth, gl_context::Driver, gl_texture_image::Height, intel_texsubimage_tiled_memcpy(), intel_texture_image(), gl_texture_image::Level, MESA_FORMAT_S_UINT8, intel_texture_image::mt, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and gl_texture_image::Width.
Referenced by intelInitTextureImageFuncs().