Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_resolve_map.h File Reference
#include <stdint.h>
#include "blorp/blorp.h"
#include "compiler/glsl/list.h"
Data Structures
struct intel_resolve_map
Map of miptree slices to needed resolves.
Enumerations
enum intel_fast_clear_state { INTEL_FAST_CLEAR_STATE_RESOLVED, INTEL_FAST_CLEAR_STATE_UNRESOLVED, INTEL_FAST_CLEAR_STATE_CLEAR }
Enum for keeping track of the fast clear state of a buffer associated with a miptree.
Functions
void intel_resolve_map_set (struct exec_list *resolve_map, uint32_t level, uint32_t layer, unsigned new_state)
Set that the miptree slice at (level, layer) needs a resolve.
const struct intel_resolve_map * intel_resolve_map_find_any (const struct exec_list *resolve_map, uint32_t start_level, uint32_t num_levels, uint32_t start_layer, uint32_t num_layers)
Get an element from the map.
static const struct intel_resolve_map * intel_resolve_map_const_get (const struct exec_list *resolve_map, uint32_t level, uint32_t layer)
static struct intel_resolve_map * intel_resolve_map_get (struct exec_list *resolve_map, uint32_t level, uint32_t layer)
void intel_resolve_map_remove (struct intel_resolve_map *resolve_map)
Remove and free an element from the map.
void intel_resolve_map_clear (struct exec_list *resolve_map)
Remove and free all elements of the map.
Enumeration Type Documentation
intel_fast_clear_state
enum intel_fast_clear_state
Enum for keeping track of the fast clear state of a buffer associated with a miptree.
Fast clear works by deferring the memory writes that would be used to clear the buffer, so that instead of performing them at the time of the clear operation, the hardware automatically performs them at the time that the buffer is later accessed for rendering. The MCS buffer keeps track of which regions of the buffer still have pending clear writes.
This enum keeps track of the driver's knowledge of pending fast clears in the MCS buffer.
MCS buffers only exist on Gen7+.
Enumerator
INTEL_FAST_CLEAR_STATE_RESOLVED
No deferred clears are pending for this miptree, and the contents of the color buffer are entirely correct.
An MCS buffer may or may not exist for this miptree. If it does exist, it is entirely in the "no deferred clears pending" state. If it does not exist, it will be created the first time a fast color clear is executed.
In this state, the color buffer can be used for purposes other than rendering without needing a render target resolve.
Since there is no such thing as a "fast color clear resolve" for MSAA buffers, an MSAA buffer will never be in this state.
INTEL_FAST_CLEAR_STATE_UNRESOLVED
An MCS buffer exists for this miptree, and deferred clears are pending for some regions of the color buffer, as indicated by the MCS buffer.
The contents of the color buffer are only correct for the regions where the MCS buffer doesn't indicate a deferred clear.
If a single-sample buffer is in this state, a render target resolve must be performed before it can be used for purposes other than rendering.
INTEL_FAST_CLEAR_STATE_CLEAR
An MCS buffer exists for this miptree, and deferred clears are pending for the entire color buffer, and the contents of the MCS buffer reflect this.
The contents of the color buffer are undefined.
If a single-sample buffer is in this state, a render target resolve must be performed before it can be used for purposes other than rendering.
If the client attempts to clear a buffer which is already in this state, the clear can be safely skipped, since the buffer is already clear.
Function Documentation
intel_resolve_map_clear()
void intel_resolve_map_clear (struct exec_list * resolve_map)
Remove and free all elements of the map.
References foreach_in_list_safe.
Referenced by intel_miptree_release(), and intel_resolve_map_get().
intel_resolve_map_const_get()
static const struct intel_resolve_map* intel_resolve_map_const_get (const struct exec_list * resolve_map, uint32_t level, uint32_t layer) static
References intel_resolve_map_find_any().
Referenced by intel_miptree_get_fast_clear_state().
intel_resolve_map_find_any()
const struct intel_resolve_map* intel_resolve_map_find_any (const struct exec_list * resolve_map, uint32_t start_level, uint32_t num_levels, uint32_t start_layer, uint32_t num_layers)
Get an element from the map.
Returns
null if element is not contained in map.
References foreach_list_typed, and intel_resolve_map::link.
Referenced by intel_miptree_has_color_unresolved(), intel_resolve_map_const_get(), and intel_resolve_map_get().
intel_resolve_map_get()
static struct intel_resolve_map* intel_resolve_map_get (struct exec_list * resolve_map, uint32_t level, uint32_t layer) static
References intel_resolve_map_clear(), intel_resolve_map_find_any(), and intel_resolve_map_remove().
Referenced by intel_miptree_resolve_color(), and intel_miptree_slice_resolve().
intel_resolve_map_remove()
void intel_resolve_map_remove (struct intel_resolve_map * resolve_map)
Remove and free an element from the map.
References intel_resolve_map::link.
Referenced by intel_miptree_all_slices_resolve(), intel_miptree_all_slices_resolve_color(), intel_miptree_resolve_color(), intel_miptree_slice_resolve(), and intel_resolve_map_get().
intel_resolve_map_set()
void intel_resolve_map_set (struct exec_list * resolve_map, uint32_t level, uint32_t layer, unsigned need)
Set that the miptree slice at (level, layer) needs a resolve.
If a map element already exists with the given key, then the value is changed to the given value of need.
References foreach_list_typed, intel_resolve_map::layer, intel_resolve_map::level, intel_resolve_map::link, and intel_resolve_map::need.
Referenced by intel_miptree_set_fast_clear_state(), intel_miptree_slice_set_needs_depth_resolve(), and intel_miptree_slice_set_needs_hiz_resolve().