Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex_subimage.c File Reference
#include "main/bufferobj.h"
#include "main/image.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/pbo.h"
#include "main/texobj.h"
#include "main/texstore.h"
#include "main/texcompress.h"
#include "main/enums.h"
#include "drivers/common/meta.h"
#include "brw_context.h"
#include "intel_batchbuffer.h"
#include "intel_tex.h"
#include "intel_mipmap_tree.h"
#include "intel_blit.h"
#include "intel_tiled_memcpy.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Functions
bool intel_texsubimage_tiled_memcpy (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing, bool for_glTexImage)
A fast path for glTexImage and glTexSubImage.
static void intelTexSubImage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
void intelInitTextureSubImageFuncs (struct dd_function_table *functions)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Function Documentation
intel_texsubimage_tiled_memcpy()
bool intel_texsubimage_tiled_memcpy (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing, bool for_glTexImage)
A fast path for glTexImage and glTexSubImage.
Parameters
for_glTexImage Was this called from glTexImage or glTexSubImage?
This fast path is taken when the texture format is BGRA, RGBA, A or L and when the texture memory is X- or Y-tiled. It uploads the texture data by mapping the texture memory without a GTT fence, thus acquiring a tiled view of the memory, and then copying sucessive spans within each tile.
This is a performance win over the conventional texture upload path because it avoids the performance penalty of writing through the write-combine buffer. In the conventional texture upload path, texstore.c:store_texsubimage(), the texture memory is mapped through a GTT fence, thus acquiring a linear view of the memory, then each row in the image is memcpy'd. In this fast path, we replace each row's copy with a sequence of copies over each linear span in tile.
One use case is Google Chrome's paint rectangles. Chrome (as of version 21) renders each page as a tiling of 256x256 GL_BGRA textures. Each page's content is initially uploaded with glTexImage2D and damaged regions are updated with glTexSubImage2D. On some workloads, the performance gain of this fastpath on Sandybridge is over 5x.
References gl_context::_ImageTransferState, _mesa_image_row_stride(), gl_pixelstore_attrib::Alignment, dd_function_table::AllocTextureImageBuffer, brw_context::batch, intel_batchbuffer::bo, brw_bo_map(), brw_context(), gl_pixelstore_attrib::BufferObj, DBG, gl_context::Driver, brw_context::has_llc, brw_context::has_swizzling, intel_batchbuffer_flush, intel_get_memcpy(), intel_miptree_all_slices_resolve_color(), intel_texture_image(), gl_pixelstore_attrib::Invert, gl_texture_image::Level, linear_to_tiled(), gl_pixelstore_attrib::LsbFirst, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_image::mt, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::TexObject.
Referenced by intelTexImage(), and intelTexSubImage().
intelInitTextureSubImageFuncs()
void intelInitTextureSubImageFuncs (struct dd_function_table * functions)
References intelTexSubImage(), and dd_function_table::TexSubImage.
Referenced by brw_init_driver_functions().
intelTexSubImage()
static void intelTexSubImage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
References _mesa_enum_to_string(), _mesa_get_format_name(), _mesa_store_texsubimage(), DBG, gl_texture_image::Depth, gl_texture_image::Height, intel_texsubimage_tiled_memcpy(), intel_texture_image(), gl_texture_image::Level, MESA_FORMAT_S_UINT8, intel_texture_image::mt, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and gl_texture_image::Width.
Referenced by intelInitTextureSubImageFuncs().