Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tex.c File Reference
#include "swrast/swrast.h"
#include "main/renderbuffer.h"
#include "main/texobj.h"
#include "main/teximage.h"
#include "main/mipmap.h"
#include "drivers/common/meta.h"
#include "brw_context.h"
#include "brw_defines.h"
#include "intel_buffer_objects.h"
#include "intel_mipmap_tree.h"
#include "intel_tex.h"
#include "intel_fbo.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Functions
static struct gl_texture_image * intelNewTextureImage (struct gl_context *ctx)
static void intelDeleteTextureImage (struct gl_context *ctx, struct gl_texture_image *img)
static struct gl_texture_object * intelNewTextureObject (struct gl_context *ctx, GLuint name, GLenum target)
static void intelDeleteTextureObject (struct gl_context *ctx, struct gl_texture_object *texObj)
static GLboolean intel_alloc_texture_image_buffer (struct gl_context *ctx, struct gl_texture_image *image)
static GLboolean intel_alloc_texture_storage (struct gl_context *ctx, struct gl_texture_object *texobj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
ctx->Driver.AllocTextureStorage() handler.
static void intel_free_texture_image_buffer (struct gl_context *ctx, struct gl_texture_image *texImage)
static void intel_map_texture_image (struct gl_context *ctx, struct gl_texture_image *tex_image, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **map, GLint *out_stride)
Map texture memory/buffer into user space.
static void intel_unmap_texture_image (struct gl_context *ctx, struct gl_texture_image *tex_image, GLuint slice)
static GLboolean intel_texture_view (struct gl_context *ctx, struct gl_texture_object *texObj, struct gl_texture_object *origTexObj)
static bool intel_set_texture_storage_for_buffer_object (struct gl_context *ctx, struct gl_texture_object *tex_obj, struct gl_buffer_object *buffer_obj, uint32_t buffer_offset, uint32_t row_stride, bool read_only)
static void intel_texture_barrier (struct gl_context *ctx)
void intelInitTextureFuncs (struct dd_function_table *functions)
Macro Definition Documentation
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_TEXTURE
Function Documentation
intel_alloc_texture_image_buffer()
static GLboolean intel_alloc_texture_image_buffer (struct gl_context * ctx, struct gl_texture_image * image) static
References _swrast_init_texture_image(), gl_texture_image::Border, brw_context(), DBG, gl_texture_image::Depth, gl_context::Driver, dd_function_table::FreeTextureImageBuffer, gl_texture_image::Height, intel_miptree_create_for_teximage(), intel_miptree_match_image(), intel_miptree_reference(), intel_quantize_num_samples(), intel_texture_image(), intel_texture_object(), gl_texture_image::Level, intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_image::NumSamples, brw_context::screen, gl_texture_image::TexObject, and gl_texture_image::Width.
Referenced by intelInitTextureFuncs().
intel_alloc_texture_storage()
static GLboolean intel_alloc_texture_storage (struct gl_context * ctx, struct gl_texture_object * texobj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth) static
ctx->Driver.AllocTextureStorage() handler.
Compare this to _mesa_AllocTextureStorage_sw, which would call into intel_alloc_texture_image_buffer() above.
References intel_texture_object::_Format, _swrast_free_texture_image_buffer(), _swrast_init_texture_image(), brw_context(), gl_texture_object::Image, intel_get_image_dims(), intel_miptree_create(), intel_miptree_match_image(), intel_miptree_reference(), intel_miptree_release(), intel_quantize_num_samples(), intel_texture_image(), intel_texture_object(), intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_image::NumSamples, brw_context::screen, gl_texture_object::Target, gl_texture_image::TexFormat, intel_texture_object::validated_first_level, and intel_texture_object::validated_last_level.
Referenced by intelInitTextureFuncs().
intel_free_texture_image_buffer()
static void intel_free_texture_image_buffer (struct gl_context * ctx, struct gl_texture_image * texImage) static
References _swrast_free_texture_image_buffer(), DBG, intel_miptree_release(), intel_texture_image(), and intel_texture_image::mt.
Referenced by intelInitTextureFuncs().
intel_map_texture_image()
static void intel_map_texture_image (struct gl_context * ctx, struct gl_texture_image * tex_image, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte ** map, GLint * out_stride) static
Map texture memory/buffer into user space.
Note: the region of interest parameters are ignored here.
Parameters
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT
mapOut returns start of mapping of region of interest
rowStrideOut returns row stride in bytes
References brw_context(), gl_texture_image::Face, intel_miptree_map(), intel_texture_image(), gl_texture_image::Level, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_image::mt, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by intelInitTextureFuncs().
intel_set_texture_storage_for_buffer_object()
static bool intel_set_texture_storage_for_buffer_object (struct gl_context * ctx, struct gl_texture_object * tex_obj, struct gl_buffer_object * buffer_obj, uint32_t buffer_offset, uint32_t row_stride, bool read_only) static
References intel_texture_object::_Format, _mesa_get_format_bytes(), _swrast_init_texture_image(), brw_context(), gl_texture_image::Depth, brw_context::format_supported_as_render_target, gl_texture_image::Height, gl_texture_object::Image, intel_buffer_object(), intel_bufferobj_buffer(), intel_miptree_create_for_bo(), intel_miptree_reference(), intel_texture_image(), intel_texture_object(), intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_image::TexFormat, intel_texture_object::validated_first_level, intel_texture_object::validated_last_level, and gl_texture_image::Width.
Referenced by intelInitTextureFuncs().
intel_texture_barrier()
static void intel_texture_barrier (struct gl_context * ctx) static
References brw_context(), brw_emit_mi_flush(), brw_emit_pipe_control_flush(), brw_context::gen, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_RENDER_TARGET_FLUSH, and PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE.
Referenced by intelInitTextureFuncs().
intel_texture_view()
static GLboolean intel_texture_view (struct gl_context * ctx, struct gl_texture_object * texObj, struct gl_texture_object * origTexObj) static
References intel_texture_object::_Format, brw_context(), gl_texture_object::Image, intel_depth_format_for_depthstencil_format(), intel_lower_compressed_format(), intel_miptree_reference(), intel_texture_image(), intel_texture_object(), intel_texture_object::mt, intel_texture_image::mt, intel_texture_object::needs_validate, gl_texture_object::NumLevels, gl_texture_object::Target, gl_texture_image::TexFormat, intel_texture_object::validated_first_level, and intel_texture_object::validated_last_level.
Referenced by intelInitTextureFuncs().
intel_unmap_texture_image()
static void intel_unmap_texture_image (struct gl_context * ctx, struct gl_texture_image * tex_image, GLuint slice) static
References brw_context(), gl_texture_image::Face, intel_miptree_unmap(), intel_texture_image(), gl_texture_image::Level, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_texture_image::mt, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by intelInitTextureFuncs().
intelDeleteTextureImage()
static void intelDeleteTextureImage (struct gl_context * ctx, struct gl_texture_image * img) static
References _mesa_delete_texture_image().
Referenced by intelInitTextureFuncs().
intelDeleteTextureObject()
static void intelDeleteTextureObject (struct gl_context * ctx, struct gl_texture_object * texObj) static
References _mesa_delete_texture_object(), intel_miptree_release(), intel_texture_object(), and intel_texture_object::mt.
Referenced by intelInitTextureFuncs().
intelInitTextureFuncs()
void intelInitTextureFuncs (struct dd_function_table * functions)
References dd_function_table::AllocTextureImageBuffer, dd_function_table::AllocTextureStorage, dd_function_table::DeleteTexture, dd_function_table::DeleteTextureImage, dd_function_table::FreeTextureImageBuffer, intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_free_texture_image_buffer(), intel_map_texture_image(), intel_set_texture_storage_for_buffer_object(), intel_texture_barrier(), intel_texture_view(), intel_unmap_texture_image(), intelDeleteTextureImage(), intelDeleteTextureObject(), intelNewTextureImage(), intelNewTextureObject(), dd_function_table::MapTextureImage, dd_function_table::NewTextureImage, dd_function_table::NewTextureObject, dd_function_table::SetTextureStorageForBufferObject, dd_function_table::TextureBarrier, dd_function_table::TextureView, and dd_function_table::UnmapTextureImage.
Referenced by brw_init_driver_functions().
intelNewTextureImage()
static struct gl_texture_image* intelNewTextureImage (struct gl_context * ctx) static
References CALLOC_STRUCT, DBG, and void.
Referenced by intelInitTextureFuncs().
intelNewTextureObject()
static struct gl_texture_object* intelNewTextureObject (struct gl_context * ctx, GLuint name, GLenum target) static
References _mesa_initialize_texture_object(), intel_texture_object::base, CALLOC_STRUCT, DBG, intel_texture_object::needs_validate, and void.
Referenced by intelInitTextureFuncs().