Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_copy_image.c File Reference
#include "brw_blorp.h"
#include "intel_fbo.h"
#include "intel_tex.h"
#include "intel_blit.h"
#include "intel_mipmap_tree.h"
#include "main/formats.h"
#include "main/teximage.h"
#include "drivers/common/meta.h"
Functions
static void copy_image_with_memcpy (struct brw_context *brw, struct intel_mipmap_tree *src_mt, int src_level, int src_x, int src_y, int src_z, struct intel_mipmap_tree *dst_mt, int dst_level, int dst_x, int dst_y, int dst_z, int src_width, int src_height)
static void copy_miptrees (struct brw_context *brw, struct intel_mipmap_tree *src_mt, int src_x, int src_y, int src_z, unsigned src_level, struct intel_mipmap_tree *dst_mt, int dst_x, int dst_y, int dst_z, unsigned dst_level, int src_width, int src_height)
static void intel_copy_image_sub_data (struct gl_context *ctx, struct gl_texture_image *src_image, struct gl_renderbuffer *src_renderbuffer, int src_x, int src_y, int src_z, struct gl_texture_image *dst_image, struct gl_renderbuffer *dst_renderbuffer, int dst_x, int dst_y, int dst_z, int src_width, int src_height)
void intelInitCopyImageFuncs (struct dd_function_table *functions)
Function Documentation
copy_image_with_memcpy()
static void copy_image_with_memcpy (struct brw_context * brw, struct intel_mipmap_tree * src_mt, int src_level, int src_x, int src_y, int src_z, struct intel_mipmap_tree * dst_mt, int dst_level, int dst_x, int dst_y, int dst_z, int src_width, int src_height) static
References _mesa_get_format_block_size(), _mesa_get_format_bytes(), GLuint, intel_miptree_map(), and intel_miptree_unmap().
Referenced by copy_miptrees().
copy_miptrees()
static void copy_miptrees (struct brw_context * brw, struct intel_mipmap_tree * src_mt, int src_x, int src_y, int src_z, unsigned src_level, struct intel_mipmap_tree * dst_mt, int dst_x, int dst_y, int dst_z, unsigned dst_level, int src_width, int src_height) static
References _mesa_get_format_block_size(), brw_blorp_copy_miptrees(), copy_image_with_memcpy(), brw_context::gen, intel_miptree_all_slices_resolve_color(), intel_miptree_all_slices_resolve_depth(), intel_miptree_all_slices_resolve_hiz(), and intel_miptree_copy().
Referenced by intel_copy_image_sub_data().
intel_copy_image_sub_data()
static void intel_copy_image_sub_data (struct gl_context * ctx, struct gl_texture_image * src_image, struct gl_renderbuffer * src_renderbuffer, int src_x, int src_y, int src_z, struct gl_texture_image * dst_image, struct gl_renderbuffer * dst_renderbuffer, int dst_x, int dst_y, int dst_z, int src_width, int src_height) static
References brw_context(), copy_miptrees(), gl_texture_image::Face, intel_renderbuffer(), intel_texture_image(), gl_texture_image::Level, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_renderbuffer::mt, intel_texture_image::mt, brw_context::stencil_mt, gl_texture_object::Target, gl_renderbuffer::TexImage, and gl_texture_image::TexObject.
Referenced by intelInitCopyImageFuncs().
intelInitCopyImageFuncs()
void intelInitCopyImageFuncs (struct dd_function_table * functions)
References dd_function_table::CopyImageSubData, and intel_copy_image_sub_data().
Referenced by brw_init_driver_functions().