Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_fbo.c File Reference
#include "main/enums.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "main/renderbuffer.h"
#include "main/context.h"
#include "main/teximage.h"
#include "main/image.h"
#include "main/condrender.h"
#include "util/hash_table.h"
#include "util/set.h"
#include "swrast/swrast.h"
#include "drivers/common/meta.h"
#include "intel_batchbuffer.h"
#include "intel_buffers.h"
#include "intel_blit.h"
#include "intel_fbo.h"
#include "intel_mipmap_tree.h"
#include "intel_image.h"
#include "intel_screen.h"
#include "intel_tex.h"
#include "brw_context.h"
#include "brw_defines.h"
Macros
#define FILE_DEBUG_FLAG DEBUG_FBO
#define fbo_incomplete(fb, ...)
Functions
static void intel_delete_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
Called by gl_renderbuffer::Delete()
void intel_renderbuffer_downsample (struct brw_context *brw, struct intel_renderbuffer *irb)
Downsample a winsys renderbuffer from mt to singlesample_mt.
void intel_renderbuffer_upsample (struct brw_context *brw, struct intel_renderbuffer *irb)
Upsample a winsys renderbuffer from singlesample_mt to mt.
static void intel_map_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **out_map, GLint *out_stride)
static void intel_unmap_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
unsigned intel_quantize_num_samples (struct intel_screen *intel, unsigned num_samples)
Round up the requested multisample count to the next supported sample size.
static mesa_format intel_renderbuffer_format (struct gl_context *ctx, GLenum internalFormat)
static GLboolean intel_alloc_private_renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLuint width, GLuint height)
static GLboolean intel_alloc_renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLuint width, GLuint height)
Called via glRenderbufferStorageEXT() to set the format and allocate storage for a user-created renderbuffer.
static void intel_image_target_renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, void *image_handle)
static GLboolean intel_alloc_window_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLuint width, GLuint height)
Called by _mesa_resize_framebuffer() for each hardware renderbuffer when a window system framebuffer is resized.
static GLboolean intel_nop_alloc_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLuint width, GLuint height)
Dummy function for gl_renderbuffer::AllocStorage()
struct intel_renderbuffer * intel_create_renderbuffer (mesa_format format, unsigned num_samples)
Create a new intel_renderbuffer which corresponds to an on-screen window, not a user-created renderbuffer.
struct intel_renderbuffer * intel_create_private_renderbuffer (mesa_format format, unsigned num_samples)
Private window-system buffers (as opposed to ones shared with the display server created with intel_create_renderbuffer()) are most similar in their handling to user-created renderbuffers, but they have a resize handler that may be called at intel_update_renderbuffers() time.
static struct gl_renderbuffer * intel_new_renderbuffer (struct gl_context *ctx, GLuint name)
Create a new renderbuffer object.
static bool intel_renderbuffer_update_wrapper (struct brw_context *brw, struct intel_renderbuffer *irb, struct gl_texture_image *image, uint32_t layer, bool layered)
void intel_renderbuffer_set_draw_offset (struct intel_renderbuffer *irb)
static void intel_render_texture (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Called by glFramebufferTexture[123]DEXT() (and other places) to prepare for rendering into texture memory.
static void intel_validate_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Do additional "completeness" testing of a framebuffer object.
static GLbitfield intel_blit_framebuffer_with_blitter (struct gl_context *ctx, const struct gl_framebuffer *readFb, const struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask)
Try to do a glBlitFramebuffer using glCopyTexSubImage2D We can do this when the dst renderbuffer is actually a texture and there is no scaling, mirroring or scissoring.
static void intel_blit_framebuffer (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
static void gen4_blit_framebuffer (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Gen4-5 implementation of glBlitFrameBuffer().
bool intel_renderbuffer_has_hiz (struct intel_renderbuffer *irb)
Does the renderbuffer have hiz enabled?
bool intel_renderbuffer_resolve_hiz (struct brw_context *brw, struct intel_renderbuffer *irb)
Perform a HiZ resolve on the renderbuffer.
void intel_renderbuffer_att_set_needs_depth_resolve (struct gl_renderbuffer_attachment *att)
bool intel_renderbuffer_resolve_depth (struct brw_context *brw, struct intel_renderbuffer *irb)
Perform a depth resolve on the renderbuffer.
void intel_renderbuffer_move_to_temp (struct brw_context *brw, struct intel_renderbuffer *irb, bool invalidate)
void brw_render_cache_set_clear (struct brw_context *brw)
void brw_render_cache_set_add_bo (struct brw_context *brw, drm_intel_bo *bo)
void brw_render_cache_set_check_flush (struct brw_context *brw, drm_intel_bo *bo)
Emits an appropriate flush for a BO if it has been rendered to within the same batchbuffer as a read that's about to be emitted.
void intel_fbo_init (struct brw_context *brw)
Do one-time context initializations related to GL_EXT_framebuffer_object.
Macro Definition Documentation
fbo_incomplete
#define fbo_incomplete (fb, ...)
Value:
do {                                          \
      static GLuint msg_id = 0;                                               \
      if (unlikely(ctx->Const.ContextFlags & GL_CONTEXT_FLAG_DEBUG_BIT)) {    \
         _mesa_gl_debug(ctx, &msg_id,                                         \
                        MESA_DEBUG_SOURCE_API,                                \
                        MESA_DEBUG_TYPE_OTHER,                                \
                        MESA_DEBUG_SEVERITY_MEDIUM,                           \
                        __VA_ARGS__);                                         \
      }                                                                       \
      DBG(__VA_ARGS__);                                                       \
      fb->_Status = GL_FRAMEBUFFER_UNSUPPORTED;                               \
   } while (0)
Referenced by intel_validate_framebuffer().
FILE_DEBUG_FLAG
#define FILE_DEBUG_FLAG DEBUG_FBO
Function Documentation
brw_render_cache_set_add_bo()
void brw_render_cache_set_add_bo (struct brw_context * brw, drm_intel_bo * bo)
References brw_context::render_cache.
Referenced by blorp_exec(), brw_postdraw_set_buffers_need_resolve(), gen8_hiz_exec(), and intel_renderbuffer_get_tile_offsets().
brw_render_cache_set_check_flush()
void brw_render_cache_set_check_flush (struct brw_context * brw, drm_intel_bo * bo)
Emits an appropriate flush for a BO if it has been rendered to within the same batchbuffer as a read that's about to be emitted.
The GPU has separate, incoherent caches for the render cache and the sampler cache, along with other caches. Usually data in the different caches don't interact (e.g. we don't render to our driver-generated immediate constant data), but for render-to-texture in FBOs we definitely do. When a batchbuffer is flushed, the kernel will ensure that everything necessary is flushed before another use of that BO, but for reuse from different caches within a batchbuffer, it's all our responsibility.
References brw_emit_mi_flush(), brw_emit_pipe_control_flush(), brw_render_cache_set_clear(), brw_context::gen, PIPE_CONTROL_CONST_CACHE_INVALIDATE, PIPE_CONTROL_CS_STALL, PIPE_CONTROL_DEPTH_CACHE_FLUSH, PIPE_CONTROL_RENDER_TARGET_FLUSH, PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE, and brw_context::render_cache.
Referenced by blorp_exec(), brw_emit_depthbuffer(), intel_renderbuffer_get_tile_offsets(), intel_update_r8stencil(), and intel_update_state().
brw_render_cache_set_clear()
void brw_render_cache_set_clear (struct brw_context * brw)
References brw_context::render_cache.
Referenced by brw_render_cache_set_check_flush(), intel_batchbuffer_reset_and_clear_render_cache(), and intel_renderbuffer_get_tile_offsets().
gen4_blit_framebuffer()
static void gen4_blit_framebuffer (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) static
Gen4-5 implementation of glBlitFrameBuffer().
Tries BLT, Meta, then swrast.
Gen4-5 have a single ring for both 3D and BLT operations, so there's no inter-ring synchronization issues like on Gen6+. It is apparently faster than using the 3D pipeline. Original Gen4 also has to rebase and copy miptree slices in order to render to unaligned locations.
References _mesa_check_conditional_render(), _swrast_BlitFramebuffer(), and intel_blit_framebuffer_with_blitter().
Referenced by intel_fbo_init().
intel_alloc_private_renderbuffer_storage()
static GLboolean intel_alloc_private_renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLuint width, GLuint height) static
References gl_renderbuffer::_BaseFormat, _mesa_enum_to_string(), _mesa_get_format_base_format(), _mesa_get_format_name(), brw_context(), DBG, gl_renderbuffer::Format, gl_renderbuffer::Height, intel_miptree_create_for_renderbuffer(), intel_miptree_release(), intel_quantize_num_samples(), intel_renderbuffer(), intel_renderbuffer::layer_count, MESA_FORMAT_NONE, intel_renderbuffer::mt, gl_renderbuffer::NumSamples, brw_context::screen, and gl_renderbuffer::Width.
Referenced by intel_alloc_renderbuffer_storage(), and intel_create_private_renderbuffer().
intel_alloc_renderbuffer_storage()
static GLboolean intel_alloc_renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLuint width, GLuint height) static
Called via glRenderbufferStorageEXT() to set the format and allocate storage for a user-created renderbuffer.
References gl_renderbuffer::Format, intel_alloc_private_renderbuffer_storage(), and intel_renderbuffer_format().
Referenced by intel_new_renderbuffer().
intel_alloc_window_storage()
static GLboolean intel_alloc_window_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLuint width, GLuint height) static
Called by _mesa_resize_framebuffer() for each hardware renderbuffer when a window system framebuffer is resized.
Any actual buffer reallocations for hardware renderbuffers (which would have triggered _mesa_resize_framebuffer()) were done by intel_process_dri2_buffer().
References gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, gl_renderbuffer::Name, void, and gl_renderbuffer::Width.
Referenced by intel_create_renderbuffer().
intel_blit_framebuffer()
static void intel_blit_framebuffer (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) static
References _mesa_check_conditional_render(), _swrast_BlitFramebuffer(), brw_blorp_framebuffer(), brw_context(), brw_context::gen, and intel_blit_framebuffer_with_blitter().
Referenced by intel_fbo_init().
intel_blit_framebuffer_with_blitter()
static GLbitfield intel_blit_framebuffer_with_blitter (struct gl_context * ctx, const struct gl_framebuffer * readFb, const struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask) static
Try to do a glBlitFramebuffer using glCopyTexSubImage2D We can do this when the dst renderbuffer is actually a texture and there is no scaling, mirroring or scissoring.
Returns
new buffer mask indicating the buffers left to blit using the normal path.
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_ColorReadBuffer, _mesa_get_format_color_encoding(), gl_framebuffer::_NumColorDrawBuffers, brw_context(), gl_context::Color, gl_scissor_attrib::EnableFlags, intel_miptree_blit(), intel_prepare_render(), intel_renderbuffer(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_renderbuffer::Name, gl_context::Scissor, and gl_colorbuffer_attrib::sRGBEnabled.
Referenced by gen4_blit_framebuffer(), and intel_blit_framebuffer().
intel_create_private_renderbuffer()
struct intel_renderbuffer* intel_create_private_renderbuffer (mesa_format format, unsigned num_samples)
Private window-system buffers (as opposed to ones shared with the display server created with intel_create_renderbuffer()) are most similar in their handling to user-created renderbuffers, but they have a resize handler that may be called at intel_update_renderbuffers() time.
Parameters
num_samples must be quantized.
References gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, intel_renderbuffer::Base, intel_alloc_private_renderbuffer_storage(), and intel_create_renderbuffer().
Referenced by intel_rb_format(), and intelCreateBuffer().
intel_create_renderbuffer()
struct intel_renderbuffer* intel_create_renderbuffer (mesa_format format, unsigned num_samples)
Create a new intel_renderbuffer which corresponds to an on-screen window, not a user-created renderbuffer.
Parameters
num_samples must be quantized.
References gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_get_format_base_format(), _mesa_init_renderbuffer(), gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, intel_renderbuffer::Base, CALLOC_STRUCT, gl_renderbuffer::ClassID, gl_renderbuffer::Delete, gl_renderbuffer::Format, intel_alloc_window_storage(), intel_delete_renderbuffer(), INTEL_RB_CLASS, gl_renderbuffer::InternalFormat, intel_renderbuffer::layer_count, and gl_renderbuffer::NumSamples.
Referenced by intel_create_private_renderbuffer(), intel_rb_format(), and intelCreateBuffer().
intel_delete_renderbuffer()
static void intel_delete_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb) static
Called by gl_renderbuffer::Delete()
References _mesa_delete_renderbuffer(), intel_miptree_release(), intel_renderbuffer(), intel_renderbuffer::mt, and intel_renderbuffer::singlesample_mt.
Referenced by intel_create_renderbuffer(), and intel_new_renderbuffer().
intel_fbo_init()
void intel_fbo_init (struct brw_context * brw)
Do one-time context initializations related to GL_EXT_framebuffer_object.
Hook in device driver functions.
References dd_function_table::BlitFramebuffer, brw_context::ctx, gl_context::Driver, dd_function_table::EGLImageTargetRenderbufferStorage, brw_context::gen, gen4_blit_framebuffer(), intel_blit_framebuffer(), intel_image_target_renderbuffer_storage(), intel_map_renderbuffer(), intel_new_renderbuffer(), intel_render_texture(), intel_unmap_renderbuffer(), intel_validate_framebuffer(), dd_function_table::MapRenderbuffer, dd_function_table::NewRenderbuffer, brw_context::render_cache, dd_function_table::RenderTexture, dd_function_table::UnmapRenderbuffer, and dd_function_table::ValidateFramebuffer.
Referenced by brwCreateContext(), and intel_rb_format().
intel_image_target_renderbuffer_storage()
static void intel_image_target_renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, void * image_handle) static
References gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_get_format_base_format(), brw_context::bo, brw_context(), intel_screen::driScrnPriv, gl_renderbuffer::Format, brw_context::format_supported_as_render_target, gl_renderbuffer::Height, intel_miptree_create_for_bo(), intel_miptree_release(), intel_renderbuffer(), gl_renderbuffer::InternalFormat, intel_renderbuffer::layer_count, intel_renderbuffer::mt, gl_renderbuffer::NeedsFinishRenderTexture, brw_context::screen, and gl_renderbuffer::Width.
Referenced by intel_fbo_init().
intel_map_renderbuffer()
static void intel_map_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte ** out_map, GLint * out_stride) static
See also
dd_function_table::MapRenderbuffer
References _mesa_get_format_bytes(), _mesa_get_format_name(), brw_context(), swrast_renderbuffer::Buffer, DBG, gl_renderbuffer::Format, gl_renderbuffer::Height, intel_miptree_create_for_renderbuffer(), intel_miptree_map(), intel_prepare_render(), intel_renderbuffer(), intel_renderbuffer_downsample(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_renderbuffer::Name, intel_renderbuffer::need_downsample, intel_renderbuffer::need_map_upsample, gl_renderbuffer::NumSamples, swrast_renderbuffer::RowStride, intel_renderbuffer::singlesample_mt, intel_renderbuffer::singlesample_mt_is_tmp, and gl_renderbuffer::Width.
Referenced by intel_fbo_init().
intel_new_renderbuffer()
static struct gl_renderbuffer* intel_new_renderbuffer (struct gl_context * ctx, GLuint name) static
Create a new renderbuffer object.
Typically called via glBindRenderbufferEXT().
References _mesa_error(), _mesa_init_renderbuffer(), gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, intel_renderbuffer::Base, CALLOC_STRUCT, gl_renderbuffer::ClassID, gl_renderbuffer::Delete, intel_alloc_renderbuffer_storage(), intel_delete_renderbuffer(), and INTEL_RB_CLASS.
Referenced by intel_fbo_init().
intel_nop_alloc_storage()
static GLboolean intel_nop_alloc_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLuint width, GLuint height) static
Dummy function for gl_renderbuffer::AllocStorage()
References _mesa_problem(), and void.
Referenced by intel_renderbuffer_update_wrapper().
intel_quantize_num_samples()
unsigned intel_quantize_num_samples (struct intel_screen * intel, unsigned num_samples)
Round up the requested multisample count to the next supported sample size.
References intel_supported_msaa_modes().
Referenced by intel_alloc_private_renderbuffer_storage(), intel_alloc_texture_image_buffer(), intel_alloc_texture_storage(), intel_renderbuffer_get_tile_offsets(), intel_update_framebuffer(), intelCreateBuffer(), and intelInitScreen2().
intel_render_texture()
static void intel_render_texture (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att) static
Called by glFramebufferTexture[123]DEXT() (and other places) to prepare for rendering into texture memory.
This might be called many times to choose different texture levels, cube faces, etc before intel_finish_render_texture() is ever called.
References _mesa_get_format_name(), _swrast_render_texture(), brw_context(), gl_renderbuffer_attachment::CubeMapFace, DBG, gl_texture_image::Depth, gl_texture_image::Height, intel_renderbuffer(), intel_renderbuffer_update_wrapper(), intel_texture_image(), gl_renderbuffer_attachment::Layered, intel_texture_image::mt, gl_texture_object::Name, gl_renderbuffer::RefCount, gl_renderbuffer_attachment::Renderbuffer, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, void, gl_texture_image::Width, and gl_renderbuffer_attachment::Zoffset.
Referenced by intel_fbo_init().
intel_renderbuffer_att_set_needs_depth_resolve()
void intel_renderbuffer_att_set_needs_depth_resolve (struct gl_renderbuffer_attachment * att)
References intel_miptree_set_all_slices_need_depth_resolve(), intel_miptree_slice_set_needs_depth_resolve(), intel_renderbuffer(), gl_renderbuffer_attachment::Layered, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by brw_fast_clear_depth(), brw_postdraw_set_buffers_need_resolve(), and intel_renderbuffer_get_tile_offsets().
intel_renderbuffer_downsample()
void intel_renderbuffer_downsample (struct brw_context * brw, struct intel_renderbuffer * irb)
Downsample a winsys renderbuffer from mt to singlesample_mt.
If the miptree needs no downsample, then skip.
References intel_miptree_updownsample(), intel_renderbuffer::mt, intel_renderbuffer::need_downsample, and intel_renderbuffer::singlesample_mt.
Referenced by intel_map_renderbuffer(), intel_renderbuffer_get_tile_offsets(), and intel_resolve_for_dri2_flush().
intel_renderbuffer_format()
static mesa_format intel_renderbuffer_format (struct gl_context * ctx, GLenum internalFormat) static
References brw_context(), dd_function_table::ChooseTextureFormat, gl_context::Driver, brw_context::has_separate_stencil, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z24_UNORM_S8_UINT, and brw_context::must_use_separate_stencil.
Referenced by intel_alloc_renderbuffer_storage().
intel_renderbuffer_has_hiz()
bool intel_renderbuffer_has_hiz (struct intel_renderbuffer * irb)
Does the renderbuffer have hiz enabled?
References intel_miptree_level_has_hiz(), intel_renderbuffer::mt, and intel_renderbuffer::mt_level.
Referenced by brw_emit_depthbuffer(), brw_fast_clear_depth(), brw_workaround_depthstencil_alignment(), intel_renderbuffer_get_tile_offsets(), intel_validate_framebuffer(), and pma_fix_enable().
intel_renderbuffer_move_to_temp()
void intel_renderbuffer_move_to_temp (struct brw_context * brw, struct intel_renderbuffer * irb, bool invalidate)
References swrast_renderbuffer::Base, swrast_texture_image::Base, intel_texture_image::base, intel_renderbuffer::Base, intel_get_image_dims(), intel_miptree_alloc_hiz(), intel_miptree_copy_teximage(), intel_miptree_create(), intel_miptree_reference(), intel_miptree_release(), intel_miptree_wants_hiz_buffer(), intel_renderbuffer_set_draw_offset(), intel_texture_image(), gl_texture_image::Level, intel_renderbuffer::mt, intel_texture_image::mt, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, and gl_texture_image::TexObject.
Referenced by brw_workaround_depthstencil_alignment(), gen4_update_renderbuffer_surface(), and intel_renderbuffer_get_tile_offsets().
intel_renderbuffer_resolve_depth()
bool intel_renderbuffer_resolve_depth (struct brw_context * brw, struct intel_renderbuffer * irb)
Perform a depth resolve on the renderbuffer.
It is safe to call this function on a renderbuffer without HiZ. In that case, the function is a no-op.
Returns
false if no resolve was needed
References intel_miptree_slice_resolve_depth(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by intel_renderbuffer_get_tile_offsets().
intel_renderbuffer_resolve_hiz()
bool intel_renderbuffer_resolve_hiz (struct brw_context * brw, struct intel_renderbuffer * irb)
Perform a HiZ resolve on the renderbuffer.
It is safe to call this function on a renderbuffer without HiZ. In that case, the function is a no-op.
Returns
false if no resolve was needed
References intel_miptree_slice_resolve_hiz(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by intel_renderbuffer_get_tile_offsets(), and intel_update_state().
intel_renderbuffer_set_draw_offset()
void intel_renderbuffer_set_draw_offset (struct intel_renderbuffer * irb)
References intel_renderbuffer::draw_x, intel_renderbuffer::draw_y, intel_miptree_get_image_offset(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, and intel_renderbuffer::mt_level.
Referenced by brw_workaround_depthstencil_alignment(), intel_rb_format(), intel_renderbuffer_move_to_temp(), and intel_renderbuffer_update_wrapper().
intel_renderbuffer_update_wrapper()
static bool intel_renderbuffer_update_wrapper (struct brw_context * brw, struct intel_renderbuffer * irb, struct gl_texture_image * image, uint32_t layer, bool layered) static
References gl_renderbuffer::AllocStorage, swrast_renderbuffer::Base, intel_renderbuffer::Base, intel_miptree_alloc_hiz(), intel_miptree_reference(), intel_miptree_wants_hiz_buffer(), intel_nop_alloc_storage(), intel_renderbuffer_set_draw_offset(), intel_texture_image(), intel_renderbuffer::layer_count, gl_texture_image::Level, gl_texture_object::MinLayer, gl_texture_object::MinLevel, intel_renderbuffer::mt, intel_texture_image::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_texture_object::NumLayers, and gl_texture_image::TexObject.
Referenced by intel_render_texture().
intel_renderbuffer_upsample()
void intel_renderbuffer_upsample (struct brw_context * brw, struct intel_renderbuffer * irb)
Upsample a winsys renderbuffer from singlesample_mt to mt.
The upsample is done unconditionally.
References intel_miptree_updownsample(), intel_renderbuffer::mt, intel_renderbuffer::need_downsample, and intel_renderbuffer::singlesample_mt.
Referenced by intel_process_dri2_buffer(), intel_renderbuffer_get_tile_offsets(), intel_unmap_renderbuffer(), and intel_update_image_buffer().
intel_unmap_renderbuffer()
static void intel_unmap_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb) static
See also
dd_function_table::UnmapRenderbuffer
References _mesa_get_format_name(), brw_context(), swrast_renderbuffer::Buffer, DBG, gl_renderbuffer::Format, intel_miptree_release(), intel_miptree_unmap(), intel_renderbuffer(), intel_renderbuffer_upsample(), intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_renderbuffer::Name, intel_renderbuffer::need_map_upsample, gl_renderbuffer::NumSamples, intel_renderbuffer::singlesample_mt, and intel_renderbuffer::singlesample_mt_is_tmp.
Referenced by intel_fbo_init().
intel_validate_framebuffer()
static void intel_validate_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb) static
Do additional "completeness" testing of a framebuffer object.
References _mesa_get_format_name(), gl_framebuffer::Attachment, gl_texture_image::Border, brw_context(), brw_render_target_supported(), BUFFER_DEPTH, BUFFER_STENCIL, DBG, gl_context::DrawBuffer, fbo_incomplete, brw_context::gen, brw_context::has_separate_stencil, intel_get_renderbuffer(), intel_rb_format(), intel_renderbuffer(), intel_renderbuffer_has_hiz(), MESA_FORMAT_S_UINT8, intel_renderbuffer::mt, intel_renderbuffer::mt_layer, intel_renderbuffer::mt_level, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer::TexImage, and gl_renderbuffer_attachment::Type.
Referenced by intel_fbo_init().