Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_tiled_memcpy.h File Reference
#include <stdint.h>
#include "main/mtypes.h"
Typedefs
typedef void *(* mem_copy_fn) (void *dest, const void *src, size_t n)
Functions
void linear_to_tiled (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char *dst, const char *src, uint32_t dst_pitch, int32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from linear to tiled texture.
void tiled_to_linear (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char *dst, const char *src, int32_t dst_pitch, uint32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from tiled to linear texture.
bool intel_get_memcpy (mesa_format tiledFormat, GLenum format, GLenum type, mem_copy_fn *mem_copy, uint32_t *cpp)
Determine which copy function to use for the given format combination.
Typedef Documentation
mem_copy_fn
typedef void*(* mem_copy_fn) (void *dest, const void *src, size_t n)
Function Documentation
intel_get_memcpy()
bool intel_get_memcpy (mesa_format tiledFormat, GLenum format, GLenum type, mem_copy_fn * mem_copy, uint32_t * cpp)
Determine which copy function to use for the given format combination.
The only two possible copy functions which are ever returned are a direct memcpy and a RGBA <-> BGRA copy function. Since RGBA -> BGRA and BGRA -> RGBA are exactly the same operation (and memcpy is obviously symmetric), it doesn't matter whether the copy is from the tiled image to the untiled or vice versa. The copy function required is the same in either case so this function can be used.
Parameters
[in] tiledFormat The format of the tiled image
[in] format The GL format of the client data
[in] type The GL type of the client data
[out] mem_copy Will be set to one of either the standard library's memcpy or a different copy function that performs an RGBA to BGRA conversion
[out] cpp Number of bytes per channel
Returns
true if the format and type combination are valid
References MESA_FORMAT_A_UNORM8, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_L_UNORM8, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, and rgba8_copy().
Referenced by intel_gettexsubimage_tiled_memcpy(), intel_readpixels_tiled_memcpy(), and intel_texsubimage_tiled_memcpy().
linear_to_tiled()
void linear_to_tiled (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char * dst, const char * src, uint32_t dst_pitch, int32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from linear to tiled texture.
Divide the region given by X range [xt1, xt2) and Y range [yt1, yt2) into pieces that do not cross tile boundaries and copy each piece with a tile copy function (tile_copy_fn). The X range is in bytes, i.e. pixels * bytes-per-pixel. The Y range is in pixels (i.e. unitless). 'dst' is the start of the texture and 'src' is the corresponding address to copy from, though copying begins at (xt1, yt1).
References ALIGN_DOWN, ALIGN_UP, linear_to_xtiled_faster(), linear_to_ytiled_faster(), span, xtile_height, xtile_span, xtile_width, y1, ytile_height, ytile_span, and ytile_width.
Referenced by intel_texsubimage_tiled_memcpy().
tiled_to_linear()
void tiled_to_linear (uint32_t xt1, uint32_t xt2, uint32_t yt1, uint32_t yt2, char * dst, const char * src, int32_t dst_pitch, uint32_t src_pitch, bool has_swizzling, uint32_t tiling, mem_copy_fn mem_copy)
Copy from tiled to linear texture.
Divide the region given by X range [xt1, xt2) and Y range [yt1, yt2) into pieces that do not cross tile boundaries and copy each piece with a tile copy function (tile_copy_fn). The X range is in bytes, i.e. pixels * bytes-per-pixel. The Y range is in pixels (i.e. unitless). 'dst' is the start of the texture and 'src' is the corresponding address to copy from, though copying begins at (xt1, yt1).
References ALIGN_DOWN, ALIGN_UP, span, xtile_height, xtile_span, xtile_width, xtiled_to_linear_faster(), y1, ytile_height, ytile_span, ytile_width, and ytiled_to_linear_faster().
Referenced by intel_gettexsubimage_tiled_memcpy(), and intel_readpixels_tiled_memcpy().