Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
intel_blit.h File Reference
#include "brw_context.h"
Functions
bool intelEmitCopyBlit (struct brw_context *brw, GLuint cpp, int32_t src_pitch, drm_intel_bo *src_buffer, GLuint src_offset, uint32_t src_tiling, int32_t dst_pitch, drm_intel_bo *dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort srcx, GLshort srcy, GLshort dstx, GLshort dsty, GLshort w, GLshort h, GLenum logicop)
bool intel_miptree_blit_compatible_formats (mesa_format src, mesa_format dst)
bool intel_miptree_blit (struct brw_context *brw, struct intel_mipmap_tree *src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, bool src_flip, struct intel_mipmap_tree *dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, bool dst_flip, uint32_t width, uint32_t height, GLenum logicop)
Implements a rectangular block transfer (blit) of pixels between two miptrees.
bool intel_miptree_copy (struct brw_context *brw, struct intel_mipmap_tree *src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, struct intel_mipmap_tree *dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, uint32_t src_width, uint32_t src_height)
bool intelEmitImmediateColorExpandBlit (struct brw_context *brw, GLuint cpp, GLubyte *src_bits, GLuint src_size, GLuint fg_color, GLshort dst_pitch, drm_intel_bo *dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort x, GLshort y, GLshort w, GLshort h, GLenum logic_op)
void intel_emit_linear_blit (struct brw_context *brw, drm_intel_bo *dst_bo, unsigned int dst_offset, drm_intel_bo *src_bo, unsigned int src_offset, unsigned int size)
Function Documentation
intel_emit_linear_blit()
void intel_emit_linear_blit (struct brw_context * brw, drm_intel_bo * dst_bo, unsigned int dst_offset, drm_intel_bo * src_bo, unsigned int src_offset, unsigned int size)
References _mesa_problem(), brw_context::ctx, GLuint, and intelEmitCopyBlit().
Referenced by brw_buffer_subdata(), brw_copy_buffer_subdata(), brw_flush_mapped_buffer_range(), and brw_unmap_buffer().
intel_miptree_blit()
bool intel_miptree_blit (struct brw_context * brw, struct intel_mipmap_tree * src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, bool src_flip, struct intel_mipmap_tree * dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, bool dst_flip, uint32_t width, uint32_t height, GLenum logicop)
Implements a rectangular block transfer (blit) of pixels between two miptrees.
Our blitter can operate on 1, 2, or 4-byte-per-pixel data, with generous, but limited, pitches and sizes allowed.
The src/dst coordinates are relative to the given level/slice of the miptree.
If or is set, then the rectangle within that miptree will be inverted (including scanline order) when copying. This is common in GL when copying between window system and user-created renderbuffers/textures.
References _mesa_get_format_bits(), _mesa_get_format_name(), _mesa_get_srgb_format_linear(), emit_miptree_blit(), intel_miptree_blit_compatible_formats(), intel_miptree_get_image_offset(), intel_miptree_resolve_color(), intel_miptree_set_alpha_to_one(), and intel_miptree_slice_resolve_depth().
Referenced by do_blit_copypixels(), do_blit_drawpixels(), intel_blit_framebuffer_with_blitter(), intel_copy_texsubimage(), and intel_miptree_copy_slice().
intel_miptree_blit_compatible_formats()
bool intel_miptree_blit_compatible_formats (mesa_format src, mesa_format dst)
References _mesa_get_srgb_format_linear(), MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, and MESA_FORMAT_R8G8B8X8_UNORM.
Referenced by do_blit_drawpixels(), and intel_miptree_blit().
intel_miptree_copy()
bool intel_miptree_copy (struct brw_context * brw, struct intel_mipmap_tree * src_mt, int src_level, int src_slice, uint32_t src_x, uint32_t src_y, struct intel_mipmap_tree * dst_mt, int dst_level, int dst_slice, uint32_t dst_x, uint32_t dst_y, uint32_t src_width, uint32_t src_height)
References _mesa_get_format_block_size(), _mesa_is_format_compressed(), emit_miptree_blit(), GLuint, intel_miptree_get_image_offset(), intel_miptree_resolve_color(), intel_miptree_slice_resolve_depth(), and MESA_FORMAT_S_UINT8.
Referenced by copy_miptrees(), intel_miptree_map_blit(), and intel_miptree_unmap_blit().
intelEmitCopyBlit()
bool intelEmitCopyBlit (struct brw_context * brw, GLuint cpp, int32_t src_pitch, drm_intel_bo * src_buffer, GLuint src_offset, uint32_t src_tiling, int32_t dst_pitch, drm_intel_bo * dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort srcx, GLshort srcy, GLshort dstx, GLshort dsty, GLshort w, GLshort h, GLenum logicop)
References ADVANCE_BATCH_TILED, alignment_valid(), brw_context::batch, BEGIN_BATCH_BLT_TILED, BLT_RING, intel_batchbuffer::bo, br13_for_cpp(), brw_emit_mi_flush(), DBG, brw_context::gen, GLuint, intel_batchbuffer_flush, intel_batchbuffer_require_space(), intel_get_tile_dims(), OUT_BATCH, OUT_RELOC, OUT_RELOC64, SET_FIELD, translate_raster_op(), and xy_blit_cmd().
Referenced by emit_miptree_blit(), and intel_emit_linear_blit().
intelEmitImmediateColorExpandBlit()
bool intelEmitImmediateColorExpandBlit (struct brw_context * brw, GLuint cpp, GLubyte * src_bits, GLuint src_size, GLuint fg_color, GLshort dst_pitch, drm_intel_bo * dst_buffer, GLuint dst_offset, uint32_t dst_tiling, GLshort x, GLshort y, GLshort w, GLshort h, GLenum logic_op)
References ADVANCE_BATCH, BEGIN_BATCH_BLT, BLT_RING, br13_for_cpp(), brw_emit_mi_flush(), DBG, brw_context::gen, intel_batchbuffer_data(), intel_batchbuffer_require_space(), OUT_BATCH, OUT_RELOC, OUT_RELOC64, SET_FIELD, translate_raster_op(), XY_BLT_WRITE_ALPHA, XY_BLT_WRITE_RGB, XY_DST_TILED, XY_SETUP_BLT_CMD, XY_TEXT_BYTE_PACKED, and XY_TEXT_IMMEDIATE_BLIT_CMD.
Referenced by do_blit_bitmap().