Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
brw_tracked_state Struct Reference
#include <brw_context.h>
Data Fields
struct brw_state_flags dirty
void(* emit)(struct brw_context *brw)
Field Documentation
dirty
struct brw_state_flags brw_tracked_state::dirty
Referenced by brw_copy_pipeline_atoms(), brw_upload_pipeline_state(), and check_and_emit_atom().
emit
void(* brw_tracked_state::emit) (struct brw_context *brw)
Referenced by blorp_exec(), brw_copy_pipeline_atoms(), and check_and_emit_atom().
The documentation for this struct was generated from the following file:
brw_context.h