Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
m_clip_tmp.h File Reference
Functions
static GLvector4f *TAG() cliptest_points4 (GLvector4f *clip_vec, GLvector4f *proj_vec, GLubyte clipMask[], GLubyte *orMask, GLubyte *andMask, GLboolean viewport_z_clip)
static GLvector4f *TAG() cliptest_np_points4 (GLvector4f *clip_vec, GLvector4f *proj_vec, GLubyte clipMask[], GLubyte *orMask, GLubyte *andMask, GLboolean viewport_z_clip)
static GLvector4f *TAG() cliptest_points3 (GLvector4f *clip_vec, GLvector4f *proj_vec, GLubyte clipMask[], GLubyte *orMask, GLubyte *andMask, GLboolean viewport_z_clip)
static GLvector4f *TAG() cliptest_points2 (GLvector4f *clip_vec, GLvector4f *proj_vec, GLubyte clipMask[], GLubyte *orMask, GLubyte *andMask, GLboolean viewport_z_clip)
void TAG() init_c_cliptest (void)
Function Documentation
cliptest_np_points4()
static GLvector4f* TAG() cliptest_np_points4 (GLvector4f * clip_vec, GLvector4f * proj_vec, GLubyte clipMask[], GLubyte * orMask, GLubyte * andMask, GLboolean viewport_z_clip) static
References CLIP_BOTTOM_BIT, CLIP_BOTTOM_SHIFT, CLIP_FAR_BIT, CLIP_FAR_SHIFT, CLIP_LEFT_BIT, CLIP_LEFT_SHIFT, CLIP_NEAR_BIT, CLIP_NEAR_SHIFT, CLIP_RIGHT_BIT, CLIP_RIGHT_SHIFT, CLIP_TOP_BIT, CLIP_TOP_SHIFT, GLuint, and STRIDE_LOOP.
Referenced by init_c_cliptest().
cliptest_points2()
static GLvector4f* TAG() cliptest_points2 (GLvector4f * clip_vec, GLvector4f * proj_vec, GLubyte clipMask[], GLubyte * orMask, GLubyte * andMask, GLboolean viewport_z_clip) static
References CLIP_BOTTOM_BIT, CLIP_LEFT_BIT, CLIP_RIGHT_BIT, CLIP_TOP_BIT, F, GLuint, and STRIDE_LOOP.
Referenced by init_c_cliptest().
cliptest_points3()
static GLvector4f* TAG() cliptest_points3 (GLvector4f * clip_vec, GLvector4f * proj_vec, GLubyte clipMask[], GLubyte * orMask, GLubyte * andMask, GLboolean viewport_z_clip) static
References CLIP_BOTTOM_BIT, CLIP_FAR_BIT, CLIP_LEFT_BIT, CLIP_NEAR_BIT, CLIP_RIGHT_BIT, CLIP_TOP_BIT, F, GLuint, and STRIDE_LOOP.
Referenced by init_c_cliptest().
cliptest_points4()
static GLvector4f* TAG() cliptest_points4 (GLvector4f * clip_vec, GLvector4f * proj_vec, GLubyte clipMask[], GLubyte * orMask, GLubyte * andMask, GLboolean viewport_z_clip) static
References CLIP_BOTTOM_BIT, CLIP_BOTTOM_SHIFT, CLIP_FAR_BIT, CLIP_FAR_SHIFT, CLIP_LEFT_BIT, CLIP_LEFT_SHIFT, CLIP_NEAR_BIT, CLIP_NEAR_SHIFT, CLIP_RIGHT_BIT, CLIP_RIGHT_SHIFT, CLIP_TOP_BIT, CLIP_TOP_SHIFT, GLuint, STRIDE_LOOP, and VEC_SIZE_4.
Referenced by init_c_cliptest().
init_c_cliptest()
void TAG() init_c_cliptest (void)
References _mesa_clip_np_tab, _mesa_clip_tab, cliptest_np_points4(), cliptest_points2(), cliptest_points3(), cliptest_points4(), and TAG.
Referenced by _math_init_transformation().