Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
m_debug.h File Reference
Functions
void _math_test_all_transform_functions (char *description)
void _math_test_all_normal_transform_functions (char *description)
void _math_test_all_cliptest_functions (char *description)
void _math_test_all_vertex_functions (char *description)
Variables
char * mesa_profile
Function Documentation
_math_test_all_cliptest_functions()
void _math_test_all_cliptest_functions (char * description)
Referenced by _math_init_transformation().
_math_test_all_normal_transform_functions()
void _math_test_all_normal_transform_functions (char * description)
Referenced by _math_init_transformation().
_math_test_all_transform_functions()
void _math_test_all_transform_functions (char * description)
Referenced by _math_init_transformation().
_math_test_all_vertex_functions()
void _math_test_all_vertex_functions (char * description)
Variable Documentation
mesa_profile
char* mesa_profile