Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
m_dotprod_tmp.h File Reference
Functions
static void TAG() dotprod_vec2 (GLfloat *out, GLuint outstride, const GLvector4f *coord_vec, const GLfloat plane[4])
static void TAG() dotprod_vec3 (GLfloat *out, GLuint outstride, const GLvector4f *coord_vec, const GLfloat plane[4])
static void TAG() dotprod_vec4 (GLfloat *out, GLuint outstride, const GLvector4f *coord_vec, const GLfloat plane[4])
static void TAG() init_dotprod (void)
Function Documentation
dotprod_vec2()
static void TAG() dotprod_vec2 (GLfloat * out, GLuint outstride, const GLvector4f * coord_vec, const GLfloat plane[4]) static
References GLuint, and STRIDE_F.
Referenced by init_dotprod().
dotprod_vec3()
static void TAG() dotprod_vec3 (GLfloat * out, GLuint outstride, const GLvector4f * coord_vec, const GLfloat plane[4]) static
References GLuint, and STRIDE_F.
Referenced by init_dotprod().
dotprod_vec4()
static void TAG() dotprod_vec4 (GLfloat * out, GLuint outstride, const GLvector4f * coord_vec, const GLfloat plane[4]) static
References GLuint, and STRIDE_F.
Referenced by init_dotprod().
init_dotprod()
static void TAG() init_dotprod (void) static
References _mesa_dotprod_tab, dotprod_vec2(), dotprod_vec3(), dotprod_vec4(), and TAG.
Referenced by _math_init_transformation().