Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
m_norm_tmp.h File Reference
Functions
static void TAG() transform_normalize_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() transform_normalize_normals_no_rot (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() transform_rescale_normals_no_rot (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() transform_rescale_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() transform_normals_no_rot (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() transform_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() normalize_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() rescale_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void TAG() init_c_norm_transform (void)
Function Documentation
init_c_norm_transform()
static void TAG() init_c_norm_transform (void) static
References _mesa_normal_tab, NORM_NORMALIZE, NORM_RESCALE, NORM_TRANSFORM, NORM_TRANSFORM_NO_ROT, normalize_normals(), rescale_normals(), TAG, transform_normalize_normals(), transform_normalize_normals_no_rot(), transform_normals(), transform_normals_no_rot(), transform_rescale_normals(), and transform_rescale_normals_no_rot().
Referenced by _math_init_transformation().
normalize_normals()
static void TAG() normalize_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, STRIDE_LOOP, void, and x.
Referenced by init_c_norm_transform().
rescale_normals()
static void TAG() rescale_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, SCALE_SCALAR_3V, STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
transform_normalize_normals()
static void TAG() transform_normalize_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, if(), GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().
transform_normalize_normals_no_rot()
static void TAG() transform_normalize_normals_no_rot (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, if(), GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().
transform_normals()
static void TAG() transform_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, GLmatrix::inv, STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
transform_normals_no_rot()
static void TAG() transform_normals_no_rot (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, GLmatrix::inv, STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
transform_rescale_normals()
static void TAG() transform_rescale_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().
transform_rescale_normals_no_rot()
static void TAG() transform_rescale_normals_no_rot (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLuint, GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().