Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
m_vector.c File Reference
#include <stdio.h>
#include "main/glheader.h"
#include "main/imports.h"
#include "main/macros.h"
#include "m_vector.h"
Functions
void _mesa_vector4f_clean_elem (GLvector4f *vec, GLuint count, GLuint elt)
Given a vector [count][4] of floats, set all the [][elt] values to 0 (if elt = 0, 1, 2) or 1.0 (if elt = 3).
void _mesa_vector4f_init (GLvector4f *v, GLbitfield flags, GLfloat(*storage)[4])
Initialize GLvector objects.
void _mesa_vector4f_alloc (GLvector4f *v, GLbitfield flags, GLuint count, GLuint alignment)
Initialize GLvector objects and allocate storage.
void _mesa_vector4f_free (GLvector4f *v)
Vector deallocation.
void _mesa_vector4f_print (const GLvector4f *v, const GLubyte *cullmask, GLboolean culling)
For debugging.
Variables
static const GLubyte size_bits [5]
Function Documentation
_mesa_vector4f_alloc()
void _mesa_vector4f_alloc (GLvector4f * v, GLbitfield flags, GLuint count, GLuint alignment)
Initialize GLvector objects and allocate storage.
Parameters
v the vector object
flags bitwise-OR of VEC_* flags
count number of elements to allocate in vector
alignment desired memory alignment for the data (in bytes)
References _mesa_align_malloc(), GLvector4f::count, GLvector4f::data, GLvector4f::flags, GLvector4f::size, size_bits, GLvector4f::start, GLvector4f::storage, GLvector4f::storage_count, GLvector4f::stride, and VEC_MALLOC.
_mesa_vector4f_clean_elem()
void _mesa_vector4f_clean_elem (GLvector4f * vec, GLuint count, GLuint elt)
Given a vector [count][4] of floats, set all the [][elt] values to 0 (if elt = 0, 1, 2) or 1.0 (if elt = 3).
References GLvector4f::flags, for(), GLuint, GLvector4f::start, VEC_DIRTY_0, VEC_DIRTY_1, VEC_DIRTY_2, and VEC_DIRTY_3.
_mesa_vector4f_free()
void _mesa_vector4f_free (GLvector4f * v)
Vector deallocation.
Free whatever memory is pointed to by the vector's storage field if the VEC_MALLOC flag is set. DO NOT free the GLvector object itself, though.
References _mesa_align_free(), GLvector4f::data, GLvector4f::flags, GLvector4f::start, GLvector4f::storage, and VEC_MALLOC.
_mesa_vector4f_init()
void _mesa_vector4f_init (GLvector4f * v, GLbitfield flags, GLfloat(*) storage[4])
Initialize GLvector objects.
Parameters
v the vector object to initialize.
flags bitwise-OR of VEC_* flags
storage pointer to storage for the vector's data
References GLvector4f::count, GLvector4f::data, GLvector4f::flags, GLvector4f::size, size_bits, GLvector4f::start, and GLvector4f::stride.
_mesa_vector4f_print()
void _mesa_vector4f_print (const GLvector4f * v, const GLubyte * cullmask, GLboolean culling)
For debugging.
References GLvector4f::count, GLvector4f::data, GLvector4f::flags, GLuint, GLvector4f::size, GLvector4f::start, GLvector4f::stride, and STRIDE_F.
Variable Documentation
size_bits
const GLubyte size_bits[5] static
Initial value:
= {
   0,
   VEC_SIZE_1,
   VEC_SIZE_2,
   VEC_SIZE_3,
   VEC_SIZE_4,
}
Referenced by _mesa_vector4f_alloc(), and _mesa_vector4f_init().