Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
m_xform_tmp.h File Reference
Macros
#define TAG_TAB _mesa_transform_tab
#define TAG_TAB_1 TAG(transform_tab_1)
#define TAG_TAB_2 TAG(transform_tab_2)
#define TAG_TAB_3 TAG(transform_tab_3)
#define TAG_TAB_4 TAG(transform_tab_4)
Functions
static void TAG() transform_points1_general (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points1_identity (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points1_2d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points1_2d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points1_3d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points1_3d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points1_perspective (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_general (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_identity (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_2d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_2d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_3d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_3d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points2_perspective (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_general (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_identity (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_2d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_2d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_3d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_3d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points3_perspective (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_general (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_identity (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_2d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_2d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_3d (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_3d_no_rot (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static void TAG() transform_points4_perspective (GLvector4f *to_vec, const GLfloat m[16], const GLvector4f *from_vec)
static transform_func TAG (transform_tab_1)[7]
static transform_func TAG (transform_tab_2)[7]
static transform_func TAG (transform_tab_3)[7]
static transform_func TAG (transform_tab_4)[7]
static void TAG() init_c_transformations (void)
Macro Definition Documentation
TAG_TAB
#define TAG_TAB _mesa_transform_tab
Referenced by init_c_transformations().
TAG_TAB_1
#define TAG_TAB_1 TAG(transform_tab_1)
Referenced by init_c_transformations().
TAG_TAB_2
#define TAG_TAB_2 TAG(transform_tab_2)
Referenced by init_c_transformations().
TAG_TAB_3
#define TAG_TAB_3 TAG(transform_tab_3)
Referenced by init_c_transformations().
TAG_TAB_4
#define TAG_TAB_4 TAG(transform_tab_4)
Referenced by init_c_transformations().
Function Documentation
init_c_transformations()
static void TAG() init_c_transformations (void) static
References MATRIX_2D, MATRIX_2D_NO_ROT, MATRIX_3D, MATRIX_3D_NO_ROT, MATRIX_GENERAL, MATRIX_IDENTITY, MATRIX_PERSPECTIVE, TAG(), TAG_TAB, TAG_TAB_1, TAG_TAB_2, TAG_TAB_3, TAG_TAB_4, transform_points1_2d(), transform_points1_2d_no_rot(), transform_points1_3d(), transform_points1_3d_no_rot(), transform_points1_general(), transform_points1_identity(), transform_points1_perspective(), transform_points2_2d(), transform_points2_2d_no_rot(), transform_points2_3d(), transform_points2_3d_no_rot(), transform_points2_general(), transform_points2_identity(), transform_points2_perspective(), transform_points3_2d(), transform_points3_2d_no_rot(), transform_points3_3d(), transform_points3_3d_no_rot(), transform_points3_general(), transform_points3_identity(), transform_points3_perspective(), transform_points4_2d(), transform_points4_2d_no_rot(), transform_points4_3d(), transform_points4_3d_no_rot(), transform_points4_general(), transform_points4_identity(), and transform_points4_perspective().
Referenced by _math_init_transformation().
TAG() [1/4]
static transform_func TAG (transform_tab_1) static
Referenced by init_c_transformations().
TAG() [2/4]
static transform_func TAG (transform_tab_2) static
TAG() [3/4]
static transform_func TAG (transform_tab_3) static
TAG() [4/4]
static transform_func TAG (transform_tab_4) static
transform_points1_2d()
static void TAG() transform_points1_2d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points1_2d_no_rot()
static void TAG() transform_points1_2d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points1_3d()
static void TAG() transform_points1_3d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points1_3d_no_rot()
static void TAG() transform_points1_3d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points1_general()
static void TAG() transform_points1_general (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points1_identity()
static void TAG() transform_points1_identity (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLvector4f::count, GLvector4f::flags, GLuint, GLvector4f::size, GLvector4f::start, STRIDE_LOOP, and VEC_SIZE_1.
Referenced by init_c_transformations().
transform_points1_perspective()
static void TAG() transform_points1_perspective (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points2_2d()
static void TAG() transform_points2_2d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points2_2d_no_rot()
static void TAG() transform_points2_2d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points2_3d()
static void TAG() transform_points2_3d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points2_3d_no_rot()
static void TAG() transform_points2_3d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points2_general()
static void TAG() transform_points2_general (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points2_identity()
static void TAG() transform_points2_identity (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLvector4f::count, GLvector4f::flags, GLuint, GLvector4f::size, GLvector4f::start, STRIDE_LOOP, and VEC_SIZE_2.
Referenced by init_c_transformations().
transform_points2_perspective()
static void TAG() transform_points2_perspective (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points3_2d()
static void TAG() transform_points3_2d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points3_2d_no_rot()
static void TAG() transform_points3_2d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points3_3d()
static void TAG() transform_points3_3d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points3_3d_no_rot()
static void TAG() transform_points3_3d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points3_general()
static void TAG() transform_points3_general (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points3_identity()
static void TAG() transform_points3_identity (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLvector4f::count, GLvector4f::flags, GLuint, GLvector4f::size, GLvector4f::start, STRIDE_LOOP, and VEC_SIZE_3.
Referenced by init_c_transformations().
transform_points3_perspective()
static void TAG() transform_points3_perspective (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points4_2d()
static void TAG() transform_points4_2d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points4_2d_no_rot()
static void TAG() transform_points4_2d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points4_3d()
static void TAG() transform_points4_3d (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points4_3d_no_rot()
static void TAG() transform_points4_3d_no_rot (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points4_general()
static void TAG() transform_points4_general (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().
transform_points4_identity()
static void TAG() transform_points4_identity (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLvector4f::count, GLvector4f::flags, GLuint, GLvector4f::size, GLvector4f::start, STRIDE_LOOP, and VEC_SIZE_4.
Referenced by init_c_transformations().
transform_points4_perspective()
static void TAG() transform_points4_perspective (GLvector4f * to_vec, const GLfloat m[16], const GLvector4f * from_vec) static
References GLuint, GLvector4f::start, and STRIDE_LOOP.
Referenced by init_c_transformations().