Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
accum.c File Reference
#include "glheader.h"
#include "accum.h"
#include "condrender.h"
#include "context.h"
#include "format_unpack.h"
#include "format_pack.h"
#include "imports.h"
#include "macros.h"
#include "state.h"
#include "mtypes.h"
#include "main/dispatch.h"
Functions
void GLAPIENTRY _mesa_ClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
void GLAPIENTRY _mesa_Accum (GLenum op, GLfloat value)
void _mesa_clear_accum_buffer (struct gl_context *ctx)
Clear the accumulation buffer by mapping the renderbuffer and writing the clear color to it.
static void accum_scale_or_bias (struct gl_context *ctx, GLfloat value, GLint xpos, GLint ypos, GLint width, GLint height, GLboolean bias)
if (bias) Accum += value else Accum *= value
static void accum_or_load (struct gl_context *ctx, GLfloat value, GLint xpos, GLint ypos, GLint width, GLint height, GLboolean load)
if (load) Accum = ColorBuf * value else Accum += ColorBuf * value
static void accum_return (struct gl_context *ctx, GLfloat value, GLint xpos, GLint ypos, GLint width, GLint height)
ColorBuffer = Accum * value.
void _mesa_accum (struct gl_context *ctx, GLenum op, GLfloat value)
Software fallback for glAccum.
void _mesa_init_accum (struct gl_context *ctx)
Function Documentation
_mesa_Accum()
void GLAPIENTRY _mesa_Accum (GLenum op, GLfloat value)
References _mesa_accum(), _mesa_error(), _mesa_update_state(), FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
_mesa_accum()
void _mesa_accum (struct gl_context * ctx, GLenum op, GLfloat value)
Software fallback for glAccum.
A hardware driver that supports signed 16-bit color channels could implement hardware accumulation operations, but no driver does so at this time.
References _mesa_check_conditional_render(), _mesa_problem(), _mesa_warning(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, accum_or_load(), accum_return(), accum_scale_or_bias(), gl_framebuffer::Attachment, BUFFER_ACCUM, gl_context::DrawBuffer, F, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_Accum().
_mesa_clear_accum_buffer()
void _mesa_clear_accum_buffer (struct gl_context * ctx)
Clear the accumulation buffer by mapping the renderbuffer and writing the clear color to it.
Called by the driver's implementation of the glClear function.
References _mesa_error(), _mesa_warning(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_context::Accum, gl_framebuffer::Attachment, BUFFER_ACCUM, gl_accum_attrib::ClearColor, gl_context::DrawBuffer, gl_context::Driver, FLOAT_TO_SHORT, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_RGBA_SNORM16, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::UnmapRenderbuffer, and x.
_mesa_ClearAccum()
void GLAPIENTRY _mesa_ClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
References F, GET_CURRENT_CONTEXT, GLAPIENTRY, and TEST_EQ_4V.
Referenced by _mesa_PopAttrib().
_mesa_init_accum()
void _mesa_init_accum (struct gl_context * ctx)
References gl_context::Accum, and gl_accum_attrib::ClearColor.
Referenced by init_attrib_groups().
accum_or_load()
static void accum_or_load (struct gl_context * ctx, GLfloat value, GLint xpos, GLint ypos, GLint width, GLint height, GLboolean load) static
if (load) Accum = ColorBuf * value else Accum += ColorBuf * value
References gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_unpack_rgba_row(), ACOMP, gl_framebuffer::Attachment, BCOMP, BUFFER_ACCUM, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, GCOMP, dd_function_table::MapRenderbuffer, MESA_FORMAT_RGBA_SNORM16, RCOMP, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_accum().
accum_return()
static void accum_return (struct gl_context * ctx, GLfloat value, GLint xpos, GLint ypos, GLint width, GLint height) static
ColorBuffer = Accum * value.
References gl_framebuffer::_ColorDrawBuffers, _mesa_error(), _mesa_pack_float_rgba_row(), _mesa_unpack_rgba_row(), gl_framebuffer::_NumColorDrawBuffers, ACOMP, gl_framebuffer::Attachment, BCOMP, BUFFER_ACCUM, gl_context::Color, gl_colorbuffer_attrib::ColorMask, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, GCOMP, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_RGBA_SNORM16, RCOMP, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_accum().
accum_scale_or_bias()
static void accum_scale_or_bias (struct gl_context * ctx, GLfloat value, GLint xpos, GLint ypos, GLint width, GLint height, GLboolean bias) static
if (bias) Accum += value else Accum *= value
References _mesa_error(), gl_framebuffer::Attachment, BUFFER_ACCUM, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, dd_function_table::MapRenderbuffer, MESA_FORMAT_RGBA_SNORM16, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_accum().