Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
api_exec.h File Reference
Functions
struct _glapi_table * _mesa_alloc_dispatch_table (void)
Allocate and initialize a new dispatch table.
void _mesa_initialize_exec_table (struct gl_context *ctx)
void _mesa_initialize_dispatch_tables (struct gl_context *ctx)
struct _glapi_table * _mesa_new_nop_table (unsigned numEntries)
Create a new API dispatch table in which all entries point to the generic_nop() function.
Function Documentation
_mesa_alloc_dispatch_table()
struct _glapi_table* _mesa_alloc_dispatch_table (void)
Allocate and initialize a new dispatch table.
The table will be populated with pointers to "no-op" functions. In turn, the no-op functions will call nop_handler() above.
References _glapi_get_dispatch_table_size(), _glapi_set_nop_handler(), and _mesa_new_nop_table().
Referenced by _mesa_initialize_context(), and create_beginend_table().
_mesa_initialize_dispatch_tables()
void _mesa_initialize_dispatch_tables (struct gl_context * ctx)
References _mesa_initialize_exec_table(), _mesa_initialize_save_table(), and gl_context::Save.
_mesa_initialize_exec_table()
void _mesa_initialize_exec_table (struct gl_context * ctx)
Referenced by _mesa_initialize_dispatch_tables().
_mesa_new_nop_table()
struct _glapi_table* _mesa_new_nop_table (unsigned numEntries)
Create a new API dispatch table in which all entries point to the generic_nop() function.
This will not work on Windows because of the __stdcall convention which requires the callee to clean up the call stack. That's impossible with one generic no-op function.
References _glapi_new_nop_table(), and generic_nop().
Referenced by _mesa_alloc_dispatch_table().