Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
api_loopback.h File Reference
#include "main/glheader.h"
Functions
void _mesa_loopback_init_api_table (const struct gl_context *ctx, struct _glapi_table *dest)
void GLAPIENTRY _mesa_Color3b (GLbyte red, GLbyte green, GLbyte blue)
void GLAPIENTRY _mesa_Color3d (GLdouble red, GLdouble green, GLdouble blue)
void GLAPIENTRY _mesa_Color3i (GLint red, GLint green, GLint blue)
void GLAPIENTRY _mesa_Color3s (GLshort red, GLshort green, GLshort blue)
void GLAPIENTRY _mesa_Color3ui (GLuint red, GLuint green, GLuint blue)
void GLAPIENTRY _mesa_Color3us (GLushort red, GLushort green, GLushort blue)
void GLAPIENTRY _mesa_Color3ub (GLubyte red, GLubyte green, GLubyte blue)
void GLAPIENTRY _mesa_Color3bv (const GLbyte *v)
void GLAPIENTRY _mesa_Color3dv (const GLdouble *v)
void GLAPIENTRY _mesa_Color3iv (const GLint *v)
void GLAPIENTRY _mesa_Color3sv (const GLshort *v)
void GLAPIENTRY _mesa_Color3uiv (const GLuint *v)
void GLAPIENTRY _mesa_Color3usv (const GLushort *v)
void GLAPIENTRY _mesa_Color3ubv (const GLubyte *v)
void GLAPIENTRY _mesa_Color4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
void GLAPIENTRY _mesa_Color4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
void GLAPIENTRY _mesa_Color4i (GLint red, GLint green, GLint blue, GLint alpha)
void GLAPIENTRY _mesa_Color4s (GLshort red, GLshort green, GLshort blue, GLshort alpha)
void GLAPIENTRY _mesa_Color4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
void GLAPIENTRY _mesa_Color4us (GLushort red, GLushort green, GLushort blue, GLushort alpha)
void GLAPIENTRY _mesa_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
void GLAPIENTRY _mesa_Color4iv (const GLint *v)
void GLAPIENTRY _mesa_Color4bv (const GLbyte *v)
void GLAPIENTRY _mesa_Color4dv (const GLdouble *v)
void GLAPIENTRY _mesa_Color4sv (const GLshort *v)
void GLAPIENTRY _mesa_Color4uiv (const GLuint *v)
void GLAPIENTRY _mesa_Color4usv (const GLushort *v)
void GLAPIENTRY _mesa_Color4ubv (const GLubyte *v)
void GLAPIENTRY _mesa_FogCoordd (GLdouble d)
void GLAPIENTRY _mesa_FogCoorddv (const GLdouble *v)
void GLAPIENTRY _mesa_Indexd (GLdouble c)
void GLAPIENTRY _mesa_Indexi (GLint c)
void GLAPIENTRY _mesa_Indexs (GLshort c)
void GLAPIENTRY _mesa_Indexub (GLubyte c)
void GLAPIENTRY _mesa_Indexdv (const GLdouble *c)
void GLAPIENTRY _mesa_Indexiv (const GLint *c)
void GLAPIENTRY _mesa_Indexsv (const GLshort *c)
void GLAPIENTRY _mesa_Indexubv (const GLubyte *c)
void GLAPIENTRY _mesa_EdgeFlagv (const GLboolean *flag)
void GLAPIENTRY _mesa_Normal3b (GLbyte nx, GLbyte ny, GLbyte nz)
void GLAPIENTRY _mesa_Normal3d (GLdouble nx, GLdouble ny, GLdouble nz)
void GLAPIENTRY _mesa_Normal3i (GLint nx, GLint ny, GLint nz)
void GLAPIENTRY _mesa_Normal3s (GLshort nx, GLshort ny, GLshort nz)
void GLAPIENTRY _mesa_Normal3bv (const GLbyte *v)
void GLAPIENTRY _mesa_Normal3dv (const GLdouble *v)
void GLAPIENTRY _mesa_Normal3iv (const GLint *v)
void GLAPIENTRY _mesa_Normal3sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord1d (GLdouble s)
void GLAPIENTRY _mesa_TexCoord1i (GLint s)
void GLAPIENTRY _mesa_TexCoord1s (GLshort s)
void GLAPIENTRY _mesa_TexCoord2d (GLdouble s, GLdouble t)
void GLAPIENTRY _mesa_TexCoord2s (GLshort s, GLshort t)
void GLAPIENTRY _mesa_TexCoord2i (GLint s, GLint t)
void GLAPIENTRY _mesa_TexCoord3d (GLdouble s, GLdouble t, GLdouble r)
void GLAPIENTRY _mesa_TexCoord3i (GLint s, GLint t, GLint r)
void GLAPIENTRY _mesa_TexCoord3s (GLshort s, GLshort t, GLshort r)
void GLAPIENTRY _mesa_TexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q)
void GLAPIENTRY _mesa_TexCoord4i (GLint s, GLint t, GLint r, GLint q)
void GLAPIENTRY _mesa_TexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q)
void GLAPIENTRY _mesa_TexCoord1dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord1iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord1sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord2dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord2iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord2sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord3dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord3iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord3sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord4dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord4iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord4sv (const GLshort *v)
void GLAPIENTRY _mesa_Vertex2d (GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_Vertex2i (GLint x, GLint y)
void GLAPIENTRY _mesa_Vertex2s (GLshort x, GLshort y)
void GLAPIENTRY _mesa_Vertex3d (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_Vertex3i (GLint x, GLint y, GLint z)
void GLAPIENTRY _mesa_Vertex3s (GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_Vertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_Vertex4i (GLint x, GLint y, GLint z, GLint w)
void GLAPIENTRY _mesa_Vertex4s (GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_Vertex2dv (const GLdouble *v)
void GLAPIENTRY _mesa_Vertex2iv (const GLint *v)
void GLAPIENTRY _mesa_Vertex2sv (const GLshort *v)
void GLAPIENTRY _mesa_Vertex3dv (const GLdouble *v)
void GLAPIENTRY _mesa_Vertex3iv (const GLint *v)
void GLAPIENTRY _mesa_Vertex3sv (const GLshort *v)
void GLAPIENTRY _mesa_Vertex4dv (const GLdouble *v)
void GLAPIENTRY _mesa_Vertex4iv (const GLint *v)
void GLAPIENTRY _mesa_Vertex4sv (const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord1d (GLenum target, GLdouble s)
void GLAPIENTRY _mesa_MultiTexCoord1dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord1i (GLenum target, GLint s)
void GLAPIENTRY _mesa_MultiTexCoord1iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord1s (GLenum target, GLshort s)
void GLAPIENTRY _mesa_MultiTexCoord1sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord2d (GLenum target, GLdouble s, GLdouble t)
void GLAPIENTRY _mesa_MultiTexCoord2dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord2i (GLenum target, GLint s, GLint t)
void GLAPIENTRY _mesa_MultiTexCoord2iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord2s (GLenum target, GLshort s, GLshort t)
void GLAPIENTRY _mesa_MultiTexCoord2sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord3d (GLenum target, GLdouble s, GLdouble t, GLdouble r)
void GLAPIENTRY _mesa_MultiTexCoord3dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord3i (GLenum target, GLint s, GLint t, GLint r)
void GLAPIENTRY _mesa_MultiTexCoord3iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord3s (GLenum target, GLshort s, GLshort t, GLshort r)
void GLAPIENTRY _mesa_MultiTexCoord3sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord4d (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
void GLAPIENTRY _mesa_MultiTexCoord4dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord4i (GLenum target, GLint s, GLint t, GLint r, GLint q)
void GLAPIENTRY _mesa_MultiTexCoord4iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord4s (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
void GLAPIENTRY _mesa_MultiTexCoord4sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_EvalCoord2dv (const GLdouble *u)
void GLAPIENTRY _mesa_EvalCoord2fv (const GLfloat *u)
void GLAPIENTRY _mesa_EvalCoord2d (GLdouble u, GLdouble v)
void GLAPIENTRY _mesa_EvalCoord1dv (const GLdouble *u)
void GLAPIENTRY _mesa_EvalCoord1fv (const GLfloat *u)
void GLAPIENTRY _mesa_EvalCoord1d (GLdouble u)
void GLAPIENTRY _mesa_Materialf (GLenum face, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_Materiali (GLenum face, GLenum pname, GLint param)
void GLAPIENTRY _mesa_Materialiv (GLenum face, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_Rectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
void GLAPIENTRY _mesa_Rectdv (const GLdouble *v1, const GLdouble *v2)
void GLAPIENTRY _mesa_Rectfv (const GLfloat *v1, const GLfloat *v2)
void GLAPIENTRY _mesa_Recti (GLint x1, GLint y1, GLint x2, GLint y2)
void GLAPIENTRY _mesa_Rectiv (const GLint *v1, const GLint *v2)
void GLAPIENTRY _mesa_Rects (GLshort x1, GLshort y1, GLshort x2, GLshort y2)
void GLAPIENTRY _mesa_Rectsv (const GLshort *v1, const GLshort *v2)
void GLAPIENTRY _mesa_SecondaryColor3b (GLbyte red, GLbyte green, GLbyte blue)
void GLAPIENTRY _mesa_SecondaryColor3d (GLdouble red, GLdouble green, GLdouble blue)
void GLAPIENTRY _mesa_SecondaryColor3i (GLint red, GLint green, GLint blue)
void GLAPIENTRY _mesa_SecondaryColor3s (GLshort red, GLshort green, GLshort blue)
void GLAPIENTRY _mesa_SecondaryColor3ui (GLuint red, GLuint green, GLuint blue)
void GLAPIENTRY _mesa_SecondaryColor3us (GLushort red, GLushort green, GLushort blue)
void GLAPIENTRY _mesa_SecondaryColor3ub (GLubyte red, GLubyte green, GLubyte blue)
void GLAPIENTRY _mesa_SecondaryColor3bv (const GLbyte *v)
void GLAPIENTRY _mesa_SecondaryColor3dv (const GLdouble *v)
void GLAPIENTRY _mesa_SecondaryColor3iv (const GLint *v)
void GLAPIENTRY _mesa_SecondaryColor3sv (const GLshort *v)
void GLAPIENTRY _mesa_SecondaryColor3uiv (const GLuint *v)
void GLAPIENTRY _mesa_SecondaryColor3usv (const GLushort *v)
void GLAPIENTRY _mesa_SecondaryColor3ubv (const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib1sNV (GLuint index, GLshort x)
void GLAPIENTRY _mesa_VertexAttrib1dNV (GLuint index, GLdouble x)
void GLAPIENTRY _mesa_VertexAttrib2sNV (GLuint index, GLshort x, GLshort y)
void GLAPIENTRY _mesa_VertexAttrib2dNV (GLuint index, GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_VertexAttrib3sNV (GLuint index, GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_VertexAttrib3dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_VertexAttrib4sNV (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_VertexAttrib4dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_VertexAttrib4ubNV (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
void GLAPIENTRY _mesa_VertexAttrib1svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib1dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib2svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib2dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib3svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib3dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib4dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4ubvNV (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttribs1svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs1fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs1dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs2svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs2fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs2dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs3svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs3fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs3dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs4svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs4fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs4dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs4ubvNV (GLuint index, GLsizei n, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib1s (GLuint index, GLshort x)
void GLAPIENTRY _mesa_VertexAttrib1d (GLuint index, GLdouble x)
void GLAPIENTRY _mesa_VertexAttrib2s (GLuint index, GLshort x, GLshort y)
void GLAPIENTRY _mesa_VertexAttrib2d (GLuint index, GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_VertexAttrib3s (GLuint index, GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_VertexAttrib3d (GLuint index, GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_VertexAttrib4s (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_VertexAttrib4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_VertexAttrib1sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib1dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib2sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib2dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib3sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib3dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib4dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4bv (GLuint index, const GLbyte *v)
void GLAPIENTRY _mesa_VertexAttrib4iv (GLuint index, const GLint *v)
void GLAPIENTRY _mesa_VertexAttrib4ubv (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib4usv (GLuint index, const GLushort *v)
void GLAPIENTRY _mesa_VertexAttrib4uiv (GLuint index, const GLuint *v)
void GLAPIENTRY _mesa_VertexAttrib4Nbv (GLuint index, const GLbyte *v)
void GLAPIENTRY _mesa_VertexAttrib4Nsv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib4Niv (GLuint index, const GLint *v)
void GLAPIENTRY _mesa_VertexAttrib4Nub (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
void GLAPIENTRY _mesa_VertexAttrib4Nubv (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib4Nusv (GLuint index, const GLushort *v)
void GLAPIENTRY _mesa_VertexAttrib4Nuiv (GLuint index, const GLuint *v)
void GLAPIENTRY _mesa_VertexAttribI1iv (GLuint index, const GLint *v)
GL_EXT_gpu_shader / GL 3.0 signed/unsigned integer-valued attributes.
void GLAPIENTRY _mesa_VertexAttribI1uiv (GLuint index, const GLuint *v)
void GLAPIENTRY _mesa_VertexAttribI4bv (GLuint index, const GLbyte *v)
void GLAPIENTRY _mesa_VertexAttribI4sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribI4ubv (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttribI4usv (GLuint index, const GLushort *v)
void GLAPIENTRY _mesa_VertexAttribL1d (GLuint index, GLdouble x)
void GLAPIENTRY _mesa_VertexAttribL2d (GLuint index, GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_VertexAttribL3d (GLuint index, GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_VertexAttribL4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_VertexAttribL1dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribL2dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribL3dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribL4dv (GLuint index, const GLdouble *v)
Function Documentation
_mesa_Color3b()
void GLAPIENTRY _mesa_Color3b (GLbyte red, GLbyte green, GLbyte blue)
References BYTE_TO_FLOAT, COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3bv()
void GLAPIENTRY _mesa_Color3bv (const GLbyte * v)
References BYTE_TO_FLOAT, COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3d()
void GLAPIENTRY _mesa_Color3d (GLdouble red, GLdouble green, GLdouble blue)
References COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3dv()
void GLAPIENTRY _mesa_Color3dv (const GLdouble * v)
References COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3i()
void GLAPIENTRY _mesa_Color3i (GLint red, GLint green, GLint blue)
References COLORF, GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3iv()
void GLAPIENTRY _mesa_Color3iv (const GLint * v)
References COLORF, GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3s()
void GLAPIENTRY _mesa_Color3s (GLshort red, GLshort green, GLshort blue)
References COLORF, GLAPIENTRY, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3sv()
void GLAPIENTRY _mesa_Color3sv (const GLshort * v)
References COLORF, GLAPIENTRY, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3ub()
void GLAPIENTRY _mesa_Color3ub (GLubyte red, GLubyte green, GLubyte blue)
References COLORF, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3ubv()
void GLAPIENTRY _mesa_Color3ubv (const GLubyte * v)
References COLORF, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3ui()
void GLAPIENTRY _mesa_Color3ui (GLuint red, GLuint green, GLuint blue)
References COLORF, GLAPIENTRY, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3uiv()
void GLAPIENTRY _mesa_Color3uiv (const GLuint * v)
References COLORF, GLAPIENTRY, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3us()
void GLAPIENTRY _mesa_Color3us (GLushort red, GLushort green, GLushort blue)
References COLORF, GLAPIENTRY, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color3usv()
void GLAPIENTRY _mesa_Color3usv (const GLushort * v)
References COLORF, GLAPIENTRY, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4b()
void GLAPIENTRY _mesa_Color4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
References BYTE_TO_FLOAT, COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4bv()
void GLAPIENTRY _mesa_Color4bv (const GLbyte * v)
References BYTE_TO_FLOAT, COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4d()
void GLAPIENTRY _mesa_Color4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
References COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4dv()
void GLAPIENTRY _mesa_Color4dv (const GLdouble * v)
References COLORF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4i()
void GLAPIENTRY _mesa_Color4i (GLint red, GLint green, GLint blue, GLint alpha)
References COLORF, GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4iv()
void GLAPIENTRY _mesa_Color4iv (const GLint * v)
References COLORF, GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4s()
void GLAPIENTRY _mesa_Color4s (GLshort red, GLshort green, GLshort blue, GLshort alpha)
References COLORF, GLAPIENTRY, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4sv()
void GLAPIENTRY _mesa_Color4sv (const GLshort * v)
References COLORF, GLAPIENTRY, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4ub()
void GLAPIENTRY _mesa_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
References COLORF, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4ubv()
void GLAPIENTRY _mesa_Color4ubv (const GLubyte * v)
References COLORF, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4ui()
void GLAPIENTRY _mesa_Color4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
References COLORF, GLAPIENTRY, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4uiv()
void GLAPIENTRY _mesa_Color4uiv (const GLuint * v)
References COLORF, GLAPIENTRY, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4us()
void GLAPIENTRY _mesa_Color4us (GLushort red, GLushort green, GLushort blue, GLushort alpha)
References COLORF, GLAPIENTRY, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Color4usv()
void GLAPIENTRY _mesa_Color4usv (const GLushort * v)
References COLORF, GLAPIENTRY, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_EdgeFlagv()
void GLAPIENTRY _mesa_EdgeFlagv (const GLboolean * flag)
References GET_DISPATCH, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_EvalCoord1d()
void GLAPIENTRY _mesa_EvalCoord1d (GLdouble u)
References EVALCOORD1, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_EvalCoord1dv()
void GLAPIENTRY _mesa_EvalCoord1dv (const GLdouble * u)
References EVALCOORD1, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_EvalCoord1fv()
void GLAPIENTRY _mesa_EvalCoord1fv (const GLfloat * u)
References EVALCOORD1, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_EvalCoord2d()
void GLAPIENTRY _mesa_EvalCoord2d (GLdouble u, GLdouble v)
References EVALCOORD2, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_EvalCoord2dv()
void GLAPIENTRY _mesa_EvalCoord2dv (const GLdouble * u)
References EVALCOORD2, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_EvalCoord2fv()
void GLAPIENTRY _mesa_EvalCoord2fv (const GLfloat * u)
References EVALCOORD2, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_FogCoordd()
void GLAPIENTRY _mesa_FogCoordd (GLdouble d)
References FOGCOORDF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_FogCoorddv()
void GLAPIENTRY _mesa_FogCoorddv (const GLdouble * v)
References FOGCOORDF, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexd()
void GLAPIENTRY _mesa_Indexd (GLdouble c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexdv()
void GLAPIENTRY _mesa_Indexdv (const GLdouble * c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexi()
void GLAPIENTRY _mesa_Indexi (GLint c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexiv()
void GLAPIENTRY _mesa_Indexiv (const GLint * c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexs()
void GLAPIENTRY _mesa_Indexs (GLshort c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexsv()
void GLAPIENTRY _mesa_Indexsv (const GLshort * c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexub()
void GLAPIENTRY _mesa_Indexub (GLubyte c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_Indexubv()
void GLAPIENTRY _mesa_Indexubv (const GLubyte * c)
References GLAPIENTRY, and INDEX.
Referenced by _mesa_loopback_init_api_table().
_mesa_loopback_init_api_table()
void _mesa_loopback_init_api_table (const struct gl_context * ctx, struct _glapi_table * dest)
References _mesa_Color3b(), _mesa_Color3bv(), _mesa_Color3d(), _mesa_Color3dv(), _mesa_Color3i(), _mesa_Color3iv(), _mesa_Color3s(), _mesa_Color3sv(), _mesa_Color3ub(), _mesa_Color3ubv(), _mesa_Color3ui(), _mesa_Color3uiv(), _mesa_Color3us(), _mesa_Color3usv(), _mesa_Color4b(), _mesa_Color4bv(), _mesa_Color4d(), _mesa_Color4dv(), _mesa_Color4i(), _mesa_Color4iv(), _mesa_Color4s(), _mesa_Color4sv(), _mesa_Color4ub(), _mesa_Color4ubv(), _mesa_Color4ui(), _mesa_Color4uiv(), _mesa_Color4us(), _mesa_Color4usv(), _mesa_EdgeFlagv(), _mesa_EvalCoord1d(), _mesa_EvalCoord1dv(), _mesa_EvalCoord1fv(), _mesa_EvalCoord2d(), _mesa_EvalCoord2dv(), _mesa_EvalCoord2fv(), _mesa_FogCoordd(), _mesa_FogCoorddv(), _mesa_Indexd(), _mesa_Indexdv(), _mesa_Indexi(), _mesa_Indexiv(), _mesa_Indexs(), _mesa_Indexsv(), _mesa_Indexub(), _mesa_Indexubv(), _mesa_is_desktop_gl(), _mesa_Materialf(), _mesa_Materiali(), _mesa_Materialiv(), _mesa_MultiTexCoord1d(), _mesa_MultiTexCoord1dv(), _mesa_MultiTexCoord1i(), _mesa_MultiTexCoord1iv(), _mesa_MultiTexCoord1s(), _mesa_MultiTexCoord1sv(), _mesa_MultiTexCoord2d(), _mesa_MultiTexCoord2dv(), _mesa_MultiTexCoord2i(), _mesa_MultiTexCoord2iv(), _mesa_MultiTexCoord2s(), _mesa_MultiTexCoord2sv(), _mesa_MultiTexCoord3d(), _mesa_MultiTexCoord3dv(), _mesa_MultiTexCoord3i(), _mesa_MultiTexCoord3iv(), _mesa_MultiTexCoord3s(), _mesa_MultiTexCoord3sv(), _mesa_MultiTexCoord4d(), _mesa_MultiTexCoord4dv(), _mesa_MultiTexCoord4i(), _mesa_MultiTexCoord4iv(), _mesa_MultiTexCoord4s(), _mesa_MultiTexCoord4sv(), _mesa_Normal3b(), _mesa_Normal3bv(), _mesa_Normal3d(), _mesa_Normal3dv(), _mesa_Normal3i(), _mesa_Normal3iv(), _mesa_Normal3s(), _mesa_Normal3sv(), _mesa_Rectd(), _mesa_Rectdv(), _mesa_Rectfv(), _mesa_Recti(), _mesa_Rectiv(), _mesa_Rects(), _mesa_Rectsv(), _mesa_SecondaryColor3b(), _mesa_SecondaryColor3bv(), _mesa_SecondaryColor3d(), _mesa_SecondaryColor3dv(), _mesa_SecondaryColor3i(), _mesa_SecondaryColor3iv(), _mesa_SecondaryColor3s(), _mesa_SecondaryColor3sv(), _mesa_SecondaryColor3ub(), _mesa_SecondaryColor3ubv(), _mesa_SecondaryColor3ui(), _mesa_SecondaryColor3uiv(), _mesa_SecondaryColor3us(), _mesa_SecondaryColor3usv(), _mesa_TexCoord1d(), _mesa_TexCoord1dv(), _mesa_TexCoord1i(), _mesa_TexCoord1iv(), _mesa_TexCoord1s(), _mesa_TexCoord1sv(), _mesa_TexCoord2d(), _mesa_TexCoord2dv(), _mesa_TexCoord2i(), _mesa_TexCoord2iv(), _mesa_TexCoord2s(), _mesa_TexCoord2sv(), _mesa_TexCoord3d(), _mesa_TexCoord3dv(), _mesa_TexCoord3i(), _mesa_TexCoord3iv(), _mesa_TexCoord3s(), _mesa_TexCoord3sv(), _mesa_TexCoord4d(), _mesa_TexCoord4dv(), _mesa_TexCoord4i(), _mesa_TexCoord4iv(), _mesa_TexCoord4s(), _mesa_TexCoord4sv(), _mesa_Vertex2d(), _mesa_Vertex2dv(), _mesa_Vertex2i(), _mesa_Vertex2iv(), _mesa_Vertex2s(), _mesa_Vertex2sv(), _mesa_Vertex3d(), _mesa_Vertex3dv(), _mesa_Vertex3i(), _mesa_Vertex3iv(), _mesa_Vertex3s(), _mesa_Vertex3sv(), _mesa_Vertex4d(), _mesa_Vertex4dv(), _mesa_Vertex4i(), _mesa_Vertex4iv(), _mesa_Vertex4s(), _mesa_Vertex4sv(), _mesa_VertexAttrib1d(), _mesa_VertexAttrib1dNV(), _mesa_VertexAttrib1dv(), _mesa_VertexAttrib1dvNV(), _mesa_VertexAttrib1s(), _mesa_VertexAttrib1sNV(), _mesa_VertexAttrib1sv(), _mesa_VertexAttrib1svNV(), _mesa_VertexAttrib2d(), _mesa_VertexAttrib2dNV(), _mesa_VertexAttrib2dv(), _mesa_VertexAttrib2dvNV(), _mesa_VertexAttrib2s(), _mesa_VertexAttrib2sNV(), _mesa_VertexAttrib2sv(), _mesa_VertexAttrib2svNV(), _mesa_VertexAttrib3d(), _mesa_VertexAttrib3dNV(), _mesa_VertexAttrib3dv(), _mesa_VertexAttrib3dvNV(), _mesa_VertexAttrib3s(), _mesa_VertexAttrib3sNV(), _mesa_VertexAttrib3sv(), _mesa_VertexAttrib3svNV(), _mesa_VertexAttrib4bv(), _mesa_VertexAttrib4d(), _mesa_VertexAttrib4dNV(), _mesa_VertexAttrib4dv(), _mesa_VertexAttrib4dvNV(), _mesa_VertexAttrib4iv(), _mesa_VertexAttrib4Nbv(), _mesa_VertexAttrib4Niv(), _mesa_VertexAttrib4Nsv(), _mesa_VertexAttrib4Nub(), _mesa_VertexAttrib4Nubv(), _mesa_VertexAttrib4Nuiv(), _mesa_VertexAttrib4Nusv(), _mesa_VertexAttrib4s(), _mesa_VertexAttrib4sNV(), _mesa_VertexAttrib4sv(), _mesa_VertexAttrib4svNV(), _mesa_VertexAttrib4ubNV(), _mesa_VertexAttrib4ubv(), _mesa_VertexAttrib4ubvNV(), _mesa_VertexAttrib4uiv(), _mesa_VertexAttrib4usv(), _mesa_VertexAttribI1iv(), _mesa_VertexAttribI1uiv(), _mesa_VertexAttribI4bv(), _mesa_VertexAttribI4sv(), _mesa_VertexAttribI4ubv(), _mesa_VertexAttribI4usv(), _mesa_VertexAttribL1d(), _mesa_VertexAttribL1dv(), _mesa_VertexAttribL2d(), _mesa_VertexAttribL2dv(), _mesa_VertexAttribL3d(), _mesa_VertexAttribL3dv(), _mesa_VertexAttribL4d(), _mesa_VertexAttribL4dv(), _mesa_VertexAttribs1dvNV(), _mesa_VertexAttribs1fvNV(), _mesa_VertexAttribs1svNV(), _mesa_VertexAttribs2dvNV(), _mesa_VertexAttribs2fvNV(), _mesa_VertexAttribs2svNV(), _mesa_VertexAttribs3dvNV(), _mesa_VertexAttribs3fvNV(), _mesa_VertexAttribs3svNV(), _mesa_VertexAttribs4dvNV(), _mesa_VertexAttribs4fvNV(), _mesa_VertexAttribs4svNV(), _mesa_VertexAttribs4ubvNV(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, and API_OPENGLES2.
Referenced by _mesa_initialize_save_table(), and create_beginend_table().
_mesa_Materialf()
void GLAPIENTRY _mesa_Materialf (GLenum face, GLenum pname, GLfloat param)
References GLAPIENTRY, and MATERIALFV.
Referenced by _mesa_loopback_init_api_table().
_mesa_Materiali()
void GLAPIENTRY _mesa_Materiali (GLenum face, GLenum pname, GLint param)
References GLAPIENTRY, and MATERIALFV.
Referenced by _mesa_loopback_init_api_table().
_mesa_Materialiv()
void GLAPIENTRY _mesa_Materialiv (GLenum face, GLenum pname, const GLint * params)
References GLAPIENTRY, INT_TO_FLOAT, and MATERIALFV.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord1d()
void GLAPIENTRY _mesa_MultiTexCoord1d (GLenum target, GLdouble s)
References GLAPIENTRY, and MULTI_TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord1dv()
void GLAPIENTRY _mesa_MultiTexCoord1dv (GLenum target, const GLdouble * v)
References GLAPIENTRY, and MULTI_TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord1i()
void GLAPIENTRY _mesa_MultiTexCoord1i (GLenum target, GLint s)
References GLAPIENTRY, and MULTI_TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord1iv()
void GLAPIENTRY _mesa_MultiTexCoord1iv (GLenum target, const GLint * v)
References GLAPIENTRY, and MULTI_TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord1s()
void GLAPIENTRY _mesa_MultiTexCoord1s (GLenum target, GLshort s)
References GLAPIENTRY, and MULTI_TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord1sv()
void GLAPIENTRY _mesa_MultiTexCoord1sv (GLenum target, const GLshort * v)
References GLAPIENTRY, and MULTI_TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord2d()
void GLAPIENTRY _mesa_MultiTexCoord2d (GLenum target, GLdouble s, GLdouble t)
References GLAPIENTRY, and MULTI_TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord2dv()
void GLAPIENTRY _mesa_MultiTexCoord2dv (GLenum target, const GLdouble * v)
References GLAPIENTRY, and MULTI_TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord2i()
void GLAPIENTRY _mesa_MultiTexCoord2i (GLenum target, GLint s, GLint t)
References GLAPIENTRY, and MULTI_TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord2iv()
void GLAPIENTRY _mesa_MultiTexCoord2iv (GLenum target, const GLint * v)
References GLAPIENTRY, and MULTI_TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord2s()
void GLAPIENTRY _mesa_MultiTexCoord2s (GLenum target, GLshort s, GLshort t)
References GLAPIENTRY, and MULTI_TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord2sv()
void GLAPIENTRY _mesa_MultiTexCoord2sv (GLenum target, const GLshort * v)
References GLAPIENTRY, and MULTI_TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord3d()
void GLAPIENTRY _mesa_MultiTexCoord3d (GLenum target, GLdouble s, GLdouble t, GLdouble r)
References GLAPIENTRY, and MULTI_TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord3dv()
void GLAPIENTRY _mesa_MultiTexCoord3dv (GLenum target, const GLdouble * v)
References GLAPIENTRY, and MULTI_TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord3i()
void GLAPIENTRY _mesa_MultiTexCoord3i (GLenum target, GLint s, GLint t, GLint r)
References GLAPIENTRY, and MULTI_TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord3iv()
void GLAPIENTRY _mesa_MultiTexCoord3iv (GLenum target, const GLint * v)
References GLAPIENTRY, and MULTI_TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord3s()
void GLAPIENTRY _mesa_MultiTexCoord3s (GLenum target, GLshort s, GLshort t, GLshort r)
References GLAPIENTRY, and MULTI_TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord3sv()
void GLAPIENTRY _mesa_MultiTexCoord3sv (GLenum target, const GLshort * v)
References GLAPIENTRY, and MULTI_TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord4d()
void GLAPIENTRY _mesa_MultiTexCoord4d (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
References GLAPIENTRY, and MULTI_TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord4dv()
void GLAPIENTRY _mesa_MultiTexCoord4dv (GLenum target, const GLdouble * v)
References GLAPIENTRY, and MULTI_TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord4i()
void GLAPIENTRY _mesa_MultiTexCoord4i (GLenum target, GLint s, GLint t, GLint r, GLint q)
References GLAPIENTRY, and MULTI_TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord4iv()
void GLAPIENTRY _mesa_MultiTexCoord4iv (GLenum target, const GLint * v)
References GLAPIENTRY, and MULTI_TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord4s()
void GLAPIENTRY _mesa_MultiTexCoord4s (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
References GLAPIENTRY, and MULTI_TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_MultiTexCoord4sv()
void GLAPIENTRY _mesa_MultiTexCoord4sv (GLenum target, const GLshort * v)
References GLAPIENTRY, and MULTI_TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3b()
void GLAPIENTRY _mesa_Normal3b (GLbyte nx, GLbyte ny, GLbyte nz)
References BYTE_TO_FLOAT, GLAPIENTRY, and NORMAL.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3bv()
void GLAPIENTRY _mesa_Normal3bv (const GLbyte * v)
References BYTE_TO_FLOAT, GLAPIENTRY, and NORMAL.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3d()
void GLAPIENTRY _mesa_Normal3d (GLdouble nx, GLdouble ny, GLdouble nz)
References GLAPIENTRY, and NORMAL.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3dv()
void GLAPIENTRY _mesa_Normal3dv (const GLdouble * v)
References GLAPIENTRY, and NORMAL.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3i()
void GLAPIENTRY _mesa_Normal3i (GLint nx, GLint ny, GLint nz)
References GLAPIENTRY, INT_TO_FLOAT, and NORMAL.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3iv()
void GLAPIENTRY _mesa_Normal3iv (const GLint * v)
References GLAPIENTRY, INT_TO_FLOAT, and NORMAL.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3s()
void GLAPIENTRY _mesa_Normal3s (GLshort nx, GLshort ny, GLshort nz)
References GLAPIENTRY, NORMAL, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Normal3sv()
void GLAPIENTRY _mesa_Normal3sv (const GLshort * v)
References GLAPIENTRY, NORMAL, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_Rectd()
void GLAPIENTRY _mesa_Rectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_Rectdv()
void GLAPIENTRY _mesa_Rectdv (const GLdouble * v1, const GLdouble * v2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_Rectfv()
void GLAPIENTRY _mesa_Rectfv (const GLfloat * v1, const GLfloat * v2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_Recti()
void GLAPIENTRY _mesa_Recti (GLint x1, GLint y1, GLint x2, GLint y2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_Rectiv()
void GLAPIENTRY _mesa_Rectiv (const GLint * v1, const GLint * v2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_Rects()
void GLAPIENTRY _mesa_Rects (GLshort x1, GLshort y1, GLshort x2, GLshort y2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_Rectsv()
void GLAPIENTRY _mesa_Rectsv (const GLshort * v1, const GLshort * v2)
References GLAPIENTRY, and RECTF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3b()
void GLAPIENTRY _mesa_SecondaryColor3b (GLbyte red, GLbyte green, GLbyte blue)
References BYTE_TO_FLOAT, GLAPIENTRY, and SECONDARYCOLORF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3bv()
void GLAPIENTRY _mesa_SecondaryColor3bv (const GLbyte * v)
References BYTE_TO_FLOAT, GLAPIENTRY, and SECONDARYCOLORF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3d()
void GLAPIENTRY _mesa_SecondaryColor3d (GLdouble red, GLdouble green, GLdouble blue)
References GLAPIENTRY, and SECONDARYCOLORF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3dv()
void GLAPIENTRY _mesa_SecondaryColor3dv (const GLdouble * v)
References GLAPIENTRY, and SECONDARYCOLORF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3i()
void GLAPIENTRY _mesa_SecondaryColor3i (GLint red, GLint green, GLint blue)
References GLAPIENTRY, INT_TO_FLOAT, and SECONDARYCOLORF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3iv()
void GLAPIENTRY _mesa_SecondaryColor3iv (const GLint * v)
References GLAPIENTRY, INT_TO_FLOAT, and SECONDARYCOLORF.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3s()
void GLAPIENTRY _mesa_SecondaryColor3s (GLshort red, GLshort green, GLshort blue)
References GLAPIENTRY, SECONDARYCOLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3sv()
void GLAPIENTRY _mesa_SecondaryColor3sv (const GLshort * v)
References GLAPIENTRY, SECONDARYCOLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3ub()
void GLAPIENTRY _mesa_SecondaryColor3ub (GLubyte red, GLubyte green, GLubyte blue)
References GLAPIENTRY, SECONDARYCOLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3ubv()
void GLAPIENTRY _mesa_SecondaryColor3ubv (const GLubyte * v)
References GLAPIENTRY, SECONDARYCOLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3ui()
void GLAPIENTRY _mesa_SecondaryColor3ui (GLuint red, GLuint green, GLuint blue)
References GLAPIENTRY, SECONDARYCOLORF, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3uiv()
void GLAPIENTRY _mesa_SecondaryColor3uiv (const GLuint * v)
References GLAPIENTRY, SECONDARYCOLORF, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3us()
void GLAPIENTRY _mesa_SecondaryColor3us (GLushort red, GLushort green, GLushort blue)
References GLAPIENTRY, SECONDARYCOLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_SecondaryColor3usv()
void GLAPIENTRY _mesa_SecondaryColor3usv (const GLushort * v)
References GLAPIENTRY, SECONDARYCOLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord1d()
void GLAPIENTRY _mesa_TexCoord1d (GLdouble s)
References GLAPIENTRY, and TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord1dv()
void GLAPIENTRY _mesa_TexCoord1dv (const GLdouble * v)
References GLAPIENTRY, and TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord1i()
void GLAPIENTRY _mesa_TexCoord1i (GLint s)
References GLAPIENTRY, and TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord1iv()
void GLAPIENTRY _mesa_TexCoord1iv (const GLint * v)
References GLAPIENTRY, and TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord1s()
void GLAPIENTRY _mesa_TexCoord1s (GLshort s)
References GLAPIENTRY, and TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord1sv()
void GLAPIENTRY _mesa_TexCoord1sv (const GLshort * v)
References GLAPIENTRY, and TEXCOORD1.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord2d()
void GLAPIENTRY _mesa_TexCoord2d (GLdouble s, GLdouble t)
References GLAPIENTRY, and TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord2dv()
void GLAPIENTRY _mesa_TexCoord2dv (const GLdouble * v)
References GLAPIENTRY, and TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord2i()
void GLAPIENTRY _mesa_TexCoord2i (GLint s, GLint t)
References GLAPIENTRY, and TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord2iv()
void GLAPIENTRY _mesa_TexCoord2iv (const GLint * v)
References GLAPIENTRY, and TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord2s()
void GLAPIENTRY _mesa_TexCoord2s (GLshort s, GLshort t)
References GLAPIENTRY, and TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord2sv()
void GLAPIENTRY _mesa_TexCoord2sv (const GLshort * v)
References GLAPIENTRY, and TEXCOORD2.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord3d()
void GLAPIENTRY _mesa_TexCoord3d (GLdouble s, GLdouble t, GLdouble r)
References GLAPIENTRY, and TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord3dv()
void GLAPIENTRY _mesa_TexCoord3dv (const GLdouble * v)
References GLAPIENTRY, and TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord3i()
void GLAPIENTRY _mesa_TexCoord3i (GLint s, GLint t, GLint r)
References GLAPIENTRY, and TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord3iv()
void GLAPIENTRY _mesa_TexCoord3iv (const GLint * v)
References GLAPIENTRY, and TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord3s()
void GLAPIENTRY _mesa_TexCoord3s (GLshort s, GLshort t, GLshort r)
References GLAPIENTRY, and TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord3sv()
void GLAPIENTRY _mesa_TexCoord3sv (const GLshort * v)
References GLAPIENTRY, and TEXCOORD3.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord4d()
void GLAPIENTRY _mesa_TexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q)
References GLAPIENTRY, and TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord4dv()
void GLAPIENTRY _mesa_TexCoord4dv (const GLdouble * v)
References GLAPIENTRY, and TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord4i()
void GLAPIENTRY _mesa_TexCoord4i (GLint s, GLint t, GLint r, GLint q)
References GLAPIENTRY, and TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord4iv()
void GLAPIENTRY _mesa_TexCoord4iv (const GLint * v)
References GLAPIENTRY, and TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord4s()
void GLAPIENTRY _mesa_TexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q)
References GLAPIENTRY, and TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_TexCoord4sv()
void GLAPIENTRY _mesa_TexCoord4sv (const GLshort * v)
References GLAPIENTRY, and TEXCOORD4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex2d()
void GLAPIENTRY _mesa_Vertex2d (GLdouble x, GLdouble y)
References GLAPIENTRY, and VERTEX2.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex2dv()
void GLAPIENTRY _mesa_Vertex2dv (const GLdouble * v)
References GLAPIENTRY, and VERTEX2.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex2i()
void GLAPIENTRY _mesa_Vertex2i (GLint x, GLint y)
References GLAPIENTRY, and VERTEX2.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex2iv()
void GLAPIENTRY _mesa_Vertex2iv (const GLint * v)
References GLAPIENTRY, and VERTEX2.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex2s()
void GLAPIENTRY _mesa_Vertex2s (GLshort x, GLshort y)
References GLAPIENTRY, and VERTEX2.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex2sv()
void GLAPIENTRY _mesa_Vertex2sv (const GLshort * v)
References GLAPIENTRY, and VERTEX2.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex3d()
void GLAPIENTRY _mesa_Vertex3d (GLdouble x, GLdouble y, GLdouble z)
References GLAPIENTRY, and VERTEX3.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex3dv()
void GLAPIENTRY _mesa_Vertex3dv (const GLdouble * v)
References GLAPIENTRY, VERTEX2, and VERTEX3.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex3i()
void GLAPIENTRY _mesa_Vertex3i (GLint x, GLint y, GLint z)
References GLAPIENTRY, and VERTEX3.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex3iv()
void GLAPIENTRY _mesa_Vertex3iv (const GLint * v)
References GLAPIENTRY, and VERTEX3.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex3s()
void GLAPIENTRY _mesa_Vertex3s (GLshort x, GLshort y, GLshort z)
References GLAPIENTRY, and VERTEX3.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex3sv()
void GLAPIENTRY _mesa_Vertex3sv (const GLshort * v)
References GLAPIENTRY, and VERTEX3.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex4d()
void GLAPIENTRY _mesa_Vertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References GLAPIENTRY, and VERTEX4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex4dv()
void GLAPIENTRY _mesa_Vertex4dv (const GLdouble * v)
References GLAPIENTRY, and VERTEX4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex4i()
void GLAPIENTRY _mesa_Vertex4i (GLint x, GLint y, GLint z, GLint w)
References GLAPIENTRY, and VERTEX4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex4iv()
void GLAPIENTRY _mesa_Vertex4iv (const GLint * v)
References GLAPIENTRY, and VERTEX4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex4s()
void GLAPIENTRY _mesa_Vertex4s (GLshort x, GLshort y, GLshort z, GLshort w)
References GLAPIENTRY, and VERTEX4.
Referenced by _mesa_loopback_init_api_table().
_mesa_Vertex4sv()
void GLAPIENTRY _mesa_Vertex4sv (const GLshort * v)
References GLAPIENTRY, and VERTEX4.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1d()
void GLAPIENTRY _mesa_VertexAttrib1d (GLuint index, GLdouble x)
References ATTRIB1ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1dNV()
void GLAPIENTRY _mesa_VertexAttrib1dNV (GLuint index, GLdouble x)
References ATTRIB1NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1dv()
void GLAPIENTRY _mesa_VertexAttrib1dv (GLuint index, const GLdouble * v)
References ATTRIB1ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1dvNV()
void GLAPIENTRY _mesa_VertexAttrib1dvNV (GLuint index, const GLdouble * v)
References ATTRIB1NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs1dvNV().
_mesa_VertexAttrib1s()
void GLAPIENTRY _mesa_VertexAttrib1s (GLuint index, GLshort x)
References ATTRIB1ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1sNV()
void GLAPIENTRY _mesa_VertexAttrib1sNV (GLuint index, GLshort x)
References ATTRIB1NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1sv()
void GLAPIENTRY _mesa_VertexAttrib1sv (GLuint index, const GLshort * v)
References ATTRIB1ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib1svNV()
void GLAPIENTRY _mesa_VertexAttrib1svNV (GLuint index, const GLshort * v)
References ATTRIB1NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs1svNV().
_mesa_VertexAttrib2d()
void GLAPIENTRY _mesa_VertexAttrib2d (GLuint index, GLdouble x, GLdouble y)
References ATTRIB2ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib2dNV()
void GLAPIENTRY _mesa_VertexAttrib2dNV (GLuint index, GLdouble x, GLdouble y)
References ATTRIB2NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib2dv()
void GLAPIENTRY _mesa_VertexAttrib2dv (GLuint index, const GLdouble * v)
References ATTRIB2ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib2dvNV()
void GLAPIENTRY _mesa_VertexAttrib2dvNV (GLuint index, const GLdouble * v)
References ATTRIB2NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs2dvNV().
_mesa_VertexAttrib2s()
void GLAPIENTRY _mesa_VertexAttrib2s (GLuint index, GLshort x, GLshort y)
References ATTRIB2ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib2sNV()
void GLAPIENTRY _mesa_VertexAttrib2sNV (GLuint index, GLshort x, GLshort y)
References ATTRIB2NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib2sv()
void GLAPIENTRY _mesa_VertexAttrib2sv (GLuint index, const GLshort * v)
References ATTRIB2ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib2svNV()
void GLAPIENTRY _mesa_VertexAttrib2svNV (GLuint index, const GLshort * v)
References ATTRIB2NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs2svNV().
_mesa_VertexAttrib3d()
void GLAPIENTRY _mesa_VertexAttrib3d (GLuint index, GLdouble x, GLdouble y, GLdouble z)
References ATTRIB4ARB, F, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib3dNV()
void GLAPIENTRY _mesa_VertexAttrib3dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z)
References ATTRIB4NV, F, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib3dv()
void GLAPIENTRY _mesa_VertexAttrib3dv (GLuint index, const GLdouble * v)
References ATTRIB3ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib3dvNV()
void GLAPIENTRY _mesa_VertexAttrib3dvNV (GLuint index, const GLdouble * v)
References ATTRIB3NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs3dvNV().
_mesa_VertexAttrib3s()
void GLAPIENTRY _mesa_VertexAttrib3s (GLuint index, GLshort x, GLshort y, GLshort z)
References ATTRIB3ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib3sNV()
void GLAPIENTRY _mesa_VertexAttrib3sNV (GLuint index, GLshort x, GLshort y, GLshort z)
References ATTRIB3NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib3sv()
void GLAPIENTRY _mesa_VertexAttrib3sv (GLuint index, const GLshort * v)
References ATTRIB3ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib3svNV()
void GLAPIENTRY _mesa_VertexAttrib3svNV (GLuint index, const GLshort * v)
References ATTRIB3NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs3svNV().
_mesa_VertexAttrib4bv()
void GLAPIENTRY _mesa_VertexAttrib4bv (GLuint index, const GLbyte * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4d()
void GLAPIENTRY _mesa_VertexAttrib4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4dNV()
void GLAPIENTRY _mesa_VertexAttrib4dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References ATTRIB4NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4dv()
void GLAPIENTRY _mesa_VertexAttrib4dv (GLuint index, const GLdouble * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4dvNV()
void GLAPIENTRY _mesa_VertexAttrib4dvNV (GLuint index, const GLdouble * v)
References ATTRIB4NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs4dvNV().
_mesa_VertexAttrib4iv()
void GLAPIENTRY _mesa_VertexAttrib4iv (GLuint index, const GLint * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Nbv()
void GLAPIENTRY _mesa_VertexAttrib4Nbv (GLuint index, const GLbyte * v)
References ATTRIB4ARB, BYTE_TO_FLOAT, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Niv()
void GLAPIENTRY _mesa_VertexAttrib4Niv (GLuint index, const GLint * v)
References ATTRIB4ARB, GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Nsv()
void GLAPIENTRY _mesa_VertexAttrib4Nsv (GLuint index, const GLshort * v)
References ATTRIB4ARB, GLAPIENTRY, and SHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Nub()
void GLAPIENTRY _mesa_VertexAttrib4Nub (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
References ATTRIB4ARB, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Nubv()
void GLAPIENTRY _mesa_VertexAttrib4Nubv (GLuint index, const GLubyte * v)
References ATTRIB4ARB, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Nuiv()
void GLAPIENTRY _mesa_VertexAttrib4Nuiv (GLuint index, const GLuint * v)
References ATTRIB4ARB, GLAPIENTRY, and UINT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4Nusv()
void GLAPIENTRY _mesa_VertexAttrib4Nusv (GLuint index, const GLushort * v)
References ATTRIB4ARB, GLAPIENTRY, and USHORT_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4s()
void GLAPIENTRY _mesa_VertexAttrib4s (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4sNV()
void GLAPIENTRY _mesa_VertexAttrib4sNV (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
References ATTRIB4NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4sv()
void GLAPIENTRY _mesa_VertexAttrib4sv (GLuint index, const GLshort * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4svNV()
void GLAPIENTRY _mesa_VertexAttrib4svNV (GLuint index, const GLshort * v)
References ATTRIB4NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs4svNV().
_mesa_VertexAttrib4ubNV()
void GLAPIENTRY _mesa_VertexAttrib4ubNV (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
References ATTRIB4NV, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4ubv()
void GLAPIENTRY _mesa_VertexAttrib4ubv (GLuint index, const GLubyte * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4ubvNV()
void GLAPIENTRY _mesa_VertexAttrib4ubvNV (GLuint index, const GLubyte * v)
References ATTRIB4NV, GLAPIENTRY, and UBYTE_TO_FLOAT.
Referenced by _mesa_loopback_init_api_table(), and _mesa_VertexAttribs4ubvNV().
_mesa_VertexAttrib4uiv()
void GLAPIENTRY _mesa_VertexAttrib4uiv (GLuint index, const GLuint * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttrib4usv()
void GLAPIENTRY _mesa_VertexAttrib4usv (GLuint index, const GLushort * v)
References ATTRIB4ARB, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribI1iv()
void GLAPIENTRY _mesa_VertexAttribI1iv (GLuint index, const GLint * v)
GL_EXT_gpu_shader / GL 3.0 signed/unsigned integer-valued attributes.
Note that attribute indexes do NOT alias conventional attributes.
References ATTRIBI_1I, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribI1uiv()
void GLAPIENTRY _mesa_VertexAttribI1uiv (GLuint index, const GLuint * v)
References ATTRIBI_1UI, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribI4bv()
void GLAPIENTRY _mesa_VertexAttribI4bv (GLuint index, const GLbyte * v)
References ATTRIBI_4I, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribI4sv()
void GLAPIENTRY _mesa_VertexAttribI4sv (GLuint index, const GLshort * v)
References ATTRIBI_4I, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribI4ubv()
void GLAPIENTRY _mesa_VertexAttribI4ubv (GLuint index, const GLubyte * v)
References ATTRIBI_4UI, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribI4usv()
void GLAPIENTRY _mesa_VertexAttribI4usv (GLuint index, const GLushort * v)
References ATTRIBI_4UI, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL1d()
void GLAPIENTRY _mesa_VertexAttribL1d (GLuint index, GLdouble x)
References ATTRIB1_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL1dv()
void GLAPIENTRY _mesa_VertexAttribL1dv (GLuint index, const GLdouble * v)
References ATTRIB1_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL2d()
void GLAPIENTRY _mesa_VertexAttribL2d (GLuint index, GLdouble x, GLdouble y)
References ATTRIB2_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL2dv()
void GLAPIENTRY _mesa_VertexAttribL2dv (GLuint index, const GLdouble * v)
References ATTRIB2_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL3d()
void GLAPIENTRY _mesa_VertexAttribL3d (GLuint index, GLdouble x, GLdouble y, GLdouble z)
References ATTRIB3_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL3dv()
void GLAPIENTRY _mesa_VertexAttribL3dv (GLuint index, const GLdouble * v)
References ATTRIB3_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL4d()
void GLAPIENTRY _mesa_VertexAttribL4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References ATTRIB4_D, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribL4dv()
void GLAPIENTRY _mesa_VertexAttribL4dv (GLuint index, const GLdouble * v)
References ATTRIB4_D.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs1dvNV()
void GLAPIENTRY _mesa_VertexAttribs1dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib1dvNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs1fvNV()
void GLAPIENTRY _mesa_VertexAttribs1fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB1NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs1svNV()
void GLAPIENTRY _mesa_VertexAttribs1svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib1svNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs2dvNV()
void GLAPIENTRY _mesa_VertexAttribs2dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib2dvNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs2fvNV()
void GLAPIENTRY _mesa_VertexAttribs2fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB2NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs2svNV()
void GLAPIENTRY _mesa_VertexAttribs2svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib2svNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs3dvNV()
void GLAPIENTRY _mesa_VertexAttribs3dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib3dvNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs3fvNV()
void GLAPIENTRY _mesa_VertexAttribs3fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB3NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs3svNV()
void GLAPIENTRY _mesa_VertexAttribs3svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib3svNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs4dvNV()
void GLAPIENTRY _mesa_VertexAttribs4dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib4dvNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs4fvNV()
void GLAPIENTRY _mesa_VertexAttribs4fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB4NV, and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs4svNV()
void GLAPIENTRY _mesa_VertexAttribs4svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib4svNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().
_mesa_VertexAttribs4ubvNV()
void GLAPIENTRY _mesa_VertexAttribs4ubvNV (GLuint index, GLsizei n, const GLubyte * v)
References _mesa_VertexAttrib4ubvNV(), and GLAPIENTRY.
Referenced by _mesa_loopback_init_api_table().