Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
api_validate.c File Reference
#include <stdbool.h>
#include "glheader.h"
#include "api_validate.h"
#include "arrayobj.h"
#include "bufferobj.h"
#include "context.h"
#include "imports.h"
#include "mtypes.h"
#include "pipelineobj.h"
#include "enums.h"
#include "state.h"
#include "transformfeedback.h"
#include "uniforms.h"
#include "vbo/vbo.h"
#include "program/prog_print.h"
Functions
static bool check_blend_func_error (struct gl_context *ctx)
GLboolean _mesa_valid_to_render (struct gl_context *ctx, const char *where)
Prior to drawing anything with glBegin, glDrawArrays, etc.
static bool check_valid_to_render (struct gl_context *ctx, const char *function)
Check if OK to draw arrays/elements.
bool _mesa_is_valid_prim_mode (struct gl_context *ctx, GLenum mode)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? The set of legal values depends on whether geometry shaders/programs are supported.
GLboolean _mesa_valid_prim_mode (struct gl_context *ctx, GLenum mode, const char *name)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? Also, do additional checking related to transformation feedback.
static bool valid_elements_type (struct gl_context *ctx, GLenum type, const char *name)
Verify that the element type is valid.
static bool validate_DrawElements_common (struct gl_context *ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, const char *caller)
GLboolean _mesa_validate_DrawElements (struct gl_context *ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
Error checking for glDrawElements().
GLboolean _mesa_validate_MultiDrawElements (struct gl_context *ctx, GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount)
Error checking for glMultiDrawElements().
GLboolean _mesa_validate_DrawRangeElements (struct gl_context *ctx, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
Error checking for glDrawRangeElements().
static bool validate_draw_arrays (struct gl_context *ctx, const char *func, GLenum mode, GLsizei count, GLsizei numInstances)
GLboolean _mesa_validate_DrawArrays (struct gl_context *ctx, GLenum mode, GLsizei count)
Called from the tnl module to error check the function parameters and verify that we really can draw something.
GLboolean _mesa_validate_DrawArraysInstanced (struct gl_context *ctx, GLenum mode, GLint first, GLsizei count, GLsizei numInstances)
GLboolean _mesa_validate_DrawElementsInstanced (struct gl_context *ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei numInstances)
GLboolean _mesa_validate_DrawTransformFeedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj, GLuint stream, GLsizei numInstances)
static GLboolean valid_draw_indirect (struct gl_context *ctx, GLenum mode, const GLvoid *indirect, GLsizei size, const char *name)
static GLboolean valid_draw_indirect_elements (struct gl_context *ctx, GLenum mode, GLenum type, const GLvoid *indirect, GLsizeiptr size, const char *name)
static GLboolean valid_draw_indirect_multi (struct gl_context *ctx, GLsizei primcount, GLsizei stride, const char *name)
GLboolean _mesa_validate_DrawArraysIndirect (struct gl_context *ctx, GLenum mode, const GLvoid *indirect)
GLboolean _mesa_validate_DrawElementsIndirect (struct gl_context *ctx, GLenum mode, GLenum type, const GLvoid *indirect)
GLboolean _mesa_validate_MultiDrawArraysIndirect (struct gl_context *ctx, GLenum mode, const GLvoid *indirect, GLsizei primcount, GLsizei stride)
GLboolean _mesa_validate_MultiDrawElementsIndirect (struct gl_context *ctx, GLenum mode, GLenum type, const GLvoid *indirect, GLsizei primcount, GLsizei stride)
static GLboolean valid_draw_indirect_parameters (struct gl_context *ctx, const char *name, GLintptr drawcount)
GLboolean _mesa_validate_MultiDrawArraysIndirectCount (struct gl_context *ctx, GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
GLboolean _mesa_validate_MultiDrawElementsIndirectCount (struct gl_context *ctx, GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
static bool check_valid_to_compute (struct gl_context *ctx, const char *function)
GLboolean _mesa_validate_DispatchCompute (struct gl_context *ctx, const GLuint *num_groups)
GLboolean _mesa_validate_DispatchComputeGroupSizeARB (struct gl_context *ctx, const GLuint *num_groups, const GLuint *group_size)
static GLboolean valid_dispatch_indirect (struct gl_context *ctx, GLintptr indirect, GLsizei size, const char *name)
GLboolean _mesa_validate_DispatchComputeIndirect (struct gl_context *ctx, GLintptr indirect)
Function Documentation
_mesa_is_valid_prim_mode()
bool _mesa_is_valid_prim_mode (struct gl_context * ctx, GLenum mode)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? The set of legal values depends on whether geometry shaders/programs are supported.
Note: This may be called during display list compilation.
References _mesa_has_geometry_shaders(), _mesa_has_tessellation(), gl_context::API, and API_OPENGL_COMPAT.
Referenced by _mesa_valid_prim_mode(), and save_Begin().
_mesa_valid_prim_mode()
GLboolean _mesa_valid_prim_mode (struct gl_context * ctx, GLenum mode, const char * name)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? Also, do additional checking related to transformation feedback.
Note: this function cannot be called during glNewList(GL_COMPILE) because this code depends on current transform feedback state. Also, do additional checking related to tessellation shaders.
References _mesa_error(), _mesa_is_valid_prim_mode(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_prim_by_nr(), gl_context::_Shader, gl_polygon_attrib::BackMode, gl_pipeline_object::CurrentProgram, gl_polygon_attrib::FrontMode, gl_program::info, gl_context::IntelConservativeRasterization, gl_transform_feedback_state::Mode, gl_context::Polygon, and gl_context::TransformFeedback.
Referenced by _mesa_validate_DrawTransformFeedback(), _mesa_validate_MultiDrawElements(), valid_draw_indirect(), validate_draw_arrays(), and validate_DrawElements_common().
_mesa_valid_to_render()
GLboolean _mesa_valid_to_render (struct gl_context * ctx, const char * where)
Prior to drawing anything with glBegin, glDrawArrays, etc.
this function is called to see if it's valid to render. This involves checking that the current shader is valid and the framebuffer is complete. It also check the current pipeline object is valid if any. If an error is detected it'll be recorded here.
Returns
GL_TRUE if OK to render, GL_FALSE if not
References gl_vertex_program_state::_Enabled, gl_fragment_program_state::_Enabled, gl_framebuffer::_IntegerBuffers, _mesa_error(), _mesa_sampler_uniforms_are_valid(), _mesa_update_state(), _mesa_validate_program_pipeline(), gl_context::_Shader, gl_framebuffer::_Status, gl_program::_Used, gl_pipeline_object::ActiveProgram, gl_context::API, API_OPENGL_COMPAT, gl_polygon_attrib::BackMode, check_blend_func_error(), gl_pipeline_shader_state::Current, gl_pipeline_object::CurrentProgram, gl_context::DrawBuffer, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, gl_pipeline_object::Flags, gl_context::FragmentProgram, gl_polygon_attrib::FrontMode, GLSL_LOG, gl_pipeline_object::Name, gl_context::NewState, gl_context::Pipeline, gl_context::Polygon, gl_pipeline_object::Validated, and gl_context::VertexProgram.
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), _mesa_DrawPixels(), and check_valid_to_render().
_mesa_validate_DispatchCompute()
GLboolean _mesa_validate_DispatchCompute (struct gl_context * ctx, const GLuint * num_groups)
References _mesa_error(), gl_context::_Shader, check_valid_to_compute(), gl_context::Const, gl_pipeline_object::CurrentProgram, FLUSH_CURRENT, gl_program::info, and gl_constants::MaxComputeWorkGroupCount.
Referenced by _mesa_DispatchCompute().
_mesa_validate_DispatchComputeGroupSizeARB()
GLboolean _mesa_validate_DispatchComputeGroupSizeARB (struct gl_context * ctx, const GLuint * num_groups, const GLuint * group_size)
References _mesa_error(), gl_context::_Shader, check_valid_to_compute(), gl_context::Const, gl_pipeline_object::CurrentProgram, FLUSH_CURRENT, GLuint, gl_program::info, gl_constants::MaxComputeVariableGroupInvocations, gl_constants::MaxComputeVariableGroupSize, and gl_constants::MaxComputeWorkGroupCount.
Referenced by _mesa_DispatchComputeGroupSizeARB().
_mesa_validate_DispatchComputeIndirect()
GLboolean _mesa_validate_DispatchComputeIndirect (struct gl_context * ctx, GLintptr indirect)
References FLUSH_CURRENT, GLuint, and valid_dispatch_indirect().
Referenced by _mesa_DispatchComputeIndirect().
_mesa_validate_DrawArrays()
GLboolean _mesa_validate_DrawArrays (struct gl_context * ctx, GLenum mode, GLsizei count)
Called from the tnl module to error check the function parameters and verify that we really can draw something.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References validate_draw_arrays().
_mesa_validate_DrawArraysIndirect()
GLboolean _mesa_validate_DrawArraysIndirect (struct gl_context * ctx, GLenum mode, const GLvoid * indirect)
References FLUSH_CURRENT, GLuint, and valid_draw_indirect().
_mesa_validate_DrawArraysInstanced()
GLboolean _mesa_validate_DrawArraysInstanced (struct gl_context * ctx, GLenum mode, GLint first, GLsizei count, GLsizei numInstances)
References _mesa_error(), and validate_draw_arrays().
_mesa_validate_DrawElements()
GLboolean _mesa_validate_DrawElements (struct gl_context * ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
Error checking for glDrawElements().
Includes parameter checking and VBO bounds checking.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References FLUSH_CURRENT, and validate_DrawElements_common().
_mesa_validate_DrawElementsIndirect()
GLboolean _mesa_validate_DrawElementsIndirect (struct gl_context * ctx, GLenum mode, GLenum type, const GLvoid * indirect)
References FLUSH_CURRENT, GLuint, and valid_draw_indirect_elements().
_mesa_validate_DrawElementsInstanced()
GLboolean _mesa_validate_DrawElementsInstanced (struct gl_context * ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLsizei numInstances)
References _mesa_error(), FLUSH_CURRENT, and validate_DrawElements_common().
_mesa_validate_DrawRangeElements()
GLboolean _mesa_validate_DrawRangeElements (struct gl_context * ctx, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices)
Error checking for glDrawRangeElements().
Includes parameter checking and VBO bounds checking.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References _mesa_error(), FLUSH_CURRENT, and validate_DrawElements_common().
_mesa_validate_DrawTransformFeedback()
GLboolean _mesa_validate_DrawTransformFeedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj, GLuint stream, GLsizei numInstances)
References _mesa_error(), _mesa_valid_prim_mode(), check_valid_to_render(), gl_context::Const, gl_transform_feedback_object::EndedAnytime, gl_transform_feedback_object::EverBound, FLUSH_CURRENT, and gl_constants::MaxVertexStreams.
_mesa_validate_MultiDrawArraysIndirect()
GLboolean _mesa_validate_MultiDrawArraysIndirect (struct gl_context * ctx, GLenum mode, const GLvoid * indirect, GLsizei primcount, GLsizei stride)
References FLUSH_CURRENT, GLuint, valid_draw_indirect(), and valid_draw_indirect_multi().
_mesa_validate_MultiDrawArraysIndirectCount()
GLboolean _mesa_validate_MultiDrawArraysIndirectCount (struct gl_context * ctx, GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
References FLUSH_CURRENT, GLuint, valid_draw_indirect(), valid_draw_indirect_multi(), and valid_draw_indirect_parameters().
_mesa_validate_MultiDrawElements()
GLboolean _mesa_validate_MultiDrawElements (struct gl_context * ctx, GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount)
Error checking for glMultiDrawElements().
Includes parameter checking and VBO bounds checking.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References _mesa_error(), _mesa_is_bufferobj(), _mesa_valid_prim_mode(), gl_context::Array, check_valid_to_render(), FLUSH_CURRENT, gl_vertex_array_object::IndexBufferObj, valid_elements_type(), and gl_array_attrib::VAO.
_mesa_validate_MultiDrawElementsIndirect()
GLboolean _mesa_validate_MultiDrawElementsIndirect (struct gl_context * ctx, GLenum mode, GLenum type, const GLvoid * indirect, GLsizei primcount, GLsizei stride)
References FLUSH_CURRENT, GLuint, valid_draw_indirect_elements(), and valid_draw_indirect_multi().
_mesa_validate_MultiDrawElementsIndirectCount()
GLboolean _mesa_validate_MultiDrawElementsIndirectCount (struct gl_context * ctx, GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
References FLUSH_CURRENT, GLuint, valid_draw_indirect_elements(), valid_draw_indirect_multi(), and valid_draw_indirect_parameters().
check_blend_func_error()
static bool check_blend_func_error (struct gl_context * ctx) static
References gl_colorbuffer_attrib::_AdvancedBlendMode, gl_pipeline_object::_CurrentFragmentProgram, _mesa_enum_to_string(), _mesa_error(), gl_framebuffer::_NumColorDrawBuffers, gl_context::_Shader, gl_colorbuffer_attrib::_UsesDualSrc, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, gl_context::Color, gl_framebuffer::ColorDrawBuffer, gl_context::Const, gl_context::DrawBuffer, gl_colorbuffer_attrib::EquationRGB, gl_constants::MaxDualSourceDrawBuffers, and gl_program::sh.
Referenced by _mesa_valid_to_render().
check_valid_to_compute()
static bool check_valid_to_compute (struct gl_context * ctx, const char * function) static
References _mesa_error(), _mesa_has_compute_shaders(), gl_context::_Shader, and gl_pipeline_object::CurrentProgram.
Referenced by _mesa_validate_DispatchCompute(), _mesa_validate_DispatchComputeGroupSizeARB(), and valid_dispatch_indirect().
check_valid_to_render()
static bool check_valid_to_render (struct gl_context * ctx, const char * function) static
Check if OK to draw arrays/elements.
References gl_vertex_program_state::_Current, gl_tess_ctrl_program_state::_Current, gl_tess_eval_program_state::_Current, _mesa_all_buffers_are_unmapped(), _mesa_error(), _mesa_is_gles3(), _mesa_valid_to_render(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_context::Array, gl_array_attrib::DefaultVAO, gl_array_attributes::Enabled, gl_context::TessCtrlProgram, gl_context::TessEvalProgram, gl_array_attrib::VAO, gl_vertex_array_object::VertexAttrib, and gl_context::VertexProgram.
Referenced by _mesa_validate_DrawTransformFeedback(), _mesa_validate_MultiDrawElements(), valid_draw_indirect(), validate_draw_arrays(), and validate_DrawElements_common().
valid_dispatch_indirect()
static GLboolean valid_dispatch_indirect (struct gl_context * ctx, GLintptr indirect, GLsizei size, const char * name) static
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), gl_context::_Shader, check_valid_to_compute(), gl_pipeline_object::CurrentProgram, gl_context::DispatchIndirectBuffer, GLuint, gl_program::info, and gl_buffer_object::Size.
Referenced by _mesa_validate_DispatchComputeIndirect().
valid_draw_indirect()
static GLboolean valid_draw_indirect (struct gl_context * ctx, GLenum mode, const GLvoid * indirect, GLsizei size, const char * name) static
References gl_vertex_array_object::_Enabled, _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), _mesa_is_gles31(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), gl_context::Array, check_valid_to_render(), gl_array_attrib::DefaultVAO, gl_context::DrawIndirectBuffer, gl_context::Extensions, GLuint, gl_extensions::OES_geometry_shader, gl_buffer_object::Size, gl_array_attrib::VAO, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by _mesa_validate_DrawArraysIndirect(), _mesa_validate_MultiDrawArraysIndirect(), _mesa_validate_MultiDrawArraysIndirectCount(), and valid_draw_indirect_elements().
valid_draw_indirect_elements()
static GLboolean valid_draw_indirect_elements (struct gl_context * ctx, GLenum mode, GLenum type, const GLvoid * indirect, GLsizeiptr size, const char * name) inline static
References _mesa_error(), _mesa_is_bufferobj(), gl_context::Array, gl_vertex_array_object::IndexBufferObj, valid_draw_indirect(), valid_elements_type(), and gl_array_attrib::VAO.
Referenced by _mesa_validate_DrawElementsIndirect(), _mesa_validate_MultiDrawElementsIndirect(), and _mesa_validate_MultiDrawElementsIndirectCount().
valid_draw_indirect_multi()
static GLboolean valid_draw_indirect_multi (struct gl_context * ctx, GLsizei primcount, GLsizei stride, const char * name) inline static
References _mesa_error().
Referenced by _mesa_validate_MultiDrawArraysIndirect(), _mesa_validate_MultiDrawArraysIndirectCount(), _mesa_validate_MultiDrawElementsIndirect(), and _mesa_validate_MultiDrawElementsIndirectCount().
valid_draw_indirect_parameters()
static GLboolean valid_draw_indirect_parameters (struct gl_context * ctx, const char * name, GLintptr drawcount) static
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), gl_context::ParameterBuffer, and gl_buffer_object::Size.
Referenced by _mesa_validate_MultiDrawArraysIndirectCount(), and _mesa_validate_MultiDrawElementsIndirectCount().
valid_elements_type()
static bool valid_elements_type (struct gl_context * ctx, GLenum type, const char * name) static
Verify that the element type is valid.
Generates GL_INVALID_ENUM and returns false if it is not.
References _mesa_enum_to_string(), and _mesa_error().
Referenced by _mesa_validate_MultiDrawElements(), valid_draw_indirect_elements(), and validate_DrawElements_common().
validate_draw_arrays()
static bool validate_draw_arrays (struct gl_context * ctx, const char * func, GLenum mode, GLsizei count, GLsizei numInstances) static
References _mesa_error(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), check_valid_to_render(), gl_transform_feedback_state::CurrentObject, FLUSH_CURRENT, gl_transform_feedback_object::GlesRemainingPrims, gl_context::TransformFeedback, and vbo_count_tessellated_primitives().
Referenced by _mesa_validate_DrawArrays(), and _mesa_validate_DrawArraysInstanced().
validate_DrawElements_common()
static bool validate_DrawElements_common (struct gl_context * ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, const char * caller) static
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), gl_context::Array, check_valid_to_render(), gl_vertex_array_object::IndexBufferObj, valid_elements_type(), and gl_array_attrib::VAO.
Referenced by _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), and _mesa_validate_DrawRangeElements().