Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
api_arrayelt.c File Reference
#include "glheader.h"
#include "arrayobj.h"
#include "api_arrayelt.h"
#include "bufferobj.h"
#include "context.h"
#include "imports.h"
#include "macros.h"
#include "mtypes.h"
#include "main/dispatch.h"
#include "varray.h"
Data Structures
struct AEarray
struct AEattrib
struct AEcontext
Macros
#define NUM_TYPES 8
Typedefs
typedef void(GLAPIENTRY * array_func) (const void *)
This file implements the glArrayElement() function.
typedef void(GLAPIENTRY * attrib_func) (GLuint indx, const void *data)
Functions
static AEcontext * AE_CONTEXT (struct gl_context *ctx)
Cast wrapper.
static int TYPE_IDX (GLenum t)
static void GLAPIENTRY VertexAttrib1NbvNV (GLuint index, const GLbyte *v)
GL_NV_vertex_program.
static void GLAPIENTRY VertexAttrib1bvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib2NbvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib2bvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib3NbvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib3bvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib4NbvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib4bvNV (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib1NubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib1ubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib2NubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib2ubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib3NubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib3ubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib4NubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib4ubvNV (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib1NsvNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib1svNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib2NsvNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib2svNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib3NsvNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib3svNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib4NsvNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib4svNV (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib1NusvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib1usvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib2NusvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib2usvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib3NusvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib3usvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib4NusvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib4usvNV (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib1NivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib1ivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib2NivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib2ivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib3NivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib3ivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib4NivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib4ivNV (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib1NuivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib1uivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib2NuivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib2uivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib3NuivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib3uivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib4NuivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib4uivNV (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib1fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib2fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib3fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib4fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib1dvNV (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib2dvNV (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib3dvNV (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib4dvNV (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib1NbvARB (GLuint index, const GLbyte *v)
GL_ARB_vertex_program.
static void GLAPIENTRY VertexAttrib1bvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib2NbvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib2bvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib3NbvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib3bvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib4NbvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib4bvARB (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttrib1NubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib1ubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib2NubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib2ubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib3NubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib3ubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib4NubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib4ubvARB (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttrib1NsvARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib1svARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib2NsvARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib2svARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib3NsvARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib3svARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib4NsvARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib4svARB (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttrib1NusvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib1usvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib2NusvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib2usvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib3NusvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib3usvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib4NusvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib4usvARB (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttrib1NivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib1ivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib2NivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib2ivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib3NivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib3ivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib4NivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib4ivARB (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttrib1NuivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib1uivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib2NuivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib2uivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib3NuivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib3uivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib4NuivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib4uivARB (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttrib1fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib2fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib3fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib4fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY VertexAttrib1dvARB (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib2dvARB (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib3dvARB (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttrib4dvARB (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttribI1bv (GLuint index, const GLbyte *v)
Integer-valued attributes.
static void GLAPIENTRY VertexAttribI2bv (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttribI3bv (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttribI4bv (GLuint index, const GLbyte *v)
static void GLAPIENTRY VertexAttribI1ubv (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttribI2ubv (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttribI3ubv (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttribI4ubv (GLuint index, const GLubyte *v)
static void GLAPIENTRY VertexAttribI1sv (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttribI2sv (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttribI3sv (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttribI4sv (GLuint index, const GLshort *v)
static void GLAPIENTRY VertexAttribI1usv (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttribI2usv (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttribI3usv (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttribI4usv (GLuint index, const GLushort *v)
static void GLAPIENTRY VertexAttribI1iv (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttribI2iv (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttribI3iv (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttribI4iv (GLuint index, const GLint *v)
static void GLAPIENTRY VertexAttribI1uiv (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttribI2uiv (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttribI3uiv (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttribI4uiv (GLuint index, const GLuint *v)
static void GLAPIENTRY VertexAttribL1dv (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttribL2dv (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttribL3dv (GLuint index, const GLdouble *v)
static void GLAPIENTRY VertexAttribL4dv (GLuint index, const GLdouble *v)
GLboolean _ae_create_context (struct gl_context *ctx)
void _ae_destroy_context (struct gl_context *ctx)
static void check_vbo (AEcontext *actx, struct gl_buffer_object *vbo)
Check if the given vertex buffer object exists and is not mapped.
static void _ae_update_state (struct gl_context *ctx)
Make a list of per-vertex functions to call for each glArrayElement call.
void _ae_map_vbos (struct gl_context *ctx)
Before replaying glArrayElements calls we need to map (for reading) any VBOs referenced by the enabled vertex arrays.
void _ae_unmap_vbos (struct gl_context *ctx)
Unmap VBOs.
void GLAPIENTRY _ae_ArrayElement (GLint elt)
Called via glArrayElement() and glDrawArrays().
void _ae_invalidate_state (struct gl_context *ctx, GLbitfield new_state)
void _mesa_install_arrayelt_vtxfmt (struct _glapi_table *disp, const GLvertexformat *vfmt)
Variables
static const int ColorFuncs [2][NUM_TYPES]
static const int VertexFuncs [3][NUM_TYPES]
static const int IndexFuncs [NUM_TYPES]
static const int NormalFuncs [NUM_TYPES]
static int SecondaryColorFuncs [NUM_TYPES]
static int FogCoordFuncs [NUM_TYPES]
static attrib_func AttribFuncsNV [2][4][NUM_TYPES]
static const attrib_func AttribFuncsARB [4][4][NUM_TYPES]
Macro Definition Documentation
NUM_TYPES
#define NUM_TYPES 8
Typedef Documentation
array_func
typedef void(GLAPIENTRY * array_func) (const void *)
This file implements the glArrayElement() function.
It involves looking at the format/type of all the enabled vertex arrays and emitting a list of pointers to functions which set the per-vertex state for the element/index.
attrib_func
typedef void(GLAPIENTRY * attrib_func) (GLuint indx, const void *data)
Function Documentation
_ae_ArrayElement()
void GLAPIENTRY _ae_ArrayElement (GLint elt)
Called via glArrayElement() and glDrawArrays().
Issue the glNormal, glVertex, glColor, glVertexAttrib, etc functions for all enabled vertex arrays (for elt-th element). Note: this may be called during display list construction.
References _ae_map_vbos(), _ae_unmap_vbos(), _ae_update_state(), _mesa_vertex_attrib_address(), ADD_POINTERS, AE_CONTEXT(), AEarray::array, AEattrib::array, AEcontext::arrays, AEcontext::attribs, AEarray::binding, AEattrib::binding, gl_vertex_buffer_binding::BufferObj, AEattrib::func, GET_CURRENT_CONTEXT, GET_DISPATCH, AEattrib::index, MAP_INTERNAL, AEcontext::mapped_vbos, gl_buffer_object::Mappings, AEcontext::NewState, AEcontext::nr_vbos, AEarray::offset, gl_buffer_mapping::Pointer, and gl_vertex_buffer_binding::Stride.
Referenced by save_vtxfmt_init().
_ae_create_context()
GLboolean _ae_create_context (struct gl_context * ctx)
References AE_CONTEXT(), gl_context::aelt_context, FogCoordFuncs, AEcontext::NewState, and SecondaryColorFuncs.
_ae_destroy_context()
void _ae_destroy_context (struct gl_context * ctx)
References AE_CONTEXT(), and gl_context::aelt_context.
_ae_invalidate_state()
void _ae_invalidate_state (struct gl_context * ctx, GLbitfield new_state)
References _NEW_ARRAY, _NEW_PROGRAM, AE_CONTEXT(), AEcontext::mapped_vbos, and AEcontext::NewState.
Referenced by client_state().
_ae_map_vbos()
void _ae_map_vbos (struct gl_context * ctx)
Before replaying glArrayElements calls we need to map (for reading) any VBOs referenced by the enabled vertex arrays.
References _ae_update_state(), AE_CONTEXT(), gl_context::Driver, GLuint, MAP_INTERNAL, dd_function_table::MapBufferRange, AEcontext::mapped_vbos, AEcontext::NewState, AEcontext::nr_vbos, gl_buffer_object::Size, and AEcontext::vbo.
Referenced by _ae_ArrayElement().
_ae_unmap_vbos()
void _ae_unmap_vbos (struct gl_context * ctx)
Unmap VBOs.
References AE_CONTEXT(), gl_context::Driver, GLAPIENTRY, GLuint, MAP_INTERNAL, AEcontext::mapped_vbos, AEcontext::NewState, AEcontext::nr_vbos, dd_function_table::UnmapBuffer, and AEcontext::vbo.
Referenced by _ae_ArrayElement().
_ae_update_state()
static void _ae_update_state (struct gl_context * ctx) static
Make a list of per-vertex functions to call for each glArrayElement call.
These functions access the array data (i.e. glVertex, glColor, glNormal, etc). Note: this may be called during display list construction.
References AE_CONTEXT(), AEarray::array, AEattrib::array, gl_context::Array, AEcontext::arrays, AttribFuncsARB, AttribFuncsNV, AEcontext::attribs, AEarray::binding, AEattrib::binding, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, check_vbo(), ColorFuncs, gl_context::Const, gl_array_attributes::Doubles, gl_array_attributes::Enabled, FogCoordFuncs, AEattrib::func, GLuint, AEattrib::index, gl_vertex_array_object::IndexBufferObj, IndexFuncs, gl_array_attributes::Integer, gl_constants::MaxTextureCoordUnits, AEcontext::NewState, NormalFuncs, gl_array_attributes::Normalized, AEcontext::nr_vbos, AEarray::offset, SecondaryColorFuncs, gl_array_attributes::Size, gl_array_attributes::Type, TYPE_IDX(), gl_array_attrib::VAO, gl_vertex_array_object::VertexAttrib, and VertexFuncs.
Referenced by _ae_ArrayElement(), and _ae_map_vbos().
_mesa_install_arrayelt_vtxfmt()
void _mesa_install_arrayelt_vtxfmt (struct _glapi_table * disp, const GLvertexformat * vfmt)
Referenced by install_vtxfmt().
AE_CONTEXT()
static AEcontext* AE_CONTEXT (struct gl_context * ctx) inline static
Cast wrapper.
References gl_context::aelt_context.
Referenced by _ae_ArrayElement(), _ae_create_context(), _ae_destroy_context(), _ae_invalidate_state(), _ae_map_vbos(), _ae_unmap_vbos(), and _ae_update_state().
check_vbo()
static void check_vbo (AEcontext * actx, struct gl_buffer_object * vbo) static
Check if the given vertex buffer object exists and is not mapped.
If so, add it to the list of buffers we must map before executing an glArrayElement call.
References _mesa_bufferobj_mapped(), _mesa_is_bufferobj(), GLuint, MAP_INTERNAL, AEcontext::nr_vbos, and AEcontext::vbo.
Referenced by _ae_update_state().
TYPE_IDX()
static int TYPE_IDX (GLenum t) inline static
Referenced by _ae_update_state().
VertexAttrib1bvARB()
static void GLAPIENTRY VertexAttrib1bvARB (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1bvNV()
static void GLAPIENTRY VertexAttrib1bvNV (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1dvARB()
static void GLAPIENTRY VertexAttrib1dvARB (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1dvNV()
static void GLAPIENTRY VertexAttrib1dvNV (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1fvARB()
static void GLAPIENTRY VertexAttrib1fvARB (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1fvNV()
static void GLAPIENTRY VertexAttrib1fvNV (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1ivARB()
static void GLAPIENTRY VertexAttrib1ivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1ivNV()
static void GLAPIENTRY VertexAttrib1ivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1NbvARB()
static void GLAPIENTRY VertexAttrib1NbvARB (GLuint index, const GLbyte * v) static
GL_ARB_vertex_program.
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1NbvNV()
static void GLAPIENTRY VertexAttrib1NbvNV (GLuint index, const GLbyte * v) static
GL_NV_vertex_program.
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1NivARB()
static void GLAPIENTRY VertexAttrib1NivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib1NivNV()
static void GLAPIENTRY VertexAttrib1NivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib1NsvARB()
static void GLAPIENTRY VertexAttrib1NsvARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib1NsvNV()
static void GLAPIENTRY VertexAttrib1NsvNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib1NubvARB()
static void GLAPIENTRY VertexAttrib1NubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib1NubvNV()
static void GLAPIENTRY VertexAttrib1NubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib1NuivARB()
static void GLAPIENTRY VertexAttrib1NuivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib1NuivNV()
static void GLAPIENTRY VertexAttrib1NuivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib1NusvARB()
static void GLAPIENTRY VertexAttrib1NusvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib1NusvNV()
static void GLAPIENTRY VertexAttrib1NusvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib1svARB()
static void GLAPIENTRY VertexAttrib1svARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1svNV()
static void GLAPIENTRY VertexAttrib1svNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1ubvARB()
static void GLAPIENTRY VertexAttrib1ubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1ubvNV()
static void GLAPIENTRY VertexAttrib1ubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1uivARB()
static void GLAPIENTRY VertexAttrib1uivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1uivNV()
static void GLAPIENTRY VertexAttrib1uivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1usvARB()
static void GLAPIENTRY VertexAttrib1usvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib1usvNV()
static void GLAPIENTRY VertexAttrib1usvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2bvARB()
static void GLAPIENTRY VertexAttrib2bvARB (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2bvNV()
static void GLAPIENTRY VertexAttrib2bvNV (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2dvARB()
static void GLAPIENTRY VertexAttrib2dvARB (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2dvNV()
static void GLAPIENTRY VertexAttrib2dvNV (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2fvARB()
static void GLAPIENTRY VertexAttrib2fvARB (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2fvNV()
static void GLAPIENTRY VertexAttrib2fvNV (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2ivARB()
static void GLAPIENTRY VertexAttrib2ivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2ivNV()
static void GLAPIENTRY VertexAttrib2ivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2NbvARB()
static void GLAPIENTRY VertexAttrib2NbvARB (GLuint index, const GLbyte * v) static
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2NbvNV()
static void GLAPIENTRY VertexAttrib2NbvNV (GLuint index, const GLbyte * v) static
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2NivARB()
static void GLAPIENTRY VertexAttrib2NivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib2NivNV()
static void GLAPIENTRY VertexAttrib2NivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib2NsvARB()
static void GLAPIENTRY VertexAttrib2NsvARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib2NsvNV()
static void GLAPIENTRY VertexAttrib2NsvNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib2NubvARB()
static void GLAPIENTRY VertexAttrib2NubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib2NubvNV()
static void GLAPIENTRY VertexAttrib2NubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib2NuivARB()
static void GLAPIENTRY VertexAttrib2NuivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib2NuivNV()
static void GLAPIENTRY VertexAttrib2NuivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib2NusvARB()
static void GLAPIENTRY VertexAttrib2NusvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib2NusvNV()
static void GLAPIENTRY VertexAttrib2NusvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib2svARB()
static void GLAPIENTRY VertexAttrib2svARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2svNV()
static void GLAPIENTRY VertexAttrib2svNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2ubvARB()
static void GLAPIENTRY VertexAttrib2ubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2ubvNV()
static void GLAPIENTRY VertexAttrib2ubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2uivARB()
static void GLAPIENTRY VertexAttrib2uivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2uivNV()
static void GLAPIENTRY VertexAttrib2uivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2usvARB()
static void GLAPIENTRY VertexAttrib2usvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib2usvNV()
static void GLAPIENTRY VertexAttrib2usvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3bvARB()
static void GLAPIENTRY VertexAttrib3bvARB (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3bvNV()
static void GLAPIENTRY VertexAttrib3bvNV (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3dvARB()
static void GLAPIENTRY VertexAttrib3dvARB (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3dvNV()
static void GLAPIENTRY VertexAttrib3dvNV (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3fvARB()
static void GLAPIENTRY VertexAttrib3fvARB (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3fvNV()
static void GLAPIENTRY VertexAttrib3fvNV (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3ivARB()
static void GLAPIENTRY VertexAttrib3ivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3ivNV()
static void GLAPIENTRY VertexAttrib3ivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3NbvARB()
static void GLAPIENTRY VertexAttrib3NbvARB (GLuint index, const GLbyte * v) static
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3NbvNV()
static void GLAPIENTRY VertexAttrib3NbvNV (GLuint index, const GLbyte * v) static
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3NivARB()
static void GLAPIENTRY VertexAttrib3NivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib3NivNV()
static void GLAPIENTRY VertexAttrib3NivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib3NsvARB()
static void GLAPIENTRY VertexAttrib3NsvARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib3NsvNV()
static void GLAPIENTRY VertexAttrib3NsvNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib3NubvARB()
static void GLAPIENTRY VertexAttrib3NubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib3NubvNV()
static void GLAPIENTRY VertexAttrib3NubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib3NuivARB()
static void GLAPIENTRY VertexAttrib3NuivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib3NuivNV()
static void GLAPIENTRY VertexAttrib3NuivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib3NusvARB()
static void GLAPIENTRY VertexAttrib3NusvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib3NusvNV()
static void GLAPIENTRY VertexAttrib3NusvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib3svARB()
static void GLAPIENTRY VertexAttrib3svARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3svNV()
static void GLAPIENTRY VertexAttrib3svNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3ubvARB()
static void GLAPIENTRY VertexAttrib3ubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3ubvNV()
static void GLAPIENTRY VertexAttrib3ubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3uivARB()
static void GLAPIENTRY VertexAttrib3uivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3uivNV()
static void GLAPIENTRY VertexAttrib3uivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3usvARB()
static void GLAPIENTRY VertexAttrib3usvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib3usvNV()
static void GLAPIENTRY VertexAttrib3usvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4bvARB()
static void GLAPIENTRY VertexAttrib4bvARB (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4bvNV()
static void GLAPIENTRY VertexAttrib4bvNV (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4dvARB()
static void GLAPIENTRY VertexAttrib4dvARB (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4dvNV()
static void GLAPIENTRY VertexAttrib4dvNV (GLuint index, const GLdouble * v) static
References GET_DISPATCH.
VertexAttrib4fvARB()
static void GLAPIENTRY VertexAttrib4fvARB (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4fvNV()
static void GLAPIENTRY VertexAttrib4fvNV (GLuint index, const GLfloat * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4ivARB()
static void GLAPIENTRY VertexAttrib4ivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4ivNV()
static void GLAPIENTRY VertexAttrib4ivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4NbvARB()
static void GLAPIENTRY VertexAttrib4NbvARB (GLuint index, const GLbyte * v) static
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4NbvNV()
static void GLAPIENTRY VertexAttrib4NbvNV (GLuint index, const GLbyte * v) static
References BYTE_TO_FLOAT, GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4NivARB()
static void GLAPIENTRY VertexAttrib4NivARB (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib4NivNV()
static void GLAPIENTRY VertexAttrib4NivNV (GLuint index, const GLint * v) static
References GET_DISPATCH, GLAPIENTRY, and INT_TO_FLOAT.
VertexAttrib4NsvARB()
static void GLAPIENTRY VertexAttrib4NsvARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib4NsvNV()
static void GLAPIENTRY VertexAttrib4NsvNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, GLAPIENTRY, and SHORT_TO_FLOAT.
VertexAttrib4NubvARB()
static void GLAPIENTRY VertexAttrib4NubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib4NubvNV()
static void GLAPIENTRY VertexAttrib4NubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, GLAPIENTRY, and UBYTE_TO_FLOAT.
VertexAttrib4NuivARB()
static void GLAPIENTRY VertexAttrib4NuivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib4NuivNV()
static void GLAPIENTRY VertexAttrib4NuivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, GLAPIENTRY, and UINT_TO_FLOAT.
VertexAttrib4NusvARB()
static void GLAPIENTRY VertexAttrib4NusvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib4NusvNV()
static void GLAPIENTRY VertexAttrib4NusvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, GLAPIENTRY, and USHORT_TO_FLOAT.
VertexAttrib4svARB()
static void GLAPIENTRY VertexAttrib4svARB (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4svNV()
static void GLAPIENTRY VertexAttrib4svNV (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4ubvARB()
static void GLAPIENTRY VertexAttrib4ubvARB (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4ubvNV()
static void GLAPIENTRY VertexAttrib4ubvNV (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4uivARB()
static void GLAPIENTRY VertexAttrib4uivARB (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4uivNV()
static void GLAPIENTRY VertexAttrib4uivNV (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4usvARB()
static void GLAPIENTRY VertexAttrib4usvARB (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttrib4usvNV()
static void GLAPIENTRY VertexAttrib4usvNV (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI1bv()
static void GLAPIENTRY VertexAttribI1bv (GLuint index, const GLbyte * v) static
Integer-valued attributes.
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI1iv()
static void GLAPIENTRY VertexAttribI1iv (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI1sv()
static void GLAPIENTRY VertexAttribI1sv (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI1ubv()
static void GLAPIENTRY VertexAttribI1ubv (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI1uiv()
static void GLAPIENTRY VertexAttribI1uiv (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI1usv()
static void GLAPIENTRY VertexAttribI1usv (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI2bv()
static void GLAPIENTRY VertexAttribI2bv (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI2iv()
static void GLAPIENTRY VertexAttribI2iv (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI2sv()
static void GLAPIENTRY VertexAttribI2sv (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI2ubv()
static void GLAPIENTRY VertexAttribI2ubv (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI2uiv()
static void GLAPIENTRY VertexAttribI2uiv (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI2usv()
static void GLAPIENTRY VertexAttribI2usv (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI3bv()
static void GLAPIENTRY VertexAttribI3bv (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI3iv()
static void GLAPIENTRY VertexAttribI3iv (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI3sv()
static void GLAPIENTRY VertexAttribI3sv (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI3ubv()
static void GLAPIENTRY VertexAttribI3ubv (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI3uiv()
static void GLAPIENTRY VertexAttribI3uiv (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI3usv()
static void GLAPIENTRY VertexAttribI3usv (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI4bv()
static void GLAPIENTRY VertexAttribI4bv (GLuint index, const GLbyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI4iv()
static void GLAPIENTRY VertexAttribI4iv (GLuint index, const GLint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI4sv()
static void GLAPIENTRY VertexAttribI4sv (GLuint index, const GLshort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI4ubv()
static void GLAPIENTRY VertexAttribI4ubv (GLuint index, const GLubyte * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI4uiv()
static void GLAPIENTRY VertexAttribI4uiv (GLuint index, const GLuint * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribI4usv()
static void GLAPIENTRY VertexAttribI4usv (GLuint index, const GLushort * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribL1dv()
static void GLAPIENTRY VertexAttribL1dv (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribL2dv()
static void GLAPIENTRY VertexAttribL2dv (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribL3dv()
static void GLAPIENTRY VertexAttribL3dv (GLuint index, const GLdouble * v) static
References GET_DISPATCH, and GLAPIENTRY.
VertexAttribL4dv()
static void GLAPIENTRY VertexAttribL4dv (GLuint index, const GLdouble * v) static
References GET_DISPATCH.
Variable Documentation
AttribFuncsARB
const attrib_func AttribFuncsARB[4][4][NUM_TYPES] static
Referenced by _ae_update_state().
AttribFuncsNV
attrib_func AttribFuncsNV[2][4][NUM_TYPES] static
Referenced by _ae_update_state().
ColorFuncs
const int ColorFuncs[2][NUM_TYPES] static
Initial value:
= {
   {
      _gloffset_Color3bv,
      _gloffset_Color3ubv,
      _gloffset_Color3sv,
      _gloffset_Color3usv,
      _gloffset_Color3iv,
      _gloffset_Color3uiv,
      _gloffset_Color3fv,
      _gloffset_Color3dv,
   },
   {
      _gloffset_Color4bv,
      _gloffset_Color4ubv,
      _gloffset_Color4sv,
      _gloffset_Color4usv,
      _gloffset_Color4iv,
      _gloffset_Color4uiv,
      _gloffset_Color4fv,
      _gloffset_Color4dv,
   },
}
Referenced by _ae_update_state().
FogCoordFuncs
int FogCoordFuncs[NUM_TYPES] static
Referenced by _ae_create_context(), and _ae_update_state().
IndexFuncs
const int IndexFuncs[NUM_TYPES] static
Initial value:
= {
   -1,
   _gloffset_Indexubv,
   _gloffset_Indexsv,
   -1,
   _gloffset_Indexiv,
   -1,
   _gloffset_Indexfv,
   _gloffset_Indexdv,
}
Referenced by _ae_update_state().
NormalFuncs
const int NormalFuncs[NUM_TYPES] static
Initial value:
= {
   _gloffset_Normal3bv,
   -1,
   _gloffset_Normal3sv,
   -1,
   _gloffset_Normal3iv,
   -1,
   _gloffset_Normal3fv,
   _gloffset_Normal3dv,
}
Referenced by _ae_update_state().
SecondaryColorFuncs
int SecondaryColorFuncs[NUM_TYPES] static
Referenced by _ae_create_context(), and _ae_update_state().
VertexFuncs
const int VertexFuncs[3][NUM_TYPES] static
Referenced by _ae_update_state().