Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
arbprogram.c File Reference
ARB_vertex/fragment_program state management functions.
#include "main/glheader.h"
#include "main/context.h"
#include "main/hash.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/arbprogram.h"
#include "main/shaderapi.h"
#include "program/arbprogparse.h"
#include "program/program.h"
#include "program/prog_print.h"
Functions
void GLAPIENTRY _mesa_BindProgramARB (GLenum target, GLuint id)
Bind a program (make it current)
void GLAPIENTRY _mesa_DeleteProgramsARB (GLsizei n, const GLuint *ids)
Delete a list of programs.
void GLAPIENTRY _mesa_GenProgramsARB (GLsizei n, GLuint *ids)
Generate a list of new program identifiers.
GLboolean GLAPIENTRY _mesa_IsProgramARB (GLuint id)
Determine if id names a vertex or fragment program.
static GLboolean get_local_param_pointer (struct gl_context *ctx, const char *func, GLenum target, GLuint index, GLfloat **param)
static GLboolean get_env_param_pointer (struct gl_context *ctx, const char *func, GLenum target, GLuint index, GLfloat **param)
void GLAPIENTRY _mesa_ProgramStringARB (GLenum target, GLenum format, GLsizei len, const GLvoid *string)
void GLAPIENTRY _mesa_ProgramEnvParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameter4dvARB (GLenum target, GLuint index, const GLdouble *params)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameter4fvARB (GLenum target, GLuint index, const GLfloat *params)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat *params)
void GLAPIENTRY _mesa_GetProgramEnvParameterdvARB (GLenum target, GLuint index, GLdouble *params)
void GLAPIENTRY _mesa_GetProgramEnvParameterfvARB (GLenum target, GLuint index, GLfloat *params)
void GLAPIENTRY _mesa_ProgramLocalParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_ProgramLocalParameter4fvARB (GLenum target, GLuint index, const GLfloat *params)
void GLAPIENTRY _mesa_ProgramLocalParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat *params)
void GLAPIENTRY _mesa_ProgramLocalParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_ProgramLocalParameter4dvARB (GLenum target, GLuint index, const GLdouble *params)
void GLAPIENTRY _mesa_GetProgramLocalParameterfvARB (GLenum target, GLuint index, GLfloat *params)
void GLAPIENTRY _mesa_GetProgramLocalParameterdvARB (GLenum target, GLuint index, GLdouble *params)
void GLAPIENTRY _mesa_GetProgramivARB (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetProgramStringARB (GLenum target, GLenum pname, GLvoid *string)
Detailed Description
ARB_vertex/fragment_program state management functions.
Author
Brian Paul
Function Documentation
_mesa_BindProgramARB()
void GLAPIENTRY _mesa_BindProgramARB (GLenum target, GLuint id)
Bind a program (make it current)
Note
Called from the GL API dispatcher by both glBindProgramNV and glBindProgramARB.
All error checking is complete now
References _mesa_error(), _mesa_HashInsert(), _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program::Id, and gl_program::Target.
Referenced by _mesa_DeleteProgramsARB().
_mesa_DeleteProgramsARB()
void GLAPIENTRY _mesa_DeleteProgramsARB (GLsizei n, const GLuint * ids)
Delete a list of programs.
Note
Not compiled into display lists.
Called by both glDeleteProgramsNV and glDeleteProgramsARB.
References _mesa_BindProgramARB(), _mesa_error(), _mesa_HashRemove(), _mesa_problem(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_program::Target.
_mesa_GenProgramsARB()
void GLAPIENTRY _mesa_GenProgramsARB (GLsizei n, GLuint * ids)
Generate a list of new program identifiers.
Note
Not compiled into display lists.
Called by both glGenProgramsNV and glGenProgramsARB.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_GetProgramEnvParameterdvARB()
void GLAPIENTRY _mesa_GetProgramEnvParameterdvARB (GLenum target, GLuint index, GLdouble * params)
References COPY_4V, GET_CURRENT_CONTEXT, get_env_param_pointer(), and GLAPIENTRY.
_mesa_GetProgramEnvParameterfvARB()
void GLAPIENTRY _mesa_GetProgramEnvParameterfvARB (GLenum target, GLuint index, GLfloat * params)
References COPY_4V, GET_CURRENT_CONTEXT, get_env_param_pointer(), and GLAPIENTRY.
_mesa_GetProgramivARB()
void GLAPIENTRY _mesa_GetProgramivARB (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), gl_program::arb, gl_program::Format, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program::Id, gl_program_constants::MaxAddressRegs, gl_program_constants::MaxAluInstructions, gl_program_constants::MaxAttribs, gl_program_constants::MaxEnvParams, gl_program_constants::MaxInstructions, gl_program_constants::MaxLocalParams, gl_program_constants::MaxNativeAddressRegs, gl_program_constants::MaxNativeAluInstructions, gl_program_constants::MaxNativeAttribs, gl_program_constants::MaxNativeInstructions, gl_program_constants::MaxNativeParameters, gl_program_constants::MaxNativeTemps, gl_program_constants::MaxNativeTexIndirections, gl_program_constants::MaxNativeTexInstructions, gl_program_constants::MaxParameters, gl_program_constants::MaxTemps, gl_program_constants::MaxTexIndirections, gl_program_constants::MaxTexInstructions, and gl_program::String.
_mesa_GetProgramLocalParameterdvARB()
void GLAPIENTRY _mesa_GetProgramLocalParameterdvARB (GLenum target, GLuint index, GLdouble * params)
References COPY_4V, GET_CURRENT_CONTEXT, get_local_param_pointer(), and GLAPIENTRY.
_mesa_GetProgramLocalParameterfvARB()
void GLAPIENTRY _mesa_GetProgramLocalParameterfvARB (GLenum target, GLuint index, GLfloat * params)
References COPY_4V, GET_CURRENT_CONTEXT, get_local_param_pointer(), and GLAPIENTRY.
_mesa_GetProgramStringARB()
void GLAPIENTRY _mesa_GetProgramStringARB (GLenum target, GLenum pname, GLvoid * string)
References _mesa_error(), GET_CURRENT_CONTEXT, and gl_program::String.
_mesa_IsProgramARB()
GLboolean GLAPIENTRY _mesa_IsProgramARB (GLuint id)
Determine if id names a vertex or fragment program.
Note
Not compiled into display lists.
Called from both glIsProgramNV and glIsProgramARB.
Parameters
id is the program identifier
Returns
GL_TRUE if id is a program, else GL_FALSE.
References ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and GET_CURRENT_CONTEXT.
_mesa_ProgramEnvParameter4dARB()
void GLAPIENTRY _mesa_ProgramEnvParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _mesa_ProgramEnvParameter4fARB(), and GLAPIENTRY.
_mesa_ProgramEnvParameter4dvARB()
void GLAPIENTRY _mesa_ProgramEnvParameter4dvARB (GLenum target, GLuint index, const GLdouble * params)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _mesa_ProgramEnvParameter4fARB(), and GLAPIENTRY.
_mesa_ProgramEnvParameter4fARB()
void GLAPIENTRY _mesa_ProgramEnvParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_env_param_pointer(), and GLAPIENTRY.
Referenced by _mesa_ProgramEnvParameter4dARB(), and _mesa_ProgramEnvParameter4dvARB().
_mesa_ProgramEnvParameter4fvARB()
void GLAPIENTRY _mesa_ProgramEnvParameter4fvARB (GLenum target, GLuint index, const GLfloat * params)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_env_param_pointer(), and GLAPIENTRY.
_mesa_ProgramEnvParameters4fvEXT()
void GLAPIENTRY _mesa_ProgramEnvParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat * params)
References _mesa_error(), _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramLocalParameter4dARB()
void GLAPIENTRY _mesa_ProgramLocalParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References _mesa_ProgramLocalParameter4fARB(), and GLAPIENTRY.
_mesa_ProgramLocalParameter4dvARB()
void GLAPIENTRY _mesa_ProgramLocalParameter4dvARB (GLenum target, GLuint index, const GLdouble * params)
References _mesa_ProgramLocalParameter4fARB(), and GLAPIENTRY.
_mesa_ProgramLocalParameter4fARB()
void GLAPIENTRY _mesa_ProgramLocalParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_local_param_pointer(), GLAPIENTRY, and MAX_PROGRAM_LOCAL_PARAMS.
Referenced by _mesa_ProgramLocalParameter4dARB(), _mesa_ProgramLocalParameter4dvARB(), and _mesa_ProgramLocalParameter4fvARB().
_mesa_ProgramLocalParameter4fvARB()
void GLAPIENTRY _mesa_ProgramLocalParameter4fvARB (GLenum target, GLuint index, const GLfloat * params)
References _mesa_ProgramLocalParameter4fARB(), and GLAPIENTRY.
_mesa_ProgramLocalParameters4fvEXT()
void GLAPIENTRY _mesa_ProgramLocalParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat * params)
References _mesa_error(), _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_local_param_pointer(), GLAPIENTRY, and GLuint.
_mesa_ProgramStringARB()
void GLAPIENTRY _mesa_ProgramStringARB (GLenum target, GLenum format, GLsizei len, const GLvoid * string)
References _mesa_error(), _mesa_get_shader_capture_path(), _mesa_warning(), _NEW_PROGRAM, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLSL_DUMP, and gl_program::Id.
get_env_param_pointer()
static GLboolean get_env_param_pointer (struct gl_context * ctx, const char * func, GLenum target, GLuint index, GLfloat ** param) static
References _mesa_error(), gl_extensions::ARB_fragment_program, gl_extensions::ARB_vertex_program, gl_context::Const, gl_context::Extensions, gl_context::FragmentProgram, GLAPIENTRY, gl_program_constants::MaxEnvParams, gl_vertex_program_state::Parameters, gl_fragment_program_state::Parameters, gl_constants::Program, and gl_context::VertexProgram.
Referenced by _mesa_GetProgramEnvParameterdvARB(), _mesa_GetProgramEnvParameterfvARB(), _mesa_ProgramEnvParameter4fARB(), and _mesa_ProgramEnvParameter4fvARB().
get_local_param_pointer()
static GLboolean get_local_param_pointer (struct gl_context * ctx, const char * func, GLenum target, GLuint index, GLfloat ** param) static
References _mesa_error(), gl_program::arb, gl_extensions::ARB_fragment_program, gl_extensions::ARB_vertex_program, gl_context::Const, gl_vertex_program_state::Current, gl_fragment_program_state::Current, gl_context::Extensions, gl_context::FragmentProgram, GLuint, gl_program_constants::MaxLocalParams, gl_constants::Program, and gl_context::VertexProgram.
Referenced by _mesa_GetProgramLocalParameterdvARB(), _mesa_GetProgramLocalParameterfvARB(), _mesa_ProgramLocalParameter4fARB(), and _mesa_ProgramLocalParameters4fvEXT().