Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
arrayobj.c File Reference
Implementation of Vertex Array Objects (VAOs), from OpenGL 3.1+, the GL_ARB_vertex_array_object extension, or the older GL_APPLE_vertex_array_object extension.
#include "glheader.h"
#include "hash.h"
#include "image.h"
#include "imports.h"
#include "context.h"
#include "bufferobj.h"
#include "arrayobj.h"
#include "macros.h"
#include "mtypes.h"
#include "varray.h"
#include "main/dispatch.h"
#include "util/bitscan.h"
Functions
struct gl_vertex_array_object * _mesa_lookup_vao (struct gl_context *ctx, GLuint id)
Look up the array object for the given ID.
struct gl_vertex_array_object * _mesa_lookup_vao_err (struct gl_context *ctx, GLuint id, const char *caller)
Looks up the array object for the given ID.
static void unbind_array_object_vbos (struct gl_context *ctx, struct gl_vertex_array_object *obj)
For all the vertex binding points in the array object, unbind any pointers to any buffer objects (VBOs).
struct gl_vertex_array_object * _mesa_new_vao (struct gl_context *ctx, GLuint name)
Allocate and initialize a new vertex array object.
void _mesa_delete_vao (struct gl_context *ctx, struct gl_vertex_array_object *obj)
Delete an array object.
void _mesa_reference_vao_ (struct gl_context *ctx, struct gl_vertex_array_object **ptr, struct gl_vertex_array_object *vao)
Set ptr to vao w/ reference counting.
static void init_array (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint index, GLint size, GLint type)
Initialize attribtes of a vertex array within a vertex array object.
void _mesa_initialize_vao (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint name)
Initialize a gl_vertex_array_object's arrays.
static void save_array_object (struct gl_context *ctx, struct gl_vertex_array_object *vao)
Add the given array object to the array object pool.
static void remove_array_object (struct gl_context *ctx, struct gl_vertex_array_object *vao)
Remove the given array object from the array object pool.
void _mesa_update_vao_client_arrays (struct gl_context *ctx, struct gl_vertex_array_object *vao)
Updates the derived gl_vertex_arrays when a gl_vertex_attrib_array or a gl_vertex_buffer_binding has changed.
bool _mesa_all_varyings_in_vbos (const struct gl_vertex_array_object *vao)
bool _mesa_all_buffers_are_unmapped (const struct gl_vertex_array_object *vao)
static void bind_vertex_array (struct gl_context *ctx, GLuint id, GLboolean genRequired)
Helper for _mesa_BindVertexArray() and _mesa_BindVertexArrayAPPLE().
void GLAPIENTRY _mesa_BindVertexArray (GLuint id)
ARB version of glBindVertexArray() This function behaves differently from glBindVertexArrayAPPLE() in that this function requires all ids to have been previously generated by glGenVertexArrays[APPLE]().
void GLAPIENTRY _mesa_BindVertexArrayAPPLE (GLuint id)
Bind a new array.
void GLAPIENTRY _mesa_DeleteVertexArrays (GLsizei n, const GLuint *ids)
Delete a set of array objects.
static void gen_vertex_arrays (struct gl_context *ctx, GLsizei n, GLuint *arrays, bool create, const char *func)
Generate a set of unique array object IDs and store them in arrays.
void GLAPIENTRY _mesa_GenVertexArrays (GLsizei n, GLuint *arrays)
ARB version of glGenVertexArrays() All arrays will be required to live in VBOs.
void GLAPIENTRY _mesa_GenVertexArraysAPPLE (GLsizei n, GLuint *arrays)
APPLE version of glGenVertexArraysAPPLE() Arrays may live in VBOs or ordinary memory.
void GLAPIENTRY _mesa_CreateVertexArrays (GLsizei n, GLuint *arrays)
ARB_direct_state_access Generates ID's and creates the array objects.
GLboolean GLAPIENTRY _mesa_IsVertexArray (GLuint id)
Determine if ID is the name of an array object.
void GLAPIENTRY _mesa_VertexArrayElementBuffer (GLuint vaobj, GLuint buffer)
Sets the element array buffer binding of a vertex array object.
void GLAPIENTRY _mesa_GetVertexArrayiv (GLuint vaobj, GLenum pname, GLint *param)
Detailed Description
Implementation of Vertex Array Objects (VAOs), from OpenGL 3.1+, the GL_ARB_vertex_array_object extension, or the older GL_APPLE_vertex_array_object extension.
Todo:
The code in this file borrows a lot from bufferobj.c. There's a certain amount of cruft left over from that origin that may be unnecessary.
Author
Ian Romanick idr@u.nosp@m.s.ib.nosp@m.m.com
Brian Paul
Function Documentation
_mesa_all_buffers_are_unmapped()
bool _mesa_all_buffers_are_unmapped (const struct gl_vertex_array_object * vao)
References gl_vertex_buffer_binding::_BoundArrays, gl_vertex_array_object::_Enabled, _mesa_check_disallowed_mapping(), _mesa_is_bufferobj(), gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_array_attributes::Enabled, gl_vertex_array_object::VertexAttrib, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by _mesa_reference_vao(), and check_valid_to_render().
_mesa_all_varyings_in_vbos()
bool _mesa_all_varyings_in_vbos (const struct gl_vertex_array_object * vao)
References gl_vertex_buffer_binding::_BoundArrays, gl_vertex_array_object::_Enabled, _mesa_is_bufferobj(), gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_array_attributes::Enabled, gl_vertex_buffer_binding::Stride, gl_vertex_array_object::VertexAttrib, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by _mesa_reference_vao().
_mesa_BindVertexArray()
void GLAPIENTRY _mesa_BindVertexArray (GLuint id)
ARB version of glBindVertexArray() This function behaves differently from glBindVertexArrayAPPLE() in that this function requires all ids to have been previously generated by glGenVertexArrays[APPLE]().
References bind_vertex_array(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_DeleteVertexArrays(), and _mesa_reference_vao().
_mesa_BindVertexArrayAPPLE()
void GLAPIENTRY _mesa_BindVertexArrayAPPLE (GLuint id)
Bind a new array.
Todo:
The binding could be done more efficiently by comparing the non-NULL pointers in the old and new objects. The only arrays that are "dirty" are the ones that are non-NULL in either object.
References bind_vertex_array(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_vao(), and restore_array_attrib().
_mesa_CreateVertexArrays()
void GLAPIENTRY _mesa_CreateVertexArrays (GLsizei n, GLuint * arrays)
ARB_direct_state_access Generates ID's and creates the array objects.
References gen_vertex_arrays(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_vao().
_mesa_delete_vao()
void _mesa_delete_vao (struct gl_context * ctx, struct gl_vertex_array_object * obj)
Delete an array object.
References _mesa_reference_buffer_object(), gl_vertex_array_object::IndexBufferObj, gl_vertex_array_object::Label, gl_vertex_array_object::Mutex, and unbind_array_object_vbos().
Referenced by _mesa_reference_vao_(), delete_arrayobj_cb(), and free_array_attrib_data().
_mesa_DeleteVertexArrays()
void GLAPIENTRY _mesa_DeleteVertexArrays (GLsizei n, const GLuint * ids)
Delete a set of array objects.
Parameters
n Number of array objects to delete.
ids Array of n array object IDs.
References _mesa_BindVertexArray(), _mesa_error(), _mesa_lookup_vao(), _mesa_reference_vao(), GET_CURRENT_CONTEXT, gl_vertex_array_object::Name, and remove_array_object().
Referenced by _mesa_reference_vao().
_mesa_GenVertexArrays()
void GLAPIENTRY _mesa_GenVertexArrays (GLsizei n, GLuint * arrays)
ARB version of glGenVertexArrays() All arrays will be required to live in VBOs.
References gen_vertex_arrays(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_vao().
_mesa_GenVertexArraysAPPLE()
void GLAPIENTRY _mesa_GenVertexArraysAPPLE (GLsizei n, GLuint * arrays)
APPLE version of glGenVertexArraysAPPLE() Arrays may live in VBOs or ordinary memory.
References gen_vertex_arrays(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_vao().
_mesa_GetVertexArrayiv()
void GLAPIENTRY _mesa_GetVertexArrayiv (GLuint vaobj, GLenum pname, GLint * param)
References _mesa_error(), _mesa_lookup_vao_err(), ASSERT_OUTSIDE_BEGIN_END, GET_CURRENT_CONTEXT, gl_vertex_array_object::IndexBufferObj, and gl_buffer_object::Name.
Referenced by _mesa_reference_vao().
_mesa_initialize_vao()
void _mesa_initialize_vao (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint name)
Initialize a gl_vertex_array_object's arrays.
References _mesa_reference_buffer_object(), GLuint, gl_vertex_array_object::IndexBufferObj, init_array(), gl_vertex_array_object::Mutex, gl_vertex_array_object::Name, gl_shared_state::NullBufferObj, gl_vertex_array_object::RefCount, gl_context::Shared, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_new_vao(), _mesa_reference_vao(), and init_array_attrib_data().
_mesa_IsVertexArray()
GLboolean GLAPIENTRY _mesa_IsVertexArray (GLuint id)
Determine if ID is the name of an array object.
Parameters
id ID of the potential array object.
Returns
GL_TRUE if id is the name of a array object, GL_FALSE otherwise.
References _mesa_lookup_vao(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_vertex_array_object::EverBound, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_vao(), and restore_array_attrib().
_mesa_lookup_vao()
struct gl_vertex_array_object* _mesa_lookup_vao (struct gl_context * ctx, GLuint id)
Look up the array object for the given ID.
Returns
Either a pointer to the array object with the specified ID or NULL for a non-existent ID. The spec defines ID 0 as being technically non-existent.
References _mesa_HashLookup(), gl_context::Array, and gl_array_attrib::Objects.
Referenced by _mesa_DeleteVertexArrays(), _mesa_IsVertexArray(), bind_vertex_array(), and get_label_pointer().
_mesa_lookup_vao_err()
struct gl_vertex_array_object* _mesa_lookup_vao_err (struct gl_context * ctx, GLuint id, const char * caller)
Looks up the array object for the given ID.
Unlike _mesa_lookup_vao, this function generates a GL_INVALID_OPERATION error if the array object does not exist. It also returns the default array object when ctx is a compatibility profile context and id is zero.
References _mesa_error(), _mesa_HashLookup(), _mesa_reference_vao(), gl_context::API, API_OPENGL_CORE, gl_context::Array, gl_array_attrib::DefaultVAO, gl_vertex_array_object::EverBound, gl_array_attrib::LastLookedUpVAO, gl_vertex_array_object::Name, and gl_array_attrib::Objects.
Referenced by _mesa_DisableVertexArrayAttrib(), _mesa_EnableVertexArrayAttrib(), _mesa_GetVertexArrayIndexed64iv(), _mesa_GetVertexArrayIndexediv(), _mesa_GetVertexArrayiv(), _mesa_VertexArrayAttribBinding(), _mesa_VertexArrayBindingDivisor(), _mesa_VertexArrayElementBuffer(), _mesa_VertexArrayVertexBuffer(), _mesa_VertexArrayVertexBuffers(), and vertex_array_attrib_format().
_mesa_new_vao()
struct gl_vertex_array_object* _mesa_new_vao (struct gl_context * ctx, GLuint name)
Allocate and initialize a new vertex array object.
References _mesa_initialize_vao(), and CALLOC_STRUCT.
Referenced by _mesa_init_varray(), bind_vertex_array(), and gen_vertex_arrays().
_mesa_reference_vao_()
void _mesa_reference_vao_ (struct gl_context * ctx, struct gl_vertex_array_object ** ptr, struct gl_vertex_array_object * vao)
Set ptr to vao w/ reference counting.
Note: this should only be called from the _mesa_reference_vao() inline function.
References _mesa_delete_vao(), _mesa_problem(), gl_vertex_array_object::Mutex, and gl_vertex_array_object::RefCount.
Referenced by _mesa_reference_vao().
_mesa_update_vao_client_arrays()
void _mesa_update_vao_client_arrays (struct gl_context * ctx, struct gl_vertex_array_object * vao)
Updates the derived gl_vertex_arrays when a gl_vertex_attrib_array or a gl_vertex_buffer_binding has changed.
References _mesa_update_client_array(), gl_vertex_array_object::_VertexAttrib, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_array_object::NewArrays, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_reference_vao(), and _mesa_update_state_locked().
_mesa_VertexArrayElementBuffer()
void GLAPIENTRY _mesa_VertexArrayElementBuffer (GLuint vaobj, GLuint buffer)
Sets the element array buffer binding of a vertex array object.
This is the ARB_direct_state_access equivalent of glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, buffer).
References _mesa_lookup_bufferobj_err(), _mesa_lookup_vao_err(), _mesa_reference_buffer_object(), ASSERT_OUTSIDE_BEGIN_END, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_vertex_array_object::IndexBufferObj.
Referenced by _mesa_reference_vao().
bind_vertex_array()
static void bind_vertex_array (struct gl_context * ctx, GLuint id, GLboolean genRequired) static
Helper for _mesa_BindVertexArray() and _mesa_BindVertexArrayAPPLE().
Parameters
genRequired specifies behavour when id was not generated with glGenVertexArrays().
References gl_array_attrib::_DrawArrays, _mesa_error(), _mesa_lookup_vao(), _mesa_new_vao(), _mesa_reference_vao(), _NEW_ARRAY, gl_vertex_array_object::ARBsemantics, gl_context::Array, gl_array_attrib::DefaultVAO, DRAW_ARRAYS, DRAW_NONE, gl_array_attrib::DrawMethod, gl_vertex_array_object::EverBound, GLAPIENTRY, gl_vertex_array_object::Name, gl_context::NewState, save_array_object(), and gl_array_attrib::VAO.
Referenced by _mesa_BindVertexArray(), and _mesa_BindVertexArrayAPPLE().
gen_vertex_arrays()
static void gen_vertex_arrays (struct gl_context * ctx, GLsizei n, GLuint * arrays, bool create, const char * func) static
Generate a set of unique array object IDs and store them in arrays.
Helper for _mesa_GenVertexArrays[APPLE]() and _mesa_CreateVertexArrays() below.
Parameters
n Number of IDs to generate.
arrays Array of n locations to store the IDs.
create Indicates that the objects should also be created.
func The name of the GL entry point.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_new_vao(), gl_context::Array, gl_vertex_array_object::EverBound, GLAPIENTRY, GLuint, gl_array_attrib::Objects, and save_array_object().
Referenced by _mesa_CreateVertexArrays(), _mesa_GenVertexArrays(), and _mesa_GenVertexArraysAPPLE().
init_array()
static void init_array (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint index, GLint size, GLint type) static
Initialize attribtes of a vertex array within a vertex array object.
Parameters
vao the container vertex array object
index which array in the VAO to initialize
size number of components (1, 2, 3 or 4) per attribute
type datatype of the attribute (GL_FLOAT, GL_INT, etc).
References gl_vertex_buffer_binding::_BoundArrays, gl_array_attributes::_ElementSize, _mesa_reference_buffer_object(), _mesa_sizeof_type(), BITFIELD64_BIT, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_array_attributes::Doubles, gl_array_attributes::Enabled, gl_array_attributes::Format, gl_array_attributes::Integer, gl_array_attributes::Normalized, gl_shared_state::NullBufferObj, gl_vertex_buffer_binding::Offset, gl_array_attributes::Ptr, gl_array_attributes::RelativeOffset, gl_context::Shared, gl_array_attributes::Size, gl_array_attributes::Stride, gl_vertex_buffer_binding::Stride, gl_array_attributes::Type, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_initialize_vao().
remove_array_object()
static void remove_array_object (struct gl_context * ctx, struct gl_vertex_array_object * vao) static
Remove the given array object from the array object pool.
Do not deallocate the array object though.
References _mesa_HashRemove(), gl_context::Array, gl_vertex_array_object::Name, and gl_array_attrib::Objects.
Referenced by _mesa_DeleteVertexArrays().
save_array_object()
static void save_array_object (struct gl_context * ctx, struct gl_vertex_array_object * vao) static
Add the given array object to the array object pool.
References _mesa_HashInsert(), gl_context::Array, gl_vertex_array_object::Name, and gl_array_attrib::Objects.
Referenced by bind_vertex_array(), and gen_vertex_arrays().
unbind_array_object_vbos()
static void unbind_array_object_vbos (struct gl_context * ctx, struct gl_vertex_array_object * obj) static
For all the vertex binding points in the array object, unbind any pointers to any buffer objects (VBOs).
This is done just prior to array object destruction.
References _mesa_reference_buffer_object(), gl_vertex_array_object::_VertexAttrib, gl_vertex_array_object::BufferBinding, gl_vertex_array::BufferObj, gl_vertex_buffer_binding::BufferObj, and GLuint.
Referenced by _mesa_delete_vao().