Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
atifragshader.h File Reference
#include "glheader.h"
Data Structures
struct ati_fs_opcode_st
struct atifragshader_src_register
struct atifragshader_dst_register
struct atifs_instruction
struct atifs_setupinst
Macros
#define MAX_NUM_INSTRUCTIONS_PER_PASS_ATI 8
#define MAX_NUM_PASSES_ATI 2
#define MAX_NUM_FRAGMENT_REGISTERS_ATI 6
#define MAX_NUM_FRAGMENT_CONSTANTS_ATI 8
#define ATI_FRAGMENT_SHADER_COLOR_OP 0
#define ATI_FRAGMENT_SHADER_ALPHA_OP 1
#define ATI_FRAGMENT_SHADER_PASS_OP 2
#define ATI_FRAGMENT_SHADER_SAMPLE_OP 3
Functions
struct ati_fragment_shader * _mesa_new_ati_fragment_shader (struct gl_context *ctx, GLuint id)
Allocate and initialize a new ATI fragment shader object.
void _mesa_delete_ati_fragment_shader (struct gl_context *ctx, struct ati_fragment_shader *s)
Delete the given ati fragment shader.
GLuint GLAPIENTRY _mesa_GenFragmentShadersATI (GLuint range)
void GLAPIENTRY _mesa_BindFragmentShaderATI (GLuint id)
void GLAPIENTRY _mesa_DeleteFragmentShaderATI (GLuint id)
void GLAPIENTRY _mesa_BeginFragmentShaderATI (void)
void GLAPIENTRY _mesa_EndFragmentShaderATI (void)
void GLAPIENTRY _mesa_PassTexCoordATI (GLuint dst, GLuint coord, GLenum swizzle)
void GLAPIENTRY _mesa_SampleMapATI (GLuint dst, GLuint interp, GLenum swizzle)
void GLAPIENTRY _mesa_ColorFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
void GLAPIENTRY _mesa_ColorFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
void GLAPIENTRY _mesa_ColorFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
void GLAPIENTRY _mesa_AlphaFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
void GLAPIENTRY _mesa_AlphaFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
void GLAPIENTRY _mesa_AlphaFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
void GLAPIENTRY _mesa_SetFragmentShaderConstantATI (GLuint dst, const GLfloat *value)
Macro Definition Documentation
ATI_FRAGMENT_SHADER_ALPHA_OP
#define ATI_FRAGMENT_SHADER_ALPHA_OP 1
Referenced by _mesa_AlphaFragmentOp1ATI(), _mesa_AlphaFragmentOp2ATI(), and _mesa_AlphaFragmentOp3ATI().
ATI_FRAGMENT_SHADER_COLOR_OP
#define ATI_FRAGMENT_SHADER_COLOR_OP 0
Referenced by _mesa_ColorFragmentOp1ATI(), _mesa_ColorFragmentOp2ATI(), and _mesa_ColorFragmentOp3ATI().
ATI_FRAGMENT_SHADER_PASS_OP
#define ATI_FRAGMENT_SHADER_PASS_OP 2
Referenced by _mesa_PassTexCoordATI().
ATI_FRAGMENT_SHADER_SAMPLE_OP
#define ATI_FRAGMENT_SHADER_SAMPLE_OP 3
Referenced by _mesa_SampleMapATI().
MAX_NUM_FRAGMENT_CONSTANTS_ATI
#define MAX_NUM_FRAGMENT_CONSTANTS_ATI 8
MAX_NUM_FRAGMENT_REGISTERS_ATI
#define MAX_NUM_FRAGMENT_REGISTERS_ATI 6
Referenced by _mesa_BeginFragmentShaderATI(), and _mesa_EndFragmentShaderATI().
MAX_NUM_INSTRUCTIONS_PER_PASS_ATI
#define MAX_NUM_INSTRUCTIONS_PER_PASS_ATI 8
Referenced by _mesa_BeginFragmentShaderATI().
MAX_NUM_PASSES_ATI
#define MAX_NUM_PASSES_ATI 2
Referenced by _mesa_BeginFragmentShaderATI(), _mesa_delete_ati_fragment_shader(), and _mesa_EndFragmentShaderATI().
Function Documentation
_mesa_AlphaFragmentOp1ATI()
void GLAPIENTRY _mesa_AlphaFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_ALPHA_OP, and GLAPIENTRY.
_mesa_AlphaFragmentOp2ATI()
void GLAPIENTRY _mesa_AlphaFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_ALPHA_OP, and GLAPIENTRY.
_mesa_AlphaFragmentOp3ATI()
void GLAPIENTRY _mesa_AlphaFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_ALPHA_OP, and GLAPIENTRY.
_mesa_BeginFragmentShaderATI()
void GLAPIENTRY _mesa_BeginFragmentShaderATI (void)
References _mesa_debug(), _mesa_error(), _NEW_PROGRAM, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_NUM_FRAGMENT_REGISTERS_ATI, MAX_NUM_INSTRUCTIONS_PER_PASS_ATI, and MAX_NUM_PASSES_ATI.
_mesa_BindFragmentShaderATI()
void GLAPIENTRY _mesa_BindFragmentShaderATI (GLuint id)
References _mesa_error(), _mesa_HashInsert(), _mesa_HashLookup(), _mesa_HashRemove(), _mesa_new_ati_fragment_shader(), _NEW_PROGRAM, DummyShader, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, ati_fragment_shader::Id, and ati_fragment_shader::RefCount.
Referenced by _mesa_DeleteFragmentShaderATI().
_mesa_ColorFragmentOp1ATI()
void GLAPIENTRY _mesa_ColorFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_COLOR_OP, and GLAPIENTRY.
_mesa_ColorFragmentOp2ATI()
void GLAPIENTRY _mesa_ColorFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_COLOR_OP, and GLAPIENTRY.
_mesa_ColorFragmentOp3ATI()
void GLAPIENTRY _mesa_ColorFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_COLOR_OP, and GLAPIENTRY.
_mesa_delete_ati_fragment_shader()
void _mesa_delete_ati_fragment_shader (struct gl_context * ctx, struct ati_fragment_shader * s)
Delete the given ati fragment shader.
References GLuint, ati_fragment_shader::Instructions, MAX_NUM_PASSES_ATI, ati_fragment_shader::Program, and ati_fragment_shader::SetupInst.
Referenced by _mesa_DeleteFragmentShaderATI(), delete_fragshader_cb(), and free_shared_state().
_mesa_DeleteFragmentShaderATI()
void GLAPIENTRY _mesa_DeleteFragmentShaderATI (GLuint id)
References _mesa_BindFragmentShaderATI(), _mesa_delete_ati_fragment_shader(), _mesa_error(), _mesa_HashLookup(), _mesa_HashRemove(), _NEW_PROGRAM, DummyShader, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and ati_fragment_shader::RefCount.
_mesa_EndFragmentShaderATI()
void GLAPIENTRY _mesa_EndFragmentShaderATI (void)
References _mesa_enum_to_string(), _mesa_error(), atifs_instruction::ArgCount, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, ati_fragment_shader::Instructions, ati_fragment_shader::interpinp1, match_pair_inst(), MAX_NUM_FRAGMENT_REGISTERS_ATI, MAX_NUM_PASSES_ATI, ati_fragment_shader::numArithInstr, atifs_instruction::Opcode, atifs_setupinst::Opcode, ati_fragment_shader::Program, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_setupinst::swizzle, and swizzle().
_mesa_GenFragmentShadersATI()
GLuint GLAPIENTRY _mesa_GenFragmentShadersATI (GLuint range)
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), DummyShader, GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_new_ati_fragment_shader()
struct ati_fragment_shader* _mesa_new_ati_fragment_shader (struct gl_context * ctx, GLuint id)
Allocate and initialize a new ATI fragment shader object.
References CALLOC_STRUCT, ati_fragment_shader::Id, ati_fragment_shader::RefCount, and void.
Referenced by _mesa_alloc_shared_state(), and _mesa_BindFragmentShaderATI().
_mesa_PassTexCoordATI()
void GLAPIENTRY _mesa_PassTexCoordATI (GLuint dst, GLuint coord, GLenum swizzle)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), ATI_FRAGMENT_SHADER_PASS_OP, ati_fragment_shader::cur_pass, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, match_pair_inst(), new_tex_inst(), atifs_setupinst::Opcode, ati_fragment_shader::regsAssigned, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_setupinst::swizzle, swizzle(), and ati_fragment_shader::swizzlerq.
_mesa_SampleMapATI()
void GLAPIENTRY _mesa_SampleMapATI (GLuint dst, GLuint interp, GLenum swizzle)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), ATI_FRAGMENT_SHADER_SAMPLE_OP, ati_fragment_shader::cur_pass, GET_CURRENT_CONTEXT, GLuint, match_pair_inst(), new_tex_inst(), atifs_setupinst::Opcode, ati_fragment_shader::regsAssigned, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_setupinst::swizzle, swizzle(), and ati_fragment_shader::swizzlerq.
_mesa_SetFragmentShaderConstantATI()
void GLAPIENTRY _mesa_SetFragmentShaderConstantATI (GLuint dst, const GLfloat * value)
References _mesa_error(), _NEW_PROGRAM, ati_fragment_shader::Constants, COPY_4V, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, and ati_fragment_shader::LocalConstDef.