Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
atifragshader.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/hash.h"
#include "main/imports.h"
#include "main/macros.h"
#include "main/enums.h"
#include "main/mtypes.h"
#include "main/dispatch.h"
#include "main/atifragshader.h"
#include "program/program.h"
Macros
#define MESA_DEBUG_ATI_FS 0
Functions
struct ati_fragment_shader * _mesa_new_ati_fragment_shader (struct gl_context *ctx, GLuint id)
Allocate and initialize a new ATI fragment shader object.
void _mesa_delete_ati_fragment_shader (struct gl_context *ctx, struct ati_fragment_shader *s)
Delete the given ati fragment shader.
static void new_arith_inst (struct ati_fragment_shader *prog)
static void new_tex_inst (struct ati_fragment_shader *prog)
static void match_pair_inst (struct ati_fragment_shader *curProg, GLuint optype)
static int check_arith_arg (struct ati_fragment_shader *curProg, GLuint optype, GLuint arg, GLuint argRep)
GLuint GLAPIENTRY _mesa_GenFragmentShadersATI (GLuint range)
void GLAPIENTRY _mesa_BindFragmentShaderATI (GLuint id)
void GLAPIENTRY _mesa_DeleteFragmentShaderATI (GLuint id)
void GLAPIENTRY _mesa_BeginFragmentShaderATI (void)
void GLAPIENTRY _mesa_EndFragmentShaderATI (void)
void GLAPIENTRY _mesa_PassTexCoordATI (GLuint dst, GLuint coord, GLenum swizzle)
void GLAPIENTRY _mesa_SampleMapATI (GLuint dst, GLuint interp, GLenum swizzle)
static void _mesa_FragmentOpXATI (GLint optype, GLuint arg_count, GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
void GLAPIENTRY _mesa_ColorFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
void GLAPIENTRY _mesa_ColorFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
void GLAPIENTRY _mesa_ColorFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
void GLAPIENTRY _mesa_AlphaFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
void GLAPIENTRY _mesa_AlphaFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
void GLAPIENTRY _mesa_AlphaFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
void GLAPIENTRY _mesa_SetFragmentShaderConstantATI (GLuint dst, const GLfloat *value)
Variables
static struct ati_fragment_shader DummyShader
Detailed Description
Author
David Airlie Copyright (C) 2004 David Airlie All Rights Reserved.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL DAVID AIRLIE BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Macro Definition Documentation
MESA_DEBUG_ATI_FS
#define MESA_DEBUG_ATI_FS 0
Function Documentation
_mesa_AlphaFragmentOp1ATI()
void GLAPIENTRY _mesa_AlphaFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_ALPHA_OP, and GLAPIENTRY.
_mesa_AlphaFragmentOp2ATI()
void GLAPIENTRY _mesa_AlphaFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_ALPHA_OP, and GLAPIENTRY.
_mesa_AlphaFragmentOp3ATI()
void GLAPIENTRY _mesa_AlphaFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_ALPHA_OP, and GLAPIENTRY.
_mesa_BeginFragmentShaderATI()
void GLAPIENTRY _mesa_BeginFragmentShaderATI (void)
References _mesa_debug(), _mesa_error(), _NEW_PROGRAM, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_NUM_FRAGMENT_REGISTERS_ATI, MAX_NUM_INSTRUCTIONS_PER_PASS_ATI, and MAX_NUM_PASSES_ATI.
_mesa_BindFragmentShaderATI()
void GLAPIENTRY _mesa_BindFragmentShaderATI (GLuint id)
References _mesa_error(), _mesa_HashInsert(), _mesa_HashLookup(), _mesa_HashRemove(), _mesa_new_ati_fragment_shader(), _NEW_PROGRAM, DummyShader, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, ati_fragment_shader::Id, and ati_fragment_shader::RefCount.
Referenced by _mesa_DeleteFragmentShaderATI().
_mesa_ColorFragmentOp1ATI()
void GLAPIENTRY _mesa_ColorFragmentOp1ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_COLOR_OP, and GLAPIENTRY.
_mesa_ColorFragmentOp2ATI()
void GLAPIENTRY _mesa_ColorFragmentOp2ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_COLOR_OP, and GLAPIENTRY.
_mesa_ColorFragmentOp3ATI()
void GLAPIENTRY _mesa_ColorFragmentOp3ATI (GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod)
References _mesa_FragmentOpXATI(), ATI_FRAGMENT_SHADER_COLOR_OP, and GLAPIENTRY.
_mesa_delete_ati_fragment_shader()
void _mesa_delete_ati_fragment_shader (struct gl_context * ctx, struct ati_fragment_shader * s)
Delete the given ati fragment shader.
References GLuint, ati_fragment_shader::Instructions, MAX_NUM_PASSES_ATI, ati_fragment_shader::Program, and ati_fragment_shader::SetupInst.
Referenced by _mesa_DeleteFragmentShaderATI(), delete_fragshader_cb(), and free_shared_state().
_mesa_DeleteFragmentShaderATI()
void GLAPIENTRY _mesa_DeleteFragmentShaderATI (GLuint id)
References _mesa_BindFragmentShaderATI(), _mesa_delete_ati_fragment_shader(), _mesa_error(), _mesa_HashLookup(), _mesa_HashRemove(), _NEW_PROGRAM, DummyShader, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and ati_fragment_shader::RefCount.
_mesa_EndFragmentShaderATI()
void GLAPIENTRY _mesa_EndFragmentShaderATI (void)
References _mesa_enum_to_string(), _mesa_error(), atifs_instruction::ArgCount, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, ati_fragment_shader::Instructions, ati_fragment_shader::interpinp1, match_pair_inst(), MAX_NUM_FRAGMENT_REGISTERS_ATI, MAX_NUM_PASSES_ATI, ati_fragment_shader::numArithInstr, atifs_instruction::Opcode, atifs_setupinst::Opcode, ati_fragment_shader::Program, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_setupinst::swizzle, and swizzle().
_mesa_FragmentOpXATI()
static void _mesa_FragmentOpXATI (GLint optype, GLuint arg_count, GLenum op, GLuint dst, GLuint dstMask, GLuint dstMod, GLuint arg1, GLuint arg1Rep, GLuint arg1Mod, GLuint arg2, GLuint arg2Rep, GLuint arg2Mod, GLuint arg3, GLuint arg3Rep, GLuint arg3Mod) static
References _mesa_error(), atifs_instruction::ArgCount, atifragshader_src_register::argMod, atifragshader_src_register::argRep, check_arith_arg(), ati_fragment_shader::cur_pass, atifragshader_dst_register::dstMask, atifragshader_dst_register::dstMod, atifs_instruction::DstReg, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, atifragshader_src_register::Index, atifragshader_dst_register::Index, ati_fragment_shader::Instructions, ati_fragment_shader::last_optype, match_pair_inst(), new_arith_inst(), ati_fragment_shader::numArithInstr, atifs_instruction::Opcode, and atifs_instruction::SrcReg.
Referenced by _mesa_AlphaFragmentOp1ATI(), _mesa_AlphaFragmentOp2ATI(), _mesa_AlphaFragmentOp3ATI(), _mesa_ColorFragmentOp1ATI(), _mesa_ColorFragmentOp2ATI(), and _mesa_ColorFragmentOp3ATI().
_mesa_GenFragmentShadersATI()
GLuint GLAPIENTRY _mesa_GenFragmentShadersATI (GLuint range)
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), DummyShader, GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_new_ati_fragment_shader()
struct ati_fragment_shader* _mesa_new_ati_fragment_shader (struct gl_context * ctx, GLuint id)
Allocate and initialize a new ATI fragment shader object.
References CALLOC_STRUCT, ati_fragment_shader::Id, ati_fragment_shader::RefCount, and void.
Referenced by _mesa_alloc_shared_state(), and _mesa_BindFragmentShaderATI().
_mesa_PassTexCoordATI()
void GLAPIENTRY _mesa_PassTexCoordATI (GLuint dst, GLuint coord, GLenum swizzle)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), ATI_FRAGMENT_SHADER_PASS_OP, ati_fragment_shader::cur_pass, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, match_pair_inst(), new_tex_inst(), atifs_setupinst::Opcode, ati_fragment_shader::regsAssigned, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_setupinst::swizzle, swizzle(), and ati_fragment_shader::swizzlerq.
_mesa_SampleMapATI()
void GLAPIENTRY _mesa_SampleMapATI (GLuint dst, GLuint interp, GLenum swizzle)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), ATI_FRAGMENT_SHADER_SAMPLE_OP, ati_fragment_shader::cur_pass, GET_CURRENT_CONTEXT, GLuint, match_pair_inst(), new_tex_inst(), atifs_setupinst::Opcode, ati_fragment_shader::regsAssigned, ati_fragment_shader::SetupInst, atifs_setupinst::src, atifs_setupinst::swizzle, swizzle(), and ati_fragment_shader::swizzlerq.
_mesa_SetFragmentShaderConstantATI()
void GLAPIENTRY _mesa_SetFragmentShaderConstantATI (GLuint dst, const GLfloat * value)
References _mesa_error(), _NEW_PROGRAM, ati_fragment_shader::Constants, COPY_4V, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, and ati_fragment_shader::LocalConstDef.
check_arith_arg()
static int check_arith_arg (struct ati_fragment_shader * curProg, GLuint optype, GLuint arg, GLuint argRep) static
References _mesa_error(), ati_fragment_shader::cur_pass, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, and ati_fragment_shader::interpinp1.
Referenced by _mesa_FragmentOpXATI().
match_pair_inst()
static void match_pair_inst (struct ati_fragment_shader * curProg, GLuint optype) static
References _mesa_enum_to_string(), GLuint, and ati_fragment_shader::last_optype.
Referenced by _mesa_EndFragmentShaderATI(), _mesa_FragmentOpXATI(), _mesa_PassTexCoordATI(), and _mesa_SampleMapATI().
new_arith_inst()
static void new_arith_inst (struct ati_fragment_shader * prog) static
References ati_fragment_shader::cur_pass, and ati_fragment_shader::numArithInstr.
Referenced by _mesa_FragmentOpXATI().
new_tex_inst()
static void new_tex_inst (struct ati_fragment_shader * prog) static
Referenced by _mesa_PassTexCoordATI(), and _mesa_SampleMapATI().
Variable Documentation
DummyShader
struct ati_fragment_shader DummyShader static
Referenced by _mesa_BindFragmentShaderATI(), _mesa_DeleteFragmentShaderATI(), and _mesa_GenFragmentShadersATI().