Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
attrib.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_PushAttrib (GLbitfield mask)
void GLAPIENTRY _mesa_PopAttrib (void)
void GLAPIENTRY _mesa_PushClientAttrib (GLbitfield mask)
void GLAPIENTRY _mesa_PopClientAttrib (void)
void _mesa_init_attrib (struct gl_context *ctx)
void _mesa_free_attrib_data (struct gl_context *ctx)
Free any attribute state data that might be attached to the context.
Function Documentation
_mesa_free_attrib_data()
void _mesa_free_attrib_data (struct gl_context * ctx)
Free any attribute state data that might be attached to the context.
References _mesa_reference_shared_state(), _mesa_reference_texobj(), gl_context::AttribStack, gl_context::AttribStackDepth, gl_context::Const, gl_attrib_node::data, for(), GLuint, gl_attrib_node::kind, gl_constants::MaxTextureUnits, gl_attrib_node::next, NUM_TEXTURE_TARGETS, texture_state::SavedTexRef, and texture_state::SharedRef.
Referenced by _mesa_free_context_data().
_mesa_init_attrib()
void _mesa_init_attrib (struct gl_context * ctx)
References gl_context::AttribStackDepth, and gl_context::ClientAttribStackDepth.
Referenced by init_attrib_groups().
_mesa_PopAttrib()
void GLAPIENTRY _mesa_PopAttrib (void)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_ActiveStencilFaceEXT(), _mesa_AlphaFunc(), _mesa_BlendColor(), _mesa_BlendEquation(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_BlendFuncSeparateiARB(), _mesa_ClampColor(), _mesa_ClearAccum(), _mesa_ClearColor(), _mesa_ClearDepth(), _mesa_ClearIndex(), _mesa_ClearStencil(), _mesa_ClipControl(), _mesa_ColorMask(), _mesa_ColorMaski(), _mesa_ColorMaterial(), _mesa_CullFace(), _mesa_debug(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthMask(), _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_enum_to_string(), _mesa_error(), _mesa_Fogf(), _mesa_Fogfv(), _mesa_Fogi(), _mesa_FrontFace(), _mesa_Hint(), _mesa_IndexMask(), _mesa_light(), _mesa_LightModelf(), _mesa_LightModelfv(), _mesa_LineStipple(), _mesa_LineWidth(), _mesa_LogicOp(), _mesa_MatrixMode(), _mesa_PointParameterf(), _mesa_PointParameterfv(), _mesa_PointParameteri(), _mesa_PointSize(), _mesa_polygon_offset_clamp(), _mesa_PolygonMode(), _mesa_problem(), _mesa_ReadBuffer(), _mesa_SampleCoverage(), _mesa_set_depth_range(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_set_scissor(), _mesa_set_viewport(), _mesa_ShadeModel(), _mesa_StencilFuncSeparate(), _mesa_StencilMaskSeparate(), _mesa_StencilOpSeparate(), _mesa_TexEnvi(), _mesa_WindowRectanglesEXT(), _NEW_ALL, _NEW_EVAL, _NEW_PIXEL, _NEW_POLYGONSTIPPLE, _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, gl_stencil_attrib::ActiveFace, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, gl_colorbuffer_attrib::AlphaRefUnclamped, gl_light::Ambient, gl_lightmodel::Ambient, API_OPENGL_COMPAT, API_OPENGL_CORE, gl_polygon_attrib::BackMode, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendColorUnclamped, gl_colorbuffer_attrib::BlendEnabled, gl_depthbuffer_attrib::BoundsMax, gl_depthbuffer_attrib::BoundsMin, gl_depthbuffer_attrib::BoundsTest, gl_colorbuffer_attrib::ClampFragmentColor, gl_colorbuffer_attrib::ClampReadColor, gl_light_attrib::ClampVertexColor, gl_depthbuffer_attrib::Clear, gl_stencil_attrib::Clear, gl_accum_attrib::ClearColor, gl_colorbuffer_attrib::ClearColor, gl_colorbuffer_attrib::ClearIndex, gl_transform_attrib::ClipDepthMode, gl_transform_attrib::ClipOrigin, gl_transform_attrib::ClipPlanesEnabled, gl_fog_attrib::Color, gl_lightmodel::ColorControl, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_light_attrib::ColorMaterialEnabled, gl_light_attrib::ColorMaterialFace, gl_light_attrib::ColorMaterialMode, gl_light::ConstantAttenuation, gl_point_attrib::CoordReplace, COPY_4V, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_attrib_node::data, gl_fog_attrib::Density, gl_transform_attrib::DepthClamp, gl_light::Diffuse, gl_colorbuffer_attrib::DitherFlag, gl_colorbuffer_attrib::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, DUMMY_BIT, gl_light::Enabled, gl_fog_attrib::Enabled, gl_light_attrib::Enabled, gl_multisample_attrib::Enabled, gl_stencil_attrib::Enabled, gl_scissor_attrib::EnableFlags, gl_fog_attrib::End, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_light::EyePosition, gl_transform_attrib::EyeUserPlane, gl_color_union::f, gl_stencil_attrib::FailFunc, gl_viewport_attrib::Far, FLUSH_CURRENT, FLUSH_VERTICES, gl_hint_attrib::Fog, for(), gl_polygon_attrib::FrontFace, gl_polygon_attrib::FrontMode, gl_depthbuffer_attrib::Func, gl_stencil_attrib::Function, GET_CURRENT_CONTEXT, GLuint, gl_scissor_rect::Height, gl_viewport_attrib::Height, gl_fog_attrib::Index, gl_colorbuffer_attrib::IndexLogicOpEnabled, gl_colorbuffer_attrib::IndexMask, gl_attrib_node::kind, gl_light_attrib::Light, gl_light::LinearAttenuation, gl_hint_attrib::LineSmooth, gl_lightmodel::LocalViewer, gl_colorbuffer_attrib::LogicOp, gl_depthbuffer_attrib::Mask, gl_light_attrib::Material, gl_transform_attrib::MatrixMode, gl_point_attrib::MaxSize, MESA_VERBOSE, gl_point_attrib::MinSize, gl_fog_attrib::Mode, gl_light_attrib::Model, gl_viewport_attrib::Near, gl_attrib_node::next, gl_transform_attrib::Normalize, gl_scissor_attrib::NumWindowRects, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, gl_point_attrib::Params, gl_hint_attrib::PerspectiveCorrection, gl_hint_attrib::PointSmooth, gl_point_attrib::PointSprite, gl_hint_attrib::PolygonSmooth, pop_enable_group(), pop_texture_group(), gl_light::QuadraticAttenuation, gl_stencil_attrib::Ref, gl_transform_attrib::RescaleNormals, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleCoverageValue, gl_scissor_attrib::ScissorArray, gl_light_attrib::ShadeModel, gl_point_attrib::Size, gl_line_attrib::SmoothFlag, gl_point_attrib::SmoothFlag, gl_polygon_attrib::SmoothFlag, gl_light::Specular, gl_light::SpotCutoff, gl_light::SpotDirection, gl_light::SpotExponent, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, gl_colorbuffer_attrib::sRGBEnabled, gl_fog_attrib::Start, gl_line_attrib::StippleFactor, gl_line_attrib::StippleFlag, gl_polygon_attrib::StippleFlag, gl_line_attrib::StipplePattern, gl_depthbuffer_attrib::Test, TEST_AND_UPDATE, gl_stencil_attrib::TestTwoSide, gl_hint_attrib::TextureCompression, gl_point_attrib::Threshold, gl_lightmodel::TwoSide, gl_stencil_attrib::ValueMask, VERBOSE_API, gl_line_attrib::Width, gl_scissor_rect::Width, gl_viewport_attrib::Width, gl_scissor_attrib::WindowRectMode, gl_scissor_attrib::WindowRects, gl_stencil_attrib::WriteMask, X, gl_scissor_rect::X, Y, gl_scissor_rect::Y, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
_mesa_PopClientAttrib()
void GLAPIENTRY _mesa_PopClientAttrib (void)
References _mesa_error(), _mesa_problem(), _mesa_reference_buffer_object(), _NEW_ARRAY, gl_pixelstore_attrib::BufferObj, copy_pixelstore(), gl_attrib_node::data, FLUSH_VERTICES, free_array_attrib_data(), GET_CURRENT_CONTEXT, GL_CLIENT_PACK_BIT, GL_CLIENT_UNPACK_BIT, gl_attrib_node::kind, gl_attrib_node::next, and restore_array_attrib().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), and _mesa_dump_stencil_buffer().
_mesa_PushAttrib()
void GLAPIENTRY _mesa_PushAttrib (GLbitfield mask)
References _mesa_copy_texture_object(), _mesa_debug(), _mesa_error(), _mesa_lock_context_textures(), _mesa_reference_shared_state(), _mesa_reference_texobj(), _mesa_unlock_context_textures(), gl_enable_attrib::AlphaTest, gl_enable_attrib::AutoNormal, gl_enable_attrib::Blend, CALLOC_STRUCT, gl_enable_attrib::ClipPlanes, gl_enable_attrib::ColorLogicOp, gl_enable_attrib::ColorMaterial, gl_enable_attrib::CullFace, gl_enable_attrib::DepthClamp, gl_enable_attrib::DepthTest, gl_enable_attrib::Dither, gl_colorbuffer_attrib::DrawBuffer, DUMMY_BIT, FLUSH_CURRENT, gl_enable_attrib::Fog, gl_enable_attrib::FragmentProgram, GET_CURRENT_CONTEXT, GLuint, gl_enable_attrib::IndexLogicOp, gl_enable_attrib::Light, gl_enable_attrib::Lighting, gl_enable_attrib::LineSmooth, gl_enable_attrib::LineStipple, MALLOC_STRUCT, gl_enable_attrib::Map1Color4, gl_enable_attrib::Map1Index, gl_enable_attrib::Map1Normal, gl_enable_attrib::Map1TextureCoord1, gl_enable_attrib::Map1TextureCoord2, gl_enable_attrib::Map1TextureCoord3, gl_enable_attrib::Map1TextureCoord4, gl_enable_attrib::Map1Vertex3, gl_enable_attrib::Map1Vertex4, gl_enable_attrib::Map2Color4, gl_enable_attrib::Map2Index, gl_enable_attrib::Map2Normal, gl_enable_attrib::Map2TextureCoord1, gl_enable_attrib::Map2TextureCoord2, gl_enable_attrib::Map2TextureCoord3, gl_enable_attrib::Map2TextureCoord4, gl_enable_attrib::Map2Vertex3, gl_enable_attrib::Map2Vertex4, MAX_ATTRIB_STACK_DEPTH, MESA_VERBOSE, gl_enable_attrib::MultisampleEnabled, gl_enable_attrib::Normalize, NUM_TEXTURE_TARGETS, gl_enable_attrib::PointSmooth, gl_enable_attrib::PointSprite, gl_enable_attrib::PolygonOffsetFill, gl_enable_attrib::PolygonOffsetLine, gl_enable_attrib::PolygonOffsetPoint, gl_enable_attrib::PolygonSmooth, gl_enable_attrib::PolygonStipple, push_attrib(), gl_enable_attrib::RasterPositionUnclipped, gl_pixel_attrib::ReadBuffer, gl_enable_attrib::RescaleNormals, gl_enable_attrib::SampleAlphaToCoverage, gl_enable_attrib::SampleAlphaToOne, gl_enable_attrib::SampleCoverage, save_attrib_data(), texture_state::SavedObj, texture_state::SavedTexRef, gl_enable_attrib::Scissor, texture_state::SharedRef, gl_enable_attrib::sRGBEnabled, gl_enable_attrib::Stencil, gl_enable_attrib::StencilTwoSide, gl_enable_attrib::TexGen, gl_enable_attrib::Texture, texture_state::Texture, VERBOSE_API, gl_enable_attrib::VertexProgram, gl_enable_attrib::VertexProgramPointSize, and gl_enable_attrib::VertexProgramTwoSide.
_mesa_PushClientAttrib()
void GLAPIENTRY _mesa_PushClientAttrib (GLbitfield mask)
References _mesa_error(), CALLOC_STRUCT, copy_pixelstore(), free_array_attrib_data(), GET_CURRENT_CONTEXT, GL_CLIENT_PACK_BIT, GL_CLIENT_UNPACK_BIT, GLAPIENTRY, init_array_attrib_data(), MAX_CLIENT_ATTRIB_STACK_DEPTH, save_array_attrib(), and save_attrib_data().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), and _mesa_dump_stencil_buffer().