Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
attrib.c File Reference
#include "glheader.h"
#include "imports.h"
#include "accum.h"
#include "arrayobj.h"
#include "attrib.h"
#include "blend.h"
#include "buffers.h"
#include "bufferobj.h"
#include "clear.h"
#include "context.h"
#include "depth.h"
#include "enable.h"
#include "enums.h"
#include "fog.h"
#include "hint.h"
#include "light.h"
#include "lines.h"
#include "macros.h"
#include "matrix.h"
#include "multisample.h"
#include "points.h"
#include "polygon.h"
#include "shared.h"
#include "scissor.h"
#include "stencil.h"
#include "texenv.h"
#include "texgen.h"
#include "texobj.h"
#include "texparam.h"
#include "texstate.h"
#include "varray.h"
#include "viewport.h"
#include "mtypes.h"
#include "main/dispatch.h"
#include "hash.h"
#include <stdbool.h>
Data Structures
struct gl_enable_attrib
glEnable()/glDisable() attribute group (GL_ENABLE_BIT).
struct gl_attrib_node
Node for the attribute stack.
struct texture_state
Special struct for saving/restoring texture state (GL_TEXTURE_BIT)
Macros
#define DUMMY_BIT 0x10000000
An unused GL_*_BIT value.
#define TEST_AND_UPDATE(VALUE, NEWVALUE, ENUM)
#define GL_CLIENT_PACK_BIT (1<<20)
#define GL_CLIENT_UNPACK_BIT (1<<21)
Functions
static bool save_attrib_data (struct gl_attrib_node **head, GLbitfield kind, void *payload)
Allocate new attribute node of given type/kind.
static bool push_attrib (struct gl_context *ctx, struct gl_attrib_node **head, GLbitfield attr_bit, GLuint attr_size, const void *attr_data)
Helper function for_mesa_PushAttrib for simple attributes.
void GLAPIENTRY _mesa_PushAttrib (GLbitfield mask)
static void pop_enable_group (struct gl_context *ctx, const struct gl_enable_attrib *enable)
static void pop_texture_group (struct gl_context *ctx, struct texture_state *texstate)
Pop/restore texture attribute/group state.
void GLAPIENTRY _mesa_PopAttrib (void)
static void copy_pixelstore (struct gl_context *ctx, struct gl_pixelstore_attrib *dst, const struct gl_pixelstore_attrib *src)
Copy gl_pixelstore_attrib from src to dst, updating buffer object refcounts.
static void copy_array_object (struct gl_context *ctx, struct gl_vertex_array_object *dest, struct gl_vertex_array_object *src)
Copy gl_vertex_array_object from src to dest.
static void copy_array_attrib (struct gl_context *ctx, struct gl_array_attrib *dest, struct gl_array_attrib *src, bool vbo_deleted)
Copy gl_array_attrib from src to dest.
static void save_array_attrib (struct gl_context *ctx, struct gl_array_attrib *dest, struct gl_array_attrib *src)
Save the content of src to dest.
static void restore_array_attrib (struct gl_context *ctx, struct gl_array_attrib *dest, struct gl_array_attrib *src)
Restore the content of src to dest.
static bool init_array_attrib_data (struct gl_context *ctx, struct gl_array_attrib *attrib)
init/alloc the fields of 'attrib'.
static void free_array_attrib_data (struct gl_context *ctx, struct gl_array_attrib *attrib)
Free/unreference the fields of 'attrib' but don't delete it (that's done later in the calling code).
void GLAPIENTRY _mesa_PushClientAttrib (GLbitfield mask)
void GLAPIENTRY _mesa_PopClientAttrib (void)
void _mesa_free_attrib_data (struct gl_context *ctx)
Free any attribute state data that might be attached to the context.
void _mesa_init_attrib (struct gl_context *ctx)
Macro Definition Documentation
DUMMY_BIT
#define DUMMY_BIT 0x10000000
An unused GL_*_BIT value.
Referenced by _mesa_PopAttrib(), and _mesa_PushAttrib().
GL_CLIENT_PACK_BIT
#define GL_CLIENT_PACK_BIT (1<<20)
Referenced by _mesa_PopClientAttrib(), and _mesa_PushClientAttrib().
GL_CLIENT_UNPACK_BIT
#define GL_CLIENT_UNPACK_BIT (1<<21)
Referenced by _mesa_PopClientAttrib(), and _mesa_PushClientAttrib().
TEST_AND_UPDATE
#define TEST_AND_UPDATE (VALUE, NEWVALUE, ENUM)
Value:
if ((VALUE) != (NEWVALUE)) {                    \
           _mesa_set_enable( ctx, ENUM, (NEWVALUE) );   \
        }
Referenced by _mesa_PopAttrib(), and pop_enable_group().
Function Documentation
_mesa_free_attrib_data()
void _mesa_free_attrib_data (struct gl_context * ctx)
Free any attribute state data that might be attached to the context.
References _mesa_reference_shared_state(), _mesa_reference_texobj(), gl_context::AttribStack, gl_context::AttribStackDepth, gl_context::Const, gl_attrib_node::data, for(), GLuint, gl_attrib_node::kind, gl_constants::MaxTextureUnits, gl_attrib_node::next, NUM_TEXTURE_TARGETS, texture_state::SavedTexRef, and texture_state::SharedRef.
Referenced by _mesa_free_context_data().
_mesa_init_attrib()
void _mesa_init_attrib (struct gl_context * ctx)
References gl_context::AttribStackDepth, and gl_context::ClientAttribStackDepth.
Referenced by init_attrib_groups().
_mesa_PopAttrib()
void GLAPIENTRY _mesa_PopAttrib (void)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_ActiveStencilFaceEXT(), _mesa_AlphaFunc(), _mesa_BlendColor(), _mesa_BlendEquation(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_BlendFuncSeparateiARB(), _mesa_ClampColor(), _mesa_ClearAccum(), _mesa_ClearColor(), _mesa_ClearDepth(), _mesa_ClearIndex(), _mesa_ClearStencil(), _mesa_ClipControl(), _mesa_ColorMask(), _mesa_ColorMaski(), _mesa_ColorMaterial(), _mesa_CullFace(), _mesa_debug(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthMask(), _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_enum_to_string(), _mesa_error(), _mesa_Fogf(), _mesa_Fogfv(), _mesa_Fogi(), _mesa_FrontFace(), _mesa_Hint(), _mesa_IndexMask(), _mesa_light(), _mesa_LightModelf(), _mesa_LightModelfv(), _mesa_LineStipple(), _mesa_LineWidth(), _mesa_LogicOp(), _mesa_MatrixMode(), _mesa_PointParameterf(), _mesa_PointParameterfv(), _mesa_PointParameteri(), _mesa_PointSize(), _mesa_polygon_offset_clamp(), _mesa_PolygonMode(), _mesa_problem(), _mesa_ReadBuffer(), _mesa_SampleCoverage(), _mesa_set_depth_range(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_set_scissor(), _mesa_set_viewport(), _mesa_ShadeModel(), _mesa_StencilFuncSeparate(), _mesa_StencilMaskSeparate(), _mesa_StencilOpSeparate(), _mesa_TexEnvi(), _mesa_WindowRectanglesEXT(), _NEW_ALL, _NEW_EVAL, _NEW_PIXEL, _NEW_POLYGONSTIPPLE, _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, gl_stencil_attrib::ActiveFace, gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, gl_colorbuffer_attrib::AlphaRefUnclamped, gl_light::Ambient, gl_lightmodel::Ambient, API_OPENGL_COMPAT, API_OPENGL_CORE, gl_polygon_attrib::BackMode, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendColorUnclamped, gl_colorbuffer_attrib::BlendEnabled, gl_depthbuffer_attrib::BoundsMax, gl_depthbuffer_attrib::BoundsMin, gl_depthbuffer_attrib::BoundsTest, gl_colorbuffer_attrib::ClampFragmentColor, gl_colorbuffer_attrib::ClampReadColor, gl_light_attrib::ClampVertexColor, gl_depthbuffer_attrib::Clear, gl_stencil_attrib::Clear, gl_accum_attrib::ClearColor, gl_colorbuffer_attrib::ClearColor, gl_colorbuffer_attrib::ClearIndex, gl_transform_attrib::ClipDepthMode, gl_transform_attrib::ClipOrigin, gl_transform_attrib::ClipPlanesEnabled, gl_fog_attrib::Color, gl_lightmodel::ColorControl, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_light_attrib::ColorMaterialEnabled, gl_light_attrib::ColorMaterialFace, gl_light_attrib::ColorMaterialMode, gl_light::ConstantAttenuation, gl_point_attrib::CoordReplace, COPY_4V, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_attrib_node::data, gl_fog_attrib::Density, gl_transform_attrib::DepthClamp, gl_light::Diffuse, gl_colorbuffer_attrib::DitherFlag, gl_colorbuffer_attrib::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, DUMMY_BIT, gl_light::Enabled, gl_fog_attrib::Enabled, gl_light_attrib::Enabled, gl_multisample_attrib::Enabled, gl_stencil_attrib::Enabled, gl_scissor_attrib::EnableFlags, gl_fog_attrib::End, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_light::EyePosition, gl_transform_attrib::EyeUserPlane, gl_color_union::f, gl_stencil_attrib::FailFunc, gl_viewport_attrib::Far, FLUSH_CURRENT, FLUSH_VERTICES, gl_hint_attrib::Fog, for(), gl_polygon_attrib::FrontFace, gl_polygon_attrib::FrontMode, gl_depthbuffer_attrib::Func, gl_stencil_attrib::Function, GET_CURRENT_CONTEXT, GLuint, gl_scissor_rect::Height, gl_viewport_attrib::Height, gl_fog_attrib::Index, gl_colorbuffer_attrib::IndexLogicOpEnabled, gl_colorbuffer_attrib::IndexMask, gl_attrib_node::kind, gl_light_attrib::Light, gl_light::LinearAttenuation, gl_hint_attrib::LineSmooth, gl_lightmodel::LocalViewer, gl_colorbuffer_attrib::LogicOp, gl_depthbuffer_attrib::Mask, gl_light_attrib::Material, gl_transform_attrib::MatrixMode, gl_point_attrib::MaxSize, MESA_VERBOSE, gl_point_attrib::MinSize, gl_fog_attrib::Mode, gl_light_attrib::Model, gl_viewport_attrib::Near, gl_attrib_node::next, gl_transform_attrib::Normalize, gl_scissor_attrib::NumWindowRects, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, gl_point_attrib::Params, gl_hint_attrib::PerspectiveCorrection, gl_hint_attrib::PointSmooth, gl_point_attrib::PointSprite, gl_hint_attrib::PolygonSmooth, pop_enable_group(), pop_texture_group(), gl_light::QuadraticAttenuation, gl_stencil_attrib::Ref, gl_transform_attrib::RescaleNormals, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleCoverageValue, gl_scissor_attrib::ScissorArray, gl_light_attrib::ShadeModel, gl_point_attrib::Size, gl_line_attrib::SmoothFlag, gl_point_attrib::SmoothFlag, gl_polygon_attrib::SmoothFlag, gl_light::Specular, gl_light::SpotCutoff, gl_light::SpotDirection, gl_light::SpotExponent, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, gl_colorbuffer_attrib::sRGBEnabled, gl_fog_attrib::Start, gl_line_attrib::StippleFactor, gl_line_attrib::StippleFlag, gl_polygon_attrib::StippleFlag, gl_line_attrib::StipplePattern, gl_depthbuffer_attrib::Test, TEST_AND_UPDATE, gl_stencil_attrib::TestTwoSide, gl_hint_attrib::TextureCompression, gl_point_attrib::Threshold, gl_lightmodel::TwoSide, gl_stencil_attrib::ValueMask, VERBOSE_API, gl_line_attrib::Width, gl_scissor_rect::Width, gl_viewport_attrib::Width, gl_scissor_attrib::WindowRectMode, gl_scissor_attrib::WindowRects, gl_stencil_attrib::WriteMask, X, gl_scissor_rect::X, Y, gl_scissor_rect::Y, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
_mesa_PopClientAttrib()
void GLAPIENTRY _mesa_PopClientAttrib (void)
References _mesa_error(), _mesa_problem(), _mesa_reference_buffer_object(), _NEW_ARRAY, gl_pixelstore_attrib::BufferObj, copy_pixelstore(), gl_attrib_node::data, FLUSH_VERTICES, free_array_attrib_data(), GET_CURRENT_CONTEXT, GL_CLIENT_PACK_BIT, GL_CLIENT_UNPACK_BIT, gl_attrib_node::kind, gl_attrib_node::next, and restore_array_attrib().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), and _mesa_dump_stencil_buffer().
_mesa_PushAttrib()
void GLAPIENTRY _mesa_PushAttrib (GLbitfield mask)
References _mesa_copy_texture_object(), _mesa_debug(), _mesa_error(), _mesa_lock_context_textures(), _mesa_reference_shared_state(), _mesa_reference_texobj(), _mesa_unlock_context_textures(), gl_enable_attrib::AlphaTest, gl_enable_attrib::AutoNormal, gl_enable_attrib::Blend, CALLOC_STRUCT, gl_enable_attrib::ClipPlanes, gl_enable_attrib::ColorLogicOp, gl_enable_attrib::ColorMaterial, gl_enable_attrib::CullFace, gl_enable_attrib::DepthClamp, gl_enable_attrib::DepthTest, gl_enable_attrib::Dither, gl_colorbuffer_attrib::DrawBuffer, DUMMY_BIT, FLUSH_CURRENT, gl_enable_attrib::Fog, gl_enable_attrib::FragmentProgram, GET_CURRENT_CONTEXT, GLuint, gl_enable_attrib::IndexLogicOp, gl_enable_attrib::Light, gl_enable_attrib::Lighting, gl_enable_attrib::LineSmooth, gl_enable_attrib::LineStipple, MALLOC_STRUCT, gl_enable_attrib::Map1Color4, gl_enable_attrib::Map1Index, gl_enable_attrib::Map1Normal, gl_enable_attrib::Map1TextureCoord1, gl_enable_attrib::Map1TextureCoord2, gl_enable_attrib::Map1TextureCoord3, gl_enable_attrib::Map1TextureCoord4, gl_enable_attrib::Map1Vertex3, gl_enable_attrib::Map1Vertex4, gl_enable_attrib::Map2Color4, gl_enable_attrib::Map2Index, gl_enable_attrib::Map2Normal, gl_enable_attrib::Map2TextureCoord1, gl_enable_attrib::Map2TextureCoord2, gl_enable_attrib::Map2TextureCoord3, gl_enable_attrib::Map2TextureCoord4, gl_enable_attrib::Map2Vertex3, gl_enable_attrib::Map2Vertex4, MAX_ATTRIB_STACK_DEPTH, MESA_VERBOSE, gl_enable_attrib::MultisampleEnabled, gl_enable_attrib::Normalize, NUM_TEXTURE_TARGETS, gl_enable_attrib::PointSmooth, gl_enable_attrib::PointSprite, gl_enable_attrib::PolygonOffsetFill, gl_enable_attrib::PolygonOffsetLine, gl_enable_attrib::PolygonOffsetPoint, gl_enable_attrib::PolygonSmooth, gl_enable_attrib::PolygonStipple, push_attrib(), gl_enable_attrib::RasterPositionUnclipped, gl_pixel_attrib::ReadBuffer, gl_enable_attrib::RescaleNormals, gl_enable_attrib::SampleAlphaToCoverage, gl_enable_attrib::SampleAlphaToOne, gl_enable_attrib::SampleCoverage, save_attrib_data(), texture_state::SavedObj, texture_state::SavedTexRef, gl_enable_attrib::Scissor, texture_state::SharedRef, gl_enable_attrib::sRGBEnabled, gl_enable_attrib::Stencil, gl_enable_attrib::StencilTwoSide, gl_enable_attrib::TexGen, gl_enable_attrib::Texture, texture_state::Texture, VERBOSE_API, gl_enable_attrib::VertexProgram, gl_enable_attrib::VertexProgramPointSize, and gl_enable_attrib::VertexProgramTwoSide.
_mesa_PushClientAttrib()
void GLAPIENTRY _mesa_PushClientAttrib (GLbitfield mask)
References _mesa_error(), CALLOC_STRUCT, copy_pixelstore(), free_array_attrib_data(), GET_CURRENT_CONTEXT, GL_CLIENT_PACK_BIT, GL_CLIENT_UNPACK_BIT, GLAPIENTRY, init_array_attrib_data(), MAX_CLIENT_ATTRIB_STACK_DEPTH, save_array_attrib(), and save_attrib_data().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), and _mesa_dump_stencil_buffer().
copy_array_attrib()
static void copy_array_attrib (struct gl_context * ctx, struct gl_array_attrib * dest, struct gl_array_attrib * src, bool vbo_deleted) static
Copy gl_array_attrib from src to dest.
'dest' must be in an initialized state.
References gl_array_attrib::_DrawArrays, gl_array_attrib::_PrimitiveRestart, gl_array_attrib::ActiveTexture, copy_array_object(), DRAW_NONE, gl_array_attrib::DrawMethod, gl_array_attrib::LockCount, gl_array_attrib::LockFirst, gl_array_attrib::PrimitiveRestart, gl_array_attrib::PrimitiveRestartFixedIndex, gl_array_attrib::RestartIndex, and gl_array_attrib::VAO.
Referenced by restore_array_attrib(), and save_array_attrib().
copy_array_object()
static void copy_array_object (struct gl_context * ctx, struct gl_vertex_array_object * dest, struct gl_vertex_array_object * src) static
Copy gl_vertex_array_object from src to dest.
'dest' must be in an initialized state.
References gl_vertex_array_object::_Enabled, _mesa_copy_client_array(), _mesa_copy_vertex_attrib_array(), _mesa_copy_vertex_buffer_binding(), gl_vertex_array_object::_VertexAttrib, gl_vertex_array_object::ARBsemantics, gl_vertex_array_object::BufferBinding, GLuint, gl_vertex_array_object::NewArrays, gl_vertex_array_object::VertexAttrib, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by copy_array_attrib().
copy_pixelstore()
static void copy_pixelstore (struct gl_context * ctx, struct gl_pixelstore_attrib * dst, const struct gl_pixelstore_attrib * src) static
Copy gl_pixelstore_attrib from src to dst, updating buffer object refcounts.
References _mesa_reference_buffer_object(), gl_pixelstore_attrib::Alignment, gl_pixelstore_attrib::BufferObj, gl_pixelstore_attrib::ImageHeight, gl_pixelstore_attrib::Invert, gl_pixelstore_attrib::LsbFirst, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipImages, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_PopClientAttrib(), and _mesa_PushClientAttrib().
free_array_attrib_data()
static void free_array_attrib_data (struct gl_context * ctx, struct gl_array_attrib * attrib) static
Free/unreference the fields of 'attrib' but don't delete it (that's done later in the calling code).
Needs to the cleanup part matching init_array_attrib_data above.
References _mesa_delete_vao(), _mesa_reference_buffer_object(), gl_array_attrib::ArrayBufferObj, GLAPIENTRY, and gl_array_attrib::VAO.
Referenced by _mesa_PopClientAttrib(), and _mesa_PushClientAttrib().
init_array_attrib_data()
static bool init_array_attrib_data (struct gl_context * ctx, struct gl_array_attrib * attrib) static
init/alloc the fields of 'attrib'.
Needs to the init part matching free_array_attrib_data below.
References _mesa_error(), _mesa_initialize_vao(), CALLOC_STRUCT, and gl_array_attrib::VAO.
Referenced by _mesa_PushClientAttrib().
pop_enable_group()
static void pop_enable_group (struct gl_context * ctx, const struct gl_enable_attrib * enable) static
References _mesa_ActiveTexture(), _mesa_set_enable(), _mesa_set_enablei(), gl_colorbuffer_attrib::AlphaEnabled, gl_enable_attrib::AlphaTest, gl_extensions::ARB_point_sprite, gl_extensions::ARB_texture_cube_map, gl_enable_attrib::AutoNormal, gl_eval_attrib::AutoNormal, gl_enable_attrib::Blend, gl_colorbuffer_attrib::BlendEnabled, gl_enable_attrib::ClipPlanes, gl_transform_attrib::ClipPlanesEnabled, gl_context::Color, gl_enable_attrib::ColorLogicOp, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_enable_attrib::ColorMaterial, gl_light_attrib::ColorMaterialEnabled, gl_context::Const, gl_enable_attrib::CullFace, gl_polygon_attrib::CullFlag, gl_texture_attrib::CurrentUnit, gl_context::Depth, gl_enable_attrib::DepthClamp, gl_transform_attrib::DepthClamp, gl_enable_attrib::DepthTest, gl_enable_attrib::Dither, gl_colorbuffer_attrib::DitherFlag, gl_fog_attrib::Enabled, gl_light_attrib::Enabled, gl_multisample_attrib::Enabled, gl_stencil_attrib::Enabled, gl_texture_unit::Enabled, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, gl_scissor_attrib::EnableFlags, gl_context::Eval, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_stencil_two_side, gl_context::Extensions, gl_enable_attrib::Fog, gl_context::Fog, gl_enable_attrib::FragmentProgram, gl_context::FragmentProgram, GLuint, gl_enable_attrib::IndexLogicOp, gl_colorbuffer_attrib::IndexLogicOpEnabled, gl_context::Light, gl_enable_attrib::Lighting, gl_context::Line, gl_enable_attrib::LineSmooth, gl_enable_attrib::LineStipple, gl_enable_attrib::Map1Color4, gl_eval_attrib::Map1Color4, gl_enable_attrib::Map1Index, gl_eval_attrib::Map1Index, gl_enable_attrib::Map1Normal, gl_eval_attrib::Map1Normal, gl_enable_attrib::Map1TextureCoord1, gl_eval_attrib::Map1TextureCoord1, gl_enable_attrib::Map1TextureCoord2, gl_eval_attrib::Map1TextureCoord2, gl_enable_attrib::Map1TextureCoord3, gl_eval_attrib::Map1TextureCoord3, gl_enable_attrib::Map1TextureCoord4, gl_eval_attrib::Map1TextureCoord4, gl_enable_attrib::Map1Vertex3, gl_eval_attrib::Map1Vertex3, gl_enable_attrib::Map1Vertex4, gl_eval_attrib::Map1Vertex4, gl_enable_attrib::Map2Color4, gl_eval_attrib::Map2Color4, gl_enable_attrib::Map2Index, gl_eval_attrib::Map2Index, gl_enable_attrib::Map2Normal, gl_eval_attrib::Map2Normal, gl_enable_attrib::Map2TextureCoord1, gl_eval_attrib::Map2TextureCoord1, gl_enable_attrib::Map2TextureCoord2, gl_eval_attrib::Map2TextureCoord2, gl_enable_attrib::Map2TextureCoord3, gl_eval_attrib::Map2TextureCoord3, gl_enable_attrib::Map2TextureCoord4, gl_eval_attrib::Map2TextureCoord4, gl_enable_attrib::Map2Vertex3, gl_eval_attrib::Map2Vertex3, gl_enable_attrib::Map2Vertex4, gl_eval_attrib::Map2Vertex4, gl_constants::MaxClipPlanes, gl_constants::MaxDrawBuffers, gl_constants::MaxTextureUnits, gl_constants::MaxViewports, gl_context::Multisample, gl_enable_attrib::MultisampleEnabled, gl_enable_attrib::Normalize, gl_transform_attrib::Normalize, gl_extensions::NV_point_sprite, gl_extensions::NV_texture_rectangle, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_context::Point, gl_vertex_program_state::PointSizeEnabled, gl_enable_attrib::PointSmooth, gl_enable_attrib::PointSprite, gl_point_attrib::PointSprite, gl_context::Polygon, gl_enable_attrib::PolygonOffsetFill, gl_enable_attrib::PolygonOffsetLine, gl_enable_attrib::PolygonOffsetPoint, gl_enable_attrib::PolygonSmooth, gl_enable_attrib::PolygonStipple, Q_BIT, R_BIT, gl_enable_attrib::RasterPositionUnclipped, gl_transform_attrib::RasterPositionUnclipped, gl_enable_attrib::RescaleNormals, gl_transform_attrib::RescaleNormals, S_BIT, gl_enable_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToCoverage, gl_enable_attrib::SampleAlphaToOne, gl_multisample_attrib::SampleAlphaToOne, gl_enable_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverage, gl_enable_attrib::Scissor, gl_context::Scissor, gl_line_attrib::SmoothFlag, gl_point_attrib::SmoothFlag, gl_polygon_attrib::SmoothFlag, gl_enable_attrib::sRGBEnabled, gl_colorbuffer_attrib::sRGBEnabled, gl_enable_attrib::Stencil, gl_context::Stencil, gl_enable_attrib::StencilTwoSide, gl_line_attrib::StippleFlag, gl_polygon_attrib::StippleFlag, T_BIT, gl_depthbuffer_attrib::Test, TEST_AND_UPDATE, gl_stencil_attrib::TestTwoSide, gl_enable_attrib::TexGen, gl_texture_unit::TexGenEnabled, gl_enable_attrib::Texture, gl_context::Texture, TEXTURE_1D_BIT, TEXTURE_2D_BIT, TEXTURE_3D_BIT, TEXTURE_CUBE_BIT, TEXTURE_RECT_BIT, gl_context::Transform, gl_vertex_program_state::TwoSideEnabled, gl_texture_attrib::Unit, gl_enable_attrib::VertexProgram, gl_context::VertexProgram, gl_enable_attrib::VertexProgramPointSize, and gl_enable_attrib::VertexProgramTwoSide.
Referenced by _mesa_PopAttrib().
pop_texture_group()
static void pop_texture_group (struct gl_context * ctx, struct texture_state * texstate) static
Pop/restore texture attribute/group state.
References _mesa_ActiveTexture(), _mesa_BindTexture(), _mesa_lock_context_textures(), _mesa_reference_shared_state(), _mesa_reference_texobj(), _mesa_set_enable(), _mesa_TexEnvf(), _mesa_TexEnvfv(), _mesa_TexEnvi(), _mesa_TexGenfv(), _mesa_TexGeni(), _mesa_TexParameterf(), _mesa_TexParameterfv(), _mesa_TexParameteri(), _mesa_unlock_context_textures(), gl_extensions::ARB_depth_texture, gl_extensions::ARB_shadow, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, gl_texture_unit::Combine, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_context::Const, gl_texture_attrib::CurrentUnit, gl_texture_object::DepthMode, gl_context::Driver, gl_texture_unit::Enabled, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_filter_anisotropic, gl_context::Extensions, gl_texgen::EyePlane, gl_color_union::f, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GL_TEXTURE_EXTERNAL_OES, GLAPIENTRY, GLuint, gl_sampler_object::LodBias, gl_texture_unit::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_constants::MaxTextureUnits, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texgen::Mode, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_texture_object::Name, NUM_TEXTURE_TARGETS, gl_extensions::NV_texture_env_combine4, gl_extensions::NV_texture_rectangle, gl_texgen::ObjectPlane, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_texture_object::Priority, Q_BIT, R_BIT, S_BIT, gl_texture_object::Sampler, texture_state::SavedObj, texture_state::SavedTexRef, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, texture_state::SharedRef, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, T_BIT, gl_texture_object::Target, dd_function_table::TexGen, gl_texture_unit::TexGenEnabled, texture_state::Texture, gl_context::Texture, TEXTURE_1D_BIT, TEXTURE_2D_BIT, TEXTURE_3D_BIT, TEXTURE_CUBE_BIT, TEXTURE_RECT_BIT, gl_texture_attrib::Unit, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_PopAttrib().
push_attrib()
static bool push_attrib (struct gl_context * ctx, struct gl_attrib_node ** head, GLbitfield attr_bit, GLuint attr_size, const void * attr_data) static
Helper function for_mesa_PushAttrib for simple attributes.
Allocates memory for attribute data and copies the given attribute data.
Parameters
head head of linked list to insert attribute data into
attr_bit one of the GL_<attrib>_BIT flags
attr_size number of bytes to allocate for attribute data
attr_data the attribute data to copy
Returns
true for success, false for out of memory
References _mesa_error(), GLAPIENTRY, and save_attrib_data().
Referenced by _mesa_PushAttrib().
restore_array_attrib()
static void restore_array_attrib (struct gl_context * ctx, struct gl_array_attrib * dest, struct gl_array_attrib * src) static
Restore the content of src to dest.
References _mesa_BindBuffer(), _mesa_BindVertexArrayAPPLE(), _mesa_IsBuffer(), _mesa_IsVertexArray(), gl_vertex_array_object::ARBsemantics, gl_array_attrib::ArrayBufferObj, copy_array_attrib(), gl_vertex_array_object::IndexBufferObj, gl_buffer_object::Name, gl_vertex_array_object::Name, and gl_array_attrib::VAO.
Referenced by _mesa_PopClientAttrib().
save_array_attrib()
static void save_array_attrib (struct gl_context * ctx, struct gl_array_attrib * dest, struct gl_array_attrib * src) static
Save the content of src to dest.
References _mesa_reference_buffer_object(), gl_array_attrib::ArrayBufferObj, copy_array_attrib(), gl_vertex_array_object::IndexBufferObj, gl_vertex_array_object::Name, and gl_array_attrib::VAO.
Referenced by _mesa_PushClientAttrib().
save_attrib_data()
static bool save_attrib_data (struct gl_attrib_node ** head, GLbitfield kind, void * payload) static
Allocate new attribute node of given type/kind.
Attach payload data. Insert it into the linked list named by 'head'.
References gl_attrib_node::data, gl_attrib_node::kind, MALLOC_STRUCT, and gl_attrib_node::next.
Referenced by _mesa_PushAttrib(), _mesa_PushClientAttrib(), and push_attrib().