Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
barrier.c File Reference
Implementation of various pipeline barrier entry points.
#include "context.h"
#include "barrier.h"
Functions
static void _mesa_texture_barrier (struct gl_context *ctx)
void _mesa_init_barrier_functions (struct dd_function_table *driver)
void GLAPIENTRY _mesa_TextureBarrierNV (void)
void GLAPIENTRY _mesa_MemoryBarrier (GLbitfield barriers)
void GLAPIENTRY _mesa_MemoryBarrierByRegion (GLbitfield barriers)
void GLAPIENTRY _mesa_BlendBarrier (void)
Detailed Description
Implementation of various pipeline barrier entry points.
Author
Marek Olšák marae.nosp@m.o@gm.nosp@m.ail.c.nosp@m.om
Function Documentation
_mesa_BlendBarrier()
void GLAPIENTRY _mesa_BlendBarrier (void)
References _mesa_error(), and GET_CURRENT_CONTEXT.
_mesa_init_barrier_functions()
void _mesa_init_barrier_functions (struct dd_function_table * driver)
References _mesa_texture_barrier(), GLAPIENTRY, and dd_function_table::TextureBarrier.
_mesa_MemoryBarrier()
void GLAPIENTRY _mesa_MemoryBarrier (GLbitfield barriers)
References GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_MemoryBarrierByRegion()
void GLAPIENTRY _mesa_MemoryBarrierByRegion (GLbitfield barriers)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_texture_barrier()
static void _mesa_texture_barrier (struct gl_context * ctx) static
Referenced by _mesa_init_barrier_functions().
_mesa_TextureBarrierNV()
void GLAPIENTRY _mesa_TextureBarrierNV (void)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.