Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
blend.h File Reference
Blending functions operations.
#include "glheader.h"
#include "formats.h"
Functions
void GLAPIENTRY _mesa_BlendFunc (GLenum sfactor, GLenum dfactor)
Specify the blending operation.
void GLAPIENTRY _mesa_BlendFuncSeparate (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Set the separate blend source/dest factors for all draw buffers.
void GLAPIENTRY _mesa_BlendFunciARB (GLuint buf, GLenum sfactor, GLenum dfactor)
Set blend source/dest factors for one color buffer/target.
void GLAPIENTRY _mesa_BlendFuncSeparateiARB (GLuint buf, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Set separate blend source/dest factors for one color buffer/target.
void GLAPIENTRY _mesa_BlendEquation (GLenum mode)
void GLAPIENTRY _mesa_BlendEquationiARB (GLuint buf, GLenum mode)
Set blend equation for one color buffer/target.
void GLAPIENTRY _mesa_BlendEquationSeparate (GLenum modeRGB, GLenum modeA)
void GLAPIENTRY _mesa_BlendEquationSeparateiARB (GLuint buf, GLenum modeRGB, GLenum modeA)
Set separate blend equations for one color buffer/target.
void GLAPIENTRY _mesa_BlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Set the blending color.
void GLAPIENTRY _mesa_AlphaFunc (GLenum func, GLclampf ref)
Specify the alpha test function.
void GLAPIENTRY _mesa_LogicOp (GLenum opcode)
Specify a logic pixel operation for color index rendering.
void GLAPIENTRY _mesa_IndexMask (GLuint mask)
void GLAPIENTRY _mesa_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
Enable or disable writing of frame buffer color components.
void GLAPIENTRY _mesa_ColorMaski (GLuint buf, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
For GL_EXT_draw_buffers2 and GL3.
void GLAPIENTRY _mesa_ClampColor (GLenum target, GLenum clamp)
GLboolean _mesa_get_clamp_fragment_color (const struct gl_context *ctx, const struct gl_framebuffer *drawFb)
GLboolean _mesa_get_clamp_vertex_color (const struct gl_context *ctx, const struct gl_framebuffer *drawFb)
GLboolean _mesa_get_clamp_read_color (const struct gl_context *ctx, const struct gl_framebuffer *readFb)
void _mesa_update_clamp_fragment_color (struct gl_context *ctx, const struct gl_framebuffer *drawFb)
Update the ctx->Color._ClampFragmentColor field.
void _mesa_update_clamp_vertex_color (struct gl_context *ctx, const struct gl_framebuffer *drawFb)
Update the ctx->Color._ClampVertexColor field.
mesa_format _mesa_get_render_format (const struct gl_context *ctx, mesa_format format)
Returns an appropriate mesa_format for color rendering based on the GL_FRAMEBUFFER_SRGB state.
void _mesa_init_color (struct gl_context *ctx)
Initialization of the context's Color attribute group.
Detailed Description
Blending functions operations.
Function Documentation
_mesa_AlphaFunc()
void GLAPIENTRY _mesa_AlphaFunc (GLenum func, GLclampf ref)
Specify the alpha test function.
Parameters
func alpha comparison function.
ref reference value.
Verifies the parameters and updates gl_colorbuffer_attrib. On a change, flushes the vertices and notifies the driver via dd_function_table::AlphaFunc callback.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_AlphaFuncx(), and _mesa_PopAttrib().
_mesa_BlendColor()
void GLAPIENTRY _mesa_BlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Set the blending color.
Parameters
red red color component.
green green color component.
blue blue color component.
alpha alpha color component.
See also
glBlendColor().
Clamps the parameters and updates gl_colorbuffer_attrib::BlendColor. On a change, flushes the vertices and notifies the driver via dd_function_table::BlendColor callback.
References _NEW_COLOR, F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and TEST_EQ_4V.
Referenced by _mesa_PopAttrib().
_mesa_BlendEquation()
void GLAPIENTRY _mesa_BlendEquation (GLenum mode)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, advanced_blend_mode(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_simple_blend_equation(), MESA_VERBOSE, num_buffers(), and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_BlendEquationiARB()
void GLAPIENTRY _mesa_BlendEquationiARB (GLuint buf, GLenum mode)
Set blend equation for one color buffer/target.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, advanced_blend_mode(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_simple_blend_equation(), MESA_VERBOSE, and VERBOSE_API.
_mesa_BlendEquationSeparate()
void GLAPIENTRY _mesa_BlendEquationSeparate (GLenum modeRGB, GLenum modeA)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_simple_blend_equation(), MESA_VERBOSE, num_buffers(), and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_BlendEquationSeparateiARB()
void GLAPIENTRY _mesa_BlendEquationSeparateiARB (GLuint buf, GLenum modeRGB, GLenum modeA)
Set separate blend equations for one color buffer/target.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_simple_blend_equation(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_BlendFunc()
void GLAPIENTRY _mesa_BlendFunc (GLenum sfactor, GLenum dfactor)
Specify the blending operation.
Parameters
sfactor source factor operator.
dfactor destination factor operator.
See also
glBlendFunc, glBlendFuncSeparateEXT
References _mesa_BlendFuncSeparate().
_mesa_BlendFunciARB()
void GLAPIENTRY _mesa_BlendFunciARB (GLuint buf, GLenum sfactor, GLenum dfactor)
Set blend source/dest factors for one color buffer/target.
References _mesa_BlendFuncSeparateiARB(), and GLAPIENTRY.
_mesa_BlendFuncSeparate()
void GLAPIENTRY _mesa_BlendFuncSeparate (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Set the separate blend source/dest factors for all draw buffers.
Parameters
sfactorRGB RGB source factor operator.
dfactorRGB RGB destination factor operator.
sfactorA alpha source factor operator.
dfactorA alpha destination factor operator.
References _mesa_debug(), _mesa_enum_to_string(), _NEW_COLOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, num_buffers(), update_uses_dual_src(), validate_blend_factors(), and VERBOSE_API.
Referenced by _mesa_BlendFunc(), and _mesa_PopAttrib().
_mesa_BlendFuncSeparateiARB()
void GLAPIENTRY _mesa_BlendFuncSeparateiARB (GLuint buf, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Set separate blend source/dest factors for one color buffer/target.
References _mesa_error(), _NEW_COLOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, update_uses_dual_src(), and validate_blend_factors().
Referenced by _mesa_BlendFunciARB(), and _mesa_PopAttrib().
_mesa_ClampColor()
void GLAPIENTRY _mesa_ClampColor (GLenum target, GLenum clamp)
References _mesa_enum_to_string(), _mesa_error(), _mesa_update_clamp_fragment_color(), _mesa_update_clamp_vertex_color(), _NEW_FRAG_CLAMP, _NEW_LIGHT, API_OPENGL_CORE, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
Referenced by _mesa_PopAttrib().
_mesa_ColorMask()
void GLAPIENTRY _mesa_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
Enable or disable writing of frame buffer color components.
Parameters
red whether to mask writing of the red color component.
green whether to mask writing of the green color component.
blue whether to mask writing of the blue color component.
alpha whether to mask writing of the alpha color component.
See also
glColorMask().
Sets the appropriate value of gl_colorbuffer_attrib::ColorMask. On a change, flushes the vertices and notifies the driver via the dd_function_table::ColorMask callback.
References _mesa_debug(), _NEW_COLOR, ACOMP, BCOMP, COPY_4UBV(), FLUSH_VERTICES, GCOMP, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, RCOMP, TEST_EQ_4V, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_ColorMaski()
void GLAPIENTRY _mesa_ColorMaski (GLuint buf, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
For GL_EXT_draw_buffers2 and GL3.
References _mesa_debug(), _mesa_error(), _NEW_COLOR, ACOMP, BCOMP, COPY_4UBV(), FLUSH_VERTICES, GCOMP, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, RCOMP, TEST_EQ_4V, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_get_clamp_fragment_color()
GLboolean _mesa_get_clamp_fragment_color (const struct gl_context * ctx, const struct gl_framebuffer * drawFb)
References gl_colorbuffer_attrib::ClampFragmentColor, gl_context::Color, and get_clamp_color().
Referenced by _mesa_GetTexEnvfv(), _mesa_update_clamp_fragment_color(), find_custom_value(), and get_tex_parameterfv().
_mesa_get_clamp_read_color()
GLboolean _mesa_get_clamp_read_color (const struct gl_context * ctx, const struct gl_framebuffer * readFb)
References gl_colorbuffer_attrib::ClampReadColor, gl_context::Color, and get_clamp_color().
Referenced by _mesa_get_readpixels_transfer_ops().
_mesa_get_clamp_vertex_color()
GLboolean _mesa_get_clamp_vertex_color (const struct gl_context * ctx, const struct gl_framebuffer * drawFb)
References gl_light_attrib::ClampVertexColor, get_clamp_color(), and gl_context::Light.
Referenced by _mesa_update_clamp_vertex_color().
_mesa_get_render_format()
mesa_format _mesa_get_render_format (const struct gl_context * ctx, mesa_format format)
Returns an appropriate mesa_format for color rendering based on the GL_FRAMEBUFFER_SRGB state.
Some drivers implement GL_FRAMEBUFFER_SRGB using a flag on the blend state (which GL_FRAMEBUFFER_SRGB maps to reasonably), but some have to do so by overriding the format of the surface. This is a helper for doing the surface format override variant.
References _mesa_get_srgb_format_linear(), gl_context::Color, and gl_colorbuffer_attrib::sRGBEnabled.
_mesa_IndexMask()
void GLAPIENTRY _mesa_IndexMask (GLuint mask)
References _NEW_COLOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_PopAttrib().
_mesa_init_color()
void _mesa_init_color (struct gl_context * ctx)
Initialization of the context's Color attribute group.
Parameters
ctx GL context.
Initializes the related fields in the context color attribute group, __struct gl_contextRec::Color.
References gl_colorbuffer_attrib::_ClampFragmentColor, _mesa_is_gles(), gl_colorbuffer_attrib::AlphaEnabled, gl_colorbuffer_attrib::AlphaFunc, gl_colorbuffer_attrib::AlphaRef, gl_context::API, API_OPENGL_COMPAT, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendCoherent, gl_colorbuffer_attrib::BlendColor, gl_colorbuffer_attrib::BlendColorUnclamped, gl_colorbuffer_attrib::BlendEnabled, gl_colorbuffer_attrib::ClampFragmentColor, gl_colorbuffer_attrib::ClampReadColor, gl_colorbuffer_attrib::ClearColor, gl_colorbuffer_attrib::ClearIndex, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_colorbuffer_attrib::DitherFlag, gl_config::doubleBufferMode, gl_colorbuffer_attrib::DrawBuffer, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_color_union::f, GLuint, gl_colorbuffer_attrib::IndexLogicOpEnabled, gl_colorbuffer_attrib::IndexMask, gl_colorbuffer_attrib::LogicOp, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, gl_colorbuffer_attrib::sRGBEnabled, and gl_context::Visual.
Referenced by init_attrib_groups().
_mesa_LogicOp()
void GLAPIENTRY _mesa_LogicOp (GLenum opcode)
Specify a logic pixel operation for color index rendering.
Parameters
opcode operation.
Verifies that opcode is a valid enum and updates gl_colorbuffer_attrib::LogicOp. On a change, flushes the vertices and notifies the driver via the dd_function_table::LogicOpcode callback.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_update_clamp_fragment_color()
void _mesa_update_clamp_fragment_color (struct gl_context * ctx, const struct gl_framebuffer * drawFb)
Update the ctx->Color._ClampFragmentColor field.
References gl_colorbuffer_attrib::_ClampFragmentColor, gl_framebuffer::_HasSNormOrFloatColorBuffer, gl_framebuffer::_IntegerBuffers, _mesa_get_clamp_fragment_color(), and gl_context::Color.
Referenced by _mesa_ClampColor(), and _mesa_update_framebuffer().
_mesa_update_clamp_vertex_color()
void _mesa_update_clamp_vertex_color (struct gl_context * ctx, const struct gl_framebuffer * drawFb)
Update the ctx->Color._ClampVertexColor field.
References gl_light_attrib::_ClampVertexColor, _mesa_get_clamp_vertex_color(), and gl_context::Light.
Referenced by _mesa_ClampColor(), and _mesa_update_framebuffer().