Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
blit.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include "context.h"
#include "enums.h"
#include "blit.h"
#include "fbobject.h"
#include "framebuffer.h"
#include "glformats.h"
#include "mtypes.h"
#include "macros.h"
#include "state.h"
Macros
#define DEBUG_BLIT 0
Set this to 1 to debug/log glBlitFramebuffer() calls.
Functions
static const struct gl_renderbuffer_attachment * find_attachment (const struct gl_framebuffer *fb, const struct gl_renderbuffer *rb)
bool _mesa_regions_overlap (int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1)
static GLboolean compatible_color_datatypes (mesa_format srcFormat, mesa_format dstFormat)
Helper function for checking if the datatypes of color buffers are compatible for glBlitFramebuffer.
static GLboolean compatible_resolve_formats (const struct gl_renderbuffer *readRb, const struct gl_renderbuffer *drawRb)
static GLboolean is_valid_blit_filter (const struct gl_context *ctx, GLenum filter)
void _mesa_blit_framebuffer (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter, const char *func)
void GLAPIENTRY _mesa_BlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Blit rectangular region, optionally from one framebuffer to another.
void GLAPIENTRY _mesa_BlitNamedFramebuffer (GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Macro Definition Documentation
DEBUG_BLIT
#define DEBUG_BLIT 0
Set this to 1 to debug/log glBlitFramebuffer() calls.
Referenced by _mesa_blit_framebuffer().
Function Documentation
_mesa_blit_framebuffer()
void _mesa_blit_framebuffer (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter, const char * func)
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_ColorReadBuffer, _mesa_enum_to_string(), _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_datatype(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_update_draw_buffer_bounds(), _mesa_update_framebuffer(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Status, gl_framebuffer::Attachment, dd_function_table::BlitFramebuffer, BUFFER_DEPTH, BUFFER_STENCIL, compatible_color_datatypes(), compatible_resolve_formats(), gl_renderbuffer_attachment::CubeMapFace, DEBUG_BLIT, gl_context::Driver, find_attachment(), FLUSH_VERTICES, gl_renderbuffer::Format, GLAPIENTRY, GLuint, gl_renderbuffer::Height, is_valid_blit_filter(), gl_texture_object::Name, gl_renderbuffer::Name, gl_framebuffer::Name, gl_renderbuffer_attachment::Renderbuffer, gl_config::samples, gl_texture_object::Target, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_framebuffer::Visual, and gl_renderbuffer::Width.
Referenced by _mesa_BlitFramebuffer(), and _mesa_BlitNamedFramebuffer().
_mesa_BlitFramebuffer()
void GLAPIENTRY _mesa_BlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Blit rectangular region, optionally from one framebuffer to another.
Note, if the src buffer is multisampled and the dest is not, this is when the samples must be resolved to a single color.
References _mesa_blit_framebuffer(), _mesa_debug(), _mesa_enum_to_string(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_BlitNamedFramebuffer()
void GLAPIENTRY _mesa_BlitNamedFramebuffer (GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
References _mesa_blit_framebuffer(), _mesa_debug(), _mesa_enum_to_string(), _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
_mesa_regions_overlap()
bool _mesa_regions_overlap (int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1)
Returns
true if two regions overlap, false otherwise
compatible_color_datatypes()
static GLboolean compatible_color_datatypes (mesa_format srcFormat, mesa_format dstFormat) static
Helper function for checking if the datatypes of color buffers are compatible for glBlitFramebuffer.
From the 3.1 spec, page 198:
"GL_INVALID_OPERATION is generated if mask contains GL_COLOR_BUFFER_BIT and any of the following conditions hold:
The read buffer contains fixed-point or floating-point values and any draw buffer contains neither fixed-point nor floating-point values.
The read buffer contains unsigned integer values and any draw buffer does not contain unsigned integer values.
The read buffer contains signed integer values and any draw buffer does not contain signed integer values."
References _mesa_get_format_datatype().
Referenced by _mesa_blit_framebuffer().
compatible_resolve_formats()
static GLboolean compatible_resolve_formats (const struct gl_renderbuffer * readRb, const struct gl_renderbuffer * drawRb) static
References _mesa_get_linear_internalformat(), _mesa_get_nongeneric_internalformat(), and gl_renderbuffer::InternalFormat.
Referenced by _mesa_blit_framebuffer().
find_attachment()
static const struct gl_renderbuffer_attachment* find_attachment (const struct gl_framebuffer * fb, const struct gl_renderbuffer * rb) static
References gl_framebuffer::Attachment, GLuint, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_blit_framebuffer().
is_valid_blit_filter()
static GLboolean is_valid_blit_filter (const struct gl_context * ctx, GLenum filter) static
References gl_extensions::EXT_framebuffer_multisample_blit_scaled, and gl_context::Extensions.
Referenced by _mesa_blit_framebuffer().