Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
bufferobj.c File Reference
Functions for the GL_ARB_vertex/pixel_buffer_object extensions.
#include <stdbool.h>
#include <inttypes.h>
#include "util/debug.h"
#include "glheader.h"
#include "enums.h"
#include "hash.h"
#include "imports.h"
#include "context.h"
#include "bufferobj.h"
#include "mtypes.h"
#include "teximage.h"
#include "glformats.h"
#include "texstore.h"
#include "transformfeedback.h"
#include "varray.h"
Macros
#define BUFFER_WARNING_CALL_COUNT 4
We count the number of buffer modification calls to check for inefficient buffer use.
#define BUFFER_USAGE_WARNING(CTX, FMT, ...)
Functions
static void buffer_usage_warning (struct gl_context *ctx, GLuint *id, const char *fmt,...)
Helper to warn of possible performance issues, such as frequently updating a buffer created with GL_STATIC_DRAW.
static struct gl_buffer_object ** get_buffer_target (struct gl_context *ctx, GLenum target)
Return pointer to address of a buffer object target.
static struct gl_buffer_object * get_buffer (struct gl_context *ctx, const char *func, GLenum target, GLenum error)
Get the buffer object bound to the specified target in a GL context.
static GLenum simplified_access_mode (struct gl_context *ctx, GLbitfield access)
Convert a GLbitfield describing the mapped buffer access flags into one of GL_READ_WRITE, GL_READ_ONLY, or GL_WRITE_ONLY.
static bool bufferobj_range_mapped (const struct gl_buffer_object *obj, GLintptr offset, GLsizeiptr size)
Test if the buffer is mapped, and if so, if the mapped range overlaps the given range.
static bool buffer_object_subdata_range_good (struct gl_context *ctx, const struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, bool mappedRange, const char *caller)
Tests the subdata range parameters and sets the GL error code for glBufferSubDataARB, glGetBufferSubDataARB and glClearBufferSubData.
static mesa_format validate_clear_buffer_format (struct gl_context *ctx, GLenum internalformat, GLenum format, GLenum type, const char *caller)
Test the format and type parameters and set the GL error code for glClearBufferData and glClearBufferSubData.
static bool convert_clear_buffer_data (struct gl_context *ctx, mesa_format internalformat, GLubyte *clearValue, GLenum format, GLenum type, const GLvoid *data, const char *caller)
Convert user-specified clear value to the specified internal format.
static struct gl_buffer_object * _mesa_new_buffer_object (struct gl_context *ctx, GLuint name)
Allocate and initialize a new buffer object.
void _mesa_delete_buffer_object (struct gl_context *ctx, struct gl_buffer_object *bufObj)
Delete a buffer object.
void _mesa_reference_buffer_object_ (struct gl_context *ctx, struct gl_buffer_object **ptr, struct gl_buffer_object *bufObj)
Set ptr to bufObj w/ reference counting.
static bool get_no_minmax_cache ()
Get the value of MESA_NO_MINMAX_CACHE.
void _mesa_initialize_buffer_object (struct gl_context *ctx, struct gl_buffer_object *obj, GLuint name)
Initialize a buffer object to default values.
static void count_buffer_size (GLuint key, void *data, void *userData)
Callback called from _mesa_HashWalk()
GLuint _mesa_total_buffer_object_memory (struct gl_context *ctx)
Compute total size (in bytes) of all buffer objects for the given context.
static GLboolean buffer_data_fallback (struct gl_context *ctx, GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage, GLenum storageFlags, struct gl_buffer_object *bufObj)
Allocate space for and store data in a buffer object.
static void buffer_sub_data_fallback (struct gl_context *ctx, GLintptr offset, GLsizeiptr size, const GLvoid *data, struct gl_buffer_object *bufObj)
Replace data in a subrange of buffer object.
static void _mesa_buffer_get_subdata (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *bufObj)
Retrieve data from a subrange of buffer object.
void _mesa_ClearBufferSubData_sw (struct gl_context *ctx, GLintptr offset, GLsizeiptr size, const GLvoid *clearValue, GLsizeiptr clearValueSize, struct gl_buffer_object *bufObj)
Clear a subrange of the buffer object with copies of the supplied data.
static void * map_buffer_range_fallback (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *bufObj, gl_map_buffer_index index)
Default fallback for dd_function_table::MapBufferRange().
static void flush_mapped_buffer_range_fallback (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj, gl_map_buffer_index index)
Default fallback for dd_function_table::FlushMappedBufferRange().
static GLboolean unmap_buffer_fallback (struct gl_context *ctx, struct gl_buffer_object *bufObj, gl_map_buffer_index index)
Default callback for dd_function_table::UnmapBuffer().
static void copy_buffer_sub_data_fallback (struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
Default fallback for dd_function_table::CopyBufferSubData().
void _mesa_init_buffer_objects (struct gl_context *ctx)
Initialize the state associated with buffer objects.
void _mesa_free_buffer_objects (struct gl_context *ctx)
bool _mesa_handle_bind_buffer_gen (struct gl_context *ctx, GLuint buffer, struct gl_buffer_object **buf_handle, const char *caller)
static void bind_buffer_object (struct gl_context *ctx, struct gl_buffer_object **bindTarget, GLuint buffer)
Bind the specified target to buffer for the specified context.
void _mesa_update_default_objects_buffer_objects (struct gl_context *ctx)
Update the default buffer objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
struct gl_buffer_object * _mesa_lookup_bufferobj (struct gl_context *ctx, GLuint buffer)
Return the gl_buffer_object for the given ID.
struct gl_buffer_object * _mesa_lookup_bufferobj_locked (struct gl_context *ctx, GLuint buffer)
struct gl_buffer_object * _mesa_lookup_bufferobj_err (struct gl_context *ctx, GLuint buffer, const char *caller)
A convenience function for direct state access functions that throws GL_INVALID_OPERATION if buffer is not the name of an existing buffer object.
struct gl_buffer_object * _mesa_multi_bind_lookup_bufferobj (struct gl_context *ctx, const GLuint *buffers, GLuint index, const char *caller)
Look up a buffer object for a multi-bind function.
static void unbind (struct gl_context *ctx, struct gl_vertex_array_object *vao, unsigned index, struct gl_buffer_object *obj)
If *ptr points to obj, set ptr = the Null/default buffer object.
void _mesa_init_buffer_object_functions (struct dd_function_table *driver)
Plug default/fallback buffer object functions into the device driver hooks.
void _mesa_buffer_unmap_all_mappings (struct gl_context *ctx, struct gl_buffer_object *bufObj)
void GLAPIENTRY _mesa_BindBuffer (GLenum target, GLuint buffer)
void GLAPIENTRY _mesa_DeleteBuffers (GLsizei n, const GLuint *ids)
Delete a set of buffer objects.
static void create_buffers (GLsizei n, GLuint *buffers, bool dsa)
This is the implementation for glGenBuffers and glCreateBuffers.
void GLAPIENTRY _mesa_GenBuffers (GLsizei n, GLuint *buffers)
Generate a set of unique buffer object IDs and store them in buffers.
void GLAPIENTRY _mesa_CreateBuffers (GLsizei n, GLuint *buffers)
Create a set of buffer objects and store their unique IDs in buffers.
GLboolean GLAPIENTRY _mesa_IsBuffer (GLuint id)
Determine if ID is the name of a buffer object.
void _mesa_buffer_storage (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum target, GLsizeiptr size, const GLvoid *data, GLbitfield flags, const char *func)
void GLAPIENTRY _mesa_BufferStorage (GLenum target, GLsizeiptr size, const GLvoid *data, GLbitfield flags)
void GLAPIENTRY _mesa_NamedBufferStorage (GLuint buffer, GLsizeiptr size, const GLvoid *data, GLbitfield flags)
void _mesa_buffer_data (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage, const char *func)
void GLAPIENTRY _mesa_BufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
void GLAPIENTRY _mesa_NamedBufferData (GLuint buffer, GLsizeiptr size, const GLvoid *data, GLenum usage)
void _mesa_buffer_sub_data (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, const GLvoid *data, const char *func)
Implementation for glBufferSubData and glNamedBufferSubData.
void GLAPIENTRY _mesa_BufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data)
void GLAPIENTRY _mesa_NamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, const GLvoid *data)
void GLAPIENTRY _mesa_GetBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, GLvoid *data)
void GLAPIENTRY _mesa_GetNamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, GLvoid *data)
void _mesa_clear_buffer_sub_data (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid *data, const char *func, bool subdata)
void GLAPIENTRY _mesa_ClearBufferData (GLenum target, GLenum internalformat, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ClearNamedBufferData (GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ClearBufferSubData (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ClearNamedBufferSubData (GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid *data)
GLboolean _mesa_unmap_buffer (struct gl_context *ctx, struct gl_buffer_object *bufObj, const char *func)
GLboolean GLAPIENTRY _mesa_UnmapBuffer (GLenum target)
GLboolean GLAPIENTRY _mesa_UnmapNamedBuffer (GLuint buffer)
static bool get_buffer_parameter (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum pname, GLint64 *params, const char *func)
void GLAPIENTRY _mesa_GetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetBufferParameteri64v (GLenum target, GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_GetNamedBufferParameteriv (GLuint buffer, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetNamedBufferParameteri64v (GLuint buffer, GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_GetBufferPointerv (GLenum target, GLenum pname, GLvoid **params)
void GLAPIENTRY _mesa_GetNamedBufferPointerv (GLuint buffer, GLenum pname, GLvoid **params)
void _mesa_copy_buffer_sub_data (struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size, const char *func)
void GLAPIENTRY _mesa_CopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void GLAPIENTRY _mesa_CopyNamedBufferSubData (GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void * _mesa_map_buffer_range (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr length, GLbitfield access, const char *func)
void *GLAPIENTRY _mesa_MapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
void *GLAPIENTRY _mesa_MapNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access)
static bool get_map_buffer_access_flags (struct gl_context *ctx, GLenum access, GLbitfield *flags)
Converts GLenum access from MapBuffer and MapNamedBuffer into flags for input to _mesa_map_buffer_range.
void *GLAPIENTRY _mesa_MapBuffer (GLenum target, GLenum access)
void *GLAPIENTRY _mesa_MapNamedBuffer (GLuint buffer, GLenum access)
void _mesa_flush_mapped_buffer_range (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr length, const char *func)
void GLAPIENTRY _mesa_FlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length)
void GLAPIENTRY _mesa_FlushMappedNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length)
static void set_ubo_binding (struct gl_context *ctx, struct gl_uniform_buffer_binding *binding, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize)
Binds a buffer object to a uniform buffer binding point.
static void set_ssbo_binding (struct gl_context *ctx, struct gl_shader_storage_buffer_binding *binding, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize)
Binds a buffer object to a shader storage buffer binding point.
static void bind_uniform_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize)
Binds a buffer object to a uniform buffer binding point.
static void bind_shader_storage_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize)
Binds a buffer object to a shader storage buffer binding point.
static void bind_buffer_range_uniform_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size)
Bind a region of a buffer object to a uniform block binding point.
static void bind_buffer_range_shader_storage_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size)
Bind a region of a buffer object to a shader storage block binding point.
static void bind_buffer_base_uniform_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj)
Bind a buffer object to a uniform block binding point.
static void bind_buffer_base_shader_storage_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj)
Bind a buffer object to a shader storage block binding point.
static void set_atomic_buffer_binding (struct gl_context *ctx, struct gl_atomic_buffer_binding *binding, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size)
Binds a buffer object to an atomic buffer binding point.
static void bind_atomic_buffer (struct gl_context *ctx, unsigned index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, const char *name)
Binds a buffer object to an atomic buffer binding point.
static bool bind_buffers_check_offset_and_size (struct gl_context *ctx, GLuint index, const GLintptr *offsets, const GLsizeiptr *sizes)
static bool error_check_bind_uniform_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const char *caller)
static bool error_check_bind_shader_storage_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const char *caller)
static void unbind_uniform_buffers (struct gl_context *ctx, GLuint first, GLsizei count)
Unbind all uniform buffers in the range <first> through <first>+<count>-1.
static void unbind_shader_storage_buffers (struct gl_context *ctx, GLuint first, GLsizei count)
Unbind all shader storage buffers in the range <first> through <first>+<count>-1.
static void bind_uniform_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const GLuint *buffers, bool range, const GLintptr *offsets, const GLsizeiptr *sizes, const char *caller)
static void bind_shader_storage_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const GLuint *buffers, bool range, const GLintptr *offsets, const GLsizeiptr *sizes, const char *caller)
static bool error_check_bind_xfb_buffers (struct gl_context *ctx, struct gl_transform_feedback_object *tfObj, GLuint first, GLsizei count, const char *caller)
static void unbind_xfb_buffers (struct gl_context *ctx, struct gl_transform_feedback_object *tfObj, GLuint first, GLsizei count)
Unbind all transform feedback buffers in the range <first> through <first>+<count>-1.
static void bind_xfb_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const GLuint *buffers, bool range, const GLintptr *offsets, const GLsizeiptr *sizes, const char *caller)
static bool error_check_bind_atomic_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const char *caller)
static void unbind_atomic_buffers (struct gl_context *ctx, GLuint first, GLsizei count)
Unbind all atomic counter buffers in the range <first> through <first>+<count>-1.
static void bind_atomic_buffers (struct gl_context *ctx, GLuint first, GLsizei count, const GLuint *buffers, bool range, const GLintptr *offsets, const GLsizeiptr *sizes, const char *caller)
void GLAPIENTRY _mesa_BindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
void GLAPIENTRY _mesa_BindBufferBase (GLenum target, GLuint index, GLuint buffer)
void GLAPIENTRY _mesa_BindBuffersRange (GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes)
void GLAPIENTRY _mesa_BindBuffersBase (GLenum target, GLuint first, GLsizei count, const GLuint *buffers)
void GLAPIENTRY _mesa_InvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length)
void GLAPIENTRY _mesa_InvalidateBufferData (GLuint buffer)
static void buffer_page_commitment (struct gl_context *ctx, struct gl_buffer_object *bufferObj, GLintptr offset, GLsizeiptr size, GLboolean commit, const char *func)
void GLAPIENTRY _mesa_BufferPageCommitmentARB (GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit)
void GLAPIENTRY _mesa_NamedBufferPageCommitmentARB (GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit)
Variables
static struct gl_buffer_object DummyBufferObject
Used as a placeholder for buffer objects between glGenBuffers() and glBindBuffer() so that glIsBuffer() can work correctly.
Detailed Description
Functions for the GL_ARB_vertex/pixel_buffer_object extensions.
Author
Brian Paul, Ian Romanick
Macro Definition Documentation
BUFFER_USAGE_WARNING
#define BUFFER_USAGE_WARNING (CTX, FMT, ...)
Value:
do { \
      static GLuint id = 0; \
      buffer_usage_warning(CTX, &id, FMT, ##__VA_ARGS__); \
   } while (0)
Referenced by _mesa_buffer_sub_data(), and _mesa_map_buffer_range().
BUFFER_WARNING_CALL_COUNT
#define BUFFER_WARNING_CALL_COUNT 4
We count the number of buffer modification calls to check for inefficient buffer use.
This is the number of such calls before we issue a warning.
Referenced by _mesa_buffer_sub_data(), and _mesa_map_buffer_range().
Function Documentation
_mesa_BindBuffer()
void GLAPIENTRY _mesa_BindBuffer (GLenum target, GLuint buffer)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), bind_buffer_object(), get_buffer_target(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object(), and restore_array_attrib().
_mesa_BindBufferBase()
void GLAPIENTRY _mesa_BindBufferBase (GLenum target, GLuint index, GLuint buffer)
References _mesa_bind_buffer_base_transform_feedback(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_handle_bind_buffer_gen(), _mesa_lookup_bufferobj(), bind_atomic_buffer(), bind_buffer_base_shader_storage_buffer(), bind_buffer_base_uniform_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_DeleteBuffers(), and _mesa_reference_buffer_object().
_mesa_BindBufferRange()
void GLAPIENTRY _mesa_BindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
References _mesa_bind_buffer_range_transform_feedback(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_handle_bind_buffer_gen(), _mesa_lookup_bufferobj(), bind_atomic_buffer(), bind_buffer_range_shader_storage_buffer(), bind_buffer_range_uniform_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object().
_mesa_BindBuffersBase()
void GLAPIENTRY _mesa_BindBuffersBase (GLenum target, GLuint first, GLsizei count, const GLuint * buffers)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object().
_mesa_BindBuffersRange()
void GLAPIENTRY _mesa_BindBuffersRange (GLenum target, GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizeiptr * sizes)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object().
_mesa_buffer_data()
void _mesa_buffer_data (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage, const char * func)
References _mesa_buffer_unmap_all_mappings(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _NEW_BUFFER_OBJECT, gl_context::API, API_OPENGLES, dd_function_table::BufferData, gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, gl_buffer_object::Immutable, MESA_VERBOSE, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::Name, VERBOSE_API, and gl_buffer_object::Written.
Referenced by _mesa_BufferData(), _mesa_NamedBufferData(), and _mesa_reference_buffer_object().
_mesa_buffer_get_subdata()
static void _mesa_buffer_get_subdata (struct gl_context * ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid * data, struct gl_buffer_object * bufObj) static
Retrieve data from a subrange of buffer object.
If the data range specified by size + offset extends beyond the end of the buffer or if data is NULL, no copy is performed.
This is the default callback for dd_function_table::GetBufferSubData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
target Buffer object target on which to operate.
offset Offset of the first byte to be fetched.
size Size, in bytes, of the data range.
data Destination for data
bufObj Object to be used.
See also
glBufferGetSubDataARB, dd_function_table::GetBufferSubData.
References gl_buffer_object::Data, gl_buffer_object::Size, and void.
Referenced by _mesa_init_buffer_object_functions().
_mesa_buffer_storage()
void _mesa_buffer_storage (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum target, GLsizeiptr size, const GLvoid * data, GLbitfield flags, const char * func)
References _mesa_buffer_unmap_all_mappings(), _mesa_error(), _NEW_BUFFER_OBJECT, gl_extensions::ARB_sparse_buffer, dd_function_table::BufferData, gl_context::Driver, gl_context::Extensions, FLUSH_VERTICES, GLAPIENTRY, gl_buffer_object::Immutable, gl_buffer_object::MinMaxCacheDirty, and gl_buffer_object::Written.
Referenced by _mesa_BufferStorage(), _mesa_NamedBufferStorage(), and _mesa_reference_buffer_object().
_mesa_buffer_sub_data()
void _mesa_buffer_sub_data (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, const GLvoid * data, const char * func)
Implementation for glBufferSubData and glNamedBufferSubData.
Parameters
ctx GL context.
bufObj The buffer object.
offset Offset of the first byte of the subdata range.
size Size, in bytes, of the subdata range.
data The data store.
func Name of calling function for recording errors.
References _mesa_enum_to_string(), _mesa_error(), buffer_object_subdata_range_good(), BUFFER_USAGE_WARNING, BUFFER_WARNING_CALL_COUNT, dd_function_table::BufferSubData, gl_context::Driver, GLAPIENTRY, gl_buffer_object::Immutable, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::Name, gl_buffer_object::NumSubDataCalls, gl_buffer_object::StorageFlags, gl_buffer_object::Usage, and gl_buffer_object::Written.
Referenced by _mesa_BufferSubData(), _mesa_NamedBufferSubData(), and _mesa_reference_buffer_object().
_mesa_buffer_unmap_all_mappings()
void _mesa_buffer_unmap_all_mappings (struct gl_context * ctx, struct gl_buffer_object * bufObj)
References _mesa_bufferobj_mapped(), gl_buffer_mapping::AccessFlags, gl_context::Driver, GLAPIENTRY, MAP_COUNT, gl_buffer_object::Mappings, gl_buffer_mapping::Pointer, and dd_function_table::UnmapBuffer.
Referenced by _mesa_buffer_data(), _mesa_buffer_storage(), _mesa_DeleteBuffers(), _mesa_reference_buffer_object(), and delete_bufferobj_cb().
_mesa_BufferData()
void GLAPIENTRY _mesa_BufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
References _mesa_buffer_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_BufferPageCommitmentARB()
void GLAPIENTRY _mesa_BufferPageCommitmentARB (GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit)
References buffer_page_commitment(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_BufferStorage()
void GLAPIENTRY _mesa_BufferStorage (GLenum target, GLsizeiptr size, const GLvoid * data, GLbitfield flags)
References _mesa_buffer_storage(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_BufferSubData()
void GLAPIENTRY _mesa_BufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data)
References _mesa_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_clear_buffer_sub_data()
void _mesa_clear_buffer_sub_data (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid * data, const char * func, bool subdata)
Parameters
subdata true if caller is *SubData, false if *Data
References _mesa_error(), _mesa_get_format_bytes(), buffer_object_subdata_range_good(), dd_function_table::ClearBufferSubData, convert_clear_buffer_data(), gl_context::Driver, GLAPIENTRY, MAX_PIXEL_BYTES, MESA_FORMAT_NONE, gl_buffer_object::MinMaxCacheDirty, and validate_clear_buffer_format().
Referenced by _mesa_ClearBufferData(), _mesa_ClearBufferSubData(), _mesa_ClearNamedBufferData(), _mesa_ClearNamedBufferSubData(), and _mesa_reference_buffer_object().
_mesa_ClearBufferData()
void GLAPIENTRY _mesa_ClearBufferData (GLenum target, GLenum internalformat, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_ClearBufferSubData()
void GLAPIENTRY _mesa_ClearBufferSubData (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_ClearBufferSubData_sw()
void _mesa_ClearBufferSubData_sw (struct gl_context * ctx, GLintptr offset, GLsizeiptr size, const GLvoid * clearValue, GLsizeiptr clearValueSize, struct gl_buffer_object * bufObj)
Clear a subrange of the buffer object with copies of the supplied data.
If data is NULL the buffer is filled with zeros.
This is the default callback for dd_function_table::ClearBufferSubData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
offset Offset of the first byte to be cleared.
size Size, in bytes, of the to be cleared range.
clearValue Source of the data.
clearValueSize Size, in bytes, of the supplied data.
bufObj Object to be cleared.
See also
glClearBufferSubData, glClearBufferData and dd_function_table::ClearBufferSubData.
References _mesa_error(), gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and dd_function_table::UnmapBuffer.
Referenced by _mesa_init_buffer_object_functions(), and _mesa_reference_buffer_object().
_mesa_ClearNamedBufferData()
void GLAPIENTRY _mesa_ClearNamedBufferData (GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_ClearNamedBufferSubData()
void GLAPIENTRY _mesa_ClearNamedBufferSubData (GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_copy_buffer_sub_data()
void _mesa_copy_buffer_sub_data (struct gl_context * ctx, struct gl_buffer_object * src, struct gl_buffer_object * dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size, const char * func)
References _mesa_check_disallowed_mapping(), _mesa_error(), dd_function_table::CopyBufferSubData, gl_context::Driver, GLAPIENTRY, gl_buffer_object::MinMaxCacheDirty, and gl_buffer_object::Size.
Referenced by _mesa_CopyBufferSubData(), _mesa_CopyNamedBufferSubData(), and _mesa_reference_buffer_object().
_mesa_CopyBufferSubData()
void GLAPIENTRY _mesa_CopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
References _mesa_copy_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_CopyNamedBufferSubData()
void GLAPIENTRY _mesa_CopyNamedBufferSubData (GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
References _mesa_copy_buffer_sub_data(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_CreateBuffers()
void GLAPIENTRY _mesa_CreateBuffers (GLsizei n, GLuint * buffers)
Create a set of buffer objects and store their unique IDs in buffers.
Parameters
n Number of IDs to generate.
buffers Array of n locations to store the IDs.
References create_buffers(), and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_delete_buffer_object()
void _mesa_delete_buffer_object (struct gl_context * ctx, struct gl_buffer_object * bufObj)
Delete a buffer object.
Default callback for the dd_function_table::DeleteBuffer() hook.
References _mesa_align_free(), gl_buffer_object::Data, gl_buffer_object::Label, gl_buffer_object::Mutex, gl_buffer_object::Name, gl_buffer_object::RefCount, vbo_delete_minmax_cache(), and void.
Referenced by _mesa_init_buffer_object_functions(), and _mesa_is_bufferobj().
_mesa_DeleteBuffers()
void GLAPIENTRY _mesa_DeleteBuffers (GLsizei n, const GLuint * ids)
Delete a set of buffer objects.
Parameters
n Number of buffer objects to delete.
ids Array of n buffer object IDs.
References _mesa_BindBufferBase(), _mesa_buffer_unmap_all_mappings(), _mesa_error(), _mesa_HashLockMutex(), _mesa_HashRemoveLocked(), _mesa_HashUnlockMutex(), _mesa_lookup_bufferobj_locked(), _mesa_reference_buffer_object(), bind_buffer_object(), gl_vertex_array_object::BufferBinding, gl_buffer_object::DeletePending, DummyBufferObject, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, gl_vertex_array_object::IndexBufferObj, MAX_FEEDBACK_BUFFERS, gl_buffer_object::Name, and unbind().
Referenced by _mesa_reference_buffer_object().
_mesa_flush_mapped_buffer_range()
void _mesa_flush_mapped_buffer_range (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr length, const char * func)
References _mesa_bufferobj_mapped(), _mesa_error(), gl_buffer_mapping::AccessFlags, gl_extensions::ARB_map_buffer_range, gl_context::Driver, gl_context::Extensions, dd_function_table::FlushMappedBufferRange, GLAPIENTRY, gl_buffer_mapping::Length, MAP_USER, and gl_buffer_object::Mappings.
Referenced by _mesa_FlushMappedBufferRange(), _mesa_FlushMappedNamedBufferRange(), and _mesa_reference_buffer_object().
_mesa_FlushMappedBufferRange()
void GLAPIENTRY _mesa_FlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length)
References _mesa_flush_mapped_buffer_range(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_FlushMappedNamedBufferRange()
void GLAPIENTRY _mesa_FlushMappedNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length)
References _mesa_flush_mapped_buffer_range(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_free_buffer_objects()
void _mesa_free_buffer_objects (struct gl_context * ctx)
References _mesa_reference_buffer_object(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::AtomicBuffer, gl_context::AtomicBufferBindings, gl_uniform_buffer_binding::BufferObject, gl_shader_storage_buffer_binding::BufferObject, gl_atomic_buffer_binding::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_context::DispatchIndirectBuffer, gl_context::DrawIndirectBuffer, GLuint, MAX_COMBINED_ATOMIC_BUFFERS, MAX_COMBINED_SHADER_STORAGE_BUFFERS, MAX_COMBINED_UNIFORM_BUFFERS, gl_context::ParameterBuffer, gl_context::QueryBuffer, gl_context::ShaderStorageBuffer, gl_context::ShaderStorageBufferBindings, gl_context::UniformBuffer, and gl_context::UniformBufferBindings.
Referenced by _mesa_free_context_data(), and _mesa_is_bufferobj().
_mesa_GenBuffers()
void GLAPIENTRY _mesa_GenBuffers (GLsizei n, GLuint * buffers)
Generate a set of unique buffer object IDs and store them in buffers.
Parameters
n Number of IDs to generate.
buffers Array of n locations to store the IDs.
References create_buffers(), and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferParameteri64v()
void GLAPIENTRY _mesa_GetBufferParameteri64v (GLenum target, GLenum pname, GLint64 * params)
References get_buffer(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferParameteriv()
void GLAPIENTRY _mesa_GetBufferParameteriv (GLenum target, GLenum pname, GLint * params)
References get_buffer(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferPointerv()
void GLAPIENTRY _mesa_GetBufferPointerv (GLenum target, GLenum pname, GLvoid ** params)
References _mesa_error(), get_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_mapping::Pointer.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferSubData()
void GLAPIENTRY _mesa_GetBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, GLvoid * data)
References buffer_object_subdata_range_good(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferParameteri64v()
void GLAPIENTRY _mesa_GetNamedBufferParameteri64v (GLuint buffer, GLenum pname, GLint64 * params)
References _mesa_lookup_bufferobj_err(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferParameteriv()
void GLAPIENTRY _mesa_GetNamedBufferParameteriv (GLuint buffer, GLenum pname, GLint * params)
References _mesa_lookup_bufferobj_err(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferPointerv()
void GLAPIENTRY _mesa_GetNamedBufferPointerv (GLuint buffer, GLenum pname, GLvoid ** params)
References _mesa_error(), _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_mapping::Pointer.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferSubData()
void GLAPIENTRY _mesa_GetNamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, GLvoid * data)
References _mesa_lookup_bufferobj_err(), buffer_object_subdata_range_good(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_handle_bind_buffer_gen()
bool _mesa_handle_bind_buffer_gen (struct gl_context * ctx, GLuint buffer, struct gl_buffer_object ** buf_handle, const char * caller)
References _mesa_error(), _mesa_HashInsert(), gl_context::API, API_OPENGL_CORE, gl_shared_state::BufferObjects, gl_context::Driver, DummyBufferObject, dd_function_table::NewBufferObject, and gl_context::Shared.
Referenced by _mesa_BindBufferBase(), _mesa_BindBufferRange(), _mesa_is_bufferobj(), bind_buffer_object(), and vertex_array_vertex_buffer().
_mesa_init_buffer_object_functions()
void _mesa_init_buffer_object_functions (struct dd_function_table * driver)
Plug default/fallback buffer object functions into the device driver hooks.
References _mesa_buffer_get_subdata(), _mesa_ClearBufferSubData_sw(), _mesa_delete_buffer_object(), _mesa_new_buffer_object(), buffer_data_fallback(), buffer_sub_data_fallback(), dd_function_table::BufferData, dd_function_table::BufferSubData, dd_function_table::ClearBufferSubData, copy_buffer_sub_data_fallback(), dd_function_table::CopyBufferSubData, dd_function_table::DeleteBuffer, flush_mapped_buffer_range_fallback(), dd_function_table::FlushMappedBufferRange, dd_function_table::GetBufferSubData, map_buffer_range_fallback(), dd_function_table::MapBufferRange, dd_function_table::NewBufferObject, unmap_buffer_fallback(), and dd_function_table::UnmapBuffer.
Referenced by _mesa_reference_buffer_object().
_mesa_init_buffer_objects()
void _mesa_init_buffer_objects (struct gl_context * ctx)
Initialize the state associated with buffer objects.
References _mesa_reference_buffer_object(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::AtomicBuffer, gl_context::AtomicBufferBindings, gl_uniform_buffer_binding::BufferObject, gl_shader_storage_buffer_binding::BufferObject, gl_atomic_buffer_binding::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_context::DispatchIndirectBuffer, gl_context::DrawIndirectBuffer, DummyBufferObject, GLuint, MAX_COMBINED_ATOMIC_BUFFERS, MAX_COMBINED_SHADER_STORAGE_BUFFERS, MAX_COMBINED_UNIFORM_BUFFERS, gl_buffer_object::Mutex, gl_shared_state::NullBufferObj, gl_uniform_buffer_binding::Offset, gl_shader_storage_buffer_binding::Offset, gl_atomic_buffer_binding::Offset, gl_context::ParameterBuffer, gl_context::QueryBuffer, gl_buffer_object::RefCount, gl_context::ShaderStorageBuffer, gl_context::ShaderStorageBufferBindings, gl_context::Shared, gl_uniform_buffer_binding::Size, gl_shader_storage_buffer_binding::Size, gl_atomic_buffer_binding::Size, gl_context::UniformBuffer, and gl_context::UniformBufferBindings.
Referenced by _mesa_is_bufferobj(), and init_attrib_groups().
_mesa_initialize_buffer_object()
void _mesa_initialize_buffer_object (struct gl_context * ctx, struct gl_buffer_object * obj, GLuint name)
Initialize a buffer object to default values.
References get_no_minmax_cache(), gl_buffer_object::Mutex, gl_buffer_object::Name, gl_buffer_object::RefCount, gl_buffer_object::Usage, USAGE_DISABLE_MINMAX_CACHE, and gl_buffer_object::UsageHistory.
Referenced by _mesa_is_bufferobj(), and _mesa_new_buffer_object().
_mesa_InvalidateBufferData()
void GLAPIENTRY _mesa_InvalidateBufferData (GLuint buffer)
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_lookup_bufferobj(), DummyBufferObject, GET_CURRENT_CONTEXT, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_InvalidateBufferSubData()
void GLAPIENTRY _mesa_InvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length)
References _mesa_error(), _mesa_lookup_bufferobj(), gl_buffer_mapping::AccessFlags, bufferobj_range_mapped(), DummyBufferObject, GET_CURRENT_CONTEXT, GLAPIENTRY, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_IsBuffer()
GLboolean GLAPIENTRY _mesa_IsBuffer (GLuint id)
Determine if ID is the name of a buffer object.
Parameters
id ID of the potential buffer object.
Returns
GL_TRUE if id is the name of a buffer object, GL_FALSE otherwise.
References _mesa_lookup_bufferobj(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyBufferObject, and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object(), and restore_array_attrib().
_mesa_lookup_bufferobj()
struct gl_buffer_object* _mesa_lookup_bufferobj (struct gl_context * ctx, GLuint buffer)
Return the gl_buffer_object for the given ID.
Always return NULL for ID 0.
References _mesa_HashLookup(), gl_shared_state::BufferObjects, and gl_context::Shared.
Referenced by _mesa_BindBufferBase(), _mesa_BindBufferOffsetEXT(), _mesa_BindBufferRange(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_is_bufferobj(), _mesa_IsBuffer(), _mesa_lookup_bufferobj_err(), _mesa_NamedBufferPageCommitmentARB(), bind_buffer_object(), buffer_object_purgeable(), buffer_object_unpurgeable(), get_buffer_object_parameteriv(), get_label_pointer(), lookup_transform_feedback_bufferobj_err(), and vertex_array_vertex_buffer().
_mesa_lookup_bufferobj_err()
struct gl_buffer_object* _mesa_lookup_bufferobj_err (struct gl_context * ctx, GLuint buffer, const char * caller)
A convenience function for direct state access functions that throws GL_INVALID_OPERATION if buffer is not the name of an existing buffer object.
References _mesa_error(), _mesa_lookup_bufferobj(), and DummyBufferObject.
Referenced by _mesa_ClearNamedBufferData(), _mesa_ClearNamedBufferSubData(), _mesa_CopyNamedBufferSubData(), _mesa_FlushMappedNamedBufferRange(), _mesa_GetNamedBufferParameteri64v(), _mesa_GetNamedBufferParameteriv(), _mesa_GetNamedBufferPointerv(), _mesa_GetNamedBufferSubData(), _mesa_GetQueryBufferObjecti64v(), _mesa_GetQueryBufferObjectiv(), _mesa_GetQueryBufferObjectui64v(), _mesa_GetQueryBufferObjectuiv(), _mesa_is_bufferobj(), _mesa_MapNamedBuffer(), _mesa_MapNamedBufferRange(), _mesa_NamedBufferData(), _mesa_NamedBufferStorage(), _mesa_NamedBufferSubData(), _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TextureBuffer(), _mesa_TextureBufferRange(), _mesa_UnmapNamedBuffer(), and _mesa_VertexArrayElementBuffer().
_mesa_lookup_bufferobj_locked()
struct gl_buffer_object* _mesa_lookup_bufferobj_locked (struct gl_context * ctx, GLuint buffer)
References _mesa_HashLookupLocked(), gl_shared_state::BufferObjects, and gl_context::Shared.
Referenced by _mesa_DeleteBuffers(), _mesa_is_bufferobj(), and _mesa_multi_bind_lookup_bufferobj().
_mesa_map_buffer_range()
void* _mesa_map_buffer_range (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr length, GLbitfield access, const char * func)
References _mesa_bufferobj_mapped(), _mesa_enum_to_string(), _mesa_error(), gl_buffer_mapping::AccessFlags, gl_extensions::ARB_buffer_storage, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, BUFFER_USAGE_WARNING, BUFFER_WARNING_CALL_COUNT, gl_context::Driver, gl_context::Extensions, for(), GLAPIENTRY, GLuint, gl_buffer_mapping::Length, MAP_USER, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::Name, gl_buffer_object::NumMapBufferWriteCalls, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, gl_buffer_object::Size, gl_buffer_object::StorageFlags, gl_buffer_object::Usage, and gl_buffer_object::Written.
Referenced by _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_MapNamedBuffer(), _mesa_MapNamedBufferRange(), and _mesa_reference_buffer_object().
_mesa_MapBuffer()
void* GLAPIENTRY _mesa_MapBuffer (GLenum target, GLenum access)
References _mesa_error(), _mesa_map_buffer_range(), get_buffer(), GET_CURRENT_CONTEXT, get_map_buffer_access_flags(), GLAPIENTRY, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_MapBufferRange()
void* GLAPIENTRY _mesa_MapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
References _mesa_error(), _mesa_map_buffer_range(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_MapNamedBuffer()
void* GLAPIENTRY _mesa_MapNamedBuffer (GLuint buffer, GLenum access)
References _mesa_error(), _mesa_lookup_bufferobj_err(), _mesa_map_buffer_range(), GET_CURRENT_CONTEXT, get_map_buffer_access_flags(), and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_MapNamedBufferRange()
void* GLAPIENTRY _mesa_MapNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access)
References _mesa_error(), _mesa_lookup_bufferobj_err(), _mesa_map_buffer_range(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_multi_bind_lookup_bufferobj()
struct gl_buffer_object* _mesa_multi_bind_lookup_bufferobj (struct gl_context * ctx, const GLuint * buffers, GLuint index, const char * caller)
Look up a buffer object for a multi-bind function.
Unlike _mesa_lookup_bufferobj(), this function also takes care of generating an error if the buffer ID is not zero or the name of an existing buffer object.
If the buffer ID refers to an existing buffer object, a pointer to the buffer object is returned. If the ID is zero, a pointer to the shared NullBufferObj is returned. If the ID is not zero and does not refer to a valid buffer object, this function returns NULL.
This function assumes that the caller has already locked the hash table mutex by calling _mesa_HashLockMutex(ctx->Shared->BufferObjects).
References _mesa_error(), _mesa_lookup_bufferobj_locked(), DummyBufferObject, gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_is_bufferobj(), bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), and vertex_array_vertex_buffers().
_mesa_NamedBufferData()
void GLAPIENTRY _mesa_NamedBufferData (GLuint buffer, GLsizeiptr size, const GLvoid * data, GLenum usage)
References _mesa_buffer_data(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_NamedBufferPageCommitmentARB()
void GLAPIENTRY _mesa_NamedBufferPageCommitmentARB (GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit)
References _mesa_error(), _mesa_lookup_bufferobj(), buffer_page_commitment(), DummyBufferObject, and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_NamedBufferStorage()
void GLAPIENTRY _mesa_NamedBufferStorage (GLuint buffer, GLsizeiptr size, const GLvoid * data, GLbitfield flags)
References _mesa_buffer_storage(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_NamedBufferSubData()
void GLAPIENTRY _mesa_NamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, const GLvoid * data)
References _mesa_buffer_sub_data(), _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_new_buffer_object()
static struct gl_buffer_object* _mesa_new_buffer_object (struct gl_context * ctx, GLuint name) static
Allocate and initialize a new buffer object.
Default callback for the dd_function_table::NewBufferObject() hook.
References _mesa_initialize_buffer_object(), MALLOC_STRUCT, and void.
Referenced by _mesa_init_buffer_object_functions().
_mesa_reference_buffer_object_()
void _mesa_reference_buffer_object_ (struct gl_context * ctx, struct gl_buffer_object ** ptr, struct gl_buffer_object * bufObj)
Set ptr to bufObj w/ reference counting.
This is normally only called from the _mesa_reference_buffer_object() macro when there's a real pointer change.
References _mesa_problem(), dd_function_table::DeleteBuffer, gl_context::Driver, gl_buffer_object::Mutex, and gl_buffer_object::RefCount.
Referenced by _mesa_is_bufferobj(), and _mesa_reference_buffer_object().
_mesa_total_buffer_object_memory()
GLuint _mesa_total_buffer_object_memory (struct gl_context * ctx)
Compute total size (in bytes) of all buffer objects for the given context.
For debugging purposes.
References _mesa_HashWalk(), gl_shared_state::BufferObjects, count_buffer_size(), GLuint, and gl_context::Shared.
Referenced by _mesa_reference_buffer_object().
_mesa_unmap_buffer()
GLboolean _mesa_unmap_buffer (struct gl_context * ctx, struct gl_buffer_object * bufObj, const char * func)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_warning(), gl_buffer_mapping::AccessFlags, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_context::Driver, for(), GLAPIENTRY, GLuint, gl_buffer_mapping::Length, MAP_USER, gl_buffer_object::Mappings, gl_buffer_object::Name, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
Referenced by _mesa_reference_buffer_object(), _mesa_UnmapBuffer(), and _mesa_UnmapNamedBuffer().
_mesa_UnmapBuffer()
GLboolean GLAPIENTRY _mesa_UnmapBuffer (GLenum target)
References _mesa_unmap_buffer(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_UnmapNamedBuffer()
GLboolean GLAPIENTRY _mesa_UnmapNamedBuffer (GLuint buffer)
References _mesa_lookup_bufferobj_err(), _mesa_unmap_buffer(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_update_default_objects_buffer_objects()
void _mesa_update_default_objects_buffer_objects (struct gl_context * ctx)
Update the default buffer objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
References gl_context::Array, gl_array_attrib::ArrayBufferObj, bind_buffer_object(), gl_pixelstore_attrib::BufferObj, gl_vertex_array_object::IndexBufferObj, gl_context::Pack, gl_context::Unpack, and gl_array_attrib::VAO.
Referenced by _mesa_is_bufferobj(), and update_default_objects().
bind_atomic_buffer()
static void bind_atomic_buffer (struct gl_context * ctx, unsigned index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, const char * name) static
Binds a buffer object to an atomic buffer binding point.
Unlike set_atomic_buffer_binding(), this function also validates the index and offset, flushes vertices, and updates NewDriverState. It also checks if the binding has actually changing before updating it.
References _mesa_error(), _mesa_reference_buffer_object(), ATOMIC_COUNTER_SIZE, gl_context::AtomicBuffer, gl_context::AtomicBufferBindings, gl_atomic_buffer_binding::BufferObject, gl_context::Const, gl_context::DriverFlags, FLUSH_VERTICES, gl_constants::MaxAtomicBufferBindings, gl_driver_flags::NewAtomicBuffer, gl_context::NewDriverState, gl_atomic_buffer_binding::Offset, set_atomic_buffer_binding(), and gl_atomic_buffer_binding::Size.
Referenced by _mesa_BindBufferBase(), and _mesa_BindBufferRange().
bind_atomic_buffers()
static void bind_atomic_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const GLuint * buffers, bool range, const GLintptr * offsets, const GLsizeiptr * sizes, const char * caller) static
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_multi_bind_lookup_bufferobj(), ATOMIC_COUNTER_SIZE, gl_context::AtomicBufferBindings, bind_buffers_check_offset_and_size(), gl_atomic_buffer_binding::BufferObject, gl_shared_state::BufferObjects, gl_context::DriverFlags, error_check_bind_atomic_buffers(), FLUSH_VERTICES, GLAPIENTRY, gl_buffer_object::Name, gl_driver_flags::NewAtomicBuffer, gl_context::NewDriverState, set_atomic_buffer_binding(), gl_context::Shared, and unbind_atomic_buffers().
Referenced by _mesa_BindBuffersBase(), and _mesa_BindBuffersRange().
bind_buffer_base_shader_storage_buffer()
static void bind_buffer_base_shader_storage_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj) static
Bind a buffer object to a shader storage block binding point.
As above, but offset = 0.
References _mesa_error(), _mesa_reference_buffer_object(), bind_shader_storage_buffer(), gl_context::Const, gl_constants::MaxShaderStorageBufferBindings, gl_shared_state::NullBufferObj, gl_context::ShaderStorageBuffer, and gl_context::Shared.
Referenced by _mesa_BindBufferBase().
bind_buffer_base_uniform_buffer()
static void bind_buffer_base_uniform_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj) static
Bind a buffer object to a uniform block binding point.
As above, but offset = 0.
References _mesa_error(), _mesa_reference_buffer_object(), bind_uniform_buffer(), gl_context::Const, gl_constants::MaxUniformBufferBindings, gl_shared_state::NullBufferObj, gl_context::Shared, and gl_context::UniformBuffer.
Referenced by _mesa_BindBufferBase().
bind_buffer_object()
static void bind_buffer_object (struct gl_context * ctx, struct gl_buffer_object ** bindTarget, GLuint buffer) static
Bind the specified target to buffer for the specified context.
Called by glBindBuffer() and other functions.
References _mesa_handle_bind_buffer_gen(), _mesa_lookup_bufferobj(), _mesa_reference_buffer_object(), gl_pixelstore_attrib::BufferObj, gl_buffer_object::DeletePending, gl_buffer_object::Name, gl_shared_state::NullBufferObj, gl_context::Pack, gl_context::Shared, USAGE_PIXEL_PACK_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by _mesa_BindBuffer(), _mesa_DeleteBuffers(), and _mesa_update_default_objects_buffer_objects().
bind_buffer_range_shader_storage_buffer()
static void bind_buffer_range_shader_storage_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size) static
Bind a region of a buffer object to a shader storage block binding point.
Parameters
index the shader storage buffer binding point index
bufObj the buffer object
offset offset to the start of buffer object region
size size of the buffer object region
References _mesa_error(), _mesa_reference_buffer_object(), bind_shader_storage_buffer(), gl_context::Const, gl_constants::MaxShaderStorageBufferBindings, gl_shared_state::NullBufferObj, gl_context::ShaderStorageBuffer, gl_constants::ShaderStorageBufferOffsetAlignment, and gl_context::Shared.
Referenced by _mesa_BindBufferRange().
bind_buffer_range_uniform_buffer()
static void bind_buffer_range_uniform_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size) static
Bind a region of a buffer object to a uniform block binding point.
Parameters
index the uniform buffer binding point index
bufObj the buffer object
offset offset to the start of buffer object region
size size of the buffer object region
References _mesa_error(), _mesa_reference_buffer_object(), bind_uniform_buffer(), gl_context::Const, gl_constants::MaxUniformBufferBindings, gl_shared_state::NullBufferObj, gl_context::Shared, gl_context::UniformBuffer, and gl_constants::UniformBufferOffsetAlignment.
Referenced by _mesa_BindBufferRange().
bind_buffers_check_offset_and_size()
static bool bind_buffers_check_offset_and_size (struct gl_context * ctx, GLuint index, const GLintptr * offsets, const GLsizeiptr * sizes) inline static
References _mesa_error().
Referenced by bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), and bind_xfb_buffers().
bind_shader_storage_buffer()
static void bind_shader_storage_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize) static
Binds a buffer object to a shader storage buffer binding point.
Unlike set_ssbo_binding(), this function also flushes vertices and updates NewDriverState. It also checks if the binding has actually changed before updating it.
References gl_shader_storage_buffer_binding::AutomaticSize, gl_shader_storage_buffer_binding::BufferObject, gl_context::DriverFlags, FLUSH_VERTICES, gl_context::NewDriverState, gl_driver_flags::NewShaderStorageBuffer, gl_shader_storage_buffer_binding::Offset, set_ssbo_binding(), gl_context::ShaderStorageBufferBindings, and gl_shader_storage_buffer_binding::Size.
Referenced by bind_buffer_base_shader_storage_buffer(), and bind_buffer_range_shader_storage_buffer().
bind_shader_storage_buffers()
static void bind_shader_storage_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const GLuint * buffers, bool range, const GLintptr * offsets, const GLsizeiptr * sizes, const char * caller) static
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_multi_bind_lookup_bufferobj(), bind_buffers_check_offset_and_size(), gl_shader_storage_buffer_binding::BufferObject, gl_shared_state::BufferObjects, gl_context::Const, gl_context::DriverFlags, error_check_bind_shader_storage_buffers(), FLUSH_VERTICES, gl_buffer_object::Name, gl_context::NewDriverState, gl_driver_flags::NewShaderStorageBuffer, gl_shared_state::NullBufferObj, set_ssbo_binding(), gl_context::ShaderStorageBufferBindings, gl_constants::ShaderStorageBufferOffsetAlignment, gl_context::Shared, and unbind_shader_storage_buffers().
Referenced by _mesa_BindBuffersBase(), and _mesa_BindBuffersRange().
bind_uniform_buffer()
static void bind_uniform_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize) static
Binds a buffer object to a uniform buffer binding point.
Unlike set_ubo_binding(), this function also flushes vertices and updates NewDriverState. It also checks if the binding has actually changed before updating it.
References gl_uniform_buffer_binding::AutomaticSize, gl_uniform_buffer_binding::BufferObject, gl_context::DriverFlags, FLUSH_VERTICES, gl_context::NewDriverState, gl_driver_flags::NewUniformBuffer, gl_uniform_buffer_binding::Offset, set_ubo_binding(), gl_uniform_buffer_binding::Size, and gl_context::UniformBufferBindings.
Referenced by bind_buffer_base_uniform_buffer(), and bind_buffer_range_uniform_buffer().
bind_uniform_buffers()
static void bind_uniform_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const GLuint * buffers, bool range, const GLintptr * offsets, const GLsizeiptr * sizes, const char * caller) static
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_multi_bind_lookup_bufferobj(), bind_buffers_check_offset_and_size(), gl_uniform_buffer_binding::BufferObject, gl_shared_state::BufferObjects, gl_context::Const, gl_context::DriverFlags, error_check_bind_uniform_buffers(), FLUSH_VERTICES, gl_buffer_object::Name, gl_context::NewDriverState, gl_driver_flags::NewUniformBuffer, gl_shared_state::NullBufferObj, set_ubo_binding(), gl_context::Shared, unbind_uniform_buffers(), gl_context::UniformBufferBindings, and gl_constants::UniformBufferOffsetAlignment.
Referenced by _mesa_BindBuffersBase(), and _mesa_BindBuffersRange().
bind_xfb_buffers()
static void bind_xfb_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const GLuint * buffers, bool range, const GLintptr * offsets, const GLsizeiptr * sizes, const char * caller) static
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_multi_bind_lookup_bufferobj(), _mesa_set_transform_feedback_binding(), bind_buffers_check_offset_and_size(), gl_shared_state::BufferObjects, gl_transform_feedback_object::Buffers, gl_transform_feedback_state::CurrentObject, gl_context::DriverFlags, error_check_bind_xfb_buffers(), FLUSH_VERTICES, GLuint, gl_buffer_object::Name, gl_context::NewDriverState, gl_driver_flags::NewTransformFeedback, gl_context::Shared, gl_context::TransformFeedback, and unbind_xfb_buffers().
Referenced by _mesa_BindBuffersBase(), and _mesa_BindBuffersRange().
buffer_data_fallback()
static GLboolean buffer_data_fallback (struct gl_context * ctx, GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage, GLenum storageFlags, struct gl_buffer_object * bufObj) static
Allocate space for and store data in a buffer object.
Any data that was previously stored in the buffer object is lost. If data is NULL, memory will be allocated, but no copy will occur.
This is the default callback for dd_function_table::BufferData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
target Buffer object target on which to operate.
size Size, in bytes, of the new data store.
data Pointer to the data to store in the buffer object. This pointer may be NULL.
usage Hints about how the data will be used.
bufObj Object to be used.
Returns
GL_TRUE for success, GL_FALSE for failure
See also
glBufferDataARB, dd_function_table::BufferData.
References _mesa_align_free(), _mesa_align_malloc(), gl_context::Const, gl_buffer_object::Data, gl_constants::MinMapBufferAlignment, gl_buffer_object::Size, gl_buffer_object::StorageFlags, gl_buffer_object::Usage, and void.
Referenced by _mesa_init_buffer_object_functions().
buffer_object_subdata_range_good()
static bool buffer_object_subdata_range_good (struct gl_context * ctx, const struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, bool mappedRange, const char * caller) static
Tests the subdata range parameters and sets the GL error code for glBufferSubDataARB, glGetBufferSubDataARB and glClearBufferSubData.
Parameters
ctx GL context.
bufObj The buffer object.
offset Offset of the first byte of the subdata range.
size Size, in bytes, of the subdata range.
mappedRange If true, checks if an overlapping range is mapped. If false, checks if buffer is mapped.
caller Name of calling function for recording errors.
Returns
false if error, true otherwise
See also
glBufferSubDataARB, glGetBufferSubDataARB, glClearBufferSubData
References _mesa_bufferobj_mapped(), _mesa_error(), gl_buffer_mapping::AccessFlags, bufferobj_range_mapped(), MAP_USER, gl_buffer_object::Mappings, and gl_buffer_object::Size.
Referenced by _mesa_buffer_sub_data(), _mesa_clear_buffer_sub_data(), _mesa_GetBufferSubData(), and _mesa_GetNamedBufferSubData().
buffer_page_commitment()
static void buffer_page_commitment (struct gl_context * ctx, struct gl_buffer_object * bufferObj, GLintptr offset, GLsizeiptr size, GLboolean commit, const char * func) static
References _mesa_error(), dd_function_table::BufferPageCommitment, gl_context::Const, gl_context::Driver, GLAPIENTRY, gl_buffer_object::Size, gl_constants::SparseBufferPageSize, and gl_buffer_object::StorageFlags.
Referenced by _mesa_BufferPageCommitmentARB(), and _mesa_NamedBufferPageCommitmentARB().
buffer_sub_data_fallback()
static void buffer_sub_data_fallback (struct gl_context * ctx, GLintptr offset, GLsizeiptr size, const GLvoid * data, struct gl_buffer_object * bufObj) static
Replace data in a subrange of buffer object.
If the data range specified by size + offset extends beyond the end of the buffer or if data is NULL, no copy is performed.
This is the default callback for dd_function_table::BufferSubData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
offset Offset of the first byte to be modified.
size Size, in bytes, of the data range.
data Pointer to the data to store in the buffer object.
bufObj Object to be used.
See also
glBufferSubDataARB, dd_function_table::BufferSubData.
References gl_buffer_object::Data, gl_buffer_object::Size, and void.
Referenced by _mesa_init_buffer_object_functions().
buffer_usage_warning()
static void buffer_usage_warning (struct gl_context * ctx, GLuint * id, const char * fmt, ...) static
Helper to warn of possible performance issues, such as frequently updating a buffer created with GL_STATIC_DRAW.
Called via the macro below.
References _mesa_gl_vdebug(), MESA_DEBUG_SEVERITY_MEDIUM, MESA_DEBUG_SOURCE_API, and MESA_DEBUG_TYPE_PERFORMANCE.
bufferobj_range_mapped()
static bool bufferobj_range_mapped (const struct gl_buffer_object * obj, GLintptr offset, GLsizeiptr size) static
Test if the buffer is mapped, and if so, if the mapped range overlaps the given range.
The regions do not overlap if and only if the end of the given region is before the mapped region or the start of the given region is after the mapped region.
Parameters
obj Buffer object target on which to operate.
offset Offset of the first byte of the subdata range.
size Size, in bytes, of the subdata range.
Returns
true if ranges overlap, false otherwise
References _mesa_bufferobj_mapped(), gl_buffer_mapping::Length, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_mapping::Offset.
Referenced by _mesa_InvalidateBufferSubData(), and buffer_object_subdata_range_good().
convert_clear_buffer_data()
static bool convert_clear_buffer_data (struct gl_context * ctx, mesa_format internalformat, GLubyte * clearValue, GLenum format, GLenum type, const GLvoid * data, const char * caller) static
Convert user-specified clear value to the specified internal format.
Parameters
ctx GL context.
internalformat Format to which the data is converted.
clearValue Points to the converted clear value.
format Format of the supplied data.
type Type of the supplied data.
data Data which is to be converted to internalformat.
caller Name of calling function for recording errors.
Returns
true if data could be converted, false otherwise.
See also
glClearBufferData, glClearBufferSubData
References _mesa_error(), _mesa_get_format_base_format(), _mesa_texstore(), and gl_context::Unpack.
Referenced by _mesa_clear_buffer_sub_data().
copy_buffer_sub_data_fallback()
static void copy_buffer_sub_data_fallback (struct gl_context * ctx, struct gl_buffer_object * src, struct gl_buffer_object * dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size) static
Default fallback for dd_function_table::CopyBufferSubData().
Called via glCopyBufferSubData().
References gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
Referenced by _mesa_init_buffer_object_functions().
count_buffer_size()
static void count_buffer_size (GLuint key, void * data, void * userData) static
Callback called from _mesa_HashWalk()
References GLuint, gl_buffer_object::Size, and void.
Referenced by _mesa_total_buffer_object_memory().
create_buffers()
static void create_buffers (GLsizei n, GLuint * buffers, bool dsa) static
This is the implementation for glGenBuffers and glCreateBuffers.
It is not exposed to the rest of Mesa to encourage the use of nameless buffers in driver internals.
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), DummyBufferObject, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_CreateBuffers(), and _mesa_GenBuffers().
error_check_bind_atomic_buffers()
static bool error_check_bind_atomic_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const char * caller) static
References _mesa_error(), gl_extensions::ARB_shader_atomic_counters, gl_context::Const, gl_context::Extensions, and gl_constants::MaxAtomicBufferBindings.
Referenced by bind_atomic_buffers().
error_check_bind_shader_storage_buffers()
static bool error_check_bind_shader_storage_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const char * caller) static
References _mesa_error(), gl_extensions::ARB_shader_storage_buffer_object, gl_context::Const, gl_context::Extensions, and gl_constants::MaxShaderStorageBufferBindings.
Referenced by bind_shader_storage_buffers().
error_check_bind_uniform_buffers()
static bool error_check_bind_uniform_buffers (struct gl_context * ctx, GLuint first, GLsizei count, const char * caller) static
References _mesa_error(), gl_extensions::ARB_uniform_buffer_object, gl_context::Const, gl_context::Extensions, and gl_constants::MaxUniformBufferBindings.
Referenced by bind_uniform_buffers().
error_check_bind_xfb_buffers()
static bool error_check_bind_xfb_buffers (struct gl_context * ctx, struct gl_transform_feedback_object * tfObj, GLuint first, GLsizei count, const char * caller) static
References _mesa_error(), gl_transform_feedback_object::Active, gl_context::Const, gl_extensions::EXT_transform_feedback, gl_context::Extensions, and gl_constants::MaxTransformFeedbackBuffers.
Referenced by bind_xfb_buffers().
flush_mapped_buffer_range_fallback()
static void flush_mapped_buffer_range_fallback (struct gl_context * ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object * obj, gl_map_buffer_index index) static
Default fallback for dd_function_table::FlushMappedBufferRange().
Called via glFlushMappedBufferRange().
References void.
Referenced by _mesa_init_buffer_object_functions().
get_buffer()
static struct gl_buffer_object* get_buffer (struct gl_context * ctx, const char * func, GLenum target, GLenum error) static
Get the buffer object bound to the specified target in a GL context.
Parameters
ctx the GL context
target the buffer object target to be retrieved.
error the GL error to record if target is illegal.
Returns
pointer to the buffer object bound to target in the specified context or NULL if target is invalid.
References _mesa_error(), _mesa_is_bufferobj(), and get_buffer_target().
Referenced by _mesa_BufferData(), _mesa_BufferPageCommitmentARB(), _mesa_BufferStorage(), _mesa_BufferSubData(), _mesa_ClearBufferData(), _mesa_ClearBufferSubData(), _mesa_CopyBufferSubData(), _mesa_FlushMappedBufferRange(), _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetBufferPointerv(), _mesa_GetBufferSubData(), _mesa_MapBuffer(), _mesa_MapBufferRange(), and _mesa_UnmapBuffer().
get_buffer_parameter()
static bool get_buffer_parameter (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum pname, GLint64 * params, const char * func) static
References _mesa_bufferobj_mapped(), _mesa_enum_to_string(), _mesa_error(), gl_buffer_mapping::AccessFlags, gl_extensions::ARB_buffer_storage, gl_extensions::ARB_map_buffer_range, gl_context::Extensions, GLAPIENTRY, gl_buffer_object::Immutable, gl_buffer_mapping::Length, MAP_USER, gl_buffer_object::Mappings, gl_buffer_mapping::Offset, simplified_access_mode(), gl_buffer_object::Size, gl_buffer_object::StorageFlags, and gl_buffer_object::Usage.
Referenced by _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetNamedBufferParameteri64v(), and _mesa_GetNamedBufferParameteriv().
get_buffer_target()
static struct gl_buffer_object** get_buffer_target (struct gl_context * ctx, GLenum target) static
Return pointer to address of a buffer object target.
Parameters
ctx the GL context
target the buffer object target to be retrieved.
Returns
pointer to pointer to the buffer object bound to target in the specified context or NULL if target is invalid.
References _mesa_has_compute_shaders(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_gles31(), gl_extensions::AMD_pinned_memory, gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_draw_indirect, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_shader_storage_buffer_object, gl_extensions::ARB_uniform_buffer_object, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::AtomicBuffer, gl_pixelstore_attrib::BufferObj, gl_texture_attrib::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_transform_feedback_state::CurrentBuffer, gl_context::DispatchIndirectBuffer, gl_context::DrawIndirectBuffer, gl_extensions::EXT_transform_feedback, gl_context::Extensions, gl_context::ExternalVirtualMemoryBuffer, gl_vertex_array_object::IndexBufferObj, gl_context::Pack, gl_context::ParameterBuffer, gl_context::QueryBuffer, gl_context::ShaderStorageBuffer, gl_context::Texture, gl_context::TransformFeedback, gl_context::UniformBuffer, gl_context::Unpack, and gl_array_attrib::VAO.
Referenced by _mesa_BindBuffer(), and get_buffer().
get_map_buffer_access_flags()
static bool get_map_buffer_access_flags (struct gl_context * ctx, GLenum access, GLbitfield * flags) static
Converts GLenum access from MapBuffer and MapNamedBuffer into flags for input to _mesa_map_buffer_range.
Returns
true if the type of requested access is permissible.
References _mesa_is_desktop_gl(), and GLAPIENTRY.
Referenced by _mesa_MapBuffer(), and _mesa_MapNamedBuffer().
get_no_minmax_cache()
static bool get_no_minmax_cache () static
Get the value of MESA_NO_MINMAX_CACHE.
Referenced by _mesa_initialize_buffer_object().
map_buffer_range_fallback()
static void* map_buffer_range_fallback (struct gl_context * ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object * bufObj, gl_map_buffer_index index) static
Default fallback for dd_function_table::MapBufferRange().
Called via glMapBufferRange().
References _mesa_bufferobj_mapped(), gl_buffer_mapping::AccessFlags, gl_buffer_object::Data, gl_buffer_mapping::Length, gl_buffer_object::Mappings, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, and void.
Referenced by _mesa_init_buffer_object_functions().
set_atomic_buffer_binding()
static void set_atomic_buffer_binding (struct gl_context * ctx, struct gl_atomic_buffer_binding * binding, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size) static
Binds a buffer object to an atomic buffer binding point.
The caller is responsible for validating the offset, flushing the vertices and updating NewDriverState.
References _mesa_reference_buffer_object(), gl_atomic_buffer_binding::BufferObject, gl_shared_state::NullBufferObj, gl_atomic_buffer_binding::Offset, gl_context::Shared, gl_atomic_buffer_binding::Size, USAGE_ATOMIC_COUNTER_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by bind_atomic_buffer(), bind_atomic_buffers(), and unbind_atomic_buffers().
set_ssbo_binding()
static void set_ssbo_binding (struct gl_context * ctx, struct gl_shader_storage_buffer_binding * binding, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize) static
Binds a buffer object to a shader storage buffer binding point.
The caller is responsible for flushing vertices and updating NewDriverState.
References _mesa_reference_buffer_object(), gl_shader_storage_buffer_binding::AutomaticSize, gl_shader_storage_buffer_binding::BufferObject, gl_shader_storage_buffer_binding::Offset, gl_shader_storage_buffer_binding::Size, USAGE_SHADER_STORAGE_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by bind_shader_storage_buffer(), bind_shader_storage_buffers(), and unbind_shader_storage_buffers().
set_ubo_binding()
static void set_ubo_binding (struct gl_context * ctx, struct gl_uniform_buffer_binding * binding, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize) static
Binds a buffer object to a uniform buffer binding point.
The caller is responsible for flushing vertices and updating NewDriverState.
References _mesa_reference_buffer_object(), gl_uniform_buffer_binding::AutomaticSize, gl_uniform_buffer_binding::BufferObject, gl_uniform_buffer_binding::Offset, gl_uniform_buffer_binding::Size, USAGE_UNIFORM_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by bind_uniform_buffer(), bind_uniform_buffers(), and unbind_uniform_buffers().
simplified_access_mode()
static GLenum simplified_access_mode (struct gl_context * ctx, GLbitfield access) static
Convert a GLbitfield describing the mapped buffer access flags into one of GL_READ_WRITE, GL_READ_ONLY, or GL_WRITE_ONLY.
References _mesa_is_gles().
Referenced by get_buffer_parameter().
unbind()
static void unbind (struct gl_context * ctx, struct gl_vertex_array_object * vao, unsigned index, struct gl_buffer_object * obj) static
If *ptr points to obj, set ptr = the Null/default buffer object.
This is a helper for buffer object deletion. The GL spec says that deleting a buffer object causes it to get unbound from all arrays in the current context.
References _mesa_bind_vertex_buffer(), gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, gl_shared_state::NullBufferObj, gl_vertex_buffer_binding::Offset, gl_context::Shared, and gl_vertex_buffer_binding::Stride.
Referenced by _mesa_DeleteBuffers().
unbind_atomic_buffers()
static void unbind_atomic_buffers (struct gl_context * ctx, GLuint first, GLsizei count) static
Unbind all atomic counter buffers in the range <first> through <first>+<count>-1.
References gl_context::AtomicBufferBindings, gl_shared_state::NullBufferObj, set_atomic_buffer_binding(), and gl_context::Shared.
Referenced by bind_atomic_buffers().
unbind_shader_storage_buffers()
static void unbind_shader_storage_buffers (struct gl_context * ctx, GLuint first, GLsizei count) static
Unbind all shader storage buffers in the range <first> through <first>+<count>-1.
References gl_shared_state::NullBufferObj, set_ssbo_binding(), gl_context::ShaderStorageBufferBindings, and gl_context::Shared.
Referenced by bind_shader_storage_buffers().
unbind_uniform_buffers()
static void unbind_uniform_buffers (struct gl_context * ctx, GLuint first, GLsizei count) static
Unbind all uniform buffers in the range <first> through <first>+<count>-1.
References gl_shared_state::NullBufferObj, set_ubo_binding(), gl_context::Shared, and gl_context::UniformBufferBindings.
Referenced by bind_uniform_buffers().
unbind_xfb_buffers()
static void unbind_xfb_buffers (struct gl_context * ctx, struct gl_transform_feedback_object * tfObj, GLuint first, GLsizei count) static
Unbind all transform feedback buffers in the range <first> through <first>+<count>-1.
References _mesa_set_transform_feedback_binding(), gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by bind_xfb_buffers().
unmap_buffer_fallback()
static GLboolean unmap_buffer_fallback (struct gl_context * ctx, struct gl_buffer_object * bufObj, gl_map_buffer_index index) static
Default callback for dd_function_table::UnmapBuffer().
The input parameters will have been already tested for errors.
See also
glUnmapBufferARB, dd_function_table::UnmapBuffer
References gl_buffer_mapping::AccessFlags, gl_buffer_mapping::Length, gl_buffer_object::Mappings, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, and void.
Referenced by _mesa_init_buffer_object_functions().
validate_clear_buffer_format()
static mesa_format validate_clear_buffer_format (struct gl_context * ctx, GLenum internalformat, GLenum format, GLenum type, const char * caller) static
Test the format and type parameters and set the GL error code for glClearBufferData and glClearBufferSubData.
Parameters
ctx GL context.
internalformat Format to which the data is to be converted.
format Format of the supplied data.
type Type of the supplied data.
caller Name of calling function for recording errors.
Returns
If internalformat, format and type are legal the mesa_format corresponding to internalformat, otherwise MESA_FORMAT_NONE.
See also
glClearBufferData and glClearBufferSubData
References _mesa_error(), _mesa_error_check_format_and_type(), _mesa_is_color_format(), _mesa_is_enum_format_signed_int(), _mesa_is_format_integer_color(), _mesa_validate_texbuffer_format(), and MESA_FORMAT_NONE.
Referenced by _mesa_clear_buffer_sub_data().
Variable Documentation
DummyBufferObject
struct gl_buffer_object DummyBufferObject static
Used as a placeholder for buffer objects between glGenBuffers() and glBindBuffer() so that glIsBuffer() can work correctly.
Referenced by _mesa_DeleteBuffers(), _mesa_handle_bind_buffer_gen(), _mesa_init_buffer_objects(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_IsBuffer(), _mesa_lookup_bufferobj_err(), _mesa_multi_bind_lookup_bufferobj(), _mesa_NamedBufferPageCommitmentARB(), and create_buffers().