Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
bufferobj.h File Reference
#include <stdbool.h>
#include "mtypes.h"
Functions
static GLboolean _mesa_bufferobj_mapped (const struct gl_buffer_object *obj, gl_map_buffer_index index)
Is the given buffer object currently mapped by the GL user?
static bool _mesa_check_disallowed_mapping (const struct gl_buffer_object *obj)
Check whether the given buffer object is illegally mapped prior to drawing from (or reading back to) the buffer.
static GLboolean _mesa_is_bufferobj (const struct gl_buffer_object *obj)
Is the given buffer object a user-created buffer object? Mesa uses default buffer objects in several places.
void _mesa_init_buffer_objects (struct gl_context *ctx)
Initialize the state associated with buffer objects.
void _mesa_free_buffer_objects (struct gl_context *ctx)
bool _mesa_handle_bind_buffer_gen (struct gl_context *ctx, GLuint buffer, struct gl_buffer_object **buf_handle, const char *caller)
void _mesa_update_default_objects_buffer_objects (struct gl_context *ctx)
Update the default buffer objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
struct gl_buffer_object * _mesa_lookup_bufferobj (struct gl_context *ctx, GLuint buffer)
Return the gl_buffer_object for the given ID.
struct gl_buffer_object * _mesa_lookup_bufferobj_locked (struct gl_context *ctx, GLuint buffer)
struct gl_buffer_object * _mesa_lookup_bufferobj_err (struct gl_context *ctx, GLuint buffer, const char *caller)
A convenience function for direct state access functions that throws GL_INVALID_OPERATION if buffer is not the name of an existing buffer object.
struct gl_buffer_object * _mesa_multi_bind_lookup_bufferobj (struct gl_context *ctx, const GLuint *buffers, GLuint index, const char *caller)
Look up a buffer object for a multi-bind function.
void _mesa_initialize_buffer_object (struct gl_context *ctx, struct gl_buffer_object *obj, GLuint name)
Initialize a buffer object to default values.
void _mesa_delete_buffer_object (struct gl_context *ctx, struct gl_buffer_object *bufObj)
Delete a buffer object.
void _mesa_reference_buffer_object_ (struct gl_context *ctx, struct gl_buffer_object **ptr, struct gl_buffer_object *bufObj)
Set ptr to bufObj w/ reference counting.
static void _mesa_reference_buffer_object (struct gl_context *ctx, struct gl_buffer_object **ptr, struct gl_buffer_object *bufObj)
GLuint _mesa_total_buffer_object_memory (struct gl_context *ctx)
Compute total size (in bytes) of all buffer objects for the given context.
void _mesa_init_buffer_object_functions (struct dd_function_table *driver)
Plug default/fallback buffer object functions into the device driver hooks.
void _mesa_buffer_storage (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum target, GLsizeiptr size, const GLvoid *data, GLbitfield flags, const char *func)
void _mesa_buffer_data (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage, const char *func)
void _mesa_buffer_sub_data (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, const GLvoid *data, const char *func)
Implementation for glBufferSubData and glNamedBufferSubData.
void _mesa_buffer_unmap_all_mappings (struct gl_context *ctx, struct gl_buffer_object *bufObj)
void _mesa_copy_buffer_sub_data (struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size, const char *func)
void * _mesa_map_buffer_range (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr length, GLbitfield access, const char *func)
void _mesa_flush_mapped_buffer_range (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr length, const char *func)
void _mesa_ClearBufferSubData_sw (struct gl_context *ctx, GLintptr offset, GLsizeiptr size, const GLvoid *clearValue, GLsizeiptr clearValueSize, struct gl_buffer_object *bufObj)
Clear a subrange of the buffer object with copies of the supplied data.
void _mesa_clear_buffer_sub_data (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid *data, const char *func, bool subdata)
GLboolean _mesa_unmap_buffer (struct gl_context *ctx, struct gl_buffer_object *bufObj, const char *func)
void GLAPIENTRY _mesa_BindBuffer (GLenum target, GLuint buffer)
void GLAPIENTRY _mesa_DeleteBuffers (GLsizei n, const GLuint *buffer)
Delete a set of buffer objects.
void GLAPIENTRY _mesa_GenBuffers (GLsizei n, GLuint *buffers)
Generate a set of unique buffer object IDs and store them in buffers.
void GLAPIENTRY _mesa_CreateBuffers (GLsizei n, GLuint *buffers)
Create a set of buffer objects and store their unique IDs in buffers.
GLboolean GLAPIENTRY _mesa_IsBuffer (GLuint buffer)
Determine if ID is the name of a buffer object.
void GLAPIENTRY _mesa_BufferStorage (GLenum target, GLsizeiptr size, const GLvoid *data, GLbitfield flags)
void GLAPIENTRY _mesa_NamedBufferStorage (GLuint buffer, GLsizeiptr size, const GLvoid *data, GLbitfield flags)
void GLAPIENTRY _mesa_BufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
void GLAPIENTRY _mesa_NamedBufferData (GLuint buffer, GLsizeiptr size, const GLvoid *data, GLenum usage)
void GLAPIENTRY _mesa_BufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data)
void GLAPIENTRY _mesa_NamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, const GLvoid *data)
void GLAPIENTRY _mesa_GetBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, GLvoid *data)
void GLAPIENTRY _mesa_GetNamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, GLvoid *data)
void GLAPIENTRY _mesa_ClearBufferData (GLenum target, GLenum internalformat, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ClearNamedBufferData (GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ClearBufferSubData (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ClearNamedBufferSubData (GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid *data)
GLboolean GLAPIENTRY _mesa_UnmapBuffer (GLenum target)
GLboolean GLAPIENTRY _mesa_UnmapNamedBuffer (GLuint buffer)
void GLAPIENTRY _mesa_GetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetBufferParameteri64v (GLenum target, GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_GetNamedBufferParameteriv (GLuint buffer, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetNamedBufferParameteri64v (GLuint buffer, GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_GetBufferPointerv (GLenum target, GLenum pname, GLvoid **params)
void GLAPIENTRY _mesa_GetNamedBufferPointerv (GLuint buffer, GLenum pname, GLvoid **params)
void GLAPIENTRY _mesa_CopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void GLAPIENTRY _mesa_CopyNamedBufferSubData (GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void *GLAPIENTRY _mesa_MapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
void *GLAPIENTRY _mesa_MapNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access)
void *GLAPIENTRY _mesa_MapBuffer (GLenum target, GLenum access)
void *GLAPIENTRY _mesa_MapNamedBuffer (GLuint buffer, GLenum access)
void GLAPIENTRY _mesa_FlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length)
void GLAPIENTRY _mesa_FlushMappedNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length)
void GLAPIENTRY _mesa_BindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
void GLAPIENTRY _mesa_BindBufferBase (GLenum target, GLuint index, GLuint buffer)
void GLAPIENTRY _mesa_BindBuffersRange (GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes)
void GLAPIENTRY _mesa_BindBuffersBase (GLenum target, GLuint first, GLsizei count, const GLuint *buffers)
void GLAPIENTRY _mesa_InvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length)
void GLAPIENTRY _mesa_InvalidateBufferData (GLuint buffer)
void GLAPIENTRY _mesa_BufferPageCommitmentARB (GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit)
void GLAPIENTRY _mesa_NamedBufferPageCommitmentARB (GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit)
Function Documentation
_mesa_BindBuffer()
void GLAPIENTRY _mesa_BindBuffer (GLenum target, GLuint buffer)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), bind_buffer_object(), get_buffer_target(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object(), and restore_array_attrib().
_mesa_BindBufferBase()
void GLAPIENTRY _mesa_BindBufferBase (GLenum target, GLuint index, GLuint buffer)
References _mesa_bind_buffer_base_transform_feedback(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_handle_bind_buffer_gen(), _mesa_lookup_bufferobj(), bind_atomic_buffer(), bind_buffer_base_shader_storage_buffer(), bind_buffer_base_uniform_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_DeleteBuffers(), and _mesa_reference_buffer_object().
_mesa_BindBufferRange()
void GLAPIENTRY _mesa_BindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
References _mesa_bind_buffer_range_transform_feedback(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_handle_bind_buffer_gen(), _mesa_lookup_bufferobj(), bind_atomic_buffer(), bind_buffer_range_shader_storage_buffer(), bind_buffer_range_uniform_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object().
_mesa_BindBuffersBase()
void GLAPIENTRY _mesa_BindBuffersBase (GLenum target, GLuint first, GLsizei count, const GLuint * buffers)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object().
_mesa_BindBuffersRange()
void GLAPIENTRY _mesa_BindBuffersRange (GLenum target, GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizeiptr * sizes)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_buffer_object().
_mesa_buffer_data()
void _mesa_buffer_data (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage, const char * func)
References _mesa_buffer_unmap_all_mappings(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _NEW_BUFFER_OBJECT, gl_context::API, API_OPENGLES, dd_function_table::BufferData, gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, gl_buffer_object::Immutable, MESA_VERBOSE, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::Name, VERBOSE_API, and gl_buffer_object::Written.
Referenced by _mesa_BufferData(), _mesa_NamedBufferData(), and _mesa_reference_buffer_object().
_mesa_buffer_storage()
void _mesa_buffer_storage (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum target, GLsizeiptr size, const GLvoid * data, GLbitfield flags, const char * func)
References _mesa_buffer_unmap_all_mappings(), _mesa_error(), _NEW_BUFFER_OBJECT, gl_extensions::ARB_sparse_buffer, dd_function_table::BufferData, gl_context::Driver, gl_context::Extensions, FLUSH_VERTICES, GLAPIENTRY, gl_buffer_object::Immutable, gl_buffer_object::MinMaxCacheDirty, and gl_buffer_object::Written.
Referenced by _mesa_BufferStorage(), _mesa_NamedBufferStorage(), and _mesa_reference_buffer_object().
_mesa_buffer_sub_data()
void _mesa_buffer_sub_data (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, const GLvoid * data, const char * func)
Implementation for glBufferSubData and glNamedBufferSubData.
Parameters
ctx GL context.
bufObj The buffer object.
offset Offset of the first byte of the subdata range.
size Size, in bytes, of the subdata range.
data The data store.
func Name of calling function for recording errors.
References _mesa_enum_to_string(), _mesa_error(), buffer_object_subdata_range_good(), BUFFER_USAGE_WARNING, BUFFER_WARNING_CALL_COUNT, dd_function_table::BufferSubData, gl_context::Driver, GLAPIENTRY, gl_buffer_object::Immutable, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::Name, gl_buffer_object::NumSubDataCalls, gl_buffer_object::StorageFlags, gl_buffer_object::Usage, and gl_buffer_object::Written.
Referenced by _mesa_BufferSubData(), _mesa_NamedBufferSubData(), and _mesa_reference_buffer_object().
_mesa_buffer_unmap_all_mappings()
void _mesa_buffer_unmap_all_mappings (struct gl_context * ctx, struct gl_buffer_object * bufObj)
References _mesa_bufferobj_mapped(), gl_buffer_mapping::AccessFlags, gl_context::Driver, GLAPIENTRY, MAP_COUNT, gl_buffer_object::Mappings, gl_buffer_mapping::Pointer, and dd_function_table::UnmapBuffer.
Referenced by _mesa_buffer_data(), _mesa_buffer_storage(), _mesa_DeleteBuffers(), _mesa_reference_buffer_object(), and delete_bufferobj_cb().
_mesa_BufferData()
void GLAPIENTRY _mesa_BufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
References _mesa_buffer_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_bufferobj_mapped()
static GLboolean _mesa_bufferobj_mapped (const struct gl_buffer_object * obj, gl_map_buffer_index index) inline static
Is the given buffer object currently mapped by the GL user?
References gl_buffer_object::Mappings, and gl_buffer_mapping::Pointer.
Referenced by _mesa_buffer_unmap_all_mappings(), _mesa_check_disallowed_mapping(), _mesa_flush_mapped_buffer_range(), _mesa_map_buffer_range(), _mesa_unmap_buffer(), buffer_object_subdata_range_good(), bufferobj_range_mapped(), check_vbo(), get_buffer_parameter(), and map_buffer_range_fallback().
_mesa_BufferPageCommitmentARB()
void GLAPIENTRY _mesa_BufferPageCommitmentARB (GLenum target, GLintptr offset, GLsizeiptr size, GLboolean commit)
References buffer_page_commitment(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_BufferStorage()
void GLAPIENTRY _mesa_BufferStorage (GLenum target, GLsizeiptr size, const GLvoid * data, GLbitfield flags)
References _mesa_buffer_storage(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_BufferSubData()
void GLAPIENTRY _mesa_BufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data)
References _mesa_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_check_disallowed_mapping()
static bool _mesa_check_disallowed_mapping (const struct gl_buffer_object * obj) inline static
Check whether the given buffer object is illegally mapped prior to drawing from (or reading back to) the buffer.
Note that it's legal for a buffer to be mapped at draw/readback time if it was mapped persistently (See GL_ARB_buffer_storage spec).
Returns
true if the buffer is illegally mapped, false otherwise
References _mesa_bufferobj_mapped(), gl_buffer_mapping::AccessFlags, MAP_USER, and gl_buffer_object::Mappings.
Referenced by _mesa_all_buffers_are_unmapped(), _mesa_Bitmap(), _mesa_copy_buffer_sub_data(), _mesa_DrawPixels(), _mesa_InvalidateBufferData(), _mesa_map_validate_pbo_dest(), _mesa_ReadnPixelsARB(), _mesa_validate_pbo_source(), _mesa_validate_pbo_source_compressed(), getcompressedteximage_error_check(), pbo_error_check(), valid_dispatch_indirect(), valid_draw_indirect(), and valid_draw_indirect_parameters().
_mesa_clear_buffer_sub_data()
void _mesa_clear_buffer_sub_data (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid * data, const char * func, bool subdata)
Parameters
subdata true if caller is *SubData, false if *Data
References _mesa_error(), _mesa_get_format_bytes(), buffer_object_subdata_range_good(), dd_function_table::ClearBufferSubData, convert_clear_buffer_data(), gl_context::Driver, GLAPIENTRY, MAX_PIXEL_BYTES, MESA_FORMAT_NONE, gl_buffer_object::MinMaxCacheDirty, and validate_clear_buffer_format().
Referenced by _mesa_ClearBufferData(), _mesa_ClearBufferSubData(), _mesa_ClearNamedBufferData(), _mesa_ClearNamedBufferSubData(), and _mesa_reference_buffer_object().
_mesa_ClearBufferData()
void GLAPIENTRY _mesa_ClearBufferData (GLenum target, GLenum internalformat, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_ClearBufferSubData()
void GLAPIENTRY _mesa_ClearBufferSubData (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_ClearBufferSubData_sw()
void _mesa_ClearBufferSubData_sw (struct gl_context * ctx, GLintptr offset, GLsizeiptr size, const GLvoid * clearValue, GLsizeiptr clearValueSize, struct gl_buffer_object * bufObj)
Clear a subrange of the buffer object with copies of the supplied data.
If data is NULL the buffer is filled with zeros.
This is the default callback for dd_function_table::ClearBufferSubData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
offset Offset of the first byte to be cleared.
size Size, in bytes, of the to be cleared range.
clearValue Source of the data.
clearValueSize Size, in bytes, of the supplied data.
bufObj Object to be cleared.
See also
glClearBufferSubData, glClearBufferData and dd_function_table::ClearBufferSubData.
References _mesa_error(), gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and dd_function_table::UnmapBuffer.
Referenced by _mesa_init_buffer_object_functions(), and _mesa_reference_buffer_object().
_mesa_ClearNamedBufferData()
void GLAPIENTRY _mesa_ClearNamedBufferData (GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_ClearNamedBufferSubData()
void GLAPIENTRY _mesa_ClearNamedBufferSubData (GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const GLvoid * data)
References _mesa_clear_buffer_sub_data(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_copy_buffer_sub_data()
void _mesa_copy_buffer_sub_data (struct gl_context * ctx, struct gl_buffer_object * src, struct gl_buffer_object * dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size, const char * func)
References _mesa_check_disallowed_mapping(), _mesa_error(), dd_function_table::CopyBufferSubData, gl_context::Driver, GLAPIENTRY, gl_buffer_object::MinMaxCacheDirty, and gl_buffer_object::Size.
Referenced by _mesa_CopyBufferSubData(), _mesa_CopyNamedBufferSubData(), and _mesa_reference_buffer_object().
_mesa_CopyBufferSubData()
void GLAPIENTRY _mesa_CopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
References _mesa_copy_buffer_sub_data(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_CopyNamedBufferSubData()
void GLAPIENTRY _mesa_CopyNamedBufferSubData (GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
References _mesa_copy_buffer_sub_data(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_CreateBuffers()
void GLAPIENTRY _mesa_CreateBuffers (GLsizei n, GLuint * buffers)
Create a set of buffer objects and store their unique IDs in buffers.
Parameters
n Number of IDs to generate.
buffers Array of n locations to store the IDs.
References create_buffers(), and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_delete_buffer_object()
void _mesa_delete_buffer_object (struct gl_context * ctx, struct gl_buffer_object * bufObj)
Delete a buffer object.
Default callback for the dd_function_table::DeleteBuffer() hook.
References _mesa_align_free(), gl_buffer_object::Data, gl_buffer_object::Label, gl_buffer_object::Mutex, gl_buffer_object::Name, gl_buffer_object::RefCount, vbo_delete_minmax_cache(), and void.
Referenced by _mesa_init_buffer_object_functions(), and _mesa_is_bufferobj().
_mesa_DeleteBuffers()
void GLAPIENTRY _mesa_DeleteBuffers (GLsizei n, const GLuint * ids)
Delete a set of buffer objects.
Parameters
n Number of buffer objects to delete.
ids Array of n buffer object IDs.
References _mesa_BindBufferBase(), _mesa_buffer_unmap_all_mappings(), _mesa_error(), _mesa_HashLockMutex(), _mesa_HashRemoveLocked(), _mesa_HashUnlockMutex(), _mesa_lookup_bufferobj_locked(), _mesa_reference_buffer_object(), bind_buffer_object(), gl_vertex_array_object::BufferBinding, gl_buffer_object::DeletePending, DummyBufferObject, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, gl_vertex_array_object::IndexBufferObj, MAX_FEEDBACK_BUFFERS, gl_buffer_object::Name, and unbind().
Referenced by _mesa_reference_buffer_object().
_mesa_flush_mapped_buffer_range()
void _mesa_flush_mapped_buffer_range (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr length, const char * func)
References _mesa_bufferobj_mapped(), _mesa_error(), gl_buffer_mapping::AccessFlags, gl_extensions::ARB_map_buffer_range, gl_context::Driver, gl_context::Extensions, dd_function_table::FlushMappedBufferRange, GLAPIENTRY, gl_buffer_mapping::Length, MAP_USER, and gl_buffer_object::Mappings.
Referenced by _mesa_FlushMappedBufferRange(), _mesa_FlushMappedNamedBufferRange(), and _mesa_reference_buffer_object().
_mesa_FlushMappedBufferRange()
void GLAPIENTRY _mesa_FlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length)
References _mesa_flush_mapped_buffer_range(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_FlushMappedNamedBufferRange()
void GLAPIENTRY _mesa_FlushMappedNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length)
References _mesa_flush_mapped_buffer_range(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_free_buffer_objects()
void _mesa_free_buffer_objects (struct gl_context * ctx)
References _mesa_reference_buffer_object(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::AtomicBuffer, gl_context::AtomicBufferBindings, gl_uniform_buffer_binding::BufferObject, gl_shader_storage_buffer_binding::BufferObject, gl_atomic_buffer_binding::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_context::DispatchIndirectBuffer, gl_context::DrawIndirectBuffer, GLuint, MAX_COMBINED_ATOMIC_BUFFERS, MAX_COMBINED_SHADER_STORAGE_BUFFERS, MAX_COMBINED_UNIFORM_BUFFERS, gl_context::ParameterBuffer, gl_context::QueryBuffer, gl_context::ShaderStorageBuffer, gl_context::ShaderStorageBufferBindings, gl_context::UniformBuffer, and gl_context::UniformBufferBindings.
Referenced by _mesa_free_context_data(), and _mesa_is_bufferobj().
_mesa_GenBuffers()
void GLAPIENTRY _mesa_GenBuffers (GLsizei n, GLuint * buffers)
Generate a set of unique buffer object IDs and store them in buffers.
Parameters
n Number of IDs to generate.
buffers Array of n locations to store the IDs.
References create_buffers(), and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferParameteri64v()
void GLAPIENTRY _mesa_GetBufferParameteri64v (GLenum target, GLenum pname, GLint64 * params)
References get_buffer(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferParameteriv()
void GLAPIENTRY _mesa_GetBufferParameteriv (GLenum target, GLenum pname, GLint * params)
References get_buffer(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferPointerv()
void GLAPIENTRY _mesa_GetBufferPointerv (GLenum target, GLenum pname, GLvoid ** params)
References _mesa_error(), get_buffer(), GET_CURRENT_CONTEXT, GLAPIENTRY, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_mapping::Pointer.
Referenced by _mesa_reference_buffer_object().
_mesa_GetBufferSubData()
void GLAPIENTRY _mesa_GetBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, GLvoid * data)
References buffer_object_subdata_range_good(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferParameteri64v()
void GLAPIENTRY _mesa_GetNamedBufferParameteri64v (GLuint buffer, GLenum pname, GLint64 * params)
References _mesa_lookup_bufferobj_err(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferParameteriv()
void GLAPIENTRY _mesa_GetNamedBufferParameteriv (GLuint buffer, GLenum pname, GLint * params)
References _mesa_lookup_bufferobj_err(), get_buffer_parameter(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferPointerv()
void GLAPIENTRY _mesa_GetNamedBufferPointerv (GLuint buffer, GLenum pname, GLvoid ** params)
References _mesa_error(), _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_mapping::Pointer.
Referenced by _mesa_reference_buffer_object().
_mesa_GetNamedBufferSubData()
void GLAPIENTRY _mesa_GetNamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, GLvoid * data)
References _mesa_lookup_bufferobj_err(), buffer_object_subdata_range_good(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_handle_bind_buffer_gen()
bool _mesa_handle_bind_buffer_gen (struct gl_context * ctx, GLuint buffer, struct gl_buffer_object ** buf_handle, const char * caller)
References _mesa_error(), _mesa_HashInsert(), gl_context::API, API_OPENGL_CORE, gl_shared_state::BufferObjects, gl_context::Driver, DummyBufferObject, dd_function_table::NewBufferObject, and gl_context::Shared.
Referenced by _mesa_BindBufferBase(), _mesa_BindBufferRange(), _mesa_is_bufferobj(), bind_buffer_object(), and vertex_array_vertex_buffer().
_mesa_init_buffer_object_functions()
void _mesa_init_buffer_object_functions (struct dd_function_table * driver)
Plug default/fallback buffer object functions into the device driver hooks.
References _mesa_buffer_get_subdata(), _mesa_ClearBufferSubData_sw(), _mesa_delete_buffer_object(), _mesa_new_buffer_object(), buffer_data_fallback(), buffer_sub_data_fallback(), dd_function_table::BufferData, dd_function_table::BufferSubData, dd_function_table::ClearBufferSubData, copy_buffer_sub_data_fallback(), dd_function_table::CopyBufferSubData, dd_function_table::DeleteBuffer, flush_mapped_buffer_range_fallback(), dd_function_table::FlushMappedBufferRange, dd_function_table::GetBufferSubData, map_buffer_range_fallback(), dd_function_table::MapBufferRange, dd_function_table::NewBufferObject, unmap_buffer_fallback(), and dd_function_table::UnmapBuffer.
Referenced by _mesa_reference_buffer_object().
_mesa_init_buffer_objects()
void _mesa_init_buffer_objects (struct gl_context * ctx)
Initialize the state associated with buffer objects.
References _mesa_reference_buffer_object(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::AtomicBuffer, gl_context::AtomicBufferBindings, gl_uniform_buffer_binding::BufferObject, gl_shader_storage_buffer_binding::BufferObject, gl_atomic_buffer_binding::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_context::DispatchIndirectBuffer, gl_context::DrawIndirectBuffer, DummyBufferObject, GLuint, MAX_COMBINED_ATOMIC_BUFFERS, MAX_COMBINED_SHADER_STORAGE_BUFFERS, MAX_COMBINED_UNIFORM_BUFFERS, gl_buffer_object::Mutex, gl_shared_state::NullBufferObj, gl_uniform_buffer_binding::Offset, gl_shader_storage_buffer_binding::Offset, gl_atomic_buffer_binding::Offset, gl_context::ParameterBuffer, gl_context::QueryBuffer, gl_buffer_object::RefCount, gl_context::ShaderStorageBuffer, gl_context::ShaderStorageBufferBindings, gl_context::Shared, gl_uniform_buffer_binding::Size, gl_shader_storage_buffer_binding::Size, gl_atomic_buffer_binding::Size, gl_context::UniformBuffer, and gl_context::UniformBufferBindings.
Referenced by _mesa_is_bufferobj(), and init_attrib_groups().
_mesa_initialize_buffer_object()
void _mesa_initialize_buffer_object (struct gl_context * ctx, struct gl_buffer_object * obj, GLuint name)
Initialize a buffer object to default values.
References get_no_minmax_cache(), gl_buffer_object::Mutex, gl_buffer_object::Name, gl_buffer_object::RefCount, gl_buffer_object::Usage, USAGE_DISABLE_MINMAX_CACHE, and gl_buffer_object::UsageHistory.
Referenced by _mesa_is_bufferobj(), and _mesa_new_buffer_object().
_mesa_InvalidateBufferData()
void GLAPIENTRY _mesa_InvalidateBufferData (GLuint buffer)
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_lookup_bufferobj(), DummyBufferObject, GET_CURRENT_CONTEXT, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_InvalidateBufferSubData()
void GLAPIENTRY _mesa_InvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length)
References _mesa_error(), _mesa_lookup_bufferobj(), gl_buffer_mapping::AccessFlags, bufferobj_range_mapped(), DummyBufferObject, GET_CURRENT_CONTEXT, GLAPIENTRY, MAP_USER, gl_buffer_object::Mappings, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_is_bufferobj()
static GLboolean _mesa_is_bufferobj (const struct gl_buffer_object * obj) inline static
Is the given buffer object a user-created buffer object? Mesa uses default buffer objects in several places.
Default buffers always have Name==0. User created buffers have Name!=0.
References _mesa_delete_buffer_object(), _mesa_free_buffer_objects(), _mesa_handle_bind_buffer_gen(), _mesa_init_buffer_objects(), _mesa_initialize_buffer_object(), _mesa_lookup_bufferobj(), _mesa_lookup_bufferobj_err(), _mesa_lookup_bufferobj_locked(), _mesa_multi_bind_lookup_bufferobj(), _mesa_reference_buffer_object_(), _mesa_update_default_objects_buffer_objects(), GLuint, and gl_buffer_object::Name.
Referenced by _mesa_all_buffers_are_unmapped(), _mesa_all_varyings_in_vbos(), _mesa_bind_vertex_buffer(), _mesa_Bitmap(), _mesa_DrawPixels(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_GetTexSubImage_sw(), _mesa_map_pbo_dest(), _mesa_map_pbo_source(), _mesa_map_validate_pbo_dest(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), _mesa_ReadnPixelsARB(), _mesa_unmap_pbo_dest(), _mesa_unmap_pbo_source(), _mesa_unmap_teximage_pbo(), _mesa_validate_MultiDrawElements(), _mesa_validate_pbo_access(), _mesa_validate_pbo_compressed_teximage(), _mesa_validate_pbo_source(), _mesa_validate_pbo_source_compressed(), _mesa_validate_pbo_teximage(), _mesa_vertex_attrib_address(), buffer_object_purgeable(), check_vbo(), get_buffer(), getcompressedteximage_error_check(), pbo_error_check(), unpack_image(), update_array(), valid_dispatch_indirect(), valid_draw_indirect(), valid_draw_indirect_elements(), valid_draw_indirect_parameters(), validate_DrawElements_common(), validate_pbo_access(), and vertex_attrib_binding().
_mesa_IsBuffer()
GLboolean GLAPIENTRY _mesa_IsBuffer (GLuint id)
Determine if ID is the name of a buffer object.
Parameters
id ID of the potential buffer object.
Returns
GL_TRUE if id is the name of a buffer object, GL_FALSE otherwise.
References _mesa_lookup_bufferobj(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyBufferObject, and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object(), and restore_array_attrib().
_mesa_lookup_bufferobj()
struct gl_buffer_object* _mesa_lookup_bufferobj (struct gl_context * ctx, GLuint buffer)
Return the gl_buffer_object for the given ID.
Always return NULL for ID 0.
References _mesa_HashLookup(), gl_shared_state::BufferObjects, and gl_context::Shared.
Referenced by _mesa_BindBufferBase(), _mesa_BindBufferOffsetEXT(), _mesa_BindBufferRange(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_is_bufferobj(), _mesa_IsBuffer(), _mesa_lookup_bufferobj_err(), _mesa_NamedBufferPageCommitmentARB(), bind_buffer_object(), buffer_object_purgeable(), buffer_object_unpurgeable(), get_buffer_object_parameteriv(), get_label_pointer(), lookup_transform_feedback_bufferobj_err(), and vertex_array_vertex_buffer().
_mesa_lookup_bufferobj_err()
struct gl_buffer_object* _mesa_lookup_bufferobj_err (struct gl_context * ctx, GLuint buffer, const char * caller)
A convenience function for direct state access functions that throws GL_INVALID_OPERATION if buffer is not the name of an existing buffer object.
References _mesa_error(), _mesa_lookup_bufferobj(), and DummyBufferObject.
Referenced by _mesa_ClearNamedBufferData(), _mesa_ClearNamedBufferSubData(), _mesa_CopyNamedBufferSubData(), _mesa_FlushMappedNamedBufferRange(), _mesa_GetNamedBufferParameteri64v(), _mesa_GetNamedBufferParameteriv(), _mesa_GetNamedBufferPointerv(), _mesa_GetNamedBufferSubData(), _mesa_GetQueryBufferObjecti64v(), _mesa_GetQueryBufferObjectiv(), _mesa_GetQueryBufferObjectui64v(), _mesa_GetQueryBufferObjectuiv(), _mesa_is_bufferobj(), _mesa_MapNamedBuffer(), _mesa_MapNamedBufferRange(), _mesa_NamedBufferData(), _mesa_NamedBufferStorage(), _mesa_NamedBufferSubData(), _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TextureBuffer(), _mesa_TextureBufferRange(), _mesa_UnmapNamedBuffer(), and _mesa_VertexArrayElementBuffer().
_mesa_lookup_bufferobj_locked()
struct gl_buffer_object* _mesa_lookup_bufferobj_locked (struct gl_context * ctx, GLuint buffer)
References _mesa_HashLookupLocked(), gl_shared_state::BufferObjects, and gl_context::Shared.
Referenced by _mesa_DeleteBuffers(), _mesa_is_bufferobj(), and _mesa_multi_bind_lookup_bufferobj().
_mesa_map_buffer_range()
void* _mesa_map_buffer_range (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr length, GLbitfield access, const char * func)
References _mesa_bufferobj_mapped(), _mesa_enum_to_string(), _mesa_error(), gl_buffer_mapping::AccessFlags, gl_extensions::ARB_buffer_storage, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, BUFFER_USAGE_WARNING, BUFFER_WARNING_CALL_COUNT, gl_context::Driver, gl_context::Extensions, for(), GLAPIENTRY, GLuint, gl_buffer_mapping::Length, MAP_USER, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::Name, gl_buffer_object::NumMapBufferWriteCalls, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, gl_buffer_object::Size, gl_buffer_object::StorageFlags, gl_buffer_object::Usage, and gl_buffer_object::Written.
Referenced by _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_MapNamedBuffer(), _mesa_MapNamedBufferRange(), and _mesa_reference_buffer_object().
_mesa_MapBuffer()
void* GLAPIENTRY _mesa_MapBuffer (GLenum target, GLenum access)
References _mesa_error(), _mesa_map_buffer_range(), get_buffer(), GET_CURRENT_CONTEXT, get_map_buffer_access_flags(), GLAPIENTRY, and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_MapBufferRange()
void* GLAPIENTRY _mesa_MapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
References _mesa_error(), _mesa_map_buffer_range(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_MapNamedBuffer()
void* GLAPIENTRY _mesa_MapNamedBuffer (GLuint buffer, GLenum access)
References _mesa_error(), _mesa_lookup_bufferobj_err(), _mesa_map_buffer_range(), GET_CURRENT_CONTEXT, get_map_buffer_access_flags(), and gl_buffer_object::Size.
Referenced by _mesa_reference_buffer_object().
_mesa_MapNamedBufferRange()
void* GLAPIENTRY _mesa_MapNamedBufferRange (GLuint buffer, GLintptr offset, GLsizeiptr length, GLbitfield access)
References _mesa_error(), _mesa_lookup_bufferobj_err(), _mesa_map_buffer_range(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_multi_bind_lookup_bufferobj()
struct gl_buffer_object* _mesa_multi_bind_lookup_bufferobj (struct gl_context * ctx, const GLuint * buffers, GLuint index, const char * caller)
Look up a buffer object for a multi-bind function.
Unlike _mesa_lookup_bufferobj(), this function also takes care of generating an error if the buffer ID is not zero or the name of an existing buffer object.
If the buffer ID refers to an existing buffer object, a pointer to the buffer object is returned. If the ID is zero, a pointer to the shared NullBufferObj is returned. If the ID is not zero and does not refer to a valid buffer object, this function returns NULL.
This function assumes that the caller has already locked the hash table mutex by calling _mesa_HashLockMutex(ctx->Shared->BufferObjects).
References _mesa_error(), _mesa_lookup_bufferobj_locked(), DummyBufferObject, gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_is_bufferobj(), bind_atomic_buffers(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), and vertex_array_vertex_buffers().
_mesa_NamedBufferData()
void GLAPIENTRY _mesa_NamedBufferData (GLuint buffer, GLsizeiptr size, const GLvoid * data, GLenum usage)
References _mesa_buffer_data(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_NamedBufferPageCommitmentARB()
void GLAPIENTRY _mesa_NamedBufferPageCommitmentARB (GLuint buffer, GLintptr offset, GLsizeiptr size, GLboolean commit)
References _mesa_error(), _mesa_lookup_bufferobj(), buffer_page_commitment(), DummyBufferObject, and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_NamedBufferStorage()
void GLAPIENTRY _mesa_NamedBufferStorage (GLuint buffer, GLsizeiptr size, const GLvoid * data, GLbitfield flags)
References _mesa_buffer_storage(), _mesa_lookup_bufferobj_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_NamedBufferSubData()
void GLAPIENTRY _mesa_NamedBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr size, const GLvoid * data)
References _mesa_buffer_sub_data(), _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_reference_buffer_object()
static void _mesa_reference_buffer_object (struct gl_context * ctx, struct gl_buffer_object ** ptr, struct gl_buffer_object * bufObj) inline static
References _mesa_BindBuffer(), _mesa_BindBufferBase(), _mesa_BindBufferRange(), _mesa_BindBuffersBase(), _mesa_BindBuffersRange(), _mesa_buffer_data(), _mesa_buffer_storage(), _mesa_buffer_sub_data(), _mesa_buffer_unmap_all_mappings(), _mesa_BufferData(), _mesa_BufferPageCommitmentARB(), _mesa_BufferStorage(), _mesa_BufferSubData(), _mesa_clear_buffer_sub_data(), _mesa_ClearBufferData(), _mesa_ClearBufferSubData(), _mesa_ClearBufferSubData_sw(), _mesa_ClearNamedBufferData(), _mesa_ClearNamedBufferSubData(), _mesa_copy_buffer_sub_data(), _mesa_CopyBufferSubData(), _mesa_CopyNamedBufferSubData(), _mesa_CreateBuffers(), _mesa_DeleteBuffers(), _mesa_flush_mapped_buffer_range(), _mesa_FlushMappedBufferRange(), _mesa_FlushMappedNamedBufferRange(), _mesa_GenBuffers(), _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetBufferPointerv(), _mesa_GetBufferSubData(), _mesa_GetNamedBufferParameteri64v(), _mesa_GetNamedBufferParameteriv(), _mesa_GetNamedBufferPointerv(), _mesa_GetNamedBufferSubData(), _mesa_init_buffer_object_functions(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_IsBuffer(), _mesa_map_buffer_range(), _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_MapNamedBuffer(), _mesa_MapNamedBufferRange(), _mesa_NamedBufferData(), _mesa_NamedBufferPageCommitmentARB(), _mesa_NamedBufferStorage(), _mesa_NamedBufferSubData(), _mesa_reference_buffer_object_(), _mesa_total_buffer_object_memory(), _mesa_unmap_buffer(), _mesa_UnmapBuffer(), _mesa_UnmapNamedBuffer(), GLAPIENTRY, and GLuint.
Referenced by _mesa_bind_vertex_buffer(), _mesa_copy_client_array(), _mesa_copy_vertex_buffer_binding(), _mesa_delete_texture_object(), _mesa_delete_vao(), _mesa_DeleteBuffers(), _mesa_free_buffer_objects(), _mesa_free_context_data(), _mesa_free_texture_data(), _mesa_free_transform_feedback(), _mesa_init_buffer_objects(), _mesa_init_pixelstore(), _mesa_init_texture(), _mesa_init_transform_feedback(), _mesa_initialize_vao(), _mesa_PopClientAttrib(), _mesa_set_transform_feedback_binding(), _mesa_update_client_array(), _mesa_VertexArrayElementBuffer(), bind_atomic_buffer(), bind_buffer_base_shader_storage_buffer(), bind_buffer_base_uniform_buffer(), bind_buffer_object(), bind_buffer_range(), bind_buffer_range_shader_storage_buffer(), bind_buffer_range_uniform_buffer(), copy_pixelstore(), delete_bufferobj_cb(), delete_transform_feedback(), free_array_attrib_data(), free_shared_state(), init_array(), save_array_attrib(), set_atomic_buffer_binding(), set_ssbo_binding(), set_ubo_binding(), texture_buffer_range(), unbind_array_object_vbos(), and validate_pbo_access().
_mesa_reference_buffer_object_()
void _mesa_reference_buffer_object_ (struct gl_context * ctx, struct gl_buffer_object ** ptr, struct gl_buffer_object * bufObj)
Set ptr to bufObj w/ reference counting.
This is normally only called from the _mesa_reference_buffer_object() macro when there's a real pointer change.
References _mesa_problem(), dd_function_table::DeleteBuffer, gl_context::Driver, gl_buffer_object::Mutex, and gl_buffer_object::RefCount.
Referenced by _mesa_is_bufferobj(), and _mesa_reference_buffer_object().
_mesa_total_buffer_object_memory()
GLuint _mesa_total_buffer_object_memory (struct gl_context * ctx)
Compute total size (in bytes) of all buffer objects for the given context.
For debugging purposes.
References _mesa_HashWalk(), gl_shared_state::BufferObjects, count_buffer_size(), GLuint, and gl_context::Shared.
Referenced by _mesa_reference_buffer_object().
_mesa_unmap_buffer()
GLboolean _mesa_unmap_buffer (struct gl_context * ctx, struct gl_buffer_object * bufObj, const char * func)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_warning(), gl_buffer_mapping::AccessFlags, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_context::Driver, for(), GLAPIENTRY, GLuint, gl_buffer_mapping::Length, MAP_USER, gl_buffer_object::Mappings, gl_buffer_object::Name, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
Referenced by _mesa_reference_buffer_object(), _mesa_UnmapBuffer(), and _mesa_UnmapNamedBuffer().
_mesa_UnmapBuffer()
GLboolean GLAPIENTRY _mesa_UnmapBuffer (GLenum target)
References _mesa_unmap_buffer(), get_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_buffer_object().
_mesa_UnmapNamedBuffer()
GLboolean GLAPIENTRY _mesa_UnmapNamedBuffer (GLuint buffer)
References _mesa_lookup_bufferobj_err(), _mesa_unmap_buffer(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_buffer_object().
_mesa_update_default_objects_buffer_objects()
void _mesa_update_default_objects_buffer_objects (struct gl_context * ctx)
Update the default buffer objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
References gl_context::Array, gl_array_attrib::ArrayBufferObj, bind_buffer_object(), gl_pixelstore_attrib::BufferObj, gl_vertex_array_object::IndexBufferObj, gl_context::Pack, gl_context::Unpack, and gl_array_attrib::VAO.
Referenced by _mesa_is_bufferobj(), and update_default_objects().