Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
buffers.c File Reference
glReadBuffer, DrawBuffer functions.
#include "glheader.h"
#include "buffers.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "mtypes.h"
#include "util/bitscan.h"
Macros
#define BAD_MASK ~0u
Functions
static GLbitfield supported_buffer_bitmask (const struct gl_context *ctx, const struct gl_framebuffer *fb)
Return bitmask of BUFFER_BIT_* flags indicating which color buffers are available to the rendering context (for drawing or reading).
static GLbitfield draw_buffer_enum_to_bitmask (const struct gl_context *ctx, GLenum buffer)
Helper routine used by glDrawBuffer and glDrawBuffersARB.
static gl_buffer_index read_buffer_enum_to_index (const struct gl_context *ctx, GLenum buffer)
Helper routine used by glReadBuffer.
static bool is_legal_es3_readbuffer_enum (GLenum buf)
static void draw_buffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum buffer, const char *caller)
Called by glDrawBuffer() and glNamedFramebufferDrawBuffer().
void GLAPIENTRY _mesa_DrawBuffer (GLenum buffer)
void GLAPIENTRY _mesa_NamedFramebufferDrawBuffer (GLuint framebuffer, GLenum buf)
static void draw_buffers (struct gl_context *ctx, struct gl_framebuffer *fb, GLsizei n, const GLenum *buffers, const char *caller)
Called by glDrawBuffersARB() and glNamedFramebufferDrawBuffers() to specify the destination color renderbuffers for N fragment program color outputs.
void GLAPIENTRY _mesa_DrawBuffers (GLsizei n, const GLenum *buffers)
void GLAPIENTRY _mesa_NamedFramebufferDrawBuffers (GLuint framebuffer, GLsizei n, const GLenum *bufs)
static void updated_drawbuffers (struct gl_context *ctx, struct gl_framebuffer *fb)
Performs necessary state updates when _mesa_drawbuffers makes an actual change.
void _mesa_drawbuffers (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint n, const GLenum *buffers, const GLbitfield *destMask)
Helper function to set the GL_DRAW_BUFFER state for the given context and FBO.
void _mesa_update_draw_buffers (struct gl_context *ctx)
Update the current drawbuffer's _ColorDrawBufferIndex[] list, etc.
void _mesa_readbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum buffer, gl_buffer_index bufferIndex)
Like.
static void read_buffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum buffer, const char *caller)
Called by glReadBuffer and glNamedFramebufferReadBuffer to set the source renderbuffer for reading pixels.
void GLAPIENTRY _mesa_ReadBuffer (GLenum buffer)
void GLAPIENTRY _mesa_NamedFramebufferReadBuffer (GLuint framebuffer, GLenum src)
Detailed Description
glReadBuffer, DrawBuffer functions.
Macro Definition Documentation
BAD_MASK
#define BAD_MASK ~0u
Referenced by _mesa_drawbuffers(), draw_buffer(), draw_buffer_enum_to_bitmask(), and draw_buffers().
Function Documentation
_mesa_DrawBuffer()
void GLAPIENTRY _mesa_DrawBuffer (GLenum buffer)
References draw_buffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_PopAttrib().
_mesa_DrawBuffers()
void GLAPIENTRY _mesa_DrawBuffers (GLsizei n, const GLenum * buffers)
References draw_buffers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_PopAttrib().
_mesa_drawbuffers()
void _mesa_drawbuffers (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint n, const GLenum * buffers, const GLbitfield * destMask)
Helper function to set the GL_DRAW_BUFFER state for the given context and FBO.
Called via glDrawBuffer(), glDrawBuffersARB()
All error checking will have been done prior to calling this function so nothing should go wrong at this point.
Parameters
ctx current context
fb the desired draw buffer
n number of color outputs to set
buffers array[n] of colorbuffer names, like GL_LEFT.
destMask array[n] of BUFFER_BIT_* bitmasks which correspond to the colorbuffer names. (i.e. GL_FRONT_AND_BACK => BUFFER_BIT_FRONT_LEFT | BUFFER_BIT_BACK_LEFT).
References gl_framebuffer::_ColorDrawBufferIndexes, _mesa_bitcount(), _mesa_is_winsys_fbo(), gl_framebuffer::_NumColorDrawBuffers, BAD_MASK, gl_context::Color, gl_framebuffer::ColorDrawBuffer, gl_context::Const, draw_buffer_enum_to_bitmask(), gl_colorbuffer_attrib::DrawBuffer, GLuint, MAX_DRAW_BUFFERS, gl_constants::MaxDrawBuffers, supported_buffer_bitmask(), and updated_drawbuffers().
Referenced by _mesa_update_draw_buffers(), draw_buffer(), draw_buffers(), handle_first_current(), and update_framebuffer().
_mesa_NamedFramebufferDrawBuffer()
void GLAPIENTRY _mesa_NamedFramebufferDrawBuffer (GLuint framebuffer, GLenum buf)
References _mesa_lookup_framebuffer_err(), draw_buffer(), and GET_CURRENT_CONTEXT.
_mesa_NamedFramebufferDrawBuffers()
void GLAPIENTRY _mesa_NamedFramebufferDrawBuffers (GLuint framebuffer, GLsizei n, const GLenum * bufs)
References _mesa_lookup_framebuffer_err(), draw_buffers(), and GET_CURRENT_CONTEXT.
_mesa_NamedFramebufferReadBuffer()
void GLAPIENTRY _mesa_NamedFramebufferReadBuffer (GLuint framebuffer, GLenum src)
References _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, and read_buffer().
_mesa_readbuffer()
void _mesa_readbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum buffer, gl_buffer_index bufferIndex)
Like.
See also
_mesa_drawbuffers(), this is a helper function for setting GL_READ_BUFFER state for the given context and FBO. Note that all error checking should have been done before calling this function.
Parameters
ctx the rendering context
fb the framebuffer object to update
buffer GL_FRONT, GL_BACK, GL_COLOR_ATTACHMENT0, etc.
bufferIndex the numerical index corresponding to 'buffer'
References gl_framebuffer::_ColorReadBufferIndex, _mesa_is_winsys_fbo(), _NEW_BUFFERS, gl_framebuffer::ColorReadBuffer, gl_context::NewState, gl_context::Pixel, gl_pixel_attrib::ReadBuffer, and gl_context::ReadBuffer.
Referenced by handle_first_current(), and read_buffer().
_mesa_ReadBuffer()
void GLAPIENTRY _mesa_ReadBuffer (GLenum buffer)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and read_buffer().
Referenced by _mesa_PopAttrib().
_mesa_update_draw_buffers()
void _mesa_update_draw_buffers (struct gl_context * ctx)
Update the current drawbuffer's _ColorDrawBufferIndex[] list, etc.
from the context's Color.DrawBuffer[] state. Use when changing contexts.
References _mesa_drawbuffers(), _mesa_is_winsys_fbo(), gl_context::Color, gl_context::Const, gl_colorbuffer_attrib::DrawBuffer, gl_context::DrawBuffer, and gl_constants::MaxDrawBuffers.
Referenced by _mesa_make_current().
draw_buffer()
static void draw_buffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum buffer, const char * caller) static
Called by glDrawBuffer() and glNamedFramebufferDrawBuffer().
Specify which renderbuffer(s) to draw into for the first color output. <buffer> can name zero, one, two or four renderbuffers!
See also
_mesa_DrawBuffers
Parameters
buffer buffer token such as GL_LEFT or GL_FRONT_AND_BACK, etc.
Note that the behaviour of this function depends on whether the current ctx->DrawBuffer is a window-system framebuffer or a user-created framebuffer object. In the former case, we update the per-context ctx->Color.DrawBuffer state var and the FB's ColorDrawBuffer state. In the later case, we update the FB's ColorDrawBuffer state only.
Furthermore, upon a MakeCurrent() or BindFramebuffer() call, if the new FB is a window system FB, we need to re-update the FB's ColorDrawBuffer state to match the context. This is handled in _mesa_update_framebuffer().
See the GL_EXT_framebuffer_object spec for more info.
References _mesa_debug(), _mesa_drawbuffers(), _mesa_enum_to_string(), _mesa_error(), BAD_MASK, draw_buffer_enum_to_bitmask(), dd_function_table::DrawBuffer, gl_context::DrawBuffer, dd_function_table::DrawBuffers, gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, MESA_VERBOSE, supported_buffer_bitmask(), and VERBOSE_API.
Referenced by _mesa_DrawBuffer(), and _mesa_NamedFramebufferDrawBuffer().
draw_buffer_enum_to_bitmask()
static GLbitfield draw_buffer_enum_to_bitmask (const struct gl_context * ctx, GLenum buffer) static
Helper routine used by glDrawBuffer and glDrawBuffersARB.
Given a GLenum naming one or more color buffers (such as GL_FRONT_AND_BACK), return the corresponding bitmask of BUFFER_BIT_* flags.
References _mesa_is_gles(), BAD_MASK, BUFFER_BIT_AUX0, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_COLOR0, BUFFER_BIT_COLOR1, BUFFER_BIT_COLOR2, BUFFER_BIT_COLOR3, BUFFER_BIT_COLOR4, BUFFER_BIT_COLOR5, BUFFER_BIT_COLOR6, BUFFER_BIT_COLOR7, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_COUNT, gl_config::doubleBufferMode, gl_context::DrawBuffer, and gl_framebuffer::Visual.
Referenced by _mesa_drawbuffers(), draw_buffer(), and draw_buffers().
draw_buffers()
static void draw_buffers (struct gl_context * ctx, struct gl_framebuffer * fb, GLsizei n, const GLenum * buffers, const char * caller) static
Called by glDrawBuffersARB() and glNamedFramebufferDrawBuffers() to specify the destination color renderbuffers for N fragment program color outputs.
See also
_mesa_DrawBuffer
Parameters
n number of outputs
buffers array [n] of renderbuffer names. Unlike glDrawBuffer, the names cannot specify more than one buffer. For example, GL_FRONT_AND_BACK is illegal. The only exception is GL_BACK that is considered special and allowed as far as n is one since 4.5.
References _mesa_bitcount(), _mesa_drawbuffers(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_gles3(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), gl_context::API, API_OPENGLES2, BAD_MASK, gl_context::Const, draw_buffer_enum_to_bitmask(), dd_function_table::DrawBuffer, gl_context::DrawBuffer, dd_function_table::DrawBuffers, gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, GLuint, MAX_DRAW_BUFFERS, gl_constants::MaxColorAttachments, gl_constants::MaxDrawBuffers, supported_buffer_bitmask(), and gl_context::Version.
Referenced by _mesa_DrawBuffers(), and _mesa_NamedFramebufferDrawBuffers().
is_legal_es3_readbuffer_enum()
static bool is_legal_es3_readbuffer_enum (GLenum buf) static
Referenced by read_buffer().
read_buffer()
static void read_buffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum buffer, const char * caller) static
Called by glReadBuffer and glNamedFramebufferReadBuffer to set the source renderbuffer for reading pixels.
Parameters
mode color buffer such as GL_FRONT, GL_BACK, etc.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_gles3(), _mesa_readbuffer(), gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, is_legal_es3_readbuffer_enum(), MESA_VERBOSE, read_buffer_enum_to_index(), dd_function_table::ReadBuffer, gl_context::ReadBuffer, supported_buffer_bitmask(), and VERBOSE_API.
Referenced by _mesa_NamedFramebufferReadBuffer(), and _mesa_ReadBuffer().
read_buffer_enum_to_index()
static gl_buffer_index read_buffer_enum_to_index (const struct gl_context * ctx, GLenum buffer) static
Helper routine used by glReadBuffer.
Given a GLenum naming a color buffer, return the index of the corresponding renderbuffer (a BUFFER_* value). return -1 for an invalid buffer.
References _mesa_is_gles(), BUFFER_AUX0, BUFFER_BACK_LEFT, BUFFER_BACK_RIGHT, BUFFER_COLOR0, BUFFER_COLOR1, BUFFER_COLOR2, BUFFER_COLOR3, BUFFER_COLOR4, BUFFER_COLOR5, BUFFER_COLOR6, BUFFER_COLOR7, BUFFER_COUNT, BUFFER_FRONT_LEFT, BUFFER_FRONT_RIGHT, gl_config::doubleBufferMode, gl_context::DrawBuffer, and gl_framebuffer::Visual.
Referenced by read_buffer().
supported_buffer_bitmask()
static GLbitfield supported_buffer_bitmask (const struct gl_context * ctx, const struct gl_framebuffer * fb) static
Return bitmask of BUFFER_BIT_* flags indicating which color buffers are available to the rendering context (for drawing or reading).
This depends on the type of framebuffer. For window system framebuffers we look at the framebuffer's visual. But for user-create framebuffers we look at the number of supported color attachments.
Parameters
fb the framebuffer to draw to, or read from
Returns
bitmask of BUFFER_BIT_* flags
References _mesa_is_user_fbo(), BUFFER_BIT_AUX0, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_COLOR0, gl_context::Const, gl_config::doubleBufferMode, gl_constants::MaxColorAttachments, gl_config::numAuxBuffers, gl_config::stereoMode, and gl_framebuffer::Visual.
Referenced by _mesa_drawbuffers(), draw_buffer(), draw_buffers(), and read_buffer().
updated_drawbuffers()
static void updated_drawbuffers (struct gl_context * ctx, struct gl_framebuffer * fb) static
Performs necessary state updates when _mesa_drawbuffers makes an actual change.
References _mesa_is_user_fbo(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_ES2_compatibility, gl_context::Extensions, and FLUSH_VERTICES.
Referenced by _mesa_drawbuffers().