Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
clear.c File Reference
glClearColor, glClearIndex, glClear() functions.
#include "glheader.h"
#include "clear.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "get.h"
#include "macros.h"
#include "mtypes.h"
#include "state.h"
Macros
#define INVALID_MASK ~0x0U
Returned by make_color_buffer_mask() for errors.
Functions
void GLAPIENTRY _mesa_ClearIndex (GLfloat c)
void GLAPIENTRY _mesa_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Specify the clear values for the color buffers.
void GLAPIENTRY _mesa_ClearColorIiEXT (GLint r, GLint g, GLint b, GLint a)
GL_EXT_texture_integer.
void GLAPIENTRY _mesa_ClearColorIuiEXT (GLuint r, GLuint g, GLuint b, GLuint a)
GL_EXT_texture_integer.
static bool color_buffer_writes_enabled (const struct gl_context *ctx, unsigned idx)
Returns true if color writes are enabled for the given color attachment.
void GLAPIENTRY _mesa_Clear (GLbitfield mask)
Clear buffers.
static GLbitfield make_color_buffer_mask (struct gl_context *ctx, GLint drawbuffer)
Convert the glClearBuffer 'drawbuffer' parameter into a bitmask of BUFFER_BIT_x values.
void GLAPIENTRY _mesa_ClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint *value)
New in GL 3.0 Clear signed integer color buffer or stencil buffer (not depth).
void GLAPIENTRY _mesa_ClearNamedFramebufferiv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint *value)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
void GLAPIENTRY _mesa_ClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint *value)
New in GL 3.0 Clear unsigned integer color buffer (not depth, not stencil).
void GLAPIENTRY _mesa_ClearNamedFramebufferuiv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint *value)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
void GLAPIENTRY _mesa_ClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat *value)
New in GL 3.0 Clear fixed-pt or float color buffer or depth buffer (not stencil).
void GLAPIENTRY _mesa_ClearNamedFramebufferfv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat *value)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
void GLAPIENTRY _mesa_ClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil)
New in GL 3.0 Clear depth/stencil buffer only.
void GLAPIENTRY _mesa_ClearNamedFramebufferfi (GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
Detailed Description
glClearColor, glClearIndex, glClear() functions.
Macro Definition Documentation
INVALID_MASK
#define INVALID_MASK ~0x0U
Returned by make_color_buffer_mask() for errors.
Referenced by _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), and make_color_buffer_mask().
Function Documentation
_mesa_Clear()
void GLAPIENTRY _mesa_Clear (GLbitfield mask)
Clear buffers.
Parameters
mask bit-mask indicating the buffers to be cleared.
Flushes the vertices and verifies the parameter. If __struct gl_contextRec::NewState is set then calls _mesa_update_state() to update gl_frame_buffer::_Xmin, etc. If the rasterization mode is set to GL_RENDER then requests the driver to clear the buffers, via the dd_function_table::Clear callback.
References _mesa_debug(), _mesa_error(), _mesa_is_gles(), _mesa_update_state(), API_OPENGL_CORE, BUFFER_BIT_ACCUM, BUFFER_BIT_DEPTH, BUFFER_BIT_STENCIL, color_buffer_writes_enabled(), FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, MESA_VERBOSE, and VERBOSE_API.
_mesa_ClearBufferfi()
void GLAPIENTRY _mesa_ClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil)
New in GL 3.0 Clear depth/stencil buffer only.
References _mesa_enum_to_string(), _mesa_error(), _mesa_update_state(), BUFFER_BIT_DEPTH, BUFFER_BIT_STENCIL, BUFFER_DEPTH, BUFFER_STENCIL, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
Referenced by _mesa_ClearNamedFramebufferfi().
_mesa_ClearBufferfv()
void GLAPIENTRY _mesa_ClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat * value)
New in GL 3.0 Clear fixed-pt or float color buffer or depth buffer (not stencil).
References _mesa_enum_to_string(), _mesa_error(), _mesa_update_state(), BUFFER_BIT_DEPTH, BUFFER_DEPTH, COPY_4V, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, INVALID_MASK, and make_color_buffer_mask().
Referenced by _mesa_ClearNamedFramebufferfv().
_mesa_ClearBufferiv()
void GLAPIENTRY _mesa_ClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint * value)
New in GL 3.0 Clear signed integer color buffer or stencil buffer (not depth).
References _mesa_enum_to_string(), _mesa_error(), _mesa_update_state(), BUFFER_BIT_STENCIL, BUFFER_STENCIL, COPY_4V, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_MASK, and make_color_buffer_mask().
Referenced by _mesa_ClearNamedFramebufferiv().
_mesa_ClearBufferuiv()
void GLAPIENTRY _mesa_ClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint * value)
New in GL 3.0 Clear unsigned integer color buffer (not depth, not stencil).
References _mesa_enum_to_string(), _mesa_error(), _mesa_update_state(), COPY_4V, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, INVALID_MASK, and make_color_buffer_mask().
Referenced by _mesa_ClearNamedFramebufferuiv().
_mesa_ClearColor()
void GLAPIENTRY _mesa_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Specify the clear values for the color buffers.
Parameters
red red color component.
green green color component.
blue blue color component.
alpha alpha component.
See also
glClearColor().
References GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_ClearColorx(), and _mesa_PopAttrib().
_mesa_ClearColorIiEXT()
void GLAPIENTRY _mesa_ClearColorIiEXT (GLint r, GLint g, GLint b, GLint a)
GL_EXT_texture_integer.
References GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ClearColorIuiEXT()
void GLAPIENTRY _mesa_ClearColorIuiEXT (GLuint r, GLuint g, GLuint b, GLuint a)
GL_EXT_texture_integer.
References GET_CURRENT_CONTEXT.
_mesa_ClearIndex()
void GLAPIENTRY _mesa_ClearIndex (GLfloat c)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
Referenced by _mesa_PopAttrib().
_mesa_ClearNamedFramebufferfi()
void GLAPIENTRY _mesa_ClearNamedFramebufferfi (GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
References _mesa_BindFramebuffer(), _mesa_ClearBufferfi(), _mesa_GetIntegerv(), and GLuint.
_mesa_ClearNamedFramebufferfv()
void GLAPIENTRY _mesa_ClearNamedFramebufferfv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat * value)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
References _mesa_BindFramebuffer(), _mesa_ClearBufferfv(), _mesa_GetIntegerv(), GLAPIENTRY, and GLuint.
_mesa_ClearNamedFramebufferiv()
void GLAPIENTRY _mesa_ClearNamedFramebufferiv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint * value)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
References _mesa_BindFramebuffer(), _mesa_ClearBufferiv(), _mesa_GetIntegerv(), GLAPIENTRY, and GLuint.
_mesa_ClearNamedFramebufferuiv()
void GLAPIENTRY _mesa_ClearNamedFramebufferuiv (GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint * value)
The ClearBuffer framework is so complicated and so riddled with the assumption that the framebuffer is bound that, for now, we will just fake direct state access clearing for the user.
References _mesa_BindFramebuffer(), _mesa_ClearBufferuiv(), _mesa_GetIntegerv(), GLAPIENTRY, and GLuint.
color_buffer_writes_enabled()
static bool color_buffer_writes_enabled (const struct gl_context * ctx, unsigned idx) static
Returns true if color writes are enabled for the given color attachment.
Beyond checking ColorMask, this uses _mesa_format_has_color_component to ignore components that don't actually exist in the format (such as X in XRGB).
References gl_framebuffer::_ColorDrawBuffers, _mesa_format_has_color_component(), gl_context::Color, gl_colorbuffer_attrib::ColorMask, gl_context::DrawBuffer, gl_renderbuffer::Format, GLAPIENTRY, and GLuint.
Referenced by _mesa_Clear().
make_color_buffer_mask()
static GLbitfield make_color_buffer_mask (struct gl_context * ctx, GLint drawbuffer) static
Convert the glClearBuffer 'drawbuffer' parameter into a bitmask of BUFFER_BIT_x values.
Return INVALID_MASK if the drawbuffer value is invalid.
References gl_framebuffer::_ColorDrawBufferIndexes, _mesa_is_gles(), gl_framebuffer::Attachment, BUFFER_BACK_LEFT, BUFFER_BACK_RIGHT, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_FRONT_LEFT, BUFFER_FRONT_RIGHT, gl_framebuffer::ColorDrawBuffer, gl_context::Const, gl_config::doubleBufferMode, gl_context::DrawBuffer, GLAPIENTRY, INVALID_MASK, gl_constants::MaxDrawBuffers, gl_renderbuffer_attachment::Renderbuffer, and gl_framebuffer::Visual.
Referenced by _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), and _mesa_ClearBufferuiv().