Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
clip.h File Reference
#include "glheader.h"
Functions
void _mesa_update_clip_plane (struct gl_context *ctx, GLuint plane)
Update derived clip plane state.
void GLAPIENTRY _mesa_ClipPlane (GLenum plane, const GLdouble *equation)
void GLAPIENTRY _mesa_GetClipPlane (GLenum plane, GLdouble *equation)
Function Documentation
_mesa_ClipPlane()
void GLAPIENTRY _mesa_ClipPlane (GLenum plane, const GLdouble * equation)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_error(), _mesa_transform_vector(), _mesa_update_clip_plane(), _NEW_TRANSFORM, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and TEST_EQ_4V.
Referenced by _mesa_ClipPlanef(), and _mesa_ClipPlanex().
_mesa_GetClipPlane()
void GLAPIENTRY _mesa_GetClipPlane (GLenum plane, GLdouble * equation)
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_GetClipPlanef(), and _mesa_GetClipPlanex().
_mesa_update_clip_plane()
void _mesa_update_clip_plane (struct gl_context * ctx, GLuint plane)
Update derived clip plane state.
References gl_transform_attrib::_ClipUserPlane, _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_transform_vector(), gl_transform_attrib::EyeUserPlane, GLAPIENTRY, GLmatrix::inv, gl_context::ProjectionMatrixStack, gl_matrix_stack::Top, and gl_context::Transform.
Referenced by _mesa_ClipPlane(), and _mesa_set_enable().