Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
colortab.c File Reference
#include "glheader.h"
#include "bufferobj.h"
#include "colortab.h"
#include "context.h"
#include "image.h"
#include "macros.h"
#include "mtypes.h"
#include "pack.h"
#include "pbo.h"
#include "state.h"
#include "teximage.h"
#include "texstate.h"
#include "main/dispatch.h"
Functions
void GLAPIENTRY _mesa_ColorTable (GLenum target, GLenum internalFormat, GLsizei width, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_ColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data)
void GLAPIENTRY _mesa_CopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_GetnColorTableARB (GLenum target, GLenum format, GLenum type, GLsizei bufSize, GLvoid *data)
void GLAPIENTRY _mesa_GetColorTable (GLenum target, GLenum format, GLenum type, GLvoid *data)
void GLAPIENTRY _mesa_ColorTableParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_ColorTableParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_GetColorTableParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetColorTableParameteriv (GLenum target, GLenum pname, GLint *params)
Function Documentation
_mesa_ColorSubTable()
void GLAPIENTRY _mesa_ColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * data)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ColorTable()
void GLAPIENTRY _mesa_ColorTable (GLenum target, GLenum internalFormat, GLsizei width, GLenum format, GLenum type, const GLvoid * data)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ColorTableParameterfv()
void GLAPIENTRY _mesa_ColorTableParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ColorTableParameteriv()
void GLAPIENTRY _mesa_ColorTableParameteriv (GLenum target, GLenum pname, const GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_CopyColorSubTable()
void GLAPIENTRY _mesa_CopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_CopyColorTable()
void GLAPIENTRY _mesa_CopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetColorTable()
void GLAPIENTRY _mesa_GetColorTable (GLenum target, GLenum format, GLenum type, GLvoid * data)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetColorTableParameterfv()
void GLAPIENTRY _mesa_GetColorTableParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetColorTableParameteriv()
void GLAPIENTRY _mesa_GetColorTableParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), and GET_CURRENT_CONTEXT.
_mesa_GetnColorTableARB()
void GLAPIENTRY _mesa_GetnColorTableARB (GLenum target, GLenum format, GLenum type, GLsizei bufSize, GLvoid * data)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.