Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
compute.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_DispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
void GLAPIENTRY _mesa_DispatchComputeIndirect (GLintptr indirect)
void GLAPIENTRY _mesa_DispatchComputeGroupSizeARB (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z)
Function Documentation
_mesa_DispatchCompute()
void GLAPIENTRY _mesa_DispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
References _mesa_debug(), _mesa_validate_DispatchCompute(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, and VERBOSE_API.
_mesa_DispatchComputeGroupSizeARB()
void GLAPIENTRY _mesa_DispatchComputeGroupSizeARB (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z)
References _mesa_debug(), _mesa_validate_DispatchComputeGroupSizeARB(), GET_CURRENT_CONTEXT, GLuint, MESA_VERBOSE, and VERBOSE_API.
_mesa_DispatchComputeIndirect()
void GLAPIENTRY _mesa_DispatchComputeIndirect (GLintptr indirect)
References _mesa_debug(), _mesa_validate_DispatchComputeIndirect(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.