Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
condrender.c File Reference
Conditional rendering functions.
#include "glheader.h"
#include "condrender.h"
#include "enums.h"
#include "mtypes.h"
#include "queryobj.h"
Functions
void GLAPIENTRY _mesa_BeginConditionalRender (GLuint queryId, GLenum mode)
void APIENTRY _mesa_EndConditionalRender (void)
GLboolean _mesa_check_conditional_render (struct gl_context *ctx)
This function is called by software rendering commands (all point, line triangle drawing, glClear, glDrawPixels, glCopyPixels, and glBitmap, glBlitFramebuffer) to determine if subsequent drawing commands should be executed or discarded depending on the current conditional rendering state.
Detailed Description
Conditional rendering functions.
Author
Brian Paul
Function Documentation
_mesa_BeginConditionalRender()
void GLAPIENTRY _mesa_BeginConditionalRender (GLuint queryId, GLenum mode)
References _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_query_object(), gl_query_object::Active, GET_CURRENT_CONTEXT, gl_query_object::Id, and gl_query_object::Target.
_mesa_check_conditional_render()
GLboolean _mesa_check_conditional_render (struct gl_context * ctx)
This function is called by software rendering commands (all point, line triangle drawing, glClear, glDrawPixels, glCopyPixels, and glBitmap, glBlitFramebuffer) to determine if subsequent drawing commands should be executed or discarded depending on the current conditional rendering state.
Ideally, this check would be implemented by the GPU when doing hardware rendering. XXX should this function be called via a new driver hook?
Returns
GL_TRUE if we should render, GL_FALSE if we should discard
References _mesa_enum_to_string(), _mesa_problem(), dd_function_table::CheckQuery, gl_query_state::CondRenderMode, gl_query_state::CondRenderQuery, gl_context::Driver, gl_context::Query, gl_query_object::Ready, gl_query_object::Result, and dd_function_table::WaitQuery.
Referenced by _mesa_accum().
_mesa_EndConditionalRender()
void APIENTRY _mesa_EndConditionalRender (void)
References _mesa_error(), FLUSH_VERTICES, and GET_CURRENT_CONTEXT.