Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
context.h File Reference
Mesa context and visual-related functions.
#include "imports.h"
#include "extensions.h"
#include "mtypes.h"
#include "vbo/vbo.h"
Macros
Macros for flushing buffered rendering commands before state changes,
checking if inside glBegin/glEnd, etc.
#define FLUSH_VERTICES(ctx, newstate)
Flush vertices.
#define FLUSH_CURRENT(ctx, newstate)
Flush current state.
#define ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL(ctx, retval)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair, with return value.
#define ASSERT_OUTSIDE_BEGIN_END(ctx)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair.
Functions
void _mesa_init_constants (struct gl_constants *consts, gl_api api)
Initialize fields of gl_constants (aka ctx->Const.
void _mesa_notifySwapBuffers (struct gl_context *gc)
Swap buffers notification callback.
struct _glapi_table * _mesa_get_dispatch (struct gl_context *ctx)
Get context's current API dispatch table.
void _mesa_set_context_lost_dispatch (struct gl_context *ctx)
static GLboolean _mesa_inside_begin_end (const struct gl_context *ctx)
Are we currently between glBegin and glEnd? During execution, not display list compilation.
static GLboolean _mesa_inside_dlist_begin_end (const struct gl_context *ctx)
Are we currently between glBegin and glEnd in a display list?
static bool _mesa_is_desktop_gl (const struct gl_context *ctx)
Checks if the context is for Desktop GL (Compatibility or Core)
static bool _mesa_is_gles (const struct gl_context *ctx)
Checks if the context is for any GLES version.
static bool _mesa_is_gles3 (const struct gl_context *ctx)
Checks if the context is for GLES 3.0 or later.
static bool _mesa_is_gles31 (const struct gl_context *ctx)
Checks if the context is for GLES 3.1 or later.
static bool _mesa_is_gles32 (const struct gl_context *ctx)
Checks if the context is for GLES 3.2 or later.
static bool _mesa_has_geometry_shaders (const struct gl_context *ctx)
Checks if the context supports geometry shaders.
static bool _mesa_has_compute_shaders (const struct gl_context *ctx)
Checks if the context supports compute shaders.
static GLboolean _mesa_has_tessellation (const struct gl_context *ctx)
Checks if the context supports tessellation.
static bool _mesa_has_texture_cube_map_array (const struct gl_context *ctx)
Visual-related functions
struct gl_config * _mesa_create_visual (GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Allocates a struct gl_config structure and initializes it via _mesa_initialize_visual().
GLboolean _mesa_initialize_visual (struct gl_config *v, GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Makes some sanity checks and fills in the fields of the struct gl_config object with the given parameters.
void _mesa_destroy_visual (struct gl_config *vis)
Destroy a visual and free its memory.
Context-related functions
GLboolean _mesa_initialize_context (struct gl_context *ctx, gl_api api, const struct gl_config *visual, struct gl_context *share_list, const struct dd_function_table *driverFunctions)
Initialize a struct gl_context struct (rendering context).
void _mesa_free_context_data (struct gl_context *ctx)
Free the data associated with the given context.
void _mesa_destroy_context (struct gl_context *ctx)
Destroy a struct gl_context structure.
void _mesa_copy_context (const struct gl_context *src, struct gl_context *dst, GLuint mask)
Copy attribute groups from one context to another.
void _mesa_check_init_viewport (struct gl_context *ctx, GLuint width, GLuint height)
Check if the viewport/scissor size has not yet been initialized.
GLboolean _mesa_make_current (struct gl_context *ctx, struct gl_framebuffer *drawBuffer, struct gl_framebuffer *readBuffer)
Bind the given context to the given drawBuffer and readBuffer and make it the current context for the calling thread.
GLboolean _mesa_share_state (struct gl_context *ctx, struct gl_context *ctxToShare)
Make context 'ctx' share the display lists, textures and programs that are associated with 'ctxToShare'.
struct gl_context * _mesa_get_current_context (void)
Miscellaneous
void _mesa_record_error (struct gl_context *ctx, GLenum error)
Record an error.
void _mesa_finish (struct gl_context *ctx)
Flush commands and wait for completion.
void _mesa_flush (struct gl_context *ctx)
Flush commands.
void GLAPIENTRY _mesa_Finish (void)
Execute glFinish().
void GLAPIENTRY _mesa_Flush (void)
Execute glFlush().
Detailed Description
Mesa context and visual-related functions.
There are three large Mesa data types/classes which are meant to be used by device drivers:
struct gl_context: this contains the Mesa rendering state
struct gl_config: this describes the color buffer (RGB vs. ci), whether or not there's a depth buffer, stencil buffer, etc.
struct gl_framebuffer: contains pointers to the depth buffer, stencil buffer, accum buffer and alpha buffers.
These types should be encapsulated by corresponding device driver data types. See xmesa.h and xmesaP.h for an example.
In OOP terms, struct gl_context, struct gl_config, and struct gl_framebuffer are base classes which the device driver must derive from.
The following functions create and destroy these data types.
Macro Definition Documentation
ASSERT_OUTSIDE_BEGIN_END
#define ASSERT_OUTSIDE_BEGIN_END (ctx)
Value:
do {                                                                    \
   if (_mesa_inside_begin_end(ctx)) {                                   \
      _mesa_error(ctx, GL_INVALID_OPERATION, "Inside glBegin/glEnd");   \
      return;                                                           \
   }                                                                    \
} while (0)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair.
Parameters
ctx GL context.
Referenced by _mesa_ClipControl(), _mesa_DeleteLists(), _mesa_Finish(), _mesa_Flush(), _mesa_GetInternalformati64v(), _mesa_GetInternalformativ(), _mesa_GetVertexArrayiv(), _mesa_ListBase(), _mesa_NewList(), _mesa_VertexArrayElementBuffer(), vertex_array_attrib_binding(), vertex_array_attrib_format(), vertex_array_binding_divisor(), vertex_array_vertex_buffer(), vertex_array_vertex_buffers(), and vertex_attrib_format().
ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL
#define ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL (ctx, retval)
Value:
do {                                                                    \
   if (_mesa_inside_begin_end(ctx)) {                                   \
      _mesa_error(ctx, GL_INVALID_OPERATION, "Inside glBegin/glEnd");   \
      return retval;                                                    \
   }                                                                    \
} while (0)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair, with return value.
Parameters
ctx GL context.
retval value to return in case the assertion fails.
Referenced by _mesa_AreTexturesResident(), _mesa_check_framebuffer_status(), _mesa_ClientWaitSync(), _mesa_FenceSync(), _mesa_GenLists(), _mesa_GetError(), _mesa_GetString(), _mesa_GetStringi(), _mesa_IsBuffer(), _mesa_IsEnabled(), _mesa_IsEnabledi(), _mesa_IsFramebuffer(), _mesa_IsList(), _mesa_IsProgramARB(), _mesa_IsQuery(), _mesa_IsRenderbuffer(), _mesa_IsSampler(), _mesa_IsSync(), _mesa_IsTexture(), _mesa_IsTransformFeedback(), _mesa_IsVertexArray(), _mesa_map_buffer_range(), _mesa_ObjectPurgeableAPPLE(), _mesa_ObjectUnpurgeableAPPLE(), _mesa_RenderMode(), and _mesa_unmap_buffer().
FLUSH_CURRENT
#define FLUSH_CURRENT (ctx, newstate)
Value:
do {                                                            \
   if (MESA_VERBOSE & VERBOSE_STATE)                            \
      _mesa_debug(ctx, "FLUSH_CURRENT in %s\n", MESA_FUNCTION); \
   if (ctx->Driver.NeedFlush & FLUSH_UPDATE_CURRENT)            \
      vbo_exec_FlushVertices(ctx, FLUSH_UPDATE_CURRENT);        \
   ctx->NewState |= newstate;                                   \
} while (0)
Flush current state.
Parameters
ctx GL context.
newstate new state.
Checks if dd_function_table::NeedFlush is marked to flush current state, and calls dd_function_table::FlushVertices if so. Marks __struct gl_contextRec::NewState with newstate.
Referenced by _mesa_Bitmap(), _mesa_CallList(), _mesa_Clear(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_ColorMaterial(), _mesa_CopyPixels(), _mesa_DrawPixels(), _mesa_finish(), _mesa_flush(), _mesa_GetMaterialfv(), _mesa_GetMaterialiv(), _mesa_NewList(), _mesa_notifySwapBuffers(), _mesa_PopAttrib(), _mesa_PushAttrib(), _mesa_ReadnPixelsARB(), _mesa_set_enable(), _mesa_validate_DispatchCompute(), _mesa_validate_DispatchComputeGroupSizeARB(), _mesa_validate_DispatchComputeIndirect(), _mesa_validate_DrawArraysIndirect(), _mesa_validate_DrawElements(), _mesa_validate_DrawElementsIndirect(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), _mesa_validate_DrawTransformFeedback(), _mesa_validate_MultiDrawArraysIndirect(), _mesa_validate_MultiDrawArraysIndirectCount(), _mesa_validate_MultiDrawElements(), _mesa_validate_MultiDrawElementsIndirect(), _mesa_validate_MultiDrawElementsIndirectCount(), check_extra(), get_current_attrib(), rasterpos(), validate_draw_arrays(), and window_pos3f().
FLUSH_VERTICES
#define FLUSH_VERTICES (ctx, newstate)
Value:
do {                                                            \
   if (MESA_VERBOSE & VERBOSE_STATE)                            \
      _mesa_debug(ctx, "FLUSH_VERTICES in %s\n", MESA_FUNCTION);\
   if (ctx->Driver.NeedFlush & FLUSH_STORED_VERTICES)           \
      vbo_exec_FlushVertices(ctx, FLUSH_STORED_VERTICES);       \
   ctx->NewState |= newstate;                                   \
} while (0)
Flush vertices.
Parameters
ctx GL context.
newstate new state.
Checks if dd_function_table::NeedFlush is marked to flush stored vertices, and calls dd_function_table::FlushVertices if so. Marks __struct gl_contextRec::NewState with newstate.
Referenced by _mesa_Accum(), _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_BeginFragmentShaderATI(), _mesa_BeginQueryIndexed(), _mesa_BeginTransformFeedback(), _mesa_bind_framebuffers(), _mesa_bind_pipeline(), _mesa_bind_sampler(), _mesa_bind_vertex_buffer(), _mesa_BindFragmentShaderATI(), _mesa_BindImageTexture(), _mesa_BindImageTextures(), _mesa_BindProgramARB(), _mesa_BindSamplers(), _mesa_Bitmap(), _mesa_BlendColor(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_BlendFuncSeparateiARB(), _mesa_blit_framebuffer(), _mesa_buffer_data(), _mesa_buffer_storage(), _mesa_ClampColor(), _mesa_Clear(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_ClientActiveTexture(), _mesa_ClipControl(), _mesa_ClipPlane(), _mesa_ColorMask(), _mesa_ColorMaski(), _mesa_ColorMaterial(), _mesa_ColorPointer(), _mesa_compressed_texture_sub_image(), _mesa_copy_texture_sub_image(), _mesa_CopyPixels(), _mesa_CullFace(), _mesa_delete_nameless_texture(), _mesa_DeleteBuffers(), _mesa_DeleteFragmentShaderATI(), _mesa_DeleteFramebuffers(), _mesa_DeleteLists(), _mesa_DeleteObjectARB(), _mesa_DeleteProgram(), _mesa_DeleteProgramsARB(), _mesa_DeleteQueries(), _mesa_DeleteRenderbuffers(), _mesa_DeleteSamplers(), _mesa_DeleteShader(), _mesa_DeleteTextures(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthMask(), _mesa_DepthRange(), _mesa_DrawPixels(), _mesa_EdgeFlagPointer(), _mesa_EGLImageTargetRenderbufferStorageOES(), _mesa_EGLImageTargetTexture2DOES(), _mesa_enable_vertex_array_attrib(), _mesa_EndConditionalRender(), _mesa_EndList(), _mesa_EndQueryIndexed(), _mesa_EndTransformFeedback(), _mesa_FeedbackBuffer(), _mesa_finish(), _mesa_flush(), _mesa_FogCoordPointer(), _mesa_Fogfv(), _mesa_framebuffer_renderbuffer(), _mesa_framebuffer_texture(), _mesa_FrontFace(), _mesa_Frustum(), _mesa_generate_texture_mipmap(), _mesa_GenLists(), _mesa_GetMaterialfv(), _mesa_GetMaterialiv(), _mesa_Hint(), _mesa_IndexMask(), _mesa_IndexPointer(), _mesa_InitNames(), _mesa_InterleavedArrays(), _mesa_IsList(), _mesa_light(), _mesa_LightModelfv(), _mesa_LineStipple(), _mesa_LineWidth(), _mesa_link_program(), _mesa_ListBase(), _mesa_LoadIdentity(), _mesa_LoadMatrixf(), _mesa_LoadName(), _mesa_LockArraysEXT(), _mesa_LogicOp(), _mesa_MapGrid1f(), _mesa_MapGrid2f(), _mesa_MinSampleShading(), _mesa_MultiDrawArrays(), _mesa_MultiModeDrawArraysIBM(), _mesa_MultiModeDrawElementsIBM(), _mesa_MultMatrixf(), _mesa_NormalPointer(), _mesa_Ortho(), _mesa_PassThrough(), _mesa_PatchParameterfv(), _mesa_PauseTransformFeedback(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), _mesa_PixelTransferf(), _mesa_PixelZoom(), _mesa_PointParameterfv(), _mesa_PointSize(), _mesa_PointSizePointerOES(), _mesa_polygon_offset_clamp(), _mesa_PolygonMode(), _mesa_PolygonStipple(), _mesa_PopAttrib(), _mesa_PopClientAttrib(), _mesa_PopMatrix(), _mesa_PopName(), _mesa_PrimitiveRestartIndex(), _mesa_PrioritizeTextures(), _mesa_ProgramEnvParameter4fARB(), _mesa_ProgramEnvParameter4fvARB(), _mesa_ProgramEnvParameters4fvEXT(), _mesa_ProgramLocalParameter4fARB(), _mesa_ProgramLocalParameters4fvEXT(), _mesa_ProgramStringARB(), _mesa_ProvokingVertex(), _mesa_PushName(), _mesa_ReadnPixelsARB(), _mesa_renderbuffer_storage(), _mesa_RenderMode(), _mesa_ResumeTransformFeedback(), _mesa_Rotatef(), _mesa_SampleCoverage(), _mesa_SampleMaski(), _mesa_Scalef(), _mesa_SecondaryColorPointer(), _mesa_SelectBuffer(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_set_framebuffer_srgb(), _mesa_set_multisample(), _mesa_SetFragmentShaderConstantATI(), _mesa_ShadeModel(), _mesa_ShaderStorageBlockBinding(), _mesa_StencilFunc(), _mesa_StencilFuncSeparate(), _mesa_StencilFuncSeparateATI(), _mesa_StencilMask(), _mesa_StencilMaskSeparate(), _mesa_StencilOp(), _mesa_StencilOpSeparate(), _mesa_test_framebuffer_completeness(), _mesa_TexCoordPointer(), _mesa_TexEnvfv(), _mesa_TexGenfv(), _mesa_texture_parameterIiv(), _mesa_texture_parameterIuiv(), _mesa_texture_sub_image(), _mesa_Translatef(), _mesa_UniformBlockBinding(), _mesa_UniformSubroutinesuiv(), _mesa_UnlockArraysEXT(), _mesa_VertexPointer(), _mesa_Viewport(), _mesa_WindowRectanglesEXT(), bind_atomic_buffer(), bind_atomic_buffers(), bind_shader_storage_buffer(), bind_shader_storage_buffers(), bind_texture(), bind_uniform_buffer(), bind_uniform_buffers(), bind_xfb_buffers(), client_state(), copyteximage(), disable_vertex_array_attrib(), draw_buffer(), draw_buffers(), enable_texture(), flush(), get_compressed_texture_image(), get_texture_image(), incomplete(), map1(), map2(), rasterpos(), read_buffer(), set_combiner_mode(), set_combiner_operand(), set_combiner_scale(), set_combiner_source(), set_env_color(), set_env_mode(), set_scissor_no_notify(), teximage(), texture_buffer_range(), updated_drawbuffers(), use_program(), vertex_array_attrib_format(), vertex_attrib_binding(), vertex_attrib_format(), vertex_binding_divisor(), and window_pos3f().
Function Documentation
_mesa_check_init_viewport()
void _mesa_check_init_viewport (struct gl_context * ctx, GLuint width, GLuint height)
Check if the viewport/scissor size has not yet been initialized.
Initialize the size if the given width and height are non-zero.
References _mesa_set_scissor(), _mesa_set_viewport(), MAX_VIEWPORTS, and gl_context::ViewportInitialized.
Referenced by _mesa_make_current().
_mesa_copy_context()
void _mesa_copy_context (const struct gl_context * src, struct gl_context * dst, GLuint mask)
Copy attribute groups from one context to another.
Parameters
src source context
dst destination context
mask bitwise OR of GL_*_BIT flags
According to the bits specified in mask, copies the corresponding attributes from src into dst. For many of the attributes a simple memcpy is not enough due to the existence of internal pointers in their data structures.
References _mesa_copy_texture_state(), _NEW_ALL, gl_context::Accum, gl_context::Color, gl_context::Const, gl_context::Current, gl_context::Depth, gl_context::Eval, gl_context::Fog, GLuint, gl_context::Hint, gl_context::Light, gl_context::Line, gl_context::List, gl_constants::MaxViewports, gl_context::NewDriverState, gl_context::NewState, gl_context::Pixel, gl_context::Point, gl_context::Polygon, gl_context::PolygonStipple, gl_context::Scissor, gl_context::Stencil, gl_context::Transform, and gl_context::ViewportArray.
_mesa_create_visual()
struct gl_config* _mesa_create_visual (GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Allocates a struct gl_config structure and initializes it via _mesa_initialize_visual().
Parameters
dbFlag double buffering
stereoFlag stereo buffer
depthBits requested bits per depth buffer value. Any value in [0, 32] is acceptable but the actual depth type will be GLushort or GLuint as needed.
stencilBits requested minimum bits per stencil buffer value
accumRedBits,accumGreenBits,accumBlueBits,accumAlphaBits number of bits per color component in accum buffer.
indexBits number of bits per pixel if rgbFlag is GL_FALSE
redBits number of bits per color component in frame buffer for RGB(A) mode. We always use 8 in core Mesa though.
greenBits same as above.
blueBits same as above.
alphaBits same as above.
numSamples not really used.
Returns
pointer to new struct gl_config or NULL if requested parameters can't be met.
Note
Need to add params for level and numAuxBuffers (at least)
References _mesa_initialize_visual(), and CALLOC_STRUCT.
_mesa_destroy_context()
void _mesa_destroy_context (struct gl_context * ctx)
Destroy a struct gl_context structure.
Parameters
ctx GL context.
Calls _mesa_free_context_data() and frees the gl_context object itself.
References _mesa_free_context_data().
_mesa_destroy_visual()
void _mesa_destroy_visual (struct gl_config * vis)
Destroy a visual and free its memory.
Parameters
vis visual.
Frees the visual structure.
_mesa_finish()
void _mesa_finish (struct gl_context * ctx)
Flush commands and wait for completion.
References gl_context::Driver, dd_function_table::Finish, FLUSH_CURRENT, and FLUSH_VERTICES.
Referenced by _mesa_Finish().
_mesa_Finish()
void GLAPIENTRY _mesa_Finish (void)
Execute glFinish().
Calls the #ASSERT_OUTSIDE_BEGIN_END_AND_FLUSH macro and the dd_function_table::Finish driver callback, if not NULL.
References _mesa_finish(), ASSERT_OUTSIDE_BEGIN_END, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_flush()
void _mesa_flush (struct gl_context * ctx)
Flush commands.
References gl_context::Driver, dd_function_table::Flush, FLUSH_CURRENT, FLUSH_VERTICES, and GLAPIENTRY.
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), _mesa_DrawPixels(), _mesa_Flush(), and _mesa_make_current().
_mesa_Flush()
void GLAPIENTRY _mesa_Flush (void)
Execute glFlush().
Calls the #ASSERT_OUTSIDE_BEGIN_END_AND_FLUSH macro and the dd_function_table::Flush driver callback, if not NULL.
References _mesa_flush(), ASSERT_OUTSIDE_BEGIN_END, and GET_CURRENT_CONTEXT.
_mesa_free_context_data()
void _mesa_free_context_data (struct gl_context * ctx)
Free the data associated with the given context.
But doesn't free the struct gl_context struct itself.
See also
_mesa_initialize_context() and init_attrib_groups().
References gl_vertex_program_state::_Current, gl_tess_ctrl_program_state::_Current, gl_tess_eval_program_state::_Current, gl_geometry_program_state::_Current, gl_fragment_program_state::_Current, _mesa_free_attrib_data(), _mesa_free_buffer_objects(), _mesa_free_display_list_data(), _mesa_free_errors_data(), _mesa_free_eval_data(), _mesa_free_matrix_data(), _mesa_free_performance_monitors(), _mesa_free_performance_queries(), _mesa_free_pipeline_data(), _mesa_free_queryobj_data(), _mesa_free_shader_state(), _mesa_free_sync_data(), _mesa_free_texture_data(), _mesa_free_transform_feedback(), _mesa_free_varray_data(), _mesa_get_current_context(), _mesa_make_current(), _mesa_reference_buffer_object(), _mesa_reference_framebuffer(), _mesa_reference_shared_state(), _mesa_reference_vao(), gl_fragment_program_state::_TexEnvProgram, gl_vertex_program_state::_TnlProgram, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::BeginEnd, gl_pixelstore_attrib::BufferObj, gl_context::ContextLost, gl_vertex_program_state::Current, gl_fragment_program_state::Current, gl_context::DefaultPacking, gl_array_attrib::DefaultVAO, gl_context::DrawBuffer, gl_context::Extensions, gl_context::FragmentProgram, gl_context::GeometryProgram, gl_context::MarshalExec, gl_context::OutsideBeginEnd, gl_context::Pack, gl_context::ReadBuffer, gl_context::Save, gl_context::Shared, gl_extensions::String, gl_context::TessCtrlProgram, gl_context::TessEvalProgram, gl_context::Unpack, gl_array_attrib::VAO, gl_context::VersionString, gl_context::VertexProgram, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
Referenced by _mesa_destroy_context().
_mesa_get_current_context()
struct gl_context* _mesa_get_current_context (void)
Returns
pointer to the current GL context for this thread.
Calls _glapi_get_context(). This isn't the fastest way to get the current context. If you need speed, see the GET_CURRENT_CONTEXT macro in context.h.
References _glapi_get_context().
Referenced by _mesa_Fogxv(), _mesa_free_context_data(), _mesa_GetLightxv(), _mesa_GetMaterialxv(), _mesa_GetTexEnvxv(), _mesa_GetTexParameterxv(), _mesa_LightModelxv(), _mesa_Lightxv(), _mesa_make_current(), _mesa_Materialx(), _mesa_Materialxv(), _mesa_PointParameterxv(), _mesa_TexEnvx(), _mesa_TexEnvxv(), and _mesa_TexParameterxv().
_mesa_get_dispatch()
struct _glapi_table* _mesa_get_dispatch (struct gl_context * ctx)
Get context's current API dispatch table.
It'll either be the immediate-mode execute dispatcher, the display list compile dispatcher, or the thread marshalling dispatcher.
Parameters
ctx GL context.
Returns
pointer to dispatch_table.
Simply returns __struct gl_contextRec::CurrentClientDispatch.
References gl_context::CurrentClientDispatch.
_mesa_has_compute_shaders()
static bool _mesa_has_compute_shaders (const struct gl_context * ctx) inline static
Checks if the context supports compute shaders.
References gl_context::API, API_OPENGLES2, and gl_context::Version.
Referenced by _mesa_GetInternalformativ(), _mesa_GetProgramPipelineiv(), _mesa_GetProgramResourceLocation(), _mesa_UseProgramStages(), _mesa_validate_shader_target(), check_valid_to_compute(), find_value_indexed(), get_buffer_target(), get_programiv(), get_query_binding_point(), and supported_interface_enum().
_mesa_has_geometry_shaders()
static bool _mesa_has_geometry_shaders (const struct gl_context * ctx) inline static
Checks if the context supports geometry shaders.
References _mesa_is_desktop_gl(), and gl_context::Version.
Referenced by _mesa_FramebufferTexture(), _mesa_get_framebuffer_attachment_parameter(), _mesa_GetInternalformativ(), _mesa_GetProgramPipelineiv(), _mesa_GetProgramResourceLocation(), _mesa_is_valid_prim_mode(), _mesa_NamedFramebufferTexture(), _mesa_UseProgramStages(), _mesa_validate_shader_target(), check_extra(), get_programiv(), get_query_binding_point(), and supported_interface_enum().
_mesa_has_tessellation()
static GLboolean _mesa_has_tessellation (const struct gl_context * ctx) inline static
Checks if the context supports tessellation.
Referenced by _mesa_GetInternalformativ(), _mesa_GetProgramPipelineiv(), _mesa_GetProgramResourceLocation(), _mesa_is_valid_prim_mode(), _mesa_PatchParameterfv(), _mesa_PatchParameteri(), _mesa_UseProgramStages(), _mesa_validate_shader_target(), check_extra(), get_programiv(), get_query_binding_point(), and supported_interface_enum().
_mesa_has_texture_cube_map_array()
static bool _mesa_has_texture_cube_map_array (const struct gl_context * ctx) inline static
Referenced by _mesa_get_current_tex_object(), _mesa_is_valid_generate_texture_mipmap_target(), _mesa_legal_get_tex_level_parameter_target(), _mesa_legal_texture_base_format_for_target(), _mesa_max_texture_levels(), _mesa_target_can_be_compressed(), _mesa_tex_target_to_index(), compressed_subtexture_target_check(), legal_teximage_target(), legal_texobj_target(), legal_texsubimage_target(), and tex_binding_to_index().
_mesa_init_constants()
void _mesa_init_constants (struct gl_constants * consts, gl_api api)
Initialize fields of gl_constants (aka ctx->Const.
*). Use defaults from config.h. The device drivers will often override some of these values (such as number of texture units).
GL_ARB_uniform_buffer_object
GL_ARB_shader_storage_buffer_object
GL_ARB_viewport_array
GL_EXT_gpu_shader4
GL_ARB_gpu_shader5
GL_KHR_context_flush_control
GL_ARB_tessellation_shader
GL_ARB_compute_variable_group_size
References _mesa_override_glsl_version(), API_OPENGL_CORE, ATOMIC_COUNTER_SIZE, gl_constants::ContextReleaseBehavior, FLOAT_AS_UNION(), gl_constants::GenerateTemporaryNames, gl_constants::GLSLVersion, init_program_limits(), gl_constants::LayerAndVPIndexProvokingVertex, LINE_WIDTH_GRANULARITY, gl_constants::LineWidthGranularity, gl_constants::Max, gl_constants::Max3DTextureLevels, MAX_3D_TEXTURE_LEVELS, MAX_ARRAY_LOCK_SIZE, MAX_ARRAY_TEXTURE_LAYERS, MAX_ATOMIC_COUNTERS, MAX_COLOR_ATTACHMENTS, MAX_COMBINED_ATOMIC_BUFFERS, MAX_COMBINED_TEXTURE_IMAGE_UNITS, MAX_CUBE_TEXTURE_LEVELS, MAX_DRAW_BUFFERS, MAX_FEEDBACK_ATTRIBS, MAX_FEEDBACK_BUFFERS, MAX_FRAGMENT_INTERPOLATION_OFFSET, MAX_GEOMETRY_OUTPUT_VERTICES, MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS, MAX_LIGHTS, MAX_LINE_WIDTH, MAX_PATCH_VERTICES, MAX_POINT_SIZE, MAX_PROGRAM_MATRICES, MAX_PROGRAM_MATRIX_STACK_DEPTH, MAX_RENDERBUFFER_SIZE, MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS, MAX_TESS_GEN_LEVEL, MAX_TESS_PATCH_COMPONENTS, MAX_TEXTURE_COORD_UNITS, MAX_TEXTURE_IMAGE_UNITS, MAX_TEXTURE_LEVELS, MAX_TEXTURE_LOD_BIAS, MAX_TEXTURE_MAX_ANISOTROPY, MAX_TEXTURE_MBYTES, MAX_TEXTURE_RECT_SIZE, MAX_UNIFORMS, MAX_VERTEX_GENERIC_ATTRIBS, gl_constants::MaxArrayLockSize, gl_constants::MaxArrayTextureLayers, gl_constants::MaxAtomicBufferBindings, gl_constants::MaxAtomicBufferSize, gl_constants::MaxClipPlanes, gl_constants::MaxColorAttachments, gl_constants::MaxColorTextureSamples, gl_constants::MaxCombinedAtomicBuffers, gl_constants::MaxCombinedAtomicCounters, gl_constants::MaxCombinedShaderStorageBlocks, gl_constants::MaxCombinedTextureImageUnits, gl_constants::MaxCombinedUniformBlocks, gl_constants::MaxComputeVariableGroupInvocations, gl_constants::MaxComputeVariableGroupSize, gl_constants::MaxComputeWorkGroupCount, gl_constants::MaxComputeWorkGroupInvocations, gl_constants::MaxComputeWorkGroupSize, gl_constants::MaxCubeTextureLevels, gl_constants::MaxDepthTextureSamples, gl_constants::MaxDrawBuffers, gl_constants::MaxElementIndex, gl_constants::MaxFragmentInterpolationOffset, gl_constants::MaxGeometryOutputVertices, gl_constants::MaxGeometryTotalOutputComponents, gl_constants::MaxIntegerSamples, gl_constants::MaxLights, gl_constants::MaxLineWidth, gl_constants::MaxLineWidthAA, gl_constants::MaxPatchVertices, gl_constants::MaxPointSize, gl_constants::MaxPointSizeAA, gl_constants::MaxProgramMatrices, gl_constants::MaxProgramMatrixStackDepth, gl_constants::MaxProgramTexelOffset, gl_constants::MaxProgramTextureGatherOffset, gl_constants::MaxRenderbufferSize, gl_constants::MaxSamples, gl_constants::MaxServerWaitTimeout, gl_constants::MaxShaderStorageBlockSize, gl_constants::MaxShaderStorageBufferBindings, gl_constants::MaxShininess, gl_constants::MaxSpotExponent, gl_constants::MaxTessControlTotalOutputComponents, gl_constants::MaxTessGenLevel, gl_constants::MaxTessPatchComponents, gl_constants::MaxTextureBufferSize, gl_constants::MaxTextureCoordUnits, gl_program_constants::MaxTextureImageUnits, gl_constants::MaxTextureLevels, gl_constants::MaxTextureLodBias, gl_constants::MaxTextureMaxAnisotropy, gl_constants::MaxTextureMbytes, gl_constants::MaxTextureRectSize, gl_constants::MaxTextureUnits, gl_constants::MaxTransformFeedbackBuffers, gl_constants::MaxTransformFeedbackInterleavedComponents, gl_constants::MaxTransformFeedbackSeparateComponents, gl_constants::MaxUniformBlockSize, gl_constants::MaxUniformBufferBindings, gl_constants::MaxUserAssignableUniformLocations, gl_constants::MaxVarying, gl_constants::MaxVertexAttribBindings, gl_constants::MaxVertexAttribRelativeOffset, gl_constants::MaxVertexAttribStride, gl_constants::MaxVertexStreams, gl_constants::MaxViewportHeight, gl_constants::MaxViewports, gl_constants::MaxViewportWidth, gl_constants::Min, MIN_FRAGMENT_INTERPOLATION_OFFSET, MIN_LINE_WIDTH, MIN_POINT_SIZE, gl_constants::MinFragmentInterpolationOffset, gl_constants::MinLineWidth, gl_constants::MinLineWidthAA, gl_constants::MinMapBufferAlignment, gl_constants::MinPointSize, gl_constants::MinPointSizeAA, gl_constants::MinProgramTexelOffset, gl_constants::MinProgramTextureGatherOffset, POINT_SIZE_GRANULARITY, gl_constants::PointSizeGranularity, gl_constants::PrimitiveRestartForPatches, gl_constants::ProfileMask, gl_constants::Program, gl_constants::QuadsFollowProvokingVertexConvention, gl_constants::ResetStrategy, gl_constants::RobustAccess, gl_constants::ShaderStorageBufferOffsetAlignment, SUB_PIXEL_BITS, gl_constants::SubPixelBits, gl_constants::TextureBufferOffsetAlignment, fi_type::u, gl_constants::UniformBooleanTrue, gl_constants::UniformBufferOffsetAlignment, gl_constants::VertexID_is_zero_based, gl_constants::ViewportBounds, and gl_constants::ViewportSubpixelBits.
Referenced by init_attrib_groups().
_mesa_initialize_context()
GLboolean _mesa_initialize_context (struct gl_context * ctx, gl_api api, const struct gl_config * visual, struct gl_context * share_list, const struct dd_function_table * driverFunctions)
Initialize a struct gl_context struct (rendering context).
This includes allocating all the other structs and arrays which hang off of the context by pointers. Note that the driver needs to pass in its dd_function_table here since we need to at least call driverFunctions->NewTextureObject to create the default texture objects.
Called by _mesa_create_context().
Performs the imports and exports callback tables initialization, and miscellaneous one-time initializations. If no shared context is supplied one is allocated, and increase its reference count. Setups the GL API dispatch tables. Initialize the TNL module. Sets the maximum Z buffer depth. Finally queries the MESA_DEBUG and MESA_VERBOSE environment variables for debug flags.
Parameters
ctx the context to initialize
api the GL API type to create the context for
visual describes the visual attributes for this context or NULL to create a configless context
share_list points to context to share textures, display lists, etc with, or NULL
driverFunctions table of device driver functions for this context to use
GL_OES_texture_cube_map says "Initially all texture generation modes are set to REFLECTION_MAP_OES"
References gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _mesa_alloc_dispatch_table(), _mesa_alloc_shared_state(), _mesa_override_gl_version(), _mesa_reference_shared_state(), gl_texgen::_ModeBit, gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_context::BeginEnd, create_beginend_table(), gl_context::CurrentClientDispatch, gl_context::CurrentServerDispatch, gl_context::DrawBuffer, gl_context::Driver, gl_context::Exec, gl_context::FirstTimeCurrent, gl_context::FragmentProgram, dd_function_table::FreeTextureImageBuffer, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, gl_context::HasConfig, init_attrib_groups(), MAX_TEXTURE_UNITS, gl_texgen::Mode, dd_function_table::NewTextureObject, one_time_init(), gl_context::OutsideBeginEnd, gl_context::ReadBuffer, gl_context::Save, gl_context::Shared, TEXGEN_REFLECTION_MAP_NV, gl_context::Texture, gl_context::TextureFormatSupported, gl_texture_attrib::Unit, gl_context::VertexProgram, gl_context::Visual, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
_mesa_initialize_visual()
GLboolean _mesa_initialize_visual (struct gl_config * vis, GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Makes some sanity checks and fills in the fields of the struct gl_config object with the given parameters.
If the caller needs to set additional fields, he should just probably init the whole gl_config object himself.
Returns
GL_TRUE on success, or GL_FALSE on failure.
See also
_mesa_create_visual() above for the parameter description.
References gl_config::accumAlphaBits, gl_config::accumBlueBits, gl_config::accumGreenBits, gl_config::accumRedBits, gl_config::alphaBits, gl_config::blueBits, gl_config::depthBits, gl_config::doubleBufferMode, gl_config::greenBits, gl_config::haveAccumBuffer, gl_config::haveDepthBuffer, gl_config::haveStencilBuffer, gl_config::indexBits, gl_config::level, gl_config::numAuxBuffers, gl_config::redBits, gl_config::rgbBits, gl_config::rgbMode, gl_config::sampleBuffers, gl_config::samples, gl_config::stencilBits, and gl_config::stereoMode.
Referenced by _mesa_create_visual().
_mesa_inside_begin_end()
static GLboolean _mesa_inside_begin_end (const struct gl_context * ctx) inline static
Are we currently between glBegin and glEnd? During execution, not display list compilation.
References dd_function_table::CurrentExecPrimitive, gl_context::Driver, and PRIM_OUTSIDE_BEGIN_END.
_mesa_inside_dlist_begin_end()
static GLboolean _mesa_inside_dlist_begin_end (const struct gl_context * ctx) inline static
Are we currently between glBegin and glEnd in a display list?
References dd_function_table::CurrentSavePrimitive, gl_context::Driver, and PRIM_MAX.
Referenced by _mesa_EndList(), and save_Begin().
_mesa_is_desktop_gl()
static bool _mesa_is_desktop_gl (const struct gl_context * ctx) inline static
Checks if the context is for Desktop GL (Compatibility or Core)
References gl_context::API, API_OPENGL_COMPAT, and API_OPENGL_CORE.
Referenced by _is_target_supported(), _mesa_base_fbo_format(), _mesa_buffer_data(), _mesa_compressed_pixel_storage_error_check(), _mesa_DebugMessageControl(), _mesa_DebugMessageInsert(), _mesa_default_image_unit(), _mesa_error_check_format_and_type(), _mesa_get_compressed_formats(), _mesa_get_framebuffer_attachment_parameter(), _mesa_GetDebugMessageLog(), _mesa_GetInternalformativ(), _mesa_GetObjectLabel(), _mesa_GetObjectPtrLabel(), _mesa_GetPointerv(), _mesa_has_geometry_shaders(), _mesa_Hint(), _mesa_install_save_vtxfmt(), _mesa_is_compressed_format(), _mesa_is_shader_image_format_supported(), _mesa_IsEnabled(), _mesa_legal_get_tex_level_parameter_target(), _mesa_loopback_init_api_table(), _mesa_max_texture_levels(), _mesa_ObjectLabel(), _mesa_ObjectPtrLabel(), _mesa_PixelStorei(), _mesa_PointParameterfv(), _mesa_PopDebugGroup(), _mesa_PushDebugGroup(), _mesa_set_enable(), _mesa_test_framebuffer_completeness(), _mesa_tex_target_to_index(), _pname_valid_for_default_framebuffer(), check_extra(), compressed_subtexture_target_check(), find_value_indexed(), get_attachment(), get_buffer_target(), get_framebuffer_target(), get_map_buffer_access_flags(), get_pipe_stats_binding_point(), get_programiv(), get_render_buffer_parameteriv(), get_tex_parameterfv(), get_tex_parameteriv(), get_vertex_array_attrib(), handle_first_current(), install_vtxfmt(), invalidate_framebuffer_storage(), is_format_color_renderable(), legal_dst_factor(), legal_src_factor(), legal_teximage_target(), legal_texobj_target(), legal_texsubimage_target(), set_sampler_cube_map_seamless(), set_tex_parameterf(), set_tex_parameteri(), tex_binding_to_index(), texture_image_multisample(), type_to_bit(), and validate_texture_wrap_mode().
_mesa_is_gles()
static bool _mesa_is_gles (const struct gl_context * ctx) inline static
Checks if the context is for any GLES version.
References gl_context::API, API_OPENGLES, and API_OPENGLES2.
Referenced by _mesa_base_fbo_format(), _mesa_base_tex_format(), _mesa_BindFramebuffer(), _mesa_BindImageTexture(), _mesa_BindRenderbuffer(), _mesa_blit_framebuffer(), _mesa_Clear(), _mesa_EGLImageTargetTexture2DOES(), _mesa_get_compressed_formats(), _mesa_get_current_tex_object(), _mesa_init_color(), _mesa_is_compressed_format(), _mesa_is_valid_generate_texture_mipmap_target(), _mesa_IsEnabled(), _mesa_make_current(), _mesa_override_gl_version(), _mesa_ReadnPixelsARB(), _mesa_set_enable(), _mesa_test_texobj_completeness(), _mesa_tex_target_to_index(), _mesa_validate_program_pipeline(), attach_shader(), check_textarget(), compressed_format_compatible(), copytexsubimage_error_check(), copytexture_error_check(), draw_buffer_enum_to_bitmask(), get_legal_types_mask(), get_tex_parameterfv(), get_tex_parameteriv(), get_texbuffer_format(), make_color_buffer_mask(), read_buffer_enum_to_index(), set_tex_parameterf(), simplified_access_mode(), test_attachment_completeness(), teximage(), texsubimage_error_check(), texture_error_check(), and update_array_format().
_mesa_is_gles3()
static bool _mesa_is_gles3 (const struct gl_context * ctx) inline static
Checks if the context is for GLES 3.0 or later.
References gl_context::API, API_OPENGLES2, and gl_context::Version.
Referenced by _is_target_supported(), _mesa_base_fbo_format(), _mesa_BeginTransformFeedback(), _mesa_blit_framebuffer(), _mesa_buffer_data(), _mesa_error_check_format_and_type(), _mesa_get_compressed_formats(), _mesa_get_fb0_attachment(), _mesa_get_framebuffer_attachment_parameter(), _mesa_GetInternalformativ(), _mesa_init_renderbuffer(), _mesa_is_compressed_format(), _mesa_is_valid_generate_texture_mipmap_internalformat(), _mesa_IsEnabled(), _mesa_PixelStorei(), _mesa_set_enable(), _mesa_target_can_be_compressed(), _mesa_test_framebuffer_completeness(), _mesa_tex_target_to_index(), _mesa_texture_view_lookup_view_class(), check_extra(), check_valid_to_render(), compressed_subtexture_target_check(), copyteximage(), copytexture_error_check(), draw_buffers(), get_attachment(), get_buffer_target(), get_framebuffer_target(), get_programiv(), get_render_buffer_parameteriv(), get_tex_parameterfv(), get_tex_parameteriv(), get_vertex_array_attrib(), install_vtxfmt(), invalidate_framebuffer_storage(), legal_dst_factor(), legal_teximage_target(), legal_texsubimage_target(), read_buffer(), set_tex_parameterf(), set_tex_parameteri(), tex_binding_to_index(), texture_format_error_check_gles(), validate_draw_arrays(), and validate_DrawElements_common().
_mesa_is_gles31()
static bool _mesa_is_gles31 (const struct gl_context * ctx) inline static
Checks if the context is for GLES 3.1 or later.
References gl_context::API, API_OPENGLES2, and gl_context::Version.
Referenced by _is_target_supported(), _legal_parameters(), _mesa_BindVertexBuffer(), _mesa_IsEnabled(), _mesa_max_texture_levels(), _mesa_set_enable(), _mesa_tex_target_to_index(), _mesa_VertexAttribBinding(), _mesa_VertexBindingDivisor(), check_extra(), find_value_indexed(), framebuffer_parameteri(), get_buffer_target(), get_framebuffer_parameteriv(), get_tex_parameterfv(), get_tex_parameteriv(), get_vertex_array_attrib(), set_tex_parameteri(), set_viewport_no_notify(), texture_image_multisample(), valid_draw_indirect(), vertex_array_vertex_buffer(), and vertex_attrib_format().
_mesa_is_gles32()
static bool _mesa_is_gles32 (const struct gl_context * ctx) inline static
Checks if the context is for GLES 3.2 or later.
References gl_context::API, API_OPENGLES2, and gl_context::Version.
Referenced by check_extra().
_mesa_make_current()
GLboolean _mesa_make_current (struct gl_context * newCtx, struct gl_framebuffer * drawBuffer, struct gl_framebuffer * readBuffer)
Bind the given context to the given drawBuffer and readBuffer and make it the current context for the calling thread.
We'll render into the drawBuffer and read pixels from the readBuffer (i.e. glRead/CopyPixels, glCopyTexImage, etc).
We check that the context's and framebuffer's visuals are compatible and return immediately if they're not.
Parameters
newCtx the new GL context. If NULL then there will be no current GL context.
drawBuffer the drawing framebuffer
readBuffer the reading framebuffer
References _glapi_set_context(), _glapi_set_dispatch(), _mesa_check_init_viewport(), _mesa_debug(), _mesa_flush(), _mesa_get_current_context(), _mesa_is_gles(), _mesa_is_winsys_fbo(), _mesa_reference_framebuffer(), _mesa_update_draw_buffers(), _mesa_warning(), _NEW_BUFFERS, check_compatible(), gl_framebuffer::ColorReadBuffer, gl_context::Const, gl_constants::ContextReleaseBehavior, gl_context::CurrentClientDispatch, gl_config::doubleBufferMode, gl_context::DrawBuffer, gl_context::FirstTimeCurrent, GET_CURRENT_CONTEXT, handle_first_current(), gl_framebuffer::Height, MESA_VERBOSE, gl_context::NewState, gl_context::ReadBuffer, VERBOSE_API, gl_framebuffer::Visual, gl_framebuffer::Width, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
Referenced by _mesa_free_context_data().
_mesa_notifySwapBuffers()
void _mesa_notifySwapBuffers (struct gl_context * ctx)
Swap buffers notification callback.
Parameters
ctx GL context.
Called by window system just before swapping buffers. We have to finish any pending rendering.
References _mesa_debug(), gl_context::Driver, dd_function_table::Flush, FLUSH_CURRENT, MESA_VERBOSE, and VERBOSE_SWAPBUFFERS.
_mesa_record_error()
void _mesa_record_error (struct gl_context * ctx, GLenum error)
Record an error.
Parameters
ctx GL context.
error error code.
Records the given error code and call the driver's dd_function_table::Error function if defined.
See also
This is called via _mesa_error().
References gl_context::ErrorValue.
Referenced by _mesa_error().
_mesa_set_context_lost_dispatch()
void _mesa_set_context_lost_dispatch (struct gl_context * ctx)
References _context_lost_GetQueryObjectuiv(), _context_lost_GetSynciv(), _glapi_get_dispatch_table_size(), _glapi_set_dispatch(), _mesa_GetError(), _mesa_GetGraphicsResetStatusARB(), context_lost_nop_handler(), gl_context::ContextLost, gl_context::CurrentServerDispatch, for(), and GLAPIENTRY.
Referenced by _mesa_GetGraphicsResetStatusARB().
_mesa_share_state()
GLboolean _mesa_share_state (struct gl_context * ctx, struct gl_context * ctxToShare)
Make context 'ctx' share the display lists, textures and programs that are associated with 'ctxToShare'.
Any display lists, textures or programs associated with 'ctx' will be deleted if nobody else is sharing them.
References _mesa_reference_shared_state(), gl_context::Shared, and update_default_objects().