Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
convolve.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_ConvolutionFilter1D (GLenum target, GLenum internalFormat, GLsizei width, GLenum format, GLenum type, const GLvoid *image)
void GLAPIENTRY _mesa_ConvolutionFilter2D (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image)
void GLAPIENTRY _mesa_ConvolutionParameterf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_ConvolutionParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_ConvolutionParameteri (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_ConvolutionParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_CopyConvolutionFilter1D (GLenum target, GLenum internalFormat, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyConvolutionFilter2D (GLenum target, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_GetnConvolutionFilterARB (GLenum target, GLenum format, GLenum type, GLsizei bufSize, GLvoid *image)
void GLAPIENTRY _mesa_GetConvolutionFilter (GLenum target, GLenum format, GLenum type, GLvoid *image)
void GLAPIENTRY _mesa_GetConvolutionParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetConvolutionParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetnSeparableFilterARB (GLenum target, GLenum format, GLenum type, GLsizei rowBufSize, GLvoid *row, GLsizei columnBufSize, GLvoid *column, GLvoid *span)
void GLAPIENTRY _mesa_GetSeparableFilter (GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span)
void GLAPIENTRY _mesa_SeparableFilter2D (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column)
Function Documentation
_mesa_ConvolutionFilter1D()
void GLAPIENTRY _mesa_ConvolutionFilter1D (GLenum target, GLenum internalFormat, GLsizei width, GLenum format, GLenum type, const GLvoid * image)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ConvolutionFilter2D()
void GLAPIENTRY _mesa_ConvolutionFilter2D (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * image)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ConvolutionParameterf()
void GLAPIENTRY _mesa_ConvolutionParameterf (GLenum target, GLenum pname, GLfloat param)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ConvolutionParameterfv()
void GLAPIENTRY _mesa_ConvolutionParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ConvolutionParameteri()
void GLAPIENTRY _mesa_ConvolutionParameteri (GLenum target, GLenum pname, GLint param)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ConvolutionParameteriv()
void GLAPIENTRY _mesa_ConvolutionParameteriv (GLenum target, GLenum pname, const GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_CopyConvolutionFilter1D()
void GLAPIENTRY _mesa_CopyConvolutionFilter1D (GLenum target, GLenum internalFormat, GLint x, GLint y, GLsizei width)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_CopyConvolutionFilter2D()
void GLAPIENTRY _mesa_CopyConvolutionFilter2D (GLenum target, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetConvolutionFilter()
void GLAPIENTRY _mesa_GetConvolutionFilter (GLenum target, GLenum format, GLenum type, GLvoid * image)
References _mesa_GetnConvolutionFilterARB(), and GLAPIENTRY.
_mesa_GetConvolutionParameterfv()
void GLAPIENTRY _mesa_GetConvolutionParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetConvolutionParameteriv()
void GLAPIENTRY _mesa_GetConvolutionParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetnConvolutionFilterARB()
void GLAPIENTRY _mesa_GetnConvolutionFilterARB (GLenum target, GLenum format, GLenum type, GLsizei bufSize, GLvoid * image)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetConvolutionFilter().
_mesa_GetnSeparableFilterARB()
void GLAPIENTRY _mesa_GetnSeparableFilterARB (GLenum target, GLenum format, GLenum type, GLsizei rowBufSize, GLvoid * row, GLsizei columnBufSize, GLvoid * column, GLvoid * span)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetSeparableFilter().
_mesa_GetSeparableFilter()
void GLAPIENTRY _mesa_GetSeparableFilter (GLenum target, GLenum format, GLenum type, GLvoid * row, GLvoid * column, GLvoid * span)
References _mesa_GetnSeparableFilterARB(), and GLAPIENTRY.
_mesa_SeparableFilter2D()
void GLAPIENTRY _mesa_SeparableFilter2D (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * row, const GLvoid * column)
References _mesa_error(), and GET_CURRENT_CONTEXT.