Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
copyimage.c File Reference
#include "context.h"
#include "glheader.h"
#include "errors.h"
#include "enums.h"
#include "copyimage.h"
#include "teximage.h"
#include "texobj.h"
#include "fbobject.h"
#include "textureview.h"
#include "glformats.h"
Enumerations
enum mesa_block_class { BLOCK_CLASS_128_BITS, BLOCK_CLASS_64_BITS }
Functions
static bool prepare_target (struct gl_context *ctx, GLuint name, GLenum target, int level, int z, int depth, struct gl_texture_image **tex_image, struct gl_renderbuffer **renderbuffer, mesa_format *format, GLenum *internalFormat, GLuint *width, GLuint *height, GLuint *num_samples, const char *dbg_prefix)
Prepare the source or destination resource.
static bool check_region_bounds (struct gl_context *ctx, GLenum target, const struct gl_texture_image *tex_image, const struct gl_renderbuffer *renderbuffer, int x, int y, int z, int width, int height, int depth, const char *dbg_prefix)
Check that the x,y,z,width,height,region is within the texture image dimensions.
static bool compressed_format_compatible (const struct gl_context *ctx, GLenum compressedFormat, GLenum otherFormat)
static bool copy_format_compatible (const struct gl_context *ctx, GLenum srcFormat, GLenum dstFormat)
void GLAPIENTRY _mesa_CopyImageSubData (GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
Enumeration Type Documentation
mesa_block_class
enum mesa_block_class
Enumerator
BLOCK_CLASS_128_BITS
BLOCK_CLASS_64_BITS
Function Documentation
_mesa_CopyImageSubData()
void GLAPIENTRY _mesa_CopyImageSubData (GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_format_block_size(), check_region_bounds(), copy_format_compatible(), GET_CURRENT_CONTEXT, GLuint, gl_texture_object::Image, MAX_FACES, MESA_VERBOSE, prepare_target(), gl_texture_object::Target, gl_texture_image::TexObject, and VERBOSE_API.
check_region_bounds()
static bool check_region_bounds (struct gl_context * ctx, GLenum target, const struct gl_texture_image * tex_image, const struct gl_renderbuffer * renderbuffer, int x, int y, int z, int width, int height, int depth, const char * dbg_prefix) static
Check that the x,y,z,width,height,region is within the texture image dimensions.
Returns
true if bounds OK, false if regions is out of bounds
References _mesa_error(), gl_texture_image::Depth, gl_texture_image::Height, gl_renderbuffer::Height, gl_texture_image::Width, and gl_renderbuffer::Width.
Referenced by _mesa_CopyImageSubData().
compressed_format_compatible()
static bool compressed_format_compatible (const struct gl_context * ctx, GLenum compressedFormat, GLenum otherFormat) static
References _mesa_is_astc_format(), _mesa_is_compressed_format(), _mesa_is_gles(), BLOCK_CLASS_128_BITS, and BLOCK_CLASS_64_BITS.
Referenced by copy_format_compatible().
copy_format_compatible()
static bool copy_format_compatible (const struct gl_context * ctx, GLenum srcFormat, GLenum dstFormat) static
References _mesa_is_compressed_format(), _mesa_texture_view_compatible_format(), compressed_format_compatible(), and GLAPIENTRY.
Referenced by _mesa_CopyImageSubData().
prepare_target()
static bool prepare_target (struct gl_context * ctx, GLuint name, GLenum target, int level, int z, int depth, struct gl_texture_image ** tex_image, struct gl_renderbuffer ** renderbuffer, mesa_format * format, GLenum * internalFormat, GLuint * width, GLuint * height, GLuint * num_samples, const char * dbg_prefix) static
Prepare the source or destination resource.
This involves error checking and returning the relevant gl_texture_image or gl_renderbuffer. Note that one of the resulting tex_image or renderbuffer pointers will be NULL and the other will be non-null.
Parameters
name the texture or renderbuffer name
target One of GL_TEXTURE_x target or GL_RENDERBUFFER
level mipmap level
z src or dest Z
depth number of slices/faces/layers to copy
tex_image returns a pointer to a texture image
renderbuffer returns a pointer to a renderbuffer
Returns
true if success, false if error
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_texture_complete(), _mesa_lookup_renderbuffer(), _mesa_lookup_texture(), _mesa_select_tex_image(), _mesa_test_texobj_completeness(), gl_renderbuffer::Format, GL_TEXTURE_EXTERNAL_OES, gl_renderbuffer::Height, gl_texture_object::Image, gl_renderbuffer::InternalFormat, MAX_FACES, MAX_TEXTURE_LEVELS, gl_renderbuffer::Name, gl_renderbuffer::NumSamples, gl_texture_object::Sampler, gl_texture_object::Target, and gl_renderbuffer::Width.
Referenced by _mesa_CopyImageSubData().