Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
debug_output.h File Reference
#include <stdio.h>
#include <stdarg.h>
#include "compiler.h"
#include "glheader.h"
#include "mtypes.h"
Functions
void _mesa_init_debug_output (struct gl_context *ctx)
void _mesa_free_errors_data (struct gl_context *ctx)
void _mesa_debug_get_id (GLuint *id)
Handles generating a GL_ARB_debug_output message ID generated by the GL or GLSL compiler.
bool _mesa_set_debug_state_int (struct gl_context *ctx, GLenum pname, GLint val)
Set the integer debug state specified by pname.
GLint _mesa_get_debug_state_int (struct gl_context *ctx, GLenum pname)
Query the integer debug state specified by pname.
void * _mesa_get_debug_state_ptr (struct gl_context *ctx, GLenum pname)
Query the pointer debug state specified by pname.
void _mesa_log_msg (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char *buf)
Log a client or driver debug message.
bool _mesa_debug_is_message_enabled (const struct gl_debug_state *debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity)
Returns if the given message source/type/ID tuple is enabled.
void GLAPIENTRY _mesa_DebugMessageInsert (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLchar *buf)
GLuint GLAPIENTRY _mesa_GetDebugMessageLog (GLuint count, GLsizei logSize, GLenum *sources, GLenum *types, GLenum *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog)
void GLAPIENTRY _mesa_DebugMessageControl (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled)
void GLAPIENTRY _mesa_DebugMessageCallback (GLDEBUGPROC callback, const void *userParam)
void GLAPIENTRY _mesa_PushDebugGroup (GLenum source, GLuint id, GLsizei length, const GLchar *message)
void GLAPIENTRY _mesa_PopDebugGroup (void)
void GLAPIENTRY _mesa_StringMarkerGREMEDY (GLsizei len, const GLvoid *string)
Function Documentation
_mesa_debug_get_id()
void _mesa_debug_get_id (GLuint * id)
Handles generating a GL_ARB_debug_output message ID generated by the GL or GLSL compiler.
The GL API has this "ID" mechanism, where the intention is to allow a client to filter in/out messages based on source, type, and ID. Of course, building a giant enum list of all debug output messages that Mesa might generate is ridiculous, so instead we have our caller pass us a pointer to static storage where the ID should get stored. This ID will be shared across all contexts for that message (which seems like a desirable property, even if it's not expected by the spec), but note that it won't be the same between executions if messages aren't generated in the same order.
References DynamicIDMutex, and NextDynamicID.
Referenced by _mesa_error(), _mesa_gl_vdebug(), _mesa_shader_debug(), and debug_message_store().
_mesa_debug_is_message_enabled()
bool _mesa_debug_is_message_enabled (const struct gl_debug_state * debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity)
Returns if the given message source/type/ID tuple is enabled.
References gl_debug_state::CurrentGroup, debug_namespace_get(), gl_debug_state::DebugOutput, gl_debug_state::Groups, and gl_debug_group::Namespaces.
Referenced by _mesa_error(), and log_msg_locked_and_unlock().
_mesa_DebugMessageCallback()
void GLAPIENTRY _mesa_DebugMessageCallback (GLDEBUGPROC callback, const void * userParam)
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::Callback, gl_debug_state::CallbackData, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DebugMessageControl()
void GLAPIENTRY _mesa_DebugMessageControl (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint * ids, GLboolean enabled)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), CONTROL, debug_set_message_enable(), debug_set_message_enable_all(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), GLAPIENTRY, gl_debug_message::severity, gl_debug_message::source, gl_debug_message::type, and validate_params().
_mesa_DebugMessageInsert()
void GLAPIENTRY _mesa_DebugMessageInsert (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLchar * buf)
References _mesa_is_desktop_gl(), _mesa_log_msg(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), GLAPIENTRY, GLuint, INSERT, validate_length(), and validate_params().
_mesa_free_errors_data()
void _mesa_free_errors_data (struct gl_context * ctx)
References gl_context::Debug, debug_destroy(), gl_context::DebugMutex, and GLAPIENTRY.
Referenced by _mesa_free_context_data().
_mesa_get_debug_state_int()
GLint _mesa_get_debug_state_int (struct gl_context * ctx, GLenum pname)
Query the integer debug state specified by pname.
This can be called _mesa_GetIntegerv for example.
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::CurrentGroup, gl_debug_state::DebugOutput, gl_debug_message::length, gl_debug_state::Log, gl_debug_log::Messages, gl_debug_log::NextMessage, gl_debug_log::NumMessages, and gl_debug_state::SyncOutput.
Referenced by _mesa_IsEnabled(), and find_custom_value().
_mesa_get_debug_state_ptr()
void* _mesa_get_debug_state_ptr (struct gl_context * ctx, GLenum pname)
Query the pointer debug state specified by pname.
This can be called _mesa_GetPointerv for example.
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::Callback, and gl_debug_state::CallbackData.
Referenced by _mesa_GetPointerv().
_mesa_GetDebugMessageLog()
GLuint GLAPIENTRY _mesa_GetDebugMessageLog (GLuint count, GLsizei logSize, GLenum * sources, GLenum * types, GLenum * ids, GLenum * severities, GLsizei * lengths, GLchar * messageLog)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), debug_delete_messages(), debug_fetch_message(), debug_severity_enums, debug_source_enums, debug_type_enums, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_debug_message::id, gl_debug_message::length, gl_debug_message::message, gl_debug_message::severity, gl_debug_message::source, gl_debug_message::type, and void.
_mesa_init_debug_output()
void _mesa_init_debug_output (struct gl_context * ctx)
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_context::Const, gl_constants::ContextFlags, DEBUG_CONTEXT, gl_context::DebugMutex, gl_debug_state::DebugOutput, gl_debug_state::LogToStderr, and MESA_DEBUG_FLAGS.
Referenced by init_attrib_groups().
_mesa_log_msg()
void _mesa_log_msg (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char * buf)
Log a client or driver debug message.
References _mesa_lock_debug_state(), and log_msg_locked_and_unlock().
Referenced by _mesa_DebugMessageInsert(), _mesa_error(), _mesa_gl_vdebug(), and _mesa_shader_debug().
_mesa_PopDebugGroup()
void GLAPIENTRY _mesa_PopDebugGroup (void)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::CurrentGroup, debug_get_group_message(), debug_message_clear(), debug_pop_group(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_type(), gl_debug_message::id, gl_debug_message::length, log_msg_locked_and_unlock(), gl_debug_message::message, and gl_debug_message::source.
_mesa_PushDebugGroup()
void GLAPIENTRY _mesa_PushDebugGroup (GLenum source, GLuint id, GLsizei length, const GLchar * message)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::CurrentGroup, debug_get_group_message(), debug_message_store(), debug_push_group(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), GLAPIENTRY, log_msg_locked_and_unlock(), MAX_DEBUG_GROUP_STACK_DEPTH, MESA_DEBUG_SEVERITY_NOTIFICATION, MESA_DEBUG_TYPE_PUSH_GROUP, and validate_length().
_mesa_set_debug_state_int()
bool _mesa_set_debug_state_int (struct gl_context * ctx, GLenum pname, GLint val)
Set the integer debug state specified by pname.
This can be called from _mesa_set_enable for example.
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::DebugOutput, and gl_debug_state::SyncOutput.
Referenced by _mesa_set_enable().
_mesa_StringMarkerGREMEDY()
void GLAPIENTRY _mesa_StringMarkerGREMEDY (GLsizei len, const GLvoid * string)
References _mesa_error(), and GET_CURRENT_CONTEXT.