Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
debug.h File Reference
Debugging functions.
#include "glheader.h"
Functions
void _mesa_print_enable_flags (const char *msg, GLuint flags)
void _mesa_print_state (const char *msg, GLuint state)
void _mesa_print_info (struct gl_context *ctx)
Print information about this Mesa version and build options.
void _mesa_init_debug (struct gl_context *ctx)
Initialize debugging variables from env vars.
void _mesa_write_renderbuffer_image (const struct gl_renderbuffer *rb)
Write renderbuffer image to a ppm file.
void _mesa_dump_texture (GLuint texture, GLuint writeImages)
Dump a single texture.
void _mesa_dump_textures (GLuint writeImages)
Print basic info about all texture objext to stdout.
void _mesa_dump_renderbuffers (GLboolean writeImages)
Print basic info about all renderbuffers to stdout.
void _mesa_dump_color_buffer (const char *filename)
void _mesa_dump_depth_buffer (const char *filename)
void _mesa_dump_stencil_buffer (const char *filename)
void _mesa_dump_image (const char *filename, const void *image, GLuint w, GLuint h, GLenum format, GLenum type)
void _mesa_print_texture (struct gl_context *ctx, struct gl_texture_image *img)
Quick and dirty function to "print" a texture to stdout.
Detailed Description
Debugging functions.
Function Documentation
_mesa_dump_color_buffer()
void _mesa_dump_color_buffer (const char * filename)
References _mesa_PixelStorei(), _mesa_PopClientAttrib(), _mesa_PushClientAttrib(), _mesa_ReadPixels(), GET_CURRENT_CONTEXT, GLuint, and write_ppm().
_mesa_dump_depth_buffer()
void _mesa_dump_depth_buffer (const char * filename)
References _mesa_PixelStorei(), _mesa_PopClientAttrib(), _mesa_PushClientAttrib(), _mesa_ReadPixels(), GET_CURRENT_CONTEXT, GLuint, and write_ppm().
_mesa_dump_image()
void _mesa_dump_image (const char * filename, const void * image, GLuint w, GLuint h, GLenum format, GLenum type)
References _mesa_problem(), GLuint, UNCLAMPED_FLOAT_TO_UBYTE, and write_ppm().
_mesa_dump_renderbuffers()
void _mesa_dump_renderbuffers (GLboolean writeImages)
Print basic info about all renderbuffers to stdout.
If dumpImages is true, write PPM of level[0] image to a file.
References _mesa_HashWalk(), dump_renderbuffer_cb(), GET_CURRENT_CONTEXT, and WriteImages.
_mesa_dump_stencil_buffer()
void _mesa_dump_stencil_buffer (const char * filename)
References _mesa_PixelStorei(), _mesa_PopClientAttrib(), _mesa_PushClientAttrib(), _mesa_ReadPixels(), GET_CURRENT_CONTEXT, GLuint, and write_ppm().
_mesa_dump_texture()
void _mesa_dump_texture (GLuint texture, GLuint writeImages)
Dump a single texture.
References _mesa_lookup_texture(), dump_texture(), and GET_CURRENT_CONTEXT.
_mesa_dump_textures()
void _mesa_dump_textures (GLuint writeImages)
Print basic info about all texture objext to stdout.
If dumpImages is true, write PPM of level[0] image to a file.
References _mesa_HashWalk(), dump_texture_cb(), GET_CURRENT_CONTEXT, and WriteImages.
_mesa_init_debug()
void _mesa_init_debug (struct gl_context * ctx)
Initialize debugging variables from env vars.
References set_debug_flags(), and set_verbose_flags().
Referenced by init_attrib_groups().
_mesa_print_enable_flags()
void _mesa_print_enable_flags (const char * msg, GLuint flags)
_mesa_print_info()
void _mesa_print_info (struct gl_context * ctx)
Print information about this Mesa version and build options.
References _mesa_debug(), _mesa_GetString(), gl_context::Extensions, and gl_extensions::String.
Referenced by handle_first_current().
_mesa_print_state()
void _mesa_print_state (const char * msg, GLuint state)
References _mesa_debug(), _NEW_ARRAY, _NEW_BUFFERS, _NEW_COLOR, _NEW_DEPTH, _NEW_EVAL, _NEW_FOG, _NEW_HINT, _NEW_LIGHT, _NEW_LINE, _NEW_MODELVIEW, _NEW_PIXEL, _NEW_POINT, _NEW_POLYGON, _NEW_POLYGONSTIPPLE, _NEW_PROJECTION, _NEW_RENDERMODE, _NEW_SCISSOR, _NEW_STENCIL, _NEW_TEXTURE_MATRIX, _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, _NEW_TRANSFORM, and _NEW_VIEWPORT.
Referenced by _mesa_update_state_locked().
_mesa_print_texture()
void _mesa_print_texture (struct gl_context * ctx, struct gl_texture_image * img)
Quick and dirty function to "print" a texture to stdout.
References _mesa_problem(), gl_context::Driver, GLuint, gl_texture_image::Height, dd_function_table::MapTextureImage, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_A_UNORM8, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_UNORM8, MESA_FORMAT_RGB_UNORM8, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
_mesa_write_renderbuffer_image()
void _mesa_write_renderbuffer_image (const struct gl_renderbuffer * rb)
Write renderbuffer image to a ppm file.
References gl_renderbuffer::_BaseFormat, _mesa_debug(), _mesa_snprintf(), GET_CURRENT_CONTEXT, gl_renderbuffer::Height, gl_renderbuffer::Name, gl_renderbuffer::Width, and write_ppm().
Referenced by dump_renderbuffer().