Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
debug.c File Reference
#include <stdio.h>
#include "mtypes.h"
#include "attrib.h"
#include "enums.h"
#include "formats.h"
#include "hash.h"
#include "imports.h"
#include "macros.h"
#include "debug.h"
#include "get.h"
#include "pixelstore.h"
#include "readpix.h"
#include "texobj.h"
Macros
#define WRITE_NONE 0
How many texture images (mipmap levels, faces) to write to files.
#define WRITE_ONE 1
#define WRITE_ALL 2
Functions
static const char * tex_target_name (GLenum tgt)
void _mesa_print_state (const char *msg, GLuint state)
void _mesa_print_info (struct gl_context *ctx)
Print information about this Mesa version and build options.
static void set_verbose_flags (const char *str)
Set verbose logging flags.
static void set_debug_flags (const char *str)
Set debugging flags.
void _mesa_init_debug (struct gl_context *ctx)
Initialize debugging variables from env vars.
static void write_ppm (const char *filename, const GLubyte *buffer, int width, int height, int comps, int rcomp, int gcomp, int bcomp, GLboolean invert)
static void write_texture_image (struct gl_texture_object *texObj, GLuint face, GLuint level)
Write a texture image to a ppm file.
void _mesa_write_renderbuffer_image (const struct gl_renderbuffer *rb)
Write renderbuffer image to a ppm file.
static void dump_texture (struct gl_texture_object *texObj, GLuint writeImages)
void _mesa_dump_texture (GLuint texture, GLuint writeImages)
Dump a single texture.
static void dump_texture_cb (GLuint id, void *data, void *userData)
void _mesa_dump_textures (GLuint writeImages)
Print basic info about all texture objext to stdout.
static void dump_renderbuffer (const struct gl_renderbuffer *rb, GLboolean writeImage)
static void dump_renderbuffer_cb (GLuint id, void *data, void *userData)
void _mesa_dump_renderbuffers (GLboolean writeImages)
Print basic info about all renderbuffers to stdout.
void _mesa_dump_color_buffer (const char *filename)
void _mesa_dump_depth_buffer (const char *filename)
void _mesa_dump_stencil_buffer (const char *filename)
void _mesa_dump_image (const char *filename, const void *image, GLuint w, GLuint h, GLenum format, GLenum type)
void _mesa_print_texture (struct gl_context *ctx, struct gl_texture_image *img)
Quick and dirty function to "print" a texture to stdout.
Variables
static GLuint WriteImages
Macro Definition Documentation
WRITE_ALL
#define WRITE_ALL 2
Referenced by dump_texture().
WRITE_NONE
#define WRITE_NONE 0
How many texture images (mipmap levels, faces) to write to files.
WRITE_ONE
#define WRITE_ONE 1
Referenced by dump_texture().
Function Documentation
_mesa_dump_color_buffer()
void _mesa_dump_color_buffer (const char * filename)
References _mesa_PixelStorei(), _mesa_PopClientAttrib(), _mesa_PushClientAttrib(), _mesa_ReadPixels(), GET_CURRENT_CONTEXT, GLuint, and write_ppm().
_mesa_dump_depth_buffer()
void _mesa_dump_depth_buffer (const char * filename)
References _mesa_PixelStorei(), _mesa_PopClientAttrib(), _mesa_PushClientAttrib(), _mesa_ReadPixels(), GET_CURRENT_CONTEXT, GLuint, and write_ppm().
_mesa_dump_image()
void _mesa_dump_image (const char * filename, const void * image, GLuint w, GLuint h, GLenum format, GLenum type)
References _mesa_problem(), GLuint, UNCLAMPED_FLOAT_TO_UBYTE, and write_ppm().
_mesa_dump_renderbuffers()
void _mesa_dump_renderbuffers (GLboolean writeImages)
Print basic info about all renderbuffers to stdout.
If dumpImages is true, write PPM of level[0] image to a file.
References _mesa_HashWalk(), dump_renderbuffer_cb(), GET_CURRENT_CONTEXT, and WriteImages.
_mesa_dump_stencil_buffer()
void _mesa_dump_stencil_buffer (const char * filename)
References _mesa_PixelStorei(), _mesa_PopClientAttrib(), _mesa_PushClientAttrib(), _mesa_ReadPixels(), GET_CURRENT_CONTEXT, GLuint, and write_ppm().
_mesa_dump_texture()
void _mesa_dump_texture (GLuint texture, GLuint writeImages)
Dump a single texture.
References _mesa_lookup_texture(), dump_texture(), and GET_CURRENT_CONTEXT.
_mesa_dump_textures()
void _mesa_dump_textures (GLuint writeImages)
Print basic info about all texture objext to stdout.
If dumpImages is true, write PPM of level[0] image to a file.
References _mesa_HashWalk(), dump_texture_cb(), GET_CURRENT_CONTEXT, and WriteImages.
_mesa_init_debug()
void _mesa_init_debug (struct gl_context * ctx)
Initialize debugging variables from env vars.
References set_debug_flags(), and set_verbose_flags().
Referenced by init_attrib_groups().
_mesa_print_info()
void _mesa_print_info (struct gl_context * ctx)
Print information about this Mesa version and build options.
References _mesa_debug(), _mesa_GetString(), gl_context::Extensions, and gl_extensions::String.
Referenced by handle_first_current().
_mesa_print_state()
void _mesa_print_state (const char * msg, GLuint state)
References _mesa_debug(), _NEW_ARRAY, _NEW_BUFFERS, _NEW_COLOR, _NEW_DEPTH, _NEW_EVAL, _NEW_FOG, _NEW_HINT, _NEW_LIGHT, _NEW_LINE, _NEW_MODELVIEW, _NEW_PIXEL, _NEW_POINT, _NEW_POLYGON, _NEW_POLYGONSTIPPLE, _NEW_PROJECTION, _NEW_RENDERMODE, _NEW_SCISSOR, _NEW_STENCIL, _NEW_TEXTURE_MATRIX, _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, _NEW_TRANSFORM, and _NEW_VIEWPORT.
Referenced by _mesa_update_state_locked().
_mesa_print_texture()
void _mesa_print_texture (struct gl_context * ctx, struct gl_texture_image * img)
Quick and dirty function to "print" a texture to stdout.
References _mesa_problem(), gl_context::Driver, GLuint, gl_texture_image::Height, dd_function_table::MapTextureImage, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_A_UNORM8, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_UNORM8, MESA_FORMAT_RGB_UNORM8, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
_mesa_write_renderbuffer_image()
void _mesa_write_renderbuffer_image (const struct gl_renderbuffer * rb)
Write renderbuffer image to a ppm file.
References gl_renderbuffer::_BaseFormat, _mesa_debug(), _mesa_snprintf(), GET_CURRENT_CONTEXT, gl_renderbuffer::Height, gl_renderbuffer::Name, gl_renderbuffer::Width, and write_ppm().
Referenced by dump_renderbuffer().
dump_renderbuffer()
static void dump_renderbuffer (const struct gl_renderbuffer * rb, GLboolean writeImage) static
References _mesa_enum_to_string(), _mesa_write_renderbuffer_image(), gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, gl_renderbuffer::Name, and gl_renderbuffer::Width.
Referenced by dump_renderbuffer_cb().
dump_renderbuffer_cb()
static void dump_renderbuffer_cb (GLuint id, void * data, void * userData) static
References dump_renderbuffer(), void, and WriteImages.
Referenced by _mesa_dump_renderbuffers().
dump_texture()
static void dump_texture (struct gl_texture_object * texObj, GLuint writeImages) static
References _mesa_get_format_name(), gl_texture_image::Depth, GLuint, gl_texture_image::Height, gl_texture_object::Image, MAX_TEXTURE_LEVELS, gl_texture_object::Name, gl_texture_object::Target, tex_target_name(), gl_texture_image::TexFormat, gl_texture_image::Width, WRITE_ALL, WRITE_ONE, and write_texture_image().
Referenced by _mesa_dump_texture(), and dump_texture_cb().
dump_texture_cb()
static void dump_texture_cb (GLuint id, void * data, void * userData) static
References dump_texture(), void, and WriteImages.
Referenced by _mesa_dump_textures().
set_debug_flags()
static void set_debug_flags (const char * str) static
Set debugging flags.
When these flags are set, Mesa will do additional debug checks or actions.
Parameters
str a comma-separated list of keywords
References DEBUG_ALWAYS_FLUSH, DEBUG_CONTEXT, DEBUG_INCOMPLETE_FBO, DEBUG_INCOMPLETE_TEXTURE, DEBUG_SILENT, GLuint, and MESA_DEBUG_FLAGS.
Referenced by _mesa_init_debug().
set_verbose_flags()
static void set_verbose_flags (const char * str) static
Set verbose logging flags.
When these flags are set, GL API calls in the various categories will be printed to stderr.
Parameters
str a comma-separated list of keywords
References GLuint, MESA_VERBOSE, VERBOSE_API, VERBOSE_DISASSEM, VERBOSE_DISPLAY_LIST, VERBOSE_DRAW, VERBOSE_DRIVER, VERBOSE_LIGHTING, VERBOSE_MATERIAL, VERBOSE_PIPELINE, VERBOSE_STATE, VERBOSE_SWAPBUFFERS, VERBOSE_TEXTURE, and VERBOSE_VARRAY.
Referenced by _mesa_init_debug().
tex_target_name()
static const char* tex_target_name (GLenum tgt) static
References GL_TEXTURE_EXTERNAL_OES, GLuint, and NUM_TEXTURE_TARGETS.
Referenced by dump_texture().
write_ppm()
static void write_ppm (const char * filename, const GLubyte * buffer, int width, int height, int comps, int rcomp, int gcomp, int bcomp, GLboolean invert) static
References x.
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), _mesa_dump_image(), _mesa_dump_stencil_buffer(), _mesa_write_renderbuffer_image(), and write_texture_image().
write_texture_image()
static void write_texture_image (struct gl_texture_object * texObj, GLuint face, GLuint level) static
Write a texture image to a ppm file.
Parameters
face cube face in [0,5]
level mipmap level
References _mesa_snprintf(), gl_texture_image::Depth, GET_CURRENT_CONTEXT, gl_texture_image::Height, gl_texture_object::Image, gl_texture_object::Name, gl_texture_image::Width, and write_ppm().
Referenced by dump_texture().
Variable Documentation
WriteImages
GLuint WriteImages static
Referenced by _mesa_dump_renderbuffers(), _mesa_dump_textures(), dump_renderbuffer_cb(), and dump_texture_cb().