Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
debug_output.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include "context.h"
#include "debug_output.h"
#include "dispatch.h"
#include "enums.h"
#include "imports.h"
#include "hash.h"
#include "mtypes.h"
#include "version.h"
#include "util/hash_table.h"
#include "util/simple_list.h"
Data Structures
struct gl_debug_element
A namespace element.
struct gl_debug_namespace
struct gl_debug_group
struct gl_debug_message
An error, warning, or other piece of debug information for an application to consume via GL_ARB_debug_output/GL_KHR_debug.
struct gl_debug_log
Debug message log.
struct gl_debug_state
Macros
#define INSERT 1
#define CONTROL 2
Functions
static enum mesa_debug_source gl_enum_to_debug_source (GLenum e)
static enum mesa_debug_type gl_enum_to_debug_type (GLenum e)
static enum mesa_debug_severity gl_enum_to_debug_severity (GLenum e)
void _mesa_debug_get_id (GLuint *id)
Handles generating a GL_ARB_debug_output message ID generated by the GL or GLSL compiler.
static void debug_message_clear (struct gl_debug_message *msg)
static void debug_message_store (struct gl_debug_message *msg, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLsizei len, const char *buf)
static void debug_namespace_init (struct gl_debug_namespace *ns)
static void debug_namespace_clear (struct gl_debug_namespace *ns)
static bool debug_namespace_copy (struct gl_debug_namespace *dst, const struct gl_debug_namespace *src)
static bool debug_namespace_set (struct gl_debug_namespace *ns, GLuint id, bool enabled)
Set the state of id in the namespace.
static void debug_namespace_set_all (struct gl_debug_namespace *ns, enum mesa_debug_severity severity, bool enabled)
Set the default state of the namespace for severity.
static bool debug_namespace_get (const struct gl_debug_namespace *ns, GLuint id, enum mesa_debug_severity severity)
Get the state of id in the namespace.
static struct gl_debug_state * debug_create (void)
Allocate and initialize context debug state.
static bool debug_is_group_read_only (const struct gl_debug_state *debug)
Return true if the top debug group points to the group below it.
static bool debug_make_group_writable (struct gl_debug_state *debug)
Make the top debug group writable.
static void debug_clear_group (struct gl_debug_state *debug)
Free the top debug group.
static void debug_destroy (struct gl_debug_state *debug)
Loop through debug group stack tearing down states for filtering debug messages.
static void debug_set_message_enable (struct gl_debug_state *debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, GLboolean enabled)
Sets the state of the given message source/type/ID tuple.
static void debug_set_message_enable_all (struct gl_debug_state *debug, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, GLboolean enabled)
bool _mesa_debug_is_message_enabled (const struct gl_debug_state *debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity)
Returns if the given message source/type/ID tuple is enabled.
static void debug_log_message (struct gl_debug_state *debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLsizei len, const char *buf)
'buf' is not necessarily a null-terminated string.
static const struct gl_debug_message * debug_fetch_message (const struct gl_debug_state *debug)
Return the oldest debug message out of the log.
static void debug_delete_messages (struct gl_debug_state *debug, int count)
Delete the oldest debug messages out of the log.
static struct gl_debug_message * debug_get_group_message (struct gl_debug_state *debug)
static void debug_push_group (struct gl_debug_state *debug)
static void debug_pop_group (struct gl_debug_state *debug)
static struct gl_debug_state * _mesa_lock_debug_state (struct gl_context *ctx)
Lock and return debug state for the context.
static void _mesa_unlock_debug_state (struct gl_context *ctx)
bool _mesa_set_debug_state_int (struct gl_context *ctx, GLenum pname, GLint val)
Set the integer debug state specified by pname.
GLint _mesa_get_debug_state_int (struct gl_context *ctx, GLenum pname)
Query the integer debug state specified by pname.
void * _mesa_get_debug_state_ptr (struct gl_context *ctx, GLenum pname)
Query the pointer debug state specified by pname.
static void log_msg_locked_and_unlock (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char *buf)
Insert a debug message.
void _mesa_log_msg (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char *buf)
Log a client or driver debug message.
static GLboolean validate_params (struct gl_context *ctx, unsigned caller, const char *callerstr, GLenum source, GLenum type, GLenum severity)
Verify that source, type, and severity are valid enums.
static GLboolean validate_length (struct gl_context *ctx, const char *callerstr, GLsizei length, const GLchar *buf)
void GLAPIENTRY _mesa_DebugMessageInsert (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLchar *buf)
GLuint GLAPIENTRY _mesa_GetDebugMessageLog (GLuint count, GLsizei logSize, GLenum *sources, GLenum *types, GLenum *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog)
void GLAPIENTRY _mesa_DebugMessageControl (GLenum gl_source, GLenum gl_type, GLenum gl_severity, GLsizei count, const GLuint *ids, GLboolean enabled)
void GLAPIENTRY _mesa_DebugMessageCallback (GLDEBUGPROC callback, const void *userParam)
void GLAPIENTRY _mesa_PushDebugGroup (GLenum source, GLuint id, GLsizei length, const GLchar *message)
void GLAPIENTRY _mesa_PopDebugGroup (void)
void _mesa_init_debug_output (struct gl_context *ctx)
void _mesa_free_errors_data (struct gl_context *ctx)
void GLAPIENTRY _mesa_StringMarkerGREMEDY (GLsizei len, const GLvoid *string)
Variables
static mtx_t DynamicIDMutex = _MTX_INITIALIZER_NP
static GLuint NextDynamicID = 1
static char out_of_memory [] = "Debugging error: out of memory"
static const GLenum debug_source_enums []
static const GLenum debug_type_enums []
static const GLenum debug_severity_enums []
Macro Definition Documentation
CONTROL
#define CONTROL 2
Referenced by _mesa_DebugMessageControl(), and validate_params().
INSERT
#define INSERT 1
Referenced by _mesa_DebugMessageInsert(), and validate_params().
Function Documentation
_mesa_debug_get_id()
void _mesa_debug_get_id (GLuint * id)
Handles generating a GL_ARB_debug_output message ID generated by the GL or GLSL compiler.
The GL API has this "ID" mechanism, where the intention is to allow a client to filter in/out messages based on source, type, and ID. Of course, building a giant enum list of all debug output messages that Mesa might generate is ridiculous, so instead we have our caller pass us a pointer to static storage where the ID should get stored. This ID will be shared across all contexts for that message (which seems like a desirable property, even if it's not expected by the spec), but note that it won't be the same between executions if messages aren't generated in the same order.
References DynamicIDMutex, and NextDynamicID.
Referenced by _mesa_error(), _mesa_gl_vdebug(), _mesa_shader_debug(), and debug_message_store().
_mesa_debug_is_message_enabled()
bool _mesa_debug_is_message_enabled (const struct gl_debug_state * debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity)
Returns if the given message source/type/ID tuple is enabled.
References gl_debug_state::CurrentGroup, debug_namespace_get(), gl_debug_state::DebugOutput, gl_debug_state::Groups, and gl_debug_group::Namespaces.
Referenced by _mesa_error(), and log_msg_locked_and_unlock().
_mesa_DebugMessageCallback()
void GLAPIENTRY _mesa_DebugMessageCallback (GLDEBUGPROC callback, const void * userParam)
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::Callback, gl_debug_state::CallbackData, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DebugMessageControl()
void GLAPIENTRY _mesa_DebugMessageControl (GLenum gl_source, GLenum gl_type, GLenum gl_severity, GLsizei count, const GLuint * ids, GLboolean enabled)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), CONTROL, debug_set_message_enable(), debug_set_message_enable_all(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), GLAPIENTRY, gl_debug_message::severity, gl_debug_message::source, gl_debug_message::type, and validate_params().
_mesa_DebugMessageInsert()
void GLAPIENTRY _mesa_DebugMessageInsert (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLchar * buf)
References _mesa_is_desktop_gl(), _mesa_log_msg(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), GLAPIENTRY, GLuint, INSERT, validate_length(), and validate_params().
_mesa_free_errors_data()
void _mesa_free_errors_data (struct gl_context * ctx)
References gl_context::Debug, debug_destroy(), gl_context::DebugMutex, and GLAPIENTRY.
Referenced by _mesa_free_context_data().
_mesa_get_debug_state_int()
GLint _mesa_get_debug_state_int (struct gl_context * ctx, GLenum pname)
Query the integer debug state specified by pname.
This can be called _mesa_GetIntegerv for example.
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::CurrentGroup, gl_debug_state::DebugOutput, gl_debug_message::length, gl_debug_state::Log, gl_debug_log::Messages, gl_debug_log::NextMessage, gl_debug_log::NumMessages, and gl_debug_state::SyncOutput.
Referenced by _mesa_IsEnabled(), and find_custom_value().
_mesa_get_debug_state_ptr()
void* _mesa_get_debug_state_ptr (struct gl_context * ctx, GLenum pname)
Query the pointer debug state specified by pname.
This can be called _mesa_GetPointerv for example.
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::Callback, and gl_debug_state::CallbackData.
Referenced by _mesa_GetPointerv().
_mesa_GetDebugMessageLog()
GLuint GLAPIENTRY _mesa_GetDebugMessageLog (GLuint count, GLsizei logSize, GLenum * sources, GLenum * types, GLenum * ids, GLenum * severities, GLsizei * lengths, GLchar * messageLog)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), debug_delete_messages(), debug_fetch_message(), debug_severity_enums, debug_source_enums, debug_type_enums, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_debug_message::id, gl_debug_message::length, gl_debug_message::message, gl_debug_message::severity, gl_debug_message::source, gl_debug_message::type, and void.
_mesa_init_debug_output()
void _mesa_init_debug_output (struct gl_context * ctx)
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_context::Const, gl_constants::ContextFlags, DEBUG_CONTEXT, gl_context::DebugMutex, gl_debug_state::DebugOutput, gl_debug_state::LogToStderr, and MESA_DEBUG_FLAGS.
Referenced by init_attrib_groups().
_mesa_lock_debug_state()
static struct gl_debug_state* _mesa_lock_debug_state (struct gl_context * ctx) static
Lock and return debug state for the context.
The debug state will be allocated and initialized upon the first call. When NULL is returned, the debug state is not locked.
References _mesa_error(), gl_context::Debug, debug_create(), gl_context::DebugMutex, and GET_CURRENT_CONTEXT.
Referenced by _mesa_DebugMessageCallback(), _mesa_DebugMessageControl(), _mesa_get_debug_state_int(), _mesa_get_debug_state_ptr(), _mesa_GetDebugMessageLog(), _mesa_init_debug_output(), _mesa_log_msg(), _mesa_PopDebugGroup(), _mesa_PushDebugGroup(), and _mesa_set_debug_state_int().
_mesa_log_msg()
void _mesa_log_msg (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char * buf)
Log a client or driver debug message.
References _mesa_lock_debug_state(), and log_msg_locked_and_unlock().
Referenced by _mesa_DebugMessageInsert(), _mesa_error(), _mesa_gl_vdebug(), and _mesa_shader_debug().
_mesa_PopDebugGroup()
void GLAPIENTRY _mesa_PopDebugGroup (void)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::CurrentGroup, debug_get_group_message(), debug_message_clear(), debug_pop_group(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_type(), gl_debug_message::id, gl_debug_message::length, log_msg_locked_and_unlock(), gl_debug_message::message, and gl_debug_message::source.
_mesa_PushDebugGroup()
void GLAPIENTRY _mesa_PushDebugGroup (GLenum source, GLuint id, GLsizei length, const GLchar * message)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::CurrentGroup, debug_get_group_message(), debug_message_store(), debug_push_group(), GET_CURRENT_CONTEXT, gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), GLAPIENTRY, log_msg_locked_and_unlock(), MAX_DEBUG_GROUP_STACK_DEPTH, MESA_DEBUG_SEVERITY_NOTIFICATION, MESA_DEBUG_TYPE_PUSH_GROUP, and validate_length().
_mesa_set_debug_state_int()
bool _mesa_set_debug_state_int (struct gl_context * ctx, GLenum pname, GLint val)
Set the integer debug state specified by pname.
This can be called from _mesa_set_enable for example.
References _mesa_lock_debug_state(), _mesa_unlock_debug_state(), gl_debug_state::DebugOutput, and gl_debug_state::SyncOutput.
Referenced by _mesa_set_enable().
_mesa_StringMarkerGREMEDY()
void GLAPIENTRY _mesa_StringMarkerGREMEDY (GLsizei len, const GLvoid * string)
References _mesa_error(), and GET_CURRENT_CONTEXT.
_mesa_unlock_debug_state()
static void _mesa_unlock_debug_state (struct gl_context * ctx) static
References gl_context::DebugMutex.
Referenced by _mesa_DebugMessageCallback(), _mesa_DebugMessageControl(), _mesa_get_debug_state_int(), _mesa_get_debug_state_ptr(), _mesa_GetDebugMessageLog(), _mesa_init_debug_output(), _mesa_PopDebugGroup(), _mesa_PushDebugGroup(), _mesa_set_debug_state_int(), and log_msg_locked_and_unlock().
debug_clear_group()
static void debug_clear_group (struct gl_debug_state * debug) static
Free the top debug group.
References gl_debug_state::CurrentGroup, debug_is_group_read_only(), debug_namespace_clear(), gl_debug_state::Groups, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, and gl_debug_group::Namespaces.
Referenced by debug_destroy(), and debug_pop_group().
debug_create()
static struct gl_debug_state* debug_create (void) static
Allocate and initialize context debug state.
References CALLOC_STRUCT, debug_namespace_init(), gl_debug_state::Groups, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, and gl_debug_group::Namespaces.
Referenced by _mesa_lock_debug_state().
debug_delete_messages()
static void debug_delete_messages (struct gl_debug_state * debug, int count) static
Delete the oldest debug messages out of the log.
References debug_message_clear(), gl_debug_state::Log, MAX_DEBUG_LOGGED_MESSAGES, gl_debug_log::Messages, gl_debug_log::NextMessage, and gl_debug_log::NumMessages.
Referenced by _mesa_GetDebugMessageLog().
debug_destroy()
static void debug_destroy (struct gl_debug_state * debug) static
Loop through debug group stack tearing down states for filtering debug messages.
Then free debug output state.
References gl_debug_state::CurrentGroup, and debug_clear_group().
Referenced by _mesa_free_errors_data().
debug_fetch_message()
static const struct gl_debug_message* debug_fetch_message (const struct gl_debug_state * debug) static
Return the oldest debug message out of the log.
References gl_debug_state::Log, gl_debug_log::Messages, gl_debug_log::NextMessage, and gl_debug_log::NumMessages.
Referenced by _mesa_GetDebugMessageLog().
debug_get_group_message()
static struct gl_debug_message* debug_get_group_message (struct gl_debug_state * debug) static
References gl_debug_state::CurrentGroup, and gl_debug_state::GroupMessages.
Referenced by _mesa_PopDebugGroup(), and _mesa_PushDebugGroup().
debug_is_group_read_only()
static bool debug_is_group_read_only (const struct gl_debug_state * debug) static
Return true if the top debug group points to the group below it.
References gl_debug_state::CurrentGroup, and gl_debug_state::Groups.
Referenced by debug_clear_group(), and debug_make_group_writable().
debug_log_message()
static void debug_log_message (struct gl_debug_state * debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLsizei len, const char * buf) static
'buf' is not necessarily a null-terminated string.
When logging, copy 'len' characters from it, store them in a new, null-terminated string, and remember the number of bytes used by that string, including the null terminator this time.
References _mesa_log(), debug_message_store(), gl_debug_state::Log, gl_debug_state::LogToStderr, MAX_DEBUG_LOGGED_MESSAGES, MAX_DEBUG_MESSAGE_LENGTH, gl_debug_log::Messages, gl_debug_log::NextMessage, and gl_debug_log::NumMessages.
Referenced by log_msg_locked_and_unlock().
debug_make_group_writable()
static bool debug_make_group_writable (struct gl_debug_state * debug) static
Make the top debug group writable.
References gl_debug_state::CurrentGroup, debug_is_group_read_only(), debug_namespace_clear(), debug_namespace_copy(), gl_debug_state::Groups, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, and gl_debug_group::Namespaces.
Referenced by debug_set_message_enable(), and debug_set_message_enable_all().
debug_message_clear()
static void debug_message_clear (struct gl_debug_message * msg) static
References gl_debug_message::length, gl_debug_message::message, and out_of_memory.
Referenced by _mesa_PopDebugGroup(), and debug_delete_messages().
debug_message_store()
static void debug_message_store (struct gl_debug_message * msg, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLsizei len, const char * buf) static
References _mesa_debug_get_id(), GLuint, gl_debug_message::id, gl_debug_message::length, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SOURCE_OTHER, MESA_DEBUG_TYPE_ERROR, gl_debug_message::message, out_of_memory, gl_debug_message::severity, gl_debug_message::source, gl_debug_message::type, and void.
Referenced by _mesa_PushDebugGroup(), and debug_log_message().
debug_namespace_clear()
static void debug_namespace_clear (struct gl_debug_namespace * ns) static
References gl_debug_namespace::Elements.
Referenced by debug_clear_group(), debug_make_group_writable(), debug_namespace_copy(), and debug_namespace_set_all().
debug_namespace_copy()
static bool debug_namespace_copy (struct gl_debug_namespace * dst, const struct gl_debug_namespace * src) static
References debug_namespace_clear(), gl_debug_namespace::DefaultState, gl_debug_namespace::Elements, gl_debug_element::ID, gl_debug_element::link, and gl_debug_element::State.
Referenced by debug_make_group_writable().
debug_namespace_get()
static bool debug_namespace_get (const struct gl_debug_namespace * ns, GLuint id, enum mesa_debug_severity severity) static
Get the state of id in the namespace.
References gl_debug_namespace::DefaultState, gl_debug_namespace::Elements, gl_debug_element::ID, and gl_debug_element::State.
Referenced by _mesa_debug_is_message_enabled().
debug_namespace_init()
static void debug_namespace_init (struct gl_debug_namespace * ns) static
References gl_debug_namespace::DefaultState, gl_debug_namespace::Elements, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SEVERITY_MEDIUM, and MESA_DEBUG_SEVERITY_NOTIFICATION.
Referenced by debug_create().
debug_namespace_set()
static bool debug_namespace_set (struct gl_debug_namespace * ns, GLuint id, bool enabled) static
Set the state of id in the namespace.
References gl_debug_namespace::DefaultState, gl_debug_namespace::Elements, gl_debug_element::ID, gl_debug_element::link, MESA_DEBUG_SEVERITY_COUNT, and gl_debug_element::State.
Referenced by debug_set_message_enable().
debug_namespace_set_all()
static void debug_namespace_set_all (struct gl_debug_namespace * ns, enum mesa_debug_severity severity, bool enabled) static
Set the default state of the namespace for severity.
When severity is MESA_DEBUG_SEVERITY_COUNT, the default values for all severities are updated.
References debug_namespace_clear(), gl_debug_namespace::DefaultState, gl_debug_namespace::Elements, MESA_DEBUG_SEVERITY_COUNT, and gl_debug_element::State.
Referenced by debug_set_message_enable_all().
debug_pop_group()
static void debug_pop_group (struct gl_debug_state * debug) static
References gl_debug_state::CurrentGroup, and debug_clear_group().
Referenced by _mesa_PopDebugGroup().
debug_push_group()
static void debug_push_group (struct gl_debug_state * debug) static
References gl_debug_state::CurrentGroup, and gl_debug_state::Groups.
Referenced by _mesa_PushDebugGroup().
debug_set_message_enable()
static void debug_set_message_enable (struct gl_debug_state * debug, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, GLboolean enabled) static
Sets the state of the given message source/type/ID tuple.
References gl_debug_state::CurrentGroup, debug_make_group_writable(), debug_namespace_set(), gl_debug_state::Groups, and gl_debug_group::Namespaces.
Referenced by _mesa_DebugMessageControl().
debug_set_message_enable_all()
static void debug_set_message_enable_all (struct gl_debug_state * debug, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, GLboolean enabled) static
References gl_debug_state::CurrentGroup, debug_make_group_writable(), debug_namespace_set_all(), gl_debug_state::Groups, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, and gl_debug_group::Namespaces.
Referenced by _mesa_DebugMessageControl().
gl_enum_to_debug_severity()
static enum mesa_debug_severity gl_enum_to_debug_severity (GLenum e) static
References debug_severity_enums.
Referenced by _mesa_DebugMessageControl(), _mesa_DebugMessageInsert(), _mesa_PopDebugGroup(), and _mesa_PushDebugGroup().
gl_enum_to_debug_source()
static enum mesa_debug_source gl_enum_to_debug_source (GLenum e) static
References debug_source_enums.
Referenced by _mesa_DebugMessageControl(), _mesa_DebugMessageInsert(), and _mesa_PushDebugGroup().
gl_enum_to_debug_type()
static enum mesa_debug_type gl_enum_to_debug_type (GLenum e) static
References debug_type_enums.
Referenced by _mesa_DebugMessageControl(), _mesa_DebugMessageInsert(), _mesa_PopDebugGroup(), and _mesa_PushDebugGroup().
log_msg_locked_and_unlock()
static void log_msg_locked_and_unlock (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char * buf) static
Insert a debug message.
The mutex is assumed to be locked, and will be unlocked by this call.
References _mesa_debug_is_message_enabled(), _mesa_unlock_debug_state(), gl_debug_state::Callback, gl_debug_state::CallbackData, gl_context::Debug, debug_log_message(), debug_severity_enums, debug_source_enums, and debug_type_enums.
Referenced by _mesa_log_msg(), _mesa_PopDebugGroup(), and _mesa_PushDebugGroup().
validate_length()
static GLboolean validate_length (struct gl_context * ctx, const char * callerstr, GLsizei length, const GLchar * buf) static
References _mesa_error(), GLAPIENTRY, and MAX_DEBUG_MESSAGE_LENGTH.
Referenced by _mesa_DebugMessageInsert(), and _mesa_PushDebugGroup().
validate_params()
static GLboolean validate_params (struct gl_context * ctx, unsigned caller, const char * callerstr, GLenum source, GLenum type, GLenum severity) static
Verify that source, type, and severity are valid enums.
The 'caller' param is used for handling values available only in glDebugMessageInsert or glDebugMessageControl
References _mesa_error(), CONTROL, and INSERT.
Referenced by _mesa_DebugMessageControl(), and _mesa_DebugMessageInsert().
Variable Documentation
debug_severity_enums
const GLenum debug_severity_enums[] static
Initial value:
= {
   GL_DEBUG_SEVERITY_LOW,
   GL_DEBUG_SEVERITY_MEDIUM,
   GL_DEBUG_SEVERITY_HIGH,
   GL_DEBUG_SEVERITY_NOTIFICATION,
}
Referenced by _mesa_GetDebugMessageLog(), gl_enum_to_debug_severity(), and log_msg_locked_and_unlock().
debug_source_enums
const GLenum debug_source_enums[] static
Initial value:
= {
   GL_DEBUG_SOURCE_API,
   GL_DEBUG_SOURCE_WINDOW_SYSTEM,
   GL_DEBUG_SOURCE_SHADER_COMPILER,
   GL_DEBUG_SOURCE_THIRD_PARTY,
   GL_DEBUG_SOURCE_APPLICATION,
   GL_DEBUG_SOURCE_OTHER,
}
Referenced by _mesa_GetDebugMessageLog(), gl_enum_to_debug_source(), and log_msg_locked_and_unlock().
debug_type_enums
const GLenum debug_type_enums[] static
Initial value:
= {
   GL_DEBUG_TYPE_ERROR,
   GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR,
   GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR,
   GL_DEBUG_TYPE_PORTABILITY,
   GL_DEBUG_TYPE_PERFORMANCE,
   GL_DEBUG_TYPE_OTHER,
   GL_DEBUG_TYPE_MARKER,
   GL_DEBUG_TYPE_PUSH_GROUP,
   GL_DEBUG_TYPE_POP_GROUP,
}
Referenced by _mesa_GetDebugMessageLog(), gl_enum_to_debug_type(), and log_msg_locked_and_unlock().
DynamicIDMutex
mtx_t DynamicIDMutex = _MTX_INITIALIZER_NP static
Referenced by _mesa_debug_get_id().
NextDynamicID
GLuint NextDynamicID = 1 static
Referenced by _mesa_debug_get_id().
out_of_memory
char out_of_memory[] = "Debugging error: out of memory" static
Referenced by build_bitmap_atlas(), debug_message_clear(), and debug_message_store().