Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
depth.c File Reference
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "depth.h"
#include "enums.h"
#include "macros.h"
#include "mtypes.h"
Functions
void GLAPIENTRY _mesa_ClearDepth (GLclampd depth)
void GLAPIENTRY _mesa_ClearDepthf (GLclampf depth)
void GLAPIENTRY _mesa_DepthFunc (GLenum func)
void GLAPIENTRY _mesa_DepthMask (GLboolean flag)
void GLAPIENTRY _mesa_DepthBoundsEXT (GLclampd zmin, GLclampd zmax)
Specified by the GL_EXT_depth_bounds_test extension.
void _mesa_init_depth (struct gl_context *ctx)
Initialize the depth buffer attribute group in the given context.
Function Documentation
_mesa_ClearDepth()
void GLAPIENTRY _mesa_ClearDepth (GLclampd depth)
References _mesa_debug(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_ClearDepthf(), and _mesa_PopAttrib().
_mesa_ClearDepthf()
void GLAPIENTRY _mesa_ClearDepthf (GLclampf depth)
References _mesa_ClearDepth(), and GLAPIENTRY.
Referenced by _mesa_ClearDepthx().
_mesa_DepthBoundsEXT()
void GLAPIENTRY _mesa_DepthBoundsEXT (GLclampd zmin, GLclampd zmax)
Specified by the GL_EXT_depth_bounds_test extension.
References _mesa_debug(), _mesa_error(), _NEW_DEPTH, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_DepthFunc()
void GLAPIENTRY _mesa_DepthFunc (GLenum func)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_DEPTH, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_DepthMask()
void GLAPIENTRY _mesa_DepthMask (GLboolean flag)
References _mesa_debug(), _NEW_DEPTH, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_init_depth()
void _mesa_init_depth (struct gl_context * ctx)
Initialize the depth buffer attribute group in the given context.
References gl_depthbuffer_attrib::Clear, gl_context::Depth, gl_depthbuffer_attrib::Func, gl_depthbuffer_attrib::Mask, and gl_depthbuffer_attrib::Test.
Referenced by init_attrib_groups().