Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
dlist.c File Reference
Display lists management functions.
#include "c99_math.h"
#include "glheader.h"
#include "imports.h"
#include "api_arrayelt.h"
#include "api_exec.h"
#include "api_loopback.h"
#include "api_validate.h"
#include "atifragshader.h"
#include "config.h"
#include "bufferobj.h"
#include "arrayobj.h"
#include "context.h"
#include "dlist.h"
#include "enums.h"
#include "eval.h"
#include "fbobject.h"
#include "framebuffer.h"
#include "glapi/glapi.h"
#include "glformats.h"
#include "hash.h"
#include "image.h"
#include "light.h"
#include "macros.h"
#include "pack.h"
#include "pbo.h"
#include "queryobj.h"
#include "samplerobj.h"
#include "shaderapi.h"
#include "syncobj.h"
#include "teximage.h"
#include "texstorage.h"
#include "mtypes.h"
#include "varray.h"
#include "arbprogram.h"
#include "transformfeedback.h"
#include "math/m_matrix.h"
#include "main/dispatch.h"
#include "vbo/vbo.h"
Data Structures
struct gl_list_instruction
Other parts of Mesa (such as the VBO module) can plug into the display list system.
struct gl_list_extensions
Used by device drivers to hook new commands into display lists.
union gl_dlist_node
Display list node.
union pointer
union uint64_pair
Used to store a 64-bit uint in a pair of "Nodes" for the sake of 32-bit environment.
Macros
#define USE_BITMAP_ATLAS 1
#define MAX_DLIST_EXT_OPCODES 16
#define SAVE_FLUSH_VERTICES(ctx)
Flush vertices.
#define ASSERT_OUTSIDE_SAVE_BEGIN_END_WITH_RETVAL(ctx, retval)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair, with return value.
#define ASSERT_OUTSIDE_SAVE_BEGIN_END(ctx)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair.
#define ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH(ctx)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair and flush the vertices.
#define ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH_WITH_RETVAL(ctx, retval)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair and flush the vertices, with return value.
#define POINTER_DWORDS (sizeof(void *) / 4)
How many 4-byte dwords to store a pointer.
#define BLOCK_SIZE 256
How many nodes to allocate at a time.
Typedefs
typedef union gl_dlist_node Node
Enumerations
enum OpCode {
OPCODE_INVALID = -1, OPCODE_ACCUM, OPCODE_ALPHA_FUNC, OPCODE_BIND_TEXTURE,
OPCODE_BITMAP, OPCODE_BLEND_COLOR, OPCODE_BLEND_EQUATION, OPCODE_BLEND_EQUATION_SEPARATE,
OPCODE_BLEND_FUNC_SEPARATE, OPCODE_BLEND_EQUATION_I, OPCODE_BLEND_EQUATION_SEPARATE_I, OPCODE_BLEND_FUNC_I,
OPCODE_BLEND_FUNC_SEPARATE_I, OPCODE_CALL_LIST, OPCODE_CALL_LISTS, OPCODE_CLEAR,
OPCODE_CLEAR_ACCUM, OPCODE_CLEAR_COLOR, OPCODE_CLEAR_DEPTH, OPCODE_CLEAR_INDEX,
OPCODE_CLEAR_STENCIL, OPCODE_CLEAR_BUFFER_IV, OPCODE_CLEAR_BUFFER_UIV, OPCODE_CLEAR_BUFFER_FV,
OPCODE_CLEAR_BUFFER_FI, OPCODE_CLIP_PLANE, OPCODE_COLOR_MASK, OPCODE_COLOR_MASK_INDEXED,
OPCODE_COLOR_MATERIAL, OPCODE_COPY_PIXELS, OPCODE_COPY_TEX_IMAGE1D, OPCODE_COPY_TEX_IMAGE2D,
OPCODE_COPY_TEX_SUB_IMAGE1D, OPCODE_COPY_TEX_SUB_IMAGE2D, OPCODE_COPY_TEX_SUB_IMAGE3D, OPCODE_CULL_FACE,
OPCODE_DEPTH_FUNC, OPCODE_DEPTH_MASK, OPCODE_DEPTH_RANGE, OPCODE_DISABLE,
OPCODE_DISABLE_INDEXED, OPCODE_DRAW_BUFFER, OPCODE_DRAW_PIXELS, OPCODE_ENABLE,
OPCODE_ENABLE_INDEXED, OPCODE_EVALMESH1, OPCODE_EVALMESH2, OPCODE_FOG,
OPCODE_FRONT_FACE, OPCODE_FRUSTUM, OPCODE_HINT, OPCODE_INDEX_MASK,
OPCODE_INIT_NAMES, OPCODE_LIGHT, OPCODE_LIGHT_MODEL, OPCODE_LINE_STIPPLE,
OPCODE_LINE_WIDTH, OPCODE_LIST_BASE, OPCODE_LOAD_IDENTITY, OPCODE_LOAD_MATRIX,
OPCODE_LOAD_NAME, OPCODE_LOGIC_OP, OPCODE_MAP1, OPCODE_MAP2,
OPCODE_MAPGRID1, OPCODE_MAPGRID2, OPCODE_MATRIX_MODE, OPCODE_MULT_MATRIX,
OPCODE_ORTHO, OPCODE_PASSTHROUGH, OPCODE_PIXEL_MAP, OPCODE_PIXEL_TRANSFER,
OPCODE_PIXEL_ZOOM, OPCODE_POINT_SIZE, OPCODE_POINT_PARAMETERS, OPCODE_POLYGON_MODE,
OPCODE_POLYGON_STIPPLE, OPCODE_POLYGON_OFFSET, OPCODE_POP_ATTRIB, OPCODE_POP_MATRIX,
OPCODE_POP_NAME, OPCODE_PRIORITIZE_TEXTURE, OPCODE_PUSH_ATTRIB, OPCODE_PUSH_MATRIX,
OPCODE_PUSH_NAME, OPCODE_RASTER_POS, OPCODE_READ_BUFFER, OPCODE_ROTATE,
OPCODE_SCALE, OPCODE_SCISSOR, OPCODE_SELECT_TEXTURE_SGIS, OPCODE_SELECT_TEXTURE_COORD_SET,
OPCODE_SHADE_MODEL, OPCODE_STENCIL_FUNC, OPCODE_STENCIL_MASK, OPCODE_STENCIL_OP,
OPCODE_TEXENV, OPCODE_TEXGEN, OPCODE_TEXPARAMETER, OPCODE_TEX_IMAGE1D,
OPCODE_TEX_IMAGE2D, OPCODE_TEX_IMAGE3D, OPCODE_TEX_SUB_IMAGE1D, OPCODE_TEX_SUB_IMAGE2D,
OPCODE_TEX_SUB_IMAGE3D, OPCODE_TRANSLATE, OPCODE_VIEWPORT, OPCODE_WINDOW_POS,
OPCODE_ACTIVE_TEXTURE, OPCODE_COMPRESSED_TEX_IMAGE_1D, OPCODE_COMPRESSED_TEX_IMAGE_2D, OPCODE_COMPRESSED_TEX_IMAGE_3D,
OPCODE_COMPRESSED_TEX_SUB_IMAGE_1D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_2D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_3D, OPCODE_SAMPLE_COVERAGE,
OPCODE_WINDOW_POS_ARB, OPCODE_BIND_PROGRAM_ARB, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, OPCODE_ACTIVE_STENCIL_FACE_EXT,
OPCODE_DEPTH_BOUNDS_EXT, OPCODE_PROGRAM_STRING_ARB, OPCODE_PROGRAM_ENV_PARAMETER_ARB, OPCODE_BEGIN_QUERY_ARB,
OPCODE_END_QUERY_ARB, OPCODE_DRAW_BUFFERS_ARB, OPCODE_BIND_FRAGMENT_SHADER_ATI, OPCODE_SET_FRAGMENT_SHADER_CONSTANTS_ATI,
OPCODE_STENCIL_FUNC_SEPARATE, OPCODE_STENCIL_OP_SEPARATE, OPCODE_STENCIL_MASK_SEPARATE, OPCODE_USE_PROGRAM,
OPCODE_UNIFORM_1F, OPCODE_UNIFORM_2F, OPCODE_UNIFORM_3F, OPCODE_UNIFORM_4F,
OPCODE_UNIFORM_1FV, OPCODE_UNIFORM_2FV, OPCODE_UNIFORM_3FV, OPCODE_UNIFORM_4FV,
OPCODE_UNIFORM_1I, OPCODE_UNIFORM_2I, OPCODE_UNIFORM_3I, OPCODE_UNIFORM_4I,
OPCODE_UNIFORM_1IV, OPCODE_UNIFORM_2IV, OPCODE_UNIFORM_3IV, OPCODE_UNIFORM_4IV,
OPCODE_UNIFORM_MATRIX22, OPCODE_UNIFORM_MATRIX33, OPCODE_UNIFORM_MATRIX44, OPCODE_UNIFORM_MATRIX23,
OPCODE_UNIFORM_MATRIX32, OPCODE_UNIFORM_MATRIX24, OPCODE_UNIFORM_MATRIX42, OPCODE_UNIFORM_MATRIX34,
OPCODE_UNIFORM_MATRIX43, OPCODE_UNIFORM_1UI, OPCODE_UNIFORM_2UI, OPCODE_UNIFORM_3UI,
OPCODE_UNIFORM_4UI, OPCODE_UNIFORM_1UIV, OPCODE_UNIFORM_2UIV, OPCODE_UNIFORM_3UIV,
OPCODE_UNIFORM_4UIV, OPCODE_USE_PROGRAM_STAGES, OPCODE_PROGRAM_UNIFORM_1F, OPCODE_PROGRAM_UNIFORM_2F,
OPCODE_PROGRAM_UNIFORM_3F, OPCODE_PROGRAM_UNIFORM_4F, OPCODE_PROGRAM_UNIFORM_1FV, OPCODE_PROGRAM_UNIFORM_2FV,
OPCODE_PROGRAM_UNIFORM_3FV, OPCODE_PROGRAM_UNIFORM_4FV, OPCODE_PROGRAM_UNIFORM_1I, OPCODE_PROGRAM_UNIFORM_2I,
OPCODE_PROGRAM_UNIFORM_3I, OPCODE_PROGRAM_UNIFORM_4I, OPCODE_PROGRAM_UNIFORM_1IV, OPCODE_PROGRAM_UNIFORM_2IV,
OPCODE_PROGRAM_UNIFORM_3IV, OPCODE_PROGRAM_UNIFORM_4IV, OPCODE_PROGRAM_UNIFORM_1UI, OPCODE_PROGRAM_UNIFORM_2UI,
OPCODE_PROGRAM_UNIFORM_3UI, OPCODE_PROGRAM_UNIFORM_4UI, OPCODE_PROGRAM_UNIFORM_1UIV, OPCODE_PROGRAM_UNIFORM_2UIV,
OPCODE_PROGRAM_UNIFORM_3UIV, OPCODE_PROGRAM_UNIFORM_4UIV, OPCODE_PROGRAM_UNIFORM_MATRIX22F, OPCODE_PROGRAM_UNIFORM_MATRIX33F,
OPCODE_PROGRAM_UNIFORM_MATRIX44F, OPCODE_PROGRAM_UNIFORM_MATRIX23F, OPCODE_PROGRAM_UNIFORM_MATRIX32F, OPCODE_PROGRAM_UNIFORM_MATRIX24F,
OPCODE_PROGRAM_UNIFORM_MATRIX42F, OPCODE_PROGRAM_UNIFORM_MATRIX34F, OPCODE_PROGRAM_UNIFORM_MATRIX43F, OPCODE_CLIP_CONTROL,
OPCODE_CLAMP_COLOR, OPCODE_BLIT_FRAMEBUFFER, OPCODE_ATTR_1F_NV, OPCODE_ATTR_2F_NV,
OPCODE_ATTR_3F_NV, OPCODE_ATTR_4F_NV, OPCODE_ATTR_1F_ARB, OPCODE_ATTR_2F_ARB,
OPCODE_ATTR_3F_ARB, OPCODE_ATTR_4F_ARB, OPCODE_MATERIAL, OPCODE_BEGIN,
OPCODE_END, OPCODE_RECTF, OPCODE_EVAL_C1, OPCODE_EVAL_C2,
OPCODE_EVAL_P1, OPCODE_EVAL_P2, OPCODE_PROVOKING_VERTEX, OPCODE_BEGIN_TRANSFORM_FEEDBACK,
OPCODE_END_TRANSFORM_FEEDBACK, OPCODE_BIND_TRANSFORM_FEEDBACK, OPCODE_PAUSE_TRANSFORM_FEEDBACK, OPCODE_RESUME_TRANSFORM_FEEDBACK,
OPCODE_DRAW_TRANSFORM_FEEDBACK, OPCODE_CLEARCOLOR_I, OPCODE_CLEARCOLOR_UI, OPCODE_TEXPARAMETER_I,
OPCODE_TEXPARAMETER_UI, OPCODE_VERTEX_ATTRIB_DIVISOR, OPCODE_TEXTURE_BARRIER_NV, OPCODE_BIND_SAMPLER,
OPCODE_SAMPLER_PARAMETERIV, OPCODE_SAMPLER_PARAMETERFV, OPCODE_SAMPLER_PARAMETERIIV, OPCODE_SAMPLER_PARAMETERUIV,
OPCODE_WAIT_SYNC, OPCODE_BEGIN_CONDITIONAL_RENDER, OPCODE_END_CONDITIONAL_RENDER, OPCODE_QUERY_COUNTER,
OPCODE_BEGIN_QUERY_INDEXED, OPCODE_END_QUERY_INDEXED, OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM, OPCODE_DRAW_TRANSFORM_FEEDBACK_INSTANCED,
OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM_INSTANCED, OPCODE_UNIFORM_BLOCK_BINDING, OPCODE_POLYGON_OFFSET_CLAMP, OPCODE_WINDOW_RECTANGLES,
OPCODE_ERROR, OPCODE_CONTINUE, OPCODE_NOP, OPCODE_END_OF_LIST,
OPCODE_EXT_0
}
Display list opcodes.
Functions
static void save_pointer (Node *dest, void *src)
Save a 4 or 8-byte pointer at dest (and dest+1).
static void * get_pointer (const Node *node)
Retrieve a 4 or 8-byte pointer from node (node+1).
void mesa_print_display_list (GLuint list)
Clients may call this function to help debug display list problems.
static bool is_bitmap_list (const struct gl_display_list *dlist)
Does the given display list only contain a single glBitmap call?
static bool is_empty_list (const struct gl_display_list *dlist)
Is the given display list an empty list?
void _mesa_delete_bitmap_atlas (struct gl_context *ctx, struct gl_bitmap_atlas *atlas)
Delete/free a gl_bitmap_atlas.
static struct gl_bitmap_atlas * lookup_bitmap_atlas (struct gl_context *ctx, GLuint listBase)
Lookup a gl_bitmap_atlas by listBase ID.
static struct gl_bitmap_atlas * alloc_bitmap_atlas (struct gl_context *ctx, GLuint listBase)
Create new bitmap atlas and insert into hash table.
static void build_bitmap_atlas (struct gl_context *ctx, struct gl_bitmap_atlas *atlas, GLuint listBase)
Try to build a bitmap atlas.
static struct gl_display_list * make_list (GLuint name, GLuint count)
Allocate a gl_display_list object with an initial block of storage.
struct gl_display_list * _mesa_lookup_list (struct gl_context *ctx, GLuint list)
Lookup function to just encapsulate casting.
static GLboolean is_ext_opcode (OpCode opcode)
Is the given opcode an extension code?
static GLint ext_opcode_destroy (struct gl_context *ctx, Node *node)
Destroy an extended opcode instruction.
static GLint ext_opcode_execute (struct gl_context *ctx, Node *node)
Execute an extended opcode instruction.
static GLint ext_opcode_print (struct gl_context *ctx, Node *node, FILE *f)
Print an extended opcode instruction.
void _mesa_delete_list (struct gl_context *ctx, struct gl_display_list *dlist)
Delete the named display list, but don't remove from hash table.
static void check_atlas_for_deleted_list (GLuint atlas_id, void *data, void *userData)
Called by _mesa_HashWalk() to check if a display list which is being deleted belongs to a bitmap texture atlas.
static void destroy_list (struct gl_context *ctx, GLuint list)
Destroy a display list and remove from hash table.
static GLint translate_id (GLsizei n, GLenum type, const GLvoid *list)
static GLvoid * unpack_image (struct gl_context *ctx, GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *unpack)
Wrapper for _mesa_unpack_image/bitmap() that handles pixel buffer objects.
static void * memdup (const void *src, GLsizei bytes)
Return copy of memory.
static Node * dlist_alloc (struct gl_context *ctx, OpCode opcode, GLuint bytes, bool align8)
Allocate space for a display list instruction (opcode + payload space).
void * _mesa_dlist_alloc (struct gl_context *ctx, GLuint opcode, GLuint bytes)
Allocate space for a display list instruction.
void * _mesa_dlist_alloc_aligned (struct gl_context *ctx, GLuint opcode, GLuint bytes)
Same as _mesa_dlist_alloc(), but return a pointer which is 8-byte aligned in 64-bit environments, 4-byte aligned otherwise.
GLint _mesa_dlist_alloc_opcode (struct gl_context *ctx, GLuint size, void(*execute)(struct gl_context *, void *), void(*destroy)(struct gl_context *, void *), void(*print)(struct gl_context *, void *, FILE *))
This function allows modules and drivers to get their own opcodes for extending display list functionality.
static Node * alloc_instruction (struct gl_context *ctx, OpCode opcode, GLuint nparams)
Allocate space for a display list instruction.
static void trim_list (struct gl_context *ctx)
Called by EndList to try to reduce memory used for the list.
static void GLAPIENTRY save_Accum (GLenum op, GLfloat value)
static void GLAPIENTRY save_AlphaFunc (GLenum func, GLclampf ref)
static void GLAPIENTRY save_BindTexture (GLenum target, GLuint texture)
static void GLAPIENTRY save_Bitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *pixels)
static void GLAPIENTRY save_BlendEquation (GLenum mode)
static void GLAPIENTRY save_BlendEquationSeparateEXT (GLenum modeRGB, GLenum modeA)
static void GLAPIENTRY save_BlendFuncSeparateEXT (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
static void GLAPIENTRY save_BlendFunc (GLenum srcfactor, GLenum dstfactor)
static void GLAPIENTRY save_BlendColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
static void GLAPIENTRY save_BlendFuncSeparatei (GLuint buf, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
static void GLAPIENTRY save_BlendFunci (GLuint buf, GLenum sfactor, GLenum dfactor)
static void GLAPIENTRY save_BlendEquationi (GLuint buf, GLenum mode)
static void GLAPIENTRY save_BlendEquationSeparatei (GLuint buf, GLenum modeRGB, GLenum modeA)
static void GLAPIENTRY save_DrawArraysInstancedARB (UNUSED GLenum mode, UNUSED GLint first, UNUSED GLsizei count, UNUSED GLsizei primcount)
static void GLAPIENTRY save_DrawElementsInstancedARB (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const GLvoid *indices, UNUSED GLsizei primcount)
static void GLAPIENTRY save_DrawElementsInstancedBaseVertexARB (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const GLvoid *indices, UNUSED GLsizei primcount, UNUSED GLint basevertex)
static void GLAPIENTRY save_DrawArraysInstancedBaseInstance (UNUSED GLenum mode, UNUSED GLint first, UNUSED GLsizei count, UNUSED GLsizei primcount, UNUSED GLuint baseinstance)
static void APIENTRY save_DrawElementsInstancedBaseInstance (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const void *indices, UNUSED GLsizei primcount, UNUSED GLuint baseinstance)
static void APIENTRY save_DrawElementsInstancedBaseVertexBaseInstance (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const void *indices, UNUSED GLsizei primcount, UNUSED GLint basevertex, UNUSED GLuint baseinstance)
static void invalidate_saved_current_state (struct gl_context *ctx)
While building a display list we cache some OpenGL state.
static void GLAPIENTRY save_CallList (GLuint list)
static void GLAPIENTRY save_CallLists (GLsizei num, GLenum type, const GLvoid *lists)
static void GLAPIENTRY save_Clear (GLbitfield mask)
static void GLAPIENTRY save_ClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint *value)
static void GLAPIENTRY save_ClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint *value)
static void GLAPIENTRY save_ClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat *value)
static void GLAPIENTRY save_ClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil)
static void GLAPIENTRY save_ClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
static void GLAPIENTRY save_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
static void GLAPIENTRY save_ClearDepth (GLclampd depth)
static void GLAPIENTRY save_ClearIndex (GLfloat c)
static void GLAPIENTRY save_ClearStencil (GLint s)
static void GLAPIENTRY save_ClipPlane (GLenum plane, const GLdouble *equ)
static void GLAPIENTRY save_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
static void GLAPIENTRY save_ColorMaskIndexed (GLuint buf, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
static void GLAPIENTRY save_ColorMaterial (GLenum face, GLenum mode)
static void GLAPIENTRY save_CopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
static void GLAPIENTRY save_CopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
static void GLAPIENTRY save_CopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
static void GLAPIENTRY save_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
static void GLAPIENTRY save_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLint height)
static void GLAPIENTRY save_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLint height)
static void GLAPIENTRY save_CullFace (GLenum mode)
static void GLAPIENTRY save_DepthFunc (GLenum func)
static void GLAPIENTRY save_DepthMask (GLboolean mask)
static void GLAPIENTRY save_DepthRange (GLclampd nearval, GLclampd farval)
static void GLAPIENTRY save_Disable (GLenum cap)
static void GLAPIENTRY save_DisableIndexed (GLuint index, GLenum cap)
static void GLAPIENTRY save_DrawBuffer (GLenum mode)
static void GLAPIENTRY save_DrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_Enable (GLenum cap)
static void GLAPIENTRY save_EnableIndexed (GLuint index, GLenum cap)
static void GLAPIENTRY save_EvalMesh1 (GLenum mode, GLint i1, GLint i2)
static void GLAPIENTRY save_EvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
static void GLAPIENTRY save_Fogfv (GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_Fogf (GLenum pname, GLfloat param)
static void GLAPIENTRY save_Fogiv (GLenum pname, const GLint *params)
static void GLAPIENTRY save_Fogi (GLenum pname, GLint param)
static void GLAPIENTRY save_FrontFace (GLenum mode)
static void GLAPIENTRY save_Frustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval)
static void GLAPIENTRY save_Hint (GLenum target, GLenum mode)
static void GLAPIENTRY save_IndexMask (GLuint mask)
static void GLAPIENTRY save_InitNames (void)
static void GLAPIENTRY save_Lightfv (GLenum light, GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_Lightf (GLenum light, GLenum pname, GLfloat param)
static void GLAPIENTRY save_Lightiv (GLenum light, GLenum pname, const GLint *params)
static void GLAPIENTRY save_Lighti (GLenum light, GLenum pname, GLint param)
static void GLAPIENTRY save_LightModelfv (GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_LightModelf (GLenum pname, GLfloat param)
static void GLAPIENTRY save_LightModeliv (GLenum pname, const GLint *params)
static void GLAPIENTRY save_LightModeli (GLenum pname, GLint param)
static void GLAPIENTRY save_LineStipple (GLint factor, GLushort pattern)
static void GLAPIENTRY save_LineWidth (GLfloat width)
static void GLAPIENTRY save_ListBase (GLuint base)
static void GLAPIENTRY save_LoadIdentity (void)
static void GLAPIENTRY save_LoadMatrixf (const GLfloat *m)
static void GLAPIENTRY save_LoadMatrixd (const GLdouble *m)
static void GLAPIENTRY save_LoadName (GLuint name)
static void GLAPIENTRY save_LogicOp (GLenum opcode)
static void GLAPIENTRY save_Map1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points)
static void GLAPIENTRY save_Map1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points)
static void GLAPIENTRY save_Map2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points)
static void GLAPIENTRY save_Map2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points)
static void GLAPIENTRY save_MapGrid1f (GLint un, GLfloat u1, GLfloat u2)
static void GLAPIENTRY save_MapGrid1d (GLint un, GLdouble u1, GLdouble u2)
static void GLAPIENTRY save_MapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
static void GLAPIENTRY save_MapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
static void GLAPIENTRY save_MatrixMode (GLenum mode)
static void GLAPIENTRY save_MultMatrixf (const GLfloat *m)
static void GLAPIENTRY save_MultMatrixd (const GLdouble *m)
static void GLAPIENTRY save_NewList (GLuint name, GLenum mode)
static void GLAPIENTRY save_Ortho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval)
static void GLAPIENTRY save_PixelMapfv (GLenum map, GLint mapsize, const GLfloat *values)
static void GLAPIENTRY save_PixelMapuiv (GLenum map, GLint mapsize, const GLuint *values)
static void GLAPIENTRY save_PixelMapusv (GLenum map, GLint mapsize, const GLushort *values)
static void GLAPIENTRY save_PixelTransferf (GLenum pname, GLfloat param)
static void GLAPIENTRY save_PixelTransferi (GLenum pname, GLint param)
static void GLAPIENTRY save_PixelZoom (GLfloat xfactor, GLfloat yfactor)
static void GLAPIENTRY save_PointParameterfvEXT (GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_PointParameterfEXT (GLenum pname, GLfloat param)
static void GLAPIENTRY save_PointParameteriNV (GLenum pname, GLint param)
static void GLAPIENTRY save_PointParameterivNV (GLenum pname, const GLint *param)
static void GLAPIENTRY save_PointSize (GLfloat size)
static void GLAPIENTRY save_PolygonMode (GLenum face, GLenum mode)
static void GLAPIENTRY save_PolygonStipple (const GLubyte *pattern)
static void GLAPIENTRY save_PolygonOffset (GLfloat factor, GLfloat units)
static void GLAPIENTRY save_PolygonOffsetEXT (GLfloat factor, GLfloat bias)
static void GLAPIENTRY save_PolygonOffsetClampEXT (GLfloat factor, GLfloat units, GLfloat clamp)
static void GLAPIENTRY save_PopAttrib (void)
static void GLAPIENTRY save_PopMatrix (void)
static void GLAPIENTRY save_PopName (void)
static void GLAPIENTRY save_PrioritizeTextures (GLsizei num, const GLuint *textures, const GLclampf *priorities)
static void GLAPIENTRY save_PushAttrib (GLbitfield mask)
static void GLAPIENTRY save_PushMatrix (void)
static void GLAPIENTRY save_PushName (GLuint name)
static void GLAPIENTRY save_RasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_RasterPos2d (GLdouble x, GLdouble y)
static void GLAPIENTRY save_RasterPos2f (GLfloat x, GLfloat y)
static void GLAPIENTRY save_RasterPos2i (GLint x, GLint y)
static void GLAPIENTRY save_RasterPos2s (GLshort x, GLshort y)
static void GLAPIENTRY save_RasterPos3d (GLdouble x, GLdouble y, GLdouble z)
static void GLAPIENTRY save_RasterPos3f (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_RasterPos3i (GLint x, GLint y, GLint z)
static void GLAPIENTRY save_RasterPos3s (GLshort x, GLshort y, GLshort z)
static void GLAPIENTRY save_RasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
static void GLAPIENTRY save_RasterPos4i (GLint x, GLint y, GLint z, GLint w)
static void GLAPIENTRY save_RasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
static void GLAPIENTRY save_RasterPos2dv (const GLdouble *v)
static void GLAPIENTRY save_RasterPos2fv (const GLfloat *v)
static void GLAPIENTRY save_RasterPos2iv (const GLint *v)
static void GLAPIENTRY save_RasterPos2sv (const GLshort *v)
static void GLAPIENTRY save_RasterPos3dv (const GLdouble *v)
static void GLAPIENTRY save_RasterPos3fv (const GLfloat *v)
static void GLAPIENTRY save_RasterPos3iv (const GLint *v)
static void GLAPIENTRY save_RasterPos3sv (const GLshort *v)
static void GLAPIENTRY save_RasterPos4dv (const GLdouble *v)
static void GLAPIENTRY save_RasterPos4fv (const GLfloat *v)
static void GLAPIENTRY save_RasterPos4iv (const GLint *v)
static void GLAPIENTRY save_RasterPos4sv (const GLshort *v)
static void GLAPIENTRY save_PassThrough (GLfloat token)
static void GLAPIENTRY save_ReadBuffer (GLenum mode)
static void GLAPIENTRY save_Rotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Rotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
static void GLAPIENTRY save_Scalef (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Scaled (GLdouble x, GLdouble y, GLdouble z)
static void GLAPIENTRY save_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
static void GLAPIENTRY save_ShadeModel (GLenum mode)
static void GLAPIENTRY save_StencilFunc (GLenum func, GLint ref, GLuint mask)
static void GLAPIENTRY save_StencilMask (GLuint mask)
static void GLAPIENTRY save_StencilOp (GLenum fail, GLenum zfail, GLenum zpass)
static void GLAPIENTRY save_StencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
static void GLAPIENTRY save_StencilFuncSeparateATI (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask)
static void GLAPIENTRY save_StencilMaskSeparate (GLenum face, GLuint mask)
static void GLAPIENTRY save_StencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
static void GLAPIENTRY save_TexEnvfv (GLenum target, GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_TexEnvf (GLenum target, GLenum pname, GLfloat param)
static void GLAPIENTRY save_TexEnvi (GLenum target, GLenum pname, GLint param)
static void GLAPIENTRY save_TexEnviv (GLenum target, GLenum pname, const GLint *param)
static void GLAPIENTRY save_TexGenfv (GLenum coord, GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_TexGeniv (GLenum coord, GLenum pname, const GLint *params)
static void GLAPIENTRY save_TexGend (GLenum coord, GLenum pname, GLdouble param)
static void GLAPIENTRY save_TexGendv (GLenum coord, GLenum pname, const GLdouble *params)
static void GLAPIENTRY save_TexGenf (GLenum coord, GLenum pname, GLfloat param)
static void GLAPIENTRY save_TexGeni (GLenum coord, GLenum pname, GLint param)
static void GLAPIENTRY save_TexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_TexParameterf (GLenum target, GLenum pname, GLfloat param)
static void GLAPIENTRY save_TexParameteri (GLenum target, GLenum pname, GLint param)
static void GLAPIENTRY save_TexParameteriv (GLenum target, GLenum pname, const GLint *params)
static void GLAPIENTRY save_TexImage1D (GLenum target, GLint level, GLint components, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_TexImage2D (GLenum target, GLint level, GLint components, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_TexImage3D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
static void GLAPIENTRY save_Translatef (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Translated (GLdouble x, GLdouble y, GLdouble z)
static void GLAPIENTRY save_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
static void GLAPIENTRY save_WindowPos4fMESA (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_WindowPos2dMESA (GLdouble x, GLdouble y)
static void GLAPIENTRY save_WindowPos2fMESA (GLfloat x, GLfloat y)
static void GLAPIENTRY save_WindowPos2iMESA (GLint x, GLint y)
static void GLAPIENTRY save_WindowPos2sMESA (GLshort x, GLshort y)
static void GLAPIENTRY save_WindowPos3dMESA (GLdouble x, GLdouble y, GLdouble z)
static void GLAPIENTRY save_WindowPos3fMESA (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_WindowPos3iMESA (GLint x, GLint y, GLint z)
static void GLAPIENTRY save_WindowPos3sMESA (GLshort x, GLshort y, GLshort z)
static void GLAPIENTRY save_WindowPos4dMESA (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
static void GLAPIENTRY save_WindowPos4iMESA (GLint x, GLint y, GLint z, GLint w)
static void GLAPIENTRY save_WindowPos4sMESA (GLshort x, GLshort y, GLshort z, GLshort w)
static void GLAPIENTRY save_WindowPos2dvMESA (const GLdouble *v)
static void GLAPIENTRY save_WindowPos2fvMESA (const GLfloat *v)
static void GLAPIENTRY save_WindowPos2ivMESA (const GLint *v)
static void GLAPIENTRY save_WindowPos2svMESA (const GLshort *v)
static void GLAPIENTRY save_WindowPos3dvMESA (const GLdouble *v)
static void GLAPIENTRY save_WindowPos3fvMESA (const GLfloat *v)
static void GLAPIENTRY save_WindowPos3ivMESA (const GLint *v)
static void GLAPIENTRY save_WindowPos3svMESA (const GLshort *v)
static void GLAPIENTRY save_WindowPos4dvMESA (const GLdouble *v)
static void GLAPIENTRY save_WindowPos4fvMESA (const GLfloat *v)
static void GLAPIENTRY save_WindowPos4ivMESA (const GLint *v)
static void GLAPIENTRY save_WindowPos4svMESA (const GLshort *v)
static void GLAPIENTRY save_ActiveTextureARB (GLenum target)
static void GLAPIENTRY save_LoadTransposeMatrixdARB (const GLdouble m[16])
static void GLAPIENTRY save_LoadTransposeMatrixfARB (const GLfloat m[16])
static void GLAPIENTRY save_MultTransposeMatrixdARB (const GLdouble m[16])
static void GLAPIENTRY save_MultTransposeMatrixfARB (const GLfloat m[16])
static GLvoid * copy_data (const GLvoid *data, GLsizei size, const char *func)
static void GLAPIENTRY save_CompressedTexImage1DARB (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data)
static void GLAPIENTRY save_CompressedTexImage2DARB (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
static void GLAPIENTRY save_CompressedTexImage3DARB (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
static void GLAPIENTRY save_CompressedTexSubImage1DARB (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
static void GLAPIENTRY save_CompressedTexSubImage2DARB (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
static void GLAPIENTRY save_CompressedTexSubImage3DARB (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
static void GLAPIENTRY save_SampleCoverageARB (GLclampf value, GLboolean invert)
static void GLAPIENTRY save_BindProgramARB (GLenum target, GLuint id)
static void GLAPIENTRY save_ProgramEnvParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_ProgramEnvParameter4fvARB (GLenum target, GLuint index, const GLfloat *params)
static void GLAPIENTRY save_ProgramEnvParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat *params)
static void GLAPIENTRY save_ProgramEnvParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
static void GLAPIENTRY save_ProgramEnvParameter4dvARB (GLenum target, GLuint index, const GLdouble *params)
static void GLAPIENTRY save_ProgramLocalParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_ProgramLocalParameter4fvARB (GLenum target, GLuint index, const GLfloat *params)
static void GLAPIENTRY save_ProgramLocalParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat *params)
static void GLAPIENTRY save_ProgramLocalParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
static void GLAPIENTRY save_ProgramLocalParameter4dvARB (GLenum target, GLuint index, const GLdouble *params)
static void GLAPIENTRY save_ActiveStencilFaceEXT (GLenum face)
static void GLAPIENTRY save_DepthBoundsEXT (GLclampd zmin, GLclampd zmax)
static void GLAPIENTRY save_ProgramStringARB (GLenum target, GLenum format, GLsizei len, const GLvoid *string)
static void GLAPIENTRY save_BeginQueryARB (GLenum target, GLuint id)
static void GLAPIENTRY save_EndQueryARB (GLenum target)
static void GLAPIENTRY save_QueryCounter (GLuint id, GLenum target)
static void GLAPIENTRY save_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
static void GLAPIENTRY save_EndQueryIndexed (GLenum target, GLuint index)
static void GLAPIENTRY save_DrawBuffersARB (GLsizei count, const GLenum *buffers)
static void GLAPIENTRY save_BindFragmentShaderATI (GLuint id)
static void GLAPIENTRY save_SetFragmentShaderConstantATI (GLuint dst, const GLfloat *value)
static void GLAPIENTRY save_Attr1fNV (GLenum attr, GLfloat x)
static void GLAPIENTRY save_Attr2fNV (GLenum attr, GLfloat x, GLfloat y)
static void GLAPIENTRY save_Attr3fNV (GLenum attr, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Attr4fNV (GLenum attr, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_Attr1fARB (GLenum attr, GLfloat x)
static void GLAPIENTRY save_Attr2fARB (GLenum attr, GLfloat x, GLfloat y)
static void GLAPIENTRY save_Attr3fARB (GLenum attr, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Attr4fARB (GLenum attr, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_EvalCoord1f (GLfloat x)
static void GLAPIENTRY save_EvalCoord1fv (const GLfloat *v)
static void GLAPIENTRY save_EvalCoord2f (GLfloat x, GLfloat y)
static void GLAPIENTRY save_EvalCoord2fv (const GLfloat *v)
static void GLAPIENTRY save_EvalPoint1 (GLint x)
static void GLAPIENTRY save_EvalPoint2 (GLint x, GLint y)
static void GLAPIENTRY save_Indexf (GLfloat x)
static void GLAPIENTRY save_Indexfv (const GLfloat *v)
static void GLAPIENTRY save_EdgeFlag (GLboolean x)
static GLboolean compare_vec (const GLfloat *a, const GLfloat *b, GLuint count)
Compare 'count' elements of vectors 'a' and 'b'.
static void GLAPIENTRY save_Materialfv (GLenum face, GLenum pname, const GLfloat *param)
This glMaterial function is used for glMaterial calls that are outside a glBegin/End pair.
static void GLAPIENTRY save_Begin (GLenum mode)
static void GLAPIENTRY save_End (void)
static void GLAPIENTRY save_Rectf (GLfloat a, GLfloat b, GLfloat c, GLfloat d)
static void GLAPIENTRY save_Vertex2f (GLfloat x, GLfloat y)
static void GLAPIENTRY save_Vertex2fv (const GLfloat *v)
static void GLAPIENTRY save_Vertex3f (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Vertex3fv (const GLfloat *v)
static void GLAPIENTRY save_Vertex4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_Vertex4fv (const GLfloat *v)
static void GLAPIENTRY save_TexCoord1f (GLfloat x)
static void GLAPIENTRY save_TexCoord1fv (const GLfloat *v)
static void GLAPIENTRY save_TexCoord2f (GLfloat x, GLfloat y)
static void GLAPIENTRY save_TexCoord2fv (const GLfloat *v)
static void GLAPIENTRY save_TexCoord3f (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_TexCoord3fv (const GLfloat *v)
static void GLAPIENTRY save_TexCoord4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_TexCoord4fv (const GLfloat *v)
static void GLAPIENTRY save_Normal3f (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Normal3fv (const GLfloat *v)
static void GLAPIENTRY save_FogCoordfEXT (GLfloat x)
static void GLAPIENTRY save_FogCoordfvEXT (const GLfloat *v)
static void GLAPIENTRY save_Color3f (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Color3fv (const GLfloat *v)
static void GLAPIENTRY save_Color4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_Color4fv (const GLfloat *v)
static void GLAPIENTRY save_SecondaryColor3fEXT (GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_SecondaryColor3fvEXT (const GLfloat *v)
static void GLAPIENTRY save_MultiTexCoord1f (GLenum target, GLfloat x)
static void GLAPIENTRY save_MultiTexCoord1fv (GLenum target, const GLfloat *v)
static void GLAPIENTRY save_MultiTexCoord2f (GLenum target, GLfloat x, GLfloat y)
static void GLAPIENTRY save_MultiTexCoord2fv (GLenum target, const GLfloat *v)
static void GLAPIENTRY save_MultiTexCoord3f (GLenum target, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_MultiTexCoord3fv (GLenum target, const GLfloat *v)
static void GLAPIENTRY save_MultiTexCoord4f (GLenum target, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_MultiTexCoord4fv (GLenum target, const GLfloat *v)
static void index_error (void)
Record a GL_INVALID_VALUE error when an invalid vertex attribute index is found.
static void GLAPIENTRY save_VertexAttrib1fARB (GLuint index, GLfloat x)
static void GLAPIENTRY save_VertexAttrib1fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY save_VertexAttrib2fARB (GLuint index, GLfloat x, GLfloat y)
static void GLAPIENTRY save_VertexAttrib2fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY save_VertexAttrib3fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_VertexAttrib3fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY save_VertexAttrib4fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_VertexAttrib4fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY save_BlitFramebufferEXT (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
static void GLAPIENTRY save_ProvokingVertexEXT (GLenum mode)
GL_EXT_provoking_vertex.
static void GLAPIENTRY save_BeginTransformFeedback (GLenum mode)
GL_EXT_transform_feedback.
static void GLAPIENTRY save_EndTransformFeedback (void)
GL_EXT_transform_feedback.
static void GLAPIENTRY save_BindTransformFeedback (GLenum target, GLuint name)
static void GLAPIENTRY save_PauseTransformFeedback (void)
static void GLAPIENTRY save_ResumeTransformFeedback (void)
static void GLAPIENTRY save_DrawTransformFeedback (GLenum mode, GLuint name)
static void GLAPIENTRY save_DrawTransformFeedbackStream (GLenum mode, GLuint name, GLuint stream)
static void GLAPIENTRY save_DrawTransformFeedbackInstanced (GLenum mode, GLuint name, GLsizei primcount)
static void GLAPIENTRY save_DrawTransformFeedbackStreamInstanced (GLenum mode, GLuint name, GLuint stream, GLsizei primcount)
static void GLAPIENTRY save_UseProgram (GLuint program)
static void GLAPIENTRY save_Uniform1fARB (GLint location, GLfloat x)
static void GLAPIENTRY save_Uniform2fARB (GLint location, GLfloat x, GLfloat y)
static void GLAPIENTRY save_Uniform3fARB (GLint location, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_Uniform4fARB (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_Uniform1fvARB (GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_Uniform2fvARB (GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_Uniform3fvARB (GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_Uniform4fvARB (GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_Uniform1iARB (GLint location, GLint x)
static void GLAPIENTRY save_Uniform2iARB (GLint location, GLint x, GLint y)
static void GLAPIENTRY save_Uniform3iARB (GLint location, GLint x, GLint y, GLint z)
static void GLAPIENTRY save_Uniform4iARB (GLint location, GLint x, GLint y, GLint z, GLint w)
static void GLAPIENTRY save_Uniform1ivARB (GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_Uniform2ivARB (GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_Uniform3ivARB (GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_Uniform4ivARB (GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_Uniform1ui (GLint location, GLuint x)
static void GLAPIENTRY save_Uniform2ui (GLint location, GLuint x, GLuint y)
static void GLAPIENTRY save_Uniform3ui (GLint location, GLuint x, GLuint y, GLuint z)
static void GLAPIENTRY save_Uniform4ui (GLint location, GLuint x, GLuint y, GLuint z, GLuint w)
static void GLAPIENTRY save_Uniform1uiv (GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_Uniform2uiv (GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_Uniform3uiv (GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_Uniform4uiv (GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_UniformMatrix2fvARB (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix3fvARB (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix4fvARB (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *m)
static void GLAPIENTRY save_UseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program)
static void GLAPIENTRY save_ProgramUniform1f (GLuint program, GLint location, GLfloat x)
static void GLAPIENTRY save_ProgramUniform2f (GLuint program, GLint location, GLfloat x, GLfloat y)
static void GLAPIENTRY save_ProgramUniform3f (GLuint program, GLint location, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY save_ProgramUniform4f (GLuint program, GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY save_ProgramUniform1fv (GLuint program, GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniform2fv (GLuint program, GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniform3fv (GLuint program, GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniform4fv (GLuint program, GLint location, GLsizei count, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniform1i (GLuint program, GLint location, GLint x)
static void GLAPIENTRY save_ProgramUniform2i (GLuint program, GLint location, GLint x, GLint y)
static void GLAPIENTRY save_ProgramUniform3i (GLuint program, GLint location, GLint x, GLint y, GLint z)
static void GLAPIENTRY save_ProgramUniform4i (GLuint program, GLint location, GLint x, GLint y, GLint z, GLint w)
static void GLAPIENTRY save_ProgramUniform1iv (GLuint program, GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_ProgramUniform2iv (GLuint program, GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_ProgramUniform3iv (GLuint program, GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_ProgramUniform4iv (GLuint program, GLint location, GLsizei count, const GLint *v)
static void GLAPIENTRY save_ProgramUniform1ui (GLuint program, GLint location, GLuint x)
static void GLAPIENTRY save_ProgramUniform2ui (GLuint program, GLint location, GLuint x, GLuint y)
static void GLAPIENTRY save_ProgramUniform3ui (GLuint program, GLint location, GLuint x, GLuint y, GLuint z)
static void GLAPIENTRY save_ProgramUniform4ui (GLuint program, GLint location, GLuint x, GLuint y, GLuint z, GLuint w)
static void GLAPIENTRY save_ProgramUniform1uiv (GLuint program, GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_ProgramUniform2uiv (GLuint program, GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_ProgramUniform3uiv (GLuint program, GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_ProgramUniform4uiv (GLuint program, GLint location, GLsizei count, const GLuint *v)
static void GLAPIENTRY save_ProgramUniformMatrix2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ProgramUniformMatrix4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *v)
static void GLAPIENTRY save_ClipControl (GLenum origin, GLenum depth)
static void GLAPIENTRY save_ClampColorARB (GLenum target, GLenum clamp)
static void GLAPIENTRY save_ClearColorIi (GLint red, GLint green, GLint blue, GLint alpha)
GL_EXT_texture_integer.
static void GLAPIENTRY save_ClearColorIui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
GL_EXT_texture_integer.
static void GLAPIENTRY save_TexParameterIiv (GLenum target, GLenum pname, const GLint *params)
GL_EXT_texture_integer.
static void GLAPIENTRY save_TexParameterIuiv (GLenum target, GLenum pname, const GLuint *params)
GL_EXT_texture_integer.
static void GLAPIENTRY save_VertexAttribDivisor (GLuint index, GLuint divisor)
static void GLAPIENTRY save_TextureBarrierNV (void)
static void GLAPIENTRY save_BindSampler (GLuint unit, GLuint sampler)
static void GLAPIENTRY save_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint *params)
static void GLAPIENTRY save_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
static void GLAPIENTRY save_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *params)
static void GLAPIENTRY save_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
static void GLAPIENTRY save_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint *params)
static void GLAPIENTRY save_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint *params)
static void GLAPIENTRY save_WaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
static void GLAPIENTRY save_BeginConditionalRender (GLuint queryId, GLenum mode)
GL_NV_conditional_render.
static void GLAPIENTRY save_EndConditionalRender (void)
static void GLAPIENTRY save_UniformBlockBinding (GLuint prog, GLuint index, GLuint binding)
static void GLAPIENTRY save_WindowRectanglesEXT (GLenum mode, GLsizei count, const GLint *box)
GL_EXT_window_rectangles.
static void save_error (struct gl_context *ctx, GLenum error, const char *s)
Save an error-generating command into display list.
void _mesa_compile_error (struct gl_context *ctx, GLenum error, const char *s)
Compile an error into current display list.
static GLboolean islist (struct gl_context *ctx, GLuint list)
Test if ID names a display list.
static void execute_list (struct gl_context *ctx, GLuint list)
GLboolean GLAPIENTRY _mesa_IsList (GLuint list)
Test if a display list number is valid.
void GLAPIENTRY _mesa_DeleteLists (GLuint list, GLsizei range)
Delete a sequence of consecutive display lists.
GLuint GLAPIENTRY _mesa_GenLists (GLsizei range)
Return a display list number, n, such that lists n through n+range-1 are free.
void GLAPIENTRY _mesa_NewList (GLuint name, GLenum mode)
Begin a new display list.
void GLAPIENTRY _mesa_EndList (void)
End definition of current display list.
void GLAPIENTRY _mesa_CallList (GLuint list)
static bool render_bitmap_atlas (struct gl_context *ctx, GLsizei n, GLenum type, const void *lists)
Try to execute a glCallLists() command where the display lists contain glBitmap commands with a texture atlas.
void GLAPIENTRY _mesa_CallLists (GLsizei n, GLenum type, const GLvoid *lists)
Execute glCallLists: call multiple display lists.
void GLAPIENTRY _mesa_ListBase (GLuint base)
Set the offset added to list numbers in glCallLists.
void _mesa_initialize_save_table (const struct gl_context *ctx)
Setup the given dispatch table to point to Mesa's display list building functions.
static const char * enum_string (GLenum k)
static void GLAPIENTRY print_list (struct gl_context *ctx, GLuint list, const char *fname)
Print the commands in a display list.
static void save_vtxfmt_init (GLvertexformat *vfmt)
void _mesa_install_dlist_vtxfmt (struct _glapi_table *disp, const GLvertexformat *vfmt)
void _mesa_init_display_list (struct gl_context *ctx)
Initialize display list state for given context.
void _mesa_free_display_list_data (struct gl_context *ctx)
Variables
static GLuint InstSize [OPCODE_END_OF_LIST+1]
Number of nodes of storage needed for each instruction.
Detailed Description
Display lists management functions.
Macro Definition Documentation
ASSERT_OUTSIDE_SAVE_BEGIN_END
#define ASSERT_OUTSIDE_SAVE_BEGIN_END (ctx)
Value:
do {                                                                 \
      if (ctx->Driver.CurrentSavePrimitive <= PRIM_MAX) {               \
         _mesa_compile_error( ctx, GL_INVALID_OPERATION, "glBegin/End" ); \
         return;                                                        \
      }                                                                 \
   } while (0)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair.
Parameters
ctx GL context.
Referenced by save_ShadeModel().
ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH
#define ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH (ctx)
Value:
do {                                                                 \
      ASSERT_OUTSIDE_SAVE_BEGIN_END(ctx);                               \
      SAVE_FLUSH_VERTICES(ctx);                                         \
   } while (0)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair and flush the vertices.
Parameters
ctx GL context.
Referenced by save_Accum(), save_ActiveStencilFaceEXT(), save_ActiveTextureARB(), save_AlphaFunc(), save_BeginConditionalRender(), save_BeginQueryARB(), save_BeginQueryIndexed(), save_BeginTransformFeedback(), save_BindProgramARB(), save_BindSampler(), save_BindTexture(), save_BindTransformFeedback(), save_Bitmap(), save_BlendColor(), save_BlendEquation(), save_BlendEquationi(), save_BlendEquationSeparateEXT(), save_BlendEquationSeparatei(), save_BlendFunci(), save_BlendFuncSeparateEXT(), save_BlendFuncSeparatei(), save_BlitFramebufferEXT(), save_ClampColorARB(), save_Clear(), save_ClearAccum(), save_ClearBufferfi(), save_ClearBufferfv(), save_ClearBufferiv(), save_ClearBufferuiv(), save_ClearColor(), save_ClearColorIi(), save_ClearColorIui(), save_ClearDepth(), save_ClearIndex(), save_ClearStencil(), save_ClipControl(), save_ClipPlane(), save_ColorMask(), save_ColorMaskIndexed(), save_ColorMaterial(), save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), save_CompressedTexSubImage3DARB(), save_CopyPixels(), save_CopyTexImage1D(), save_CopyTexImage2D(), save_CopyTexSubImage1D(), save_CopyTexSubImage2D(), save_CopyTexSubImage3D(), save_CullFace(), save_DepthBoundsEXT(), save_DepthFunc(), save_DepthMask(), save_DepthRange(), save_Disable(), save_DisableIndexed(), save_DrawBuffer(), save_DrawBuffersARB(), save_DrawPixels(), save_DrawTransformFeedback(), save_DrawTransformFeedbackInstanced(), save_DrawTransformFeedbackStream(), save_DrawTransformFeedbackStreamInstanced(), save_Enable(), save_EnableIndexed(), save_EndConditionalRender(), save_EndQueryARB(), save_EndQueryIndexed(), save_EndTransformFeedback(), save_EvalMesh1(), save_EvalMesh2(), save_Fogfv(), save_FrontFace(), save_Frustum(), save_Hint(), save_IndexMask(), save_InitNames(), save_Lightfv(), save_LightModelfv(), save_LineStipple(), save_LineWidth(), save_ListBase(), save_LoadIdentity(), save_LoadMatrixf(), save_LoadName(), save_LogicOp(), save_Map1d(), save_Map1f(), save_Map2d(), save_Map2f(), save_MapGrid1f(), save_MapGrid2f(), save_MatrixMode(), save_MultMatrixf(), save_Ortho(), save_PassThrough(), save_PauseTransformFeedback(), save_PixelMapfv(), save_PixelTransferf(), save_PixelZoom(), save_PointParameterfvEXT(), save_PointSize(), save_PolygonMode(), save_PolygonOffset(), save_PolygonOffsetClampEXT(), save_PolygonStipple(), save_PopAttrib(), save_PopMatrix(), save_PopName(), save_PrioritizeTextures(), save_ProgramEnvParameter4fARB(), save_ProgramEnvParameters4fvEXT(), save_ProgramLocalParameter4dARB(), save_ProgramLocalParameter4dvARB(), save_ProgramLocalParameter4fARB(), save_ProgramLocalParameter4fvARB(), save_ProgramLocalParameters4fvEXT(), save_ProgramStringARB(), save_ProgramUniform1f(), save_ProgramUniform1fv(), save_ProgramUniform1i(), save_ProgramUniform1iv(), save_ProgramUniform1ui(), save_ProgramUniform1uiv(), save_ProgramUniform2f(), save_ProgramUniform2fv(), save_ProgramUniform2i(), save_ProgramUniform2iv(), save_ProgramUniform2ui(), save_ProgramUniform2uiv(), save_ProgramUniform3f(), save_ProgramUniform3fv(), save_ProgramUniform3i(), save_ProgramUniform3iv(), save_ProgramUniform3ui(), save_ProgramUniform3uiv(), save_ProgramUniform4f(), save_ProgramUniform4fv(), save_ProgramUniform4i(), save_ProgramUniform4iv(), save_ProgramUniform4ui(), save_ProgramUniform4uiv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_ProvokingVertexEXT(), save_PushAttrib(), save_PushMatrix(), save_PushName(), save_QueryCounter(), save_RasterPos4f(), save_ReadBuffer(), save_Rectf(), save_ResumeTransformFeedback(), save_Rotatef(), save_SampleCoverageARB(), save_SamplerParameterfv(), save_SamplerParameterIiv(), save_SamplerParameterIuiv(), save_SamplerParameteriv(), save_Scalef(), save_Scissor(), save_StencilFunc(), save_StencilFuncSeparate(), save_StencilFuncSeparateATI(), save_StencilMask(), save_StencilMaskSeparate(), save_StencilOp(), save_StencilOpSeparate(), save_TexEnvfv(), save_TexGenfv(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexParameterfv(), save_TexParameterIiv(), save_TexParameterIuiv(), save_TexSubImage1D(), save_TexSubImage2D(), save_TexSubImage3D(), save_TextureBarrierNV(), save_Translatef(), save_Uniform1fARB(), save_Uniform1fvARB(), save_Uniform1iARB(), save_Uniform1ivARB(), save_Uniform1ui(), save_Uniform1uiv(), save_Uniform2fARB(), save_Uniform2fvARB(), save_Uniform2iARB(), save_Uniform2ivARB(), save_Uniform2ui(), save_Uniform2uiv(), save_Uniform3fARB(), save_Uniform3fvARB(), save_Uniform3iARB(), save_Uniform3ivARB(), save_Uniform3ui(), save_Uniform3uiv(), save_Uniform4fARB(), save_Uniform4fvARB(), save_Uniform4iARB(), save_Uniform4ivARB(), save_Uniform4ui(), save_Uniform4uiv(), save_UniformBlockBinding(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), save_UseProgram(), save_UseProgramStages(), save_VertexAttribDivisor(), save_Viewport(), save_WaitSync(), save_WindowPos4fMESA(), and save_WindowRectanglesEXT().
ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH_WITH_RETVAL
#define ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH_WITH_RETVAL (ctx, retval)
Value:
do {                                                                 \
      ASSERT_OUTSIDE_SAVE_BEGIN_END_WITH_RETVAL(ctx, retval);           \
      SAVE_FLUSH_VERTICES(ctx);                                         \
   } while (0)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair and flush the vertices, with return value.
Parameters
ctx GL context.
retval value to return value in case the assertion fails.
ASSERT_OUTSIDE_SAVE_BEGIN_END_WITH_RETVAL
#define ASSERT_OUTSIDE_SAVE_BEGIN_END_WITH_RETVAL (ctx, retval)
Value:
do {                                                                 \
      if (ctx->Driver.CurrentSavePrimitive <= PRIM_MAX) {               \
         _mesa_compile_error( ctx, GL_INVALID_OPERATION, "glBegin/End" ); \
         return retval;                                                 \
      }                                                                 \
   } while (0)
Macro to assert that the API call was made outside the glBegin()/glEnd() pair, with return value.
Parameters
ctx GL context.
retval value to return value in case the assertion fails.
BLOCK_SIZE
#define BLOCK_SIZE 256
How many nodes to allocate at a time.
Note that bulk vertex data from glBegin/glVertex/glEnd primitives will typically wind up in a VBO, and not directly in the display list itself.
Referenced by _mesa_NewList(), dlist_alloc(), and trim_list().
MAX_DLIST_EXT_OPCODES
#define MAX_DLIST_EXT_OPCODES 16
Referenced by _mesa_dlist_alloc_opcode().
POINTER_DWORDS
#define POINTER_DWORDS (sizeof(void *) / 4)
How many 4-byte dwords to store a pointer.
Referenced by dlist_alloc(), get_pointer(), save_Bitmap(), save_CallLists(), save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), save_CompressedTexSubImage3DARB(), save_DrawPixels(), save_error(), save_Map1d(), save_Map1f(), save_Map2d(), save_Map2f(), save_PixelMapfv(), save_pointer(), save_PolygonStipple(), save_ProgramStringARB(), save_ProgramUniform1fv(), save_ProgramUniform1iv(), save_ProgramUniform1uiv(), save_ProgramUniform2fv(), save_ProgramUniform2iv(), save_ProgramUniform2uiv(), save_ProgramUniform3fv(), save_ProgramUniform3iv(), save_ProgramUniform3uiv(), save_ProgramUniform4fv(), save_ProgramUniform4iv(), save_ProgramUniform4uiv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexSubImage1D(), save_TexSubImage2D(), save_TexSubImage3D(), save_Uniform1fvARB(), save_Uniform1ivARB(), save_Uniform1uiv(), save_Uniform2fvARB(), save_Uniform2ivARB(), save_Uniform2uiv(), save_Uniform3fvARB(), save_Uniform3ivARB(), save_Uniform3uiv(), save_Uniform4fvARB(), save_Uniform4ivARB(), save_Uniform4uiv(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), and save_WindowRectanglesEXT().
SAVE_FLUSH_VERTICES
#define SAVE_FLUSH_VERTICES (ctx)
Value:
do {                                              \
      if (ctx->Driver.SaveNeedFlush)                 \
         vbo_save_SaveFlushVertices(ctx);            \
   } while (0)
Flush vertices.
Parameters
ctx GL context.
Checks if dd_function_table::SaveNeedFlush is marked to flush stored (save) vertices, and calls vbo_save_SaveFlushVertices if so.
Referenced by _mesa_EndList(), save_Attr1fARB(), save_Attr1fNV(), save_Attr2fARB(), save_Attr2fNV(), save_Attr3fARB(), save_Attr3fNV(), save_Attr4fARB(), save_Attr4fNV(), save_Begin(), save_CallList(), save_CallLists(), save_End(), save_EvalCoord1f(), save_EvalCoord2f(), save_EvalPoint1(), save_EvalPoint2(), save_Materialfv(), and save_ShadeModel().
USE_BITMAP_ATLAS
#define USE_BITMAP_ATLAS 1
Referenced by _mesa_GenLists(), and render_bitmap_atlas().
Typedef Documentation
Node
typedef union gl_dlist_node Node
Enumeration Type Documentation
OpCode
enum OpCode
Display list opcodes.
The fact that these identifiers are assigned consecutive integer values starting at 0 is very important, see InstSize array usage)
Enumerator
OPCODE_INVALID
OPCODE_ACCUM
OPCODE_ALPHA_FUNC
OPCODE_BIND_TEXTURE
OPCODE_BITMAP
OPCODE_BLEND_COLOR
OPCODE_BLEND_EQUATION
OPCODE_BLEND_EQUATION_SEPARATE
OPCODE_BLEND_FUNC_SEPARATE
OPCODE_BLEND_EQUATION_I
OPCODE_BLEND_EQUATION_SEPARATE_I
OPCODE_BLEND_FUNC_I
OPCODE_BLEND_FUNC_SEPARATE_I
OPCODE_CALL_LIST
OPCODE_CALL_LISTS
OPCODE_CLEAR
OPCODE_CLEAR_ACCUM
OPCODE_CLEAR_COLOR
OPCODE_CLEAR_DEPTH
OPCODE_CLEAR_INDEX
OPCODE_CLEAR_STENCIL
OPCODE_CLEAR_BUFFER_IV
OPCODE_CLEAR_BUFFER_UIV
OPCODE_CLEAR_BUFFER_FV
OPCODE_CLEAR_BUFFER_FI
OPCODE_CLIP_PLANE
OPCODE_COLOR_MASK
OPCODE_COLOR_MASK_INDEXED
OPCODE_COLOR_MATERIAL
OPCODE_COPY_PIXELS
OPCODE_COPY_TEX_IMAGE1D
OPCODE_COPY_TEX_IMAGE2D
OPCODE_COPY_TEX_SUB_IMAGE1D
OPCODE_COPY_TEX_SUB_IMAGE2D
OPCODE_COPY_TEX_SUB_IMAGE3D
OPCODE_CULL_FACE
OPCODE_DEPTH_FUNC
OPCODE_DEPTH_MASK
OPCODE_DEPTH_RANGE
OPCODE_DISABLE
OPCODE_DISABLE_INDEXED
OPCODE_DRAW_BUFFER
OPCODE_DRAW_PIXELS
OPCODE_ENABLE
OPCODE_ENABLE_INDEXED
OPCODE_EVALMESH1
OPCODE_EVALMESH2
OPCODE_FOG
OPCODE_FRONT_FACE
OPCODE_FRUSTUM
OPCODE_HINT
OPCODE_INDEX_MASK
OPCODE_INIT_NAMES
OPCODE_LIGHT
OPCODE_LIGHT_MODEL
OPCODE_LINE_STIPPLE
OPCODE_LINE_WIDTH
OPCODE_LIST_BASE
OPCODE_LOAD_IDENTITY
OPCODE_LOAD_MATRIX
OPCODE_LOAD_NAME
OPCODE_LOGIC_OP
OPCODE_MAP1
OPCODE_MAP2
OPCODE_MAPGRID1
OPCODE_MAPGRID2
OPCODE_MATRIX_MODE
OPCODE_MULT_MATRIX
OPCODE_ORTHO
OPCODE_PASSTHROUGH
OPCODE_PIXEL_MAP
OPCODE_PIXEL_TRANSFER
OPCODE_PIXEL_ZOOM
OPCODE_POINT_SIZE
OPCODE_POINT_PARAMETERS
OPCODE_POLYGON_MODE
OPCODE_POLYGON_STIPPLE
OPCODE_POLYGON_OFFSET
OPCODE_POP_ATTRIB
OPCODE_POP_MATRIX
OPCODE_POP_NAME
OPCODE_PRIORITIZE_TEXTURE
OPCODE_PUSH_ATTRIB
OPCODE_PUSH_MATRIX
OPCODE_PUSH_NAME
OPCODE_RASTER_POS
OPCODE_READ_BUFFER
OPCODE_ROTATE
OPCODE_SCALE
OPCODE_SCISSOR
OPCODE_SELECT_TEXTURE_SGIS
OPCODE_SELECT_TEXTURE_COORD_SET
OPCODE_SHADE_MODEL
OPCODE_STENCIL_FUNC
OPCODE_STENCIL_MASK
OPCODE_STENCIL_OP
OPCODE_TEXENV
OPCODE_TEXGEN
OPCODE_TEXPARAMETER
OPCODE_TEX_IMAGE1D
OPCODE_TEX_IMAGE2D
OPCODE_TEX_IMAGE3D
OPCODE_TEX_SUB_IMAGE1D
OPCODE_TEX_SUB_IMAGE2D
OPCODE_TEX_SUB_IMAGE3D
OPCODE_TRANSLATE
OPCODE_VIEWPORT
OPCODE_WINDOW_POS
OPCODE_ACTIVE_TEXTURE
OPCODE_COMPRESSED_TEX_IMAGE_1D
OPCODE_COMPRESSED_TEX_IMAGE_2D
OPCODE_COMPRESSED_TEX_IMAGE_3D
OPCODE_COMPRESSED_TEX_SUB_IMAGE_1D
OPCODE_COMPRESSED_TEX_SUB_IMAGE_2D
OPCODE_COMPRESSED_TEX_SUB_IMAGE_3D
OPCODE_SAMPLE_COVERAGE
OPCODE_WINDOW_POS_ARB
OPCODE_BIND_PROGRAM_ARB
OPCODE_PROGRAM_LOCAL_PARAMETER_ARB
OPCODE_ACTIVE_STENCIL_FACE_EXT
OPCODE_DEPTH_BOUNDS_EXT
OPCODE_PROGRAM_STRING_ARB
OPCODE_PROGRAM_ENV_PARAMETER_ARB
OPCODE_BEGIN_QUERY_ARB
OPCODE_END_QUERY_ARB
OPCODE_DRAW_BUFFERS_ARB
OPCODE_BIND_FRAGMENT_SHADER_ATI
OPCODE_SET_FRAGMENT_SHADER_CONSTANTS_ATI
OPCODE_STENCIL_FUNC_SEPARATE
OPCODE_STENCIL_OP_SEPARATE
OPCODE_STENCIL_MASK_SEPARATE
OPCODE_USE_PROGRAM
OPCODE_UNIFORM_1F
OPCODE_UNIFORM_2F
OPCODE_UNIFORM_3F
OPCODE_UNIFORM_4F
OPCODE_UNIFORM_1FV
OPCODE_UNIFORM_2FV
OPCODE_UNIFORM_3FV
OPCODE_UNIFORM_4FV
OPCODE_UNIFORM_1I
OPCODE_UNIFORM_2I
OPCODE_UNIFORM_3I
OPCODE_UNIFORM_4I
OPCODE_UNIFORM_1IV
OPCODE_UNIFORM_2IV
OPCODE_UNIFORM_3IV
OPCODE_UNIFORM_4IV
OPCODE_UNIFORM_MATRIX22
OPCODE_UNIFORM_MATRIX33
OPCODE_UNIFORM_MATRIX44
OPCODE_UNIFORM_MATRIX23
OPCODE_UNIFORM_MATRIX32
OPCODE_UNIFORM_MATRIX24
OPCODE_UNIFORM_MATRIX42
OPCODE_UNIFORM_MATRIX34
OPCODE_UNIFORM_MATRIX43
OPCODE_UNIFORM_1UI
OPCODE_UNIFORM_2UI
OPCODE_UNIFORM_3UI
OPCODE_UNIFORM_4UI
OPCODE_UNIFORM_1UIV
OPCODE_UNIFORM_2UIV
OPCODE_UNIFORM_3UIV
OPCODE_UNIFORM_4UIV
OPCODE_USE_PROGRAM_STAGES
OPCODE_PROGRAM_UNIFORM_1F
OPCODE_PROGRAM_UNIFORM_2F
OPCODE_PROGRAM_UNIFORM_3F
OPCODE_PROGRAM_UNIFORM_4F
OPCODE_PROGRAM_UNIFORM_1FV
OPCODE_PROGRAM_UNIFORM_2FV
OPCODE_PROGRAM_UNIFORM_3FV
OPCODE_PROGRAM_UNIFORM_4FV
OPCODE_PROGRAM_UNIFORM_1I
OPCODE_PROGRAM_UNIFORM_2I
OPCODE_PROGRAM_UNIFORM_3I
OPCODE_PROGRAM_UNIFORM_4I
OPCODE_PROGRAM_UNIFORM_1IV
OPCODE_PROGRAM_UNIFORM_2IV
OPCODE_PROGRAM_UNIFORM_3IV
OPCODE_PROGRAM_UNIFORM_4IV
OPCODE_PROGRAM_UNIFORM_1UI
OPCODE_PROGRAM_UNIFORM_2UI
OPCODE_PROGRAM_UNIFORM_3UI
OPCODE_PROGRAM_UNIFORM_4UI
OPCODE_PROGRAM_UNIFORM_1UIV
OPCODE_PROGRAM_UNIFORM_2UIV
OPCODE_PROGRAM_UNIFORM_3UIV
OPCODE_PROGRAM_UNIFORM_4UIV
OPCODE_PROGRAM_UNIFORM_MATRIX22F
OPCODE_PROGRAM_UNIFORM_MATRIX33F
OPCODE_PROGRAM_UNIFORM_MATRIX44F
OPCODE_PROGRAM_UNIFORM_MATRIX23F
OPCODE_PROGRAM_UNIFORM_MATRIX32F
OPCODE_PROGRAM_UNIFORM_MATRIX24F
OPCODE_PROGRAM_UNIFORM_MATRIX42F
OPCODE_PROGRAM_UNIFORM_MATRIX34F
OPCODE_PROGRAM_UNIFORM_MATRIX43F
OPCODE_CLIP_CONTROL
OPCODE_CLAMP_COLOR
OPCODE_BLIT_FRAMEBUFFER
OPCODE_ATTR_1F_NV
OPCODE_ATTR_2F_NV
OPCODE_ATTR_3F_NV
OPCODE_ATTR_4F_NV
OPCODE_ATTR_1F_ARB
OPCODE_ATTR_2F_ARB
OPCODE_ATTR_3F_ARB
OPCODE_ATTR_4F_ARB
OPCODE_MATERIAL
OPCODE_BEGIN
OPCODE_END
OPCODE_RECTF
OPCODE_EVAL_C1
OPCODE_EVAL_C2
OPCODE_EVAL_P1
OPCODE_EVAL_P2
OPCODE_PROVOKING_VERTEX
OPCODE_BEGIN_TRANSFORM_FEEDBACK
OPCODE_END_TRANSFORM_FEEDBACK
OPCODE_BIND_TRANSFORM_FEEDBACK
OPCODE_PAUSE_TRANSFORM_FEEDBACK
OPCODE_RESUME_TRANSFORM_FEEDBACK
OPCODE_DRAW_TRANSFORM_FEEDBACK
OPCODE_CLEARCOLOR_I
OPCODE_CLEARCOLOR_UI
OPCODE_TEXPARAMETER_I
OPCODE_TEXPARAMETER_UI
OPCODE_VERTEX_ATTRIB_DIVISOR
OPCODE_TEXTURE_BARRIER_NV
OPCODE_BIND_SAMPLER
OPCODE_SAMPLER_PARAMETERIV
OPCODE_SAMPLER_PARAMETERFV
OPCODE_SAMPLER_PARAMETERIIV
OPCODE_SAMPLER_PARAMETERUIV
OPCODE_WAIT_SYNC
OPCODE_BEGIN_CONDITIONAL_RENDER
OPCODE_END_CONDITIONAL_RENDER
OPCODE_QUERY_COUNTER
OPCODE_BEGIN_QUERY_INDEXED
OPCODE_END_QUERY_INDEXED
OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM
OPCODE_DRAW_TRANSFORM_FEEDBACK_INSTANCED
OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM_INSTANCED
OPCODE_UNIFORM_BLOCK_BINDING
OPCODE_POLYGON_OFFSET_CLAMP
OPCODE_WINDOW_RECTANGLES
OPCODE_ERROR
OPCODE_CONTINUE
OPCODE_NOP
OPCODE_END_OF_LIST
OPCODE_EXT_0
Function Documentation
_mesa_CallList()
void GLAPIENTRY _mesa_CallList (GLuint list)
References _glapi_set_dispatch(), _mesa_debug(), _mesa_error(), gl_context::CompileFlag, gl_context::CurrentClientDispatch, gl_context::CurrentServerDispatch, execute_list(), FLUSH_CURRENT, GET_CURRENT_CONTEXT, gl_context::MarshalExec, mesa_print_display_list(), MESA_VERBOSE, gl_context::Save, and VERBOSE_API.
Referenced by save_CallList().
_mesa_CallLists()
void GLAPIENTRY _mesa_CallLists (GLsizei n, GLenum type, const GLvoid * lists)
Execute glCallLists: call multiple display lists.
References _glapi_set_dispatch(), _mesa_debug(), _mesa_error(), gl_context::CompileFlag, gl_context::CurrentClientDispatch, gl_context::CurrentServerDispatch, execute_list(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_context::List, gl_list_attrib::ListBase, gl_context::MarshalExec, MESA_VERBOSE, render_bitmap_atlas(), gl_context::Save, translate_id(), and VERBOSE_API.
_mesa_compile_error()
void _mesa_compile_error (struct gl_context * ctx, GLenum error, const char * s)
Compile an error into current display list.
References _mesa_error(), gl_context::CompileFlag, gl_context::ExecuteFlag, and save_error().
Referenced by save_Begin(), and save_Materialfv().
_mesa_delete_bitmap_atlas()
void _mesa_delete_bitmap_atlas (struct gl_context * ctx, struct gl_bitmap_atlas * atlas)
Delete/free a gl_bitmap_atlas.
Called during context tear-down.
References dd_function_table::DeleteTexture, gl_context::Driver, gl_bitmap_atlas::glyphs, and gl_bitmap_atlas::texObj.
Referenced by _mesa_DeleteLists(), and delete_bitmap_atlas_cb().
_mesa_delete_list()
void _mesa_delete_list (struct gl_context * ctx, struct gl_display_list * dlist)
Delete the named display list, but don't remove from hash table.
Parameters
dlist - display list pointer
References ext_opcode_destroy(), get_pointer(), gl_display_list::Head, InstSize, is_ext_opcode(), gl_display_list::Label, gl_dlist_node::opcode, OPCODE_BITMAP, OPCODE_CALL_LISTS, OPCODE_COMPRESSED_TEX_IMAGE_1D, OPCODE_COMPRESSED_TEX_IMAGE_2D, OPCODE_COMPRESSED_TEX_IMAGE_3D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_1D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_2D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_3D, OPCODE_CONTINUE, OPCODE_DRAW_PIXELS, OPCODE_END_OF_LIST, OPCODE_MAP1, OPCODE_MAP2, OPCODE_PIXEL_MAP, OPCODE_POLYGON_STIPPLE, OPCODE_PROGRAM_STRING_ARB, OPCODE_PROGRAM_UNIFORM_1FV, OPCODE_PROGRAM_UNIFORM_1IV, OPCODE_PROGRAM_UNIFORM_1UIV, OPCODE_PROGRAM_UNIFORM_2FV, OPCODE_PROGRAM_UNIFORM_2IV, OPCODE_PROGRAM_UNIFORM_2UIV, OPCODE_PROGRAM_UNIFORM_3FV, OPCODE_PROGRAM_UNIFORM_3IV, OPCODE_PROGRAM_UNIFORM_3UIV, OPCODE_PROGRAM_UNIFORM_4FV, OPCODE_PROGRAM_UNIFORM_4IV, OPCODE_PROGRAM_UNIFORM_4UIV, OPCODE_PROGRAM_UNIFORM_MATRIX22F, OPCODE_PROGRAM_UNIFORM_MATRIX23F, OPCODE_PROGRAM_UNIFORM_MATRIX24F, OPCODE_PROGRAM_UNIFORM_MATRIX32F, OPCODE_PROGRAM_UNIFORM_MATRIX33F, OPCODE_PROGRAM_UNIFORM_MATRIX34F, OPCODE_PROGRAM_UNIFORM_MATRIX42F, OPCODE_PROGRAM_UNIFORM_MATRIX43F, OPCODE_PROGRAM_UNIFORM_MATRIX44F, OPCODE_TEX_IMAGE1D, OPCODE_TEX_IMAGE2D, OPCODE_TEX_IMAGE3D, OPCODE_TEX_SUB_IMAGE1D, OPCODE_TEX_SUB_IMAGE2D, OPCODE_TEX_SUB_IMAGE3D, OPCODE_UNIFORM_1FV, OPCODE_UNIFORM_1IV, OPCODE_UNIFORM_1UIV, OPCODE_UNIFORM_2FV, OPCODE_UNIFORM_2IV, OPCODE_UNIFORM_2UIV, OPCODE_UNIFORM_3FV, OPCODE_UNIFORM_3IV, OPCODE_UNIFORM_3UIV, OPCODE_UNIFORM_4FV, OPCODE_UNIFORM_4IV, OPCODE_UNIFORM_4UIV, OPCODE_UNIFORM_MATRIX22, OPCODE_UNIFORM_MATRIX23, OPCODE_UNIFORM_MATRIX24, OPCODE_UNIFORM_MATRIX32, OPCODE_UNIFORM_MATRIX33, OPCODE_UNIFORM_MATRIX34, OPCODE_UNIFORM_MATRIX42, OPCODE_UNIFORM_MATRIX43, OPCODE_UNIFORM_MATRIX44, and OPCODE_WINDOW_RECTANGLES.
Referenced by delete_displaylist_cb(), and destroy_list().
_mesa_DeleteLists()
void GLAPIENTRY _mesa_DeleteLists (GLuint list, GLsizei range)
Delete a sequence of consecutive display lists.
References _mesa_delete_bitmap_atlas(), _mesa_error(), _mesa_HashRemove(), ASSERT_OUTSIDE_BEGIN_END, gl_shared_state::BitmapAtlas, destroy_list(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, lookup_bitmap_atlas(), and gl_context::Shared.
_mesa_dlist_alloc()
void* _mesa_dlist_alloc (struct gl_context * ctx, GLuint opcode, GLuint bytes)
Allocate space for a display list instruction.
Used by callers outside this file for things like VBO vertex data.
Parameters
opcode the instruction opcode (OPCODE_* value)
bytes instruction size in bytes, not counting opcode.
Returns
pointer to the usable data area (not including the internal opcode).
References dlist_alloc().
_mesa_dlist_alloc_aligned()
void* _mesa_dlist_alloc_aligned (struct gl_context * ctx, GLuint opcode, GLuint bytes)
Same as _mesa_dlist_alloc(), but return a pointer which is 8-byte aligned in 64-bit environments, 4-byte aligned otherwise.
References dlist_alloc().
_mesa_dlist_alloc_opcode()
GLint _mesa_dlist_alloc_opcode (struct gl_context * ctx, GLuint size, void(*)(struct gl_context *, void *) execute, void(*)(struct gl_context *, void *) destroy, void(*)(struct gl_context *, void *, FILE *) print)
This function allows modules and drivers to get their own opcodes for extending display list functionality.
Parameters
ctx the rendering context
size number of bytes for storing the new display list command
execute function to execute the new display list command
destroy function to destroy the new display list command
print function to print the new display list command
Returns
the new opcode number or -1 if error
References gl_list_instruction::Destroy, gl_list_instruction::Execute, GLuint, gl_context::ListExt, MAX_DLIST_EXT_OPCODES, gl_list_extensions::NumOpcodes, gl_list_extensions::Opcode, OPCODE_EXT_0, gl_list_instruction::Print, and gl_list_instruction::Size.
_mesa_EndList()
void GLAPIENTRY _mesa_EndList (void)
End definition of current display list.
References _glapi_set_dispatch(), _mesa_debug(), _mesa_error(), _mesa_HashInsert(), _mesa_inside_dlist_begin_end(), alloc_instruction(), gl_context::CompileFlag, gl_dlist_state::CurrentBlock, gl_context::CurrentClientDispatch, gl_dlist_state::CurrentList, gl_dlist_state::CurrentPos, gl_context::CurrentServerDispatch, destroy_list(), gl_shared_state::DisplayList, gl_context::Exec, gl_context::ExecuteFlag, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, gl_context::MarshalExec, mesa_print_display_list(), MESA_VERBOSE, gl_display_list::Name, OPCODE_END_OF_LIST, SAVE_FLUSH_VERTICES, gl_context::Shared, trim_list(), vbo_save_EndList(), VERBOSE_API, VERBOSE_DISPLAY_LIST, and void.
_mesa_free_display_list_data()
void _mesa_free_display_list_data (struct gl_context * ctx)
References gl_context::ListExt.
Referenced by _mesa_free_context_data().
_mesa_GenLists()
GLuint GLAPIENTRY _mesa_GenLists (GLsizei range)
Return a display list number, n, such that lists n through n+range-1 are free.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), alloc_bitmap_atlas(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_shared_state::DisplayList, dd_function_table::DrawAtlasBitmaps, gl_context::Driver, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, lookup_bitmap_atlas(), make_list(), gl_bitmap_atlas::numBitmaps, gl_context::Shared, and USE_BITMAP_ATLAS.
_mesa_init_display_list()
void _mesa_init_display_list (struct gl_context * ctx)
Initialize display list state for given context.
References gl_dlist_state::CallDepth, CALLOC_STRUCT, gl_context::CompileFlag, gl_dlist_state::CurrentBlock, gl_dlist_state::CurrentPos, gl_context::ExecuteFlag, InstSize, gl_context::List, gl_list_attrib::ListBase, gl_context::ListExt, gl_context::ListState, gl_dlist_state::ListVtxfmt, OPCODE_NOP, and save_vtxfmt_init().
Referenced by init_attrib_groups().
_mesa_initialize_save_table()
void _mesa_initialize_save_table (const struct gl_context * ctx)
Setup the given dispatch table to point to Mesa's display list building functions.
This does not include any of the tnl functions - they are initialized from _mesa_init_api_defaults and from the active vtxfmt struct.
References _glapi_get_dispatch_table_size(), _mesa_loopback_init_api_table(), gl_context::Exec, gl_context::Save, save_Accum(), save_ActiveStencilFaceEXT(), save_ActiveTextureARB(), save_AlphaFunc(), save_BeginConditionalRender(), save_BeginQueryARB(), save_BeginQueryIndexed(), save_BeginTransformFeedback(), save_BindFragmentShaderATI(), save_BindProgramARB(), save_BindSampler(), save_BindTexture(), save_BindTransformFeedback(), save_Bitmap(), save_BlendColor(), save_BlendEquation(), save_BlendEquationi(), save_BlendEquationSeparateEXT(), save_BlendEquationSeparatei(), save_BlendFunc(), save_BlendFunci(), save_BlendFuncSeparateEXT(), save_BlendFuncSeparatei(), save_BlitFramebufferEXT(), save_CallList(), save_CallLists(), save_ClampColorARB(), save_Clear(), save_ClearAccum(), save_ClearBufferfi(), save_ClearBufferfv(), save_ClearBufferiv(), save_ClearBufferuiv(), save_ClearColor(), save_ClearColorIi(), save_ClearColorIui(), save_ClearDepth(), save_ClearIndex(), save_ClearStencil(), save_ClipControl(), save_ClipPlane(), save_ColorMask(), save_ColorMaskIndexed(), save_ColorMaterial(), save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), save_CompressedTexSubImage3DARB(), save_CopyPixels(), save_CopyTexImage1D(), save_CopyTexImage2D(), save_CopyTexSubImage1D(), save_CopyTexSubImage2D(), save_CopyTexSubImage3D(), save_CullFace(), save_DepthBoundsEXT(), save_DepthFunc(), save_DepthMask(), save_DepthRange(), save_Disable(), save_DisableIndexed(), save_DrawArraysInstancedARB(), save_DrawArraysInstancedBaseInstance(), save_DrawBuffer(), save_DrawBuffersARB(), save_DrawElementsInstancedARB(), save_DrawElementsInstancedBaseInstance(), save_DrawElementsInstancedBaseVertexARB(), save_DrawElementsInstancedBaseVertexBaseInstance(), save_DrawPixels(), save_DrawTransformFeedback(), save_DrawTransformFeedbackInstanced(), save_DrawTransformFeedbackStream(), save_DrawTransformFeedbackStreamInstanced(), save_Enable(), save_EnableIndexed(), save_EndConditionalRender(), save_EndQueryARB(), save_EndQueryIndexed(), save_EndTransformFeedback(), save_EvalMesh1(), save_EvalMesh2(), save_Fogf(), save_Fogfv(), save_Fogi(), save_Fogiv(), save_FrontFace(), save_Frustum(), save_Hint(), save_IndexMask(), save_InitNames(), save_Lightf(), save_Lightfv(), save_Lighti(), save_Lightiv(), save_LightModelf(), save_LightModelfv(), save_LightModeli(), save_LightModeliv(), save_LineStipple(), save_LineWidth(), save_ListBase(), save_LoadIdentity(), save_LoadMatrixd(), save_LoadMatrixf(), save_LoadName(), save_LoadTransposeMatrixdARB(), save_LoadTransposeMatrixfARB(), save_LogicOp(), save_Map1d(), save_Map1f(), save_Map2d(), save_Map2f(), save_MapGrid1d(), save_MapGrid1f(), save_MapGrid2d(), save_MapGrid2f(), save_MatrixMode(), save_MultMatrixd(), save_MultMatrixf(), save_MultTransposeMatrixdARB(), save_MultTransposeMatrixfARB(), save_NewList(), save_Ortho(), save_PassThrough(), save_PauseTransformFeedback(), save_PixelMapfv(), save_PixelMapuiv(), save_PixelMapusv(), save_PixelTransferf(), save_PixelTransferi(), save_PixelZoom(), save_PointParameterfEXT(), save_PointParameterfvEXT(), save_PointParameteriNV(), save_PointParameterivNV(), save_PointSize(), save_PolygonMode(), save_PolygonOffset(), save_PolygonOffsetClampEXT(), save_PolygonOffsetEXT(), save_PolygonStipple(), save_PopAttrib(), save_PopMatrix(), save_PopName(), save_PrioritizeTextures(), save_ProgramEnvParameter4dARB(), save_ProgramEnvParameter4dvARB(), save_ProgramEnvParameter4fARB(), save_ProgramEnvParameter4fvARB(), save_ProgramEnvParameters4fvEXT(), save_ProgramLocalParameter4dARB(), save_ProgramLocalParameter4dvARB(), save_ProgramLocalParameter4fARB(), save_ProgramLocalParameter4fvARB(), save_ProgramLocalParameters4fvEXT(), save_ProgramStringARB(), save_ProgramUniform1f(), save_ProgramUniform1fv(), save_ProgramUniform1i(), save_ProgramUniform1iv(), save_ProgramUniform1ui(), save_ProgramUniform1uiv(), save_ProgramUniform2f(), save_ProgramUniform2fv(), save_ProgramUniform2i(), save_ProgramUniform2iv(), save_ProgramUniform2ui(), save_ProgramUniform2uiv(), save_ProgramUniform3f(), save_ProgramUniform3fv(), save_ProgramUniform3i(), save_ProgramUniform3iv(), save_ProgramUniform3ui(), save_ProgramUniform3uiv(), save_ProgramUniform4f(), save_ProgramUniform4fv(), save_ProgramUniform4i(), save_ProgramUniform4iv(), save_ProgramUniform4ui(), save_ProgramUniform4uiv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_ProvokingVertexEXT(), save_PushAttrib(), save_PushMatrix(), save_PushName(), save_QueryCounter(), save_RasterPos2d(), save_RasterPos2dv(), save_RasterPos2f(), save_RasterPos2fv(), save_RasterPos2i(), save_RasterPos2iv(), save_RasterPos2s(), save_RasterPos2sv(), save_RasterPos3d(), save_RasterPos3dv(), save_RasterPos3f(), save_RasterPos3fv(), save_RasterPos3i(), save_RasterPos3iv(), save_RasterPos3s(), save_RasterPos3sv(), save_RasterPos4d(), save_RasterPos4dv(), save_RasterPos4f(), save_RasterPos4fv(), save_RasterPos4i(), save_RasterPos4iv(), save_RasterPos4s(), save_RasterPos4sv(), save_ReadBuffer(), save_Rectf(), save_ResumeTransformFeedback(), save_Rotated(), save_Rotatef(), save_SampleCoverageARB(), save_SamplerParameterf(), save_SamplerParameterfv(), save_SamplerParameteri(), save_SamplerParameterIiv(), save_SamplerParameterIuiv(), save_SamplerParameteriv(), save_Scaled(), save_Scalef(), save_Scissor(), save_SetFragmentShaderConstantATI(), save_ShadeModel(), save_StencilFunc(), save_StencilFuncSeparate(), save_StencilFuncSeparateATI(), save_StencilMask(), save_StencilMaskSeparate(), save_StencilOp(), save_StencilOpSeparate(), save_TexEnvf(), save_TexEnvfv(), save_TexEnvi(), save_TexEnviv(), save_TexGend(), save_TexGendv(), save_TexGenf(), save_TexGenfv(), save_TexGeni(), save_TexGeniv(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexParameterf(), save_TexParameterfv(), save_TexParameteri(), save_TexParameterIiv(), save_TexParameterIuiv(), save_TexParameteriv(), save_TexSubImage1D(), save_TexSubImage2D(), save_TexSubImage3D(), save_TextureBarrierNV(), save_Translated(), save_Translatef(), save_Uniform1fARB(), save_Uniform1fvARB(), save_Uniform1iARB(), save_Uniform1ivARB(), save_Uniform1ui(), save_Uniform1uiv(), save_Uniform2fARB(), save_Uniform2fvARB(), save_Uniform2iARB(), save_Uniform2ivARB(), save_Uniform2ui(), save_Uniform2uiv(), save_Uniform3fARB(), save_Uniform3fvARB(), save_Uniform3iARB(), save_Uniform3ivARB(), save_Uniform3ui(), save_Uniform3uiv(), save_Uniform4fARB(), save_Uniform4fvARB(), save_Uniform4iARB(), save_Uniform4ivARB(), save_Uniform4ui(), save_Uniform4uiv(), save_UniformBlockBinding(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), save_UseProgram(), save_UseProgramStages(), save_VertexAttribDivisor(), save_Viewport(), save_WaitSync(), save_WindowPos2dMESA(), save_WindowPos2dvMESA(), save_WindowPos2fMESA(), save_WindowPos2fvMESA(), save_WindowPos2iMESA(), save_WindowPos2ivMESA(), save_WindowPos2sMESA(), save_WindowPos2svMESA(), save_WindowPos3dMESA(), save_WindowPos3dvMESA(), save_WindowPos3fMESA(), save_WindowPos3fvMESA(), save_WindowPos3iMESA(), save_WindowPos3ivMESA(), save_WindowPos3sMESA(), save_WindowPos3svMESA(), save_WindowPos4dMESA(), save_WindowPos4dvMESA(), save_WindowPos4fMESA(), save_WindowPos4fvMESA(), save_WindowPos4iMESA(), save_WindowPos4ivMESA(), save_WindowPos4sMESA(), save_WindowPos4svMESA(), save_WindowRectanglesEXT(), vbo_initialize_save_dispatch(), and void.
Referenced by _mesa_initialize_dispatch_tables().
_mesa_install_dlist_vtxfmt()
void _mesa_install_dlist_vtxfmt (struct _glapi_table * disp, const GLvertexformat * vfmt)
Referenced by install_vtxfmt().
_mesa_IsList()
GLboolean GLAPIENTRY _mesa_IsList (GLuint list)
Test if a display list number is valid.
References ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and islist().
_mesa_ListBase()
void GLAPIENTRY _mesa_ListBase (GLuint base)
Set the offset added to list numbers in glCallLists.
References ASSERT_OUTSIDE_BEGIN_END, FLUSH_VERTICES, GET_CURRENT_CONTEXT, gl_context::List, and gl_list_attrib::ListBase.
_mesa_lookup_list()
struct gl_display_list* _mesa_lookup_list (struct gl_context * ctx, GLuint list)
Lookup function to just encapsulate casting.
References _mesa_HashLookup(), gl_shared_state::DisplayList, and gl_context::Shared.
Referenced by build_bitmap_atlas(), destroy_list(), execute_list(), get_label_pointer(), islist(), and print_list().
_mesa_NewList()
void GLAPIENTRY _mesa_NewList (GLuint name, GLenum mode)
Begin a new display list.
References _glapi_set_dispatch(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), ASSERT_OUTSIDE_BEGIN_END, BLOCK_SIZE, gl_context::CompileFlag, gl_dlist_state::CurrentBlock, gl_context::CurrentClientDispatch, gl_dlist_state::CurrentList, gl_dlist_state::CurrentPos, gl_context::CurrentServerDispatch, gl_context::ExecuteFlag, FLUSH_CURRENT, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_display_list::Head, invalidate_saved_current_state(), gl_context::ListState, make_list(), gl_context::MarshalExec, MESA_VERBOSE, gl_context::Save, vbo_save_NewList(), and VERBOSE_API.
alloc_bitmap_atlas()
static struct gl_bitmap_atlas* alloc_bitmap_atlas (struct gl_context * ctx, GLuint listBase) static
Create new bitmap atlas and insert into hash table.
References _mesa_HashInsert(), _mesa_HashLookup(), gl_shared_state::BitmapAtlas, and gl_context::Shared.
Referenced by _mesa_GenLists(), and render_bitmap_atlas().
alloc_instruction()
static Node* alloc_instruction (struct gl_context * ctx, OpCode opcode, GLuint nparams) inline static
Allocate space for a display list instruction.
The space is basically an array of Nodes where node[0] holds the opcode, node[1] is the first function parameter, node[2] is the second parameter, etc.
Parameters
opcode one of OPCODE_x
nparams number of function parameters
Returns
pointer to start of instruction space
References dlist_alloc().
Referenced by _mesa_EndList(), save_Accum(), save_ActiveStencilFaceEXT(), save_ActiveTextureARB(), save_AlphaFunc(), save_Attr1fARB(), save_Attr1fNV(), save_Attr2fARB(), save_Attr2fNV(), save_Attr3fARB(), save_Attr3fNV(), save_Attr4fARB(), save_Attr4fNV(), save_Begin(), save_BeginConditionalRender(), save_BeginQueryARB(), save_BeginQueryIndexed(), save_BeginTransformFeedback(), save_BindFragmentShaderATI(), save_BindProgramARB(), save_BindSampler(), save_BindTexture(), save_BindTransformFeedback(), save_Bitmap(), save_BlendColor(), save_BlendEquation(), save_BlendEquationi(), save_BlendEquationSeparateEXT(), save_BlendEquationSeparatei(), save_BlendFunci(), save_BlendFuncSeparateEXT(), save_BlendFuncSeparatei(), save_BlitFramebufferEXT(), save_CallList(), save_CallLists(), save_ClampColorARB(), save_Clear(), save_ClearAccum(), save_ClearBufferfi(), save_ClearBufferfv(), save_ClearBufferiv(), save_ClearBufferuiv(), save_ClearColor(), save_ClearColorIi(), save_ClearColorIui(), save_ClearDepth(), save_ClearIndex(), save_ClearStencil(), save_ClipControl(), save_ClipPlane(), save_ColorMask(), save_ColorMaskIndexed(), save_ColorMaterial(), save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), save_CompressedTexSubImage3DARB(), save_CopyPixels(), save_CopyTexImage1D(), save_CopyTexImage2D(), save_CopyTexSubImage1D(), save_CopyTexSubImage2D(), save_CopyTexSubImage3D(), save_CullFace(), save_DepthBoundsEXT(), save_DepthFunc(), save_DepthMask(), save_DepthRange(), save_Disable(), save_DisableIndexed(), save_DrawBuffer(), save_DrawBuffersARB(), save_DrawPixels(), save_DrawTransformFeedback(), save_DrawTransformFeedbackInstanced(), save_DrawTransformFeedbackStream(), save_DrawTransformFeedbackStreamInstanced(), save_Enable(), save_EnableIndexed(), save_End(), save_EndConditionalRender(), save_EndQueryARB(), save_EndQueryIndexed(), save_EndTransformFeedback(), save_error(), save_EvalCoord1f(), save_EvalCoord2f(), save_EvalMesh1(), save_EvalMesh2(), save_EvalPoint1(), save_EvalPoint2(), save_Fogfv(), save_FrontFace(), save_Frustum(), save_Hint(), save_IndexMask(), save_InitNames(), save_Lightfv(), save_LightModelfv(), save_LineStipple(), save_LineWidth(), save_ListBase(), save_LoadIdentity(), save_LoadMatrixf(), save_LoadName(), save_LogicOp(), save_Map1d(), save_Map1f(), save_Map2d(), save_Map2f(), save_MapGrid1f(), save_MapGrid2f(), save_Materialfv(), save_MatrixMode(), save_MultMatrixf(), save_Ortho(), save_PassThrough(), save_PauseTransformFeedback(), save_PixelMapfv(), save_PixelTransferf(), save_PixelZoom(), save_PointParameterfvEXT(), save_PointSize(), save_PolygonMode(), save_PolygonOffset(), save_PolygonOffsetClampEXT(), save_PolygonStipple(), save_PopAttrib(), save_PopMatrix(), save_PopName(), save_PrioritizeTextures(), save_ProgramEnvParameter4fARB(), save_ProgramEnvParameters4fvEXT(), save_ProgramLocalParameter4dARB(), save_ProgramLocalParameter4dvARB(), save_ProgramLocalParameter4fARB(), save_ProgramLocalParameter4fvARB(), save_ProgramLocalParameters4fvEXT(), save_ProgramStringARB(), save_ProgramUniform1f(), save_ProgramUniform1fv(), save_ProgramUniform1i(), save_ProgramUniform1iv(), save_ProgramUniform1ui(), save_ProgramUniform1uiv(), save_ProgramUniform2f(), save_ProgramUniform2fv(), save_ProgramUniform2i(), save_ProgramUniform2iv(), save_ProgramUniform2ui(), save_ProgramUniform2uiv(), save_ProgramUniform3f(), save_ProgramUniform3fv(), save_ProgramUniform3i(), save_ProgramUniform3iv(), save_ProgramUniform3ui(), save_ProgramUniform3uiv(), save_ProgramUniform4f(), save_ProgramUniform4fv(), save_ProgramUniform4i(), save_ProgramUniform4iv(), save_ProgramUniform4ui(), save_ProgramUniform4uiv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_ProvokingVertexEXT(), save_PushAttrib(), save_PushMatrix(), save_PushName(), save_QueryCounter(), save_RasterPos4f(), save_ReadBuffer(), save_Rectf(), save_ResumeTransformFeedback(), save_Rotatef(), save_SampleCoverageARB(), save_SamplerParameterfv(), save_SamplerParameterIiv(), save_SamplerParameterIuiv(), save_SamplerParameteriv(), save_Scalef(), save_Scissor(), save_SetFragmentShaderConstantATI(), save_ShadeModel(), save_StencilFunc(), save_StencilFuncSeparate(), save_StencilFuncSeparateATI(), save_StencilMask(), save_StencilMaskSeparate(), save_StencilOp(), save_StencilOpSeparate(), save_TexEnvfv(), save_TexGenfv(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexParameterfv(), save_TexParameterIiv(), save_TexParameterIuiv(), save_TexSubImage1D(), save_TexSubImage2D(), save_TexSubImage3D(), save_TextureBarrierNV(), save_Translatef(), save_Uniform1fARB(), save_Uniform1fvARB(), save_Uniform1iARB(), save_Uniform1ivARB(), save_Uniform1ui(), save_Uniform1uiv(), save_Uniform2fARB(), save_Uniform2fvARB(), save_Uniform2iARB(), save_Uniform2ivARB(), save_Uniform2ui(), save_Uniform2uiv(), save_Uniform3fARB(), save_Uniform3fvARB(), save_Uniform3iARB(), save_Uniform3ivARB(), save_Uniform3ui(), save_Uniform3uiv(), save_Uniform4fARB(), save_Uniform4fvARB(), save_Uniform4iARB(), save_Uniform4ivARB(), save_Uniform4ui(), save_Uniform4uiv(), save_UniformBlockBinding(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), save_UseProgram(), save_UseProgramStages(), save_VertexAttribDivisor(), save_Viewport(), save_WaitSync(), save_WindowPos4fMESA(), and save_WindowRectanglesEXT().
build_bitmap_atlas()
static void build_bitmap_atlas (struct gl_context * ctx, struct gl_bitmap_atlas * atlas, GLuint listBase) static
Try to build a bitmap atlas.
This involves examining a sequence of display lists which contain glBitmap commands and putting the bitmap images into a texture map (the atlas). If we succeed, gl_bitmap_atlas::complete will be set to true. If we fail, gl_bitmap_atlas::incomplete will be set to true.
References _mesa_error(), _mesa_expand_bitmap(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_lookup_list(), dd_function_table::AllocTextureImageBuffer, gl_bitmap_atlas::complete, gl_context::Const, gl_context::DefaultPacking, dd_function_table::DeleteTexture, gl_context::Driver, gl_context::Extensions, gl_dlist_node::f, get_pointer(), gl_bitmap_atlas::glyphs, gl_bitmap_glyph::h, gl_display_list::Head, gl_dlist_node::i, gl_texture_object::Immutable, gl_bitmap_atlas::incomplete, is_bitmap_list(), is_empty_list(), gl_sampler_object::MagFilter, dd_function_table::MapTextureImage, gl_texture_object::MaxLevel, gl_constants::MaxTextureRectSize, MESA_FORMAT_A_UNORM8, gl_sampler_object::MinFilter, dd_function_table::NewTextureObject, gl_bitmap_atlas::numBitmaps, gl_extensions::NV_texture_rectangle, OPCODE_BITMAP, OPCODE_END_OF_LIST, out_of_memory, gl_texture_object::Sampler, gl_bitmap_atlas::texHeight, gl_bitmap_atlas::texImage, gl_bitmap_atlas::texObj, gl_bitmap_atlas::texWidth, dd_function_table::UnmapTextureImage, gl_bitmap_glyph::w, gl_bitmap_glyph::x, gl_bitmap_glyph::xmove, gl_bitmap_glyph::xorig, gl_bitmap_glyph::y, gl_bitmap_glyph::ymove, and gl_bitmap_glyph::yorig.
Referenced by render_bitmap_atlas().
check_atlas_for_deleted_list()
static void check_atlas_for_deleted_list (GLuint atlas_id, void * data, void * userData) static
Called by _mesa_HashWalk() to check if a display list which is being deleted belongs to a bitmap texture atlas.
References gl_bitmap_atlas::complete, GLuint, gl_bitmap_atlas::incomplete, and gl_bitmap_atlas::numBitmaps.
Referenced by destroy_list().
compare_vec()
static GLboolean compare_vec (const GLfloat * a, const GLfloat * b, GLuint count) inline static
Compare 'count' elements of vectors 'a' and 'b'.
Returns
GL_TRUE if equal, GL_FALSE if different.
References GLAPIENTRY.
Referenced by save_Materialfv().
copy_data()
static GLvoid* copy_data (const GLvoid * data, GLsizei size, const char * func) static
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), and save_CompressedTexSubImage3DARB().
destroy_list()
static void destroy_list (struct gl_context * ctx, GLuint list) static
Destroy a display list and remove from hash table.
Parameters
list - display list number
References _mesa_delete_list(), _mesa_HashRemove(), _mesa_HashWalk(), _mesa_lookup_list(), gl_shared_state::BitmapAtlas, check_atlas_for_deleted_list(), gl_shared_state::DisplayList, is_bitmap_list(), and gl_context::Shared.
Referenced by _mesa_DeleteLists(), and _mesa_EndList().
dlist_alloc()
static Node* dlist_alloc (struct gl_context * ctx, OpCode opcode, GLuint bytes, bool align8) static
Allocate space for a display list instruction (opcode + payload space).
Parameters
opcode the instruction opcode (OPCODE_* value)
bytes instruction payload size (not counting opcode)
align8 does the payload need to be 8-byte aligned? This is only relevant in 64-bit environments.
Returns
pointer to allocated memory (the payload will be at pointer+1)
References _mesa_error(), BLOCK_SIZE, gl_dlist_state::CurrentBlock, gl_dlist_state::CurrentPos, GLuint, InstSize, gl_context::ListState, gl_dlist_node::opcode, OPCODE_CONTINUE, OPCODE_EXT_0, OPCODE_NOP, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_dlist_alloc(), _mesa_dlist_alloc_aligned(), and alloc_instruction().
enum_string()
static const char* enum_string (GLenum k) static
References _mesa_enum_to_string(), and GLAPIENTRY.
Referenced by print_list().
execute_list()
static void execute_list (struct gl_context * ctx, GLuint list) static
References _mesa_error(), _mesa_evaluator_components(), _mesa_lookup_list(), _mesa_problem(), _mesa_snprintf(), bf, gl_dlist_node::bf, gl_dlist_state::CallDepth, gl_context::DefaultPacking, gl_dlist_node::e, gl_context::Exec, ext_opcode_execute(), gl_dlist_node::f, get_pointer(), GLAPIENTRY, GLuint, gl_display_list::Head, gl_dlist_node::i, InstSize, is_ext_opcode(), islist(), gl_context::ListState, MAX_DRAW_BUFFERS, MAX_LIST_NESTING, gl_dlist_node::opcode, OPCODE_ACCUM, OPCODE_ACTIVE_STENCIL_FACE_EXT, OPCODE_ACTIVE_TEXTURE, OPCODE_ALPHA_FUNC, OPCODE_ATTR_1F_ARB, OPCODE_ATTR_1F_NV, OPCODE_ATTR_2F_ARB, OPCODE_ATTR_2F_NV, OPCODE_ATTR_3F_ARB, OPCODE_ATTR_3F_NV, OPCODE_ATTR_4F_ARB, OPCODE_ATTR_4F_NV, OPCODE_BEGIN, OPCODE_BEGIN_CONDITIONAL_RENDER, OPCODE_BEGIN_QUERY_ARB, OPCODE_BEGIN_QUERY_INDEXED, OPCODE_BEGIN_TRANSFORM_FEEDBACK, OPCODE_BIND_FRAGMENT_SHADER_ATI, OPCODE_BIND_PROGRAM_ARB, OPCODE_BIND_SAMPLER, OPCODE_BIND_TEXTURE, OPCODE_BIND_TRANSFORM_FEEDBACK, OPCODE_BITMAP, OPCODE_BLEND_COLOR, OPCODE_BLEND_EQUATION, OPCODE_BLEND_EQUATION_I, OPCODE_BLEND_EQUATION_SEPARATE, OPCODE_BLEND_EQUATION_SEPARATE_I, OPCODE_BLEND_FUNC_I, OPCODE_BLEND_FUNC_SEPARATE, OPCODE_BLEND_FUNC_SEPARATE_I, OPCODE_BLIT_FRAMEBUFFER, OPCODE_CALL_LIST, OPCODE_CALL_LISTS, OPCODE_CLAMP_COLOR, OPCODE_CLEAR, OPCODE_CLEAR_ACCUM, OPCODE_CLEAR_BUFFER_FI, OPCODE_CLEAR_BUFFER_FV, OPCODE_CLEAR_BUFFER_IV, OPCODE_CLEAR_BUFFER_UIV, OPCODE_CLEAR_COLOR, OPCODE_CLEAR_DEPTH, OPCODE_CLEAR_INDEX, OPCODE_CLEAR_STENCIL, OPCODE_CLEARCOLOR_I, OPCODE_CLEARCOLOR_UI, OPCODE_CLIP_CONTROL, OPCODE_CLIP_PLANE, OPCODE_COLOR_MASK, OPCODE_COLOR_MASK_INDEXED, OPCODE_COLOR_MATERIAL, OPCODE_COMPRESSED_TEX_IMAGE_1D, OPCODE_COMPRESSED_TEX_IMAGE_2D, OPCODE_COMPRESSED_TEX_IMAGE_3D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_1D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_2D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_3D, OPCODE_CONTINUE, OPCODE_COPY_PIXELS, OPCODE_COPY_TEX_IMAGE1D, OPCODE_COPY_TEX_IMAGE2D, OPCODE_COPY_TEX_SUB_IMAGE1D, OPCODE_COPY_TEX_SUB_IMAGE2D, OPCODE_COPY_TEX_SUB_IMAGE3D, OPCODE_CULL_FACE, OPCODE_DEPTH_BOUNDS_EXT, OPCODE_DEPTH_FUNC, OPCODE_DEPTH_MASK, OPCODE_DEPTH_RANGE, OPCODE_DISABLE, OPCODE_DISABLE_INDEXED, OPCODE_DRAW_BUFFER, OPCODE_DRAW_BUFFERS_ARB, OPCODE_DRAW_PIXELS, OPCODE_DRAW_TRANSFORM_FEEDBACK, OPCODE_DRAW_TRANSFORM_FEEDBACK_INSTANCED, OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM, OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM_INSTANCED, OPCODE_ENABLE, OPCODE_ENABLE_INDEXED, OPCODE_END, OPCODE_END_CONDITIONAL_RENDER, OPCODE_END_OF_LIST, OPCODE_END_QUERY_ARB, OPCODE_END_QUERY_INDEXED, OPCODE_END_TRANSFORM_FEEDBACK, OPCODE_ERROR, OPCODE_EVAL_C1, OPCODE_EVAL_C2, OPCODE_EVAL_P1, OPCODE_EVAL_P2, OPCODE_EVALMESH1, OPCODE_EVALMESH2, OPCODE_FOG, OPCODE_FRONT_FACE, OPCODE_FRUSTUM, OPCODE_HINT, OPCODE_INDEX_MASK, OPCODE_INIT_NAMES, OPCODE_LIGHT, OPCODE_LIGHT_MODEL, OPCODE_LINE_STIPPLE, OPCODE_LINE_WIDTH, OPCODE_LIST_BASE, OPCODE_LOAD_IDENTITY, OPCODE_LOAD_MATRIX, OPCODE_LOAD_NAME, OPCODE_LOGIC_OP, OPCODE_MAP1, OPCODE_MAP2, OPCODE_MAPGRID1, OPCODE_MAPGRID2, OPCODE_MATERIAL, OPCODE_MATRIX_MODE, OPCODE_MULT_MATRIX, OPCODE_NOP, OPCODE_ORTHO, OPCODE_PASSTHROUGH, OPCODE_PAUSE_TRANSFORM_FEEDBACK, OPCODE_PIXEL_MAP, OPCODE_PIXEL_TRANSFER, OPCODE_PIXEL_ZOOM, OPCODE_POINT_PARAMETERS, OPCODE_POINT_SIZE, OPCODE_POLYGON_MODE, OPCODE_POLYGON_OFFSET, OPCODE_POLYGON_OFFSET_CLAMP, OPCODE_POLYGON_STIPPLE, OPCODE_POP_ATTRIB, OPCODE_POP_MATRIX, OPCODE_POP_NAME, OPCODE_PRIORITIZE_TEXTURE, OPCODE_PROGRAM_ENV_PARAMETER_ARB, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, OPCODE_PROGRAM_STRING_ARB, OPCODE_PROGRAM_UNIFORM_1F, OPCODE_PROGRAM_UNIFORM_1FV, OPCODE_PROGRAM_UNIFORM_1I, OPCODE_PROGRAM_UNIFORM_1IV, OPCODE_PROGRAM_UNIFORM_1UI, OPCODE_PROGRAM_UNIFORM_1UIV, OPCODE_PROGRAM_UNIFORM_2F, OPCODE_PROGRAM_UNIFORM_2FV, OPCODE_PROGRAM_UNIFORM_2I, OPCODE_PROGRAM_UNIFORM_2IV, OPCODE_PROGRAM_UNIFORM_2UI, OPCODE_PROGRAM_UNIFORM_2UIV, OPCODE_PROGRAM_UNIFORM_3F, OPCODE_PROGRAM_UNIFORM_3FV, OPCODE_PROGRAM_UNIFORM_3I, OPCODE_PROGRAM_UNIFORM_3IV, OPCODE_PROGRAM_UNIFORM_3UI, OPCODE_PROGRAM_UNIFORM_3UIV, OPCODE_PROGRAM_UNIFORM_4F, OPCODE_PROGRAM_UNIFORM_4FV, OPCODE_PROGRAM_UNIFORM_4I, OPCODE_PROGRAM_UNIFORM_4IV, OPCODE_PROGRAM_UNIFORM_4UI, OPCODE_PROGRAM_UNIFORM_4UIV, OPCODE_PROGRAM_UNIFORM_MATRIX22F, OPCODE_PROGRAM_UNIFORM_MATRIX23F, OPCODE_PROGRAM_UNIFORM_MATRIX24F, OPCODE_PROGRAM_UNIFORM_MATRIX32F, OPCODE_PROGRAM_UNIFORM_MATRIX33F, OPCODE_PROGRAM_UNIFORM_MATRIX34F, OPCODE_PROGRAM_UNIFORM_MATRIX42F, OPCODE_PROGRAM_UNIFORM_MATRIX43F, OPCODE_PROGRAM_UNIFORM_MATRIX44F, OPCODE_PROVOKING_VERTEX, OPCODE_PUSH_ATTRIB, OPCODE_PUSH_MATRIX, OPCODE_PUSH_NAME, OPCODE_QUERY_COUNTER, OPCODE_RASTER_POS, OPCODE_READ_BUFFER, OPCODE_RECTF, OPCODE_RESUME_TRANSFORM_FEEDBACK, OPCODE_ROTATE, OPCODE_SAMPLE_COVERAGE, OPCODE_SAMPLER_PARAMETERFV, OPCODE_SAMPLER_PARAMETERIIV, OPCODE_SAMPLER_PARAMETERIV, OPCODE_SAMPLER_PARAMETERUIV, OPCODE_SCALE, OPCODE_SCISSOR, OPCODE_SET_FRAGMENT_SHADER_CONSTANTS_ATI, OPCODE_SHADE_MODEL, OPCODE_STENCIL_FUNC, OPCODE_STENCIL_FUNC_SEPARATE, OPCODE_STENCIL_MASK, OPCODE_STENCIL_MASK_SEPARATE, OPCODE_STENCIL_OP, OPCODE_STENCIL_OP_SEPARATE, OPCODE_TEX_IMAGE1D, OPCODE_TEX_IMAGE2D, OPCODE_TEX_IMAGE3D, OPCODE_TEX_SUB_IMAGE1D, OPCODE_TEX_SUB_IMAGE2D, OPCODE_TEX_SUB_IMAGE3D, OPCODE_TEXENV, OPCODE_TEXGEN, OPCODE_TEXPARAMETER, OPCODE_TEXPARAMETER_I, OPCODE_TEXPARAMETER_UI, OPCODE_TEXTURE_BARRIER_NV, OPCODE_TRANSLATE, OPCODE_UNIFORM_1F, OPCODE_UNIFORM_1FV, OPCODE_UNIFORM_1I, OPCODE_UNIFORM_1IV, OPCODE_UNIFORM_1UI, OPCODE_UNIFORM_1UIV, OPCODE_UNIFORM_2F, OPCODE_UNIFORM_2FV, OPCODE_UNIFORM_2I, OPCODE_UNIFORM_2IV, OPCODE_UNIFORM_2UI, OPCODE_UNIFORM_2UIV, OPCODE_UNIFORM_3F, OPCODE_UNIFORM_3FV, OPCODE_UNIFORM_3I, OPCODE_UNIFORM_3IV, OPCODE_UNIFORM_3UI, OPCODE_UNIFORM_3UIV, OPCODE_UNIFORM_4F, OPCODE_UNIFORM_4FV, OPCODE_UNIFORM_4I, OPCODE_UNIFORM_4IV, OPCODE_UNIFORM_4UI, OPCODE_UNIFORM_4UIV, OPCODE_UNIFORM_BLOCK_BINDING, OPCODE_UNIFORM_MATRIX22, OPCODE_UNIFORM_MATRIX23, OPCODE_UNIFORM_MATRIX24, OPCODE_UNIFORM_MATRIX32, OPCODE_UNIFORM_MATRIX33, OPCODE_UNIFORM_MATRIX34, OPCODE_UNIFORM_MATRIX42, OPCODE_UNIFORM_MATRIX43, OPCODE_UNIFORM_MATRIX44, OPCODE_USE_PROGRAM, OPCODE_USE_PROGRAM_STAGES, OPCODE_VERTEX_ATTRIB_DIVISOR, OPCODE_VIEWPORT, OPCODE_WAIT_SYNC, OPCODE_WINDOW_POS, OPCODE_WINDOW_POS_ARB, OPCODE_WINDOW_RECTANGLES, gl_dlist_node::ui, uint64_pair::uint32, uint64_pair::uint64, gl_context::Unpack, vbo_save_BeginCallList(), and vbo_save_EndCallList().
Referenced by _mesa_CallList(), and _mesa_CallLists().
ext_opcode_destroy()
static GLint ext_opcode_destroy (struct gl_context * ctx, Node * node) static
Destroy an extended opcode instruction.
References gl_list_instruction::Destroy, gl_context::ListExt, gl_list_extensions::Opcode, gl_dlist_node::opcode, OPCODE_EXT_0, and gl_list_instruction::Size.
Referenced by _mesa_delete_list().
ext_opcode_execute()
static GLint ext_opcode_execute (struct gl_context * ctx, Node * node) static
Execute an extended opcode instruction.
References gl_list_instruction::Execute, gl_context::ListExt, gl_list_extensions::Opcode, gl_dlist_node::opcode, OPCODE_EXT_0, and gl_list_instruction::Size.
Referenced by execute_list().
ext_opcode_print()
static GLint ext_opcode_print (struct gl_context * ctx, Node * node, FILE * f) static
Print an extended opcode instruction.
References gl_context::ListExt, gl_list_extensions::Opcode, gl_dlist_node::opcode, OPCODE_EXT_0, gl_list_instruction::Print, and gl_list_instruction::Size.
Referenced by print_list().
get_pointer()
static void* get_pointer (const Node * node) inline static
Retrieve a 4 or 8-byte pointer from node (node+1).
References pointer::dwords, POINTER_DWORDS, pointer::ptr, and gl_dlist_node::ui.
Referenced by _mesa_delete_list(), build_bitmap_atlas(), execute_list(), and print_list().
index_error()
static void index_error (void) static
Record a GL_INVALID_VALUE error when an invalid vertex attribute index is found.
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by save_VertexAttrib1fARB(), save_VertexAttrib1fvARB(), save_VertexAttrib2fARB(), save_VertexAttrib2fvARB(), save_VertexAttrib3fARB(), save_VertexAttrib3fvARB(), save_VertexAttrib4fARB(), and save_VertexAttrib4fvARB().
invalidate_saved_current_state()
static void invalidate_saved_current_state (struct gl_context * ctx) static
While building a display list we cache some OpenGL state.
Under some circumstances we need to invalidate that state (immediately when we start compiling a list, or after glCallList(s)).
References gl_dlist_state::ActiveAttribSize, gl_dlist_state::ActiveMaterialSize, gl_dlist_state::Current, dd_function_table::CurrentSavePrimitive, gl_context::Driver, for(), GLAPIENTRY, gl_context::ListState, MAT_ATTRIB_MAX, and PRIM_UNKNOWN.
Referenced by _mesa_NewList(), save_CallList(), and save_CallLists().
is_bitmap_list()
static bool is_bitmap_list (const struct gl_display_list * dlist) static
Does the given display list only contain a single glBitmap call?
References gl_display_list::Head, InstSize, OPCODE_BITMAP, and OPCODE_END_OF_LIST.
Referenced by build_bitmap_atlas(), and destroy_list().
is_empty_list()
static bool is_empty_list (const struct gl_display_list * dlist) static
Is the given display list an empty list?
References gl_display_list::Head, gl_dlist_node::opcode, and OPCODE_END_OF_LIST.
Referenced by build_bitmap_atlas().
is_ext_opcode()
static GLboolean is_ext_opcode (OpCode opcode) inline static
Is the given opcode an extension code?
References OPCODE_EXT_0.
Referenced by _mesa_delete_list(), execute_list(), and print_list().
islist()
static GLboolean islist (struct gl_context * ctx, GLuint list) static
Test if ID names a display list.
References _mesa_lookup_list().
Referenced by _mesa_IsList(), execute_list(), and print_list().
lookup_bitmap_atlas()
static struct gl_bitmap_atlas* lookup_bitmap_atlas (struct gl_context * ctx, GLuint listBase) static
Lookup a gl_bitmap_atlas by listBase ID.
References _mesa_HashLookup(), gl_shared_state::BitmapAtlas, and gl_context::Shared.
Referenced by _mesa_DeleteLists(), _mesa_GenLists(), and render_bitmap_atlas().
make_list()
static struct gl_display_list* make_list (GLuint name, GLuint count) static
Allocate a gl_display_list object with an initial block of storage.
Parameters
count how many display list nodes/tokens to allocate
References CALLOC_STRUCT, gl_display_list::Head, gl_display_list::Name, gl_dlist_node::opcode, and OPCODE_END_OF_LIST.
Referenced by _mesa_GenLists(), and _mesa_NewList().
memdup()
static void* memdup (const void * src, GLsizei bytes) static
Return copy of memory.
Referenced by save_CallLists(), save_PixelMapfv(), save_ProgramUniform1fv(), save_ProgramUniform1iv(), save_ProgramUniform1uiv(), save_ProgramUniform2fv(), save_ProgramUniform2iv(), save_ProgramUniform2uiv(), save_ProgramUniform3fv(), save_ProgramUniform3iv(), save_ProgramUniform3uiv(), save_ProgramUniform4fv(), save_ProgramUniform4iv(), save_ProgramUniform4uiv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_Uniform1fvARB(), save_Uniform1ivARB(), save_Uniform1uiv(), save_Uniform2fvARB(), save_Uniform2ivARB(), save_Uniform2uiv(), save_Uniform3fvARB(), save_Uniform3ivARB(), save_Uniform3uiv(), save_Uniform4fvARB(), save_Uniform4ivARB(), save_Uniform4uiv(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), and save_WindowRectanglesEXT().
mesa_print_display_list()
void mesa_print_display_list (GLuint list)
Clients may call this function to help debug display list problems.
This function is ONLY_FOR_DEBUGGING_PURPOSES. It may be removed, changed, or break in the future without notice.
References GET_CURRENT_CONTEXT, and print_list().
Referenced by _mesa_CallList(), and _mesa_EndList().
print_list()
static void GLAPIENTRY print_list (struct gl_context * ctx, GLuint list, const char * fname) static
Print the commands in a display list.
For debugging only. TODO: many commands aren't handled yet.
Parameters
fname filename to write display list to. If null, use stdout.
References _mesa_enum_to_string(), _mesa_lookup_list(), bf, enum_string(), ext_opcode_print(), get_pointer(), gl_display_list::Head, InstSize, is_ext_opcode(), islist(), gl_dlist_node::opcode, OPCODE_ACCUM, OPCODE_ACTIVE_TEXTURE, OPCODE_ATTR_1F_ARB, OPCODE_ATTR_1F_NV, OPCODE_ATTR_2F_ARB, OPCODE_ATTR_2F_NV, OPCODE_ATTR_3F_ARB, OPCODE_ATTR_3F_NV, OPCODE_ATTR_4F_ARB, OPCODE_ATTR_4F_NV, OPCODE_BEGIN, OPCODE_BIND_TEXTURE, OPCODE_BITMAP, OPCODE_BLEND_COLOR, OPCODE_BLEND_EQUATION, OPCODE_BLEND_EQUATION_I, OPCODE_BLEND_EQUATION_SEPARATE, OPCODE_BLEND_EQUATION_SEPARATE_I, OPCODE_BLEND_FUNC_I, OPCODE_BLEND_FUNC_SEPARATE, OPCODE_BLEND_FUNC_SEPARATE_I, OPCODE_CALL_LIST, OPCODE_CALL_LISTS, OPCODE_CONTINUE, OPCODE_DISABLE, OPCODE_ENABLE, OPCODE_END, OPCODE_END_OF_LIST, OPCODE_ERROR, OPCODE_EVAL_C1, OPCODE_EVAL_C2, OPCODE_EVAL_P1, OPCODE_EVAL_P2, OPCODE_EVALMESH1, OPCODE_EVALMESH2, OPCODE_FRUSTUM, OPCODE_LINE_STIPPLE, OPCODE_LINE_WIDTH, OPCODE_LOAD_IDENTITY, OPCODE_LOAD_MATRIX, OPCODE_MAP1, OPCODE_MAP2, OPCODE_MAPGRID1, OPCODE_MAPGRID2, OPCODE_MATERIAL, OPCODE_MULT_MATRIX, OPCODE_NOP, OPCODE_ORTHO, OPCODE_POINT_SIZE, OPCODE_POP_ATTRIB, OPCODE_POP_MATRIX, OPCODE_POP_NAME, OPCODE_PROVOKING_VERTEX, OPCODE_PUSH_ATTRIB, OPCODE_PUSH_MATRIX, OPCODE_PUSH_NAME, OPCODE_RASTER_POS, OPCODE_RECTF, OPCODE_ROTATE, OPCODE_SCALE, OPCODE_SHADE_MODEL, and OPCODE_TRANSLATE.
Referenced by mesa_print_display_list().
render_bitmap_atlas()
static bool render_bitmap_atlas (struct gl_context * ctx, GLsizei n, GLenum type, const void * lists) static
Try to execute a glCallLists() command where the display lists contain glBitmap commands with a texture atlas.
Returns
true for success, false otherwise
References alloc_bitmap_atlas(), build_bitmap_atlas(), gl_bitmap_atlas::complete, gl_context::Current, dd_function_table::DrawAtlasBitmaps, gl_context::Driver, GLAPIENTRY, gl_bitmap_atlas::incomplete, gl_context::List, gl_list_attrib::ListBase, lookup_bitmap_atlas(), gl_bitmap_atlas::numBitmaps, gl_current_attrib::RasterPosValid, and USE_BITMAP_ATLAS.
Referenced by _mesa_CallLists().
save_Accum()
static void GLAPIENTRY save_Accum (GLenum op, GLfloat value) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_ACCUM.
Referenced by _mesa_initialize_save_table().
save_ActiveStencilFaceEXT()
static void GLAPIENTRY save_ActiveStencilFaceEXT (GLenum face) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_ACTIVE_STENCIL_FACE_EXT.
Referenced by _mesa_initialize_save_table().
save_ActiveTextureARB()
static void GLAPIENTRY save_ActiveTextureARB (GLenum target) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_ACTIVE_TEXTURE.
Referenced by _mesa_initialize_save_table().
save_AlphaFunc()
static void GLAPIENTRY save_AlphaFunc (GLenum func, GLclampf ref) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_ALPHA_FUNC.
Referenced by _mesa_initialize_save_table().
save_Attr1fARB()
static void GLAPIENTRY save_Attr1fARB (GLenum attr, GLfloat x) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_1F_ARB, SAVE_FLUSH_VERTICES, and x.
Referenced by save_VertexAttrib1fARB(), and save_VertexAttrib1fvARB().
save_Attr1fNV()
static void GLAPIENTRY save_Attr1fNV (GLenum attr, GLfloat x) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_1F_NV, SAVE_FLUSH_VERTICES, and x.
Referenced by save_EdgeFlag(), save_FogCoordfEXT(), save_FogCoordfvEXT(), save_Indexf(), save_Indexfv(), save_MultiTexCoord1f(), save_MultiTexCoord1fv(), save_TexCoord1f(), and save_TexCoord1fv().
save_Attr2fARB()
static void GLAPIENTRY save_Attr2fARB (GLenum attr, GLfloat x, GLfloat y) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_2F_ARB, SAVE_FLUSH_VERTICES, and x.
Referenced by save_VertexAttrib2fARB(), and save_VertexAttrib2fvARB().
save_Attr2fNV()
static void GLAPIENTRY save_Attr2fNV (GLenum attr, GLfloat x, GLfloat y) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_2F_NV, SAVE_FLUSH_VERTICES, and x.
Referenced by save_MultiTexCoord2f(), save_MultiTexCoord2fv(), save_TexCoord2f(), save_TexCoord2fv(), save_Vertex2f(), and save_Vertex2fv().
save_Attr3fARB()
static void GLAPIENTRY save_Attr3fARB (GLenum attr, GLfloat x, GLfloat y, GLfloat z) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_3F_ARB, SAVE_FLUSH_VERTICES, and x.
Referenced by save_VertexAttrib3fARB(), and save_VertexAttrib3fvARB().
save_Attr3fNV()
static void GLAPIENTRY save_Attr3fNV (GLenum attr, GLfloat x, GLfloat y, GLfloat z) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_3F_NV, SAVE_FLUSH_VERTICES, and x.
Referenced by save_Color3f(), save_Color3fv(), save_MultiTexCoord3f(), save_MultiTexCoord3fv(), save_Normal3f(), save_Normal3fv(), save_SecondaryColor3fEXT(), save_SecondaryColor3fvEXT(), save_TexCoord3f(), save_TexCoord3fv(), save_Vertex3f(), and save_Vertex3fv().
save_Attr4fARB()
static void GLAPIENTRY save_Attr4fARB (GLenum attr, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_4F_ARB, SAVE_FLUSH_VERTICES, and x.
Referenced by save_VertexAttrib4fARB(), and save_VertexAttrib4fvARB().
save_Attr4fNV()
static void GLAPIENTRY save_Attr4fNV (GLenum attr, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References gl_dlist_state::ActiveAttribSize, alloc_instruction(), gl_dlist_state::CurrentAttrib, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, MAX_VERTEX_GENERIC_ATTRIBS, OPCODE_ATTR_4F_NV, SAVE_FLUSH_VERTICES, and x.
Referenced by save_Color4f(), save_Color4fv(), save_MultiTexCoord4f(), save_MultiTexCoord4fv(), save_TexCoord4f(), save_TexCoord4fv(), save_Vertex4f(), and save_Vertex4fv().
save_Begin()
static void GLAPIENTRY save_Begin (GLenum mode) static
References _mesa_compile_error(), _mesa_inside_dlist_begin_end(), _mesa_is_valid_prim_mode(), alloc_instruction(), dd_function_table::CurrentSavePrimitive, gl_context::Driver, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BEGIN, SAVE_FLUSH_VERTICES, and vbo_save_NotifyBegin().
Referenced by save_vtxfmt_init().
save_BeginConditionalRender()
static void GLAPIENTRY save_BeginConditionalRender (GLuint queryId, GLenum mode) static
GL_NV_conditional_render.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_BEGIN_CONDITIONAL_RENDER.
Referenced by _mesa_initialize_save_table().
save_BeginQueryARB()
static void GLAPIENTRY save_BeginQueryARB (GLenum target, GLuint id) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BEGIN_QUERY_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BeginQueryIndexed()
static void GLAPIENTRY save_BeginQueryIndexed (GLenum target, GLuint index, GLuint id) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BEGIN_QUERY_INDEXED, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BeginTransformFeedback()
static void GLAPIENTRY save_BeginTransformFeedback (GLenum mode) static
GL_EXT_transform_feedback.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_BEGIN_TRANSFORM_FEEDBACK.
Referenced by _mesa_initialize_save_table().
save_BindFragmentShaderATI()
static void GLAPIENTRY save_BindFragmentShaderATI (GLuint id) static
References alloc_instruction(), gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BIND_FRAGMENT_SHADER_ATI, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BindProgramARB()
static void GLAPIENTRY save_BindProgramARB (GLenum target, GLuint id) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BIND_PROGRAM_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BindSampler()
static void GLAPIENTRY save_BindSampler (GLuint unit, GLuint sampler) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BIND_SAMPLER, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BindTexture()
static void GLAPIENTRY save_BindTexture (GLenum target, GLuint texture) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BIND_TEXTURE, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BindTransformFeedback()
static void GLAPIENTRY save_BindTransformFeedback (GLenum target, GLuint name) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BIND_TRANSFORM_FEEDBACK, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_Bitmap()
static void GLAPIENTRY save_Bitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_BITMAP, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_BlendColor()
static void GLAPIENTRY save_BlendColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_BLEND_COLOR.
Referenced by _mesa_initialize_save_table().
save_BlendEquation()
static void GLAPIENTRY save_BlendEquation (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_BLEND_EQUATION.
Referenced by _mesa_initialize_save_table().
save_BlendEquationi()
static void GLAPIENTRY save_BlendEquationi (GLuint buf, GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BLEND_EQUATION_I, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BlendEquationSeparateEXT()
static void GLAPIENTRY save_BlendEquationSeparateEXT (GLenum modeRGB, GLenum modeA) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_BLEND_EQUATION_SEPARATE.
Referenced by _mesa_initialize_save_table().
save_BlendEquationSeparatei()
static void GLAPIENTRY save_BlendEquationSeparatei (GLuint buf, GLenum modeRGB, GLenum modeA) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BLEND_EQUATION_SEPARATE_I, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BlendFunc()
static void GLAPIENTRY save_BlendFunc (GLenum srcfactor, GLenum dstfactor) static
References GLAPIENTRY, and save_BlendFuncSeparateEXT().
Referenced by _mesa_initialize_save_table().
save_BlendFunci()
static void GLAPIENTRY save_BlendFunci (GLuint buf, GLenum sfactor, GLenum dfactor) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BLEND_FUNC_I, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BlendFuncSeparateEXT()
static void GLAPIENTRY save_BlendFuncSeparateEXT (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_BLEND_FUNC_SEPARATE.
Referenced by _mesa_initialize_save_table(), and save_BlendFunc().
save_BlendFuncSeparatei()
static void GLAPIENTRY save_BlendFuncSeparatei (GLuint buf, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_BLEND_FUNC_SEPARATE_I, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_BlitFramebufferEXT()
static void GLAPIENTRY save_BlitFramebufferEXT (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_BLIT_FRAMEBUFFER.
Referenced by _mesa_initialize_save_table().
save_CallList()
static void GLAPIENTRY save_CallList (GLuint list) static
References _mesa_CallList(), alloc_instruction(), gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, invalidate_saved_current_state(), OPCODE_CALL_LIST, SAVE_FLUSH_VERTICES, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table(), and save_vtxfmt_init().
save_CallLists()
static void GLAPIENTRY save_CallLists (GLsizei num, GLenum type, const GLvoid * lists) static
References alloc_instruction(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, invalidate_saved_current_state(), memdup(), OPCODE_CALL_LISTS, POINTER_DWORDS, SAVE_FLUSH_VERTICES, and save_pointer().
Referenced by _mesa_initialize_save_table(), and save_vtxfmt_init().
save_ClampColorARB()
static void GLAPIENTRY save_ClampColorARB (GLenum target, GLenum clamp) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLAMP_COLOR.
Referenced by _mesa_initialize_save_table().
save_Clear()
static void GLAPIENTRY save_Clear (GLbitfield mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::bf, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLEAR.
Referenced by _mesa_initialize_save_table().
save_ClearAccum()
static void GLAPIENTRY save_ClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLEAR_ACCUM.
Referenced by _mesa_initialize_save_table().
save_ClearBufferfi()
static void GLAPIENTRY save_ClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_CLEAR_BUFFER_FI.
Referenced by _mesa_initialize_save_table().
save_ClearBufferfv()
static void GLAPIENTRY save_ClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat * value) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_CLEAR_BUFFER_FV.
Referenced by _mesa_initialize_save_table().
save_ClearBufferiv()
static void GLAPIENTRY save_ClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint * value) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_CLEAR_BUFFER_IV.
Referenced by _mesa_initialize_save_table().
save_ClearBufferuiv()
static void GLAPIENTRY save_ClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint * value) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_CLEAR_BUFFER_UIV, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ClearColor()
static void GLAPIENTRY save_ClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLEAR_COLOR.
Referenced by _mesa_initialize_save_table().
save_ClearColorIi()
static void GLAPIENTRY save_ClearColorIi (GLint red, GLint green, GLint blue, GLint alpha) static
GL_EXT_texture_integer.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_CLEARCOLOR_I.
Referenced by _mesa_initialize_save_table().
save_ClearColorIui()
static void GLAPIENTRY save_ClearColorIui (GLuint red, GLuint green, GLuint blue, GLuint alpha) static
GL_EXT_texture_integer.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_CLEARCOLOR_UI, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ClearDepth()
static void GLAPIENTRY save_ClearDepth (GLclampd depth) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLEAR_DEPTH.
Referenced by _mesa_initialize_save_table().
save_ClearIndex()
static void GLAPIENTRY save_ClearIndex (GLfloat c) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLEAR_INDEX.
Referenced by _mesa_initialize_save_table().
save_ClearStencil()
static void GLAPIENTRY save_ClearStencil (GLint s) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_CLEAR_STENCIL.
Referenced by _mesa_initialize_save_table().
save_ClipControl()
static void GLAPIENTRY save_ClipControl (GLenum origin, GLenum depth) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLIP_CONTROL.
Referenced by _mesa_initialize_save_table().
save_ClipPlane()
static void GLAPIENTRY save_ClipPlane (GLenum plane, const GLdouble * equ) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CLIP_PLANE.
Referenced by _mesa_initialize_save_table().
save_Color3f()
static void GLAPIENTRY save_Color3f (GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_Color3fv()
static void GLAPIENTRY save_Color3fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_Color4f()
static void GLAPIENTRY save_Color4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References GLAPIENTRY, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_Color4fv()
static void GLAPIENTRY save_Color4fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_ColorMask()
static void GLAPIENTRY save_ColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_COLOR_MASK.
Referenced by _mesa_initialize_save_table().
save_ColorMaskIndexed()
static void GLAPIENTRY save_ColorMaskIndexed (GLuint buf, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_COLOR_MASK_INDEXED, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ColorMaterial()
static void GLAPIENTRY save_ColorMaterial (GLenum face, GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_COLOR_MATERIAL.
Referenced by _mesa_initialize_save_table().
save_CompressedTexImage1DARB()
static void GLAPIENTRY save_CompressedTexImage1DARB (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, copy_data(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COMPRESSED_TEX_IMAGE_1D, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_CompressedTexImage2DARB()
static void GLAPIENTRY save_CompressedTexImage2DARB (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, copy_data(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COMPRESSED_TEX_IMAGE_2D, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_CompressedTexImage3DARB()
static void GLAPIENTRY save_CompressedTexImage3DARB (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, copy_data(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COMPRESSED_TEX_IMAGE_3D, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_CompressedTexSubImage1DARB()
static void GLAPIENTRY save_CompressedTexSubImage1DARB (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, copy_data(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COMPRESSED_TEX_SUB_IMAGE_1D, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_CompressedTexSubImage2DARB()
static void GLAPIENTRY save_CompressedTexSubImage2DARB (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, copy_data(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COMPRESSED_TEX_SUB_IMAGE_2D, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_CompressedTexSubImage3DARB()
static void GLAPIENTRY save_CompressedTexSubImage3DARB (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, copy_data(), gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COMPRESSED_TEX_SUB_IMAGE_3D, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_CopyPixels()
static void GLAPIENTRY save_CopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COPY_PIXELS, and x.
Referenced by _mesa_initialize_save_table().
save_CopyTexImage1D()
static void GLAPIENTRY save_CopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COPY_TEX_IMAGE1D, and x.
Referenced by _mesa_initialize_save_table().
save_CopyTexImage2D()
static void GLAPIENTRY save_CopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COPY_TEX_IMAGE2D, and x.
Referenced by _mesa_initialize_save_table().
save_CopyTexSubImage1D()
static void GLAPIENTRY save_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COPY_TEX_SUB_IMAGE1D, and x.
Referenced by _mesa_initialize_save_table().
save_CopyTexSubImage2D()
static void GLAPIENTRY save_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLint height) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COPY_TEX_SUB_IMAGE2D, and x.
Referenced by _mesa_initialize_save_table().
save_CopyTexSubImage3D()
static void GLAPIENTRY save_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLint height) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_COPY_TEX_SUB_IMAGE3D, and x.
Referenced by _mesa_initialize_save_table().
save_CullFace()
static void GLAPIENTRY save_CullFace (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_CULL_FACE.
Referenced by _mesa_initialize_save_table().
save_DepthBoundsEXT()
static void GLAPIENTRY save_DepthBoundsEXT (GLclampd zmin, GLclampd zmax) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_DEPTH_BOUNDS_EXT.
Referenced by _mesa_initialize_save_table().
save_DepthFunc()
static void GLAPIENTRY save_DepthFunc (GLenum func) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_DEPTH_FUNC.
Referenced by _mesa_initialize_save_table().
save_DepthMask()
static void GLAPIENTRY save_DepthMask (GLboolean mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_DEPTH_MASK.
Referenced by _mesa_initialize_save_table().
save_DepthRange()
static void GLAPIENTRY save_DepthRange (GLclampd nearval, GLclampd farval) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_DEPTH_RANGE.
Referenced by _mesa_initialize_save_table().
save_Disable()
static void GLAPIENTRY save_Disable (GLenum cap) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_DISABLE.
Referenced by _mesa_initialize_save_table().
save_DisableIndexed()
static void GLAPIENTRY save_DisableIndexed (GLuint index, GLenum cap) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_DISABLE_INDEXED, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_DrawArraysInstancedARB()
static void GLAPIENTRY save_DrawArraysInstancedARB (UNUSED GLenum mode, UNUSED GLint first, UNUSED GLsizei count, UNUSED GLsizei primcount) static
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_initialize_save_table().
save_DrawArraysInstancedBaseInstance()
static void GLAPIENTRY save_DrawArraysInstancedBaseInstance (UNUSED GLenum mode, UNUSED GLint first, UNUSED GLsizei count, UNUSED GLsizei primcount, UNUSED GLuint baseinstance) static
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_initialize_save_table().
save_DrawBuffer()
static void GLAPIENTRY save_DrawBuffer (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_DRAW_BUFFER.
Referenced by _mesa_initialize_save_table().
save_DrawBuffersARB()
static void GLAPIENTRY save_DrawBuffersARB (GLsizei count, const GLenum * buffers) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, MAX_DRAW_BUFFERS, and OPCODE_DRAW_BUFFERS_ARB.
Referenced by _mesa_initialize_save_table().
save_DrawElementsInstancedARB()
static void GLAPIENTRY save_DrawElementsInstancedARB (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const GLvoid * indices, UNUSED GLsizei primcount) static
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_initialize_save_table().
save_DrawElementsInstancedBaseInstance()
static void APIENTRY save_DrawElementsInstancedBaseInstance (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const void * indices, UNUSED GLsizei primcount, UNUSED GLuint baseinstance) static
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_initialize_save_table().
save_DrawElementsInstancedBaseVertexARB()
static void GLAPIENTRY save_DrawElementsInstancedBaseVertexARB (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const GLvoid * indices, UNUSED GLsizei primcount, UNUSED GLint basevertex) static
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_initialize_save_table().
save_DrawElementsInstancedBaseVertexBaseInstance()
static void APIENTRY save_DrawElementsInstancedBaseVertexBaseInstance (UNUSED GLenum mode, UNUSED GLsizei count, UNUSED GLenum type, UNUSED const void * indices, UNUSED GLsizei primcount, UNUSED GLint basevertex, UNUSED GLuint baseinstance) static
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_initialize_save_table().
save_DrawPixels()
static void GLAPIENTRY save_DrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_DRAW_PIXELS, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_DrawTransformFeedback()
static void GLAPIENTRY save_DrawTransformFeedback (GLenum mode, GLuint name) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_DRAW_TRANSFORM_FEEDBACK, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_DrawTransformFeedbackInstanced()
static void GLAPIENTRY save_DrawTransformFeedbackInstanced (GLenum mode, GLuint name, GLsizei primcount) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_DRAW_TRANSFORM_FEEDBACK_INSTANCED, gl_dlist_node::si, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_DrawTransformFeedbackStream()
static void GLAPIENTRY save_DrawTransformFeedbackStream (GLenum mode, GLuint name, GLuint stream) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_DrawTransformFeedbackStreamInstanced()
static void GLAPIENTRY save_DrawTransformFeedbackStreamInstanced (GLenum mode, GLuint name, GLuint stream, GLsizei primcount) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_DRAW_TRANSFORM_FEEDBACK_STREAM_INSTANCED, gl_dlist_node::si, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_EdgeFlag()
static void GLAPIENTRY save_EdgeFlag (GLboolean x) static
References save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_Enable()
static void GLAPIENTRY save_Enable (GLenum cap) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_ENABLE.
Referenced by _mesa_initialize_save_table().
save_EnableIndexed()
static void GLAPIENTRY save_EnableIndexed (GLuint index, GLenum cap) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_ENABLE_INDEXED, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_End()
static void GLAPIENTRY save_End (void) static
References alloc_instruction(), dd_function_table::CurrentSavePrimitive, gl_context::Driver, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_END, PRIM_OUTSIDE_BEGIN_END, SAVE_FLUSH_VERTICES, and void.
Referenced by save_vtxfmt_init().
save_EndConditionalRender()
static void GLAPIENTRY save_EndConditionalRender (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_END_CONDITIONAL_RENDER.
Referenced by _mesa_initialize_save_table().
save_EndQueryARB()
static void GLAPIENTRY save_EndQueryARB (GLenum target) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_END_QUERY_ARB.
Referenced by _mesa_initialize_save_table().
save_EndQueryIndexed()
static void GLAPIENTRY save_EndQueryIndexed (GLenum target, GLuint index) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_END_QUERY_INDEXED, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_EndTransformFeedback()
static void GLAPIENTRY save_EndTransformFeedback (void) static
GL_EXT_transform_feedback.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_END_TRANSFORM_FEEDBACK, and void.
Referenced by _mesa_initialize_save_table().
save_error()
static void save_error (struct gl_context * ctx, GLenum error, const char * s) static
Save an error-generating command into display list.
KW: Will appear in the list before the vertex buffer containing the command that provoked the error. I don't see this as a problem.
References alloc_instruction(), gl_dlist_node::e, OPCODE_ERROR, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_compile_error().
save_EvalCoord1f()
static void GLAPIENTRY save_EvalCoord1f (GLfloat x) static
References alloc_instruction(), gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_EVAL_C1, SAVE_FLUSH_VERTICES, and x.
Referenced by save_EvalCoord1fv(), and save_vtxfmt_init().
save_EvalCoord1fv()
static void GLAPIENTRY save_EvalCoord1fv (const GLfloat * v) static
References GLAPIENTRY, and save_EvalCoord1f().
Referenced by save_vtxfmt_init().
save_EvalCoord2f()
static void GLAPIENTRY save_EvalCoord2f (GLfloat x, GLfloat y) static
References alloc_instruction(), gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_EVAL_C2, SAVE_FLUSH_VERTICES, and x.
Referenced by save_EvalCoord2fv(), and save_vtxfmt_init().
save_EvalCoord2fv()
static void GLAPIENTRY save_EvalCoord2fv (const GLfloat * v) static
References GLAPIENTRY, and save_EvalCoord2f().
Referenced by save_vtxfmt_init().
save_EvalMesh1()
static void GLAPIENTRY save_EvalMesh1 (GLenum mode, GLint i1, GLint i2) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_EVALMESH1.
Referenced by _mesa_initialize_save_table().
save_EvalMesh2()
static void GLAPIENTRY save_EvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_EVALMESH2.
Referenced by _mesa_initialize_save_table().
save_EvalPoint1()
static void GLAPIENTRY save_EvalPoint1 (GLint x) static
References alloc_instruction(), gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_EVAL_P1, SAVE_FLUSH_VERTICES, and x.
Referenced by save_vtxfmt_init().
save_EvalPoint2()
static void GLAPIENTRY save_EvalPoint2 (GLint x, GLint y) static
References alloc_instruction(), gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_EVAL_P2, SAVE_FLUSH_VERTICES, and x.
Referenced by save_vtxfmt_init().
save_FogCoordfEXT()
static void GLAPIENTRY save_FogCoordfEXT (GLfloat x) static
References GLAPIENTRY, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_FogCoordfvEXT()
static void GLAPIENTRY save_FogCoordfvEXT (const GLfloat * v) static
References GLAPIENTRY, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_Fogf()
static void GLAPIENTRY save_Fogf (GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_Fogfv().
Referenced by _mesa_initialize_save_table().
save_Fogfv()
static void GLAPIENTRY save_Fogfv (GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_FOG.
Referenced by _mesa_initialize_save_table(), save_Fogf(), and save_Fogiv().
save_Fogi()
static void GLAPIENTRY save_Fogi (GLenum pname, GLint param) static
References GLAPIENTRY, and save_Fogiv().
Referenced by _mesa_initialize_save_table().
save_Fogiv()
static void GLAPIENTRY save_Fogiv (GLenum pname, const GLint * params) static
References F, GLAPIENTRY, INT_TO_FLOAT, and save_Fogfv().
Referenced by _mesa_initialize_save_table(), and save_Fogi().
save_FrontFace()
static void GLAPIENTRY save_FrontFace (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_FRONT_FACE.
Referenced by _mesa_initialize_save_table().
save_Frustum()
static void GLAPIENTRY save_Frustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_FRUSTUM.
Referenced by _mesa_initialize_save_table().
save_Hint()
static void GLAPIENTRY save_Hint (GLenum target, GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_HINT.
Referenced by _mesa_initialize_save_table().
save_Indexf()
static void GLAPIENTRY save_Indexf (GLfloat x) static
References GLAPIENTRY, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_Indexfv()
static void GLAPIENTRY save_Indexfv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_IndexMask()
static void GLAPIENTRY save_IndexMask (GLuint mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_INDEX_MASK, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_InitNames()
static void GLAPIENTRY save_InitNames (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_INIT_NAMES, and void.
Referenced by _mesa_initialize_save_table().
save_Lightf()
static void GLAPIENTRY save_Lightf (GLenum light, GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_Lightfv().
Referenced by _mesa_initialize_save_table().
save_Lightfv()
static void GLAPIENTRY save_Lightfv (GLenum light, GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_LIGHT.
Referenced by _mesa_initialize_save_table(), save_Lightf(), and save_Lightiv().
save_Lighti()
static void GLAPIENTRY save_Lighti (GLenum light, GLenum pname, GLint param) static
References GLAPIENTRY, and save_Lightiv().
Referenced by _mesa_initialize_save_table().
save_Lightiv()
static void GLAPIENTRY save_Lightiv (GLenum light, GLenum pname, const GLint * params) static
References GLAPIENTRY, INT_TO_FLOAT, and save_Lightfv().
Referenced by _mesa_initialize_save_table(), and save_Lighti().
save_LightModelf()
static void GLAPIENTRY save_LightModelf (GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_LightModelfv().
Referenced by _mesa_initialize_save_table().
save_LightModelfv()
static void GLAPIENTRY save_LightModelfv (GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_LIGHT_MODEL.
Referenced by _mesa_initialize_save_table(), save_LightModelf(), and save_LightModeliv().
save_LightModeli()
static void GLAPIENTRY save_LightModeli (GLenum pname, GLint param) static
References GLAPIENTRY, and save_LightModeliv().
Referenced by _mesa_initialize_save_table().
save_LightModeliv()
static void GLAPIENTRY save_LightModeliv (GLenum pname, const GLint * params) static
References F, GLAPIENTRY, INT_TO_FLOAT, and save_LightModelfv().
Referenced by _mesa_initialize_save_table(), and save_LightModeli().
save_LineStipple()
static void GLAPIENTRY save_LineStipple (GLint factor, GLushort pattern) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_LINE_STIPPLE, and gl_dlist_node::us.
Referenced by _mesa_initialize_save_table().
save_LineWidth()
static void GLAPIENTRY save_LineWidth (GLfloat width) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_LINE_WIDTH.
Referenced by _mesa_initialize_save_table().
save_ListBase()
static void GLAPIENTRY save_ListBase (GLuint base) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_LIST_BASE, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_LoadIdentity()
static void GLAPIENTRY save_LoadIdentity (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_LOAD_IDENTITY, and void.
Referenced by _mesa_initialize_save_table().
save_LoadMatrixd()
static void GLAPIENTRY save_LoadMatrixd (const GLdouble * m) static
References GLAPIENTRY, and save_LoadMatrixf().
Referenced by _mesa_initialize_save_table().
save_LoadMatrixf()
static void GLAPIENTRY save_LoadMatrixf (const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, and OPCODE_LOAD_MATRIX.
Referenced by _mesa_initialize_save_table(), save_LoadMatrixd(), save_LoadTransposeMatrixdARB(), and save_LoadTransposeMatrixfARB().
save_LoadName()
static void GLAPIENTRY save_LoadName (GLuint name) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_LOAD_NAME, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_LoadTransposeMatrixdARB()
static void GLAPIENTRY save_LoadTransposeMatrixdARB (const GLdouble m[16]) static
References _math_transposefd(), GLAPIENTRY, and save_LoadMatrixf().
Referenced by _mesa_initialize_save_table().
save_LoadTransposeMatrixfARB()
static void GLAPIENTRY save_LoadTransposeMatrixfARB (const GLfloat m[16]) static
References _math_transposef(), GLAPIENTRY, and save_LoadMatrixf().
Referenced by _mesa_initialize_save_table().
save_LogicOp()
static void GLAPIENTRY save_LogicOp (GLenum opcode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_LOGIC_OP.
Referenced by _mesa_initialize_save_table().
save_Map1d()
static void GLAPIENTRY save_Map1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points) static
References _mesa_copy_map_points1d(), _mesa_evaluator_components(), alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_MAP1, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Map1f()
static void GLAPIENTRY save_Map1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points) static
References _mesa_copy_map_points1f(), _mesa_evaluator_components(), alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_MAP1, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Map2d()
static void GLAPIENTRY save_Map2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points) static
References _mesa_copy_map_points2d(), _mesa_evaluator_components(), alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_MAP2, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Map2f()
static void GLAPIENTRY save_Map2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points) static
References _mesa_copy_map_points2f(), _mesa_evaluator_components(), alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_MAP2, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_MapGrid1d()
static void GLAPIENTRY save_MapGrid1d (GLint un, GLdouble u1, GLdouble u2) static
References GLAPIENTRY, and save_MapGrid1f().
Referenced by _mesa_initialize_save_table().
save_MapGrid1f()
static void GLAPIENTRY save_MapGrid1f (GLint un, GLfloat u1, GLfloat u2) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_MAPGRID1.
Referenced by _mesa_initialize_save_table(), and save_MapGrid1d().
save_MapGrid2d()
static void GLAPIENTRY save_MapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2) static
References GLAPIENTRY, and save_MapGrid2f().
Referenced by _mesa_initialize_save_table().
save_MapGrid2f()
static void GLAPIENTRY save_MapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_MAPGRID2.
Referenced by _mesa_initialize_save_table(), and save_MapGrid2d().
save_Materialfv()
static void GLAPIENTRY save_Materialfv (GLenum face, GLenum pname, const GLfloat * param) static
This glMaterial function is used for glMaterial calls that are outside a glBegin/End pair.
For glMaterial inside glBegin/End, see the VBO code.
References _mesa_compile_error(), _mesa_material_bitmask(), gl_dlist_state::ActiveMaterialSize, alloc_instruction(), compare_vec(), COPY_SZ_4V, gl_dlist_state::CurrentMaterial, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_context::ListState, MAT_ATTRIB_MAX, OPCODE_MATERIAL, and SAVE_FLUSH_VERTICES.
Referenced by save_vtxfmt_init().
save_MatrixMode()
static void GLAPIENTRY save_MatrixMode (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_MATRIX_MODE.
Referenced by _mesa_initialize_save_table().
save_MultiTexCoord1f()
static void GLAPIENTRY save_MultiTexCoord1f (GLenum target, GLfloat x) static
References GLAPIENTRY, GLuint, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord1fv()
static void GLAPIENTRY save_MultiTexCoord1fv (GLenum target, const GLfloat * v) static
References GLAPIENTRY, GLuint, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord2f()
static void GLAPIENTRY save_MultiTexCoord2f (GLenum target, GLfloat x, GLfloat y) static
References GLAPIENTRY, GLuint, and save_Attr2fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord2fv()
static void GLAPIENTRY save_MultiTexCoord2fv (GLenum target, const GLfloat * v) static
References GLAPIENTRY, GLuint, and save_Attr2fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord3f()
static void GLAPIENTRY save_MultiTexCoord3f (GLenum target, GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, GLuint, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord3fv()
static void GLAPIENTRY save_MultiTexCoord3fv (GLenum target, const GLfloat * v) static
References GLAPIENTRY, GLuint, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord4f()
static void GLAPIENTRY save_MultiTexCoord4f (GLenum target, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References GLAPIENTRY, GLuint, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_MultiTexCoord4fv()
static void GLAPIENTRY save_MultiTexCoord4fv (GLenum target, const GLfloat * v) static
References GLuint, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_MultMatrixd()
static void GLAPIENTRY save_MultMatrixd (const GLdouble * m) static
References GLAPIENTRY, and save_MultMatrixf().
Referenced by _mesa_initialize_save_table().
save_MultMatrixf()
static void GLAPIENTRY save_MultMatrixf (const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, and OPCODE_MULT_MATRIX.
Referenced by _mesa_initialize_save_table(), save_MultMatrixd(), save_MultTransposeMatrixdARB(), and save_MultTransposeMatrixfARB().
save_MultTransposeMatrixdARB()
static void GLAPIENTRY save_MultTransposeMatrixdARB (const GLdouble m[16]) static
References _math_transposefd(), GLAPIENTRY, and save_MultMatrixf().
Referenced by _mesa_initialize_save_table().
save_MultTransposeMatrixfARB()
static void GLAPIENTRY save_MultTransposeMatrixfARB (const GLfloat m[16]) static
References _math_transposef(), and save_MultMatrixf().
Referenced by _mesa_initialize_save_table().
save_NewList()
static void GLAPIENTRY save_NewList (GLuint name, GLenum mode) static
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
Referenced by _mesa_initialize_save_table().
save_Normal3f()
static void GLAPIENTRY save_Normal3f (GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_Normal3fv()
static void GLAPIENTRY save_Normal3fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_Ortho()
static void GLAPIENTRY save_Ortho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_ORTHO.
Referenced by _mesa_initialize_save_table().
save_PassThrough()
static void GLAPIENTRY save_PassThrough (GLfloat token) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_PASSTHROUGH.
Referenced by _mesa_initialize_save_table().
save_PauseTransformFeedback()
static void GLAPIENTRY save_PauseTransformFeedback (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PAUSE_TRANSFORM_FEEDBACK, and void.
Referenced by _mesa_initialize_save_table().
save_PixelMapfv()
static void GLAPIENTRY save_PixelMapfv (GLenum map, GLint mapsize, const GLfloat * values) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PIXEL_MAP, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table(), save_PixelMapuiv(), and save_PixelMapusv().
save_PixelMapuiv()
static void GLAPIENTRY save_PixelMapuiv (GLenum map, GLint mapsize, const GLuint * values) static
References GLAPIENTRY, MAX_PIXEL_MAP_TABLE, save_PixelMapfv(), and UINT_TO_FLOAT.
Referenced by _mesa_initialize_save_table().
save_PixelMapusv()
static void GLAPIENTRY save_PixelMapusv (GLenum map, GLint mapsize, const GLushort * values) static
References GLAPIENTRY, MAX_PIXEL_MAP_TABLE, save_PixelMapfv(), and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_save_table().
save_PixelTransferf()
static void GLAPIENTRY save_PixelTransferf (GLenum pname, GLfloat param) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_PIXEL_TRANSFER.
Referenced by _mesa_initialize_save_table(), and save_PixelTransferi().
save_PixelTransferi()
static void GLAPIENTRY save_PixelTransferi (GLenum pname, GLint param) static
References GLAPIENTRY, and save_PixelTransferf().
Referenced by _mesa_initialize_save_table().
save_PixelZoom()
static void GLAPIENTRY save_PixelZoom (GLfloat xfactor, GLfloat yfactor) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_PIXEL_ZOOM.
Referenced by _mesa_initialize_save_table().
save_pointer()
static void save_pointer (Node * dest, void * src) inline static
Save a 4 or 8-byte pointer at dest (and dest+1).
References pointer::dwords, POINTER_DWORDS, and pointer::ptr.
Referenced by dlist_alloc(), save_Bitmap(), save_CallLists(), save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), save_CompressedTexSubImage3DARB(), save_DrawPixels(), save_error(), save_Map1d(), save_Map1f(), save_Map2d(), save_Map2f(), save_PixelMapfv(), save_PolygonStipple(), save_ProgramStringARB(), save_ProgramUniform1fv(), save_ProgramUniform1iv(), save_ProgramUniform1uiv(), save_ProgramUniform2fv(), save_ProgramUniform2iv(), save_ProgramUniform2uiv(), save_ProgramUniform3fv(), save_ProgramUniform3iv(), save_ProgramUniform3uiv(), save_ProgramUniform4fv(), save_ProgramUniform4iv(), save_ProgramUniform4uiv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexSubImage1D(), save_TexSubImage2D(), save_TexSubImage3D(), save_Uniform1fvARB(), save_Uniform1ivARB(), save_Uniform1uiv(), save_Uniform2fvARB(), save_Uniform2ivARB(), save_Uniform2uiv(), save_Uniform3fvARB(), save_Uniform3ivARB(), save_Uniform3uiv(), save_Uniform4fvARB(), save_Uniform4ivARB(), save_Uniform4uiv(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), save_WaitSync(), and save_WindowRectanglesEXT().
save_PointParameterfEXT()
static void GLAPIENTRY save_PointParameterfEXT (GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_PointParameterfvEXT().
Referenced by _mesa_initialize_save_table().
save_PointParameterfvEXT()
static void GLAPIENTRY save_PointParameterfvEXT (GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_POINT_PARAMETERS.
Referenced by _mesa_initialize_save_table(), save_PointParameterfEXT(), save_PointParameteriNV(), and save_PointParameterivNV().
save_PointParameteriNV()
static void GLAPIENTRY save_PointParameteriNV (GLenum pname, GLint param) static
References GLAPIENTRY, and save_PointParameterfvEXT().
Referenced by _mesa_initialize_save_table().
save_PointParameterivNV()
static void GLAPIENTRY save_PointParameterivNV (GLenum pname, const GLint * param) static
References GLAPIENTRY, and save_PointParameterfvEXT().
Referenced by _mesa_initialize_save_table().
save_PointSize()
static void GLAPIENTRY save_PointSize (GLfloat size) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_POINT_SIZE.
Referenced by _mesa_initialize_save_table().
save_PolygonMode()
static void GLAPIENTRY save_PolygonMode (GLenum face, GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_POLYGON_MODE.
Referenced by _mesa_initialize_save_table().
save_PolygonOffset()
static void GLAPIENTRY save_PolygonOffset (GLfloat factor, GLfloat units) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_POLYGON_OFFSET.
Referenced by _mesa_initialize_save_table(), and save_PolygonOffsetEXT().
save_PolygonOffsetClampEXT()
static void GLAPIENTRY save_PolygonOffsetClampEXT (GLfloat factor, GLfloat units, GLfloat clamp) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_POLYGON_OFFSET_CLAMP.
Referenced by _mesa_initialize_save_table().
save_PolygonOffsetEXT()
static void GLAPIENTRY save_PolygonOffsetEXT (GLfloat factor, GLfloat bias) static
References gl_framebuffer::_DepthMaxF, gl_context::DrawBuffer, GET_CURRENT_CONTEXT, GLAPIENTRY, and save_PolygonOffset().
Referenced by _mesa_initialize_save_table().
save_PolygonStipple()
static void GLAPIENTRY save_PolygonStipple (const GLubyte * pattern) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_POLYGON_STIPPLE, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_PopAttrib()
static void GLAPIENTRY save_PopAttrib (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_POP_ATTRIB, and void.
Referenced by _mesa_initialize_save_table().
save_PopMatrix()
static void GLAPIENTRY save_PopMatrix (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_POP_MATRIX, and void.
Referenced by _mesa_initialize_save_table().
save_PopName()
static void GLAPIENTRY save_PopName (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_POP_NAME, and void.
Referenced by _mesa_initialize_save_table().
save_PrioritizeTextures()
static void GLAPIENTRY save_PrioritizeTextures (GLsizei num, const GLuint * textures, const GLclampf * priorities) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PRIORITIZE_TEXTURE, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramEnvParameter4dARB()
static void GLAPIENTRY save_ProgramEnvParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w) static
References GLAPIENTRY, and save_ProgramEnvParameter4fARB().
Referenced by _mesa_initialize_save_table().
save_ProgramEnvParameter4dvARB()
static void GLAPIENTRY save_ProgramEnvParameter4dvARB (GLenum target, GLuint index, const GLdouble * params) static
References GLAPIENTRY, and save_ProgramEnvParameter4fARB().
Referenced by _mesa_initialize_save_table().
save_ProgramEnvParameter4fARB()
static void GLAPIENTRY save_ProgramEnvParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_ENV_PARAMETER_ARB, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table(), save_ProgramEnvParameter4dARB(), save_ProgramEnvParameter4dvARB(), and save_ProgramEnvParameter4fvARB().
save_ProgramEnvParameter4fvARB()
static void GLAPIENTRY save_ProgramEnvParameter4fvARB (GLenum target, GLuint index, const GLfloat * params) static
References GLAPIENTRY, and save_ProgramEnvParameter4fARB().
Referenced by _mesa_initialize_save_table().
save_ProgramEnvParameters4fvEXT()
static void GLAPIENTRY save_ProgramEnvParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_ENV_PARAMETER_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramLocalParameter4dARB()
static void GLAPIENTRY save_ProgramLocalParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramLocalParameter4dvARB()
static void GLAPIENTRY save_ProgramLocalParameter4dvARB (GLenum target, GLuint index, const GLdouble * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramLocalParameter4fARB()
static void GLAPIENTRY save_ProgramLocalParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramLocalParameter4fvARB()
static void GLAPIENTRY save_ProgramLocalParameter4fvARB (GLenum target, GLuint index, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramLocalParameters4fvEXT()
static void GLAPIENTRY save_ProgramLocalParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PROGRAM_LOCAL_PARAMETER_ARB, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramStringARB()
static void GLAPIENTRY save_ProgramStringARB (GLenum target, GLenum format, GLsizei len, const GLvoid * string) static
References _mesa_error(), alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_STRING_ARB, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_ProgramUniform1f()
static void GLAPIENTRY save_ProgramUniform1f (GLuint program, GLint location, GLfloat x) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_1F, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform1fv()
static void GLAPIENTRY save_ProgramUniform1fv (GLuint program, GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_1FV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform1i()
static void GLAPIENTRY save_ProgramUniform1i (GLuint program, GLint location, GLint x) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_1I, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform1iv()
static void GLAPIENTRY save_ProgramUniform1iv (GLuint program, GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_1IV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform1ui()
static void GLAPIENTRY save_ProgramUniform1ui (GLuint program, GLint location, GLuint x) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_1UI, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform1uiv()
static void GLAPIENTRY save_ProgramUniform1uiv (GLuint program, GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_1UIV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform2f()
static void GLAPIENTRY save_ProgramUniform2f (GLuint program, GLint location, GLfloat x, GLfloat y) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_2F, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform2fv()
static void GLAPIENTRY save_ProgramUniform2fv (GLuint program, GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_2FV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform2i()
static void GLAPIENTRY save_ProgramUniform2i (GLuint program, GLint location, GLint x, GLint y) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_2I, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform2iv()
static void GLAPIENTRY save_ProgramUniform2iv (GLuint program, GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_2IV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform2ui()
static void GLAPIENTRY save_ProgramUniform2ui (GLuint program, GLint location, GLuint x, GLuint y) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_2UI, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform2uiv()
static void GLAPIENTRY save_ProgramUniform2uiv (GLuint program, GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_2UIV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform3f()
static void GLAPIENTRY save_ProgramUniform3f (GLuint program, GLint location, GLfloat x, GLfloat y, GLfloat z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_3F, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform3fv()
static void GLAPIENTRY save_ProgramUniform3fv (GLuint program, GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_3FV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform3i()
static void GLAPIENTRY save_ProgramUniform3i (GLuint program, GLint location, GLint x, GLint y, GLint z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_3I, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform3iv()
static void GLAPIENTRY save_ProgramUniform3iv (GLuint program, GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_3IV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform3ui()
static void GLAPIENTRY save_ProgramUniform3ui (GLuint program, GLint location, GLuint x, GLuint y, GLuint z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_3UI, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform3uiv()
static void GLAPIENTRY save_ProgramUniform3uiv (GLuint program, GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_3UIV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform4f()
static void GLAPIENTRY save_ProgramUniform4f (GLuint program, GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_4F, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform4fv()
static void GLAPIENTRY save_ProgramUniform4fv (GLuint program, GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_4FV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform4i()
static void GLAPIENTRY save_ProgramUniform4i (GLuint program, GLint location, GLint x, GLint y, GLint z, GLint w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_4I, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform4iv()
static void GLAPIENTRY save_ProgramUniform4iv (GLuint program, GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_4IV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform4ui()
static void GLAPIENTRY save_ProgramUniform4ui (GLuint program, GLint location, GLuint x, GLuint y, GLuint z, GLuint w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_PROGRAM_UNIFORM_4UI, gl_dlist_node::ui, and x.
Referenced by _mesa_initialize_save_table().
save_ProgramUniform4uiv()
static void GLAPIENTRY save_ProgramUniform4uiv (GLuint program, GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_4UIV, POINTER_DWORDS, save_pointer(), and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix2fv()
static void GLAPIENTRY save_ProgramUniformMatrix2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX22F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix2x3fv()
static void GLAPIENTRY save_ProgramUniformMatrix2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX23F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix2x4fv()
static void GLAPIENTRY save_ProgramUniformMatrix2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX24F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix3fv()
static void GLAPIENTRY save_ProgramUniformMatrix3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX33F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix3x2fv()
static void GLAPIENTRY save_ProgramUniformMatrix3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX32F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix3x4fv()
static void GLAPIENTRY save_ProgramUniformMatrix3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX34F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix4fv()
static void GLAPIENTRY save_ProgramUniformMatrix4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX44F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix4x2fv()
static void GLAPIENTRY save_ProgramUniformMatrix4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX42F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProgramUniformMatrix4x3fv()
static void GLAPIENTRY save_ProgramUniformMatrix4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_PROGRAM_UNIFORM_MATRIX43F, POINTER_DWORDS, save_pointer(), transpose, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ProvokingVertexEXT()
static void GLAPIENTRY save_ProvokingVertexEXT (GLenum mode) static
GL_EXT_provoking_vertex.
References _mesa_ProvokingVertex(), alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_PROVOKING_VERTEX.
Referenced by _mesa_initialize_save_table().
save_PushAttrib()
static void GLAPIENTRY save_PushAttrib (GLbitfield mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::bf, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_PUSH_ATTRIB.
Referenced by _mesa_initialize_save_table().
save_PushMatrix()
static void GLAPIENTRY save_PushMatrix (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PUSH_MATRIX, and void.
Referenced by _mesa_initialize_save_table().
save_PushName()
static void GLAPIENTRY save_PushName (GLuint name) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_PUSH_NAME, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_QueryCounter()
static void GLAPIENTRY save_QueryCounter (GLuint id, GLenum target) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_QUERY_COUNTER, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_RasterPos2d()
static void GLAPIENTRY save_RasterPos2d (GLdouble x, GLdouble y) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2dv()
static void GLAPIENTRY save_RasterPos2dv (const GLdouble * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2f()
static void GLAPIENTRY save_RasterPos2f (GLfloat x, GLfloat y) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2fv()
static void GLAPIENTRY save_RasterPos2fv (const GLfloat * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2i()
static void GLAPIENTRY save_RasterPos2i (GLint x, GLint y) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2iv()
static void GLAPIENTRY save_RasterPos2iv (const GLint * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2s()
static void GLAPIENTRY save_RasterPos2s (GLshort x, GLshort y) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos2sv()
static void GLAPIENTRY save_RasterPos2sv (const GLshort * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3d()
static void GLAPIENTRY save_RasterPos3d (GLdouble x, GLdouble y, GLdouble z) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3dv()
static void GLAPIENTRY save_RasterPos3dv (const GLdouble * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3f()
static void GLAPIENTRY save_RasterPos3f (GLfloat x, GLfloat y, GLfloat z) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3fv()
static void GLAPIENTRY save_RasterPos3fv (const GLfloat * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3i()
static void GLAPIENTRY save_RasterPos3i (GLint x, GLint y, GLint z) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3iv()
static void GLAPIENTRY save_RasterPos3iv (const GLint * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3s()
static void GLAPIENTRY save_RasterPos3s (GLshort x, GLshort y, GLshort z) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos3sv()
static void GLAPIENTRY save_RasterPos3sv (const GLshort * v) static
References F, GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4d()
static void GLAPIENTRY save_RasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4dv()
static void GLAPIENTRY save_RasterPos4dv (const GLdouble * v) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4f()
static void GLAPIENTRY save_RasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_RASTER_POS, and x.
Referenced by _mesa_initialize_save_table(), save_RasterPos2d(), save_RasterPos2dv(), save_RasterPos2f(), save_RasterPos2fv(), save_RasterPos2i(), save_RasterPos2iv(), save_RasterPos2s(), save_RasterPos2sv(), save_RasterPos3d(), save_RasterPos3dv(), save_RasterPos3f(), save_RasterPos3fv(), save_RasterPos3i(), save_RasterPos3iv(), save_RasterPos3s(), save_RasterPos3sv(), save_RasterPos4d(), save_RasterPos4dv(), save_RasterPos4fv(), save_RasterPos4i(), save_RasterPos4iv(), save_RasterPos4s(), and save_RasterPos4sv().
save_RasterPos4fv()
static void GLAPIENTRY save_RasterPos4fv (const GLfloat * v) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4i()
static void GLAPIENTRY save_RasterPos4i (GLint x, GLint y, GLint z, GLint w) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4iv()
static void GLAPIENTRY save_RasterPos4iv (const GLint * v) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4s()
static void GLAPIENTRY save_RasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_RasterPos4sv()
static void GLAPIENTRY save_RasterPos4sv (const GLshort * v) static
References GLAPIENTRY, and save_RasterPos4f().
Referenced by _mesa_initialize_save_table().
save_ReadBuffer()
static void GLAPIENTRY save_ReadBuffer (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_READ_BUFFER.
Referenced by _mesa_initialize_save_table().
save_Rectf()
static void GLAPIENTRY save_Rectf (GLfloat a, GLfloat b, GLfloat c, GLfloat d) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_RECTF.
Referenced by _mesa_initialize_save_table().
save_ResumeTransformFeedback()
static void GLAPIENTRY save_ResumeTransformFeedback (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_RESUME_TRANSFORM_FEEDBACK, and void.
Referenced by _mesa_initialize_save_table().
save_Rotated()
static void GLAPIENTRY save_Rotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z) static
References GLAPIENTRY, and save_Rotatef().
Referenced by _mesa_initialize_save_table().
save_Rotatef()
static void GLAPIENTRY save_Rotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_ROTATE, and x.
Referenced by _mesa_initialize_save_table(), and save_Rotated().
save_SampleCoverageARB()
static void GLAPIENTRY save_SampleCoverageARB (GLclampf value, GLboolean invert) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_SAMPLE_COVERAGE.
Referenced by _mesa_initialize_save_table().
save_SamplerParameterf()
static void GLAPIENTRY save_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_SamplerParameterfv().
Referenced by _mesa_initialize_save_table().
save_SamplerParameterfv()
static void GLAPIENTRY save_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_SAMPLER_PARAMETERFV, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table(), and save_SamplerParameterf().
save_SamplerParameteri()
static void GLAPIENTRY save_SamplerParameteri (GLuint sampler, GLenum pname, GLint param) static
References GLAPIENTRY, and save_SamplerParameteriv().
Referenced by _mesa_initialize_save_table().
save_SamplerParameterIiv()
static void GLAPIENTRY save_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_SAMPLER_PARAMETERIIV, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_SamplerParameterIuiv()
static void GLAPIENTRY save_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_SAMPLER_PARAMETERUIV, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_SamplerParameteriv()
static void GLAPIENTRY save_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_SAMPLER_PARAMETERIV, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table(), and save_SamplerParameteri().
save_Scaled()
static void GLAPIENTRY save_Scaled (GLdouble x, GLdouble y, GLdouble z) static
References GLAPIENTRY, and save_Scalef().
Referenced by _mesa_initialize_save_table().
save_Scalef()
static void GLAPIENTRY save_Scalef (GLfloat x, GLfloat y, GLfloat z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_SCALE, and x.
Referenced by _mesa_initialize_save_table(), and save_Scaled().
save_Scissor()
static void GLAPIENTRY save_Scissor (GLint x, GLint y, GLsizei width, GLsizei height) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_SCISSOR, and x.
Referenced by _mesa_initialize_save_table().
save_SecondaryColor3fEXT()
static void GLAPIENTRY save_SecondaryColor3fEXT (GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_SecondaryColor3fvEXT()
static void GLAPIENTRY save_SecondaryColor3fvEXT (const GLfloat * v) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_SetFragmentShaderConstantATI()
static void GLAPIENTRY save_SetFragmentShaderConstantATI (GLuint dst, const GLfloat * value) static
References alloc_instruction(), gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_SET_FRAGMENT_SHADER_CONSTANTS_ATI, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_ShadeModel()
static void GLAPIENTRY save_ShadeModel (GLenum mode) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END, gl_dlist_state::Current, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_context::ListState, OPCODE_SHADE_MODEL, SAVE_FLUSH_VERTICES, and gl_dlist_state::ShadeModel.
Referenced by _mesa_initialize_save_table().
save_StencilFunc()
static void GLAPIENTRY save_StencilFunc (GLenum func, GLint ref, GLuint mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_STENCIL_FUNC, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_StencilFuncSeparate()
static void GLAPIENTRY save_StencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_STENCIL_FUNC_SEPARATE, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_StencilFuncSeparateATI()
static void GLAPIENTRY save_StencilFuncSeparateATI (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_STENCIL_FUNC_SEPARATE, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_StencilMask()
static void GLAPIENTRY save_StencilMask (GLuint mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_STENCIL_MASK, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_StencilMaskSeparate()
static void GLAPIENTRY save_StencilMaskSeparate (GLenum face, GLuint mask) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_STENCIL_MASK_SEPARATE, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_StencilOp()
static void GLAPIENTRY save_StencilOp (GLenum fail, GLenum zfail, GLenum zpass) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_STENCIL_OP.
Referenced by _mesa_initialize_save_table().
save_StencilOpSeparate()
static void GLAPIENTRY save_StencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_STENCIL_OP_SEPARATE.
Referenced by _mesa_initialize_save_table().
save_TexCoord1f()
static void GLAPIENTRY save_TexCoord1f (GLfloat x) static
References GLAPIENTRY, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_TexCoord1fv()
static void GLAPIENTRY save_TexCoord1fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr1fNV().
Referenced by save_vtxfmt_init().
save_TexCoord2f()
static void GLAPIENTRY save_TexCoord2f (GLfloat x, GLfloat y) static
References GLAPIENTRY, and save_Attr2fNV().
Referenced by save_vtxfmt_init().
save_TexCoord2fv()
static void GLAPIENTRY save_TexCoord2fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr2fNV().
Referenced by save_vtxfmt_init().
save_TexCoord3f()
static void GLAPIENTRY save_TexCoord3f (GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_TexCoord3fv()
static void GLAPIENTRY save_TexCoord3fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_TexCoord4f()
static void GLAPIENTRY save_TexCoord4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References GLAPIENTRY, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_TexCoord4fv()
static void GLAPIENTRY save_TexCoord4fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_TexEnvf()
static void GLAPIENTRY save_TexEnvf (GLenum target, GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_TexEnvfv().
Referenced by _mesa_initialize_save_table().
save_TexEnvfv()
static void GLAPIENTRY save_TexEnvfv (GLenum target, GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_TEXENV.
Referenced by _mesa_initialize_save_table(), save_TexEnvf(), save_TexEnvi(), and save_TexEnviv().
save_TexEnvi()
static void GLAPIENTRY save_TexEnvi (GLenum target, GLenum pname, GLint param) static
References GLAPIENTRY, and save_TexEnvfv().
Referenced by _mesa_initialize_save_table().
save_TexEnviv()
static void GLAPIENTRY save_TexEnviv (GLenum target, GLenum pname, const GLint * param) static
References GLAPIENTRY, INT_TO_FLOAT, and save_TexEnvfv().
Referenced by _mesa_initialize_save_table().
save_TexGend()
static void GLAPIENTRY save_TexGend (GLenum coord, GLenum pname, GLdouble param) static
References GLAPIENTRY, and save_TexGenfv().
Referenced by _mesa_initialize_save_table().
save_TexGendv()
static void GLAPIENTRY save_TexGendv (GLenum coord, GLenum pname, const GLdouble * params) static
References GLAPIENTRY, and save_TexGenfv().
Referenced by _mesa_initialize_save_table().
save_TexGenf()
static void GLAPIENTRY save_TexGenf (GLenum coord, GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_TexGenfv().
Referenced by _mesa_initialize_save_table().
save_TexGenfv()
static void GLAPIENTRY save_TexGenfv (GLenum coord, GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_TEXGEN.
Referenced by _mesa_initialize_save_table(), save_TexGend(), save_TexGendv(), save_TexGenf(), and save_TexGeniv().
save_TexGeni()
static void GLAPIENTRY save_TexGeni (GLenum coord, GLenum pname, GLint param) static
References GLAPIENTRY, and save_TexGeniv().
Referenced by _mesa_initialize_save_table().
save_TexGeniv()
static void GLAPIENTRY save_TexGeniv (GLenum coord, GLenum pname, const GLint * params) static
References GLAPIENTRY, and save_TexGenfv().
Referenced by _mesa_initialize_save_table(), and save_TexGeni().
save_TexImage1D()
static void GLAPIENTRY save_TexImage1D (GLenum target, GLint level, GLint components, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_TEX_IMAGE1D, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_TexImage2D()
static void GLAPIENTRY save_TexImage2D (GLenum target, GLint level, GLint components, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_TEX_IMAGE2D, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_TexImage3D()
static void GLAPIENTRY save_TexImage3D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_TEX_IMAGE3D, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_TexParameterf()
static void GLAPIENTRY save_TexParameterf (GLenum target, GLenum pname, GLfloat param) static
References GLAPIENTRY, and save_TexParameterfv().
Referenced by _mesa_initialize_save_table().
save_TexParameterfv()
static void GLAPIENTRY save_TexParameterfv (GLenum target, GLenum pname, const GLfloat * params) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_TEXPARAMETER.
Referenced by _mesa_initialize_save_table(), save_TexParameterf(), save_TexParameteri(), and save_TexParameteriv().
save_TexParameteri()
static void GLAPIENTRY save_TexParameteri (GLenum target, GLenum pname, GLint param) static
References GLAPIENTRY, and save_TexParameterfv().
Referenced by _mesa_initialize_save_table().
save_TexParameterIiv()
static void GLAPIENTRY save_TexParameterIiv (GLenum target, GLenum pname, const GLint * params) static
GL_EXT_texture_integer.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, and OPCODE_TEXPARAMETER_I.
Referenced by _mesa_initialize_save_table().
save_TexParameterIuiv()
static void GLAPIENTRY save_TexParameterIuiv (GLenum target, GLenum pname, const GLuint * params) static
GL_EXT_texture_integer.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_TEXPARAMETER_UI, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_TexParameteriv()
static void GLAPIENTRY save_TexParameteriv (GLenum target, GLenum pname, const GLint * params) static
References GLAPIENTRY, and save_TexParameterfv().
Referenced by _mesa_initialize_save_table().
save_TexSubImage1D()
static void GLAPIENTRY save_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_TEX_SUB_IMAGE1D, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_TexSubImage2D()
static void GLAPIENTRY save_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_TEX_SUB_IMAGE2D, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_TexSubImage3D()
static void GLAPIENTRY save_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_TEX_SUB_IMAGE3D, POINTER_DWORDS, save_pointer(), gl_context::Unpack, and unpack_image().
Referenced by _mesa_initialize_save_table().
save_TextureBarrierNV()
static void GLAPIENTRY save_TextureBarrierNV (void) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, and OPCODE_TEXTURE_BARRIER_NV.
Referenced by _mesa_initialize_save_table().
save_Translated()
static void GLAPIENTRY save_Translated (GLdouble x, GLdouble y, GLdouble z) static
References GLAPIENTRY, and save_Translatef().
Referenced by _mesa_initialize_save_table().
save_Translatef()
static void GLAPIENTRY save_Translatef (GLfloat x, GLfloat y, GLfloat z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_TRANSLATE, and x.
Referenced by _mesa_initialize_save_table(), and save_Translated().
save_Uniform1fARB()
static void GLAPIENTRY save_Uniform1fARB (GLint location, GLfloat x) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_1F, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform1fvARB()
static void GLAPIENTRY save_Uniform1fvARB (GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_1FV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform1iARB()
static void GLAPIENTRY save_Uniform1iARB (GLint location, GLint x) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_1I, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform1ivARB()
static void GLAPIENTRY save_Uniform1ivARB (GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_1IV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform1ui()
static void GLAPIENTRY save_Uniform1ui (GLint location, GLuint x) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_1UI, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform1uiv()
static void GLAPIENTRY save_Uniform1uiv (GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_1UIV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform2fARB()
static void GLAPIENTRY save_Uniform2fARB (GLint location, GLfloat x, GLfloat y) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_2F, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform2fvARB()
static void GLAPIENTRY save_Uniform2fvARB (GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_2FV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform2iARB()
static void GLAPIENTRY save_Uniform2iARB (GLint location, GLint x, GLint y) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_2I, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform2ivARB()
static void GLAPIENTRY save_Uniform2ivARB (GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_2IV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform2ui()
static void GLAPIENTRY save_Uniform2ui (GLint location, GLuint x, GLuint y) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_2UI, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform2uiv()
static void GLAPIENTRY save_Uniform2uiv (GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_2UIV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform3fARB()
static void GLAPIENTRY save_Uniform3fARB (GLint location, GLfloat x, GLfloat y, GLfloat z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_3F, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform3fvARB()
static void GLAPIENTRY save_Uniform3fvARB (GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_3FV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform3iARB()
static void GLAPIENTRY save_Uniform3iARB (GLint location, GLint x, GLint y, GLint z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_3I, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform3ivARB()
static void GLAPIENTRY save_Uniform3ivARB (GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_3IV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform3ui()
static void GLAPIENTRY save_Uniform3ui (GLint location, GLuint x, GLuint y, GLuint z) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_3UI, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform3uiv()
static void GLAPIENTRY save_Uniform3uiv (GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_3UIV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform4fARB()
static void GLAPIENTRY save_Uniform4fARB (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_4F, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform4fvARB()
static void GLAPIENTRY save_Uniform4fvARB (GLint location, GLsizei count, const GLfloat * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_4FV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform4iARB()
static void GLAPIENTRY save_Uniform4iARB (GLint location, GLint x, GLint y, GLint z, GLint w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_4I, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform4ivARB()
static void GLAPIENTRY save_Uniform4ivARB (GLint location, GLsizei count, const GLint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_4IV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_Uniform4ui()
static void GLAPIENTRY save_Uniform4ui (GLint location, GLuint x, GLuint y, GLuint z, GLuint w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_UNIFORM_4UI, and x.
Referenced by _mesa_initialize_save_table().
save_Uniform4uiv()
static void GLAPIENTRY save_Uniform4uiv (GLint location, GLsizei count, const GLuint * v) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_4UIV, POINTER_DWORDS, and save_pointer().
Referenced by _mesa_initialize_save_table().
save_UniformBlockBinding()
static void GLAPIENTRY save_UniformBlockBinding (GLuint prog, GLuint index, GLuint binding) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_UNIFORM_BLOCK_BINDING, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix2fvARB()
static void GLAPIENTRY save_UniformMatrix2fvARB (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX22, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix2x3fv()
static void GLAPIENTRY save_UniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX23, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix2x4fv()
static void GLAPIENTRY save_UniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX24, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix3fvARB()
static void GLAPIENTRY save_UniformMatrix3fvARB (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX33, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix3x2fv()
static void GLAPIENTRY save_UniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX32, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix3x4fv()
static void GLAPIENTRY save_UniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX34, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix4fvARB()
static void GLAPIENTRY save_UniformMatrix4fvARB (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX44, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix4x2fv()
static void GLAPIENTRY save_UniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX42, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UniformMatrix4x3fv()
static void GLAPIENTRY save_UniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * m) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::b, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, memdup(), OPCODE_UNIFORM_MATRIX43, POINTER_DWORDS, save_pointer(), and transpose.
Referenced by _mesa_initialize_save_table().
save_UseProgram()
static void GLAPIENTRY save_UseProgram (GLuint program) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_USE_PROGRAM, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_UseProgramStages()
static void GLAPIENTRY save_UseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_USE_PROGRAM_STAGES, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_Vertex2f()
static void GLAPIENTRY save_Vertex2f (GLfloat x, GLfloat y) static
References GLAPIENTRY, and save_Attr2fNV().
Referenced by save_vtxfmt_init().
save_Vertex2fv()
static void GLAPIENTRY save_Vertex2fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr2fNV().
Referenced by save_vtxfmt_init().
save_Vertex3f()
static void GLAPIENTRY save_Vertex3f (GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_Vertex3fv()
static void GLAPIENTRY save_Vertex3fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr3fNV().
Referenced by save_vtxfmt_init().
save_Vertex4f()
static void GLAPIENTRY save_Vertex4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References GLAPIENTRY, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_Vertex4fv()
static void GLAPIENTRY save_Vertex4fv (const GLfloat * v) static
References GLAPIENTRY, and save_Attr4fNV().
Referenced by save_vtxfmt_init().
save_VertexAttrib1fARB()
static void GLAPIENTRY save_VertexAttrib1fARB (GLuint index, GLfloat x) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr1fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib1fvARB()
static void GLAPIENTRY save_VertexAttrib1fvARB (GLuint index, const GLfloat * v) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr1fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib2fARB()
static void GLAPIENTRY save_VertexAttrib2fARB (GLuint index, GLfloat x, GLfloat y) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr2fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib2fvARB()
static void GLAPIENTRY save_VertexAttrib2fvARB (GLuint index, const GLfloat * v) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr2fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib3fARB()
static void GLAPIENTRY save_VertexAttrib3fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr3fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib3fvARB()
static void GLAPIENTRY save_VertexAttrib3fvARB (GLuint index, const GLfloat * v) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr3fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib4fARB()
static void GLAPIENTRY save_VertexAttrib4fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr4fARB().
Referenced by save_vtxfmt_init().
save_VertexAttrib4fvARB()
static void GLAPIENTRY save_VertexAttrib4fvARB (GLuint index, const GLfloat * v) static
References GLAPIENTRY, index_error(), MAX_VERTEX_GENERIC_ATTRIBS, and save_Attr4fARB().
Referenced by save_vtxfmt_init().
save_VertexAttribDivisor()
static void GLAPIENTRY save_VertexAttribDivisor (GLuint index, GLuint divisor) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_VERTEX_ATTRIB_DIVISOR, and gl_dlist_node::ui.
Referenced by _mesa_initialize_save_table().
save_Viewport()
static void GLAPIENTRY save_Viewport (GLint x, GLint y, GLsizei width, GLsizei height) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_dlist_node::i, OPCODE_VIEWPORT, and x.
Referenced by _mesa_initialize_save_table().
save_vtxfmt_init()
static void save_vtxfmt_init (GLvertexformat * vfmt) static
References _ae_ArrayElement(), save_Begin(), save_CallList(), save_CallLists(), save_Color3f(), save_Color3fv(), save_Color4f(), save_Color4fv(), save_EdgeFlag(), save_End(), save_EvalCoord1f(), save_EvalCoord1fv(), save_EvalCoord2f(), save_EvalCoord2fv(), save_EvalPoint1(), save_EvalPoint2(), save_FogCoordfEXT(), save_FogCoordfvEXT(), save_Indexf(), save_Indexfv(), save_Materialfv(), save_MultiTexCoord1f(), save_MultiTexCoord1fv(), save_MultiTexCoord2f(), save_MultiTexCoord2fv(), save_MultiTexCoord3f(), save_MultiTexCoord3fv(), save_MultiTexCoord4f(), save_MultiTexCoord4fv(), save_Normal3f(), save_Normal3fv(), save_SecondaryColor3fEXT(), save_SecondaryColor3fvEXT(), save_TexCoord1f(), save_TexCoord1fv(), save_TexCoord2f(), save_TexCoord2fv(), save_TexCoord3f(), save_TexCoord3fv(), save_TexCoord4f(), save_TexCoord4fv(), save_Vertex2f(), save_Vertex2fv(), save_Vertex3f(), save_Vertex3fv(), save_Vertex4f(), save_Vertex4fv(), save_VertexAttrib1fARB(), save_VertexAttrib1fvARB(), save_VertexAttrib2fARB(), save_VertexAttrib2fvARB(), save_VertexAttrib3fARB(), save_VertexAttrib3fvARB(), save_VertexAttrib4fARB(), and save_VertexAttrib4fvARB().
Referenced by _mesa_init_display_list().
save_WaitSync()
static void GLAPIENTRY save_WaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::bf, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_WAIT_SYNC, save_pointer(), gl_dlist_node::ui, uint64_pair::uint32, and uint64_pair::uint64.
Referenced by _mesa_initialize_save_table().
save_WindowPos2dMESA()
static void GLAPIENTRY save_WindowPos2dMESA (GLdouble x, GLdouble y) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2dvMESA()
static void GLAPIENTRY save_WindowPos2dvMESA (const GLdouble * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2fMESA()
static void GLAPIENTRY save_WindowPos2fMESA (GLfloat x, GLfloat y) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2fvMESA()
static void GLAPIENTRY save_WindowPos2fvMESA (const GLfloat * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2iMESA()
static void GLAPIENTRY save_WindowPos2iMESA (GLint x, GLint y) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2ivMESA()
static void GLAPIENTRY save_WindowPos2ivMESA (const GLint * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2sMESA()
static void GLAPIENTRY save_WindowPos2sMESA (GLshort x, GLshort y) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos2svMESA()
static void GLAPIENTRY save_WindowPos2svMESA (const GLshort * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3dMESA()
static void GLAPIENTRY save_WindowPos3dMESA (GLdouble x, GLdouble y, GLdouble z) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3dvMESA()
static void GLAPIENTRY save_WindowPos3dvMESA (const GLdouble * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3fMESA()
static void GLAPIENTRY save_WindowPos3fMESA (GLfloat x, GLfloat y, GLfloat z) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3fvMESA()
static void GLAPIENTRY save_WindowPos3fvMESA (const GLfloat * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3iMESA()
static void GLAPIENTRY save_WindowPos3iMESA (GLint x, GLint y, GLint z) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3ivMESA()
static void GLAPIENTRY save_WindowPos3ivMESA (const GLint * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3sMESA()
static void GLAPIENTRY save_WindowPos3sMESA (GLshort x, GLshort y, GLshort z) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos3svMESA()
static void GLAPIENTRY save_WindowPos3svMESA (const GLshort * v) static
References F, GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4dMESA()
static void GLAPIENTRY save_WindowPos4dMESA (GLdouble x, GLdouble y, GLdouble z, GLdouble w) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4dvMESA()
static void GLAPIENTRY save_WindowPos4dvMESA (const GLdouble * v) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4fMESA()
static void GLAPIENTRY save_WindowPos4fMESA (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_context::Exec, gl_context::ExecuteFlag, gl_dlist_node::f, GET_CURRENT_CONTEXT, GLAPIENTRY, OPCODE_WINDOW_POS, and x.
Referenced by _mesa_initialize_save_table(), save_WindowPos2dMESA(), save_WindowPos2dvMESA(), save_WindowPos2fMESA(), save_WindowPos2fvMESA(), save_WindowPos2iMESA(), save_WindowPos2ivMESA(), save_WindowPos2sMESA(), save_WindowPos2svMESA(), save_WindowPos3dMESA(), save_WindowPos3dvMESA(), save_WindowPos3fMESA(), save_WindowPos3fvMESA(), save_WindowPos3iMESA(), save_WindowPos3ivMESA(), save_WindowPos3sMESA(), save_WindowPos3svMESA(), save_WindowPos4dMESA(), save_WindowPos4dvMESA(), save_WindowPos4fvMESA(), save_WindowPos4iMESA(), save_WindowPos4ivMESA(), save_WindowPos4sMESA(), and save_WindowPos4svMESA().
save_WindowPos4fvMESA()
static void GLAPIENTRY save_WindowPos4fvMESA (const GLfloat * v) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4iMESA()
static void GLAPIENTRY save_WindowPos4iMESA (GLint x, GLint y, GLint z, GLint w) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4ivMESA()
static void GLAPIENTRY save_WindowPos4ivMESA (const GLint * v) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4sMESA()
static void GLAPIENTRY save_WindowPos4sMESA (GLshort x, GLshort y, GLshort z, GLshort w) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowPos4svMESA()
static void GLAPIENTRY save_WindowPos4svMESA (const GLshort * v) static
References GLAPIENTRY, and save_WindowPos4fMESA().
Referenced by _mesa_initialize_save_table().
save_WindowRectanglesEXT()
static void GLAPIENTRY save_WindowRectanglesEXT (GLenum mode, GLsizei count, const GLint * box) static
GL_EXT_window_rectangles.
References alloc_instruction(), ASSERT_OUTSIDE_SAVE_BEGIN_END_AND_FLUSH, gl_dlist_node::e, gl_context::Exec, gl_context::ExecuteFlag, GET_CURRENT_CONTEXT, memdup(), OPCODE_WINDOW_RECTANGLES, POINTER_DWORDS, save_pointer(), and gl_dlist_node::si.
Referenced by _mesa_initialize_save_table().
translate_id()
static GLint translate_id (GLsizei n, GLenum type, const GLvoid * list) static
References GLuint, and GLushort.
Referenced by _mesa_CallLists().
trim_list()
static void trim_list (struct gl_context * ctx) static
Called by EndList to try to reduce memory used for the list.
References _mesa_error(), BLOCK_SIZE, gl_dlist_state::CurrentBlock, gl_dlist_state::CurrentList, gl_dlist_state::CurrentPos, GLAPIENTRY, GLuint, gl_display_list::Head, and gl_context::ListState.
Referenced by _mesa_EndList().
unpack_image()
static GLvoid* unpack_image (struct gl_context * ctx, GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * unpack) static
Wrapper for _mesa_unpack_image/bitmap() that handles pixel buffer objects.
If width < 0 or height < 0 or format or type are invalid we'll just return NULL. We will not generate an error since OpenGL command arguments aren't error-checked until the command is actually executed (not when they're compiled). But if we run out of memory, GL_OUT_OF_MEMORY will be recorded.
References _mesa_bytes_per_pixel(), _mesa_error(), _mesa_is_bufferobj(), _mesa_unpack_image(), _mesa_validate_pbo_access(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
Referenced by save_Bitmap(), save_DrawPixels(), save_PolygonStipple(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexSubImage1D(), save_TexSubImage2D(), and save_TexSubImage3D().
Variable Documentation
InstSize
GLuint InstSize[OPCODE_END_OF_LIST+1] static
Number of nodes of storage needed for each instruction.
Sizes for dynamically allocated opcodes are stored in the context struct.
Referenced by _mesa_delete_list(), _mesa_init_display_list(), dlist_alloc(), execute_list(), is_bitmap_list(), and print_list().