Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
dlopen.h File Reference
Typedefs
typedef void(* GenericFunc) (void)
Wrapper functions for dlopen(), dlsym(), dlclose().
Functions
static void * _mesa_dlopen (const char *libname, int flags)
Wrapper for dlopen().
static GenericFunc _mesa_dlsym (void *handle, const char *fname)
Wrapper for dlsym() that does a cast to a generic function type, rather than a void *.
static void _mesa_dlclose (void *handle)
Wrapper for dlclose().
Typedef Documentation
GenericFunc
typedef void(* GenericFunc) (void)
Wrapper functions for dlopen(), dlsym(), dlclose().
Note that the #ifdef tests for various environments should be expanded.
Function Documentation
_mesa_dlclose()
static void _mesa_dlclose (void * handle) inline static
Wrapper for dlclose().
References void.
Referenced by _mesa_init_texture_s3tc().
_mesa_dlopen()
static void* _mesa_dlopen (const char * libname, int flags) inline static
Wrapper for dlopen().
Note that 'flags' isn't used at this time.
Referenced by _mesa_init_texture_s3tc().
_mesa_dlsym()
static GenericFunc _mesa_dlsym (void * handle, const char * fname) inline static
Wrapper for dlsym() that does a cast to a generic function type, rather than a void *.
This reduces the number of warnings that are generated.
Referenced by _mesa_init_texture_s3tc().