Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
drawtex.c File Reference
#include "main/drawtex.h"
#include "main/state.h"
#include "main/imports.h"
#include "main/mtypes.h"
Functions
static void draw_texture (struct gl_context *ctx, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
void GLAPIENTRY _mesa_DrawTexfOES (GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
void GLAPIENTRY _mesa_DrawTexfvOES (const GLfloat *coords)
void GLAPIENTRY _mesa_DrawTexiOES (GLint x, GLint y, GLint z, GLint width, GLint height)
void GLAPIENTRY _mesa_DrawTexivOES (const GLint *coords)
void GLAPIENTRY _mesa_DrawTexsOES (GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
void GLAPIENTRY _mesa_DrawTexsvOES (const GLshort *coords)
void GLAPIENTRY _mesa_DrawTexx (GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
void GLAPIENTRY _mesa_DrawTexxv (const GLfixed *coords)
Function Documentation
_mesa_DrawTexfOES()
void GLAPIENTRY _mesa_DrawTexfOES (GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_DrawTexxOES().
_mesa_DrawTexfvOES()
void GLAPIENTRY _mesa_DrawTexfvOES (const GLfloat * coords)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_DrawTexxvOES().
_mesa_DrawTexiOES()
void GLAPIENTRY _mesa_DrawTexiOES (GLint x, GLint y, GLint z, GLint width, GLint height)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DrawTexivOES()
void GLAPIENTRY _mesa_DrawTexivOES (const GLint * coords)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DrawTexsOES()
void GLAPIENTRY _mesa_DrawTexsOES (GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DrawTexsvOES()
void GLAPIENTRY _mesa_DrawTexsvOES (const GLshort * coords)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DrawTexx()
void GLAPIENTRY _mesa_DrawTexx (GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
References draw_texture(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DrawTexxv()
void GLAPIENTRY _mesa_DrawTexxv (const GLfixed * coords)
References draw_texture(), and GET_CURRENT_CONTEXT.
draw_texture()
static void draw_texture (struct gl_context * ctx, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height) static
References _mesa_error(), _mesa_set_vp_override(), _mesa_update_state(), dd_function_table::DrawTex, gl_context::Driver, gl_context::Extensions, GLAPIENTRY, gl_context::NewState, and gl_extensions::OES_draw_texture.
Referenced by _mesa_DrawTexfOES(), _mesa_DrawTexfvOES(), _mesa_DrawTexiOES(), _mesa_DrawTexivOES(), _mesa_DrawTexsOES(), _mesa_DrawTexsvOES(), _mesa_DrawTexx(), and _mesa_DrawTexxv().