Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
drawpix.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_DrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_CopyPixels (GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLenum type)
void GLAPIENTRY _mesa_Bitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap)
Function Documentation
_mesa_Bitmap()
void GLAPIENTRY _mesa_Bitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap)
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_feedback_token(), _mesa_feedback_vertex(), _mesa_flush(), _mesa_is_bufferobj(), _mesa_valid_to_render(), _mesa_validate_pbo_access(), DEBUG_ALWAYS_FLUSH, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, IFLOOR(), MESA_DEBUG_FLAGS, and x.
_mesa_CopyPixels()
void GLAPIENTRY _mesa_CopyPixels (GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLenum type)
References _mesa_debug(), _mesa_dest_buffer_exists(), _mesa_enum_to_string(), _mesa_error(), _mesa_feedback_token(), _mesa_feedback_vertex(), _mesa_flush(), _mesa_is_user_fbo(), _mesa_set_vp_override(), _mesa_source_buffer_exists(), _mesa_valid_to_render(), DEBUG_ALWAYS_FLUSH, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, IROUND(), MESA_DEBUG_FLAGS, MESA_VERBOSE, and VERBOSE_API.
_mesa_DrawPixels()
void GLAPIENTRY _mesa_DrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References _mesa_check_disallowed_mapping(), _mesa_debug(), _mesa_dest_buffer_exists(), _mesa_enum_to_string(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_feedback_token(), _mesa_feedback_vertex(), _mesa_flush(), _mesa_is_bufferobj(), _mesa_is_enum_format_integer(), _mesa_set_vp_override(), _mesa_valid_to_render(), _mesa_validate_pbo_access(), DEBUG_ALWAYS_FLUSH, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, IROUND(), MESA_DEBUG_FLAGS, MESA_VERBOSE, VERBOSE_API, and x.