Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
enable.c File Reference
Enable/disable/query GL capabilities.
#include "glheader.h"
#include "clip.h"
#include "context.h"
#include "debug_output.h"
#include "enable.h"
#include "errors.h"
#include "light.h"
#include "mtypes.h"
#include "enums.h"
#include "api_arrayelt.h"
#include "texstate.h"
Macros
#define CHECK_EXTENSION(EXTNAME, CAP)
#define CHECK_EXTENSION(EXTNAME, CAP)
#define CHECK_EXTENSION2(EXT1, EXT2, CAP)
#define CHECK_EXTENSION(EXTNAME)
#define CHECK_EXTENSION2(EXT1, EXT2)
Functions
static void update_derived_primitive_restart_state (struct gl_context *ctx)
static void client_state (struct gl_context *ctx, GLenum cap, GLboolean state)
Helper to enable/disable client-side state.
void GLAPIENTRY _mesa_EnableClientState (GLenum cap)
Enable GL capability.
void GLAPIENTRY _mesa_DisableClientState (GLenum cap)
Disable GL capability.
static struct gl_texture_unit * get_texcoord_unit (struct gl_context *ctx)
Return pointer to current texture unit for setting/getting coordinate state.
static GLboolean enable_texture (struct gl_context *ctx, GLboolean state, GLbitfield texBit)
Helper function to enable or disable a texture target.
void _mesa_set_multisample (struct gl_context *ctx, GLboolean state)
Helper function to enable or disable GL_MULTISAMPLE, skipping the check for whether the API supports it (GLES doesn't).
void _mesa_set_framebuffer_srgb (struct gl_context *ctx, GLboolean state)
Helper function to enable or disable GL_FRAMEBUFFER_SRGB, skipping the check for whether the API supports it (GLES doesn't).
void _mesa_set_enable (struct gl_context *ctx, GLenum cap, GLboolean state)
Helper function to enable or disable state.
void GLAPIENTRY _mesa_Enable (GLenum cap)
Enable GL capability.
void GLAPIENTRY _mesa_Disable (GLenum cap)
Disable GL capability.
void _mesa_set_enablei (struct gl_context *ctx, GLenum cap, GLuint index, GLboolean state)
Enable/disable an indexed state var.
void GLAPIENTRY _mesa_Disablei (GLenum cap, GLuint index)
void GLAPIENTRY _mesa_Enablei (GLenum cap, GLuint index)
GLboolean GLAPIENTRY _mesa_IsEnabledi (GLenum cap, GLuint index)
static GLboolean is_texture_enabled (struct gl_context *ctx, GLbitfield bit)
Helper function to determine whether a texture target is enabled.
GLboolean GLAPIENTRY _mesa_IsEnabled (GLenum cap)
Return simple enable/disable state.
Detailed Description
Enable/disable/query GL capabilities.
Macro Definition Documentation
CHECK_EXTENSION [1/3]
#define CHECK_EXTENSION (EXTNAME, CAP)
Value:
if (!ctx->Extensions.EXTNAME) {                                 \
      goto invalid_enum_error;                                          \
   }
Referenced by _mesa_IsEnabled(), and _mesa_set_enable().
CHECK_EXTENSION [2/3]
#define CHECK_EXTENSION (EXTNAME, CAP)
Value:
if (!ctx->Extensions.EXTNAME) {                                 \
      goto invalid_enum_error;                                          \
   }
CHECK_EXTENSION [3/3]
#define CHECK_EXTENSION (EXTNAME)
Value:
if (!ctx->Extensions.EXTNAME) {                 \
      goto invalid_enum_error;                          \
   }
CHECK_EXTENSION2 [1/2]
#define CHECK_EXTENSION2 (EXT1, EXT2, CAP)
Value:
if (!ctx->Extensions.EXT1 && !ctx->Extensions.EXT2) {           \
      goto invalid_enum_error;                                          \
   }
Referenced by _mesa_IsEnabled(), and _mesa_set_enable().
CHECK_EXTENSION2 [2/2]
#define CHECK_EXTENSION2 (EXT1, EXT2)
Value:
if (!ctx->Extensions.EXT1 && !ctx->Extensions.EXT2) {   \
      goto invalid_enum_error;                                  \
   }
Function Documentation
_mesa_Disable()
void GLAPIENTRY _mesa_Disable (GLenum cap)
Disable GL capability.
Called by glDisable()
Parameters
cap state to disable.
References _mesa_set_enable(), and GET_CURRENT_CONTEXT.
_mesa_DisableClientState()
void GLAPIENTRY _mesa_DisableClientState (GLenum cap)
Disable GL capability.
Parameters
cap state to enable/disable.
Get's the current context, assures that we're outside glBegin()/glEnd() and calls client_state().
References client_state(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_InterleavedArrays().
_mesa_Disablei()
void GLAPIENTRY _mesa_Disablei (GLenum cap, GLuint index)
References _mesa_set_enablei(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Enable()
void GLAPIENTRY _mesa_Enable (GLenum cap)
Enable GL capability.
Called by glEnable()
Parameters
cap state to enable.
References _mesa_set_enable(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_EnableClientState()
void GLAPIENTRY _mesa_EnableClientState (GLenum cap)
Enable GL capability.
Parameters
cap state to enable/disable.
Get's the current context, assures that we're outside glBegin()/glEnd() and calls client_state().
References client_state(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_InterleavedArrays().
_mesa_Enablei()
void GLAPIENTRY _mesa_Enablei (GLenum cap, GLuint index)
References _mesa_set_enablei(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_IsEnabled()
GLboolean GLAPIENTRY _mesa_IsEnabled (GLenum cap)
Return simple enable/disable state.
Parameters
cap state variable to query.
Returns the state of the specified capability from the current GL context. For the capabilities associated with extensions verifies that those extensions are effectively present before reporting.
References _mesa_enum_to_string(), _mesa_error(), _mesa_get_debug_state_int(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_is_gles31(), API_OPENGL_COMPAT, API_OPENGLES, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, CHECK_EXTENSION, CHECK_EXTENSION2, GET_CURRENT_CONTEXT, get_texcoord_unit(), GL_POINT_SIZE_ARRAY_OES, GL_TEXTURE_EXTERNAL_OES, GL_TEXTURE_GEN_STR_OES, GLuint, is_texture_enabled(), S_BIT, STR_BITS, gl_texture_unit::TexGenEnabled, TEXTURE_1D_BIT, TEXTURE_2D_BIT, TEXTURE_3D_BIT, TEXTURE_CUBE_BIT, TEXTURE_EXTERNAL_BIT, and TEXTURE_RECT_BIT.
Referenced by find_custom_value().
_mesa_IsEnabledi()
GLboolean GLAPIENTRY _mesa_IsEnabledi (GLenum cap, GLuint index)
References _mesa_enum_to_string(), _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and GET_CURRENT_CONTEXT.
_mesa_set_enable()
void _mesa_set_enable (struct gl_context * ctx, GLenum cap, GLboolean state)
Helper function to enable or disable state.
Parameters
ctx GL context.
cap the state to enable/disable
state whether to enable or disable the specified capability.
Updates the current context and flushes the vertices as needed. For capabilities associated with extensions it verifies that those extensions are effectivly present before updating. Notifies the driver via dd_function_table::Enable.
References gl_stencil_attrib::_BackFace, gl_light_attrib::_EnabledLights, _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_is_gles31(), _mesa_set_debug_state_int(), _mesa_set_framebuffer_srgb(), _mesa_set_multisample(), _mesa_update_clip_plane(), _mesa_update_color_material(), _NEW_COLOR, _NEW_DEPTH, _NEW_EVAL, _NEW_FOG, _NEW_LIGHT, _NEW_LINE, _NEW_MULTISAMPLE, _NEW_POINT, _NEW_POLYGON, _NEW_PROGRAM, _NEW_SCISSOR, _NEW_STENCIL, _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, _NEW_TRANSFORM, gl_colorbuffer_attrib::AlphaEnabled, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_ES3_compatibility, gl_context::Array, gl_context::ATIFragmentShader, gl_current_attrib::Attrib, gl_eval_attrib::AutoNormal, gl_colorbuffer_attrib::BlendCoherent, gl_colorbuffer_attrib::BlendEnabled, gl_depthbuffer_attrib::BoundsTest, CHECK_EXTENSION, CHECK_EXTENSION2, client_state(), gl_transform_attrib::ClipPlanesEnabled, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_light_attrib::ColorMaterialEnabled, gl_fog_attrib::ColorSumEnabled, gl_context::Const, gl_texture_attrib::CubeMapSeamless, gl_polygon_attrib::CullFlag, gl_context::Current, gl_context::Depth, gl_transform_attrib::DepthClamp, gl_colorbuffer_attrib::DitherFlag, gl_context::Driver, gl_context::DriverFlags, dd_function_table::Enable, enable_texture(), gl_light::Enabled, gl_fog_attrib::Enabled, gl_light_attrib::Enabled, gl_stencil_attrib::Enabled, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, gl_ati_fragment_shader_state::Enabled, gl_scissor_attrib::EnableFlags, gl_context::Eval, gl_context::Extensions, FLUSH_CURRENT, FLUSH_VERTICES, gl_context::Fog, gl_context::FragmentProgram, get_texcoord_unit(), GL_POINT_SIZE_ARRAY_OES, GL_TEXTURE_EXTERNAL_OES, GL_TEXTURE_GEN_STR_OES, GLAPIENTRY, GLuint, gl_colorbuffer_attrib::IndexLogicOpEnabled, gl_context::IntelConservativeRasterization, gl_light_attrib::Light, gl_context::Light, gl_context::Line, gl_eval_attrib::Map1Color4, gl_eval_attrib::Map1Index, gl_eval_attrib::Map1Normal, gl_eval_attrib::Map1TextureCoord1, gl_eval_attrib::Map1TextureCoord2, gl_eval_attrib::Map1TextureCoord3, gl_eval_attrib::Map1TextureCoord4, gl_eval_attrib::Map1Vertex3, gl_eval_attrib::Map1Vertex4, gl_eval_attrib::Map2Color4, gl_eval_attrib::Map2Index, gl_eval_attrib::Map2Normal, gl_eval_attrib::Map2TextureCoord1, gl_eval_attrib::Map2TextureCoord2, gl_eval_attrib::Map2TextureCoord3, gl_eval_attrib::Map2TextureCoord4, gl_eval_attrib::Map2Vertex3, gl_eval_attrib::Map2Vertex4, gl_constants::MaxClipPlanes, gl_constants::MaxDrawBuffers, gl_constants::MaxViewports, MESA_VERBOSE, gl_context::Multisample, gl_context::NewDriverState, gl_driver_flags::NewIntelConservativeRasterization, gl_driver_flags::NewRasterizerDiscard, gl_context::NewState, gl_transform_attrib::Normalize, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_context::Point, gl_vertex_program_state::PointSizeEnabled, gl_point_attrib::PointSprite, gl_context::Polygon, gl_array_attrib::PrimitiveRestart, gl_array_attrib::PrimitiveRestartFixedIndex, gl_context::RasterDiscard, gl_transform_attrib::RasterPositionUnclipped, gl_transform_attrib::RescaleNormals, S_BIT, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleMask, gl_multisample_attrib::SampleShading, gl_context::Scissor, gl_line_attrib::SmoothFlag, gl_point_attrib::SmoothFlag, gl_polygon_attrib::SmoothFlag, gl_context::Stencil, gl_line_attrib::StippleFlag, gl_polygon_attrib::StippleFlag, STR_BITS, gl_depthbuffer_attrib::Test, gl_stencil_attrib::TestTwoSide, gl_texture_unit::TexGenEnabled, gl_context::Texture, TEXTURE_1D_BIT, TEXTURE_2D_BIT, TEXTURE_3D_BIT, TEXTURE_CUBE_BIT, TEXTURE_EXTERNAL_BIT, TEXTURE_RECT_BIT, gl_context::Transform, gl_vertex_program_state::TwoSideEnabled, update_derived_primitive_restart_state(), VERBOSE_API, gl_context::Version, and gl_context::VertexProgram.
Referenced by _mesa_Disable(), _mesa_Enable(), _mesa_PopAttrib(), pop_enable_group(), and pop_texture_group().
_mesa_set_enablei()
void _mesa_set_enablei (struct gl_context * ctx, GLenum cap, GLuint index, GLboolean state)
Enable/disable an indexed state var.
References _mesa_enum_to_string(), _mesa_error(), _NEW_COLOR, _NEW_SCISSOR, gl_colorbuffer_attrib::BlendEnabled, gl_context::Color, gl_context::Const, gl_scissor_attrib::EnableFlags, gl_extensions::EXT_draw_buffers2, gl_context::Extensions, FLUSH_VERTICES, GLAPIENTRY, gl_constants::MaxDrawBuffers, gl_constants::MaxViewports, and gl_context::Scissor.
Referenced by _mesa_Disablei(), _mesa_Enablei(), _mesa_PopAttrib(), and pop_enable_group().
_mesa_set_framebuffer_srgb()
void _mesa_set_framebuffer_srgb (struct gl_context * ctx, GLboolean state)
Helper function to enable or disable GL_FRAMEBUFFER_SRGB, skipping the check for whether the API supports it (GLES doesn't).
References _NEW_BUFFERS, gl_context::Color, gl_context::Driver, dd_function_table::Enable, FLUSH_VERTICES, and gl_colorbuffer_attrib::sRGBEnabled.
Referenced by _mesa_set_enable().
_mesa_set_multisample()
void _mesa_set_multisample (struct gl_context * ctx, GLboolean state)
Helper function to enable or disable GL_MULTISAMPLE, skipping the check for whether the API supports it (GLES doesn't).
References _NEW_MULTISAMPLE, gl_context::Driver, dd_function_table::Enable, gl_multisample_attrib::Enabled, FLUSH_VERTICES, and gl_context::Multisample.
Referenced by _mesa_set_enable().
client_state()
static void client_state (struct gl_context * ctx, GLenum cap, GLboolean state) static
Helper to enable/disable client-side state.
References _ae_invalidate_state(), gl_vertex_array_object::_Enabled, _mesa_enum_to_string(), _mesa_error(), _NEW_ARRAY, _NEW_PROGRAM, gl_array_attrib::ActiveTexture, gl_context::Array, gl_context::Driver, dd_function_table::Enable, gl_array_attributes::Enabled, gl_context::Extensions, FLUSH_VERTICES, GL_POINT_SIZE_ARRAY_OES, GLAPIENTRY, gl_vertex_array_object::NewArrays, gl_extensions::NV_primitive_restart, gl_vertex_program_state::PointSizeEnabled, gl_array_attrib::PrimitiveRestart, update_derived_primitive_restart_state(), gl_array_attrib::VAO, gl_vertex_array_object::VertexAttrib, and gl_context::VertexProgram.
Referenced by _mesa_DisableClientState(), _mesa_EnableClientState(), and _mesa_set_enable().
enable_texture()
static GLboolean enable_texture (struct gl_context * ctx, GLboolean state, GLbitfield texBit) static
Helper function to enable or disable a texture target.
Parameters
bit one of the TEXTURE_x_BIT values
Returns
GL_TRUE if state is changing or GL_FALSE if no change
References _mesa_get_current_tex_unit(), _NEW_TEXTURE_STATE, gl_texture_unit::Enabled, and FLUSH_VERTICES.
Referenced by _mesa_set_enable().
get_texcoord_unit()
static struct gl_texture_unit* get_texcoord_unit (struct gl_context * ctx) static
Return pointer to current texture unit for setting/getting coordinate state.
Note that we'll set GL_INVALID_OPERATION and return NULL if the active texture unit is higher than the number of supported coordinate units.
References _mesa_error(), gl_context::Const, gl_texture_attrib::CurrentUnit, gl_constants::MaxTextureCoordUnits, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_IsEnabled(), and _mesa_set_enable().
is_texture_enabled()
static GLboolean is_texture_enabled (struct gl_context * ctx, GLbitfield bit) static
Helper function to determine whether a texture target is enabled.
References gl_texture_attrib::CurrentUnit, gl_texture_unit::Enabled, GLAPIENTRY, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_IsEnabled().
update_derived_primitive_restart_state()
static void update_derived_primitive_restart_state (struct gl_context * ctx) static
References gl_array_attrib::_PrimitiveRestart, gl_context::Array, gl_array_attrib::PrimitiveRestart, and gl_array_attrib::PrimitiveRestartFixedIndex.
Referenced by _mesa_set_enable(), and client_state().