Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
enums.h File Reference
Enumeration name/number lookup functions.
Functions
const char * _mesa_enum_to_string (int nr)
const char * _mesa_lookup_prim_by_nr (unsigned nr)
Detailed Description
Enumeration name/number lookup functions.
Function Documentation
_mesa_enum_to_string()
const char* _mesa_enum_to_string (int nr)
Referenced by _legal_parameters(), _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_BeginConditionalRender(), _mesa_BeginQueryIndexed(), _mesa_BindBuffer(), _mesa_BindBufferBase(), _mesa_BindBufferRange(), _mesa_BindBuffersBase(), _mesa_BindBuffersRange(), _mesa_BindImageTextures(), _mesa_BindTexture(), _mesa_BindTextureUnit(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_blit_framebuffer(), _mesa_BlitFramebuffer(), _mesa_BlitNamedFramebuffer(), _mesa_buffer_data(), _mesa_buffer_sub_data(), _mesa_check_conditional_render(), _mesa_CheckFramebufferStatus(), _mesa_CheckNamedFramebufferStatus(), _mesa_choose_tex_format(), _mesa_choose_texture_format(), _mesa_ClampColor(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_ClientActiveTexture(), _mesa_ClipControl(), _mesa_ColorMaterial(), _mesa_compute_component_mapping(), _mesa_copy_texture_sub_image(), _mesa_CopyImageSubData(), _mesa_CopyPixels(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), _mesa_CreateQueries(), _mesa_CreateShader(), _mesa_CullFace(), _mesa_DepthFunc(), _mesa_DiscardFramebufferEXT(), _mesa_DrawPixels(), _mesa_EndFragmentShaderATI(), _mesa_EndQueryIndexed(), _mesa_error(), _mesa_framebuffer_texture(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_FrontFace(), _mesa_generate_texture_mipmap(), _mesa_GenerateMipmap(), _mesa_GenerateTextureMipmap(), _mesa_get_framebuffer_attachment_parameter(), _mesa_GetError(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetPointerv(), _mesa_GetProgramInterfaceiv(), _mesa_GetProgramPipelineiv(), _mesa_GetProgramResourceIndex(), _mesa_GetProgramResourceiv(), _mesa_GetProgramResourceLocation(), _mesa_GetProgramResourceLocationIndex(), _mesa_GetProgramResourceName(), _mesa_GetQueryIndexediv(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_Hint(), _mesa_InvalidateFramebuffer(), _mesa_InvalidateSubFramebuffer(), _mesa_IsEnabled(), _mesa_IsEnabledi(), _mesa_LogicOp(), _mesa_map_buffer_range(), _mesa_NewList(), _mesa_pack_depth_span(), _mesa_PassTexCoordATI(), _mesa_PolygonMode(), _mesa_PopAttrib(), _mesa_PopMatrix(), _mesa_print_arrays(), _mesa_print_framebuffer(), _mesa_print_texunit_state(), _mesa_ProgramParameteri(), _mesa_PushMatrix(), _mesa_QueryCounter(), _mesa_ReadnPixelsARB(), _mesa_RenderMode(), _mesa_SampleMapATI(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_ShadeModel(), _mesa_TexEnvfv(), _mesa_TexGenfv(), _mesa_TextureView(), _mesa_WindowRectanglesEXT(), check_blend_func_error(), check_clear_tex_image(), check_extra(), check_layered_texture_target(), check_textarget(), check_texture_target(), client_state(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), compressed_texture_error_check(), copyteximage(), copytexsubimage_error_check(), copytexture_error_check(), create_shader(), draw_buffer(), draw_buffers(), dump_renderbuffer(), enum_string(), find_value(), find_value_indexed(), flush_delayed_errors(), framebuffer_renderbuffer(), framebuffer_texture_with_dims(), get_buffer_parameter(), get_label_pointer(), get_map_idx(), get_programiv(), get_query_object(), get_render_buffer_parameteriv(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), invalidate_framebuffer_storage(), match_pair_inst(), mesa_bufferiv(), prepare_target(), print_list(), read_buffer(), renderbuffer_storage(), renderbuffer_storage_named(), renderbuffer_storage_target(), set_tex_parameterf(), set_tex_parameteri(), target_valid(), tex_storage_error_check(), teximage(), texstorage(), texsubimage(), texsubimage_error_check(), texture_buffer_range(), texture_error_check(), texture_format_error_check_gles(), texture_image_multisample(), texturestorage(), texturesubimage(), update_array_format(), valid_elements_type(), valid_tex_level_parameteriv_target(), and validate_blend_factors().
_mesa_lookup_prim_by_nr()
const char* _mesa_lookup_prim_by_nr (unsigned nr)
Referenced by _mesa_valid_prim_mode().