Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
errors.c File Reference
Mesa debugging and error handling functions.
#include <stdarg.h>
#include <stdio.h>
#include "errors.h"
#include "enums.h"
#include "imports.h"
#include "context.h"
#include "debug_output.h"
Functions
static void output_if_debug (const char *prefixString, const char *outputString, GLboolean newline)
FILE * _mesa_get_log_file (void)
Return the file handle to use for debug/logging.
static void flush_delayed_errors (struct gl_context *ctx)
When a new type of error is recorded, print a message describing previous errors which were accumulated.
void _mesa_warning (struct gl_context *ctx, const char *fmtString,...)
Report a warning (a recoverable error condition) to stderr if either DEBUG is defined or the MESA_DEBUG env var is set.
void _mesa_problem (const struct gl_context *ctx, const char *fmtString,...)
Report an internal implementation problem.
static GLboolean should_output (struct gl_context *ctx, GLenum error, const char *fmtString)
void _mesa_gl_vdebug (struct gl_context *ctx, GLuint *id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char *fmtString, va_list args)
void _mesa_gl_debug (struct gl_context *ctx, GLuint *id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char *fmtString,...)
void _mesa_error (struct gl_context *ctx, GLenum error, const char *fmtString,...)
Record an OpenGL state error.
void _mesa_error_no_memory (const char *caller)
void _mesa_debug (const struct gl_context *ctx, const char *fmtString,...)
Report debug information.
void _mesa_log (const char *fmtString,...)
void _mesa_shader_debug (struct gl_context *ctx, GLenum type, GLuint *id, const char *msg)
Report debug information from the shader compiler via GL_ARB_debug_output.
Variables
static FILE * LogFile = NULL
Detailed Description
Mesa debugging and error handling functions.
Function Documentation
_mesa_debug()
void _mesa_debug (const struct gl_context * ctx, const char * fmtString, ...)
Report debug information.
Print error message to stderr via fprintf(). No-op if DEBUG mode not enabled.
Parameters
ctx GL context.
fmtString printf()-style format string, followed by optional args.
References _mesa_vsnprintf(), MAX_DEBUG_MESSAGE_LENGTH, output_if_debug(), and void.
Referenced by _mesa_ActiveShaderProgram(), _mesa_ActiveStencilFaceEXT(), _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_AreTexturesResident(), _mesa_BeginFragmentShaderATI(), _mesa_BeginQueryIndexed(), _mesa_BindBuffer(), _mesa_BindBufferBase(), _mesa_BindBufferRange(), _mesa_BindBuffersBase(), _mesa_BindBuffersRange(), _mesa_BindProgramPipeline(), _mesa_BindTexture(), _mesa_BindTextureUnit(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_BlitFramebuffer(), _mesa_BlitNamedFramebuffer(), _mesa_buffer_data(), _mesa_CallList(), _mesa_CallLists(), _mesa_CheckFramebufferStatus(), _mesa_Clear(), _mesa_ClearDepth(), _mesa_ClearStencil(), _mesa_ClientActiveTexture(), _mesa_ClipControl(), _mesa_ColorMask(), _mesa_ColorMaski(), _mesa_ColorMaterial(), _mesa_compile_shader(), _mesa_CompileShader(), _mesa_copy_texture_sub_image(), _mesa_CopyImageSubData(), _mesa_CopyPixels(), _mesa_CreateProgram(), _mesa_CreateProgramPipelines(), _mesa_CreateShader(), _mesa_CullFace(), _mesa_DeleteObjectARB(), _mesa_DeletePerfMonitorsAMD(), _mesa_DeleteProgramPipelines(), _mesa_DeleteQueries(), _mesa_DeleteTextures(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthMask(), _mesa_DepthRange(), _mesa_DepthRangeArrayfvOES(), _mesa_DepthRangeArrayv(), _mesa_DepthRangeIndexed(), _mesa_DispatchCompute(), _mesa_DispatchComputeGroupSizeARB(), _mesa_DispatchComputeIndirect(), _mesa_DrawPixels(), _mesa_EndList(), _mesa_EndQueryIndexed(), _mesa_FrontFace(), _mesa_GenPerfMonitorsAMD(), _mesa_GenProgramPipelines(), _mesa_GetError(), _mesa_GetGraphicsResetStatusARB(), _mesa_GetnPolygonStippleARB(), _mesa_GetPointerv(), _mesa_GetProgramInterfaceiv(), _mesa_GetProgramPipelineInfoLog(), _mesa_GetProgramPipelineiv(), _mesa_GetProgramResourceIndex(), _mesa_GetProgramResourceiv(), _mesa_GetProgramResourceLocation(), _mesa_GetProgramResourceLocationIndex(), _mesa_GetProgramResourceName(), _mesa_GetQueryIndexediv(), _mesa_Hint(), _mesa_InvalidateTexImage(), _mesa_InvalidateTexSubImage(), _mesa_IsProgramPipeline(), _mesa_IsQuery(), _mesa_IsTexture(), _mesa_LineStipple(), _mesa_LineWidth(), _mesa_link_program(), _mesa_LinkProgram(), _mesa_LoadIdentity(), _mesa_LoadMatrixf(), _mesa_LockArraysEXT(), _mesa_LogicOp(), _mesa_make_current(), _mesa_make_extension_string(), _mesa_MultMatrixf(), _mesa_NewList(), _mesa_notifySwapBuffers(), _mesa_Ortho(), _mesa_PassTexCoordATI(), _mesa_PolygonMode(), _mesa_PolygonOffset(), _mesa_PolygonOffsetClampEXT(), _mesa_PolygonStipple(), _mesa_PopAttrib(), _mesa_PopMatrix(), _mesa_print_info(), _mesa_print_state(), _mesa_PrioritizeTextures(), _mesa_ProvokingVertex(), _mesa_PushAttrib(), _mesa_PushMatrix(), _mesa_QueryCounter(), _mesa_ReadnPixelsARB(), _mesa_RenderMode(), _mesa_SampleMapATI(), _mesa_Scissor(), _mesa_set_enable(), _mesa_ShadeModel(), _mesa_StencilFunc(), _mesa_StencilFuncSeparate(), _mesa_StencilFuncSeparateATI(), _mesa_StencilMask(), _mesa_StencilMaskSeparate(), _mesa_StencilOp(), _mesa_StencilOpSeparate(), _mesa_TexEnvfv(), _mesa_TexGenfv(), _mesa_TextureView(), _mesa_UnlockArraysEXT(), _mesa_update_material(), _mesa_UseProgram(), _mesa_UseProgramStages(), _mesa_ValidateProgramPipeline(), _mesa_Viewport(), _mesa_ViewportArrayv(), _mesa_WindowRectanglesEXT(), _mesa_write_renderbuffer_image(), att_incomplete(), copyteximage(), create_buffers(), create_queries(), create_samplers(), create_textures(), debug_print_entry(), draw_buffer(), fbo_incomplete(), get_compressed_texture_image(), get_query_object(), get_texture_image(), incomplete(), one_time_init(), problem(), read_buffer(), renderbuffer_storage_named(), renderbuffer_storage_target(), ScissorIndexed(), teximage(), texstorage(), texsubimage(), texture_image_multisample(), texturestorage(), texturesubimage(), and ViewportIndexedf().
_mesa_error()
void _mesa_error (struct gl_context * ctx, GLenum error, const char * fmtString, ...)
Record an OpenGL state error.
These usually occur when the user passes invalid parameters to a GL function.
If debugging is enabled (either at compile-time via the DEBUG macro, or run-time via the MESA_DEBUG environment variable), report the error with _mesa_debug().
Parameters
ctx the GL context.
error the error value.
fmtString printf() style format string, followed by optional args
References _mesa_debug_get_id(), _mesa_debug_is_message_enabled(), _mesa_enum_to_string(), _mesa_log_msg(), _mesa_record_error(), _mesa_snprintf(), _mesa_vsnprintf(), gl_context::Debug, gl_context::DebugMutex, GLuint, MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SOURCE_API, MESA_DEBUG_TYPE_ERROR, output_if_debug(), and should_output().
Referenced by _context_lost_GetQueryObjectuiv(), _context_lost_GetSynciv(), _es_TexGenf(), _es_TexGenfv(), _legal_parameters(), _mesa_Accum(), _mesa_active_program(), _mesa_ActiveShaderProgram(), _mesa_ActiveStencilFaceEXT(), _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_AreTexturesResident(), _mesa_BeginConditionalRender(), _mesa_BeginFragmentShaderATI(), _mesa_BeginPerfMonitorAMD(), _mesa_BeginPerfQueryINTEL(), _mesa_BeginQueryIndexed(), _mesa_BeginTransformFeedback(), _mesa_bind_buffer_base_transform_feedback(), _mesa_bind_buffer_range_transform_feedback(), _mesa_BindBuffer(), _mesa_BindBufferBase(), _mesa_BindBufferOffsetEXT(), _mesa_BindBufferRange(), _mesa_BindBuffersBase(), _mesa_BindBuffersRange(), _mesa_BindFragmentShaderATI(), _mesa_BindImageTexture(), _mesa_BindImageTextures(), _mesa_BindProgramARB(), _mesa_BindProgramPipeline(), _mesa_BindSampler(), _mesa_BindSamplers(), _mesa_BindTexture(), _mesa_BindTextures(), _mesa_BindTextureUnit(), _mesa_BindTransformFeedback(), _mesa_BindVertexBuffer(), _mesa_BindVertexBuffers(), _mesa_Bitmap(), _mesa_BlendBarrier(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparateiARB(), _mesa_blit_framebuffer(), _mesa_buffer_data(), _mesa_buffer_storage(), _mesa_buffer_sub_data(), _mesa_CallList(), _mesa_CallLists(), _mesa_CheckFramebufferStatus(), _mesa_CheckNamedFramebufferStatus(), _mesa_ClampColor(), _mesa_Clear(), _mesa_clear_accum_buffer(), _mesa_clear_buffer_sub_data(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferSubData_sw(), _mesa_ClearBufferuiv(), _mesa_ClearTexSubImage(), _mesa_ClientActiveTexture(), _mesa_ClientWaitSync(), _mesa_ClipControl(), _mesa_ClipPlane(), _mesa_ColorMaski(), _mesa_ColorSubTable(), _mesa_ColorTable(), _mesa_ColorTableParameterfv(), _mesa_ColorTableParameteriv(), _mesa_compile_error(), _mesa_compressed_pixel_storage_error_check(), _mesa_CompressedTextureSubImage3D(), _mesa_ConvolutionFilter1D(), _mesa_ConvolutionFilter2D(), _mesa_ConvolutionParameterf(), _mesa_ConvolutionParameterfv(), _mesa_ConvolutionParameteri(), _mesa_ConvolutionParameteriv(), _mesa_copy_buffer_sub_data(), _mesa_CopyColorSubTable(), _mesa_CopyColorTable(), _mesa_CopyConvolutionFilter1D(), _mesa_CopyConvolutionFilter2D(), _mesa_CopyImageSubData(), _mesa_CopyPixels(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), _mesa_CreatePerfQueryINTEL(), _mesa_CreateQueries(), _mesa_CreateShaderProgramv(), _mesa_CreateTextures(), _mesa_CullFace(), _mesa_DebugMessageControl(), _mesa_DeleteBuffers(), _mesa_DeleteFragmentShaderATI(), _mesa_DeleteFramebuffers(), _mesa_DeleteLists(), _mesa_DeletePerfMonitorsAMD(), _mesa_DeletePerfQueryINTEL(), _mesa_DeleteProgramPipelines(), _mesa_DeleteProgramsARB(), _mesa_DeleteQueries(), _mesa_DeleteRenderbuffers(), _mesa_DeleteSamplers(), _mesa_DeleteSync(), _mesa_DeleteTextures(), _mesa_DeleteTransformFeedbacks(), _mesa_DeleteVertexArrays(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthRangeArrayfvOES(), _mesa_DepthRangeArrayv(), _mesa_DepthRangeIndexed(), _mesa_DiscardFramebufferEXT(), _mesa_DrawPixels(), _mesa_EGLImageTargetRenderbufferStorageOES(), _mesa_EGLImageTargetTexture2DOES(), _mesa_EndConditionalRender(), _mesa_EndFragmentShaderATI(), _mesa_EndList(), _mesa_EndPerfMonitorAMD(), _mesa_EndPerfQueryINTEL(), _mesa_EndQueryIndexed(), _mesa_EndTransformFeedback(), _mesa_error_no_memory(), _mesa_FeedbackBuffer(), _mesa_FenceSync(), _mesa_flush_mapped_buffer_range(), _mesa_Fogfv(), _mesa_Fogxv(), _mesa_FragmentOpXATI(), _mesa_framebuffer_texture(), _mesa_FramebufferParameteri(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_FrontFace(), _mesa_Frustum(), _mesa_generate_texture_mipmap(), _mesa_GenerateMipmap(), _mesa_GenerateTextureMipmap(), _mesa_GenFragmentShadersATI(), _mesa_GenLists(), _mesa_GenPerfMonitorsAMD(), _mesa_GenProgramsARB(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_framebuffer_attachment_parameter(), _mesa_get_tex_image(), _mesa_GetActiveAtomicCounterBufferiv(), _mesa_GetActiveSubroutineName(), _mesa_GetActiveSubroutineUniformiv(), _mesa_GetActiveSubroutineUniformName(), _mesa_GetActiveUniformBlockiv(), _mesa_GetActiveUniformBlockName(), _mesa_GetActiveUniformName(), _mesa_GetBufferPointerv(), _mesa_GetClipPlane(), _mesa_GetColorTable(), _mesa_GetColorTableParameterfv(), _mesa_GetColorTableParameteriv(), _mesa_GetCompressedTexImage(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetCompressedTextureSubImage(), _mesa_GetConvolutionParameterfv(), _mesa_GetConvolutionParameteriv(), _mesa_GetDebugMessageLog(), _mesa_GetFirstPerfQueryIdINTEL(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetFramebufferParameteriv(), _mesa_GetHistogramParameterfv(), _mesa_GetHistogramParameteriv(), _mesa_GetInfoLogARB(), _mesa_GetInternalformati64v(), _mesa_GetInternalformativ(), _mesa_GetLightfv(), _mesa_GetLightiv(), _mesa_GetLightxv(), _mesa_GetMaterialfv(), _mesa_GetMaterialiv(), _mesa_GetMaterialxv(), _mesa_GetMinmaxParameterfv(), _mesa_GetMinmaxParameteriv(), _mesa_GetMultisamplefv(), _mesa_GetNamedBufferPointerv(), _mesa_GetNamedFramebufferParameteriv(), _mesa_GetNamedRenderbufferParameteriv(), _mesa_GetnColorTableARB(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnConvolutionFilterARB(), _mesa_GetNextPerfQueryIdINTEL(), _mesa_GetnHistogramARB(), _mesa_GetnMapdvARB(), _mesa_GetnMapfvARB(), _mesa_GetnMapivARB(), _mesa_GetnMinmaxARB(), _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_GetnSeparableFilterARB(), _mesa_GetnTexImageARB(), _mesa_GetObjectLabel(), _mesa_GetObjectParameterivAPPLE(), _mesa_GetObjectParameterivARB(), _mesa_GetObjectPtrLabel(), _mesa_GetPerfCounterInfoINTEL(), _mesa_GetPerfMonitorCounterDataAMD(), _mesa_GetPerfMonitorCounterInfoAMD(), _mesa_GetPerfMonitorCountersAMD(), _mesa_GetPerfMonitorCounterStringAMD(), _mesa_GetPerfMonitorGroupStringAMD(), _mesa_GetPerfQueryDataINTEL(), _mesa_GetPerfQueryIdByNameINTEL(), _mesa_GetPerfQueryInfoINTEL(), _mesa_GetPointerv(), _mesa_GetProgramBinary(), _mesa_GetProgramInterfaceiv(), _mesa_GetProgramivARB(), _mesa_GetProgramPipelineInfoLog(), _mesa_GetProgramPipelineiv(), _mesa_GetProgramResourceIndex(), _mesa_GetProgramResourceiv(), _mesa_GetProgramResourceLocation(), _mesa_GetProgramResourceLocationIndex(), _mesa_GetProgramResourceName(), _mesa_GetProgramStageiv(), _mesa_GetProgramStringARB(), _mesa_GetQueryIndexediv(), _mesa_GetRenderbufferParameteriv(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_GetShaderPrecisionFormat(), _mesa_GetString(), _mesa_GetStringi(), _mesa_GetSubroutineIndex(), _mesa_GetSubroutineUniformLocation(), _mesa_GetSynciv(), _mesa_GetTexEnvfv(), _mesa_GetTexEnviv(), _mesa_GetTexEnvxv(), _mesa_GetTexGendv(), _mesa_GetTexGenfv(), _mesa_GetTexGeniv(), _mesa_GetTexImage(), _mesa_GetTexParameterxv(), _mesa_GetTexSubImage_sw(), _mesa_GetTextureImage(), _mesa_GetTextureParameterfv(), _mesa_GetTextureParameterIiv(), _mesa_GetTextureParameterIuiv(), _mesa_GetTextureParameteriv(), _mesa_GetTextureSubImage(), _mesa_GetTransformFeedbacki64_v(), _mesa_GetTransformFeedbacki_v(), _mesa_GetTransformFeedbackiv(), _mesa_GetTransformFeedbackVarying(), _mesa_GetUniformBlockIndex(), _mesa_GetUniformIndices(), _mesa_GetUniformLocation(), _mesa_GetUniformSubroutineuiv(), _mesa_GetVertexArrayIndexed64iv(), _mesa_GetVertexArrayiv(), _mesa_GetVertexAttribPointerv(), _mesa_handle_bind_buffer_gen(), _mesa_Hint(), _mesa_Histogram(), _mesa_InterleavedArrays(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_InvalidateFramebuffer(), _mesa_InvalidateSubFramebuffer(), _mesa_InvalidateTexSubImage(), _mesa_IsEnabled(), _mesa_IsEnabledi(), _mesa_Lightfv(), _mesa_LightModelfv(), _mesa_LightModelxv(), _mesa_Lightxv(), _mesa_LineWidth(), _mesa_link_program(), _mesa_LoadName(), _mesa_lock_debug_state(), _mesa_LockArraysEXT(), _mesa_LogicOp(), _mesa_lookup_bufferobj_err(), _mesa_lookup_framebuffer_err(), _mesa_lookup_renderbuffer_err(), _mesa_lookup_shader_err(), _mesa_lookup_shader_program_err(), _mesa_lookup_texture_err(), _mesa_lookup_vao_err(), _mesa_map_buffer_range(), _mesa_map_validate_pbo_dest(), _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_MapGrid1f(), _mesa_MapGrid2f(), _mesa_MapNamedBuffer(), _mesa_MapNamedBufferRange(), _mesa_material_bitmask(), _mesa_Materialx(), _mesa_Materialxv(), _mesa_MatrixMode(), _mesa_MemoryBarrierByRegion(), _mesa_Minmax(), _mesa_MinSampleShading(), _mesa_multi_bind_lookup_bufferobj(), _mesa_NamedBufferPageCommitmentARB(), _mesa_NamedFramebufferParameteri(), _mesa_NamedFramebufferRenderbuffer(), _mesa_NamedFramebufferTexture(), _mesa_NewList(), _mesa_ObjectPtrLabel(), _mesa_ObjectPurgeableAPPLE(), _mesa_ObjectUnpurgeableAPPLE(), _mesa_Ortho(), _mesa_pack_depth_span(), _mesa_pack_depth_stencil_span(), _mesa_pack_stencil_span(), _mesa_PassTexCoordATI(), _mesa_PatchParameterfv(), _mesa_PatchParameteri(), _mesa_PauseTransformFeedback(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), _mesa_PixelStorei(), _mesa_PixelTransferf(), _mesa_PointParameterfv(), _mesa_PointParameterxv(), _mesa_PointSize(), _mesa_PointSizePointerOES(), _mesa_PolygonMode(), _mesa_PolygonOffsetClampEXT(), _mesa_PopAttrib(), _mesa_PopClientAttrib(), _mesa_PopDebugGroup(), _mesa_PopMatrix(), _mesa_PopName(), _mesa_PrimitiveRestartIndex(), _mesa_PrioritizeTextures(), _mesa_ProgramBinary(), _mesa_ProgramEnvParameters4fvEXT(), _mesa_ProgramLocalParameters4fvEXT(), _mesa_ProgramParameteri(), _mesa_ProgramStringARB(), _mesa_ProvokingVertex(), _mesa_PushAttrib(), _mesa_PushClientAttrib(), _mesa_PushDebugGroup(), _mesa_PushMatrix(), _mesa_PushName(), _mesa_QueryCounter(), _mesa_ReadnPixelsARB(), _mesa_RenderMode(), _mesa_ResetHistogram(), _mesa_ResetMinmax(), _mesa_resize_framebuffer(), _mesa_ResumeTransformFeedback(), _mesa_SampleMapATI(), _mesa_SampleMaski(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), _mesa_Scissor(), _mesa_ScissorArrayv(), _mesa_SelectBuffer(), _mesa_SelectPerfMonitorCountersAMD(), _mesa_SeparableFilter2D(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_SetFragmentShaderConstantATI(), _mesa_ShadeModel(), _mesa_ShaderBinary(), _mesa_ShaderSource(), _mesa_ShaderStorageBlockBinding(), _mesa_StencilFunc(), _mesa_StencilFuncSeparate(), _mesa_StencilFuncSeparateATI(), _mesa_StencilMaskSeparate(), _mesa_StencilOp(), _mesa_StencilOpSeparate(), _mesa_store_cleartexsubimage(), _mesa_store_compressed_teximage(), _mesa_store_compressed_texsubimage(), _mesa_store_teximage(), _mesa_StringMarkerGREMEDY(), _mesa_TexEnvfv(), _mesa_TexEnvx(), _mesa_TexEnvxv(), _mesa_TexGenfv(), _mesa_TexParameterxv(), _mesa_texture_parameterf(), _mesa_texture_parameteri(), _mesa_texture_parameterIiv(), _mesa_texture_parameterIuiv(), _mesa_texture_parameteriv(), _mesa_texture_storage(), _mesa_TextureBarrierNV(), _mesa_TextureParameterf(), _mesa_TextureParameterfv(), _mesa_TextureParameteri(), _mesa_TextureParameterIiv(), _mesa_TextureParameterIuiv(), _mesa_TextureParameteriv(), _mesa_TextureStorage1DEXT(), _mesa_TextureStorage2DEXT(), _mesa_TextureStorage3DEXT(), _mesa_TextureView(), _mesa_TransformFeedbackVaryings(), _mesa_UniformBlockBinding(), _mesa_UniformSubroutinesuiv(), _mesa_UnlockArraysEXT(), _mesa_unmap_buffer(), _mesa_unpack_color_index_to_rgba_float(), _mesa_unpack_depth_span(), _mesa_unpack_stencil_span(), _mesa_update_texture_renderbuffer(), _mesa_UseProgram(), _mesa_UseProgramStages(), _mesa_valid_prim_mode(), _mesa_valid_to_render(), _mesa_validate_DispatchCompute(), _mesa_validate_DispatchComputeGroupSizeARB(), _mesa_validate_DrawArraysInstanced(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), _mesa_validate_DrawTransformFeedback(), _mesa_validate_MultiDrawElements(), _mesa_validate_pbo_source(), _mesa_validate_pbo_source_compressed(), _mesa_validate_pbo_teximage(), _mesa_ValidateProgramPipeline(), _mesa_VDPAUFiniNV(), _mesa_VDPAUGetSurfaceivNV(), _mesa_VDPAUInitNV(), _mesa_VDPAUIsSurfaceNV(), _mesa_VDPAUMapSurfacesNV(), _mesa_VDPAURegisterOutputSurfaceNV(), _mesa_VDPAURegisterVideoSurfaceNV(), _mesa_VDPAUSurfaceAccessNV(), _mesa_VDPAUUnmapSurfacesNV(), _mesa_VDPAUUnregisterSurfaceNV(), _mesa_VertexAttribBinding(), _mesa_VertexAttribDivisor(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribLPointer(), _mesa_VertexAttribPointer(), _mesa_VertexBindingDivisor(), _mesa_Viewport(), _mesa_ViewportArrayv(), _mesa_WaitSync(), _mesa_WindowRectanglesEXT(), accum_or_load(), accum_return(), accum_scale_or_bias(), allocate_renderbuffer_locked(), attach_shader(), bind_atomic_buffer(), bind_atomic_buffers(), bind_buffer_base_shader_storage_buffer(), bind_buffer_base_uniform_buffer(), bind_buffer_range_shader_storage_buffer(), bind_buffer_range_uniform_buffer(), bind_buffers_check_offset_and_size(), bind_framebuffer(), bind_renderbuffer(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_vertex_array(), bind_xfb_buffers(), buffer_object_purgeable(), buffer_object_subdata_range_good(), buffer_object_unpurgeable(), buffer_page_commitment(), build_bitmap_atlas(), check_arith_arg(), check_blend_func_error(), check_clear_tex_image(), check_extra(), check_gs_query(), check_layer(), check_layered_texture_target(), check_level(), check_region_bounds(), check_tcs_query(), check_tes_query(), check_textarget(), check_texture_buffer_range(), check_texture_buffer_target(), check_texture_target(), check_valid_to_compute(), check_valid_to_render(), clear_texture_fields(), client_state(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), compressed_texture_error_check(), context_lost_nop_handler(), convert_clear_buffer_data(), copy_data(), copyteximage(), copytexsubimage_error_check(), copytexture_error_check(), create_buffers(), create_framebuffers(), create_program_pipelines(), create_queries(), create_render_buffers(), create_samplers(), create_shader(), create_textures(), create_transform_feedbacks(), detach_shader(), dimensions_error_check(), disable_vertex_array_attrib(), dlist_alloc(), draw_buffer(), draw_buffers(), draw_texture(), emit_op3fn(), enable_vertex_array_attrib(), error_check_bind_atomic_buffers(), error_check_bind_shader_storage_buffers(), error_check_bind_uniform_buffers(), error_check_bind_xfb_buffers(), error_check_subtexture_dimensions(), error_check_subtexture_negative_dimensions(), execute_list(), fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), find_value(), find_value_indexed(), framebuffer_parameteri(), framebuffer_renderbuffer(), framebuffer_texture_with_dims(), fxt1_encode(), gen_vertex_arrays(), generate_mipmap_compressed(), generate_mipmap_uncompressed(), generic_nop(), get_attached_shaders(), get_buffer(), get_buffer_object_parameteriv(), get_buffer_parameter(), get_current_attrib(), get_env_param_pointer(), get_framebuffer_parameteriv(), get_handle(), get_label_pointer(), get_local_param_pointer(), get_program_info_log(), get_programiv(), get_proxy_tex_image(), get_query_object(), get_render_buffer_parameteriv(), get_renderbuffer_parameteriv(), get_shader_info_log(), get_shader_source(), get_shaderiv(), get_tex_depth(), get_tex_depth_stencil(), get_tex_images_for_clear(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), get_tex_level_parameteriv(), get_tex_memcpy(), get_tex_obj_for_clear(), get_tex_parameterfv(), get_tex_parameteriv(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_stencil(), get_tex_ycbcr(), get_texcoord_unit(), get_texenvi(), get_texobj_by_name(), get_texobj_by_target(), get_texture_for_framebuffer(), get_texture_object_parameteriv(), get_vertex_array_attrib(), getcompressedteximage_error_check(), getteximage_error_check(), index_error(), init_array_attrib_data(), initialize_texture_fields(), invalidate_framebuffer_storage(), invalidate_tex_image_error_check(), lookup_linked_program(), lookup_transform_feedback_bufferobj_err(), lookup_transform_feedback_object_err(), map1(), map2(), mesa_bufferiv(), pbo_error_check(), prepare_target(), push_attrib(), query_error_check_index(), read_buffer(), read_depth_pixels(), read_rgba_pixels(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), register_surface(), renderbuffer_purgeable(), renderbuffer_storage(), renderbuffer_storage_named(), renderbuffer_storage_target(), renderbuffer_unpurgeable(), sampler_parameter_error_check(), save_DrawArraysInstancedARB(), save_DrawArraysInstancedBaseInstance(), save_DrawElementsInstancedARB(), save_DrawElementsInstancedBaseInstance(), save_DrawElementsInstancedBaseVertexARB(), save_DrawElementsInstancedBaseVertexBaseInstance(), save_NewList(), save_ProgramStringARB(), ScissorIndexed(), set_combiner_scale(), set_label(), set_tex_parameterf(), set_tex_parameteri(), slow_read_depth_stencil_pixels_separate(), store_pixelmap(), store_texsubimage(), target_valid(), tex_storage_error_check(), teximage(), texstorage(), texsubimage(), texsubimage_error_check(), texture_buffer_range(), texture_error_check(), texture_format_error_check_gles(), texture_image_multisample(), texture_object_purgeable(), texture_object_unpurgeable(), texturestorage(), texturesubimage(), trim_list(), unpack_image(), update_array(), update_array_format(), valid_dispatch_indirect(), valid_draw_indirect(), valid_draw_indirect_elements(), valid_draw_indirect_multi(), valid_draw_indirect_parameters(), valid_elements_type(), valid_tex_level_parameteriv_target(), valid_texstorage_ms_parameters(), validate_bind_image_texture(), validate_blend_factors(), validate_clear_buffer_format(), validate_draw_arrays(), validate_DrawElements_common(), validate_length(), validate_params(), validate_pbo_access(), validate_texture_wrap_mode(), vertex_array_attrib_binding(), vertex_array_attrib_format(), vertex_array_binding_divisor(), vertex_array_vertex_buffer(), vertex_array_vertex_buffers(), vertex_attrib_format(), and ViewportIndexedf().
_mesa_error_no_memory()
void _mesa_error_no_memory (const char * caller)
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_CreatePerfQueryINTEL(), _mesa_NewHashTable(), format_array_format_table_init(), and register_surface().
_mesa_get_log_file()
FILE* _mesa_get_log_file (void)
Return the file handle to use for debug/logging.
Defaults to stderr unless MESA_LOG_FILE is defined.
References LogFile.
Referenced by _mesa_compile_shader().
_mesa_gl_debug()
void _mesa_gl_debug (struct gl_context * ctx, GLuint * id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char * fmtString, ...)
References _mesa_gl_vdebug().
Referenced by _mesa_validate_program_pipeline(), and fbo_incomplete().
_mesa_gl_vdebug()
void _mesa_gl_vdebug (struct gl_context * ctx, GLuint * id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char * fmtString, va_list args)
References _mesa_debug_get_id(), _mesa_log_msg(), _mesa_vsnprintf(), and MAX_DEBUG_MESSAGE_LENGTH.
Referenced by _mesa_gl_debug(), and buffer_usage_warning().
_mesa_log()
void _mesa_log (const char * fmtString, ...)
References _mesa_vsnprintf(), MAX_DEBUG_MESSAGE_LENGTH, and output_if_debug().
Referenced by _mesa_compile_shader(), and debug_log_message().
_mesa_problem()
void _mesa_problem (const struct gl_context * ctx, const char * fmtString, ...)
Report an internal implementation problem.
Prints the message to stderr via fprintf().
Parameters
ctx GL context.
fmtString problem description string.
References _mesa_vsnprintf(), MAX_DEBUG_MESSAGE_LENGTH, and void.
Referenced by _mesa_accum(), _mesa_check_conditional_render(), _mesa_choose_tex_format(), _mesa_compressed_format_to_glenum(), _mesa_compute_version(), _mesa_convert_colors(), _mesa_decompress_image(), _mesa_DeleteHashTable(), _mesa_DeleteProgramsARB(), _mesa_dump_image(), _mesa_format_row_stride(), _mesa_generate_mipmap_level(), _mesa_get_current_tex_object(), _mesa_get_format_bits(), _mesa_get_framebuffer_attachment_parameter(), _mesa_get_texture_dimensions(), _mesa_GetQueryIndexediv(), _mesa_HashRemove_unlocked(), _mesa_legal_texture_dimensions(), _mesa_light(), _mesa_pack_depth_span(), _mesa_pack_stencil_span(), _mesa_PopAttrib(), _mesa_PopClientAttrib(), _mesa_print_texture(), _mesa_RasterPos(), _mesa_reference_buffer_object_(), _mesa_reference_pipeline_object_(), _mesa_reference_sampler_object_(), _mesa_reference_texobj_(), _mesa_reference_vao_(), _mesa_store_compressed_teximage(), _mesa_store_compressed_texsubimage(), _mesa_test_texobj_completeness(), _mesa_unpack_depth_span(), _mesa_unpack_stencil_span(), calculate_derived_texenv(), compute_texgen(), do_row(), do_row_3D(), execute_list(), extract_uint_indexes(), find_custom_value(), get_extension_override(), get_map_idx(), get_temp(), init_teximage_fields_ms(), legal_teximage_target(), legal_texobj_target(), legal_texsubimage_target(), proxy_target(), reference_transform_feedback_object(), renderbuffer_exists(), shading_language_version(), update_tex_combine(), and valid_texture_object().
_mesa_shader_debug()
void _mesa_shader_debug (struct gl_context * ctx, GLenum type, GLuint * id, const char * msg)
Report debug information from the shader compiler via GL_ARB_debug_output.
Parameters
ctx GL context.
type The namespace to which this message belongs.
id The message ID within the given namespace.
msg The message to output. Must be null-terminated.
References _mesa_debug_get_id(), _mesa_log_msg(), MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, and MESA_DEBUG_SOURCE_SHADER_COMPILER.
_mesa_warning()
void _mesa_warning (struct gl_context * ctx, const char * fmtString, ...)
Report a warning (a recoverable error condition) to stderr if either DEBUG is defined or the MESA_DEBUG env var is set.
Parameters
ctx GL context.
fmtString printf()-like format string.
References _mesa_vsnprintf(), flush_delayed_errors(), MAX_DEBUG_MESSAGE_LENGTH, output_if_debug(), and void.
Referenced by _mesa_accum(), _mesa_base_format_has_channel(), _mesa_choose_texture_format(), _mesa_clear_accum_buffer(), _mesa_GetInternalformativ(), _mesa_init_remap_table(), _mesa_init_texture_s3tc(), _mesa_link_program(), _mesa_LinkProgram(), _mesa_make_current(), _mesa_ProgramStringARB(), _mesa_RenderMode(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_unmap_buffer(), and store_texsubimage().
flush_delayed_errors()
static void flush_delayed_errors (struct gl_context * ctx) static
When a new type of error is recorded, print a message describing previous errors which were accumulated.
References _mesa_enum_to_string(), _mesa_snprintf(), gl_context::ErrorDebugCount, gl_context::ErrorValue, MAX_DEBUG_MESSAGE_LENGTH, and output_if_debug().
Referenced by _mesa_warning(), and should_output().
output_if_debug()
static void output_if_debug (const char * prefixString, const char * outputString, GLboolean newline) static
References _mesa_snprintf(), DEBUG_SILENT, LogFile, and MESA_DEBUG_FLAGS.
Referenced by _mesa_debug(), _mesa_error(), _mesa_log(), _mesa_warning(), and flush_delayed_errors().
should_output()
static GLboolean should_output (struct gl_context * ctx, GLenum error, const char * fmtString) static
References gl_context::ErrorDebugCount, gl_context::ErrorDebugFmtString, gl_context::ErrorValue, and flush_delayed_errors().
Referenced by _mesa_error().
Variable Documentation
LogFile
FILE* LogFile = NULL static
Referenced by _mesa_get_log_file(), and output_if_debug().