Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
errors.h File Reference
Mesa debugging and error handling functions.
#include <stdio.h>
#include <stdarg.h>
#include "compiler.h"
#include "glheader.h"
#include "mtypes.h"
Macros
#define _mesa_perf_debug(ctx, sev, ...)
Functions
void _mesa_warning (struct gl_context *gc, const char *fmtString,...) PRINTFLIKE(2
void void _mesa_problem (const struct gl_context *ctx, const char *fmtString,...) PRINTFLIKE(2
void void void _mesa_error (struct gl_context *ctx, GLenum error, const char *fmtString,...) PRINTFLIKE(3
void void void void _mesa_error_no_memory (const char *caller)
void _mesa_debug (const struct gl_context *ctx, const char *fmtString,...) PRINTFLIKE(2
void void _mesa_log (const char *fmtString,...) PRINTFLIKE(1
void void FILE * _mesa_get_log_file (void)
Return the file handle to use for debug/logging.
void _mesa_shader_debug (struct gl_context *ctx, GLenum type, GLuint *id, const char *msg)
Report debug information from the shader compiler via GL_ARB_debug_output.
void _mesa_gl_vdebug (struct gl_context *ctx, GLuint *id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char *fmtString, va_list args)
void _mesa_gl_debug (struct gl_context *ctx, GLuint *id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char *fmtString,...) PRINTFLIKE(6
Detailed Description
Mesa debugging and error handling functions.
This file provides functions to record errors, warnings, and miscellaneous debug information.
Macro Definition Documentation
_mesa_perf_debug
#define _mesa_perf_debug (ctx, sev, ...)
Value:
do {                              \
   static GLuint msg_id = 0;                                              \
   if (unlikely(ctx->Const.ContextFlags & GL_CONTEXT_FLAG_DEBUG_BIT)) {   \
      _mesa_gl_debug(ctx, &msg_id,                                        \
                     MESA_DEBUG_SOURCE_API,                               \
                     MESA_DEBUG_TYPE_PERFORMANCE,                         \
                     sev,                                                 \
                     __VA_ARGS__);                                        \
   }                                                                      \
} while (0)
Referenced by copyteximage().
Function Documentation
_mesa_debug()
void _mesa_debug (const struct gl_context * ctx, const char * fmtString, ...)
_mesa_error()
void void void _mesa_error (struct gl_context * ctx, GLenum error, const char * fmtString, ...)
_mesa_error_no_memory()
void void void void _mesa_error_no_memory (const char * caller)
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_CreatePerfQueryINTEL(), _mesa_NewHashTable(), format_array_format_table_init(), and register_surface().
_mesa_get_log_file()
void void FILE* _mesa_get_log_file (void)
Return the file handle to use for debug/logging.
Defaults to stderr unless MESA_LOG_FILE is defined.
References LogFile.
Referenced by _mesa_compile_shader().
_mesa_gl_debug()
void _mesa_gl_debug (struct gl_context * ctx, GLuint * id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char * fmtString, ...)
_mesa_gl_vdebug()
void _mesa_gl_vdebug (struct gl_context * ctx, GLuint * id, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, const char * fmtString, va_list args)
References _mesa_debug_get_id(), _mesa_log_msg(), _mesa_vsnprintf(), and MAX_DEBUG_MESSAGE_LENGTH.
Referenced by _mesa_gl_debug(), and buffer_usage_warning().
_mesa_log()
void void _mesa_log (const char * fmtString, ...)
_mesa_problem()
void void _mesa_problem (const struct gl_context * ctx, const char * fmtString, ...)
_mesa_shader_debug()
void _mesa_shader_debug (struct gl_context * ctx, GLenum type, GLuint * id, const char * msg)
Report debug information from the shader compiler via GL_ARB_debug_output.
Parameters
ctx GL context.
type The namespace to which this message belongs.
id The message ID within the given namespace.
msg The message to output. Must be null-terminated.
References _mesa_debug_get_id(), _mesa_log_msg(), MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, and MESA_DEBUG_SOURCE_SHADER_COMPILER.
_mesa_warning()
void _mesa_warning (struct gl_context * gc, const char * fmtString, ...)