Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
es1_conversion.h File Reference
Macros
#define GL_APIENTRY GLAPIENTRY
Functions
void GL_APIENTRY _mesa_AlphaFuncx (GLenum func, GLclampx ref)
void GL_APIENTRY _mesa_ClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
void GL_APIENTRY _mesa_ClearDepthx (GLclampx depth)
void GL_APIENTRY _mesa_ClipPlanef (GLenum plane, const GLfloat *equation)
void GL_APIENTRY _mesa_ClipPlanex (GLenum plane, const GLfixed *equation)
void GL_APIENTRY _es_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
void GL_APIENTRY _mesa_Color4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
void GL_APIENTRY _mesa_DepthRangex (GLclampx zNear, GLclampx zFar)
void GL_APIENTRY _mesa_DrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed w, GLfixed h)
void GL_APIENTRY _mesa_DrawTexxvOES (const GLfixed *coords)
void GL_APIENTRY _mesa_Fogx (GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_Fogxv (GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_Frustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
void GL_APIENTRY _mesa_Frustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
void GL_APIENTRY _mesa_GetClipPlanef (GLenum plane, GLfloat *equation)
void GL_APIENTRY _mesa_GetClipPlanex (GLenum plane, GLfixed *equation)
void GL_APIENTRY _mesa_GetLightxv (GLenum light, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_GetMaterialxv (GLenum face, GLenum pname, GLfixed *params)
void GL_APIENTRY _check_GetTexGenivOES (GLenum coord, GLenum pname, GLint *params)
void GL_APIENTRY _mesa_GetTexEnvxv (GLenum target, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_GetTexGenxvOES (GLenum coord, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_GetTexParameterxv (GLenum target, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_LightModelx (GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_LightModelxv (GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_Lightx (GLenum light, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_Lightxv (GLenum light, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_LineWidthx (GLfixed width)
void GL_APIENTRY _mesa_LoadMatrixx (const GLfixed *m)
void GL_APIENTRY _mesa_Materialx (GLenum face, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_Materialxv (GLenum face, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_MultMatrixx (const GLfixed *m)
void GL_APIENTRY _mesa_MultiTexCoord4x (GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
void GL_APIENTRY _mesa_Normal3x (GLfixed nx, GLfixed ny, GLfixed nz)
void GL_APIENTRY _mesa_Orthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
void GL_APIENTRY _mesa_Orthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
void GL_APIENTRY _mesa_PointParameterx (GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_PointParameterxv (GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_PointSizex (GLfixed size)
void GL_APIENTRY _mesa_PolygonOffsetx (GLfixed factor, GLfixed units)
void GL_APIENTRY _mesa_Rotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
void GL_APIENTRY _mesa_SampleCoveragex (GLclampx value, GLboolean invert)
void GL_APIENTRY _mesa_Scalex (GLfixed x, GLfixed y, GLfixed z)
void GL_APIENTRY _mesa_TexEnvx (GLenum target, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_TexEnvxv (GLenum target, GLenum pname, const GLfixed *params)
void GL_APIENTRY _check_TexGeniOES (GLenum coord, GLenum pname, GLint param)
void GL_APIENTRY _check_TexGenivOES (GLenum coord, GLenum pname, const GLint *params)
void GL_APIENTRY _mesa_TexGenxOES (GLenum coord, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_TexGenxvOES (GLenum coord, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_TexParameterx (GLenum target, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_TexParameterxv (GLenum target, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_Translatex (GLfixed x, GLfixed y, GLfixed z)
Macro Definition Documentation
GL_APIENTRY
#define GL_APIENTRY GLAPIENTRY
Referenced by _check_GetTexGenivOES(), _check_TexGeniOES(), _check_TexGenivOES(), _es_Color4ub(), _mesa_AlphaFuncx(), _mesa_ClearColorx(), _mesa_ClearDepthx(), _mesa_ClipPlanef(), _mesa_ClipPlanex(), _mesa_Color4x(), _mesa_DepthRangex(), _mesa_DrawTexxOES(), _mesa_DrawTexxvOES(), _mesa_Fogx(), _mesa_Fogxv(), _mesa_Frustumf(), _mesa_Frustumx(), _mesa_GetClipPlanef(), _mesa_GetClipPlanex(), _mesa_GetLightxv(), _mesa_GetMaterialxv(), _mesa_GetTexEnvxv(), _mesa_GetTexGenxvOES(), _mesa_GetTexParameterxv(), _mesa_LightModelx(), _mesa_LightModelxv(), _mesa_Lightx(), _mesa_Lightxv(), _mesa_LineWidthx(), _mesa_LoadMatrixx(), _mesa_Materialx(), _mesa_Materialxv(), _mesa_MultiTexCoord4x(), _mesa_MultMatrixx(), _mesa_Normal3x(), _mesa_Orthof(), _mesa_Orthox(), _mesa_PointParameterx(), _mesa_PointParameterxv(), _mesa_PointSizex(), _mesa_PolygonOffsetx(), _mesa_Rotatex(), _mesa_SampleCoveragex(), _mesa_Scalex(), _mesa_TexEnvx(), _mesa_TexEnvxv(), _mesa_TexGenxOES(), _mesa_TexGenxvOES(), _mesa_TexParameterx(), and _mesa_TexParameterxv().
Function Documentation
_check_GetTexGenivOES()
void GL_APIENTRY _check_GetTexGenivOES (GLenum coord, GLenum pname, GLint * params)
References _mesa_GetTexGeniv(), and GL_APIENTRY.
_check_TexGeniOES()
void GL_APIENTRY _check_TexGeniOES (GLenum coord, GLenum pname, GLint param)
References _es_TexGenf(), and GL_APIENTRY.
_check_TexGenivOES()
void GL_APIENTRY _check_TexGenivOES (GLenum coord, GLenum pname, const GLint * params)
References _es_TexGenf(), and GL_APIENTRY.
_es_Color4ub()
void GL_APIENTRY _es_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
References _es_Color4f(), and GL_APIENTRY.
_mesa_AlphaFuncx()
void GL_APIENTRY _mesa_AlphaFuncx (GLenum func, GLclampx ref)
References _mesa_AlphaFunc(), and GL_APIENTRY.
_mesa_ClearColorx()
void GL_APIENTRY _mesa_ClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
References _mesa_ClearColor(), and GL_APIENTRY.
_mesa_ClearDepthx()
void GL_APIENTRY _mesa_ClearDepthx (GLclampx depth)
References _mesa_ClearDepthf(), and GL_APIENTRY.
_mesa_ClipPlanef()
void GL_APIENTRY _mesa_ClipPlanef (GLenum plane, const GLfloat * equation)
References _mesa_ClipPlane(), and GL_APIENTRY.
_mesa_ClipPlanex()
void GL_APIENTRY _mesa_ClipPlanex (GLenum plane, const GLfixed * equation)
References _mesa_ClipPlane(), and GL_APIENTRY.
_mesa_Color4x()
void GL_APIENTRY _mesa_Color4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
References _es_Color4f(), and GL_APIENTRY.
_mesa_DepthRangex()
void GL_APIENTRY _mesa_DepthRangex (GLclampx zNear, GLclampx zFar)
References _mesa_DepthRangef(), and GL_APIENTRY.
_mesa_DrawTexxOES()
void GL_APIENTRY _mesa_DrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed w, GLfixed h)
References _mesa_DrawTexfOES(), and GL_APIENTRY.
_mesa_DrawTexxvOES()
void GL_APIENTRY _mesa_DrawTexxvOES (const GLfixed * coords)
References _mesa_DrawTexfvOES(), and GL_APIENTRY.
_mesa_Fogx()
void GL_APIENTRY _mesa_Fogx (GLenum pname, GLfixed param)
References _mesa_Fogf(), and GL_APIENTRY.
_mesa_Fogxv()
void GL_APIENTRY _mesa_Fogxv (GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_Fogfv(), _mesa_get_current_context(), and GL_APIENTRY.
_mesa_Frustumf()
void GL_APIENTRY _mesa_Frustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
References _mesa_Frustum(), and GL_APIENTRY.
_mesa_Frustumx()
void GL_APIENTRY _mesa_Frustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
References _mesa_Frustum(), and GL_APIENTRY.
_mesa_GetClipPlanef()
void GL_APIENTRY _mesa_GetClipPlanef (GLenum plane, GLfloat * equation)
References _mesa_GetClipPlane(), and GL_APIENTRY.
_mesa_GetClipPlanex()
void GL_APIENTRY _mesa_GetClipPlanex (GLenum plane, GLfixed * equation)
References _mesa_GetClipPlane(), and GL_APIENTRY.
_mesa_GetLightxv()
void GL_APIENTRY _mesa_GetLightxv (GLenum light, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_GetLightfv(), and GL_APIENTRY.
_mesa_GetMaterialxv()
void GL_APIENTRY _mesa_GetMaterialxv (GLenum face, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_GetMaterialfv(), and GL_APIENTRY.
_mesa_GetTexEnvxv()
void GL_APIENTRY _mesa_GetTexEnvxv (GLenum target, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_GetTexEnvfv(), and GL_APIENTRY.
_mesa_GetTexGenxvOES()
void GL_APIENTRY _mesa_GetTexGenxvOES (GLenum coord, GLenum pname, GLfixed * params)
References _mesa_GetTexGeniv(), and GL_APIENTRY.
_mesa_GetTexParameterxv()
void GL_APIENTRY _mesa_GetTexParameterxv (GLenum target, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_GetTexParameterfv(), GL_APIENTRY, GL_TEXTURE_CROP_RECT_OES, and GL_TEXTURE_EXTERNAL_OES.
_mesa_LightModelx()
void GL_APIENTRY _mesa_LightModelx (GLenum pname, GLfixed param)
References _mesa_LightModelf(), and GL_APIENTRY.
_mesa_LightModelxv()
void GL_APIENTRY _mesa_LightModelxv (GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_LightModelfv(), and GL_APIENTRY.
_mesa_Lightx()
void GL_APIENTRY _mesa_Lightx (GLenum light, GLenum pname, GLfixed param)
References _mesa_Lightf(), and GL_APIENTRY.
_mesa_Lightxv()
void GL_APIENTRY _mesa_Lightxv (GLenum light, GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_Lightfv(), and GL_APIENTRY.
_mesa_LineWidthx()
void GL_APIENTRY _mesa_LineWidthx (GLfixed width)
References _mesa_LineWidth(), and GL_APIENTRY.
_mesa_LoadMatrixx()
void GL_APIENTRY _mesa_LoadMatrixx (const GLfixed * m)
References _mesa_LoadMatrixf(), and GL_APIENTRY.
_mesa_Materialx()
void GL_APIENTRY _mesa_Materialx (GLenum face, GLenum pname, GLfixed param)
References _es_Materialf(), _mesa_error(), _mesa_get_current_context(), and GL_APIENTRY.
_mesa_Materialxv()
void GL_APIENTRY _mesa_Materialxv (GLenum face, GLenum pname, const GLfixed * params)
References _es_Materialfv(), _mesa_error(), _mesa_get_current_context(), and GL_APIENTRY.
_mesa_MultiTexCoord4x()
void GL_APIENTRY _mesa_MultiTexCoord4x (GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
References _es_MultiTexCoord4f(), and GL_APIENTRY.
_mesa_MultMatrixx()
void GL_APIENTRY _mesa_MultMatrixx (const GLfixed * m)
References _mesa_MultMatrixf(), and GL_APIENTRY.
_mesa_Normal3x()
void GL_APIENTRY _mesa_Normal3x (GLfixed nx, GLfixed ny, GLfixed nz)
References _es_Normal3f(), and GL_APIENTRY.
_mesa_Orthof()
void GL_APIENTRY _mesa_Orthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
References _mesa_Ortho(), and GL_APIENTRY.
_mesa_Orthox()
void GL_APIENTRY _mesa_Orthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
References _mesa_Ortho(), and GL_APIENTRY.
_mesa_PointParameterx()
void GL_APIENTRY _mesa_PointParameterx (GLenum pname, GLfixed param)
References _mesa_PointParameterf(), and GL_APIENTRY.
_mesa_PointParameterxv()
void GL_APIENTRY _mesa_PointParameterxv (GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_PointParameterfv(), and GL_APIENTRY.
_mesa_PointSizex()
void GL_APIENTRY _mesa_PointSizex (GLfixed size)
References _mesa_PointSize(), and GL_APIENTRY.
_mesa_PolygonOffsetx()
void GL_APIENTRY _mesa_PolygonOffsetx (GLfixed factor, GLfixed units)
References _mesa_PolygonOffset(), and GL_APIENTRY.
_mesa_Rotatex()
void GL_APIENTRY _mesa_Rotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
References _mesa_Rotatef(), and GL_APIENTRY.
_mesa_SampleCoveragex()
void GL_APIENTRY _mesa_SampleCoveragex (GLclampx value, GLboolean invert)
References _mesa_SampleCoverage(), and GL_APIENTRY.
_mesa_Scalex()
void GL_APIENTRY _mesa_Scalex (GLfixed x, GLfixed y, GLfixed z)
References _mesa_Scalef(), and GL_APIENTRY.
_mesa_TexEnvx()
void GL_APIENTRY _mesa_TexEnvx (GLenum target, GLenum pname, GLfixed param)
References _mesa_error(), _mesa_get_current_context(), _mesa_TexEnvf(), and GL_APIENTRY.
_mesa_TexEnvxv()
void GL_APIENTRY _mesa_TexEnvxv (GLenum target, GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_TexEnvf(), _mesa_TexEnvfv(), and GL_APIENTRY.
_mesa_TexGenxOES()
void GL_APIENTRY _mesa_TexGenxOES (GLenum coord, GLenum pname, GLfixed param)
References _es_TexGenf(), and GL_APIENTRY.
_mesa_TexGenxvOES()
void GL_APIENTRY _mesa_TexGenxvOES (GLenum coord, GLenum pname, const GLfixed * params)
References _es_TexGenf(), and GL_APIENTRY.
_mesa_TexParameterx()
void GL_APIENTRY _mesa_TexParameterx (GLenum target, GLenum pname, GLfixed param)
References _mesa_TexParameterf(), and GL_APIENTRY.
_mesa_TexParameterxv()
void GL_APIENTRY _mesa_TexParameterxv (GLenum target, GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_TexParameterfv(), GL_APIENTRY, GL_TEXTURE_CROP_RECT_OES, and GL_TEXTURE_EXTERNAL_OES.
_mesa_Translatex()
void GL_APIENTRY _mesa_Translatex (GLfixed x, GLfixed y, GLfixed z)
References _mesa_Translatef().