Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
eval.c File Reference
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "eval.h"
#include "macros.h"
#include "mtypes.h"
#include "main/dispatch.h"
Functions
GLuint _mesa_evaluator_components (GLenum target)
static struct gl_1d_map * get_1d_map (struct gl_context *ctx, GLenum target)
static struct gl_2d_map * get_2d_map (struct gl_context *ctx, GLenum target)
GLfloat * _mesa_copy_map_points1f (GLenum target, GLint ustride, GLint uorder, const GLfloat *points)
GLfloat * _mesa_copy_map_points1d (GLenum target, GLint ustride, GLint uorder, const GLdouble *points)
GLfloat * _mesa_copy_map_points2f (GLenum target, GLint ustride, GLint uorder, GLint vstride, GLint vorder, const GLfloat *points)
GLfloat * _mesa_copy_map_points2d (GLenum target, GLint ustride, GLint uorder, GLint vstride, GLint vorder, const GLdouble *points)
static void map1 (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, const GLvoid *points, GLenum type)
void GLAPIENTRY _mesa_Map1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points)
void GLAPIENTRY _mesa_Map1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points)
static void map2 (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLvoid *points, GLenum type)
void GLAPIENTRY _mesa_Map2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points)
void GLAPIENTRY _mesa_Map2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points)
void GLAPIENTRY _mesa_GetnMapdvARB (GLenum target, GLenum query, GLsizei bufSize, GLdouble *v)
void GLAPIENTRY _mesa_GetMapdv (GLenum target, GLenum query, GLdouble *v)
void GLAPIENTRY _mesa_GetnMapfvARB (GLenum target, GLenum query, GLsizei bufSize, GLfloat *v)
void GLAPIENTRY _mesa_GetMapfv (GLenum target, GLenum query, GLfloat *v)
void GLAPIENTRY _mesa_GetnMapivARB (GLenum target, GLenum query, GLsizei bufSize, GLint *v)
void GLAPIENTRY _mesa_GetMapiv (GLenum target, GLenum query, GLint *v)
void GLAPIENTRY _mesa_MapGrid1f (GLint un, GLfloat u1, GLfloat u2)
void GLAPIENTRY _mesa_MapGrid1d (GLint un, GLdouble u1, GLdouble u2)
void GLAPIENTRY _mesa_MapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
void GLAPIENTRY _mesa_MapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
void _mesa_install_eval_vtxfmt (struct _glapi_table *disp, const GLvertexformat *vfmt)
static void init_1d_map (struct gl_1d_map *map, int n, const float *initial)
Initialize a 1-D evaluator map.
static void init_2d_map (struct gl_2d_map *map, int n, const float *initial)
Initialize a 2-D evaluator map.
void _mesa_init_eval (struct gl_context *ctx)
void _mesa_free_eval_data (struct gl_context *ctx)
Function Documentation
_mesa_copy_map_points1d()
GLfloat* _mesa_copy_map_points1d (GLenum target, GLint ustride, GLint uorder, const GLdouble * points)
References _mesa_evaluator_components().
Referenced by map1(), and save_Map1d().
_mesa_copy_map_points1f()
GLfloat* _mesa_copy_map_points1f (GLenum target, GLint ustride, GLint uorder, const GLfloat * points)
References _mesa_evaluator_components().
Referenced by map1(), and save_Map1f().
_mesa_copy_map_points2d()
GLfloat* _mesa_copy_map_points2d (GLenum target, GLint ustride, GLint uorder, GLint vstride, GLint vorder, const GLdouble * points)
References _mesa_evaluator_components().
Referenced by map2(), and save_Map2d().
_mesa_copy_map_points2f()
GLfloat* _mesa_copy_map_points2f (GLenum target, GLint ustride, GLint uorder, GLint vstride, GLint vorder, const GLfloat * points)
References _mesa_evaluator_components().
Referenced by map2(), and save_Map2f().
_mesa_evaluator_components()
GLuint _mesa_evaluator_components (GLenum target)
References GLuint.
Referenced by _mesa_copy_map_points1d(), _mesa_copy_map_points1f(), _mesa_copy_map_points2d(), _mesa_copy_map_points2f(), _mesa_GetnMapdvARB(), _mesa_GetnMapfvARB(), _mesa_GetnMapivARB(), execute_list(), map1(), map2(), save_Map1d(), save_Map1f(), save_Map2d(), and save_Map2f().
_mesa_free_eval_data()
void _mesa_free_eval_data (struct gl_context * ctx)
References gl_context::EvalMap, gl_evaluators::Map1Color4, gl_evaluators::Map1Index, gl_evaluators::Map1Normal, gl_evaluators::Map1Texture1, gl_evaluators::Map1Texture2, gl_evaluators::Map1Texture3, gl_evaluators::Map1Texture4, gl_evaluators::Map1Vertex3, gl_evaluators::Map1Vertex4, gl_evaluators::Map2Color4, gl_evaluators::Map2Index, gl_evaluators::Map2Normal, gl_evaluators::Map2Texture1, gl_evaluators::Map2Texture2, gl_evaluators::Map2Texture3, gl_evaluators::Map2Texture4, gl_evaluators::Map2Vertex3, gl_evaluators::Map2Vertex4, gl_1d_map::Points, and gl_2d_map::Points.
Referenced by _mesa_free_context_data().
_mesa_GetMapdv()
void GLAPIENTRY _mesa_GetMapdv (GLenum target, GLenum query, GLdouble * v)
References _mesa_GetnMapdvARB(), and GLAPIENTRY.
_mesa_GetMapfv()
void GLAPIENTRY _mesa_GetMapfv (GLenum target, GLenum query, GLfloat * v)
References _mesa_GetnMapfvARB(), and GLAPIENTRY.
_mesa_GetMapiv()
void GLAPIENTRY _mesa_GetMapiv (GLenum target, GLenum query, GLint * v)
References _mesa_GetnMapivARB(), and GLAPIENTRY.
_mesa_GetnMapdvARB()
void GLAPIENTRY _mesa_GetnMapdvARB (GLenum target, GLenum query, GLsizei bufSize, GLdouble * v)
References _mesa_error(), _mesa_evaluator_components(), get_1d_map(), get_2d_map(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_1d_map::Order, gl_1d_map::Points, gl_2d_map::Points, gl_1d_map::u1, gl_2d_map::u1, gl_1d_map::u2, gl_2d_map::u2, gl_2d_map::Uorder, gl_2d_map::v1, gl_2d_map::v2, and gl_2d_map::Vorder.
Referenced by _mesa_GetMapdv().
_mesa_GetnMapfvARB()
void GLAPIENTRY _mesa_GetnMapfvARB (GLenum target, GLenum query, GLsizei bufSize, GLfloat * v)
References _mesa_error(), _mesa_evaluator_components(), get_1d_map(), get_2d_map(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_1d_map::Order, gl_1d_map::Points, gl_2d_map::Points, gl_1d_map::u1, gl_2d_map::u1, gl_1d_map::u2, gl_2d_map::u2, gl_2d_map::Uorder, gl_2d_map::v1, gl_2d_map::v2, and gl_2d_map::Vorder.
Referenced by _mesa_GetMapfv().
_mesa_GetnMapivARB()
void GLAPIENTRY _mesa_GetnMapivARB (GLenum target, GLenum query, GLsizei bufSize, GLint * v)
References _mesa_error(), _mesa_evaluator_components(), get_1d_map(), get_2d_map(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, IROUND(), gl_1d_map::Order, gl_1d_map::Points, gl_2d_map::Points, gl_1d_map::u1, gl_2d_map::u1, gl_1d_map::u2, gl_2d_map::u2, gl_2d_map::Uorder, gl_2d_map::v1, gl_2d_map::v2, and gl_2d_map::Vorder.
Referenced by _mesa_GetMapiv().
_mesa_init_eval()
void _mesa_init_eval (struct gl_context * ctx)
References gl_eval_attrib::AutoNormal, gl_context::Eval, gl_context::EvalMap, init_1d_map(), init_2d_map(), gl_eval_attrib::Map1Color4, gl_evaluators::Map1Color4, gl_eval_attrib::Map1Index, gl_evaluators::Map1Index, gl_eval_attrib::Map1Normal, gl_evaluators::Map1Normal, gl_evaluators::Map1Texture1, gl_evaluators::Map1Texture2, gl_evaluators::Map1Texture3, gl_evaluators::Map1Texture4, gl_eval_attrib::Map1TextureCoord1, gl_eval_attrib::Map1TextureCoord2, gl_eval_attrib::Map1TextureCoord3, gl_eval_attrib::Map1TextureCoord4, gl_eval_attrib::Map1Vertex3, gl_evaluators::Map1Vertex3, gl_eval_attrib::Map1Vertex4, gl_evaluators::Map1Vertex4, gl_eval_attrib::Map2Color4, gl_evaluators::Map2Color4, gl_eval_attrib::Map2Index, gl_evaluators::Map2Index, gl_eval_attrib::Map2Normal, gl_evaluators::Map2Normal, gl_evaluators::Map2Texture1, gl_evaluators::Map2Texture2, gl_evaluators::Map2Texture3, gl_evaluators::Map2Texture4, gl_eval_attrib::Map2TextureCoord1, gl_eval_attrib::Map2TextureCoord2, gl_eval_attrib::Map2TextureCoord3, gl_eval_attrib::Map2TextureCoord4, gl_eval_attrib::Map2Vertex3, gl_evaluators::Map2Vertex3, gl_eval_attrib::Map2Vertex4, gl_evaluators::Map2Vertex4, gl_eval_attrib::MapGrid1u1, gl_eval_attrib::MapGrid1u2, gl_eval_attrib::MapGrid1un, gl_eval_attrib::MapGrid2u1, gl_eval_attrib::MapGrid2u2, gl_eval_attrib::MapGrid2un, gl_eval_attrib::MapGrid2v1, gl_eval_attrib::MapGrid2v2, and gl_eval_attrib::MapGrid2vn.
Referenced by init_attrib_groups().
_mesa_install_eval_vtxfmt()
void _mesa_install_eval_vtxfmt (struct _glapi_table * disp, const GLvertexformat * vfmt)
Referenced by install_vtxfmt().
_mesa_Map1d()
void GLAPIENTRY _mesa_Map1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points)
References map1().
_mesa_Map1f()
void GLAPIENTRY _mesa_Map1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points)
References GLAPIENTRY, and map1().
_mesa_Map2d()
void GLAPIENTRY _mesa_Map2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points)
References GLAPIENTRY, and map2().
_mesa_Map2f()
void GLAPIENTRY _mesa_Map2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points)
References GLAPIENTRY, and map2().
_mesa_MapGrid1d()
void GLAPIENTRY _mesa_MapGrid1d (GLint un, GLdouble u1, GLdouble u2)
References _mesa_MapGrid1f(), and GLAPIENTRY.
_mesa_MapGrid1f()
void GLAPIENTRY _mesa_MapGrid1f (GLint un, GLfloat u1, GLfloat u2)
References _mesa_error(), _NEW_EVAL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_2d_map::u1, and gl_2d_map::u2.
Referenced by _mesa_MapGrid1d().
_mesa_MapGrid2d()
void GLAPIENTRY _mesa_MapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
References _mesa_MapGrid2f().
_mesa_MapGrid2f()
void GLAPIENTRY _mesa_MapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
References _mesa_error(), _NEW_EVAL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_2d_map::u1, gl_2d_map::u2, gl_2d_map::v1, and gl_2d_map::v2.
Referenced by _mesa_MapGrid2d().
get_1d_map()
static struct gl_1d_map* get_1d_map (struct gl_context * ctx, GLenum target) static
References gl_context::EvalMap, gl_evaluators::Map1Color4, gl_evaluators::Map1Index, gl_evaluators::Map1Normal, gl_evaluators::Map1Texture1, gl_evaluators::Map1Texture2, gl_evaluators::Map1Texture3, gl_evaluators::Map1Texture4, gl_evaluators::Map1Vertex3, and gl_evaluators::Map1Vertex4.
Referenced by _mesa_GetnMapdvARB(), _mesa_GetnMapfvARB(), _mesa_GetnMapivARB(), and map1().
get_2d_map()
static struct gl_2d_map* get_2d_map (struct gl_context * ctx, GLenum target) static
References gl_context::EvalMap, gl_evaluators::Map2Color4, gl_evaluators::Map2Index, gl_evaluators::Map2Normal, gl_evaluators::Map2Texture1, gl_evaluators::Map2Texture2, gl_evaluators::Map2Texture3, gl_evaluators::Map2Texture4, gl_evaluators::Map2Vertex3, and gl_evaluators::Map2Vertex4.
Referenced by _mesa_GetnMapdvARB(), _mesa_GetnMapfvARB(), _mesa_GetnMapivARB(), and map2().
init_1d_map()
static void init_1d_map (struct gl_1d_map * map, int n, const float * initial) static
Initialize a 1-D evaluator map.
References gl_1d_map::Order, gl_1d_map::Points, gl_1d_map::u1, and gl_1d_map::u2.
Referenced by _mesa_init_eval().
init_2d_map()
static void init_2d_map (struct gl_2d_map * map, int n, const float * initial) static
Initialize a 2-D evaluator map.
References gl_2d_map::Points, gl_2d_map::u1, gl_2d_map::u2, gl_2d_map::Uorder, gl_2d_map::v1, gl_2d_map::v2, and gl_2d_map::Vorder.
Referenced by _mesa_init_eval().
map1()
static void map1 (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, const GLvoid * points, GLenum type) static
References _mesa_copy_map_points1d(), _mesa_copy_map_points1f(), _mesa_error(), _mesa_evaluator_components(), _NEW_EVAL, gl_1d_map::du, FLUSH_VERTICES, get_1d_map(), GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_EVAL_ORDER, gl_1d_map::Order, gl_1d_map::Points, gl_1d_map::u1, and gl_1d_map::u2.
Referenced by _mesa_Map1d(), and _mesa_Map1f().
map2()
static void map2 (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLvoid * points, GLenum type) static
References _mesa_copy_map_points2d(), _mesa_copy_map_points2f(), _mesa_error(), _mesa_evaluator_components(), _NEW_EVAL, gl_2d_map::du, gl_2d_map::dv, FLUSH_VERTICES, get_2d_map(), GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_EVAL_ORDER, gl_2d_map::Points, gl_2d_map::u1, gl_2d_map::u2, gl_2d_map::Uorder, gl_2d_map::v1, gl_2d_map::v2, and gl_2d_map::Vorder.
Referenced by _mesa_Map2d(), and _mesa_Map2f().