Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
extensions.c File Reference
Extension handling.
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "extensions.h"
#include "macros.h"
#include "mtypes.h"
Macros
#define o(x) offsetof(struct gl_extensions, x)
Given a member x of struct gl_extensions, return offset of x in bytes.
Typedefs
typedef unsigned short extension_index
Functions
static int name_to_index (const char *name)
Given an extension name, lookup up the corresponding member of struct gl_extensions and return that member's index.
static void override_extensions_in_context (struct gl_context *ctx)
Overrides extensions in ctx based on the values in _mesa_extension_override_enables and _mesa_extension_override_disables.
void _mesa_enable_sw_extensions (struct gl_context *ctx)
Enable all extensions suitable for a software-only renderer.
static size_t set_extension (struct gl_extensions *ext, int i, GLboolean state)
Either enable or disable the named extension.
static char * get_extension_override (struct gl_context *ctx)
Apply the MESA_EXTENSION_OVERRIDE environment variable.
static void free_unknown_extensions_strings (void)
Free extra_extensions string.
void _mesa_one_time_init_extension_overrides (void)
Initialize extension override tables.
void _mesa_init_extensions (struct gl_extensions *extensions)
Initialize extension tables and enable default extensions.
static bool _mesa_extension_supported (const struct gl_context *ctx, extension_index i)
Given an extension enum, return whether or not the extension is supported dependent on the following factors: There's driver support and the OpenGL/ES version is at least that specified in the _mesa_extension_table.
static int extension_compare (const void *p1, const void *p2)
Compare two entries of the extensions table.
GLubyte * _mesa_make_extension_string (struct gl_context *ctx)
Construct the GL_EXTENSIONS string.
GLuint _mesa_get_extension_count (struct gl_context *ctx)
Return number of enabled extensions.
const GLubyte * _mesa_get_enabled_extension (struct gl_context *ctx, GLuint index)
Return name of i-th enabled extension.
Variables
struct gl_extensions _mesa_extension_override_enables
struct gl_extensions _mesa_extension_override_disables
static char * extra_extensions = NULL
static bool disabled_extensions [MESA_EXTENSION_COUNT]
Detailed Description
Extension handling.
Macro Definition Documentation
o
#define o (x) offsetof(struct gl_extensions, x)
Given a member x of struct gl_extensions, return offset of x in bytes.
Referenced by _mesa_init_extensions(), _mesa_one_time_init_extension_overrides(), and set_extension().
Typedef Documentation
extension_index
typedef unsigned short extension_index
Function Documentation
_mesa_enable_sw_extensions()
void _mesa_enable_sw_extensions (struct gl_context * ctx)
Enable all extensions suitable for a software-only renderer.
This is a convenience function used by the XMesa, OSMesa, GGI drivers, etc.
References gl_extensions::ANGLE_texture_compression_dxt, gl_extensions::APPLE_object_purgeable, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_program, gl_extensions::ARB_fragment_program_shadow, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_point_sprite, gl_extensions::ARB_shadow, gl_extensions::ARB_sync, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_rg, gl_extensions::ARB_vertex_program, gl_extensions::ARB_vertex_shader, gl_extensions::ATI_fragment_shader, gl_extensions::ATI_separate_stencil, gl_extensions::ATI_texture_compression_3dc, gl_extensions::ATI_texture_env_combine3, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_depth_bounds_test, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_gpu_program_parameters, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_compression_latc, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_env_dot3, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_mirror_clamp, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, gl_context::Mesa_DXTn, gl_extensions::MESA_pack_invert, gl_extensions::MESA_ycbcr_texture, gl_extensions::NV_conditional_render, gl_extensions::NV_point_sprite, gl_extensions::NV_texture_env_combine4, gl_extensions::NV_texture_rectangle, gl_extensions::OES_standard_derivatives, and gl_extensions::TDFX_texture_compression_FXT1.
_mesa_extension_supported()
static bool _mesa_extension_supported (const struct gl_context * ctx, extension_index i) inline static
Given an extension enum, return whether or not the extension is supported dependent on the following factors: There's driver support and the OpenGL/ES version is at least that specified in the _mesa_extension_table.
References _mesa_extension_table, gl_context::API, disabled_extensions, gl_context::Extensions, and gl_context::Version.
Referenced by _mesa_get_enabled_extension(), _mesa_get_extension_count(), and _mesa_make_extension_string().
_mesa_get_enabled_extension()
const GLubyte* _mesa_get_enabled_extension (struct gl_context * ctx, GLuint index)
Return name of i-th enabled extension.
References _mesa_extension_supported(), _mesa_extension_table, and mesa_extension::name.
Referenced by _mesa_GetStringi().
_mesa_get_extension_count()
GLuint _mesa_get_extension_count (struct gl_context * ctx)
Return number of enabled extensions.
References _mesa_extension_supported(), gl_extensions::Count, and gl_context::Extensions.
Referenced by _mesa_GetStringi(), and find_custom_value().
_mesa_init_extensions()
void _mesa_init_extensions (struct gl_extensions * extensions)
Initialize extension tables and enable default extensions.
This should be called during context initialization. Note: Sets gl_extensions.dummy_true to true.
References gl_extensions::dummy_true, gl_extensions::extension_sentinel, and o.
Referenced by init_attrib_groups().
_mesa_make_extension_string()
GLubyte* _mesa_make_extension_string (struct gl_context * ctx)
Construct the GL_EXTENSIONS string.
Called the first time that glGetString(GL_EXTENSIONS) is called.
References _mesa_debug(), _mesa_extension_supported(), _mesa_extension_table, ALIGN(), extension_compare(), extra_extensions, get_extension_override(), GLuint, mesa_extension::name, and mesa_extension::year.
Referenced by handle_first_current().
_mesa_one_time_init_extension_overrides()
void _mesa_one_time_init_extension_overrides (void)
Initialize extension override tables.
This should be called one time early during first context initialization.
References _mesa_extension_override_disables, _mesa_extension_override_enables, ALIGN(), disabled_extensions, gl_extensions::dummy_true, extra_extensions, free_unknown_extensions_strings(), name_to_index(), o, and set_extension().
Referenced by one_time_init().
extension_compare()
static int extension_compare (const void * p1, const void * p2) static
Compare two entries of the extensions table.
Sorts first by year, then by name.
Arguments are indices into _mesa_extension_table.
References _mesa_extension_table, mesa_extension::name, and mesa_extension::year.
Referenced by _mesa_make_extension_string().
free_unknown_extensions_strings()
static void free_unknown_extensions_strings (void) static
Free extra_extensions string.
These strings are allocated early during the first context creation by _mesa_one_time_init_extension_overrides.
References extra_extensions.
Referenced by _mesa_one_time_init_extension_overrides().
get_extension_override()
static char* get_extension_override (struct gl_context * ctx) static
Apply the MESA_EXTENSION_OVERRIDE environment variable.
MESA_EXTENSION_OVERRIDE is a space-separated list of extensions to enable or disable. The list is processed thus:
Enable recognized extension names that are prefixed with '+'.
Disable recognized extension names that are prefixed with '-'.
Enable recognized extension names that are not prefixed.
Collect unrecognized extension names in a new string.
MESA_EXTENSION_OVERRIDE was previously parsed during _mesa_one_time_init_extension_overrides. We just use the results of that parsing in this function.
Returns
Space-separated list of unrecognized extension names (which must be freed). Does not return NULL.
References _mesa_problem(), extra_extensions, and override_extensions_in_context().
Referenced by _mesa_make_extension_string().
name_to_index()
static int name_to_index (const char * name) static
Given an extension name, lookup up the corresponding member of struct gl_extensions and return that member's index.
If the name is not found in the _mesa_extension_table, return -1.
Parameters
name Name of extension.
Returns
Index of member in struct gl_extensions.
References _mesa_extension_table.
Referenced by _mesa_one_time_init_extension_overrides().
override_extensions_in_context()
static void override_extensions_in_context (struct gl_context * ctx) static
Overrides extensions in ctx based on the values in _mesa_extension_override_enables and _mesa_extension_override_disables.
References _mesa_extension_override_disables, _mesa_extension_override_enables, _mesa_extension_table, gl_context::Extensions, for(), and mesa_extension::offset.
Referenced by get_extension_override().
set_extension()
static size_t set_extension (struct gl_extensions * ext, int i, GLboolean state) static
Either enable or disable the named extension.
Returns
offset of extensions withint `ext' or 0 if extension is not known
References _mesa_extension_table, gl_extensions::dummy_true, o, and mesa_extension::offset.
Referenced by _mesa_one_time_init_extension_overrides().
Variable Documentation
_mesa_extension_override_disables
struct gl_extensions _mesa_extension_override_disables
Referenced by _mesa_one_time_init_extension_overrides(), and override_extensions_in_context().
_mesa_extension_override_enables
struct gl_extensions _mesa_extension_override_enables
Referenced by _mesa_one_time_init_extension_overrides(), and override_extensions_in_context().
disabled_extensions
bool disabled_extensions[MESA_EXTENSION_COUNT] static
Referenced by _mesa_extension_supported(), and _mesa_one_time_init_extension_overrides().
extra_extensions
char* extra_extensions = NULL static
Referenced by _mesa_make_extension_string(), _mesa_one_time_init_extension_overrides(), free_unknown_extensions_strings(), and get_extension_override().