Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
extensions.h File Reference
Extension handling.
#include "glheader.h"
#include "extensions_table.h"
Data Structures
struct mesa_extension
An element of the extension_table.
Macros
#define EXT(name_str, ...) MESA_EXTENSION_##name_str,
Checks if the context supports a user-facing extension.
#define EXT(name_str, driver_cap, ...)
Checks if the context supports a user-facing extension.
Enumerations
enum { EXT, EXT }
Functions
void _mesa_enable_sw_extensions (struct gl_context *ctx)
Enable all extensions suitable for a software-only renderer.
void _mesa_one_time_init_extension_overrides (void)
Initialize extension override tables.
void _mesa_init_extensions (struct gl_extensions *extentions)
Initialize extension tables and enable default extensions.
GLubyte * _mesa_make_extension_string (struct gl_context *ctx)
Construct the GL_EXTENSIONS string.
GLuint _mesa_get_extension_count (struct gl_context *ctx)
Return number of enabled extensions.
const GLubyte * _mesa_get_enabled_extension (struct gl_context *ctx, GLuint index)
Return name of i-th enabled extension.
Variables
const struct mesa_extension _mesa_extension_table []
Table of supported OpenGL extensions for all API's.
struct gl_extensions _mesa_extension_override_enables
struct gl_extensions _mesa_extension_override_disables
Detailed Description
Extension handling.
Macro Definition Documentation
EXT [1/2]
#define EXT (name_str, ...) MESA_EXTENSION_##name_str,
Checks if the context supports a user-facing extension.
EXT [2/2]
#define EXT (name_str, driver_cap, ...)
Value:
static inline bool \
_mesa_has_##name_str(const struct gl_context *ctx) \
{ \
   return ctx->Extensions.driver_cap && (ctx->Extensions.Version >= \
          _mesa_extension_table[MESA_EXTENSION_##name_str].version[ctx->API]); \
}
Checks if the context supports a user-facing extension.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EXT
EXT
Function Documentation
_mesa_enable_sw_extensions()
void _mesa_enable_sw_extensions (struct gl_context * ctx)
Enable all extensions suitable for a software-only renderer.
This is a convenience function used by the XMesa, OSMesa, GGI drivers, etc.
References gl_extensions::ANGLE_texture_compression_dxt, gl_extensions::APPLE_object_purgeable, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_program, gl_extensions::ARB_fragment_program_shadow, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_point_sprite, gl_extensions::ARB_shadow, gl_extensions::ARB_sync, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_rg, gl_extensions::ARB_vertex_program, gl_extensions::ARB_vertex_shader, gl_extensions::ATI_fragment_shader, gl_extensions::ATI_separate_stencil, gl_extensions::ATI_texture_compression_3dc, gl_extensions::ATI_texture_env_combine3, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_depth_bounds_test, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_gpu_program_parameters, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_compression_latc, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_env_dot3, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_mirror_clamp, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, gl_context::Mesa_DXTn, gl_extensions::MESA_pack_invert, gl_extensions::MESA_ycbcr_texture, gl_extensions::NV_conditional_render, gl_extensions::NV_point_sprite, gl_extensions::NV_texture_env_combine4, gl_extensions::NV_texture_rectangle, gl_extensions::OES_standard_derivatives, and gl_extensions::TDFX_texture_compression_FXT1.
_mesa_get_enabled_extension()
const GLubyte* _mesa_get_enabled_extension (struct gl_context * ctx, GLuint index)
Return name of i-th enabled extension.
References _mesa_extension_supported(), _mesa_extension_table, and mesa_extension::name.
Referenced by _mesa_GetStringi().
_mesa_get_extension_count()
GLuint _mesa_get_extension_count (struct gl_context * ctx)
Return number of enabled extensions.
References _mesa_extension_supported(), gl_extensions::Count, and gl_context::Extensions.
Referenced by _mesa_GetStringi(), and find_custom_value().
_mesa_init_extensions()
void _mesa_init_extensions (struct gl_extensions * extensions)
Initialize extension tables and enable default extensions.
This should be called during context initialization. Note: Sets gl_extensions.dummy_true to true.
References gl_extensions::dummy_true, gl_extensions::extension_sentinel, and o.
Referenced by init_attrib_groups().
_mesa_make_extension_string()
GLubyte* _mesa_make_extension_string (struct gl_context * ctx)
Construct the GL_EXTENSIONS string.
Called the first time that glGetString(GL_EXTENSIONS) is called.
References _mesa_debug(), _mesa_extension_supported(), _mesa_extension_table, ALIGN(), extension_compare(), extra_extensions, get_extension_override(), GLuint, mesa_extension::name, and mesa_extension::year.
Referenced by handle_first_current().
_mesa_one_time_init_extension_overrides()
void _mesa_one_time_init_extension_overrides (void)
Initialize extension override tables.
This should be called one time early during first context initialization.
References _mesa_extension_override_disables, _mesa_extension_override_enables, ALIGN(), disabled_extensions, gl_extensions::dummy_true, extra_extensions, free_unknown_extensions_strings(), name_to_index(), o, and set_extension().
Referenced by one_time_init().
Variable Documentation
_mesa_extension_override_disables
struct gl_extensions _mesa_extension_override_disables
Referenced by _mesa_one_time_init_extension_overrides(), and override_extensions_in_context().
_mesa_extension_override_enables
struct gl_extensions _mesa_extension_override_enables
Referenced by _mesa_one_time_init_extension_overrides(), and override_extensions_in_context().
_mesa_extension_table
const struct mesa_extension _mesa_extension_table[]
Table of supported OpenGL extensions for all API's.
Referenced by _mesa_extension_supported(), _mesa_get_enabled_extension(), _mesa_make_extension_string(), extension_compare(), name_to_index(), override_extensions_in_context(), and set_extension().