Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
fbobject.c File Reference
#include <stdbool.h>
#include "buffers.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "formats.h"
#include "framebuffer.h"
#include "glformats.h"
#include "hash.h"
#include "macros.h"
#include "multisample.h"
#include "mtypes.h"
#include "renderbuffer.h"
#include "state.h"
#include "teximage.h"
#include "texobj.h"
Macros
#define NO_SAMPLES 1000
sentinal value, see below
Functions
static void delete_dummy_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
static void delete_dummy_framebuffer (struct gl_framebuffer *fb)
void _mesa_init_fbobjects (struct gl_context *ctx)
struct gl_framebuffer * _mesa_get_incomplete_framebuffer (void)
struct gl_renderbuffer * _mesa_lookup_renderbuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_renderbuffer.
struct gl_renderbuffer * _mesa_lookup_renderbuffer_err (struct gl_context *ctx, GLuint id, const char *func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the renderbuffer doesn't exist.
struct gl_framebuffer * _mesa_lookup_framebuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_framebuffer.
struct gl_framebuffer * _mesa_lookup_framebuffer_err (struct gl_context *ctx, GLuint id, const char *func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the framebuffer doesn't exist.
static void invalidate_framebuffer (struct gl_framebuffer *fb)
Mark the given framebuffer as invalid.
static struct gl_framebuffer * get_framebuffer_target (struct gl_context *ctx, GLenum target)
Return the gl_framebuffer object which corresponds to the given framebuffer target, such as GL_DRAW_FRAMEBUFFER.
static struct gl_renderbuffer_attachment * get_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, bool *is_color_attachment)
Given a GL_*_ATTACHMENTn token, return a pointer to the corresponding gl_renderbuffer_attachment object.
static struct gl_renderbuffer_attachment * _mesa_get_fb0_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment)
As above, but only used for getting attachments of the default / window-system framebuffer (not user-created framebuffer objects).
static void remove_attachment (struct gl_context *ctx, struct gl_renderbuffer_attachment *att)
Remove any texture or renderbuffer attached to the given attachment point.
static bool driver_RenderTexture_is_safe (const struct gl_renderbuffer_attachment *att)
Verify a couple error conditions that will lead to an incomplete FBO and may cause problems for the driver's RenderTexture path.
void _mesa_update_texture_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
static void set_texture_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att, struct gl_texture_object *texObj, GLenum texTarget, GLuint level, GLuint layer, GLboolean layered)
Bind a texture object to an attachment point.
static void set_renderbuffer_attachment (struct gl_context *ctx, struct gl_renderbuffer_attachment *att, struct gl_renderbuffer *rb)
Bind a renderbuffer to an attachment point.
void _mesa_FramebufferRenderbuffer_sw (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
void _mesa_validate_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer *fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
static void att_incomplete (const char *msg)
For debug only.
static void fbo_incomplete (struct gl_context *ctx, const char *msg, int index)
For debug only.
GLboolean _mesa_is_legal_color_format (const struct gl_context *ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
static GLboolean is_format_color_renderable (const struct gl_context *ctx, mesa_format format, GLenum internalFormat)
Is the given base format a legal format for a color renderbuffer?
static GLboolean is_legal_depth_format (const struct gl_context *ctx, GLenum baseFormat)
Is the given base format a legal format for a depth/stencil renderbuffer?
static void test_attachment_completeness (const struct gl_context *ctx, GLenum format, struct gl_renderbuffer_attachment *att)
Test if an attachment point is complete and update its Complete field.
void _mesa_test_framebuffer_completeness (struct gl_context *ctx, struct gl_framebuffer *fb)
Test if the given framebuffer object is complete and update its Status field with the results.
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
static struct gl_renderbuffer * allocate_renderbuffer_locked (struct gl_context *ctx, GLuint renderbuffer, const char *func)
static void bind_renderbuffer (GLenum target, GLuint renderbuffer, bool allow_user_names)
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
void GLAPIENTRY _mesa_BindRenderbufferEXT (GLenum target, GLuint renderbuffer)
static void framebuffer_parameteri (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum pname, GLint param, const char *func)
ARB_framebuffer_no_attachment - Application passes requested param's here.
void GLAPIENTRY _mesa_FramebufferParameteri (GLenum target, GLenum pname, GLint param)
static bool _pname_valid_for_default_framebuffer (struct gl_context *ctx, GLenum pname)
static void get_framebuffer_parameteriv (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum pname, GLint *params, const char *func)
void GLAPIENTRY _mesa_GetFramebufferParameteriv (GLenum target, GLenum pname, GLint *params)
bool _mesa_detach_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, const void *att)
Remove the specified renderbuffer or texture from any attachment point in the framebuffer.
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
static void create_render_buffers (struct gl_context *ctx, GLsizei n, GLuint *renderbuffers, bool dsa)
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint *renderbuffers)
void GLAPIENTRY _mesa_CreateRenderbuffers (GLsizei n, GLuint *renderbuffers)
GLenum _mesa_base_fbo_format (struct gl_context *ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
static void invalidate_rb (GLuint key, void *data, void *userData)
Invalidate a renderbuffer attachment.
void _mesa_renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples)
static void renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples, const char *func)
Helper function used by renderbuffer_storage_direct() and renderbuffer_storage_target().
static void renderbuffer_storage_named (GLuint renderbuffer, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples, const char *func)
Helper function used by _mesa_NamedRenderbufferStorage*().
static void renderbuffer_storage_target (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples, const char *func)
Helper function used by _mesa_RenderbufferStorage() and _mesa_RenderbufferStorageMultisample().
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
static GLint get_component_bits (GLenum pname, GLenum baseFormat, mesa_format format)
Helper function for _mesa_GetRenderbufferParameteriv() and _mesa_GetFramebufferAttachmentParameteriv() We have to be careful to respect the base format.
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalFormat, GLsizei width, GLsizei height)
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
void GLAPIENTRY _mesa_NamedRenderbufferStorage (GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_NamedRenderbufferStorageMultisample (GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
static void get_render_buffer_parameteriv (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum pname, GLint *params, const char *func)
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetNamedRenderbufferParameteriv (GLuint renderbuffer, GLenum pname, GLint *params)
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
static void check_begin_texture_render (struct gl_context *ctx, struct gl_framebuffer *fb)
Check if any of the attachments of the given framebuffer are textures (render to texture).
static void check_end_texture_render (struct gl_context *ctx, struct gl_framebuffer *fb)
Examine all the framebuffer's attachments to see if any are textures.
static void bind_framebuffer (GLenum target, GLuint framebuffer, bool allow_user_names)
void _mesa_bind_framebuffers (struct gl_context *ctx, struct gl_framebuffer *newDrawFb, struct gl_framebuffer *newReadFb)
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
void GLAPIENTRY _mesa_BindFramebufferEXT (GLenum target, GLuint framebuffer)
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
static void create_framebuffers (GLsizei n, GLuint *framebuffers, bool dsa)
This is the implementation for glGenFramebuffers and glCreateFramebuffers.
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint *framebuffers)
void GLAPIENTRY _mesa_CreateFramebuffers (GLsizei n, GLuint *framebuffers)
GLenum _mesa_check_framebuffer_status (struct gl_context *ctx, struct gl_framebuffer *buffer)
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
GLenum GLAPIENTRY _mesa_CheckNamedFramebufferStatus (GLuint framebuffer, GLenum target)
static void reuse_framebuffer_texture_attachment (struct gl_framebuffer *fb, gl_buffer_index dst, gl_buffer_index src)
Replicate the src attachment point.
static bool get_texture_for_framebuffer (struct gl_context *ctx, GLuint texture, bool layered, const char *caller, struct gl_texture_object **texObj)
Common code called by gl*FramebufferTexture*() to retrieve the correct texture object pointer.
static bool check_layered_texture_target (struct gl_context *ctx, GLenum target, const char *caller, GLboolean *layered)
Common code called by gl*FramebufferTexture() to verify the texture target and decide whether or not the attachment should truly be considered layered.
static bool check_texture_target (struct gl_context *ctx, GLenum target, const char *caller)
Common code called by gl*FramebufferTextureLayer() to verify the texture target.
static bool check_textarget (struct gl_context *ctx, int dims, GLenum target, GLenum textarget, const char *caller)
Common code called by glFramebufferTexture*D() to verify the texture target.
static bool check_layer (struct gl_context *ctx, GLenum target, GLint layer, const char *caller)
Common code called by gl*FramebufferTextureLayer() and glFramebufferTexture3D() to validate the layer.
static bool check_level (struct gl_context *ctx, GLenum target, GLint level, const char *caller)
Common code called by all gl*FramebufferTexture*() entry points to verify the level.
void _mesa_framebuffer_texture (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_texture_object *texObj, GLenum textarget, GLint level, GLuint layer, GLboolean layered, const char *caller)
static void framebuffer_texture_with_dims (int dims, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint layer, const char *caller)
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_NamedFramebufferTextureLayer (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
void GLAPIENTRY _mesa_NamedFramebufferTexture (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level)
void _mesa_framebuffer_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
static void framebuffer_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb, const char *func)
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void GLAPIENTRY _mesa_NamedFramebufferRenderbuffer (GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void _mesa_get_framebuffer_attachment_parameter (struct gl_context *ctx, struct gl_framebuffer *buffer, GLenum attachment, GLenum pname, GLint *params, const char *caller)
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetNamedFramebufferAttachmentParameteriv (GLuint framebuffer, GLenum attachment, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_NamedFramebufferParameteri (GLuint framebuffer, GLenum pname, GLint param)
void GLAPIENTRY _mesa_GetNamedFramebufferParameteriv (GLuint framebuffer, GLenum pname, GLint *param)
static void invalidate_framebuffer_storage (struct gl_context *ctx, struct gl_framebuffer *fb, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height, const char *name)
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_InvalidateNamedFramebufferSubData (GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_InvalidateNamedFramebufferData (GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments)
Variables
static struct gl_framebuffer DummyFramebuffer
Notes:
static struct gl_renderbuffer DummyRenderbuffer
static struct gl_framebuffer IncompleteFramebuffer
Macro Definition Documentation
NO_SAMPLES
#define NO_SAMPLES 1000
sentinal value, see below
Referenced by _mesa_NamedRenderbufferStorage(), _mesa_renderbuffer_storage(), _mesa_RenderbufferStorage(), renderbuffer_storage(), renderbuffer_storage_named(), and renderbuffer_storage_target().
Function Documentation
_es_RenderbufferStorageEXT()
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
References GLAPIENTRY, and renderbuffer_storage_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_base_fbo_format()
GLenum _mesa_base_fbo_format (struct gl_context * ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
This is similar to _mesa_base_tex_format() but the set of valid internal formats is different.
Note that even if a format is determined to be legal here, validation of the FBO may fail if the format is not supported by the driver/GPU.
Parameters
internalFormat as passed to glRenderbufferStorage()
Returns
the base internal format, or 0 if internalFormat is illegal
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_snorm, gl_context::Extensions, and gl_context::Version.
Referenced by _is_internalformat_supported(), _is_renderable(), _is_resource_supported(), _mesa_GetInternalformativ(), _mesa_is_renderable_texture_format(), _mesa_is_winsys_fbo(), _mesa_renderbuffer_storage(), and renderbuffer_storage().
_mesa_bind_framebuffers()
void _mesa_bind_framebuffers (struct gl_context * ctx, struct gl_framebuffer * newDrawFb, struct gl_framebuffer * newReadFb)
References _mesa_reference_framebuffer(), _NEW_BUFFERS, dd_function_table::BindFramebuffer, check_begin_texture_render(), check_end_texture_render(), gl_context::DrawBuffer, gl_context::Driver, DummyFramebuffer, FLUSH_VERTICES, GLAPIENTRY, and gl_context::ReadBuffer.
Referenced by _mesa_is_winsys_fbo(), and bind_framebuffer().
_mesa_BindFramebuffer()
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
References _mesa_is_gles(), bind_framebuffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_ClearNamedFramebufferfi(), _mesa_ClearNamedFramebufferfv(), _mesa_ClearNamedFramebufferiv(), _mesa_ClearNamedFramebufferuiv(), _mesa_DeleteFramebuffers(), and _mesa_is_winsys_fbo().
_mesa_BindFramebufferEXT()
void GLAPIENTRY _mesa_BindFramebufferEXT (GLenum target, GLuint framebuffer)
References bind_framebuffer(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_BindRenderbuffer()
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
References _mesa_is_gles(), bind_renderbuffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_DeleteRenderbuffers(), and _mesa_is_winsys_fbo().
_mesa_BindRenderbufferEXT()
void GLAPIENTRY _mesa_BindRenderbufferEXT (GLenum target, GLuint renderbuffer)
References bind_renderbuffer().
Referenced by _mesa_is_winsys_fbo().
_mesa_check_framebuffer_status()
GLenum _mesa_check_framebuffer_status (struct gl_context * ctx, struct gl_framebuffer * buffer)
References _mesa_is_winsys_fbo(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GLAPIENTRY, and IncompleteFramebuffer.
Referenced by _mesa_CheckFramebufferStatus(), _mesa_CheckNamedFramebufferStatus(), and _mesa_is_winsys_fbo().
_mesa_CheckFramebufferStatus()
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
References _mesa_check_framebuffer_status(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_target(), GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_is_winsys_fbo().
_mesa_CheckNamedFramebufferStatus()
GLenum GLAPIENTRY _mesa_CheckNamedFramebufferStatus (GLuint framebuffer, GLenum target)
References _mesa_check_framebuffer_status(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_framebuffer_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_CreateFramebuffers()
void GLAPIENTRY _mesa_CreateFramebuffers (GLsizei n, GLuint * framebuffers)
References create_framebuffers().
Referenced by _mesa_is_winsys_fbo().
_mesa_CreateRenderbuffers()
void GLAPIENTRY _mesa_CreateRenderbuffers (GLsizei n, GLuint * renderbuffers)
References create_render_buffers(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_DeleteFramebuffers()
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
References _mesa_BindFramebuffer(), _mesa_error(), _mesa_HashRemove(), _mesa_lookup_framebuffer(), _mesa_reference_framebuffer(), _NEW_BUFFERS, DummyFramebuffer, FLUSH_VERTICES, GET_CURRENT_CONTEXT, gl_framebuffer::Name, and gl_framebuffer::RefCount.
Referenced by _mesa_is_winsys_fbo().
_mesa_DeleteRenderbuffers()
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
References _mesa_BindRenderbuffer(), _mesa_detach_renderbuffer(), _mesa_error(), _mesa_HashRemove(), _mesa_is_user_fbo(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), _NEW_BUFFERS, DummyRenderbuffer, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and gl_renderbuffer::RefCount.
Referenced by _mesa_is_winsys_fbo().
_mesa_detach_renderbuffer()
bool _mesa_detach_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, const void * att)
Remove the specified renderbuffer or texture from any attachment point in the framebuffer.
Returns
true if the renderbuffer was detached from an attachment point. false otherwise.
References gl_framebuffer::Attachment, BUFFER_COUNT, GLAPIENTRY, invalidate_framebuffer(), remove_attachment(), gl_renderbuffer_attachment::Renderbuffer, and gl_renderbuffer_attachment::Texture.
Referenced by _mesa_DeleteRenderbuffers(), _mesa_is_winsys_fbo(), and unbind_texobj_from_fbo().
_mesa_DiscardFramebufferEXT()
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), GET_CURRENT_CONTEXT, and get_framebuffer_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_EGLImageTargetRenderbufferStorageOES()
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
References _mesa_error(), _NEW_BUFFERS, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_framebuffer_renderbuffer()
void _mesa_framebuffer_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb)
References _mesa_is_winsys_fbo(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, gl_context::Driver, FLUSH_VERTICES, and dd_function_table::FramebufferRenderbuffer.
Referenced by _mesa_is_winsys_fbo(), and framebuffer_renderbuffer().
_mesa_framebuffer_texture()
void _mesa_framebuffer_texture (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_texture_object * texObj, GLenum textarget, GLint level, GLuint layer, GLboolean layered, const char * caller)
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_winsys_fbo(), _mesa_tex_target_to_face(), _NEW_BUFFERS, gl_texture_object::_RenderToTexture, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::CubeMapFace, FLUSH_VERTICES, get_attachment(), invalidate_framebuffer(), gl_framebuffer::Mutex, remove_attachment(), reuse_framebuffer_texture_attachment(), set_texture_attachment(), gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_is_winsys_fbo(), _mesa_NamedFramebufferTexture(), _mesa_NamedFramebufferTextureLayer(), and framebuffer_texture_with_dims().
_mesa_FramebufferParameteri()
void GLAPIENTRY _mesa_FramebufferParameteri (GLenum target, GLenum pname, GLint param)
References _mesa_error(), _mesa_is_winsys_fbo(), framebuffer_parameteri(), GET_CURRENT_CONTEXT, and get_framebuffer_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferRenderbuffer()
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
References _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_renderbuffer_err(), framebuffer_renderbuffer(), GET_CURRENT_CONTEXT, get_framebuffer_target(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferRenderbuffer_sw()
void _mesa_FramebufferRenderbuffer_sw (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
References gl_renderbuffer::AttachedAnytime, get_attachment(), invalidate_framebuffer(), gl_framebuffer::Mutex, remove_attachment(), and set_renderbuffer_attachment().
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture()
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
References _mesa_enum_to_string(), _mesa_error(), _mesa_framebuffer_texture(), _mesa_has_geometry_shaders(), check_layered_texture_target(), check_level(), GET_CURRENT_CONTEXT, get_framebuffer_target(), get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture1D()
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References framebuffer_texture_with_dims(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture2D()
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References framebuffer_texture_with_dims(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture3D()
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint layer)
References framebuffer_texture_with_dims(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTextureLayer()
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
References _mesa_enum_to_string(), _mesa_error(), _mesa_framebuffer_texture(), check_layer(), check_level(), check_texture_target(), GET_CURRENT_CONTEXT, get_framebuffer_target(), get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_GenFramebuffers()
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint * framebuffers)
References create_framebuffers(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GenRenderbuffers()
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint * renderbuffers)
References create_render_buffers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_get_fb0_attachment()
static struct gl_renderbuffer_attachment* _mesa_get_fb0_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment) static
As above, but only used for getting attachments of the default / window-system framebuffer (not user-created framebuffer objects).
References _mesa_is_gles3(), _mesa_is_winsys_fbo(), gl_framebuffer::Attachment, BUFFER_AUX0, BUFFER_BACK_LEFT, BUFFER_BACK_RIGHT, BUFFER_DEPTH, BUFFER_FRONT_LEFT, BUFFER_FRONT_RIGHT, BUFFER_STENCIL, gl_config::doubleBufferMode, gl_context::DrawBuffer, gl_config::numAuxBuffers, gl_renderbuffer_attachment::Type, and gl_framebuffer::Visual.
Referenced by _mesa_get_framebuffer_attachment_parameter().
_mesa_get_framebuffer_attachment_parameter()
void _mesa_get_framebuffer_attachment_parameter (struct gl_context * ctx, struct gl_framebuffer * buffer, GLenum attachment, GLenum pname, GLint * params, const char * caller)
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_enum_to_string(), _mesa_error(), _mesa_get_fb0_attachment(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_has_geometry_shaders(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_winsys_fbo(), _mesa_problem(), _mesa_select_tex_image(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_extensions::ARB_framebuffer_object, gl_renderbuffer_attachment::CubeMapFace, gl_extensions::EXT_framebuffer_sRGB, gl_context::Extensions, gl_renderbuffer::Format, get_attachment(), get_component_bits(), GLAPIENTRY, if(), gl_renderbuffer_attachment::Layered, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, gl_texture_object::Name, gl_renderbuffer::Name, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, gl_context::Version, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetNamedFramebufferAttachmentParameteriv(), and _mesa_is_winsys_fbo().
_mesa_get_incomplete_framebuffer()
struct gl_framebuffer* _mesa_get_incomplete_framebuffer (void)
References IncompleteFramebuffer.
Referenced by _mesa_is_winsys_fbo(), check_compatible(), and handle_first_current().
_mesa_GetFramebufferAttachmentParameteriv()
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
References _mesa_enum_to_string(), _mesa_error(), _mesa_get_framebuffer_attachment_parameter(), GET_CURRENT_CONTEXT, get_framebuffer_target(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GetFramebufferParameteriv()
void GLAPIENTRY _mesa_GetFramebufferParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_parameteriv(), and get_framebuffer_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_GetNamedFramebufferAttachmentParameteriv()
void GLAPIENTRY _mesa_GetNamedFramebufferAttachmentParameteriv (GLuint framebuffer, GLenum attachment, GLenum pname, GLint * params)
References _mesa_get_framebuffer_attachment_parameter(), _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GetNamedFramebufferParameteriv()
void GLAPIENTRY _mesa_GetNamedFramebufferParameteriv (GLuint framebuffer, GLenum pname, GLint * param)
References _mesa_error(), _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, and get_framebuffer_parameteriv().
Referenced by _mesa_is_winsys_fbo().
_mesa_GetNamedRenderbufferParameteriv()
void GLAPIENTRY _mesa_GetNamedRenderbufferParameteriv (GLuint renderbuffer, GLenum pname, GLint * params)
References _mesa_error(), _mesa_lookup_renderbuffer(), DummyRenderbuffer, GET_CURRENT_CONTEXT, get_render_buffer_parameteriv(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GetRenderbufferParameteriv()
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_render_buffer_parameteriv(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_has_depthstencil_combined()
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer * fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
References gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_is_winsys_fbo(), _mesa_readpixels_needs_slow_path(), and _mesa_test_framebuffer_completeness().
_mesa_init_fbobjects()
void _mesa_init_fbobjects (struct gl_context * ctx)
References gl_renderbuffer::Delete, gl_framebuffer::Delete, delete_dummy_framebuffer(), delete_dummy_renderbuffer(), DummyFramebuffer, DummyRenderbuffer, IncompleteFramebuffer, gl_renderbuffer::Mutex, and gl_framebuffer::Mutex.
Referenced by _mesa_is_winsys_fbo(), and init_attrib_groups().
_mesa_InvalidateFramebuffer()
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_target(), GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_InvalidateNamedFramebufferData()
void GLAPIENTRY _mesa_InvalidateNamedFramebufferData (GLuint framebuffer, GLsizei numAttachments, const GLenum * attachments)
References _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_InvalidateNamedFramebufferSubData()
void GLAPIENTRY _mesa_InvalidateNamedFramebufferSubData (GLuint framebuffer, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_InvalidateSubFramebuffer()
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_target(), GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_is_legal_color_format()
GLboolean _mesa_is_legal_color_format (const struct gl_context * ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
References gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_rg, and gl_context::Extensions.
Referenced by _mesa_is_winsys_fbo(), _mesa_update_framebuffer_visual(), is_format_color_renderable(), and test_attachment_completeness().
_mesa_IsFramebuffer()
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
References _mesa_lookup_framebuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyFramebuffer, and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_IsRenderbuffer()
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
References _mesa_lookup_renderbuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyRenderbuffer, and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_lookup_framebuffer()
struct gl_framebuffer* _mesa_lookup_framebuffer (struct gl_context * ctx, GLuint id)
Helper routine for getting a gl_framebuffer.
References _mesa_HashLookup(), gl_shared_state::FrameBuffers, and gl_context::Shared.
Referenced by _mesa_DeleteFramebuffers(), _mesa_is_winsys_fbo(), _mesa_IsFramebuffer(), _mesa_lookup_framebuffer_err(), bind_framebuffer(), and get_label_pointer().
_mesa_lookup_framebuffer_err()
struct gl_framebuffer* _mesa_lookup_framebuffer_err (struct gl_context * ctx, GLuint id, const char * func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the framebuffer doesn't exist.
References _mesa_error(), _mesa_lookup_framebuffer(), and DummyFramebuffer.
Referenced by _mesa_BlitNamedFramebuffer(), _mesa_CheckNamedFramebufferStatus(), _mesa_GetNamedFramebufferAttachmentParameteriv(), _mesa_GetNamedFramebufferParameteriv(), _mesa_InvalidateNamedFramebufferData(), _mesa_InvalidateNamedFramebufferSubData(), _mesa_is_winsys_fbo(), _mesa_NamedFramebufferDrawBuffer(), _mesa_NamedFramebufferDrawBuffers(), _mesa_NamedFramebufferParameteri(), _mesa_NamedFramebufferReadBuffer(), _mesa_NamedFramebufferRenderbuffer(), _mesa_NamedFramebufferTexture(), and _mesa_NamedFramebufferTextureLayer().
_mesa_lookup_renderbuffer()
struct gl_renderbuffer* _mesa_lookup_renderbuffer (struct gl_context * ctx, GLuint id)
Helper routine for getting a gl_renderbuffer.
References _mesa_HashLookup(), gl_shared_state::RenderBuffers, and gl_context::Shared.
Referenced by _mesa_DeleteRenderbuffers(), _mesa_GetNamedRenderbufferParameteriv(), _mesa_is_winsys_fbo(), _mesa_IsRenderbuffer(), _mesa_lookup_renderbuffer_err(), bind_renderbuffer(), get_label_pointer(), get_renderbuffer_parameteriv(), prepare_target(), renderbuffer_purgeable(), renderbuffer_storage_named(), and renderbuffer_unpurgeable().
_mesa_lookup_renderbuffer_err()
struct gl_renderbuffer* _mesa_lookup_renderbuffer_err (struct gl_context * ctx, GLuint id, const char * func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the renderbuffer doesn't exist.
References _mesa_error(), _mesa_lookup_renderbuffer(), and DummyRenderbuffer.
Referenced by _mesa_FramebufferRenderbuffer(), _mesa_is_winsys_fbo(), and _mesa_NamedFramebufferRenderbuffer().
_mesa_NamedFramebufferParameteri()
void GLAPIENTRY _mesa_NamedFramebufferParameteri (GLuint framebuffer, GLenum pname, GLint param)
References _mesa_error(), _mesa_lookup_framebuffer_err(), framebuffer_parameteri(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedFramebufferRenderbuffer()
void GLAPIENTRY _mesa_NamedFramebufferRenderbuffer (GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
References _mesa_error(), _mesa_lookup_framebuffer_err(), _mesa_lookup_renderbuffer_err(), framebuffer_renderbuffer(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedFramebufferTexture()
void GLAPIENTRY _mesa_NamedFramebufferTexture (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level)
References _mesa_error(), _mesa_framebuffer_texture(), _mesa_has_geometry_shaders(), _mesa_lookup_framebuffer_err(), check_layered_texture_target(), check_level(), GET_CURRENT_CONTEXT, get_texture_for_framebuffer(), and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedFramebufferTextureLayer()
void GLAPIENTRY _mesa_NamedFramebufferTextureLayer (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer)
References _mesa_framebuffer_texture(), _mesa_lookup_framebuffer_err(), check_layer(), check_level(), check_texture_target(), GET_CURRENT_CONTEXT, get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedRenderbufferStorage()
void GLAPIENTRY _mesa_NamedRenderbufferStorage (GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, NO_SAMPLES, and renderbuffer_storage_named().
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedRenderbufferStorageMultisample()
void GLAPIENTRY _mesa_NamedRenderbufferStorageMultisample (GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
References renderbuffer_storage_named().
Referenced by _mesa_is_winsys_fbo().
_mesa_renderbuffer_storage()
void _mesa_renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples)
References gl_renderbuffer::_BaseFormat, _mesa_base_fbo_format(), _mesa_check_sample_count(), _mesa_HashWalk(), _NEW_BUFFERS, gl_renderbuffer::AllocStorage, gl_renderbuffer::AttachedAnytime, gl_context::Const, FLUSH_VERTICES, gl_renderbuffer::Format, gl_shared_state::FrameBuffers, GLuint, gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, invalidate_rb(), gl_constants::MaxRenderbufferSize, MESA_FORMAT_NONE, NO_SAMPLES, gl_renderbuffer::NumSamples, gl_context::Shared, and gl_renderbuffer::Width.
Referenced by _mesa_is_winsys_fbo(), and renderbuffer_storage().
_mesa_RenderbufferStorage()
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
References GLAPIENTRY, NO_SAMPLES, and renderbuffer_storage_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_RenderbufferStorageMultisample()
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalFormat, GLsizei width, GLsizei height)
References GLAPIENTRY, and renderbuffer_storage_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_test_framebuffer_completeness()
void _mesa_test_framebuffer_completeness (struct gl_context * ctx, struct gl_framebuffer * fb)
Test if the given framebuffer object is complete and update its Status field with the results.
Calls the ctx->Driver.ValidateFramebuffer() function to allow the driver to make hardware-specific validation/completeness checks. Also update the framebuffer's Width and Height fields if the framebuffer is complete.
References gl_framebuffer::_AllColorBuffersFixedPoint, gl_texture_image::_BaseFormat, gl_framebuffer::_HasAttachments, gl_framebuffer::_HasSNormOrFloatColorBuffer, gl_framebuffer::_IntegerBuffers, _mesa_get_format_datatype(), _mesa_has_depthstencil_combined(), _mesa_is_desktop_gl(), _mesa_is_format_integer_color(), _mesa_is_gles3(), _mesa_is_user_fbo(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_framebuffer_object, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, gl_renderbuffer_attachment::Complete, gl_context::Const, gl_framebuffer::DefaultGeometry, gl_renderbuffer::Depth, gl_context::Driver, gl_context::Extensions, fbo_incomplete(), gl_texture_image::FixedSampleLocations, FLUSH_VERTICES, gl_renderbuffer::Format, get_attachment(), GLAPIENTRY, GLuint, gl_texture_image::Height, gl_renderbuffer::Height, gl_framebuffer::Height, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, is_format_color_renderable(), is_legal_depth_format(), gl_renderbuffer_attachment::Layered, gl_constants::MaxColorAttachments, gl_constants::MaxDrawBuffers, gl_framebuffer::MaxNumLayers, MESA_FORMAT_NONE, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, test_attachment_completeness(), gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::Type, dd_function_table::ValidateFramebuffer, gl_texture_image::Width, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_check_framebuffer_status(), _mesa_is_winsys_fbo(), copytexsubimage_error_check(), copytexture_error_check(), renderbuffer_exists(), and update_framebuffer().
_mesa_update_texture_renderbuffer()
void _mesa_update_texture_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
By using a gl_renderbuffer (like user-allocated renderbuffers), drivers get to share most of their framebuffer rendering code between winsys, renderbuffer, and texture attachments.
The allocated renderbuffer uses a non-zero Name so that drivers can check it for determining vertical orientation, but we use ~0 to make it fairly unambiguous with actual user (non-texture) renderbuffers.
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_error(), gl_renderbuffer::AllocStorage, gl_renderbuffer_attachment::CubeMapFace, gl_renderbuffer::Depth, gl_texture_image::Depth2, gl_context::Driver, driver_RenderTexture_is_safe(), dd_function_table::FinishRenderTexture, gl_renderbuffer::Format, gl_renderbuffer::Height, gl_texture_image::Height2, gl_texture_object::Image, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, gl_renderbuffer::NeedsFinishRenderTexture, dd_function_table::NewRenderbuffer, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::RenderTexture, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer::Width, and gl_texture_image::Width2.
Referenced by _mesa_is_winsys_fbo(), check_rtt_cb(), and set_texture_attachment().
_mesa_validate_framebuffer()
void _mesa_validate_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
Drivers should probably override this.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer::Format, MESA_FORMAT_R9G9B9E5_FLOAT, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_is_winsys_fbo().
_pname_valid_for_default_framebuffer()
static bool _pname_valid_for_default_framebuffer (struct gl_context * ctx, GLenum pname) static
References _mesa_is_desktop_gl().
Referenced by get_framebuffer_parameteriv().
allocate_renderbuffer_locked()
static struct gl_renderbuffer* allocate_renderbuffer_locked (struct gl_context * ctx, GLuint renderbuffer, const char * func) static
References _mesa_error(), _mesa_HashInsertLocked(), gl_renderbuffer::AllocStorage, gl_context::Driver, dd_function_table::NewRenderbuffer, gl_shared_state::RenderBuffers, and gl_context::Shared.
Referenced by bind_renderbuffer(), and create_render_buffers().
att_incomplete()
static void att_incomplete (const char * msg) static
For debug only.
References _mesa_debug(), DEBUG_INCOMPLETE_FBO, and MESA_DEBUG_FLAGS.
Referenced by test_attachment_completeness().
bind_framebuffer()
static void bind_framebuffer (GLenum target, GLuint framebuffer, bool allow_user_names) static
References _mesa_bind_framebuffers(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_framebuffer(), DummyFramebuffer, and GET_CURRENT_CONTEXT.
Referenced by _mesa_BindFramebuffer(), and _mesa_BindFramebufferEXT().
bind_renderbuffer()
static void bind_renderbuffer (GLenum target, GLuint renderbuffer, bool allow_user_names) static
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), allocate_renderbuffer_locked(), DummyRenderbuffer, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_BindRenderbuffer(), and _mesa_BindRenderbufferEXT().
check_begin_texture_render()
static void check_begin_texture_render (struct gl_context * ctx, struct gl_framebuffer * fb) static
Check if any of the attachments of the given framebuffer are textures (render to texture).
Call ctx->Driver.RenderTexture() for such attachments.
References _mesa_is_winsys_fbo(), gl_framebuffer::Attachment, BUFFER_COUNT, gl_context::Driver, driver_RenderTexture_is_safe(), GLuint, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::RenderTexture, gl_renderbuffer::TexImage, and gl_renderbuffer_attachment::Texture.
Referenced by _mesa_bind_framebuffers().
check_end_texture_render()
static void check_end_texture_render (struct gl_context * ctx, struct gl_framebuffer * fb) static
Examine all the framebuffer's attachments to see if any are textures.
If so, call ctx->Driver.FinishRenderTexture() for each texture to notify the device driver that the texture image may have changed.
References _mesa_is_winsys_fbo(), gl_framebuffer::Attachment, dd_function_table::BindRenderbufferTexImage, BUFFER_COUNT, gl_context::Driver, dd_function_table::FinishRenderTexture, GLuint, gl_renderbuffer::NeedsFinishRenderTexture, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_bind_framebuffers().
check_layer()
static bool check_layer (struct gl_context * ctx, GLenum target, GLint layer, const char * caller) static
Common code called by gl*FramebufferTextureLayer() and glFramebufferTexture3D() to validate the layer.
Returns
true if no errors, false if errors
References _mesa_error(), gl_context::Const, GLuint, gl_constants::Max3DTextureLevels, and gl_constants::MaxArrayTextureLayers.
Referenced by _mesa_FramebufferTextureLayer(), _mesa_NamedFramebufferTextureLayer(), and framebuffer_texture_with_dims().
check_layered_texture_target()
static bool check_layered_texture_target (struct gl_context * ctx, GLenum target, const char * caller, GLboolean * layered) static
Common code called by gl*FramebufferTexture() to verify the texture target and decide whether or not the attachment should truly be considered layered.
Parameters
layered true if attachment should be considered layered, false if not
Returns
true if no errors, false if errors
References _mesa_enum_to_string(), and _mesa_error().
Referenced by _mesa_FramebufferTexture(), and _mesa_NamedFramebufferTexture().
check_level()
static bool check_level (struct gl_context * ctx, GLenum target, GLint level, const char * caller) static
Common code called by all gl*FramebufferTexture*() entry points to verify the level.
Returns
true if no errors, false if errors
References _mesa_error(), and _mesa_max_texture_levels().
Referenced by _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_NamedFramebufferTexture(), _mesa_NamedFramebufferTextureLayer(), and framebuffer_texture_with_dims().
check_textarget()
static bool check_textarget (struct gl_context * ctx, int dims, GLenum target, GLenum textarget, const char * caller) static
Common code called by glFramebufferTexture*D() to verify the texture target.
Returns
true if no errors, false if errors
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_cube_face(), _mesa_is_gles(), gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::NV_texture_rectangle, and gl_context::Version.
Referenced by framebuffer_texture_with_dims().
check_texture_target()
static bool check_texture_target (struct gl_context * ctx, GLenum target, const char * caller) static
Common code called by gl*FramebufferTextureLayer() to verify the texture target.
Returns
true if no errors, false if errors
References _mesa_enum_to_string(), _mesa_error(), gl_context::API, and API_OPENGL_CORE.
Referenced by _mesa_FramebufferTextureLayer(), and _mesa_NamedFramebufferTextureLayer().
create_framebuffers()
static void create_framebuffers (GLsizei n, GLuint * framebuffers, bool dsa) static
This is the implementation for glGenFramebuffers and glCreateFramebuffers.
It is not exposed to the rest of Mesa to encourage the use of nameless buffers in driver internals.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), DummyFramebuffer, GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
Referenced by _mesa_CreateFramebuffers(), and _mesa_GenFramebuffers().
create_render_buffers()
static void create_render_buffers (struct gl_context * ctx, GLsizei n, GLuint * renderbuffers, bool dsa) static
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), allocate_renderbuffer_locked(), DummyRenderbuffer, GLAPIENTRY, GLuint, gl_shared_state::RenderBuffers, and gl_context::Shared.
Referenced by _mesa_CreateRenderbuffers(), and _mesa_GenRenderbuffers().
delete_dummy_framebuffer()
static void delete_dummy_framebuffer (struct gl_framebuffer * fb) static
Referenced by _mesa_init_fbobjects().
delete_dummy_renderbuffer()
static void delete_dummy_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb) static
Referenced by _mesa_init_fbobjects().
driver_RenderTexture_is_safe()
static bool driver_RenderTexture_is_safe (const struct gl_renderbuffer_attachment * att) static
Verify a couple error conditions that will lead to an incomplete FBO and may cause problems for the driver's RenderTexture path.
References gl_renderbuffer_attachment::CubeMapFace, gl_texture_image::Depth, gl_texture_image::Height, gl_texture_object::Image, gl_texture_object::Target, gl_texture_image::TexObject, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_texture_image::Width, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_update_texture_renderbuffer(), and check_begin_texture_render().
fbo_incomplete()
static void fbo_incomplete (struct gl_context * ctx, const char * msg, int index) static
For debug only.
References _mesa_debug(), _mesa_gl_debug(), DEBUG_INCOMPLETE_FBO, GLuint, MESA_DEBUG_FLAGS, MESA_DEBUG_SEVERITY_MEDIUM, MESA_DEBUG_SOURCE_API, and MESA_DEBUG_TYPE_OTHER.
Referenced by _mesa_test_framebuffer_completeness().
framebuffer_parameteri()
static void framebuffer_parameteri (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum pname, GLint param, const char * func) static
ARB_framebuffer_no_attachment - Application passes requested param's here.
NOTE: NumSamples requested need not be _NumSamples which is what the hw supports.
References _mesa_error(), _mesa_is_gles31(), _NEW_BUFFERS, gl_context::Const, gl_framebuffer::DefaultGeometry, gl_context::Extensions, gl_framebuffer::FixedSampleLocations, GLAPIENTRY, gl_framebuffer::Height, invalidate_framebuffer(), gl_framebuffer::Layers, gl_constants::MaxFramebufferHeight, gl_constants::MaxFramebufferLayers, gl_constants::MaxFramebufferSamples, gl_constants::MaxFramebufferWidth, gl_context::NewState, gl_framebuffer::NumSamples, gl_extensions::OES_geometry_shader, and gl_framebuffer::Width.
Referenced by _mesa_FramebufferParameteri(), and _mesa_NamedFramebufferParameteri().
framebuffer_renderbuffer()
static void framebuffer_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb, const char * func) static
References _mesa_enum_to_string(), _mesa_error(), _mesa_framebuffer_renderbuffer(), _mesa_get_format_base_format(), _mesa_is_winsys_fbo(), gl_renderbuffer::Format, get_attachment(), GLAPIENTRY, and MESA_FORMAT_NONE.
Referenced by _mesa_FramebufferRenderbuffer(), and _mesa_NamedFramebufferRenderbuffer().
framebuffer_texture_with_dims()
static void framebuffer_texture_with_dims (int dims, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint layer, const char * caller) static
References _mesa_enum_to_string(), _mesa_error(), _mesa_framebuffer_texture(), check_layer(), check_level(), check_textarget(), GET_CURRENT_CONTEXT, get_framebuffer_target(), get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_FramebufferTexture1D(), _mesa_FramebufferTexture2D(), and _mesa_FramebufferTexture3D().
get_attachment()
static struct gl_renderbuffer_attachment* get_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, bool * is_color_attachment) static
Given a GL_*_ATTACHMENTn token, return a pointer to the corresponding gl_renderbuffer_attachment object.
This function is only used for user-created FB objects, not the default / window-system FB object. If attachment is GL_DEPTH_STENCIL_ATTACHMENT, return a pointer to the depth buffer attachment point. Returns if the attachment is a GL_COLOR_ATTACHMENTm_EXT on is_color_attachment, because several callers would return different errors if they don't find the attachment.
References _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_user_fbo(), gl_context::API, API_OPENGLES, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Const, GLuint, and gl_constants::MaxColorAttachments.
Referenced by _mesa_framebuffer_texture(), _mesa_FramebufferRenderbuffer_sw(), _mesa_get_framebuffer_attachment_parameter(), _mesa_test_framebuffer_completeness(), and framebuffer_renderbuffer().
get_component_bits()
static GLint get_component_bits (GLenum pname, GLenum baseFormat, mesa_format format) static
Helper function for _mesa_GetRenderbufferParameteriv() and _mesa_GetFramebufferAttachmentParameteriv() We have to be careful to respect the base format.
For example, if a renderbuffer/texture was created with internalFormat=GL_RGB but the driver actually chose a GL_RGBA format, when the user queries ALPHA_SIZE we need to return zero.
References _mesa_base_format_has_channel(), _mesa_get_format_bits(), and GLAPIENTRY.
Referenced by _mesa_get_framebuffer_attachment_parameter(), and get_render_buffer_parameteriv().
get_framebuffer_parameteriv()
static void get_framebuffer_parameteriv (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum pname, GLint * params, const char * func) static
References _mesa_error(), _mesa_geometric_samples(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_is_gles31(), _mesa_is_winsys_fbo(), _pname_valid_for_default_framebuffer(), gl_framebuffer::DefaultGeometry, gl_config::doubleBufferMode, gl_context::Extensions, gl_framebuffer::FixedSampleLocations, GLAPIENTRY, gl_framebuffer::Height, gl_framebuffer::Layers, gl_framebuffer::NumSamples, gl_extensions::OES_geometry_shader, gl_config::stereoMode, gl_framebuffer::Visual, and gl_framebuffer::Width.
Referenced by _mesa_GetFramebufferParameteriv(), and _mesa_GetNamedFramebufferParameteriv().
get_framebuffer_target()
static struct gl_framebuffer* get_framebuffer_target (struct gl_context * ctx, GLenum target) static
Return the gl_framebuffer object which corresponds to the given framebuffer target, such as GL_DRAW_FRAMEBUFFER.
Check support for GL_EXT_framebuffer_blit to determine if certain targets are legal.
Returns
gl_framebuffer pointer or NULL if target is illegal
References _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_context::DrawBuffer, and gl_context::ReadBuffer.
Referenced by _mesa_CheckFramebufferStatus(), _mesa_DiscardFramebufferEXT(), _mesa_FramebufferParameteri(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetFramebufferParameteriv(), _mesa_InvalidateFramebuffer(), _mesa_InvalidateSubFramebuffer(), and framebuffer_texture_with_dims().
get_render_buffer_parameteriv()
static void get_render_buffer_parameteriv (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum pname, GLint * params, const char * func) static
References gl_renderbuffer::_BaseFormat, _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_extensions::ARB_framebuffer_object, gl_context::Extensions, gl_renderbuffer::Format, get_component_bits(), GLAPIENTRY, gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, gl_renderbuffer::NumSamples, and gl_renderbuffer::Width.
Referenced by _mesa_GetNamedRenderbufferParameteriv(), and _mesa_GetRenderbufferParameteriv().
get_texture_for_framebuffer()
static bool get_texture_for_framebuffer (struct gl_context * ctx, GLuint texture, bool layered, const char * caller, struct gl_texture_object ** texObj) static
Common code called by gl*FramebufferTexture*() to retrieve the correct texture object pointer.
Parameters
texObj where the pointer to the texture object is returned. Note that a successful call may return texObj = NULL.
Returns
true if no errors, false if errors
References _mesa_error(), _mesa_lookup_texture(), and gl_texture_object::Target.
Referenced by _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_NamedFramebufferTexture(), _mesa_NamedFramebufferTextureLayer(), and framebuffer_texture_with_dims().
invalidate_framebuffer()
static void invalidate_framebuffer (struct gl_framebuffer * fb) static
Mark the given framebuffer as invalid.
This will force the test for framebuffer completeness to be done before the framebuffer is used.
References gl_framebuffer::_Status.
Referenced by _mesa_detach_renderbuffer(), _mesa_framebuffer_texture(), _mesa_FramebufferRenderbuffer_sw(), framebuffer_parameteri(), and set_texture_attachment().
invalidate_framebuffer_storage()
static void invalidate_framebuffer_storage (struct gl_context * ctx, struct gl_framebuffer * fb, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height, const char * name) static
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_winsys_fbo(), gl_context::API, API_OPENGL_COMPAT, gl_context::Const, GLAPIENTRY, and gl_constants::MaxColorAttachments.
Referenced by _mesa_InvalidateFramebuffer(), _mesa_InvalidateNamedFramebufferData(), _mesa_InvalidateNamedFramebufferSubData(), and _mesa_InvalidateSubFramebuffer().
invalidate_rb()
static void invalidate_rb (GLuint key, void * data, void * userData) static
Invalidate a renderbuffer attachment.
Called from _mesa_HashWalk().
References _mesa_is_user_fbo(), gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, GLuint, gl_renderbuffer_attachment::Renderbuffer, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_renderbuffer_storage().
is_format_color_renderable()
static GLboolean is_format_color_renderable (const struct gl_context * ctx, mesa_format format, GLenum internalFormat) static
Is the given base format a legal format for a color renderbuffer?
References _mesa_get_format_base_format(), _mesa_is_desktop_gl(), _mesa_is_legal_color_format(), and MESA_FORMAT_B10G10R10A2_UNORM.
Referenced by _mesa_test_framebuffer_completeness().
is_legal_depth_format()
static GLboolean is_legal_depth_format (const struct gl_context * ctx, GLenum baseFormat) static
Is the given base format a legal format for a depth/stencil renderbuffer?
Referenced by _mesa_test_framebuffer_completeness().
remove_attachment()
static void remove_attachment (struct gl_context * ctx, struct gl_renderbuffer_attachment * att) static
Remove any texture or renderbuffer attached to the given attachment point.
Update reference counts, etc.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), gl_renderbuffer_attachment::Complete, gl_context::Driver, dd_function_table::FinishRenderTexture, gl_renderbuffer::NeedsFinishRenderTexture, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_detach_renderbuffer(), _mesa_framebuffer_texture(), _mesa_FramebufferRenderbuffer_sw(), set_renderbuffer_attachment(), and set_texture_attachment().
renderbuffer_storage()
static void renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples, const char * func) static
Helper function used by renderbuffer_storage_direct() and renderbuffer_storage_target().
samples will be NO_SAMPLES if called by a non-multisample function.
References _mesa_base_fbo_format(), _mesa_check_sample_count(), _mesa_enum_to_string(), _mesa_error(), _mesa_renderbuffer_storage(), gl_context::Const, gl_constants::MaxRenderbufferSize, and NO_SAMPLES.
Referenced by renderbuffer_storage_named(), and renderbuffer_storage_target().
renderbuffer_storage_named()
static void renderbuffer_storage_named (GLuint renderbuffer, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples, const char * func) static
Helper function used by _mesa_NamedRenderbufferStorage*().
samples will be NO_SAMPLES if called by a non-multisample function.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_renderbuffer(), DummyRenderbuffer, GET_CURRENT_CONTEXT, MESA_VERBOSE, NO_SAMPLES, renderbuffer_storage(), and VERBOSE_API.
Referenced by _mesa_NamedRenderbufferStorage(), and _mesa_NamedRenderbufferStorageMultisample().
renderbuffer_storage_target()
static void renderbuffer_storage_target (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples, const char * func) static
Helper function used by _mesa_RenderbufferStorage() and _mesa_RenderbufferStorageMultisample().
samples will be NO_SAMPLES if called by _mesa_RenderbufferStorage().
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, NO_SAMPLES, renderbuffer_storage(), and VERBOSE_API.
Referenced by _es_RenderbufferStorageEXT(), _mesa_RenderbufferStorage(), and _mesa_RenderbufferStorageMultisample().
reuse_framebuffer_texture_attachment()
static void reuse_framebuffer_texture_attachment (struct gl_framebuffer * fb, gl_buffer_index dst, gl_buffer_index src) static
Replicate the src attachment point.
Used by framebuffer_texture() when the same texture is attached at GL_DEPTH_ATTACHMENT and GL_STENCIL_ATTACHMENT.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), gl_framebuffer::Attachment, gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_renderbuffer_attachment::Layered, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_framebuffer_texture().
set_renderbuffer_attachment()
static void set_renderbuffer_attachment (struct gl_context * ctx, struct gl_renderbuffer_attachment * att, struct gl_renderbuffer * rb) static
Bind a renderbuffer to an attachment point.
The previous binding, if any, will be removed first.
References _mesa_reference_renderbuffer(), gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::Layered, remove_attachment(), gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_FramebufferRenderbuffer_sw().
set_texture_attachment()
static void set_texture_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att, struct gl_texture_object * texObj, GLenum texTarget, GLuint level, GLuint layer, GLboolean layered) static
Bind a texture object to an attachment point.
The previous binding, if any, will be removed first.
References _mesa_reference_texobj(), _mesa_tex_target_to_face(), _mesa_update_texture_renderbuffer(), gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, dd_function_table::FinishRenderTexture, invalidate_framebuffer(), gl_renderbuffer_attachment::Layered, gl_renderbuffer::NeedsFinishRenderTexture, remove_attachment(), gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_framebuffer_texture().
test_attachment_completeness()
static void test_attachment_completeness (const struct gl_context * ctx, GLenum format, struct gl_renderbuffer_attachment * att) static
Test if an attachment point is complete and update its Complete field.
Parameters
format if GL_COLOR, this is a color attachment point, if GL_DEPTH, this is a depth component attachment point, if GL_STENCIL, this is a stencil component attachment point.
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, gl_texture_object::_IsFloat, gl_texture_object::_IsHalfFloat, _mesa_is_format_compressed(), _mesa_is_gles(), _mesa_is_legal_color_format(), gl_extensions::ARB_depth_texture, gl_extensions::ARB_texture_stencil8, att_incomplete(), gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_texture_image::Depth, gl_context::Extensions, gl_texture_image::Height, gl_renderbuffer::Height, gl_texture_object::Image, gl_renderbuffer::InternalFormat, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, gl_texture_image::Width, gl_renderbuffer::Width, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_test_framebuffer_completeness().
Variable Documentation
DummyFramebuffer
struct gl_framebuffer DummyFramebuffer static
Notes:
None of the GL_EXT_framebuffer_object functions are compiled into display lists.
Referenced by _mesa_bind_framebuffers(), _mesa_DeleteFramebuffers(), _mesa_init_fbobjects(), _mesa_IsFramebuffer(), _mesa_lookup_framebuffer_err(), bind_framebuffer(), and create_framebuffers().
DummyRenderbuffer
struct gl_renderbuffer DummyRenderbuffer static
Referenced by _mesa_DeleteRenderbuffers(), _mesa_GetNamedRenderbufferParameteriv(), _mesa_init_fbobjects(), _mesa_IsRenderbuffer(), _mesa_lookup_renderbuffer_err(), bind_renderbuffer(), create_render_buffers(), and renderbuffer_storage_named().
IncompleteFramebuffer
struct gl_framebuffer IncompleteFramebuffer static
Referenced by _mesa_check_framebuffer_status(), _mesa_get_incomplete_framebuffer(), and _mesa_init_fbobjects().