Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
fbobject.h File Reference
#include "compiler.h"
#include "glheader.h"
#include <stdbool.h>
Functions
static GLboolean _mesa_is_user_fbo (const struct gl_framebuffer *fb)
Is the given FBO a user-created FBO?
static GLboolean _mesa_is_winsys_fbo (const struct gl_framebuffer *fb)
Is the given FBO a window system FBO (like an X window)?
void _mesa_init_fbobjects (struct gl_context *ctx)
struct gl_framebuffer * _mesa_get_incomplete_framebuffer (void)
struct gl_renderbuffer * _mesa_lookup_renderbuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_renderbuffer.
struct gl_renderbuffer * _mesa_lookup_renderbuffer_err (struct gl_context *ctx, GLuint id, const char *func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the renderbuffer doesn't exist.
struct gl_framebuffer * _mesa_lookup_framebuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_framebuffer.
struct gl_framebuffer * _mesa_lookup_framebuffer_err (struct gl_context *ctx, GLuint id, const char *func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the framebuffer doesn't exist.
void _mesa_update_texture_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
void _mesa_FramebufferRenderbuffer_sw (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
void _mesa_framebuffer_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
void _mesa_renderbuffer_storage (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples)
void _mesa_validate_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer *fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
void _mesa_test_framebuffer_completeness (struct gl_context *ctx, struct gl_framebuffer *fb)
Test if the given framebuffer object is complete and update its Status field with the results.
GLboolean _mesa_is_legal_color_format (const struct gl_context *ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
GLenum _mesa_base_fbo_format (struct gl_context *ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
bool _mesa_detach_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, const void *att)
Remove the specified renderbuffer or texture from any attachment point in the framebuffer.
void _mesa_framebuffer_texture (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_texture_object *texObj, GLenum textarget, GLint level, GLuint layer, GLboolean layered, const char *caller)
GLenum _mesa_check_framebuffer_status (struct gl_context *ctx, struct gl_framebuffer *fb)
void _mesa_get_framebuffer_attachment_parameter (struct gl_context *ctx, struct gl_framebuffer *buffer, GLenum attachment, GLenum pname, GLint *params, const char *caller)
void _mesa_bind_framebuffers (struct gl_context *ctx, struct gl_framebuffer *newDrawFb, struct gl_framebuffer *newReadFb)
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
void GLAPIENTRY _mesa_BindRenderbufferEXT (GLenum target, GLuint renderbuffer)
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint *renderbuffers)
void GLAPIENTRY _mesa_CreateRenderbuffers (GLsizei n, GLuint *renderbuffers)
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
void GLAPIENTRY _mesa_NamedRenderbufferStorage (GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_NamedRenderbufferStorageMultisample (GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetNamedRenderbufferParameteriv (GLuint renderbuffer, GLenum pname, GLint *params)
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
void GLAPIENTRY _mesa_BindFramebufferEXT (GLenum target, GLuint framebuffer)
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint *framebuffers)
void GLAPIENTRY _mesa_CreateFramebuffers (GLsizei n, GLuint *framebuffers)
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
GLenum GLAPIENTRY _mesa_CheckNamedFramebufferStatus (GLuint framebuffer, GLenum target)
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_NamedFramebufferTextureLayer (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
void GLAPIENTRY _mesa_NamedFramebufferTexture (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void GLAPIENTRY _mesa_NamedFramebufferRenderbuffer (GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetNamedFramebufferAttachmentParameteriv (GLuint framebuffer, GLenum attachment, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_NamedFramebufferParameteri (GLuint framebuffer, GLenum pname, GLint param)
void GLAPIENTRY _mesa_GetNamedFramebufferParameteriv (GLuint framebuffer, GLenum pname, GLint *param)
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_InvalidateNamedFramebufferSubData (GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_InvalidateNamedFramebufferData (GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_FramebufferParameteri (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_GetFramebufferParameteriv (GLenum target, GLenum pname, GLint *params)
Function Documentation
_es_RenderbufferStorageEXT()
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
References GLAPIENTRY, and renderbuffer_storage_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_base_fbo_format()
GLenum _mesa_base_fbo_format (struct gl_context * ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
This is similar to _mesa_base_tex_format() but the set of valid internal formats is different.
Note that even if a format is determined to be legal here, validation of the FBO may fail if the format is not supported by the driver/GPU.
Parameters
internalFormat as passed to glRenderbufferStorage()
Returns
the base internal format, or 0 if internalFormat is illegal
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_snorm, gl_context::Extensions, and gl_context::Version.
Referenced by _is_internalformat_supported(), _is_renderable(), _is_resource_supported(), _mesa_GetInternalformativ(), _mesa_is_renderable_texture_format(), _mesa_is_winsys_fbo(), _mesa_renderbuffer_storage(), and renderbuffer_storage().
_mesa_bind_framebuffers()
void _mesa_bind_framebuffers (struct gl_context * ctx, struct gl_framebuffer * newDrawFb, struct gl_framebuffer * newReadFb)
References _mesa_reference_framebuffer(), _NEW_BUFFERS, dd_function_table::BindFramebuffer, check_begin_texture_render(), check_end_texture_render(), gl_context::DrawBuffer, gl_context::Driver, DummyFramebuffer, FLUSH_VERTICES, GLAPIENTRY, and gl_context::ReadBuffer.
Referenced by _mesa_is_winsys_fbo(), and bind_framebuffer().
_mesa_BindFramebuffer()
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
References _mesa_is_gles(), bind_framebuffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_ClearNamedFramebufferfi(), _mesa_ClearNamedFramebufferfv(), _mesa_ClearNamedFramebufferiv(), _mesa_ClearNamedFramebufferuiv(), _mesa_DeleteFramebuffers(), and _mesa_is_winsys_fbo().
_mesa_BindFramebufferEXT()
void GLAPIENTRY _mesa_BindFramebufferEXT (GLenum target, GLuint framebuffer)
References bind_framebuffer(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_BindRenderbuffer()
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
References _mesa_is_gles(), bind_renderbuffer(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_DeleteRenderbuffers(), and _mesa_is_winsys_fbo().
_mesa_BindRenderbufferEXT()
void GLAPIENTRY _mesa_BindRenderbufferEXT (GLenum target, GLuint renderbuffer)
References bind_renderbuffer().
Referenced by _mesa_is_winsys_fbo().
_mesa_check_framebuffer_status()
GLenum _mesa_check_framebuffer_status (struct gl_context * ctx, struct gl_framebuffer * fb)
References _mesa_is_winsys_fbo(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GLAPIENTRY, and IncompleteFramebuffer.
Referenced by _mesa_CheckFramebufferStatus(), _mesa_CheckNamedFramebufferStatus(), and _mesa_is_winsys_fbo().
_mesa_CheckFramebufferStatus()
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
References _mesa_check_framebuffer_status(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_target(), GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_is_winsys_fbo().
_mesa_CheckNamedFramebufferStatus()
GLenum GLAPIENTRY _mesa_CheckNamedFramebufferStatus (GLuint framebuffer, GLenum target)
References _mesa_check_framebuffer_status(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_framebuffer_err(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_CreateFramebuffers()
void GLAPIENTRY _mesa_CreateFramebuffers (GLsizei n, GLuint * framebuffers)
References create_framebuffers().
Referenced by _mesa_is_winsys_fbo().
_mesa_CreateRenderbuffers()
void GLAPIENTRY _mesa_CreateRenderbuffers (GLsizei n, GLuint * renderbuffers)
References create_render_buffers(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_DeleteFramebuffers()
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
References _mesa_BindFramebuffer(), _mesa_error(), _mesa_HashRemove(), _mesa_lookup_framebuffer(), _mesa_reference_framebuffer(), _NEW_BUFFERS, DummyFramebuffer, FLUSH_VERTICES, GET_CURRENT_CONTEXT, gl_framebuffer::Name, and gl_framebuffer::RefCount.
Referenced by _mesa_is_winsys_fbo().
_mesa_DeleteRenderbuffers()
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
References _mesa_BindRenderbuffer(), _mesa_detach_renderbuffer(), _mesa_error(), _mesa_HashRemove(), _mesa_is_user_fbo(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), _NEW_BUFFERS, DummyRenderbuffer, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and gl_renderbuffer::RefCount.
Referenced by _mesa_is_winsys_fbo().
_mesa_detach_renderbuffer()
bool _mesa_detach_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, const void * att)
Remove the specified renderbuffer or texture from any attachment point in the framebuffer.
Returns
true if the renderbuffer was detached from an attachment point. false otherwise.
References gl_framebuffer::Attachment, BUFFER_COUNT, GLAPIENTRY, invalidate_framebuffer(), remove_attachment(), gl_renderbuffer_attachment::Renderbuffer, and gl_renderbuffer_attachment::Texture.
Referenced by _mesa_DeleteRenderbuffers(), _mesa_is_winsys_fbo(), and unbind_texobj_from_fbo().
_mesa_DiscardFramebufferEXT()
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), GET_CURRENT_CONTEXT, and get_framebuffer_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_EGLImageTargetRenderbufferStorageOES()
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
References _mesa_error(), _NEW_BUFFERS, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_framebuffer_renderbuffer()
void _mesa_framebuffer_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb)
References _mesa_is_winsys_fbo(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, gl_context::Driver, FLUSH_VERTICES, and dd_function_table::FramebufferRenderbuffer.
Referenced by _mesa_is_winsys_fbo(), and framebuffer_renderbuffer().
_mesa_framebuffer_texture()
void _mesa_framebuffer_texture (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_texture_object * texObj, GLenum textarget, GLint level, GLuint layer, GLboolean layered, const char * caller)
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_winsys_fbo(), _mesa_tex_target_to_face(), _NEW_BUFFERS, gl_texture_object::_RenderToTexture, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::CubeMapFace, FLUSH_VERTICES, get_attachment(), invalidate_framebuffer(), gl_framebuffer::Mutex, remove_attachment(), reuse_framebuffer_texture_attachment(), set_texture_attachment(), gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_FramebufferTexture(), _mesa_FramebufferTextureLayer(), _mesa_is_winsys_fbo(), _mesa_NamedFramebufferTexture(), _mesa_NamedFramebufferTextureLayer(), and framebuffer_texture_with_dims().
_mesa_FramebufferParameteri()
void GLAPIENTRY _mesa_FramebufferParameteri (GLenum target, GLenum pname, GLint param)
References _mesa_error(), _mesa_is_winsys_fbo(), framebuffer_parameteri(), GET_CURRENT_CONTEXT, and get_framebuffer_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferRenderbuffer()
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
References _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_renderbuffer_err(), framebuffer_renderbuffer(), GET_CURRENT_CONTEXT, get_framebuffer_target(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferRenderbuffer_sw()
void _mesa_FramebufferRenderbuffer_sw (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
References gl_renderbuffer::AttachedAnytime, get_attachment(), invalidate_framebuffer(), gl_framebuffer::Mutex, remove_attachment(), and set_renderbuffer_attachment().
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture()
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
References _mesa_enum_to_string(), _mesa_error(), _mesa_framebuffer_texture(), _mesa_has_geometry_shaders(), check_layered_texture_target(), check_level(), GET_CURRENT_CONTEXT, get_framebuffer_target(), get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture1D()
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References framebuffer_texture_with_dims(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture2D()
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References framebuffer_texture_with_dims(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTexture3D()
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint layer)
References framebuffer_texture_with_dims(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_FramebufferTextureLayer()
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
References _mesa_enum_to_string(), _mesa_error(), _mesa_framebuffer_texture(), check_layer(), check_level(), check_texture_target(), GET_CURRENT_CONTEXT, get_framebuffer_target(), get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_GenFramebuffers()
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint * framebuffers)
References create_framebuffers(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GenRenderbuffers()
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint * renderbuffers)
References create_render_buffers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_get_framebuffer_attachment_parameter()
void _mesa_get_framebuffer_attachment_parameter (struct gl_context * ctx, struct gl_framebuffer * buffer, GLenum attachment, GLenum pname, GLint * params, const char * caller)
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_enum_to_string(), _mesa_error(), _mesa_get_fb0_attachment(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_has_geometry_shaders(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_winsys_fbo(), _mesa_problem(), _mesa_select_tex_image(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_extensions::ARB_framebuffer_object, gl_renderbuffer_attachment::CubeMapFace, gl_extensions::EXT_framebuffer_sRGB, gl_context::Extensions, gl_renderbuffer::Format, get_attachment(), get_component_bits(), GLAPIENTRY, if(), gl_renderbuffer_attachment::Layered, MESA_FORMAT_S_UINT8, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, gl_texture_object::Name, gl_renderbuffer::Name, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, gl_context::Version, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetNamedFramebufferAttachmentParameteriv(), and _mesa_is_winsys_fbo().
_mesa_get_incomplete_framebuffer()
struct gl_framebuffer* _mesa_get_incomplete_framebuffer (void)
References IncompleteFramebuffer.
Referenced by _mesa_is_winsys_fbo(), check_compatible(), and handle_first_current().
_mesa_GetFramebufferAttachmentParameteriv()
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
References _mesa_enum_to_string(), _mesa_error(), _mesa_get_framebuffer_attachment_parameter(), GET_CURRENT_CONTEXT, get_framebuffer_target(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GetFramebufferParameteriv()
void GLAPIENTRY _mesa_GetFramebufferParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_parameteriv(), and get_framebuffer_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_GetNamedFramebufferAttachmentParameteriv()
void GLAPIENTRY _mesa_GetNamedFramebufferAttachmentParameteriv (GLuint framebuffer, GLenum attachment, GLenum pname, GLint * params)
References _mesa_get_framebuffer_attachment_parameter(), _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GetNamedFramebufferParameteriv()
void GLAPIENTRY _mesa_GetNamedFramebufferParameteriv (GLuint framebuffer, GLenum pname, GLint * param)
References _mesa_error(), _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, and get_framebuffer_parameteriv().
Referenced by _mesa_is_winsys_fbo().
_mesa_GetNamedRenderbufferParameteriv()
void GLAPIENTRY _mesa_GetNamedRenderbufferParameteriv (GLuint renderbuffer, GLenum pname, GLint * params)
References _mesa_error(), _mesa_lookup_renderbuffer(), DummyRenderbuffer, GET_CURRENT_CONTEXT, get_render_buffer_parameteriv(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_GetRenderbufferParameteriv()
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_render_buffer_parameteriv(), and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_has_depthstencil_combined()
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer * fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
References gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_is_winsys_fbo(), _mesa_readpixels_needs_slow_path(), and _mesa_test_framebuffer_completeness().
_mesa_init_fbobjects()
void _mesa_init_fbobjects (struct gl_context * ctx)
References gl_renderbuffer::Delete, gl_framebuffer::Delete, delete_dummy_framebuffer(), delete_dummy_renderbuffer(), DummyFramebuffer, DummyRenderbuffer, IncompleteFramebuffer, gl_renderbuffer::Mutex, and gl_framebuffer::Mutex.
Referenced by _mesa_is_winsys_fbo(), and init_attrib_groups().
_mesa_InvalidateFramebuffer()
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_target(), GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_InvalidateNamedFramebufferData()
void GLAPIENTRY _mesa_InvalidateNamedFramebufferData (GLuint framebuffer, GLsizei numAttachments, const GLenum * attachments)
References _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_InvalidateNamedFramebufferSubData()
void GLAPIENTRY _mesa_InvalidateNamedFramebufferSubData (GLuint framebuffer, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_lookup_framebuffer_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_InvalidateSubFramebuffer()
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, get_framebuffer_target(), GLAPIENTRY, and invalidate_framebuffer_storage().
Referenced by _mesa_is_winsys_fbo().
_mesa_is_legal_color_format()
GLboolean _mesa_is_legal_color_format (const struct gl_context * ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
References gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_rg, and gl_context::Extensions.
Referenced by _mesa_is_winsys_fbo(), _mesa_update_framebuffer_visual(), is_format_color_renderable(), and test_attachment_completeness().
_mesa_is_user_fbo()
static GLboolean _mesa_is_user_fbo (const struct gl_framebuffer * fb) inline static
Is the given FBO a user-created FBO?
References gl_framebuffer::Name.
Referenced by _mesa_add_renderbuffer(), _mesa_CopyPixels(), _mesa_DeleteRenderbuffers(), _mesa_DiscardFramebufferEXT(), _mesa_is_front_buffer_drawing(), _mesa_is_front_buffer_reading(), _mesa_ReadnPixelsARB(), _mesa_test_framebuffer_completeness(), _mesa_update_draw_buffer_bounds(), check_rtt_cb(), copytexsubimage_error_check(), copytexture_error_check(), draw_buffers(), get_attachment(), invalidate_rb(), supported_buffer_bitmask(), unbind_texobj_from_fbo(), update_framebuffer_size(), and updated_drawbuffers().
_mesa_is_winsys_fbo()
static GLboolean _mesa_is_winsys_fbo (const struct gl_framebuffer * fb) inline static
Is the given FBO a window system FBO (like an X window)?
References _es_RenderbufferStorageEXT(), _mesa_base_fbo_format(), _mesa_bind_framebuffers(), _mesa_BindFramebuffer(), _mesa_BindFramebufferEXT(), _mesa_BindRenderbuffer(), _mesa_BindRenderbufferEXT(), _mesa_check_framebuffer_status(), _mesa_CheckFramebufferStatus(), _mesa_CheckNamedFramebufferStatus(), _mesa_CreateFramebuffers(), _mesa_CreateRenderbuffers(), _mesa_DeleteFramebuffers(), _mesa_DeleteRenderbuffers(), _mesa_detach_renderbuffer(), _mesa_DiscardFramebufferEXT(), _mesa_EGLImageTargetRenderbufferStorageOES(), _mesa_framebuffer_renderbuffer(), _mesa_framebuffer_texture(), _mesa_FramebufferParameteri(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferRenderbuffer_sw(), _mesa_FramebufferTexture(), _mesa_FramebufferTexture1D(), _mesa_FramebufferTexture2D(), _mesa_FramebufferTexture3D(), _mesa_FramebufferTextureLayer(), _mesa_GenFramebuffers(), _mesa_GenRenderbuffers(), _mesa_get_framebuffer_attachment_parameter(), _mesa_get_incomplete_framebuffer(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetFramebufferParameteriv(), _mesa_GetNamedFramebufferAttachmentParameteriv(), _mesa_GetNamedFramebufferParameteriv(), _mesa_GetNamedRenderbufferParameteriv(), _mesa_GetRenderbufferParameteriv(), _mesa_has_depthstencil_combined(), _mesa_init_fbobjects(), _mesa_InvalidateFramebuffer(), _mesa_InvalidateNamedFramebufferData(), _mesa_InvalidateNamedFramebufferSubData(), _mesa_InvalidateSubFramebuffer(), _mesa_is_legal_color_format(), _mesa_IsFramebuffer(), _mesa_IsRenderbuffer(), _mesa_lookup_framebuffer(), _mesa_lookup_framebuffer_err(), _mesa_lookup_renderbuffer(), _mesa_lookup_renderbuffer_err(), _mesa_NamedFramebufferParameteri(), _mesa_NamedFramebufferRenderbuffer(), _mesa_NamedFramebufferTexture(), _mesa_NamedFramebufferTextureLayer(), _mesa_NamedRenderbufferStorage(), _mesa_NamedRenderbufferStorageMultisample(), _mesa_renderbuffer_storage(), _mesa_RenderbufferStorage(), _mesa_RenderbufferStorageMultisample(), _mesa_test_framebuffer_completeness(), _mesa_update_texture_renderbuffer(), _mesa_validate_framebuffer(), GLAPIENTRY, GLuint, gl_framebuffer::Name, and x.
Referenced by _mesa_check_framebuffer_status(), _mesa_DiscardFramebufferEXT(), _mesa_drawbuffers(), _mesa_framebuffer_renderbuffer(), _mesa_framebuffer_texture(), _mesa_FramebufferParameteri(), _mesa_get_fb0_attachment(), _mesa_get_framebuffer_attachment_parameter(), _mesa_GetMultisamplefv(), _mesa_make_current(), _mesa_readbuffer(), _mesa_resize_framebuffer(), _mesa_update_draw_buffers(), check_begin_texture_render(), check_end_texture_render(), draw_buffers(), framebuffer_renderbuffer(), get_framebuffer_parameteriv(), invalidate_framebuffer_storage(), and update_framebuffer().
_mesa_IsFramebuffer()
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
References _mesa_lookup_framebuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyFramebuffer, and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_IsRenderbuffer()
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
References _mesa_lookup_renderbuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyRenderbuffer, and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_lookup_framebuffer()
struct gl_framebuffer* _mesa_lookup_framebuffer (struct gl_context * ctx, GLuint id)
Helper routine for getting a gl_framebuffer.
References _mesa_HashLookup(), gl_shared_state::FrameBuffers, and gl_context::Shared.
Referenced by _mesa_DeleteFramebuffers(), _mesa_is_winsys_fbo(), _mesa_IsFramebuffer(), _mesa_lookup_framebuffer_err(), bind_framebuffer(), and get_label_pointer().
_mesa_lookup_framebuffer_err()
struct gl_framebuffer* _mesa_lookup_framebuffer_err (struct gl_context * ctx, GLuint id, const char * func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the framebuffer doesn't exist.
References _mesa_error(), _mesa_lookup_framebuffer(), and DummyFramebuffer.
Referenced by _mesa_BlitNamedFramebuffer(), _mesa_CheckNamedFramebufferStatus(), _mesa_GetNamedFramebufferAttachmentParameteriv(), _mesa_GetNamedFramebufferParameteriv(), _mesa_InvalidateNamedFramebufferData(), _mesa_InvalidateNamedFramebufferSubData(), _mesa_is_winsys_fbo(), _mesa_NamedFramebufferDrawBuffer(), _mesa_NamedFramebufferDrawBuffers(), _mesa_NamedFramebufferParameteri(), _mesa_NamedFramebufferReadBuffer(), _mesa_NamedFramebufferRenderbuffer(), _mesa_NamedFramebufferTexture(), and _mesa_NamedFramebufferTextureLayer().
_mesa_lookup_renderbuffer()
struct gl_renderbuffer* _mesa_lookup_renderbuffer (struct gl_context * ctx, GLuint id)
Helper routine for getting a gl_renderbuffer.
References _mesa_HashLookup(), gl_shared_state::RenderBuffers, and gl_context::Shared.
Referenced by _mesa_DeleteRenderbuffers(), _mesa_GetNamedRenderbufferParameteriv(), _mesa_is_winsys_fbo(), _mesa_IsRenderbuffer(), _mesa_lookup_renderbuffer_err(), bind_renderbuffer(), get_label_pointer(), get_renderbuffer_parameteriv(), prepare_target(), renderbuffer_purgeable(), renderbuffer_storage_named(), and renderbuffer_unpurgeable().
_mesa_lookup_renderbuffer_err()
struct gl_renderbuffer* _mesa_lookup_renderbuffer_err (struct gl_context * ctx, GLuint id, const char * func)
A convenience function for direct state access that throws GL_INVALID_OPERATION if the renderbuffer doesn't exist.
References _mesa_error(), _mesa_lookup_renderbuffer(), and DummyRenderbuffer.
Referenced by _mesa_FramebufferRenderbuffer(), _mesa_is_winsys_fbo(), and _mesa_NamedFramebufferRenderbuffer().
_mesa_NamedFramebufferParameteri()
void GLAPIENTRY _mesa_NamedFramebufferParameteri (GLuint framebuffer, GLenum pname, GLint param)
References _mesa_error(), _mesa_lookup_framebuffer_err(), framebuffer_parameteri(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedFramebufferRenderbuffer()
void GLAPIENTRY _mesa_NamedFramebufferRenderbuffer (GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
References _mesa_error(), _mesa_lookup_framebuffer_err(), _mesa_lookup_renderbuffer_err(), framebuffer_renderbuffer(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedFramebufferTexture()
void GLAPIENTRY _mesa_NamedFramebufferTexture (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level)
References _mesa_error(), _mesa_framebuffer_texture(), _mesa_has_geometry_shaders(), _mesa_lookup_framebuffer_err(), check_layered_texture_target(), check_level(), GET_CURRENT_CONTEXT, get_texture_for_framebuffer(), and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedFramebufferTextureLayer()
void GLAPIENTRY _mesa_NamedFramebufferTextureLayer (GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer)
References _mesa_framebuffer_texture(), _mesa_lookup_framebuffer_err(), check_layer(), check_level(), check_texture_target(), GET_CURRENT_CONTEXT, get_texture_for_framebuffer(), GLAPIENTRY, and gl_texture_object::Target.
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedRenderbufferStorage()
void GLAPIENTRY _mesa_NamedRenderbufferStorage (GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, NO_SAMPLES, and renderbuffer_storage_named().
Referenced by _mesa_is_winsys_fbo().
_mesa_NamedRenderbufferStorageMultisample()
void GLAPIENTRY _mesa_NamedRenderbufferStorageMultisample (GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
References renderbuffer_storage_named().
Referenced by _mesa_is_winsys_fbo().
_mesa_renderbuffer_storage()
void _mesa_renderbuffer_storage (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples)
References gl_renderbuffer::_BaseFormat, _mesa_base_fbo_format(), _mesa_check_sample_count(), _mesa_HashWalk(), _NEW_BUFFERS, gl_renderbuffer::AllocStorage, gl_renderbuffer::AttachedAnytime, gl_context::Const, FLUSH_VERTICES, gl_renderbuffer::Format, gl_shared_state::FrameBuffers, GLuint, gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, invalidate_rb(), gl_constants::MaxRenderbufferSize, MESA_FORMAT_NONE, NO_SAMPLES, gl_renderbuffer::NumSamples, gl_context::Shared, and gl_renderbuffer::Width.
Referenced by _mesa_is_winsys_fbo(), and renderbuffer_storage().
_mesa_RenderbufferStorage()
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, NO_SAMPLES, and renderbuffer_storage_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_RenderbufferStorageMultisample()
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, and renderbuffer_storage_target().
Referenced by _mesa_is_winsys_fbo().
_mesa_test_framebuffer_completeness()
void _mesa_test_framebuffer_completeness (struct gl_context * ctx, struct gl_framebuffer * fb)
Test if the given framebuffer object is complete and update its Status field with the results.
Calls the ctx->Driver.ValidateFramebuffer() function to allow the driver to make hardware-specific validation/completeness checks. Also update the framebuffer's Width and Height fields if the framebuffer is complete.
References gl_framebuffer::_AllColorBuffersFixedPoint, gl_texture_image::_BaseFormat, gl_framebuffer::_HasAttachments, gl_framebuffer::_HasSNormOrFloatColorBuffer, gl_framebuffer::_IntegerBuffers, _mesa_get_format_datatype(), _mesa_has_depthstencil_combined(), _mesa_is_desktop_gl(), _mesa_is_format_integer_color(), _mesa_is_gles3(), _mesa_is_user_fbo(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_framebuffer_object, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, gl_renderbuffer_attachment::Complete, gl_context::Const, gl_framebuffer::DefaultGeometry, gl_renderbuffer::Depth, gl_context::Driver, gl_context::Extensions, fbo_incomplete(), gl_texture_image::FixedSampleLocations, FLUSH_VERTICES, gl_renderbuffer::Format, get_attachment(), GLAPIENTRY, GLuint, gl_texture_image::Height, gl_renderbuffer::Height, gl_framebuffer::Height, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, is_format_color_renderable(), is_legal_depth_format(), gl_renderbuffer_attachment::Layered, gl_constants::MaxColorAttachments, gl_constants::MaxDrawBuffers, gl_framebuffer::MaxNumLayers, MESA_FORMAT_NONE, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, test_attachment_completeness(), gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::Type, dd_function_table::ValidateFramebuffer, gl_texture_image::Width, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_check_framebuffer_status(), _mesa_is_winsys_fbo(), copytexsubimage_error_check(), copytexture_error_check(), renderbuffer_exists(), and update_framebuffer().
_mesa_update_texture_renderbuffer()
void _mesa_update_texture_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
By using a gl_renderbuffer (like user-allocated renderbuffers), drivers get to share most of their framebuffer rendering code between winsys, renderbuffer, and texture attachments.
The allocated renderbuffer uses a non-zero Name so that drivers can check it for determining vertical orientation, but we use ~0 to make it fairly unambiguous with actual user (non-texture) renderbuffers.
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_error(), gl_renderbuffer::AllocStorage, gl_renderbuffer_attachment::CubeMapFace, gl_renderbuffer::Depth, gl_texture_image::Depth2, gl_context::Driver, driver_RenderTexture_is_safe(), dd_function_table::FinishRenderTexture, gl_renderbuffer::Format, gl_renderbuffer::Height, gl_texture_image::Height2, gl_texture_object::Image, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, gl_renderbuffer::NeedsFinishRenderTexture, dd_function_table::NewRenderbuffer, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::RenderTexture, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer::Width, and gl_texture_image::Width2.
Referenced by _mesa_is_winsys_fbo(), check_rtt_cb(), and set_texture_attachment().
_mesa_validate_framebuffer()
void _mesa_validate_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
Drivers should probably override this.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer::Format, MESA_FORMAT_R9G9B9E5_FLOAT, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_is_winsys_fbo().