Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
feedback.h File Reference
#include "main/mtypes.h"
Functions
void GLAPIENTRY _mesa_FeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer)
void GLAPIENTRY _mesa_PassThrough (GLfloat token)
void GLAPIENTRY _mesa_SelectBuffer (GLsizei size, GLuint *buffer)
Establish a buffer for selection mode values.
void GLAPIENTRY _mesa_InitNames (void)
Initialize the name stack.
void GLAPIENTRY _mesa_LoadName (GLuint name)
Load the top-most name of the name stack.
void GLAPIENTRY _mesa_PushName (GLuint name)
Push a name into the name stack.
void GLAPIENTRY _mesa_PopName (void)
Pop a name into the name stack.
GLint GLAPIENTRY _mesa_RenderMode (GLenum mode)
Set rasterization mode.
void _mesa_feedback_vertex (struct gl_context *ctx, const GLfloat win[4], const GLfloat color[4], const GLfloat texcoord[4])
Put a vertex into the feedback buffer.
static void _mesa_feedback_token (struct gl_context *ctx, GLfloat token)
void _mesa_update_hitflag (struct gl_context *ctx, GLfloat z)
Update the hit flag and the maximum and minimum depth values.
void _mesa_init_feedback (struct gl_context *ctx)
Initialize context feedback data.
Function Documentation
_mesa_feedback_token()
static void _mesa_feedback_token (struct gl_context * ctx, GLfloat token) inline static
References _mesa_init_feedback(), _mesa_update_hitflag(), gl_feedback::Buffer, gl_feedback::BufferSize, gl_feedback::Count, and gl_context::Feedback.
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), _mesa_DrawPixels(), _mesa_feedback_vertex(), and _mesa_PassThrough().
_mesa_feedback_vertex()
void _mesa_feedback_vertex (struct gl_context * ctx, const GLfloat win[4], const GLfloat color[4], const GLfloat texcoord[4])
Put a vertex into the feedback buffer.
References gl_feedback::_Mask, _mesa_feedback_token(), FB_3D, FB_4D, FB_COLOR, FB_TEXTURE, gl_context::Feedback, and GLAPIENTRY.
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), and _mesa_DrawPixels().
_mesa_FeedbackBuffer()
void GLAPIENTRY _mesa_FeedbackBuffer (GLsizei size, GLenum type, GLfloat * buffer)
References _mesa_error(), _NEW_RENDERMODE, FB_3D, FB_4D, FB_COLOR, FB_TEXTURE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_init_feedback()
void _mesa_init_feedback (struct gl_context * ctx)
Initialize context feedback data.
References gl_feedback::Buffer, gl_selection::Buffer, gl_selection::BufferCount, gl_feedback::BufferSize, gl_selection::BufferSize, gl_feedback::Count, gl_context::Feedback, gl_selection::Hits, gl_selection::NameStackDepth, gl_context::RenderMode, gl_context::Select, and gl_feedback::Type.
Referenced by _mesa_feedback_token(), and init_attrib_groups().
_mesa_InitNames()
void GLAPIENTRY _mesa_InitNames (void)
Initialize the name stack.
Verifies we are in select mode and resets the name stack depth and resets the hit record data in gl_selection. Marks new render mode in __struct gl_contextRec::NewState.
References _NEW_RENDERMODE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and write_hit_record().
_mesa_LoadName()
void GLAPIENTRY _mesa_LoadName (GLuint name)
Load the top-most name of the name stack.
Parameters
name name.
Verifies we are in selection mode and that the name stack is not empty. Flushes vertices. If there is a hit flag writes it (via write_hit_record()), and replace the top-most name in the stack.
sa __struct gl_contextRec::Select.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_NAME_STACK_DEPTH, and write_hit_record().
_mesa_PassThrough()
void GLAPIENTRY _mesa_PassThrough (GLfloat token)
References _mesa_feedback_token(), FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
_mesa_PopName()
void GLAPIENTRY _mesa_PopName (void)
Pop a name into the name stack.
Verifies we are in selection mode and that the name stack is not empty. Flushes vertices. If there is a hit flag writes it (via write_hit_record()), and removes top-most name in the name stack.
sa __struct gl_contextRec::Select.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and write_hit_record().
_mesa_PushName()
void GLAPIENTRY _mesa_PushName (GLuint name)
Push a name into the name stack.
Parameters
name name.
Verifies we are in selection mode and that the name stack is not full. Flushes vertices. If there is a hit flag writes it (via write_hit_record()), and adds the name to the top of the name stack.
sa __struct gl_contextRec::Select.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_NAME_STACK_DEPTH, and write_hit_record().
_mesa_RenderMode()
GLint GLAPIENTRY _mesa_RenderMode (GLenum mode)
Set rasterization mode.
Parameters
mode rasterization mode.
Note
this function can't be put in a display list.
See also
glRenderMode().
Flushes the vertices and do the necessary cleanup according to the previous rasterization mode, such as writing the hit record or resent the select buffer index when exiting the select mode. Updates __struct gl_contextRec::RenderMode and notifies the driver via the dd_function_table::RenderMode callback.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_warning(), _NEW_RENDERMODE, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, VERBOSE_API, and write_hit_record().
_mesa_SelectBuffer()
void GLAPIENTRY _mesa_SelectBuffer (GLsizei size, GLuint * buffer)
Establish a buffer for selection mode values.
Parameters
size buffer size.
buffer buffer.
See also
glSelectBuffer().
Note
this function can't be put in a display list.
Verifies we're not in selection mode, flushes the vertices and initialize the fields in __struct gl_contextRec::Select with the given buffer.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
_mesa_update_hitflag()
void _mesa_update_hitflag (struct gl_context * ctx, GLfloat z)
Update the hit flag and the maximum and minimum depth values.
Parameters
ctx GL context.
z depth.
Sets gl_selection::HitFlag and updates gl_selection::HitMinZ and gl_selection::HitMaxZ.
References gl_selection::HitFlag, gl_selection::HitMaxZ, gl_selection::HitMinZ, and gl_context::Select.
Referenced by _mesa_feedback_token(), _mesa_RasterPos(), and window_pos3f().