Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ffvertex_prog.c File Reference
Create a vertex program to execute the current fixed function T&L pipeline.
#include "main/glheader.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/enums.h"
#include "main/ffvertex_prog.h"
#include "program/program.h"
#include "program/prog_cache.h"
#include "program/prog_instruction.h"
#include "program/prog_parameter.h"
#include "program/prog_print.h"
#include "program/prog_statevars.h"
#include "util/bitscan.h"
Data Structures
struct state_key
struct ureg
struct tnl_program
Macros
#define NUM_UNITS MAX2(MAX_TEXTURE_COORD_UNITS, MAX_LIGHTS)
Max of number of lights and texture coord units.
#define TXG_NONE 0
#define TXG_OBJ_LINEAR 1
#define TXG_EYE_LINEAR 2
#define TXG_SPHERE_MAP 3
#define TXG_REFLECTION_MAP 4
#define TXG_NORMAL_MAP 5
#define FDM_EYE_RADIAL 0
#define FDM_EYE_PLANE 1
#define FDM_EYE_PLANE_ABS 2
#define DISASSEM 0
#define X SWIZZLE_X
#define Y SWIZZLE_Y
#define Z SWIZZLE_Z
#define W SWIZZLE_W
#define register_param1(p, s0) register_param5(p,s0,0,0,0,0)
#define register_param2(p, s0, s1) register_param5(p,s0,s1,0,0,0)
#define register_param3(p, s0, s1, s2) register_param5(p,s0,s1,s2,0,0)
#define register_param4(p, s0, s1, s2, s3) register_param5(p,s0,s1,s2,s3,0)
#define register_const1f(p, s0) register_const4f(p, s0, 0, 0, 1)
#define register_scalar_const(p, s0) register_const4f(p, s0, s0, s0, s0)
#define register_const2f(p, s0, s1) register_const4f(p, s0, s1, 0, 1)
#define register_const3f(p, s0, s1, s2) register_const4f(p, s0, s1, s2, 1)
#define emit_op3(p, op, dst, mask, src0, src1, src2) emit_op3fn(p, op, dst, mask, src0, src1, src2, __func__, __LINE__)
#define emit_op2(p, op, dst, mask, src0, src1) emit_op3fn(p, op, dst, mask, src0, src1, undef, __func__, __LINE__)
#define emit_op1(p, op, dst, mask, src0) emit_op3fn(p, op, dst, mask, src0, undef, undef, __func__, __LINE__)
#define SCENE_COLOR_BITS(side)
Functions
static GLuint translate_texgen (GLboolean enabled, GLenum mode)
static GLuint translate_fog_distance_mode (GLenum mode)
static GLboolean check_active_shininess (struct gl_context *ctx, const struct state_key *key, GLuint side)
static void make_state_key (struct gl_context *ctx, struct state_key *key)
static struct ureg make_ureg (GLuint file, GLint idx)
static struct ureg negate (struct ureg reg)
static struct ureg swizzle (struct ureg reg, int x, int y, int z, int w)
static struct ureg swizzle1 (struct ureg reg, int x)
static struct ureg get_temp (struct tnl_program *p)
static struct ureg reserve_temp (struct tnl_program *p)
static void release_temp (struct tnl_program *p, struct ureg reg)
static void release_temps (struct tnl_program *p)
static struct ureg register_param5 (struct tnl_program *p, GLint s0, GLint s1, GLint s2, GLint s3, GLint s4)
static struct ureg register_input (struct tnl_program *p, GLuint input)
static struct ureg register_output (struct tnl_program *p, GLuint output)
static struct ureg register_const4f (struct tnl_program *p, GLfloat s0, GLfloat s1, GLfloat s2, GLfloat s3)
static GLboolean is_undef (struct ureg reg)
static struct ureg get_identity_param (struct tnl_program *p)
static void register_matrix_param5 (struct tnl_program *p, GLint s0, GLint s1, GLint s2, GLint s3, GLint s4, struct ureg *matrix)
static void emit_arg (struct prog_src_register *src, struct ureg reg)
static void emit_dst (struct prog_dst_register *dst, struct ureg reg, GLuint mask)
static void debug_insn (struct prog_instruction *inst, const char *fn, GLuint line)
static void emit_op3fn (struct tnl_program *p, enum prog_opcode op, struct ureg dest, GLuint mask, struct ureg src0, struct ureg src1, struct ureg src2, const char *fn, GLuint line)
static struct ureg make_temp (struct tnl_program *p, struct ureg reg)
static void emit_matrix_transform_vec4 (struct tnl_program *p, struct ureg dest, const struct ureg *mat, struct ureg src)
static void emit_transpose_matrix_transform_vec4 (struct tnl_program *p, struct ureg dest, const struct ureg *mat, struct ureg src)
static void emit_matrix_transform_vec3 (struct tnl_program *p, struct ureg dest, const struct ureg *mat, struct ureg src)
static void emit_normalize_vec3 (struct tnl_program *p, struct ureg dest, struct ureg src)
static void emit_passthrough (struct tnl_program *p, GLuint input, GLuint output)
static struct ureg get_eye_position (struct tnl_program *p)
static struct ureg get_eye_position_z (struct tnl_program *p)
static struct ureg get_eye_position_normalized (struct tnl_program *p)
static struct ureg get_transformed_normal (struct tnl_program *p)
static void build_hpos (struct tnl_program *p)
static GLuint material_attrib (GLuint side, GLuint property)
static void set_material_flags (struct tnl_program *p)
Get a bitmask of which material values vary on a per-vertex basis.
static struct ureg get_material (struct tnl_program *p, GLuint side, GLuint property)
static struct ureg get_scenecolor (struct tnl_program *p, GLuint side)
Either return a precalculated constant value or emit code to calculate these values dynamically in the case where material calls are present between begin/end pairs.
static struct ureg get_lightprod (struct tnl_program *p, GLuint light, GLuint side, GLuint property)
static struct ureg calculate_light_attenuation (struct tnl_program *p, GLuint i, struct ureg VPpli, struct ureg dist)
static void emit_degenerate_lit (struct tnl_program *p, struct ureg lit, struct ureg dots)
Compute: lit.y = MAX(0, dots.x) lit.z = SLT(0, dots.x)
static void build_lighting (struct tnl_program *p)
static void build_fog (struct tnl_program *p)
static void build_reflect_texgen (struct tnl_program *p, struct ureg dest, GLuint writemask)
static void build_sphere_texgen (struct tnl_program *p, struct ureg dest, GLuint writemask)
static void build_texture_transform (struct tnl_program *p)
static void build_atten_pointsize (struct tnl_program *p)
Point size attenuation computation.
static void build_array_pointsize (struct tnl_program *p)
Pass-though per-vertex point size, from user's point size array.
static void build_tnl_program (struct tnl_program *p)
static void create_new_program (const struct state_key *key, struct gl_program *program, GLboolean mvp_with_dp4, GLuint max_temps)
struct gl_program * _mesa_get_fixed_func_vertex_program (struct gl_context *ctx)
Return a vertex program which implements the current fixed-function transform/lighting/texgen operations.
Variables
static const struct ureg undef
Detailed Description
Create a vertex program to execute the current fixed function T&L pipeline.
Author
Keith Whitwell
Macro Definition Documentation
DISASSEM
#define DISASSEM 0
Referenced by build_tnl_program(), and debug_insn().
emit_op1
#define emit_op1 (p, op, dst, mask, src0) emit_op3fn(p, op, dst, mask, src0, undef, undef, __func__, __LINE__)
Referenced by build_array_pointsize(), build_atten_pointsize(), build_fog(), build_lighting(), build_sphere_texgen(), build_texture_transform(), build_tnl_program(), calculate_light_attenuation(), emit_normalize_vec3(), emit_passthrough(), and make_temp().
emit_op2
#define emit_op2 (p, op, dst, mask, src0, src1) emit_op3fn(p, op, dst, mask, src0, src1, undef, __func__, __LINE__)
Referenced by build_atten_pointsize(), build_fog(), build_lighting(), build_reflect_texgen(), build_sphere_texgen(), build_texture_transform(), calculate_light_attenuation(), emit_degenerate_lit(), emit_matrix_transform_vec3(), emit_matrix_transform_vec4(), emit_normalize_vec3(), emit_transpose_matrix_transform_vec4(), get_eye_position_z(), get_lightprod(), and get_transformed_normal().
emit_op3
#define emit_op3 (p, op, dst, mask, src0, src1, src2) emit_op3fn(p, op, dst, mask, src0, src1, src2, __func__, __LINE__)
Referenced by build_atten_pointsize(), build_lighting(), build_reflect_texgen(), build_sphere_texgen(), emit_transpose_matrix_transform_vec4(), and get_scenecolor().
FDM_EYE_PLANE
#define FDM_EYE_PLANE 1
Referenced by build_fog(), and translate_fog_distance_mode().
FDM_EYE_PLANE_ABS
#define FDM_EYE_PLANE_ABS 2
Referenced by build_fog(), and translate_fog_distance_mode().
FDM_EYE_RADIAL
#define FDM_EYE_RADIAL 0
Referenced by build_fog(), and translate_fog_distance_mode().
NUM_UNITS
#define NUM_UNITS MAX2(MAX_TEXTURE_COORD_UNITS, MAX_LIGHTS)
Max of number of lights and texture coord units.
register_const1f
#define register_const1f (p, s0) register_const4f(p, s0, 0, 0, 1)
register_const2f
#define register_const2f (p, s0, s1) register_const4f(p, s0, s1, 0, 1)
register_const3f
#define register_const3f (p, s0, s1, s2) register_const4f(p, s0, s1, s2, 1)
register_param1
#define register_param1 (p, s0) register_param5(p,s0,0,0,0,0)
Referenced by build_atten_pointsize(), and get_scenecolor().
register_param2
#define register_param2 (p, s0, s1) register_param5(p,s0,s1,0,0,0)
Referenced by build_atten_pointsize(), get_scenecolor(), and get_transformed_normal().
register_param3
#define register_param3 (p, s0, s1, s2) register_param5(p,s0,s1,s2,0,0)
Referenced by build_lighting(), build_texture_transform(), calculate_light_attenuation(), get_lightprod(), get_material(), and register_input().
register_param4
#define register_param4 (p, s0, s1, s2, s3) register_param5(p,s0,s1,s2,s3,0)
Referenced by get_lightprod().
register_scalar_const
#define register_scalar_const (p, s0) register_const4f(p, s0, s0, s0, s0)
Referenced by build_sphere_texgen().
SCENE_COLOR_BITS
#define SCENE_COLOR_BITS (side)
Value:
((MAT_BIT_FRONT_EMISSION | \
                                   MAT_BIT_FRONT_AMBIENT | \
                                   MAT_BIT_FRONT_DIFFUSE) << (side))
Referenced by get_scenecolor().
TXG_EYE_LINEAR
#define TXG_EYE_LINEAR 2
Referenced by build_texture_transform(), and translate_texgen().
TXG_NONE
#define TXG_NONE 0
Referenced by build_texture_transform(), and translate_texgen().
TXG_NORMAL_MAP
#define TXG_NORMAL_MAP 5
Referenced by build_texture_transform(), and translate_texgen().
TXG_OBJ_LINEAR
#define TXG_OBJ_LINEAR 1
Referenced by build_texture_transform(), and translate_texgen().
TXG_REFLECTION_MAP
#define TXG_REFLECTION_MAP 4
Referenced by build_texture_transform(), and translate_texgen().
TXG_SPHERE_MAP
#define TXG_SPHERE_MAP 3
Referenced by build_texture_transform(), and translate_texgen().
W
#define W SWIZZLE_W
Referenced by build_lighting(), build_sphere_texgen(), calculate_light_attenuation(), and emit_transpose_matrix_transform_vec4().
X
#define X SWIZZLE_X
Referenced by _mesa_PopAttrib(), _mesa_ScissorArrayv(), build_atten_pointsize(), build_fog(), build_lighting(), build_sphere_texgen(), emit_normalize_vec3(), and emit_transpose_matrix_transform_vec4().
Y
#define Y SWIZZLE_Y
Referenced by _mesa_PopAttrib(), _mesa_ScissorArrayv(), build_atten_pointsize(), build_lighting(), build_sphere_texgen(), calculate_light_attenuation(), and emit_transpose_matrix_transform_vec4().
Z
#define Z SWIZZLE_Z
Referenced by build_atten_pointsize(), build_lighting(), build_sphere_texgen(), emit_degenerate_lit(), emit_transpose_matrix_transform_vec4(), and get_eye_position_z().
Function Documentation
_mesa_get_fixed_func_vertex_program()
struct gl_program* _mesa_get_fixed_func_vertex_program (struct gl_context * ctx)
Return a vertex program which implements the current fixed-function transform/lighting/texgen operations.
References gl_vertex_program_state::Cache, gl_context::Const, create_new_program(), gl_context::Driver, make_state_key(), gl_program_constants::MaxTemps, dd_function_table::NewProgram, gl_shader_compiler_options::OptimizeForAOS, gl_constants::Program, dd_function_table::ProgramStringNotify, gl_constants::ShaderCompilerOptions, and gl_context::VertexProgram.
Referenced by update_program().
build_array_pointsize()
static void build_array_pointsize (struct tnl_program * p) static
Pass-though per-vertex point size, from user's point size array.
References emit_op1, register_input(), and register_output().
Referenced by build_tnl_program().
build_atten_pointsize()
static void build_atten_pointsize (struct tnl_program * p) static
Point size attenuation computation.
References emit_op1, emit_op2, emit_op3, get_eye_position_z(), get_temp(), register_output(), register_param1, register_param2, release_temp(), swizzle1(), X, Y, and Z.
Referenced by build_tnl_program().
build_fog()
static void build_fog (struct tnl_program * p) static
References emit_op1, emit_op2, FDM_EYE_PLANE, FDM_EYE_PLANE_ABS, FDM_EYE_RADIAL, state_key::fog_distance_mode, state_key::fog_source_is_depth, get_eye_position(), get_eye_position_z(), get_identity_param(), register_input(), register_output(), tnl_program::state, swizzle1(), and X.
Referenced by build_tnl_program().
build_hpos()
static void build_hpos (struct tnl_program * p) static
References emit_matrix_transform_vec4(), emit_transpose_matrix_transform_vec4(), tnl_program::mvp_with_dp4, register_input(), register_matrix_param5(), and register_output().
Referenced by build_tnl_program().
build_lighting()
static void build_lighting (struct tnl_program * p) static
References calculate_light_attenuation(), emit_degenerate_lit(), emit_normalize_vec3(), emit_op1, emit_op2, emit_op3, get_eye_position(), get_eye_position_normalized(), get_identity_param(), get_lightprod(), get_material(), get_scenecolor(), get_temp(), get_transformed_normal(), GLuint, is_undef(), state_key::light_enabled, state_key::light_eyepos3_is_zero, state_key::light_local_viewer, state_key::light_twoside, make_temp(), state_key::material_shininess_is_zero, MAX_LIGHTS, negate(), register_output(), register_param3, release_temp(), release_temps(), state_key::separate_specular, set_material_flags(), tnl_program::state, swizzle(), swizzle1(), undef, state_key::unit, W, X, Y, and Z.
Referenced by build_tnl_program().
build_reflect_texgen()
static void build_reflect_texgen (struct tnl_program * p, struct ureg dest, GLuint writemask) static
References emit_op2, emit_op3, get_eye_position_normalized(), get_temp(), get_transformed_normal(), negate(), and release_temp().
Referenced by build_texture_transform().
build_sphere_texgen()
static void build_sphere_texgen (struct tnl_program * p, struct ureg dest, GLuint writemask) static
References emit_op1, emit_op2, emit_op3, get_eye_position_normalized(), get_identity_param(), get_temp(), get_transformed_normal(), negate(), register_scalar_const, release_temp(), swizzle(), W, X, Y, and Z.
Referenced by build_texture_transform().
build_texture_transform()
static void build_texture_transform (struct tnl_program * p) static
References build_reflect_texgen(), build_sphere_texgen(), state_key::coord_replace, emit_matrix_transform_vec4(), emit_op1, emit_op2, emit_passthrough(), emit_transpose_matrix_transform_vec4(), state_key::fragprog_inputs_read, get_eye_position(), get_temp(), get_transformed_normal(), GLuint, is_undef(), MAX_TEXTURE_COORD_UNITS, tnl_program::mvp_with_dp4, register_input(), register_matrix_param5(), register_output(), register_param3, release_temps(), tnl_program::state, state_key::texgen_enabled, state_key::texgen_mode0, state_key::texgen_mode1, state_key::texgen_mode2, state_key::texgen_mode3, state_key::texmat_enabled, TXG_EYE_LINEAR, TXG_NONE, TXG_NORMAL_MAP, TXG_OBJ_LINEAR, TXG_REFLECTION_MAP, TXG_SPHERE_MAP, undef, and state_key::unit.
Referenced by build_tnl_program().
build_tnl_program()
static void build_tnl_program (struct tnl_program * p) static
References build_array_pointsize(), build_atten_pointsize(), build_fog(), build_hpos(), build_lighting(), build_texture_transform(), DISASSEM, emit_op1, emit_passthrough(), state_key::fragprog_inputs_read, state_key::light_global_enabled, OPCODE_END, state_key::point_array, state_key::point_attenuated, and tnl_program::state.
Referenced by create_new_program().
calculate_light_attenuation()
static struct ureg calculate_light_attenuation (struct tnl_program * p, GLuint i, struct ureg VPpli, struct ureg dist) static
References emit_op1, emit_op2, get_temp(), GLuint, is_undef(), negate(), register_param3, release_temp(), swizzle1(), undef, W, and Y.
Referenced by build_lighting().
check_active_shininess()
static GLboolean check_active_shininess (struct gl_context * ctx, const struct state_key * key, GLuint side) static
References gl_material::Attrib, GLuint, gl_context::Light, state_key::light_color_material_mask, MAT_ATTRIB_FRONT_SHININESS, gl_light_attrib::Material, and state_key::varying_vp_inputs.
Referenced by make_state_key().
create_new_program()
static void create_new_program (const struct state_key * key, struct gl_program * program, GLboolean mvp_with_dp4, GLuint max_temps) static
References gl_program::arb, build_tnl_program(), tnl_program::eye_position, tnl_program::eye_position_normalized, tnl_program::eye_position_z, tnl_program::identity, gl_program::info, tnl_program::max_inst, tnl_program::mvp_with_dp4, gl_program::Parameters, tnl_program::program, tnl_program::state, gl_program::String, tnl_program::temp_in_use, tnl_program::temp_reserved, tnl_program::transformed_normal, and undef.
Referenced by _mesa_get_fixed_func_vertex_program().
debug_insn()
static void debug_insn (struct prog_instruction * inst, const char * fn, GLuint line) static
References DISASSEM.
Referenced by emit_op3fn().
emit_arg()
static void emit_arg (struct prog_src_register * src, struct ureg reg) static
References ureg::file, ureg::idx, ureg::negate, and ureg::swz.
Referenced by emit_op3fn().
emit_degenerate_lit()
static void emit_degenerate_lit (struct tnl_program * p, struct ureg lit, struct ureg dots) static
Compute: lit.y = MAX(0, dots.x) lit.z = SLT(0, dots.x)
References emit_op2, get_identity_param(), swizzle1(), and Z.
Referenced by build_lighting().
emit_dst()
static void emit_dst (struct prog_dst_register * dst, struct ureg reg, GLuint mask) static
References ureg::file, and ureg::idx.
Referenced by emit_op3fn().
emit_matrix_transform_vec3()
static void emit_matrix_transform_vec3 (struct tnl_program * p, struct ureg dest, const struct ureg * mat, struct ureg src) static
References emit_op2.
Referenced by get_transformed_normal().
emit_matrix_transform_vec4()
static void emit_matrix_transform_vec4 (struct tnl_program * p, struct ureg dest, const struct ureg * mat, struct ureg src) static
References emit_op2.
Referenced by build_hpos(), build_texture_transform(), and get_eye_position().
emit_normalize_vec3()
static void emit_normalize_vec3 (struct tnl_program * p, struct ureg dest, struct ureg src) static
References emit_op1, emit_op2, get_temp(), release_temp(), swizzle1(), and X.
Referenced by build_lighting(), get_eye_position_normalized(), and get_transformed_normal().
emit_op3fn()
static void emit_op3fn (struct tnl_program * p, enum prog_opcode op, struct ureg dest, GLuint mask, struct ureg src0, struct ureg src1, struct ureg src2, const char * fn, GLuint line) static
References _mesa_error(), gl_program::arb, debug_insn(), emit_arg(), emit_dst(), GLuint, tnl_program::max_inst, and tnl_program::program.
emit_passthrough()
static void emit_passthrough (struct tnl_program * p, GLuint input, GLuint output) static
References emit_op1, register_input(), and register_output().
Referenced by build_texture_transform(), and build_tnl_program().
emit_transpose_matrix_transform_vec4()
static void emit_transpose_matrix_transform_vec4 (struct tnl_program * p, struct ureg dest, const struct ureg * mat, struct ureg src) static
References emit_op2, emit_op3, ureg::file, get_temp(), PROGRAM_TEMPORARY, release_temp(), swizzle1(), W, X, Y, and Z.
Referenced by build_hpos(), build_texture_transform(), and get_eye_position().
get_eye_position()
static struct ureg get_eye_position (struct tnl_program * p) static
References emit_matrix_transform_vec4(), emit_transpose_matrix_transform_vec4(), is_undef(), register_input(), register_matrix_param5(), and reserve_temp().
Referenced by build_fog(), build_lighting(), build_texture_transform(), and get_eye_position_normalized().
get_eye_position_normalized()
static struct ureg get_eye_position_normalized (struct tnl_program * p) static
References emit_normalize_vec3(), get_eye_position(), is_undef(), and reserve_temp().
Referenced by build_lighting(), build_reflect_texgen(), and build_sphere_texgen().
get_eye_position_z()
static struct ureg get_eye_position_z (struct tnl_program * p) static
References emit_op2, is_undef(), register_input(), register_matrix_param5(), reserve_temp(), swizzle1(), and Z.
Referenced by build_atten_pointsize(), and build_fog().
get_identity_param()
static struct ureg get_identity_param (struct tnl_program * p) static
References is_undef(), and register_const4f().
Referenced by build_fog(), build_lighting(), build_sphere_texgen(), and emit_degenerate_lit().
get_lightprod()
static struct ureg get_lightprod (struct tnl_program * p, GLuint light, GLuint side, GLuint property) static
References emit_op2, get_material(), get_temp(), GLuint, material_attrib(), register_param3, and register_param4.
Referenced by build_lighting().
get_material()
static struct ureg get_material (struct tnl_program * p, GLuint side, GLuint property) static
References GLuint, material_attrib(), register_input(), and register_param3.
Referenced by build_lighting(), get_lightprod(), and get_scenecolor().
get_scenecolor()
static struct ureg get_scenecolor (struct tnl_program * p, GLuint side) static
Either return a precalculated constant value or emit code to calculate these values dynamically in the case where material calls are present between begin/end pairs.
Probably want to shift this to the program compilation phase - if we always emitted the calculation here, a smart compiler could detect that it was constant (given a certain set of inputs), and lift it out of the main loop. That way the programs created here would be independent of the vertex_buffer details.
References emit_op3, get_material(), GLuint, make_temp(), register_param1, register_param2, and SCENE_COLOR_BITS.
Referenced by build_lighting().
get_temp()
static struct ureg get_temp (struct tnl_program * p) static
References _mesa_problem(), GLuint, make_ureg(), and PROGRAM_TEMPORARY.
Referenced by build_atten_pointsize(), build_lighting(), build_reflect_texgen(), build_sphere_texgen(), build_texture_transform(), calculate_light_attenuation(), emit_normalize_vec3(), emit_transpose_matrix_transform_vec4(), get_lightprod(), make_temp(), and reserve_temp().
get_transformed_normal()
static struct ureg get_transformed_normal (struct tnl_program * p) static
References emit_matrix_transform_vec3(), emit_normalize_vec3(), emit_op2, ureg::file, is_undef(), PROGRAM_TEMPORARY, register_input(), register_matrix_param5(), register_param2, and reserve_temp().
Referenced by build_lighting(), build_reflect_texgen(), build_sphere_texgen(), and build_texture_transform().
is_undef()
static GLboolean is_undef (struct ureg reg) static
References ureg::file, and PROGRAM_UNDEFINED.
Referenced by build_lighting(), build_texture_transform(), calculate_light_attenuation(), get_eye_position(), get_eye_position_normalized(), get_eye_position_z(), get_identity_param(), and get_transformed_normal().
make_state_key()
static void make_state_key (struct gl_context * ctx, struct state_key * key) static
References gl_point_attrib::_Attenuated, gl_light_attrib::_ColorMaterialBitmask, gl_texture_unit::_Current, gl_fragment_program_state::_Current, gl_texture_attrib::_EnabledCoordUnits, gl_light_attrib::_EnabledLights, gl_texture_attrib::_MaxEnabledTexImageUnit, gl_context::_NeedEyeCoords, gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_context::Array, check_active_shininess(), gl_lightmodel::ColorControl, gl_light_attrib::ColorMaterialEnabled, gl_light::ConstantAttenuation, state_key::coord_replace, gl_point_attrib::CoordReplace, ENABLE_TEXMAT, gl_light_attrib::Enabled, gl_array_attributes::Enabled, gl_light::EyePosition, gl_context::Fog, state_key::fog_distance_mode, state_key::fog_source_is_depth, gl_fog_attrib::FogCoordinateSource, gl_fog_attrib::FogDistanceMode, gl_context::FragmentProgram, state_key::fragprog_inputs_read, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, gl_program::info, gl_light_attrib::Light, gl_context::Light, state_key::light_attenuated, state_key::light_color_material_mask, state_key::light_enabled, state_key::light_eyepos3_is_zero, state_key::light_global_enabled, state_key::light_local_viewer, state_key::light_spotcutoff_is_180, state_key::light_twoside, gl_light::LinearAttenuation, gl_lightmodel::LocalViewer, state_key::material_shininess_is_zero, gl_texgen::Mode, gl_light_attrib::Model, state_key::need_eye_coords, state_key::normalize, gl_transform_attrib::Normalize, gl_context::Point, state_key::point_array, state_key::point_attenuated, gl_point_attrib::PointSprite, gl_light::QuadraticAttenuation, gl_context::RenderMode, state_key::rescale_normals, gl_transform_attrib::RescaleNormals, state_key::separate_specular, gl_light::SpotCutoff, state_key::texgen_enabled, state_key::texgen_mode0, state_key::texgen_mode1, state_key::texgen_mode2, state_key::texgen_mode3, gl_texture_unit::TexGenEnabled, state_key::texmat_enabled, gl_context::Texture, state_key::texture_enabled_global, state_key::texunit_really_enabled, gl_context::Transform, translate_fog_distance_mode(), translate_texgen(), gl_lightmodel::TwoSide, state_key::unit, gl_texture_attrib::Unit, gl_array_attrib::VAO, state_key::varying_vp_inputs, gl_context::varying_vp_inputs, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_get_fixed_func_vertex_program().
make_temp()
static struct ureg make_temp (struct tnl_program * p, struct ureg reg) static
References emit_op1, get_temp(), and PROGRAM_TEMPORARY.
Referenced by build_lighting(), and get_scenecolor().
make_ureg()
static struct ureg make_ureg (GLuint file, GLint idx) static
References ureg::file, GLuint, ureg::idx, ureg::negate, ureg::pad, and ureg::swz.
Referenced by get_temp(), register_const4f(), register_input(), register_output(), and register_param5().
material_attrib()
static GLuint material_attrib (GLuint side, GLuint property) static
References GLuint.
Referenced by get_lightprod(), and get_material().
negate()
static struct ureg negate (struct ureg reg) static
References ureg::negate.
Referenced by build_lighting(), build_reflect_texgen(), build_sphere_texgen(), and calculate_light_attenuation().
register_const4f()
static struct ureg register_const4f (struct tnl_program * p, GLfloat s0, GLfloat s1, GLfloat s2, GLfloat s3) static
References GLuint, ureg::idx, make_ureg(), PROGRAM_CONSTANT, and swizzle().
Referenced by get_identity_param().
register_input()
static struct ureg register_input (struct tnl_program * p, GLuint input) static
Parameters
input one of VERT_ATTRIB_x tokens.
References GLuint, make_ureg(), PROGRAM_INPUT, and register_param3.
Referenced by build_array_pointsize(), build_fog(), build_hpos(), build_texture_transform(), emit_passthrough(), get_eye_position(), get_eye_position_z(), get_material(), and get_transformed_normal().
register_matrix_param5()
static void register_matrix_param5 (struct tnl_program * p, GLint s0, GLint s1, GLint s2, GLint s3, GLint s4, struct ureg * matrix) static
References register_param5().
Referenced by build_hpos(), build_texture_transform(), get_eye_position(), get_eye_position_z(), and get_transformed_normal().
register_output()
static struct ureg register_output (struct tnl_program * p, GLuint output) static
Parameters
input one of VARYING_SLOT_x tokens.
References BITFIELD64_BIT, GLuint, make_ureg(), and PROGRAM_OUTPUT.
Referenced by build_array_pointsize(), build_atten_pointsize(), build_fog(), build_hpos(), build_lighting(), build_texture_transform(), and emit_passthrough().
register_param5()
static struct ureg register_param5 (struct tnl_program * p, GLint s0, GLint s1, GLint s2, GLint s3, GLint s4) static
References ureg::idx, make_ureg(), and PROGRAM_STATE_VAR.
Referenced by register_matrix_param5().
release_temp()
static void release_temp (struct tnl_program * p, struct ureg reg) static
References ureg::file, ureg::idx, PROGRAM_TEMPORARY, tnl_program::temp_in_use, and tnl_program::temp_reserved.
Referenced by build_atten_pointsize(), build_lighting(), build_reflect_texgen(), build_sphere_texgen(), calculate_light_attenuation(), emit_normalize_vec3(), and emit_transpose_matrix_transform_vec4().
release_temps()
static void release_temps (struct tnl_program * p) static
References tnl_program::temp_in_use, and tnl_program::temp_reserved.
Referenced by build_lighting(), and build_texture_transform().
reserve_temp()
static struct ureg reserve_temp (struct tnl_program * p) static
References get_temp(), and ureg::idx.
Referenced by get_eye_position(), get_eye_position_normalized(), get_eye_position_z(), and get_transformed_normal().
set_material_flags()
static void set_material_flags (struct tnl_program * p) static
Get a bitmask of which material values vary on a per-vertex basis.
References tnl_program::color_materials, state_key::light_color_material_mask, tnl_program::materials, tnl_program::state, and state_key::varying_vp_inputs.
Referenced by build_lighting().
swizzle()
static struct ureg swizzle (struct ureg reg, int x, int y, int z, int w) static
References ureg::swz, and x.
Referenced by _mesa_array_format_flip_channels(), _mesa_EndFragmentShaderATI(), _mesa_format_from_format_and_type(), _mesa_half_to_signed(), _mesa_PassTexCoordATI(), _mesa_SampleMapATI(), build_lighting(), build_sphere_texgen(), get_base_format_for_array_format(), register_const4f(), and swizzle1().
swizzle1()
static struct ureg swizzle1 (struct ureg reg, int x) static
References swizzle(), and x.
Referenced by build_atten_pointsize(), build_fog(), build_lighting(), calculate_light_attenuation(), emit_degenerate_lit(), emit_normalize_vec3(), emit_transpose_matrix_transform_vec4(), and get_eye_position_z().
translate_fog_distance_mode()
static GLuint translate_fog_distance_mode (GLenum mode) static
References FDM_EYE_PLANE, FDM_EYE_PLANE_ABS, FDM_EYE_RADIAL, and GLuint.
Referenced by make_state_key().
translate_texgen()
static GLuint translate_texgen (GLboolean enabled, GLenum mode) static
References GLuint, TXG_EYE_LINEAR, TXG_NONE, TXG_NORMAL_MAP, TXG_OBJ_LINEAR, TXG_REFLECTION_MAP, and TXG_SPHERE_MAP.
Referenced by make_state_key().
Variable Documentation
undef
const struct ureg undef static
Initial value:
= {
   PROGRAM_UNDEFINED,
   0,
   0,
   0,
   0
}
Referenced by build_lighting(), build_texture_transform(), calculate_light_attenuation(), and create_new_program().