Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ffvertex_prog.h File Reference
Functions
struct gl_program * _mesa_get_fixed_func_vertex_program (struct gl_context *ctx)
Return a vertex program which implements the current fixed-function transform/lighting/texgen operations.
Function Documentation
_mesa_get_fixed_func_vertex_program()
struct gl_program* _mesa_get_fixed_func_vertex_program (struct gl_context * ctx)
Return a vertex program which implements the current fixed-function transform/lighting/texgen operations.
References gl_vertex_program_state::Cache, gl_context::Const, create_new_program(), gl_context::Driver, make_state_key(), gl_program_constants::MaxTemps, dd_function_table::NewProgram, gl_shader_compiler_options::OptimizeForAOS, gl_constants::Program, dd_function_table::ProgramStringNotify, gl_constants::ShaderCompilerOptions, and gl_context::VertexProgram.
Referenced by update_program().