Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
formatquery.c File Reference
#include "mtypes.h"
#include "context.h"
#include "glformats.h"
#include "macros.h"
#include "enums.h"
#include "fbobject.h"
#include "formatquery.h"
#include "teximage.h"
#include "texparam.h"
#include "texobj.h"
#include "get.h"
#include "genmipmap.h"
#include "shaderimage.h"
#include "texcompress.h"
#include "textureview.h"
Functions
static bool _is_renderable (struct gl_context *ctx, GLenum internalformat)
static bool _legal_parameters (struct gl_context *ctx, GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params)
static void _set_default_response (GLenum pname, GLint buffer[16])
static bool _is_target_supported (struct gl_context *ctx, GLenum target)
static bool _is_resource_supported (struct gl_context *ctx, GLenum target, GLenum internalformat, GLenum pname)
static bool _is_internalformat_supported (struct gl_context *ctx, GLenum target, GLenum internalformat)
static bool _legal_target_for_framebuffer_texture_layer (struct gl_context *ctx, GLenum target)
static GLenum _mesa_generic_type_for_internal_format (GLenum internalFormat)
void _mesa_query_internal_format_default (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint *params)
static GLenum _equivalent_size_pname (GLenum target, GLenum pname)
static GLint _get_target_dimensions (GLenum target)
static GLint _get_min_dimensions (GLenum pname)
static bool _is_multisample_target (GLenum target)
void GLAPIENTRY _mesa_GetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params)
void GLAPIENTRY _mesa_GetInternalformati64v (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 *params)
Function Documentation
_equivalent_size_pname()
static GLenum _equivalent_size_pname (GLenum target, GLenum pname) static
Referenced by _mesa_GetInternalformativ().
_get_min_dimensions()
static GLint _get_min_dimensions (GLenum pname) static
Referenced by _mesa_GetInternalformativ().
_get_target_dimensions()
static GLint _get_target_dimensions (GLenum target) static
References _mesa_get_texture_dimensions().
Referenced by _mesa_GetInternalformativ().
_is_internalformat_supported()
static bool _is_internalformat_supported (struct gl_context * ctx, GLenum target, GLenum internalformat) static
References _mesa_base_fbo_format(), _mesa_base_tex_format(), gl_context::Driver, and dd_function_table::QueryInternalFormat.
Referenced by _mesa_GetInternalformativ().
_is_multisample_target()
static bool _is_multisample_target (GLenum target) static
References GLAPIENTRY.
Referenced by _mesa_GetInternalformativ().
_is_renderable()
static bool _is_renderable (struct gl_context * ctx, GLenum internalformat) static
References _mesa_base_fbo_format().
Referenced by _legal_parameters(), and _mesa_GetInternalformativ().
_is_resource_supported()
static bool _is_resource_supported (struct gl_context * ctx, GLenum target, GLenum internalformat, GLenum pname) static
References _mesa_base_fbo_format(), _mesa_base_tex_format(), _mesa_format_no_online_compression(), _mesa_is_compressed_format(), _mesa_is_renderable_texture_format(), _mesa_legal_texture_base_format_for_target(), _mesa_target_can_be_compressed(), _mesa_validate_texbuffer_format(), and MESA_FORMAT_NONE.
Referenced by _mesa_GetInternalformativ().
_is_target_supported()
static bool _is_target_supported (struct gl_context * ctx, GLenum target) static
References _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_gles31(), gl_context::API, and API_OPENGL_CORE.
Referenced by _mesa_GetInternalformativ().
_legal_parameters()
static bool _legal_parameters (struct gl_context * ctx, GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint * params) static
References _is_renderable(), _mesa_enum_to_string(), _mesa_error(), and _mesa_is_gles31().
Referenced by _mesa_GetInternalformativ().
_legal_target_for_framebuffer_texture_layer()
static bool _legal_target_for_framebuffer_texture_layer (struct gl_context * ctx, GLenum target) static
Referenced by _mesa_GetInternalformativ().
_mesa_generic_type_for_internal_format()
static GLenum _mesa_generic_type_for_internal_format (GLenum internalFormat) static
References _mesa_is_enum_format_signed_int(), and _mesa_is_enum_format_unsigned_int().
Referenced by _mesa_query_internal_format_default().
_mesa_GetInternalformati64v()
void GLAPIENTRY _mesa_GetInternalformati64v (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 * params)
References _mesa_error(), _mesa_GetInternalformativ(), ASSERT_OUTSIDE_BEGIN_END, and GET_CURRENT_CONTEXT.
_mesa_GetInternalformativ()
void GLAPIENTRY _mesa_GetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint * params)
References _equivalent_size_pname(), _get_min_dimensions(), _get_target_dimensions(), _is_internalformat_supported(), _is_multisample_target(), _is_renderable(), _is_resource_supported(), _is_target_supported(), _legal_parameters(), _legal_target_for_framebuffer_texture_layer(), _mesa_base_fbo_format(), _mesa_base_format_has_channel(), _mesa_base_format_to_integer_format(), _mesa_base_tex_format(), _mesa_delete_texture_object(), _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_block_size(), _mesa_get_format_bytes(), _mesa_get_format_datatype(), _mesa_get_image_format_class(), _mesa_get_shader_image_format(), _mesa_GetIntegerv(), _mesa_GetInternalformativ(), _mesa_glenum_to_compressed_format(), _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_is_array_texture(), _mesa_is_color_format(), _mesa_is_compressed_format(), _mesa_is_cube_map_texture(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), _mesa_is_desktop_gl(), _mesa_is_enum_format_integer(), _mesa_is_gles3(), _mesa_is_shader_image_format_supported(), _mesa_is_srgb_format(), _mesa_is_stencil_format(), _mesa_is_valid_generate_texture_mipmap_internalformat(), _mesa_is_valid_generate_texture_mipmap_target(), _mesa_legal_get_tex_level_parameter_target(), _mesa_new_texture_object(), _mesa_target_allows_setting_sampler_parameters(), _mesa_texture_view_lookup_view_class(), _mesa_uncompressed_format_to_type_and_comps(), _mesa_warning(), _set_default_response(), API_OPENGL_CORE, API_OPENGLES2, ASSERT_OUTSIDE_BEGIN_END, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_texture_object::ImageFormatCompatibilityType, MESA_FORMAT_NONE, and MESA_FORMAT_R9G9B9E5_FLOAT.
Referenced by _mesa_GetInternalformati64v(), and _mesa_GetInternalformativ().
_mesa_query_internal_format_default()
void _mesa_query_internal_format_default (struct gl_context * ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint * params)
References _mesa_base_format_to_integer_format(), _mesa_base_tex_format(), _mesa_generic_type_for_internal_format(), _mesa_is_enum_format_integer(), _set_default_response(), and void.
_set_default_response()
static void _set_default_response (GLenum pname, GLint buffer[16]) static
Referenced by _mesa_GetInternalformativ(), and _mesa_query_internal_format_default().