Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
format_utils.h File Reference
A collection of format conversion utility functions.
#include "imports.h"
#include "macros.h"
#include "util/rounding.h"
#include "util/half_float.h"
Macros
#define MAX_UINT(BITS) ((BITS) == 32 ? UINT32_MAX : ((1u << (BITS)) - 1))
#define MAX_INT(BITS) ((int)MAX_UINT((BITS) - 1))
#define MIN_INT(BITS) ((BITS) == 32 ? INT32_MIN : (-(1 << (BITS - 1))))
#define EXTEND_NORMALIZED_INT(X, SRC_BITS, DST_BITS)
Functions
static float _mesa_unorm_to_float (unsigned x, unsigned src_bits)
static float _mesa_snorm_to_float (int x, unsigned src_bits)
static uint16_t _mesa_unorm_to_half (unsigned x, unsigned src_bits)
static uint16_t _mesa_snorm_to_half (int x, unsigned src_bits)
static unsigned _mesa_float_to_unorm (float x, unsigned dst_bits)
static unsigned _mesa_half_to_unorm (uint16_t x, unsigned dst_bits)
static unsigned _mesa_unorm_to_unorm (unsigned x, unsigned src_bits, unsigned dst_bits)
static unsigned _mesa_snorm_to_unorm (int x, unsigned src_bits, unsigned dst_bits)
static int _mesa_float_to_snorm (float x, unsigned dst_bits)
static int _mesa_half_to_snorm (uint16_t x, unsigned dst_bits)
static int _mesa_unorm_to_snorm (unsigned x, unsigned src_bits, unsigned dst_bits)
static int _mesa_snorm_to_snorm (int x, unsigned src_bits, unsigned dst_bits)
static unsigned _mesa_unsigned_to_unsigned (unsigned src, unsigned dst_size)
static int _mesa_unsigned_to_signed (unsigned src, unsigned dst_size)
static int _mesa_signed_to_signed (int src, unsigned dst_size)
static unsigned _mesa_signed_to_unsigned (int src, unsigned dst_size)
static unsigned _mesa_float_to_unsigned (float src, unsigned dst_bits)
static unsigned _mesa_float_to_signed (float src, unsigned dst_bits)
static unsigned _mesa_half_to_unsigned (uint16_t src, unsigned dst_bits)
static unsigned _mesa_half_to_signed (uint16_t src, unsigned dst_bits)
bool _mesa_format_to_array (mesa_format, GLenum *type, int *num_components, uint8_t swizzle[4], bool *normalized)
Describes a format as an array format, if possible.
void _mesa_swizzle_and_convert (void *dst, enum mesa_array_format_datatype dst_type, int num_dst_channels, const void *src, enum mesa_array_format_datatype src_type, int num_src_channels, const uint8_t swizzle[4], bool normalized, int count)
Convert between array-based color formats.
bool _mesa_compute_rgba2base2rgba_component_mapping (GLenum baseFormat, uint8_t *map)
This function is used by clients of _mesa_format_convert to obtain the rebase swizzle to use in a format conversion based on the base format involved.
void _mesa_format_convert (void *void_dst, uint32_t dst_format, size_t dst_stride, void *void_src, uint32_t src_format, size_t src_stride, size_t width, size_t height, uint8_t *rebase_swizzle)
This can be used to convert between most color formats.
Variables
const mesa_array_format RGBA32_FLOAT
const mesa_array_format RGBA8_UBYTE
const mesa_array_format RGBA32_UINT
const mesa_array_format RGBA32_INT
Detailed Description
A collection of format conversion utility functions.
Macro Definition Documentation
EXTEND_NORMALIZED_INT
#define EXTEND_NORMALIZED_INT (X, SRC_BITS, DST_BITS)
Value:
(((X) * (int)(MAX_UINT(DST_BITS) / MAX_UINT(SRC_BITS))) + \
       ((DST_BITS % SRC_BITS) ? ((X) >> (SRC_BITS - DST_BITS % SRC_BITS)) : 0))
Referenced by _mesa_snorm_to_snorm(), and _mesa_unorm_to_unorm().
MAX_INT
#define MAX_INT (BITS) ((int)MAX_UINT((BITS) - 1))
Referenced by _mesa_float_to_signed(), _mesa_float_to_snorm(), _mesa_signed_to_signed(), _mesa_snorm_to_float(), _mesa_snorm_to_snorm(), and _mesa_unsigned_to_signed().
MAX_UINT
#define MAX_UINT (BITS) ((BITS) == 32 ? UINT32_MAX : ((1u << (BITS)) - 1))
Referenced by _mesa_float_to_unorm(), _mesa_float_to_unsigned(), _mesa_signed_to_unsigned(), _mesa_unorm_to_float(), _mesa_unorm_to_unorm(), and _mesa_unsigned_to_unsigned().
MIN_INT
#define MIN_INT (BITS) ((BITS) == 32 ? INT32_MIN : (-(1 << (BITS - 1))))
Referenced by _mesa_signed_to_signed().
Function Documentation
_mesa_compute_rgba2base2rgba_component_mapping()
bool _mesa_compute_rgba2base2rgba_component_mapping (GLenum baseFormat, uint8_t * map)
This function is used by clients of _mesa_format_convert to obtain the rebase swizzle to use in a format conversion based on the base format involved.
Parameters
baseFormat the base internal format involved in the conversion.
map the rebase swizzle to consider
This function computes 'map' as rgba -> baseformat -> rgba and returns true if the resulting swizzle transform is not the identity transform (thus, a rebase is needed). If the function returns false then a rebase swizzle is not necessary and the value of 'map' is undefined. In this situation clients of _mesa_format_convert should pass NULL in the 'rebase_swizzle' parameter.
References _mesa_compute_component_mapping(), and MESA_FORMAT_SWIZZLE_W.
Referenced by _mesa_half_to_signed(), read_rgba_pixels(), teximage_needs_rebase(), and texstore_rgba().
_mesa_float_to_signed()
static unsigned _mesa_float_to_signed (float src, unsigned dst_bits) inline static
References _mesa_signed_to_signed(), and MAX_INT.
Referenced by _mesa_half_to_signed(), convert_byte(), convert_int(), and convert_short().
_mesa_float_to_snorm()
static int _mesa_float_to_snorm (float x, unsigned dst_bits) inline static
References MAX_INT.
Referenced by _mesa_half_to_snorm(), convert_byte(), convert_int(), and convert_short().
_mesa_float_to_unorm()
static unsigned _mesa_float_to_unorm (float x, unsigned dst_bits) inline static
References MAX_UINT.
Referenced by _mesa_half_to_unorm(), convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_float_to_unsigned()
static unsigned _mesa_float_to_unsigned (float src, unsigned dst_bits) inline static
References _mesa_signed_to_unsigned(), and MAX_UINT.
Referenced by convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_format_convert()
void _mesa_format_convert (void * void_dst, uint32_t dst_format, size_t dst_stride, void * void_src, uint32_t src_format, size_t src_stride, size_t width, size_t height, uint8_t * rebase_swizzle)
This can be used to convert between most color formats.
Limitations:
This function doesn't handle GL_COLOR_INDEX or YCBCR formats.
This function doesn't handle byte-swapping or transferOps, these should be handled by the caller.
Parameters
void_dst The address where converted color data will be stored. The caller must ensure that the buffer is large enough to hold the converted pixel data.
dst_format The destination color format. It can be a mesa_format or a mesa_array_format represented as an uint32_t.
dst_stride The stride of the destination format in bytes.
void_src The address of the source color data to convert.
src_format The source color format. It can be a mesa_format or a mesa_array_format represented as an uint32_t.
src_stride The stride of the source format in bytes.
width The width, in pixels, of the source image to convert.
height The height, in pixels, of the source image to convert.
rebase_swizzle A swizzle transform to apply during the conversion, typically used to match a different internal base format involved. NULL if no rebase transform is needed (i.e. the internal base format and the base format of the dst or the src -depending on whether we are doing an upload or a download respectively- are the same).
References _mesa_array_format_get_datatype(), _mesa_array_format_get_num_channels(), _mesa_array_format_get_swizzle(), _mesa_array_format_get_type_size(), _mesa_array_format_is_float(), _mesa_array_format_is_normalized(), _mesa_array_format_is_signed(), _mesa_format_is_mesa_array_format(), _mesa_format_to_array_format(), _mesa_get_format_datatype(), _mesa_get_format_max_bits(), _mesa_is_format_color_format(), _mesa_is_format_integer_color(), _mesa_is_format_unsigned(), _mesa_pack_float_rgba_row(), _mesa_pack_ubyte_rgba_row(), _mesa_pack_uint_rgba_row(), _mesa_swizzle_and_convert(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_rgba_row(), _mesa_unpack_uint_rgba_row(), compute_rebased_rgba_component_mapping(), compute_src2dst_component_mapping(), convert_ubyte_rgba_to_bgra(), invert_swizzle(), MESA_ARRAY_FORMAT_TYPE_FLOAT, MESA_ARRAY_FORMAT_TYPE_INT, MESA_ARRAY_FORMAT_TYPE_UBYTE, MESA_ARRAY_FORMAT_TYPE_UINT, MESA_FORMAT_B8G8R8A8_UNORM, RGBA32_FLOAT, RGBA32_UINT, and RGBA8_UBYTE.
Referenced by _mesa_half_to_signed(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), read_rgba_pixels(), and texstore_rgba().
_mesa_format_to_array()
bool _mesa_format_to_array (mesa_format format, GLenum * type, int * num_components, uint8_t swizzle[4], bool * normalized)
Describes a format as an array format, if possible.
A helper function for figuring out if a (possibly packed) format is actually an array format and, if so, what the array parameters are.
Parameters
[in] format the mesa format
[out] type the GL type of the array (GL_BYTE, etc.)
[out] num_components the number of components in the array
[out] swizzle a swizzle describing how to get from the given format to RGBA
[out] normalized for integer formats, this represents whether the format is a normalized integer or a regular integer
Returns
true if this format is an array format, false otherwise
References _mesa_get_format_bytes(), _mesa_get_format_layout(), _mesa_get_format_max_bits(), _mesa_get_format_swizzle(), _mesa_is_format_compressed(), _mesa_is_format_integer(), _mesa_little_endian(), _mesa_uncompressed_format_to_type_and_comps(), GLuint, map_1032, map_3210, map_identity, MESA_FORMAT_LAYOUT_ARRAY, MESA_FORMAT_LAYOUT_OTHER, and MESA_FORMAT_LAYOUT_PACKED.
Referenced by _mesa_half_to_signed().
_mesa_half_to_signed()
static unsigned _mesa_half_to_signed (uint16_t src, unsigned dst_bits) inline static
References _mesa_compute_rgba2base2rgba_component_mapping(), _mesa_float_to_signed(), _mesa_format_convert(), _mesa_format_to_array(), _mesa_swizzle_and_convert(), and swizzle().
Referenced by convert_byte(), convert_int(), and convert_short().
_mesa_half_to_snorm()
static int _mesa_half_to_snorm (uint16_t x, unsigned dst_bits) inline static
References _mesa_float_to_snorm().
Referenced by convert_byte(), convert_int(), and convert_short().
_mesa_half_to_unorm()
static unsigned _mesa_half_to_unorm (uint16_t x, unsigned dst_bits) inline static
References _mesa_float_to_unorm().
Referenced by convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_half_to_unsigned()
static unsigned _mesa_half_to_unsigned (uint16_t src, unsigned dst_bits) inline static
References _mesa_half_is_negative(), and _mesa_unsigned_to_unsigned().
Referenced by convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_signed_to_signed()
static int _mesa_signed_to_signed (int src, unsigned dst_size) inline static
References MAX_INT, and MIN_INT.
Referenced by _mesa_float_to_signed(), convert_byte(), convert_integer(), convert_integer_luminance64(), and convert_short().
_mesa_signed_to_unsigned()
static unsigned _mesa_signed_to_unsigned (int src, unsigned dst_size) inline static
References MAX_UINT.
Referenced by _mesa_float_to_unsigned(), convert_integer(), convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_snorm_to_float()
static float _mesa_snorm_to_float (int x, unsigned src_bits) inline static
References MAX_INT.
Referenced by _mesa_snorm_to_half(), and convert_float().
_mesa_snorm_to_half()
static uint16_t _mesa_snorm_to_half (int x, unsigned src_bits) inline static
References _mesa_snorm_to_float().
Referenced by convert_half_float().
_mesa_snorm_to_snorm()
static int _mesa_snorm_to_snorm (int x, unsigned src_bits, unsigned dst_bits) inline static
References EXTEND_NORMALIZED_INT, and MAX_INT.
Referenced by convert_byte(), convert_int(), and convert_short().
_mesa_snorm_to_unorm()
static unsigned _mesa_snorm_to_unorm (int x, unsigned src_bits, unsigned dst_bits) inline static
References _mesa_unorm_to_unorm().
Referenced by convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_swizzle_and_convert()
void _mesa_swizzle_and_convert (void * void_dst, enum mesa_array_format_datatype dst_type, int num_dst_channels, const void * void_src, enum mesa_array_format_datatype src_type, int num_src_channels, const uint8_t swizzle[4], bool normalized, int count)
Convert between array-based color formats.
Most format conversion operations required by GL can be performed by converting one channel at a time, shuffling the channels around, and optionally filling missing channels with zeros and ones. This function does just that in a general, yet efficient, way.
The swizzle parameter is an array of 4 numbers (see _mesa_get_format_swizzle) that describes where each channel in the destination should come from in the source. If swizzle[i] < 4 then it means that dst[i] = CONVERT(src[swizzle[i]]). If swizzle[i] is MESA_FORMAT_SWIZZLE_ZERO or MESA_FORMAT_SWIZZLE_ONE, the corresponding dst[i] will be filled with the appropreate representation of zero or one respectively.
Under most circumstances, the source and destination images must be different as no care is taken not to clobber one with the other. However, if they have the same number of bits per pixel, it is safe to do an in-place conversion.
Parameters
[out] dst pointer to where the converted data should be stored
[in] dst_type the destination GL type of the converted data (GL_BYTE, etc.)
[in] num_dst_channels the number of channels in the converted data
[in] src pointer to the source data
[in] src_type the GL type of the source data (GL_BYTE, etc.)
[in] num_src_channels the number of channels in the source data (the number of channels total, not just the number used)
[in] swizzle describes how to get the destination data from the source data.
[in] normalized for integer types, this indicates whether the data should be considered as integers or as normalized integers;
[in] count the number of pixels to convert
References convert_byte(), convert_float(), convert_half_float(), convert_int(), convert_short(), convert_ubyte(), convert_uint(), convert_ushort(), MESA_ARRAY_FORMAT_TYPE_BYTE, MESA_ARRAY_FORMAT_TYPE_FLOAT, MESA_ARRAY_FORMAT_TYPE_HALF, MESA_ARRAY_FORMAT_TYPE_INT, MESA_ARRAY_FORMAT_TYPE_SHORT, MESA_ARRAY_FORMAT_TYPE_UBYTE, MESA_ARRAY_FORMAT_TYPE_UINT, MESA_ARRAY_FORMAT_TYPE_USHORT, and swizzle_convert_try_memcpy().
Referenced by _mesa_format_convert(), and _mesa_half_to_signed().
_mesa_unorm_to_float()
static float _mesa_unorm_to_float (unsigned x, unsigned src_bits) inline static
References MAX_UINT.
Referenced by _mesa_unorm_to_half(), and convert_float().
_mesa_unorm_to_half()
static uint16_t _mesa_unorm_to_half (unsigned x, unsigned src_bits) inline static
References _mesa_unorm_to_float().
Referenced by convert_half_float().
_mesa_unorm_to_snorm()
static int _mesa_unorm_to_snorm (unsigned x, unsigned src_bits, unsigned dst_bits) inline static
References _mesa_unorm_to_unorm().
Referenced by convert_byte(), convert_int(), and convert_short().
_mesa_unorm_to_unorm()
static unsigned _mesa_unorm_to_unorm (unsigned x, unsigned src_bits, unsigned dst_bits) inline static
References EXTEND_NORMALIZED_INT, MAX_UINT, and x.
Referenced by _mesa_snorm_to_unorm(), _mesa_unorm_to_snorm(), convert_ubyte(), convert_uint(), and convert_ushort().
_mesa_unsigned_to_signed()
static int _mesa_unsigned_to_signed (unsigned src, unsigned dst_size) inline static
References MAX_INT.
Referenced by convert_byte(), convert_int(), convert_integer(), and convert_short().
_mesa_unsigned_to_unsigned()
static unsigned _mesa_unsigned_to_unsigned (unsigned src, unsigned dst_size) inline static
References MAX_UINT.
Referenced by _mesa_half_to_unsigned(), convert_integer(), convert_integer_luminance64(), convert_ubyte(), and convert_ushort().
Variable Documentation
RGBA32_FLOAT
const mesa_array_format RGBA32_FLOAT
Referenced by _mesa_format_convert(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), read_rgba_pixels(), and texstore_rgba().
RGBA32_INT
const mesa_array_format RGBA32_INT
Referenced by read_rgba_pixels().
RGBA32_UINT
const mesa_array_format RGBA32_UINT
Referenced by _mesa_format_convert(), and read_rgba_pixels().
RGBA8_UBYTE
const mesa_array_format RGBA8_UBYTE
Referenced by _mesa_format_convert().