Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
formatquery.h File Reference
#include "compiler.h"
#include "glheader.h"
Functions
size_t _mesa_query_samples_for_format (struct gl_context *ctx, GLenum target, GLenum internalFormat, int samples[16])
void _mesa_query_internal_format_default (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params)
void GLAPIENTRY _mesa_GetInternalformati64v (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 *params)
Function Documentation
_mesa_GetInternalformati64v()
void GLAPIENTRY _mesa_GetInternalformati64v (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 * params)
References _mesa_error(), _mesa_GetInternalformativ(), ASSERT_OUTSIDE_BEGIN_END, and GET_CURRENT_CONTEXT.
_mesa_GetInternalformativ()
void GLAPIENTRY _mesa_GetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint * params)
References _equivalent_size_pname(), _get_min_dimensions(), _get_target_dimensions(), _is_internalformat_supported(), _is_multisample_target(), _is_renderable(), _is_resource_supported(), _is_target_supported(), _legal_parameters(), _legal_target_for_framebuffer_texture_layer(), _mesa_base_fbo_format(), _mesa_base_format_has_channel(), _mesa_base_format_to_integer_format(), _mesa_base_tex_format(), _mesa_delete_texture_object(), _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_block_size(), _mesa_get_format_bytes(), _mesa_get_format_datatype(), _mesa_get_image_format_class(), _mesa_get_shader_image_format(), _mesa_GetIntegerv(), _mesa_GetInternalformativ(), _mesa_glenum_to_compressed_format(), _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_is_array_texture(), _mesa_is_color_format(), _mesa_is_compressed_format(), _mesa_is_cube_map_texture(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), _mesa_is_desktop_gl(), _mesa_is_enum_format_integer(), _mesa_is_gles3(), _mesa_is_shader_image_format_supported(), _mesa_is_srgb_format(), _mesa_is_stencil_format(), _mesa_is_valid_generate_texture_mipmap_internalformat(), _mesa_is_valid_generate_texture_mipmap_target(), _mesa_legal_get_tex_level_parameter_target(), _mesa_new_texture_object(), _mesa_target_allows_setting_sampler_parameters(), _mesa_texture_view_lookup_view_class(), _mesa_uncompressed_format_to_type_and_comps(), _mesa_warning(), _set_default_response(), API_OPENGL_CORE, API_OPENGLES2, ASSERT_OUTSIDE_BEGIN_END, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_texture_object::ImageFormatCompatibilityType, MESA_FORMAT_NONE, and MESA_FORMAT_R9G9B9E5_FLOAT.
Referenced by _mesa_GetInternalformati64v(), and _mesa_GetInternalformativ().
_mesa_query_internal_format_default()
void _mesa_query_internal_format_default (struct gl_context * ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint * params)
References _mesa_base_format_to_integer_format(), _mesa_base_tex_format(), _mesa_generic_type_for_internal_format(), _mesa_is_enum_format_integer(), _set_default_response(), and void.
_mesa_query_samples_for_format()
size_t _mesa_query_samples_for_format (struct gl_context * ctx, GLenum target, GLenum internalFormat, int samples[16])