Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
format_unpack.h File Reference
#include "formats.h"
Functions
void _mesa_unpack_rgba_row (mesa_format format, GLuint n, const void *src, GLfloat dst[][4])
void _mesa_unpack_ubyte_rgba_row (mesa_format format, GLuint n, const void *src, GLubyte dst[][4])
void _mesa_unpack_uint_rgba_row (mesa_format format, GLuint n, const void *src, GLuint dst[][4])
void _mesa_unpack_rgba_block (mesa_format format, const void *src, GLint srcRowStride, GLfloat dst[][4], GLint dstRowStride, GLuint x, GLuint y, GLuint width, GLuint height)
void _mesa_unpack_float_z_row (mesa_format format, GLuint n, const void *src, GLfloat *dst)
void _mesa_unpack_uint_z_row (mesa_format format, GLuint n, const void *src, GLuint *dst)
void _mesa_unpack_ubyte_stencil_row (mesa_format format, GLuint n, const void *src, GLubyte *dst)
void _mesa_unpack_uint_24_8_depth_stencil_row (mesa_format format, GLuint n, const void *src, GLuint *dst)
void _mesa_unpack_float_32_uint_24_8_depth_stencil_row (mesa_format format, GLuint n, const void *src, GLuint *dst)
void _mesa_unpack_depth_stencil_row (mesa_format format, GLuint n, const void *src, GLenum type, GLuint *dst)
Function Documentation
_mesa_unpack_depth_stencil_row()
void _mesa_unpack_depth_stencil_row (mesa_format format, GLuint n, const void * src, GLenum type, GLuint * dst)
Referenced by get_tex_depth_stencil().
_mesa_unpack_float_32_uint_24_8_depth_stencil_row()
void _mesa_unpack_float_32_uint_24_8_depth_stencil_row (mesa_format format, GLuint n, const void * src, GLuint * dst)
_mesa_unpack_float_z_row()
void _mesa_unpack_float_z_row (mesa_format format, GLuint n, const void * src, GLfloat * dst)
Referenced by get_tex_depth(), read_depth_pixels(), and slow_read_depth_stencil_pixels_separate().
_mesa_unpack_rgba_block()
void _mesa_unpack_rgba_block (mesa_format format, const void * src, GLint srcRowStride, GLfloat dst[][4], GLint dstRowStride, GLuint x, GLuint y, GLuint width, GLuint height)
_mesa_unpack_rgba_row()
void _mesa_unpack_rgba_row (mesa_format format, GLuint n, const void * src, GLfloat dst[][4])
Referenced by _mesa_format_convert(), accum_or_load(), and accum_return().
_mesa_unpack_ubyte_rgba_row()
void _mesa_unpack_ubyte_rgba_row (mesa_format format, GLuint n, const void * src, GLubyte dst[][4])
Referenced by _mesa_format_convert().
_mesa_unpack_ubyte_stencil_row()
void _mesa_unpack_ubyte_stencil_row (mesa_format format, GLuint n, const void * src, GLubyte * dst)
Referenced by fast_read_depth_stencil_pixels_separate(), get_tex_stencil(), read_stencil_pixels(), and slow_read_depth_stencil_pixels_separate().
_mesa_unpack_uint_24_8_depth_stencil_row()
void _mesa_unpack_uint_24_8_depth_stencil_row (mesa_format format, GLuint n, const void * src, GLuint * dst)
Referenced by fast_read_depth_stencil_pixels().
_mesa_unpack_uint_rgba_row()
void _mesa_unpack_uint_rgba_row (mesa_format format, GLuint n, const void * src, GLuint dst[][4])
Referenced by _mesa_format_convert().
_mesa_unpack_uint_z_row()
void _mesa_unpack_uint_z_row (mesa_format format, GLuint n, const void * src, GLuint * dst)
Referenced by fast_read_depth_stencil_pixels_separate(), and read_uint_depth_pixels().