Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
format_pack.h File Reference
#include "formats.h"
Typedefs
typedef void(* gl_pack_ubyte_rgba_func) (const GLubyte src[4], void *dst)
Pack a GLubyte rgba[4] color to dest address.
typedef void(* gl_pack_float_rgba_func) (const GLfloat src[4], void *dst)
Pack a GLfloat rgba[4] color to dest address.
typedef void(* gl_pack_float_z_func) (const GLfloat *src, void *dst)
Pack a GLfloat Z value to dest address.
typedef void(* gl_pack_uint_z_func) (const GLuint *src, void *dst)
Pack a GLuint Z value to dest address.
typedef void(* gl_pack_ubyte_stencil_func) (const GLubyte *src, void *dst)
Pack a GLubyte stencil value to dest address.
Functions
gl_pack_ubyte_rgba_func _mesa_get_pack_ubyte_rgba_function (mesa_format format)
gl_pack_float_rgba_func _mesa_get_pack_float_rgba_function (mesa_format format)
gl_pack_float_z_func _mesa_get_pack_float_z_func (mesa_format format)
gl_pack_uint_z_func _mesa_get_pack_uint_z_func (mesa_format format)
gl_pack_ubyte_stencil_func _mesa_get_pack_ubyte_stencil_func (mesa_format format)
void _mesa_pack_float_rgba_row (mesa_format format, GLuint n, const GLfloat src[][4], void *dst)
void _mesa_pack_ubyte_rgba_row (mesa_format format, GLuint n, const GLubyte src[][4], void *dst)
void _mesa_pack_uint_rgba_row (mesa_format format, GLuint n, const GLuint src[][4], void *dst)
void _mesa_pack_ubyte_rgba_rect (mesa_format format, GLuint width, GLuint height, const GLubyte *src, GLint srcRowStride, void *dst, GLint dstRowStride)
void _mesa_pack_float_z_row (mesa_format format, GLuint n, const GLfloat *src, void *dst)
void _mesa_pack_uint_z_row (mesa_format format, GLuint n, const GLuint *src, void *dst)
void _mesa_pack_ubyte_stencil_row (mesa_format format, GLuint n, const GLubyte *src, void *dst)
void _mesa_pack_uint_24_8_depth_stencil_row (mesa_format format, GLuint n, const GLuint *src, void *dst)
void _mesa_pack_colormask (mesa_format format, const GLubyte colorMask[4], void *dst)
Typedef Documentation
gl_pack_float_rgba_func
typedef void(* gl_pack_float_rgba_func) (const GLfloat src[4], void *dst)
Pack a GLfloat rgba[4] color to dest address.
gl_pack_float_z_func
typedef void(* gl_pack_float_z_func) (const GLfloat *src, void *dst)
Pack a GLfloat Z value to dest address.
gl_pack_ubyte_rgba_func
typedef void(* gl_pack_ubyte_rgba_func) (const GLubyte src[4], void *dst)
Pack a GLubyte rgba[4] color to dest address.
gl_pack_ubyte_stencil_func
typedef void(* gl_pack_ubyte_stencil_func) (const GLubyte *src, void *dst)
Pack a GLubyte stencil value to dest address.
gl_pack_uint_z_func
typedef void(* gl_pack_uint_z_func) (const GLuint *src, void *dst)
Pack a GLuint Z value to dest address.
Function Documentation
_mesa_get_pack_float_rgba_function()
gl_pack_float_rgba_func _mesa_get_pack_float_rgba_function (mesa_format format)
_mesa_get_pack_float_z_func()
gl_pack_float_z_func _mesa_get_pack_float_z_func (mesa_format format)
_mesa_get_pack_ubyte_rgba_function()
gl_pack_ubyte_rgba_func _mesa_get_pack_ubyte_rgba_function (mesa_format format)
_mesa_get_pack_ubyte_stencil_func()
gl_pack_ubyte_stencil_func _mesa_get_pack_ubyte_stencil_func (mesa_format format)
_mesa_get_pack_uint_z_func()
gl_pack_uint_z_func _mesa_get_pack_uint_z_func (mesa_format format)
_mesa_pack_colormask()
void _mesa_pack_colormask (mesa_format format, const GLubyte colorMask[4], void * dst)
_mesa_pack_float_rgba_row()
void _mesa_pack_float_rgba_row (mesa_format format, GLuint n, const GLfloat src[][4], void * dst)
Referenced by _mesa_format_convert(), and accum_return().
_mesa_pack_float_z_row()
void _mesa_pack_float_z_row (mesa_format format, GLuint n, const GLfloat * src, void * dst)
_mesa_pack_ubyte_rgba_rect()
void _mesa_pack_ubyte_rgba_rect (mesa_format format, GLuint width, GLuint height, const GLubyte * src, GLint srcRowStride, void * dst, GLint dstRowStride)
_mesa_pack_ubyte_rgba_row()
void _mesa_pack_ubyte_rgba_row (mesa_format format, GLuint n, const GLubyte src[][4], void * dst)
Referenced by _mesa_format_convert().
_mesa_pack_ubyte_stencil_row()
void _mesa_pack_ubyte_stencil_row (mesa_format format, GLuint n, const GLubyte * src, void * dst)
_mesa_pack_uint_24_8_depth_stencil_row()
void _mesa_pack_uint_24_8_depth_stencil_row (mesa_format format, GLuint n, const GLuint * src, void * dst)
_mesa_pack_uint_rgba_row()
void _mesa_pack_uint_rgba_row (mesa_format format, GLuint n, const GLuint src[][4], void * dst)
Referenced by _mesa_format_convert().
_mesa_pack_uint_z_row()
void _mesa_pack_uint_z_row (mesa_format format, GLuint n, const GLuint * src, void * dst)