Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
formats.c File Reference
#include "imports.h"
#include "formats.h"
#include "macros.h"
#include "glformats.h"
#include "c11/threads.h"
#include "util/hash_table.h"
#include "format_info.h"
Data Structures
struct gl_format_info
Information about texture formats.
Functions
static const struct gl_format_info * _mesa_get_format_info (mesa_format format)
const char * _mesa_get_format_name (mesa_format format)
Return string name of format (for debugging)
GLint _mesa_get_format_bytes (mesa_format format)
Return bytes needed to store a block of pixels in the given format.
GLint _mesa_get_format_bits (mesa_format format, GLenum pname)
Return bits per component for the given format.
GLuint _mesa_get_format_max_bits (mesa_format format)
enum mesa_format_layout _mesa_get_format_layout (mesa_format format)
Return the layout type of the given format.
GLenum _mesa_get_format_datatype (mesa_format format)
Return the data type (or more specifically, the data representation) for the given format.
static GLenum get_base_format_for_array_format (mesa_array_format format)
GLenum _mesa_get_format_base_format (uint32_t format)
Return the basic format for the given type.
void _mesa_get_format_block_size (mesa_format format, GLuint *bw, GLuint *bh)
Return the block size (in pixels) for the given format.
void _mesa_get_format_block_size_3d (mesa_format format, GLuint *bw, GLuint *bh, GLuint *bd)
Return the block size (in pixels) for the given format.
void _mesa_get_format_swizzle (mesa_format format, uint8_t swizzle_out[4])
Returns the an array of four numbers representing the transformation from the RGBA or SZ colorspace to the given format.
mesa_array_format _mesa_array_format_flip_channels (mesa_array_format format)
uint32_t _mesa_format_to_array_format (mesa_format format)
static bool array_formats_equal (const void *a, const void *b)
static void format_array_format_table_init (void)
mesa_format _mesa_format_from_array_format (uint32_t array_format)
GLboolean _mesa_is_format_compressed (mesa_format format)
Is the given format a compressed format?
GLboolean _mesa_is_format_packed_depth_stencil (mesa_format format)
Determine if the given format represents a packed depth/stencil buffer.
GLboolean _mesa_is_format_integer_color (mesa_format format)
Is the given format a signed/unsigned integer color format?
GLboolean _mesa_is_format_unsigned (mesa_format format)
Is the given format an unsigned integer format?
GLboolean _mesa_is_format_signed (mesa_format format)
Does the given format store signed values?
GLboolean _mesa_is_format_integer (mesa_format format)
Is the given format an integer format?
GLenum _mesa_is_format_color_format (mesa_format format)
Return true if the given format is a color format.
GLenum _mesa_get_format_color_encoding (mesa_format format)
Return color encoding for given format.
bool _mesa_is_format_etc2 (mesa_format format)
Return TRUE if format is an ETC2 compressed format specified by GL_ARB_ES3_compatibility.
mesa_format _mesa_get_srgb_format_linear (mesa_format format)
For an sRGB format, return the corresponding linear color space format.
mesa_format _mesa_get_uncompressed_format (mesa_format format)
If the given format is a compressed format, return a corresponding uncompressed format.
GLuint _mesa_format_num_components (mesa_format format)
bool _mesa_format_has_color_component (mesa_format format, int component)
Returns true if a color format has data stored in the R/G/B/A channels, given an index from 0 to 3.
GLuint _mesa_format_image_size (mesa_format format, GLsizei width, GLsizei height, GLsizei depth)
Return number of bytes needed to store an image of the given size in the given format.
uint64_t _mesa_format_image_size64 (mesa_format format, GLsizei width, GLsizei height, GLsizei depth)
Same as _mesa_format_image_size() but returns a 64-bit value to accommodate very large textures.
GLint _mesa_format_row_stride (mesa_format format, GLsizei width)
Non-normalized unsigned integer formats.
Return datatype and number of components per texel for the given uncompressed mesa_format.
Only used for mipmap generation code.
GLboolean _mesa_format_matches_format_and_type (mesa_format mesa_format, GLenum format, GLenum type, GLboolean swapBytes, GLenum *error)
Check if a mesa_format exactly matches a GL format/type combination such that we can use memcpy() from one to the other.
Variables
static struct hash_table * format_array_format_table
static once_flag format_array_format_table_exists = ONCE_FLAG_INIT
Function Documentation
_mesa_array_format_flip_channels()
mesa_array_format _mesa_array_format_flip_channels (mesa_array_format format)
References _mesa_array_format_get_num_channels(), _mesa_array_format_get_swizzle(), _mesa_array_format_set_swizzle(), and swizzle().
Referenced by _mesa_format_to_array_format(), and format_array_format_table_init().
_mesa_format_from_array_format()
mesa_format _mesa_format_from_array_format (uint32_t array_format)
References _mesa_format_is_mesa_array_format(), format_array_format_table, format_array_format_table_exists, format_array_format_table_init(), and MESA_FORMAT_NONE.
Referenced by _mesa_tex_format_from_format_and_type().
_mesa_format_has_color_component()
bool _mesa_format_has_color_component (mesa_format format, int component)
Returns true if a color format has data stored in the R/G/B/A channels, given an index from 0 to 3.
References _mesa_get_format_info(), gl_format_info::AlphaBits, gl_format_info::BaseFormat, gl_format_info::BlueBits, GLuint, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, and gl_format_info::RedBits.
Referenced by color_buffer_writes_enabled().
_mesa_format_image_size()
GLuint _mesa_format_image_size (mesa_format format, GLsizei width, GLsizei height, GLsizei depth)
Return number of bytes needed to store an image of the given size in the given format.
References _mesa_get_format_info(), gl_format_info::BlockDepth, gl_format_info::BlockHeight, gl_format_info::BlockWidth, gl_format_info::BytesPerBlock, and GLuint.
Referenced by _mesa_CompressedTextureSubImage3D(), compressed_tex_size(), generate_mipmap_compressed(), get_tex_level_parameter_image(), and texture_size().
_mesa_format_image_size64()
uint64_t _mesa_format_image_size64 (mesa_format format, GLsizei width, GLsizei height, GLsizei depth)
Same as _mesa_format_image_size() but returns a 64-bit value to accommodate very large textures.
References _mesa_get_format_info(), gl_format_info::BlockDepth, gl_format_info::BlockHeight, gl_format_info::BlockWidth, and gl_format_info::BytesPerBlock.
Referenced by _mesa_test_proxy_teximage().
_mesa_format_matches_format_and_type()
GLboolean _mesa_format_matches_format_and_type (mesa_format mesa_format, GLenum format, GLenum type, GLboolean swapBytes, GLenum * error)
Check if a mesa_format exactly matches a GL format/type combination such that we can use memcpy() from one to the other.
Parameters
mesa_format a MESA_FORMAT_x value
format the user-specified image format
type the user-specified image datatype
swapBytes typically the current pixel pack/unpack byteswap state
[out] error GL_NO_ERROR if format is an expected input. GL_INVALID_ENUM if format is an unexpected input.
Returns
GL_TRUE if the formats match, GL_FALSE otherwise.
References _mesa_is_format_compressed(), _mesa_little_endian(), MESA_FORMAT_A16L16_UNORM, MESA_FORMAT_A1B5G5R5_UINT, MESA_FORMAT_A1B5G5R5_UNORM, MESA_FORMAT_A1R5G5B5_UINT, MESA_FORMAT_A1R5G5B5_UNORM, MESA_FORMAT_A2B10G10R10_UINT, MESA_FORMAT_A2B10G10R10_UNORM, MESA_FORMAT_A2R10G10B10_UINT, MESA_FORMAT_A2R10G10B10_UNORM, MESA_FORMAT_A4B4G4R4_UINT, MESA_FORMAT_A4B4G4R4_UNORM, MESA_FORMAT_A4R4G4B4_UINT, MESA_FORMAT_A4R4G4B4_UNORM, MESA_FORMAT_A8B8G8R8_SNORM, MESA_FORMAT_A8B8G8R8_SRGB, MESA_FORMAT_A8B8G8R8_UINT, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_SNORM, MESA_FORMAT_A8L8_SRGB, MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_A8R8G8B8_SRGB, MESA_FORMAT_A8R8G8B8_UINT, MESA_FORMAT_A8R8G8B8_UNORM, MESA_FORMAT_A_FLOAT16, MESA_FORMAT_A_FLOAT32, MESA_FORMAT_A_SINT16, MESA_FORMAT_A_SINT32, MESA_FORMAT_A_SINT8, MESA_FORMAT_A_SNORM16, MESA_FORMAT_A_SNORM8, MESA_FORMAT_A_UINT16, MESA_FORMAT_A_UINT32, MESA_FORMAT_A_UINT8, MESA_FORMAT_A_UNORM16, MESA_FORMAT_A_UNORM8, MESA_FORMAT_B10G10R10A2_UINT, MESA_FORMAT_B10G10R10A2_UNORM, MESA_FORMAT_B10G10R10X2_UNORM, MESA_FORMAT_B2G3R3_UINT, MESA_FORMAT_B2G3R3_UNORM, MESA_FORMAT_B4G4R4A4_UINT, MESA_FORMAT_B4G4R4A4_UNORM, MESA_FORMAT_B4G4R4X4_UNORM, MESA_FORMAT_B5G5R5A1_UINT, MESA_FORMAT_B5G5R5A1_UNORM, MESA_FORMAT_B5G5R5X1_UNORM, MESA_FORMAT_B5G6R5_UINT, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UINT, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_BGR_SRGB8, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_COUNT, MESA_FORMAT_G16R16_SNORM, MESA_FORMAT_G16R16_UNORM, MESA_FORMAT_G8R8_SNORM, MESA_FORMAT_G8R8_UNORM, MESA_FORMAT_I_FLOAT16, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_I_SINT16, MESA_FORMAT_I_SINT32, MESA_FORMAT_I_SINT8, MESA_FORMAT_I_SNORM16, MESA_FORMAT_I_SNORM8, MESA_FORMAT_I_UINT16, MESA_FORMAT_I_UINT32, MESA_FORMAT_I_UINT8, MESA_FORMAT_I_UNORM16, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L16A16_UNORM, MESA_FORMAT_L4A4_UNORM, MESA_FORMAT_L8A8_SNORM, MESA_FORMAT_L8A8_SRGB, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_FLOAT16, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_L_SINT16, MESA_FORMAT_L_SINT32, MESA_FORMAT_L_SINT8, MESA_FORMAT_L_SNORM16, MESA_FORMAT_L_SNORM8, MESA_FORMAT_L_SRGB8, MESA_FORMAT_L_UINT16, MESA_FORMAT_L_UINT32, MESA_FORMAT_L_UINT8, MESA_FORMAT_L_UNORM16, MESA_FORMAT_L_UNORM8, MESA_FORMAT_LA_FLOAT16, MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_SINT16, MESA_FORMAT_LA_SINT32, MESA_FORMAT_LA_SINT8, MESA_FORMAT_LA_SNORM16, MESA_FORMAT_LA_UINT16, MESA_FORMAT_LA_UINT32, MESA_FORMAT_LA_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R10G10B10X2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R16G16_SNORM, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R3G3B2_UINT, MESA_FORMAT_R3G3B2_UNORM, MESA_FORMAT_R4G4B4A4_UINT, MESA_FORMAT_R4G4B4A4_UNORM, MESA_FORMAT_R5G5B5A1_UINT, MESA_FORMAT_R5G5B5A1_UNORM, MESA_FORMAT_R5G6B5_UINT, MESA_FORMAT_R5G6B5_UNORM, MESA_FORMAT_R8G8_SNORM, MESA_FORMAT_R8G8_UNORM, MESA_FORMAT_R8G8B8A8_SNORM, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UINT, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_R9G9B9E5_FLOAT, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_SNORM16, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_SINT16, MESA_FORMAT_RGB_SINT32, MESA_FORMAT_RGB_SINT8, MESA_FORMAT_RGB_SNORM16, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGB_UNORM8, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBA_UNORM16, MESA_FORMAT_RGBX_FLOAT16, MESA_FORMAT_RGBX_FLOAT32, MESA_FORMAT_RGBX_SINT16, MESA_FORMAT_RGBX_SINT32, MESA_FORMAT_RGBX_SINT8, MESA_FORMAT_RGBX_SNORM16, MESA_FORMAT_RGBX_UINT16, MESA_FORMAT_RGBX_UINT32, MESA_FORMAT_RGBX_UINT8, MESA_FORMAT_RGBX_UNORM16, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_X8_UINT_Z24_UNORM, MESA_FORMAT_X8B8G8R8_SNORM, MESA_FORMAT_X8B8G8R8_SRGB, MESA_FORMAT_X8B8G8R8_UNORM, MESA_FORMAT_X8R8G8B8_SRGB, MESA_FORMAT_X8R8G8B8_UNORM, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, and MESA_FORMAT_Z_UNORM32.
Referenced by _mesa_texstore_can_use_memcpy(), get_tex_memcpy(), and readpixels_can_use_memcpy().
_mesa_format_num_components()
GLuint _mesa_format_num_components (mesa_format format)
References _mesa_get_format_info(), gl_format_info::AlphaBits, gl_format_info::BlueBits, gl_format_info::DepthBits, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, gl_format_info::RedBits, and gl_format_info::StencilBits.
Referenced by generate_mipmap_compressed().
_mesa_format_row_stride()
GLint _mesa_format_row_stride (mesa_format format, GLsizei width)
References _mesa_get_format_info(), _mesa_get_format_name(), _mesa_is_format_compressed(), _mesa_problem(), _mesa_uncompressed_format_to_type_and_comps(), gl_format_info::BlockHeight, gl_format_info::BlockWidth, gl_format_info::BytesPerBlock, GLuint, MESA_FORMAT_A16L16_UNORM, MESA_FORMAT_A1B5G5R5_UINT, MESA_FORMAT_A1B5G5R5_UNORM, MESA_FORMAT_A1R5G5B5_UINT, MESA_FORMAT_A1R5G5B5_UNORM, MESA_FORMAT_A2B10G10R10_UINT, MESA_FORMAT_A2B10G10R10_UNORM, MESA_FORMAT_A2R10G10B10_UINT, MESA_FORMAT_A2R10G10B10_UNORM, MESA_FORMAT_A4B4G4R4_UINT, MESA_FORMAT_A4B4G4R4_UNORM, MESA_FORMAT_A4R4G4B4_UINT, MESA_FORMAT_A4R4G4B4_UNORM, MESA_FORMAT_A8B8G8R8_SNORM, MESA_FORMAT_A8B8G8R8_SRGB, MESA_FORMAT_A8B8G8R8_UINT, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_SNORM, MESA_FORMAT_A8L8_SRGB, MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_A8R8G8B8_SRGB, MESA_FORMAT_A8R8G8B8_UINT, MESA_FORMAT_A8R8G8B8_UNORM, MESA_FORMAT_A_FLOAT16, MESA_FORMAT_A_FLOAT32, MESA_FORMAT_A_SINT16, MESA_FORMAT_A_SINT32, MESA_FORMAT_A_SINT8, MESA_FORMAT_A_SNORM16, MESA_FORMAT_A_SNORM8, MESA_FORMAT_A_UINT16, MESA_FORMAT_A_UINT32, MESA_FORMAT_A_UINT8, MESA_FORMAT_A_UNORM16, MESA_FORMAT_A_UNORM8, MESA_FORMAT_B10G10R10A2_UINT, MESA_FORMAT_B10G10R10A2_UNORM, MESA_FORMAT_B10G10R10X2_UNORM, MESA_FORMAT_B2G3R3_UINT, MESA_FORMAT_B2G3R3_UNORM, MESA_FORMAT_B4G4R4A4_UINT, MESA_FORMAT_B4G4R4A4_UNORM, MESA_FORMAT_B4G4R4X4_UNORM, MESA_FORMAT_B5G5R5A1_UINT, MESA_FORMAT_B5G5R5A1_UNORM, MESA_FORMAT_B5G5R5X1_UNORM, MESA_FORMAT_B5G6R5_UINT, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UINT, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_BGR_SRGB8, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_COUNT, MESA_FORMAT_G16R16_SNORM, MESA_FORMAT_G16R16_UNORM, MESA_FORMAT_G8R8_SNORM, MESA_FORMAT_G8R8_UNORM, MESA_FORMAT_I_FLOAT16, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_I_SINT16, MESA_FORMAT_I_SINT32, MESA_FORMAT_I_SINT8, MESA_FORMAT_I_SNORM16, MESA_FORMAT_I_SNORM8, MESA_FORMAT_I_UINT16, MESA_FORMAT_I_UINT32, MESA_FORMAT_I_UINT8, MESA_FORMAT_I_UNORM16, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L16A16_UNORM, MESA_FORMAT_L4A4_UNORM, MESA_FORMAT_L8A8_SNORM, MESA_FORMAT_L8A8_SRGB, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_FLOAT16, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_L_SINT16, MESA_FORMAT_L_SINT32, MESA_FORMAT_L_SINT8, MESA_FORMAT_L_SNORM16, MESA_FORMAT_L_SNORM8, MESA_FORMAT_L_SRGB8, MESA_FORMAT_L_UINT16, MESA_FORMAT_L_UINT32, MESA_FORMAT_L_UINT8, MESA_FORMAT_L_UNORM16, MESA_FORMAT_L_UNORM8, MESA_FORMAT_LA_FLOAT16, MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_SINT16, MESA_FORMAT_LA_SINT32, MESA_FORMAT_LA_SINT8, MESA_FORMAT_LA_SNORM16, MESA_FORMAT_LA_UINT16, MESA_FORMAT_LA_UINT32, MESA_FORMAT_LA_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R10G10B10X2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R16G16_SNORM, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R3G3B2_UINT, MESA_FORMAT_R3G3B2_UNORM, MESA_FORMAT_R4G4B4A4_UINT, MESA_FORMAT_R4G4B4A4_UNORM, MESA_FORMAT_R5G5B5A1_UINT, MESA_FORMAT_R5G5B5A1_UNORM, MESA_FORMAT_R5G6B5_UINT, MESA_FORMAT_R5G6B5_UNORM, MESA_FORMAT_R8G8_SNORM, MESA_FORMAT_R8G8_UNORM, MESA_FORMAT_R8G8B8A8_SNORM, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UINT, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_R9G9B9E5_FLOAT, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_SNORM16, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_SINT16, MESA_FORMAT_RGB_SINT32, MESA_FORMAT_RGB_SINT8, MESA_FORMAT_RGB_SNORM16, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGB_UNORM8, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBA_UNORM16, MESA_FORMAT_RGBX_FLOAT16, MESA_FORMAT_RGBX_FLOAT32, MESA_FORMAT_RGBX_SINT16, MESA_FORMAT_RGBX_SINT32, MESA_FORMAT_RGBX_SINT8, MESA_FORMAT_RGBX_SNORM16, MESA_FORMAT_RGBX_UINT16, MESA_FORMAT_RGBX_UINT32, MESA_FORMAT_RGBX_UINT8, MESA_FORMAT_RGBX_UNORM16, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_X8_UINT_Z24_UNORM, MESA_FORMAT_X8B8G8R8_SNORM, MESA_FORMAT_X8B8G8R8_SRGB, MESA_FORMAT_X8B8G8R8_UNORM, MESA_FORMAT_X8R8G8B8_SRGB, MESA_FORMAT_X8R8G8B8_UNORM, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, and MESA_UNSIGNED_BYTE_4_4.
Referenced by _mesa_compute_compressed_pixelstore(), and generate_mipmap_compressed().
_mesa_format_to_array_format()
uint32_t _mesa_format_to_array_format (mesa_format format)
References _mesa_array_format_flip_channels(), _mesa_get_format_info(), _mesa_little_endian(), gl_format_info::ArrayFormat, gl_format_info::Layout, and MESA_FORMAT_LAYOUT_PACKED.
Referenced by _mesa_format_convert().
_mesa_get_format_base_format()
GLenum _mesa_get_format_base_format (uint32_t format)
Return the basic format for the given type.
The result will be one of GL_RGB, GL_RGBA, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, GL_YCBCR_MESA, GL_DEPTH_COMPONENT, GL_STENCIL_INDEX, GL_DEPTH_STENCIL. This functions accepts a mesa_format or a mesa_array_format.
References _mesa_format_is_mesa_array_format(), _mesa_get_format_info(), gl_format_info::BaseFormat, and get_base_format_for_array_format().
Referenced by _mesa_get_readpixels_transfer_ops(), _mesa_texstore_can_use_memcpy(), _mesa_update_framebuffer_visual(), _mesa_validate_texbuffer_format(), convert_clear_buffer_data(), framebuffer_renderbuffer(), generate_mipmap_compressed(), get_read_write_mode(), get_tex_level_parameter_buffer(), get_tex_memcpy(), get_tex_rgba_compressed(), getteximage_error_check(), is_format_color_renderable(), read_rgba_pixels(), readpixels_can_use_memcpy(), teximage_needs_rebase(), and texstore_rgba().
_mesa_get_format_bits()
GLint _mesa_get_format_bits (mesa_format format, GLenum pname)
Return bits per component for the given format.
Parameters
format one of MESA_FORMAT_x
pname the component, such as GL_RED_BITS, GL_TEXTURE_BLUE_BITS, etc.
References _mesa_get_format_info(), _mesa_problem(), gl_format_info::AlphaBits, gl_format_info::BlueBits, gl_format_info::DepthBits, GLuint, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, gl_format_info::RedBits, and gl_format_info::StencilBits.
Referenced by _mesa_blit_framebuffer(), _mesa_GetInternalformativ(), _mesa_update_framebuffer_visual(), find_custom_value(), formats_differ_in_component_sizes(), get_component_bits(), get_copy_tex_image_source(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), and renderbuffer_exists().
_mesa_get_format_block_size()
void _mesa_get_format_block_size (mesa_format format, GLuint * bw, GLuint * bh)
Return the block size (in pixels) for the given format.
Normally the block size is 1x1. But compressed formats will have block sizes of 4x4 or 8x4 pixels, etc.
Parameters
bw returns block width in pixels
bh returns block height in pixels
References _mesa_get_format_info(), gl_format_info::BlockDepth, gl_format_info::BlockHeight, and gl_format_info::BlockWidth.
Referenced by _mesa_compressed_image_address(), _mesa_CopyImageSubData(), _mesa_decompress_image(), and _mesa_GetInternalformativ().
_mesa_get_format_block_size_3d()
void _mesa_get_format_block_size_3d (mesa_format format, GLuint * bw, GLuint * bh, GLuint * bd)
Return the block size (in pixels) for the given format.
Normally the block size is 1x1x1. But compressed formats will have block sizes of 4x4x4, 3x3x3 pixels, etc.
Parameters
bw returns block width in pixels
bh returns block height in pixels
bd returns block depth in pixels
References _mesa_get_format_info(), gl_format_info::BlockDepth, gl_format_info::BlockHeight, and gl_format_info::BlockWidth.
Referenced by _mesa_compute_compressed_pixelstore(), dimensions_error_check(), and error_check_subtexture_dimensions().
_mesa_get_format_bytes()
GLint _mesa_get_format_bytes (mesa_format format)
Return bytes needed to store a block of pixels in the given format.
Normally, a block is 1x1 (a single pixel). But for compressed formats a block may be 4x4 or 8x4, etc.
Note: not GLuint, so as not to coerce math to unsigned. cf. fdo #37351
References _mesa_get_format_info(), _mesa_is_format_compressed(), gl_format_info::BytesPerBlock, and MAX_PIXEL_BYTES.
Referenced by _mesa_clear_buffer_sub_data(), _mesa_compressed_image_address(), _mesa_decompress_image(), _mesa_format_to_array(), _mesa_GetInternalformativ(), _mesa_is_image_unit_valid(), _mesa_memcpy_texture(), _mesa_store_cleartexsubimage(), _mesa_texstore_ycbcr(), _mesa_texstore_z16(), _mesa_texstore_z32(), get_tex_level_parameter_buffer(), get_tex_memcpy(), and readpixels_memcpy().
_mesa_get_format_color_encoding()
GLenum _mesa_get_format_color_encoding (mesa_format format)
Return color encoding for given format.
Returns
GL_LINEAR or GL_SRGB
References _mesa_get_format_info(), and gl_format_info::IsSRGBFormat.
Referenced by _mesa_get_framebuffer_attachment_parameter(), _mesa_is_compressed_format(), _mesa_update_framebuffer_visual(), and copytexture_error_check().
_mesa_get_format_datatype()
GLenum _mesa_get_format_datatype (mesa_format format)
Return the data type (or more specifically, the data representation) for the given format.
The return value will be one of: GL_UNSIGNED_NORMALIZED = unsigned int representing [0,1] GL_SIGNED_NORMALIZED = signed int representing [-1, 1] GL_UNSIGNED_INT = an ordinary unsigned integer GL_INT = an ordinary signed integer GL_FLOAT = an ordinary float
References _mesa_get_format_info(), and gl_format_info::DataType.
Referenced by _mesa_blit_framebuffer(), _mesa_format_convert(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_framebuffer_attachment_parameter(), _mesa_get_readpixels_transfer_ops(), _mesa_GetInternalformativ(), _mesa_test_framebuffer_completeness(), _mesa_test_texobj_completeness(), _mesa_texstore_needs_transfer_ops(), _mesa_update_framebuffer_visual(), _mesa_validate_texbuffer_format(), compatible_color_datatypes(), fast_read_depth_stencil_pixels_separate(), generate_mipmap_compressed(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), get_tex_rgba(), read_pixels_es3_error_check(), and read_uint_depth_pixels().
_mesa_get_format_info()
static const struct gl_format_info* _mesa_get_format_info (mesa_format format) static
References MESA_FORMAT_COUNT, and gl_format_info::Name.
Referenced by _mesa_format_has_color_component(), _mesa_format_image_size(), _mesa_format_image_size64(), _mesa_format_num_components(), _mesa_format_row_stride(), _mesa_format_to_array_format(), _mesa_get_format_base_format(), _mesa_get_format_bits(), _mesa_get_format_block_size(), _mesa_get_format_block_size_3d(), _mesa_get_format_bytes(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_get_format_layout(), _mesa_get_format_max_bits(), _mesa_get_format_name(), _mesa_get_format_swizzle(), _mesa_is_format_color_format(), _mesa_is_format_compressed(), _mesa_is_format_integer(), _mesa_is_format_integer_color(), _mesa_is_format_packed_depth_stencil(), _mesa_is_format_signed(), _mesa_is_format_unsigned(), and format_array_format_table_init().
_mesa_get_format_layout()
enum mesa_format_layout _mesa_get_format_layout (mesa_format format)
Return the layout type of the given format.
References _mesa_get_format_info(), and gl_format_info::Layout.
Referenced by _mesa_format_to_array(), _mesa_get_compressed_fetch_func(), _mesa_is_compressed_format(), and _mesa_target_can_be_compressed().
_mesa_get_format_max_bits()
GLuint _mesa_get_format_max_bits (mesa_format format)
References _mesa_get_format_info(), gl_format_info::AlphaBits, gl_format_info::BlueBits, gl_format_info::DepthBits, GLuint, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, gl_format_info::RedBits, and gl_format_info::StencilBits.
Referenced by _mesa_format_convert(), and _mesa_format_to_array().
_mesa_get_format_name()
const char* _mesa_get_format_name (mesa_format format)
Return string name of format (for debugging)
References _mesa_get_format_info(), and gl_format_info::StrName.
Referenced by _mesa_format_row_stride(), _mesa_print_framebuffer(), dump_texture(), get_compressed_texture_image(), and get_texture_image().
_mesa_get_format_swizzle()
void _mesa_get_format_swizzle (mesa_format format, uint8_t swizzle_out[4])
Returns the an array of four numbers representing the transformation from the RGBA or SZ colorspace to the given format.
For array formats, the i'th RGBA component is given by:
if (swizzle[i] <= MESA_FORMAT_SWIZZLE_W) comp = data[swizzle[i]]; else if (swizzle[i] == MESA_FORMAT_SWIZZLE_ZERO) comp = 0; else if (swizzle[i] == MESA_FORMAT_SWIZZLE_ONE) comp = 1; else if (swizzle[i] == MESA_FORMAT_SWIZZLE_NONE) // data does not contain a channel of this format
For packed formats, the swizzle gives the number of components left of the least significant bit.
Compressed formats have no swizzle.
References _mesa_get_format_info(), and gl_format_info::Swizzle.
Referenced by _mesa_format_to_array().
_mesa_get_srgb_format_linear()
mesa_format _mesa_get_srgb_format_linear (mesa_format format)
For an sRGB format, return the corresponding linear color space format.
For non-sRGB formats, return the format as-is.
References MESA_FORMAT_A8B8G8R8_SRGB, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_SRGB, MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_A8R8G8B8_SRGB, MESA_FORMAT_A8R8G8B8_UNORM, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_SRGB, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_BGR_SRGB8, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_BPTC_RGBA_UNORM, MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_L8A8_SRGB, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_SRGB8, MESA_FORMAT_L_UNORM8, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA_ASTC_10x10, MESA_FORMAT_RGBA_ASTC_10x5, MESA_FORMAT_RGBA_ASTC_10x6, MESA_FORMAT_RGBA_ASTC_10x8, MESA_FORMAT_RGBA_ASTC_12x10, MESA_FORMAT_RGBA_ASTC_12x12, MESA_FORMAT_RGBA_ASTC_4x4, MESA_FORMAT_RGBA_ASTC_5x4, MESA_FORMAT_RGBA_ASTC_5x5, MESA_FORMAT_RGBA_ASTC_6x5, MESA_FORMAT_RGBA_ASTC_6x6, MESA_FORMAT_RGBA_ASTC_8x5, MESA_FORMAT_RGBA_ASTC_8x6, MESA_FORMAT_RGBA_ASTC_8x8, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x8, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x12, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8B8G8R8_SRGB, MESA_FORMAT_X8B8G8R8_UNORM, MESA_FORMAT_X8R8G8B8_SRGB, and MESA_FORMAT_X8R8G8B8_UNORM.
Referenced by _mesa_get_render_format(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), read_rgba_pixels(), and texstore_rgba().
_mesa_get_uncompressed_format()
mesa_format _mesa_get_uncompressed_format (mesa_format format)
If the given format is a compressed format, return a corresponding uncompressed format.
References _mesa_is_format_compressed(), GLuint, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, MESA_FORMAT_BPTC_RGBA_UNORM, MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_L8A8_SNORM, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_L_SNORM8, MESA_FORMAT_L_UNORM8, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R8G8_SNORM, MESA_FORMAT_R8G8_UNORM, MESA_FORMAT_R_RGTC1_SNORM, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_RGTC2_SNORM, MESA_FORMAT_RG_RGTC2_UNORM, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, and MESA_FORMAT_SRGBA_DXT5.
Referenced by generate_mipmap_compressed().
_mesa_is_format_color_format()
GLenum _mesa_is_format_color_format (mesa_format format)
Return true if the given format is a color format.
References _mesa_get_format_info(), and gl_format_info::BaseFormat.
Referenced by _mesa_format_convert().
_mesa_is_format_compressed()
GLboolean _mesa_is_format_compressed (mesa_format format)
Is the given format a compressed format?
References _mesa_get_format_info(), gl_format_info::BlockHeight, and gl_format_info::BlockWidth.
Referenced by _mesa_format_matches_format_and_type(), _mesa_format_row_stride(), _mesa_format_to_array(), _mesa_generate_mipmap(), _mesa_get_format_bytes(), _mesa_get_uncompressed_format(), _mesa_texstore(), copytexsubimage_error_check(), get_tex_level_parameter_image(), get_tex_rgba(), getcompressedteximage_error_check(), test_attachment_completeness(), and texsubimage_error_check().
_mesa_is_format_etc2()
bool _mesa_is_format_etc2 (mesa_format format)
Return TRUE if format is an ETC2 compressed format specified by GL_ARB_ES3_compatibility.
References MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, and MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1.
_mesa_is_format_integer()
GLboolean _mesa_is_format_integer (mesa_format format)
Is the given format an integer format?
References _mesa_get_format_info(), and gl_format_info::DataType.
Referenced by _mesa_format_to_array(), and getteximage_error_check().
_mesa_is_format_integer_color()
GLboolean _mesa_is_format_integer_color (mesa_format format)
Is the given format a signed/unsigned integer color format?
References _mesa_get_format_info(), gl_format_info::BaseFormat, and gl_format_info::DataType.
Referenced by _mesa_format_convert(), _mesa_ReadnPixelsARB(), _mesa_test_framebuffer_completeness(), check_clear_tex_image(), copytexsubimage_error_check(), texsubimage_error_check(), and validate_clear_buffer_format().
_mesa_is_format_packed_depth_stencil()
GLboolean _mesa_is_format_packed_depth_stencil (mesa_format format)
Determine if the given format represents a packed depth/stencil buffer.
References _mesa_get_format_info(), and gl_format_info::BaseFormat.
_mesa_is_format_signed()
GLboolean _mesa_is_format_signed (mesa_format format)
Does the given format store signed values?
References _mesa_get_format_info(), gl_format_info::DataType, MESA_FORMAT_R11G11B10_FLOAT, and MESA_FORMAT_R9G9B9E5_FLOAT.
Referenced by find_custom_value().
_mesa_is_format_unsigned()
GLboolean _mesa_is_format_unsigned (mesa_format format)
Is the given format an unsigned integer format?
References _mesa_get_format_info(), _mesa_is_type_unsigned(), and gl_format_info::DataType.
Referenced by _mesa_format_convert(), and read_rgba_pixels().
array_formats_equal()
static bool array_formats_equal (const void * a, const void * b) static
Referenced by format_array_format_table_init().
format_array_format_table_init()
static void format_array_format_table_init (void) static
References _mesa_array_format_flip_channels(), _mesa_error_no_memory(), _mesa_get_format_info(), _mesa_little_endian(), array_formats_equal(), gl_format_info::ArrayFormat, format_array_format_table, and MESA_FORMAT_COUNT.
Referenced by _mesa_format_from_array_format().
get_base_format_for_array_format()
static GLenum get_base_format_for_array_format (mesa_array_format format) static
References _mesa_array_format_get_num_channels(), _mesa_array_format_get_swizzle(), MESA_FORMAT_SWIZZLE_W, and swizzle().
Referenced by _mesa_get_format_base_format().
Variable Documentation
format_array_format_table
struct hash_table* format_array_format_table static
Referenced by _mesa_format_from_array_format(), and format_array_format_table_init().
format_array_format_table_exists
once_flag format_array_format_table_exists = ONCE_FLAG_INIT static
Referenced by _mesa_format_from_array_format().