Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
framebuffer.h File Reference
#include "mtypes.h"
Functions
struct gl_framebuffer * _mesa_create_framebuffer (const struct gl_config *visual)
Create and initialize a gl_framebuffer object.
struct gl_framebuffer * _mesa_new_framebuffer (struct gl_context *ctx, GLuint name)
Allocate a new gl_framebuffer object.
void _mesa_initialize_window_framebuffer (struct gl_framebuffer *fb, const struct gl_config *visual)
Initialize a gl_framebuffer object.
void _mesa_initialize_user_framebuffer (struct gl_framebuffer *fb, GLuint name)
Initialize a user-created gl_framebuffer object.
void _mesa_destroy_framebuffer (struct gl_framebuffer *buffer)
Deallocate buffer and everything attached to it.
void _mesa_free_framebuffer_data (struct gl_framebuffer *buffer)
Free all the data hanging off the given gl_framebuffer, but don't free the gl_framebuffer object itself.
void _mesa_reference_framebuffer_ (struct gl_framebuffer **ptr, struct gl_framebuffer *fb)
Set *ptr to point to fb, with refcounting and locking.
static void _mesa_reference_framebuffer (struct gl_framebuffer **ptr, struct gl_framebuffer *fb)
void _mesa_resize_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint width, GLuint height)
Resize the given framebuffer's renderbuffers to the new width and height.
void _mesa_resizebuffers (struct gl_context *ctx)
void _mesa_scissor_bounding_box (const struct gl_context *ctx, const struct gl_framebuffer *buffer, unsigned idx, int *bbox)
Calculate the inclusive bounding box for the scissor of a specific viewport.
void _mesa_intersect_scissor_bounding_box (const struct gl_context *ctx, unsigned idx, int *bbox)
Given a bounding box, intersect the bounding box with the scissor of a specified vieport.
static GLuint _mesa_geometric_width (const struct gl_framebuffer *buffer)
static GLuint _mesa_geometric_height (const struct gl_framebuffer *buffer)
static GLuint _mesa_geometric_samples (const struct gl_framebuffer *buffer)
static GLuint _mesa_geometric_layers (const struct gl_framebuffer *buffer)
void _mesa_update_draw_buffer_bounds (struct gl_context *ctx, struct gl_framebuffer *drawFb)
Update the context's current drawing buffer's Xmin, Xmax, Ymin, Ymax fields.
void _mesa_update_framebuffer_visual (struct gl_context *ctx, struct gl_framebuffer *fb)
The glGet queries of the framebuffer red/green/blue size, stencil size, etc.
void _mesa_update_framebuffer (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb)
Update state related to the draw/read framebuffers.
GLboolean _mesa_source_buffer_exists (struct gl_context *ctx, GLenum format)
Check if the renderbuffer for a read operation (glReadPixels, glCopyPixels, glCopyTex[Sub]Image, etc) exists.
GLboolean _mesa_dest_buffer_exists (struct gl_context *ctx, GLenum format)
As above, but for drawing operations.
GLenum _mesa_get_color_read_type (struct gl_context *ctx, struct gl_framebuffer *fb, const char *caller)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_TYPE_OES queries (using GetIntegerv, GetFramebufferParameteriv, etc)
GLenum _mesa_get_color_read_format (struct gl_context *ctx, struct gl_framebuffer *fb, const char *caller)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES queries (using GetIntegerv, GetFramebufferParameteriv, etc)
struct gl_renderbuffer * _mesa_get_read_renderbuffer_for_format (const struct gl_context *ctx, GLenum format)
Returns the read renderbuffer for the specified format.
void _mesa_print_framebuffer (const struct gl_framebuffer *fb)
Print framebuffer info to stderr, for debugging.
bool _mesa_is_front_buffer_reading (const struct gl_framebuffer *fb)
bool _mesa_is_front_buffer_drawing (const struct gl_framebuffer *fb)
bool _mesa_is_multisample_enabled (const struct gl_context *ctx)
bool _mesa_is_alpha_test_enabled (const struct gl_context *ctx)
Is alpha testing enabled and applicable to the currently bound framebuffer?
bool _mesa_is_alpha_to_coverage_enabled (const struct gl_context *ctx)
Is alpha to coverage enabled and applicable to the currently bound framebuffer?
Function Documentation
_mesa_create_framebuffer()
struct gl_framebuffer* _mesa_create_framebuffer (const struct gl_config * visual)
Create and initialize a gl_framebuffer object.
This is intended for creating window_system framebuffers, not generic framebuffer objects ala GL_EXT_framebuffer_object.
See also
_mesa_new_framebuffer
References _mesa_initialize_window_framebuffer(), and CALLOC_STRUCT.
_mesa_dest_buffer_exists()
GLboolean _mesa_dest_buffer_exists (struct gl_context * ctx, GLenum format)
As above, but for drawing operations.
References gl_context::DrawBuffer, and renderbuffer_exists().
Referenced by _mesa_CopyPixels(), _mesa_DrawPixels(), and _mesa_geometric_layers().
_mesa_destroy_framebuffer()
void _mesa_destroy_framebuffer (struct gl_framebuffer * fb)
Deallocate buffer and everything attached to it.
Typically called via the gl_framebuffer->Delete() method.
References _mesa_free_framebuffer_data(), and gl_framebuffer::Label.
Referenced by _mesa_initialize_user_framebuffer(), and _mesa_initialize_window_framebuffer().
_mesa_free_framebuffer_data()
void _mesa_free_framebuffer_data (struct gl_framebuffer * buffer)
Free all the data hanging off the given gl_framebuffer, but don't free the gl_framebuffer object itself.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), gl_framebuffer::Attachment, BUFFER_COUNT, GLuint, gl_framebuffer::Mutex, gl_framebuffer::RefCount, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_destroy_framebuffer().
_mesa_geometric_height()
static GLuint _mesa_geometric_height (const struct gl_framebuffer * buffer) inline static
References gl_framebuffer::_HasAttachments, gl_framebuffer::DefaultGeometry, GLuint, and gl_framebuffer::Height.
_mesa_geometric_layers()
static GLuint _mesa_geometric_layers (const struct gl_framebuffer * buffer) inline static
References gl_framebuffer::_HasAttachments, _mesa_dest_buffer_exists(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_read_renderbuffer_for_format(), _mesa_is_alpha_test_enabled(), _mesa_is_alpha_to_coverage_enabled(), _mesa_is_front_buffer_drawing(), _mesa_is_front_buffer_reading(), _mesa_is_multisample_enabled(), _mesa_print_framebuffer(), _mesa_source_buffer_exists(), _mesa_update_draw_buffer_bounds(), _mesa_update_framebuffer(), _mesa_update_framebuffer_visual(), gl_framebuffer::DefaultGeometry, gl_framebuffer::Layers, and gl_framebuffer::MaxNumLayers.
_mesa_geometric_samples()
static GLuint _mesa_geometric_samples (const struct gl_framebuffer * buffer) inline static
References gl_framebuffer::_HasAttachments, gl_framebuffer::_NumSamples, gl_framebuffer::DefaultGeometry, GLuint, gl_config::samples, and gl_framebuffer::Visual.
Referenced by find_custom_value(), and get_framebuffer_parameteriv().
_mesa_geometric_width()
static GLuint _mesa_geometric_width (const struct gl_framebuffer * buffer) inline static
References gl_framebuffer::_HasAttachments, gl_framebuffer::DefaultGeometry, GLuint, and gl_framebuffer::Width.
_mesa_get_color_read_format()
GLenum _mesa_get_color_read_format (struct gl_context * ctx, struct gl_framebuffer * fb, const char * caller)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES queries (using GetIntegerv, GetFramebufferParameteriv, etc)
If is NULL, the method returns the value for the current bound framebuffer.
References gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_format_datatype(), _mesa_update_state(), gl_renderbuffer::Format, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_R_UNORM8, gl_context::NewState, and gl_context::ReadBuffer.
Referenced by _mesa_geometric_layers(), _mesa_ReadnPixelsARB(), find_custom_value(), and get_framebuffer_parameteriv().
_mesa_get_color_read_type()
GLenum _mesa_get_color_read_type (struct gl_context * ctx, struct gl_framebuffer * fb, const char * caller)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_TYPE_OES queries (using GetIntegerv, GetFramebufferParameteriv, etc)
If is NULL, the method returns the value for the current bound framebuffer.
References gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_format_datatype(), _mesa_update_state(), gl_renderbuffer::Format, MESA_FORMAT_B5G6R5_UNORM, gl_context::NewState, and gl_context::ReadBuffer.
Referenced by _mesa_geometric_layers(), _mesa_ReadnPixelsARB(), find_custom_value(), and get_framebuffer_parameteriv().
_mesa_get_read_renderbuffer_for_format()
struct gl_renderbuffer* _mesa_get_read_renderbuffer_for_format (const struct gl_context * ctx, GLenum format)
Returns the read renderbuffer for the specified format.
References gl_framebuffer::_ColorReadBufferIndex, _mesa_is_color_format(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::ReadBuffer, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_geometric_layers(), _mesa_ReadnPixelsARB(), _mesa_readpixels_needs_slow_path(), copyteximage(), copytexture_error_check(), readpixels_can_use_memcpy(), and readpixels_memcpy().
_mesa_initialize_user_framebuffer()
void _mesa_initialize_user_framebuffer (struct gl_framebuffer * fb, GLuint name)
Initialize a user-created gl_framebuffer object.
See also
_mesa_initialize_window_framebuffer
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorReadBufferIndex, _mesa_destroy_framebuffer(), gl_framebuffer::_NumColorDrawBuffers, BUFFER_COLOR0, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, gl_framebuffer::Delete, gl_framebuffer::Mutex, gl_framebuffer::Name, and gl_framebuffer::RefCount.
Referenced by _mesa_new_framebuffer().
_mesa_initialize_window_framebuffer()
void _mesa_initialize_window_framebuffer (struct gl_framebuffer * fb, const struct gl_config * visual)
Initialize a gl_framebuffer object.
Typically used to initialize window system-created framebuffers, not user-created framebuffers.
See also
_mesa_initialize_user_framebuffer
References gl_framebuffer::_AllColorBuffersFixedPoint, gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorReadBufferIndex, gl_framebuffer::_HasAttachments, gl_framebuffer::_HasSNormOrFloatColorBuffer, _mesa_destroy_framebuffer(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Status, BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, compute_depth_max(), gl_framebuffer::Delete, gl_config::doubleBufferMode, gl_config::floatMode, gl_framebuffer::Mutex, gl_framebuffer::RefCount, and gl_framebuffer::Visual.
Referenced by _mesa_create_framebuffer().
_mesa_intersect_scissor_bounding_box()
void _mesa_intersect_scissor_bounding_box (const struct gl_context * ctx, unsigned idx, int * bbox)
Given a bounding box, intersect the bounding box with the scissor of a specified vieport.
Parameters
ctx GL context.
idx Index of the desired viewport
bbox Bounding box for the scissored viewport. Stored as xmin, xmax, ymin, ymax.
References gl_scissor_attrib::EnableFlags, gl_scissor_rect::Height, gl_context::Scissor, gl_scissor_attrib::ScissorArray, gl_scissor_rect::Width, gl_scissor_rect::X, and gl_scissor_rect::Y.
Referenced by _mesa_reference_framebuffer(), and _mesa_scissor_bounding_box().
_mesa_is_alpha_test_enabled()
bool _mesa_is_alpha_test_enabled (const struct gl_context * ctx)
Is alpha testing enabled and applicable to the currently bound framebuffer?
References gl_framebuffer::_IntegerBuffers, gl_colorbuffer_attrib::AlphaEnabled, gl_context::Color, and gl_context::DrawBuffer.
Referenced by _mesa_geometric_layers().
_mesa_is_alpha_to_coverage_enabled()
bool _mesa_is_alpha_to_coverage_enabled (const struct gl_context * ctx)
Is alpha to coverage enabled and applicable to the currently bound framebuffer?
References gl_framebuffer::_IntegerBuffers, _mesa_is_multisample_enabled(), gl_context::DrawBuffer, gl_context::Multisample, and gl_multisample_attrib::SampleAlphaToCoverage.
Referenced by _mesa_geometric_layers().
_mesa_is_front_buffer_drawing()
bool _mesa_is_front_buffer_drawing (const struct gl_framebuffer * fb)
References gl_framebuffer::_ColorDrawBufferIndexes, _mesa_is_user_fbo(), gl_framebuffer::_NumColorDrawBuffers, BUFFER_FRONT_LEFT, and GLuint.
Referenced by _mesa_geometric_layers().
_mesa_is_front_buffer_reading()
bool _mesa_is_front_buffer_reading (const struct gl_framebuffer * fb)
References gl_framebuffer::_ColorReadBufferIndex, _mesa_is_user_fbo(), and BUFFER_FRONT_LEFT.
Referenced by _mesa_geometric_layers().
_mesa_is_multisample_enabled()
bool _mesa_is_multisample_enabled (const struct gl_context * ctx)
References _mesa_geometric_nonvalidated_samples(), gl_context::DrawBuffer, gl_multisample_attrib::Enabled, and gl_context::Multisample.
Referenced by _mesa_geometric_layers(), and _mesa_is_alpha_to_coverage_enabled().
_mesa_new_framebuffer()
struct gl_framebuffer* _mesa_new_framebuffer (struct gl_context * ctx, GLuint name)
Allocate a new gl_framebuffer object.
This is the default function for ctx->Driver.NewFramebuffer(). This is for allocating user-created framebuffers, not window-system framebuffers!
See also
_mesa_create_framebuffer
References _mesa_initialize_user_framebuffer(), CALLOC_STRUCT, and void.
_mesa_print_framebuffer()
void _mesa_print_framebuffer (const struct gl_framebuffer * fb)
Print framebuffer info to stderr, for debugging.
References _mesa_enum_to_string(), _mesa_get_format_name(), gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_texture_image::Depth, gl_renderbuffer::Format, GLuint, gl_texture_image::Height, gl_renderbuffer::Height, gl_framebuffer::Height, gl_texture_object::Name, gl_renderbuffer::Name, gl_framebuffer::Name, gl_renderbuffer_attachment::Renderbuffer, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, gl_texture_image::Width, gl_renderbuffer::Width, gl_framebuffer::Width, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_geometric_layers().
_mesa_reference_framebuffer()
static void _mesa_reference_framebuffer (struct gl_framebuffer ** ptr, struct gl_framebuffer * fb) inline static
References _mesa_intersect_scissor_bounding_box(), _mesa_reference_framebuffer_(), _mesa_resize_framebuffer(), _mesa_resizebuffers(), _mesa_scissor_bounding_box(), and GLuint.
Referenced by _mesa_bind_framebuffers(), _mesa_DeleteFramebuffers(), _mesa_free_context_data(), and _mesa_make_current().
_mesa_reference_framebuffer_()
void _mesa_reference_framebuffer_ (struct gl_framebuffer ** ptr, struct gl_framebuffer * fb)
Set *ptr to point to fb, with refcounting and locking.
This is normally only called from the _mesa_reference_framebuffer() macro when there's a real pointer change.
References gl_framebuffer::Delete, gl_framebuffer::Mutex, and gl_framebuffer::RefCount.
Referenced by _mesa_reference_framebuffer().
_mesa_resize_framebuffer()
void _mesa_resize_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint width, GLuint height)
Resize the given framebuffer's renderbuffers to the new width and height.
This should only be used for window-system framebuffers, not user-created renderbuffers (i.e. made with GL_EXT_framebuffer_object). This will typically be called directly from a device driver.
Note
it's possible for ctx to be null since a window can be resized without a currently bound rendering context.
References _mesa_error(), _mesa_is_winsys_fbo(), _mesa_update_draw_buffer_bounds(), _NEW_BUFFERS, gl_renderbuffer::AllocStorage, gl_framebuffer::Attachment, BUFFER_COUNT, gl_context::DrawBuffer, GLuint, gl_renderbuffer::Height, gl_framebuffer::Height, gl_renderbuffer::InternalFormat, gl_context::NewState, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Type, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_reference_framebuffer().
_mesa_resizebuffers()
void _mesa_resizebuffers (struct gl_context * ctx)
Referenced by _mesa_reference_framebuffer().
_mesa_scissor_bounding_box()
void _mesa_scissor_bounding_box (const struct gl_context * ctx, const struct gl_framebuffer * buffer, unsigned idx, int * bbox)
Calculate the inclusive bounding box for the scissor of a specific viewport.
Parameters
ctx GL context.
buffer Framebuffer to be checked against
idx Index of the desired viewport
bbox Bounding box for the scissored viewport. Stored as xmin, xmax, ymin, ymax.
Warning
This function assumes that the framebuffer dimensions are up to date (e.g., update_framebuffer_size has been recently called on buffer).
See also
_mesa_clip_to_region
References _mesa_intersect_scissor_bounding_box(), gl_framebuffer::Height, and gl_framebuffer::Width.
Referenced by _mesa_reference_framebuffer(), and _mesa_update_draw_buffer_bounds().
_mesa_source_buffer_exists()
GLboolean _mesa_source_buffer_exists (struct gl_context * ctx, GLenum format)
Check if the renderbuffer for a read operation (glReadPixels, glCopyPixels, glCopyTex[Sub]Image, etc) exists.
Parameters
format a basic image format such as GL_RGB, GL_RGBA, GL_ALPHA, GL_DEPTH_COMPONENT, etc. or GL_COLOR, GL_DEPTH, GL_STENCIL.
Returns
GL_TRUE if buffer exists, GL_FALSE otherwise
References gl_context::ReadBuffer, and renderbuffer_exists().
Referenced by _mesa_CopyPixels(), _mesa_geometric_layers(), _mesa_ReadnPixelsARB(), copytexsubimage_error_check(), and copytexture_error_check().
_mesa_update_draw_buffer_bounds()
void _mesa_update_draw_buffer_bounds (struct gl_context * ctx, struct gl_framebuffer * buffer)
Update the context's current drawing buffer's Xmin, Xmax, Ymin, Ymax fields.
These values are computed from the buffer's width and height and the scissor box, if it's enabled.
Parameters
ctx the GL context.
References _mesa_is_user_fbo(), _mesa_scissor_bounding_box(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, and update_framebuffer_size().
Referenced by _mesa_blit_framebuffer(), _mesa_geometric_layers(), _mesa_resize_framebuffer(), and _mesa_update_state_locked().
_mesa_update_framebuffer()
void _mesa_update_framebuffer (struct gl_context * ctx, struct gl_framebuffer * readFb, struct gl_framebuffer * drawFb)
Update state related to the draw/read framebuffers.
References _mesa_update_clamp_fragment_color(), _mesa_update_clamp_vertex_color(), and update_framebuffer().
Referenced by _mesa_blit_framebuffer(), _mesa_geometric_layers(), and _mesa_update_state_locked().
_mesa_update_framebuffer_visual()
void _mesa_update_framebuffer_visual (struct gl_context * ctx, struct gl_framebuffer * fb)
The glGet queries of the framebuffer red/green/blue size, stencil size, etc.
are satisfied by the fields of ctx->DrawBuffer->Visual. These can change depending on the renderbuffer bindings. This function updates the given framebuffer's Visual from the current renderbuffer bindings.
This may apply to user-created framebuffers or window system framebuffers.
Also note: ctx->DrawBuffer->Visual.depthBits might not equal ctx->DrawBuffer->Attachment[BUFFER_DEPTH].Renderbuffer.DepthBits. The former one is used to convert floating point depth values into integer Z values.
References _mesa_get_format_base_format(), _mesa_get_format_bits(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_is_legal_color_format(), gl_framebuffer::_Status, gl_config::accumAlphaBits, gl_config::accumBlueBits, gl_config::accumGreenBits, gl_config::accumRedBits, gl_config::alphaBits, gl_framebuffer::Attachment, gl_config::blueBits, BUFFER_ACCUM, BUFFER_COUNT, BUFFER_DEPTH, BUFFER_STENCIL, compute_depth_max(), gl_config::depthBits, gl_extensions::EXT_framebuffer_sRGB, gl_context::Extensions, gl_config::floatMode, gl_renderbuffer::Format, GLuint, gl_config::greenBits, gl_config::haveAccumBuffer, gl_config::haveDepthBuffer, gl_config::haveStencilBuffer, gl_renderbuffer::NumSamples, gl_config::redBits, gl_renderbuffer_attachment::Renderbuffer, gl_config::rgbBits, gl_config::rgbMode, gl_config::sampleBuffers, gl_config::samples, gl_config::sRGBCapable, gl_config::stencilBits, and gl_framebuffer::Visual.
Referenced by _mesa_framebuffer_renderbuffer(), _mesa_geometric_layers(), and _mesa_test_framebuffer_completeness().