Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
genmipmap.h File Reference
#include "glheader.h"
Functions
void _mesa_generate_texture_mipmap (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, bool dsa)
Implements glGenerateMipmap and glGenerateTextureMipmap.
bool _mesa_is_valid_generate_texture_mipmap_target (struct gl_context *ctx, GLenum target)
bool _mesa_is_valid_generate_texture_mipmap_internalformat (struct gl_context *ctx, GLenum internalformat)
void GLAPIENTRY _mesa_GenerateMipmap (GLenum target)
Generate all the mipmap levels below the base level.
void GLAPIENTRY _mesa_GenerateTextureMipmap (GLuint texture)
Generate all the mipmap levels below the base level.
Function Documentation
_mesa_generate_texture_mipmap()
void _mesa_generate_texture_mipmap (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, bool dsa)
Implements glGenerateMipmap and glGenerateTextureMipmap.
Generates all the mipmap levels below the base level.
References _mesa_cube_complete(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_valid_generate_texture_mipmap_internalformat(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), gl_texture_object::BaseLevel, gl_context::Driver, FLUSH_VERTICES, dd_function_table::GenerateMipmap, GLAPIENTRY, GLuint, gl_texture_image::Height, gl_texture_image::InternalFormat, gl_texture_object::MaxLevel, gl_texture_object::Target, and gl_texture_image::Width.
Referenced by _mesa_GenerateMipmap(), and _mesa_GenerateTextureMipmap().
_mesa_GenerateMipmap()
void GLAPIENTRY _mesa_GenerateMipmap (GLenum target)
Generate all the mipmap levels below the base level.
Note: this GL function would be more useful if one could specify a cube face, a set of array slices, etc.
References _mesa_enum_to_string(), _mesa_error(), _mesa_generate_texture_mipmap(), _mesa_get_current_tex_object(), _mesa_is_valid_generate_texture_mipmap_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GenerateTextureMipmap()
void GLAPIENTRY _mesa_GenerateTextureMipmap (GLuint texture)
Generate all the mipmap levels below the base level.
References _mesa_enum_to_string(), _mesa_error(), _mesa_generate_texture_mipmap(), _mesa_is_valid_generate_texture_mipmap_target(), _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, and gl_texture_object::Target.
_mesa_is_valid_generate_texture_mipmap_internalformat()
bool _mesa_is_valid_generate_texture_mipmap_internalformat (struct gl_context * ctx, GLenum internalformat)
References _mesa_is_astc_format(), _mesa_is_depthstencil_format(), _mesa_is_enum_format_integer(), _mesa_is_es3_color_renderable(), _mesa_is_es3_texture_filterable(), _mesa_is_gles3(), and _mesa_is_stencil_format().
Referenced by _mesa_generate_texture_mipmap(), and _mesa_GetInternalformativ().
_mesa_is_valid_generate_texture_mipmap_target()
bool _mesa_is_valid_generate_texture_mipmap_target (struct gl_context * ctx, GLenum target)
References _mesa_has_texture_cube_map_array(), _mesa_is_gles(), gl_context::API, API_OPENGLES, gl_extensions::ARB_texture_cube_map, gl_extensions::EXT_texture_array, gl_context::Extensions, and gl_context::Version.
Referenced by _mesa_GenerateMipmap(), _mesa_GenerateTextureMipmap(), and _mesa_GetInternalformativ().