Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
get.h File Reference
State query functions.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_GetBooleanv (GLenum pname, GLboolean *params)
void GLAPIENTRY _mesa_GetDoublev (GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetFloatv (GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetIntegerv (GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetInteger64v (GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_GetFixedv (GLenum pname, GLfixed *params)
void GLAPIENTRY _mesa_GetBooleani_v (GLenum pname, GLuint index, GLboolean *params)
void GLAPIENTRY _mesa_GetIntegeri_v (GLenum pname, GLuint index, GLint *params)
void GLAPIENTRY _mesa_GetInteger64i_v (GLenum pname, GLuint index, GLint64 *params)
void GLAPIENTRY _mesa_GetPointerv (GLenum pname, GLvoid **params)
Return pointer-valued state, such as a vertex array pointer.
void GLAPIENTRY _mesa_GetFloati_v (GLenum target, GLuint index, GLfloat *data)
void GLAPIENTRY _mesa_GetDoublei_v (GLenum target, GLuint index, GLdouble *data)
const GLubyte *GLAPIENTRY _mesa_GetString (GLenum name)
Query string-valued state.
const GLubyte *GLAPIENTRY _mesa_GetStringi (GLenum name, GLuint index)
GL3.
GLenum GLAPIENTRY _mesa_GetError (void)
Returns the current GL error code, or GL_NO_ERROR.
GLenum GLAPIENTRY _mesa_GetGraphicsResetStatusARB (void)
Returns an error code specified by GL_ARB_robustness, or GL_NO_ERROR.
Detailed Description
State query functions.
Function Documentation
_mesa_GetBooleani_v()
void GLAPIENTRY _mesa_GetBooleani_v (GLenum pname, GLuint index, GLboolean * params)
References find_value_indexed(), GLAPIENTRY, INT64_TO_BOOLEAN, INT_TO_BOOLEAN, value_desc::type, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_UINT, TYPE_UINT_4, value::value_int, value::value_int64, and value::value_int_4.
_mesa_GetBooleanv()
void GLAPIENTRY _mesa_GetBooleanv (GLenum pname, GLboolean * params)
References find_value(), FLOAT_TO_BOOLEAN, GLAPIENTRY, INT64_TO_BOOLEAN, INT_TO_BOOLEAN, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetDoublei_v()
void GLAPIENTRY _mesa_GetDoublei_v (GLenum target, GLuint index, GLdouble * data)
References BOOLEAN_TO_FLOAT, find_value_indexed(), GLAPIENTRY, GLuint, value::ints, GLmatrix::m, value::n, transpose, value_desc::type, TYPE_BOOLEAN, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, value::value_bool, value::value_double_2, value::value_float_4, value::value_int64, value::value_int_4, and value::value_int_n.
_mesa_GetDoublev()
void GLAPIENTRY _mesa_GetDoublev (GLenum pname, GLdouble * params)
References find_value(), GLuint, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetError()
GLenum GLAPIENTRY _mesa_GetError (void)
Returns the current GL error code, or GL_NO_ERROR.
Returns
current error code
Returns __struct gl_contextRec::ErrorValue.
References _mesa_debug(), _mesa_enum_to_string(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_set_context_lost_dispatch().
_mesa_GetFixedv()
void GLAPIENTRY _mesa_GetFixedv (GLenum pname, GLfixed * params)
References BOOLEAN_TO_FIXED, find_value(), FLOAT_TO_FIXED, INT_TO_FIXED, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetFloati_v()
void GLAPIENTRY _mesa_GetFloati_v (GLenum target, GLuint index, GLfloat * data)
References BOOLEAN_TO_FLOAT, find_value_indexed(), GLAPIENTRY, GLuint, value::ints, GLmatrix::m, value::n, transpose, value_desc::type, TYPE_BOOLEAN, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, value::value_bool, value::value_double_2, value::value_float_4, value::value_int64, value::value_int_4, and value::value_int_n.
_mesa_GetFloatv()
void GLAPIENTRY _mesa_GetFloatv (GLenum pname, GLfloat * params)
References BOOLEAN_TO_FLOAT, find_value(), GLAPIENTRY, GLuint, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
Referenced by _mesa_QueryMatrixxOES().
_mesa_GetGraphicsResetStatusARB()
GLenum GLAPIENTRY _mesa_GetGraphicsResetStatusARB (void)
Returns an error code specified by GL_ARB_robustness, or GL_NO_ERROR.
Returns
current context status
References _mesa_debug(), _mesa_set_context_lost_dispatch(), GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_set_context_lost_dispatch().
_mesa_GetInteger64i_v()
void GLAPIENTRY _mesa_GetInteger64i_v (GLenum pname, GLuint index, GLint64 * params)
References find_value_indexed(), GLAPIENTRY, GLuint, value_desc::type, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_UINT, TYPE_UINT_4, value::value_int, value::value_int64, and value::value_int_4.
_mesa_GetInteger64v()
void GLAPIENTRY _mesa_GetInteger64v (GLenum pname, GLint64 * params)
References find_value(), FLOAT_TO_INT, FLOAT_TO_INT64, GLAPIENTRY, GLuint, INT_TO_BOOLEAN, value::ints, IROUND64(), value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetIntegeri_v()
void GLAPIENTRY _mesa_GetIntegeri_v (GLenum pname, GLuint index, GLint * params)
References find_value_indexed(), GLAPIENTRY, INT64_TO_INT, IROUND(), value_desc::type, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_UINT, TYPE_UINT_4, value::value_double_2, value::value_float_4, value::value_int, value::value_int64, and value::value_int_4.
_mesa_GetIntegerv()
void GLAPIENTRY _mesa_GetIntegerv (GLenum pname, GLint * params)
References BOOLEAN_TO_INT, find_value(), FLOAT_TO_INT, GLAPIENTRY, INT64_TO_INT, value::ints, IROUND(), value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
Referenced by _mesa_ClearNamedFramebufferfi(), _mesa_ClearNamedFramebufferfv(), _mesa_ClearNamedFramebufferiv(), _mesa_ClearNamedFramebufferuiv(), _mesa_GetInternalformativ(), and _mesa_QueryMatrixxOES().
_mesa_GetPointerv()
void GLAPIENTRY _mesa_GetPointerv (GLenum pname, GLvoid ** params)
Return pointer-valued state, such as a vertex array pointer.
Parameters
pname names state to be queried
params returns the pointer value
See also
glGetPointerv().
Tries to get the specified pointer via dd_function_table::GetPointerv, otherwise gets the specified pointer from the current context.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_debug_state_ptr(), _mesa_is_desktop_gl(), API_OPENGL_COMPAT, API_OPENGLES, GET_CURRENT_CONTEXT, GL_POINT_SIZE_ARRAY_POINTER_OES, GLAPIENTRY, GLuint, if(), MESA_VERBOSE, and VERBOSE_API.
_mesa_GetString()
const GLubyte* GLAPIENTRY _mesa_GetString (GLenum name)
Query string-valued state.
The return value should not be freed by the caller.
Parameters
name the state variable to query.
See also
glGetString().
Tries to get the string from dd_function_table::GetString, otherwise returns the hardcoded strings.
References _mesa_error(), API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, GLAPIENTRY, and shading_language_version().
Referenced by _mesa_print_info().
_mesa_GetStringi()
const GLubyte* GLAPIENTRY _mesa_GetStringi (GLenum name, GLuint index)
GL3.
References _mesa_error(), _mesa_get_enabled_extension(), _mesa_get_extension_count(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, and GLAPIENTRY.