Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
get.c File Reference
#include "glheader.h"
#include "context.h"
#include "blend.h"
#include "debug_output.h"
#include "enable.h"
#include "enums.h"
#include "errors.h"
#include "extensions.h"
#include "get.h"
#include "macros.h"
#include "mtypes.h"
#include "state.h"
#include "texcompress.h"
#include "texstate.h"
#include "framebuffer.h"
#include "samplerobj.h"
#include "stencil.h"
#include "get_hash.h"
Data Structures
struct value_desc
union value
Macros
#define FLOAT_TO_BOOLEAN(X) ((X) ? GL_TRUE : GL_FALSE)
#define FLOAT_TO_FIXED(F)
#define INT_TO_BOOLEAN(I) ((I) ? GL_TRUE : GL_FALSE)
#define INT_TO_FIXED(I)
#define INT64_TO_BOOLEAN(I) ((I) ? GL_TRUE : GL_FALSE)
#define INT64_TO_INT(I) ((GLint)((I > INT_MAX) ? INT_MAX : ((I < INT_MIN) ? INT_MIN : (I))))
#define BOOLEAN_TO_INT(B) ((GLint) (B))
#define BOOLEAN_TO_INT64(B) ((GLint64) (B))
#define BOOLEAN_TO_FLOAT(B) ((B) ? 1.0F : 0.0F)
#define BOOLEAN_TO_FIXED(B) ((GLint) ((B) ? 1 : 0) << 16)
#define ENUM_TO_INT64(E) ((GLint64) (E))
#define ENUM_TO_FIXED(E) (E)
#define NO_EXTRA NULL
#define NO_OFFSET 0
#define BUFFER_FIELD(field, type) LOC_BUFFER, type, offsetof(struct gl_framebuffer, field)
#define CONTEXT_FIELD(field, type) LOC_CONTEXT, type, offsetof(struct gl_context, field)
#define ARRAY_FIELD(field, type) LOC_ARRAY, type, offsetof(struct gl_vertex_array_object, field)
#define CONST(value) LOC_CONTEXT, TYPE_CONST, value
#define BUFFER_INT(field) BUFFER_FIELD(field, TYPE_INT)
#define BUFFER_ENUM(field) BUFFER_FIELD(field, TYPE_ENUM)
#define BUFFER_BOOL(field) BUFFER_FIELD(field, TYPE_BOOLEAN)
#define CONTEXT_INT(field) CONTEXT_FIELD(field, TYPE_INT)
#define CONTEXT_INT2(field) CONTEXT_FIELD(field, TYPE_INT_2)
#define CONTEXT_INT64(field) CONTEXT_FIELD(field, TYPE_INT64)
#define CONTEXT_UINT(field) CONTEXT_FIELD(field, TYPE_UINT)
#define CONTEXT_ENUM(field) CONTEXT_FIELD(field, TYPE_ENUM)
#define CONTEXT_ENUM2(field) CONTEXT_FIELD(field, TYPE_ENUM_2)
#define CONTEXT_BOOL(field) CONTEXT_FIELD(field, TYPE_BOOLEAN)
#define CONTEXT_BIT0(field) CONTEXT_FIELD(field, TYPE_BIT_0)
#define CONTEXT_BIT1(field) CONTEXT_FIELD(field, TYPE_BIT_1)
#define CONTEXT_BIT2(field) CONTEXT_FIELD(field, TYPE_BIT_2)
#define CONTEXT_BIT3(field) CONTEXT_FIELD(field, TYPE_BIT_3)
#define CONTEXT_BIT4(field) CONTEXT_FIELD(field, TYPE_BIT_4)
#define CONTEXT_BIT5(field) CONTEXT_FIELD(field, TYPE_BIT_5)
#define CONTEXT_BIT6(field) CONTEXT_FIELD(field, TYPE_BIT_6)
#define CONTEXT_BIT7(field) CONTEXT_FIELD(field, TYPE_BIT_7)
#define CONTEXT_FLOAT(field) CONTEXT_FIELD(field, TYPE_FLOAT)
#define CONTEXT_FLOAT2(field) CONTEXT_FIELD(field, TYPE_FLOAT_2)
#define CONTEXT_FLOAT3(field) CONTEXT_FIELD(field, TYPE_FLOAT_3)
#define CONTEXT_FLOAT4(field) CONTEXT_FIELD(field, TYPE_FLOAT_4)
#define CONTEXT_FLOAT8(field) CONTEXT_FIELD(field, TYPE_FLOAT_8)
#define CONTEXT_MATRIX(field) CONTEXT_FIELD(field, TYPE_MATRIX)
#define CONTEXT_MATRIX_T(field) CONTEXT_FIELD(field, TYPE_MATRIX_T)
#define ARRAY_INT(field) ARRAY_FIELD(field, TYPE_INT)
#define ARRAY_ENUM(field) ARRAY_FIELD(field, TYPE_ENUM)
#define ARRAY_BOOL(field) ARRAY_FIELD(field, TYPE_BOOLEAN)
#define EXT(f) offsetof(struct gl_extensions, f)
#define EXTRA_EXT(e)
#define EXTRA_EXT2(e1, e2)
Enumerations
enum value_type {
TYPE_INVALID, TYPE_INT, TYPE_INT_2, TYPE_INT_3,
TYPE_INT_4, TYPE_INT_N, TYPE_UINT, TYPE_UINT_2,
TYPE_UINT_3, TYPE_UINT_4, TYPE_INT64, TYPE_ENUM,
TYPE_ENUM_2, TYPE_BOOLEAN, TYPE_BIT_0, TYPE_BIT_1,
TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5,
TYPE_BIT_6, TYPE_BIT_7, TYPE_FLOAT, TYPE_FLOAT_2,
TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN,
TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_DOUBLEN,
TYPE_DOUBLEN_2, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_CONST
}
enum value_location {
LOC_BUFFER, LOC_CONTEXT, LOC_ARRAY, LOC_TEXUNIT,
LOC_CUSTOM
}
enum value_extra {
EXTRA_END = 0x8000, EXTRA_VERSION_30, EXTRA_VERSION_31, EXTRA_VERSION_32,
EXTRA_VERSION_40, EXTRA_API_GL, EXTRA_API_GL_CORE, EXTRA_API_ES2,
EXTRA_API_ES3, EXTRA_API_ES31, EXTRA_API_ES32, EXTRA_NEW_BUFFERS,
EXTRA_NEW_FRAG_CLAMP, EXTRA_VALID_DRAW_BUFFER, EXTRA_VALID_TEXTURE_UNIT, EXTRA_VALID_CLIP_DISTANCE,
EXTRA_FLUSH_CURRENT, EXTRA_GLSL_130, EXTRA_EXT_UBO_GS, EXTRA_EXT_ATOMICS_GS,
EXTRA_EXT_SHADER_IMAGE_GS, EXTRA_EXT_ATOMICS_TESS, EXTRA_EXT_SHADER_IMAGE_TESS, EXTRA_EXT_SSBO_GS,
EXTRA_EXT_FB_NO_ATTACH_GS, EXTRA_EXT_ES_GS
}
Functions
EXTRA_EXT (ARB_texture_cube_map)
EXTRA_EXT (EXT_texture_array)
EXTRA_EXT (NV_fog_distance)
EXTRA_EXT (EXT_texture_filter_anisotropic)
EXTRA_EXT (NV_point_sprite)
EXTRA_EXT (NV_texture_rectangle)
EXTRA_EXT (EXT_stencil_two_side)
EXTRA_EXT (EXT_depth_bounds_test)
EXTRA_EXT (ARB_depth_clamp)
EXTRA_EXT (ATI_fragment_shader)
EXTRA_EXT (EXT_provoking_vertex)
EXTRA_EXT (ARB_fragment_shader)
EXTRA_EXT (ARB_fragment_program)
EXTRA_EXT2 (ARB_framebuffer_object, EXT_framebuffer_multisample)
EXTRA_EXT (ARB_seamless_cube_map)
EXTRA_EXT (ARB_sync)
EXTRA_EXT (ARB_vertex_shader)
EXTRA_EXT (EXT_transform_feedback)
EXTRA_EXT (ARB_transform_feedback3)
EXTRA_EXT (EXT_pixel_buffer_object)
EXTRA_EXT (ARB_vertex_program)
EXTRA_EXT2 (NV_point_sprite, ARB_point_sprite)
EXTRA_EXT2 (ARB_vertex_program, ARB_fragment_program)
EXTRA_EXT (ARB_color_buffer_float)
EXTRA_EXT (EXT_framebuffer_sRGB)
EXTRA_EXT (OES_EGL_image_external)
EXTRA_EXT (ARB_blend_func_extended)
EXTRA_EXT (ARB_uniform_buffer_object)
EXTRA_EXT (ARB_timer_query)
EXTRA_EXT2 (ARB_texture_cube_map_array, OES_texture_cube_map_array)
EXTRA_EXT (ARB_texture_buffer_range)
EXTRA_EXT (ARB_texture_multisample)
EXTRA_EXT (ARB_texture_gather)
EXTRA_EXT (ARB_shader_atomic_counters)
EXTRA_EXT (ARB_draw_indirect)
EXTRA_EXT (ARB_shader_image_load_store)
EXTRA_EXT (ARB_query_buffer_object)
EXTRA_EXT2 (ARB_transform_feedback3, ARB_gpu_shader5)
EXTRA_EXT (INTEL_performance_query)
EXTRA_EXT (ARB_explicit_uniform_location)
EXTRA_EXT (ARB_clip_control)
EXTRA_EXT (EXT_polygon_offset_clamp)
EXTRA_EXT (ARB_framebuffer_no_attachments)
EXTRA_EXT (ARB_tessellation_shader)
EXTRA_EXT (ARB_shader_subroutine)
EXTRA_EXT (ARB_shader_storage_buffer_object)
EXTRA_EXT (ARB_indirect_parameters)
EXTRA_EXT (ATI_meminfo)
EXTRA_EXT (NVX_gpu_memory_info)
EXTRA_EXT (ARB_cull_distance)
EXTRA_EXT (EXT_window_rectangles)
EXTRA_EXT (KHR_blend_equation_advanced_coherent)
EXTRA_EXT (OES_primitive_bounding_box)
EXTRA_EXT (ARB_compute_variable_group_size)
EXTRA_EXT (KHR_robustness)
EXTRA_EXT (ARB_sparse_buffer)
static void find_custom_value (struct gl_context *ctx, const struct value_desc *d, union value *v)
Handle irregular enums.
static GLboolean check_extra (struct gl_context *ctx, const char *func, const struct value_desc *d)
Check extra constraints on a struct value_desc descriptor.
static const struct value_desc * find_value (const char *func, GLenum pname, void **p, union value *v)
Find the struct value_desc corresponding to the enum 'pname'.
void GLAPIENTRY _mesa_GetBooleanv (GLenum pname, GLboolean *params)
void GLAPIENTRY _mesa_GetFloatv (GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetIntegerv (GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetInteger64v (GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_GetDoublev (GLenum pname, GLdouble *params)
static int tex_binding_to_index (const struct gl_context *ctx, GLenum binding)
Convert a GL texture binding enum such as GL_TEXTURE_BINDING_2D into the corresponding Mesa texture target index.
static enum value_type find_value_indexed (const char *func, GLenum pname, GLuint index, union value *v)
void GLAPIENTRY _mesa_GetBooleani_v (GLenum pname, GLuint index, GLboolean *params)
void GLAPIENTRY _mesa_GetIntegeri_v (GLenum pname, GLuint index, GLint *params)
void GLAPIENTRY _mesa_GetInteger64i_v (GLenum pname, GLuint index, GLint64 *params)
void GLAPIENTRY _mesa_GetFloati_v (GLenum pname, GLuint index, GLfloat *params)
void GLAPIENTRY _mesa_GetDoublei_v (GLenum pname, GLuint index, GLdouble *params)
void GLAPIENTRY _mesa_GetFixedv (GLenum pname, GLfixed *params)
Variables
static const int extra_new_buffers []
static const int extra_new_frag_clamp []
static const int extra_valid_draw_buffer []
static const int extra_valid_texture_unit []
static const int extra_valid_clip_distance []
static const int extra_flush_current_valid_texture_unit []
static const int extra_flush_current []
static const int extra_EXT_texture_integer_and_new_buffers []
static const int extra_GLSL_130_es3 []
static const int extra_texture_buffer_object []
static const int extra_ARB_transform_feedback2_api_es3 []
static const int extra_ARB_uniform_buffer_object_and_geometry_shader []
static const int extra_ARB_ES2_compatibility_api_es2 []
static const int extra_ARB_ES3_compatibility_api_es3 []
static const int extra_EXT_framebuffer_sRGB_and_new_buffers []
static const int extra_EXT_packed_float []
static const int extra_EXT_texture_array_es3 []
static const int extra_ARB_shader_atomic_counters_and_geometry_shader []
static const int extra_ARB_shader_image_load_store_and_geometry_shader []
static const int extra_ARB_shader_atomic_counters_and_tessellation []
static const int extra_ARB_shader_image_load_store_and_tessellation []
static const int extra_ARB_compute_shader_es31 []
static const int extra_ARB_shader_storage_buffer_object_es31 []
static const int extra_ARB_shader_storage_buffer_object_and_geometry_shader []
static const int extra_ARB_shader_image_load_store_shader_storage_buffer_object_es31 []
static const int extra_ARB_framebuffer_no_attachments_and_geometry_shader []
static const int extra_ARB_viewport_array_or_oes_geometry_shader []
static const int extra_ARB_viewport_array_or_oes_viewport_array []
static const int extra_ARB_gpu_shader5_or_oes_geometry_shader []
static const int extra_ARB_gpu_shader5_or_OES_sample_variables []
static const int extra_ES32 []
static const int extra_KHR_robustness_or_GL []
static const int extra_INTEL_conservative_rasterization []
static const int extra_ARB_color_buffer_float_or_glcore []
static const int extra_NV_primitive_restart []
static const int extra_version_30 [] = { EXTRA_VERSION_30, EXTRA_END }
static const int extra_version_31 [] = { EXTRA_VERSION_31, EXTRA_END }
static const int extra_version_32 [] = { EXTRA_VERSION_32, EXTRA_END }
static const int extra_gl30_es3 []
static const int extra_gl32_es3 []
static const int extra_version_32_OES_geometry_shader []
static const int extra_gl40_ARB_sample_shading []
static const int extra_ARB_vertex_program_api_es2 []
static const int extra_NV_read_buffer_api_gl []
static const int extra_core_ARB_color_buffer_float_and_new_buffers []
static const int extra_EXT_shader_framebuffer_fetch []
static const struct value_desc error_value
static const int transpose []
Macro Definition Documentation
ARRAY_BOOL
#define ARRAY_BOOL (field) ARRAY_FIELD(field, TYPE_BOOLEAN)
ARRAY_ENUM
#define ARRAY_ENUM (field) ARRAY_FIELD(field, TYPE_ENUM)
ARRAY_FIELD
#define ARRAY_FIELD (field, type) LOC_ARRAY, type, offsetof(struct gl_vertex_array_object, field)
ARRAY_INT
#define ARRAY_INT (field) ARRAY_FIELD(field, TYPE_INT)
BOOLEAN_TO_FIXED
#define BOOLEAN_TO_FIXED (B) ((GLint) ((B) ? 1 : 0) << 16)
Referenced by _mesa_GetFixedv().
BOOLEAN_TO_FLOAT
#define BOOLEAN_TO_FLOAT (B) ((B) ? 1.0F : 0.0F)
Referenced by _mesa_GetDoublei_v(), _mesa_GetFloati_v(), and _mesa_GetFloatv().
BOOLEAN_TO_INT
#define BOOLEAN_TO_INT (B) ((GLint) (B))
Referenced by _mesa_GetIntegerv().
BOOLEAN_TO_INT64
#define BOOLEAN_TO_INT64 (B) ((GLint64) (B))
BUFFER_BOOL
#define BUFFER_BOOL (field) BUFFER_FIELD(field, TYPE_BOOLEAN)
BUFFER_ENUM
#define BUFFER_ENUM (field) BUFFER_FIELD(field, TYPE_ENUM)
BUFFER_FIELD
#define BUFFER_FIELD (field, type) LOC_BUFFER, type, offsetof(struct gl_framebuffer, field)
BUFFER_INT
#define BUFFER_INT (field) BUFFER_FIELD(field, TYPE_INT)
CONST
#define CONST (value) LOC_CONTEXT, TYPE_CONST, value
CONTEXT_BIT0
#define CONTEXT_BIT0 (field) CONTEXT_FIELD(field, TYPE_BIT_0)
CONTEXT_BIT1
#define CONTEXT_BIT1 (field) CONTEXT_FIELD(field, TYPE_BIT_1)
CONTEXT_BIT2
#define CONTEXT_BIT2 (field) CONTEXT_FIELD(field, TYPE_BIT_2)
CONTEXT_BIT3
#define CONTEXT_BIT3 (field) CONTEXT_FIELD(field, TYPE_BIT_3)
CONTEXT_BIT4
#define CONTEXT_BIT4 (field) CONTEXT_FIELD(field, TYPE_BIT_4)
CONTEXT_BIT5
#define CONTEXT_BIT5 (field) CONTEXT_FIELD(field, TYPE_BIT_5)
CONTEXT_BIT6
#define CONTEXT_BIT6 (field) CONTEXT_FIELD(field, TYPE_BIT_6)
CONTEXT_BIT7
#define CONTEXT_BIT7 (field) CONTEXT_FIELD(field, TYPE_BIT_7)
CONTEXT_BOOL
#define CONTEXT_BOOL (field) CONTEXT_FIELD(field, TYPE_BOOLEAN)
CONTEXT_ENUM
#define CONTEXT_ENUM (field) CONTEXT_FIELD(field, TYPE_ENUM)
CONTEXT_ENUM2
#define CONTEXT_ENUM2 (field) CONTEXT_FIELD(field, TYPE_ENUM_2)
CONTEXT_FIELD
#define CONTEXT_FIELD (field, type) LOC_CONTEXT, type, offsetof(struct gl_context, field)
CONTEXT_FLOAT
#define CONTEXT_FLOAT (field) CONTEXT_FIELD(field, TYPE_FLOAT)
CONTEXT_FLOAT2
#define CONTEXT_FLOAT2 (field) CONTEXT_FIELD(field, TYPE_FLOAT_2)
CONTEXT_FLOAT3
#define CONTEXT_FLOAT3 (field) CONTEXT_FIELD(field, TYPE_FLOAT_3)
CONTEXT_FLOAT4
#define CONTEXT_FLOAT4 (field) CONTEXT_FIELD(field, TYPE_FLOAT_4)
CONTEXT_FLOAT8
#define CONTEXT_FLOAT8 (field) CONTEXT_FIELD(field, TYPE_FLOAT_8)
CONTEXT_INT
#define CONTEXT_INT (field) CONTEXT_FIELD(field, TYPE_INT)
CONTEXT_INT2
#define CONTEXT_INT2 (field) CONTEXT_FIELD(field, TYPE_INT_2)
CONTEXT_INT64
#define CONTEXT_INT64 (field) CONTEXT_FIELD(field, TYPE_INT64)
CONTEXT_MATRIX
#define CONTEXT_MATRIX (field) CONTEXT_FIELD(field, TYPE_MATRIX)
CONTEXT_MATRIX_T
#define CONTEXT_MATRIX_T (field) CONTEXT_FIELD(field, TYPE_MATRIX_T)
CONTEXT_UINT
#define CONTEXT_UINT (field) CONTEXT_FIELD(field, TYPE_UINT)
ENUM_TO_FIXED
#define ENUM_TO_FIXED (E) (E)
ENUM_TO_INT64
#define ENUM_TO_INT64 (E) ((GLint64) (E))
EXT
#define EXT (f) offsetof(struct gl_extensions, f)
EXTRA_EXT
#define EXTRA_EXT (e)
Value:
static const int extra_##e[] = {                \
      EXT(e), EXTRA_END                         \
   }
EXTRA_EXT2
#define EXTRA_EXT2 (e1, e2)
Value:
static const int extra_##e1##_##e2[] = {        \
      EXT(e1), EXT(e2), EXTRA_END               \
   }
FLOAT_TO_BOOLEAN
#define FLOAT_TO_BOOLEAN (X) ((X) ? GL_TRUE : GL_FALSE)
Referenced by _mesa_GetBooleanv().
FLOAT_TO_FIXED
#define FLOAT_TO_FIXED (F)
Value:
(((F) * 65536.0f > INT_MAX) ? INT_MAX : \
                                ((F) * 65536.0f < INT_MIN) ? INT_MIN : \
                                (GLint) ((F) * 65536.0f) )
Referenced by _mesa_GetFixedv().
INT64_TO_BOOLEAN
#define INT64_TO_BOOLEAN (I) ((I) ? GL_TRUE : GL_FALSE)
Referenced by _mesa_GetBooleani_v(), and _mesa_GetBooleanv().
INT64_TO_INT
#define INT64_TO_INT (I) ((GLint)((I > INT_MAX) ? INT_MAX : ((I < INT_MIN) ? INT_MIN : (I))))
Referenced by _mesa_GetIntegeri_v(), and _mesa_GetIntegerv().
INT_TO_BOOLEAN
#define INT_TO_BOOLEAN (I) ((I) ? GL_TRUE : GL_FALSE)
Referenced by _mesa_GetBooleani_v(), _mesa_GetBooleanv(), and _mesa_GetInteger64v().
INT_TO_FIXED
#define INT_TO_FIXED (I)
Value:
(((I) > SHRT_MAX) ? INT_MAX : \
                                ((I) < SHRT_MIN) ? INT_MIN : \
                                (GLint) ((I) * 65536) )
Referenced by _mesa_GetFixedv().
NO_EXTRA
#define NO_EXTRA NULL
NO_OFFSET
#define NO_OFFSET 0
Enumeration Type Documentation
value_extra
enum value_extra
Enumerator
EXTRA_END
EXTRA_VERSION_30
EXTRA_VERSION_31
EXTRA_VERSION_32
EXTRA_VERSION_40
EXTRA_API_GL
EXTRA_API_GL_CORE
EXTRA_API_ES2
EXTRA_API_ES3
EXTRA_API_ES31
EXTRA_API_ES32
EXTRA_NEW_BUFFERS
EXTRA_NEW_FRAG_CLAMP
EXTRA_VALID_DRAW_BUFFER
EXTRA_VALID_TEXTURE_UNIT
EXTRA_VALID_CLIP_DISTANCE
EXTRA_FLUSH_CURRENT
EXTRA_GLSL_130
EXTRA_EXT_UBO_GS
EXTRA_EXT_ATOMICS_GS
EXTRA_EXT_SHADER_IMAGE_GS
EXTRA_EXT_ATOMICS_TESS
EXTRA_EXT_SHADER_IMAGE_TESS
EXTRA_EXT_SSBO_GS
EXTRA_EXT_FB_NO_ATTACH_GS
EXTRA_EXT_ES_GS
value_location
enum value_location
Enumerator
LOC_BUFFER
LOC_CONTEXT
LOC_ARRAY
LOC_TEXUNIT
LOC_CUSTOM
value_type
enum value_type
Enumerator
TYPE_INVALID
TYPE_INT
TYPE_INT_2
TYPE_INT_3
TYPE_INT_4
TYPE_INT_N
TYPE_UINT
TYPE_UINT_2
TYPE_UINT_3
TYPE_UINT_4
TYPE_INT64
TYPE_ENUM
TYPE_ENUM_2
TYPE_BOOLEAN
TYPE_BIT_0
TYPE_BIT_1
TYPE_BIT_2
TYPE_BIT_3
TYPE_BIT_4
TYPE_BIT_5
TYPE_BIT_6
TYPE_BIT_7
TYPE_FLOAT
TYPE_FLOAT_2
TYPE_FLOAT_3
TYPE_FLOAT_4
TYPE_FLOAT_8
TYPE_FLOATN
TYPE_FLOATN_2
TYPE_FLOATN_3
TYPE_FLOATN_4
TYPE_DOUBLEN
TYPE_DOUBLEN_2
TYPE_MATRIX
TYPE_MATRIX_T
TYPE_CONST
Function Documentation
_mesa_GetBooleani_v()
void GLAPIENTRY _mesa_GetBooleani_v (GLenum pname, GLuint index, GLboolean * params)
References find_value_indexed(), GLAPIENTRY, INT64_TO_BOOLEAN, INT_TO_BOOLEAN, value_desc::type, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_UINT, TYPE_UINT_4, value::value_int, value::value_int64, and value::value_int_4.
_mesa_GetBooleanv()
void GLAPIENTRY _mesa_GetBooleanv (GLenum pname, GLboolean * params)
References find_value(), FLOAT_TO_BOOLEAN, GLAPIENTRY, INT64_TO_BOOLEAN, INT_TO_BOOLEAN, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetDoublei_v()
void GLAPIENTRY _mesa_GetDoublei_v (GLenum pname, GLuint index, GLdouble * params)
References BOOLEAN_TO_FLOAT, find_value_indexed(), GLAPIENTRY, GLuint, value::ints, GLmatrix::m, value::n, transpose, value_desc::type, TYPE_BOOLEAN, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, value::value_bool, value::value_double_2, value::value_float_4, value::value_int64, value::value_int_4, and value::value_int_n.
_mesa_GetDoublev()
void GLAPIENTRY _mesa_GetDoublev (GLenum pname, GLdouble * params)
References find_value(), GLuint, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetFixedv()
void GLAPIENTRY _mesa_GetFixedv (GLenum pname, GLfixed * params)
References BOOLEAN_TO_FIXED, find_value(), FLOAT_TO_FIXED, INT_TO_FIXED, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetFloati_v()
void GLAPIENTRY _mesa_GetFloati_v (GLenum pname, GLuint index, GLfloat * params)
References BOOLEAN_TO_FLOAT, find_value_indexed(), GLAPIENTRY, GLuint, value::ints, GLmatrix::m, value::n, transpose, value_desc::type, TYPE_BOOLEAN, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, value::value_bool, value::value_double_2, value::value_float_4, value::value_int64, value::value_int_4, and value::value_int_n.
_mesa_GetFloatv()
void GLAPIENTRY _mesa_GetFloatv (GLenum pname, GLfloat * params)
References BOOLEAN_TO_FLOAT, find_value(), GLAPIENTRY, GLuint, value::ints, value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
Referenced by _mesa_QueryMatrixxOES().
_mesa_GetInteger64i_v()
void GLAPIENTRY _mesa_GetInteger64i_v (GLenum pname, GLuint index, GLint64 * params)
References find_value_indexed(), GLAPIENTRY, GLuint, value_desc::type, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_UINT, TYPE_UINT_4, value::value_int, value::value_int64, and value::value_int_4.
_mesa_GetInteger64v()
void GLAPIENTRY _mesa_GetInteger64v (GLenum pname, GLint64 * params)
References find_value(), FLOAT_TO_INT, FLOAT_TO_INT64, GLAPIENTRY, GLuint, INT_TO_BOOLEAN, value::ints, IROUND64(), value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
_mesa_GetIntegeri_v()
void GLAPIENTRY _mesa_GetIntegeri_v (GLenum pname, GLuint index, GLint * params)
References find_value_indexed(), GLAPIENTRY, INT64_TO_INT, IROUND(), value_desc::type, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_UINT, TYPE_UINT_4, value::value_double_2, value::value_float_4, value::value_int, value::value_int64, and value::value_int_4.
_mesa_GetIntegerv()
void GLAPIENTRY _mesa_GetIntegerv (GLenum pname, GLint * params)
References BOOLEAN_TO_INT, find_value(), FLOAT_TO_INT, GLAPIENTRY, INT64_TO_INT, value::ints, IROUND(), value::n, value_desc::offset, transpose, value_desc::type, TYPE_BIT_0, TYPE_BIT_1, TYPE_BIT_2, TYPE_BIT_3, TYPE_BIT_4, TYPE_BIT_5, TYPE_BIT_6, TYPE_BIT_7, TYPE_BOOLEAN, TYPE_CONST, TYPE_DOUBLEN, TYPE_DOUBLEN_2, TYPE_ENUM, TYPE_ENUM_2, TYPE_FLOAT, TYPE_FLOAT_2, TYPE_FLOAT_3, TYPE_FLOAT_4, TYPE_FLOAT_8, TYPE_FLOATN, TYPE_FLOATN_2, TYPE_FLOATN_3, TYPE_FLOATN_4, TYPE_INT, TYPE_INT64, TYPE_INT_2, TYPE_INT_3, TYPE_INT_4, TYPE_INT_N, TYPE_INVALID, TYPE_MATRIX, TYPE_MATRIX_T, TYPE_UINT, TYPE_UINT_2, TYPE_UINT_3, TYPE_UINT_4, and value::value_int_n.
Referenced by _mesa_ClearNamedFramebufferfi(), _mesa_ClearNamedFramebufferfv(), _mesa_ClearNamedFramebufferiv(), _mesa_ClearNamedFramebufferuiv(), _mesa_GetInternalformativ(), and _mesa_QueryMatrixxOES().
check_extra()
static GLboolean check_extra (struct gl_context * ctx, const char * func, const struct value_desc * d) static
Check extra constraints on a struct value_desc descriptor.
If a struct value_desc has a non-NULL extra pointer, it means that there are a number of extra constraints to check or actions to perform. The extras is just an integer array where each integer encode different constraints or actions.
Parameters
ctx current context
func name of calling glGet*v() function for error reporting
d the struct value_desc that has the extra constraints
Returns
GL_FALSE if all of the constraints were not satisfied, otherwise GL_TRUE.
References _mesa_enum_to_string(), _mesa_error(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_gles31(), _mesa_is_gles32(), _mesa_update_state(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, gl_context::API, API_OPENGL_CORE, API_OPENGLES2, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shader_storage_buffer_object, gl_extensions::ARB_uniform_buffer_object, gl_context::Const, gl_texture_attrib::CurrentUnit, gl_context::Extensions, value_desc::extra, EXTRA_API_ES2, EXTRA_API_ES3, EXTRA_API_ES31, EXTRA_API_ES32, EXTRA_API_GL, EXTRA_API_GL_CORE, EXTRA_END, EXTRA_EXT_ATOMICS_GS, EXTRA_EXT_ATOMICS_TESS, EXTRA_EXT_ES_GS, EXTRA_EXT_FB_NO_ATTACH_GS, EXTRA_EXT_SHADER_IMAGE_GS, EXTRA_EXT_SHADER_IMAGE_TESS, EXTRA_EXT_SSBO_GS, EXTRA_EXT_UBO_GS, EXTRA_FLUSH_CURRENT, EXTRA_GLSL_130, EXTRA_NEW_BUFFERS, EXTRA_NEW_FRAG_CLAMP, EXTRA_VALID_CLIP_DISTANCE, EXTRA_VALID_DRAW_BUFFER, EXTRA_VALID_TEXTURE_UNIT, EXTRA_VERSION_30, EXTRA_VERSION_31, EXTRA_VERSION_32, FLUSH_CURRENT, gl_constants::GLSLVersion, GLuint, gl_constants::MaxClipPlanes, gl_constants::MaxDrawBuffers, gl_constants::MaxTextureCoordUnits, gl_context::NewState, value_desc::pname, gl_context::Texture, and gl_context::Version.
Referenced by find_value().
EXTRA_EXT() [1/51]
EXTRA_EXT (ARB_texture_cube_map)
EXTRA_EXT() [2/51]
EXTRA_EXT (EXT_texture_array)
EXTRA_EXT() [3/51]
EXTRA_EXT (NV_fog_distance)
EXTRA_EXT() [4/51]
EXTRA_EXT (EXT_texture_filter_anisotropic)
EXTRA_EXT() [5/51]
EXTRA_EXT (NV_point_sprite)
EXTRA_EXT() [6/51]
EXTRA_EXT (NV_texture_rectangle)
EXTRA_EXT() [7/51]
EXTRA_EXT (EXT_stencil_two_side)
EXTRA_EXT() [8/51]
EXTRA_EXT (EXT_depth_bounds_test)
EXTRA_EXT() [9/51]
EXTRA_EXT (ARB_depth_clamp)
EXTRA_EXT() [10/51]
EXTRA_EXT (ATI_fragment_shader)
EXTRA_EXT() [11/51]
EXTRA_EXT (EXT_provoking_vertex)
EXTRA_EXT() [12/51]
EXTRA_EXT (ARB_fragment_shader)
EXTRA_EXT() [13/51]
EXTRA_EXT (ARB_fragment_program)
EXTRA_EXT() [14/51]
EXTRA_EXT (ARB_seamless_cube_map)
EXTRA_EXT() [15/51]
EXTRA_EXT (ARB_sync)
EXTRA_EXT() [16/51]
EXTRA_EXT (ARB_vertex_shader)
EXTRA_EXT() [17/51]
EXTRA_EXT (EXT_transform_feedback)
EXTRA_EXT() [18/51]
EXTRA_EXT (ARB_transform_feedback3)
EXTRA_EXT() [19/51]
EXTRA_EXT (EXT_pixel_buffer_object)
EXTRA_EXT() [20/51]
EXTRA_EXT (ARB_vertex_program)
EXTRA_EXT() [21/51]
EXTRA_EXT (ARB_color_buffer_float)
EXTRA_EXT() [22/51]
EXTRA_EXT (EXT_framebuffer_sRGB)
EXTRA_EXT() [23/51]
EXTRA_EXT (OES_EGL_image_external)
EXTRA_EXT() [24/51]
EXTRA_EXT (ARB_blend_func_extended)
EXTRA_EXT() [25/51]
EXTRA_EXT (ARB_uniform_buffer_object)
EXTRA_EXT() [26/51]
EXTRA_EXT (ARB_timer_query)
EXTRA_EXT() [27/51]
EXTRA_EXT (ARB_texture_buffer_range)
EXTRA_EXT() [28/51]
EXTRA_EXT (ARB_texture_multisample)
EXTRA_EXT() [29/51]
EXTRA_EXT (ARB_texture_gather)
EXTRA_EXT() [30/51]
EXTRA_EXT (ARB_shader_atomic_counters)
EXTRA_EXT() [31/51]
EXTRA_EXT (ARB_draw_indirect)
EXTRA_EXT() [32/51]
EXTRA_EXT (ARB_shader_image_load_store)
EXTRA_EXT() [33/51]
EXTRA_EXT (ARB_query_buffer_object)
EXTRA_EXT() [34/51]
EXTRA_EXT (INTEL_performance_query)
EXTRA_EXT() [35/51]
EXTRA_EXT (ARB_explicit_uniform_location)
EXTRA_EXT() [36/51]
EXTRA_EXT (ARB_clip_control)
EXTRA_EXT() [37/51]
EXTRA_EXT (EXT_polygon_offset_clamp)
EXTRA_EXT() [38/51]
EXTRA_EXT (ARB_framebuffer_no_attachments)
EXTRA_EXT() [39/51]
EXTRA_EXT (ARB_tessellation_shader)
EXTRA_EXT() [40/51]
EXTRA_EXT (ARB_shader_subroutine)
EXTRA_EXT() [41/51]
EXTRA_EXT (ARB_shader_storage_buffer_object)
EXTRA_EXT() [42/51]
EXTRA_EXT (ARB_indirect_parameters)
EXTRA_EXT() [43/51]
EXTRA_EXT (ATI_meminfo)
EXTRA_EXT() [44/51]
EXTRA_EXT (NVX_gpu_memory_info)
EXTRA_EXT() [45/51]
EXTRA_EXT (ARB_cull_distance)
EXTRA_EXT() [46/51]
EXTRA_EXT (EXT_window_rectangles)
EXTRA_EXT() [47/51]
EXTRA_EXT (KHR_blend_equation_advanced_coherent)
EXTRA_EXT() [48/51]
EXTRA_EXT (OES_primitive_bounding_box)
EXTRA_EXT() [49/51]
EXTRA_EXT (ARB_compute_variable_group_size)
EXTRA_EXT() [50/51]
EXTRA_EXT (KHR_robustness)
EXTRA_EXT() [51/51]
EXTRA_EXT (ARB_sparse_buffer)
EXTRA_EXT2() [1/5]
EXTRA_EXT2 (ARB_framebuffer_object , EXT_framebuffer_multisample)
EXTRA_EXT2() [2/5]
EXTRA_EXT2 (NV_point_sprite , ARB_point_sprite)
EXTRA_EXT2() [3/5]
EXTRA_EXT2 (ARB_vertex_program , ARB_fragment_program)
EXTRA_EXT2() [4/5]
EXTRA_EXT2 (ARB_texture_cube_map_array , OES_texture_cube_map_array)
EXTRA_EXT2() [5/5]
EXTRA_EXT2 (ARB_transform_feedback3 , ARB_gpu_shader5)
find_custom_value()
static void find_custom_value (struct gl_context * ctx, const struct value_desc * d, union value * v) static
Handle irregular enums.
Some values don't conform to the "well-known type at context pointer + offset" pattern, so we have this function to catch all the corner cases. Typically, it's a computed value or a one-off pointer to a custom struct or something.
In this case we can't return a pointer to the value, so we'll have to use the temporary variable 'v' declared back in the calling glGet*v() function to store the result.
Parameters
ctx the current context
d the struct value_desc that describes the enum
v pointer to the tmp declared in the calling glGet*v() function
References gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_IntegerBuffers, _mesa_geometric_samples(), _mesa_get_clamp_fragment_color(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_compressed_formats(), _mesa_get_debug_state_int(), _mesa_get_extension_count(), _mesa_get_format_bits(), _mesa_get_stencil_ref(), _mesa_is_format_signed(), _mesa_IsEnabled(), _mesa_problem(), ACOMP, gl_transform_feedback_object::Active, gl_stencil_attrib::ActiveFace, gl_pipeline_object::ActiveProgram, gl_array_attrib::ActiveTexture, gl_colorbuffer_attrib::AlphaRef, gl_colorbuffer_attrib::AlphaRefUnclamped, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::AtomicBuffer, gl_current_attrib::Attrib, gl_memory_info::avail_device_memory, gl_memory_info::avail_staging_memory, BCOMP, gl_colorbuffer_attrib::BlendColor, gl_colorbuffer_attrib::BlendColorUnclamped, gl_vertex_array_object::BufferBinding, gl_pixelstore_attrib::BufferObj, gl_vertex_buffer_binding::BufferObj, gl_texture_object::BufferObject, gl_texture_attrib::BufferObject, gl_texture_object::BufferObjectFormat, gl_colorbuffer_attrib::ClearColor, gl_fog_attrib::Color, gl_context::Color, gl_colorbuffer_attrib::ColorMask, gl_framebuffer::ColorReadBuffer, gl_fog_attrib::ColorUnclamped, gl_context::CompileFlag, gl_context::Const, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_pipeline_shader_state::Current, gl_context::Current, gl_transform_feedback_state::CurrentBuffer, gl_dlist_state::CurrentList, gl_transform_feedback_state::CurrentObject, gl_context::CurrentRenderbuffer, gl_context::CurrentStack, gl_texture_unit::CurrentTex, gl_texture_attrib::CurrentUnit, gl_matrix_stack::Depth, gl_memory_info::device_memory_evicted, gl_context::DispatchIndirectBuffer, gl_context::DrawBuffer, gl_context::DrawIndirectBuffer, gl_context::Driver, gl_scissor_attrib::EnableFlags, gl_context::Eval, gl_context::ExecuteFlag, gl_color_union::f, gl_stencil_attrib::FailFunc, gl_viewport_attrib::Far, gl_context::Fog, gl_array_attributes::Format, gl_renderbuffer::Format, gl_stencil_attrib::Function, GCOMP, dd_function_table::GetTimestamp, GL_MAX_FRAGMENT_UNIFORM_VECTORS, GL_MAX_VERTEX_UNIFORM_VECTORS, GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES, GL_TEXTURE_BINDING_EXTERNAL_OES, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_scissor_rect::Height, gl_viewport_attrib::Height, gl_vertex_array_object::IndexBufferObj, value::ints, gl_context::Line, gl_context::ListState, gl_eval_attrib::MapGrid2u1, gl_eval_attrib::MapGrid2u2, gl_eval_attrib::MapGrid2v1, gl_eval_attrib::MapGrid2v2, gl_program_constants::MaxUniformComponents, gl_constants::MaxVarying, value::n, gl_sampler_object::Name, gl_texture_object::Name, gl_buffer_object::Name, gl_transform_feedback_object::Name, gl_shader_program::Name, gl_pipeline_object::Name, gl_renderbuffer::Name, gl_framebuffer::Name, gl_display_list::Name, gl_viewport_attrib::Near, gl_memory_info::nr_device_memory_evictions, value_desc::offset, gl_context::Pack, gl_context::ParameterBuffer, gl_transform_feedback_object::Paused, gl_context::Pipeline, value_desc::pname, gl_constants::Program, gl_context::QueryBuffer, dd_function_table::QueryMemoryInfo, gl_current_attrib::RasterTexCoords, RCOMP, gl_context::ReadBuffer, gl_texture_unit::Sampler, gl_context::Scissor, gl_scissor_attrib::ScissorArray, gl_context::Shader, gl_context::ShaderStorageBuffer, gl_array_attributes::Size, gl_context::Stencil, gl_line_attrib::StipplePattern, gl_context::Texture, TEXTURE_BUFFER_INDEX, gl_context::TextureMatrixStack, gl_matrix_stack::Top, gl_memory_info::total_device_memory, gl_memory_info::total_staging_memory, gl_context::TransformFeedback, gl_context::UniformBuffer, gl_texture_attrib::Unit, gl_context::Unpack, value::value_bool, value::value_double_2, value::value_enum, value::value_float, value::value_float_4, value::value_int, value::value_int64, value::value_int_4, value::value_int_n, value::value_matrix, gl_stencil_attrib::ValueMask, gl_array_attrib::VAO, gl_context::Version, gl_vertex_array_object::VertexAttrib, gl_context::ViewportArray, gl_scissor_rect::Width, gl_viewport_attrib::Width, gl_stencil_attrib::WriteMask, gl_scissor_rect::X, gl_viewport_attrib::X, gl_scissor_rect::Y, gl_viewport_attrib::Y, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Referenced by find_value().
find_value()
static const struct value_desc* find_value (const char * func, GLenum pname, void ** p, union value * v) static
Find the struct value_desc corresponding to the enum 'pname'.
We hash the enum value to get an index into the 'table' array, which holds the index in the 'values' array of struct value_desc. Once we've found the entry, we do the extra checks, if any, then look up the value and return a pointer to it.
If the value has to be computed (for example, it's the result of a function call or we need to add 1 to it), we use the tmp 'v' to store the result.
Parameters
func name of glGet*v() func for error reporting
pname the enum value we're looking up
p is were we return the pointer to the value
v a tmp union value variable in the calling glGet*v() function
Returns
the struct value_desc corresponding to the enum or a struct value_desc of TYPE_INVALID if not found. This lets the calling glGet*v() function jump right into a switch statement and handle errors there instead of having to check for NULL.
References _mesa_enum_to_string(), _mesa_error(), API_OPENGL_LAST, API_OPENGLES2, check_extra(), error_value, value_desc::extra, find_custom_value(), GET_CURRENT_CONTEXT, LOC_ARRAY, LOC_BUFFER, LOC_CONTEXT, LOC_CUSTOM, LOC_TEXUNIT, value_desc::location, value_desc::offset, and value_desc::pname.
Referenced by _mesa_GetBooleanv(), _mesa_GetDoublev(), _mesa_GetFixedv(), _mesa_GetFloatv(), _mesa_GetInteger64v(), and _mesa_GetIntegerv().
find_value_indexed()
static enum value_type find_value_indexed (const char * func, GLenum pname, GLuint index, union value * v) static
References _mesa_enum_to_string(), _mesa_error(), _mesa_has_compute_shaders(), _mesa_is_desktop_gl(), _mesa_is_gles31(), _mesa_max_tex_unit(), ACOMP, API_OPENGL_CORE, API_OPENGLES2, BCOMP, GCOMP, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_sampler_object::Name, gl_texture_object::Name, RCOMP, tex_binding_to_index(), TYPE_DOUBLEN_2, TYPE_FLOAT_4, TYPE_INT, TYPE_INT64, TYPE_INT_4, TYPE_INVALID, value::value_double_2, value::value_float_4, value::value_int, value::value_int64, and value::value_int_4.
Referenced by _mesa_GetBooleani_v(), _mesa_GetDoublei_v(), _mesa_GetFloati_v(), _mesa_GetInteger64i_v(), and _mesa_GetIntegeri_v().
tex_binding_to_index()
static int tex_binding_to_index (const struct gl_context * ctx, GLenum binding) static
Convert a GL texture binding enum such as GL_TEXTURE_BINDING_2D into the corresponding Mesa texture target index.
Returns
TEXTURE_x_INDEX or -1 if binding is invalid
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_context::API, API_OPENGLES, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::NV_texture_rectangle, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_BUFFER_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, and TEXTURE_RECT_INDEX.
Referenced by find_value_indexed().
Variable Documentation
error_value
const struct value_desc error_value static
Initial value:
=
   { 0, 0, TYPE_INVALID, NO_OFFSET, NO_EXTRA }
Referenced by find_value().
extra_ARB_color_buffer_float_or_glcore
const int extra_ARB_color_buffer_float_or_glcore[] static
Initial value:
= {
   EXT(ARB_color_buffer_float),
   EXTRA_API_GL_CORE,
   EXTRA_END
}
extra_ARB_compute_shader_es31
const int extra_ARB_compute_shader_es31[] static
Initial value:
= {
   EXT(ARB_compute_shader),
   EXTRA_API_ES31,
   EXTRA_END
}
extra_ARB_ES2_compatibility_api_es2
const int extra_ARB_ES2_compatibility_api_es2[] static
Initial value:
= {
   EXT(ARB_ES2_compatibility),
   EXTRA_API_ES2,
   EXTRA_END
}
extra_ARB_ES3_compatibility_api_es3
const int extra_ARB_ES3_compatibility_api_es3[] static
Initial value:
= {
   EXT(ARB_ES3_compatibility),
   EXTRA_API_ES3,
   EXTRA_END
}
extra_ARB_framebuffer_no_attachments_and_geometry_shader
const int extra_ARB_framebuffer_no_attachments_and_geometry_shader[] static
Initial value:
= {
   EXTRA_EXT_FB_NO_ATTACH_GS,
   EXTRA_END
}
extra_ARB_gpu_shader5_or_oes_geometry_shader
const int extra_ARB_gpu_shader5_or_oes_geometry_shader[] static
Initial value:
= {
   EXT(ARB_gpu_shader5),
   EXTRA_EXT_ES_GS,
   EXTRA_END
}
extra_ARB_gpu_shader5_or_OES_sample_variables
const int extra_ARB_gpu_shader5_or_OES_sample_variables[] static
Initial value:
= {
   EXT(ARB_gpu_shader5),
   EXT(OES_sample_variables),
   EXTRA_END
}
extra_ARB_shader_atomic_counters_and_geometry_shader
const int extra_ARB_shader_atomic_counters_and_geometry_shader[] static
Initial value:
= {
   EXTRA_EXT_ATOMICS_GS,
   EXTRA_END
}
extra_ARB_shader_atomic_counters_and_tessellation
const int extra_ARB_shader_atomic_counters_and_tessellation[] static
Initial value:
= {
   EXTRA_EXT_ATOMICS_TESS,
   EXTRA_END
}
extra_ARB_shader_image_load_store_and_geometry_shader
const int extra_ARB_shader_image_load_store_and_geometry_shader[] static
Initial value:
= {
   EXTRA_EXT_SHADER_IMAGE_GS,
   EXTRA_END
}
extra_ARB_shader_image_load_store_and_tessellation
const int extra_ARB_shader_image_load_store_and_tessellation[] static
Initial value:
= {
   EXTRA_EXT_SHADER_IMAGE_TESS,
   EXTRA_END
}
extra_ARB_shader_image_load_store_shader_storage_buffer_object_es31
const int extra_ARB_shader_image_load_store_shader_storage_buffer_object_es31[] static
Initial value:
= {
   EXT(ARB_shader_image_load_store),
   EXT(ARB_shader_storage_buffer_object),
   EXTRA_API_ES31,
   EXTRA_END
}
extra_ARB_shader_storage_buffer_object_and_geometry_shader
const int extra_ARB_shader_storage_buffer_object_and_geometry_shader[] static
Initial value:
= {
   EXTRA_EXT_SSBO_GS,
   EXTRA_END
}
extra_ARB_shader_storage_buffer_object_es31
const int extra_ARB_shader_storage_buffer_object_es31[] static
Initial value:
= {
   EXT(ARB_shader_storage_buffer_object),
   EXTRA_API_ES31,
   EXTRA_END
}
extra_ARB_transform_feedback2_api_es3
const int extra_ARB_transform_feedback2_api_es3[] static
Initial value:
= {
   EXT(ARB_transform_feedback2),
   EXTRA_API_ES3,
   EXTRA_END
}
extra_ARB_uniform_buffer_object_and_geometry_shader
const int extra_ARB_uniform_buffer_object_and_geometry_shader[] static
Initial value:
= {
   EXTRA_EXT_UBO_GS,
   EXTRA_END
}
extra_ARB_vertex_program_api_es2
const int extra_ARB_vertex_program_api_es2[] static
Initial value:
= {
   EXT(ARB_vertex_program),
   EXTRA_API_ES2,
   EXTRA_END
}
extra_ARB_viewport_array_or_oes_geometry_shader
const int extra_ARB_viewport_array_or_oes_geometry_shader[] static
Initial value:
= {
   EXT(ARB_viewport_array),
   EXTRA_EXT_ES_GS,
   EXTRA_END
}
extra_ARB_viewport_array_or_oes_viewport_array
const int extra_ARB_viewport_array_or_oes_viewport_array[] static
Initial value:
= {
   EXT(ARB_viewport_array),
   EXT(OES_viewport_array),
   EXTRA_END
}
extra_core_ARB_color_buffer_float_and_new_buffers
const int extra_core_ARB_color_buffer_float_and_new_buffers[] static
Initial value:
= {
   EXTRA_API_GL_CORE,
   EXT(ARB_color_buffer_float),
   EXTRA_NEW_BUFFERS,
   EXTRA_END
}
extra_ES32
const int extra_ES32[] static
Initial value:
= {
   EXT(ARB_ES3_2_compatibility),
   EXTRA_API_ES32,
   EXTRA_END
}
extra_EXT_framebuffer_sRGB_and_new_buffers
const int extra_EXT_framebuffer_sRGB_and_new_buffers[] static
Initial value:
= {
   EXT(EXT_framebuffer_sRGB),
   EXTRA_NEW_BUFFERS,
   EXTRA_END
}
extra_EXT_packed_float
const int extra_EXT_packed_float[] static
Initial value:
= {
   EXT(EXT_packed_float),
   EXTRA_NEW_BUFFERS,
   EXTRA_END
}
extra_EXT_shader_framebuffer_fetch
const int extra_EXT_shader_framebuffer_fetch[] static
Initial value:
= {
   EXTRA_API_ES2,
   EXTRA_API_ES3,
   EXT(MESA_shader_framebuffer_fetch),
   EXTRA_END
}
extra_EXT_texture_array_es3
const int extra_EXT_texture_array_es3[] static
Initial value:
= {
   EXT(EXT_texture_array),
   EXTRA_API_ES3,
   EXTRA_END
}
extra_EXT_texture_integer_and_new_buffers
const int extra_EXT_texture_integer_and_new_buffers[] static
Initial value:
= {
   EXT(EXT_texture_integer),
   EXTRA_NEW_BUFFERS,
   EXTRA_END
}
extra_flush_current
const int extra_flush_current[] static
Initial value:
= {
   EXTRA_FLUSH_CURRENT,
   EXTRA_END
}
extra_flush_current_valid_texture_unit
const int extra_flush_current_valid_texture_unit[] static
Initial value:
= {
   EXTRA_FLUSH_CURRENT,
   EXTRA_VALID_TEXTURE_UNIT,
   EXTRA_END
}
extra_gl30_es3
const int extra_gl30_es3[] static
Initial value:
= {
    EXTRA_VERSION_30,
    EXTRA_API_ES3,
    EXTRA_END,
}
extra_gl32_es3
const int extra_gl32_es3[] static
Initial value:
= {
    EXTRA_VERSION_32,
    EXTRA_API_ES3,
    EXTRA_END,
}
extra_gl40_ARB_sample_shading
const int extra_gl40_ARB_sample_shading[] static
Initial value:
= {
   EXTRA_VERSION_40,
   EXT(ARB_sample_shading),
   EXTRA_END
}
extra_GLSL_130_es3
const int extra_GLSL_130_es3[] static
Initial value:
= {
   EXTRA_GLSL_130,
   EXTRA_API_ES3,
   EXTRA_END
}
extra_INTEL_conservative_rasterization
const int extra_INTEL_conservative_rasterization[] static
Initial value:
= {
   EXT(INTEL_conservative_rasterization),
   EXTRA_END
}
extra_KHR_robustness_or_GL
const int extra_KHR_robustness_or_GL[] static
Initial value:
= {
   EXT(KHR_robustness),
   EXTRA_API_GL,
   EXTRA_API_GL_CORE,
   EXTRA_END
}
extra_new_buffers
const int extra_new_buffers[] static
Initial value:
= {
   EXTRA_NEW_BUFFERS,
   EXTRA_END
}
extra_new_frag_clamp
const int extra_new_frag_clamp[] static
Initial value:
= {
   EXTRA_NEW_FRAG_CLAMP,
   EXTRA_END
}
extra_NV_primitive_restart
const int extra_NV_primitive_restart[] static
Initial value:
= {
   EXT(NV_primitive_restart),
   EXTRA_END
}
extra_NV_read_buffer_api_gl
const int extra_NV_read_buffer_api_gl[] static
Initial value:
= {
   EXTRA_API_ES2,
   EXTRA_API_GL,
   EXTRA_END
}
extra_texture_buffer_object
const int extra_texture_buffer_object[] static
Initial value:
= {
   EXTRA_API_GL_CORE,
   EXTRA_VERSION_31,
   EXT(ARB_texture_buffer_object),
   EXTRA_END
}
extra_valid_clip_distance
const int extra_valid_clip_distance[] static
Initial value:
= {
   EXTRA_VALID_CLIP_DISTANCE,
   EXTRA_END
}
extra_valid_draw_buffer
const int extra_valid_draw_buffer[] static
Initial value:
= {
   EXTRA_VALID_DRAW_BUFFER,
   EXTRA_END
}
extra_valid_texture_unit
const int extra_valid_texture_unit[] static
Initial value:
= {
   EXTRA_VALID_TEXTURE_UNIT,
   EXTRA_END
}
extra_version_30
const int extra_version_30[] = { EXTRA_VERSION_30, EXTRA_END } static
extra_version_31
const int extra_version_31[] = { EXTRA_VERSION_31, EXTRA_END } static
extra_version_32
const int extra_version_32[] = { EXTRA_VERSION_32, EXTRA_END } static
extra_version_32_OES_geometry_shader
const int extra_version_32_OES_geometry_shader[] static
Initial value:
= {
    EXTRA_VERSION_32,
    EXTRA_EXT_ES_GS,
    EXTRA_END
}
transpose
const int transpose[] static
Initial value:
= {
   0, 4,  8, 12,
   1, 5,  9, 13,
   2, 6, 10, 14,
   3, 7, 11, 15
}
Referenced by _mesa_GetBooleanv(), _mesa_GetDoublei_v(), _mesa_GetDoublev(), _mesa_GetFixedv(), _mesa_GetFloati_v(), _mesa_GetFloatv(), _mesa_GetInteger64v(), _mesa_GetIntegerv(), save_ProgramUniformMatrix2fv(), save_ProgramUniformMatrix2x3fv(), save_ProgramUniformMatrix2x4fv(), save_ProgramUniformMatrix3fv(), save_ProgramUniformMatrix3x2fv(), save_ProgramUniformMatrix3x4fv(), save_ProgramUniformMatrix4fv(), save_ProgramUniformMatrix4x2fv(), save_ProgramUniformMatrix4x3fv(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), and save_UniformMatrix4x3fv().