Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glformats.c File Reference
#include "context.h"
#include "glformats.h"
#include "formats.h"
#include "texcompress.h"
#include "enums.h"
Macros
#define MAP1(x) MAP4(x, ZERO, ZERO, ZERO)
#define MAP2(x, y) MAP4(x, y, ZERO, ZERO)
#define MAP3(x, y, z) MAP4(x, y, z, ZERO)
#define MAP4(x, y, z, w) { x, y, z, w, ZERO, ONE }
Enumerations
enum { ZERO = 4, ONE = 5 }
enum {
IDX_LUMINANCE = 0, IDX_ALPHA, IDX_INTENSITY, IDX_LUMINANCE_ALPHA,
IDX_RGB, IDX_RGBA, IDX_RED, IDX_GREEN,
IDX_BLUE, IDX_BGR, IDX_BGRA, IDX_ABGR,
IDX_RG, MAX_IDX
}
Functions
static int get_map_idx (GLenum value)
Convert a GL image format enum to an IDX_* value (see above).
void _mesa_compute_component_mapping (GLenum inFormat, GLenum outFormat, GLubyte *map)
When promoting texture formats (see below) we need to compute the mapping of dest components back to source components.
GLboolean _mesa_type_is_packed (GLenum type)
GLint _mesa_sizeof_type (GLenum type)
Get the size of a GL data type.
GLint _mesa_sizeof_packed_type (GLenum type)
Same as _mesa_sizeof_type() but also accepting the packed pixel format data types.
GLint _mesa_components_in_format (GLenum format)
Get the number of components in a pixel format.
GLint _mesa_bytes_per_pixel (GLenum format, GLenum type)
Get the bytes per pixel of pixel format type pair.
GLint _mesa_bytes_per_vertex_attrib (GLint comps, GLenum type)
Get the number of bytes for a vertex attrib with the given number of components and type.
GLboolean _mesa_is_enum_format_unsized (GLenum format)
Test if the given format is unsized.
GLboolean _mesa_is_enum_format_unorm (GLenum format)
Test if the given format is a UNORM (unsigned-normalized) format.
GLboolean _mesa_is_enum_format_snorm (GLenum format)
Test if the given format is a SNORM (signed-normalized) format.
GLboolean _mesa_is_enum_format_unsigned_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
GLboolean _mesa_is_enum_format_signed_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
static bool is_astc_2d_format (GLenum internalFormat)
Test if the given format is an ASTC 2D format.
static bool is_astc_3d_format (GLenum internalFormat)
Test if the given format is an ASTC 3D format.
GLboolean _mesa_is_astc_format (GLenum internalFormat)
Test if the given format is an ASTC format.
GLboolean _mesa_is_etc2_format (GLenum internalFormat)
Test if the given format is an ETC2 format.
GLboolean _mesa_is_enum_format_integer (GLenum format)
Test if the given format is an integer (non-normalized) format.
GLboolean _mesa_is_type_unsigned (GLenum type)
GLboolean _mesa_is_color_format (GLenum format)
Test if the given image format is a color/RGBA format (i.e., not color index, depth, stencil, etc).
GLboolean _mesa_is_depth_format (GLenum format)
Test if the given image format is a depth component format.
GLboolean _mesa_is_stencil_format (GLenum format)
Test if the given image format is a stencil format.
GLboolean _mesa_is_ycbcr_format (GLenum format)
Test if the given image format is a YCbCr format.
GLboolean _mesa_is_depthstencil_format (GLenum format)
Test if the given image format is a depth+stencil format.
GLboolean _mesa_is_depth_or_stencil_format (GLenum format)
Test if the given image format is a depth or stencil format.
GLboolean _mesa_is_compressed_format (const struct gl_context *ctx, GLenum format)
Test if an image format is a supported compressed format.
GLboolean _mesa_is_srgb_format (GLenum format)
Test if the given format represents an sRGB format.
GLenum _mesa_unpack_format_to_base_format (GLenum format)
Convert various unpack formats to the corresponding base format.
GLenum _mesa_base_format_to_integer_format (GLenum format)
Convert various base formats to the corresponding integer format.
GLboolean _mesa_base_format_has_channel (GLenum base_format, GLenum pname)
Does the given base texture/renderbuffer format have the channel named by 'pname'?
GLint _mesa_base_format_component_count (GLenum base_format)
Returns the number of channels/components for a base format.
GLenum _mesa_generic_compressed_format_to_uncompressed_format (GLenum format)
If format is a generic compressed format, return the corresponding non-compressed format.
GLenum _mesa_get_nongeneric_internalformat (GLenum format)
Return the equivalent non-generic internal format.
GLenum _mesa_get_linear_internalformat (GLenum format)
Convert an sRGB internal format to linear.
GLenum _mesa_error_check_format_and_type (const struct gl_context *ctx, GLenum format, GLenum type)
Do error checking of format/type combinations for glReadPixels, glDrawPixels and glTex[Sub]Image.
GLenum _mesa_es_error_check_format_and_type (const struct gl_context *ctx, GLenum format, GLenum type, unsigned dimensions)
Do error checking of format/type combinations for OpenGL ES glReadPixels and glTex[Sub]Image.
GLint _mesa_base_tex_format (const struct gl_context *ctx, GLint internalFormat)
Return the simple base format for a given internal texture format.
static GLenum _mesa_es3_effective_internal_format_for_format_and_type (GLenum format, GLenum type)
Returns the effective internal format from a texture format and type.
GLenum _mesa_es3_error_check_format_and_type (const struct gl_context *ctx, GLenum format, GLenum type, GLenum internalFormat)
Do error checking of format/type combinations for OpenGL ES 3 glTex[Sub]Image.
static void set_swizzle (uint8_t *swizzle, int x, int y, int z, int w)
static bool get_swizzle_from_gl_format (GLenum format, uint8_t *swizzle)
uint32_t _mesa_format_from_format_and_type (GLenum format, GLenum type)
Take an OpenGL format (GL_RGB, GL_RGBA, etc), OpenGL data type (GL_INT, GL_FOAT, etc) and return a matching mesa_array_format or a mesa_format otherwise (for non-array formats).
uint32_t _mesa_tex_format_from_format_and_type (const struct gl_context *ctx, GLenum gl_format, GLenum type)
bool _mesa_is_es3_color_renderable (GLenum internal_format)
Returns true if internal_format is a sized internal format that is marked "Color Renderable" in Table 8.10 of the ES 3.2 specification.
bool _mesa_is_es3_texture_filterable (const struct gl_context *ctx, GLenum internal_format)
Returns true if internal_format is a sized internal format that is marked "Texture Filterable" in Table 8.10 of the ES 3.2 specification.
Variables
struct {
GLubyte format_idx
GLubyte to_rgba [6]
GLubyte from_rgba [6]
} mappings [MAX_IDX]
Macro Definition Documentation
MAP1
#define MAP1 (x) MAP4(x, ZERO, ZERO, ZERO)
MAP2
#define MAP2 (x, y) MAP4(x, y, ZERO, ZERO)
MAP3
#define MAP3 (x, y, z) MAP4(x, y, z, ZERO)
MAP4
#define MAP4 (x, y, z, w) { x, y, z, w, ZERO, ONE }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ZERO
ONE
anonymous enum
anonymous enum
Enumerator
IDX_LUMINANCE
IDX_ALPHA
IDX_INTENSITY
IDX_LUMINANCE_ALPHA
IDX_RGB
IDX_RGBA
IDX_RED
IDX_GREEN
IDX_BLUE
IDX_BGR
IDX_BGRA
IDX_ABGR
IDX_RG
MAX_IDX
Function Documentation
_mesa_base_format_component_count()
GLint _mesa_base_format_component_count (GLenum base_format)
Returns the number of channels/components for a base format.
Referenced by copytexture_error_check().
_mesa_base_format_has_channel()
GLboolean _mesa_base_format_has_channel (GLenum base_format, GLenum pname)
Does the given base texture/renderbuffer format have the channel named by 'pname'?
References _mesa_warning().
Referenced by _mesa_GetInternalformativ(), get_component_bits(), get_tex_level_parameter_buffer(), and get_tex_level_parameter_image().
_mesa_base_format_to_integer_format()
GLenum _mesa_base_format_to_integer_format (GLenum format)
Convert various base formats to the corresponding integer format.
Referenced by _mesa_GetInternalformativ(), and _mesa_query_internal_format_default().
_mesa_base_tex_format()
GLint _mesa_base_tex_format (const struct gl_context * ctx, GLint internalFormat)
Return the simple base format for a given internal texture format.
For example, given GL_LUMINANCE12_ALPHA4, return GL_LUMINANCE_ALPHA.
Parameters
ctx GL context.
internalFormat the internal texture format token or 1, 2, 3, or 4.
Returns
the corresponding base internal format (GL_ALPHA, GL_LUMINANCE, GL_LUMANCE_ALPHA, GL_INTENSITY, GL_RGB, or GL_RGBA), or -1 if invalid enum.
This is the format which is used during texture application (i.e. the texture format and env mode determine the arithmetic used.
References _mesa_gl_compressed_format_base_format(), _mesa_is_compressed_format(), _mesa_is_gles(), gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_depth_texture, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::ARB_texture_stencil8, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_texture_sRGB, gl_context::Extensions, is_astc_2d_format(), is_astc_3d_format(), gl_extensions::KHR_texture_compression_astc_ldr, gl_extensions::MESA_ycbcr_texture, gl_extensions::OES_texture_compression_astc, and gl_context::Version.
Referenced by _is_internalformat_supported(), _is_resource_supported(), _mesa_es3_error_check_format_and_type(), _mesa_GetInternalformativ(), _mesa_is_legal_tex_storage_format(), _mesa_legal_texture_base_format_for_target(), _mesa_query_internal_format_default(), compressed_texture_error_check(), copytexture_error_check(), init_teximage_fields_ms(), and texture_error_check().
_mesa_bytes_per_pixel()
GLint _mesa_bytes_per_pixel (GLenum format, GLenum type)
Get the bytes per pixel of pixel format type pair.
Parameters
format pixel format.
type pixel type.
Returns
bytes per pixel, or -1 if a bad format or type was given.
References _mesa_components_in_format(), GL_HALF_FLOAT_OES, GLuint, and GLushort.
Referenced by _mesa_image_image_stride(), _mesa_image_offset(), _mesa_image_row_stride(), _mesa_swap_bytes_2d_image(), _mesa_unpack_image(), and unpack_image().
_mesa_bytes_per_vertex_attrib()
GLint _mesa_bytes_per_vertex_attrib (GLint comps, GLenum type)
Get the number of bytes for a vertex attrib with the given number of components and type.
Parameters
comps number of components.
type data type.
Returns
bytes per attribute, or -1 if a bad comps/type combination was given.
References GL_HALF_FLOAT_OES, and GLuint.
Referenced by _mesa_update_array_format().
_mesa_components_in_format()
GLint _mesa_components_in_format (GLenum format)
Get the number of components in a pixel format.
Parameters
format pixel format.
Returns
the number of components in the given format, or -1 if a bad format.
Referenced by _mesa_bytes_per_pixel(), _mesa_format_from_format_and_type(), _mesa_get_tex_max_num_levels(), and _mesa_unpack_image().
_mesa_compute_component_mapping()
void _mesa_compute_component_mapping (GLenum inFormat, GLenum outFormat, GLubyte * map)
When promoting texture formats (see below) we need to compute the mapping of dest components back to source components.
This function does that.
Parameters
inFormat the incoming format of the texture
outFormat the final texture format
Returns
map[6] a full 6-component map
References _mesa_enum_to_string(), get_map_idx(), mappings, ONE, and ZERO.
Referenced by _mesa_compute_rgba2base2rgba_component_mapping().
_mesa_error_check_format_and_type()
GLenum _mesa_error_check_format_and_type (const struct gl_context * ctx, GLenum format, GLenum type)
Do error checking of format/type combinations for glReadPixels, glDrawPixels and glTex[Sub]Image.
Note that depending on the format and type values, we may either generate GL_INVALID_OPERATION or GL_INVALID_ENUM.
Parameters
format pixel format.
type pixel type.
Returns
GL_INVALID_ENUM, GL_INVALID_OPERATION or GL_NO_ERROR
References _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_context::API, API_OPENGLES2, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_context::Extensions, GL_HALF_FLOAT_OES, gl_extensions::MESA_ycbcr_texture, and gl_context::Version.
Referenced by _mesa_DrawPixels(), _mesa_ReadnPixelsARB(), check_clear_tex_image(), getteximage_error_check(), texsubimage_error_check(), texture_error_check(), and validate_clear_buffer_format().
_mesa_es3_effective_internal_format_for_format_and_type()
static GLenum _mesa_es3_effective_internal_format_for_format_and_type (GLenum format, GLenum type) static
Returns the effective internal format from a texture format and type.
This is used by texture image operations internally for validation, when the specified internal format is a base (unsized) format.
This method will only return a valid effective internal format if the combination of format, type and internal format in base form, is acceptable.
If a single sized internal format is defined in the spec (OpenGL-ES 3.0.4) or in extensions, to unambiguously correspond to the given base format, then that internal format is returned as the effective. Otherwise, if the combination is accepted but a single effective format is not defined, the passed base format will be returned instead.
Parameters
format the texture format
type the texture type
References GL_HALF_FLOAT_OES.
Referenced by _mesa_es3_error_check_format_and_type().
_mesa_es3_error_check_format_and_type()
GLenum _mesa_es3_error_check_format_and_type (const struct gl_context * ctx, GLenum format, GLenum type, GLenum internalFormat)
Do error checking of format/type combinations for OpenGL ES 3 glTex[Sub]Image.
Returns
error code, or GL_NO_ERROR.
References _mesa_base_tex_format(), _mesa_es3_effective_internal_format_for_format_and_type(), _mesa_is_enum_format_unsized(), gl_extensions::ARB_texture_rg, gl_context::Extensions, GL_HALF_FLOAT_OES, gl_extensions::OES_texture_float, and gl_extensions::OES_texture_half_float.
Referenced by texture_format_error_check_gles().
_mesa_es_error_check_format_and_type()
GLenum _mesa_es_error_check_format_and_type (const struct gl_context * ctx, GLenum format, GLenum type, unsigned dimensions)
Do error checking of format/type combinations for OpenGL ES glReadPixels and glTex[Sub]Image.
Returns
error code, or GL_NO_ERROR.
References gl_context::API, API_OPENGLES, gl_extensions::ARB_texture_rg, gl_context::Extensions, and GL_HALF_FLOAT_OES.
Referenced by _mesa_ReadnPixelsARB(), and texture_format_error_check_gles().
_mesa_format_from_format_and_type()
uint32_t _mesa_format_from_format_and_type (GLenum format, GLenum type)
Take an OpenGL format (GL_RGB, GL_RGBA, etc), OpenGL data type (GL_INT, GL_FOAT, etc) and return a matching mesa_array_format or a mesa_format otherwise (for non-array formats).
This function will typically be used to compute a mesa format from a GL type so we can then call _mesa_format_convert. This function does not consider byte swapping, so it returns types assuming that no byte swapping is involved. If byte swapping is involved then clients are supposed to handle that on their side before calling _mesa_format_convert.
This function returns an uint32_t that can pack a mesa_format or a mesa_array_format. Clients must check the mesa array format bit (MESA_ARRAY_FORMAT_BIT) on the return value to know if the returned format is a mesa_array_format or a mesa_format.
References _mesa_components_in_format(), _mesa_is_enum_format_integer(), get_swizzle_from_gl_format(), GL_HALF_FLOAT_OES, MESA_ARRAY_FORMAT, MESA_FORMAT_A1B5G5R5_UINT, MESA_FORMAT_A1B5G5R5_UNORM, MESA_FORMAT_A1R5G5B5_UINT, MESA_FORMAT_A1R5G5B5_UNORM, MESA_FORMAT_A2B10G10R10_UINT, MESA_FORMAT_A2B10G10R10_UNORM, MESA_FORMAT_A2R10G10B10_UINT, MESA_FORMAT_A2R10G10B10_UNORM, MESA_FORMAT_A4B4G4R4_UINT, MESA_FORMAT_A4B4G4R4_UNORM, MESA_FORMAT_A4R4G4B4_UINT, MESA_FORMAT_A4R4G4B4_UNORM, MESA_FORMAT_A8B8G8R8_UINT, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8R8G8B8_UINT, MESA_FORMAT_A8R8G8B8_UNORM, MESA_FORMAT_B10G10R10A2_UINT, MESA_FORMAT_B10G10R10A2_UNORM, MESA_FORMAT_B2G3R3_UINT, MESA_FORMAT_B2G3R3_UNORM, MESA_FORMAT_B4G4R4A4_UINT, MESA_FORMAT_B4G4R4A4_UNORM, MESA_FORMAT_B5G5R5A1_UINT, MESA_FORMAT_B5G5R5A1_UNORM, MESA_FORMAT_B5G6R5_UINT, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_UINT, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R10G10B10X2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R3G3B2_UINT, MESA_FORMAT_R3G3B2_UNORM, MESA_FORMAT_R4G4B4A4_UINT, MESA_FORMAT_R4G4B4A4_UNORM, MESA_FORMAT_R5G5B5A1_UINT, MESA_FORMAT_R5G5B5A1_UNORM, MESA_FORMAT_R5G6B5_UINT, MESA_FORMAT_R5G6B5_UNORM, MESA_FORMAT_R8G8B8A8_UINT, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R9G9B9E5_FLOAT, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, and swizzle().
Referenced by _mesa_tex_format_from_format_and_type(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), read_rgba_pixels(), and texstore_rgba().
_mesa_generic_compressed_format_to_uncompressed_format()
GLenum _mesa_generic_compressed_format_to_uncompressed_format (GLenum format)
If format is a generic compressed format, return the corresponding non-compressed format.
For other formats, return the format as-is.
_mesa_get_linear_internalformat()
GLenum _mesa_get_linear_internalformat (GLenum format)
Convert an sRGB internal format to linear.
Referenced by compatible_resolve_formats(), and copytexture_error_check().
_mesa_get_nongeneric_internalformat()
GLenum _mesa_get_nongeneric_internalformat (GLenum format)
Return the equivalent non-generic internal format.
This is useful for comparing whether two internal formats are equivalent.
Referenced by compatible_resolve_formats().
_mesa_is_astc_format()
GLboolean _mesa_is_astc_format (GLenum internalFormat)
Test if the given format is an ASTC format.
References is_astc_2d_format(), and is_astc_3d_format().
Referenced by _mesa_format_no_online_compression(), _mesa_is_valid_generate_texture_mipmap_internalformat(), and compressed_format_compatible().
_mesa_is_color_format()
GLboolean _mesa_is_color_format (GLenum format)
Test if the given image format is a color/RGBA format (i.e., not color index, depth, stencil, etc).
Parameters
format the image format value (may by an internal texture format)
Returns
GL_TRUE if its a color/RGBA format, GL_FALSE otherwise.
References GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, and GL_ETC1_RGB8_OES.
Referenced by _mesa_get_read_renderbuffer_for_format(), _mesa_GetInternalformativ(), _mesa_ReadnPixelsARB(), copytexsubimage_error_check(), copytexture_error_check(), getteximage_error_check(), texture_formats_agree(), and validate_clear_buffer_format().
_mesa_is_compressed_format()
GLboolean _mesa_is_compressed_format (const struct gl_context * ctx, GLenum format)
Test if an image format is a supported compressed format.
Parameters
format the internal format token provided by the user.
Returns
GL_TRUE if compressed, GL_FALSE if uncompressed
References _mesa_get_format_color_encoding(), _mesa_get_format_layout(), _mesa_glenum_to_compressed_format(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_extensions::ANGLE_texture_compression_dxt, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ATI_texture_compression_3dc, gl_extensions::EXT_texture_compression_latc, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_sRGB, gl_context::Extensions, GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, gl_extensions::KHR_texture_compression_astc_ldr, MESA_FORMAT_LAYOUT_ASTC, MESA_FORMAT_LAYOUT_BPTC, MESA_FORMAT_LAYOUT_ETC1, MESA_FORMAT_LAYOUT_ETC2, MESA_FORMAT_LAYOUT_FXT1, MESA_FORMAT_LAYOUT_LATC, MESA_FORMAT_LAYOUT_RGTC, MESA_FORMAT_LAYOUT_S3TC, gl_extensions::OES_compressed_ETC1_RGB8_texture, and gl_extensions::TDFX_texture_compression_FXT1.
Referenced by _is_resource_supported(), _mesa_base_tex_format(), _mesa_choose_tex_format(), _mesa_GetInternalformativ(), check_clear_tex_image(), compressed_format_compatible(), compressed_subtexture_error_check(), compressed_texture_error_check(), copy_format_compatible(), copytexture_error_check(), tex_storage_error_check(), and texture_error_check().
_mesa_is_depth_format()
GLboolean _mesa_is_depth_format (GLenum format)
Test if the given image format is a depth component format.
Referenced by _mesa_get_read_renderbuffer_for_format(), _mesa_GetInternalformativ(), getteximage_error_check(), and texture_formats_agree().
_mesa_is_depth_or_stencil_format()
GLboolean _mesa_is_depth_or_stencil_format (GLenum format)
Test if the given image format is a depth or stencil format.
Referenced by _mesa_check_sample_count(), and _mesa_texstore().
_mesa_is_depthstencil_format()
GLboolean _mesa_is_depthstencil_format (GLenum format)
Test if the given image format is a depth+stencil format.
Referenced by _mesa_get_read_renderbuffer_for_format(), _mesa_GetInternalformativ(), _mesa_is_valid_generate_texture_mipmap_internalformat(), getteximage_error_check(), and texture_formats_agree().
_mesa_is_enum_format_integer()
GLboolean _mesa_is_enum_format_integer (GLenum format)
Test if the given format is an integer (non-normalized) format.
References _mesa_is_enum_format_signed_int(), and _mesa_is_enum_format_unsigned_int().
Referenced by _mesa_check_sample_count(), _mesa_DrawPixels(), _mesa_format_from_format_and_type(), _mesa_get_readpixels_transfer_ops(), _mesa_GetInternalformativ(), _mesa_is_valid_generate_texture_mipmap_internalformat(), _mesa_query_internal_format_default(), _mesa_ReadnPixelsARB(), check_clear_tex_image(), copytexture_error_check(), get_tex_rgba_uncompressed(), getteximage_error_check(), read_rgba_pixels(), texsubimage_error_check(), and texture_error_check().
_mesa_is_enum_format_signed_int()
GLboolean _mesa_is_enum_format_signed_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
Referenced by _mesa_generic_type_for_internal_format(), _mesa_is_enum_format_integer(), read_pixels_es3_error_check(), and validate_clear_buffer_format().
_mesa_is_enum_format_snorm()
GLboolean _mesa_is_enum_format_snorm (GLenum format)
Test if the given format is a SNORM (signed-normalized) format.
Referenced by copytexture_error_check().
_mesa_is_enum_format_unorm()
GLboolean _mesa_is_enum_format_unorm (GLenum format)
Test if the given format is a UNORM (unsigned-normalized) format.
Referenced by copytexture_error_check().
_mesa_is_enum_format_unsigned_int()
GLboolean _mesa_is_enum_format_unsigned_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
Referenced by _mesa_generic_type_for_internal_format(), _mesa_is_enum_format_integer(), copytexture_error_check(), and read_pixels_es3_error_check().
_mesa_is_enum_format_unsized()
GLboolean _mesa_is_enum_format_unsized (GLenum format)
Test if the given format is unsized.
Referenced by _mesa_es3_error_check_format_and_type(), and copyteximage().
_mesa_is_es3_color_renderable()
bool _mesa_is_es3_color_renderable (GLenum internal_format)
Returns true if internal_format is a sized internal format that is marked "Color Renderable" in Table 8.10 of the ES 3.2 specification.
Referenced by _mesa_is_valid_generate_texture_mipmap_internalformat().
_mesa_is_es3_texture_filterable()
bool _mesa_is_es3_texture_filterable (const struct gl_context * ctx, GLenum internal_format)
Returns true if internal_format is a sized internal format that is marked "Texture Filterable" in Table 8.10 of the ES 3.2 specification.
References gl_context::Extensions, and gl_extensions::OES_texture_float_linear.
Referenced by _mesa_is_valid_generate_texture_mipmap_internalformat().
_mesa_is_etc2_format()
GLboolean _mesa_is_etc2_format (GLenum internalFormat)
Test if the given format is an ETC2 format.
Referenced by _mesa_format_no_online_compression().
_mesa_is_srgb_format()
GLboolean _mesa_is_srgb_format (GLenum format)
Test if the given format represents an sRGB format.
Parameters
format the GL format (can be an internal format)
Returns
GL_TRUE if format is sRGB, GL_FALSE otherwise
Referenced by _mesa_GetInternalformativ().
_mesa_is_stencil_format()
GLboolean _mesa_is_stencil_format (GLenum format)
Test if the given image format is a stencil format.
Referenced by _mesa_GetInternalformativ(), _mesa_is_valid_generate_texture_mipmap_internalformat(), copytexsubimage_error_check(), and getteximage_error_check().
_mesa_is_type_unsigned()
GLboolean _mesa_is_type_unsigned (GLenum type)
Referenced by _mesa_is_format_unsigned().
_mesa_is_ycbcr_format()
GLboolean _mesa_is_ycbcr_format (GLenum format)
Test if the given image format is a YCbCr format.
Referenced by getteximage_error_check(), and texture_formats_agree().
_mesa_sizeof_packed_type()
GLint _mesa_sizeof_packed_type (GLenum type)
Same as _mesa_sizeof_type() but also accepting the packed pixel format data types.
References GL_HALF_FLOAT_OES, GLuint, GLushort, and MESA_UNSIGNED_BYTE_4_4.
Referenced by _mesa_swap_bytes_2d_image(), _mesa_validate_pbo_access(), bytes_per_pixel(), and texstore_rgba().
_mesa_sizeof_type()
GLint _mesa_sizeof_type (GLenum type)
Get the size of a GL data type.
Parameters
type GL data type.
Returns
the size, in bytes, of the given data type, 0 if a GL_BITMAP, or -1 if an invalid type enum.
References GL_HALF_FLOAT_OES, GLuint, and GLushort.
Referenced by _mesa_pack_luminance_from_rgba_integer(), and init_array().
_mesa_tex_format_from_format_and_type()
uint32_t _mesa_tex_format_from_format_and_type (const struct gl_context * ctx, GLenum gl_format, GLenum type)
References _mesa_format_from_array_format(), _mesa_format_from_format_and_type(), _mesa_format_is_mesa_array_format(), MESA_FORMAT_NONE, and gl_context::TextureFormatSupported.
_mesa_type_is_packed()
GLboolean _mesa_type_is_packed (GLenum type)
Returns
GL_TRUE if type is packed pixel type, GL_FALSE otherwise.
References MESA_UNSIGNED_BYTE_4_4.
Referenced by _mesa_unpack_image(), and bytes_per_pixel().
_mesa_unpack_format_to_base_format()
GLenum _mesa_unpack_format_to_base_format (GLenum format)
Convert various unpack formats to the corresponding base format.
Referenced by _mesa_get_readpixels_transfer_ops(), _mesa_readpixels_needs_slow_path(), and read_rgba_pixels().
get_map_idx()
static int get_map_idx (GLenum value) static
Convert a GL image format enum to an IDX_* value (see above).
References _mesa_enum_to_string(), _mesa_problem(), IDX_ABGR, IDX_ALPHA, IDX_BGR, IDX_BGRA, IDX_BLUE, IDX_GREEN, IDX_INTENSITY, IDX_LUMINANCE, IDX_LUMINANCE_ALPHA, IDX_RED, IDX_RG, IDX_RGB, and IDX_RGBA.
Referenced by _mesa_compute_component_mapping().
get_swizzle_from_gl_format()
static bool get_swizzle_from_gl_format (GLenum format, uint8_t * swizzle) static
References set_swizzle().
Referenced by _mesa_format_from_format_and_type().
is_astc_2d_format()
static bool is_astc_2d_format (GLenum internalFormat) static
Test if the given format is an ASTC 2D format.
Referenced by _mesa_base_tex_format(), and _mesa_is_astc_format().
is_astc_3d_format()
static bool is_astc_3d_format (GLenum internalFormat) static
Test if the given format is an ASTC 3D format.
References GL_COMPRESSED_RGBA_ASTC_3x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x6_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES, and GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES.
Referenced by _mesa_base_tex_format(), and _mesa_is_astc_format().
set_swizzle()
static void set_swizzle (uint8_t * swizzle, int x, int y, int z, int w) static
References MESA_FORMAT_SWIZZLE_W, MESA_FORMAT_SWIZZLE_X, MESA_FORMAT_SWIZZLE_Y, MESA_FORMAT_SWIZZLE_Z, and x.
Referenced by get_swizzle_from_gl_format().
Variable Documentation
format_idx
GLubyte format_idx
from_rgba
GLubyte from_rgba[6]
mappings
const { ... } mappings[MAX_IDX]
Referenced by _mesa_compute_component_mapping().
to_rgba
GLubyte to_rgba[6]