Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
hash.h File Reference
Generic hash table.
#include "glheader.h"
Functions
struct _mesa_HashTable * _mesa_NewHashTable (void)
Create a new hash table.
void _mesa_DeleteHashTable (struct _mesa_HashTable *table)
Delete a hash table.
void * _mesa_HashLookup (struct _mesa_HashTable *table, GLuint key)
Lookup an entry in the hash table.
void _mesa_HashInsert (struct _mesa_HashTable *table, GLuint key, void *data)
Insert a key/pointer pair into the hash table.
void _mesa_HashRemove (struct _mesa_HashTable *table, GLuint key)
void _mesa_HashLockMutex (struct _mesa_HashTable *table)
Lock the hash table mutex.
void _mesa_HashUnlockMutex (struct _mesa_HashTable *table)
Unlock the hash table mutex.
void * _mesa_HashLookupLocked (struct _mesa_HashTable *table, GLuint key)
Lookup an entry in the hash table without locking the mutex.
void _mesa_HashInsertLocked (struct _mesa_HashTable *table, GLuint key, void *data)
Insert a key/pointer pair into the hash table without locking the mutex.
void _mesa_HashRemoveLocked (struct _mesa_HashTable *table, GLuint key)
void _mesa_HashDeleteAll (struct _mesa_HashTable *table, void(*callback)(GLuint key, void *data, void *userData), void *userData)
Delete all entries in a hash table, but don't delete the table itself.
void _mesa_HashWalk (const struct _mesa_HashTable *table, void(*callback)(GLuint key, void *data, void *userData), void *userData)
Walk over all entries in a hash table, calling callback function for each.
void _mesa_HashPrint (const struct _mesa_HashTable *table)
Dump contents of hash table for debugging.
GLuint _mesa_HashFindFreeKeyBlock (struct _mesa_HashTable *table, GLuint numKeys)
Find a block of adjacent unused hash keys.
GLuint _mesa_HashNumEntries (const struct _mesa_HashTable *table)
Return the number of entries in the hash table.
void _mesa_test_hash_functions (void)
Detailed Description
Generic hash table.
Function Documentation
_mesa_DeleteHashTable()
void _mesa_DeleteHashTable (struct _mesa_HashTable * table)
Delete a hash table.
Frees each entry on the hash table and then the hash table structure itself. Note that the caller should have already traversed the table and deleted the objects in the table (i.e. We don't free the entries' data pointer).
Parameters
table the hash table to delete.
References _mesa_problem(), _mesa_HashTable::ht, and _mesa_HashTable::Mutex.
Referenced by _mesa_free_performance_monitors(), _mesa_free_performance_queries(), _mesa_free_pipeline_data(), _mesa_free_queryobj_data(), _mesa_free_transform_feedback(), _mesa_free_varray_data(), and free_shared_state().
_mesa_HashDeleteAll()
void _mesa_HashDeleteAll (struct _mesa_HashTable * table, void(*)(GLuint key, void *data, void *userData) callback, void * userData)
Delete all entries in a hash table, but don't delete the table itself.
Invoke the given callback function for each table entry.
Parameters
table the hash table to delete
callback the callback function
userData arbitrary pointer to pass along to the callback (this is typically a struct gl_context pointer)
References _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, _mesa_HashTable::ht, _mesa_HashTable::InDeleteAll, and _mesa_HashTable::Mutex.
Referenced by _mesa_free_performance_monitors(), _mesa_free_performance_queries(), _mesa_free_pipeline_data(), _mesa_free_queryobj_data(), _mesa_free_transform_feedback(), _mesa_free_varray_data(), and free_shared_state().
_mesa_HashFindFreeKeyBlock()
GLuint _mesa_HashFindFreeKeyBlock (struct _mesa_HashTable * table, GLuint numKeys)
Find a block of adjacent unused hash keys.
Parameters
table the hash table.
numKeys number of keys needed.
Returns
Starting key of free block or 0 if failure.
If there are enough free keys between the maximum key existing in the table (_mesa_HashTable::MaxKey) and the maximum key possible, then simply return the adjacent key. Otherwise do a full search for a free key block in the allowable key range.
References _mesa_HashLookup_unlocked(), GLuint, and _mesa_HashTable::MaxKey.
Referenced by _mesa_CreatePerfQueryINTEL(), _mesa_GenFragmentShadersATI(), _mesa_GenLists(), _mesa_GenPerfMonitorsAMD(), _mesa_GenProgramsARB(), create_buffers(), create_framebuffers(), create_program_pipelines(), create_queries(), create_render_buffers(), create_samplers(), create_shader(), create_shader_program(), create_textures(), create_transform_feedbacks(), and gen_vertex_arrays().
_mesa_HashInsert()
void _mesa_HashInsert (struct _mesa_HashTable * table, GLuint key, void * data)
Insert a key/pointer pair into the hash table.
If an entry with this key already exists we'll replace the existing entry.
Parameters
table the hash table.
key the key (not zero).
data pointer to user data.
References _mesa_HashInsert_unlocked(), and _mesa_HashTable::Mutex.
Referenced by _mesa_BeginQueryIndexed(), _mesa_BindFragmentShaderATI(), _mesa_BindProgramARB(), _mesa_BindTexture(), _mesa_CreatePerfQueryINTEL(), _mesa_EndList(), _mesa_GenPerfMonitorsAMD(), _mesa_handle_bind_buffer_gen(), _mesa_QueryCounter(), alloc_bitmap_atlas(), bind_framebuffer(), create_queries(), create_transform_feedbacks(), save_array_object(), and save_pipeline_object().
_mesa_HashInsertLocked()
void _mesa_HashInsertLocked (struct _mesa_HashTable * table, GLuint key, void * data)
Insert a key/pointer pair into the hash table without locking the mutex.
If an entry with this key already exists we'll replace the existing entry.
The hash table mutex must be locked manually by calling _mesa_HashLockMutex() before calling this function.
Parameters
table the hash table.
key the key (not zero).
data pointer to user data.
References _mesa_HashInsert_unlocked().
Referenced by _mesa_GenFragmentShadersATI(), _mesa_GenLists(), _mesa_GenProgramsARB(), allocate_renderbuffer_locked(), create_buffers(), create_framebuffers(), create_render_buffers(), create_samplers(), create_shader(), create_shader_program(), and create_textures().
_mesa_HashLockMutex()
void _mesa_HashLockMutex (struct _mesa_HashTable * table)
Lock the hash table mutex.
This function should be used when multiple objects need to be looked up in the hash table, to avoid having to lock and unlock the mutex each time.
Parameters
table the hash table.
References _mesa_HashTable::Mutex.
Referenced by _mesa_BindImageTextures(), _mesa_BindSamplers(), _mesa_BindTextures(), _mesa_DeleteBuffers(), _mesa_DeleteSamplers(), _mesa_GenFragmentShadersATI(), _mesa_GenLists(), _mesa_GenProgramsARB(), bind_atomic_buffers(), bind_renderbuffer(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), create_buffers(), create_framebuffers(), create_render_buffers(), create_samplers(), create_shader(), create_shader_program(), create_textures(), and vertex_array_vertex_buffers().
_mesa_HashLookup()
void* _mesa_HashLookup (struct _mesa_HashTable * table, GLuint key)
Lookup an entry in the hash table.
Parameters
table the hash table.
key the key.
Returns
pointer to user's data or NULL if key not in table
References _mesa_HashLookup_unlocked(), and _mesa_HashTable::Mutex.
Referenced by _mesa_BindFragmentShaderATI(), _mesa_DeleteFragmentShaderATI(), _mesa_lookup_bufferobj(), _mesa_lookup_framebuffer(), _mesa_lookup_list(), _mesa_lookup_pipeline_object(), _mesa_lookup_query_object(), _mesa_lookup_renderbuffer(), _mesa_lookup_samplerobj(), _mesa_lookup_shader(), _mesa_lookup_shader_err(), _mesa_lookup_shader_program(), _mesa_lookup_shader_program_err(), _mesa_lookup_texture(), _mesa_lookup_transform_feedback_object(), _mesa_lookup_vao(), _mesa_lookup_vao_err(), alloc_bitmap_atlas(), lookup_bitmap_atlas(), lookup_monitor(), and lookup_object().
_mesa_HashLookupLocked()
void* _mesa_HashLookupLocked (struct _mesa_HashTable * table, GLuint key)
Lookup an entry in the hash table without locking the mutex.
The hash table mutex must be locked manually by calling _mesa_HashLockMutex() before calling this function.
Parameters
table the hash table.
key the key.
Returns
pointer to user's data or NULL if key not in table
References _mesa_HashLookup_unlocked().
Referenced by _mesa_lookup_bufferobj_locked(), _mesa_lookup_texture_locked(), and lookup_samplerobj_locked().
_mesa_HashNumEntries()
GLuint _mesa_HashNumEntries (const struct _mesa_HashTable * table)
Return the number of entries in the hash table.
References _mesa_HashTable::deleted_key_data, GLuint, and _mesa_HashTable::ht.
_mesa_HashPrint()
void _mesa_HashPrint (const struct _mesa_HashTable * table)
Dump contents of hash table for debugging.
Parameters
table the hash table.
References _mesa_HashWalk(), debug_print_entry(), _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, and GLuint.
_mesa_HashRemove()
void _mesa_HashRemove (struct _mesa_HashTable * table, GLuint key)
References _mesa_HashRemove_unlocked(), and _mesa_HashTable::Mutex.
Referenced by _mesa_BindFragmentShaderATI(), _mesa_DeleteFragmentShaderATI(), _mesa_DeleteFramebuffers(), _mesa_DeleteLists(), _mesa_DeletePerfMonitorsAMD(), _mesa_DeletePerfQueryINTEL(), _mesa_DeleteProgramsARB(), _mesa_DeleteQueries(), _mesa_DeleteRenderbuffers(), _mesa_DeleteTextures(), _mesa_DeleteTransformFeedbacks(), _mesa_reference_shader(), _mesa_reference_shader_program_(), destroy_list(), remove_array_object(), and remove_pipeline_object().
_mesa_HashRemoveLocked()
void _mesa_HashRemoveLocked (struct _mesa_HashTable * table, GLuint key)
References _mesa_HashRemove_unlocked().
Referenced by _mesa_DeleteBuffers(), and _mesa_DeleteSamplers().
_mesa_HashUnlockMutex()
void _mesa_HashUnlockMutex (struct _mesa_HashTable * table)
Unlock the hash table mutex.
Parameters
table the hash table.
References _mesa_HashTable::Mutex.
Referenced by _mesa_BindImageTextures(), _mesa_BindSamplers(), _mesa_BindTextures(), _mesa_DeleteBuffers(), _mesa_DeleteSamplers(), _mesa_GenFragmentShadersATI(), _mesa_GenLists(), _mesa_GenProgramsARB(), bind_atomic_buffers(), bind_renderbuffer(), bind_shader_storage_buffers(), bind_uniform_buffers(), bind_xfb_buffers(), create_buffers(), create_framebuffers(), create_render_buffers(), create_samplers(), create_shader(), create_shader_program(), create_textures(), and vertex_array_vertex_buffers().
_mesa_HashWalk()
void _mesa_HashWalk (const struct _mesa_HashTable * table, void(*)(GLuint key, void *data, void *userData) callback, void * userData)
Walk over all entries in a hash table, calling callback function for each.
Parameters
table the hash table to walk
callback the callback function
userData arbitrary pointer to pass along to the callback (this is typically a struct gl_context pointer)
References _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, _mesa_HashTable::ht, and _mesa_HashTable::Mutex.
Referenced by _mesa_dump_renderbuffers(), _mesa_dump_textures(), _mesa_HashPrint(), _mesa_renderbuffer_storage(), _mesa_total_buffer_object_memory(), _mesa_total_texture_memory(), _mesa_transform_feedback_is_using_program(), _mesa_update_fbo_texture(), destroy_list(), and free_shared_state().
_mesa_NewHashTable()
struct _mesa_HashTable* _mesa_NewHashTable (void)
Create a new hash table.
Returns
pointer to a new, empty hash table.
References _mesa_error_no_memory(), CALLOC_STRUCT, DELETED_KEY_VALUE, _mesa_HashTable::ht, _mesa_HashTable::Mutex, uint_key(), uint_key_compare(), and uint_key_hash().
Referenced by _mesa_alloc_shared_state(), _mesa_init_performance_monitors(), _mesa_init_performance_queries(), _mesa_init_pipeline(), _mesa_init_queryobj(), _mesa_init_transform_feedback(), and _mesa_init_varray().
_mesa_test_hash_functions()
void _mesa_test_hash_functions (void)