Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
hint.c File Reference
#include "glheader.h"
#include "enums.h"
#include "context.h"
#include "hint.h"
#include "imports.h"
#include "mtypes.h"
Functions
void GLAPIENTRY _mesa_Hint (GLenum target, GLenum mode)
void _mesa_init_hint (struct gl_context *ctx)
Function Documentation
_mesa_Hint()
void GLAPIENTRY _mesa_Hint (GLenum target, GLenum mode)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _NEW_HINT, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_init_hint()
void _mesa_init_hint (struct gl_context * ctx)
References gl_hint_attrib::Fog, gl_hint_attrib::FragmentShaderDerivative, gl_hint_attrib::GenerateMipmap, gl_context::Hint, gl_hint_attrib::LineSmooth, gl_hint_attrib::PerspectiveCorrection, gl_hint_attrib::PointSmooth, gl_hint_attrib::PolygonSmooth, and gl_hint_attrib::TextureCompression.
Referenced by init_attrib_groups().