Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
histogram.h File Reference
Histogram.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_GetnMinmaxARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid *values)
void GLAPIENTRY _mesa_GetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
void GLAPIENTRY _mesa_GetnHistogramARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid *values)
void GLAPIENTRY _mesa_GetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
void GLAPIENTRY _mesa_GetHistogramParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetHistogramParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetMinmaxParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetMinmaxParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_Histogram (GLenum target, GLsizei width, GLenum internalFormat, GLboolean sink)
void GLAPIENTRY _mesa_Minmax (GLenum target, GLenum internalFormat, GLboolean sink)
void GLAPIENTRY _mesa_ResetHistogram (GLenum target)
void GLAPIENTRY _mesa_ResetMinmax (GLenum target)
Detailed Description
Histogram.
Function Documentation
_mesa_GetHistogram()
void GLAPIENTRY _mesa_GetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values)
References _mesa_GetnHistogramARB(), and GLAPIENTRY.
_mesa_GetHistogramParameterfv()
void GLAPIENTRY _mesa_GetHistogramParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetHistogramParameteriv()
void GLAPIENTRY _mesa_GetHistogramParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetMinmax()
void GLAPIENTRY _mesa_GetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values)
References _mesa_GetnMinmaxARB(), and GLAPIENTRY.
_mesa_GetMinmaxParameterfv()
void GLAPIENTRY _mesa_GetMinmaxParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetMinmaxParameteriv()
void GLAPIENTRY _mesa_GetMinmaxParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetnHistogramARB()
void GLAPIENTRY _mesa_GetnHistogramARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid * values)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetHistogram().
_mesa_GetnMinmaxARB()
void GLAPIENTRY _mesa_GetnMinmaxARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid * values)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetMinmax().
_mesa_Histogram()
void GLAPIENTRY _mesa_Histogram (GLenum target, GLsizei width, GLenum internalFormat, GLboolean sink)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Minmax()
void GLAPIENTRY _mesa_Minmax (GLenum target, GLenum internalFormat, GLboolean sink)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ResetHistogram()
void GLAPIENTRY _mesa_ResetHistogram (GLenum target)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ResetMinmax()
void GLAPIENTRY _mesa_ResetMinmax (GLenum target)
References _mesa_error(), and GET_CURRENT_CONTEXT.