Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
image.c File Reference
Image handling.
#include "glheader.h"
#include "colormac.h"
#include "glformats.h"
#include "image.h"
#include "imports.h"
#include "macros.h"
#include "mtypes.h"
Functions
static void swap2_copy (GLushort *dst, GLushort *src, GLuint n)
Flip the order of the 2 bytes in each word in the given array (src) and store the result in another array (dst).
void _mesa_swap2 (GLushort *p, GLuint n)
static void swap4_copy (GLuint *dst, GLuint *src, GLuint n)
void _mesa_swap4 (GLuint *p, GLuint n)
GLintptr _mesa_image_offset (GLuint dimensions, const struct gl_pixelstore_attrib *packing, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint img, GLint row, GLint column)
Return the byte offset of a specific pixel in an image (1D, 2D or 3D).
GLvoid * _mesa_image_address (GLuint dimensions, const struct gl_pixelstore_attrib *packing, const GLvoid *image, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint img, GLint row, GLint column)
Return the address of a specific pixel in an image (1D, 2D or 3D).
GLvoid * _mesa_image_address1d (const struct gl_pixelstore_attrib *packing, const GLvoid *image, GLsizei width, GLenum format, GLenum type, GLint column)
GLvoid * _mesa_image_address2d (const struct gl_pixelstore_attrib *packing, const GLvoid *image, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint row, GLint column)
GLvoid * _mesa_image_address3d (const struct gl_pixelstore_attrib *packing, const GLvoid *image, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint img, GLint row, GLint column)
GLint _mesa_image_row_stride (const struct gl_pixelstore_attrib *packing, GLint width, GLenum format, GLenum type)
Compute the stride (in bytes) between image rows.
GLint _mesa_image_image_stride (const struct gl_pixelstore_attrib *packing, GLint width, GLint height, GLenum format, GLenum type)
void _mesa_expand_bitmap (GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap, GLubyte *destBuffer, GLint destStride, GLubyte onValue)
"Expand" a bitmap from 1-bit per pixel to 8-bits per pixel.
void _mesa_convert_colors (GLenum srcType, const GLvoid *src, GLenum dstType, GLvoid *dst, GLuint count, const GLubyte mask[])
Convert an array of RGBA colors from one datatype to another.
GLboolean _mesa_clip_drawpixels (const struct gl_context *ctx, GLint *destX, GLint *destY, GLsizei *width, GLsizei *height, struct gl_pixelstore_attrib *unpack)
Perform basic clipping for glDrawPixels.
GLboolean _mesa_clip_readpixels (const struct gl_context *ctx, GLint *srcX, GLint *srcY, GLsizei *width, GLsizei *height, struct gl_pixelstore_attrib *pack)
Perform clipping for glReadPixels.
GLboolean _mesa_clip_copytexsubimage (const struct gl_context *ctx, GLint *destX, GLint *destY, GLint *srcX, GLint *srcY, GLsizei *width, GLsizei *height)
Do clipping for a glCopyTexSubImage call.
GLboolean _mesa_clip_to_region (GLint xmin, GLint ymin, GLint xmax, GLint ymax, GLint *x, GLint *y, GLsizei *width, GLsizei *height)
Clip the rectangle defined by (x, y, width, height) against the bounds specified by [xmin, xmax) and [ymin, ymax).
static void clip_right_or_top (GLint *srcX0, GLint *srcX1, GLint *dstX0, GLint *dstX1, GLint maxValue)
Clip dst coords against Xmax (or Ymax).
static void clip_left_or_bottom (GLint *srcX0, GLint *srcX1, GLint *dstX0, GLint *dstX1, GLint minValue)
Clip dst coords against Xmin (or Ymin).
GLboolean _mesa_clip_blit (struct gl_context *ctx, const struct gl_framebuffer *readFb, const struct gl_framebuffer *drawFb, GLint *srcX0, GLint *srcY0, GLint *srcX1, GLint *srcY1, GLint *dstX0, GLint *dstY0, GLint *dstX1, GLint *dstY1)
Do clipping of blit src/dest rectangles.
void _mesa_swap_bytes_2d_image (GLenum format, GLenum type, const struct gl_pixelstore_attrib *packing, GLsizei width, GLsizei height, GLvoid *dst, const GLvoid *src)
Swap the bytes in a 2D image.
Detailed Description
Image handling.
Function Documentation
_mesa_clip_blit()
GLboolean _mesa_clip_blit (struct gl_context * ctx, const struct gl_framebuffer * readFb, const struct gl_framebuffer * drawFb, GLint * srcX0, GLint * srcY0, GLint * srcX1, GLint * srcY1, GLint * dstX0, GLint * dstY0, GLint * dstX1, GLint * dstY1)
Do clipping of blit src/dest rectangles.
The dest rect is clipped against both the buffer bounds and scissor bounds. The src rect is just clipped against the buffer bounds.
When either the src or dest rect is clipped, the other is also clipped proportionately!
Note that X0 need not be less than X1 (same for Y) for either the source and dest rects. That makes the clipping a little trickier.
Returns
GL_TRUE if anything is left to draw, GL_FALSE if totally clipped
References gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, clip_left_or_bottom(), clip_right_or_top(), gl_framebuffer::Height, and gl_framebuffer::Width.
_mesa_clip_copytexsubimage()
GLboolean _mesa_clip_copytexsubimage (const struct gl_context * ctx, GLint * destX, GLint * destY, GLint * srcX, GLint * srcY, GLsizei * width, GLsizei * height)
Do clipping for a glCopyTexSubImage call.
The framebuffer source region might extend outside the framebuffer bounds. Clip the source region against the framebuffer bounds and adjust the texture/dest position and size accordingly.
Returns
GL_FALSE if region is totally clipped, GL_TRUE otherwise.
References _mesa_clip_to_region(), gl_framebuffer::Height, gl_context::ReadBuffer, and gl_framebuffer::Width.
Referenced by _mesa_copy_texture_sub_image(), and copyteximage().
_mesa_clip_drawpixels()
GLboolean _mesa_clip_drawpixels (const struct gl_context * ctx, GLint * destX, GLint * destY, GLsizei * width, GLsizei * height, struct gl_pixelstore_attrib * unpack)
Perform basic clipping for glDrawPixels.
The image's position and size and the unpack SkipPixels and SkipRows are adjusted so that the image region is entirely within the window and scissor bounds. NOTE: this will only work when glPixelZoom is (1, 1) or (1, -1). If Pixel.ZoomY is -1, *destY will be changed to be the first row which we'll actually write. Beforehand, *destY-1 is the first drawing row.
Returns
GL_TRUE if image is ready for drawing or GL_FALSE if image was completely clipped away (draw nothing)
References gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_context::DrawBuffer, gl_context::Pixel, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
_mesa_clip_readpixels()
GLboolean _mesa_clip_readpixels (const struct gl_context * ctx, GLint * srcX, GLint * srcY, GLsizei * width, GLsizei * height, struct gl_pixelstore_attrib * pack)
Perform clipping for glReadPixels.
The image's window position and size, and the pack skipPixels, skipRows and rowLength are adjusted so that the image region is entirely within the window bounds. Note: this is different from _mesa_clip_drawpixels() in that the scissor box is ignored, and we use the bounds of the current readbuffer surface or the attached image.
Returns
GL_TRUE if region to read is in bounds GL_FALSE if region is completely out of bounds (nothing to read)
References gl_framebuffer::_ColorReadBuffer, gl_renderbuffer::Height, gl_framebuffer::Height, gl_context::ReadBuffer, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_ReadnPixelsARB().
_mesa_clip_to_region()
GLboolean _mesa_clip_to_region (GLint xmin, GLint ymin, GLint xmax, GLint ymax, GLint * x, GLint * y, GLsizei * width, GLsizei * height)
Clip the rectangle defined by (x, y, width, height) against the bounds specified by [xmin, xmax) and [ymin, ymax).
Returns
GL_FALSE if rect is totally clipped, GL_TRUE otherwise.
References x.
Referenced by _mesa_clip_copytexsubimage().
_mesa_convert_colors()
void _mesa_convert_colors (GLenum srcType, const GLvoid * src, GLenum dstType, GLvoid * dst, GLuint count, const GLubyte mask[])
Convert an array of RGBA colors from one datatype to another.
NOTE: src may equal dst. In that case, we use a temporary buffer.
References _mesa_problem(), _mesa_unclamped_float_rgba_to_ubyte(), ACOMP, BCOMP, GCOMP, GLuint, GLushort, MAX_PIXEL_BYTES, RCOMP, UBYTE_TO_FLOAT, UBYTE_TO_USHORT, UNCLAMPED_FLOAT_TO_USHORT, USHORT_TO_FLOAT, and USHORT_TO_UBYTE.
_mesa_expand_bitmap()
void _mesa_expand_bitmap (GLsizei width, GLsizei height, const struct gl_pixelstore_attrib * unpack, const GLubyte * bitmap, GLubyte * destBuffer, GLint destStride, GLubyte onValue)
"Expand" a bitmap from 1-bit per pixel to 8-bits per pixel.
This is typically used to convert a bitmap into a GLubyte/pixel texture. "On" bits will set texels to onValue. "Off" bits will not modify texels.
Parameters
width src bitmap width in pixels
height src bitmap height in pixels
unpack bitmap unpacking state
bitmap the src bitmap data
destBuffer start of dest buffer
destStride row stride in dest buffer
onValue if bit is 1, set destBuffer pixel to this value
References _mesa_image_address2d(), _mesa_image_row_stride(), gl_pixelstore_attrib::LsbFirst, and gl_pixelstore_attrib::SkipPixels.
Referenced by build_bitmap_atlas().
_mesa_image_address()
GLvoid* _mesa_image_address (GLuint dimensions, const struct gl_pixelstore_attrib * packing, const GLvoid * image, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint img, GLint row, GLint column)
Return the address of a specific pixel in an image (1D, 2D or 3D).
Pixel unpacking/packing parameters are observed according to packing.
Parameters
dimensions either 1, 2 or 3 to indicate dimensionality of image
packing the pixelstore attributes
image starting address of image data
width the image width
height the image height
format the pixel format (must be validated beforehand)
type the pixel data type (must be validated beforehand)
img which image in the volume (0 for 1D or 2D images)
row row of pixel in the image (0 for 1D images)
column column of pixel in the image
Returns
address of pixel.
See also
gl_pixelstore_attrib.
References _mesa_image_offset().
Referenced by _mesa_image_address1d(), _mesa_image_address2d(), _mesa_image_address3d(), _mesa_memcpy_texture(), _mesa_texstore_s8(), _mesa_texstore_s8_z24(), _mesa_texstore_x8_z24(), _mesa_texstore_z16(), _mesa_texstore_z24_s8(), _mesa_texstore_z24_x8(), _mesa_texstore_z32(), _mesa_texstore_z32f_x24s8(), _mesa_unpack_color_index_to_rgba_float(), _mesa_unpack_image(), get_tex_depth(), get_tex_depth_stencil(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_stencil(), get_tex_ycbcr(), and texstore_rgba().
_mesa_image_address1d()
GLvoid* _mesa_image_address1d (const struct gl_pixelstore_attrib * packing, const GLvoid * image, GLsizei width, GLenum format, GLenum type, GLint column)
References _mesa_image_address().
_mesa_image_address2d()
GLvoid* _mesa_image_address2d (const struct gl_pixelstore_attrib * packing, const GLvoid * image, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint row, GLint column)
References _mesa_image_address().
Referenced by _mesa_expand_bitmap(), _mesa_pack_bitmap(), _mesa_texstore_bptc_rgba_unorm(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgb_fxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_texstore_rgba_fxt1(), get_tex_memcpy(), read_depth_pixels(), read_depth_stencil_pixels(), read_rgba_pixels(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), and texstore_bptc_rgb_float().
_mesa_image_address3d()
GLvoid* _mesa_image_address3d (const struct gl_pixelstore_attrib * packing, const GLvoid * image, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint img, GLint row, GLint column)
References _mesa_image_address().
_mesa_image_image_stride()
GLint _mesa_image_image_stride (const struct gl_pixelstore_attrib * packing, GLint width, GLint height, GLenum format, GLenum type)
References _mesa_bytes_per_pixel(), gl_pixelstore_attrib::Alignment, gl_pixelstore_attrib::ImageHeight, and gl_pixelstore_attrib::RowLength.
Referenced by _mesa_memcpy_texture(), get_texture_image(), store_texsubimage(), texstore_rgba(), and texturesubimage().
_mesa_image_offset()
GLintptr _mesa_image_offset (GLuint dimensions, const struct gl_pixelstore_attrib * packing, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint img, GLint row, GLint column)
Return the byte offset of a specific pixel in an image (1D, 2D or 3D).
Pixel unpacking/packing parameters are observed according to packing.
Parameters
dimensions either 1, 2 or 3 to indicate dimensionality of image
packing the pixelstore attributes
width the image width
height the image height
format the pixel format (must be validated beforehand)
type the pixel data type (must be validated beforehand)
img which image in the volume (0 for 1D or 2D images)
row row of pixel in the image (0 for 1D images)
column column of pixel in the image
Returns
offset of pixel.
See also
gl_pixelstore_attrib.
References _mesa_bytes_per_pixel(), gl_pixelstore_attrib::Alignment, bytes_per_pixel(), if(), gl_pixelstore_attrib::ImageHeight, gl_pixelstore_attrib::Invert, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipImages, gl_pixelstore_attrib::SkipPixels, and gl_pixelstore_attrib::SkipRows.
Referenced by _mesa_image_address(), and _mesa_validate_pbo_access().
_mesa_image_row_stride()
GLint _mesa_image_row_stride (const struct gl_pixelstore_attrib * packing, GLint width, GLenum format, GLenum type)
Compute the stride (in bytes) between image rows.
Parameters
packing the pixelstore attributes
width image width.
format pixel format.
type pixel data type.
Returns
the stride in bytes for the given parameters, or -1 if error
References _mesa_bytes_per_pixel(), gl_pixelstore_attrib::Alignment, gl_pixelstore_attrib::Invert, and gl_pixelstore_attrib::RowLength.
Referenced by _mesa_expand_bitmap(), _mesa_memcpy_texture(), _mesa_swap_bytes_2d_image(), _mesa_texstore_bptc_rgba_unorm(), _mesa_texstore_rgb_fxt1(), _mesa_texstore_rgba_fxt1(), _mesa_texstore_s8(), _mesa_texstore_s8_z24(), _mesa_texstore_z24_s8(), _mesa_texstore_z32f_x24s8(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), read_depth_pixels(), read_depth_stencil_pixels(), read_rgba_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), store_texsubimage(), texstore_bptc_rgb_float(), and texstore_rgba().
_mesa_swap2()
void _mesa_swap2 (GLushort * p, GLuint n)
References swap2_copy().
Referenced by _mesa_pack_depth_span(), _mesa_pack_stencil_span(), _mesa_texstore_ycbcr(), _mesa_unpack_image(), and get_tex_ycbcr().
_mesa_swap4()
void _mesa_swap4 (GLuint * p, GLuint n)
References swap4_copy().
Referenced by _mesa_pack_depth_span(), _mesa_pack_depth_stencil_span(), _mesa_pack_stencil_span(), _mesa_unpack_image(), and get_tex_depth_stencil().
_mesa_swap_bytes_2d_image()
void _mesa_swap_bytes_2d_image (GLenum format, GLenum type, const struct gl_pixelstore_attrib * packing, GLsizei width, GLsizei height, GLvoid * dst, const GLvoid * src)
Swap the bytes in a 2D image.
using the packing information this swaps the bytes according to the format and type of data being input. It takes into a/c various packing parameters like Alignment and RowLength.
References _mesa_bytes_per_pixel(), _mesa_image_row_stride(), _mesa_sizeof_packed_type(), GLuint, GLushort, swap2_copy(), swap4_copy(), and gl_pixelstore_attrib::SwapBytes.
Referenced by get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), read_rgba_pixels(), and texstore_rgba().
clip_left_or_bottom()
static void clip_left_or_bottom (GLint * srcX0, GLint * srcX1, GLint * dstX0, GLint * dstX1, GLint minValue) inline static
Clip dst coords against Xmin (or Ymin).
References F.
Referenced by _mesa_clip_blit().
clip_right_or_top()
static void clip_right_or_top (GLint * srcX0, GLint * srcX1, GLint * dstX0, GLint * dstX1, GLint maxValue) inline static
Clip dst coords against Xmax (or Ymax).
References F.
Referenced by _mesa_clip_blit().
swap2_copy()
static void swap2_copy (GLushort * dst, GLushort * src, GLuint n) static
Flip the order of the 2 bytes in each word in the given array (src) and store the result in another array (dst).
For in-place byte-swapping this function can be called with the same array for src and dst.
Parameters
dst the array where byte-swapped data will be stored.
src the array with the source data we want to byte-swap.
n number of words.
References GLuint.
Referenced by _mesa_swap2(), and _mesa_swap_bytes_2d_image().
swap4_copy()
static void swap4_copy (GLuint * dst, GLuint * src, GLuint n) static
References GLuint.
Referenced by _mesa_swap4(), and _mesa_swap_bytes_2d_image().