Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
imports.h File Reference
Standard C library function wrappers.
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "compiler.h"
#include "glheader.h"
#include "errors.h"
#include "util/bitscan.h"
Data Structures
union fi_type
Sometimes we treat GLfloats as GLints.
Macros
#define ADD_POINTERS(A, B) ((GLubyte *) (A) + (uintptr_t) (B))
#define IS_INF_OR_NAN(x) (!finite(x))
finite macro.
#define MALLOC_STRUCT(T) (struct T *) malloc(sizeof(struct T))
Memory macros.
#define CALLOC_STRUCT(T) (struct T *) calloc(1, sizeof(struct T))
Allocate and zero a structure of type T.
Functions
static GLfloat LOG2 (GLfloat x)
static int IROUND (float f)
Convert float to int by rounding to nearest integer, away from zero.
static int IROUNDD (double d)
Convert double to int by rounding to nearest integer, away from zero.
static GLint64 IROUND64 (float f)
Convert float to int64 by rounding to nearest integer.
static int IROUND_POS (float f)
Convert positive float to int by rounding to nearest integer.
static int IFLOOR (float f)
Return (as an integer) floor of float.
static int _mesa_is_pow_two (int x)
Is x a power of two?
static int32_t _mesa_next_pow_two_32 (uint32_t x)
Round given integer to next higer power of two If X is zero result is undefined.
static int64_t _mesa_next_pow_two_64 (uint64_t x)
static GLuint _mesa_logbase2 (GLuint n)
static GLboolean _mesa_little_endian (void)
Return 1 if this is a little endian machine, 0 if big endian.
void * _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
void * _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
void _mesa_align_free (void *ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
void * _mesa_align_realloc (void *oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
void * _mesa_exec_malloc (GLuint size)
void _mesa_exec_free (void *addr)
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
static bool _mesa_half_is_negative (GLhalfARB h)
int _mesa_snprintf (char *str, size_t size, const char *fmt,...) PRINTFLIKE(3
int int _mesa_vsnprintf (char *str, size_t size, const char *fmt, va_list arg)
Needed due to #ifdef's, above.
Detailed Description
Standard C library function wrappers.
This file provides wrappers for all the standard C library functions like malloc(), free(), printf(), getenv(), etc.
Macro Definition Documentation
ADD_POINTERS
#define ADD_POINTERS (A, B) ((GLubyte *) (A) + (uintptr_t) (B))
Referenced by _ae_ArrayElement(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetTexSubImage_sw(), _mesa_map_pbo_dest(), _mesa_map_pbo_source(), _mesa_validate_pbo_compressed_teximage(), _mesa_validate_pbo_teximage(), and unpack_image().
CALLOC_STRUCT
#define CALLOC_STRUCT (T) (struct T *) calloc(1, sizeof(struct T))
Allocate and zero a structure of type T.
Referenced by _mesa_alloc_shared_state(), _mesa_create_framebuffer(), _mesa_create_visual(), _mesa_init_display_list(), _mesa_new_ati_fragment_shader(), _mesa_new_framebuffer(), _mesa_new_query_object(), _mesa_new_renderbuffer(), _mesa_new_sampler_object(), _mesa_new_sync_object(), _mesa_new_vao(), _mesa_NewHashTable(), _mesa_PushAttrib(), _mesa_PushClientAttrib(), debug_create(), init_array_attrib_data(), make_list(), new_transform_feedback(), and register_surface().
IS_INF_OR_NAN
#define IS_INF_OR_NAN (x) (!finite(x))
finite macro.
MALLOC_STRUCT
#define MALLOC_STRUCT (T) (struct T *) malloc(sizeof(struct T))
Memory macros.
Allocate a structure of type T
Referenced by _mesa_new_buffer_object(), _mesa_new_texture_object(), _mesa_PushAttrib(), and save_attrib_data().
Function Documentation
_mesa_align_calloc()
void* _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
References _mesa_align_malloc(), and void.
Referenced by _mesa_little_endian().
_mesa_align_free()
void _mesa_align_free (void * ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
Parameters
ptr pointer to the memory to be freed. The actual address to free is stored in the word immediately before the address the client sees. Note that it is legal to pass NULL pointer to this function and will be handled accordingly.
Referenced by _mesa_align_realloc(), _mesa_delete_buffer_object(), _mesa_little_endian(), and buffer_data_fallback().
_mesa_align_malloc()
void* _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
Parameters
bytes number of bytes to allocate.
alignment alignment (must be greater than zero).
Allocates extra memory to accommodate rounding up the address for alignment and to record the real malloc address.
See also
_mesa_align_free().
Referenced by _mesa_align_calloc(), _mesa_align_realloc(), _mesa_little_endian(), and buffer_data_fallback().
_mesa_align_realloc()
void* _mesa_align_realloc (void * oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
References _mesa_align_free(), _mesa_align_malloc(), and void.
Referenced by _mesa_little_endian().
_mesa_bitcount()
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
Referenced by _mesa_drawbuffers(), _mesa_little_endian(), and draw_buffers().
_mesa_bitcount_64()
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
Referenced by _mesa_little_endian().
_mesa_exec_free()
void _mesa_exec_free (void * addr)
References mem_block::free.
Referenced by _mesa_little_endian().
_mesa_exec_malloc()
void* _mesa_exec_malloc (GLuint size)
Referenced by _mesa_little_endian().
_mesa_half_is_negative()
static bool _mesa_half_is_negative (GLhalfARB h) inline static
References _mesa_snprintf(), and _mesa_vsnprintf().
Referenced by _mesa_half_to_unsigned().
_mesa_is_pow_two()
static int _mesa_is_pow_two (int x) inline static
Is x a power of two?
Referenced by _mesa_legal_texture_dimensions(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), ALIGN(), and ROUND_DOWN_TO().
_mesa_little_endian()
static GLboolean _mesa_little_endian (void) inline static
Return 1 if this is a little endian machine, 0 if big endian.
References _mesa_align_calloc(), _mesa_align_free(), _mesa_align_malloc(), _mesa_align_realloc(), _mesa_bitcount(), _mesa_bitcount_64(), _mesa_exec_free(), _mesa_exec_malloc(), and GLuint.
Referenced by _mesa_format_matches_format_and_type(), _mesa_format_to_array(), _mesa_format_to_array_format(), _mesa_texstore_bptc_rgba_unorm(), _mesa_texstore_rg_rgtc2(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_texstore_rgba_fxt1(), _mesa_texstore_ycbcr(), and format_array_format_table_init().
_mesa_logbase2()
static GLuint _mesa_logbase2 (GLuint n) inline static
References GLuint.
Referenced by _mesa_get_tex_max_num_levels(), and init_teximage_fields_ms().
_mesa_next_pow_two_32()
static int32_t _mesa_next_pow_two_32 (uint32_t x) inline static
Round given integer to next higer power of two If X is zero result is undefined.
Source for the fallback implementation is Sean Eron Anderson's webpage "Bit Twiddling Hacks" http://graphics.stanford.edu/~seander/bithacks.html
When using builtin function have to do some work for case when passed values 1 to prevent hiting undefined result from __builtin_clz. Undefined results would be different depending on optimization level used for build.
References x.
_mesa_next_pow_two_64()
static int64_t _mesa_next_pow_two_64 (uint64_t x) inline static
References GLuint, and x.
_mesa_snprintf()
int _mesa_snprintf (char * str, size_t size, const char * fmt, ...)
Referenced by _mesa_half_is_negative().
_mesa_vsnprintf()
int int _mesa_vsnprintf (char * str, size_t size, const char * fmt, va_list args)
Needed due to #ifdef's, above.
Referenced by _mesa_debug(), _mesa_error(), _mesa_gl_vdebug(), _mesa_half_is_negative(), _mesa_log(), _mesa_problem(), and _mesa_warning().
IFLOOR()
static int IFLOOR (float f) inline static
Return (as an integer) floor of float.
References bf, fi_type::f, and fi_type::i.
Referenced by _mesa_Bitmap().
IROUND()
static int IROUND (float f) inline static
Convert float to int by rounding to nearest integer, away from zero.
References F.
Referenced by _mesa_CopyPixels(), _mesa_DrawPixels(), _mesa_GetIntegeri_v(), _mesa_GetIntegerv(), _mesa_GetMaterialiv(), _mesa_GetnMapivARB(), _mesa_GetSamplerParameteriv(), _mesa_PixelStoref(), get_tex_parameteriv(), and store_pixelmap().
IROUND64()
static GLint64 IROUND64 (float f) inline static
Convert float to int64 by rounding to nearest integer.
References F.
Referenced by _mesa_GetInteger64v().
IROUND_POS()
static int IROUND_POS (float f) inline static
Convert positive float to int by rounding to nearest integer.
References F.
IROUNDD()
static int IROUNDD (double d) inline static
Convert double to int by rounding to nearest integer, away from zero.
LOG2()
static GLfloat LOG2 (GLfloat x) inline static
References fi_type::f, GLuint, fi_type::i, and x.