Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
imports.c File Reference
Standard C library function wrappers.
#include <stdio.h>
#include <stdarg.h>
#include "c99_math.h"
#include "util/rounding.h"
#include "imports.h"
#include "context.h"
#include "mtypes.h"
#include "version.h"
Functions
int _mesa_vsnprintf (char *str, size_t size, const char *fmt, va_list args)
Needed due to #ifdef's, above.
int _mesa_snprintf (char *str, size_t size, const char *fmt,...)
Wrapper around vsnprintf()
Memory
void * _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
void * _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
void _mesa_align_free (void *ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
void * _mesa_align_realloc (void *oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
Math
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
Detailed Description
Standard C library function wrappers.
Imports are services which the device driver or window system or operating system provides to the core renderer. The core renderer (Mesa) will call these functions in order to do memory allocation, simple I/O, etc.
Some drivers will want to override/replace this file with something specialized, but that'll be rare.
Eventually, I want to move roll the glheader.h file into this.
Todo:
Functions still needed:
scanf
qsort
rand and RAND_MAX
Function Documentation
_mesa_align_calloc()
void* _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
References _mesa_align_malloc(), and void.
Referenced by _mesa_little_endian().
_mesa_align_free()
void _mesa_align_free (void * ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
Parameters
ptr pointer to the memory to be freed. The actual address to free is stored in the word immediately before the address the client sees. Note that it is legal to pass NULL pointer to this function and will be handled accordingly.
Referenced by _mesa_align_realloc(), _mesa_delete_buffer_object(), _mesa_little_endian(), and buffer_data_fallback().
_mesa_align_malloc()
void* _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
Parameters
bytes number of bytes to allocate.
alignment alignment (must be greater than zero).
Allocates extra memory to accommodate rounding up the address for alignment and to record the real malloc address.
See also
_mesa_align_free().
Referenced by _mesa_align_calloc(), _mesa_align_realloc(), _mesa_little_endian(), and buffer_data_fallback().
_mesa_align_realloc()
void* _mesa_align_realloc (void * oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
References _mesa_align_free(), _mesa_align_malloc(), and void.
Referenced by _mesa_little_endian().
_mesa_bitcount()
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
Referenced by _mesa_drawbuffers(), _mesa_little_endian(), and draw_buffers().
_mesa_bitcount_64()
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
Referenced by _mesa_little_endian().
_mesa_snprintf()
int _mesa_snprintf (char * str, size_t size, const char * fmt, ...)
Wrapper around vsnprintf()
Referenced by _mesa_error(), _mesa_write_renderbuffer_image(), create_version_string(), execute_list(), flush_delayed_errors(), output_if_debug(), texture_error_check(), and write_texture_image().
_mesa_vsnprintf()
int _mesa_vsnprintf (char * str, size_t size, const char * fmt, va_list args)
Needed due to #ifdef's, above.
Referenced by _mesa_debug(), _mesa_error(), _mesa_gl_vdebug(), _mesa_half_is_negative(), _mesa_log(), _mesa_problem(), and _mesa_warning().