Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
light.c File Reference
#include "c99_math.h"
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "enums.h"
#include "light.h"
#include "macros.h"
#include "mtypes.h"
#include "math/m_matrix.h"
#include "util/bitscan.h"
Functions
void GLAPIENTRY _mesa_ShadeModel (GLenum mode)
void GLAPIENTRY _mesa_ProvokingVertex (GLenum mode)
Set the provoking vertex (the vertex which specifies the prim's color when flat shading) to either the first or last vertex of the triangle or line.
void _mesa_light (struct gl_context *ctx, GLuint lnum, GLenum pname, const GLfloat *params)
Helper function called by _mesa_Lightfv and _mesa_PopAttrib to set per-light state.
void GLAPIENTRY _mesa_Lightf (GLenum light, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_Lightfv (GLenum light, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_Lighti (GLenum light, GLenum pname, GLint param)
void GLAPIENTRY _mesa_Lightiv (GLenum light, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_GetLightfv (GLenum light, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetLightiv (GLenum light, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_LightModelfv (GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_LightModeliv (GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_LightModeli (GLenum pname, GLint param)
void GLAPIENTRY _mesa_LightModelf (GLenum pname, GLfloat param)
GLuint _mesa_material_bitmask (struct gl_context *ctx, GLenum face, GLenum pname, GLuint legal, const char *where)
void _mesa_update_material (struct gl_context *ctx, GLuint bitmask)
void _mesa_update_color_material (struct gl_context *ctx, const GLfloat color[4])
void GLAPIENTRY _mesa_ColorMaterial (GLenum face, GLenum mode)
void GLAPIENTRY _mesa_GetMaterialfv (GLenum face, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetMaterialiv (GLenum face, GLenum pname, GLint *params)
void _mesa_update_lighting (struct gl_context *ctx)
Examine current lighting parameters to determine if the optimized lighting function can be used.
static void compute_light_positions (struct gl_context *ctx)
Update state derived from light position, spot direction.
static void update_modelview_scale (struct gl_context *ctx)
void _mesa_update_tnl_spaces (struct gl_context *ctx, GLuint new_state)
Bring up to date any state that relies on _NeedEyeCoords.
void _mesa_allow_light_in_model (struct gl_context *ctx, GLboolean flag)
Drivers may need this if the hardware tnl unit doesn't support the light-in-modelspace optimization.
static void init_light (struct gl_light *l, GLuint n)
Initialize the n-th light data structure.
static void init_lightmodel (struct gl_lightmodel *lm)
Initialize the light model data structure.
static void init_material (struct gl_material *m)
Initialize the material data structure.
void _mesa_init_lighting (struct gl_context *ctx)
Initialize all lighting state for the given context.
Function Documentation
_mesa_allow_light_in_model()
void _mesa_allow_light_in_model (struct gl_context * ctx, GLboolean flag)
Drivers may need this if the hardware tnl unit doesn't support the light-in-modelspace optimization.
It's also useful for debugging.
References gl_context::_ForceEyeCoords, _NEW_POINT, and gl_context::NewState.
_mesa_ColorMaterial()
void GLAPIENTRY _mesa_ColorMaterial (GLenum face, GLenum mode)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_material_bitmask(), _mesa_update_color_material(), _NEW_LIGHT, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_SPECULAR, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_GetLightfv()
void GLAPIENTRY _mesa_GetLightfv (GLenum light, GLenum pname, GLfloat * params)
References _mesa_error(), COPY_3V, COPY_4V, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetLightxv().
_mesa_GetLightiv()
void GLAPIENTRY _mesa_GetLightiv (GLenum light, GLenum pname, GLint * params)
References _mesa_error(), FLOAT_TO_INT, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetMaterialfv()
void GLAPIENTRY _mesa_GetMaterialfv (GLenum face, GLenum pname, GLfloat * params)
References _mesa_error(), API_OPENGL_COMPAT, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MAT_ATTRIB_AMBIENT, MAT_ATTRIB_DIFFUSE, MAT_ATTRIB_EMISSION, MAT_ATTRIB_INDEXES, MAT_ATTRIB_SHININESS, and MAT_ATTRIB_SPECULAR.
Referenced by _mesa_GetMaterialxv().
_mesa_GetMaterialiv()
void GLAPIENTRY _mesa_GetMaterialiv (GLenum face, GLenum pname, GLint * params)
References _mesa_error(), API_OPENGL_COMPAT, FLOAT_TO_INT, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, IROUND(), MAT_ATTRIB_AMBIENT, MAT_ATTRIB_DIFFUSE, MAT_ATTRIB_EMISSION, MAT_ATTRIB_INDEXES, MAT_ATTRIB_SHININESS, and MAT_ATTRIB_SPECULAR.
_mesa_init_lighting()
void _mesa_init_lighting (struct gl_context * ctx)
Initialize all lighting state for the given context.
References gl_light_attrib::_ClampVertexColor, gl_light_attrib::_ColorMaterialBitmask, gl_light_attrib::_EnabledLights, gl_context::_ForceEyeCoords, _mesa_material_bitmask(), gl_context::_ModelViewInvScale, gl_light_attrib::_NeedEyeCoords, gl_context::_NeedEyeCoords, gl_context::API, API_OPENGL_COMPAT, gl_light_attrib::ClampVertexColor, gl_light_attrib::ColorMaterialEnabled, gl_light_attrib::ColorMaterialFace, gl_light_attrib::ColorMaterialMode, gl_light_attrib::Enabled, GLuint, init_light(), init_lightmodel(), init_material(), gl_light_attrib::Light, gl_context::Light, gl_light_attrib::Material, MAX_LIGHTS, gl_light_attrib::Model, gl_light_attrib::ProvokingVertex, and gl_light_attrib::ShadeModel.
Referenced by init_attrib_groups().
_mesa_light()
void _mesa_light (struct gl_context * ctx, GLuint lnum, GLenum pname, const GLfloat * params)
Helper function called by _mesa_Lightfv and _mesa_PopAttrib to set per-light state.
For GL_POSITION and GL_SPOT_DIRECTION the params position/direction will have already been transformed by the modelview matrix! Also, all error checking should have already been done.
References gl_light::_CosCutoff, gl_light::_Flags, _mesa_problem(), _NEW_LIGHT, gl_light::Ambient, gl_context::Const, gl_light::ConstantAttenuation, COPY_3V, COPY_4V, gl_light::Diffuse, gl_context::Driver, gl_light::EyePosition, F, FLUSH_VERTICES, GLAPIENTRY, gl_light_attrib::Light, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, dd_function_table::Lightfv, gl_light::LinearAttenuation, MAX_LIGHTS, gl_constants::MaxSpotExponent, gl_light::QuadraticAttenuation, gl_light::Specular, gl_light::SpotCutoff, gl_light::SpotDirection, gl_light::SpotExponent, TEST_EQ_3V, and TEST_EQ_4V.
Referenced by _mesa_Lightfv(), and _mesa_PopAttrib().
_mesa_Lightf()
void GLAPIENTRY _mesa_Lightf (GLenum light, GLenum pname, GLfloat param)
References _mesa_Lightfv(), and GLAPIENTRY.
Referenced by _mesa_Lightx().
_mesa_Lightfv()
void GLAPIENTRY _mesa_Lightfv (GLenum light, GLenum pname, const GLfloat * params)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_error(), _mesa_light(), F, GET_CURRENT_CONTEXT, GLAPIENTRY, TRANSFORM_DIRECTION, and TRANSFORM_POINT.
Referenced by _mesa_Lightf(), _mesa_Lightiv(), and _mesa_Lightxv().
_mesa_Lighti()
void GLAPIENTRY _mesa_Lighti (GLenum light, GLenum pname, GLint param)
References _mesa_Lightiv(), and GLAPIENTRY.
_mesa_Lightiv()
void GLAPIENTRY _mesa_Lightiv (GLenum light, GLenum pname, const GLint * params)
References _mesa_Lightfv(), GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_Lighti().
_mesa_LightModelf()
void GLAPIENTRY _mesa_LightModelf (GLenum pname, GLfloat param)
References _mesa_LightModelfv(), and GLuint.
Referenced by _mesa_LightModelx(), and _mesa_PopAttrib().
_mesa_LightModelfv()
void GLAPIENTRY _mesa_LightModelfv (GLenum pname, const GLfloat * params)
References _mesa_error(), _NEW_LIGHT, API_OPENGL_COMPAT, COPY_4V, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and TEST_EQ_4V.
Referenced by _mesa_LightModelf(), _mesa_LightModeliv(), _mesa_LightModelxv(), and _mesa_PopAttrib().
_mesa_LightModeli()
void GLAPIENTRY _mesa_LightModeli (GLenum pname, GLint param)
References _mesa_LightModeliv(), and GLAPIENTRY.
_mesa_LightModeliv()
void GLAPIENTRY _mesa_LightModeliv (GLenum pname, const GLint * params)
References _mesa_LightModelfv(), F, GLAPIENTRY, and INT_TO_FLOAT.
Referenced by _mesa_LightModeli().
_mesa_material_bitmask()
GLuint _mesa_material_bitmask (struct gl_context * ctx, GLenum face, GLenum pname, GLuint legal, const char * where)
References _mesa_error(), BACK_MATERIAL_BITS, FRONT_MATERIAL_BITS, GLuint, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_INDEXES, MAT_BIT_BACK_SHININESS, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_INDEXES, MAT_BIT_FRONT_SHININESS, and MAT_BIT_FRONT_SPECULAR.
Referenced by _mesa_ColorMaterial(), _mesa_init_lighting(), and save_Materialfv().
_mesa_ProvokingVertex()
void GLAPIENTRY _mesa_ProvokingVertex (GLenum mode)
Set the provoking vertex (the vertex which specifies the prim's color when flat shading) to either the first or last vertex of the triangle or line.
References _mesa_debug(), _mesa_error(), _NEW_LIGHT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by save_ProvokingVertexEXT().
_mesa_ShadeModel()
void GLAPIENTRY _mesa_ShadeModel (GLenum mode)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_LIGHT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_update_color_material()
void _mesa_update_color_material (struct gl_context * ctx, const GLfloat color[4])
References gl_light_attrib::_ColorMaterialBitmask, _mesa_update_material(), gl_material::Attrib, GLAPIENTRY, gl_context::Light, and gl_light_attrib::Material.
Referenced by _mesa_ColorMaterial(), and _mesa_set_enable().
_mesa_update_lighting()
void _mesa_update_lighting (struct gl_context * ctx)
Examine current lighting parameters to determine if the optimized lighting function can be used.
Also, precompute some lighting values such as the products of light source and material ambient, diffuse and specular coefficients.
References gl_light_attrib::_EnabledLights, gl_light::_Flags, _mesa_update_material(), gl_light_attrib::_NeedEyeCoords, gl_light_attrib::_NeedVertices, gl_lightmodel::ColorControl, gl_light_attrib::Enabled, gl_light_attrib::Light, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, gl_lightmodel::LocalViewer, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_SPECULAR, gl_light_attrib::Model, and gl_lightmodel::TwoSide.
Referenced by _mesa_update_state_locked().
_mesa_update_material()
void _mesa_update_material (struct gl_context * ctx, GLuint bitmask)
References gl_light_attrib::_BaseColor, gl_light_attrib::_EnabledLights, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, _mesa_debug(), ACC_SCALE_3V, gl_light::Ambient, gl_lightmodel::Ambient, gl_material::Attrib, COPY_3V, gl_light::Diffuse, gl_light_attrib::Light, gl_context::Light, MAT_ATTRIB_BACK_AMBIENT, MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_BACK_EMISSION, MAT_ATTRIB_BACK_SPECULAR, MAT_ATTRIB_FRONT_AMBIENT, MAT_ATTRIB_FRONT_DIFFUSE, MAT_ATTRIB_FRONT_EMISSION, MAT_ATTRIB_FRONT_SPECULAR, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_SPECULAR, gl_light_attrib::Material, MESA_VERBOSE, gl_light_attrib::Model, SCALE_3V, gl_light::Specular, and VERBOSE_MATERIAL.
Referenced by _mesa_update_color_material(), and _mesa_update_lighting().
_mesa_update_tnl_spaces()
void _mesa_update_tnl_spaces (struct gl_context * ctx, GLuint new_state)
Bring up to date any state that relies on _NeedEyeCoords.
References gl_point_attrib::_Attenuated, gl_context::_ForceEyeCoords, gl_texture_attrib::_GenFlags, _math_matrix_is_length_preserving(), gl_light_attrib::_NeedEyeCoords, gl_context::_NeedEyeCoords, _NEW_LIGHT, _NEW_MODELVIEW, compute_light_positions(), gl_context::Driver, gl_light_attrib::Enabled, GLuint, if(), gl_context::Light, dd_function_table::LightingSpaceChange, gl_context::ModelviewMatrixStack, gl_context::NewState, gl_context::Point, TEXGEN_NEED_EYE_COORD, gl_context::Texture, gl_matrix_stack::Top, update_modelview_scale(), and void.
Referenced by _mesa_update_state_locked().
compute_light_positions()
static void compute_light_positions (struct gl_context * ctx) static
Update state derived from light position, spot direction.
Called upon: _NEW_MODELVIEW _NEW_LIGHT _TNL_NEW_NEED_EYE_COORDS
Update on (_NEW_MODELVIEW | _NEW_LIGHT) when lighting is enabled. Also update on lighting space changes.
References gl_light::_CosCutoff, gl_light_attrib::_EnabledLights, gl_context::_EyeZDir, gl_light::_Flags, gl_light::_h_inf_norm, gl_context::_NeedEyeCoords, gl_light::_NormSpotDirection, gl_light::_Position, gl_light::_VP_inf_norm, gl_light::_VP_inf_spot_attenuation, ADD_3V, COPY_3V, DOT3(), gl_light_attrib::Enabled, gl_light::EyePosition, GLmatrix::inv, gl_light_attrib::Light, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, gl_lightmodel::LocalViewer, GLmatrix::m, gl_light_attrib::Model, gl_context::ModelviewMatrixStack, NORMALIZE_3FV(), gl_light::SpotDirection, gl_light::SpotExponent, gl_matrix_stack::Top, TRANSFORM_NORMAL, and TRANSFORM_POINT.
Referenced by _mesa_update_tnl_spaces().
init_light()
static void init_light (struct gl_light * l, GLuint n) static
Initialize the n-th light data structure.
Parameters
l pointer to the gl_light structure to be initialized.
n number of the light.
Note
The defaults for light 0 are different than the other lights.
References gl_light::_CosCutoff, gl_light::Ambient, ASSIGN_3V, gl_light::ConstantAttenuation, gl_light::Diffuse, gl_light::Enabled, gl_light::EyePosition, gl_light::LinearAttenuation, gl_light::QuadraticAttenuation, gl_light::Specular, gl_light::SpotCutoff, gl_light::SpotDirection, and gl_light::SpotExponent.
Referenced by _mesa_init_lighting().
init_lightmodel()
static void init_lightmodel (struct gl_lightmodel * lm) static
Initialize the light model data structure.
Parameters
lm pointer to the gl_lightmodel structure to be initialized.
References gl_lightmodel::Ambient, gl_lightmodel::ColorControl, gl_lightmodel::LocalViewer, and gl_lightmodel::TwoSide.
Referenced by _mesa_init_lighting().
init_material()
static void init_material (struct gl_material * m) static
Initialize the material data structure.
Parameters
m pointer to the gl_material structure to be initialized.
References gl_material::Attrib, MAT_ATTRIB_BACK_AMBIENT, MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_BACK_EMISSION, MAT_ATTRIB_BACK_INDEXES, MAT_ATTRIB_BACK_SHININESS, MAT_ATTRIB_BACK_SPECULAR, MAT_ATTRIB_FRONT_AMBIENT, MAT_ATTRIB_FRONT_DIFFUSE, MAT_ATTRIB_FRONT_EMISSION, MAT_ATTRIB_FRONT_INDEXES, MAT_ATTRIB_FRONT_SHININESS, and MAT_ATTRIB_FRONT_SPECULAR.
Referenced by _mesa_init_lighting().
update_modelview_scale()
static void update_modelview_scale (struct gl_context * ctx) static
References _math_matrix_is_length_preserving(), gl_context::_ModelViewInvScale, gl_context::_NeedEyeCoords, GLmatrix::inv, gl_context::ModelviewMatrixStack, and gl_matrix_stack::Top.
Referenced by _mesa_update_tnl_spaces().