Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lines.c File Reference
#include "glheader.h"
#include "context.h"
#include "lines.h"
#include "macros.h"
#include "mtypes.h"
Functions
void GLAPIENTRY _mesa_LineWidth (GLfloat width)
Set the line width.
void GLAPIENTRY _mesa_LineStipple (GLint factor, GLushort pattern)
Set the line stipple pattern.
void GLAPIENTRY _mesa_init_line (struct gl_context *ctx)
Initialize the context line state.
Function Documentation
_mesa_init_line()
void GLAPIENTRY _mesa_init_line (struct gl_context * ctx)
Initialize the context line state.
Parameters
ctx GL context.
Initializes __struct gl_contextRec::Line and line related constants in __struct gl_contextRec::Const.
References gl_context::Line, gl_line_attrib::SmoothFlag, gl_line_attrib::StippleFactor, gl_line_attrib::StippleFlag, gl_line_attrib::StipplePattern, and gl_line_attrib::Width.
Referenced by init_attrib_groups().
_mesa_LineStipple()
void GLAPIENTRY _mesa_LineStipple (GLint factor, GLushort pattern)
Set the line stipple pattern.
Parameters
factor pattern scale factor.
pattern bit pattern.
See also
glLineStipple().
Updates gl_line_attrib::StippleFactor and gl_line_attrib::StipplePattern. On change flushes the vertices and notifies the driver via the dd_function_table::LineStipple callback.
References _mesa_debug(), _NEW_LINE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_LineWidth()
void GLAPIENTRY _mesa_LineWidth (GLfloat width)
Set the line width.
Parameters
width line width in pixels.
See also
glLineWidth().
References _mesa_debug(), _mesa_error(), _NEW_LINE, API_OPENGL_CORE, F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_LineWidthx(), and _mesa_PopAttrib().