Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
marshal.h File Reference
Declarations of functions related to marshalling GL calls from a client thread to a server thread.
#include "main/glthread.h"
#include "main/context.h"
#include "main/macros.h"
Data Structures
struct marshal_cmd_base
Macros
#define DEBUG_MARSHAL_PRINT_CALLS 0
Functions
static void * _mesa_glthread_allocate_command (struct gl_context *ctx, uint16_t cmd_id, size_t size)
static bool _mesa_glthread_is_non_vbo_vertex_attrib_pointer (const struct gl_context *ctx)
static bool _mesa_glthread_is_non_vbo_draw_elements (const struct gl_context *ctx)
static void debug_print_sync_fallback (const char *func)
This is printed when we have fallen back to a sync.
static void debug_print_sync (const char *func)
static void debug_print_marshal (const char *func)
static void debug_print_unmarshal (const char *func)
struct _glapi_table * _mesa_create_marshal_table (const struct gl_context *ctx)
size_t _mesa_unmarshal_dispatch_cmd (struct gl_context *ctx, const void *cmd)
static void _mesa_post_marshal_hook (struct gl_context *ctx)
static bool _mesa_glthread_is_compat_bind_vertex_array (const struct gl_context *ctx)
Checks whether we're on a compat context for code-generated glBindVertexArray().
void _mesa_unmarshal_Enable (struct gl_context *ctx, const struct marshal_cmd_Enable *cmd)
void GLAPIENTRY _mesa_marshal_Enable (GLenum cap)
void GLAPIENTRY _mesa_marshal_ShaderSource (GLuint shader, GLsizei count, const GLchar *const *string, const GLint *length)
void _mesa_unmarshal_ShaderSource (struct gl_context *ctx, const struct marshal_cmd_ShaderSource *cmd)
void GLAPIENTRY _mesa_marshal_Flush (void)
void _mesa_unmarshal_Flush (struct gl_context *ctx, const struct marshal_cmd_Flush *cmd)
void GLAPIENTRY _mesa_marshal_BindBuffer (GLenum target, GLuint buffer)
void _mesa_unmarshal_BindBuffer (struct gl_context *ctx, const struct marshal_cmd_BindBuffer *cmd)
void _mesa_unmarshal_BufferData (struct gl_context *ctx, const struct marshal_cmd_BufferData *cmd)
void GLAPIENTRY _mesa_marshal_BufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
void _mesa_unmarshal_BufferSubData (struct gl_context *ctx, const struct marshal_cmd_BufferSubData *cmd)
void GLAPIENTRY _mesa_marshal_BufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data)
void _mesa_unmarshal_ClearBufferfv (struct gl_context *ctx, const struct marshal_cmd_ClearBufferfv *cmd)
void GLAPIENTRY _mesa_marshal_ClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat *value)
Detailed Description
Declarations of functions related to marshalling GL calls from a client thread to a server thread.
Macro Definition Documentation
DEBUG_MARSHAL_PRINT_CALLS
#define DEBUG_MARSHAL_PRINT_CALLS 0
Function Documentation
_mesa_create_marshal_table()
struct _glapi_table* _mesa_create_marshal_table (const struct gl_context * ctx)
Referenced by debug_print_unmarshal().
_mesa_glthread_allocate_command()
static void* _mesa_glthread_allocate_command (struct gl_context * ctx, uint16_t cmd_id, size_t size) inline static
_mesa_glthread_is_compat_bind_vertex_array()
static bool _mesa_glthread_is_compat_bind_vertex_array (const struct gl_context * ctx) inline static
Checks whether we're on a compat context for code-generated glBindVertexArray().
In order to decide whether a draw call uses only VBOs for vertex and index buffers, we track the current vertex and index buffer bindings by glBindBuffer(). However, the index buffer binding is stored in the vertex array as opposed to the context. If we were to accurately track whether the index buffer was a user pointer ot not, we'd have to track it per vertex array, which would mean synchronizing with the client thread and looking into the hash table to find the actual vertex array object. That's more tracking than we'd like to do in the main thread, if possible.
Instead, just punt for now and disable threading on apps using vertex arrays and compat contexts. Apps using vertex arrays can probably use a core context.
References _mesa_marshal_BindBuffer(), _mesa_marshal_BufferData(), _mesa_marshal_BufferSubData(), _mesa_marshal_ClearBufferfv(), _mesa_marshal_Enable(), _mesa_marshal_Flush(), _mesa_marshal_ShaderSource(), _mesa_unmarshal_BindBuffer(), _mesa_unmarshal_BufferData(), _mesa_unmarshal_BufferSubData(), _mesa_unmarshal_ClearBufferfv(), _mesa_unmarshal_Enable(), _mesa_unmarshal_Flush(), _mesa_unmarshal_ShaderSource(), gl_context::API, API_OPENGL_CORE, GLAPIENTRY, and GLuint.
_mesa_glthread_is_non_vbo_draw_elements()
static bool _mesa_glthread_is_non_vbo_draw_elements (const struct gl_context * ctx) inline static
_mesa_glthread_is_non_vbo_vertex_attrib_pointer()
static bool _mesa_glthread_is_non_vbo_vertex_attrib_pointer (const struct gl_context * ctx) inline static
_mesa_marshal_BindBuffer()
void GLAPIENTRY _mesa_marshal_BindBuffer (GLenum target, GLuint buffer)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_marshal_BufferData()
void GLAPIENTRY _mesa_marshal_BufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_marshal_BufferSubData()
void GLAPIENTRY _mesa_marshal_BufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_marshal_ClearBufferfv()
void GLAPIENTRY _mesa_marshal_ClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat * value)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_marshal_Enable()
void GLAPIENTRY _mesa_marshal_Enable (GLenum cap)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_marshal_Flush()
void GLAPIENTRY _mesa_marshal_Flush (void)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_marshal_ShaderSource()
void GLAPIENTRY _mesa_marshal_ShaderSource (GLuint shader, GLsizei count, const GLchar *const * string, const GLint * length)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_post_marshal_hook()
static void _mesa_post_marshal_hook (struct gl_context * ctx) inline static
References _mesa_glthread_finish().
_mesa_unmarshal_BindBuffer()
void _mesa_unmarshal_BindBuffer (struct gl_context * ctx, const struct marshal_cmd_BindBuffer * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_unmarshal_BufferData()
void _mesa_unmarshal_BufferData (struct gl_context * ctx, const struct marshal_cmd_BufferData * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_unmarshal_BufferSubData()
void _mesa_unmarshal_BufferSubData (struct gl_context * ctx, const struct marshal_cmd_BufferSubData * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_unmarshal_ClearBufferfv()
void _mesa_unmarshal_ClearBufferfv (struct gl_context * ctx, const struct marshal_cmd_ClearBufferfv * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_unmarshal_dispatch_cmd()
size_t _mesa_unmarshal_dispatch_cmd (struct gl_context * ctx, const void * cmd)
Referenced by debug_print_unmarshal().
_mesa_unmarshal_Enable()
void _mesa_unmarshal_Enable (struct gl_context * ctx, const struct marshal_cmd_Enable * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_unmarshal_Flush()
void _mesa_unmarshal_Flush (struct gl_context * ctx, const struct marshal_cmd_Flush * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
_mesa_unmarshal_ShaderSource()
void _mesa_unmarshal_ShaderSource (struct gl_context * ctx, const struct marshal_cmd_ShaderSource * cmd)
Referenced by _mesa_glthread_is_compat_bind_vertex_array().
debug_print_marshal()
static void debug_print_marshal (const char * func) inline static
debug_print_sync()
static void debug_print_sync (const char * func) inline static
debug_print_sync_fallback()
static void debug_print_sync_fallback (const char * func) inline static
This is printed when we have fallen back to a sync.
This can happen when MARSHAL_MAX_CMD_SIZE is exceeded.
debug_print_unmarshal()
static void debug_print_unmarshal (const char * func) inline static
References _mesa_create_marshal_table(), and _mesa_unmarshal_dispatch_cmd().