Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
matrix.c File Reference
Matrix operations.
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "enums.h"
#include "macros.h"
#include "matrix.h"
#include "mtypes.h"
#include "math/m_matrix.h"
#include "util/bitscan.h"
Functions
void GLAPIENTRY _mesa_Frustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval)
Apply a perspective projection matrix.
void GLAPIENTRY _mesa_Ortho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval)
Apply an orthographic projection matrix.
void GLAPIENTRY _mesa_MatrixMode (GLenum mode)
Set the current matrix stack.
void GLAPIENTRY _mesa_PushMatrix (void)
Push the current matrix stack.
void GLAPIENTRY _mesa_PopMatrix (void)
Pop the current matrix stack.
void GLAPIENTRY _mesa_LoadIdentity (void)
Replace the current matrix with the identity matrix.
void GLAPIENTRY _mesa_LoadMatrixf (const GLfloat *m)
Replace the current matrix with a given matrix.
void GLAPIENTRY _mesa_MultMatrixf (const GLfloat *m)
Multiply the current matrix with a given matrix.
void GLAPIENTRY _mesa_Rotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
Multiply the current matrix with a rotation matrix.
void GLAPIENTRY _mesa_Scalef (GLfloat x, GLfloat y, GLfloat z)
Multiply the current matrix with a general scaling matrix.
void GLAPIENTRY _mesa_Translatef (GLfloat x, GLfloat y, GLfloat z)
Multiply the current matrix with a translation matrix.
void GLAPIENTRY _mesa_LoadMatrixd (const GLdouble *m)
void GLAPIENTRY _mesa_MultMatrixd (const GLdouble *m)
void GLAPIENTRY _mesa_Rotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_Scaled (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_Translated (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_LoadTransposeMatrixf (const GLfloat *m)
void GLAPIENTRY _mesa_LoadTransposeMatrixd (const GLdouble *m)
void GLAPIENTRY _mesa_MultTransposeMatrixf (const GLfloat *m)
void GLAPIENTRY _mesa_MultTransposeMatrixd (const GLdouble *m)
State management
static void update_projection (struct gl_context *ctx)
Update the projection matrix stack.
static void calculate_model_project_matrix (struct gl_context *ctx)
Calculate the combined modelview-projection matrix.
void _mesa_update_modelview_project (struct gl_context *ctx, GLuint new_state)
Updates the combined modelview-projection matrix.
static void init_matrix_stack (struct gl_matrix_stack *stack, GLuint maxDepth, GLuint dirtyFlag)
Matrix stack initialization.
static void free_matrix_stack (struct gl_matrix_stack *stack)
Free matrix stack.
Initialization
void _mesa_init_matrix (struct gl_context *ctx)
Initialize the context matrix data.
void _mesa_free_matrix_data (struct gl_context *ctx)
Free the context matrix data.
void _mesa_init_transform (struct gl_context *ctx)
Initialize the context transform attribute group.
Detailed Description
Matrix operations.
Note
4x4 transformation matrices are stored in memory in column major order.
Points/vertices are to be thought of as column vectors.
Transformation of a point p by a matrix M is: p' = M * p
Function Documentation
_mesa_free_matrix_data()
void _mesa_free_matrix_data (struct gl_context * ctx)
Free the context matrix data.
Parameters
ctx GL context.
Frees each of the matrix stacks and the combined modelview-projection matrix.
References _math_matrix_dtr(), gl_context::_ModelProjectMatrix, free_matrix_stack(), GLuint, gl_context::ModelviewMatrixStack, gl_context::ProgramMatrixStack, gl_context::ProjectionMatrixStack, and gl_context::TextureMatrixStack.
Referenced by _mesa_free_context_data().
_mesa_Frustum()
void GLAPIENTRY _mesa_Frustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval)
Apply a perspective projection matrix.
Parameters
left left clipping plane coordinate.
right right clipping plane coordinate.
bottom bottom clipping plane coordinate.
top top clipping plane coordinate.
nearval distance to the near clipping plane.
farval distance to the far clipping plane.
See also
glFrustum().
Flushes vertices and validates parameters. Calls _math_matrix_frustum() with the top matrix of the current matrix stack and sets __struct gl_contextRec::NewState.
References _math_matrix_frustum(), _mesa_error(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_Frustumf(), and _mesa_Frustumx().
_mesa_init_matrix()
void _mesa_init_matrix (struct gl_context * ctx)
Initialize the context matrix data.
Parameters
ctx GL context.
Initializes each of the matrix stacks and the combined modelview-projection matrix.
References _math_matrix_ctr(), gl_context::_ModelProjectMatrix, _NEW_MODELVIEW, _NEW_PROJECTION, _NEW_TEXTURE_MATRIX, _NEW_TRACK_MATRIX, gl_context::CurrentStack, GLuint, init_matrix_stack(), MAX_MODELVIEW_STACK_DEPTH, MAX_PROGRAM_MATRIX_STACK_DEPTH, MAX_PROJECTION_STACK_DEPTH, MAX_TEXTURE_STACK_DEPTH, gl_context::ModelviewMatrixStack, gl_context::ProgramMatrixStack, gl_context::ProjectionMatrixStack, and gl_context::TextureMatrixStack.
Referenced by init_attrib_groups().
_mesa_init_transform()
void _mesa_init_transform (struct gl_context * ctx)
Initialize the context transform attribute group.
Parameters
ctx GL context.
Todo:
Move this to a new file with other 'transform' routines.
References gl_transform_attrib::ClipPlanesEnabled, gl_context::Const, gl_transform_attrib::EyeUserPlane, GLuint, gl_transform_attrib::MatrixMode, gl_constants::MaxClipPlanes, gl_transform_attrib::Normalize, gl_transform_attrib::RasterPositionUnclipped, gl_transform_attrib::RescaleNormals, and gl_context::Transform.
Referenced by init_attrib_groups().
_mesa_LoadIdentity()
void GLAPIENTRY _mesa_LoadIdentity (void)
Replace the current matrix with the identity matrix.
See also
glLoadIdentity().
Flushes the vertices and calls _math_matrix_set_identity() with the top-most matrix in the current stack. Marks __struct gl_contextRec::NewState with the stack dirty flag.
References _math_matrix_set_identity(), _mesa_debug(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_LoadMatrixd()
void GLAPIENTRY _mesa_LoadMatrixd (const GLdouble * m)
References _mesa_LoadMatrixf(), and GLAPIENTRY.
_mesa_LoadMatrixf()
void GLAPIENTRY _mesa_LoadMatrixf (const GLfloat * m)
Replace the current matrix with a given matrix.
Parameters
m matrix.
See also
glLoadMatrixf().
Flushes the vertices and calls _math_matrix_loadf() with the top-most matrix in the current stack and the given matrix. Marks __struct gl_contextRec::NewState with the dirty stack flag.
References _math_matrix_loadf(), _mesa_debug(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_LoadMatrixd(), _mesa_LoadMatrixx(), _mesa_LoadTransposeMatrixd(), and _mesa_LoadTransposeMatrixf().
_mesa_LoadTransposeMatrixd()
void GLAPIENTRY _mesa_LoadTransposeMatrixd (const GLdouble * m)
References _math_transposefd(), _mesa_LoadMatrixf(), and GLAPIENTRY.
_mesa_LoadTransposeMatrixf()
void GLAPIENTRY _mesa_LoadTransposeMatrixf (const GLfloat * m)
References _math_transposef(), _mesa_LoadMatrixf(), and GLAPIENTRY.
_mesa_MatrixMode()
void GLAPIENTRY _mesa_MatrixMode (GLenum mode)
Set the current matrix stack.
Parameters
mode matrix stack.
See also
glMatrixMode().
Flushes the vertices, validates the parameter and updates __struct gl_contextRec::CurrentStack and gl_transform_attrib::MatrixMode with the specified matrix stack.
References _mesa_error(), API_OPENGL_COMPAT, GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
Referenced by _mesa_PopAttrib().
_mesa_MultMatrixd()
void GLAPIENTRY _mesa_MultMatrixd (const GLdouble * m)
References _mesa_MultMatrixf(), and GLAPIENTRY.
_mesa_MultMatrixf()
void GLAPIENTRY _mesa_MultMatrixf (const GLfloat * m)
Multiply the current matrix with a given matrix.
Parameters
m matrix.
See also
glMultMatrixf().
Flushes the vertices and calls _math_matrix_mul_floats() with the top-most matrix in the current stack and the given matrix. Marks __struct gl_contextRec::NewState with the dirty stack flag.
References _math_matrix_mul_floats(), _mesa_debug(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_MultMatrixd(), _mesa_MultMatrixx(), _mesa_MultTransposeMatrixd(), and _mesa_MultTransposeMatrixf().
_mesa_MultTransposeMatrixd()
void GLAPIENTRY _mesa_MultTransposeMatrixd (const GLdouble * m)
References _math_transposefd(), and _mesa_MultMatrixf().
_mesa_MultTransposeMatrixf()
void GLAPIENTRY _mesa_MultTransposeMatrixf (const GLfloat * m)
References _math_transposef(), _mesa_MultMatrixf(), and GLAPIENTRY.
_mesa_Ortho()
void GLAPIENTRY _mesa_Ortho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearval, GLdouble farval)
Apply an orthographic projection matrix.
Parameters
left left clipping plane coordinate.
right right clipping plane coordinate.
bottom bottom clipping plane coordinate.
top top clipping plane coordinate.
nearval distance to the near clipping plane.
farval distance to the far clipping plane.
See also
glOrtho().
Flushes vertices and validates parameters. Calls _math_matrix_ortho() with the top matrix of the current matrix stack and sets __struct gl_contextRec::NewState.
References _math_matrix_ortho(), _mesa_debug(), _mesa_error(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_Orthof(), and _mesa_Orthox().
_mesa_PopMatrix()
void GLAPIENTRY _mesa_PopMatrix (void)
Pop the current matrix stack.
See also
glPopMatrix().
Flushes the vertices, verifies the current matrix stack is not empty, and moves the stack head down. Marks __struct gl_contextRec::NewState with the dirty stack flag.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), gl_matrix_stack::Depth, gl_matrix_stack::DirtyFlag, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, gl_matrix_stack::Stack, gl_matrix_stack::Top, and VERBOSE_API.
_mesa_PushMatrix()
void GLAPIENTRY _mesa_PushMatrix (void)
Push the current matrix stack.
See also
glPushMatrix().
Verifies the current matrix stack is not full, and duplicates the top-most matrix in the stack. Marks __struct gl_contextRec::NewState with the stack dirty flag.
References _math_matrix_copy(), _math_matrix_ctr(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), gl_matrix_stack::Depth, gl_matrix_stack::DirtyFlag, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_matrix_stack::MaxDepth, MESA_VERBOSE, gl_matrix_stack::Stack, gl_matrix_stack::StackSize, gl_matrix_stack::Top, and VERBOSE_API.
_mesa_Rotated()
void GLAPIENTRY _mesa_Rotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
References _mesa_Rotatef(), and GLAPIENTRY.
_mesa_Rotatef()
void GLAPIENTRY _mesa_Rotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
Multiply the current matrix with a rotation matrix.
Parameters
angle angle of rotation, in degrees.
x rotation vector x coordinate.
y rotation vector y coordinate.
z rotation vector z coordinate.
See also
glRotatef().
Flushes the vertices and calls _math_matrix_rotate() with the top-most matrix in the current stack and the given parameters. Marks __struct gl_contextRec::NewState with the dirty stack flag.
References _math_matrix_rotate(), F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_Rotated(), and _mesa_Rotatex().
_mesa_Scaled()
void GLAPIENTRY _mesa_Scaled (GLdouble x, GLdouble y, GLdouble z)
References _mesa_Scalef(), and GLAPIENTRY.
_mesa_Scalef()
void GLAPIENTRY _mesa_Scalef (GLfloat x, GLfloat y, GLfloat z)
Multiply the current matrix with a general scaling matrix.
Parameters
x x axis scale factor.
y y axis scale factor.
z z axis scale factor.
See also
glScalef().
Flushes the vertices and calls _math_matrix_scale() with the top-most matrix in the current stack and the given parameters. Marks __struct gl_contextRec::NewState with the dirty stack flag.
References _math_matrix_scale(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_Scaled(), and _mesa_Scalex().
_mesa_Translated()
void GLAPIENTRY _mesa_Translated (GLdouble x, GLdouble y, GLdouble z)
References _mesa_Translatef(), and GLAPIENTRY.
_mesa_Translatef()
void GLAPIENTRY _mesa_Translatef (GLfloat x, GLfloat y, GLfloat z)
Multiply the current matrix with a translation matrix.
Parameters
x translation vector x coordinate.
y translation vector y coordinate.
z translation vector z coordinate.
See also
glTranslatef().
Flushes the vertices and calls _math_matrix_translate() with the top-most matrix in the current stack and the given parameters. Marks __struct gl_contextRec::NewState with the dirty stack flag.
References _math_matrix_translate(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_Translated(), and _mesa_Translatex().
_mesa_update_modelview_project()
void _mesa_update_modelview_project (struct gl_context * ctx, GLuint new_state)
Updates the combined modelview-projection matrix.
Parameters
ctx GL context.
new_state new state bit mask.
If there is a new model view matrix then analyzes it. If there is a new projection matrix, updates it. Finally calls calculate_model_project_matrix() to recalculate the modelview-projection matrix.
References _math_matrix_analyse(), _NEW_MODELVIEW, _NEW_PROJECTION, calculate_model_project_matrix(), gl_context::ModelviewMatrixStack, gl_matrix_stack::Top, and update_projection().
Referenced by _mesa_update_state_locked().
calculate_model_project_matrix()
static void calculate_model_project_matrix (struct gl_context * ctx) static
Calculate the combined modelview-projection matrix.
Parameters
ctx GL context.
Multiplies the top matrices of the projection and model view stacks into __struct gl_contextRec::_ModelProjectMatrix via _math_matrix_mul_matrix() and analyzes the resulting matrix via _math_matrix_analyse().
References _math_matrix_analyse(), _math_matrix_mul_matrix(), gl_context::_ModelProjectMatrix, gl_context::ModelviewMatrixStack, gl_context::ProjectionMatrixStack, and gl_matrix_stack::Top.
Referenced by _mesa_update_modelview_project().
free_matrix_stack()
static void free_matrix_stack (struct gl_matrix_stack * stack) static
Free matrix stack.
Parameters
stack matrix stack.
Calls _math_matrix_dtr() for each element of the matrix stack and frees the array.
References _math_matrix_dtr(), GLuint, gl_matrix_stack::Stack, gl_matrix_stack::StackSize, and gl_matrix_stack::Top.
Referenced by _mesa_free_matrix_data().
init_matrix_stack()
static void init_matrix_stack (struct gl_matrix_stack * stack, GLuint maxDepth, GLuint dirtyFlag) static
Matrix stack initialization.
Initialize a matrix stack.
Parameters
stack matrix stack.
maxDepth maximum stack depth.
dirtyFlag dirty flag.
Allocates an array of maxDepth elements for the matrix stack and calls _math_matrix_ctr() for each element to initialize it.
References _math_matrix_ctr(), gl_matrix_stack::Depth, gl_matrix_stack::DirtyFlag, GLuint, gl_matrix_stack::MaxDepth, gl_matrix_stack::Stack, gl_matrix_stack::StackSize, and gl_matrix_stack::Top.
Referenced by _mesa_init_matrix().
update_projection()
static void update_projection (struct gl_context * ctx) static
Update the projection matrix stack.
Parameters
ctx GL context.
Calls _math_matrix_analyse() with the top-matrix of the projection matrix stack, and recomputes user clip positions if necessary.
Note
This routine references __struct gl_contextRec::Tranform attribute values to compute userclip positions in clip space, but is only called on _NEW_PROJECTION. The _mesa_ClipPlane() function keeps these values up to date across changes to the __struct gl_contextRec::Transform attributes.
References gl_transform_attrib::_ClipUserPlane, _math_matrix_analyse(), _mesa_transform_vector(), gl_transform_attrib::ClipPlanesEnabled, gl_transform_attrib::EyeUserPlane, GLmatrix::inv, gl_context::ProjectionMatrixStack, gl_matrix_stack::Top, and gl_context::Transform.
Referenced by _mesa_update_modelview_project().