Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
mipmap.c File Reference
mipmap generation and teximage resizing functions.
#include "imports.h"
#include "formats.h"
#include "glformats.h"
#include "mipmap.h"
#include "mtypes.h"
#include "teximage.h"
#include "texobj.h"
#include "texstore.h"
#include "image.h"
#include "macros.h"
#include "util/half_float.h"
#include "util/format_rgb9e5.h"
#include "util/format_r11g11b10f.h"
Macros
Support macros for do_row and do_row_3d
The macro madness is here for two reasons.
First, it compacts the code slightly. Second, it makes it much easier to adjust the specifics of the filter to tune the rounding characteristics.
#define DECLARE_ROW_POINTERS(t, e)
#define DECLARE_ROW_POINTERS0(t)
#define FILTER_SUM_3D(Aj, Ak, Bj, Bk, Cj, Ck, Dj, Dk)
#define FILTER_3D(e)
#define FILTER_SUM_3D_SIGNED(Aj, Ak, Bj, Bk, Cj, Ck, Dj, Dk)
#define FILTER_3D_SIGNED(e)
#define FILTER_F_3D(e)
#define FILTER_HF_3D(e)
Functions
static GLint bytes_per_pixel (GLenum datatype, GLuint comps)
static void do_row (GLenum datatype, GLuint comps, GLint srcWidth, const GLvoid *srcRowA, const GLvoid *srcRowB, GLint dstWidth, GLvoid *dstRow)
Average together two rows of a source image to produce a single new row in the dest image.
static void do_row_3D (GLenum datatype, GLuint comps, GLint srcWidth, const GLvoid *srcRowA, const GLvoid *srcRowB, const GLvoid *srcRowC, const GLvoid *srcRowD, GLint dstWidth, GLvoid *dstRow)
Average together four rows of a source image to produce a single new row in the dest image.
static void make_1d_mipmap (GLenum datatype, GLuint comps, GLint border, GLint srcWidth, const GLubyte *srcPtr, GLint dstWidth, GLubyte *dstPtr)
static void make_2d_mipmap (GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, const GLubyte *srcPtr, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLubyte *dstPtr, GLint dstRowStride)
static void make_3d_mipmap (GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte **srcPtr, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte **dstPtr, GLint dstRowStride)
void _mesa_generate_mipmap_level (GLenum target, GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte **srcData, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte **dstData, GLint dstRowStride)
Down-sample a texture image to produce the next lower mipmap level.
GLboolean _mesa_next_mipmap_level_size (GLenum target, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLint *dstWidth, GLint *dstHeight, GLint *dstDepth)
compute next (level+1) image size
static GLboolean prepare_mipmap_level (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint level, GLsizei width, GLsizei height, GLsizei depth, GLsizei border, GLenum intFormat, mesa_format format)
Helper function for mipmap generation.
void _mesa_prepare_mipmap_levels (struct gl_context *ctx, struct gl_texture_object *texObj, unsigned baseLevel, unsigned maxLevel)
Prepare all mipmap levels beyond 'baseLevel' for mipmap generation.
static void generate_mipmap_uncompressed (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, const struct gl_texture_image *srcImage, GLuint maxLevel)
static void generate_mipmap_compressed (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, struct gl_texture_image *srcImage, GLuint maxLevel)
void _mesa_generate_mipmap (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Automatic mipmap generation.
Detailed Description
mipmap generation and teximage resizing functions.
Macro Definition Documentation
DECLARE_ROW_POINTERS
#define DECLARE_ROW_POINTERS (t, e)
Value:
const t(*rowA)[e] = (const t(*)[e]) srcRowA; \
      const t(*rowB)[e] = (const t(*)[e]) srcRowB; \
      const t(*rowC)[e] = (const t(*)[e]) srcRowC; \
      const t(*rowD)[e] = (const t(*)[e]) srcRowD; \
      t(*dst)[e] = (t(*)[e]) dstRow
Referenced by do_row_3D().
DECLARE_ROW_POINTERS0
#define DECLARE_ROW_POINTERS0 (t)
Value:
const t *rowA = (const t *) srcRowA; \
      const t *rowB = (const t *) srcRowB; \
      const t *rowC = (const t *) srcRowC; \
      const t *rowD = (const t *) srcRowD; \
      t *dst = (t *) dstRow
Referenced by do_row_3D().
FILTER_3D
#define FILTER_3D (e)
Value:
do { \
      dst[i][e] = FILTER_SUM_3D(rowA[j][e], rowA[k][e], \
                                rowB[j][e], rowB[k][e], \
                                rowC[j][e], rowC[k][e], \
                                rowD[j][e], rowD[k][e]); \
   } while(0)
Referenced by do_row_3D().
FILTER_3D_SIGNED
#define FILTER_3D_SIGNED (e)
Value:
do { \
      dst[i][e] = FILTER_SUM_3D_SIGNED(rowA[j][e], rowA[k][e], \
                                       rowB[j][e], rowB[k][e], \
                                       rowC[j][e], rowC[k][e], \
                                       rowD[j][e], rowD[k][e]); \
   } while(0)
Referenced by do_row_3D().
FILTER_F_3D
#define FILTER_F_3D (e)
Value:
do { \
      dst[i][e] = (rowA[j][e] + rowA[k][e] \
                   + rowB[j][e] + rowB[k][e] \
                   + rowC[j][e] + rowC[k][e] \
                   + rowD[j][e] + rowD[k][e]) * 0.125F; \
   } while(0)
Referenced by do_row_3D().
FILTER_HF_3D
#define FILTER_HF_3D (e)
Value:
do { \
      const GLfloat aj = _mesa_half_to_float(rowA[j][e]); \
      const GLfloat ak = _mesa_half_to_float(rowA[k][e]); \
      const GLfloat bj = _mesa_half_to_float(rowB[j][e]); \
      const GLfloat bk = _mesa_half_to_float(rowB[k][e]); \
      const GLfloat cj = _mesa_half_to_float(rowC[j][e]); \
      const GLfloat ck = _mesa_half_to_float(rowC[k][e]); \
      const GLfloat dj = _mesa_half_to_float(rowD[j][e]); \
      const GLfloat dk = _mesa_half_to_float(rowD[k][e]); \
      dst[i][e] = _mesa_float_to_half((aj + ak + bj + bk + cj + ck + dj + dk) \
                                      * 0.125F); \
   } while(0)
Referenced by do_row_3D().
FILTER_SUM_3D
#define FILTER_SUM_3D (Aj, Ak, Bj, Bk, Cj, Ck, Dj, Dk)
Value:
((unsigned) Aj + (unsigned) Ak \
    + (unsigned) Bj + (unsigned) Bk \
    + (unsigned) Cj + (unsigned) Ck \
    + (unsigned) Dj + (unsigned) Dk \
    + 4) >> 3
Referenced by do_row_3D().
FILTER_SUM_3D_SIGNED
#define FILTER_SUM_3D_SIGNED (Aj, Ak, Bj, Bk, Cj, Ck, Dj, Dk)
Value:
(Aj + Ak \
    + Bj + Bk \
    + Cj + Ck \
    + Dj + Dk \
    + 4) / 8
Function Documentation
_mesa_generate_mipmap()
void _mesa_generate_mipmap (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj)
Automatic mipmap generation.
This is the fallback/default function for ctx->Driver.GenerateMipmap(). Generate a complete set of mipmaps from texObj's BaseLevel image. Stop at texObj's MaxLevel or when we get to the 1x1 texture. For cube maps, target will be one of GL_TEXTURE_CUBE_MAP_POSITIVE/NEGATIVE_X/Y/Z; never GL_TEXTURE_CUBE_MAP.
References _mesa_is_format_compressed(), _mesa_max_texture_levels(), _mesa_prepare_mipmap_levels(), _mesa_select_tex_image(), gl_texture_object::BaseLevel, generate_mipmap_compressed(), generate_mipmap_uncompressed(), gl_texture_object::MaxLevel, gl_texture_object::Target, and gl_texture_image::TexFormat.
_mesa_generate_mipmap_level()
void _mesa_generate_mipmap_level (GLenum target, GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte ** srcData, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte ** dstData, GLint dstRowStride)
Down-sample a texture image to produce the next lower mipmap level.
Parameters
comps components per texel (1, 2, 3 or 4)
srcData array[slice] of pointers to source image slices
dstData array[slice] of pointers to dest image slices
srcRowStride stride between source rows, in bytes
dstRowStride stride between destination rows, in bytes
References _mesa_problem(), GL_TEXTURE_EXTERNAL_OES, make_1d_mipmap(), make_2d_mipmap(), and make_3d_mipmap().
Referenced by generate_mipmap_compressed(), and generate_mipmap_uncompressed().
_mesa_next_mipmap_level_size()
GLboolean _mesa_next_mipmap_level_size (GLenum target, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLint * dstWidth, GLint * dstHeight, GLint * dstDepth)
compute next (level+1) image size
Returns
GL_FALSE if no smaller size can be generated (eg. src is 1x1x1 size)
Referenced by _mesa_prepare_mipmap_levels(), _mesa_test_proxy_teximage(), and initialize_texture_fields().
_mesa_prepare_mipmap_levels()
void _mesa_prepare_mipmap_levels (struct gl_context * ctx, struct gl_texture_object * texObj, unsigned baseLevel, unsigned maxLevel)
Prepare all mipmap levels beyond 'baseLevel' for mipmap generation.
When finished, all the gl_texture_image structures for the smaller mipmap levels will be consistent with the base level (in terms of dimensions, format, etc).
References _mesa_next_mipmap_level_size(), _mesa_select_tex_image(), gl_texture_image::Depth, gl_texture_image::Height, gl_texture_image::InternalFormat, prepare_mipmap_level(), gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_generate_mipmap().
bytes_per_pixel()
static GLint bytes_per_pixel (GLenum datatype, GLuint comps) static
References _mesa_sizeof_packed_type(), and _mesa_type_is_packed().
Referenced by _mesa_image_offset(), make_1d_mipmap(), make_2d_mipmap(), and make_3d_mipmap().
do_row()
static void do_row (GLenum datatype, GLuint comps, GLint srcWidth, const GLvoid * srcRowA, const GLvoid * srcRowB, GLint dstWidth, GLvoid * dstRow) static
Average together two rows of a source image to produce a single new row in the dest image.
It's legal for the two source rows to point to the same data. The source width must be equal to either the dest width or two times the dest width.
Parameters
datatype GL_UNSIGNED_BYTE, GL_UNSIGNED_SHORT, GL_FLOAT, etc.
comps number of components per pixel (1..4)
References _mesa_problem(), F, GLuint, GLushort, and MESA_UNSIGNED_BYTE_4_4.
Referenced by make_1d_mipmap(), make_2d_mipmap(), and make_3d_mipmap().
do_row_3D()
static void do_row_3D (GLenum datatype, GLuint comps, GLint srcWidth, const GLvoid * srcRowA, const GLvoid * srcRowB, const GLvoid * srcRowC, const GLvoid * srcRowD, GLint dstWidth, GLvoid * dstRow) static
Average together four rows of a source image to produce a single new row in the dest image.
It's legal for the two source rows to point to the same data. The source width must be equal to either the dest width or two times the dest width.
Parameters
datatype GL pixel type GL_UNSIGNED_BYTE, GL_UNSIGNED_SHORT, GL_FLOAT, etc.
comps number of components per pixel (1..4)
srcWidth Width of a row in the source data
srcRowA Pointer to one of the rows of source data
srcRowB Pointer to one of the rows of source data
srcRowC Pointer to one of the rows of source data
srcRowD Pointer to one of the rows of source data
dstWidth Width of a row in the destination data
srcRowA Pointer to the row of destination data
References _mesa_problem(), DECLARE_ROW_POINTERS, DECLARE_ROW_POINTERS0, F, FILTER_3D, FILTER_3D_SIGNED, FILTER_F_3D, FILTER_HF_3D, FILTER_SUM_3D, GLuint, GLushort, and MESA_UNSIGNED_BYTE_4_4.
Referenced by make_3d_mipmap().
generate_mipmap_compressed()
static void generate_mipmap_compressed (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj, struct gl_texture_image * srcImage, GLuint maxLevel) static
References _mesa_error(), _mesa_format_image_size(), _mesa_format_num_components(), _mesa_format_row_stride(), _mesa_generate_mipmap_level(), _mesa_get_format_base_format(), _mesa_get_format_datatype(), _mesa_get_uncompressed_format(), _mesa_select_tex_image(), gl_texture_object::BaseLevel, gl_texture_image::Border, gl_context::DefaultPacking, gl_texture_image::Depth, gl_context::Driver, dd_function_table::GetTexSubImage, GLuint, gl_texture_image::Height, gl_texture_image::Level, gl_context::Pack, gl_texture_object::Target, gl_texture_image::TexFormat, dd_function_table::TexSubImage, and gl_texture_image::Width.
Referenced by _mesa_generate_mipmap().
generate_mipmap_uncompressed()
static void generate_mipmap_uncompressed (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj, const struct gl_texture_image * srcImage, GLuint maxLevel) static
References _mesa_error(), _mesa_generate_mipmap_level(), _mesa_select_tex_image(), _mesa_uncompressed_format_to_type_and_comps(), gl_texture_object::BaseLevel, gl_texture_image::Border, gl_texture_image::Depth, gl_context::Driver, GLuint, gl_texture_image::Height, dd_function_table::MapTextureImage, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by _mesa_generate_mipmap().
make_1d_mipmap()
static void make_1d_mipmap (GLenum datatype, GLuint comps, GLint border, GLint srcWidth, const GLubyte * srcPtr, GLint dstWidth, GLubyte * dstPtr) static
References bytes_per_pixel(), and do_row().
Referenced by _mesa_generate_mipmap_level().
make_2d_mipmap()
static void make_2d_mipmap (GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, const GLubyte * srcPtr, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLubyte * dstPtr, GLint dstRowStride) static
References bytes_per_pixel(), and do_row().
Referenced by _mesa_generate_mipmap_level(), and make_3d_mipmap().
make_3d_mipmap()
static void make_3d_mipmap (GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte ** srcPtr, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte ** dstPtr, GLint dstRowStride) static
References bytes_per_pixel(), do_row(), do_row_3D(), make_2d_mipmap(), and void.
Referenced by _mesa_generate_mipmap_level().
prepare_mipmap_level()
static GLboolean prepare_mipmap_level (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint level, GLsizei width, GLsizei height, GLsizei depth, GLsizei border, GLenum intFormat, mesa_format format) static
Helper function for mipmap generation.
Make sure the specified destination mipmap level is the right size/format for mipmap generation. If not, (re) allocate it.
Returns
GL_TRUE if successful, GL_FALSE if mipmap generation should stop
References _mesa_cube_face_target(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_num_tex_faces(), _mesa_update_fbo_texture(), _NEW_TEXTURE_OBJECT, dd_function_table::AllocTextureImageBuffer, gl_texture_image::Border, gl_texture_image::Depth, gl_context::Driver, dd_function_table::FreeTextureImageBuffer, GLuint, gl_texture_image::Height, gl_texture_object::Image, gl_texture_object::Immutable, gl_texture_image::InternalFormat, gl_context::NewState, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_prepare_mipmap_levels().