Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
mipmap.h File Reference
#include "mtypes.h"
Functions
void _mesa_generate_mipmap_level (GLenum target, GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte **srcData, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte **dstData, GLint dstRowStride)
Down-sample a texture image to produce the next lower mipmap level.
void _mesa_prepare_mipmap_levels (struct gl_context *ctx, struct gl_texture_object *texObj, unsigned baseLevel, unsigned maxLevel)
Prepare all mipmap levels beyond 'baseLevel' for mipmap generation.
void _mesa_generate_mipmap (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Automatic mipmap generation.
GLboolean _mesa_next_mipmap_level_size (GLenum target, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLint *dstWidth, GLint *dstHeight, GLint *dstDepth)
compute next (level+1) image size
Function Documentation
_mesa_generate_mipmap()
void _mesa_generate_mipmap (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj)
Automatic mipmap generation.
This is the fallback/default function for ctx->Driver.GenerateMipmap(). Generate a complete set of mipmaps from texObj's BaseLevel image. Stop at texObj's MaxLevel or when we get to the 1x1 texture. For cube maps, target will be one of GL_TEXTURE_CUBE_MAP_POSITIVE/NEGATIVE_X/Y/Z; never GL_TEXTURE_CUBE_MAP.
References _mesa_is_format_compressed(), _mesa_max_texture_levels(), _mesa_prepare_mipmap_levels(), _mesa_select_tex_image(), gl_texture_object::BaseLevel, generate_mipmap_compressed(), generate_mipmap_uncompressed(), gl_texture_object::MaxLevel, gl_texture_object::Target, and gl_texture_image::TexFormat.
_mesa_generate_mipmap_level()
void _mesa_generate_mipmap_level (GLenum target, GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte ** srcData, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte ** dstData, GLint dstRowStride)
Down-sample a texture image to produce the next lower mipmap level.
Parameters
comps components per texel (1, 2, 3 or 4)
srcData array[slice] of pointers to source image slices
dstData array[slice] of pointers to dest image slices
srcRowStride stride between source rows, in bytes
dstRowStride stride between destination rows, in bytes
References _mesa_problem(), GL_TEXTURE_EXTERNAL_OES, make_1d_mipmap(), make_2d_mipmap(), and make_3d_mipmap().
Referenced by generate_mipmap_compressed(), and generate_mipmap_uncompressed().
_mesa_next_mipmap_level_size()
GLboolean _mesa_next_mipmap_level_size (GLenum target, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLint * dstWidth, GLint * dstHeight, GLint * dstDepth)
compute next (level+1) image size
Returns
GL_FALSE if no smaller size can be generated (eg. src is 1x1x1 size)
Referenced by _mesa_prepare_mipmap_levels(), _mesa_test_proxy_teximage(), and initialize_texture_fields().
_mesa_prepare_mipmap_levels()
void _mesa_prepare_mipmap_levels (struct gl_context * ctx, struct gl_texture_object * texObj, unsigned baseLevel, unsigned maxLevel)
Prepare all mipmap levels beyond 'baseLevel' for mipmap generation.
When finished, all the gl_texture_image structures for the smaller mipmap levels will be consistent with the base level (in terms of dimensions, format, etc).
References _mesa_next_mipmap_level_size(), _mesa_select_tex_image(), gl_texture_image::Depth, gl_texture_image::Height, gl_texture_image::InternalFormat, prepare_mipmap_level(), gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_generate_mipmap().