Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
multisample.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/macros.h"
#include "main/multisample.h"
#include "main/mtypes.h"
#include "main/fbobject.h"
#include "main/glformats.h"
#include "main/state.h"
Functions
void GLAPIENTRY _mesa_SampleCoverage (GLclampf value, GLboolean invert)
Called via glSampleCoverageARB.
void _mesa_init_multisample (struct gl_context *ctx)
Initialize the context's multisample state.
void GLAPIENTRY _mesa_GetMultisamplefv (GLenum pname, GLuint index, GLfloat *val)
void GLAPIENTRY _mesa_SampleMaski (GLuint index, GLbitfield mask)
void GLAPIENTRY _mesa_MinSampleShading (GLclampf value)
Called via glMinSampleShadingARB.
GLenum _mesa_check_sample_count (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLsizei samples)
Helper for checking a requested sample count against the limit for a particular (target, internalFormat) pair.
Function Documentation
_mesa_check_sample_count()
GLenum _mesa_check_sample_count (struct gl_context * ctx, GLenum target, GLenum internalFormat, GLsizei samples)
Helper for checking a requested sample count against the limit for a particular (target, internalFormat) pair.
The limit imposed, and the error generated, both depend on which extensions are supported.
Returns a GL error enum, or GL_NO_ERROR if the requested sample count is acceptable.
References _mesa_is_depth_or_stencil_format(), _mesa_is_enum_format_integer(), gl_context::API, API_OPENGLES2, gl_extensions::ARB_internalformat_query, gl_extensions::ARB_texture_multisample, gl_context::Const, gl_context::Driver, gl_context::Extensions, GLuint, gl_constants::MaxColorTextureSamples, gl_constants::MaxDepthTextureSamples, gl_constants::MaxIntegerSamples, gl_constants::MaxSamples, dd_function_table::QueryInternalFormat, and gl_context::Version.
Referenced by _mesa_renderbuffer_storage(), renderbuffer_storage(), and texture_image_multisample().
_mesa_GetMultisamplefv()
void GLAPIENTRY _mesa_GetMultisamplefv (GLenum pname, GLuint index, GLfloat * val)
References _mesa_error(), _mesa_is_winsys_fbo(), _mesa_update_state(), _NEW_BUFFERS, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_init_multisample()
void _mesa_init_multisample (struct gl_context * ctx)
Initialize the context's multisample state.
Parameters
ctx the GL context.
References gl_multisample_attrib::Enabled, GLAPIENTRY, gl_context::Multisample, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleCoverageValue, gl_multisample_attrib::SampleMask, and gl_multisample_attrib::SampleMaskValue.
Referenced by init_attrib_groups().
_mesa_MinSampleShading()
void GLAPIENTRY _mesa_MinSampleShading (GLclampf value)
Called via glMinSampleShadingARB.
References _mesa_error(), _NEW_MULTISAMPLE, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
_mesa_SampleCoverage()
void GLAPIENTRY _mesa_SampleCoverage (GLclampf value, GLboolean invert)
Called via glSampleCoverageARB.
References _NEW_MULTISAMPLE, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
Referenced by _mesa_PopAttrib(), and _mesa_SampleCoveragex().
_mesa_SampleMaski()
void GLAPIENTRY _mesa_SampleMaski (GLuint index, GLbitfield mask)
References _mesa_error(), _NEW_MULTISAMPLE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.