Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
objectpurge.h File Reference
Functions
GLenum GLAPIENTRY _mesa_ObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
GLenum GLAPIENTRY _mesa_ObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
void GLAPIENTRY _mesa_GetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint *params)
Function Documentation
_mesa_GetObjectParameterivAPPLE()
void GLAPIENTRY _mesa_GetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint * params)
References _mesa_error(), get_buffer_object_parameteriv(), GET_CURRENT_CONTEXT, get_renderbuffer_parameteriv(), and get_texture_object_parameteriv().
_mesa_ObjectPurgeableAPPLE()
GLenum GLAPIENTRY _mesa_ObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, buffer_object_purgeable(), GET_CURRENT_CONTEXT, renderbuffer_purgeable(), and texture_object_purgeable().
_mesa_ObjectUnpurgeableAPPLE()
GLenum GLAPIENTRY _mesa_ObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, buffer_object_unpurgeable(), GET_CURRENT_CONTEXT, renderbuffer_unpurgeable(), and texture_object_unpurgeable().