Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
objectpurge.c File Reference
#include "glheader.h"
#include "enums.h"
#include "hash.h"
#include "imports.h"
#include "context.h"
#include "bufferobj.h"
#include "fbobject.h"
#include "mtypes.h"
#include "objectpurge.h"
#include "texobj.h"
#include "teximage.h"
Functions
static GLenum buffer_object_purgeable (struct gl_context *ctx, GLuint name, GLenum option)
Code related to the GL_APPLE_object_purgeable extension.
static GLenum renderbuffer_purgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum texture_object_purgeable (struct gl_context *ctx, GLuint name, GLenum option)
GLenum GLAPIENTRY _mesa_ObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
static GLenum buffer_object_unpurgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum renderbuffer_unpurgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum texture_object_unpurgeable (struct gl_context *ctx, GLuint name, GLenum option)
GLenum GLAPIENTRY _mesa_ObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
static void get_buffer_object_parameteriv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
static void get_renderbuffer_parameteriv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
static void get_texture_object_parameteriv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint *params)
Function Documentation
_mesa_GetObjectParameterivAPPLE()
void GLAPIENTRY _mesa_GetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint * params)
References _mesa_error(), get_buffer_object_parameteriv(), GET_CURRENT_CONTEXT, get_renderbuffer_parameteriv(), and get_texture_object_parameteriv().
_mesa_ObjectPurgeableAPPLE()
GLenum GLAPIENTRY _mesa_ObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, buffer_object_purgeable(), GET_CURRENT_CONTEXT, renderbuffer_purgeable(), and texture_object_purgeable().
_mesa_ObjectUnpurgeableAPPLE()
GLenum GLAPIENTRY _mesa_ObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, buffer_object_unpurgeable(), GET_CURRENT_CONTEXT, renderbuffer_unpurgeable(), and texture_object_unpurgeable().
buffer_object_purgeable()
static GLenum buffer_object_purgeable (struct gl_context * ctx, GLuint name, GLenum option) static
Code related to the GL_APPLE_object_purgeable extension.
References _mesa_error(), _mesa_is_bufferobj(), _mesa_lookup_bufferobj(), dd_function_table::BufferObjectPurgeable, gl_context::Driver, and gl_buffer_object::Purgeable.
Referenced by _mesa_ObjectPurgeableAPPLE().
buffer_object_unpurgeable()
static GLenum buffer_object_unpurgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_bufferobj(), dd_function_table::BufferObjectUnpurgeable, gl_context::Driver, and gl_buffer_object::Purgeable.
Referenced by _mesa_ObjectUnpurgeableAPPLE().
get_buffer_object_parameteriv()
static void get_buffer_object_parameteriv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
References _mesa_error(), _mesa_lookup_bufferobj(), and gl_buffer_object::Purgeable.
Referenced by _mesa_GetObjectParameterivAPPLE().
get_renderbuffer_parameteriv()
static void get_renderbuffer_parameteriv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
References _mesa_error(), _mesa_lookup_renderbuffer(), and gl_renderbuffer::Purgeable.
Referenced by _mesa_GetObjectParameterivAPPLE().
get_texture_object_parameteriv()
static void get_texture_object_parameteriv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
References _mesa_error(), _mesa_lookup_texture(), GLAPIENTRY, and gl_texture_object::Purgeable.
Referenced by _mesa_GetObjectParameterivAPPLE().
renderbuffer_purgeable()
static GLenum renderbuffer_purgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_renderbuffer(), gl_context::Driver, gl_renderbuffer::Purgeable, and dd_function_table::RenderObjectPurgeable.
Referenced by _mesa_ObjectPurgeableAPPLE().
renderbuffer_unpurgeable()
static GLenum renderbuffer_unpurgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_renderbuffer(), gl_context::Driver, gl_renderbuffer::Purgeable, and dd_function_table::RenderObjectUnpurgeable.
Referenced by _mesa_ObjectUnpurgeableAPPLE().
texture_object_purgeable()
static GLenum texture_object_purgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_texture(), gl_context::Driver, GLAPIENTRY, gl_texture_object::Purgeable, and dd_function_table::TextureObjectPurgeable.
Referenced by _mesa_ObjectPurgeableAPPLE().
texture_object_unpurgeable()
static GLenum texture_object_unpurgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_texture(), gl_context::Driver, GLAPIENTRY, gl_texture_object::Purgeable, and dd_function_table::TextureObjectUnpurgeable.
Referenced by _mesa_ObjectUnpurgeableAPPLE().