Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
objectlabel.c File Reference
#include "arrayobj.h"
#include "bufferobj.h"
#include "context.h"
#include "dlist.h"
#include "enums.h"
#include "fbobject.h"
#include "objectlabel.h"
#include "pipelineobj.h"
#include "queryobj.h"
#include "samplerobj.h"
#include "shaderobj.h"
#include "syncobj.h"
#include "texobj.h"
#include "transformfeedback.h"
Functions
static void set_label (struct gl_context *ctx, char **labelPtr, const char *label, int length, const char *caller)
Helper for _mesa_ObjectLabel() and _mesa_ObjectPtrLabel().
static void copy_label (const GLchar *src, GLchar *dst, GLsizei *length, GLsizei bufSize)
Helper for _mesa_GetObjectLabel() and _mesa_GetObjectPtrLabel().
static char ** get_label_pointer (struct gl_context *ctx, GLenum identifier, GLuint name, const char *caller)
Helper for _mesa_ObjectLabel() and _mesa_GetObjectLabel().
void GLAPIENTRY _mesa_ObjectLabel (GLenum identifier, GLuint name, GLsizei length, const GLchar *label)
void GLAPIENTRY _mesa_GetObjectLabel (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label)
void GLAPIENTRY _mesa_ObjectPtrLabel (const void *ptr, GLsizei length, const GLchar *label)
void GLAPIENTRY _mesa_GetObjectPtrLabel (const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label)
Function Documentation
_mesa_GetObjectLabel()
void GLAPIENTRY _mesa_GetObjectLabel (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei * length, GLchar * label)
References _mesa_error(), _mesa_is_desktop_gl(), copy_label(), GET_CURRENT_CONTEXT, get_label_pointer(), and GLAPIENTRY.
_mesa_GetObjectPtrLabel()
void GLAPIENTRY _mesa_GetObjectPtrLabel (const void * ptr, GLsizei bufSize, GLsizei * length, GLchar * label)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_is_desktop_gl(), _mesa_unref_sync_object(), copy_label(), GET_CURRENT_CONTEXT, and gl_sync_object::Label.
_mesa_ObjectLabel()
void GLAPIENTRY _mesa_ObjectLabel (GLenum identifier, GLuint name, GLsizei length, const GLchar * label)
References _mesa_is_desktop_gl(), GET_CURRENT_CONTEXT, get_label_pointer(), GLAPIENTRY, and set_label().
_mesa_ObjectPtrLabel()
void GLAPIENTRY _mesa_ObjectPtrLabel (const void * ptr, GLsizei length, const GLchar * label)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_is_desktop_gl(), _mesa_unref_sync_object(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_sync_object::Label, and set_label().
copy_label()
static void copy_label (const GLchar * src, GLchar * dst, GLsizei * length, GLsizei bufSize) static
Helper for _mesa_GetObjectLabel() and _mesa_GetObjectPtrLabel().
Parameters
src the src label (may be null)
dst pointer to dest buffer (may be null)
length returns length of label (may be null)
bufsize size of dst buffer
Referenced by _mesa_GetObjectLabel(), and _mesa_GetObjectPtrLabel().
get_label_pointer()
static char** get_label_pointer (struct gl_context * ctx, GLenum identifier, GLuint name, const char * caller) static
Helper for _mesa_ObjectLabel() and _mesa_GetObjectLabel().
References _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_bufferobj(), _mesa_lookup_framebuffer(), _mesa_lookup_list(), _mesa_lookup_pipeline_object(), _mesa_lookup_query_object(), _mesa_lookup_renderbuffer(), _mesa_lookup_samplerobj(), _mesa_lookup_shader(), _mesa_lookup_shader_program(), _mesa_lookup_texture(), _mesa_lookup_transform_feedback_object(), _mesa_lookup_vao(), gl_context::API, API_OPENGL_COMPAT, gl_transform_feedback_object::EverBound, GLAPIENTRY, gl_sampler_object::Label, gl_texture_object::Label, gl_buffer_object::Label, gl_vertex_array_object::Label, gl_transform_feedback_object::Label, gl_shader::Label, gl_shader_program::Label, gl_pipeline_object::Label, gl_query_object::Label, gl_renderbuffer::Label, gl_framebuffer::Label, gl_display_list::Label, and gl_texture_object::Target.
Referenced by _mesa_GetObjectLabel(), and _mesa_ObjectLabel().
set_label()
static void set_label (struct gl_context * ctx, char ** labelPtr, const char * label, int length, const char * caller) static
Helper for _mesa_ObjectLabel() and _mesa_ObjectPtrLabel().
References _mesa_error(), and MAX_LABEL_LENGTH.
Referenced by _mesa_ObjectLabel(), and _mesa_ObjectPtrLabel().