Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
objectlabel.h File Reference
Mesa object label functions.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_ObjectLabel (GLenum identifier, GLuint name, GLsizei length, const GLchar *label)
void GLAPIENTRY _mesa_GetObjectLabel (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label)
void GLAPIENTRY _mesa_ObjectPtrLabel (const void *ptr, GLsizei length, const GLchar *label)
void GLAPIENTRY _mesa_GetObjectPtrLabel (const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label)
Detailed Description
Mesa object label functions.
This file provides functions to assign and retrieve object labels.
Function Documentation
_mesa_GetObjectLabel()
void GLAPIENTRY _mesa_GetObjectLabel (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei * length, GLchar * label)
References _mesa_error(), _mesa_is_desktop_gl(), copy_label(), GET_CURRENT_CONTEXT, get_label_pointer(), and GLAPIENTRY.
_mesa_GetObjectPtrLabel()
void GLAPIENTRY _mesa_GetObjectPtrLabel (const void * ptr, GLsizei bufSize, GLsizei * length, GLchar * label)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_is_desktop_gl(), _mesa_unref_sync_object(), copy_label(), GET_CURRENT_CONTEXT, and gl_sync_object::Label.
_mesa_ObjectLabel()
void GLAPIENTRY _mesa_ObjectLabel (GLenum identifier, GLuint name, GLsizei length, const GLchar * label)
References _mesa_is_desktop_gl(), GET_CURRENT_CONTEXT, get_label_pointer(), GLAPIENTRY, and set_label().
_mesa_ObjectPtrLabel()
void GLAPIENTRY _mesa_ObjectPtrLabel (const void * ptr, GLsizei length, const GLchar * label)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_is_desktop_gl(), _mesa_unref_sync_object(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_sync_object::Label, and set_label().