Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
pack.c File Reference
Image and pixel span packing and unpacking.
#include "glheader.h"
#include "enums.h"
#include "image.h"
#include "imports.h"
#include "macros.h"
#include "mtypes.h"
#include "pack.h"
#include "pixeltransfer.h"
#include "glformats.h"
#include "format_utils.h"
#include "format_pack.h"
Macros
#define SWAP2BYTE(VALUE)
#define SWAP4BYTE(VALUE)
#define DEPTH_VALUES(GLTYPE, GLTYPE2FLOAT)
Functions
static void flip_bytes (GLubyte *p, GLuint n)
Flip the 8 bits in each byte of the given array.
void _mesa_unpack_polygon_stipple (const GLubyte *pattern, GLuint dest[32], const struct gl_pixelstore_attrib *unpacking)
void _mesa_pack_polygon_stipple (const GLuint pattern[32], GLubyte *dest, const struct gl_pixelstore_attrib *packing)
void _mesa_pack_bitmap (GLint width, GLint height, const GLubyte *source, GLubyte *dest, const struct gl_pixelstore_attrib *packing)
static void extract_uint_indexes (GLuint n, GLuint indexes[], GLenum srcFormat, GLenum srcType, const GLvoid *src, const struct gl_pixelstore_attrib *unpack)
static GLuint clamp_float_to_uint (GLfloat f)
static GLuint clamp_half_to_uint (GLhalfARB h)
void _mesa_unpack_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_pack_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, const GLubyte *source, const struct gl_pixelstore_attrib *dstPacking)
void _mesa_unpack_depth_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLuint depthMax, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking)
Unpack a row of depth/z values from memory, returning GLushort, GLuint or GLfloat values.
void _mesa_pack_depth_span (struct gl_context *ctx, GLuint n, GLvoid *dest, GLenum dstType, const GLfloat *depthSpan, const struct gl_pixelstore_attrib *dstPacking)
void _mesa_pack_depth_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLuint *dest, const GLfloat *depthVals, const GLubyte *stencilVals, const struct gl_pixelstore_attrib *dstPacking)
Pack depth and stencil values as GL_DEPTH_STENCIL (GL_UNSIGNED_INT_24_8 etc)
void * _mesa_unpack_image (GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *unpack)
Unpack image data.
void _mesa_pack_luminance_from_rgba_float (GLuint n, GLfloat rgba[][4], GLvoid *dstAddr, GLenum dst_format, GLbitfield transferOps)
static int32_t clamp_sint64_to_sint32 (int64_t src)
static int32_t clamp_sint64_to_uint32 (int64_t src)
static int32_t clamp_uint64_to_uint32 (uint64_t src)
static int32_t clamp_uint64_to_sint32 (uint64_t src)
static int32_t convert_integer_luminance64 (int64_t src64, int bits, bool dst_is_signed, bool src_is_signed)
static int32_t convert_integer (int32_t src, int bits, bool dst_is_signed, bool src_is_signed)
void _mesa_pack_luminance_from_rgba_integer (GLuint n, GLuint rgba[][4], bool rgba_is_signed, GLvoid *dstAddr, GLenum dst_format, GLenum dst_type)
GLfloat * _mesa_unpack_color_index_to_rgba_float (struct gl_context *ctx, GLuint dims, const void *src, GLenum srcFormat, GLenum srcType, int srcWidth, int srcHeight, int srcDepth, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
GLubyte * _mesa_unpack_color_index_to_rgba_ubyte (struct gl_context *ctx, GLuint dims, const void *src, GLenum srcFormat, GLenum srcType, int srcWidth, int srcHeight, int srcDepth, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Detailed Description
Image and pixel span packing and unpacking.
Macro Definition Documentation
DEPTH_VALUES
#define DEPTH_VALUES (GLTYPE, GLTYPE2FLOAT)
Value:
do {                                                                \
        GLuint i;                                                       \
        const GLTYPE *src = (const GLTYPE *)source;                     \
        for (i = 0; i < n; i++) {                                       \
            GLTYPE value = src[i];                                      \
            if (srcPacking->SwapBytes) {                                \
                if (sizeof(GLTYPE) == 2) {                              \
                    SWAP2BYTE(value);                                   \
                } else if (sizeof(GLTYPE) == 4) {                       \
                    SWAP4BYTE(value);                                   \
                }                                                       \
            }                                                           \
            depthValues[i] = GLTYPE2FLOAT(value);                       \
        }                                                               \
    } while (0)
Referenced by _mesa_unpack_depth_span().
SWAP2BYTE
#define SWAP2BYTE (VALUE)
Value:
{                                               \
      GLubyte *bytes = (GLubyte *) &(VALUE);    \
      GLubyte tmp = bytes[0];                   \
      bytes[0] = bytes[1];                      \
      bytes[1] = tmp;                           \
   }
Referenced by _mesa_unpack_depth_span(), and extract_uint_indexes().
SWAP4BYTE
#define SWAP4BYTE (VALUE)
Value:
{                                               \
      GLubyte *bytes = (GLubyte *) &(VALUE);    \
      GLubyte tmp = bytes[0];                   \
      bytes[0] = bytes[3];                      \
      bytes[3] = tmp;                           \
      tmp = bytes[1];                           \
      bytes[1] = bytes[2];                      \
      bytes[2] = tmp;                           \
   }
Referenced by _mesa_unpack_depth_span(), and extract_uint_indexes().
Function Documentation
_mesa_pack_bitmap()
void _mesa_pack_bitmap (GLint width, GLint height, const GLubyte * source, GLubyte * dest, const struct gl_pixelstore_attrib * packing)
References _mesa_image_address2d(), flip_bytes(), gl_pixelstore_attrib::LsbFirst, and gl_pixelstore_attrib::SkipPixels.
Referenced by _mesa_pack_polygon_stipple().
_mesa_pack_depth_span()
void _mesa_pack_depth_span (struct gl_context * ctx, GLuint n, GLvoid * dest, GLenum dstType, const GLfloat * depthSpan, const struct gl_pixelstore_attrib * dstPacking)
References _mesa_enum_to_string(), _mesa_error(), _mesa_problem(), _mesa_scale_and_bias_depth(), _mesa_swap2(), _mesa_swap4(), CLAMPED_FLOAT_TO_USHORT, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, FLOAT_TO_BYTE, FLOAT_TO_INT, FLOAT_TO_SHORT, FLOAT_TO_UBYTE, FLOAT_TO_UINT, GL_HALF_FLOAT_OES, GLuint, GLushort, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by get_tex_depth(), and read_depth_pixels().
_mesa_pack_depth_stencil_span()
void _mesa_pack_depth_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLuint * dest, const GLfloat * depthVals, const GLubyte * stencilVals, const struct gl_pixelstore_attrib * dstPacking)
Pack depth and stencil values as GL_DEPTH_STENCIL (GL_UNSIGNED_INT_24_8 etc)
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _mesa_scale_and_bias_depth(), _mesa_swap4(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, GLuint, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by slow_read_depth_stencil_pixels_separate().
_mesa_pack_luminance_from_rgba_float()
void _mesa_pack_luminance_from_rgba_float (GLuint n, GLfloat rgba[][4], GLvoid * dstAddr, GLenum dst_format, GLbitfield transferOps)
References ACOMP, BCOMP, F, GCOMP, IMAGE_CLAMP_BIT, and RCOMP.
Referenced by read_rgba_pixels().
_mesa_pack_luminance_from_rgba_integer()
void _mesa_pack_luminance_from_rgba_integer (GLuint n, GLuint rgba[][4], bool rgba_is_signed, GLvoid * dstAddr, GLenum dst_format, GLenum dst_type)
References _mesa_sizeof_type(), ACOMP, BCOMP, convert_integer(), convert_integer_luminance64(), GCOMP, and RCOMP.
Referenced by read_rgba_pixels().
_mesa_pack_polygon_stipple()
void _mesa_pack_polygon_stipple (const GLuint pattern[32], GLubyte * dest, const struct gl_pixelstore_attrib * packing)
References _mesa_pack_bitmap().
Referenced by _mesa_GetnPolygonStippleARB().
_mesa_pack_stencil_span()
void _mesa_pack_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, const GLubyte * source, const struct gl_pixelstore_attrib * dstPacking)
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _mesa_problem(), _mesa_swap2(), _mesa_swap4(), GL_HALF_FLOAT_OES, GLuint, GLushort, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixelstore_attrib::LsbFirst, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by read_stencil_pixels().
_mesa_unpack_color_index_to_rgba_float()
GLfloat* _mesa_unpack_color_index_to_rgba_float (struct gl_context * ctx, GLuint dims, const void * src, GLenum srcFormat, GLenum srcType, int srcWidth, int srcHeight, int srcDepth, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_apply_rgba_transfer_ops(), _mesa_error(), _mesa_image_address(), _mesa_map_ci_to_rgba(), _mesa_shift_and_offset_ci(), extract_uint_indexes(), GLuint, IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, and IMAGE_SHIFT_OFFSET_BIT.
Referenced by _mesa_unpack_color_index_to_rgba_ubyte().
_mesa_unpack_color_index_to_rgba_ubyte()
GLubyte* _mesa_unpack_color_index_to_rgba_ubyte (struct gl_context * ctx, GLuint dims, const void * src, GLenum srcFormat, GLenum srcType, int srcWidth, int srcHeight, int srcDepth, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_unpack_color_index_to_rgba_float(), CLAMPED_FLOAT_TO_UBYTE, and IMAGE_CLAMP_BIT.
Referenced by texstore_rgba().
_mesa_unpack_depth_span()
void _mesa_unpack_depth_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLuint depthMax, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking)
Unpack a row of depth/z values from memory, returning GLushort, GLuint or GLfloat values.
The glPixelTransfer (scale/bias) params will be applied.
Parameters
dstType one of GL_UNSIGNED_SHORT, GL_UNSIGNED_INT, GL_FLOAT
depthMax max value for returned GLushort or GLuint values (ignored for GLfloat).
References _mesa_error(), _mesa_problem(), BYTE_TO_FLOATZ, DEPTH_VALUES, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, F, GL_HALF_FLOAT_OES, GLuint, GLushort, INT_TO_FLOAT, gl_context::Pixel, SHORT_TO_FLOATZ, SWAP2BYTE, SWAP4BYTE, gl_pixelstore_attrib::SwapBytes, UBYTE_TO_FLOAT, UINT_TO_FLOAT, and USHORT_TO_FLOAT.
Referenced by _mesa_texstore_s8_z24(), _mesa_texstore_x8_z24(), _mesa_texstore_z16(), _mesa_texstore_z24_s8(), _mesa_texstore_z24_x8(), _mesa_texstore_z32(), and _mesa_texstore_z32f_x24s8().
_mesa_unpack_image()
void* _mesa_unpack_image (GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * unpack)
Unpack image data.
Apply byte swapping, byte flipping (bitmap). Return all image data in a contiguous block. This is used when we compile glDrawPixels, glTexImage, etc into a display list. We need a copy of the data in a standard format.
References _mesa_bytes_per_pixel(), _mesa_components_in_format(), _mesa_image_address(), _mesa_swap2(), _mesa_swap4(), _mesa_type_is_packed(), flip_bytes(), GLuint, GLushort, gl_pixelstore_attrib::LsbFirst, gl_pixelstore_attrib::SkipPixels, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_unpack_polygon_stipple(), and unpack_image().
_mesa_unpack_polygon_stipple()
void _mesa_unpack_polygon_stipple (const GLubyte * pattern, GLuint dest[32], const struct gl_pixelstore_attrib * unpacking)
References _mesa_unpack_image().
Referenced by _mesa_PolygonStipple().
_mesa_unpack_stencil_span()
void _mesa_unpack_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_error(), _mesa_problem(), _mesa_shift_and_offset_ci(), extract_uint_indexes(), GL_HALF_FLOAT_OES, GLuint, GLushort, IMAGE_SHIFT_OFFSET_BIT, gl_pixelmap::Map, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, gl_context::PixelMaps, gl_pixelmap::Size, gl_pixelmaps::StoS, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_s8(), _mesa_texstore_s8_z24(), _mesa_texstore_z24_s8(), and _mesa_texstore_z32f_x24s8().
clamp_float_to_uint()
static GLuint clamp_float_to_uint (GLfloat f) inline static
References GLuint.
clamp_half_to_uint()
static GLuint clamp_half_to_uint (GLhalfARB h) inline static
clamp_sint64_to_sint32()
static int32_t clamp_sint64_to_sint32 (int64_t src) static
Referenced by convert_integer_luminance64().
clamp_sint64_to_uint32()
static int32_t clamp_sint64_to_uint32 (int64_t src) static
Referenced by convert_integer_luminance64().
clamp_uint64_to_sint32()
static int32_t clamp_uint64_to_sint32 (uint64_t src) static
Referenced by convert_integer_luminance64().
clamp_uint64_to_uint32()
static int32_t clamp_uint64_to_uint32 (uint64_t src) static
Referenced by convert_integer_luminance64().
convert_integer()
static int32_t convert_integer (int32_t src, int bits, bool dst_is_signed, bool src_is_signed) static
References _mesa_signed_to_signed(), _mesa_signed_to_unsigned(), _mesa_unsigned_to_signed(), and _mesa_unsigned_to_unsigned().
Referenced by _mesa_pack_luminance_from_rgba_integer().
convert_integer_luminance64()
static int32_t convert_integer_luminance64 (int64_t src64, int bits, bool dst_is_signed, bool src_is_signed) static
References _mesa_signed_to_signed(), _mesa_unsigned_to_unsigned(), clamp_sint64_to_sint32(), clamp_sint64_to_uint32(), clamp_uint64_to_sint32(), and clamp_uint64_to_uint32().
Referenced by _mesa_pack_luminance_from_rgba_integer().
extract_uint_indexes()
static void extract_uint_indexes (GLuint n, GLuint indexes[], GLenum srcFormat, GLenum srcType, const GLvoid * src, const struct gl_pixelstore_attrib * unpack) static
References _mesa_problem(), GL_HALF_FLOAT_OES, GLuint, GLushort, gl_pixelstore_attrib::LsbFirst, gl_pixelstore_attrib::SkipPixels, SWAP2BYTE, SWAP4BYTE, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_unpack_color_index_to_rgba_float(), and _mesa_unpack_stencil_span().
flip_bytes()
static void flip_bytes (GLubyte * p, GLuint n) static
Flip the 8 bits in each byte of the given array.
Parameters
p array.
n number of bytes.
Todo:
try this trick to flip bytes someday:
v = ((v & 0x55555555) << 1) | ((v >> 1) & 0x55555555);
v = ((v & 0x33333333) << 2) | ((v >> 2) & 0x33333333);
v = ((v & 0x0f0f0f0f) << 4) | ((v >> 4) & 0x0f0f0f0f);
References GLuint.
Referenced by _mesa_pack_bitmap(), and _mesa_unpack_image().