Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
pbo.h File Reference
#include "mtypes.h"
Functions
GLboolean _mesa_validate_pbo_access (GLuint dimensions, const struct gl_pixelstore_attrib *pack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid *ptr)
When we're about to read pixel data out of a PBO (via glDrawPixels, glTexImage, etc) or write data into a PBO (via glReadPixels, glGetTexImage, etc) we call this function to check that we're not going to read/write out of bounds.
const GLvoid * _mesa_map_pbo_source (struct gl_context *ctx, const struct gl_pixelstore_attrib *unpack, const GLvoid *src)
For commands that read from a PBO (glDrawPixels, glTexImage, glPolygonStipple, etc), if we're reading from a PBO, map it read-only and return the pointer into the PBO.
const GLvoid * _mesa_map_validate_pbo_source (struct gl_context *ctx, GLuint dimensions, const struct gl_pixelstore_attrib *unpack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid *ptr, const char *where)
Perform PBO-read mapping.
void _mesa_unmap_pbo_source (struct gl_context *ctx, const struct gl_pixelstore_attrib *unpack)
Counterpart to _mesa_map_pbo_source()
void * _mesa_map_pbo_dest (struct gl_context *ctx, const struct gl_pixelstore_attrib *pack, GLvoid *dest)
For commands that write to a PBO (glReadPixels, glGetColorTable, etc), if we're writing to a PBO, map it write-only and return the pointer into the PBO.
GLvoid * _mesa_map_validate_pbo_dest (struct gl_context *ctx, GLuint dimensions, const struct gl_pixelstore_attrib *unpack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, GLvoid *ptr, const char *where)
Combine PBO-write validation and mapping.
void _mesa_unmap_pbo_dest (struct gl_context *ctx, const struct gl_pixelstore_attrib *pack)
Counterpart to _mesa_map_pbo_dest()
const GLvoid * _mesa_validate_pbo_teximage (struct gl_context *ctx, GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *unpack, const char *funcName)
Check if an unpack PBO is active prior to fetching a texture image.
const GLvoid * _mesa_validate_pbo_compressed_teximage (struct gl_context *ctx, GLuint dimensions, GLsizei imageSize, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing, const char *funcName)
Check if an unpack PBO is active prior to fetching a compressed texture image.
void _mesa_unmap_teximage_pbo (struct gl_context *ctx, const struct gl_pixelstore_attrib *unpack)
This function must be called after either of the validate_pbo_*_teximage() functions.
bool _mesa_validate_pbo_source (struct gl_context *ctx, GLuint dimensions, const struct gl_pixelstore_attrib *unpack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid *ptr, const char *where)
Perform PBO validation for read operations with uncompressed textures.
bool _mesa_validate_pbo_source_compressed (struct gl_context *ctx, GLuint dimensions, const struct gl_pixelstore_attrib *unpack, GLsizei imageSize, const GLvoid *ptr, const char *where)
Perform PBO validation for read operations with compressed textures.
Function Documentation
_mesa_map_pbo_dest()
void* _mesa_map_pbo_dest (struct gl_context * ctx, const struct gl_pixelstore_attrib * pack, GLvoid * dest)
For commands that write to a PBO (glReadPixels, glGetColorTable, etc), if we're writing to a PBO, map it write-only and return the pointer into the PBO.
If we're not writing to a PBO, return dst as-is. If non-null return, must call _mesa_unmap_pbo_dest() when done.
Returns
NULL if error, else pointer to start of data
References _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and gl_buffer_object::Size.
Referenced by _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_map_validate_pbo_dest(), and _mesa_readpixels().
_mesa_map_pbo_source()
const GLvoid* _mesa_map_pbo_source (struct gl_context * ctx, const struct gl_pixelstore_attrib * unpack, const GLvoid * src)
For commands that read from a PBO (glDrawPixels, glTexImage, glPolygonStipple, etc), if we're reading from a PBO, map it read-only and return the pointer into the PBO.
If we're not reading from a PBO, return src as-is. If non-null return, must call _mesa_unmap_pbo_source() when done.
Returns
NULL if error, else pointer to start of data
References _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and gl_buffer_object::Size.
Referenced by _mesa_map_validate_pbo_source(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), and _mesa_PixelMapusv().
_mesa_map_validate_pbo_dest()
GLvoid* _mesa_map_validate_pbo_dest (struct gl_context * ctx, GLuint dimensions, const struct gl_pixelstore_attrib * unpack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, GLvoid * ptr, const char * where)
Combine PBO-write validation and mapping.
If any GL errors are detected, they'll be recorded and NULL returned.
See also
_mesa_validate_pbo_access
_mesa_map_pbo_dest A call to this function should have a matching call to _mesa_unmap_pbo_dest().
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_validate_pbo_access(), and gl_pixelstore_attrib::BufferObj.
Referenced by _mesa_GetnPolygonStippleARB().
_mesa_map_validate_pbo_source()
const GLvoid* _mesa_map_validate_pbo_source (struct gl_context * ctx, GLuint dimensions, const struct gl_pixelstore_attrib * unpack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid * ptr, const char * where)
Perform PBO-read mapping.
If any GL errors are detected, they'll be recorded and NULL returned.
See also
_mesa_validate_pbo_source
_mesa_map_pbo_source A call to this function should have a matching call to _mesa_unmap_pbo_source().
References _mesa_map_pbo_source(), and _mesa_validate_pbo_source().
Referenced by _mesa_PolygonStipple().
_mesa_unmap_pbo_dest()
void _mesa_unmap_pbo_dest (struct gl_context * ctx, const struct gl_pixelstore_attrib * pack)
Counterpart to _mesa_map_pbo_dest()
References _mesa_is_bufferobj(), gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::UnmapBuffer, and gl_context::Unpack.
Referenced by _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_GetnPolygonStippleARB(), and _mesa_readpixels().
_mesa_unmap_pbo_source()
void _mesa_unmap_pbo_source (struct gl_context * ctx, const struct gl_pixelstore_attrib * unpack)
Counterpart to _mesa_map_pbo_source()
References _mesa_is_bufferobj(), gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, gl_context::Pack, and dd_function_table::UnmapBuffer.
Referenced by _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), and _mesa_PolygonStipple().
_mesa_unmap_teximage_pbo()
void _mesa_unmap_teximage_pbo (struct gl_context * ctx, const struct gl_pixelstore_attrib * unpack)
This function must be called after either of the validate_pbo_*_teximage() functions.
It unmaps the PBO buffer if it was mapped earlier.
References _mesa_is_bufferobj(), gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, and dd_function_table::UnmapBuffer.
Referenced by _mesa_store_compressed_texsubimage(), and store_texsubimage().
_mesa_validate_pbo_access()
GLboolean _mesa_validate_pbo_access (GLuint dimensions, const struct gl_pixelstore_attrib * pack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid * ptr)
When we're about to read pixel data out of a PBO (via glDrawPixels, glTexImage, etc) or write data into a PBO (via glReadPixels, glGetTexImage, etc) we call this function to check that we're not going to read/write out of bounds.
XXX This would also be a convenient time to check that the PBO isn't currently mapped. Whoever calls this function should check for that. Remember, we can't use a PBO when it's mapped!
If we're not using a PBO, this is a no-op.
Parameters
width width of image to read/write
height height of image to read/write
depth depth of image to read/write
format format of image to read/write
type datatype of image to read/write
clientMemSize the maximum number of bytes to read/write
ptr the user-provided pointer/offset
Returns
GL_TRUE if the buffer access is OK, GL_FALSE if the access would go out of bounds.
References _mesa_image_offset(), _mesa_is_bufferobj(), _mesa_sizeof_packed_type(), gl_pixelstore_attrib::BufferObj, and gl_buffer_object::Size.
Referenced by _mesa_Bitmap(), _mesa_DrawPixels(), _mesa_map_validate_pbo_dest(), _mesa_ReadnPixelsARB(), _mesa_validate_pbo_source(), _mesa_validate_pbo_teximage(), pbo_error_check(), unpack_image(), and validate_pbo_access().
_mesa_validate_pbo_compressed_teximage()
const GLvoid* _mesa_validate_pbo_compressed_teximage (struct gl_context * ctx, GLuint dimensions, GLsizei imageSize, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing, const char * funcName)
Check if an unpack PBO is active prior to fetching a compressed texture image.
If so, do bounds checking and map the buffer into main memory. Any errors detected will be recorded. The caller must call _mesa_unmap_teximage_pbo() too!
References _mesa_is_bufferobj(), _mesa_validate_pbo_source_compressed(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and gl_buffer_object::Size.
Referenced by _mesa_store_compressed_texsubimage().
_mesa_validate_pbo_source()
bool _mesa_validate_pbo_source (struct gl_context * ctx, GLuint dimensions, const struct gl_pixelstore_attrib * unpack, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid * ptr, const char * where)
Perform PBO validation for read operations with uncompressed textures.
If any GL errors are detected, false is returned, otherwise returns true.
See also
_mesa_validate_pbo_access
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), _mesa_validate_pbo_access(), and gl_pixelstore_attrib::BufferObj.
Referenced by _mesa_map_validate_pbo_source(), texsubimage_error_check(), and texture_error_check().
_mesa_validate_pbo_source_compressed()
bool _mesa_validate_pbo_source_compressed (struct gl_context * ctx, GLuint dimensions, const struct gl_pixelstore_attrib * unpack, GLsizei imageSize, const GLvoid * pixels, const char * where)
Perform PBO validation for read operations with compressed textures.
If any GL errors are detected, false is returned, otherwise returns true.
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), gl_pixelstore_attrib::BufferObj, and gl_buffer_object::Size.
Referenced by _mesa_validate_pbo_compressed_teximage(), compressed_subtexture_error_check(), and compressed_texture_error_check().
_mesa_validate_pbo_teximage()
const GLvoid* _mesa_validate_pbo_teximage (struct gl_context * ctx, GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * unpack, const char * funcName)
Check if an unpack PBO is active prior to fetching a texture image.
If so, do bounds checking and map the buffer into main memory. Any errors detected will be recorded. The caller must call _mesa_unmap_teximage_pbo() too!
References _mesa_error(), _mesa_is_bufferobj(), _mesa_validate_pbo_access(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, and gl_buffer_object::Size.
Referenced by store_texsubimage().