Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
performance_query.c File Reference
Core Mesa support for the INTEL_performance_query extension.
#include <stdbool.h>
#include "glheader.h"
#include "context.h"
#include "enums.h"
#include "hash.h"
#include "macros.h"
#include "mtypes.h"
#include "performance_query.h"
#include "util/ralloc.h"
Functions
void _mesa_init_performance_queries (struct gl_context *ctx)
static void free_performance_query (GLuint key, void *data, void *user)
void _mesa_free_performance_queries (struct gl_context *ctx)
static struct gl_perf_query_object * lookup_object (struct gl_context *ctx, GLuint id)
static GLuint init_performance_query_info (struct gl_context *ctx)
static unsigned queryid_to_index (GLuint queryid)
static GLuint index_to_queryid (unsigned index)
static bool queryid_valid (const struct gl_context *ctx, unsigned numQueries, GLuint queryid)
static GLuint counterid_to_index (GLuint counterid)
static void output_clipped_string (GLchar *stringRet, GLuint stringMaxLen, const char *string)
void GLAPIENTRY _mesa_GetFirstPerfQueryIdINTEL (GLuint *queryId)
void GLAPIENTRY _mesa_GetNextPerfQueryIdINTEL (GLuint queryId, GLuint *nextQueryId)
void GLAPIENTRY _mesa_GetPerfQueryIdByNameINTEL (char *queryName, GLuint *queryId)
void GLAPIENTRY _mesa_GetPerfQueryInfoINTEL (GLuint queryId, GLuint nameLength, GLchar *name, GLuint *dataSize, GLuint *numCounters, GLuint *numActive, GLuint *capsMask)
void GLAPIENTRY _mesa_GetPerfCounterInfoINTEL (GLuint queryId, GLuint counterId, GLuint nameLength, GLchar *name, GLuint descLength, GLchar *desc, GLuint *offset, GLuint *dataSize, GLuint *typeEnum, GLuint *dataTypeEnum, GLuint64 *rawCounterMaxValue)
void GLAPIENTRY _mesa_CreatePerfQueryINTEL (GLuint queryId, GLuint *queryHandle)
void GLAPIENTRY _mesa_DeletePerfQueryINTEL (GLuint queryHandle)
void GLAPIENTRY _mesa_BeginPerfQueryINTEL (GLuint queryHandle)
void GLAPIENTRY _mesa_EndPerfQueryINTEL (GLuint queryHandle)
void GLAPIENTRY _mesa_GetPerfQueryDataINTEL (GLuint queryHandle, GLuint flags, GLsizei dataSize, void *data, GLuint *bytesWritten)
Detailed Description
Core Mesa support for the INTEL_performance_query extension.
Function Documentation
_mesa_BeginPerfQueryINTEL()
void GLAPIENTRY _mesa_BeginPerfQueryINTEL (GLuint queryHandle)
References _mesa_error(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_object(), gl_perf_query_object::Ready, and gl_perf_query_object::Used.
_mesa_CreatePerfQueryINTEL()
void GLAPIENTRY _mesa_CreatePerfQueryINTEL (GLuint queryId, GLuint * queryHandle)
References _mesa_error(), _mesa_error_no_memory(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_perf_query_object::Id, init_performance_query_info(), queryid_to_index(), queryid_valid(), and gl_perf_query_object::Ready.
_mesa_DeletePerfQueryINTEL()
void GLAPIENTRY _mesa_DeletePerfQueryINTEL (GLuint queryHandle)
References _mesa_EndPerfQueryINTEL(), _mesa_error(), _mesa_HashRemove(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_object(), gl_perf_query_object::Ready, and gl_perf_query_object::Used.
_mesa_EndPerfQueryINTEL()
void GLAPIENTRY _mesa_EndPerfQueryINTEL (GLuint queryHandle)
References _mesa_error(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_object(), and gl_perf_query_object::Ready.
Referenced by _mesa_DeletePerfQueryINTEL().
_mesa_free_performance_queries()
void _mesa_free_performance_queries (struct gl_context * ctx)
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), free_performance_query(), gl_perf_query_state::Objects, and gl_context::PerfQuery.
Referenced by _mesa_free_context_data().
_mesa_GetFirstPerfQueryIdINTEL()
void GLAPIENTRY _mesa_GetFirstPerfQueryIdINTEL (GLuint * queryId)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, index_to_queryid(), and init_performance_query_info().
_mesa_GetNextPerfQueryIdINTEL()
void GLAPIENTRY _mesa_GetNextPerfQueryIdINTEL (GLuint queryId, GLuint * nextQueryId)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, init_performance_query_info(), and queryid_valid().
_mesa_GetPerfCounterInfoINTEL()
void GLAPIENTRY _mesa_GetPerfCounterInfoINTEL (GLuint queryId, GLuint counterId, GLuint nameLength, GLchar * name, GLuint descLength, GLchar * desc, GLuint * offset, GLuint * dataSize, GLuint * typeEnum, GLuint * dataTypeEnum, GLuint64 * rawCounterMaxValue)
References _mesa_error(), counterid_to_index(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, init_performance_query_info(), output_clipped_string(), queryid_to_index(), and queryid_valid().
_mesa_GetPerfQueryDataINTEL()
void GLAPIENTRY _mesa_GetPerfQueryDataINTEL (GLuint queryHandle, GLuint flags, GLsizei dataSize, void * data, GLuint * bytesWritten)
References _mesa_error(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, lookup_object(), and gl_perf_query_object::Ready.
_mesa_GetPerfQueryIdByNameINTEL()
void GLAPIENTRY _mesa_GetPerfQueryIdByNameINTEL (char * queryName, GLuint * queryId)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, index_to_queryid(), and init_performance_query_info().
_mesa_GetPerfQueryInfoINTEL()
void GLAPIENTRY _mesa_GetPerfQueryInfoINTEL (GLuint queryId, GLuint nameLength, GLchar * name, GLuint * dataSize, GLuint * numCounters, GLuint * numActive, GLuint * capsMask)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, init_performance_query_info(), output_clipped_string(), queryid_to_index(), and queryid_valid().
_mesa_init_performance_queries()
void _mesa_init_performance_queries (struct gl_context * ctx)
References _mesa_NewHashTable(), gl_perf_query_state::Objects, and gl_context::PerfQuery.
Referenced by init_attrib_groups().
counterid_to_index()
static GLuint counterid_to_index (GLuint counterid) inline static
Referenced by _mesa_GetPerfCounterInfoINTEL().
free_performance_query()
static void free_performance_query (GLuint key, void * data, void * user) static
References dd_function_table::DeletePerfQuery, and gl_context::Driver.
Referenced by _mesa_free_performance_queries().
index_to_queryid()
static GLuint index_to_queryid (unsigned index) inline static
Referenced by _mesa_GetFirstPerfQueryIdINTEL(), and _mesa_GetPerfQueryIdByNameINTEL().
init_performance_query_info()
static GLuint init_performance_query_info (struct gl_context * ctx) static
References gl_context::Driver, and dd_function_table::InitPerfQueryInfo.
Referenced by _mesa_CreatePerfQueryINTEL(), _mesa_GetFirstPerfQueryIdINTEL(), _mesa_GetNextPerfQueryIdINTEL(), _mesa_GetPerfCounterInfoINTEL(), _mesa_GetPerfQueryIdByNameINTEL(), and _mesa_GetPerfQueryInfoINTEL().
lookup_object()
static struct gl_perf_query_object* lookup_object (struct gl_context * ctx, GLuint id) static
References _mesa_HashLookup(), GLuint, gl_perf_query_state::Objects, and gl_context::PerfQuery.
Referenced by _mesa_BeginPerfQueryINTEL(), _mesa_DeletePerfQueryINTEL(), _mesa_EndPerfQueryINTEL(), and _mesa_GetPerfQueryDataINTEL().
output_clipped_string()
static void output_clipped_string (GLchar * stringRet, GLuint stringMaxLen, const char * string) static
References GLAPIENTRY.
Referenced by _mesa_GetPerfCounterInfoINTEL(), and _mesa_GetPerfQueryInfoINTEL().
queryid_to_index()
static unsigned queryid_to_index (GLuint queryid) inline static
References GLuint.
Referenced by _mesa_CreatePerfQueryINTEL(), _mesa_GetPerfCounterInfoINTEL(), _mesa_GetPerfQueryInfoINTEL(), and queryid_valid().
queryid_valid()
static bool queryid_valid (const struct gl_context * ctx, unsigned numQueries, GLuint queryid) inline static
References GLuint, and queryid_to_index().
Referenced by _mesa_CreatePerfQueryINTEL(), _mesa_GetNextPerfQueryIdINTEL(), _mesa_GetPerfCounterInfoINTEL(), and _mesa_GetPerfQueryInfoINTEL().