Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
performance_monitor.h File Reference
Core Mesa support for the AMD_performance_monitor extension and the INTEL_performance_query extension.
#include "glheader.h"
Functions
void _mesa_init_performance_monitors (struct gl_context *ctx)
void _mesa_free_performance_monitors (struct gl_context *ctx)
void GLAPIENTRY _mesa_GetPerfMonitorGroupsAMD (GLint *numGroups, GLsizei groupsSize, GLuint *groups)
void GLAPIENTRY _mesa_GetPerfMonitorCountersAMD (GLuint group, GLint *numCounters, GLint *maxActiveCounters, GLsizei countersSize, GLuint *counters)
void GLAPIENTRY _mesa_GetPerfMonitorGroupStringAMD (GLuint group, GLsizei bufSize, GLsizei *length, GLchar *groupString)
void GLAPIENTRY _mesa_GetPerfMonitorCounterStringAMD (GLuint group, GLuint counter, GLsizei bufSize, GLsizei *length, GLchar *counterString)
void GLAPIENTRY _mesa_GetPerfMonitorCounterInfoAMD (GLuint group, GLuint counter, GLenum pname, GLvoid *data)
void GLAPIENTRY _mesa_GenPerfMonitorsAMD (GLsizei n, GLuint *monitors)
void GLAPIENTRY _mesa_DeletePerfMonitorsAMD (GLsizei n, GLuint *monitors)
void GLAPIENTRY _mesa_SelectPerfMonitorCountersAMD (GLuint monitor, GLboolean enable, GLuint group, GLint numCounters, GLuint *counterList)
void GLAPIENTRY _mesa_BeginPerfMonitorAMD (GLuint monitor)
void GLAPIENTRY _mesa_EndPerfMonitorAMD (GLuint monitor)
void GLAPIENTRY _mesa_GetPerfMonitorCounterDataAMD (GLuint monitor, GLenum pname, GLsizei dataSize, GLuint *data, GLint *bytesWritten)
unsigned _mesa_perf_monitor_counter_size (const struct gl_perf_monitor_counter *)
Returns how many bytes a counter's value takes up.
Detailed Description
Core Mesa support for the AMD_performance_monitor extension and the INTEL_performance_query extension.
Function Documentation
_mesa_BeginPerfMonitorAMD()
void GLAPIENTRY _mesa_BeginPerfMonitorAMD (GLuint monitor)
References _mesa_error(), gl_perf_monitor_object::Active, gl_perf_monitor_object::Ended, GET_CURRENT_CONTEXT, GLAPIENTRY, and lookup_monitor().
_mesa_DeletePerfMonitorsAMD()
void GLAPIENTRY _mesa_DeletePerfMonitorsAMD (GLsizei n, GLuint * monitors)
References _mesa_debug(), _mesa_error(), _mesa_HashRemove(), gl_perf_monitor_object::Active, gl_perf_monitor_object::ActiveCounters, gl_perf_monitor_object::ActiveGroups, gl_perf_monitor_object::Ended, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_monitor(), MESA_VERBOSE, and VERBOSE_API.
_mesa_EndPerfMonitorAMD()
void GLAPIENTRY _mesa_EndPerfMonitorAMD (GLuint monitor)
References _mesa_error(), gl_perf_monitor_object::Active, gl_perf_monitor_object::Ended, GET_CURRENT_CONTEXT, and lookup_monitor().
_mesa_free_performance_monitors()
void _mesa_free_performance_monitors (struct gl_context * ctx)
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), free_performance_monitor(), gl_perf_monitor_state::Monitors, and gl_context::PerfMonitor.
Referenced by _mesa_free_context_data().
_mesa_GenPerfMonitorsAMD()
void GLAPIENTRY _mesa_GenPerfMonitorsAMD (GLsizei n, GLuint * monitors)
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, init_groups(), MESA_VERBOSE, new_performance_monitor(), and VERBOSE_API.
_mesa_GetPerfMonitorCounterDataAMD()
void GLAPIENTRY _mesa_GetPerfMonitorCounterDataAMD (GLuint monitor, GLenum pname, GLsizei dataSize, GLuint * data, GLint * bytesWritten)
References _mesa_error(), gl_perf_monitor_object::Ended, GET_CURRENT_CONTEXT, GLuint, lookup_monitor(), and perf_monitor_result_size().
_mesa_GetPerfMonitorCounterInfoAMD()
void GLAPIENTRY _mesa_GetPerfMonitorCounterInfoAMD (GLuint group, GLuint counter, GLenum pname, GLvoid * data)
References _mesa_error(), gl_perf_monitor_counter_value::f, get_counter(), GET_CURRENT_CONTEXT, get_group(), GLAPIENTRY, init_groups(), gl_perf_monitor_counter::Maximum, gl_perf_monitor_counter::Minimum, gl_perf_monitor_counter::Type, gl_perf_monitor_counter_value::u32, and gl_perf_monitor_counter_value::u64.
_mesa_GetPerfMonitorCountersAMD()
void GLAPIENTRY _mesa_GetPerfMonitorCountersAMD (GLuint group, GLint * numCounters, GLint * maxActiveCounters, GLsizei countersSize, GLuint * counters)
References _mesa_error(), GET_CURRENT_CONTEXT, get_group(), GLAPIENTRY, GLuint, init_groups(), gl_perf_monitor_group::MaxActiveCounters, and gl_perf_monitor_group::NumCounters.
_mesa_GetPerfMonitorCounterStringAMD()
void GLAPIENTRY _mesa_GetPerfMonitorCounterStringAMD (GLuint group, GLuint counter, GLsizei bufSize, GLsizei * length, GLchar * counterString)
References _mesa_error(), get_counter(), GET_CURRENT_CONTEXT, get_group(), GLAPIENTRY, init_groups(), and gl_perf_monitor_counter::Name.
_mesa_GetPerfMonitorGroupsAMD()
void GLAPIENTRY _mesa_GetPerfMonitorGroupsAMD (GLint * numGroups, GLsizei groupsSize, GLuint * groups)
References GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, and init_groups().
_mesa_GetPerfMonitorGroupStringAMD()
void GLAPIENTRY _mesa_GetPerfMonitorGroupStringAMD (GLuint group, GLsizei bufSize, GLsizei * length, GLchar * groupString)
References _mesa_error(), GET_CURRENT_CONTEXT, get_group(), GLAPIENTRY, init_groups(), and gl_perf_monitor_group::Name.
_mesa_init_performance_monitors()
void _mesa_init_performance_monitors (struct gl_context * ctx)
References _mesa_NewHashTable(), gl_perf_monitor_state::Groups, gl_perf_monitor_state::Monitors, gl_perf_monitor_state::NumGroups, and gl_context::PerfMonitor.
Referenced by init_attrib_groups().
_mesa_perf_monitor_counter_size()
unsigned _mesa_perf_monitor_counter_size (const struct gl_perf_monitor_counter *)
Returns how many bytes a counter's value takes up.
References GLuint, and gl_perf_monitor_counter::Type.
Referenced by perf_monitor_result_size().
_mesa_SelectPerfMonitorCountersAMD()
void GLAPIENTRY _mesa_SelectPerfMonitorCountersAMD (GLuint monitor, GLboolean enable, GLuint group, GLint numCounters, GLuint * counterList)
References _mesa_error(), gl_perf_monitor_object::ActiveCounters, gl_perf_monitor_object::ActiveGroups, GET_CURRENT_CONTEXT, get_group(), GLAPIENTRY, lookup_monitor(), and gl_perf_monitor_group::NumCounters.