Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
performance_query.h File Reference
Core Mesa support for the INTEL_performance_query extension.
#include "glheader.h"
Functions
void _mesa_init_performance_queries (struct gl_context *ctx)
void _mesa_free_performance_queries (struct gl_context *ctx)
void GLAPIENTRY _mesa_GetFirstPerfQueryIdINTEL (GLuint *queryId)
void GLAPIENTRY _mesa_GetNextPerfQueryIdINTEL (GLuint queryId, GLuint *nextQueryId)
void GLAPIENTRY _mesa_GetPerfQueryIdByNameINTEL (char *queryName, GLuint *queryId)
void GLAPIENTRY _mesa_GetPerfQueryInfoINTEL (GLuint queryId, GLuint queryNameLength, char *queryName, GLuint *dataSize, GLuint *noCounters, GLuint *noActiveInstances, GLuint *capsMask)
void GLAPIENTRY _mesa_GetPerfCounterInfoINTEL (GLuint queryId, GLuint counterId, GLuint counterNameLength, char *counterName, GLuint counterDescLength, char *counterDesc, GLuint *counterOffset, GLuint *counterDataSize, GLuint *counterTypeEnum, GLuint *counterDataTypeEnum, GLuint64 *rawCounterMaxValue)
void GLAPIENTRY _mesa_CreatePerfQueryINTEL (GLuint queryId, GLuint *queryHandle)
void GLAPIENTRY _mesa_DeletePerfQueryINTEL (GLuint queryHandle)
void GLAPIENTRY _mesa_BeginPerfQueryINTEL (GLuint queryHandle)
void GLAPIENTRY _mesa_EndPerfQueryINTEL (GLuint queryHandle)
void GLAPIENTRY _mesa_GetPerfQueryDataINTEL (GLuint queryHandle, GLuint flags, GLsizei dataSize, void *data, GLuint *bytesWritten)
Detailed Description
Core Mesa support for the INTEL_performance_query extension.
Function Documentation
_mesa_BeginPerfQueryINTEL()
void GLAPIENTRY _mesa_BeginPerfQueryINTEL (GLuint queryHandle)
References _mesa_error(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_object(), gl_perf_query_object::Ready, and gl_perf_query_object::Used.
_mesa_CreatePerfQueryINTEL()
void GLAPIENTRY _mesa_CreatePerfQueryINTEL (GLuint queryId, GLuint * queryHandle)
References _mesa_error(), _mesa_error_no_memory(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_perf_query_object::Id, init_performance_query_info(), queryid_to_index(), queryid_valid(), and gl_perf_query_object::Ready.
_mesa_DeletePerfQueryINTEL()
void GLAPIENTRY _mesa_DeletePerfQueryINTEL (GLuint queryHandle)
References _mesa_EndPerfQueryINTEL(), _mesa_error(), _mesa_HashRemove(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_object(), gl_perf_query_object::Ready, and gl_perf_query_object::Used.
_mesa_EndPerfQueryINTEL()
void GLAPIENTRY _mesa_EndPerfQueryINTEL (GLuint queryHandle)
References _mesa_error(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_object(), and gl_perf_query_object::Ready.
Referenced by _mesa_DeletePerfQueryINTEL().
_mesa_free_performance_queries()
void _mesa_free_performance_queries (struct gl_context * ctx)
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), free_performance_query(), gl_perf_query_state::Objects, and gl_context::PerfQuery.
Referenced by _mesa_free_context_data().
_mesa_GetFirstPerfQueryIdINTEL()
void GLAPIENTRY _mesa_GetFirstPerfQueryIdINTEL (GLuint * queryId)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, index_to_queryid(), and init_performance_query_info().
_mesa_GetNextPerfQueryIdINTEL()
void GLAPIENTRY _mesa_GetNextPerfQueryIdINTEL (GLuint queryId, GLuint * nextQueryId)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, init_performance_query_info(), and queryid_valid().
_mesa_GetPerfCounterInfoINTEL()
void GLAPIENTRY _mesa_GetPerfCounterInfoINTEL (GLuint queryId, GLuint counterId, GLuint counterNameLength, char * counterName, GLuint counterDescLength, char * counterDesc, GLuint * counterOffset, GLuint * counterDataSize, GLuint * counterTypeEnum, GLuint * counterDataTypeEnum, GLuint64 * rawCounterMaxValue)
_mesa_GetPerfQueryDataINTEL()
void GLAPIENTRY _mesa_GetPerfQueryDataINTEL (GLuint queryHandle, GLuint flags, GLsizei dataSize, void * data, GLuint * bytesWritten)
References _mesa_error(), gl_perf_query_object::Active, GET_CURRENT_CONTEXT, lookup_object(), and gl_perf_query_object::Ready.
_mesa_GetPerfQueryIdByNameINTEL()
void GLAPIENTRY _mesa_GetPerfQueryIdByNameINTEL (char * queryName, GLuint * queryId)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, index_to_queryid(), and init_performance_query_info().
_mesa_GetPerfQueryInfoINTEL()
void GLAPIENTRY _mesa_GetPerfQueryInfoINTEL (GLuint queryId, GLuint queryNameLength, char * queryName, GLuint * dataSize, GLuint * noCounters, GLuint * noActiveInstances, GLuint * capsMask)
_mesa_init_performance_queries()
void _mesa_init_performance_queries (struct gl_context * ctx)
References _mesa_NewHashTable(), gl_perf_query_state::Objects, and gl_context::PerfQuery.
Referenced by init_attrib_groups().