Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
pipelineobj.c File Reference
#include <stdbool.h>
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/enums.h"
#include "main/hash.h"
#include "main/mtypes.h"
#include "main/pipelineobj.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/transformfeedback.h"
#include "main/uniforms.h"
#include "compiler/glsl/glsl_parser_extras.h"
#include "compiler/glsl/ir_uniform.h"
#include "program/program.h"
#include "program/prog_parameter.h"
#include "util/ralloc.h"
Functions
void _mesa_delete_pipeline_object (struct gl_context *ctx, struct gl_pipeline_object *obj)
Delete a pipeline object.
static struct gl_pipeline_object * _mesa_new_pipeline_object (struct gl_context *ctx, GLuint name)
Allocate and initialize a new pipeline object.
void _mesa_init_pipeline (struct gl_context *ctx)
Initialize pipeline object state for given context.
static void delete_pipelineobj_cb (UNUSED GLuint id, void *data, void *userData)
Callback for deleting a pipeline object.
void _mesa_free_pipeline_data (struct gl_context *ctx)
Free pipeline state for given context.
struct gl_pipeline_object * _mesa_lookup_pipeline_object (struct gl_context *ctx, GLuint id)
Look up the pipeline object for the given ID.
static void save_pipeline_object (struct gl_context *ctx, struct gl_pipeline_object *obj)
Add the given pipeline object to the pipeline object pool.
static void remove_pipeline_object (struct gl_context *ctx, struct gl_pipeline_object *obj)
Remove the given pipeline object from the pipeline object pool.
void _mesa_reference_pipeline_object_ (struct gl_context *ctx, struct gl_pipeline_object **ptr, struct gl_pipeline_object *obj)
Set ptr to obj w/ reference counting.
static void use_program_stage (struct gl_context *ctx, GLenum type, struct gl_shader_program *shProg, struct gl_pipeline_object *pipe)
void GLAPIENTRY _mesa_UseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program)
Bound program to severals stages of the pipeline.
void GLAPIENTRY _mesa_ActiveShaderProgram (GLuint pipeline, GLuint program)
Use the named shader program for subsequent glUniform calls (if pipeline bound)
void GLAPIENTRY _mesa_BindProgramPipeline (GLuint pipeline)
Make program of the pipeline current.
void _mesa_bind_pipeline (struct gl_context *ctx, struct gl_pipeline_object *pipe)
void GLAPIENTRY _mesa_DeleteProgramPipelines (GLsizei n, const GLuint *pipelines)
Delete a set of pipeline objects.
static void create_program_pipelines (struct gl_context *ctx, GLsizei n, GLuint *pipelines, bool dsa)
Generate a set of unique pipeline object IDs and store them in pipelines.
void GLAPIENTRY _mesa_GenProgramPipelines (GLsizei n, GLuint *pipelines)
void GLAPIENTRY _mesa_CreateProgramPipelines (GLsizei n, GLuint *pipelines)
GLboolean GLAPIENTRY _mesa_IsProgramPipeline (GLuint pipeline)
Determine if ID is the name of an pipeline object.
void GLAPIENTRY _mesa_GetProgramPipelineiv (GLuint pipeline, GLenum pname, GLint *params)
glGetProgramPipelineiv() - get pipeline shader state.
static bool program_stages_all_active (struct gl_pipeline_object *pipe, const struct gl_program *prog)
Determines whether every stage in a linked program is active in the specified pipeline.
static bool program_stages_interleaved_illegally (const struct gl_pipeline_object *pipe)
GLboolean _mesa_validate_program_pipeline (struct gl_context *ctx, struct gl_pipeline_object *pipe)
void GLAPIENTRY _mesa_ValidateProgramPipeline (GLuint pipeline)
Check compatibility of pipeline's program.
void GLAPIENTRY _mesa_GetProgramPipelineInfoLog (GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
Detailed Description
Author
Hainaut Gregory grego.nosp@m.ry.h.nosp@m.ainau.nosp@m.t@gm.nosp@m.ail.c.nosp@m.om
Implementation of pipeline object related API functions. Based on GL_ARB_separate_shader_objects extension.
Function Documentation
_mesa_ActiveShaderProgram()
void GLAPIENTRY _mesa_ActiveShaderProgram (GLuint pipeline, GLuint program)
Use the named shader program for subsequent glUniform calls (if pipeline bound)
References _mesa_debug(), _mesa_error(), _mesa_lookup_pipeline_object(), _mesa_lookup_shader_program_err(), _mesa_reference_shader_program(), gl_pipeline_object::ActiveProgram, gl_shader_program::data, gl_pipeline_object::EverBound, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_shader_program_data::LinkStatus, MESA_VERBOSE, gl_shader_program::Name, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_bind_pipeline()
void _mesa_bind_pipeline (struct gl_context * ctx, struct gl_pipeline_object * pipe)
References _mesa_program_init_subroutine_defaults(), _mesa_reference_pipeline_object(), _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, gl_context::_Shader, gl_pipeline_shader_state::Current, gl_pipeline_object::CurrentProgram, gl_pipeline_shader_state::Default, FLUSH_VERTICES, GLAPIENTRY, gl_context::Pipeline, and gl_context::Shader.
Referenced by _mesa_BindProgramPipeline(), and _mesa_reference_pipeline_object().
_mesa_BindProgramPipeline()
void GLAPIENTRY _mesa_BindProgramPipeline (GLuint pipeline)
Make program of the pipeline current.
References _mesa_bind_pipeline(), _mesa_debug(), _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_pipeline_object(), gl_pipeline_object::EverBound, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_DeleteProgramPipelines(), _mesa_reference_pipeline_object(), and _mesa_UseProgram().
_mesa_CreateProgramPipelines()
void GLAPIENTRY _mesa_CreateProgramPipelines (GLsizei n, GLuint * pipelines)
References _mesa_debug(), create_program_pipelines(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_delete_pipeline_object()
void _mesa_delete_pipeline_object (struct gl_context * ctx, struct gl_pipeline_object * obj)
Delete a pipeline object.
References gl_pipeline_object::_CurrentFragmentProgram, _mesa_reference_shader_program(), gl_pipeline_object::ActiveProgram, gl_pipeline_object::CurrentProgram, gl_pipeline_object::Label, gl_pipeline_object::Mutex, and gl_pipeline_object::ReferencedPrograms.
Referenced by _mesa_free_pipeline_data(), _mesa_reference_pipeline_object_(), and delete_pipelineobj_cb().
_mesa_DeleteProgramPipelines()
void GLAPIENTRY _mesa_DeleteProgramPipelines (GLsizei n, const GLuint * pipelines)
Delete a set of pipeline objects.
Parameters
n Number of pipeline objects to delete.
ids pipeline of n pipeline object IDs.
References _mesa_BindProgramPipeline(), _mesa_debug(), _mesa_error(), _mesa_lookup_pipeline_object(), _mesa_reference_pipeline_object(), GET_CURRENT_CONTEXT, MESA_VERBOSE, gl_pipeline_object::Name, remove_pipeline_object(), and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_free_pipeline_data()
void _mesa_free_pipeline_data (struct gl_context * ctx)
Free pipeline state for given context.
References _mesa_delete_pipeline_object(), _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), _mesa_reference_pipeline_object(), gl_context::_Shader, gl_pipeline_shader_state::Default, delete_pipelineobj_cb(), gl_pipeline_shader_state::Objects, and gl_context::Pipeline.
Referenced by _mesa_free_context_data().
_mesa_GenProgramPipelines()
void GLAPIENTRY _mesa_GenProgramPipelines (GLsizei n, GLuint * pipelines)
References _mesa_debug(), create_program_pipelines(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_GetProgramPipelineInfoLog()
void GLAPIENTRY _mesa_GetProgramPipelineInfoLog (GLuint pipeline, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References _mesa_copy_string(), _mesa_debug(), _mesa_error(), _mesa_lookup_pipeline_object(), GET_CURRENT_CONTEXT, gl_pipeline_object::InfoLog, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_GetProgramPipelineiv()
void GLAPIENTRY _mesa_GetProgramPipelineiv (GLuint pipeline, GLenum pname, GLint * params)
glGetProgramPipelineiv() - get pipeline shader state.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_lookup_pipeline_object(), gl_pipeline_object::ActiveProgram, gl_pipeline_object::CurrentProgram, gl_pipeline_object::EverBound, GET_CURRENT_CONTEXT, gl_program::Id, gl_pipeline_object::InfoLog, MESA_VERBOSE, gl_shader_program::Name, gl_pipeline_object::Validated, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_init_pipeline()
void _mesa_init_pipeline (struct gl_context * ctx)
Initialize pipeline object state for given context.
References _mesa_new_pipeline_object(), _mesa_NewHashTable(), _mesa_reference_pipeline_object(), gl_context::_Shader, gl_pipeline_shader_state::Current, gl_pipeline_shader_state::Default, gl_pipeline_shader_state::Objects, and gl_context::Pipeline.
Referenced by init_attrib_groups().
_mesa_IsProgramPipeline()
GLboolean GLAPIENTRY _mesa_IsProgramPipeline (GLuint pipeline)
Determine if ID is the name of an pipeline object.
Parameters
id ID of the potential pipeline object.
Returns
GL_TRUE if id is the name of a pipeline object, GL_FALSE otherwise.
References _mesa_debug(), _mesa_lookup_pipeline_object(), gl_pipeline_object::EverBound, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_lookup_pipeline_object()
struct gl_pipeline_object* _mesa_lookup_pipeline_object (struct gl_context * ctx, GLuint id)
Look up the pipeline object for the given ID.
Returns
Either a pointer to the pipeline object with the specified ID or NULL for a non-existent ID. The spec defines ID 0 as being technically non-existent.
References _mesa_HashLookup(), gl_pipeline_shader_state::Objects, and gl_context::Pipeline.
Referenced by _mesa_ActiveShaderProgram(), _mesa_BindProgramPipeline(), _mesa_DeleteProgramPipelines(), _mesa_GetProgramPipelineInfoLog(), _mesa_GetProgramPipelineiv(), _mesa_IsProgramPipeline(), _mesa_UseProgramStages(), _mesa_ValidateProgramPipeline(), and get_label_pointer().
_mesa_new_pipeline_object()
static struct gl_pipeline_object* _mesa_new_pipeline_object (struct gl_context * ctx, GLuint name) static
Allocate and initialize a new pipeline object.
References _mesa_get_shader_flags(), gl_pipeline_object::Flags, gl_pipeline_object::InfoLog, gl_pipeline_object::Mutex, gl_pipeline_object::Name, and gl_pipeline_object::RefCount.
Referenced by _mesa_init_pipeline(), and create_program_pipelines().
_mesa_reference_pipeline_object_()
void _mesa_reference_pipeline_object_ (struct gl_context * ctx, struct gl_pipeline_object ** ptr, struct gl_pipeline_object * obj)
Set ptr to obj w/ reference counting.
Note: this should only be called from the _mesa_reference_pipeline_object() inline function.
References _mesa_delete_pipeline_object(), _mesa_problem(), gl_pipeline_object::Mutex, and gl_pipeline_object::RefCount.
Referenced by _mesa_reference_pipeline_object().
_mesa_UseProgramStages()
void GLAPIENTRY _mesa_UseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program)
Bound program to severals stages of the pipeline.
References _mesa_debug(), _mesa_error(), _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_pipeline_object(), _mesa_lookup_shader_program_err(), gl_shader_program::data, gl_pipeline_object::EverBound, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_shader_program_data::LinkStatus, MESA_VERBOSE, gl_shader_program::SeparateShader, use_program_stage(), gl_pipeline_object::Validated, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
_mesa_validate_program_pipeline()
GLboolean _mesa_validate_program_pipeline (struct gl_context * ctx, struct gl_pipeline_object * pipe)
References _mesa_gl_debug(), _mesa_is_gles(), _mesa_sampler_uniforms_pipeline_are_valid(), _mesa_validate_pipeline_io(), gl_context::Const, gl_constants::ContextFlags, gl_pipeline_object::CurrentProgram, GLAPIENTRY, GLuint, gl_program::Id, gl_program::info, gl_pipeline_object::InfoLog, MESA_DEBUG_SEVERITY_MEDIUM, MESA_DEBUG_SOURCE_API, MESA_DEBUG_TYPE_PORTABILITY, gl_pipeline_object::Name, program_stages_all_active(), program_stages_interleaved_illegally(), and gl_pipeline_object::Validated.
Referenced by _mesa_reference_pipeline_object(), _mesa_valid_to_render(), and _mesa_ValidateProgramPipeline().
_mesa_ValidateProgramPipeline()
void GLAPIENTRY _mesa_ValidateProgramPipeline (GLuint pipeline)
Check compatibility of pipeline's program.
References _mesa_debug(), _mesa_error(), _mesa_lookup_pipeline_object(), _mesa_validate_program_pipeline(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_reference_pipeline_object().
create_program_pipelines()
static void create_program_pipelines (struct gl_context * ctx, GLsizei n, GLuint * pipelines, bool dsa) static
Generate a set of unique pipeline object IDs and store them in pipelines.
Parameters
n Number of IDs to generate.
pipelines pipeline of n locations to store the IDs.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_new_pipeline_object(), gl_pipeline_object::EverBound, GLAPIENTRY, GLuint, gl_pipeline_shader_state::Objects, gl_context::Pipeline, and save_pipeline_object().
Referenced by _mesa_CreateProgramPipelines(), and _mesa_GenProgramPipelines().
delete_pipelineobj_cb()
static void delete_pipelineobj_cb (UNUSED GLuint id, void * data, void * userData) static
Callback for deleting a pipeline object.
Called by _mesa_HashDeleteAll().
References _mesa_delete_pipeline_object().
Referenced by _mesa_free_pipeline_data().
program_stages_all_active()
static bool program_stages_all_active (struct gl_pipeline_object * pipe, const struct gl_program * prog) static
Determines whether every stage in a linked program is active in the specified pipeline.
References gl_pipeline_object::CurrentProgram, gl_program::Id, gl_pipeline_object::InfoLog, and gl_program::sh.
Referenced by _mesa_validate_program_pipeline().
program_stages_interleaved_illegally()
static bool program_stages_interleaved_illegally (const struct gl_pipeline_object * pipe) static
References gl_pipeline_object::CurrentProgram, and gl_program::sh.
Referenced by _mesa_validate_program_pipeline().
remove_pipeline_object()
static void remove_pipeline_object (struct gl_context * ctx, struct gl_pipeline_object * obj) static
Remove the given pipeline object from the pipeline object pool.
Do not deallocate the pipeline object though.
References _mesa_HashRemove(), gl_pipeline_object::Name, gl_pipeline_shader_state::Objects, and gl_context::Pipeline.
Referenced by _mesa_DeleteProgramPipelines().
save_pipeline_object()
static void save_pipeline_object (struct gl_context * ctx, struct gl_pipeline_object * obj) static
Add the given pipeline object to the pipeline object pool.
References _mesa_HashInsert(), gl_pipeline_object::Name, gl_pipeline_shader_state::Objects, and gl_context::Pipeline.
Referenced by create_program_pipelines().
use_program_stage()
static void use_program_stage (struct gl_context * ctx, GLenum type, struct gl_shader_program * shProg, struct gl_pipeline_object * pipe) static
References gl_shader_program::_LinkedShaders, _mesa_shader_enum_to_shader_stage(), _mesa_use_program(), GLAPIENTRY, and gl_linked_shader::Program.
Referenced by _mesa_UseProgramStages().