Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
pixeltransfer.c File Reference
Pixel transfer operations (scale, bias, table lookups, etc)
#include "glheader.h"
#include "macros.h"
#include "pixeltransfer.h"
#include "imports.h"
#include "mtypes.h"
#include "util/rounding.h"
Functions
void _mesa_scale_and_bias_rgba (GLuint n, GLfloat rgba[][4], GLfloat rScale, GLfloat gScale, GLfloat bScale, GLfloat aScale, GLfloat rBias, GLfloat gBias, GLfloat bBias, GLfloat aBias)
void _mesa_map_rgba (const struct gl_context *ctx, GLuint n, GLfloat rgba[][4])
void _mesa_map_ci_to_rgba (const struct gl_context *ctx, GLuint n, const GLuint index[], GLfloat rgba[][4])
void _mesa_scale_and_bias_depth (const struct gl_context *ctx, GLuint n, GLfloat depthValues[])
void _mesa_scale_and_bias_depth_uint (const struct gl_context *ctx, GLuint n, GLuint depthValues[])
void _mesa_apply_rgba_transfer_ops (struct gl_context *ctx, GLbitfield transferOps, GLuint n, GLfloat rgba[][4])
Apply various pixel transfer operations to an array of RGBA pixels as indicated by the transferOps bitmask.
void _mesa_shift_and_offset_ci (const struct gl_context *ctx, GLuint n, GLuint indexes[])
void _mesa_apply_ci_transfer_ops (const struct gl_context *ctx, GLbitfield transferOps, GLuint n, GLuint indexes[])
Apply color index shift, offset and table lookup to an array of color indexes;.
void _mesa_apply_stencil_transfer_ops (const struct gl_context *ctx, GLuint n, GLubyte stencil[])
Apply stencil index shift, offset and table lookup to an array of stencil values.
Detailed Description
Pixel transfer operations (scale, bias, table lookups, etc)
Function Documentation
_mesa_apply_ci_transfer_ops()
void _mesa_apply_ci_transfer_ops (const struct gl_context * ctx, GLbitfield transferOps, GLuint n, GLuint indexes[])
Apply color index shift, offset and table lookup to an array of color indexes;.
References _mesa_shift_and_offset_ci(), GLuint, IMAGE_MAP_COLOR_BIT, IMAGE_SHIFT_OFFSET_BIT, gl_pixelmaps::ItoI, gl_pixelmap::Map, gl_context::PixelMaps, and gl_pixelmap::Size.
_mesa_apply_rgba_transfer_ops()
void _mesa_apply_rgba_transfer_ops (struct gl_context * ctx, GLbitfield transferOps, GLuint n, GLfloat rgba[][4])
Apply various pixel transfer operations to an array of RGBA pixels as indicated by the transferOps bitmask.
References _mesa_map_rgba(), _mesa_scale_and_bias_rgba(), ACOMP, gl_pixel_attrib::AlphaBias, gl_pixel_attrib::AlphaScale, BCOMP, gl_pixel_attrib::BlueBias, gl_pixel_attrib::BlueScale, F, GCOMP, GLuint, gl_pixel_attrib::GreenBias, gl_pixel_attrib::GreenScale, IMAGE_CLAMP_BIT, IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, gl_context::Pixel, RCOMP, gl_pixel_attrib::RedBias, and gl_pixel_attrib::RedScale.
Referenced by _mesa_unpack_color_index_to_rgba_float(), get_tex_rgba_uncompressed(), read_rgba_pixels(), and texstore_rgba().
_mesa_apply_stencil_transfer_ops()
void _mesa_apply_stencil_transfer_ops (const struct gl_context * ctx, GLuint n, GLubyte stencil[])
Apply stencil index shift, offset and table lookup to an array of stencil values.
References GLuint, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixelmap::Map, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, gl_context::PixelMaps, gl_pixelmap::Size, and gl_pixelmaps::StoS.
Referenced by _mesa_pack_depth_stencil_span(), and _mesa_pack_stencil_span().
_mesa_map_ci_to_rgba()
void _mesa_map_ci_to_rgba (const struct gl_context * ctx, GLuint n, const GLuint index[], GLfloat rgba[][4])
References ACOMP, BCOMP, GCOMP, GLuint, gl_pixelmaps::ItoA, gl_pixelmaps::ItoB, gl_pixelmaps::ItoG, gl_pixelmaps::ItoR, gl_pixelmap::Map, gl_context::PixelMaps, RCOMP, and gl_pixelmap::Size.
Referenced by _mesa_unpack_color_index_to_rgba_float().
_mesa_map_rgba()
void _mesa_map_rgba (const struct gl_context * ctx, GLuint n, GLfloat rgba[][4])
References ACOMP, gl_pixelmaps::AtoA, BCOMP, gl_pixelmaps::BtoB, F, GCOMP, GLuint, gl_pixelmaps::GtoG, gl_pixelmap::Map, gl_context::PixelMaps, RCOMP, gl_pixelmaps::RtoR, and gl_pixelmap::Size.
Referenced by _mesa_apply_rgba_transfer_ops().
_mesa_scale_and_bias_depth()
void _mesa_scale_and_bias_depth (const struct gl_context * ctx, GLuint n, GLfloat depthValues[])
References gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, F, GLuint, and gl_context::Pixel.
Referenced by _mesa_pack_depth_span(), and _mesa_pack_depth_stencil_span().
_mesa_scale_and_bias_depth_uint()
void _mesa_scale_and_bias_depth_uint (const struct gl_context * ctx, GLuint n, GLuint depthValues[])
References gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, GLuint, and gl_context::Pixel.
_mesa_scale_and_bias_rgba()
void _mesa_scale_and_bias_rgba (GLuint n, GLfloat rgba[][4], GLfloat rScale, GLfloat gScale, GLfloat bScale, GLfloat aScale, GLfloat rBias, GLfloat gBias, GLfloat bBias, GLfloat aBias)
References ACOMP, BCOMP, F, GCOMP, GLuint, and RCOMP.
Referenced by _mesa_apply_rgba_transfer_ops().
_mesa_shift_and_offset_ci()
void _mesa_shift_and_offset_ci (const struct gl_context * ctx, GLuint n, GLuint indexes[])
References GLuint, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, and gl_context::Pixel.
Referenced by _mesa_apply_ci_transfer_ops(), _mesa_unpack_color_index_to_rgba_float(), and _mesa_unpack_stencil_span().