Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
pixelstore.c File Reference
glPixelStore functions.
#include "glheader.h"
#include "bufferobj.h"
#include "context.h"
#include "pixelstore.h"
#include "mtypes.h"
Functions
void GLAPIENTRY _mesa_PixelStorei (GLenum pname, GLint param)
void GLAPIENTRY _mesa_PixelStoref (GLenum pname, GLfloat param)
void _mesa_init_pixelstore (struct gl_context *ctx)
Initialize the context's pixel store state.
bool _mesa_compressed_pixel_storage_error_check (struct gl_context *ctx, GLint dimensions, const struct gl_pixelstore_attrib *packing, const char *caller)
Check if the given compressed pixel storage parameters are legal.
Detailed Description
glPixelStore functions.
Function Documentation
_mesa_compressed_pixel_storage_error_check()
bool _mesa_compressed_pixel_storage_error_check (struct gl_context * ctx, GLint dimensions, const struct gl_pixelstore_attrib * packing, const char * caller)
Check if the given compressed pixel storage parameters are legal.
Record a GL error if illegal.
Returns
true if legal, false if illegal
References _mesa_error(), _mesa_is_desktop_gl(), gl_pixelstore_attrib::CompressedBlockDepth, gl_pixelstore_attrib::CompressedBlockHeight, gl_pixelstore_attrib::CompressedBlockSize, gl_pixelstore_attrib::CompressedBlockWidth, gl_pixelstore_attrib::SkipImages, gl_pixelstore_attrib::SkipPixels, and gl_pixelstore_attrib::SkipRows.
Referenced by compressed_subtexture_error_check(), compressed_texture_error_check(), and getcompressedteximage_error_check().
_mesa_init_pixelstore()
void _mesa_init_pixelstore (struct gl_context * ctx)
Initialize the context's pixel store state.
References _mesa_reference_buffer_object(), gl_pixelstore_attrib::Alignment, gl_pixelstore_attrib::BufferObj, gl_pixelstore_attrib::CompressedBlockDepth, gl_pixelstore_attrib::CompressedBlockHeight, gl_pixelstore_attrib::CompressedBlockSize, gl_pixelstore_attrib::CompressedBlockWidth, gl_context::DefaultPacking, gl_pixelstore_attrib::ImageHeight, gl_pixelstore_attrib::Invert, gl_pixelstore_attrib::LsbFirst, gl_shared_state::NullBufferObj, gl_context::Pack, gl_pixelstore_attrib::RowLength, gl_context::Shared, gl_pixelstore_attrib::SkipImages, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, and gl_context::Unpack.
Referenced by init_attrib_groups().
_mesa_PixelStoref()
void GLAPIENTRY _mesa_PixelStoref (GLenum pname, GLfloat param)
References _mesa_PixelStorei(), and IROUND().
_mesa_PixelStorei()
void GLAPIENTRY _mesa_PixelStorei (GLenum pname, GLint param)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), API_OPENGLES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_cpal_compressed_teximage2d(), _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), _mesa_dump_stencil_buffer(), and _mesa_PixelStoref().