Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
pixel.h File Reference
Pixel operations.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_PixelZoom (GLfloat xfactor, GLfloat yfactor)
void GLAPIENTRY _mesa_PixelMapfv (GLenum map, GLsizei mapsize, const GLfloat *values)
void GLAPIENTRY _mesa_PixelMapuiv (GLenum map, GLsizei mapsize, const GLuint *values)
void GLAPIENTRY _mesa_PixelMapusv (GLenum map, GLsizei mapsize, const GLushort *values)
void GLAPIENTRY _mesa_GetnPixelMapfvARB (GLenum map, GLsizei bufSize, GLfloat *values)
void GLAPIENTRY _mesa_GetPixelMapfv (GLenum map, GLfloat *values)
void GLAPIENTRY _mesa_GetnPixelMapuivARB (GLenum map, GLsizei bufSize, GLuint *values)
void GLAPIENTRY _mesa_GetPixelMapuiv (GLenum map, GLuint *values)
void GLAPIENTRY _mesa_GetnPixelMapusvARB (GLenum map, GLsizei bufSize, GLushort *values)
void GLAPIENTRY _mesa_GetPixelMapusv (GLenum map, GLushort *values)
void GLAPIENTRY _mesa_PixelTransferf (GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_PixelTransferi (GLenum pname, GLint param)
void _mesa_update_pixel (struct gl_context *ctx, GLuint newstate)
Update mesa pixel transfer derived state.
void _mesa_init_pixel (struct gl_context *ctx)
Initialize the context's PIXEL attribute group.
Detailed Description
Pixel operations.
Function Documentation
_mesa_GetnPixelMapfvARB()
void GLAPIENTRY _mesa_GetnPixelMapfvARB (GLenum map, GLsizei bufSize, GLfloat * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), GET_CURRENT_CONTEXT, get_pixelmap(), GLAPIENTRY, gl_pixelmap::Map, gl_pixelmap::Size, and validate_pbo_access().
Referenced by _mesa_GetPixelMapfv().
_mesa_GetnPixelMapuivARB()
void GLAPIENTRY _mesa_GetnPixelMapuivARB (GLenum map, GLsizei bufSize, GLuint * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), FLOAT_TO_UINT, GET_CURRENT_CONTEXT, get_pixelmap(), GLAPIENTRY, GLuint, gl_pixelmap::Map, gl_pixelmap::Size, and validate_pbo_access().
Referenced by _mesa_GetPixelMapuiv().
_mesa_GetnPixelMapusvARB()
void GLAPIENTRY _mesa_GetnPixelMapusvARB (GLenum map, GLsizei bufSize, GLushort * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), CLAMPED_FLOAT_TO_USHORT, GET_CURRENT_CONTEXT, get_pixelmap(), GLAPIENTRY, GLushort, gl_pixelmap::Map, gl_pixelmap::Size, and validate_pbo_access().
Referenced by _mesa_GetPixelMapusv().
_mesa_GetPixelMapfv()
void GLAPIENTRY _mesa_GetPixelMapfv (GLenum map, GLfloat * values)
References _mesa_GetnPixelMapfvARB(), and GLAPIENTRY.
_mesa_GetPixelMapuiv()
void GLAPIENTRY _mesa_GetPixelMapuiv (GLenum map, GLuint * values)
References _mesa_GetnPixelMapuivARB(), and GLAPIENTRY.
_mesa_GetPixelMapusv()
void GLAPIENTRY _mesa_GetPixelMapusv (GLenum map, GLushort * values)
References _mesa_GetnPixelMapusvARB(), and GLAPIENTRY.
_mesa_init_pixel()
void _mesa_init_pixel (struct gl_context * ctx)
Initialize the context's PIXEL attribute group.
References gl_context::_ImageTransferState, gl_pixel_attrib::AlphaBias, gl_pixel_attrib::AlphaScale, gl_pixelmaps::AtoA, gl_pixel_attrib::BlueBias, gl_pixel_attrib::BlueScale, gl_pixelmaps::BtoB, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_config::doubleBufferMode, gl_pixel_attrib::GreenBias, gl_pixel_attrib::GreenScale, gl_pixelmaps::GtoG, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, init_pixelmap(), gl_pixelmaps::ItoA, gl_pixelmaps::ItoB, gl_pixelmaps::ItoG, gl_pixelmaps::ItoI, gl_pixelmaps::ItoR, gl_pixel_attrib::MapColorFlag, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, gl_context::PixelMaps, gl_pixel_attrib::ReadBuffer, gl_pixel_attrib::RedBias, gl_pixel_attrib::RedScale, gl_pixelmaps::RtoR, gl_pixelmaps::StoS, gl_context::Visual, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by init_attrib_groups().
_mesa_PixelMapfv()
void GLAPIENTRY _mesa_PixelMapfv (GLenum map, GLsizei mapsize, const GLfloat * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_pow_two(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _NEW_PIXEL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MAX_PIXEL_MAP_TABLE, store_pixelmap(), and validate_pbo_access().
_mesa_PixelMapuiv()
void GLAPIENTRY _mesa_PixelMapuiv (GLenum map, GLsizei mapsize, const GLuint * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_pow_two(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _NEW_PIXEL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MAX_PIXEL_MAP_TABLE, store_pixelmap(), UINT_TO_FLOAT, and validate_pbo_access().
_mesa_PixelMapusv()
void GLAPIENTRY _mesa_PixelMapusv (GLenum map, GLsizei mapsize, const GLushort * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_pow_two(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _NEW_PIXEL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLushort, MAX_PIXEL_MAP_TABLE, store_pixelmap(), USHORT_TO_FLOAT, and validate_pbo_access().
_mesa_PixelTransferf()
void GLAPIENTRY _mesa_PixelTransferf (GLenum pname, GLfloat param)
References _mesa_error(), _NEW_PIXEL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_PixelTransferi().
_mesa_PixelTransferi()
void GLAPIENTRY _mesa_PixelTransferi (GLenum pname, GLint param)
References _mesa_PixelTransferf().
_mesa_PixelZoom()
void GLAPIENTRY _mesa_PixelZoom (GLfloat xfactor, GLfloat yfactor)
References _NEW_PIXEL, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
_mesa_update_pixel()
void _mesa_update_pixel (struct gl_context * ctx, GLuint newstate)
Update mesa pixel transfer derived state.
References _NEW_PIXEL, and update_image_transfer_state().
Referenced by _mesa_update_state_locked().