Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
points.c File Reference
Point operations.
#include "glheader.h"
#include "context.h"
#include "macros.h"
#include "points.h"
#include "mtypes.h"
Functions
void GLAPIENTRY _mesa_PointSize (GLfloat size)
Set current point size.
void GLAPIENTRY _mesa_PointParameteri (GLenum pname, GLint param)
void GLAPIENTRY _mesa_PointParameteriv (GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_PointParameterf (GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_PointParameterfv (GLenum pname, const GLfloat *params)
void _mesa_init_point (struct gl_context *ctx)
Initialize the context point state.
Detailed Description
Point operations.
Function Documentation
_mesa_init_point()
void _mesa_init_point (struct gl_context * ctx)
Initialize the context point state.
Parameters
ctx GL context.
Initializes __struct gl_contextRec::Point and point related constants in __struct gl_contextRec::Const.
References gl_point_attrib::_Attenuated, gl_context::API, API_OPENGL_CORE, API_OPENGLES2, gl_context::Const, gl_point_attrib::CoordReplace, gl_constants::MaxPointSize, gl_constants::MaxPointSizeAA, gl_point_attrib::MaxSize, gl_point_attrib::MinSize, gl_point_attrib::Params, gl_context::Point, gl_point_attrib::PointSprite, gl_point_attrib::Size, gl_point_attrib::SmoothFlag, gl_point_attrib::SpriteOrigin, gl_point_attrib::SpriteRMode, and gl_point_attrib::Threshold.
Referenced by init_attrib_groups().
_mesa_PointParameterf()
void GLAPIENTRY _mesa_PointParameterf (GLenum pname, GLfloat param)
References _mesa_PointParameterfv(), and GLAPIENTRY.
Referenced by _mesa_PointParameterx(), and _mesa_PopAttrib().
_mesa_PointParameterfv()
void GLAPIENTRY _mesa_PointParameterfv (GLenum pname, const GLfloat * params)
References _mesa_error(), _mesa_is_desktop_gl(), _NEW_POINT, API_OPENGL_COMPAT, API_OPENGL_CORE, COPY_3V, F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and TEST_EQ_3V.
Referenced by _mesa_PointParameterf(), _mesa_PointParameteri(), _mesa_PointParameteriv(), _mesa_PointParameterxv(), and _mesa_PopAttrib().
_mesa_PointParameteri()
void GLAPIENTRY _mesa_PointParameteri (GLenum pname, GLint param)
References _mesa_PointParameterfv(), and GLAPIENTRY.
Referenced by _mesa_PopAttrib().
_mesa_PointParameteriv()
void GLAPIENTRY _mesa_PointParameteriv (GLenum pname, const GLint * params)
References _mesa_PointParameterfv(), and GLAPIENTRY.
_mesa_PointSize()
void GLAPIENTRY _mesa_PointSize (GLfloat size)
Set current point size.
Parameters
size point diameter in pixels
See also
glPointSize().
References _mesa_error(), _NEW_POINT, F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_PointSizex(), and _mesa_PopAttrib().