Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
polygon.h File Reference
Polygon operations.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_GetnPolygonStippleARB (GLsizei bufSize, GLubyte *dest)
Called by glPolygonStipple.
void GLAPIENTRY _mesa_CullFace (GLenum mode)
Specify whether to cull front- or back-facing facets.
void GLAPIENTRY _mesa_FrontFace (GLenum mode)
Define front- and back-facing.
void GLAPIENTRY _mesa_PolygonMode (GLenum face, GLenum mode)
Set the polygon rasterization mode.
void GLAPIENTRY _mesa_PolygonOffset (GLfloat factor, GLfloat units)
void GLAPIENTRY _mesa_PolygonOffsetEXT (GLfloat factor, GLfloat bias)
void GLAPIENTRY _mesa_PolygonOffsetClampEXT (GLfloat factor, GLfloat units, GLfloat clamp)
void GLAPIENTRY _mesa_PolygonStipple (const GLubyte *mask)
Called by glPolygonStipple.
void GLAPIENTRY _mesa_GetPolygonStipple (GLubyte *mask)
void _mesa_polygon_offset_clamp (struct gl_context *ctx, GLfloat factor, GLfloat units, GLfloat clamp)
void _mesa_init_polygon (struct gl_context *ctx)
Initialize the context polygon state.
Detailed Description
Polygon operations.
Function Documentation
_mesa_CullFace()
void GLAPIENTRY _mesa_CullFace (GLenum mode)
Specify whether to cull front- or back-facing facets.
Parameters
mode culling mode.
See also
glCullFace().
Verifies the parameter and updates gl_polygon_attrib::CullFaceMode. On change, flushes the vertices and notifies the driver via the dd_function_table::CullFace callback.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_POLYGON, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_FrontFace()
void GLAPIENTRY _mesa_FrontFace (GLenum mode)
Define front- and back-facing.
Parameters
mode orientation of front-facing polygons.
See also
glFrontFace().
Verifies the parameter and updates gl_polygon_attrib::FrontFace. On change flushes the vertices and notifies the driver via the dd_function_table::FrontFace callback.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_POLYGON, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_GetnPolygonStippleARB()
void GLAPIENTRY _mesa_GetnPolygonStippleARB (GLsizei bufSize, GLubyte * dest)
Called by glPolygonStipple.
References _mesa_debug(), _mesa_map_validate_pbo_dest(), _mesa_pack_polygon_stipple(), _mesa_unmap_pbo_dest(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_GetPolygonStipple().
_mesa_GetPolygonStipple()
void GLAPIENTRY _mesa_GetPolygonStipple (GLubyte * mask)
References _mesa_GetnPolygonStippleARB().
_mesa_init_polygon()
void _mesa_init_polygon (struct gl_context * ctx)
Initialize the context polygon state.
Parameters
ctx GL context.
Initializes __struct gl_contextRec::Polygon and __struct gl_contextRec::PolygonStipple attribute groups.
References gl_polygon_attrib::_FrontBit, gl_polygon_attrib::BackMode, gl_polygon_attrib::CullFaceMode, gl_polygon_attrib::CullFlag, gl_polygon_attrib::FrontFace, gl_polygon_attrib::FrontMode, GLuint, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, gl_context::Polygon, gl_context::PolygonStipple, gl_polygon_attrib::SmoothFlag, and gl_polygon_attrib::StippleFlag.
Referenced by init_attrib_groups().
_mesa_polygon_offset_clamp()
void _mesa_polygon_offset_clamp (struct gl_context * ctx, GLfloat factor, GLfloat units, GLfloat clamp)
References _NEW_POLYGON, gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, gl_polygon_attrib::OffsetClamp, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetUnits, gl_context::Polygon, and dd_function_table::PolygonOffset.
Referenced by _mesa_PolygonOffset(), _mesa_PolygonOffsetClampEXT(), and _mesa_PopAttrib().
_mesa_PolygonMode()
void GLAPIENTRY _mesa_PolygonMode (GLenum face, GLenum mode)
Set the polygon rasterization mode.
Parameters
face the polygons which mode applies to.
mode how polygons should be rasterized.
See also
glPolygonMode().
Verifies the parameters and updates gl_polygon_attrib::FrontMode and gl_polygon_attrib::BackMode. On change flushes the vertices and notifies the driver via the dd_function_table::PolygonMode callback.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_POLYGON, API_OPENGL_CORE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_PolygonOffset()
void GLAPIENTRY _mesa_PolygonOffset (GLfloat factor, GLfloat units)
References _mesa_debug(), _mesa_polygon_offset_clamp(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PolygonOffsetEXT(), and _mesa_PolygonOffsetx().
_mesa_PolygonOffsetClampEXT()
void GLAPIENTRY _mesa_PolygonOffsetClampEXT (GLfloat factor, GLfloat units, GLfloat clamp)
References _mesa_debug(), _mesa_error(), _mesa_polygon_offset_clamp(), GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
_mesa_PolygonOffsetEXT()
void GLAPIENTRY _mesa_PolygonOffsetEXT (GLfloat factor, GLfloat bias)
References _mesa_PolygonOffset(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_PolygonStipple()
void GLAPIENTRY _mesa_PolygonStipple (const GLubyte * mask)
Called by glPolygonStipple.
References _mesa_debug(), _mesa_map_validate_pbo_source(), _mesa_unmap_pbo_source(), _mesa_unpack_polygon_stipple(), _NEW_POLYGONSTIPPLE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.