Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
program_resource.c File Reference
#include "main/enums.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/context.h"
#include "program_resource.h"
#include "compiler/glsl/ir_uniform.h"
Functions
static bool supported_interface_enum (struct gl_context *ctx, GLenum iface)
static struct gl_shader_program * lookup_linked_program (GLuint program, const char *caller)
void GLAPIENTRY _mesa_GetProgramInterfaceiv (GLuint program, GLenum programInterface, GLenum pname, GLint *params)
static bool is_xfb_marker (const char *str)
GLuint GLAPIENTRY _mesa_GetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar *name)
void GLAPIENTRY _mesa_GetProgramResourceName (GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name)
void GLAPIENTRY _mesa_GetProgramResourceiv (GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params)
GLint GLAPIENTRY _mesa_GetProgramResourceLocation (GLuint program, GLenum programInterface, const GLchar *name)
GLint GLAPIENTRY _mesa_GetProgramResourceLocationIndex (GLuint program, GLenum programInterface, const GLchar *name)
Returns output index for dual source blending.
Function Documentation
_mesa_GetProgramInterfaceiv()
void GLAPIENTRY _mesa_GetProgramInterfaceiv (GLuint program, GLenum programInterface, GLenum pname, GLint * params)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_name(), _mesa_program_resource_name_len(), gl_program_resource::Data, gl_shader_program::data, for(), GET_CURRENT_CONTEXT, gl_uniform_buffer_variable::IndexName, MESA_VERBOSE, gl_shader_program_data::NumProgramResourceList, gl_uniform_block::NumUniforms, gl_active_atomic_buffer::NumUniforms, gl_transform_feedback_buffer::NumVaryings, gl_shader_program_data::ProgramResourceList, supported_interface_enum(), gl_program_resource::Type, gl_uniform_block::Uniforms, and VERBOSE_API.
_mesa_GetProgramResourceIndex()
GLuint GLAPIENTRY _mesa_GetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar * name)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_name(), _mesa_program_resource_index(), GET_CURRENT_CONTEXT, GLAPIENTRY, is_xfb_marker(), MESA_VERBOSE, supported_interface_enum(), and VERBOSE_API.
_mesa_GetProgramResourceiv()
void GLAPIENTRY _mesa_GetProgramResourceiv (GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum * props, GLsizei bufSize, GLsizei * length, GLint * params)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_program_resourceiv(), _mesa_lookup_shader_program_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_GetProgramResourceLocation()
GLint GLAPIENTRY _mesa_GetProgramResourceLocation (GLuint program, GLenum programInterface, const GLchar * name)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_program_resource_location(), GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_linked_program(), MESA_VERBOSE, and VERBOSE_API.
_mesa_GetProgramResourceLocationIndex()
GLint GLAPIENTRY _mesa_GetProgramResourceLocationIndex (GLuint program, GLenum programInterface, const GLchar * name)
Returns output index for dual source blending.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_program_resource_location_index(), GET_CURRENT_CONTEXT, lookup_linked_program(), MESA_VERBOSE, and VERBOSE_API.
_mesa_GetProgramResourceName()
void GLAPIENTRY _mesa_GetProgramResourceName (GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei * length, GLchar * name)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, supported_interface_enum(), and VERBOSE_API.
is_xfb_marker()
static bool is_xfb_marker (const char * str) static
References GLAPIENTRY, and GLuint.
Referenced by _mesa_GetProgramResourceIndex().
lookup_linked_program()
static struct gl_shader_program* lookup_linked_program (GLuint program, const char * caller) static
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, linking_failure, and gl_shader_program_data::LinkStatus.
Referenced by _mesa_GetProgramResourceLocation(), and _mesa_GetProgramResourceLocationIndex().
supported_interface_enum()
static bool supported_interface_enum (struct gl_context * ctx, GLenum iface) static
References _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), and _mesa_has_tessellation().
Referenced by _mesa_GetProgramInterfaceiv(), _mesa_GetProgramResourceIndex(), and _mesa_GetProgramResourceName().