Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
queryobj.h File Reference
#include "main/mtypes.h"
#include "main/hash.h"
Functions
static struct gl_query_object * _mesa_lookup_query_object (struct gl_context *ctx, GLuint id)
void _mesa_init_query_object_functions (struct dd_function_table *driver)
void _mesa_init_queryobj (struct gl_context *ctx)
Allocate/init the context state related to query objects.
void _mesa_free_queryobj_data (struct gl_context *ctx)
Free the context state related to query objects.
void GLAPIENTRY _mesa_GenQueries (GLsizei n, GLuint *ids)
void GLAPIENTRY _mesa_CreateQueries (GLenum target, GLsizei n, GLuint *ids)
void GLAPIENTRY _mesa_DeleteQueries (GLsizei n, const GLuint *ids)
GLboolean GLAPIENTRY _mesa_IsQuery (GLuint id)
void GLAPIENTRY _mesa_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
void GLAPIENTRY _mesa_EndQueryIndexed (GLenum target, GLuint index)
void GLAPIENTRY _mesa_BeginQuery (GLenum target, GLuint id)
void GLAPIENTRY _mesa_EndQuery (GLenum target)
void GLAPIENTRY _mesa_QueryCounter (GLuint id, GLenum target)
void GLAPIENTRY _mesa_GetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryiv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryObjectiv (GLuint id, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params)
void GLAPIENTRY _mesa_GetQueryObjecti64v (GLuint id, GLenum pname, GLint64EXT *params)
New with GL_EXT_timer_query.
void GLAPIENTRY _mesa_GetQueryObjectui64v (GLuint id, GLenum pname, GLuint64EXT *params)
New with GL_EXT_timer_query.
void GLAPIENTRY _mesa_GetQueryBufferObjectiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
New with GL_ARB_query_buffer_object.
void GLAPIENTRY _mesa_GetQueryBufferObjectuiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
void GLAPIENTRY _mesa_GetQueryBufferObjecti64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
void GLAPIENTRY _mesa_GetQueryBufferObjectui64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
Function Documentation
_mesa_BeginQuery()
void GLAPIENTRY _mesa_BeginQuery (GLenum target, GLuint id)
References _mesa_BeginQueryIndexed(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_BeginQueryIndexed()
void GLAPIENTRY _mesa_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_query_object(), gl_query_object::Active, API_OPENGL_COMPAT, gl_query_object::EverBound, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, MESA_VERBOSE, query_error_check_index(), gl_query_object::Ready, gl_query_object::Result, gl_query_object::Stream, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_BeginQuery(), and _mesa_lookup_query_object().
_mesa_CreateQueries()
void GLAPIENTRY _mesa_CreateQueries (GLenum target, GLsizei n, GLuint * ids)
References _mesa_enum_to_string(), _mesa_error(), create_queries(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_DeleteQueries()
void GLAPIENTRY _mesa_DeleteQueries (GLsizei n, const GLuint * ids)
References _mesa_debug(), _mesa_error(), _mesa_HashRemove(), _mesa_lookup_query_object(), gl_query_object::Active, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, MESA_VERBOSE, gl_query_object::Stream, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_lookup_query_object().
_mesa_EndQuery()
void GLAPIENTRY _mesa_EndQuery (GLenum target)
References _mesa_EndQueryIndexed(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_EndQueryIndexed()
void GLAPIENTRY _mesa_EndQueryIndexed (GLenum target, GLuint index)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), gl_query_object::Active, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, MESA_VERBOSE, query_error_check_index(), gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_EndQuery(), and _mesa_lookup_query_object().
_mesa_free_queryobj_data()
void _mesa_free_queryobj_data (struct gl_context * ctx)
Free the context state related to query objects.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), delete_queryobj_cb(), gl_context::Query, and gl_query_state::QueryObjects.
Referenced by _mesa_free_context_data(), and _mesa_lookup_query_object().
_mesa_GenQueries()
void GLAPIENTRY _mesa_GenQueries (GLsizei n, GLuint * ids)
References create_queries(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjecti64v()
void GLAPIENTRY _mesa_GetQueryBufferObjecti64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjectiv()
void GLAPIENTRY _mesa_GetQueryBufferObjectiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
New with GL_ARB_query_buffer_object.
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjectui64v()
void GLAPIENTRY _mesa_GetQueryBufferObjectui64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, and get_query_object().
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjectuiv()
void GLAPIENTRY _mesa_GetQueryBufferObjectuiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryIndexediv()
void GLAPIENTRY _mesa_GetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint * params)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_problem(), GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, gl_query_object::Id, MESA_VERBOSE, query_error_check_index(), gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_GetQueryiv(), and _mesa_lookup_query_object().
_mesa_GetQueryiv()
void GLAPIENTRY _mesa_GetQueryiv (GLenum target, GLenum pname, GLint * params)
References _mesa_GetQueryIndexediv().
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjecti64v()
void GLAPIENTRY _mesa_GetQueryObjecti64v (GLuint id, GLenum pname, GLint64EXT * params)
New with GL_EXT_timer_query.
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjectiv()
void GLAPIENTRY _mesa_GetQueryObjectiv (GLuint id, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjectui64v()
void GLAPIENTRY _mesa_GetQueryObjectui64v (GLuint id, GLenum pname, GLuint64EXT * params)
New with GL_EXT_timer_query.
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjectuiv()
void GLAPIENTRY _mesa_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint * params)
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_init_query_object_functions()
void _mesa_init_query_object_functions (struct dd_function_table * driver)
References _mesa_begin_query(), _mesa_check_query(), _mesa_delete_query(), _mesa_end_query(), _mesa_new_query_object(), _mesa_wait_query(), dd_function_table::BeginQuery, dd_function_table::CheckQuery, dd_function_table::DeleteQuery, dd_function_table::EndQuery, dd_function_table::NewQueryObject, and dd_function_table::WaitQuery.
Referenced by _mesa_lookup_query_object().
_mesa_init_queryobj()
void _mesa_init_queryobj (struct gl_context * ctx)
Allocate/init the context state related to query objects.
References _mesa_NewHashTable(), gl_constants::ClInPrimitives, gl_constants::ClOutPrimitives, gl_constants::ComputeInvocations, gl_context::Const, gl_query_state::CurrentOcclusionObject, gl_constants::FsInvocations, gl_constants::GsInvocations, gl_constants::GsPrimitives, gl_constants::PrimitivesGenerated, gl_constants::PrimitivesSubmitted, gl_constants::PrimitivesWritten, gl_context::Query, gl_constants::QueryCounterBits, gl_query_state::QueryObjects, gl_constants::SamplesPassed, gl_constants::TessInvocations, gl_constants::TessPatches, gl_constants::TimeElapsed, gl_constants::Timestamp, gl_constants::VerticesSubmitted, and gl_constants::VsInvocations.
Referenced by _mesa_lookup_query_object(), and init_attrib_groups().
_mesa_IsQuery()
GLboolean GLAPIENTRY _mesa_IsQuery (GLuint id)
References _mesa_debug(), _mesa_lookup_query_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_query_object::EverBound, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_lookup_query_object().
_mesa_lookup_query_object()
static struct gl_query_object* _mesa_lookup_query_object (struct gl_context * ctx, GLuint id) static
References _mesa_BeginQuery(), _mesa_BeginQueryIndexed(), _mesa_CreateQueries(), _mesa_DeleteQueries(), _mesa_EndQuery(), _mesa_EndQueryIndexed(), _mesa_free_queryobj_data(), _mesa_GenQueries(), _mesa_GetQueryBufferObjecti64v(), _mesa_GetQueryBufferObjectiv(), _mesa_GetQueryBufferObjectui64v(), _mesa_GetQueryBufferObjectuiv(), _mesa_GetQueryIndexediv(), _mesa_GetQueryiv(), _mesa_GetQueryObjecti64v(), _mesa_GetQueryObjectiv(), _mesa_GetQueryObjectui64v(), _mesa_GetQueryObjectuiv(), _mesa_HashLookup(), _mesa_init_query_object_functions(), _mesa_init_queryobj(), _mesa_IsQuery(), _mesa_QueryCounter(), GLAPIENTRY, GLuint, gl_context::Query, and gl_query_state::QueryObjects.
Referenced by _mesa_BeginConditionalRender(), _mesa_BeginQueryIndexed(), _mesa_DeleteQueries(), _mesa_IsQuery(), _mesa_QueryCounter(), get_label_pointer(), and get_query_object().
_mesa_QueryCounter()
void GLAPIENTRY _mesa_QueryCounter (GLuint id, GLenum target)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_query_object(), gl_query_object::Active, gl_query_object::EverBound, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_lookup_query_object().