Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
queryobj.c File Reference
#include "bufferobj.h"
#include "glheader.h"
#include "context.h"
#include "enums.h"
#include "hash.h"
#include "imports.h"
#include "queryobj.h"
#include "mtypes.h"
#include "main/dispatch.h"
Functions
static struct gl_query_object * _mesa_new_query_object (struct gl_context *ctx, GLuint id)
Allocate a new query object.
static void _mesa_begin_query (struct gl_context *ctx, struct gl_query_object *q)
Begin a query.
static void _mesa_end_query (struct gl_context *ctx, struct gl_query_object *q)
End a query.
static void _mesa_wait_query (struct gl_context *ctx, struct gl_query_object *q)
Wait for query to complete.
static void _mesa_check_query (struct gl_context *ctx, struct gl_query_object *q)
Check if a query results are ready.
static void _mesa_delete_query (struct gl_context *ctx, struct gl_query_object *q)
Delete a query object.
void _mesa_init_query_object_functions (struct dd_function_table *driver)
static struct gl_query_object ** get_pipe_stats_binding_point (struct gl_context *ctx, GLenum target)
static struct gl_query_object ** get_query_binding_point (struct gl_context *ctx, GLenum target, GLuint index)
Return pointer to the query object binding point for the given target and index.
static void create_queries (struct gl_context *ctx, GLenum target, GLsizei n, GLuint *ids, bool dsa)
Create $n query objects and store them in *ids.
void GLAPIENTRY _mesa_GenQueries (GLsizei n, GLuint *ids)
void GLAPIENTRY _mesa_CreateQueries (GLenum target, GLsizei n, GLuint *ids)
void GLAPIENTRY _mesa_DeleteQueries (GLsizei n, const GLuint *ids)
GLboolean GLAPIENTRY _mesa_IsQuery (GLuint id)
static GLboolean query_error_check_index (struct gl_context *ctx, GLenum target, GLuint index)
void GLAPIENTRY _mesa_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
void GLAPIENTRY _mesa_EndQueryIndexed (GLenum target, GLuint index)
void GLAPIENTRY _mesa_BeginQuery (GLenum target, GLuint id)
void GLAPIENTRY _mesa_EndQuery (GLenum target)
void GLAPIENTRY _mesa_QueryCounter (GLuint id, GLenum target)
void GLAPIENTRY _mesa_GetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryiv (GLenum target, GLenum pname, GLint *params)
static void get_query_object (struct gl_context *ctx, const char *func, GLuint id, GLenum pname, GLenum ptype, struct gl_buffer_object *buf, intptr_t offset)
void GLAPIENTRY _mesa_GetQueryObjectiv (GLuint id, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params)
void GLAPIENTRY _mesa_GetQueryObjecti64v (GLuint id, GLenum pname, GLint64EXT *params)
New with GL_EXT_timer_query.
void GLAPIENTRY _mesa_GetQueryObjectui64v (GLuint id, GLenum pname, GLuint64EXT *params)
New with GL_EXT_timer_query.
void GLAPIENTRY _mesa_GetQueryBufferObjectiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
New with GL_ARB_query_buffer_object.
void GLAPIENTRY _mesa_GetQueryBufferObjectuiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
void GLAPIENTRY _mesa_GetQueryBufferObjecti64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
void GLAPIENTRY _mesa_GetQueryBufferObjectui64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
void _mesa_init_queryobj (struct gl_context *ctx)
Allocate/init the context state related to query objects.
static void delete_queryobj_cb (GLuint id, void *data, void *userData)
Callback for deleting a query object.
void _mesa_free_queryobj_data (struct gl_context *ctx)
Free the context state related to query objects.
Function Documentation
_mesa_begin_query()
static void _mesa_begin_query (struct gl_context * ctx, struct gl_query_object * q) static
Begin a query.
Software driver fallback. Called via ctx->Driver.BeginQuery().
References _NEW_DEPTH, and gl_context::NewState.
Referenced by _mesa_init_query_object_functions().
_mesa_BeginQuery()
void GLAPIENTRY _mesa_BeginQuery (GLenum target, GLuint id)
References _mesa_BeginQueryIndexed(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_BeginQueryIndexed()
void GLAPIENTRY _mesa_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_query_object(), gl_query_object::Active, API_OPENGL_COMPAT, gl_query_object::EverBound, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, MESA_VERBOSE, query_error_check_index(), gl_query_object::Ready, gl_query_object::Result, gl_query_object::Stream, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_BeginQuery(), and _mesa_lookup_query_object().
_mesa_check_query()
static void _mesa_check_query (struct gl_context * ctx, struct gl_query_object * q) static
Check if a query results are ready.
Software driver fallback. Called via ctx->Driver.CheckQuery().
Referenced by _mesa_init_query_object_functions().
_mesa_CreateQueries()
void GLAPIENTRY _mesa_CreateQueries (GLenum target, GLsizei n, GLuint * ids)
References _mesa_enum_to_string(), _mesa_error(), create_queries(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_delete_query()
static void _mesa_delete_query (struct gl_context * ctx, struct gl_query_object * q) static
Delete a query object.
Called via ctx->Driver.DeleteQuery(). Not removed from hash table here.
References gl_query_object::Label.
Referenced by _mesa_init_query_object_functions().
_mesa_DeleteQueries()
void GLAPIENTRY _mesa_DeleteQueries (GLsizei n, const GLuint * ids)
References _mesa_debug(), _mesa_error(), _mesa_HashRemove(), _mesa_lookup_query_object(), gl_query_object::Active, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, MESA_VERBOSE, gl_query_object::Stream, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_lookup_query_object().
_mesa_end_query()
static void _mesa_end_query (struct gl_context * ctx, struct gl_query_object * q) static
End a query.
Software driver fallback. Called via ctx->Driver.EndQuery().
References _NEW_DEPTH, gl_context::NewState, and gl_query_object::Ready.
Referenced by _mesa_init_query_object_functions().
_mesa_EndQuery()
void GLAPIENTRY _mesa_EndQuery (GLenum target)
References _mesa_EndQueryIndexed(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_EndQueryIndexed()
void GLAPIENTRY _mesa_EndQueryIndexed (GLenum target, GLuint index)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), gl_query_object::Active, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, MESA_VERBOSE, query_error_check_index(), gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_EndQuery(), and _mesa_lookup_query_object().
_mesa_free_queryobj_data()
void _mesa_free_queryobj_data (struct gl_context * ctx)
Free the context state related to query objects.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), delete_queryobj_cb(), gl_context::Query, and gl_query_state::QueryObjects.
Referenced by _mesa_free_context_data(), and _mesa_lookup_query_object().
_mesa_GenQueries()
void GLAPIENTRY _mesa_GenQueries (GLsizei n, GLuint * ids)
References create_queries(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjecti64v()
void GLAPIENTRY _mesa_GetQueryBufferObjecti64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjectiv()
void GLAPIENTRY _mesa_GetQueryBufferObjectiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
New with GL_ARB_query_buffer_object.
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjectui64v()
void GLAPIENTRY _mesa_GetQueryBufferObjectui64v (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, and get_query_object().
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryBufferObjectuiv()
void GLAPIENTRY _mesa_GetQueryBufferObjectuiv (GLuint id, GLuint buffer, GLenum pname, GLintptr offset)
References _mesa_lookup_bufferobj_err(), GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryIndexediv()
void GLAPIENTRY _mesa_GetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint * params)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_problem(), GET_CURRENT_CONTEXT, get_query_binding_point(), GLAPIENTRY, gl_query_object::Id, MESA_VERBOSE, query_error_check_index(), gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_GetQueryiv(), and _mesa_lookup_query_object().
_mesa_GetQueryiv()
void GLAPIENTRY _mesa_GetQueryiv (GLenum target, GLenum pname, GLint * params)
References _mesa_GetQueryIndexediv().
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjecti64v()
void GLAPIENTRY _mesa_GetQueryObjecti64v (GLuint id, GLenum pname, GLint64EXT * params)
New with GL_EXT_timer_query.
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjectiv()
void GLAPIENTRY _mesa_GetQueryObjectiv (GLuint id, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjectui64v()
void GLAPIENTRY _mesa_GetQueryObjectui64v (GLuint id, GLenum pname, GLuint64EXT * params)
New with GL_EXT_timer_query.
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_GetQueryObjectuiv()
void GLAPIENTRY _mesa_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint * params)
References GET_CURRENT_CONTEXT, get_query_object(), and GLAPIENTRY.
Referenced by _mesa_lookup_query_object().
_mesa_init_query_object_functions()
void _mesa_init_query_object_functions (struct dd_function_table * driver)
References _mesa_begin_query(), _mesa_check_query(), _mesa_delete_query(), _mesa_end_query(), _mesa_new_query_object(), _mesa_wait_query(), dd_function_table::BeginQuery, dd_function_table::CheckQuery, dd_function_table::DeleteQuery, dd_function_table::EndQuery, dd_function_table::NewQueryObject, and dd_function_table::WaitQuery.
Referenced by _mesa_lookup_query_object().
_mesa_init_queryobj()
void _mesa_init_queryobj (struct gl_context * ctx)
Allocate/init the context state related to query objects.
References _mesa_NewHashTable(), gl_constants::ClInPrimitives, gl_constants::ClOutPrimitives, gl_constants::ComputeInvocations, gl_context::Const, gl_query_state::CurrentOcclusionObject, gl_constants::FsInvocations, gl_constants::GsInvocations, gl_constants::GsPrimitives, gl_constants::PrimitivesGenerated, gl_constants::PrimitivesSubmitted, gl_constants::PrimitivesWritten, gl_context::Query, gl_constants::QueryCounterBits, gl_query_state::QueryObjects, gl_constants::SamplesPassed, gl_constants::TessInvocations, gl_constants::TessPatches, gl_constants::TimeElapsed, gl_constants::Timestamp, gl_constants::VerticesSubmitted, and gl_constants::VsInvocations.
Referenced by _mesa_lookup_query_object(), and init_attrib_groups().
_mesa_IsQuery()
GLboolean GLAPIENTRY _mesa_IsQuery (GLuint id)
References _mesa_debug(), _mesa_lookup_query_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_query_object::EverBound, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_lookup_query_object().
_mesa_new_query_object()
static struct gl_query_object* _mesa_new_query_object (struct gl_context * ctx, GLuint id) static
Allocate a new query object.
This is a fallback routine called via ctx->Driver.NewQueryObject().
Parameters
ctx - rendering context
id - the new object's ID
Returns
pointer to new query_object object or NULL if out of memory.
References gl_query_object::Active, CALLOC_STRUCT, gl_query_object::EverBound, gl_query_object::Id, gl_query_object::Ready, gl_query_object::Result, and void.
Referenced by _mesa_init_query_object_functions().
_mesa_QueryCounter()
void GLAPIENTRY _mesa_QueryCounter (GLuint id, GLenum target)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_query_object(), gl_query_object::Active, gl_query_object::EverBound, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_lookup_query_object().
_mesa_wait_query()
static void _mesa_wait_query (struct gl_context * ctx, struct gl_query_object * q) static
Wait for query to complete.
Software driver fallback. Called via ctx->Driver.WaitQuery().
References gl_query_object::Ready.
Referenced by _mesa_init_query_object_functions().
create_queries()
static void create_queries (struct gl_context * ctx, GLenum target, GLsizei n, GLuint * ids, bool dsa) static
Create $n query objects and store them in *ids.
Make them of type $target if dsa is set. Called from _mesa_GenQueries() and _mesa_CreateQueries().
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_context::Driver, gl_query_object::EverBound, GLAPIENTRY, GLuint, MESA_VERBOSE, dd_function_table::NewQueryObject, gl_context::Query, gl_query_state::QueryObjects, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_CreateQueries(), and _mesa_GenQueries().
delete_queryobj_cb()
static void delete_queryobj_cb (GLuint id, void * data, void * userData) static
Callback for deleting a query object.
Called by _mesa_HashDeleteAll().
References dd_function_table::DeleteQuery, and gl_context::Driver.
Referenced by _mesa_free_queryobj_data().
get_pipe_stats_binding_point()
static struct gl_query_object** get_pipe_stats_binding_point (struct gl_context * ctx, GLenum target) static
References _mesa_is_desktop_gl(), gl_extensions::ARB_pipeline_statistics_query, gl_context::Extensions, MAX_PIPELINE_STATISTICS, gl_query_state::pipeline_stats, and gl_context::Query.
Referenced by get_query_binding_point().
get_query_binding_point()
static struct gl_query_object** get_query_binding_point (struct gl_context * ctx, GLenum target, GLuint index) static
Return pointer to the query object binding point for the given target and index.
Returns
NULL if invalid target, else the address of binding point
References _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), gl_context::API, API_OPENGLES2, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_transform_feedback_overflow_query, gl_query_state::CurrentOcclusionObject, gl_query_state::CurrentTimerObject, gl_extensions::EXT_timer_query, gl_extensions::EXT_transform_feedback, gl_context::Extensions, get_pipe_stats_binding_point(), MAX_PIPELINE_STATISTICS, gl_query_state::PrimitivesGenerated, gl_query_state::PrimitivesWritten, gl_context::Query, gl_query_state::TransformFeedbackOverflow, gl_query_state::TransformFeedbackOverflowAny, and gl_context::Version.
Referenced by _mesa_BeginQueryIndexed(), _mesa_DeleteQueries(), _mesa_EndQueryIndexed(), and _mesa_GetQueryIndexediv().
get_query_object()
static void get_query_object (struct gl_context * ctx, const char * func, GLuint id, GLenum pname, GLenum ptype, struct gl_buffer_object * buf, intptr_t offset) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_query_object(), gl_query_object::Active, gl_extensions::ARB_query_buffer_object, dd_function_table::CheckQuery, gl_context::Driver, gl_query_object::EverBound, gl_context::Extensions, GLAPIENTRY, GLuint, MESA_VERBOSE, gl_shared_state::NullBufferObj, gl_query_object::Ready, gl_query_object::Result, gl_context::Shared, gl_buffer_object::Size, dd_function_table::StoreQueryResult, gl_query_object::Target, VERBOSE_API, and dd_function_table::WaitQuery.
Referenced by _mesa_GetQueryBufferObjecti64v(), _mesa_GetQueryBufferObjectiv(), _mesa_GetQueryBufferObjectui64v(), _mesa_GetQueryBufferObjectuiv(), _mesa_GetQueryObjecti64v(), _mesa_GetQueryObjectiv(), _mesa_GetQueryObjectui64v(), and _mesa_GetQueryObjectuiv().
query_error_check_index()
static GLboolean query_error_check_index (struct gl_context * ctx, GLenum target, GLuint index) static
References _mesa_error(), gl_context::Const, GLAPIENTRY, and gl_constants::MaxVertexStreams.
Referenced by _mesa_BeginQueryIndexed(), _mesa_EndQueryIndexed(), and _mesa_GetQueryIndexediv().