Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
rastpos.h File Reference
Raster position operations.
#include "glheader.h"
Functions
void _mesa_init_rastpos (struct gl_context *ctx)
Initialize the context current raster position information.
void _mesa_RasterPos (struct gl_context *ctx, const GLfloat vObj[4])
glRasterPos transformation.
void GLAPIENTRY _mesa_RasterPos2d (GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_RasterPos2f (GLfloat x, GLfloat y)
void GLAPIENTRY _mesa_RasterPos2i (GLint x, GLint y)
void GLAPIENTRY _mesa_RasterPos2s (GLshort x, GLshort y)
void GLAPIENTRY _mesa_RasterPos3d (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_RasterPos3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _mesa_RasterPos3i (GLint x, GLint y, GLint z)
void GLAPIENTRY _mesa_RasterPos3s (GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_RasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_RasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_RasterPos4i (GLint x, GLint y, GLint z, GLint w)
void GLAPIENTRY _mesa_RasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_RasterPos2dv (const GLdouble *v)
void GLAPIENTRY _mesa_RasterPos2fv (const GLfloat *v)
void GLAPIENTRY _mesa_RasterPos2iv (const GLint *v)
void GLAPIENTRY _mesa_RasterPos2sv (const GLshort *v)
void GLAPIENTRY _mesa_RasterPos3dv (const GLdouble *v)
void GLAPIENTRY _mesa_RasterPos3fv (const GLfloat *v)
void GLAPIENTRY _mesa_RasterPos3iv (const GLint *v)
void GLAPIENTRY _mesa_RasterPos3sv (const GLshort *v)
void GLAPIENTRY _mesa_RasterPos4dv (const GLdouble *v)
void GLAPIENTRY _mesa_RasterPos4fv (const GLfloat *v)
void GLAPIENTRY _mesa_RasterPos4iv (const GLint *v)
void GLAPIENTRY _mesa_RasterPos4sv (const GLshort *v)
void GLAPIENTRY _mesa_WindowPos2d (GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_WindowPos2f (GLfloat x, GLfloat y)
void GLAPIENTRY _mesa_WindowPos2i (GLint x, GLint y)
void GLAPIENTRY _mesa_WindowPos2s (GLshort x, GLshort y)
void GLAPIENTRY _mesa_WindowPos3d (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_WindowPos3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _mesa_WindowPos3i (GLint x, GLint y, GLint z)
void GLAPIENTRY _mesa_WindowPos3s (GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_WindowPos4dMESA (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_WindowPos4fMESA (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_WindowPos4iMESA (GLint x, GLint y, GLint z, GLint w)
void GLAPIENTRY _mesa_WindowPos4sMESA (GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_WindowPos2dv (const GLdouble *v)
void GLAPIENTRY _mesa_WindowPos2fv (const GLfloat *v)
void GLAPIENTRY _mesa_WindowPos2iv (const GLint *v)
void GLAPIENTRY _mesa_WindowPos2sv (const GLshort *v)
void GLAPIENTRY _mesa_WindowPos3dv (const GLdouble *v)
void GLAPIENTRY _mesa_WindowPos3fv (const GLfloat *v)
void GLAPIENTRY _mesa_WindowPos3iv (const GLint *v)
void GLAPIENTRY _mesa_WindowPos3sv (const GLshort *v)
void GLAPIENTRY _mesa_WindowPos4dvMESA (const GLdouble *v)
void GLAPIENTRY _mesa_WindowPos4fvMESA (const GLfloat *v)
void GLAPIENTRY _mesa_WindowPos4ivMESA (const GLint *v)
void GLAPIENTRY _mesa_WindowPos4svMESA (const GLshort *v)
Detailed Description
Raster position operations.
Function Documentation
_mesa_init_rastpos()
void _mesa_init_rastpos (struct gl_context * ctx)
Initialize the context current raster position information.
Parameters
ctx GL context.
Initialize the current raster position information in __struct gl_contextRec::Current, and adds the extension entry points to the dispatcher.
References gl_context::Current, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_current_attrib::RasterPosValid, gl_current_attrib::RasterSecondaryColor, and gl_current_attrib::RasterTexCoords.
Referenced by init_attrib_groups().
_mesa_RasterPos()
void _mesa_RasterPos (struct gl_context * ctx, const GLfloat vObj[4])
glRasterPos transformation.
Typically called via ctx->Driver.RasterPos().
Parameters
vObj vertex position in object space
References gl_vertex_program_state::_Enabled, _mesa_get_viewport_xform(), _mesa_problem(), _mesa_update_hitflag(), gl_context::_NeedEyeCoords, gl_current_attrib::Attrib, gl_transform_attrib::ClipPlanesEnabled, compute_texgen(), gl_context::Const, COPY_4V, gl_context::Current, gl_transform_attrib::DepthClamp, gl_light_attrib::Enabled, F, gl_viewport_attrib::Far, gl_context::Fog, gl_fog_attrib::FogCoordinateSource, GLuint, GLmatrix::inv, gl_context::Light, GLmatrix::m, gl_constants::MaxTextureCoordUnits, gl_context::ModelviewMatrixStack, gl_viewport_attrib::Near, gl_context::ProjectionMatrixStack, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_transform_attrib::RasterPositionUnclipped, gl_current_attrib::RasterPosValid, gl_current_attrib::RasterSecondaryColor, gl_current_attrib::RasterTexCoords, gl_context::RenderMode, shade_rastpos(), gl_texture_unit::TexGenEnabled, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, gl_context::Transform, TRANSFORM_NORMAL, TRANSFORM_POINT, gl_texture_attrib::Unit, userclip_point(), gl_context::VertexProgram, viewclip_point_xy(), viewclip_point_z(), and gl_context::ViewportArray.
_mesa_RasterPos2d()
void GLAPIENTRY _mesa_RasterPos2d (GLdouble x, GLdouble y)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos2dv()
void GLAPIENTRY _mesa_RasterPos2dv (const GLdouble * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2f()
void GLAPIENTRY _mesa_RasterPos2f (GLfloat x, GLfloat y)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2fv()
void GLAPIENTRY _mesa_RasterPos2fv (const GLfloat * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2i()
void GLAPIENTRY _mesa_RasterPos2i (GLint x, GLint y)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2iv()
void GLAPIENTRY _mesa_RasterPos2iv (const GLint * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2s()
void GLAPIENTRY _mesa_RasterPos2s (GLshort x, GLshort y)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2sv()
void GLAPIENTRY _mesa_RasterPos2sv (const GLshort * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3d()
void GLAPIENTRY _mesa_RasterPos3d (GLdouble x, GLdouble y, GLdouble z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3dv()
void GLAPIENTRY _mesa_RasterPos3dv (const GLdouble * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3f()
void GLAPIENTRY _mesa_RasterPos3f (GLfloat x, GLfloat y, GLfloat z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3fv()
void GLAPIENTRY _mesa_RasterPos3fv (const GLfloat * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3i()
void GLAPIENTRY _mesa_RasterPos3i (GLint x, GLint y, GLint z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3iv()
void GLAPIENTRY _mesa_RasterPos3iv (const GLint * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3s()
void GLAPIENTRY _mesa_RasterPos3s (GLshort x, GLshort y, GLshort z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3sv()
void GLAPIENTRY _mesa_RasterPos3sv (const GLshort * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos4d()
void GLAPIENTRY _mesa_RasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4dv()
void GLAPIENTRY _mesa_RasterPos4dv (const GLdouble * v)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4f()
void GLAPIENTRY _mesa_RasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4fv()
void GLAPIENTRY _mesa_RasterPos4fv (const GLfloat * v)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4i()
void GLAPIENTRY _mesa_RasterPos4i (GLint x, GLint y, GLint z, GLint w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4iv()
void GLAPIENTRY _mesa_RasterPos4iv (const GLint * v)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4s()
void GLAPIENTRY _mesa_RasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4sv()
void GLAPIENTRY _mesa_RasterPos4sv (const GLshort * v)
References rasterpos().
_mesa_WindowPos2d()
void GLAPIENTRY _mesa_WindowPos2d (GLdouble x, GLdouble y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2dv()
void GLAPIENTRY _mesa_WindowPos2dv (const GLdouble * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2f()
void GLAPIENTRY _mesa_WindowPos2f (GLfloat x, GLfloat y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2fv()
void GLAPIENTRY _mesa_WindowPos2fv (const GLfloat * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2i()
void GLAPIENTRY _mesa_WindowPos2i (GLint x, GLint y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2iv()
void GLAPIENTRY _mesa_WindowPos2iv (const GLint * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2s()
void GLAPIENTRY _mesa_WindowPos2s (GLshort x, GLshort y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2sv()
void GLAPIENTRY _mesa_WindowPos2sv (const GLshort * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3d()
void GLAPIENTRY _mesa_WindowPos3d (GLdouble x, GLdouble y, GLdouble z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3dv()
void GLAPIENTRY _mesa_WindowPos3dv (const GLdouble * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3f()
void GLAPIENTRY _mesa_WindowPos3f (GLfloat x, GLfloat y, GLfloat z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3fv()
void GLAPIENTRY _mesa_WindowPos3fv (const GLfloat * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3i()
void GLAPIENTRY _mesa_WindowPos3i (GLint x, GLint y, GLint z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3iv()
void GLAPIENTRY _mesa_WindowPos3iv (const GLint * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3s()
void GLAPIENTRY _mesa_WindowPos3s (GLshort x, GLshort y, GLshort z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3sv()
void GLAPIENTRY _mesa_WindowPos3sv (const GLshort * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4dMESA()
void GLAPIENTRY _mesa_WindowPos4dMESA (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4dvMESA()
void GLAPIENTRY _mesa_WindowPos4dvMESA (const GLdouble * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4fMESA()
void GLAPIENTRY _mesa_WindowPos4fMESA (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4fvMESA()
void GLAPIENTRY _mesa_WindowPos4fvMESA (const GLfloat * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4iMESA()
void GLAPIENTRY _mesa_WindowPos4iMESA (GLint x, GLint y, GLint z, GLint w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4ivMESA()
void GLAPIENTRY _mesa_WindowPos4ivMESA (const GLint * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4sMESA()
void GLAPIENTRY _mesa_WindowPos4sMESA (GLshort x, GLshort y, GLshort z, GLshort w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4svMESA()
void GLAPIENTRY _mesa_WindowPos4svMESA (const GLshort * v)
References window_pos4f(), and x.