Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
rastpos.c File Reference
Raster position operations.
#include "glheader.h"
#include "context.h"
#include "feedback.h"
#include "macros.h"
#include "mtypes.h"
#include "rastpos.h"
#include "state.h"
#include "main/dispatch.h"
#include "main/viewport.h"
#include "util/bitscan.h"
Functions
static GLuint viewclip_point_xy (const GLfloat v[])
Clip a point against the view volume.
static GLuint viewclip_point_z (const GLfloat v[])
Clip a point against the far/near Z clipping planes.
static GLuint userclip_point (struct gl_context *ctx, const GLfloat v[])
Clip a point against the user clipping planes.
static void shade_rastpos (struct gl_context *ctx, const GLfloat vertex[4], const GLfloat normal[3], GLfloat Rcolor[4], GLfloat Rspec[4])
Compute lighting for the raster position.
static void compute_texgen (struct gl_context *ctx, const GLfloat vObj[4], const GLfloat vEye[4], const GLfloat normal[3], GLuint unit, GLfloat texcoord[4])
Do texgen needed for glRasterPos.
void _mesa_RasterPos (struct gl_context *ctx, const GLfloat vObj[4])
glRasterPos transformation.
static void rasterpos (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Helper function for all the RasterPos functions.
void GLAPIENTRY _mesa_RasterPos2d (GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_RasterPos2f (GLfloat x, GLfloat y)
void GLAPIENTRY _mesa_RasterPos2i (GLint x, GLint y)
void GLAPIENTRY _mesa_RasterPos2s (GLshort x, GLshort y)
void GLAPIENTRY _mesa_RasterPos3d (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_RasterPos3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _mesa_RasterPos3i (GLint x, GLint y, GLint z)
void GLAPIENTRY _mesa_RasterPos3s (GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_RasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_RasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_RasterPos4i (GLint x, GLint y, GLint z, GLint w)
void GLAPIENTRY _mesa_RasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_RasterPos2dv (const GLdouble *v)
void GLAPIENTRY _mesa_RasterPos2fv (const GLfloat *v)
void GLAPIENTRY _mesa_RasterPos2iv (const GLint *v)
void GLAPIENTRY _mesa_RasterPos2sv (const GLshort *v)
void GLAPIENTRY _mesa_RasterPos3dv (const GLdouble *v)
void GLAPIENTRY _mesa_RasterPos3fv (const GLfloat *v)
void GLAPIENTRY _mesa_RasterPos3iv (const GLint *v)
void GLAPIENTRY _mesa_RasterPos3sv (const GLshort *v)
void GLAPIENTRY _mesa_RasterPos4dv (const GLdouble *v)
void GLAPIENTRY _mesa_RasterPos4fv (const GLfloat *v)
void GLAPIENTRY _mesa_RasterPos4iv (const GLint *v)
void GLAPIENTRY _mesa_RasterPos4sv (const GLshort *v)
static void window_pos3f (GLfloat x, GLfloat y, GLfloat z)
All glWindowPosMESA and glWindowPosARB commands call this function to update the current raster position.
static void window_pos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_WindowPos2d (GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_WindowPos2f (GLfloat x, GLfloat y)
void GLAPIENTRY _mesa_WindowPos2i (GLint x, GLint y)
void GLAPIENTRY _mesa_WindowPos2s (GLshort x, GLshort y)
void GLAPIENTRY _mesa_WindowPos3d (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_WindowPos3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _mesa_WindowPos3i (GLint x, GLint y, GLint z)
void GLAPIENTRY _mesa_WindowPos3s (GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_WindowPos4dMESA (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_WindowPos4fMESA (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_WindowPos4iMESA (GLint x, GLint y, GLint z, GLint w)
void GLAPIENTRY _mesa_WindowPos4sMESA (GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_WindowPos2dv (const GLdouble *v)
void GLAPIENTRY _mesa_WindowPos2fv (const GLfloat *v)
void GLAPIENTRY _mesa_WindowPos2iv (const GLint *v)
void GLAPIENTRY _mesa_WindowPos2sv (const GLshort *v)
void GLAPIENTRY _mesa_WindowPos3dv (const GLdouble *v)
void GLAPIENTRY _mesa_WindowPos3fv (const GLfloat *v)
void GLAPIENTRY _mesa_WindowPos3iv (const GLint *v)
void GLAPIENTRY _mesa_WindowPos3sv (const GLshort *v)
void GLAPIENTRY _mesa_WindowPos4dvMESA (const GLdouble *v)
void GLAPIENTRY _mesa_WindowPos4fvMESA (const GLfloat *v)
void GLAPIENTRY _mesa_WindowPos4ivMESA (const GLint *v)
void GLAPIENTRY _mesa_WindowPos4svMESA (const GLshort *v)
Initialization
void _mesa_init_rastpos (struct gl_context *ctx)
Initialize the context current raster position information.
Detailed Description
Raster position operations.
Function Documentation
_mesa_init_rastpos()
void _mesa_init_rastpos (struct gl_context * ctx)
Initialize the context current raster position information.
Parameters
ctx GL context.
Initialize the current raster position information in __struct gl_contextRec::Current, and adds the extension entry points to the dispatcher.
References gl_context::Current, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_current_attrib::RasterPosValid, gl_current_attrib::RasterSecondaryColor, and gl_current_attrib::RasterTexCoords.
Referenced by init_attrib_groups().
_mesa_RasterPos()
void _mesa_RasterPos (struct gl_context * ctx, const GLfloat vObj[4])
glRasterPos transformation.
Typically called via ctx->Driver.RasterPos().
Parameters
vObj vertex position in object space
References gl_vertex_program_state::_Enabled, _mesa_get_viewport_xform(), _mesa_problem(), _mesa_update_hitflag(), gl_context::_NeedEyeCoords, gl_current_attrib::Attrib, gl_transform_attrib::ClipPlanesEnabled, compute_texgen(), gl_context::Const, COPY_4V, gl_context::Current, gl_transform_attrib::DepthClamp, gl_light_attrib::Enabled, F, gl_viewport_attrib::Far, gl_context::Fog, gl_fog_attrib::FogCoordinateSource, GLuint, GLmatrix::inv, gl_context::Light, GLmatrix::m, gl_constants::MaxTextureCoordUnits, gl_context::ModelviewMatrixStack, gl_viewport_attrib::Near, gl_context::ProjectionMatrixStack, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_transform_attrib::RasterPositionUnclipped, gl_current_attrib::RasterPosValid, gl_current_attrib::RasterSecondaryColor, gl_current_attrib::RasterTexCoords, gl_context::RenderMode, shade_rastpos(), gl_texture_unit::TexGenEnabled, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, gl_context::Transform, TRANSFORM_NORMAL, TRANSFORM_POINT, gl_texture_attrib::Unit, userclip_point(), gl_context::VertexProgram, viewclip_point_xy(), viewclip_point_z(), and gl_context::ViewportArray.
_mesa_RasterPos2d()
void GLAPIENTRY _mesa_RasterPos2d (GLdouble x, GLdouble y)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos2dv()
void GLAPIENTRY _mesa_RasterPos2dv (const GLdouble * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2f()
void GLAPIENTRY _mesa_RasterPos2f (GLfloat x, GLfloat y)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2fv()
void GLAPIENTRY _mesa_RasterPos2fv (const GLfloat * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2i()
void GLAPIENTRY _mesa_RasterPos2i (GLint x, GLint y)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2iv()
void GLAPIENTRY _mesa_RasterPos2iv (const GLint * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2s()
void GLAPIENTRY _mesa_RasterPos2s (GLshort x, GLshort y)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos2sv()
void GLAPIENTRY _mesa_RasterPos2sv (const GLshort * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3d()
void GLAPIENTRY _mesa_RasterPos3d (GLdouble x, GLdouble y, GLdouble z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3dv()
void GLAPIENTRY _mesa_RasterPos3dv (const GLdouble * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3f()
void GLAPIENTRY _mesa_RasterPos3f (GLfloat x, GLfloat y, GLfloat z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3fv()
void GLAPIENTRY _mesa_RasterPos3fv (const GLfloat * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3i()
void GLAPIENTRY _mesa_RasterPos3i (GLint x, GLint y, GLint z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3iv()
void GLAPIENTRY _mesa_RasterPos3iv (const GLint * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3s()
void GLAPIENTRY _mesa_RasterPos3s (GLshort x, GLshort y, GLshort z)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos3sv()
void GLAPIENTRY _mesa_RasterPos3sv (const GLshort * v)
References F, GLAPIENTRY, and rasterpos().
_mesa_RasterPos4d()
void GLAPIENTRY _mesa_RasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4dv()
void GLAPIENTRY _mesa_RasterPos4dv (const GLdouble * v)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4f()
void GLAPIENTRY _mesa_RasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4fv()
void GLAPIENTRY _mesa_RasterPos4fv (const GLfloat * v)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4i()
void GLAPIENTRY _mesa_RasterPos4i (GLint x, GLint y, GLint z, GLint w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4iv()
void GLAPIENTRY _mesa_RasterPos4iv (const GLint * v)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4s()
void GLAPIENTRY _mesa_RasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
References GLAPIENTRY, and rasterpos().
_mesa_RasterPos4sv()
void GLAPIENTRY _mesa_RasterPos4sv (const GLshort * v)
References rasterpos().
_mesa_WindowPos2d()
void GLAPIENTRY _mesa_WindowPos2d (GLdouble x, GLdouble y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2dv()
void GLAPIENTRY _mesa_WindowPos2dv (const GLdouble * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2f()
void GLAPIENTRY _mesa_WindowPos2f (GLfloat x, GLfloat y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2fv()
void GLAPIENTRY _mesa_WindowPos2fv (const GLfloat * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2i()
void GLAPIENTRY _mesa_WindowPos2i (GLint x, GLint y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2iv()
void GLAPIENTRY _mesa_WindowPos2iv (const GLint * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2s()
void GLAPIENTRY _mesa_WindowPos2s (GLshort x, GLshort y)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos2sv()
void GLAPIENTRY _mesa_WindowPos2sv (const GLshort * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3d()
void GLAPIENTRY _mesa_WindowPos3d (GLdouble x, GLdouble y, GLdouble z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3dv()
void GLAPIENTRY _mesa_WindowPos3dv (const GLdouble * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3f()
void GLAPIENTRY _mesa_WindowPos3f (GLfloat x, GLfloat y, GLfloat z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3fv()
void GLAPIENTRY _mesa_WindowPos3fv (const GLfloat * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3i()
void GLAPIENTRY _mesa_WindowPos3i (GLint x, GLint y, GLint z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3iv()
void GLAPIENTRY _mesa_WindowPos3iv (const GLint * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3s()
void GLAPIENTRY _mesa_WindowPos3s (GLshort x, GLshort y, GLshort z)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos3sv()
void GLAPIENTRY _mesa_WindowPos3sv (const GLshort * v)
References F, GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4dMESA()
void GLAPIENTRY _mesa_WindowPos4dMESA (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4dvMESA()
void GLAPIENTRY _mesa_WindowPos4dvMESA (const GLdouble * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4fMESA()
void GLAPIENTRY _mesa_WindowPos4fMESA (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4fvMESA()
void GLAPIENTRY _mesa_WindowPos4fvMESA (const GLfloat * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4iMESA()
void GLAPIENTRY _mesa_WindowPos4iMESA (GLint x, GLint y, GLint z, GLint w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4ivMESA()
void GLAPIENTRY _mesa_WindowPos4ivMESA (const GLint * v)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4sMESA()
void GLAPIENTRY _mesa_WindowPos4sMESA (GLshort x, GLshort y, GLshort z, GLshort w)
References GLAPIENTRY, and window_pos4f().
_mesa_WindowPos4svMESA()
void GLAPIENTRY _mesa_WindowPos4svMESA (const GLshort * v)
References window_pos4f(), and x.
compute_texgen()
static void compute_texgen (struct gl_context * ctx, const GLfloat vObj[4], const GLfloat vEye[4], const GLfloat normal[3], GLuint unit, GLfloat texcoord[4]) static
Do texgen needed for glRasterPos.
Parameters
ctx rendering context
vObj object-space vertex coordinate
vEye eye-space vertex coordinate
normal vertex normal
unit texture unit number
texcoord incoming texcoord and resulting texcoord
References _mesa_problem(), COPY_3V, DOT3(), DOT4(), gl_texgen::EyePlane, F, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, gl_texgen::Mode, NORMALIZE_3FV(), gl_texgen::ObjectPlane, Q_BIT, R_BIT, S_BIT, T_BIT, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_RasterPos().
rasterpos()
static void rasterpos (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
Helper function for all the RasterPos functions.
References _mesa_update_state(), FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and x.
Referenced by _mesa_RasterPos2d(), _mesa_RasterPos2dv(), _mesa_RasterPos2f(), _mesa_RasterPos2fv(), _mesa_RasterPos2i(), _mesa_RasterPos2iv(), _mesa_RasterPos2s(), _mesa_RasterPos2sv(), _mesa_RasterPos3d(), _mesa_RasterPos3dv(), _mesa_RasterPos3f(), _mesa_RasterPos3fv(), _mesa_RasterPos3i(), _mesa_RasterPos3iv(), _mesa_RasterPos3s(), _mesa_RasterPos3sv(), _mesa_RasterPos4d(), _mesa_RasterPos4dv(), _mesa_RasterPos4f(), _mesa_RasterPos4fv(), _mesa_RasterPos4i(), _mesa_RasterPos4iv(), _mesa_RasterPos4s(), and _mesa_RasterPos4sv().
shade_rastpos()
static void shade_rastpos (struct gl_context * ctx, const GLfloat vertex[4], const GLfloat normal[3], GLfloat Rcolor[4], GLfloat Rspec[4]) static
Compute lighting for the raster position.
RGB modes computed.
Parameters
ctx the context
vertex vertex location
normal normal vector
Rcolor returned color
Rspec returned specular color (if separate specular enabled)
References gl_light_attrib::_BaseColor, gl_light::_CosCutoff, gl_light_attrib::_EnabledLights, gl_context::_EyeZDir, gl_light::_Flags, gl_light::_h_inf_norm, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, gl_light::_NormSpotDirection, gl_light::_Position, gl_light::_VP_inf_norm, gl_light::_VP_inf_spot_attenuation, ACC_3V, ACC_SCALE_SCALAR_3V, ASSIGN_3V, gl_material::Attrib, gl_lightmodel::ColorControl, gl_light::ConstantAttenuation, COPY_3V, DOT3(), F, LEN_3FV(), gl_light_attrib::Light, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, gl_light::LinearAttenuation, gl_lightmodel::LocalViewer, MAT_ATTRIB_FRONT_DIFFUSE, MAT_ATTRIB_FRONT_SHININESS, gl_light_attrib::Material, gl_light_attrib::Model, NORMALIZE_3FV(), gl_light::QuadraticAttenuation, SELF_SCALE_SCALAR_3V, gl_light::SpotExponent, and SUB_3V.
Referenced by _mesa_RasterPos().
userclip_point()
static GLuint userclip_point (struct gl_context * ctx, const GLfloat v[]) static
Clip a point against the user clipping planes.
Parameters
ctx GL context.
v vertex vector describing the point to clip.
Returns
zero if the point was clipped, or one otherwise.
References gl_transform_attrib::_ClipUserPlane, gl_transform_attrib::ClipPlanesEnabled, F, and gl_context::Transform.
Referenced by _mesa_RasterPos().
viewclip_point_xy()
static GLuint viewclip_point_xy (const GLfloat v[]) static
Clip a point against the view volume.
Parameters
v vertex vector describing the point to clip.
Returns
zero if outside view volume, or one if inside.
References GLuint.
Referenced by _mesa_RasterPos().
viewclip_point_z()
static GLuint viewclip_point_z (const GLfloat v[]) static
Clip a point against the far/near Z clipping planes.
Parameters
v vertex vector describing the point to clip.
Returns
zero if outside view volume, or one if inside.
References GLuint.
Referenced by _mesa_RasterPos().
window_pos3f()
static void window_pos3f (GLfloat x, GLfloat y, GLfloat z) static
All glWindowPosMESA and glWindowPosARB commands call this function to update the current raster position.
References _mesa_update_hitflag(), F, FLUSH_CURRENT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, and if().
Referenced by window_pos4f().
window_pos4f()
static void window_pos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
References GET_CURRENT_CONTEXT, GLAPIENTRY, and window_pos3f().
Referenced by _mesa_WindowPos2d(), _mesa_WindowPos2dv(), _mesa_WindowPos2f(), _mesa_WindowPos2fv(), _mesa_WindowPos2i(), _mesa_WindowPos2iv(), _mesa_WindowPos2s(), _mesa_WindowPos2sv(), _mesa_WindowPos3d(), _mesa_WindowPos3dv(), _mesa_WindowPos3f(), _mesa_WindowPos3fv(), _mesa_WindowPos3i(), _mesa_WindowPos3iv(), _mesa_WindowPos3s(), _mesa_WindowPos3sv(), _mesa_WindowPos4dMESA(), _mesa_WindowPos4dvMESA(), _mesa_WindowPos4fMESA(), _mesa_WindowPos4fvMESA(), _mesa_WindowPos4iMESA(), _mesa_WindowPos4ivMESA(), _mesa_WindowPos4sMESA(), and _mesa_WindowPos4svMESA().