Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
readpix.c File Reference
#include "glheader.h"
#include "imports.h"
#include "blend.h"
#include "bufferobj.h"
#include "context.h"
#include "enums.h"
#include "readpix.h"
#include "framebuffer.h"
#include "formats.h"
#include "format_unpack.h"
#include "image.h"
#include "mtypes.h"
#include "pack.h"
#include "pbo.h"
#include "state.h"
#include "glformats.h"
#include "fbobject.h"
#include "format_utils.h"
#include "pixeltransfer.h"
Functions
GLboolean _mesa_need_rgb_to_luminance_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L=R+G+B is needed.
GLboolean _mesa_need_luminance_to_rgb_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L,I to RGB conversion is needed.
GLbitfield _mesa_get_readpixels_transfer_ops (const struct gl_context *ctx, mesa_format texFormat, GLenum format, GLenum type, GLboolean uses_blit)
Return transfer op flags for this ReadPixels operation.
GLboolean _mesa_readpixels_needs_slow_path (const struct gl_context *ctx, GLenum format, GLenum type, GLboolean uses_blit)
Return true if memcpy cannot be used for ReadPixels.
static GLboolean readpixels_can_use_memcpy (const struct gl_context *ctx, GLenum format, GLenum type, const struct gl_pixelstore_attrib *packing)
static GLboolean readpixels_memcpy (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
static GLboolean read_uint_depth_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Optimized path for conversion of depth values to GL_DEPTH_COMPONENT, GL_UNSIGNED_INT.
static void read_depth_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Read pixels for format=GL_DEPTH_COMPONENT.
static void read_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Read pixels for format=GL_STENCIL_INDEX.
static void read_rgba_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
static GLboolean fast_read_depth_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLubyte *dst, int dstStride)
For a packed depth/stencil buffer being read as depth/stencil, just memcpy the data (possibly swapping 8/24 vs 24/8 as we go).
static GLboolean fast_read_depth_stencil_pixels_separate (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, uint32_t *dst, int dstStride)
For non-float-depth and stencil buffers being read as 24/8 depth/stencil, copy the integer data directly instead of converting depth to float and re-packing.
static void slow_read_depth_stencil_pixels_separate (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib *packing, GLubyte *dst, int dstStride)
static void read_depth_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Read combined depth/stencil values.
void _mesa_readpixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *packing, GLvoid *pixels)
Software fallback routine for ctx->Driver.ReadPixels().
static GLenum read_pixels_es3_error_check (GLenum format, GLenum type, const struct gl_renderbuffer *rb)
void GLAPIENTRY _mesa_ReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_ReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
Function Documentation
_mesa_get_readpixels_transfer_ops()
GLbitfield _mesa_get_readpixels_transfer_ops (const struct gl_context * ctx, mesa_format texFormat, GLenum format, GLenum type, GLboolean uses_blit)
Return transfer op flags for this ReadPixels operation.
References gl_context::_ImageTransferState, _mesa_get_clamp_read_color(), _mesa_get_format_base_format(), _mesa_get_format_datatype(), _mesa_is_enum_format_integer(), _mesa_need_rgb_to_luminance_conversion(), _mesa_unpack_format_to_base_format(), IMAGE_CLAMP_BIT, and gl_context::ReadBuffer.
Referenced by _mesa_readpixels_needs_slow_path(), and read_rgba_pixels().
_mesa_need_luminance_to_rgb_conversion()
GLboolean _mesa_need_luminance_to_rgb_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L,I to RGB conversion is needed.
_mesa_need_rgb_to_luminance_conversion()
GLboolean _mesa_need_rgb_to_luminance_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L=R+G+B is needed.
Referenced by _mesa_get_readpixels_transfer_ops(), _mesa_readpixels_needs_slow_path(), and read_rgba_pixels().
_mesa_ReadnPixelsARB()
void GLAPIENTRY _mesa_ReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_check_disallowed_mapping(), _mesa_clip_readpixels(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_es_error_check_format_and_type(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_read_renderbuffer_for_format(), _mesa_is_bufferobj(), _mesa_is_color_format(), _mesa_is_enum_format_integer(), _mesa_is_format_integer_color(), _mesa_is_gles(), _mesa_is_user_fbo(), _mesa_source_buffer_exists(), _mesa_update_state(), _mesa_validate_pbo_access(), API_OPENGLES2, FLUSH_CURRENT, FLUSH_VERTICES, gl_renderbuffer::Format, GET_CURRENT_CONTEXT, GL_HALF_FLOAT_OES, GLAPIENTRY, MESA_VERBOSE, read_pixels_es3_error_check(), and VERBOSE_API.
Referenced by _mesa_ReadPixels().
_mesa_readpixels()
void _mesa_readpixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * packing, GLvoid * pixels)
Software fallback routine for ctx->Driver.ReadPixels().
By time we get here, all error checking will have been done.
References _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), _mesa_update_state(), gl_context::NewState, read_depth_pixels(), read_depth_stencil_pixels(), read_rgba_pixels(), read_stencil_pixels(), and readpixels_memcpy().
_mesa_ReadPixels()
void GLAPIENTRY _mesa_ReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_ReadnPixelsARB().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), and _mesa_dump_stencil_buffer().
_mesa_readpixels_needs_slow_path()
GLboolean _mesa_readpixels_needs_slow_path (const struct gl_context * ctx, GLenum format, GLenum type, GLboolean uses_blit)
Return true if memcpy cannot be used for ReadPixels.
If uses_blit is true, the function returns true if a simple 3D engine blit cannot be used for ReadPixels packing.
NOTE: This doesn't take swizzling and format conversions between the readbuffer and the pixel pack buffer into account.
References gl_renderbuffer::_BaseFormat, _mesa_get_read_renderbuffer_for_format(), _mesa_get_readpixels_transfer_ops(), _mesa_has_depthstencil_combined(), _mesa_need_rgb_to_luminance_conversion(), _mesa_unpack_format_to_base_format(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_renderbuffer::Format, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_context::ReadBuffer.
Referenced by readpixels_can_use_memcpy().
fast_read_depth_stencil_pixels()
static GLboolean fast_read_depth_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLubyte * dst, int dstStride) static
For a packed depth/stencil buffer being read as depth/stencil, just memcpy the data (possibly swapping 8/24 vs 24/8 as we go).
References _mesa_error(), _mesa_unpack_uint_24_8_depth_stencil_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_Z24_UNORM_S8_UINT, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_stencil_pixels().
fast_read_depth_stencil_pixels_separate()
static GLboolean fast_read_depth_stencil_pixels_separate (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, uint32_t * dst, int dstStride) static
For non-float-depth and stencil buffers being read as 24/8 depth/stencil, copy the integer data directly instead of converting depth to float and re-packing.
References _mesa_error(), _mesa_get_format_datatype(), _mesa_unpack_ubyte_stencil_row(), _mesa_unpack_uint_z_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_stencil_pixels().
read_depth_pixels()
static void read_depth_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Read pixels for format=GL_DEPTH_COMPONENT.
References _mesa_error(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_pack_depth_span(), _mesa_unpack_float_z_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, gl_context::Driver, gl_renderbuffer::Format, gl_renderbuffer::Height, dd_function_table::MapRenderbuffer, read_uint_depth_pixels(), gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::UnmapRenderbuffer, and gl_renderbuffer::Width.
Referenced by _mesa_readpixels().
read_depth_stencil_pixels()
static void read_depth_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Read combined depth/stencil values.
We'll have already done error checking to be sure the expected depth and stencil buffers really exist.
References _mesa_image_address2d(), _mesa_image_row_stride(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, slow_read_depth_stencil_pixels_separate(), and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_readpixels().
read_pixels_es3_error_check()
static GLenum read_pixels_es3_error_check (GLenum format, GLenum type, const struct gl_renderbuffer * rb) static
References _mesa_get_format_datatype(), _mesa_is_enum_format_signed_int(), _mesa_is_enum_format_unsigned_int(), gl_renderbuffer::Format, GLAPIENTRY, and gl_renderbuffer::InternalFormat.
Referenced by _mesa_ReadnPixelsARB().
read_rgba_pixels()
static void read_rgba_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorReadBuffer, _mesa_apply_rgba_transfer_ops(), _mesa_compute_rgba2base2rgba_component_mapping(), _mesa_error(), _mesa_format_convert(), _mesa_format_from_format_and_type(), _mesa_get_format_base_format(), _mesa_get_readpixels_transfer_ops(), _mesa_get_srgb_format_linear(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_is_enum_format_integer(), _mesa_is_format_unsigned(), _mesa_need_rgb_to_luminance_conversion(), _mesa_pack_luminance_from_rgba_float(), _mesa_pack_luminance_from_rgba_integer(), _mesa_swap_bytes_2d_image(), _mesa_unpack_format_to_base_format(), gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, MESA_FORMAT_SWIZZLE_ONE, MESA_FORMAT_SWIZZLE_W, MESA_FORMAT_SWIZZLE_X, MESA_FORMAT_SWIZZLE_ZERO, gl_context::ReadBuffer, RGBA32_FLOAT, RGBA32_INT, RGBA32_UINT, gl_pixelstore_attrib::SwapBytes, and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_readpixels().
read_stencil_pixels()
static void read_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Read pixels for format=GL_STENCIL_INDEX.
References _mesa_error(), _mesa_image_address2d(), _mesa_pack_stencil_span(), _mesa_unpack_ubyte_stencil_row(), gl_framebuffer::Attachment, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_readpixels().
read_uint_depth_pixels()
static GLboolean read_uint_depth_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Optimized path for conversion of depth values to GL_DEPTH_COMPONENT, GL_UNSIGNED_INT.
References _mesa_error(), _mesa_get_format_datatype(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_unpack_uint_z_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, gl_context::Pixel, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_pixelstore_attrib::SwapBytes, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_pixels().
readpixels_can_use_memcpy()
static GLboolean readpixels_can_use_memcpy (const struct gl_context * ctx, GLenum format, GLenum type, const struct gl_pixelstore_attrib * packing) static
References gl_renderbuffer::_BaseFormat, _mesa_format_matches_format_and_type(), _mesa_get_format_base_format(), _mesa_get_read_renderbuffer_for_format(), _mesa_readpixels_needs_slow_path(), gl_renderbuffer::Format, and gl_pixelstore_attrib::SwapBytes.
Referenced by readpixels_memcpy().
readpixels_memcpy()
static GLboolean readpixels_memcpy (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
References _mesa_error(), _mesa_get_format_bytes(), _mesa_get_read_renderbuffer_for_format(), _mesa_image_address2d(), _mesa_image_row_stride(), gl_context::Driver, gl_renderbuffer::Format, dd_function_table::MapRenderbuffer, readpixels_can_use_memcpy(), and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_readpixels().
slow_read_depth_stencil_pixels_separate()
static void slow_read_depth_stencil_pixels_separate (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib * packing, GLubyte * dst, int dstStride) static
References _mesa_error(), _mesa_pack_depth_stencil_span(), _mesa_unpack_float_z_row(), _mesa_unpack_ubyte_stencil_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLuint, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_stencil_pixels().