Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
readpix.h File Reference
#include "glheader.h"
Functions
GLboolean _mesa_readpixels_needs_slow_path (const struct gl_context *ctx, GLenum format, GLenum type, GLboolean uses_blit)
Return true if memcpy cannot be used for ReadPixels.
GLboolean _mesa_need_rgb_to_luminance_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L=R+G+B is needed.
GLboolean _mesa_need_luminance_to_rgb_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L,I to RGB conversion is needed.
GLbitfield _mesa_get_readpixels_transfer_ops (const struct gl_context *ctx, mesa_format texFormat, GLenum format, GLenum type, GLboolean uses_blit)
Return transfer op flags for this ReadPixels operation.
void _mesa_readpixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *packing, GLvoid *pixels)
Software fallback routine for ctx->Driver.ReadPixels().
void GLAPIENTRY _mesa_ReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
void GLAPIENTRY _mesa_ReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
Function Documentation
_mesa_get_readpixels_transfer_ops()
GLbitfield _mesa_get_readpixels_transfer_ops (const struct gl_context * ctx, mesa_format texFormat, GLenum format, GLenum type, GLboolean uses_blit)
Return transfer op flags for this ReadPixels operation.
References gl_context::_ImageTransferState, _mesa_get_clamp_read_color(), _mesa_get_format_base_format(), _mesa_get_format_datatype(), _mesa_is_enum_format_integer(), _mesa_need_rgb_to_luminance_conversion(), _mesa_unpack_format_to_base_format(), IMAGE_CLAMP_BIT, and gl_context::ReadBuffer.
Referenced by _mesa_readpixels_needs_slow_path(), and read_rgba_pixels().
_mesa_need_luminance_to_rgb_conversion()
GLboolean _mesa_need_luminance_to_rgb_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L,I to RGB conversion is needed.
_mesa_need_rgb_to_luminance_conversion()
GLboolean _mesa_need_rgb_to_luminance_conversion (GLenum srcBaseFormat, GLenum dstBaseFormat)
Return true if the conversion L=R+G+B is needed.
Referenced by _mesa_get_readpixels_transfer_ops(), _mesa_readpixels_needs_slow_path(), and read_rgba_pixels().
_mesa_ReadnPixelsARB()
void GLAPIENTRY _mesa_ReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_check_disallowed_mapping(), _mesa_clip_readpixels(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_es_error_check_format_and_type(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_read_renderbuffer_for_format(), _mesa_is_bufferobj(), _mesa_is_color_format(), _mesa_is_enum_format_integer(), _mesa_is_format_integer_color(), _mesa_is_gles(), _mesa_is_user_fbo(), _mesa_source_buffer_exists(), _mesa_update_state(), _mesa_validate_pbo_access(), API_OPENGLES2, FLUSH_CURRENT, FLUSH_VERTICES, gl_renderbuffer::Format, GET_CURRENT_CONTEXT, GL_HALF_FLOAT_OES, GLAPIENTRY, MESA_VERBOSE, read_pixels_es3_error_check(), and VERBOSE_API.
Referenced by _mesa_ReadPixels().
_mesa_readpixels()
void _mesa_readpixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * packing, GLvoid * pixels)
Software fallback routine for ctx->Driver.ReadPixels().
By time we get here, all error checking will have been done.
References _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), _mesa_update_state(), gl_context::NewState, read_depth_pixels(), read_depth_stencil_pixels(), read_rgba_pixels(), read_stencil_pixels(), and readpixels_memcpy().
_mesa_ReadPixels()
void GLAPIENTRY _mesa_ReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_ReadnPixelsARB().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), and _mesa_dump_stencil_buffer().
_mesa_readpixels_needs_slow_path()
GLboolean _mesa_readpixels_needs_slow_path (const struct gl_context * ctx, GLenum format, GLenum type, GLboolean uses_blit)
Return true if memcpy cannot be used for ReadPixels.
If uses_blit is true, the function returns true if a simple 3D engine blit cannot be used for ReadPixels packing.
NOTE: This doesn't take swizzling and format conversions between the readbuffer and the pixel pack buffer into account.
References gl_renderbuffer::_BaseFormat, _mesa_get_read_renderbuffer_for_format(), _mesa_get_readpixels_transfer_ops(), _mesa_has_depthstencil_combined(), _mesa_need_rgb_to_luminance_conversion(), _mesa_unpack_format_to_base_format(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_renderbuffer::Format, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_context::ReadBuffer.
Referenced by readpixels_can_use_memcpy().