Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
remap.c File Reference
Remap table management.
#include <stdbool.h>
#include "remap.h"
#include "imports.h"
#include "glapi/glapi.h"
#include "main/remap_helper.h"
Macros
#define MAX_ENTRY_POINTS 16
#define need_MESA_remap_table
Functions
static int map_function_spec (const char *spec)
Map a function by its spec.
void _mesa_init_remap_table (void)
Initialize the remap table.
Variables
int driDispatchRemapTable [driDispatchRemapTable_size]
Detailed Description
Remap table management.
Entries in the dispatch table are either static or dynamic. The dispatch table is shared by mesa core and glapi. When they are built separately, it is possible that a static entry in mesa core is dynamic, or assigned a different static offset, in glapi. The remap table is in charge of mapping a static entry in mesa core to a dynamic entry, or the corresponding static entry, in glapi.
Macro Definition Documentation
MAX_ENTRY_POINTS
#define MAX_ENTRY_POINTS 16
Referenced by map_function_spec().
need_MESA_remap_table
#define need_MESA_remap_table
Function Documentation
_mesa_init_remap_table()
void _mesa_init_remap_table (void)
Initialize the remap table.
This is called in one_time_init(). The remap table needs to be initialized before calling the CALL/GET/SET macros defined in main/dispatch.h.
References _mesa_warning(), driDispatchRemapTable, and map_function_spec().
Referenced by one_time_init().
map_function_spec()
static int map_function_spec (const char * spec) static
Map a function by its spec.
The function will be added to glapi, and the dispatch offset will be returned.
Parameters
spec a '\0'-separated string array specifying a function. It begins with the parameter signature of the function, followed by the names of the entry points. An empty entry point name terminates the array.
Returns
the offset of the (re-)mapped function in the dispatch table, or -1.
References _glapi_add_dispatch(), and MAX_ENTRY_POINTS.
Referenced by _mesa_init_remap_table().
Variable Documentation
driDispatchRemapTable
int driDispatchRemapTable[driDispatchRemapTable_size]
Referenced by _mesa_init_remap_table().