Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
renderbuffer.c File Reference
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "fbobject.h"
#include "formats.h"
#include "mtypes.h"
#include "renderbuffer.h"
Functions
void _mesa_init_renderbuffer (struct gl_renderbuffer *rb, GLuint name)
Initialize the fields of a gl_renderbuffer to default values.
struct gl_renderbuffer * _mesa_new_renderbuffer (struct gl_context *ctx, GLuint name)
Allocate a new gl_renderbuffer object.
void _mesa_delete_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
Delete a gl_framebuffer.
void _mesa_add_renderbuffer (struct gl_framebuffer *fb, gl_buffer_index bufferName, struct gl_renderbuffer *rb)
Attach a renderbuffer to a framebuffer.
void _mesa_remove_renderbuffer (struct gl_framebuffer *fb, gl_buffer_index bufferName)
Remove the named renderbuffer from the given framebuffer.
void _mesa_reference_renderbuffer_ (struct gl_renderbuffer **ptr, struct gl_renderbuffer *rb)
Set *ptr to point to rb.
Function Documentation
_mesa_add_renderbuffer()
void _mesa_add_renderbuffer (struct gl_framebuffer * fb, gl_buffer_index bufferName, struct gl_renderbuffer * rb)
Attach a renderbuffer to a framebuffer.
Parameters
bufferName one of the BUFFER_x tokens
References _mesa_is_user_fbo(), _mesa_reference_renderbuffer(), gl_framebuffer::Attachment, BUFFER_COUNT, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::Complete, gl_renderbuffer::Name, gl_renderbuffer_attachment::Renderbuffer, and gl_renderbuffer_attachment::Type.
_mesa_delete_renderbuffer()
void _mesa_delete_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb)
Delete a gl_framebuffer.
This is the default function for renderbuffer->Delete(). Drivers which subclass gl_renderbuffer should probably implement their own delete function. But the driver might also call this function to free the object in the end.
References gl_renderbuffer::Label, and gl_renderbuffer::Mutex.
Referenced by _mesa_init_renderbuffer().
_mesa_init_renderbuffer()
void _mesa_init_renderbuffer (struct gl_renderbuffer * rb, GLuint name)
Initialize the fields of a gl_renderbuffer to default values.
References _mesa_delete_renderbuffer(), _mesa_is_gles3(), gl_renderbuffer::AllocStorage, gl_renderbuffer::ClassID, gl_renderbuffer::Delete, gl_renderbuffer::Depth, gl_renderbuffer::Format, GET_CURRENT_CONTEXT, gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, MESA_FORMAT_NONE, gl_renderbuffer::Mutex, gl_renderbuffer::Name, gl_renderbuffer::RefCount, and gl_renderbuffer::Width.
Referenced by _mesa_new_renderbuffer().
_mesa_new_renderbuffer()
struct gl_renderbuffer* _mesa_new_renderbuffer (struct gl_context * ctx, GLuint name)
Allocate a new gl_renderbuffer object.
This can be used for user-created renderbuffers or window-system renderbuffers.
References _mesa_init_renderbuffer(), and CALLOC_STRUCT.
_mesa_reference_renderbuffer_()
void _mesa_reference_renderbuffer_ (struct gl_renderbuffer ** ptr, struct gl_renderbuffer * rb)
Set *ptr to point to rb.
If *ptr points to another renderbuffer, dereference that buffer first. The new renderbuffer's refcount will be incremented. The old renderbuffer's refcount will be decremented. This is normally only called from the _mesa_reference_renderbuffer() macro when there's a real pointer change.
References gl_renderbuffer::Delete, GET_CURRENT_CONTEXT, gl_renderbuffer::Mutex, and gl_renderbuffer::RefCount.
Referenced by _mesa_reference_renderbuffer().
_mesa_remove_renderbuffer()
void _mesa_remove_renderbuffer (struct gl_framebuffer * fb, gl_buffer_index bufferName)
Remove the named renderbuffer from the given framebuffer.
Parameters
bufferName one of the BUFFER_x tokens
References _mesa_reference_renderbuffer(), gl_framebuffer::Attachment, BUFFER_COUNT, and gl_renderbuffer_attachment::Renderbuffer.