Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
robustness.c File Reference
#include <stdbool.h>
#include "context.h"
#include "debug_output.h"
#include "get.h"
#include "mtypes.h"
#include "macros.h"
#include "main/dispatch.h"
Functions
static void GLAPIENTRY _context_lost_GetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values)
static void GLAPIENTRY _context_lost_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params)
static int context_lost_nop_handler (void)
void _mesa_set_context_lost_dispatch (struct gl_context *ctx)
GLenum GLAPIENTRY _mesa_GetGraphicsResetStatusARB (void)
Returns an error code specified by GL_ARB_robustness, or GL_NO_ERROR.
Function Documentation
_context_lost_GetQueryObjectuiv()
static void GLAPIENTRY _context_lost_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint * params) static
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_set_context_lost_dispatch().
_context_lost_GetSynciv()
static void GLAPIENTRY _context_lost_GetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values) static
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_set_context_lost_dispatch().
_mesa_GetGraphicsResetStatusARB()
GLenum GLAPIENTRY _mesa_GetGraphicsResetStatusARB (void)
Returns an error code specified by GL_ARB_robustness, or GL_NO_ERROR.
Returns
current context status
References _mesa_debug(), _mesa_set_context_lost_dispatch(), GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_set_context_lost_dispatch().
_mesa_set_context_lost_dispatch()
void _mesa_set_context_lost_dispatch (struct gl_context * ctx)
References _context_lost_GetQueryObjectuiv(), _context_lost_GetSynciv(), _glapi_get_dispatch_table_size(), _glapi_set_dispatch(), _mesa_GetError(), _mesa_GetGraphicsResetStatusARB(), context_lost_nop_handler(), gl_context::ContextLost, gl_context::CurrentServerDispatch, for(), and GLAPIENTRY.
Referenced by _mesa_GetGraphicsResetStatusARB().
context_lost_nop_handler()
static int context_lost_nop_handler (void) static
References _mesa_error(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_set_context_lost_dispatch().