Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
samplerobj.h File Reference
#include "mtypes.h"
Functions
static struct gl_sampler_object * _mesa_get_samplerobj (struct gl_context *ctx, GLuint unit)
static GLboolean _mesa_is_mipmap_filter (const struct gl_sampler_object *samp)
Does the given filter state do mipmap filtering?
void _mesa_reference_sampler_object_ (struct gl_context *ctx, struct gl_sampler_object **ptr, struct gl_sampler_object *samp)
Handle reference counting.
static void _mesa_reference_sampler_object (struct gl_context *ctx, struct gl_sampler_object **ptr, struct gl_sampler_object *samp)
struct gl_sampler_object * _mesa_lookup_samplerobj (struct gl_context *ctx, GLuint name)
struct gl_sampler_object * _mesa_new_sampler_object (struct gl_context *ctx, GLuint name)
Fallback for ctx->Driver.NewSamplerObject();.
void _mesa_init_sampler_object_functions (struct dd_function_table *driver)
void _mesa_set_sampler_wrap (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum s, GLenum t, GLenum r)
void _mesa_set_sampler_filters (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum min_filter, GLenum mag_filter)
void _mesa_set_sampler_srgb_decode (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum param)
void _mesa_bind_sampler (struct gl_context *ctx, GLuint unit, struct gl_sampler_object *sampObj)
void GLAPIENTRY _mesa_GenSamplers (GLsizei count, GLuint *samplers)
void GLAPIENTRY _mesa_CreateSamplers (GLsizei count, GLuint *samplers)
void GLAPIENTRY _mesa_DeleteSamplers (GLsizei count, const GLuint *samplers)
GLboolean GLAPIENTRY _mesa_IsSampler (GLuint sampler)
void GLAPIENTRY _mesa_BindSampler (GLuint unit, GLuint sampler)
void GLAPIENTRY _mesa_BindSamplers (GLuint first, GLsizei count, const GLuint *samplers)
void GLAPIENTRY _mesa_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
void GLAPIENTRY _mesa_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint *params)
void GLAPIENTRY _mesa_GetSamplerParameteriv (GLuint sampler, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint *params)
Function Documentation
_mesa_bind_sampler()
void _mesa_bind_sampler (struct gl_context * ctx, GLuint unit, struct gl_sampler_object * sampObj)
References _mesa_reference_sampler_object(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GLAPIENTRY, gl_texture_unit::Sampler, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_BindSampler(), and _mesa_reference_sampler_object().
_mesa_BindSampler()
void GLAPIENTRY _mesa_BindSampler (GLuint unit, GLuint sampler)
References _mesa_bind_sampler(), _mesa_error(), _mesa_lookup_samplerobj(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_sampler_object().
_mesa_BindSamplers()
void GLAPIENTRY _mesa_BindSamplers (GLuint first, GLsizei count, const GLuint * samplers)
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_reference_sampler_object(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, lookup_samplerobj_locked(), and gl_sampler_object::Name.
Referenced by _mesa_reference_sampler_object().
_mesa_CreateSamplers()
void GLAPIENTRY _mesa_CreateSamplers (GLsizei count, GLuint * samplers)
References create_samplers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_sampler_object().
_mesa_DeleteSamplers()
void GLAPIENTRY _mesa_DeleteSamplers (GLsizei count, const GLuint * samplers)
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashRemoveLocked(), _mesa_HashUnlockMutex(), _mesa_reference_sampler_object(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, and lookup_samplerobj_locked().
Referenced by _mesa_reference_sampler_object().
_mesa_GenSamplers()
void GLAPIENTRY _mesa_GenSamplers (GLsizei count, GLuint * samplers)
References create_samplers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_sampler_object().
_mesa_get_samplerobj()
static struct gl_sampler_object* _mesa_get_samplerobj (struct gl_context * ctx, GLuint unit) static
References gl_texture_unit::_Current, gl_texture_object::Sampler, gl_texture_unit::Sampler, gl_context::Texture, and gl_texture_attrib::Unit.
_mesa_GetSamplerParameterfv()
void GLAPIENTRY _mesa_GetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, GET_CURRENT_CONTEXT, GLAPIENTRY, if(), gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameterIiv()
void GLAPIENTRY _mesa_GetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_color_union::i, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameterIuiv()
void GLAPIENTRY _mesa_GetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, GET_CURRENT_CONTEXT, GLuint, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_color_union::ui, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameteriv()
void GLAPIENTRY _mesa_GetSamplerParameteriv (GLuint sampler, GLenum pname, GLint * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, FLOAT_TO_INT, GET_CURRENT_CONTEXT, GLAPIENTRY, IROUND(), gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_init_sampler_object_functions()
void _mesa_init_sampler_object_functions (struct dd_function_table * driver)
References _mesa_new_sampler_object(), and dd_function_table::NewSamplerObject.
Referenced by _mesa_reference_sampler_object().
_mesa_is_mipmap_filter()
static GLboolean _mesa_is_mipmap_filter (const struct gl_sampler_object * samp) inline static
Does the given filter state do mipmap filtering?
References _mesa_reference_sampler_object_(), and gl_sampler_object::MinFilter.
Referenced by _mesa_is_texture_complete().
_mesa_IsSampler()
GLboolean GLAPIENTRY _mesa_IsSampler (GLuint sampler)
References _mesa_lookup_samplerobj(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_sampler_object().
_mesa_lookup_samplerobj()
struct gl_sampler_object* _mesa_lookup_samplerobj (struct gl_context * ctx, GLuint name)
References _mesa_HashLookup(), gl_shared_state::SamplerObjects, and gl_context::Shared.
Referenced by _mesa_BindSampler(), _mesa_IsSampler(), _mesa_reference_sampler_object(), get_label_pointer(), and sampler_parameter_error_check().
_mesa_new_sampler_object()
struct gl_sampler_object* _mesa_new_sampler_object (struct gl_context * ctx, GLuint name)
Fallback for ctx->Driver.NewSamplerObject();.
References _mesa_init_sampler_object(), and CALLOC_STRUCT.
Referenced by _mesa_init_sampler_object_functions(), and _mesa_reference_sampler_object().
_mesa_reference_sampler_object()
static void _mesa_reference_sampler_object (struct gl_context * ctx, struct gl_sampler_object ** ptr, struct gl_sampler_object * samp) inline static
References _mesa_bind_sampler(), _mesa_BindSampler(), _mesa_BindSamplers(), _mesa_CreateSamplers(), _mesa_DeleteSamplers(), _mesa_GenSamplers(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_init_sampler_object_functions(), _mesa_IsSampler(), _mesa_lookup_samplerobj(), _mesa_new_sampler_object(), _mesa_reference_sampler_object_(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), _mesa_set_sampler_filters(), _mesa_set_sampler_srgb_decode(), _mesa_set_sampler_wrap(), GLAPIENTRY, and GLuint.
Referenced by _mesa_bind_sampler(), _mesa_BindSamplers(), _mesa_DeleteSamplers(), _mesa_free_texture_data(), and delete_sampler_object_cb().
_mesa_reference_sampler_object_()
void _mesa_reference_sampler_object_ (struct gl_context * ctx, struct gl_sampler_object ** ptr, struct gl_sampler_object * samp)
Handle reference counting.
References _mesa_problem(), delete_sampler_object(), gl_sampler_object::Mutex, and gl_sampler_object::RefCount.
Referenced by _mesa_is_mipmap_filter(), and _mesa_reference_sampler_object().
_mesa_SamplerParameterf()
void GLAPIENTRY _mesa_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameterfv()
void GLAPIENTRY _mesa_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colorf(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameteri()
void GLAPIENTRY _mesa_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameterIiv()
void GLAPIENTRY _mesa_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colori(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameterIuiv()
void GLAPIENTRY _mesa_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colorui(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameteriv()
void GLAPIENTRY _mesa_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INT_TO_FLOAT, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colorf(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_set_sampler_filters()
void _mesa_set_sampler_filters (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum min_filter, GLenum mag_filter)
References flush(), GLuint, gl_sampler_object::MagFilter, and gl_sampler_object::MinFilter.
Referenced by _mesa_reference_sampler_object().
_mesa_set_sampler_srgb_decode()
void _mesa_set_sampler_srgb_decode (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum param)
References flush(), GLuint, and gl_sampler_object::sRGBDecode.
Referenced by _mesa_reference_sampler_object().
_mesa_set_sampler_wrap()
void _mesa_set_sampler_wrap (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum s, GLenum t, GLenum r)
References flush(), validate_texture_wrap_mode(), gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().