Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
samplerobj.c File Reference
Functions for the GL_ARB_sampler_objects extension.
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/enums.h"
#include "main/hash.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/samplerobj.h"
Macros
#define INVALID_PARAM 0x100
#define INVALID_PNAME 0x101
#define INVALID_VALUE 0x102
Functions
struct gl_sampler_object * _mesa_lookup_samplerobj (struct gl_context *ctx, GLuint name)
static struct gl_sampler_object * lookup_samplerobj_locked (struct gl_context *ctx, GLuint name)
static void delete_sampler_object (struct gl_context *ctx, struct gl_sampler_object *sampObj)
void _mesa_reference_sampler_object_ (struct gl_context *ctx, struct gl_sampler_object **ptr, struct gl_sampler_object *samp)
Handle reference counting.
static void _mesa_init_sampler_object (struct gl_sampler_object *sampObj, GLuint name)
Initialize the fields of the given sampler object.
struct gl_sampler_object * _mesa_new_sampler_object (struct gl_context *ctx, GLuint name)
Fallback for ctx->Driver.NewSamplerObject();.
static void create_samplers (struct gl_context *ctx, GLsizei count, GLuint *samplers, const char *caller)
void GLAPIENTRY _mesa_GenSamplers (GLsizei count, GLuint *samplers)
void GLAPIENTRY _mesa_CreateSamplers (GLsizei count, GLuint *samplers)
void GLAPIENTRY _mesa_DeleteSamplers (GLsizei count, const GLuint *samplers)
GLboolean GLAPIENTRY _mesa_IsSampler (GLuint sampler)
void _mesa_bind_sampler (struct gl_context *ctx, GLuint unit, struct gl_sampler_object *sampObj)
void GLAPIENTRY _mesa_BindSampler (GLuint unit, GLuint sampler)
void GLAPIENTRY _mesa_BindSamplers (GLuint first, GLsizei count, const GLuint *samplers)
static GLboolean validate_texture_wrap_mode (struct gl_context *ctx, GLenum wrap)
Check if a coordinate wrap mode is legal.
static void flush (struct gl_context *ctx)
This is called just prior to changing any sampler object state.
void _mesa_set_sampler_wrap (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum s, GLenum t, GLenum r)
static GLuint set_sampler_wrap_s (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_wrap_t (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_wrap_r (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
void _mesa_set_sampler_filters (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum min_filter, GLenum mag_filter)
static GLuint set_sampler_min_filter (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_mag_filter (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_lod_bias (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_border_colorf (struct gl_context *ctx, struct gl_sampler_object *samp, const GLfloat params[4])
static GLuint set_sampler_border_colori (struct gl_context *ctx, struct gl_sampler_object *samp, const GLint params[4])
static GLuint set_sampler_border_colorui (struct gl_context *ctx, struct gl_sampler_object *samp, const GLuint params[4])
static GLuint set_sampler_min_lod (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_max_lod (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_compare_mode (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_compare_func (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_max_anisotropy (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_cube_map_seamless (struct gl_context *ctx, struct gl_sampler_object *samp, GLboolean param)
void _mesa_set_sampler_srgb_decode (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum param)
static GLuint set_sampler_srgb_decode (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum param)
static struct gl_sampler_object * sampler_parameter_error_check (struct gl_context *ctx, GLuint sampler, const char *name)
void GLAPIENTRY _mesa_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
void GLAPIENTRY _mesa_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint *params)
void GLAPIENTRY _mesa_GetSamplerParameteriv (GLuint sampler, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint *params)
void _mesa_init_sampler_object_functions (struct dd_function_table *driver)
Detailed Description
Functions for the GL_ARB_sampler_objects extension.
Author
Brian Paul
Macro Definition Documentation
INVALID_PARAM
#define INVALID_PARAM 0x100
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_mag_filter(), set_sampler_min_filter(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
INVALID_PNAME
#define INVALID_PNAME 0x101
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), set_sampler_cube_map_seamless(), set_sampler_max_anisotropy(), and set_sampler_srgb_decode().
INVALID_VALUE
#define INVALID_VALUE 0x102
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), set_sampler_cube_map_seamless(), set_sampler_max_anisotropy(), and set_sampler_srgb_decode().
Function Documentation
_mesa_bind_sampler()
void _mesa_bind_sampler (struct gl_context * ctx, GLuint unit, struct gl_sampler_object * sampObj)
References _mesa_reference_sampler_object(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GLAPIENTRY, gl_texture_unit::Sampler, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_BindSampler(), and _mesa_reference_sampler_object().
_mesa_BindSampler()
void GLAPIENTRY _mesa_BindSampler (GLuint unit, GLuint sampler)
References _mesa_bind_sampler(), _mesa_error(), _mesa_lookup_samplerobj(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_sampler_object().
_mesa_BindSamplers()
void GLAPIENTRY _mesa_BindSamplers (GLuint first, GLsizei count, const GLuint * samplers)
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_reference_sampler_object(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, lookup_samplerobj_locked(), and gl_sampler_object::Name.
Referenced by _mesa_reference_sampler_object().
_mesa_CreateSamplers()
void GLAPIENTRY _mesa_CreateSamplers (GLsizei count, GLuint * samplers)
References create_samplers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_sampler_object().
_mesa_DeleteSamplers()
void GLAPIENTRY _mesa_DeleteSamplers (GLsizei count, const GLuint * samplers)
References _mesa_error(), _mesa_HashLockMutex(), _mesa_HashRemoveLocked(), _mesa_HashUnlockMutex(), _mesa_reference_sampler_object(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, and lookup_samplerobj_locked().
Referenced by _mesa_reference_sampler_object().
_mesa_GenSamplers()
void GLAPIENTRY _mesa_GenSamplers (GLsizei count, GLuint * samplers)
References create_samplers(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameterfv()
void GLAPIENTRY _mesa_GetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, GET_CURRENT_CONTEXT, GLAPIENTRY, if(), gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameterIiv()
void GLAPIENTRY _mesa_GetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_color_union::i, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameterIuiv()
void GLAPIENTRY _mesa_GetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, GET_CURRENT_CONTEXT, GLuint, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_color_union::ui, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_GetSamplerParameteriv()
void GLAPIENTRY _mesa_GetSamplerParameteriv (GLuint sampler, GLenum pname, GLint * params)
References _mesa_enum_to_string(), _mesa_error(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, FLOAT_TO_INT, GET_CURRENT_CONTEXT, GLAPIENTRY, IROUND(), gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, sampler_parameter_error_check(), gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
_mesa_init_sampler_object()
static void _mesa_init_sampler_object (struct gl_sampler_object * sampObj, GLuint name) static
Initialize the fields of the given sampler object.
References gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_sampler_object::Mutex, gl_sampler_object::Name, gl_sampler_object::RefCount, gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_new_sampler_object().
_mesa_init_sampler_object_functions()
void _mesa_init_sampler_object_functions (struct dd_function_table * driver)
References _mesa_new_sampler_object(), and dd_function_table::NewSamplerObject.
Referenced by _mesa_reference_sampler_object().
_mesa_IsSampler()
GLboolean GLAPIENTRY _mesa_IsSampler (GLuint sampler)
References _mesa_lookup_samplerobj(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and GET_CURRENT_CONTEXT.
Referenced by _mesa_reference_sampler_object().
_mesa_lookup_samplerobj()
struct gl_sampler_object* _mesa_lookup_samplerobj (struct gl_context * ctx, GLuint name)
References _mesa_HashLookup(), gl_shared_state::SamplerObjects, and gl_context::Shared.
Referenced by _mesa_BindSampler(), _mesa_IsSampler(), _mesa_reference_sampler_object(), get_label_pointer(), and sampler_parameter_error_check().
_mesa_new_sampler_object()
struct gl_sampler_object* _mesa_new_sampler_object (struct gl_context * ctx, GLuint name)
Fallback for ctx->Driver.NewSamplerObject();.
References _mesa_init_sampler_object(), and CALLOC_STRUCT.
Referenced by _mesa_init_sampler_object_functions(), and _mesa_reference_sampler_object().
_mesa_reference_sampler_object_()
void _mesa_reference_sampler_object_ (struct gl_context * ctx, struct gl_sampler_object ** ptr, struct gl_sampler_object * samp)
Handle reference counting.
References _mesa_problem(), delete_sampler_object(), gl_sampler_object::Mutex, and gl_sampler_object::RefCount.
Referenced by _mesa_is_mipmap_filter(), and _mesa_reference_sampler_object().
_mesa_SamplerParameterf()
void GLAPIENTRY _mesa_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameterfv()
void GLAPIENTRY _mesa_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colorf(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameteri()
void GLAPIENTRY _mesa_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameterIiv()
void GLAPIENTRY _mesa_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colori(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameterIuiv()
void GLAPIENTRY _mesa_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colorui(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_SamplerParameteriv()
void GLAPIENTRY _mesa_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint * params)
References _mesa_enum_to_string(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, INT_TO_FLOAT, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, sampler_parameter_error_check(), set_sampler_border_colorf(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_reference_sampler_object().
_mesa_set_sampler_filters()
void _mesa_set_sampler_filters (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum min_filter, GLenum mag_filter)
References flush(), GLuint, gl_sampler_object::MagFilter, and gl_sampler_object::MinFilter.
Referenced by _mesa_reference_sampler_object().
_mesa_set_sampler_srgb_decode()
void _mesa_set_sampler_srgb_decode (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum param)
References flush(), GLuint, and gl_sampler_object::sRGBDecode.
Referenced by _mesa_reference_sampler_object().
_mesa_set_sampler_wrap()
void _mesa_set_sampler_wrap (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum s, GLenum t, GLenum r)
References flush(), validate_texture_wrap_mode(), gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_reference_sampler_object().
create_samplers()
static void create_samplers (struct gl_context * ctx, GLsizei count, GLuint * samplers, const char * caller) static
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), gl_context::Driver, GLAPIENTRY, GLuint, MESA_VERBOSE, dd_function_table::NewSamplerObject, gl_shared_state::SamplerObjects, gl_context::Shared, and VERBOSE_API.
Referenced by _mesa_CreateSamplers(), and _mesa_GenSamplers().
delete_sampler_object()
static void delete_sampler_object (struct gl_context * ctx, struct gl_sampler_object * sampObj) static
References gl_sampler_object::Label, and gl_sampler_object::Mutex.
Referenced by _mesa_reference_sampler_object_().
flush()
static void flush (struct gl_context * ctx) inline static
This is called just prior to changing any sampler object state.
References _NEW_TEXTURE_OBJECT, and FLUSH_VERTICES.
Referenced by _mesa_set_sampler_filters(), _mesa_set_sampler_srgb_decode(), _mesa_set_sampler_wrap(), set_sampler_border_colorf(), set_sampler_border_colori(), set_sampler_border_colorui(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
lookup_samplerobj_locked()
static struct gl_sampler_object* lookup_samplerobj_locked (struct gl_context * ctx, GLuint name) static
References _mesa_HashLookupLocked(), gl_shared_state::SamplerObjects, and gl_context::Shared.
Referenced by _mesa_BindSamplers(), and _mesa_DeleteSamplers().
sampler_parameter_error_check()
static struct gl_sampler_object* sampler_parameter_error_check (struct gl_context * ctx, GLuint sampler, const char * name) static
References _mesa_error(), _mesa_lookup_samplerobj(), and GLAPIENTRY.
Referenced by _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_border_colorf()
static GLuint set_sampler_border_colorf (struct gl_context * ctx, struct gl_sampler_object * samp, const GLfloat params[4]) static
References ACOMP, BCOMP, gl_sampler_object::BorderColor, gl_color_union::f, flush(), GCOMP, GLuint, and RCOMP.
Referenced by _mesa_SamplerParameterfv(), and _mesa_SamplerParameteriv().
set_sampler_border_colori()
static GLuint set_sampler_border_colori (struct gl_context * ctx, struct gl_sampler_object * samp, const GLint params[4]) static
References ACOMP, BCOMP, gl_sampler_object::BorderColor, flush(), GCOMP, GLuint, gl_color_union::i, and RCOMP.
Referenced by _mesa_SamplerParameterIiv().
set_sampler_border_colorui()
static GLuint set_sampler_border_colorui (struct gl_context * ctx, struct gl_sampler_object * samp, const GLuint params[4]) static
References ACOMP, BCOMP, gl_sampler_object::BorderColor, flush(), GCOMP, GLuint, RCOMP, and gl_color_union::ui.
Referenced by _mesa_SamplerParameterIuiv().
set_sampler_compare_func()
static GLuint set_sampler_compare_func (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References gl_extensions::ARB_shadow, gl_sampler_object::CompareFunc, gl_context::Extensions, flush(), GLuint, and INVALID_PARAM.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_compare_mode()
static GLuint set_sampler_compare_mode (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References gl_extensions::ARB_shadow, gl_sampler_object::CompareMode, gl_context::Extensions, flush(), GLuint, and INVALID_PARAM.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_cube_map_seamless()
static GLuint set_sampler_cube_map_seamless (struct gl_context * ctx, struct gl_sampler_object * samp, GLboolean param) static
References _mesa_is_desktop_gl(), gl_extensions::AMD_seamless_cubemap_per_texture, gl_sampler_object::CubeMapSeamless, gl_context::Extensions, flush(), INVALID_PNAME, and INVALID_VALUE.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_lod_bias()
static GLuint set_sampler_lod_bias (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References flush(), GLuint, and gl_sampler_object::LodBias.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_mag_filter()
static GLuint set_sampler_mag_filter (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), GLuint, INVALID_PARAM, and gl_sampler_object::MagFilter.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_max_anisotropy()
static GLuint set_sampler_max_anisotropy (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References gl_context::Const, gl_extensions::EXT_texture_filter_anisotropic, gl_context::Extensions, F, flush(), GLuint, INVALID_PNAME, INVALID_VALUE, gl_sampler_object::MaxAnisotropy, and gl_constants::MaxTextureMaxAnisotropy.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_max_lod()
static GLuint set_sampler_max_lod (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References flush(), GLuint, and gl_sampler_object::MaxLod.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_min_filter()
static GLuint set_sampler_min_filter (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), GLuint, INVALID_PARAM, and gl_sampler_object::MinFilter.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_min_lod()
static GLuint set_sampler_min_lod (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References flush(), GLuint, and gl_sampler_object::MinLod.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_srgb_decode()
static GLuint set_sampler_srgb_decode (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum param) static
References gl_extensions::EXT_texture_sRGB_decode, gl_context::Extensions, flush(), INVALID_PNAME, INVALID_VALUE, and gl_sampler_object::sRGBDecode.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_wrap_r()
static GLuint set_sampler_wrap_r (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), INVALID_PARAM, validate_texture_wrap_mode(), and gl_sampler_object::WrapR.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_wrap_s()
static GLuint set_sampler_wrap_s (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), GLuint, INVALID_PARAM, validate_texture_wrap_mode(), and gl_sampler_object::WrapS.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
set_sampler_wrap_t()
static GLuint set_sampler_wrap_t (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), GLuint, INVALID_PARAM, validate_texture_wrap_mode(), and gl_sampler_object::WrapT.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
validate_texture_wrap_mode()
static GLboolean validate_texture_wrap_mode (struct gl_context * ctx, GLenum wrap) static
Check if a coordinate wrap mode is legal.
Returns
GL_TRUE if legal, GL_FALSE otherwise
References gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_texture_mirror_clamp, and gl_context::Extensions.
Referenced by _mesa_set_sampler_wrap(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().