Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
scissor.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
Called via glScissor.
void GLAPIENTRY _mesa_ScissorArrayv (GLuint first, GLsizei count, const GLint *v)
Define count scissor boxes starting at index.
void GLAPIENTRY _mesa_ScissorIndexed (GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_ScissorIndexedv (GLuint index, const GLint *v)
void GLAPIENTRY _mesa_WindowRectanglesEXT (GLenum mode, GLsizei count, const GLint *box)
void _mesa_set_scissor (struct gl_context *ctx, unsigned idx, GLint x, GLint y, GLsizei width, GLsizei height)
Define the scissor box.
void _mesa_init_scissor (struct gl_context *ctx)
Initialize the context's scissor state.
Function Documentation
_mesa_init_scissor()
void _mesa_init_scissor (struct gl_context * ctx)
Initialize the context's scissor state.
Parameters
ctx the GL context.
References gl_scissor_attrib::EnableFlags, MAX_VIEWPORTS, gl_context::Scissor, set_scissor_no_notify(), and gl_scissor_attrib::WindowRectMode.
Referenced by init_attrib_groups().
_mesa_Scissor()
void GLAPIENTRY _mesa_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
Called via glScissor.
References _mesa_debug(), _mesa_error(), GET_CURRENT_CONTEXT, MESA_VERBOSE, set_scissor_no_notify(), and VERBOSE_API.
_mesa_ScissorArrayv()
void GLAPIENTRY _mesa_ScissorArrayv (GLuint first, GLsizei count, const GLint * v)
Define count scissor boxes starting at index.
Parameters
index index of first scissor records to set
count number of scissor records to set
x,y pointer to array of struct gl_scissor_rects
See also
glScissorArrayv().
Verifies the parameters and call set_scissor_no_notify to do the work.
References _mesa_error(), GET_CURRENT_CONTEXT, gl_scissor_rect::Height, set_scissor_no_notify(), gl_scissor_rect::Width, X, and Y.
_mesa_ScissorIndexed()
void GLAPIENTRY _mesa_ScissorIndexed (GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height)
References GLAPIENTRY, and ScissorIndexed().
_mesa_ScissorIndexedv()
void GLAPIENTRY _mesa_ScissorIndexedv (GLuint index, const GLint * v)
References GLAPIENTRY, and ScissorIndexed().
_mesa_set_scissor()
void _mesa_set_scissor (struct gl_context * ctx, unsigned idx, GLint x, GLint y, GLsizei width, GLsizei height)
Define the scissor box.
Parameters
x,y coordinates of the scissor box lower-left corner.
width width of the scissor box.
height height of the scissor box.
See also
glScissor().
Verifies the parameters and updates __struct gl_contextRec::Scissor. On a change flushes the vertices and notifies the driver via the dd_function_table::Scissor callback.
References gl_context::Driver, GLAPIENTRY, dd_function_table::Scissor, and set_scissor_no_notify().
Referenced by _mesa_check_init_viewport(), and _mesa_PopAttrib().
_mesa_WindowRectanglesEXT()
void GLAPIENTRY _mesa_WindowRectanglesEXT (GLenum mode, GLsizei count, const GLint * box)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_SCISSOR, FLUSH_VERTICES, GET_CURRENT_CONTEXT, gl_scissor_rect::Height, MESA_VERBOSE, VERBOSE_API, gl_scissor_rect::Width, gl_scissor_rect::X, and gl_scissor_rect::Y.
Referenced by _mesa_PopAttrib().