Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shaderapi.h File Reference
#include "glheader.h"
Functions
GLbitfield _mesa_get_shader_flags (void)
Return mask of GLSL_x flags by examining the MESA_GLSL env var.
const char * _mesa_get_shader_capture_path (void)
Memoized version of getenv("MESA_SHADER_CAPTURE_PATH").
void _mesa_copy_string (GLchar *dst, GLsizei maxLength, GLsizei *length, const GLchar *src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
void _mesa_use_shader_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Use the named shader program for subsequent rendering.
void _mesa_active_program (struct gl_context *ctx, struct gl_shader_program *shProg, const char *caller)
Use the named shader program for subsequent glUniform calls.
void _mesa_compile_shader (struct gl_context *ctx, struct gl_shader *sh)
Compile a shader.
void _mesa_link_program (struct gl_context *ctx, struct gl_shader_program *sh_prog)
Link a program's shaders.
unsigned _mesa_count_active_attribs (struct gl_shader_program *shProg)
size_t _mesa_longest_attribute_name_length (struct gl_shader_program *shProg)
void _mesa_shader_write_subroutine_indices (struct gl_context *ctx, gl_shader_stage stage)
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB, GLhandleARB)
void GLAPIENTRY _mesa_CompileShader (GLuint)
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB, GLhandleARB)
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB, GLsizei, GLsizei *, GLhandleARB *)
GLint GLAPIENTRY _mesa_GetFragDataLocation (GLuint program, const GLchar *name)
GLint GLAPIENTRY _mesa_GetFragDataIndex (GLuint program, const GLchar *name)
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB, GLsizei, GLsizei *, GLcharARB *)
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB, GLenum, GLfloat *)
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB, GLenum, GLint *)
void GLAPIENTRY _mesa_GetShaderSource (GLuint, GLsizei, GLsizei *, GLchar *)
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
void GLAPIENTRY _mesa_LinkProgram (GLuint programObj)
void GLAPIENTRY _mesa_ShaderSource (GLuint, GLsizei, const GLchar *const *, const GLint *)
Called via glShaderSource() and glShaderSourceARB() API functions.
void GLAPIENTRY _mesa_UseProgram (GLuint)
void GLAPIENTRY _mesa_ValidateProgram (GLuint)
void GLAPIENTRY _mesa_BindAttribLocation (GLuint program, GLuint, const GLchar *)
void GLAPIENTRY _mesa_BindFragDataLocation (GLuint program, GLuint colorNumber, const GLchar *name)
void GLAPIENTRY _mesa_BindFragDataLocationIndexed (GLuint program, GLuint colorNumber, GLuint index, const GLchar *name)
void GLAPIENTRY _mesa_GetActiveAttrib (GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *)
GLint GLAPIENTRY _mesa_GetAttribLocation (GLuint, const GLchar *)
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
GLuint GLAPIENTRY _mesa_CreateShader (GLenum)
GLuint GLAPIENTRY _mesa_CreateProgram (void)
void GLAPIENTRY _mesa_DeleteProgram (GLuint program)
void GLAPIENTRY _mesa_DeleteShader (GLuint shader)
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj)
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint *shaders, GLenum binaryformat, const void *binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, GLvoid *binary)
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid *binary, GLsizei length)
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
void _mesa_use_program (struct gl_context *ctx, gl_shader_stage stage, struct gl_shader_program *shProg, struct gl_program *prog, struct gl_pipeline_object *shTarget)
void _mesa_copy_linked_program_data (const struct gl_shader_program *src, struct gl_linked_shader *dst_sh)
Copy program-specific data generated by linking from the gl_shader_program object to the gl_program object referred to by the gl_linked_shader.
bool _mesa_validate_shader_target (const struct gl_context *ctx, GLenum type)
Confirm that the a shader type is valid and supported by the implementation.
GLuint GLAPIENTRY _mesa_CreateShaderProgramv (GLenum type, GLsizei count, const GLchar *const *strings)
ARB_separate_shader_objects: Compile & Link Program.
const char * _mesa_program_resource_name (struct gl_program_resource *res)
unsigned _mesa_program_resource_array_size (struct gl_program_resource *res)
GLuint _mesa_program_resource_index (struct gl_shader_program *shProg, struct gl_program_resource *res)
struct gl_program_resource * _mesa_program_resource_find_name (struct gl_shader_program *shProg, GLenum programInterface, const char *name, unsigned *array_index)
struct gl_program_resource * _mesa_program_resource_find_index (struct gl_shader_program *shProg, GLenum programInterface, GLuint index)
bool _mesa_get_program_resource_name (struct gl_shader_program *shProg, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name, const char *caller)
unsigned _mesa_program_resource_name_len (struct gl_program_resource *res)
GLint _mesa_program_resource_location (struct gl_shader_program *shProg, GLenum programInterface, const char *name)
GLint _mesa_program_resource_location_index (struct gl_shader_program *shProg, GLenum programInterface, const char *name)
unsigned _mesa_program_resource_prop (struct gl_shader_program *shProg, struct gl_program_resource *res, GLuint index, const GLenum prop, GLint *val, const char *caller)
void _mesa_get_program_resourceiv (struct gl_shader_program *shProg, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params)
void GLAPIENTRY _mesa_PatchParameteri (GLenum pname, GLint value)
For GL_ARB_tessellation_shader.
void GLAPIENTRY _mesa_PatchParameterfv (GLenum pname, const GLfloat *values)
void _mesa_program_init_subroutine_defaults (struct gl_context *ctx, struct gl_program *prog)
GLint GLAPIENTRY _mesa_GetSubroutineUniformLocation (GLuint program, GLenum shadertype, const GLchar *name)
ARB_shader_subroutine.
GLuint GLAPIENTRY _mesa_GetSubroutineIndex (GLuint program, GLenum shadertype, const GLchar *name)
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformiv (GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values)
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name)
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name)
GLvoid GLAPIENTRY _mesa_UniformSubroutinesuiv (GLenum shadertype, GLsizei count, const GLuint *indices)
GLvoid GLAPIENTRY _mesa_GetUniformSubroutineuiv (GLenum shadertype, GLint location, GLuint *params)
GLvoid GLAPIENTRY _mesa_GetProgramStageiv (GLuint program, GLenum shadertype, GLenum pname, GLint *values)
Function Documentation
_mesa_active_program()
void _mesa_active_program (struct gl_context * ctx, struct gl_shader_program * shProg, const char * caller)
Use the named shader program for subsequent glUniform calls.
References _mesa_error(), _mesa_reference_shader_program(), gl_pipeline_object::ActiveProgram, gl_shader_program::data, gl_shader_program_data::LinkStatus, gl_shader_program::Name, and gl_context::Shader.
Referenced by _mesa_use_shader_program().
_mesa_AttachObjectARB()
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB , GLhandleARB)
References attach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_AttachShader()
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
References attach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_BindAttribLocation()
void GLAPIENTRY _mesa_BindAttribLocation (GLuint program, GLuint , const GLchar *)
_mesa_BindFragDataLocation()
void GLAPIENTRY _mesa_BindFragDataLocation (GLuint program, GLuint colorNumber, const GLchar * name)
_mesa_BindFragDataLocationIndexed()
void GLAPIENTRY _mesa_BindFragDataLocationIndexed (GLuint program, GLuint colorNumber, GLuint index, const GLchar * name)
_mesa_compile_shader()
void _mesa_compile_shader (struct gl_context * ctx, struct gl_shader * sh)
Compile a shader.
References _mesa_debug(), _mesa_get_log_file(), _mesa_log(), gl_context::_Shader, compile_failure, gl_shader::CompileStatus, gl_pipeline_object::Flags, GLSL_DUMP, GLSL_DUMP_ON_ERROR, GLSL_LOG, GLSL_REPORT_ERRORS, gl_shader::InfoLog, gl_shader::ir, gl_shader::Name, gl_shader::Source, and gl_shader::Stage.
Referenced by _mesa_CompileShader(), and _mesa_CreateShaderProgramv().
_mesa_CompileShader()
void GLAPIENTRY _mesa_CompileShader (GLuint)
References _mesa_compile_shader(), _mesa_debug(), _mesa_lookup_shader_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, and VERBOSE_API.
_mesa_copy_linked_program_data()
void _mesa_copy_linked_program_data (const struct gl_shader_program * src, struct gl_linked_shader * dst_sh)
Copy program-specific data generated by linking from the gl_shader_program object to the gl_program object referred to by the gl_linked_shader.
This function expects _mesa_reference_program() to have been previously called setting the gl_linked_shaders program reference.
References gl_shader_program::Comp, gl_shader_program::FragDepthLayout, gl_shader_program::Geom, GLAPIENTRY, GLuint, gl_program::info, gl_linked_shader::Program, gl_shader_program::SeparateShader, gl_shader_program::SharedSize, gl_linked_shader::Stage, gl_shader_program::UsesEndPrimitive, gl_shader_program::UsesStreams, and gl_shader_program::VerticesIn.
_mesa_copy_string()
void _mesa_copy_string (GLchar * dst, GLsizei maxLength, GLsizei * length, const GLchar * src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
Parameters
src the strings source
maxLength max chars to copy
length returns number of chars copied
dst the string destination
Referenced by _mesa_GetProgramPipelineInfoLog(), _mesa_GetTransformFeedbackVarying(), get_program_info_log(), get_shader_info_log(), and get_shader_source().
_mesa_count_active_attribs()
unsigned _mesa_count_active_attribs (struct gl_shader_program * shProg)
Referenced by get_programiv().
_mesa_CreateProgram()
GLuint GLAPIENTRY _mesa_CreateProgram (void)
References _mesa_debug(), create_shader_program(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_CreateProgramObjectARB()
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
References create_shader_program(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_CreateShader()
GLuint GLAPIENTRY _mesa_CreateShader (GLenum)
References _mesa_debug(), _mesa_enum_to_string(), create_shader(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_CreateShaderObjectARB()
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
References create_shader(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_CreateShaderProgramv()
GLuint GLAPIENTRY _mesa_CreateShaderProgramv (GLenum type, GLsizei count, const GLchar *const * strings)
ARB_separate_shader_objects: Compile & Link Program.
References _mesa_compile_shader(), _mesa_error(), _mesa_link_program(), _mesa_lookup_shader(), _mesa_lookup_shader_program(), _mesa_ShaderSource(), attach_shader(), create_shader(), create_shader_program(), gl_shader_program::data, delete_shader(), detach_shader(), GET_CURRENT_CONTEXT, get_shaderiv(), GLAPIENTRY, GLuint, gl_shader::InfoLog, gl_shader_program_data::InfoLog, linking_failure, gl_shader_program_data::LinkStatus, and gl_shader_program::SeparateShader.
_mesa_DeleteObjectARB()
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
References _mesa_debug(), delete_shader(), delete_shader_program(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, is_program(), is_shader(), MESA_VERBOSE, and VERBOSE_API.
_mesa_DeleteProgram()
void GLAPIENTRY _mesa_DeleteProgram (GLuint program)
References delete_shader_program(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DeleteShader()
void GLAPIENTRY _mesa_DeleteShader (GLuint shader)
References delete_shader(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DetachObjectARB()
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB , GLhandleARB)
References detach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DetachShader()
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
References detach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_get_program_resource_name()
bool _mesa_get_program_resource_name (struct gl_shader_program * shProg, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei * length, GLchar * name, const char * caller)
Referenced by _mesa_GetActiveSubroutineName(), _mesa_GetActiveSubroutineUniformName(), _mesa_GetActiveUniformBlockName(), _mesa_GetActiveUniformName(), and _mesa_GetProgramResourceName().
_mesa_get_program_resourceiv()
void _mesa_get_program_resourceiv (struct gl_shader_program * shProg, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum * props, GLsizei bufSize, GLsizei * length, GLint * params)
Referenced by _mesa_GetProgramResourceiv().
_mesa_get_shader_capture_path()
const char* _mesa_get_shader_capture_path (void)
Memoized version of getenv("MESA_SHADER_CAPTURE_PATH").
Referenced by _mesa_link_program(), and _mesa_ProgramStringARB().
_mesa_get_shader_flags()
GLbitfield _mesa_get_shader_flags (void)
Return mask of GLSL_x flags by examining the MESA_GLSL env var.
References GLSL_CACHE_INFO, GLSL_DUMP, GLSL_DUMP_ON_ERROR, GLSL_LOG, GLSL_NOP_FRAG, GLSL_NOP_VERT, GLSL_REPORT_ERRORS, GLSL_UNIFORMS, and GLSL_USE_PROG.
Referenced by _mesa_init_shader_state(), and _mesa_new_pipeline_object().
_mesa_GetActiveAttrib()
void GLAPIENTRY _mesa_GetActiveAttrib (GLuint , GLuint , GLsizei , GLsizei * , GLint * , GLenum * , GLchar *)
_mesa_GetActiveSubroutineName()
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei * length, GLchar * name)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetActiveSubroutineUniformiv()
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformiv (GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint * values)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_array_size(), _mesa_program_resource_find_index(), _mesa_program_resource_name(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), gl_program_resource::Data, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_subroutine_function::num_compat_types, gl_linked_shader::Program, gl_program::sh, and gl_subroutine_function::types.
_mesa_GetActiveSubroutineUniformName()
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei * length, GLchar * name)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetAttachedObjectsARB()
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB , GLsizei , GLsizei * , GLhandleARB *)
References get_attached_shaders(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetAttachedShaders()
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj)
References get_attached_shaders(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetAttribLocation()
GLint GLAPIENTRY _mesa_GetAttribLocation (GLuint , const GLchar *)
_mesa_GetFragDataIndex()
GLint GLAPIENTRY _mesa_GetFragDataIndex (GLuint program, const GLchar * name)
_mesa_GetFragDataLocation()
GLint GLAPIENTRY _mesa_GetFragDataLocation (GLuint program, const GLchar * name)
_mesa_GetHandleARB()
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
References GET_CURRENT_CONTEXT, get_handle(), and GLAPIENTRY.
_mesa_GetInfoLogARB()
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB , GLsizei , GLsizei * , GLcharARB *)
References _mesa_error(), GET_CURRENT_CONTEXT, get_program_info_log(), get_shader_info_log(), GLAPIENTRY, is_program(), and is_shader().
_mesa_GetObjectParameterfvARB()
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB , GLenum , GLfloat *)
References _mesa_GetObjectParameterivARB(), and GLAPIENTRY.
_mesa_GetObjectParameterivARB()
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB , GLenum , GLint *)
References _mesa_error(), GET_CURRENT_CONTEXT, get_programiv(), get_shaderiv(), GLAPIENTRY, is_program(), and is_shader().
Referenced by _mesa_GetObjectParameterfvARB().
_mesa_GetProgramBinary()
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, GLvoid * binary)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_shader_program_data::LinkStatus, gl_shader_program::Name, and void.
_mesa_GetProgramInfoLog()
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References GET_CURRENT_CONTEXT, get_program_info_log(), and GLAPIENTRY.
_mesa_GetProgramiv()
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_programiv(), and GLAPIENTRY.
_mesa_GetProgramStageiv()
GLvoid GLAPIENTRY _mesa_GetProgramStageiv (GLuint program, GLenum shadertype, GLenum pname, GLint * values)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_array_size(), _mesa_program_resource_find_index(), _mesa_program_resource_name(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, gl_linked_shader::Program, and gl_program::sh.
_mesa_GetShaderInfoLog()
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References GET_CURRENT_CONTEXT, get_shader_info_log(), and GLAPIENTRY.
_mesa_GetShaderiv()
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_shaderiv(), and GLAPIENTRY.
_mesa_GetShaderPrecisionFormat()
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program_constants::HighFloat, gl_program_constants::HighInt, gl_precision::Precision, gl_precision::RangeMax, and gl_precision::RangeMin.
_mesa_GetShaderSource()
void GLAPIENTRY _mesa_GetShaderSource (GLuint , GLsizei , GLsizei * , GLchar *)
References GET_CURRENT_CONTEXT, get_shader_source(), and GLAPIENTRY.
_mesa_GetSubroutineIndex()
GLuint GLAPIENTRY _mesa_GetSubroutineIndex (GLuint program, GLenum shadertype, const GLchar * name)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_name(), _mesa_program_resource_index(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetSubroutineUniformLocation()
GLint GLAPIENTRY _mesa_GetSubroutineUniformLocation (GLuint program, GLenum shadertype, const GLchar * name)
ARB_shader_subroutine.
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_location(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_GetUniformSubroutineuiv()
GLvoid GLAPIENTRY _mesa_GetUniformSubroutineuiv (GLenum shadertype, GLint location, GLuint * params)
References _mesa_error(), _mesa_shader_enum_to_shader_stage(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program::info, and gl_program::sh.
_mesa_IsProgram()
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and is_program().
_mesa_IsShader()
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and is_shader().
_mesa_link_program()
void _mesa_link_program (struct gl_context * ctx, struct gl_shader_program * sh_prog)
Link a program's shaders.
References gl_shader_program::_LinkedShaders, _mesa_debug(), _mesa_error(), _mesa_get_shader_capture_path(), _mesa_transform_feedback_is_using_program(), _mesa_use_program(), _mesa_warning(), gl_context::_Shader, gl_pipeline_object::CurrentProgram, gl_shader_program::data, gl_pipeline_object::Flags, FLUSH_VERTICES, GLSL_REPORT_ERRORS, GLuint, gl_program::Id, gl_shader_program_data::InfoLog, gl_shader_program::IsES, linking_failure, gl_shader_program_data::LinkStatus, gl_shader::Name, gl_shader_program::Name, gl_shader_program::NumShaders, gl_linked_shader::Program, gl_shader_program::SeparateShader, gl_shader_program::Shaders, gl_shader::Source, gl_shader::Stage, and gl_shader_program_data::Version.
Referenced by _mesa_CreateShaderProgramv(), and _mesa_LinkProgram().
_mesa_LinkProgram()
void GLAPIENTRY _mesa_LinkProgram (GLuint programObj)
References _mesa_debug(), _mesa_link_program(), _mesa_lookup_shader_program_err(), _mesa_warning(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_longest_attribute_name_length()
size_t _mesa_longest_attribute_name_length (struct gl_shader_program * shProg)
Referenced by get_programiv().
_mesa_PatchParameterfv()
void GLAPIENTRY _mesa_PatchParameterfv (GLenum pname, const GLfloat * values)
References _mesa_error(), _mesa_has_tessellation(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_PatchParameteri()
void GLAPIENTRY _mesa_PatchParameteri (GLenum pname, GLint value)
For GL_ARB_tessellation_shader.
References _mesa_error(), _mesa_has_tessellation(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_program_init_subroutine_defaults()
void _mesa_program_init_subroutine_defaults (struct gl_context * ctx, struct gl_program * prog)
References find_compat_subroutine(), GLuint, gl_subroutine_index_binding::IndexPtr, gl_program::info, gl_subroutine_index_binding::NumIndex, gl_program::sh, and gl_context::SubroutineIndex.
Referenced by _mesa_bind_pipeline(), and use_program().
_mesa_program_resource_array_size()
unsigned _mesa_program_resource_array_size (struct gl_program_resource * res)
Referenced by _mesa_GetActiveSubroutineUniformiv(), and _mesa_GetProgramStageiv().
_mesa_program_resource_find_index()
struct gl_program_resource* _mesa_program_resource_find_index (struct gl_shader_program * shProg, GLenum programInterface, GLuint index)
Referenced by _mesa_GetActiveSubroutineUniformiv(), _mesa_GetProgramStageiv(), _mesa_GetTransformFeedbackVarying(), and mesa_bufferiv().
_mesa_program_resource_find_name()
struct gl_program_resource* _mesa_program_resource_find_name (struct gl_shader_program * shProg, GLenum programInterface, const char * name, unsigned * array_index)
Referenced by _mesa_GetProgramInterfaceiv(), _mesa_GetProgramResourceIndex(), _mesa_GetSubroutineIndex(), _mesa_GetUniformBlockIndex(), and _mesa_GetUniformIndices().
_mesa_program_resource_index()
GLuint _mesa_program_resource_index (struct gl_shader_program * shProg, struct gl_program_resource * res)
Referenced by _mesa_GetProgramResourceIndex(), _mesa_GetSubroutineIndex(), _mesa_GetUniformBlockIndex(), and _mesa_GetUniformIndices().
_mesa_program_resource_location()
GLint _mesa_program_resource_location (struct gl_shader_program * shProg, GLenum programInterface, const char * name)
Referenced by _mesa_GetProgramResourceLocation(), _mesa_GetSubroutineUniformLocation(), and _mesa_GetUniformLocation().
_mesa_program_resource_location_index()
GLint _mesa_program_resource_location_index (struct gl_shader_program * shProg, GLenum programInterface, const char * name)
Referenced by _mesa_GetProgramResourceLocationIndex().
_mesa_program_resource_name()
const char* _mesa_program_resource_name (struct gl_program_resource * res)
Referenced by _mesa_GetActiveSubroutineUniformiv(), _mesa_GetProgramStageiv(), and _mesa_GetTransformFeedbackVarying().
_mesa_program_resource_name_len()
unsigned _mesa_program_resource_name_len (struct gl_program_resource * res)
Referenced by _mesa_GetProgramInterfaceiv().
_mesa_program_resource_prop()
unsigned _mesa_program_resource_prop (struct gl_shader_program * shProg, struct gl_program_resource * res, GLuint index, const GLenum prop, GLint * val, const char * caller)
Referenced by _mesa_GetTransformFeedbackVarying(), and mesa_bufferiv().
_mesa_ProgramBinary()
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid * binary, GLsizei length)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, linking_failure, gl_shader_program_data::LinkStatus, and void.
_mesa_ProgramParameteri()
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
References _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::BinaryRetreivableHint, GET_CURRENT_CONTEXT, and gl_shader_program::SeparateShader.
_mesa_ReleaseShaderCompiler()
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References GLAPIENTRY.
_mesa_shader_write_subroutine_indices()
void _mesa_shader_write_subroutine_indices (struct gl_context * ctx, gl_shader_stage stage)
References _mesa_shader_write_subroutine_index(), gl_context::_Shader, and gl_pipeline_object::CurrentProgram.
_mesa_ShaderBinary()
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint * shaders, GLenum binaryformat, const void * binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
_mesa_ShaderSource()
void GLAPIENTRY _mesa_ShaderSource (GLuint shaderObj, GLsizei count, const GLchar *const * string, const GLint * length)
Called via glShaderSource() and glShaderSourceARB() API functions.
Basically, concatenate the source code strings into one long string and pass it to _mesa_shader_source().
References _mesa_error(), _mesa_lookup_shader_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, shader_source(), and gl_shader::Stage.
Referenced by _mesa_CreateShaderProgramv().
_mesa_UniformSubroutinesuiv()
GLvoid GLAPIENTRY _mesa_UniformSubroutinesuiv (GLenum shadertype, GLsizei count, const GLuint * indices)
References _mesa_error(), _mesa_shader_enum_to_shader_stage(), _mesa_validate_shader_target(), _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program::info, gl_subroutine_function::num_compat_types, gl_program::sh, and gl_subroutine_function::types.
_mesa_use_program()
void _mesa_use_program (struct gl_context * ctx, gl_shader_stage stage, struct gl_shader_program * shProg, struct gl_program * prog, struct gl_pipeline_object * shTarget)
References use_program().
Referenced by _mesa_link_program(), and use_program_stage().
_mesa_use_shader_program()
void _mesa_use_shader_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Use the named shader program for subsequent rendering.
References gl_shader_program::_LinkedShaders, _mesa_active_program(), gl_linked_shader::Program, gl_context::Shader, and use_program().
Referenced by _mesa_UseProgram().
_mesa_UseProgram()
void GLAPIENTRY _mesa_UseProgram (GLuint)
References _mesa_BindProgramPipeline(), _mesa_debug(), _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_shader_program_err(), _mesa_reference_pipeline_object(), _mesa_use_shader_program(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, GLSL_USE_PROG, gl_shader_program_data::LinkStatus, MESA_VERBOSE, print_shader_info(), and VERBOSE_API.
_mesa_validate_shader_target()
bool _mesa_validate_shader_target (const struct gl_context * ctx, GLenum type)
Confirm that the a shader type is valid and supported by the implementation.
Parameters
ctx Current GL context
type Shader target
References _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), gl_extensions::ARB_fragment_shader, gl_extensions::ARB_vertex_shader, and gl_context::Extensions.
Referenced by _mesa_GetActiveSubroutineName(), _mesa_GetActiveSubroutineUniformiv(), _mesa_GetActiveSubroutineUniformName(), _mesa_GetProgramStageiv(), _mesa_GetSubroutineIndex(), _mesa_GetSubroutineUniformLocation(), _mesa_GetUniformSubroutineuiv(), _mesa_UniformSubroutinesuiv(), create_shader(), and delete_shader_cb().
_mesa_ValidateProgram()
void GLAPIENTRY _mesa_ValidateProgram (GLuint)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and validate_program().