Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shaderobj.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/hash.h"
#include "main/mtypes.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/uniforms.h"
#include "program/program.h"
#include "program/prog_parameter.h"
#include "util/ralloc.h"
#include "util/string_to_uint_map.h"
#include "util/u_atomic.h"
Functions
void _mesa_reference_shader (struct gl_context *ctx, struct gl_shader **ptr, struct gl_shader *sh)
Set ptr to point to sh.
static void _mesa_init_shader (struct gl_shader *shader)
struct gl_shader * _mesa_new_shader (GLuint name, gl_shader_stage stage)
Allocate a new gl_shader object, initialize it.
void _mesa_delete_shader (struct gl_context *ctx, struct gl_shader *sh)
Delete a shader object.
void _mesa_delete_linked_shader (struct gl_context *ctx, struct gl_linked_shader *sh)
Delete a shader object.
struct gl_shader * _mesa_lookup_shader (struct gl_context *ctx, GLuint name)
Lookup a GLSL shader object.
struct gl_shader * _mesa_lookup_shader_err (struct gl_context *ctx, GLuint name, const char *caller)
As above, but record an error if shader is not found.
void _mesa_reference_shader_program_data (struct gl_context *ctx, struct gl_shader_program_data **ptr, struct gl_shader_program_data *data)
void _mesa_reference_shader_program_ (struct gl_context *ctx, struct gl_shader_program **ptr, struct gl_shader_program *shProg)
Set ptr to point to shProg.
static struct gl_shader_program_data * create_shader_program_data ()
static void init_shader_program (struct gl_shader_program *prog)
struct gl_shader_program * _mesa_new_shader_program (GLuint name)
Allocate a new gl_shader_program object, initialize it.
void _mesa_clear_shader_program_data (struct gl_context *ctx, struct gl_shader_program *shProg)
Clear (free) the shader program state that gets produced by linking.
void _mesa_free_shader_program_data (struct gl_context *ctx, struct gl_shader_program *shProg)
Free all the data that hangs off a shader program object, but not the object itself.
void _mesa_delete_shader_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Free/delete a shader program object.
struct gl_shader_program * _mesa_lookup_shader_program (struct gl_context *ctx, GLuint name)
Lookup a GLSL program object.
struct gl_shader_program * _mesa_lookup_shader_program_err (struct gl_context *ctx, GLuint name, const char *caller)
As above, but record an error if program is not found.
void _mesa_init_shader_object_functions (struct dd_function_table *driver)
Detailed Description
Author
Brian Paul
Function Documentation
_mesa_clear_shader_program_data()
void _mesa_clear_shader_program_data (struct gl_context * ctx, struct gl_shader_program * shProg)
Clear (free) the shader program state that gets produced by linking.
References gl_shader_program::_LinkedShaders, _mesa_delete_linked_shader(), _mesa_uniform_detach_all_driver_storage(), gl_shader_program_data::AtomicBuffers, gl_shader_program_data::cache_fallback, gl_shader_program::data, gl_shader_program_data::InfoLog, gl_shader_program_data::linked_stages, gl_shader_program_data::NumAtomicBuffers, gl_shader_program_data::NumProgramResourceList, gl_shader_program_data::NumShaderStorageBlocks, gl_shader_program_data::NumUniformBlocks, gl_shader_program::NumUniformRemapTable, gl_shader_program_data::NumUniformStorage, gl_shader_program_data::ProgramResourceList, gl_shader_program_data::ShaderStorageBlocks, gl_shader_program_data::UniformBlocks, gl_shader_program::UniformHash, gl_shader_program::UniformRemapTable, and gl_shader_program_data::UniformStorage.
Referenced by _mesa_free_shader_program_data(), and _mesa_reference_shader_program().
_mesa_delete_linked_shader()
void _mesa_delete_linked_shader (struct gl_context * ctx, struct gl_linked_shader * sh)
Delete a shader object.
References gl_linked_shader::Program.
Referenced by _mesa_clear_shader_program_data(), and _mesa_reference_shader_program().
_mesa_delete_shader()
void _mesa_delete_shader (struct gl_context * ctx, struct gl_shader * sh)
Delete a shader object.
References gl_shader::FallbackSource, gl_shader::Label, and gl_shader::Source.
Referenced by _mesa_reference_shader(), _mesa_reference_shader_program(), and delete_shader_cb().
_mesa_delete_shader_program()
void _mesa_delete_shader_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Free/delete a shader program object.
References _mesa_free_shader_program_data(), _mesa_reference_shader_program_data(), gl_shader_program_data::cache_fallback, and gl_shader_program::data.
Referenced by _mesa_reference_shader_program(), _mesa_reference_shader_program_(), and delete_shader_cb().
_mesa_free_shader_program_data()
void _mesa_free_shader_program_data (struct gl_context * ctx, struct gl_shader_program * shProg)
Free all the data that hangs off a shader program object, but not the object itself.
References _mesa_clear_shader_program_data(), _mesa_reference_shader(), gl_shader_program::AttributeBindings, gl_shader_program::FragDataBindings, gl_shader_program::FragDataIndexBindings, GL_SHADER_PROGRAM_MESA, GLuint, gl_shader_program::Label, gl_shader_program::NumShaders, gl_shader_program::NumVarying, gl_shader_program::Shaders, gl_shader_program::TransformFeedback, gl_shader_program::Type, and gl_shader_program::VaryingNames.
Referenced by _mesa_delete_shader_program(), _mesa_reference_shader_program(), and free_shader_program_data_cb().
_mesa_init_shader()
static void _mesa_init_shader (struct gl_shader * shader) static
References gl_shader_info::Geom, gl_shader::info, gl_shader_info::InputType, gl_shader_info::OutputType, gl_shader::RefCount, and gl_shader_info::VerticesOut.
Referenced by _mesa_new_shader().
_mesa_init_shader_object_functions()
void _mesa_init_shader_object_functions (struct dd_function_table * driver)
References dd_function_table::LinkShader.
Referenced by _mesa_reference_shader_program().
_mesa_lookup_shader()
struct gl_shader* _mesa_lookup_shader (struct gl_context * ctx, GLuint name)
Lookup a GLSL shader object.
References _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader::Type.
Referenced by _mesa_CreateShaderProgramv(), get_label_pointer(), and is_shader().
_mesa_lookup_shader_err()
struct gl_shader* _mesa_lookup_shader_err (struct gl_context * ctx, GLuint name, const char * caller)
As above, but record an error if shader is not found.
References _mesa_error(), _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader::Type.
Referenced by _mesa_CompileShader(), _mesa_ShaderSource(), attach_shader(), delete_shader(), get_shader_info_log(), get_shader_source(), and get_shaderiv().
_mesa_lookup_shader_program()
struct gl_shader_program* _mesa_lookup_shader_program (struct gl_context * ctx, GLuint name)
Lookup a GLSL program object.
References _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader_program::Type.
Referenced by _mesa_CreateShaderProgramv(), _mesa_reference_shader_program(), get_label_pointer(), and is_program().
_mesa_lookup_shader_program_err()
struct gl_shader_program* _mesa_lookup_shader_program_err (struct gl_context * ctx, GLuint name, const char * caller)
As above, but record an error if program is not found.
References _mesa_error(), _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader_program::Type.
Referenced by _mesa_ActiveShaderProgram(), _mesa_GetActiveAtomicCounterBufferiv(), _mesa_GetActiveSubroutineName(), _mesa_GetActiveSubroutineUniformiv(), _mesa_GetActiveSubroutineUniformName(), _mesa_GetActiveUniformBlockiv(), _mesa_GetActiveUniformBlockName(), _mesa_GetActiveUniformName(), _mesa_GetProgramBinary(), _mesa_GetProgramInterfaceiv(), _mesa_GetProgramResourceIndex(), _mesa_GetProgramResourceiv(), _mesa_GetProgramResourceName(), _mesa_GetProgramStageiv(), _mesa_GetSubroutineIndex(), _mesa_GetSubroutineUniformLocation(), _mesa_GetTransformFeedbackVarying(), _mesa_GetUniformBlockIndex(), _mesa_GetUniformIndices(), _mesa_GetUniformLocation(), _mesa_LinkProgram(), _mesa_ProgramBinary(), _mesa_ProgramParameteri(), _mesa_ProgramUniform1d(), _mesa_ProgramUniform1dv(), _mesa_ProgramUniform1f(), _mesa_ProgramUniform1fv(), _mesa_ProgramUniform1i(), _mesa_ProgramUniform1i64ARB(), _mesa_ProgramUniform1i64vARB(), _mesa_ProgramUniform1iv(), _mesa_ProgramUniform1ui(), _mesa_ProgramUniform1ui64ARB(), _mesa_ProgramUniform1ui64vARB(), _mesa_ProgramUniform1uiv(), _mesa_ProgramUniform2d(), _mesa_ProgramUniform2dv(), _mesa_ProgramUniform2f(), _mesa_ProgramUniform2fv(), _mesa_ProgramUniform2i(), _mesa_ProgramUniform2i64ARB(), _mesa_ProgramUniform2i64vARB(), _mesa_ProgramUniform2iv(), _mesa_ProgramUniform2ui(), _mesa_ProgramUniform2ui64ARB(), _mesa_ProgramUniform2ui64vARB(), _mesa_ProgramUniform2uiv(), _mesa_ProgramUniform3d(), _mesa_ProgramUniform3dv(), _mesa_ProgramUniform3f(), _mesa_ProgramUniform3fv(), _mesa_ProgramUniform3i(), _mesa_ProgramUniform3i64ARB(), _mesa_ProgramUniform3i64vARB(), _mesa_ProgramUniform3iv(), _mesa_ProgramUniform3ui(), _mesa_ProgramUniform3ui64ARB(), _mesa_ProgramUniform3ui64vARB(), _mesa_ProgramUniform3uiv(), _mesa_ProgramUniform4d(), _mesa_ProgramUniform4dv(), _mesa_ProgramUniform4f(), _mesa_ProgramUniform4fv(), _mesa_ProgramUniform4i(), _mesa_ProgramUniform4i64ARB(), _mesa_ProgramUniform4i64vARB(), _mesa_ProgramUniform4iv(), _mesa_ProgramUniform4ui(), _mesa_ProgramUniform4ui64ARB(), _mesa_ProgramUniform4ui64vARB(), _mesa_ProgramUniform4uiv(), _mesa_ProgramUniformMatrix2dv(), _mesa_ProgramUniformMatrix2fv(), _mesa_ProgramUniformMatrix2x3dv(), _mesa_ProgramUniformMatrix2x3fv(), _mesa_ProgramUniformMatrix2x4dv(), _mesa_ProgramUniformMatrix2x4fv(), _mesa_ProgramUniformMatrix3dv(), _mesa_ProgramUniformMatrix3fv(), _mesa_ProgramUniformMatrix3x2dv(), _mesa_ProgramUniformMatrix3x2fv(), _mesa_ProgramUniformMatrix3x4dv(), _mesa_ProgramUniformMatrix3x4fv(), _mesa_ProgramUniformMatrix4dv(), _mesa_ProgramUniformMatrix4fv(), _mesa_ProgramUniformMatrix4x2dv(), _mesa_ProgramUniformMatrix4x2fv(), _mesa_ProgramUniformMatrix4x3dv(), _mesa_ProgramUniformMatrix4x3fv(), _mesa_reference_shader_program(), _mesa_ShaderStorageBlockBinding(), _mesa_TransformFeedbackVaryings(), _mesa_UniformBlockBinding(), _mesa_UseProgram(), _mesa_UseProgramStages(), attach_shader(), delete_shader_program(), detach_shader(), get_attached_shaders(), get_program_info_log(), get_programiv(), lookup_linked_program(), and validate_program().
_mesa_new_shader()
struct gl_shader* _mesa_new_shader (GLuint name, gl_shader_stage stage)
Allocate a new gl_shader object, initialize it.
References _mesa_init_shader(), gl_shader::Name, and gl_shader::Stage.
Referenced by _mesa_reference_shader_program(), and create_shader().
_mesa_new_shader_program()
struct gl_shader_program* _mesa_new_shader_program (GLuint name)
Allocate a new gl_shader_program object, initialize it.
References create_shader_program_data(), gl_shader_program::data, init_shader_program(), and gl_shader_program::Name.
Referenced by _mesa_reference_shader_program(), and create_shader_program().
_mesa_reference_shader()
void _mesa_reference_shader (struct gl_context * ctx, struct gl_shader ** ptr, struct gl_shader * sh)
Set ptr to point to sh.
If ptr is pointing to another shader, decrement its refcount (and delete if refcount hits zero). Then set ptr to point to sh, incrementing its refcount.
References _mesa_delete_shader(), _mesa_HashRemove(), gl_shader::Name, gl_shader::RefCount, gl_shared_state::ShaderObjects, and gl_context::Shared.
Referenced by _mesa_free_shader_program_data(), attach_shader(), delete_shader(), and detach_shader().
_mesa_reference_shader_program_()
void _mesa_reference_shader_program_ (struct gl_context * ctx, struct gl_shader_program ** ptr, struct gl_shader_program * shProg)
Set ptr to point to shProg.
If ptr is pointing to another object, decrement its refcount (and delete if refcount hits zero). Then set ptr to point to shProg, incrementing its refcount.
References _mesa_delete_shader_program(), _mesa_HashRemove(), gl_shader_program::Name, gl_shader_program::RefCount, gl_shared_state::ShaderObjects, and gl_context::Shared.
Referenced by _mesa_reference_shader_program().
_mesa_reference_shader_program_data()
void _mesa_reference_shader_program_data (struct gl_context * ctx, struct gl_shader_program_data ** ptr, struct gl_shader_program_data * data)
References gl_shader_program_data::RefCount.
Referenced by _mesa_delete_shader_program().
create_shader_program_data()
static struct gl_shader_program_data* create_shader_program_data () static
References gl_shader_program_data::RefCount.
Referenced by _mesa_new_shader_program().
init_shader_program()
static void init_shader_program (struct gl_shader_program * prog) static
References gl_shader_program::AttributeBindings, gl_shader_program::BufferMode, gl_shader_program::data, gl_shader_program::EmptyUniformLocations, gl_shader_program::FragDataBindings, gl_shader_program::FragDataIndexBindings, gl_shader_program::Geom, GL_SHADER_PROGRAM_MESA, gl_shader_program_data::InfoLog, gl_shader_program::RefCount, gl_shader_program::TransformFeedback, gl_shader_program::Type, gl_shader_program::UsesEndPrimitive, and gl_shader_program::UsesStreams.
Referenced by _mesa_new_shader_program().