Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shaderimage.c File Reference
#include <assert.h>
#include "shaderimage.h"
#include "mtypes.h"
#include "formats.h"
#include "errors.h"
#include "hash.h"
#include "context.h"
#include "texobj.h"
#include "teximage.h"
#include "enums.h"
Macros
#define MESA_FORMAT_RGBA_8 MESA_FORMAT_R8G8B8A8_UNORM
#define MESA_FORMAT_RG_16 MESA_FORMAT_R16G16_UNORM
#define MESA_FORMAT_RG_8 MESA_FORMAT_R8G8_UNORM
#define MESA_FORMAT_SIGNED_RGBA_8 MESA_FORMAT_R8G8B8A8_SNORM
#define MESA_FORMAT_SIGNED_RG_16 MESA_FORMAT_R16G16_SNORM
#define MESA_FORMAT_SIGNED_RG_8 MESA_FORMAT_R8G8_SNORM
Enumerations
enum image_format_class {
IMAGE_FORMAT_CLASS_NONE = 0, IMAGE_FORMAT_CLASS_1X8, IMAGE_FORMAT_CLASS_1X16, IMAGE_FORMAT_CLASS_1X32,
IMAGE_FORMAT_CLASS_2X8, IMAGE_FORMAT_CLASS_2X16, IMAGE_FORMAT_CLASS_2X32, IMAGE_FORMAT_CLASS_10_11_11,
IMAGE_FORMAT_CLASS_4X8, IMAGE_FORMAT_CLASS_4X16, IMAGE_FORMAT_CLASS_4X32, IMAGE_FORMAT_CLASS_2_10_10_10
}
Functions
mesa_format _mesa_get_shader_image_format (GLenum format)
Get the matching mesa_format for a shader image format GL enum.
static enum image_format_class get_image_format_class (mesa_format format)
static GLenum _image_format_class_to_glenum (enum image_format_class class)
GLenum _mesa_get_image_format_class (GLenum format)
Get the GL image format class for a shader image format GL enum.
bool _mesa_is_shader_image_format_supported (const struct gl_context *ctx, GLenum format)
Return whether an image format should be supported based on the current API version of the context.
struct gl_image_unit _mesa_default_image_unit (struct gl_context *ctx)
Get a single image unit struct with the default state.
void _mesa_init_image_units (struct gl_context *ctx)
Initialize a context's shader image units to the default state.
GLboolean _mesa_is_image_unit_valid (struct gl_context *ctx, struct gl_image_unit *u)
Return GL_TRUE if the state of the image unit passed as argument is valid and access from the shader is allowed.
static GLboolean validate_bind_image_texture (struct gl_context *ctx, GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format)
void GLAPIENTRY _mesa_BindImageTexture (GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format)
void GLAPIENTRY _mesa_BindImageTextures (GLuint first, GLsizei count, const GLuint *textures)
Macro Definition Documentation
MESA_FORMAT_RG_16
#define MESA_FORMAT_RG_16 MESA_FORMAT_R16G16_UNORM
Referenced by _mesa_get_shader_image_format(), and get_image_format_class().
MESA_FORMAT_RG_8
#define MESA_FORMAT_RG_8 MESA_FORMAT_R8G8_UNORM
Referenced by _mesa_get_shader_image_format(), and get_image_format_class().
MESA_FORMAT_RGBA_8
#define MESA_FORMAT_RGBA_8 MESA_FORMAT_R8G8B8A8_UNORM
Referenced by _mesa_get_shader_image_format(), and get_image_format_class().
MESA_FORMAT_SIGNED_RG_16
#define MESA_FORMAT_SIGNED_RG_16 MESA_FORMAT_R16G16_SNORM
Referenced by _mesa_get_shader_image_format(), and get_image_format_class().
MESA_FORMAT_SIGNED_RG_8
#define MESA_FORMAT_SIGNED_RG_8 MESA_FORMAT_R8G8_SNORM
Referenced by _mesa_get_shader_image_format(), and get_image_format_class().
MESA_FORMAT_SIGNED_RGBA_8
#define MESA_FORMAT_SIGNED_RGBA_8 MESA_FORMAT_R8G8B8A8_SNORM
Referenced by _mesa_get_shader_image_format(), and get_image_format_class().
Enumeration Type Documentation
image_format_class
enum image_format_class
Enumerator
IMAGE_FORMAT_CLASS_NONE
Not a valid image format.
IMAGE_FORMAT_CLASS_1X8
Classes of image formats you can cast into each other.
IMAGE_FORMAT_CLASS_1X16
IMAGE_FORMAT_CLASS_1X32
IMAGE_FORMAT_CLASS_2X8
IMAGE_FORMAT_CLASS_2X16
IMAGE_FORMAT_CLASS_2X32
IMAGE_FORMAT_CLASS_10_11_11
IMAGE_FORMAT_CLASS_4X8
IMAGE_FORMAT_CLASS_4X16
IMAGE_FORMAT_CLASS_4X32
IMAGE_FORMAT_CLASS_2_10_10_10
Function Documentation
_image_format_class_to_glenum()
static GLenum _image_format_class_to_glenum (enum image_format_class class) static
References IMAGE_FORMAT_CLASS_10_11_11, IMAGE_FORMAT_CLASS_1X16, IMAGE_FORMAT_CLASS_1X32, IMAGE_FORMAT_CLASS_1X8, IMAGE_FORMAT_CLASS_2_10_10_10, IMAGE_FORMAT_CLASS_2X16, IMAGE_FORMAT_CLASS_2X32, IMAGE_FORMAT_CLASS_2X8, IMAGE_FORMAT_CLASS_4X16, IMAGE_FORMAT_CLASS_4X32, IMAGE_FORMAT_CLASS_4X8, and IMAGE_FORMAT_CLASS_NONE.
Referenced by _mesa_get_image_format_class().
_mesa_BindImageTexture()
void GLAPIENTRY _mesa_BindImageTexture (GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format)
References gl_image_unit::_ActualFormat, gl_image_unit::_Layer, _mesa_error(), _mesa_get_shader_image_format(), _mesa_is_gles(), _mesa_lookup_texture(), _mesa_reference_texobj(), _mesa_tex_target_is_layered(), gl_image_unit::Access, FLUSH_VERTICES, gl_image_unit::Format, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Immutable, gl_image_unit::Layer, gl_image_unit::Layered, gl_image_unit::Level, gl_texture_object::Target, gl_image_unit::TexObj, and validate_bind_image_texture().
_mesa_BindImageTextures()
void GLAPIENTRY _mesa_BindImageTextures (GLuint first, GLsizei count, const GLuint * textures)
References gl_image_unit::_ActualFormat, gl_image_unit::_Layer, _mesa_enum_to_string(), _mesa_error(), _mesa_get_shader_image_format(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_is_shader_image_format_supported(), _mesa_lookup_texture_locked(), _mesa_reference_texobj(), _mesa_tex_target_is_layered(), gl_image_unit::Access, gl_texture_object::BufferObjectFormat, gl_texture_image::Depth, FLUSH_VERTICES, gl_image_unit::Format, GET_CURRENT_CONTEXT, GLuint, gl_texture_image::Height, gl_texture_object::Image, gl_texture_image::InternalFormat, gl_image_unit::Layer, gl_image_unit::Layered, gl_image_unit::Level, MESA_FORMAT_R_UNORM8, gl_texture_object::Name, gl_texture_object::Target, gl_image_unit::TexObj, and gl_texture_image::Width.
_mesa_default_image_unit()
struct gl_image_unit _mesa_default_image_unit (struct gl_context * ctx)
Get a single image unit struct with the default state.
References _mesa_get_shader_image_format(), _mesa_is_desktop_gl(), and gl_image_unit::Access.
Referenced by _mesa_init_image_units(), and unbind_texobj_from_image_units().
_mesa_get_image_format_class()
GLenum _mesa_get_image_format_class (GLenum format)
Get the GL image format class for a shader image format GL enum.
References _image_format_class_to_glenum(), _mesa_get_shader_image_format(), and MESA_FORMAT_NONE.
Referenced by _mesa_GetInternalformativ().
_mesa_get_shader_image_format()
mesa_format _mesa_get_shader_image_format (GLenum format)
Get the matching mesa_format for a shader image format GL enum.
References MESA_FORMAT_NONE, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_SNORM16, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_16, MESA_FORMAT_RG_8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGBA_8, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBA_UNORM16, MESA_FORMAT_SIGNED_RG_16, MESA_FORMAT_SIGNED_RG_8, and MESA_FORMAT_SIGNED_RGBA_8.
Referenced by _mesa_BindImageTexture(), _mesa_BindImageTextures(), _mesa_default_image_unit(), _mesa_get_image_format_class(), _mesa_GetInternalformativ(), and _mesa_is_image_unit_valid().
_mesa_init_image_units()
void _mesa_init_image_units (struct gl_context * ctx)
Initialize a context's shader image units to the default state.
References _mesa_default_image_unit(), and gl_context::ImageUnits.
Referenced by init_attrib_groups().
_mesa_is_image_unit_valid()
GLboolean _mesa_is_image_unit_valid (struct gl_context * ctx, struct gl_image_unit * u)
Return GL_TRUE if the state of the image unit passed as argument is valid and access from the shader is allowed.
Otherwise loads from this unit should return zero and stores should have no effect.
The result depends on context state other than the passed image unit, part of the _NEW_TEXTURE_OBJECT set.
References gl_image_unit::_ActualFormat, gl_texture_object::_BaseComplete, gl_image_unit::_Layer, gl_texture_object::_MaxLevel, _mesa_get_format_bytes(), _mesa_get_shader_image_format(), _mesa_get_texture_layers(), _mesa_test_texobj_completeness(), _mesa_tex_target_is_layered(), gl_texture_object::_MipmapComplete, gl_texture_object::BaseLevel, gl_texture_image::Border, gl_texture_object::BufferObjectFormat, gl_context::Const, get_image_format_class(), gl_texture_object::Image, gl_texture_object::ImageFormatCompatibilityType, gl_texture_image::InternalFormat, gl_image_unit::Level, gl_constants::MaxImageSamples, gl_texture_image::NumSamples, gl_texture_object::Target, and gl_image_unit::TexObj.
_mesa_is_shader_image_format_supported()
bool _mesa_is_shader_image_format_supported (const struct gl_context * ctx, GLenum format)
Return whether an image format should be supported based on the current API version of the context.
References _mesa_is_desktop_gl().
Referenced by _mesa_BindImageTextures(), _mesa_GetInternalformativ(), and validate_bind_image_texture().
get_image_format_class()
static enum image_format_class get_image_format_class (mesa_format format) static
References IMAGE_FORMAT_CLASS_10_11_11, IMAGE_FORMAT_CLASS_1X16, IMAGE_FORMAT_CLASS_1X32, IMAGE_FORMAT_CLASS_1X8, IMAGE_FORMAT_CLASS_2_10_10_10, IMAGE_FORMAT_CLASS_2X16, IMAGE_FORMAT_CLASS_2X32, IMAGE_FORMAT_CLASS_2X8, IMAGE_FORMAT_CLASS_4X16, IMAGE_FORMAT_CLASS_4X32, IMAGE_FORMAT_CLASS_4X8, IMAGE_FORMAT_CLASS_NONE, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_SNORM16, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_16, MESA_FORMAT_RG_8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGBA_8, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBA_UNORM16, MESA_FORMAT_SIGNED_RG_16, MESA_FORMAT_SIGNED_RG_8, and MESA_FORMAT_SIGNED_RGBA_8.
Referenced by _mesa_is_image_unit_valid().
validate_bind_image_texture()
static GLboolean validate_bind_image_texture (struct gl_context * ctx, GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format) static
References _mesa_error(), _mesa_is_shader_image_format_supported(), gl_context::Const, GLAPIENTRY, MAX_IMAGE_UNITS, and gl_constants::MaxImageUnits.
Referenced by _mesa_BindImageTexture().