Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shaderapi.c File Reference
#include <stdbool.h>
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/enums.h"
#include "main/hash.h"
#include "main/mtypes.h"
#include "main/pipelineobj.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/transformfeedback.h"
#include "main/uniforms.h"
#include "compiler/glsl/glsl_parser_extras.h"
#include "compiler/glsl/ir.h"
#include "compiler/glsl/ir_uniform.h"
#include "compiler/glsl/program.h"
#include "program/program.h"
#include "program/prog_print.h"
#include "program/prog_parameter.h"
#include "util/ralloc.h"
#include "util/hash_table.h"
#include "util/mesa-sha1.h"
#include "util/crc32.h"
Functions
GLbitfield _mesa_get_shader_flags (void)
Return mask of GLSL_x flags by examining the MESA_GLSL env var.
const char * _mesa_get_shader_capture_path (void)
Memoized version of getenv("MESA_SHADER_CAPTURE_PATH").
void _mesa_init_shader_state (struct gl_context *ctx)
Initialize context's shader state.
void _mesa_free_shader_state (struct gl_context *ctx)
Free the per-context shader-related state.
void _mesa_copy_string (GLchar *dst, GLsizei maxLength, GLsizei *length, const GLchar *src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
bool _mesa_validate_shader_target (const struct gl_context *ctx, GLenum type)
Confirm that the a shader type is valid and supported by the implementation.
static GLboolean is_program (struct gl_context *ctx, GLuint name)
static GLboolean is_shader (struct gl_context *ctx, GLuint name)
static void attach_shader (struct gl_context *ctx, GLuint program, GLuint shader)
Attach shader to a shader program.
static GLuint create_shader (struct gl_context *ctx, GLenum type)
static GLuint create_shader_program (struct gl_context *ctx)
static void delete_shader_program (struct gl_context *ctx, GLuint name)
Delete a shader program.
static void delete_shader (struct gl_context *ctx, GLuint shader)
static void detach_shader (struct gl_context *ctx, GLuint program, GLuint shader)
static void get_attached_shaders (struct gl_context *ctx, GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj)
Return list of shaders attached to shader program.
static GLuint get_handle (struct gl_context *ctx, GLenum pname)
glGetHandleARB() - return ID/name of currently bound shader program.
static bool check_gs_query (struct gl_context *ctx, const struct gl_shader_program *shProg)
Check if a geometry shader query is valid at this time.
static bool check_tcs_query (struct gl_context *ctx, const struct gl_shader_program *shProg)
Check if a tessellation control shader query is valid at this time.
static bool check_tes_query (struct gl_context *ctx, const struct gl_shader_program *shProg)
Check if a tessellation evaluation shader query is valid at this time.
static void get_programiv (struct gl_context *ctx, GLuint program, GLenum pname, GLint *params)
glGetProgramiv() - get shader program state.
static void get_shaderiv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
glGetShaderiv() - get GLSL shader state
static void get_program_info_log (struct gl_context *ctx, GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
static void get_shader_info_log (struct gl_context *ctx, GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
static void get_shader_source (struct gl_context *ctx, GLuint shader, GLsizei maxLength, GLsizei *length, GLchar *sourceOut)
Return shader source code.
static void shader_source (struct gl_shader *sh, const GLchar *source)
Set/replace shader source code.
void _mesa_compile_shader (struct gl_context *ctx, struct gl_shader *sh)
Compile a shader.
void _mesa_link_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Link a program's shaders.
static void print_shader_info (const struct gl_shader_program *shProg)
Print basic shader info (for debug).
void _mesa_active_program (struct gl_context *ctx, struct gl_shader_program *shProg, const char *caller)
Use the named shader program for subsequent glUniform calls.
static void use_program (struct gl_context *ctx, gl_shader_stage stage, struct gl_shader_program *shProg, struct gl_program *new_prog, struct gl_pipeline_object *shTarget)
void _mesa_use_shader_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Use the named shader program for subsequent rendering.
static GLboolean validate_shader_program (const struct gl_shader_program *shProg, char *errMsg)
Do validation of the given shader program.
static void validate_program (struct gl_context *ctx, GLuint program)
Called via glValidateProgram()
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB program, GLhandleARB shader)
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
void GLAPIENTRY _mesa_CompileShader (GLuint shaderObj)
GLuint GLAPIENTRY _mesa_CreateShader (GLenum type)
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
GLuint GLAPIENTRY _mesa_CreateProgram (void)
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
void GLAPIENTRY _mesa_DeleteProgram (GLuint name)
void GLAPIENTRY _mesa_DeleteShader (GLuint name)
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB program, GLhandleARB shader)
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB container, GLsizei maxCount, GLsizei *count, GLhandleARB *obj)
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj)
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB object, GLsizei maxLength, GLsizei *length, GLcharARB *infoLog)
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB object, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB object, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderSource (GLuint shader, GLsizei maxLength, GLsizei *length, GLchar *sourceOut)
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
void GLAPIENTRY _mesa_LinkProgram (GLuint programObj)
void GLAPIENTRY _mesa_ShaderSource (GLuint shaderObj, GLsizei count, const GLchar *const *string, const GLint *length)
Called via glShaderSource() and glShaderSourceARB() API functions.
void GLAPIENTRY _mesa_UseProgram (GLuint program)
void GLAPIENTRY _mesa_ValidateProgram (GLuint program)
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint *shaders, GLenum binaryformat, const void *binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, GLvoid *binary)
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid *binary, GLsizei length)
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
void _mesa_use_program (struct gl_context *ctx, gl_shader_stage stage, struct gl_shader_program *shProg, struct gl_program *prog, struct gl_pipeline_object *shTarget)
void _mesa_copy_linked_program_data (const struct gl_shader_program *src, struct gl_linked_shader *dst_sh)
Copy program-specific data generated by linking from the gl_shader_program object to the gl_program object referred to by the gl_linked_shader.
GLuint GLAPIENTRY _mesa_CreateShaderProgramv (GLenum type, GLsizei count, const GLchar *const *strings)
ARB_separate_shader_objects: Compile & Link Program.
void GLAPIENTRY _mesa_PatchParameteri (GLenum pname, GLint value)
For GL_ARB_tessellation_shader.
void GLAPIENTRY _mesa_PatchParameterfv (GLenum pname, const GLfloat *values)
GLint GLAPIENTRY _mesa_GetSubroutineUniformLocation (GLuint program, GLenum shadertype, const GLchar *name)
ARB_shader_subroutine.
GLuint GLAPIENTRY _mesa_GetSubroutineIndex (GLuint program, GLenum shadertype, const GLchar *name)
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformiv (GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values)
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name)
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei *length, GLchar *name)
GLvoid GLAPIENTRY _mesa_UniformSubroutinesuiv (GLenum shadertype, GLsizei count, const GLuint *indices)
GLvoid GLAPIENTRY _mesa_GetUniformSubroutineuiv (GLenum shadertype, GLint location, GLuint *params)
GLvoid GLAPIENTRY _mesa_GetProgramStageiv (GLuint program, GLenum shadertype, GLenum pname, GLint *values)
static int find_compat_subroutine (struct gl_program *p, const struct glsl_type *type)
static void _mesa_shader_write_subroutine_index (struct gl_context *ctx, struct gl_program *p)
void _mesa_shader_write_subroutine_indices (struct gl_context *ctx, gl_shader_stage stage)
void _mesa_program_init_subroutine_defaults (struct gl_context *ctx, struct gl_program *p)
Detailed Description
Author
Brian Paul
Implementation of GLSL-related API functions. The glUniform* functions are in uniforms.c
XXX things to do:
Check that the right error code is generated for all _mesa_error() calls.
Insert FLUSH_VERTICES calls in various places
Function Documentation
_mesa_active_program()
void _mesa_active_program (struct gl_context * ctx, struct gl_shader_program * shProg, const char * caller)
Use the named shader program for subsequent glUniform calls.
References _mesa_error(), _mesa_reference_shader_program(), gl_pipeline_object::ActiveProgram, gl_shader_program::data, gl_shader_program_data::LinkStatus, gl_shader_program::Name, and gl_context::Shader.
Referenced by _mesa_use_shader_program().
_mesa_AttachObjectARB()
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB program, GLhandleARB shader)
References attach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_AttachShader()
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
References attach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_compile_shader()
void _mesa_compile_shader (struct gl_context * ctx, struct gl_shader * sh)
Compile a shader.
References _mesa_debug(), _mesa_get_log_file(), _mesa_log(), gl_context::_Shader, compile_failure, gl_shader::CompileStatus, gl_pipeline_object::Flags, GLSL_DUMP, GLSL_DUMP_ON_ERROR, GLSL_LOG, GLSL_REPORT_ERRORS, gl_shader::InfoLog, gl_shader::ir, gl_shader::Name, gl_shader::Source, and gl_shader::Stage.
Referenced by _mesa_CompileShader(), and _mesa_CreateShaderProgramv().
_mesa_CompileShader()
void GLAPIENTRY _mesa_CompileShader (GLuint shaderObj)
References _mesa_compile_shader(), _mesa_debug(), _mesa_lookup_shader_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, and VERBOSE_API.
_mesa_copy_linked_program_data()
void _mesa_copy_linked_program_data (const struct gl_shader_program * src, struct gl_linked_shader * dst_sh)
Copy program-specific data generated by linking from the gl_shader_program object to the gl_program object referred to by the gl_linked_shader.
This function expects _mesa_reference_program() to have been previously called setting the gl_linked_shaders program reference.
References gl_shader_program::Comp, gl_shader_program::FragDepthLayout, gl_shader_program::Geom, GLAPIENTRY, GLuint, gl_program::info, gl_linked_shader::Program, gl_shader_program::SeparateShader, gl_shader_program::SharedSize, gl_linked_shader::Stage, gl_shader_program::UsesEndPrimitive, gl_shader_program::UsesStreams, and gl_shader_program::VerticesIn.
_mesa_copy_string()
void _mesa_copy_string (GLchar * dst, GLsizei maxLength, GLsizei * length, const GLchar * src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
Parameters
src the strings source
maxLength max chars to copy
length returns number of chars copied
dst the string destination
Referenced by _mesa_GetProgramPipelineInfoLog(), _mesa_GetTransformFeedbackVarying(), get_program_info_log(), get_shader_info_log(), and get_shader_source().
_mesa_CreateProgram()
GLuint GLAPIENTRY _mesa_CreateProgram (void)
References _mesa_debug(), create_shader_program(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_CreateProgramObjectARB()
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
References create_shader_program(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_CreateShader()
GLuint GLAPIENTRY _mesa_CreateShader (GLenum type)
References _mesa_debug(), _mesa_enum_to_string(), create_shader(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_CreateShaderObjectARB()
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
References create_shader(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_CreateShaderProgramv()
GLuint GLAPIENTRY _mesa_CreateShaderProgramv (GLenum type, GLsizei count, const GLchar *const * strings)
ARB_separate_shader_objects: Compile & Link Program.
References _mesa_compile_shader(), _mesa_error(), _mesa_link_program(), _mesa_lookup_shader(), _mesa_lookup_shader_program(), _mesa_ShaderSource(), attach_shader(), create_shader(), create_shader_program(), gl_shader_program::data, delete_shader(), detach_shader(), GET_CURRENT_CONTEXT, get_shaderiv(), GLAPIENTRY, GLuint, gl_shader::InfoLog, gl_shader_program_data::InfoLog, linking_failure, gl_shader_program_data::LinkStatus, and gl_shader_program::SeparateShader.
_mesa_DeleteObjectARB()
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
References _mesa_debug(), delete_shader(), delete_shader_program(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, is_program(), is_shader(), MESA_VERBOSE, and VERBOSE_API.
_mesa_DeleteProgram()
void GLAPIENTRY _mesa_DeleteProgram (GLuint name)
References delete_shader_program(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DeleteShader()
void GLAPIENTRY _mesa_DeleteShader (GLuint name)
References delete_shader(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DetachObjectARB()
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB program, GLhandleARB shader)
References detach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DetachShader()
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
References detach_shader(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_free_shader_state()
void _mesa_free_shader_state (struct gl_context * ctx)
Free the per-context shader-related state.
References gl_pipeline_object::_CurrentFragmentProgram, _mesa_reference_pipeline_object(), _mesa_reference_shader_program(), gl_context::_Shader, gl_pipeline_object::ActiveProgram, gl_pipeline_object::CurrentProgram, gl_pipeline_object::Mutex, gl_pipeline_object::RefCount, and gl_context::Shader.
Referenced by _mesa_free_context_data().
_mesa_get_shader_capture_path()
const char* _mesa_get_shader_capture_path (void)
Memoized version of getenv("MESA_SHADER_CAPTURE_PATH").
Referenced by _mesa_link_program(), and _mesa_ProgramStringARB().
_mesa_get_shader_flags()
GLbitfield _mesa_get_shader_flags (void)
Return mask of GLSL_x flags by examining the MESA_GLSL env var.
References GLSL_CACHE_INFO, GLSL_DUMP, GLSL_DUMP_ON_ERROR, GLSL_LOG, GLSL_NOP_FRAG, GLSL_NOP_VERT, GLSL_REPORT_ERRORS, GLSL_UNIFORMS, and GLSL_USE_PROG.
Referenced by _mesa_init_shader_state(), and _mesa_new_pipeline_object().
_mesa_GetActiveSubroutineName()
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei * length, GLchar * name)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetActiveSubroutineUniformiv()
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformiv (GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint * values)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_array_size(), _mesa_program_resource_find_index(), _mesa_program_resource_name(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), gl_program_resource::Data, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_subroutine_function::num_compat_types, gl_linked_shader::Program, gl_program::sh, and gl_subroutine_function::types.
_mesa_GetActiveSubroutineUniformName()
GLvoid GLAPIENTRY _mesa_GetActiveSubroutineUniformName (GLuint program, GLenum shadertype, GLuint index, GLsizei bufsize, GLsizei * length, GLchar * name)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetAttachedObjectsARB()
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB container, GLsizei maxCount, GLsizei * count, GLhandleARB * obj)
References get_attached_shaders(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetAttachedShaders()
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj)
References get_attached_shaders(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetHandleARB()
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
References GET_CURRENT_CONTEXT, get_handle(), and GLAPIENTRY.
_mesa_GetInfoLogARB()
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB object, GLsizei maxLength, GLsizei * length, GLcharARB * infoLog)
References _mesa_error(), GET_CURRENT_CONTEXT, get_program_info_log(), get_shader_info_log(), GLAPIENTRY, is_program(), and is_shader().
_mesa_GetObjectParameterfvARB()
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB object, GLenum pname, GLfloat * params)
References _mesa_GetObjectParameterivARB(), and GLAPIENTRY.
_mesa_GetObjectParameterivARB()
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB object, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_programiv(), get_shaderiv(), GLAPIENTRY, is_program(), and is_shader().
Referenced by _mesa_GetObjectParameterfvARB().
_mesa_GetProgramBinary()
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, GLvoid * binary)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_shader_program_data::LinkStatus, gl_shader_program::Name, and void.
_mesa_GetProgramInfoLog()
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References GET_CURRENT_CONTEXT, get_program_info_log(), and GLAPIENTRY.
_mesa_GetProgramiv()
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_programiv(), and GLAPIENTRY.
_mesa_GetProgramStageiv()
GLvoid GLAPIENTRY _mesa_GetProgramStageiv (GLuint program, GLenum shadertype, GLenum pname, GLint * values)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_array_size(), _mesa_program_resource_find_index(), _mesa_program_resource_name(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, gl_linked_shader::Program, and gl_program::sh.
_mesa_GetShaderInfoLog()
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References GET_CURRENT_CONTEXT, get_shader_info_log(), and GLAPIENTRY.
_mesa_GetShaderiv()
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_shaderiv(), and GLAPIENTRY.
_mesa_GetShaderPrecisionFormat()
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program_constants::HighFloat, gl_program_constants::HighInt, gl_precision::Precision, gl_precision::RangeMax, and gl_precision::RangeMin.
_mesa_GetShaderSource()
void GLAPIENTRY _mesa_GetShaderSource (GLuint shader, GLsizei maxLength, GLsizei * length, GLchar * sourceOut)
References GET_CURRENT_CONTEXT, get_shader_source(), and GLAPIENTRY.
_mesa_GetSubroutineIndex()
GLuint GLAPIENTRY _mesa_GetSubroutineIndex (GLuint program, GLenum shadertype, const GLchar * name)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_name(), _mesa_program_resource_index(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetSubroutineUniformLocation()
GLint GLAPIENTRY _mesa_GetSubroutineUniformLocation (GLuint program, GLenum shadertype, const GLchar * name)
ARB_shader_subroutine.
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_location(), _mesa_shader_enum_to_shader_stage(), _mesa_shader_stage_to_subroutine_uniform(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_GetUniformSubroutineuiv()
GLvoid GLAPIENTRY _mesa_GetUniformSubroutineuiv (GLenum shadertype, GLint location, GLuint * params)
References _mesa_error(), _mesa_shader_enum_to_shader_stage(), _mesa_validate_shader_target(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program::info, and gl_program::sh.
_mesa_init_shader_state()
void _mesa_init_shader_state (struct gl_context * ctx)
Initialize context's shader state.
Internal functions.
References _mesa_get_shader_flags(), gl_context::Const, gl_pipeline_object::Flags, for(), gl_constants::GenerateTemporaryNames, gl_shader_compiler_options::MaxIfDepth, gl_shader_compiler_options::MaxUnrollIterations, gl_pipeline_object::Mutex, gl_tess_ctrl_program_state::patch_default_inner_level, gl_tess_ctrl_program_state::patch_default_outer_level, gl_tess_ctrl_program_state::patch_vertices, gl_pipeline_object::RefCount, gl_context::Shader, gl_constants::ShaderCompilerOptions, and gl_context::TessCtrlProgram.
Referenced by init_attrib_groups().
_mesa_IsProgram()
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and is_program().
_mesa_IsShader()
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and is_shader().
_mesa_link_program()
void _mesa_link_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Link a program's shaders.
References gl_shader_program::_LinkedShaders, _mesa_debug(), _mesa_error(), _mesa_get_shader_capture_path(), _mesa_transform_feedback_is_using_program(), _mesa_use_program(), _mesa_warning(), gl_context::_Shader, gl_pipeline_object::CurrentProgram, gl_shader_program::data, gl_pipeline_object::Flags, FLUSH_VERTICES, GLSL_REPORT_ERRORS, GLuint, gl_program::Id, gl_shader_program_data::InfoLog, gl_shader_program::IsES, linking_failure, gl_shader_program_data::LinkStatus, gl_shader::Name, gl_shader_program::Name, gl_shader_program::NumShaders, gl_linked_shader::Program, gl_shader_program::SeparateShader, gl_shader_program::Shaders, gl_shader::Source, gl_shader::Stage, and gl_shader_program_data::Version.
Referenced by _mesa_CreateShaderProgramv(), and _mesa_LinkProgram().
_mesa_LinkProgram()
void GLAPIENTRY _mesa_LinkProgram (GLuint programObj)
References _mesa_debug(), _mesa_link_program(), _mesa_lookup_shader_program_err(), _mesa_warning(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_PatchParameterfv()
void GLAPIENTRY _mesa_PatchParameterfv (GLenum pname, const GLfloat * values)
References _mesa_error(), _mesa_has_tessellation(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_PatchParameteri()
void GLAPIENTRY _mesa_PatchParameteri (GLenum pname, GLint value)
For GL_ARB_tessellation_shader.
References _mesa_error(), _mesa_has_tessellation(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_program_init_subroutine_defaults()
void _mesa_program_init_subroutine_defaults (struct gl_context * ctx, struct gl_program * p)
References find_compat_subroutine(), GLuint, gl_subroutine_index_binding::IndexPtr, gl_program::info, gl_subroutine_index_binding::NumIndex, gl_program::sh, and gl_context::SubroutineIndex.
Referenced by _mesa_bind_pipeline(), and use_program().
_mesa_ProgramBinary()
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid * binary, GLsizei length)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, linking_failure, gl_shader_program_data::LinkStatus, and void.
_mesa_ProgramParameteri()
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
References _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::BinaryRetreivableHint, GET_CURRENT_CONTEXT, and gl_shader_program::SeparateShader.
_mesa_ReleaseShaderCompiler()
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References GLAPIENTRY.
_mesa_shader_write_subroutine_index()
static void _mesa_shader_write_subroutine_index (struct gl_context * ctx, struct gl_program * p) static
References _mesa_propagate_uniforms_to_driver_storage(), gl_subroutine_index_binding::IndexPtr, gl_program::info, gl_program::sh, and gl_context::SubroutineIndex.
Referenced by _mesa_shader_write_subroutine_indices().
_mesa_shader_write_subroutine_indices()
void _mesa_shader_write_subroutine_indices (struct gl_context * ctx, gl_shader_stage stage)
References _mesa_shader_write_subroutine_index(), gl_context::_Shader, and gl_pipeline_object::CurrentProgram.
_mesa_ShaderBinary()
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint * shaders, GLenum binaryformat, const void * binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
_mesa_ShaderSource()
void GLAPIENTRY _mesa_ShaderSource (GLuint shaderObj, GLsizei count, const GLchar *const * string, const GLint * length)
Called via glShaderSource() and glShaderSourceARB() API functions.
Basically, concatenate the source code strings into one long string and pass it to _mesa_shader_source().
References _mesa_error(), _mesa_lookup_shader_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, shader_source(), and gl_shader::Stage.
Referenced by _mesa_CreateShaderProgramv().
_mesa_UniformSubroutinesuiv()
GLvoid GLAPIENTRY _mesa_UniformSubroutinesuiv (GLenum shadertype, GLsizei count, const GLuint * indices)
References _mesa_error(), _mesa_shader_enum_to_shader_stage(), _mesa_validate_shader_target(), _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_program::info, gl_subroutine_function::num_compat_types, gl_program::sh, and gl_subroutine_function::types.
_mesa_use_program()
void _mesa_use_program (struct gl_context * ctx, gl_shader_stage stage, struct gl_shader_program * shProg, struct gl_program * prog, struct gl_pipeline_object * shTarget)
References use_program().
Referenced by _mesa_link_program(), and use_program_stage().
_mesa_use_shader_program()
void _mesa_use_shader_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Use the named shader program for subsequent rendering.
References gl_shader_program::_LinkedShaders, _mesa_active_program(), gl_linked_shader::Program, gl_context::Shader, and use_program().
Referenced by _mesa_UseProgram().
_mesa_UseProgram()
void GLAPIENTRY _mesa_UseProgram (GLuint program)
References _mesa_BindProgramPipeline(), _mesa_debug(), _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_shader_program_err(), _mesa_reference_pipeline_object(), _mesa_use_shader_program(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, GLSL_USE_PROG, gl_shader_program_data::LinkStatus, MESA_VERBOSE, print_shader_info(), and VERBOSE_API.
_mesa_validate_shader_target()
bool _mesa_validate_shader_target (const struct gl_context * ctx, GLenum type)
Confirm that the a shader type is valid and supported by the implementation.
Parameters
ctx Current GL context
type Shader target
References _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), gl_extensions::ARB_fragment_shader, gl_extensions::ARB_vertex_shader, and gl_context::Extensions.
Referenced by _mesa_GetActiveSubroutineName(), _mesa_GetActiveSubroutineUniformiv(), _mesa_GetActiveSubroutineUniformName(), _mesa_GetProgramStageiv(), _mesa_GetSubroutineIndex(), _mesa_GetSubroutineUniformLocation(), _mesa_GetUniformSubroutineuiv(), _mesa_UniformSubroutinesuiv(), create_shader(), and delete_shader_cb().
_mesa_ValidateProgram()
void GLAPIENTRY _mesa_ValidateProgram (GLuint program)
References GET_CURRENT_CONTEXT, GLAPIENTRY, and validate_program().
attach_shader()
static void attach_shader (struct gl_context * ctx, GLuint program, GLuint shader) static
Attach shader to a shader program.
References _mesa_error(), _mesa_is_gles(), _mesa_lookup_shader_err(), _mesa_lookup_shader_program_err(), _mesa_reference_shader(), GLuint, gl_shader_program::NumShaders, gl_shader_program::Shaders, and gl_shader::Stage.
Referenced by _mesa_AttachObjectARB(), _mesa_AttachShader(), and _mesa_CreateShaderProgramv().
check_gs_query()
static bool check_gs_query (struct gl_context * ctx, const struct gl_shader_program * shProg) static
Check if a geometry shader query is valid at this time.
If not, report an error and return false.
From GL 3.2 section 6.1.16 (Shader and Program Queries):
"If GEOMETRY_VERTICES_OUT, GEOMETRY_INPUT_TYPE, or GEOMETRY_OUTPUT_TYPE
are queried for a program which has not been linked successfully, or
which does not contain objects to form a geometry shader, then an
INVALID_OPERATION error is generated."
References gl_shader_program::_LinkedShaders, _mesa_error(), gl_shader_program::data, and gl_shader_program_data::LinkStatus.
Referenced by get_programiv().
check_tcs_query()
static bool check_tcs_query (struct gl_context * ctx, const struct gl_shader_program * shProg) static
Check if a tessellation control shader query is valid at this time.
If not, report an error and return false.
From GL 4.0 section 6.1.12 (Shader and Program Queries):
"If TESS_CONTROL_OUTPUT_VERTICES is queried for a program which has
not been linked successfully, or which does not contain objects to
form a tessellation control shader, then an INVALID_OPERATION error is
generated."
References gl_shader_program::_LinkedShaders, _mesa_error(), gl_shader_program::data, and gl_shader_program_data::LinkStatus.
Referenced by get_programiv().
check_tes_query()
static bool check_tes_query (struct gl_context * ctx, const struct gl_shader_program * shProg) static
Check if a tessellation evaluation shader query is valid at this time.
If not, report an error and return false.
From GL 4.0 section 6.1.12 (Shader and Program Queries):
"If any of the pname values in this paragraph are queried for a program
which has not been linked successfully, or which does not contain
objects to form a tessellation evaluation shader, then an
INVALID_OPERATION error is generated."
References gl_shader_program::_LinkedShaders, _mesa_error(), gl_shader_program::data, and gl_shader_program_data::LinkStatus.
Referenced by get_programiv().
create_shader()
static GLuint create_shader (struct gl_context * ctx, GLenum type) static
References _mesa_enum_to_string(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_new_shader(), _mesa_shader_enum_to_shader_stage(), _mesa_validate_shader_target(), GLuint, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader::Type.
Referenced by _mesa_CreateShader(), _mesa_CreateShaderObjectARB(), and _mesa_CreateShaderProgramv().
create_shader_program()
static GLuint create_shader_program (struct gl_context * ctx) static
References _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_new_shader_program(), GLuint, gl_shader_program::RefCount, gl_shared_state::ShaderObjects, and gl_context::Shared.
Referenced by _mesa_CreateProgram(), _mesa_CreateProgramObjectARB(), and _mesa_CreateShaderProgramv().
delete_shader()
static void delete_shader (struct gl_context * ctx, GLuint shader) static
References _mesa_lookup_shader_err(), _mesa_reference_shader(), and gl_shader::DeletePending.
Referenced by _mesa_CreateShaderProgramv(), _mesa_DeleteObjectARB(), and _mesa_DeleteShader().
delete_shader_program()
static void delete_shader_program (struct gl_context * ctx, GLuint name) static
Delete a shader program.
Actually, just decrement the program's reference count and mark it as DeletePending. Used to implement glDeleteProgram() and glDeleteObjectARB().
References _mesa_lookup_shader_program_err(), _mesa_reference_shader_program(), and gl_shader_program::DeletePending.
Referenced by _mesa_DeleteObjectARB(), and _mesa_DeleteProgram().
detach_shader()
static void detach_shader (struct gl_context * ctx, GLuint program, GLuint shader) static
References _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_reference_shader(), GLuint, is_program(), is_shader(), gl_shader::Name, gl_shader_program::NumShaders, gl_shader::RefCount, gl_shader_program::Shaders, and gl_shader::Stage.
Referenced by _mesa_CreateShaderProgramv(), _mesa_DetachObjectARB(), and _mesa_DetachShader().
find_compat_subroutine()
static int find_compat_subroutine (struct gl_program * p, const struct glsl_type * type) static
References gl_subroutine_function::num_compat_types, gl_program::sh, and gl_subroutine_function::types.
Referenced by _mesa_program_init_subroutine_defaults().
get_attached_shaders()
static void get_attached_shaders (struct gl_context * ctx, GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj) static
Return list of shaders attached to shader program.
References _mesa_error(), _mesa_lookup_shader_program_err(), GLuint, gl_shader::Name, gl_shader_program::NumShaders, and gl_shader_program::Shaders.
Referenced by _mesa_GetAttachedObjectsARB(), and _mesa_GetAttachedShaders().
get_handle()
static GLuint get_handle (struct gl_context * ctx, GLenum pname) static
glGetHandleARB() - return ID/name of currently bound shader program.
References _mesa_error(), gl_context::_Shader, gl_pipeline_object::ActiveProgram, and gl_shader_program::Name.
Referenced by _mesa_GetHandleARB().
get_program_info_log()
static void get_program_info_log (struct gl_context * ctx, GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog) static
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::data, and gl_shader_program_data::InfoLog.
Referenced by _mesa_GetInfoLogARB(), and _mesa_GetProgramInfoLog().
get_programiv()
static void get_programiv (struct gl_context * ctx, GLuint program, GLenum pname, GLint * params) static
glGetProgramiv() - get shader program state.
Note that this is for GLSL shader programs, not ARB vertex/fragment programs (see glGetProgramivARB).
References gl_shader_program::_LinkedShaders, _mesa_count_active_attribs(), _mesa_enum_to_string(), _mesa_error(), _mesa_has_compute_shaders(), _mesa_has_geometry_shaders(), _mesa_has_tessellation(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_longest_attribute_name_length(), _mesa_lookup_shader_program_err(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, gl_extensions::ARB_gpu_shader5, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_uniform_buffer_object, gl_shader_program::BinaryRetreivableHint, gl_shader_program::BufferMode, check_gs_query(), check_tcs_query(), check_tes_query(), gl_shader_program::data, gl_shader_program::DeletePending, gl_extensions::EXT_transform_feedback, gl_context::Extensions, if(), gl_program::info, gl_shader_program_data::InfoLog, linking_failure, gl_shader_program_data::LinkStatus, gl_uniform_block::Name, gl_shader_program_data::NumAtomicBuffers, gl_shader_program_data::NumHiddenUniforms, gl_shader_program::NumShaders, gl_shader_program_data::NumUniformBlocks, gl_shader_program_data::NumUniformStorage, gl_shader_program::NumVarying, gl_linked_shader::Program, gl_shader_program::SeparateShader, gl_shader_program::TransformFeedback, gl_shader_program_data::UniformBlocks, gl_shader_program_data::UniformStorage, gl_shader_program_data::Validated, and gl_shader_program::VaryingNames.
Referenced by _mesa_GetObjectParameterivARB(), and _mesa_GetProgramiv().
get_shader_info_log()
static void get_shader_info_log (struct gl_context * ctx, GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog) static
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_err(), and gl_shader::InfoLog.
Referenced by _mesa_GetInfoLogARB(), and _mesa_GetShaderInfoLog().
get_shader_source()
static void get_shader_source (struct gl_context * ctx, GLuint shader, GLsizei maxLength, GLsizei * length, GLchar * sourceOut) static
Return shader source code.
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_err(), and gl_shader::Source.
Referenced by _mesa_GetShaderSource().
get_shaderiv()
static void get_shaderiv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
glGetShaderiv() - get GLSL shader state
References _mesa_error(), _mesa_lookup_shader_err(), gl_shader::CompileStatus, gl_shader::DeletePending, gl_shader::InfoLog, gl_shader::Source, and gl_shader::Type.
Referenced by _mesa_CreateShaderProgramv(), _mesa_GetObjectParameterivARB(), and _mesa_GetShaderiv().
is_program()
static GLboolean is_program (struct gl_context * ctx, GLuint name) static
References _mesa_lookup_shader_program().
Referenced by _mesa_DeleteObjectARB(), _mesa_GetInfoLogARB(), _mesa_GetObjectParameterivARB(), _mesa_IsProgram(), and detach_shader().
is_shader()
static GLboolean is_shader (struct gl_context * ctx, GLuint name) static
References _mesa_lookup_shader().
Referenced by _mesa_DeleteObjectARB(), _mesa_GetInfoLogARB(), _mesa_GetObjectParameterivARB(), _mesa_IsShader(), and detach_shader().
print_shader_info()
static void print_shader_info (const struct gl_shader_program * shProg) static
Print basic shader info (for debug).
References gl_shader_program::_LinkedShaders, GLuint, gl_program::Id, gl_shader::Name, gl_shader_program::Name, gl_shader_program::NumShaders, gl_linked_shader::Program, gl_shader_program::Shaders, and gl_shader::Stage.
Referenced by _mesa_UseProgram().
shader_source()
static void shader_source (struct gl_shader * sh, const GLchar * source) static
Set/replace shader source code.
A helper function used by glShaderSource[ARB].
References compile_skipped, gl_shader::CompileStatus, gl_shader::FallbackSource, and gl_shader::Source.
Referenced by _mesa_ShaderSource().
use_program()
static void use_program (struct gl_context * ctx, gl_shader_stage stage, struct gl_shader_program * shProg, struct gl_program * new_prog, struct gl_pipeline_object * shTarget) static
References gl_pipeline_object::_CurrentFragmentProgram, _mesa_program_init_subroutine_defaults(), _mesa_reference_shader_program(), _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, gl_context::_Shader, gl_pipeline_object::CurrentProgram, FLUSH_VERTICES, and gl_pipeline_object::ReferencedPrograms.
Referenced by _mesa_use_program(), and _mesa_use_shader_program().
validate_program()
static void validate_program (struct gl_context * ctx, GLuint program) static
Called via glValidateProgram()
References _mesa_lookup_shader_program_err(), gl_shader_program::data, GLAPIENTRY, gl_shader_program_data::InfoLog, validate_shader_program(), and gl_shader_program_data::Validated.
Referenced by _mesa_ValidateProgram().
validate_shader_program()
static GLboolean validate_shader_program (const struct gl_shader_program * shProg, char * errMsg) static
Do validation of the given shader program.
Parameters
errMsg returns error message if validation fails.
Returns
GL_TRUE if valid, GL_FALSE if invalid (and set errMsg)
References _mesa_sampler_uniforms_are_valid(), gl_shader_program::data, and gl_shader_program_data::LinkStatus.
Referenced by validate_program().