Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shared.h File Reference
Functions
void _mesa_reference_shared_state (struct gl_context *ctx, struct gl_shared_state **ptr, struct gl_shared_state *state)
gl_shared_state objects are ref counted.
struct gl_shared_state * _mesa_alloc_shared_state (struct gl_context *ctx)
Allocate and initialize a shared context state structure.
Function Documentation
_mesa_alloc_shared_state()
struct gl_shared_state* _mesa_alloc_shared_state (struct gl_context * ctx)
Allocate and initialize a shared context state structure.
Initializes the display list, texture objects and vertex programs hash tables, allocates the texture objects. If it runs out of memory, frees everything already allocated before returning NULL.
Returns
pointer to a gl_shared_state structure on success, or NULL on failure.
References _mesa_new_ati_fragment_shader(), _mesa_NewHashTable(), gl_shared_state::ATIShaders, gl_shared_state::BitmapAtlas, gl_shared_state::BufferObjects, CALLOC_STRUCT, gl_shared_state::DefaultFragmentProgram, gl_shared_state::DefaultFragmentShader, gl_shared_state::DefaultTex, gl_shared_state::DefaultVertexProgram, gl_shared_state::DisplayList, gl_context::Driver, gl_shared_state::FrameBuffers, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_shared_state::Mutex, dd_function_table::NewBufferObject, dd_function_table::NewProgram, dd_function_table::NewTextureObject, gl_shared_state::NullBufferObj, NUM_TEXTURE_TARGETS, gl_shared_state::Programs, gl_texture_object::RefCount, gl_shared_state::RenderBuffers, gl_shared_state::SamplerObjects, gl_shared_state::ShaderObjects, gl_shared_state::SyncObjects, gl_texture_object::TargetIndex, gl_shared_state::TexMutex, gl_shared_state::TexObjects, TEXTURE_1D_INDEX, and gl_shared_state::TextureStateStamp.
Referenced by _mesa_initialize_context().
_mesa_reference_shared_state()
void _mesa_reference_shared_state (struct gl_context * ctx, struct gl_shared_state ** ptr, struct gl_shared_state * state)
gl_shared_state objects are ref counted.
If ptr's refcount goes to zero, free the shared state.
References free_shared_state(), gl_shared_state::Mutex, and gl_shared_state::RefCount.
Referenced by _mesa_free_attrib_data(), _mesa_free_context_data(), _mesa_initialize_context(), _mesa_PushAttrib(), _mesa_share_state(), and pop_texture_group().