Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shared.c File Reference
Shared-context state.
#include "imports.h"
#include "mtypes.h"
#include "hash.h"
#include "atifragshader.h"
#include "bufferobj.h"
#include "shared.h"
#include "program/program.h"
#include "dlist.h"
#include "samplerobj.h"
#include "shaderapi.h"
#include "shaderobj.h"
#include "syncobj.h"
#include "util/hash_table.h"
#include "util/set.h"
Functions
struct gl_shared_state * _mesa_alloc_shared_state (struct gl_context *ctx)
Allocate and initialize a shared context state structure.
static void delete_displaylist_cb (GLuint id, void *data, void *userData)
Callback for deleting a display list.
static void delete_bitmap_atlas_cb (GLuint id, void *data, void *userData)
Callback for deleting a bitmap atlas.
static void delete_texture_cb (GLuint id, void *data, void *userData)
Callback for deleting a texture object.
static void delete_program_cb (GLuint id, void *data, void *userData)
Callback for deleting a program object.
static void delete_fragshader_cb (GLuint id, void *data, void *userData)
Callback for deleting an ATI fragment shader object.
static void delete_bufferobj_cb (GLuint id, void *data, void *userData)
Callback for deleting a buffer object.
static void free_shader_program_data_cb (GLuint id, void *data, void *userData)
Callback for freeing shader program data.
static void delete_shader_cb (GLuint id, void *data, void *userData)
Callback for deleting shader and shader programs objects.
static void delete_framebuffer_cb (GLuint id, void *data, void *userData)
Callback for deleting a framebuffer object.
static void delete_renderbuffer_cb (GLuint id, void *data, void *userData)
Callback for deleting a renderbuffer object.
static void delete_sampler_object_cb (GLuint id, void *data, void *userData)
Callback for deleting a sampler object.
static void free_shared_state (struct gl_context *ctx, struct gl_shared_state *shared)
Deallocate a shared state object and all children structures.
void _mesa_reference_shared_state (struct gl_context *ctx, struct gl_shared_state **ptr, struct gl_shared_state *state)
gl_shared_state objects are ref counted.
Detailed Description
Shared-context state.
Function Documentation
_mesa_alloc_shared_state()
struct gl_shared_state* _mesa_alloc_shared_state (struct gl_context * ctx)
Allocate and initialize a shared context state structure.
Initializes the display list, texture objects and vertex programs hash tables, allocates the texture objects. If it runs out of memory, frees everything already allocated before returning NULL.
Returns
pointer to a gl_shared_state structure on success, or NULL on failure.
References _mesa_new_ati_fragment_shader(), _mesa_NewHashTable(), gl_shared_state::ATIShaders, gl_shared_state::BitmapAtlas, gl_shared_state::BufferObjects, CALLOC_STRUCT, gl_shared_state::DefaultFragmentProgram, gl_shared_state::DefaultFragmentShader, gl_shared_state::DefaultTex, gl_shared_state::DefaultVertexProgram, gl_shared_state::DisplayList, gl_context::Driver, gl_shared_state::FrameBuffers, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_shared_state::Mutex, dd_function_table::NewBufferObject, dd_function_table::NewProgram, dd_function_table::NewTextureObject, gl_shared_state::NullBufferObj, NUM_TEXTURE_TARGETS, gl_shared_state::Programs, gl_texture_object::RefCount, gl_shared_state::RenderBuffers, gl_shared_state::SamplerObjects, gl_shared_state::ShaderObjects, gl_shared_state::SyncObjects, gl_texture_object::TargetIndex, gl_shared_state::TexMutex, gl_shared_state::TexObjects, TEXTURE_1D_INDEX, and gl_shared_state::TextureStateStamp.
Referenced by _mesa_initialize_context().
_mesa_reference_shared_state()
void _mesa_reference_shared_state (struct gl_context * ctx, struct gl_shared_state ** ptr, struct gl_shared_state * state)
gl_shared_state objects are ref counted.
If ptr's refcount goes to zero, free the shared state.
References free_shared_state(), gl_shared_state::Mutex, and gl_shared_state::RefCount.
Referenced by _mesa_free_attrib_data(), _mesa_free_context_data(), _mesa_initialize_context(), _mesa_PushAttrib(), _mesa_share_state(), and pop_texture_group().
delete_bitmap_atlas_cb()
static void delete_bitmap_atlas_cb (GLuint id, void * data, void * userData) static
Callback for deleting a bitmap atlas.
Called by _mesa_HashDeleteAll().
References _mesa_delete_bitmap_atlas().
Referenced by free_shared_state().
delete_bufferobj_cb()
static void delete_bufferobj_cb (GLuint id, void * data, void * userData) static
Callback for deleting a buffer object.
Called by _mesa_HashDeleteAll().
References _mesa_buffer_unmap_all_mappings(), and _mesa_reference_buffer_object().
Referenced by free_shared_state().
delete_displaylist_cb()
static void delete_displaylist_cb (GLuint id, void * data, void * userData) static
Callback for deleting a display list.
Called by _mesa_HashDeleteAll().
References _mesa_delete_list().
Referenced by free_shared_state().
delete_fragshader_cb()
static void delete_fragshader_cb (GLuint id, void * data, void * userData) static
Callback for deleting an ATI fragment shader object.
Called by _mesa_HashDeleteAll().
References _mesa_delete_ati_fragment_shader().
Referenced by free_shared_state().
delete_framebuffer_cb()
static void delete_framebuffer_cb (GLuint id, void * data, void * userData) static
Callback for deleting a framebuffer object.
Called by _mesa_HashDeleteAll()
References gl_framebuffer::Delete, and gl_framebuffer::RefCount.
Referenced by free_shared_state().
delete_program_cb()
static void delete_program_cb (GLuint id, void * data, void * userData) static
Callback for deleting a program object.
Called by _mesa_HashDeleteAll().
References dd_function_table::DeleteProgram, gl_context::Driver, and gl_program::RefCount.
Referenced by free_shared_state().
delete_renderbuffer_cb()
static void delete_renderbuffer_cb (GLuint id, void * data, void * userData) static
Callback for deleting a renderbuffer object.
Called by _mesa_HashDeleteAll()
References gl_renderbuffer::Delete, and gl_renderbuffer::RefCount.
Referenced by free_shared_state().
delete_sampler_object_cb()
static void delete_sampler_object_cb (GLuint id, void * data, void * userData) static
Callback for deleting a sampler object.
Called by _mesa_HashDeleteAll()
References _mesa_reference_sampler_object().
Referenced by free_shared_state().
delete_shader_cb()
static void delete_shader_cb (GLuint id, void * data, void * userData) static
Callback for deleting shader and shader programs objects.
Called by _mesa_HashDeleteAll().
References _mesa_delete_shader(), _mesa_delete_shader_program(), _mesa_validate_shader_target(), GL_SHADER_PROGRAM_MESA, gl_shader::Type, and gl_shader_program::Type.
Referenced by free_shared_state().
delete_texture_cb()
static void delete_texture_cb (GLuint id, void * data, void * userData) static
Callback for deleting a texture object.
Called by _mesa_HashDeleteAll().
References dd_function_table::DeleteTexture, and gl_context::Driver.
Referenced by free_shared_state().
free_shader_program_data_cb()
static void free_shader_program_data_cb (GLuint id, void * data, void * userData) static
Callback for freeing shader program data.
Call it before delete_shader_cb to avoid memory access error.
References _mesa_free_shader_program_data(), GL_SHADER_PROGRAM_MESA, and gl_shader_program::Type.
Referenced by free_shared_state().
free_shared_state()
static void free_shared_state (struct gl_context * ctx, struct gl_shared_state * shared) static
Deallocate a shared state object and all children structures.
Parameters
ctx GL context.
shared shared state pointer.
Frees the display lists, the texture objects (calling the driver texture deletion callback to free its private data) and the vertex programs, as well as their hash tables.
See also
alloc_shared_state().
References _mesa_delete_ati_fragment_shader(), _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), _mesa_HashWalk(), _mesa_reference_buffer_object(), _mesa_unref_sync_object(), gl_shared_state::ATIShaders, gl_shared_state::BitmapAtlas, gl_shared_state::BufferObjects, gl_shared_state::DefaultFragmentProgram, gl_shared_state::DefaultFragmentShader, gl_shared_state::DefaultTex, gl_shared_state::DefaultVertexProgram, delete_bitmap_atlas_cb(), delete_bufferobj_cb(), delete_displaylist_cb(), delete_fragshader_cb(), delete_framebuffer_cb(), delete_program_cb(), delete_renderbuffer_cb(), delete_sampler_object_cb(), delete_shader_cb(), delete_texture_cb(), dd_function_table::DeleteTexture, gl_shared_state::DisplayList, gl_context::Driver, gl_shared_state::FallbackTex, gl_shared_state::FrameBuffers, free_shader_program_data_cb(), GLuint, gl_shared_state::Mutex, gl_shared_state::NullBufferObj, NUM_TEXTURE_TARGETS, gl_shared_state::Programs, gl_shared_state::RenderBuffers, gl_shared_state::SamplerObjects, gl_shared_state::ShaderObjects, gl_shared_state::SyncObjects, gl_shared_state::TexMutex, and gl_shared_state::TexObjects.
Referenced by _mesa_reference_shared_state().