Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
state.h File Reference
#include "mtypes.h"
Functions
void _mesa_update_state (struct gl_context *ctx)
void _mesa_update_state_locked (struct gl_context *ctx)
Compute derived GL state.
void _mesa_set_varying_vp_inputs (struct gl_context *ctx, GLbitfield64 varying_inputs)
Want to figure out which fragment program inputs are actually constant/current values from ctx->Current.
void _mesa_set_vp_override (struct gl_context *ctx, GLboolean flag)
Used by drivers to tell core Mesa that the driver is going to install/ use its own vertex program.
static GLboolean _mesa_need_secondary_color (const struct gl_context *ctx)
Is the secondary color needed?
Function Documentation
_mesa_need_secondary_color()
static GLboolean _mesa_need_secondary_color (const struct gl_context * ctx) inline static
Is the secondary color needed?
References gl_vertex_program_state::_Current, gl_fragment_program_state::_Current, gl_fragment_program_state::_TexEnvProgram, gl_vertex_program_state::_TnlProgram, gl_lightmodel::ColorControl, gl_fog_attrib::ColorSumEnabled, gl_light_attrib::Enabled, gl_context::Fog, gl_context::FragmentProgram, gl_program::info, gl_context::Light, gl_light_attrib::Model, and gl_context::VertexProgram.
_mesa_set_varying_vp_inputs()
void _mesa_set_varying_vp_inputs (struct gl_context * ctx, GLbitfield64 varying_inputs)
Want to figure out which fragment program inputs are actually constant/current values from ctx->Current.
These should be referenced as a tracked state variable rather than a fragment program input, to save the overhead of putting a constant value in every submitted vertex, transferring it to hardware, interpolating it across the triangle, etc...
When there is a VP bound, just use vp->outputs. But when we're generating vp from fixed function state, basically want to calculate:
vp_out_2_fp_in(vp_in_2_vp_out(varying_inputs) | potential_vp_outputs)
Where potential_vp_outputs is calculated by looking at enabled texgen, etc.
The generated fragment program should then only declare inputs that may vary or otherwise differ from the ctx->Current values. Otherwise, the fp should track them as state values instead.
References _NEW_VARYING_VP_INPUTS, gl_fragment_program_state::_TexEnvProgram, gl_vertex_program_state::_TnlProgram, gl_context::FragmentProgram, gl_context::NewState, gl_context::varying_vp_inputs, and gl_context::VertexProgram.
_mesa_set_vp_override()
void _mesa_set_vp_override (struct gl_context * ctx, GLboolean flag)
Used by drivers to tell core Mesa that the driver is going to install/ use its own vertex program.
In particular, this will prevent generated fragment programs from using state vars instead of ordinary varyings/inputs.
References _NEW_PROGRAM, gl_vertex_program_state::_Overriden, gl_context::NewState, and gl_context::VertexProgram.
Referenced by _mesa_CopyPixels(), _mesa_DrawPixels(), and draw_texture().
_mesa_update_state()
void _mesa_update_state (struct gl_context * ctx)
References _mesa_lock_context_textures(), _mesa_unlock_context_textures(), and _mesa_update_state_locked().
Referenced by _mesa_Accum(), _mesa_Clear(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_copy_texture_sub_image(), _mesa_EGLImageTargetTexture2DOES(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_GetMultisamplefv(), _mesa_GetTexEnvfv(), _mesa_ReadnPixelsARB(), _mesa_readpixels(), _mesa_texture_sub_image(), _mesa_valid_to_render(), check_extra(), copyteximage(), draw_texture(), rasterpos(), and teximage().
_mesa_update_state_locked()
void _mesa_update_state_locked (struct gl_context * ctx)
Compute derived GL state.
If __struct gl_contextRec::NewState is non-zero then this function must be called before rendering anything.
Calls dd_function_table::UpdateState to perform any internal state management necessary.
See also
_mesa_update_modelview_project(), _mesa_update_texture(), _mesa_update_buffer_bounds(), _mesa_update_lighting() and _mesa_update_tnl_spaces().
References gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _MESA_NEW_NEED_EYE_COORDS, _mesa_print_state(), _mesa_update_draw_buffer_bounds(), _mesa_update_framebuffer(), _mesa_update_lighting(), _mesa_update_modelview_project(), _mesa_update_pixel(), _mesa_update_stencil(), _mesa_update_texture_matrices(), _mesa_update_texture_state(), _mesa_update_tnl_spaces(), _mesa_update_vao_client_arrays(), _NEW_ARRAY, _NEW_BUFFERS, _NEW_COLOR, _NEW_CURRENT_ATTRIB, _NEW_FOG, _NEW_FRAG_CLAMP, _NEW_LIGHT, _NEW_LINE, _NEW_MODELVIEW, _NEW_PIXEL, _NEW_POINT, _NEW_POLYGON, _NEW_PROGRAM, _NEW_PROJECTION, _NEW_RENDERMODE, _NEW_SCISSOR, _NEW_STENCIL, _NEW_TEXTURE_MATRIX, _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, _NEW_TRANSFORM, _NEW_VARYING_VP_INPUTS, _NEW_VIEWPORT, gl_context::Array, gl_context::DrawBuffer, gl_context::Driver, gl_context::FragmentProgram, MESA_VERBOSE, gl_vertex_array_object::NewArrays, gl_context::NewState, gl_context::ReadBuffer, update_frontbit(), update_program(), update_program_constants(), update_program_enables(), update_twoside(), dd_function_table::UpdateState, gl_array_attrib::VAO, VERBOSE_STATE, and gl_context::VertexProgram.
Referenced by _mesa_update_state(), and get_tex_parameterfv().