Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
stencil.h File Reference
Stencil operations.
#include "glheader.h"
#include "macros.h"
Functions
void GLAPIENTRY _mesa_ClearStencil (GLint s)
Set the clear value for the stencil buffer.
void GLAPIENTRY _mesa_StencilFunc (GLenum func, GLint ref, GLuint mask)
Set the function and reference value for stencil testing.
void GLAPIENTRY _mesa_StencilMask (GLuint mask)
Set the stencil writing mask.
void GLAPIENTRY _mesa_StencilOp (GLenum fail, GLenum zfail, GLenum zpass)
Set the stencil test actions.
void GLAPIENTRY _mesa_ActiveStencilFaceEXT (GLenum face)
void GLAPIENTRY _mesa_StencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
void GLAPIENTRY _mesa_StencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
void GLAPIENTRY _mesa_StencilFuncSeparateATI (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask)
Set the function and reference value for stencil testing.
void GLAPIENTRY _mesa_StencilMaskSeparate (GLenum face, GLuint mask)
void _mesa_update_stencil (struct gl_context *ctx)
Update derived stencil state.
void _mesa_init_stencil (struct gl_context *ctx)
Initialize the context stipple state.
static GLint _mesa_get_stencil_ref (struct gl_context const *ctx, int face)
Detailed Description
Stencil operations.
Function Documentation
_mesa_ActiveStencilFaceEXT()
void GLAPIENTRY _mesa_ActiveStencilFaceEXT (GLenum face)
References _mesa_debug(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_ClearStencil()
void GLAPIENTRY _mesa_ClearStencil (GLint s)
Set the clear value for the stencil buffer.
Parameters
s clear value.
See also
glClearStencil().
Updates gl_stencil_attrib::Clear. On change flushes the vertices and notifies the driver via the dd_function_table::ClearStencil callback.
References _mesa_debug(), GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_get_stencil_ref()
static GLint _mesa_get_stencil_ref (struct gl_context const * ctx, int face) inline static
References gl_context::DrawBuffer, gl_stencil_attrib::Ref, gl_context::Stencil, gl_config::stencilBits, and gl_framebuffer::Visual.
Referenced by find_custom_value().
_mesa_init_stencil()
void _mesa_init_stencil (struct gl_context * ctx)
Initialize the context stipple state.
Parameters
ctx GL context.
Initializes __struct gl_contextRec::Stencil attribute group.
References gl_stencil_attrib::_BackFace, gl_stencil_attrib::ActiveFace, gl_stencil_attrib::Clear, gl_stencil_attrib::Enabled, gl_stencil_attrib::FailFunc, gl_stencil_attrib::Function, gl_stencil_attrib::Ref, gl_context::Stencil, gl_stencil_attrib::TestTwoSide, gl_stencil_attrib::ValueMask, gl_stencil_attrib::WriteMask, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Referenced by init_attrib_groups().
_mesa_StencilFunc()
void GLAPIENTRY _mesa_StencilFunc (GLenum func, GLint ref, GLuint mask)
Set the function and reference value for stencil testing.
Parameters
func test function.
ref reference value.
mask bitmask.
See also
glStencilFunc().
Verifies the parameters and updates the respective values in __struct gl_contextRec::Stencil. On change flushes the vertices and notifies the driver via the dd_function_table::StencilFunc callback.
References _mesa_debug(), _mesa_error(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, validate_stencil_func(), and VERBOSE_API.
_mesa_StencilFuncSeparate()
void GLAPIENTRY _mesa_StencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
References _mesa_debug(), _mesa_error(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, validate_stencil_func(), and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_StencilFuncSeparateATI()
void GLAPIENTRY _mesa_StencilFuncSeparateATI (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask)
Set the function and reference value for stencil testing.
Parameters
frontfunc front test function.
backfunc back test function.
ref front and back reference value.
mask front and back bitmask.
See also
glStencilFunc().
Verifies the parameters and updates the respective values in __struct gl_contextRec::Stencil. On change flushes the vertices and notifies the driver via the dd_function_table::StencilFunc callback.
References _mesa_debug(), _mesa_error(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, validate_stencil_func(), and VERBOSE_API.
_mesa_StencilMask()
void GLAPIENTRY _mesa_StencilMask (GLuint mask)
Set the stencil writing mask.
Parameters
mask bit-mask to enable/disable writing of individual bits in the stencil planes.
See also
glStencilMask().
Updates gl_stencil_attrib::WriteMask. On change flushes the vertices and notifies the driver via the dd_function_table::StencilMask callback.
References _mesa_debug(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
_mesa_StencilMaskSeparate()
void GLAPIENTRY _mesa_StencilMaskSeparate (GLenum face, GLuint mask)
References _mesa_debug(), _mesa_error(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_StencilOp()
void GLAPIENTRY _mesa_StencilOp (GLenum fail, GLenum zfail, GLenum zpass)
Set the stencil test actions.
Parameters
fail action to take when stencil test fails.
zfail action to take when stencil test passes, but depth test fails.
zpass action to take when stencil test passes and the depth test passes (or depth testing is not enabled).
See also
glStencilOp().
Verifies the parameters and updates the respective fields in __struct gl_contextRec::Stencil. On change flushes the vertices and notifies the driver via the dd_function_table::StencilOp callback.
References _mesa_debug(), _mesa_error(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, validate_stencil_op(), and VERBOSE_API.
_mesa_StencilOpSeparate()
void GLAPIENTRY _mesa_StencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
References _mesa_debug(), _mesa_error(), _NEW_STENCIL, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, validate_stencil_op(), and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_update_stencil()
void _mesa_update_stencil (struct gl_context * ctx)
Update derived stencil state.
References gl_stencil_attrib::_BackFace, gl_stencil_attrib::_Enabled, gl_stencil_attrib::_TestTwoSide, gl_stencil_attrib::_WriteEnabled, gl_context::DrawBuffer, gl_stencil_attrib::Enabled, gl_stencil_attrib::FailFunc, gl_stencil_attrib::Function, gl_stencil_attrib::Ref, gl_context::Stencil, gl_config::stencilBits, gl_stencil_attrib::ValueMask, gl_framebuffer::Visual, gl_stencil_attrib::WriteMask, gl_stencil_attrib::ZFailFunc, and gl_stencil_attrib::ZPassFunc.
Referenced by _mesa_update_state_locked().