Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
dd_function_table Struct Reference
Device driver function table.
#include <dd.h>
Data Fields
const GLubyte *(* GetString)(struct gl_context *ctx, GLenum name)
Return a string as needed by glGetString().
void(* UpdateState)(struct gl_context *ctx, GLbitfield new_state)
Notify the driver after Mesa has made some internal state changes.
void(* Finish)(struct gl_context *ctx)
This is called whenever glFinish() is called.
void(* Flush)(struct gl_context *ctx)
This is called whenever glFlush() is called.
void(* Clear)(struct gl_context *ctx, GLbitfield buffers)
Clear the color/depth/stencil/accum buffer(s).
void(* RasterPos)(struct gl_context *ctx, const GLfloat v[4])
Execute glRasterPos, updating the ctx->Current.Raster fields.
void(* BlitFramebuffer)(struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
void(* DiscardFramebuffer)(struct gl_context *ctx, GLenum target, GLsizei numAttachments, const GLenum *attachments)
void(* BeginConditionalRender)(struct gl_context *ctx, struct gl_query_object *q, GLenum mode)
GL_NV_conditional_render.
void(* EndConditionalRender)(struct gl_context *ctx, struct gl_query_object *q)
void(* QueryMemoryInfo)(struct gl_context *ctx, struct gl_memory_info *info)
Query information about memory.
void(* SetBackgroundContext)(struct gl_context *ctx)
Indicate that this thread is being used by Mesa as a background drawing thread for the given GL context.
Image-related functions
void(* DrawPixels)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Called by glDrawPixels().
void(* ReadPixels)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, GLvoid *dest)
Called by glReadPixels().
void(* CopyPixels)(struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint dstx, GLint dsty, GLenum type)
Called by glCopyPixels().
void(* Bitmap)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
Called by glBitmap().
void(* DrawAtlasBitmaps)(struct gl_context *ctx, const struct gl_bitmap_atlas *atlas, GLuint count, const GLubyte *ids)
Called by display list code for optimized glCallLists/glBitmap rendering The driver must support texture rectangles of width 1024 or more.
Texture image functions
mesa_format(* ChooseTextureFormat)(struct gl_context *ctx, GLenum target, GLint internalFormat, GLenum srcFormat, GLenum srcType)
Choose actual hardware texture format given the texture target, the user-provided source image format and type and the desired internal format.
void(* QueryInternalFormat)(struct gl_context *ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint *params)
Queries different driver parameters for a particular target and format.
void(* TexImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexImage[123]D() and glCopyTexImage[12]D() Allocate texture memory and copy the user's image to the buffer.
void(* TexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexSubImage[123]D().
void(* GetTexSubImage)(struct gl_context *ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
Called by glGetTexImage(), glGetTextureSubImage().
void(* ClearTexSubImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, const GLvoid *clearValue)
Called by glClearTex[Sub]Image.
void(* CopyTexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint slice, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height)
Called by glCopyTex[Sub]Image[123]D().
void(* CopyImageSubData)(struct gl_context *ctx, struct gl_texture_image *src_teximage, struct gl_renderbuffer *src_renderbuffer, int src_x, int src_y, int src_z, struct gl_texture_image *dst_teximage, struct gl_renderbuffer *dst_renderbuffer, int dst_x, int dst_y, int dst_z, int src_width, int src_height)
Called by glCopyImageSubData().
void(* GenerateMipmap)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Called by glGenerateMipmap() or when GL_GENERATE_MIPMAP_SGIS is enabled.
GLboolean(* TestProxyTexImage)(struct gl_context *ctx, GLenum target, GLuint numLevels, GLint level, mesa_format format, GLuint numSamples, GLint width, GLint height, GLint depth)
Called by glTexImage, glCompressedTexImage, glCopyTexImage and glTexStorage to check if the dimensions of the texture image are too large.
Compressed texture functions
void(* CompressedTexImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexImage[123]D().
void(* CompressedTexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexSubImage[123]D().
void(* GetCompressedTexSubImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLvoid *data)
Called by glGetCompressedTexImage.
Texture object / image functions
void(* BindTexture)(struct gl_context *ctx, GLuint texUnit, GLenum target, struct gl_texture_object *tObj)
Called by glBindTexture() and glBindTextures().
struct gl_texture_object *(* NewTextureObject)(struct gl_context *ctx, GLuint name, GLenum target)
Called to allocate a new texture object.
void(* DeleteTexture)(struct gl_context *ctx, struct gl_texture_object *texObj)
Called to delete/free a texture object.
struct gl_texture_image *(* NewTextureImage)(struct gl_context *ctx)
Called to allocate a new texture image object.
void(* DeleteTextureImage)(struct gl_context *ctx, struct gl_texture_image *)
Called to free a texture image object returned by NewTextureImage()
GLboolean(* AllocTextureImageBuffer)(struct gl_context *ctx, struct gl_texture_image *texImage)
Called to allocate memory for a single texture image.
void(* FreeTextureImageBuffer)(struct gl_context *ctx, struct gl_texture_image *texImage)
Free the memory for a single texture image.
void(* MapTextureImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a slice of a texture image into user space.
void(* UnmapTextureImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice)
GLboolean(* AllocTextureStorage)(struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
For GL_ARB_texture_storage.
GLboolean(* TextureView)(struct gl_context *ctx, struct gl_texture_object *texObj, struct gl_texture_object *origTexObj)
Called as part of glTextureView to add views to origTexObj.
bool(* SetTextureStorageForBufferObject)(struct gl_context *ctx, struct gl_texture_object *texObj, struct gl_buffer_object *bufferObj, uint32_t buffer_offset, uint32_t row_stride, bool read_only)
Sets the given buffer object as the texture's storage.
void(* MapRenderbuffer)(struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a renderbuffer into user space.
void(* UnmapRenderbuffer)(struct gl_context *ctx, struct gl_renderbuffer *rb)
GLboolean(* BindRenderbufferTexImage)(struct gl_context *ctx, struct gl_renderbuffer *rb, struct gl_texture_image *texImage)
Optional driver entrypoint that binds a non-texture renderbuffer's contents to a texture image.
Vertex/fragment program functions
struct gl_program *(* NewProgram)(struct gl_context *ctx, GLenum target, GLuint id, bool is_arb_asm)
Allocate a new program.
void(* DeleteProgram)(struct gl_context *ctx, struct gl_program *prog)
Delete a program.
struct gl_program *(* NewATIfs)(struct gl_context *ctx, struct ati_fragment_shader *curProg)
Allocate a program to associate with the new ATI fragment shader (optional)
GLboolean(* ProgramStringNotify)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that a program string (and GPU code) has been specified or modified.
void(* SamplerUniformChange)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that the sampler uniforms for the current program have changed.
GLboolean(* IsProgramNative)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Query if program can be loaded onto hardware.
GLSL shader/program functions.
GLboolean(* LinkShader)(struct gl_context *ctx, struct gl_shader_program *shader)
Called when a shader program is linked.
State-changing functions.
Note
drawing functions are above.
These functions are called by their corresponding OpenGL API functions. They are also called by the gl_PopAttrib() function!!! May add more functions like these to the device driver in the future.
void(* AlphaFunc)(struct gl_context *ctx, GLenum func, GLfloat ref)
Specify the alpha test function.
void(* BlendColor)(struct gl_context *ctx, const GLfloat color[4])
Set the blend color.
void(* BlendEquationSeparate)(struct gl_context *ctx, GLenum modeRGB, GLenum modeA)
Set the blend equation.
void(* BlendFuncSeparate)(struct gl_context *ctx, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Specify pixel arithmetic.
void(* ClipPlane)(struct gl_context *ctx, GLenum plane, const GLfloat *eq)
Specify a plane against which all geometry is clipped.
void(* ColorMask)(struct gl_context *ctx, GLboolean rmask, GLboolean gmask, GLboolean bmask, GLboolean amask)
Enable and disable writing of frame buffer color components.
void(* ColorMaterial)(struct gl_context *ctx, GLenum face, GLenum mode)
Cause a material color to track the current color.
void(* CullFace)(struct gl_context *ctx, GLenum mode)
Specify whether front- or back-facing facets can be culled.
void(* FrontFace)(struct gl_context *ctx, GLenum mode)
Define front- and back-facing polygons.
void(* DepthFunc)(struct gl_context *ctx, GLenum func)
Specify the value used for depth buffer comparisons.
void(* DepthMask)(struct gl_context *ctx, GLboolean flag)
Enable or disable writing into the depth buffer.
void(* DepthRange)(struct gl_context *ctx)
Specify mapping of depth values from NDC to window coordinates.
void(* DrawBuffer)(struct gl_context *ctx, GLenum buffer)
Specify the current buffer for writing.
void(* DrawBuffers)(struct gl_context *ctx, GLsizei n, const GLenum *buffers)
Specify the buffers for writing for fragment programs.
void(* Enable)(struct gl_context *ctx, GLenum cap, GLboolean state)
Enable or disable server-side gl capabilities.
void(* Fogfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
Specify fog parameters.
void(* Lightfv)(struct gl_context *ctx, GLenum light, GLenum pname, const GLfloat *params)
Set light source parameters.
void(* LightModelfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
Set the lighting model parameters.
void(* LineStipple)(struct gl_context *ctx, GLint factor, GLushort pattern)
Specify the line stipple pattern.
void(* LineWidth)(struct gl_context *ctx, GLfloat width)
Specify the width of rasterized lines.
void(* LogicOpcode)(struct gl_context *ctx, GLenum opcode)
Specify a logical pixel operation for color index rendering.
void(* PointParameterfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
void(* PointSize)(struct gl_context *ctx, GLfloat size)
Specify the diameter of rasterized points.
void(* PolygonMode)(struct gl_context *ctx, GLenum face, GLenum mode)
Select a polygon rasterization mode.
void(* PolygonOffset)(struct gl_context *ctx, GLfloat factor, GLfloat units, GLfloat clamp)
Set the scale and units used to calculate depth values.
void(* PolygonStipple)(struct gl_context *ctx, const GLubyte *mask)
Set the polygon stippling pattern.
void(* ReadBuffer)(struct gl_context *ctx, GLenum buffer)
void(* RenderMode)(struct gl_context *ctx, GLenum mode)
Set rasterization mode.
void(* Scissor)(struct gl_context *ctx)
Define the scissor box.
void(* ShadeModel)(struct gl_context *ctx, GLenum mode)
Select flat or smooth shading.
void(* StencilFuncSeparate)(struct gl_context *ctx, GLenum face, GLenum func, GLint ref, GLuint mask)
OpenGL 2.0 two-sided StencilFunc.
void(* StencilMaskSeparate)(struct gl_context *ctx, GLenum face, GLuint mask)
OpenGL 2.0 two-sided StencilMask.
void(* StencilOpSeparate)(struct gl_context *ctx, GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
OpenGL 2.0 two-sided StencilOp.
void(* TexGen)(struct gl_context *ctx, GLenum coord, GLenum pname, const GLfloat *params)
Control the generation of texture coordinates.
void(* TexEnv)(struct gl_context *ctx, GLenum target, GLenum pname, const GLfloat *param)
Set texture environment parameters.
void(* TexParameter)(struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname)
Set texture parameter (callee gets param value from the texObj)
void(* Viewport)(struct gl_context *ctx)
Set the viewport.
Vertex/pixel buffer object functions
struct gl_buffer_object *(* NewBufferObject)(struct gl_context *ctx, GLuint buffer)
void(* DeleteBuffer)(struct gl_context *ctx, struct gl_buffer_object *obj)
GLboolean(* BufferData)(struct gl_context *ctx, GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage, GLenum storageFlags, struct gl_buffer_object *obj)
void(* BufferSubData)(struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data, struct gl_buffer_object *obj)
void(* GetBufferSubData)(struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *obj)
void(* ClearBufferSubData)(struct gl_context *ctx, GLintptr offset, GLsizeiptr size, const GLvoid *clearValue, GLsizeiptr clearValueSize, struct gl_buffer_object *obj)
void(* CopyBufferSubData)(struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void(* InvalidateBufferSubData)(struct gl_context *ctx, struct gl_buffer_object *obj, GLintptr offset, GLsizeiptr length)
void *(* MapBufferRange)(struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *obj, gl_map_buffer_index index)
void(* FlushMappedBufferRange)(struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj, gl_map_buffer_index index)
GLboolean(* UnmapBuffer)(struct gl_context *ctx, struct gl_buffer_object *obj, gl_map_buffer_index index)
Functions for GL_APPLE_object_purgeable
GLenum(* BufferObjectPurgeable)(struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
GLenum(* RenderObjectPurgeable)(struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
GLenum(* TextureObjectPurgeable)(struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
GLenum(* BufferObjectUnpurgeable)(struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
GLenum(* RenderObjectUnpurgeable)(struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
GLenum(* TextureObjectUnpurgeable)(struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
Functions for GL_EXT_framebuffer_{object,blit,discard}.
struct gl_framebuffer *(* NewFramebuffer)(struct gl_context *ctx, GLuint name)
struct gl_renderbuffer *(* NewRenderbuffer)(struct gl_context *ctx, GLuint name)
void(* BindFramebuffer)(struct gl_context *ctx, GLenum target, struct gl_framebuffer *drawFb, struct gl_framebuffer *readFb)
void(* FramebufferRenderbuffer)(struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
void(* RenderTexture)(struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
void(* FinishRenderTexture)(struct gl_context *ctx, struct gl_renderbuffer *rb)
void(* ValidateFramebuffer)(struct gl_context *ctx, struct gl_framebuffer *fb)
Query objects
struct gl_query_object *(* NewQueryObject)(struct gl_context *ctx, GLuint id)
void(* DeleteQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* BeginQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* QueryCounter)(struct gl_context *ctx, struct gl_query_object *q)
void(* EndQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* CheckQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* WaitQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* StoreQueryResult)(struct gl_context *ctx, struct gl_query_object *q, struct gl_buffer_object *buf, intptr_t offset, GLenum pname, GLenum ptype)
Performance monitors
void(* InitPerfMonitorGroups)(struct gl_context *ctx)
struct gl_perf_monitor_object *(* NewPerfMonitor)(struct gl_context *ctx)
void(* DeletePerfMonitor)(struct gl_context *ctx, struct gl_perf_monitor_object *m)
GLboolean(* BeginPerfMonitor)(struct gl_context *ctx, struct gl_perf_monitor_object *m)
void(* ResetPerfMonitor)(struct gl_context *ctx, struct gl_perf_monitor_object *m)
Stop an active performance monitor, discarding results.
void(* EndPerfMonitor)(struct gl_context *ctx, struct gl_perf_monitor_object *m)
GLboolean(* IsPerfMonitorResultAvailable)(struct gl_context *ctx, struct gl_perf_monitor_object *m)
void(* GetPerfMonitorResult)(struct gl_context *ctx, struct gl_perf_monitor_object *m, GLsizei dataSize, GLuint *data, GLint *bytesWritten)
Performance Query objects
unsigned(* InitPerfQueryInfo)(struct gl_context *ctx)
void(* GetPerfQueryInfo)(struct gl_context *ctx, unsigned queryIndex, const char **name, GLuint *dataSize, GLuint *numCounters, GLuint *numActive)
void(* GetPerfCounterInfo)(struct gl_context *ctx, unsigned queryIndex, unsigned counterIndex, const char **name, const char **desc, GLuint *offset, GLuint *data_size, GLuint *type_enum, GLuint *data_type_enum, GLuint64 *raw_max)
struct gl_perf_query_object *(* NewPerfQueryObject)(struct gl_context *ctx, unsigned queryIndex)
void(* DeletePerfQuery)(struct gl_context *ctx, struct gl_perf_query_object *obj)
bool(* BeginPerfQuery)(struct gl_context *ctx, struct gl_perf_query_object *obj)
void(* EndPerfQuery)(struct gl_context *ctx, struct gl_perf_query_object *obj)
void(* WaitPerfQuery)(struct gl_context *ctx, struct gl_perf_query_object *obj)
bool(* IsPerfQueryReady)(struct gl_context *ctx, struct gl_perf_query_object *obj)
void(* GetPerfQueryData)(struct gl_context *ctx, struct gl_perf_query_object *obj, GLsizei dataSize, GLuint *data, GLuint *bytesWritten)
GREMEDY debug/marker functions
void(* EmitStringMarker)(struct gl_context *ctx, const GLchar *string, GLsizei len)
Support for multiple T&L engines
GLuint CurrentExecPrimitive
Set by the driver-supplied T&L engine.
GLuint CurrentSavePrimitive
Current glBegin state of an in-progress compilation.
GLbitfield NeedFlush
Set by the driver-supplied T&L engine whenever vertices are buffered between glBegin()/glEnd() objects or __struct gl_contextRec::Current is not updated.
GLboolean SaveNeedFlush
Need to call vbo_save_SaveFlushVertices() upon state change?
void(* LightingSpaceChange)(struct gl_context *ctx)
Notify driver that the special derived value _NeedEyeCoords has changed.
GL_ARB_sync interfaces
struct gl_sync_object *(* NewSyncObject)(struct gl_context *, GLenum)
void(* FenceSync)(struct gl_context *, struct gl_sync_object *, GLenum, GLbitfield)
void(* DeleteSyncObject)(struct gl_context *, struct gl_sync_object *)
void(* CheckSync)(struct gl_context *, struct gl_sync_object *)
void(* ClientWaitSync)(struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
void(* ServerWaitSync)(struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
GL_OES_draw_texture interface
void(* DrawTex)(struct gl_context *ctx, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
GL_OES_EGL_image interface
void(* EGLImageTargetTexture2D)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLeglImageOES image_handle)
void(* EGLImageTargetRenderbufferStorage)(struct gl_context *ctx, struct gl_renderbuffer *rb, void *image_handle)
GL_EXT_transform_feedback interface
struct gl_transform_feedback_object *(* NewTransformFeedback)(struct gl_context *ctx, GLuint name)
void(* DeleteTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void(* BeginTransformFeedback)(struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
void(* EndTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void(* PauseTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void(* ResumeTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
GLsizei(* GetTransformFeedbackVertexCount)(struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint stream)
Return the number of vertices written to a stream during the last Begin/EndTransformFeedback block.
GL_NV_texture_barrier interface
void(* TextureBarrier)(struct gl_context *ctx)
GL_ARB_sampler_objects
struct gl_sampler_object *(* NewSamplerObject)(struct gl_context *ctx, GLuint name)
Return a timestamp in nanoseconds as defined by GL_ARB_timer_query.
This should be equivalent to glGetInteger64v(GL_TIMESTAMP);
uint64_t(* GetTimestamp)(struct gl_context *ctx)
GL_ARB_texture_multisample
void(* GetSamplePosition)(struct gl_context *ctx, struct gl_framebuffer *fb, GLuint index, GLfloat *outValue)
NV_vdpau_interop interface
void(* VDPAUMapSurface)(struct gl_context *ctx, GLenum target, GLenum access, GLboolean output, struct gl_texture_object *texObj, struct gl_texture_image *texImage, const GLvoid *vdpSurface, GLuint index)
void(* VDPAUUnmapSurface)(struct gl_context *ctx, GLenum target, GLenum access, GLboolean output, struct gl_texture_object *texObj, struct gl_texture_image *texImage, const GLvoid *vdpSurface, GLuint index)
GLenum(* GetGraphicsResetStatus)(struct gl_context *ctx)
Query reset status for GL_ARB_robustness.
GL_ARB_shader_image_load_store interface.
void(* MemoryBarrier)(struct gl_context *ctx, GLbitfield barriers)
void(* BlendBarrier)(struct gl_context *ctx)
GL_MESA_shader_framebuffer_fetch_non_coherent rendering barrier.
GL_ARB_compute_shader interface
void(* DispatchCompute)(struct gl_context *ctx, const GLuint *num_groups)
void(* DispatchComputeIndirect)(struct gl_context *ctx, GLintptr indirect)
GL_ARB_compute_variable_group_size interface
void(* DispatchComputeGroupSize)(struct gl_context *ctx, const GLuint *num_groups, const GLuint *group_size)
GL_ARB_sparse_buffer interface
void(* BufferPageCommitment)(struct gl_context *ctx, struct gl_buffer_object *bufferObj, GLintptr offset, GLsizeiptr size, GLboolean commit)
Detailed Description
Device driver function table.
Core Mesa uses these function pointers to call into device drivers. Most of these functions directly correspond to OpenGL state commands. Core Mesa will call these functions after error checking has been done so that the drivers don't have to worry about error testing.
Vertex transformation/clipping/lighting is patched into the T&L module. Rasterization functions are patched into the swrast module.
Note: when new functions are added here, the drivers/common/driverfuncs.c file should be updated too!!!
Field Documentation
AllocTextureImageBuffer
GLboolean(* dd_function_table::AllocTextureImageBuffer) (struct gl_context *ctx, struct gl_texture_image *texImage)
Called to allocate memory for a single texture image.
Referenced by _mesa_AllocTextureStorage_sw(), _mesa_store_compressed_teximage(), _mesa_store_teximage(), build_bitmap_atlas(), copyteximage(), and prepare_mipmap_level().
AllocTextureStorage
GLboolean(* dd_function_table::AllocTextureStorage) (struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
For GL_ARB_texture_storage.
Allocate memory for whole mipmap stack. All the gl_texture_images in the texture object will have their dimensions, format, etc. initialized already.
Referenced by _mesa_texture_storage(), and texture_image_multisample().
AlphaFunc
void(* dd_function_table::AlphaFunc) (struct gl_context *ctx, GLenum func, GLfloat ref)
Specify the alpha test function.
BeginConditionalRender
void(* dd_function_table::BeginConditionalRender) (struct gl_context *ctx, struct gl_query_object *q, GLenum mode)
GL_NV_conditional_render.
BeginPerfMonitor
GLboolean(* dd_function_table::BeginPerfMonitor) (struct gl_context *ctx, struct gl_perf_monitor_object *m)
BeginPerfQuery
bool(* dd_function_table::BeginPerfQuery) (struct gl_context *ctx, struct gl_perf_query_object *obj)
BeginQuery
void(* dd_function_table::BeginQuery) (struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_init_query_object_functions().
BeginTransformFeedback
void(* dd_function_table::BeginTransformFeedback) (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
BindFramebuffer
void(* dd_function_table::BindFramebuffer) (struct gl_context *ctx, GLenum target, struct gl_framebuffer *drawFb, struct gl_framebuffer *readFb)
Referenced by _mesa_bind_framebuffers().
BindRenderbufferTexImage
GLboolean(* dd_function_table::BindRenderbufferTexImage) (struct gl_context *ctx, struct gl_renderbuffer *rb, struct gl_texture_image *texImage)
Optional driver entrypoint that binds a non-texture renderbuffer's contents to a texture image.
Referenced by check_end_texture_render().
BindTexture
void(* dd_function_table::BindTexture) (struct gl_context *ctx, GLuint texUnit, GLenum target, struct gl_texture_object *tObj)
Called by glBindTexture() and glBindTextures().
Referenced by bind_texture(), and unbind_textures_from_unit().
Bitmap
void(* dd_function_table::Bitmap) (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
Called by glBitmap().
BlendBarrier
void(* dd_function_table::BlendBarrier) (struct gl_context *ctx)
GL_MESA_shader_framebuffer_fetch_non_coherent rendering barrier.
On return from this function any framebuffer contents written by previous draw commands are guaranteed to be visible from subsequent fragment shader invocations using the MESA_shader_framebuffer_fetch_non_coherent interface.
BlendColor
void(* dd_function_table::BlendColor) (struct gl_context *ctx, const GLfloat color[4])
Set the blend color.
BlendEquationSeparate
void(* dd_function_table::BlendEquationSeparate) (struct gl_context *ctx, GLenum modeRGB, GLenum modeA)
Set the blend equation.
BlendFuncSeparate
void(* dd_function_table::BlendFuncSeparate) (struct gl_context *ctx, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Specify pixel arithmetic.
BlitFramebuffer
void(* dd_function_table::BlitFramebuffer) (struct gl_context *ctx, struct gl_framebuffer *readFb, struct gl_framebuffer *drawFb, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Referenced by _mesa_blit_framebuffer().
BufferData
GLboolean(* dd_function_table::BufferData) (struct gl_context *ctx, GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage, GLenum storageFlags, struct gl_buffer_object *obj)
Referenced by _mesa_buffer_data(), _mesa_buffer_storage(), and _mesa_init_buffer_object_functions().
BufferObjectPurgeable
GLenum(* dd_function_table::BufferObjectPurgeable) (struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
Referenced by buffer_object_purgeable().
BufferObjectUnpurgeable
GLenum(* dd_function_table::BufferObjectUnpurgeable) (struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
Referenced by buffer_object_unpurgeable().
BufferPageCommitment
void(* dd_function_table::BufferPageCommitment) (struct gl_context *ctx, struct gl_buffer_object *bufferObj, GLintptr offset, GLsizeiptr size, GLboolean commit)
Referenced by buffer_page_commitment().
BufferSubData
void(* dd_function_table::BufferSubData) (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data, struct gl_buffer_object *obj)
Referenced by _mesa_buffer_sub_data(), and _mesa_init_buffer_object_functions().
CheckQuery
void(* dd_function_table::CheckQuery) (struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_check_conditional_render(), _mesa_init_query_object_functions(), and get_query_object().
CheckSync
void(* dd_function_table::CheckSync) (struct gl_context *, struct gl_sync_object *)
Referenced by _mesa_init_sync_object_functions().
ChooseTextureFormat
mesa_format(* dd_function_table::ChooseTextureFormat) (struct gl_context *ctx, GLenum target, GLint internalFormat, GLenum srcFormat, GLenum srcType)
Choose actual hardware texture format given the texture target, the user-provided source image format and type and the desired internal format.
In some cases, srcFormat and srcType can be GL_NONE. Note: target may be GL_TEXTURE_CUBE_MAP, but never GL_TEXTURE_CUBE_MAP_[POSITIVE/NEGATIVE]_[XYZ]. Called by glTexImage(), etc.
Referenced by _mesa_choose_texture_format(), and _mesa_get_fallback_texture().
Clear
void(* dd_function_table::Clear) (struct gl_context *ctx, GLbitfield buffers)
Clear the color/depth/stencil/accum buffer(s).
Parameters
buffers a bitmask of BUFFER_BIT_* flags indicating which renderbuffers need to be cleared.
ClearBufferSubData
void(* dd_function_table::ClearBufferSubData) (struct gl_context *ctx, GLintptr offset, GLsizeiptr size, const GLvoid *clearValue, GLsizeiptr clearValueSize, struct gl_buffer_object *obj)
Referenced by _mesa_clear_buffer_sub_data(), and _mesa_init_buffer_object_functions().
ClearTexSubImage
void(* dd_function_table::ClearTexSubImage) (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, const GLvoid *clearValue)
Called by glClearTex[Sub]Image.
Clears a rectangular region of the image to a given value. The clearValue argument is either NULL or points to a single texel to use as the clear value in the same internal format as the texture image. If it is NULL then the texture should be cleared to zeroes.
Referenced by _mesa_ClearTexImage(), and _mesa_ClearTexSubImage().
ClientWaitSync
void(* dd_function_table::ClientWaitSync) (struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
Referenced by _mesa_init_sync_object_functions().
ClipPlane
void(* dd_function_table::ClipPlane) (struct gl_context *ctx, GLenum plane, const GLfloat *eq)
Specify a plane against which all geometry is clipped.
ColorMask
void(* dd_function_table::ColorMask) (struct gl_context *ctx, GLboolean rmask, GLboolean gmask, GLboolean bmask, GLboolean amask)
Enable and disable writing of frame buffer color components.
ColorMaterial
void(* dd_function_table::ColorMaterial) (struct gl_context *ctx, GLenum face, GLenum mode)
Cause a material color to track the current color.
CompressedTexImage
void(* dd_function_table::CompressedTexImage) (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexImage[123]D().
Referenced by teximage().
CompressedTexSubImage
void(* dd_function_table::CompressedTexSubImage) (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexSubImage[123]D().
Referenced by _mesa_compressed_texture_sub_image(), and _mesa_store_compressed_teximage().
CopyBufferSubData
void(* dd_function_table::CopyBufferSubData) (struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
Referenced by _mesa_copy_buffer_sub_data(), and _mesa_init_buffer_object_functions().
CopyImageSubData
void(* dd_function_table::CopyImageSubData) (struct gl_context *ctx, struct gl_texture_image *src_teximage, struct gl_renderbuffer *src_renderbuffer, int src_x, int src_y, int src_z, struct gl_texture_image *dst_teximage, struct gl_renderbuffer *dst_renderbuffer, int dst_x, int dst_y, int dst_z, int src_width, int src_height)
Called by glCopyImageSubData().
This function should copy one 2-D slice from src_teximage or src_renderbuffer to dst_teximage or dst_renderbuffer. Either the teximage or renderbuffer pointer will be non-null to indicate which is the real src/dst.
If one of the textures is 3-D or is a 1-D or 2-D array texture, this function will be called multiple times: once for each slice. If one of the textures is a cube map, this function will be called once for each face to be copied.
CopyPixels
void(* dd_function_table::CopyPixels) (struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint dstx, GLint dsty, GLenum type)
Called by glCopyPixels().
CopyTexSubImage
void(* dd_function_table::CopyTexSubImage) (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint slice, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height)
Called by glCopyTex[Sub]Image[123]D().
This function should copy a rectangular region in the rb to a single destination slice, specified by . In the case of 1D array textures (where one GL call can potentially affect multiple destination slices), core mesa takes care of calling this function multiple times, once for each scanline to be copied.
Referenced by copytexsubimage_by_slice().
CullFace
void(* dd_function_table::CullFace) (struct gl_context *ctx, GLenum mode)
Specify whether front- or back-facing facets can be culled.
CurrentExecPrimitive
GLuint dd_function_table::CurrentExecPrimitive
Set by the driver-supplied T&L engine.
Set to PRIM_OUTSIDE_BEGIN_END when outside glBegin()/glEnd().
Referenced by _mesa_inside_begin_end().
CurrentSavePrimitive
GLuint dd_function_table::CurrentSavePrimitive
Current glBegin state of an in-progress compilation.
May be GL_POINTS, GL_TRIANGLE_STRIP, etc. or PRIM_OUTSIDE_BEGIN_END or PRIM_UNKNOWN.
Referenced by _mesa_inside_dlist_begin_end(), invalidate_saved_current_state(), save_Begin(), and save_End().
DeleteBuffer
void(* dd_function_table::DeleteBuffer) (struct gl_context *ctx, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions(), and _mesa_reference_buffer_object_().
DeletePerfMonitor
void(* dd_function_table::DeletePerfMonitor) (struct gl_context *ctx, struct gl_perf_monitor_object *m)
Referenced by free_performance_monitor(), and new_performance_monitor().
DeletePerfQuery
void(* dd_function_table::DeletePerfQuery) (struct gl_context *ctx, struct gl_perf_query_object *obj)
Referenced by free_performance_query().
DeleteProgram
void(* dd_function_table::DeleteProgram) (struct gl_context *ctx, struct gl_program *prog)
Delete a program.
Referenced by delete_program_cb().
DeleteQuery
void(* dd_function_table::DeleteQuery) (struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_init_query_object_functions(), and delete_queryobj_cb().
DeleteSyncObject
void(* dd_function_table::DeleteSyncObject) (struct gl_context *, struct gl_sync_object *)
Referenced by _mesa_init_sync_object_functions(), and _mesa_unref_sync_object().
DeleteTexture
void(* dd_function_table::DeleteTexture) (struct gl_context *ctx, struct gl_texture_object *texObj)
Called to delete/free a texture object.
Drivers should free the object and any image data it contains.
Referenced by _mesa_delete_bitmap_atlas(), _mesa_free_texture_data(), alloc_proxy_textures(), build_bitmap_atlas(), delete_texture_cb(), and free_shared_state().
DeleteTextureImage
void(* dd_function_table::DeleteTextureImage) (struct gl_context *ctx, struct gl_texture_image *)
Called to free a texture image object returned by NewTextureImage()
Referenced by _mesa_delete_texture_object().
DeleteTransformFeedback
void(* dd_function_table::DeleteTransformFeedback) (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_free_transform_feedback(), _mesa_init_transform_feedback_functions(), and delete_cb().
DepthFunc
void(* dd_function_table::DepthFunc) (struct gl_context *ctx, GLenum func)
Specify the value used for depth buffer comparisons.
DepthMask
void(* dd_function_table::DepthMask) (struct gl_context *ctx, GLboolean flag)
Enable or disable writing into the depth buffer.
DepthRange
void(* dd_function_table::DepthRange) (struct gl_context *ctx)
Specify mapping of depth values from NDC to window coordinates.
Referenced by _mesa_set_depth_range().
DiscardFramebuffer
void(* dd_function_table::DiscardFramebuffer) (struct gl_context *ctx, GLenum target, GLsizei numAttachments, const GLenum *attachments)
DispatchCompute
void(* dd_function_table::DispatchCompute) (struct gl_context *ctx, const GLuint *num_groups)
DispatchComputeGroupSize
void(* dd_function_table::DispatchComputeGroupSize) (struct gl_context *ctx, const GLuint *num_groups, const GLuint *group_size)
DispatchComputeIndirect
void(* dd_function_table::DispatchComputeIndirect) (struct gl_context *ctx, GLintptr indirect)
DrawAtlasBitmaps
void(* dd_function_table::DrawAtlasBitmaps) (struct gl_context *ctx, const struct gl_bitmap_atlas *atlas, GLuint count, const GLubyte *ids)
Called by display list code for optimized glCallLists/glBitmap rendering The driver must support texture rectangles of width 1024 or more.
Referenced by _mesa_GenLists(), and render_bitmap_atlas().
DrawBuffer
void(* dd_function_table::DrawBuffer) (struct gl_context *ctx, GLenum buffer)
Specify the current buffer for writing.
Referenced by draw_buffer(), and draw_buffers().
DrawBuffers
void(* dd_function_table::DrawBuffers) (struct gl_context *ctx, GLsizei n, const GLenum *buffers)
Specify the buffers for writing for fragment programs.
Referenced by draw_buffer(), and draw_buffers().
DrawPixels
void(* dd_function_table::DrawPixels) (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Called by glDrawPixels().
unpack describes how to unpack the source image data.
DrawTex
void(* dd_function_table::DrawTex) (struct gl_context *ctx, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
Referenced by draw_texture().
EGLImageTargetRenderbufferStorage
void(* dd_function_table::EGLImageTargetRenderbufferStorage) (struct gl_context *ctx, struct gl_renderbuffer *rb, void *image_handle)
EGLImageTargetTexture2D
void(* dd_function_table::EGLImageTargetTexture2D) (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLeglImageOES image_handle)
Referenced by _mesa_EGLImageTargetTexture2DOES().
EmitStringMarker
void(* dd_function_table::EmitStringMarker) (struct gl_context *ctx, const GLchar *string, GLsizei len)
Enable
void(* dd_function_table::Enable) (struct gl_context *ctx, GLenum cap, GLboolean state)
Enable or disable server-side gl capabilities.
Referenced by _mesa_set_enable(), _mesa_set_framebuffer_srgb(), _mesa_set_multisample(), and client_state().
EndConditionalRender
void(* dd_function_table::EndConditionalRender) (struct gl_context *ctx, struct gl_query_object *q)
EndPerfMonitor
void(* dd_function_table::EndPerfMonitor) (struct gl_context *ctx, struct gl_perf_monitor_object *m)
EndPerfQuery
void(* dd_function_table::EndPerfQuery) (struct gl_context *ctx, struct gl_perf_query_object *obj)
EndQuery
void(* dd_function_table::EndQuery) (struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_init_query_object_functions().
EndTransformFeedback
void(* dd_function_table::EndTransformFeedback) (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
FenceSync
void(* dd_function_table::FenceSync) (struct gl_context *, struct gl_sync_object *, GLenum, GLbitfield)
Referenced by _mesa_init_sync_object_functions().
Finish
void(* dd_function_table::Finish) (struct gl_context *ctx)
This is called whenever glFinish() is called.
Referenced by _mesa_finish().
FinishRenderTexture
void(* dd_function_table::FinishRenderTexture) (struct gl_context *ctx, struct gl_renderbuffer *rb)
Referenced by _mesa_update_texture_renderbuffer(), check_end_texture_render(), remove_attachment(), and set_texture_attachment().
Flush
void(* dd_function_table::Flush) (struct gl_context *ctx)
This is called whenever glFlush() is called.
Referenced by _mesa_flush(), and _mesa_notifySwapBuffers().
FlushMappedBufferRange
void(* dd_function_table::FlushMappedBufferRange) (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj, gl_map_buffer_index index)
Referenced by _mesa_flush_mapped_buffer_range(), and _mesa_init_buffer_object_functions().
Fogfv
void(* dd_function_table::Fogfv) (struct gl_context *ctx, GLenum pname, const GLfloat *params)
Specify fog parameters.
FramebufferRenderbuffer
void(* dd_function_table::FramebufferRenderbuffer) (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
Referenced by _mesa_framebuffer_renderbuffer().
FreeTextureImageBuffer
void(* dd_function_table::FreeTextureImageBuffer) (struct gl_context *ctx, struct gl_texture_image *texImage)
Free the memory for a single texture image.
Referenced by _mesa_clear_texture_image(), _mesa_delete_texture_image(), _mesa_EGLImageTargetTexture2DOES(), _mesa_initialize_context(), copyteximage(), prepare_mipmap_level(), teximage(), and texture_image_multisample().
FrontFace
void(* dd_function_table::FrontFace) (struct gl_context *ctx, GLenum mode)
Define front- and back-facing polygons.
GenerateMipmap
void(* dd_function_table::GenerateMipmap) (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Called by glGenerateMipmap() or when GL_GENERATE_MIPMAP_SGIS is enabled.
Note that if the texture is a cube map, the <target> parameter will indicate which cube face to generate (GL_POSITIVE/NEGATIVE_X/Y/Z). texObj->BaseLevel is the level from which to generate the remaining mipmap levels.
Referenced by _mesa_generate_texture_mipmap(), and check_gen_mipmap().
GetBufferSubData
void(* dd_function_table::GetBufferSubData) (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions().
GetCompressedTexSubImage
void(* dd_function_table::GetCompressedTexSubImage) (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLvoid *data)
Called by glGetCompressedTexImage.
Referenced by get_compressed_texture_image().
GetGraphicsResetStatus
GLenum(* dd_function_table::GetGraphicsResetStatus) (struct gl_context *ctx)
Query reset status for GL_ARB_robustness.
Per glGetGraphicsResetStatusARB, this function should return a non-zero value once after a reset. If a reset is non-atomic, the non-zero status should be returned for the duration of the reset.
GetPerfCounterInfo
void(* dd_function_table::GetPerfCounterInfo) (struct gl_context *ctx, unsigned queryIndex, unsigned counterIndex, const char **name, const char **desc, GLuint *offset, GLuint *data_size, GLuint *type_enum, GLuint *data_type_enum, GLuint64 *raw_max)
GetPerfMonitorResult
void(* dd_function_table::GetPerfMonitorResult) (struct gl_context *ctx, struct gl_perf_monitor_object *m, GLsizei dataSize, GLuint *data, GLint *bytesWritten)
GetPerfQueryData
void(* dd_function_table::GetPerfQueryData) (struct gl_context *ctx, struct gl_perf_query_object *obj, GLsizei dataSize, GLuint *data, GLuint *bytesWritten)
GetPerfQueryInfo
void(* dd_function_table::GetPerfQueryInfo) (struct gl_context *ctx, unsigned queryIndex, const char **name, GLuint *dataSize, GLuint *numCounters, GLuint *numActive)
GetSamplePosition
void(* dd_function_table::GetSamplePosition) (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint index, GLfloat *outValue)
GetString
const GLubyte*(* dd_function_table::GetString) (struct gl_context *ctx, GLenum name)
Return a string as needed by glGetString().
Only the GL_RENDERER query must be implemented. Otherwise, NULL can be returned.
GetTexSubImage
void(* dd_function_table::GetTexSubImage) (struct gl_context *ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
Called by glGetTexImage(), glGetTextureSubImage().
Referenced by generate_mipmap_compressed(), and get_texture_image().
GetTimestamp
uint64_t(* dd_function_table::GetTimestamp) (struct gl_context *ctx)
Referenced by find_custom_value().
GetTransformFeedbackVertexCount
GLsizei(* dd_function_table::GetTransformFeedbackVertexCount) (struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint stream)
Return the number of vertices written to a stream during the last Begin/EndTransformFeedback block.
InitPerfMonitorGroups
void(* dd_function_table::InitPerfMonitorGroups) (struct gl_context *ctx)
Referenced by init_groups().
InitPerfQueryInfo
unsigned(* dd_function_table::InitPerfQueryInfo) (struct gl_context *ctx)
Referenced by init_performance_query_info().
InvalidateBufferSubData
void(* dd_function_table::InvalidateBufferSubData) (struct gl_context *ctx, struct gl_buffer_object *obj, GLintptr offset, GLsizeiptr length)
IsPerfMonitorResultAvailable
GLboolean(* dd_function_table::IsPerfMonitorResultAvailable) (struct gl_context *ctx, struct gl_perf_monitor_object *m)
IsPerfQueryReady
bool(* dd_function_table::IsPerfQueryReady) (struct gl_context *ctx, struct gl_perf_query_object *obj)
IsProgramNative
GLboolean(* dd_function_table::IsProgramNative) (struct gl_context *ctx, GLenum target, struct gl_program *prog)
Query if program can be loaded onto hardware.
Lightfv
void(* dd_function_table::Lightfv) (struct gl_context *ctx, GLenum light, GLenum pname, const GLfloat *params)
Set light source parameters.
Note: for GL_POSITION and GL_SPOT_DIRECTION, params will have already been transformed to eye-space.
Referenced by _mesa_light().
LightingSpaceChange
void(* dd_function_table::LightingSpaceChange) (struct gl_context *ctx)
Notify driver that the special derived value _NeedEyeCoords has changed.
Referenced by _mesa_update_tnl_spaces().
LightModelfv
void(* dd_function_table::LightModelfv) (struct gl_context *ctx, GLenum pname, const GLfloat *params)
Set the lighting model parameters.
LineStipple
void(* dd_function_table::LineStipple) (struct gl_context *ctx, GLint factor, GLushort pattern)
Specify the line stipple pattern.
LineWidth
void(* dd_function_table::LineWidth) (struct gl_context *ctx, GLfloat width)
Specify the width of rasterized lines.
LinkShader
GLboolean(* dd_function_table::LinkShader) (struct gl_context *ctx, struct gl_shader_program *shader)
Called when a shader program is linked.
This gives drivers an opportunity to clone the IR and make their own transformations on it for the purposes of code generation.
Referenced by _mesa_init_shader_object_functions().
LogicOpcode
void(* dd_function_table::LogicOpcode) (struct gl_context *ctx, GLenum opcode)
Specify a logical pixel operation for color index rendering.
MapBufferRange
void*(* dd_function_table::MapBufferRange) (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *obj, gl_map_buffer_index index)
Referenced by _ae_map_vbos(), _mesa_ClearBufferSubData_sw(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetTexSubImage_sw(), _mesa_init_buffer_object_functions(), _mesa_map_buffer_range(), _mesa_map_pbo_dest(), _mesa_map_pbo_source(), _mesa_validate_pbo_compressed_teximage(), _mesa_validate_pbo_teximage(), copy_buffer_sub_data_fallback(), and unpack_image().
MapRenderbuffer
void(* dd_function_table::MapRenderbuffer) (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a renderbuffer into user space.
Parameters
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT and GL_MAP_INVALIDATE_RANGE_BIT (if writing)
Referenced by _mesa_clear_accum_buffer(), accum_or_load(), accum_return(), accum_scale_or_bias(), fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), read_depth_pixels(), read_rgba_pixels(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), and slow_read_depth_stencil_pixels_separate().
MapTextureImage
void(* dd_function_table::MapTextureImage) (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a slice of a texture image into user space.
Note: for GL_TEXTURE_1D_ARRAY, height must be 1, y must be 0 and slice indicates the 1D array index.
Parameters
texImage the texture image
slice the 3D image slice or array texture slice
x,y,w,h region of interest
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT and GL_MAP_INVALIDATE_RANGE_BIT (if writing)
mapOut returns start of mapping of region of interest
rowStrideOut returns row stride (in bytes). In the case of a compressed texture, this is the byte stride between one row of blocks and another.
Referenced by _mesa_GetCompressedTexSubImage_sw(), _mesa_print_texture(), _mesa_store_cleartexsubimage(), _mesa_store_compressed_texsubimage(), build_bitmap_atlas(), generate_mipmap_uncompressed(), get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_stencil(), get_tex_ycbcr(), and store_texsubimage().
MemoryBarrier
void(* dd_function_table::MemoryBarrier) (struct gl_context *ctx, GLbitfield barriers)
NeedFlush
GLbitfield dd_function_table::NeedFlush
Set by the driver-supplied T&L engine whenever vertices are buffered between glBegin()/glEnd() objects or __struct gl_contextRec::Current is not updated.
A bitmask of the FLUSH_x values above.
The dd_function_table::FlushVertices call below may be used to resolve these conditions.
NewATIfs
struct gl_program*(* dd_function_table::NewATIfs) (struct gl_context *ctx, struct ati_fragment_shader *curProg)
Allocate a program to associate with the new ATI fragment shader (optional)
NewBufferObject
struct gl_buffer_object*(* dd_function_table::NewBufferObject) (struct gl_context *ctx, GLuint buffer)
Referenced by _mesa_alloc_shared_state(), _mesa_handle_bind_buffer_gen(), and _mesa_init_buffer_object_functions().
NewFramebuffer
struct gl_framebuffer*(* dd_function_table::NewFramebuffer) (struct gl_context *ctx, GLuint name)
NewPerfMonitor
struct gl_perf_monitor_object*(* dd_function_table::NewPerfMonitor) (struct gl_context *ctx)
Referenced by new_performance_monitor().
NewPerfQueryObject
struct gl_perf_query_object*(* dd_function_table::NewPerfQueryObject) (struct gl_context *ctx, unsigned queryIndex)
NewProgram
struct gl_program*(* dd_function_table::NewProgram) (struct gl_context *ctx, GLenum target, GLuint id, bool is_arb_asm)
Allocate a new program.
Referenced by _mesa_alloc_shared_state(), and _mesa_get_fixed_func_vertex_program().
NewQueryObject
struct gl_query_object*(* dd_function_table::NewQueryObject) (struct gl_context *ctx, GLuint id)
Referenced by _mesa_init_query_object_functions(), and create_queries().
NewRenderbuffer
struct gl_renderbuffer*(* dd_function_table::NewRenderbuffer) (struct gl_context *ctx, GLuint name)
Referenced by _mesa_update_texture_renderbuffer(), and allocate_renderbuffer_locked().
NewSamplerObject
struct gl_sampler_object*(* dd_function_table::NewSamplerObject) (struct gl_context *ctx, GLuint name)
Referenced by _mesa_init_sampler_object_functions(), and create_samplers().
NewSyncObject
struct gl_sync_object*(* dd_function_table::NewSyncObject) (struct gl_context *, GLenum)
Referenced by _mesa_init_sync_object_functions().
NewTextureImage
struct gl_texture_image*(* dd_function_table::NewTextureImage) (struct gl_context *ctx)
Called to allocate a new texture image object.
Referenced by _mesa_get_tex_image(), and get_proxy_tex_image().
NewTextureObject
struct gl_texture_object*(* dd_function_table::NewTextureObject) (struct gl_context *ctx, GLuint name, GLenum target)
Called to allocate a new texture object.
Drivers will usually allocate/return a subclass of gl_texture_object.
Referenced by _mesa_alloc_shared_state(), _mesa_get_fallback_texture(), _mesa_initialize_context(), alloc_proxy_textures(), build_bitmap_atlas(), and create_textures().
NewTransformFeedback
struct gl_transform_feedback_object*(* dd_function_table::NewTransformFeedback) (struct gl_context *ctx, GLuint name)
Referenced by _mesa_free_transform_feedback(), _mesa_init_transform_feedback(), _mesa_init_transform_feedback_functions(), and create_transform_feedbacks().
PauseTransformFeedback
void(* dd_function_table::PauseTransformFeedback) (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
PointParameterfv
void(* dd_function_table::PointParameterfv) (struct gl_context *ctx, GLenum pname, const GLfloat *params)
PointSize
void(* dd_function_table::PointSize) (struct gl_context *ctx, GLfloat size)
Specify the diameter of rasterized points.
PolygonMode
void(* dd_function_table::PolygonMode) (struct gl_context *ctx, GLenum face, GLenum mode)
Select a polygon rasterization mode.
PolygonOffset
void(* dd_function_table::PolygonOffset) (struct gl_context *ctx, GLfloat factor, GLfloat units, GLfloat clamp)
Set the scale and units used to calculate depth values.
Referenced by _mesa_polygon_offset_clamp().
PolygonStipple
void(* dd_function_table::PolygonStipple) (struct gl_context *ctx, const GLubyte *mask)
Set the polygon stippling pattern.
ProgramStringNotify
GLboolean(* dd_function_table::ProgramStringNotify) (struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that a program string (and GPU code) has been specified or modified.
Return GL_TRUE or GL_FALSE to indicate if the program is supported by the driver.
Referenced by _mesa_get_fixed_func_vertex_program().
QueryCounter
void(* dd_function_table::QueryCounter) (struct gl_context *ctx, struct gl_query_object *q)
QueryInternalFormat
void(* dd_function_table::QueryInternalFormat) (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLenum pname, GLint *params)
Queries different driver parameters for a particular target and format.
Since ARB_internalformat_query2 introduced several new query parameters over ARB_internalformat_query, having one driver hook for each parameter is no longer feasible. So this is the generic entry-point for calls to glGetInternalFormativ and glGetInternalFormati64v, after Mesa has checked errors and default values.
Parameters
ctx GL context
target GL target enum
internalFormat GL format enum
pname GL enum that specifies the info to query.
params Buffer to hold the result of the query.
Referenced by _is_internalformat_supported(), and _mesa_check_sample_count().
QueryMemoryInfo
void(* dd_function_table::QueryMemoryInfo) (struct gl_context *ctx, struct gl_memory_info *info)
Query information about memory.
Device memory is e.g. VRAM. Staging memory is e.g. GART. All sizes are in kilobytes.
Referenced by find_custom_value().
RasterPos
void(* dd_function_table::RasterPos) (struct gl_context *ctx, const GLfloat v[4])
Execute glRasterPos, updating the ctx->Current.Raster fields.
ReadBuffer
void(* dd_function_table::ReadBuffer) (struct gl_context *ctx, GLenum buffer)
Referenced by read_buffer().
ReadPixels
void(* dd_function_table::ReadPixels) (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, GLvoid *dest)
Called by glReadPixels().
RenderMode
void(* dd_function_table::RenderMode) (struct gl_context *ctx, GLenum mode)
Set rasterization mode.
RenderObjectPurgeable
GLenum(* dd_function_table::RenderObjectPurgeable) (struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
Referenced by renderbuffer_purgeable().
RenderObjectUnpurgeable
GLenum(* dd_function_table::RenderObjectUnpurgeable) (struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
Referenced by renderbuffer_unpurgeable().
RenderTexture
void(* dd_function_table::RenderTexture) (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Referenced by _mesa_update_texture_renderbuffer(), and check_begin_texture_render().
ResetPerfMonitor
void(* dd_function_table::ResetPerfMonitor) (struct gl_context *ctx, struct gl_perf_monitor_object *m)
Stop an active performance monitor, discarding results.
ResumeTransformFeedback
void(* dd_function_table::ResumeTransformFeedback) (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
SamplerUniformChange
void(* dd_function_table::SamplerUniformChange) (struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that the sampler uniforms for the current program have changed.
On some drivers, this may require shader recompiles.
SaveNeedFlush
GLboolean dd_function_table::SaveNeedFlush
Need to call vbo_save_SaveFlushVertices() upon state change?
Scissor
void(* dd_function_table::Scissor) (struct gl_context *ctx)
Define the scissor box.
Referenced by _mesa_set_scissor().
ServerWaitSync
void(* dd_function_table::ServerWaitSync) (struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
Referenced by _mesa_init_sync_object_functions().
SetBackgroundContext
void(* dd_function_table::SetBackgroundContext) (struct gl_context *ctx)
Indicate that this thread is being used by Mesa as a background drawing thread for the given GL context.
If this function is called more than once from any given thread, each subsequent call overrides the context that was passed in the previous call. Mesa takes advantage of this to re-use a background thread to perform drawing on behalf of multiple contexts.
Mesa may sometimes call this function from a non-background thread (i.e. a thread that has already been bound to a context using __DriverAPIRec::MakeCurrent()); when this happens, ctx will be equal to the context that is bound to this thread.
Mesa will only call this function if GL multithreading is enabled.
SetTextureStorageForBufferObject
bool(* dd_function_table::SetTextureStorageForBufferObject) (struct gl_context *ctx, struct gl_texture_object *texObj, struct gl_buffer_object *bufferObj, uint32_t buffer_offset, uint32_t row_stride, bool read_only)
Sets the given buffer object as the texture's storage.
The given texture must have target GL_TEXTURE_1D, GL_TEXTURE_2D, GL_TEXTURE_RECTANGLE, and GL_TEXTURE_2D_ARRAY; have only a single mipmap level; be immutable; and must not have any assigned storage. The format and dimensions of the gl_texture_object will already be initialized.
This function is used by the meta PBO texture upload path.
ShadeModel
void(* dd_function_table::ShadeModel) (struct gl_context *ctx, GLenum mode)
Select flat or smooth shading.
StencilFuncSeparate
void(* dd_function_table::StencilFuncSeparate) (struct gl_context *ctx, GLenum face, GLenum func, GLint ref, GLuint mask)
OpenGL 2.0 two-sided StencilFunc.
StencilMaskSeparate
void(* dd_function_table::StencilMaskSeparate) (struct gl_context *ctx, GLenum face, GLuint mask)
OpenGL 2.0 two-sided StencilMask.
StencilOpSeparate
void(* dd_function_table::StencilOpSeparate) (struct gl_context *ctx, GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
OpenGL 2.0 two-sided StencilOp.
StoreQueryResult
void(* dd_function_table::StoreQueryResult) (struct gl_context *ctx, struct gl_query_object *q, struct gl_buffer_object *buf, intptr_t offset, GLenum pname, GLenum ptype)
Referenced by get_query_object().
TestProxyTexImage
GLboolean(* dd_function_table::TestProxyTexImage) (struct gl_context *ctx, GLenum target, GLuint numLevels, GLint level, mesa_format format, GLuint numSamples, GLint width, GLint height, GLint depth)
Called by glTexImage, glCompressedTexImage, glCopyTexImage and glTexStorage to check if the dimensions of the texture image are too large.
Parameters
target any GL_PROXY_TEXTURE_x target
Returns
GL_TRUE if the image is OK, GL_FALSE if too large
Referenced by _mesa_texture_storage(), copyteximage(), teximage(), and texture_image_multisample().
TexEnv
void(* dd_function_table::TexEnv) (struct gl_context *ctx, GLenum target, GLenum pname, const GLfloat *param)
Set texture environment parameters.
TexGen
void(* dd_function_table::TexGen) (struct gl_context *ctx, GLenum coord, GLenum pname, const GLfloat *params)
Control the generation of texture coordinates.
Referenced by pop_texture_group().
TexImage
void(* dd_function_table::TexImage) (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexImage[123]D() and glCopyTexImage[12]D() Allocate texture memory and copy the user's image to the buffer.
The gl_texture_image fields, etc. will be fully initialized. The parameters are the same as glTexImage3D(), plus:
Parameters
dims 1, 2, or 3 indicating glTexImage1/2/3D()
packing describes how to unpack the source data.
texImage is the destination texture image.
Referenced by _mesa_get_fallback_texture(), and teximage().
TexParameter
void(* dd_function_table::TexParameter) (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname)
Set texture parameter (callee gets param value from the texObj)
Referenced by _mesa_texture_parameterf(), _mesa_texture_parameterfv(), _mesa_texture_parameteri(), _mesa_texture_parameteriv(), finish_texture_init(), and texture_buffer_range().
TexSubImage
void(* dd_function_table::TexSubImage) (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexSubImage[123]D().
Replace a subset of the target texture with new texel data.
Referenced by _mesa_texture_sub_image(), and generate_mipmap_compressed().
TextureBarrier
void(* dd_function_table::TextureBarrier) (struct gl_context *ctx)
Referenced by _mesa_init_barrier_functions().
TextureObjectPurgeable
GLenum(* dd_function_table::TextureObjectPurgeable) (struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
Referenced by texture_object_purgeable().
TextureObjectUnpurgeable
GLenum(* dd_function_table::TextureObjectUnpurgeable) (struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
Referenced by texture_object_unpurgeable().
TextureView
GLboolean(* dd_function_table::TextureView) (struct gl_context *ctx, struct gl_texture_object *texObj, struct gl_texture_object *origTexObj)
Called as part of glTextureView to add views to origTexObj.
UnmapBuffer
GLboolean(* dd_function_table::UnmapBuffer) (struct gl_context *ctx, struct gl_buffer_object *obj, gl_map_buffer_index index)
Referenced by _ae_unmap_vbos(), _mesa_buffer_unmap_all_mappings(), _mesa_ClearBufferSubData_sw(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetTexSubImage_sw(), _mesa_init_buffer_object_functions(), _mesa_unmap_buffer(), _mesa_unmap_pbo_dest(), _mesa_unmap_pbo_source(), _mesa_unmap_teximage_pbo(), copy_buffer_sub_data_fallback(), and unpack_image().
UnmapRenderbuffer
void(* dd_function_table::UnmapRenderbuffer) (struct gl_context *ctx, struct gl_renderbuffer *rb)
Referenced by _mesa_clear_accum_buffer(), accum_or_load(), accum_return(), accum_scale_or_bias(), fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), read_depth_pixels(), read_rgba_pixels(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), and slow_read_depth_stencil_pixels_separate().
UnmapTextureImage
void(* dd_function_table::UnmapTextureImage) (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice)
Referenced by _mesa_GetCompressedTexSubImage_sw(), _mesa_print_texture(), _mesa_store_cleartexsubimage(), _mesa_store_compressed_texsubimage(), build_bitmap_atlas(), generate_mipmap_uncompressed(), get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_stencil(), get_tex_ycbcr(), and store_texsubimage().
UpdateState
void(* dd_function_table::UpdateState) (struct gl_context *ctx, GLbitfield new_state)
Notify the driver after Mesa has made some internal state changes.
This is in addition to any state change callbacks Mesa may already have made.
Referenced by _mesa_update_state_locked().
ValidateFramebuffer
void(* dd_function_table::ValidateFramebuffer) (struct gl_context *ctx, struct gl_framebuffer *fb)
Referenced by _mesa_test_framebuffer_completeness().
VDPAUMapSurface
void(* dd_function_table::VDPAUMapSurface) (struct gl_context *ctx, GLenum target, GLenum access, GLboolean output, struct gl_texture_object *texObj, struct gl_texture_image *texImage, const GLvoid *vdpSurface, GLuint index)
VDPAUUnmapSurface
void(* dd_function_table::VDPAUUnmapSurface) (struct gl_context *ctx, GLenum target, GLenum access, GLboolean output, struct gl_texture_object *texObj, struct gl_texture_image *texImage, const GLvoid *vdpSurface, GLuint index)
Viewport
void(* dd_function_table::Viewport) (struct gl_context *ctx)
Set the viewport.
Referenced by _mesa_set_viewport().
WaitPerfQuery
void(* dd_function_table::WaitPerfQuery) (struct gl_context *ctx, struct gl_perf_query_object *obj)
WaitQuery
void(* dd_function_table::WaitQuery) (struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_check_conditional_render(), _mesa_init_query_object_functions(), and get_query_object().
The documentation for this struct was generated from the following file:
dd.h