Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
gl_list_instruction Struct Reference
Other parts of Mesa (such as the VBO module) can plug into the display list system.
Data Fields
GLuint Size
void(* Execute)(struct gl_context *ctx, void *data)
void(* Destroy)(struct gl_context *ctx, void *data)
void(* Print)(struct gl_context *ctx, void *data, FILE *f)
Detailed Description
Other parts of Mesa (such as the VBO module) can plug into the display list system.
This structure describes new display list instructions.
Field Documentation
Destroy
void(* gl_list_instruction::Destroy) (struct gl_context *ctx, void *data)
Referenced by _mesa_dlist_alloc_opcode(), and ext_opcode_destroy().
Execute
void(* gl_list_instruction::Execute) (struct gl_context *ctx, void *data)
Referenced by _mesa_dlist_alloc_opcode(), and ext_opcode_execute().
Print
void(* gl_list_instruction::Print) (struct gl_context *ctx, void *data, FILE *f)
Referenced by _mesa_dlist_alloc_opcode(), and ext_opcode_print().
Size
GLuint gl_list_instruction::Size
Referenced by _mesa_dlist_alloc_opcode(), ext_opcode_destroy(), ext_opcode_execute(), and ext_opcode_print().
The documentation for this struct was generated from the following file:
dlist.c