Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
syncobj.c File Reference
Sync object management.
#include <inttypes.h>
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "macros.h"
#include "get.h"
#include "dispatch.h"
#include "mtypes.h"
#include "util/hash_table.h"
#include "util/set.h"
#include "syncobj.h"
Functions
static struct gl_sync_object * _mesa_new_sync_object (struct gl_context *ctx, GLenum type)
static void _mesa_delete_sync_object (struct gl_context *ctx, struct gl_sync_object *syncObj)
static void _mesa_fence_sync (struct gl_context *ctx, struct gl_sync_object *syncObj, GLenum condition, GLbitfield flags)
static void _mesa_check_sync (struct gl_context *ctx, struct gl_sync_object *syncObj)
static void _mesa_wait_sync (struct gl_context *ctx, struct gl_sync_object *syncObj, GLbitfield flags, GLuint64 timeout)
void _mesa_init_sync_object_functions (struct dd_function_table *driver)
void _mesa_init_sync (struct gl_context *ctx)
Allocate/init the context state related to sync objects.
void _mesa_free_sync_data (struct gl_context *ctx)
Free the context state related to sync objects.
struct gl_sync_object * _mesa_get_and_ref_sync (struct gl_context *ctx, GLsync sync, bool incRefCount)
Check if the given sync object is:
void _mesa_unref_sync_object (struct gl_context *ctx, struct gl_sync_object *syncObj, int amount)
GLboolean GLAPIENTRY _mesa_IsSync (GLsync sync)
void GLAPIENTRY _mesa_DeleteSync (GLsync sync)
GLsync GLAPIENTRY _mesa_FenceSync (GLenum condition, GLbitfield flags)
GLenum GLAPIENTRY _mesa_ClientWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
void GLAPIENTRY _mesa_WaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
void GLAPIENTRY _mesa_GetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values)
Detailed Description
Sync object management.
Unlike textures and other objects that are shared between contexts, sync objects are not bound to the context. As a result, the reference counting and delete behavior of sync objects is slightly different. References to sync objects are added:
By glFencSynce. This sets the initial reference count to 1.
At the start of glClientWaitSync. The reference is held for the duration of the wait call.
References are removed:
By glDeleteSync.
At the end of glClientWaitSync.
Additionally, drivers may call _mesa_ref_sync_object and _mesa_unref_sync_object as needed to implement ServerWaitSync.
As with shader objects, sync object names become invalid as soon as glDeleteSync is called. For this reason glDeleteSync sets the DeletePending flag. All functions validate object handles by testing this flag.
Note
Only GL_ARB_sync objects are shared between contexts. If support is ever added for either GL_NV_fence or GL_APPLE_fence different semantics will need to be implemented.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
_mesa_check_sync()
static void _mesa_check_sync (struct gl_context * ctx, struct gl_sync_object * syncObj) static
References void.
Referenced by _mesa_init_sync_object_functions().
_mesa_ClientWaitSync()
GLenum GLAPIENTRY _mesa_ClientWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_sync_object::StatusFlag.
_mesa_delete_sync_object()
static void _mesa_delete_sync_object (struct gl_context * ctx, struct gl_sync_object * syncObj) static
References gl_sync_object::Label, and void.
Referenced by _mesa_init_sync_object_functions().
_mesa_DeleteSync()
void GLAPIENTRY _mesa_DeleteSync (GLsync sync)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), gl_sync_object::DeletePending, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_fence_sync()
static void _mesa_fence_sync (struct gl_context * ctx, struct gl_sync_object * syncObj, GLenum condition, GLbitfield flags) static
References gl_sync_object::StatusFlag, and void.
Referenced by _mesa_init_sync_object_functions().
_mesa_FenceSync()
GLsync GLAPIENTRY _mesa_FenceSync (GLenum condition, GLbitfield flags)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_sync_object::DeletePending, gl_sync_object::Flags, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_sync_object::Name, gl_sync_object::RefCount, gl_sync_object::StatusFlag, gl_sync_object::SyncCondition, and gl_sync_object::Type.
_mesa_free_sync_data()
void _mesa_free_sync_data (struct gl_context * ctx)
Free the context state related to sync objects.
References void.
Referenced by _mesa_free_context_data().
_mesa_get_and_ref_sync()
struct gl_sync_object* _mesa_get_and_ref_sync (struct gl_context * ctx, GLsync sync, bool incRefCount)
Check if the given sync object is:
non-null
not in sync objects hash table
type is GL_SYNC_FENCE
not marked as deleted
Returns the internal gl_sync_object pointer if the sync object is valid or NULL if it isn't.
If "incRefCount" is true, the reference count is incremented, which is normally what you want; otherwise, a glDeleteSync from another thread could delete the sync object while you are still working on it.
References gl_sync_object::DeletePending, gl_shared_state::Mutex, gl_sync_object::RefCount, gl_context::Shared, gl_shared_state::SyncObjects, and gl_sync_object::Type.
Referenced by _mesa_ClientWaitSync(), _mesa_DeleteSync(), _mesa_GetObjectPtrLabel(), _mesa_GetSynciv(), _mesa_IsSync(), _mesa_ObjectPtrLabel(), and _mesa_WaitSync().
_mesa_GetSynciv()
void GLAPIENTRY _mesa_GetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), gl_sync_object::Flags, GET_CURRENT_CONTEXT, gl_sync_object::StatusFlag, gl_sync_object::SyncCondition, and gl_sync_object::Type.
_mesa_init_sync()
void _mesa_init_sync (struct gl_context * ctx)
Allocate/init the context state related to sync objects.
References void.
Referenced by init_attrib_groups().
_mesa_init_sync_object_functions()
void _mesa_init_sync_object_functions (struct dd_function_table * driver)
References _mesa_check_sync(), _mesa_delete_sync_object(), _mesa_fence_sync(), _mesa_new_sync_object(), _mesa_wait_sync(), dd_function_table::CheckSync, dd_function_table::ClientWaitSync, dd_function_table::DeleteSyncObject, dd_function_table::FenceSync, dd_function_table::NewSyncObject, and dd_function_table::ServerWaitSync.
_mesa_IsSync()
GLboolean GLAPIENTRY _mesa_IsSync (GLsync sync)
References _mesa_get_and_ref_sync(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_new_sync_object()
static struct gl_sync_object* _mesa_new_sync_object (struct gl_context * ctx, GLenum type) static
References CALLOC_STRUCT, and void.
Referenced by _mesa_init_sync_object_functions().
_mesa_unref_sync_object()
void _mesa_unref_sync_object (struct gl_context * ctx, struct gl_sync_object * syncObj, int amount)
References dd_function_table::DeleteSyncObject, gl_context::Driver, GLAPIENTRY, gl_shared_state::Mutex, gl_sync_object::RefCount, gl_context::Shared, and gl_shared_state::SyncObjects.
Referenced by _mesa_ClientWaitSync(), _mesa_DeleteSync(), _mesa_GetObjectPtrLabel(), _mesa_GetSynciv(), _mesa_ObjectPtrLabel(), _mesa_WaitSync(), and free_shared_state().
_mesa_wait_sync()
static void _mesa_wait_sync (struct gl_context * ctx, struct gl_sync_object * syncObj, GLbitfield flags, GLuint64 timeout) static
References void.
Referenced by _mesa_init_sync_object_functions().
_mesa_WaitSync()
void GLAPIENTRY _mesa_WaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), GET_CURRENT_CONTEXT, and GLAPIENTRY.