Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
syncobj.h File Reference
Sync object management.
#include "glheader.h"
Functions
void _mesa_init_sync_object_functions (struct dd_function_table *driver)
void _mesa_init_sync (struct gl_context *)
Allocate/init the context state related to sync objects.
void _mesa_free_sync_data (struct gl_context *)
Free the context state related to sync objects.
struct gl_sync_object * _mesa_get_and_ref_sync (struct gl_context *ctx, GLsync sync, bool incRefCount)
Check if the given sync object is:
void _mesa_unref_sync_object (struct gl_context *ctx, struct gl_sync_object *syncObj, int amount)
GLboolean GLAPIENTRY _mesa_IsSync (GLsync sync)
void GLAPIENTRY _mesa_DeleteSync (GLsync sync)
GLsync GLAPIENTRY _mesa_FenceSync (GLenum condition, GLbitfield flags)
GLenum GLAPIENTRY _mesa_ClientWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
void GLAPIENTRY _mesa_WaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
void GLAPIENTRY _mesa_GetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values)
Detailed Description
Sync object management.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
_mesa_ClientWaitSync()
GLenum GLAPIENTRY _mesa_ClientWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_sync_object::StatusFlag.
_mesa_DeleteSync()
void GLAPIENTRY _mesa_DeleteSync (GLsync sync)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), gl_sync_object::DeletePending, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_FenceSync()
GLsync GLAPIENTRY _mesa_FenceSync (GLenum condition, GLbitfield flags)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_sync_object::DeletePending, gl_sync_object::Flags, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_sync_object::Name, gl_sync_object::RefCount, gl_sync_object::StatusFlag, gl_sync_object::SyncCondition, and gl_sync_object::Type.
_mesa_free_sync_data()
void _mesa_free_sync_data (struct gl_context *)
Free the context state related to sync objects.
References void.
Referenced by _mesa_free_context_data().
_mesa_get_and_ref_sync()
struct gl_sync_object* _mesa_get_and_ref_sync (struct gl_context * ctx, GLsync sync, bool incRefCount)
Check if the given sync object is:
non-null
not in sync objects hash table
type is GL_SYNC_FENCE
not marked as deleted
Returns the internal gl_sync_object pointer if the sync object is valid or NULL if it isn't.
If "incRefCount" is true, the reference count is incremented, which is normally what you want; otherwise, a glDeleteSync from another thread could delete the sync object while you are still working on it.
References gl_sync_object::DeletePending, gl_shared_state::Mutex, gl_sync_object::RefCount, gl_context::Shared, gl_shared_state::SyncObjects, and gl_sync_object::Type.
Referenced by _mesa_ClientWaitSync(), _mesa_DeleteSync(), _mesa_GetObjectPtrLabel(), _mesa_GetSynciv(), _mesa_IsSync(), _mesa_ObjectPtrLabel(), and _mesa_WaitSync().
_mesa_GetSynciv()
void GLAPIENTRY _mesa_GetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), gl_sync_object::Flags, GET_CURRENT_CONTEXT, gl_sync_object::StatusFlag, gl_sync_object::SyncCondition, and gl_sync_object::Type.
_mesa_init_sync()
void _mesa_init_sync (struct gl_context *)
Allocate/init the context state related to sync objects.
References void.
Referenced by init_attrib_groups().
_mesa_init_sync_object_functions()
void _mesa_init_sync_object_functions (struct dd_function_table * driver)
References _mesa_check_sync(), _mesa_delete_sync_object(), _mesa_fence_sync(), _mesa_new_sync_object(), _mesa_wait_sync(), dd_function_table::CheckSync, dd_function_table::ClientWaitSync, dd_function_table::DeleteSyncObject, dd_function_table::FenceSync, dd_function_table::NewSyncObject, and dd_function_table::ServerWaitSync.
_mesa_IsSync()
GLboolean GLAPIENTRY _mesa_IsSync (GLsync sync)
References _mesa_get_and_ref_sync(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_unref_sync_object()
void _mesa_unref_sync_object (struct gl_context * ctx, struct gl_sync_object * syncObj, int amount)
References dd_function_table::DeleteSyncObject, gl_context::Driver, GLAPIENTRY, gl_shared_state::Mutex, gl_sync_object::RefCount, gl_context::Shared, and gl_shared_state::SyncObjects.
Referenced by _mesa_ClientWaitSync(), _mesa_DeleteSync(), _mesa_GetObjectPtrLabel(), _mesa_GetSynciv(), _mesa_ObjectPtrLabel(), _mesa_WaitSync(), and free_shared_state().
_mesa_WaitSync()
void GLAPIENTRY _mesa_WaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout)
References _mesa_error(), _mesa_get_and_ref_sync(), _mesa_unref_sync_object(), GET_CURRENT_CONTEXT, and GLAPIENTRY.