Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_s3tc.h File Reference
#include "glheader.h"
#include "texstore.h"
#include "texcompress.h"
Functions
GLboolean _mesa_texstore_rgb_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_dxt1 format.
GLboolean _mesa_texstore_rgba_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt1 format.
GLboolean _mesa_texstore_rgba_dxt3 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt3 format.
GLboolean _mesa_texstore_rgba_dxt5 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt5 format.
void _mesa_init_texture_s3tc (struct gl_context *ctx)
compressed_fetch_func _mesa_get_dxt_fetch_func (mesa_format format)
Function Documentation
_mesa_get_dxt_fetch_func()
compressed_fetch_func _mesa_get_dxt_fetch_func (mesa_format format)
References fetch_rgb_dxt1(), fetch_rgba_dxt1(), fetch_rgba_dxt3(), fetch_rgba_dxt5(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), fetch_srgba_dxt5(), MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, and MESA_FORMAT_SRGBA_DXT5.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_init_texture_s3tc()
void _mesa_init_texture_s3tc (struct gl_context * ctx)
References _mesa_dlclose(), _mesa_dlopen(), _mesa_dlsym(), _mesa_warning(), dxtlibhandle, DXTN_LIBNAME, ext_tx_compress_dxtn, fetch_ext_rgb_dxt1, fetch_ext_rgba_dxt1, fetch_ext_rgba_dxt3, fetch_ext_rgba_dxt5, and gl_context::Mesa_DXTn.
Referenced by init_attrib_groups().
_mesa_texstore_rgb_dxt1()
GLboolean _mesa_texstore_rgb_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_dxt1 format.
References _mesa_image_address2d(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_UNORM8, and MESA_FORMAT_SRGB_DXT1.
Referenced by texstore_compressed().
_mesa_texstore_rgba_dxt1()
GLboolean _mesa_texstore_rgba_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt1 format.
References _mesa_image_address2d(), _mesa_little_endian(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_DXT1, and MESA_FORMAT_SRGBA_DXT1.
Referenced by texstore_compressed().
_mesa_texstore_rgba_dxt3()
GLboolean _mesa_texstore_rgba_dxt3 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt3 format.
References _mesa_image_address2d(), _mesa_little_endian(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_DXT3, and MESA_FORMAT_SRGBA_DXT3.
Referenced by texstore_compressed().
_mesa_texstore_rgba_dxt5()
GLboolean _mesa_texstore_rgba_dxt5 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt5 format.
References _mesa_image_address2d(), _mesa_little_endian(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_DXT5, and MESA_FORMAT_SRGBA_DXT5.
Referenced by texstore_compressed().