Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_etc_tmp.h File Reference
Functions
struct TAG (etc1_block)
static UINT8_TYPE TAG() etc1_base_color_diff_hi (UINT8_TYPE in)
static UINT8_TYPE TAG() etc1_base_color_diff_lo (UINT8_TYPE in)
static UINT8_TYPE TAG() etc1_base_color_ind_hi (UINT8_TYPE in)
static UINT8_TYPE TAG() etc1_base_color_ind_lo (UINT8_TYPE in)
static UINT8_TYPE TAG() etc1_clamp (UINT8_TYPE base, int modifier)
static const int TAG (etc1_modifier_tables)[8][4]
static void TAG() etc1_parse_block (struct TAG(etc1_block) *block, const UINT8_TYPE *src)
static void TAG() etc1_fetch_texel (const struct TAG(etc1_block) *block, int x, int y, UINT8_TYPE *dst)
static void etc1_unpack_rgba8888 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
Function Documentation
etc1_base_color_diff_hi()
static UINT8_TYPE TAG() etc1_base_color_diff_hi (UINT8_TYPE in) static
References UINT8_TYPE.
Referenced by etc1_parse_block(), and etc2_rgb8_parse_block().
etc1_base_color_diff_lo()
static UINT8_TYPE TAG() etc1_base_color_diff_lo (UINT8_TYPE in) static
References UINT8_TYPE.
Referenced by etc1_parse_block(), and etc2_rgb8_parse_block().
etc1_base_color_ind_hi()
static UINT8_TYPE TAG() etc1_base_color_ind_hi (UINT8_TYPE in) static
References UINT8_TYPE.
Referenced by etc1_parse_block(), and etc2_rgb8_parse_block().
etc1_base_color_ind_lo()
static UINT8_TYPE TAG() etc1_base_color_ind_lo (UINT8_TYPE in) static
References UINT8_TYPE.
Referenced by etc1_parse_block(), and etc2_rgb8_parse_block().
etc1_clamp()
static UINT8_TYPE TAG() etc1_clamp (UINT8_TYPE base, int modifier) static
References TAG(), and UINT8_TYPE.
Referenced by etc1_fetch_texel().
etc1_fetch_texel()
static void TAG() etc1_fetch_texel (const struct TAG(etc1_block) * block, int x, int y, UINT8_TYPE * dst) static
References etc1_clamp(), TAG(), UINT8_TYPE, and x.
Referenced by etc1_unpack_rgba8888(), and fetch_etc1_rgb8().
etc1_parse_block()
static void TAG() etc1_parse_block (struct TAG(etc1_block) * block, const UINT8_TYPE * src) static
References etc1_base_color_diff_hi(), etc1_base_color_diff_lo(), etc1_base_color_ind_hi(), etc1_base_color_ind_lo(), and TAG().
Referenced by etc1_unpack_rgba8888(), and fetch_etc1_rgb8().
etc1_unpack_rgba8888()
static void etc1_unpack_rgba8888 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc1_fetch_texel(), etc1_parse_block(), and x.
Referenced by _mesa_etc1_unpack_rgba8888().
TAG() [1/2]
static const int TAG (etc1_modifier_tables) static
TAG() [2/2]
struct TAG (etc1_block)
References UINT8_TYPE.
Referenced by etc1_clamp(), etc1_fetch_texel(), and etc1_parse_block().