Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_cpal.c File Reference
#include "glheader.h"
#include "context.h"
#include "mtypes.h"
#include "imports.h"
#include "pixelstore.h"
#include "texcompress_cpal.h"
#include "teximage.h"
Data Structures
struct cpal_format_info
Code to convert compressed/paletted texture images to ordinary images.
Functions
static GLuint get_palette_entry (const struct cpal_format_info *info, const GLubyte *palette, GLuint index, GLubyte *pixel)
Get a color/entry from the palette.
static void paletted_to_color (const struct cpal_format_info *info, const GLubyte *palette, const void *indices, GLuint num_pixels, GLubyte *image)
Convert paletted texture to color texture.
unsigned _mesa_cpal_compressed_size (int level, GLenum internalFormat, unsigned width, unsigned height)
void _mesa_cpal_compressed_teximage2d (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei imageSize, const void *palette)
Convert a call to glCompressedTexImage2D() where internalFormat is a compressed palette format into a regular GLubyte/RGBA glTexImage2D() call.
Variables
static const struct cpal_format_info formats []
Function Documentation
_mesa_cpal_compressed_size()
unsigned _mesa_cpal_compressed_size (int level, GLenum internalFormat, unsigned width, unsigned height)
References cpal_format_info::cpal_format, formats, cpal_format_info::palette_size, and cpal_format_info::size.
Referenced by compressed_texture_error_check().
_mesa_cpal_compressed_teximage2d()
void _mesa_cpal_compressed_teximage2d (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei imageSize, const void * palette)
Convert a call to glCompressedTexImage2D() where internalFormat is a compressed palette format into a regular GLubyte/RGBA glTexImage2D() call.
References _mesa_PixelStorei(), _mesa_TexImage2D(), for(), cpal_format_info::format, formats, GET_CURRENT_CONTEXT, GLuint, cpal_format_info::palette_size, paletted_to_color(), cpal_format_info::size, and cpal_format_info::type.
Referenced by teximage().
get_palette_entry()
static GLuint get_palette_entry (const struct cpal_format_info * info, const GLubyte * palette, GLuint index, GLubyte * pixel) static
Get a color/entry from the palette.
References cpal_format_info::size.
Referenced by paletted_to_color().
paletted_to_color()
static void paletted_to_color (const struct cpal_format_info * info, const GLubyte * palette, const void * indices, GLuint num_pixels, GLubyte * image) static
Convert paletted texture to color texture.
References get_palette_entry(), GLuint, and cpal_format_info::palette_size.
Referenced by _mesa_cpal_compressed_teximage2d().
Variable Documentation
formats
const struct cpal_format_info formats[] static
Initial value:
= {
   { GL_PALETTE4_RGB8_OES,     GL_RGB,  GL_UNSIGNED_BYTE,           16, 3 },
   { GL_PALETTE4_RGBA8_OES,    GL_RGBA, GL_UNSIGNED_BYTE,           16, 4 },
   { GL_PALETTE4_R5_G6_B5_OES, GL_RGB,  GL_UNSIGNED_SHORT_5_6_5,    16, 2 },
   { GL_PALETTE4_RGBA4_OES,    GL_RGBA, GL_UNSIGNED_SHORT_4_4_4_4,  16, 2 },
   { GL_PALETTE4_RGB5_A1_OES,  GL_RGBA, GL_UNSIGNED_SHORT_5_5_5_1,  16, 2 },
   { GL_PALETTE8_RGB8_OES,     GL_RGB,  GL_UNSIGNED_BYTE,          256, 3 },
   { GL_PALETTE8_RGBA8_OES,    GL_RGBA, GL_UNSIGNED_BYTE,          256, 4 },
   { GL_PALETTE8_R5_G6_B5_OES, GL_RGB,  GL_UNSIGNED_SHORT_5_6_5,   256, 2 },
   { GL_PALETTE8_RGBA4_OES,    GL_RGBA, GL_UNSIGNED_SHORT_4_4_4_4, 256, 2 },
   { GL_PALETTE8_RGB5_A1_OES,  GL_RGBA, GL_UNSIGNED_SHORT_5_5_5_1, 256, 2 }
}
Referenced by _mesa_cpal_compressed_size(), and _mesa_cpal_compressed_teximage2d().