Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_rgtc.c File Reference
GL_EXT_texture_compression_rgtc support.
#include "glheader.h"
#include "imports.h"
#include "image.h"
#include "macros.h"
#include "mipmap.h"
#include "texcompress.h"
#include "util/rgtc.h"
#include "texcompress_rgtc.h"
#include "texstore.h"
Functions
static void extractsrc_u (GLubyte srcpixels[4][4], const GLubyte *srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps)
static void extractsrc_s (GLbyte srcpixels[4][4], const GLfloat *srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps)
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
static void fetch_red_rgtc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_l_latc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_red_rgtc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_l_latc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rg_rgtc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_la_latc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_rg_rgtc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_la_latc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
compressed_fetch_func _mesa_get_compressed_rgtc_func (mesa_format format)
Detailed Description
GL_EXT_texture_compression_rgtc support.
Function Documentation
_mesa_get_compressed_rgtc_func()
compressed_fetch_func _mesa_get_compressed_rgtc_func (mesa_format format)
References fetch_l_latc1(), fetch_la_latc2(), fetch_red_rgtc1(), fetch_rg_rgtc2(), fetch_signed_l_latc1(), fetch_signed_la_latc2(), fetch_signed_red_rgtc1(), fetch_signed_rg_rgtc2(), MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_R_RGTC1_SNORM, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_RG_RGTC2_SNORM, and MESA_FORMAT_RG_RGTC2_UNORM.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_red_rgtc1()
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_texstore(), extractsrc_u(), MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_R_RGTC1_UNORM, and MESA_FORMAT_R_UNORM8.
Referenced by texstore_compressed().
_mesa_texstore_rg_rgtc2()
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_little_endian(), _mesa_texstore(), extractsrc_u(), MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_G8R8_UNORM, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_R8G8_UNORM, and MESA_FORMAT_RG_RGTC2_UNORM.
Referenced by texstore_compressed().
_mesa_texstore_signed_red_rgtc1()
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_texstore(), extractsrc_s(), MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_R_FLOAT32, and MESA_FORMAT_R_RGTC1_SNORM.
Referenced by texstore_compressed().
_mesa_texstore_signed_rg_rgtc2()
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_texstore(), extractsrc_s(), MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_RG_FLOAT32, and MESA_FORMAT_RG_RGTC2_SNORM.
Referenced by texstore_compressed().
extractsrc_s()
static void extractsrc_s (GLbyte srcpixels[4][4], const GLfloat * srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps) static
References FLOAT_TO_BYTE_TEX.
Referenced by _mesa_texstore_signed_red_rgtc1(), and _mesa_texstore_signed_rg_rgtc2().
extractsrc_u()
static void extractsrc_u (GLubyte srcpixels[4][4], const GLubyte * srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps) static
Referenced by _mesa_texstore_red_rgtc1(), and _mesa_texstore_rg_rgtc2().
fetch_l_latc1()
static void fetch_l_latc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_la_latc2()
static void fetch_la_latc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_red_rgtc1()
static void fetch_red_rgtc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_rg_rgtc2()
static void fetch_rg_rgtc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_signed_l_latc1()
static void fetch_signed_l_latc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT, GCOMP, and RCOMP.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_signed_la_latc2()
static void fetch_signed_la_latc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, and RCOMP.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_signed_red_rgtc1()
static void fetch_signed_red_rgtc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, and RCOMP.
Referenced by _mesa_get_compressed_rgtc_func().
fetch_signed_rg_rgtc2()
static void fetch_signed_rg_rgtc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, and RCOMP.
Referenced by _mesa_get_compressed_rgtc_func().