Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_fxt1.h File Reference
#include "glheader.h"
#include "texstore.h"
Functions
GLboolean _mesa_texstore_rgb_fxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_fxt1 format.
GLboolean _mesa_texstore_rgba_fxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_fxt1 format.
compressed_fetch_func _mesa_get_fxt_fetch_func (mesa_format format)
Function Documentation
_mesa_get_fxt_fetch_func()
compressed_fetch_func _mesa_get_fxt_fetch_func (mesa_format format)
References fetch_rgb_fxt1(), fetch_rgba_fxt1(), MESA_FORMAT_RGB_FXT1, and MESA_FORMAT_RGBA_FXT1.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_rgb_fxt1()
GLboolean _mesa_texstore_rgb_fxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_fxt1 format.
References _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_texstore(), ALIGN(), fxt1_encode(), MESA_FORMAT_RGB_FXT1, and MESA_FORMAT_RGB_UNORM8.
Referenced by texstore_compressed().
_mesa_texstore_rgba_fxt1()
GLboolean _mesa_texstore_rgba_fxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_fxt1 format.
References _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_little_endian(), _mesa_texstore(), fxt1_encode(), MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, and MESA_FORMAT_RGBA_FXT1.
Referenced by texstore_compressed().