Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress.h File Reference
#include "formats.h"
#include "glheader.h"
Typedefs
typedef void(* compressed_fetch_func) (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
A function to fetch one texel from a compressed texture.
Functions
GLenum _mesa_gl_compressed_format_base_format (GLenum format)
Get the GL base format of a specified GL compressed texture format.
GLuint _mesa_get_compressed_formats (struct gl_context *ctx, GLint *formats)
Return list of (and count of) all specific texture compression formats that are supported.
mesa_format _mesa_glenum_to_compressed_format (GLenum format)
Convert GLenum to a compressed MESA_FORMAT_x.
GLenum _mesa_compressed_format_to_glenum (struct gl_context *ctx, mesa_format mesaFormat)
Given a compressed MESA_FORMAT_x value, return the corresponding GLenum for that format.
GLubyte * _mesa_compressed_image_address (GLint col, GLint row, GLint img, mesa_format mesaFormat, GLsizei width, const GLubyte *image)
compressed_fetch_func _mesa_get_compressed_fetch_func (mesa_format format)
Return a texel-fetch function for the given format, or NULL if invalid format.
void _mesa_decompress_image (mesa_format format, GLuint width, GLuint height, const GLubyte *src, GLint srcRowStride, GLfloat *dest)
Decompress a compressed texture image, returning a GL_RGBA/GL_FLOAT image.
Typedef Documentation
compressed_fetch_func
typedef void(* compressed_fetch_func) (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
A function to fetch one texel from a compressed texture.
Function Documentation
_mesa_compressed_format_to_glenum()
GLenum _mesa_compressed_format_to_glenum (struct gl_context * ctx, mesa_format mesaFormat)
Given a compressed MESA_FORMAT_x value, return the corresponding GLenum for that format.
This is needed for glGetTexLevelParameter(GL_TEXTURE_INTERNAL_FORMAT) which must return the specific texture format used when the user might have originally specified a generic compressed format in their glTexImage2D() call. For non-compressed textures, we always return the user-specified internal format unchanged.
References _mesa_problem(), GL_COMPRESSED_RGBA_ASTC_3x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x6_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES, GL_ETC1_RGB8_OES, MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, MESA_FORMAT_BPTC_RGBA_UNORM, MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_R_RGTC1_SNORM, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_RG_RGTC2_SNORM, MESA_FORMAT_RG_RGTC2_UNORM, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGBA_ASTC_10x10, MESA_FORMAT_RGBA_ASTC_10x5, MESA_FORMAT_RGBA_ASTC_10x6, MESA_FORMAT_RGBA_ASTC_10x8, MESA_FORMAT_RGBA_ASTC_12x10, MESA_FORMAT_RGBA_ASTC_12x12, MESA_FORMAT_RGBA_ASTC_3x3x3, MESA_FORMAT_RGBA_ASTC_4x3x3, MESA_FORMAT_RGBA_ASTC_4x4, MESA_FORMAT_RGBA_ASTC_4x4x3, MESA_FORMAT_RGBA_ASTC_4x4x4, MESA_FORMAT_RGBA_ASTC_5x4, MESA_FORMAT_RGBA_ASTC_5x4x4, MESA_FORMAT_RGBA_ASTC_5x5, MESA_FORMAT_RGBA_ASTC_5x5x4, MESA_FORMAT_RGBA_ASTC_5x5x5, MESA_FORMAT_RGBA_ASTC_6x5, MESA_FORMAT_RGBA_ASTC_6x5x5, MESA_FORMAT_RGBA_ASTC_6x6, MESA_FORMAT_RGBA_ASTC_6x6x5, MESA_FORMAT_RGBA_ASTC_6x6x6, MESA_FORMAT_RGBA_ASTC_8x5, MESA_FORMAT_RGBA_ASTC_8x6, MESA_FORMAT_RGBA_ASTC_8x8, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x8, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x12, MESA_FORMAT_SRGB8_ALPHA8_ASTC_3x3x3, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x3x3, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4x3, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, and MESA_FORMAT_SRGBA_DXT5.
Referenced by get_tex_level_parameter_image().
_mesa_compressed_image_address()
GLubyte* _mesa_compressed_image_address (GLint col, GLint row, GLint img, mesa_format mesaFormat, GLsizei width, const GLubyte * image)
References _mesa_get_format_block_size(), _mesa_get_format_bytes(), and GLuint.
_mesa_decompress_image()
void _mesa_decompress_image (mesa_format format, GLuint width, GLuint height, const GLubyte * src, GLint srcRowStride, GLfloat * dest)
Decompress a compressed texture image, returning a GL_RGBA/GL_FLOAT image.
Parameters
srcRowStride stride in bytes between rows of blocks in the compressed source image.
References _mesa_get_compressed_fetch_func(), _mesa_get_format_block_size(), _mesa_get_format_bytes(), _mesa_problem(), and GLuint.
Referenced by get_tex_rgba_compressed().
_mesa_get_compressed_fetch_func()
compressed_fetch_func _mesa_get_compressed_fetch_func (mesa_format format)
Return a texel-fetch function for the given format, or NULL if invalid format.
References _mesa_get_bptc_fetch_func(), _mesa_get_compressed_rgtc_func(), _mesa_get_dxt_fetch_func(), _mesa_get_etc_fetch_func(), _mesa_get_format_layout(), _mesa_get_fxt_fetch_func(), MESA_FORMAT_LAYOUT_BPTC, MESA_FORMAT_LAYOUT_ETC1, MESA_FORMAT_LAYOUT_FXT1, MESA_FORMAT_LAYOUT_LATC, MESA_FORMAT_LAYOUT_RGTC, and MESA_FORMAT_LAYOUT_S3TC.
Referenced by _mesa_decompress_image().
_mesa_get_compressed_formats()
GLuint _mesa_get_compressed_formats (struct gl_context * ctx, GLint * formats)
Return list of (and count of) all specific texture compression formats that are supported.
Some formats are not returned by this function. The GL_COMPRESSED_TEXTURE_FORMATS query only returns formats that are "suitable for general-purpose usage." All texture compression extensions have taken this to mean either linear RGB or linear RGBA.
The GL_ARB_texture_compress_rgtc spec says:
"19) Should the GL_NUM_COMPRESSED_TEXTURE_FORMATS and GL_COMPRESSED_TEXTURE_FORMATS queries return the RGTC formats?
RESOLVED: No.
The OpenGL 2.1 specification says "The only values returned by this query [GL_COMPRESSED_TEXTURE_FORMATS"] are those corresponding to formats suitable for general-purpose usage. The renderer will not enumerate formats with restrictions that need to be specifically understood prior to use."
Compressed textures with just red or red-green components are not general-purpose so should not be returned by these queries because they have restrictions.
Applications that seek to use the RGTC formats should do so by looking for this extension's name in the string returned by glGetString(GL_EXTENSIONS) rather than what GL_NUM_COMPRESSED_TEXTURE_FORMATS and GL_COMPRESSED_TEXTURE_FORMATS return."
There is nearly identical wording in the GL_EXT_texture_compression_rgtc spec.
The GL_EXT_texture_rRGB spec says:
"22) Should the new COMPRESSED_SRGB_* formats be listed in an implementation's GL_COMPRESSED_TEXTURE_FORMATS list?
RESOLVED: No. Section 3.8.1 says formats listed by GL_COMPRESSED_TEXTURE_FORMATS are "suitable for general-purpose usage." The non-linear distribution of red, green, and blue for these sRGB compressed formats makes them not really general-purpose."
The GL_EXT_texture_compression_latc spec says:
"16) Should the GL_NUM_COMPRESSED_TEXTURE_FORMATS and GL_COMPRESSED_TEXTURE_FORMATS queries return the LATC formats?
RESOLVED: No.
The OpenGL 2.1 specification says "The only values returned by this query [GL_COMPRESSED_TEXTURE_FORMATS"] are those corresponding to formats suitable for general-purpose usage. The renderer will not enumerate formats with restrictions that need to be specifically understood prior to use."
Historically, OpenGL implementation have advertised the RGB and RGBA versions of the S3TC extensions compressed format tokens through this mechanism.
The specification is not sufficiently clear about what "suitable for general-purpose usage" means. Historically that seems to mean unsigned RGB or unsigned RGBA. The DXT1 format supporting alpha (GL_COMPRESSED_RGBA_S3TC_DXT1_EXT) is not exposed in the list (at least for NVIDIA drivers) because the alpha is always 1.0 expect when it is 0.0 when RGB is required to be black. NVIDIA's even limits itself to true linear RGB or RGBA formats, specifically not including EXT_texture_sRGB's sRGB S3TC compressed formats.
Adding luminance and luminance-alpha texture formats (and certainly signed versions of luminance and luminance-alpha formats!) invites potential comptaibility problems with old applications using this mechanism since old applications are unlikely to expect non-RGB or non-RGBA formats to be advertised through this mechanism. However no specific misinteractions with old applications is known.
Applications that seek to use the LATC formats should do so by looking for this extension's name in the string returned by glGetString(GL_EXTENSIONS) rather than what GL_NUM_COMPRESSED_TEXTURE_FORMATS and GL_COMPRESSED_TEXTURE_FORMATS return."
There is no formal spec for GL_ATI_texture_compression_3dc. Since the formats added by this extension are luminance-alpha formats, it is reasonable to expect them to follow the same rules as GL_EXT_texture_compression_latc. At the very least, Catalyst 11.6 does not expose the 3dc formats through this mechanism.
The spec for GL_ARB_texture_compression_bptc doesn't mention whether it should be included in GL_COMPRESSED_TEXTURE_FORMATS. However as it takes a very long time to compress the textures in this format it's probably not very useful as a general format where the GL will have to compress it on the fly.
Parameters
ctx the GL context
formats the resulting format list (may be NULL).
Returns
number of formats.
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_context::API, API_OPENGLES, API_OPENGLES2, gl_extensions::ARB_ES3_compatibility, gl_extensions::EXT_texture_compression_s3tc, gl_context::Extensions, GL_COMPRESSED_RGBA_ASTC_3x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x6_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES, GL_ETC1_RGB8_OES, GLuint, gl_extensions::KHR_texture_compression_astc_ldr, gl_extensions::OES_compressed_ETC1_RGB8_texture, gl_extensions::OES_texture_compression_astc, and gl_extensions::TDFX_texture_compression_FXT1.
Referenced by find_custom_value().
_mesa_gl_compressed_format_base_format()
GLenum _mesa_gl_compressed_format_base_format (GLenum format)
Get the GL base format of a specified GL compressed texture format.
From page 232 of the OpenGL 3.3 (Compatiblity Profile) spec:
"Compressed Internal Format      Base Internal Format    Type
---------------------------     --------------------    ---------
COMPRESSED_ALPHA                ALPHA                   Generic
COMPRESSED_LUMINANCE            LUMINANCE               Generic
COMPRESSED_LUMINANCE_ALPHA      LUMINANCE_ALPHA         Generic
COMPRESSED_INTENSITY            INTENSITY               Generic
COMPRESSED_RED                  RED                     Generic
COMPRESSED_RG                   RG                      Generic
COMPRESSED_RGB                  RGB                     Generic
COMPRESSED_RGBA                 RGBA                    Generic
COMPRESSED_SRGB                 RGB                     Generic
COMPRESSED_SRGB_ALPHA           RGBA                    Generic
COMPRESSED_SLUMINANCE           LUMINANCE               Generic
COMPRESSED_SLUMINANCE_ALPHA     LUMINANCE_ALPHA         Generic
COMPRESSED_RED_RGTC1            RED                     Specific
COMPRESSED_SIGNED_RED_RGTC1     RED                     Specific
COMPRESSED_RG_RGTC2             RG                      Specific
COMPRESSED_SIGNED_RG_RGTC2      RG                      Specific"
Returns
The base format of format if format is a compressed format (either generic or specific. Otherwise 0 is returned.
References GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, GL_ETC1_RGB8_OES, and GLuint.
Referenced by _mesa_base_tex_format(), and get_tex_level_parameter_image().
_mesa_glenum_to_compressed_format()
mesa_format _mesa_glenum_to_compressed_format (GLenum format)
Convert GLenum to a compressed MESA_FORMAT_x.
References GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, GL_COMPRESSED_RGBA_ASTC_3x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x3x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x3_OES, GL_COMPRESSED_RGBA_ASTC_4x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x4x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x4_OES, GL_COMPRESSED_RGBA_ASTC_5x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x5x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x5_OES, GL_COMPRESSED_RGBA_ASTC_6x6x6_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES, GL_ETC1_RGB8_OES, MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, MESA_FORMAT_BPTC_RGBA_UNORM, MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_NONE, MESA_FORMAT_R_RGTC1_SNORM, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_RG_RGTC2_SNORM, MESA_FORMAT_RG_RGTC2_UNORM, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGBA_ASTC_10x10, MESA_FORMAT_RGBA_ASTC_10x5, MESA_FORMAT_RGBA_ASTC_10x6, MESA_FORMAT_RGBA_ASTC_10x8, MESA_FORMAT_RGBA_ASTC_12x10, MESA_FORMAT_RGBA_ASTC_12x12, MESA_FORMAT_RGBA_ASTC_3x3x3, MESA_FORMAT_RGBA_ASTC_4x3x3, MESA_FORMAT_RGBA_ASTC_4x4, MESA_FORMAT_RGBA_ASTC_4x4x3, MESA_FORMAT_RGBA_ASTC_4x4x4, MESA_FORMAT_RGBA_ASTC_5x4, MESA_FORMAT_RGBA_ASTC_5x4x4, MESA_FORMAT_RGBA_ASTC_5x5, MESA_FORMAT_RGBA_ASTC_5x5x4, MESA_FORMAT_RGBA_ASTC_5x5x5, MESA_FORMAT_RGBA_ASTC_6x5, MESA_FORMAT_RGBA_ASTC_6x5x5, MESA_FORMAT_RGBA_ASTC_6x6, MESA_FORMAT_RGBA_ASTC_6x6x5, MESA_FORMAT_RGBA_ASTC_6x6x6, MESA_FORMAT_RGBA_ASTC_8x5, MESA_FORMAT_RGBA_ASTC_8x6, MESA_FORMAT_RGBA_ASTC_8x8, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_10x8, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x10, MESA_FORMAT_SRGB8_ALPHA8_ASTC_12x12, MESA_FORMAT_SRGB8_ALPHA8_ASTC_3x3x3, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x3x3, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4x3, MESA_FORMAT_SRGB8_ALPHA8_ASTC_4x4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x4x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5x4, MESA_FORMAT_SRGB8_ALPHA8_ASTC_5x5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x5x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_6x6x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x5, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x6, MESA_FORMAT_SRGB8_ALPHA8_ASTC_8x8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, and MESA_FORMAT_SRGBA_DXT5.
Referenced by _mesa_choose_tex_format(), _mesa_GetInternalformativ(), _mesa_is_compressed_format(), _mesa_target_can_be_compressed(), compressed_tex_size(), and teximage().