Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_s3tc.c File Reference
GL_EXT_texture_compression_s3tc support.
#include "glheader.h"
#include "imports.h"
#include "dlopen.h"
#include "image.h"
#include "macros.h"
#include "mtypes.h"
#include "texcompress.h"
#include "texcompress_s3tc.h"
#include "texstore.h"
#include "format_unpack.h"
#include "util/format_srgb.h"
Macros
#define DXTN_LIBNAME "libtxc_dxtn.so"
Typedefs
typedef void(* dxtFetchTexelFuncExt) (GLint srcRowstride, const GLubyte *pixdata, GLint col, GLint row, GLvoid *texelOut)
typedef void(* dxtCompressTexFuncExt) (GLint srccomps, GLint width, GLint height, const GLubyte *srcPixData, GLenum destformat, GLubyte *dest, GLint dstRowStride)
Functions
void _mesa_init_texture_s3tc (struct gl_context *ctx)
GLboolean _mesa_texstore_rgb_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_dxt1 format.
GLboolean _mesa_texstore_rgba_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt1 format.
GLboolean _mesa_texstore_rgba_dxt3 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt3 format.
GLboolean _mesa_texstore_rgba_dxt5 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt5 format.
static void problem (const char *func)
Report problem with dxt texture decompression, once.
static void fetch_rgb_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rgba_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rgba_dxt3 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rgba_dxt5 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgb_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgba_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgba_dxt3 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgba_dxt5 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
compressed_fetch_func _mesa_get_dxt_fetch_func (mesa_format format)
Variables
static dxtFetchTexelFuncExt fetch_ext_rgb_dxt1 = NULL
static dxtFetchTexelFuncExt fetch_ext_rgba_dxt1 = NULL
static dxtFetchTexelFuncExt fetch_ext_rgba_dxt3 = NULL
static dxtFetchTexelFuncExt fetch_ext_rgba_dxt5 = NULL
static dxtCompressTexFuncExt ext_tx_compress_dxtn = NULL
static void * dxtlibhandle = NULL
Detailed Description
GL_EXT_texture_compression_s3tc support.
Macro Definition Documentation
DXTN_LIBNAME
#define DXTN_LIBNAME "libtxc_dxtn.so"
Referenced by _mesa_init_texture_s3tc().
Typedef Documentation
dxtCompressTexFuncExt
typedef void(* dxtCompressTexFuncExt) (GLint srccomps, GLint width, GLint height, const GLubyte *srcPixData, GLenum destformat, GLubyte *dest, GLint dstRowStride)
dxtFetchTexelFuncExt
typedef void(* dxtFetchTexelFuncExt) (GLint srcRowstride, const GLubyte *pixdata, GLint col, GLint row, GLvoid *texelOut)
Function Documentation
_mesa_get_dxt_fetch_func()
compressed_fetch_func _mesa_get_dxt_fetch_func (mesa_format format)
References fetch_rgb_dxt1(), fetch_rgba_dxt1(), fetch_rgba_dxt3(), fetch_rgba_dxt5(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), fetch_srgba_dxt5(), MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, and MESA_FORMAT_SRGBA_DXT5.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_init_texture_s3tc()
void _mesa_init_texture_s3tc (struct gl_context * ctx)
References _mesa_dlclose(), _mesa_dlopen(), _mesa_dlsym(), _mesa_warning(), dxtlibhandle, DXTN_LIBNAME, ext_tx_compress_dxtn, fetch_ext_rgb_dxt1, fetch_ext_rgba_dxt1, fetch_ext_rgba_dxt3, fetch_ext_rgba_dxt5, and gl_context::Mesa_DXTn.
Referenced by init_attrib_groups().
_mesa_texstore_rgb_dxt1()
GLboolean _mesa_texstore_rgb_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_dxt1 format.
References _mesa_image_address2d(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_UNORM8, and MESA_FORMAT_SRGB_DXT1.
Referenced by texstore_compressed().
_mesa_texstore_rgba_dxt1()
GLboolean _mesa_texstore_rgba_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt1 format.
References _mesa_image_address2d(), _mesa_little_endian(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_DXT1, and MESA_FORMAT_SRGBA_DXT1.
Referenced by texstore_compressed().
_mesa_texstore_rgba_dxt3()
GLboolean _mesa_texstore_rgba_dxt3 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt3 format.
References _mesa_image_address2d(), _mesa_little_endian(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_DXT3, and MESA_FORMAT_SRGBA_DXT3.
Referenced by texstore_compressed().
_mesa_texstore_rgba_dxt5()
GLboolean _mesa_texstore_rgba_dxt5 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt5 format.
References _mesa_image_address2d(), _mesa_little_endian(), _mesa_texstore(), _mesa_warning(), ALIGN(), ext_tx_compress_dxtn, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_RGBA_DXT5, and MESA_FORMAT_SRGBA_DXT5.
Referenced by texstore_compressed().
fetch_rgb_dxt1()
static void fetch_rgb_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgb_dxt1, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_rgba_dxt1()
static void fetch_rgba_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt1, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_rgba_dxt3()
static void fetch_rgba_dxt3 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt3, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_rgba_dxt5()
static void fetch_rgba_dxt5 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt5, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_srgb_dxt1()
static void fetch_srgb_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgb_dxt1, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_srgba_dxt1()
static void fetch_srgba_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt1, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_srgba_dxt3()
static void fetch_srgba_dxt3 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt3, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
fetch_srgba_dxt5()
static void fetch_srgba_dxt5 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt5, GCOMP, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
problem()
static void problem (const char * func) static
Report problem with dxt texture decompression, once.
References _mesa_debug().
Referenced by fetch_rgb_dxt1(), fetch_rgba_dxt1(), fetch_rgba_dxt3(), fetch_rgba_dxt5(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), and fetch_srgba_dxt5().
Variable Documentation
dxtlibhandle
void* dxtlibhandle = NULL static
Referenced by _mesa_init_texture_s3tc().
ext_tx_compress_dxtn
dxtCompressTexFuncExt ext_tx_compress_dxtn = NULL static
Referenced by _mesa_init_texture_s3tc(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), and _mesa_texstore_rgba_dxt5().
fetch_ext_rgb_dxt1
dxtFetchTexelFuncExt fetch_ext_rgb_dxt1 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgb_dxt1(), and fetch_srgb_dxt1().
fetch_ext_rgba_dxt1
dxtFetchTexelFuncExt fetch_ext_rgba_dxt1 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgba_dxt1(), and fetch_srgba_dxt1().
fetch_ext_rgba_dxt3
dxtFetchTexelFuncExt fetch_ext_rgba_dxt3 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgba_dxt3(), and fetch_srgba_dxt3().
fetch_ext_rgba_dxt5
dxtFetchTexelFuncExt fetch_ext_rgba_dxt5 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgba_dxt5(), and fetch_srgba_dxt5().