Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_etc.c File Reference
GL_OES_compressed_ETC1_RGB8_texture support.
#include <stdbool.h>
#include "texcompress.h"
#include "texcompress_etc.h"
#include "texstore.h"
#include "macros.h"
#include "format_unpack.h"
#include "util/format_srgb.h"
#include "texcompress_etc_tmp.h"
Data Structures
struct etc2_block
Macros
#define UINT8_TYPE GLubyte
#define TAG(x) x
Functions
GLboolean _mesa_texstore_etc1_rgb8 (TEXSTORE_PARAMS)
void _mesa_etc1_unpack_rgba8888 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned src_width, unsigned src_height)
Decode texture data in format MESA_FORMAT_ETC1_RGB8 to MESA_FORMAT_ABGR8888.
static uint8_t etc2_base_color1_t_mode (const uint8_t *in, GLuint index)
static uint8_t etc2_base_color2_t_mode (const uint8_t *in, GLuint index)
static uint8_t etc2_base_color1_h_mode (const uint8_t *in, GLuint index)
static uint8_t etc2_base_color2_h_mode (const uint8_t *in, GLuint index)
static uint8_t etc2_base_color_o_planar (const uint8_t *in, GLuint index)
static uint8_t etc2_base_color_h_planar (const uint8_t *in, GLuint index)
static uint8_t etc2_base_color_v_planar (const uint8_t *in, GLuint index)
static GLint etc2_get_pixel_index (const struct etc2_block *block, int x, int y)
static uint8_t etc2_clamp (int color)
static GLushort etc2_clamp2 (int color)
static GLshort etc2_clamp3 (int color)
static void etc2_rgb8_parse_block (struct etc2_block *block, const uint8_t *src, GLboolean punchthrough_alpha)
static void etc2_rgb8_fetch_texel (const struct etc2_block *block, int x, int y, uint8_t *dst, GLboolean punchthrough_alpha)
static void etc2_alpha8_fetch_texel (const struct etc2_block *block, int x, int y, uint8_t *dst)
static void etc2_r11_fetch_texel (const struct etc2_block *block, int x, int y, uint8_t *dst)
static void etc2_signed_r11_fetch_texel (const struct etc2_block *block, int x, int y, uint8_t *dst)
static void etc2_alpha8_parse_block (struct etc2_block *block, const uint8_t *src)
static void etc2_r11_parse_block (struct etc2_block *block, const uint8_t *src)
static void etc2_rgba8_parse_block (struct etc2_block *block, const uint8_t *src)
static void etc2_rgba8_fetch_texel (const struct etc2_block *block, int x, int y, uint8_t *dst)
static void etc2_unpack_rgb8 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_srgb8 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_rgba8 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_srgb8_alpha8 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_r11 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_rg11 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_signed_r11 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_signed_rg11 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_rgb8_punchthrough_alpha1 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
static void etc2_unpack_srgb8_punchthrough_alpha1 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned width, unsigned height)
GLboolean _mesa_texstore_etc2_rgb8 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_srgb8 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rgba8_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_srgb8_alpha8_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_r11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_signed_r11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rg11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_signed_rg11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_srgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
void _mesa_unpack_etc2_format (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned src_width, unsigned src_height, mesa_format format)
Decode texture data in any one of following formats: MESA_FORMAT_ETC2_RGB8 MESA_FORMAT_ETC2_SRGB8 MESA_FORMAT_ETC2_RGBA8_EAC MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC MESA_FORMAT_ETC2_R11_EAC MESA_FORMAT_ETC2_RG11_EAC MESA_FORMAT_ETC2_SIGNED_R11_EAC MESA_FORMAT_ETC2_SIGNED_RG11_EAC MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1
static void fetch_etc1_rgb8 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_rgb8 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_srgb8 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_rgba8_eac (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_srgb8_alpha8_eac (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_r11_eac (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_rg11_eac (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_signed_r11_eac (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_signed_rg11_eac (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_rgb8_punchthrough_alpha1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_etc2_srgb8_punchthrough_alpha1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
compressed_fetch_func _mesa_get_etc_fetch_func (mesa_format format)
Variables
static const int etc2_distance_table [8]
static const int etc2_modifier_tables [16][8]
static const int etc2_modifier_tables_non_opaque [8][4]
Detailed Description
GL_OES_compressed_ETC1_RGB8_texture support.
Supported ETC2 texture formats are: GL_COMPRESSED_RGB8_ETC2 GL_COMPRESSED_SRGB8_ETC2 GL_COMPRESSED_RGBA8_ETC2_EAC GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC GL_COMPRESSED_R11_EAC GL_COMPRESSED_RG11_EAC GL_COMPRESSED_SIGNED_R11_EAC GL_COMPRESSED_SIGNED_RG11_EAC MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1
Macro Definition Documentation
TAG
#define TAG (x) x
UINT8_TYPE
#define UINT8_TYPE GLubyte
Referenced by etc1_base_color_diff_hi(), etc1_base_color_diff_lo(), etc1_base_color_ind_hi(), etc1_base_color_ind_lo(), etc1_clamp(), etc1_fetch_texel(), and TAG().
Function Documentation
_mesa_etc1_unpack_rgba8888()
void _mesa_etc1_unpack_rgba8888 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned src_width, unsigned src_height)
Decode texture data in format MESA_FORMAT_ETC1_RGB8 to MESA_FORMAT_ABGR8888.
The size of the source data must be a multiple of the ETC1 block size, which is 8, even if the texture image's dimensions are not aligned to 4. From the GL_OES_compressed_ETC1_RGB8_texture spec: The texture is described as a number of 4x4 pixel blocks. If the texture (or a particular mip-level) is smaller than 4 pixels in any dimension (such as a 2x2 or a 8x1 texture), the texture is found in the upper left part of the block(s), and the rest of the pixels are not used. For instance, a texture of size 4x2 will be placed in the upper half of a 4x4 block, and the lower half of the pixels in the block will not be accessed.
Parameters
src_width in pixels
src_height in pixels
dst_stride in bytes
References etc1_unpack_rgba8888().
_mesa_get_etc_fetch_func()
compressed_fetch_func _mesa_get_etc_fetch_func (mesa_format format)
References fetch_etc1_rgb8(), fetch_etc2_r11_eac(), fetch_etc2_rg11_eac(), fetch_etc2_rgb8(), fetch_etc2_rgb8_punchthrough_alpha1(), fetch_etc2_rgba8_eac(), fetch_etc2_signed_r11_eac(), fetch_etc2_signed_rg11_eac(), fetch_etc2_srgb8(), fetch_etc2_srgb8_alpha8_eac(), fetch_etc2_srgb8_punchthrough_alpha1(), MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, and MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_etc1_rgb8()
GLboolean _mesa_texstore_etc1_rgb8 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_r11_eac()
GLboolean _mesa_texstore_etc2_r11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rg11_eac()
GLboolean _mesa_texstore_etc2_rg11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rgb8()
GLboolean _mesa_texstore_etc2_rgb8 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rgb8_punchthrough_alpha1()
GLboolean _mesa_texstore_etc2_rgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rgba8_eac()
GLboolean _mesa_texstore_etc2_rgba8_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_signed_r11_eac()
GLboolean _mesa_texstore_etc2_signed_r11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_signed_rg11_eac()
GLboolean _mesa_texstore_etc2_signed_rg11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_srgb8()
GLboolean _mesa_texstore_etc2_srgb8 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_srgb8_alpha8_eac()
GLboolean _mesa_texstore_etc2_srgb8_alpha8_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_srgb8_punchthrough_alpha1()
GLboolean _mesa_texstore_etc2_srgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_unpack_etc2_format()
void _mesa_unpack_etc2_format (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned src_width, unsigned src_height, mesa_format format)
Decode texture data in any one of following formats: MESA_FORMAT_ETC2_RGB8 MESA_FORMAT_ETC2_SRGB8 MESA_FORMAT_ETC2_RGBA8_EAC MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC MESA_FORMAT_ETC2_R11_EAC MESA_FORMAT_ETC2_RG11_EAC MESA_FORMAT_ETC2_SIGNED_R11_EAC MESA_FORMAT_ETC2_SIGNED_RG11_EAC MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1
The size of the source data must be a multiple of the ETC2 block size even if the texture image's dimensions are not aligned to 4.
Parameters
src_width in pixels
src_height in pixels
dst_stride in bytes
References etc2_unpack_r11(), etc2_unpack_rg11(), etc2_unpack_rgb8(), etc2_unpack_rgb8_punchthrough_alpha1(), etc2_unpack_rgba8(), etc2_unpack_signed_r11(), etc2_unpack_signed_rg11(), etc2_unpack_srgb8(), etc2_unpack_srgb8_alpha8(), etc2_unpack_srgb8_punchthrough_alpha1(), MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, and MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1.
etc2_alpha8_fetch_texel()
static void etc2_alpha8_fetch_texel (const struct etc2_block * block, int x, int y, uint8_t * dst) static
References etc2_block::base_codeword, etc2_clamp(), etc2_get_pixel_index(), etc2_modifier_tables, etc2_block::multiplier, and etc2_block::table_index.
Referenced by etc2_rgba8_fetch_texel().
etc2_alpha8_parse_block()
static void etc2_alpha8_parse_block (struct etc2_block * block, const uint8_t * src) static
References etc2_block::base_codeword, etc2_block::multiplier, etc2_block::pixel_indices, and etc2_block::table_index.
Referenced by etc2_r11_parse_block(), and etc2_rgba8_parse_block().
etc2_base_color1_h_mode()
static uint8_t etc2_base_color1_h_mode (const uint8_t * in, GLuint index) static
References x.
Referenced by etc2_rgb8_parse_block().
etc2_base_color1_t_mode()
static uint8_t etc2_base_color1_t_mode (const uint8_t * in, GLuint index) static
References x.
Referenced by etc2_rgb8_parse_block().
etc2_base_color2_h_mode()
static uint8_t etc2_base_color2_h_mode (const uint8_t * in, GLuint index) static
References x.
Referenced by etc2_rgb8_parse_block().
etc2_base_color2_t_mode()
static uint8_t etc2_base_color2_t_mode (const uint8_t * in, GLuint index) static
References x.
Referenced by etc2_rgb8_parse_block().
etc2_base_color_h_planar()
static uint8_t etc2_base_color_h_planar (const uint8_t * in, GLuint index) static
References GLuint.
Referenced by etc2_rgb8_parse_block().
etc2_base_color_o_planar()
static uint8_t etc2_base_color_o_planar (const uint8_t * in, GLuint index) static
References GLuint.
Referenced by etc2_rgb8_parse_block().
etc2_base_color_v_planar()
static uint8_t etc2_base_color_v_planar (const uint8_t * in, GLuint index) static
References GLuint.
Referenced by etc2_rgb8_parse_block().
etc2_clamp()
static uint8_t etc2_clamp (int color) static
References GLushort.
Referenced by etc2_alpha8_fetch_texel(), etc2_rgb8_fetch_texel(), and etc2_rgb8_parse_block().
etc2_clamp2()
static GLushort etc2_clamp2 (int color) static
References GLushort.
Referenced by etc2_r11_fetch_texel().
etc2_clamp3()
static GLshort etc2_clamp3 (int color) static
Referenced by etc2_signed_r11_fetch_texel().
etc2_get_pixel_index()
static GLint etc2_get_pixel_index (const struct etc2_block * block, int x, int y) static
References etc2_block::pixel_indices.
Referenced by etc2_alpha8_fetch_texel(), etc2_r11_fetch_texel(), and etc2_signed_r11_fetch_texel().
etc2_r11_fetch_texel()
static void etc2_r11_fetch_texel (const struct etc2_block * block, int x, int y, uint8_t * dst) static
References etc2_block::base_codeword, etc2_clamp2(), etc2_get_pixel_index(), etc2_modifier_tables, GLushort, etc2_block::multiplier, and etc2_block::table_index.
Referenced by etc2_unpack_r11(), etc2_unpack_rg11(), fetch_etc2_r11_eac(), and fetch_etc2_rg11_eac().
etc2_r11_parse_block()
static void etc2_r11_parse_block (struct etc2_block * block, const uint8_t * src) static
References etc2_alpha8_parse_block().
Referenced by etc2_unpack_r11(), etc2_unpack_rg11(), etc2_unpack_signed_r11(), etc2_unpack_signed_rg11(), fetch_etc2_r11_eac(), fetch_etc2_rg11_eac(), fetch_etc2_signed_r11_eac(), and fetch_etc2_signed_rg11_eac().
etc2_rgb8_fetch_texel()
static void etc2_rgb8_fetch_texel (const struct etc2_block * block, int x, int y, uint8_t * dst, GLboolean punchthrough_alpha) static
References etc2_block::base_colors, etc2_clamp(), etc2_block::flipped, etc2_block::is_diff_mode, etc2_block::is_h_mode, etc2_block::is_ind_mode, etc2_block::is_planar_mode, etc2_block::is_t_mode, etc2_block::modifier_tables, etc2_block::opaque, etc2_block::paint_colors, and etc2_block::pixel_indices.
Referenced by etc2_rgba8_fetch_texel(), etc2_unpack_rgb8(), etc2_unpack_rgb8_punchthrough_alpha1(), etc2_unpack_srgb8(), etc2_unpack_srgb8_punchthrough_alpha1(), fetch_etc2_rgb8(), fetch_etc2_rgb8_punchthrough_alpha1(), fetch_etc2_srgb8(), and fetch_etc2_srgb8_punchthrough_alpha1().
etc2_rgb8_parse_block()
static void etc2_rgb8_parse_block (struct etc2_block * block, const uint8_t * src, GLboolean punchthrough_alpha) static
References etc2_block::base_colors, etc2_block::distance, etc1_base_color_diff_hi(), etc1_base_color_diff_lo(), etc1_base_color_ind_hi(), etc1_base_color_ind_lo(), etc2_base_color1_h_mode(), etc2_base_color1_t_mode(), etc2_base_color2_h_mode(), etc2_base_color2_t_mode(), etc2_base_color_h_planar(), etc2_base_color_o_planar(), etc2_base_color_v_planar(), etc2_clamp(), etc2_distance_table, etc2_modifier_tables_non_opaque, etc2_block::flipped, etc2_block::is_diff_mode, etc2_block::is_h_mode, etc2_block::is_ind_mode, etc2_block::is_planar_mode, etc2_block::is_t_mode, etc2_block::modifier_tables, etc2_block::opaque, etc2_block::paint_colors, and etc2_block::pixel_indices.
Referenced by etc2_rgba8_parse_block(), etc2_unpack_rgb8(), etc2_unpack_rgb8_punchthrough_alpha1(), etc2_unpack_srgb8(), etc2_unpack_srgb8_punchthrough_alpha1(), fetch_etc2_rgb8(), fetch_etc2_rgb8_punchthrough_alpha1(), fetch_etc2_srgb8(), and fetch_etc2_srgb8_punchthrough_alpha1().
etc2_rgba8_fetch_texel()
static void etc2_rgba8_fetch_texel (const struct etc2_block * block, int x, int y, uint8_t * dst) static
References etc2_alpha8_fetch_texel(), and etc2_rgb8_fetch_texel().
Referenced by etc2_unpack_rgba8(), etc2_unpack_srgb8_alpha8(), fetch_etc2_rgba8_eac(), and fetch_etc2_srgb8_alpha8_eac().
etc2_rgba8_parse_block()
static void etc2_rgba8_parse_block (struct etc2_block * block, const uint8_t * src) static
References etc2_alpha8_parse_block(), and etc2_rgb8_parse_block().
Referenced by etc2_unpack_rgba8(), etc2_unpack_srgb8_alpha8(), fetch_etc2_rgba8_eac(), and fetch_etc2_srgb8_alpha8_eac().
etc2_signed_r11_fetch_texel()
static void etc2_signed_r11_fetch_texel (const struct etc2_block * block, int x, int y, uint8_t * dst) static
References etc2_block::base_codeword, etc2_clamp3(), etc2_get_pixel_index(), etc2_modifier_tables, if(), etc2_block::multiplier, and etc2_block::table_index.
Referenced by etc2_unpack_signed_r11(), etc2_unpack_signed_rg11(), fetch_etc2_signed_r11_eac(), and fetch_etc2_signed_rg11_eac().
etc2_unpack_r11()
static void etc2_unpack_r11 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_r11_fetch_texel(), etc2_r11_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_rg11()
static void etc2_unpack_rg11 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_r11_fetch_texel(), etc2_r11_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_rgb8()
static void etc2_unpack_rgb8 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_rgb8_punchthrough_alpha1()
static void etc2_unpack_rgb8_punchthrough_alpha1 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_rgba8()
static void etc2_unpack_rgba8 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_rgba8_fetch_texel(), etc2_rgba8_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_signed_r11()
static void etc2_unpack_signed_r11 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_r11_parse_block(), etc2_signed_r11_fetch_texel(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_signed_rg11()
static void etc2_unpack_signed_rg11 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_r11_parse_block(), etc2_signed_r11_fetch_texel(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_srgb8()
static void etc2_unpack_srgb8 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_srgb8_alpha8()
static void etc2_unpack_srgb8_alpha8 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_rgba8_fetch_texel(), etc2_rgba8_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
etc2_unpack_srgb8_punchthrough_alpha1()
static void etc2_unpack_srgb8_punchthrough_alpha1 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned width, unsigned height) static
References etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), and x.
Referenced by _mesa_unpack_etc2_format().
fetch_etc1_rgb8()
static void fetch_etc1_rgb8 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc1_fetch_texel(), etc1_parse_block(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_r11_eac()
static void fetch_etc2_r11_eac (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_r11_fetch_texel(), etc2_r11_parse_block(), GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_rg11_eac()
static void fetch_etc2_rg11_eac (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_r11_fetch_texel(), etc2_r11_parse_block(), GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_rgb8()
static void fetch_etc2_rgb8 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_rgb8_punchthrough_alpha1()
static void fetch_etc2_rgb8_punchthrough_alpha1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_rgba8_eac()
static void fetch_etc2_rgba8_eac (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_rgba8_fetch_texel(), etc2_rgba8_parse_block(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_signed_r11_eac()
static void fetch_etc2_signed_r11_eac (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_r11_parse_block(), etc2_signed_r11_fetch_texel(), GCOMP, GLushort, RCOMP, and SHORT_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_signed_rg11_eac()
static void fetch_etc2_signed_rg11_eac (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_r11_parse_block(), etc2_signed_r11_fetch_texel(), GCOMP, GLushort, RCOMP, and SHORT_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_srgb8()
static void fetch_etc2_srgb8 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), GCOMP, and RCOMP.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_srgb8_alpha8_eac()
static void fetch_etc2_srgb8_alpha8_eac (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_rgba8_fetch_texel(), etc2_rgba8_parse_block(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
fetch_etc2_srgb8_punchthrough_alpha1()
static void fetch_etc2_srgb8_punchthrough_alpha1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, etc2_rgb8_fetch_texel(), etc2_rgb8_parse_block(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_etc_fetch_func().
Variable Documentation
etc2_distance_table
const int etc2_distance_table[8] static
Initial value:
= {
   3, 6, 11, 16, 23, 32, 41, 64 }
Referenced by etc2_rgb8_parse_block().
etc2_modifier_tables
const int etc2_modifier_tables[16][8] static
Initial value:
= {
   {  -3,   -6,   -9,  -15,   2,   5,   8,   14},
   {  -3,   -7,  -10,  -13,   2,   6,   9,   12},
   {  -2,   -5,   -8,  -13,   1,   4,   7,   12},
   {  -2,   -4,   -6,  -13,   1,   3,   5,   12},
   {  -3,   -6,   -8,  -12,   2,   5,   7,   11},
   {  -3,   -7,   -9,  -11,   2,   6,   8,   10},
   {  -4,   -7,   -8,  -11,   3,   6,   7,   10},
   {  -3,   -5,   -8,  -11,   2,   4,   7,   10},
   {  -2,   -6,   -8,  -10,   1,   5,   7,    9},
   {  -2,   -5,   -8,  -10,   1,   4,   7,    9},
   {  -2,   -4,   -8,  -10,   1,   3,   7,    9},
   {  -2,   -5,   -7,  -10,   1,   4,   6,    9},
   {  -3,   -4,   -7,  -10,   2,   3,   6,    9},
   {  -1,   -2,   -3,  -10,   0,   1,   2,    9},
   {  -4,   -6,   -8,   -9,   3,   5,   7,    8},
   {  -3,   -5,   -7,   -9,   2,   4,   6,    8},
}
Referenced by etc2_alpha8_fetch_texel(), etc2_r11_fetch_texel(), and etc2_signed_r11_fetch_texel().
etc2_modifier_tables_non_opaque
const int etc2_modifier_tables_non_opaque[8][4] static
Initial value:
= {
   { 0,   8,   0,    -8},
   { 0,   17,  0,   -17},
   { 0,   29,  0,   -29},
   { 0,   42,  0,   -42},
   { 0,   60,  0,   -60},
   { 0,   80,  0,   -80},
   { 0,   106, 0,  -106},
   { 0,   183, 0,  -183}
}
Referenced by etc2_rgb8_parse_block().