Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_bptc.c File Reference
GL_ARB_texture_compression_bptc support.
#include <stdbool.h>
#include "texcompress.h"
#include "texcompress_bptc.h"
#include "util/format_srgb.h"
#include "util/half_float.h"
#include "texstore.h"
#include "macros.h"
#include "image.h"
Data Structures
struct bptc_unorm_mode
struct bptc_float_bitfield
struct bptc_float_mode
struct bit_writer
Macros
#define BLOCK_SIZE 4
#define N_PARTITIONS 64
#define BLOCK_BYTES 16
Functions
static int extract_bits (const uint8_t *block, int offset, int n_bits)
static uint8_t expand_component (uint8_t byte, int n_bits)
static int extract_unorm_endpoints (const struct bptc_unorm_mode *mode, const uint8_t *block, int bit_offset, uint8_t endpoints[][4])
static bool is_anchor (int n_subsets, int partition_num, int texel)
static int count_anchors_before_texel (int n_subsets, int partition_num, int texel)
static int32_t interpolate (int32_t a, int32_t b, int index, int index_bits)
static void apply_rotation (int rotation, uint8_t *result)
static void fetch_rgba_unorm_from_block (const uint8_t *block, uint8_t *result, int texel)
static void fetch_bptc_rgba_unorm_bytes (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLubyte *texel)
static void fetch_bptc_rgba_unorm (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_bptc_srgb_alpha_unorm (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static int32_t sign_extend (int32_t value, int n_bits)
static int signed_unquantize (int value, int n_endpoint_bits)
static int unsigned_unquantize (int value, int n_endpoint_bits)
static int extract_float_endpoints (const struct bptc_float_mode *mode, const uint8_t *block, int bit_offset, int32_t endpoints[][3], bool is_signed)
static int32_t finish_unsigned_unquantize (int32_t value)
static int32_t finish_signed_unquantize (int32_t value)
static void fetch_rgb_float_from_block (const uint8_t *block, float *result, int texel, bool is_signed)
static void fetch_bptc_rgb_float (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel, bool is_signed)
static void fetch_bptc_rgb_signed_float (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_bptc_rgb_unsigned_float (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
compressed_fetch_func _mesa_get_bptc_fetch_func (mesa_format format)
static void write_bits (struct bit_writer *writer, int n_bits, int value)
static void get_average_luminance_alpha_unorm (int width, int height, const uint8_t *src, int src_rowstride, int *average_luminance, int *average_alpha)
static void get_rgba_endpoints_unorm (int width, int height, const uint8_t *src, int src_rowstride, int average_luminance, int average_alpha, uint8_t endpoints[][4])
static void write_rgb_indices_unorm (struct bit_writer *writer, int src_width, int src_height, const uint8_t *src, int src_rowstride, uint8_t endpoints[][4])
static void write_alpha_indices_unorm (struct bit_writer *writer, int src_width, int src_height, const uint8_t *src, int src_rowstride, uint8_t endpoints[][4])
static void compress_rgba_unorm_block (int src_width, int src_height, const uint8_t *src, int src_rowstride, uint8_t *dst)
static void compress_rgba_unorm (int width, int height, const uint8_t *src, int src_rowstride, uint8_t *dst, int dst_rowstride)
GLboolean _mesa_texstore_bptc_rgba_unorm (TEXSTORE_PARAMS)
static float get_average_luminance_float (int width, int height, const float *src, int src_rowstride)
static float clamp_value (float value, bool is_signed)
static void get_endpoints_float (int width, int height, const float *src, int src_rowstride, float average_luminance, float endpoints[][3], bool is_signed)
static void write_rgb_indices_float (struct bit_writer *writer, int src_width, int src_height, const float *src, int src_rowstride, float endpoints[][3])
static int get_endpoint_value (float value, bool is_signed)
static void compress_rgb_float_block (int src_width, int src_height, const float *src, int src_rowstride, uint8_t *dst, bool is_signed)
static void compress_rgb_float (int width, int height, const float *src, int src_rowstride, uint8_t *dst, int dst_rowstride, bool is_signed)
static GLboolean texstore_bptc_rgb_float (TEXSTORE_PARAMS, bool is_signed)
GLboolean _mesa_texstore_bptc_rgb_signed_float (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_bptc_rgb_unsigned_float (TEXSTORE_PARAMS)
Variables
static const struct bptc_unorm_mode bptc_unorm_modes []
static const struct bptc_float_mode bptc_float_modes []
static const uint32_t partition_table1 [N_PARTITIONS]
static const uint32_t partition_table2 [N_PARTITIONS]
static const uint8_t anchor_indices [][N_PARTITIONS]
Detailed Description
GL_ARB_texture_compression_bptc support.
Macro Definition Documentation
BLOCK_BYTES
#define BLOCK_BYTES 16
Referenced by compress_rgb_float(), and compress_rgba_unorm().
BLOCK_SIZE
#define BLOCK_SIZE 4
Referenced by compress_rgb_float(), compress_rgba_unorm(), fetch_rgba_unorm_from_block(), write_alpha_indices_unorm(), write_rgb_indices_float(), and write_rgb_indices_unorm().
N_PARTITIONS
#define N_PARTITIONS 64
Function Documentation
_mesa_get_bptc_fetch_func()
compressed_fetch_func _mesa_get_bptc_fetch_func (mesa_format format)
References fetch_bptc_rgb_signed_float(), fetch_bptc_rgb_unsigned_float(), fetch_bptc_rgba_unorm(), fetch_bptc_srgb_alpha_unorm(), MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, MESA_FORMAT_BPTC_RGBA_UNORM, and MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_bptc_rgb_signed_float()
GLboolean _mesa_texstore_bptc_rgb_signed_float (TEXSTORE_PARAMS)
References MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, and texstore_bptc_rgb_float().
Referenced by texstore_compressed().
_mesa_texstore_bptc_rgb_unsigned_float()
GLboolean _mesa_texstore_bptc_rgb_unsigned_float (TEXSTORE_PARAMS)
References MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, and texstore_bptc_rgb_float().
Referenced by texstore_compressed().
_mesa_texstore_bptc_rgba_unorm()
GLboolean _mesa_texstore_bptc_rgba_unorm (TEXSTORE_PARAMS)
References _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_little_endian(), _mesa_texstore(), compress_rgba_unorm(), MESA_FORMAT_A8B8G8R8_UNORM, and MESA_FORMAT_R8G8B8A8_UNORM.
Referenced by texstore_compressed().
apply_rotation()
static void apply_rotation (int rotation, uint8_t * result) static
Referenced by fetch_rgba_unorm_from_block().
clamp_value()
static float clamp_value (float value, bool is_signed) static
Referenced by get_endpoints_float().
compress_rgb_float()
static void compress_rgb_float (int width, int height, const float * src, int src_rowstride, uint8_t * dst, int dst_rowstride, bool is_signed) static
References BLOCK_BYTES, BLOCK_SIZE, compress_rgb_float_block(), and x.
Referenced by texstore_bptc_rgb_float().
compress_rgb_float_block()
static void compress_rgb_float_block (int src_width, int src_height, const float * src, int src_rowstride, uint8_t * dst, bool is_signed) static
References bit_writer::buf, bit_writer::dst, get_average_luminance_float(), get_endpoint_value(), get_endpoints_float(), bit_writer::pos, write_bits(), and write_rgb_indices_float().
Referenced by compress_rgb_float().
compress_rgba_unorm()
static void compress_rgba_unorm (int width, int height, const uint8_t * src, int src_rowstride, uint8_t * dst, int dst_rowstride) static
References BLOCK_BYTES, BLOCK_SIZE, compress_rgba_unorm_block(), and x.
Referenced by _mesa_texstore_bptc_rgba_unorm().
compress_rgba_unorm_block()
static void compress_rgba_unorm_block (int src_width, int src_height, const uint8_t * src, int src_rowstride, uint8_t * dst) static
References bit_writer::buf, bit_writer::dst, get_average_luminance_alpha_unorm(), get_rgba_endpoints_unorm(), bit_writer::pos, write_alpha_indices_unorm(), write_bits(), and write_rgb_indices_unorm().
Referenced by compress_rgba_unorm().
count_anchors_before_texel()
static int count_anchors_before_texel (int n_subsets, int partition_num, int texel) static
References anchor_indices.
Referenced by fetch_rgb_float_from_block(), and fetch_rgba_unorm_from_block().
expand_component()
static uint8_t expand_component (uint8_t byte, int n_bits) static
Referenced by extract_unorm_endpoints().
extract_bits()
static int extract_bits (const uint8_t * block, int offset, int n_bits) static
Referenced by extract_float_endpoints(), extract_unorm_endpoints(), fetch_rgb_float_from_block(), and fetch_rgba_unorm_from_block().
extract_float_endpoints()
static int extract_float_endpoints (const struct bptc_float_mode * mode, const uint8_t * block, int bit_offset, int32_t endpoints[][3], bool is_signed) static
References bptc_float_mode::bitfields, bptc_float_bitfield::component, bptc_float_bitfield::endpoint, extract_bits(), bptc_float_bitfield::n_bits, bptc_float_mode::n_delta_bits, bptc_float_mode::n_endpoint_bits, bptc_float_mode::n_partition_bits, bptc_float_bitfield::offset, bptc_float_bitfield::reverse, sign_extend(), signed_unquantize(), bptc_float_mode::transformed_endpoints, and unsigned_unquantize().
Referenced by fetch_rgb_float_from_block().
extract_unorm_endpoints()
static int extract_unorm_endpoints (const struct bptc_unorm_mode * mode, const uint8_t * block, int bit_offset, uint8_t endpoints[][4]) static
References expand_component(), extract_bits(), bptc_unorm_mode::has_endpoint_pbits, bptc_unorm_mode::has_shared_pbits, bptc_unorm_mode::n_alpha_bits, bptc_unorm_mode::n_color_bits, and bptc_unorm_mode::n_subsets.
Referenced by fetch_rgba_unorm_from_block().
fetch_bptc_rgb_float()
static void fetch_bptc_rgb_float (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel, bool is_signed) static
References fetch_rgb_float_from_block().
Referenced by fetch_bptc_rgb_signed_float(), and fetch_bptc_rgb_unsigned_float().
fetch_bptc_rgb_signed_float()
static void fetch_bptc_rgb_signed_float (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References fetch_bptc_rgb_float().
Referenced by _mesa_get_bptc_fetch_func().
fetch_bptc_rgb_unsigned_float()
static void fetch_bptc_rgb_unsigned_float (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References fetch_bptc_rgb_float().
Referenced by _mesa_get_bptc_fetch_func().
fetch_bptc_rgba_unorm()
static void fetch_bptc_rgba_unorm (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_bptc_rgba_unorm_bytes(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_bptc_fetch_func().
fetch_bptc_rgba_unorm_bytes()
static void fetch_bptc_rgba_unorm_bytes (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLubyte * texel) static
References fetch_rgba_unorm_from_block().
Referenced by fetch_bptc_rgba_unorm(), and fetch_bptc_srgb_alpha_unorm().
fetch_bptc_srgb_alpha_unorm()
static void fetch_bptc_srgb_alpha_unorm (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_bptc_rgba_unorm_bytes(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_bptc_fetch_func().
fetch_rgb_float_from_block()
static void fetch_rgb_float_from_block (const uint8_t * block, float * result, int texel, bool is_signed) static
References count_anchors_before_texel(), extract_bits(), extract_float_endpoints(), finish_signed_unquantize(), finish_unsigned_unquantize(), interpolate(), is_anchor(), bptc_float_mode::n_index_bits, bptc_float_mode::n_partition_bits, bptc_unorm_mode::n_subsets, partition_table1, and bptc_float_mode::reserved.
Referenced by fetch_bptc_rgb_float().
fetch_rgba_unorm_from_block()
static void fetch_rgba_unorm_from_block (const uint8_t * block, uint8_t * result, int texel) static
References apply_rotation(), BLOCK_SIZE, count_anchors_before_texel(), extract_bits(), extract_unorm_endpoints(), bptc_unorm_mode::has_index_selection_bit, bptc_unorm_mode::has_rotation_bits, interpolate(), is_anchor(), bptc_unorm_mode::n_index_bits, bptc_unorm_mode::n_partition_bits, bptc_unorm_mode::n_secondary_index_bits, bptc_unorm_mode::n_subsets, partition_table1, and partition_table2.
Referenced by fetch_bptc_rgba_unorm_bytes().
finish_signed_unquantize()
static int32_t finish_signed_unquantize (int32_t value) static
Referenced by fetch_rgb_float_from_block().
finish_unsigned_unquantize()
static int32_t finish_unsigned_unquantize (int32_t value) static
Referenced by fetch_rgb_float_from_block().
get_average_luminance_alpha_unorm()
static void get_average_luminance_alpha_unorm (int width, int height, const uint8_t * src, int src_rowstride, int * average_luminance, int * average_alpha) static
References x.
Referenced by compress_rgba_unorm_block().
get_average_luminance_float()
static float get_average_luminance_float (int width, int height, const float * src, int src_rowstride) static
References x.
Referenced by compress_rgb_float_block().
get_endpoint_value()
static int get_endpoint_value (float value, bool is_signed) static
Referenced by compress_rgb_float_block().
get_endpoints_float()
static void get_endpoints_float (int width, int height, const float * src, int src_rowstride, float average_luminance, float endpoints[][3], bool is_signed) static
References clamp_value(), and x.
Referenced by compress_rgb_float_block().
get_rgba_endpoints_unorm()
static void get_rgba_endpoints_unorm (int width, int height, const uint8_t * src, int src_rowstride, int average_luminance, int average_alpha, uint8_t endpoints[][4]) static
References x.
Referenced by compress_rgba_unorm_block().
interpolate()
static int32_t interpolate (int32_t a, int32_t b, int index, int index_bits) static
Referenced by fetch_rgb_float_from_block(), and fetch_rgba_unorm_from_block().
is_anchor()
static bool is_anchor (int n_subsets, int partition_num, int texel) static
References anchor_indices.
Referenced by fetch_rgb_float_from_block(), and fetch_rgba_unorm_from_block().
sign_extend()
static int32_t sign_extend (int32_t value, int n_bits) static
Referenced by extract_float_endpoints().
signed_unquantize()
static int signed_unquantize (int value, int n_endpoint_bits) static
Referenced by extract_float_endpoints().
texstore_bptc_rgb_float()
static GLboolean texstore_bptc_rgb_float (TEXSTORE_PARAMS , bool is_signed) static
References _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_texstore(), compress_rgb_float(), and MESA_FORMAT_RGB_FLOAT32.
Referenced by _mesa_texstore_bptc_rgb_signed_float(), and _mesa_texstore_bptc_rgb_unsigned_float().
unsigned_unquantize()
static int unsigned_unquantize (int value, int n_endpoint_bits) static
Referenced by extract_float_endpoints().
write_alpha_indices_unorm()
static void write_alpha_indices_unorm (struct bit_writer * writer, int src_width, int src_height, const uint8_t * src, int src_rowstride, uint8_t endpoints[][4]) static
References BLOCK_SIZE, write_bits(), and x.
Referenced by compress_rgba_unorm_block().
write_bits()
static void write_bits (struct bit_writer * writer, int n_bits, int value) static
References bit_writer::buf, bit_writer::dst, and bit_writer::pos.
Referenced by compress_rgb_float_block(), compress_rgba_unorm_block(), write_alpha_indices_unorm(), write_rgb_indices_float(), and write_rgb_indices_unorm().
write_rgb_indices_float()
static void write_rgb_indices_float (struct bit_writer * writer, int src_width, int src_height, const float * src, int src_rowstride, float endpoints[][3]) static
References BLOCK_SIZE, write_bits(), and x.
Referenced by compress_rgb_float_block().
write_rgb_indices_unorm()
static void write_rgb_indices_unorm (struct bit_writer * writer, int src_width, int src_height, const uint8_t * src, int src_rowstride, uint8_t endpoints[][4]) static
References BLOCK_SIZE, write_bits(), and x.
Referenced by compress_rgba_unorm_block().
Variable Documentation
anchor_indices
const uint8_t anchor_indices[][N_PARTITIONS] static
Initial value:
= {
   {
      0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,
      0xf,0x2,0x8,0x2,0x2,0x8,0x8,0xf,0x2,0x8,0x2,0x2,0x8,0x8,0x2,0x2,
      0xf,0xf,0x6,0x8,0x2,0x8,0xf,0xf,0x2,0x8,0x2,0x2,0x2,0xf,0xf,0x6,
      0x6,0x2,0x6,0x8,0xf,0xf,0x2,0x2,0xf,0xf,0xf,0xf,0xf,0x2,0x2,0xf
   },
   {
      0x3,0x3,0xf,0xf,0x8,0x3,0xf,0xf,0x8,0x8,0x6,0x6,0x6,0x5,0x3,0x3,
      0x3,0x3,0x8,0xf,0x3,0x3,0x6,0xa,0x5,0x8,0x8,0x6,0x8,0x5,0xf,0xf,
      0x8,0xf,0x3,0x5,0x6,0xa,0x8,0xf,0xf,0x3,0xf,0x5,0xf,0xf,0xf,0xf,
      0x3,0xf,0x5,0x5,0x5,0x8,0x5,0xa,0x5,0xa,0x8,0xd,0xf,0xc,0x3,0x3
   },
   {
      0xf,0x8,0x8,0x3,0xf,0xf,0x3,0x8,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0x8,
      0xf,0x8,0xf,0x3,0xf,0x8,0xf,0x8,0x3,0xf,0x6,0xa,0xf,0xf,0xa,0x8,
      0xf,0x3,0xf,0xa,0xa,0x8,0x9,0xa,0x6,0xf,0x8,0xf,0x3,0x6,0x6,0x8,
      0xf,0x3,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0xf,0x3,0xf,0xf,0x8
   }
}
Referenced by count_anchors_before_texel(), and is_anchor().
bptc_float_modes
const struct bptc_float_mode bptc_float_modes[] static
bptc_unorm_modes
const struct bptc_unorm_mode bptc_unorm_modes[] static
Initial value:
= {
    { 3, 4, false, false, 4, 0, true,  false, 3, 0 },
    { 2, 6, false, false, 6, 0, false, true,  3, 0 },
    { 3, 6, false, false, 5, 0, false, false, 2, 0 },
    { 2, 6, false, false, 7, 0, true,  false, 2, 0 },
    { 1, 0, true,  true,  5, 6, false, false, 2, 3 },
    { 1, 0, true,  false, 7, 8, false, false, 2, 2 },
    { 1, 0, false, false, 7, 7, true,  false, 4, 0 },
    { 2, 6, false, false, 5, 5, true,  false, 2, 0 }
}
partition_table1
const uint32_t partition_table1[N_PARTITIONS] static
Initial value:
= {
   0x50505050U, 0x40404040U, 0x54545454U, 0x54505040U,
   0x50404000U, 0x55545450U, 0x55545040U, 0x54504000U,
   0x50400000U, 0x55555450U, 0x55544000U, 0x54400000U,
   0x55555440U, 0x55550000U, 0x55555500U, 0x55000000U,
   0x55150100U, 0x00004054U, 0x15010000U, 0x00405054U,
   0x00004050U, 0x15050100U, 0x05010000U, 0x40505054U,
   0x00404050U, 0x05010100U, 0x14141414U, 0x05141450U,
   0x01155440U, 0x00555500U, 0x15014054U, 0x05414150U,
   0x44444444U, 0x55005500U, 0x11441144U, 0x05055050U,
   0x05500550U, 0x11114444U, 0x41144114U, 0x44111144U,
   0x15055054U, 0x01055040U, 0x05041050U, 0x05455150U,
   0x14414114U, 0x50050550U, 0x41411414U, 0x00141400U,
   0x00041504U, 0x00105410U, 0x10541000U, 0x04150400U,
   0x50410514U, 0x41051450U, 0x05415014U, 0x14054150U,
   0x41050514U, 0x41505014U, 0x40011554U, 0x54150140U,
   0x50505500U, 0x00555050U, 0x15151010U, 0x54540404U,
}
Referenced by fetch_rgb_float_from_block(), and fetch_rgba_unorm_from_block().
partition_table2
const uint32_t partition_table2[N_PARTITIONS] static
Initial value:
= {
   0xaa685050U, 0x6a5a5040U, 0x5a5a4200U, 0x5450a0a8U,
   0xa5a50000U, 0xa0a05050U, 0x5555a0a0U, 0x5a5a5050U,
   0xaa550000U, 0xaa555500U, 0xaaaa5500U, 0x90909090U,
   0x94949494U, 0xa4a4a4a4U, 0xa9a59450U, 0x2a0a4250U,
   0xa5945040U, 0x0a425054U, 0xa5a5a500U, 0x55a0a0a0U,
   0xa8a85454U, 0x6a6a4040U, 0xa4a45000U, 0x1a1a0500U,
   0x0050a4a4U, 0xaaa59090U, 0x14696914U, 0x69691400U,
   0xa08585a0U, 0xaa821414U, 0x50a4a450U, 0x6a5a0200U,
   0xa9a58000U, 0x5090a0a8U, 0xa8a09050U, 0x24242424U,
   0x00aa5500U, 0x24924924U, 0x24499224U, 0x50a50a50U,
   0x500aa550U, 0xaaaa4444U, 0x66660000U, 0xa5a0a5a0U,
   0x50a050a0U, 0x69286928U, 0x44aaaa44U, 0x66666600U,
   0xaa444444U, 0x54a854a8U, 0x95809580U, 0x96969600U,
   0xa85454a8U, 0x80959580U, 0xaa141414U, 0x96960000U,
   0xaaaa1414U, 0xa05050a0U, 0xa0a5a5a0U, 0x96000000U,
   0x40804080U, 0xa9a8a9a8U, 0xaaaaaa44U, 0x2a4a5254U
}
Referenced by fetch_rgba_unorm_from_block().