Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_etc.h File Reference
#include <inttypes.h>
#include "glheader.h"
#include "texcompress.h"
#include "texstore.h"
Functions
GLboolean _mesa_texstore_etc1_rgb8 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rgb8 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_srgb8 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rgba8_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_srgb8_alpha8_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_r11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rg11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_signed_r11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_signed_rg11_eac (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_rgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_etc2_srgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
void _mesa_etc1_unpack_rgba8888 (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned src_width, unsigned src_height)
Decode texture data in format MESA_FORMAT_ETC1_RGB8 to MESA_FORMAT_ABGR8888.
void _mesa_unpack_etc2_format (uint8_t *dst_row, unsigned dst_stride, const uint8_t *src_row, unsigned src_stride, unsigned src_width, unsigned src_height, mesa_format format)
Decode texture data in any one of following formats: MESA_FORMAT_ETC2_RGB8 MESA_FORMAT_ETC2_SRGB8 MESA_FORMAT_ETC2_RGBA8_EAC MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC MESA_FORMAT_ETC2_R11_EAC MESA_FORMAT_ETC2_RG11_EAC MESA_FORMAT_ETC2_SIGNED_R11_EAC MESA_FORMAT_ETC2_SIGNED_RG11_EAC MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1
compressed_fetch_func _mesa_get_etc_fetch_func (mesa_format format)
Function Documentation
_mesa_etc1_unpack_rgba8888()
void _mesa_etc1_unpack_rgba8888 (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned src_width, unsigned src_height)
Decode texture data in format MESA_FORMAT_ETC1_RGB8 to MESA_FORMAT_ABGR8888.
The size of the source data must be a multiple of the ETC1 block size, which is 8, even if the texture image's dimensions are not aligned to 4. From the GL_OES_compressed_ETC1_RGB8_texture spec: The texture is described as a number of 4x4 pixel blocks. If the texture (or a particular mip-level) is smaller than 4 pixels in any dimension (such as a 2x2 or a 8x1 texture), the texture is found in the upper left part of the block(s), and the rest of the pixels are not used. For instance, a texture of size 4x2 will be placed in the upper half of a 4x4 block, and the lower half of the pixels in the block will not be accessed.
Parameters
src_width in pixels
src_height in pixels
dst_stride in bytes
References etc1_unpack_rgba8888().
_mesa_get_etc_fetch_func()
compressed_fetch_func _mesa_get_etc_fetch_func (mesa_format format)
References fetch_etc1_rgb8(), fetch_etc2_r11_eac(), fetch_etc2_rg11_eac(), fetch_etc2_rgb8(), fetch_etc2_rgb8_punchthrough_alpha1(), fetch_etc2_rgba8_eac(), fetch_etc2_signed_r11_eac(), fetch_etc2_signed_rg11_eac(), fetch_etc2_srgb8(), fetch_etc2_srgb8_alpha8_eac(), fetch_etc2_srgb8_punchthrough_alpha1(), MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, and MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_etc1_rgb8()
GLboolean _mesa_texstore_etc1_rgb8 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_r11_eac()
GLboolean _mesa_texstore_etc2_r11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rg11_eac()
GLboolean _mesa_texstore_etc2_rg11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rgb8()
GLboolean _mesa_texstore_etc2_rgb8 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rgb8_punchthrough_alpha1()
GLboolean _mesa_texstore_etc2_rgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_rgba8_eac()
GLboolean _mesa_texstore_etc2_rgba8_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_signed_r11_eac()
GLboolean _mesa_texstore_etc2_signed_r11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_signed_rg11_eac()
GLboolean _mesa_texstore_etc2_signed_rg11_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_srgb8()
GLboolean _mesa_texstore_etc2_srgb8 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_srgb8_alpha8_eac()
GLboolean _mesa_texstore_etc2_srgb8_alpha8_eac (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_texstore_etc2_srgb8_punchthrough_alpha1()
GLboolean _mesa_texstore_etc2_srgb8_punchthrough_alpha1 (TEXSTORE_PARAMS)
Referenced by texstore_compressed().
_mesa_unpack_etc2_format()
void _mesa_unpack_etc2_format (uint8_t * dst_row, unsigned dst_stride, const uint8_t * src_row, unsigned src_stride, unsigned src_width, unsigned src_height, mesa_format format)
Decode texture data in any one of following formats: MESA_FORMAT_ETC2_RGB8 MESA_FORMAT_ETC2_SRGB8 MESA_FORMAT_ETC2_RGBA8_EAC MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC MESA_FORMAT_ETC2_R11_EAC MESA_FORMAT_ETC2_RG11_EAC MESA_FORMAT_ETC2_SIGNED_R11_EAC MESA_FORMAT_ETC2_SIGNED_RG11_EAC MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1
The size of the source data must be a multiple of the ETC2 block size even if the texture image's dimensions are not aligned to 4.
Parameters
src_width in pixels
src_height in pixels
dst_stride in bytes
References etc2_unpack_r11(), etc2_unpack_rg11(), etc2_unpack_rgb8(), etc2_unpack_rgb8_punchthrough_alpha1(), etc2_unpack_rgba8(), etc2_unpack_signed_r11(), etc2_unpack_signed_rg11(), etc2_unpack_srgb8(), etc2_unpack_srgb8_alpha8(), etc2_unpack_srgb8_punchthrough_alpha1(), MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, and MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1.