Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_rgtc.h File Reference
#include "glheader.h"
#include "texstore.h"
Functions
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
compressed_fetch_func _mesa_get_compressed_rgtc_func (mesa_format format)
Function Documentation
_mesa_get_compressed_rgtc_func()
compressed_fetch_func _mesa_get_compressed_rgtc_func (mesa_format format)
References fetch_l_latc1(), fetch_la_latc2(), fetch_red_rgtc1(), fetch_rg_rgtc2(), fetch_signed_l_latc1(), fetch_signed_la_latc2(), fetch_signed_red_rgtc1(), fetch_signed_rg_rgtc2(), MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_R_RGTC1_SNORM, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_RG_RGTC2_SNORM, and MESA_FORMAT_RG_RGTC2_UNORM.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_red_rgtc1()
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_texstore(), extractsrc_u(), MESA_FORMAT_L_LATC1_UNORM, MESA_FORMAT_R_RGTC1_UNORM, and MESA_FORMAT_R_UNORM8.
Referenced by texstore_compressed().
_mesa_texstore_rg_rgtc2()
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_little_endian(), _mesa_texstore(), extractsrc_u(), MESA_FORMAT_A8L8_UNORM, MESA_FORMAT_G8R8_UNORM, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_LA_LATC2_UNORM, MESA_FORMAT_R8G8_UNORM, and MESA_FORMAT_RG_RGTC2_UNORM.
Referenced by texstore_compressed().
_mesa_texstore_signed_red_rgtc1()
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_texstore(), extractsrc_s(), MESA_FORMAT_L_LATC1_SNORM, MESA_FORMAT_R_FLOAT32, and MESA_FORMAT_R_RGTC1_SNORM.
Referenced by texstore_compressed().
_mesa_texstore_signed_rg_rgtc2()
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_texstore(), extractsrc_s(), MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_LATC2_SNORM, MESA_FORMAT_RG_FLOAT32, and MESA_FORMAT_RG_RGTC2_SNORM.
Referenced by texstore_compressed().