Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texcompress_bptc.h File Reference
#include <inttypes.h>
#include "glheader.h"
#include "texcompress.h"
#include "texstore.h"
Functions
GLboolean _mesa_texstore_bptc_rgba_unorm (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_bptc_rgb_signed_float (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_bptc_rgb_unsigned_float (TEXSTORE_PARAMS)
compressed_fetch_func _mesa_get_bptc_fetch_func (mesa_format format)
Function Documentation
_mesa_get_bptc_fetch_func()
compressed_fetch_func _mesa_get_bptc_fetch_func (mesa_format format)
References fetch_bptc_rgb_signed_float(), fetch_bptc_rgb_unsigned_float(), fetch_bptc_rgba_unorm(), fetch_bptc_srgb_alpha_unorm(), MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, MESA_FORMAT_BPTC_RGBA_UNORM, and MESA_FORMAT_BPTC_SRGB_ALPHA_UNORM.
Referenced by _mesa_get_compressed_fetch_func().
_mesa_texstore_bptc_rgb_signed_float()
GLboolean _mesa_texstore_bptc_rgb_signed_float (TEXSTORE_PARAMS)
References MESA_FORMAT_BPTC_RGB_SIGNED_FLOAT, and texstore_bptc_rgb_float().
Referenced by texstore_compressed().
_mesa_texstore_bptc_rgb_unsigned_float()
GLboolean _mesa_texstore_bptc_rgb_unsigned_float (TEXSTORE_PARAMS)
References MESA_FORMAT_BPTC_RGB_UNSIGNED_FLOAT, and texstore_bptc_rgb_float().
Referenced by texstore_compressed().
_mesa_texstore_bptc_rgba_unorm()
GLboolean _mesa_texstore_bptc_rgba_unorm (TEXSTORE_PARAMS)
References _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_little_endian(), _mesa_texstore(), compress_rgba_unorm(), MESA_FORMAT_A8B8G8R8_UNORM, and MESA_FORMAT_R8G8B8A8_UNORM.
Referenced by texstore_compressed().