Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texenv.h File Reference
#include "main/glheader.h"
Functions
void GLAPIENTRY _mesa_GetTexEnvfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexEnviv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_TexEnvf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexEnvfv (GLenum target, GLenum pname, const GLfloat *param)
void GLAPIENTRY _mesa_TexEnvi (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexEnviv (GLenum target, GLenum pname, const GLint *param)
Function Documentation
_mesa_GetTexEnvfv()
void GLAPIENTRY _mesa_GetTexEnvfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_clamp_fragment_color(), _mesa_get_current_tex_unit(), _mesa_update_state(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, gl_texture_unit::EnvColor, gl_texture_unit::EnvColorUnclamped, GET_CURRENT_CONTEXT, get_texenvi(), GLAPIENTRY, GLuint, if(), and gl_texture_unit::LodBias.
Referenced by _mesa_GetTexEnvxv().
_mesa_GetTexEnviv()
void GLAPIENTRY _mesa_GetTexEnviv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), gl_texture_unit::EnvColor, FLOAT_TO_INT, GET_CURRENT_CONTEXT, get_texenvi(), GLuint, if(), and gl_texture_unit::LodBias.
_mesa_TexEnvf()
void GLAPIENTRY _mesa_TexEnvf (GLenum target, GLenum pname, GLfloat param)
References _mesa_TexEnvfv(), and GLAPIENTRY.
Referenced by _mesa_TexEnvx(), _mesa_TexEnvxv(), and pop_texture_group().
_mesa_TexEnvfv()
void GLAPIENTRY _mesa_TexEnvfv (GLenum target, GLenum pname, const GLfloat * param)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_unit(), _NEW_POINT, _NEW_TEXTURE_STATE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, if(), gl_texture_unit::LodBias, MESA_VERBOSE, set_combiner_mode(), set_combiner_operand(), set_combiner_scale(), set_combiner_source(), set_env_color(), set_env_mode(), TE_ERROR, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_TexEnvf(), _mesa_TexEnvi(), _mesa_TexEnviv(), _mesa_TexEnvxv(), and pop_texture_group().
_mesa_TexEnvi()
void GLAPIENTRY _mesa_TexEnvi (GLenum target, GLenum pname, GLint param)
References _mesa_TexEnvfv(), and GLAPIENTRY.
Referenced by _mesa_PopAttrib(), and pop_texture_group().
_mesa_TexEnviv()
void GLAPIENTRY _mesa_TexEnviv (GLenum target, GLenum pname, const GLint * param)
References _mesa_TexEnvfv(), and INT_TO_FLOAT.