Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texformat.h File Reference
#include "formats.h"
Functions
mesa_format _mesa_choose_tex_format (struct gl_context *ctx, GLenum target, GLint internalFormat, GLenum format, GLenum type)
Choose an appropriate texture format given the format, type and internalFormat parameters passed to glTexImage().
Function Documentation
_mesa_choose_tex_format()
mesa_format _mesa_choose_tex_format (struct gl_context * ctx, GLenum target, GLint internalFormat, GLenum format, GLenum type)
Choose an appropriate texture format given the format, type and internalFormat parameters passed to glTexImage().
Parameters
ctx the GL context.
target a texture target (GL_TEXTURE_x)
internalFormat user's prefered internal texture format.
format incoming image pixel format.
type incoming image data type.
Returns
the closest mesa_format for the given format/type arguments
This is called via dd_function_table::ChooseTextureFormat. Hardware drivers may override this function with a specialized version.
References _mesa_enum_to_string(), _mesa_glenum_to_compressed_format(), _mesa_is_compressed_format(), _mesa_problem(), gl_context::Mesa_DXTn, MESA_FORMAT_A4R4G4B4_UNORM, MESA_FORMAT_A8B8G8R8_SNORM, MESA_FORMAT_A8B8G8R8_SRGB, MESA_FORMAT_A8B8G8R8_UNORM, MESA_FORMAT_A8L8_SNORM, MESA_FORMAT_A8L8_SRGB, MESA_FORMAT_A8R8G8B8_SRGB, MESA_FORMAT_A_FLOAT16, MESA_FORMAT_A_FLOAT32, MESA_FORMAT_A_SINT16, MESA_FORMAT_A_SINT32, MESA_FORMAT_A_SINT8, MESA_FORMAT_A_SNORM16, MESA_FORMAT_A_SNORM8, MESA_FORMAT_A_UINT16, MESA_FORMAT_A_UINT32, MESA_FORMAT_A_UINT8, MESA_FORMAT_A_UNORM16, MESA_FORMAT_A_UNORM8, MESA_FORMAT_B10G10R10A2_UINT, MESA_FORMAT_B10G10R10A2_UNORM, MESA_FORMAT_B2G3R3_UNORM, MESA_FORMAT_B4G4R4A4_UNORM, MESA_FORMAT_B5G5R5A1_UNORM, MESA_FORMAT_B5G6R5_UNORM, MESA_FORMAT_B8G8R8A8_SRGB, MESA_FORMAT_B8G8R8A8_UNORM, MESA_FORMAT_B8G8R8X8_UNORM, MESA_FORMAT_BGR_SRGB8, MESA_FORMAT_BGR_UNORM8, MESA_FORMAT_I_FLOAT16, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_I_SINT16, MESA_FORMAT_I_SINT32, MESA_FORMAT_I_SINT8, MESA_FORMAT_I_SNORM16, MESA_FORMAT_I_SNORM8, MESA_FORMAT_I_UINT16, MESA_FORMAT_I_UINT32, MESA_FORMAT_I_UINT8, MESA_FORMAT_I_UNORM16, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L16A16_UNORM, MESA_FORMAT_L4A4_UNORM, MESA_FORMAT_L8A8_SNORM, MESA_FORMAT_L8A8_SRGB, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_FLOAT16, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_L_SINT16, MESA_FORMAT_L_SINT32, MESA_FORMAT_L_SINT8, MESA_FORMAT_L_SNORM16, MESA_FORMAT_L_SNORM8, MESA_FORMAT_L_SRGB8, MESA_FORMAT_L_UINT16, MESA_FORMAT_L_UINT32, MESA_FORMAT_L_UINT8, MESA_FORMAT_L_UNORM16, MESA_FORMAT_L_UNORM8, MESA_FORMAT_LA_FLOAT16, MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_SINT16, MESA_FORMAT_LA_SINT32, MESA_FORMAT_LA_SINT8, MESA_FORMAT_LA_SNORM16, MESA_FORMAT_LA_UINT16, MESA_FORMAT_LA_UINT32, MESA_FORMAT_LA_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R10G10B10A2_UINT, MESA_FORMAT_R10G10B10A2_UNORM, MESA_FORMAT_R11G11B10_FLOAT, MESA_FORMAT_R16G16_SNORM, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R5G6B5_UNORM, MESA_FORMAT_R8G8_SNORM, MESA_FORMAT_R8G8_UNORM, MESA_FORMAT_R8G8B8A8_SNORM, MESA_FORMAT_R8G8B8A8_SRGB, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R8G8B8X8_SNORM, MESA_FORMAT_R8G8B8X8_SRGB, MESA_FORMAT_R8G8B8X8_UNORM, MESA_FORMAT_R9G9B9E5_FLOAT, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_RGTC1_UNORM, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_SNORM16, MESA_FORMAT_R_SNORM8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_RGTC2_UNORM, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGB_SINT16, MESA_FORMAT_RGB_SINT32, MESA_FORMAT_RGB_SINT8, MESA_FORMAT_RGB_SNORM16, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGB_UNORM8, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_SNORM16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBA_UNORM16, MESA_FORMAT_RGBX_FLOAT16, MESA_FORMAT_RGBX_FLOAT32, MESA_FORMAT_RGBX_SINT16, MESA_FORMAT_RGBX_SINT32, MESA_FORMAT_RGBX_SINT8, MESA_FORMAT_RGBX_SNORM16, MESA_FORMAT_RGBX_UINT16, MESA_FORMAT_RGBX_UINT32, MESA_FORMAT_RGBX_UINT8, MESA_FORMAT_RGBX_UNORM16, MESA_FORMAT_S8_UINT_Z24_UNORM, MESA_FORMAT_S_UINT8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_X8B8G8R8_SNORM, MESA_FORMAT_X8B8G8R8_SRGB, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z24_UNORM_S8_UINT, MESA_FORMAT_Z24_UNORM_X8_UINT, MESA_FORMAT_Z32_FLOAT_S8X24_UINT, MESA_FORMAT_Z_FLOAT32, MESA_FORMAT_Z_UNORM16, MESA_FORMAT_Z_UNORM32, RETURN_IF_SUPPORTED, gl_context::TextureFormatSupported, and void.