Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texgetimage.h File Reference
#include "glheader.h"
Functions
GLenum _mesa_base_pack_format (GLenum format)
Return a base GL format given the user-requested format for glGetTexImage().
void _mesa_GetTexSubImage_sw (struct gl_context *ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
This is the software fallback for Driver.GetTexSubImage().
void _mesa_GetCompressedTexSubImage_sw (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLint height, GLint depth, GLvoid *data)
This is the software fallback for Driver.GetCompressedTexSubImage().
void _mesa_get_compressed_texture_image (struct gl_context *ctx, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLenum target, GLint level, GLsizei bufSize, GLvoid *pixels, bool dsa)
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_GetTextureImage (GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_GetTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels)
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint lod, GLvoid *img)
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid *img)
void GLAPIENTRY _mesa_GetCompressedTextureImage (GLuint texture, GLint level, GLsizei bufSize, GLvoid *pixels)
void APIENTRY _mesa_GetCompressedTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void *pixels)
Function Documentation
_mesa_base_pack_format()
GLenum _mesa_base_pack_format (GLenum format)
Return a base GL format given the user-requested format for glGetTexImage().
_mesa_get_compressed_texture_image()
void _mesa_get_compressed_texture_image (struct gl_context * ctx, struct gl_texture_object * texObj, struct gl_texture_image * texImage, GLenum target, GLint level, GLsizei bufSize, GLvoid * pixels, bool dsa)
_mesa_GetCompressedTexImage()
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint lod, GLvoid * img)
References _mesa_error(), _mesa_get_current_tex_object(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, get_texture_image_dims(), getcompressedteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetCompressedTexSubImage_sw()
void _mesa_GetCompressedTexSubImage_sw (struct gl_context * ctx, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLint height, GLint depth, GLvoid * img)
This is the software fallback for Driver.GetCompressedTexSubImage().
All error checking will have been done before this routine is called.
References _mesa_compute_compressed_pixelstore(), _mesa_error(), _mesa_get_texture_dimensions(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, compressed_pixelstore::CopyBytesPerRow, compressed_pixelstore::CopyRowsPerSlice, compressed_pixelstore::CopySlices, gl_context::Driver, GLuint, MAP_INTERNAL, dd_function_table::MapBufferRange, dd_function_table::MapTextureImage, gl_context::Pack, gl_buffer_object::Size, compressed_pixelstore::SkipBytes, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, compressed_pixelstore::TotalBytesPerRow, compressed_pixelstore::TotalRowsPerSlice, dd_function_table::UnmapBuffer, and dd_function_table::UnmapTextureImage.
_mesa_GetCompressedTextureImage()
void GLAPIENTRY _mesa_GetCompressedTextureImage (GLuint texture, GLint level, GLsizei bufSize, GLvoid * pixels)
References _mesa_lookup_texture_err(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, get_texture_image_dims(), getcompressedteximage_error_check(), and gl_texture_object::Target.
_mesa_GetCompressedTextureSubImage()
void APIENTRY _mesa_GetCompressedTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void * pixels)
References _mesa_error(), _mesa_lookup_texture(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, getcompressedteximage_error_check(), and gl_texture_object::Target.
_mesa_GetnCompressedTexImageARB()
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid * img)
References _mesa_error(), _mesa_get_current_tex_object(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, get_texture_image_dims(), getcompressedteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetnTexImageARB()
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_error(), _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_texture_image(), get_texture_image_dims(), getteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetTexImage()
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_error(), _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_texture_image(), get_texture_image_dims(), getteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetTexSubImage_sw()
void _mesa_GetTexSubImage_sw (struct gl_context * ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage)
This is the software fallback for Driver.GetTexSubImage().
All error checking will have been done before this routine is called. We'll call ctx->Driver.MapTextureImage() to access the data, then unmap with ctx->Driver.UnmapTextureImage().
References _mesa_error(), _mesa_get_texture_dimensions(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba(), get_tex_stencil(), get_tex_ycbcr(), GLuint, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_context::Pack, gl_buffer_object::Size, gl_texture_object::Target, gl_texture_image::TexObject, and dd_function_table::UnmapBuffer.
_mesa_GetTextureImage()
void GLAPIENTRY _mesa_GetTextureImage (GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_error(), _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, get_texture_image(), get_texture_image_dims(), getteximage_error_check(), GLAPIENTRY, legal_getteximage_target(), and gl_texture_object::Target.
_mesa_GetTextureSubImage()
void GLAPIENTRY _mesa_GetTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void * pixels)
References _mesa_error(), _mesa_lookup_texture(), GET_CURRENT_CONTEXT, get_texture_image(), getteximage_error_check(), legal_getteximage_target(), and gl_texture_object::Target.