Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texgen.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_TexGenfv (GLenum coord, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexGeniv (GLenum coord, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TexGend (GLenum coord, GLenum pname, GLdouble param)
void GLAPIENTRY _mesa_TexGendv (GLenum coord, GLenum pname, const GLdouble *params)
void GLAPIENTRY _mesa_TexGenf (GLenum coord, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexGeni (GLenum coord, GLenum pname, GLint param)
void GLAPIENTRY _mesa_GetTexGendv (GLenum coord, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetTexGenfv (GLenum coord, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexGeniv (GLenum coord, GLenum pname, GLint *params)
void GLAPIENTRY _es_GetTexGenfv (GLenum coord, GLenum pname, GLfloat *params)
void GLAPIENTRY _es_TexGenf (GLenum coord, GLenum pname, GLfloat param)
void GLAPIENTRY _es_TexGenfv (GLenum coord, GLenum pname, const GLfloat *params)
Function Documentation
_es_GetTexGenfv()
void GLAPIENTRY _es_GetTexGenfv (GLenum coord, GLenum pname, GLfloat * params)
References _mesa_GetTexGenfv(), and GLAPIENTRY.
_es_TexGenf()
void GLAPIENTRY _es_TexGenf (GLenum coord, GLenum pname, GLfloat param)
References _mesa_error(), _mesa_TexGenf(), GET_CURRENT_CONTEXT, GL_TEXTURE_GEN_STR_OES, and GLAPIENTRY.
Referenced by _check_TexGeniOES(), _check_TexGenivOES(), _mesa_TexGenxOES(), and _mesa_TexGenxvOES().
_es_TexGenfv()
void GLAPIENTRY _es_TexGenfv (GLenum coord, GLenum pname, const GLfloat * params)
References _mesa_error(), _mesa_TexGenfv(), GET_CURRENT_CONTEXT, GL_TEXTURE_GEN_STR_OES, and GLAPIENTRY.
_mesa_GetTexGendv()
void GLAPIENTRY _mesa_GetTexGendv (GLenum coord, GLenum pname, GLdouble * params)
References _mesa_error(), _mesa_get_current_tex_unit(), COPY_4V, ENUM_TO_DOUBLE, gl_texgen::EyePlane, GET_CURRENT_CONTEXT, get_texgen(), GLAPIENTRY, gl_texgen::Mode, and gl_texgen::ObjectPlane.
_mesa_GetTexGenfv()
void GLAPIENTRY _mesa_GetTexGenfv (GLenum coord, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_current_tex_unit(), API_OPENGL_COMPAT, COPY_4V, ENUM_TO_FLOAT, gl_texgen::EyePlane, GET_CURRENT_CONTEXT, get_texgen(), GLAPIENTRY, gl_texgen::Mode, and gl_texgen::ObjectPlane.
Referenced by _es_GetTexGenfv().
_mesa_GetTexGeniv()
void GLAPIENTRY _mesa_GetTexGeniv (GLenum coord, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), API_OPENGL_COMPAT, gl_texgen::EyePlane, GET_CURRENT_CONTEXT, get_texgen(), gl_texgen::Mode, and gl_texgen::ObjectPlane.
Referenced by _check_GetTexGenivOES(), and _mesa_GetTexGenxvOES().
_mesa_TexGend()
void GLAPIENTRY _mesa_TexGend (GLenum coord, GLenum pname, GLdouble param)
References _mesa_TexGenfv(), and GLAPIENTRY.
_mesa_TexGendv()
void GLAPIENTRY _mesa_TexGendv (GLenum coord, GLenum pname, const GLdouble * params)
References _mesa_TexGenfv(), and GLAPIENTRY.
_mesa_TexGenf()
void GLAPIENTRY _mesa_TexGenf (GLenum coord, GLenum pname, GLfloat param)
References _mesa_TexGenfv(), and GLAPIENTRY.
Referenced by _es_TexGenf().
_mesa_TexGenfv()
void GLAPIENTRY _mesa_TexGenfv (GLenum coord, GLenum pname, const GLfloat * params)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_unit(), _mesa_transform_vector(), gl_texgen::_ModeBit, _NEW_TEXTURE_STATE, API_OPENGL_COMPAT, gl_texgen::EyePlane, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_texgen(), GLAPIENTRY, MESA_VERBOSE, gl_texgen::Mode, gl_texgen::ObjectPlane, TEST_EQ_4V, TEXGEN_EYE_LINEAR, TEXGEN_NORMAL_MAP_NV, TEXGEN_OBJ_LINEAR, TEXGEN_REFLECTION_MAP_NV, TEXGEN_SPHERE_MAP, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _es_TexGenfv(), _mesa_TexGend(), _mesa_TexGendv(), _mesa_TexGenf(), _mesa_TexGeniv(), and pop_texture_group().
_mesa_TexGeni()
void GLAPIENTRY _mesa_TexGeni (GLenum coord, GLenum pname, GLint param)
References _mesa_TexGeniv(), and GLAPIENTRY.
Referenced by pop_texture_group().
_mesa_TexGeniv()
void GLAPIENTRY _mesa_TexGeniv (GLenum coord, GLenum pname, const GLint * params)
References _mesa_TexGenfv(), and GLAPIENTRY.
Referenced by _mesa_TexGeni().