Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texgetimage.c File Reference
#include "glheader.h"
#include "bufferobj.h"
#include "enums.h"
#include "context.h"
#include "formats.h"
#include "format_unpack.h"
#include "glformats.h"
#include "image.h"
#include "mtypes.h"
#include "pack.h"
#include "pbo.h"
#include "pixelstore.h"
#include "texcompress.h"
#include "texgetimage.h"
#include "teximage.h"
#include "texobj.h"
#include "texstore.h"
#include "format_utils.h"
#include "pixeltransfer.h"
Functions
static GLboolean type_needs_clamping (GLenum type)
Code for glGetTexImage() and glGetCompressedTexImage().
static void get_tex_depth (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for depth/Z pixels.
static void get_tex_depth_stencil (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for depth/stencil pixels.
static void get_tex_stencil (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for stencil pixels.
static void get_tex_ycbcr (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for YCbCr pixels.
static bool teximage_needs_rebase (mesa_format texFormat, GLenum baseFormat, bool is_compressed, uint8_t *rebaseSwizzle)
Depending on the base format involved we may need to apply a rebase transform (for example: if we download to a Luminance format we want G=0 and B=0).
static void get_tex_rgba_compressed (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage, GLbitfield transferOps)
Get a color texture image with decompression.
GLenum _mesa_base_pack_format (GLenum format)
Return a base GL format given the user-requested format for glGetTexImage().
static void get_tex_rgba_uncompressed (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage, GLbitfield transferOps)
Get an uncompressed color texture image.
static void get_tex_rgba (struct gl_context *ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for color formats (RGBA, RGB, alpha, LA, etc).
static GLboolean get_tex_memcpy (struct gl_context *ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
Try to do glGetTexImage() with simple memcpy().
void _mesa_GetTexSubImage_sw (struct gl_context *ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
This is the software fallback for Driver.GetTexSubImage().
void _mesa_GetCompressedTexSubImage_sw (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLint height, GLint depth, GLvoid *img)
This is the software fallback for Driver.GetCompressedTexSubImage().
static GLboolean legal_getteximage_target (struct gl_context *ctx, GLenum target, bool dsa)
Validate the texture target enum supplied to glGetTex(ture)Image or glGetCompressedTex(ture)Image.
static struct gl_texture_image * select_tex_image (const struct gl_texture_object *texObj, GLenum target, GLint level, GLint zoffset)
Wrapper for _mesa_select_tex_image() which can handle target being GL_TEXTURE_CUBE_MAP in which case we use zoffset to select a cube face.
static bool dimensions_error_check (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, const char *caller)
Error-check the offset and size arguments to glGet[Compressed]TextureSubImage().
static bool pbo_error_check (struct gl_context *ctx, GLenum target, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, GLvoid *pixels, const char *caller)
Do PBO-related error checking for getting uncompressed images.
static bool getteximage_error_check (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels, const char *caller)
Do error checking for all (non-compressed) get-texture-image functions.
static void get_texture_image_dims (const struct gl_texture_object *texObj, GLenum target, GLint level, GLsizei *width, GLsizei *height, GLsizei *depth)
Return the width, height and depth of a texture image.
static void get_texture_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid *pixels, const char *caller)
Common code for all (uncompressed) get-texture-image functions.
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
void GLAPIENTRY _mesa_GetTextureImage (GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_GetTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels)
static GLsizei packed_compressed_size (GLuint dimensions, mesa_format format, GLsizei width, GLsizei height, GLsizei depth, const struct gl_pixelstore_attrib *packing)
Compute the number of bytes which will be written when retrieving a sub-region of a compressed texture.
static bool getcompressedteximage_error_check (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, GLvoid *pixels, const char *caller)
Do error checking for getting compressed texture images.
static void get_compressed_texture_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLvoid *pixels, const char *caller)
Common helper for all glGetCompressed-teximage functions.
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint level, GLvoid *pixels)
void GLAPIENTRY _mesa_GetCompressedTextureImage (GLuint texture, GLint level, GLsizei bufSize, GLvoid *pixels)
void APIENTRY _mesa_GetCompressedTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void *pixels)
Function Documentation
_mesa_base_pack_format()
GLenum _mesa_base_pack_format (GLenum format)
Return a base GL format given the user-requested format for glGetTexImage().
_mesa_GetCompressedTexImage()
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint level, GLvoid * pixels)
References _mesa_error(), _mesa_get_current_tex_object(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, get_texture_image_dims(), getcompressedteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetCompressedTexSubImage_sw()
void _mesa_GetCompressedTexSubImage_sw (struct gl_context * ctx, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLint height, GLint depth, GLvoid * img)
This is the software fallback for Driver.GetCompressedTexSubImage().
All error checking will have been done before this routine is called.
References _mesa_compute_compressed_pixelstore(), _mesa_error(), _mesa_get_texture_dimensions(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, compressed_pixelstore::CopyBytesPerRow, compressed_pixelstore::CopyRowsPerSlice, compressed_pixelstore::CopySlices, gl_context::Driver, GLuint, MAP_INTERNAL, dd_function_table::MapBufferRange, dd_function_table::MapTextureImage, gl_context::Pack, gl_buffer_object::Size, compressed_pixelstore::SkipBytes, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, compressed_pixelstore::TotalBytesPerRow, compressed_pixelstore::TotalRowsPerSlice, dd_function_table::UnmapBuffer, and dd_function_table::UnmapTextureImage.
_mesa_GetCompressedTextureImage()
void GLAPIENTRY _mesa_GetCompressedTextureImage (GLuint texture, GLint level, GLsizei bufSize, GLvoid * pixels)
References _mesa_lookup_texture_err(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, get_texture_image_dims(), getcompressedteximage_error_check(), and gl_texture_object::Target.
_mesa_GetCompressedTextureSubImage()
void APIENTRY _mesa_GetCompressedTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void * pixels)
References _mesa_error(), _mesa_lookup_texture(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, getcompressedteximage_error_check(), and gl_texture_object::Target.
_mesa_GetnCompressedTexImageARB()
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid * pixels)
References _mesa_error(), _mesa_get_current_tex_object(), get_compressed_texture_image(), GET_CURRENT_CONTEXT, get_texture_image_dims(), getcompressedteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetnTexImageARB()
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_error(), _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_texture_image(), get_texture_image_dims(), getteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetTexImage()
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_error(), _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_texture_image(), get_texture_image_dims(), getteximage_error_check(), GLAPIENTRY, and legal_getteximage_target().
_mesa_GetTexSubImage_sw()
void _mesa_GetTexSubImage_sw (struct gl_context * ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage)
This is the software fallback for Driver.GetTexSubImage().
All error checking will have been done before this routine is called. We'll call ctx->Driver.MapTextureImage() to access the data, then unmap with ctx->Driver.UnmapTextureImage().
References _mesa_error(), _mesa_get_texture_dimensions(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba(), get_tex_stencil(), get_tex_ycbcr(), GLuint, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_context::Pack, gl_buffer_object::Size, gl_texture_object::Target, gl_texture_image::TexObject, and dd_function_table::UnmapBuffer.
_mesa_GetTextureImage()
void GLAPIENTRY _mesa_GetTextureImage (GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_error(), _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, get_texture_image(), get_texture_image_dims(), getteximage_error_check(), GLAPIENTRY, legal_getteximage_target(), and gl_texture_object::Target.
_mesa_GetTextureSubImage()
void GLAPIENTRY _mesa_GetTextureSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void * pixels)
References _mesa_error(), _mesa_lookup_texture(), GET_CURRENT_CONTEXT, get_texture_image(), getteximage_error_check(), legal_getteximage_target(), and gl_texture_object::Target.
dimensions_error_check()
static bool dimensions_error_check (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, const char * caller) static
Error-check the offset and size arguments to glGet[Compressed]TextureSubImage().
Also checks if the specified texture image is missing.
Returns
true if error, false if no error.
References _mesa_error(), _mesa_get_format_block_size_3d(), _mesa_select_tex_image(), gl_texture_image::Depth, GLuint, gl_texture_image::Height, select_tex_image(), gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by getcompressedteximage_error_check(), and getteximage_error_check().
get_compressed_texture_image()
static void get_compressed_texture_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLvoid * pixels, const char * caller) static
Common helper for all glGetCompressed-teximage functions.
References _mesa_compute_compressed_pixelstore(), _mesa_debug(), _mesa_get_format_name(), _mesa_is_zero_size_texture(), _mesa_lock_texture(), _mesa_tex_target_to_face(), _mesa_unlock_texture(), gl_context::Driver, FLUSH_VERTICES, dd_function_table::GetCompressedTexSubImage, GLAPIENTRY, gl_texture_image::Height, gl_texture_object::Image, MESA_VERBOSE, gl_texture_object::Name, gl_context::Pack, select_tex_image(), gl_texture_image::TexFormat, compressed_pixelstore::TotalBytesPerRow, compressed_pixelstore::TotalRowsPerSlice, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_GetCompressedTexImage(), _mesa_GetCompressedTextureImage(), _mesa_GetCompressedTextureSubImage(), and _mesa_GetnCompressedTexImageARB().
get_tex_depth()
static void get_tex_depth (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for depth/Z pixels.
References _mesa_error(), _mesa_image_address(), _mesa_pack_depth_span(), _mesa_unpack_float_z_row(), gl_context::Driver, dd_function_table::MapTextureImage, gl_context::Pack, gl_texture_image::TexFormat, and dd_function_table::UnmapTextureImage.
Referenced by _mesa_GetTexSubImage_sw().
get_tex_depth_stencil()
static void get_tex_depth_stencil (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for depth/stencil pixels.
References _mesa_error(), _mesa_image_address(), _mesa_swap4(), _mesa_unpack_depth_stencil_row(), gl_context::Driver, GLuint, dd_function_table::MapTextureImage, gl_context::Pack, gl_pixelstore_attrib::SwapBytes, gl_texture_image::TexFormat, and dd_function_table::UnmapTextureImage.
Referenced by _mesa_GetTexSubImage_sw().
get_tex_memcpy()
static GLboolean get_tex_memcpy (struct gl_context * ctx, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
Try to do glGetTexImage() with simple memcpy().
Returns
GL_TRUE if done, GL_FALSE otherwise
References gl_texture_image::_BaseFormat, _mesa_error(), _mesa_format_matches_format_and_type(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_is_cube_face(), gl_context::Driver, GLuint, dd_function_table::MapTextureImage, gl_context::Pack, gl_pixelstore_attrib::SwapBytes, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and dd_function_table::UnmapTextureImage.
Referenced by _mesa_GetTexSubImage_sw().
get_tex_rgba()
static void get_tex_rgba (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for color formats (RGBA, RGB, alpha, LA, etc).
Compressed textures are handled here as well.
References _mesa_get_format_datatype(), _mesa_is_format_compressed(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), IMAGE_CLAMP_BIT, gl_texture_image::TexFormat, and type_needs_clamping().
Referenced by _mesa_GetTexSubImage_sw().
get_tex_rgba_compressed()
static void get_tex_rgba_compressed (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage, GLbitfield transferOps) static
Get a color texture image with decompression.
References _mesa_decompress_image(), _mesa_error(), _mesa_format_convert(), _mesa_format_from_format_and_type(), _mesa_get_format_base_format(), _mesa_get_srgb_format_linear(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_swap_bytes_2d_image(), gl_context::Driver, GLuint, dd_function_table::MapTextureImage, gl_context::Pack, RGBA32_FLOAT, gl_pixelstore_attrib::SwapBytes, gl_texture_image::TexFormat, teximage_needs_rebase(), and dd_function_table::UnmapTextureImage.
Referenced by get_tex_rgba().
get_tex_rgba_uncompressed()
static void get_tex_rgba_uncompressed (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage, GLbitfield transferOps) static
Get an uncompressed color texture image.
References gl_texture_image::_BaseFormat, _mesa_apply_rgba_transfer_ops(), _mesa_error(), _mesa_format_convert(), _mesa_format_from_format_and_type(), _mesa_get_srgb_format_linear(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_is_enum_format_integer(), _mesa_swap_bytes_2d_image(), gl_context::Driver, GLuint, dd_function_table::MapTextureImage, gl_context::Pack, RGBA32_FLOAT, gl_pixelstore_attrib::SwapBytes, gl_texture_image::TexFormat, teximage_needs_rebase(), dd_function_table::UnmapTextureImage, and void.
Referenced by get_tex_rgba().
get_tex_stencil()
static void get_tex_stencil (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for stencil pixels.
References _mesa_error(), _mesa_image_address(), _mesa_unpack_ubyte_stencil_row(), gl_context::Driver, GLuint, dd_function_table::MapTextureImage, gl_context::Pack, gl_texture_image::TexFormat, and dd_function_table::UnmapTextureImage.
Referenced by _mesa_GetTexSubImage_sw().
get_tex_ycbcr()
static void get_tex_ycbcr (struct gl_context * ctx, GLuint dimensions, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for YCbCr pixels.
References _mesa_error(), _mesa_image_address(), _mesa_swap2(), gl_context::Driver, GLushort, dd_function_table::MapTextureImage, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, gl_context::Pack, gl_pixelstore_attrib::SwapBytes, gl_texture_image::TexFormat, and dd_function_table::UnmapTextureImage.
Referenced by _mesa_GetTexSubImage_sw().
get_texture_image()
static void get_texture_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, GLvoid * pixels, const char * caller) static
Common code for all (uncompressed) get-texture-image functions.
Parameters
texObj the texture object (should not be null)
target user-provided target, or 0 for DSA
level image level.
format pixel data format for returned image.
type pixel data type for returned image.
bufSize size of the pixels data buffer.
pixels returned pixel data.
caller name of calling function
References _mesa_debug(), _mesa_get_format_name(), _mesa_image_image_stride(), _mesa_is_zero_size_texture(), _mesa_lock_texture(), _mesa_tex_target_to_face(), _mesa_unlock_texture(), gl_context::Driver, FLUSH_VERTICES, dd_function_table::GetTexSubImage, GLAPIENTRY, gl_texture_image::Height, gl_texture_object::Image, MESA_VERBOSE, gl_texture_object::Name, gl_context::Pack, select_tex_image(), gl_texture_image::TexFormat, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_GetnTexImageARB(), _mesa_GetTexImage(), _mesa_GetTextureImage(), and _mesa_GetTextureSubImage().
get_texture_image_dims()
static void get_texture_image_dims (const struct gl_texture_object * texObj, GLenum target, GLint level, GLsizei * width, GLsizei * height, GLsizei * depth) static
Return the width, height and depth of a texture image.
This function must be resilient to bad parameter values since this is called before full error checking.
References _mesa_select_tex_image(), gl_texture_image::Depth, gl_texture_image::Height, MAX_TEXTURE_LEVELS, and gl_texture_image::Width.
Referenced by _mesa_GetCompressedTexImage(), _mesa_GetCompressedTextureImage(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), _mesa_GetTexImage(), and _mesa_GetTextureImage().
getcompressedteximage_error_check()
static bool getcompressedteximage_error_check (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, GLvoid * pixels, const char * caller) static
Do error checking for getting compressed texture images.
Returns
true if any error, false if no errors.
References _mesa_check_disallowed_mapping(), _mesa_compressed_pixel_storage_error_check(), _mesa_error(), _mesa_get_texture_dimensions(), _mesa_is_bufferobj(), _mesa_is_format_compressed(), _mesa_max_texture_levels(), gl_pixelstore_attrib::BufferObj, dimensions_error_check(), GLuint, gl_context::Pack, packed_compressed_size(), select_tex_image(), gl_buffer_object::Size, gl_texture_object::Target, and gl_texture_image::TexFormat.
Referenced by _mesa_GetCompressedTexImage(), _mesa_GetCompressedTextureImage(), _mesa_GetCompressedTextureSubImage(), and _mesa_GetnCompressedTexImageARB().
getteximage_error_check()
static bool getteximage_error_check (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels, const char * caller) static
Do error checking for all (non-compressed) get-texture-image functions.
Returns
true if any error, false if no errors.
References _mesa_error(), _mesa_error_check_format_and_type(), _mesa_get_format_base_format(), _mesa_is_color_format(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), _mesa_is_enum_format_integer(), _mesa_is_format_integer(), _mesa_is_stencil_format(), _mesa_is_ycbcr_format(), _mesa_max_texture_levels(), gl_extensions::ARB_texture_stencil8, dimensions_error_check(), gl_context::Extensions, pbo_error_check(), select_tex_image(), gl_texture_object::Target, and gl_texture_image::TexFormat.
Referenced by _mesa_GetnTexImageARB(), _mesa_GetTexImage(), _mesa_GetTextureImage(), and _mesa_GetTextureSubImage().
legal_getteximage_target()
static GLboolean legal_getteximage_target (struct gl_context * ctx, GLenum target, bool dsa) static
Validate the texture target enum supplied to glGetTex(ture)Image or glGetCompressedTex(ture)Image.
References gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::EXT_texture_array, gl_context::Extensions, and gl_extensions::NV_texture_rectangle.
Referenced by _mesa_GetCompressedTexImage(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), _mesa_GetTexImage(), _mesa_GetTextureImage(), and _mesa_GetTextureSubImage().
packed_compressed_size()
static GLsizei packed_compressed_size (GLuint dimensions, mesa_format format, GLsizei width, GLsizei height, GLsizei depth, const struct gl_pixelstore_attrib * packing) static
Compute the number of bytes which will be written when retrieving a sub-region of a compressed texture.
References _mesa_compute_compressed_pixelstore(), compressed_pixelstore::CopyBytesPerRow, compressed_pixelstore::CopyRowsPerSlice, compressed_pixelstore::CopySlices, compressed_pixelstore::SkipBytes, compressed_pixelstore::TotalBytesPerRow, and compressed_pixelstore::TotalRowsPerSlice.
Referenced by getcompressedteximage_error_check().
pbo_error_check()
static bool pbo_error_check (struct gl_context * ctx, GLenum target, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei clientMemSize, GLvoid * pixels, const char * caller) static
Do PBO-related error checking for getting uncompressed images.
Returns
true if there was an error (or the GetTexImage is to be a no-op)
References _mesa_check_disallowed_mapping(), _mesa_error(), _mesa_is_bufferobj(), _mesa_validate_pbo_access(), gl_pixelstore_attrib::BufferObj, GLuint, and gl_context::Pack.
Referenced by getteximage_error_check().
select_tex_image()
static struct gl_texture_image* select_tex_image (const struct gl_texture_object * texObj, GLenum target, GLint level, GLint zoffset) static
Wrapper for _mesa_select_tex_image() which can handle target being GL_TEXTURE_CUBE_MAP in which case we use zoffset to select a cube face.
This can happen for glGetTextureImage and glGetTextureSubImage (DSA functions).
References _mesa_select_tex_image(), and MAX_TEXTURE_LEVELS.
Referenced by dimensions_error_check(), get_compressed_texture_image(), get_texture_image(), getcompressedteximage_error_check(), and getteximage_error_check().
teximage_needs_rebase()
static bool teximage_needs_rebase (mesa_format texFormat, GLenum baseFormat, bool is_compressed, uint8_t * rebaseSwizzle) static
Depending on the base format involved we may need to apply a rebase transform (for example: if we download to a Luminance format we want G=0 and B=0).
References _mesa_compute_rgba2base2rgba_component_mapping(), _mesa_get_format_base_format(), MESA_FORMAT_SWIZZLE_ONE, MESA_FORMAT_SWIZZLE_W, MESA_FORMAT_SWIZZLE_X, and MESA_FORMAT_SWIZZLE_ZERO.
Referenced by get_tex_rgba_compressed(), and get_tex_rgba_uncompressed().
type_needs_clamping()
static GLboolean type_needs_clamping (GLenum type) inline static
Code for glGetTexImage() and glGetCompressedTexImage().
Can the given type represent negative values?
Referenced by get_tex_rgba().