Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
teximage.c File Reference
Texture image-related functions.
#include <stdbool.h>
#include "glheader.h"
#include "bufferobj.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "framebuffer.h"
#include "hash.h"
#include "image.h"
#include "imports.h"
#include "macros.h"
#include "mipmap.h"
#include "multisample.h"
#include "pixelstore.h"
#include "state.h"
#include "texcompress.h"
#include "texcompress_cpal.h"
#include "teximage.h"
#include "texobj.h"
#include "texstate.h"
#include "texstorage.h"
#include "textureview.h"
#include "mtypes.h"
#include "glformats.h"
#include "texstore.h"
#include "pbo.h"
Data Structures
struct cb_info
Callback info for walking over FBO hash table.
Macros
#define NEW_COPY_TEX_STATE (_NEW_BUFFERS | _NEW_PIXEL)
State changes which we care about for glCopyTex[Sub]Image() calls.
Functions
static GLenum adjust_for_oes_float_texture (const struct gl_context *ctx, GLenum format, GLenum type)
Returns a corresponding internal floating point format for a given base format as specifed by OES_texture_float.
static void set_tex_image (struct gl_texture_object *tObj, GLenum target, GLint level, struct gl_texture_image *texImage)
Install gl_texture_image in a gl_texture_object according to the target and level parameters.
void _mesa_delete_texture_image (struct gl_context *ctx, struct gl_texture_image *texImage)
Free a gl_texture_image and associated data.
GLboolean _mesa_is_proxy_texture (GLenum target)
Test if a target is a proxy target.
bool _mesa_is_array_texture (GLenum target)
Test if a target is an array target.
bool _mesa_is_cube_map_texture (GLenum target)
Test if a target is a cube map.
static GLenum proxy_target (GLenum target)
Return the proxy target which corresponds to the given texture target.
struct gl_texture_image * _mesa_select_tex_image (const struct gl_texture_object *texObj, GLenum target, GLint level)
Get a texture image pointer from a texture object, given a texture target and mipmap level.
struct gl_texture_image * _mesa_get_tex_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level)
Like _mesa_select_tex_image() but if the image doesn't exist, allocate it and install it.
static struct gl_texture_image * get_proxy_tex_image (struct gl_context *ctx, GLenum target, GLint level)
Return pointer to the specified proxy texture image.
GLint _mesa_max_texture_levels (struct gl_context *ctx, GLenum target)
Get the maximum number of allowed mipmap levels.
GLint _mesa_get_texture_dimensions (GLenum target)
Return number of dimensions per mipmap level for the given texture target.
GLboolean _mesa_tex_target_is_layered (GLenum target)
Check if a texture target can have more than one layer.
GLuint _mesa_get_texture_layers (const struct gl_texture_object *texObj, GLint level)
Return the number of layers present in the given level of an array, cubemap or 3D texture.
GLsizei _mesa_get_tex_max_num_levels (GLenum target, GLsizei width, GLsizei height, GLsizei depth)
Return the maximum number of mipmap levels for the given target and the dimensions.
static void clear_teximage_fields (struct gl_texture_image *img)
Set the size and format-related fields of a gl_texture_image struct to zero.
static void init_teximage_fields_ms (struct gl_context *ctx, struct gl_texture_image *img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, mesa_format format, GLuint numSamples, GLboolean fixedSampleLocations)
Initialize basic fields of the gl_texture_image struct.
void _mesa_init_teximage_fields (struct gl_context *ctx, struct gl_texture_image *img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, mesa_format format)
void _mesa_clear_texture_image (struct gl_context *ctx, struct gl_texture_image *texImage)
Free and clear fields of the gl_texture_image struct.
GLboolean _mesa_legal_texture_dimensions (struct gl_context *ctx, GLenum target, GLint level, GLint width, GLint height, GLint depth, GLint border)
Check the width, height, depth and border of a texture image are legal.
static bool error_check_subtexture_negative_dimensions (struct gl_context *ctx, GLuint dims, GLsizei subWidth, GLsizei subHeight, GLsizei subDepth, const char *func)
static GLboolean error_check_subtexture_dimensions (struct gl_context *ctx, GLuint dims, const struct gl_texture_image *destImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei subWidth, GLsizei subHeight, GLsizei subDepth, const char *func)
Do error checking of xoffset, yoffset, zoffset, width, height and depth for glTexSubImage, glCopyTexSubImage and glCompressedTexSubImage.
GLboolean _mesa_test_proxy_teximage (struct gl_context *ctx, GLenum target, GLuint numLevels, GLint level, mesa_format format, GLuint numSamples, GLint width, GLint height, GLint depth)
This is the fallback for Driver.TestProxyTexImage() for doing device- specific texture image size checks.
static bool compressedteximage_only_format (const struct gl_context *ctx, GLenum format)
Return true if the format is only valid for glCompressedTexImage.
bool _mesa_format_no_online_compression (const struct gl_context *ctx, GLenum format)
Return true if the format doesn't support online compression.
static bool write_error (GLenum *err_ptr, GLenum error)
GLboolean _mesa_target_can_be_compressed (const struct gl_context *ctx, GLenum target, GLenum intFormat, GLenum *error)
Helper function to determine whether a target and specific compression format are supported.
static GLboolean legal_teximage_target (struct gl_context *ctx, GLuint dims, GLenum target)
Check if the given texture target value is legal for a glTexImage1/2/3D call.
static GLboolean legal_texsubimage_target (struct gl_context *ctx, GLuint dims, GLenum target, bool dsa)
Check if the given texture target value is legal for a glTexSubImage, glCopyTexSubImage or glCopyTexImage call.
static GLboolean mutable_tex_object (struct gl_context *ctx, GLenum target)
Helper function to determine if a texture object is mutable (in terms of GL_ARB_texture_storage).
static GLuint compressed_tex_size (GLsizei width, GLsizei height, GLsizei depth, GLenum glformat)
Return expected size of a compressed texture.
bool _mesa_legal_texture_base_format_for_target (struct gl_context *ctx, GLenum target, GLenum internalFormat)
Verify that a texture format is valid with a particular target.
static bool texture_formats_agree (GLenum internalFormat, GLenum format)
static bool texture_format_error_check_gles (struct gl_context *ctx, GLenum format, GLenum type, GLenum internalFormat, GLuint dimensions, const char *callerName)
Test the combination of format, type and internal format arguments of different texture operations on GLES.
static GLboolean texture_error_check (struct gl_context *ctx, GLuint dimensions, GLenum target, GLint level, GLint internalFormat, GLenum format, GLenum type, GLint width, GLint height, GLint depth, GLint border, const GLvoid *pixels)
Test the glTexImage[123]D() parameters for errors.
static GLenum compressed_texture_error_check (struct gl_context *ctx, GLint dimensions, GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
Error checking for glCompressedTexImage[123]D().
static GLboolean texsubimage_error_check (struct gl_context *ctx, GLuint dimensions, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, bool dsa, const char *callerName)
Test glTexSubImage[123]D() parameters for errors.
static GLboolean copytexture_error_check (struct gl_context *ctx, GLuint dimensions, GLenum target, GLint level, GLint internalFormat, GLint width, GLint height, GLint border)
Test glCopyTexImage[12]D() parameters for errors.
static GLboolean copytexsubimage_error_check (struct gl_context *ctx, GLuint dimensions, const struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, const char *caller)
Test glCopyTexSubImage[12]D() parameters for errors.
static void check_rtt_cb (GLuint key, void *data, void *userData)
Check render to texture callback.
void _mesa_update_fbo_texture (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
When a texture image is specified we have to check if it's bound to any framebuffer objects (render to texture) in order to detect changes in size or format since that effects FBO completeness.
static void check_gen_mipmap (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, GLint level)
If the texture object's GenerateMipmap flag is set and we've changed the texture base level image, regenerate the rest of the mipmap levels now.
static GLenum override_internal_format (GLenum internalFormat, GLint width, GLint height)
Debug helper: override the user-requested internal format.
mesa_format _mesa_choose_texture_format (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLenum internalFormat, GLenum format, GLenum type)
Choose the actual hardware format for a texture image.
static void strip_texture_border (GLenum target, GLint *width, GLint *height, GLint *depth, const struct gl_pixelstore_attrib *unpack, struct gl_pixelstore_attrib *unpackNew)
Adjust pixel unpack params and image dimensions to strip off the one-pixel texture border.
static void teximage (struct gl_context *ctx, GLboolean compressed, GLuint dims, GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, GLsizei imageSize, const GLvoid *pixels)
Common code to implement all the glTexImage1D/2D/3D functions as well as glCompressedTexImage1D/2D/3D.
void GLAPIENTRY _mesa_TexImage1D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage2D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage3D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage3DEXT (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_EGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
void _mesa_texture_sub_image (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, bool dsa)
Helper that implements the glTexSubImage1/2/3D() and glTextureSubImage1/2/3D() functions.
static void texsubimage (struct gl_context *ctx, GLuint dims, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const char *callerName)
Implement all the glTexSubImage1/2/3D() functions.
static void texturesubimage (struct gl_context *ctx, GLuint dims, GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const char *callerName)
Implement all the glTextureSubImage1/2/3D() functions.
void GLAPIENTRY _mesa_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
static struct gl_renderbuffer * get_copy_tex_image_source (struct gl_context *ctx, mesa_format texFormat)
For glCopyTexSubImage, return the source renderbuffer to copy texel data from.
static void copytexsubimage_by_slice (struct gl_context *ctx, struct gl_texture_image *texImage, GLuint dims, GLint xoffset, GLint yoffset, GLint zoffset, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height)
static GLboolean formats_differ_in_component_sizes (mesa_format f1, mesa_format f2)
static bool can_avoid_reallocation (const struct gl_texture_image *texImage, GLenum internalFormat, mesa_format texFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
Check if the given texture format and size arguments match those of the texture image.
static void copyteximage (struct gl_context *ctx, GLuint dims, GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
Implement the glCopyTexImage1/2D() functions.
void GLAPIENTRY _mesa_CopyTexImage1D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border)
void GLAPIENTRY _mesa_CopyTexImage2D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
void _mesa_copy_texture_sub_image (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height, const char *caller)
Implementation for glCopyTex(ture)SubImage1/2/3D() functions.
void GLAPIENTRY _mesa_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
static bool check_clear_tex_image (struct gl_context *ctx, const char *function, struct gl_texture_image *texImage, GLenum format, GLenum type, const void *data, GLubyte *clearValue)
static struct gl_texture_object * get_tex_obj_for_clear (struct gl_context *ctx, const char *function, GLuint texture)
static int get_tex_images_for_clear (struct gl_context *ctx, const char *function, struct gl_texture_object *texObj, GLint level, struct gl_texture_image **texImages)
void GLAPIENTRY _mesa_ClearTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data)
void GLAPIENTRY _mesa_ClearTexImage (GLuint texture, GLint level, GLenum format, GLenum type, const void *data)
static GLboolean compressed_subtexture_target_check (struct gl_context *ctx, GLenum target, GLint dims, GLenum format, bool dsa, const char *caller)
Target checking for glCompressedTexSubImage[123]D().
static GLboolean compressed_subtexture_error_check (struct gl_context *ctx, GLint dims, const struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data, const char *callerName)
Error checking for glCompressedTexSubImage[123]D().
void GLAPIENTRY _mesa_CompressedTexImage1D (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexImage2D (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexImage3D (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
void _mesa_compressed_texture_sub_image (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Common helper for glCompressedTexSubImage1/2/3D() and glCompressedTextureSubImage1/2/3D().
void GLAPIENTRY _mesa_CompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
static mesa_format get_texbuffer_format (const struct gl_context *ctx, GLenum internalFormat)
mesa_format _mesa_validate_texbuffer_format (const struct gl_context *ctx, GLenum internalFormat)
static void texture_buffer_range (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum internalFormat, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, const char *caller)
Do work common to glTexBuffer, glTexBufferRange, glTextureBuffer and glTextureBufferRange, including some error checking.
static bool check_texture_buffer_target (struct gl_context *ctx, GLenum target, const char *caller)
Make sure the texture buffer target is GL_TEXTURE_BUFFER.
static bool check_texture_buffer_range (struct gl_context *ctx, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, const char *caller)
Check for errors related to the texture buffer range.
void GLAPIENTRY _mesa_TexBuffer (GLenum target, GLenum internalFormat, GLuint buffer)
GL_ARB_texture_buffer_object.
void GLAPIENTRY _mesa_TexBufferRange (GLenum target, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GL_ARB_texture_buffer_range.
void GLAPIENTRY _mesa_TextureBuffer (GLuint texture, GLenum internalFormat, GLuint buffer)
void GLAPIENTRY _mesa_TextureBufferRange (GLuint texture, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GLboolean _mesa_is_renderable_texture_format (struct gl_context *ctx, GLenum internalformat)
static GLboolean check_multisample_target (GLuint dims, GLenum target, bool dsa)
GL_ARB_texture_multisample.
static void texture_image_multisample (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations, GLboolean immutable, const char *func)
void GLAPIENTRY _mesa_TexImage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexImage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
static bool valid_texstorage_ms_parameters (GLsizei width, GLsizei height, GLsizei depth, GLsizei samples, unsigned dims)
void GLAPIENTRY _mesa_TexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TextureStorage2DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TextureStorage3DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
Detailed Description
Texture image-related functions.
Macro Definition Documentation
NEW_COPY_TEX_STATE
#define NEW_COPY_TEX_STATE (_NEW_BUFFERS | _NEW_PIXEL)
State changes which we care about for glCopyTex[Sub]Image() calls.
In particular, we care about pixel transfer state and buffer state (such as glReadBuffer to make sure we read from the right renderbuffer).
Referenced by _mesa_copy_texture_sub_image(), and copyteximage().
Function Documentation
_mesa_choose_texture_format()
mesa_format _mesa_choose_texture_format (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLenum internalFormat, GLenum format, GLenum type)
Choose the actual hardware format for a texture image.
Try to use the same format as the previous image level when possible. Otherwise, ask the driver for the best format. It's important to try to choose a consistant format for all levels for efficient texture memory layout/allocation. In particular, this comes up during automatic mipmap generation.
References _mesa_enum_to_string(), _mesa_select_tex_image(), _mesa_warning(), dd_function_table::ChooseTextureFormat, gl_context::Driver, gl_texture_image::InternalFormat, gl_context::Mesa_DXTn, MESA_FORMAT_NONE, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_is_zero_size_texture(), _mesa_texture_storage(), _mesa_TextureView(), copyteximage(), teximage(), and texture_image_multisample().
_mesa_clear_texture_image()
void _mesa_clear_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free and clear fields of the gl_texture_image struct.
Parameters
ctx GL context.
texImage texture image structure to be cleared.
After the call, texImage will have no data associated with it. Its fields are cleared so that its parent object will test incomplete.
References clear_teximage_fields(), gl_context::Driver, and dd_function_table::FreeTextureImageBuffer.
Referenced by _mesa_clear_texture_object(), _mesa_is_zero_size_texture(), and clear_texture_fields().
_mesa_ClearTexImage()
void GLAPIENTRY _mesa_ClearTexImage (GLuint texture, GLint level, GLenum format, GLenum type, const void * data)
References _mesa_lock_texture(), _mesa_unlock_texture(), gl_texture_image::Border, check_clear_tex_image(), dd_function_table::ClearTexSubImage, cb_info::ctx, gl_texture_image::Depth, gl_context::Driver, GET_CURRENT_CONTEXT, get_tex_images_for_clear(), get_tex_obj_for_clear(), gl_texture_image::Height, MAX_FACES, MAX_PIXEL_BYTES, cb_info::texObj, and gl_texture_image::Width.
Referenced by _mesa_base_tex_image().
_mesa_ClearTexSubImage()
void GLAPIENTRY _mesa_ClearTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * data)
References _mesa_error(), _mesa_lock_texture(), _mesa_unlock_texture(), gl_texture_image::Border, check_clear_tex_image(), dd_function_table::ClearTexSubImage, cb_info::ctx, gl_texture_image::Depth, gl_context::Driver, GET_CURRENT_CONTEXT, get_tex_images_for_clear(), get_tex_obj_for_clear(), GLAPIENTRY, gl_texture_image::Height, MAX_FACES, MAX_PIXEL_BYTES, cb_info::texObj, and gl_texture_image::Width.
Referenced by _mesa_base_tex_image().
_mesa_compressed_texture_sub_image()
void _mesa_compressed_texture_sub_image (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, struct gl_texture_image * texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
Common helper for glCompressedTexSubImage1/2/3D() and glCompressedTextureSubImage1/2/3D().
References _mesa_lock_texture(), _mesa_unlock_texture(), check_gen_mipmap(), dd_function_table::CompressedTexSubImage, gl_context::Driver, FLUSH_VERTICES, and GLAPIENTRY.
Referenced by _mesa_base_tex_image(), _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), and _mesa_CompressedTextureSubImage3D().
_mesa_CompressedTexImage1D()
void GLAPIENTRY _mesa_CompressedTexImage1D (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexImage2D()
void GLAPIENTRY _mesa_CompressedTexImage2D (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexImage3D()
void GLAPIENTRY _mesa_CompressedTexImage3D (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data)
References cb_info::ctx, GET_CURRENT_CONTEXT, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexSubImage1D()
void GLAPIENTRY _mesa_CompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexSubImage2D()
void GLAPIENTRY _mesa_CompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexSubImage3D()
void GLAPIENTRY _mesa_CompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTextureSubImage1D()
void GLAPIENTRY _mesa_CompressedTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_lookup_texture_err(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTextureSubImage2D()
void GLAPIENTRY _mesa_CompressedTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_lookup_texture_err(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTextureSubImage3D()
void GLAPIENTRY _mesa_CompressedTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_cube_level_complete(), _mesa_error(), _mesa_format_image_size(), _mesa_lookup_texture_err(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, gl_texture_image::Height, gl_texture_object::Image, cb_info::level, gl_texture_object::Target, gl_texture_image::TexFormat, cb_info::texObj, and gl_texture_image::Width.
Referenced by _mesa_base_tex_image().
_mesa_copy_texture_sub_image()
void _mesa_copy_texture_sub_image (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height, const char * caller)
Implementation for glCopyTex(ture)SubImage1/2/3D() functions.
References _mesa_clip_copytexsubimage(), _mesa_debug(), _mesa_enum_to_string(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), _mesa_update_state(), gl_texture_image::Border, check_gen_mipmap(), copytexsubimage_by_slice(), copytexsubimage_error_check(), FLUSH_VERTICES, get_copy_tex_image_source(), GLAPIENTRY, MESA_VERBOSE, NEW_COPY_TEX_STATE, gl_context::NewState, gl_texture_image::TexFormat, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_base_tex_image(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), and copyteximage().
_mesa_CopyTexImage1D()
void GLAPIENTRY _mesa_CopyTexImage1D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border)
References copyteximage(), cb_info::ctx, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexImage2D()
void GLAPIENTRY _mesa_CopyTexImage2D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
References copyteximage(), cb_info::ctx, and GET_CURRENT_CONTEXT.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexSubImage1D()
void GLAPIENTRY _mesa_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexSubImage2D()
void GLAPIENTRY _mesa_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexSubImage3D()
void GLAPIENTRY _mesa_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTextureSubImage1D()
void GLAPIENTRY _mesa_CopyTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTextureSubImage2D()
void GLAPIENTRY _mesa_CopyTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTextureSubImage3D()
void GLAPIENTRY _mesa_CopyTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, legal_texsubimage_target(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_delete_texture_image()
void _mesa_delete_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free a gl_texture_image and associated data.
This function is a fallback called via ctx->Driver.DeleteTextureImage().
Parameters
texImage texture image.
Free the texture image structure and the associated image data.
References gl_context::Driver, and dd_function_table::FreeTextureImageBuffer.
Referenced by _mesa_is_zero_size_texture().
_mesa_EGLImageTargetTexture2DOES()
void GLAPIENTRY _mesa_EGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
References _mesa_dirty_texobj(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_get_tex_image(), _mesa_is_gles(), _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state(), _NEW_PIXEL, cb_info::ctx, gl_context::Driver, dd_function_table::EGLImageTargetTexture2D, gl_context::Extensions, FLUSH_VERTICES, dd_function_table::FreeTextureImageBuffer, GET_CURRENT_CONTEXT, GL_TEXTURE_EXTERNAL_OES, gl_texture_object::Immutable, gl_context::NewState, gl_extensions::OES_EGL_image, gl_extensions::OES_EGL_image_external, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_format_no_online_compression()
bool _mesa_format_no_online_compression (const struct gl_context * ctx, GLenum format)
Return true if the format doesn't support online compression.
References _mesa_is_astc_format(), _mesa_is_etc2_format(), and compressedteximage_only_format().
Referenced by _is_resource_supported(), _mesa_base_tex_image(), copytexsubimage_error_check(), copytexture_error_check(), texsubimage_error_check(), and texture_error_check().
_mesa_get_tex_image()
struct gl_texture_image* _mesa_get_tex_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level)
Like _mesa_select_tex_image() but if the image doesn't exist, allocate it and install it.
Only return NULL if passed a bad parameter or run out of memory.
References _mesa_error(), _mesa_select_tex_image(), gl_context::Driver, dd_function_table::NewTextureImage, and set_tex_image().
Referenced by _mesa_EGLImageTargetTexture2DOES(), _mesa_get_fallback_texture(), _mesa_is_zero_size_texture(), _mesa_VDPAUMapSurfacesNV(), build_bitmap_atlas(), copyteximage(), get_tex_image(), initialize_texture_fields(), prepare_mipmap_level(), teximage(), and texture_image_multisample().
_mesa_get_tex_max_num_levels()
GLsizei _mesa_get_tex_max_num_levels (GLenum target, GLsizei width, GLsizei height, GLsizei depth)
Return the maximum number of mipmap levels for the given target and the dimensions.
The dimensions are expected not to include the border.
References _mesa_components_in_format(), _mesa_logbase2(), and GL_TEXTURE_EXTERNAL_OES.
Referenced by _mesa_base_tex_image(), init_teximage_fields_ms(), and tex_storage_error_check().
_mesa_get_texture_dimensions()
GLint _mesa_get_texture_dimensions (GLenum target)
Return number of dimensions per mipmap level for the given texture target.
References _mesa_problem(), and GL_TEXTURE_EXTERNAL_OES.
Referenced by _get_target_dimensions(), _mesa_base_tex_image(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetTexSubImage_sw(), and getcompressedteximage_error_check().
_mesa_get_texture_layers()
GLuint _mesa_get_texture_layers (const struct gl_texture_object * texObj, GLint level)
Return the number of layers present in the given level of an array, cubemap or 3D texture.
If the texture is not layered return zero.
References gl_texture_image::Depth, GL_TEXTURE_EXTERNAL_OES, gl_texture_image::Height, gl_texture_object::Image, MAX_TEXTURE_LEVELS, and gl_texture_object::Target.
Referenced by _mesa_base_tex_image(), and _mesa_is_image_unit_valid().
_mesa_init_teximage_fields()
void _mesa_init_teximage_fields (struct gl_context * ctx, struct gl_texture_image * img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, mesa_format format)
References init_teximage_fields_ms().
Referenced by _mesa_get_fallback_texture(), _mesa_is_zero_size_texture(), build_bitmap_atlas(), copyteximage(), initialize_texture_fields(), prepare_mipmap_level(), teximage(), and texture_image_multisample().
_mesa_is_array_texture()
bool _mesa_is_array_texture (GLenum target)
Test if a target is an array target.
Parameters
target texture target.
Returns
true if the target is an array target, false otherwise.
Referenced by _mesa_GetInternalformativ(), and _mesa_is_zero_size_texture().
_mesa_is_cube_map_texture()
bool _mesa_is_cube_map_texture (GLenum target)
Test if a target is a cube map.
Parameters
target texture target.
Returns
true if the target is a cube map, false otherwise.
Referenced by _mesa_base_tex_image(), and _mesa_GetInternalformativ().
_mesa_is_proxy_texture()
GLboolean _mesa_is_proxy_texture (GLenum target)
Test if a target is a proxy target.
Parameters
target texture target.
Returns
GL_TRUE if the target is a proxy target, GL_FALSE otherwise.
References NUM_TEXTURE_TARGETS.
Referenced by _mesa_is_zero_size_texture(), _mesa_texture_storage(), get_tex_level_parameter_image(), tex_storage_error_check(), teximage(), and texture_image_multisample().
_mesa_is_renderable_texture_format()
GLboolean _mesa_is_renderable_texture_format (struct gl_context * ctx, GLenum internalformat)
References _mesa_base_fbo_format(), gl_extensions::ARB_texture_stencil8, and gl_context::Extensions.
Referenced by _is_resource_supported(), _mesa_base_tex_image(), and texture_image_multisample().
_mesa_legal_texture_base_format_for_target()
bool _mesa_legal_texture_base_format_for_target (struct gl_context * ctx, GLenum target, GLenum internalFormat)
Verify that a texture format is valid with a particular target.
In particular, textures with base format of GL_DEPTH_COMPONENT or GL_DEPTH_STENCIL are only valid with certain, context dependent texture targets.
Parameters
ctx GL context
target Texture target
internalFormat Internal format of the texture image
Returns
true if the combination is legal, false otherwise.
References _mesa_base_tex_format(), _mesa_has_texture_cube_map_array(), _mesa_is_cube_face(), gl_context::API, API_OPENGLES2, gl_extensions::EXT_gpu_shader4, gl_context::Extensions, gl_extensions::OES_depth_texture_cube_map, and gl_context::Version.
Referenced by _is_resource_supported(), _mesa_base_tex_image(), tex_storage_error_check(), and texture_error_check().
_mesa_legal_texture_dimensions()
GLboolean _mesa_legal_texture_dimensions (struct gl_context * ctx, GLenum target, GLint level, GLint width, GLint height, GLint depth, GLint border)
Check the width, height, depth and border of a texture image are legal.
Used by all the glTexImage, glCompressedTexImage and glCopyTexImage functions. The target and level parameters will have already been validated.
Returns
GL_TRUE if size is OK, GL_FALSE otherwise.
References _mesa_is_pow_two(), _mesa_problem(), gl_extensions::ARB_texture_non_power_of_two, gl_context::Const, gl_context::Extensions, gl_constants::Max3DTextureLevels, gl_constants::MaxArrayTextureLayers, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, and gl_constants::MaxTextureRectSize.
Referenced by _mesa_base_tex_image(), _mesa_texture_storage(), _mesa_TextureView(), copyteximage(), teximage(), and texture_image_multisample().
_mesa_max_texture_levels()
GLint _mesa_max_texture_levels (struct gl_context * ctx, GLenum target)
Get the maximum number of allowed mipmap levels.
Parameters
ctx GL context.
target texture target.
Returns
the maximum number of allowed mipmap levels for the given texture target, or zero if passed a bad target.
See also
gl_constants.
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles31(), gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_context::Const, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_constants::Max3DTextureLevels, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, and gl_extensions::NV_texture_rectangle.
Referenced by _mesa_base_tex_image(), _mesa_generate_mipmap(), check_level(), compressed_subtexture_error_check(), compressed_texture_error_check(), copytexsubimage_error_check(), copytexture_error_check(), get_tex_level_parameteriv(), getcompressedteximage_error_check(), getteximage_error_check(), tex_storage_error_check(), texsubimage_error_check(), and texture_error_check().
_mesa_select_tex_image()
struct gl_texture_image* _mesa_select_tex_image (const struct gl_texture_object * texObj, GLenum target, GLint level)
Get a texture image pointer from a texture object, given a texture target and mipmap level.
The target and level parameters should have already been error-checked.
Parameters
texObj texture unit.
target texture target.
level image level.
Returns
pointer to the texture image structure, or NULL on failure.
References _mesa_tex_target_to_face(), GLuint, gl_texture_object::Image, and MAX_TEXTURE_LEVELS.
Referenced by _mesa_choose_texture_format(), _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), _mesa_CompressedTextureSubImage3D(), _mesa_copy_texture_sub_image(), _mesa_generate_mipmap(), _mesa_generate_texture_mipmap(), _mesa_get_framebuffer_attachment_parameter(), _mesa_get_tex_image(), _mesa_is_zero_size_texture(), _mesa_prepare_mipmap_levels(), _mesa_set_texture_view_state(), _mesa_TextureView(), _mesa_VDPAUUnmapSurfacesNV(), compressed_subtexture_error_check(), copyteximage(), copytexsubimage_error_check(), dimensions_error_check(), generate_mipmap_compressed(), generate_mipmap_uncompressed(), get_tex_images_for_clear(), get_tex_level_parameter_image(), get_texture_image_dims(), prepare_target(), select_tex_image(), texsubimage(), texsubimage_error_check(), and texturesubimage().
_mesa_target_can_be_compressed()
GLboolean _mesa_target_can_be_compressed (const struct gl_context * ctx, GLenum target, GLenum intFormat, GLenum * error)
Helper function to determine whether a target and specific compression format are supported.
The error parameter returns GL_NO_ERROR if the target can be compressed. Otherwise it returns either GL_INVALID_OPERATION or GL_INVALID_ENUM, whichever is more appropriate.
References _mesa_get_format_layout(), _mesa_glenum_to_compressed_format(), _mesa_has_texture_cube_map_array(), _mesa_is_gles3(), gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_cube_map, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::KHR_texture_compression_astc_hdr, gl_extensions::KHR_texture_compression_astc_sliced_3d, MESA_FORMAT_LAYOUT_ASTC, MESA_FORMAT_LAYOUT_BPTC, MESA_FORMAT_LAYOUT_ETC2, and write_error().
Referenced by _is_resource_supported(), _mesa_base_tex_image(), compressed_texture_error_check(), copytexture_error_check(), tex_storage_error_check(), and texture_error_check().
_mesa_test_proxy_teximage()
GLboolean _mesa_test_proxy_teximage (struct gl_context * ctx, GLenum target, GLuint numLevels, GLint level, mesa_format format, GLuint numSamples, GLint width, GLint height, GLint depth)
This is the fallback for Driver.TestProxyTexImage() for doing device- specific texture image size checks.
A hardware driver might override this function if, for example, the max 3D texture size is 512x512x64 (i.e. not a cube).
Note that width, height, depth == 0 is not an error. However, a texture with zero width/height/depth will be considered "incomplete" and texturing will effectively be disabled.
Parameters
target any texture target/type
numLevels number of mipmap levels in the texture or 0 if not known
level as passed to glTexImage
format the MESA_FORMAT_x for the tex image
numSamples number of samples per texel
width as passed to glTexImage
height as passed to glTexImage
depth as passed to glTexImage
Returns
GL_TRUE if the image is acceptable, GL_FALSE if not acceptable.
References _mesa_format_image_size64(), _mesa_next_mipmap_level_size(), _mesa_num_tex_faces(), gl_context::Const, and gl_constants::MaxTextureMbytes.
Referenced by _mesa_base_tex_image().
_mesa_tex_target_is_layered()
GLboolean _mesa_tex_target_is_layered (GLenum target)
Check if a texture target can have more than one layer.
References GL_TEXTURE_EXTERNAL_OES, and GLuint.
Referenced by _mesa_base_tex_image(), _mesa_BindImageTexture(), _mesa_BindImageTextures(), and _mesa_is_image_unit_valid().
_mesa_TexBuffer()
void GLAPIENTRY _mesa_TexBuffer (GLenum target, GLenum internalFormat, GLuint buffer)
GL_ARB_texture_buffer_object.
References _mesa_get_current_tex_object(), _mesa_lookup_bufferobj_err(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TexBufferRange()
void GLAPIENTRY _mesa_TexBufferRange (GLenum target, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GL_ARB_texture_buffer_range.
References _mesa_get_current_tex_object(), _mesa_lookup_bufferobj_err(), check_texture_buffer_range(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TexImage1D()
void GLAPIENTRY _mesa_TexImage1D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_TexImage2D()
void GLAPIENTRY _mesa_TexImage2D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image(), and _mesa_cpal_compressed_teximage2d().
_mesa_TexImage2DMultisample()
void GLAPIENTRY _mesa_TexImage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, and texture_image_multisample().
Referenced by _mesa_base_tex_image().
_mesa_TexImage3D()
void GLAPIENTRY _mesa_TexImage3D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image(), and _mesa_TexImage3DEXT().
_mesa_TexImage3DEXT()
void GLAPIENTRY _mesa_TexImage3DEXT (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References _mesa_TexImage3D(), and GLAPIENTRY.
Referenced by _mesa_base_tex_image().
_mesa_TexImage3DMultisample()
void GLAPIENTRY _mesa_TexImage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, cb_info::texObj, and texture_image_multisample().
Referenced by _mesa_base_tex_image().
_mesa_TexStorage2DMultisample()
void GLAPIENTRY _mesa_TexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TexStorage3DMultisample()
void GLAPIENTRY _mesa_TexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TexSubImage1D()
void GLAPIENTRY _mesa_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texsubimage().
Referenced by _mesa_base_tex_image().
_mesa_TexSubImage2D()
void GLAPIENTRY _mesa_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texsubimage().
Referenced by _mesa_base_tex_image().
_mesa_TexSubImage3D()
void GLAPIENTRY _mesa_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texsubimage().
Referenced by _mesa_base_tex_image().
_mesa_texture_sub_image()
void _mesa_texture_sub_image (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, struct gl_texture_image * texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, bool dsa)
Helper that implements the glTexSubImage1/2/3D() and glTextureSubImage1/2/3D() functions.
References _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state(), _NEW_PIXEL, gl_texture_image::Border, check_gen_mipmap(), gl_context::Driver, FLUSH_VERTICES, gl_context::NewState, dd_function_table::TexSubImage, and gl_context::Unpack.
Referenced by _mesa_base_tex_image(), texsubimage(), and texturesubimage().
_mesa_TextureBuffer()
void GLAPIENTRY _mesa_TextureBuffer (GLuint texture, GLenum internalFormat, GLuint buffer)
References _mesa_lookup_bufferobj_err(), _mesa_lookup_texture_err(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TextureBufferRange()
void GLAPIENTRY _mesa_TextureBufferRange (GLuint texture, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
References _mesa_lookup_bufferobj_err(), _mesa_lookup_texture_err(), check_texture_buffer_range(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, gl_texture_object::Target, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TextureStorage2DMultisample()
void GLAPIENTRY _mesa_TextureStorage2DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TextureStorage3DMultisample()
void GLAPIENTRY _mesa_TextureStorage3DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, gl_texture_object::Target, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TextureSubImage1D()
void GLAPIENTRY _mesa_TextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texturesubimage().
Referenced by _mesa_base_tex_image().
_mesa_TextureSubImage2D()
void GLAPIENTRY _mesa_TextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texturesubimage().
Referenced by _mesa_base_tex_image().
_mesa_TextureSubImage3D()
void GLAPIENTRY _mesa_TextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, and texturesubimage().
Referenced by _mesa_base_tex_image().
_mesa_update_fbo_texture()
void _mesa_update_fbo_texture (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint face, GLuint level)
When a texture image is specified we have to check if it's bound to any framebuffer objects (render to texture) in order to detect changes in size or format since that effects FBO completeness.
Any FBOs rendering into the texture must be re-validated.
References _mesa_HashWalk(), gl_texture_object::_RenderToTexture, check_rtt_cb(), cb_info::ctx, cb_info::face, gl_shared_state::FrameBuffers, cb_info::level, gl_context::Shared, and cb_info::texObj.
Referenced by _mesa_is_zero_size_texture(), copyteximage(), prepare_mipmap_level(), teximage(), texture_image_multisample(), and update_fbo_texture().
_mesa_validate_texbuffer_format()
mesa_format _mesa_validate_texbuffer_format (const struct gl_context * ctx, GLenum internalFormat)
References _mesa_get_format_base_format(), _mesa_get_format_datatype(), gl_extensions::ARB_texture_buffer_object_rgb32, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_context::Extensions, get_texbuffer_format(), and MESA_FORMAT_NONE.
Referenced by _is_resource_supported(), _mesa_base_tex_image(), texture_buffer_range(), and validate_clear_buffer_format().
adjust_for_oes_float_texture()
static GLenum adjust_for_oes_float_texture (const struct gl_context * ctx, GLenum format, GLenum type) static
Returns a corresponding internal floating point format for a given base format as specifed by OES_texture_float.
In case of GL_FLOAT, the internal format needs to be a 32 bit component and in case of GL_HALF_FLOAT_OES it needs to be a 16 bit component.
For example, given base format GL_RGBA, type GL_FLOAT return GL_RGBA32F_ARB.
References gl_context::Extensions, GL_HALF_FLOAT_OES, gl_extensions::OES_texture_float, and gl_extensions::OES_texture_half_float.
Referenced by teximage().
can_avoid_reallocation()
static bool can_avoid_reallocation (const struct gl_texture_image * texImage, GLenum internalFormat, mesa_format texFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) static
Check if the given texture format and size arguments match those of the texture image.
Parameters
return true if arguments match, false otherwise.
References gl_texture_image::Border, gl_texture_image::Height2, gl_texture_image::InternalFormat, gl_texture_image::TexFormat, and gl_texture_image::Width2.
Referenced by copyteximage().
check_clear_tex_image()
static bool check_clear_tex_image (struct gl_context * ctx, const char * function, struct gl_texture_image * texImage, GLenum format, GLenum type, const void * data, GLubyte * clearValue) static
References gl_texture_image::_BaseFormat, _mesa_enum_to_string(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_is_compressed_format(), _mesa_is_enum_format_integer(), _mesa_is_format_integer_color(), _mesa_texstore(), gl_context::DefaultPacking, gl_extensions::EXT_texture_integer, gl_context::Extensions, gl_texture_image::InternalFormat, MAX_PIXEL_BYTES, gl_texture_object::Target, gl_texture_image::TexFormat, cb_info::texObj, gl_texture_image::TexObject, texture_formats_agree(), and gl_context::Version.
Referenced by _mesa_ClearTexImage(), and _mesa_ClearTexSubImage().
check_gen_mipmap()
static void check_gen_mipmap (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj, GLint level) inline static
If the texture object's GenerateMipmap flag is set and we've changed the texture base level image, regenerate the rest of the mipmap levels now.
References gl_texture_object::BaseLevel, gl_context::Driver, dd_function_table::GenerateMipmap, and gl_texture_object::GenerateMipmap.
Referenced by _mesa_compressed_texture_sub_image(), _mesa_copy_texture_sub_image(), _mesa_texture_sub_image(), copyteximage(), and teximage().
check_multisample_target()
static GLboolean check_multisample_target (GLuint dims, GLenum target, bool dsa) static
GL_ARB_texture_multisample.
Referenced by texture_image_multisample().
check_rtt_cb()
static void check_rtt_cb (GLuint key, void * data, void * userData) static
Check render to texture callback.
Called from _mesa_HashWalk().
References _mesa_is_user_fbo(), _mesa_update_texture_renderbuffer(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, cb_info::ctx, gl_renderbuffer_attachment::CubeMapFace, gl_context::DrawBuffer, cb_info::face, GLuint, cb_info::level, gl_context::NewState, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer::TexImage, cb_info::texObj, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_update_fbo_texture().
check_texture_buffer_range()
static bool check_texture_buffer_range (struct gl_context * ctx, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, const char * caller) static
Check for errors related to the texture buffer range.
Return false if errors are found, true if none are found.
References _mesa_error(), gl_context::Const, GLAPIENTRY, gl_buffer_object::Size, and gl_constants::TextureBufferOffsetAlignment.
Referenced by _mesa_TexBufferRange(), and _mesa_TextureBufferRange().
check_texture_buffer_target()
static bool check_texture_buffer_target (struct gl_context * ctx, GLenum target, const char * caller) static
Make sure the texture buffer target is GL_TEXTURE_BUFFER.
Return true if it is, and return false if it is not (and throw INVALID ENUM as dictated in the OpenGL 4.5 core spec, 02.02.2015, PDF page 245).
References _mesa_error().
Referenced by _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TextureBuffer(), and _mesa_TextureBufferRange().
clear_teximage_fields()
static void clear_teximage_fields (struct gl_texture_image * img) static
Set the size and format-related fields of a gl_texture_image struct to zero.
This is used when a proxy texture test fails.
References gl_texture_image::_BaseFormat, gl_texture_image::Border, gl_texture_image::Depth, gl_texture_image::Depth2, gl_texture_image::DepthLog2, gl_texture_image::FixedSampleLocations, gl_texture_image::Height, gl_texture_image::Height2, gl_texture_image::HeightLog2, gl_texture_image::InternalFormat, MESA_FORMAT_NONE, gl_texture_image::NumSamples, gl_texture_image::TexFormat, gl_texture_image::Width, gl_texture_image::Width2, and gl_texture_image::WidthLog2.
Referenced by _mesa_clear_texture_image(), teximage(), and texture_image_multisample().
compressed_subtexture_error_check()
static GLboolean compressed_subtexture_error_check (struct gl_context * ctx, GLint dims, const struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data, const char * callerName) static
Error checking for glCompressedTexSubImage[123]D().
Returns
GL_TRUE if error, GL_FALSE if no error
References _mesa_compressed_pixel_storage_error_check(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_compressed_format(), _mesa_max_texture_levels(), _mesa_select_tex_image(), _mesa_validate_pbo_source_compressed(), compressed_tex_size(), compressedteximage_only_format(), error_check_subtexture_dimensions(), error_check_subtexture_negative_dimensions(), GLAPIENTRY, gl_texture_image::InternalFormat, and gl_context::Unpack.
Referenced by _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), and _mesa_CompressedTextureSubImage3D().
compressed_subtexture_target_check()
static GLboolean compressed_subtexture_target_check (struct gl_context * ctx, GLenum target, GLint dims, GLenum format, bool dsa, const char * caller) static
Target checking for glCompressedTexSubImage[123]D().
Returns
GL_TRUE if error, GL_FALSE if no error Must come before other error checking so that the texture object can be correctly retrieved using _mesa_get_current_tex_object.
References _mesa_enum_to_string(), _mesa_error(), _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_extensions::ARB_texture_cube_map, gl_extensions::EXT_texture_array, and gl_context::Extensions.
Referenced by _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), and _mesa_CompressedTextureSubImage3D().
compressed_tex_size()
static GLuint compressed_tex_size (GLsizei width, GLsizei height, GLsizei depth, GLenum glformat) static
Return expected size of a compressed texture.
References _mesa_format_image_size(), and _mesa_glenum_to_compressed_format().
Referenced by compressed_subtexture_error_check(), and compressed_texture_error_check().
compressed_texture_error_check()
static GLenum compressed_texture_error_check (struct gl_context * ctx, GLint dimensions, GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data) static
Error checking for glCompressedTexImage[123]D().
Note that the width, height and depth values are not fully error checked here.
Returns
GL_TRUE if a error is found, GL_FALSE otherwise
References _mesa_base_tex_format(), _mesa_compressed_pixel_storage_error_check(), _mesa_cpal_compressed_size(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_compressed_format(), _mesa_max_texture_levels(), _mesa_target_can_be_compressed(), _mesa_validate_pbo_source_compressed(), compressed_tex_size(), mutable_tex_object(), and gl_context::Unpack.
Referenced by teximage().
compressedteximage_only_format()
static bool compressedteximage_only_format (const struct gl_context * ctx, GLenum format) static
Return true if the format is only valid for glCompressedTexImage.
Referenced by _mesa_format_no_online_compression(), and compressed_subtexture_error_check().
copyteximage()
static void copyteximage (struct gl_context * ctx, GLuint dims, GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) static
Implement the glCopyTexImage1/2D() functions.
References _mesa_choose_texture_format(), _mesa_clip_copytexsubimage(), _mesa_copy_texture_sub_image(), _mesa_debug(), _mesa_dirty_texobj(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_get_read_renderbuffer_for_format(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_is_enum_format_unsized(), _mesa_is_gles3(), _mesa_legal_texture_dimensions(), _mesa_lock_texture(), _mesa_perf_debug, _mesa_select_tex_image(), _mesa_tex_target_to_face(), _mesa_unlock_texture(), _mesa_update_fbo_texture(), _mesa_update_state(), dd_function_table::AllocTextureImageBuffer, can_avoid_reallocation(), check_gen_mipmap(), gl_context::Const, copytexsubimage_by_slice(), copytexture_error_check(), gl_context::Driver, cb_info::face, FLUSH_VERTICES, gl_renderbuffer::Format, formats_differ_in_component_sizes(), dd_function_table::FreeTextureImageBuffer, get_copy_tex_image_source(), GLAPIENTRY, GLuint, gl_renderbuffer::InternalFormat, MESA_DEBUG_SEVERITY_LOW, MESA_FORMAT_NONE, MESA_VERBOSE, NEW_COPY_TEX_STATE, gl_context::NewState, proxy_target(), gl_constants::StripTextureBorder, dd_function_table::TestProxyTexImage, gl_texture_image::TexFormat, cb_info::texObj, VERBOSE_API, VERBOSE_TEXTURE, and x.
Referenced by _mesa_CopyTexImage1D(), and _mesa_CopyTexImage2D().
copytexsubimage_by_slice()
static void copytexsubimage_by_slice (struct gl_context * ctx, struct gl_texture_image * texImage, GLuint dims, GLint xoffset, GLint yoffset, GLint zoffset, struct gl_renderbuffer * rb, GLint x, GLint y, GLsizei width, GLsizei height) static
References dd_function_table::CopyTexSubImage, gl_context::Driver, gl_renderbuffer::Height, gl_texture_object::Target, and gl_texture_image::TexObject.
Referenced by _mesa_copy_texture_sub_image(), and copyteximage().
copytexsubimage_error_check()
static GLboolean copytexsubimage_error_check (struct gl_context * ctx, GLuint dimensions, const struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, const char * caller) static
Test glCopyTexSubImage[12]D() parameters for errors.
Returns
GL_TRUE if an error was detected, or GL_FALSE if no errors.
References gl_texture_image::_BaseFormat, gl_framebuffer::_ColorReadBuffer, _mesa_enum_to_string(), _mesa_error(), _mesa_format_no_online_compression(), _mesa_is_color_format(), _mesa_is_format_compressed(), _mesa_is_format_integer_color(), _mesa_is_gles(), _mesa_is_stencil_format(), _mesa_is_user_fbo(), _mesa_max_texture_levels(), _mesa_select_tex_image(), _mesa_source_buffer_exists(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, error_check_subtexture_dimensions(), error_check_subtexture_negative_dimensions(), gl_renderbuffer::Format, gl_texture_image::InternalFormat, gl_context::ReadBuffer, gl_config::samples, gl_texture_image::TexFormat, and gl_framebuffer::Visual.
Referenced by _mesa_copy_texture_sub_image().
copytexture_error_check()
static GLboolean copytexture_error_check (struct gl_context * ctx, GLuint dimensions, GLenum target, GLint level, GLint internalFormat, GLint width, GLint height, GLint border) static
Test glCopyTexImage[12]D() parameters for errors.
Parameters
ctx GL context.
dimensions texture image dimensions (must be 1, 2 or 3).
target texture target given by the user.
level image level given by the user.
internalFormat internal format given by the user.
width image width given by the user.
height image height given by the user.
border texture border.
Returns
GL_TRUE if an error was detected, or GL_FALSE if no errors.
Verifies each of the parameters against the constants specified in __struct gl_contextRec::Const and the supported extensions, and according to the OpenGL specification.
References _mesa_base_format_component_count(), _mesa_base_tex_format(), _mesa_enum_to_string(), _mesa_error(), _mesa_format_no_online_compression(), _mesa_get_format_color_encoding(), _mesa_get_linear_internalformat(), _mesa_get_read_renderbuffer_for_format(), _mesa_is_color_format(), _mesa_is_compressed_format(), _mesa_is_enum_format_integer(), _mesa_is_enum_format_snorm(), _mesa_is_enum_format_unorm(), _mesa_is_enum_format_unsigned_int(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_is_user_fbo(), _mesa_max_texture_levels(), _mesa_source_buffer_exists(), _mesa_target_can_be_compressed(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, gl_context::API, API_OPENGL_COMPAT, gl_extensions::EXT_framebuffer_sRGB, gl_context::Extensions, gl_renderbuffer::Format, gl_renderbuffer::InternalFormat, legal_texsubimage_target(), mutable_tex_object(), gl_context::ReadBuffer, gl_config::samples, and gl_framebuffer::Visual.
Referenced by copyteximage().
error_check_subtexture_dimensions()
static GLboolean error_check_subtexture_dimensions (struct gl_context * ctx, GLuint dims, const struct gl_texture_image * destImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei subWidth, GLsizei subHeight, GLsizei subDepth, const char * func) static
Do error checking of xoffset, yoffset, zoffset, width, height and depth for glTexSubImage, glCopyTexSubImage and glCompressedTexSubImage.
Parameters
destImage the destination texture image.
Returns
GL_TRUE if error found, GL_FALSE otherwise.
References _mesa_error(), _mesa_get_format_block_size_3d(), gl_texture_image::Border, gl_texture_image::Depth, GLuint, gl_texture_image::Height, if(), gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and gl_texture_image::Width.
Referenced by compressed_subtexture_error_check(), copytexsubimage_error_check(), and texsubimage_error_check().
error_check_subtexture_negative_dimensions()
static bool error_check_subtexture_negative_dimensions (struct gl_context * ctx, GLuint dims, GLsizei subWidth, GLsizei subHeight, GLsizei subDepth, const char * func) static
References _mesa_error().
Referenced by compressed_subtexture_error_check(), copytexsubimage_error_check(), and texsubimage_error_check().
formats_differ_in_component_sizes()
static GLboolean formats_differ_in_component_sizes (mesa_format f1, mesa_format f2) static
References _mesa_get_format_bits().
Referenced by copyteximage().
get_copy_tex_image_source()
static struct gl_renderbuffer* get_copy_tex_image_source (struct gl_context * ctx, mesa_format texFormat) static
For glCopyTexSubImage, return the source renderbuffer to copy texel data from.
This depends on whether the texture contains color or depth values.
References gl_framebuffer::_ColorReadBuffer, _mesa_get_format_bits(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::ReadBuffer, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_copy_texture_sub_image(), and copyteximage().
get_proxy_tex_image()
static struct gl_texture_image* get_proxy_tex_image (struct gl_context * ctx, GLenum target, GLint level) static
Return pointer to the specified proxy texture image.
Note that proxy textures are per-context, not per-texture unit.
Returns
pointer to texture image or NULL if invalid target, invalid level, or out of memory.
References _mesa_error(), gl_context::Const, gl_context::Driver, GLuint, gl_texture_object::Image, gl_constants::Max3DTextureLevels, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, dd_function_table::NewTextureImage, gl_texture_attrib::ProxyTex, gl_texture_image::TexObject, gl_context::Texture, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, and TEXTURE_RECT_INDEX.
Referenced by teximage().
get_tex_images_for_clear()
static int get_tex_images_for_clear (struct gl_context * ctx, const char * function, struct gl_texture_object * texObj, GLint level, struct gl_texture_image ** texImages) static
References _mesa_error(), _mesa_select_tex_image(), GLAPIENTRY, MAX_FACES, MAX_TEXTURE_LEVELS, and gl_texture_object::Target.
Referenced by _mesa_ClearTexImage(), and _mesa_ClearTexSubImage().
get_tex_obj_for_clear()
static struct gl_texture_object* get_tex_obj_for_clear (struct gl_context * ctx, const char * function, GLuint texture) static
References _mesa_error(), _mesa_lookup_texture(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_ClearTexImage(), and _mesa_ClearTexSubImage().
get_texbuffer_format()
static mesa_format get_texbuffer_format (const struct gl_context * ctx, GLenum internalFormat) static
References _mesa_is_gles(), gl_context::API, API_OPENGL_COMPAT, MESA_FORMAT_A_FLOAT16, MESA_FORMAT_A_FLOAT32, MESA_FORMAT_A_SINT16, MESA_FORMAT_A_SINT32, MESA_FORMAT_A_SINT8, MESA_FORMAT_A_UINT16, MESA_FORMAT_A_UINT32, MESA_FORMAT_A_UINT8, MESA_FORMAT_A_UNORM16, MESA_FORMAT_A_UNORM8, MESA_FORMAT_I_FLOAT16, MESA_FORMAT_I_FLOAT32, MESA_FORMAT_I_SINT16, MESA_FORMAT_I_SINT32, MESA_FORMAT_I_SINT8, MESA_FORMAT_I_UINT16, MESA_FORMAT_I_UINT32, MESA_FORMAT_I_UINT8, MESA_FORMAT_I_UNORM16, MESA_FORMAT_I_UNORM8, MESA_FORMAT_L16A16_UNORM, MESA_FORMAT_L8A8_UNORM, MESA_FORMAT_L_FLOAT16, MESA_FORMAT_L_FLOAT32, MESA_FORMAT_L_SINT16, MESA_FORMAT_L_SINT32, MESA_FORMAT_L_SINT8, MESA_FORMAT_L_UINT16, MESA_FORMAT_L_UINT32, MESA_FORMAT_L_UINT8, MESA_FORMAT_L_UNORM16, MESA_FORMAT_L_UNORM8, MESA_FORMAT_LA_FLOAT16, MESA_FORMAT_LA_FLOAT32, MESA_FORMAT_LA_SINT16, MESA_FORMAT_LA_SINT32, MESA_FORMAT_LA_SINT8, MESA_FORMAT_LA_UINT16, MESA_FORMAT_LA_UINT32, MESA_FORMAT_LA_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R16G16_UNORM, MESA_FORMAT_R8G8_UNORM, MESA_FORMAT_R8G8B8A8_UNORM, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_SINT16, MESA_FORMAT_R_SINT32, MESA_FORMAT_R_SINT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_R_UNORM16, MESA_FORMAT_R_UNORM8, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_SINT16, MESA_FORMAT_RG_SINT32, MESA_FORMAT_RG_SINT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_SINT32, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_SINT16, MESA_FORMAT_RGBA_SINT32, MESA_FORMAT_RGBA_SINT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, and MESA_FORMAT_RGBA_UNORM16.
Referenced by _mesa_validate_texbuffer_format().
init_teximage_fields_ms()
static void init_teximage_fields_ms (struct gl_context * ctx, struct gl_texture_image * img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, mesa_format format, GLuint numSamples, GLboolean fixedSampleLocations) static
Initialize basic fields of the gl_texture_image struct.
Parameters
ctx GL context.
img texture image structure to be initialized.
width image width.
height image height.
depth image depth.
border image border.
internalFormat internal format.
format the actual hardware format (one of MESA_FORMAT_*)
numSamples number of samples per texel, or zero for non-MS.
fixedSampleLocations are sample locations fixed?
Fills in the fields of img with the given information. Note: width, height and depth include the border.
References gl_texture_image::_BaseFormat, _mesa_base_tex_format(), _mesa_get_tex_max_num_levels(), _mesa_logbase2(), _mesa_problem(), gl_texture_image::Border, gl_texture_image::Depth, gl_texture_image::Depth2, gl_texture_image::DepthLog2, gl_texture_image::FixedSampleLocations, GL_TEXTURE_EXTERNAL_OES, gl_texture_image::Height, gl_texture_image::Height2, gl_texture_image::HeightLog2, gl_texture_image::InternalFormat, gl_texture_image::MaxNumLevels, gl_texture_image::NumSamples, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, gl_texture_image::Width, gl_texture_image::Width2, and gl_texture_image::WidthLog2.
Referenced by _mesa_init_teximage_fields(), and texture_image_multisample().
legal_teximage_target()
static GLboolean legal_teximage_target (struct gl_context * ctx, GLuint dims, GLenum target) static
Check if the given texture target value is legal for a glTexImage1/2/3D call.
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_problem(), gl_extensions::ARB_texture_cube_map, gl_extensions::EXT_texture_array, gl_context::Extensions, and gl_extensions::NV_texture_rectangle.
Referenced by teximage().
legal_texsubimage_target()
static GLboolean legal_texsubimage_target (struct gl_context * ctx, GLuint dims, GLenum target, bool dsa) static
Check if the given texture target value is legal for a glTexSubImage, glCopyTexSubImage or glCopyTexImage call.
The difference compared to legal_teximage_target() above is that proxy targets are not supported.
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_problem(), gl_extensions::ARB_texture_cube_map, gl_extensions::EXT_texture_array, gl_context::Extensions, and gl_extensions::NV_texture_rectangle.
Referenced by _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), copytexture_error_check(), texsubimage(), and texturesubimage().
mutable_tex_object()
static GLboolean mutable_tex_object (struct gl_context * ctx, GLenum target) static
Helper function to determine if a texture object is mutable (in terms of GL_ARB_texture_storage).
References _mesa_get_current_tex_object(), GLuint, and gl_texture_object::Immutable.
Referenced by compressed_texture_error_check(), copytexture_error_check(), and texture_error_check().
override_internal_format()
static GLenum override_internal_format (GLenum internalFormat, GLint width, GLint height) static
Debug helper: override the user-requested internal format.
Referenced by teximage().
proxy_target()
static GLenum proxy_target (GLenum target) static
Return the proxy target which corresponds to the given texture target.
References _mesa_problem().
Referenced by copyteximage(), and teximage().
set_tex_image()
static void set_tex_image (struct gl_texture_object * tObj, GLenum target, GLint level, struct gl_texture_image * texImage) static
Install gl_texture_image in a gl_texture_object according to the target and level parameters.
Parameters
tObj texture object.
target texture target.
level image level.
texImage texture image.
References _mesa_tex_target_to_face(), gl_texture_image::Face, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_texture_object::Image, gl_texture_image::Level, and gl_texture_image::TexObject.
Referenced by _mesa_get_tex_image().
strip_texture_border()
static void strip_texture_border (GLenum target, GLint * width, GLint * height, GLint * depth, const struct gl_pixelstore_attrib * unpack, struct gl_pixelstore_attrib * unpackNew) static
Adjust pixel unpack params and image dimensions to strip off the one-pixel texture border.
Gallium and intel don't support texture borders. They've seldem been used and seldom been implemented correctly anyway.
Parameters
unpackNew returns the new pixel unpack parameters
References gl_pixelstore_attrib::ImageHeight, gl_pixelstore_attrib::RowLength, gl_pixelstore_attrib::SkipImages, gl_pixelstore_attrib::SkipPixels, and gl_pixelstore_attrib::SkipRows.
Referenced by teximage().
teximage()
static void teximage (struct gl_context * ctx, GLboolean compressed, GLuint dims, GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, GLsizei imageSize, const GLvoid * pixels) static
Common code to implement all the glTexImage1D/2D/3D functions as well as glCompressedTexImage1D/2D/3D.
Parameters
compressed only GL_TRUE for glCompressedTexImage1D/2D/3D calls.
format the user's image format (only used if !compressed)
type the user's image type (only used if !compressed)
imageSize only used for glCompressedTexImage1D/2D/3D calls.
References gl_texture_object::_IsFloat, gl_texture_object::_IsHalfFloat, _mesa_choose_texture_format(), _mesa_cpal_compressed_teximage2d(), _mesa_debug(), _mesa_dirty_texobj(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_get_tex_image(), _mesa_glenum_to_compressed_format(), _mesa_init_teximage_fields(), _mesa_is_gles(), _mesa_is_proxy_texture(), _mesa_legal_texture_dimensions(), _mesa_lock_texture(), _mesa_tex_target_to_face(), _mesa_unlock_texture(), _mesa_update_fbo_texture(), _mesa_update_state(), _NEW_PIXEL, adjust_for_oes_float_texture(), gl_context::API, API_OPENGLES, check_gen_mipmap(), clear_teximage_fields(), compressed_texture_error_check(), dd_function_table::CompressedTexImage, gl_context::Const, gl_context::Driver, cb_info::face, FLUSH_VERTICES, dd_function_table::FreeTextureImageBuffer, get_proxy_tex_image(), GL_HALF_FLOAT_OES, GLAPIENTRY, GLuint, legal_teximage_target(), MESA_FORMAT_NONE, MESA_VERBOSE, gl_context::NewState, override_internal_format(), proxy_target(), strip_texture_border(), gl_constants::StripTextureBorder, dd_function_table::TestProxyTexImage, dd_function_table::TexImage, cb_info::texObj, texture_error_check(), gl_context::Unpack, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_CompressedTexImage1D(), _mesa_CompressedTexImage2D(), _mesa_CompressedTexImage3D(), _mesa_is_zero_size_texture(), _mesa_TexImage1D(), _mesa_TexImage2D(), and _mesa_TexImage3D().
texsubimage()
static void texsubimage (struct gl_context * ctx, GLuint dims, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const char * callerName) static
Implement all the glTexSubImage1/2/3D() functions.
Must split this out this way because of GL_TEXTURE_CUBE_MAP.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), _mesa_texture_sub_image(), legal_texsubimage_target(), MESA_VERBOSE, cb_info::texObj, texsubimage_error_check(), VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_TexSubImage1D(), _mesa_TexSubImage2D(), and _mesa_TexSubImage3D().
texsubimage_error_check()
static GLboolean texsubimage_error_check (struct gl_context * ctx, GLuint dimensions, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const GLvoid * pixels, bool dsa, const char * callerName) static
Test glTexSubImage[123]D() parameters for errors.
Parameters
ctx GL context.
dimensions texture image dimensions (must be 1, 2 or 3).
target texture target given by the user (already validated)
level image level given by the user.
xoffset sub-image x offset given by the user.
yoffset sub-image y offset given by the user.
zoffset sub-image z offset given by the user.
format pixel data format given by the user.
type pixel data type given by the user.
width image width given by the user.
height image height given by the user.
depth image depth given by the user.
Returns
GL_TRUE if an error was detected, or GL_FALSE if no errors.
Verifies each of the parameters against the constants specified in __struct gl_contextRec::Const and the supported extensions, and according to the OpenGL specification.
References _mesa_enum_to_string(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_format_no_online_compression(), _mesa_is_enum_format_integer(), _mesa_is_format_compressed(), _mesa_is_format_integer_color(), _mesa_is_gles(), _mesa_max_texture_levels(), _mesa_select_tex_image(), _mesa_validate_pbo_source(), error_check_subtexture_dimensions(), error_check_subtexture_negative_dimensions(), gl_extensions::EXT_texture_integer, gl_context::Extensions, gl_texture_image::InternalFormat, gl_texture_image::TexFormat, texture_format_error_check_gles(), gl_context::Unpack, and gl_context::Version.
Referenced by texsubimage(), and texturesubimage().
texture_buffer_range()
static void texture_buffer_range (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum internalFormat, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, const char * caller) static
Do work common to glTexBuffer, glTexBufferRange, glTextureBuffer and glTextureBufferRange, including some error checking.
References gl_texture_object::_BufferObjectFormat, _mesa_enum_to_string(), _mesa_error(), _mesa_lock_texture(), _mesa_reference_buffer_object(), _mesa_unlock_texture(), _mesa_validate_texbuffer_format(), gl_texture_object::BufferObject, gl_texture_object::BufferObjectFormat, gl_texture_object::BufferOffset, gl_texture_object::BufferSize, gl_context::Driver, gl_context::DriverFlags, FLUSH_VERTICES, MESA_FORMAT_NONE, gl_context::NewDriverState, gl_driver_flags::NewTextureBuffer, dd_function_table::TexParameter, USAGE_TEXTURE_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TextureBuffer(), and _mesa_TextureBufferRange().
texture_error_check()
static GLboolean texture_error_check (struct gl_context * ctx, GLuint dimensions, GLenum target, GLint level, GLint internalFormat, GLenum format, GLenum type, GLint width, GLint height, GLint depth, GLint border, const GLvoid * pixels) static
Test the glTexImage[123]D() parameters for errors.
Parameters
ctx GL context.
dimensions texture image dimensions (must be 1, 2 or 3).
target texture target given by the user (already validated).
level image level given by the user.
internalFormat internal format given by the user.
format pixel data format given by the user.
type pixel data type given by the user.
width image width given by the user.
height image height given by the user.
depth image depth given by the user.
border image border given by the user.
Returns
GL_TRUE if a error is found, GL_FALSE otherwise
Verifies each of the parameters against the constants specified in __struct gl_contextRec::Const and the supported extensions, and according to the OpenGL specification. Note that we don't fully error-check the width, height, depth values here. That's done in _mesa_legal_texture_dimensions() which is used by several other GL entrypoints. Plus, texture dims have a special interaction with proxy textures.
References _mesa_base_tex_format(), _mesa_enum_to_string(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_format_no_online_compression(), _mesa_is_compressed_format(), _mesa_is_enum_format_integer(), _mesa_is_gles(), _mesa_legal_texture_base_format_for_target(), _mesa_max_texture_levels(), _mesa_snprintf(), _mesa_target_can_be_compressed(), _mesa_validate_pbo_source(), gl_context::API, API_OPENGL_COMPAT, gl_extensions::EXT_texture_integer, gl_context::Extensions, gl_extensions::MESA_ycbcr_texture, mutable_tex_object(), texture_format_error_check_gles(), texture_formats_agree(), gl_context::Unpack, and gl_context::Version.
Referenced by teximage().
texture_format_error_check_gles()
static bool texture_format_error_check_gles (struct gl_context * ctx, GLenum format, GLenum type, GLenum internalFormat, GLuint dimensions, const char * callerName) static
Test the combination of format, type and internal format arguments of different texture operations on GLES.
Parameters
ctx GL context.
format pixel data format given by the user.
type pixel data type given by the user.
internalFormat internal format given by the user.
dimensions texture image dimensions (must be 1, 2 or 3).
callerName name of the caller function to print in the error message
Returns
true if a error is found, false otherwise
Currently, it is used by texture_error_check() and texsubimage_error_check().
References _mesa_enum_to_string(), _mesa_error(), _mesa_es3_error_check_format_and_type(), _mesa_es_error_check_format_and_type(), and _mesa_is_gles3().
Referenced by texsubimage_error_check(), and texture_error_check().
texture_formats_agree()
static bool texture_formats_agree (GLenum internalFormat, GLenum format) static
References _mesa_is_color_format(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), and _mesa_is_ycbcr_format().
Referenced by check_clear_tex_image(), and texture_error_check().
texture_image_multisample()
static void texture_image_multisample (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations, GLboolean immutable, const char * func) static
References _mesa_check_sample_count(), _mesa_choose_texture_format(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_is_desktop_gl(), _mesa_is_gles31(), _mesa_is_legal_tex_storage_format(), _mesa_is_proxy_texture(), _mesa_is_renderable_texture_format(), _mesa_legal_texture_dimensions(), _mesa_set_texture_view_state(), _mesa_update_fbo_texture(), dd_function_table::AllocTextureStorage, gl_extensions::ARB_texture_multisample, check_multisample_target(), clear_teximage_fields(), gl_context::Driver, gl_context::Extensions, dd_function_table::FreeTextureImageBuffer, GLAPIENTRY, gl_texture_object::Immutable, init_teximage_fields_ms(), MESA_FORMAT_NONE, MESA_VERBOSE, gl_texture_object::Name, dd_function_table::TestProxyTexImage, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_TexImage2DMultisample(), _mesa_TexImage3DMultisample(), _mesa_TexStorage2DMultisample(), _mesa_TexStorage3DMultisample(), _mesa_TextureStorage2DMultisample(), and _mesa_TextureStorage3DMultisample().
texturesubimage()
static void texturesubimage (struct gl_context * ctx, GLuint dims, GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const char * callerName) static
Implement all the glTextureSubImage1/2/3D() functions.
Must split this out this way because of GL_TEXTURE_CUBE_MAP.
References _mesa_cube_level_complete(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_image_image_stride(), _mesa_lookup_texture(), _mesa_select_tex_image(), _mesa_texture_sub_image(), GLAPIENTRY, gl_texture_object::Image, legal_texsubimage_target(), cb_info::level, MESA_VERBOSE, gl_texture_object::Target, cb_info::texObj, texsubimage_error_check(), gl_context::Unpack, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_TextureSubImage1D(), _mesa_TextureSubImage2D(), and _mesa_TextureSubImage3D().
valid_texstorage_ms_parameters()
static bool valid_texstorage_ms_parameters (GLsizei width, GLsizei height, GLsizei depth, GLsizei samples, unsigned dims) static
References _mesa_error(), _mesa_valid_tex_storage_dim(), cb_info::ctx, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_TexStorage2DMultisample(), _mesa_TexStorage3DMultisample(), _mesa_TextureStorage2DMultisample(), and _mesa_TextureStorage3DMultisample().
write_error()
static bool write_error (GLenum * err_ptr, GLenum error) static
Referenced by _mesa_target_can_be_compressed().