Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
teximage.h File Reference
Texture images manipulation functions.
#include "mtypes.h"
#include "formats.h"
Functions
static GLboolean _mesa_is_cube_face (GLenum target)
Is the given value one of the 6 cube faces?
static GLuint _mesa_num_tex_faces (GLenum target)
Return number of faces for a texture target.
static GLenum _mesa_cube_face_target (GLenum target, unsigned face)
If the target is GL_TEXTURE_CUBE_MAP, return one of the GL_TEXTURE_CUBE_MAP_POSITIVE/NEGATIVE_X/Y/Z targets corresponding to the face parameter.
static GLuint _mesa_tex_target_to_face (GLenum target)
For cube map faces, return a face index in [0,5].
static GLboolean _mesa_is_zero_size_texture (const struct gl_texture_image *texImage)
Are any of the dimensions of given texture equal to zero?
Internal functions
GLboolean _mesa_is_proxy_texture (GLenum target)
Test if a target is a proxy target.
bool _mesa_is_array_texture (GLenum target)
Test if a target is an array target.
void _mesa_delete_texture_image (struct gl_context *ctx, struct gl_texture_image *teximage)
Free a gl_texture_image and associated data.
void _mesa_init_teximage_fields (struct gl_context *ctx, struct gl_texture_image *img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, mesa_format format)
mesa_format _mesa_choose_texture_format (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLenum internalFormat, GLenum format, GLenum type)
Choose the actual hardware format for a texture image.
void _mesa_update_fbo_texture (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
When a texture image is specified we have to check if it's bound to any framebuffer objects (render to texture) in order to detect changes in size or format since that effects FBO completeness.
void _mesa_clear_texture_image (struct gl_context *ctx, struct gl_texture_image *texImage)
Free and clear fields of the gl_texture_image struct.
struct gl_texture_image * _mesa_select_tex_image (const struct gl_texture_object *texObj, GLenum target, GLint level)
Get a texture image pointer from a texture object, given a texture target and mipmap level.
struct gl_texture_image * _mesa_get_tex_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level)
Like _mesa_select_tex_image() but if the image doesn't exist, allocate it and install it.
static const struct gl_texture_image * _mesa_base_tex_image (const struct gl_texture_object *texObj)
Return the base-level texture image for the given texture object.
GLint _mesa_max_texture_levels (struct gl_context *ctx, GLenum target)
Get the maximum number of allowed mipmap levels.
GLboolean _mesa_test_proxy_teximage (struct gl_context *ctx, GLenum target, GLuint numLevels, GLint level, mesa_format format, GLuint numSamples, GLint width, GLint height, GLint depth)
This is the fallback for Driver.TestProxyTexImage() for doing device- specific texture image size checks.
GLboolean _mesa_target_can_be_compressed (const struct gl_context *ctx, GLenum target, GLenum intFormat, GLenum *error)
Helper function to determine whether a target and specific compression format are supported.
GLint _mesa_get_texture_dimensions (GLenum target)
Return number of dimensions per mipmap level for the given texture target.
GLboolean _mesa_tex_target_is_layered (GLenum target)
Check if a texture target can have more than one layer.
GLuint _mesa_get_texture_layers (const struct gl_texture_object *texObj, GLint level)
Return the number of layers present in the given level of an array, cubemap or 3D texture.
GLsizei _mesa_get_tex_max_num_levels (GLenum target, GLsizei width, GLsizei height, GLsizei depth)
Return the maximum number of mipmap levels for the given target and the dimensions.
GLboolean _mesa_legal_texture_dimensions (struct gl_context *ctx, GLenum target, GLint level, GLint width, GLint height, GLint depth, GLint border)
Check the width, height, depth and border of a texture image are legal.
mesa_format _mesa_validate_texbuffer_format (const struct gl_context *ctx, GLenum internalFormat)
bool _mesa_legal_texture_base_format_for_target (struct gl_context *ctx, GLenum target, GLenum internalFormat)
Verify that a texture format is valid with a particular target.
bool _mesa_format_no_online_compression (const struct gl_context *ctx, GLenum format)
Return true if the format doesn't support online compression.
GLboolean _mesa_is_renderable_texture_format (struct gl_context *ctx, GLenum internalformat)
void _mesa_texture_sub_image (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, bool dsa)
Helper that implements the glTexSubImage1/2/3D() and glTextureSubImage1/2/3D() functions.
void _mesa_compressed_texture_sub_image (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Common helper for glCompressedTexSubImage1/2/3D() and glCompressedTextureSubImage1/2/3D().
void _mesa_copy_texture_sub_image (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height, const char *caller)
Implementation for glCopyTex(ture)SubImage1/2/3D() functions.
bool _mesa_is_cube_map_texture (GLenum target)
Test if a target is a cube map.
API entry point functions
void GLAPIENTRY _mesa_TexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage3D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage3DEXT (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_EGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
void GLAPIENTRY _mesa_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_CopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
void GLAPIENTRY _mesa_CopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
void GLAPIENTRY _mesa_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_ClearTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data)
void GLAPIENTRY _mesa_ClearTexImage (GLuint texture, GLint level, GLenum format, GLenum type, const void *data)
void GLAPIENTRY _mesa_CompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_TexBuffer (GLenum target, GLenum internalFormat, GLuint buffer)
GL_ARB_texture_buffer_object.
void GLAPIENTRY _mesa_TexBufferRange (GLenum target, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GL_ARB_texture_buffer_range.
void GLAPIENTRY _mesa_TextureBuffer (GLuint texture, GLenum internalFormat, GLuint buffer)
void GLAPIENTRY _mesa_TextureBufferRange (GLuint texture, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
void GLAPIENTRY _mesa_TexImage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexImage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TextureStorage2DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TextureStorage3DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
Detailed Description
Texture images manipulation functions.
Function Documentation
_mesa_base_tex_image()
static const struct gl_texture_image* _mesa_base_tex_image (const struct gl_texture_object * texObj) static
Return the base-level texture image for the given texture object.
References _mesa_ClearTexImage(), _mesa_ClearTexSubImage(), _mesa_compressed_texture_sub_image(), _mesa_CompressedTexImage1D(), _mesa_CompressedTexImage2D(), _mesa_CompressedTexImage3D(), _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), _mesa_CompressedTextureSubImage3D(), _mesa_copy_texture_sub_image(), _mesa_CopyTexImage1D(), _mesa_CopyTexImage2D(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), _mesa_EGLImageTargetTexture2DOES(), _mesa_format_no_online_compression(), _mesa_get_tex_max_num_levels(), _mesa_get_texture_dimensions(), _mesa_get_texture_layers(), _mesa_is_cube_map_texture(), _mesa_is_renderable_texture_format(), _mesa_legal_texture_base_format_for_target(), _mesa_legal_texture_dimensions(), _mesa_max_texture_levels(), _mesa_target_can_be_compressed(), _mesa_test_proxy_teximage(), _mesa_tex_target_is_layered(), _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TexImage1D(), _mesa_TexImage2D(), _mesa_TexImage2DMultisample(), _mesa_TexImage3D(), _mesa_TexImage3DEXT(), _mesa_TexImage3DMultisample(), _mesa_TexStorage2DMultisample(), _mesa_TexStorage3DMultisample(), _mesa_TexSubImage1D(), _mesa_TexSubImage2D(), _mesa_TexSubImage3D(), _mesa_texture_sub_image(), _mesa_TextureBuffer(), _mesa_TextureBufferRange(), _mesa_TextureStorage2DMultisample(), _mesa_TextureStorage3DMultisample(), _mesa_TextureSubImage1D(), _mesa_TextureSubImage2D(), _mesa_TextureSubImage3D(), _mesa_validate_texbuffer_format(), gl_texture_object::BaseLevel, GLAPIENTRY, GLuint, gl_texture_object::Image, and x.
Referenced by _mesa_texture_base_format().
_mesa_choose_texture_format()
mesa_format _mesa_choose_texture_format (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLenum internalFormat, GLenum format, GLenum type)
Choose the actual hardware format for a texture image.
Try to use the same format as the previous image level when possible. Otherwise, ask the driver for the best format. It's important to try to choose a consistant format for all levels for efficient texture memory layout/allocation. In particular, this comes up during automatic mipmap generation.
References _mesa_enum_to_string(), _mesa_select_tex_image(), _mesa_warning(), dd_function_table::ChooseTextureFormat, gl_context::Driver, gl_texture_image::InternalFormat, gl_context::Mesa_DXTn, MESA_FORMAT_NONE, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_is_zero_size_texture(), _mesa_texture_storage(), _mesa_TextureView(), copyteximage(), teximage(), and texture_image_multisample().
_mesa_clear_texture_image()
void _mesa_clear_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free and clear fields of the gl_texture_image struct.
Parameters
ctx GL context.
texImage texture image structure to be cleared.
After the call, texImage will have no data associated with it. Its fields are cleared so that its parent object will test incomplete.
References clear_teximage_fields(), gl_context::Driver, and dd_function_table::FreeTextureImageBuffer.
Referenced by _mesa_clear_texture_object(), _mesa_is_zero_size_texture(), and clear_texture_fields().
_mesa_ClearTexImage()
void GLAPIENTRY _mesa_ClearTexImage (GLuint texture, GLint level, GLenum format, GLenum type, const void * data)
References _mesa_lock_texture(), _mesa_unlock_texture(), gl_texture_image::Border, check_clear_tex_image(), dd_function_table::ClearTexSubImage, cb_info::ctx, gl_texture_image::Depth, gl_context::Driver, GET_CURRENT_CONTEXT, get_tex_images_for_clear(), get_tex_obj_for_clear(), gl_texture_image::Height, MAX_FACES, MAX_PIXEL_BYTES, cb_info::texObj, and gl_texture_image::Width.
Referenced by _mesa_base_tex_image().
_mesa_ClearTexSubImage()
void GLAPIENTRY _mesa_ClearTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * data)
References _mesa_error(), _mesa_lock_texture(), _mesa_unlock_texture(), gl_texture_image::Border, check_clear_tex_image(), dd_function_table::ClearTexSubImage, cb_info::ctx, gl_texture_image::Depth, gl_context::Driver, GET_CURRENT_CONTEXT, get_tex_images_for_clear(), get_tex_obj_for_clear(), GLAPIENTRY, gl_texture_image::Height, MAX_FACES, MAX_PIXEL_BYTES, cb_info::texObj, and gl_texture_image::Width.
Referenced by _mesa_base_tex_image().
_mesa_compressed_texture_sub_image()
void _mesa_compressed_texture_sub_image (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, struct gl_texture_image * texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
Common helper for glCompressedTexSubImage1/2/3D() and glCompressedTextureSubImage1/2/3D().
References _mesa_lock_texture(), _mesa_unlock_texture(), check_gen_mipmap(), dd_function_table::CompressedTexSubImage, gl_context::Driver, FLUSH_VERTICES, and GLAPIENTRY.
Referenced by _mesa_base_tex_image(), _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), and _mesa_CompressedTextureSubImage3D().
_mesa_CompressedTexImage1D()
void GLAPIENTRY _mesa_CompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexImage2D()
void GLAPIENTRY _mesa_CompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexImage3D()
void GLAPIENTRY _mesa_CompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data)
References cb_info::ctx, GET_CURRENT_CONTEXT, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexSubImage1D()
void GLAPIENTRY _mesa_CompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexSubImage2D()
void GLAPIENTRY _mesa_CompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTexSubImage3D()
void GLAPIENTRY _mesa_CompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_get_current_tex_object(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTextureSubImage1D()
void GLAPIENTRY _mesa_CompressedTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_lookup_texture_err(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTextureSubImage2D()
void GLAPIENTRY _mesa_CompressedTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_lookup_texture_err(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CompressedTextureSubImage3D()
void GLAPIENTRY _mesa_CompressedTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
References _mesa_compressed_texture_sub_image(), _mesa_cube_level_complete(), _mesa_error(), _mesa_format_image_size(), _mesa_lookup_texture_err(), _mesa_select_tex_image(), compressed_subtexture_error_check(), compressed_subtexture_target_check(), cb_info::ctx, GET_CURRENT_CONTEXT, gl_texture_image::Height, gl_texture_object::Image, cb_info::level, gl_texture_object::Target, gl_texture_image::TexFormat, cb_info::texObj, and gl_texture_image::Width.
Referenced by _mesa_base_tex_image().
_mesa_copy_texture_sub_image()
void _mesa_copy_texture_sub_image (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height, const char * caller)
Implementation for glCopyTex(ture)SubImage1/2/3D() functions.
References _mesa_clip_copytexsubimage(), _mesa_debug(), _mesa_enum_to_string(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), _mesa_update_state(), gl_texture_image::Border, check_gen_mipmap(), copytexsubimage_by_slice(), copytexsubimage_error_check(), FLUSH_VERTICES, get_copy_tex_image_source(), GLAPIENTRY, MESA_VERBOSE, NEW_COPY_TEX_STATE, gl_context::NewState, gl_texture_image::TexFormat, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_base_tex_image(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), and copyteximage().
_mesa_CopyTexImage1D()
void GLAPIENTRY _mesa_CopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
References copyteximage(), cb_info::ctx, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexImage2D()
void GLAPIENTRY _mesa_CopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
References copyteximage(), cb_info::ctx, and GET_CURRENT_CONTEXT.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexSubImage1D()
void GLAPIENTRY _mesa_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexSubImage2D()
void GLAPIENTRY _mesa_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTexSubImage3D()
void GLAPIENTRY _mesa_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTextureSubImage1D()
void GLAPIENTRY _mesa_CopyTextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTextureSubImage2D()
void GLAPIENTRY _mesa_CopyTextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texsubimage_target(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_CopyTextureSubImage3D()
void GLAPIENTRY _mesa_CopyTextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References _mesa_copy_texture_sub_image(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, legal_texsubimage_target(), gl_texture_object::Target, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_cube_face_target()
static GLenum _mesa_cube_face_target (GLenum target, unsigned face) inline static
If the target is GL_TEXTURE_CUBE_MAP, return one of the GL_TEXTURE_CUBE_MAP_POSITIVE/NEGATIVE_X/Y/Z targets corresponding to the face parameter.
Else, return target as-is.
References GLuint.
Referenced by _mesa_get_fallback_texture(), _mesa_TextureView(), initialize_texture_fields(), and prepare_mipmap_level().
_mesa_delete_texture_image()
void _mesa_delete_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free a gl_texture_image and associated data.
This function is a fallback called via ctx->Driver.DeleteTextureImage().
Parameters
texImage texture image.
Free the texture image structure and the associated image data.
References gl_context::Driver, and dd_function_table::FreeTextureImageBuffer.
Referenced by _mesa_is_zero_size_texture().
_mesa_EGLImageTargetTexture2DOES()
void GLAPIENTRY _mesa_EGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
References _mesa_dirty_texobj(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_get_tex_image(), _mesa_is_gles(), _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state(), _NEW_PIXEL, cb_info::ctx, gl_context::Driver, dd_function_table::EGLImageTargetTexture2D, gl_context::Extensions, FLUSH_VERTICES, dd_function_table::FreeTextureImageBuffer, GET_CURRENT_CONTEXT, GL_TEXTURE_EXTERNAL_OES, gl_texture_object::Immutable, gl_context::NewState, gl_extensions::OES_EGL_image, gl_extensions::OES_EGL_image_external, and cb_info::texObj.
Referenced by _mesa_base_tex_image().
_mesa_format_no_online_compression()
bool _mesa_format_no_online_compression (const struct gl_context * ctx, GLenum format)
Return true if the format doesn't support online compression.
References _mesa_is_astc_format(), _mesa_is_etc2_format(), and compressedteximage_only_format().
Referenced by _is_resource_supported(), _mesa_base_tex_image(), copytexsubimage_error_check(), copytexture_error_check(), texsubimage_error_check(), and texture_error_check().
_mesa_get_tex_image()
struct gl_texture_image* _mesa_get_tex_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level)
Like _mesa_select_tex_image() but if the image doesn't exist, allocate it and install it.
Only return NULL if passed a bad parameter or run out of memory.
References _mesa_error(), _mesa_select_tex_image(), gl_context::Driver, dd_function_table::NewTextureImage, and set_tex_image().
Referenced by _mesa_EGLImageTargetTexture2DOES(), _mesa_get_fallback_texture(), _mesa_is_zero_size_texture(), _mesa_VDPAUMapSurfacesNV(), build_bitmap_atlas(), copyteximage(), get_tex_image(), initialize_texture_fields(), prepare_mipmap_level(), teximage(), and texture_image_multisample().
_mesa_get_tex_max_num_levels()
GLsizei _mesa_get_tex_max_num_levels (GLenum target, GLsizei width, GLsizei height, GLsizei depth)
Return the maximum number of mipmap levels for the given target and the dimensions.
The dimensions are expected not to include the border.
References _mesa_components_in_format(), _mesa_logbase2(), and GL_TEXTURE_EXTERNAL_OES.
Referenced by _mesa_base_tex_image(), init_teximage_fields_ms(), and tex_storage_error_check().
_mesa_get_texture_dimensions()
GLint _mesa_get_texture_dimensions (GLenum target)
Return number of dimensions per mipmap level for the given texture target.
References _mesa_problem(), and GL_TEXTURE_EXTERNAL_OES.
Referenced by _get_target_dimensions(), _mesa_base_tex_image(), _mesa_GetCompressedTexSubImage_sw(), _mesa_GetTexSubImage_sw(), and getcompressedteximage_error_check().
_mesa_get_texture_layers()
GLuint _mesa_get_texture_layers (const struct gl_texture_object * texObj, GLint level)
Return the number of layers present in the given level of an array, cubemap or 3D texture.
If the texture is not layered return zero.
References gl_texture_image::Depth, GL_TEXTURE_EXTERNAL_OES, gl_texture_image::Height, gl_texture_object::Image, MAX_TEXTURE_LEVELS, and gl_texture_object::Target.
Referenced by _mesa_base_tex_image(), and _mesa_is_image_unit_valid().
_mesa_init_teximage_fields()
void _mesa_init_teximage_fields (struct gl_context * ctx, struct gl_texture_image * img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, mesa_format format)
References init_teximage_fields_ms().
Referenced by _mesa_get_fallback_texture(), _mesa_is_zero_size_texture(), build_bitmap_atlas(), copyteximage(), initialize_texture_fields(), prepare_mipmap_level(), teximage(), and texture_image_multisample().
_mesa_is_array_texture()
bool _mesa_is_array_texture (GLenum target)
Test if a target is an array target.
Parameters
target texture target.
Returns
true if the target is an array target, false otherwise.
Referenced by _mesa_GetInternalformativ(), and _mesa_is_zero_size_texture().
_mesa_is_cube_face()
static GLboolean _mesa_is_cube_face (GLenum target) inline static
Is the given value one of the 6 cube faces?
References GLuint.
Referenced by _mesa_legal_texture_base_format_for_target(), _mesa_tex_target_to_face(), check_textarget(), and get_tex_memcpy().
_mesa_is_cube_map_texture()
bool _mesa_is_cube_map_texture (GLenum target)
Test if a target is a cube map.
Parameters
target texture target.
Returns
true if the target is a cube map, false otherwise.
Referenced by _mesa_base_tex_image(), and _mesa_GetInternalformativ().
_mesa_is_proxy_texture()
GLboolean _mesa_is_proxy_texture (GLenum target)
Test if a target is a proxy target.
Parameters
target texture target.
Returns
GL_TRUE if the target is a proxy target, GL_FALSE otherwise.
References NUM_TEXTURE_TARGETS.
Referenced by _mesa_is_zero_size_texture(), _mesa_texture_storage(), get_tex_level_parameter_image(), tex_storage_error_check(), teximage(), and texture_image_multisample().
_mesa_is_renderable_texture_format()
GLboolean _mesa_is_renderable_texture_format (struct gl_context * ctx, GLenum internalformat)
References _mesa_base_fbo_format(), gl_extensions::ARB_texture_stencil8, and gl_context::Extensions.
Referenced by _is_resource_supported(), _mesa_base_tex_image(), and texture_image_multisample().
_mesa_is_zero_size_texture()
static GLboolean _mesa_is_zero_size_texture (const struct gl_texture_image * texImage) inline static
Are any of the dimensions of given texture equal to zero?
References _mesa_choose_texture_format(), _mesa_clear_texture_image(), _mesa_delete_texture_image(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_is_array_texture(), _mesa_is_proxy_texture(), _mesa_select_tex_image(), _mesa_update_fbo_texture(), gl_texture_image::Depth, GLuint, gl_texture_image::Height, teximage(), and gl_texture_image::Width.
Referenced by get_compressed_texture_image(), and get_texture_image().
_mesa_legal_texture_base_format_for_target()
bool _mesa_legal_texture_base_format_for_target (struct gl_context * ctx, GLenum target, GLenum internalFormat)
Verify that a texture format is valid with a particular target.
In particular, textures with base format of GL_DEPTH_COMPONENT or GL_DEPTH_STENCIL are only valid with certain, context dependent texture targets.
Parameters
ctx GL context
target Texture target
internalFormat Internal format of the texture image
Returns
true if the combination is legal, false otherwise.
References _mesa_base_tex_format(), _mesa_has_texture_cube_map_array(), _mesa_is_cube_face(), gl_context::API, API_OPENGLES2, gl_extensions::EXT_gpu_shader4, gl_context::Extensions, gl_extensions::OES_depth_texture_cube_map, and gl_context::Version.
Referenced by _is_resource_supported(), _mesa_base_tex_image(), tex_storage_error_check(), and texture_error_check().
_mesa_legal_texture_dimensions()
GLboolean _mesa_legal_texture_dimensions (struct gl_context * ctx, GLenum target, GLint level, GLint width, GLint height, GLint depth, GLint border)
Check the width, height, depth and border of a texture image are legal.
Used by all the glTexImage, glCompressedTexImage and glCopyTexImage functions. The target and level parameters will have already been validated.
Returns
GL_TRUE if size is OK, GL_FALSE otherwise.
References _mesa_is_pow_two(), _mesa_problem(), gl_extensions::ARB_texture_non_power_of_two, gl_context::Const, gl_context::Extensions, gl_constants::Max3DTextureLevels, gl_constants::MaxArrayTextureLayers, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, and gl_constants::MaxTextureRectSize.
Referenced by _mesa_base_tex_image(), _mesa_texture_storage(), _mesa_TextureView(), copyteximage(), teximage(), and texture_image_multisample().
_mesa_max_texture_levels()
GLint _mesa_max_texture_levels (struct gl_context * ctx, GLenum target)
Get the maximum number of allowed mipmap levels.
Parameters
ctx GL context.
target texture target.
Returns
the maximum number of allowed mipmap levels for the given texture target, or zero if passed a bad target.
See also
gl_constants.
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles31(), gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_context::Const, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_constants::Max3DTextureLevels, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, and gl_extensions::NV_texture_rectangle.
Referenced by _mesa_base_tex_image(), _mesa_generate_mipmap(), check_level(), compressed_subtexture_error_check(), compressed_texture_error_check(), copytexsubimage_error_check(), copytexture_error_check(), get_tex_level_parameteriv(), getcompressedteximage_error_check(), getteximage_error_check(), tex_storage_error_check(), texsubimage_error_check(), and texture_error_check().
_mesa_num_tex_faces()
static GLuint _mesa_num_tex_faces (GLenum target) inline static
Return number of faces for a texture target.
This will be 6 for cube maps and 1 otherwise. NOTE: this function is not used for cube map arrays which operate more like 2D arrays than cube maps.
Referenced by _mesa_AllocTextureStorage_sw(), _mesa_test_proxy_teximage(), _mesa_test_texobj_completeness(), clear_texture_fields(), initialize_texture_fields(), prepare_mipmap_level(), texture_size(), and update_fbo_texture().
_mesa_select_tex_image()
struct gl_texture_image* _mesa_select_tex_image (const struct gl_texture_object * texObj, GLenum target, GLint level)
Get a texture image pointer from a texture object, given a texture target and mipmap level.
The target and level parameters should have already been error-checked.
Parameters
texObj texture unit.
target texture target.
level image level.
Returns
pointer to the texture image structure, or NULL on failure.
References _mesa_tex_target_to_face(), GLuint, gl_texture_object::Image, and MAX_TEXTURE_LEVELS.
Referenced by _mesa_choose_texture_format(), _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), _mesa_CompressedTextureSubImage3D(), _mesa_copy_texture_sub_image(), _mesa_generate_mipmap(), _mesa_generate_texture_mipmap(), _mesa_get_framebuffer_attachment_parameter(), _mesa_get_tex_image(), _mesa_is_zero_size_texture(), _mesa_prepare_mipmap_levels(), _mesa_set_texture_view_state(), _mesa_TextureView(), _mesa_VDPAUUnmapSurfacesNV(), compressed_subtexture_error_check(), copyteximage(), copytexsubimage_error_check(), dimensions_error_check(), generate_mipmap_compressed(), generate_mipmap_uncompressed(), get_tex_images_for_clear(), get_tex_level_parameter_image(), get_texture_image_dims(), prepare_target(), select_tex_image(), texsubimage(), texsubimage_error_check(), and texturesubimage().
_mesa_target_can_be_compressed()
GLboolean _mesa_target_can_be_compressed (const struct gl_context * ctx, GLenum target, GLenum intFormat, GLenum * error)
Helper function to determine whether a target and specific compression format are supported.
The error parameter returns GL_NO_ERROR if the target can be compressed. Otherwise it returns either GL_INVALID_OPERATION or GL_INVALID_ENUM, whichever is more appropriate.
References _mesa_get_format_layout(), _mesa_glenum_to_compressed_format(), _mesa_has_texture_cube_map_array(), _mesa_is_gles3(), gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_cube_map, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::KHR_texture_compression_astc_hdr, gl_extensions::KHR_texture_compression_astc_sliced_3d, MESA_FORMAT_LAYOUT_ASTC, MESA_FORMAT_LAYOUT_BPTC, MESA_FORMAT_LAYOUT_ETC2, and write_error().
Referenced by _is_resource_supported(), _mesa_base_tex_image(), compressed_texture_error_check(), copytexture_error_check(), tex_storage_error_check(), and texture_error_check().
_mesa_test_proxy_teximage()
GLboolean _mesa_test_proxy_teximage (struct gl_context * ctx, GLenum target, GLuint numLevels, GLint level, mesa_format format, GLuint numSamples, GLint width, GLint height, GLint depth)
This is the fallback for Driver.TestProxyTexImage() for doing device- specific texture image size checks.
A hardware driver might override this function if, for example, the max 3D texture size is 512x512x64 (i.e. not a cube).
Note that width, height, depth == 0 is not an error. However, a texture with zero width/height/depth will be considered "incomplete" and texturing will effectively be disabled.
Parameters
target any texture target/type
numLevels number of mipmap levels in the texture or 0 if not known
level as passed to glTexImage
format the MESA_FORMAT_x for the tex image
numSamples number of samples per texel
width as passed to glTexImage
height as passed to glTexImage
depth as passed to glTexImage
Returns
GL_TRUE if the image is acceptable, GL_FALSE if not acceptable.
References _mesa_format_image_size64(), _mesa_next_mipmap_level_size(), _mesa_num_tex_faces(), gl_context::Const, and gl_constants::MaxTextureMbytes.
Referenced by _mesa_base_tex_image().
_mesa_tex_target_is_layered()
GLboolean _mesa_tex_target_is_layered (GLenum target)
Check if a texture target can have more than one layer.
References GL_TEXTURE_EXTERNAL_OES, and GLuint.
Referenced by _mesa_base_tex_image(), _mesa_BindImageTexture(), _mesa_BindImageTextures(), and _mesa_is_image_unit_valid().
_mesa_tex_target_to_face()
static GLuint _mesa_tex_target_to_face (GLenum target) inline static
For cube map faces, return a face index in [0,5].
For other targets return 0;
References _mesa_is_cube_face(), and GLuint.
Referenced by _mesa_framebuffer_texture(), _mesa_select_tex_image(), copyteximage(), get_compressed_texture_image(), get_texture_image(), set_tex_image(), set_texture_attachment(), and teximage().
_mesa_TexBuffer()
void GLAPIENTRY _mesa_TexBuffer (GLenum target, GLenum internalFormat, GLuint buffer)
GL_ARB_texture_buffer_object.
References _mesa_get_current_tex_object(), _mesa_lookup_bufferobj_err(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TexBufferRange()
void GLAPIENTRY _mesa_TexBufferRange (GLenum target, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GL_ARB_texture_buffer_range.
References _mesa_get_current_tex_object(), _mesa_lookup_bufferobj_err(), check_texture_buffer_range(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TexImage1D()
void GLAPIENTRY _mesa_TexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image().
_mesa_TexImage2D()
void GLAPIENTRY _mesa_TexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image(), and _mesa_cpal_compressed_teximage2d().
_mesa_TexImage2DMultisample()
void GLAPIENTRY _mesa_TexImage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, and texture_image_multisample().
Referenced by _mesa_base_tex_image().
_mesa_TexImage3D()
void GLAPIENTRY _mesa_TexImage3D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and teximage().
Referenced by _mesa_base_tex_image(), and _mesa_TexImage3DEXT().
_mesa_TexImage3DEXT()
void GLAPIENTRY _mesa_TexImage3DEXT (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References _mesa_TexImage3D(), and GLAPIENTRY.
Referenced by _mesa_base_tex_image().
_mesa_TexImage3DMultisample()
void GLAPIENTRY _mesa_TexImage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, cb_info::texObj, and texture_image_multisample().
Referenced by _mesa_base_tex_image().
_mesa_TexStorage2DMultisample()
void GLAPIENTRY _mesa_TexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TexStorage3DMultisample()
void GLAPIENTRY _mesa_TexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References _mesa_get_current_tex_object(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TexSubImage1D()
void GLAPIENTRY _mesa_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texsubimage().
Referenced by _mesa_base_tex_image().
_mesa_TexSubImage2D()
void GLAPIENTRY _mesa_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texsubimage().
Referenced by _mesa_base_tex_image().
_mesa_TexSubImage3D()
void GLAPIENTRY _mesa_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texsubimage().
Referenced by _mesa_base_tex_image().
_mesa_texture_sub_image()
void _mesa_texture_sub_image (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, struct gl_texture_image * texImage, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, bool dsa)
Helper that implements the glTexSubImage1/2/3D() and glTextureSubImage1/2/3D() functions.
References _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state(), _NEW_PIXEL, gl_texture_image::Border, check_gen_mipmap(), gl_context::Driver, FLUSH_VERTICES, gl_context::NewState, dd_function_table::TexSubImage, and gl_context::Unpack.
Referenced by _mesa_base_tex_image(), texsubimage(), and texturesubimage().
_mesa_TextureBuffer()
void GLAPIENTRY _mesa_TextureBuffer (GLuint texture, GLenum internalFormat, GLuint buffer)
References _mesa_lookup_bufferobj_err(), _mesa_lookup_texture_err(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TextureBufferRange()
void GLAPIENTRY _mesa_TextureBufferRange (GLuint texture, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
References _mesa_lookup_bufferobj_err(), _mesa_lookup_texture_err(), check_texture_buffer_range(), check_texture_buffer_target(), cb_info::ctx, GET_CURRENT_CONTEXT, gl_texture_object::Target, cb_info::texObj, and texture_buffer_range().
Referenced by _mesa_base_tex_image().
_mesa_TextureStorage2DMultisample()
void GLAPIENTRY _mesa_TextureStorage2DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Target, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TextureStorage3DMultisample()
void GLAPIENTRY _mesa_TextureStorage3DMultisample (GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References _mesa_lookup_texture_err(), cb_info::ctx, GET_CURRENT_CONTEXT, gl_texture_object::Target, cb_info::texObj, texture_image_multisample(), and valid_texstorage_ms_parameters().
Referenced by _mesa_base_tex_image().
_mesa_TextureSubImage1D()
void GLAPIENTRY _mesa_TextureSubImage1D (GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texturesubimage().
Referenced by _mesa_base_tex_image().
_mesa_TextureSubImage2D()
void GLAPIENTRY _mesa_TextureSubImage2D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, GLAPIENTRY, and texturesubimage().
Referenced by _mesa_base_tex_image().
_mesa_TextureSubImage3D()
void GLAPIENTRY _mesa_TextureSubImage3D (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
References cb_info::ctx, GET_CURRENT_CONTEXT, and texturesubimage().
Referenced by _mesa_base_tex_image().
_mesa_update_fbo_texture()
void _mesa_update_fbo_texture (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint face, GLuint level)
When a texture image is specified we have to check if it's bound to any framebuffer objects (render to texture) in order to detect changes in size or format since that effects FBO completeness.
Any FBOs rendering into the texture must be re-validated.
References _mesa_HashWalk(), gl_texture_object::_RenderToTexture, check_rtt_cb(), cb_info::ctx, cb_info::face, gl_shared_state::FrameBuffers, cb_info::level, gl_context::Shared, and cb_info::texObj.
Referenced by _mesa_is_zero_size_texture(), copyteximage(), prepare_mipmap_level(), teximage(), texture_image_multisample(), and update_fbo_texture().
_mesa_validate_texbuffer_format()
mesa_format _mesa_validate_texbuffer_format (const struct gl_context * ctx, GLenum internalFormat)
References _mesa_get_format_base_format(), _mesa_get_format_datatype(), gl_extensions::ARB_texture_buffer_object_rgb32, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_context::Extensions, get_texbuffer_format(), and MESA_FORMAT_NONE.
Referenced by _is_resource_supported(), _mesa_base_tex_image(), texture_buffer_range(), and validate_clear_buffer_format().