Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texobj.c File Reference
Texture object management.
#include <stdio.h>
#include "bufferobj.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "formats.h"
#include "hash.h"
#include "imports.h"
#include "macros.h"
#include "shaderimage.h"
#include "teximage.h"
#include "texobj.h"
#include "texstate.h"
#include "mtypes.h"
#include "program/prog_instruction.h"
Functions
API functions
void GLAPIENTRY _mesa_GenTextures (GLsizei n, GLuint *textures)
Generate texture names.
void GLAPIENTRY _mesa_CreateTextures (GLenum target, GLsizei n, GLuint *textures)
Create texture objects.
static void unbind_texobj_from_fbo (struct gl_context *ctx, struct gl_texture_object *texObj)
Check if the given texture object is bound to the current draw or read framebuffer.
static void unbind_texobj_from_texunits (struct gl_context *ctx, struct gl_texture_object *texObj)
Check if the given texture object is bound to any texture image units and unbind it if so (revert to default textures).
static void unbind_texobj_from_image_units (struct gl_context *ctx, struct gl_texture_object *texObj)
Check if the given texture object is bound to any shader image unit and unbind it if that's the case.
static void unbind_textures_from_unit (struct gl_context *ctx, GLuint unit)
Unbinds all textures bound to the given texture image unit.
void GLAPIENTRY _mesa_DeleteTextures (GLsizei n, const GLuint *textures)
Delete named textures.
void _mesa_delete_nameless_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
This deletes a texObj without altering the hash table.
int _mesa_tex_target_to_index (const struct gl_context *ctx, GLenum target)
Convert a GL texture target enum such as GL_TEXTURE_2D or GL_TEXTURE_3D into the corresponding Mesa texture target index.
static void bind_texture (struct gl_context *ctx, unsigned unit, struct gl_texture_object *texObj)
Do actual texture binding.
void GLAPIENTRY _mesa_BindTexture (GLenum target, GLuint texName)
Implement glBindTexture().
void GLAPIENTRY _mesa_BindTextureUnit (GLuint unit, GLuint texture)
OpenGL 4.5 / GL_ARB_direct_state_access glBindTextureUnit().
void GLAPIENTRY _mesa_BindTextures (GLuint first, GLsizei count, const GLuint *textures)
OpenGL 4.4 / GL_ARB_multi_bind glBindTextures().
void GLAPIENTRY _mesa_PrioritizeTextures (GLsizei n, const GLuint *texName, const GLclampf *priorities)
Set texture priorities.
GLboolean GLAPIENTRY _mesa_AreTexturesResident (GLsizei n, const GLuint *texName, GLboolean *residences)
See if textures are loaded in texture memory.
GLboolean GLAPIENTRY _mesa_IsTexture (GLuint texture)
See if a name corresponds to a texture.
void _mesa_lock_context_textures (struct gl_context *ctx)
Simplest implementation of texture locking: grab the shared tex mutex.
void _mesa_unlock_context_textures (struct gl_context *ctx)
void GLAPIENTRY _mesa_InvalidateTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_InvalidateTexImage (GLuint texture, GLint level)
Internal functions
enum base_mipmap { BASE, MIPMAP }
static bool valid_filter_for_float (const struct gl_context *ctx, const struct gl_texture_object *obj)
This function checks for all valid combinations of Min and Mag filters for Float types, when extensions like OES_texture_float and OES_texture_float_linear are supported.
struct gl_texture_object * _mesa_lookup_texture (struct gl_context *ctx, GLuint id)
Return the gl_texture_object for a given ID.
struct gl_texture_object * _mesa_lookup_texture_err (struct gl_context *ctx, GLuint id, const char *func)
Wrapper around _mesa_lookup_texture that throws GL_INVALID_OPERATION if id is not in the hash table.
struct gl_texture_object * _mesa_lookup_texture_locked (struct gl_context *ctx, GLuint id)
struct gl_texture_object * _mesa_get_current_tex_object (struct gl_context *ctx, GLenum target)
Return a pointer to the current texture object for the given target on the current texture unit.
struct gl_texture_object * _mesa_new_texture_object (struct gl_context *ctx, GLuint name, GLenum target)
Allocate and initialize a new texture object.
void _mesa_initialize_texture_object (struct gl_context *ctx, struct gl_texture_object *obj, GLuint name, GLenum target)
Initialize a new texture object to default values.
static void finish_texture_init (struct gl_context *ctx, GLenum target, struct gl_texture_object *obj)
Some texture initialization can't be finished until we know which target it's getting bound to (GL_TEXTURE_1D/2D/etc).
void _mesa_delete_texture_object (struct gl_context *ctx, struct gl_texture_object *texObj)
Deallocate a texture object struct.
void _mesa_copy_texture_object (struct gl_texture_object *dest, const struct gl_texture_object *src)
Copy texture object state from one texture object to another.
void _mesa_clear_texture_object (struct gl_context *ctx, struct gl_texture_object *texObj)
Free all texture images of the given texture object.
static GLboolean valid_texture_object (const struct gl_texture_object *tex)
Check if the given texture object is valid by examining its Target field.
void _mesa_reference_texobj_ (struct gl_texture_object **ptr, struct gl_texture_object *tex)
Reference (or unreference) a texture object.
static void incomplete (struct gl_texture_object *t, enum base_mipmap bm, const char *fmt,...)
Mark a texture object as incomplete.
void _mesa_test_texobj_completeness (const struct gl_context *ctx, struct gl_texture_object *t)
Examine a texture object to determine if it is complete.
GLboolean _mesa_cube_level_complete (const struct gl_texture_object *texObj, const GLint level)
GLboolean _mesa_cube_complete (const struct gl_texture_object *texObj)
Check if the given cube map texture is "cube complete" as defined in the OpenGL specification.
void _mesa_dirty_texobj (struct gl_context *ctx, struct gl_texture_object *texObj)
Mark a texture object dirty.
struct gl_texture_object * _mesa_get_fallback_texture (struct gl_context *ctx, gl_texture_index tex)
Return pointer to a default/fallback texture of the given type/target.
static GLuint texture_size (const struct gl_texture_object *texObj)
Compute the size of the given texture object, in bytes.
static void count_tex_size (GLuint key, void *data, void *userData)
Callback called from _mesa_HashWalk()
GLuint _mesa_total_texture_memory (struct gl_context *ctx)
Compute total size (in bytes) of all textures for the given context.
GLenum _mesa_texture_base_format (const struct gl_texture_object *texObj)
Return the base format for the given texture object by looking at the base texture image.
static struct gl_texture_object * invalidate_tex_image_error_check (struct gl_context *ctx, GLuint texture, GLint level, const char *name)
static void create_textures (struct gl_context *ctx, GLenum target, GLsizei n, GLuint *textures, const char *caller)
Helper function for glCreateTextures and glGenTextures.
Detailed Description
Texture object management.
Enumeration Type Documentation
base_mipmap
enum base_mipmap
Enumerator
BASE
MIPMAP
Function Documentation
_mesa_AreTexturesResident()
GLboolean GLAPIENTRY _mesa_AreTexturesResident (GLsizei n, const GLuint * texName, GLboolean * residences)
See if textures are loaded in texture memory.
Parameters
n number of textures to query.
texName array with the texture names.
residences array which will hold the residence status.
Returns
GL_TRUE if all textures are resident and residences is left unchanged,
Note: we assume all textures are always resident
References _mesa_debug(), _mesa_error(), _mesa_lookup_texture(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete().
_mesa_BindTexture()
void GLAPIENTRY _mesa_BindTexture (GLenum target, GLuint texName)
Implement glBindTexture().
Do error checking, look-up or create a new texture object, then bind it in the current texture unit.
Parameters
target texture target.
texName texture name.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_texture(), _mesa_tex_target_to_index(), API_OPENGL_CORE, bind_texture(), finish_texture_init(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, NUM_TEXTURE_TARGETS, gl_texture_object::Target, gl_texture_object::TargetIndex, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete(), and pop_texture_group().
_mesa_BindTextures()
void GLAPIENTRY _mesa_BindTextures (GLuint first, GLsizei count, const GLuint * textures)
OpenGL 4.4 / GL_ARB_multi_bind glBindTextures().
References gl_texture_unit::_Current, _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_lookup_texture_locked(), bind_texture(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Name, gl_texture_object::Target, and unbind_textures_from_unit().
Referenced by _mesa_is_texture_complete().
_mesa_BindTextureUnit()
void GLAPIENTRY _mesa_BindTextureUnit (GLuint unit, GLuint texture)
OpenGL 4.5 / GL_ARB_direct_state_access glBindTextureUnit().
Parameters
unit texture unit.
texture texture name.
See also
glBindTexture().
If the named texture is 0, this will reset each target for the specified texture unit to its default texture. If the named texture is not 0 or a recognized texture name, this throws GL_INVALID_OPERATION.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_lookup_texture(), _mesa_max_tex_unit(), bind_texture(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, gl_texture_object::Target, unbind_textures_from_unit(), valid_texture_object(), VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete().
_mesa_clear_texture_object()
void _mesa_clear_texture_object (struct gl_context * ctx, struct gl_texture_object * texObj)
Free all texture images of the given texture object.
Parameters
ctx GL context.
t texture object.
See also
_mesa_clear_texture_image().
References _mesa_clear_texture_image(), GLuint, gl_texture_object::Image, MAX_FACES, MAX_TEXTURE_LEVELS, and gl_texture_object::Target.
_mesa_copy_texture_object()
void _mesa_copy_texture_object (struct gl_texture_object * dest, const struct gl_texture_object * src)
Copy texture object state from one texture object to another.
Use for glPush/PopAttrib.
Parameters
dest destination texture object.
src source texture object.
References gl_texture_object::_BaseComplete, gl_texture_object::_IsFloat, gl_texture_object::_IsHalfFloat, gl_texture_object::_MaxLambda, gl_texture_object::_MaxLevel, gl_texture_object::_MipmapComplete, gl_texture_object::_Swizzle, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, COPY_4V, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_color_union::f, gl_texture_object::GenerateMipmap, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Name, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, gl_texture_object::Swizzle, gl_texture_object::Target, gl_texture_object::TargetIndex, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_PushAttrib().
_mesa_CreateTextures()
void GLAPIENTRY _mesa_CreateTextures (GLenum target, GLsizei n, GLuint * textures)
Create texture objects.
Parameters
target the texture target for each name to be generated.
n number of texture names to be generated.
textures an array in which will hold the generated texture names.
See also
glCreateTextures(), glGenTextures().
Calls _mesa_HashFindFreeKeyBlock() to find a block of free texture IDs which are stored in textures. Corresponding empty texture objects are also generated.
References _mesa_error(), _mesa_tex_target_to_index(), create_textures(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_is_texture_complete().
_mesa_cube_complete()
GLboolean _mesa_cube_complete (const struct gl_texture_object * texObj)
Check if the given cube map texture is "cube complete" as defined in the OpenGL specification.
References _mesa_cube_level_complete(), and gl_texture_object::BaseLevel.
Referenced by _mesa_generate_texture_mipmap(), and _mesa_is_texture_complete().
_mesa_cube_level_complete()
GLboolean _mesa_cube_level_complete (const struct gl_texture_object * texObj, const GLint level)
References GLuint, gl_texture_image::Height, gl_texture_object::Image, MAX_TEXTURE_LEVELS, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_CompressedTextureSubImage3D(), _mesa_cube_complete(), _mesa_is_texture_complete(), and texturesubimage().
_mesa_delete_nameless_texture()
void _mesa_delete_nameless_texture (struct gl_context * ctx, struct gl_texture_object * texObj)
This deletes a texObj without altering the hash table.
References _mesa_lock_texture(), _mesa_reference_texobj(), _mesa_unlock_texture(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, gl_context::NewState, unbind_texobj_from_fbo(), unbind_texobj_from_image_units(), and unbind_texobj_from_texunits().
Referenced by _mesa_is_texture_complete().
_mesa_delete_texture_object()
void _mesa_delete_texture_object (struct gl_context * ctx, struct gl_texture_object * texObj)
Deallocate a texture object struct.
It should have already been removed from the texture object pool. Called via ctx->Driver.DeleteTexture() if not overriden by a driver.
Parameters
shared the shared GL state to which the object belongs.
texObj the texture object to delete.
References _mesa_reference_buffer_object(), gl_texture_object::BufferObject, dd_function_table::DeleteTextureImage, gl_context::Driver, GLuint, gl_texture_object::Image, gl_texture_object::Label, MAX_TEXTURE_LEVELS, gl_texture_object::Mutex, and gl_texture_object::Target.
Referenced by _mesa_GetInternalformativ().
_mesa_DeleteTextures()
void GLAPIENTRY _mesa_DeleteTextures (GLsizei n, const GLuint * textures)
Delete named textures.
Parameters
n number of textures to be deleted.
textures array of texture IDs to be deleted.
See also
glDeleteTextures().
If we're about to delete a texture that's currently bound to any texture unit, unbind the texture first. Decrement the reference count on the texture object and delete it if it's zero. Recall that texture objects can be shared among several rendering contexts.
References _mesa_debug(), _mesa_error(), _mesa_HashRemove(), _mesa_lock_texture(), _mesa_lookup_texture(), _mesa_reference_texobj(), _mesa_unlock_texture(), _NEW_TEXTURE_OBJECT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, gl_texture_object::Name, unbind_texobj_from_fbo(), unbind_texobj_from_image_units(), unbind_texobj_from_texunits(), VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete().
_mesa_dirty_texobj()
void _mesa_dirty_texobj (struct gl_context * ctx, struct gl_texture_object * texObj)
Mark a texture object dirty.
It forces the object to be incomplete and forces the context to re-validate its state.
Parameters
ctx GL context.
texObj texture object.
References gl_texture_object::_BaseComplete, gl_texture_object::_MipmapComplete, _NEW_TEXTURE_OBJECT, and gl_context::NewState.
Referenced by _mesa_EGLImageTargetTexture2DOES(), _mesa_is_texture_complete(), copyteximage(), incomplete(), and teximage().
_mesa_GenTextures()
void GLAPIENTRY _mesa_GenTextures (GLsizei n, GLuint * textures)
Generate texture names.
Parameters
n number of texture names to be generated.
textures an array in which will hold the generated texture names.
See also
glGenTextures(), glCreateTextures().
Calls _mesa_HashFindFreeKeyBlock() to find a block of free texture IDs which are stored in textures. Corresponding empty texture objects are also generated.
References create_textures(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_is_texture_complete().
_mesa_get_current_tex_object()
struct gl_texture_object* _mesa_get_current_tex_object (struct gl_context * ctx, GLenum target)
Return a pointer to the current texture object for the given target on the current texture unit.
Note: all <target> error checking should have been done by this point.
References _mesa_get_current_tex_unit(), _mesa_has_texture_cube_map_array(), _mesa_is_gles(), _mesa_problem(), gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_texture_unit::CurrentTex, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_extensions::NV_texture_rectangle, gl_extensions::OES_EGL_image_external, gl_texture_attrib::ProxyTex, gl_context::Texture, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_BUFFER_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, TEXTURE_EXTERNAL_INDEX, and TEXTURE_RECT_INDEX.
Referenced by _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_EGLImageTargetTexture2DOES(), _mesa_GenerateMipmap(), _mesa_GetCompressedTexImage(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), _mesa_GetTexImage(), _mesa_GetTexLevelParameterfv(), _mesa_GetTexLevelParameteriv(), _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TexImage2DMultisample(), _mesa_TexImage3DMultisample(), _mesa_TexStorage2DMultisample(), _mesa_TexStorage3DMultisample(), copyteximage(), mutable_tex_object(), teximage(), texstorage(), and texsubimage().
_mesa_get_fallback_texture()
struct gl_texture_object* _mesa_get_fallback_texture (struct gl_context * ctx, gl_texture_index tex)
Return pointer to a default/fallback texture of the given type/target.
The texture is an RGBA texture with all texels = (0,0,0,1). That's the value a GLSL sampler should get when sampling from an incomplete texture.
References gl_texture_object::_BaseComplete, _mesa_cube_face_target(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_test_texobj_completeness(), gl_texture_object::_MipmapComplete, dd_function_table::ChooseTextureFormat, gl_context::DefaultPacking, gl_context::Driver, gl_shared_state::FallbackTex, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, dd_function_table::NewTextureObject, gl_texture_object::RefCount, gl_texture_object::Sampler, gl_context::Shared, dd_function_table::TexImage, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_BUFFER_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, TEXTURE_EXTERNAL_INDEX, and TEXTURE_RECT_INDEX.
Referenced by _mesa_is_texture_complete(), and update_single_program_texture().
_mesa_initialize_texture_object()
void _mesa_initialize_texture_object (struct gl_context * ctx, struct gl_texture_object * obj, GLuint name, GLenum target)
Initialize a new texture object to default values.
Parameters
obj the texture object
name the texture name
target the texture target
References gl_texture_object::_BufferObjectFormat, _mesa_tex_target_to_index(), gl_texture_object::_Swizzle, gl_context::API, API_OPENGL_CORE, gl_texture_object::BaseLevel, gl_texture_object::BufferObjectFormat, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, GL_TEXTURE_EXTERNAL_OES, gl_texture_object::ImageFormatCompatibilityType, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, MESA_FORMAT_R_UNORM8, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Mutex, gl_texture_object::Name, NUM_TEXTURE_TARGETS, gl_texture_object::Priority, gl_texture_object::RefCount, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, gl_texture_object::Swizzle, gl_texture_object::Target, gl_texture_object::TargetIndex, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_new_texture_object().
_mesa_InvalidateTexImage()
void GLAPIENTRY _mesa_InvalidateTexImage (GLuint texture, GLint level)
References _mesa_debug(), GET_CURRENT_CONTEXT, invalidate_tex_image_error_check(), MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete().
_mesa_InvalidateTexSubImage()
void GLAPIENTRY _mesa_InvalidateTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth)
References _mesa_debug(), _mesa_error(), gl_texture_image::Border, gl_texture_image::Depth, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_image::Height, gl_texture_object::Image, invalidate_tex_image_error_check(), MESA_VERBOSE, gl_texture_object::Target, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_is_texture_complete().
_mesa_IsTexture()
GLboolean GLAPIENTRY _mesa_IsTexture (GLuint texture)
See if a name corresponds to a texture.
Parameters
texture texture name.
Returns
GL_TRUE if texture name corresponds to a texture, or GL_FALSE otherwise.
See also
glIsTexture().
Calls _mesa_HashLookup().
References _mesa_debug(), _mesa_lookup_texture(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GET_CURRENT_CONTEXT, MESA_VERBOSE, gl_texture_object::Target, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete().
_mesa_lock_context_textures()
void _mesa_lock_context_textures (struct gl_context * ctx)
Simplest implementation of texture locking: grab the shared tex mutex.
Examine the shared context state timestamp and if there has been a change, set the appropriate bits in ctx->NewState.
This is used to deal with synchronizing things when a texture object is used/modified by different contexts (or threads) which are sharing the texture.
See also _mesa_lock/unlock_texture() in teximage.h
References _NEW_TEXTURE_OBJECT, gl_context::NewState, gl_context::Shared, gl_shared_state::TexMutex, gl_shared_state::TextureStateStamp, and gl_context::TextureStateTimestamp.
Referenced by _mesa_copy_texture_state(), _mesa_is_texture_complete(), _mesa_PushAttrib(), _mesa_update_state(), get_tex_parameterfv(), and pop_texture_group().
_mesa_lookup_texture()
struct gl_texture_object* _mesa_lookup_texture (struct gl_context * ctx, GLuint id)
Return the gl_texture_object for a given ID.
References _mesa_HashLookup(), gl_context::Shared, and gl_shared_state::TexObjects.
Referenced by _mesa_AreTexturesResident(), _mesa_BindImageTexture(), _mesa_BindTexture(), _mesa_BindTextureUnit(), _mesa_DeleteTextures(), _mesa_dump_texture(), _mesa_GetCompressedTextureSubImage(), _mesa_GetTextureSubImage(), _mesa_IsTexture(), _mesa_lookup_texture_err(), _mesa_PrioritizeTextures(), _mesa_TextureView(), get_label_pointer(), get_tex_obj_for_clear(), get_texobj_by_name(), get_texture_for_framebuffer(), get_texture_object_parameteriv(), invalidate_tex_image_error_check(), prepare_target(), register_surface(), texture_object_purgeable(), texture_object_unpurgeable(), texturestorage(), and texturesubimage().
_mesa_lookup_texture_err()
struct gl_texture_object* _mesa_lookup_texture_err (struct gl_context * ctx, GLuint id, const char * func)
Wrapper around _mesa_lookup_texture that throws GL_INVALID_OPERATION if id is not in the hash table.
After calling _mesa_error, it returns NULL.
References _mesa_error(), and _mesa_lookup_texture().
Referenced by _mesa_CompressedTextureSubImage1D(), _mesa_CompressedTextureSubImage2D(), _mesa_CompressedTextureSubImage3D(), _mesa_CopyTextureSubImage1D(), _mesa_CopyTextureSubImage2D(), _mesa_CopyTextureSubImage3D(), _mesa_GenerateTextureMipmap(), _mesa_GetCompressedTextureImage(), _mesa_GetTextureImage(), _mesa_GetTextureLevelParameterfv(), _mesa_GetTextureLevelParameteriv(), _mesa_TextureBuffer(), _mesa_TextureBufferRange(), _mesa_TextureStorage2DMultisample(), and _mesa_TextureStorage3DMultisample().
_mesa_lookup_texture_locked()
struct gl_texture_object* _mesa_lookup_texture_locked (struct gl_context * ctx, GLuint id)
References _mesa_HashLookupLocked(), gl_context::Shared, and gl_shared_state::TexObjects.
Referenced by _mesa_BindImageTextures(), and _mesa_BindTextures().
_mesa_new_texture_object()
struct gl_texture_object* _mesa_new_texture_object (struct gl_context * ctx, GLuint name, GLenum target)
Allocate and initialize a new texture object.
But don't put it into the texture object hash table.
Called via ctx->Driver.NewTextureObject, unless overridden by a device driver.
Parameters
shared the shared GL state structure to contain the texture object
name integer name for the texture object
target either GL_TEXTURE_1D, GL_TEXTURE_2D, GL_TEXTURE_3D, GL_TEXTURE_CUBE_MAP or GL_TEXTURE_RECTANGLE_NV. zero is ok for the sake of GenTextures()
Returns
pointer to new texture object.
References _mesa_initialize_texture_object(), MALLOC_STRUCT, and void.
Referenced by _mesa_GetInternalformativ().
_mesa_PrioritizeTextures()
void GLAPIENTRY _mesa_PrioritizeTextures (GLsizei n, const GLuint * texName, const GLclampf * priorities)
Set texture priorities.
Parameters
n number of textures.
texName texture names.
priorities corresponding texture priorities.
See also
glPrioritizeTextures().
Looks up each texture in the hash, clamps the corresponding priority between 0.0 and 1.0, and calls dd_function_table::PrioritizeTexture.
References _mesa_debug(), _mesa_error(), _mesa_lookup_texture(), _NEW_TEXTURE_OBJECT, F, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, gl_texture_object::Priority, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_is_texture_complete().
_mesa_reference_texobj_()
void _mesa_reference_texobj_ (struct gl_texture_object ** ptr, struct gl_texture_object * tex)
Reference (or unreference) a texture object.
If '*ptr', decrement *ptr's refcount (and delete if it becomes zero). If 'tex' is non-null, increment its refcount. This is normally only called from the _mesa_reference_texobj() macro when there's a real pointer change.
References _mesa_problem(), GET_CURRENT_CONTEXT, gl_texture_object::Mutex, gl_texture_object::RefCount, valid_texture_object(), and void.
Referenced by _mesa_reference_texobj().
_mesa_test_texobj_completeness()
void _mesa_test_texobj_completeness (const struct gl_context * ctx, struct gl_texture_object * t)
Examine a texture object to determine if it is complete.
The gl_texture_object::Complete flag will be set to GL_TRUE or GL_FALSE accordingly.
Parameters
ctx GL context.
t texture object.
According to the texture target, verifies that each of the mipmaps is present and has the expected size.
References gl_texture_object::_BaseComplete, gl_texture_object::_IsIntegerFormat, gl_texture_object::_MaxLambda, gl_texture_object::_MaxLevel, _mesa_get_format_datatype(), _mesa_is_gles(), _mesa_num_tex_faces(), _mesa_problem(), gl_texture_object::_MipmapComplete, BASE, gl_texture_object::BaseLevel, gl_texture_image::Border, gl_context::Const, gl_texture_image::Depth, gl_texture_image::Depth2, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_texture_image::Height, gl_texture_image::Height2, gl_texture_object::Image, gl_texture_object::Immutable, incomplete(), gl_texture_image::InternalFormat, gl_constants::Max3DTextureLevels, MAX_TEXTURE_LEVELS, gl_constants::MaxCubeTextureLevels, gl_texture_object::MaxLevel, gl_texture_image::MaxNumLevels, gl_constants::MaxTextureLevels, MIPMAP, gl_texture_object::NumLevels, gl_texture_object::Target, gl_texture_image::TexFormat, valid_filter_for_float(), gl_texture_image::Width, and gl_texture_image::Width2.
Referenced by _mesa_get_fallback_texture(), _mesa_is_image_unit_valid(), _mesa_is_texture_complete(), prepare_target(), update_ff_texture_state(), and update_single_program_texture().
_mesa_tex_target_to_index()
int _mesa_tex_target_to_index (const struct gl_context * ctx, GLenum target)
Convert a GL texture target enum such as GL_TEXTURE_2D or GL_TEXTURE_3D into the corresponding Mesa texture target index.
Note that proxy targets are not valid here.
Returns
TEXTURE_x_INDEX or -1 if target is invalid
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_is_gles31(), gl_context::API, API_OPENGLES, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_extensions::NV_texture_rectangle, gl_extensions::OES_EGL_image_external, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_BUFFER_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, TEXTURE_EXTERNAL_INDEX, and TEXTURE_RECT_INDEX.
Referenced by _mesa_BindTexture(), _mesa_CreateTextures(), _mesa_initialize_texture_object(), _mesa_TextureView(), finish_texture_init(), get_texobj_by_target(), and register_surface().
_mesa_texture_base_format()
GLenum _mesa_texture_base_format (const struct gl_texture_object * texObj)
Return the base format for the given texture object by looking at the base texture image.
Returns
base format (such as GL_RGBA) or GL_NONE if it can't be determined
References gl_texture_image::_BaseFormat, and _mesa_base_tex_image().
Referenced by _mesa_is_texture_complete().
_mesa_total_texture_memory()
GLuint _mesa_total_texture_memory (struct gl_context * ctx)
Compute total size (in bytes) of all textures for the given context.
For debugging purposes.
References _mesa_HashWalk(), count_tex_size(), gl_shared_state::DefaultTex, GLuint, NUM_TEXTURE_TARGETS, gl_context::Shared, gl_shared_state::TexObjects, and texture_size().
Referenced by _mesa_is_texture_complete().
_mesa_unlock_context_textures()
void _mesa_unlock_context_textures (struct gl_context * ctx)
References GLAPIENTRY, gl_context::Shared, gl_shared_state::TexMutex, gl_shared_state::TextureStateStamp, and gl_context::TextureStateTimestamp.
Referenced by _mesa_copy_texture_state(), _mesa_is_texture_complete(), _mesa_PushAttrib(), _mesa_update_state(), get_tex_parameterfv(), and pop_texture_group().
bind_texture()
static void bind_texture (struct gl_context * ctx, unsigned unit, struct gl_texture_object * texObj) static
Do actual texture binding.
All error checking should have been done prior to calling this function. Note that the texture target (1D, 2D, etc) is always specified by the texObj->TargetIndex.
Parameters
unit index of texture unit to update
texObj the new texture object (cannot be NULL)
References gl_texture_unit::_BoundTextures, _mesa_reference_texobj(), _NEW_TEXTURE_OBJECT, dd_function_table::BindTexture, gl_texture_unit::CurrentTex, gl_context::Driver, FLUSH_VERTICES, GLAPIENTRY, gl_shared_state::Mutex, gl_texture_object::Name, NUM_TEXTURE_TARGETS, gl_texture_attrib::NumCurrentTexUsed, gl_shared_state::RefCount, gl_context::Shared, gl_texture_object::Target, gl_texture_object::TargetIndex, gl_context::Texture, TEXTURE_EXTERNAL_INDEX, gl_texture_attrib::Unit, and valid_texture_object().
Referenced by _mesa_BindTexture(), _mesa_BindTextures(), and _mesa_BindTextureUnit().
count_tex_size()
static void count_tex_size (GLuint key, void * data, void * userData) static
Callback called from _mesa_HashWalk()
References GLuint, texture_size(), and void.
Referenced by _mesa_total_texture_memory().
create_textures()
static void create_textures (struct gl_context * ctx, GLenum target, GLsizei n, GLuint * textures, const char * caller) static
Helper function for glCreateTextures and glGenTextures.
Need this because glCreateTextures should throw errors if target = 0. This is not exposed to the rest of Mesa to encourage Mesa internals to use nameless textures, which do not require expensive hash lookups.
Parameters
target either 0 or a valid / error-checked texture target enum
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsertLocked(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), gl_context::Driver, GLAPIENTRY, GLuint, MESA_VERBOSE, gl_texture_object::Name, dd_function_table::NewTextureObject, gl_context::Shared, gl_shared_state::TexObjects, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_CreateTextures(), and _mesa_GenTextures().
finish_texture_init()
static void finish_texture_init (struct gl_context * ctx, GLenum target, struct gl_texture_object * obj) static
Some texture initialization can't be finished until we know which target it's getting bound to (GL_TEXTURE_1D/2D/etc).
References _mesa_tex_target_to_index(), gl_context::Driver, GL_TEXTURE_EXTERNAL_OES, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, NUM_TEXTURE_TARGETS, gl_texture_object::Sampler, gl_texture_object::Target, gl_texture_object::TargetIndex, dd_function_table::TexParameter, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_BindTexture().
incomplete()
static void incomplete (struct gl_texture_object * t, enum base_mipmap bm, const char * fmt, ...) static
Mark a texture object as incomplete.
There are actually three kinds of (in)completeness:
"base incomplete": the base level of the texture is invalid so no texturing is possible.
"mipmap incomplete": a non-base level of the texture is invalid so mipmap filtering isn't possible, but non-mipmap filtering is.
"texture incompleteness": some combination of texture state and sampler state renders the texture incomplete.
Parameters
t texture object
bm either BASE or MIPMAP to indicate what's incomplete
fmt... string describing why it's incomplete (for debugging).
References gl_texture_object::_BaseComplete, _mesa_debug(), gl_texture_object::_MipmapComplete, BASE, DEBUG_INCOMPLETE_TEXTURE, MESA_DEBUG_FLAGS, and gl_texture_object::Name.
Referenced by _mesa_test_texobj_completeness().
invalidate_tex_image_error_check()
static struct gl_texture_object* invalidate_tex_image_error_check (struct gl_context * ctx, GLuint texture, GLint level, const char * name) static
References _mesa_error(), _mesa_lookup_texture(), gl_texture_object::MaxLevel, and gl_texture_object::Target.
Referenced by _mesa_InvalidateTexImage(), and _mesa_InvalidateTexSubImage().
texture_size()
static GLuint texture_size (const struct gl_texture_object * texObj) static
Compute the size of the given texture object, in bytes.
References _mesa_format_image_size(), _mesa_num_tex_faces(), gl_texture_image::Depth, GLuint, gl_texture_image::Height, gl_texture_object::Image, MAX_TEXTURE_LEVELS, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_total_texture_memory(), and count_tex_size().
unbind_texobj_from_fbo()
static void unbind_texobj_from_fbo (struct gl_context * ctx, struct gl_texture_object * texObj) static
Check if the given texture object is bound to the current draw or read framebuffer.
If so, Unbind it.
References _mesa_detach_renderbuffer(), _mesa_is_user_fbo(), _NEW_BUFFERS, gl_context::DrawBuffer, gl_context::NewState, and gl_context::ReadBuffer.
Referenced by _mesa_delete_nameless_texture(), and _mesa_DeleteTextures().
unbind_texobj_from_image_units()
static void unbind_texobj_from_image_units (struct gl_context * ctx, struct gl_texture_object * texObj) static
Check if the given texture object is bound to any shader image unit and unbind it if that's the case.
References _mesa_default_image_unit(), _mesa_reference_texobj(), gl_context::Const, GLuint, gl_context::ImageUnits, gl_constants::MaxImageUnits, and gl_image_unit::TexObj.
Referenced by _mesa_delete_nameless_texture(), and _mesa_DeleteTextures().
unbind_texobj_from_texunits()
static void unbind_texobj_from_texunits (struct gl_context * ctx, struct gl_texture_object * texObj) static
Check if the given texture object is bound to any texture image units and unbind it if so (revert to default textures).
References gl_texture_unit::_BoundTextures, _mesa_reference_texobj(), gl_texture_unit::CurrentTex, gl_shared_state::DefaultTex, GLuint, NUM_TEXTURE_TARGETS, gl_texture_attrib::NumCurrentTexUsed, gl_context::Shared, gl_texture_object::Target, gl_texture_object::TargetIndex, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_delete_nameless_texture(), and _mesa_DeleteTextures().
unbind_textures_from_unit()
static void unbind_textures_from_unit (struct gl_context * ctx, GLuint unit) static
Unbinds all textures bound to the given texture image unit.
References gl_texture_unit::_BoundTextures, _mesa_reference_texobj(), _NEW_TEXTURE_OBJECT, dd_function_table::BindTexture, gl_texture_unit::CurrentTex, gl_shared_state::DefaultTex, gl_context::Driver, GLAPIENTRY, GLuint, gl_context::NewState, gl_context::Shared, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_BindTextures(), and _mesa_BindTextureUnit().
valid_filter_for_float()
static bool valid_filter_for_float (const struct gl_context * ctx, const struct gl_texture_object * obj) static
This function checks for all valid combinations of Min and Mag filters for Float types, when extensions like OES_texture_float and OES_texture_float_linear are supported.
OES_texture_float mentions support for NEAREST, NEAREST_MIPMAP_NEAREST magnification and minification filters. Mag filters like LINEAR and min filters like NEAREST_MIPMAP_LINEAR, LINEAR_MIPMAP_NEAREST and LINEAR_MIPMAP_LINEAR are only valid in case OES_texture_float_linear is supported.
Returns true in case the filter is valid for given Float type else false.
References gl_texture_object::_IsFloat, gl_texture_object::_IsHalfFloat, gl_context::Extensions, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, gl_extensions::OES_texture_float_linear, gl_extensions::OES_texture_half_float_linear, and gl_texture_object::Sampler.
Referenced by _mesa_test_texobj_completeness().
valid_texture_object()
static GLboolean valid_texture_object (const struct gl_texture_object * tex) static
Check if the given texture object is valid by examining its Target field.
For debugging only.
References _mesa_problem(), GL_TEXTURE_EXTERNAL_OES, gl_texture_object::Name, and gl_texture_object::Target.
Referenced by _mesa_BindTextureUnit(), _mesa_reference_texobj_(), and bind_texture().