Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texparam.c File Reference
glTexParameter-related functions
#include <stdbool.h>
#include "main/glheader.h"
#include "main/blend.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/formats.h"
#include "main/glformats.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/state.h"
#include "main/texcompress.h"
#include "main/texobj.h"
#include "main/texparam.h"
#include "main/teximage.h"
#include "main/texstate.h"
#include "program/prog_instruction.h"
Functions
static GLboolean validate_texture_wrap_mode (struct gl_context *ctx, GLenum target, GLenum wrap)
Check if a coordinate wrap mode is supported for the texture target.
static struct gl_texture_object * get_texobj_by_target (struct gl_context *ctx, GLenum target, GLboolean get)
Get current texture object for given target.
static struct gl_texture_object * get_texobj_by_name (struct gl_context *ctx, GLuint texture, GLboolean get)
Get current texture object for given name.
static GLint comp_to_swizzle (GLenum comp)
Convert GL_RED/GREEN/BLUE/ALPHA/ZERO/ONE to SWIZZLE_X/Y/Z/W/ZERO/ONE.
static void set_swizzle_component (GLuint *swizzle, GLuint comp, GLuint swz)
static void flush (struct gl_context *ctx)
This is called just prior to changing any texture object state which will not affect texture completeness.
static void incomplete (struct gl_context *ctx, struct gl_texture_object *texObj)
This is called just prior to changing any texture object state which could affect texture completeness (texture base level, max level).
GLboolean _mesa_target_allows_setting_sampler_parameters (GLenum target)
static GLboolean set_tex_parameteri (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLint *params, bool dsa)
Set an integer-valued texture parameter.
static GLboolean set_tex_parameterf (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLfloat *params, bool dsa)
Set a float-valued texture parameter.
void _mesa_texture_parameterf (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, GLfloat param, bool dsa)
void _mesa_texture_parameterfv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLfloat *params, bool dsa)
void _mesa_texture_parameteri (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, GLint param, bool dsa)
void _mesa_texture_parameteriv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLint *params, bool dsa)
void _mesa_texture_parameterIiv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLint *params, bool dsa)
void _mesa_texture_parameterIuiv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLuint *params, bool dsa)
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint *params)
Set tex parameter to integer value(s).
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint *params)
Set tex parameter to unsigned integer value(s).
void GLAPIENTRY _mesa_TextureParameterfv (GLuint texture, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TextureParameterf (GLuint texture, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TextureParameteri (GLuint texture, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TextureParameteriv (GLuint texture, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TextureParameterIiv (GLuint texture, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TextureParameterIuiv (GLuint texture, GLenum pname, const GLuint *params)
GLboolean _mesa_legal_get_tex_level_parameter_target (struct gl_context *ctx, GLenum target, bool dsa)
static void get_tex_level_parameter_image (struct gl_context *ctx, const struct gl_texture_object *texObj, GLenum target, GLint level, GLenum pname, GLint *params, bool dsa)
static void get_tex_level_parameter_buffer (struct gl_context *ctx, const struct gl_texture_object *texObj, GLenum pname, GLint *params, bool dsa)
Handle a glGetTexLevelParamteriv() call for a texture buffer.
static bool valid_tex_level_parameteriv_target (struct gl_context *ctx, GLenum target, bool dsa)
static void get_tex_level_parameteriv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLenum pname, GLint *params, bool dsa)
This isn't exposed to the rest of the driver because it is a part of the OpenGL API that is rarely used.
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTextureLevelParameterfv (GLuint texture, GLint level, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTextureLevelParameteriv (GLuint texture, GLint level, GLenum pname, GLint *params)
static void get_tex_parameterfv (struct gl_context *ctx, struct gl_texture_object *obj, GLenum pname, GLfloat *params, bool dsa)
This isn't exposed to the rest of the driver because it is a part of the OpenGL API that is rarely used.
static void get_tex_parameteriv (struct gl_context *ctx, struct gl_texture_object *obj, GLenum pname, GLint *params, bool dsa)
static void get_tex_parameterIiv (struct gl_context *ctx, struct gl_texture_object *obj, GLenum pname, GLint *params, bool dsa)
static void get_tex_parameterIuiv (struct gl_context *ctx, struct gl_texture_object *obj, GLenum pname, GLuint *params, bool dsa)
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_GetTextureParameterfv (GLuint texture, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTextureParameteriv (GLuint texture, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTextureParameterIiv (GLuint texture, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTextureParameterIuiv (GLuint texture, GLenum pname, GLuint *params)
Detailed Description
glTexParameter-related functions
Function Documentation
_mesa_GetTexLevelParameterfv()
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat * params)
References _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), GLAPIENTRY, and valid_tex_level_parameteriv_target().
_mesa_GetTexLevelParameteriv()
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint * params)
References _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), GLAPIENTRY, and valid_tex_level_parameteriv_target().
_mesa_GetTexParameterfv()
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
References GET_CURRENT_CONTEXT, get_tex_parameterfv(), get_texobj_by_target(), and GLAPIENTRY.
Referenced by _mesa_GetTexParameterxv().
_mesa_GetTexParameterIiv()
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint * params)
New in GL 3.0.
References GET_CURRENT_CONTEXT, get_tex_parameterIiv(), get_texobj_by_target(), and GLAPIENTRY.
_mesa_GetTexParameterIuiv()
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint * params)
New in GL 3.0.
References GET_CURRENT_CONTEXT, get_tex_parameterIuiv(), get_texobj_by_target(), and GLAPIENTRY.
_mesa_GetTexParameteriv()
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_tex_parameteriv(), get_texobj_by_target(), and GLAPIENTRY.
_mesa_GetTextureLevelParameterfv()
void GLAPIENTRY _mesa_GetTextureLevelParameterfv (GLuint texture, GLint level, GLenum pname, GLfloat * params)
References _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), GLAPIENTRY, gl_texture_object::Target, and valid_tex_level_parameteriv_target().
_mesa_GetTextureLevelParameteriv()
void GLAPIENTRY _mesa_GetTextureLevelParameteriv (GLuint texture, GLint level, GLenum pname, GLint * params)
References _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), gl_texture_object::Target, and valid_tex_level_parameteriv_target().
_mesa_GetTextureParameterfv()
void GLAPIENTRY _mesa_GetTextureParameterfv (GLuint texture, GLenum pname, GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameterfv(), get_texobj_by_name(), and GLAPIENTRY.
_mesa_GetTextureParameterIiv()
void GLAPIENTRY _mesa_GetTextureParameterIiv (GLuint texture, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameterIiv(), get_texobj_by_name(), and GLAPIENTRY.
_mesa_GetTextureParameterIuiv()
void GLAPIENTRY _mesa_GetTextureParameterIuiv (GLuint texture, GLenum pname, GLuint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameterIuiv(), and get_texobj_by_name().
_mesa_GetTextureParameteriv()
void GLAPIENTRY _mesa_GetTextureParameteriv (GLuint texture, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameteriv(), get_texobj_by_name(), and GLAPIENTRY.
_mesa_legal_get_tex_level_parameter_target()
GLboolean _mesa_legal_get_tex_level_parameter_target (struct gl_context * ctx, GLenum target, bool dsa)
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_multisample, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::NV_texture_rectangle, and gl_context::Version.
Referenced by _mesa_GetInternalformativ(), and valid_tex_level_parameteriv_target().
_mesa_target_allows_setting_sampler_parameters()
GLboolean _mesa_target_allows_setting_sampler_parameters (GLenum target)
Referenced by _mesa_GetInternalformativ(), _mesa_texture_parameterIiv(), _mesa_texture_parameterIuiv(), _mesa_texture_parameteriv(), set_tex_parameterf(), and set_tex_parameteri().
_mesa_TexParameterf()
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
References _mesa_texture_parameterf(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
Referenced by _mesa_TexParameterx(), and pop_texture_group().
_mesa_TexParameterfv()
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References _mesa_texture_parameterfv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
Referenced by _mesa_TexParameterxv(), and pop_texture_group().
_mesa_TexParameteri()
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
References _mesa_texture_parameteri(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
Referenced by pop_texture_group().
_mesa_TexParameterIiv()
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint * params)
Set tex parameter to integer value(s).
Primarily intended to set integer-valued texture border color (for integer-valued textures). New in GL 3.0.
References _mesa_texture_parameterIiv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
_mesa_TexParameterIuiv()
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint * params)
Set tex parameter to unsigned integer value(s).
Primarily intended to set uint-valued texture border color (for integer-valued textures). New in GL 3.0
References _mesa_texture_parameterIuiv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
_mesa_TexParameteriv()
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint * params)
References _mesa_texture_parameteriv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
_mesa_texture_parameterf()
void _mesa_texture_parameterf (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, GLfloat param, bool dsa)
References _mesa_error(), gl_context::Driver, set_tex_parameterf(), set_tex_parameteri(), and dd_function_table::TexParameter.
Referenced by _mesa_TexParameterf(), and _mesa_TextureParameterf().
_mesa_texture_parameterfv()
void _mesa_texture_parameterfv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLfloat * params, bool dsa)
References gl_context::Driver, GL_TEXTURE_CROP_RECT_OES, set_tex_parameterf(), set_tex_parameteri(), and dd_function_table::TexParameter.
Referenced by _mesa_TexParameterfv(), and _mesa_TextureParameterfv().
_mesa_texture_parameteri()
void _mesa_texture_parameteri (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, GLint param, bool dsa)
References _mesa_error(), gl_context::Driver, set_tex_parameterf(), set_tex_parameteri(), and dd_function_table::TexParameter.
Referenced by _mesa_TexParameteri(), and _mesa_TextureParameteri().
_mesa_texture_parameterIiv()
void _mesa_texture_parameterIiv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLint * params, bool dsa)
References _mesa_error(), _mesa_target_allows_setting_sampler_parameters(), _mesa_texture_parameteriv(), _NEW_TEXTURE_OBJECT, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, gl_color_union::i, gl_texture_object::Sampler, and gl_texture_object::Target.
Referenced by _mesa_TexParameterIiv(), and _mesa_TextureParameterIiv().
_mesa_texture_parameterIuiv()
void _mesa_texture_parameterIuiv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLuint * params, bool dsa)
References _mesa_error(), _mesa_target_allows_setting_sampler_parameters(), _mesa_texture_parameteriv(), _NEW_TEXTURE_OBJECT, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, GLAPIENTRY, gl_texture_object::Sampler, gl_texture_object::Target, and gl_color_union::ui.
Referenced by _mesa_TexParameterIuiv(), and _mesa_TextureParameterIuiv().
_mesa_texture_parameteriv()
void _mesa_texture_parameteriv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLint * params, bool dsa)
References _mesa_error(), _mesa_target_allows_setting_sampler_parameters(), gl_context::Driver, INT_TO_FLOAT, set_tex_parameterf(), set_tex_parameteri(), gl_texture_object::Target, and dd_function_table::TexParameter.
Referenced by _mesa_TexParameteriv(), _mesa_texture_parameterIiv(), _mesa_texture_parameterIuiv(), and _mesa_TextureParameteriv().
_mesa_TextureParameterf()
void GLAPIENTRY _mesa_TextureParameterf (GLuint texture, GLenum pname, GLfloat param)
References _mesa_error(), _mesa_texture_parameterf(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameterfv()
void GLAPIENTRY _mesa_TextureParameterfv (GLuint texture, GLenum pname, const GLfloat * params)
References _mesa_error(), _mesa_texture_parameterfv(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameteri()
void GLAPIENTRY _mesa_TextureParameteri (GLuint texture, GLenum pname, GLint param)
References _mesa_error(), _mesa_texture_parameteri(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameterIiv()
void GLAPIENTRY _mesa_TextureParameterIiv (GLuint texture, GLenum pname, const GLint * params)
References _mesa_error(), _mesa_texture_parameterIiv(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameterIuiv()
void GLAPIENTRY _mesa_TextureParameterIuiv (GLuint texture, GLenum pname, const GLuint * params)
References _mesa_error(), _mesa_texture_parameterIuiv(), GET_CURRENT_CONTEXT, and get_texobj_by_name().
_mesa_TextureParameteriv()
void GLAPIENTRY _mesa_TextureParameteriv (GLuint texture, GLenum pname, const GLint * params)
References _mesa_error(), _mesa_texture_parameteriv(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
comp_to_swizzle()
static GLint comp_to_swizzle (GLenum comp) static
Convert GL_RED/GREEN/BLUE/ALPHA/ZERO/ONE to SWIZZLE_X/Y/Z/W/ZERO/ONE.
Returns
-1 if error.
Referenced by set_tex_parameteri().
flush()
static void flush (struct gl_context * ctx) inline static
This is called just prior to changing any texture object state which will not affect texture completeness.
References _NEW_TEXTURE_OBJECT, and FLUSH_VERTICES.
Referenced by set_tex_parameterf(), and set_tex_parameteri().
get_tex_level_parameter_buffer()
static void get_tex_level_parameter_buffer (struct gl_context * ctx, const struct gl_texture_object * texObj, GLenum pname, GLint * params, bool dsa) static
Handle a glGetTexLevelParamteriv() call for a texture buffer.
References gl_texture_object::_BufferObjectFormat, _mesa_base_format_has_channel(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_format_base_format(), _mesa_get_format_bits(), _mesa_get_format_bytes(), _mesa_get_format_datatype(), gl_extensions::ARB_texture_buffer_range, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_multisample, gl_texture_object::BufferObject, gl_texture_object::BufferObjectFormat, gl_texture_object::BufferOffset, gl_texture_object::BufferSize, gl_context::Extensions, if(), gl_buffer_object::Name, gl_buffer_object::Size, and gl_texture_object::Target.
Referenced by get_tex_level_parameteriv().
get_tex_level_parameter_image()
static void get_tex_level_parameter_image (struct gl_context * ctx, const struct gl_texture_object * texObj, GLenum target, GLint level, GLenum pname, GLint * params, bool dsa) static
References gl_texture_image::_BaseFormat, _mesa_base_format_has_channel(), _mesa_compressed_format_to_glenum(), _mesa_enum_to_string(), _mesa_error(), _mesa_format_image_size(), _mesa_get_format_bits(), _mesa_get_format_datatype(), _mesa_gl_compressed_format_base_format(), _mesa_is_format_compressed(), _mesa_is_proxy_texture(), _mesa_select_tex_image(), gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_depth_texture, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_buffer_range, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_multisample, gl_texture_image::Border, gl_texture_image::Depth, gl_extensions::EXT_texture_shared_exponent, gl_context::Extensions, gl_texture_image::FixedSampleLocations, gl_texture_image::Height, gl_texture_image::InternalFormat, MESA_FORMAT_NONE, MESA_FORMAT_R9G9B9E5_FLOAT, gl_texture_image::NumSamples, gl_texture_image::TexFormat, gl_context::Version, and gl_texture_image::Width.
Referenced by get_tex_level_parameteriv().
get_tex_level_parameteriv()
static void get_tex_level_parameteriv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLenum pname, GLint * params, bool dsa) static
This isn't exposed to the rest of the driver because it is a part of the OpenGL API that is rarely used.
References _mesa_error(), _mesa_max_texture_levels(), gl_context::Const, gl_texture_attrib::CurrentUnit, get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), GLAPIENTRY, gl_constants::MaxCombinedTextureImageUnits, and gl_context::Texture.
Referenced by _mesa_GetTexLevelParameterfv(), _mesa_GetTexLevelParameteriv(), _mesa_GetTextureLevelParameterfv(), and _mesa_GetTextureLevelParameteriv().
get_tex_parameterfv()
static void get_tex_parameterfv (struct gl_context * ctx, struct gl_texture_object * obj, GLenum pname, GLfloat * params, bool dsa) static
This isn't exposed to the rest of the driver because it is a part of the OpenGL API that is rarely used.
References _mesa_error(), _mesa_get_clamp_fragment_color(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_is_gles31(), _mesa_lock_context_textures(), _mesa_unlock_context_textures(), _mesa_update_state_locked(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, gl_extensions::AMD_seamless_cubemap_per_texture, gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, gl_extensions::ARB_depth_texture, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shadow, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_view, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_context::DrawBuffer, ENUM_TO_FLOAT, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_context::Extensions, gl_color_union::f, gl_texture_object::GenerateMipmap, GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES, GL_TEXTURE_CROP_RECT_OES, GLuint, if(), gl_texture_object::ImageFormatCompatibilityType, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_texture_object::MinLayer, gl_texture_object::MinLevel, gl_sampler_object::MinLod, gl_context::NewState, gl_texture_object::NumLayers, gl_texture_object::NumLevels, gl_extensions::OES_draw_texture, gl_extensions::OES_EGL_image_external, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, gl_texture_object::Swizzle, gl_texture_object::Target, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_GetTexParameterfv(), and _mesa_GetTextureParameterfv().
get_tex_parameterIiv()
static void get_tex_parameterIiv (struct gl_context * ctx, struct gl_texture_object * obj, GLenum pname, GLint * params, bool dsa) static
References gl_sampler_object::BorderColor, COPY_4V, get_tex_parameteriv(), gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_GetTexParameterIiv(), and _mesa_GetTextureParameterIiv().
get_tex_parameterIuiv()
static void get_tex_parameterIuiv (struct gl_context * ctx, struct gl_texture_object * obj, GLenum pname, GLuint * params, bool dsa) static
References gl_sampler_object::BorderColor, COPY_4V, get_tex_parameteriv(), GL_TEXTURE_CROP_RECT_OES, GLAPIENTRY, gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_GetTexParameterIuiv(), and _mesa_GetTextureParameterIuiv().
get_tex_parameteriv()
static void get_tex_parameteriv (struct gl_context * ctx, struct gl_texture_object * obj, GLenum pname, GLint * params, bool dsa) static
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_is_gles31(), _mesa_lock_texture(), _mesa_unlock_texture(), gl_extensions::AMD_seamless_cubemap_per_texture, gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, gl_extensions::ARB_depth_texture, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shadow, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_view, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, COPY_4V, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_context::Extensions, gl_color_union::f, FLOAT_TO_INT, gl_texture_object::GenerateMipmap, GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES, GL_TEXTURE_CROP_RECT_OES, if(), gl_texture_object::ImageFormatCompatibilityType, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, IROUND(), gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_texture_object::MinLayer, gl_texture_object::MinLevel, gl_sampler_object::MinLod, gl_texture_object::NumLayers, gl_texture_object::NumLevels, gl_extensions::OES_draw_texture, gl_extensions::OES_EGL_image_external, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, gl_texture_object::Swizzle, gl_texture_object::Target, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_GetTexParameteriv(), _mesa_GetTextureParameteriv(), get_tex_parameterIiv(), and get_tex_parameterIuiv().
get_texobj_by_name()
static struct gl_texture_object* get_texobj_by_name (struct gl_context * ctx, GLuint texture, GLboolean get) static
Get current texture object for given name.
Return NULL if any error (and record the error). Note that proxy targets are not accepted. Only the glGetTexLevelParameter() functions accept proxy targets.
References _mesa_error(), _mesa_lookup_texture(), and gl_texture_object::Target.
Referenced by _mesa_GetTextureParameterfv(), _mesa_GetTextureParameterIiv(), _mesa_GetTextureParameterIuiv(), _mesa_GetTextureParameteriv(), _mesa_TextureParameterf(), _mesa_TextureParameterfv(), _mesa_TextureParameteri(), _mesa_TextureParameterIiv(), _mesa_TextureParameterIuiv(), and _mesa_TextureParameteriv().
get_texobj_by_target()
static struct gl_texture_object* get_texobj_by_target (struct gl_context * ctx, GLenum target, GLboolean get) static
Get current texture object for given target.
Return NULL if any error (and record the error). Note that this is different from _mesa_get_current_tex_object() in that proxy targets are not accepted. Only the glGetTexLevelParameter() functions accept proxy targets.
References _mesa_error(), _mesa_get_current_tex_unit(), _mesa_tex_target_to_index(), gl_context::Const, gl_texture_unit::CurrentTex, gl_texture_attrib::CurrentUnit, gl_constants::MaxCombinedTextureImageUnits, NUM_TEXTURE_TARGETS, gl_context::Texture, and TEXTURE_BUFFER_INDEX.
Referenced by _mesa_GetTexParameterfv(), _mesa_GetTexParameterIiv(), _mesa_GetTexParameterIuiv(), _mesa_GetTexParameteriv(), _mesa_TexParameterf(), _mesa_TexParameterfv(), _mesa_TexParameteri(), _mesa_TexParameterIiv(), _mesa_TexParameterIuiv(), and _mesa_TexParameteriv().
incomplete()
static void incomplete (struct gl_context * ctx, struct gl_texture_object * texObj) inline static
This is called just prior to changing any texture object state which could affect texture completeness (texture base level, max level).
Any pending rendering will be flushed out, we'll set the _NEW_TEXTURE_OBJECT state flag and then mark the texture object as 'incomplete' so that any per-texture derived state gets recomputed.
References _mesa_dirty_texobj(), _NEW_TEXTURE_OBJECT, and FLUSH_VERTICES.
Referenced by set_tex_parameteri().
set_swizzle_component()
static void set_swizzle_component (GLuint * swizzle, GLuint comp, GLuint swz) static
References GLuint.
Referenced by set_tex_parameteri().
set_tex_parameterf()
static GLboolean set_tex_parameterf (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLfloat * params, bool dsa) static
Set a float-valued texture parameter.
Returns
GL_TRUE if legal AND the value changed, GL_FALSE otherwise
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_target_allows_setting_sampler_parameters(), ACOMP, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_float, BCOMP, gl_sampler_object::BorderColor, gl_context::Const, gl_extensions::EXT_texture_filter_anisotropic, gl_context::Extensions, F, gl_color_union::f, flush(), GCOMP, GLuint, gl_sampler_object::LodBias, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_constants::MaxTextureMaxAnisotropy, gl_sampler_object::MinLod, gl_texture_object::Priority, RCOMP, gl_texture_object::Sampler, and gl_texture_object::Target.
Referenced by _mesa_texture_parameterf(), _mesa_texture_parameterfv(), _mesa_texture_parameteri(), and _mesa_texture_parameteriv().
set_tex_parameteri()
static GLboolean set_tex_parameteri (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLint * params, bool dsa) static
Set an integer-valued texture parameter.
Returns
GL_TRUE if legal AND the value changed, GL_FALSE otherwise
See note about ARB_texture_storage below
From ARB_texture_storage: However, if TEXTURE_IMMUTABLE_FORMAT is TRUE, then level_base is clamped to the range [0, <levels> - 1] and level_max is then clamped to the range [level_base, <levels> - 1], where <levels> is the parameter passed the call to TexStorage* for the texture object.
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_gles31(), _mesa_target_allows_setting_sampler_parameters(), gl_texture_object::_Swizzle, gl_extensions::AMD_seamless_cubemap_per_texture, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_depth_texture, gl_extensions::ARB_shadow, gl_extensions::ARB_texture_rg, gl_texture_object::BaseLevel, comp_to_swizzle(), gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_context::Extensions, flush(), gl_texture_object::GenerateMipmap, GL_TEXTURE_CROP_RECT_OES, GL_TEXTURE_EXTERNAL_OES, GLuint, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, incomplete(), gl_sampler_object::MagFilter, gl_texture_object::MaxLevel, gl_sampler_object::MinFilter, gl_extensions::OES_draw_texture, gl_texture_object::Sampler, set_swizzle_component(), gl_sampler_object::sRGBDecode, gl_texture_object::StencilSampling, gl_texture_object::Swizzle, gl_texture_object::Target, validate_texture_wrap_mode(), gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_texture_parameterf(), _mesa_texture_parameterfv(), _mesa_texture_parameteri(), and _mesa_texture_parameteriv().
valid_tex_level_parameteriv_target()
static bool valid_tex_level_parameteriv_target (struct gl_context * ctx, GLenum target, bool dsa) static
References _mesa_enum_to_string(), _mesa_error(), and _mesa_legal_get_tex_level_parameter_target().
Referenced by _mesa_GetTexLevelParameterfv(), _mesa_GetTexLevelParameteriv(), _mesa_GetTextureLevelParameterfv(), and _mesa_GetTextureLevelParameteriv().
validate_texture_wrap_mode()
static GLboolean validate_texture_wrap_mode (struct gl_context * ctx, GLenum target, GLenum wrap) static
Check if a coordinate wrap mode is supported for the texture target.
Returns
GL_TRUE if legal, GL_FALSE otherwise
References _mesa_error(), _mesa_is_desktop_gl(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_texture_mirror_clamp, gl_context::Extensions, and GL_TEXTURE_EXTERNAL_OES.
Referenced by set_tex_parameteri().