Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texparam.h File Reference
#include "main/glheader.h"
Functions
Internal functions
void _mesa_texture_parameterf (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, GLfloat param, bool dsa)
void _mesa_texture_parameterfv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLfloat *params, bool dsa)
void _mesa_texture_parameteri (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, GLint param, bool dsa)
void _mesa_texture_parameteriv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLint *params, bool dsa)
void _mesa_texture_parameterIiv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLint *params, bool dsa)
void _mesa_texture_parameterIuiv (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLuint *params, bool dsa)
GLboolean _mesa_legal_get_tex_level_parameter_target (struct gl_context *ctx, GLenum target, bool dsa)
GLboolean _mesa_target_allows_setting_sampler_parameters (GLenum target)
API functions
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTextureLevelParameterfv (GLuint texture, GLint level, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTextureLevelParameteriv (GLuint texture, GLint level, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_GetTextureParameterfv (GLuint texture, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTextureParameteriv (GLuint texture, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTextureParameterIiv (GLuint texture, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTextureParameterIuiv (GLuint texture, GLenum pname, GLuint *params)
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint *params)
Set tex parameter to integer value(s).
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint *params)
Set tex parameter to unsigned integer value(s).
void GLAPIENTRY _mesa_TextureParameterfv (GLuint texture, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TextureParameterf (GLuint texture, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TextureParameteri (GLuint texture, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TextureParameteriv (GLuint texture, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TextureParameterIiv (GLuint texture, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TextureParameterIuiv (GLuint texture, GLenum pname, const GLuint *params)
Function Documentation
_mesa_GetTexLevelParameterfv()
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat * params)
References _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), GLAPIENTRY, and valid_tex_level_parameteriv_target().
_mesa_GetTexLevelParameteriv()
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint * params)
References _mesa_get_current_tex_object(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), GLAPIENTRY, and valid_tex_level_parameteriv_target().
_mesa_GetTexParameterfv()
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
References GET_CURRENT_CONTEXT, get_tex_parameterfv(), get_texobj_by_target(), and GLAPIENTRY.
Referenced by _mesa_GetTexParameterxv().
_mesa_GetTexParameterIiv()
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint * params)
New in GL 3.0.
References GET_CURRENT_CONTEXT, get_tex_parameterIiv(), get_texobj_by_target(), and GLAPIENTRY.
_mesa_GetTexParameterIuiv()
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint * params)
New in GL 3.0.
References GET_CURRENT_CONTEXT, get_tex_parameterIuiv(), get_texobj_by_target(), and GLAPIENTRY.
_mesa_GetTexParameteriv()
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint * params)
References GET_CURRENT_CONTEXT, get_tex_parameteriv(), get_texobj_by_target(), and GLAPIENTRY.
_mesa_GetTextureLevelParameterfv()
void GLAPIENTRY _mesa_GetTextureLevelParameterfv (GLuint texture, GLint level, GLenum pname, GLfloat * params)
References _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), GLAPIENTRY, gl_texture_object::Target, and valid_tex_level_parameteriv_target().
_mesa_GetTextureLevelParameteriv()
void GLAPIENTRY _mesa_GetTextureLevelParameteriv (GLuint texture, GLint level, GLenum pname, GLint * params)
References _mesa_lookup_texture_err(), GET_CURRENT_CONTEXT, get_tex_level_parameteriv(), gl_texture_object::Target, and valid_tex_level_parameteriv_target().
_mesa_GetTextureParameterfv()
void GLAPIENTRY _mesa_GetTextureParameterfv (GLuint texture, GLenum pname, GLfloat * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameterfv(), get_texobj_by_name(), and GLAPIENTRY.
_mesa_GetTextureParameterIiv()
void GLAPIENTRY _mesa_GetTextureParameterIiv (GLuint texture, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameterIiv(), get_texobj_by_name(), and GLAPIENTRY.
_mesa_GetTextureParameterIuiv()
void GLAPIENTRY _mesa_GetTextureParameterIuiv (GLuint texture, GLenum pname, GLuint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameterIuiv(), and get_texobj_by_name().
_mesa_GetTextureParameteriv()
void GLAPIENTRY _mesa_GetTextureParameteriv (GLuint texture, GLenum pname, GLint * params)
References _mesa_error(), GET_CURRENT_CONTEXT, get_tex_parameteriv(), get_texobj_by_name(), and GLAPIENTRY.
_mesa_legal_get_tex_level_parameter_target()
GLboolean _mesa_legal_get_tex_level_parameter_target (struct gl_context * ctx, GLenum target, bool dsa)
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_multisample, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::NV_texture_rectangle, and gl_context::Version.
Referenced by _mesa_GetInternalformativ(), and valid_tex_level_parameteriv_target().
_mesa_target_allows_setting_sampler_parameters()
GLboolean _mesa_target_allows_setting_sampler_parameters (GLenum target)
Referenced by _mesa_GetInternalformativ(), _mesa_texture_parameterIiv(), _mesa_texture_parameterIuiv(), _mesa_texture_parameteriv(), set_tex_parameterf(), and set_tex_parameteri().
_mesa_TexParameterf()
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
References _mesa_texture_parameterf(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
Referenced by _mesa_TexParameterx(), and pop_texture_group().
_mesa_TexParameterfv()
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References _mesa_texture_parameterfv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
Referenced by _mesa_TexParameterxv(), and pop_texture_group().
_mesa_TexParameteri()
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
References _mesa_texture_parameteri(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
Referenced by pop_texture_group().
_mesa_TexParameterIiv()
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint * params)
Set tex parameter to integer value(s).
Primarily intended to set integer-valued texture border color (for integer-valued textures). New in GL 3.0.
References _mesa_texture_parameterIiv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
_mesa_TexParameterIuiv()
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint * params)
Set tex parameter to unsigned integer value(s).
Primarily intended to set uint-valued texture border color (for integer-valued textures). New in GL 3.0
References _mesa_texture_parameterIuiv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
_mesa_TexParameteriv()
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint * params)
References _mesa_texture_parameteriv(), GET_CURRENT_CONTEXT, get_texobj_by_target(), and GLAPIENTRY.
_mesa_texture_parameterf()
void _mesa_texture_parameterf (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, GLfloat param, bool dsa)
References _mesa_error(), gl_context::Driver, set_tex_parameterf(), set_tex_parameteri(), and dd_function_table::TexParameter.
Referenced by _mesa_TexParameterf(), and _mesa_TextureParameterf().
_mesa_texture_parameterfv()
void _mesa_texture_parameterfv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLfloat * params, bool dsa)
References gl_context::Driver, GL_TEXTURE_CROP_RECT_OES, set_tex_parameterf(), set_tex_parameteri(), and dd_function_table::TexParameter.
Referenced by _mesa_TexParameterfv(), and _mesa_TextureParameterfv().
_mesa_texture_parameteri()
void _mesa_texture_parameteri (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, GLint param, bool dsa)
References _mesa_error(), gl_context::Driver, set_tex_parameterf(), set_tex_parameteri(), and dd_function_table::TexParameter.
Referenced by _mesa_TexParameteri(), and _mesa_TextureParameteri().
_mesa_texture_parameterIiv()
void _mesa_texture_parameterIiv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLint * params, bool dsa)
References _mesa_error(), _mesa_target_allows_setting_sampler_parameters(), _mesa_texture_parameteriv(), _NEW_TEXTURE_OBJECT, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, gl_color_union::i, gl_texture_object::Sampler, and gl_texture_object::Target.
Referenced by _mesa_TexParameterIiv(), and _mesa_TextureParameterIiv().
_mesa_texture_parameterIuiv()
void _mesa_texture_parameterIuiv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLuint * params, bool dsa)
References _mesa_error(), _mesa_target_allows_setting_sampler_parameters(), _mesa_texture_parameteriv(), _NEW_TEXTURE_OBJECT, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, GLAPIENTRY, gl_texture_object::Sampler, gl_texture_object::Target, and gl_color_union::ui.
Referenced by _mesa_TexParameterIuiv(), and _mesa_TextureParameterIuiv().
_mesa_texture_parameteriv()
void _mesa_texture_parameteriv (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLint * params, bool dsa)
References _mesa_error(), _mesa_target_allows_setting_sampler_parameters(), gl_context::Driver, INT_TO_FLOAT, set_tex_parameterf(), set_tex_parameteri(), gl_texture_object::Target, and dd_function_table::TexParameter.
Referenced by _mesa_TexParameteriv(), _mesa_texture_parameterIiv(), _mesa_texture_parameterIuiv(), and _mesa_TextureParameteriv().
_mesa_TextureParameterf()
void GLAPIENTRY _mesa_TextureParameterf (GLuint texture, GLenum pname, GLfloat param)
References _mesa_error(), _mesa_texture_parameterf(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameterfv()
void GLAPIENTRY _mesa_TextureParameterfv (GLuint texture, GLenum pname, const GLfloat * params)
References _mesa_error(), _mesa_texture_parameterfv(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameteri()
void GLAPIENTRY _mesa_TextureParameteri (GLuint texture, GLenum pname, GLint param)
References _mesa_error(), _mesa_texture_parameteri(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameterIiv()
void GLAPIENTRY _mesa_TextureParameterIiv (GLuint texture, GLenum pname, const GLint * params)
References _mesa_error(), _mesa_texture_parameterIiv(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.
_mesa_TextureParameterIuiv()
void GLAPIENTRY _mesa_TextureParameterIuiv (GLuint texture, GLenum pname, const GLuint * params)
References _mesa_error(), _mesa_texture_parameterIuiv(), GET_CURRENT_CONTEXT, and get_texobj_by_name().
_mesa_TextureParameteriv()
void GLAPIENTRY _mesa_TextureParameteriv (GLuint texture, GLenum pname, const GLint * params)
References _mesa_error(), _mesa_texture_parameteriv(), GET_CURRENT_CONTEXT, get_texobj_by_name(), and GLAPIENTRY.