Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texstate.c File Reference
Texture state handling.
#include <stdio.h>
#include "glheader.h"
#include "bufferobj.h"
#include "context.h"
#include "enums.h"
#include "macros.h"
#include "texobj.h"
#include "teximage.h"
#include "texstate.h"
#include "mtypes.h"
#include "util/bitscan.h"
#include "util/bitset.h"
Functions
void _mesa_copy_texture_state (const struct gl_context *src, struct gl_context *dst)
Used by glXCopyContext to copy texture state from one context to another.
void _mesa_print_texunit_state (struct gl_context *ctx, GLuint unit)
static void calculate_derived_texenv (struct gl_tex_env_combine_state *state, GLenum mode, GLenum texBaseFormat)
Convert "classic" texture environment to ARB_texture_env_combine style environments.
void GLAPIENTRY _mesa_ActiveTexture (GLenum texture)
void GLAPIENTRY _mesa_ClientActiveTexture (GLenum texture)
void _mesa_update_texture_matrices (struct gl_context *ctx)
static void update_tex_combine (struct gl_context *ctx, struct gl_texture_unit *texUnit)
Examine texture unit's combine/env state to update derived state.
static void update_texgen (struct gl_context *ctx)
static struct gl_texture_object * update_single_program_texture (struct gl_context *ctx, struct gl_program *prog, int s)
static void update_program_texture_state (struct gl_context *ctx, struct gl_program **prog, BITSET_WORD *enabled_texture_units)
static void update_ff_texture_state (struct gl_context *ctx, BITSET_WORD *enabled_texture_units)
void _mesa_update_texture_state (struct gl_context *ctx)
static GLboolean alloc_proxy_textures (struct gl_context *ctx)
Allocate the proxy textures for the given context.
static void init_texture_unit (struct gl_context *ctx, GLuint unit)
Initialize a texture unit.
GLboolean _mesa_init_texture (struct gl_context *ctx)
Initialize texture state for the given context.
void _mesa_free_texture_data (struct gl_context *ctx)
Free dynamically-allocted texture data attached to the given context.
void _mesa_update_default_objects_texture (struct gl_context *ctx)
Update the default texture objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
Variables
static const struct gl_tex_env_combine_state default_combine_state
Default texture combine environment state.
Detailed Description
Texture state handling.
Function Documentation
_mesa_ActiveTexture()
void GLAPIENTRY _mesa_ActiveTexture (GLenum texture)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_max_tex_unit(), _NEW_TEXTURE_STATE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_max_tex_unit(), pop_enable_group(), and pop_texture_group().
_mesa_ClientActiveTexture()
void GLAPIENTRY _mesa_ClientActiveTexture (GLenum texture)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_max_tex_unit().
_mesa_copy_texture_state()
void _mesa_copy_texture_state (const struct gl_context * src, struct gl_context * dst)
Used by glXCopyContext to copy texture state from one context to another.
References gl_texture_unit::_BoundTextures, gl_texture_attrib::_GenFlags, _mesa_lock_context_textures(), _mesa_reference_texobj(), _mesa_unlock_context_textures(), gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_texture_unit::Combine, gl_context::Const, COPY_4V, gl_texture_unit::CurrentTex, gl_texture_attrib::CurrentUnit, gl_texture_unit::Enabled, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GLuint, gl_texture_unit::LodBias, gl_constants::MaxCombinedTextureImageUnits, NUM_TEXTURE_TARGETS, gl_texture_attrib::NumCurrentTexUsed, gl_context::Shared, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_copy_context(), and _mesa_max_tex_unit().
_mesa_free_texture_data()
void _mesa_free_texture_data (struct gl_context * ctx)
Free dynamically-allocted texture data attached to the given context.
References gl_texture_unit::_Current, _mesa_reference_buffer_object(), _mesa_reference_sampler_object(), _mesa_reference_texobj(), gl_texture_attrib::BufferObject, gl_texture_unit::CurrentTex, dd_function_table::DeleteTexture, gl_context::Driver, GLuint, NUM_TEXTURE_TARGETS, gl_texture_attrib::ProxyTex, gl_texture_unit::Sampler, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_free_context_data(), and _mesa_max_tex_unit().
_mesa_init_texture()
GLboolean _mesa_init_texture (struct gl_context * ctx)
Initialize texture state for the given context.
References _mesa_reference_buffer_object(), alloc_proxy_textures(), gl_context::API, API_OPENGLES2, gl_texture_attrib::BufferObject, gl_texture_attrib::CubeMapSeamless, gl_texture_attrib::CurrentUnit, gl_shared_state::DefaultTex, GLuint, init_texture_unit(), MAX_COMBINED_TEXTURE_IMAGE_UNITS, gl_shared_state::NullBufferObj, gl_texture_attrib::NumCurrentTexUsed, gl_texture_object::RefCount, gl_context::Shared, gl_context::Texture, TEXTURE_1D_INDEX, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit(), and init_attrib_groups().
_mesa_print_texunit_state()
void _mesa_print_texunit_state (struct gl_context * ctx, GLuint unit)
References _mesa_enum_to_string(), gl_texture_unit::Combine, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit().
_mesa_update_default_objects_texture()
void _mesa_update_default_objects_texture (struct gl_context * ctx)
Update the default texture objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
References _mesa_reference_texobj(), gl_texture_unit::CurrentTex, gl_shared_state::DefaultTex, GLuint, NUM_TEXTURE_TARGETS, gl_context::Shared, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit(), and update_default_objects().
_mesa_update_texture_matrices()
void _mesa_update_texture_matrices (struct gl_context * ctx)
Note
This routine refers to derived texture attribute values to compute the ENABLE_TEXMAT flags, but is only called on _NEW_TEXTURE_MATRIX. On changes to _NEW_TEXTURE_OBJECT/STATE, the ENABLE_TEXMAT flags are updated by _mesa_update_textures(), below.
Parameters
ctx GL context.
References gl_texture_unit::_Current, _math_matrix_analyse(), _math_matrix_is_dirty(), gl_texture_attrib::_TexMatEnabled, gl_context::Const, ENABLE_TEXMAT, GLuint, MATRIX_IDENTITY, gl_constants::MaxTextureCoordUnits, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, GLmatrix::type, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit(), and _mesa_update_state_locked().
_mesa_update_texture_state()
void _mesa_update_texture_state (struct gl_context * ctx)
Note
This routine refers to derived texture matrix values to compute the ENABLE_TEXMAT flags, but is only called on _NEW_TEXTURE_OBJECT/STATE. On changes to _NEW_TEXTURE_MATRIX, the ENABLE_TEXMAT flags are updated by _mesa_update_texture_matrices, above.
Parameters
ctx GL context.
References gl_texture_unit::_Current, gl_fragment_program_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, gl_texture_attrib::_GenFlags, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_reference_texobj(), _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, gl_context::_Shader, gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_fragment_program_state::Current, gl_pipeline_object::CurrentProgram, gl_context::FragmentProgram, MAX_COMBINED_TEXTURE_IMAGE_UNITS, gl_context::NewState, gl_context::Texture, gl_texture_attrib::Unit, update_ff_texture_state(), update_program_texture_state(), and update_texgen().
Referenced by _mesa_max_tex_unit(), and _mesa_update_state_locked().
alloc_proxy_textures()
static GLboolean alloc_proxy_textures (struct gl_context * ctx) static
Allocate the proxy textures for the given context.
Parameters
ctx the context to allocate proxies for.
Returns
GL_TRUE on success, or GL_FALSE on failure
If run out of memory part way through the allocations, clean up and return GL_FALSE.
References dd_function_table::DeleteTexture, gl_context::Driver, GL_TEXTURE_EXTERNAL_OES, dd_function_table::NewTextureObject, NUM_TEXTURE_TARGETS, gl_texture_attrib::ProxyTex, gl_texture_object::RefCount, gl_context::Texture, TEXTURE_2D_INDEX, and TEXTURE_CUBE_INDEX.
Referenced by _mesa_init_texture().
calculate_derived_texenv()
static void calculate_derived_texenv (struct gl_tex_env_combine_state * state, GLenum mode, GLenum texBaseFormat) static
Convert "classic" texture environment to ARB_texture_env_combine style environments.
Parameters
state texture_env_combine state vector to be filled-in.
mode Classic texture environment mode (i.e., GL_REPLACE, GL_BLEND, GL_DECAL, etc.).
texBaseFormat Base format of the texture associated with the texture unit.
References _mesa_problem(), default_combine_state, GLAPIENTRY, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_tex_env_combine_state::SourceA, and gl_tex_env_combine_state::SourceRGB.
Referenced by update_tex_combine().
init_texture_unit()
static void init_texture_unit (struct gl_context * ctx, GLuint unit) static
Initialize a texture unit.
Parameters
ctx GL context.
unit texture unit number to be initialized.
References gl_texture_unit::_BoundTextures, gl_texture_unit::_CurrentCombine, gl_texture_unit::_EnvMode, _mesa_reference_texobj(), gl_texgen::_ModeBit, gl_texture_unit::Combine, gl_texture_unit::CurrentTex, default_combine_state, gl_shared_state::DefaultTex, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_texgen::EyePlane, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GLuint, gl_texgen::Mode, NUM_TEXTURE_TARGETS, gl_texgen::ObjectPlane, gl_context::Shared, TEXGEN_EYE_LINEAR, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_init_texture().
update_ff_texture_state()
static void update_ff_texture_state (struct gl_context * ctx, BITSET_WORD * enabled_texture_units) static
References gl_texture_unit::_Current, gl_texture_attrib::_EnabledCoordUnits, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_is_texture_complete(), _mesa_reference_texobj(), _mesa_test_texobj_completeness(), gl_context::Const, gl_texture_unit::CurrentTex, gl_texture_unit::Enabled, gl_constants::MaxTextureUnits, gl_texture_object::Sampler, gl_texture_unit::Sampler, gl_context::Texture, gl_texture_attrib::Unit, and update_tex_combine().
Referenced by _mesa_update_texture_state().
update_program_texture_state()
static void update_program_texture_state (struct gl_context * ctx, struct gl_program ** prog, BITSET_WORD * enabled_texture_units) static
References gl_texture_unit::_Current, gl_texture_attrib::_EnabledCoordUnits, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_reference_texobj(), GLuint, gl_program::info, MAX_SAMPLERS, MAX_TEXTURE_COORD_UNITS, gl_program::SamplerUnits, gl_context::Texture, gl_texture_attrib::Unit, and update_single_program_texture().
Referenced by _mesa_update_texture_state().
update_single_program_texture()
static struct gl_texture_object* update_single_program_texture (struct gl_context * ctx, struct gl_program * prog, int s) static
References _mesa_get_fallback_texture(), _mesa_is_texture_complete(), _mesa_test_texobj_completeness(), gl_texture_unit::CurrentTex, gl_texture_object::Sampler, gl_texture_unit::Sampler, gl_program::SamplersUsed, gl_program::SamplerUnits, gl_context::Texture, gl_program::TexturesUsed, and gl_texture_attrib::Unit.
Referenced by update_program_texture_state().
update_tex_combine()
static void update_tex_combine (struct gl_context * ctx, struct gl_texture_unit * texUnit) static
Examine texture unit's combine/env state to update derived state.
References gl_texture_image::_BaseFormat, gl_texture_unit::_Current, gl_texture_unit::_CurrentCombine, gl_texture_unit::_EnvMode, _mesa_problem(), gl_tex_env_combine_state::_NumArgsA, gl_tex_env_combine_state::_NumArgsRGB, gl_texture_object::BaseLevel, calculate_derived_texenv(), gl_texture_unit::Combine, gl_texture_object::DepthMode, gl_texture_unit::EnvMode, gl_texture_object::Image, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, and gl_texture_object::Target.
Referenced by update_ff_texture_state().
update_texgen()
static void update_texgen (struct gl_context * ctx) static
References gl_texture_attrib::_EnabledCoordUnits, gl_texture_unit::_GenFlags, gl_texture_attrib::_GenFlags, gl_texgen::_ModeBit, gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_context::Const, ENABLE_TEXGEN, ENABLE_TEXMAT, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GLuint, MATRIX_IDENTITY, gl_constants::MaxTextureCoordUnits, Q_BIT, R_BIT, S_BIT, T_BIT, gl_texture_unit::TexGenEnabled, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, GLmatrix::type, and gl_texture_attrib::Unit.
Referenced by _mesa_update_texture_state().
Variable Documentation
default_combine_state
const struct gl_tex_env_combine_state default_combine_state static
Initial value:
= {
   GL_MODULATE, GL_MODULATE,
   { GL_TEXTURE, GL_PREVIOUS, GL_CONSTANT, GL_CONSTANT },
   { GL_TEXTURE, GL_PREVIOUS, GL_CONSTANT, GL_CONSTANT },
   { GL_SRC_COLOR, GL_SRC_COLOR, GL_SRC_ALPHA, GL_SRC_ALPHA },
   { GL_SRC_ALPHA, GL_SRC_ALPHA, GL_SRC_ALPHA, GL_SRC_ALPHA },
   0, 0,
   2, 2
}
Default texture combine environment state.
This is used to initialize a context's texture units and as the basis for converting "classic" texture environmnets to ARB_texture_env_combine style values.
Referenced by calculate_derived_texenv(), and init_texture_unit().