Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texstorage.h File Reference
Functions
Internal functions
void _mesa_texture_storage (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, bool dsa)
Helper that does the storage allocation for _mesa_TexStorage1/2/3D() and _mesa_TextureStorage1/2/3D().
static bool _mesa_valid_tex_storage_dim (GLsizei width, GLsizei height, GLsizei depth)
Texture width, height and depth check shared with the multisample variants of TexStorage functions.
API functions
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_TextureStorage1D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TextureStorage2D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TextureStorage3D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
GLboolean _mesa_is_legal_tex_storage_format (const struct gl_context *ctx, GLenum internalformat)
GLboolean _mesa_AllocTextureStorage_sw (struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
Function Documentation
_mesa_AllocTextureStorage_sw()
GLboolean _mesa_AllocTextureStorage_sw (struct gl_context * ctx, struct gl_texture_object * texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
The driver can override this with a more specific implementation if it desires, but this can be used to get the texture images allocated using the usual texture image handling code. The immutability of GL_ARB_texture_storage texture layouts is handled by texObj->Immutable checks at glTexImage* time.
References _mesa_num_tex_faces(), dd_function_table::AllocTextureImageBuffer, gl_context::Driver, gl_texture_object::Image, gl_texture_object::Target, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_is_legal_tex_storage_format()
GLboolean _mesa_is_legal_tex_storage_format (const struct gl_context * ctx, GLenum internalformat)
References _mesa_base_tex_format().
Referenced by _mesa_valid_tex_storage_dim(), texstorage(), texture_image_multisample(), and texturestorage().
_mesa_TexStorage1D()
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
References GLAPIENTRY, and texstorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TexStorage2D()
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, and texstorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TexStorage3D()
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References GLAPIENTRY, and texstorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_texture_storage()
void _mesa_texture_storage (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, bool dsa)
Helper that does the storage allocation for _mesa_TexStorage1/2/3D() and _mesa_TextureStorage1/2/3D().
References _mesa_choose_texture_format(), _mesa_error(), _mesa_is_proxy_texture(), _mesa_legal_texture_dimensions(), _mesa_set_texture_view_state(), dd_function_table::AllocTextureStorage, clear_texture_fields(), gl_context::Driver, initialize_texture_fields(), MESA_FORMAT_NONE, dd_function_table::TestProxyTexImage, tex_storage_error_check(), and update_fbo_texture().
Referenced by texstorage(), and texturestorage().
_mesa_TextureStorage1D()
void GLAPIENTRY _mesa_TextureStorage1D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width)
References GLAPIENTRY, and texturestorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage1DEXT()
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage2D()
void GLAPIENTRY _mesa_TextureStorage2D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, and texturestorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage2DEXT()
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage3D()
void GLAPIENTRY _mesa_TextureStorage3D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References GLAPIENTRY, and texturestorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage3DEXT()
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References _mesa_error(), GET_CURRENT_CONTEXT, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_valid_tex_storage_dim()
static bool _mesa_valid_tex_storage_dim (GLsizei width, GLsizei height, GLsizei depth) inline static
Texture width, height and depth check shared with the multisample variants of TexStorage functions.
From OpenGL 4.5 Core spec, page 260 (section 8.19)
"An INVALID_VALUE error is generated if width, height, depth
or levels are less than 1, for commands with the corresponding
parameters."
(referring to TextureStorage* commands, these also match values specified for OpenGL ES 3.1.)
References _mesa_AllocTextureStorage_sw(), _mesa_is_legal_tex_storage_format(), _mesa_TexStorage1D(), _mesa_TexStorage2D(), _mesa_TexStorage3D(), _mesa_TextureStorage1D(), _mesa_TextureStorage1DEXT(), _mesa_TextureStorage2D(), _mesa_TextureStorage2DEXT(), _mesa_TextureStorage3D(), _mesa_TextureStorage3DEXT(), GLAPIENTRY, and GLuint.
Referenced by tex_storage_error_check(), and valid_texstorage_ms_parameters().