Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texstorage.c File Reference
GL_ARB_texture_storage functions.
#include "glheader.h"
#include "context.h"
#include "enums.h"
#include "imports.h"
#include "macros.h"
#include "teximage.h"
#include "texobj.h"
#include "mipmap.h"
#include "texstorage.h"
#include "textureview.h"
#include "mtypes.h"
#include "glformats.h"
#include "hash.h"
Functions
static bool legal_texobj_target (const struct gl_context *ctx, GLuint dims, GLenum target)
Check if the given texture target is a legal texture object target for a glTexStorage() command.
static struct gl_texture_image * get_tex_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
Helper to get a particular texture image in a texture object.
static GLboolean initialize_texture_fields (struct gl_context *ctx, struct gl_texture_object *texObj, GLint levels, GLsizei width, GLsizei height, GLsizei depth, GLenum internalFormat, mesa_format texFormat)
static void clear_texture_fields (struct gl_context *ctx, struct gl_texture_object *texObj)
Clear all fields of texture object to zeros.
static void update_fbo_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
Update/re-validate framebuffer object.
GLboolean _mesa_is_legal_tex_storage_format (const struct gl_context *ctx, GLenum internalformat)
GLboolean _mesa_AllocTextureStorage_sw (struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
static GLboolean tex_storage_error_check (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, bool dsa)
Do error checking for calls to glTexStorage1/2/3D().
void _mesa_texture_storage (struct gl_context *ctx, GLuint dims, struct gl_texture_object *texObj, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, bool dsa)
Helper that does the storage allocation for _mesa_TexStorage1/2/3D() and _mesa_TextureStorage1/2/3D().
static void texstorage (GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Helper used by _mesa_TexStorage1/2/3D().
static void texturestorage (GLuint dims, GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Helper used by _mesa_TextureStorage1/2/3D().
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_TextureStorage1D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TextureStorage2D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TextureStorage3D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Detailed Description
GL_ARB_texture_storage functions.
Function Documentation
_mesa_AllocTextureStorage_sw()
GLboolean _mesa_AllocTextureStorage_sw (struct gl_context * ctx, struct gl_texture_object * texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
The driver can override this with a more specific implementation if it desires, but this can be used to get the texture images allocated using the usual texture image handling code. The immutability of GL_ARB_texture_storage texture layouts is handled by texObj->Immutable checks at glTexImage* time.
References _mesa_num_tex_faces(), dd_function_table::AllocTextureImageBuffer, gl_context::Driver, gl_texture_object::Image, gl_texture_object::Target, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_is_legal_tex_storage_format()
GLboolean _mesa_is_legal_tex_storage_format (const struct gl_context * ctx, GLenum internalformat)
References _mesa_base_tex_format().
Referenced by _mesa_valid_tex_storage_dim(), texstorage(), texture_image_multisample(), and texturestorage().
_mesa_TexStorage1D()
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
References GLAPIENTRY, and texstorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TexStorage2D()
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, and texstorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TexStorage3D()
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References GLAPIENTRY, and texstorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_texture_storage()
void _mesa_texture_storage (struct gl_context * ctx, GLuint dims, struct gl_texture_object * texObj, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, bool dsa)
Helper that does the storage allocation for _mesa_TexStorage1/2/3D() and _mesa_TextureStorage1/2/3D().
References _mesa_choose_texture_format(), _mesa_error(), _mesa_is_proxy_texture(), _mesa_legal_texture_dimensions(), _mesa_set_texture_view_state(), dd_function_table::AllocTextureStorage, clear_texture_fields(), gl_context::Driver, initialize_texture_fields(), MESA_FORMAT_NONE, dd_function_table::TestProxyTexImage, tex_storage_error_check(), and update_fbo_texture().
Referenced by texstorage(), and texturestorage().
_mesa_TextureStorage1D()
void GLAPIENTRY _mesa_TextureStorage1D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width)
References GLAPIENTRY, and texturestorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage1DEXT()
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage2D()
void GLAPIENTRY _mesa_TextureStorage2D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References GLAPIENTRY, and texturestorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage2DEXT()
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and void.
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage3D()
void GLAPIENTRY _mesa_TextureStorage3D (GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References GLAPIENTRY, and texturestorage().
Referenced by _mesa_valid_tex_storage_dim().
_mesa_TextureStorage3DEXT()
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References _mesa_error(), GET_CURRENT_CONTEXT, and void.
Referenced by _mesa_valid_tex_storage_dim().
clear_texture_fields()
static void clear_texture_fields (struct gl_context * ctx, struct gl_texture_object * texObj) static
Clear all fields of texture object to zeros.
Used for proxy texture tests and to clean up when a texture memory allocation fails.
References _mesa_clear_texture_image(), _mesa_error(), _mesa_num_tex_faces(), get_tex_image(), GLuint, gl_texture_object::Image, and gl_texture_object::Target.
Referenced by _mesa_texture_storage().
get_tex_image()
static struct gl_texture_image* get_tex_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint face, GLuint level) static
Helper to get a particular texture image in a texture object.
References _mesa_get_tex_image(), and gl_texture_object::Target.
Referenced by clear_texture_fields(), and initialize_texture_fields().
initialize_texture_fields()
static GLboolean initialize_texture_fields (struct gl_context * ctx, struct gl_texture_object * texObj, GLint levels, GLsizei width, GLsizei height, GLsizei depth, GLenum internalFormat, mesa_format texFormat) static
References _mesa_error(), _mesa_init_teximage_fields(), _mesa_next_mipmap_level_size(), _mesa_num_tex_faces(), get_tex_image(), GLuint, and gl_texture_object::Target.
Referenced by _mesa_texture_storage().
legal_texobj_target()
static bool legal_texobj_target (const struct gl_context * ctx, GLuint dims, GLenum target) static
Check if the given texture target is a legal texture object target for a glTexStorage() command.
This is a bit different than legal_teximage_target() when it comes to cube maps.
References _mesa_has_texture_cube_map_array(), _mesa_is_desktop_gl(), _mesa_problem(), gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::EXT_texture_array, gl_context::Extensions, and gl_extensions::NV_texture_rectangle.
Referenced by texstorage(), and texturestorage().
tex_storage_error_check()
static GLboolean tex_storage_error_check (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, bool dsa) static
Do error checking for calls to glTexStorage1/2/3D().
If an error is found, record it with _mesa_error(), unless the target is a proxy texture.
Returns
GL_TRUE if any error, GL_FALSE otherwise.
References _mesa_enum_to_string(), _mesa_error(), _mesa_get_tex_max_num_levels(), _mesa_is_compressed_format(), _mesa_is_proxy_texture(), _mesa_legal_texture_base_format_for_target(), _mesa_max_texture_levels(), _mesa_target_can_be_compressed(), _mesa_valid_tex_storage_dim(), gl_texture_object::Immutable, and gl_texture_object::Name.
Referenced by _mesa_texture_storage().
texstorage()
static void texstorage (GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) static
Helper used by _mesa_TexStorage1/2/3D().
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_is_legal_tex_storage_format(), _mesa_texture_storage(), GET_CURRENT_CONTEXT, legal_texobj_target(), MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_TexStorage1D(), _mesa_TexStorage2D(), and _mesa_TexStorage3D().
texturestorage()
static void texturestorage (GLuint dims, GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) static
Helper used by _mesa_TextureStorage1/2/3D().
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_is_legal_tex_storage_format(), _mesa_lookup_texture(), _mesa_texture_storage(), GET_CURRENT_CONTEXT, GLAPIENTRY, legal_texobj_target(), MESA_VERBOSE, gl_texture_object::Target, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_TextureStorage1D(), _mesa_TextureStorage2D(), and _mesa_TextureStorage3D().
update_fbo_texture()
static void update_fbo_texture (struct gl_context * ctx, struct gl_texture_object * texObj) static
Update/re-validate framebuffer object.
References _mesa_num_tex_faces(), _mesa_update_fbo_texture(), gl_texture_object::Image, and gl_texture_object::Target.
Referenced by _mesa_texture_storage().