Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
texstate.h File Reference
Texture state management.
#include "compiler.h"
#include "enums.h"
#include "macros.h"
#include "mtypes.h"
Functions
static struct gl_texture_unit * _mesa_get_tex_unit (struct gl_context *ctx, GLuint unit)
static struct gl_texture_unit * _mesa_get_current_tex_unit (struct gl_context *ctx)
Return pointer to current texture unit.
static GLuint _mesa_max_tex_unit (struct gl_context *ctx)
void _mesa_copy_texture_state (const struct gl_context *src, struct gl_context *dst)
Used by glXCopyContext to copy texture state from one context to another.
void _mesa_print_texunit_state (struct gl_context *ctx, GLuint unit)
Called from API
void GLAPIENTRY _mesa_ActiveTexture (GLenum target)
void GLAPIENTRY _mesa_ClientActiveTexture (GLenum target)
Initialization, state maintenance
void _mesa_update_texture_matrices (struct gl_context *ctx)
void _mesa_update_texture_state (struct gl_context *ctx)
GLboolean _mesa_init_texture (struct gl_context *ctx)
Initialize texture state for the given context.
void _mesa_free_texture_data (struct gl_context *ctx)
Free dynamically-allocted texture data attached to the given context.
void _mesa_update_default_objects_texture (struct gl_context *ctx)
Update the default texture objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
Detailed Description
Texture state management.
Function Documentation
_mesa_ActiveTexture()
void GLAPIENTRY _mesa_ActiveTexture (GLenum target)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_max_tex_unit(), _NEW_TEXTURE_STATE, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_max_tex_unit(), pop_enable_group(), and pop_texture_group().
_mesa_ClientActiveTexture()
void GLAPIENTRY _mesa_ClientActiveTexture (GLenum target)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLuint, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_max_tex_unit().
_mesa_copy_texture_state()
void _mesa_copy_texture_state (const struct gl_context * src, struct gl_context * dst)
Used by glXCopyContext to copy texture state from one context to another.
References gl_texture_unit::_BoundTextures, gl_texture_attrib::_GenFlags, _mesa_lock_context_textures(), _mesa_reference_texobj(), _mesa_unlock_context_textures(), gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_texture_unit::Combine, gl_context::Const, COPY_4V, gl_texture_unit::CurrentTex, gl_texture_attrib::CurrentUnit, gl_texture_unit::Enabled, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GLuint, gl_texture_unit::LodBias, gl_constants::MaxCombinedTextureImageUnits, NUM_TEXTURE_TARGETS, gl_texture_attrib::NumCurrentTexUsed, gl_context::Shared, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_copy_context(), and _mesa_max_tex_unit().
_mesa_free_texture_data()
void _mesa_free_texture_data (struct gl_context * ctx)
Free dynamically-allocted texture data attached to the given context.
References gl_texture_unit::_Current, _mesa_reference_buffer_object(), _mesa_reference_sampler_object(), _mesa_reference_texobj(), gl_texture_attrib::BufferObject, gl_texture_unit::CurrentTex, dd_function_table::DeleteTexture, gl_context::Driver, GLuint, NUM_TEXTURE_TARGETS, gl_texture_attrib::ProxyTex, gl_texture_unit::Sampler, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_free_context_data(), and _mesa_max_tex_unit().
_mesa_get_current_tex_unit()
static struct gl_texture_unit* _mesa_get_current_tex_unit (struct gl_context * ctx) static
Return pointer to current texture unit.
This the texture unit set by glActiveTexture(), not glClientActiveTexture().
References _mesa_get_tex_unit(), gl_texture_attrib::CurrentUnit, GLuint, and gl_context::Texture.
Referenced by _mesa_get_current_tex_object(), _mesa_GetTexEnvfv(), _mesa_GetTexEnviv(), _mesa_GetTexGendv(), _mesa_GetTexGenfv(), _mesa_GetTexGeniv(), _mesa_TexEnvfv(), _mesa_TexGenfv(), enable_texture(), and get_texobj_by_target().
_mesa_get_tex_unit()
static struct gl_texture_unit* _mesa_get_tex_unit (struct gl_context * ctx, GLuint unit) static
References gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_get_current_tex_unit().
_mesa_init_texture()
GLboolean _mesa_init_texture (struct gl_context * ctx)
Initialize texture state for the given context.
References _mesa_reference_buffer_object(), alloc_proxy_textures(), gl_context::API, API_OPENGLES2, gl_texture_attrib::BufferObject, gl_texture_attrib::CubeMapSeamless, gl_texture_attrib::CurrentUnit, gl_shared_state::DefaultTex, GLuint, init_texture_unit(), MAX_COMBINED_TEXTURE_IMAGE_UNITS, gl_shared_state::NullBufferObj, gl_texture_attrib::NumCurrentTexUsed, gl_texture_object::RefCount, gl_context::Shared, gl_context::Texture, TEXTURE_1D_INDEX, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit(), and init_attrib_groups().
_mesa_max_tex_unit()
static GLuint _mesa_max_tex_unit (struct gl_context * ctx) inline static
References _mesa_ActiveTexture(), _mesa_ClientActiveTexture(), _mesa_copy_texture_state(), _mesa_free_texture_data(), _mesa_init_texture(), _mesa_print_texunit_state(), _mesa_update_default_objects_texture(), _mesa_update_texture_matrices(), _mesa_update_texture_state(), gl_context::Const, GLAPIENTRY, GLuint, gl_constants::MaxCombinedTextureImageUnits, and gl_constants::MaxTextureCoordUnits.
Referenced by _mesa_ActiveTexture(), _mesa_BindTextureUnit(), and find_value_indexed().
_mesa_print_texunit_state()
void _mesa_print_texunit_state (struct gl_context * ctx, GLuint unit)
References _mesa_enum_to_string(), gl_texture_unit::Combine, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit().
_mesa_update_default_objects_texture()
void _mesa_update_default_objects_texture (struct gl_context * ctx)
Update the default texture objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
References _mesa_reference_texobj(), gl_texture_unit::CurrentTex, gl_shared_state::DefaultTex, GLuint, NUM_TEXTURE_TARGETS, gl_context::Shared, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit(), and update_default_objects().
_mesa_update_texture_matrices()
void _mesa_update_texture_matrices (struct gl_context * ctx)
Note
This routine refers to derived texture attribute values to compute the ENABLE_TEXMAT flags, but is only called on _NEW_TEXTURE_MATRIX. On changes to _NEW_TEXTURE_OBJECT/STATE, the ENABLE_TEXMAT flags are updated by _mesa_update_textures(), below.
Parameters
ctx GL context.
References gl_texture_unit::_Current, _math_matrix_analyse(), _math_matrix_is_dirty(), gl_texture_attrib::_TexMatEnabled, gl_context::Const, ENABLE_TEXMAT, GLuint, MATRIX_IDENTITY, gl_constants::MaxTextureCoordUnits, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, GLmatrix::type, and gl_texture_attrib::Unit.
Referenced by _mesa_max_tex_unit(), and _mesa_update_state_locked().
_mesa_update_texture_state()
void _mesa_update_texture_state (struct gl_context * ctx)
Note
This routine refers to derived texture matrix values to compute the ENABLE_TEXMAT flags, but is only called on _NEW_TEXTURE_OBJECT/STATE. On changes to _NEW_TEXTURE_MATRIX, the ENABLE_TEXMAT flags are updated by _mesa_update_texture_matrices, above.
Parameters
ctx GL context.
References gl_texture_unit::_Current, gl_fragment_program_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, gl_texture_attrib::_GenFlags, gl_texture_attrib::_MaxEnabledTexImageUnit, _mesa_reference_texobj(), _NEW_TEXTURE_OBJECT, _NEW_TEXTURE_STATE, gl_context::_Shader, gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_fragment_program_state::Current, gl_pipeline_object::CurrentProgram, gl_context::FragmentProgram, MAX_COMBINED_TEXTURE_IMAGE_UNITS, gl_context::NewState, gl_context::Texture, gl_texture_attrib::Unit, update_ff_texture_state(), update_program_texture_state(), and update_texgen().
Referenced by _mesa_max_tex_unit(), and _mesa_update_state_locked().