Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
textureview.h File Reference
Functions
bool _mesa_texture_view_compatible_format (const struct gl_context *ctx, GLenum origInternalFormat, GLenum newInternalFormat)
Check for compatible format If an error is found, record it with _mesa_error()
GLenum _mesa_texture_view_lookup_view_class (const struct gl_context *ctx, GLenum internalformat)
Lookup format view class based on internalformat.
void GLAPIENTRY _mesa_TextureView (GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers)
glTextureView (ARB_texture_view) If an error is found, record it with _mesa_error()
void _mesa_set_texture_view_state (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLuint levels)
Helper function for TexStorage and teximagemultisample to set immutable texture state needed by ARB_texture_view.
Function Documentation
_mesa_set_texture_view_state()
void _mesa_set_texture_view_state (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLuint levels)
Helper function for TexStorage and teximagemultisample to set immutable texture state needed by ARB_texture_view.
References _mesa_select_tex_image(), gl_texture_image::Depth, GLAPIENTRY, gl_texture_image::Height, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_texture_object::MinLayer, gl_texture_object::MinLevel, gl_texture_object::NumLayers, and gl_texture_object::NumLevels.
Referenced by _mesa_texture_storage(), and texture_image_multisample().
_mesa_texture_view_compatible_format()
bool _mesa_texture_view_compatible_format (const struct gl_context * ctx, GLenum origInternalFormat, GLenum newInternalFormat)
Check for compatible format If an error is found, record it with _mesa_error()
Returns
false if any error, true otherwise.
References _mesa_texture_view_lookup_view_class().
Referenced by _mesa_TextureView(), and copy_format_compatible().
_mesa_texture_view_lookup_view_class()
GLenum _mesa_texture_view_lookup_view_class (const struct gl_context * ctx, GLenum internalformat)
Lookup format view class based on internalformat.
Returns
VIEW_CLASS if internalformat found in table, false otherwise.
References _mesa_is_gles3(), gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_sRGB, gl_context::Extensions, GLuint, internal_format_class_info::internal_format, gl_extensions::KHR_texture_compression_astc_ldr, gl_extensions::OES_texture_compression_astc, and internal_format_class_info::view_class.
Referenced by _mesa_GetInternalformativ(), and _mesa_texture_view_compatible_format().
_mesa_TextureView()
void GLAPIENTRY _mesa_TextureView (GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers)
glTextureView (ARB_texture_view) If an error is found, record it with _mesa_error()
Returns
none.
References _mesa_choose_texture_format(), _mesa_cube_face_target(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_legal_texture_dimensions(), _mesa_lookup_texture(), _mesa_select_tex_image(), _mesa_tex_target_to_index(), _mesa_texture_view_compatible_format(), gl_texture_image::Depth, GET_CURRENT_CONTEXT, GLuint, gl_texture_image::Height, gl_texture_object::Image, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, initialize_texture_fields(), gl_texture_image::InternalFormat, MESA_FORMAT_NONE, MESA_VERBOSE, gl_texture_object::MinLayer, gl_texture_object::MinLevel, NUM_TEXTURE_TARGETS, gl_texture_object::NumLayers, gl_texture_object::NumLevels, gl_texture_image::NumSamples, gl_texture_object::Target, target_valid(), gl_texture_object::TargetIndex, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.