Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
textureview.c File Reference
GL_ARB_texture_view functions.
#include "glheader.h"
#include "context.h"
#include "enums.h"
#include "imports.h"
#include "macros.h"
#include "teximage.h"
#include "texobj.h"
#include "mipmap.h"
#include "texstorage.h"
#include "textureview.h"
#include "stdbool.h"
#include "mtypes.h"
Data Structures
struct internal_format_class_info
Macros
#define VIEW_CLASS_GLES(x) (GL_VIEW_CLASS_BPTC_FLOAT + 1 + x)
#define VIEW_CLASS_EAC_R11 VIEW_CLASS_GLES(0)
#define VIEW_CLASS_EAC_RG11 VIEW_CLASS_GLES(1)
#define VIEW_CLASS_ETC2_RGB VIEW_CLASS_GLES(2)
#define VIEW_CLASS_ETC2_RGBA VIEW_CLASS_GLES(3)
#define VIEW_CLASS_ETC2_EAC_RGBA VIEW_CLASS_GLES(4)
#define VIEW_CLASS_ASTC_4x4_RGBA VIEW_CLASS_GLES(5)
#define VIEW_CLASS_ASTC_5x4_RGBA VIEW_CLASS_GLES(6)
#define VIEW_CLASS_ASTC_5x5_RGBA VIEW_CLASS_GLES(7)
#define VIEW_CLASS_ASTC_6x5_RGBA VIEW_CLASS_GLES(8)
#define VIEW_CLASS_ASTC_6x6_RGBA VIEW_CLASS_GLES(9)
#define VIEW_CLASS_ASTC_8x5_RGBA VIEW_CLASS_GLES(10)
#define VIEW_CLASS_ASTC_8x6_RGBA VIEW_CLASS_GLES(11)
#define VIEW_CLASS_ASTC_8x8_RGBA VIEW_CLASS_GLES(12)
#define VIEW_CLASS_ASTC_10x5_RGBA VIEW_CLASS_GLES(13)
#define VIEW_CLASS_ASTC_10x6_RGBA VIEW_CLASS_GLES(14)
#define VIEW_CLASS_ASTC_10x8_RGBA VIEW_CLASS_GLES(15)
#define VIEW_CLASS_ASTC_10x10_RGBA VIEW_CLASS_GLES(16)
#define VIEW_CLASS_ASTC_12x10_RGBA VIEW_CLASS_GLES(17)
#define VIEW_CLASS_ASTC_12x12_RGBA VIEW_CLASS_GLES(18)
#define VIEW_CLASS_ASTC_3x3x3_RGBA VIEW_CLASS_GLES(19)
#define VIEW_CLASS_ASTC_4x3x3_RGBA VIEW_CLASS_GLES(20)
#define VIEW_CLASS_ASTC_4x4x3_RGBA VIEW_CLASS_GLES(21)
#define VIEW_CLASS_ASTC_4x4x4_RGBA VIEW_CLASS_GLES(22)
#define VIEW_CLASS_ASTC_5x4x4_RGBA VIEW_CLASS_GLES(23)
#define VIEW_CLASS_ASTC_5x5x4_RGBA VIEW_CLASS_GLES(24)
#define VIEW_CLASS_ASTC_5x5x5_RGBA VIEW_CLASS_GLES(25)
#define VIEW_CLASS_ASTC_6x5x5_RGBA VIEW_CLASS_GLES(26)
#define VIEW_CLASS_ASTC_6x6x5_RGBA VIEW_CLASS_GLES(27)
#define VIEW_CLASS_ASTC_6x6x6_RGBA VIEW_CLASS_GLES(28)
#define ASTC_FMT(size)
#define ASTC_FMT(size)
#define RETURN_IF_SUPPORTED(t)
Functions
GLenum _mesa_texture_view_lookup_view_class (const struct gl_context *ctx, GLenum internalformat)
Lookup format view class based on internalformat.
static GLboolean initialize_texture_fields (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, GLint levels, GLsizei width, GLsizei height, GLsizei depth, GLenum internalFormat, mesa_format texFormat)
Initialize new texture's gl_texture_image structures.
static bool target_valid (struct gl_context *ctx, GLenum origTarget, GLenum newTarget)
Check for compatible target If an error is found, record it with _mesa_error()
bool _mesa_texture_view_compatible_format (const struct gl_context *ctx, GLenum origInternalFormat, GLenum newInternalFormat)
Check for compatible format If an error is found, record it with _mesa_error()
void _mesa_set_texture_view_state (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLuint levels)
Helper function for TexStorage and teximagemultisample to set immutable texture state needed by ARB_texture_view.
void GLAPIENTRY _mesa_TextureView (GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers)
glTextureView (ARB_texture_view) If an error is found, record it with _mesa_error()
Variables
static const struct internal_format_class_info compatible_internal_formats []
static const struct internal_format_class_info s3tc_compatible_internal_formats []
static const struct internal_format_class_info gles_etc2_compatible_internal_formats []
static const struct internal_format_class_info gles_astc_compatible_internal_formats []
static const struct internal_format_class_info gles_astc_3d_compatible_internal_formats []
Detailed Description
GL_ARB_texture_view functions.
Macro Definition Documentation
ASTC_FMT [1/2]
#define ASTC_FMT (size)
Value:
{VIEW_CLASS_ASTC_##size##_RGBA, GL_COMPRESSED_RGBA_ASTC_##size##_KHR}, \
   {VIEW_CLASS_ASTC_##size##_RGBA, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_##size##_KHR}
ASTC_FMT [2/2]
#define ASTC_FMT (size)
Value:
{VIEW_CLASS_ASTC_##size##_RGBA, GL_COMPRESSED_RGBA_ASTC_##size##_OES}, \
   {VIEW_CLASS_ASTC_##size##_RGBA, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_##size##_OES}
RETURN_IF_SUPPORTED
#define RETURN_IF_SUPPORTED (t)
Value:
do {            \
   if (newTarget == GL_ ## t)                   \
      return true;                              \
} while (0)
Referenced by target_valid().
VIEW_CLASS_ASTC_10x10_RGBA
#define VIEW_CLASS_ASTC_10x10_RGBA VIEW_CLASS_GLES(16)
VIEW_CLASS_ASTC_10x5_RGBA
#define VIEW_CLASS_ASTC_10x5_RGBA VIEW_CLASS_GLES(13)
VIEW_CLASS_ASTC_10x6_RGBA
#define VIEW_CLASS_ASTC_10x6_RGBA VIEW_CLASS_GLES(14)
VIEW_CLASS_ASTC_10x8_RGBA
#define VIEW_CLASS_ASTC_10x8_RGBA VIEW_CLASS_GLES(15)
VIEW_CLASS_ASTC_12x10_RGBA
#define VIEW_CLASS_ASTC_12x10_RGBA VIEW_CLASS_GLES(17)
VIEW_CLASS_ASTC_12x12_RGBA
#define VIEW_CLASS_ASTC_12x12_RGBA VIEW_CLASS_GLES(18)
VIEW_CLASS_ASTC_3x3x3_RGBA
#define VIEW_CLASS_ASTC_3x3x3_RGBA VIEW_CLASS_GLES(19)
VIEW_CLASS_ASTC_4x3x3_RGBA
#define VIEW_CLASS_ASTC_4x3x3_RGBA VIEW_CLASS_GLES(20)
VIEW_CLASS_ASTC_4x4_RGBA
#define VIEW_CLASS_ASTC_4x4_RGBA VIEW_CLASS_GLES(5)
VIEW_CLASS_ASTC_4x4x3_RGBA
#define VIEW_CLASS_ASTC_4x4x3_RGBA VIEW_CLASS_GLES(21)
VIEW_CLASS_ASTC_4x4x4_RGBA
#define VIEW_CLASS_ASTC_4x4x4_RGBA VIEW_CLASS_GLES(22)
VIEW_CLASS_ASTC_5x4_RGBA
#define VIEW_CLASS_ASTC_5x4_RGBA VIEW_CLASS_GLES(6)
VIEW_CLASS_ASTC_5x4x4_RGBA
#define VIEW_CLASS_ASTC_5x4x4_RGBA VIEW_CLASS_GLES(23)
VIEW_CLASS_ASTC_5x5_RGBA
#define VIEW_CLASS_ASTC_5x5_RGBA VIEW_CLASS_GLES(7)
VIEW_CLASS_ASTC_5x5x4_RGBA
#define VIEW_CLASS_ASTC_5x5x4_RGBA VIEW_CLASS_GLES(24)
VIEW_CLASS_ASTC_5x5x5_RGBA
#define VIEW_CLASS_ASTC_5x5x5_RGBA VIEW_CLASS_GLES(25)
VIEW_CLASS_ASTC_6x5_RGBA
#define VIEW_CLASS_ASTC_6x5_RGBA VIEW_CLASS_GLES(8)
VIEW_CLASS_ASTC_6x5x5_RGBA
#define VIEW_CLASS_ASTC_6x5x5_RGBA VIEW_CLASS_GLES(26)
VIEW_CLASS_ASTC_6x6_RGBA
#define VIEW_CLASS_ASTC_6x6_RGBA VIEW_CLASS_GLES(9)
VIEW_CLASS_ASTC_6x6x5_RGBA
#define VIEW_CLASS_ASTC_6x6x5_RGBA VIEW_CLASS_GLES(27)
VIEW_CLASS_ASTC_6x6x6_RGBA
#define VIEW_CLASS_ASTC_6x6x6_RGBA VIEW_CLASS_GLES(28)
VIEW_CLASS_ASTC_8x5_RGBA
#define VIEW_CLASS_ASTC_8x5_RGBA VIEW_CLASS_GLES(10)
VIEW_CLASS_ASTC_8x6_RGBA
#define VIEW_CLASS_ASTC_8x6_RGBA VIEW_CLASS_GLES(11)
VIEW_CLASS_ASTC_8x8_RGBA
#define VIEW_CLASS_ASTC_8x8_RGBA VIEW_CLASS_GLES(12)
VIEW_CLASS_EAC_R11
#define VIEW_CLASS_EAC_R11 VIEW_CLASS_GLES(0)
VIEW_CLASS_EAC_RG11
#define VIEW_CLASS_EAC_RG11 VIEW_CLASS_GLES(1)
VIEW_CLASS_ETC2_EAC_RGBA
#define VIEW_CLASS_ETC2_EAC_RGBA VIEW_CLASS_GLES(4)
VIEW_CLASS_ETC2_RGB
#define VIEW_CLASS_ETC2_RGB VIEW_CLASS_GLES(2)
VIEW_CLASS_ETC2_RGBA
#define VIEW_CLASS_ETC2_RGBA VIEW_CLASS_GLES(3)
VIEW_CLASS_GLES
#define VIEW_CLASS_GLES (x) (GL_VIEW_CLASS_BPTC_FLOAT + 1 + x)
Function Documentation
_mesa_set_texture_view_state()
void _mesa_set_texture_view_state (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLuint levels)
Helper function for TexStorage and teximagemultisample to set immutable texture state needed by ARB_texture_view.
References _mesa_select_tex_image(), gl_texture_image::Depth, GLAPIENTRY, gl_texture_image::Height, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_texture_object::MinLayer, gl_texture_object::MinLevel, gl_texture_object::NumLayers, and gl_texture_object::NumLevels.
Referenced by _mesa_texture_storage(), and texture_image_multisample().
_mesa_texture_view_compatible_format()
bool _mesa_texture_view_compatible_format (const struct gl_context * ctx, GLenum origInternalFormat, GLenum newInternalFormat)
Check for compatible format If an error is found, record it with _mesa_error()
Returns
false if any error, true otherwise.
References _mesa_texture_view_lookup_view_class().
Referenced by _mesa_TextureView(), and copy_format_compatible().
_mesa_texture_view_lookup_view_class()
GLenum _mesa_texture_view_lookup_view_class (const struct gl_context * ctx, GLenum internalformat)
Lookup format view class based on internalformat.
Returns
VIEW_CLASS if internalformat found in table, false otherwise.
References _mesa_is_gles3(), gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_sRGB, gl_context::Extensions, GLuint, internal_format_class_info::internal_format, gl_extensions::KHR_texture_compression_astc_ldr, gl_extensions::OES_texture_compression_astc, and internal_format_class_info::view_class.
Referenced by _mesa_GetInternalformativ(), and _mesa_texture_view_compatible_format().
_mesa_TextureView()
void GLAPIENTRY _mesa_TextureView (GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers)
glTextureView (ARB_texture_view) If an error is found, record it with _mesa_error()
Returns
none.
References _mesa_choose_texture_format(), _mesa_cube_face_target(), _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _mesa_legal_texture_dimensions(), _mesa_lookup_texture(), _mesa_select_tex_image(), _mesa_tex_target_to_index(), _mesa_texture_view_compatible_format(), gl_texture_image::Depth, GET_CURRENT_CONTEXT, GLuint, gl_texture_image::Height, gl_texture_object::Image, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, initialize_texture_fields(), gl_texture_image::InternalFormat, MESA_FORMAT_NONE, MESA_VERBOSE, gl_texture_object::MinLayer, gl_texture_object::MinLevel, NUM_TEXTURE_TARGETS, gl_texture_object::NumLayers, gl_texture_object::NumLevels, gl_texture_image::NumSamples, gl_texture_object::Target, target_valid(), gl_texture_object::TargetIndex, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
initialize_texture_fields()
static GLboolean initialize_texture_fields (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj, GLint levels, GLsizei width, GLsizei height, GLsizei depth, GLenum internalFormat, mesa_format texFormat) static
Initialize new texture's gl_texture_image structures.
Will not call driver to allocate new space, simply record relevant layer, face, format, etc.
Returns
GL_FALSE if any error, GL_TRUE otherwise.
References _mesa_cube_face_target(), _mesa_error(), _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_next_mipmap_level_size(), _mesa_num_tex_faces(), GLuint, and gl_texture_object::Target.
Referenced by _mesa_TextureView().
target_valid()
static bool target_valid (struct gl_context * ctx, GLenum origTarget, GLenum newTarget) static
Check for compatible target If an error is found, record it with _mesa_error()
Returns
false if any error, true otherwise.
References _mesa_enum_to_string(), _mesa_error(), and RETURN_IF_SUPPORTED.
Referenced by _mesa_TextureView().
Variable Documentation
compatible_internal_formats
const struct internal_format_class_info compatible_internal_formats[] static
gles_astc_3d_compatible_internal_formats
const struct internal_format_class_info gles_astc_3d_compatible_internal_formats[] static
Initial value:
= {
#define ASTC_FMT(size)
   ASTC_FMT(3x3x3),
   ASTC_FMT(4x3x3),
   ASTC_FMT(4x4x3),
   ASTC_FMT(4x4x4),
   ASTC_FMT(5x4x4),
   ASTC_FMT(5x5x4),
   ASTC_FMT(5x5x5),
   ASTC_FMT(6x5x5),
   ASTC_FMT(6x6x5),
   ASTC_FMT(6x6x6),
}
gles_astc_compatible_internal_formats
const struct internal_format_class_info gles_astc_compatible_internal_formats[] static
Initial value:
= {
#define ASTC_FMT(size)
   ASTC_FMT(4x4),
   ASTC_FMT(5x4),
   ASTC_FMT(5x5),
   ASTC_FMT(6x5),
   ASTC_FMT(6x6),
   ASTC_FMT(8x5),
   ASTC_FMT(8x6),
   ASTC_FMT(8x8),
   ASTC_FMT(10x5),
   ASTC_FMT(10x6),
   ASTC_FMT(10x8),
   ASTC_FMT(10x10),
   ASTC_FMT(12x10),
   ASTC_FMT(12x12),
}
gles_etc2_compatible_internal_formats
const struct internal_format_class_info gles_etc2_compatible_internal_formats[] static
Initial value:
= {
   {VIEW_CLASS_EAC_R11, GL_COMPRESSED_R11_EAC},
   {VIEW_CLASS_EAC_R11, GL_COMPRESSED_SIGNED_R11_EAC},
   {VIEW_CLASS_EAC_RG11, GL_COMPRESSED_RG11_EAC},
   {VIEW_CLASS_EAC_RG11, GL_COMPRESSED_SIGNED_RG11_EAC},
   {VIEW_CLASS_ETC2_RGB, GL_COMPRESSED_RGB8_ETC2},
   {VIEW_CLASS_ETC2_RGB, GL_COMPRESSED_SRGB8_ETC2},
   {VIEW_CLASS_ETC2_RGBA, GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2},
   {VIEW_CLASS_ETC2_RGBA, GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2},
   {VIEW_CLASS_ETC2_EAC_RGBA, GL_COMPRESSED_RGBA8_ETC2_EAC},
   {VIEW_CLASS_ETC2_EAC_RGBA, GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC},
}
s3tc_compatible_internal_formats
const struct internal_format_class_info s3tc_compatible_internal_formats[] static
Initial value:
= {
   {GL_VIEW_CLASS_S3TC_DXT1_RGB, GL_COMPRESSED_RGB_S3TC_DXT1_EXT},
   {GL_VIEW_CLASS_S3TC_DXT1_RGB, GL_COMPRESSED_SRGB_S3TC_DXT1_EXT},
   {GL_VIEW_CLASS_S3TC_DXT1_RGBA, GL_COMPRESSED_RGBA_S3TC_DXT1_EXT},
   {GL_VIEW_CLASS_S3TC_DXT1_RGBA, GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT},
   {GL_VIEW_CLASS_S3TC_DXT3_RGBA, GL_COMPRESSED_RGBA_S3TC_DXT3_EXT},
   {GL_VIEW_CLASS_S3TC_DXT3_RGBA, GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT},
   {GL_VIEW_CLASS_S3TC_DXT5_RGBA, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT},
   {GL_VIEW_CLASS_S3TC_DXT5_RGBA, GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT},
}