Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
transformfeedback.c File Reference
#include "buffers.h"
#include "context.h"
#include "hash.h"
#include "macros.h"
#include "mtypes.h"
#include "transformfeedback.h"
#include "shaderapi.h"
#include "shaderobj.h"
#include "main/dispatch.h"
#include "program/prog_parameter.h"
Data Structures
struct using_program_tuple
Functions
static void active_xfb_object_references_program (GLuint key, void *data, void *user_data)
bool _mesa_transform_feedback_is_using_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Return true if any active transform feedback object is using a program.
static void reference_transform_feedback_object (struct gl_transform_feedback_object **ptr, struct gl_transform_feedback_object *obj)
Do reference counting of transform feedback buffers.
GLboolean _mesa_validate_transform_feedback_buffers (struct gl_context *ctx)
Check that all the buffer objects currently bound for transform feedback actually exist.
void _mesa_init_transform_feedback (struct gl_context *ctx)
Per-context init for transform feedback.
static void delete_cb (GLuint key, void *data, void *userData)
Callback for _mesa_HashDeleteAll().
void _mesa_free_transform_feedback (struct gl_context *ctx)
Per-context free/clean-up for transform feedback.
void _mesa_init_transform_feedback_object (struct gl_transform_feedback_object *obj, GLuint name)
Initialize the fields of a gl_transform_feedback_object.
static struct gl_transform_feedback_object * new_transform_feedback (struct gl_context *ctx, GLuint name)
Default fallback for ctx->Driver.NewTransformFeedback()
static void delete_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.DeleteTransformFeedback()
static void begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.BeginTransformFeedback()
static void end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.EndTransformFeedback()
static void pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.PauseTransformFeedback()
static void resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.ResumeTransformFeedback()
void _mesa_init_transform_feedback_functions (struct dd_function_table *driver)
Plug in default device driver functions for transform feedback.
static void compute_transform_feedback_buffer_sizes (struct gl_transform_feedback_object *obj)
Fill in the correct Size value for each buffer in obj.
unsigned _mesa_compute_max_transform_feedback_vertices (struct gl_context *ctx, const struct gl_transform_feedback_object *obj, const struct gl_transform_feedback_info *info)
Compute the maximum number of vertices that can be written to the currently enabled transform feedback buffers without overflowing any of them.
static struct gl_program * get_xfb_source (struct gl_context *ctx)
Begin API functions.
void GLAPIENTRY _mesa_BeginTransformFeedback (GLenum mode)
void GLAPIENTRY _mesa_EndTransformFeedback (void)
static void bind_buffer_range (struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, bool dsa)
Helper used by BindBufferRange() and BindBufferBase().
void _mesa_bind_buffer_range_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, bool dsa)
Specify a buffer object to receive transform feedback results.
void _mesa_bind_buffer_base_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj, GLuint index, struct gl_buffer_object *bufObj, bool dsa)
Specify a buffer object to receive transform feedback results.
static struct gl_transform_feedback_object * lookup_transform_feedback_object_err (struct gl_context *ctx, GLuint xfb, const char *func)
Wrapper around lookup_transform_feedback_object that throws GL_INVALID_OPERATION if id is not in the hash table.
static struct gl_buffer_object * lookup_transform_feedback_bufferobj_err (struct gl_context *ctx, GLuint buffer, const char *func)
Wrapper around _mesa_lookup_bufferobj that throws GL_INVALID_VALUE if id is not in the hash table.
void GLAPIENTRY _mesa_TransformFeedbackBufferBase (GLuint xfb, GLuint index, GLuint buffer)
void GLAPIENTRY _mesa_TransformFeedbackBufferRange (GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
void GLAPIENTRY _mesa_BindBufferOffsetEXT (GLenum target, GLuint index, GLuint buffer, GLintptr offset)
Specify a buffer object to receive transform feedback results, plus the offset in the buffer to start placing results.
void GLAPIENTRY _mesa_TransformFeedbackVaryings (GLuint program, GLsizei count, const GLchar *const *varyings, GLenum bufferMode)
This function specifies the transform feedback outputs to be written to the feedback buffer(s), and in what order.
void GLAPIENTRY _mesa_GetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name)
Get info about the transform feedback outputs which are to be written to the feedback buffer(s).
struct gl_transform_feedback_object * _mesa_lookup_transform_feedback_object (struct gl_context *ctx, GLuint name)
static void create_transform_feedbacks (struct gl_context *ctx, GLsizei n, GLuint *ids, bool dsa)
void GLAPIENTRY _mesa_GenTransformFeedbacks (GLsizei n, GLuint *names)
Create new transform feedback objects.
void GLAPIENTRY _mesa_CreateTransformFeedbacks (GLsizei n, GLuint *names)
Create new transform feedback objects.
GLboolean GLAPIENTRY _mesa_IsTransformFeedback (GLuint name)
Is the given ID a transform feedback object? Part of GL_ARB_transform_feedback2.
void GLAPIENTRY _mesa_BindTransformFeedback (GLenum target, GLuint name)
Bind the given transform feedback object.
void GLAPIENTRY _mesa_DeleteTransformFeedbacks (GLsizei n, const GLuint *names)
Delete the given transform feedback objects.
void GLAPIENTRY _mesa_PauseTransformFeedback (void)
Pause transform feedback.
void GLAPIENTRY _mesa_ResumeTransformFeedback (void)
Resume transform feedback.
void GLAPIENTRY _mesa_GetTransformFeedbackiv (GLuint xfb, GLenum pname, GLint *param)
void GLAPIENTRY _mesa_GetTransformFeedbacki_v (GLuint xfb, GLenum pname, GLuint index, GLint *param)
void GLAPIENTRY _mesa_GetTransformFeedbacki64_v (GLuint xfb, GLenum pname, GLuint index, GLint64 *param)
Function Documentation
_mesa_BeginTransformFeedback()
void GLAPIENTRY _mesa_BeginTransformFeedback (GLenum mode)
References _mesa_compute_max_transform_feedback_vertices(), _mesa_error(), _mesa_is_gles3(), gl_transform_feedback_object::Active, gl_transform_feedback_info::ActiveBuffers, gl_transform_feedback_object::BufferNames, compute_transform_feedback_buffer_sizes(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_xfb_source(), GLAPIENTRY, gl_transform_feedback_object::GlesRemainingPrims, GLuint, gl_transform_feedback_info::NumOutputs, gl_transform_feedback_object::program, and gl_program::sh.
_mesa_bind_buffer_base_transform_feedback()
void _mesa_bind_buffer_base_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj, GLuint index, struct gl_buffer_object * bufObj, bool dsa)
Specify a buffer object to receive transform feedback results.
As above, but start at offset = 0. Called from the glBindBufferBase() and glTransformFeedbackBufferBase() functions.
References _mesa_error(), gl_transform_feedback_object::Active, bind_buffer_range(), gl_context::Const, and gl_constants::MaxTransformFeedbackBuffers.
Referenced by _mesa_BindBufferBase(), and _mesa_TransformFeedbackBufferBase().
_mesa_bind_buffer_range_transform_feedback()
void _mesa_bind_buffer_range_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, bool dsa)
Specify a buffer object to receive transform feedback results.
Plus, specify the starting offset to place the results, and max size. Called from the glBindBufferRange() and glTransformFeedbackBufferRange functions.
References _mesa_error(), gl_transform_feedback_object::Active, bind_buffer_range(), gl_context::Const, gl_constants::MaxTransformFeedbackBuffers, gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_BindBufferRange(), and _mesa_TransformFeedbackBufferRange().
_mesa_BindBufferOffsetEXT()
void GLAPIENTRY _mesa_BindBufferOffsetEXT (GLenum target, GLuint index, GLuint buffer, GLintptr offset)
Specify a buffer object to receive transform feedback results, plus the offset in the buffer to start placing results.
This function is part of GL_EXT_transform_feedback, but not GL3.
References _mesa_error(), _mesa_lookup_bufferobj(), gl_transform_feedback_object::Active, bind_buffer_range(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_BindTransformFeedback()
void GLAPIENTRY _mesa_BindTransformFeedback (GLenum target, GLuint name)
Bind the given transform feedback object.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_transform_feedback_object(), GET_CURRENT_CONTEXT, GLAPIENTRY, and reference_transform_feedback_object().
_mesa_compute_max_transform_feedback_vertices()
unsigned _mesa_compute_max_transform_feedback_vertices (struct gl_context * ctx, const struct gl_transform_feedback_object * obj, const struct gl_transform_feedback_info * info)
Compute the maximum number of vertices that can be written to the currently enabled transform feedback buffers without overflowing any of them.
References gl_transform_feedback_info::ActiveBuffers, gl_transform_feedback_info::Buffers, gl_context::Const, gl_constants::MaxTransformFeedbackBuffers, gl_transform_feedback_object::Size, and gl_transform_feedback_buffer::Stride.
Referenced by _mesa_BeginTransformFeedback().
_mesa_CreateTransformFeedbacks()
void GLAPIENTRY _mesa_CreateTransformFeedbacks (GLsizei n, GLuint * names)
Create new transform feedback objects.
Transform feedback objects encapsulate the state related to transform feedback to allow quickly switching state (and drawing the results, below). Part of GL_ARB_direct_state_access.
References create_transform_feedbacks(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_DeleteTransformFeedbacks()
void GLAPIENTRY _mesa_DeleteTransformFeedbacks (GLsizei n, const GLuint * names)
Delete the given transform feedback objects.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_HashRemove(), _mesa_lookup_transform_feedback_object(), gl_transform_feedback_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, and reference_transform_feedback_object().
_mesa_EndTransformFeedback()
void GLAPIENTRY _mesa_EndTransformFeedback (void)
References _mesa_error(), gl_transform_feedback_object::Active, FLUSH_VERTICES, and GET_CURRENT_CONTEXT.
_mesa_free_transform_feedback()
void _mesa_free_transform_feedback (struct gl_context * ctx)
Per-context free/clean-up for transform feedback.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), _mesa_reference_buffer_object(), gl_transform_feedback_state::CurrentBuffer, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_state::DefaultObject, delete_cb(), dd_function_table::DeleteTransformFeedback, gl_context::Driver, dd_function_table::NewTransformFeedback, gl_transform_feedback_state::Objects, and gl_context::TransformFeedback.
Referenced by _mesa_free_context_data().
_mesa_GenTransformFeedbacks()
void GLAPIENTRY _mesa_GenTransformFeedbacks (GLsizei n, GLuint * names)
Create new transform feedback objects.
Transform feedback objects encapsulate the state related to transform feedback to allow quickly switching state (and drawing the results, below). Part of GL_ARB_transform_feedback2.
References create_transform_feedbacks(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetTransformFeedbacki64_v()
void GLAPIENTRY _mesa_GetTransformFeedbacki64_v (GLuint xfb, GLenum pname, GLuint index, GLint64 * param)
References _mesa_error(), compute_transform_feedback_buffer_sizes(), GET_CURRENT_CONTEXT, lookup_transform_feedback_object_err(), gl_transform_feedback_object::Offset, and gl_transform_feedback_object::Size.
Referenced by _mesa_set_transform_feedback_binding().
_mesa_GetTransformFeedbacki_v()
void GLAPIENTRY _mesa_GetTransformFeedbacki_v (GLuint xfb, GLenum pname, GLuint index, GLint * param)
References _mesa_error(), gl_transform_feedback_object::BufferNames, GET_CURRENT_CONTEXT, GLAPIENTRY, and lookup_transform_feedback_object_err().
Referenced by _mesa_set_transform_feedback_binding().
_mesa_GetTransformFeedbackiv()
void GLAPIENTRY _mesa_GetTransformFeedbackiv (GLuint xfb, GLenum pname, GLint * param)
References _mesa_error(), gl_transform_feedback_object::Active, GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_transform_feedback_object_err(), and gl_transform_feedback_object::Paused.
Referenced by _mesa_set_transform_feedback_binding().
_mesa_GetTransformFeedbackVarying()
void GLAPIENTRY _mesa_GetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLsizei * size, GLenum * type, GLchar * name)
Get info about the transform feedback outputs which are to be written to the feedback buffer(s).
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_index(), _mesa_program_resource_name(), _mesa_program_resource_prop(), and GET_CURRENT_CONTEXT.
_mesa_init_transform_feedback()
void _mesa_init_transform_feedback (struct gl_context * ctx)
Per-context init for transform feedback.
References _mesa_NewHashTable(), _mesa_reference_buffer_object(), gl_transform_feedback_state::CurrentBuffer, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_state::DefaultObject, gl_context::Driver, dd_function_table::NewTransformFeedback, gl_shared_state::NullBufferObj, gl_transform_feedback_state::Objects, gl_transform_feedback_object::RefCount, reference_transform_feedback_object(), gl_context::Shared, and gl_context::TransformFeedback.
Referenced by init_attrib_groups().
_mesa_init_transform_feedback_functions()
void _mesa_init_transform_feedback_functions (struct dd_function_table * driver)
Plug in default device driver functions for transform feedback.
Most drivers will override some/all of these.
References begin_transform_feedback(), dd_function_table::BeginTransformFeedback, delete_transform_feedback(), dd_function_table::DeleteTransformFeedback, end_transform_feedback(), dd_function_table::EndTransformFeedback, new_transform_feedback(), dd_function_table::NewTransformFeedback, pause_transform_feedback(), dd_function_table::PauseTransformFeedback, resume_transform_feedback(), and dd_function_table::ResumeTransformFeedback.
_mesa_init_transform_feedback_object()
void _mesa_init_transform_feedback_object (struct gl_transform_feedback_object * obj, GLuint name)
Initialize the fields of a gl_transform_feedback_object.
References gl_transform_feedback_object::EverBound, gl_transform_feedback_object::Name, and gl_transform_feedback_object::RefCount.
Referenced by new_transform_feedback().
_mesa_IsTransformFeedback()
GLboolean GLAPIENTRY _mesa_IsTransformFeedback (GLuint name)
Is the given ID a transform feedback object? Part of GL_ARB_transform_feedback2.
References _mesa_lookup_transform_feedback_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_transform_feedback_object::EverBound, GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_lookup_transform_feedback_object()
struct gl_transform_feedback_object* _mesa_lookup_transform_feedback_object (struct gl_context * ctx, GLuint name)
References _mesa_HashLookup(), gl_transform_feedback_state::DefaultObject, gl_transform_feedback_state::Objects, and gl_context::TransformFeedback.
Referenced by _mesa_BindTransformFeedback(), _mesa_DeleteTransformFeedbacks(), _mesa_IsTransformFeedback(), get_label_pointer(), and lookup_transform_feedback_object_err().
_mesa_PauseTransformFeedback()
void GLAPIENTRY _mesa_PauseTransformFeedback (void)
Pause transform feedback.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_transform_feedback_object::Paused.
_mesa_ResumeTransformFeedback()
void GLAPIENTRY _mesa_ResumeTransformFeedback (void)
Resume transform feedback.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), gl_transform_feedback_object::Active, FLUSH_VERTICES, GET_CURRENT_CONTEXT, get_xfb_source(), GLAPIENTRY, gl_transform_feedback_object::Paused, and gl_transform_feedback_object::program.
_mesa_transform_feedback_is_using_program()
bool _mesa_transform_feedback_is_using_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Return true if any active transform feedback object is using a program.
References _mesa_HashWalk(), active_xfb_object_references_program(), gl_transform_feedback_state::DefaultObject, using_program_tuple::found, gl_shader_program::last_vert_prog, gl_transform_feedback_state::Objects, using_program_tuple::prog, and gl_context::TransformFeedback.
Referenced by _mesa_is_xfb_active_and_unpaused(), and _mesa_link_program().
_mesa_TransformFeedbackBufferBase()
void GLAPIENTRY _mesa_TransformFeedbackBufferBase (GLuint xfb, GLuint index, GLuint buffer)
References _mesa_bind_buffer_base_transform_feedback(), GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_transform_feedback_bufferobj_err(), and lookup_transform_feedback_object_err().
Referenced by _mesa_set_transform_feedback_binding().
_mesa_TransformFeedbackBufferRange()
void GLAPIENTRY _mesa_TransformFeedbackBufferRange (GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
References _mesa_bind_buffer_range_transform_feedback(), GET_CURRENT_CONTEXT, GLAPIENTRY, lookup_transform_feedback_bufferobj_err(), and lookup_transform_feedback_object_err().
Referenced by _mesa_set_transform_feedback_binding().
_mesa_TransformFeedbackVaryings()
void GLAPIENTRY _mesa_TransformFeedbackVaryings (GLuint program, GLsizei count, const GLchar *const * varyings, GLenum bufferMode)
This function specifies the transform feedback outputs to be written to the feedback buffer(s), and in what order.
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::BufferMode, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, gl_shader_program::NumVarying, gl_shader_program::TransformFeedback, and gl_shader_program::VaryingNames.
_mesa_validate_transform_feedback_buffers()
GLboolean _mesa_validate_transform_feedback_buffers (struct gl_context * ctx)
Check that all the buffer objects currently bound for transform feedback actually exist.
Raise a GL_INVALID_OPERATION error if any buffers are missing.
Returns
GL_TRUE for success, GL_FALSE if error
active_xfb_object_references_program()
static void active_xfb_object_references_program (GLuint key, void * data, void * user_data) static
References gl_transform_feedback_object::Active, using_program_tuple::found, using_program_tuple::prog, and gl_transform_feedback_object::program.
Referenced by _mesa_transform_feedback_is_using_program().
begin_transform_feedback()
static void begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.BeginTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().
bind_buffer_range()
static void bind_buffer_range (struct gl_context * ctx, struct gl_transform_feedback_object * obj, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, bool dsa) static
Helper used by BindBufferRange() and BindBufferBase().
References _mesa_reference_buffer_object(), _mesa_set_transform_feedback_binding(), gl_transform_feedback_state::CurrentBuffer, and gl_context::TransformFeedback.
Referenced by _mesa_bind_buffer_base_transform_feedback(), _mesa_bind_buffer_range_transform_feedback(), and _mesa_BindBufferOffsetEXT().
compute_transform_feedback_buffer_sizes()
static void compute_transform_feedback_buffer_sizes (struct gl_transform_feedback_object * obj) static
Fill in the correct Size value for each buffer in obj.
From the GL 4.3 spec, section 6.1.1 ("Binding Buffer Objects to Indexed Targets"):
BindBufferBase binds the entire buffer, even when the size of the buffer is changed after the binding is established. It is equivalent to calling BindBufferRange with offset zero, while size is determined by the size of the bound buffer at the time the binding is used.
Regardless of the size specified with BindBufferRange, or indirectly with BindBufferBase, the GL will never read or write beyond the end of a bound buffer. In some cases this constraint may result in visibly different behavior when a buffer overflow would otherwise result, such as described for transform feedback operations in section 13.2.2.
References gl_transform_feedback_object::Buffers, MAX_FEEDBACK_BUFFERS, gl_transform_feedback_object::Offset, gl_transform_feedback_object::RequestedSize, gl_buffer_object::Size, and gl_transform_feedback_object::Size.
Referenced by _mesa_BeginTransformFeedback(), and _mesa_GetTransformFeedbacki64_v().
create_transform_feedbacks()
static void create_transform_feedbacks (struct gl_context * ctx, GLsizei n, GLuint * ids, bool dsa) static
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_context::Driver, gl_transform_feedback_object::EverBound, GLAPIENTRY, GLuint, dd_function_table::NewTransformFeedback, gl_transform_feedback_state::Objects, and gl_context::TransformFeedback.
Referenced by _mesa_CreateTransformFeedbacks(), and _mesa_GenTransformFeedbacks().
delete_cb()
static void delete_cb (GLuint key, void * data, void * userData) static
Callback for _mesa_HashDeleteAll().
References dd_function_table::DeleteTransformFeedback, and gl_context::Driver.
Referenced by _mesa_free_transform_feedback().
delete_transform_feedback()
static void delete_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.DeleteTransformFeedback()
References _mesa_reference_buffer_object(), gl_transform_feedback_object::Buffers, GLuint, and gl_transform_feedback_object::Label.
Referenced by _mesa_init_transform_feedback_functions().
end_transform_feedback()
static void end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.EndTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().
get_xfb_source()
static struct gl_program* get_xfb_source (struct gl_context * ctx) static
Begin API functions.
Figure out which stage of the pipeline is the source of transform feedback data given the current context state, and return its gl_program.
If no active program can generate transform feedback data (i.e. no vertex shader is active), returns NULL.
References gl_context::_Shader, gl_pipeline_object::CurrentProgram, and GLAPIENTRY.
Referenced by _mesa_BeginTransformFeedback(), and _mesa_ResumeTransformFeedback().
lookup_transform_feedback_bufferobj_err()
static struct gl_buffer_object* lookup_transform_feedback_bufferobj_err (struct gl_context * ctx, GLuint buffer, const char * func) static
Wrapper around _mesa_lookup_bufferobj that throws GL_INVALID_VALUE if id is not in the hash table.
Specialised version for the transform-feedback-related functions. After calling _mesa_error, it returns NULL.
References _mesa_error(), _mesa_lookup_bufferobj(), GLAPIENTRY, gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_TransformFeedbackBufferBase(), and _mesa_TransformFeedbackBufferRange().
lookup_transform_feedback_object_err()
static struct gl_transform_feedback_object* lookup_transform_feedback_object_err (struct gl_context * ctx, GLuint xfb, const char * func) static
Wrapper around lookup_transform_feedback_object that throws GL_INVALID_OPERATION if id is not in the hash table.
After calling _mesa_error, it returns NULL.
References _mesa_error(), and _mesa_lookup_transform_feedback_object().
Referenced by _mesa_GetTransformFeedbacki64_v(), _mesa_GetTransformFeedbacki_v(), _mesa_GetTransformFeedbackiv(), _mesa_TransformFeedbackBufferBase(), and _mesa_TransformFeedbackBufferRange().
new_transform_feedback()
static struct gl_transform_feedback_object* new_transform_feedback (struct gl_context * ctx, GLuint name) static
Default fallback for ctx->Driver.NewTransformFeedback()
References _mesa_init_transform_feedback_object(), and CALLOC_STRUCT.
Referenced by _mesa_init_transform_feedback_functions().
pause_transform_feedback()
static void pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.PauseTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().
reference_transform_feedback_object()
static void reference_transform_feedback_object (struct gl_transform_feedback_object ** ptr, struct gl_transform_feedback_object * obj) static
Do reference counting of transform feedback buffers.
References _mesa_problem(), gl_transform_feedback_object::EverBound, GET_CURRENT_CONTEXT, and gl_transform_feedback_object::RefCount.
Referenced by _mesa_BindTransformFeedback(), _mesa_DeleteTransformFeedbacks(), and _mesa_init_transform_feedback().
resume_transform_feedback()
static void resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.ResumeTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().