Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
uniforms.h File Reference
#include "main/glheader.h"
#include "compiler/glsl_types.h"
#include "compiler/glsl/ir_uniform.h"
#include "program/prog_parameter.h"
Data Structures
struct gl_builtin_uniform_element
struct gl_builtin_uniform_desc
Functions
void GLAPIENTRY _mesa_Uniform1f (GLint, GLfloat)
void GLAPIENTRY _mesa_Uniform2f (GLint, GLfloat, GLfloat)
void GLAPIENTRY _mesa_Uniform3f (GLint, GLfloat, GLfloat, GLfloat)
void GLAPIENTRY _mesa_Uniform4f (GLint, GLfloat, GLfloat, GLfloat, GLfloat)
void GLAPIENTRY _mesa_Uniform1i (GLint, GLint)
void GLAPIENTRY _mesa_Uniform2i (GLint, GLint, GLint)
void GLAPIENTRY _mesa_Uniform3i (GLint, GLint, GLint, GLint)
void GLAPIENTRY _mesa_Uniform4i (GLint, GLint, GLint, GLint, GLint)
void GLAPIENTRY _mesa_Uniform1fv (GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_Uniform2fv (GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_Uniform3fv (GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_Uniform4fv (GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_Uniform1iv (GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_Uniform2iv (GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_Uniform3iv (GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_Uniform4iv (GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_Uniform1ui (GLint location, GLuint v0)
OpenGL 3.0 GLuint-valued functions.
void GLAPIENTRY _mesa_Uniform2ui (GLint location, GLuint v0, GLuint v1)
void GLAPIENTRY _mesa_Uniform3ui (GLint location, GLuint v0, GLuint v1, GLuint v2)
void GLAPIENTRY _mesa_Uniform4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
void GLAPIENTRY _mesa_Uniform1uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_Uniform2uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_Uniform3uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_Uniform4uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_UniformMatrix2fv (GLint, GLsizei, GLboolean, const GLfloat *)
void GLAPIENTRY _mesa_UniformMatrix3fv (GLint, GLsizei, GLboolean, const GLfloat *)
void GLAPIENTRY _mesa_UniformMatrix4fv (GLint, GLsizei, GLboolean, const GLfloat *)
void GLAPIENTRY _mesa_UniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
Non-square UniformMatrix are OpenGL 2.1.
void GLAPIENTRY _mesa_UniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_ProgramUniform1f (GLuint program, GLint, GLfloat)
Same as above with direct state access.
void GLAPIENTRY _mesa_ProgramUniform2f (GLuint program, GLint, GLfloat, GLfloat)
void GLAPIENTRY _mesa_ProgramUniform3f (GLuint program, GLint, GLfloat, GLfloat, GLfloat)
void GLAPIENTRY _mesa_ProgramUniform4f (GLuint program, GLint, GLfloat, GLfloat, GLfloat, GLfloat)
void GLAPIENTRY _mesa_ProgramUniform1i (GLuint program, GLint, GLint)
void GLAPIENTRY _mesa_ProgramUniform2i (GLuint program, GLint, GLint, GLint)
void GLAPIENTRY _mesa_ProgramUniform3i (GLuint program, GLint, GLint, GLint, GLint)
void GLAPIENTRY _mesa_ProgramUniform4i (GLuint program, GLint, GLint, GLint, GLint, GLint)
void GLAPIENTRY _mesa_ProgramUniform1fv (GLuint program, GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniform2fv (GLuint program, GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniform3fv (GLuint program, GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniform4fv (GLuint program, GLint, GLsizei, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniform1iv (GLuint program, GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_ProgramUniform2iv (GLuint program, GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_ProgramUniform3iv (GLuint program, GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_ProgramUniform4iv (GLuint program, GLint, GLsizei, const GLint *)
void GLAPIENTRY _mesa_ProgramUniform1ui (GLuint program, GLint location, GLuint v0)
Same as above with direct state access.
void GLAPIENTRY _mesa_ProgramUniform2ui (GLuint program, GLint location, GLuint v0, GLuint v1)
void GLAPIENTRY _mesa_ProgramUniform3ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2)
void GLAPIENTRY _mesa_ProgramUniform4ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
void GLAPIENTRY _mesa_ProgramUniform1uiv (GLuint program, GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_ProgramUniform2uiv (GLuint program, GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_ProgramUniform3uiv (GLuint program, GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_ProgramUniform4uiv (GLuint program, GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix2fv (GLuint program, GLint, GLsizei, GLboolean, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniformMatrix3fv (GLuint program, GLint, GLsizei, GLboolean, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniformMatrix4fv (GLuint program, GLint, GLsizei, GLboolean, const GLfloat *)
void GLAPIENTRY _mesa_ProgramUniformMatrix2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
Same as above with direct state access.
void GLAPIENTRY _mesa_ProgramUniformMatrix3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_GetnUniformfvARB (GLuint, GLint, GLsizei, GLfloat *)
void GLAPIENTRY _mesa_GetUniformfv (GLuint, GLint, GLfloat *)
void GLAPIENTRY _mesa_GetnUniformivARB (GLuint, GLint, GLsizei, GLint *)
void GLAPIENTRY _mesa_GetUniformuiv (GLuint, GLint, GLuint *)
void GLAPIENTRY _mesa_GetnUniformuivARB (GLuint, GLint, GLsizei, GLuint *)
void GLAPIENTRY _mesa_GetnUniformdvARB (GLuint, GLint, GLsizei, GLdouble *)
void GLAPIENTRY _mesa_GetUniformdv (GLuint, GLint, GLdouble *)
GLint GLAPIENTRY _mesa_GetUniformLocation (GLuint, const GLcharARB *)
GLuint GLAPIENTRY _mesa_GetUniformBlockIndex (GLuint program, const GLchar *uniformBlockName)
void GLAPIENTRY _mesa_GetUniformIndices (GLuint program, GLsizei uniformCount, const GLchar *const *uniformNames, GLuint *uniformIndices)
void GLAPIENTRY _mesa_UniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
void GLAPIENTRY _mesa_ShaderStorageBlockBinding (GLuint program, GLuint shaderStorageBlockIndex, GLuint shaderStorageBlockBinding)
void GLAPIENTRY _mesa_GetActiveAtomicCounterBufferiv (GLuint program, GLuint bufferIndex, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName)
void GLAPIENTRY _mesa_GetActiveUniformName (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName)
void GLAPIENTRY _mesa_GetActiveUniform (GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLcharARB *)
void GLAPIENTRY _mesa_GetActiveUniformsiv (GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetUniformiv (GLuint, GLint, GLint *)
void GLAPIENTRY _mesa_Uniform1d (GLint, GLdouble)
void GLAPIENTRY _mesa_Uniform2d (GLint, GLdouble, GLdouble)
void GLAPIENTRY _mesa_Uniform3d (GLint, GLdouble, GLdouble, GLdouble)
void GLAPIENTRY _mesa_Uniform4d (GLint, GLdouble, GLdouble, GLdouble, GLdouble)
void GLAPIENTRY _mesa_Uniform1dv (GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_Uniform2dv (GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_Uniform3dv (GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_Uniform4dv (GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_GetUniformi64vARB (GLuint, GLint, GLint64 *)
void GLAPIENTRY _mesa_GetUniformui64vARB (GLuint, GLint, GLuint64 *)
void GLAPIENTRY _mesa_GetnUniformi64vARB (GLuint, GLint, GLsizei, GLint64 *)
void GLAPIENTRY _mesa_GetnUniformui64vARB (GLuint, GLint, GLsizei, GLuint64 *)
void GLAPIENTRY _mesa_UniformMatrix2dv (GLint, GLsizei, GLboolean, const GLdouble *)
void GLAPIENTRY _mesa_UniformMatrix3dv (GLint, GLsizei, GLboolean, const GLdouble *)
void GLAPIENTRY _mesa_UniformMatrix4dv (GLint, GLsizei, GLboolean, const GLdouble *)
void GLAPIENTRY _mesa_UniformMatrix2x3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_UniformMatrix3x2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_UniformMatrix2x4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_UniformMatrix4x2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_UniformMatrix3x4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_UniformMatrix4x3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_ProgramUniform1d (GLuint program, GLint, GLdouble)
void GLAPIENTRY _mesa_ProgramUniform2d (GLuint program, GLint, GLdouble, GLdouble)
void GLAPIENTRY _mesa_ProgramUniform3d (GLuint program, GLint, GLdouble, GLdouble, GLdouble)
void GLAPIENTRY _mesa_ProgramUniform4d (GLuint program, GLint, GLdouble, GLdouble, GLdouble, GLdouble)
void GLAPIENTRY _mesa_ProgramUniform1dv (GLuint program, GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniform2dv (GLuint program, GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniform3dv (GLuint program, GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniform4dv (GLuint program, GLint, GLsizei, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniformMatrix2dv (GLuint program, GLint, GLsizei, GLboolean, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniformMatrix3dv (GLuint program, GLint, GLsizei, GLboolean, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniformMatrix4dv (GLuint program, GLint, GLsizei, GLboolean, const GLdouble *)
void GLAPIENTRY _mesa_ProgramUniformMatrix2x3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix3x2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix2x4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix4x2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix3x4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_ProgramUniformMatrix4x3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value)
void GLAPIENTRY _mesa_Uniform1i64ARB (GLint, GLint64)
void GLAPIENTRY _mesa_Uniform2i64ARB (GLint, GLint64, GLint64)
void GLAPIENTRY _mesa_Uniform3i64ARB (GLint, GLint64, GLint64, GLint64)
void GLAPIENTRY _mesa_Uniform4i64ARB (GLint, GLint64, GLint64, GLint64, GLint64)
void GLAPIENTRY _mesa_Uniform1i64vARB (GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_Uniform2i64vARB (GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_Uniform3i64vARB (GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_Uniform4i64vARB (GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_Uniform1ui64ARB (GLint, GLuint64)
void GLAPIENTRY _mesa_Uniform2ui64ARB (GLint, GLuint64, GLuint64)
void GLAPIENTRY _mesa_Uniform3ui64ARB (GLint, GLuint64, GLuint64, GLuint64)
void GLAPIENTRY _mesa_Uniform4ui64ARB (GLint, GLuint64, GLuint64, GLuint64, GLuint64)
void GLAPIENTRY _mesa_Uniform1ui64vARB (GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_Uniform2ui64vARB (GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_Uniform3ui64vARB (GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_Uniform4ui64vARB (GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_ProgramUniform1i64ARB (GLuint, GLint, GLint64)
void GLAPIENTRY _mesa_ProgramUniform2i64ARB (GLuint, GLint, GLint64, GLint64)
void GLAPIENTRY _mesa_ProgramUniform3i64ARB (GLuint, GLint, GLint64, GLint64, GLint64)
void GLAPIENTRY _mesa_ProgramUniform4i64ARB (GLuint, GLint, GLint64, GLint64, GLint64, GLint64)
void GLAPIENTRY _mesa_ProgramUniform1i64vARB (GLuint, GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_ProgramUniform2i64vARB (GLuint, GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_ProgramUniform3i64vARB (GLuint, GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_ProgramUniform4i64vARB (GLuint, GLint, GLsizei, const GLint64 *)
void GLAPIENTRY _mesa_ProgramUniform1ui64ARB (GLuint, GLint, GLuint64)
void GLAPIENTRY _mesa_ProgramUniform2ui64ARB (GLuint, GLint, GLuint64, GLuint64)
void GLAPIENTRY _mesa_ProgramUniform3ui64ARB (GLuint, GLint, GLuint64, GLuint64, GLuint64)
void GLAPIENTRY _mesa_ProgramUniform4ui64ARB (GLuint, GLint, GLuint64, GLuint64, GLuint64, GLuint64)
void GLAPIENTRY _mesa_ProgramUniform1ui64vARB (GLuint, GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_ProgramUniform2ui64vARB (GLuint, GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_ProgramUniform3ui64vARB (GLuint, GLint, GLsizei, const GLuint64 *)
void GLAPIENTRY _mesa_ProgramUniform4ui64vARB (GLuint, GLint, GLsizei, const GLuint64 *)
void _mesa_uniform (GLint location, GLsizei count, const GLvoid *values, struct gl_context *, struct gl_shader_program *, enum glsl_base_type basicType, unsigned src_components)
void _mesa_uniform_matrix (GLint location, GLsizei count, GLboolean transpose, const void *values, struct gl_context *, struct gl_shader_program *, GLuint cols, GLuint rows, enum glsl_base_type basicType)
void _mesa_get_uniform (struct gl_context *ctx, GLuint program, GLint location, GLsizei bufSize, enum glsl_base_type returnType, GLvoid *paramsOut)
void _mesa_uniform_attach_driver_storage (struct gl_uniform_storage *, unsigned element_stride, unsigned vector_stride, enum gl_uniform_driver_format format, void *data)
Connect a piece of driver storage with a part of a uniform.
void _mesa_uniform_detach_all_driver_storage (struct gl_uniform_storage *uni)
Sever all connections with all pieces of driver storage for all uniforms.
void _mesa_propagate_uniforms_to_driver_storage (struct gl_uniform_storage *uni, unsigned array_index, unsigned count)
void _mesa_update_shader_textures_used (struct gl_shader_program *shProg, struct gl_program *prog)
XXX things to do:
bool _mesa_sampler_uniforms_are_valid (const struct gl_shader_program *shProg, char *errMsg, size_t errMsgLength)
bool _mesa_sampler_uniforms_pipeline_are_valid (struct gl_pipeline_object *)
const struct gl_program_parameter * get_uniform_parameter (struct gl_shader_program *shProg, GLint index)
Function Documentation
_mesa_get_uniform()
void _mesa_get_uniform (struct gl_context * ctx, GLuint program, GLint location, GLsizei bufSize, enum glsl_base_type returnType, GLvoid * paramsOut)
Referenced by _mesa_GetnUniformdvARB(), _mesa_GetnUniformfvARB(), _mesa_GetnUniformi64vARB(), _mesa_GetnUniformivARB(), _mesa_GetnUniformui64vARB(), and _mesa_GetnUniformuivARB().
_mesa_GetActiveAtomicCounterBufferiv()
void GLAPIENTRY _mesa_GetActiveAtomicCounterBufferiv (GLuint program, GLuint bufferIndex, GLenum pname, GLint * params)
References _mesa_error(), _mesa_lookup_shader_program_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and mesa_bufferiv().
_mesa_GetActiveUniform()
void GLAPIENTRY _mesa_GetActiveUniform (GLuint , GLuint , GLsizei , GLsizei * , GLint * , GLenum * , GLcharARB *)
_mesa_GetActiveUniformBlockiv()
void GLAPIENTRY _mesa_GetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint * params)
References _mesa_error(), _mesa_lookup_shader_program_err(), GET_CURRENT_CONTEXT, GLAPIENTRY, and mesa_bufferiv().
_mesa_GetActiveUniformBlockName()
void GLAPIENTRY _mesa_GetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformBlockName)
References _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetActiveUniformName()
void GLAPIENTRY _mesa_GetActiveUniformName (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformName)
References _mesa_error(), _mesa_get_program_resource_name(), _mesa_lookup_shader_program_err(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetActiveUniformsiv()
void GLAPIENTRY _mesa_GetActiveUniformsiv (GLuint program, GLsizei uniformCount, const GLuint * uniformIndices, GLenum pname, GLint * params)
_mesa_GetnUniformdvARB()
void GLAPIENTRY _mesa_GetnUniformdvARB (GLuint , GLint , GLsizei , GLdouble *)
References _mesa_get_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetUniformdv().
_mesa_GetnUniformfvARB()
void GLAPIENTRY _mesa_GetnUniformfvARB (GLuint , GLint , GLsizei , GLfloat *)
References _mesa_get_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetUniformfv().
_mesa_GetnUniformi64vARB()
void GLAPIENTRY _mesa_GetnUniformi64vARB (GLuint , GLint , GLsizei , GLint64 *)
References _mesa_get_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetUniformi64vARB().
_mesa_GetnUniformivARB()
void GLAPIENTRY _mesa_GetnUniformivARB (GLuint , GLint , GLsizei , GLint *)
References _mesa_get_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetUniformiv().
_mesa_GetnUniformui64vARB()
void GLAPIENTRY _mesa_GetnUniformui64vARB (GLuint , GLint , GLsizei , GLuint64 *)
References _mesa_get_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetUniformui64vARB().
_mesa_GetnUniformuivARB()
void GLAPIENTRY _mesa_GetnUniformuivARB (GLuint , GLint , GLsizei , GLuint *)
References _mesa_get_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_GetUniformuiv().
_mesa_GetUniformBlockIndex()
GLuint GLAPIENTRY _mesa_GetUniformBlockIndex (GLuint program, const GLchar * uniformBlockName)
References _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_name(), _mesa_program_resource_index(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetUniformdv()
void GLAPIENTRY _mesa_GetUniformdv (GLuint , GLint , GLdouble *)
References _mesa_GetnUniformdvARB(), and GLAPIENTRY.
_mesa_GetUniformfv()
void GLAPIENTRY _mesa_GetUniformfv (GLuint , GLint , GLfloat *)
References _mesa_GetnUniformfvARB(), and GLAPIENTRY.
_mesa_GetUniformi64vARB()
void GLAPIENTRY _mesa_GetUniformi64vARB (GLuint , GLint , GLint64 *)
References _mesa_GetnUniformi64vARB(), and GLAPIENTRY.
_mesa_GetUniformIndices()
void GLAPIENTRY _mesa_GetUniformIndices (GLuint program, GLsizei uniformCount, const GLchar *const * uniformNames, GLuint * uniformIndices)
References _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_find_name(), _mesa_program_resource_index(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_GetUniformiv()
void GLAPIENTRY _mesa_GetUniformiv (GLuint , GLint , GLint *)
References _mesa_GetnUniformivARB(), and GLAPIENTRY.
_mesa_GetUniformLocation()
GLint GLAPIENTRY _mesa_GetUniformLocation (GLuint , const GLcharARB *)
References _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_program_resource_location(), gl_shader_program::data, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, linking_failure, and gl_shader_program_data::LinkStatus.
_mesa_GetUniformui64vARB()
void GLAPIENTRY _mesa_GetUniformui64vARB (GLuint , GLint , GLuint64 *)
References _mesa_GetnUniformui64vARB(), and GLAPIENTRY.
_mesa_GetUniformuiv()
void GLAPIENTRY _mesa_GetUniformuiv (GLuint , GLint , GLuint *)
References _mesa_GetnUniformuivARB(), and GLAPIENTRY.
_mesa_ProgramUniform1d()
void GLAPIENTRY _mesa_ProgramUniform1d (GLuint program, GLint , GLdouble)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1dv()
void GLAPIENTRY _mesa_ProgramUniform1dv (GLuint program, GLint , GLsizei , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1f()
void GLAPIENTRY _mesa_ProgramUniform1f (GLuint program, GLint , GLfloat)
Same as above with direct state access.
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1fv()
void GLAPIENTRY _mesa_ProgramUniform1fv (GLuint program, GLint , GLsizei , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1i()
void GLAPIENTRY _mesa_ProgramUniform1i (GLuint program, GLint , GLint)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1i64ARB()
void GLAPIENTRY _mesa_ProgramUniform1i64ARB (GLuint , GLint , GLint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1i64vARB()
void GLAPIENTRY _mesa_ProgramUniform1i64vARB (GLuint , GLint , GLsizei , const GLint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1iv()
void GLAPIENTRY _mesa_ProgramUniform1iv (GLuint program, GLint , GLsizei , const GLint *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1ui()
void GLAPIENTRY _mesa_ProgramUniform1ui (GLuint program, GLint location, GLuint v0)
Same as above with direct state access.
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1ui64ARB()
void GLAPIENTRY _mesa_ProgramUniform1ui64ARB (GLuint , GLint , GLuint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1ui64vARB()
void GLAPIENTRY _mesa_ProgramUniform1ui64vARB (GLuint , GLint , GLsizei , const GLuint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform1uiv()
void GLAPIENTRY _mesa_ProgramUniform1uiv (GLuint program, GLint location, GLsizei count, const GLuint * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2d()
void GLAPIENTRY _mesa_ProgramUniform2d (GLuint program, GLint , GLdouble , GLdouble)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2dv()
void GLAPIENTRY _mesa_ProgramUniform2dv (GLuint program, GLint , GLsizei , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2f()
void GLAPIENTRY _mesa_ProgramUniform2f (GLuint program, GLint , GLfloat , GLfloat)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2fv()
void GLAPIENTRY _mesa_ProgramUniform2fv (GLuint program, GLint , GLsizei , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2i()
void GLAPIENTRY _mesa_ProgramUniform2i (GLuint program, GLint , GLint , GLint)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2i64ARB()
void GLAPIENTRY _mesa_ProgramUniform2i64ARB (GLuint , GLint , GLint64 , GLint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2i64vARB()
void GLAPIENTRY _mesa_ProgramUniform2i64vARB (GLuint , GLint , GLsizei , const GLint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2iv()
void GLAPIENTRY _mesa_ProgramUniform2iv (GLuint program, GLint , GLsizei , const GLint *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2ui()
void GLAPIENTRY _mesa_ProgramUniform2ui (GLuint program, GLint location, GLuint v0, GLuint v1)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_ProgramUniform2ui64ARB()
void GLAPIENTRY _mesa_ProgramUniform2ui64ARB (GLuint , GLint , GLuint64 , GLuint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2ui64vARB()
void GLAPIENTRY _mesa_ProgramUniform2ui64vARB (GLuint , GLint , GLsizei , const GLuint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform2uiv()
void GLAPIENTRY _mesa_ProgramUniform2uiv (GLuint program, GLint location, GLsizei count, const GLuint * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3d()
void GLAPIENTRY _mesa_ProgramUniform3d (GLuint program, GLint , GLdouble , GLdouble , GLdouble)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3dv()
void GLAPIENTRY _mesa_ProgramUniform3dv (GLuint program, GLint , GLsizei , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3f()
void GLAPIENTRY _mesa_ProgramUniform3f (GLuint program, GLint , GLfloat , GLfloat , GLfloat)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3fv()
void GLAPIENTRY _mesa_ProgramUniform3fv (GLuint program, GLint , GLsizei , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3i()
void GLAPIENTRY _mesa_ProgramUniform3i (GLuint program, GLint , GLint , GLint , GLint)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3i64ARB()
void GLAPIENTRY _mesa_ProgramUniform3i64ARB (GLuint , GLint , GLint64 , GLint64 , GLint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3i64vARB()
void GLAPIENTRY _mesa_ProgramUniform3i64vARB (GLuint , GLint , GLsizei , const GLint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3iv()
void GLAPIENTRY _mesa_ProgramUniform3iv (GLuint program, GLint , GLsizei , const GLint *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3ui()
void GLAPIENTRY _mesa_ProgramUniform3ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_ProgramUniform3ui64ARB()
void GLAPIENTRY _mesa_ProgramUniform3ui64ARB (GLuint , GLint , GLuint64 , GLuint64 , GLuint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3ui64vARB()
void GLAPIENTRY _mesa_ProgramUniform3ui64vARB (GLuint , GLint , GLsizei , const GLuint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform3uiv()
void GLAPIENTRY _mesa_ProgramUniform3uiv (GLuint program, GLint location, GLsizei count, const GLuint * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4d()
void GLAPIENTRY _mesa_ProgramUniform4d (GLuint program, GLint , GLdouble , GLdouble , GLdouble , GLdouble)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4dv()
void GLAPIENTRY _mesa_ProgramUniform4dv (GLuint program, GLint , GLsizei , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4f()
void GLAPIENTRY _mesa_ProgramUniform4f (GLuint program, GLint , GLfloat , GLfloat , GLfloat , GLfloat)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4fv()
void GLAPIENTRY _mesa_ProgramUniform4fv (GLuint program, GLint , GLsizei , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4i()
void GLAPIENTRY _mesa_ProgramUniform4i (GLuint program, GLint , GLint , GLint , GLint , GLint)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4i64ARB()
void GLAPIENTRY _mesa_ProgramUniform4i64ARB (GLuint , GLint , GLint64 , GLint64 , GLint64 , GLint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4i64vARB()
void GLAPIENTRY _mesa_ProgramUniform4i64vARB (GLuint , GLint , GLsizei , const GLint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4iv()
void GLAPIENTRY _mesa_ProgramUniform4iv (GLuint program, GLint , GLsizei , const GLint *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4ui()
void GLAPIENTRY _mesa_ProgramUniform4ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_ProgramUniform4ui64ARB()
void GLAPIENTRY _mesa_ProgramUniform4ui64ARB (GLuint , GLint , GLuint64 , GLuint64 , GLuint64 , GLuint64)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniform4ui64vARB()
void GLAPIENTRY _mesa_ProgramUniform4ui64vARB (GLuint , GLint , GLsizei , const GLuint64 *)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), and GET_CURRENT_CONTEXT.
_mesa_ProgramUniform4uiv()
void GLAPIENTRY _mesa_ProgramUniform4uiv (GLuint program, GLint location, GLsizei count, const GLuint * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix2dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix2dv (GLuint program, GLint , GLsizei , GLboolean , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix2fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix2fv (GLuint program, GLint , GLsizei , GLboolean , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix2x3dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix2x3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix2x3fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Same as above with direct state access.
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix2x4dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix2x4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix2x4fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix3dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix3dv (GLuint program, GLint , GLsizei , GLboolean , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix3fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix3fv (GLuint program, GLint , GLsizei , GLboolean , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix3x2dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix3x2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix3x2fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix3x4dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix3x4dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix3x4fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix4dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix4dv (GLuint program, GLint , GLsizei , GLboolean , const GLdouble *)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix4fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix4fv (GLuint program, GLint , GLsizei , GLboolean , const GLfloat *)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix4x2dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix4x2dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix4x2fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix4x3dv()
void GLAPIENTRY _mesa_ProgramUniformMatrix4x3dv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_ProgramUniformMatrix4x3fv()
void GLAPIENTRY _mesa_ProgramUniformMatrix4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_lookup_shader_program_err(), _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_propagate_uniforms_to_driver_storage()
void _mesa_propagate_uniforms_to_driver_storage (struct gl_uniform_storage * uni, unsigned array_index, unsigned count)
Referenced by _mesa_shader_write_subroutine_index().
_mesa_sampler_uniforms_are_valid()
bool _mesa_sampler_uniforms_are_valid (const struct gl_shader_program * shProg, char * errMsg, size_t errMsgLength)
Referenced by _mesa_valid_to_render(), and validate_shader_program().
_mesa_sampler_uniforms_pipeline_are_valid()
bool _mesa_sampler_uniforms_pipeline_are_valid (struct gl_pipeline_object *)
Referenced by _mesa_validate_program_pipeline().
_mesa_ShaderStorageBlockBinding()
void GLAPIENTRY _mesa_ShaderStorageBlockBinding (GLuint program, GLuint shaderStorageBlockIndex, GLuint shaderStorageBlockBinding)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_uniform_block::Binding, gl_shader_program::data, FLUSH_VERTICES, GET_CURRENT_CONTEXT, gl_shader_program_data::NumShaderStorageBlocks, and gl_shader_program_data::ShaderStorageBlocks.
_mesa_uniform()
void _mesa_uniform (GLint location, GLsizei count, const GLvoid * values, struct gl_context * , struct gl_shader_program * , enum glsl_base_type basicType, unsigned src_components)
Referenced by _mesa_ProgramUniform1d(), _mesa_ProgramUniform1dv(), _mesa_ProgramUniform1f(), _mesa_ProgramUniform1fv(), _mesa_ProgramUniform1i(), _mesa_ProgramUniform1i64ARB(), _mesa_ProgramUniform1i64vARB(), _mesa_ProgramUniform1iv(), _mesa_ProgramUniform1ui(), _mesa_ProgramUniform1ui64ARB(), _mesa_ProgramUniform1ui64vARB(), _mesa_ProgramUniform1uiv(), _mesa_ProgramUniform2d(), _mesa_ProgramUniform2dv(), _mesa_ProgramUniform2f(), _mesa_ProgramUniform2fv(), _mesa_ProgramUniform2i(), _mesa_ProgramUniform2i64ARB(), _mesa_ProgramUniform2i64vARB(), _mesa_ProgramUniform2iv(), _mesa_ProgramUniform2ui(), _mesa_ProgramUniform2ui64ARB(), _mesa_ProgramUniform2ui64vARB(), _mesa_ProgramUniform2uiv(), _mesa_ProgramUniform3d(), _mesa_ProgramUniform3dv(), _mesa_ProgramUniform3f(), _mesa_ProgramUniform3fv(), _mesa_ProgramUniform3i(), _mesa_ProgramUniform3i64ARB(), _mesa_ProgramUniform3i64vARB(), _mesa_ProgramUniform3iv(), _mesa_ProgramUniform3ui(), _mesa_ProgramUniform3ui64ARB(), _mesa_ProgramUniform3ui64vARB(), _mesa_ProgramUniform3uiv(), _mesa_ProgramUniform4d(), _mesa_ProgramUniform4dv(), _mesa_ProgramUniform4f(), _mesa_ProgramUniform4fv(), _mesa_ProgramUniform4i(), _mesa_ProgramUniform4i64ARB(), _mesa_ProgramUniform4i64vARB(), _mesa_ProgramUniform4iv(), _mesa_ProgramUniform4ui(), _mesa_ProgramUniform4ui64ARB(), _mesa_ProgramUniform4ui64vARB(), _mesa_ProgramUniform4uiv(), _mesa_Uniform1d(), _mesa_Uniform1dv(), _mesa_Uniform1f(), _mesa_Uniform1fv(), _mesa_Uniform1i(), _mesa_Uniform1i64ARB(), _mesa_Uniform1i64vARB(), _mesa_Uniform1iv(), _mesa_Uniform1ui(), _mesa_Uniform1ui64ARB(), _mesa_Uniform1ui64vARB(), _mesa_Uniform1uiv(), _mesa_Uniform2d(), _mesa_Uniform2dv(), _mesa_Uniform2f(), _mesa_Uniform2fv(), _mesa_Uniform2i(), _mesa_Uniform2i64ARB(), _mesa_Uniform2i64vARB(), _mesa_Uniform2iv(), _mesa_Uniform2ui(), _mesa_Uniform2ui64ARB(), _mesa_Uniform2ui64vARB(), _mesa_Uniform2uiv(), _mesa_Uniform3d(), _mesa_Uniform3dv(), _mesa_Uniform3f(), _mesa_Uniform3fv(), _mesa_Uniform3i(), _mesa_Uniform3i64ARB(), _mesa_Uniform3i64vARB(), _mesa_Uniform3iv(), _mesa_Uniform3ui(), _mesa_Uniform3ui64ARB(), _mesa_Uniform3ui64vARB(), _mesa_Uniform3uiv(), _mesa_Uniform4d(), _mesa_Uniform4dv(), _mesa_Uniform4f(), _mesa_Uniform4fv(), _mesa_Uniform4i(), _mesa_Uniform4i64ARB(), _mesa_Uniform4i64vARB(), _mesa_Uniform4iv(), _mesa_Uniform4ui(), _mesa_Uniform4ui64ARB(), _mesa_Uniform4ui64vARB(), and _mesa_Uniform4uiv().
_mesa_Uniform1d()
void GLAPIENTRY _mesa_Uniform1d (GLint , GLdouble)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1dv()
void GLAPIENTRY _mesa_Uniform1dv (GLint , GLsizei , const GLdouble *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1f()
void GLAPIENTRY _mesa_Uniform1f (GLint , GLfloat)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1fv()
void GLAPIENTRY _mesa_Uniform1fv (GLint , GLsizei , const GLfloat *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1i()
void GLAPIENTRY _mesa_Uniform1i (GLint , GLint)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1i64ARB()
void GLAPIENTRY _mesa_Uniform1i64ARB (GLint , GLint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1i64vARB()
void GLAPIENTRY _mesa_Uniform1i64vARB (GLint , GLsizei , const GLint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1iv()
void GLAPIENTRY _mesa_Uniform1iv (GLint , GLsizei , const GLint *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1ui()
void GLAPIENTRY _mesa_Uniform1ui (GLint location, GLuint v0)
OpenGL 3.0 GLuint-valued functions.
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1ui64ARB()
void GLAPIENTRY _mesa_Uniform1ui64ARB (GLint , GLuint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1ui64vARB()
void GLAPIENTRY _mesa_Uniform1ui64vARB (GLint , GLsizei , const GLuint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform1uiv()
void GLAPIENTRY _mesa_Uniform1uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2d()
void GLAPIENTRY _mesa_Uniform2d (GLint , GLdouble , GLdouble)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2dv()
void GLAPIENTRY _mesa_Uniform2dv (GLint , GLsizei , const GLdouble *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2f()
void GLAPIENTRY _mesa_Uniform2f (GLint , GLfloat , GLfloat)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2fv()
void GLAPIENTRY _mesa_Uniform2fv (GLint , GLsizei , const GLfloat *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2i()
void GLAPIENTRY _mesa_Uniform2i (GLint , GLint , GLint)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2i64ARB()
void GLAPIENTRY _mesa_Uniform2i64ARB (GLint , GLint64 , GLint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2i64vARB()
void GLAPIENTRY _mesa_Uniform2i64vARB (GLint , GLsizei , const GLint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2iv()
void GLAPIENTRY _mesa_Uniform2iv (GLint , GLsizei , const GLint *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2ui()
void GLAPIENTRY _mesa_Uniform2ui (GLint location, GLuint v0, GLuint v1)
References _mesa_uniform(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_Uniform2ui64ARB()
void GLAPIENTRY _mesa_Uniform2ui64ARB (GLint , GLuint64 , GLuint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2ui64vARB()
void GLAPIENTRY _mesa_Uniform2ui64vARB (GLint , GLsizei , const GLuint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform2uiv()
void GLAPIENTRY _mesa_Uniform2uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3d()
void GLAPIENTRY _mesa_Uniform3d (GLint , GLdouble , GLdouble , GLdouble)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3dv()
void GLAPIENTRY _mesa_Uniform3dv (GLint , GLsizei , const GLdouble *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3f()
void GLAPIENTRY _mesa_Uniform3f (GLint , GLfloat , GLfloat , GLfloat)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3fv()
void GLAPIENTRY _mesa_Uniform3fv (GLint , GLsizei , const GLfloat *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3i()
void GLAPIENTRY _mesa_Uniform3i (GLint , GLint , GLint , GLint)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3i64ARB()
void GLAPIENTRY _mesa_Uniform3i64ARB (GLint , GLint64 , GLint64 , GLint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3i64vARB()
void GLAPIENTRY _mesa_Uniform3i64vARB (GLint , GLsizei , const GLint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3iv()
void GLAPIENTRY _mesa_Uniform3iv (GLint , GLsizei , const GLint *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3ui()
void GLAPIENTRY _mesa_Uniform3ui (GLint location, GLuint v0, GLuint v1, GLuint v2)
References _mesa_uniform(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_Uniform3ui64ARB()
void GLAPIENTRY _mesa_Uniform3ui64ARB (GLint , GLuint64 , GLuint64 , GLuint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3ui64vARB()
void GLAPIENTRY _mesa_Uniform3ui64vARB (GLint , GLsizei , const GLuint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform3uiv()
void GLAPIENTRY _mesa_Uniform3uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4d()
void GLAPIENTRY _mesa_Uniform4d (GLint , GLdouble , GLdouble , GLdouble , GLdouble)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4dv()
void GLAPIENTRY _mesa_Uniform4dv (GLint , GLsizei , const GLdouble *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4f()
void GLAPIENTRY _mesa_Uniform4f (GLint , GLfloat , GLfloat , GLfloat , GLfloat)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4fv()
void GLAPIENTRY _mesa_Uniform4fv (GLint , GLsizei , const GLfloat *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4i()
void GLAPIENTRY _mesa_Uniform4i (GLint , GLint , GLint , GLint , GLint)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4i64ARB()
void GLAPIENTRY _mesa_Uniform4i64ARB (GLint , GLint64 , GLint64 , GLint64 , GLint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4i64vARB()
void GLAPIENTRY _mesa_Uniform4i64vARB (GLint , GLsizei , const GLint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4iv()
void GLAPIENTRY _mesa_Uniform4iv (GLint , GLsizei , const GLint *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4ui()
void GLAPIENTRY _mesa_Uniform4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
References _mesa_uniform(), GET_CURRENT_CONTEXT, GLAPIENTRY, and GLuint.
_mesa_Uniform4ui64ARB()
void GLAPIENTRY _mesa_Uniform4ui64ARB (GLint , GLuint64 , GLuint64 , GLuint64 , GLuint64)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4ui64vARB()
void GLAPIENTRY _mesa_Uniform4ui64vARB (GLint , GLsizei , const GLuint64 *)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_Uniform4uiv()
void GLAPIENTRY _mesa_Uniform4uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_uniform_attach_driver_storage()
void _mesa_uniform_attach_driver_storage (struct gl_uniform_storage * uni, unsigned element_stride, unsigned vector_stride, enum gl_uniform_driver_format format, void * data)
Connect a piece of driver storage with a part of a uniform.
Parameters
uni The uniform with which the storage will be associated
element_stride Byte-stride between array elements.
See also
gl_uniform_driver_storage::element_stride.
Parameters
vector_stride Byte-stride between vectors (in a matrix).
See also
gl_uniform_driver_storage::vector_stride.
Parameters
format Conversion from native format to driver format required by the driver.
data Location to dump the data.
_mesa_uniform_detach_all_driver_storage()
void _mesa_uniform_detach_all_driver_storage (struct gl_uniform_storage * uni)
Sever all connections with all pieces of driver storage for all uniforms.
Warning
This function does not release any of the data pointers previously passed in to _mesa_uniform_attach_driver_stoarge.
References GLAPIENTRY.
Referenced by _mesa_clear_shader_program_data().
_mesa_uniform_matrix()
void _mesa_uniform_matrix (GLint location, GLsizei count, GLboolean transpose, const void * values, struct gl_context * , struct gl_shader_program * , GLuint cols, GLuint rows, enum glsl_base_type basicType)
Referenced by _mesa_ProgramUniformMatrix2dv(), _mesa_ProgramUniformMatrix2fv(), _mesa_ProgramUniformMatrix2x3dv(), _mesa_ProgramUniformMatrix2x3fv(), _mesa_ProgramUniformMatrix2x4dv(), _mesa_ProgramUniformMatrix2x4fv(), _mesa_ProgramUniformMatrix3dv(), _mesa_ProgramUniformMatrix3fv(), _mesa_ProgramUniformMatrix3x2dv(), _mesa_ProgramUniformMatrix3x2fv(), _mesa_ProgramUniformMatrix3x4dv(), _mesa_ProgramUniformMatrix3x4fv(), _mesa_ProgramUniformMatrix4dv(), _mesa_ProgramUniformMatrix4fv(), _mesa_ProgramUniformMatrix4x2dv(), _mesa_ProgramUniformMatrix4x2fv(), _mesa_ProgramUniformMatrix4x3dv(), _mesa_ProgramUniformMatrix4x3fv(), _mesa_UniformMatrix2dv(), _mesa_UniformMatrix2fv(), _mesa_UniformMatrix2x3dv(), _mesa_UniformMatrix2x3fv(), _mesa_UniformMatrix2x4dv(), _mesa_UniformMatrix2x4fv(), _mesa_UniformMatrix3dv(), _mesa_UniformMatrix3fv(), _mesa_UniformMatrix3x2dv(), _mesa_UniformMatrix3x2fv(), _mesa_UniformMatrix3x4dv(), _mesa_UniformMatrix3x4fv(), _mesa_UniformMatrix4dv(), _mesa_UniformMatrix4fv(), _mesa_UniformMatrix4x2dv(), _mesa_UniformMatrix4x2fv(), _mesa_UniformMatrix4x3dv(), and _mesa_UniformMatrix4x3fv().
_mesa_UniformBlockBinding()
void GLAPIENTRY _mesa_UniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_uniform_block::Binding, gl_shader_program::data, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, gl_shader_program_data::NumUniformBlocks, and gl_shader_program_data::UniformBlocks.
_mesa_UniformMatrix2dv()
void GLAPIENTRY _mesa_UniformMatrix2dv (GLint , GLsizei , GLboolean , const GLdouble *)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix2fv()
void GLAPIENTRY _mesa_UniformMatrix2fv (GLint , GLsizei , GLboolean , const GLfloat *)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix2x3dv()
void GLAPIENTRY _mesa_UniformMatrix2x3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix2x3fv()
void GLAPIENTRY _mesa_UniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Non-square UniformMatrix are OpenGL 2.1.
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix2x4dv()
void GLAPIENTRY _mesa_UniformMatrix2x4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix2x4fv()
void GLAPIENTRY _mesa_UniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix3dv()
void GLAPIENTRY _mesa_UniformMatrix3dv (GLint , GLsizei , GLboolean , const GLdouble *)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix3fv()
void GLAPIENTRY _mesa_UniformMatrix3fv (GLint , GLsizei , GLboolean , const GLfloat *)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix3x2dv()
void GLAPIENTRY _mesa_UniformMatrix3x2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix3x2fv()
void GLAPIENTRY _mesa_UniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix3x4dv()
void GLAPIENTRY _mesa_UniformMatrix3x4dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix3x4fv()
void GLAPIENTRY _mesa_UniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix4dv()
void GLAPIENTRY _mesa_UniformMatrix4dv (GLint , GLsizei , GLboolean , const GLdouble *)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix4fv()
void GLAPIENTRY _mesa_UniformMatrix4fv (GLint , GLsizei , GLboolean , const GLfloat *)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix4x2dv()
void GLAPIENTRY _mesa_UniformMatrix4x2dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix4x2fv()
void GLAPIENTRY _mesa_UniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix4x3dv()
void GLAPIENTRY _mesa_UniformMatrix4x3dv (GLint location, GLsizei count, GLboolean transpose, const GLdouble * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_UniformMatrix4x3fv()
void GLAPIENTRY _mesa_UniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_update_shader_textures_used()
void _mesa_update_shader_textures_used (struct gl_shader_program * shProg, struct gl_program * prog)
XXX things to do:
Check that the right error code is generated for all _mesa_error() calls.
Insert FLUSH_VERTICES calls in various places Update the vertex/fragment program's TexturesUsed array.
This needs to be called after glUniform(set sampler var) is called. A call to glUniform(samplerVar, value) causes a sampler to point to a particular texture unit. We know the sampler's texture target (1D/2D/3D/etc) from compile time but the sampler's texture unit is set by glUniform() calls.
So, scan the program->SamplerUnits[] and program->SamplerTargets[] information to update the prog->TexturesUsed[] values. Each value of TexturesUsed[unit] is one of zero, TEXTURE_1D_INDEX, TEXTURE_2D_INDEX, TEXTURE_3D_INDEX, etc. We'll use that info for state validation before rendering.
References GLuint, NUM_TEXTURE_TARGETS, gl_program::SamplersUsed, gl_shader_program::SamplersValidated, gl_program::SamplerUnits, gl_program::sh, and gl_program::TexturesUsed.
get_uniform_parameter()
const struct gl_program_parameter* get_uniform_parameter (struct gl_shader_program * shProg, GLint index)