Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
varray.c File Reference
#include <stdio.h>
#include <inttypes.h>
#include "glheader.h"
#include "imports.h"
#include "bufferobj.h"
#include "context.h"
#include "enable.h"
#include "enums.h"
#include "hash.h"
#include "image.h"
#include "macros.h"
#include "mtypes.h"
#include "varray.h"
#include "arrayobj.h"
#include "main/dispatch.h"
Macros
#define BGRA_OR_4 5
Used to do error checking for GL_EXT_vertex_array_bgra.
#define BOOL_BIT (1 << 0)
Used to indicate which GL datatypes are accepted by each of the glVertex/Color/Attrib/EtcPointer() functions.
#define BYTE_BIT (1 << 1)
#define UNSIGNED_BYTE_BIT (1 << 2)
#define SHORT_BIT (1 << 3)
#define UNSIGNED_SHORT_BIT (1 << 4)
#define INT_BIT (1 << 5)
#define UNSIGNED_INT_BIT (1 << 6)
#define HALF_BIT (1 << 7)
#define FLOAT_BIT (1 << 8)
#define DOUBLE_BIT (1 << 9)
#define FIXED_ES_BIT (1 << 10)
#define FIXED_GL_BIT (1 << 11)
#define UNSIGNED_INT_2_10_10_10_REV_BIT (1 << 12)
#define INT_2_10_10_10_REV_BIT (1 << 13)
#define UNSIGNED_INT_10F_11F_11F_REV_BIT (1 << 14)
#define ALL_TYPE_BITS ((1 << 15) - 1)
#define ATTRIB_FORMAT_TYPES_MASK
#define ATTRIB_IFORMAT_TYPES_MASK
#define ATTRIB_LFORMAT_TYPES_MASK DOUBLE_BIT
Functions
static GLbitfield type_to_bit (const struct gl_context *ctx, GLenum type)
Convert GL datatype enum into a <type>_BIT value seen above.
static void vertex_attrib_binding (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint attribIndex, GLuint bindingIndex)
Sets the BufferBindingIndex field for the vertex attribute given by attribIndex.
void _mesa_bind_vertex_buffer (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint index, struct gl_buffer_object *vbo, GLintptr offset, GLsizei stride)
Binds a buffer object to the vertex buffer binding point given by index, and sets the Offset and Stride fields.
static void vertex_binding_divisor (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint bindingIndex, GLuint divisor)
Sets the InstanceDivisor field in the vertex buffer binding point given by bindingIndex.
static GLbitfield get_legal_types_mask (const struct gl_context *ctx)
Examine the API profile and extensions to determine which types are legal for vertex arrays.
void _mesa_update_array_format (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint attrib, GLint size, GLenum type, GLenum format, GLboolean normalized, GLboolean integer, GLboolean doubles, GLuint relativeOffset)
static bool update_array_format (struct gl_context *ctx, const char *func, struct gl_vertex_array_object *vao, GLuint attrib, GLbitfield legalTypesMask, GLint sizeMin, GLint sizeMax, GLint size, GLenum type, GLboolean normalized, GLboolean integer, GLboolean doubles, GLuint relativeOffset)
Does error checking and updates the format in an attrib array.
static void update_array (struct gl_context *ctx, const char *func, GLuint attrib, GLbitfield legalTypesMask, GLint sizeMin, GLint sizeMax, GLint size, GLenum type, GLsizei stride, GLboolean normalized, GLboolean integer, GLboolean doubles, const GLvoid *ptr)
Do error checking and update state for glVertex/Color/TexCoord/...Pointer functions.
void GLAPIENTRY _mesa_VertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_NormalPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_ColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_FogCoordPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_IndexPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_SecondaryColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_TexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_EdgeFlagPointer (GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_PointSizePointerOES (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_VertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *ptr)
Set a generic vertex attribute array.
void GLAPIENTRY _mesa_VertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
GL_EXT_gpu_shader4 / GL 3.0.
void GLAPIENTRY _mesa_VertexAttribLPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void _mesa_enable_vertex_array_attrib (struct gl_context *ctx, struct gl_vertex_array_object *vao, unsigned attrib)
static void enable_vertex_array_attrib (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint index, const char *func)
void GLAPIENTRY _mesa_EnableVertexAttribArray (GLuint index)
void GLAPIENTRY _mesa_EnableVertexArrayAttrib (GLuint vaobj, GLuint index)
static void disable_vertex_array_attrib (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint index, const char *func)
void GLAPIENTRY _mesa_DisableVertexAttribArray (GLuint index)
void GLAPIENTRY _mesa_DisableVertexArrayAttrib (GLuint vaobj, GLuint index)
static GLuint get_vertex_array_attrib (struct gl_context *ctx, const struct gl_vertex_array_object *vao, GLuint index, GLenum pname, const char *caller)
Return info for a vertex attribute array (no alias with legacy vertex attributes (pos, normal, color, etc)).
static const GLfloat * get_current_attrib (struct gl_context *ctx, GLuint index, const char *function)
void GLAPIENTRY _mesa_GetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetVertexAttribdv (GLuint index, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetVertexAttribLdv (GLuint index, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetVertexAttribiv (GLuint index, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetVertexAttribIiv (GLuint index, GLenum pname, GLint *params)
GL 3.0.
void GLAPIENTRY _mesa_GetVertexAttribIuiv (GLuint index, GLenum pname, GLuint *params)
GL 3.0.
void GLAPIENTRY _mesa_GetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid **pointer)
void GLAPIENTRY _mesa_GetVertexArrayIndexediv (GLuint vaobj, GLuint index, GLenum pname, GLint *params)
ARB_direct_state_access.
void GLAPIENTRY _mesa_GetVertexArrayIndexed64iv (GLuint vaobj, GLuint index, GLenum pname, GLint64 *params)
void GLAPIENTRY _mesa_VertexPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_NormalPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_ColorPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_IndexPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_TexCoordPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_EdgeFlagPointerEXT (GLsizei stride, GLsizei count, const GLboolean *ptr)
void GLAPIENTRY _mesa_InterleavedArrays (GLenum format, GLsizei stride, const GLvoid *pointer)
void GLAPIENTRY _mesa_LockArraysEXT (GLint first, GLsizei count)
void GLAPIENTRY _mesa_UnlockArraysEXT (void)
void GLAPIENTRY _mesa_MultiDrawArrays (GLenum mode, const GLint *first, const GLsizei *count, GLsizei primcount)
void GLAPIENTRY _mesa_MultiModeDrawArraysIBM (const GLenum *mode, const GLint *first, const GLsizei *count, GLsizei primcount, GLint modestride)
void GLAPIENTRY _mesa_MultiModeDrawElementsIBM (const GLenum *mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount, GLint modestride)
void GLAPIENTRY _mesa_PrimitiveRestartIndex (GLuint index)
GL_NV_primitive_restart and GL 3.1.
void GLAPIENTRY _mesa_VertexAttribDivisor (GLuint index, GLuint divisor)
See GL_ARB_instanced_arrays.
unsigned _mesa_primitive_restart_index (const struct gl_context *ctx, GLenum ib_type)
static void vertex_array_vertex_buffer (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride, const char *func)
GL_ARB_vertex_attrib_binding.
void GLAPIENTRY _mesa_BindVertexBuffer (GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
void GLAPIENTRY _mesa_VertexArrayVertexBuffer (GLuint vaobj, GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
static void vertex_array_vertex_buffers (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides, const char *func)
void GLAPIENTRY _mesa_BindVertexBuffers (GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides)
void GLAPIENTRY _mesa_VertexArrayVertexBuffers (GLuint vaobj, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides)
static void vertex_attrib_format (GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLboolean integer, GLboolean doubles, GLbitfield legalTypes, GLsizei maxSize, GLuint relativeOffset, const char *func)
void GLAPIENTRY _mesa_VertexAttribFormat (GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexAttribIFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexAttribLFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
static void vertex_array_attrib_format (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLboolean integer, GLboolean doubles, GLbitfield legalTypes, GLsizei maxSize, GLuint relativeOffset, const char *func)
void GLAPIENTRY _mesa_VertexArrayAttribFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexArrayAttribIFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexArrayAttribLFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
static void vertex_array_attrib_binding (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint attribIndex, GLuint bindingIndex, const char *func)
void GLAPIENTRY _mesa_VertexAttribBinding (GLuint attribIndex, GLuint bindingIndex)
void GLAPIENTRY _mesa_VertexArrayAttribBinding (GLuint vaobj, GLuint attribIndex, GLuint bindingIndex)
static void vertex_array_binding_divisor (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint bindingIndex, GLuint divisor, const char *func)
void GLAPIENTRY _mesa_VertexBindingDivisor (GLuint bindingIndex, GLuint divisor)
void GLAPIENTRY _mesa_VertexArrayBindingDivisor (GLuint vaobj, GLuint bindingIndex, GLuint divisor)
void _mesa_copy_client_array (struct gl_context *ctx, struct gl_vertex_array *dst, struct gl_vertex_array *src)
Copy one client vertex array to another.
void _mesa_copy_vertex_attrib_array (struct gl_context *ctx, struct gl_array_attributes *dst, const struct gl_array_attributes *src)
void _mesa_copy_vertex_buffer_binding (struct gl_context *ctx, struct gl_vertex_buffer_binding *dst, const struct gl_vertex_buffer_binding *src)
void _mesa_print_arrays (struct gl_context *ctx)
Print current vertex object/array info.
void _mesa_init_varray (struct gl_context *ctx)
Initialize vertex array state for given context.
static void delete_arrayobj_cb (GLuint id, void *data, void *userData)
Callback for deleting an array object.
void _mesa_free_varray_data (struct gl_context *ctx)
Free vertex array state for given context.
Macro Definition Documentation
ALL_TYPE_BITS
#define ALL_TYPE_BITS ((1 << 15) - 1)
Referenced by get_legal_types_mask().
ATTRIB_FORMAT_TYPES_MASK
#define ATTRIB_FORMAT_TYPES_MASK
Value:
(BYTE_BIT | UNSIGNED_BYTE_BIT | \
                                  SHORT_BIT | UNSIGNED_SHORT_BIT | \
                                  INT_BIT | UNSIGNED_INT_BIT | \
                                  HALF_BIT | FLOAT_BIT | DOUBLE_BIT | \
                                  FIXED_GL_BIT | \
                                  UNSIGNED_INT_2_10_10_10_REV_BIT | \
                                  INT_2_10_10_10_REV_BIT | \
                                  UNSIGNED_INT_10F_11F_11F_REV_BIT)
Referenced by _mesa_VertexArrayAttribFormat(), and _mesa_VertexAttribFormat().
ATTRIB_IFORMAT_TYPES_MASK
#define ATTRIB_IFORMAT_TYPES_MASK
Value:
(BYTE_BIT | UNSIGNED_BYTE_BIT | \
                                   SHORT_BIT | UNSIGNED_SHORT_BIT | \
                                   INT_BIT | UNSIGNED_INT_BIT)
Referenced by _mesa_VertexArrayAttribIFormat(), and _mesa_VertexAttribIFormat().
ATTRIB_LFORMAT_TYPES_MASK
#define ATTRIB_LFORMAT_TYPES_MASK DOUBLE_BIT
Referenced by _mesa_VertexArrayAttribLFormat(), and _mesa_VertexAttribLFormat().
BGRA_OR_4
#define BGRA_OR_4 5
Used to do error checking for GL_EXT_vertex_array_bgra.
Referenced by _mesa_ColorPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexArrayAttribFormat(), _mesa_VertexAttribFormat(), _mesa_VertexAttribPointer(), and update_array_format().
BOOL_BIT
#define BOOL_BIT (1 << 0)
Used to indicate which GL datatypes are accepted by each of the glVertex/Color/Attrib/EtcPointer() functions.
Referenced by type_to_bit().
BYTE_BIT
#define BYTE_BIT (1 << 1)
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), and type_to_bit().
DOUBLE_BIT
#define DOUBLE_BIT (1 << 9)
Referenced by _mesa_ColorPointer(), _mesa_FogCoordPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribLPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), get_legal_types_mask(), and type_to_bit().
FIXED_ES_BIT
#define FIXED_ES_BIT (1 << 10)
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_PointSizePointerOES(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), get_legal_types_mask(), and type_to_bit().
FIXED_GL_BIT
#define FIXED_GL_BIT (1 << 11)
Referenced by _mesa_VertexAttribPointer(), get_legal_types_mask(), and type_to_bit().
FLOAT_BIT
#define FLOAT_BIT (1 << 8)
Referenced by _mesa_ColorPointer(), _mesa_FogCoordPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_PointSizePointerOES(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), and type_to_bit().
HALF_BIT
#define HALF_BIT (1 << 7)
Referenced by _mesa_ColorPointer(), _mesa_FogCoordPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), get_legal_types_mask(), and type_to_bit().
INT_2_10_10_10_REV_BIT
#define INT_2_10_10_10_REV_BIT (1 << 13)
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), get_legal_types_mask(), and type_to_bit().
INT_BIT
#define INT_BIT (1 << 5)
Referenced by _mesa_ColorPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), get_legal_types_mask(), and type_to_bit().
SHORT_BIT
#define SHORT_BIT (1 << 3)
Referenced by _mesa_ColorPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), and type_to_bit().
UNSIGNED_BYTE_BIT
#define UNSIGNED_BYTE_BIT (1 << 2)
Referenced by _mesa_ColorPointer(), _mesa_EdgeFlagPointer(), _mesa_IndexPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), and type_to_bit().
UNSIGNED_INT_10F_11F_11F_REV_BIT
#define UNSIGNED_INT_10F_11F_11F_REV_BIT (1 << 14)
Referenced by _mesa_VertexAttribPointer(), get_legal_types_mask(), and type_to_bit().
UNSIGNED_INT_2_10_10_10_REV_BIT
#define UNSIGNED_INT_2_10_10_10_REV_BIT (1 << 12)
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), get_legal_types_mask(), and type_to_bit().
UNSIGNED_INT_BIT
#define UNSIGNED_INT_BIT (1 << 6)
Referenced by _mesa_ColorPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), get_legal_types_mask(), and type_to_bit().
UNSIGNED_SHORT_BIT
#define UNSIGNED_SHORT_BIT (1 << 4)
Referenced by _mesa_ColorPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), and type_to_bit().
Function Documentation
_mesa_bind_vertex_buffer()
void _mesa_bind_vertex_buffer (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint index, struct gl_buffer_object * vbo, GLintptr offset, GLsizei stride)
Binds a buffer object to the vertex buffer binding point given by index, and sets the Offset and Stride fields.
References gl_vertex_buffer_binding::_BoundArrays, _mesa_is_bufferobj(), _mesa_reference_buffer_object(), _NEW_ARRAY, gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, FLUSH_VERTICES, gl_vertex_array_object::NewArrays, gl_vertex_buffer_binding::Offset, gl_vertex_buffer_binding::Stride, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by _mesa_attr_zero_aliases_vertex(), unbind(), update_array(), vertex_array_vertex_buffer(), and vertex_array_vertex_buffers().
_mesa_BindVertexBuffer()
void GLAPIENTRY _mesa_BindVertexBuffer (GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_vertex_buffer().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_BindVertexBuffers()
void GLAPIENTRY _mesa_BindVertexBuffers (GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizei * strides)
References _mesa_error(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_vertex_buffers().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_ColorPointer()
void GLAPIENTRY _mesa_ColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_ColorPointerEXT(), and _mesa_InterleavedArrays().
_mesa_ColorPointerEXT()
void GLAPIENTRY _mesa_ColorPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_ColorPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_copy_client_array()
void _mesa_copy_client_array (struct gl_context * ctx, struct gl_vertex_array * dst, struct gl_vertex_array * src)
Copy one client vertex array to another.
References gl_vertex_array::_ElementSize, _mesa_reference_buffer_object(), gl_vertex_array::BufferObj, gl_vertex_array::Doubles, gl_vertex_array::Format, gl_vertex_array::InstanceDivisor, gl_vertex_array::Integer, gl_vertex_array::Normalized, gl_vertex_array::Ptr, gl_vertex_array::Size, gl_vertex_array::StrideB, and gl_vertex_array::Type.
Referenced by _mesa_attr_zero_aliases_vertex(), and copy_array_object().
_mesa_copy_vertex_attrib_array()
void _mesa_copy_vertex_attrib_array (struct gl_context * ctx, struct gl_array_attributes * dst, const struct gl_array_attributes * src)
References gl_array_attributes::_ElementSize, gl_array_attributes::BufferBindingIndex, gl_array_attributes::Doubles, gl_array_attributes::Enabled, gl_array_attributes::Format, gl_array_attributes::Integer, gl_array_attributes::Normalized, gl_array_attributes::Ptr, gl_array_attributes::RelativeOffset, gl_array_attributes::Size, and gl_array_attributes::Type.
Referenced by _mesa_attr_zero_aliases_vertex(), and copy_array_object().
_mesa_copy_vertex_buffer_binding()
void _mesa_copy_vertex_buffer_binding (struct gl_context * ctx, struct gl_vertex_buffer_binding * dst, const struct gl_vertex_buffer_binding * src)
References gl_vertex_buffer_binding::_BoundArrays, _mesa_reference_buffer_object(), gl_vertex_buffer_binding::BufferObj, gl_vertex_buffer_binding::InstanceDivisor, gl_vertex_buffer_binding::Offset, and gl_vertex_buffer_binding::Stride.
Referenced by _mesa_attr_zero_aliases_vertex(), and copy_array_object().
_mesa_DisableVertexArrayAttrib()
void GLAPIENTRY _mesa_DisableVertexArrayAttrib (GLuint vaobj, GLuint index)
References _mesa_lookup_vao_err(), disable_vertex_array_attrib(), GET_CURRENT_CONTEXT, and GLuint.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DisableVertexAttribArray()
void GLAPIENTRY _mesa_DisableVertexAttribArray (GLuint index)
References disable_vertex_array_attrib(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_EdgeFlagPointer()
void GLAPIENTRY _mesa_EdgeFlagPointer (GLsizei stride, const GLvoid * ptr)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, UNSIGNED_BYTE_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), and _mesa_EdgeFlagPointerEXT().
_mesa_EdgeFlagPointerEXT()
void GLAPIENTRY _mesa_EdgeFlagPointerEXT (GLsizei stride, GLsizei count, const GLboolean * ptr)
References _mesa_EdgeFlagPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_enable_vertex_array_attrib()
void _mesa_enable_vertex_array_attrib (struct gl_context * ctx, struct gl_vertex_array_object * vao, unsigned attrib)
References gl_vertex_array_object::_Enabled, _NEW_ARRAY, gl_array_attributes::Enabled, FLUSH_VERTICES, gl_vertex_array_object::NewArrays, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex(), and enable_vertex_array_attrib().
_mesa_EnableVertexArrayAttrib()
void GLAPIENTRY _mesa_EnableVertexArrayAttrib (GLuint vaobj, GLuint index)
References _mesa_lookup_vao_err(), enable_vertex_array_attrib(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_EnableVertexAttribArray()
void GLAPIENTRY _mesa_EnableVertexAttribArray (GLuint index)
References enable_vertex_array_attrib(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_FogCoordPointer()
void GLAPIENTRY _mesa_FogCoordPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_free_varray_data()
void _mesa_free_varray_data (struct gl_context * ctx)
Free vertex array state for given context.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), gl_context::Array, delete_arrayobj_cb(), and gl_array_attrib::Objects.
Referenced by _mesa_attr_zero_aliases_vertex(), and _mesa_free_context_data().
_mesa_GetVertexArrayIndexed64iv()
void GLAPIENTRY _mesa_GetVertexArrayIndexed64iv (GLuint vaobj, GLuint index, GLenum pname, GLint64 * params)
References _mesa_error(), _mesa_lookup_vao_err(), gl_vertex_array_object::BufferBinding, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_vertex_buffer_binding::Offset.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexArrayIndexediv()
void GLAPIENTRY _mesa_GetVertexArrayIndexediv (GLuint vaobj, GLuint index, GLenum pname, GLint * params)
ARB_direct_state_access.
References _mesa_lookup_vao_err(), gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, GET_CURRENT_CONTEXT, get_vertex_array_attrib(), GLAPIENTRY, gl_vertex_buffer_binding::InstanceDivisor, gl_buffer_object::Name, gl_vertex_buffer_binding::Offset, and gl_vertex_buffer_binding::Stride.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribdv()
void GLAPIENTRY _mesa_GetVertexAttribdv (GLuint index, GLenum pname, GLdouble * params)
References get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribfv()
void GLAPIENTRY _mesa_GetVertexAttribfv (GLuint index, GLenum pname, GLfloat * params)
References COPY_4V, get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribIiv()
void GLAPIENTRY _mesa_GetVertexAttribIiv (GLuint index, GLenum pname, GLint * params)
GL 3.0.
References COPY_4V, get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribIuiv()
void GLAPIENTRY _mesa_GetVertexAttribIuiv (GLuint index, GLenum pname, GLuint * params)
GL 3.0.
References COPY_4V, get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), GLAPIENTRY, and GLuint.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribiv()
void GLAPIENTRY _mesa_GetVertexAttribiv (GLuint index, GLenum pname, GLint * params)
References get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribLdv()
void GLAPIENTRY _mesa_GetVertexAttribLdv (GLuint index, GLenum pname, GLdouble * params)
References get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribPointerv()
void GLAPIENTRY _mesa_GetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid ** pointer)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_IndexPointer()
void GLAPIENTRY _mesa_IndexPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), and _mesa_IndexPointerEXT().
_mesa_IndexPointerEXT()
void GLAPIENTRY _mesa_IndexPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_IndexPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_init_varray()
void _mesa_init_varray (struct gl_context * ctx)
Initialize vertex array state for given context.
References _mesa_new_vao(), _mesa_NewHashTable(), _mesa_reference_vao(), gl_array_attrib::ActiveTexture, gl_context::Array, gl_array_attrib::DefaultVAO, gl_array_attrib::Objects, and gl_array_attrib::VAO.
Referenced by _mesa_attr_zero_aliases_vertex(), and init_attrib_groups().
_mesa_InterleavedArrays()
void GLAPIENTRY _mesa_InterleavedArrays (GLenum format, GLsizei stride, const GLvoid * pointer)
References _mesa_ColorPointer(), _mesa_DisableClientState(), _mesa_EnableClientState(), _mesa_error(), _mesa_NormalPointer(), _mesa_TexCoordPointer(), _mesa_VertexPointer(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_LockArraysEXT()
void GLAPIENTRY _mesa_LockArraysEXT (GLint first, GLsizei count)
References _mesa_debug(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiDrawArrays()
void GLAPIENTRY _mesa_MultiDrawArrays (GLenum mode, const GLint * first, const GLsizei * count, GLsizei primcount)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiModeDrawArraysIBM()
void GLAPIENTRY _mesa_MultiModeDrawArraysIBM (const GLenum * mode, const GLint * first, const GLsizei * count, GLsizei primcount, GLint modestride)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiModeDrawElementsIBM()
void GLAPIENTRY _mesa_MultiModeDrawElementsIBM (const GLenum * mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount, GLint modestride)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_NormalPointer()
void GLAPIENTRY _mesa_NormalPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_InterleavedArrays(), and _mesa_NormalPointerEXT().
_mesa_NormalPointerEXT()
void GLAPIENTRY _mesa_NormalPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_NormalPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_PointSizePointerOES()
void GLAPIENTRY _mesa_PointSizePointerOES (GLenum type, GLsizei stride, const GLvoid * ptr)
References _mesa_error(), API_OPENGLES, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_primitive_restart_index()
unsigned _mesa_primitive_restart_index (const struct gl_context * ctx, GLenum ib_type)
References gl_context::Array, gl_array_attrib::PrimitiveRestartFixedIndex, and gl_array_attrib::RestartIndex.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_PrimitiveRestartIndex()
void GLAPIENTRY _mesa_PrimitiveRestartIndex (GLuint index)
GL_NV_primitive_restart and GL 3.1.
References _mesa_error(), _NEW_TRANSFORM, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_print_arrays()
void _mesa_print_arrays (struct gl_context * ctx)
Print current vertex object/array info.
For debug.
References gl_array_attributes::_ElementSize, _mesa_enum_to_string(), gl_context::Array, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_array_attributes::Enabled, gl_buffer_object::Name, gl_vertex_array_object::Name, gl_array_attributes::Ptr, gl_buffer_object::Size, gl_array_attributes::Size, gl_vertex_buffer_binding::Stride, gl_array_attributes::Type, gl_array_attrib::VAO, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_SecondaryColorPointer()
void GLAPIENTRY _mesa_SecondaryColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_TexCoordPointer()
void GLAPIENTRY _mesa_TexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_InterleavedArrays(), and _mesa_TexCoordPointerEXT().
_mesa_TexCoordPointerEXT()
void GLAPIENTRY _mesa_TexCoordPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_TexCoordPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_UnlockArraysEXT()
void GLAPIENTRY _mesa_UnlockArraysEXT (void)
References _mesa_debug(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_update_array_format()
void _mesa_update_array_format (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint attrib, GLint size, GLenum type, GLenum format, GLboolean normalized, GLboolean integer, GLboolean doubles, GLuint relativeOffset)
Parameters
attrib The index of the attribute array
size Components per element (1, 2, 3 or 4)
type Datatype of each component (GL_FLOAT, GL_INT, etc)
format Either GL_RGBA or GL_BGRA.
normalized Whether integer types are converted to floats in [-1, 1]
integer Integer-valued values (will not be normalized to [-1, 1])
doubles Double values not reduced to floats
relativeOffset Offset of the first element relative to the binding offset.
flush_verties Should FLUSH_VERTICES be invoked before updating state?
References gl_array_attributes::_ElementSize, _mesa_bytes_per_vertex_attrib(), _NEW_ARRAY, gl_array_attributes::Doubles, gl_array_attributes::Format, gl_array_attributes::Integer, gl_vertex_array_object::NewArrays, gl_context::NewState, gl_array_attributes::Normalized, gl_array_attributes::RelativeOffset, gl_array_attributes::Size, gl_array_attributes::Type, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex(), and update_array_format().
_mesa_VertexArrayAttribBinding()
void GLAPIENTRY _mesa_VertexArrayAttribBinding (GLuint vaobj, GLuint attribIndex, GLuint bindingIndex)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_attrib_binding().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayAttribFormat()
void GLAPIENTRY _mesa_VertexArrayAttribFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
References ATTRIB_FORMAT_TYPES_MASK, BGRA_OR_4, GLAPIENTRY, and vertex_array_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayAttribIFormat()
void GLAPIENTRY _mesa_VertexArrayAttribIFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_IFORMAT_TYPES_MASK, GLAPIENTRY, and vertex_array_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayAttribLFormat()
void GLAPIENTRY _mesa_VertexArrayAttribLFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_LFORMAT_TYPES_MASK, and vertex_array_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayBindingDivisor()
void GLAPIENTRY _mesa_VertexArrayBindingDivisor (GLuint vaobj, GLuint bindingIndex, GLuint divisor)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_binding_divisor().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayVertexBuffer()
void GLAPIENTRY _mesa_VertexArrayVertexBuffer (GLuint vaobj, GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_vertex_buffer().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayVertexBuffers()
void GLAPIENTRY _mesa_VertexArrayVertexBuffers (GLuint vaobj, GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizei * strides)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_vertex_buffers().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribBinding()
void GLAPIENTRY _mesa_VertexAttribBinding (GLuint attribIndex, GLuint bindingIndex)
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_attrib_binding().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribDivisor()
void GLAPIENTRY _mesa_VertexAttribDivisor (GLuint index, GLuint divisor)
See GL_ARB_instanced_arrays.
Note that the instance divisor only applies to generic arrays, not the legacy vertex arrays.
References _mesa_error(), GET_CURRENT_CONTEXT, GLuint, vertex_attrib_binding(), vertex_binding_divisor(), and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribFormat()
void GLAPIENTRY _mesa_VertexAttribFormat (GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
References ATTRIB_FORMAT_TYPES_MASK, BGRA_OR_4, GLAPIENTRY, and vertex_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribIFormat()
void GLAPIENTRY _mesa_VertexAttribIFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_IFORMAT_TYPES_MASK, GLAPIENTRY, and vertex_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribIPointer()
void GLAPIENTRY _mesa_VertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
GL_EXT_gpu_shader4 / GL 3.0.
Set an integer-valued vertex attribute array. Note that these arrays DO NOT alias the conventional GL vertex arrays (position, normal, color, fog, texcoord, etc).
References _mesa_error(), BYTE_BIT, GET_CURRENT_CONTEXT, GLAPIENTRY, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribLFormat()
void GLAPIENTRY _mesa_VertexAttribLFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_LFORMAT_TYPES_MASK, and vertex_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribLPointer()
void GLAPIENTRY _mesa_VertexAttribLPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References _mesa_error(), DOUBLE_BIT, GET_CURRENT_CONTEXT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribPointer()
void GLAPIENTRY _mesa_VertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * ptr)
Set a generic vertex attribute array.
Note that these arrays DO NOT alias the conventional GL vertex arrays (position, normal, color, fog, texcoord, etc).
References _mesa_error(), BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FIXED_GL_BIT, FLOAT_BIT, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_10F_11F_11F_REV_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexBindingDivisor()
void GLAPIENTRY _mesa_VertexBindingDivisor (GLuint bindingIndex, GLuint divisor)
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_binding_divisor().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexPointer()
void GLAPIENTRY _mesa_VertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_InterleavedArrays(), and _mesa_VertexPointerEXT().
_mesa_VertexPointerEXT()
void GLAPIENTRY _mesa_VertexPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_VertexPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
delete_arrayobj_cb()
static void delete_arrayobj_cb (GLuint id, void * data, void * userData) static
Callback for deleting an array object.
Called by _mesa_HashDeleteAll().
References _mesa_delete_vao().
Referenced by _mesa_free_varray_data().
disable_vertex_array_attrib()
static void disable_vertex_array_attrib (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint index, const char * func) static
References gl_vertex_array_object::_Enabled, _mesa_error(), _NEW_ARRAY, gl_context::Const, gl_array_attributes::Enabled, FLUSH_VERTICES, GLAPIENTRY, gl_program_constants::MaxAttribs, gl_vertex_array_object::NewArrays, gl_constants::Program, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_DisableVertexArrayAttrib(), and _mesa_DisableVertexAttribArray().
enable_vertex_array_attrib()
static void enable_vertex_array_attrib (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint index, const char * func) static
References _mesa_enable_vertex_array_attrib(), _mesa_error(), gl_context::Const, GLAPIENTRY, gl_program_constants::MaxAttribs, and gl_constants::Program.
Referenced by _mesa_EnableVertexArrayAttrib(), and _mesa_EnableVertexAttribArray().
get_current_attrib()
static const GLfloat* get_current_attrib (struct gl_context * ctx, GLuint index, const char * function) static
References _mesa_attr_zero_aliases_vertex(), _mesa_error(), gl_context::Array, gl_current_attrib::Attrib, gl_context::Const, gl_context::Current, FLUSH_CURRENT, GLAPIENTRY, gl_program_constants::MaxAttribs, gl_constants::Program, gl_array_attrib::VAO, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_GetVertexAttribdv(), _mesa_GetVertexAttribfv(), _mesa_GetVertexAttribIiv(), _mesa_GetVertexAttribIuiv(), _mesa_GetVertexAttribiv(), and _mesa_GetVertexAttribLdv().
get_legal_types_mask()
static GLbitfield get_legal_types_mask (const struct gl_context * ctx) static
Examine the API profile and extensions to determine which types are legal for vertex arrays.
This is called once from update_array_format().
References _mesa_is_gles(), ALL_TYPE_BITS, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_vertex_type_10f_11f_11f_rev, gl_extensions::ARB_vertex_type_2_10_10_10_rev, DOUBLE_BIT, gl_context::Extensions, FIXED_ES_BIT, FIXED_GL_BIT, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, UNSIGNED_INT_10F_11F_11F_REV_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, and gl_context::Version.
Referenced by update_array_format().
get_vertex_array_attrib()
static GLuint get_vertex_array_attrib (struct gl_context * ctx, const struct gl_vertex_array_object * vao, GLuint index, GLenum pname, const char * caller) static
Return info for a vertex attribute array (no alias with legacy vertex attributes (pos, normal, color, etc)).
This function does not handle the 4-element GL_CURRENT_VERTEX_ATTRIB_ARB query.
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_gles31(), gl_extensions::ARB_instanced_arrays, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_context::Const, gl_array_attributes::Doubles, gl_array_attributes::Enabled, gl_extensions::EXT_gpu_shader4, gl_context::Extensions, gl_array_attributes::Format, gl_vertex_buffer_binding::InstanceDivisor, gl_array_attributes::Integer, gl_program_constants::MaxAttribs, gl_buffer_object::Name, gl_array_attributes::Normalized, gl_constants::Program, gl_array_attributes::RelativeOffset, gl_array_attributes::Size, gl_array_attributes::Stride, gl_array_attributes::Type, gl_context::Version, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_GetVertexArrayIndexediv(), _mesa_GetVertexAttribdv(), _mesa_GetVertexAttribfv(), _mesa_GetVertexAttribIiv(), _mesa_GetVertexAttribIuiv(), _mesa_GetVertexAttribiv(), and _mesa_GetVertexAttribLdv().
type_to_bit()
static GLbitfield type_to_bit (const struct gl_context * ctx, GLenum type) static
Convert GL datatype enum into a <type>_BIT value seen above.
References _mesa_is_desktop_gl(), gl_extensions::ARB_half_float_vertex, BOOL_BIT, BYTE_BIT, DOUBLE_BIT, gl_context::Extensions, FIXED_ES_BIT, FIXED_GL_BIT, FLOAT_BIT, GL_HALF_FLOAT_OES, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_10F_11F_11F_REV_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, and UNSIGNED_SHORT_BIT.
Referenced by update_array_format().
update_array()
static void update_array (struct gl_context * ctx, const char * func, GLuint attrib, GLbitfield legalTypesMask, GLint sizeMin, GLint sizeMax, GLint size, GLenum type, GLsizei stride, GLboolean normalized, GLboolean integer, GLboolean doubles, const GLvoid * ptr) static
Do error checking and update state for glVertex/Color/TexCoord/...Pointer functions.
Parameters
func name of calling function used for error reporting
attrib the attribute array index to update
legalTypes bitmask of *_BIT above indicating legal datatypes
sizeMin min allowable size value
sizeMax max allowable size value (may also be BGRA_OR_4)
size components per element (1, 2, 3 or 4)
type datatype of each component (GL_FLOAT, GL_INT, etc)
stride stride between elements, in elements
normalized are integer types converted to floats in [-1, 1]?
integer integer-valued values (will not be normalized to [-1,1])
doubles Double values not reduced to floats
ptr the address (or offset inside VBO) of the array data
References gl_array_attributes::_ElementSize, _mesa_bind_vertex_buffer(), _mesa_error(), _mesa_is_bufferobj(), gl_context::API, API_OPENGL_CORE, gl_vertex_array_object::ARBsemantics, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_context::Const, gl_array_attrib::DefaultVAO, GLAPIENTRY, gl_constants::MaxVertexAttribStride, gl_array_attributes::Ptr, gl_array_attributes::Stride, update_array_format(), gl_array_attrib::VAO, gl_context::Version, vertex_attrib_binding(), and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_ColorPointer(), _mesa_EdgeFlagPointer(), _mesa_FogCoordPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_PointSizePointerOES(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribLPointer(), _mesa_VertexAttribPointer(), and _mesa_VertexPointer().
update_array_format()
static bool update_array_format (struct gl_context * ctx, const char * func, struct gl_vertex_array_object * vao, GLuint attrib, GLbitfield legalTypesMask, GLint sizeMin, GLint sizeMax, GLint size, GLenum type, GLboolean normalized, GLboolean integer, GLboolean doubles, GLuint relativeOffset) static
Does error checking and updates the format in an attrib array.
Called by update_array() and VertexAttrib*Format().
Parameters
func Name of calling function used for error reporting
attrib The index of the attribute array
legalTypes Bitmask of *_BIT above indicating legal datatypes
sizeMin Min allowable size value
sizeMax Max allowable size value (may also be BGRA_OR_4)
size Components per element (1, 2, 3 or 4)
type Datatype of each component (GL_FLOAT, GL_INT, etc)
normalized Whether integer types are converted to floats in [-1, 1]
integer Integer-valued values (will not be normalized to [-1, 1])
doubles Double values not reduced to floats
relativeOffset Offset of the first element relative to the binding offset.
References _mesa_enum_to_string(), _mesa_error(), _mesa_is_gles(), _mesa_update_array_format(), gl_context::API, gl_extensions::ARB_vertex_type_10f_11f_11f_rev, gl_extensions::ARB_vertex_type_2_10_10_10_rev, gl_context::Array, BGRA_OR_4, gl_context::Const, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, get_legal_types_mask(), gl_array_attrib::LegalTypesMask, gl_array_attrib::LegalTypesMaskAPI, gl_constants::MaxVertexAttribRelativeOffset, and type_to_bit().
Referenced by update_array(), vertex_array_attrib_format(), and vertex_attrib_format().
vertex_array_attrib_binding()
static void vertex_array_attrib_binding (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint attribIndex, GLuint bindingIndex, const char * func) static
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END, gl_context::Const, GLAPIENTRY, gl_program_constants::MaxAttribs, gl_constants::MaxVertexAttribBindings, gl_constants::Program, vertex_attrib_binding(), and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_VertexArrayAttribBinding(), and _mesa_VertexAttribBinding().
vertex_array_attrib_format()
static void vertex_array_attrib_format (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLboolean integer, GLboolean doubles, GLbitfield legalTypes, GLsizei maxSize, GLuint relativeOffset, const char * func) static
References _mesa_error(), _mesa_lookup_vao_err(), ASSERT_OUTSIDE_BEGIN_END, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and update_array_format().
Referenced by _mesa_VertexArrayAttribFormat(), _mesa_VertexArrayAttribIFormat(), and _mesa_VertexArrayAttribLFormat().
vertex_array_binding_divisor()
static void vertex_array_binding_divisor (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint bindingIndex, GLuint divisor, const char * func) static
References _mesa_error(), gl_extensions::ARB_instanced_arrays, ASSERT_OUTSIDE_BEGIN_END, gl_context::Const, gl_context::Extensions, GLAPIENTRY, gl_constants::MaxVertexAttribBindings, and vertex_binding_divisor().
Referenced by _mesa_VertexArrayBindingDivisor(), and _mesa_VertexBindingDivisor().
vertex_array_vertex_buffer()
static void vertex_array_vertex_buffer (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride, const char * func) static
GL_ARB_vertex_attrib_binding.
References _mesa_bind_vertex_buffer(), _mesa_error(), _mesa_handle_bind_buffer_gen(), _mesa_is_gles31(), _mesa_lookup_bufferobj(), gl_context::API, API_OPENGL_CORE, ASSERT_OUTSIDE_BEGIN_END, gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, gl_context::Const, GLAPIENTRY, gl_constants::MaxVertexAttribBindings, gl_constants::MaxVertexAttribStride, gl_shared_state::NullBufferObj, gl_context::Shared, and gl_context::Version.
Referenced by _mesa_BindVertexBuffer(), and _mesa_VertexArrayVertexBuffer().
vertex_array_vertex_buffers()
static void vertex_array_vertex_buffers (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizei * strides, const char * func) static
The ARB_multi_bind spec says:
"If <buffers> is NULL, each affected vertex buffer binding point from <first> through <first>+<count>-1 will be reset to have no bound buffer object. In this case, the offsets and strides associated with the binding points are set to default values, ignoring <offsets> and <strides>."
References _mesa_bind_vertex_buffer(), _mesa_error(), _mesa_HashLockMutex(), _mesa_HashUnlockMutex(), _mesa_multi_bind_lookup_bufferobj(), gl_context::API, API_OPENGL_CORE, ASSERT_OUTSIDE_BEGIN_END, gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, gl_shared_state::BufferObjects, gl_context::Const, GLAPIENTRY, GLuint, gl_constants::MaxVertexAttribBindings, gl_constants::MaxVertexAttribStride, gl_buffer_object::Name, gl_shared_state::NullBufferObj, gl_context::Shared, and gl_context::Version.
Referenced by _mesa_BindVertexBuffers(), and _mesa_VertexArrayVertexBuffers().
vertex_attrib_binding()
static void vertex_attrib_binding (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint attribIndex, GLuint bindingIndex) static
Sets the BufferBindingIndex field for the vertex attribute given by attribIndex.
References gl_vertex_buffer_binding::_BoundArrays, _mesa_is_bufferobj(), _NEW_ARRAY, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, FLUSH_VERTICES, gl_vertex_array_object::NewArrays, gl_vertex_array_object::VertexAttrib, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by _mesa_VertexAttribDivisor(), update_array(), and vertex_array_attrib_binding().
vertex_attrib_format()
static void vertex_attrib_format (GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLboolean integer, GLboolean doubles, GLbitfield legalTypes, GLsizei maxSize, GLuint relativeOffset, const char * func) static
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, ASSERT_OUTSIDE_BEGIN_END, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and update_array_format().
Referenced by _mesa_VertexAttribFormat(), _mesa_VertexAttribIFormat(), and _mesa_VertexAttribLFormat().
vertex_binding_divisor()
static void vertex_binding_divisor (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint bindingIndex, GLuint divisor) static
Sets the InstanceDivisor field in the vertex buffer binding point given by bindingIndex.
References gl_vertex_buffer_binding::_BoundArrays, _NEW_ARRAY, gl_vertex_array_object::BufferBinding, FLUSH_VERTICES, gl_vertex_buffer_binding::InstanceDivisor, and gl_vertex_array_object::NewArrays.
Referenced by _mesa_VertexAttribDivisor(), and vertex_array_binding_divisor().