Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
varray.h File Reference
#include "glheader.h"
#include "bufferobj.h"
Functions
static const GLubyte * _mesa_vertex_attrib_address (const struct gl_array_attributes *array, const struct gl_vertex_buffer_binding *binding)
Returns a pointer to the vertex attribute data in a client array, or the offset into the vertex buffer for an array that resides in a vertex buffer.
static void _mesa_update_client_array (struct gl_context *ctx, struct gl_vertex_array *dst, const struct gl_array_attributes *src, const struct gl_vertex_buffer_binding *binding)
Sets the fields in a gl_vertex_array to values derived from a gl_vertex_attrib_array and a gl_vertex_buffer_binding.
static bool _mesa_attr_zero_aliases_vertex (struct gl_context *ctx)
void _mesa_update_array_format (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint attrib, GLint size, GLenum type, GLenum format, GLboolean normalized, GLboolean integer, GLboolean doubles, GLuint relativeOffset)
void _mesa_enable_vertex_array_attrib (struct gl_context *ctx, struct gl_vertex_array_object *vao, unsigned attrib)
void _mesa_bind_vertex_buffer (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint index, struct gl_buffer_object *vbo, GLintptr offset, GLsizei stride)
Binds a buffer object to the vertex buffer binding point given by index, and sets the Offset and Stride fields.
void GLAPIENTRY _mesa_VertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_NormalPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_ColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_IndexPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_TexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_EdgeFlagPointer (GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_VertexPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_NormalPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_ColorPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_IndexPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_TexCoordPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_EdgeFlagPointerEXT (GLsizei stride, GLsizei count, const GLboolean *ptr)
void GLAPIENTRY _mesa_FogCoordPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_SecondaryColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_PointSizePointerOES (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_VertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *pointer)
Set a generic vertex attribute array.
void GLAPIENTRY _mesa_VertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
GL_EXT_gpu_shader4 / GL 3.0.
void GLAPIENTRY _mesa_VertexAttribLPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
void GLAPIENTRY _mesa_EnableVertexAttribArray (GLuint index)
void GLAPIENTRY _mesa_EnableVertexArrayAttrib (GLuint vaobj, GLuint index)
void GLAPIENTRY _mesa_DisableVertexAttribArray (GLuint index)
void GLAPIENTRY _mesa_DisableVertexArrayAttrib (GLuint vaobj, GLuint index)
void GLAPIENTRY _mesa_GetVertexAttribdv (GLuint index, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetVertexAttribLdv (GLuint index, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetVertexAttribiv (GLuint index, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetVertexAttribIiv (GLuint index, GLenum pname, GLint *params)
GL 3.0.
void GLAPIENTRY _mesa_GetVertexAttribIuiv (GLuint index, GLenum pname, GLuint *params)
GL 3.0.
void GLAPIENTRY _mesa_GetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid **pointer)
void GLAPIENTRY _mesa_GetVertexArrayIndexediv (GLuint vaobj, GLuint index, GLenum pname, GLint *param)
ARB_direct_state_access.
void GLAPIENTRY _mesa_GetVertexArrayIndexed64iv (GLuint vaobj, GLuint index, GLenum pname, GLint64 *param)
void GLAPIENTRY _mesa_InterleavedArrays (GLenum format, GLsizei stride, const GLvoid *pointer)
void GLAPIENTRY _mesa_MultiDrawArrays (GLenum mode, const GLint *first, const GLsizei *count, GLsizei primcount)
void GLAPIENTRY _mesa_MultiDrawElementsEXT (GLenum mode, const GLsizei *count, GLenum type, const GLvoid **indices, GLsizei primcount)
void GLAPIENTRY _mesa_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei *count, GLenum type, const GLvoid **indices, GLsizei primcount, const GLint *basevertex)
void GLAPIENTRY _mesa_MultiModeDrawArraysIBM (const GLenum *mode, const GLint *first, const GLsizei *count, GLsizei primcount, GLint modestride)
void GLAPIENTRY _mesa_MultiModeDrawElementsIBM (const GLenum *mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount, GLint modestride)
void GLAPIENTRY _mesa_LockArraysEXT (GLint first, GLsizei count)
void GLAPIENTRY _mesa_UnlockArraysEXT (void)
void GLAPIENTRY _mesa_DrawArrays (GLenum mode, GLint first, GLsizei count)
void GLAPIENTRY _mesa_DrawArraysInstanced (GLenum mode, GLint first, GLsizei count, GLsizei primcount)
void GLAPIENTRY _mesa_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
void GLAPIENTRY _mesa_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
void GLAPIENTRY _mesa_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
void GLAPIENTRY _mesa_DrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
void GLAPIENTRY _mesa_DrawTransformFeedback (GLenum mode, GLuint name)
void GLAPIENTRY _mesa_PrimitiveRestartIndex (GLuint index)
GL_NV_primitive_restart and GL 3.1.
void GLAPIENTRY _mesa_VertexAttribDivisor (GLuint index, GLuint divisor)
See GL_ARB_instanced_arrays.
unsigned _mesa_primitive_restart_index (const struct gl_context *ctx, GLenum ib_type)
void GLAPIENTRY _mesa_BindVertexBuffer (GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
void GLAPIENTRY _mesa_VertexArrayVertexBuffer (GLuint vaobj, GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
void GLAPIENTRY _mesa_BindVertexBuffers (GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides)
void GLAPIENTRY _mesa_VertexArrayVertexBuffers (GLuint vaobj, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides)
void GLAPIENTRY _mesa_VertexAttribFormat (GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexArrayAttribFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexAttribIFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexArrayAttribIFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexAttribLFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexArrayAttribLFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
void GLAPIENTRY _mesa_VertexAttribBinding (GLuint attribIndex, GLuint bindingIndex)
void GLAPIENTRY _mesa_VertexArrayAttribBinding (GLuint vaobj, GLuint attribIndex, GLuint bindingIndex)
void GLAPIENTRY _mesa_VertexBindingDivisor (GLuint bindingIndex, GLuint divisor)
void GLAPIENTRY _mesa_VertexArrayBindingDivisor (GLuint vaobj, GLuint bindingIndex, GLuint divisor)
void _mesa_copy_client_array (struct gl_context *ctx, struct gl_vertex_array *dst, struct gl_vertex_array *src)
Copy one client vertex array to another.
void _mesa_copy_vertex_attrib_array (struct gl_context *ctx, struct gl_array_attributes *dst, const struct gl_array_attributes *src)
void _mesa_copy_vertex_buffer_binding (struct gl_context *ctx, struct gl_vertex_buffer_binding *dst, const struct gl_vertex_buffer_binding *src)
void _mesa_print_arrays (struct gl_context *ctx)
Print current vertex object/array info.
void _mesa_init_varray (struct gl_context *ctx)
Initialize vertex array state for given context.
void _mesa_free_varray_data (struct gl_context *ctx)
Free vertex array state for given context.
Function Documentation
_mesa_attr_zero_aliases_vertex()
static bool _mesa_attr_zero_aliases_vertex (struct gl_context * ctx) inline static
References _mesa_bind_vertex_buffer(), _mesa_BindVertexBuffer(), _mesa_BindVertexBuffers(), _mesa_ColorPointer(), _mesa_ColorPointerEXT(), _mesa_copy_client_array(), _mesa_copy_vertex_attrib_array(), _mesa_copy_vertex_buffer_binding(), _mesa_DisableVertexArrayAttrib(), _mesa_DisableVertexAttribArray(), _mesa_DrawArrays(), _mesa_DrawArraysInstanced(), _mesa_DrawElements(), _mesa_DrawElementsBaseVertex(), _mesa_DrawRangeElements(), _mesa_DrawRangeElementsBaseVertex(), _mesa_DrawTransformFeedback(), _mesa_EdgeFlagPointer(), _mesa_EdgeFlagPointerEXT(), _mesa_enable_vertex_array_attrib(), _mesa_EnableVertexArrayAttrib(), _mesa_EnableVertexAttribArray(), _mesa_FogCoordPointer(), _mesa_free_varray_data(), _mesa_GetVertexArrayIndexed64iv(), _mesa_GetVertexArrayIndexediv(), _mesa_GetVertexAttribdv(), _mesa_GetVertexAttribfv(), _mesa_GetVertexAttribIiv(), _mesa_GetVertexAttribIuiv(), _mesa_GetVertexAttribiv(), _mesa_GetVertexAttribLdv(), _mesa_GetVertexAttribPointerv(), _mesa_IndexPointer(), _mesa_IndexPointerEXT(), _mesa_init_varray(), _mesa_InterleavedArrays(), _mesa_LockArraysEXT(), _mesa_MultiDrawArrays(), _mesa_MultiDrawElementsBaseVertex(), _mesa_MultiDrawElementsEXT(), _mesa_MultiModeDrawArraysIBM(), _mesa_MultiModeDrawElementsIBM(), _mesa_NormalPointer(), _mesa_NormalPointerEXT(), _mesa_PointSizePointerOES(), _mesa_primitive_restart_index(), _mesa_PrimitiveRestartIndex(), _mesa_print_arrays(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_TexCoordPointerEXT(), _mesa_UnlockArraysEXT(), _mesa_update_array_format(), _mesa_VertexArrayAttribBinding(), _mesa_VertexArrayAttribFormat(), _mesa_VertexArrayAttribIFormat(), _mesa_VertexArrayAttribLFormat(), _mesa_VertexArrayBindingDivisor(), _mesa_VertexArrayVertexBuffer(), _mesa_VertexArrayVertexBuffers(), _mesa_VertexAttribBinding(), _mesa_VertexAttribDivisor(), _mesa_VertexAttribFormat(), _mesa_VertexAttribIFormat(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribLFormat(), _mesa_VertexAttribLPointer(), _mesa_VertexAttribPointer(), _mesa_VertexBindingDivisor(), _mesa_VertexPointer(), _mesa_VertexPointerEXT(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_context::Const, gl_constants::ContextFlags, GLAPIENTRY, and GLuint.
Referenced by get_current_attrib().
_mesa_bind_vertex_buffer()
void _mesa_bind_vertex_buffer (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint index, struct gl_buffer_object * vbo, GLintptr offset, GLsizei stride)
Binds a buffer object to the vertex buffer binding point given by index, and sets the Offset and Stride fields.
References gl_vertex_buffer_binding::_BoundArrays, _mesa_is_bufferobj(), _mesa_reference_buffer_object(), _NEW_ARRAY, gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, FLUSH_VERTICES, gl_vertex_array_object::NewArrays, gl_vertex_buffer_binding::Offset, gl_vertex_buffer_binding::Stride, and gl_vertex_array_object::VertexAttribBufferMask.
Referenced by _mesa_attr_zero_aliases_vertex(), unbind(), update_array(), vertex_array_vertex_buffer(), and vertex_array_vertex_buffers().
_mesa_BindVertexBuffer()
void GLAPIENTRY _mesa_BindVertexBuffer (GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_vertex_buffer().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_BindVertexBuffers()
void GLAPIENTRY _mesa_BindVertexBuffers (GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizei * strides)
References _mesa_error(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_vertex_buffers().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_ColorPointer()
void GLAPIENTRY _mesa_ColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_ColorPointerEXT(), and _mesa_InterleavedArrays().
_mesa_ColorPointerEXT()
void GLAPIENTRY _mesa_ColorPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_ColorPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_copy_client_array()
void _mesa_copy_client_array (struct gl_context * ctx, struct gl_vertex_array * dst, struct gl_vertex_array * src)
Copy one client vertex array to another.
References gl_vertex_array::_ElementSize, _mesa_reference_buffer_object(), gl_vertex_array::BufferObj, gl_vertex_array::Doubles, gl_vertex_array::Format, gl_vertex_array::InstanceDivisor, gl_vertex_array::Integer, gl_vertex_array::Normalized, gl_vertex_array::Ptr, gl_vertex_array::Size, gl_vertex_array::StrideB, and gl_vertex_array::Type.
Referenced by _mesa_attr_zero_aliases_vertex(), and copy_array_object().
_mesa_copy_vertex_attrib_array()
void _mesa_copy_vertex_attrib_array (struct gl_context * ctx, struct gl_array_attributes * dst, const struct gl_array_attributes * src)
References gl_array_attributes::_ElementSize, gl_array_attributes::BufferBindingIndex, gl_array_attributes::Doubles, gl_array_attributes::Enabled, gl_array_attributes::Format, gl_array_attributes::Integer, gl_array_attributes::Normalized, gl_array_attributes::Ptr, gl_array_attributes::RelativeOffset, gl_array_attributes::Size, and gl_array_attributes::Type.
Referenced by _mesa_attr_zero_aliases_vertex(), and copy_array_object().
_mesa_copy_vertex_buffer_binding()
void _mesa_copy_vertex_buffer_binding (struct gl_context * ctx, struct gl_vertex_buffer_binding * dst, const struct gl_vertex_buffer_binding * src)
References gl_vertex_buffer_binding::_BoundArrays, _mesa_reference_buffer_object(), gl_vertex_buffer_binding::BufferObj, gl_vertex_buffer_binding::InstanceDivisor, gl_vertex_buffer_binding::Offset, and gl_vertex_buffer_binding::Stride.
Referenced by _mesa_attr_zero_aliases_vertex(), and copy_array_object().
_mesa_DisableVertexArrayAttrib()
void GLAPIENTRY _mesa_DisableVertexArrayAttrib (GLuint vaobj, GLuint index)
References _mesa_lookup_vao_err(), disable_vertex_array_attrib(), GET_CURRENT_CONTEXT, and GLuint.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DisableVertexAttribArray()
void GLAPIENTRY _mesa_DisableVertexAttribArray (GLuint index)
References disable_vertex_array_attrib(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawArrays()
void GLAPIENTRY _mesa_DrawArrays (GLenum mode, GLint first, GLsizei count)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawArraysInstanced()
void GLAPIENTRY _mesa_DrawArraysInstanced (GLenum mode, GLint first, GLsizei count, GLsizei primcount)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawElements()
void GLAPIENTRY _mesa_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawElementsBaseVertex()
void GLAPIENTRY _mesa_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawRangeElements()
void GLAPIENTRY _mesa_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawRangeElementsBaseVertex()
void GLAPIENTRY _mesa_DrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_DrawTransformFeedback()
void GLAPIENTRY _mesa_DrawTransformFeedback (GLenum mode, GLuint name)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_EdgeFlagPointer()
void GLAPIENTRY _mesa_EdgeFlagPointer (GLsizei stride, const GLvoid * ptr)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, UNSIGNED_BYTE_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), and _mesa_EdgeFlagPointerEXT().
_mesa_EdgeFlagPointerEXT()
void GLAPIENTRY _mesa_EdgeFlagPointerEXT (GLsizei stride, GLsizei count, const GLboolean * ptr)
References _mesa_EdgeFlagPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_enable_vertex_array_attrib()
void _mesa_enable_vertex_array_attrib (struct gl_context * ctx, struct gl_vertex_array_object * vao, unsigned attrib)
References gl_vertex_array_object::_Enabled, _NEW_ARRAY, gl_array_attributes::Enabled, FLUSH_VERTICES, gl_vertex_array_object::NewArrays, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex(), and enable_vertex_array_attrib().
_mesa_EnableVertexArrayAttrib()
void GLAPIENTRY _mesa_EnableVertexArrayAttrib (GLuint vaobj, GLuint index)
References _mesa_lookup_vao_err(), enable_vertex_array_attrib(), and GET_CURRENT_CONTEXT.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_EnableVertexAttribArray()
void GLAPIENTRY _mesa_EnableVertexAttribArray (GLuint index)
References enable_vertex_array_attrib(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_FogCoordPointer()
void GLAPIENTRY _mesa_FogCoordPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_free_varray_data()
void _mesa_free_varray_data (struct gl_context * ctx)
Free vertex array state for given context.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), gl_context::Array, delete_arrayobj_cb(), and gl_array_attrib::Objects.
Referenced by _mesa_attr_zero_aliases_vertex(), and _mesa_free_context_data().
_mesa_GetVertexArrayIndexed64iv()
void GLAPIENTRY _mesa_GetVertexArrayIndexed64iv (GLuint vaobj, GLuint index, GLenum pname, GLint64 * param)
References _mesa_error(), _mesa_lookup_vao_err(), gl_vertex_array_object::BufferBinding, GET_CURRENT_CONTEXT, GLAPIENTRY, and gl_vertex_buffer_binding::Offset.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexArrayIndexediv()
void GLAPIENTRY _mesa_GetVertexArrayIndexediv (GLuint vaobj, GLuint index, GLenum pname, GLint * param)
ARB_direct_state_access.
References _mesa_lookup_vao_err(), gl_vertex_array_object::BufferBinding, gl_vertex_buffer_binding::BufferObj, GET_CURRENT_CONTEXT, get_vertex_array_attrib(), GLAPIENTRY, gl_vertex_buffer_binding::InstanceDivisor, gl_buffer_object::Name, gl_vertex_buffer_binding::Offset, and gl_vertex_buffer_binding::Stride.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribdv()
void GLAPIENTRY _mesa_GetVertexAttribdv (GLuint index, GLenum pname, GLdouble * params)
References get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribfv()
void GLAPIENTRY _mesa_GetVertexAttribfv (GLuint index, GLenum pname, GLfloat * params)
References COPY_4V, get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribIiv()
void GLAPIENTRY _mesa_GetVertexAttribIiv (GLuint index, GLenum pname, GLint * params)
GL 3.0.
References COPY_4V, get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribIuiv()
void GLAPIENTRY _mesa_GetVertexAttribIuiv (GLuint index, GLenum pname, GLuint * params)
GL 3.0.
References COPY_4V, get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), GLAPIENTRY, and GLuint.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribiv()
void GLAPIENTRY _mesa_GetVertexAttribiv (GLuint index, GLenum pname, GLint * params)
References get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribLdv()
void GLAPIENTRY _mesa_GetVertexAttribLdv (GLuint index, GLenum pname, GLdouble * params)
References get_current_attrib(), GET_CURRENT_CONTEXT, get_vertex_array_attrib(), and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_GetVertexAttribPointerv()
void GLAPIENTRY _mesa_GetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid ** pointer)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_IndexPointer()
void GLAPIENTRY _mesa_IndexPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), and _mesa_IndexPointerEXT().
_mesa_IndexPointerEXT()
void GLAPIENTRY _mesa_IndexPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_IndexPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_init_varray()
void _mesa_init_varray (struct gl_context * ctx)
Initialize vertex array state for given context.
References _mesa_new_vao(), _mesa_NewHashTable(), _mesa_reference_vao(), gl_array_attrib::ActiveTexture, gl_context::Array, gl_array_attrib::DefaultVAO, gl_array_attrib::Objects, and gl_array_attrib::VAO.
Referenced by _mesa_attr_zero_aliases_vertex(), and init_attrib_groups().
_mesa_InterleavedArrays()
void GLAPIENTRY _mesa_InterleavedArrays (GLenum format, GLsizei stride, const GLvoid * pointer)
References _mesa_ColorPointer(), _mesa_DisableClientState(), _mesa_EnableClientState(), _mesa_error(), _mesa_NormalPointer(), _mesa_TexCoordPointer(), _mesa_VertexPointer(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_LockArraysEXT()
void GLAPIENTRY _mesa_LockArraysEXT (GLint first, GLsizei count)
References _mesa_debug(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiDrawArrays()
void GLAPIENTRY _mesa_MultiDrawArrays (GLenum mode, const GLint * first, const GLsizei * count, GLsizei primcount)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiDrawElementsBaseVertex()
void GLAPIENTRY _mesa_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei * count, GLenum type, const GLvoid ** indices, GLsizei primcount, const GLint * basevertex)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiDrawElementsEXT()
void GLAPIENTRY _mesa_MultiDrawElementsEXT (GLenum mode, const GLsizei * count, GLenum type, const GLvoid ** indices, GLsizei primcount)
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiModeDrawArraysIBM()
void GLAPIENTRY _mesa_MultiModeDrawArraysIBM (const GLenum * mode, const GLint * first, const GLsizei * count, GLsizei primcount, GLint modestride)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_MultiModeDrawElementsIBM()
void GLAPIENTRY _mesa_MultiModeDrawElementsIBM (const GLenum * mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount, GLint modestride)
References FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_NormalPointer()
void GLAPIENTRY _mesa_NormalPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_InterleavedArrays(), and _mesa_NormalPointerEXT().
_mesa_NormalPointerEXT()
void GLAPIENTRY _mesa_NormalPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_NormalPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_PointSizePointerOES()
void GLAPIENTRY _mesa_PointSizePointerOES (GLenum type, GLsizei stride, const GLvoid * ptr)
References _mesa_error(), API_OPENGLES, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_primitive_restart_index()
unsigned _mesa_primitive_restart_index (const struct gl_context * ctx, GLenum ib_type)
References gl_context::Array, gl_array_attrib::PrimitiveRestartFixedIndex, and gl_array_attrib::RestartIndex.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_PrimitiveRestartIndex()
void GLAPIENTRY _mesa_PrimitiveRestartIndex (GLuint index)
GL_NV_primitive_restart and GL 3.1.
References _mesa_error(), _NEW_TRANSFORM, FLUSH_VERTICES, GET_CURRENT_CONTEXT, and GLAPIENTRY.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_print_arrays()
void _mesa_print_arrays (struct gl_context * ctx)
Print current vertex object/array info.
For debug.
References gl_array_attributes::_ElementSize, _mesa_enum_to_string(), gl_context::Array, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_array_attributes::Enabled, gl_buffer_object::Name, gl_vertex_array_object::Name, gl_array_attributes::Ptr, gl_buffer_object::Size, gl_array_attributes::Size, gl_vertex_buffer_binding::Stride, gl_array_attributes::Type, gl_array_attrib::VAO, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_SecondaryColorPointer()
void GLAPIENTRY _mesa_SecondaryColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_TexCoordPointer()
void GLAPIENTRY _mesa_TexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, GLuint, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_InterleavedArrays(), and _mesa_TexCoordPointerEXT().
_mesa_TexCoordPointerEXT()
void GLAPIENTRY _mesa_TexCoordPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_TexCoordPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_UnlockArraysEXT()
void GLAPIENTRY _mesa_UnlockArraysEXT (void)
References _mesa_debug(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_update_array_format()
void _mesa_update_array_format (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint attrib, GLint size, GLenum type, GLenum format, GLboolean normalized, GLboolean integer, GLboolean doubles, GLuint relativeOffset)
Parameters
attrib The index of the attribute array
size Components per element (1, 2, 3 or 4)
type Datatype of each component (GL_FLOAT, GL_INT, etc)
format Either GL_RGBA or GL_BGRA.
normalized Whether integer types are converted to floats in [-1, 1]
integer Integer-valued values (will not be normalized to [-1, 1])
doubles Double values not reduced to floats
relativeOffset Offset of the first element relative to the binding offset.
flush_verties Should FLUSH_VERTICES be invoked before updating state?
References gl_array_attributes::_ElementSize, _mesa_bytes_per_vertex_attrib(), _NEW_ARRAY, gl_array_attributes::Doubles, gl_array_attributes::Format, gl_array_attributes::Integer, gl_vertex_array_object::NewArrays, gl_context::NewState, gl_array_attributes::Normalized, gl_array_attributes::RelativeOffset, gl_array_attributes::Size, gl_array_attributes::Type, and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex(), and update_array_format().
_mesa_update_client_array()
static void _mesa_update_client_array (struct gl_context * ctx, struct gl_vertex_array * dst, const struct gl_array_attributes * src, const struct gl_vertex_buffer_binding * binding) inline static
Sets the fields in a gl_vertex_array to values derived from a gl_vertex_attrib_array and a gl_vertex_buffer_binding.
References gl_vertex_array::_ElementSize, gl_array_attributes::_ElementSize, _mesa_reference_buffer_object(), _mesa_vertex_attrib_address(), gl_vertex_array::BufferObj, gl_vertex_buffer_binding::BufferObj, gl_vertex_array::Doubles, gl_array_attributes::Doubles, gl_vertex_array::Format, gl_array_attributes::Format, gl_vertex_array::InstanceDivisor, gl_vertex_buffer_binding::InstanceDivisor, gl_vertex_array::Integer, gl_array_attributes::Integer, gl_vertex_array::Normalized, gl_array_attributes::Normalized, gl_vertex_array::Ptr, gl_vertex_array::Size, gl_array_attributes::Size, gl_vertex_buffer_binding::Stride, gl_vertex_array::StrideB, gl_vertex_array::Type, and gl_array_attributes::Type.
Referenced by _mesa_update_vao_client_arrays().
_mesa_vertex_attrib_address()
static const GLubyte* _mesa_vertex_attrib_address (const struct gl_array_attributes * array, const struct gl_vertex_buffer_binding * binding) inline static
Returns a pointer to the vertex attribute data in a client array, or the offset into the vertex buffer for an array that resides in a vertex buffer.
References _mesa_is_bufferobj(), gl_vertex_buffer_binding::BufferObj, gl_vertex_buffer_binding::Offset, gl_array_attributes::Ptr, and gl_array_attributes::RelativeOffset.
Referenced by _ae_ArrayElement(), and _mesa_update_client_array().
_mesa_VertexArrayAttribBinding()
void GLAPIENTRY _mesa_VertexArrayAttribBinding (GLuint vaobj, GLuint attribIndex, GLuint bindingIndex)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_attrib_binding().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayAttribFormat()
void GLAPIENTRY _mesa_VertexArrayAttribFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
References ATTRIB_FORMAT_TYPES_MASK, BGRA_OR_4, GLAPIENTRY, and vertex_array_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayAttribIFormat()
void GLAPIENTRY _mesa_VertexArrayAttribIFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_IFORMAT_TYPES_MASK, GLAPIENTRY, and vertex_array_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayAttribLFormat()
void GLAPIENTRY _mesa_VertexArrayAttribLFormat (GLuint vaobj, GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_LFORMAT_TYPES_MASK, and vertex_array_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayBindingDivisor()
void GLAPIENTRY _mesa_VertexArrayBindingDivisor (GLuint vaobj, GLuint bindingIndex, GLuint divisor)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_binding_divisor().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayVertexBuffer()
void GLAPIENTRY _mesa_VertexArrayVertexBuffer (GLuint vaobj, GLuint bindingIndex, GLuint buffer, GLintptr offset, GLsizei stride)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_vertex_buffer().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexArrayVertexBuffers()
void GLAPIENTRY _mesa_VertexArrayVertexBuffers (GLuint vaobj, GLuint first, GLsizei count, const GLuint * buffers, const GLintptr * offsets, const GLsizei * strides)
References _mesa_lookup_vao_err(), GET_CURRENT_CONTEXT, and vertex_array_vertex_buffers().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribBinding()
void GLAPIENTRY _mesa_VertexAttribBinding (GLuint attribIndex, GLuint bindingIndex)
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_attrib_binding().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribDivisor()
void GLAPIENTRY _mesa_VertexAttribDivisor (GLuint index, GLuint divisor)
See GL_ARB_instanced_arrays.
Note that the instance divisor only applies to generic arrays, not the legacy vertex arrays.
References _mesa_error(), GET_CURRENT_CONTEXT, GLuint, vertex_attrib_binding(), vertex_binding_divisor(), and gl_vertex_array_object::VertexAttrib.
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribFormat()
void GLAPIENTRY _mesa_VertexAttribFormat (GLuint attribIndex, GLint size, GLenum type, GLboolean normalized, GLuint relativeOffset)
References ATTRIB_FORMAT_TYPES_MASK, BGRA_OR_4, GLAPIENTRY, and vertex_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribIFormat()
void GLAPIENTRY _mesa_VertexAttribIFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_IFORMAT_TYPES_MASK, GLAPIENTRY, and vertex_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribIPointer()
void GLAPIENTRY _mesa_VertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
GL_EXT_gpu_shader4 / GL 3.0.
Set an integer-valued vertex attribute array. Note that these arrays DO NOT alias the conventional GL vertex arrays (position, normal, color, fog, texcoord, etc).
References _mesa_error(), BYTE_BIT, GET_CURRENT_CONTEXT, GLAPIENTRY, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribLFormat()
void GLAPIENTRY _mesa_VertexAttribLFormat (GLuint attribIndex, GLint size, GLenum type, GLuint relativeOffset)
References ATTRIB_LFORMAT_TYPES_MASK, and vertex_attrib_format().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribLPointer()
void GLAPIENTRY _mesa_VertexAttribLPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
References _mesa_error(), DOUBLE_BIT, GET_CURRENT_CONTEXT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexAttribPointer()
void GLAPIENTRY _mesa_VertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * ptr)
Set a generic vertex attribute array.
Note that these arrays DO NOT alias the conventional GL vertex arrays (position, normal, color, fog, texcoord, etc).
References _mesa_error(), BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FIXED_GL_BIT, FLOAT_BIT, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_10F_11F_11F_REV_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexBindingDivisor()
void GLAPIENTRY _mesa_VertexBindingDivisor (GLuint bindingIndex, GLuint divisor)
References _mesa_error(), _mesa_is_gles31(), API_OPENGL_CORE, GET_CURRENT_CONTEXT, GLAPIENTRY, and vertex_array_binding_divisor().
Referenced by _mesa_attr_zero_aliases_vertex().
_mesa_VertexPointer()
void GLAPIENTRY _mesa_VertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, and update_array().
Referenced by _mesa_attr_zero_aliases_vertex(), _mesa_InterleavedArrays(), and _mesa_VertexPointerEXT().
_mesa_VertexPointerEXT()
void GLAPIENTRY _mesa_VertexPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_VertexPointer(), GLAPIENTRY, and void.
Referenced by _mesa_attr_zero_aliases_vertex().