Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vdpau.c File Reference
#include <stdbool.h>
#include "util/hash_table.h"
#include "util/set.h"
#include "context.h"
#include "glformats.h"
#include "texobj.h"
#include "teximage.h"
#include "vdpau.h"
Data Structures
struct vdp_surface
Macros
#define MAX_TEXTURES 4
Functions
void GLAPIENTRY _mesa_VDPAUInitNV (const GLvoid *vdpDevice, const GLvoid *getProcAddress)
static void unregister_surface (struct set_entry *entry)
void GLAPIENTRY _mesa_VDPAUFiniNV (void)
static GLintptr register_surface (struct gl_context *ctx, GLboolean isOutput, const GLvoid *vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint *textureNames)
GLintptr GLAPIENTRY _mesa_VDPAURegisterVideoSurfaceNV (const GLvoid *vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint *textureNames)
GLintptr GLAPIENTRY _mesa_VDPAURegisterOutputSurfaceNV (const GLvoid *vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint *textureNames)
GLboolean GLAPIENTRY _mesa_VDPAUIsSurfaceNV (GLintptr surface)
void GLAPIENTRY _mesa_VDPAUUnregisterSurfaceNV (GLintptr surface)
void GLAPIENTRY _mesa_VDPAUGetSurfaceivNV (GLintptr surface, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values)
void GLAPIENTRY _mesa_VDPAUSurfaceAccessNV (GLintptr surface, GLenum access)
void GLAPIENTRY _mesa_VDPAUMapSurfacesNV (GLsizei numSurfaces, const GLintptr *surfaces)
void GLAPIENTRY _mesa_VDPAUUnmapSurfacesNV (GLsizei numSurfaces, const GLintptr *surfaces)
Macro Definition Documentation
MAX_TEXTURES
#define MAX_TEXTURES 4
Referenced by _mesa_VDPAUUnregisterSurfaceNV().
Function Documentation
_mesa_VDPAUFiniNV()
void GLAPIENTRY _mesa_VDPAUFiniNV (void)
References _mesa_error(), GET_CURRENT_CONTEXT, and unregister_surface().
_mesa_VDPAUGetSurfaceivNV()
void GLAPIENTRY _mesa_VDPAUGetSurfaceivNV (GLintptr surface, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and vdp_surface::state.
_mesa_VDPAUInitNV()
void GLAPIENTRY _mesa_VDPAUInitNV (const GLvoid * vdpDevice, const GLvoid * getProcAddress)
References _mesa_error(), and GET_CURRENT_CONTEXT.
_mesa_VDPAUIsSurfaceNV()
GLboolean GLAPIENTRY _mesa_VDPAUIsSurfaceNV (GLintptr surface)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_VDPAUMapSurfacesNV()
void GLAPIENTRY _mesa_VDPAUMapSurfacesNV (GLsizei numSurfaces, const GLintptr * surfaces)
References _mesa_error(), _mesa_get_tex_image(), _mesa_lock_texture(), _mesa_unlock_texture(), vdp_surface::access, GET_CURRENT_CONTEXT, GLAPIENTRY, vdp_surface::output, vdp_surface::state, vdp_surface::target, vdp_surface::textures, and vdp_surface::vdpSurface.
_mesa_VDPAURegisterOutputSurfaceNV()
GLintptr GLAPIENTRY _mesa_VDPAURegisterOutputSurfaceNV (const GLvoid * vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint * textureNames)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and register_surface().
_mesa_VDPAURegisterVideoSurfaceNV()
GLintptr GLAPIENTRY _mesa_VDPAURegisterVideoSurfaceNV (const GLvoid * vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint * textureNames)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and register_surface().
_mesa_VDPAUSurfaceAccessNV()
void GLAPIENTRY _mesa_VDPAUSurfaceAccessNV (GLintptr surface, GLenum access)
References _mesa_error(), vdp_surface::access, GET_CURRENT_CONTEXT, GLAPIENTRY, and vdp_surface::state.
_mesa_VDPAUUnmapSurfacesNV()
void GLAPIENTRY _mesa_VDPAUUnmapSurfacesNV (GLsizei numSurfaces, const GLintptr * surfaces)
References _mesa_error(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), vdp_surface::access, GET_CURRENT_CONTEXT, vdp_surface::output, vdp_surface::state, vdp_surface::target, vdp_surface::textures, and vdp_surface::vdpSurface.
Referenced by unregister_surface().
_mesa_VDPAUUnregisterSurfaceNV()
void GLAPIENTRY _mesa_VDPAUUnregisterSurfaceNV (GLintptr surface)
References _mesa_error(), _mesa_reference_texobj(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Immutable, MAX_TEXTURES, and vdp_surface::textures.
register_surface()
static GLintptr register_surface (struct gl_context * ctx, GLboolean isOutput, const GLvoid * vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint * textureNames) static
References _mesa_error(), _mesa_error_no_memory(), _mesa_lock_texture(), _mesa_lookup_texture(), _mesa_reference_texobj(), _mesa_tex_target_to_index(), _mesa_unlock_texture(), vdp_surface::access, CALLOC_STRUCT, gl_context::Extensions, GLAPIENTRY, gl_texture_object::Immutable, gl_extensions::NV_texture_rectangle, vdp_surface::output, vdp_surface::state, vdp_surface::target, gl_texture_object::Target, gl_texture_object::TargetIndex, vdp_surface::textures, gl_context::vdpDevice, gl_context::vdpGetProcAddress, vdp_surface::vdpSurface, and gl_context::vdpSurfaces.
Referenced by _mesa_VDPAURegisterOutputSurfaceNV(), and _mesa_VDPAURegisterVideoSurfaceNV().
unregister_surface()
static void unregister_surface (struct set_entry * entry) static
References _mesa_VDPAUUnmapSurfacesNV(), GET_CURRENT_CONTEXT, GLAPIENTRY, and vdp_surface::state.
Referenced by _mesa_VDPAUFiniNV().