Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vdpau.h File Reference
Functions
void GLAPIENTRY _mesa_VDPAUInitNV (const GLvoid *vdpDevice, const GLvoid *getProcAddress)
void GLAPIENTRY _mesa_VDPAUFiniNV (void)
GLintptr GLAPIENTRY _mesa_VDPAURegisterVideoSurfaceNV (const GLvoid *vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint *textureNames)
GLintptr GLAPIENTRY _mesa_VDPAURegisterOutputSurfaceNV (const GLvoid *vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint *textureNames)
GLboolean GLAPIENTRY _mesa_VDPAUIsSurfaceNV (GLintptr surface)
void GLAPIENTRY _mesa_VDPAUUnregisterSurfaceNV (GLintptr surface)
void GLAPIENTRY _mesa_VDPAUGetSurfaceivNV (GLintptr surface, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values)
void GLAPIENTRY _mesa_VDPAUSurfaceAccessNV (GLintptr surface, GLenum access)
void GLAPIENTRY _mesa_VDPAUMapSurfacesNV (GLsizei numSurfaces, const GLintptr *surfaces)
void GLAPIENTRY _mesa_VDPAUUnmapSurfacesNV (GLsizei numSurfaces, const GLintptr *surfaces)
Function Documentation
_mesa_VDPAUFiniNV()
void GLAPIENTRY _mesa_VDPAUFiniNV (void)
References _mesa_error(), GET_CURRENT_CONTEXT, and unregister_surface().
_mesa_VDPAUGetSurfaceivNV()
void GLAPIENTRY _mesa_VDPAUGetSurfaceivNV (GLintptr surface, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and vdp_surface::state.
_mesa_VDPAUInitNV()
void GLAPIENTRY _mesa_VDPAUInitNV (const GLvoid * vdpDevice, const GLvoid * getProcAddress)
References _mesa_error(), and GET_CURRENT_CONTEXT.
_mesa_VDPAUIsSurfaceNV()
GLboolean GLAPIENTRY _mesa_VDPAUIsSurfaceNV (GLintptr surface)
References _mesa_error(), GET_CURRENT_CONTEXT, and GLAPIENTRY.
_mesa_VDPAUMapSurfacesNV()
void GLAPIENTRY _mesa_VDPAUMapSurfacesNV (GLsizei numSurfaces, const GLintptr * surfaces)
References _mesa_error(), _mesa_get_tex_image(), _mesa_lock_texture(), _mesa_unlock_texture(), vdp_surface::access, GET_CURRENT_CONTEXT, GLAPIENTRY, vdp_surface::output, vdp_surface::state, vdp_surface::target, vdp_surface::textures, and vdp_surface::vdpSurface.
_mesa_VDPAURegisterOutputSurfaceNV()
GLintptr GLAPIENTRY _mesa_VDPAURegisterOutputSurfaceNV (const GLvoid * vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint * textureNames)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and register_surface().
_mesa_VDPAURegisterVideoSurfaceNV()
GLintptr GLAPIENTRY _mesa_VDPAURegisterVideoSurfaceNV (const GLvoid * vdpSurface, GLenum target, GLsizei numTextureNames, const GLuint * textureNames)
References _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, and register_surface().
_mesa_VDPAUSurfaceAccessNV()
void GLAPIENTRY _mesa_VDPAUSurfaceAccessNV (GLintptr surface, GLenum access)
References _mesa_error(), vdp_surface::access, GET_CURRENT_CONTEXT, GLAPIENTRY, and vdp_surface::state.
_mesa_VDPAUUnmapSurfacesNV()
void GLAPIENTRY _mesa_VDPAUUnmapSurfacesNV (GLsizei numSurfaces, const GLintptr * surfaces)
References _mesa_error(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), vdp_surface::access, GET_CURRENT_CONTEXT, vdp_surface::output, vdp_surface::state, vdp_surface::target, vdp_surface::textures, and vdp_surface::vdpSurface.
Referenced by unregister_surface().
_mesa_VDPAUUnregisterSurfaceNV()
void GLAPIENTRY _mesa_VDPAUUnregisterSurfaceNV (GLintptr surface)
References _mesa_error(), _mesa_reference_texobj(), GET_CURRENT_CONTEXT, GLAPIENTRY, gl_texture_object::Immutable, MAX_TEXTURES, and vdp_surface::textures.