Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
version.h File Reference
#include "mtypes.h"
Functions
GLuint _mesa_get_version (const struct gl_extensions *extensions, struct gl_constants *consts, gl_api api)
void _mesa_compute_version (struct gl_context *ctx)
Set the context's Version and VersionString fields.
bool _mesa_override_gl_version_contextless (struct gl_constants *consts, gl_api *apiOut, GLuint *versionOut)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
void _mesa_override_gl_version (struct gl_context *ctx)
void _mesa_override_glsl_version (struct gl_constants *consts)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
Function Documentation
_mesa_compute_version()
void _mesa_compute_version (struct gl_context * ctx)
Set the context's Version and VersionString fields.
This should only be called once as part of context initialization or to perform version check for GLX_ARB_create_context_profile.
References _mesa_get_version(), _mesa_problem(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_context::Const, create_version_string(), gl_context::Extensions, gl_constants::GLSLVersion, gl_extensions::Version, and gl_context::Version.
_mesa_get_version()
GLuint _mesa_get_version (const struct gl_extensions * extensions, struct gl_constants * consts, gl_api api)
References gl_constants::AllowHigherCompatVersion, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, compute_version(), compute_version_es1(), compute_version_es2(), and gl_constants::GLSLVersion.
Referenced by _mesa_compute_version().
_mesa_override_gl_version()
void _mesa_override_gl_version (struct gl_context * ctx)
References _mesa_is_gles(), _mesa_override_gl_version_contextless(), gl_context::API, gl_context::Const, create_version_string(), gl_context::Extensions, gl_extensions::Version, and gl_context::Version.
Referenced by _mesa_initialize_context().
_mesa_override_gl_version_contextless()
bool _mesa_override_gl_version_contextless (struct gl_constants * consts, gl_api * apiOut, GLuint * versionOut)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
Example uses of MESA_GL_VERSION_OVERRIDE:
2.1: select a compatibility (non-Core) profile with GL version 2.1 3.0: select a compatibility (non-Core) profile with GL version 3.0 3.0FC: select a Core+Forward Compatible profile with GL version 3.0 3.1: select a Core profile with GL version 3.1 3.1FC: select a Core+Forward Compatible profile with GL version 3.1
References API_OPENGL_COMPAT, API_OPENGL_CORE, gl_constants::ContextFlags, and get_gl_override().
Referenced by _mesa_override_gl_version().
_mesa_override_glsl_version()
void _mesa_override_glsl_version (struct gl_constants * consts)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
Valid values for MESA_GLSL_VERSION_OVERRIDE are integers, such as "130".
References gl_constants::GLSLVersion, and GLuint.
Referenced by _mesa_init_constants().