Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
version.c File Reference
#include <stdio.h>
#include "context.h"
#include "imports.h"
#include "mtypes.h"
#include "version.h"
#include "git_sha1.h"
Functions
static bool check_for_ending (const char *string, const char *ending)
Scans 'string' to see if it ends with 'ending'.
static void get_gl_override (gl_api api, int *version, bool *fwd_context, bool *compat_context)
Returns the gl override data.
static void create_version_string (struct gl_context *ctx, const char *prefix)
Builds the Mesa version string.
bool _mesa_override_gl_version_contextless (struct gl_constants *consts, gl_api *apiOut, GLuint *versionOut)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
void _mesa_override_gl_version (struct gl_context *ctx)
void _mesa_override_glsl_version (struct gl_constants *consts)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
static GLuint compute_version (const struct gl_extensions *extensions, const struct gl_constants *consts, gl_api api)
Examine enabled GL extensions to determine GL version.
static GLuint compute_version_es1 (const struct gl_extensions *extensions)
static GLuint compute_version_es2 (const struct gl_extensions *extensions, const struct gl_constants *consts)
GLuint _mesa_get_version (const struct gl_extensions *extensions, struct gl_constants *consts, gl_api api)
void _mesa_compute_version (struct gl_context *ctx)
Set the context's Version and VersionString fields.
Function Documentation
_mesa_compute_version()
void _mesa_compute_version (struct gl_context * ctx)
Set the context's Version and VersionString fields.
This should only be called once as part of context initialization or to perform version check for GLX_ARB_create_context_profile.
References _mesa_get_version(), _mesa_problem(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_context::Const, create_version_string(), gl_context::Extensions, gl_constants::GLSLVersion, gl_extensions::Version, and gl_context::Version.
_mesa_get_version()
GLuint _mesa_get_version (const struct gl_extensions * extensions, struct gl_constants * consts, gl_api api)
References gl_constants::AllowHigherCompatVersion, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, compute_version(), compute_version_es1(), compute_version_es2(), and gl_constants::GLSLVersion.
Referenced by _mesa_compute_version().
_mesa_override_gl_version()
void _mesa_override_gl_version (struct gl_context * ctx)
References _mesa_is_gles(), _mesa_override_gl_version_contextless(), gl_context::API, gl_context::Const, create_version_string(), gl_context::Extensions, gl_extensions::Version, and gl_context::Version.
Referenced by _mesa_initialize_context().
_mesa_override_gl_version_contextless()
bool _mesa_override_gl_version_contextless (struct gl_constants * consts, gl_api * apiOut, GLuint * versionOut)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
Example uses of MESA_GL_VERSION_OVERRIDE:
2.1: select a compatibility (non-Core) profile with GL version 2.1 3.0: select a compatibility (non-Core) profile with GL version 3.0 3.0FC: select a Core+Forward Compatible profile with GL version 3.0 3.1: select a Core profile with GL version 3.1 3.1FC: select a Core+Forward Compatible profile with GL version 3.1
References API_OPENGL_COMPAT, API_OPENGL_CORE, gl_constants::ContextFlags, and get_gl_override().
Referenced by _mesa_override_gl_version().
_mesa_override_glsl_version()
void _mesa_override_glsl_version (struct gl_constants * consts)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
Valid values for MESA_GLSL_VERSION_OVERRIDE are integers, such as "130".
References gl_constants::GLSLVersion, and GLuint.
Referenced by _mesa_init_constants().
check_for_ending()
static bool check_for_ending (const char * string, const char * ending) static
Scans 'string' to see if it ends with 'ending'.
Referenced by get_gl_override().
compute_version()
static GLuint compute_version (const struct gl_extensions * extensions, const struct gl_constants * consts, gl_api api) static
Examine enabled GL extensions to determine GL version.
References API_OPENGL_CORE, gl_extensions::ARB_arrays_of_arrays, gl_extensions::ARB_base_instance, gl_extensions::ARB_blend_func_extended, gl_extensions::ARB_buffer_storage, gl_extensions::ARB_clear_texture, gl_extensions::ARB_clip_control, gl_extensions::ARB_color_buffer_float, gl_extensions::ARB_compute_shader, gl_extensions::ARB_conditional_render_inverted, gl_extensions::ARB_conservative_depth, gl_extensions::ARB_copy_image, gl_extensions::ARB_cull_distance, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_derivative_control, gl_extensions::ARB_draw_buffers_blend, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_indirect, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_enhanced_layouts, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_ES3_1_compatibility, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_explicit_uniform_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_layer_viewport, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_gpu_shader5, gl_extensions::ARB_gpu_shader_fp64, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_instanced_arrays, gl_extensions::ARB_internalformat_query, gl_extensions::ARB_internalformat_query2, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_point_sprite, gl_extensions::ARB_query_buffer_object, gl_extensions::ARB_robust_buffer_access_behavior, gl_extensions::ARB_sample_shading, gl_extensions::ARB_seamless_cube_map, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_shader_bit_encoding, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shader_image_size, gl_extensions::ARB_shader_precision, gl_extensions::ARB_shader_storage_buffer_object, gl_extensions::ARB_shader_subroutine, gl_extensions::ARB_shader_texture_image_samples, gl_extensions::ARB_shader_texture_lod, gl_extensions::ARB_shading_language_420pack, gl_extensions::ARB_shading_language_packing, gl_extensions::ARB_shadow, gl_extensions::ARB_stencil_texturing, gl_extensions::ARB_sync, gl_extensions::ARB_tessellation_shader, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_buffer_object_rgb32, gl_extensions::ARB_texture_buffer_range, gl_extensions::ARB_texture_compression_bptc, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_mirror_clamp_to_edge, gl_extensions::ARB_texture_multisample, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_query_levels, gl_extensions::ARB_texture_query_lod, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::ARB_texture_stencil8, gl_extensions::ARB_texture_view, gl_extensions::ARB_timer_query, gl_extensions::ARB_transform_feedback2, gl_extensions::ARB_transform_feedback3, gl_extensions::ARB_transform_feedback_instanced, gl_extensions::ARB_uniform_buffer_object, gl_extensions::ARB_vertex_attrib_64bit, gl_extensions::ARB_vertex_shader, gl_extensions::ARB_vertex_type_10f_11f_11f_rev, gl_extensions::ARB_vertex_type_2_10_10_10_rev, gl_extensions::ARB_viewport_array, gl_extensions::ATI_separate_stencil, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_framebuffer_sRGB, gl_extensions::EXT_packed_float, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_transform_feedback, gl_extensions::EXT_vertex_array_bgra, gl_constants::FakeSWMSAA, gl_constants::GLSLVersion, GLuint, gl_constants::MaxSamples, gl_program_constants::MaxTextureImageUnits, gl_extensions::NV_conditional_render, gl_extensions::NV_primitive_restart, gl_extensions::NV_texture_barrier, gl_extensions::NV_texture_rectangle, and gl_constants::Program.
Referenced by _mesa_get_version().
compute_version_es1()
static GLuint compute_version_es1 (const struct gl_extensions * extensions) static
References gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_dot3, gl_extensions::EXT_point_parameters, and GLuint.
Referenced by _mesa_get_version().
compute_version_es2()
static GLuint compute_version_es2 (const struct gl_extensions * extensions, const struct gl_constants * consts) static
References gl_extensions::ARB_arrays_of_arrays, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_draw_buffers_blend, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_indirect, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_explicit_uniform_location, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_no_attachments, gl_extensions::ARB_gpu_shader5, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_internalformat_query, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_shader_atomic_counters, gl_extensions::ARB_shader_image_load_store, gl_extensions::ARB_shader_image_size, gl_extensions::ARB_shader_storage_buffer_object, gl_extensions::ARB_shader_texture_lod, gl_extensions::ARB_shading_language_packing, gl_extensions::ARB_stencil_texturing, gl_extensions::ARB_tessellation_shader, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_multisample, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_stencil8, gl_extensions::ARB_uniform_buffer_object, gl_extensions::ARB_vertex_shader, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_framebuffer_sRGB, gl_extensions::EXT_packed_float, gl_extensions::EXT_shader_integer_mix, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_transform_feedback, GLuint, gl_extensions::KHR_blend_equation_advanced, gl_extensions::KHR_robustness, gl_extensions::KHR_texture_compression_astc_ldr, gl_constants::MaxComputeWorkGroupInvocations, gl_extensions::NV_primitive_restart, gl_extensions::OES_copy_image, gl_extensions::OES_depth_texture_cube_map, gl_extensions::OES_geometry_shader, gl_extensions::OES_primitive_bounding_box, gl_extensions::OES_sample_variables, gl_extensions::OES_texture_buffer, and gl_extensions::OES_texture_cube_map_array.
Referenced by _mesa_get_version().
create_version_string()
static void create_version_string (struct gl_context * ctx, const char * prefix) static
Builds the Mesa version string.
References _mesa_snprintf(), gl_context::API, API_OPENGL_CORE, gl_context::Version, and gl_context::VersionString.
Referenced by _mesa_compute_version(), and _mesa_override_gl_version().
get_gl_override()
static void get_gl_override (gl_api api, int * version, bool * fwd_context, bool * compat_context) static
Returns the gl override data.
version > 0 indicates there is an override requested fwd_context is only valid if version > 0
References API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGL_LAST, API_OPENGLES, API_OPENGLES2, and check_for_ending().
Referenced by _mesa_override_gl_version_contextless().