Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
viewport.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set the viewport.
void GLAPIENTRY _mesa_ViewportArrayv (GLuint first, GLsizei count, const GLfloat *v)
void GLAPIENTRY _mesa_ViewportIndexedf (GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h)
void GLAPIENTRY _mesa_ViewportIndexedfv (GLuint index, const GLfloat *v)
void _mesa_set_viewport (struct gl_context *ctx, unsigned idx, GLfloat x, GLfloat y, GLfloat width, GLfloat height)
Set new viewport parameters and update derived state.
void GLAPIENTRY _mesa_DepthRange (GLclampd nearval, GLclampd farval)
Called by glDepthRange.
void GLAPIENTRY _mesa_DepthRangef (GLclampf nearval, GLclampf farval)
void GLAPIENTRY _mesa_DepthRangeArrayv (GLuint first, GLsizei count, const GLclampd *v)
Update a range DepthRange values.
void GLAPIENTRY _mesa_DepthRangeArrayfvOES (GLuint first, GLsizei count, const GLfloat *v)
void GLAPIENTRY _mesa_DepthRangeIndexed (GLuint index, GLclampd n, GLclampd f)
Update a single DepthRange.
void GLAPIENTRY _mesa_DepthRangeIndexedfOES (GLuint index, GLfloat n, GLfloat f)
void _mesa_set_depth_range (struct gl_context *ctx, unsigned idx, GLclampd nearval, GLclampd farval)
void _mesa_init_viewport (struct gl_context *ctx)
Initialize the context viewport attribute group.
void GLAPIENTRY _mesa_ClipControl (GLenum origin, GLenum depth)
void _mesa_get_viewport_xform (struct gl_context *ctx, unsigned i, float scale[3], float translate[3])
Computes the scaling and the translation part of the viewport transform matrix of the.
Function Documentation
_mesa_ClipControl()
void GLAPIENTRY _mesa_ClipControl (GLenum origin, GLenum depth)
References _mesa_debug(), _mesa_enum_to_string(), _mesa_error(), _NEW_POLYGON, _NEW_TRANSFORM, _NEW_VIEWPORT, ASSERT_OUTSIDE_BEGIN_END, FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_PopAttrib().
_mesa_DepthRange()
void GLAPIENTRY _mesa_DepthRange (GLclampd nearval, GLclampd farval)
Called by glDepthRange.
Parameters
nearval specifies the Z buffer value which should correspond to the near clip plane
farval specifies the Z buffer value which should correspond to the far clip plane
References _mesa_debug(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, set_depth_range_no_notify(), and VERBOSE_API.
Referenced by _mesa_DepthRangef().
_mesa_DepthRangeArrayfvOES()
void GLAPIENTRY _mesa_DepthRangeArrayfvOES (GLuint first, GLsizei count, const GLfloat * v)
References _mesa_debug(), _mesa_error(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, set_depth_range_no_notify(), and VERBOSE_API.
_mesa_DepthRangeArrayv()
void GLAPIENTRY _mesa_DepthRangeArrayv (GLuint first, GLsizei count, const GLclampd * v)
Update a range DepthRange values.
Parameters
first starting array index
count count of DepthRange items to update
v pointer to memory containing GLclampd near and far clip-plane values
References _mesa_debug(), _mesa_error(), gl_depthrange_inputs::Far, GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, gl_depthrange_inputs::Near, set_depth_range_no_notify(), and VERBOSE_API.
_mesa_DepthRangef()
void GLAPIENTRY _mesa_DepthRangef (GLclampf nearval, GLclampf farval)
References _mesa_DepthRange(), and GLAPIENTRY.
Referenced by _mesa_DepthRangex().
_mesa_DepthRangeIndexed()
void GLAPIENTRY _mesa_DepthRangeIndexed (GLuint index, GLclampd nearval, GLclampd farval)
Update a single DepthRange.
Parameters
index array index to update
nearval specifies the Z buffer value which should correspond to the near clip plane
farval specifies the Z buffer value which should correspond to the far clip plane
References _mesa_debug(), _mesa_error(), _mesa_set_depth_range(), GET_CURRENT_CONTEXT, GLAPIENTRY, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_DepthRangeIndexedfOES().
_mesa_DepthRangeIndexedfOES()
void GLAPIENTRY _mesa_DepthRangeIndexedfOES (GLuint index, GLfloat n, GLfloat f)
References _mesa_DepthRangeIndexed().
_mesa_get_viewport_xform()
void _mesa_get_viewport_xform (struct gl_context * ctx, unsigned i, float scale[3], float translate[3])
Computes the scaling and the translation part of the viewport transform matrix of the.
Parameters
i-th viewport and writes that into
scale and
translate.
References gl_transform_attrib::ClipDepthMode, gl_transform_attrib::ClipOrigin, gl_viewport_attrib::Far, gl_viewport_attrib::Height, gl_viewport_attrib::Near, gl_context::Transform, gl_context::ViewportArray, gl_viewport_attrib::Width, x, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
Referenced by _mesa_RasterPos().
_mesa_init_viewport()
void _mesa_init_viewport (struct gl_context * ctx)
Initialize the context viewport attribute group.
Parameters
ctx the GL context.
References gl_transform_attrib::ClipDepthMode, gl_transform_attrib::ClipOrigin, gl_viewport_attrib::Far, GLAPIENTRY, gl_viewport_attrib::Height, MAX_VIEWPORTS, gl_viewport_attrib::Near, gl_context::Transform, gl_context::ViewportArray, gl_viewport_attrib::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
Referenced by init_attrib_groups().
_mesa_set_depth_range()
void _mesa_set_depth_range (struct gl_context * ctx, unsigned idx, GLclampd nearval, GLclampd farval)
References dd_function_table::DepthRange, gl_context::Driver, GLAPIENTRY, and set_depth_range_no_notify().
Referenced by _mesa_DepthRangeIndexed(), and _mesa_PopAttrib().
_mesa_set_viewport()
void _mesa_set_viewport (struct gl_context * ctx, unsigned idx, GLfloat x, GLfloat y, GLfloat width, GLfloat height)
Set new viewport parameters and update derived state.
Usually called from _mesa_Viewport().
Parameters
ctx GL context.
idx Index of the viewport to be updated.
x,y coordinates of the lower left corner of the viewport rectangle.
width width of the viewport rectangle.
height height of the viewport rectangle.
References gl_context::Driver, GLAPIENTRY, set_viewport_no_notify(), and dd_function_table::Viewport.
Referenced by _mesa_check_init_viewport(), _mesa_PopAttrib(), and ViewportIndexedf().
_mesa_Viewport()
void GLAPIENTRY _mesa_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set the viewport.
See also
Called via glViewport() or display list execution.
Flushes the vertices and calls _mesa_set_viewport() with the given parameters.
References _mesa_debug(), _mesa_error(), FLUSH_VERTICES, GET_CURRENT_CONTEXT, MESA_VERBOSE, set_viewport_no_notify(), and VERBOSE_API.
_mesa_ViewportArrayv()
void GLAPIENTRY _mesa_ViewportArrayv (GLuint first, GLsizei count, const GLfloat * v)
References _mesa_debug(), _mesa_error(), GET_CURRENT_CONTEXT, gl_viewport_inputs::Height, MESA_VERBOSE, set_viewport_no_notify(), VERBOSE_API, gl_viewport_inputs::Width, gl_viewport_inputs::X, and gl_viewport_inputs::Y.
_mesa_ViewportIndexedf()
void GLAPIENTRY _mesa_ViewportIndexedf (GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h)
References GLAPIENTRY, and ViewportIndexedf().
_mesa_ViewportIndexedfv()
void GLAPIENTRY _mesa_ViewportIndexedfv (GLuint index, const GLfloat * v)
References ViewportIndexedf().