Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vtxfmt.h File Reference
#include "mtypes.h"
Functions
void _mesa_install_exec_vtxfmt (struct gl_context *ctx, const GLvertexformat *vfmt)
Install per-vertex functions into the API dispatch table for execution.
void _mesa_install_save_vtxfmt (struct gl_context *ctx, const GLvertexformat *vfmt)
Install per-vertex functions into the API dispatch table for display list compilation.
void _mesa_initialize_vbo_vtxfmt (struct gl_context *ctx)
Install VBO vtxfmt functions.
Detailed Description
Author
Keith Whitwell keith.nosp@m.w@vm.nosp@m.ware..nosp@m.com
Gareth Hughes
Function Documentation
_mesa_initialize_vbo_vtxfmt()
void _mesa_initialize_vbo_vtxfmt (struct gl_context * ctx)
Install VBO vtxfmt functions.
This function depends on ctx->Version.
References _mesa_install_exec_vtxfmt(), _mesa_install_save_vtxfmt(), gl_context::API, API_OPENGL_COMPAT, vbo_context::exec, gl_context::ListState, gl_dlist_state::ListVtxfmt, and vbo_exec_context::vtxfmt.
_mesa_install_exec_vtxfmt()
void _mesa_install_exec_vtxfmt (struct gl_context * ctx, const GLvertexformat * vfmt)
Install per-vertex functions into the API dispatch table for execution.
References gl_context::BeginEnd, gl_context::Exec, and install_vtxfmt().
Referenced by _mesa_initialize_vbo_vtxfmt().
_mesa_install_save_vtxfmt()
void _mesa_install_save_vtxfmt (struct gl_context * ctx, const GLvertexformat * vfmt)
Install per-vertex functions into the API dispatch table for display list compilation.
References _mesa_is_desktop_gl(), install_vtxfmt(), and gl_context::Save.
Referenced by _mesa_initialize_vbo_vtxfmt().