Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast.h File Reference
#include "list.h"
#include "glsl_parser_extras.h"
Data Structures
class ast_node
Base class of all abstract syntax tree nodes.
class ast_expression
Representation of any sort of expression.
class ast_expression_bin
class ast_function_expression
Subclass of expressions for function calls.
class ast_subroutine_list
class ast_array_specifier
class ast_layout_expression
class ast_aggregate_initializer
C-style aggregate initialization class.
class ast_compound_statement
class ast_declaration
struct ast_type_qualifier
class ast_struct_specifier
class ast_type_specifier
class ast_fully_specified_type
class ast_declarator_list
class ast_parameter_declarator
class ast_function
class ast_expression_statement
class ast_case_label
class ast_case_label_list
class ast_case_statement
class ast_case_statement_list
class ast_switch_body
class ast_selection_statement
class ast_switch_statement
class ast_iteration_statement
class ast_jump_statement
class ast_function_definition
class ast_interface_block
class ast_tcs_output_layout
AST node representing a declaration of the output layout for tessellation control shaders.
class ast_gs_input_layout
AST node representing a declaration of the input layout for geometry shaders.
class ast_cs_input_layout
AST node representing a decalaration of the input layout for compute shaders.
Macros
#define AST_NUM_OPERATORS (ast_aggregate + 1)
Number of possible operators for an ast_expression.
Enumerations
enum ast_operators {
ast_assign, ast_plus, ast_neg, ast_add,
ast_sub, ast_mul, ast_div, ast_mod,
ast_lshift, ast_rshift, ast_less, ast_greater,
ast_lequal, ast_gequal, ast_equal, ast_nequal,
ast_bit_and, ast_bit_xor, ast_bit_or, ast_bit_not,
ast_logic_and, ast_logic_xor, ast_logic_or, ast_logic_not,
ast_mul_assign, ast_div_assign, ast_mod_assign, ast_add_assign,
ast_sub_assign, ast_ls_assign, ast_rs_assign, ast_and_assign,
ast_xor_assign, ast_or_assign, ast_conditional, ast_pre_inc,
ast_pre_dec, ast_post_inc, ast_post_dec, ast_field_selection,
ast_array_index, ast_unsized_array_dim, ast_function_call, ast_identifier,
ast_int_constant, ast_uint_constant, ast_float_constant, ast_bool_constant,
ast_double_constant, ast_int64_constant, ast_uint64_constant, ast_sequence
}
Operators for AST expression nodes.
enum { ast_precision_none = 0, ast_precision_high, ast_precision_medium, ast_precision_low }
enum {
ast_depth_none = 0, ast_depth_any, ast_depth_greater, ast_depth_less,
ast_depth_unchanged
}
Functions
void _mesa_ast_to_hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
ir_rvalue * _mesa_ast_field_selection_to_hir (const ast_expression *expr, exec_list *instructions, struct _mesa_glsl_parse_state *state)
ir_rvalue * _mesa_ast_array_index_to_hir (void *mem_ctx, struct _mesa_glsl_parse_state *state, ir_rvalue *array, ir_rvalue *idx, YYLTYPE &loc, YYLTYPE &idx_loc)
void _mesa_ast_set_aggregate_type (const glsl_type *type, ast_expression *expr)
Recurses through <type> and <expr> if <expr> is an aggregate initializer and sets <expr>'s <constructor_type> field to <type>.
void emit_function (_mesa_glsl_parse_state *state, ir_function *f)
void check_builtin_array_max_size (const char *name, unsigned size, YYLTYPE loc, struct _mesa_glsl_parse_state *state)
If name refers to a builtin array whose maximum allowed size is less than size, report an error and return true.
void _mesa_ast_process_interface_block (YYLTYPE *locp, _mesa_glsl_parse_state *state, ast_interface_block *const block, const struct ast_type_qualifier &q)
bool process_qualifier_constant (struct _mesa_glsl_parse_state *state, YYLTYPE *loc, const char *qual_indentifier, ast_expression *const_expression, unsigned *value)
Macro Definition Documentation
AST_NUM_OPERATORS
#define AST_NUM_OPERATORS (ast_aggregate + 1)
Number of possible operators for an ast_expression.
This is done as a define instead of as an additional value in the enum so that the compiler won't generate spurious messages like "warning: enumeration value ‘ast_num_operators’ not handled in switch"
Referenced by ast_expression::do_hir().
Function Documentation
_mesa_ast_array_index_to_hir()
ir_rvalue* _mesa_ast_array_index_to_hir (void * mem_ctx, struct _mesa_glsl_parse_state * state, ir_rvalue * array, ir_rvalue * idx, YYLTYPE & loc, YYLTYPE & idx_loc)
References _mesa_glsl_error(), _mesa_glsl_warning(), get_implicit_array_size(), and update_max_array_access().
Referenced by ast_cs_input_layout::ast_cs_input_layout(), ast_expression::do_hir(), and generate_array_index().
_mesa_ast_field_selection_to_hir()
ir_rvalue* _mesa_ast_field_selection_to_hir (const ast_expression * expr, exec_list * instructions, struct _mesa_glsl_parse_state * state)
References _mesa_glsl_error(), ast_node::get_location(), ast_expression::hir(), ast_expression::identifier, ast_expression::primary_expression, and ast_expression::subexpressions.
Referenced by ast_cs_input_layout::ast_cs_input_layout(), and ast_expression::do_hir().
_mesa_ast_process_interface_block()
void _mesa_ast_process_interface_block (YYLTYPE * locp, _mesa_glsl_parse_state * state, ast_interface_block *const block, const struct ast_type_qualifier & q)
References _mesa_glsl_error(), _mesa_glsl_warning(), ast_interface_block::declarations, ast_interface_block::default_layout, ast_type_qualifier::flags, foreach_list_typed, ast_type_qualifier::i, ast_interface_block::instance_name, ast_type_qualifier::q, ast_type_qualifier::stream, and ast_type_qualifier::xfb_buffer.
Referenced by ast_cs_input_layout::ast_cs_input_layout().
_mesa_ast_set_aggregate_type()
void _mesa_ast_set_aggregate_type (const glsl_type * type, ast_expression * expr)
Recurses through <type> and <expr> if <expr> is an aggregate initializer and sets <expr>'s <constructor_type> field to <type>.
Gives later functions (process_array_constructor, et al) sufficient information to do type checking.
Operates on assignments involving an aggregate initializer. E.g.,
vec4 pos = {1.0, -1.0, 0.0, 1.0};
or more ridiculously,
struct S { vec4 v[2]; };
struct { S a[2], b; int c; } aggregate = { { { { {1.0, 2.0, 3.0, 4.0}, // a[0].v[0] {5.0, 6.0, 7.0, 8.0} // a[0].v[1] } // a[0].v }, // a[0] { { {1.0, 2.0, 3.0, 4.0}, // a[1].v[0] {5.0, 6.0, 7.0, 8.0} // a[1].v[1] } // a[1].v } // a[1] }, // a { { {1.0, 2.0, 3.0, 4.0}, // b.v[0] {5.0, 6.0, 7.0, 8.0} // b.v[1] } // b.v }, // b 4 // c };
This pass is necessary because the right-hand side of <type> e = { ... } doesn't contain sufficient information to determine if the types match.
References ast_aggregate_initializer::constructor_type, exec_node_data, ir_builder::expr(), ast_expression::expressions, exec_node::next, and ast_expression::oper.
Referenced by ast_cs_input_layout::ast_cs_input_layout(), and process_initializer().
_mesa_ast_to_hir()
void _mesa_ast_to_hir (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References _mesa_glsl_error(), _mesa_glsl_initialize_variables(), detect_conflicting_assignments(), detect_recursion_unlinked(), foreach_in_list_safe, foreach_list_typed, read_from_write_only_variable_visitor::get_variable(), and remove_per_vertex_blocks().
Referenced by _mesa_glsl_compile_shader(), ast_cs_input_layout::ast_cs_input_layout(), and test_optpass().
check_builtin_array_max_size()
void check_builtin_array_max_size (const char * name, unsigned size, YYLTYPE loc, struct _mesa_glsl_parse_state * state)
If name refers to a builtin array whose maximum allowed size is less than size, report an error and return true.
Otherwise return false.
References _mesa_glsl_error().
Referenced by ast_cs_input_layout::ast_cs_input_layout(), get_variable_being_redeclared(), ast_interface_block::hir(), and update_max_array_access().
emit_function()
void emit_function (_mesa_glsl_parse_state * state, ir_function * f)
Referenced by ast_cs_input_layout::ast_cs_input_layout(), and ast_function::hir().
process_qualifier_constant()
bool process_qualifier_constant (struct _mesa_glsl_parse_state * state, YYLTYPE * loc, const char * qual_indentifier, ast_expression * const_expression, unsigned * value)
References _mesa_glsl_error(), and ast_expression::hir().
Referenced by apply_explicit_binding(), apply_explicit_location(), apply_layout_qualifier_to_variable(), ast_cs_input_layout::ast_cs_input_layout(), ast_layout_expression::ast_layout_expression(), ast_process_struct_or_iface_block_members(), handle_tess_ctrl_shader_output_decl(), ast_struct_specifier::hir(), ast_declarator_list::hir(), ast_function::hir(), ast_interface_block::hir(), ast_tcs_output_layout::hir(), ast_cs_input_layout::hir(), ast_type_qualifier::push_to_global(), and set_shader_inout_layout().