Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_to_hir.cpp File Reference
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "ast.h"
#include "compiler/glsl_types.h"
#include "util/hash_table.h"
#include "main/macros.h"
#include "main/shaderobj.h"
#include "ir.h"
#include "ir_builder.h"
#include "builtin_functions.h"
Data Structures
class read_from_write_only_variable_visitor
Visitor class that finds the first instance of any write-only variable that is ever read, if any.
class interface_block_usage_visitor
Visitor class which detects whether a given interface block has been used.
Functions
static void detect_conflicting_assignments (struct _mesa_glsl_parse_state *state, exec_list *instructions)
static void remove_per_vertex_blocks (exec_list *instructions, _mesa_glsl_parse_state *state, ir_variable_mode mode)
void _mesa_ast_to_hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static ir_expression_operation get_implicit_conversion_operation (const glsl_type *to, const glsl_type *from, struct _mesa_glsl_parse_state *state)
static bool apply_implicit_conversion (const glsl_type *to, ir_rvalue *&from, struct _mesa_glsl_parse_state *state)
If a conversion is available, convert one operand to a different type.
static const struct glsl_type * arithmetic_result_type (ir_rvalue *&value_a, ir_rvalue *&value_b, bool multiply, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static const struct glsl_type * unary_arithmetic_result_type (const struct glsl_type *type, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static const struct glsl_type * bit_logic_result_type (ir_rvalue *&value_a, ir_rvalue *&value_b, ast_operators op, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
Return the result type of a bit-logic operation.
static const struct glsl_type * modulus_result_type (ir_rvalue *&value_a, ir_rvalue *&value_b, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static const struct glsl_type * relational_result_type (ir_rvalue *&value_a, ir_rvalue *&value_b, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static const struct glsl_type * shift_result_type (const struct glsl_type *type_a, const struct glsl_type *type_b, ast_operators op, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
Return the result type of a bit-shift operation.
static ir_rvalue * find_innermost_array_index (ir_rvalue *rv)
Returns the innermost array index expression in an rvalue tree.
static ir_rvalue * validate_assignment (struct _mesa_glsl_parse_state *state, YYLTYPE loc, ir_rvalue *lhs, ir_rvalue *rhs, bool is_initializer)
Validates that a value can be assigned to a location with a specified type.
static void mark_whole_array_access (ir_rvalue *access)
static bool do_assignment (exec_list *instructions, struct _mesa_glsl_parse_state *state, const char *non_lvalue_description, ir_rvalue *lhs, ir_rvalue *rhs, ir_rvalue **out_rvalue, bool needs_rvalue, bool is_initializer, YYLTYPE lhs_loc)
static ir_rvalue * get_lvalue_copy (exec_list *instructions, ir_rvalue *lvalue)
static ir_rvalue * do_comparison (void *mem_ctx, int operation, ir_rvalue *op0, ir_rvalue *op1)
ir_rvalue * get_scalar_boolean_operand (exec_list *instructions, struct _mesa_glsl_parse_state *state, ast_expression *parent_expr, int operand, const char *operand_name, bool *error_emitted)
void check_builtin_array_max_size (const char *name, unsigned size, YYLTYPE loc, struct _mesa_glsl_parse_state *state)
If name refers to a builtin array whose maximum allowed size is less than size, report an error and return true.
static ir_rvalue * constant_one_for_inc_dec (void *ctx, const glsl_type *type)
Create the constant 1, of a which is appropriate for incrementing and decrementing values of the given GLSL type.
static unsigned process_array_size (exec_node *node, struct _mesa_glsl_parse_state *state)
Evaluate the given exec_node (which should be an ast_node representing a single array dimension) and return its integer value.
static const glsl_type * process_array_type (YYLTYPE *loc, const glsl_type *base, ast_array_specifier *array_specifier, struct _mesa_glsl_parse_state *state)
static bool precision_qualifier_allowed (const glsl_type *type)
static const char * get_type_name_for_precision_qualifier (const glsl_type *type)
From the OpenGL ES 3.0 spec, 4.5.4 Default Precision Qualifiers:
static unsigned select_gles_precision (unsigned qual_precision, const glsl_type *type, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static bool is_varying_var (ir_variable *var, gl_shader_stage target)
Determine whether a toplevel variable declaration declares a varying.
static bool is_allowed_invariant (ir_variable *var, struct _mesa_glsl_parse_state *state)
static void validate_matrix_layout_for_type (struct _mesa_glsl_parse_state *state, YYLTYPE *loc, const glsl_type *type, ir_variable *var)
Matrix layout qualifiers are only allowed on certain types.
static bool validate_xfb_buffer_qualifier (YYLTYPE *loc, struct _mesa_glsl_parse_state *state, unsigned xfb_buffer)
static bool validate_xfb_offset_qualifier (YYLTYPE *loc, struct _mesa_glsl_parse_state *state, int xfb_offset, const glsl_type *type, unsigned component_size)
static bool validate_stream_qualifier (YYLTYPE *loc, struct _mesa_glsl_parse_state *state, unsigned stream)
static void apply_explicit_binding (struct _mesa_glsl_parse_state *state, YYLTYPE *loc, ir_variable *var, const glsl_type *type, const ast_type_qualifier *qual)
static void validate_interpolation_qualifier (struct _mesa_glsl_parse_state *state, YYLTYPE *loc, const glsl_interp_mode interpolation, const struct ast_type_qualifier *qual, const struct glsl_type *var_type, ir_variable_mode mode)
static glsl_interp_mode interpret_interpolation_qualifier (const struct ast_type_qualifier *qual, const struct glsl_type *var_type, ir_variable_mode mode, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static void apply_explicit_location (const struct ast_type_qualifier *qual, ir_variable *var, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static void apply_image_qualifier_to_variable (const struct ast_type_qualifier *qual, ir_variable *var, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static const char * get_layout_qualifier_string (bool origin_upper_left, bool pixel_center_integer)
static bool is_conflicting_fragcoord_redeclaration (struct _mesa_glsl_parse_state *state, const struct ast_type_qualifier *qual)
static void validate_array_dimensions (const glsl_type *t, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static void apply_layout_qualifier_to_variable (const struct ast_type_qualifier *qual, ir_variable *var, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static void apply_type_qualifier_to_variable (const struct ast_type_qualifier *qual, ir_variable *var, struct _mesa_glsl_parse_state *state, YYLTYPE *loc, bool is_parameter)
static ir_variable * get_variable_being_redeclared (ir_variable *var, YYLTYPE loc, struct _mesa_glsl_parse_state *state, bool allow_all_redeclarations, bool *is_redeclaration)
Get the variable that is being redeclared by this declaration or if it does not exist, the current declared variable.
ir_rvalue * process_initializer (ir_variable *var, ast_declaration *decl, ast_fully_specified_type *type, exec_list *initializer_instructions, struct _mesa_glsl_parse_state *state)
Generate the IR for an initializer in a variable declaration.
static void validate_layout_qualifier_vertex_count (struct _mesa_glsl_parse_state *state, YYLTYPE loc, ir_variable *var, unsigned num_vertices, unsigned *size, const char *var_category)
static void handle_tess_ctrl_shader_output_decl (struct _mesa_glsl_parse_state *state, YYLTYPE loc, ir_variable *var)
static void handle_tess_shader_input_decl (struct _mesa_glsl_parse_state *state, YYLTYPE loc, ir_variable *var)
Do additional processing necessary for tessellation control/evaluation shader input declarations.
static void handle_geometry_shader_input_decl (struct _mesa_glsl_parse_state *state, YYLTYPE loc, ir_variable *var)
Do additional processing necessary for geometry shader input declarations (this covers both interface blocks arrays and bare input variables).
void validate_identifier (const char *identifier, YYLTYPE loc, struct _mesa_glsl_parse_state *state)
void emit_function (_mesa_glsl_parse_state *state, ir_function *f)
static bool compare_case_value (const void *a, const void *b)
static unsigned key_contents (const void *key)
static bool is_valid_default_precision_type (const struct glsl_type *const type)
Determine if the given type is valid for establishing a default precision qualifier.
static unsigned ast_process_struct_or_iface_block_members (exec_list *instructions, struct _mesa_glsl_parse_state *state, exec_list *declarations, glsl_struct_field **fields_ret, bool is_interface, enum glsl_matrix_layout matrix_layout, bool allow_reserved_names, ir_variable_mode var_mode, ast_type_qualifier *layout, unsigned block_stream, unsigned block_xfb_buffer, unsigned block_xfb_offset, unsigned expl_location, unsigned expl_align)
Process a structure or interface block tree into an array of structure fields.
static bool is_unsized_array_last_element (ir_variable *v)
static void apply_memory_qualifiers (ir_variable *var, glsl_struct_field field)
Function Documentation
_mesa_ast_to_hir()
void _mesa_ast_to_hir (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References _mesa_glsl_error(), _mesa_glsl_initialize_variables(), detect_conflicting_assignments(), detect_recursion_unlinked(), foreach_in_list_safe, foreach_list_typed, read_from_write_only_variable_visitor::get_variable(), and remove_per_vertex_blocks().
Referenced by _mesa_glsl_compile_shader(), ast_cs_input_layout::ast_cs_input_layout(), and test_optpass().
apply_explicit_binding()
static void apply_explicit_binding (struct _mesa_glsl_parse_state * state, YYLTYPE * loc, ir_variable * var, const glsl_type * type, const ast_type_qualifier * qual) static
References _mesa_glsl_error(), ast_type_qualifier::binding, ast_type_qualifier::flags, process_qualifier_constant(), and ast_type_qualifier::q.
Referenced by apply_layout_qualifier_to_variable(), and ast_interface_block::hir().
apply_explicit_location()
static void apply_explicit_location (const struct ast_type_qualifier * qual, ir_variable * var, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), ast_type_qualifier::flags, ast_type_qualifier::index, ast_type_qualifier::is_subroutine_decl(), ast_type_qualifier::location, mode_string(), process_qualifier_constant(), and ast_type_qualifier::q.
Referenced by apply_layout_qualifier_to_variable().
apply_image_qualifier_to_variable()
static void apply_image_qualifier_to_variable (const struct ast_type_qualifier * qual, ir_variable * var, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), ast_type_qualifier::flags, ast_type_qualifier::image_base_type, ast_type_qualifier::image_format, and ast_type_qualifier::q.
Referenced by apply_type_qualifier_to_variable().
apply_implicit_conversion()
static bool apply_implicit_conversion (const glsl_type * to, ir_rvalue *& from, struct _mesa_glsl_parse_state * state) static
If a conversion is available, convert one operand to a different type.
The from ir_rvalue is converted "in place".
Parameters
to Type that the operand it to be converted to
from Operand that is being converted
state GLSL compiler state
Returns
If a conversion is possible (or unnecessary), true is returned. Otherwise false is returned.
References get_implicit_conversion_operation().
Referenced by arithmetic_result_type(), bit_logic_result_type(), ast_expression::do_hir(), ast_case_label::hir(), ast_jump_statement::hir(), modulus_result_type(), relational_result_type(), and validate_assignment().
apply_layout_qualifier_to_variable()
static void apply_layout_qualifier_to_variable (const struct ast_type_qualifier * qual, ir_variable * var, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), _mesa_glsl_warning(), apply_explicit_binding(), apply_explicit_location(), ast_depth_any, ast_depth_greater, ast_depth_less, ast_depth_unchanged, ast_type_qualifier::component, ast_type_qualifier::depth_type, ast_type_qualifier::flags, get_layout_qualifier_string(), ast_type_qualifier::has_layout(), is_conflicting_fragcoord_redeclaration(), ast_type_qualifier::offset, process_qualifier_constant(), ast_type_qualifier::q, ast_type_qualifier::stream, ast_type_qualifier::subroutine_list, validate_matrix_layout_for_type(), validate_stream_qualifier(), validate_xfb_buffer_qualifier(), validate_xfb_offset_qualifier(), ast_type_qualifier::xfb_buffer, and ast_type_qualifier::xfb_stride.
Referenced by ast_declarator_list::hir().
apply_memory_qualifiers()
static void apply_memory_qualifiers (ir_variable * var, glsl_struct_field field) static
Referenced by ast_interface_block::hir().
apply_type_qualifier_to_variable()
static void apply_type_qualifier_to_variable (const struct ast_type_qualifier * qual, ir_variable * var, struct _mesa_glsl_parse_state * state, YYLTYPE * loc, bool is_parameter) static
References _mesa_glsl_error(), apply_image_qualifier_to_variable(), ast_type_qualifier::flags, ast_type_qualifier::i, interpret_interpolation_qualifier(), ast_type_qualifier::is_subroutine_decl(), is_varying_var(), ast_type_qualifier::precision, ast_type_qualifier::q, and select_gles_precision().
Referenced by ast_declarator_list::hir(), and ast_parameter_declarator::hir().
arithmetic_result_type()
static const struct glsl_type* arithmetic_result_type (ir_rvalue *& value_a, ir_rvalue *& value_b, bool multiply, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), and apply_implicit_conversion().
Referenced by ast_expression::do_hir().
ast_process_struct_or_iface_block_members()
static unsigned ast_process_struct_or_iface_block_members (exec_list * instructions, struct _mesa_glsl_parse_state * state, exec_list * declarations, glsl_struct_field ** fields_ret, bool is_interface, enum glsl_matrix_layout matrix_layout, bool allow_reserved_names, ir_variable_mode var_mode, ast_type_qualifier * layout, unsigned block_stream, unsigned block_xfb_buffer, unsigned block_xfb_offset, unsigned expl_location, unsigned expl_align) static
Process a structure or interface block tree into an array of structure fields.
After parsing, where there are some syntax differnces, structures and interface blocks are almost identical. They are similar enough that the AST for each can be processed the same way into a set of glsl_struct_field to describe the members.
If we're processing an interface block, var_mode should be the type of the interface block (ir_var_shader_in, ir_var_shader_out, ir_var_uniform or ir_var_shader_storage). If we're processing a structure, var_mode should be ir_var_auto.
Returns
The number of fields processed. A pointer to the array structure fields is stored in *fields_ret.
References _mesa_glsl_error(), ast_type_qualifier::align, ast_type_qualifier::explicit_xfb_buffer, ast_type_qualifier::flags, foreach_list_typed, ast_type_qualifier::has_auxiliary_storage(), ast_type_qualifier::has_interpolation(), interpret_interpolation_qualifier(), ast_type_qualifier::location, ast_type_qualifier::offset, ast_type_qualifier::precision, process_array_type(), process_qualifier_constant(), ast_type_qualifier::q, ast_type_qualifier::stream, validate_array_dimensions(), validate_identifier(), validate_matrix_layout_for_type(), ast_type_qualifier::xfb_buffer, and ast_type_qualifier::xfb_stride.
Referenced by ast_struct_specifier::hir(), and ast_interface_block::hir().
bit_logic_result_type()
static const struct glsl_type* bit_logic_result_type (ir_rvalue *& value_a, ir_rvalue *& value_b, ast_operators op, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
Return the result type of a bit-logic operation.
If the given types to the bit-logic operator are invalid, return glsl_type::error_type.
Parameters
value_a LHS of bit-logic op
value_b RHS of bit-logic op
References _mesa_glsl_error(), _mesa_glsl_warning(), apply_implicit_conversion(), and ast_expression::operator_string().
Referenced by ast_expression::do_hir().
check_builtin_array_max_size()
void check_builtin_array_max_size (const char * name, unsigned size, YYLTYPE loc, struct _mesa_glsl_parse_state * state)
If name refers to a builtin array whose maximum allowed size is less than size, report an error and return true.
Otherwise return false.
References _mesa_glsl_error().
Referenced by ast_cs_input_layout::ast_cs_input_layout(), get_variable_being_redeclared(), ast_interface_block::hir(), and update_max_array_access().
compare_case_value()
static bool compare_case_value (const void * a, const void * b) static
Referenced by ast_switch_statement::hir().
constant_one_for_inc_dec()
static ir_rvalue* constant_one_for_inc_dec (void * ctx, const glsl_type * type) static
Create the constant 1, of a which is appropriate for incrementing and decrementing values of the given GLSL type.
For example, if type is vec4, this creates a constant value of 1.0 having type float.
If the given type is invalid for increment and decrement operators, return a floating point 1–the error will be detected later.
Referenced by ast_expression::do_hir().
detect_conflicting_assignments()
static void detect_conflicting_assignments (struct _mesa_glsl_parse_state * state, exec_list * instructions) static
References _mesa_glsl_error(), and foreach_in_list.
Referenced by _mesa_ast_to_hir().
do_assignment()
static bool do_assignment (exec_list * instructions, struct _mesa_glsl_parse_state * state, const char * non_lvalue_description, ir_rvalue * lhs, ir_rvalue * rhs, ir_rvalue ** out_rvalue, bool needs_rvalue, bool is_initializer, YYLTYPE lhs_loc) static
References _mesa_glsl_error(), ir_builder::assign(), mark_whole_array_access(), and validate_assignment().
Referenced by ast_expression::do_hir(), and process_initializer().
do_comparison()
static ir_rvalue* do_comparison (void * mem_ctx, int operation, ir_rvalue * op0, ir_rvalue * op1) static
References mark_whole_array_access().
Referenced by ast_expression::do_hir().
emit_function()
void emit_function (_mesa_glsl_parse_state * state, ir_function * f)
Referenced by ast_cs_input_layout::ast_cs_input_layout(), and ast_function::hir().
find_innermost_array_index()
static ir_rvalue* find_innermost_array_index (ir_rvalue * rv) static
Returns the innermost array index expression in an rvalue tree.
This is the largest indexing level – if an array of blocks, then it is the block index rather than an indexing expression for an array-typed member of an array of blocks.
Referenced by validate_assignment().
get_implicit_conversion_operation()
static ir_expression_operation get_implicit_conversion_operation (const glsl_type * to, const glsl_type * from, struct _mesa_glsl_parse_state * state) static
Referenced by apply_implicit_conversion().
get_layout_qualifier_string()
static const char* get_layout_qualifier_string (bool origin_upper_left, bool pixel_center_integer) inline static
Referenced by apply_layout_qualifier_to_variable().
get_lvalue_copy()
static ir_rvalue* get_lvalue_copy (exec_list * instructions, ir_rvalue * lvalue) static
Referenced by ast_expression::do_hir().
get_scalar_boolean_operand()
ir_rvalue* get_scalar_boolean_operand (exec_list * instructions, struct _mesa_glsl_parse_state * state, ast_expression * parent_expr, int operand, const char * operand_name, bool * error_emitted)
References _mesa_glsl_error(), ir_builder::expr(), ast_node::get_location(), ast_expression::hir(), ast_expression::oper, ast_expression::operator_string(), and ast_expression::subexpressions.
Referenced by ast_expression::do_hir().
get_type_name_for_precision_qualifier()
static const char* get_type_name_for_precision_qualifier (const glsl_type * type) static
From the OpenGL ES 3.0 spec, 4.5.4 Default Precision Qualifiers:
"The precision statement
precision precision-qualifier type;
can be used to establish a default precision qualifier. The type field can be either int or float or any of the sampler types, (...) If type is float, the directive applies to non-precision-qualified floating point type (scalar, vector, and matrix) declarations. If type is int, the directive applies to all non-precision-qualified integer type (scalar, vector, signed, and unsigned) declarations."
We use the symbol table to keep the values of the default precisions for each 'type' in each scope and we use the 'type' string from the precision statement as key in the symbol table. When we want to retrieve the default precision associated with a given glsl_type we need to know the type string associated with it. This is what this function returns.
Referenced by select_gles_precision().
get_variable_being_redeclared()
static ir_variable* get_variable_being_redeclared (ir_variable * var, YYLTYPE loc, struct _mesa_glsl_parse_state * state, bool allow_all_redeclarations, bool * is_redeclaration) static
Get the variable that is being redeclared by this declaration or if it does not exist, the current declared variable.
Semantic checks to verify the validity of the redeclaration are also performed. If semantic checks fail, compilation error will be emitted via _mesa_glsl_error, but a non-NULL pointer will still be returned.
Returns
A pointer to an existing variable in the current scope if the declaration is a redeclaration, current variable otherwise. is_declared boolean will return true if the declaration is a redeclaration, false otherwise.
From the AMD_conservative_depth spec: Within any shader, the first redeclarations of gl_FragDepth must appear before any use of gl_FragDepth.
References _mesa_glsl_error(), check_builtin_array_max_size(), and depth_layout_string().
Referenced by ast_declarator_list::hir(), and ast_interface_block::hir().
handle_geometry_shader_input_decl()
static void handle_geometry_shader_input_decl (struct _mesa_glsl_parse_state * state, YYLTYPE loc, ir_variable * var) static
Do additional processing necessary for geometry shader input declarations (this covers both interface blocks arrays and bare input variables).
References validate_layout_qualifier_vertex_count(), and vertices_per_prim().
Referenced by ast_declarator_list::hir(), and ast_interface_block::hir().
handle_tess_ctrl_shader_output_decl()
static void handle_tess_ctrl_shader_output_decl (struct _mesa_glsl_parse_state * state, YYLTYPE loc, ir_variable * var) static
References _mesa_glsl_error(), process_qualifier_constant(), and validate_layout_qualifier_vertex_count().
Referenced by ast_declarator_list::hir(), and ast_interface_block::hir().
handle_tess_shader_input_decl()
static void handle_tess_shader_input_decl (struct _mesa_glsl_parse_state * state, YYLTYPE loc, ir_variable * var) static
Do additional processing necessary for tessellation control/evaluation shader input declarations.
This covers both interface block arrays and bare input variables.
References _mesa_glsl_error().
Referenced by ast_declarator_list::hir(), and ast_interface_block::hir().
interpret_interpolation_qualifier()
static glsl_interp_mode interpret_interpolation_qualifier (const struct ast_type_qualifier * qual, const struct glsl_type * var_type, ir_variable_mode mode, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References ast_type_qualifier::flags, ast_type_qualifier::q, and validate_interpolation_qualifier().
Referenced by apply_type_qualifier_to_variable(), and ast_process_struct_or_iface_block_members().
is_allowed_invariant()
static bool is_allowed_invariant (ir_variable * var, struct _mesa_glsl_parse_state * state) static
References is_varying_var().
Referenced by ast_declarator_list::hir().
is_conflicting_fragcoord_redeclaration()
static bool is_conflicting_fragcoord_redeclaration (struct _mesa_glsl_parse_state * state, const struct ast_type_qualifier * qual) inline static
References ast_type_qualifier::flags, and ast_type_qualifier::q.
Referenced by apply_layout_qualifier_to_variable().
is_unsized_array_last_element()
static bool is_unsized_array_last_element (ir_variable * v) static
Referenced by ast_interface_block::hir().
is_valid_default_precision_type()
static bool is_valid_default_precision_type (const struct glsl_type *const type) static
Determine if the given type is valid for establishing a default precision qualifier.
From GLSL ES 3.00 section 4.5.4 ("Default Precision Qualifiers"):
"The precision statement
    precision precision-qualifier type;
can be used to establish a default precision qualifier. The type field
can be either int or float or any of the sampler types, and the
precision-qualifier can be lowp, mediump, or highp."
GLSL ES 1.00 has similar language. GLSL 1.30 doesn't allow precision qualifiers on sampler types, but this seems like an oversight (since the intention of including these in GLSL 1.30 is to allow compatibility with ES shaders). So we allow int, float, and all sampler types regardless of GLSL version.
Referenced by ast_type_specifier::hir().
is_varying_var()
static bool is_varying_var (ir_variable * var, gl_shader_stage target) static
Determine whether a toplevel variable declaration declares a varying.
This function operates by examining the variable's mode and the shader target, so it correctly identifies linkage variables regardless of whether they are declared using the deprecated "varying" syntax or the new "in/out" syntax.
Passing a non-toplevel variable declaration (e.g. a function parameter) to this function will produce undefined results.
Referenced by apply_type_qualifier_to_variable(), and is_allowed_invariant().
key_contents()
static unsigned key_contents (const void * key) static
Referenced by ast_switch_statement::hir().
mark_whole_array_access()
static void mark_whole_array_access (ir_rvalue * access) static
Referenced by do_assignment(), do_comparison(), and ast_expression::do_hir().
modulus_result_type()
static const struct glsl_type* modulus_result_type (ir_rvalue *& value_a, ir_rvalue *& value_b, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), and apply_implicit_conversion().
Referenced by ast_expression::do_hir().
precision_qualifier_allowed()
static bool precision_qualifier_allowed (const glsl_type * type) static
Referenced by ast_declarator_list::hir(), and select_gles_precision().
process_array_size()
static unsigned process_array_size (exec_node * node, struct _mesa_glsl_parse_state * state) static
Evaluate the given exec_node (which should be an ast_node representing a single array dimension) and return its integer value.
Dimensions other than the outermost dimension can by unsized if they are immediately sized by a constructor or initializer.
References _mesa_glsl_error(), ast_unsized_array_dim, exec_node_data, ast_node::get_location(), ast_node::has_sequence_subexpression(), and ast_node::hir().
Referenced by process_array_type().
process_array_type()
static const glsl_type* process_array_type (YYLTYPE * loc, const glsl_type * base, ast_array_specifier * array_specifier, struct _mesa_glsl_parse_state * state) static
References ast_array_specifier::array_dimensions, and process_array_size().
Referenced by ast_process_struct_or_iface_block_members(), ast_type_specifier::glsl_type(), ast_declarator_list::hir(), ast_parameter_declarator::hir(), and ast_interface_block::hir().
process_initializer()
ir_rvalue* process_initializer (ir_variable * var, ast_declaration * decl, ast_fully_specified_type * type, exec_list * initializer_instructions, struct _mesa_glsl_parse_state * state)
Generate the IR for an initializer in a variable declaration.
References _mesa_ast_set_aggregate_type(), _mesa_glsl_error(), do_assignment(), ast_type_qualifier::flags, ast_node::get_location(), ast_expression::has_sequence_subexpression(), ast_expression::hir(), ast_declaration::identifier, ast_declaration::initializer, ast_expression::oper, ast_type_qualifier::q, ast_fully_specified_type::qualifier, and validate_assignment().
Referenced by ast_declarator_list::hir().
relational_result_type()
static const struct glsl_type* relational_result_type (ir_rvalue *& value_a, ir_rvalue *& value_b, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), and apply_implicit_conversion().
Referenced by ast_expression::do_hir().
remove_per_vertex_blocks()
static void remove_per_vertex_blocks (exec_list * instructions, _mesa_glsl_parse_state * state, ir_variable_mode mode) static
References foreach_in_list_safe, and interface_block_usage_visitor::usage_found().
Referenced by _mesa_ast_to_hir().
select_gles_precision()
static unsigned select_gles_precision (unsigned qual_precision, const glsl_type * type, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error(), ast_precision_high, ast_precision_none, get_type_name_for_precision_qualifier(), and precision_qualifier_allowed().
Referenced by apply_type_qualifier_to_variable(), and ast_interface_block::hir().
shift_result_type()
static const struct glsl_type* shift_result_type (const struct glsl_type * type_a, const struct glsl_type * type_b, ast_operators op, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
Return the result type of a bit-shift operation.
If the given types to the bit-shift operator are invalid, return glsl_type::error_type.
Parameters
type_a Type of LHS of bit-shift op
type_b Type of RHS of bit-shift op
References _mesa_glsl_error(), and ast_expression::operator_string().
Referenced by ast_expression::do_hir().
unary_arithmetic_result_type()
static const struct glsl_type* unary_arithmetic_result_type (const struct glsl_type * type, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static
References _mesa_glsl_error().
Referenced by ast_expression::do_hir().
validate_array_dimensions()
static void validate_array_dimensions (const glsl_type * t, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) inline static
References _mesa_glsl_error().
Referenced by ast_process_struct_or_iface_block_members(), and ast_declarator_list::hir().
validate_assignment()
static ir_rvalue* validate_assignment (struct _mesa_glsl_parse_state * state, YYLTYPE loc, ir_rvalue * lhs, ir_rvalue * rhs, bool is_initializer) static
Validates that a value can be assigned to a location with a specified type.
Validates that rhs can be assigned to some location. If the types are not an exact match but an automatic conversion is possible, rhs will be converted.
Returns
NULL if rhs cannot be assigned to a location with type lhs_type. Otherwise the actual RHS to be assigned will be returned. This may be rhs, or it may be rhs after some type conversion.
Note
In addition to being used for assignments, this function is used to type-check return values.
References _mesa_glsl_error(), apply_implicit_conversion(), and find_innermost_array_index().
Referenced by do_assignment(), and process_initializer().
validate_identifier()
void validate_identifier (const char * identifier, YYLTYPE loc, struct _mesa_glsl_parse_state * state)
References _mesa_glsl_error(), and _mesa_glsl_warning().
Referenced by ast_process_struct_or_iface_block_members(), ast_struct_specifier::hir(), ast_declarator_list::hir(), ast_function::hir(), and ast_interface_block::hir().
validate_interpolation_qualifier()
static void validate_interpolation_qualifier (struct _mesa_glsl_parse_state * state, YYLTYPE * loc, const glsl_interp_mode interpolation, const struct ast_type_qualifier * qual, const struct glsl_type * var_type, ir_variable_mode mode) static
References _mesa_glsl_error(), ast_type_qualifier::flags, interpolation_string(), and ast_type_qualifier::q.
Referenced by interpret_interpolation_qualifier().
validate_layout_qualifier_vertex_count()
static void validate_layout_qualifier_vertex_count (struct _mesa_glsl_parse_state * state, YYLTYPE loc, ir_variable * var, unsigned num_vertices, unsigned * size, const char * var_category) static
References _mesa_glsl_error().
Referenced by handle_geometry_shader_input_decl(), and handle_tess_ctrl_shader_output_decl().
validate_matrix_layout_for_type()
static void validate_matrix_layout_for_type (struct _mesa_glsl_parse_state * state, YYLTYPE * loc, const glsl_type * type, ir_variable * var) static
Matrix layout qualifiers are only allowed on certain types.
References _mesa_glsl_error(), and _mesa_glsl_warning().
Referenced by apply_layout_qualifier_to_variable(), and ast_process_struct_or_iface_block_members().
validate_stream_qualifier()
static bool validate_stream_qualifier (YYLTYPE * loc, struct _mesa_glsl_parse_state * state, unsigned stream) static
References _mesa_glsl_error().
Referenced by apply_layout_qualifier_to_variable(), and ast_interface_block::hir().
validate_xfb_buffer_qualifier()
static bool validate_xfb_buffer_qualifier (YYLTYPE * loc, struct _mesa_glsl_parse_state * state, unsigned xfb_buffer) static
References _mesa_glsl_error().
Referenced by apply_layout_qualifier_to_variable(), and ast_interface_block::hir().
validate_xfb_offset_qualifier()
static bool validate_xfb_offset_qualifier (YYLTYPE * loc, struct _mesa_glsl_parse_state * state, int xfb_offset, const glsl_type * type, unsigned component_size) static
References _mesa_glsl_error().
Referenced by apply_layout_qualifier_to_variable(), and ast_interface_block::hir().