Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_type.cpp File Reference
#include "ast.h"
Functions
static bool validate_prim_type (YYLTYPE *loc, _mesa_glsl_parse_state *state, const ast_type_qualifier &qualifier, const ast_type_qualifier &new_qualifier)
static bool validate_vertex_spacing (YYLTYPE *loc, _mesa_glsl_parse_state *state, const ast_type_qualifier &qualifier, const ast_type_qualifier &new_qualifier)
static bool validate_ordering (YYLTYPE *loc, _mesa_glsl_parse_state *state, const ast_type_qualifier &qualifier, const ast_type_qualifier &new_qualifier)
static bool validate_point_mode (MAYBE_UNUSED const ast_type_qualifier &qualifier, MAYBE_UNUSED const ast_type_qualifier &new_qualifier)
bool process_qualifier_constant (struct _mesa_glsl_parse_state *state, YYLTYPE *loc, const char *qual_indentifier, ast_expression *const_expression, unsigned *value)
Function Documentation
process_qualifier_constant()
bool process_qualifier_constant (struct _mesa_glsl_parse_state * state, YYLTYPE * loc, const char * qual_indentifier, ast_expression * const_expression, unsigned * value)
References _mesa_glsl_error(), and ast_expression::hir().
Referenced by apply_explicit_binding(), apply_explicit_location(), apply_layout_qualifier_to_variable(), ast_cs_input_layout::ast_cs_input_layout(), ast_layout_expression::ast_layout_expression(), ast_process_struct_or_iface_block_members(), handle_tess_ctrl_shader_output_decl(), ast_struct_specifier::hir(), ast_declarator_list::hir(), ast_function::hir(), ast_interface_block::hir(), ast_tcs_output_layout::hir(), ast_cs_input_layout::hir(), ast_type_qualifier::push_to_global(), and set_shader_inout_layout().
validate_ordering()
static bool validate_ordering (YYLTYPE * loc, _mesa_glsl_parse_state * state, const ast_type_qualifier & qualifier, const ast_type_qualifier & new_qualifier) static
References _mesa_glsl_error(), ast_type_qualifier::flags, ast_type_qualifier::ordering, and ast_type_qualifier::q.
Referenced by ast_type_qualifier::merge_qualifier(), and ast_type_qualifier::validate_in_qualifier().
validate_point_mode()
static bool validate_point_mode (MAYBE_UNUSED const ast_type_qualifier & qualifier, MAYBE_UNUSED const ast_type_qualifier & new_qualifier) static
Referenced by ast_type_qualifier::merge_qualifier(), and ast_type_qualifier::validate_in_qualifier().
validate_prim_type()
static bool validate_prim_type (YYLTYPE * loc, _mesa_glsl_parse_state * state, const ast_type_qualifier & qualifier, const ast_type_qualifier & new_qualifier) static
References _mesa_glsl_error(), ast_type_qualifier::flags, ast_type_qualifier::prim_type, and ast_type_qualifier::q.
Referenced by ast_type_qualifier::merge_qualifier(), and ast_type_qualifier::validate_in_qualifier().
validate_vertex_spacing()
static bool validate_vertex_spacing (YYLTYPE * loc, _mesa_glsl_parse_state * state, const ast_type_qualifier & qualifier, const ast_type_qualifier & new_qualifier) static
References _mesa_glsl_error(), ast_type_qualifier::flags, ast_type_qualifier::q, and ast_type_qualifier::vertex_spacing.
Referenced by ast_type_qualifier::merge_qualifier(), and ast_type_qualifier::validate_in_qualifier().