Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_array_index.cpp File Reference
#include "ast.h"
#include "compiler/glsl_types.h"
#include "ir.h"
Functions
static void update_max_array_access (ir_rvalue *ir, int idx, YYLTYPE *loc, struct _mesa_glsl_parse_state *state)
If ir is a reference to an array for which we are tracking the max array element accessed, track that the given element has been accessed.
static int get_implicit_array_size (struct _mesa_glsl_parse_state *state, ir_rvalue *array)
ir_rvalue * _mesa_ast_array_index_to_hir (void *mem_ctx, struct _mesa_glsl_parse_state *state, ir_rvalue *array, ir_rvalue *idx, YYLTYPE &loc, YYLTYPE &idx_loc)
Function Documentation
_mesa_ast_array_index_to_hir()
ir_rvalue* _mesa_ast_array_index_to_hir (void * mem_ctx, struct _mesa_glsl_parse_state * state, ir_rvalue * array, ir_rvalue * idx, YYLTYPE & loc, YYLTYPE & idx_loc)
References _mesa_glsl_error(), _mesa_glsl_warning(), get_implicit_array_size(), and update_max_array_access().
Referenced by ast_cs_input_layout::ast_cs_input_layout(), ast_expression::do_hir(), and generate_array_index().
get_implicit_array_size()
static int get_implicit_array_size (struct _mesa_glsl_parse_state * state, ir_rvalue * array) static
Referenced by _mesa_ast_array_index_to_hir().
update_max_array_access()
static void update_max_array_access (ir_rvalue * ir, int idx, YYLTYPE * loc, struct _mesa_glsl_parse_state * state) static
If ir is a reference to an array for which we are tracking the max array element accessed, track that the given element has been accessed.
Otherwise do nothing.
This function also checks whether the array is a built-in array whose maximum size is too small to accommodate the given index, and if so uses loc and state to report the error.
References check_builtin_array_max_size().
Referenced by _mesa_ast_array_index_to_hir().