Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_function.cpp File Reference
#include "glsl_symbol_table.h"
#include "ast.h"
#include "compiler/glsl_types.h"
#include "ir.h"
#include "main/core.h"
#include "main/shaderobj.h"
#include "builtin_functions.h"
Functions
static ir_rvalue * convert_component (ir_rvalue *src, const glsl_type *desired_type)
Perform automatic type conversion of constructor parameters.
static unsigned process_parameters (exec_list *instructions, exec_list *actual_parameters, exec_list *parameters, struct _mesa_glsl_parse_state *state)
char * prototype_string (const glsl_type *return_type, const char *name, exec_list *parameters)
Generate a source prototype for a function signature.
static bool verify_image_parameter (YYLTYPE *loc, _mesa_glsl_parse_state *state, const ir_variable *formal, const ir_variable *actual)
static bool verify_first_atomic_parameter (YYLTYPE *loc, _mesa_glsl_parse_state *state, ir_variable *var)
static bool is_atomic_function (const char *func_name)
static bool verify_parameter_modes (_mesa_glsl_parse_state *state, ir_function_signature *sig, exec_list &actual_ir_parameters, exec_list &actual_ast_parameters)
Verify that 'out' and 'inout' actual parameters are lvalues.
static void fix_parameter (void *mem_ctx, ir_rvalue *actual, const glsl_type *formal_type, exec_list *before_instructions, exec_list *after_instructions, bool parameter_is_inout)
static ir_rvalue * generate_call (exec_list *instructions, ir_function_signature *sig, exec_list *actual_parameters, ir_variable *sub_var, ir_rvalue *array_idx, struct _mesa_glsl_parse_state *state, bool inline_immediately)
Generate a function call.
static ir_function_signature * match_function_by_name (const char *name, exec_list *actual_parameters, struct _mesa_glsl_parse_state *state)
Given a function name and parameter list, find the matching signature.
static ir_function_signature * match_subroutine_by_name (const char *name, exec_list *actual_parameters, struct _mesa_glsl_parse_state *state, ir_variable **var_r)
static ir_rvalue * generate_array_index (void *mem_ctx, exec_list *instructions, struct _mesa_glsl_parse_state *state, YYLTYPE loc, const ast_expression *array, ast_expression *idx, const char **function_name, exec_list *actual_parameters)
static void print_function_prototypes (_mesa_glsl_parse_state *state, YYLTYPE *loc, ir_function *f)
static void no_matching_function_error (const char *name, YYLTYPE *loc, exec_list *actual_parameters, _mesa_glsl_parse_state *state)
Raise a "no matching function" error, listing all possible overloads the compiler considered so developers can figure out what went wrong.
static bool implicitly_convert_component (ir_rvalue *&from, const glsl_base_type to, struct _mesa_glsl_parse_state *state)
Perform automatic type and constant conversion of constructor parameters.
static ir_rvalue * dereference_component (ir_rvalue *src, unsigned component)
Dereference a specific component from a scalar, vector, or matrix.
static ir_rvalue * process_vec_mat_constructor (exec_list *instructions, const glsl_type *constructor_type, YYLTYPE *loc, exec_list *parameters, struct _mesa_glsl_parse_state *state)
static ir_rvalue * process_array_constructor (exec_list *instructions, const glsl_type *constructor_type, YYLTYPE *loc, exec_list *parameters, struct _mesa_glsl_parse_state *state)
bool single_scalar_parameter (exec_list *parameters)
Determine if a list consists of a single scalar r-value.
ir_rvalue * emit_inline_vector_constructor (const glsl_type *type, exec_list *instructions, exec_list *parameters, void *ctx)
Generate inline code for a vector constructor.
ir_instruction * assign_to_matrix_column (ir_variable *var, unsigned column, unsigned row_base, ir_rvalue *src, unsigned src_base, unsigned count, void *mem_ctx)
Generate assignment of a portion of a vector to a portion of a matrix column.
ir_rvalue * emit_inline_matrix_constructor (const glsl_type *type, exec_list *instructions, exec_list *parameters, void *ctx)
Generate inline code for a matrix constructor.
ir_rvalue * emit_inline_record_constructor (const glsl_type *type, exec_list *instructions, exec_list *parameters, void *mem_ctx)
static ir_rvalue * process_record_constructor (exec_list *instructions, const glsl_type *constructor_type, YYLTYPE *loc, exec_list *parameters, struct _mesa_glsl_parse_state *state)
Function Documentation
assign_to_matrix_column()
ir_instruction* assign_to_matrix_column (ir_variable * var, unsigned column, unsigned row_base, ir_rvalue * src, unsigned src_base, unsigned count, void * mem_ctx)
Generate assignment of a portion of a vector to a portion of a matrix column.
Parameters
src_base First component of the source to be used in assignment
column Column of destination to be assiged
row_base First component of the destination column to be assigned
count Number of components to be assigned
Note
src_base + count must be less than or equal to the number of components in the source vector.
Referenced by emit_inline_matrix_constructor().
convert_component()
static ir_rvalue * convert_component (ir_rvalue * src, const glsl_type * desired_type) static
Perform automatic type conversion of constructor parameters.
This implements the rules in the "Conversion and Scalar Constructors" section (GLSL 1.10 section 5.4.1), not the "Implicit Conversions" rules.
Referenced by fix_parameter(), generate_call(), ast_function_expression::hir(), and implicitly_convert_component().
dereference_component()
static ir_rvalue* dereference_component (ir_rvalue * src, unsigned component) static
Dereference a specific component from a scalar, vector, or matrix.
Referenced by ast_function_expression::hir().
emit_inline_matrix_constructor()
ir_rvalue* emit_inline_matrix_constructor (const glsl_type * type, exec_list * instructions, exec_list * parameters, void * ctx)
Generate inline code for a matrix constructor.
The generated constructor code will consist of a temporary variable declaration of the same type as the constructor. A sequence of assignments from constructor parameters to the temporary will follow.
Returns
An ir_dereference_variable of the temprorary generated in the constructor body.
References assign_to_matrix_column(), foreach_in_list, and single_scalar_parameter().
Referenced by ast_function_expression::hir().
emit_inline_record_constructor()
ir_rvalue* emit_inline_record_constructor (const glsl_type * type, exec_list * instructions, exec_list * parameters, void * mem_ctx)
References ir_builder::assign(), and exec_node::next.
Referenced by process_record_constructor().
emit_inline_vector_constructor()
ir_rvalue* emit_inline_vector_constructor (const glsl_type * type, exec_list * instructions, exec_list * parameters, void * ctx)
Generate inline code for a vector constructor.
The generated constructor code will consist of a temporary variable declaration of the same type as the constructor. A sequence of assignments from constructor parameters to the temporary will follow.
Returns
An ir_dereference_variable of the temprorary generated in the constructor body.
References foreach_in_list, and single_scalar_parameter().
Referenced by ast_function_expression::hir().
fix_parameter()
static void fix_parameter (void * mem_ctx, ir_rvalue * actual, const glsl_type * formal_type, exec_list * before_instructions, exec_list * after_instructions, bool parameter_is_inout) static
References convert_component(), and ir_builder::expr().
Referenced by generate_call().
generate_array_index()
static ir_rvalue* generate_array_index (void * mem_ctx, exec_list * instructions, struct _mesa_glsl_parse_state * state, YYLTYPE loc, const ast_expression * array, ast_expression * idx, const char ** function_name, exec_list * actual_parameters) static
References _mesa_ast_array_index_to_hir(), ast_array_index, ast_node::get_location(), ast_expression::hir(), ast_expression::identifier, match_subroutine_by_name(), ast_expression::oper, ast_expression::primary_expression, and ast_expression::subexpressions.
Referenced by ast_function_expression::hir().
generate_call()
static ir_rvalue* generate_call (exec_list * instructions, ir_function_signature * sig, exec_list * actual_parameters, ir_variable * sub_var, ir_rvalue * array_idx, struct _mesa_glsl_parse_state * state, bool inline_immediately) static
Generate a function call.
For non-void functions, this returns a dereference of the temporary variable which stores the return value for the call. For void functions, this returns NULL.
References convert_component(), fix_parameter(), and foreach_two_lists.
Referenced by ast_function_expression::hir().
implicitly_convert_component()
static bool implicitly_convert_component (ir_rvalue *& from, const glsl_base_type to, struct _mesa_glsl_parse_state * state) static
Perform automatic type and constant conversion of constructor parameters.
This implements the rules in the "Implicit Conversions" rules, not the "Conversion and Scalar Constructors".
After attempting the implicit conversion, an attempt to convert into a constant valued expression is also done.
The from ir_rvalue is converted "in place".
Parameters
from Operand that is being converted
to Base type the operand will be converted to
state GLSL compiler state
Returns
If the attempt to convert into a constant expression succeeds, true is returned. Otherwise false is returned.
References convert_component().
Referenced by process_array_constructor(), process_record_constructor(), and process_vec_mat_constructor().
is_atomic_function()
static bool is_atomic_function (const char * func_name) static
Referenced by verify_parameter_modes().
match_function_by_name()
static ir_function_signature* match_function_by_name (const char * name, exec_list * actual_parameters, struct _mesa_glsl_parse_state * state) static
Given a function name and parameter list, find the matching signature.
References _mesa_glsl_find_builtin_function(), and _mesa_glsl_initialize_builtin_functions().
Referenced by ast_function_expression::hir().
match_subroutine_by_name()
static ir_function_signature* match_subroutine_by_name (const char * name, exec_list * actual_parameters, struct _mesa_glsl_parse_state * state, ir_variable ** var_r) static
Referenced by generate_array_index(), and ast_function_expression::hir().
no_matching_function_error()
static void no_matching_function_error (const char * name, YYLTYPE * loc, exec_list * actual_parameters, _mesa_glsl_parse_state * state) static
Raise a "no matching function" error, listing all possible overloads the compiler considered so developers can figure out what went wrong.
References _mesa_glsl_error(), _mesa_glsl_get_builtin_function_shader(), print_function_prototypes(), and prototype_string().
Referenced by ast_function_expression::hir().
print_function_prototypes()
static void print_function_prototypes (_mesa_glsl_parse_state * state, YYLTYPE * loc, ir_function * f) static
References _mesa_glsl_error(), foreach_in_list, and prototype_string().
Referenced by no_matching_function_error().
process_array_constructor()
static ir_rvalue* process_array_constructor (exec_list * instructions, const glsl_type * constructor_type, YYLTYPE * loc, exec_list * parameters, struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error(), foreach_in_list, foreach_in_list_safe, implicitly_convert_component(), and process_parameters().
Referenced by ast_function_expression::hir(), and ast_aggregate_initializer::hir().
process_parameters()
static unsigned process_parameters (exec_list * instructions, exec_list * actual_parameters, exec_list * parameters, struct _mesa_glsl_parse_state * state) static
References foreach_list_typed.
Referenced by ast_function_expression::hir(), process_array_constructor(), process_record_constructor(), and process_vec_mat_constructor().
process_record_constructor()
static ir_rvalue* process_record_constructor (exec_list * instructions, const glsl_type * constructor_type, YYLTYPE * loc, exec_list * parameters, struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error(), emit_inline_record_constructor(), ast_expression::expressions, foreach_in_list_safe, ast_node::get_location(), ast_expression::hir(), ast_expression::identifier, implicitly_convert_component(), ast_expression::primary_expression, process_parameters(), ast_expression::set_is_lhs(), and ast_expression::subexpressions.
Referenced by ast_function_expression::hir(), and ast_aggregate_initializer::hir().
process_vec_mat_constructor()
static ir_rvalue* process_vec_mat_constructor (exec_list * instructions, const glsl_type * constructor_type, YYLTYPE * loc, exec_list * parameters, struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error(), foreach_in_list, foreach_in_list_safe, implicitly_convert_component(), and process_parameters().
Referenced by ast_aggregate_initializer::hir().
prototype_string()
char* prototype_string (const glsl_type * return_type, const char * name, exec_list * parameters)
Generate a source prototype for a function signature.
Parameters
return_type Return type of the function. May be NULL.
name Name of the function.
parameters List of ir_instruction nodes representing the parameter list for the function. This may be either a formal (ir_variable) or actual (ir_rvalue) parameter list. Only the type is used.
Returns
A ralloced string representing the prototype of the function.
References foreach_in_list.
Referenced by emit_errors_linked(), emit_errors_unlinked(), no_matching_function_error(), and print_function_prototypes().
single_scalar_parameter()
bool single_scalar_parameter (exec_list * parameters)
Determine if a list consists of a single scalar r-value.
Referenced by emit_inline_matrix_constructor(), and emit_inline_vector_constructor().
verify_first_atomic_parameter()
static bool verify_first_atomic_parameter (YYLTYPE * loc, _mesa_glsl_parse_state * state, ir_variable * var) static
References _mesa_glsl_error().
Referenced by verify_parameter_modes().
verify_image_parameter()
static bool verify_image_parameter (YYLTYPE * loc, _mesa_glsl_parse_state * state, const ir_variable * formal, const ir_variable * actual) static
From the ARB_shader_image_load_store specification:
"The values of image variables qualified with coherent, volatile, restrict, readonly, or writeonly may not be passed to functions whose formal parameters lack such qualifiers. [...] It is legal to have additional qualifiers on a formal parameter, but not to have fewer."
References _mesa_glsl_error().
Referenced by verify_parameter_modes().
verify_parameter_modes()
static bool verify_parameter_modes (_mesa_glsl_parse_state * state, ir_function_signature * sig, exec_list & actual_ir_parameters, exec_list & actual_ast_parameters) static
Verify that 'out' and 'inout' actual parameters are lvalues.
Also, verify that 'const_in' formal parameters (an extension in our IR) correspond to ir_constant actual parameters.
References _mesa_glsl_error(), _mesa_glsl_warning(), exec_node_data, foreach_in_list, ast_node::get_location(), is_atomic_function(), exec_node::next, ast_expression::non_lvalue_description, verify_first_atomic_parameter(), and verify_image_parameter().
Referenced by ast_function_expression::hir().