Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
blob.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
Data Structures
struct blob
struct blob_reader
Functions
struct blob * blob_create (void)
Create a new, empty blob.
static void blob_destroy (struct blob *blob)
Destroy a blob and free its memory.
bool blob_write_bytes (struct blob *blob, const void *bytes, size_t to_write)
Add some unstructured, fixed-size data to a blob.
uint8_t * blob_reserve_bytes (struct blob *blob, size_t to_write)
Reserve space in for a number of bytes.
bool blob_overwrite_bytes (struct blob *blob, size_t offset, const void *bytes, size_t to_write)
Overwrite some data previously written to the blob.
bool blob_write_uint32 (struct blob *blob, uint32_t value)
Add a uint32_t to a blob.
bool blob_overwrite_uint32 (struct blob *blob, size_t offset, uint32_t value)
Overwrite a uint32_t previously written to the blob.
bool blob_write_uint64 (struct blob *blob, uint64_t value)
Add a uint64_t to a blob.
bool blob_write_intptr (struct blob *blob, intptr_t value)
Add an intptr_t to a blob.
bool blob_write_string (struct blob *blob, const char *str)
Add a NULL-terminated string to a blob, (including the NULL terminator).
void blob_reader_init (struct blob_reader *blob, uint8_t *data, size_t size)
Start reading a blob, (initializing the contents of for reading).
void * blob_read_bytes (struct blob_reader *blob, size_t size)
Read some unstructured, fixed-size data from the current location, (and update the current location to just past this data).
void blob_copy_bytes (struct blob_reader *blob, uint8_t *dest, size_t size)
Read some unstructured, fixed-size data from the current location, copying it to (and update the current location to just past this data)
uint32_t blob_read_uint32 (struct blob_reader *blob)
Read a uint32_t from the current location, (and update the current location to just past this uint32_t).
uint64_t blob_read_uint64 (struct blob_reader *blob)
Read a uint64_t from the current location, (and update the current location to just past this uint64_t).
intptr_t blob_read_intptr (struct blob_reader *blob)
Read an intptr_t value from the current location, (and update the current location to just past this intptr_t).
char * blob_read_string (struct blob_reader *blob)
Read a NULL-terminated string from the current location, (and update the current location to just past this string).
Function Documentation
blob_copy_bytes()
void blob_copy_bytes (struct blob_reader * blob, uint8_t * dest, size_t size)
Read some unstructured, fixed-size data from the current location, copying it to (and update the current location to just past this data)
References blob_read_bytes().
Referenced by blob_destroy(), create_linked_shader_and_program(), read_atomic_buffers(), read_program_resource_data(), read_program_resource_list(), read_shader_metadata(), read_shader_parameters(), read_uniforms(), and read_xfb().
blob_create()
struct blob* blob_create (void)
Create a new, empty blob.
Returns
The new blob, (or NULL in case of allocation failure).
References blob::allocated, blob::data, and blob::size.
Referenced by shader_cache_write_program_metadata().
blob_destroy()
static void blob_destroy (struct blob * blob) inline static
Destroy a blob and free its memory.
References blob_copy_bytes(), blob_overwrite_bytes(), blob_overwrite_uint32(), blob_read_bytes(), blob_read_intptr(), blob_read_string(), blob_read_uint32(), blob_read_uint64(), blob_reader_init(), blob_reserve_bytes(), blob_write_bytes(), blob_write_intptr(), blob_write_string(), blob_write_uint32(), blob_write_uint64(), blob::data, and blob::size.
Referenced by shader_cache_write_program_metadata().
blob_overwrite_bytes()
bool blob_overwrite_bytes (struct blob * blob, size_t offset, const void * bytes, size_t to_write)
Overwrite some data previously written to the blob.
Writes data to an existing portion of the blob at an offset of . This data range must have previously been written to the blob by one of the blob_write_* calls.
For example usage, see blob_overwrite_uint32
Returns
True unless the requested offset or offset+to_write lie outside the current blob's size.
References blob::data, and blob::size.
Referenced by blob_destroy(), and blob_overwrite_uint32().
blob_overwrite_uint32()
bool blob_overwrite_uint32 (struct blob * blob, size_t offset, uint32_t value)
Overwrite a uint32_t previously written to the blob.
Writes a uint32_t value to an existing portion of the blob at an offset of . This data range must have previously been written to the blob by one of the blob_write_* calls.
The expected usage is something like the following pattern:
 size_t offset;
 offset = blob->size;
 blob_write_uint32 (blob, 0); // placeholder
 ... various blob write calls, writing N items ...
 blob_overwrite_uint32 (blob, offset, N);
Returns
True unless the requested position or position+to_write lie outside the current blob's size.
References blob_overwrite_bytes().
Referenced by blob_destroy(), and write_hash_table().
blob_read_bytes()
void* blob_read_bytes (struct blob_reader * blob, size_t size)
Read some unstructured, fixed-size data from the current location, (and update the current location to just past this data).
Note
The memory returned belongs to the data underlying the blob reader. The caller must copy the data in order to use it after the lifetime of the data underlying the blob reader.
Returns
The bytes read (see note above about memory lifetime).
References blob_reader::current, ensure_can_read(), ir_builder::ret(), and blob::size.
Referenced by blob_copy_bytes(), blob_destroy(), decode_type_from_blob(), and read_uniforms().
blob_read_intptr()
intptr_t blob_read_intptr (struct blob_reader * blob)
Read an intptr_t value from the current location, (and update the current location to just past this intptr_t).
Note
This function will only read from an intptr_t-aligned offset from the beginning of the blob's data, so some padding bytes may be skipped.
Returns
The intptr_t read
References align_blob_reader(), blob_reader::current, ensure_can_read(), ir_builder::ret(), and blob::size.
Referenced by blob_destroy().
blob_read_string()
char* blob_read_string (struct blob_reader * blob)
Read a NULL-terminated string from the current location, (and update the current location to just past this string).
Note
The memory returned belongs to the data underlying the blob reader. The caller must copy the string in order to use the string after the lifetime of the data underlying the blob reader.
Returns
The string read (see note above about memory lifetime). However, if there is no NULL byte remaining within the blob, this function returns NULL.
References blob_reader::current, blob_reader::end, ensure_can_read(), blob_reader::overrun, ir_builder::ret(), and blob::size.
Referenced by blob_destroy(), create_linked_shader_and_program(), decode_type_from_blob(), read_buffer_block(), read_hash_table(), read_program_resource_data(), read_shader_parameters(), read_subroutines(), read_uniforms(), and read_xfb().
blob_read_uint32()
uint32_t blob_read_uint32 (struct blob_reader * blob)
Read a uint32_t from the current location, (and update the current location to just past this uint32_t).
Note
This function will only read from a uint32_t-aligned offset from the beginning of the blob's data, so some padding bytes may be skipped.
Returns
The uint32_t read
References align_blob_reader(), blob_reader::current, ensure_can_read(), ir_builder::ret(), and blob::size.
Referenced by blob_destroy(), decode_type_from_blob(), read_atomic_buffers(), read_buffer_block(), read_buffer_blocks(), read_hash_table(), read_program_resource_data(), read_program_resource_list(), read_shader_metadata(), read_shader_parameters(), read_subroutines(), read_uniform_remap_table_entry(), read_uniform_remap_tables(), read_uniforms(), read_xfb(), and shader_cache_read_program_metadata().
blob_read_uint64()
uint64_t blob_read_uint64 (struct blob_reader * blob)
Read a uint64_t from the current location, (and update the current location to just past this uint64_t).
Note
This function will only read from a uint64_t-aligned offset from the beginning of the blob's data, so some padding bytes may be skipped.
Returns
The uint64_t read
References align_blob_reader(), blob_reader::current, ensure_can_read(), ir_builder::ret(), and blob::size.
Referenced by blob_destroy(), and read_shader_metadata().
blob_reader_init()
void blob_reader_init (struct blob_reader * blob, uint8_t * data, size_t size)
Start reading a blob, (initializing the contents of for reading).
After this call, the caller can use the various blob_read_* functions to read elements from the data array.
For all of the blob_read_* functions, if there is insufficient data remaining, the functions will do nothing, (perhaps returning default values such as 0). The caller can detect this by noting that the blob_reader's current value is unchanged before and after the call.
References blob_reader::current, blob::data, blob_reader::data, blob_reader::end, blob_reader::overrun, and blob::size.
Referenced by blob_destroy(), and shader_cache_read_program_metadata().
blob_reserve_bytes()
uint8_t* blob_reserve_bytes (struct blob * blob, size_t to_write)
Reserve space in for a number of bytes.
Space will be allocated within the blob for these byes, but the bytes will be left uninitialized. The caller is expected to use the return value to write directly (and immediately) to these bytes.
Note
The return value is valid immediately upon return, but can be invalidated by any other call to a blob function. So the caller should call blob_reserve_byes immediately before writing through the returned pointer.
This function is intended to be used when interfacing with an existing API that is not aware of the blob API, (so that blob_write_bytes cannot be called).
Returns
A pointer to space allocated within to which bytes can be written, (or NULL in case of any allocation error).
References blob::data, grow_to_fit(), ir_builder::ret(), and blob::size.
Referenced by blob_destroy().
blob_write_bytes()
bool blob_write_bytes (struct blob * blob, const void * bytes, size_t to_write)
Add some unstructured, fixed-size data to a blob.
Returns
True unless allocation failed.
References blob::data, grow_to_fit(), and blob::size.
Referenced by blob_destroy(), blob_write_intptr(), blob_write_string(), blob_write_uint32(), blob_write_uint64(), encode_type_to_blob(), shader_cache_write_program_metadata(), write_atomic_buffers(), write_program_resource_data(), write_program_resource_list(), write_shader_metadata(), write_shader_parameters(), write_uniforms(), and write_xfb().
blob_write_intptr()
bool blob_write_intptr (struct blob * blob, intptr_t value)
Add an intptr_t to a blob.
Note
This function will only write to an intptr_t-aligned offset from the beginning of the blob's data, so some padding bytes may be added to the blob if this write follows some unaligned write (such as blob_write_string).
Returns
True unless allocation failed.
References align_blob(), and blob_write_bytes().
Referenced by blob_destroy().
blob_write_string()
bool blob_write_string (struct blob * blob, const char * str)
Add a NULL-terminated string to a blob, (including the NULL terminator).
Returns
True unless allocation failed.
References blob_write_bytes().
Referenced by blob_destroy(), encode_type_to_blob(), shader_cache_write_program_metadata(), write_buffer_block(), write_hash_table_entry(), write_program_resource_data(), write_shader_parameters(), write_subroutines(), write_uniforms(), and write_xfb().
blob_write_uint32()
bool blob_write_uint32 (struct blob * blob, uint32_t value)
Add a uint32_t to a blob.
Note
This function will only write to a uint32_t-aligned offset from the beginning of the blob's data, so some padding bytes may be added to the blob if this write follows some unaligned write (such as blob_write_string).
Returns
True unless allocation failed.
References align_blob(), and blob_write_bytes().
Referenced by blob_destroy(), encode_type_to_blob(), shader_cache_write_program_metadata(), write_atomic_buffers(), write_buffer_block(), write_buffer_blocks(), write_hash_table(), write_hash_table_entry(), write_program_resource_data(), write_program_resource_list(), write_shader_metadata(), write_shader_parameters(), write_shader_subroutine_index(), write_subroutines(), write_uniform_remap_table_entry(), write_uniform_remap_tables(), write_uniforms(), and write_xfb().
blob_write_uint64()
bool blob_write_uint64 (struct blob * blob, uint64_t value)
Add a uint64_t to a blob.
Note
This function will only write to a uint64_t-aligned offset from the beginning of the blob's data, so some padding bytes may be added to the blob if this write follows some unaligned write (such as blob_write_string).
Returns
True unless allocation failed.
References align_blob(), and blob_write_bytes().
Referenced by blob_destroy(), and write_shader_metadata().