Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
builtin_int64.h File Reference
Functions
ir_function_signature * umul64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * sign64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * udivmod64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * udiv64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * idiv64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * umod64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * imod64 (void *mem_ctx, builtin_available_predicate avail)
Function Documentation
idiv64()
ir_function_signature* idiv64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::add(), ir_builder::assign(), ir_builder::bit_or(), ir_builder::equal(), ir_builder::expr(), ir_builder::gequal(), ir_builder::lequal(), ir_builder::less(), ir_builder::logic_and(), ir_builder::lshift(), ir_builder::neg(), ir_builder::nequal(), ir_builder::ret(), ir_builder::sub(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().
imod64()
ir_function_signature* imod64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::add(), ir_builder::assign(), ir_builder::bit_or(), ir_builder::equal(), ir_builder::expr(), ir_builder::gequal(), ir_builder::lequal(), ir_builder::less(), ir_builder::logic_and(), ir_builder::lshift(), ir_builder::neg(), ir_builder::nequal(), ir_builder::ret(), ir_builder::sub(), ir_builder::swizzle(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().
sign64()
ir_function_signature* sign64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::assign(), ir_builder::bit_or(), ir_builder::expr(), ir_builder::nequal(), ir_builder::ret(), ir_builder::rshift(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().
udiv64()
ir_function_signature* udiv64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::add(), ir_builder::assign(), ir_builder::bit_or(), ir_builder::equal(), ir_builder::expr(), ir_builder::gequal(), ir_builder::lequal(), ir_builder::less(), ir_builder::logic_and(), ir_builder::lshift(), ir_builder::ret(), ir_builder::sub(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().
udivmod64()
ir_function_signature* udivmod64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::add(), ir_builder::assign(), ir_builder::bit_or(), ir_builder::equal(), ir_builder::expr(), ir_builder::gequal(), ir_builder::lequal(), ir_builder::less(), ir_builder::logic_and(), ir_builder::lshift(), ir_builder::ret(), ir_builder::sub(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().
umod64()
ir_function_signature* umod64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::add(), ir_builder::assign(), ir_builder::bit_or(), ir_builder::equal(), ir_builder::expr(), ir_builder::gequal(), ir_builder::lequal(), ir_builder::less(), ir_builder::logic_and(), ir_builder::lshift(), ir_builder::ret(), ir_builder::sub(), ir_builder::swizzle(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().
umul64()
ir_function_signature* umul64 (void * mem_ctx, builtin_available_predicate avail)
References ir_builder::add(), ir_builder::assign(), ir_builder::imul_high(), ir_builder::mul(), ir_builder::ret(), ir_builder::swizzle_x(), and ir_builder::swizzle_y().