Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
builtin_functions.cpp File Reference
Support for GLSL built-in functions.
#include <stdarg.h>
#include <stdio.h>
#include "main/core.h"
#include "main/shaderobj.h"
#include "ir_builder.h"
#include "glsl_parser_extras.h"
#include "program/prog_instruction.h"
#include <math.h>
#include "builtin_functions.h"
#include "util/hash_table.h"
Macros
#define M_PIf ((float) M_PI)
Unfortunately, some versions of MinGW produce bad code if this file is compiled with -O2 or -O3.
#define M_PI_2f ((float) M_PI_2)
#define M_PI_4f ((float) M_PI_4)
#define F(NAME)
#define FD(NAME)
#define FD130(NAME)
#define FDGS5(NAME)
#define FI(NAME)
#define FI64(NAME)
#define FIUD_VEC(NAME)
#define IU(NAME)
#define FIUBD_VEC(NAME)
#define FIUD2_MIXED(NAME)
#define IMM_FP(type, val) (type->base_type == GLSL_TYPE_DOUBLE) ? imm(val) : imm((float)val)
#define B0(X) ir_function_signature *_##X();
#define B1(X) ir_function_signature *_##X(const glsl_type *);
#define B2(X) ir_function_signature *_##X(const glsl_type *, const glsl_type *);
#define B3(X) ir_function_signature *_##X(const glsl_type *, const glsl_type *, const glsl_type *);
#define BA1(X) ir_function_signature *_##X(builtin_available_predicate, const glsl_type *);
#define BA2(X) ir_function_signature *_##X(builtin_available_predicate, const glsl_type *, const glsl_type *);
#define TEX_PROJECT 1
Flags to _texture()
#define TEX_OFFSET 2
#define TEX_COMPONENT 4
#define TEX_OFFSET_NONCONST 8
#define TEX_OFFSET_ARRAY 16
Enumerations
enum image_function_flags
Functions
always_available always_available ir_unop_rsq UNOPA (abs, ir_unop_abs) UNOPA(sign
always_available always_available ir_unop_rsq ir_unop_sign UNOPA (floor, ir_unop_floor) UNOPA(trunc
always_available always_available ir_unop_rsq ir_unop_sign ir_unop_trunc UNOPA (round, ir_unop_round_even) UNOPA(roundEven
always_available always_available ir_unop_rsq ir_unop_sign ir_unop_trunc ir_unop_round_even UNOPA (ceil, ir_unop_ceil) UNOPA(fract
UNOP (not, ir_unop_logic_not, always_available) static bool has_lod(const glsl_type *sampler_type)
UNOP (dFdx, ir_unop_dFdx, fs_oes_derivatives) UNOP(dFdxCoarse
fs_derivative_control UNOP (dFdxFine, ir_unop_dFdx_fine, fs_derivative_control) UNOP(dFdy
fs_derivative_control fs_oes_derivatives UNOP (dFdyCoarse, ir_unop_dFdy_coarse, fs_derivative_control) UNOP(dFdyFine
UNOP (bitfieldReverse, ir_unop_bitfield_reverse, gpu_shader5_or_es31_or_integer_functions) ir_function_signature *builtin_builder
static builtin_available_predicate get_image_available_predicate (const glsl_type *type, unsigned flags)
static bool always_available (const _mesa_glsl_parse_state *)
Availability predicates:
static bool compatibility_vs_only (const _mesa_glsl_parse_state *state)
static bool fs_only (const _mesa_glsl_parse_state *state)
static bool gs_only (const _mesa_glsl_parse_state *state)
static bool v110 (const _mesa_glsl_parse_state *state)
static bool v110_fs_only (const _mesa_glsl_parse_state *state)
static bool v120 (const _mesa_glsl_parse_state *state)
static bool v130 (const _mesa_glsl_parse_state *state)
static bool v130_desktop (const _mesa_glsl_parse_state *state)
static bool v130_fs_only (const _mesa_glsl_parse_state *state)
static bool v140_or_es3 (const _mesa_glsl_parse_state *state)
static bool v400_fs_only (const _mesa_glsl_parse_state *state)
static bool texture_rectangle (const _mesa_glsl_parse_state *state)
static bool texture_external (const _mesa_glsl_parse_state *state)
static bool lod_exists_in_stage (const _mesa_glsl_parse_state *state)
True if texturing functions with explicit LOD are allowed.
static bool v110_lod (const _mesa_glsl_parse_state *state)
static bool texture_buffer (const _mesa_glsl_parse_state *state)
static bool shader_texture_lod (const _mesa_glsl_parse_state *state)
static bool shader_texture_lod_and_rect (const _mesa_glsl_parse_state *state)
static bool shader_bit_encoding (const _mesa_glsl_parse_state *state)
static bool shader_integer_mix (const _mesa_glsl_parse_state *state)
static bool shader_packing_or_es3 (const _mesa_glsl_parse_state *state)
static bool shader_packing_or_es3_or_gpu_shader5 (const _mesa_glsl_parse_state *state)
static bool gpu_shader5 (const _mesa_glsl_parse_state *state)
static bool gpu_shader5_es (const _mesa_glsl_parse_state *state)
static bool gpu_shader5_or_OES_texture_cube_map_array (const _mesa_glsl_parse_state *state)
static bool es31_not_gs5 (const _mesa_glsl_parse_state *state)
static bool gpu_shader5_or_es31 (const _mesa_glsl_parse_state *state)
static bool shader_packing_or_es31_or_gpu_shader5 (const _mesa_glsl_parse_state *state)
static bool gpu_shader5_or_es31_or_integer_functions (const _mesa_glsl_parse_state *state)
static bool fs_interpolate_at (const _mesa_glsl_parse_state *state)
static bool texture_array_lod (const _mesa_glsl_parse_state *state)
static bool fs_texture_array (const _mesa_glsl_parse_state *state)
static bool texture_array (const _mesa_glsl_parse_state *state)
static bool texture_multisample (const _mesa_glsl_parse_state *state)
static bool texture_multisample_array (const _mesa_glsl_parse_state *state)
static bool texture_samples_identical (const _mesa_glsl_parse_state *state)
static bool texture_samples_identical_array (const _mesa_glsl_parse_state *state)
static bool fs_texture_cube_map_array (const _mesa_glsl_parse_state *state)
static bool texture_cube_map_array (const _mesa_glsl_parse_state *state)
static bool texture_query_levels (const _mesa_glsl_parse_state *state)
static bool texture_query_lod (const _mesa_glsl_parse_state *state)
static bool texture_gather_cube_map_array (const _mesa_glsl_parse_state *state)
static bool texture_gather_or_es31 (const _mesa_glsl_parse_state *state)
static bool texture_gather_only_or_es31 (const _mesa_glsl_parse_state *state)
static bool fs_oes_derivatives (const _mesa_glsl_parse_state *state)
static bool fs_derivative_control (const _mesa_glsl_parse_state *state)
static bool tex1d_lod (const _mesa_glsl_parse_state *state)
static bool tex3d (const _mesa_glsl_parse_state *state)
True if sampler3D exists.
static bool fs_tex3d (const _mesa_glsl_parse_state *state)
static bool tex3d_lod (const _mesa_glsl_parse_state *state)
static bool shader_atomic_counters (const _mesa_glsl_parse_state *state)
static bool shader_atomic_counter_ops (const _mesa_glsl_parse_state *state)
static bool shader_ballot (const _mesa_glsl_parse_state *state)
static bool shader_clock (const _mesa_glsl_parse_state *state)
static bool shader_clock_int64 (const _mesa_glsl_parse_state *state)
static bool shader_storage_buffer_object (const _mesa_glsl_parse_state *state)
static bool shader_trinary_minmax (const _mesa_glsl_parse_state *state)
static bool shader_image_load_store (const _mesa_glsl_parse_state *state)
static bool shader_image_atomic (const _mesa_glsl_parse_state *state)
static bool shader_image_atomic_exchange_float (const _mesa_glsl_parse_state *state)
static bool shader_image_size (const _mesa_glsl_parse_state *state)
static bool shader_samples (const _mesa_glsl_parse_state *state)
static bool gs_streams (const _mesa_glsl_parse_state *state)
static bool fp64 (const _mesa_glsl_parse_state *state)
static bool int64 (const _mesa_glsl_parse_state *state)
static bool int64_fp64 (const _mesa_glsl_parse_state *state)
static bool compute_shader (const _mesa_glsl_parse_state *state)
static bool compute_shader_supported (const _mesa_glsl_parse_state *state)
static bool buffer_atomics_supported (const _mesa_glsl_parse_state *state)
static bool barrier_supported (const _mesa_glsl_parse_state *state)
static bool vote (const _mesa_glsl_parse_state *state)
static bool integer_functions_supported (const _mesa_glsl_parse_state *state)
void _mesa_glsl_initialize_builtin_functions ()
External API (exposing the built-in module to the rest of the compiler):
void _mesa_glsl_release_builtin_functions ()
ir_function_signature * _mesa_glsl_find_builtin_function (_mesa_glsl_parse_state *state, const char *name, exec_list *actual_parameters)
bool _mesa_glsl_has_builtin_function (const char *name)
gl_shader * _mesa_glsl_get_builtin_function_shader ()
ir_function_signature * _mesa_get_main_function_signature (glsl_symbol_table *symbols)
Get the function signature for main from a shader.
Variables
ir_unop_dFdx_coarse
fs_derivative_control ir_unop_dFdy
fs_derivative_control fs_oes_derivatives ir_unop_dFdy_fine
static builtin_builder builtins
static mtx_t builtins_lock = _MTX_INITIALIZER_NP
#define MAKE_SIG(return_type, avail, ...)
#define MAKE_INTRINSIC(return_type, id, avail, ...)
#define UNOP(NAME, OPCODE, AVAIL)
#define UNOPA(NAME, OPCODE)
#define BINOP(NAME, OPCODE, AVAIL)
ir_unop_cos
UNOP (sin, ir_unop_sin, always_available) UNOP(cos
ir_unop_log
always_available ir_unop_log2
UNOP (exp, ir_unop_exp, always_available) UNOP(log
always_available UNOP (exp2, ir_unop_exp2, always_available) UNOP(log2
always_available always_available UNOPA (sqrt, ir_unop_sqrt) UNOPA(inversesqrt
Detailed Description
Support for GLSL built-in functions.
This file is split into several main components:
Availability predicates
A series of small functions that check whether the current shader supports the version/extensions required to expose a built-in.
Core builtin_builder class functionality
Lists of built-in functions
The builtin_builder::create_builtins() function contains lists of all built-in function signatures, where they're available, what types they take, and so on.
Implementations of built-in function signatures
A series of functions which create ir_function_signatures and emit IR via ir_builder to implement them.
External API
A few functions the rest of the compiler can use to interact with the built-in function module. For example, searching for a built-in by name and parameters.
Macro Definition Documentation
B0
#define B0 (X) ir_function_signature *_##X();
B1
#define B1 (X) ir_function_signature *_##X(const glsl_type *);
B2
#define B2 (X) ir_function_signature *_##X(const glsl_type *, const glsl_type *);
B3
#define B3 (X) ir_function_signature *_##X(const glsl_type *, const glsl_type *, const glsl_type *);
BA1
#define BA1 (X) ir_function_signature *_##X(builtin_available_predicate, const glsl_type *);
BA2
#define BA2 (X) ir_function_signature *_##X(builtin_available_predicate, const glsl_type *, const glsl_type *);
BINOP
#define BINOP (NAME, OPCODE, AVAIL)
Value:
ir_function_signature *                                                 \
builtin_builder::_##NAME(const glsl_type *return_type,                  \
                         const glsl_type *param0_type,                  \
                         const glsl_type *param1_type)                  \
{                                                                       \
   return binop(&AVAIL, OPCODE, return_type, param0_type, param1_type); \
}
F
#define F (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(glsl_type::float_type), \
                _##NAME(glsl_type::vec2_type),  \
                _##NAME(glsl_type::vec3_type),  \
                _##NAME(glsl_type::vec4_type),  \
                NULL);
FD
#define FD (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(always_available, glsl_type::float_type), \
                _##NAME(always_available, glsl_type::vec2_type),  \
                _##NAME(always_available, glsl_type::vec3_type),  \
                _##NAME(always_available, glsl_type::vec4_type),  \
                _##NAME(fp64, glsl_type::double_type),  \
                _##NAME(fp64, glsl_type::dvec2_type),    \
                _##NAME(fp64, glsl_type::dvec3_type),     \
                _##NAME(fp64, glsl_type::dvec4_type),      \
                NULL);
FD130
#define FD130 (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(v130, glsl_type::float_type), \
                _##NAME(v130, glsl_type::vec2_type),  \
                _##NAME(v130, glsl_type::vec3_type),                  \
                _##NAME(v130, glsl_type::vec4_type),  \
                _##NAME(fp64, glsl_type::double_type),  \
                _##NAME(fp64, glsl_type::dvec2_type),    \
                _##NAME(fp64, glsl_type::dvec3_type),     \
                _##NAME(fp64, glsl_type::dvec4_type),      \
                NULL);
FDGS5
#define FDGS5 (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(gpu_shader5_es, glsl_type::float_type), \
                _##NAME(gpu_shader5_es, glsl_type::vec2_type),  \
                _##NAME(gpu_shader5_es, glsl_type::vec3_type),                  \
                _##NAME(gpu_shader5_es, glsl_type::vec4_type),  \
                _##NAME(fp64, glsl_type::double_type),  \
                _##NAME(fp64, glsl_type::dvec2_type),    \
                _##NAME(fp64, glsl_type::dvec3_type),     \
                _##NAME(fp64, glsl_type::dvec4_type),      \
                NULL);
FI
#define FI (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(glsl_type::float_type), \
                _##NAME(glsl_type::vec2_type),  \
                _##NAME(glsl_type::vec3_type),  \
                _##NAME(glsl_type::vec4_type),  \
                _##NAME(glsl_type::int_type),   \
                _##NAME(glsl_type::ivec2_type), \
                _##NAME(glsl_type::ivec3_type), \
                _##NAME(glsl_type::ivec4_type), \
                NULL);
FI64
#define FI64 (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(always_available, glsl_type::float_type), \
                _##NAME(always_available, glsl_type::vec2_type),  \
                _##NAME(always_available, glsl_type::vec3_type),  \
                _##NAME(always_available, glsl_type::vec4_type),  \
                _##NAME(always_available, glsl_type::int_type),   \
                _##NAME(always_available, glsl_type::ivec2_type), \
                _##NAME(always_available, glsl_type::ivec3_type), \
                _##NAME(always_available, glsl_type::ivec4_type), \
                _##NAME(fp64, glsl_type::double_type), \
                _##NAME(fp64, glsl_type::dvec2_type),  \
                _##NAME(fp64, glsl_type::dvec3_type),  \
                _##NAME(fp64, glsl_type::dvec4_type),  \
                _##NAME(int64, glsl_type::int64_t_type), \
                _##NAME(int64, glsl_type::i64vec2_type),  \
                _##NAME(int64, glsl_type::i64vec3_type),  \
                _##NAME(int64, glsl_type::i64vec4_type),  \
                NULL);
FIUBD_VEC
#define FIUBD_VEC (NAME)
Value:
add_function(#NAME,                                            \
                _##NAME(always_available, glsl_type::vec2_type),  \
                _##NAME(always_available, glsl_type::vec3_type),  \
                _##NAME(always_available, glsl_type::vec4_type),  \
                                                                  \
                _##NAME(always_available, glsl_type::ivec2_type), \
                _##NAME(always_available, glsl_type::ivec3_type), \
                _##NAME(always_available, glsl_type::ivec4_type), \
                                                                  \
                _##NAME(v130, glsl_type::uvec2_type),             \
                _##NAME(v130, glsl_type::uvec3_type),             \
                _##NAME(v130, glsl_type::uvec4_type),             \
                                                                  \
                _##NAME(always_available, glsl_type::bvec2_type), \
                _##NAME(always_available, glsl_type::bvec3_type), \
                _##NAME(always_available, glsl_type::bvec4_type), \
                                                                  \
                _##NAME(fp64, glsl_type::dvec2_type), \
                _##NAME(fp64, glsl_type::dvec3_type), \
                _##NAME(fp64, glsl_type::dvec4_type), \
                _##NAME(int64, glsl_type::int64_t_type), \
                _##NAME(int64, glsl_type::i64vec2_type),  \
                _##NAME(int64, glsl_type::i64vec3_type),  \
                _##NAME(int64, glsl_type::i64vec4_type),  \
                _##NAME(int64, glsl_type::uint64_t_type), \
                _##NAME(int64, glsl_type::u64vec2_type),  \
                _##NAME(int64, glsl_type::u64vec3_type),  \
                _##NAME(int64, glsl_type::u64vec4_type),  \
                NULL);
FIUD2_MIXED
#define FIUD2_MIXED (NAME)
FIUD_VEC
#define FIUD_VEC (NAME)
Value:
add_function(#NAME,                                            \
                _##NAME(always_available, glsl_type::vec2_type),  \
                _##NAME(always_available, glsl_type::vec3_type),  \
                _##NAME(always_available, glsl_type::vec4_type),  \
                                                                  \
                _##NAME(always_available, glsl_type::ivec2_type), \
                _##NAME(always_available, glsl_type::ivec3_type), \
                _##NAME(always_available, glsl_type::ivec4_type), \
                                                                  \
                _##NAME(v130, glsl_type::uvec2_type),             \
                _##NAME(v130, glsl_type::uvec3_type),             \
                _##NAME(v130, glsl_type::uvec4_type),             \
                _##NAME(fp64, glsl_type::dvec2_type),  \
                _##NAME(fp64, glsl_type::dvec3_type),  \
                _##NAME(fp64, glsl_type::dvec4_type),  \
                _##NAME(int64, glsl_type::int64_t_type), \
                _##NAME(int64, glsl_type::i64vec2_type),  \
                _##NAME(int64, glsl_type::i64vec3_type),  \
                _##NAME(int64, glsl_type::i64vec4_type),  \
                _##NAME(int64, glsl_type::uint64_t_type), \
                _##NAME(int64, glsl_type::u64vec2_type),  \
                _##NAME(int64, glsl_type::u64vec3_type),  \
                _##NAME(int64, glsl_type::u64vec4_type),  \
                NULL);
IMM_FP
#define IMM_FP (type, val) (type->base_type == GLSL_TYPE_DOUBLE) ? imm(val) : imm((float)val)
IU
#define IU (NAME)
Value:
add_function(#NAME,                          \
                _##NAME(glsl_type::int_type),   \
                _##NAME(glsl_type::ivec2_type), \
                _##NAME(glsl_type::ivec3_type), \
                _##NAME(glsl_type::ivec4_type), \
                                                \
                _##NAME(glsl_type::uint_type),  \
                _##NAME(glsl_type::uvec2_type), \
                _##NAME(glsl_type::uvec3_type), \
                _##NAME(glsl_type::uvec4_type), \
                NULL);
M_PI_2f
#define M_PI_2f ((float) M_PI_2)
M_PI_4f
#define M_PI_4f ((float) M_PI_4)
M_PIf
#define M_PIf ((float) M_PI)
Unfortunately, some versions of MinGW produce bad code if this file is compiled with -O2 or -O3.
The resulting driver will crash in random places if the app uses GLSL. The work-around is to disable optimizations for just this file. Luckily, this code is basically just executed once.
MinGW 4.6.3 (in Ubuntu 13.10) does not have this bug. MinGW 5.3.1 (in Ubuntu 16.04) definitely has this bug. MinGW 6.2.0 (in Ubuntu 16.10) definitely has this bug. MinGW x.y.z - don't know. Assume versions after 4.6.x are buggy
MAKE_INTRINSIC
#define MAKE_INTRINSIC (return_type, id, avail, ...)
Value:
ir_function_signature *sig =                      \
      new_sig(return_type, avail, __VA_ARGS__);      \
   sig->intrinsic_id = id;
Referenced by get_image_available_predicate(), and UNOP().
MAKE_SIG
#define MAKE_SIG (return_type, avail, ...)
Value:
ir_function_signature *sig =               \
      new_sig(return_type, avail, __VA_ARGS__);      \
   ir_factory body(&sig->body, mem_ctx);             \
   sig->is_defined = true;
Referenced by get_image_available_predicate(), and UNOP().
TEX_COMPONENT
#define TEX_COMPONENT 4
Referenced by UNOP().
TEX_OFFSET
#define TEX_OFFSET 2
Referenced by UNOP().
TEX_OFFSET_ARRAY
#define TEX_OFFSET_ARRAY 16
Referenced by UNOP().
TEX_OFFSET_NONCONST
#define TEX_OFFSET_NONCONST 8
Referenced by UNOP().
TEX_PROJECT
#define TEX_PROJECT 1
Flags to _texture()
Referenced by UNOP().
UNOP
#define UNOP (NAME, OPCODE, AVAIL)
Value:
ir_function_signature *                         \
builtin_builder::_##NAME(const glsl_type *type) \
{                                               \
   return unop(&AVAIL, OPCODE, type, type);     \
}
Referenced by UNOP().
UNOPA
#define UNOPA (NAME, OPCODE)
Value:
ir_function_signature *                         \
builtin_builder::_##NAME(builtin_available_predicate avail, const glsl_type *type) \
{                                               \
   return unop(avail, OPCODE, type, type);     \
}
Enumeration Type Documentation
image_function_flags
enum image_function_flags
Function Documentation
_mesa_get_main_function_signature()
ir_function_signature* _mesa_get_main_function_signature (glsl_symbol_table * symbols)
Get the function signature for main from a shader.
References glsl_symbol_table::get_function().
Referenced by _mesa_glsl_initialize_derived_variables(), link_intrastage_shaders(), and lower_vertex_id().
_mesa_glsl_find_builtin_function()
ir_function_signature* _mesa_glsl_find_builtin_function (_mesa_glsl_parse_state * state, const char * name, exec_list * actual_parameters)
References builtins_lock.
Referenced by match_function_by_name().
_mesa_glsl_get_builtin_function_shader()
gl_shader* _mesa_glsl_get_builtin_function_shader (void)
Referenced by no_matching_function_error().
_mesa_glsl_has_builtin_function()
bool _mesa_glsl_has_builtin_function (const char * name)
References builtins_lock.
Referenced by ast_function::hir().
_mesa_glsl_initialize_builtin_functions()
void _mesa_glsl_initialize_builtin_functions ()
External API (exposing the built-in module to the rest of the compiler):
References builtins_lock.
Referenced by ast_function::hir(), and match_function_by_name().
_mesa_glsl_release_builtin_functions()
void _mesa_glsl_release_builtin_functions (void)
References builtins_lock.
Referenced by _mesa_destroy_shader_compiler_caches(), and standalone_compiler_cleanup().
always_available()
static bool always_available (const _mesa_glsl_parse_state *) static
Availability predicates:
barrier_supported()
static bool barrier_supported (const _mesa_glsl_parse_state * state) static
References compute_shader().
Referenced by UNOP().
buffer_atomics_supported()
static bool buffer_atomics_supported (const _mesa_glsl_parse_state * state) static
References compute_shader(), and shader_storage_buffer_object().
compatibility_vs_only()
static bool compatibility_vs_only (const _mesa_glsl_parse_state * state) static
compute_shader()
static bool compute_shader (const _mesa_glsl_parse_state * state) static
Referenced by barrier_supported(), and buffer_atomics_supported().
compute_shader_supported()
static bool compute_shader_supported (const _mesa_glsl_parse_state * state) static
es31_not_gs5()
static bool es31_not_gs5 (const _mesa_glsl_parse_state * state) static
References gpu_shader5_es().
fp64()
static bool fp64 (const _mesa_glsl_parse_state * state) static
Referenced by UNOP().
fs_derivative_control()
static bool fs_derivative_control (const _mesa_glsl_parse_state * state) static
fs_interpolate_at()
static bool fs_interpolate_at (const _mesa_glsl_parse_state * state) static
Referenced by UNOP().
fs_oes_derivatives()
static bool fs_oes_derivatives (const _mesa_glsl_parse_state * state) static
Referenced by UNOP().
fs_only()
static bool fs_only (const _mesa_glsl_parse_state * state) static
fs_tex3d()
static bool fs_tex3d (const _mesa_glsl_parse_state * state) static
fs_texture_array()
static bool fs_texture_array (const _mesa_glsl_parse_state * state) static
fs_texture_cube_map_array()
static bool fs_texture_cube_map_array (const _mesa_glsl_parse_state * state) static
get_image_available_predicate()
static builtin_available_predicate get_image_available_predicate (const glsl_type * type, unsigned flags) static
References ir_builder::ir_factory::emit(), ir_builder::expr(), MAKE_INTRINSIC, MAKE_SIG, ir_builder::ir_factory::make_temp(), ir_builder::ret(), shader_ballot(), shader_image_atomic(), shader_image_atomic_exchange_float(), shader_image_load_store(), shader_image_size(), shader_samples(), and vote().
gpu_shader5()
static bool gpu_shader5 (const _mesa_glsl_parse_state * state) static
Referenced by gs_streams().
gpu_shader5_es()
static bool gpu_shader5_es (const _mesa_glsl_parse_state * state) static
Referenced by es31_not_gs5().
gpu_shader5_or_es31()
static bool gpu_shader5_or_es31 (const _mesa_glsl_parse_state * state) static
Referenced by gpu_shader5_or_es31_or_integer_functions().
gpu_shader5_or_es31_or_integer_functions()
static bool gpu_shader5_or_es31_or_integer_functions (const _mesa_glsl_parse_state * state) static
References gpu_shader5_or_es31().
Referenced by UNOP().
gpu_shader5_or_OES_texture_cube_map_array()
static bool gpu_shader5_or_OES_texture_cube_map_array (const _mesa_glsl_parse_state * state) static
gs_only()
static bool gs_only (const _mesa_glsl_parse_state * state) static
Referenced by gs_streams(), and UNOP().
gs_streams()
static bool gs_streams (const _mesa_glsl_parse_state * state) static
References gpu_shader5(), and gs_only().
int64()
static bool int64 (const _mesa_glsl_parse_state * state) static
Referenced by depth_layout_string().
int64_fp64()
static bool int64_fp64 (const _mesa_glsl_parse_state * state) static
integer_functions_supported()
static bool integer_functions_supported (const _mesa_glsl_parse_state * state) static
References ir_builder::ret().
lod_exists_in_stage()
static bool lod_exists_in_stage (const _mesa_glsl_parse_state * state) static
True if texturing functions with explicit LOD are allowed.
Referenced by tex1d_lod(), tex3d_lod(), texture_array_lod(), and v110_lod().
shader_atomic_counter_ops()
static bool shader_atomic_counter_ops (const _mesa_glsl_parse_state * state) static
shader_atomic_counters()
static bool shader_atomic_counters (const _mesa_glsl_parse_state * state) static
shader_ballot()
static bool shader_ballot (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate().
shader_bit_encoding()
static bool shader_bit_encoding (const _mesa_glsl_parse_state * state) static
shader_clock()
static bool shader_clock (const _mesa_glsl_parse_state * state) static
shader_clock_int64()
static bool shader_clock_int64 (const _mesa_glsl_parse_state * state) static
shader_image_atomic()
static bool shader_image_atomic (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate().
shader_image_atomic_exchange_float()
static bool shader_image_atomic_exchange_float (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate().
shader_image_load_store()
static bool shader_image_load_store (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate().
shader_image_size()
static bool shader_image_size (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate().
shader_integer_mix()
static bool shader_integer_mix (const _mesa_glsl_parse_state * state) static
References v130().
shader_packing_or_es3()
static bool shader_packing_or_es3 (const _mesa_glsl_parse_state * state) static
shader_packing_or_es31_or_gpu_shader5()
static bool shader_packing_or_es31_or_gpu_shader5 (const _mesa_glsl_parse_state * state) static
shader_packing_or_es3_or_gpu_shader5()
static bool shader_packing_or_es3_or_gpu_shader5 (const _mesa_glsl_parse_state * state) static
shader_samples()
static bool shader_samples (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate(), and UNOP().
shader_storage_buffer_object()
static bool shader_storage_buffer_object (const _mesa_glsl_parse_state * state) static
Referenced by buffer_atomics_supported().
shader_texture_lod()
static bool shader_texture_lod (const _mesa_glsl_parse_state * state) static
shader_texture_lod_and_rect()
static bool shader_texture_lod_and_rect (const _mesa_glsl_parse_state * state) static
shader_trinary_minmax()
static bool shader_trinary_minmax (const _mesa_glsl_parse_state * state) static
Referenced by UNOP().
tex1d_lod()
static bool tex1d_lod (const _mesa_glsl_parse_state * state) static
References lod_exists_in_stage().
tex3d()
static bool tex3d (const _mesa_glsl_parse_state * state) static
True if sampler3D exists.
Referenced by tex3d_lod().
tex3d_lod()
static bool tex3d_lod (const _mesa_glsl_parse_state * state) static
References lod_exists_in_stage(), and tex3d().
texture_array()
static bool texture_array (const _mesa_glsl_parse_state * state) static
texture_array_lod()
static bool texture_array_lod (const _mesa_glsl_parse_state * state) static
References lod_exists_in_stage().
texture_buffer()
static bool texture_buffer (const _mesa_glsl_parse_state * state) static
texture_cube_map_array()
static bool texture_cube_map_array (const _mesa_glsl_parse_state * state) static
Referenced by UNOP().
texture_external()
static bool texture_external (const _mesa_glsl_parse_state * state) static
texture_gather_cube_map_array()
static bool texture_gather_cube_map_array (const _mesa_glsl_parse_state * state) static
texture_gather_only_or_es31()
static bool texture_gather_only_or_es31 (const _mesa_glsl_parse_state * state) static
texture_gather_or_es31()
static bool texture_gather_or_es31 (const _mesa_glsl_parse_state * state) static
texture_multisample()
static bool texture_multisample (const _mesa_glsl_parse_state * state) static
Referenced by texture_samples_identical().
texture_multisample_array()
static bool texture_multisample_array (const _mesa_glsl_parse_state * state) static
Referenced by texture_samples_identical_array().
texture_query_levels()
static bool texture_query_levels (const _mesa_glsl_parse_state * state) static
Referenced by UNOP().
texture_query_lod()
static bool texture_query_lod (const _mesa_glsl_parse_state * state) static
texture_rectangle()
static bool texture_rectangle (const _mesa_glsl_parse_state * state) static
texture_samples_identical()
static bool texture_samples_identical (const _mesa_glsl_parse_state * state) static
References texture_multisample().
texture_samples_identical_array()
static bool texture_samples_identical_array (const _mesa_glsl_parse_state * state) static
References texture_multisample_array().
UNOP() [1/8]
UNOP (sin , ir_unop_sin , always_available)
UNOP() [2/8]
UNOP (exp , ir_unop_exp , always_available)
UNOP() [3/8]
always_available UNOP (exp2 , ir_unop_exp2 , always_available)
UNOP() [4/8]
UNOP (not , ir_unop_logic_not , always_available) const
References barrier_supported(), fs_oes_derivatives(), gs_only(), MAKE_SIG, ir_builder::ret(), shader_samples(), ir_builder::swizzle(), ir_builder::swizzle_for_size(), TEX_COMPONENT, TEX_OFFSET, TEX_OFFSET_ARRAY, TEX_OFFSET_NONCONST, TEX_PROJECT, texture_cube_map_array(), texture_query_levels(), and UNOP.
UNOP() [5/8]
UNOP (dFdx , ir_unop_dFdx , fs_oes_derivatives)
UNOP() [6/8]
fs_derivative_control UNOP (dFdxFine , ir_unop_dFdx_fine , fs_derivative_control)
UNOP() [7/8]
fs_derivative_control fs_oes_derivatives UNOP (dFdyCoarse , ir_unop_dFdy_coarse , fs_derivative_control)
UNOP() [8/8]
UNOP (bitfieldReverse , ir_unop_bitfield_reverse , gpu_shader5_or_es31_or_integer_functions)
References ir_builder::abs(), ir_builder::add(), ir_builder::assign(), ir_builder::bit_and(), ir_builder::bit_or(), ir_builder::bitcast_f2i(), ir_builder::bitcast_f2u(), ir_builder::bitcast_u2f(), ir_builder::borrow(), ir_builder::carry(), ir_builder::csel(), ir_builder::expr(), ir_builder::fma(), fp64(), fs_interpolate_at(), gpu_shader5_or_es31_or_integer_functions(), ir_builder::imul_high(), ir_builder::interpolate_at_centroid(), ir_builder::interpolate_at_offset(), ir_builder::interpolate_at_sample(), MAKE_INTRINSIC, MAKE_SIG, ir_builder::max2(), ir_builder::min2(), ir_builder::mul(), ir_builder::neg(), ir_builder::nequal(), ir_builder::ret(), ir_builder::rshift(), shader_trinary_minmax(), and ir_builder::sub().
UNOPA() [1/5]
always_available always_available UNOPA (sqrt , ir_unop_sqrt)
UNOPA() [2/5]
always_available always_available ir_unop_rsq UNOPA (abs , ir_unop_abs)
UNOPA() [3/5]
always_available always_available ir_unop_rsq ir_unop_sign UNOPA (floor , ir_unop_floor)
UNOPA() [4/5]
always_available always_available ir_unop_rsq ir_unop_sign ir_unop_trunc UNOPA (round , ir_unop_round_even)
UNOPA() [5/5]
always_available always_available ir_unop_rsq ir_unop_sign ir_unop_trunc ir_unop_round_even UNOPA (ceil , ir_unop_ceil)
v110()
static bool v110 (const _mesa_glsl_parse_state * state) static
v110_fs_only()
static bool v110_fs_only (const _mesa_glsl_parse_state * state) static
v110_lod()
static bool v110_lod (const _mesa_glsl_parse_state * state) static
References lod_exists_in_stage().
v120()
static bool v120 (const _mesa_glsl_parse_state * state) static
v130()
static bool v130 (const _mesa_glsl_parse_state * state) static
Referenced by shader_integer_mix().
v130_desktop()
static bool v130_desktop (const _mesa_glsl_parse_state * state) static
v130_fs_only()
static bool v130_fs_only (const _mesa_glsl_parse_state * state) static
v140_or_es3()
static bool v140_or_es3 (const _mesa_glsl_parse_state * state) static
v400_fs_only()
static bool v400_fs_only (const _mesa_glsl_parse_state * state) static
vote()
static bool vote (const _mesa_glsl_parse_state * state) static
Referenced by get_image_available_predicate().
Variable Documentation
builtins
builtin_builder builtins static
builtins_lock
mtx_t builtins_lock = _MTX_INITIALIZER_NP static
Referenced by _mesa_glsl_find_builtin_function(), _mesa_glsl_has_builtin_function(), _mesa_glsl_initialize_builtin_functions(), and _mesa_glsl_release_builtin_functions().
ir_unop_cos
ir_unop_cos
Referenced by ir_builder::cos(), type_is_signed(), and update_rhs_swizzle().
ir_unop_dFdx_coarse
ir_unop_dFdx_coarse
Referenced by type_is_signed(), and update_rhs_swizzle().
ir_unop_dFdy
fs_derivative_control ir_unop_dFdy
Referenced by type_is_signed(), and update_rhs_swizzle().
ir_unop_dFdy_fine
fs_derivative_control fs_oes_derivatives ir_unop_dFdy_fine
Referenced by type_is_signed(), and update_rhs_swizzle().
ir_unop_log
ir_unop_log
Referenced by ir_builder::log(), lower_instructions(), try_replace_with_dot(), type_is_signed(), and update_rhs_swizzle().
ir_unop_log2
always_available ir_unop_log2
Referenced by lower_instructions(), try_replace_with_dot(), type_is_signed(), and update_rhs_swizzle().