Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
builtin_types.cpp File Reference
The glsl_type class has static members to represent all the built-in types (such as the glsl_type::_float_type flyweight) as well as convenience pointer accessors (such as glsl_type::float_type).
#include "compiler/glsl_types.h"
#include "glsl_parser_extras.h"
#include "util/macros.h"
#include "compiler/builtin_type_macros.h"
Data Structures
struct builtin_type_versions
#define DECL_TYPE(NAME, ...)
Declarations of type flyweights (glsl_type::_foo_type) and convenience pointers (glsl_type::foo_type).
#define STRUCT_TYPE(NAME)
static const struct glsl_struct_field gl_DepthRangeParameters_fields []
static const struct glsl_struct_field gl_PointParameters_fields []
static const struct glsl_struct_field gl_MaterialParameters_fields []
static const struct glsl_struct_field gl_LightSourceParameters_fields []
static const struct glsl_struct_field gl_LightModelParameters_fields []
static const struct glsl_struct_field gl_LightModelProducts_fields []
static const struct glsl_struct_field gl_LightProducts_fields []
static const struct glsl_struct_field gl_FogParameters_fields []
#define T(TYPE, MIN_GL, MIN_ES) { glsl_type::TYPE##_type, MIN_GL, MIN_ES },
Code to populate a symbol table with the built-in types available in a particular shading language version.
static const struct builtin_type_versions builtin_type_versions []
static const glsl_type *const deprecated_types []
static void add_type (glsl_symbol_table *symbols, const glsl_type *const type)
void _mesa_glsl_initialize_types (struct _mesa_glsl_parse_state *state)
Populate the symbol table with available built-in types.
Detailed Description
The glsl_type class has static members to represent all the built-in types (such as the glsl_type::_float_type flyweight) as well as convenience pointer accessors (such as glsl_type::float_type).
Those global variables are declared and initialized in this file.
This also contains _mesa_glsl_initialize_types(), a function which populates a symbol table with the available built-in types for a particular language version and set of enabled extensions.
Macro Definition Documentation
DECL_TYPE
#define DECL_TYPE (NAME, ...)
Declarations of type flyweights (glsl_type::_foo_type) and convenience pointers (glsl_type::foo_type).
STRUCT_TYPE
#define STRUCT_TYPE (NAME)
Value:
const glsl_type glsl_type::_struct_##NAME##_type =           \
      glsl_type(NAME##_fields, ARRAY_SIZE(NAME##_fields), #NAME); \
   const glsl_type *const glsl_type::struct_##NAME##_type =     \
      &glsl_type::_struct_##NAME##_type;
T
#define T (TYPE, MIN_GL, MIN_ES) { glsl_type::TYPE##_type, MIN_GL, MIN_ES },
Code to populate a symbol table with the built-in types available in a particular shading language version.
The table below contains tags every type with the GLSL/GLSL ES versions where it was introduced.
Function Documentation
_mesa_glsl_initialize_types()
void _mesa_glsl_initialize_types (struct _mesa_glsl_parse_state * state)
Populate the symbol table with available built-in types.
References add_type(), deprecated_types, builtin_type_versions::min_es, builtin_type_versions::min_gl, and builtin_type_versions::type.
Referenced by test_optpass().
add_type()
static void add_type (glsl_symbol_table * symbols, const glsl_type *const type) inline static
References glsl_symbol_table::add_type().
Referenced by _mesa_glsl_initialize_types().
Variable Documentation
builtin_type_versions
const struct builtin_type_versions builtin_type_versions[] static
deprecated_types
const glsl_type* const deprecated_types[] static
Initial value:
= {
   glsl_type::struct_gl_PointParameters_type,
   glsl_type::struct_gl_MaterialParameters_type,
   glsl_type::struct_gl_LightSourceParameters_type,
   glsl_type::struct_gl_LightModelParameters_type,
   glsl_type::struct_gl_LightModelProducts_type,
   glsl_type::struct_gl_LightProducts_type,
   glsl_type::struct_gl_FogParameters_type,
}
Referenced by _mesa_glsl_initialize_types().
gl_DepthRangeParameters_fields
const struct glsl_struct_field gl_DepthRangeParameters_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::float_type, "near"),
   glsl_struct_field(glsl_type::float_type, "far"),
   glsl_struct_field(glsl_type::float_type, "diff"),
}
gl_FogParameters_fields
const struct glsl_struct_field gl_FogParameters_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::vec4_type, "color"),
   glsl_struct_field(glsl_type::float_type, "density"),
   glsl_struct_field(glsl_type::float_type, "start"),
   glsl_struct_field(glsl_type::float_type, "end"),
   glsl_struct_field(glsl_type::float_type, "scale"),
}
gl_LightModelParameters_fields
const struct glsl_struct_field gl_LightModelParameters_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::vec4_type, "ambient"),
}
gl_LightModelProducts_fields
const struct glsl_struct_field gl_LightModelProducts_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::vec4_type, "sceneColor"),
}
gl_LightProducts_fields
const struct glsl_struct_field gl_LightProducts_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::vec4_type, "ambient"),
   glsl_struct_field(glsl_type::vec4_type, "diffuse"),
   glsl_struct_field(glsl_type::vec4_type, "specular"),
}
gl_LightSourceParameters_fields
const struct glsl_struct_field gl_LightSourceParameters_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::vec4_type, "ambient"),
   glsl_struct_field(glsl_type::vec4_type, "diffuse"),
   glsl_struct_field(glsl_type::vec4_type, "specular"),
   glsl_struct_field(glsl_type::vec4_type, "position"),
   glsl_struct_field(glsl_type::vec4_type, "halfVector"),
   glsl_struct_field(glsl_type::vec3_type, "spotDirection"),
   glsl_struct_field(glsl_type::float_type, "spotExponent"),
   glsl_struct_field(glsl_type::float_type, "spotCutoff"),
   glsl_struct_field(glsl_type::float_type, "spotCosCutoff"),
   glsl_struct_field(glsl_type::float_type, "constantAttenuation"),
   glsl_struct_field(glsl_type::float_type, "linearAttenuation"),
   glsl_struct_field(glsl_type::float_type, "quadraticAttenuation"),
}
gl_MaterialParameters_fields
const struct glsl_struct_field gl_MaterialParameters_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::vec4_type, "emission"),
   glsl_struct_field(glsl_type::vec4_type, "ambient"),
   glsl_struct_field(glsl_type::vec4_type, "diffuse"),
   glsl_struct_field(glsl_type::vec4_type, "specular"),
   glsl_struct_field(glsl_type::float_type, "shininess"),
}
gl_PointParameters_fields
const struct glsl_struct_field gl_PointParameters_fields[] static
Initial value:
= {
   glsl_struct_field(glsl_type::float_type, "size"),
   glsl_struct_field(glsl_type::float_type, "sizeMin"),
   glsl_struct_field(glsl_type::float_type, "sizeMax"),
   glsl_struct_field(glsl_type::float_type, "fadeThresholdSize"),
   glsl_struct_field(glsl_type::float_type, "distanceConstantAttenuation"),
   glsl_struct_field(glsl_type::float_type, "distanceLinearAttenuation"),
   glsl_struct_field(glsl_type::float_type, "distanceQuadraticAttenuation"),
}