Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
builtin_functions.h File Reference
Namespaces
generate_ir
Functions
void _mesa_glsl_initialize_builtin_functions ()
External API (exposing the built-in module to the rest of the compiler):
ir_function_signature * _mesa_glsl_find_builtin_function (_mesa_glsl_parse_state *state, const char *name, exec_list *actual_parameters)
bool _mesa_glsl_has_builtin_function (const char *name)
gl_shader * _mesa_glsl_get_builtin_function_shader (void)
ir_function_signature * _mesa_get_main_function_signature (glsl_symbol_table *symbols)
Get the function signature for main from a shader.
void _mesa_glsl_release_builtin_functions (void)
ir_function_signature * generate_ir::udiv64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * generate_ir::idiv64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * generate_ir::umod64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * generate_ir::imod64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * generate_ir::umul64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * generate_ir::sign64 (void *mem_ctx, builtin_available_predicate avail)
Function Documentation
_mesa_get_main_function_signature()
ir_function_signature* _mesa_get_main_function_signature (glsl_symbol_table * symbols)
Get the function signature for main from a shader.
References glsl_symbol_table::get_function().
Referenced by _mesa_glsl_initialize_derived_variables(), link_intrastage_shaders(), and lower_vertex_id().
_mesa_glsl_find_builtin_function()
ir_function_signature* _mesa_glsl_find_builtin_function (_mesa_glsl_parse_state * state, const char * name, exec_list * actual_parameters)
References builtins_lock.
Referenced by match_function_by_name().
_mesa_glsl_get_builtin_function_shader()
gl_shader* _mesa_glsl_get_builtin_function_shader (void)
Referenced by no_matching_function_error().
_mesa_glsl_has_builtin_function()
bool _mesa_glsl_has_builtin_function (const char * name)
References builtins_lock.
Referenced by ast_function::hir().
_mesa_glsl_initialize_builtin_functions()
void _mesa_glsl_initialize_builtin_functions ()
External API (exposing the built-in module to the rest of the compiler):
References builtins_lock.
Referenced by ast_function::hir(), and match_function_by_name().
_mesa_glsl_release_builtin_functions()
void _mesa_glsl_release_builtin_functions (void)
References builtins_lock.
Referenced by _mesa_destroy_shader_compiler_caches(), and standalone_compiler_cleanup().