Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
builtin_variables.cpp File Reference
#include "ir.h"
#include "ir_builder.h"
#include "linker.h"
#include "glsl_parser_extras.h"
#include "glsl_symbol_table.h"
#include "main/core.h"
#include "main/uniforms.h"
#include "program/prog_statevars.h"
#include "program/prog_instruction.h"
#include "builtin_functions.h"
Macros
#define MATRIX(name, statevar, modifier)
#define STATEVAR(name) {#name, name ## _elements, ARRAY_SIZE(name ## _elements)}
Functions
MATRIX (gl_ModelViewMatrix, STATE_MODELVIEW_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ModelViewMatrixInverse, STATE_MODELVIEW_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_ModelViewMatrixTranspose, STATE_MODELVIEW_MATRIX, 0)
MATRIX (gl_ModelViewMatrixInverseTranspose, STATE_MODELVIEW_MATRIX, STATE_MATRIX_INVERSE)
MATRIX (gl_ProjectionMatrix, STATE_PROJECTION_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ProjectionMatrixInverse, STATE_PROJECTION_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_ProjectionMatrixTranspose, STATE_PROJECTION_MATRIX, 0)
MATRIX (gl_ProjectionMatrixInverseTranspose, STATE_PROJECTION_MATRIX, STATE_MATRIX_INVERSE)
MATRIX (gl_ModelViewProjectionMatrix, STATE_MVP_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ModelViewProjectionMatrixInverse, STATE_MVP_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_ModelViewProjectionMatrixTranspose, STATE_MVP_MATRIX, 0)
MATRIX (gl_ModelViewProjectionMatrixInverseTranspose, STATE_MVP_MATRIX, STATE_MATRIX_INVERSE)
MATRIX (gl_TextureMatrix, STATE_TEXTURE_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_TextureMatrixInverse, STATE_TEXTURE_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_TextureMatrixTranspose, STATE_TEXTURE_MATRIX, 0)
MATRIX (gl_TextureMatrixInverseTranspose, STATE_TEXTURE_MATRIX, STATE_MATRIX_INVERSE)
void _mesa_glsl_initialize_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void initialize_cs_derived_variables (gl_shader *shader, ir_function_signature *const main_sig)
Initialize compute shader variables with values that are derived from other compute shader variable.
void _mesa_glsl_initialize_derived_variables (struct gl_context *ctx, gl_shader *shader)
Initialize builtin variables with values based on other builtin variables.
Variables
static const struct gl_builtin_uniform_element gl_NumSamples_elements []
static const struct gl_builtin_uniform_element gl_PatchVerticesIn_elements []
static const struct gl_builtin_uniform_element gl_DepthRange_elements []
static const struct gl_builtin_uniform_element gl_ClipPlane_elements []
static const struct gl_builtin_uniform_element gl_Point_elements []
static const struct gl_builtin_uniform_element gl_FrontMaterial_elements []
static const struct gl_builtin_uniform_element gl_BackMaterial_elements []
static const struct gl_builtin_uniform_element gl_LightSource_elements []
static const struct gl_builtin_uniform_element gl_LightModel_elements []
static const struct gl_builtin_uniform_element gl_FrontLightModelProduct_elements []
static const struct gl_builtin_uniform_element gl_BackLightModelProduct_elements []
static const struct gl_builtin_uniform_element gl_FrontLightProduct_elements []
static const struct gl_builtin_uniform_element gl_BackLightProduct_elements []
static const struct gl_builtin_uniform_element gl_TextureEnvColor_elements []
static const struct gl_builtin_uniform_element gl_EyePlaneS_elements []
static const struct gl_builtin_uniform_element gl_EyePlaneT_elements []
static const struct gl_builtin_uniform_element gl_EyePlaneR_elements []
static const struct gl_builtin_uniform_element gl_EyePlaneQ_elements []
static const struct gl_builtin_uniform_element gl_ObjectPlaneS_elements []
static const struct gl_builtin_uniform_element gl_ObjectPlaneT_elements []
static const struct gl_builtin_uniform_element gl_ObjectPlaneR_elements []
static const struct gl_builtin_uniform_element gl_ObjectPlaneQ_elements []
static const struct gl_builtin_uniform_element gl_Fog_elements []
static const struct gl_builtin_uniform_element gl_NormalScale_elements []
static const struct gl_builtin_uniform_element gl_FogParamsOptimizedMESA_elements []
static const struct gl_builtin_uniform_element gl_CurrentAttribVertMESA_elements []
static const struct gl_builtin_uniform_element gl_CurrentAttribFragMESA_elements []
static const struct gl_builtin_uniform_element gl_NormalMatrix_elements []
static const struct gl_builtin_uniform_desc _mesa_builtin_uniform_desc []
Macro Definition Documentation
MATRIX
#define MATRIX (name, statevar, modifier)
Value:
static const struct gl_builtin_uniform_element name ## _elements[] = { \
      { NULL, { statevar, 0, 0, 0, modifier}, SWIZZLE_XYZW },           \
      { NULL, { statevar, 0, 1, 1, modifier}, SWIZZLE_XYZW },           \
      { NULL, { statevar, 0, 2, 2, modifier}, SWIZZLE_XYZW },           \
      { NULL, { statevar, 0, 3, 3, modifier}, SWIZZLE_XYZW },           \
   }
STATEVAR
#define STATEVAR (name) {#name, name ## _elements, ARRAY_SIZE(name ## _elements)}
Function Documentation
_mesa_glsl_initialize_derived_variables()
void _mesa_glsl_initialize_derived_variables (struct gl_context * ctx, gl_shader * shader)
Initialize builtin variables with values based on other builtin variables.
These are initialized in the main function.
References _mesa_get_main_function_signature(), and initialize_cs_derived_variables().
Referenced by _mesa_glsl_compile_shader().
_mesa_glsl_initialize_variables()
void _mesa_glsl_initialize_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state)
Referenced by _mesa_ast_to_hir().
initialize_cs_derived_variables()
static void initialize_cs_derived_variables (gl_shader * shader, ir_function_signature *const main_sig) static
Initialize compute shader variables with values that are derived from other compute shader variable.
References ir_builder::add(), ir_builder::assign(), ir_builder::mul(), ir_builder::swizzle_x(), ir_builder::swizzle_y(), and ir_builder::swizzle_z().
Referenced by _mesa_glsl_initialize_derived_variables().
MATRIX() [1/16]
MATRIX (gl_ModelViewMatrix , STATE_MODELVIEW_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX() [2/16]
MATRIX (gl_ModelViewMatrixInverse , STATE_MODELVIEW_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX() [3/16]
MATRIX (gl_ModelViewMatrixTranspose , STATE_MODELVIEW_MATRIX , 0)
MATRIX() [4/16]
MATRIX (gl_ModelViewMatrixInverseTranspose , STATE_MODELVIEW_MATRIX , STATE_MATRIX_INVERSE)
MATRIX() [5/16]
MATRIX (gl_ProjectionMatrix , STATE_PROJECTION_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX() [6/16]
MATRIX (gl_ProjectionMatrixInverse , STATE_PROJECTION_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX() [7/16]
MATRIX (gl_ProjectionMatrixTranspose , STATE_PROJECTION_MATRIX , 0)
MATRIX() [8/16]
MATRIX (gl_ProjectionMatrixInverseTranspose , STATE_PROJECTION_MATRIX , STATE_MATRIX_INVERSE)
MATRIX() [9/16]
MATRIX (gl_ModelViewProjectionMatrix , STATE_MVP_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX() [10/16]
MATRIX (gl_ModelViewProjectionMatrixInverse , STATE_MVP_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX() [11/16]
MATRIX (gl_ModelViewProjectionMatrixTranspose , STATE_MVP_MATRIX , 0)
MATRIX() [12/16]
MATRIX (gl_ModelViewProjectionMatrixInverseTranspose , STATE_MVP_MATRIX , STATE_MATRIX_INVERSE)
MATRIX() [13/16]
MATRIX (gl_TextureMatrix , STATE_TEXTURE_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX() [14/16]
MATRIX (gl_TextureMatrixInverse , STATE_TEXTURE_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX() [15/16]
MATRIX (gl_TextureMatrixTranspose , STATE_TEXTURE_MATRIX , 0)
MATRIX() [16/16]
MATRIX (gl_TextureMatrixInverseTranspose , STATE_TEXTURE_MATRIX , STATE_MATRIX_INVERSE)
Variable Documentation
_mesa_builtin_uniform_desc
const struct gl_builtin_uniform_desc _mesa_builtin_uniform_desc[] static
gl_BackLightModelProduct_elements
const struct gl_builtin_uniform_element gl_BackLightModelProduct_elements[] static
Initial value:
= {
   {"sceneColor", {STATE_LIGHTMODEL_SCENECOLOR, 1}, SWIZZLE_XYZW},
}
gl_BackLightProduct_elements
const struct gl_builtin_uniform_element gl_BackLightProduct_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHTPROD, 0, 1, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_LIGHTPROD, 0, 1, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_LIGHTPROD, 0, 1, STATE_SPECULAR}, SWIZZLE_XYZW},
}
gl_BackMaterial_elements
const struct gl_builtin_uniform_element gl_BackMaterial_elements[] static
Initial value:
= {
   {"emission", {STATE_MATERIAL, 1, STATE_EMISSION}, SWIZZLE_XYZW},
   {"ambient", {STATE_MATERIAL, 1, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_MATERIAL, 1, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_MATERIAL, 1, STATE_SPECULAR}, SWIZZLE_XYZW},
   {"shininess", {STATE_MATERIAL, 1, STATE_SHININESS}, SWIZZLE_XXXX},
}
gl_ClipPlane_elements
const struct gl_builtin_uniform_element gl_ClipPlane_elements[] static
Initial value:
= {
   {NULL, {STATE_CLIPPLANE, 0, 0}, SWIZZLE_XYZW}
}
gl_CurrentAttribFragMESA_elements
const struct gl_builtin_uniform_element gl_CurrentAttribFragMESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_CURRENT_ATTRIB_MAYBE_VP_CLAMPED, 0}, SWIZZLE_XYZW},
}
gl_CurrentAttribVertMESA_elements
const struct gl_builtin_uniform_element gl_CurrentAttribVertMESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_CURRENT_ATTRIB, 0}, SWIZZLE_XYZW},
}
gl_DepthRange_elements
const struct gl_builtin_uniform_element gl_DepthRange_elements[] static
Initial value:
= {
   {"near", {STATE_DEPTH_RANGE, 0, 0}, SWIZZLE_XXXX},
   {"far", {STATE_DEPTH_RANGE, 0, 0}, SWIZZLE_YYYY},
   {"diff", {STATE_DEPTH_RANGE, 0, 0}, SWIZZLE_ZZZZ},
}
gl_EyePlaneQ_elements
const struct gl_builtin_uniform_element gl_EyePlaneQ_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_Q}, SWIZZLE_XYZW},
}
gl_EyePlaneR_elements
const struct gl_builtin_uniform_element gl_EyePlaneR_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_R}, SWIZZLE_XYZW},
}
gl_EyePlaneS_elements
const struct gl_builtin_uniform_element gl_EyePlaneS_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_S}, SWIZZLE_XYZW},
}
gl_EyePlaneT_elements
const struct gl_builtin_uniform_element gl_EyePlaneT_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_T}, SWIZZLE_XYZW},
}
gl_Fog_elements
const struct gl_builtin_uniform_element gl_Fog_elements[] static
Initial value:
= {
   {"color", {STATE_FOG_COLOR}, SWIZZLE_XYZW},
   {"density", {STATE_FOG_PARAMS}, SWIZZLE_XXXX},
   {"start", {STATE_FOG_PARAMS}, SWIZZLE_YYYY},
   {"end", {STATE_FOG_PARAMS}, SWIZZLE_ZZZZ},
   {"scale", {STATE_FOG_PARAMS}, SWIZZLE_WWWW},
}
gl_FogParamsOptimizedMESA_elements
const struct gl_builtin_uniform_element gl_FogParamsOptimizedMESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_FOG_PARAMS_OPTIMIZED}, SWIZZLE_XYZW},
}
gl_FrontLightModelProduct_elements
const struct gl_builtin_uniform_element gl_FrontLightModelProduct_elements[] static
Initial value:
= {
   {"sceneColor", {STATE_LIGHTMODEL_SCENECOLOR, 0}, SWIZZLE_XYZW},
}
gl_FrontLightProduct_elements
const struct gl_builtin_uniform_element gl_FrontLightProduct_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHTPROD, 0, 0, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_LIGHTPROD, 0, 0, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_LIGHTPROD, 0, 0, STATE_SPECULAR}, SWIZZLE_XYZW},
}
gl_FrontMaterial_elements
const struct gl_builtin_uniform_element gl_FrontMaterial_elements[] static
Initial value:
= {
   {"emission", {STATE_MATERIAL, 0, STATE_EMISSION}, SWIZZLE_XYZW},
   {"ambient", {STATE_MATERIAL, 0, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_MATERIAL, 0, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_MATERIAL, 0, STATE_SPECULAR}, SWIZZLE_XYZW},
   {"shininess", {STATE_MATERIAL, 0, STATE_SHININESS}, SWIZZLE_XXXX},
}
gl_LightModel_elements
const struct gl_builtin_uniform_element gl_LightModel_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHTMODEL_AMBIENT, 0}, SWIZZLE_XYZW},
}
gl_LightSource_elements
const struct gl_builtin_uniform_element gl_LightSource_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHT, 0, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_LIGHT, 0, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_LIGHT, 0, STATE_SPECULAR}, SWIZZLE_XYZW},
   {"position", {STATE_LIGHT, 0, STATE_POSITION}, SWIZZLE_XYZW},
   {"halfVector", {STATE_LIGHT, 0, STATE_HALF_VECTOR}, SWIZZLE_XYZW},
   {"spotDirection", {STATE_LIGHT, 0, STATE_SPOT_DIRECTION},
    MAKE_SWIZZLE4(SWIZZLE_X,
                  SWIZZLE_Y,
                  SWIZZLE_Z,
                  SWIZZLE_Z)},
   {"spotCosCutoff", {STATE_LIGHT, 0, STATE_SPOT_DIRECTION}, SWIZZLE_WWWW},
   {"spotCutoff", {STATE_LIGHT, 0, STATE_SPOT_CUTOFF}, SWIZZLE_XXXX},
   {"spotExponent", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_WWWW},
   {"constantAttenuation", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_XXXX},
   {"linearAttenuation", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_YYYY},
   {"quadraticAttenuation", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_ZZZZ},
}
gl_NormalMatrix_elements
const struct gl_builtin_uniform_element gl_NormalMatrix_elements[] static
Initial value:
= {
   { NULL, { STATE_MODELVIEW_MATRIX, 0, 0, 0, STATE_MATRIX_INVERSE},
     MAKE_SWIZZLE4(SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_Z) },
   { NULL, { STATE_MODELVIEW_MATRIX, 0, 1, 1, STATE_MATRIX_INVERSE},
     MAKE_SWIZZLE4(SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_Z) },
   { NULL, { STATE_MODELVIEW_MATRIX, 0, 2, 2, STATE_MATRIX_INVERSE},
     MAKE_SWIZZLE4(SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_Z) },
}
gl_NormalScale_elements
const struct gl_builtin_uniform_element gl_NormalScale_elements[] static
Initial value:
= {
   {NULL, {STATE_NORMAL_SCALE}, SWIZZLE_XXXX},
}
gl_NumSamples_elements
const struct gl_builtin_uniform_element gl_NumSamples_elements[] static
Initial value:
= {
   {NULL, {STATE_NUM_SAMPLES, 0, 0}, SWIZZLE_XXXX}
}
gl_ObjectPlaneQ_elements
const struct gl_builtin_uniform_element gl_ObjectPlaneQ_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_Q}, SWIZZLE_XYZW},
}
gl_ObjectPlaneR_elements
const struct gl_builtin_uniform_element gl_ObjectPlaneR_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_R}, SWIZZLE_XYZW},
}
gl_ObjectPlaneS_elements
const struct gl_builtin_uniform_element gl_ObjectPlaneS_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_S}, SWIZZLE_XYZW},
}
gl_ObjectPlaneT_elements
const struct gl_builtin_uniform_element gl_ObjectPlaneT_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_T}, SWIZZLE_XYZW},
}
gl_PatchVerticesIn_elements
const struct gl_builtin_uniform_element gl_PatchVerticesIn_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_TCS_PATCH_VERTICES_IN}, SWIZZLE_XXXX}
}
gl_Point_elements
const struct gl_builtin_uniform_element gl_Point_elements[] static
Initial value:
= {
   {"size", {STATE_POINT_SIZE}, SWIZZLE_XXXX},
   {"sizeMin", {STATE_POINT_SIZE}, SWIZZLE_YYYY},
   {"sizeMax", {STATE_POINT_SIZE}, SWIZZLE_ZZZZ},
   {"fadeThresholdSize", {STATE_POINT_SIZE}, SWIZZLE_WWWW},
   {"distanceConstantAttenuation", {STATE_POINT_ATTENUATION}, SWIZZLE_XXXX},
   {"distanceLinearAttenuation", {STATE_POINT_ATTENUATION}, SWIZZLE_YYYY},
   {"distanceQuadraticAttenuation", {STATE_POINT_ATTENUATION}, SWIZZLE_ZZZZ},
}
gl_TextureEnvColor_elements
const struct gl_builtin_uniform_element gl_TextureEnvColor_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXENV_COLOR, 0}, SWIZZLE_XYZW},
}