Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_expression_flattening_visitor Class Reference
Public Member Functions
ir_expression_flattening_visitor (bool(*predicate)(ir_instruction *ir))
virtual ~ir_expression_flattening_visitor ()
void handle_rvalue (ir_rvalue **rvalue)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_discard *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
virtual ir_visitor_status visit_leave (ir_emit_vertex *)
virtual ir_visitor_status visit_leave (ir_end_primitive *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_discard *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
ir_visitor_status rvalue_visit (ir_emit_vertex *)
ir_visitor_status rvalue_visit (ir_end_primitive *)
Data Fields
bool(* predicate)(ir_instruction *ir)
Constructor & Destructor Documentation
ir_expression_flattening_visitor()
ir_expression_flattening_visitor::ir_expression_flattening_visitor (bool(*)(ir_instruction *ir) predicate) inline
References predicate.
~ir_expression_flattening_visitor()
virtual ir_expression_flattening_visitor::~ir_expression_flattening_visitor () inline virtual
References handle_rvalue().
Member Function Documentation
handle_rvalue()
void ir_expression_flattening_visitor::handle_rvalue (ir_rvalue ** rvalue) virtual
Implements ir_rvalue_base_visitor.
References ir_builder::assign(), and predicate.
Referenced by ~ir_expression_flattening_visitor().
Field Documentation
predicate
bool(* ir_expression_flattening_visitor::predicate) (ir_instruction *ir)
Referenced by do_expression_flattening(), handle_rvalue(), and ir_expression_flattening_visitor().
The documentation for this class was generated from the following file:
ir_expression_flattening.cpp