Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_symbol Class Reference
#include <s_expression.h>
Public Member Functions
s_symbol (const char *, size_t)
bool is_symbol () const
const char * value ()
void print ()
Print out an S-Expression.
Public Member Functions inherited from s_expression
virtual bool is_list () const
virtual bool is_number () const
virtual bool is_int () const
Additional Inherited Members
Static Public Member Functions inherited from s_expression
static s_expression * read_expression (void *ctx, const char *&src)
Read an S-Expression from the given string.
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Protected Member Functions inherited from s_expression
s_expression ()
Constructor & Destructor Documentation
s_symbol()
s_symbol::s_symbol (const char * str, size_t n)
Referenced by read_atom().
Member Function Documentation
is_symbol()
bool s_symbol::is_symbol () const inline virtual
Reimplemented from s_expression.
print()
void s_symbol::print () virtual
Print out an S-Expression.
Useful for debugging.
Implements s_expression.
value()
const char* s_symbol::value () inline
References s_expression::print().
Referenced by _mesa_glsl_read_ir(), always_available(), and s_pattern::match().
The documentation for this class was generated from the following files:
s_expression.h
s_expression.cpp