Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_array_refcount_entry Class Reference
#include <ir_array_refcount.h>
Public Member Functions
ir_array_refcount_entry (ir_variable *var)
~ir_array_refcount_entry ()
void mark_array_elements_referenced (const array_deref_range *dr, unsigned count)
Mark a set of array elements as accessed.
bool is_linearized_index_referenced (unsigned linearized_index) const
Has a linearized array index been referenced?
Data Fields
ir_variable * var
bool is_referenced
Has the variable been referenced?
Friends
class array_refcount_test
Constructor & Destructor Documentation
ir_array_refcount_entry()
ir_array_refcount_entry::ir_array_refcount_entry (ir_variable * var)
Referenced by ir_array_refcount_visitor::get_variable_entry().
~ir_array_refcount_entry()
ir_array_refcount_entry::~ir_array_refcount_entry ()
Member Function Documentation
is_linearized_index_referenced()
bool ir_array_refcount_entry::is_linearized_index_referenced (unsigned linearized_index) const inline
Has a linearized array index been referenced?
Referenced by link_update_uniform_buffer_variables().
mark_array_elements_referenced()
void ir_array_refcount_entry::mark_array_elements_referenced (const array_deref_range * dr, unsigned count)
Mark a set of array elements as accessed.
If every array_deref_range is for a single index, only a single element will be marked. If any array_deref_range is for an entire array-of-, then multiple elements will be marked.
Items in the array_deref_range list appear in least- to most-significant order. This is the opposite order the indices appear in the GLSL shader text. An array access like
x = y[1][i][3];
would appear as
{ { 3, n }, { m, m }, { 1, p } }
where n, m, and p are the sizes of the arrays-of-arrays.
The set of marked array elements can later be queried by ::is_linearized_index_referenced.
Parameters
dr List of array_deref_range elements to be processed.
count Number of array_deref_range elements to be processed.
References array_deref_range::index, and array_deref_range::size.
Referenced by ir_array_refcount_visitor::visit_enter().
Friends And Related Function Documentation
array_refcount_test
friend class array_refcount_test friend
Field Documentation
is_referenced
bool ir_array_refcount_entry::is_referenced
Has the variable been referenced?
Referenced by link_update_uniform_buffer_variables(), variable_is_referenced(), and ir_array_refcount_visitor::visit().
var
ir_variable* ir_array_refcount_entry::var
Referenced by ir_array_refcount_visitor::visit().
The documentation for this class was generated from the following files:
ir_array_refcount.h
ir_array_refcount.cpp