Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_builder_print_visitor Class Reference
Public Member Functions
ir_builder_print_visitor (FILE *f)
virtual ~ir_builder_print_visitor ()
void indent (void)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_return *)
Constructor & Destructor Documentation
ir_builder_print_visitor()
ir_builder_print_visitor::ir_builder_print_visitor (FILE * f)
~ir_builder_print_visitor()
ir_builder_print_visitor::~ir_builder_print_visitor () virtual
Member Function Documentation
indent()
void ir_builder_print_visitor::indent (void)
visit() [1/4]
ir_visitor_status ir_builder_print_visitor::visit (class ir_variable * ir) virtual
References visit_continue.
visit() [2/4]
ir_visitor_status ir_builder_print_visitor::visit (class ir_dereference_variable * ir) virtual
References visit_continue.
visit() [3/4]
ir_visitor_status ir_builder_print_visitor::visit (class ir_constant * ir) virtual
References is_simple_operand(), and visit_continue.
visit() [4/4]
ir_visitor_status ir_builder_print_visitor::visit (class ir_loop_jump * ir) virtual
References visit_continue.
visit_enter() [1/5]
ir_visitor_status ir_builder_print_visitor::visit_enter (class ir_if * ir) virtual
References visit_continue, visit_continue_with_parent, visit_list_elements(), and visit_stop.
visit_enter() [2/5]
ir_visitor_status ir_builder_print_visitor::visit_enter (class ir_loop * ir) virtual
References visit_continue.
visit_enter() [3/5]
ir_visitor_status ir_builder_print_visitor::visit_enter (class ir_function_signature * ir) virtual
References visit_continue, and visit_continue_with_parent.
visit_enter() [4/5]
ir_visitor_status ir_builder_print_visitor::visit_enter (class ir_expression * ir) virtual
References is_simple_operand(), and visit_continue_with_parent.
visit_enter() [5/5]
ir_visitor_status ir_builder_print_visitor::visit_enter (class ir_assignment * ir) virtual
References is_simple_operand(), visit_continue, and visit_continue_with_parent.
visit_leave() [1/6]
ir_visitor_status ir_builder_print_visitor::visit_leave (class ir_loop * ir) virtual
References visit_continue.
visit_leave() [2/6]
ir_visitor_status ir_builder_print_visitor::visit_leave (class ir_function_signature * ir) virtual
References visit_continue.
visit_leave() [3/6]
ir_visitor_status ir_builder_print_visitor::visit_leave (class ir_assignment * ir) virtual
References is_simple_operand(), and visit_continue.
visit_leave() [4/6]
ir_visitor_status ir_builder_print_visitor::visit_leave (class ir_call * ir) virtual
References foreach_in_list, and visit_continue.
visit_leave() [5/6]
ir_visitor_status ir_builder_print_visitor::visit_leave (class ir_swizzle * ir) virtual
References visit_continue.
visit_leave() [6/6]
ir_visitor_status ir_builder_print_visitor::visit_leave (class ir_return * ir) virtual
References visit_continue.
The documentation for this class was generated from the following file:
ir_builder_print_visitor.cpp