Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
program_resource_visitor Class Reference abstract
Class for processing all of the leaf fields of a variable that corresponds to a program resource.
#include <linker.h>
Public Member Functions
void process (ir_variable *var)
Begin processing a variable.
void process (const glsl_type *type, const char *name)
Begin processing a variable of a structured type.
Protected Member Functions
virtual void visit_field (const glsl_type *type, const char *name, bool row_major, const glsl_type *record_type, const enum glsl_interface_packing packing, bool last_field)=0
Method invoked for each leaf of the variable.
virtual void visit_field (const glsl_struct_field *field)
Visit a record before visiting its fields.
virtual void enter_record (const glsl_type *type, const char *name, bool row_major, const enum glsl_interface_packing packing)
virtual void leave_record (const glsl_type *type, const char *name, bool row_major, const enum glsl_interface_packing packing)
virtual void set_buffer_offset (unsigned offset)
virtual void set_record_array_count (unsigned record_array_count)
Detailed Description
Class for processing all of the leaf fields of a variable that corresponds to a program resource.
The leaf fields are all the parts of the variable that the application could query using glGetProgramResourceIndex (or that could be returned by glGetProgramResourceName).
Classes my derive from this class to implement specific functionality. This class only provides the mechanism to iterate over the leaves. Derived classes must implement ::visit_field and may override ::process.
Member Function Documentation
enter_record()
void program_resource_visitor::enter_record (const glsl_type * type, const char * name, bool row_major, const enum glsl_interface_packing packing) protected virtual
Referenced by process().
leave_record()
void program_resource_visitor::leave_record (const glsl_type * type, const char * name, bool row_major, const enum glsl_interface_packing packing) protected virtual
Referenced by process().
process() [1/2]
void program_resource_visitor::process (ir_variable * var)
Begin processing a variable.
Classes that overload this function should call ::process from the base class to start the recursive processing of the variable.
Parameters
var The variable that is to be processed
Calls ::visit_field for each leaf of the variable.
Warning
When processing a uniform block, this entry should only be used in cases where the row / column ordering of matrices in the block does not matter. For example, enumerating the names of members of the block, but not for determining the offsets of members.
References enter_record(), leave_record(), set_buffer_offset(), set_record_array_count(), and visit_field().
Referenced by tfeedback_candidate_generator::process(), parcel_out_uniform_storage::set_and_process(), and set_record_array_count().
process() [2/2]
void program_resource_visitor::process (const glsl_type * type, const char * name)
Begin processing a variable of a structured type.
This flavor of process should be used to handle structured types (i.e., structures, interfaces, or arrays there of) that need special name handling. A common usage is to handle cases where the block name (instead of the instance name) is used for an interface block.
Parameters
type Type that is to be processed, associated with name
name Base name of the structured variable being processed
Note
type must be GLSL_TYPE_RECORD, GLSL_TYPE_INTERFACE, or an array there of.
set_buffer_offset()
void program_resource_visitor::set_buffer_offset (unsigned offset) protected virtual
Referenced by process().
set_record_array_count()
void program_resource_visitor::set_record_array_count (unsigned record_array_count) protected virtual
References process(), values_for_type(), and visit_field().
Referenced by process().
visit_field() [1/2]
virtual void program_resource_visitor::visit_field (const glsl_type * type, const char * name, bool row_major, const glsl_type * record_type, const enum glsl_interface_packing packing, bool last_field) protected pure virtual
Method invoked for each leaf of the variable.
Parameters
type Type of the field.
name Fully qualified name of the field.
row_major For a matrix type, is it stored row-major.
record_type Type of the record containing the field.
last_field Set if name is the last field of the structure containing it. This will always be false for items not contained in a structure or interface block.
Referenced by process(), and set_record_array_count().
visit_field() [2/2]
void program_resource_visitor::visit_field (const glsl_struct_field * field) protected virtual
Visit a record before visiting its fields.
For structures-of-structures or interfaces-of-structures, this visits the inner structure before visiting its fields.
The default implementation does nothing.
The documentation for this class was generated from the following files:
linker.h
link_uniforms.cpp