Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
tfeedback_decl Class Reference
Data structure tracking information about a transform feedback declaration during linking.
#include <link_varyings.h>
Public Member Functions
void init (struct gl_context *ctx, const void *mem_ctx, const char *input)
Initialize this object based on a string that was passed to glTransformFeedbackVaryings.
bool assign_location (struct gl_context *ctx, struct gl_shader_program *prog)
Assign a location and stream ID for this tfeedback_decl object based on the transform feedback candidate found by find_candidate.
unsigned get_num_outputs () const
bool store (struct gl_context *ctx, struct gl_shader_program *prog, struct gl_transform_feedback_info *info, unsigned buffer, unsigned buffer_index, const unsigned max_outputs, bool *explicit_stride, bool has_xfb_qualifiers) const
Update gl_transform_feedback_info to reflect this tfeedback_decl.
const tfeedback_candidate * find_candidate (gl_shader_program *prog, hash_table *tfeedback_candidates)
bool is_next_buffer_separator () const
bool is_varying_written () const
bool is_varying () const
const char * name () const
unsigned get_stream_id () const
unsigned get_buffer () const
unsigned get_offset () const
unsigned num_components () const
The total number of varying components taken up by this variable.
unsigned get_location () const
Static Public Member Functions
static bool is_same (const tfeedback_decl &x, const tfeedback_decl &y)
Determine whether two tfeedback_decl objects refer to the same variable and array index (if applicable).
Detailed Description
Data structure tracking information about a transform feedback declaration during linking.
Member Function Documentation
assign_location()
bool tfeedback_decl::assign_location (struct gl_context * ctx, struct gl_shader_program * prog)
Assign a location and stream ID for this tfeedback_decl object based on the transform feedback candidate found by find_candidate.
If an error occurs, the error is reported through linker_error() and false is returned.
References is_varying(), linker_error(), tfeedback_candidate::offset, tfeedback_candidate::toplevel_var, and tfeedback_candidate::type.
Referenced by assign_varying_locations().
find_candidate()
const tfeedback_candidate * tfeedback_decl::find_candidate (gl_shader_program * prog, hash_table * tfeedback_candidates)
References linker_error(), and name().
Referenced by assign_varying_locations().
get_buffer()
unsigned tfeedback_decl::get_buffer () const inline
Referenced by cmp_xfb_offset(), and store_tfeedback_info().
get_location()
unsigned tfeedback_decl::get_location (void) const inline
References cross_validate_outputs_to_inputs(), link_varyings(), tfeedback_candidate::offset, and tfeedback_candidate::type.
get_num_outputs()
unsigned tfeedback_decl::get_num_outputs () const
References is_varying(), and num_components().
Referenced by store_tfeedback_info().
get_offset()
unsigned tfeedback_decl::get_offset () const inline
References tfeedback_candidate::offset.
Referenced by cmp_xfb_offset().
get_stream_id()
unsigned tfeedback_decl::get_stream_id () const inline
Referenced by store_tfeedback_info().
init()
void tfeedback_decl::init (struct gl_context * ctx, const void * mem_ctx, const char * input)
Initialize this object based on a string that was passed to glTransformFeedbackVaryings.
If the input is mal-formed, this call still succeeds, but it sets this->var_name to a mal-formed input, so tfeedback_decl::find_output_var() will fail to find any matching variable.
References parse_program_resource_name().
Referenced by parse_tfeedback_decls().
is_next_buffer_separator()
bool tfeedback_decl::is_next_buffer_separator () const inline
Referenced by store_tfeedback_info().
is_same()
bool tfeedback_decl::is_same (const tfeedback_decl & x, const tfeedback_decl & y) static
Determine whether two tfeedback_decl objects refer to the same variable and array index (if applicable).
References is_varying().
Referenced by parse_tfeedback_decls().
is_varying()
bool tfeedback_decl::is_varying () const inline
Referenced by assign_location(), assign_varying_locations(), get_num_outputs(), is_same(), parse_tfeedback_decls(), and store_tfeedback_info().
is_varying_written()
bool tfeedback_decl::is_varying_written () const inline
Referenced by store(), and store_tfeedback_info().
name()
const char* tfeedback_decl::name () const inline
Referenced by find_candidate(), tfeedback_candidate_generator::process(), and store_tfeedback_info().
num_components()
unsigned tfeedback_decl::num_components () const inline
The total number of varying components taken up by this variable.
Only valid if assign_location() has been called.
Referenced by get_num_outputs(), store(), and store_tfeedback_info().
store()
bool tfeedback_decl::store (struct gl_context * ctx, struct gl_shader_program * prog, struct gl_transform_feedback_info * info, unsigned buffer, unsigned buffer_index, const unsigned max_outputs, bool * explicit_stride, bool has_xfb_qualifiers) const
Update gl_transform_feedback_info to reflect this tfeedback_decl.
If an error occurs, the error is reported through linker_error() and false is returned.
References is_varying_written(), linker_error(), and num_components().
Referenced by store_tfeedback_info().
The documentation for this class was generated from the following files:
link_varyings.h
link_varyings.cpp