Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_array_refcount_visitor Class Reference
#include <ir_array_refcount.h>
Public Member Functions
ir_array_refcount_visitor (void)
~ir_array_refcount_visitor (void)
virtual ir_visitor_status visit (ir_dereference_variable *)
virtual ir_visitor_status visit_enter (ir_function_signature *)
virtual ir_visitor_status visit_enter (ir_dereference_array *)
ir_array_refcount_entry * get_variable_entry (ir_variable *var)
Find variable in the hash table, and insert it if not present.
Data Fields
struct hash_table * ht
Hash table mapping ir_variable to ir_array_refcount_entry.
void * mem_ctx
Constructor & Destructor Documentation
ir_array_refcount_visitor()
ir_array_refcount_visitor::ir_array_refcount_visitor (void)
References ht, and mem_ctx.
~ir_array_refcount_visitor()
ir_array_refcount_visitor::~ir_array_refcount_visitor (void)
References free_entry(), ht, and mem_ctx.
Member Function Documentation
get_variable_entry()
ir_array_refcount_entry * ir_array_refcount_visitor::get_variable_entry (ir_variable * var)
Find variable in the hash table, and insert it if not present.
References ir_array_refcount_entry::ir_array_refcount_entry().
Referenced by link_update_uniform_buffer_variables(), and variable_is_referenced().
visit()
ir_visitor_status ir_array_refcount_visitor::visit (ir_dereference_variable * ir) virtual
References ir_array_refcount_entry::is_referenced, ir_array_refcount_entry::var, and visit_continue.
visit_enter() [1/2]
ir_visitor_status ir_array_refcount_visitor::visit_enter (ir_function_signature * ir) virtual
References visit_continue_with_parent, and visit_list_elements().
visit_enter() [2/2]
ir_visitor_status ir_array_refcount_visitor::visit_enter (ir_dereference_array * ir) virtual
References array_deref_range::index, ir_array_refcount_entry::mark_array_elements_referenced(), array_deref_range::size, visit_continue, and visit_stop.
Field Documentation
ht
struct hash_table* ir_array_refcount_visitor::ht
Hash table mapping ir_variable to ir_array_refcount_entry.
Referenced by ir_array_refcount_visitor(), and ~ir_array_refcount_visitor().
mem_ctx
void* ir_array_refcount_visitor::mem_ctx
Referenced by ir_array_refcount_visitor(), and ~ir_array_refcount_visitor().
The documentation for this class was generated from the following files:
ir_array_refcount.h
ir_array_refcount.cpp