Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
parcel_out_uniform_storage Class Reference
Class to help parcel out pieces of backing storage to uniforms.
Public Member Functions
parcel_out_uniform_storage (struct gl_shader_program *prog, struct string_to_uint_map *map, struct gl_uniform_storage *uniforms, union gl_constant_value *values)
void start_shader (gl_shader_stage shader_type)
void set_and_process (ir_variable *var)
Public Member Functions inherited from program_resource_visitor
void process (ir_variable *var)
Begin processing a variable.
void process (const glsl_type *type, const char *name)
Begin processing a variable of a structured type.
Data Fields
int buffer_block_index
int ubo_byte_offset
gl_shader_stage shader_type
union gl_constant_value * values
gl_texture_index targets [MAX_SAMPLERS]
unsigned shader_samplers_used
Mask of samplers used by the current shader stage.
unsigned shader_shadow_samplers
Mask of samplers used by the current shader stage for shadows.
Additional Inherited Members
Protected Member Functions inherited from program_resource_visitor
virtual void visit_field (const glsl_struct_field *field)
Visit a record before visiting its fields.
Detailed Description
Class to help parcel out pieces of backing storage to uniforms.
Each uniform processed has some range of the gl_constant_value structures associated with it. The association is done by finding the uniform in the string_to_uint_map and using the value from the map to connect that slot in the gl_uniform_storage table with the next available slot in the gl_constant_value array.
Warning
This class assumes that every uniform that will be processed is already in the string_to_uint_map. In addition, it assumes that the gl_uniform_storage and gl_constant_value arrays are "big enough."
Constructor & Destructor Documentation
parcel_out_uniform_storage()
parcel_out_uniform_storage::parcel_out_uniform_storage (struct gl_shader_program * prog, struct string_to_uint_map * map, struct gl_uniform_storage * uniforms, union gl_constant_value * values) inline
Member Function Documentation
set_and_process()
void parcel_out_uniform_storage::set_and_process (ir_variable * var) inline
References program_resource_visitor::process().
Referenced by link_assign_uniform_storage().
start_shader()
void parcel_out_uniform_storage::start_shader (gl_shader_stage shader_type) inline
Referenced by link_assign_uniform_storage().
Field Documentation
buffer_block_index
int parcel_out_uniform_storage::buffer_block_index
shader_samplers_used
unsigned parcel_out_uniform_storage::shader_samplers_used
Mask of samplers used by the current shader stage.
Referenced by link_assign_uniform_storage().
shader_shadow_samplers
unsigned parcel_out_uniform_storage::shader_shadow_samplers
Mask of samplers used by the current shader stage for shadows.
Referenced by link_assign_uniform_storage().
shader_type
gl_shader_stage parcel_out_uniform_storage::shader_type
targets
gl_texture_index parcel_out_uniform_storage::targets[MAX_SAMPLERS]
Referenced by link_assign_uniform_storage().
ubo_byte_offset
int parcel_out_uniform_storage::ubo_byte_offset
values
union gl_constant_value* parcel_out_uniform_storage::values
Referenced by link_assign_uniform_storage().
The documentation for this class was generated from the following file:
link_uniforms.cpp