Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_expression Class Reference
Abstract syntax tree node definitions
Representation of any sort of expression.
#include <ast.h>
Public Member Functions
ast_expression (int oper, ast_expression *, ast_expression *, ast_expression *)
ast_expression (const char *identifier)
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
virtual void hir_no_rvalue (exec_list *instructions, struct _mesa_glsl_parse_state *state)
virtual bool has_sequence_subexpression () const
ir_rvalue * do_hir (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool needs_rvalue)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
void set_is_lhs (bool new_value)
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
Static Public Member Functions
static const char * operator_string (enum ast_operators op)
Data Fields
enum ast_operators oper
ast_expression * subexpressions [3]
union {
const char * identifier
int int_constant
float float_constant
unsigned uint_constant
int bool_constant
double double_constant
uint64_t uint64_constant
int64_t int64_constant
} primary_expression
exec_list expressions
List of expressions for an ast_sequence or parameters for an ast_function_call.
const char * non_lvalue_description
For things that can't be l-values, this describes what it is.
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Additional Inherited Members
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Detailed Description
Representation of any sort of expression.
Constructor & Destructor Documentation
ast_expression() [1/2]
ast_expression::ast_expression (int oper, ast_expression * ex0, ast_expression * ex1, ast_expression * ex2)
References non_lvalue_description, and subexpressions.
ast_expression() [2/2]
ast_expression::ast_expression (const char * identifier) inline
References ast_node::has_sequence_subexpression(), ast_node::hir(), and ast_node::print().
Member Function Documentation
do_hir()
ir_rvalue * ast_expression::do_hir (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool needs_rvalue)
References _mesa_ast_array_index_to_hir(), _mesa_ast_field_selection_to_hir(), _mesa_glsl_error(), _mesa_glsl_warning(), apply_implicit_conversion(), arithmetic_result_type(), ast_add, ast_add_assign, ast_and_assign, ast_array_index, ast_assign, ast_bit_and, ast_bit_not, ast_bit_or, ast_bit_xor, ast_bool_constant, ast_conditional, ast_div, ast_div_assign, ast_double_constant, ast_equal, ast_field_selection, ast_float_constant, ast_function_call, ast_gequal, ast_greater, ast_identifier, ast_int64_constant, ast_int_constant, ast_lequal, ast_less, ast_logic_and, ast_logic_not, ast_logic_or, ast_logic_xor, ast_ls_assign, ast_lshift, ast_mod, ast_mod_assign, ast_mul, ast_mul_assign, ast_neg, ast_nequal, AST_NUM_OPERATORS, ast_or_assign, ast_plus, ast_post_dec, ast_post_inc, ast_pre_dec, ast_pre_inc, ast_rs_assign, ast_rshift, ast_sequence, ast_sub, ast_sub_assign, ast_uint64_constant, ast_uint_constant, ast_unsized_array_dim, ast_xor_assign, bit_logic_result_type(), constant_one_for_inc_dec(), do_assignment(), do_comparison(), foreach_list_typed, get_lvalue_copy(), get_scalar_boolean_operand(), mark_whole_array_access(), modulus_result_type(), relational_result_type(), shift_result_type(), and unary_arithmetic_result_type().
has_sequence_subexpression()
bool ast_expression::has_sequence_subexpression () const virtual
Reimplemented from ast_node.
Reimplemented in ast_function_expression.
References ast_add, ast_add_assign, ast_and_assign, ast_array_index, ast_assign, ast_bit_and, ast_bit_not, ast_bit_or, ast_bit_xor, ast_bool_constant, ast_conditional, ast_div, ast_div_assign, ast_double_constant, ast_equal, ast_field_selection, ast_float_constant, ast_function_call, ast_gequal, ast_greater, ast_identifier, ast_int64_constant, ast_int_constant, ast_lequal, ast_less, ast_logic_and, ast_logic_not, ast_logic_or, ast_logic_xor, ast_ls_assign, ast_lshift, ast_mod, ast_mod_assign, ast_mul, ast_mul_assign, ast_neg, ast_nequal, ast_or_assign, ast_plus, ast_post_dec, ast_post_inc, ast_pre_dec, ast_pre_inc, ast_rs_assign, ast_rshift, ast_sequence, ast_sub, ast_sub_assign, ast_uint64_constant, ast_uint_constant, ast_unsized_array_dim, and ast_xor_assign.
Referenced by process_initializer().
hir()
ir_rvalue * ast_expression::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
Reimplemented in ast_aggregate_initializer, and ast_function_expression.
Referenced by _mesa_ast_field_selection_to_hir(), generate_array_index(), get_scalar_boolean_operand(), process_initializer(), process_qualifier_constant(), and process_record_constructor().
hir_no_rvalue()
void ast_expression::hir_no_rvalue (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Reimplemented in ast_aggregate_initializer, and ast_function_expression.
operator_string()
const char * ast_expression::operator_string (enum ast_operators op) static
Referenced by bit_logic_result_type(), get_scalar_boolean_operand(), ast_expression_bin::print(), and shift_result_type().
print()
void ast_expression::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
Reimplemented in ast_expression_bin.
References ast_add_assign, ast_and_assign, ast_array_index, ast_assign, ast_bit_not, ast_bool_constant, ast_conditional, ast_div_assign, ast_double_constant, ast_field_selection, ast_float_constant, ast_function_call, ast_identifier, ast_int64_constant, ast_int_constant, ast_logic_not, ast_ls_assign, ast_mod_assign, ast_mul_assign, ast_neg, ast_or_assign, ast_plus, ast_post_dec, ast_post_inc, ast_pre_dec, ast_pre_inc, ast_rs_assign, ast_sequence, ast_sub_assign, ast_uint64_constant, ast_uint_constant, ast_xor_assign, and foreach_list_typed.
Referenced by ast_expression_bin::print().
set_is_lhs()
void ast_expression::set_is_lhs (bool new_value) virtual
Reimplemented from ast_node.
Referenced by process_record_constructor().
Field Documentation
bool_constant
int ast_expression::bool_constant
double_constant
double ast_expression::double_constant
expressions
exec_list ast_expression::expressions
List of expressions for an ast_sequence or parameters for an ast_function_call.
Referenced by _mesa_ast_set_aggregate_type(), ast_function_expression::has_sequence_subexpression(), ast_function_expression::hir(), ast_aggregate_initializer::hir(), and process_record_constructor().
float_constant
float ast_expression::float_constant
identifier
const char* ast_expression::identifier
Referenced by _mesa_ast_field_selection_to_hir(), generate_array_index(), and process_record_constructor().
int64_constant
int64_t ast_expression::int64_constant
int_constant
int ast_expression::int_constant
non_lvalue_description
const char* ast_expression::non_lvalue_description
For things that can't be l-values, this describes what it is.
This text is used by the code that generates IR for assignments to detect and emit useful messages for assignments to some things that can't be l-values. For example, pre- or post-incerement expressions.
Note
This pointer may be NULL.
Referenced by ast_expression(), and verify_parameter_modes().
oper
enum ast_operators ast_expression::oper
Referenced by _mesa_ast_set_aggregate_type(), generate_array_index(), get_scalar_boolean_operand(), ast_function_expression::hir(), ast_expression_bin::print(), and process_initializer().
primary_expression
union { ... } ast_expression::primary_expression
Referenced by _mesa_ast_field_selection_to_hir(), generate_array_index(), and process_record_constructor().
subexpressions
ast_expression* ast_expression::subexpressions[3]
Referenced by _mesa_ast_field_selection_to_hir(), ast_expression(), generate_array_index(), get_scalar_boolean_operand(), ast_function_expression::hir(), ast_expression_bin::print(), and process_record_constructor().
uint64_constant
uint64_t ast_expression::uint64_constant
uint_constant
unsigned ast_expression::uint_constant
The documentation for this class was generated from the following files:
ast.h
ast_expr.cpp
ast_to_hir.cpp
glsl_parser_extras.cpp