Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_builder::ir_factory Class Reference
#include <ir_builder.h>
Public Member Functions
ir_factory (exec_list *instructions=NULL, void *mem_ctx=NULL)
void emit (ir_instruction *ir)
ir_variable * make_temp (const glsl_type *type, const char *name)
ir_constant * constant (float f)
ir_constant * constant (int i)
ir_constant * constant (unsigned u)
ir_constant * constant (bool b)
Data Fields
exec_list * instructions
void * mem_ctx
Constructor & Destructor Documentation
ir_factory()
ir_builder::ir_factory::ir_factory (exec_list * instructions = NULL, void * mem_ctx = NULL) inline
Member Function Documentation
constant() [1/4]
ir_constant* ir_builder::ir_factory::constant (float f) inline
constant() [2/4]
ir_constant* ir_builder::ir_factory::constant (int i) inline
constant() [3/4]
ir_constant* ir_builder::ir_factory::constant (unsigned u) inline
constant() [4/4]
ir_constant* ir_builder::ir_factory::constant (bool b) inline
emit()
void ir_builder::ir_factory::emit (ir_instruction * ir)
References instructions.
Referenced by calc_blend_result(), lower_64bit::compact_destination(), lower_64bit::expand_source(), get_image_available_predicate(), lower_blend_equation_advanced(), lower_64bit::lower_op_to_function_call(), make_temp(), set_lum(), and set_lum_sat().
make_temp()
ir_variable * ir_builder::ir_factory::make_temp (const glsl_type * type, const char * name)
References emit(), and mem_ctx.
Referenced by calc_blend_result(), lower_64bit::compact_destination(), lower_64bit::expand_source(), get_image_available_predicate(), lower_64bit::lower_op_to_function_call(), set_lum(), and set_lum_sat().
Field Documentation
instructions
exec_list* ir_builder::ir_factory::instructions
Referenced by calc_blend_result(), and emit().
mem_ctx
void* ir_builder::ir_factory::mem_ctx
Referenced by ir_builder::assign(), ir_builder::bitfield_insert(), calc_blend_result(), ir_builder::expr(), ir_builder::if_tree(), make_temp(), ir_builder::ret(), set_lum(), set_lum_sat(), ir_builder::swizzle(), and ir_builder::swizzle_for_size().
The documentation for this class was generated from the following files:
ir_builder.h
ir_builder.cpp