Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_node Class Reference
Abstract syntax tree node definitions
Base class of all abstract syntax tree nodes.
#include <ast.h>
Public Member Functions
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Data Fields
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Protected Member Functions
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Detailed Description
Base class of all abstract syntax tree nodes.
Constructor & Destructor Documentation
ast_node()
ast_node::ast_node (void) protected
The only constructor is protected so that only derived class objects can be created.
References first_column, first_line, last_column, last_line, ast_type_qualifier::location, and source.
Member Function Documentation
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS()
ast_node::DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
get_location()
struct YYLTYPE ast_node::get_location (void) const inline
Retrieve the source location of an AST node.
This function is primarily used to get the source position of an AST node into a form that can be passed to _mesa_glsl_error.
See also
_mesa_glsl_error, ast_node::set_location
References location.
Referenced by _mesa_ast_field_selection_to_hir(), generate_array_index(), get_scalar_boolean_operand(), ast_function_expression::hir(), ast_aggregate_initializer::hir(), ast_case_label::hir(), ast_parameter_declarator::parameters_to_hir(), process_array_size(), process_initializer(), ast_layout_expression::process_qualifier_constant(), process_record_constructor(), and verify_parameter_modes().
has_sequence_subexpression()
bool ast_node::has_sequence_subexpression () const virtual
Reimplemented in ast_function_expression, and ast_expression.
Referenced by ast_expression::ast_expression(), ast_function_expression::is_constructor(), and process_array_size().
hir()
ir_rvalue * ast_node::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented in ast_cs_input_layout, ast_gs_input_layout, ast_tcs_output_layout, ast_interface_block, ast_function_definition, ast_jump_statement, ast_iteration_statement, ast_switch_statement, ast_selection_statement, ast_switch_body, ast_case_statement_list, ast_case_statement, ast_case_label_list, ast_case_label, ast_expression_statement, ast_function, ast_parameter_declarator, ast_declarator_list, ast_type_specifier, ast_struct_specifier, ast_compound_statement, ast_aggregate_initializer, ast_function_expression, and ast_expression.
Referenced by ast_cs_input_layout::ast_cs_input_layout(), ast_expression::ast_expression(), ast_function_definition::ast_function_definition(), ast_gs_input_layout::ast_gs_input_layout(), ast_interface_block::ast_interface_block(), ast_parameter_declarator::ast_parameter_declarator(), ast_tcs_output_layout::ast_tcs_output_layout(), ast_type_specifier::ast_type_specifier(), ast_function_expression::is_constructor(), process_array_size(), and ast_layout_expression::process_qualifier_constant().
print()
void ast_node::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented in ast_function_definition, ast_jump_statement, ast_iteration_statement, ast_switch_statement, ast_selection_statement, ast_switch_body, ast_case_statement_list, ast_case_statement, ast_case_label_list, ast_case_label, ast_expression_statement, ast_function, ast_parameter_declarator, ast_declarator_list, ast_fully_specified_type, ast_type_specifier, ast_struct_specifier, ast_declaration, ast_compound_statement, ast_array_specifier, ast_subroutine_list, ast_expression_bin, and ast_expression.
Referenced by ast_expression::ast_expression(), ast_function_definition::ast_function_definition(), ast_parameter_declarator::ast_parameter_declarator(), ast_type_specifier::ast_type_specifier(), and ast_array_specifier::is_single_dimension().
set_is_lhs()
void ast_node::set_is_lhs (bool) virtual
Reimplemented in ast_expression.
set_location()
void ast_node::set_location (const struct YYLTYPE & locp) inline
Set the source location of an AST node from a parser location.
See also
ast_node::get_location
References location.
Referenced by ast_array_specifier::ast_array_specifier(), ast_cs_input_layout::ast_cs_input_layout(), ast_gs_input_layout::ast_gs_input_layout(), ast_layout_expression::ast_layout_expression(), and ast_tcs_output_layout::ast_tcs_output_layout().
set_location_range()
void ast_node::set_location_range (const struct YYLTYPE & begin, const struct YYLTYPE & end) inline
Set the source location range of an AST node using two location nodes.
See also
ast_node::set_location
References location.
Field Documentation
first_column
unsigned ast_node::first_column
First column in the first line.
Referenced by ast_node().
first_line
unsigned ast_node::first_line
First line number within the source string.
Referenced by ast_node().
last_column
unsigned ast_node::last_column
Last column in the last line.
Referenced by ast_node().
last_line
unsigned ast_node::last_line
Last line number within the source string.
Referenced by ast_node().
link
exec_node ast_node::link
Referenced by _mesa_glsl_compile_shader(), ast_array_specifier::add_dimension(), ast_array_specifier::ast_array_specifier(), ast_compound_statement::ast_compound_statement(), ast_layout_expression::ast_layout_expression(), ast_struct_specifier::ast_struct_specifier(), ast_function_expression::has_sequence_subexpression(), ast_function_expression::hir(), ast_subroutine_list::print(), ast_array_specifier::print(), ast_struct_specifier::print(), ast_declarator_list::print(), ast_function::print(), ast_case_label_list::print(), ast_case_statement::print(), ast_case_statement_list::print(), and ast_layout_expression::process_qualifier_constant().
location
struct { ... } ast_node::location
Source location of the AST node.
Referenced by get_location(), ast_type_qualifier::merge_qualifier(), set_location(), and set_location_range().
source
unsigned ast_node::source
GLSL source number.
Referenced by _mesa_glsl_compile_shader(), and ast_node().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp