Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_parameter_declarator Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_parameter_declarator ()
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Static Public Member Functions
static void parameters_to_hir (exec_list *ast_parameters, bool formal, exec_list *ir_parameters, struct _mesa_glsl_parse_state *state)
Data Fields
ast_fully_specified_type * type
const char * identifier
ast_array_specifier * array_specifier
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Additional Inherited Members
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_parameter_declarator()
ast_parameter_declarator::ast_parameter_declarator () inline
References ast_node::hir(), and ast_node::print().
Member Function Documentation
hir()
ir_rvalue * ast_parameter_declarator::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), apply_type_qualifier_to_variable(), and process_array_type().
parameters_to_hir()
void ast_parameter_declarator::parameters_to_hir (exec_list * ast_parameters, bool formal, exec_list * ir_parameters, struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error(), foreach_list_typed, and ast_node::get_location().
Referenced by ast_function::hir().
print()
void ast_parameter_declarator::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References ast_opt_array_dimensions_print(), and ast_function::identifier.
Field Documentation
array_specifier
ast_array_specifier* ast_parameter_declarator::array_specifier
identifier
const char* ast_parameter_declarator::identifier
type
ast_fully_specified_type* ast_parameter_declarator::type
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp