Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_jump_statement Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Types
enum ast_jump_modes { ast_continue, ast_break, ast_return, ast_discard }
Public Member Functions
ast_jump_statement (int mode, ast_expression *return_value)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Data Fields
enum ast_jump_statement::ast_jump_modes mode
ast_expression * opt_return_value
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Additional Inherited Members
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Member Enumeration Documentation
ast_jump_modes
enum ast_jump_statement::ast_jump_modes
Enumerator
ast_continue
ast_break
ast_return
ast_discard
Constructor & Destructor Documentation
ast_jump_statement()
ast_jump_statement::ast_jump_statement (int mode, ast_expression * return_value)
References ast_return, and opt_return_value.
Member Function Documentation
hir()
ir_rvalue * ast_jump_statement::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), apply_implicit_conversion(), ast_iteration_statement::ast_do_while, and ir_builder::ret().
print()
void ast_jump_statement::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
Field Documentation
mode
enum ast_jump_statement::ast_jump_modes ast_jump_statement::mode
Referenced by ast_iteration_statement::print().
opt_return_value
ast_expression* ast_jump_statement::opt_return_value
Referenced by ast_jump_statement().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp