Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_expression Class Reference abstract
#include <s_expression.h>
Public Member Functions
virtual void print ()=0
Print out an S-Expression.
virtual bool is_list () const
virtual bool is_symbol () const
virtual bool is_number () const
virtual bool is_int () const
Static Public Member Functions
static s_expression * read_expression (void *ctx, const char *&src)
Read an S-Expression from the given string.
Protected Member Functions
s_expression ()
Additional Inherited Members
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Constructor & Destructor Documentation
s_expression()
s_expression::s_expression () inline protected
Member Function Documentation
is_int()
virtual bool s_expression::is_int () const inline virtual
Reimplemented in s_int.
Referenced by s_pattern::match().
is_list()
virtual bool s_expression::is_list () const inline virtual
Reimplemented in s_list.
Referenced by s_pattern::match().
is_number()
virtual bool s_expression::is_number () const inline virtual
Reimplemented in s_number.
Referenced by s_pattern::match().
is_symbol()
virtual bool s_expression::is_symbol () const inline virtual
Reimplemented in s_symbol.
Referenced by s_pattern::match().
print()
virtual void s_expression::print () pure virtual
Print out an S-Expression.
Useful for debugging.
Implemented in s_list, s_symbol, s_float, and s_int.
Referenced by _mesa_glsl_read_ir(), s_float::fvalue(), s_list::is_list(), s_int::value(), and s_symbol::value().
read_expression()
s_expression * s_expression::read_expression (void * ctx, const char *& src) static
Read an S-Expression from the given string.
Advances the supplied pointer to just after the expression read.
Any allocation will be performed with 'ctx' as the ralloc owner.
References __read_expression().
Referenced by _mesa_glsl_read_ir().
The documentation for this class was generated from the following files:
s_expression.h
s_expression.cpp