Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_interface_block Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_interface_block (const char *instance_name, ast_array_specifier *array_specifier)
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Data Fields
ast_type_qualifier default_layout
ast_type_qualifier layout
const char * block_name
const char * instance_name
Declared name of the block instance, if specified.
exec_list declarations
List of ast_declarator_list *.
ast_array_specifier * array_specifier
Declared array size of the block instance.
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Additional Inherited Members
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_interface_block()
ast_interface_block::ast_interface_block (const char * instance_name, ast_array_specifier * array_specifier) inline
References ast_node::hir().
Member Function Documentation
hir()
ir_rvalue * ast_interface_block::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), apply_explicit_binding(), apply_memory_qualifiers(), ast_process_struct_or_iface_block_members(), check_builtin_array_max_size(), ast_type_qualifier::flags, foreach_in_list_safe, get_variable_being_redeclared(), handle_geometry_shader_input_decl(), handle_tess_ctrl_shader_output_decl(), handle_tess_shader_input_decl(), ast_type_qualifier::i, is_unsized_array_last_element(), process_array_type(), process_qualifier_constant(), ast_type_qualifier::q, select_gles_precision(), interface_block_usage_visitor::usage_found(), validate_identifier(), validate_stream_qualifier(), validate_xfb_buffer_qualifier(), and validate_xfb_offset_qualifier().
Field Documentation
array_specifier
ast_array_specifier* ast_interface_block::array_specifier
Declared array size of the block instance.
If the block is not declared as an array or if the block instance array is unsized, this field will be NULL.
block_name
const char* ast_interface_block::block_name
declarations
exec_list ast_interface_block::declarations
List of ast_declarator_list *.
Referenced by _mesa_ast_process_interface_block().
default_layout
ast_type_qualifier ast_interface_block::default_layout
Referenced by _mesa_ast_process_interface_block().
instance_name
const char* ast_interface_block::instance_name
Declared name of the block instance, if specified.
If the block does not have an instance name, this field will be NULL.
Referenced by _mesa_ast_process_interface_block().
layout
ast_type_qualifier ast_interface_block::layout
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp