Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
loop_variable Class Reference
#include <loop_analysis.h>
Public Member Functions
bool is_induction_var () const
bool is_loop_constant () const
void record_reference (bool in_assignee, bool in_conditional_code_or_nested_loop, ir_assignment *current_assignment)
Record the fact that the given loop variable was referenced inside the loop.
Data Fields
ir_variable * var
The variable in question.
bool read_before_write
Is the variable read in the loop before it is written?
bool rhs_clean
Are all variables in the RHS of the assignment loop constants?
bool conditional_or_nested_assignment
Is there an assignment to the variable that is conditional, or inside a nested loop?
ir_assignment * first_assignment
Reference to the first assignment to the variable in the loop body.
unsigned num_assignments
Number of assignments to the variable in the loop body.
ir_rvalue * increment
Increment value for a loop induction variable.
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Member Function Documentation
is_induction_var()
bool loop_variable::is_induction_var () const inline
Referenced by loop_variable_state::get_or_insert(), and loop_unroll_count::visit_enter().
is_loop_constant()
bool loop_variable::is_loop_constant () const inline
Referenced by get_basic_induction_increment(), and examine_rhs::visit().
record_reference()
void loop_variable::record_reference (bool in_assignee, bool in_conditional_code_or_nested_loop, ir_assignment * current_assignment)
Record the fact that the given loop variable was referenced inside the loop.
in_assignee is true if the reference was on the LHS of an assignment.
in_conditional_code_or_nested_loop is true if the reference occurred inside an if statement or a nested loop.
current_assignment is the ir_assignment node that the loop variable is on the LHS of, if any (ignored if in_assignee is false).
References conditional_or_nested_assignment, first_assignment, num_assignments, and read_before_write.
Referenced by loop_variable_state::get_or_insert().
Field Documentation
conditional_or_nested_assignment
bool loop_variable::conditional_or_nested_assignment
Is there an assignment to the variable that is conditional, or inside a nested loop?
Referenced by record_reference().
first_assignment
ir_assignment* loop_variable::first_assignment
Reference to the first assignment to the variable in the loop body.
Referenced by record_reference().
increment
ir_rvalue* loop_variable::increment
Increment value for a loop induction variable.
If this is a loop induction variable, the amount by which the variable is incremented on each iteration through the loop.
If this is not a loop induction variable, NULL.
Referenced by loop_variable_state::get_or_insert().
num_assignments
unsigned loop_variable::num_assignments
Number of assignments to the variable in the loop body.
Referenced by record_reference().
read_before_write
bool loop_variable::read_before_write
Is the variable read in the loop before it is written?
Referenced by loop_variable_state::get_or_insert(), and record_reference().
rhs_clean
bool loop_variable::rhs_clean
Are all variables in the RHS of the assignment loop constants?
var
ir_variable* loop_variable::var
The variable in question.
Referenced by get_basic_induction_increment(), loop_variable_state::get_or_insert(), and loop_variable_state::insert().
The documentation for this class was generated from the following files:
loop_analysis.h
loop_analysis.cpp