Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_pattern Class Reference
Part of a pattern to match - essentially a record holding a pointer to the storage for the component to match, along with the appropriate type.
#include <s_expression.h>
Public Member Functions
s_pattern (s_expression *&s)
s_pattern (s_list *&s)
s_pattern (s_symbol *&s)
s_pattern (s_number *&s)
s_pattern (s_int *&s)
s_pattern (const char *str)
bool match (s_expression *expr)
Detailed Description
Part of a pattern to match - essentially a record holding a pointer to the storage for the component to match, along with the appropriate type.
Constructor & Destructor Documentation
s_pattern() [1/6]
s_pattern::s_pattern (s_expression *& s) inline
s_pattern() [2/6]
s_pattern::s_pattern (s_list *& s) inline
s_pattern() [3/6]
s_pattern::s_pattern (s_symbol *& s) inline
s_pattern() [4/6]
s_pattern::s_pattern (s_number *& s) inline
s_pattern() [5/6]
s_pattern::s_pattern (s_int *& s) inline
s_pattern() [6/6]
s_pattern::s_pattern (const char * str) inline
References ir_builder::expr().
Member Function Documentation
match()
bool s_pattern::match (s_expression * expr)
References ir_builder::expr(), s_expression::is_int(), s_expression::is_list(), s_expression::is_number(), s_expression::is_symbol(), SX_AS_SYMBOL, and s_symbol::value().
Field Documentation
literal
const char* s_pattern::literal
p_expr
s_expression** s_pattern::p_expr
p_int
s_int** s_pattern::p_int
p_list
s_list** s_pattern::p_list
p_number
s_number** s_pattern::p_number
p_symbol
s_symbol** s_pattern::p_symbol
The documentation for this class was generated from the following files:
s_expression.h
s_expression.cpp