Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_function_expression Class Reference
Abstract syntax tree node definitions
Subclass of expressions for function calls.
#include <ast.h>
Public Member Functions
ast_function_expression (ast_expression *callee)
ast_function_expression (class ast_type_specifier *type)
bool is_constructor () const
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
virtual void hir_no_rvalue (exec_list *instructions, struct _mesa_glsl_parse_state *state)
virtual bool has_sequence_subexpression () const
Public Member Functions inherited from ast_expression
ast_expression (int oper, ast_expression *, ast_expression *, ast_expression *)
ast_expression (const char *identifier)
ir_rvalue * do_hir (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool needs_rvalue)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
void set_is_lhs (bool new_value)
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
Additional Inherited Members
Static Public Member Functions inherited from ast_expression
static const char * operator_string (enum ast_operators op)
Data Fields inherited from ast_expression
enum ast_operators oper
ast_expression * subexpressions [3]
union {
const char * identifier
int int_constant
float float_constant
unsigned uint_constant
int bool_constant
double double_constant
uint64_t uint64_constant
int64_t int64_constant
} primary_expression
exec_list expressions
List of expressions for an ast_sequence or parameters for an ast_function_call.
const char * non_lvalue_description
For things that can't be l-values, this describes what it is.
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Detailed Description
Subclass of expressions for function calls.
Constructor & Destructor Documentation
ast_function_expression() [1/2]
ast_function_expression::ast_function_expression (ast_expression * callee) inline
ast_function_expression() [2/2]
ast_function_expression::ast_function_expression (class ast_type_specifier * type) inline
Member Function Documentation
has_sequence_subexpression()
bool ast_function_expression::has_sequence_subexpression () const virtual
Reimplemented from ast_expression.
References ast_expression::expressions, foreach_list_typed, and ast_node::link.
hir()
ir_rvalue * ast_function_expression::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_expression.
References _mesa_glsl_error(), ast_array_index, ast_field_selection, ast_identifier, convert_component(), dereference_component(), emit_inline_matrix_constructor(), emit_inline_vector_constructor(), ast_expression::expressions, foreach_in_list_safe, foreach_list_typed, generate_array_index(), generate_call(), ast_node::get_location(), ast_type_specifier::glsl_type(), is_constructor(), ast_node::link, match_function_by_name(), match_subroutine_by_name(), no_matching_function_error(), ast_expression::oper, process_array_constructor(), process_parameters(), process_record_constructor(), ast_expression::subexpressions, ast_type_specifier::type_name, and verify_parameter_modes().
hir_no_rvalue()
void ast_function_expression::hir_no_rvalue (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Reimplemented from ast_expression.
is_constructor()
bool ast_function_expression::is_constructor () const inline
References ast_node::has_sequence_subexpression(), and ast_node::hir().
Referenced by hir().
The documentation for this class was generated from the following files:
ast.h
ast_function.cpp
ast_to_hir.cpp