Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_cs_input_layout Class Reference
Abstract syntax tree node definitions
AST node representing a decalaration of the input layout for compute shaders.
#include <ast.h>
Public Member Functions
ast_cs_input_layout (const struct YYLTYPE &locp, ast_layout_expression *const *local_size)
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Additional Inherited Members
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Detailed Description
AST node representing a decalaration of the input layout for compute shaders.
Constructor & Destructor Documentation
ast_cs_input_layout()
ast_cs_input_layout::ast_cs_input_layout (const struct YYLTYPE & locp, ast_layout_expression *const * local_size) inline
References _mesa_ast_array_index_to_hir(), _mesa_ast_field_selection_to_hir(), _mesa_ast_process_interface_block(), _mesa_ast_set_aggregate_type(), _mesa_ast_to_hir(), check_builtin_array_max_size(), emit_function(), ir_builder::expr(), ast_node::hir(), process_qualifier_constant(), and ast_node::set_location().
Member Function Documentation
hir()
ir_rvalue * ast_cs_input_layout::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), and process_qualifier_constant().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp