Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_declarator_list Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_declarator_list (ast_fully_specified_type *)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Data Fields
ast_fully_specified_type * type
exec_list declarations
List of 'ast_declaration *'.
int invariant
Flags for redeclarations.
int precise
< invariant redeclaration
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Additional Inherited Members
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_declarator_list()
ast_declarator_list::ast_declarator_list (ast_fully_specified_type * type)
References ast_type_qualifier::invariant, and ast_type_qualifier::precise.
Member Function Documentation
hir()
ir_rvalue * ast_declarator_list::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), _mesa_glsl_warning(), apply_layout_qualifier_to_variable(), apply_type_qualifier_to_variable(), ast_precision_none, ast_type_qualifier::flags, foreach_list_typed, get_variable_being_redeclared(), handle_geometry_shader_input_decl(), handle_tess_ctrl_shader_output_decl(), handle_tess_shader_input_decl(), ast_type_qualifier::i, is_allowed_invariant(), precision_qualifier_allowed(), process_array_type(), process_initializer(), process_qualifier_constant(), ast_type_qualifier::q, validate_array_dimensions(), and validate_identifier().
print()
void ast_declarator_list::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References foreach_list_typed, ast_type_qualifier::invariant, and ast_node::link.
Field Documentation
declarations
exec_list ast_declarator_list::declarations
List of 'ast_declaration *'.
invariant
int ast_declarator_list::invariant
Flags for redeclarations.
In these cases, no type is specified, to type is allowed to be NULL. In all other cases, this would be an error.
precise
int ast_declarator_list::precise
< invariant redeclaration
type
ast_fully_specified_type* ast_declarator_list::type
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp