Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
loop_variable_state Class Reference
Tracking for all variables used in a loop.
#include <loop_analysis.h>
Public Member Functions
class loop_variable * get (const ir_variable *)
class loop_variable * insert (ir_variable *)
class loop_variable * get_or_insert (ir_variable *, bool in_assignee)
If the given variable already is recorded in the state for this loop, return the corresponding loop_variable object that records information about it.
class loop_terminator * insert (ir_if *)
loop_variable_state ()
~loop_variable_state ()
Data Fields
exec_list variables
Variables that have not yet been classified.
exec_list constants
Variables whose values are constant within the body of the loop.
exec_list induction_variables
Induction variables for this loop.
exec_list terminators
Simple if-statements that lead to the termination of the loop.
loop_terminator * limiting_terminator
If any of the terminators in terminators leads to termination of the loop after a constant number of iterations, this is the terminator that leads to termination after the smallest number of iterations.
hash_table * var_hash
Hash table containing all variables accessed in this loop.
unsigned num_loop_jumps
Number of ir_loop_jump instructions that operate on this loop.
bool contains_calls
Whether this loop contains any function calls.
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Detailed Description
Tracking for all variables used in a loop.
Constructor & Destructor Documentation
loop_variable_state()
loop_variable_state::loop_variable_state () inline
~loop_variable_state()
loop_variable_state::~loop_variable_state () inline
Member Function Documentation
get()
loop_variable * loop_variable_state::get (const ir_variable * ir)
Referenced by calculate_iterations(), get_or_insert(), and loop_unroll_count::visit_enter().
get_or_insert()
loop_variable * loop_variable_state::get_or_insert (ir_variable * var, bool in_assignee)
If the given variable already is recorded in the state for this loop, return the corresponding loop_variable object that records information about it.
Otherwise, create a new loop_variable object to record information about the variable, and set its read_before_write field appropriately based on in_assignee.
in_assignee is true if this variable was encountered on the LHS of an assignment.
References all_expression_operands_are_loop_constant(), calculate_iterations(), constants, contains_calls, find_initial_value(), foreach_in_list, foreach_in_list_safe, get(), get_basic_induction_increment(), loop_variable::increment, induction_variables, insert(), loop_state::insert(), loop_variable::is_induction_var(), is_loop_terminator(), loop_terminator::iterations, limiting_terminator, num_loop_jumps, loop_variable::read_before_write, loop_variable::record_reference(), terminators, loop_variable::var, var_hash, variables, visit_continue, and visit_continue_with_parent.
insert() [1/2]
loop_variable * loop_variable_state::insert (ir_variable * var)
References loop_variable::var.
Referenced by get_or_insert().
insert() [2/2]
loop_terminator * loop_variable_state::insert (ir_if * if_stmt)
References loop_terminator::ir.
Field Documentation
constants
exec_list loop_variable_state::constants
Variables whose values are constant within the body of the loop.
This list contains loop_variable objects.
Referenced by get_or_insert().
contains_calls
bool loop_variable_state::contains_calls
Whether this loop contains any function calls.
Referenced by get_or_insert().
induction_variables
exec_list loop_variable_state::induction_variables
Induction variables for this loop.
This list contains loop_variable objects.
Referenced by get_or_insert().
limiting_terminator
loop_terminator* loop_variable_state::limiting_terminator
If any of the terminators in terminators leads to termination of the loop after a constant number of iterations, this is the terminator that leads to termination after the smallest number of iterations.
Otherwise NULL.
Referenced by calculate_iterations(), get_or_insert(), and loop_unroll_count::visit_enter().
num_loop_jumps
unsigned loop_variable_state::num_loop_jumps
Number of ir_loop_jump instructions that operate on this loop.
Referenced by calculate_iterations(), get_or_insert(), and loop_unroll_count::visit_enter().
terminators
exec_list loop_variable_state::terminators
Simple if-statements that lead to the termination of the loop.
This list contains loop_terminator objects.
See also
is_loop_terminator
Referenced by calculate_iterations(), and get_or_insert().
var_hash
hash_table* loop_variable_state::var_hash
Hash table containing all variables accessed in this loop.
Referenced by get_or_insert().
variables
exec_list loop_variable_state::variables
Variables that have not yet been classified.
Referenced by get_or_insert().
The documentation for this class was generated from the following files:
loop_analysis.h
loop_analysis.cpp