Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_buffer_access::lower_buffer_access Class Reference abstract
#include <lower_buffer_access.h>
Public Member Functions
virtual void insert_buffer_access (void *mem_ctx, ir_dereference *deref, const glsl_type *type, ir_rvalue *offset, unsigned mask, int channel)=0
void emit_access (void *mem_ctx, bool is_write, ir_dereference *deref, ir_variable *base_offset, unsigned int deref_offset, bool row_major, int matrix_columns, unsigned int packing, unsigned int write_mask)
Takes a deref and recursively calls itself to break the deref down to the point that the reads or writes generated are contiguous scalars or vectors.
bool is_dereferenced_thing_row_major (const ir_rvalue *deref)
Determine if a thing being dereferenced is row-major.
void setup_buffer_access (void *mem_ctx, ir_rvalue *deref, ir_rvalue **offset, unsigned *const_offset, bool *row_major, int *matrix_columns, const glsl_struct_field **struct_field, enum glsl_interface_packing packing)
This function initializes various values that will be used later by emit_access when actually emitting loads or stores.
Public Member Functions inherited from ir_rvalue_enter_visitor
virtual ir_visitor_status visit_enter (ir_assignment *)
virtual ir_visitor_status visit_enter (ir_call *)
virtual ir_visitor_status visit_enter (ir_dereference_array *)
virtual ir_visitor_status visit_enter (ir_dereference_record *)
virtual ir_visitor_status visit_enter (ir_discard *)
virtual ir_visitor_status visit_enter (ir_expression *)
virtual ir_visitor_status visit_enter (ir_if *)
virtual ir_visitor_status visit_enter (ir_return *)
virtual ir_visitor_status visit_enter (ir_swizzle *)
virtual ir_visitor_status visit_enter (ir_texture *)
virtual ir_visitor_status visit_enter (ir_emit_vertex *)
virtual ir_visitor_status visit_enter (ir_end_primitive *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_discard *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
ir_visitor_status rvalue_visit (ir_emit_vertex *)
ir_visitor_status rvalue_visit (ir_end_primitive *)
virtual void handle_rvalue (ir_rvalue **rvalue)=0
Member Function Documentation
emit_access()
void lower_buffer_access::lower_buffer_access::emit_access (void * mem_ctx, bool is_write, ir_dereference * deref, ir_variable * base_offset, unsigned int deref_offset, bool row_major, int matrix_columns, unsigned int packing, unsigned int write_mask)
Takes a deref and recursively calls itself to break the deref down to the point that the reads or writes generated are contiguous scalars or vectors.
References ir_builder::add(), and lower_buffer_access::writemask_for_size().
insert_buffer_access()
virtual void lower_buffer_access::lower_buffer_access::insert_buffer_access (void * mem_ctx, ir_dereference * deref, const glsl_type * type, ir_rvalue * offset, unsigned mask, int channel) pure virtual
is_dereferenced_thing_row_major()
bool lower_buffer_access::lower_buffer_access::is_dereferenced_thing_row_major (const ir_rvalue * deref)
Determine if a thing being dereferenced is row-major.
There is some trickery here.
If the thing being dereferenced is a member of uniform block without an instance name, then the name of the ir_variable is the field name of an interface type. If this field is row-major, then the thing referenced is row-major.
If the thing being dereferenced is a member of uniform block with an instance name, then the last dereference in the tree will be an ir_dereference_record. If that record field is row-major, then the thing referenced is row-major.
setup_buffer_access()
void lower_buffer_access::lower_buffer_access::setup_buffer_access (void * mem_ctx, ir_rvalue * deref, ir_rvalue ** offset, unsigned * const_offset, bool * row_major, int * matrix_columns, const glsl_struct_field ** struct_field, enum glsl_interface_packing packing)
This function initializes various values that will be used later by emit_access when actually emitting loads or stores.
Note: const_offset is an input as well as an output, clients must initialize it to the offset of the variable in the underlying block, and this function will adjust it by adding the constant offset of the member being accessed into that variable.
References ir_builder::add(), ir_builder::i2u(), and ir_builder::mul().
The documentation for this class was generated from the following files:
lower_buffer_access.h
lower_buffer_access.cpp