Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ast_type_specifier Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_type_specifier (const char *name)
Construct a type specifier from a type name.
ast_type_specifier (ast_struct_specifier *s)
Construct a type specifier from a structure definition.
const struct glsl_type * glsl_type (const char **name, struct _mesa_glsl_parse_state *state) const
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
ir_rvalue * hir (exec_list *, struct _mesa_glsl_parse_state *)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
DECLARE_LINEAR_ZALLOC_CXX_OPERATORS (ast_node)
virtual bool has_sequence_subexpression () const
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
void set_location_range (const struct YYLTYPE &begin, const struct YYLTYPE &end)
Set the source location range of an AST node using two location nodes.
virtual void set_is_lhs (bool)
Data Fields
const char * type_name
ast_struct_specifier * structure
ast_array_specifier * array_specifier
unsigned default_precision:2
For precision statements, this is the given precision; otherwise none.
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned first_line
First line number within the source string.
unsigned first_column
First column in the first line.
unsigned last_line
Last line number within the source string.
unsigned last_column
Last column in the last line.
} location
Source location of the AST node.
exec_node link
Additional Inherited Members
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_type_specifier() [1/2]
ast_type_specifier::ast_type_specifier (const char * name) inline
Construct a type specifier from a type name.
Referenced by glsl_symbol_table::add_default_precision_qualifier().
ast_type_specifier() [2/2]
ast_type_specifier::ast_type_specifier (ast_struct_specifier * s) inline
Construct a type specifier from a structure definition.
References ast_node::hir(), and ast_node::print().
Member Function Documentation
glsl_type()
const glsl_type * ast_type_specifier::glsl_type (const char ** name, struct _mesa_glsl_parse_state * state) const
References process_array_type().
Referenced by ast_function_expression::hir().
hir()
ir_rvalue * ast_type_specifier::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), ast_precision_none, and is_valid_default_precision_type().
print()
void ast_type_specifier::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References array_specifier, ast_array_specifier::print(), ast_struct_specifier::print(), structure, and type_name.
Field Documentation
array_specifier
ast_array_specifier* ast_type_specifier::array_specifier
Referenced by print().
default_precision
unsigned ast_type_specifier::default_precision
For precision statements, this is the given precision; otherwise none.
Referenced by glsl_symbol_table::add_default_precision_qualifier(), and glsl_symbol_table::get_default_precision_qualifier().
structure
ast_struct_specifier* ast_type_specifier::structure
Referenced by print().
type_name
const char* ast_type_specifier::type_name
Referenced by ast_function_expression::hir(), and print().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
ast_type.cpp