Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
tfeedback_candidate_generator Class Reference
Visitor class that generates tfeedback_candidate structs describing all possible targets of transform feedback.
Public Member Functions
tfeedback_candidate_generator (void *mem_ctx, hash_table *tfeedback_candidates)
void process (ir_variable *var)
Public Member Functions inherited from program_resource_visitor
void process (ir_variable *var)
Begin processing a variable.
void process (const glsl_type *type, const char *name)
Begin processing a variable of a structured type.
Additional Inherited Members
Protected Member Functions inherited from program_resource_visitor
virtual void visit_field (const glsl_struct_field *field)
Visit a record before visiting its fields.
virtual void enter_record (const glsl_type *type, const char *name, bool row_major, const enum glsl_interface_packing packing)
virtual void leave_record (const glsl_type *type, const char *name, bool row_major, const enum glsl_interface_packing packing)
virtual void set_buffer_offset (unsigned offset)
virtual void set_record_array_count (unsigned record_array_count)
Detailed Description
Visitor class that generates tfeedback_candidate structs describing all possible targets of transform feedback.
tfeedback_candidate structs are stored in the hash table tfeedback_candidates, which is passed to the constructor. This hash table maps varying names to instances of the tfeedback_candidate struct.
Constructor & Destructor Documentation
tfeedback_candidate_generator()
tfeedback_candidate_generator::tfeedback_candidate_generator (void * mem_ctx, hash_table * tfeedback_candidates) inline
Member Function Documentation
process()
void tfeedback_candidate_generator::process (ir_variable * var) inline
References tfeedback_decl::name(), and program_resource_visitor::process().
Referenced by assign_varying_locations().
The documentation for this class was generated from the following file:
link_varyings.cpp