Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_rvalue_visitor Class Reference
#include <ir_rvalue_visitor.h>
Public Member Functions
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_discard *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
virtual ir_visitor_status visit_leave (ir_emit_vertex *)
virtual ir_visitor_status visit_leave (ir_end_primitive *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_discard *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
ir_visitor_status rvalue_visit (ir_emit_vertex *)
ir_visitor_status rvalue_visit (ir_end_primitive *)
virtual void handle_rvalue (ir_rvalue **rvalue)=0
Member Function Documentation
visit_leave() [1/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_assignment * ir) virtual
Reimplemented in ir_array_splitting_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
Referenced by is_array_or_matrix(), and process_array_ir().
visit_leave() [2/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_call * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [3/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_dereference_array * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [4/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_dereference_record * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [5/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_discard * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [6/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_expression * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [7/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_if * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [8/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_return * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [9/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_swizzle * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [10/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_texture * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [11/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_emit_vertex * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
visit_leave() [12/12]
ir_visitor_status ir_rvalue_visitor::visit_leave (ir_end_primitive * ir) virtual
References ir_rvalue_base_visitor::rvalue_visit().
The documentation for this class was generated from the following files:
ir_rvalue_visitor.h
ir_rvalue_visitor.cpp