Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
loop_unroll_count Class Reference
Public Member Functions
loop_unroll_count (exec_list *list, loop_variable_state *ls, const struct gl_shader_compiler_options *options)
virtual ir_visitor_status visit_enter (ir_assignment *)
virtual ir_visitor_status visit_enter (ir_expression *)
virtual ir_visitor_status visit_enter (ir_loop *)
virtual ir_visitor_status visit_enter (ir_dereference_array *ir)
Data Fields
int nodes
bool unsupported_variable_indexing
bool array_indexed_by_induction_var_with_exact_iterations
bool nested_loop
Constructor & Destructor Documentation
loop_unroll_count()
loop_unroll_count::loop_unroll_count (exec_list * list, loop_variable_state * ls, const struct gl_shader_compiler_options * options) inline
Member Function Documentation
visit_enter() [1/4]
virtual ir_visitor_status loop_unroll_count::visit_enter (ir_assignment *) inline virtual
References visit_continue.
visit_enter() [2/4]
virtual ir_visitor_status loop_unroll_count::visit_enter (ir_expression *) inline virtual
References visit_continue.
visit_enter() [3/4]
virtual ir_visitor_status loop_unroll_count::visit_enter (ir_loop *) inline virtual
References visit_continue.
visit_enter() [4/4]
virtual ir_visitor_status loop_unroll_count::visit_enter (ir_dereference_array * ir) inline virtual
References array_indexed_by_induction_var_with_exact_iterations, clone_ir_list(), foreach_in_list, loop_variable_state::get(), loop_terminator::ir, is_break(), loop_variable::is_induction_var(), loop_terminator::iterations, loop_variable_state::limiting_terminator, nested_loop, nodes, loop_variable_state::num_loop_jumps, options, unsupported_variable_indexing, and visit_continue.
Field Documentation
array_indexed_by_induction_var_with_exact_iterations
bool loop_unroll_count::array_indexed_by_induction_var_with_exact_iterations
Referenced by visit_enter().
nested_loop
bool loop_unroll_count::nested_loop
Referenced by visit_enter().
nodes
int loop_unroll_count::nodes
Referenced by visit_enter().
unsupported_variable_indexing
bool loop_unroll_count::unsupported_variable_indexing
Referenced by visit_enter().
The documentation for this class was generated from the following file:
loop_unroll.cpp