Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glsl_parser_extras.h File Reference
Typedefs
typedef void(* glcpp_extension_iterator) (struct _mesa_glsl_parse_state *state, void(*add_builtin_define) (struct glcpp_parser *, const char *, int), struct glcpp_parser *data, unsigned version, bool es)
Functions
int glcpp_preprocess (void *ctx, const char **shader, char **info_log, glcpp_extension_iterator extensions, struct _mesa_glsl_parse_state *state, struct gl_context *gl_ctx)
void _mesa_destroy_shader_compiler (void)
To be called at GL teardown time, this frees compiler datastructures.
void _mesa_destroy_shader_compiler_caches (void)
Releases compiler caches to trade off performance for memory.
Typedef Documentation
glcpp_extension_iterator
typedef void(* glcpp_extension_iterator) (struct _mesa_glsl_parse_state *state, void(*add_builtin_define)(struct glcpp_parser *, const char *, int), struct glcpp_parser *data, unsigned version, bool es)
Function Documentation
_mesa_destroy_shader_compiler()
void _mesa_destroy_shader_compiler (void)
To be called at GL teardown time, this frees compiler datastructures.
After calling this, any previously compiled shaders and shader programs would be invalid. So this should happen at approximately program exit.
References _mesa_destroy_shader_compiler_caches().
_mesa_destroy_shader_compiler_caches()
void _mesa_destroy_shader_compiler_caches (void)
Releases compiler caches to trade off performance for memory.
Intended to be used with glReleaseShaderCompiler().
References _mesa_glsl_release_builtin_functions().
Referenced by _mesa_destroy_shader_compiler().
glcpp_preprocess()
int glcpp_preprocess (void * ctx, const char ** shader, char ** info_log, glcpp_extension_iterator extensions, struct _mesa_glsl_parse_state * state, struct gl_context * gl_ctx)
Referenced by _mesa_glsl_compile_shader(), and test_optpass().