Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glsl_to_nir.cpp File Reference
#include "glsl_to_nir.h"
#include "ir_visitor.h"
#include "ir_hierarchical_visitor.h"
#include "ir.h"
#include "compiler/nir/nir_control_flow.h"
#include "compiler/nir/nir_builder.h"
#include "main/imports.h"
Functions
static void nir_remap_attributes (nir_shader *shader)
nir_shader * glsl_to_nir (const struct gl_shader_program *shader_prog, gl_shader_stage stage, const nir_shader_compiler_options *options)
static nir_constant * constant_copy (ir_constant *ir, void *mem_ctx)
static nir_dest * get_instr_dest (nir_instr *instr)
static bool type_is_float (glsl_base_type type)
static bool type_is_signed (glsl_base_type type)
Function Documentation
constant_copy()
static nir_constant* constant_copy (ir_constant * ir, void * mem_ctx) static
References copy(), foreach_in_list, ir_builder::ret(), visit_continue_with_parent, and visit_exec_list().
Referenced by type_is_signed().
get_instr_dest()
static nir_dest* get_instr_dest (nir_instr * instr) static
glsl_to_nir()
nir_shader* glsl_to_nir (const struct gl_shader_program * shader_prog, gl_shader_stage stage, const nir_shader_compiler_options * options)
References nir_remap_attributes(), and visit_exec_list().
nir_remap_attributes()
static void nir_remap_attributes (nir_shader * shader) static
Referenced by glsl_to_nir().
type_is_float()
static bool type_is_float (glsl_base_type type) static
Referenced by type_is_signed().
type_is_signed()
static bool type_is_signed (glsl_base_type type) static
References constant_copy(), ir_unop_cos, ir_unop_dFdx_coarse, ir_unop_dFdy, ir_unop_dFdy_fine, ir_unop_log, ir_unop_log2, ir_builder::swizzle(), and type_is_float().