Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glsl_parser_extras.cpp File Reference
#include <inttypes.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <assert.h>
#include "main/core.h"
#include "main/context.h"
#include "main/debug_output.h"
#include "main/formats.h"
#include "main/shaderobj.h"
#include "util/u_atomic.h"
#include "util/ralloc.h"
#include "util/disk_cache.h"
#include "util/mesa-sha1.h"
#include "ast.h"
#include "glsl_parser_extras.h"
#include "glsl_parser.h"
#include "ir_optimization.h"
#include "loop_analysis.h"
#include "builtin_functions.h"
#include "main/extensions_table.h"
Data Structures
struct _mesa_glsl_extension
Element type for _mesa_glsl_supported_extensions.
Macros
#define EXT(name_str, driver_cap, ...)
Checks if the context supports a user-facing extension.
#define EXT(NAME)
Checks if the context supports a user-facing extension.
#define EXT_AEP(NAME)
#define OPT(PASS, ...)
Enumerations
enum ext_behavior { extension_disable, extension_enable, extension_require, extension_warn }
Enum representing the possible behaviors that can be specified in an #extension directive.
Functions
const char * glsl_compute_version_string (void *mem_ctx, bool is_es, unsigned version)
Format a short human-readable description of the given GLSL version.
static void _mesa_glsl_msg (const YYLTYPE *locp, _mesa_glsl_parse_state *state, GLenum type, const char *fmt, va_list ap)
void _mesa_glsl_error (YYLTYPE *locp, _mesa_glsl_parse_state *state, const char *fmt,...)
void _mesa_glsl_warning (const YYLTYPE *locp, _mesa_glsl_parse_state *state, const char *fmt,...)
static const _mesa_glsl_extension * find_extension (const char *name)
Find an extension by name in _mesa_glsl_supported_extensions.
bool _mesa_glsl_process_extension (const char *name, YYLTYPE *name_locp, const char *behavior_string, YYLTYPE *behavior_locp, _mesa_glsl_parse_state *state)
void _mesa_ast_set_aggregate_type (const glsl_type *type, ast_expression *expr)
Recurses through <type> and <expr> if <expr> is an aggregate initializer and sets <expr>'s <constructor_type> field to <type>.
void _mesa_ast_process_interface_block (YYLTYPE *locp, _mesa_glsl_parse_state *state, ast_interface_block *const block, const struct ast_type_qualifier &q)
void _mesa_ast_type_qualifier_print (const struct ast_type_qualifier *q)
static void ast_opt_array_dimensions_print (const ast_array_specifier *array_specifier)
static void set_shader_inout_layout (struct gl_shader *shader, struct _mesa_glsl_parse_state *state)
static void assign_subroutine_indexes (struct gl_shader *sh, struct _mesa_glsl_parse_state *state)
static void add_builtin_defines (struct _mesa_glsl_parse_state *state, void(*add_builtin_define)(struct glcpp_parser *, const char *, int), struct glcpp_parser *data, unsigned version, bool es)
static void do_late_parsing_checks (struct _mesa_glsl_parse_state *state)
void _mesa_glsl_compile_shader (struct gl_context *ctx, struct gl_shader *shader, bool dump_ast, bool dump_hir, bool force_recompile)
bool do_common_optimization (exec_list *ir, bool linked, bool uniform_locations_assigned, const struct gl_shader_compiler_options *options, bool native_integers)
Do the set of common optimizations passes.
void _mesa_destroy_shader_compiler (void)
To be called at GL teardown time, this frees compiler datastructures.
void _mesa_destroy_shader_compiler_caches (void)
Releases compiler caches to trade off performance for memory.
Variables
static const unsigned known_desktop_glsl_versions []
static const unsigned known_desktop_gl_versions []
static const _mesa_glsl_extension _mesa_glsl_supported_extensions []
Table of extensions that can be enabled/disabled within a shader, and the conditions under which they are supported.
Macro Definition Documentation
EXT [1/2]
#define EXT (name_str, driver_cap, ...)
Value:
static MAYBE_UNUSED bool \
has_##name_str(const struct gl_context *ctx, gl_api api, uint8_t version) \
{ \
   return ctx->Extensions.driver_cap && (version >= \
          _mesa_extension_table[MESA_EXTENSION_##name_str].version[api]); \
}
Checks if the context supports a user-facing extension.
EXT [2/2]
#define EXT (NAME)
Value:
{ "GL_" #NAME, false, has_##NAME,                        \
     &_mesa_glsl_parse_state::NAME##_enable,                \
     &_mesa_glsl_parse_state::NAME##_warn }
Checks if the context supports a user-facing extension.
EXT_AEP
#define EXT_AEP (NAME)
Value:
{ "GL_" #NAME, true, has_##NAME,                         \
     &_mesa_glsl_parse_state::NAME##_enable,                \
     &_mesa_glsl_parse_state::NAME##_warn }
OPT
#define OPT (PASS, ...)
Value:
do {                                             \
      if (debug) {                                                      \
         fprintf(stderr, "START GLSL optimization %s\n", #PASS);        \
         const bool opt_progress = PASS(__VA_ARGS__);                   \
         progress = opt_progress || progress;                           \
         if (opt_progress)                                              \
            _mesa_print_ir(stderr, ir, NULL);                           \
         fprintf(stderr, "GLSL optimization %s: %s progress\n",         \
                 #PASS, opt_progress ? "made" : "no");                  \
      } else {                                                          \
         progress = PASS(__VA_ARGS__) || progress;                      \
      }                                                                 \
   } while (false)
Referenced by do_common_optimization().
Enumeration Type Documentation
ext_behavior
enum ext_behavior
Enum representing the possible behaviors that can be specified in an #extension directive.
Enumerator
extension_disable
extension_enable
extension_require
extension_warn
Function Documentation
_mesa_ast_process_interface_block()
void _mesa_ast_process_interface_block (YYLTYPE * locp, _mesa_glsl_parse_state * state, ast_interface_block *const block, const struct ast_type_qualifier & q)
References _mesa_glsl_error(), _mesa_glsl_warning(), ast_interface_block::declarations, ast_interface_block::default_layout, ast_type_qualifier::flags, foreach_list_typed, ast_type_qualifier::i, ast_interface_block::instance_name, ast_type_qualifier::q, ast_type_qualifier::stream, and ast_type_qualifier::xfb_buffer.
Referenced by ast_cs_input_layout::ast_cs_input_layout().
_mesa_ast_set_aggregate_type()
void _mesa_ast_set_aggregate_type (const glsl_type * type, ast_expression * expr)
Recurses through <type> and <expr> if <expr> is an aggregate initializer and sets <expr>'s <constructor_type> field to <type>.
Gives later functions (process_array_constructor, et al) sufficient information to do type checking.
Operates on assignments involving an aggregate initializer. E.g.,
vec4 pos = {1.0, -1.0, 0.0, 1.0};
or more ridiculously,
struct S { vec4 v[2]; };
struct { S a[2], b; int c; } aggregate = { { { { {1.0, 2.0, 3.0, 4.0}, // a[0].v[0] {5.0, 6.0, 7.0, 8.0} // a[0].v[1] } // a[0].v }, // a[0] { { {1.0, 2.0, 3.0, 4.0}, // a[1].v[0] {5.0, 6.0, 7.0, 8.0} // a[1].v[1] } // a[1].v } // a[1] }, // a { { {1.0, 2.0, 3.0, 4.0}, // b.v[0] {5.0, 6.0, 7.0, 8.0} // b.v[1] } // b.v }, // b 4 // c };
This pass is necessary because the right-hand side of <type> e = { ... } doesn't contain sufficient information to determine if the types match.
References ast_aggregate_initializer::constructor_type, exec_node_data, ir_builder::expr(), ast_expression::expressions, exec_node::next, and ast_expression::oper.
Referenced by ast_cs_input_layout::ast_cs_input_layout(), and process_initializer().
_mesa_ast_type_qualifier_print()
void _mesa_ast_type_qualifier_print (const struct ast_type_qualifier * q)
References ast_type_qualifier::flags, ast_type_qualifier::is_subroutine_decl(), ast_subroutine_list::print(), ast_type_qualifier::q, and ast_type_qualifier::subroutine_list.
Referenced by ast_fully_specified_type::print().
_mesa_destroy_shader_compiler()
void _mesa_destroy_shader_compiler (void)
To be called at GL teardown time, this frees compiler datastructures.
After calling this, any previously compiled shaders and shader programs would be invalid. So this should happen at approximately program exit.
References _mesa_destroy_shader_compiler_caches().
_mesa_destroy_shader_compiler_caches()
void _mesa_destroy_shader_compiler_caches (void)
Releases compiler caches to trade off performance for memory.
Intended to be used with glReleaseShaderCompiler().
References _mesa_glsl_release_builtin_functions().
Referenced by _mesa_destroy_shader_compiler().
_mesa_glsl_compile_shader()
void _mesa_glsl_compile_shader (struct gl_context * ctx, struct gl_shader * shader, bool dump_ast, bool dump_hir, bool force_recompile)
References _mesa_ast_to_hir(), _mesa_glsl_initialize_derived_variables(), _mesa_print_ir(), add_builtin_defines(), assign_subroutine_indexes(), do_common_optimization(), do_late_parsing_checks(), foreach_in_list, foreach_list_typed, glcpp_preprocess(), ast_node::link, lower_subroutine(), optimize_dead_builtin_variables(), options, reparent_ir(), set_shader_inout_layout(), ast_node::source, and validate_ir_tree().
Referenced by compile_shader(), compile_shaders(), and link_shaders().
_mesa_glsl_error()
void _mesa_glsl_error (YYLTYPE * locp, _mesa_glsl_parse_state * state, const char * fmt, ...)
References _mesa_glsl_msg().
Referenced by _mesa_ast_array_index_to_hir(), _mesa_ast_field_selection_to_hir(), _mesa_ast_process_interface_block(), _mesa_ast_to_hir(), _mesa_glsl_process_extension(), apply_explicit_binding(), apply_explicit_location(), apply_image_qualifier_to_variable(), apply_layout_qualifier_to_variable(), apply_type_qualifier_to_variable(), arithmetic_result_type(), ast_process_struct_or_iface_block_members(), bit_logic_result_type(), check_builtin_array_max_size(), ast_iteration_statement::condition_to_hir(), detect_conflicting_assignments(), do_assignment(), ast_expression::do_hir(), do_late_parsing_checks(), emit_errors_unlinked(), get_scalar_boolean_operand(), get_variable_being_redeclared(), handle_tess_ctrl_shader_output_decl(), handle_tess_shader_input_decl(), ast_function_expression::hir(), ast_aggregate_initializer::hir(), ast_struct_specifier::hir(), ast_type_specifier::hir(), ast_declarator_list::hir(), ast_parameter_declarator::hir(), ast_function::hir(), ast_case_label::hir(), ast_selection_statement::hir(), ast_switch_statement::hir(), ast_jump_statement::hir(), ast_function_definition::hir(), ast_interface_block::hir(), ast_tcs_output_layout::hir(), ast_gs_input_layout::hir(), ast_cs_input_layout::hir(), ast_type_qualifier::merge_into_in_qualifier(), ast_type_qualifier::merge_qualifier(), modulus_result_type(), no_matching_function_error(), ast_parameter_declarator::parameters_to_hir(), print_function_prototypes(), process_array_constructor(), process_array_size(), process_initializer(), ast_layout_expression::process_qualifier_constant(), process_qualifier_constant(), process_record_constructor(), process_vec_mat_constructor(), relational_result_type(), select_gles_precision(), set_shader_inout_layout(), shift_result_type(), unary_arithmetic_result_type(), validate_array_dimensions(), validate_assignment(), ast_type_qualifier::validate_flags(), validate_identifier(), ast_type_qualifier::validate_in_qualifier(), validate_interpolation_qualifier(), validate_layout_qualifier_vertex_count(), validate_matrix_layout_for_type(), validate_ordering(), ast_type_qualifier::validate_out_qualifier(), validate_prim_type(), validate_stream_qualifier(), validate_vertex_spacing(), validate_xfb_buffer_qualifier(), validate_xfb_offset_qualifier(), verify_first_atomic_parameter(), verify_image_parameter(), and verify_parameter_modes().
_mesa_glsl_msg()
static void _mesa_glsl_msg (const YYLTYPE * locp, _mesa_glsl_parse_state * state, GLenum type, const char * fmt, va_list ap) static
References _mesa_shader_debug().
Referenced by _mesa_glsl_error(), and _mesa_glsl_warning().
_mesa_glsl_process_extension()
bool _mesa_glsl_process_extension (const char * name, YYLTYPE * name_locp, const char * behavior_string, YYLTYPE * behavior_locp, _mesa_glsl_parse_state * state)
References _mesa_glsl_error(), _mesa_glsl_warning(), _mesa_glsl_extension::aep, _mesa_glsl_extension::available_pred, _mesa_glsl_extension::compatible_with_state(), extension_disable, extension_enable, extension_require, extension_warn, find_extension(), and _mesa_glsl_extension::set_flags().
_mesa_glsl_warning()
void _mesa_glsl_warning (const YYLTYPE * locp, _mesa_glsl_parse_state * state, const char * fmt, ...)
References _mesa_glsl_msg().
Referenced by _mesa_ast_array_index_to_hir(), _mesa_ast_process_interface_block(), _mesa_glsl_process_extension(), apply_layout_qualifier_to_variable(), bit_logic_result_type(), ast_expression::do_hir(), ast_struct_specifier::hir(), ast_declarator_list::hir(), validate_identifier(), validate_matrix_layout_for_type(), and verify_parameter_modes().
add_builtin_defines()
static void add_builtin_defines (struct _mesa_glsl_parse_state * state, void(*)(struct glcpp_parser *, const char *, int) add_builtin_define, struct glcpp_parser * data, unsigned version, bool es) static
References _mesa_glsl_extension::compatible_with_state(), ast_type_qualifier::i, and _mesa_glsl_extension::name.
Referenced by _mesa_glsl_compile_shader().
assign_subroutine_indexes()
static void assign_subroutine_indexes (struct gl_shader * sh, struct _mesa_glsl_parse_state * state) static
References ast_type_qualifier::index.
Referenced by _mesa_glsl_compile_shader().
ast_opt_array_dimensions_print()
static void ast_opt_array_dimensions_print (const ast_array_specifier * array_specifier) static
References ast_array_specifier::print().
Referenced by ast_declaration::print(), and ast_parameter_declarator::print().
do_common_optimization()
bool do_common_optimization (exec_list * ir, bool linked, bool uniform_locations_assigned, const struct gl_shader_compiler_options * options, bool native_integers)
Do the set of common optimizations passes.
Parameters
ir List of instructions to be optimized
linked Is the shader linked? This enables optimizations passes that remove code at global scope and could cause linking to fail.
uniform_locations_assigned Have locations already been assigned for uniforms? This prevents the declarations of unused uniforms from being removed. The setting of this flag only matters if linked is true.
options The driver's preferred shader options.
native_integers Selects optimizations that depend on the implementations supporting integers natively (as opposed to supporting integers in floating point registers).
References analyze_loop_variables(), debug, do_algebraic(), do_constant_folding(), do_constant_propagation(), do_constant_variable(), do_constant_variable_unlinked(), do_copy_propagation(), do_copy_propagation_elements(), do_dead_code(), do_dead_code_local(), do_dead_code_unlinked(), do_dead_functions(), do_function_inlining(), do_if_simplification(), do_lower_jumps(), do_minmax_prune(), do_noop_swizzle(), do_rebalance_tree(), do_structure_splitting(), do_swizzle_swizzle(), do_tree_grafting(), do_vec_index_to_swizzle(), do_vectorize(), loop_state::loop_found, lower_instructions(), lower_vector_insert(), OPT, opt_conditional_discard(), opt_flatten_nested_if_blocks(), opt_flip_matrices(), optimize_redundant_jumps(), optimize_split_arrays(), propagate_invariance(), set_loop_controls(), SUB_TO_ADD_NEG, and unroll_loops().
Referenced by _mesa_glsl_compile_shader(), do_optimization(), linker_optimisation_loop(), and standalone_compile_shader().
do_late_parsing_checks()
static void do_late_parsing_checks (struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error().
Referenced by _mesa_glsl_compile_shader().
find_extension()
static const _mesa_glsl_extension* find_extension (const char * name) static
Find an extension by name in _mesa_glsl_supported_extensions.
If the name is not found, return NULL.
Referenced by _mesa_glsl_process_extension().
glsl_compute_version_string()
const char* glsl_compute_version_string (void * mem_ctx, bool is_es, unsigned version)
Format a short human-readable description of the given GLSL version.
set_shader_inout_layout()
static void set_shader_inout_layout (struct gl_shader * shader, struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error(), ast_type_qualifier::i, ast_type_qualifier::invocations, process_qualifier_constant(), ast_type_qualifier::vertices, and ast_type_qualifier::xfb_stride.
Referenced by _mesa_glsl_compile_shader().
Variable Documentation
_mesa_glsl_supported_extensions
const _mesa_glsl_extension _mesa_glsl_supported_extensions[] static
Table of extensions that can be enabled/disabled within a shader, and the conditions under which they are supported.
known_desktop_gl_versions
const unsigned known_desktop_gl_versions[] static
Initial value:
=
   {  20,  21,  30,  31,  32,  33,  40,  41,  42,  43,  44,  45 }
known_desktop_glsl_versions
const unsigned known_desktop_glsl_versions[] static
Initial value:
=
   { 110, 120, 130, 140, 150, 330, 400, 410, 420, 430, 440, 450 }