Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "util/ralloc.h"
#include "compiler/glsl_types.h"
#include "list.h"
#include "ir_visitor.h"
#include "ir_hierarchical_visitor.h"
#include "main/mtypes.h"
Functions
void _mesa_print_ir (FILE *f, struct exec_list *instructions, struct _mesa_glsl_parse_state *state)
void fprint_ir (FILE *f, const void *instruction)
const struct gl_builtin_uniform_desc * _mesa_glsl_get_builtin_uniform_desc (const char *name)
unsigned vertices_per_prim (GLenum prim)
Function Documentation
_mesa_glsl_get_builtin_uniform_desc()
const struct gl_builtin_uniform_desc* _mesa_glsl_get_builtin_uniform_desc (const char * name)
_mesa_print_ir()
void _mesa_print_ir (FILE * f, struct exec_list * instructions, struct _mesa_glsl_parse_state * state)
References foreach_in_list, and print_type().
Referenced by _mesa_glsl_compile_shader(), compile_shader(), optimize_split_arrays(), and test_optpass().
fprint_ir()
void fprint_ir (FILE * f, const void * instruction)
vertices_per_prim()
unsigned vertices_per_prim (GLenum prim)
Referenced by handle_geometry_shader_input_decl(), ast_gs_input_layout::hir(), link_intrastage_shaders(), and validate_geometry_shader_executable().