Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir.cpp File Reference
#include <string.h>
#include "main/core.h"
#include "ir.h"
#include "compiler/glsl_types.h"
#include "ir_expression_operation_strings.h"
Macros
#define X 1
#define R 5
#define S 9
#define I 13
Functions
static void update_rhs_swizzle (ir_swizzle_mask &m, unsigned from, unsigned to)
Modify the swizzle make to move one component to another.
const char * depth_layout_string (ir_depth_layout layout)
const char * interpolation_string (unsigned interpolation)
static bool modes_match (unsigned a, unsigned b)
void visit_exec_list (exec_list *list, ir_visitor *visitor)
static void steal_memory (ir_instruction *ir, void *new_ctx)
void reparent_ir (exec_list *list, void *mem_ctx)
static ir_rvalue * try_min_one (ir_rvalue *ir)
static ir_rvalue * try_max_zero (ir_rvalue *ir)
unsigned vertices_per_prim (GLenum prim)
const char * mode_string (const ir_variable *var)
Generate a string describing the mode of a variable.
Variables
static const char *const tex_opcode_strs [] = { "tex", "txb", "txl", "txd", "txf", "txf_ms", "txs", "lod", "tg4", "query_levels", "texture_samples", "samples_identical" }
Macro Definition Documentation
I
#define I 13
R
#define R 5
S
#define S 9
X
#define X 1
Function Documentation
depth_layout_string()
const char* depth_layout_string (ir_depth_layout layout)
References foreach_in_list, int64(), and exec_node::next.
Referenced by get_variable_being_redeclared().
interpolation_string()
const char* interpolation_string (unsigned interpolation)
Referenced by cross_validate_types_and_qualifiers(), and validate_interpolation_qualifier().
mode_string()
const char* mode_string (const ir_variable * var)
Generate a string describing the mode of a variable.
Referenced by apply_explicit_location(), cross_validate_globals(), and validate_intrastage_arrays().
modes_match()
static bool modes_match (unsigned a, unsigned b) static
References foreach_in_list, and foreach_two_lists.
reparent_ir()
void reparent_ir (exec_list * list, void * mem_ctx)
References foreach_in_list, steal_memory(), and visit_tree().
Referenced by _mesa_glsl_compile_shader(), and link_shaders().
steal_memory()
static void steal_memory (ir_instruction * ir, void * new_ctx) static
References foreach_in_list.
Referenced by reparent_ir().
try_max_zero()
static ir_rvalue* try_max_zero (ir_rvalue * ir) static
References ir_builder::expr().
try_min_one()
static ir_rvalue* try_min_one (ir_rvalue * ir) static
References ir_builder::expr().
update_rhs_swizzle()
static void update_rhs_swizzle (ir_swizzle_mask & m, unsigned from, unsigned to) static
Modify the swizzle make to move one component to another.
Parameters
m IR swizzle to be modified
from Component in the RHS that is to be swizzled
to Desired swizzle location of from
References ir_unop_cos, ir_unop_dFdx_coarse, ir_unop_dFdy, ir_unop_dFdy_fine, ir_unop_log, and ir_unop_log2.
vertices_per_prim()
unsigned vertices_per_prim (GLenum prim)
Referenced by handle_geometry_shader_input_decl(), ast_gs_input_layout::hir(), link_intrastage_shaders(), and validate_geometry_shader_executable().
visit_exec_list()
void visit_exec_list (exec_list * list, ir_visitor * visitor)
References foreach_in_list_safe.
Referenced by constant_copy(), do_lower_jumps(), and glsl_to_nir().
Variable Documentation
tex_opcode_strs
const char* const tex_opcode_strs[] = { "tex", "txb", "txl", "txd", "txf", "txf_ms", "txs", "lod", "tg4", "query_levels", "texture_samples", "samples_identical" } static