Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_hierarchical_visitor.cpp File Reference
#include "ir.h"
#include "ir_hierarchical_visitor.h"
Functions
void visit_tree (ir_instruction *ir, void(*callback_enter)(class ir_instruction *ir, void *data), void *data_enter, void(*callback_leave)(class ir_instruction *ir, void *data), void *data_leave)
Function Documentation
visit_tree()
void visit_tree (ir_instruction * ir, void(*)(class ir_instruction *ir, void *data) callback_enter, void * data_enter, void(*)(class ir_instruction *ir, void *data) callback_leave, void * data_leave)
Referenced by handle_expression(), move_block_to_cond_assign(), reparent_ir(), replace_return_with_assignment(), rewrite_swizzle(), update_types(), and validate_ir_tree().