Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_reader.h File Reference
#include "ir.h"
Functions
void _mesa_glsl_read_ir (_mesa_glsl_parse_state *state, exec_list *instructions, const char *src, bool scan_for_prototypes)
Function Documentation
_mesa_glsl_read_ir()
void _mesa_glsl_read_ir (_mesa_glsl_parse_state * state, exec_list * instructions, const char * src, bool scan_for_prototypes)
References debug, ir_builder::expr(), foreach_in_list, MATCH, exec_node::next, PARTIAL_MATCH, s_expression::print(), s_expression::read_expression(), ir_builder::sub(), s_list::subexpressions, SX_AS_LIST, SX_AS_SYMBOL, validate_ir_tree(), and s_symbol::value().
Referenced by test_optpass().