Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_hv_accept.cpp File Reference
Implementations of all hierarchical visitor accept methods for IR instructions.
#include "ir.h"
Functions
ir_visitor_status visit_list_elements (ir_hierarchical_visitor *v, exec_list *l, bool statement_list)
Process a list of nodes using a hierarchical vistor.
Detailed Description
Implementations of all hierarchical visitor accept methods for IR instructions.
Function Documentation
visit_list_elements()
ir_visitor_status visit_list_elements (ir_hierarchical_visitor * v, exec_list * l, bool statement_list)
Process a list of nodes using a hierarchical vistor.
If statement_list is true (the default), this is a list of statements, so v->base_ir will be set to point to each statement just before iterating over it, and restored after iteration is complete. If statement_list is false, this is a list that appears inside a statement (e.g. a parameter list), so v->base_ir will be left alone.
Warning
This function will operate correctly if a node being processed is removed from the list. However, if nodes are added to the list after the node being processed, some of the added nodes may not be processed.
References foreach_in_list_safe, visit_continue, visit_continue_with_parent, and visit_stop.
Referenced by do_algebraic(), do_constant_folding(), do_constant_propagation(), do_copy_propagation(), do_copy_propagation_elements(), do_dead_functions(), do_lower_texture_projection(), do_mat_op_to_vec(), do_minmax_prune(), do_noop_swizzle(), do_set_program_inouts(), do_structure_splitting(), do_tree_grafting(), do_variable_replacement(), do_vec_index_to_cond_assign(), is_multiple_vertices(), link_uniform_blocks(), lower_64bit_integer_instructions(), lower_clip_cull_distance(), lower_discard(), lower_discard_flow(), lower_if_to_cond_assign(), lower_instructions(), lower_noise(), lower_offset_arrays(), lower_output_reads(), lower_packing_builtins(), lower_quadop_vector(), lower_shared_reference(), lower_subroutine(), lower_tess_level(), lower_ubo_reference(), lower_variable_index_to_cond_assign(), lower_vector_derefs(), lower_vector_insert(), opt_flip_matrices(), optimize_split_arrays(), process_array_ir(), propagate_invariance(), standalone_compile_shader(), ir_builder_print_visitor::visit_enter(), ir_variable_refcount_visitor::visit_enter(), ir_array_refcount_visitor::visit_enter(), and write_mask_matches_swizzle().