Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_optimization.h File Reference
Prototypes for optimization passes to be called by the compiler and drivers.
Macros
#define SUB_TO_ADD_NEG 0x01
#define FDIV_TO_MUL_RCP 0x02
#define EXP_TO_EXP2 0x04
#define POW_TO_EXP2 0x08
#define LOG_TO_LOG2 0x10
#define MOD_TO_FLOOR 0x20
#define INT_DIV_TO_MUL_RCP 0x40
#define LDEXP_TO_ARITH 0x80
#define CARRY_TO_ARITH 0x100
#define BORROW_TO_ARITH 0x200
#define SAT_TO_CLAMP 0x400
#define DOPS_TO_DFRAC 0x800
#define DFREXP_DLDEXP_TO_ARITH 0x1000
#define BIT_COUNT_TO_MATH 0x02000
#define EXTRACT_TO_SHIFTS 0x04000
#define INSERT_TO_SHIFTS 0x08000
#define REVERSE_TO_SHIFTS 0x10000
#define FIND_LSB_TO_FLOAT_CAST 0x20000
#define FIND_MSB_TO_FLOAT_CAST 0x40000
#define IMUL_HIGH_TO_MUL 0x80000
#define DDIV_TO_MUL_RCP 0x100000
#define DIV_TO_MUL_RCP (FDIV_TO_MUL_RCP | DDIV_TO_MUL_RCP)
#define SQRT_TO_ABS_SQRT 0x200000
#define MUL64 (1U << 0)
#define SIGN64 (1U << 1)
#define DIV64 (1U << 2)
#define MOD64 (1U << 3)
Enumerations
enum lower_packing_builtins_op {
LOWER_PACK_UNPACK_NONE = 0x0000, LOWER_PACK_SNORM_2x16 = 0x0001, LOWER_UNPACK_SNORM_2x16 = 0x0002, LOWER_PACK_UNORM_2x16 = 0x0004,
LOWER_UNPACK_UNORM_2x16 = 0x0008, LOWER_PACK_HALF_2x16 = 0x0010, LOWER_UNPACK_HALF_2x16 = 0x0020, LOWER_PACK_SNORM_4x8 = 0x0040,
LOWER_UNPACK_SNORM_4x8 = 0x0080, LOWER_PACK_UNORM_4x8 = 0x0100, LOWER_UNPACK_UNORM_4x8 = 0x0200, LOWER_PACK_USE_BFI = 0x0400,
LOWER_PACK_USE_BFE = 0x0800
}
Functions
bool do_common_optimization (exec_list *ir, bool linked, bool uniform_locations_assigned, const struct gl_shader_compiler_options *options, bool native_integers)
Do the set of common optimizations passes.
bool ir_constant_fold (ir_rvalue **rvalue)
bool do_rebalance_tree (exec_list *instructions)
bool do_algebraic (exec_list *instructions, bool native_integers, const struct gl_shader_compiler_options *options)
bool opt_conditional_discard (exec_list *instructions)
bool do_constant_folding (exec_list *instructions)
bool do_constant_variable (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_constant_variable_unlinked (exec_list *instructions)
bool do_copy_propagation (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_copy_propagation_elements (exec_list *instructions)
bool do_constant_propagation (exec_list *instructions)
Does a constant propagation pass on the code present in the instruction stream.
void do_dead_builtin_varyings (struct gl_context *ctx, gl_linked_shader *producer, gl_linked_shader *consumer, unsigned num_tfeedback_decls, class tfeedback_decl *tfeedback_decls)
bool do_dead_code (exec_list *instructions, bool uniform_locations_assigned)
Do a dead code pass over instructions and everything that instructions references.
bool do_dead_code_local (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_dead_code_unlinked (exec_list *instructions)
Does a dead code pass on the functions present in the instruction stream.
bool do_dead_functions (exec_list *instructions)
bool opt_flip_matrices (exec_list *instructions)
bool do_function_inlining (exec_list *instructions)
bool do_lower_jumps (exec_list *instructions, bool pull_out_jumps=true, bool lower_sub_return=true, bool lower_main_return=false, bool lower_continue=false, bool lower_break=false)
bool do_lower_texture_projection (exec_list *instructions)
bool do_if_simplification (exec_list *instructions)
bool opt_flatten_nested_if_blocks (exec_list *instructions)
bool do_discard_simplification (exec_list *instructions)
bool lower_if_to_cond_assign (gl_shader_stage stage, exec_list *instructions, unsigned max_depth=0, unsigned min_branch_cost=0)
bool do_mat_op_to_vec (exec_list *instructions)
bool do_minmax_prune (exec_list *instructions)
bool do_noop_swizzle (exec_list *instructions)
bool do_structure_splitting (exec_list *instructions)
bool do_swizzle_swizzle (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_vectorize (exec_list *instructions)
Combines scalar assignments of the same expression (modulo swizzle) to multiple channels of the same variable into a single vectorized expression and assignment.
bool do_tree_grafting (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_vec_index_to_cond_assign (exec_list *instructions)
bool do_vec_index_to_swizzle (exec_list *instructions)
bool lower_discard (exec_list *instructions)
void lower_discard_flow (exec_list *instructions)
bool lower_instructions (exec_list *instructions, unsigned what_to_lower)
bool lower_noise (exec_list *instructions)
bool lower_variable_index_to_cond_assign (gl_shader_stage stage, exec_list *instructions, bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
bool lower_quadop_vector (exec_list *instructions, bool dont_lower_swz)
bool lower_const_arrays_to_uniforms (exec_list *instructions, unsigned stage)
bool lower_clip_cull_distance (struct gl_shader_program *prog, gl_linked_shader *shader)
void lower_output_reads (unsigned stage, exec_list *instructions)
bool lower_packing_builtins (exec_list *instructions, int op_mask)
Lower the builtin packing functions.
void lower_shared_reference (struct gl_linked_shader *shader, unsigned *shared_size)
void lower_ubo_reference (struct gl_linked_shader *shader, bool clamp_block_indices)
void lower_packed_varyings (void *mem_ctx, unsigned locations_used, const uint8_t *components, ir_variable_mode mode, unsigned gs_input_vertices, gl_linked_shader *shader, bool disable_varying_packing, bool xfb_enabled)
bool lower_vector_insert (exec_list *instructions, bool lower_nonconstant_index)
bool lower_vector_derefs (gl_linked_shader *shader)
void lower_named_interface_blocks (void *mem_ctx, gl_linked_shader *shader)
bool optimize_redundant_jumps (exec_list *instructions)
bool optimize_split_arrays (exec_list *instructions, bool linked)
bool lower_offset_arrays (exec_list *instructions)
void optimize_dead_builtin_variables (exec_list *instructions, enum ir_variable_mode other)
Pre-linking, optimize unused built-in variables.
bool lower_tess_level (gl_linked_shader *shader)
bool lower_vertex_id (gl_linked_shader *shader)
bool lower_blend_equation_advanced (gl_linked_shader *shader)
bool lower_subroutine (exec_list *instructions, struct _mesa_glsl_parse_state *state)
void propagate_invariance (exec_list *instructions)
ir_rvalue * compare_index_block (exec_list *instructions, ir_variable *index, unsigned base, unsigned components, void *mem_ctx)
Generate a comparison value for a block of indices.
bool lower_64bit_integer_instructions (exec_list *instructions, unsigned what_to_lower)
Detailed Description
Prototypes for optimization passes to be called by the compiler and drivers.
Macro Definition Documentation
BIT_COUNT_TO_MATH
#define BIT_COUNT_TO_MATH 0x02000
Referenced by lower_instructions().
BORROW_TO_ARITH
#define BORROW_TO_ARITH 0x200
Referenced by lower_instructions().
CARRY_TO_ARITH
#define CARRY_TO_ARITH 0x100
Referenced by lower_instructions().
DDIV_TO_MUL_RCP
#define DDIV_TO_MUL_RCP 0x100000
Referenced by lower_instructions().
DFREXP_DLDEXP_TO_ARITH
#define DFREXP_DLDEXP_TO_ARITH 0x1000
Referenced by lower_instructions().
DIV64
#define DIV64 (1U << 2)
Referenced by lower_64bit::lower_op_to_function_call().
DIV_TO_MUL_RCP
#define DIV_TO_MUL_RCP (FDIV_TO_MUL_RCP | DDIV_TO_MUL_RCP)
DOPS_TO_DFRAC
#define DOPS_TO_DFRAC 0x800
Referenced by lower_instructions().
EXP_TO_EXP2
#define EXP_TO_EXP2 0x04
Referenced by lower_instructions().
EXTRACT_TO_SHIFTS
#define EXTRACT_TO_SHIFTS 0x04000
Referenced by lower_instructions().
FDIV_TO_MUL_RCP
#define FDIV_TO_MUL_RCP 0x02
Referenced by lower_instructions().
FIND_LSB_TO_FLOAT_CAST
#define FIND_LSB_TO_FLOAT_CAST 0x20000
Referenced by lower_instructions().
FIND_MSB_TO_FLOAT_CAST
#define FIND_MSB_TO_FLOAT_CAST 0x40000
Referenced by lower_instructions().
IMUL_HIGH_TO_MUL
#define IMUL_HIGH_TO_MUL 0x80000
Referenced by lower_instructions().
INSERT_TO_SHIFTS
#define INSERT_TO_SHIFTS 0x08000
Referenced by lower_instructions().
INT_DIV_TO_MUL_RCP
#define INT_DIV_TO_MUL_RCP 0x40
Referenced by lower_instructions().
LDEXP_TO_ARITH
#define LDEXP_TO_ARITH 0x80
Referenced by lower_instructions().
LOG_TO_LOG2
#define LOG_TO_LOG2 0x10
Referenced by lower_instructions().
MOD64
#define MOD64 (1U << 3)
Referenced by lower_64bit::lower_op_to_function_call().
MOD_TO_FLOOR
#define MOD_TO_FLOOR 0x20
Referenced by lower_instructions().
MUL64
#define MUL64 (1U << 0)
Referenced by lower_64bit::lower_op_to_function_call().
POW_TO_EXP2
#define POW_TO_EXP2 0x08
Referenced by lower_instructions().
REVERSE_TO_SHIFTS
#define REVERSE_TO_SHIFTS 0x10000
Referenced by lower_instructions().
SAT_TO_CLAMP
#define SAT_TO_CLAMP 0x400
Referenced by lower_instructions().
SIGN64
#define SIGN64 (1U << 1)
Referenced by lower_64bit::lower_op_to_function_call().
SQRT_TO_ABS_SQRT
#define SQRT_TO_ABS_SQRT 0x200000
Referenced by lower_instructions().
SUB_TO_ADD_NEG
#define SUB_TO_ADD_NEG 0x01
Referenced by do_common_optimization(), and lower_instructions().
Enumeration Type Documentation
lower_packing_builtins_op
enum lower_packing_builtins_op
See also
class lower_packing_builtins_visitor
Enumerator
LOWER_PACK_UNPACK_NONE
LOWER_PACK_SNORM_2x16
LOWER_UNPACK_SNORM_2x16
LOWER_PACK_UNORM_2x16
LOWER_UNPACK_UNORM_2x16
LOWER_PACK_HALF_2x16
LOWER_UNPACK_HALF_2x16
LOWER_PACK_SNORM_4x8
LOWER_UNPACK_SNORM_4x8
LOWER_PACK_UNORM_4x8
LOWER_UNPACK_UNORM_4x8
LOWER_PACK_USE_BFI
LOWER_PACK_USE_BFE
Function Documentation
compare_index_block()
ir_rvalue* compare_index_block (exec_list * instructions, ir_variable * index, unsigned base, unsigned components, void * mem_ctx)
Generate a comparison value for a block of indices.
Lowering passes for non-constant indexing of arrays, matrices, or vectors can use this to generate blocks of index comparison values.
Parameters
instructions List where new instructions will be appended
index ir_variable containing the desired index
base Base value for this block of comparisons
components Number of unique index values to compare. This must be on the range [1, 4].
mem_ctx ralloc memory context to be used for all allocations.
Returns
An ir_rvalue that must be cloned for each use in conditional assignments, etc.
Referenced by is_array_or_matrix().
do_algebraic()
bool do_algebraic (exec_list * instructions, bool native_integers, const struct gl_shader_compiler_options * options)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_common_optimization()
bool do_common_optimization (exec_list * ir, bool linked, bool uniform_locations_assigned, const struct gl_shader_compiler_options * options, bool native_integers)
Do the set of common optimizations passes.
Parameters
ir List of instructions to be optimized
linked Is the shader linked? This enables optimizations passes that remove code at global scope and could cause linking to fail.
uniform_locations_assigned Have locations already been assigned for uniforms? This prevents the declarations of unused uniforms from being removed. The setting of this flag only matters if linked is true.
options The driver's preferred shader options.
native_integers Selects optimizations that depend on the implementations supporting integers natively (as opposed to supporting integers in floating point registers).
References analyze_loop_variables(), debug, do_algebraic(), do_constant_folding(), do_constant_propagation(), do_constant_variable(), do_constant_variable_unlinked(), do_copy_propagation(), do_copy_propagation_elements(), do_dead_code(), do_dead_code_local(), do_dead_code_unlinked(), do_dead_functions(), do_function_inlining(), do_if_simplification(), do_lower_jumps(), do_minmax_prune(), do_noop_swizzle(), do_rebalance_tree(), do_structure_splitting(), do_swizzle_swizzle(), do_tree_grafting(), do_vec_index_to_swizzle(), do_vectorize(), loop_state::loop_found, lower_instructions(), lower_vector_insert(), OPT, opt_conditional_discard(), opt_flatten_nested_if_blocks(), opt_flip_matrices(), optimize_redundant_jumps(), optimize_split_arrays(), propagate_invariance(), set_loop_controls(), SUB_TO_ADD_NEG, and unroll_loops().
Referenced by _mesa_glsl_compile_shader(), do_optimization(), linker_optimisation_loop(), and standalone_compile_shader().
do_constant_folding()
bool do_constant_folding (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_constant_propagation()
bool do_constant_propagation (exec_list * instructions)
Does a constant propagation pass on the code present in the instruction stream.
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_constant_variable()
bool do_constant_variable (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
Referenced by do_common_optimization(), do_constant_variable_unlinked(), and do_optimization().
do_constant_variable_unlinked()
bool do_constant_variable_unlinked (exec_list * instructions)
References do_constant_variable(), and foreach_in_list.
Referenced by do_common_optimization(), and do_optimization().
do_copy_propagation()
bool do_copy_propagation (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_copy_propagation_elements()
bool do_copy_propagation_elements (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_dead_builtin_varyings()
void do_dead_builtin_varyings (struct gl_context * ctx, gl_linked_shader * producer, gl_linked_shader * consumer, unsigned num_tfeedback_decls, class tfeedback_decl * tfeedback_decls)
References lower_fragdata_array(), and lower_texcoord_array().
Referenced by link_varyings().
do_dead_code()
bool do_dead_code (exec_list * instructions, bool uniform_locations_assigned)
Do a dead code pass over instructions and everything that instructions references.
Note that this will remove assignments to globals, so it is not suitable for usage on an unlinked instruction stream.
References assignment_entry::assign, ir_variable_refcount_entry::assign_list, ir_variable_refcount_entry::assigned_count, debug, ir_variable_refcount_entry::declaration, exec_node_data, ir_variable_refcount_visitor::ht, assignment_entry::link, ir_variable_refcount_entry::referenced_count, and ir_variable_refcount_entry::var.
Referenced by do_common_optimization(), do_dead_code_unlinked(), do_optimization(), and remove_unused_shader_inputs_and_outputs().
do_dead_code_local()
bool do_dead_code_local (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References call_for_basic_blocks(), and dead_code_local_basic_block().
Referenced by do_common_optimization(), and do_optimization().
do_dead_code_unlinked()
bool do_dead_code_unlinked (exec_list * instructions)
Does a dead code pass on the functions present in the instruction stream.
This is suitable for use while the program is not linked, as it will ignore variable declarations (and the assignments to them) for variables with global scope.
References do_dead_code(), and foreach_in_list.
Referenced by do_common_optimization(), and do_optimization().
do_dead_functions()
bool do_dead_functions (exec_list * instructions)
References foreach_in_list_safe, and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_discard_simplification()
bool do_discard_simplification (exec_list * instructions)
do_function_inlining()
bool do_function_inlining (exec_list * instructions)
Referenced by do_common_optimization(), do_optimization(), and standalone_compile_shader().
do_if_simplification()
bool do_if_simplification (exec_list * instructions)
References visit_continue.
Referenced by do_common_optimization(), and do_optimization().
do_lower_jumps()
bool do_lower_jumps (exec_list * instructions, bool pull_out_jumps = true, bool lower_sub_return = true, bool lower_main_return = false, bool lower_continue = false, bool lower_break = false)
References visit_exec_list().
Referenced by do_common_optimization(), do_optimization(), and lower_blend_equation_advanced().
do_lower_texture_projection()
bool do_lower_texture_projection (exec_list * instructions)
References visit_list_elements().
Referenced by do_optimization().
do_mat_op_to_vec()
bool do_mat_op_to_vec (exec_list * instructions)
References ir_builder::assign(), do_expression_flattening(), ir_builder::expr(), mat_op_to_vec_predicate(), and visit_list_elements().
Referenced by do_optimization().
do_minmax_prune()
bool do_minmax_prune (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization().
do_noop_swizzle()
bool do_noop_swizzle (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_rebalance_tree()
bool do_rebalance_tree (exec_list * instructions)
Referenced by do_common_optimization().
do_structure_splitting()
bool do_structure_splitting (exec_list * instructions)
References foreach_in_list_safe, and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_swizzle_swizzle()
bool do_swizzle_swizzle (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
Referenced by do_common_optimization(), and do_optimization().
do_tree_grafting()
bool do_tree_grafting (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References call_for_basic_blocks(), and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
do_vec_index_to_cond_assign()
bool do_vec_index_to_cond_assign (exec_list * instructions)
References visit_list_elements().
Referenced by do_optimization().
do_vec_index_to_swizzle()
bool do_vec_index_to_swizzle (exec_list * instructions)
Referenced by do_common_optimization(), do_optimization(), and link_varyings_and_uniforms().
do_vectorize()
bool do_vectorize (exec_list * instructions)
Combines scalar assignments of the same expression (modulo swizzle) to multiple channels of the same variable into a single vectorized expression and assignment.
Referenced by do_common_optimization().
ir_constant_fold()
bool ir_constant_fold (ir_rvalue ** rvalue)
References ir_builder::expr(), foreach_two_lists, ir_rvalue_base_visitor::handle_rvalue(), and visit_continue_with_parent.
lower_64bit_integer_instructions()
bool lower_64bit_integer_instructions (exec_list * instructions, unsigned what_to_lower)
References exec_list::head_sentinel, exec_node::next, exec_node::prev, and visit_list_elements().
lower_blend_equation_advanced()
bool lower_blend_equation_advanced (gl_linked_shader * shader)
References ir_builder::assign(), calc_blend_result(), deref_output(), do_lower_jumps(), ir_builder::ir_factory::emit(), foreach_in_list, get_main(), main(), ir_builder::swizzle(), and validate_ir_tree().
lower_clip_cull_distance()
bool lower_clip_cull_distance (struct gl_shader_program * prog, gl_linked_shader * shader)
References visit_list_elements().
Referenced by link_shaders().
lower_const_arrays_to_uniforms()
bool lower_const_arrays_to_uniforms (exec_list * instructions, unsigned stage)
Referenced by link_shaders().
lower_discard()
bool lower_discard (exec_list * instructions)
References visit_list_elements().
Referenced by do_optimization().
lower_discard_flow()
void lower_discard_flow (exec_list * instructions)
References visit_list_elements().
Referenced by link_shaders().
lower_if_to_cond_assign()
bool lower_if_to_cond_assign (gl_shader_stage stage, exec_list * instructions, unsigned max_depth = 0, unsigned min_branch_cost = 0)
References visit_list_elements().
Referenced by do_optimization().
lower_instructions()
bool lower_instructions (exec_list * instructions, unsigned what_to_lower)
References ir_builder::abs(), ir_builder::add(), ir_builder::assign(), ir_builder::b2i(), ir_builder::bit_and(), BIT_COUNT_TO_MATH, ir_builder::bit_not(), ir_builder::bit_or(), ir_builder::bitcast_f2i(), ir_builder::bitcast_f2u(), ir_builder::bitcast_u2f(), ir_builder::bitfield_insert(), BORROW_TO_ARITH, ir_builder::carry(), CARRY_TO_ARITH, ir_builder::csel(), DDIV_TO_MUL_RCP, DFREXP_DLDEXP_TO_ARITH, DOPS_TO_DFRAC, ir_builder::equal(), ir_builder::exp(), EXP_TO_EXP2, ir_builder::expr(), EXTRACT_TO_SHIFTS, FDIV_TO_MUL_RCP, FIND_LSB_TO_FLOAT_CAST, FIND_MSB_TO_FLOAT_CAST, ir_builder::fma(), ir_builder::fract(), ir_builder::gequal(), ir_builder::greater(), ir_builder::i2u(), IMUL_HIGH_TO_MUL, INSERT_TO_SHIFTS, INT_DIV_TO_MUL_RCP, ir_unop_log, ir_unop_log2, LDEXP_TO_ARITH, ir_builder::less(), LOG_TO_LOG2, ir_builder::logic_and(), lowering, ir_builder::lshift(), MOD_TO_FLOOR, ir_builder::mul(), ir_builder::neg(), ir_builder::nequal(), POW_TO_EXP2, REVERSE_TO_SHIFTS, ir_builder::rshift(), SAT_TO_CLAMP, SQRT_TO_ABS_SQRT, ir_builder::sub(), SUB_TO_ADD_NEG, ir_builder::swizzle(), ir_builder::swizzle_y(), ir_builder::u2f(), ir_builder::u2i(), ir_builder::operand::val, visit_continue, visit_list_elements(), ir_builder::WRITEMASK_X, and ir_builder::WRITEMASK_Y.
Referenced by do_common_optimization(), and do_optimization().
lower_named_interface_blocks()
void lower_named_interface_blocks (void * mem_ctx, gl_linked_shader * shader)
Referenced by link_shaders().
lower_noise()
bool lower_noise (exec_list * instructions)
References lower_noise_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
lower_offset_arrays()
bool lower_offset_arrays (exec_list * instructions)
References lower_offset_array_visitor::progress, and visit_list_elements().
lower_output_reads()
void lower_output_reads (unsigned stage, exec_list * instructions)
References visit_list_elements().
lower_packed_varyings()
void lower_packed_varyings (void * mem_ctx, unsigned locations_used, const uint8_t * components, ir_variable_mode mode, unsigned gs_input_vertices, gl_linked_shader * shader, bool disable_varying_packing, bool xfb_enabled)
Referenced by assign_varying_locations().
lower_packing_builtins()
bool lower_packing_builtins (exec_list * instructions, int op_mask)
Lower the builtin packing functions.
Parameters
op_mask is a bitmask of enum lower_packing_builtins_op.
References visit_list_elements().
lower_quadop_vector()
bool lower_quadop_vector (exec_list * instructions, bool dont_lower_swz)
References visit_list_elements().
Referenced by do_optimization().
lower_shared_reference()
void lower_shared_reference (struct gl_linked_shader * shader, unsigned * shared_size)
References visit_list_elements().
Referenced by link_varyings_and_uniforms().
lower_subroutine()
bool lower_subroutine (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References ir_builder::equal(), foreach_in_list, ir_builder::if_tree(), ir_builder::subr_to_int(), visit_continue, and visit_list_elements().
Referenced by _mesa_glsl_compile_shader().
lower_tess_level()
bool lower_tess_level (gl_linked_shader * shader)
References visit_list_elements().
Referenced by link_shaders().
lower_ubo_reference()
void lower_ubo_reference (struct gl_linked_shader * shader, bool clamp_block_indices)
References visit_list_elements().
Referenced by link_varyings_and_uniforms().
lower_variable_index_to_cond_assign()
bool lower_variable_index_to_cond_assign (gl_shader_stage stage, exec_list * instructions, bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
References visit_list_elements().
Referenced by do_optimization().
lower_vector_derefs()
bool lower_vector_derefs (gl_linked_shader * shader)
References visit_list_elements().
Referenced by link_varyings_and_uniforms().
lower_vector_insert()
bool lower_vector_insert (exec_list * instructions, bool lower_nonconstant_index)
References visit_list_elements().
Referenced by do_common_optimization().
lower_vertex_id()
bool lower_vertex_id (gl_linked_shader * shader)
References _mesa_get_main_function_signature().
Referenced by link_intrastage_shaders().
opt_conditional_discard()
bool opt_conditional_discard (exec_list * instructions)
References visit_continue.
Referenced by do_common_optimization().
opt_flatten_nested_if_blocks()
bool opt_flatten_nested_if_blocks (exec_list * instructions)
References ir_builder::logic_and(), and visit_continue.
Referenced by do_common_optimization().
opt_flip_matrices()
bool opt_flip_matrices (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization().
optimize_dead_builtin_variables()
void optimize_dead_builtin_variables (exec_list * instructions, enum ir_variable_mode other)
Pre-linking, optimize unused built-in variables.
Uniforms, constants, system values, inputs (vertex shader only), and outputs (fragment shader only) that are not used can be removed.
References foreach_in_list_safe.
Referenced by _mesa_glsl_compile_shader().
optimize_redundant_jumps()
bool optimize_redundant_jumps (exec_list * instructions)
Referenced by do_common_optimization(), and do_optimization().
optimize_split_arrays()
bool optimize_split_arrays (exec_list * instructions, bool linked)
References _mesa_print_ir(), debug, foreach_in_list, and visit_list_elements().
Referenced by do_common_optimization().
propagate_invariance()
void propagate_invariance (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and link_shaders().