Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_constant_expression.cpp File Reference
Evaluate and process constant valued expressions.
#include <math.h>
#include "main/core.h"
#include "util/rounding.h"
#include "util/half_float.h"
#include "ir.h"
#include "compiler/glsl_types.h"
#include "util/hash_table.h"
#include "ir_expression_operation_constant.h"
Typedefs
typedef uint8_t(* pack_1x8_func_t) (float)
Evaluate one component of a floating-point 4x8 unpacking function.
typedef uint16_t(* pack_1x16_func_t) (float)
Evaluate one component of a floating-point 2x16 unpacking function.
typedef float(* unpack_1x8_func_t) (uint8_t)
Evaluate one component of a floating-point 4x8 unpacking function.
typedef float(* unpack_1x16_func_t) (uint16_t)
Evaluate one component of a floating-point 2x16 unpacking function.
Functions
static float dot_f (ir_constant *op0, ir_constant *op1)
static double dot_d (ir_constant *op0, ir_constant *op1)
static float bitcast_u2f (unsigned int u)
static unsigned int bitcast_f2u (float f)
static double bitcast_u642d (uint64_t u)
static double bitcast_i642d (int64_t i)
static double bitcast_d2u64 (double d)
static double bitcast_d2i64 (double d)
static uint32_t pack_2x16 (pack_1x16_func_t pack_1x16, float x, float y)
Evaluate a 2x16 floating-point packing function.
static uint32_t pack_4x8 (pack_1x8_func_t pack_1x8, float x, float y, float z, float w)
Evaluate a 4x8 floating-point packing function.
static void unpack_2x16 (unpack_1x16_func_t unpack_1x16, uint32_t u, float *x, float *y)
Evaluate a 2x16 floating-point unpacking function.
static void unpack_4x8 (unpack_1x8_func_t unpack_1x8, uint32_t u, float *x, float *y, float *z, float *w)
Evaluate a 4x8 floating-point unpacking function.
static uint8_t pack_snorm_1x8 (float x)
Evaluate one component of packSnorm4x8.
static uint16_t pack_snorm_1x16 (float x)
Evaluate one component of packSnorm2x16.
static float unpack_snorm_1x8 (uint8_t u)
Evaluate one component of unpackSnorm4x8.
static float unpack_snorm_1x16 (uint16_t u)
Evaluate one component of unpackSnorm2x16.
static uint8_t pack_unorm_1x8 (float x)
Evaluate one component packUnorm4x8.
static uint16_t pack_unorm_1x16 (float x)
Evaluate one component packUnorm2x16.
static float unpack_unorm_1x8 (uint8_t u)
Evaluate one component of unpackUnorm4x8.
static float unpack_unorm_1x16 (uint16_t u)
Evaluate one component of unpackUnorm2x16.
static uint16_t pack_half_1x16 (float x)
Evaluate one component of packHalf2x16.
static float unpack_half_1x16 (uint16_t u)
Evaluate one component of unpackHalf2x16.
static bool constant_referenced (const ir_dereference *deref, struct hash_table *variable_context, ir_constant *&store, int &offset)
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
static uint32_t bitfield_reverse (uint32_t v)
static int find_msb_uint (uint32_t v)
static int find_msb_int (int32_t v)
static float ldexpf_flush_subnormal (float x, int exp)
static double ldexp_flush_subnormal (double x, int exp)
static uint32_t bitfield_extract_uint (uint32_t value, int offset, int bits)
static int32_t bitfield_extract_int (int32_t value, int offset, int bits)
static uint32_t bitfield_insert (uint32_t base, uint32_t insert, int offset, int bits)
Detailed Description
Evaluate and process constant valued expressions.
In GLSL, constant valued expressions are used in several places. These must be processed and evaluated very early in the compilation process.
Sizes of arrays
Initializers for uniforms
Initializers for const variables
Typedef Documentation
pack_1x16_func_t
typedef uint16_t(* pack_1x16_func_t) (float)
Evaluate one component of a floating-point 2x16 unpacking function.
pack_1x8_func_t
typedef uint8_t(* pack_1x8_func_t) (float)
Evaluate one component of a floating-point 4x8 unpacking function.
unpack_1x16_func_t
typedef float(* unpack_1x16_func_t) (uint16_t)
Evaluate one component of a floating-point 2x16 unpacking function.
unpack_1x8_func_t
typedef float(* unpack_1x8_func_t) (uint8_t)
Evaluate one component of a floating-point 4x8 unpacking function.
Function Documentation
bitcast_d2i64()
static double bitcast_d2i64 (double d) static
bitcast_d2u64()
static double bitcast_d2u64 (double d) static
bitcast_f2u()
static unsigned int bitcast_f2u (float f) static
bitcast_i642d()
static double bitcast_i642d (int64_t i) static
bitcast_u2f()
static float bitcast_u2f (unsigned int u) static
bitcast_u642d()
static double bitcast_u642d (uint64_t u) static
bitfield_extract_int()
static int32_t bitfield_extract_int (int32_t value, int offset, int bits) static
bitfield_extract_uint()
static uint32_t bitfield_extract_uint (uint32_t value, int offset, int bits) static
bitfield_insert()
static uint32_t bitfield_insert (uint32_t base, uint32_t insert, int offset, int bits) static
References constant_referenced(), foreach_in_list, and exec_node::next.
bitfield_reverse()
static uint32_t bitfield_reverse (uint32_t v) static
constant_referenced()
static bool constant_referenced (const ir_dereference * deref, struct hash_table * variable_context, ir_constant *& store, int & offset) static
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
The offset is used when the reference is to a specific column of a matrix.
Referenced by bitfield_insert().
dot_d()
static double dot_d (ir_constant * op0, ir_constant * op1) static
dot_f()
static float dot_f (ir_constant * op0, ir_constant * op1) static
find_msb_int()
static int find_msb_int (int32_t v) static
References find_msb_uint().
find_msb_uint()
static int find_msb_uint (uint32_t v) static
Referenced by find_msb_int().
ldexp_flush_subnormal()
static double ldexp_flush_subnormal (double x, int exp) static
ldexpf_flush_subnormal()
static float ldexpf_flush_subnormal (float x, int exp) static
pack_2x16()
static uint32_t pack_2x16 (pack_1x16_func_t pack_1x16, float x, float y) static
Evaluate a 2x16 floating-point packing function.
pack_4x8()
static uint32_t pack_4x8 (pack_1x8_func_t pack_1x8, float x, float y, float z, float w) static
Evaluate a 4x8 floating-point packing function.
pack_half_1x16()
static uint16_t pack_half_1x16 (float x) static
Evaluate one component of packHalf2x16.
pack_snorm_1x16()
static uint16_t pack_snorm_1x16 (float x) static
Evaluate one component of packSnorm2x16.
pack_snorm_1x8()
static uint8_t pack_snorm_1x8 (float x) static
Evaluate one component of packSnorm4x8.
pack_unorm_1x16()
static uint16_t pack_unorm_1x16 (float x) static
Evaluate one component packUnorm2x16.
pack_unorm_1x8()
static uint8_t pack_unorm_1x8 (float x) static
Evaluate one component packUnorm4x8.
unpack_2x16()
static void unpack_2x16 (unpack_1x16_func_t unpack_1x16, uint32_t u, float * x, float * y) static
Evaluate a 2x16 floating-point unpacking function.
unpack_4x8()
static void unpack_4x8 (unpack_1x8_func_t unpack_1x8, uint32_t u, float * x, float * y, float * z, float * w) static
Evaluate a 4x8 floating-point unpacking function.
unpack_half_1x16()
static float unpack_half_1x16 (uint16_t u) static
Evaluate one component of unpackHalf2x16.
unpack_snorm_1x16()
static float unpack_snorm_1x16 (uint16_t u) static
Evaluate one component of unpackSnorm2x16.
unpack_snorm_1x8()
static float unpack_snorm_1x8 (uint8_t u) static
Evaluate one component of unpackSnorm4x8.
unpack_unorm_1x16()
static float unpack_unorm_1x16 (uint16_t u) static
Evaluate one component of unpackUnorm2x16.
unpack_unorm_1x8()
static float unpack_unorm_1x8 (uint8_t u) static
Evaluate one component of unpackUnorm4x8.