Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_print_visitor.cpp File Reference
#include <inttypes.h>
#include "ir_print_visitor.h"
#include "compiler/glsl_types.h"
#include "glsl_parser_extras.h"
#include "main/macros.h"
#include "util/hash_table.h"
Functions
static void print_type (FILE *f, const glsl_type *t)
void _mesa_print_ir (FILE *f, exec_list *instructions, struct _mesa_glsl_parse_state *state)
void fprint_ir (FILE *f, const void *instruction)
Function Documentation
_mesa_print_ir()
void _mesa_print_ir (FILE * f, exec_list * instructions, struct _mesa_glsl_parse_state * state)
References foreach_in_list, and print_type().
Referenced by _mesa_glsl_compile_shader(), compile_shader(), optimize_split_arrays(), and test_optpass().
fprint_ir()
void fprint_ir (FILE * f, const void * instruction)
print_type()
static void print_type (FILE * f, const glsl_type * t) static
Referenced by _mesa_print_ir(), and ir_print_visitor::visit().