Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_set_program_inouts.cpp File Reference
Sets the inputs_read and outputs_written of Mesa programs.
#include "main/core.h"
#include "ir.h"
#include "ir_visitor.h"
#include "compiler/glsl_types.h"
Functions
static bool is_shader_inout (ir_variable *var)
static void mark (struct gl_program *prog, ir_variable *var, int offset, int len, gl_shader_stage stage)
static bool is_multiple_vertices (gl_shader_stage stage, ir_variable *var)
void do_set_program_inouts (exec_list *instructions, struct gl_program *prog, gl_shader_stage shader_stage)
Detailed Description
Sets the inputs_read and outputs_written of Mesa programs.
Mesa programs (gl_program, not gl_shader_program) have a set of flags indicating which varyings are read and written. Computing which are actually read from some sort of backend code can be tricky when variable array indexing involved. So this pass provides support for setting inputs_read and outputs_written right from the GLSL IR.
Function Documentation
do_set_program_inouts()
void do_set_program_inouts (exec_list * instructions, struct gl_program * prog, gl_shader_stage shader_stage)
References visit_list_elements().
is_multiple_vertices()
static bool is_multiple_vertices (gl_shader_stage stage, ir_variable * var) static
References is_shader_inout(), visit_continue, visit_continue_with_parent, and visit_list_elements().
is_shader_inout()
static bool is_shader_inout (ir_variable * var) inline static
Referenced by is_multiple_vertices(), and mark().
mark()
static void mark (struct gl_program * prog, ir_variable * var, int offset, int len, gl_shader_stage stage) static
References is_shader_inout(), and visit_continue.