Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_function.cpp File Reference
#include "compiler/glsl_types.h"
#include "ir.h"
#include "glsl_parser_extras.h"
#include "main/errors.h"
Enumerations
enum parameter_list_match_t { PARAMETER_LIST_NO_MATCH, PARAMETER_LIST_EXACT_MATCH, PARAMETER_LIST_INEXACT_MATCH }
enum parameter_match_t {
PARAMETER_EXACT_MATCH, PARAMETER_FLOAT_TO_DOUBLE, PARAMETER_INT_TO_FLOAT, PARAMETER_INT_TO_DOUBLE,
PARAMETER_OTHER_CONVERSION
}
Functions
static parameter_list_match_t parameter_lists_match (_mesa_glsl_parse_state *state, const exec_list *list_a, const exec_list *list_b)
Check if two parameter lists match.
static parameter_match_t get_parameter_match_type (const ir_variable *param, const ir_rvalue *actual)
static bool is_better_parameter_match (parameter_match_t a_match, parameter_match_t b_match)
static bool is_best_inexact_overload (const exec_list *actual_parameters, ir_function_signature **matches, int num_matches, ir_function_signature *sig)
static ir_function_signature * choose_best_inexact_overload (_mesa_glsl_parse_state *state, const exec_list *actual_parameters, ir_function_signature **matches, int num_matches)
static bool parameter_lists_match_exact (const exec_list *list_a, const exec_list *list_b)
Enumeration Type Documentation
parameter_list_match_t
enum parameter_list_match_t
Enumerator
PARAMETER_LIST_NO_MATCH
PARAMETER_LIST_EXACT_MATCH
PARAMETER_LIST_INEXACT_MATCH
parameter_match_t
enum parameter_match_t
Enumerator
PARAMETER_EXACT_MATCH
PARAMETER_FLOAT_TO_DOUBLE
PARAMETER_INT_TO_FLOAT
PARAMETER_INT_TO_DOUBLE
PARAMETER_OTHER_CONVERSION
Function Documentation
choose_best_inexact_overload()
static ir_function_signature* choose_best_inexact_overload (_mesa_glsl_parse_state * state, const exec_list * actual_parameters, ir_function_signature ** matches, int num_matches) static
References foreach_in_list, is_best_inexact_overload(), PARAMETER_LIST_EXACT_MATCH, PARAMETER_LIST_INEXACT_MATCH, PARAMETER_LIST_NO_MATCH, and parameter_lists_match().
get_parameter_match_type()
static parameter_match_t get_parameter_match_type (const ir_variable * param, const ir_rvalue * actual) static
References PARAMETER_EXACT_MATCH, PARAMETER_FLOAT_TO_DOUBLE, PARAMETER_INT_TO_DOUBLE, PARAMETER_INT_TO_FLOAT, and PARAMETER_OTHER_CONVERSION.
Referenced by is_best_inexact_overload().
is_best_inexact_overload()
static bool is_best_inexact_overload (const exec_list * actual_parameters, ir_function_signature ** matches, int num_matches, ir_function_signature * sig) static
References get_parameter_match_type(), is_better_parameter_match(), and exec_node::next.
Referenced by choose_best_inexact_overload().
is_better_parameter_match()
static bool is_better_parameter_match (parameter_match_t a_match, parameter_match_t b_match) static
References PARAMETER_INT_TO_FLOAT, and PARAMETER_OTHER_CONVERSION.
Referenced by is_best_inexact_overload().
parameter_lists_match()
static parameter_list_match_t parameter_lists_match (_mesa_glsl_parse_state * state, const exec_list * list_a, const exec_list * list_b) static
Check if two parameter lists match.
Parameters
list_a Parameters of the function definition.
list_b Actual parameters passed to the function.
See also
matching_signature()
References exec_node::next, PARAMETER_LIST_EXACT_MATCH, PARAMETER_LIST_INEXACT_MATCH, and PARAMETER_LIST_NO_MATCH.
Referenced by choose_best_inexact_overload().
parameter_lists_match_exact()
static bool parameter_lists_match_exact (const exec_list * list_a, const exec_list * list_b) static
References foreach_in_list, and exec_node::next.