Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_builder_print_visitor.cpp File Reference
#include <inttypes.h>
#include "ir.h"
#include "ir_hierarchical_visitor.h"
#include "ir_builder_print_visitor.h"
#include "compiler/glsl_types.h"
#include "glsl_parser_extras.h"
#include "main/macros.h"
#include "util/hash_table.h"
Data Structures
class ir_builder_print_visitor
Functions
static bool is_simple_operand (const ir_rvalue *ir, unsigned depth=1)
void _mesa_print_builder_for_ir (FILE *f, exec_list *instructions)
Function Documentation
_mesa_print_builder_for_ir()
void _mesa_print_builder_for_ir (FILE * f, exec_list * instructions)
Referenced by standalone_compile_shader().
is_simple_operand()
static bool is_simple_operand (const ir_rvalue * ir, unsigned depth = 1) static
References ir_builder::expr().
Referenced by ir_builder_print_visitor::visit(), ir_builder_print_visitor::visit_enter(), and ir_builder_print_visitor::visit_leave().