Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_reader.cpp File Reference
#include "ir_reader.h"
#include "glsl_parser_extras.h"
#include "compiler/glsl_types.h"
#include "s_expression.h"
Functions
void _mesa_glsl_read_ir (_mesa_glsl_parse_state *state, exec_list *instructions, const char *src, bool scan_for_protos)
static bool always_available (const _mesa_glsl_parse_state *)
Variables
static const bool debug = false
Function Documentation
_mesa_glsl_read_ir()
void _mesa_glsl_read_ir (_mesa_glsl_parse_state * state, exec_list * instructions, const char * src, bool scan_for_protos)
References debug, ir_builder::expr(), foreach_in_list, MATCH, exec_node::next, PARTIAL_MATCH, s_expression::print(), s_expression::read_expression(), ir_builder::sub(), s_list::subexpressions, SX_AS_LIST, SX_AS_SYMBOL, validate_ir_tree(), and s_symbol::value().
Referenced by test_optpass().
always_available()
static bool always_available (const _mesa_glsl_parse_state *) static
References ir_builder::expr(), foreach_in_list, s_number::fvalue(), MATCH, exec_node::next, PARTIAL_MATCH, ir_builder::sub(), s_list::subexpressions, SX_AS_INT, SX_AS_LIST, SX_AS_NUMBER, SX_AS_SYMBOL, s_int::value(), and s_symbol::value().
Variable Documentation
debug
const bool debug = false static
Referenced by _mesa_glsl_read_ir(), and do_common_optimization().