Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_varyings.cpp File Reference
Linker functions related specifically to linking varyings between shader stages.
#include "main/mtypes.h"
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "ir_optimization.h"
#include "linker.h"
#include "link_varyings.h"
#include "main/macros.h"
#include "util/hash_table.h"
#include "program.h"
Data Structures
class tfeedback_candidate_generator
Visitor class that generates tfeedback_candidate structs describing all possible targets of transform feedback.
Namespaces
linker
Functions
static const glsl_type * get_varying_type (const ir_variable *var, gl_shader_stage stage)
Get the varying type stripped of the outermost array if we're processing a stage whose varyings are arrays indexed by a vertex number (such as geometry shader inputs).
static void create_xfb_varying_names (void *mem_ctx, const glsl_type *t, char **name, size_t name_length, unsigned *count, const char *ifc_member_name, const glsl_type *ifc_member_t, char ***varying_names)
static bool process_xfb_layout_qualifiers (void *mem_ctx, const gl_linked_shader *sh, struct gl_shader_program *prog, unsigned *num_tfeedback_decls, char ***varying_names)
static bool anonymous_struct_type_matches (const glsl_type *output_type, const glsl_type *to_match)
static void cross_validate_types_and_qualifiers (struct gl_shader_program *prog, const ir_variable *input, const ir_variable *output, gl_shader_stage consumer_stage, gl_shader_stage producer_stage)
Validate the types and qualifiers of an output from one stage against the matching input to another stage.
static void cross_validate_front_and_back_color (struct gl_shader_program *prog, const ir_variable *input, const ir_variable *front_color, const ir_variable *back_color, gl_shader_stage consumer_stage, gl_shader_stage producer_stage)
Validate front and back color outputs against single color input.
void cross_validate_outputs_to_inputs (struct gl_shader_program *prog, gl_linked_shader *producer, gl_linked_shader *consumer)
Validate that outputs from one stage match inputs of another.
static void remove_unused_shader_inputs_and_outputs (bool is_separate_shader_object, gl_linked_shader *sh, enum ir_variable_mode mode)
Demote shader inputs and outputs that are not used in other stages, and remove them via dead code elimination.
static bool parse_tfeedback_decls (struct gl_context *ctx, struct gl_shader_program *prog, const void *mem_ctx, unsigned num_names, char **varying_names, tfeedback_decl *decls)
Parse all the transform feedback declarations that were passed to glTransformFeedbackVaryings() and store them in tfeedback_decl objects.
static int cmp_xfb_offset (const void *x_generic, const void *y_generic)
static bool store_tfeedback_info (struct gl_context *ctx, struct gl_shader_program *prog, unsigned num_tfeedback_decls, tfeedback_decl *tfeedback_decls, bool has_xfb_qualifiers)
Store transform feedback location assignments into prog->sh.LinkedTransformFeedback based on the data stored in tfeedback_decls.
static bool var_counts_against_varying_limit (gl_shader_stage stage, const ir_variable *var)
Is the given variable a varying variable to be counted against the limit in ctx->Const.MaxVarying? This includes variables such as texcoords, colors and generic varyings, but excludes variables such as gl_FrontFacing and gl_FragCoord.
void linker::populate_consumer_input_sets (void *mem_ctx, exec_list *ir, hash_table *consumer_inputs, hash_table *consumer_interface_inputs, ir_variable *consumer_inputs_with_locations[VARYING_SLOT_TESS_MAX])
ir_variable * linker::get_matching_input (void *mem_ctx, const ir_variable *output_var, hash_table *consumer_inputs, hash_table *consumer_interface_inputs, ir_variable *consumer_inputs_with_locations[VARYING_SLOT_TESS_MAX])
Find a variable from the consumer that "matches" the specified variable.
static int io_variable_cmp (const void *_a, const void *_b)
static void canonicalize_shader_io (exec_list *ir, enum ir_variable_mode io_mode)
Sort the shader IO variables into canonical order.
static uint64_t reserved_varying_slot (struct gl_linked_shader *stage, ir_variable_mode io_mode)
Generate a bitfield map of the explicit locations for shader varyings.
static bool assign_varying_locations (struct gl_context *ctx, void *mem_ctx, struct gl_shader_program *prog, gl_linked_shader *producer, gl_linked_shader *consumer, unsigned num_tfeedback_decls, tfeedback_decl *tfeedback_decls, const uint64_t reserved_slots)
Assign locations for all variables that are produced in one pipeline stage (the "producer") and consumed in the next stage (the "consumer").
bool check_against_output_limit (struct gl_context *ctx, struct gl_shader_program *prog, gl_linked_shader *producer, unsigned num_explicit_locations)
bool check_against_input_limit (struct gl_context *ctx, struct gl_shader_program *prog, gl_linked_shader *consumer, unsigned num_explicit_locations)
bool link_varyings (struct gl_shader_program *prog, unsigned first, unsigned last, struct gl_context *ctx, void *mem_ctx)
Detailed Description
Linker functions related specifically to linking varyings between shader stages.
Function Documentation
anonymous_struct_type_matches()
static bool anonymous_struct_type_matches (const glsl_type * output_type, const glsl_type * to_match) static
Referenced by cross_validate_types_and_qualifiers().
assign_varying_locations()
static bool assign_varying_locations (struct gl_context * ctx, void * mem_ctx, struct gl_shader_program * prog, gl_linked_shader * producer, gl_linked_shader * consumer, unsigned num_tfeedback_decls, tfeedback_decl * tfeedback_decls, const uint64_t reserved_slots) static
Assign locations for all variables that are produced in one pipeline stage (the "producer") and consumed in the next stage (the "consumer").
Variables produced by the producer may also be consumed by transform feedback.
Parameters
num_tfeedback_decls is the number of declarations indicating variables that may be consumed by transform feedback.
tfeedback_decls is a pointer to an array of tfeedback_decl objects representing the result of parsing the strings passed to glTransformFeedbackVaryings(). assign_location() will be called for each of these objects that matches one of the outputs of the producer.
When num_tfeedback_decls is nonzero, it is permissible for the consumer to be NULL. In this case, varying locations are assigned solely based on the requirements of transform feedback.
References tfeedback_decl::assign_location(), canonicalize_shader_io(), tfeedback_decl::find_candidate(), foreach_in_list, linker::get_matching_input(), tfeedback_decl::is_varying(), linker_error(), linker_warning(), lower_packed_varyings(), linker::populate_consumer_input_sets(), tfeedback_candidate_generator::process(), remove_unused_shader_inputs_and_outputs(), and tfeedback_candidate::toplevel_var.
Referenced by link_varyings().
canonicalize_shader_io()
static void canonicalize_shader_io (exec_list * ir, enum ir_variable_mode io_mode) static
Sort the shader IO variables into canonical order.
References foreach_in_list, and io_variable_cmp().
Referenced by assign_varying_locations().
check_against_input_limit()
bool check_against_input_limit (struct gl_context * ctx, struct gl_shader_program * prog, gl_linked_shader * consumer, unsigned num_explicit_locations)
References foreach_in_list, linker_error(), and var_counts_against_varying_limit().
Referenced by link_varyings().
check_against_output_limit()
bool check_against_output_limit (struct gl_context * ctx, struct gl_shader_program * prog, gl_linked_shader * producer, unsigned num_explicit_locations)
References foreach_in_list, linker_error(), and var_counts_against_varying_limit().
Referenced by link_varyings().
cmp_xfb_offset()
static int cmp_xfb_offset (const void * x_generic, const void * y_generic) static
References tfeedback_decl::get_buffer(), and tfeedback_decl::get_offset().
Referenced by store_tfeedback_info().
create_xfb_varying_names()
static void create_xfb_varying_names (void * mem_ctx, const glsl_type * t, char ** name, size_t name_length, unsigned * count, const char * ifc_member_name, const glsl_type * ifc_member_t, char *** varying_names) static
Referenced by process_xfb_layout_qualifiers().
cross_validate_front_and_back_color()
static void cross_validate_front_and_back_color (struct gl_shader_program * prog, const ir_variable * input, const ir_variable * front_color, const ir_variable * back_color, gl_shader_stage consumer_stage, gl_shader_stage producer_stage) static
Validate front and back color outputs against single color input.
References cross_validate_types_and_qualifiers().
Referenced by cross_validate_outputs_to_inputs().
cross_validate_outputs_to_inputs()
void cross_validate_outputs_to_inputs (struct gl_shader_program * prog, gl_linked_shader * producer, gl_linked_shader * consumer)
Validate that outputs from one stage match inputs of another.
References glsl_symbol_table::add_variable(), cross_validate_front_and_back_color(), cross_validate_types_and_qualifiers(), foreach_in_list, glsl_symbol_table::get_variable(), get_varying_type(), and linker_error().
Referenced by tfeedback_decl::get_location(), and link_shaders().
cross_validate_types_and_qualifiers()
static void cross_validate_types_and_qualifiers (struct gl_shader_program * prog, const ir_variable * input, const ir_variable * output, gl_shader_stage consumer_stage, gl_shader_stage producer_stage) static
Validate the types and qualifiers of an output from one stage against the matching input to another stage.
References anonymous_struct_type_matches(), interpolation_string(), and linker_error().
Referenced by cross_validate_front_and_back_color(), and cross_validate_outputs_to_inputs().
get_varying_type()
static const glsl_type* get_varying_type (const ir_variable * var, gl_shader_stage stage) static
Get the varying type stripped of the outermost array if we're processing a stage whose varyings are arrays indexed by a vertex number (such as geometry shader inputs).
Referenced by cross_validate_outputs_to_inputs(), reserved_varying_slot(), and store_tfeedback_info().
io_variable_cmp()
static int io_variable_cmp (const void * _a, const void * _b) static
Referenced by canonicalize_shader_io().
link_varyings()
bool link_varyings (struct gl_shader_program * prog, unsigned first, unsigned last, struct gl_context * ctx, void * mem_ctx)
References assign_varying_locations(), check_against_input_limit(), check_against_output_limit(), do_dead_builtin_varyings(), linker_error(), parse_tfeedback_decls(), process_xfb_layout_qualifiers(), remove_unused_shader_inputs_and_outputs(), reserved_varying_slot(), and store_tfeedback_info().
Referenced by tfeedback_decl::get_location(), and link_varyings_and_uniforms().
parse_tfeedback_decls()
static bool parse_tfeedback_decls (struct gl_context * ctx, struct gl_shader_program * prog, const void * mem_ctx, unsigned num_names, char ** varying_names, tfeedback_decl * decls) static
Parse all the transform feedback declarations that were passed to glTransformFeedbackVaryings() and store them in tfeedback_decl objects.
If an error occurs, the error is reported through linker_error() and false is returned.
References tfeedback_decl::init(), tfeedback_decl::is_same(), tfeedback_decl::is_varying(), and linker_error().
Referenced by link_varyings().
process_xfb_layout_qualifiers()
static bool process_xfb_layout_qualifiers (void * mem_ctx, const gl_linked_shader * sh, struct gl_shader_program * prog, unsigned * num_tfeedback_decls, char *** varying_names) static
References create_xfb_varying_names(), and foreach_in_list.
Referenced by link_varyings().
remove_unused_shader_inputs_and_outputs()
static void remove_unused_shader_inputs_and_outputs (bool is_separate_shader_object, gl_linked_shader * sh, enum ir_variable_mode mode) static
Demote shader inputs and outputs that are not used in other stages, and remove them via dead code elimination.
References do_dead_code(), and foreach_in_list.
Referenced by assign_varying_locations(), and link_varyings().
reserved_varying_slot()
static uint64_t reserved_varying_slot (struct gl_linked_shader * stage, ir_variable_mode io_mode) static
Generate a bitfield map of the explicit locations for shader varyings.
Note: For Tessellation shaders we are sitting right on the limits of the 64 bit map. Per-vertex and per-patch both have separate location domains with a max of MAX_VARYING.
References foreach_in_list, and get_varying_type().
Referenced by link_varyings().
store_tfeedback_info()
static bool store_tfeedback_info (struct gl_context * ctx, struct gl_shader_program * prog, unsigned num_tfeedback_decls, tfeedback_decl * tfeedback_decls, bool has_xfb_qualifiers) static
Store transform feedback location assignments into prog->sh.LinkedTransformFeedback based on the data stored in tfeedback_decls.
If an error occurs, the error is reported through linker_error() and false is returned.
References cmp_xfb_offset(), tfeedback_decl::get_buffer(), tfeedback_decl::get_num_outputs(), tfeedback_decl::get_stream_id(), get_varying_type(), tfeedback_decl::is_next_buffer_separator(), tfeedback_decl::is_varying(), tfeedback_decl::is_varying_written(), linker_error(), tfeedback_decl::name(), tfeedback_decl::num_components(), and tfeedback_decl::store().
Referenced by link_varyings().
var_counts_against_varying_limit()
static bool var_counts_against_varying_limit (gl_shader_stage stage, const ir_variable * var) static
Is the given variable a varying variable to be counted against the limit in ctx->Const.MaxVarying? This includes variables such as texcoords, colors and generic varyings, but excludes variables such as gl_FrontFacing and gl_FragCoord.
Referenced by check_against_input_limit(), and check_against_output_limit().