Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_interface_blocks.cpp File Reference
Linker support for GLSL's interface blocks.
#include "ir.h"
#include "glsl_symbol_table.h"
#include "linker.h"
#include "main/macros.h"
#include "util/hash_table.h"
Functions
void validate_intrastage_interface_blocks (struct gl_shader_program *prog, const gl_shader **shader_list, unsigned num_shaders)
static bool is_builtin_gl_in_block (ir_variable *var, int consumer_stage)
void validate_interstage_inout_blocks (struct gl_shader_program *prog, const gl_linked_shader *producer, const gl_linked_shader *consumer)
void validate_interstage_uniform_blocks (struct gl_shader_program *prog, gl_linked_shader **stages)
Detailed Description
Linker support for GLSL's interface blocks.
Function Documentation
is_builtin_gl_in_block()
static bool is_builtin_gl_in_block (ir_variable * var, int consumer_stage) static
Referenced by validate_interstage_inout_blocks().
validate_interstage_inout_blocks()
void validate_interstage_inout_blocks (struct gl_shader_program * prog, const gl_linked_shader * producer, const gl_linked_shader * consumer)
References foreach_in_list, is_builtin_gl_in_block(), and linker_error().
Referenced by link_shaders().
validate_interstage_uniform_blocks()
void validate_interstage_uniform_blocks (struct gl_shader_program * prog, gl_linked_shader ** stages)
References foreach_in_list, and linker_error().
Referenced by link_shaders().
validate_intrastage_interface_blocks()
void validate_intrastage_interface_blocks (struct gl_shader_program * prog, const gl_shader ** shader_list, unsigned num_shaders)
References foreach_in_list, and linker_error().
Referenced by link_intrastage_shaders().