Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_uniforms.cpp File Reference
Assign locations for GLSL uniforms.
#include "main/core.h"
#include "ir.h"
#include "linker.h"
#include "ir_uniform.h"
#include "glsl_symbol_table.h"
#include "program.h"
#include "util/string_to_uint_map.h"
#include "ir_array_refcount.h"
Data Structures
class parcel_out_uniform_storage
Class to help parcel out pieces of backing storage to uniforms.
Macros
#define UNMAPPED_UNIFORM_LOC ~0u
Used by linker to indicate uniforms that have no location set.
Functions
unsigned values_for_type (const glsl_type *type)
Count the backing storage requirements for a type.
static bool variable_is_referenced (ir_array_refcount_visitor &v, ir_variable *var)
static void link_update_uniform_buffer_variables (struct gl_linked_shader *shader, unsigned stage)
Walks the IR and update the references to uniform blocks in the ir_variables to point at linked shader's list (previously, they would point at the uniform block list in one of the pre-linked shaders).
static void assign_hidden_uniform_slot_id (const char *name, unsigned hidden_id, void *closure)
Combine the hidden uniform hash map with the uniform hash map so that the hidden uniforms will be given indicies at the end of the uniform storage array.
static int find_empty_block (struct gl_shader_program *prog, struct gl_uniform_storage *uniform)
Search through the list of empty blocks to find one that fits the current uniform.
static void link_setup_uniform_remap_tables (struct gl_context *ctx, struct gl_shader_program *prog)
static void link_assign_uniform_storage (struct gl_context *ctx, struct gl_shader_program *prog, const unsigned num_data_slots)
void link_assign_uniform_locations (struct gl_shader_program *prog, struct gl_context *ctx)
Detailed Description
Assign locations for GLSL uniforms.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Macro Definition Documentation
UNMAPPED_UNIFORM_LOC
#define UNMAPPED_UNIFORM_LOC ~0u
Used by linker to indicate uniforms that have no location set.
Referenced by link_setup_uniform_remap_tables().
Function Documentation
assign_hidden_uniform_slot_id()
static void assign_hidden_uniform_slot_id (const char * name, unsigned hidden_id, void * closure) static
Combine the hidden uniform hash map with the uniform hash map so that the hidden uniforms will be given indicies at the end of the uniform storage array.
Referenced by link_assign_uniform_locations().
find_empty_block()
static int find_empty_block (struct gl_shader_program * prog, struct gl_uniform_storage * uniform) static
Search through the list of empty blocks to find one that fits the current uniform.
References gl_uniform_storage::array_elements, exec_node_remove(), and foreach_list_typed.
Referenced by link_setup_uniform_remap_tables().
link_assign_uniform_locations()
void link_assign_uniform_locations (struct gl_shader_program * prog, struct gl_context * ctx)
References assign_hidden_uniform_slot_id(), foreach_in_list, link_assign_uniform_storage(), and link_update_uniform_buffer_variables().
Referenced by link_and_validate_uniforms().
link_assign_uniform_storage()
static void link_assign_uniform_storage (struct gl_context * ctx, struct gl_shader_program * prog, const unsigned num_data_slots) static
References foreach_in_list, link_set_uniform_initializers(), link_setup_uniform_remap_tables(), parcel_out_uniform_storage::set_and_process(), parcel_out_uniform_storage::shader_samplers_used, parcel_out_uniform_storage::shader_shadow_samplers, parcel_out_uniform_storage::start_shader(), parcel_out_uniform_storage::targets, and parcel_out_uniform_storage::values.
Referenced by link_assign_uniform_locations().
link_setup_uniform_remap_tables()
static void link_setup_uniform_remap_tables (struct gl_context * ctx, struct gl_shader_program * prog) static
References find_empty_block(), INACTIVE_UNIFORM_EXPLICIT_LOCATION, linker_error(), and UNMAPPED_UNIFORM_LOC.
Referenced by link_assign_uniform_storage().
link_update_uniform_buffer_variables()
static void link_update_uniform_buffer_variables (struct gl_linked_shader * shader, unsigned stage) static
Walks the IR and update the references to uniform blocks in the ir_variables to point at linked shader's list (previously, they would point at the uniform block list in one of the pre-linked shaders).
References foreach_in_list, ir_array_refcount_visitor::get_variable_entry(), ir_array_refcount_entry::is_linearized_index_referenced(), ir_array_refcount_entry::is_referenced, and variable_is_referenced().
Referenced by link_assign_uniform_locations().
values_for_type()
unsigned values_for_type (const glsl_type * type)
Count the backing storage requirements for a type.
Referenced by read_uniforms(), program_resource_visitor::set_record_array_count(), and write_uniforms().
variable_is_referenced()
static bool variable_is_referenced (ir_array_refcount_visitor & v, ir_variable * var) static
References ir_array_refcount_visitor::get_variable_entry(), and ir_array_refcount_entry::is_referenced.
Referenced by link_update_uniform_buffer_variables().