Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
linker.cpp File Reference
GLSL linker implementation.
#include <ctype.h>
#include "util/strndup.h"
#include "main/core.h"
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "ir.h"
#include "program.h"
#include "program/prog_instruction.h"
#include "program/program.h"
#include "util/mesa-sha1.h"
#include "util/set.h"
#include "util/string_to_uint_map.h"
#include "linker.h"
#include "link_varyings.h"
#include "ir_optimization.h"
#include "ir_rvalue_visitor.h"
#include "ir_uniform.h"
#include "builtin_functions.h"
#include "shader_cache.h"
#include "main/shaderobj.h"
#include "main/enums.h"
Data Structures
class array_sizing_visitor
This class is only used in link_intrastage_shaders() below but declaring it inside that function leads to compiler warnings with some versions of gcc.
Functions
void linker_error (gl_shader_program *prog, const char *fmt,...)
void linker_warning (gl_shader_program *prog, const char *fmt,...)
long parse_program_resource_name (const GLchar *name, const GLchar **out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
void link_invalidate_variable_locations (exec_list *ir)
static void analyze_clip_cull_usage (struct gl_shader_program *prog, struct gl_linked_shader *shader, struct gl_context *ctx, GLuint *clip_distance_array_size, GLuint *cull_distance_array_size)
Set clip_distance_array_size based and cull_distance_array_size on the given shader.
void validate_vertex_shader_executable (struct gl_shader_program *prog, struct gl_linked_shader *shader, struct gl_context *ctx)
Verify that a vertex shader executable meets all semantic requirements.
void validate_tess_eval_shader_executable (struct gl_shader_program *prog, struct gl_linked_shader *shader, struct gl_context *ctx)
void validate_fragment_shader_executable (struct gl_shader_program *prog, struct gl_linked_shader *shader)
Verify that a fragment shader executable meets all semantic requirements.
void validate_geometry_shader_executable (struct gl_shader_program *prog, struct gl_linked_shader *shader, struct gl_context *ctx)
Verify that a geometry shader executable meets all semantic requirements.
static void validate_geometry_shader_emissions (struct gl_context *ctx, struct gl_shader_program *prog)
Check if geometry shaders emit to non-zero streams and do corresponding validations.
bool validate_intrastage_arrays (struct gl_shader_program *prog, ir_variable *const var, ir_variable *const existing)
void cross_validate_globals (struct gl_shader_program *prog, struct exec_list *ir, glsl_symbol_table *variables, bool uniforms_only)
Perform validation of global variables used across multiple shaders.
void cross_validate_uniforms (struct gl_shader_program *prog)
Perform validation of uniforms used across multiple shader stages.
static bool interstage_cross_validate_uniform_blocks (struct gl_shader_program *prog, bool validate_ssbo)
Accumulates the array of buffer blocks and checks that all definitions of blocks agree on their contents.
static void populate_symbol_table (gl_linked_shader *sh)
Populates a shaders symbol table with all global declarations.
void remap_variables (ir_instruction *inst, struct gl_linked_shader *target, hash_table *temps)
Remap variables referenced in an instruction tree.
exec_node * move_non_declarations (exec_list *instructions, exec_node *last, bool make_copies, gl_linked_shader *target)
Move non-declarations from one instruction stream to another.
static bool validate_xfb_buffer_stride (struct gl_context *ctx, unsigned idx, struct gl_shader_program *prog)
static void link_xfb_stride_layout_qualifiers (struct gl_context *ctx, struct gl_shader_program *prog, struct gl_linked_shader *linked_shader, struct gl_shader **shader_list, unsigned num_shaders)
Check for conflicting xfb_stride default qualifiers and store buffer stride for later use.
static void link_tcs_out_layout_qualifiers (struct gl_shader_program *prog, struct gl_program *gl_prog, struct gl_shader **shader_list, unsigned num_shaders)
Performs the cross-validation of tessellation control shader vertices and layout qualifiers for the attached tessellation control shaders, and propagates them to the linked TCS and linked shader program.
static void link_tes_in_layout_qualifiers (struct gl_shader_program *prog, struct gl_program *gl_prog, struct gl_shader **shader_list, unsigned num_shaders)
Performs the cross-validation of tessellation evaluation shader primitive type, vertex spacing, ordering and point_mode layout qualifiers for the attached tessellation evaluation shaders, and propagates them to the linked TES and linked shader program.
static void link_fs_inout_layout_qualifiers (struct gl_shader_program *prog, struct gl_linked_shader *linked_shader, struct gl_shader **shader_list, unsigned num_shaders)
Performs the cross-validation of layout qualifiers specified in redeclaration of gl_FragCoord for the attached fragment shaders, and propagates them to the linked FS and linked shader program.
static void link_gs_inout_layout_qualifiers (struct gl_shader_program *prog, struct gl_program *gl_prog, struct gl_shader **shader_list, unsigned num_shaders)
Performs the cross-validation of geometry shader max_vertices and primitive type layout qualifiers for the attached geometry shaders, and propagates them to the linked GS and linked shader program.
static void link_cs_input_layout_qualifiers (struct gl_shader_program *prog, struct gl_program *gl_prog, struct gl_shader **shader_list, unsigned num_shaders)
Perform cross-validation of compute shader local_size_{x,y,z} layout qualifiers for the attached compute shaders, and propagate them to the linked CS and linked shader program.
struct gl_linked_shader * link_intrastage_shaders (void *mem_ctx, struct gl_context *ctx, struct gl_shader_program *prog, struct gl_shader **shader_list, unsigned num_shaders, bool allow_missing_main)
Combine a group of shaders for a single stage to generate a linked shader.
static void update_array_sizes (struct gl_shader_program *prog)
Update the sizes of linked shader uniform arrays to the maximum array index used.
static void resize_tes_inputs (struct gl_context *ctx, struct gl_shader_program *prog)
Resize tessellation evaluation per-vertex inputs to the size of tessellation control per-vertex outputs.
int find_available_slots (unsigned used_mask, unsigned needed_count)
Find a contiguous set of available bits in a bitmask.
bool assign_attribute_or_color_locations (void *mem_ctx, gl_shader_program *prog, struct gl_constants *constants, unsigned target_index)
Assign locations for either VS inputs or FS outputs.
static void match_explicit_outputs_to_inputs (gl_linked_shader *producer, gl_linked_shader *consumer)
Match explicit locations of outputs to inputs and deactivate the unmatch flag if found so we don't optimise them away.
static void store_fragdepth_layout (struct gl_shader_program *prog)
Store the gl_FragDepth layout in the gl_shader_program struct.
static void check_resources (struct gl_context *ctx, struct gl_shader_program *prog)
Validate the resources used by a program versus the implementation limits.
static void link_calculate_subroutine_compat (struct gl_shader_program *prog)
static void check_subroutine_resources (struct gl_shader_program *prog)
static void check_image_resources (struct gl_context *ctx, struct gl_shader_program *prog)
Validate shader image resources.
static int reserve_explicit_locations (struct gl_shader_program *prog, string_to_uint_map *map, ir_variable *var)
Initializes explicit location slots to INACTIVE_UNIFORM_EXPLICIT_LOCATION for a variable, checks for overlaps between other uniforms using explicit locations.
static bool reserve_subroutine_explicit_locations (struct gl_shader_program *prog, struct gl_program *p, ir_variable *var)
static void check_explicit_uniform_locations (struct gl_context *ctx, struct gl_shader_program *prog)
Check and reserve all explicit uniform locations, called before any optimizations happen to handle also inactive uniforms and inactive array elements that may get trimmed away.
static bool should_add_buffer_variable (struct gl_shader_program *shProg, GLenum type, const char *name)
static bool add_program_resource (struct gl_shader_program *prog, struct set *resource_set, GLenum type, const void *data, uint8_t stages)
static bool included_in_packed_varying (ir_variable *var, const char *name)
static uint8_t build_stageref (struct gl_shader_program *shProg, const char *name, unsigned mode)
Function builds a stage reference bitmask from variable name.
static gl_shader_variable * create_shader_variable (struct gl_shader_program *shProg, const ir_variable *in, const char *name, const glsl_type *type, const glsl_type *interface_type, bool use_implicit_location, int location, const glsl_type *outermost_struct_type)
Create gl_shader_variable from ir_variable class.
static bool add_shader_variable (const struct gl_context *ctx, struct gl_shader_program *shProg, struct set *resource_set, unsigned stage_mask, GLenum programInterface, ir_variable *var, const char *name, const glsl_type *type, bool use_implicit_location, int location, const glsl_type *outermost_struct_type=NULL)
static bool add_interface_variables (const struct gl_context *ctx, struct gl_shader_program *shProg, struct set *resource_set, unsigned stage, GLenum programInterface)
static bool add_packed_varyings (const struct gl_context *ctx, struct gl_shader_program *shProg, struct set *resource_set, int stage, GLenum type)
static bool add_fragdata_arrays (const struct gl_context *ctx, struct gl_shader_program *shProg, struct set *resource_set)
static char * get_top_level_name (const char *name)
static char * get_var_name (const char *name)
static bool is_top_level_shader_storage_block_member (const char *name, const char *interface_name, const char *field_name)
static int get_array_size (struct gl_uniform_storage *uni, const glsl_struct_field *field, char *interface_name, char *var_name)
static int get_array_stride (struct gl_uniform_storage *uni, const glsl_type *interface, const glsl_struct_field *field, char *interface_name, char *var_name)
static void calculate_array_size_and_stride (struct gl_shader_program *shProg, struct gl_uniform_storage *uni)
void build_program_resource_list (struct gl_context *ctx, struct gl_shader_program *shProg)
Builds up a list of program resources that point to existing resource data.
static bool validate_sampler_array_indexing (struct gl_context *ctx, struct gl_shader_program *prog)
This check is done to make sure we allow only constant expression indexing and "constant-index-expression" (indexing with an expression that includes loop induction variable).
static void link_assign_subroutine_types (struct gl_shader_program *prog)
static void set_always_active_io (exec_list *ir, ir_variable_mode io_mode)
static void disable_varying_optimizations_for_sso (struct gl_shader_program *prog)
When separate shader programs are enabled, only input/outputs between the stages of a multi-stage separate program can be safely removed from the shader interface.
static void link_and_validate_uniforms (struct gl_context *ctx, struct gl_shader_program *prog)
static bool link_varyings_and_uniforms (unsigned first, unsigned last, struct gl_context *ctx, struct gl_shader_program *prog, void *mem_ctx)
static void linker_optimisation_loop (struct gl_context *ctx, exec_list *ir, unsigned stage)
void link_shaders (struct gl_context *ctx, struct gl_shader_program *prog)
Detailed Description
GLSL linker implementation.
Given a set of shaders that are to be linked to generate a final program, there are three distinct stages.
In the first stage shaders are partitioned into groups based on the shader type. All shaders of a particular type (e.g., vertex shaders) are linked together.
Undefined references in each shader are resolve to definitions in another shader.
Types and qualifiers of uniforms, outputs, and global variables defined in multiple shaders with the same name are verified to be the same.
Initializers for uniforms and global variables defined in multiple shaders with the same name are verified to be the same.
The result, in the terminology of the GLSL spec, is a set of shader executables for each processing unit.
After the first stage is complete, a series of semantic checks are performed on each of the shader executables.
Each shader executable must define a main function.
Each vertex shader executable must write to gl_Position.
Each fragment shader executable must write to either gl_FragData or gl_FragColor.
In the final stage individual shader executables are linked to create a complete exectuable.
Types of uniforms defined in multiple shader stages with the same name are verified to be the same.
Initializers for uniforms defined in multiple shader stages with the same name are verified to be the same.
Types and qualifiers of outputs defined in one stage are verified to be the same as the types and qualifiers of inputs defined with the same name in a later stage.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
add_fragdata_arrays()
static bool add_fragdata_arrays (const struct gl_context * ctx, struct gl_shader_program * shProg, struct set * resource_set) static
References add_shader_variable(), and foreach_in_list.
Referenced by build_program_resource_list().
add_interface_variables()
static bool add_interface_variables (const struct gl_context * ctx, struct gl_shader_program * shProg, struct set * resource_set, unsigned stage, GLenum programInterface) static
References add_shader_variable(), and foreach_in_list.
Referenced by build_program_resource_list().
add_packed_varyings()
static bool add_packed_varyings (const struct gl_context * ctx, struct gl_shader_program * shProg, struct set * resource_set, int stage, GLenum type) static
References add_shader_variable(), build_stageref(), and foreach_in_list.
Referenced by build_program_resource_list().
add_program_resource()
static bool add_program_resource (struct gl_shader_program * prog, struct set * resource_set, GLenum type, const void * data, uint8_t stages) static
References linker_error().
Referenced by add_shader_variable(), and build_program_resource_list().
add_shader_variable()
static bool add_shader_variable (const struct gl_context * ctx, struct gl_shader_program * shProg, struct set * resource_set, unsigned stage_mask, GLenum programInterface, ir_variable * var, const char * name, const glsl_type * type, bool use_implicit_location, int location, const glsl_type * outermost_struct_type = NULL) static
References add_program_resource(), and create_shader_variable().
Referenced by add_fragdata_arrays(), add_interface_variables(), and add_packed_varyings().
analyze_clip_cull_usage()
static void analyze_clip_cull_usage (struct gl_shader_program * prog, struct gl_linked_shader * shader, struct gl_context * ctx, GLuint * clip_distance_array_size, GLuint * cull_distance_array_size) static
Set clip_distance_array_size based and cull_distance_array_size on the given shader.
Also check for errors based on incorrect usage of gl_ClipVertex and gl_ClipDistance and gl_CullDistance. Additionally test whether the arrays gl_ClipDistance and gl_CullDistance exceed the maximum size defined by gl_MaxCombinedClipAndCullDistances.
Return false if an error was reported.
References linker_error().
Referenced by validate_geometry_shader_executable(), validate_tess_eval_shader_executable(), and validate_vertex_shader_executable().
assign_attribute_or_color_locations()
bool assign_attribute_or_color_locations (void * mem_ctx, gl_shader_program * prog, struct gl_constants * constants, unsigned target_index)
Assign locations for either VS inputs or FS outputs.
Parameters
mem_ctx Temporary ralloc context used for linking
prog Shader program whose variables need locations assigned
constants Driver specific constant values for the program.
target_index Selector for the program target to receive location assignmnets. Must be either MESA_SHADER_VERTEX or MESA_SHADER_FRAGMENT.
Returns
If locations are successfully assigned, true is returned. Otherwise an error is emitted to the shader link log and false is returned.
References find_available_slots(), foreach_in_list, linker_error(), and linker_warning().
Referenced by link_varyings_and_uniforms().
build_program_resource_list()
void build_program_resource_list (struct gl_context * ctx, struct gl_shader_program * shProg)
Builds up a list of program resources that point to existing resource data.
References add_fragdata_arrays(), add_interface_variables(), add_packed_varyings(), add_program_resource(), build_stageref(), calculate_array_size_and_stride(), and should_add_buffer_variable().
build_stageref()
static uint8_t build_stageref (struct gl_shader_program * shProg, const char * name, unsigned mode) static
Function builds a stage reference bitmask from variable name.
References foreach_in_list, and included_in_packed_varying().
Referenced by add_packed_varyings(), and build_program_resource_list().
calculate_array_size_and_stride()
static void calculate_array_size_and_stride (struct gl_shader_program * shProg, struct gl_uniform_storage * uni) static
References gl_uniform_storage::block_index, foreach_in_list, get_array_size(), get_array_stride(), get_top_level_name(), get_var_name(), gl_uniform_storage::is_shader_storage, linker_error(), gl_uniform_storage::name, gl_uniform_storage::top_level_array_size, and gl_uniform_storage::top_level_array_stride.
Referenced by build_program_resource_list().
check_explicit_uniform_locations()
static void check_explicit_uniform_locations (struct gl_context * ctx, struct gl_shader_program * prog) static
Check and reserve all explicit uniform locations, called before any optimizations happen to handle also inactive uniforms and inactive array elements that may get trimmed away.
References exec_list_push_tail(), foreach_in_list, empty_uniform_block::link, linker_error(), reserve_explicit_locations(), reserve_subroutine_explicit_locations(), ir_builder::ret(), empty_uniform_block::slots, and empty_uniform_block::start.
Referenced by link_shaders().
check_image_resources()
static void check_image_resources (struct gl_context * ctx, struct gl_shader_program * prog) static
Validate shader image resources.
References foreach_in_list, and linker_error().
Referenced by link_and_validate_uniforms().
check_resources()
static void check_resources (struct gl_context * ctx, struct gl_shader_program * prog) static
Validate the resources used by a program versus the implementation limits.
References linker_error(), and linker_warning().
Referenced by link_and_validate_uniforms().
check_subroutine_resources()
static void check_subroutine_resources (struct gl_shader_program * prog) static
References linker_error().
Referenced by link_and_validate_uniforms().
create_shader_variable()
static gl_shader_variable* create_shader_variable (struct gl_shader_program * shProg, const ir_variable * in, const char * name, const glsl_type * type, const glsl_type * interface_type, bool use_implicit_location, int location, const glsl_type * outermost_struct_type) static
Create gl_shader_variable from ir_variable class.
Referenced by add_shader_variable().
cross_validate_globals()
void cross_validate_globals (struct gl_shader_program * prog, struct exec_list * ir, glsl_symbol_table * variables, bool uniforms_only)
Perform validation of global variables used across multiple shaders.
References glsl_symbol_table::add_variable(), foreach_in_list, glsl_symbol_table::get_variable(), linker_error(), mode_string(), glsl_symbol_table::replace_variable(), and validate_intrastage_arrays().
Referenced by cross_validate_uniforms(), and link_intrastage_shaders().
cross_validate_uniforms()
void cross_validate_uniforms (struct gl_shader_program * prog)
Perform validation of uniforms used across multiple shader stages.
References cross_validate_globals().
Referenced by link_shaders().
disable_varying_optimizations_for_sso()
static void disable_varying_optimizations_for_sso (struct gl_shader_program * prog) static
When separate shader programs are enabled, only input/outputs between the stages of a multi-stage separate program can be safely removed from the shader interface.
Other inputs/outputs must remain active.
References set_always_active_io().
Referenced by link_shaders().
find_available_slots()
int find_available_slots (unsigned used_mask, unsigned needed_count)
Find a contiguous set of available bits in a bitmask.
Parameters
used_mask Bits representing used (1) and unused (0) locations
needed_count Number of contiguous bits needed.
Returns
Base location of the available bits on success or -1 on failure.
Referenced by assign_attribute_or_color_locations().
get_array_size()
static int get_array_size (struct gl_uniform_storage * uni, const glsl_struct_field * field, char * interface_name, char * var_name) static
References is_top_level_shader_storage_block_member(), and gl_uniform_storage::name.
Referenced by calculate_array_size_and_stride().
get_array_stride()
static int get_array_stride (struct gl_uniform_storage * uni, const glsl_type * interface, const glsl_struct_field * field, char * interface_name, char * var_name) static
References is_top_level_shader_storage_block_member(), and gl_uniform_storage::name.
Referenced by calculate_array_size_and_stride().
get_top_level_name()
static char* get_top_level_name (const char * name) static
Referenced by calculate_array_size_and_stride().
get_var_name()
static char* get_var_name (const char * name) static
Referenced by calculate_array_size_and_stride().
included_in_packed_varying()
static bool included_in_packed_varying (ir_variable * var, const char * name) static
Referenced by build_stageref().
interstage_cross_validate_uniform_blocks()
static bool interstage_cross_validate_uniform_blocks (struct gl_shader_program * prog, bool validate_ssbo) static
Accumulates the array of buffer blocks and checks that all definitions of blocks agree on their contents.
References link_cross_validate_uniform_block(), and linker_error().
Referenced by link_shaders().
is_top_level_shader_storage_block_member()
static bool is_top_level_shader_storage_block_member (const char * name, const char * interface_name, const char * field_name) static
Referenced by get_array_size(), and get_array_stride().
link_and_validate_uniforms()
static void link_and_validate_uniforms (struct gl_context * ctx, struct gl_shader_program * prog) static
References check_image_resources(), check_resources(), check_subroutine_resources(), link_assign_atomic_counter_resources(), link_assign_uniform_locations(), link_calculate_subroutine_compat(), link_check_atomic_counter_resources(), and update_array_sizes().
Referenced by link_varyings_and_uniforms().
link_assign_subroutine_types()
static void link_assign_subroutine_types (struct gl_shader_program * prog) static
References foreach_in_list, and linker_error().
Referenced by link_shaders().
link_calculate_subroutine_compat()
static void link_calculate_subroutine_compat (struct gl_shader_program * prog) static
References INACTIVE_UNIFORM_EXPLICIT_LOCATION, linker_error(), gl_uniform_storage::num_compatible_subroutines, and gl_uniform_storage::type.
Referenced by link_and_validate_uniforms().
link_cs_input_layout_qualifiers()
static void link_cs_input_layout_qualifiers (struct gl_shader_program * prog, struct gl_program * gl_prog, struct gl_shader ** shader_list, unsigned num_shaders) static
Perform cross-validation of compute shader local_size_{x,y,z} layout qualifiers for the attached compute shaders, and propagate them to the linked CS and linked shader program.
References linker_error().
Referenced by link_intrastage_shaders().
link_fs_inout_layout_qualifiers()
static void link_fs_inout_layout_qualifiers (struct gl_shader_program * prog, struct gl_linked_shader * linked_shader, struct gl_shader ** shader_list, unsigned num_shaders) static
Performs the cross-validation of layout qualifiers specified in redeclaration of gl_FragCoord for the attached fragment shaders, and propagates them to the linked FS and linked shader program.
References linker_error().
Referenced by link_intrastage_shaders().
link_gs_inout_layout_qualifiers()
static void link_gs_inout_layout_qualifiers (struct gl_shader_program * prog, struct gl_program * gl_prog, struct gl_shader ** shader_list, unsigned num_shaders) static
Performs the cross-validation of geometry shader max_vertices and primitive type layout qualifiers for the attached geometry shaders, and propagates them to the linked GS and linked shader program.
References linker_error().
Referenced by link_intrastage_shaders().
link_intrastage_shaders()
struct gl_linked_shader* link_intrastage_shaders (void * mem_ctx, struct gl_context * ctx, struct gl_shader_program * prog, struct gl_shader ** shader_list, unsigned num_shaders, bool allow_missing_main)
Combine a group of shaders for a single stage to generate a linked shader.
Note
If this function is supplied a single shader, it is cloned, and the new shader is returned.
References _mesa_delete_linked_shader(), _mesa_get_main_function_signature(), _mesa_reference_shader_program_data(), clone_ir_list(), cross_validate_globals(), array_sizing_visitor::fixup_unnamed_interface_types(), foreach_in_list, link_cs_input_layout_qualifiers(), link_fs_inout_layout_qualifiers(), link_function_calls(), link_gs_inout_layout_qualifiers(), link_tcs_out_layout_qualifiers(), link_tes_in_layout_qualifiers(), link_uniform_blocks(), link_xfb_stride_layout_qualifiers(), linker_error(), lower_vertex_id(), main(), move_non_declarations(), populate_symbol_table(), validate_intrastage_interface_blocks(), validate_ir_tree(), and vertices_per_prim().
Referenced by link_shaders(), and standalone_compile_shader().
link_invalidate_variable_locations()
void link_invalidate_variable_locations (exec_list * ir)
References foreach_in_list.
Referenced by link_varyings_and_uniforms().
link_shaders()
void link_shaders (struct gl_context * ctx, struct gl_shader_program * prog)
References _mesa_delete_linked_shader(), _mesa_glsl_compile_shader(), check_explicit_uniform_locations(), cross_validate_outputs_to_inputs(), cross_validate_uniforms(), detect_recursion_linked(), disable_varying_optimizations_for_sso(), interstage_cross_validate_uniform_blocks(), link_assign_subroutine_types(), link_intrastage_shaders(), link_varyings_and_uniforms(), linker_error(), linker_optimisation_loop(), lower_clip_cull_distance(), lower_const_arrays_to_uniforms(), lower_discard_flow(), lower_named_interface_blocks(), lower_tess_level(), propagate_invariance(), reparent_ir(), resize_tes_inputs(), shader_cache_read_program_metadata(), store_fragdepth_layout(), validate_fragment_shader_executable(), validate_geometry_shader_emissions(), validate_geometry_shader_executable(), validate_interstage_inout_blocks(), validate_interstage_uniform_blocks(), validate_ir_tree(), validate_sampler_array_indexing(), validate_tess_eval_shader_executable(), and validate_vertex_shader_executable().
Referenced by standalone_compile_shader().
link_tcs_out_layout_qualifiers()
static void link_tcs_out_layout_qualifiers (struct gl_shader_program * prog, struct gl_program * gl_prog, struct gl_shader ** shader_list, unsigned num_shaders) static
Performs the cross-validation of tessellation control shader vertices and layout qualifiers for the attached tessellation control shaders, and propagates them to the linked TCS and linked shader program.
References linker_error().
Referenced by link_intrastage_shaders().
link_tes_in_layout_qualifiers()
static void link_tes_in_layout_qualifiers (struct gl_shader_program * prog, struct gl_program * gl_prog, struct gl_shader ** shader_list, unsigned num_shaders) static
Performs the cross-validation of tessellation evaluation shader primitive type, vertex spacing, ordering and point_mode layout qualifiers for the attached tessellation evaluation shaders, and propagates them to the linked TES and linked shader program.
References linker_error().
Referenced by link_intrastage_shaders().
link_varyings_and_uniforms()
static bool link_varyings_and_uniforms (unsigned first, unsigned last, struct gl_context * ctx, struct gl_shader_program * prog, void * mem_ctx) static
References assign_attribute_or_color_locations(), do_vec_index_to_swizzle(), link_and_validate_uniforms(), link_invalidate_variable_locations(), link_varyings(), lower_shared_reference(), lower_ubo_reference(), lower_vector_derefs(), match_explicit_outputs_to_inputs(), and options.
Referenced by link_shaders().
link_xfb_stride_layout_qualifiers()
static void link_xfb_stride_layout_qualifiers (struct gl_context * ctx, struct gl_shader_program * prog, struct gl_linked_shader * linked_shader, struct gl_shader ** shader_list, unsigned num_shaders) static
Check for conflicting xfb_stride default qualifiers and store buffer stride for later use.
References linker_error(), and validate_xfb_buffer_stride().
Referenced by link_intrastage_shaders().
linker_error()
void linker_error (gl_shader_program * prog, const char * fmt, ...)
Referenced by add_program_resource(), analyze_clip_cull_usage(), assign_attribute_or_color_locations(), tfeedback_decl::assign_location(), assign_varying_locations(), calculate_array_size_and_stride(), check_against_input_limit(), check_against_output_limit(), check_explicit_uniform_locations(), check_image_resources(), check_resources(), check_subroutine_resources(), cross_validate_globals(), cross_validate_outputs_to_inputs(), cross_validate_types_and_qualifiers(), emit_errors_linked(), tfeedback_decl::find_candidate(), interstage_cross_validate_uniform_blocks(), link_assign_subroutine_types(), link_calculate_subroutine_compat(), link_check_atomic_counter_resources(), link_cs_input_layout_qualifiers(), link_fs_inout_layout_qualifiers(), link_gs_inout_layout_qualifiers(), link_intrastage_shaders(), link_setup_uniform_remap_tables(), link_shaders(), link_tcs_out_layout_qualifiers(), link_tes_in_layout_qualifiers(), link_uniform_blocks(), link_varyings(), link_xfb_stride_layout_qualifiers(), parse_tfeedback_decls(), process_block_array_leaf(), reserve_explicit_locations(), reserve_subroutine_explicit_locations(), tfeedback_decl::store(), store_tfeedback_info(), validate_fragment_shader_executable(), validate_geometry_shader_emissions(), validate_interstage_inout_blocks(), validate_interstage_uniform_blocks(), validate_intrastage_arrays(), validate_intrastage_interface_blocks(), validate_sampler_array_indexing(), validate_vertex_shader_executable(), validate_xfb_buffer_stride(), link_uniform_block_active_visitor::visit(), and link_uniform_block_active_visitor::visit_enter().
linker_optimisation_loop()
static void linker_optimisation_loop (struct gl_context * ctx, exec_list * ir, unsigned stage) static
References do_common_optimization().
Referenced by link_shaders().
linker_warning()
void linker_warning (gl_shader_program * prog, const char * fmt, ...)
Referenced by assign_attribute_or_color_locations(), assign_varying_locations(), check_resources(), validate_sampler_array_indexing(), and validate_vertex_shader_executable().
match_explicit_outputs_to_inputs()
static void match_explicit_outputs_to_inputs (gl_linked_shader * producer, gl_linked_shader * consumer) static
Match explicit locations of outputs to inputs and deactivate the unmatch flag if found so we don't optimise them away.
References foreach_in_list.
Referenced by link_varyings_and_uniforms().
move_non_declarations()
exec_node* move_non_declarations (exec_list * instructions, exec_node * last, bool make_copies, gl_linked_shader * target)
Move non-declarations from one instruction stream to another.
The intended usage pattern of this function is to pass the pointer to the head sentinel of a list (i.e., a pointer to the list cast to an exec_node pointer) for last and false for make_copies on the first call. Successive calls pass the return value of the previous call for last and true for make_copies.
Parameters
instructions Source instruction stream
last Instruction after which new instructions should be inserted in the target instruction stream
make_copies Flag selecting whether instructions in instructions should be copied (via ir_instruction::clone) into the target list or moved.
Returns
The new "last" instruction in the target instruction stream. This pointer is suitable for use as the last parameter of a later call to this function.
References foreach_in_list_safe, and remap_variables().
Referenced by link_intrastage_shaders().
parse_program_resource_name()
long parse_program_resource_name (const GLchar * name, const GLchar ** out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
If an array index is present, out_base_name_end is set to point to the "[" that precedes the array index, and the array index itself is returned as a long.
If no array index is present (or if the array index is negative or mal-formed), out_base_name_end, is set to point to the null terminator at the end of the input string, and -1 is returned.
Only the final array index is parsed; if the string contains other array indices (or structure field accesses), they are left in the base name.
No attempt is made to check that the base name is properly formed; typically the caller will look up the base name in a hash table, so ill-formed base names simply turn into hash table lookup failures.
Referenced by tfeedback_decl::init().
populate_symbol_table()
static void populate_symbol_table (gl_linked_shader * sh) static
Populates a shaders symbol table with all global declarations.
References foreach_in_list.
Referenced by link_intrastage_shaders().
remap_variables()
void remap_variables (ir_instruction * inst, struct gl_linked_shader * target, hash_table * temps)
Remap variables referenced in an instruction tree.
This is used when instruction trees are cloned from one shader and placed in another. These trees will contain references to ir_variable nodes that do not exist in the target shader. This function finds these ir_variable references and replaces the references with matching variables in the target shader.
If there is no matching variable in the target shader, a clone of the ir_variable is made and added to the target shader. The new variable is added to both the instruction stream and the symbol table.
Parameters
inst IR tree that is to be processed.
symbols Symbol table containing global scope symbols in the linked shader.
instructions Instruction stream where new variable declarations should be added.
References copy(), and visit_continue.
Referenced by move_non_declarations().
reserve_explicit_locations()
static int reserve_explicit_locations (struct gl_shader_program * prog, string_to_uint_map * map, ir_variable * var) static
Initializes explicit location slots to INACTIVE_UNIFORM_EXPLICIT_LOCATION for a variable, checks for overlaps between other uniforms using explicit locations.
References INACTIVE_UNIFORM_EXPLICIT_LOCATION, and linker_error().
Referenced by check_explicit_uniform_locations().
reserve_subroutine_explicit_locations()
static bool reserve_subroutine_explicit_locations (struct gl_shader_program * prog, struct gl_program * p, ir_variable * var) static
References INACTIVE_UNIFORM_EXPLICIT_LOCATION, and linker_error().
Referenced by check_explicit_uniform_locations().
resize_tes_inputs()
static void resize_tes_inputs (struct gl_context * ctx, struct gl_shader_program * prog) static
Resize tessellation evaluation per-vertex inputs to the size of tessellation control per-vertex outputs.
References foreach_in_list.
Referenced by link_shaders().
set_always_active_io()
static void set_always_active_io (exec_list * ir, ir_variable_mode io_mode) static
References foreach_in_list.
Referenced by disable_varying_optimizations_for_sso().
should_add_buffer_variable()
static bool should_add_buffer_variable (struct gl_shader_program * shProg, GLenum type, const char * name) static
Referenced by build_program_resource_list().
store_fragdepth_layout()
static void store_fragdepth_layout (struct gl_shader_program * prog) static
Store the gl_FragDepth layout in the gl_shader_program struct.
References foreach_in_list.
Referenced by link_shaders().
update_array_sizes()
static void update_array_sizes (struct gl_shader_program * prog) static
Update the sizes of linked shader uniform arrays to the maximum array index used.
From page 81 (page 95 of the PDF) of the OpenGL 2.1 spec:
If one or more elements of an array are active,
GetActiveUniform will return the name of the array in name,
subject to the restrictions listed above. The type of the array
is returned in type. The size parameter contains the highest
array element index used, plus one. The compiler or linker
determines the highest index used.  There will be only one
active uniform reported by the GL per uniform array.
References foreach_in_list.
Referenced by link_and_validate_uniforms().
validate_fragment_shader_executable()
void validate_fragment_shader_executable (struct gl_shader_program * prog, struct gl_linked_shader * shader)
Verify that a fragment shader executable meets all semantic requirements.
Parameters
shader Fragment shader executable to be verified
References linker_error().
Referenced by link_shaders().
validate_geometry_shader_emissions()
static void validate_geometry_shader_emissions (struct gl_context * ctx, struct gl_shader_program * prog) static
Check if geometry shaders emit to non-zero streams and do corresponding validations.
References linker_error().
Referenced by link_shaders().
validate_geometry_shader_executable()
void validate_geometry_shader_executable (struct gl_shader_program * prog, struct gl_linked_shader * shader, struct gl_context * ctx)
Verify that a geometry shader executable meets all semantic requirements.
Also sets prog->Geom.VerticesIn, and info.clip_distance_array_sizeand info.cull_distance_array_size as a side effect.
Parameters
shader Geometry shader executable to be verified
References analyze_clip_cull_usage(), and vertices_per_prim().
Referenced by link_shaders().
validate_intrastage_arrays()
bool validate_intrastage_arrays (struct gl_shader_program * prog, ir_variable *const var, ir_variable *const existing)
References linker_error(), and mode_string().
Referenced by cross_validate_globals().
validate_sampler_array_indexing()
static bool validate_sampler_array_indexing (struct gl_context * ctx, struct gl_shader_program * prog) static
This check is done to make sure we allow only constant expression indexing and "constant-index-expression" (indexing with an expression that includes loop induction variable).
References linker_error(), and linker_warning().
Referenced by link_shaders().
validate_tess_eval_shader_executable()
void validate_tess_eval_shader_executable (struct gl_shader_program * prog, struct gl_linked_shader * shader, struct gl_context * ctx)
References analyze_clip_cull_usage().
Referenced by link_shaders().
validate_vertex_shader_executable()
void validate_vertex_shader_executable (struct gl_shader_program * prog, struct gl_linked_shader * shader, struct gl_context * ctx)
Verify that a vertex shader executable meets all semantic requirements.
Also sets info.clip_distance_array_size and info.cull_distance_array_size as a side effect.
Parameters
shader Vertex shader executable to be verified
References analyze_clip_cull_usage(), linker_error(), and linker_warning().
Referenced by link_shaders().
validate_xfb_buffer_stride()
static bool validate_xfb_buffer_stride (struct gl_context * ctx, unsigned idx, struct gl_shader_program * prog) static
References linker_error().
Referenced by link_xfb_stride_layout_qualifiers().