Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
linker.h File Reference
Data Structures
class program_resource_visitor
Class for processing all of the leaf fields of a variable that corresponds to a program resource.
struct empty_uniform_block
Sometimes there are empty slots left over in UniformRemapTable after we allocate slots to explicit locations.
Functions
bool link_function_calls (gl_shader_program *prog, gl_linked_shader *main, gl_shader **shader_list, unsigned num_shaders)
void link_invalidate_variable_locations (exec_list *ir)
void link_assign_uniform_locations (struct gl_shader_program *prog, struct gl_context *ctx)
void link_set_uniform_initializers (struct gl_shader_program *prog, unsigned int boolean_true)
int link_cross_validate_uniform_block (void *mem_ctx, struct gl_uniform_block **linked_blocks, unsigned int *num_linked_blocks, struct gl_uniform_block *new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
void link_uniform_blocks (void *mem_ctx, struct gl_context *ctx, struct gl_shader_program *prog, struct gl_linked_shader *shader, struct gl_uniform_block **ubo_blocks, unsigned *num_ubo_blocks, struct gl_uniform_block **ssbo_blocks, unsigned *num_ssbo_blocks)
bool validate_intrastage_arrays (struct gl_shader_program *prog, ir_variable *const var, ir_variable *const existing)
void validate_intrastage_interface_blocks (struct gl_shader_program *prog, const gl_shader **shader_list, unsigned num_shaders)
void validate_interstage_inout_blocks (struct gl_shader_program *prog, const gl_linked_shader *producer, const gl_linked_shader *consumer)
void validate_interstage_uniform_blocks (struct gl_shader_program *prog, gl_linked_shader **stages)
unsigned values_for_type (const glsl_type *type)
Count the backing storage requirements for a type.
void link_assign_atomic_counter_resources (struct gl_context *ctx, struct gl_shader_program *prog)
void link_check_atomic_counter_resources (struct gl_context *ctx, struct gl_shader_program *prog)
struct gl_linked_shader * link_intrastage_shaders (void *mem_ctx, struct gl_context *ctx, struct gl_shader_program *prog, struct gl_shader **shader_list, unsigned num_shaders, bool allow_missing_main)
Combine a group of shaders for a single stage to generate a linked shader.
void linker_error (gl_shader_program *prog, const char *fmt,...)
void linker_warning (gl_shader_program *prog, const char *fmt,...)
Function Documentation
link_assign_atomic_counter_resources()
void link_assign_atomic_counter_resources (struct gl_context * ctx, struct gl_shader_program * prog)
References ir_builder::abs(), gl_uniform_storage::array_stride, gl_uniform_storage::atomic_buffer_index, gl_uniform_storage::matrix_stride, and gl_uniform_storage::offset.
Referenced by link_and_validate_uniforms().
link_assign_uniform_locations()
void link_assign_uniform_locations (struct gl_shader_program * prog, struct gl_context * ctx)
References assign_hidden_uniform_slot_id(), foreach_in_list, link_assign_uniform_storage(), and link_update_uniform_buffer_variables().
Referenced by link_and_validate_uniforms().
link_check_atomic_counter_resources()
void link_check_atomic_counter_resources (struct gl_context * ctx, struct gl_shader_program * prog)
References ir_builder::abs(), and linker_error().
Referenced by link_and_validate_uniforms().
link_cross_validate_uniform_block()
int link_cross_validate_uniform_block (void * mem_ctx, struct gl_uniform_block ** linked_blocks, unsigned int * num_linked_blocks, struct gl_uniform_block * new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
Returns the index of the new block in the array.
References link_uniform_blocks_are_compatible().
Referenced by interstage_cross_validate_uniform_blocks().
link_function_calls()
bool link_function_calls (gl_shader_program * prog, gl_linked_shader * main, gl_shader ** shader_list, unsigned num_shaders)
Referenced by link_intrastage_shaders().
link_intrastage_shaders()
struct gl_linked_shader* link_intrastage_shaders (void * mem_ctx, struct gl_context * ctx, struct gl_shader_program * prog, struct gl_shader ** shader_list, unsigned num_shaders, bool allow_missing_main)
Combine a group of shaders for a single stage to generate a linked shader.
Note
If this function is supplied a single shader, it is cloned, and the new shader is returned.
References _mesa_delete_linked_shader(), _mesa_get_main_function_signature(), _mesa_reference_shader_program_data(), clone_ir_list(), cross_validate_globals(), array_sizing_visitor::fixup_unnamed_interface_types(), foreach_in_list, link_cs_input_layout_qualifiers(), link_fs_inout_layout_qualifiers(), link_function_calls(), link_gs_inout_layout_qualifiers(), link_tcs_out_layout_qualifiers(), link_tes_in_layout_qualifiers(), link_uniform_blocks(), link_xfb_stride_layout_qualifiers(), linker_error(), lower_vertex_id(), main(), move_non_declarations(), populate_symbol_table(), validate_intrastage_interface_blocks(), validate_ir_tree(), and vertices_per_prim().
Referenced by link_shaders(), and standalone_compile_shader().
link_invalidate_variable_locations()
void link_invalidate_variable_locations (exec_list * ir)
References foreach_in_list.
Referenced by link_varyings_and_uniforms().
link_set_uniform_initializers()
void link_set_uniform_initializers (struct gl_shader_program * prog, unsigned int boolean_true)
References foreach_in_list, linker::set_block_binding(), linker::set_opaque_binding(), and linker::set_uniform_initializer().
Referenced by link_assign_uniform_storage().
link_uniform_blocks()
void link_uniform_blocks (void * mem_ctx, struct gl_context * ctx, struct gl_shader_program * prog, struct gl_linked_shader * shader, struct gl_uniform_block ** ubo_blocks, unsigned * num_ubo_blocks, struct gl_uniform_block ** ssbo_blocks, unsigned * num_ssbo_blocks)
References link_uniform_block_active::array, create_buffer_blocks(), link_uniform_block_active::is_shader_storage, linker_error(), resize_block_array(), link_uniform_block_active::type, link_uniform_block_active::var, and visit_list_elements().
Referenced by link_intrastage_shaders().
linker_error()
void linker_error (gl_shader_program * prog, const char * fmt, ...)
Referenced by add_program_resource(), analyze_clip_cull_usage(), assign_attribute_or_color_locations(), tfeedback_decl::assign_location(), assign_varying_locations(), calculate_array_size_and_stride(), check_against_input_limit(), check_against_output_limit(), check_explicit_uniform_locations(), check_image_resources(), check_resources(), check_subroutine_resources(), cross_validate_globals(), cross_validate_outputs_to_inputs(), cross_validate_types_and_qualifiers(), emit_errors_linked(), tfeedback_decl::find_candidate(), interstage_cross_validate_uniform_blocks(), link_assign_subroutine_types(), link_calculate_subroutine_compat(), link_check_atomic_counter_resources(), link_cs_input_layout_qualifiers(), link_fs_inout_layout_qualifiers(), link_gs_inout_layout_qualifiers(), link_intrastage_shaders(), link_setup_uniform_remap_tables(), link_shaders(), link_tcs_out_layout_qualifiers(), link_tes_in_layout_qualifiers(), link_uniform_blocks(), link_varyings(), link_xfb_stride_layout_qualifiers(), parse_tfeedback_decls(), process_block_array_leaf(), reserve_explicit_locations(), reserve_subroutine_explicit_locations(), tfeedback_decl::store(), store_tfeedback_info(), validate_fragment_shader_executable(), validate_geometry_shader_emissions(), validate_interstage_inout_blocks(), validate_interstage_uniform_blocks(), validate_intrastage_arrays(), validate_intrastage_interface_blocks(), validate_sampler_array_indexing(), validate_vertex_shader_executable(), validate_xfb_buffer_stride(), link_uniform_block_active_visitor::visit(), and link_uniform_block_active_visitor::visit_enter().
linker_warning()
void linker_warning (gl_shader_program * prog, const char * fmt, ...)
Referenced by assign_attribute_or_color_locations(), assign_varying_locations(), check_resources(), validate_sampler_array_indexing(), and validate_vertex_shader_executable().
validate_interstage_inout_blocks()
void validate_interstage_inout_blocks (struct gl_shader_program * prog, const gl_linked_shader * producer, const gl_linked_shader * consumer)
References foreach_in_list, is_builtin_gl_in_block(), and linker_error().
Referenced by link_shaders().
validate_interstage_uniform_blocks()
void validate_interstage_uniform_blocks (struct gl_shader_program * prog, gl_linked_shader ** stages)
References foreach_in_list, and linker_error().
Referenced by link_shaders().
validate_intrastage_arrays()
bool validate_intrastage_arrays (struct gl_shader_program * prog, ir_variable *const var, ir_variable *const existing)
References linker_error(), and mode_string().
Referenced by cross_validate_globals().
validate_intrastage_interface_blocks()
void validate_intrastage_interface_blocks (struct gl_shader_program * prog, const gl_shader ** shader_list, unsigned num_shaders)
References foreach_in_list, and linker_error().
Referenced by link_intrastage_shaders().
values_for_type()
unsigned values_for_type (const glsl_type * type)
Count the backing storage requirements for a type.
Referenced by read_uniforms(), program_resource_visitor::set_record_array_count(), and write_uniforms().