Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_varyings.h File Reference
Linker functions related specifically to linking varyings between shader stages.
#include "main/glheader.h"
Data Structures
struct tfeedback_candidate
Data structure describing a varying which is available for use in transform feedback.
class tfeedback_decl
Data structure tracking information about a transform feedback declaration during linking.
Functions
bool link_varyings (struct gl_shader_program *prog, unsigned first, unsigned last, struct gl_context *ctx, void *mem_ctx)
void cross_validate_outputs_to_inputs (struct gl_shader_program *prog, gl_linked_shader *producer, gl_linked_shader *consumer)
Validate that outputs from one stage match inputs of another.
Detailed Description
Linker functions related specifically to linking varyings between shader stages.
Function Documentation
cross_validate_outputs_to_inputs()
void cross_validate_outputs_to_inputs (struct gl_shader_program * prog, gl_linked_shader * producer, gl_linked_shader * consumer)
Validate that outputs from one stage match inputs of another.
References glsl_symbol_table::add_variable(), cross_validate_front_and_back_color(), cross_validate_types_and_qualifiers(), foreach_in_list, glsl_symbol_table::get_variable(), get_varying_type(), and linker_error().
Referenced by tfeedback_decl::get_location(), and link_shaders().
link_varyings()
bool link_varyings (struct gl_shader_program * prog, unsigned first, unsigned last, struct gl_context * ctx, void * mem_ctx)
References assign_varying_locations(), check_against_input_limit(), check_against_output_limit(), do_dead_builtin_varyings(), linker_error(), parse_tfeedback_decls(), process_xfb_layout_qualifiers(), remove_unused_shader_inputs_and_outputs(), reserved_varying_slot(), and store_tfeedback_info().
Referenced by tfeedback_decl::get_location(), and link_varyings_and_uniforms().