Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_uniform_block_active_visitor.cpp File Reference
#include "link_uniform_block_active_visitor.h"
#include "program.h"
Functions
static link_uniform_block_active * process_block (void *mem_ctx, struct hash_table *ht, ir_variable *var)
static struct uniform_block_array_elements ** process_arrays (void *mem_ctx, ir_dereference_array *ir, struct link_uniform_block_active *block)
Function Documentation
process_arrays()
static struct uniform_block_array_elements** process_arrays (void * mem_ctx, ir_dereference_array * ir, struct link_uniform_block_active * block) static
References uniform_block_array_elements::array, link_uniform_block_active::array, uniform_block_array_elements::array_elements, uniform_block_array_elements::ir, and uniform_block_array_elements::num_array_elements.
Referenced by link_uniform_block_active_visitor::visit_enter().
process_block()
static link_uniform_block_active* process_block (void * mem_ctx, struct hash_table * ht, ir_variable * var) static
References link_uniform_block_active::binding, link_uniform_block_active::has_binding, link_uniform_block_active::has_instance_name, link_uniform_block_active::is_shader_storage, and link_uniform_block_active::type.
Referenced by link_uniform_block_active_visitor::visit(), and link_uniform_block_active_visitor::visit_enter().