Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_uniform_initializers.cpp File Reference
#include "main/core.h"
#include "ir.h"
#include "linker.h"
#include "ir_uniform.h"
#include "util/string_to_uint_map.h"
Namespaces
linker
Functions
gl_uniform_storage * linker::get_storage (struct gl_shader_program *prog, const char *name)
void linker::copy_constant_to_storage (union gl_constant_value *storage, const ir_constant *val, const enum glsl_base_type base_type, const unsigned int elements, unsigned int boolean_true)
void linker::set_opaque_binding (void *mem_ctx, gl_shader_program *prog, const glsl_type *type, const char *name, int *binding)
Initialize an opaque uniform from the value of an explicit binding qualifier specified in the shader.
void linker::set_block_binding (gl_shader_program *prog, const char *block_name, unsigned mode, int binding)
void linker::set_uniform_initializer (void *mem_ctx, gl_shader_program *prog, const char *name, const glsl_type *type, ir_constant *val, unsigned int boolean_true)
void link_set_uniform_initializers (struct gl_shader_program *prog, unsigned int boolean_true)
Function Documentation
link_set_uniform_initializers()
void link_set_uniform_initializers (struct gl_shader_program * prog, unsigned int boolean_true)
References foreach_in_list, linker::set_block_binding(), linker::set_opaque_binding(), and linker::set_uniform_initializer().
Referenced by link_assign_uniform_storage().