Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
link_uniform_blocks.cpp File Reference
#include "main/core.h"
#include "ir.h"
#include "linker.h"
#include "ir_uniform.h"
#include "link_uniform_block_active_visitor.h"
#include "util/hash_table.h"
#include "program.h"
Data Structures
struct block
Functions
static void process_block_array_leaf (const char *name, gl_uniform_block *blocks, ubo_visitor *parcel, gl_uniform_buffer_variable *variables, const struct link_uniform_block_active *const b, unsigned *block_index, unsigned *binding_offset, unsigned linearized_index, struct gl_context *ctx, struct gl_shader_program *prog)
static void process_block_array (struct uniform_block_array_elements *ub_array, char **name, size_t name_length, gl_uniform_block *blocks, ubo_visitor *parcel, gl_uniform_buffer_variable *variables, const struct link_uniform_block_active *const b, unsigned *block_index, unsigned *binding_offset, struct gl_context *ctx, struct gl_shader_program *prog, unsigned first_index)
static const glsl_type * resize_block_array (const glsl_type *type, struct uniform_block_array_elements *ub_array)
static void create_buffer_blocks (void *mem_ctx, struct gl_context *ctx, struct gl_shader_program *prog, struct gl_uniform_block **out_blks, unsigned num_blocks, struct hash_table *block_hash, unsigned num_variables, bool create_ubo_blocks)
void link_uniform_blocks (void *mem_ctx, struct gl_context *ctx, struct gl_shader_program *prog, struct gl_linked_shader *shader, struct gl_uniform_block **ubo_blocks, unsigned *num_ubo_blocks, struct gl_uniform_block **ssbo_blocks, unsigned *num_ssbo_blocks)
static bool link_uniform_blocks_are_compatible (const gl_uniform_block *a, const gl_uniform_block *b)
int link_cross_validate_uniform_block (void *mem_ctx, struct gl_uniform_block **linked_blocks, unsigned int *num_linked_blocks, struct gl_uniform_block *new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
Function Documentation
create_buffer_blocks()
static void create_buffer_blocks (void * mem_ctx, struct gl_context * ctx, struct gl_shader_program * prog, struct gl_uniform_block ** out_blks, unsigned num_blocks, struct hash_table * block_hash, unsigned num_variables, bool create_ubo_blocks) static
References link_uniform_block_active::array, link_uniform_block_active::has_instance_name, link_uniform_block_active::is_shader_storage, process_block_array(), process_block_array_leaf(), and link_uniform_block_active::type.
Referenced by link_uniform_blocks().
link_cross_validate_uniform_block()
int link_cross_validate_uniform_block (void * mem_ctx, struct gl_uniform_block ** linked_blocks, unsigned int * num_linked_blocks, struct gl_uniform_block * new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
Returns the index of the new block in the array.
References link_uniform_blocks_are_compatible().
Referenced by interstage_cross_validate_uniform_blocks().
link_uniform_blocks()
void link_uniform_blocks (void * mem_ctx, struct gl_context * ctx, struct gl_shader_program * prog, struct gl_linked_shader * shader, struct gl_uniform_block ** ubo_blocks, unsigned * num_ubo_blocks, struct gl_uniform_block ** ssbo_blocks, unsigned * num_ssbo_blocks)
References link_uniform_block_active::array, create_buffer_blocks(), link_uniform_block_active::is_shader_storage, linker_error(), resize_block_array(), link_uniform_block_active::type, link_uniform_block_active::var, and visit_list_elements().
Referenced by link_intrastage_shaders().
link_uniform_blocks_are_compatible()
static bool link_uniform_blocks_are_compatible (const gl_uniform_block * a, const gl_uniform_block * b) static
Referenced by link_cross_validate_uniform_block().
process_block_array()
static void process_block_array (struct uniform_block_array_elements * ub_array, char ** name, size_t name_length, gl_uniform_block * blocks, ubo_visitor * parcel, gl_uniform_buffer_variable * variables, const struct link_uniform_block_active *const b, unsigned * block_index, unsigned * binding_offset, struct gl_context * ctx, struct gl_shader_program * prog, unsigned first_index) static
Parameters
first_index Value of block_index for the first element of the array.
References uniform_block_array_elements::array, uniform_block_array_elements::array_elements, uniform_block_array_elements::num_array_elements, and process_block_array_leaf().
Referenced by create_buffer_blocks().
process_block_array_leaf()
static void process_block_array_leaf (const char * name, gl_uniform_block * blocks, ubo_visitor * parcel, gl_uniform_buffer_variable * variables, const struct link_uniform_block_active *const b, unsigned * block_index, unsigned * binding_offset, unsigned linearized_index, struct gl_context * ctx, struct gl_shader_program * prog) static
References link_uniform_block_active::binding, link_uniform_block_active::has_binding, link_uniform_block_active::has_instance_name, link_uniform_block_active::is_shader_storage, linker_error(), and link_uniform_block_active::type.
Referenced by create_buffer_blocks(), and process_block_array().
resize_block_array()
static const glsl_type* resize_block_array (const glsl_type * type, struct uniform_block_array_elements * ub_array) static
References uniform_block_array_elements::array, uniform_block_array_elements::ir, and uniform_block_array_elements::num_array_elements.
Referenced by link_uniform_blocks().