Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
list.h File Reference
Doubly-linked list abstract container type.
#include <stddef.h>
#include <assert.h>
#include "util/ralloc.h"
Data Structures
struct exec_node
struct exec_list
Macros
#define exec_list_offsetof(t, f, p) offsetof(t, f)
#define exec_node_data(type, node, field) ((type *) (((char *) node) - exec_list_offsetof(type, field, node)))
Get a pointer to the structure containing an exec_node.
#define foreach_in_list(__type, __inst, __list)
#define foreach_in_list_reverse(__type, __inst, __list)
#define foreach_in_list_safe(__type, __node, __list)
This version is safe even if the current node is removed.
#define foreach_in_list_reverse_safe(__type, __node, __list)
#define foreach_in_list_use_after(__type, __inst, __list)
#define foreach_two_lists(__node1, __list1, __node2, __list2)
Iterate through two lists at once.
#define foreach_list_typed(__type, __node, __field, __list)
#define foreach_list_typed_from(__type, __node, __field, __list, __start)
#define foreach_list_typed_reverse(__type, __node, __field, __list)
#define foreach_list_typed_safe(__type, __node, __field, __list)
#define foreach_list_typed_reverse_safe(__type, __node, __field, __list)
Functions
static void exec_node_init (struct exec_node *n)
static const struct exec_node * exec_node_get_next_const (const struct exec_node *n)
static struct exec_node * exec_node_get_next (struct exec_node *n)
static const struct exec_node * exec_node_get_prev_const (const struct exec_node *n)
static struct exec_node * exec_node_get_prev (struct exec_node *n)
static void exec_node_remove (struct exec_node *n)
static void exec_node_self_link (struct exec_node *n)
static void exec_node_insert_after (struct exec_node *n, struct exec_node *after)
static void exec_node_insert_node_before (struct exec_node *n, struct exec_node *before)
static void exec_node_replace_with (struct exec_node *n, struct exec_node *replacement)
static bool exec_node_is_tail_sentinel (const struct exec_node *n)
static bool exec_node_is_head_sentinel (const struct exec_node *n)
static void exec_list_make_empty (struct exec_list *list)
static bool exec_list_is_empty (const struct exec_list *list)
static const struct exec_node * exec_list_get_head_const (const struct exec_list *list)
static struct exec_node * exec_list_get_head (struct exec_list *list)
static const struct exec_node * exec_list_get_head_raw_const (const struct exec_list *list)
static struct exec_node * exec_list_get_head_raw (struct exec_list *list)
static const struct exec_node * exec_list_get_tail_const (const struct exec_list *list)
static struct exec_node * exec_list_get_tail (struct exec_list *list)
static const struct exec_node * exec_list_get_tail_raw_const (const struct exec_list *list)
static struct exec_node * exec_list_get_tail_raw (struct exec_list *list)
static unsigned exec_list_length (const struct exec_list *list)
static void exec_list_push_head (struct exec_list *list, struct exec_node *n)
static void exec_list_push_tail (struct exec_list *list, struct exec_node *n)
static void exec_list_push_degenerate_list_at_head (struct exec_list *list, struct exec_node *n)
static struct exec_node * exec_list_pop_head (struct exec_list *list)
static void exec_list_move_nodes_to (struct exec_list *list, struct exec_list *target)
static void exec_list_append (struct exec_list *list, struct exec_list *source)
static void exec_list_prepend (struct exec_list *list, struct exec_list *source)
static void exec_node_insert_list_before (struct exec_node *n, struct exec_list *before)
static void exec_list_validate (const struct exec_list *list)
Detailed Description
Doubly-linked list abstract container type.
Each doubly-linked list has a sentinel head and tail node. These nodes contain no data. The head sentinel can be identified by its prev pointer being NULL. The tail sentinel can be identified by its next pointer being NULL.
A list is empty if either the head sentinel's next pointer points to the tail sentinel or the tail sentinel's prev poiner points to the head sentinel. The head sentinel and tail sentinel nodes are allocated within the list structure.
Do note that this means that the list nodes will contain pointers into the list structure itself and as a result you may not realloc() an exec_list or any structure in which an exec_list is embedded.
Macro Definition Documentation
exec_list_offsetof
#define exec_list_offsetof (t, f, p) offsetof(t, f)
exec_node_data
#define exec_node_data (type, node, field) ((type *) (((char *) node) - exec_list_offsetof(type, field, node)))
Get a pointer to the structure containing an exec_node.
Given a pointer to an exec_node embedded in a structure, get a pointer to the containing structure.
Parameters
type Base type of the structure containing the node
node Pointer to the exec_node
field Name of the field in type that is the embedded exec_node
Referenced by _mesa_ast_set_aggregate_type(), do_dead_code(), free_entry(), process_array_size(), ast_layout_expression::process_qualifier_constant(), and verify_parameter_modes().
foreach_in_list
#define foreach_in_list (__type, __inst, __list)
Value:
for (__type *(__inst) = (__type *)(__list)->head_sentinel.next; \
        !(__inst)->is_tail_sentinel();               \
        (__inst) = (__type *)(__inst)->next)
Referenced by _mesa_glsl_compile_shader(), _mesa_glsl_read_ir(), _mesa_print_ir(), add_fragdata_arrays(), add_interface_variables(), add_packed_varyings(), always_available(), assign_attribute_or_color_locations(), assign_varying_locations(), bitfield_insert(), build_stageref(), calculate_array_size_and_stride(), calculate_iterations(), call_for_basic_blocks(), canonicalize_shader_io(), check_against_input_limit(), check_against_output_limit(), check_explicit_uniform_locations(), check_image_resources(), choose_best_inexact_overload(), clone_ir_list(), constant_copy(), cross_validate_globals(), cross_validate_outputs_to_inputs(), depth_layout_string(), detect_conflicting_assignments(), do_constant_variable_unlinked(), do_dead_code_unlinked(), do_expression_flattening(), emit_inline_matrix_constructor(), emit_inline_vector_constructor(), find_discard(), get_main(), loop_variable_state::get_or_insert(), ir_array_splitting_visitor::get_splitting_entry(), ast_case_statement_list::hir(), ast_function_definition::hir(), ast_tcs_output_layout::hir(), ast_gs_input_layout::hir(), link_assign_subroutine_types(), link_assign_uniform_locations(), link_assign_uniform_storage(), link_intrastage_shaders(), link_invalidate_variable_locations(), link_set_uniform_initializers(), link_update_uniform_buffer_variables(), lower_blend_equation_advanced(), lower_subroutine(), match_explicit_outputs_to_inputs(), modes_match(), move_block_to_cond_assign(), optimize_split_arrays(), parameter_lists_match_exact(), linker::populate_consumer_input_sets(), populate_symbol_table(), s_list::print(), print_function_prototypes(), process_array_constructor(), process_assignment(), process_vec_mat_constructor(), process_xfb_layout_qualifiers(), prototype_string(), remove_unused_shader_inputs_and_outputs(), reparent_ir(), replace_return_with_assignment(), reserved_varying_slot(), resize_tes_inputs(), s_match(), set_always_active_io(), steal_memory(), store_fragdepth_layout(), update_array_sizes(), validate_interstage_inout_blocks(), validate_interstage_uniform_blocks(), validate_intrastage_interface_blocks(), validate_ir_tree(), verify_parameter_modes(), ir_print_visitor::visit(), loop_unroll_count::visit_enter(), ir_builder_print_visitor::visit_leave(), lower_packed_varyings_gs_splicer::visit_leave(), and lower_packed_varyings_return_splicer::visit_leave().
foreach_in_list_reverse
#define foreach_in_list_reverse (__type, __inst, __list)
Value:
for (__type *(__inst) = (__type *)(__list)->tail_sentinel.prev; \
        !(__inst)->is_head_sentinel();                    \
        (__inst) = (__type *)(__inst)->prev)
foreach_in_list_reverse_safe
#define foreach_in_list_reverse_safe (__type, __node, __list)
Value:
for (__type *__node = (__type *)(__list)->tail_sentinel.prev,      \
               *__prev = (__type *)__node->prev;             \
        __prev != NULL;                                      \
        __node = __prev, __prev = (__type *)__prev->prev)
foreach_in_list_safe
#define foreach_in_list_safe (__type, __node, __list)
Value:
for (__type *__node = (__type *)(__list)->head_sentinel.next,   \
               *__next = (__type *)__node->next;     \
        __next != NULL;                              \
        __node = __next, __next = (__type *)__next->next)
This version is safe even if the current node is removed.
Referenced by _mesa_ast_to_hir(), destroy_links(), do_dead_functions(), do_structure_splitting(), loop_variable_state::get_or_insert(), ast_function_expression::hir(), ast_interface_block::hir(), move_block_to_cond_assign(), move_non_declarations(), optimize_dead_builtin_variables(), process_array_constructor(), process_array_ir(), process_assignment(), process_record_constructor(), process_vec_mat_constructor(), remove_per_vertex_blocks(), ir_rvalue_base_visitor::rvalue_visit(), visit_exec_list(), ir_variable_replacement_visitor::visit_leave(), and visit_list_elements().
foreach_in_list_use_after
#define foreach_in_list_use_after (__type, __inst, __list)
Value:
__type *(__inst);                                      \
   for ((__inst) = (__type *)(__list)->head_sentinel.next; \
        !(__inst)->is_tail_sentinel();                    \
        (__inst) = (__type *)(__inst)->next)
foreach_list_typed
#define foreach_list_typed (__type, __node, __field, __list)
Value:
for (__type * __node =                                          \
         exec_node_data(__type, (__list)->head_sentinel.next, __field); \
        (__node)->__field.next != NULL;                                 \
        (__node) = exec_node_data(__type, (__node)->__field.next, __field))
Referenced by _mesa_ast_process_interface_block(), _mesa_ast_to_hir(), _mesa_glsl_compile_shader(), ast_process_struct_or_iface_block_members(), ast_expression::do_hir(), find_empty_block(), ast_function_expression::has_sequence_subexpression(), ast_function_expression::hir(), ast_compound_statement::hir(), ast_declarator_list::hir(), ast_function::hir(), ast_case_label_list::hir(), ast_case_statement::hir(), ast_case_statement_list::hir(), ast_parameter_declarator::parameters_to_hir(), ast_expression::print(), ast_subroutine_list::print(), ast_array_specifier::print(), ast_compound_statement::print(), ast_struct_specifier::print(), ast_declarator_list::print(), ast_function::print(), ast_case_label_list::print(), ast_case_statement::print(), ast_case_statement_list::print(), and process_parameters().
foreach_list_typed_from
#define foreach_list_typed_from (__type, __node, __field, __list, __start)
Value:
for (__type * __node = exec_node_data(__type, (__start), __field);      \
        (__node)->__field.next != NULL;                                    \
        (__node) = exec_node_data(__type, (__node)->__field.next, __field))
foreach_list_typed_reverse
#define foreach_list_typed_reverse (__type, __node, __field, __list)
Value:
for (__type * __node =                                                \
           exec_node_data(__type, (__list)->tail_sentinel.prev, __field);  \
        (__node)->__field.prev != NULL;                                 \
        (__node) = exec_node_data(__type, (__node)->__field.prev, __field))
foreach_list_typed_reverse_safe
#define foreach_list_typed_reverse_safe (__type, __node, __field, __list)
Value:
for (__type * __node =                                                  \
           exec_node_data(__type, (__list)->tail_sentinel.prev, __field),  \
               * __prev =                                                  \
           exec_node_data(__type, (__node)->__field.prev, __field);        \
        (__node)->__field.prev != NULL;                                    \
        __node = __prev, __prev =                                          \
           exec_node_data(__type, (__prev)->__field.prev, __field))
foreach_list_typed_safe
#define foreach_list_typed_safe (__type, __node, __field, __list)
Value:
for (__type * __node =                                                  \
           exec_node_data(__type, (__list)->head_sentinel.next, __field),  \
               * __next =                                                  \
           exec_node_data(__type, (__node)->__field.next, __field);        \
        (__node)->__field.next != NULL;                                    \
        __node = __next, __next =                                          \
           exec_node_data(__type, (__next)->__field.next, __field))
foreach_two_lists
#define foreach_two_lists (__node1, __list1, __node2, __list2)
Value:
for (struct exec_node * __node1 = (__list1)->head_sentinel.next, \
                         * __node2 = (__list2)->head_sentinel.next, \
                         * __next1 = __node1->next,           \
                         * __next2 = __node2->next            \
        ; __next1 != NULL && __next2 != NULL                  \
        ; __node1 = __next1,                                  \
          __node2 = __next2,                                  \
          __next1 = __next1->next,                            \
          __next2 = __next2->next)
Iterate through two lists at once.
Stops at the end of the shorter list.
This is safe against either current node being removed or replaced.
Referenced by generate_call(), get_assignment_entry(), ir_constant_fold(), modes_match(), and replace_return_with_assignment().
Function Documentation
exec_list_append()
static void exec_list_append (struct exec_list * list, struct exec_list * source) inline static
References exec_list_is_empty(), exec_list_make_empty(), exec_list::head_sentinel, exec_node::next, exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_prepend(), and exec_list_validate().
exec_list_get_head()
static struct exec_node* exec_list_get_head (struct exec_list * list) static
References exec_list_is_empty(), exec_list::head_sentinel, and exec_node::next.
Referenced by exec_list_pop_head(), and exec_list_validate().
exec_list_get_head_const()
static const struct exec_node* exec_list_get_head_const (const struct exec_list * list) static
References exec_list_is_empty(), exec_list::head_sentinel, and exec_node::next.
Referenced by exec_list_validate().
exec_list_get_head_raw()
static struct exec_node* exec_list_get_head_raw (struct exec_list * list) static
References exec_list::head_sentinel, and exec_node::next.
Referenced by exec_list_validate().
exec_list_get_head_raw_const()
static const struct exec_node* exec_list_get_head_raw_const (const struct exec_list * list) static
References exec_list::head_sentinel, and exec_node::next.
Referenced by exec_list_validate().
exec_list_get_tail()
static struct exec_node* exec_list_get_tail (struct exec_list * list) static
References exec_list_is_empty(), exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_validate().
exec_list_get_tail_const()
static const struct exec_node* exec_list_get_tail_const (const struct exec_list * list) static
References exec_list_is_empty(), exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_validate().
exec_list_get_tail_raw()
static struct exec_node* exec_list_get_tail_raw (struct exec_list * list) static
References exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_validate().
exec_list_get_tail_raw_const()
static const struct exec_node* exec_list_get_tail_raw_const (const struct exec_list * list) static
References exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_validate().
exec_list_is_empty()
static bool exec_list_is_empty (const struct exec_list * list) inline static
References exec_list::head_sentinel, exec_node::next, and exec_list::tail_sentinel.
Referenced by exec_list_append(), exec_list_get_head(), exec_list_get_head_const(), exec_list_get_tail(), exec_list_get_tail_const(), exec_list_move_nodes_to(), exec_list_validate(), and exec_node_insert_list_before().
exec_list_length()
static unsigned exec_list_length (const struct exec_list * list) inline static
References exec_list::head_sentinel, and exec_node::next.
Referenced by exec_list_validate().
exec_list_make_empty()
static void exec_list_make_empty (struct exec_list * list) inline static
References exec_list::head_sentinel, exec_node::next, exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_append(), exec_list_move_nodes_to(), exec_list_validate(), and exec_node_insert_list_before().
exec_list_move_nodes_to()
static void exec_list_move_nodes_to (struct exec_list * list, struct exec_list * target) inline static
References exec_list_is_empty(), exec_list_make_empty(), exec_list::head_sentinel, exec_node::next, exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_prepend(), and exec_list_validate().
exec_list_pop_head()
static struct exec_node* exec_list_pop_head (struct exec_list * list) static
References exec_list_get_head(), and exec_node_remove().
Referenced by exec_list_validate().
exec_list_prepend()
static void exec_list_prepend (struct exec_list * list, struct exec_list * source) inline static
References exec_list_append(), and exec_list_move_nodes_to().
Referenced by exec_list_validate().
exec_list_push_degenerate_list_at_head()
static void exec_list_push_degenerate_list_at_head (struct exec_list * list, struct exec_node * n) inline static
References exec_list::head_sentinel, exec_node::next, and exec_node::prev.
Referenced by exec_list_validate().
exec_list_push_head()
static void exec_list_push_head (struct exec_list * list, struct exec_node * n) inline static
References exec_list::head_sentinel, exec_node::next, and exec_node::prev.
Referenced by exec_list_validate().
exec_list_push_tail()
static void exec_list_push_tail (struct exec_list * list, struct exec_node * n) inline static
References exec_node::next, exec_node::prev, and exec_list::tail_sentinel.
Referenced by check_explicit_uniform_locations(), and exec_list_validate().
exec_list_validate()
static void exec_list_validate (const struct exec_list * list) inline static
References exec_list_append(), exec_list_get_head(), exec_list_get_head_const(), exec_list_get_head_raw(), exec_list_get_head_raw_const(), exec_list_get_tail(), exec_list_get_tail_const(), exec_list_get_tail_raw(), exec_list_get_tail_raw_const(), exec_list_is_empty(), exec_list_length(), exec_list_make_empty(), exec_list_move_nodes_to(), exec_list_pop_head(), exec_list_prepend(), exec_list_push_degenerate_list_at_head(), exec_list_push_head(), exec_list_push_tail(), exec_node_insert_list_before(), exec_list::head_sentinel, exec_node::next, exec_node::prev, and exec_list::tail_sentinel.
exec_node_get_next()
static struct exec_node* exec_node_get_next (struct exec_node * n) static
References exec_node::next.
Referenced by exec_node_is_head_sentinel().
exec_node_get_next_const()
static const struct exec_node* exec_node_get_next_const (const struct exec_node * n) static
References exec_node::next.
Referenced by exec_node_is_head_sentinel().
exec_node_get_prev()
static struct exec_node* exec_node_get_prev (struct exec_node * n) static
References exec_node::prev.
Referenced by exec_node_is_head_sentinel().
exec_node_get_prev_const()
static const struct exec_node* exec_node_get_prev_const (const struct exec_node * n) static
References exec_node::prev.
Referenced by exec_node_is_head_sentinel().
exec_node_init()
static void exec_node_init (struct exec_node * n) inline static
References exec_node::next, and exec_node::prev.
exec_node_insert_after()
static void exec_node_insert_after (struct exec_node * n, struct exec_node * after) inline static
References exec_node::next, and exec_node::prev.
Referenced by exec_node_is_head_sentinel().
exec_node_insert_list_before()
static void exec_node_insert_list_before (struct exec_node * n, struct exec_list * before) inline static
References exec_list_is_empty(), exec_list_make_empty(), exec_list::head_sentinel, exec_node::next, exec_node::prev, and exec_list::tail_sentinel.
Referenced by exec_list_validate().
exec_node_insert_node_before()
static void exec_node_insert_node_before (struct exec_node * n, struct exec_node * before) inline static
References exec_node::next, and exec_node::prev.
Referenced by exec_node_is_head_sentinel().
exec_node_is_head_sentinel()
static bool exec_node_is_head_sentinel (const struct exec_node * n) inline static
References exec_node_get_next(), exec_node_get_next_const(), exec_node_get_prev(), exec_node_get_prev_const(), exec_node_insert_after(), exec_node_insert_node_before(), exec_node_is_tail_sentinel(), exec_node_remove(), exec_node_replace_with(), exec_node_self_link(), and exec_node::prev.
exec_node_is_tail_sentinel()
static bool exec_node_is_tail_sentinel (const struct exec_node * n) inline static
References exec_node::next.
Referenced by exec_node_is_head_sentinel().
exec_node_remove()
static void exec_node_remove (struct exec_node * n) inline static
References exec_node::next, and exec_node::prev.
Referenced by exec_list_pop_head(), exec_node_is_head_sentinel(), and find_empty_block().
exec_node_replace_with()
static void exec_node_replace_with (struct exec_node * n, struct exec_node * replacement) inline static
References exec_node::next, and exec_node::prev.
Referenced by exec_node_is_head_sentinel().
exec_node_self_link()
static void exec_node_self_link (struct exec_node * n) inline static
References exec_node::next, and exec_node::prev.
Referenced by exec_node_is_head_sentinel().