Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
loop_analysis.h File Reference
#include "ir.h"
#include "util/hash_table.h"
Data Structures
class loop_variable_state
Tracking for all variables used in a loop.
class loop_variable
class loop_terminator
class loop_state
Functions
class loop_state * analyze_loop_variables (exec_list *instructions)
Analyze and classify all variables used in all loops in the instruction list.
bool set_loop_controls (exec_list *instructions, loop_state *ls)
Fill in loop control fields.
bool unroll_loops (exec_list *instructions, loop_state *ls, const struct gl_shader_compiler_options *options)
ir_rvalue * find_initial_value (ir_loop *loop, ir_variable *var)
Find an initializer of a variable outside a loop.
int calculate_iterations (ir_rvalue *from, ir_rvalue *to, ir_rvalue *increment, enum ir_expression_operation op)
Function Documentation
analyze_loop_variables()
class loop_state* analyze_loop_variables (exec_list * instructions)
Analyze and classify all variables used in all loops in the instruction list.
Referenced by do_common_optimization().
calculate_iterations()
int calculate_iterations (ir_rvalue * from, ir_rvalue * to, ir_rvalue * increment, enum ir_expression_operation op)
References ir_builder::add(), ir_builder::div(), foreach_in_list, loop_variable_state::get(), loop_terminator::iterations, loop_variable_state::limiting_terminator, ir_builder::mul(), loop_variable_state::num_loop_jumps, ir_builder::sub(), loop_variable_state::terminators, and visit_continue.
Referenced by loop_variable_state::get_or_insert().
find_initial_value()
ir_rvalue* find_initial_value (ir_loop * loop, ir_variable * var)
Find an initializer of a variable outside a loop.
Works backwards from the loop to find the pre-loop value of the variable. This is used, for example, to find the initial value of loop induction variables.
Parameters
loop Loop where var is an induction variable
var Variable whose initializer is to be found
Returns
The ir_rvalue assigned to the variable outside the loop. May return NULL if no initializer can be found.
References ir_builder::assign(), and exec_node::prev.
Referenced by loop_variable_state::get_or_insert().
set_loop_controls()
bool set_loop_controls (exec_list * instructions, loop_state * ls)
Fill in loop control fields.
Based on analysis of loop variables, this function tries to remove redundant sequences in the loop of the form
(if (expression bool ...) (break))
For example, if it is provable that one loop exit condition will always be satisfied before another, the unnecessary exit condition will be removed.
Referenced by do_common_optimization().
unroll_loops()
bool unroll_loops (exec_list * instructions, loop_state * ls, const struct gl_shader_compiler_options * options)
Referenced by do_common_optimization().