Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_subroutine.cpp File Reference
lowers subroutines to an if ladder.
#include "compiler/glsl_types.h"
#include "glsl_parser_extras.h"
#include "ir.h"
#include "ir_builder.h"
Functions
bool lower_subroutine (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Detailed Description
lowers subroutines to an if ladder.
Function Documentation
lower_subroutine()
bool lower_subroutine (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References ir_builder::equal(), foreach_in_list, ir_builder::if_tree(), ir_builder::subr_to_int(), visit_continue, and visit_list_elements().
Referenced by _mesa_glsl_compile_shader().