Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_instructions.cpp File Reference
Many GPUs lack native instructions for certain expression operations, and must replace them with some other expression tree.
#include "c99_math.h"
#include "program/prog_instruction.h"
#include "compiler/glsl_types.h"
#include "ir.h"
#include "ir_builder.h"
#include "ir_optimization.h"
Macros
#define lowering(x) (this->lower & x)
Determine if a particular type of lowering should occur.
Functions
bool lower_instructions (exec_list *instructions, unsigned what_to_lower)
Detailed Description
Many GPUs lack native instructions for certain expression operations, and must replace them with some other expression tree.
This pass lowers some of the most common cases, allowing the lowering code to be implemented once rather than in each driver backend.
Currently supported transformations:
SUB_TO_ADD_NEG
DIV_TO_MUL_RCP
INT_DIV_TO_MUL_RCP
EXP_TO_EXP2
POW_TO_EXP2
LOG_TO_LOG2
MOD_TO_FLOOR
LDEXP_TO_ARITH
DFREXP_TO_ARITH
CARRY_TO_ARITH
BORROW_TO_ARITH
SAT_TO_CLAMP
DOPS_TO_DFRAC
SUB_TO_ADD_NEG:
Breaks an ir_binop_sub expression down to add(op0, neg(op1))
This simplifies expression reassociation, and for many backends there is no subtract operation separate from adding the negation. For backends with native subtract operations, they will probably want to recognize add(op0, neg(op1)) or the other way around to produce a subtract anyway.
FDIV_TO_MUL_RCP, DDIV_TO_MUL_RCP, and INT_DIV_TO_MUL_RCP:
Breaks an ir_binop_div expression down to op0 * (rcp(op1)).
Many GPUs don't have a divide instruction (945 and 965 included), but they do have an RCP instruction to compute an approximate reciprocal. By breaking the operation down, constant reciprocals can get constant folded.
FDIV_TO_MUL_RCP only lowers single-precision floating point division; DDIV_TO_MUL_RCP only lowers double-precision floating point division. DIV_TO_MUL_RCP is a convenience macro that sets both flags. INT_DIV_TO_MUL_RCP handles the integer case, converting to and from floating point so that RCP is possible.
EXP_TO_EXP2 and LOG_TO_LOG2:
Many GPUs don't have a base e log or exponent instruction, but they do have base 2 versions, so this pass converts exp and log to exp2 and log2 operations.
POW_TO_EXP2:
Many older GPUs don't have an x**y instruction. For these GPUs, convert x**y to 2**(y * log2(x)).
MOD_TO_FLOOR:
Breaks an ir_binop_mod expression down to (op0 - op1 * floor(op0 / op1))
Many GPUs don't have a MOD instruction (945 and 965 included), and if we have to break it down like this anyway, it gives an opportunity to do things like constant fold the (1.0 / op1) easily.
Note: before we used to implement this as op1 * fract(op / op1) but this implementation had significant precision errors.
LDEXP_TO_ARITH:
Converts ir_binop_ldexp to arithmetic and bit operations for float sources.
DFREXP_DLDEXP_TO_ARITH:
Converts ir_binop_ldexp, ir_unop_frexp_sig, and ir_unop_frexp_exp to arithmetic and bit ops for double arguments.
CARRY_TO_ARITH:
Converts ir_carry into (x + y) < x.
BORROW_TO_ARITH:
Converts ir_borrow into (x < y).
SAT_TO_CLAMP:
Converts ir_unop_saturate into min(max(x, 0.0), 1.0)
DOPS_TO_DFRAC:
Converts double trunc, ceil, floor, round to fract
Macro Definition Documentation
lowering
#define lowering (x) (this->lower & x)
Determine if a particular type of lowering should occur.
Referenced by lower_instructions().
Function Documentation
lower_instructions()
bool lower_instructions (exec_list * instructions, unsigned what_to_lower)
References ir_builder::abs(), ir_builder::add(), ir_builder::assign(), ir_builder::b2i(), ir_builder::bit_and(), BIT_COUNT_TO_MATH, ir_builder::bit_not(), ir_builder::bit_or(), ir_builder::bitcast_f2i(), ir_builder::bitcast_f2u(), ir_builder::bitcast_u2f(), ir_builder::bitfield_insert(), BORROW_TO_ARITH, ir_builder::carry(), CARRY_TO_ARITH, ir_builder::csel(), DDIV_TO_MUL_RCP, DFREXP_DLDEXP_TO_ARITH, DOPS_TO_DFRAC, ir_builder::equal(), ir_builder::exp(), EXP_TO_EXP2, ir_builder::expr(), EXTRACT_TO_SHIFTS, FDIV_TO_MUL_RCP, FIND_LSB_TO_FLOAT_CAST, FIND_MSB_TO_FLOAT_CAST, ir_builder::fma(), ir_builder::fract(), ir_builder::gequal(), ir_builder::greater(), ir_builder::i2u(), IMUL_HIGH_TO_MUL, INSERT_TO_SHIFTS, INT_DIV_TO_MUL_RCP, ir_unop_log, ir_unop_log2, LDEXP_TO_ARITH, ir_builder::less(), LOG_TO_LOG2, ir_builder::logic_and(), lowering, ir_builder::lshift(), MOD_TO_FLOOR, ir_builder::mul(), ir_builder::neg(), ir_builder::nequal(), POW_TO_EXP2, REVERSE_TO_SHIFTS, ir_builder::rshift(), SAT_TO_CLAMP, SQRT_TO_ABS_SQRT, ir_builder::sub(), SUB_TO_ADD_NEG, ir_builder::swizzle(), ir_builder::swizzle_y(), ir_builder::u2f(), ir_builder::u2i(), ir_builder::operand::val, visit_continue, visit_list_elements(), ir_builder::WRITEMASK_X, and ir_builder::WRITEMASK_Y.
Referenced by do_common_optimization(), and do_optimization().