Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_if_to_cond_assign.cpp File Reference
This flattens if-statements to conditional assignments if:
#include "compiler/glsl_types.h"
#include "ir.h"
#include "util/set.h"
#include "util/hash_table.h"
#include "main/macros.h"
Functions
bool lower_if_to_cond_assign (gl_shader_stage stage, exec_list *instructions, unsigned max_depth, unsigned min_branch_cost)
void check_ir_node (ir_instruction *ir, void *data)
void move_block_to_cond_assign (void *mem_ctx, ir_if *if_ir, ir_rvalue *cond_expr, exec_list *instructions, struct set *set)
Detailed Description
This flattens if-statements to conditional assignments if:
the GPU has limited or no flow control support (controlled by max_depth)
small conditional branches are more expensive than conditional assignments (controlled by min_branch_cost, that's the cost for a branch to be preserved)
It can't handle other control flow being inside of its block, such as calls or loops. Hopefully loop unrolling and inlining will take care of those.
Drivers for GPUs with no control flow support should simply call
lower_if_to_cond_assign(instructions)
to attempt to flatten all if-statements.
Some GPUs (such as i965 prior to gen6) do support control flow, but have a maximum nesting depth N. Drivers for such hardware can call
lower_if_to_cond_assign(instructions, N)
to attempt to flatten any if-statements appearing at depth > N.
Function Documentation
check_ir_node()
void check_ir_node (ir_instruction * ir, void * data)
Referenced by move_block_to_cond_assign().
lower_if_to_cond_assign()
bool lower_if_to_cond_assign (gl_shader_stage stage, exec_list * instructions, unsigned max_depth, unsigned min_branch_cost)
References visit_list_elements().
Referenced by do_optimization().
move_block_to_cond_assign()
void move_block_to_cond_assign (void * mem_ctx, ir_if * if_ir, ir_rvalue * cond_expr, exec_list * instructions, struct set * set)
References ir_builder::assign(), check_ir_node(), foreach_in_list, foreach_in_list_safe, visit_continue, and visit_tree().