Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_blend_equation_advanced.cpp File Reference
#include "ir.h"
#include "ir_builder.h"
#include "ir_optimization.h"
#include "ir_hierarchical_visitor.h"
#include "program/prog_instruction.h"
#include "program/prog_statevars.h"
#include "util/bitscan.h"
#include "builtin_functions.h"
Macros
#define imm1(x) new(mem_ctx) ir_constant((float) (x), 1)
#define imm3(x) new(mem_ctx) ir_constant((float) (x), 3)
Functions
static ir_rvalue * blend_multiply (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_screen (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_overlay (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_darken (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_lighten (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_colordodge (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_colorburn (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_hardlight (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_softlight (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_difference (ir_variable *src, ir_variable *dst)
static ir_rvalue * blend_exclusion (ir_variable *src, ir_variable *dst)
static ir_rvalue * minv3 (ir_variable *v)
static ir_rvalue * maxv3 (ir_variable *v)
static ir_rvalue * lumv3 (ir_variable *c)
static ir_rvalue * satv3 (ir_variable *c)
static void set_lum (ir_factory *f, ir_variable *color, ir_variable *cbase, ir_variable *clum)
static void set_lum_sat (ir_factory *f, ir_variable *color, ir_variable *cbase, ir_variable *csat, ir_variable *clum)
static ir_rvalue * is_mode (ir_variable *mode, enum gl_advanced_blend_mode q)
static ir_variable * calc_blend_result (ir_factory f, ir_variable *mode, ir_variable *fb, ir_rvalue *blend_src, GLbitfield blend_qualifiers)
static ir_dereference * deref_output (ir_variable *var)
Dereference var, or var[0] if it's an array.
static ir_function_signature * get_main (gl_linked_shader *sh)
bool lower_blend_equation_advanced (struct gl_linked_shader *sh)
Macro Definition Documentation
imm1
#define imm1 (x) new(mem_ctx) ir_constant((float) (x), 1)
Referenced by calc_blend_result(), set_lum(), and set_lum_sat().
imm3
#define imm3 (x) new(mem_ctx) ir_constant((float) (x), 3)
Referenced by blend_colorburn(), blend_colordodge(), blend_exclusion(), blend_hardlight(), blend_overlay(), blend_softlight(), calc_blend_result(), set_lum(), and set_lum_sat().
Function Documentation
blend_colorburn()
static ir_rvalue* blend_colorburn (ir_variable * src, ir_variable * dst) static
References ir_builder::csel(), ir_builder::div(), ir_builder::gequal(), imm3, ir_builder::lequal(), ir_builder::min2(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_colordodge()
static ir_rvalue* blend_colordodge (ir_variable * src, ir_variable * dst) static
References ir_builder::csel(), ir_builder::div(), ir_builder::gequal(), imm3, ir_builder::lequal(), ir_builder::min2(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_darken()
static ir_rvalue* blend_darken (ir_variable * src, ir_variable * dst) static
References ir_builder::min2().
Referenced by calc_blend_result().
blend_difference()
static ir_rvalue* blend_difference (ir_variable * src, ir_variable * dst) static
References ir_builder::abs(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_exclusion()
static ir_rvalue* blend_exclusion (ir_variable * src, ir_variable * dst) static
References ir_builder::add(), imm3, ir_builder::mul(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_hardlight()
static ir_rvalue* blend_hardlight (ir_variable * src, ir_variable * dst) static
References ir_builder::csel(), imm3, ir_builder::lequal(), ir_builder::mul(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_lighten()
static ir_rvalue* blend_lighten (ir_variable * src, ir_variable * dst) static
References ir_builder::max2().
Referenced by calc_blend_result().
blend_multiply()
static ir_rvalue* blend_multiply (ir_variable * src, ir_variable * dst) static
References ir_builder::mul().
Referenced by calc_blend_result().
blend_overlay()
static ir_rvalue* blend_overlay (ir_variable * src, ir_variable * dst) static
References ir_builder::csel(), imm3, ir_builder::lequal(), ir_builder::mul(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_screen()
static ir_rvalue* blend_screen (ir_variable * src, ir_variable * dst) static
References ir_builder::add(), ir_builder::mul(), and ir_builder::sub().
Referenced by calc_blend_result().
blend_softlight()
static ir_rvalue* blend_softlight (ir_variable * src, ir_variable * dst) static
References ir_builder::add(), ir_builder::csel(), imm3, ir_builder::lequal(), ir_builder::mul(), ir_builder::sqrt(), and ir_builder::sub().
Referenced by calc_blend_result().
calc_blend_result()
static ir_variable* calc_blend_result (ir_factory f, ir_variable * mode, ir_variable * fb, ir_rvalue * blend_src, GLbitfield blend_qualifiers) static
References ir_builder::add(), ir_builder::assign(), blend_colorburn(), blend_colordodge(), blend_darken(), blend_difference(), blend_exclusion(), blend_hardlight(), blend_lighten(), blend_multiply(), blend_overlay(), blend_screen(), blend_softlight(), ir_builder::csel(), ir_builder::div(), ir_builder::ir_factory::emit(), ir_builder::equal(), ir_builder::if_tree(), imm1, imm3, ir_builder::ir_factory::instructions, is_mode(), ir_builder::ir_factory::make_temp(), ir_builder::ir_factory::mem_ctx, ir_builder::mul(), set_lum(), set_lum_sat(), ir_builder::sub(), ir_builder::swizzle(), ir_builder::swizzle_w(), ir_builder::swizzle_xyz(), and ir_builder::WRITEMASK_W.
Referenced by lower_blend_equation_advanced().
deref_output()
static ir_dereference* deref_output (ir_variable * var) static
Dereference var, or var[0] if it's an array.
Referenced by lower_blend_equation_advanced().
get_main()
static ir_function_signature* get_main (gl_linked_shader * sh) static
References foreach_in_list.
Referenced by lower_blend_equation_advanced().
is_mode()
static ir_rvalue* is_mode (ir_variable * mode, enum gl_advanced_blend_mode q) static
References ir_builder::equal().
Referenced by calc_blend_result().
lower_blend_equation_advanced()
bool lower_blend_equation_advanced (struct gl_linked_shader * sh)
References ir_builder::assign(), calc_blend_result(), deref_output(), do_lower_jumps(), ir_builder::ir_factory::emit(), foreach_in_list, get_main(), main(), ir_builder::swizzle(), and validate_ir_tree().
lumv3()
static ir_rvalue* lumv3 (ir_variable * c) static
References ir_builder::dot().
Referenced by set_lum().
maxv3()
static ir_rvalue* maxv3 (ir_variable * v) static
References ir_builder::max2(), ir_builder::swizzle_x(), ir_builder::swizzle_y(), and ir_builder::swizzle_z().
Referenced by satv3(), and set_lum().
minv3()
static ir_rvalue* minv3 (ir_variable * v) static
References ir_builder::min2(), ir_builder::swizzle_x(), ir_builder::swizzle_y(), and ir_builder::swizzle_z().
Referenced by satv3(), set_lum(), and set_lum_sat().
satv3()
static ir_rvalue* satv3 (ir_variable * c) static
References maxv3(), minv3(), and ir_builder::sub().
Referenced by set_lum_sat().
set_lum()
static void set_lum (ir_factory * f, ir_variable * color, ir_variable * cbase, ir_variable * clum) static
References ir_builder::add(), ir_builder::assign(), ir_builder::div(), ir_builder::ir_factory::emit(), ir_builder::greater(), ir_builder::if_tree(), imm1, imm3, ir_builder::less(), lumv3(), ir_builder::ir_factory::make_temp(), maxv3(), ir_builder::ir_factory::mem_ctx, minv3(), ir_builder::mul(), and ir_builder::sub().
Referenced by calc_blend_result(), and set_lum_sat().
set_lum_sat()
static void set_lum_sat (ir_factory * f, ir_variable * color, ir_variable * cbase, ir_variable * csat, ir_variable * clum) static
References ir_builder::assign(), ir_builder::div(), ir_builder::ir_factory::emit(), ir_builder::greater(), ir_builder::if_tree(), imm1, imm3, ir_builder::ir_factory::make_temp(), ir_builder::ir_factory::mem_ctx, minv3(), ir_builder::mul(), satv3(), set_lum(), and ir_builder::sub().
Referenced by calc_blend_result().