Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_named_interface_blocks.cpp File Reference
This lowering pass converts all interface blocks with instance names into interface blocks without an instance name.
#include "glsl_symbol_table.h"
#include "ir.h"
#include "ir_optimization.h"
#include "ir_rvalue_visitor.h"
#include "util/hash_table.h"
Functions
static const glsl_type * process_array_type (const glsl_type *type, unsigned idx)
static ir_rvalue * process_array_ir (void *const mem_ctx, ir_dereference_array *deref_array_prev, ir_rvalue *deref_var)
void lower_named_interface_blocks (void *mem_ctx, gl_linked_shader *shader)
Detailed Description
This lowering pass converts all interface blocks with instance names into interface blocks without an instance name.
For example, the following shader:
out block { float block_var; } inst_name;
main() { inst_name.block_var = 0.0; }
Is rewritten to:
out block { float block_var; };
main() { block_var = 0.0; }
This takes place after the shader code has already been verified with the interface name in place.
The linking phase will use the interface block name rather than the interface's instance name when linking interfaces.
This modification to the ir allows our currently existing dead code elimination to work with interface blocks without changes.
Function Documentation
lower_named_interface_blocks()
void lower_named_interface_blocks (void * mem_ctx, gl_linked_shader * shader)
Referenced by link_shaders().
process_array_ir()
static ir_rvalue* process_array_ir (void *const mem_ctx, ir_dereference_array * deref_array_prev, ir_rvalue * deref_var) static
References foreach_in_list_safe, ir_rvalue_base_visitor::handle_rvalue(), process_array_type(), ir_rvalue_base_visitor::rvalue_visit(), ir_rvalue_visitor::visit_leave(), and visit_list_elements().
process_array_type()
static const glsl_type* process_array_type (const glsl_type * type, unsigned idx) static
Referenced by process_array_ir().