Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_variable_index_to_cond_assign.cpp File Reference
Turns non-constant indexing into array types to a series of conditional moves of each element into a temporary.
#include "ir.h"
#include "ir_rvalue_visitor.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
#include "main/macros.h"
Functions
ir_rvalue * compare_index_block (exec_list *instructions, ir_variable *index, unsigned base, unsigned components, void *mem_ctx)
Generate a comparison value for a block of indices.
static bool is_array_or_matrix (const ir_rvalue *ir)
bool lower_variable_index_to_cond_assign (gl_shader_stage stage, exec_list *instructions, bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
Detailed Description
Turns non-constant indexing into array types to a series of conditional moves of each element into a temporary.
Pre-DX10 GPUs often don't have a native way to do this operation, and this works around that.
The lowering process proceeds as follows. Each non-constant index found in an r-value is converted to a canonical form array[i]. Each element of the array is conditionally assigned to a temporary by comparing i to a constant index. This is done by cloning the canonical form and replacing all occurances of i with a constant. Each remaining occurance of the canonical form in the IR is replaced with a dereference of the temporary variable.
L-values with non-constant indices are handled similarly. In this case, the RHS of the assignment is assigned to a temporary. The non-constant index is replace with the canonical form (just like for r-values). The temporary is conditionally assigned to each element of the canonical form by comparing i with each index. The same clone-and-replace scheme is used.
Function Documentation
compare_index_block()
ir_rvalue* compare_index_block (exec_list * instructions, ir_variable * index, unsigned base, unsigned components, void * mem_ctx)
Generate a comparison value for a block of indices.
Lowering passes for non-constant indexing of arrays, matrices, or vectors can use this to generate blocks of index comparison values.
Parameters
instructions List where new instructions will be appended
index ir_variable containing the desired index
base Base value for this block of comparisons
components Number of unique index values to compare. This must be on the range [1, 4].
mem_ctx ralloc memory context to be used for all allocations.
Returns
An ir_rvalue that must be cloned for each use in conditional assignments, etc.
Referenced by is_array_or_matrix().
is_array_or_matrix()
static bool is_array_or_matrix (const ir_rvalue * ir) inline static
References ir_builder::assign(), compare_index_block(), ir_builder::less(), visit_continue, ir_rvalue_visitor::visit_leave(), and visit_stop.
lower_variable_index_to_cond_assign()
bool lower_variable_index_to_cond_assign (gl_shader_stage stage, exec_list * instructions, bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
References visit_list_elements().
Referenced by do_optimization().