Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
main.cpp File Reference
This file is the main() routine and scaffolding for producing builtin_compiler (which doesn't include builtins itself and is used to generate the profile information for builtin_function.cpp), and for glsl_compiler (which does include builtins and can be used to offline compile GLSL code and examine the resulting GLSL IR.
#include <stdio.h>
#include <getopt.h>
#include "main/mtypes.h"
#include "standalone.h"
Functions
void usage_fail (const char *name)
Print proper usage and exit with failure.
int main (int argc, char *const *argv)
Variables
static struct standalone_options options
const struct option compiler_opts []
Detailed Description
This file is the main() routine and scaffolding for producing builtin_compiler (which doesn't include builtins itself and is used to generate the profile information for builtin_function.cpp), and for glsl_compiler (which does include builtins and can be used to offline compile GLSL code and examine the resulting GLSL IR.
Function Documentation
main()
int main (int argc, char *const * argv)
References compiler_opts, standalone_options::glsl_version, options, standalone_compile_shader(), standalone_compiler_cleanup(), and usage_fail().
Referenced by link_intrastage_shaders(), and lower_blend_equation_advanced().
usage_fail()
void usage_fail (const char * name)
Print proper usage and exit with failure.
References compiler_opts.
Referenced by main().
Variable Documentation
compiler_opts
const struct option compiler_opts[]
Initial value:
= {
   { "dump-ast", no_argument, &options.dump_ast, 1 },
   { "dump-hir", no_argument, &options.dump_hir, 1 },
   { "dump-lir", no_argument, &options.dump_lir, 1 },
   { "dump-builder", no_argument, &options.dump_builder, 1 },
   { "link",     no_argument, &options.do_link,  1 },
   { "just-log", no_argument, &options.just_log, 1 },
   { "version",  required_argument, NULL, 'v' },
   { NULL, 0, NULL, 0 }
}
Referenced by main(), and usage_fail().
options
struct standalone_options options static
Referenced by _mesa_glsl_compile_shader(), link_varyings_and_uniforms(), main(), test_optpass(), try_replace_with_dot(), and loop_unroll_count::visit_enter().