Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
generate_ir Namespace Reference
Functions
ir_function_signature * udiv64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * idiv64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * umod64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * imod64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * umul64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * sign64 (void *mem_ctx, builtin_available_predicate avail)
ir_function_signature * udivmod64 (void *mem_ctx, builtin_available_predicate avail)
Function Documentation
idiv64()
ir_function_signature * generate_ir::idiv64 (void * mem_ctx, builtin_available_predicate avail)
Referenced by lower_64bit::lower_op_to_function_call().
imod64()
ir_function_signature * generate_ir::imod64 (void * mem_ctx, builtin_available_predicate avail)
Referenced by lower_64bit::lower_op_to_function_call().
sign64()
ir_function_signature * generate_ir::sign64 (void * mem_ctx, builtin_available_predicate avail)
Referenced by lower_64bit::lower_op_to_function_call().
udiv64()
ir_function_signature * generate_ir::udiv64 (void * mem_ctx, builtin_available_predicate avail)
Referenced by lower_64bit::lower_op_to_function_call().
udivmod64()
ir_function_signature* generate_ir::udivmod64 (void * mem_ctx, builtin_available_predicate avail)
umod64()
ir_function_signature * generate_ir::umod64 (void * mem_ctx, builtin_available_predicate avail)
Referenced by lower_64bit::lower_op_to_function_call().
umul64()
ir_function_signature * generate_ir::umul64 (void * mem_ctx, builtin_available_predicate avail)
Referenced by lower_64bit::lower_op_to_function_call().