Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
ir_builder Namespace Reference
Data Structures
class deref
Automatic generator for ir_dereference_variable on assignment LHS.
class ir_factory
class operand
This little class exists to let the helper expression generators take either an ir_rvalue * or an ir_variable * to be automatically dereferenced, while still providing compile-time type checking.
Enumerations
enum writemask { WRITEMASK_X = 0x1, WRITEMASK_Y = 0x2, WRITEMASK_Z = 0x4, WRITEMASK_W = 0x8 }
Functions
ir_assignment * assign (deref lhs, operand rhs, operand condition, int writemask)
ir_assignment * assign (deref lhs, operand rhs)
ir_assignment * assign (deref lhs, operand rhs, int writemask)
ir_assignment * assign (deref lhs, operand rhs, operand condition)
ir_return * ret (operand retval)
ir_swizzle * swizzle (operand a, int swizzle, int components)
ir_swizzle * swizzle_for_size (operand a, unsigned components)
Swizzle away later components, but preserve the ordering.
ir_swizzle * swizzle_xxxx (operand a)
ir_swizzle * swizzle_yyyy (operand a)
ir_swizzle * swizzle_zzzz (operand a)
ir_swizzle * swizzle_wwww (operand a)
ir_swizzle * swizzle_x (operand a)
ir_swizzle * swizzle_y (operand a)
ir_swizzle * swizzle_z (operand a)
ir_swizzle * swizzle_w (operand a)
ir_swizzle * swizzle_xy (operand a)
ir_swizzle * swizzle_xyz (operand a)
ir_swizzle * swizzle_xyzw (operand a)
ir_expression * expr (ir_expression_operation op, operand a)
ir_expression * expr (ir_expression_operation op, operand a, operand b)
ir_expression * expr (ir_expression_operation op, operand a, operand b, operand c)
ir_expression * add (operand a, operand b)
ir_expression * sub (operand a, operand b)
ir_expression * min2 (operand a, operand b)
ir_expression * max2 (operand a, operand b)
ir_expression * mul (operand a, operand b)
ir_expression * imul_high (operand a, operand b)
ir_expression * div (operand a, operand b)
ir_expression * carry (operand a, operand b)
ir_expression * borrow (operand a, operand b)
ir_expression * trunc (operand a)
ir_expression * round_even (operand a)
ir_expression * fract (operand a)
ir_expression * dot (operand a, operand b)
ir_expression * clamp (operand a, operand b, operand c)
ir_expression * saturate (operand a)
ir_expression * abs (operand a)
ir_expression * neg (operand a)
ir_expression * sin (operand a)
ir_expression * cos (operand a)
ir_expression * exp (operand a)
ir_expression * rcp (operand a)
ir_expression * rsq (operand a)
ir_expression * sqrt (operand a)
ir_expression * log (operand a)
ir_expression * sign (operand a)
ir_expression * subr_to_int (operand a)
ir_expression * equal (operand a, operand b)
ir_expression * nequal (operand a, operand b)
ir_expression * less (operand a, operand b)
ir_expression * greater (operand a, operand b)
ir_expression * lequal (operand a, operand b)
ir_expression * gequal (operand a, operand b)
ir_expression * logic_not (operand a)
ir_expression * logic_and (operand a, operand b)
ir_expression * logic_or (operand a, operand b)
ir_expression * bit_not (operand a)
ir_expression * bit_and (operand a, operand b)
ir_expression * bit_or (operand a, operand b)
ir_expression * bit_xor (operand a, operand b)
ir_expression * lshift (operand a, operand b)
ir_expression * rshift (operand a, operand b)
ir_expression * f2i (operand a)
ir_expression * bitcast_f2i (operand a)
ir_expression * i2f (operand a)
ir_expression * bitcast_i2f (operand a)
ir_expression * i2u (operand a)
ir_expression * u2i (operand a)
ir_expression * f2u (operand a)
ir_expression * bitcast_f2u (operand a)
ir_expression * u2f (operand a)
ir_expression * bitcast_u2f (operand a)
ir_expression * i2b (operand a)
ir_expression * b2i (operand a)
ir_expression * f2b (operand a)
ir_expression * b2f (operand a)
ir_expression * bitcast_d2i64 (operand a)
ir_expression * bitcast_d2u64 (operand a)
ir_expression * bitcast_i642d (operand a)
ir_expression * bitcast_u642d (operand a)
ir_expression * interpolate_at_centroid (operand a)
ir_expression * interpolate_at_offset (operand a, operand b)
ir_expression * interpolate_at_sample (operand a, operand b)
ir_expression * f2d (operand a)
ir_expression * i2d (operand a)
ir_expression * u2d (operand a)
ir_expression * fma (operand a, operand b, operand c)
ir_expression * lrp (operand x, operand y, operand a)
ir_expression * csel (operand a, operand b, operand c)
ir_expression * bitfield_extract (operand a, operand b, operand c)
ir_expression * bitfield_insert (operand a, operand b, operand c, operand d)
ir_if * if_tree (operand condition, ir_instruction *then_branch)
ir_if * if_tree (operand condition, ir_instruction *then_branch, ir_instruction *else_branch)
Enumeration Type Documentation
writemask
enum ir_builder::writemask
Enumerator
WRITEMASK_X
WRITEMASK_Y
WRITEMASK_Z
WRITEMASK_W
Function Documentation
abs()
ir_expression * ir_builder::abs (operand a)
References expr().
Referenced by blend_difference(), link_assign_atomic_counter_resources(), link_check_atomic_counter_resources(), lower_instructions(), try_replace_with_dot(), and UNOP().
add()
ir_expression * ir_builder::add (operand a, operand b)
References expr().
Referenced by blend_exclusion(), blend_screen(), blend_softlight(), calc_blend_result(), calculate_iterations(), lower_buffer_access::lower_buffer_access::emit_access(), idiv64(), imod64(), initialize_cs_derived_variables(), lower_instructions(), set_lum(), lower_buffer_access::lower_buffer_access::setup_buffer_access(), try_replace_with_dot(), udiv64(), udivmod64(), umod64(), umul64(), and UNOP().
assign() [1/4]
ir_assignment * ir_builder::assign (deref lhs, operand rhs, operand condition, int writemask)
References ir_builder::ir_factory::mem_ctx, ir_builder::operand::val, and ir_builder::deref::val.
Referenced by assign(), calc_blend_result(), lower_64bit::compact_destination(), do_assignment(), do_mat_op_to_vec(), emit_inline_record_constructor(), lower_64bit::expand_source(), find_initial_value(), lower_offset_array_visitor::handle_rvalue(), ir_expression_flattening_visitor::handle_rvalue(), has_matrix_operand(), ast_case_statement_list::hir(), idiv64(), imod64(), initialize_cs_derived_variables(), is_array_or_matrix(), is_extended_swizzle(), lower_blend_equation_advanced(), lower_instructions(), move_block_to_cond_assign(), replace_return_with_assignment(), set_lum(), set_lum_sat(), sign64(), try_replace_with_dot(), udiv64(), udivmod64(), umod64(), umul64(), and UNOP().
assign() [2/4]
ir_assignment * ir_builder::assign (deref lhs, operand rhs)
References assign(), and ir_builder::deref::val.
assign() [3/4]
ir_assignment * ir_builder::assign (deref lhs, operand rhs, int writemask)
References assign().
assign() [4/4]
ir_assignment * ir_builder::assign (deref lhs, operand rhs, operand condition)
References assign(), and ir_builder::deref::val.
b2f()
ir_expression * ir_builder::b2f (operand a)
References expr().
Referenced by try_replace_with_dot().
b2i()
ir_expression * ir_builder::b2i (operand a)
References expr().
Referenced by lower_instructions().
bit_and()
ir_expression * ir_builder::bit_and (operand a, operand b)
References expr().
Referenced by lower_instructions(), and UNOP().
bit_not()
ir_expression * ir_builder::bit_not (operand a)
References expr().
Referenced by lower_instructions().
bit_or()
ir_expression * ir_builder::bit_or (operand a, operand b)
References expr().
Referenced by idiv64(), imod64(), lower_instructions(), sign64(), udiv64(), udivmod64(), umod64(), and UNOP().
bit_xor()
ir_expression * ir_builder::bit_xor (operand a, operand b)
References expr().
bitcast_d2i64()
ir_expression * ir_builder::bitcast_d2i64 (operand a)
References expr().
bitcast_d2u64()
ir_expression * ir_builder::bitcast_d2u64 (operand a)
References expr().
bitcast_f2i()
ir_expression * ir_builder::bitcast_f2i (operand a)
References expr().
Referenced by lower_instructions(), and UNOP().
bitcast_f2u()
ir_expression * ir_builder::bitcast_f2u (operand a)
References expr().
Referenced by lower_instructions(), and UNOP().
bitcast_i2f()
ir_expression * ir_builder::bitcast_i2f (operand a)
References expr().
bitcast_i642d()
ir_expression * ir_builder::bitcast_i642d (operand a)
References expr().
bitcast_u2f()
ir_expression * ir_builder::bitcast_u2f (operand a)
References expr().
Referenced by lower_instructions(), and UNOP().
bitcast_u642d()
ir_expression * ir_builder::bitcast_u642d (operand a)
References expr().
bitfield_extract()
ir_expression * ir_builder::bitfield_extract (operand a, operand b, operand c)
References expr().
bitfield_insert()
ir_expression * ir_builder::bitfield_insert (operand a, operand b, operand c, operand d)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
Referenced by lower_instructions().
borrow()
ir_expression * ir_builder::borrow (operand a, operand b)
References expr().
Referenced by UNOP().
carry()
ir_expression * ir_builder::carry (operand a, operand b)
References expr().
Referenced by lower_instructions(), and UNOP().
clamp()
ir_expression * ir_builder::clamp (operand a, operand b, operand c)
References expr().
cos()
ir_expression * ir_builder::cos (operand a)
References expr(), and ir_unop_cos.
csel()
ir_expression * ir_builder::csel (operand a, operand b, operand c)
References expr().
Referenced by blend_colorburn(), blend_colordodge(), blend_hardlight(), blend_overlay(), blend_softlight(), calc_blend_result(), lower_instructions(), and UNOP().
div()
ir_expression * ir_builder::div (operand a, operand b)
References expr().
Referenced by blend_colorburn(), blend_colordodge(), calc_blend_result(), calculate_iterations(), set_lum(), and set_lum_sat().
dot()
ir_expression * ir_builder::dot (operand a, operand b)
References expr(), and ir_builder::operand::val.
Referenced by lumv3(), and try_replace_with_dot().
equal()
ir_expression * ir_builder::equal (operand a, operand b)
References expr().
Referenced by calc_blend_result(), idiv64(), imod64(), is_mode(), lower_instructions(), lower_subroutine(), udiv64(), udivmod64(), and umod64().
exp()
ir_expression * ir_builder::exp (operand a)
References expr().
Referenced by ast_case_statement_list::hir(), and lower_instructions().
expr() [1/3]
ir_expression * ir_builder::expr (ir_expression_operation op, operand a)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
Referenced by __read_expression(), _mesa_ast_set_aggregate_type(), _mesa_glsl_read_ir(), abs(), add(), always_available(), ast_cs_input_layout::ast_cs_input_layout(), b2f(), b2i(), bit_and(), bit_not(), bit_or(), bit_xor(), bitcast_d2i64(), bitcast_d2u64(), bitcast_f2i(), bitcast_f2u(), bitcast_i2f(), bitcast_i642d(), bitcast_u2f(), bitcast_u642d(), bitfield_extract(), borrow(), carry(), clamp(), lower_64bit::compact_destination(), cos(), csel(), div(), do_mat_op_to_vec(), dot(), equal(), exp(), lower_64bit::expand_source(), f2b(), f2d(), f2i(), f2u(), fix_parameter(), fma(), fract(), gequal(), get_image_available_predicate(), get_scalar_boolean_operand(), greater(), handle_expression(), lower_noise_visitor::handle_rvalue(), i2b(), i2d(), i2f(), i2u(), idiv64(), imod64(), imul_high(), interpolate_at_centroid(), interpolate_at_offset(), interpolate_at_sample(), ir_constant_fold(), is_extended_swizzle(), is_reduction(), is_simple_operand(), lequal(), less(), log(), logic_and(), logic_not(), logic_or(), lower_instructions(), lrp(), lshift(), mat_op_to_vec_predicate(), s_pattern::match(), max2(), min2(), mul(), neg(), nequal(), s_list::print(), rcp(), read_atom(), rewrite_swizzle(), round_even(), rshift(), rsq(), s_match(), s_pattern::s_pattern(), saturate(), sign(), sign64(), sin(), sqrt(), sub(), subr_to_int(), trunc(), try_max_zero(), try_min_one(), try_replace_with_dot(), u2d(), u2f(), u2i(), udiv64(), udivmod64(), umod64(), UNOP(), and update_types().
expr() [2/3]
ir_expression * ir_builder::expr (ir_expression_operation op, operand a, operand b)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
expr() [3/3]
ir_expression * ir_builder::expr (ir_expression_operation op, operand a, operand b, operand c)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
f2b()
ir_expression * ir_builder::f2b (operand a)
References expr().
f2d()
ir_expression * ir_builder::f2d (operand a)
References expr().
f2i()
ir_expression * ir_builder::f2i (operand a)
References expr().
f2u()
ir_expression * ir_builder::f2u (operand a)
References expr().
fma()
ir_expression * ir_builder::fma (operand a, operand b, operand c)
References expr().
Referenced by lower_instructions(), and UNOP().
fract()
ir_expression * ir_builder::fract (operand a)
References expr().
Referenced by lower_instructions().
gequal()
ir_expression * ir_builder::gequal (operand a, operand b)
References expr().
Referenced by blend_colorburn(), blend_colordodge(), idiv64(), imod64(), lower_instructions(), udiv64(), udivmod64(), and umod64().
greater()
ir_expression * ir_builder::greater (operand a, operand b)
References expr().
Referenced by lower_instructions(), set_lum(), and set_lum_sat().
i2b()
ir_expression * ir_builder::i2b (operand a)
References expr().
i2d()
ir_expression * ir_builder::i2d (operand a)
References expr().
i2f()
ir_expression * ir_builder::i2f (operand a)
References expr().
i2u()
ir_expression * ir_builder::i2u (operand a)
References expr().
Referenced by lower_instructions(), and lower_buffer_access::lower_buffer_access::setup_buffer_access().
if_tree() [1/2]
ir_if * ir_builder::if_tree (operand condition, ir_instruction * then_branch)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
Referenced by calc_blend_result(), lower_subroutine(), set_lum(), and set_lum_sat().
if_tree() [2/2]
ir_if * ir_builder::if_tree (operand condition, ir_instruction * then_branch, ir_instruction * else_branch)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
imul_high()
ir_expression * ir_builder::imul_high (operand a, operand b)
References expr().
Referenced by umul64(), and UNOP().
interpolate_at_centroid()
ir_expression * ir_builder::interpolate_at_centroid (operand a)
References expr().
Referenced by UNOP().
interpolate_at_offset()
ir_expression * ir_builder::interpolate_at_offset (operand a, operand b)
References expr().
Referenced by UNOP().
interpolate_at_sample()
ir_expression * ir_builder::interpolate_at_sample (operand a, operand b)
References expr().
Referenced by UNOP().
lequal()
ir_expression * ir_builder::lequal (operand a, operand b)
References expr().
Referenced by blend_colorburn(), blend_colordodge(), blend_hardlight(), blend_overlay(), blend_softlight(), idiv64(), imod64(), udiv64(), udivmod64(), and umod64().
less()
ir_expression * ir_builder::less (operand a, operand b)
References expr().
Referenced by idiv64(), imod64(), is_array_or_matrix(), lower_instructions(), set_lum(), udiv64(), udivmod64(), and umod64().
log()
ir_expression * ir_builder::log (operand a)
References expr(), and ir_unop_log.
logic_and()
ir_expression * ir_builder::logic_and (operand a, operand b)
References expr().
Referenced by idiv64(), imod64(), lower_instructions(), opt_flatten_nested_if_blocks(), try_replace_with_dot(), udiv64(), udivmod64(), and umod64().
logic_not()
ir_expression * ir_builder::logic_not (operand a)
References expr().
Referenced by try_replace_with_dot().
logic_or()
ir_expression * ir_builder::logic_or (operand a, operand b)
References expr().
Referenced by try_replace_with_dot().
lrp()
ir_expression * ir_builder::lrp (operand x, operand y, operand a)
References expr().
Referenced by try_replace_with_dot().
lshift()
ir_expression * ir_builder::lshift (operand a, operand b)
References expr().
Referenced by idiv64(), imod64(), lower_instructions(), udiv64(), udivmod64(), and umod64().
max2()
ir_expression * ir_builder::max2 (operand a, operand b)
References expr().
Referenced by blend_lighten(), maxv3(), and UNOP().
min2()
ir_expression * ir_builder::min2 (operand a, operand b)
References expr().
Referenced by blend_colorburn(), blend_colordodge(), blend_darken(), minv3(), and UNOP().
mul()
ir_expression * ir_builder::mul (operand a, operand b)
References expr().
Referenced by blend_exclusion(), blend_hardlight(), blend_multiply(), blend_overlay(), blend_screen(), blend_softlight(), calc_blend_result(), calculate_iterations(), initialize_cs_derived_variables(), lower_instructions(), set_lum(), set_lum_sat(), lower_buffer_access::lower_buffer_access::setup_buffer_access(), try_replace_with_dot(), umul64(), and UNOP().
neg()
ir_expression * ir_builder::neg (operand a)
References expr().
Referenced by idiv64(), imod64(), lower_instructions(), try_replace_with_dot(), and UNOP().
nequal()
ir_expression * ir_builder::nequal (operand a, operand b)
References expr().
Referenced by idiv64(), imod64(), lower_instructions(), sign64(), and UNOP().
rcp()
ir_expression * ir_builder::rcp (operand a)
References expr().
ret()
ir_return * ir_builder::ret (operand retval)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
Referenced by blob_read_bytes(), blob_read_intptr(), blob_read_string(), blob_read_uint32(), blob_read_uint64(), blob_reserve_bytes(), check_explicit_uniform_locations(), constant_copy(), get_image_available_predicate(), ast_jump_statement::hir(), idiv64(), imod64(), integer_functions_supported(), replace_return_with_assignment(), sign64(), udiv64(), udivmod64(), umod64(), umul64(), and UNOP().
round_even()
ir_expression * ir_builder::round_even (operand a)
References expr().
rshift()
ir_expression * ir_builder::rshift (operand a, operand b)
References expr().
Referenced by lower_instructions(), sign64(), and UNOP().
rsq()
ir_expression * ir_builder::rsq (operand a)
References expr().
Referenced by try_replace_with_dot().
saturate()
ir_expression * ir_builder::saturate (operand a)
References expr().
Referenced by try_replace_with_dot().
sign()
ir_expression * ir_builder::sign (operand a)
References expr().
sin()
ir_expression * ir_builder::sin (operand a)
References expr().
sqrt()
ir_expression * ir_builder::sqrt (operand a)
References expr().
Referenced by blend_softlight(), and try_replace_with_dot().
sub()
ir_expression * ir_builder::sub (operand a, operand b)
References expr().
Referenced by _mesa_glsl_read_ir(), always_available(), blend_colorburn(), blend_colordodge(), blend_difference(), blend_exclusion(), blend_hardlight(), blend_overlay(), blend_screen(), blend_softlight(), calc_blend_result(), calculate_iterations(), idiv64(), imod64(), lower_instructions(), satv3(), set_lum(), set_lum_sat(), udiv64(), udivmod64(), umod64(), and UNOP().
subr_to_int()
ir_expression * ir_builder::subr_to_int (operand a)
References expr().
Referenced by lower_subroutine().
swizzle()
ir_swizzle * ir_builder::swizzle (operand a, int swizzle, int components)
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
Referenced by calc_blend_result(), lower_64bit::expand_source(), imod64(), lower_blend_equation_advanced(), lower_instructions(), swizzle_w(), swizzle_wwww(), swizzle_x(), swizzle_xxxx(), swizzle_xy(), swizzle_xyz(), swizzle_xyzw(), swizzle_y(), swizzle_yyyy(), swizzle_z(), swizzle_zzzz(), type_is_signed(), umod64(), and UNOP().
swizzle_for_size()
ir_swizzle * ir_builder::swizzle_for_size (operand a, unsigned components)
Swizzle away later components, but preserve the ordering.
References ir_builder::ir_factory::mem_ctx, and ir_builder::operand::val.
Referenced by UNOP().
swizzle_w()
ir_swizzle * ir_builder::swizzle_w (operand a)
References swizzle().
Referenced by calc_blend_result(), and lower_offset_array_visitor::handle_rvalue().
swizzle_wwww()
ir_swizzle * ir_builder::swizzle_wwww (operand a)
References swizzle().
swizzle_x()
ir_swizzle * ir_builder::swizzle_x (operand a)
References swizzle().
Referenced by idiv64(), imod64(), initialize_cs_derived_variables(), maxv3(), minv3(), sign64(), udiv64(), udivmod64(), umod64(), and umul64().
swizzle_xxxx()
ir_swizzle * ir_builder::swizzle_xxxx (operand a)
References swizzle().
swizzle_xy()
ir_swizzle * ir_builder::swizzle_xy (operand a)
References swizzle().
swizzle_xyz()
ir_swizzle * ir_builder::swizzle_xyz (operand a)
References swizzle().
Referenced by calc_blend_result().
swizzle_xyzw()
ir_swizzle * ir_builder::swizzle_xyzw (operand a)
References swizzle().
swizzle_y()
ir_swizzle * ir_builder::swizzle_y (operand a)
References swizzle().
Referenced by idiv64(), imod64(), initialize_cs_derived_variables(), lower_instructions(), maxv3(), minv3(), sign64(), udiv64(), udivmod64(), umod64(), and umul64().
swizzle_yyyy()
ir_swizzle * ir_builder::swizzle_yyyy (operand a)
References swizzle().
swizzle_z()
ir_swizzle * ir_builder::swizzle_z (operand a)
References swizzle().
Referenced by initialize_cs_derived_variables(), maxv3(), and minv3().
swizzle_zzzz()
ir_swizzle * ir_builder::swizzle_zzzz (operand a)
References swizzle().
trunc()
ir_expression * ir_builder::trunc (operand a)
References expr().
Referenced by try_replace_with_dot().
u2d()
ir_expression * ir_builder::u2d (operand a)
References expr().
u2f()
ir_expression * ir_builder::u2f (operand a)
References expr().
Referenced by lower_instructions().
u2i()
ir_expression * ir_builder::u2i (operand a)
References expr().
Referenced by lower_instructions().