Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
linker Namespace Reference
Functions
gl_uniform_storage * get_storage (struct gl_shader_program *prog, const char *name)
void copy_constant_to_storage (union gl_constant_value *storage, const ir_constant *val, const enum glsl_base_type base_type, const unsigned int elements, unsigned int boolean_true)
void set_opaque_binding (void *mem_ctx, gl_shader_program *prog, const glsl_type *type, const char *name, int *binding)
Initialize an opaque uniform from the value of an explicit binding qualifier specified in the shader.
void set_block_binding (gl_shader_program *prog, const char *block_name, unsigned mode, int binding)
void set_uniform_initializer (void *mem_ctx, gl_shader_program *prog, const char *name, const glsl_type *type, ir_constant *val, unsigned int boolean_true)
void populate_consumer_input_sets (void *mem_ctx, exec_list *ir, hash_table *consumer_inputs, hash_table *consumer_interface_inputs, ir_variable *consumer_inputs_with_locations[VARYING_SLOT_TESS_MAX])
ir_variable * get_matching_input (void *mem_ctx, const ir_variable *output_var, hash_table *consumer_inputs, hash_table *consumer_interface_inputs, ir_variable *consumer_inputs_with_locations[VARYING_SLOT_TESS_MAX])
Find a variable from the consumer that "matches" the specified variable.
Function Documentation
copy_constant_to_storage()
void linker::copy_constant_to_storage (union gl_constant_value * storage, const ir_constant * val, const enum glsl_base_type base_type, const unsigned int elements, unsigned int boolean_true)
Referenced by set_uniform_initializer().
get_matching_input()
ir_variable* linker::get_matching_input (void * mem_ctx, const ir_variable * output_var, hash_table * consumer_inputs, hash_table * consumer_interface_inputs, ir_variable * consumer_inputs_with_locations[VARYING_SLOT_TESS_MAX])
Find a variable from the consumer that "matches" the specified variable.
This function only finds inputs with names that match. There is no validation (here) that the types, etc. are compatible.
Referenced by assign_varying_locations().
get_storage()
gl_uniform_storage* linker::get_storage (struct gl_shader_program * prog, const char * name)
Referenced by set_opaque_binding(), and set_uniform_initializer().
populate_consumer_input_sets()
void linker::populate_consumer_input_sets (void * mem_ctx, exec_list * ir, hash_table * consumer_inputs, hash_table * consumer_interface_inputs, ir_variable * consumer_inputs_with_locations[VARYING_SLOT_TESS_MAX])
References foreach_in_list.
Referenced by assign_varying_locations().
set_block_binding()
void linker::set_block_binding (gl_shader_program * prog, const char * block_name, unsigned mode, int binding)
Referenced by link_set_uniform_initializers().
set_opaque_binding()
void linker::set_opaque_binding (void * mem_ctx, gl_shader_program * prog, const glsl_type * type, const char * name, int * binding)
Initialize an opaque uniform from the value of an explicit binding qualifier specified in the shader.
Atomic counters are different because they have no storage and should be handled elsewhere.
References gl_opaque_uniform_index::active, gl_uniform_storage::array_elements, get_storage(), gl_opaque_uniform_index::index, gl_uniform_storage::opaque, gl_uniform_storage::storage, and gl_uniform_storage::type.
Referenced by link_set_uniform_initializers().
set_uniform_initializer()
void linker::set_uniform_initializer (void * mem_ctx, gl_shader_program * prog, const char * name, const glsl_type * type, ir_constant * val, unsigned int boolean_true)
References gl_opaque_uniform_index::active, gl_uniform_storage::array_elements, copy_constant_to_storage(), get_storage(), gl_opaque_uniform_index::index, gl_uniform_storage::opaque, gl_uniform_storage::storage, and gl_uniform_storage::type.
Referenced by link_set_uniform_initializers().