Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
lower_64bit Namespace Reference
Functions
void expand_source (ir_factory &, ir_rvalue *val, ir_variable **expanded_src)
Expand individual 64-bit values to uvec2 values.
ir_dereference_variable * compact_destination (ir_factory &, const glsl_type *type, ir_variable *result[4])
Convert a series of uvec2 results into a single 64-bit integer vector.
ir_rvalue * lower_op_to_function_call (ir_instruction *base_ir, ir_expression *ir, ir_function_signature *callee)
Function Documentation
compact_destination()
ir_dereference_variable * lower_64bit::compact_destination (ir_factory & body, const glsl_type * type, ir_variable * result[4])
Convert a series of uvec2 results into a single 64-bit integer vector.
References ir_builder::assign(), ir_builder::ir_factory::emit(), ir_builder::expr(), and ir_builder::ir_factory::make_temp().
Referenced by lower_op_to_function_call().
expand_source()
void lower_64bit::expand_source (ir_factory & body, ir_rvalue * val, ir_variable ** expanded_src)
Expand individual 64-bit values to uvec2 values.
Each operation is in one of a few forms.
vector op vector
vector op scalar
scalar op vector
scalar op scalar
In the 'vector op vector' case, the two vectors must have the same size. In a way, the 'scalar op scalar' form is special case of the 'vector op vector' form.
This method generates a new set of uvec2 values for each element of a single operand. If the operand is a scalar, the uvec2 is replicated multiple times. A value like
u64vec3(a) + u64vec3(b)
becomes
u64vec3 tmp0 = u64vec3(a) + u64vec3(b);
uvec2 tmp1 = unpackUint2x32(tmp0.x);
uvec2 tmp2 = unpackUint2x32(tmp0.y);
uvec2 tmp3 = unpackUint2x32(tmp0.z);
and the returned operands array contains ir_variable pointers to
{ tmp1, tmp2, tmp3, tmp1 }
References ir_builder::assign(), ir_builder::ir_factory::emit(), ir_builder::expr(), ir_builder::ir_factory::make_temp(), and ir_builder::swizzle().
Referenced by lower_op_to_function_call().
lower_op_to_function_call()
ir_rvalue * lower_64bit::lower_op_to_function_call (ir_instruction * base_ir, ir_expression * ir, ir_function_signature * callee)
References compact_destination(), DIV64, ir_builder::ir_factory::emit(), expand_source(), exec_list::head_sentinel, generate_ir::idiv64(), generate_ir::imod64(), is_integer_64(), lowering, ir_builder::ir_factory::make_temp(), MOD64, MUL64, exec_node::next, exec_node::prev, SIGN64, generate_ir::sign64(), exec_list::tail_sentinel, generate_ir::udiv64(), generate_ir::umod64(), and generate_ir::umul64().