Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_dead_builtin_varyings.cpp File Reference
This eliminates the built-in shader outputs which are either not written at all or not used by the next stage.
#include "main/core.h"
#include "ir.h"
#include "ir_rvalue_visitor.h"
#include "ir_optimization.h"
#include "ir_print_visitor.h"
#include "compiler/glsl_types.h"
#include "link_varyings.h"
Functions
static void lower_texcoord_array (struct gl_linked_shader *shader, const varying_info_visitor *info)
static void lower_fragdata_array (struct gl_linked_shader *shader)
void do_dead_builtin_varyings (struct gl_context *ctx, gl_linked_shader *producer, gl_linked_shader *consumer, unsigned num_tfeedback_decls, tfeedback_decl *tfeedback_decls)
Detailed Description
This eliminates the built-in shader outputs which are either not written at all or not used by the next stage.
It also eliminates unused elements of gl_TexCoord inputs, which reduces the overall varying usage. The varyings handled here are the primary and secondary color, the fog, and the texture coordinates (gl_TexCoord).
This pass is necessary, because the Mesa GLSL linker cannot eliminate built-in varyings like it eliminates user-defined varyings, because the built-in varyings have pre-assigned locations. Also, the elimination of unused gl_TexCoord elements requires its own lowering pass anyway.
It's implemented by replacing all occurrences of dead varyings with temporary variables, which creates dead code. It is recommended to run a dead-code elimination pass after this.
If any texture coordinate slots can be eliminated, the gl_TexCoord array is broken down into separate vec4 variables with locations equal to VARYING_SLOT_TEX0 + i.
The same is done for the gl_FragData fragment shader output.
Function Documentation
do_dead_builtin_varyings()
void do_dead_builtin_varyings (struct gl_context * ctx, gl_linked_shader * producer, gl_linked_shader * consumer, unsigned num_tfeedback_decls, tfeedback_decl * tfeedback_decls)
References lower_fragdata_array(), and lower_texcoord_array().
Referenced by link_varyings().
lower_fragdata_array()
static void lower_fragdata_array (struct gl_linked_shader * shader) static
Referenced by do_dead_builtin_varyings().
lower_texcoord_array()
static void lower_texcoord_array (struct gl_linked_shader * shader, const varying_info_visitor * info) static
Referenced by do_dead_builtin_varyings().