Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_constant_variable.cpp File Reference
Marks variables assigned a single constant value over the course of the program as constant.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
#include "util/hash_table.h"
Functions
static struct assignment_entry * get_assignment_entry (ir_variable *var, struct hash_table *ht)
bool do_constant_variable (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_constant_variable_unlinked (exec_list *instructions)
Detailed Description
Marks variables assigned a single constant value over the course of the program as constant.
The goal here is to trigger further constant folding and then dead code elimination. This is common with vector/matrix constructors and calls to builtin functions.
Function Documentation
do_constant_variable()
bool do_constant_variable (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
Referenced by do_common_optimization(), do_constant_variable_unlinked(), and do_optimization().
do_constant_variable_unlinked()
bool do_constant_variable_unlinked (exec_list * instructions)
References do_constant_variable(), and foreach_in_list.
Referenced by do_common_optimization(), and do_optimization().
get_assignment_entry()
static struct assignment_entry* get_assignment_entry (ir_variable * var, struct hash_table * ht) static
References foreach_two_lists, visit_continue, and visit_continue_with_parent.