Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_tree_grafting.cpp File Reference
Takes assignments to variables that are dereferenced only once and pastes the RHS expression into where the variable is dereferenced.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_variable_refcount.h"
#include "ir_basic_block.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
Functions
bool do_tree_grafting (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
Detailed Description
Takes assignments to variables that are dereferenced only once and pastes the RHS expression into where the variable is dereferenced.
In the process of various operations like function inlining and tertiary op handling, we'll end up with our expression trees having been chopped up into a series of assignments of short expressions to temps. Other passes like ir_algebraic.cpp would prefer to see the deepest expression trees they can to try to optimize them.
This is a lot like copy propagaton. In comparison, copy propagation only acts on plain copies, not arbitrary expressions on the RHS. Generally, we wouldn't want to go pasting some complicated expression everywhere it got used, though, so we don't handle expressions in that pass.
The hard part is making sure we don't move an expression across some other assignments that would change the value of the expression. So we split this into two passes: First, find the variables in our scope which are written to once and read once, and then go through basic blocks seeing if we find an opportunity to move those expressions safely.
Function Documentation
do_tree_grafting()
bool do_tree_grafting (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References call_for_basic_blocks(), and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().