Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_algebraic.cpp File Reference
Takes advantage of association, commutivity, and other algebraic properties to simplify expressions.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_rvalue_visitor.h"
#include "ir_optimization.h"
#include "ir_builder.h"
#include "compiler/glsl_types.h"
Macros
#define HANDLE_PACK_UNPACK_INVERSE(inverse_operation)
Functions
static bool is_vec_zero (ir_constant *ir)
static bool is_vec_one (ir_constant *ir)
static bool is_vec_two (ir_constant *ir)
static bool is_vec_four (ir_constant *ir)
static bool is_vec_negative_one (ir_constant *ir)
static bool is_valid_vec_const (ir_constant *ir)
static bool is_less_than_one (ir_constant *ir)
static bool is_greater_than_zero (ir_constant *ir)
static void update_type (ir_expression *ir)
static ir_expression * try_replace_with_dot (ir_expression *expr0, ir_expression *expr1, void *mem_ctx)
bool do_algebraic (exec_list *instructions, bool native_integers, const struct gl_shader_compiler_options *options)
Detailed Description
Takes advantage of association, commutivity, and other algebraic properties to simplify expressions.
Macro Definition Documentation
HANDLE_PACK_UNPACK_INVERSE
#define HANDLE_PACK_UNPACK_INVERSE (inverse_operation)
Value:
{                                                                 \
         ir_expression *const op = ir->operands[0]->as_expression();    \
         if (op == NULL)                                                \
            break;                                                      \
         if (op->operation == (inverse_operation))                      \
            return op->operands[0];                                     \
         break;                                                         \
      }
Referenced by try_replace_with_dot().
Function Documentation
do_algebraic()
bool do_algebraic (exec_list * instructions, bool native_integers, const struct gl_shader_compiler_options * options)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
is_greater_than_zero()
static bool is_greater_than_zero (ir_constant * ir) inline static
References is_valid_vec_const().
Referenced by try_replace_with_dot().
is_less_than_one()
static bool is_less_than_one (ir_constant * ir) inline static
References is_valid_vec_const().
Referenced by try_replace_with_dot().
is_valid_vec_const()
static bool is_valid_vec_const (ir_constant * ir) inline static
Referenced by is_greater_than_zero(), and is_less_than_one().
is_vec_four()
static bool is_vec_four (ir_constant * ir) inline static
Referenced by try_replace_with_dot().
is_vec_negative_one()
static bool is_vec_negative_one (ir_constant * ir) inline static
Referenced by try_replace_with_dot().
is_vec_one()
static bool is_vec_one (ir_constant * ir) inline static
Referenced by try_replace_with_dot().
is_vec_two()
static bool is_vec_two (ir_constant * ir) inline static
Referenced by try_replace_with_dot().
is_vec_zero()
static bool is_vec_zero (ir_constant * ir) inline static
Referenced by try_replace_with_dot().
try_replace_with_dot()
static ir_expression* try_replace_with_dot (ir_expression * expr0, ir_expression * expr1, void * mem_ctx) static
References ir_builder::abs(), ir_builder::add(), ir_builder::assign(), ir_builder::b2f(), ir_builder::dot(), ir_builder::expr(), handle_expression(), HANDLE_PACK_UNPACK_INVERSE, ir_unop_log, ir_unop_log2, is_greater_than_zero(), is_less_than_one(), is_vec_four(), is_vec_negative_one(), is_vec_one(), is_vec_two(), is_vec_zero(), ir_builder::logic_and(), ir_builder::logic_not(), ir_builder::logic_or(), ir_builder::lrp(), ir_builder::mul(), ir_builder::neg(), options, ir_builder::rsq(), ir_builder::saturate(), ir_builder::sqrt(), ir_builder::trunc(), and update_type().
update_type()
static void update_type (ir_expression * ir) static
Referenced by try_replace_with_dot().