Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_constant_folding.cpp File Reference
Replace constant-valued expressions with references to constant values.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_rvalue_visitor.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
Functions
bool ir_constant_fold (ir_rvalue **rvalue)
bool do_constant_folding (exec_list *instructions)
Detailed Description
Replace constant-valued expressions with references to constant values.
Function Documentation
do_constant_folding()
bool do_constant_folding (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
ir_constant_fold()
bool ir_constant_fold (ir_rvalue ** rvalue)
References ir_builder::expr(), foreach_two_lists, ir_rvalue_base_visitor::handle_rvalue(), and visit_continue_with_parent.