Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_vectorize.cpp File Reference
Combines scalar assignments of the same expression (modulo swizzle) to multiple channels of the same variable into a single vectorized expression and assignment.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
#include "program/prog_instruction.h"
Functions
static void rewrite_swizzle (ir_instruction *ir, void *data)
Rewrites the swizzles and types of a right-hand side of an assignment.
static bool single_channel_write_mask (unsigned write_mask)
Returns whether the write mask is a single channel.
static unsigned write_mask_to_swizzle (unsigned write_mask)
Translates single-channeled write mask to single-channeled swizzle.
static bool write_mask_matches_swizzle (unsigned write_mask, const ir_swizzle *swz)
Returns whether a single-channeled write mask matches a swizzle.
bool do_vectorize (exec_list *instructions)
Combines scalar assignments of the same expression (modulo swizzle) to multiple channels of the same variable into a single vectorized expression and assignment.
Detailed Description
Combines scalar assignments of the same expression (modulo swizzle) to multiple channels of the same variable into a single vectorized expression and assignment.
Many generated shaders contain scalarized code. That is, they contain
r1.x = log2(v0.x); r1.y = log2(v0.y); r1.z = log2(v0.z);
rather than
r1.xyz = log2(v0.xyz);
We look for consecutive assignments of the same expression (modulo swizzle) to each channel of the same variable.
For instance, we want to convert these three scalar operations
(assign (x) (var_ref r1) (expression float log2 (swiz x (var_ref v0)))) (assign (y) (var_ref r1) (expression float log2 (swiz y (var_ref v0)))) (assign (z) (var_ref r1) (expression float log2 (swiz z (var_ref v0))))
into a single vector operation
(assign (xyz) (var_ref r1) (expression vec3 log2 (swiz xyz (var_ref v0))))
Function Documentation
do_vectorize()
bool do_vectorize (exec_list * instructions)
Combines scalar assignments of the same expression (modulo swizzle) to multiple channels of the same variable into a single vectorized expression and assignment.
Referenced by do_common_optimization().
rewrite_swizzle()
static void rewrite_swizzle (ir_instruction * ir, void * data) static
Rewrites the swizzles and types of a right-hand side of an assignment.
From the example above, this function would be called (by visit_tree()) on the nodes of the tree (expression float log2 (swiz z (var_ref v0))), rewriting it into (expression vec3 log2 (swiz xyz (var_ref v0))).
The function operates on ir_expressions (and its operands) and ir_swizzles. For expressions it sets a new type and swizzles any non-expression and non- swizzle scalar operands into appropriately sized vector arguments. For example, if combining
(assign (x) (var_ref r1) (expression float + (swiz x (var_ref v0) (var_ref v1)))) (assign (y) (var_ref r1) (expression float + (swiz y (var_ref v0) (var_ref v1))))
where v1 is a scalar, rewrite_swizzle() would insert a swizzle on (var_ref v1) such that the final result was
(assign (xy) (var_ref r1) (expression vec2 + (swiz xy (var_ref v0)) (swiz xx (var_ref v1))))
For swizzles, it sets a new type, and if the variable being swizzled is a vector it overwrites the swizzle mask with the ir_swizzle_mask passed as the data parameter. If the swizzled variable is scalar, then the swizzle was added by an earlier call to rewrite_swizzle() on an expression, so the mask should not be modified.
References ir_builder::expr(), and visit_tree().
single_channel_write_mask()
static bool single_channel_write_mask (unsigned write_mask) static
Returns whether the write mask is a single channel.
Referenced by write_mask_matches_swizzle().
write_mask_matches_swizzle()
static bool write_mask_matches_swizzle (unsigned write_mask, const ir_swizzle * swz) static
Returns whether a single-channeled write mask matches a swizzle.
References single_channel_write_mask(), visit_continue, visit_continue_with_parent, visit_list_elements(), write_mask_to_swizzle(), ir_builder::WRITEMASK_W, ir_builder::WRITEMASK_X, ir_builder::WRITEMASK_Y, and ir_builder::WRITEMASK_Z.
write_mask_to_swizzle()
static unsigned write_mask_to_swizzle (unsigned write_mask) static
Translates single-channeled write mask to single-channeled swizzle.
References ir_builder::WRITEMASK_W, ir_builder::WRITEMASK_X, ir_builder::WRITEMASK_Y, and ir_builder::WRITEMASK_Z.
Referenced by write_mask_matches_swizzle().