Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_copy_propagation_elements.cpp File Reference
Replaces usage of recently-copied components of variables with the previous copy of the variable.
#include "ir.h"
#include "ir_rvalue_visitor.h"
#include "ir_basic_block.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
#include "util/hash_table.h"
Functions
bool do_copy_propagation_elements (exec_list *instructions)
Variables
static bool debug = false
Detailed Description
Replaces usage of recently-copied components of variables with the previous copy of the variable.
This pass can be compared with opt_copy_propagation, which operands on arbitrary whole-variable copies. However, in order to handle the copy propagation of swizzled variables or writemasked writes, we want to track things on a channel-wise basis. I found that trying to mix the swizzled/writemasked support here with the whole-variable stuff in opt_copy_propagation.cpp just made a mess, so this is separate despite the ACP handling being somewhat similar.
This should reduce the number of MOV instructions in the generated programs unless copy propagation is also done on the LIR, and may help anyway by triggering other optimizations that live in the HIR.
Function Documentation
do_copy_propagation_elements()
bool do_copy_propagation_elements (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
Variable Documentation
debug
bool debug = false static