Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_rebalance_tree.cpp File Reference
Rebalances a reduction expression tree.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_rvalue_visitor.h"
#include "ir_optimization.h"
#include "main/macros.h"
Functions
static unsigned tree_to_vine (ir_expression *root)
static void compression (ir_expression *root, unsigned count)
static void vine_to_tree (ir_expression *root, unsigned size)
static bool is_reduction_operation (ir_expression_operation operation)
static void is_reduction (ir_instruction *ir, void *data)
static ir_rvalue * handle_expression (ir_expression *expr)
static void update_types (ir_instruction *ir, void *)
bool do_rebalance_tree (exec_list *instructions)
Detailed Description
Rebalances a reduction expression tree.
For reduction operations (e.g., x + y + z + w) we generate an expression tree like
   +
  / \
 +   w
/ \
z / \ x y
which we can rebalance into
  +
 / \
/   \
+ / \ / \ x y z w
to get a better instruction scheduling.
See "Tree Rebalancing in Optimal Editor Time and Space" by Quentin F. Stout and Bette L. Warren.
Also see http://penguin.ewu.edu/~trolfe/DSWpaper/ for a very readable explanation of the of the tree_to_vine() (rightward rotation) and vine_to_tree() (leftward rotation) algorithms.
Function Documentation
compression()
static void compression (ir_expression * root, unsigned count) static
Referenced by vine_to_tree().
do_rebalance_tree()
bool do_rebalance_tree (exec_list * instructions)
Referenced by do_common_optimization().
handle_expression()
ir_rvalue * ir_algebraic_visitor::handle_expression (ir_expression * expr) static
References ir_builder::expr(), is_reduction(), tree_to_vine(), vine_to_tree(), and visit_tree().
Referenced by try_replace_with_dot(), and update_types().
is_reduction()
static void is_reduction (ir_instruction * ir, void * data) static
References ir_builder::expr(), and is_reduction_operation().
Referenced by handle_expression(), and vine_to_tree().
is_reduction_operation()
static bool is_reduction_operation (ir_expression_operation operation) static
Referenced by is_reduction(), and update_types().
tree_to_vine()
static unsigned tree_to_vine (ir_expression * root) static
Referenced by handle_expression().
update_types()
static void update_types (ir_instruction * ir, void *) static
References ir_builder::expr(), handle_expression(), is_reduction_operation(), and visit_tree().
vine_to_tree()
static void vine_to_tree (ir_expression * root, unsigned size) static
References compression(), ir_rvalue_base_visitor::handle_rvalue(), is_reduction(), visit_continue, visit_continue_with_parent, and ir_rvalue_enter_visitor::visit_enter().
Referenced by handle_expression().