Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_function_inlining.cpp File Reference
Replaces calls to functions with the body of the function.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_function_inlining.h"
#include "ir_expression_flattening.h"
#include "compiler/glsl_types.h"
#include "util/hash_table.h"
Data Structures
class ir_variable_replacement_visitor
Replaces references to the "orig" variable with a clone of "repl.".
Functions
static void do_variable_replacement (exec_list *instructions, ir_variable *orig, ir_dereference *repl)
bool do_function_inlining (exec_list *instructions)
static void replace_return_with_assignment (ir_instruction *ir, void *data)
Detailed Description
Replaces calls to functions with the body of the function.
Function Documentation
do_function_inlining()
bool do_function_inlining (exec_list * instructions)
Referenced by do_common_optimization(), do_optimization(), and standalone_compile_shader().
do_variable_replacement()
static void do_variable_replacement (exec_list * instructions, ir_variable * orig, ir_dereference * repl) static
References visit_list_elements().
Referenced by replace_return_with_assignment().
replace_return_with_assignment()
static void replace_return_with_assignment (ir_instruction * ir, void * data) static
References ir_builder::assign(), can_inline(), do_variable_replacement(), foreach_in_list, foreach_two_lists, ir_builder::ret(), visit_continue, visit_continue_with_parent, visit_stop, and visit_tree().