Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
opt_dead_functions.cpp File Reference
Eliminates unused functions from the linked program.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_expression_flattening.h"
#include "compiler/glsl_types.h"
Functions
bool do_dead_functions (exec_list *instructions)
Detailed Description
Eliminates unused functions from the linked program.
Function Documentation
do_dead_functions()
bool do_dead_functions (exec_list * instructions)
References foreach_in_list_safe, and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().