Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
program.h File Reference
Functions
void _mesa_glsl_compile_shader (struct gl_context *ctx, struct gl_shader *shader, bool dump_ast, bool dump_hir, bool force_recompile)
void link_shaders (struct gl_context *ctx, struct gl_shader_program *prog)
void build_program_resource_list (struct gl_context *ctx, struct gl_shader_program *shProg)
Builds up a list of program resources that point to existing resource data.
void linker_error (struct gl_shader_program *prog, const char *fmt,...) PRINTFLIKE(2
void void linker_warning (struct gl_shader_program *prog, const char *fmt,...) PRINTFLIKE(2
void void long parse_program_resource_name (const GLchar *name, const GLchar **out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
Function Documentation
_mesa_glsl_compile_shader()
void _mesa_glsl_compile_shader (struct gl_context * ctx, struct gl_shader * shader, bool dump_ast, bool dump_hir, bool force_recompile)
References _mesa_ast_to_hir(), _mesa_glsl_initialize_derived_variables(), _mesa_print_ir(), add_builtin_defines(), assign_subroutine_indexes(), do_common_optimization(), do_late_parsing_checks(), foreach_in_list, foreach_list_typed, glcpp_preprocess(), ast_node::link, lower_subroutine(), optimize_dead_builtin_variables(), options, reparent_ir(), set_shader_inout_layout(), ast_node::source, and validate_ir_tree().
Referenced by compile_shader(), compile_shaders(), and link_shaders().
build_program_resource_list()
void build_program_resource_list (struct gl_context * ctx, struct gl_shader_program * shProg)
Builds up a list of program resources that point to existing resource data.
References add_fragdata_arrays(), add_interface_variables(), add_packed_varyings(), add_program_resource(), build_stageref(), calculate_array_size_and_stride(), and should_add_buffer_variable().
link_shaders()
void link_shaders (struct gl_context * ctx, struct gl_shader_program * prog)
References _mesa_delete_linked_shader(), _mesa_glsl_compile_shader(), check_explicit_uniform_locations(), cross_validate_outputs_to_inputs(), cross_validate_uniforms(), detect_recursion_linked(), disable_varying_optimizations_for_sso(), interstage_cross_validate_uniform_blocks(), link_assign_subroutine_types(), link_intrastage_shaders(), link_varyings_and_uniforms(), linker_error(), linker_optimisation_loop(), lower_clip_cull_distance(), lower_const_arrays_to_uniforms(), lower_discard_flow(), lower_named_interface_blocks(), lower_tess_level(), propagate_invariance(), reparent_ir(), resize_tes_inputs(), shader_cache_read_program_metadata(), store_fragdepth_layout(), validate_fragment_shader_executable(), validate_geometry_shader_emissions(), validate_geometry_shader_executable(), validate_interstage_inout_blocks(), validate_interstage_uniform_blocks(), validate_ir_tree(), validate_sampler_array_indexing(), validate_tess_eval_shader_executable(), and validate_vertex_shader_executable().
Referenced by standalone_compile_shader().
linker_error()
void linker_error (struct gl_shader_program * prog, const char * fmt, ...)
linker_warning()
void void linker_warning (struct gl_shader_program * prog, const char * fmt, ...)
parse_program_resource_name()
void void long parse_program_resource_name (const GLchar * name, const GLchar ** out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
If an array index is present, out_base_name_end is set to point to the "[" that precedes the array index, and the array index itself is returned as a long.
If no array index is present (or if the array index is negative or mal-formed), out_base_name_end, is set to point to the null terminator at the end of the input string, and -1 is returned.
Only the final array index is parsed; if the string contains other array indices (or structure field accesses), they are left in the base name.
No attempt is made to check that the base name is properly formed; typically the caller will look up the base name in a hash table, so ill-formed base names simply turn into hash table lookup failures.
Referenced by tfeedback_decl::init().