Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
propagate_invariance.cpp File Reference
Propagate the "invariant" and "precise" qualifiers to variables used to compute invariant or precise values.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_rvalue_visitor.h"
#include "ir_optimization.h"
#include "compiler/glsl_types.h"
Functions
void propagate_invariance (exec_list *instructions)
Detailed Description
Propagate the "invariant" and "precise" qualifiers to variables used to compute invariant or precise values.
The GLSL spec (depending on what version you read) says, among the conditions for getting bit-for-bit the same values on an invariant output:
"All operations in the consuming expressions and any intermediate expressions must be the same, with the same order of operands and same associativity, to give the same order of evaluation."
This effectively means that if a variable is used to compute an invariant value then that variable becomes invariant. The same should apply to the "precise" qualifier.
Function Documentation
propagate_invariance()
void propagate_invariance (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and link_shaders().