Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
s_expression.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <math.h>
#include "s_expression.h"
Functions
static void skip_whitespace (const char *&src, char *&symbol_buffer)
static s_expression * read_atom (void *ctx, const char *&src, char *&symbol_buffer)
static s_expression * __read_expression (void *ctx, const char *&src, char *&symbol_buffer)
bool s_match (s_expression *top, unsigned n, s_pattern *pattern, bool partial)
Function Documentation
__read_expression()
static s_expression* __read_expression (void * ctx, const char *& src, char *& symbol_buffer) static
References ir_builder::expr(), read_atom(), skip_whitespace(), and s_list::subexpressions.
Referenced by s_expression::read_expression().
read_atom()
static s_expression* read_atom (void * ctx, const char *& src, char *& symbol_buffer) static
References ir_builder::expr(), s_symbol::s_symbol(), and skip_whitespace().
Referenced by __read_expression().
s_match()
bool s_match (s_expression * top, unsigned n, s_pattern * pattern, bool partial)
References ir_builder::expr(), foreach_in_list, s_list::subexpressions, and SX_AS_LIST.
skip_whitespace()
static void skip_whitespace (const char *& src, char *& symbol_buffer) static
Referenced by __read_expression(), and read_atom().