Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shader_cache.h File Reference
#include "util/disk_cache.h"
Functions
void shader_cache_write_program_metadata (struct gl_context *ctx, struct gl_shader_program *prog)
bool shader_cache_read_program_metadata (struct gl_context *ctx, struct gl_shader_program *prog)
Function Documentation
shader_cache_read_program_metadata()
bool shader_cache_read_program_metadata (struct gl_context * ctx, struct gl_shader_program * prog)
References blob_read_uint32(), blob_reader_init(), compile_shaders(), create_binding_str(), create_linked_shader_and_program(), blob_reader::current, blob_reader::end, blob_reader::overrun, read_atomic_buffers(), read_buffer_blocks(), read_hash_tables(), read_program_resource_list(), read_subroutines(), read_uniform_remap_tables(), read_uniforms(), and read_xfb().
Referenced by link_shaders().
shader_cache_write_program_metadata()
void shader_cache_write_program_metadata (struct gl_context * ctx, struct gl_shader_program * prog)
References blob_create(), blob_destroy(), blob_write_bytes(), blob_write_string(), blob_write_uint32(), blob::data, blob::size, write_atomic_buffers(), write_buffer_blocks(), write_hash_tables(), write_program_resource_list(), write_shader_metadata(), write_subroutines(), write_uniform_remap_tables(), write_uniforms(), and write_xfb().