Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
shader_cache.cpp File Reference
GLSL shader cache implementation.
#include "blob.h"
#include "compiler/shader_info.h"
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "ir.h"
#include "ir_optimization.h"
#include "ir_rvalue_visitor.h"
#include "ir_uniform.h"
#include "linker.h"
#include "link_varyings.h"
#include "main/core.h"
#include "nir.h"
#include "program.h"
#include "shader_cache.h"
#include "util/mesa-sha1.h"
#include "util/string_to_uint_map.h"
#include "main/enums.h"
#include "main/shaderobj.h"
#include "program/program.h"
Data Structures
struct whte_closure
Enumerations
enum uniform_remap_type { remap_type_inactive_explicit_location, remap_type_null_ptr, remap_type_uniform_offset }
Functions
static void compile_shaders (struct gl_context *ctx, struct gl_shader_program *prog)
static void encode_type_to_blob (struct blob *blob, const glsl_type *type)
static const glsl_type * decode_type_from_blob (struct blob_reader *blob)
static void write_subroutines (struct blob *metadata, struct gl_shader_program *prog)
static void read_subroutines (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_buffer_block (struct blob *metadata, struct gl_uniform_block *b)
static void write_buffer_blocks (struct blob *metadata, struct gl_shader_program *prog)
static void read_buffer_block (struct blob_reader *metadata, struct gl_uniform_block *b, struct gl_shader_program *prog)
static void read_buffer_blocks (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_atomic_buffers (struct blob *metadata, struct gl_shader_program *prog)
static void read_atomic_buffers (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_xfb (struct blob *metadata, struct gl_shader_program *shProg)
static void read_xfb (struct blob_reader *metadata, struct gl_shader_program *shProg)
static void write_uniforms (struct blob *metadata, struct gl_shader_program *prog)
static void read_uniforms (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_uniform_remap_table_entry (struct blob *metadata, gl_uniform_storage *uniform_storage, gl_uniform_storage *entry)
static void write_uniform_remap_tables (struct blob *metadata, struct gl_shader_program *prog)
static void read_uniform_remap_table_entry (struct blob_reader *metadata, gl_uniform_storage *uniform_storage, gl_uniform_storage **entry, enum uniform_remap_type type)
static void read_uniform_remap_tables (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_hash_table_entry (const char *key, unsigned value, void *closure)
static void write_hash_table (struct blob *metadata, struct string_to_uint_map *hash)
static void read_hash_table (struct blob_reader *metadata, struct string_to_uint_map *hash)
static void write_hash_tables (struct blob *metadata, struct gl_shader_program *prog)
static void read_hash_tables (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_shader_subroutine_index (struct blob *metadata, struct gl_linked_shader *sh, struct gl_program_resource *res)
static void write_program_resource_data (struct blob *metadata, struct gl_shader_program *prog, struct gl_program_resource *res)
static void read_program_resource_data (struct blob_reader *metadata, struct gl_shader_program *prog, struct gl_program_resource *res)
static void write_program_resource_list (struct blob *metadata, struct gl_shader_program *prog)
static void read_program_resource_list (struct blob_reader *metadata, struct gl_shader_program *prog)
static void write_shader_parameters (struct blob *metadata, struct gl_program_parameter_list *params)
static void read_shader_parameters (struct blob_reader *metadata, struct gl_program_parameter_list *params)
static void write_shader_metadata (struct blob *metadata, gl_linked_shader *shader)
static void read_shader_metadata (struct blob_reader *metadata, struct gl_program *glprog, gl_linked_shader *linked)
static void create_binding_str (const char *key, unsigned value, void *closure)
static void create_linked_shader_and_program (struct gl_context *ctx, gl_shader_stage stage, struct gl_shader_program *prog, struct blob_reader *metadata)
void shader_cache_write_program_metadata (struct gl_context *ctx, struct gl_shader_program *prog)
bool shader_cache_read_program_metadata (struct gl_context *ctx, struct gl_shader_program *prog)
Detailed Description
GLSL shader cache implementation.
This uses disk_cache.c to write out a serialization of various state that's required in order to successfully load and use a binary written out by a drivers backend, this state is referred to as "metadata" throughout the implementation.
The hash key for glsl metadata is a hash of the hashes of each GLSL source string as well as some API settings that change the final program such as SSO, attribute bindings, frag data bindings, etc.
In order to avoid caching any actual IR we use the put_key/get_key support in the disk_cache to put the SHA-1 hash for each successfully compiled shader into the cache, and optimisticly return early from glCompileShader (if the identical shader had been successfully compiled in the past), in the hope that the final linked shader will be found in the cache. If anything goes wrong (shader variant not found, backend cache item is corrupt, etc) we will use a fallback path to compile and link the IR.
Enumeration Type Documentation
uniform_remap_type
enum uniform_remap_type
Enumerator
remap_type_inactive_explicit_location
remap_type_null_ptr
remap_type_uniform_offset
Function Documentation
compile_shaders()
static void compile_shaders (struct gl_context * ctx, struct gl_shader_program * prog) static
References _mesa_glsl_compile_shader().
Referenced by shader_cache_read_program_metadata().
create_binding_str()
static void create_binding_str (const char * key, unsigned value, void * closure) static
Referenced by shader_cache_read_program_metadata().
create_linked_shader_and_program()
static void create_linked_shader_and_program (struct gl_context * ctx, gl_shader_stage stage, struct gl_shader_program * prog, struct blob_reader * metadata) static
References _mesa_reference_shader_program_data(), blob_copy_bytes(), blob_read_string(), and read_shader_metadata().
Referenced by shader_cache_read_program_metadata().
decode_type_from_blob()
static const glsl_type* decode_type_from_blob (struct blob_reader * blob) static
References blob_read_bytes(), blob_read_string(), and blob_read_uint32().
Referenced by read_buffer_block(), read_program_resource_data(), read_subroutines(), and read_uniforms().
encode_type_to_blob()
static void encode_type_to_blob (struct blob * blob, const glsl_type * type) static
References blob_write_bytes(), blob_write_string(), and blob_write_uint32().
Referenced by write_buffer_block(), write_program_resource_data(), write_subroutines(), and write_uniforms().
read_atomic_buffers()
static void read_atomic_buffers (struct blob_reader * metadata, struct gl_shader_program * prog) static
References blob_copy_bytes(), blob_read_uint32(), and blob_reader::data.
Referenced by shader_cache_read_program_metadata().
read_buffer_block()
static void read_buffer_block (struct blob_reader * metadata, struct gl_uniform_block * b, struct gl_shader_program * prog) static
References blob_read_string(), blob_read_uint32(), and decode_type_from_blob().
Referenced by read_buffer_blocks().
read_buffer_blocks()
static void read_buffer_blocks (struct blob_reader * metadata, struct gl_shader_program * prog) static
References blob_read_uint32(), blob_reader::data, and read_buffer_block().
Referenced by shader_cache_read_program_metadata().
read_hash_table()
static void read_hash_table (struct blob_reader * metadata, struct string_to_uint_map * hash) static
References blob_read_string(), blob_read_uint32(), and whte_closure::num_entries.
Referenced by read_hash_tables().
read_hash_tables()
static void read_hash_tables (struct blob_reader * metadata, struct gl_shader_program * prog) static
References read_hash_table().
Referenced by shader_cache_read_program_metadata().
read_program_resource_data()
static void read_program_resource_data (struct blob_reader * metadata, struct gl_shader_program * prog, struct gl_program_resource * res) static
References blob_copy_bytes(), blob_read_string(), blob_read_uint32(), and decode_type_from_blob().
Referenced by read_program_resource_list().
read_program_resource_list()
static void read_program_resource_list (struct blob_reader * metadata, struct gl_shader_program * prog) static
References blob_copy_bytes(), blob_read_uint32(), blob_reader::data, and read_program_resource_data().
Referenced by shader_cache_read_program_metadata().
read_shader_metadata()
static void read_shader_metadata (struct blob_reader * metadata, struct gl_program * glprog, gl_linked_shader * linked) static
References blob_copy_bytes(), blob_read_uint32(), blob_read_uint64(), and read_shader_parameters().
Referenced by create_linked_shader_and_program().
read_shader_parameters()
static void read_shader_parameters (struct blob_reader * metadata, struct gl_program_parameter_list * params) static
References blob_copy_bytes(), blob_read_string(), and blob_read_uint32().
Referenced by read_shader_metadata().
read_subroutines()
static void read_subroutines (struct blob_reader * metadata, struct gl_shader_program * prog) static
References blob_read_string(), blob_read_uint32(), and decode_type_from_blob().
Referenced by shader_cache_read_program_metadata().
read_uniform_remap_table_entry()
static void read_uniform_remap_table_entry (struct blob_reader * metadata, gl_uniform_storage * uniform_storage, gl_uniform_storage ** entry, enum uniform_remap_type type) static
References blob_read_uint32(), INACTIVE_UNIFORM_EXPLICIT_LOCATION, remap_type_inactive_explicit_location, and remap_type_null_ptr.
Referenced by read_uniform_remap_tables().
read_uniform_remap_tables()
static void read_uniform_remap_tables (struct blob_reader * metadata, struct gl_shader_program * prog) static
References blob_read_uint32(), blob_reader::data, and read_uniform_remap_table_entry().
Referenced by shader_cache_read_program_metadata().
read_uniforms()
static void read_uniforms (struct blob_reader * metadata, struct gl_shader_program * prog) static
References gl_uniform_storage::array_elements, gl_uniform_storage::array_stride, gl_uniform_storage::atomic_buffer_index, blob_copy_bytes(), blob_read_bytes(), blob_read_string(), blob_read_uint32(), gl_uniform_storage::block_index, gl_uniform_storage::builtin, blob_reader::data, decode_type_from_blob(), gl_uniform_storage::hidden, gl_uniform_storage::is_shader_storage, gl_uniform_storage::matrix_stride, gl_uniform_storage::name, gl_uniform_storage::num_compatible_subroutines, gl_uniform_storage::offset, gl_uniform_storage::remap_location, gl_uniform_storage::row_major, gl_uniform_storage::storage, gl_uniform_storage::top_level_array_size, gl_uniform_storage::top_level_array_stride, gl_uniform_storage::type, and values_for_type().
Referenced by shader_cache_read_program_metadata().
read_xfb()
static void read_xfb (struct blob_reader * metadata, struct gl_shader_program * shProg) static
References blob_copy_bytes(), blob_read_string(), and blob_read_uint32().
Referenced by shader_cache_read_program_metadata().
shader_cache_read_program_metadata()
bool shader_cache_read_program_metadata (struct gl_context * ctx, struct gl_shader_program * prog)
References blob_read_uint32(), blob_reader_init(), compile_shaders(), create_binding_str(), create_linked_shader_and_program(), blob_reader::current, blob_reader::end, blob_reader::overrun, read_atomic_buffers(), read_buffer_blocks(), read_hash_tables(), read_program_resource_list(), read_subroutines(), read_uniform_remap_tables(), read_uniforms(), and read_xfb().
Referenced by link_shaders().
shader_cache_write_program_metadata()
void shader_cache_write_program_metadata (struct gl_context * ctx, struct gl_shader_program * prog)
References blob_create(), blob_destroy(), blob_write_bytes(), blob_write_string(), blob_write_uint32(), blob::data, blob::size, write_atomic_buffers(), write_buffer_blocks(), write_hash_tables(), write_program_resource_list(), write_shader_metadata(), write_subroutines(), write_uniform_remap_tables(), write_uniforms(), and write_xfb().
write_atomic_buffers()
static void write_atomic_buffers (struct blob * metadata, struct gl_shader_program * prog) static
References blob_write_bytes(), blob_write_uint32(), and blob::data.
Referenced by shader_cache_write_program_metadata().
write_buffer_block()
static void write_buffer_block (struct blob * metadata, struct gl_uniform_block * b) static
References blob_write_string(), blob_write_uint32(), and encode_type_to_blob().
Referenced by write_buffer_blocks().
write_buffer_blocks()
static void write_buffer_blocks (struct blob * metadata, struct gl_shader_program * prog) static
References blob_write_uint32(), blob::data, and write_buffer_block().
Referenced by shader_cache_write_program_metadata().
write_hash_table()
static void write_hash_table (struct blob * metadata, struct string_to_uint_map * hash) static
References whte_closure::blob, blob_overwrite_uint32(), blob_write_uint32(), whte_closure::num_entries, blob::size, and write_hash_table_entry().
Referenced by write_hash_tables().
write_hash_table_entry()
static void write_hash_table_entry (const char * key, unsigned value, void * closure) static
References whte_closure::blob, blob_write_string(), blob_write_uint32(), and whte_closure::num_entries.
Referenced by write_hash_table().
write_hash_tables()
static void write_hash_tables (struct blob * metadata, struct gl_shader_program * prog) static
References write_hash_table().
Referenced by shader_cache_write_program_metadata().
write_program_resource_data()
static void write_program_resource_data (struct blob * metadata, struct gl_shader_program * prog, struct gl_program_resource * res) static
References blob_write_bytes(), blob_write_string(), blob_write_uint32(), encode_type_to_blob(), and write_shader_subroutine_index().
Referenced by write_program_resource_list().
write_program_resource_list()
static void write_program_resource_list (struct blob * metadata, struct gl_shader_program * prog) static
References blob_write_bytes(), blob_write_uint32(), blob::data, and write_program_resource_data().
Referenced by shader_cache_write_program_metadata().
write_shader_metadata()
static void write_shader_metadata (struct blob * metadata, gl_linked_shader * shader) static
References blob_write_bytes(), blob_write_uint32(), blob_write_uint64(), and write_shader_parameters().
Referenced by shader_cache_write_program_metadata().
write_shader_parameters()
static void write_shader_parameters (struct blob * metadata, struct gl_program_parameter_list * params) static
References blob_write_bytes(), blob_write_string(), and blob_write_uint32().
Referenced by write_shader_metadata().
write_shader_subroutine_index()
static void write_shader_subroutine_index (struct blob * metadata, struct gl_linked_shader * sh, struct gl_program_resource * res) static
References blob_write_uint32().
Referenced by write_program_resource_data().
write_subroutines()
static void write_subroutines (struct blob * metadata, struct gl_shader_program * prog) static
References blob_write_string(), blob_write_uint32(), and encode_type_to_blob().
Referenced by shader_cache_write_program_metadata().
write_uniform_remap_table_entry()
static void write_uniform_remap_table_entry (struct blob * metadata, gl_uniform_storage * uniform_storage, gl_uniform_storage * entry) static
References blob_write_uint32(), INACTIVE_UNIFORM_EXPLICIT_LOCATION, remap_type_inactive_explicit_location, remap_type_null_ptr, and remap_type_uniform_offset.
Referenced by write_uniform_remap_tables().
write_uniform_remap_tables()
static void write_uniform_remap_tables (struct blob * metadata, struct gl_shader_program * prog) static
References blob_write_uint32(), blob::data, and write_uniform_remap_table_entry().
Referenced by shader_cache_write_program_metadata().
write_uniforms()
static void write_uniforms (struct blob * metadata, struct gl_shader_program * prog) static
References blob_write_bytes(), blob_write_string(), blob_write_uint32(), blob::data, encode_type_to_blob(), and values_for_type().
Referenced by shader_cache_write_program_metadata().
write_xfb()
static void write_xfb (struct blob * metadata, struct gl_shader_program * shProg) static
References blob_write_bytes(), blob_write_string(), and blob_write_uint32().
Referenced by shader_cache_write_program_metadata().