Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
standalone.cpp File Reference
Standalone compiler helper lib.
#include <getopt.h>
#include "ast.h"
#include "glsl_parser_extras.h"
#include "ir_optimization.h"
#include "program.h"
#include "loop_analysis.h"
#include "standalone_scaffolding.h"
#include "standalone.h"
#include "util/string_to_uint_map.h"
#include "util/set.h"
#include "linker.h"
#include "ir_builder_print_visitor.h"
#include "builtin_functions.h"
#include "opt_add_neg_to_sub.h"
Data Structures
class dead_variable_visitor
Functions
void init_gl_program (struct gl_program *prog, GLenum target, bool is_arb_asm)
struct gl_program * new_program (struct gl_context *ctx, GLenum target, GLuint id, bool is_arb_asm)
static void initialize_context (struct gl_context *ctx, gl_api api)
static char * load_text_file (void *ctx, const char *file_name)
void compile_shader (struct gl_context *ctx, struct gl_shader *shader)
struct gl_shader_program * standalone_compile_shader (const struct standalone_options *_options, unsigned num_files, char *const *files)
void standalone_compiler_cleanup (struct gl_shader_program *whole_program)
Variables
static const struct standalone_options * options
Detailed Description
Standalone compiler helper lib.
Used by standalone glsl_compiler and also available to drivers to implement their own standalone compiler with driver backend.
Function Documentation
compile_shader()
void compile_shader (struct gl_context * ctx, struct gl_shader * shader)
References _mesa_glsl_compile_shader(), _mesa_print_ir(), standalone_options::dump_ast, standalone_options::dump_hir, and standalone_options::dump_lir.
Referenced by standalone_compile_shader().
init_gl_program()
void init_gl_program (struct gl_program * prog, GLenum target, bool is_arb_asm)
Referenced by new_program().
initialize_context()
static void initialize_context (struct gl_context * ctx, gl_api api) static
References standalone_options::glsl_version, initialize_context_to_defaults(), and new_program().
Referenced by standalone_compile_shader().
load_text_file()
static char* load_text_file (void * ctx, const char * file_name) static
Referenced by standalone_compile_shader().
new_program()
struct gl_program* new_program (struct gl_context * ctx, GLenum target, GLuint id, bool is_arb_asm)
References init_gl_program().
Referenced by initialize_context().
standalone_compile_shader()
struct gl_shader_program* standalone_compile_shader (const struct standalone_options * _options, unsigned num_files, char *const * files)
References _mesa_clear_shader_program_data(), _mesa_print_builder_for_ir(), _mesa_shader_enum_to_shader_stage(), compile_shader(), do_common_optimization(), do_function_inlining(), standalone_options::do_link, standalone_options::dump_builder, standalone_options::glsl_version, initialize_context(), standalone_options::just_log, link_intrastage_shaders(), link_shaders(), load_text_file(), dead_variable_visitor::remove_dead_variables(), and visit_list_elements().
Referenced by main().
standalone_compiler_cleanup()
void standalone_compiler_cleanup (struct gl_shader_program * whole_program)
References _mesa_glsl_release_builtin_functions().
Referenced by main().
Variable Documentation
options
const struct standalone_options* options static