Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
standalone_scaffolding.cpp File Reference
#include "standalone_scaffolding.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "util/ralloc.h"
#include "util/strtod.h"
Functions
void _mesa_warning (struct gl_context *ctx, const char *fmt,...)
void _mesa_reference_shader_program_data (struct gl_context *ctx, struct gl_shader_program_data **ptr, struct gl_shader_program_data *data)
void _mesa_reference_shader (struct gl_context *ctx, struct gl_shader **ptr, struct gl_shader *sh)
void _mesa_reference_program_ (struct gl_context *ctx, struct gl_program **ptr, struct gl_program *prog)
void _mesa_shader_debug (struct gl_context *, GLenum, GLuint *, const char *)
struct gl_shader * _mesa_new_shader (GLuint name, gl_shader_stage stage)
GLbitfield _mesa_program_state_flags (const gl_state_index state[STATE_LENGTH])
char * _mesa_program_state_string (const gl_state_index state[STATE_LENGTH])
void _mesa_delete_shader (struct gl_context *ctx, struct gl_shader *sh)
void _mesa_delete_linked_shader (struct gl_context *ctx, struct gl_linked_shader *sh)
void _mesa_clear_shader_program_data (struct gl_context *ctx, struct gl_shader_program *shProg)
void initialize_context_to_defaults (struct gl_context *ctx, gl_api api)
Initialize the given gl_context structure to a reasonable set of defaults representing the minimum capabilities required by the OpenGL spec.
Function Documentation
_mesa_clear_shader_program_data()
void _mesa_clear_shader_program_data (struct gl_context * ctx, struct gl_shader_program * shProg)
References _mesa_delete_linked_shader().
Referenced by standalone_compile_shader().
_mesa_delete_linked_shader()
void _mesa_delete_linked_shader (struct gl_context * ctx, struct gl_linked_shader * sh)
Referenced by _mesa_clear_shader_program_data(), link_intrastage_shaders(), and link_shaders().
_mesa_delete_shader()
void _mesa_delete_shader (struct gl_context * ctx, struct gl_shader * sh)
_mesa_new_shader()
struct gl_shader* _mesa_new_shader (GLuint name, gl_shader_stage stage)
_mesa_program_state_flags()
GLbitfield _mesa_program_state_flags (const gl_state_index state[STATE_LENGTH])
_mesa_program_state_string()
char* _mesa_program_state_string (const gl_state_index state[STATE_LENGTH])
_mesa_reference_program_()
void _mesa_reference_program_ (struct gl_context * ctx, struct gl_program ** ptr, struct gl_program * prog)
_mesa_reference_shader()
void _mesa_reference_shader (struct gl_context * ctx, struct gl_shader ** ptr, struct gl_shader * sh)
_mesa_reference_shader_program_data()
void _mesa_reference_shader_program_data (struct gl_context * ctx, struct gl_shader_program_data ** ptr, struct gl_shader_program_data * data)
Referenced by create_linked_shader_and_program(), and link_intrastage_shaders().
_mesa_shader_debug()
void _mesa_shader_debug (struct gl_context * , GLenum , GLuint * , const char *)
Referenced by _mesa_glsl_msg().
_mesa_warning()
void _mesa_warning (struct gl_context * ctx, const char * fmt, ...)
initialize_context_to_defaults()
void initialize_context_to_defaults (struct gl_context * ctx, gl_api api)
Initialize the given gl_context structure to a reasonable set of defaults representing the minimum capabilities required by the OpenGL spec.
This is used when compiling builtin functions and in testing, when we don't have a connection to an actual driver.
Referenced by _mesa_shader_enum_to_shader_stage(), initialize_context(), and test_optpass().