Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
standalone.h File Reference
Data Structures
struct standalone_options
Functions
struct gl_shader_program * standalone_compile_shader (const struct standalone_options *options, unsigned num_files, char *const *files)
void standalone_compiler_cleanup (struct gl_shader_program *prog)
Function Documentation
standalone_compile_shader()
struct gl_shader_program* standalone_compile_shader (const struct standalone_options * options, unsigned num_files, char *const * files)
References _mesa_clear_shader_program_data(), _mesa_print_builder_for_ir(), _mesa_shader_enum_to_shader_stage(), compile_shader(), do_common_optimization(), do_function_inlining(), standalone_options::do_link, standalone_options::dump_builder, standalone_options::glsl_version, initialize_context(), standalone_options::just_log, link_intrastage_shaders(), link_shaders(), load_text_file(), dead_variable_visitor::remove_dead_variables(), and visit_list_elements().
Referenced by main().
standalone_compiler_cleanup()
void standalone_compiler_cleanup (struct gl_shader_program * prog)
References _mesa_glsl_release_builtin_functions().
Referenced by main().