Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glsl_symbol_table Struct Reference
Facade class for _mesa_symbol_table.
#include <glsl_symbol_table.h>
Public Member Functions
DECLARE_RALLOC_CXX_OPERATORS (glsl_symbol_table) glsl_symbol_table()
~glsl_symbol_table ()
void push_scope ()
void pop_scope ()
bool name_declared_this_scope (const char *name)
Determine whether a name was declared at the current scope.
void add_global_function (ir_function *f)
Add an function at global scope without checking for scoping conflicts.
void disable_variable (const char *name)
Disable a previously-added variable so that it no longer appears to be in the symbol table.
void replace_variable (const char *name, ir_variable *v)
Replaces the variable in the entry by the new variable.
Methods to add symbols to the table
There is some temptation to rename all these functions to add_symbol or similar.
However, this breaks symmetry with the getter functions and reduces the clarity of the intention of code that uses these methods.
bool add_variable (ir_variable *v)
bool add_type (const char *name, const glsl_type *t)
bool add_function (ir_function *f)
bool add_interface (const char *name, const glsl_type *i, enum ir_variable_mode mode)
bool add_default_precision_qualifier (const char *type_name, int precision)
Methods to get symbols from the table
ir_variable * get_variable (const char *name)
const glsl_type * get_type (const char *name)
ir_function * get_function (const char *name)
const glsl_type * get_interface (const char *name, enum ir_variable_mode mode)
int get_default_precision_qualifier (const char *type_name)
Data Fields
bool separate_function_namespace
Detailed Description
Facade class for _mesa_symbol_table.
Wraps the existing _mesa_symbol_table data structure to enforce some type safe and some symbol table invariants.
Constructor & Destructor Documentation
~glsl_symbol_table()
glsl_symbol_table::~glsl_symbol_table ()
Member Function Documentation
add_default_precision_qualifier()
bool glsl_symbol_table::add_default_precision_qualifier (const char * type_name, int precision)
References ast_type_specifier::ast_type_specifier(), ast_type_specifier::default_precision, and symbol_table_entry::symbol_table_entry().
add_function()
bool glsl_symbol_table::add_function (ir_function * f)
References symbol_table_entry::f, symbol_table_entry::symbol_table_entry(), and symbol_table_entry::t.
add_global_function()
void glsl_symbol_table::add_global_function (ir_function * f)
Add an function at global scope without checking for scoping conflicts.
References symbol_table_entry::symbol_table_entry().
add_interface()
bool glsl_symbol_table::add_interface (const char * name, const glsl_type * i, enum ir_variable_mode mode)
References symbol_table_entry::symbol_table_entry().
add_type()
bool glsl_symbol_table::add_type (const char * name, const glsl_type * t)
References symbol_table_entry::symbol_table_entry().
Referenced by add_type().
add_variable()
bool glsl_symbol_table::add_variable (ir_variable * v)
References symbol_table_entry::f, symbol_table_entry::symbol_table_entry(), symbol_table_entry::t, and symbol_table_entry::v.
Referenced by cross_validate_globals(), and cross_validate_outputs_to_inputs().
DECLARE_RALLOC_CXX_OPERATORS()
glsl_symbol_table::DECLARE_RALLOC_CXX_OPERATORS (glsl_symbol_table)
disable_variable()
void glsl_symbol_table::disable_variable (const char * name)
Disable a previously-added variable so that it no longer appears to be in the symbol table.
This is necessary when gl_PerVertex is redeclared, to ensure that previously-available built-in variables are no longer available.
References symbol_table_entry::v.
get_default_precision_qualifier()
int glsl_symbol_table::get_default_precision_qualifier (const char * type_name)
References symbol_table_entry::a, ast_precision_none, and ast_type_specifier::default_precision.
get_function()
ir_function * glsl_symbol_table::get_function (const char * name)
References symbol_table_entry::f.
Referenced by _mesa_get_main_function_signature(), and find_matching_signature().
get_interface()
const glsl_type * glsl_symbol_table::get_interface (const char * name, enum ir_variable_mode mode)
References symbol_table_entry::get_interface().
get_type()
const glsl_type * glsl_symbol_table::get_type (const char * name)
References symbol_table_entry::t.
get_variable()
ir_variable * glsl_symbol_table::get_variable (const char * name)
References symbol_table_entry::v.
Referenced by cross_validate_globals(), and cross_validate_outputs_to_inputs().
name_declared_this_scope()
bool glsl_symbol_table::name_declared_this_scope (const char * name)
Determine whether a name was declared at the current scope.
pop_scope()
void glsl_symbol_table::pop_scope ()
push_scope()
void glsl_symbol_table::push_scope ()
replace_variable()
void glsl_symbol_table::replace_variable (const char * name, ir_variable * v)
Replaces the variable in the entry by the new variable.
References symbol_table_entry::v.
Referenced by cross_validate_globals().
Field Documentation
separate_function_namespace
bool glsl_symbol_table::separate_function_namespace
The documentation for this struct was generated from the following files:
glsl_symbol_table.h
glsl_symbol_table.cpp