Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
_mesa_glsl_extension Struct Reference
Element type for _mesa_glsl_supported_extensions.
Public Member Functions
bool compatible_with_state (const _mesa_glsl_parse_state *state, gl_api api, uint8_t gl_version) const
Determine whether a given extension is compatible with the target, API, and extension information in the current parser state.
void set_flags (_mesa_glsl_parse_state *state, ext_behavior behavior) const
Set the appropriate flags in the parser state to establish the given behavior for this extension.
Data Fields
const char * name
Name of the extension when referred to in a GLSL extension statement.
bool aep
Whether this extension is a part of AEP.
bool(* available_pred)(const struct gl_context *, gl_api api, uint8_t version)
Predicate that checks whether the relevant extension is available for this context.
bool _mesa_glsl_parse_state::* enable_flag
Flag in the _mesa_glsl_parse_state struct that should be set when this extension is enabled.
bool _mesa_glsl_parse_state::* warn_flag
Flag in the _mesa_glsl_parse_state struct that should be set when the shader requests "warn" behavior for this extension.
Detailed Description
Element type for _mesa_glsl_supported_extensions.
Member Function Documentation
compatible_with_state()
bool _mesa_glsl_extension::compatible_with_state (const _mesa_glsl_parse_state * state, gl_api api, uint8_t gl_version) const
Determine whether a given extension is compatible with the target, API, and extension information in the current parser state.
References available_pred.
Referenced by _mesa_glsl_process_extension(), and add_builtin_defines().
set_flags()
void _mesa_glsl_extension::set_flags (_mesa_glsl_parse_state * state, ext_behavior behavior) const
Set the appropriate flags in the parser state to establish the given behavior for this extension.
References enable_flag, extension_disable, extension_warn, and warn_flag.
Referenced by _mesa_glsl_process_extension().
Field Documentation
aep
bool _mesa_glsl_extension::aep
Whether this extension is a part of AEP.
Referenced by _mesa_glsl_process_extension().
available_pred
bool(* _mesa_glsl_extension::available_pred) (const struct gl_context *, gl_api api, uint8_t version)
Predicate that checks whether the relevant extension is available for this context.
Referenced by _mesa_glsl_process_extension(), and compatible_with_state().
enable_flag
bool _mesa_glsl_parse_state::* _mesa_glsl_extension::enable_flag
Flag in the _mesa_glsl_parse_state struct that should be set when this extension is enabled.
See note in _mesa_glsl_extension::supported_flag about "pointer to member" types.
Referenced by set_flags().
name
const char* _mesa_glsl_extension::name
Name of the extension when referred to in a GLSL extension statement.
Referenced by add_builtin_defines().
warn_flag
bool _mesa_glsl_parse_state::* _mesa_glsl_extension::warn_flag
Flag in the _mesa_glsl_parse_state struct that should be set when the shader requests "warn" behavior for this extension.
See note in _mesa_glsl_extension::supported_flag about "pointer to member" types.
Referenced by set_flags().
The documentation for this struct was generated from the following file:
glsl_parser_extras.cpp