Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
test_optpass.cpp File Reference
Standalone test for optimization passes.
#include <string>
#include <iostream>
#include <sstream>
#include <getopt.h>
#include "ast.h"
#include "ir_optimization.h"
#include "program.h"
#include "ir_reader.h"
#include "standalone_scaffolding.h"
Functions
static string read_stdin_to_eof ()
static GLboolean do_optimization (struct exec_list *ir, const char *optimization, const struct gl_shader_compiler_options *options)
static GLboolean do_optimization_passes (struct exec_list *ir, char **optimizations, int num_optimizations, bool quiet, const struct gl_shader_compiler_options *options)
int test_optpass (int argc, char **argv)
Detailed Description
Standalone test for optimization passes.
This file provides the "optpass" command for the standalone glsl_test app. It accepts either GLSL or high-level IR as input, and performs the optimiation passes specified on the command line. It outputs the IR, both before and after optimiations.
Function Documentation
do_optimization()
static GLboolean do_optimization (struct exec_list * ir, const char * optimization, const struct gl_shader_compiler_options * options) static
References do_algebraic(), do_common_optimization(), do_constant_folding(), do_constant_propagation(), do_constant_variable(), do_constant_variable_unlinked(), do_copy_propagation(), do_copy_propagation_elements(), do_dead_code(), do_dead_code_local(), do_dead_code_unlinked(), do_dead_functions(), do_function_inlining(), do_if_simplification(), do_lower_jumps(), do_lower_texture_projection(), do_mat_op_to_vec(), do_noop_swizzle(), do_structure_splitting(), do_swizzle_swizzle(), do_tree_grafting(), do_vec_index_to_cond_assign(), do_vec_index_to_swizzle(), lower_discard(), lower_if_to_cond_assign(), lower_instructions(), lower_noise(), lower_quadop_vector(), lower_variable_index_to_cond_assign(), and optimize_redundant_jumps().
Referenced by do_optimization_passes().
do_optimization_passes()
static GLboolean do_optimization_passes (struct exec_list * ir, char ** optimizations, int num_optimizations, bool quiet, const struct gl_shader_compiler_options * options) static
References do_optimization(), and validate_ir_tree().
Referenced by test_optpass().
read_stdin_to_eof()
static string read_stdin_to_eof () static
Referenced by test_optpass().
test_optpass()
int test_optpass (int argc, char ** argv)
References _mesa_ast_to_hir(), _mesa_glsl_initialize_types(), _mesa_glsl_read_ir(), _mesa_print_ir(), _mesa_shader_enum_to_shader_stage(), do_optimization_passes(), glcpp_preprocess(), initialize_context_to_defaults(), options, and read_stdin_to_eof().
Referenced by main().