Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
test.cpp File Reference
Standalone tests for the GLSL compiler.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "test_optpass.h"
Functions
static void usage_fail (const char *name)
Print proper usage and exit with failure.
static const char * extract_command_from_argv (int *argc, char **argv)
int main (int argc, char **argv)
Detailed Description
Standalone tests for the GLSL compiler.
This file provides a standalone executable which can be used to test components of the GLSL.
Each test is a function with the same signature as main(). The main function interprets its first argument as the name of the test to run, strips out that argument, and then calls the test function.
Function Documentation
extract_command_from_argv()
static const char* extract_command_from_argv (int * argc, char ** argv) static
References usage_fail().
Referenced by main().
main()
int main (int argc, char ** argv)
References extract_command_from_argv(), test_optpass(), and usage_fail().
usage_fail()
static void usage_fail (const char * name) static
Print proper usage and exit with failure.
Referenced by extract_command_from_argv(), and main().