Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
test_optpass.h File Reference
Functions
int test_optpass (int argc, char **argv)
Function Documentation
test_optpass()
int test_optpass (int argc, char ** argv)
References _mesa_ast_to_hir(), _mesa_glsl_initialize_types(), _mesa_glsl_read_ir(), _mesa_print_ir(), _mesa_shader_enum_to_shader_stage(), do_optimization_passes(), glcpp_preprocess(), initialize_context_to_defaults(), options, and read_stdin_to_eof().
Referenced by main().