Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
t_dd_dmatmp2.h File Reference
Template for render stages which build and emit vertices directly to fixed-size dma buffers.
Macros
#define EMIT_TWO_ELTS(dest, offset, elt0, elt1)
Functions
static ELT_TYPE *TAG() emit_elts (struct gl_context *ctx, ELT_TYPE *dest, GLuint *elts, GLuint nr)
static ELT_TYPE *TAG() emit_consecutive_elts (struct gl_context *ctx, ELT_TYPE *dest, GLuint start, GLuint nr)
static void TAG() render_points_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_lines_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_line_strip_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_line_loop_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_triangles_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_tri_strip_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_tri_fan_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_poly_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_quad_strip_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_quads_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_noop (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static tnl_render_func TAG (render_tab_verts)[GL_POLYGON+2]
static void TAG() render_points_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_lines_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_line_strip_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_line_loop_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_triangles_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_tri_strip_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_tri_fan_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_poly_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_quad_strip_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_quads_elts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static tnl_render_func TAG (render_tab_elts)[GL_POLYGON+2]
Detailed Description
Template for render stages which build and emit vertices directly to fixed-size dma buffers.
Useful for rendering strips and other native primitives where clipping and per-vertex tweaks such as those in t_dd_tritmp.h are not required.
Macro Definition Documentation
EMIT_TWO_ELTS
#define EMIT_TWO_ELTS (dest, offset, elt0, elt1)
Value:
do {                                            \
   (dest)[offset] = (elt0);                     \
   (dest)[offset+1] = (elt1);                   \
} while (0)
Referenced by emit_consecutive_elts(), emit_elts(), render_line_loop_verts(), render_line_strip_verts(), render_quad_strip_elts(), render_quad_strip_verts(), render_quads_elts(), and render_quads_verts().
Function Documentation
emit_consecutive_elts()
static ELT_TYPE* TAG() emit_consecutive_elts (struct gl_context * ctx, ELT_TYPE * dest, GLuint start, GLuint nr) static
References EMIT_TWO_ELTS, GLuint, and LOCAL_VARS.
Referenced by render_line_loop_verts().
emit_elts()
static ELT_TYPE* TAG() emit_elts (struct gl_context * ctx, ELT_TYPE * dest, GLuint * elts, GLuint nr) static
References EMIT_TWO_ELTS, GLuint, and LOCAL_VARS.
Referenced by render_line_loop_elts(), render_line_strip_elts(), render_lines_elts(), render_points_elts(), render_poly_elts(), render_quad_strip_elts(), render_tri_fan_elts(), render_tri_strip_elts(), and render_triangles_elts().
render_line_loop_elts()
static void TAG() render_line_loop_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, gl_context::Line, LOCAL_VARS, PRIM_BEGIN, PRIM_END, RESET_STIPPLE, gl_line_attrib::StippleFlag, TAG(), and void.
Referenced by render_quads_elts().
render_line_loop_verts()
static void TAG() render_line_loop_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_consecutive_elts(), EMIT_TWO_ELTS, GLuint, gl_context::Line, LOCAL_VARS, PRIM_BEGIN, PRIM_END, render_line_strip_verts(), RESET_STIPPLE, gl_line_attrib::StippleFlag, TAG(), and void.
Referenced by render_noop().
render_line_strip_elts()
static void TAG() render_line_strip_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, gl_context::Line, LOCAL_VARS, PRIM_BEGIN, RESET_STIPPLE, gl_line_attrib::StippleFlag, TAG(), and void.
Referenced by render_quads_elts().
render_line_strip_verts()
static void TAG() render_line_strip_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References EMIT_TWO_ELTS, GLuint, gl_context::Line, LOCAL_VARS, PRIM_BEGIN, RESET_STIPPLE, and gl_line_attrib::StippleFlag.
Referenced by render_line_loop_verts(), and render_noop().
render_lines_elts()
static void TAG() render_lines_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, gl_context::Line, LOCAL_VARS, PRIM_BEGIN, PRIM_END, RESET_STIPPLE, gl_line_attrib::StippleFlag, TAG(), and void.
Referenced by render_quads_elts().
render_lines_verts()
static void TAG() render_lines_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, gl_context::Line, LOCAL_VARS, PRIM_BEGIN, PRIM_END, RESET_STIPPLE, and gl_line_attrib::StippleFlag.
Referenced by render_noop().
render_noop()
static void TAG() render_noop (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, render_line_loop_verts(), render_line_strip_verts(), render_lines_verts(), render_points_verts(), render_poly_verts(), render_quad_strip_verts(), render_quads_verts(), render_tri_fan_verts(), render_tri_strip_verts(), render_triangles_verts(), and TAG().
Referenced by render_quads_elts().
render_points_elts()
static void TAG() render_points_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, LOCAL_VARS, TAG(), and void.
Referenced by render_quads_elts().
render_points_verts()
static void TAG() render_points_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, and LOCAL_VARS.
Referenced by render_noop().
render_poly_elts()
static void TAG() render_poly_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, LOCAL_VARS, TAG(), and void.
Referenced by render_quads_elts().
render_poly_verts()
static void TAG() render_poly_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, and LOCAL_VARS.
Referenced by render_noop().
render_quad_strip_elts()
static void TAG() render_quad_strip_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), EMIT_TWO_ELTS, GLuint, gl_context::Light, LOCAL_VARS, gl_light_attrib::ShadeModel, TAG(), and void.
Referenced by render_quads_elts().
render_quad_strip_verts()
static void TAG() render_quad_strip_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References EMIT_TWO_ELTS, GLuint, gl_context::Light, LOCAL_VARS, and gl_light_attrib::ShadeModel.
Referenced by render_noop().
render_quads_elts()
static void TAG() render_quads_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References EMIT_TWO_ELTS, GLuint, LOCAL_VARS, render_line_loop_elts(), render_line_strip_elts(), render_lines_elts(), render_noop(), render_points_elts(), render_poly_elts(), render_quad_strip_elts(), render_tri_fan_elts(), render_tri_strip_elts(), render_triangles_elts(), and TAG().
render_quads_verts()
static void TAG() render_quads_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References EMIT_TWO_ELTS, GLuint, and LOCAL_VARS.
Referenced by render_noop().
render_tri_fan_elts()
static void TAG() render_tri_fan_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, LOCAL_VARS, TAG(), and void.
Referenced by render_quads_elts().
render_tri_fan_verts()
static void TAG() render_tri_fan_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, and LOCAL_VARS.
Referenced by render_noop().
render_tri_strip_elts()
static void TAG() render_tri_strip_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, LOCAL_VARS, TAG(), and void.
Referenced by render_quads_elts().
render_tri_strip_verts()
static void TAG() render_tri_strip_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, and LOCAL_VARS.
Referenced by render_noop().
render_triangles_elts()
static void TAG() render_triangles_elts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_elts(), GLuint, LOCAL_VARS, TAG(), and void.
Referenced by render_quads_elts().
render_triangles_verts()
static void TAG() render_triangles_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References GLuint, and LOCAL_VARS.
Referenced by render_noop().
TAG() [1/2]
static tnl_render_func TAG (render_tab_verts) static
Referenced by render_line_loop_elts(), render_line_loop_verts(), render_line_strip_elts(), render_lines_elts(), render_noop(), render_points_elts(), render_poly_elts(), render_quad_strip_elts(), render_quads_elts(), render_tri_fan_elts(), render_tri_strip_elts(), and render_triangles_elts().
TAG() [2/2]
static tnl_render_func TAG (render_tab_elts) static