Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glapi_priv.h File Reference
#include "GL/gl.h"
#include "GL/glext.h"
#include "glapi/glapi.h"
Macros
#define GL_GLEXT_PROTOTYPES
#define MAX_EXTENSION_FUNCS 256
Size (in bytes) of dispatch function (entrypoint).
Typedefs
typedef int GLclampx
Functions
void init_glapi_relocs_once (void)
_glapi_proc generate_entrypoint (unsigned int functionOffset)
void fill_in_entrypoint_offset (_glapi_proc entrypoint, unsigned int offset)
_glapi_proc get_entrypoint_address (unsigned int functionOffset)
Macro Definition Documentation
GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES
MAX_EXTENSION_FUNCS
#define MAX_EXTENSION_FUNCS 256
Size (in bytes) of dispatch function (entrypoint).
Number of extension functions which we can dynamically add at runtime.
Number of extension functions is also subject to the size of backing exec mem we allocate. For the common case of dispatch stubs with size 16 bytes, the two limits will be hit simultaneously. For larger dispatch function sizes, MAX_EXTENSION_FUNCS is effectively reduced.
Referenced by _glapi_get_dispatch_table_size(), and add_function_name().
Typedef Documentation
GLclampx
typedef int GLclampx
Function Documentation
fill_in_entrypoint_offset()
void fill_in_entrypoint_offset (_glapi_proc entrypoint, unsigned int offset)
generate_entrypoint()
_glapi_proc generate_entrypoint (unsigned int functionOffset)
get_entrypoint_address()
_glapi_proc get_entrypoint_address (unsigned int functionOffset)
Referenced by get_static_proc_address().
init_glapi_relocs_once()
void init_glapi_relocs_once (void)
References init_glapi_relocs().
Referenced by _glapi_add_dispatch(), and _glapi_get_proc_address().