Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glapi.h File Reference
#include "util/macros.h"
Macros
#define _GLAPI_EXPORT
#define GET_DISPATCH() (likely(_glapi_Dispatch) ? _glapi_Dispatch : _glapi_get_dispatch())
#define GET_CURRENT_CONTEXT(C)
Typedefs
typedef void(* _glapi_proc) (void)
typedef void(* _glapi_nop_handler_proc) (const char *name)
Functions
void _glapi_destroy_multithread (void)
_GLAPI_EXPORT void _glapi_check_multithread (void)
_GLAPI_EXPORT void _glapi_set_context (void *context)
_GLAPI_EXPORT void * _glapi_get_context (void)
_GLAPI_EXPORT void _glapi_set_dispatch (struct _glapi_table *dispatch)
_GLAPI_EXPORT struct _glapi_table * _glapi_get_dispatch (void)
_GLAPI_EXPORT unsigned int _glapi_get_dispatch_table_size (void)
Return size of dispatch table struct as number of functions (or slots).
_GLAPI_EXPORT int _glapi_add_dispatch (const char *const *function_names, const char *parameter_signature)
Fill-in the dispatch stub for the named function.
_GLAPI_EXPORT int _glapi_get_proc_offset (const char *funcName)
Return offset of entrypoint for named function within dispatch table.
_GLAPI_EXPORT _glapi_proc _glapi_get_proc_address (const char *funcName)
Return pointer to the named function.
_GLAPI_EXPORT const char * _glapi_get_proc_name (unsigned int offset)
_GLAPI_EXPORT void _glapi_set_nop_handler (_glapi_nop_handler_proc func)
Register the no-op handler call-back function.
_GLAPI_EXPORT struct _glapi_table * _glapi_new_nop_table (unsigned num_entries)
Return pointer to new dispatch table filled with no-op functions.
_GLAPI_EXPORT unsigned long _glthread_GetID (void)
Deprecated function.
_GLAPI_EXPORT void _glapi_noop_enable_warnings (unsigned char enable)
No-op dispatch table.
_GLAPI_EXPORT void _glapi_set_warning_func (_glapi_proc func)
Variables
_GLAPI_EXPORT struct _glapi_table * _glapi_Dispatch
_GLAPI_EXPORT void * _glapi_Context
Macro Definition Documentation
_GLAPI_EXPORT
#define _GLAPI_EXPORT
GET_CURRENT_CONTEXT
#define GET_CURRENT_CONTEXT (C)
Value:
struct gl_context *C = (struct gl_context *) \
     (likely(_glapi_Context) ? _glapi_Context : _glapi_get_context())
GET_DISPATCH
#define GET_DISPATCH () (likely(_glapi_Dispatch) ? _glapi_Dispatch : _glapi_get_dispatch())
Typedef Documentation
_glapi_nop_handler_proc
typedef void(* _glapi_nop_handler_proc) (const char *name)
_glapi_proc
typedef void(* _glapi_proc) (void)
Function Documentation
_glapi_add_dispatch()
_GLAPI_EXPORT int _glapi_add_dispatch (const char *const * function_names, const char * parameter_signature)
Fill-in the dispatch stub for the named function.
This function is intended to be called by a hardware driver. When called, a dispatch stub may be created for the function. A pointer to this dispatch function will be returned by glXGetProcAddress.
Parameters
function_names Array of pointers to function names that should share a common dispatch offset.
parameter_signature String representing the types of the parameters passed to the named function. Parameter types are converted to characters using the following rules:
'i' for GLint, GLuint, and GLenum
'p' for any pointer type
'f' for GLfloat and GLclampf
'd' for GLdouble and GLclampd
Returns
The offset in the dispatch table of the named function. A pointer to the driver's implementation of the named function should be stored at dispatch_table[offset]. Return -1 if error/problem.
See also
glXGetProcAddress
Warning
This function can only handle up to 8 names at a time. As far as I know, the maximum number of names ever associated with an existing GL function is 4 (glPointParameterfSGIS, glPointParameterfEXT, glPointParameterfARB, and glPointParameterf), so this should not be too painful of a limitation.
Todo:
Determine whether or not parameter_signature should be allowed to be NULL. It doesn't seem like much of a hardship for drivers to have to pass in an empty string.
Todo:
Determine if code should be added to reject function names that start with 'glX'.
Bug:
Add code to compare parameter_signature with the parameter signature of a static function. In order to do that, we need to find a way to get the parameter signature of a static function.
References add_function_name(), _glapi_function::dispatch_offset, FIRST_DYNAMIC_OFFSET, get_extension_proc(), get_static_proc_offset(), init_glapi_relocs_once(), set_entry_info(), and void.
_glapi_check_multithread()
_GLAPI_EXPORT void _glapi_check_multithread (void)
_glapi_destroy_multithread()
void _glapi_destroy_multithread (void)
_glapi_get_context()
_GLAPI_EXPORT void* _glapi_get_context (void)
_glapi_get_dispatch()
_GLAPI_EXPORT struct _glapi_table* _glapi_get_dispatch (void)
_glapi_get_dispatch_table_size()
_GLAPI_EXPORT unsigned int _glapi_get_dispatch_table_size (void)
Return size of dispatch table struct as number of functions (or slots).
References FIRST_DYNAMIC_OFFSET, and MAX_EXTENSION_FUNCS.
_glapi_get_proc_address()
_GLAPI_EXPORT _glapi_proc _glapi_get_proc_address (const char * funcName)
Return pointer to the named function.
If the function name isn't found in the name of static functions, try generating a new API entrypoint on the fly with assembly language.
References add_function_name(), _glapi_function::dispatch_stub, get_extension_proc_address(), get_static_proc_address(), and init_glapi_relocs_once().
_glapi_get_proc_name()
_GLAPI_EXPORT const char* _glapi_get_proc_name (unsigned int offset)
_glapi_get_proc_offset()
_GLAPI_EXPORT int _glapi_get_proc_offset (const char * funcName)
Return offset of entrypoint for named function within dispatch table.
References get_extension_proc_offset(), and get_static_proc_offset().
_glapi_new_nop_table()
_GLAPI_EXPORT struct _glapi_table* _glapi_new_nop_table (unsigned num_entries)
Return pointer to new dispatch table filled with no-op functions.
_glapi_noop_enable_warnings()
_GLAPI_EXPORT void _glapi_noop_enable_warnings (unsigned char enable)
No-op dispatch table.
This file defines a special dispatch table which is loaded with no-op functions.
Mesa can register a "no-op handler function" which will be called in the event that a no-op function is called.
In the past, the dispatch table was loaded with pointers to a single no-op function. But that broke on Windows because the GL entrypoints use __stdcall convention. __stdcall means the callee cleans up the stack. So one no-op function can't properly clean up the stack. This would lead to crashes.
Another benefit of unique no-op functions is we can accurately report the function's name in an error message.
_glapi_set_context()
_GLAPI_EXPORT void _glapi_set_context (void * context)
_glapi_set_dispatch()
_GLAPI_EXPORT void _glapi_set_dispatch (struct _glapi_table * dispatch)
_glapi_set_nop_handler()
_GLAPI_EXPORT void _glapi_set_nop_handler (_glapi_nop_handler_proc func)
Register the no-op handler call-back function.
References nop_handler.
_glapi_set_warning_func()
_GLAPI_EXPORT void _glapi_set_warning_func (_glapi_proc func)
_glthread_GetID()
_GLAPI_EXPORT unsigned long _glthread_GetID (void)
Deprecated function.
Variable Documentation
_glapi_Context
_GLAPI_EXPORT void* _glapi_Context
_glapi_Dispatch
_GLAPI_EXPORT struct _glapi_table* _glapi_Dispatch