Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glapi_entrypoint.c File Reference
Arch-specific code for manipulating GL API entrypoints (dispatch stubs).
#include <string.h>
#include "c11/threads.h"
#include "glapi/glapi_priv.h"
#include "u_execmem.h"
Functions
static void init_glapi_relocs (void)
_glapi_proc generate_entrypoint (GLuint functionOffset)
void fill_in_entrypoint_offset (_glapi_proc entrypoint, GLuint offset)
void init_glapi_relocs_once (void)
Detailed Description
Arch-specific code for manipulating GL API entrypoints (dispatch stubs).
Function Documentation
fill_in_entrypoint_offset()
void fill_in_entrypoint_offset (_glapi_proc entrypoint, GLuint offset)
References void.
Referenced by set_entry_info().
generate_entrypoint()
_glapi_proc generate_entrypoint (GLuint functionOffset)
References void.
Referenced by add_function_name().
init_glapi_relocs()
static void init_glapi_relocs (void) static
Referenced by init_glapi_relocs_once().
init_glapi_relocs_once()
void init_glapi_relocs_once (void)
References init_glapi_relocs().
Referenced by _glapi_add_dispatch(), and _glapi_get_proc_address().