Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
glapi_getproc.c File Reference
Code for implementing glXGetProcAddress(), etc.
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include "glapi/glapi_priv.h"
#include "glapi/glapitable.h"
#include "glapi/glprocs.h"
Data Structures
struct _glapi_function
Track information about a function added to the GL API.
Macros
#define FIRST_DYNAMIC_OFFSET (sizeof(struct _glapi_table) / sizeof(void *))
#define NEED_FUNCTION_POINTER
Functions
static const glprocs_table_t * get_static_proc (const char *n)
Search the table of static entrypoint functions for the named function and return the corresponding glprocs_table_t entry.
static GLint get_static_proc_offset (const char *funcName)
Return dispatch table offset of the named static (built-in) function.
static _glapi_proc get_static_proc_address (const char *funcName)
Return dispatch function address for the named static (built-in) function.
static const char * get_static_proc_name (GLuint offset)
Return the name of the function at the given offset in the dispatch table.
static struct _glapi_function * get_extension_proc (const char *funcName)
static GLint get_extension_proc_offset (const char *funcName)
static _glapi_proc get_extension_proc_address (const char *funcName)
static const char * get_extension_proc_name (GLuint offset)
static char * str_dup (const char *str)
strdup() is actually not a standard ANSI C or POSIX routine.
static struct _glapi_function * add_function_name (const char *funcName)
Generate new entrypoint.
static struct _glapi_function * set_entry_info (struct _glapi_function *entry, const char *signature, unsigned offset)
int _glapi_add_dispatch (const char *const *function_names, const char *parameter_signature)
Fill-in the dispatch stub for the named function.
GLint _glapi_get_proc_offset (const char *funcName)
Return offset of entrypoint for named function within dispatch table.
_glapi_proc _glapi_get_proc_address (const char *funcName)
Return pointer to the named function.
const char * _glapi_get_proc_name (GLuint offset)
Return the name of the function at the given dispatch offset.
GLuint _glapi_get_dispatch_table_size (void)
Return size of dispatch table struct as number of functions (or slots).
Variables
static struct _glapi_function ExtEntryTable [MAX_EXTENSION_FUNCS]
static GLuint NumExtEntryPoints = 0
Detailed Description
Code for implementing glXGetProcAddress(), etc.
This was originally in glapi.c but refactored out.
Macro Definition Documentation
FIRST_DYNAMIC_OFFSET
#define FIRST_DYNAMIC_OFFSET (sizeof(struct _glapi_table) / sizeof(void *))
Referenced by _glapi_add_dispatch(), and _glapi_get_dispatch_table_size().
NEED_FUNCTION_POINTER
#define NEED_FUNCTION_POINTER
Function Documentation
_glapi_add_dispatch()
int _glapi_add_dispatch (const char *const * function_names, const char * parameter_signature)
Fill-in the dispatch stub for the named function.
This function is intended to be called by a hardware driver. When called, a dispatch stub may be created for the function. A pointer to this dispatch function will be returned by glXGetProcAddress.
Parameters
function_names Array of pointers to function names that should share a common dispatch offset.
parameter_signature String representing the types of the parameters passed to the named function. Parameter types are converted to characters using the following rules:
'i' for GLint, GLuint, and GLenum
'p' for any pointer type
'f' for GLfloat and GLclampf
'd' for GLdouble and GLclampd
Returns
The offset in the dispatch table of the named function. A pointer to the driver's implementation of the named function should be stored at dispatch_table[offset]. Return -1 if error/problem.
See also
glXGetProcAddress
Warning
This function can only handle up to 8 names at a time. As far as I know, the maximum number of names ever associated with an existing GL function is 4 (glPointParameterfSGIS, glPointParameterfEXT, glPointParameterfARB, and glPointParameterf), so this should not be too painful of a limitation.
Todo:
Determine whether or not parameter_signature should be allowed to be NULL. It doesn't seem like much of a hardship for drivers to have to pass in an empty string.
Todo:
Determine if code should be added to reject function names that start with 'glX'.
Bug:
Add code to compare parameter_signature with the parameter signature of a static function. In order to do that, we need to find a way to get the parameter signature of a static function.
References add_function_name(), _glapi_function::dispatch_offset, FIRST_DYNAMIC_OFFSET, get_extension_proc(), get_static_proc_offset(), init_glapi_relocs_once(), set_entry_info(), and void.
_glapi_get_dispatch_table_size()
GLuint _glapi_get_dispatch_table_size (void)
Return size of dispatch table struct as number of functions (or slots).
References FIRST_DYNAMIC_OFFSET, and MAX_EXTENSION_FUNCS.
_glapi_get_proc_address()
_glapi_proc _glapi_get_proc_address (const char * funcName)
Return pointer to the named function.
If the function name isn't found in the name of static functions, try generating a new API entrypoint on the fly with assembly language.
References add_function_name(), _glapi_function::dispatch_stub, get_extension_proc_address(), get_static_proc_address(), and init_glapi_relocs_once().
_glapi_get_proc_name()
const char* _glapi_get_proc_name (GLuint offset)
Return the name of the function at the given dispatch offset.
This is only intended for debugging.
References get_extension_proc_name(), get_static_proc_name(), and GLuint.
_glapi_get_proc_offset()
GLint _glapi_get_proc_offset (const char * funcName)
Return offset of entrypoint for named function within dispatch table.
References get_extension_proc_offset(), and get_static_proc_offset().
add_function_name()
static struct _glapi_function* add_function_name (const char * funcName) static
Generate new entrypoint.
Use a temporary dispatch offset of ~0 (i.e. -1). Later, when the driver calls _glapi_add_dispatch we'll put in the proper offset. If that never happens, and the user calls this function, he'll segfault. That's what you get when you try calling a GL function that doesn't really exist.
Parameters
funcName Name of the function to create an entry-point for.
See also
_glapi_add_entrypoint
References _glapi_function::dispatch_offset, _glapi_function::dispatch_stub, ExtEntryTable, generate_entrypoint(), MAX_EXTENSION_FUNCS, _glapi_function::name, NumExtEntryPoints, _glapi_function::parameter_signature, and str_dup().
Referenced by _glapi_add_dispatch(), and _glapi_get_proc_address().
get_extension_proc()
static struct _glapi_function* get_extension_proc (const char * funcName) static
References ExtEntryTable, GLuint, _glapi_function::name, and NumExtEntryPoints.
Referenced by _glapi_add_dispatch(), get_extension_proc_address(), and get_extension_proc_offset().
get_extension_proc_address()
static _glapi_proc get_extension_proc_address (const char * funcName) static
References _glapi_function::dispatch_stub, and get_extension_proc().
Referenced by _glapi_get_proc_address().
get_extension_proc_name()
static const char* get_extension_proc_name (GLuint offset) static
References _glapi_function::dispatch_offset, ExtEntryTable, GLuint, _glapi_function::name, and NumExtEntryPoints.
Referenced by _glapi_get_proc_name().
get_extension_proc_offset()
static GLint get_extension_proc_offset (const char * funcName) static
References _glapi_function::dispatch_offset, and get_extension_proc().
Referenced by _glapi_get_proc_offset().
get_static_proc()
static const glprocs_table_t* get_static_proc (const char * n) static
Search the table of static entrypoint functions for the named function and return the corresponding glprocs_table_t entry.
References GLuint.
Referenced by get_static_proc_address(), and get_static_proc_offset().
get_static_proc_address()
static _glapi_proc get_static_proc_address (const char * funcName) static
Return dispatch function address for the named static (built-in) function.
Return NULL if function not found.
References get_entrypoint_address(), and get_static_proc().
Referenced by _glapi_get_proc_address().
get_static_proc_name()
static const char* get_static_proc_name (GLuint offset) static
Return the name of the function at the given offset in the dispatch table.
For debugging only.
References GLuint.
Referenced by _glapi_get_proc_name().
get_static_proc_offset()
static GLint get_static_proc_offset (const char * funcName) static
Return dispatch table offset of the named static (built-in) function.
Return -1 if function not found.
References get_static_proc().
Referenced by _glapi_add_dispatch(), and _glapi_get_proc_offset().
set_entry_info()
static struct _glapi_function* set_entry_info (struct _glapi_function * entry, const char * signature, unsigned offset) static
References _glapi_function::dispatch_offset, _glapi_function::dispatch_stub, fill_in_entrypoint_offset(), _glapi_function::parameter_signature, and str_dup().
Referenced by _glapi_add_dispatch().
str_dup()
static char* str_dup (const char * str) static
strdup() is actually not a standard ANSI C or POSIX routine.
Irix will not define it if ANSI mode is in effect.
Referenced by add_function_name(), and set_entry_info().
Variable Documentation
ExtEntryTable
struct _glapi_function ExtEntryTable[MAX_EXTENSION_FUNCS] static
Referenced by add_function_name(), get_extension_proc(), and get_extension_proc_name().
NumExtEntryPoints
GLuint NumExtEntryPoints = 0 static
Referenced by add_function_name(), get_extension_proc(), and get_extension_proc_name().