Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_move_comparisons.c File Reference
This pass moves ALU comparison operations just before their first use.
#include "nir.h"
Functions
static bool is_comparison (nir_op op)
static bool move_comparison_source (nir_src *src, nir_block *block, nir_instr *before)
static bool move_comparison_source_cb (nir_src *src, void *data)
static bool move_comparisons (nir_block *block)
bool nir_opt_move_comparisons (nir_shader *shader)
Detailed Description
This pass moves ALU comparison operations just before their first use.
It only moves instructions within a single basic block; cross-block movement is left to global code motion.
Many GPUs generate condition codes for comparisons, and use predication for conditional selects and control flow. In a sequence such as:
vec1 32 ssa_1 = flt a b
<some other operations>
vec1 32 ssa_2 = bcsel ssa_1 c d
the backend would likely do the comparison, producing condition codes, then save those to a boolean value. The intervening operations might trash the condition codes. Then, in order to do the bcsel, it would need to re-populate the condition code register based on the boolean.
By moving the comparison just before the bcsel, the condition codes could be used directly. This eliminates the need to reload them from the boolean (generally eliminating an instruction). It may also eliminate the need to create a boolean value altogether (unless it's used elsewhere), which could lower register pressure.
Function Documentation
is_comparison()
static bool is_comparison (nir_op op) static
Referenced by move_comparison_source().
move_comparison_source()
static bool move_comparison_source (nir_src * src, nir_block * block, nir_instr * before) static
References nir_instr::block, nir_block::instr_list, is_comparison(), nir_src::is_ssa, nir_instr_type_alu, nir_instr::node, nir_ssa_def::parent_instr, nir_src::ssa, and nir_instr::type.
Referenced by move_comparison_source_cb(), and move_comparisons().
move_comparison_source_cb()
static bool move_comparison_source_cb (nir_src * src, void * data) static
References nir_instr::block, instr, move_comparison_source(), and nir_src::parent_instr.
Referenced by move_comparisons().
move_comparisons()
static bool move_comparisons (nir_block * block) static
References nir_if::condition, instr, move_comparison_source(), move_comparison_source_cb(), nir_block_get_following_if(), nir_foreach_instr_reverse, nir_foreach_src(), nir_instr_type_alu, nir_instr_type_phi, nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_src::src, and nir_alu_instr::src.
Referenced by nir_opt_move_comparisons().
nir_opt_move_comparisons()
bool nir_opt_move_comparisons (nir_shader * shader)
References move_comparisons(), nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, and nir_metadata_preserve().