Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_dce.c File Reference
#include "nir.h"
Data Structures
struct worklist_elem
Functions
static void worklist_push (struct exec_list *worklist, nir_instr *instr)
static nir_instr * worklist_pop (struct exec_list *worklist)
static bool mark_live_cb (nir_src *src, void *_state)
static void init_instr (nir_instr *instr, struct exec_list *worklist)
static bool init_block (nir_block *block, struct exec_list *worklist)
static bool nir_opt_dce_impl (nir_function_impl *impl)
bool nir_opt_dce (nir_shader *shader)
Function Documentation
init_block()
static bool init_block (nir_block * block, struct exec_list * worklist) static
References nir_if::condition, init_instr(), instr, nir_src::is_ssa, nir_block_get_following_if(), nir_foreach_instr, nir_ssa_def::parent_instr, nir_instr::pass_flags, nir_src::ssa, and worklist_push().
Referenced by nir_opt_dce_impl().
init_instr()
static void init_instr (nir_instr * instr, struct exec_list * worklist) static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, nir_tex_instr::dest, nir_intrinsic_info::flags, nir_intrinsic_info::has_dest, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_tex, NIR_INTRINSIC_CAN_ELIMINATE, nir_intrinsic_infos, nir_instr::pass_flags, nir_instr::type, and worklist_push().
Referenced by init_block().
mark_live_cb()
static bool mark_live_cb (nir_src * src, void * _state) static
References nir_src::is_ssa, nir_ssa_def::parent_instr, nir_instr::pass_flags, nir_src::ssa, and worklist_push().
Referenced by nir_opt_dce_impl().
nir_opt_dce()
bool nir_opt_dce (nir_shader * shader)
References nir_foreach_function, and nir_opt_dce_impl().
nir_opt_dce_impl()
static bool nir_opt_dce_impl (nir_function_impl * impl) static
References init_block(), instr, mark_live_cb(), nir_foreach_block, nir_foreach_instr_safe, nir_foreach_src(), nir_instr_remove(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and worklist_pop().
Referenced by nir_opt_dce().
worklist_pop()
static nir_instr* worklist_pop (struct exec_list * worklist) static
References exec_node_data, and worklist_elem::instr.
Referenced by nir_opt_dce_impl().
worklist_push()
static void worklist_push (struct exec_list * worklist, nir_instr * instr) static
References worklist_elem::instr, instr, worklist_elem::node, and nir_instr::pass_flags.
Referenced by init_block(), init_instr(), and mark_live_cb().