Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_vars_to_ssa.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "nir_phi_builder.h"
#include "nir_vla.h"
Data Structures
struct deref_node
struct lower_variables_state
Functions
static struct deref_node * deref_node_create (struct deref_node *parent, const struct glsl_type *type, nir_shader *shader)
static struct deref_node * get_deref_node_for_var (nir_variable *var, struct lower_variables_state *state)
static struct deref_node * get_deref_node (nir_deref_var *deref, struct lower_variables_state *state)
static bool foreach_deref_node_worker (struct deref_node *node, nir_deref *deref, bool(*cb)(struct deref_node *node, struct lower_variables_state *state), struct lower_variables_state *state)
static bool foreach_deref_node_match (nir_deref_var *deref, bool(*cb)(struct deref_node *node, struct lower_variables_state *state), struct lower_variables_state *state)
static bool deref_may_be_aliased_node (struct deref_node *node, nir_deref *deref, struct lower_variables_state *state)
static bool deref_may_be_aliased (nir_deref_var *deref, struct lower_variables_state *state)
static void register_load_instr (nir_intrinsic_instr *load_instr, struct lower_variables_state *state)
static void register_store_instr (nir_intrinsic_instr *store_instr, struct lower_variables_state *state)
static void register_copy_instr (nir_intrinsic_instr *copy_instr, struct lower_variables_state *state)
static bool register_variable_uses_block (nir_block *block, struct lower_variables_state *state)
static bool lower_copies_to_load_store (struct deref_node *node, struct lower_variables_state *state)
static bool rename_variables (struct lower_variables_state *state)
static bool nir_lower_vars_to_ssa_impl (nir_function_impl *impl)
Implements a pass to lower variable uses to SSA values.
bool nir_lower_vars_to_ssa (nir_shader *shader)
Function Documentation
deref_may_be_aliased()
static bool deref_may_be_aliased (nir_deref_var * deref, struct lower_variables_state * state) static
References nir_deref_var::deref, deref_may_be_aliased_node(), get_deref_node_for_var(), and nir_deref_var::var.
Referenced by nir_lower_vars_to_ssa_impl().
deref_may_be_aliased_node()
static bool deref_may_be_aliased_node (struct deref_node * node, nir_deref * deref, struct lower_variables_state * state) static
References nir_deref_array::base_offset, nir_deref::child, deref_node::children, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_struct::index, deref_node::indirect, nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_type_array, nir_deref_type_struct, and deref_node::wildcard.
Referenced by deref_may_be_aliased().
deref_node_create()
static struct deref_node* deref_node_create (struct deref_node * parent, const struct glsl_type * type, nir_shader * shader) static
References deref_node::deref, deref_node::direct_derefs_link, deref_node::parent, and deref_node::type.
Referenced by get_deref_node(), and get_deref_node_for_var().
foreach_deref_node_match()
static bool foreach_deref_node_match (nir_deref_var * deref, bool(*)(struct deref_node *node, struct lower_variables_state *state) cb, struct lower_variables_state * state) static
References nir_deref::child, deref_node::deref, nir_deref_var::deref, foreach_deref_node_worker(), and get_deref_node().
Referenced by nir_lower_vars_to_ssa_impl().
foreach_deref_node_worker()
static bool foreach_deref_node_worker (struct deref_node * node, nir_deref * deref, bool(*)(struct deref_node *node, struct lower_variables_state *state) cb, struct lower_variables_state * state) static
References nir_deref_array::base_offset, nir_deref::child, deref_node::children, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_struct::index, nir_deref_array_type_direct, nir_deref_type_array, nir_deref_type_struct, and deref_node::wildcard.
Referenced by foreach_deref_node_match().
get_deref_node()
static struct deref_node* get_deref_node (nir_deref_var * deref, struct lower_variables_state * state) static
References lower_variables_state::add_to_direct_deref_nodes, nir_deref_array::base_offset, nir_deref::child, deref_node::children, lower_variables_state::dead_ctx, deref_node::deref, nir_deref_var::deref, nir_deref_array::deref_array_type, deref_node_create(), lower_variables_state::direct_deref_nodes, deref_node::direct_derefs_link, get_deref_node_for_var(), nir_deref_struct::index, deref_node::indirect, exec_node::next, nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_array_type_wildcard, nir_deref_type_array, nir_deref_type_struct, deref_node::type, nir_deref::type, nir_deref_var::var, and deref_node::wildcard.
Referenced by foreach_deref_node_match(), lower_copies_to_load_store(), register_copy_instr(), register_load_instr(), register_store_instr(), and rename_variables().
get_deref_node_for_var()
static struct deref_node* get_deref_node_for_var (nir_variable * var, struct lower_variables_state * state) static
References lower_variables_state::dead_ctx, deref_node_create(), lower_variables_state::deref_var_nodes, and nir_variable::type.
Referenced by deref_may_be_aliased(), and get_deref_node().
lower_copies_to_load_store()
static bool lower_copies_to_load_store (struct deref_node * node, struct lower_variables_state * state) static
References deref_node::copies, get_deref_node(), nir_intrinsic_instr::instr, nir_instr_remove(), nir_lower_var_copy_instr(), lower_variables_state::shader, and nir_intrinsic_instr::variables.
Referenced by nir_lower_vars_to_ssa_impl().
nir_lower_vars_to_ssa()
bool nir_lower_vars_to_ssa (nir_shader * shader)
References nir_foreach_function, and nir_lower_vars_to_ssa_impl().
nir_lower_vars_to_ssa_impl()
static bool nir_lower_vars_to_ssa_impl (nir_function_impl * impl) static
Implements a pass to lower variable uses to SSA values.
This path walks the list of instructions and tries to lower as many local variable load/store operations to SSA defs and uses as it can. The process involves four passes:
1) Iterate over all of the instructions and mark where each local variable deref is used in a load, store, or copy. While we're at it, we keep track of all of the fully-qualified (no wildcards) and fully-direct references we see and store them in the direct_deref_nodes hash table.
2) Walk over the list of fully-qualified direct derefs generated in the previous pass. For each deref, we determine if it can ever be aliased, i.e. if there is an indirect reference anywhere that may refer to it. If it cannot be aliased, we mark it for lowering to an SSA value. At this point, we lower any var_copy instructions that use the given deref to load/store operations.
3) Walk over the list of derefs we plan to lower to SSA values and insert phi nodes as needed.
4) Perform "variable renaming" by replacing the load/store instructions with SSA definitions and SSA uses.
References lower_variables_state::add_to_direct_deref_nodes, nir_instr::block, nir_variable::constant_initializer, nir_variable::data, lower_variables_state::dead_ctx, deref_node::deref, deref_may_be_aliased(), lower_variables_state::deref_var_nodes, lower_variables_state::direct_deref_nodes, deref_node::direct_derefs_link, foreach_deref_node_match(), foreach_list_typed, foreach_list_typed_safe, nir_function_impl::function, lower_variables_state::impl, nir_block::index, nir_intrinsic_instr::instr, lower_copies_to_load_store(), deref_node::lower_to_ssa, nir_variable::nir_variable_data::mode, nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), nir_phi_builder_add_value(), nir_phi_builder_create(), nir_phi_builder_finish(), nir_var_local, NIR_VLA, nir_function_impl::num_blocks, deref_node::pb_value, lower_variables_state::phi_builder, register_variable_uses_block(), rename_variables(), lower_variables_state::shader, nir_function::shader, deref_node::stores, deref_node::type, and nir_deref_var::var.
Referenced by nir_lower_vars_to_ssa().
register_copy_instr()
static void register_copy_instr (nir_intrinsic_instr * copy_instr, struct lower_variables_state * state) static
References deref_node::copies, lower_variables_state::dead_ctx, get_deref_node(), and nir_intrinsic_instr::variables.
Referenced by register_variable_uses_block().
register_load_instr()
static void register_load_instr (nir_intrinsic_instr * load_instr, struct lower_variables_state * state) static
References lower_variables_state::dead_ctx, get_deref_node(), deref_node::loads, and nir_intrinsic_instr::variables.
Referenced by register_variable_uses_block().
register_store_instr()
static void register_store_instr (nir_intrinsic_instr * store_instr, struct lower_variables_state * state) static
References lower_variables_state::dead_ctx, get_deref_node(), deref_node::stores, and nir_intrinsic_instr::variables.
Referenced by register_variable_uses_block().
register_variable_uses_block()
static bool register_variable_uses_block (nir_block * block, struct lower_variables_state * state) static
References instr, nir_intrinsic_instr::intrinsic, nir_foreach_instr_safe, nir_instr_type_intrinsic, register_copy_instr(), register_load_instr(), and register_store_instr().
Referenced by nir_lower_vars_to_ssa_impl().
rename_variables()
static bool rename_variables (struct lower_variables_state * state) static
References nir_ssa_def::bit_size, nir_builder::cursor, nir_ssa_undef_instr::def, nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, get_deref_node(), lower_variables_state::impl, nir_alu_instr::instr, nir_intrinsic_instr::instr, nir_ssa_undef_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_dest::is_ssa, deref_node::lower_to_ssa, nir_alu_instr_create(), nir_before_instr(), nir_builder_init(), nir_channel(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_insert_before(), nir_instr_remove(), nir_instr_type_intrinsic, nir_phi_builder_value_get_block_def(), nir_phi_builder_value_set_block_def(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_ssa_undef_instr_create(), nir_swizzle(), nir_vec(), nir_ssa_def::num_components, nir_intrinsic_instr::num_components, deref_node::pb_value, lower_variables_state::shader, nir_alu_src::src, nir_alu_instr::src, nir_intrinsic_instr::src, nir_src::ssa, nir_dest::ssa, nir_alu_src::swizzle, deref_node::type, nir_intrinsic_instr::variables, and nir_alu_dest::write_mask.
Referenced by nir_lower_vars_to_ssa_impl().