Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_split_var_copies.c File Reference
#include "nir.h"
Data Structures
struct split_var_copies_state
Functions
static void split_var_copy_instr (nir_intrinsic_instr *old_copy, nir_deref_var *dest_head, nir_deref_var *src_head, nir_deref *dest_tail, nir_deref *src_tail, struct split_var_copies_state *state)
static bool split_var_copies_block (nir_block *block, struct split_var_copies_state *state)
static bool split_var_copies_impl (nir_function_impl *impl)
bool nir_split_var_copies (nir_shader *shader)
Function Documentation
nir_split_var_copies()
bool nir_split_var_copies (nir_shader * shader)
References nir_foreach_function, split_var_copies_state::progress, and split_var_copies_impl().
split_var_copies_block()
static bool split_var_copies_block (nir_block * block, struct split_var_copies_state * state) static
References split_var_copies_state::dead_ctx, nir_deref_var::deref, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_intrinsic, split_var_copy_instr(), nir_deref::type, and nir_intrinsic_instr::variables.
Referenced by split_var_copies_impl().
split_var_copies_impl()
static bool split_var_copies_impl (nir_function_impl * impl) static
References split_var_copies_state::dead_ctx, nir_function_impl::function, nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), split_var_copies_state::progress, split_var_copies_state::shader, nir_function::shader, and split_var_copies_block().
Referenced by nir_split_var_copies().
split_var_copy_instr()
static void split_var_copy_instr (nir_intrinsic_instr * old_copy, nir_deref_var * dest_head, nir_deref_var * src_head, nir_deref * dest_tail, nir_deref * src_tail, struct split_var_copies_state * state) static
References nir_deref::child, split_var_copies_state::dead_ctx, nir_deref_array::deref, nir_deref_struct::deref, deref, nir_deref_array::deref_array_type, nir_intrinsic_instr::instr, nir_deref_array_create(), nir_deref_array_type_wildcard, nir_deref_struct_create(), nir_deref_var_clone(), nir_instr_insert_after(), nir_intrinsic_instr_create(), split_var_copies_state::progress, split_var_copies_state::shader, nir_deref::type, and nir_intrinsic_instr::variables.
Referenced by split_var_copies_block().