Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_global_vars_to_local.c File Reference
#include "nir.h"
Functions
static bool mark_global_var_uses_block (nir_block *block, nir_function_impl *impl, struct hash_table *var_func_table)
bool nir_lower_global_vars_to_local (nir_shader *shader)
Function Documentation
mark_global_var_uses_block()
static bool mark_global_var_uses_block (nir_block * block, nir_function_impl * impl, struct hash_table * var_func_table) static
References nir_variable::data, instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::mode, nir_foreach_instr, nir_instr_type_intrinsic, nir_intrinsic_infos, nir_var_global, nir_intrinsic_info::num_variables, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_lower_global_vars_to_local().
nir_lower_global_vars_to_local()
bool nir_lower_global_vars_to_local (nir_shader * shader)
References nir_variable::data, mark_global_var_uses_block(), nir_variable::nir_variable_data::mode, nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_preserve(), nir_var_global, nir_var_local, and nir_variable::node.