Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir.h File Reference
#include "util/hash_table.h"
#include "compiler/glsl/list.h"
#include "GL/gl.h"
#include "util/list.h"
#include "util/ralloc.h"
#include "util/set.h"
#include "util/bitset.h"
#include "util/macros.h"
#include "compiler/nir_types.h"
#include "compiler/shader_enums.h"
#include "compiler/shader_info.h"
#include <stdio.h>
#include "nir_opcodes.h"
#include "nir_intrinsics.h"
Data Structures
struct nir_state_slot
Description of built-in state associated with a uniform.
union nir_const_value
struct nir_constant
struct nir_variable
Either a uniform, global variable, shader input, or shader output.
struct nir_variable::nir_variable_data
struct nir_register
struct nir_instr
struct nir_ssa_def
struct nir_reg_src
struct nir_reg_dest
struct nir_src
struct nir_dest
struct nir_alu_src
struct nir_alu_dest
struct nir_op_info
struct nir_alu_instr
struct nir_deref
struct nir_deref_var
struct nir_deref_array
struct nir_deref_struct
struct nir_call_instr
struct nir_intrinsic_instr
Represents an intrinsic.
struct nir_intrinsic_info
struct nir_tex_src
struct nir_tex_instr
struct nir_load_const_instr
struct nir_jump_instr
struct nir_ssa_undef_instr
struct nir_phi_src
struct nir_phi_instr
struct nir_parallel_copy_entry
struct nir_parallel_copy_instr
struct nir_cf_node
struct nir_block
struct nir_if
struct nir_loop_terminator
struct nir_loop_info
struct nir_loop
struct nir_function_impl
struct nir_parameter
struct nir_function
struct nir_shader_compiler_options
struct nir_shader
struct nir_cursor
struct nir_lower_tex_options
struct nir_lower_wpos_ytransform_options
struct nir_lower_drawpixels_options
struct nir_lower_bitmap_options
Macros
#define NIR_FALSE 0u
#define NIR_TRUE (~0u)
#define NIR_DEFINE_CAST(name, in_type, out_type, field, type_field, type_value)
Defines a cast function.
#define nir_foreach_variable(var, var_list) foreach_list_typed(nir_variable, var, node, var_list)
#define nir_foreach_variable_safe(var, var_list) foreach_list_typed_safe(nir_variable, var, node, var_list)
#define nir_foreach_register(reg, reg_list) foreach_list_typed(nir_register, reg, node, reg_list)
#define nir_foreach_register_safe(reg, reg_list) foreach_list_typed_safe(nir_register, reg, node, reg_list)
#define NIR_SRC_INIT nir_src_init()
#define nir_foreach_use(src, reg_or_ssa_def) list_for_each_entry(nir_src, src, &(reg_or_ssa_def)->uses, use_link)
#define nir_foreach_use_safe(src, reg_or_ssa_def) list_for_each_entry_safe(nir_src, src, &(reg_or_ssa_def)->uses, use_link)
#define nir_foreach_if_use(src, reg_or_ssa_def) list_for_each_entry(nir_src, src, &(reg_or_ssa_def)->if_uses, use_link)
#define nir_foreach_if_use_safe(src, reg_or_ssa_def) list_for_each_entry_safe(nir_src, src, &(reg_or_ssa_def)->if_uses, use_link)
#define NIR_DEST_INIT nir_dest_init()
#define nir_foreach_def(dest, reg) list_for_each_entry(nir_dest, dest, &(reg)->defs, reg.def_link)
#define nir_foreach_def_safe(dest, reg) list_for_each_entry_safe(nir_dest, dest, &(reg)->defs, reg.def_link)
#define NIR_ALU_TYPE_SIZE_MASK 0xfffffff8
#define NIR_ALU_TYPE_BASE_TYPE_MASK 0x00000007
#define INTRINSIC(name, num_srcs, src_components, has_dest, dest_components, num_variables, num_indices, idx0, idx1, idx2, flags) nir_intrinsic_##name,
#define LAST_INTRINSIC(name) nir_last_intrinsic = nir_intrinsic_##name,
#define NIR_INTRINSIC_MAX_CONST_INDEX 3
#define nir_foreach_block(block, impl)
#define nir_foreach_block_safe(block, impl)
#define nir_foreach_block_reverse(block, impl)
#define nir_foreach_block_reverse_safe(block, impl)
#define nir_foreach_block_in_cf_node(block, node)
#define _PASS(nir, do_pass)
#define NIR_PASS(progress, nir, pass, ...)
#define NIR_PASS_V(nir, pass, ...)
Typedefs
typedef struct nir_constant nir_constant
typedef struct nir_variable nir_variable
Either a uniform, global variable, shader input, or shader output.
typedef struct nir_register nir_register
typedef struct nir_ssa_def nir_ssa_def
typedef struct nir_src nir_src
typedef struct nir_alu_instr nir_alu_instr
typedef struct nir_deref nir_deref
typedef bool(* nir_foreach_ssa_def_cb) (nir_ssa_def *def, void *state)
typedef bool(* nir_foreach_dest_cb) (nir_dest *dest, void *state)
typedef bool(* nir_foreach_src_cb) (nir_src *src, void *state)
typedef struct nir_lower_tex_options nir_lower_tex_options
typedef struct nir_lower_wpos_ytransform_options nir_lower_wpos_ytransform_options
typedef struct nir_lower_drawpixels_options nir_lower_drawpixels_options
typedef struct nir_lower_bitmap_options nir_lower_bitmap_options
Enumerations
enum nir_variable_mode {
nir_var_shader_in = (1 << 0), nir_var_shader_out = (1 << 1), nir_var_global = (1 << 2), nir_var_local = (1 << 3),
nir_var_uniform = (1 << 4), nir_var_shader_storage = (1 << 5), nir_var_system_value = (1 << 6), nir_var_param = (1 << 7),
nir_var_shared = (1 << 8), nir_var_all = ~0
}
enum nir_depth_layout {
nir_depth_layout_none, nir_depth_layout_any, nir_depth_layout_greater, nir_depth_layout_less,
nir_depth_layout_unchanged
}
Layout qualifiers for gl_FragDepth.
enum nir_instr_type {
nir_instr_type_alu, nir_instr_type_call, nir_instr_type_tex, nir_instr_type_intrinsic,
nir_instr_type_load_const, nir_instr_type_jump, nir_instr_type_ssa_undef, nir_instr_type_phi,
nir_instr_type_parallel_copy
}
enum nir_alu_type {
nir_type_invalid = 0, nir_type_float, nir_type_int, nir_type_uint,
nir_type_bool, nir_type_bool32 = 32 | nir_type_bool, nir_type_int8 = 8 | nir_type_int, nir_type_int16 = 16 | nir_type_int,
nir_type_int32 = 32 | nir_type_int, nir_type_int64 = 64 | nir_type_int, nir_type_uint8 = 8 | nir_type_uint, nir_type_uint16 = 16 | nir_type_uint,
nir_type_uint32 = 32 | nir_type_uint, nir_type_uint64 = 64 | nir_type_uint, nir_type_float16 = 16 | nir_type_float, nir_type_float32 = 32 | nir_type_float,
nir_type_float64 = 64 | nir_type_float
}
enum nir_op_algebraic_property { NIR_OP_IS_COMMUTATIVE = (1 << 0), NIR_OP_IS_ASSOCIATIVE = (1 << 1) }
enum nir_deref_type { nir_deref_type_var, nir_deref_type_array, nir_deref_type_struct }
enum nir_deref_array_type { nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_array_type_wildcard }
enum nir_intrinsic_op { INTRINSIC }
enum nir_lower_io_options { nir_lower_io_force_sample_interpolation = (1 << 1) }
enum nir_lower_int64_options { nir_lower_imul64 = (1 << 0), nir_lower_isign64 = (1 << 1), nir_lower_divmod64 = (1 << 2) }
enum nir_lower_doubles_options {
nir_lower_drcp = (1 << 0), nir_lower_dsqrt = (1 << 1), nir_lower_drsq = (1 << 2), nir_lower_dtrunc = (1 << 3),
nir_lower_dfloor = (1 << 4), nir_lower_dceil = (1 << 5), nir_lower_dfract = (1 << 6), nir_lower_dround_even = (1 << 7),
nir_lower_dmod = (1 << 8)
}
NIR intrinsics semantic flags
information about what the compiler can do with the intrinsics.
See also
nir_intrinsic_info::flags
enum nir_intrinsic_semantic_flag { NIR_INTRINSIC_CAN_ELIMINATE = (1 << 0), NIR_INTRINSIC_CAN_REORDER = (1 << 1) }
Functions
static bool nir_variable_is_global (const nir_variable *var)
static nir_instr * nir_instr_next (nir_instr *instr)
static nir_instr * nir_instr_prev (nir_instr *instr)
static bool nir_instr_is_first (nir_instr *instr)
static bool nir_instr_is_last (nir_instr *instr)
static nir_src nir_src_init (void)
static nir_dest nir_dest_init (void)
static nir_src nir_src_for_ssa (nir_ssa_def *def)
static nir_src nir_src_for_reg (nir_register *reg)
static nir_dest nir_dest_for_reg (nir_register *reg)
static unsigned nir_src_bit_size (nir_src src)
static unsigned nir_dest_bit_size (nir_dest dest)
void nir_src_copy (nir_src *dest, const nir_src *src, void *instr_or_if)
void nir_dest_copy (nir_dest *dest, const nir_dest *src, nir_instr *instr)
static unsigned nir_alu_type_get_type_size (nir_alu_type type)
static unsigned nir_alu_type_get_base_type (nir_alu_type type)
static nir_alu_type nir_get_nir_type_for_glsl_base_type (enum glsl_base_type base_type)
static nir_alu_type nir_get_nir_type_for_glsl_type (const struct glsl_type *type)
nir_op nir_type_conversion_op (nir_alu_type src, nir_alu_type dst)
void nir_alu_src_copy (nir_alu_src *dest, const nir_alu_src *src, nir_alu_instr *instr)
void nir_alu_dest_copy (nir_alu_dest *dest, const nir_alu_dest *src, nir_alu_instr *instr)
static bool nir_alu_instr_channel_used (nir_alu_instr *instr, unsigned src, unsigned channel)
static unsigned nir_ssa_alu_instr_src_components (const nir_alu_instr *instr, unsigned src)
bool nir_alu_srcs_equal (const nir_alu_instr *alu1, const nir_alu_instr *alu2, unsigned src1, unsigned src2)
NIR_DEFINE_CAST (nir_deref_as_var, nir_deref, nir_deref_var, deref, deref_type, nir_deref_type_var) NIR_DEFINE_CAST(nir_deref_as_array
nir_deref_type_array NIR_DEFINE_CAST (nir_deref_as_struct, nir_deref, nir_deref_struct, deref, deref_type, nir_deref_type_struct) static inline nir_deref *nir_deref_tail(nir_deref *deref)
bool nir_foreach_ssa_def (nir_instr *instr, nir_foreach_ssa_def_cb cb, void *state)
bool nir_foreach_dest (nir_instr *instr, nir_foreach_dest_cb cb, void *state)
bool nir_foreach_src (nir_instr *instr, nir_foreach_src_cb cb, void *state)
nir_const_value * nir_src_as_const_value (nir_src src)
bool nir_src_is_dynamically_uniform (nir_src src)
Returns true if the source is known to be dynamically uniform.
bool nir_srcs_equal (nir_src src1, nir_src src2)
void nir_instr_rewrite_src (nir_instr *instr, nir_src *src, nir_src new_src)
void nir_instr_move_src (nir_instr *dest_instr, nir_src *dest, nir_src *src)
void nir_if_rewrite_condition (nir_if *if_stmt, nir_src new_src)
void nir_instr_rewrite_dest (nir_instr *instr, nir_dest *dest, nir_dest new_dest)
void nir_ssa_dest_init (nir_instr *instr, nir_dest *dest, unsigned num_components, unsigned bit_size, const char *name)
void nir_ssa_def_init (nir_instr *instr, nir_ssa_def *def, unsigned num_components, unsigned bit_size, const char *name)
void nir_ssa_def_rewrite_uses (nir_ssa_def *def, nir_src new_src)
void nir_ssa_def_rewrite_uses_after (nir_ssa_def *def, nir_src new_src, nir_instr *after_me)
uint8_t nir_ssa_def_components_read (nir_ssa_def *def)
nir_block * nir_block_cf_tree_next (nir_block *block)
nir_block * nir_block_cf_tree_prev (nir_block *block)
nir_block * nir_cf_node_cf_tree_first (nir_cf_node *node)
nir_block * nir_cf_node_cf_tree_last (nir_cf_node *node)
nir_block * nir_cf_node_cf_tree_next (nir_cf_node *node)
nir_if * nir_block_get_following_if (nir_block *block)
nir_loop * nir_block_get_following_loop (nir_block *block)
void nir_index_local_regs (nir_function_impl *impl)
void nir_index_global_regs (nir_shader *shader)
void nir_index_ssa_defs (nir_function_impl *impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
unsigned nir_index_instrs (nir_function_impl *impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
void nir_index_blocks (nir_function_impl *impl)
void nir_print_shader (nir_shader *shader, FILE *fp)
void nir_print_shader_annotated (nir_shader *shader, FILE *fp, struct hash_table *errors)
void nir_print_instr (const nir_instr *instr, FILE *fp)
nir_shader * nir_shader_clone (void *mem_ctx, const nir_shader *s)
nir_function_impl * nir_function_impl_clone (const nir_function_impl *fi)
nir_constant * nir_constant_clone (const nir_constant *c, nir_variable *var)
nir_variable * nir_variable_clone (const nir_variable *c, nir_shader *shader)
nir_deref * nir_deref_clone (const nir_deref *deref, void *mem_ctx)
nir_deref_var * nir_deref_var_clone (const nir_deref_var *deref, void *mem_ctx)
static void nir_validate_shader (nir_shader *shader)
static void nir_metadata_set_validation_flag (nir_shader *shader)
static void nir_metadata_check_validation_flag (nir_shader *shader)
static bool should_clone_nir (void)
void nir_calc_dominance_impl (nir_function_impl *impl)
void nir_calc_dominance (nir_shader *shader)
nir_block * nir_dominance_lca (nir_block *b1, nir_block *b2)
Computes the least common anscestor of two blocks.
bool nir_block_dominates (nir_block *parent, nir_block *child)
Returns true if parent dominates child.
void nir_dump_dom_tree_impl (nir_function_impl *impl, FILE *fp)
void nir_dump_dom_tree (nir_shader *shader, FILE *fp)
void nir_dump_dom_frontier_impl (nir_function_impl *impl, FILE *fp)
void nir_dump_dom_frontier (nir_shader *shader, FILE *fp)
void nir_dump_cfg_impl (nir_function_impl *impl, FILE *fp)
void nir_dump_cfg (nir_shader *shader, FILE *fp)
int nir_gs_count_vertices (const nir_shader *shader)
If a geometry shader emits a constant number of vertices, return the number of vertices.
bool nir_split_var_copies (nir_shader *shader)
bool nir_lower_returns_impl (nir_function_impl *impl)
bool nir_lower_returns (nir_shader *shader)
bool nir_inline_functions (nir_shader *shader)
bool nir_propagate_invariant (nir_shader *shader)
void nir_lower_var_copy_instr (nir_intrinsic_instr *copy, nir_shader *shader)
bool nir_lower_var_copies (nir_shader *shader)
bool nir_lower_global_vars_to_local (nir_shader *shader)
bool nir_lower_indirect_derefs (nir_shader *shader, nir_variable_mode modes)
Lowers indirect variable loads/stores to direct loads/stores.
bool nir_lower_locals_to_regs (nir_shader *shader)
void nir_lower_io_to_temporaries (nir_shader *shader, nir_function_impl *entrypoint, bool outputs, bool inputs)
void nir_shader_gather_info (nir_shader *shader, nir_function_impl *entrypoint)
void nir_assign_var_locations (struct exec_list *var_list, unsigned *size, int(*type_size)(const struct glsl_type *))
bool nir_lower_io (nir_shader *shader, nir_variable_mode modes, int(*type_size)(const struct glsl_type *), nir_lower_io_options)
nir_src * nir_get_io_offset_src (nir_intrinsic_instr *instr)
Return the offset soruce for a load/store intrinsic.
nir_src * nir_get_io_vertex_index_src (nir_intrinsic_instr *instr)
Return the vertex index source for a load/store per_vertex intrinsic.
bool nir_is_per_vertex_io (nir_variable *var, gl_shader_stage stage)
Return true if the given variable is a per-vertex input/output array.
void nir_lower_io_types (nir_shader *shader)
bool nir_lower_regs_to_ssa_impl (nir_function_impl *impl)
bool nir_lower_regs_to_ssa (nir_shader *shader)
bool nir_lower_vars_to_ssa (nir_shader *shader)
bool nir_remove_dead_variables (nir_shader *shader, nir_variable_mode modes)
bool nir_lower_constant_initializers (nir_shader *shader, nir_variable_mode modes)
bool nir_move_vec_src_uses_to_dest (nir_shader *shader)
bool nir_lower_vec_to_movs (nir_shader *shader)
bool nir_lower_alu_to_scalar (nir_shader *shader)
bool nir_lower_load_const_to_scalar (nir_shader *shader)
bool nir_lower_phis_to_scalar (nir_shader *shader)
A pass that lowers vector phi nodes to scalar.
void nir_lower_io_to_scalar (nir_shader *shader, nir_variable_mode mask)
bool nir_lower_samplers (nir_shader *shader, const struct gl_shader_program *shader_program)
bool nir_lower_system_values (nir_shader *shader)
bool nir_lower_tex (nir_shader *shader, const nir_lower_tex_options *options)
bool nir_lower_idiv (nir_shader *shader)
bool nir_lower_clip_vs (nir_shader *shader, unsigned ucp_enables)
bool nir_lower_clip_fs (nir_shader *shader, unsigned ucp_enables)
bool nir_lower_clip_cull_distance_arrays (nir_shader *nir)
void nir_lower_two_sided_color (nir_shader *shader)
bool nir_lower_clamp_color_outputs (nir_shader *shader)
void nir_lower_passthrough_edgeflags (nir_shader *shader)
void nir_lower_tes_patch_vertices (nir_shader *tes, unsigned patch_vertices)
bool nir_lower_wpos_ytransform (nir_shader *shader, const nir_lower_wpos_ytransform_options *options)
bool nir_lower_wpos_center (nir_shader *shader, const bool for_sample_shading)
void nir_lower_drawpixels (nir_shader *shader, const nir_lower_drawpixels_options *options)
void nir_lower_bitmap (nir_shader *shader, const nir_lower_bitmap_options *options)
bool nir_lower_atomics (nir_shader *shader, const struct gl_shader_program *shader_program)
bool nir_lower_to_source_mods (nir_shader *shader)
bool nir_lower_gs_intrinsics (nir_shader *shader)
bool nir_lower_int64 (nir_shader *shader, nir_lower_int64_options options)
bool nir_lower_doubles (nir_shader *shader, nir_lower_doubles_options options)
bool nir_lower_64bit_pack (nir_shader *shader)
bool nir_normalize_cubemap_coords (nir_shader *shader)
void nir_live_ssa_defs_impl (nir_function_impl *impl)
void nir_loop_analyze_impl (nir_function_impl *impl, nir_variable_mode indirect_mask)
bool nir_ssa_defs_interfere (nir_ssa_def *a, nir_ssa_def *b)
bool nir_repair_ssa_impl (nir_function_impl *impl)
bool nir_repair_ssa (nir_shader *shader)
This pass can be used to repair SSA form in a shader.
void nir_convert_loop_to_lcssa (nir_loop *loop)
bool nir_convert_from_ssa (nir_shader *shader, bool phi_webs_only)
bool nir_lower_phis_to_regs_block (nir_block *block)
Lower all of the phi nodes in a block to imovs to and from a register.
bool nir_lower_ssa_defs_to_regs_block (nir_block *block)
Lower all of the SSA defs in a block to registers.
bool nir_opt_algebraic (nir_shader *shader)
bool nir_opt_algebraic_late (nir_shader *shader)
bool nir_opt_constant_folding (nir_shader *shader)
bool nir_opt_global_to_local (nir_shader *shader)
bool nir_copy_prop (nir_shader *shader)
bool nir_opt_copy_prop_vars (nir_shader *shader)
bool nir_opt_cse (nir_shader *shader)
bool nir_opt_dce (nir_shader *shader)
bool nir_opt_dead_cf (nir_shader *shader)
bool nir_opt_gcm (nir_shader *shader, bool value_number)
bool nir_opt_if (nir_shader *shader)
bool nir_opt_loop_unroll (nir_shader *shader, nir_variable_mode indirect_mask)
bool nir_opt_move_comparisons (nir_shader *shader)
bool nir_opt_peephole_select (nir_shader *shader, unsigned limit)
bool nir_opt_remove_phis (nir_shader *shader)
bool nir_opt_trivial_continues (nir_shader *shader)
This simple pass gets rid of any "trivial" continues, i.e.
bool nir_opt_undef (nir_shader *shader)
bool nir_opt_conditional_discard (nir_shader *shader)
void nir_sweep (nir_shader *shader)
nir_intrinsic_op nir_intrinsic_from_system_value (gl_system_value val)
gl_system_value nir_system_value_from_intrinsic (nir_intrinsic_op intrin)
Variables
const nir_op_info nir_op_infos [nir_num_opcodes]
nir_deref_array
deref
deref_type
NIR intrinsics const-index flag
Indicates the usage of a const_index slot.
See also
nir_intrinsic_info::index_map
#define NIR_INTRINSIC_MAX_INPUTS 4
#define INTRINSIC_IDX_ACCESSORS(name, flag, type)
#define nir_foreach_phi_src(phi_src, phi) foreach_list_typed(nir_phi_src, phi_src, node, &(phi)->srcs)
#define nir_foreach_phi_src_safe(phi_src, phi) foreach_list_typed_safe(nir_phi_src, phi_src, node, &(phi)->srcs)
#define nir_foreach_parallel_copy_entry(entry, pcopy) foreach_list_typed(nir_parallel_copy_entry, entry, node, &(pcopy)->entries)
#define nir_foreach_instr(instr, block) foreach_list_typed(nir_instr, instr, node, &(block)->instr_list)
#define nir_foreach_instr_reverse(instr, block) foreach_list_typed_reverse(nir_instr, instr, node, &(block)->instr_list)
#define nir_foreach_instr_safe(instr, block) foreach_list_typed_safe(nir_instr, instr, node, &(block)->instr_list)
#define nir_foreach_instr_reverse_safe(instr, block) foreach_list_typed_reverse_safe(nir_instr, instr, node, &(block)->instr_list)
#define nir_foreach_function(func, shader) foreach_list_typed(nir_function, func, node, &(shader)->functions)
enum nir_intrinsic_index_flag {
NIR_INTRINSIC_BASE = 1, NIR_INTRINSIC_WRMASK = 2, NIR_INTRINSIC_STREAM_ID = 3, NIR_INTRINSIC_UCP_ID = 4,
NIR_INTRINSIC_RANGE = 5, NIR_INTRINSIC_DESC_SET = 6, NIR_INTRINSIC_BINDING = 7, NIR_INTRINSIC_COMPONENT = 8,
NIR_INTRINSIC_INTERP_MODE = 9, NIR_INTRINSIC_NUM_INDEX_FLAGS
}
enum nir_tex_src_type {
nir_tex_src_coord, nir_tex_src_projector, nir_tex_src_comparator, nir_tex_src_offset,
nir_tex_src_bias, nir_tex_src_lod, nir_tex_src_ms_index, nir_tex_src_ms_mcs,
nir_tex_src_ddx, nir_tex_src_ddy, nir_tex_src_texture_offset, nir_tex_src_sampler_offset,
nir_tex_src_plane, nir_num_tex_src_types
}
texture information
enum nir_texop {
nir_texop_tex, nir_texop_txb, nir_texop_txl, nir_texop_txd,
nir_texop_txf, nir_texop_txf_ms, nir_texop_txf_ms_mcs, nir_texop_txs,
nir_texop_lod, nir_texop_tg4, nir_texop_query_levels, nir_texop_texture_samples,
nir_texop_samples_identical
}
enum nir_jump_type { nir_jump_return, nir_jump_break, nir_jump_continue }
enum nir_metadata {
nir_metadata_none = 0x0, nir_metadata_block_index = 0x1, nir_metadata_dominance = 0x2, nir_metadata_live_ssa_defs = 0x4,
nir_metadata_not_properly_reset = 0x8, nir_metadata_loop_analysis = 0x10
}
Various bits of metadata that can may be created or required by optimization and analysis passes.
enum nir_parameter_type { nir_parameter_in, nir_parameter_out, nir_parameter_inout }
enum nir_cursor_option { nir_cursor_before_block, nir_cursor_after_block, nir_cursor_before_instr, nir_cursor_after_instr }
NIR Cursors and Instruction Insertion API.
typedef struct nir_instr nir_instr
typedef struct nir_cf_node nir_cf_node
typedef struct nir_block nir_block
typedef struct nir_if nir_if
typedef struct nir_function nir_function
typedef struct nir_shader_compiler_options nir_shader_compiler_options
typedef struct nir_shader nir_shader
typedef bool(* nir_deref_foreach_leaf_cb) (nir_deref_var *deref, void *state)
const nir_intrinsic_info nir_intrinsic_infos [nir_num_intrinsics]
nir_call_instr
instr
type
nir_instr_type_call nir_tex_instr
nir_instr_type_call nir_instr_type_tex nir_load_const_instr
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const nir_phi_instr
nir_cf_node_type
cf_node
nir_cf_node_if nir_function_impl
static unsigned nir_tex_instr_dest_size (nir_tex_instr *instr)
static bool nir_tex_instr_is_query (nir_tex_instr *instr)
static nir_alu_type nir_tex_instr_src_type (nir_tex_instr *instr, unsigned src)
static unsigned nir_tex_instr_src_size (nir_tex_instr *instr, unsigned src)
static int nir_tex_instr_src_index (nir_tex_instr *instr, nir_tex_src_type type)
void nir_tex_instr_remove_src (nir_tex_instr *tex, unsigned src_idx)
NIR_DEFINE_CAST (nir_instr_as_alu, nir_instr, nir_alu_instr, instr, type, nir_instr_type_alu) NIR_DEFINE_CAST(nir_instr_as_call
nir_instr_type_call NIR_DEFINE_CAST (nir_instr_as_jump, nir_instr, nir_jump_instr, instr, type, nir_instr_type_jump) NIR_DEFINE_CAST(nir_instr_as_tex
nir_instr_type_call nir_instr_type_tex NIR_DEFINE_CAST (nir_instr_as_intrinsic, nir_instr, nir_intrinsic_instr, instr, type, nir_instr_type_intrinsic) NIR_DEFINE_CAST(nir_instr_as_load_const
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const NIR_DEFINE_CAST (nir_instr_as_ssa_undef, nir_instr, nir_ssa_undef_instr, instr, type, nir_instr_type_ssa_undef) NIR_DEFINE_CAST(nir_instr_as_phi
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const nir_instr_type_phi NIR_DEFINE_CAST (nir_instr_as_parallel_copy, nir_instr, nir_parallel_copy_instr, instr, type, nir_instr_type_parallel_copy) typedef enum
static nir_instr * nir_block_first_instr (nir_block *block)
static nir_instr * nir_block_last_instr (nir_block *block)
static ATTRIBUTE_RETURNS_NONNULL nir_block * nir_start_block (nir_function_impl *impl)
static ATTRIBUTE_RETURNS_NONNULL nir_block * nir_impl_last_block (nir_function_impl *impl)
static nir_cf_node * nir_cf_node_next (nir_cf_node *node)
static nir_cf_node * nir_cf_node_prev (nir_cf_node *node)
static bool nir_cf_node_is_first (const nir_cf_node *node)
static bool nir_cf_node_is_last (const nir_cf_node *node)
NIR_DEFINE_CAST (nir_cf_node_as_block, nir_cf_node, nir_block, cf_node, type, nir_cf_node_block) NIR_DEFINE_CAST(nir_cf_node_as_if
nir_cf_node_if NIR_DEFINE_CAST (nir_cf_node_as_loop, nir_cf_node, nir_loop, cf_node, type, nir_cf_node_loop) NIR_DEFINE_CAST(nir_cf_node_as_function
nir_cf_node_if static nir_cf_node_function nir_block * nir_if_first_then_block (nir_if *if_stmt)
static nir_block * nir_if_last_then_block (nir_if *if_stmt)
static nir_block * nir_if_first_else_block (nir_if *if_stmt)
static nir_block * nir_if_last_else_block (nir_if *if_stmt)
static nir_block * nir_loop_first_block (nir_loop *loop)
static nir_block * nir_loop_last_block (nir_loop *loop)
static nir_function_impl * nir_shader_get_entrypoint (nir_shader *shader)
nir_shader * nir_shader_create (void *mem_ctx, gl_shader_stage stage, const nir_shader_compiler_options *options, shader_info *si)
nir_register * nir_global_reg_create (nir_shader *shader)
creates a register, including assigning it an index and adding it to the list
nir_register * nir_local_reg_create (nir_function_impl *impl)
void nir_reg_remove (nir_register *reg)
void nir_shader_add_variable (nir_shader *shader, nir_variable *var)
Adds a variable to the appropriate list in nir_shader.
static void nir_function_impl_add_variable (nir_function_impl *impl, nir_variable *var)
nir_variable * nir_variable_create (nir_shader *shader, nir_variable_mode mode, const struct glsl_type *type, const char *name)
creates a variable, sets a few defaults, and adds it to the list
nir_variable * nir_local_variable_create (nir_function_impl *impl, const struct glsl_type *type, const char *name)
creates a local variable and adds it to the list
nir_function * nir_function_create (nir_shader *shader, const char *name)
creates a function and adds it to the shader's list of functions
nir_function_impl * nir_function_impl_create (nir_function *func)
nir_function_impl * nir_function_impl_create_bare (nir_shader *shader)
creates a function_impl that isn't tied to any particular function
nir_block * nir_block_create (nir_shader *shader)
nir_if * nir_if_create (nir_shader *shader)
nir_loop * nir_loop_create (nir_shader *shader)
nir_function_impl * nir_cf_node_get_function (nir_cf_node *node)
void nir_metadata_require (nir_function_impl *impl, nir_metadata required,...)
requests that the given pieces of metadata be generated
void nir_metadata_preserve (nir_function_impl *impl, nir_metadata preserved)
dirties all but the preserved metadata
nir_alu_instr * nir_alu_instr_create (nir_shader *shader, nir_op op)
creates an instruction with default swizzle/writemask/etc.
nir_jump_instr * nir_jump_instr_create (nir_shader *shader, nir_jump_type type)
nir_load_const_instr * nir_load_const_instr_create (nir_shader *shader, unsigned num_components, unsigned bit_size)
nir_intrinsic_instr * nir_intrinsic_instr_create (nir_shader *shader, nir_intrinsic_op op)
nir_call_instr * nir_call_instr_create (nir_shader *shader, nir_function *callee)
nir_tex_instr * nir_tex_instr_create (nir_shader *shader, unsigned num_srcs)
nir_phi_instr * nir_phi_instr_create (nir_shader *shader)
nir_parallel_copy_instr * nir_parallel_copy_instr_create (nir_shader *shader)
nir_ssa_undef_instr * nir_ssa_undef_instr_create (nir_shader *shader, unsigned num_components, unsigned bit_size)
nir_deref_var * nir_deref_var_create (void *mem_ctx, nir_variable *var)
nir_deref_array * nir_deref_array_create (void *mem_ctx)
nir_deref_struct * nir_deref_struct_create (void *mem_ctx, unsigned field_index)
bool nir_deref_foreach_leaf (nir_deref_var *deref, nir_deref_foreach_leaf_cb cb, void *state)
This function iterates over all of the possible derefs that can be created with the given deref as the head.
nir_load_const_instr * nir_deref_get_const_initializer_load (nir_shader *shader, nir_deref_var *deref)
static nir_block * nir_cursor_current_block (nir_cursor cursor)
bool nir_cursors_equal (nir_cursor a, nir_cursor b)
static nir_cursor nir_before_block (nir_block *block)
static nir_cursor nir_after_block (nir_block *block)
static nir_cursor nir_before_instr (nir_instr *instr)
static nir_cursor nir_after_instr (nir_instr *instr)
static nir_cursor nir_after_block_before_jump (nir_block *block)
static nir_cursor nir_before_cf_node (nir_cf_node *node)
static nir_cursor nir_after_cf_node (nir_cf_node *node)
static nir_cursor nir_after_phis (nir_block *block)
static nir_cursor nir_after_cf_node_and_phis (nir_cf_node *node)
static nir_cursor nir_before_cf_list (struct exec_list *cf_list)
static nir_cursor nir_after_cf_list (struct exec_list *cf_list)
void nir_instr_insert (nir_cursor cursor, nir_instr *instr)
Insert a NIR instruction at the given cursor.
static void nir_instr_insert_before (nir_instr *instr, nir_instr *before)
static void nir_instr_insert_after (nir_instr *instr, nir_instr *after)
static void nir_instr_insert_before_block (nir_block *block, nir_instr *before)
static void nir_instr_insert_after_block (nir_block *block, nir_instr *after)
static void nir_instr_insert_before_cf (nir_cf_node *node, nir_instr *before)
static void nir_instr_insert_after_cf (nir_cf_node *node, nir_instr *after)
static void nir_instr_insert_before_cf_list (struct exec_list *list, nir_instr *before)
static void nir_instr_insert_after_cf_list (struct exec_list *list, nir_instr *after)
void nir_instr_remove (nir_instr *instr)
Macro Definition Documentation
_PASS
#define _PASS (nir, do_pass)
Value:
do {                                     \
   do_pass                                                           \
   nir_validate_shader(nir);                                         \
   if (should_clone_nir()) {                                         \
      nir_shader *clone = nir_shader_clone(ralloc_parent(nir), nir); \
      ralloc_free(nir);                                              \
      nir = clone;                                                   \
   }                                                                 \
} while (0)
INTRINSIC
#define INTRINSIC (name, num_srcs, src_components, has_dest, dest_components, num_variables, num_indices, idx0, idx1, idx2, flags) nir_intrinsic_##name,
INTRINSIC_IDX_ACCESSORS
#define INTRINSIC_IDX_ACCESSORS (name, flag, type)
Value:
static inline type                                                            \
nir_intrinsic_##name(nir_intrinsic_instr *instr)                              \
{                                                                             \
   const nir_intrinsic_info *info = &nir_intrinsic_infos[instr->intrinsic];   \
   assert(info->index_map[NIR_INTRINSIC_##flag] > 0);                         \
   return instr->const_index[info->index_map[NIR_INTRINSIC_##flag] - 1];      \
}                                                                             \
static inline void                                                            \
nir_intrinsic_set_##name(nir_intrinsic_instr *instr, type val)                \
{                                                                             \
   const nir_intrinsic_info *info = &nir_intrinsic_infos[instr->intrinsic];   \
   assert(info->index_map[NIR_INTRINSIC_##flag] > 0);                         \
   instr->const_index[info->index_map[NIR_INTRINSIC_##flag] - 1] = val;       \
}
LAST_INTRINSIC
#define LAST_INTRINSIC (name) nir_last_intrinsic = nir_intrinsic_##name,
NIR_ALU_TYPE_BASE_TYPE_MASK
#define NIR_ALU_TYPE_BASE_TYPE_MASK 0x00000007
Referenced by nir_alu_type_get_base_type().
NIR_ALU_TYPE_SIZE_MASK
#define NIR_ALU_TYPE_SIZE_MASK 0xfffffff8
Referenced by nir_alu_type_get_type_size().
NIR_DEFINE_CAST
#define NIR_DEFINE_CAST (name, in_type, out_type, field, type_field, type_value)
Value:
static inline out_type *                                \
name(const in_type *parent)                             \
{                                                       \
   assert(parent && parent->type_field == type_value);  \
   return exec_node_data(out_type, parent, field);      \
}
Defines a cast function.
This macro defines a cast function from in_type to out_type where out_type is some structure type that contains a field of type out_type.
Note that you have to be a bit careful as the generated cast function destroys constness.
Referenced by nir_cf_node_is_last().
NIR_DEST_INIT
#define NIR_DEST_INIT nir_dest_init()
Referenced by nir_dest_for_reg().
NIR_FALSE
#define NIR_FALSE 0u
Referenced by lower_returns_in_block().
nir_foreach_block
#define nir_foreach_block (block, impl)
Value:
for (nir_block *block = nir_start_block(impl); block != NULL; \
        block = nir_block_cf_tree_next(block))
Referenced by add_var_use_shader(), calc_dom_children(), combine_clip_cull(), convert_impl(), emit_output_copies_impl(), get_loop_info(), inline_functions_block(), lower_64bit_pack_impl(), lower_drawpixels_impl(), lower_impl(), lower_int64_impl(), lower_io_types_impl(), lower_phis_to_scalar_impl(), lower_var_copies_impl(), lower_wpos_ytransform_impl(), nir_block_worklist_add_all(), nir_calc_dominance_impl(), nir_convert_from_ssa_impl(), nir_copy_prop_impl(), nir_dump_cfg_impl(), nir_dump_dom_frontier_impl(), nir_dump_dom_tree_impl(), nir_index_blocks(), nir_index_instrs(), nir_index_ssa_defs(), nir_live_ssa_defs_impl(), nir_lower_alu_to_scalar_impl(), nir_lower_atomics(), nir_lower_doubles_impl(), nir_lower_global_vars_to_local(), nir_lower_io_impl(), nir_lower_io_to_scalar(), nir_lower_load_const_to_scalar_impl(), nir_lower_locals_to_regs_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_tes_patch_vertices(), nir_lower_tex_impl(), nir_lower_to_source_mods_impl(), nir_lower_two_sided_color_impl(), nir_lower_vars_to_ssa_impl(), nir_lower_vec_to_movs_impl(), nir_lower_wpos_center(), nir_move_vec_src_uses_to_dest_impl(), nir_opt_constant_folding_impl(), nir_opt_copy_prop_vars(), nir_opt_dce_impl(), nir_opt_move_comparisons(), nir_opt_undef(), nir_phi_builder_create(), nir_repair_ssa_impl(), nir_shader_gather_info(), normalize_cubemap_coords_impl(), opt_gcm_impl(), remove_dead_var_writes(), remove_phis_impl(), rename_variables(), and split_var_copies_impl().
nir_foreach_block_in_cf_node
#define nir_foreach_block_in_cf_node (block, node)
Value:
for (nir_block *block = nir_cf_node_cf_tree_first(node); \
        block != nir_cf_node_cf_tree_next(node); \
        block = nir_block_cf_tree_next(block))
Referenced by cf_node_has_side_effects(), get_loop_info(), and opt_peel_loop_initial_if().
nir_foreach_block_reverse
#define nir_foreach_block_reverse (block, impl)
Value:
for (nir_block *block = nir_impl_last_block(impl); block != NULL; \
        block = nir_block_cf_tree_prev(block))
Referenced by find_output(), and propagate_invariant_impl().
nir_foreach_block_reverse_safe
#define nir_foreach_block_reverse_safe (block, impl)
Value:
for (nir_block *block = nir_impl_last_block(impl), \
        *prev = nir_block_cf_tree_prev(block); \
        block != NULL; \
        block = prev, prev = nir_block_cf_tree_prev(block))
nir_foreach_block_safe
#define nir_foreach_block_safe (block, impl)
Value:
for (nir_block *block = nir_start_block(impl), \
        *next = nir_block_cf_tree_next(block); \
        block != NULL; \
        block = next, next = nir_block_cf_tree_next(block))
Referenced by inline_function_impl(), lower_indirects_impl(), nir_lower_gs_intrinsics(), nir_opt_conditional_discard(), and nir_opt_peephole_select_impl().
nir_foreach_def
#define nir_foreach_def (dest, reg) list_for_each_entry(nir_dest, dest, &(reg)->defs, reg.def_link)
Referenced by global_to_local(), and nir_lower_regs_to_ssa_impl().
nir_foreach_def_safe
#define nir_foreach_def_safe (dest, reg) list_for_each_entry_safe(nir_dest, dest, &(reg)->defs, reg.def_link)
nir_foreach_function
#define nir_foreach_function (func, shader) foreach_list_typed(nir_function, func, node, &(shader)->functions)
Referenced by add_var_use_shader(), combine_clip_cull(), find_output(), nir_calc_dominance(), nir_convert_from_ssa(), nir_copy_prop(), nir_dump_cfg(), nir_dump_dom_frontier(), nir_dump_dom_tree(), nir_gs_count_vertices(), nir_inline_functions(), nir_lower_64bit_pack(), nir_lower_alu_to_scalar(), nir_lower_atomics(), nir_lower_clamp_color_outputs(), nir_lower_clip_fs(), nir_lower_clip_vs(), nir_lower_constant_initializers(), nir_lower_doubles(), nir_lower_drawpixels(), nir_lower_global_vars_to_local(), nir_lower_idiv(), nir_lower_indirect_derefs(), nir_lower_int64(), nir_lower_io(), nir_lower_io_to_scalar(), nir_lower_io_to_temporaries(), nir_lower_io_types(), nir_lower_load_const_to_scalar(), nir_lower_locals_to_regs(), nir_lower_phis_to_scalar(), nir_lower_regs_to_ssa(), nir_lower_returns(), nir_lower_samplers(), nir_lower_system_values(), nir_lower_tes_patch_vertices(), nir_lower_tex(), nir_lower_to_source_mods(), nir_lower_two_sided_color(), nir_lower_var_copies(), nir_lower_vars_to_ssa(), nir_lower_vec_to_movs(), nir_lower_wpos_center(), nir_lower_wpos_ytransform(), nir_metadata_preserve(), nir_move_vec_src_uses_to_dest(), nir_normalize_cubemap_coords(), nir_opt_conditional_discard(), nir_opt_constant_folding(), nir_opt_copy_prop_vars(), nir_opt_cse(), nir_opt_dce(), nir_opt_dead_cf(), nir_opt_gcm(), nir_opt_if(), nir_opt_loop_unroll(), nir_opt_move_comparisons(), nir_opt_peephole_select(), nir_opt_remove_phis(), nir_opt_trivial_continues(), nir_opt_undef(), nir_propagate_invariant(), nir_remove_dead_variables(), nir_repair_ssa(), nir_shader_clone(), nir_split_var_copies(), and remove_dead_var_writes().
nir_foreach_if_use
#define nir_foreach_if_use (src, reg_or_ssa_def) list_for_each_entry(nir_src, src, &(reg_or_ssa_def)->if_uses, use_link)
Referenced by convert_loop_exit_for_ssa(), gcm_schedule_late_def(), and global_to_local().
nir_foreach_if_use_safe
#define nir_foreach_if_use_safe (src, reg_or_ssa_def) list_for_each_entry_safe(nir_src, src, &(reg_or_ssa_def)->if_uses, use_link)
Referenced by convert_loop_exit_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_ssa_def_rewrite_uses_after().
nir_foreach_instr
#define nir_foreach_instr (instr, block) foreach_list_typed(nir_instr, instr, node, &(block)->instr_list)
Referenced by add_var_use_shader(), aggressive_coalesce_block(), block_check_for_allowed_instrs(), cf_node_has_side_effects(), clone_block(), coalesce_phi_nodes_block(), combine_clip_cull(), contains_other_jump(), convert_to_lcssa(), cse_block(), emit_output_copies_impl(), find_output_in_block(), force_unroll_heuristics(), gather_info_block(), get_loop_info(), init_block(), init_loop_block(), inline_functions_block(), insert_phi_undef(), isolate_phi_nodes_block(), loop_is_dead(), lower_impl(), lower_io_types_block(), lower_params_to_locals_block(), lower_phis_to_scalar_block(), lower_wpos_center_block(), mark_global_var_uses_block(), move_vec_src_uses_to_dest_block(), nir_after_phis(), nir_copy_prop_impl(), nir_index_instrs(), nir_index_ssa_defs(), nir_live_ssa_defs_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_ssa_defs_to_regs_block(), nir_lower_to_source_mods_block(), normalize_cubemap_coords_block(), print_block(), propagate_across_edge(), remove_phi_src(), and sweep_block().
nir_foreach_instr_reverse
#define nir_foreach_instr_reverse (instr, block) foreach_list_typed_reverse(nir_instr, instr, node, &(block)->instr_list)
Referenced by move_comparisons(), nir_gs_count_vertices(), nir_live_ssa_defs_impl(), and propagate_invariant_impl().
nir_foreach_instr_reverse_safe
#define nir_foreach_instr_reverse_safe (instr, block) foreach_list_typed_reverse_safe(nir_instr, instr, node, &(block)->instr_list)
nir_foreach_instr_safe
#define nir_foreach_instr_safe (instr, block) foreach_list_typed_safe(nir_instr, instr, node, &(block)->instr_list)
Referenced by cleanup_cf_node(), constant_fold_block(), convert_block(), convert_impl(), copy_prop_vars_block(), cse_block(), gcm_pin_instructions_block(), inline_functions_block(), lower_64bit_pack_impl(), lower_block(), lower_drawpixels_block(), lower_indirect_block(), lower_int64_impl(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_var_copies_impl(), lower_vec_to_movs_block(), lower_wpos_ytransform_block(), nir_lower_alu_to_scalar_impl(), nir_lower_atomics(), nir_lower_doubles_impl(), nir_lower_io_block(), nir_lower_io_to_scalar(), nir_lower_load_const_to_scalar_impl(), nir_lower_phis_to_regs_block(), nir_lower_tes_patch_vertices(), nir_lower_tex_block(), nir_lower_two_sided_color_block(), nir_opt_conditional_discard_block(), nir_opt_dce_impl(), nir_opt_peephole_select_block(), nir_opt_undef(), nir_repair_ssa_impl(), opt_constant_if(), register_variable_uses_block(), remove_dead_var_writes(), remove_phis_block(), rename_variables(), resolve_registers_block(), rewrite_intrinsics(), rewrite_phi_preds(), split_block_before_instr(), split_block_beginning(), and split_var_copies_block().
nir_foreach_parallel_copy_entry
#define nir_foreach_parallel_copy_entry (entry, pcopy) foreach_list_typed(nir_parallel_copy_entry, entry, node, &(pcopy)->entries)
Referenced by aggressive_coalesce_parallel_copy(), print_parallel_copy_instr(), resolve_parallel_copy(), visit_parallel_copy_dest(), and visit_parallel_copy_src().
nir_foreach_phi_src
#define nir_foreach_phi_src (phi_src, phi) foreach_list_typed(nir_phi_src, phi_src, node, &(phi)->srcs)
Referenced by coalesce_phi_nodes_block(), compute_induction_information(), copy_prop_instr(), gcm_schedule_late_def(), hash_phi(), isolate_phi_nodes_block(), lower_phis_to_scalar_block(), nir_instrs_equal(), nir_lower_phis_to_regs_block(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), opt_constant_if(), opt_peel_loop_initial_if(), print_phi_instr(), propagate_across_edge(), propagate_invariant_instr(), remove_phis_block(), rewrite_phi_preds(), should_lower_phi(), and visit_phi_src().
nir_foreach_phi_src_safe
#define nir_foreach_phi_src_safe (phi_src, phi) foreach_list_typed_safe(nir_phi_src, phi_src, node, &(phi)->srcs)
Referenced by remove_phi_src().
nir_foreach_register
#define nir_foreach_register (reg, reg_list) foreach_list_typed(nir_register, reg, node, reg_list)
Referenced by nir_lower_regs_to_ssa_impl().
nir_foreach_register_safe
#define nir_foreach_register_safe (reg, reg_list) foreach_list_typed_safe(nir_register, reg, node, reg_list)
Referenced by nir_lower_regs_to_ssa_impl().
nir_foreach_use
#define nir_foreach_use (src, reg_or_ssa_def) list_for_each_entry(nir_src, src, &(reg_or_ssa_def)->uses, use_link)
Referenced by block_check_for_allowed_instrs(), convert_loop_exit_for_ssa(), gcm_place_instr_def(), gcm_schedule_late_def(), global_to_local(), nir_lower_to_source_mods_block(), nir_ssa_def_components_read(), repair_ssa_def(), and try_coalesce().
nir_foreach_use_safe
#define nir_foreach_use_safe (src, reg_or_ssa_def) list_for_each_entry_safe(nir_src, src, &(reg_or_ssa_def)->uses, use_link)
Referenced by convert_loop_exit_for_ssa(), move_vec_src_uses_to_dest_block(), nir_ssa_def_rewrite_uses(), nir_ssa_def_rewrite_uses_after(), and repair_ssa_def().
nir_foreach_variable
#define nir_foreach_variable (var, var_list) foreach_list_typed(nir_variable, var, node, var_list)
Referenced by combine_clip_cull(), get_new_var(), get_texcoord(), lower_const_initializer(), lower_intrinsic(), nir_assign_var_locations(), nir_lower_clip_fs(), nir_lower_clip_vs(), nir_lower_io_to_temporaries(), nir_print_shader_annotated(), nir_shader_gather_info(), print_function_impl(), print_intrinsic_instr(), and setup_inputs().
nir_foreach_variable_safe
#define nir_foreach_variable_safe (var, var_list) foreach_list_typed_safe(nir_variable, var, node, var_list)
NIR_INTRINSIC_MAX_CONST_INDEX
#define NIR_INTRINSIC_MAX_CONST_INDEX 3
NIR_INTRINSIC_MAX_INPUTS
#define NIR_INTRINSIC_MAX_INPUTS 4
NIR_PASS
#define NIR_PASS (progress, nir, pass, ...)
Value:
_PASS(nir,                \
   nir_metadata_set_validation_flag(nir);                            \
   if (pass(nir, ##__VA_ARGS__)) {                                   \
      progress = true;                                               \
      nir_metadata_check_validation_flag(nir);                       \
   }                                                                 \
)
NIR_PASS_V
#define NIR_PASS_V (nir, pass, ...)
Value:
_PASS(nir,                        \
   pass(nir, ##__VA_ARGS__);                                         \
)
NIR_SRC_INIT
#define NIR_SRC_INIT nir_src_init()
Referenced by calc_sampler_offsets(), construct_value(), deref_foreach_leaf_build_recur(), emit_indirect_load_store(), nir_instr_move_src(), nir_src_for_reg(), nir_src_for_ssa(), nir_ssa_for_src(), nir_swizzle(), nir_tex_instr_remove_src(), and try_coalesce().
NIR_TRUE
#define NIR_TRUE (~0u)
Referenced by lower_returns_in_block(), and lower_udiv64_mod64().
Typedef Documentation
nir_alu_instr
typedef struct nir_alu_instr nir_alu_instr
nir_block
typedef struct nir_block nir_block
nir_cf_node
nir_cf_node_if nir_cf_node
nir_constant
typedef struct nir_constant nir_constant
nir_deref
nir_deref
nir_deref_foreach_leaf_cb
typedef bool(* nir_deref_foreach_leaf_cb) (nir_deref_var *deref, void *state)
nir_foreach_dest_cb
typedef bool(* nir_foreach_dest_cb) (nir_dest *dest, void *state)
nir_foreach_src_cb
typedef bool(* nir_foreach_src_cb) (nir_src *src, void *state)
nir_foreach_ssa_def_cb
typedef bool(* nir_foreach_ssa_def_cb) (nir_ssa_def *def, void *state)
nir_function
typedef struct nir_function nir_function
nir_if
nir_if
nir_instr
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const nir_instr
nir_lower_bitmap_options
typedef struct nir_lower_bitmap_options nir_lower_bitmap_options
nir_lower_drawpixels_options
typedef struct nir_lower_drawpixels_options nir_lower_drawpixels_options
nir_lower_tex_options
typedef struct nir_lower_tex_options nir_lower_tex_options
nir_lower_wpos_ytransform_options
typedef struct nir_lower_wpos_ytransform_options nir_lower_wpos_ytransform_options
nir_register
typedef struct nir_register nir_register
nir_shader
typedef struct nir_shader nir_shader
nir_shader_compiler_options
typedef struct nir_shader_compiler_options nir_shader_compiler_options
nir_src
typedef struct nir_src nir_src
nir_ssa_def
typedef struct nir_ssa_def nir_ssa_def
nir_variable
typedef struct nir_variable nir_variable
Either a uniform, global variable, shader input, or shader output.
Based on ir_variable - it should be easy to translate between the two.
Enumeration Type Documentation
nir_alu_type
enum nir_alu_type
Enumerator
nir_type_invalid
nir_type_float
nir_type_int
nir_type_uint
nir_type_bool
nir_type_bool32
nir_type_int8
nir_type_int16
nir_type_int32
nir_type_int64
nir_type_uint8
nir_type_uint16
nir_type_uint32
nir_type_uint64
nir_type_float16
nir_type_float32
nir_type_float64
nir_cursor_option
enum nir_cursor_option
NIR Cursors and Instruction Insertion API.
A tiny struct representing a point to insert/extract instructions or control flow nodes. Helps reduce the combinatorial explosion of possible points to insert/extract.
See also
nir_control_flow.h
Enumerator
nir_cursor_before_block
nir_cursor_after_block
nir_cursor_before_instr
nir_cursor_after_instr
nir_depth_layout
enum nir_depth_layout
Layout qualifiers for gl_FragDepth.
The AMD/ARB_conservative_depth extensions allow gl_FragDepth to be redeclared with a layout qualifier.
Enumerator
nir_depth_layout_none
No depth layout is specified.
nir_depth_layout_any
nir_depth_layout_greater
nir_depth_layout_less
nir_depth_layout_unchanged
nir_deref_array_type
enum nir_deref_array_type
Enumerator
nir_deref_array_type_direct
nir_deref_array_type_indirect
nir_deref_array_type_wildcard
nir_deref_type
enum nir_deref_type
Enumerator
nir_deref_type_var
nir_deref_type_array
nir_deref_type_struct
nir_instr_type
enum nir_instr_type
Enumerator
nir_instr_type_alu
nir_instr_type_call
nir_instr_type_tex
nir_instr_type_intrinsic
nir_instr_type_load_const
nir_instr_type_jump
nir_instr_type_ssa_undef
nir_instr_type_phi
nir_instr_type_parallel_copy
nir_intrinsic_index_flag
enum nir_intrinsic_index_flag
Enumerator
NIR_INTRINSIC_BASE
Generally instructions that take a offset src argument, can encode a constant 'base' value which is added to the offset.
NIR_INTRINSIC_WRMASK
For store instructions, a writemask for the store.
NIR_INTRINSIC_STREAM_ID
The stream-id for GS emit_vertex/end_primitive intrinsics.
NIR_INTRINSIC_UCP_ID
The clip-plane id for load_user_clip_plane intrinsic.
NIR_INTRINSIC_RANGE
The amount of data, starting from BASE, that this instruction may access.
This is used to provide bounds if the offset is not constant.
NIR_INTRINSIC_DESC_SET
The Vulkan descriptor set for vulkan_resource_index intrinsic.
NIR_INTRINSIC_BINDING
The Vulkan descriptor set binding for vulkan_resource_index intrinsic.
NIR_INTRINSIC_COMPONENT
Component offset.
NIR_INTRINSIC_INTERP_MODE
Interpolation mode (only meaningful for FS inputs).
NIR_INTRINSIC_NUM_INDEX_FLAGS
nir_intrinsic_op
enum nir_intrinsic_op
Enumerator
INTRINSIC
nir_intrinsic_semantic_flag
enum nir_intrinsic_semantic_flag
Enumerator
NIR_INTRINSIC_CAN_ELIMINATE
whether the intrinsic can be safely eliminated if none of its output value is not being used.
NIR_INTRINSIC_CAN_REORDER
Whether the intrinsic can be reordered with respect to any other intrinsic, i.e.
whether the only reordering dependencies of the intrinsic are due to the register reads/writes.
nir_jump_type
enum nir_jump_type
Enumerator
nir_jump_return
nir_jump_break
nir_jump_continue
nir_lower_doubles_options
enum nir_lower_doubles_options
Enumerator
nir_lower_drcp
nir_lower_dsqrt
nir_lower_drsq
nir_lower_dtrunc
nir_lower_dfloor
nir_lower_dceil
nir_lower_dfract
nir_lower_dround_even
nir_lower_dmod
nir_lower_int64_options
enum nir_lower_int64_options
Enumerator
nir_lower_imul64
nir_lower_isign64
nir_lower_divmod64
Lower all int64 modulus and division opcodes.
nir_lower_io_options
enum nir_lower_io_options
Enumerator
nir_lower_io_force_sample_interpolation
nir_metadata
enum nir_metadata
Various bits of metadata that can may be created or required by optimization and analysis passes.
Enumerator
nir_metadata_none
nir_metadata_block_index
nir_metadata_dominance
nir_metadata_live_ssa_defs
nir_metadata_not_properly_reset
nir_metadata_loop_analysis
nir_op_algebraic_property
enum nir_op_algebraic_property
Enumerator
NIR_OP_IS_COMMUTATIVE
NIR_OP_IS_ASSOCIATIVE
nir_parameter_type
enum nir_parameter_type
Enumerator
nir_parameter_in
nir_parameter_out
nir_parameter_inout
nir_tex_src_type
enum nir_tex_src_type
texture information
This gives semantic information about textures which is useful to the frontend, the backend, and lowering passes, but not the optimizer.
Enumerator
nir_tex_src_coord
nir_tex_src_projector
nir_tex_src_comparator
nir_tex_src_offset
nir_tex_src_bias
nir_tex_src_lod
nir_tex_src_ms_index
nir_tex_src_ms_mcs
nir_tex_src_ddx
nir_tex_src_ddy
nir_tex_src_texture_offset
nir_tex_src_sampler_offset
nir_tex_src_plane
nir_num_tex_src_types
nir_texop
enum nir_texop
Enumerator
nir_texop_tex
Regular texture look-up.
nir_texop_txb
Texture look-up with LOD bias.
nir_texop_txl
Texture look-up with explicit LOD.
nir_texop_txd
Texture look-up with partial derivatvies.
nir_texop_txf
Texel fetch with explicit LOD.
nir_texop_txf_ms
Multisample texture fetch.
nir_texop_txf_ms_mcs
Multisample compression value fetch.
nir_texop_txs
Texture size.
nir_texop_lod
Texture lod query.
nir_texop_tg4
Texture gather.
nir_texop_query_levels
Texture levels query.
nir_texop_texture_samples
Texture samples query.
nir_texop_samples_identical
Query whether all samples are definitely identical.
nir_variable_mode
enum nir_variable_mode
Enumerator
nir_var_shader_in
nir_var_shader_out
nir_var_global
nir_var_local
nir_var_uniform
nir_var_shader_storage
nir_var_system_value
nir_var_param
nir_var_shared
nir_var_all
Function Documentation
nir_after_block()
static nir_cursor nir_after_block (nir_block * block) inline static
References nir_instr::block, nir_cursor::block, nir_cursor_after_block, and nir_cursor::option.
Referenced by complex_unroll(), get_complex_unroll_insert_location(), lower_returns_in_block(), move_cf_list_into_loop_term(), nir_after_block_before_jump(), nir_after_cf_node(), nir_after_cf_node_and_phis(), nir_after_phis(), nir_before_cf_node(), nir_instr_insert_after_block(), opt_peel_loop_initial_if(), and simple_unroll().
nir_after_block_before_jump()
static nir_cursor nir_after_block_before_jump (nir_block * block) inline static
References nir_after_block(), nir_before_instr(), nir_block_last_instr(), nir_instr_type_jump, and nir_instr::type.
Referenced by add_parallel_copy_to_end_of_block(), append_set_vertex_count(), emit_output_copies_impl(), opt_peel_loop_initial_if(), and place_phi_read().
nir_after_cf_list()
static nir_cursor nir_after_cf_list (struct exec_list * cf_list) inline static
References exec_node_data, nir_after_cf_node(), and nir_instr_insert().
Referenced by lower_clip_vs(), lower_returns_in_block(), lower_returns_in_if(), nir_builder_init_simple_shader(), nir_cf_list_extract(), nir_cf_node_insert_end(), nir_instr_insert_after_cf_list(), opt_peel_loop_initial_if(), and predicate_following().
nir_after_cf_node()
static nir_cursor nir_after_cf_node (nir_cf_node * node) inline static
References nir_after_block(), nir_before_block(), nir_cf_node_next(), and nir_cf_node::type.
Referenced by complex_unroll(), lower_returns_in_if(), nir_after_cf_list(), nir_cf_node_insert_after(), nir_cf_node_remove(), nir_instr_insert_after_cf(), nir_pop_if(), nir_pop_loop(), opt_constant_if(), predicate_following(), remove_after_cf_node(), and simple_unroll().
nir_after_cf_node_and_phis()
static nir_cursor nir_after_cf_node_and_phis (nir_cf_node * node) inline static
References nir_after_block(), nir_after_phis(), nir_cf_node_next(), and nir_cf_node::type.
Referenced by predicate_following().
nir_after_instr()
static nir_cursor nir_after_instr (nir_instr * instr) inline static
References instr, nir_cursor::instr, nir_cursor_after_instr, and nir_cursor::option.
Referenced by convert_block(), instr_remove_cursor(), linearize_srgb_result(), load_from_ssa_entry_value(), lower_load_sample_pos(), lower_y_u_v_external(), lower_y_uv_external(), lower_yx_xuxv_external(), nir_builder_instr_insert(), nir_instr_insert_after(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), rewrite_alu_instr(), swizzle_result(), and update_fragcoord().
nir_after_phis()
static nir_cursor nir_after_phis (nir_block * block) inline static
References nir_after_block(), nir_before_instr(), nir_foreach_instr, nir_instr_type_phi, and nir_instr::type.
Referenced by nir_after_cf_node_and_phis(), and remove_phis_block().
nir_alu_dest_copy()
void nir_alu_dest_copy (nir_alu_dest * dest, const nir_alu_dest * src, nir_alu_instr * instr)
References nir_alu_dest::dest, nir_alu_instr::instr, nir_dest_copy(), nir_alu_dest::saturate, and nir_alu_dest::write_mask.
Referenced by insert_mov().
nir_alu_instr_channel_used()
static bool nir_alu_instr_channel_used (nir_alu_instr * instr, unsigned src, unsigned channel) inline static
References nir_alu_instr::dest, nir_op_info::input_sizes, nir_alu_instr::op, and nir_alu_dest::write_mask.
Referenced by copy_prop_alu_src(), move_vec_src_uses_to_dest_block(), nir_lower_to_source_mods_block(), nir_ssa_def_components_read(), and print_alu_src().
nir_alu_instr_create()
nir_alu_instr* nir_alu_instr_create (nir_shader * shader, nir_op op)
creates an instruction with default swizzle/writemask/etc.
with NULL registers
References alu_dest_init(), alu_src_init(), nir_alu_instr::dest, nir_alu_instr::instr, instr, instr_init(), nir_instr_type_alu, nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, and nir_alu_instr::src.
Referenced by clone_alu(), construct_value(), emit_copy(), get_deref_reg_src(), insert_mov(), lower_alu_instr_scalar(), lower_instr(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_reduction(), nir_build_alu(), nir_fmov_alu(), nir_function_impl_add_variable(), nir_imov_alu(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_opt_peephole_select_block(), nir_replace_instr(), place_phi_read(), rename_variables(), and rewrite_alu_instr().
nir_alu_src_copy()
void nir_alu_src_copy (nir_alu_src * dest, const nir_alu_src * src, nir_alu_instr * instr)
References nir_alu_src::abs, nir_alu_instr::instr, nir_alu_src::negate, nir_src_copy(), nir_alu_src::src, and nir_alu_src::swizzle.
Referenced by construct_value(), insert_mov(), lower_alu_instr_scalar(), lower_reduction(), and opt_undef_csel().
nir_alu_srcs_equal()
bool nir_alu_srcs_equal (const nir_alu_instr * alu1, const nir_alu_instr * alu2, unsigned src1, unsigned src2)
References nir_alu_src::abs, nir_alu_src::negate, nir_srcs_equal(), nir_ssa_alu_instr_src_components(), nir_alu_src::src, nir_alu_instr::src, and nir_alu_src::swizzle.
Referenced by matching_mov(), nir_instrs_equal(), and nir_ssa_alu_instr_src_components().
nir_alu_type_get_base_type()
static unsigned nir_alu_type_get_base_type (nir_alu_type type) inline static
References NIR_ALU_TYPE_BASE_TYPE_MASK.
Referenced by calculate_iterations(), linearize_srgb_result(), nir_lower_to_source_mods_block(), sample_plane(), and src_is_type().
nir_alu_type_get_type_size()
static unsigned nir_alu_type_get_type_size (nir_alu_type type) inline static
References NIR_ALU_TYPE_SIZE_MASK.
Referenced by build_bitsize_tree(), constant_fold_alu_instr(), and nir_build_alu().
nir_assign_var_locations()
void nir_assign_var_locations (struct exec_list * var_list, unsigned * size, int(*)(const struct glsl_type *) type_size)
References nir_foreach_variable, nir_var_shader_storage, nir_var_uniform, and lower_io_state::type_size.
nir_before_block()
static nir_cursor nir_before_block (nir_block * block) inline static
References nir_instr::block, nir_cursor::block, nir_cursor_before_block, and nir_cursor::option.
Referenced by complex_unroll(), emit_input_copies_impl(), emit_output_copies_impl(), instr_remove_cursor(), nir_after_cf_node(), nir_before_cf_node(), nir_instr_insert_before_block(), nir_phi_builder_finish(), opt_peel_loop_initial_if(), and simple_unroll().
nir_before_cf_list()
static nir_cursor nir_before_cf_list (struct exec_list * cf_list) inline static
References exec_node_data, and nir_before_cf_node().
Referenced by lower_bitmap_impl(), lower_clip_fs(), lower_const_initializer(), lower_impl(), lower_returns_in_block(), nir_cf_list_extract(), nir_cf_node_insert_begin(), nir_instr_insert_before_cf_list(), nir_lower_gs_intrinsics(), nir_phi_builder_value_get_block_def(), nir_push_else(), nir_push_if(), nir_push_loop(), nir_ssa_undef(), opt_peel_loop_initial_if(), and predicate_following().
nir_before_cf_node()
static nir_cursor nir_before_cf_node (nir_cf_node * node) inline static
References nir_after_block(), nir_before_block(), nir_cf_node_prev(), and nir_cf_node::type.
Referenced by complex_unroll(), get_complex_unroll_insert_location(), lower_returns_in_block(), nir_before_cf_list(), nir_cf_node_insert_before(), nir_cf_node_remove(), nir_instr_insert_before_cf(), nir_opt_conditional_discard_block(), opt_peel_loop_initial_if(), and simple_unroll().
nir_before_instr()
static nir_cursor nir_before_instr (nir_instr * instr) inline static
References instr, nir_cursor::instr, nir_cursor_before_instr, and nir_cursor::option.
Referenced by convert_instr(), emit_output_copies_impl(), emit_wpos_adjustment(), get_texture_size(), inline_functions_block(), lower_64bit_pack_impl(), lower_alu_instr_scalar(), lower_color(), lower_doubles_instr(), lower_fddy(), lower_indirect_block(), lower_int64_impl(), lower_interp_var_at_offset(), lower_intrinsic(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_offset(), lower_sampler(), lower_store_output_to_scalar(), lower_texcoord(), nir_after_block_before_jump(), nir_after_phis(), nir_instr_insert_before(), nir_lower_io_block(), nir_lower_tes_patch_vertices(), nir_lower_two_sided_color_block(), normalize_cubemap_coords_block(), opt_undef_vecN(), project_src(), rename_variables(), resolve_parallel_copy(), rewrite_emit_vertex(), rewrite_end_primitive(), and saturate_src().
nir_block_cf_tree_next()
nir_block* nir_block_cf_tree_next (nir_block * block)
References nir_block::cf_node, nir_cf_node_cf_tree_first(), nir_cf_node_next(), nir_if_first_else_block(), nir_if_last_else_block(), nir_if_last_then_block(), nir_cf_node::parent, and nir_cf_node::type.
Referenced by nir_cf_node_cf_tree_next().
nir_block_cf_tree_prev()
nir_block* nir_block_cf_tree_prev (nir_block * block)
References nir_block::cf_node, nir_cf_node_cf_tree_last(), nir_cf_node_prev(), nir_if_first_else_block(), nir_if_first_then_block(), nir_if_last_then_block(), nir_cf_node::parent, and nir_cf_node::type.
nir_block_create()
nir_block* nir_block_create (nir_shader * shader)
References cf_init(), nir_block::cf_node, nir_block::dom_frontier, nir_block::imm_dom, nir_block::instr_list, nir_block::predecessors, and nir_block::successors.
Referenced by nir_cf_list_clone(), nir_function_impl_add_variable(), nir_function_impl_create_bare(), nir_if_create(), nir_loop_create(), split_block_beginning(), and split_block_end().
nir_block_dominates()
bool nir_block_dominates (nir_block * parent, nir_block * child)
Returns true if parent dominates child.
References nir_block::cf_node, nir_block::dom_post_index, nir_block::dom_pre_index, nir_cf_node_get_function(), nir_metadata_dominance, and nir_function_impl::valid_metadata.
Referenced by repair_ssa_def(), ssa_def_dominates(), and ssa_def_dominates_instr().
nir_block_first_instr()
static nir_instr* nir_block_first_instr (nir_block * block) inline static
References exec_node_data, nir_block::instr_list, and nir_instr::node.
Referenced by add_parallel_copy_to_end_of_block(), loop_is_dead(), lower_trivial_continues_block(), nir_opt_conditional_discard_block(), and resolve_parallel_copies_block().
nir_block_get_following_if()
nir_if* nir_block_get_following_if (nir_block * block)
References nir_block::cf_node, nir_cf_node_is_last(), nir_cf_node_next(), nir_cf_node::node, and nir_cf_node::type.
Referenced by dead_cf_block(), init_block(), move_comparisons(), nir_copy_prop_impl(), nir_live_ssa_defs_impl(), and nir_lower_regs_to_ssa_impl().
nir_block_get_following_loop()
nir_loop* nir_block_get_following_loop (nir_block * block)
References nir_block::cf_node, nir_cf_node_is_last(), nir_cf_node_next(), nir_cf_node::node, and nir_cf_node::type.
Referenced by dead_cf_block().
nir_block_last_instr()
static nir_instr* nir_block_last_instr (nir_block * block) inline static
References exec_node_data, nir_block::instr_list, and nir_instr::node.
Referenced by block_ends_in_jump(), complex_unroll(), contains_other_jump(), ends_in_break(), ends_in_jump(), gcm_place_instr(), get_parallel_copy_at_end_of_block(), loop_prepare_for_unroll(), lower_phis_to_scalar_block(), lower_returns_in_block(), lower_trivial_continues_block(), move_cf_list_into_loop_term(), nir_after_block_before_jump(), nir_handle_add_jump(), nir_instr_insert(), nir_is_trivial_loop_if(), opt_constant_if(), opt_peel_loop_initial_if(), and simple_unroll().
nir_calc_dominance()
void nir_calc_dominance (nir_shader * shader)
References nir_calc_dominance_impl(), and nir_foreach_function.
nir_calc_dominance_impl()
void nir_calc_dominance_impl (nir_function_impl * impl)
References calc_dfs_indicies(), calc_dom_children(), calc_dom_frontier(), calc_dominance(), nir_block::imm_dom, init_block(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_require(), nir_start_block(), and nir_function_impl::valid_metadata.
Referenced by nir_calc_dominance(), and nir_metadata_require().
nir_call_instr_create()
nir_call_instr* nir_call_instr_create (nir_shader * shader, nir_function * callee)
References nir_call_instr::callee, nir_call_instr::instr, instr, instr_init(), nir_instr_type_call, nir_call_instr::num_params, nir_function::num_params, nir_call_instr::params, and nir_call_instr::return_deref.
Referenced by clone_call(), and nir_function_impl_add_variable().
nir_cf_node_cf_tree_first()
nir_block* nir_cf_node_cf_tree_first (nir_cf_node * node)
References nir_if_first_then_block(), nir_loop_first_block(), nir_start_block(), and nir_cf_node::type.
Referenced by nir_block_cf_tree_next().
nir_cf_node_cf_tree_last()
nir_block* nir_cf_node_cf_tree_last (nir_cf_node * node)
References nir_if_last_else_block(), nir_impl_last_block(), nir_loop_last_block(), and nir_cf_node::type.
Referenced by nir_block_cf_tree_prev().
nir_cf_node_cf_tree_next()
nir_block* nir_cf_node_cf_tree_next (nir_cf_node * node)
References nir_block_cf_tree_next(), nir_cf_node_next(), and nir_cf_node::type.
nir_cf_node_get_function()
nir_function_impl* nir_cf_node_get_function (nir_cf_node * node)
References nir_cf_node::parent, and nir_cf_node::type.
Referenced by add_ssa_def_cb(), global_to_local(), insert_phi_undef(), loop_is_dead(), lower_doubles_instr(), lower_load_const_instr_scalar(), nir_block_dominates(), nir_cf_extract(), nir_convert_loop_to_lcssa(), nir_dominance_lca(), nir_function_impl_add_variable(), nir_handle_add_jump(), nir_handle_remove_jump(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_ssa_def_init(), and process_loops().
nir_cf_node_is_first()
static bool nir_cf_node_is_first (const nir_cf_node * node) inline static
References nir_cf_node::node, and exec_node::prev.
Referenced by nir_opt_conditional_discard_block(), and nir_opt_peephole_select_block().
nir_cf_node_is_last()
static bool nir_cf_node_is_last (const nir_cf_node * node) inline static
References cf_node, exec_node::next, NIR_DEFINE_CAST, nir_cf_node::node, and nir_instr::type.
Referenced by nir_block_get_following_if(), nir_block_get_following_loop(), and remove_after_cf_node().
nir_cf_node_next()
static nir_cf_node* nir_cf_node_next (nir_cf_node * node) inline static
References exec_node_data, exec_node::next, and nir_cf_node::node.
Referenced by block_add_normal_succs(), convert_loop_exit_for_ssa(), dead_cf_list(), is_if_use_inside_loop(), is_use_inside_loop(), loop_is_dead(), loop_prepare_for_unroll(), lower_returns_in_block(), nir_after_cf_node(), nir_after_cf_node_and_phis(), nir_block_cf_tree_next(), nir_block_get_following_if(), nir_block_get_following_loop(), nir_cf_extract(), nir_cf_node_cf_tree_next(), nir_cf_reinsert(), nir_handle_add_jump(), nir_opt_conditional_discard_block(), opt_constant_if(), opt_peel_loop_initial_if(), and remove_after_cf_node().
nir_cf_node_prev()
static nir_cf_node* nir_cf_node_prev (nir_cf_node * node) inline static
References exec_node_data, nir_cf_node::node, and exec_node::prev.
Referenced by complex_unroll(), gcm_schedule_late_def(), is_if_use_inside_loop(), is_use_inside_loop(), loop_is_dead(), lower_trivial_continues_block(), nir_before_cf_node(), nir_block_cf_tree_prev(), nir_cf_reinsert(), nir_if_phi(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), opt_peel_loop_initial_if(), reduce_cursor(), and rewrite_if_condition().
nir_constant_clone()
nir_constant* nir_constant_clone (const nir_constant * c, nir_variable * var)
References nir_constant::elements, nir_constant::num_elements, and nir_constant::values.
Referenced by nir_variable_clone().
nir_convert_from_ssa()
bool nir_convert_from_ssa (nir_shader * shader, bool phi_webs_only)
References nir_convert_from_ssa_impl(), nir_foreach_function, and from_ssa_state::progress.
nir_convert_loop_to_lcssa()
void nir_convert_loop_to_lcssa (nir_loop * loop)
References nir_loop::body, nir_loop::cf_node, convert_to_lcssa(), foreach_list_typed, nir_function_impl::function, lcssa_state::loop, nir_cf_node_get_function(), nir_metadata_block_index, nir_metadata_require(), lcssa_state::shader, and nir_function::shader.
Referenced by loop_prepare_for_unroll(), and opt_peel_loop_initial_if().
nir_copy_prop()
bool nir_copy_prop (nir_shader * shader)
References nir_copy_prop_impl(), nir_foreach_function, and copy_prop_var_state::progress.
nir_cursor_current_block()
static nir_block* nir_cursor_current_block (nir_cursor cursor) inline static
References nir_instr::block, nir_cursor::block, nir_cursor::instr, nir_cursor_after_instr, nir_cursor_before_instr, nir_cursors_equal(), and nir_cursor::option.
Referenced by nir_builder_is_inside_cf(), nir_if_phi(), nir_pop_if(), nir_pop_loop(), and nir_push_else().
nir_cursors_equal()
bool nir_cursors_equal (nir_cursor a, nir_cursor b)
References nir_cursor::block, nir_cursor::option, and reduce_cursor().
Referenced by nir_cf_extract(), nir_cursor_current_block(), and predicate_following().
NIR_DEFINE_CAST() [1/9]
NIR_DEFINE_CAST (nir_deref_as_var , nir_deref , nir_deref_var , deref , deref_type , nir_deref_type_var)
NIR_DEFINE_CAST() [2/9]
nir_deref_type_array NIR_DEFINE_CAST (nir_deref_as_struct , nir_deref , nir_deref_struct , deref , deref_type , nir_deref_type_struct)
References deref.
NIR_DEFINE_CAST() [3/9]
NIR_DEFINE_CAST (nir_instr_as_alu , nir_instr , nir_alu_instr , instr , type , nir_instr_type_alu)
NIR_DEFINE_CAST() [4/9]
nir_instr_type_call NIR_DEFINE_CAST (nir_instr_as_jump , nir_instr , nir_jump_instr , instr , type , nir_instr_type_jump)
NIR_DEFINE_CAST() [5/9]
nir_instr_type_call nir_instr_type_tex NIR_DEFINE_CAST (nir_instr_as_intrinsic , nir_instr , nir_intrinsic_instr , instr , type , nir_instr_type_intrinsic)
NIR_DEFINE_CAST() [6/9]
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const NIR_DEFINE_CAST (nir_instr_as_ssa_undef , nir_instr , nir_ssa_undef_instr , instr , type , nir_instr_type_ssa_undef)
NIR_DEFINE_CAST() [7/9]
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const nir_instr_type_phi NIR_DEFINE_CAST (nir_instr_as_parallel_copy , nir_instr , nir_parallel_copy_instr , instr , type , nir_instr_type_parallel_copy)
NIR_DEFINE_CAST() [8/9]
NIR_DEFINE_CAST (nir_cf_node_as_block , nir_cf_node , nir_block , cf_node , type , nir_cf_node_block)
NIR_DEFINE_CAST() [9/9]
nir_cf_node_if NIR_DEFINE_CAST (nir_cf_node_as_loop , nir_cf_node , nir_loop , cf_node , type , nir_cf_node_loop)
nir_deref_array_create()
nir_deref_array* nir_deref_array_create (void * mem_ctx)
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref, deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_array::indirect, nir_deref_array_type_direct, nir_deref_type_array, and src_init().
Referenced by clone_deref_array(), deref_array_clone(), nir_function_impl_add_variable(), specialize_wildcards(), and split_var_copy_instr().
nir_deref_clone()
nir_deref* nir_deref_clone (const nir_deref * deref, void * mem_ctx)
References nir_deref_var::deref, nir_deref_array::deref, nir_deref_struct::deref, deref_array_clone(), deref_struct_clone(), nir_deref::deref_type, nir_deref_type_array, nir_deref_type_struct, nir_deref_type_var, and nir_deref_var_clone().
Referenced by deref_array_clone(), deref_struct_clone(), load_from_deref_entry_value(), and nir_deref_var_clone().
nir_deref_foreach_leaf()
bool nir_deref_foreach_leaf (nir_deref_var * deref, nir_deref_foreach_leaf_cb cb, void * state)
This function iterates over all of the possible derefs that can be created with the given deref as the head.
It then calls the provided callback with a full deref for each one.
The deref passed to the callback will be allocated on the stack. You will need to make a copy if you want it to hang around.
References nir_deref_var::deref, deref, and deref_foreach_leaf_copy_recur().
Referenced by lower_const_initializer().
nir_deref_get_const_initializer_load()
nir_load_const_instr* nir_deref_get_const_initializer_load (nir_shader * shader, nir_deref_var * deref)
References nir_deref_array::base_offset, nir_deref::child, nir_variable::constant_initializer, nir_deref_var::deref, nir_deref_array::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_constant::elements, nir_deref_array_type_direct, nir_deref_type_array, nir_deref_type_struct, nir_load_const_instr_create(), nir_deref::type, nir_load_const_instr::value, nir_constant::values, and nir_deref_var::var.
Referenced by deref_apply_constant_initializer().
nir_deref_struct_create()
nir_deref_struct* nir_deref_struct_create (void * mem_ctx, unsigned field_index)
References nir_deref::child, nir_deref_struct::deref, deref, nir_deref::deref_type, nir_deref_struct::index, and nir_deref_type_struct.
Referenced by clone_deref_struct(), deref_struct_clone(), nir_function_impl_add_variable(), specialize_wildcards(), and split_var_copy_instr().
nir_deref_var_clone()
nir_deref_var* nir_deref_var_clone (const nir_deref_var * deref, void * mem_ctx)
References nir_deref::child, nir_deref_var::deref, nir_deref_clone(), nir_deref_var_create(), ret(), nir_deref::type, and nir_deref_var::var.
Referenced by convert_deref_to_param_deref(), emit_copy_load_store(), emit_load_store(), get_texture_size(), load_from_deref_entry_value(), nir_copy_deref_var(), nir_deref_clone(), nir_load_deref_var(), nir_store_deref_var(), replace_gradient_with_lod(), sample_plane(), and split_var_copy_instr().
nir_deref_var_create()
nir_deref_var* nir_deref_var_create (void * mem_ctx, nir_variable * var)
References nir_deref::child, nir_deref_var::deref, deref, nir_deref::deref_type, nir_deref_type_var, nir_variable::type, nir_deref::type, and nir_deref_var::var.
Referenced by clone_deref_var(), emit_copies(), inline_functions_block(), lower_io_types_block(), nir_copy_var(), nir_deref_var_clone(), nir_function_impl_add_variable(), nir_load_var(), nir_store_var(), and specialize_wildcards().
nir_dest_bit_size()
static unsigned nir_dest_bit_size (nir_dest dest) inline static
References nir_register::bit_size, nir_ssa_def::bit_size, instr, nir_dest::is_ssa, nir_dest_copy(), nir_src_copy(), nir_reg_dest::reg, nir_dest::reg, and nir_dest::ssa.
Referenced by opt_undef_vecN().
nir_dest_copy()
void nir_dest_copy (nir_dest * dest, const nir_dest * src, nir_instr * instr)
References nir_reg_dest::base_offset, nir_reg_dest::indirect, nir_dest::is_ssa, nir_src_copy(), nir_reg_dest::reg, and nir_dest::reg.
Referenced by lower_instr(), lower_locals_to_regs_block(), nir_alu_dest_copy(), nir_dest_bit_size(), nir_instr_rewrite_dest(), and nir_lower_io_block().
nir_dest_for_reg()
static nir_dest nir_dest_for_reg (nir_register * reg) inline static
References NIR_DEST_INIT, nir_reg_dest::reg, and nir_dest::reg.
Referenced by dest_replace_ssa_with_reg(), emit_copy(), lower_vec_to_movs_block(), nir_lower_ssa_defs_to_regs_block(), place_phi_read(), and rewrite_ssa_def().
nir_dest_init()
static nir_dest nir_dest_init (void) inline static
nir_dominance_lca()
nir_block* nir_dominance_lca (nir_block * b1, nir_block * b2)
Computes the least common anscestor of two blocks.
If one of the blocks is null, the other block is returned.
References nir_block::cf_node, intersect(), nir_cf_node_get_function(), nir_metadata_dominance, and nir_function_impl::valid_metadata.
Referenced by gcm_schedule_late_def().
nir_dump_cfg()
void nir_dump_cfg (nir_shader * shader, FILE * fp)
References nir_dump_cfg_impl(), and nir_foreach_function.
nir_dump_cfg_impl()
void nir_dump_cfg_impl (nir_function_impl * impl, FILE * fp)
References nir_function_impl::function, nir_function::name, and nir_foreach_block.
Referenced by nir_dump_cfg().
nir_dump_dom_frontier()
void nir_dump_dom_frontier (nir_shader * shader, FILE * fp)
References nir_dump_dom_frontier_impl(), and nir_foreach_function.
nir_dump_dom_frontier_impl()
void nir_dump_dom_frontier_impl (nir_function_impl * impl, FILE * fp)
References nir_block::index, and nir_foreach_block.
Referenced by nir_dump_dom_frontier().
nir_dump_dom_tree()
void nir_dump_dom_tree (nir_shader * shader, FILE * fp)
References nir_dump_dom_tree_impl(), and nir_foreach_function.
nir_dump_dom_tree_impl()
void nir_dump_dom_tree_impl (nir_function_impl * impl, FILE * fp)
References nir_function_impl::function, nir_function::name, and nir_foreach_block.
Referenced by nir_dump_dom_tree().
nir_foreach_dest()
bool nir_foreach_dest (nir_instr * instr, nir_foreach_dest_cb cb, void * state)
References nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, nir_instr::type, visit_alu_dest(), visit_intrinsic_dest(), visit_parallel_copy_dest(), visit_phi_dest(), and visit_texture_dest().
Referenced by add_defs_uses(), instr_can_rewrite(), nir_foreach_src(), nir_foreach_ssa_def(), nir_lower_regs_to_ssa_impl(), nir_lower_ssa_defs_to_regs_block(), remove_defs_uses(), and sweep_block().
nir_foreach_src()
bool nir_foreach_src (nir_instr * instr, nir_foreach_src_cb cb, void * state)
References foreach_ssa_def_state::cb, visit_dest_indirect_state::cb, nir_foreach_dest(), nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, visit_dest_indirect_state::state, nir_instr::type, visit_alu_src(), visit_dest_indirect(), visit_intrinsic_src(), visit_parallel_copy_src(), visit_phi_src(), and visit_tex_src().
Referenced by add_defs_uses(), gcm_schedule_early_instr(), instr_can_rewrite(), move_comparisons(), nir_live_ssa_defs_impl(), nir_lower_regs_to_ssa_impl(), nir_opt_dce_impl(), propagate_invariant_instr(), remove_defs_uses(), rewrite_alu_instr(), search_for_use_after_instr(), and sweep_block().
nir_foreach_ssa_def()
bool nir_foreach_ssa_def (nir_instr * instr, nir_foreach_ssa_def_cb cb, void * state)
References foreach_ssa_def_state::cb, nir_foreach_dest(), nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, nir_ssa_def_visitor(), and nir_instr::type.
Referenced by add_defs_uses(), cleanup_cf_node(), convert_to_lcssa(), gcm_place_instr(), gcm_schedule_late_instr(), get_loop_info(), init_loop_block(), loop_is_dead(), nir_index_ssa_defs(), nir_live_ssa_defs_impl(), nir_repair_ssa_impl(), and resolve_registers_block().
nir_function_create()
nir_function* nir_function_create (nir_shader * shader, const char * name)
creates a function and adds it to the shader's list of functions
References nir_shader::functions, nir_function::impl, nir_function::name, nir_function::node, nir_function::num_params, nir_function::params, nir_function::return_type, and nir_function::shader.
Referenced by clone_function(), nir_builder_init_simple_shader(), and nir_function_impl_add_variable().
nir_function_impl_add_variable()
static void nir_function_impl_add_variable (nir_function_impl * impl, nir_variable * var) inline static
References nir_variable::data, nir_function_impl::locals, mem_ctx, nir_variable::nir_variable_data::mode, nir_alu_instr_create(), nir_block_create(), nir_call_instr_create(), nir_cf_node_get_function(), nir_deref_array_create(), nir_deref_struct_create(), nir_deref_var_create(), nir_function_create(), nir_function_impl_create(), nir_function_impl_create_bare(), nir_if_create(), nir_intrinsic_instr_create(), nir_jump_instr_create(), nir_load_const_instr_create(), nir_local_variable_create(), nir_loop_create(), nir_metadata_preserve(), nir_metadata_require(), nir_parallel_copy_instr_create(), nir_phi_instr_create(), nir_ssa_undef_instr_create(), nir_tex_instr_create(), nir_var_local, nir_variable_create(), nir_variable::node, nir_instr::node, and nir_instr::type.
Referenced by nir_local_variable_create().
nir_function_impl_clone()
nir_function_impl* nir_function_impl_clone (const nir_function_impl * fi)
References clone_function_impl(), free_clone_state(), nir_function_impl::function, init_clone_state(), clone_state::ns, and nir_function::shader.
Referenced by inline_functions_block().
nir_function_impl_create()
nir_function_impl* nir_function_impl_create (nir_function * func)
References nir_variable::data, nir_function_impl::function, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_function_impl_create_bare(), nir_var_param, nir_function_impl::num_params, nir_function_impl::params, nir_function_impl::return_var, and nir_variable::type.
Referenced by nir_builder_init_simple_shader(), and nir_function_impl_add_variable().
nir_function_impl_create_bare()
nir_function_impl* nir_function_impl_create_bare (nir_shader * shader)
creates a function_impl that isn't tied to any particular function
References nir_function_impl::body, cf_init(), nir_block::cf_node, nir_function_impl::cf_node, nir_function_impl::end_block, nir_function_impl::function, nir_function_impl::locals, nir_block_create(), nir_metadata_none, nir_cf_node::node, nir_function_impl::num_params, nir_function_impl::params, nir_cf_node::parent, nir_block::predecessors, nir_function_impl::reg_alloc, nir_function_impl::registers, nir_function_impl::return_var, nir_function_impl::ssa_alloc, nir_block::successors, and nir_function_impl::valid_metadata.
Referenced by clone_function_impl(), nir_function_impl_add_variable(), and nir_function_impl_create().
nir_get_io_offset_src()
nir_src* nir_get_io_offset_src (nir_intrinsic_instr * instr)
Return the offset soruce for a load/store intrinsic.
References nir_intrinsic_instr::intrinsic, and nir_intrinsic_instr::src.
nir_get_io_vertex_index_src()
nir_src* nir_get_io_vertex_index_src (nir_intrinsic_instr * instr)
Return the vertex index source for a load/store per_vertex intrinsic.
References nir_intrinsic_instr::intrinsic, and nir_intrinsic_instr::src.
nir_get_nir_type_for_glsl_base_type()
static nir_alu_type nir_get_nir_type_for_glsl_base_type (enum glsl_base_type base_type) inline static
References nir_type_bool32, nir_type_float32, nir_type_float64, nir_type_int32, nir_type_int64, nir_type_uint32, and nir_type_uint64.
Referenced by nir_get_nir_type_for_glsl_type().
nir_get_nir_type_for_glsl_type()
static nir_alu_type nir_get_nir_type_for_glsl_type (const struct glsl_type * type) inline static
References nir_get_nir_type_for_glsl_base_type(), and nir_type_conversion_op().
nir_global_reg_create()
nir_register* nir_global_reg_create (nir_shader * shader)
creates a register, including assigning it an index and adding it to the list
References nir_register::index, nir_register::is_global, nir_shader::reg_alloc, reg_create(), and nir_shader::registers.
nir_gs_count_vertices()
int nir_gs_count_vertices (const nir_shader * shader)
If a geometry shader emits a constant number of vertices, return the number of vertices.
Otherwise, return -1 (unknown).
This only works if you've used nir_lower_gs_intrinsics() to do vertex counting at the NIR level.
References as_set_vertex_count(), nir_const_value::i32, instr, nir_foreach_function, nir_foreach_instr_reverse, nir_src_as_const_value(), and nir_intrinsic_instr::src.
nir_if_create()
nir_if* nir_if_create (nir_shader * shader)
References cf_init(), nir_block::cf_node, nir_if::cf_node, nir_if::condition, nir_if::else_list, nir_block_create(), nir_cf_node::node, nir_cf_node::parent, src_init(), and nir_if::then_list.
Referenced by clone_if(), nir_function_impl_add_variable(), nir_push_if(), and predicate_following().
nir_if_first_else_block()
static nir_block* nir_if_first_else_block (nir_if * if_stmt) inline static
References nir_if::else_list, exec_node_data, and nir_instr::node.
Referenced by block_add_normal_succs(), get_first_blocks_in_terminator(), link_block_to_non_block(), nir_block_cf_tree_next(), nir_block_cf_tree_prev(), nir_opt_conditional_discard_block(), and nir_opt_peephole_select_block().
nir_if_first_then_block()
nir_cf_node_if static nir_cf_node_function nir_block* nir_if_first_then_block (nir_if * if_stmt) inline static
References exec_node_data, and nir_instr::node.
Referenced by block_add_normal_succs(), get_first_blocks_in_terminator(), link_block_to_non_block(), nir_block_cf_tree_prev(), nir_cf_node_cf_tree_first(), nir_opt_conditional_discard_block(), and nir_opt_peephole_select_block().
nir_if_last_else_block()
static nir_block* nir_if_last_else_block (nir_if * if_stmt) inline static
References nir_if::else_list, exec_node_data, and nir_instr::node.
Referenced by find_loop_terminators(), get_complex_unroll_insert_location(), link_non_block_to_block(), lower_trivial_continues_block(), nir_block_cf_tree_next(), nir_cf_node_cf_tree_last(), nir_if_phi(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), and opt_constant_if().
nir_if_last_then_block()
static nir_block* nir_if_last_then_block (nir_if * if_stmt) inline static
References exec_node_data, nir_instr::node, and nir_if::then_list.
Referenced by find_loop_terminators(), get_complex_unroll_insert_location(), link_non_block_to_block(), lower_trivial_continues_block(), nir_block_cf_tree_next(), nir_block_cf_tree_prev(), nir_if_phi(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), and opt_constant_if().
nir_if_rewrite_condition()
void nir_if_rewrite_condition (nir_if * if_stmt, nir_src new_src)
References nir_if::condition, nir_src::parent_if, src_add_all_uses(), src_is_valid(), and src_remove_all_uses().
Referenced by convert_loop_exit_for_ssa(), copy_prop_src(), nir_ssa_def_rewrite_uses(), nir_ssa_def_rewrite_uses_after(), and rewrite_if_condition().
nir_impl_last_block()
static ATTRIBUTE_RETURNS_NONNULL nir_block* nir_impl_last_block (nir_function_impl * impl) inline static
References nir_function_impl::body, exec_node::prev, and exec_list::tail_sentinel.
Referenced by nir_cf_node_cf_tree_last().
nir_index_blocks()
void nir_index_blocks (nir_function_impl * impl)
References nir_foreach_block, nir_metadata_block_index, nir_function_impl::num_blocks, and nir_function_impl::valid_metadata.
Referenced by nir_metadata_require(), and print_function_impl().
nir_index_global_regs()
void nir_index_global_regs (nir_shader * shader)
References foreach_list_typed, nir_shader::reg_alloc, and nir_shader::registers.
nir_index_instrs()
unsigned nir_index_instrs (nir_function_impl * impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
References instr, nir_foreach_block, and nir_foreach_instr.
Referenced by nir_move_vec_src_uses_to_dest_impl().
nir_index_local_regs()
void nir_index_local_regs (nir_function_impl * impl)
References foreach_list_typed, nir_function_impl::reg_alloc, and nir_function_impl::registers.
Referenced by inline_function_impl(), and nir_lower_regs_to_ssa_impl().
nir_index_ssa_defs()
void nir_index_ssa_defs (nir_function_impl * impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
References index_ssa_def_cb(), instr, nir_foreach_block, nir_foreach_instr, nir_foreach_ssa_def(), and nir_function_impl::ssa_alloc.
Referenced by inline_function_impl(), and nir_loop_analyze_impl().
nir_inline_functions()
bool nir_inline_functions (nir_shader * shader)
References inline_function_impl(), and nir_foreach_function.
nir_instr_insert()
void nir_instr_insert (nir_cursor cursor, nir_instr * instr)
Insert a NIR instruction at the given cursor.
Note: This does not update the cursor.
References add_defs_uses(), nir_instr::block, nir_cursor::block, nir_cursor::instr, nir_block::instr_list, nir_block_last_instr(), nir_cursor_after_block, nir_cursor_after_instr, nir_cursor_before_block, nir_cursor_before_instr, nir_handle_add_jump(), nir_instr_type_jump, nir_instr::node, nir_cursor::option, nir_instr::type, and void.
Referenced by add_parallel_copy_to_end_of_block(), emit_copies(), nir_after_cf_list(), nir_builder_instr_insert(), nir_instr_insert_after(), nir_instr_insert_after_block(), nir_instr_insert_after_cf(), nir_instr_insert_after_cf_list(), nir_instr_insert_before(), nir_instr_insert_before_block(), nir_instr_insert_before_cf(), nir_instr_insert_before_cf_list(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_phi_builder_finish(), nir_phi_builder_value_get_block_def(), nir_ssa_undef(), place_phi_read(), predicate_following(), and rewrite_alu_instr().
nir_instr_insert_after()
static void nir_instr_insert_after (nir_instr * instr, nir_instr * after) inline static
References nir_after_instr(), and nir_instr_insert().
Referenced by isolate_phi_nodes_block(), lower_phis_to_scalar_block(), and split_var_copy_instr().
nir_instr_insert_after_block()
static void nir_instr_insert_after_block (nir_block * block, nir_instr * after) inline static
References nir_after_block(), and nir_instr_insert().
Referenced by clone_block(), clone_phi(), and lower_phis_to_scalar_block().
nir_instr_insert_after_cf()
static void nir_instr_insert_after_cf (nir_cf_node * node, nir_instr * after) inline static
References nir_after_cf_node(), and nir_instr_insert().
nir_instr_insert_after_cf_list()
static void nir_instr_insert_after_cf_list (struct exec_list * list, nir_instr * after) inline static
References nir_after_cf_list(), nir_instr_insert(), and nir_instr_remove().
nir_instr_insert_before()
static void nir_instr_insert_before (nir_instr * instr, nir_instr * before) inline static
References nir_before_instr(), and nir_instr_insert().
Referenced by constant_fold_alu_instr(), construct_value(), emit_copy_load_store(), get_deref_reg_src(), insert_mov(), lower_instr(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), nir_lower_io_block(), nir_opt_peephole_select_block(), nir_replace_instr(), and rename_variables().
nir_instr_insert_before_block()
static void nir_instr_insert_before_block (nir_block * block, nir_instr * before) inline static
References nir_before_block(), and nir_instr_insert().
Referenced by convert_loop_exit_for_ssa().
nir_instr_insert_before_cf()
static void nir_instr_insert_before_cf (nir_cf_node * node, nir_instr * before) inline static
References nir_before_cf_node(), and nir_instr_insert().
Referenced by nir_opt_conditional_discard_block().
nir_instr_insert_before_cf_list()
static void nir_instr_insert_before_cf_list (struct exec_list * list, nir_instr * before) inline static
References nir_before_cf_list(), and nir_instr_insert().
Referenced by insert_phi_undef(), and replace_ssa_def_uses().
nir_instr_is_first()
static bool nir_instr_is_first (nir_instr * instr) inline static
References nir_instr::node.
nir_instr_is_last()
static bool nir_instr_is_last (nir_instr * instr) inline static
References nir_instr::node.
Referenced by split_block_cursor().
nir_instr_move_src()
void nir_instr_move_src (nir_instr * dest_instr, nir_src * dest, nir_src * src)
References NIR_SRC_INIT, nir_src::parent_instr, src_add_all_uses(), src_is_valid(), and src_remove_all_uses().
Referenced by lower_sampler(), and nir_tex_instr_remove_src().
nir_instr_next()
static nir_instr* nir_instr_next (nir_instr * instr) inline static
References exec_node_data, exec_node::next, and nir_instr::node.
Referenced by gcm_place_instr(), reduce_cursor(), and split_block_cursor().
nir_instr_prev()
static nir_instr* nir_instr_prev (nir_instr * instr) inline static
References exec_node_data, nir_instr::node, and exec_node::prev.
Referenced by get_parallel_copy_at_end_of_block(), instr_remove_cursor(), is_instr_between(), and reduce_cursor().
nir_instr_remove()
void nir_instr_remove (nir_instr * instr)
References nir_instr::block, nir_handle_remove_jump(), nir_instr_type_jump, nir_instr::node, remove_defs_uses(), nir_instr::type, and nir_jump_instr::type.
Referenced by cleanup_cf_node(), complex_unroll(), constant_fold_alu_instr(), constant_fold_intrinsic_instr(), convert_block(), copy_prop_vars_block(), cse_block(), inline_functions_block(), instr_remove_cursor(), load_from_ssa_entry_value(), loop_prepare_for_unroll(), lower_64bit_pack_impl(), lower_alu_instr_scalar(), lower_copies_to_load_store(), lower_doubles_instr(), lower_indirect_block(), lower_instr(), lower_int64_impl(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_reduction(), lower_returns_in_block(), lower_store_output_to_scalar(), lower_trivial_continues_block(), lower_var_copies_impl(), lower_vec_to_movs_block(), move_cf_list_into_loop_term(), nir_instr_insert_after_cf_list(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_lower_tes_patch_vertices(), nir_lower_to_source_mods_block(), nir_opt_conditional_discard_block(), nir_opt_dce_impl(), nir_opt_peephole_select_block(), nir_replace_instr(), opt_constant_if(), opt_gcm_impl(), opt_undef_store(), remove_dead_var_writes(), remove_dead_writes(), remove_phis_block(), rename_variables(), replace_gradient_with_lod(), resolve_parallel_copy(), resolve_registers_block(), rewrite_emit_vertex(), rewrite_end_primitive(), rewrite_ssa_def(), simple_unroll(), and split_var_copies_block().
nir_instr_rewrite_dest()
void nir_instr_rewrite_dest (nir_instr * instr, nir_dest * dest, nir_dest new_dest)
References nir_reg_dest::def_link, nir_register::defs, nir_ssa_def::if_uses, nir_reg_dest::indirect, instr, nir_dest::is_ssa, nir_dest_copy(), nir_reg_dest::parent_instr, nir_reg_dest::reg, nir_dest::reg, src_add_all_uses(), src_remove_all_uses(), nir_dest::ssa, and nir_ssa_def::uses.
Referenced by lower_vec_to_movs_block(), rewrite_ssa_def(), and try_coalesce().
nir_instr_rewrite_src()
void nir_instr_rewrite_src (nir_instr * instr, nir_src * src, nir_src new_src)
References nir_src::parent_instr, src_add_all_uses(), src_is_valid(), and src_remove_all_uses().
Referenced by calc_sampler_offsets(), constant_fold_deref(), convert_loop_exit_for_ssa(), copy_prop_alu_src(), copy_prop_src(), isolate_phi_nodes_block(), lower_fddy(), lower_interp_var_at_offset(), lower_intrinsic(), lower_offset(), lower_rect(), lower_sampler(), move_vec_src_uses_to_dest_block(), nir_lower_to_source_mods_block(), nir_ssa_def_rewrite_uses(), nir_ssa_def_rewrite_uses_after(), nir_tex_instr_remove_src(), normalize_cubemap_coords_block(), opt_undef_csel(), project_src(), repair_ssa_def(), rewrite_src(), saturate_src(), and try_coalesce().
nir_intrinsic_from_system_value()
nir_intrinsic_op nir_intrinsic_from_system_value (gl_system_value val)
Referenced by convert_block().
nir_intrinsic_instr_create()
nir_intrinsic_instr* nir_intrinsic_instr_create (nir_shader * shader, nir_intrinsic_op op)
References nir_intrinsic_instr::dest, dest_init(), nir_intrinsic_instr::instr, instr, instr_init(), nir_intrinsic_instr::intrinsic, nir_instr_type_intrinsic, nir_intrinsic_infos, nir_intrinsic_info::num_srcs, nir_intrinsic_instr::src, and src_init().
Referenced by append_set_vertex_count(), clone_intrinsic(), emit_copies(), emit_copy_load_store(), emit_load_store(), load_clipdist_input(), load_input(), lower_atomic(), lower_bitmap(), lower_clip_fs(), lower_instr(), lower_interpolate_at(), lower_load(), lower_load_input_to_scalar(), lower_store(), lower_store_output_to_scalar(), nir_copy_deref_var(), nir_copy_var(), nir_function_impl_add_variable(), nir_load_barycentric(), nir_load_deref_var(), nir_load_system_value(), nir_load_var(), nir_opt_conditional_discard_block(), nir_store_deref_var(), nir_store_var(), rewrite_emit_vertex(), rewrite_end_primitive(), split_var_copy_instr(), and store_clipdist_output().
nir_is_per_vertex_io()
bool nir_is_per_vertex_io (nir_variable * var, gl_shader_stage stage)
Return true if the given variable is a per-vertex input/output array.
(such as geometry shader inputs).
References nir_variable::data, nir_variable::nir_variable_data::mode, nir_var_shader_in, nir_var_shader_out, nir_variable::nir_variable_data::patch, and nir_variable::type.
Referenced by get_unwrapped_array_length(), mark_whole_variable(), nir_lower_io_block(), try_mask_partial_io(), and update_type().
nir_jump_instr_create()
nir_jump_instr* nir_jump_instr_create (nir_shader * shader, nir_jump_type type)
References nir_jump_instr::instr, instr, instr_init(), nir_instr_type_jump, nir_jump_instr::type, and type.
Referenced by clone_jump(), nir_function_impl_add_variable(), nir_jump(), and predicate_following().
nir_live_ssa_defs_impl()
void nir_live_ssa_defs_impl (nir_function_impl * impl)
References live_ssa_defs_state::bitset_words, nir_if::condition, if(), index_ssa_def(), init_liveness_block(), instr, nir_block::live_in, nir_block::live_out, nir_block_get_following_if(), nir_block_worklist_fini(), nir_block_worklist_init(), nir_block_worklist_is_empty(), nir_block_worklist_pop_head(), nir_block_worklist_push_tail(), nir_foreach_block, nir_foreach_instr, nir_foreach_instr_reverse, nir_foreach_src(), nir_foreach_ssa_def(), nir_instr_type_phi, nir_function_impl::num_blocks, live_ssa_defs_state::num_ssa_defs, nir_block::predecessors, propagate_across_edge(), set_src_live(), set_ssa_def_dead(), and live_ssa_defs_state::worklist.
Referenced by nir_metadata_require().
nir_load_const_instr_create()
nir_load_const_instr* nir_load_const_instr_create (nir_shader * shader, unsigned num_components, unsigned bit_size)
References nir_load_const_instr::def, nir_load_const_instr::instr, instr, instr_init(), nir_instr_type_load_const, and nir_ssa_def_init().
Referenced by clone_load_const(), constant_fold_alu_instr(), construct_value(), get_deref_reg_src(), lower_instr(), lower_load_const_instr_scalar(), nir_build_imm(), nir_deref_get_const_initializer_load(), and nir_function_impl_add_variable().
nir_local_reg_create()
nir_register* nir_local_reg_create (nir_function_impl * impl)
References nir_register::index, nir_register::is_global, nir_function_impl::reg_alloc, reg_create(), and nir_function_impl::registers.
Referenced by create_reg_for_ssa_def(), get_reg_for_deref(), lower_vec_to_movs_block(), and resolve_parallel_copy().
nir_local_variable_create()
nir_variable* nir_local_variable_create (nir_function_impl * impl, const struct glsl_type * type, const char * name)
creates a local variable and adds it to the list
References nir_variable::data, nir_function_impl::function, nir_variable::nir_variable_data::mode, nir_variable::name, nir_function_impl_add_variable(), nir_var_local, nir_function::shader, nir_variable::type, and type.
Referenced by lower_returns_in_block(), nir_function_impl_add_variable(), and nir_lower_gs_intrinsics().
nir_loop_analyze_impl()
void nir_loop_analyze_impl (nir_function_impl * impl, nir_variable_mode indirect_mask)
References nir_function_impl::body, foreach_list_typed, nir_index_ssa_defs(), and process_loops().
Referenced by nir_metadata_require().
nir_loop_create()
nir_loop* nir_loop_create (nir_shader * shader)
References nir_loop::body, cf_init(), nir_block::cf_node, nir_loop::cf_node, nir_block_create(), nir_cf_node::node, nir_cf_node::parent, nir_block::predecessors, and nir_block::successors.
Referenced by clone_loop(), nir_function_impl_add_variable(), and nir_push_loop().
nir_loop_first_block()
static nir_block* nir_loop_first_block (nir_loop * loop) inline static
References nir_loop::body, exec_node_data, and nir_instr::node.
Referenced by block_add_normal_succs(), complex_unroll(), link_block_to_non_block(), loop_prepare_for_unroll(), lower_trivial_continues_block(), nir_cf_node_cf_tree_first(), nir_handle_add_jump(), opt_peel_loop_initial_if(), and simple_unroll().
nir_loop_last_block()
static nir_block* nir_loop_last_block (nir_loop * loop) inline static
References nir_loop::body, exec_node_data, and nir_instr::node.
Referenced by complex_unroll(), loop_prepare_for_unroll(), lower_trivial_continues_list(), nir_cf_node_cf_tree_last(), and simple_unroll().
nir_lower_64bit_pack()
bool nir_lower_64bit_pack (nir_shader * shader)
References lower_64bit_pack_impl(), and nir_foreach_function.
nir_lower_alu_to_scalar()
bool nir_lower_alu_to_scalar (nir_shader * shader)
References nir_foreach_function, and nir_lower_alu_to_scalar_impl().
nir_lower_atomics()
bool nir_lower_atomics (nir_shader * shader, const struct gl_shader_program * shader_program)
References instr, lower_instr(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_type_intrinsic, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
nir_lower_bitmap()
void nir_lower_bitmap (nir_shader * shader, const nir_lower_bitmap_options * options)
References lower_bitmap_impl(), nir_shader_get_entrypoint(), and nir_shader::stage.
nir_lower_clamp_color_outputs()
bool nir_lower_clamp_color_outputs (nir_shader * shader)
References lower_impl(), and nir_foreach_function.
nir_lower_clip_cull_distance_arrays()
bool nir_lower_clip_cull_distance_arrays (nir_shader * nir)
References combine_clip_cull(), nir_shader::inputs, nir_shader::outputs, and nir_shader::stage.
nir_lower_clip_fs()
bool nir_lower_clip_fs (nir_shader * shader, unsigned ucp_enables)
References create_clipdist_var(), nir_shader::inputs, lower_clip_fs(), nir_foreach_function, and nir_foreach_variable.
nir_lower_clip_vs()
bool nir_lower_clip_vs (nir_shader * shader, unsigned ucp_enables)
References create_clipdist_var(), find_output(), lower_clip_vs(), nir_foreach_function, nir_foreach_variable, and nir_shader::outputs.
nir_lower_constant_initializers()
bool nir_lower_constant_initializers (nir_shader * shader, nir_variable_mode modes)
References nir_shader::globals, nir_builder::impl, nir_function_impl::locals, lower_const_initializer(), nir_builder_init(), nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_preserve(), nir_shader_get_entrypoint(), nir_var_global, nir_var_local, nir_var_shader_out, nir_var_system_value, nir_shader::outputs, and nir_shader::system_values.
nir_lower_doubles()
bool nir_lower_doubles (nir_shader * shader, nir_lower_doubles_options options)
References nir_foreach_function, and nir_lower_doubles_impl().
nir_lower_drawpixels()
void nir_lower_drawpixels (nir_shader * shader, const nir_lower_drawpixels_options * options)
References lower_drawpixels_impl(), nir_foreach_function, nir_builder::shader, and nir_shader::stage.
nir_lower_global_vars_to_local()
bool nir_lower_global_vars_to_local (nir_shader * shader)
References nir_variable::data, mark_global_var_uses_block(), nir_variable::nir_variable_data::mode, nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_preserve(), nir_var_global, nir_var_local, and nir_variable::node.
nir_lower_gs_intrinsics()
bool nir_lower_gs_intrinsics (nir_shader * shader)
References append_set_vertex_count(), nir_function_impl::body, state::builder, nir_builder::cursor, nir_function_impl::end_block, nir_before_cf_list(), nir_builder_init(), nir_foreach_block_safe, nir_imm_int(), nir_local_variable_create(), nir_metadata_preserve(), nir_shader_get_entrypoint(), nir_store_var(), state::progress, rewrite_intrinsics(), and state::vertex_count_var.
nir_lower_idiv()
bool nir_lower_idiv (nir_shader * shader)
References convert_impl(), nir_foreach_function, and state::progress.
nir_lower_indirect_derefs()
bool nir_lower_indirect_derefs (nir_shader * shader, nir_variable_mode modes)
Lowers indirect variable loads/stores to direct loads/stores.
The pass works by replacing any indirect load or store with an if-ladder that does a binary search on the array index.
References lower_indirects_impl(), nir_foreach_function, and state::progress.
nir_lower_int64()
bool nir_lower_int64 (nir_shader * shader, nir_lower_int64_options options)
References lower_int64_impl(), nir_foreach_function, and state::progress.
nir_lower_io()
bool nir_lower_io (nir_shader * shader, nir_variable_mode modes, int(*)(const struct glsl_type *) type_size, nir_lower_io_options)
References nir_foreach_function, nir_lower_io_impl(), and lower_io_state::type_size.
nir_lower_io_to_scalar()
void nir_lower_io_to_scalar (nir_shader * shader, nir_variable_mode mask)
References nir_builder::impl, instr, nir_intrinsic_instr::intrinsic, lower_load_input_to_scalar(), lower_store_output_to_scalar(), nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_type_intrinsic, nir_var_shader_in, nir_var_shader_out, and nir_intrinsic_instr::num_components.
nir_lower_io_to_temporaries()
void nir_lower_io_to_temporaries (nir_shader * shader, nir_function_impl * entrypoint, bool outputs, bool inputs)
References create_shadow_temp(), emit_input_copies_impl(), emit_output_copies_impl(), lower_io_state::entrypoint, nir_shader::globals, nir_shader::inputs, nir_foreach_function, nir_foreach_variable, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_variable::node, lower_io_state::old_inputs, lower_io_state::old_outputs, nir_shader::outputs, lower_io_state::shader, and nir_shader::stage.
nir_lower_io_types()
void nir_lower_io_types (nir_shader * shader)
References nir_shader::inputs, lower_io_types_impl(), lower_io_types_state::new_ins, lower_io_types_state::new_outs, nir_foreach_function, nir_shader::outputs, and lower_io_types_state::shader.
nir_lower_load_const_to_scalar()
bool nir_lower_load_const_to_scalar (nir_shader * shader)
References nir_foreach_function, and nir_lower_load_const_to_scalar_impl().
nir_lower_locals_to_regs()
bool nir_lower_locals_to_regs (nir_shader * shader)
References nir_foreach_function, nir_lower_locals_to_regs_impl(), and locals_to_regs_state::progress.
nir_lower_passthrough_edgeflags()
void nir_lower_passthrough_edgeflags (nir_shader * shader)
References lower_impl(), and nir_shader_get_entrypoint().
nir_lower_phis_to_regs_block()
bool nir_lower_phis_to_regs_block (nir_block * block)
Lower all of the phi nodes in a block to imovs to and from a register.
This provides a very quick-and-dirty out-of-SSA pass that you can run on a single block to convert all of its phis to a register and some imovs. The code that is generated, while not optimal for actual codegen in a back-end, is easy to generate, correct, and will turn into the same set of phis after you call regs_to_ssa and do some copy propagation.
The one intelligent thing this pass does is that it places the moves from the phi sources as high up the predecessor tree as possible instead of in the exact predecessor. This means that, in particular, it will crawl into the deepest nesting of any if-ladders. In order to ensure that doing so is safe, it stops as soon as one of the predecessors has multiple successors.
References nir_ssa_def::bit_size, nir_block::cf_node, create_reg_for_ssa_def(), nir_alu_dest::dest, nir_alu_instr::dest, nir_phi_instr::dest, nir_function_impl::function, from_ssa_state::instr, nir_alu_instr::instr, nir_phi_instr::instr, nir_dest::is_ssa, nir_ssa_def::name, nir_after_instr(), nir_alu_instr_create(), nir_cf_node_get_function(), nir_foreach_instr_safe, nir_foreach_phi_src, nir_instr_insert(), nir_instr_remove(), nir_instr_type_phi, nir_src_for_reg(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_ssa_def::num_components, place_phi_read(), from_ssa_state::progress, nir_function::shader, nir_alu_src::src, nir_alu_instr::src, nir_dest::ssa, nir_instr::type, and nir_alu_dest::write_mask.
Referenced by loop_prepare_for_unroll(), lower_trivial_continues_block(), and opt_peel_loop_initial_if().
nir_lower_phis_to_scalar()
bool nir_lower_phis_to_scalar (nir_shader * shader)
A pass that lowers vector phi nodes to scalar.
This pass loops through the blocks and lowers looks for vector phi nodes it can lower to scalar phi nodes. Not all phi nodes are lowered. For instance, if one of the sources is a non-scalarizable vector, then we don't bother lowering because that would generate hard-to-coalesce movs.
References lower_phis_to_scalar_impl(), and nir_foreach_function.
nir_lower_regs_to_ssa()
bool nir_lower_regs_to_ssa (nir_shader * shader)
References nir_foreach_function, nir_lower_regs_to_ssa_impl(), and nir_shader::registers.
nir_lower_regs_to_ssa_impl()
bool nir_lower_regs_to_ssa_impl (nir_function_impl * impl)
References nir_function_impl::function, instr, nir_block_get_following_if(), nir_foreach_block, nir_foreach_def, nir_foreach_dest(), nir_foreach_instr, nir_foreach_register, nir_foreach_register_safe, nir_foreach_src(), nir_index_local_regs(), nir_instr_type_alu, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), nir_phi_builder_add_value(), nir_phi_builder_create(), nir_phi_builder_finish(), NIR_VLA, nir_function_impl::num_blocks, nir_function_impl::reg_alloc, nir_function_impl::registers, rewrite_alu_instr(), rewrite_dest(), rewrite_if_condition(), rewrite_src(), regs_to_ssa_state::shader, nir_function::shader, and regs_to_ssa_state::values.
Referenced by nir_lower_regs_to_ssa(), nir_opt_if(), nir_opt_loop_unroll_impl(), and nir_opt_trivial_continues().
nir_lower_returns()
bool nir_lower_returns (nir_shader * shader)
References nir_foreach_function, and nir_lower_returns_impl().
nir_lower_returns_impl()
bool nir_lower_returns_impl (nir_function_impl * impl)
References nir_function_impl::body, lower_returns_state::builder, lower_returns_state::cf_list, lower_returns_state::has_predicated_return, lower_returns_state::loop, lower_returns_in_cf_list(), nir_builder_init(), nir_metadata_none, nir_metadata_preserve(), nir_repair_ssa_impl(), and lower_returns_state::return_flag.
Referenced by nir_lower_returns().
nir_lower_samplers()
bool nir_lower_samplers (nir_shader * shader, const struct gl_shader_program * shader_program)
References lower_impl(), nir_foreach_function, and nir_shader::stage.
nir_lower_ssa_defs_to_regs_block()
bool nir_lower_ssa_defs_to_regs_block (nir_block * block)
Lower all of the SSA defs in a block to registers.
This performs the very simple operation of blindly replacing all of the SSA defs in the given block with registers. If not used carefully, this may result in phi nodes with register sources which is technically invalid. Fortunately, the register-based into-SSA pass handles them anyway.
References nir_block::cf_node, create_reg_for_ssa_def(), nir_load_const_instr::def, nir_ssa_undef_instr::def, nir_alu_dest::dest, nir_alu_instr::dest, dest_replace_ssa_with_reg(), nir_function_impl::function, ssa_def_to_reg_state::impl, from_ssa_state::instr, nir_alu_instr::instr, nir_load_const_instr::instr, nir_after_instr(), nir_alu_instr_create(), nir_cf_node_get_function(), nir_dest_for_reg(), nir_foreach_dest(), nir_foreach_instr, nir_instr_insert(), nir_instr_type_load_const, nir_instr_type_ssa_undef, nir_src_for_reg(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_register::num_components, ssa_def_to_reg_state::progress, nir_function::shader, nir_alu_src::src, nir_alu_instr::src, nir_instr::type, and nir_alu_dest::write_mask.
Referenced by opt_peel_loop_initial_if().
nir_lower_system_values()
bool nir_lower_system_values (nir_shader * shader)
References convert_impl(), nir_foreach_function, and nir_shader::system_values.
nir_lower_tes_patch_vertices()
void nir_lower_tes_patch_vertices (nir_shader * tes, unsigned patch_vertices)
References nir_builder::cursor, nir_intrinsic_instr::dest, nir_builder::impl, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_before_instr(), nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_imm_int(), nir_instr_remove(), nir_instr_type_intrinsic, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_dest::ssa.
nir_lower_tex()
bool nir_lower_tex (nir_shader * shader, const nir_lower_tex_options * options)
References nir_foreach_function, and nir_lower_tex_impl().
nir_lower_to_source_mods()
bool nir_lower_to_source_mods (nir_shader * shader)
References nir_foreach_function, and nir_lower_to_source_mods_impl().
nir_lower_two_sided_color()
void nir_lower_two_sided_color (nir_shader * shader)
References nir_foreach_function, nir_lower_two_sided_color_impl(), setup_inputs(), and nir_shader::stage.
nir_lower_var_copies()
bool nir_lower_var_copies (nir_shader * shader)
References lower_var_copies_impl(), and nir_foreach_function.
nir_lower_var_copy_instr()
void nir_lower_var_copy_instr (nir_intrinsic_instr * copy, nir_shader * shader)
References nir_deref_var::deref, emit_copy_load_store(), nir_intrinsic_instr::intrinsic, and nir_intrinsic_instr::variables.
Referenced by lower_copies_to_load_store(), and lower_var_copies_impl().
nir_lower_vars_to_ssa()
bool nir_lower_vars_to_ssa (nir_shader * shader)
References nir_foreach_function, and nir_lower_vars_to_ssa_impl().
nir_lower_vec_to_movs()
bool nir_lower_vec_to_movs (nir_shader * shader)
References nir_foreach_function, and nir_lower_vec_to_movs_impl().
nir_lower_wpos_center()
bool nir_lower_wpos_center (nir_shader * shader, const bool for_sample_shading)
References nir_builder::impl, lower_wpos_center_block(), nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and nir_shader::stage.
nir_lower_wpos_ytransform()
bool nir_lower_wpos_ytransform (nir_shader * shader, const nir_lower_wpos_ytransform_options * options)
References lower_wpos_ytransform_impl(), nir_foreach_function, nir_shader::stage, and lower_wpos_ytransform_state::transform.
nir_metadata_check_validation_flag()
static void nir_metadata_check_validation_flag (nir_shader * shader) inline static
References void.
Referenced by nir_metadata_preserve().
nir_metadata_preserve()
void nir_metadata_preserve (nir_function_impl * impl, nir_metadata preserved)
dirties all but the preserved metadata
References nir_foreach_function, nir_metadata_check_validation_flag(), nir_metadata_not_properly_reset, nir_metadata_set_validation_flag(), and nir_function_impl::valid_metadata.
Referenced by combine_clip_cull(), convert_impl(), inline_function_impl(), lower_64bit_pack_impl(), lower_bitmap_impl(), lower_clip_fs(), lower_clip_vs(), lower_drawpixels_impl(), lower_impl(), lower_indirects_impl(), lower_io_types_impl(), lower_phis_to_scalar_impl(), lower_var_copies_impl(), lower_wpos_ytransform_impl(), nir_cf_extract(), nir_convert_from_ssa_impl(), nir_copy_prop_impl(), nir_function_impl_add_variable(), nir_handle_add_jump(), nir_handle_remove_jump(), nir_lower_alu_to_scalar_impl(), nir_lower_atomics(), nir_lower_constant_initializers(), nir_lower_doubles_impl(), nir_lower_global_vars_to_local(), nir_lower_gs_intrinsics(), nir_lower_io_impl(), nir_lower_io_to_temporaries(), nir_lower_load_const_to_scalar_impl(), nir_lower_locals_to_regs_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_returns_impl(), nir_lower_tes_patch_vertices(), nir_lower_tex_impl(), nir_lower_to_source_mods_impl(), nir_lower_two_sided_color_impl(), nir_lower_vars_to_ssa_impl(), nir_lower_vec_to_movs_impl(), nir_lower_wpos_center(), nir_move_vec_src_uses_to_dest_impl(), nir_opt_constant_folding_impl(), nir_opt_copy_prop_vars(), nir_opt_cse_impl(), nir_opt_dce_impl(), nir_opt_if(), nir_opt_move_comparisons(), nir_opt_peephole_select_impl(), nir_opt_trivial_continues(), nir_opt_undef(), nir_remove_dead_variables(), nir_repair_ssa_impl(), normalize_cubemap_coords_impl(), opt_dead_cf_impl(), opt_gcm_impl(), propagate_invariant_impl(), remove_phis_impl(), split_var_copies_impl(), and sweep_impl().
nir_metadata_require()
void nir_metadata_require (nir_function_impl * impl, nir_metadata required, ...)
requests that the given pieces of metadata be generated
References NEEDS_UPDATE, nir_calc_dominance_impl(), nir_index_blocks(), nir_live_ssa_defs_impl(), nir_loop_analyze_impl(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_loop_analysis, and nir_function_impl::valid_metadata.
Referenced by loop_is_dead(), nir_calc_dominance_impl(), nir_convert_from_ssa_impl(), nir_convert_loop_to_lcssa(), nir_function_impl_add_variable(), nir_lower_locals_to_regs_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_vars_to_ssa_impl(), nir_move_vec_src_uses_to_dest_impl(), nir_opt_cse_impl(), nir_opt_loop_unroll_impl(), nir_repair_ssa_impl(), and opt_gcm_impl().
nir_metadata_set_validation_flag()
static void nir_metadata_set_validation_flag (nir_shader * shader) inline static
References void.
Referenced by nir_metadata_preserve().
nir_move_vec_src_uses_to_dest()
bool nir_move_vec_src_uses_to_dest (nir_shader * shader)
References nir_foreach_function, and nir_move_vec_src_uses_to_dest_impl().
nir_normalize_cubemap_coords()
bool nir_normalize_cubemap_coords (nir_shader * shader)
References nir_foreach_function, and normalize_cubemap_coords_impl().
nir_opt_algebraic()
bool nir_opt_algebraic (nir_shader * shader)
nir_opt_algebraic_late()
bool nir_opt_algebraic_late (nir_shader * shader)
nir_opt_conditional_discard()
bool nir_opt_conditional_discard (nir_shader * shader)
References nir_builder::impl, nir_builder_init(), nir_foreach_block_safe, nir_foreach_function, and nir_opt_conditional_discard_block().
nir_opt_constant_folding()
bool nir_opt_constant_folding (nir_shader * shader)
References nir_foreach_function, nir_opt_constant_folding_impl(), and constant_fold_state::progress.
nir_opt_copy_prop_vars()
bool nir_opt_copy_prop_vars (nir_shader * shader)
References copy_prop_var_state::copies, copy_prop_var_state::copy_free_list, copy_prop_vars_block(), nir_builder::impl, copy_prop_var_state::mem_ctx, nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), copy_prop_var_state::progress, and copy_prop_var_state::shader.
nir_opt_cse()
bool nir_opt_cse (nir_shader * shader)
References nir_foreach_function, and nir_opt_cse_impl().
nir_opt_dce()
bool nir_opt_dce (nir_shader * shader)
References nir_foreach_function, and nir_opt_dce_impl().
nir_opt_dead_cf()
bool nir_opt_dead_cf (nir_shader * shader)
References nir_foreach_function, and opt_dead_cf_impl().
nir_opt_gcm()
bool nir_opt_gcm (nir_shader * shader, bool value_number)
References nir_foreach_function, and opt_gcm_impl().
nir_opt_global_to_local()
bool nir_opt_global_to_local (nir_shader * shader)
References foreach_list_typed_safe, global_to_local(), and nir_shader::registers.
nir_opt_if()
bool nir_opt_if (nir_shader * shader)
References nir_foreach_function, nir_lower_regs_to_ssa_impl(), nir_metadata_none, nir_metadata_preserve(), and opt_if_cf_list().
nir_opt_loop_unroll()
bool nir_opt_loop_unroll (nir_shader * shader, nir_variable_mode indirect_mask)
References nir_foreach_function, and nir_opt_loop_unroll_impl().
nir_opt_move_comparisons()
bool nir_opt_move_comparisons (nir_shader * shader)
References move_comparisons(), nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, and nir_metadata_preserve().
nir_opt_peephole_select()
bool nir_opt_peephole_select (nir_shader * shader, unsigned limit)
References nir_foreach_function, and nir_opt_peephole_select_impl().
nir_opt_remove_phis()
bool nir_opt_remove_phis (nir_shader * shader)
References nir_foreach_function, and remove_phis_impl().
nir_opt_trivial_continues()
bool nir_opt_trivial_continues (nir_shader * shader)
This simple pass gets rid of any "trivial" continues, i.e.
those that are at the tail of a loop where we can just delete the continue instruction and control-flow will naturally and harmlessly take us back to the top of the loop.
References lower_trivial_continues_list(), nir_foreach_function, nir_lower_regs_to_ssa_impl(), nir_metadata_none, and nir_metadata_preserve().
nir_opt_undef()
bool nir_opt_undef (nir_shader * shader)
References nir_builder::impl, instr, nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_type_alu, nir_instr_type_intrinsic, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), opt_undef_csel(), opt_undef_store(), and opt_undef_vecN().
nir_parallel_copy_instr_create()
nir_parallel_copy_instr* nir_parallel_copy_instr_create (nir_shader * shader)
References nir_parallel_copy_instr::entries, nir_parallel_copy_instr::instr, instr, instr_init(), and nir_instr_type_parallel_copy.
Referenced by add_parallel_copy_to_end_of_block(), isolate_phi_nodes_block(), and nir_function_impl_add_variable().
nir_phi_instr_create()
nir_phi_instr* nir_phi_instr_create (nir_shader * shader)
References nir_phi_instr::dest, dest_init(), nir_phi_instr::instr, instr, instr_init(), nir_instr_type_phi, and nir_phi_instr::srcs.
Referenced by clone_phi(), convert_loop_exit_for_ssa(), lower_phis_to_scalar_block(), nir_function_impl_add_variable(), nir_if_phi(), and nir_phi_builder_value_get_block_def().
nir_print_instr()
void nir_print_instr (const nir_instr * instr, FILE * fp)
References print_state::fp, and print_instr().
nir_print_shader()
void nir_print_shader (nir_shader * shader, FILE * fp)
References nir_print_shader_annotated().
nir_print_shader_annotated()
void nir_print_shader_annotated (nir_shader * shader, FILE * fp, struct hash_table * errors)
References print_state::annotations, destroy_print_state(), foreach_list_typed, nir_shader::functions, nir_shader::globals, nir_shader::info, init_print_state(), nir_shader::inputs, nir_foreach_variable, nir_phi_builder_value::node, nir_shader::num_inputs, nir_shader::num_outputs, nir_shader::num_shared, nir_shader::num_uniforms, nir_shader::outputs, print_function(), print_register_decl(), print_var_decl(), nir_shader::registers, nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
Referenced by nir_print_shader().
nir_propagate_invariant()
bool nir_propagate_invariant (nir_shader * shader)
References nir_foreach_function, and propagate_invariant_impl().
nir_reg_remove()
void nir_reg_remove (nir_register * reg)
References nir_register::node.
Referenced by global_to_local().
nir_remove_dead_variables()
bool nir_remove_dead_variables (nir_shader * shader, nir_variable_mode modes)
References add_var_use_shader(), nir_shader::globals, nir_shader::inputs, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_var_global, nir_var_local, nir_var_shader_in, nir_var_shader_out, nir_var_shared, nir_var_system_value, nir_var_uniform, nir_shader::outputs, remove_dead_var_writes(), remove_dead_vars(), nir_shader::shared, nir_shader::system_values, and nir_shader::uniforms.
nir_repair_ssa()
bool nir_repair_ssa (nir_shader * shader)
This pass can be used to repair SSA form in a shader.
Sometimes a transformation (such as return lowering) will have to make changes to a shader which, while still correct, break some of NIR's SSA invariants. This pass will insert ssa_undefs and phi nodes as needed to get the shader back into SSA that the validator will like.
References nir_foreach_function, nir_repair_ssa_impl(), and repair_ssa_state::progress.
nir_repair_ssa_impl()
bool nir_repair_ssa_impl (nir_function_impl * impl)
References repair_ssa_state::def_set, repair_ssa_state::impl, instr, nir_foreach_block, nir_foreach_instr_safe, nir_foreach_ssa_def(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), nir_phi_builder_finish(), repair_ssa_state::phi_builder, repair_ssa_state::progress, and repair_ssa_def().
Referenced by nir_lower_returns_impl(), and nir_repair_ssa().
nir_shader_add_variable()
void nir_shader_add_variable (nir_shader * shader, nir_variable * var)
Adds a variable to the appropriate list in nir_shader.
References nir_variable::data, nir_shader::globals, nir_shader::inputs, nir_variable::nir_variable_data::mode, nir_var_all, nir_var_global, nir_var_local, nir_var_param, nir_var_shader_in, nir_var_shader_out, nir_var_shader_storage, nir_var_shared, nir_var_system_value, nir_var_uniform, nir_variable::node, nir_shader::outputs, nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
Referenced by nir_variable_create().
nir_shader_clone()
nir_shader* nir_shader_clone (void * mem_ctx, const nir_shader * s)
References clone_function(), clone_function_impl(), clone_reg_list(), clone_var_list(), foreach_list_typed, free_clone_state(), nir_function_impl::function, nir_shader::functions, nir_shader::globals, nir_function::impl, nir_shader::info, init_clone_state(), nir_shader::inputs, nir_foreach_function, nir_shader_create(), clone_state::ns, nir_shader::num_inputs, nir_shader::num_outputs, nir_shader::num_shared, nir_shader::num_uniforms, nir_shader::options, nir_shader::outputs, nir_shader::reg_alloc, nir_shader::registers, remap_global(), nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
nir_shader_create()
nir_shader* nir_shader_create (void * mem_ctx, gl_shader_stage stage, const nir_shader_compiler_options * options, shader_info * si)
References nir_shader::functions, nir_shader::globals, nir_shader::info, nir_shader::inputs, nir_shader::num_inputs, nir_shader::num_outputs, nir_shader::num_shared, nir_shader::num_uniforms, nir_shader::options, nir_shader::outputs, nir_shader::reg_alloc, nir_shader::registers, nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
Referenced by nir_builder_init_simple_shader(), and nir_shader_clone().
nir_shader_gather_info()
void nir_shader_gather_info (nir_shader * shader, nir_function_impl * entrypoint)
References gather_info_block(), nir_shader::info, nir_foreach_block, nir_foreach_variable, nir_shader::stage, type, and nir_shader::uniforms.
nir_shader_get_entrypoint()
static nir_function_impl* nir_shader_get_entrypoint (nir_shader * shader) inline static
References exec_node_data, nir_shader::functions, nir_function::impl, nir_instr::node, nir_function::num_params, and nir_function::return_type.
Referenced by nir_lower_bitmap(), nir_lower_constant_initializers(), nir_lower_gs_intrinsics(), and nir_lower_passthrough_edgeflags().
nir_split_var_copies()
bool nir_split_var_copies (nir_shader * shader)
References nir_foreach_function, split_var_copies_state::progress, and split_var_copies_impl().
nir_src_as_const_value()
nir_const_value* nir_src_as_const_value (nir_src src)
References nir_src::is_ssa, nir_instr_type_load_const, nir_ssa_def::parent_instr, nir_src::ssa, nir_instr::type, and nir_load_const_instr::value.
Referenced by constant_fold_intrinsic_instr(), dead_cf_block(), find_output_in_block(), is_neg_power_of_two(), is_pos_power_of_two(), is_zero_to_one(), nir_gs_count_vertices(), nir_lower_two_sided_color_block(), and opt_peel_loop_initial_if().
nir_src_bit_size()
static unsigned nir_src_bit_size (nir_src src) inline static
References nir_register::bit_size, nir_ssa_def::bit_size, nir_src::is_ssa, nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by build_bitsize_tree(), calculate_iterations(), match_value(), nir_fmov_alu(), and nir_imov_alu().
nir_src_copy()
void nir_src_copy (nir_src * dest, const nir_src * src, void * instr_or_if)
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, nir_src_copy(), nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by deref_array_clone(), emit_copy(), get_deref_reg_src(), lower_atomic(), lower_instr(), lower_interpolate_at(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_store(), nir_alu_src_copy(), nir_dest_bit_size(), nir_dest_copy(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), nir_src_copy(), replace_gradient_with_lod(), and sample_plane().
nir_src_for_reg()
static nir_src nir_src_for_reg (nir_register * reg) inline static
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, NIR_SRC_INIT, nir_reg_src::reg, and nir_src::reg.
Referenced by dest_replace_ssa_with_reg(), lower_vec_to_movs_block(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), resolve_parallel_copy(), and rewrite_ssa_def().
nir_src_for_ssa()
static nir_src nir_src_for_ssa (nir_ssa_def * def) inline static
References nir_src::is_ssa, NIR_SRC_INIT, and nir_src::ssa.
Referenced by append_set_vertex_count(), constant_fold_alu_instr(), constant_fold_deref(), construct_value(), convert_block(), convert_instr(), convert_loop_exit_for_ssa(), convert_yuv_to_rgb(), copy_prop_alu_src(), copy_prop_src(), copy_prop_vars_block(), emit_load_store(), emit_wpos_adjustment(), get_texture_size(), isolate_phi_nodes_block(), linearize_srgb_result(), load_clipdist_input(), load_input(), lower_64bit_pack_impl(), lower_alu_instr_scalar(), lower_atomic(), lower_bitmap(), lower_clip_fs(), lower_color(), lower_doubles_instr(), lower_fddy(), lower_indirect_block(), lower_instr(), lower_int64_impl(), lower_interp_var_at_offset(), lower_interpolate_at(), lower_intrinsic(), lower_load(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_load_sample_pos(), lower_locals_to_regs_block(), lower_offset(), lower_phis_to_scalar_block(), lower_rect(), lower_reduction(), lower_sampler(), lower_store(), lower_store_output_to_scalar(), lower_texcoord(), move_vec_src_uses_to_dest_block(), nir_build_alu(), nir_if_phi(), nir_instr_set_add_or_rewrite(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_lower_tes_patch_vertices(), nir_lower_two_sided_color_block(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), nir_phi_builder_finish(), nir_push_if(), nir_replace_instr(), nir_store_deref_var(), nir_store_var(), nir_swizzle(), normalize_cubemap_coords_block(), opt_constant_if(), opt_undef_vecN(), place_phi_read(), predicate_following(), project_src(), remove_phis_block(), rename_variables(), repair_ssa_def(), replace_gradient_with_lod(), replace_ssa_def_uses(), rewrite_alu_instr(), rewrite_emit_vertex(), rewrite_end_primitive(), rewrite_if_condition(), rewrite_src(), sample_plane(), saturate_src(), store_clipdist_output(), swizzle_result(), and update_fragcoord().
nir_src_init()
static nir_src nir_src_init (void) inline static
nir_src_is_dynamically_uniform()
bool nir_src_is_dynamically_uniform (nir_src src)
Returns true if the source is known to be dynamically uniform.
Otherwise it returns false which means it may or may not be dynamically uniform but it can't be determined.
References nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_instr_type_intrinsic, nir_instr_type_load_const, nir_ssa_def::parent_instr, nir_src::ssa, and nir_instr::type.
nir_srcs_equal()
bool nir_srcs_equal (nir_src src1, nir_src src2)
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by insert_mov(), nir_alu_srcs_equal(), nir_instrs_equal(), and resolve_parallel_copy().
nir_ssa_alu_instr_src_components()
static unsigned nir_ssa_alu_instr_src_components (const nir_alu_instr * instr, unsigned src) inline static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_op_info::input_sizes, nir_dest::is_ssa, nir_alu_srcs_equal(), nir_ssa_def::num_components, nir_alu_instr::op, and nir_dest::ssa.
Referenced by constant_fold_alu_instr(), hash_alu(), nir_alu_srcs_equal(), and nir_ssa_for_alu_src().
nir_ssa_def_components_read()
uint8_t nir_ssa_def_components_read (nir_ssa_def * def)
References exec_node_data, nir_alu_instr_channel_used(), nir_foreach_use, nir_instr_type_alu, nir_op_infos, nir_ssa_def::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_instr::src, and nir_alu_src::swizzle.
Referenced by copy_prop_vars_block(), and load_from_ssa_entry_value().
nir_ssa_def_init()
void nir_ssa_def_init (nir_instr * instr, nir_ssa_def * def, unsigned num_components, unsigned bit_size, const char * name)
References nir_ssa_def::bit_size, nir_instr::block, nir_block::cf_node, nir_ssa_def::if_uses, nir_ssa_def::index, instr, nir_ssa_def::name, nir_cf_node_get_function(), nir_ssa_def::num_components, nir_ssa_def::parent_instr, nir_function_impl::ssa_alloc, and nir_ssa_def::uses.
Referenced by nir_load_const_instr_create(), nir_ssa_dest_init(), and nir_ssa_undef_instr_create().
nir_ssa_def_rewrite_uses()
void nir_ssa_def_rewrite_uses (nir_ssa_def * def, nir_src new_src)
References nir_src::is_ssa, nir_foreach_if_use_safe, nir_foreach_use_safe, nir_if_rewrite_condition(), nir_instr_rewrite_src(), and nir_src::ssa.
Referenced by constant_fold_alu_instr(), convert_block(), convert_instr(), convert_yuv_to_rgb(), copy_prop_vars_block(), dest_replace_ssa_with_reg(), emit_wpos_adjustment(), isolate_phi_nodes_block(), lower_64bit_pack_impl(), lower_alu_instr_scalar(), lower_color(), lower_doubles_instr(), lower_indirect_block(), lower_instr(), lower_int64_impl(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_reduction(), lower_texcoord(), lower_vec_to_movs_block(), nir_instr_set_add_or_rewrite(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_lower_tes_patch_vertices(), nir_lower_two_sided_color_block(), nir_opt_peephole_select_block(), nir_replace_instr(), opt_constant_if(), opt_undef_vecN(), remove_phis_block(), rename_variables(), replace_gradient_with_lod(), replace_ssa_def_uses(), and rewrite_ssa_def().
nir_ssa_def_rewrite_uses_after()
void nir_ssa_def_rewrite_uses_after (nir_ssa_def * def, nir_src new_src, nir_instr * after_me)
References is_instr_between(), nir_src::is_ssa, nir_foreach_if_use_safe, nir_foreach_use_safe, nir_if_rewrite_condition(), nir_instr_rewrite_src(), nir_ssa_def::parent_instr, and nir_src::ssa.
Referenced by copy_prop_vars_block(), linearize_srgb_result(), lower_load_sample_pos(), swizzle_result(), and update_fragcoord().
nir_ssa_defs_interfere()
bool nir_ssa_defs_interfere (nir_ssa_def * a, nir_ssa_def * b)
References nir_ssa_def::live_index, nir_ssa_def_is_live_at(), and nir_ssa_def::parent_instr.
Referenced by merge_nodes_interfere().
nir_ssa_dest_init()
void nir_ssa_dest_init (nir_instr * instr, nir_dest * dest, unsigned num_components, unsigned bit_size, const char * name)
References nir_dest::is_ssa, nir_ssa_def_init(), and nir_dest::ssa.
Referenced by __clone_dst(), construct_value(), convert_loop_exit_for_ssa(), emit_copy_load_store(), emit_load_store(), get_deref_reg_src(), get_texture_size(), isolate_phi_nodes_block(), load_clipdist_input(), load_input(), lower_bitmap(), lower_color(), lower_instr(), lower_interpolate_at(), lower_load_input_to_scalar(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), nir_alu_ssa_dest_init(), nir_build_alu(), nir_fmov_alu(), nir_if_phi(), nir_imov_alu(), nir_load_barycentric(), nir_load_deref_var(), nir_load_system_value(), nir_load_var(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_opt_peephole_select_block(), nir_phi_builder_value_get_block_def(), nir_replace_instr(), rename_variables(), replace_gradient_with_lod(), rewrite_alu_instr(), rewrite_dest(), and sample_plane().
nir_ssa_undef_instr_create()
nir_ssa_undef_instr* nir_ssa_undef_instr_create (nir_shader * shader, unsigned num_components, unsigned bit_size)
References nir_ssa_undef_instr::def, nir_ssa_undef_instr::instr, instr, instr_init(), nir_instr_type_ssa_undef, and nir_ssa_def_init().
Referenced by clone_ssa_undef(), insert_phi_undef(), nir_function_impl_add_variable(), nir_phi_builder_value_get_block_def(), nir_ssa_undef(), rename_variables(), and replace_ssa_def_uses().
nir_start_block()
static ATTRIBUTE_RETURNS_NONNULL nir_block* nir_start_block (nir_function_impl * impl) inline static
References nir_function_impl::body, exec_list::head_sentinel, and exec_node::next.
Referenced by emit_input_copies_impl(), emit_output_copies_impl(), gcm_schedule_early_instr(), init_block(), lower_returns_in_block(), nir_calc_dominance_impl(), nir_cf_node_cf_tree_first(), and nir_opt_cse_impl().
nir_sweep()
void nir_sweep (nir_shader * shader)
References foreach_list_typed, nir_shader::functions, nir_shader::globals, nir_shader::info, nir_shader::inputs, nir_shader::outputs, nir_shader::registers, nir_shader::shared, steal_list, sweep_function(), nir_shader::system_values, and nir_shader::uniforms.
nir_system_value_from_intrinsic()
gl_system_value nir_system_value_from_intrinsic (nir_intrinsic_op intrin)
Referenced by gather_intrinsic_info().
nir_tex_instr_create()
nir_tex_instr* nir_tex_instr_create (nir_shader * shader, unsigned num_srcs)
References nir_tex_instr::dest, dest_init(), nir_tex_instr::instr, instr, instr_init(), nir_instr_type_tex, nir_tex_instr::num_srcs, nir_tex_instr::sampler, nir_tex_instr::sampler_index, nir_tex_src::src, nir_tex_instr::src, src_init(), nir_tex_instr::texture, nir_tex_instr::texture_array_size, and nir_tex_instr::texture_index.
Referenced by clone_tex(), get_texture_size(), lower_bitmap(), lower_color(), nir_function_impl_add_variable(), replace_gradient_with_lod(), and sample_plane().
nir_tex_instr_dest_size()
static unsigned nir_tex_instr_dest_size (nir_tex_instr * instr) inline static
References nir_tex_instr::is_array, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, nir_texop_lod, nir_texop_query_levels, nir_texop_samples_identical, nir_texop_texture_samples, nir_texop_txs, nir_tex_instr::op, ret(), and nir_tex_instr::sampler_dim.
Referenced by get_texture_size(), linearize_srgb_result(), sample_plane(), and swizzle_result().
nir_tex_instr_is_query()
static bool nir_tex_instr_is_query (nir_tex_instr * instr) inline static
References nir_texop_lod, nir_texop_query_levels, nir_texop_tex, nir_texop_texture_samples, nir_texop_tg4, nir_texop_txb, nir_texop_txd, nir_texop_txf, nir_texop_txf_ms, nir_texop_txf_ms_mcs, nir_texop_txl, nir_texop_txs, and nir_tex_instr::op.
Referenced by nir_lower_tex_block().
nir_tex_instr_remove_src()
void nir_tex_instr_remove_src (nir_tex_instr * tex, unsigned src_idx)
References nir_tex_instr::instr, nir_instr_move_src(), nir_instr_rewrite_src(), NIR_SRC_INIT, nir_tex_instr::num_srcs, nir_tex_src::src, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by lower_offset(), nir_tex_instr_src_index(), and project_src().
nir_tex_instr_src_index()
static int nir_tex_instr_src_index (nir_tex_instr * instr, nir_tex_src_type type) inline static
References nir_tex_instr_remove_src(), nir_tex_instr::num_srcs, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by lower_gradient_cube_map(), lower_gradient_shadow(), lower_offset(), and project_src().
nir_tex_instr_src_size()
static unsigned nir_tex_instr_src_size (nir_tex_instr * instr, unsigned src) inline static
References nir_tex_instr::coord_components, nir_tex_instr::is_array, nir_tex_src_coord, nir_tex_src_ddx, nir_tex_src_ddy, nir_tex_src_ms_mcs, nir_tex_src_offset, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by copy_prop_instr(), normalize_cubemap_coords_block(), and project_src().
nir_tex_instr_src_type()
static nir_alu_type nir_tex_instr_src_type (nir_tex_instr * instr, unsigned src) inline static
References nir_tex_src_bias, nir_tex_src_comparator, nir_tex_src_coord, nir_tex_src_ddx, nir_tex_src_ddy, nir_tex_src_lod, nir_tex_src_ms_index, nir_tex_src_offset, nir_tex_src_projector, nir_tex_src_sampler_offset, nir_tex_src_texture_offset, nir_texop_samples_identical, nir_texop_txf, nir_texop_txf_ms, nir_texop_txf_ms_mcs, nir_texop_txs, nir_type_float, nir_type_int, nir_tex_instr::op, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by lower_offset().
nir_type_conversion_op()
nir_op nir_type_conversion_op (nir_alu_type src, nir_alu_type dst)
Referenced by nir_get_nir_type_for_glsl_type().
nir_validate_shader()
static void nir_validate_shader (nir_shader * shader) inline static
References void.
nir_variable_clone()
nir_variable* nir_variable_clone (const nir_variable * c, nir_shader * shader)
References nir_variable::constant_initializer, nir_variable::data, nir_variable::interface_type, nir_variable::name, nir_constant_clone(), nir_variable::num_state_slots, nir_variable::state_slots, and nir_variable::type.
Referenced by clone_variable().
nir_variable_create()
nir_variable* nir_variable_create (nir_shader * shader, nir_variable_mode mode, const struct glsl_type * type, const char * name)
creates a variable, sets a few defaults, and adds it to the list
References nir_variable::data, nir_variable::nir_variable_data::interpolation, nir_variable::nir_variable_data::mode, nir_variable::name, nir_shader_add_variable(), nir_var_shader_in, nir_var_shader_out, nir_var_uniform, nir_variable::nir_variable_data::read_only, nir_shader::stage, nir_variable::type, and type.
Referenced by create_uniform(), get_new_var(), get_texcoord(), get_transform(), lower_impl(), and nir_function_impl_add_variable().
nir_variable_is_global()
static bool nir_variable_is_global (const nir_variable * var) inline static
References nir_variable::data, nir_variable::nir_variable_data::mode, nir_var_local, and nir_var_param.
Referenced by remap_var().
should_clone_nir()
static bool should_clone_nir (void) inline static
Variable Documentation
cf_node
nir_cf_node_if cf_node
Referenced by clone_block(), lower_trivial_continues_list(), nir_cf_extract(), nir_cf_node_is_last(), opt_if_cf_list(), opt_peel_loop_initial_if(), sweep_if(), sweep_impl(), and sweep_loop().
deref
deref
Referenced by __clone_dst(), copy_prop_deref_var(), hash_deref(), lower_const_initializer(), NIR_DEFINE_CAST(), nir_deref_array_create(), nir_deref_foreach_leaf(), nir_deref_struct_create(), nir_deref_var_create(), rewrite_references(), and split_var_copy_instr().
deref_type
deref_type
Referenced by lower_io_types_block().
instr
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const instr
Referenced by add_reg_def_cb(), add_ssa_def_cb(), add_use_cb(), add_var_use_shader(), block_check_for_allowed_instrs(), cf_node_has_side_effects(), cleanup_cf_node(), clone_block(), combine_clip_cull(), constant_fold_block(), contains_other_jump(), convert_block(), convert_impl(), convert_to_lcssa(), copy_prop_vars_block(), cse_block(), emit_output_copies_impl(), ends_in_break(), ends_in_jump(), find_output_in_block(), force_unroll_heuristics(), gather_info_block(), gcm_pin_instructions_block(), gcm_place_instr(), gcm_schedule_early_instr(), gcm_schedule_early_src(), get_loop_info(), global_to_local(), hash_instr(), init_block(), init_loop_block(), inline_functions_block(), insert_phi_undef(), loop_is_dead(), lower_64bit_pack_impl(), lower_block(), lower_drawpixels_block(), lower_impl(), lower_indirect_block(), lower_int64_impl(), lower_io_types_block(), lower_locals_to_regs_block(), lower_params_to_locals_block(), lower_phis_to_scalar_block(), lower_var_copies_impl(), lower_vec_to_movs_block(), lower_wpos_center_block(), lower_wpos_ytransform_block(), mark_global_var_uses_block(), move_comparison_source_cb(), move_comparisons(), move_vec_src_uses_to_dest_block(), nir_after_instr(), nir_alu_instr_create(), nir_before_instr(), nir_build_alu(), nir_call_instr_create(), nir_copy_prop_impl(), nir_dest_bit_size(), nir_gs_count_vertices(), nir_handle_add_jump(), nir_index_instrs(), nir_index_ssa_defs(), nir_instr_rewrite_dest(), nir_intrinsic_instr_create(), nir_jump_instr_create(), nir_live_ssa_defs_impl(), nir_load_const_instr_create(), nir_lower_alu_to_scalar_impl(), nir_lower_atomics(), nir_lower_doubles_impl(), nir_lower_io_block(), nir_lower_io_to_scalar(), nir_lower_load_const_to_scalar_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_tes_patch_vertices(), nir_lower_tex_block(), nir_lower_to_source_mods_block(), nir_lower_two_sided_color_block(), nir_opt_conditional_discard_block(), nir_opt_dce_impl(), nir_opt_peephole_select_block(), nir_opt_undef(), nir_parallel_copy_instr_create(), nir_phi_builder_finish(), nir_phi_instr_create(), nir_repair_ssa_impl(), nir_ssa_def_init(), nir_ssa_undef_instr_create(), nir_tex_instr_create(), normalize_cubemap_coords_block(), opt_constant_if(), print_block(), propagate_across_edge(), propagate_invariant_impl(), register_variable_uses_block(), remove_dead_var_writes(), remove_dead_writes(), remove_phi_src(), remove_phis_block(), rename_variables(), rewrite_dest(), rewrite_intrinsics(), rewrite_phi_preds(), rewrite_src(), search_for_use_after_instr(), split_block_beginning(), split_var_copies_block(), stitch_blocks(), sweep_block(), and worklist_push().
nir_call_instr
nir_call_instr
nir_cf_node_type
nir_cf_node_type
nir_deref_array
nir_deref_array
nir_function_impl
nir_cf_node_if nir_function_impl
nir_intrinsic_infos
const nir_intrinsic_info nir_intrinsic_infos[nir_num_intrinsics]
Referenced by add_var_use_intrinsic(), cf_node_has_side_effects(), clone_intrinsic(), constant_fold_intrinsic_instr(), copy_prop_instr(), force_unroll_heuristics(), gcm_pin_instructions_block(), hash_intrinsic(), init_instr(), instr_can_rewrite(), lower_atomic(), lower_instr(), lower_params_to_locals_block(), mark_global_var_uses_block(), nir_instrs_equal(), nir_intrinsic_instr_create(), nir_load_system_value(), nir_lower_io_block(), print_intrinsic_instr(), rewrite_param_derefs(), visit_intrinsic_dest(), and visit_intrinsic_src().
nir_load_const_instr
nir_instr_type_call nir_instr_type_tex nir_load_const_instr
nir_op_infos
const nir_op_info nir_op_infos[nir_num_opcodes]
Referenced by build_bitsize_tree(), calculate_iterations(), clone_alu(), compute_induction_information(), constant_fold_alu_instr(), construct_value(), copy_prop_instr(), hash_alu(), insert_mov(), is_neg_power_of_two(), is_phi_src_scalarizable(), is_pos_power_of_two(), is_swizzleless_move(), is_vec(), is_zero_to_one(), lower_alu_instr_scalar(), lower_int64_alu_instr(), lower_reduction(), mark_invariant(), match_expression(), match_value(), move_comparisons(), move_vec_src_uses_to_dest_block(), nir_alu_instr_create(), nir_build_alu(), nir_instrs_equal(), nir_lower_to_source_mods_block(), nir_ssa_def_components_read(), opt_undef_vecN(), print_alu_instr(), rewrite_alu_instr(), src_is_type(), test_iterations(), try_coalesce(), and visit_alu_src().
nir_phi_instr
nir_instr_type_call nir_instr_type_tex nir_instr_type_load_const nir_phi_instr
nir_tex_instr
nir_instr_type_call nir_tex_instr
type
nir_cf_node_if type
Referenced by cf_init(), cf_node_has_side_effects(), get_unwrapped_array_length(), instr_init(), load_from_ssa_entry_value(), loop_is_dead(), loop_prepare_for_unroll(), mark_whole_variable(), nir_is_trivial_loop_if(), nir_jump_instr_create(), nir_load_deref_var(), nir_local_variable_create(), nir_shader_gather_info(), nir_variable_create(), rewrite_references(), src_is_type(), try_mask_partial_io(), and update_type().