Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_builder.h File Reference
#include "nir_control_flow.h"
#include "nir_builder_opcodes.h"
#include "nir_intrinsics.h"
Data Structures
struct nir_builder
Macros
#define INTRINSIC(name, num_srcs, src_components, has_dest, dest_components, num_variables, num_indices, idx0, idx1, idx2, flags)
#define LAST_INTRINSIC(name)
#define DEFINE_SYSTEM_VALUE(name)
Typedefs
typedef struct nir_builder nir_builder
Functions
static void nir_builder_init (nir_builder *build, nir_function_impl *impl)
static void nir_builder_init_simple_shader (nir_builder *build, void *mem_ctx, gl_shader_stage stage, const nir_shader_compiler_options *options)
static void nir_builder_instr_insert (nir_builder *build, nir_instr *instr)
static nir_instr * nir_builder_last_instr (nir_builder *build)
static void nir_builder_cf_insert (nir_builder *build, nir_cf_node *cf)
static bool nir_builder_is_inside_cf (nir_builder *build, nir_cf_node *cf_node)
static nir_if * nir_push_if (nir_builder *build, nir_ssa_def *condition)
static nir_if * nir_push_else (nir_builder *build, nir_if *nif)
static void nir_pop_if (nir_builder *build, nir_if *nif)
static nir_ssa_def * nir_if_phi (nir_builder *build, nir_ssa_def *then_def, nir_ssa_def *else_def)
static nir_loop * nir_push_loop (nir_builder *build)
static void nir_pop_loop (nir_builder *build, nir_loop *loop)
static nir_ssa_def * nir_ssa_undef (nir_builder *build, unsigned num_components, unsigned bit_size)
static nir_ssa_def * nir_build_imm (nir_builder *build, unsigned num_components, unsigned bit_size, nir_const_value value)
static nir_ssa_def * nir_imm_float (nir_builder *build, float x)
static nir_ssa_def * nir_imm_double (nir_builder *build, double x)
static nir_ssa_def * nir_imm_vec4 (nir_builder *build, float x, float y, float z, float w)
static nir_ssa_def * nir_imm_int (nir_builder *build, int x)
static nir_ssa_def * nir_imm_int64 (nir_builder *build, int64_t x)
static nir_ssa_def * nir_imm_ivec4 (nir_builder *build, int x, int y, int z, int w)
static nir_ssa_def * nir_build_alu (nir_builder *build, nir_op op, nir_ssa_def *src0, nir_ssa_def *src1, nir_ssa_def *src2, nir_ssa_def *src3)
static nir_ssa_def * nir_vec (nir_builder *build, nir_ssa_def **comp, unsigned num_components)
static nir_ssa_def * nir_fmov_alu (nir_builder *build, nir_alu_src src, unsigned num_components)
Similar to nir_fmov, but takes a nir_alu_src instead of a nir_ssa_def.
static nir_ssa_def * nir_imov_alu (nir_builder *build, nir_alu_src src, unsigned num_components)
static nir_ssa_def * nir_swizzle (nir_builder *build, nir_ssa_def *src, const unsigned swiz[4], unsigned num_components, bool use_fmov)
Construct an fmov or imov that reswizzles the source's components.
static nir_ssa_def * nir_fdot (nir_builder *build, nir_ssa_def *src0, nir_ssa_def *src1)
static nir_ssa_def * nir_bany_inequal (nir_builder *b, nir_ssa_def *src0, nir_ssa_def *src1)
static nir_ssa_def * nir_bany (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * nir_channel (nir_builder *b, nir_ssa_def *def, unsigned c)
static nir_ssa_def * nir_channels (nir_builder *b, nir_ssa_def *def, unsigned mask)
static nir_ssa_def * nir_ssa_for_src (nir_builder *build, nir_src src, int num_components)
Turns a nir_src into a nir_ssa_def * so it can be passed to nir_build_alu()-based builder calls.
static nir_ssa_def * nir_ssa_for_alu_src (nir_builder *build, nir_alu_instr *instr, unsigned srcn)
Similar to nir_ssa_for_src(), but for alu srcs, respecting the nir_alu_src's swizzle.
static nir_ssa_def * nir_load_var (nir_builder *build, nir_variable *var)
static nir_ssa_def * nir_load_deref_var (nir_builder *build, nir_deref_var *deref)
static void nir_store_var (nir_builder *build, nir_variable *var, nir_ssa_def *value, unsigned writemask)
static void nir_store_deref_var (nir_builder *build, nir_deref_var *deref, nir_ssa_def *value, unsigned writemask)
static void nir_copy_deref_var (nir_builder *build, nir_deref_var *dest, nir_deref_var *src)
static void nir_copy_var (nir_builder *build, nir_variable *dest, nir_variable *src)
static nir_ssa_def * nir_load_system_value (nir_builder *build, nir_intrinsic_op op, int index)
static nir_ssa_def * nir_load_barycentric (nir_builder *build, nir_intrinsic_op op, unsigned interp_mode)
static void nir_jump (nir_builder *build, nir_jump_type jump_type)
Macro Definition Documentation
DEFINE_SYSTEM_VALUE
#define DEFINE_SYSTEM_VALUE (name)
Value:
static inline nir_ssa_def *                                           \
   nir_load_##name(nir_builder *build)                                   \
   {                                                                     \
      return nir_load_system_value(build, nir_intrinsic_load_##name, 0); \
   }                                                                     \
INTRINSIC
#define INTRINSIC (name, num_srcs, src_components, has_dest, dest_components, num_variables, num_indices, idx0, idx1, idx2, flags)
LAST_INTRINSIC
#define LAST_INTRINSIC (name)
Typedef Documentation
nir_builder
typedef struct nir_builder nir_builder
Function Documentation
nir_bany()
static nir_ssa_def* nir_bany (nir_builder * b, nir_ssa_def * src) inline static
References nir_bany_inequal(), and nir_imm_int().
Referenced by lower_udiv64_mod64().
nir_bany_inequal()
static nir_ssa_def* nir_bany_inequal (nir_builder * b, nir_ssa_def * src0, nir_ssa_def * src1) inline static
References nir_ssa_def::num_components.
Referenced by nir_bany().
nir_build_alu()
static nir_ssa_def* nir_build_alu (nir_builder * build, nir_op op, nir_ssa_def * src0, nir_ssa_def * src1, nir_ssa_def * src2, nir_ssa_def * src3) inline static
References nir_ssa_def::bit_size, nir_alu_dest::dest, nir_alu_instr::dest, nir_builder::exact, nir_alu_instr::exact, nir_op_info::input_sizes, nir_op_info::input_types, nir_alu_instr::instr, instr, nir_alu_instr_create(), nir_alu_type_get_type_size(), nir_builder_instr_insert(), nir_op_infos, nir_src_for_ssa(), nir_ssa_dest_init(), nir_ssa_def::num_components, nir_op_info::num_inputs, nir_op_info::output_size, nir_op_info::output_type, nir_builder::shader, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_alu_src::swizzle, and nir_alu_dest::write_mask.
Referenced by lower_reduction().
nir_build_imm()
static nir_ssa_def* nir_build_imm (nir_builder * build, unsigned num_components, unsigned bit_size, nir_const_value value) inline static
References nir_load_const_instr::def, nir_load_const_instr::instr, nir_builder_instr_insert(), nir_load_const_instr_create(), nir_builder::shader, value, and nir_load_const_instr::value.
Referenced by convert_block(), convert_yuv_to_rgb(), get_zero_or_one(), lower_udiv64_mod64(), nir_imm_double(), nir_imm_float(), nir_imm_int(), nir_imm_int64(), nir_imm_ivec4(), and nir_imm_vec4().
nir_builder_cf_insert()
static void nir_builder_cf_insert (nir_builder * build, nir_cf_node * cf) inline static
References nir_builder::cursor, and nir_cf_node_insert().
Referenced by nir_push_if(), and nir_push_loop().
nir_builder_init()
static void nir_builder_init (nir_builder * build, nir_function_impl * impl) inline static
References nir_builder::exact, nir_function_impl::function, nir_builder::impl, nir_builder::shader, and nir_function::shader.
Referenced by convert_impl(), inline_function_impl(), lower_64bit_pack_impl(), lower_bitmap_impl(), lower_clip_fs(), lower_clip_vs(), lower_doubles_instr(), lower_drawpixels_impl(), lower_impl(), lower_indirects_impl(), lower_int64_impl(), lower_load_const_instr_scalar(), lower_wpos_ytransform_impl(), nir_convert_from_ssa_impl(), nir_lower_alu_to_scalar_impl(), nir_lower_constant_initializers(), nir_lower_gs_intrinsics(), nir_lower_io_impl(), nir_lower_io_to_scalar(), nir_lower_returns_impl(), nir_lower_tes_patch_vertices(), nir_lower_tex_impl(), nir_lower_two_sided_color_impl(), nir_lower_wpos_center(), nir_opt_conditional_discard(), nir_opt_copy_prop_vars(), nir_opt_undef(), normalize_cubemap_coords_impl(), remove_phis_impl(), and rename_variables().
nir_builder_init_simple_shader()
static void nir_builder_init_simple_shader (nir_builder * build, void * mem_ctx, gl_shader_stage stage, const nir_shader_compiler_options * options) inline static
References nir_function_impl::body, nir_builder::cursor, nir_builder::exact, nir_builder::impl, nir_after_cf_list(), nir_function_create(), nir_function_impl_create(), nir_shader_create(), and nir_builder::shader.
nir_builder_instr_insert()
static void nir_builder_instr_insert (nir_builder * build, nir_instr * instr) inline static
References nir_builder::cursor, nir_after_instr(), and nir_instr_insert().
Referenced by append_set_vertex_count(), copy_prop_vars_block(), deref_apply_constant_initializer(), emit_copy(), emit_load_store(), get_texture_size(), load_clipdist_input(), load_input(), lower_alu_instr_scalar(), lower_bitmap(), lower_clip_fs(), lower_color(), lower_interpolate_at(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_reduction(), lower_store_output_to_scalar(), nir_build_alu(), nir_build_imm(), nir_copy_deref_var(), nir_copy_var(), nir_fmov_alu(), nir_if_phi(), nir_imov_alu(), nir_jump(), nir_load_barycentric(), nir_load_deref_var(), nir_load_system_value(), nir_load_var(), nir_store_deref_var(), nir_store_var(), replace_gradient_with_lod(), rewrite_emit_vertex(), rewrite_end_primitive(), sample_plane(), and store_clipdist_output().
nir_builder_is_inside_cf()
static bool nir_builder_is_inside_cf (nir_builder * build, nir_cf_node * cf_node) inline static
References nir_block::cf_node, nir_builder::cursor, nir_cursor_current_block(), and nir_cf_node::parent.
Referenced by nir_pop_if(), nir_pop_loop(), and nir_push_else().
nir_builder_last_instr()
static nir_instr* nir_builder_last_instr (nir_builder * build) inline static
References nir_builder::cursor, nir_cursor::instr, nir_cursor_after_instr, and nir_cursor::option.
Referenced by copy_prop_vars_block().
nir_channel()
static nir_ssa_def* nir_channel (nir_builder * b, nir_ssa_def * def, unsigned c) inline static
References nir_swizzle(), and swizzle().
Referenced by convert_block(), convert_yuv_to_rgb(), emit_wpos_adjustment(), linearize_srgb_result(), load_clipdist_input(), load_from_ssa_entry_value(), lower_alu_instr_scalar(), lower_bitmap(), lower_color(), lower_fddy(), lower_gradient_cube_map(), lower_interp_var_at_offset(), lower_load_sample_pos(), lower_offset(), lower_pack_64(), lower_store_output_to_scalar(), lower_y_u_v_external(), lower_y_uv_external(), lower_yx_xuxv_external(), normalize_cubemap_coords_block(), project_src(), rename_variables(), saturate_src(), swizzle_result(), and update_fragcoord().
nir_channels()
static nir_ssa_def* nir_channels (nir_builder * b, nir_ssa_def * def, unsigned mask) inline static
References nir_swizzle(), and swizzle().
Referenced by lower_gradient_shadow().
nir_copy_deref_var()
static void nir_copy_deref_var (nir_builder * build, nir_deref_var * dest, nir_deref_var * src) inline static
References nir_deref_var::deref, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_var_clone(), nir_intrinsic_instr_create(), nir_builder::shader, and nir_intrinsic_instr::variables.
Referenced by inline_functions_block().
nir_copy_var()
static void nir_copy_var (nir_builder * build, nir_variable * dest, nir_variable * src) inline static
References nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_var_create(), nir_intrinsic_instr_create(), nir_builder::shader, and nir_intrinsic_instr::variables.
nir_fdot()
static nir_ssa_def* nir_fdot (nir_builder * build, nir_ssa_def * src0, nir_ssa_def * src1) inline static
References nir_ssa_def::num_components.
Referenced by lower_gradient_cube_map(), and lower_gradient_shadow().
nir_fmov_alu()
static nir_ssa_def* nir_fmov_alu (nir_builder * build, nir_alu_src src, unsigned num_components) inline static
Similar to nir_fmov, but takes a nir_alu_src instead of a nir_ssa_def.
References nir_alu_dest::dest, nir_alu_instr::dest, nir_builder::exact, nir_alu_instr::exact, nir_alu_instr::instr, nir_alu_instr_create(), nir_builder_instr_insert(), nir_src_bit_size(), nir_ssa_dest_init(), nir_builder::shader, nir_alu_src::src, nir_alu_instr::src, nir_dest::ssa, and nir_alu_dest::write_mask.
Referenced by lower_doubles_instr(), nir_swizzle(), and remove_phis_block().
nir_if_phi()
static nir_ssa_def* nir_if_phi (nir_builder * build, nir_ssa_def * then_def, nir_ssa_def * else_def) inline static
References nir_ssa_def::bit_size, nir_block::cf_node, nir_builder::cursor, nir_phi_instr::dest, nir_phi_instr::instr, nir_builder_instr_insert(), nir_cf_node_prev(), nir_cursor_current_block(), nir_if_last_else_block(), nir_if_last_then_block(), nir_phi_instr_create(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_phi_src::node, nir_ssa_def::num_components, nir_phi_src::pred, nir_builder::shader, nir_phi_src::src, nir_phi_instr::srcs, and nir_dest::ssa.
Referenced by emit_indirect_load_store(), and lower_udiv64_mod64().
nir_imm_double()
static nir_ssa_def* nir_imm_double (nir_builder * build, double x) inline static
References nir_const_value::f64, and nir_build_imm().
Referenced by fix_inv_result(), lower_ceil(), lower_floor(), lower_mod(), lower_rcp(), lower_round_even(), lower_sqrt_rsq(), and lower_trunc().
nir_imm_float()
static nir_ssa_def* nir_imm_float (nir_builder * build, float x) inline static
References nir_const_value::f32, and nir_build_imm().
Referenced by convert_yuv_to_rgb(), linearize_srgb_result(), lower_clip_fs(), lower_clip_vs(), lower_gradient_cube_map(), lower_load_sample_pos(), nir_cmp(), saturate_src(), and update_fragcoord().
nir_imm_int()
static nir_ssa_def* nir_imm_int (nir_builder * build, int x) inline static
References nir_const_value::i32, and nir_build_imm().
Referenced by calc_sampler_offsets(), convert_block(), convert_instr(), emit_indirect_load_store(), fix_inv_result(), get_exponent(), get_io_offset(), get_signed_inf(), get_texture_size(), load_clipdist_input(), load_input(), lower_alu_instr_scalar(), lower_idiv64(), lower_imod64(), lower_irem64(), lower_isign64(), lower_rcp(), lower_returns_in_block(), lower_sampler(), lower_sqrt_rsq(), lower_trunc(), lower_udiv64_mod64(), nir_bany(), nir_lower_gs_intrinsics(), nir_lower_tes_patch_vertices(), rewrite_emit_vertex(), sample_plane(), set_exponent(), and store_clipdist_output().
nir_imm_int64()
static nir_ssa_def* nir_imm_int64 (nir_builder * build, int64_t x) inline static
References nir_const_value::i64, and nir_build_imm().
Referenced by lower_imod64().
nir_imm_ivec4()
static nir_ssa_def* nir_imm_ivec4 (nir_builder * build, int x, int y, int z, int w) inline static
References nir_const_value::i32, and nir_build_imm().
nir_imm_vec4()
static nir_ssa_def* nir_imm_vec4 (nir_builder * build, float x, float y, float z, float w) inline static
References nir_const_value::f32, and nir_build_imm().
Referenced by emit_wpos_adjustment(), and update_fragcoord().
nir_imov_alu()
static nir_ssa_def* nir_imov_alu (nir_builder * build, nir_alu_src src, unsigned num_components) inline static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_builder::exact, nir_alu_instr::exact, nir_alu_instr::instr, nir_alu_instr_create(), nir_builder_instr_insert(), nir_src_bit_size(), nir_ssa_dest_init(), nir_builder::shader, nir_alu_src::src, nir_alu_instr::src, nir_dest::ssa, and nir_alu_dest::write_mask.
Referenced by nir_ssa_for_alu_src(), nir_ssa_for_src(), nir_swizzle(), and remove_phis_block().
nir_jump()
static void nir_jump (nir_builder * build, nir_jump_type jump_type) inline static
References nir_jump_instr::instr, nir_builder_instr_insert(), nir_jump_instr_create(), and nir_builder::shader.
Referenced by lower_returns_in_block().
nir_load_barycentric()
static nir_ssa_def* nir_load_barycentric (nir_builder * build, nir_intrinsic_op op, unsigned interp_mode) inline static
References nir_intrinsic_instr::dest, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_intrinsic_instr_create(), nir_ssa_dest_init(), nir_builder::shader, and nir_dest::ssa.
Referenced by lower_load().
nir_load_deref_var()
static nir_ssa_def* nir_load_deref_var (nir_builder * build, nir_deref_var * deref) inline static
References nir_deref_var::deref, nir_intrinsic_instr::dest, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_var_clone(), nir_intrinsic_instr_create(), nir_ssa_dest_init(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_dest::ssa, type, and nir_intrinsic_instr::variables.
Referenced by load_from_ssa_entry_value().
nir_load_system_value()
static nir_ssa_def* nir_load_system_value (nir_builder * build, nir_intrinsic_op op, int index) inline static
References nir_intrinsic_instr::const_index, nir_intrinsic_instr::dest, nir_intrinsic_info::dest_components, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_intrinsic_infos, nir_intrinsic_instr_create(), nir_ssa_dest_init(), nir_intrinsic_instr::num_components, nir_builder::shader, and nir_dest::ssa.
Referenced by convert_block(), lower_clip_vs(), and update_fragcoord().
nir_load_var()
static nir_ssa_def* nir_load_var (nir_builder * build, nir_variable * var) inline static
References nir_intrinsic_instr::dest, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_var_create(), nir_intrinsic_instr_create(), nir_ssa_dest_init(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_dest::ssa, nir_variable::type, and nir_intrinsic_instr::variables.
Referenced by append_set_vertex_count(), emit_wpos_adjustment(), get_bias(), get_scale(), get_texcoord(), get_texcoord_const(), get_transform(), lower_bitmap(), lower_impl(), predicate_following(), rewrite_emit_vertex(), and rewrite_end_primitive().
nir_pop_if()
static void nir_pop_if (nir_builder * build, nir_if * nif) inline static
References nir_block::cf_node, nir_if::cf_node, nir_builder::cursor, nir_after_cf_node(), nir_builder_is_inside_cf(), nir_cursor_current_block(), and nir_cf_node::parent.
Referenced by emit_indirect_load_store(), lower_udiv64_mod64(), and rewrite_emit_vertex().
nir_pop_loop()
static void nir_pop_loop (nir_builder * build, nir_loop * loop) inline static
References nir_block::cf_node, nir_loop::cf_node, nir_builder::cursor, nir_after_cf_node(), nir_builder_is_inside_cf(), nir_cursor_current_block(), and nir_cf_node::parent.
nir_push_else()
static nir_if* nir_push_else (nir_builder * build, nir_if * nif) inline static
References nir_block::cf_node, nir_if::cf_node, nir_builder::cursor, nir_if::else_list, nir_before_cf_list(), nir_builder_is_inside_cf(), nir_cursor_current_block(), and nir_cf_node::parent.
Referenced by emit_indirect_load_store().
nir_push_if()
static nir_if* nir_push_if (nir_builder * build, nir_ssa_def * condition) inline static
References nir_if::cf_node, nir_if::condition, nir_builder::cursor, nir_before_cf_list(), nir_builder_cf_insert(), nir_if_create(), nir_src_for_ssa(), nir_builder::shader, and nir_if::then_list.
Referenced by emit_indirect_load_store(), lower_udiv64_mod64(), and rewrite_emit_vertex().
nir_push_loop()
static nir_loop* nir_push_loop (nir_builder * build) inline static
References nir_loop::body, nir_loop::cf_node, nir_builder::cursor, nir_before_cf_list(), nir_builder_cf_insert(), nir_loop_create(), and nir_builder::shader.
nir_ssa_for_alu_src()
static nir_ssa_def* nir_ssa_for_alu_src (nir_builder * build, nir_alu_instr * instr, unsigned srcn) inline static
Similar to nir_ssa_for_src(), but for alu srcs, respecting the nir_alu_src's swizzle.
References nir_alu_src::abs, nir_src::is_ssa, nir_alu_src::negate, nir_imov_alu(), nir_ssa_alu_instr_src_components(), nir_ssa_def::num_components, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and nir_alu_src::swizzle.
Referenced by convert_instr(), lower_64bit_pack_impl(), lower_fddy(), and lower_int64_alu_instr().
nir_ssa_for_src()
static nir_ssa_def* nir_ssa_for_src (nir_builder * build, nir_src src, int num_components) inline static
Turns a nir_src into a nir_ssa_def * so it can be passed to nir_build_alu()-based builder calls.
See nir_ssa_for_alu_src() for alu instructions.
References nir_src::is_ssa, nir_imov_alu(), NIR_SRC_INIT, nir_ssa_def::num_components, nir_alu_src::src, nir_src::ssa, and nir_alu_src::swizzle.
Referenced by calc_sampler_offsets(), get_io_offset(), lower_interp_var_at_offset(), lower_intrinsic(), lower_rect(), lower_store_output_to_scalar(), nir_opt_conditional_discard_block(), normalize_cubemap_coords_block(), project_src(), and saturate_src().
nir_ssa_undef()
static nir_ssa_def* nir_ssa_undef (nir_builder * build, unsigned num_components, unsigned bit_size) inline static
References nir_function_impl::body, nir_ssa_undef_instr::def, nir_builder::impl, nir_ssa_undef_instr::instr, nir_before_cf_list(), nir_instr_insert(), nir_ssa_undef_instr_create(), and nir_builder::shader.
Referenced by opt_undef_vecN().
nir_store_deref_var()
static void nir_store_deref_var (nir_builder * build, nir_deref_var * deref, nir_ssa_def * value, unsigned writemask) inline static
References nir_intrinsic_instr::const_index, nir_deref_var::deref, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_var_clone(), nir_intrinsic_instr_create(), nir_src_for_ssa(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_intrinsic_instr::src, and nir_intrinsic_instr::variables.
Referenced by copy_prop_vars_block(), and deref_apply_constant_initializer().
nir_store_var()
static void nir_store_var (nir_builder * build, nir_variable * var, nir_ssa_def * value, unsigned writemask) inline static
References nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_var_create(), nir_intrinsic_instr_create(), nir_src_for_ssa(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_intrinsic_instr::src, nir_variable::type, and nir_intrinsic_instr::variables.
Referenced by lower_impl(), lower_returns_in_block(), nir_lower_gs_intrinsics(), and rewrite_emit_vertex().
nir_swizzle()
static nir_ssa_def* nir_swizzle (nir_builder * build, nir_ssa_def * src, const unsigned swiz[4], unsigned num_components, bool use_fmov) inline static
Construct an fmov or imov that reswizzles the source's components.
References nir_fmov_alu(), nir_imov_alu(), nir_src_for_ssa(), NIR_SRC_INIT, nir_alu_src::src, and nir_alu_src::swizzle.
Referenced by linearize_srgb_result(), lower_color(), lower_gradient_cube_map(), nir_channel(), nir_channels(), rename_variables(), and swizzle_result().
nir_vec()
static nir_ssa_def* nir_vec (nir_builder * build, nir_ssa_def ** comp, unsigned num_components) inline static
Referenced by load_from_ssa_entry_value(), lower_alu_instr_scalar(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), rename_variables(), saturate_src(), and swizzle_result().