Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_clamp_color_outputs.c File Reference
#include "nir.h"
#include "nir_builder.h"
Data Structures
struct lower_state
Functions
static bool is_color_output (lower_state *state, nir_variable *out)
static bool lower_intrinsic (lower_state *state, nir_intrinsic_instr *intr)
static bool lower_block (lower_state *state, nir_block *block)
static bool lower_impl (lower_state *state, nir_function_impl *impl)
bool nir_lower_clamp_color_outputs (nir_shader *shader)
Function Documentation
is_color_output()
static bool is_color_output (lower_state * state, nir_variable * out) static
References nir_variable::data, nir_variable::nir_variable_data::location, lower_state::shader, and nir_shader::stage.
Referenced by lower_intrinsic().
lower_block()
static bool lower_block (lower_state * state, nir_block * block) static
References instr, lower_intrinsic(), nir_foreach_instr_safe, and nir_instr_type_intrinsic.
Referenced by lower_impl().
lower_impl()
static bool lower_impl (lower_state * state, nir_function_impl * impl) static
References lower_state::b, lower_block(), nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_clamp_color_outputs().
lower_intrinsic()
static bool lower_intrinsic (lower_state * state, nir_intrinsic_instr * intr) static
References lower_state::b, nir_builder::cursor, nir_variable::data, nir_intrinsic_instr::instr, nir_intrinsic_instr::intrinsic, is_color_output(), nir_variable::nir_variable_data::mode, nir_before_instr(), nir_foreach_variable, nir_instr_rewrite_src(), nir_src_for_ssa(), nir_ssa_for_src(), nir_var_shader_out, nir_intrinsic_instr::num_components, nir_shader::outputs, lower_state::shader, nir_intrinsic_instr::src, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_block().
nir_lower_clamp_color_outputs()
bool nir_lower_clamp_color_outputs (nir_shader * shader)
References lower_impl(), and nir_foreach_function.