Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_io_to_temporaries.c File Reference
#include "nir.h"
Data Structures
struct lower_io_state
Functions
static void emit_copies (nir_cursor cursor, nir_shader *shader, struct exec_list *new_vars, struct exec_list *old_vars)
static void emit_output_copies_impl (struct lower_io_state *state, nir_function_impl *impl)
static void emit_input_copies_impl (struct lower_io_state *state, nir_function_impl *impl)
static nir_variable * create_shadow_temp (struct lower_io_state *state, nir_variable *var)
void nir_lower_io_to_temporaries (nir_shader *shader, nir_function_impl *entrypoint, bool outputs, bool inputs)
Function Documentation
create_shadow_temp()
static nir_variable* create_shadow_temp (struct lower_io_state * state, nir_variable * var) static
References nir_variable::constant_initializer, nir_variable::data, nir_variable::nir_variable_data::fb_fetch_output, nir_variable::nir_variable_data::mode, nir_variable::name, nir_var_global, nir_var_shader_in, nir_variable::nir_variable_data::read_only, and lower_io_state::shader.
Referenced by nir_lower_io_to_temporaries().
emit_copies()
static void emit_copies (nir_cursor cursor, nir_shader * shader, struct exec_list * new_vars, struct exec_list * old_vars) static
References nir_variable::data, exec_node_data, nir_variable::nir_variable_data::fb_fetch_output, foreach_two_lists, nir_intrinsic_instr::instr, nir_variable::nir_variable_data::mode, nir_deref_var_create(), nir_instr_insert(), nir_intrinsic_instr_create(), nir_var_shader_out, nir_variable::nir_variable_data::read_only, and nir_intrinsic_instr::variables.
Referenced by emit_input_copies_impl(), and emit_output_copies_impl().
emit_input_copies_impl()
static void emit_input_copies_impl (struct lower_io_state * state, nir_function_impl * impl) static
References emit_copies(), lower_io_state::entrypoint, nir_shader::inputs, nir_before_block(), nir_start_block(), lower_io_state::old_inputs, and lower_io_state::shader.
Referenced by nir_lower_io_to_temporaries().
emit_output_copies_impl()
static void emit_output_copies_impl (struct lower_io_state * state, nir_function_impl * impl) static
References emit_copies(), nir_function_impl::end_block, lower_io_state::entrypoint, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_after_block_before_jump(), nir_before_block(), nir_before_instr(), nir_foreach_block, nir_foreach_instr, nir_instr_type_intrinsic, nir_start_block(), lower_io_state::old_outputs, nir_shader::outputs, nir_block::predecessors, lower_io_state::shader, and nir_shader::stage.
Referenced by nir_lower_io_to_temporaries().
nir_lower_io_to_temporaries()
void nir_lower_io_to_temporaries (nir_shader * shader, nir_function_impl * entrypoint, bool outputs, bool inputs)
References create_shadow_temp(), emit_input_copies_impl(), emit_output_copies_impl(), lower_io_state::entrypoint, nir_shader::globals, nir_shader::inputs, nir_foreach_function, nir_foreach_variable, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_variable::node, lower_io_state::old_inputs, lower_io_state::old_outputs, nir_shader::outputs, lower_io_state::shader, and nir_shader::stage.