Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_copy_prop_vars.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "util/bitscan.h"
Data Structures
struct value
Variable-based copy propagation.
struct copy_entry
struct copy_prop_var_state
Enumerations
enum deref_compare_result { derefs_equal_bit = (1 << 0), derefs_may_alias_bit = (1 << 1), derefs_a_contains_b_bit = (1 << 2), derefs_b_contains_a_bit = (1 << 3) }
Functions
static struct copy_entry * copy_entry_create (struct copy_prop_var_state *state, nir_deref_var *dst_deref)
static void copy_entry_remove (struct copy_prop_var_state *state, struct copy_entry *entry)
static enum deref_compare_result compare_derefs (nir_deref_var *a, nir_deref_var *b)
Returns true if the storage referrenced to by deref completely contains the storage referenced by sub.
static void remove_dead_writes (struct copy_prop_var_state *state, struct copy_entry *entry, unsigned write_mask)
static struct copy_entry * lookup_entry_for_deref (struct copy_prop_var_state *state, nir_deref_var *deref, enum deref_compare_result allowed_comparisons)
static void mark_aliased_entries_as_read (struct copy_prop_var_state *state, nir_deref_var *deref, unsigned components)
static struct copy_entry * get_entry_and_kill_aliases (struct copy_prop_var_state *state, nir_deref_var *deref, unsigned write_mask)
static void apply_barrier_for_modes (struct copy_prop_var_state *state, nir_variable_mode modes)
static void store_to_entry (struct copy_prop_var_state *state, struct copy_entry *entry, const struct value *value, unsigned write_mask, nir_instr *store_instr)
static nir_cursor instr_remove_cursor (nir_instr *instr)
static bool load_from_ssa_entry_value (struct copy_prop_var_state *state, struct copy_entry *entry, nir_builder *b, nir_intrinsic_instr *intrin, struct value *value)
static nir_deref_var * specialize_wildcards (nir_deref_var *deref, nir_deref_var *guide, nir_deref_var *specific, void *mem_ctx)
Specialize the wildcards in a deref chain.
static bool load_from_deref_entry_value (struct copy_prop_var_state *state, struct copy_entry *entry, nir_builder *b, nir_intrinsic_instr *intrin, nir_deref_var *src, struct value *value)
static bool try_load_from_entry (struct copy_prop_var_state *state, struct copy_entry *entry, nir_builder *b, nir_intrinsic_instr *intrin, nir_deref_var *src, struct value *value)
static void copy_prop_vars_block (struct copy_prop_var_state *state, nir_builder *b, nir_block *block)
bool nir_opt_copy_prop_vars (nir_shader *shader)
Enumeration Type Documentation
deref_compare_result
enum deref_compare_result
Enumerator
derefs_equal_bit
derefs_may_alias_bit
derefs_a_contains_b_bit
derefs_b_contains_a_bit
Function Documentation
apply_barrier_for_modes()
static void apply_barrier_for_modes (struct copy_prop_var_state * state, nir_variable_mode modes) static
References copy_prop_var_state::copies, copy_entry_remove(), and copy_entry::link.
Referenced by copy_prop_vars_block().
compare_derefs()
static enum deref_compare_result compare_derefs (nir_deref_var * a, nir_deref_var * b) static
Returns true if the storage referrenced to by deref completely contains the storage referenced by sub.
NOTE: This is fairly general and could be moved to core NIR if someone else ever needs it.
References nir_deref_array::base_offset, nir_deref::child, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, derefs_a_contains_b_bit, derefs_b_contains_a_bit, derefs_equal_bit, derefs_may_alias_bit, nir_deref_struct::index, nir_deref_array::indirect, nir_src::is_ssa, nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_array_type_wildcard, nir_deref_type_array, nir_deref_type_struct, nir_src::ssa, and nir_deref_var::var.
Referenced by copy_prop_vars_block(), get_entry_and_kill_aliases(), lookup_entry_for_deref(), and mark_aliased_entries_as_read().
copy_entry_create()
static struct copy_entry* copy_entry_create (struct copy_prop_var_state * state, nir_deref_var * dst_deref) static
References copy_prop_var_state::copies, copy_prop_var_state::copy_free_list, copy_entry::dst, copy_entry::link, and copy_prop_var_state::mem_ctx.
Referenced by copy_prop_vars_block(), and get_entry_and_kill_aliases().
copy_entry_remove()
static void copy_entry_remove (struct copy_prop_var_state * state, struct copy_entry * entry) static
References copy_prop_var_state::copy_free_list, and copy_entry::link.
Referenced by apply_barrier_for_modes(), copy_prop_vars_block(), and get_entry_and_kill_aliases().
copy_prop_vars_block()
static void copy_prop_vars_block (struct copy_prop_var_state * state, nir_builder * b, nir_block * block) static
References apply_barrier_for_modes(), nir_instr::block, compare_derefs(), copy_prop_var_state::copies, copy_entry_create(), copy_entry_remove(), derefs_a_contains_b_bit, derefs_equal_bit, nir_intrinsic_instr::dest, copy_entry::dst, get_entry_and_kill_aliases(), nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, lookup_entry_for_deref(), mark_aliased_entries_as_read(), nir_builder_instr_insert(), nir_builder_last_instr(), nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_intrinsic, nir_src_for_ssa(), nir_ssa_def_components_read(), nir_ssa_def_rewrite_uses(), nir_ssa_def_rewrite_uses_after(), nir_store_deref_var(), nir_var_global, nir_var_local, nir_var_shader_in, nir_var_shader_out, nir_var_uniform, nir_intrinsic_instr::num_components, nir_ssa_def::parent_instr, copy_prop_var_state::progress, copy_entry::src, nir_intrinsic_instr::src, nir_src::ssa, nir_dest::ssa, store_to_entry(), try_load_from_entry(), and nir_intrinsic_instr::variables.
Referenced by nir_opt_copy_prop_vars().
get_entry_and_kill_aliases()
static struct copy_entry* get_entry_and_kill_aliases (struct copy_prop_var_state * state, nir_deref_var * deref, unsigned write_mask) static
References compare_derefs(), copy_prop_var_state::copies, copy_entry_create(), copy_entry_remove(), derefs_b_contains_a_bit, derefs_equal_bit, derefs_may_alias_bit, copy_entry::link, and remove_dead_writes().
Referenced by copy_prop_vars_block().
instr_remove_cursor()
static nir_cursor instr_remove_cursor (nir_instr * instr) static
References nir_instr::block, nir_after_instr(), nir_before_block(), nir_instr_prev(), and nir_instr_remove().
Referenced by load_from_deref_entry_value(), and load_from_ssa_entry_value().
load_from_deref_entry_value()
static bool load_from_deref_entry_value (struct copy_prop_var_state * state, struct copy_entry * entry, nir_builder * b, nir_intrinsic_instr * intrin, nir_deref_var * src, struct value * value) static
References nir_deref::child, nir_builder::cursor, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, copy_entry::dst, nir_intrinsic_instr::instr, instr_remove_cursor(), copy_prop_var_state::mem_ctx, nir_deref_array_type_wildcard, nir_deref_clone(), nir_deref_type_array, nir_deref_var_clone(), specialize_wildcards(), and copy_entry::src.
Referenced by try_load_from_entry().
load_from_ssa_entry_value()
static bool load_from_ssa_entry_value (struct copy_prop_var_state * state, struct copy_entry * entry, nir_builder * b, nir_intrinsic_instr * intrin, struct value * value) static
References nir_instr::block, nir_builder::cursor, nir_deref_var::deref, nir_intrinsic_instr::dest, copy_entry::dst, if(), nir_intrinsic_instr::instr, nir_cursor::instr, instr_remove_cursor(), nir_intrinsic_instr::intrinsic, nir_after_instr(), nir_channel(), nir_instr_remove(), nir_load_deref_var(), nir_ssa_def_components_read(), nir_vec(), nir_ssa_def::parent_instr, copy_entry::src, nir_dest::ssa, and type.
Referenced by try_load_from_entry().
lookup_entry_for_deref()
static struct copy_entry* lookup_entry_for_deref (struct copy_prop_var_state * state, nir_deref_var * deref, enum deref_compare_result allowed_comparisons) static
References compare_derefs(), copy_prop_var_state::copies, and copy_entry::link.
Referenced by copy_prop_vars_block().
mark_aliased_entries_as_read()
static void mark_aliased_entries_as_read (struct copy_prop_var_state * state, nir_deref_var * deref, unsigned components) static
References compare_derefs(), copy_prop_var_state::copies, derefs_may_alias_bit, and copy_entry::link.
Referenced by copy_prop_vars_block().
nir_opt_copy_prop_vars()
bool nir_opt_copy_prop_vars (nir_shader * shader)
References copy_prop_var_state::copies, copy_prop_var_state::copy_free_list, copy_prop_vars_block(), nir_builder::impl, copy_prop_var_state::mem_ctx, nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), copy_prop_var_state::progress, and copy_prop_var_state::shader.
remove_dead_writes()
static void remove_dead_writes (struct copy_prop_var_state * state, struct copy_entry * entry, unsigned write_mask) static
References copy_entry::comps_may_be_read, instr, nir_instr_remove(), copy_prop_var_state::progress, and copy_entry::store_instr.
Referenced by get_entry_and_kill_aliases().
specialize_wildcards()
static nir_deref_var* specialize_wildcards (nir_deref_var * deref, nir_deref_var * guide, nir_deref_var * specific, void * mem_ctx) static
Specialize the wildcards in a deref chain.
This function returns a deref chain identical to
Parameters
deref except that some of its wildcards are replaced with indices from
specific. The process is guided by
guide which references the same type as
specific but has the same wildcard array lengths as
deref.
References nir_deref_array::base_offset, nir_deref::child, nir_deref_var::deref, nir_deref_array::deref, nir_deref_struct::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_struct::index, nir_deref_array::indirect, nir_src::is_ssa, nir_deref_array_create(), nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_array_type_wildcard, nir_deref_struct_create(), nir_deref_type_array, nir_deref_type_struct, nir_deref_type_var, nir_deref_var_create(), ret(), nir_deref::type, and nir_deref_var::var.
Referenced by load_from_deref_entry_value().
store_to_entry()
static void store_to_entry (struct copy_prop_var_state * state, struct copy_entry * entry, const struct value * value, unsigned write_mask, nir_instr * store_instr) static
References copy_entry::comps_may_be_read, copy_entry::src, and copy_entry::store_instr.
Referenced by copy_prop_vars_block().
try_load_from_entry()
static bool try_load_from_entry (struct copy_prop_var_state * state, struct copy_entry * entry, nir_builder * b, nir_intrinsic_instr * intrin, nir_deref_var * src, struct value * value) static
References load_from_deref_entry_value(), load_from_ssa_entry_value(), and copy_entry::src.
Referenced by copy_prop_vars_block().