Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_conditional_discard.c File Reference
Handles optimization of lowering if (cond) discard to discard_if(cond).
#include "nir.h"
#include "nir_builder.h"
Functions
static bool nir_opt_conditional_discard_block (nir_builder *b, nir_block *block)
bool nir_opt_conditional_discard (nir_shader *shader)
Detailed Description
Handles optimization of lowering if (cond) discard to discard_if(cond).
Function Documentation
nir_opt_conditional_discard()
bool nir_opt_conditional_discard (nir_shader * shader)
References nir_builder::impl, nir_builder_init(), nir_foreach_block_safe, nir_foreach_function, and nir_opt_conditional_discard_block().
nir_opt_conditional_discard_block()
static bool nir_opt_conditional_discard_block (nir_builder * b, nir_block * block) static
References nir_block::cf_node, nir_if::cf_node, nir_if::condition, nir_builder::cursor, nir_intrinsic_instr::instr, instr, nir_block::instr_list, nir_intrinsic_instr::intrinsic, nir_before_cf_node(), nir_block_first_instr(), nir_cf_node_is_first(), nir_cf_node_next(), nir_cf_node_prev(), nir_cf_node_remove(), nir_foreach_instr_safe, nir_foreach_phi_src, nir_if_first_else_block(), nir_if_first_then_block(), nir_if_last_else_block(), nir_if_last_then_block(), nir_instr_insert_before_cf(), nir_instr_remove(), nir_instr_type_intrinsic, nir_instr_type_phi, nir_intrinsic_instr_create(), nir_src_copy(), nir_src_for_ssa(), nir_ssa_for_src(), nir_builder::shader, nir_intrinsic_instr::src, nir_instr::type, and nir_cf_node::type.
Referenced by nir_opt_conditional_discard().