Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_samplers.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "compiler/glsl/ir_uniform.h"
#include "main/compiler.h"
#include "main/mtypes.h"
#include "program/prog_parameter.h"
#include "program/program.h"
Functions
static void calc_sampler_offsets (nir_deref *tail, nir_tex_instr *instr, unsigned *array_elements, nir_ssa_def **indirect, nir_builder *b, unsigned *location)
static bool lower_sampler (nir_tex_instr *instr, const struct gl_shader_program *shader_program, gl_shader_stage stage, nir_builder *b)
static bool lower_impl (nir_function_impl *impl, const struct gl_shader_program *shader_program, gl_shader_stage stage)
bool nir_lower_samplers (nir_shader *shader, const struct gl_shader_program *shader_program)
Function Documentation
calc_sampler_offsets()
static void calc_sampler_offsets (nir_deref * tail, nir_tex_instr * instr, unsigned * array_elements, nir_ssa_def ** indirect, nir_builder * b, unsigned * location) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_struct::index, nir_deref_array::indirect, nir_tex_instr::instr, mul(), nir_deref_array_type_indirect, nir_deref_array_type_wildcard, nir_deref_type_array, nir_deref_type_struct, nir_imm_int(), nir_instr_rewrite_src(), NIR_SRC_INIT, nir_ssa_for_src(), nir_tex_instr::texture_index, and nir_deref::type.
Referenced by lower_sampler().
lower_impl()
static bool lower_impl (nir_function_impl * impl, const struct gl_shader_program * shader_program, gl_shader_stage stage) static
References instr, lower_sampler(), nir_builder_init(), nir_foreach_block, nir_foreach_instr, and nir_instr_type_tex.
Referenced by nir_lower_samplers().
lower_sampler()
static bool lower_sampler (nir_tex_instr * instr, const struct gl_shader_program * shader_program, gl_shader_stage stage, nir_builder * b) static
References gl_opaque_uniform_index::active, calc_sampler_offsets(), nir_builder::cursor, gl_shader_program::data, nir_variable::data, nir_deref_var::deref, gl_opaque_uniform_index::index, nir_tex_instr::instr, nir_variable::nir_variable_data::location, nir_before_instr(), nir_imm_int(), nir_instr_move_src(), nir_instr_rewrite_src(), nir_src_for_ssa(), nir_tex_src_sampler_offset, nir_tex_src_texture_offset, nir_tex_instr::num_srcs, gl_uniform_storage::opaque, nir_tex_instr::sampler, nir_tex_instr::sampler_index, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_tex_instr::texture, nir_tex_instr::texture_array_size, nir_tex_instr::texture_index, gl_shader_program_data::UniformStorage, and nir_deref_var::var.
Referenced by lower_impl().
nir_lower_samplers()
bool nir_lower_samplers (nir_shader * shader, const struct gl_shader_program * shader_program)
References lower_impl(), nir_foreach_function, and nir_shader::stage.