Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_control_flow.c File Reference
#include "nir_control_flow_private.h"
Functions
Control flow modification
These functions modify the control flow tree while keeping the control flow graph up-to-date.
The invariants respected are:
Each then statement, else statement, or loop body must have at least one control flow node.
Each if-statement and loop must have one basic block before it and one after.
Two basic blocks cannot be directly next to each other.
If a basic block has a jump instruction, there must be only one and it must be at the end of the block.
The purpose of the second one is so that we have places to insert code during GCM, as well as eliminating the possibility of critical edges.
static bool block_ends_in_jump (nir_block *block)
static void block_add_pred (nir_block *block, nir_block *pred)
static void block_remove_pred (nir_block *block, nir_block *pred)
static void link_blocks (nir_block *pred, nir_block *succ1, nir_block *succ2)
static void unlink_blocks (nir_block *pred, nir_block *succ)
static void unlink_block_successors (nir_block *block)
static void link_non_block_to_block (nir_cf_node *node, nir_block *block)
static void link_block_to_non_block (nir_block *block, nir_cf_node *node)
static void replace_successor (nir_block *block, nir_block *old_succ, nir_block *new_succ)
Replace a block's successor with a different one.
static nir_block * split_block_beginning (nir_block *block)
Takes a basic block and inserts a new empty basic block before it, making its predecessors point to the new block.
static void rewrite_phi_preds (nir_block *block, nir_block *old_pred, nir_block *new_pred)
static void insert_phi_undef (nir_block *block, nir_block *pred)
static void move_successors (nir_block *source, nir_block *dest)
Moves the successors of source to the successors of dest, leaving both successors of source NULL.
static void block_add_normal_succs (nir_block *block)
static nir_block * split_block_end (nir_block *block)
static nir_block * split_block_before_instr (nir_instr *instr)
static void split_block_cursor (nir_cursor cursor, nir_block **_before, nir_block **_after)
static void insert_non_block (nir_block *before, nir_cf_node *node, nir_block *after)
Inserts a non-basic block between two basic blocks and links them together.
static nir_loop * nearest_loop (nir_cf_node *node)
void nir_handle_add_jump (nir_block *block)
static void remove_phi_src (nir_block *block, nir_block *pred)
static void unlink_jump (nir_block *block, nir_jump_type type, bool add_normal_successors)
void nir_handle_remove_jump (nir_block *block, nir_jump_type type)
static void update_if_uses (nir_cf_node *node)
static void stitch_blocks (nir_block *before, nir_block *after)
Stitch two basic blocks together into one.
void nir_cf_node_insert (nir_cursor cursor, nir_cf_node *node)
NIR Control Flow Modification.
static bool replace_ssa_def_uses (nir_ssa_def *def, void *void_impl)
static void cleanup_cf_node (nir_cf_node *node, nir_function_impl *impl)
void nir_cf_extract (nir_cf_list *extracted, nir_cursor begin, nir_cursor end)
void nir_cf_reinsert (nir_cf_list *cf_list, nir_cursor cursor)
void nir_cf_delete (nir_cf_list *cf_list)
Function Documentation
block_add_normal_succs()
static void block_add_normal_succs (nir_block * block) static
References nir_block::cf_node, nir_function_impl::end_block, insert_phi_undef(), link_blocks(), exec_node::next, nir_cf_node_next(), nir_if_first_else_block(), nir_if_first_then_block(), nir_loop_first_block(), nir_cf_node::node, nir_cf_node::parent, and nir_cf_node::type.
Referenced by split_block_end(), and unlink_jump().
block_add_pred()
static void block_add_pred (nir_block * block, nir_block * pred) inline static
References nir_block::predecessors.
Referenced by link_blocks(), and replace_successor().
block_ends_in_jump()
static bool block_ends_in_jump (nir_block * block) static
References nir_block::instr_list, nir_block_last_instr(), nir_instr_type_jump, and nir_instr::type.
Referenced by link_non_block_to_block(), nir_cf_node_insert(), split_block_end(), and stitch_blocks().
block_remove_pred()
static void block_remove_pred (nir_block * block, nir_block * pred) inline static
References nir_block::predecessors.
Referenced by replace_successor(), and unlink_blocks().
cleanup_cf_node()
static void cleanup_cf_node (nir_cf_node * node, nir_function_impl * impl) static
References nir_loop::body, nir_function_impl::body, nir_if::condition, nir_if::else_list, foreach_list_typed, instr, nir_foreach_instr_safe, nir_foreach_ssa_def(), nir_instr_remove(), nir_instr_type_jump, replace_ssa_def_uses(), nir_if::then_list, nir_cf_node::type, unlink_jump(), and nir_src::use_link.
Referenced by nir_cf_delete().
insert_non_block()
static void insert_non_block (nir_block * before, nir_cf_node * node, nir_block * after) static
Inserts a non-basic block between two basic blocks and links them together.
References nir_block::cf_node, link_block_to_non_block(), link_non_block_to_block(), nir_cf_node::node, and nir_cf_node::parent.
Referenced by nir_cf_node_insert().
insert_phi_undef()
static void insert_phi_undef (nir_block * block, nir_block * pred) static
References nir_ssa_def::bit_size, nir_function_impl::body, nir_block::cf_node, nir_ssa_undef_instr::def, nir_phi_instr::dest, nir_ssa_undef_instr::instr, nir_phi_instr::instr, instr, nir_src::is_ssa, nir_cf_node_get_function(), nir_foreach_instr, nir_instr_insert_before_cf_list(), nir_instr_type_phi, nir_ssa_undef_instr_create(), nir_phi_src::node, nir_ssa_def::num_components, nir_src::parent_instr, nir_phi_src::pred, nir_phi_src::src, nir_phi_instr::srcs, nir_src::ssa, nir_dest::ssa, nir_src::use_link, and nir_ssa_def::uses.
Referenced by block_add_normal_succs().
link_block_to_non_block()
static void link_block_to_non_block (nir_block * block, nir_cf_node * node) static
References link_blocks(), nir_if_first_else_block(), nir_if_first_then_block(), nir_loop_first_block(), nir_cf_node::type, and unlink_block_successors().
Referenced by insert_non_block().
link_blocks()
static void link_blocks (nir_block * pred, nir_block * succ1, nir_block * succ2) static
References block_add_pred(), and nir_block::successors.
Referenced by block_add_normal_succs(), link_block_to_non_block(), link_non_block_to_block(), move_successors(), and nir_handle_add_jump().
link_non_block_to_block()
static void link_non_block_to_block (nir_cf_node * node, nir_block * block) static
References block_ends_in_jump(), link_blocks(), nir_if_last_else_block(), nir_if_last_then_block(), nir_cf_node::type, and unlink_block_successors().
Referenced by insert_non_block().
move_successors()
static void move_successors (nir_block * source, nir_block * dest) static
Moves the successors of source to the successors of dest, leaving both successors of source NULL.
References link_blocks(), rewrite_phi_preds(), nir_block::successors, unlink_block_successors(), and unlink_blocks().
Referenced by split_block_end(), and stitch_blocks().
nearest_loop()
static nir_loop* nearest_loop (nir_cf_node * node) static
References nir_cf_node::parent, and nir_cf_node::type.
Referenced by nir_handle_add_jump().
nir_cf_delete()
void nir_cf_delete (nir_cf_list * cf_list)
References cleanup_cf_node(), foreach_list_typed, nir_cf_list::impl, and nir_cf_list::list.
Referenced by complex_unroll(), lower_returns_in_block(), lower_returns_in_if(), nir_cf_node_remove(), remove_after_cf_node(), and simple_unroll().
nir_cf_extract()
void nir_cf_extract (nir_cf_list * extracted, nir_cursor begin, nir_cursor end)
References nir_block::cf_node, cf_node, nir_cf_list::impl, nir_cf_list::list, nir_cf_node_get_function(), nir_cf_node_next(), nir_cursors_equal(), nir_metadata_none, nir_metadata_preserve(), nir_cf_node::node, nir_cf_node::parent, split_block_cursor(), and stitch_blocks().
Referenced by complex_unroll(), lower_returns_in_block(), lower_returns_in_if(), nir_cf_list_extract(), nir_cf_node_remove(), opt_peel_loop_initial_if(), predicate_following(), remove_after_cf_node(), and simple_unroll().
nir_cf_node_insert()
void nir_cf_node_insert (nir_cursor cursor, nir_cf_node * node)
NIR Control Flow Modification.
This file contains various APIs that make modifying control flow in NIR, while maintaining the invariants checked by the validator, much easier. There are two parts to this:
Inserting control flow (ifs and loops) in various places, for creating IR either from scratch or as part of some lowering pass.
Taking existing pieces of the IR and either moving them around or deleting them.Control flow insertion. puts a control flow node where the cursor is
References block_ends_in_jump(), nir_block::cf_node, insert_non_block(), nir_handle_add_jump(), nir_cf_node::node, nir_cf_node::parent, split_block_cursor(), stitch_blocks(), nir_cf_node::type, and update_if_uses().
Referenced by nir_builder_cf_insert(), nir_cf_node_insert_after(), nir_cf_node_insert_before(), nir_cf_node_insert_begin(), nir_cf_node_insert_end(), and predicate_following().
nir_cf_reinsert()
void nir_cf_reinsert (nir_cf_list * cf_list, nir_cursor cursor)
References nir_block::cf_node, foreach_list_typed_safe, nir_cf_list::list, nir_cf_node_next(), nir_cf_node_prev(), nir_cf_node::node, nir_cf_node::parent, split_block_cursor(), and stitch_blocks().
Referenced by complex_unroll(), inline_functions_block(), lower_returns_in_if(), move_cf_list_into_loop_term(), opt_constant_if(), opt_peel_loop_initial_if(), predicate_following(), and simple_unroll().
nir_handle_add_jump()
void nir_handle_add_jump (nir_block * block)
References nir_block::cf_node, nir_loop::cf_node, nir_function_impl::end_block, instr, link_blocks(), nearest_loop(), nir_block_last_instr(), nir_cf_node_get_function(), nir_cf_node_next(), nir_jump_break, nir_jump_continue, nir_jump_return, nir_loop_first_block(), nir_metadata_none, nir_metadata_preserve(), nir_jump_instr::type, and unlink_block_successors().
Referenced by nir_cf_node_insert(), and nir_instr_insert().
nir_handle_remove_jump()
void nir_handle_remove_jump (nir_block * block, nir_jump_type type)
References nir_block::cf_node, nir_cf_node_get_function(), nir_metadata_none, nir_metadata_preserve(), and unlink_jump().
Referenced by nir_instr_remove().
remove_phi_src()
static void remove_phi_src (nir_block * block, nir_block * pred) static
References instr, nir_foreach_instr, nir_foreach_phi_src_safe, and nir_instr_type_phi.
Referenced by stitch_blocks(), and unlink_jump().
replace_ssa_def_uses()
static bool replace_ssa_def_uses (nir_ssa_def * def, void * void_impl) static
References nir_ssa_def::bit_size, nir_function_impl::body, nir_ssa_undef_instr::def, nir_ssa_undef_instr::instr, mem_ctx, nir_instr_insert_before_cf_list(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_undef_instr_create(), and nir_ssa_def::num_components.
Referenced by cleanup_cf_node().
replace_successor()
static void replace_successor (nir_block * block, nir_block * old_succ, nir_block * new_succ) static
Replace a block's successor with a different one.
References block_add_pred(), block_remove_pred(), and nir_block::successors.
Referenced by split_block_beginning().
rewrite_phi_preds()
static void rewrite_phi_preds (nir_block * block, nir_block * old_pred, nir_block * new_pred) static
References instr, nir_foreach_instr_safe, nir_foreach_phi_src, and nir_instr_type_phi.
Referenced by move_successors().
split_block_before_instr()
static nir_block* split_block_before_instr (nir_instr * instr) static
References nir_instr::block, nir_block::instr_list, nir_foreach_instr_safe, nir_instr_type_phi, split_block_beginning(), and nir_instr::type.
Referenced by split_block_cursor().
split_block_beginning()
static nir_block* split_block_beginning (nir_block * block) static
Takes a basic block and inserts a new empty basic block before it, making its predecessors point to the new block.
This essentially splits the block into an empty header and a body so that another non-block CF node can be inserted between the two. Note that this does not link the two basic blocks, so some kind of cleanup must be performed after this call.
References nir_block::cf_node, instr, nir_block::instr_list, nir_block_create(), nir_foreach_instr_safe, nir_instr_type_phi, nir_cf_node::node, nir_cf_node::parent, nir_block::predecessors, and replace_successor().
Referenced by split_block_before_instr(), and split_block_cursor().
split_block_cursor()
static void split_block_cursor (nir_cursor cursor, nir_block ** _before, nir_block ** _after) static
References nir_instr::block, nir_cursor::block, nir_cursor::instr, nir_cursor_after_block, nir_cursor_after_instr, nir_cursor_before_block, nir_cursor_before_instr, nir_instr_is_last(), nir_instr_next(), nir_cursor::option, split_block_before_instr(), split_block_beginning(), and split_block_end().
Referenced by nir_cf_extract(), nir_cf_node_insert(), and nir_cf_reinsert().
split_block_end()
static nir_block* split_block_end (nir_block * block) static
References block_add_normal_succs(), block_ends_in_jump(), nir_block::cf_node, move_successors(), nir_block_create(), nir_cf_node::node, and nir_cf_node::parent.
Referenced by split_block_cursor().
stitch_blocks()
static void stitch_blocks (nir_block * before, nir_block * after) static
Stitch two basic blocks together into one.
The aggregate must have the same predecessors as the first and the same successors as the second.
References block_ends_in_jump(), nir_block::cf_node, foreach_list_typed, instr, nir_block::instr_list, move_successors(), nir_cf_node::node, remove_phi_src(), nir_block::successors, and unlink_block_successors().
Referenced by nir_cf_extract(), nir_cf_node_insert(), and nir_cf_reinsert().
unlink_block_successors()
static void unlink_block_successors (nir_block * block) static
References nir_block::successors, and unlink_blocks().
Referenced by link_block_to_non_block(), link_non_block_to_block(), move_successors(), nir_handle_add_jump(), stitch_blocks(), and unlink_jump().
unlink_blocks()
static void unlink_blocks (nir_block * pred, nir_block * succ) static
References block_remove_pred(), and nir_block::successors.
Referenced by move_successors(), and unlink_block_successors().
unlink_jump()
static void unlink_jump (nir_block * block, nir_jump_type type, bool add_normal_successors) static
References block_add_normal_succs(), remove_phi_src(), nir_block::successors, and unlink_block_successors().
Referenced by cleanup_cf_node(), and nir_handle_remove_jump().
update_if_uses()
static void update_if_uses (nir_cf_node * node) static
References nir_if::condition, nir_register::if_uses, nir_ssa_def::if_uses, nir_src::is_ssa, nir_src::parent_if, nir_reg_src::reg, nir_src::reg, nir_src::ssa, nir_cf_node::type, and nir_src::use_link.
Referenced by nir_cf_node_insert().