Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_passthrough_edgeflags.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static void lower_impl (nir_function_impl *impl)
void nir_lower_passthrough_edgeflags (nir_shader *shader)
Function Documentation
lower_impl()
static void lower_impl (nir_function_impl * impl) static
References nir_function_impl::body, nir_builder::cursor, nir_variable::data, nir_function_impl::function, nir_variable::nir_variable_data::location, nir_before_cf_list(), nir_builder_init(), nir_load_var(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_store_var(), nir_var_shader_in, nir_var_shader_out, nir_variable_create(), locals_to_regs_state::shader, and nir_function::shader.
Referenced by nir_lower_passthrough_edgeflags().
nir_lower_passthrough_edgeflags()
void nir_lower_passthrough_edgeflags (nir_shader * shader)
References lower_impl(), and nir_shader_get_entrypoint().