Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_drawpixels.c File Reference
#include "nir.h"
#include "nir_builder.h"
Data Structures
struct lower_drawpixels_state
Functions
static nir_ssa_def * get_texcoord (lower_drawpixels_state *state)
static nir_variable * create_uniform (nir_shader *shader, const char *name, const int state_tokens[5])
static nir_ssa_def * get_scale (lower_drawpixels_state *state)
static nir_ssa_def * get_bias (lower_drawpixels_state *state)
static nir_ssa_def * get_texcoord_const (lower_drawpixels_state *state)
static void lower_color (lower_drawpixels_state *state, nir_intrinsic_instr *intr)
static void lower_texcoord (lower_drawpixels_state *state, nir_intrinsic_instr *intr)
static bool lower_drawpixels_block (lower_drawpixels_state *state, nir_block *block)
static void lower_drawpixels_impl (lower_drawpixels_state *state, nir_function_impl *impl)
void nir_lower_drawpixels (nir_shader *shader, const nir_lower_drawpixels_options *options)
Function Documentation
create_uniform()
static nir_variable* create_uniform (nir_shader * shader, const char * name, const int state_tokens[5]) static
References nir_var_uniform, nir_variable_create(), nir_variable::num_state_slots, nir_variable::state_slots, and nir_state_slot::tokens.
Referenced by get_bias(), get_scale(), and get_texcoord_const().
get_bias()
static nir_ssa_def* get_bias (lower_drawpixels_state * state) static
References lower_drawpixels_state::b, lower_drawpixels_state::bias, nir_lower_drawpixels_options::bias_state_tokens, create_uniform(), nir_load_var(), lower_drawpixels_state::options, and lower_drawpixels_state::shader.
Referenced by lower_color().
get_scale()
static nir_ssa_def* get_scale (lower_drawpixels_state * state) static
References lower_drawpixels_state::b, create_uniform(), nir_load_var(), lower_drawpixels_state::options, lower_drawpixels_state::scale, nir_lower_drawpixels_options::scale_state_tokens, and lower_drawpixels_state::shader.
Referenced by lower_color().
get_texcoord()
static nir_ssa_def* get_texcoord (lower_drawpixels_state * state) static
References lower_drawpixels_state::b, nir_variable::data, nir_shader::inputs, nir_variable::nir_variable_data::location, nir_foreach_variable, nir_load_var(), nir_var_shader_in, nir_variable_create(), lower_drawpixels_state::shader, and lower_drawpixels_state::texcoord.
Referenced by lower_color().
get_texcoord_const()
static nir_ssa_def* get_texcoord_const (lower_drawpixels_state * state) static
References lower_drawpixels_state::b, lower_drawpixels_state::bias, create_uniform(), nir_load_var(), lower_drawpixels_state::options, lower_drawpixels_state::shader, and nir_lower_drawpixels_options::texcoord_state_tokens.
Referenced by lower_texcoord().
lower_color()
static void lower_color (lower_drawpixels_state * state, nir_intrinsic_instr * intr) static
References lower_drawpixels_state::b, nir_tex_instr::coord_components, nir_builder::cursor, nir_intrinsic_instr::dest, nir_tex_instr::dest, nir_tex_instr::dest_type, nir_lower_drawpixels_options::drawpix_sampler, get_bias(), get_scale(), get_texcoord(), nir_intrinsic_instr::instr, nir_tex_instr::instr, nir_dest::is_ssa, nir_before_instr(), nir_builder_instr_insert(), nir_channel(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_swizzle(), nir_tex_instr_create(), nir_tex_src_coord, nir_texop_tex, nir_type_float, nir_tex_instr::op, lower_drawpixels_state::options, nir_lower_drawpixels_options::pixel_maps, nir_lower_drawpixels_options::pixelmap_sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_lower_drawpixels_options::scale_and_bias, lower_drawpixels_state::shader, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_dest::ssa, and nir_tex_instr::texture_index.
Referenced by lower_drawpixels_block().
lower_drawpixels_block()
static bool lower_drawpixels_block (lower_drawpixels_state * state, nir_block * block) static
References nir_deref::child, nir_variable::data, nir_deref_var::deref, instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::location, lower_color(), lower_texcoord(), nir_foreach_instr_safe, nir_instr_type_intrinsic, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_drawpixels_impl().
lower_drawpixels_impl()
static void lower_drawpixels_impl (lower_drawpixels_state * state, nir_function_impl * impl) static
References lower_drawpixels_state::b, lower_drawpixels_block(), nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_drawpixels().
lower_texcoord()
static void lower_texcoord (lower_drawpixels_state * state, nir_intrinsic_instr * intr) static
References lower_drawpixels_state::b, nir_builder::cursor, nir_intrinsic_instr::dest, get_texcoord_const(), nir_intrinsic_instr::instr, nir_before_instr(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_dest::ssa.
Referenced by lower_drawpixels_block().
nir_lower_drawpixels()
void nir_lower_drawpixels (nir_shader * shader, const nir_lower_drawpixels_options * options)
References lower_drawpixels_impl(), nir_foreach_function, nir_builder::shader, and nir_shader::stage.