Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_inline_functions.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "nir_control_flow.h"
Functions
static bool inline_function_impl (nir_function_impl *impl, struct set *inlined)
static void convert_deref_to_param_deref (nir_instr *instr, nir_deref_var **deref, nir_call_instr *call)
static void rewrite_param_derefs (nir_instr *instr, nir_call_instr *call)
static void lower_param_to_local (nir_variable *param, nir_function_impl *impl, bool write)
static bool lower_params_to_locals_block (nir_block *block, nir_function_impl *impl)
static bool inline_functions_block (nir_block *block, nir_builder *b, struct set *inlined)
bool nir_inline_functions (nir_shader *shader)
Function Documentation
convert_deref_to_param_deref()
static void convert_deref_to_param_deref (nir_instr * instr, nir_deref_var ** deref, nir_call_instr * call) static
References nir_deref::child, nir_deref_var::deref, nir_deref_var_clone(), nir_var_param, nir_call_instr::params, and nir_call_instr::return_deref.
Referenced by rewrite_param_derefs().
inline_function_impl()
static bool inline_function_impl (nir_function_impl * impl, struct set * inlined) static
References inline_functions_block(), nir_builder_init(), nir_foreach_block_safe, nir_index_local_regs(), nir_index_ssa_defs(), nir_metadata_none, and nir_metadata_preserve().
Referenced by inline_functions_block(), and nir_inline_functions().
inline_functions_block()
static bool inline_functions_block (nir_block * block, nir_builder * b, struct set * inlined) static
References nir_function_impl::body, nir_call_instr::callee, nir_builder::cursor, nir_variable::data, nir_function_impl::function, nir_builder::impl, nir_function::impl, inline_function_impl(), nir_call_instr::instr, instr, nir_function_impl::locals, lower_params_to_locals_block(), nir_variable::nir_variable_data::mode, nir_before_instr(), nir_cf_list_extract(), nir_cf_reinsert(), nir_copy_deref_var(), nir_deref_var_create(), nir_foreach_block, nir_foreach_instr, nir_foreach_instr_safe, nir_function_impl_clone(), nir_instr_remove(), nir_instr_type_call, nir_parameter_in, nir_parameter_out, nir_var_local, nir_call_instr::num_params, nir_function_impl::num_params, nir_parameter::param_type, nir_call_instr::params, nir_function_impl::params, nir_function::params, nir_function_impl::registers, nir_call_instr::return_deref, nir_function::return_type, nir_function_impl::return_var, rewrite_param_derefs(), and nir_builder::shader.
Referenced by inline_function_impl().
lower_param_to_local()
static void lower_param_to_local (nir_variable * param, nir_function_impl * impl, bool write) static
References nir_variable::data, nir_function_impl::function, nir_function_impl::locals, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_parameter_in, nir_parameter_out, nir_var_local, nir_var_param, nir_variable::node, nir_function_impl::num_params, nir_parameter::param_type, and nir_function::params.
Referenced by lower_params_to_locals_block().
lower_params_to_locals_block()
static bool lower_params_to_locals_block (nir_block * block, nir_function_impl * impl) static
References instr, nir_intrinsic_instr::intrinsic, lower_param_to_local(), nir_foreach_instr, nir_instr_type_intrinsic, nir_intrinsic_infos, nir_intrinsic_info::num_variables, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by inline_functions_block().
nir_inline_functions()
bool nir_inline_functions (nir_shader * shader)
References inline_function_impl(), and nir_foreach_function.
rewrite_param_derefs()
static void rewrite_param_derefs (nir_instr * instr, nir_call_instr * call) static
References convert_deref_to_param_deref(), nir_tex_instr::instr, nir_intrinsic_instr::intrinsic, nir_instr_type_intrinsic, nir_instr_type_tex, nir_intrinsic_infos, nir_intrinsic_info::num_variables, nir_tex_instr::sampler, nir_tex_instr::texture, nir_instr::type, and nir_intrinsic_instr::variables.
Referenced by inline_functions_block().