Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_vec_to_movs.c File Reference
#include "nir.h"
Functions
static bool src_matches_dest_reg (nir_dest *dest, nir_src *src)
static unsigned insert_mov (nir_alu_instr *vec, unsigned start_idx, nir_shader *shader)
For a given starting writemask channel and corresponding source index in the vec instruction, insert a MOV to the vec instruction's dest of all the writemask channels that get read from the same src reg.
static bool has_replicated_dest (nir_alu_instr *alu)
static unsigned try_coalesce (nir_alu_instr *vec, unsigned start_idx)
static bool lower_vec_to_movs_block (nir_block *block, nir_function_impl *impl)
static bool nir_lower_vec_to_movs_impl (nir_function_impl *impl)
bool nir_lower_vec_to_movs (nir_shader *shader)
Function Documentation
has_replicated_dest()
static bool has_replicated_dest (nir_alu_instr * alu) static
References nir_alu_instr::op.
Referenced by try_coalesce().
insert_mov()
static unsigned insert_mov (nir_alu_instr * vec, unsigned start_idx, nir_shader * shader) static
For a given starting writemask channel and corresponding source index in the vec instruction, insert a MOV to the vec instruction's dest of all the writemask channels that get read from the same src reg.
Returns the writemask of our MOV, so the parent loop calling this knows which ones have been processed.
References nir_alu_src::abs, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, nir_alu_src::negate, nir_alu_dest_copy(), nir_alu_instr_create(), nir_alu_src_copy(), nir_instr_insert_before(), nir_op_infos, nir_srcs_equal(), nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_src::src, nir_alu_instr::src, src_matches_dest_reg(), nir_alu_src::swizzle, and nir_alu_dest::write_mask.
Referenced by lower_vec_to_movs_block().
lower_vec_to_movs_block()
static bool lower_vec_to_movs_block (nir_block * block, nir_function_impl * impl) static
References nir_register::bit_size, nir_ssa_def::bit_size, nir_alu_dest::dest, nir_alu_instr::dest, nir_function_impl::function, insert_mov(), nir_alu_instr::instr, instr, nir_dest::is_ssa, nir_dest_for_reg(), nir_foreach_instr_safe, nir_instr_remove(), nir_instr_rewrite_dest(), nir_instr_type_alu, nir_local_reg_create(), nir_src_for_reg(), nir_ssa_def_rewrite_uses(), nir_register::num_components, nir_ssa_def::num_components, nir_alu_instr::op, nir_function::shader, nir_alu_src::src, nir_alu_instr::src, src_matches_dest_reg(), nir_dest::ssa, try_coalesce(), and nir_alu_dest::write_mask.
Referenced by nir_lower_vec_to_movs_impl().
nir_lower_vec_to_movs()
bool nir_lower_vec_to_movs (nir_shader * shader)
References nir_foreach_function, and nir_lower_vec_to_movs_impl().
nir_lower_vec_to_movs_impl()
static bool nir_lower_vec_to_movs_impl (nir_function_impl * impl) static
References lower_vec_to_movs_block(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_vec_to_movs().
src_matches_dest_reg()
static bool src_matches_dest_reg (nir_dest * dest, nir_src * src) static
References nir_reg_src::base_offset, nir_reg_dest::base_offset, nir_reg_src::indirect, nir_reg_dest::indirect, nir_src::is_ssa, nir_dest::is_ssa, nir_reg_src::reg, nir_reg_dest::reg, nir_src::reg, and nir_dest::reg.
Referenced by insert_mov(), and lower_vec_to_movs_block().
try_coalesce()
static unsigned try_coalesce (nir_alu_instr * vec, unsigned start_idx) static
References nir_alu_src::abs, nir_alu_dest::dest, nir_alu_instr::dest, exec_node_data, for(), has_replicated_dest(), nir_ssa_def::if_uses, nir_op_info::input_sizes, nir_alu_instr::instr, nir_src::is_ssa, nir_alu_src::negate, nir_foreach_use, nir_instr_rewrite_dest(), nir_instr_rewrite_src(), nir_instr_type_alu, nir_op_infos, NIR_SRC_INIT, nir_op_info::num_inputs, nir_alu_instr::op, nir_op_info::output_size, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_alu_src::swizzle, nir_instr::type, and nir_alu_dest::write_mask.
Referenced by lower_vec_to_movs_block().