Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_instr_set.h File Reference
#include "nir.h"
Functions
struct set * nir_instr_set_create (void *mem_ctx)
This file defines functions for creating, destroying, and manipulating an "instruction set," which is an abstraction for finding duplicate instructions using a hash set.
void nir_instr_set_destroy (struct set *instr_set)
Destroys an instruction set.
bool nir_instr_set_add_or_rewrite (struct set *instr_set, nir_instr *instr)
Adds an instruction to an instruction set if it doesn't exist, or if it does already exist, rewrites all uses of it to point to the other already-inserted instruction.
void nir_instr_set_remove (struct set *instr_set, nir_instr *instr)
Removes an instruction from an instruction set, so that other instructions won't be merged with it.
Function Documentation
nir_instr_set_add_or_rewrite()
bool nir_instr_set_add_or_rewrite (struct set * instr_set, nir_instr * instr)
Adds an instruction to an instruction set if it doesn't exist, or if it does already exist, rewrites all uses of it to point to the other already-inserted instruction.
Returns 'true' if the uses of the instruction were rewritten.
References instr_can_rewrite(), nir_instr_get_dest_ssa_def(), nir_instr_type_alu, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_instr::type.
Referenced by cse_block(), and opt_gcm_impl().
nir_instr_set_create()
struct set* nir_instr_set_create (void * mem_ctx)
This file defines functions for creating, destroying, and manipulating an "instruction set," which is an abstraction for finding duplicate instructions using a hash set.
Note that the question of whether an instruction is actually a duplicate (e.g. whether it has any side effects) is handled transparently. The user can pass any instruction to nir_instr_set_add_or_rewrite() and nir_instr_set_remove(), and if the instruction isn't safe to rewrite or isn't supported, it's silently removed.Creates an instruction set, using a given ralloc mem_ctx
References cmp_func(), and hash_instr().
Referenced by nir_opt_cse_impl(), and opt_gcm_impl().
nir_instr_set_destroy()
void nir_instr_set_destroy (struct set * instr_set)
Destroys an instruction set.
Referenced by nir_opt_cse_impl(), and opt_gcm_impl().
nir_instr_set_remove()
void nir_instr_set_remove (struct set * instr_set, nir_instr * instr)
Removes an instruction from an instruction set, so that other instructions won't be merged with it.
References instr_can_rewrite().
Referenced by cse_block().