Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_io.c File Reference
#include "nir.h"
#include "nir_builder.h"
Data Structures
struct lower_io_state
Macros
#define OP(O) case nir_intrinsic_var_##O: op = nir_intrinsic_shared_##O; break;
Functions
void nir_assign_var_locations (struct exec_list *var_list, unsigned *size, int(*type_size)(const struct glsl_type *))
bool nir_is_per_vertex_io (nir_variable *var, gl_shader_stage stage)
Return true if the given variable is a per-vertex input/output array.
static nir_ssa_def * get_io_offset (nir_builder *b, nir_deref_var *deref, nir_ssa_def **vertex_index, int(*type_size)(const struct glsl_type *), unsigned *component)
static nir_intrinsic_instr * lower_load (nir_intrinsic_instr *intrin, struct lower_io_state *state, nir_ssa_def *vertex_index, nir_ssa_def *offset, unsigned component)
static nir_intrinsic_instr * lower_store (nir_intrinsic_instr *intrin, struct lower_io_state *state, nir_ssa_def *vertex_index, nir_ssa_def *offset, unsigned component)
static nir_intrinsic_instr * lower_atomic (nir_intrinsic_instr *intrin, struct lower_io_state *state, nir_ssa_def *offset)
static nir_intrinsic_instr * lower_interpolate_at (nir_intrinsic_instr *intrin, struct lower_io_state *state, nir_ssa_def *offset, unsigned component)
static bool nir_lower_io_block (nir_block *block, struct lower_io_state *state)
static bool nir_lower_io_impl (nir_function_impl *impl, nir_variable_mode modes, int(*type_size)(const struct glsl_type *), nir_lower_io_options options)
bool nir_lower_io (nir_shader *shader, nir_variable_mode modes, int(*type_size)(const struct glsl_type *), nir_lower_io_options options)
nir_src * nir_get_io_offset_src (nir_intrinsic_instr *instr)
Return the offset soruce for a load/store intrinsic.
nir_src * nir_get_io_vertex_index_src (nir_intrinsic_instr *instr)
Return the vertex index source for a load/store per_vertex intrinsic.
Macro Definition Documentation
OP
#define OP (O) case nir_intrinsic_var_##O: op = nir_intrinsic_shared_##O; break;
Referenced by lower_atomic().
Function Documentation
get_io_offset()
static nir_ssa_def* get_io_offset (nir_builder * b, nir_deref_var * deref, nir_ssa_def ** vertex_index, int(*)(const struct glsl_type *) type_size, unsigned * component) static
References nir_deref_array::base_offset, nir_deref::child, nir_variable::nir_variable_data::compact, nir_variable::data, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_struct::index, nir_deref_array::indirect, mul(), nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_type_array, nir_deref_type_struct, nir_imm_int(), nir_ssa_for_src(), nir_variable::type, nir_deref::type, lower_io_state::type_size, and nir_deref_var::var.
Referenced by nir_lower_io_block().
lower_atomic()
static nir_intrinsic_instr* lower_atomic (nir_intrinsic_instr * intrin, struct lower_io_state * state, nir_ssa_def * offset) static
References lower_io_state::builder, nir_variable::data, nir_variable::nir_variable_data::driver_location, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::mode, nir_intrinsic_infos, nir_intrinsic_instr_create(), nir_src_copy(), nir_src_for_ssa(), nir_var_shared, nir_intrinsic_info::num_srcs, OP, nir_builder::shader, nir_intrinsic_instr::src, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_lower_io_block().
lower_interpolate_at()
static nir_intrinsic_instr* lower_interpolate_at (nir_intrinsic_instr * intrin, struct lower_io_state * state, nir_ssa_def * offset, unsigned component) static
References lower_io_state::builder, nir_variable::data, nir_intrinsic_instr::dest, nir_variable::nir_variable_data::driver_location, nir_intrinsic_instr::instr, nir_variable::nir_variable_data::interpolation, nir_intrinsic_instr::intrinsic, lower_load(), nir_variable::nir_variable_data::mode, nir_builder_instr_insert(), nir_intrinsic_instr_create(), nir_lower_io_force_sample_interpolation, nir_src_copy(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_var_shader_in, nir_intrinsic_instr::num_components, lower_io_state::options, nir_builder::shader, nir_intrinsic_instr::src, nir_dest::ssa, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_lower_io_block().
lower_load()
static nir_intrinsic_instr* lower_load (nir_intrinsic_instr * intrin, struct lower_io_state * state, nir_ssa_def * vertex_index, nir_ssa_def * offset, unsigned component) static
References lower_io_state::builder, nir_variable::nir_variable_data::centroid, nir_variable::data, nir_variable::nir_variable_data::driver_location, nir_variable::nir_variable_data::interpolation, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::mode, nir_intrinsic_instr_create(), nir_load_barycentric(), nir_lower_io_force_sample_interpolation, nir_src_for_ssa(), nir_var_shader_in, nir_var_shader_out, nir_var_shared, nir_var_uniform, nir_intrinsic_instr::num_components, lower_io_state::options, nir_shader::options, nir_variable::nir_variable_data::sample, nir_builder::shader, nir_intrinsic_instr::src, nir_shader::stage, nir_variable::type, lower_io_state::type_size, nir_shader_compiler_options::use_interpolated_input_intrinsics, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_interpolate_at(), and nir_lower_io_block().
lower_store()
static nir_intrinsic_instr* lower_store (nir_intrinsic_instr * intrin, struct lower_io_state * state, nir_ssa_def * vertex_index, nir_ssa_def * offset, unsigned component) static
References lower_io_state::builder, nir_variable::data, nir_variable::nir_variable_data::driver_location, nir_variable::nir_variable_data::mode, nir_intrinsic_instr_create(), nir_src_copy(), nir_src_for_ssa(), nir_var_shader_out, nir_var_shared, nir_intrinsic_instr::num_components, nir_builder::shader, nir_intrinsic_instr::src, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_lower_io_block().
nir_assign_var_locations()
void nir_assign_var_locations (struct exec_list * var_list, unsigned * size, int(*)(const struct glsl_type *) type_size)
References nir_foreach_variable, nir_var_shader_storage, nir_var_uniform, and lower_io_state::type_size.
nir_get_io_offset_src()
nir_src* nir_get_io_offset_src (nir_intrinsic_instr * instr)
Return the offset soruce for a load/store intrinsic.
References nir_intrinsic_instr::intrinsic, and nir_intrinsic_instr::src.
nir_get_io_vertex_index_src()
nir_src* nir_get_io_vertex_index_src (nir_intrinsic_instr * instr)
Return the vertex index source for a load/store per_vertex intrinsic.
References nir_intrinsic_instr::intrinsic, and nir_intrinsic_instr::src.
nir_is_per_vertex_io()
bool nir_is_per_vertex_io (nir_variable * var, gl_shader_stage stage)
Return true if the given variable is a per-vertex input/output array.
(such as geometry shader inputs).
References nir_variable::data, nir_variable::nir_variable_data::mode, nir_var_shader_in, nir_var_shader_out, nir_variable::nir_variable_data::patch, and nir_variable::type.
Referenced by get_unwrapped_array_length(), mark_whole_variable(), nir_lower_io_block(), try_mask_partial_io(), and update_type().
nir_lower_io()
bool nir_lower_io (nir_shader * shader, nir_variable_mode modes, int(*)(const struct glsl_type *) type_size, nir_lower_io_options options)
References nir_foreach_function, nir_lower_io_impl(), and lower_io_state::type_size.
nir_lower_io_block()
static bool nir_lower_io_block (nir_block * block, struct lower_io_state * state) static
References nir_ssa_def::bit_size, lower_io_state::builder, nir_builder::cursor, nir_variable::data, nir_intrinsic_instr::dest, get_io_offset(), nir_intrinsic_info::has_dest, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, nir_variable::nir_variable_data::location_frac, lower_atomic(), lower_interpolate_at(), lower_load(), lower_store(), nir_variable::nir_variable_data::mode, lower_io_state::modes, nir_before_instr(), nir_dest_copy(), nir_foreach_instr_safe, nir_instr_insert_before(), nir_instr_remove(), nir_instr_type_intrinsic, nir_intrinsic_infos, nir_is_per_vertex_io(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_var_shader_in, nir_var_shader_out, nir_var_shared, nir_var_uniform, nir_ssa_def::num_components, lower_io_state::options, nir_shader::options, nir_builder::shader, nir_dest::ssa, nir_shader::stage, lower_io_state::type_size, nir_shader_compiler_options::use_interpolated_input_intrinsics, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_lower_io_impl().
nir_lower_io_impl()
static bool nir_lower_io_impl (nir_function_impl * impl, nir_variable_mode modes, int(*)(const struct glsl_type *) type_size, nir_lower_io_options options) static
References lower_io_state::builder, lower_io_state::modes, nir_builder_init(), nir_foreach_block, nir_lower_io_block(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), lower_io_state::options, and lower_io_state::type_size.
Referenced by nir_lower_io().