Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_if.c File Reference
#include "nir.h"
#include "nir_control_flow.h"
Functions
static bool opt_peel_loop_initial_if (nir_loop *loop)
This optimization detects if statements at the tops of loops where the condition is a phi node of two constants and moves half of the if to above the loop and the other half of the if to the end of the loop.
static bool opt_if_cf_list (struct exec_list *cf_list)
bool nir_opt_if (nir_shader *shader)
Function Documentation
nir_opt_if()
bool nir_opt_if (nir_shader * shader)
References nir_foreach_function, nir_lower_regs_to_ssa_impl(), nir_metadata_none, nir_metadata_preserve(), and opt_if_cf_list().
opt_if_cf_list()
static bool opt_if_cf_list (struct exec_list * cf_list) static
References nir_loop::body, cf_node, nir_if::else_list, foreach_list_typed, opt_peel_loop_initial_if(), and nir_if::then_list.
Referenced by nir_opt_if().
opt_peel_loop_initial_if()
static bool opt_peel_loop_initial_if (nir_loop * loop) static
This optimization detects if statements at the tops of loops where the condition is a phi node of two constants and moves half of the if to above the loop and the other half of the if to the end of the loop.
A simple for loop "for (int i = 0; i < 4; i++)", when run through the SPIR-V front-end, ends up looking something like this:
vec1 32 ssa_0 = load_const (0x00000000) vec1 32 ssa_1 = load_const (0xffffffff) loop { block block_1: vec1 32 ssa_2 = phi block_0: ssa_0, block_7: ssa_5 vec1 32 ssa_3 = phi block_0: ssa_0, block_7: ssa_1 if ssa_2 { block block_2: vec1 32 ssa_4 = load_const (0x00000001) vec1 32 ssa_5 = iadd ssa_2, ssa_4 } else { block block_3: } block block_4: vec1 32 ssa_6 = load_const (0x00000004) vec1 32 ssa_7 = ilt ssa_5, ssa_6 if ssa_7 { block block_5: } else { block block_6: break } block block_7: }
This turns it into something like this:
// Stuff from block 1 // Stuff from block 3 loop { block block_1: vec1 32 ssa_3 = phi block_0: ssa_0, block_7: ssa_1 vec1 32 ssa_6 = load_const (0x00000004) vec1 32 ssa_7 = ilt ssa_5, ssa_6 if ssa_7 { block block_5: } else { block block_6: break } block block_7: // Stuff from block 1 // Stuff from block 2 vec1 32 ssa_4 = load_const (0x00000001) vec1 32 ssa_5 = iadd ssa_2, ssa_4 }
References nir_instr::block, nir_block::cf_node, nir_if::cf_node, nir_loop::cf_node, cf_node, nir_if::condition, nir_if::else_list, foreach_list_typed, nir_src::is_ssa, nir_after_block(), nir_after_block_before_jump(), nir_after_cf_list(), nir_before_block(), nir_before_cf_list(), nir_before_cf_node(), nir_block_last_instr(), nir_cf_extract(), nir_cf_list_clone(), nir_cf_node_next(), nir_cf_node_prev(), nir_cf_node_remove(), nir_cf_reinsert(), nir_convert_loop_to_lcssa(), nir_foreach_block_in_cf_node, nir_foreach_phi_src, nir_instr_type_jump, nir_instr_type_phi, nir_loop_first_block(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_src_as_const_value(), nir_ssa_def::parent_instr, nir_block::predecessors, nir_phi_instr::srcs, nir_src::ssa, nir_if::then_list, nir_instr::type, nir_cf_node::type, and nir_const_value::u32.
Referenced by opt_if_cf_list().