Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_sweep.c File Reference
The nir_sweep() pass performs a mark and sweep pass over a nir_shader's associated memory - anything still connected to the program will be kept, and any dead memory we dropped on the floor will be freed.
#include "nir.h"
Macros
#define steal_list(mem_ctx, type, list) foreach_list_typed(type, obj, node, list) { ralloc_steal(mem_ctx, obj); }
Functions
static void sweep_cf_node (nir_shader *nir, nir_cf_node *cf_node)
static bool sweep_src_indirect (nir_src *src, void *nir)
static bool sweep_dest_indirect (nir_dest *dest, void *nir)
static void sweep_block (nir_shader *nir, nir_block *block)
static void sweep_if (nir_shader *nir, nir_if *iff)
static void sweep_loop (nir_shader *nir, nir_loop *loop)
static void sweep_impl (nir_shader *nir, nir_function_impl *impl)
static void sweep_function (nir_shader *nir, nir_function *f)
void nir_sweep (nir_shader *nir)
Detailed Description
The nir_sweep() pass performs a mark and sweep pass over a nir_shader's associated memory - anything still connected to the program will be kept, and any dead memory we dropped on the floor will be freed.
The expectation is that drivers should call this when finished compiling the shader (after any optimization, lowering, and so on). However, it's also fine to call it earlier, and even many times, trading CPU cycles for memory savings.
Macro Definition Documentation
steal_list
#define steal_list (mem_ctx, type, list) foreach_list_typed(type, obj, node, list) { ralloc_steal(mem_ctx, obj); }
Referenced by nir_sweep(), and sweep_impl().
Function Documentation
nir_sweep()
void nir_sweep (nir_shader * nir)
References foreach_list_typed, nir_shader::functions, nir_shader::globals, nir_shader::info, nir_shader::inputs, nir_shader::outputs, nir_shader::registers, nir_shader::shared, steal_list, sweep_function(), nir_shader::system_values, and nir_shader::uniforms.
sweep_block()
static void sweep_block (nir_shader * nir, nir_block * block) static
References instr, nir_foreach_dest(), nir_foreach_instr, nir_foreach_src(), sweep_dest_indirect(), and sweep_src_indirect().
Referenced by sweep_cf_node(), and sweep_impl().
sweep_cf_node()
static void sweep_cf_node (nir_shader * nir, nir_cf_node * cf_node) static
References sweep_block(), sweep_if(), sweep_loop(), and nir_cf_node::type.
Referenced by sweep_if(), sweep_impl(), and sweep_loop().
sweep_dest_indirect()
static bool sweep_dest_indirect (nir_dest * dest, void * nir) static
References nir_reg_dest::indirect, nir_dest::is_ssa, and nir_dest::reg.
Referenced by sweep_block().
sweep_function()
static void sweep_function (nir_shader * nir, nir_function * f) static
References nir_function::impl, nir_function::params, and sweep_impl().
Referenced by nir_sweep().
sweep_if()
static void sweep_if (nir_shader * nir, nir_if * iff) static
References cf_node, nir_if::else_list, foreach_list_typed, sweep_cf_node(), and nir_if::then_list.
Referenced by sweep_cf_node().
sweep_impl()
static void sweep_impl (nir_shader * nir, nir_function_impl * impl) static
References nir_function_impl::body, cf_node, nir_function_impl::end_block, foreach_list_typed, nir_function_impl::locals, nir_metadata_none, nir_metadata_preserve(), nir_function_impl::num_params, nir_function_impl::params, nir_function_impl::registers, nir_function_impl::return_var, steal_list, sweep_block(), and sweep_cf_node().
Referenced by sweep_function().
sweep_loop()
static void sweep_loop (nir_shader * nir, nir_loop * loop) static
References nir_loop::body, cf_node, foreach_list_typed, and sweep_cf_node().
Referenced by sweep_cf_node().
sweep_src_indirect()
static bool sweep_src_indirect (nir_src * src, void * nir) static
References nir_reg_src::indirect, nir_src::is_ssa, and nir_src::reg.
Referenced by sweep_block().