Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_control_flow_private.h File Reference
#include "nir_control_flow.h"
Functions
void nir_handle_add_jump (nir_block *block)
void nir_handle_remove_jump (nir_block *block, nir_jump_type type)
Function Documentation
nir_handle_add_jump()
void nir_handle_add_jump (nir_block * block)
References nir_block::cf_node, nir_loop::cf_node, nir_function_impl::end_block, instr, link_blocks(), nearest_loop(), nir_block_last_instr(), nir_cf_node_get_function(), nir_cf_node_next(), nir_jump_break, nir_jump_continue, nir_jump_return, nir_loop_first_block(), nir_metadata_none, nir_metadata_preserve(), nir_jump_instr::type, and unlink_block_successors().
Referenced by nir_cf_node_insert(), and nir_instr_insert().
nir_handle_remove_jump()
void nir_handle_remove_jump (nir_block * block, nir_jump_type type)
References nir_block::cf_node, nir_cf_node_get_function(), nir_metadata_none, nir_metadata_preserve(), and unlink_jump().
Referenced by nir_instr_remove().