Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_from_ssa.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "nir_vla.h"
Data Structures
struct from_ssa_state
struct merge_node
struct merge_set
struct ssa_def_to_reg_state
Typedefs
typedef struct merge_set merge_set
Functions
static bool ssa_def_dominates (nir_ssa_def *a, nir_ssa_def *b)
static merge_node * get_merge_node (nir_ssa_def *def, struct from_ssa_state *state)
static bool merge_nodes_interfere (merge_node *a, merge_node *b)
static merge_set * merge_merge_sets (merge_set *a, merge_set *b)
static bool merge_sets_interfere (merge_set *a, merge_set *b)
static bool add_parallel_copy_to_end_of_block (nir_block *block, void *dead_ctx)
static nir_parallel_copy_instr * get_parallel_copy_at_end_of_block (nir_block *block)
static bool isolate_phi_nodes_block (nir_block *block, void *dead_ctx)
Isolate phi nodes with parallel copies.
static bool coalesce_phi_nodes_block (nir_block *block, struct from_ssa_state *state)
static void aggressive_coalesce_parallel_copy (nir_parallel_copy_instr *pcopy, struct from_ssa_state *state)
static bool aggressive_coalesce_block (nir_block *block, struct from_ssa_state *state)
static nir_register * create_reg_for_ssa_def (nir_ssa_def *def, nir_function_impl *impl)
static bool rewrite_ssa_def (nir_ssa_def *def, void *void_state)
static void resolve_registers_block (nir_block *block, struct from_ssa_state *state)
static void emit_copy (nir_builder *b, nir_src src, nir_src dest_src)
static void resolve_parallel_copy (nir_parallel_copy_instr *pcopy, struct from_ssa_state *state)
static bool resolve_parallel_copies_block (nir_block *block, struct from_ssa_state *state)
static bool nir_convert_from_ssa_impl (nir_function_impl *impl, bool phi_webs_only)
bool nir_convert_from_ssa (nir_shader *shader, bool phi_webs_only)
static void place_phi_read (nir_shader *shader, nir_register *reg, nir_ssa_def *def, nir_block *block)
bool nir_lower_phis_to_regs_block (nir_block *block)
Lower all of the phi nodes in a block to imovs to and from a register.
static bool dest_replace_ssa_with_reg (nir_dest *dest, void *void_state)
bool nir_lower_ssa_defs_to_regs_block (nir_block *block)
Lower all of the SSA defs in a block to registers.
Typedef Documentation
merge_set
typedef struct merge_set merge_set
Function Documentation
add_parallel_copy_to_end_of_block()
static bool add_parallel_copy_to_end_of_block (nir_block * block, void * dead_ctx) static
References from_ssa_state::instr, nir_parallel_copy_instr::instr, nir_after_block_before_jump(), nir_block_first_instr(), nir_instr_insert(), nir_instr_type_phi, nir_parallel_copy_instr_create(), nir_block::successors, and nir_instr::type.
Referenced by nir_convert_from_ssa_impl().
aggressive_coalesce_block()
static bool aggressive_coalesce_block (nir_block * block, struct from_ssa_state * state) static
References aggressive_coalesce_parallel_copy(), get_parallel_copy_at_end_of_block(), from_ssa_state::instr, nir_foreach_instr, nir_instr_type_parallel_copy, nir_instr_type_phi, and nir_instr::type.
Referenced by nir_convert_from_ssa_impl().
aggressive_coalesce_parallel_copy()
static void aggressive_coalesce_parallel_copy (nir_parallel_copy_instr * pcopy, struct from_ssa_state * state) static
References get_merge_node(), merge_merge_sets(), merge_sets_interfere(), nir_foreach_parallel_copy_entry, nir_instr_type_load_const, and merge_node::set.
Referenced by aggressive_coalesce_block().
coalesce_phi_nodes_block()
static bool coalesce_phi_nodes_block (nir_block * block, struct from_ssa_state * state) static
References nir_phi_instr::dest, get_merge_node(), from_ssa_state::instr, nir_dest::is_ssa, merge_merge_sets(), nir_foreach_instr, nir_foreach_phi_src, nir_instr_type_phi, merge_node::set, nir_dest::ssa, and nir_instr::type.
Referenced by nir_convert_from_ssa_impl().
create_reg_for_ssa_def()
static nir_register* create_reg_for_ssa_def (nir_ssa_def * def, nir_function_impl * impl) static
References nir_register::bit_size, nir_ssa_def::bit_size, nir_register::name, nir_ssa_def::name, nir_local_reg_create(), nir_register::num_array_elems, nir_register::num_components, and nir_ssa_def::num_components.
Referenced by dest_replace_ssa_with_reg(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), and rewrite_ssa_def().
dest_replace_ssa_with_reg()
static bool dest_replace_ssa_with_reg (nir_dest * dest, void * void_state) static
References create_reg_for_ssa_def(), nir_reg_dest::def_link, nir_register::defs, ssa_def_to_reg_state::impl, from_ssa_state::instr, nir_dest::is_ssa, nir_dest_for_reg(), nir_src_for_reg(), nir_ssa_def_rewrite_uses(), nir_ssa_def::parent_instr, nir_reg_dest::parent_instr, ssa_def_to_reg_state::progress, nir_dest::reg, and nir_dest::ssa.
Referenced by nir_lower_ssa_defs_to_regs_block().
emit_copy()
static void emit_copy (nir_builder * b, nir_src src, nir_src dest_src) static
References nir_reg_src::base_offset, nir_alu_dest::dest, nir_alu_instr::dest, nir_reg_src::indirect, nir_alu_instr::instr, nir_src::is_ssa, nir_alu_instr_create(), nir_builder_instr_insert(), nir_dest_for_reg(), nir_src_copy(), nir_register::num_components, nir_ssa_def::num_components, nir_reg_src::reg, nir_src::reg, nir_builder::shader, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and nir_alu_dest::write_mask.
Referenced by resolve_parallel_copy().
get_merge_node()
static merge_node* get_merge_node (nir_ssa_def * def, struct from_ssa_state * state) static
References from_ssa_state::dead_ctx, merge_node::def, from_ssa_state::merge_node_table, merge_node::node, and merge_node::set.
Referenced by aggressive_coalesce_parallel_copy(), and coalesce_phi_nodes_block().
get_parallel_copy_at_end_of_block()
static nir_parallel_copy_instr* get_parallel_copy_at_end_of_block (nir_block * block) static
References nir_block_last_instr(), nir_instr_prev(), nir_instr_type_jump, nir_instr_type_parallel_copy, and nir_instr::type.
Referenced by aggressive_coalesce_block(), isolate_phi_nodes_block(), and resolve_parallel_copies_block().
isolate_phi_nodes_block()
static bool isolate_phi_nodes_block (nir_block * block, void * dead_ctx) static
Isolate phi nodes with parallel copies.
In order to solve the dependency problems with the sources and destinations of phi nodes, we first isolate them by adding parallel copies to the beginnings and ends of basic blocks. For every block with phi nodes, we add a parallel copy immediately following the last phi node that copies the destinations of all of the phi nodes to new SSA values. We also add a parallel copy to the end of every block that has a successor with phi nodes that, for each phi node in each successor, copies the corresponding sorce of the phi node and adjust the phi to used the destination of the parallel copy.
In SSA form, each value has exactly one definition. What this does is ensure that each value used in a phi also has exactly one use. The destinations of phis are only used by the parallel copy immediately following the phi nodes and. Thanks to the parallel copy at the end of the predecessor block, the sources of phi nodes are are the only use of that value. This allows us to immediately assign all the sources and destinations of any given phi node to the same register without worrying about interference at all. We do coalescing to get rid of the parallel copies where possible.
Before this pass can be run, we have to iterate over the blocks with add_parallel_copy_to_end_of_block to ensure that the parallel copies at the ends of blocks exist. We can create the ones at the beginnings as we go, but the ones at the ends of blocks need to be created ahead of time because of potential back-edges in the CFG.
References nir_ssa_def::bit_size, nir_phi_instr::dest, nir_parallel_copy_entry::dest, nir_parallel_copy_instr::entries, get_parallel_copy_at_end_of_block(), from_ssa_state::instr, nir_phi_instr::instr, nir_parallel_copy_instr::instr, nir_dest::is_ssa, nir_ssa_def::name, nir_foreach_instr, nir_foreach_phi_src, nir_instr_insert_after(), nir_instr_rewrite_src(), nir_instr_type_phi, nir_parallel_copy_instr_create(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_parallel_copy_entry::node, nir_ssa_def::num_components, nir_parallel_copy_entry::src, nir_dest::ssa, and nir_instr::type.
Referenced by nir_convert_from_ssa_impl().
merge_merge_sets()
static merge_set* merge_merge_sets (merge_set * a, merge_set * b) static
References merge_node::def, exec_node_data, nir_ssa_def::live_index, exec_node::next, merge_set::nodes, and merge_set::size.
Referenced by aggressive_coalesce_parallel_copy(), and coalesce_phi_nodes_block().
merge_nodes_interfere()
static bool merge_nodes_interfere (merge_node * a, merge_node * b) static
References merge_node::def, and nir_ssa_defs_interfere().
Referenced by merge_sets_interfere().
merge_sets_interfere()
static bool merge_sets_interfere (merge_set * a, merge_set * b) static
References merge_node::def, exec_node_data, nir_ssa_def::live_index, merge_nodes_interfere(), exec_node::next, NIR_VLA, merge_set::nodes, merge_set::size, and ssa_def_dominates().
Referenced by aggressive_coalesce_parallel_copy().
nir_convert_from_ssa()
bool nir_convert_from_ssa (nir_shader * shader, bool phi_webs_only)
References nir_convert_from_ssa_impl(), nir_foreach_function, and from_ssa_state::progress.
nir_convert_from_ssa_impl()
static bool nir_convert_from_ssa_impl (nir_function_impl * impl, bool phi_webs_only) static
References add_parallel_copy_to_end_of_block(), aggressive_coalesce_block(), from_ssa_state::builder, coalesce_phi_nodes_block(), from_ssa_state::dead_ctx, isolate_phi_nodes_block(), from_ssa_state::merge_node_table, nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_preserve(), nir_metadata_require(), from_ssa_state::phi_webs_only, from_ssa_state::progress, resolve_parallel_copies_block(), and resolve_registers_block().
Referenced by nir_convert_from_ssa().
nir_lower_phis_to_regs_block()
bool nir_lower_phis_to_regs_block (nir_block * block)
Lower all of the phi nodes in a block to imovs to and from a register.
This provides a very quick-and-dirty out-of-SSA pass that you can run on a single block to convert all of its phis to a register and some imovs. The code that is generated, while not optimal for actual codegen in a back-end, is easy to generate, correct, and will turn into the same set of phis after you call regs_to_ssa and do some copy propagation.
The one intelligent thing this pass does is that it places the moves from the phi sources as high up the predecessor tree as possible instead of in the exact predecessor. This means that, in particular, it will crawl into the deepest nesting of any if-ladders. In order to ensure that doing so is safe, it stops as soon as one of the predecessors has multiple successors.
References nir_ssa_def::bit_size, nir_block::cf_node, create_reg_for_ssa_def(), nir_alu_dest::dest, nir_alu_instr::dest, nir_phi_instr::dest, nir_function_impl::function, from_ssa_state::instr, nir_alu_instr::instr, nir_phi_instr::instr, nir_dest::is_ssa, nir_ssa_def::name, nir_after_instr(), nir_alu_instr_create(), nir_cf_node_get_function(), nir_foreach_instr_safe, nir_foreach_phi_src, nir_instr_insert(), nir_instr_remove(), nir_instr_type_phi, nir_src_for_reg(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_ssa_def::num_components, place_phi_read(), from_ssa_state::progress, nir_function::shader, nir_alu_src::src, nir_alu_instr::src, nir_dest::ssa, nir_instr::type, and nir_alu_dest::write_mask.
Referenced by loop_prepare_for_unroll(), lower_trivial_continues_block(), and opt_peel_loop_initial_if().
nir_lower_ssa_defs_to_regs_block()
bool nir_lower_ssa_defs_to_regs_block (nir_block * block)
Lower all of the SSA defs in a block to registers.
This performs the very simple operation of blindly replacing all of the SSA defs in the given block with registers. If not used carefully, this may result in phi nodes with register sources which is technically invalid. Fortunately, the register-based into-SSA pass handles them anyway.
References nir_block::cf_node, create_reg_for_ssa_def(), nir_load_const_instr::def, nir_ssa_undef_instr::def, nir_alu_dest::dest, nir_alu_instr::dest, dest_replace_ssa_with_reg(), nir_function_impl::function, ssa_def_to_reg_state::impl, from_ssa_state::instr, nir_alu_instr::instr, nir_load_const_instr::instr, nir_after_instr(), nir_alu_instr_create(), nir_cf_node_get_function(), nir_dest_for_reg(), nir_foreach_dest(), nir_foreach_instr, nir_instr_insert(), nir_instr_type_load_const, nir_instr_type_ssa_undef, nir_src_for_reg(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_register::num_components, ssa_def_to_reg_state::progress, nir_function::shader, nir_alu_src::src, nir_alu_instr::src, nir_instr::type, and nir_alu_dest::write_mask.
Referenced by opt_peel_loop_initial_if().
place_phi_read()
static void place_phi_read (nir_shader * shader, nir_register * reg, nir_ssa_def * def, nir_block * block) static
References nir_instr::block, nir_alu_dest::dest, nir_alu_instr::dest, if(), nir_alu_instr::instr, nir_after_block_before_jump(), nir_alu_instr_create(), nir_dest_for_reg(), nir_instr_insert(), nir_src_for_ssa(), nir_register::num_components, nir_ssa_def::parent_instr, nir_block::predecessors, nir_alu_src::src, nir_alu_instr::src, nir_block::successors, and nir_alu_dest::write_mask.
Referenced by nir_lower_phis_to_regs_block().
resolve_parallel_copies_block()
static bool resolve_parallel_copies_block (nir_block * block, struct from_ssa_state * state) static
References get_parallel_copy_at_end_of_block(), nir_block_first_instr(), nir_instr_type_parallel_copy, resolve_parallel_copy(), and nir_instr::type.
Referenced by nir_convert_from_ssa_impl().
resolve_parallel_copy()
static void resolve_parallel_copy (nir_parallel_copy_instr * pcopy, struct from_ssa_state * state) static
References from_ssa_state::builder, nir_builder::cursor, emit_copy(), nir_builder::impl, nir_parallel_copy_instr::instr, nir_register::name, nir_before_instr(), nir_foreach_parallel_copy_entry, nir_instr_remove(), nir_local_reg_create(), nir_src_for_reg(), nir_srcs_equal(), NIR_VLA, NIR_VLA_FILL, NIR_VLA_ZERO, nir_register::num_array_elems, and nir_register::num_components.
Referenced by resolve_parallel_copies_block().
resolve_registers_block()
static void resolve_registers_block (nir_block * block, struct from_ssa_state * state) static
References from_ssa_state::dead_ctx, from_ssa_state::instr, nir_foreach_instr_safe, nir_foreach_ssa_def(), nir_instr_remove(), nir_instr_type_phi, from_ssa_state::progress, rewrite_ssa_def(), and nir_instr::type.
Referenced by nir_convert_from_ssa_impl().
rewrite_ssa_def()
static bool rewrite_ssa_def (nir_ssa_def * def, void * void_state) static
References from_ssa_state::builder, create_reg_for_ssa_def(), from_ssa_state::dead_ctx, exec_node_data, if(), nir_ssa_def::if_uses, nir_builder::impl, from_ssa_state::instr, from_ssa_state::merge_node_table, nir_dest_for_reg(), nir_instr_remove(), nir_instr_rewrite_dest(), nir_instr_type_load_const, nir_instr_type_ssa_undef, nir_src_for_reg(), nir_ssa_def_rewrite_uses(), nir_ssa_def::parent_instr, from_ssa_state::phi_webs_only, from_ssa_state::progress, merge_set::reg, merge_node::set, nir_instr::type, and nir_ssa_def::uses.
Referenced by resolve_registers_block().
ssa_def_dominates()
static bool ssa_def_dominates (nir_ssa_def * a, nir_ssa_def * b) static
References nir_instr::block, nir_ssa_def::live_index, nir_block_dominates(), and nir_ssa_def::parent_instr.
Referenced by merge_sets_interfere().