Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_wpos_ytransform.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "program/prog_instruction.h"
Data Structures
struct lower_wpos_ytransform_state
Functions
static nir_ssa_def * get_transform (lower_wpos_ytransform_state *state)
static nir_ssa_def * nir_cmp (nir_builder *b, nir_ssa_def *src0, nir_ssa_def *src1, nir_ssa_def *src2)
static void emit_wpos_adjustment (lower_wpos_ytransform_state *state, nir_intrinsic_instr *intr, bool invert, float adjX, float adjY[2])
static void lower_fragcoord (lower_wpos_ytransform_state *state, nir_intrinsic_instr *intr)
static void lower_fddy (lower_wpos_ytransform_state *state, nir_alu_instr *fddy)
static void lower_interp_var_at_offset (lower_wpos_ytransform_state *state, nir_intrinsic_instr *interp)
static void lower_load_sample_pos (lower_wpos_ytransform_state *state, nir_intrinsic_instr *intr)
static void lower_wpos_ytransform_block (lower_wpos_ytransform_state *state, nir_block *block)
static void lower_wpos_ytransform_impl (lower_wpos_ytransform_state *state, nir_function_impl *impl)
bool nir_lower_wpos_ytransform (nir_shader *shader, const nir_lower_wpos_ytransform_options *options)
Function Documentation
emit_wpos_adjustment()
static void emit_wpos_adjustment (lower_wpos_ytransform_state * state, nir_intrinsic_instr * intr, bool invert, float adjX, float adjY[2]) static
References lower_wpos_ytransform_state::b, nir_builder::cursor, nir_intrinsic_instr::dest, get_transform(), nir_intrinsic_instr::instr, nir_dest::is_ssa, nir_before_instr(), nir_channel(), nir_cmp(), nir_imm_vec4(), nir_load_var(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_dest::ssa, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_fragcoord().
get_transform()
static nir_ssa_def* get_transform (lower_wpos_ytransform_state * state) static
References lower_wpos_ytransform_state::b, nir_load_var(), nir_var_uniform, nir_variable_create(), nir_variable::num_state_slots, lower_wpos_ytransform_state::options, lower_wpos_ytransform_state::shader, nir_variable::state_slots, nir_lower_wpos_ytransform_options::state_tokens, nir_state_slot::swizzle, nir_state_slot::tokens, and lower_wpos_ytransform_state::transform.
Referenced by emit_wpos_adjustment(), lower_fddy(), lower_interp_var_at_offset(), and lower_load_sample_pos().
lower_fddy()
static void lower_fddy (lower_wpos_ytransform_state * state, nir_alu_instr * fddy) static
References lower_wpos_ytransform_state::b, nir_builder::cursor, get_transform(), nir_alu_instr::instr, nir_before_instr(), nir_channel(), nir_instr_rewrite_src(), nir_src_for_ssa(), nir_ssa_for_alu_src(), nir_ssa_def::num_components, nir_alu_src::src, nir_alu_instr::src, and nir_alu_src::swizzle.
Referenced by lower_wpos_ytransform_block().
lower_fragcoord()
static void lower_fragcoord (lower_wpos_ytransform_state * state, nir_intrinsic_instr * intr) static
References nir_variable::data, emit_wpos_adjustment(), nir_lower_wpos_ytransform_options::fs_coord_origin_lower_left, nir_lower_wpos_ytransform_options::fs_coord_origin_upper_left, nir_lower_wpos_ytransform_options::fs_coord_pixel_center_half_integer, nir_lower_wpos_ytransform_options::fs_coord_pixel_center_integer, lower_wpos_ytransform_state::options, nir_variable::nir_variable_data::origin_upper_left, nir_variable::nir_variable_data::pixel_center_integer, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_wpos_ytransform_block().
lower_interp_var_at_offset()
static void lower_interp_var_at_offset (lower_wpos_ytransform_state * state, nir_intrinsic_instr * interp) static
References lower_wpos_ytransform_state::b, nir_builder::cursor, get_transform(), nir_intrinsic_instr::instr, nir_before_instr(), nir_channel(), nir_instr_rewrite_src(), nir_src_for_ssa(), nir_ssa_for_src(), and nir_intrinsic_instr::src.
Referenced by lower_wpos_ytransform_block().
lower_load_sample_pos()
static void lower_load_sample_pos (lower_wpos_ytransform_state * state, nir_intrinsic_instr * intr) static
References lower_wpos_ytransform_state::b, nir_builder::cursor, nir_intrinsic_instr::dest, get_transform(), nir_intrinsic_instr::instr, nir_after_instr(), nir_channel(), nir_imm_float(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses_after(), nir_ssa_def::parent_instr, and nir_dest::ssa.
Referenced by lower_wpos_ytransform_block().
lower_wpos_ytransform_block()
static void lower_wpos_ytransform_block (lower_wpos_ytransform_state * state, nir_block * block) static
References nir_deref::child, nir_variable::data, nir_deref_var::deref, instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::location, lower_fddy(), lower_fragcoord(), lower_interp_var_at_offset(), lower_load_sample_pos(), nir_variable::nir_variable_data::mode, nir_foreach_instr_safe, nir_instr_type_alu, nir_instr_type_intrinsic, nir_var_shader_in, nir_var_system_value, nir_alu_instr::op, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_wpos_ytransform_impl().
lower_wpos_ytransform_impl()
static void lower_wpos_ytransform_impl (lower_wpos_ytransform_state * state, nir_function_impl * impl) static
References lower_wpos_ytransform_state::b, lower_wpos_ytransform_block(), nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_wpos_ytransform().
nir_cmp()
static nir_ssa_def* nir_cmp (nir_builder * b, nir_ssa_def * src0, nir_ssa_def * src1, nir_ssa_def * src2) static
References nir_imm_float().
Referenced by emit_wpos_adjustment().
nir_lower_wpos_ytransform()
bool nir_lower_wpos_ytransform (nir_shader * shader, const nir_lower_wpos_ytransform_options * options)
References lower_wpos_ytransform_impl(), nir_foreach_function, nir_shader::stage, and lower_wpos_ytransform_state::transform.