Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_propagate_invariant.c File Reference
#include "nir.h"
Functions
static void add_src (nir_src *src, struct set *invariants)
static bool add_src_cb (nir_src *src, void *state)
static bool dest_is_invariant (nir_dest *dest, struct set *invariants)
static void add_cf_node (nir_cf_node *cf, struct set *invariants)
static void add_var (nir_variable *var, struct set *invariants)
static bool var_is_invariant (nir_variable *var, struct set *invariants)
static void propagate_invariant_instr (nir_instr *instr, struct set *invariants)
static bool propagate_invariant_impl (nir_function_impl *impl, struct set *invariants)
bool nir_propagate_invariant (nir_shader *shader)
Function Documentation
add_cf_node()
static void add_cf_node (nir_cf_node * cf, struct set * invariants) static
References add_src(), nir_if::condition, nir_cf_node::parent, and nir_cf_node::type.
Referenced by propagate_invariant_instr().
add_src()
static void add_src (nir_src * src, struct set * invariants) static
References nir_src::is_ssa, nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by add_cf_node(), add_src_cb(), propagate_invariant_instr(), and test_iterations().
add_src_cb()
static bool add_src_cb (nir_src * src, void * state) static
References add_src().
Referenced by propagate_invariant_instr().
add_var()
static void add_var (nir_variable * var, struct set * invariants) static
Referenced by propagate_invariant_instr().
dest_is_invariant()
static bool dest_is_invariant (nir_dest * dest, struct set * invariants) static
References nir_dest::is_ssa, nir_reg_dest::reg, nir_dest::reg, and nir_dest::ssa.
Referenced by propagate_invariant_instr().
nir_propagate_invariant()
bool nir_propagate_invariant (nir_shader * shader)
References nir_foreach_function, and propagate_invariant_impl().
propagate_invariant_impl()
static bool propagate_invariant_impl (nir_function_impl * impl, struct set * invariants) static
References instr, nir_foreach_block_reverse, nir_foreach_instr_reverse, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_preserve(), and propagate_invariant_instr().
Referenced by nir_propagate_invariant().
propagate_invariant_instr()
static void propagate_invariant_instr (nir_instr * instr, struct set * invariants) static
References add_cf_node(), add_src(), add_src_cb(), add_var(), nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, nir_tex_instr::dest, nir_phi_instr::dest, dest_is_invariant(), nir_alu_instr::exact, nir_intrinsic_instr::intrinsic, nir_foreach_phi_src, nir_foreach_src(), nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, nir_intrinsic_instr::src, nir_instr::type, nir_deref_var::var, var_is_invariant(), and nir_intrinsic_instr::variables.
Referenced by propagate_invariant_impl().
var_is_invariant()
static bool var_is_invariant (nir_variable * var, struct set * invariants) static
References nir_variable::data, and nir_variable::nir_variable_data::invariant.
Referenced by propagate_invariant_instr().