Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_atomics.c File Reference
#include "compiler/glsl/ir_uniform.h"
#include "nir.h"
#include "main/config.h"
#include <assert.h>
Functions
static bool lower_instr (nir_intrinsic_instr *instr, const struct gl_shader_program *shader_program, nir_shader *shader)
bool nir_lower_atomics (nir_shader *shader, const struct gl_shader_program *shader_program)
Function Documentation
lower_instr()
static bool lower_instr (nir_intrinsic_instr * instr, const struct gl_shader_program * shader_program, nir_shader * shader) static
References add(), ATOMIC_COUNTER_SIZE, nir_deref_array::base_offset, nir_deref::child, gl_shader_program::data, nir_variable::data, nir_load_const_instr::def, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, if(), gl_opaque_uniform_index::index, nir_deref_array::indirect, nir_alu_instr::instr, nir_intrinsic_instr::instr, nir_load_const_instr::instr, nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_dest::is_ssa, nir_variable::nir_variable_data::location, mem_ctx, nir_variable::nir_variable_data::mode, mul(), nir_alu_instr_create(), nir_deref_array_type_indirect, nir_dest_copy(), nir_instr_insert_before(), nir_instr_remove(), nir_intrinsic_infos, nir_intrinsic_instr_create(), nir_load_const_instr_create(), nir_src_copy(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_var_shader_storage, nir_var_shared, nir_var_uniform, nir_ssa_def::num_components, nir_intrinsic_info::num_srcs, nir_variable::nir_variable_data::offset, gl_uniform_storage::opaque, nir_alu_src::src, nir_alu_instr::src, nir_intrinsic_instr::src, nir_src::ssa, nir_dest::ssa, nir_shader::stage, nir_deref::type, nir_const_value::u32, gl_shader_program_data::UniformStorage, nir_load_const_instr::value, nir_deref_var::var, nir_intrinsic_instr::variables, and nir_alu_dest::write_mask.
Referenced by nir_lower_atomics().
nir_lower_atomics()
bool nir_lower_atomics (nir_shader * shader, const struct gl_shader_program * shader_program)
References instr, lower_instr(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_type_intrinsic, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().