Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_dominance.c File Reference
#include "nir.h"
Functions
static bool init_block (nir_block *block, nir_function_impl *impl)
static nir_block * intersect (nir_block *b1, nir_block *b2)
static bool calc_dominance (nir_block *block)
static bool calc_dom_frontier (nir_block *block)
static void calc_dom_children (nir_function_impl *impl)
static void calc_dfs_indicies (nir_block *block, unsigned *index)
void nir_calc_dominance_impl (nir_function_impl *impl)
void nir_calc_dominance (nir_shader *shader)
nir_block * nir_dominance_lca (nir_block *b1, nir_block *b2)
Computes the least common anscestor of two blocks.
bool nir_block_dominates (nir_block *parent, nir_block *child)
Returns true if parent dominates child.
void nir_dump_dom_tree_impl (nir_function_impl *impl, FILE *fp)
void nir_dump_dom_tree (nir_shader *shader, FILE *fp)
void nir_dump_dom_frontier_impl (nir_function_impl *impl, FILE *fp)
void nir_dump_dom_frontier (nir_shader *shader, FILE *fp)
void nir_dump_cfg_impl (nir_function_impl *impl, FILE *fp)
void nir_dump_cfg (nir_shader *shader, FILE *fp)
Function Documentation
calc_dfs_indicies()
static void calc_dfs_indicies (nir_block * block, unsigned * index) static
References nir_block::dom_children, nir_block::dom_post_index, nir_block::dom_pre_index, and nir_block::num_dom_children.
Referenced by nir_calc_dominance_impl().
calc_dom_children()
static void calc_dom_children (nir_function_impl * impl) static
References mem_ctx, and nir_foreach_block.
Referenced by nir_calc_dominance_impl().
calc_dom_frontier()
static bool calc_dom_frontier (nir_block * block) static
References nir_block::dom_frontier, if(), nir_block::imm_dom, and nir_block::predecessors.
Referenced by nir_calc_dominance_impl().
calc_dominance()
static bool calc_dominance (nir_block * block) static
References if(), nir_block::imm_dom, intersect(), and nir_block::predecessors.
Referenced by nir_calc_dominance_impl().
init_block()
static bool init_block (nir_block * block, nir_function_impl * impl) static
References nir_block::dom_frontier, nir_block::imm_dom, nir_start_block(), and nir_block::num_dom_children.
Referenced by nir_calc_dominance_impl().
intersect()
static nir_block* intersect (nir_block * b1, nir_block * b2) static
References nir_block::imm_dom, and nir_block::index.
Referenced by calc_dominance(), and nir_dominance_lca().
nir_block_dominates()
bool nir_block_dominates (nir_block * parent, nir_block * child)
Returns true if parent dominates child.
References nir_block::cf_node, nir_block::dom_post_index, nir_block::dom_pre_index, nir_cf_node_get_function(), nir_metadata_dominance, and nir_function_impl::valid_metadata.
Referenced by repair_ssa_def(), ssa_def_dominates(), and ssa_def_dominates_instr().
nir_calc_dominance()
void nir_calc_dominance (nir_shader * shader)
References nir_calc_dominance_impl(), and nir_foreach_function.
nir_calc_dominance_impl()
void nir_calc_dominance_impl (nir_function_impl * impl)
References calc_dfs_indicies(), calc_dom_children(), calc_dom_frontier(), calc_dominance(), nir_block::imm_dom, init_block(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_require(), nir_start_block(), and nir_function_impl::valid_metadata.
Referenced by nir_calc_dominance(), and nir_metadata_require().
nir_dominance_lca()
nir_block* nir_dominance_lca (nir_block * b1, nir_block * b2)
Computes the least common anscestor of two blocks.
If one of the blocks is null, the other block is returned.
References nir_block::cf_node, intersect(), nir_cf_node_get_function(), nir_metadata_dominance, and nir_function_impl::valid_metadata.
Referenced by gcm_schedule_late_def().
nir_dump_cfg()
void nir_dump_cfg (nir_shader * shader, FILE * fp)
References nir_dump_cfg_impl(), and nir_foreach_function.
nir_dump_cfg_impl()
void nir_dump_cfg_impl (nir_function_impl * impl, FILE * fp)
References nir_function_impl::function, nir_function::name, and nir_foreach_block.
Referenced by nir_dump_cfg().
nir_dump_dom_frontier()
void nir_dump_dom_frontier (nir_shader * shader, FILE * fp)
References nir_dump_dom_frontier_impl(), and nir_foreach_function.
nir_dump_dom_frontier_impl()
void nir_dump_dom_frontier_impl (nir_function_impl * impl, FILE * fp)
References nir_block::index, and nir_foreach_block.
Referenced by nir_dump_dom_frontier().
nir_dump_dom_tree()
void nir_dump_dom_tree (nir_shader * shader, FILE * fp)
References nir_dump_dom_tree_impl(), and nir_foreach_function.
nir_dump_dom_tree_impl()
void nir_dump_dom_tree_impl (nir_function_impl * impl, FILE * fp)
References nir_function_impl::function, nir_function::name, and nir_foreach_block.
Referenced by nir_dump_dom_tree().