Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_constant_folding.c File Reference
#include "nir_constant_expressions.h"
#include <math.h>
Data Structures
struct constant_fold_state
Functions
static bool constant_fold_alu_instr (nir_alu_instr *instr, void *mem_ctx)
static bool constant_fold_deref (nir_instr *instr, nir_deref_var *deref)
static bool constant_fold_intrinsic_instr (nir_intrinsic_instr *instr)
static bool constant_fold_tex_instr (nir_tex_instr *instr)
static bool constant_fold_block (nir_block *block, void *mem_ctx)
static bool nir_opt_constant_folding_impl (nir_function_impl *impl)
bool nir_opt_constant_folding (nir_shader *shader)
Function Documentation
constant_fold_alu_instr()
static bool constant_fold_alu_instr (nir_alu_instr * instr, void * mem_ctx) static
References nir_alu_src::abs, nir_ssa_def::bit_size, nir_load_const_instr::def, nir_alu_dest::dest, nir_alu_instr::dest, nir_op_info::input_sizes, nir_alu_instr::instr, nir_load_const_instr::instr, nir_src::is_ssa, nir_dest::is_ssa, nir_alu_src::negate, nir_alu_type_get_type_size(), nir_eval_const_opcode(), nir_instr_insert_before(), nir_instr_remove(), nir_instr_type_load_const, nir_load_const_instr_create(), nir_op_infos, nir_src_for_ssa(), nir_ssa_alu_instr_src_components(), nir_ssa_def_rewrite_uses(), nir_ssa_def::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_op_info::output_type, nir_ssa_def::parent_instr, nir_alu_dest::saturate, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_alu_src::swizzle, nir_instr::type, nir_const_value::u32, nir_const_value::u64, and nir_load_const_instr::value.
Referenced by constant_fold_block().
constant_fold_block()
static bool constant_fold_block (nir_block * block, void * mem_ctx) static
References constant_fold_alu_instr(), constant_fold_intrinsic_instr(), constant_fold_tex_instr(), instr, nir_foreach_instr_safe, nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_tex, and constant_fold_state::progress.
Referenced by nir_opt_constant_folding_impl().
constant_fold_deref()
static bool constant_fold_deref (nir_instr * instr, nir_deref_var * deref) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref_array::indirect, nir_src::is_ssa, nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_type_array, nir_instr_rewrite_src(), nir_instr_type_load_const, nir_src_for_ssa(), nir_ssa_def::parent_instr, constant_fold_state::progress, nir_src::ssa, nir_instr::type, nir_const_value::u32, and nir_load_const_instr::value.
Referenced by constant_fold_intrinsic_instr(), and constant_fold_tex_instr().
constant_fold_intrinsic_instr()
static bool constant_fold_intrinsic_instr (nir_intrinsic_instr * instr) static
References constant_fold_deref(), nir_intrinsic_instr::instr, nir_intrinsic_instr::intrinsic, nir_instr_remove(), nir_intrinsic_infos, nir_src_as_const_value(), nir_intrinsic_info::num_variables, constant_fold_state::progress, nir_intrinsic_instr::src, nir_const_value::u32, and nir_intrinsic_instr::variables.
Referenced by constant_fold_block().
constant_fold_tex_instr()
static bool constant_fold_tex_instr (nir_tex_instr * instr) static
References constant_fold_deref(), nir_tex_instr::instr, constant_fold_state::progress, nir_tex_instr::sampler, and nir_tex_instr::texture.
Referenced by constant_fold_block().
nir_opt_constant_folding()
bool nir_opt_constant_folding (nir_shader * shader)
References nir_foreach_function, nir_opt_constant_folding_impl(), and constant_fold_state::progress.
nir_opt_constant_folding_impl()
static bool nir_opt_constant_folding_impl (nir_function_impl * impl) static
References constant_fold_block(), constant_fold_state::mem_ctx, nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and constant_fold_state::progress.
Referenced by nir_opt_constant_folding().