Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_remove_dead_variables.c File Reference
#include "nir.h"
Functions
static void add_var_use_intrinsic (nir_intrinsic_instr *instr, struct set *live)
static void add_var_use_call (nir_call_instr *instr, struct set *live)
static void add_var_use_tex (nir_tex_instr *instr, struct set *live)
static void add_var_use_shader (nir_shader *shader, struct set *live)
static void remove_dead_var_writes (nir_shader *shader, struct set *live)
static bool remove_dead_vars (struct exec_list *var_list, struct set *live)
bool nir_remove_dead_variables (nir_shader *shader, nir_variable_mode modes)
Function Documentation
add_var_use_call()
static void add_var_use_call (nir_call_instr * instr, struct set * live) static
References nir_call_instr::num_params, nir_call_instr::params, nir_call_instr::return_deref, and nir_deref_var::var.
Referenced by add_var_use_shader().
add_var_use_intrinsic()
static void add_var_use_intrinsic (nir_intrinsic_instr * instr, struct set * live) static
References nir_variable::data, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::mode, nir_intrinsic_infos, nir_var_global, nir_var_local, nir_var_shared, nir_intrinsic_info::num_variables, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by add_var_use_shader().
add_var_use_shader()
static void add_var_use_shader (nir_shader * shader, struct set * live) static
References add_var_use_call(), add_var_use_intrinsic(), add_var_use_tex(), instr, nir_foreach_block, nir_foreach_function, nir_foreach_instr, nir_instr_type_call, nir_instr_type_intrinsic, and nir_instr_type_tex.
Referenced by nir_remove_dead_variables().
add_var_use_tex()
static void add_var_use_tex (nir_tex_instr * instr, struct set * live) static
References nir_tex_instr::sampler, nir_tex_instr::texture, and nir_deref_var::var.
Referenced by add_var_use_shader().
nir_remove_dead_variables()
bool nir_remove_dead_variables (nir_shader * shader, nir_variable_mode modes)
References add_var_use_shader(), nir_shader::globals, nir_shader::inputs, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_var_global, nir_var_local, nir_var_shader_in, nir_var_shader_out, nir_var_shared, nir_var_system_value, nir_var_uniform, nir_shader::outputs, remove_dead_var_writes(), remove_dead_vars(), nir_shader::shared, nir_shader::system_values, and nir_shader::uniforms.
remove_dead_var_writes()
static void remove_dead_var_writes (nir_shader * shader, struct set * live) static
References nir_variable::data, instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::mode, nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_intrinsic, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_remove_dead_variables().
remove_dead_vars()
static bool remove_dead_vars (struct exec_list * var_list, struct set * live) static
References foreach_list_typed_safe.
Referenced by nir_remove_dead_variables().