Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_worklist.h File Reference
#include "nir.h"
Data Structures
struct nir_block_worklist
Represents a double-ended queue of unique blocks.
Functions
void nir_block_worklist_init (nir_block_worklist *w, unsigned num_blocks, void *mem_ctx)
void nir_block_worklist_fini (nir_block_worklist *w)
void nir_block_worklist_add_all (nir_block_worklist *w, nir_function_impl *impl)
static bool nir_block_worklist_is_empty (const nir_block_worklist *w)
void nir_block_worklist_push_head (nir_block_worklist *w, nir_block *block)
nir_block * nir_block_worklist_peek_head (const nir_block_worklist *w)
nir_block * nir_block_worklist_pop_head (nir_block_worklist *w)
void nir_block_worklist_push_tail (nir_block_worklist *w, nir_block *block)
nir_block * nir_block_worklist_peek_tail (const nir_block_worklist *w)
nir_block * nir_block_worklist_pop_tail (nir_block_worklist *w)
Function Documentation
nir_block_worklist_add_all()
void nir_block_worklist_add_all (nir_block_worklist * w, nir_function_impl * impl)
References nir_block_worklist_push_tail(), and nir_foreach_block.
nir_block_worklist_fini()
void nir_block_worklist_fini (nir_block_worklist * w)
References nir_block_worklist::blocks, and nir_block_worklist::blocks_present.
Referenced by nir_live_ssa_defs_impl().
nir_block_worklist_init()
void nir_block_worklist_init (nir_block_worklist * w, unsigned num_blocks, void * mem_ctx)
References nir_block_worklist::blocks, nir_block_worklist::blocks_present, nir_block_worklist::count, nir_block_worklist::size, and nir_block_worklist::start.
Referenced by nir_live_ssa_defs_impl().
nir_block_worklist_is_empty()
static bool nir_block_worklist_is_empty (const nir_block_worklist * w) inline static
References nir_block_worklist::count, nir_block_worklist_peek_head(), nir_block_worklist_peek_tail(), nir_block_worklist_pop_head(), nir_block_worklist_pop_tail(), nir_block_worklist_push_head(), and nir_block_worklist_push_tail().
Referenced by nir_live_ssa_defs_impl().
nir_block_worklist_peek_head()
nir_block* nir_block_worklist_peek_head (const nir_block_worklist * w)
References nir_block_worklist::blocks, nir_block_worklist::count, and nir_block_worklist::start.
Referenced by nir_block_worklist_is_empty().
nir_block_worklist_peek_tail()
nir_block* nir_block_worklist_peek_tail (const nir_block_worklist * w)
References nir_block_worklist::blocks, nir_block_worklist::count, nir_block_worklist::size, and nir_block_worklist::start.
Referenced by nir_block_worklist_is_empty().
nir_block_worklist_pop_head()
nir_block* nir_block_worklist_pop_head (nir_block_worklist * w)
References nir_block_worklist::blocks, nir_block_worklist::blocks_present, nir_block_worklist::count, nir_block::index, nir_block_worklist::size, and nir_block_worklist::start.
Referenced by nir_block_worklist_is_empty(), and nir_live_ssa_defs_impl().
nir_block_worklist_pop_tail()
nir_block* nir_block_worklist_pop_tail (nir_block_worklist * w)
References nir_block_worklist::blocks, nir_block_worklist::blocks_present, nir_block_worklist::count, nir_block::index, nir_block_worklist::size, and nir_block_worklist::start.
Referenced by nir_block_worklist_is_empty().
nir_block_worklist_push_head()
void nir_block_worklist_push_head (nir_block_worklist * w, nir_block * block)
References nir_block_worklist::blocks, nir_block_worklist::blocks_present, nir_block_worklist::count, nir_block::index, nir_block_worklist::size, and nir_block_worklist::start.
Referenced by init_liveness_block(), and nir_block_worklist_is_empty().
nir_block_worklist_push_tail()
void nir_block_worklist_push_tail (nir_block_worklist * w, nir_block * block)
References nir_block_worklist::blocks, nir_block_worklist::blocks_present, nir_block_worklist::count, nir_block::index, nir_block_worklist::size, and nir_block_worklist::start.
Referenced by nir_block_worklist_add_all(), nir_block_worklist_is_empty(), and nir_live_ssa_defs_impl().