Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_io_to_scalar.c File Reference
Replaces nir_load_input/nir_store_output operations with num_components != 1 with individual per-channel operations.
#include "nir.h"
#include "nir_builder.h"
Functions
static void lower_load_input_to_scalar (nir_builder *b, nir_intrinsic_instr *intr)
static void lower_store_output_to_scalar (nir_builder *b, nir_intrinsic_instr *intr)
void nir_lower_io_to_scalar (nir_shader *shader, nir_variable_mode mask)
Detailed Description
Replaces nir_load_input/nir_store_output operations with num_components != 1 with individual per-channel operations.
Function Documentation
lower_load_input_to_scalar()
static void lower_load_input_to_scalar (nir_builder * b, nir_intrinsic_instr * intr) static
References nir_ssa_def::bit_size, nir_builder::cursor, nir_intrinsic_instr::dest, nir_intrinsic_instr::instr, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, nir_before_instr(), nir_builder_instr_insert(), nir_instr_remove(), nir_intrinsic_instr_create(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_vec(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_intrinsic_instr::src, and nir_dest::ssa.
Referenced by nir_lower_io_to_scalar().
lower_store_output_to_scalar()
static void lower_store_output_to_scalar (nir_builder * b, nir_intrinsic_instr * intr) static
References nir_builder::cursor, nir_intrinsic_instr::instr, nir_intrinsic_instr::intrinsic, nir_before_instr(), nir_builder_instr_insert(), nir_channel(), nir_instr_remove(), nir_intrinsic_instr_create(), nir_src_for_ssa(), nir_ssa_for_src(), nir_intrinsic_instr::num_components, nir_builder::shader, and nir_intrinsic_instr::src.
Referenced by nir_lower_io_to_scalar().
nir_lower_io_to_scalar()
void nir_lower_io_to_scalar (nir_shader * shader, nir_variable_mode mask)
References nir_builder::impl, instr, nir_intrinsic_instr::intrinsic, lower_load_input_to_scalar(), lower_store_output_to_scalar(), nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_type_intrinsic, nir_var_shader_in, nir_var_shader_out, and nir_intrinsic_instr::num_components.