Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_loop_analyze.c File Reference
#include "nir.h"
#include "nir_constant_expressions.h"
#include "nir_loop_analyze.h"
Data Structures
struct nir_loop_variable
struct nir_basic_induction_var
struct loop_info_state
struct init_loop_state
Typedefs
typedef struct nir_basic_induction_var nir_basic_induction_var
Enumerations
enum nir_loop_variable_type { undefined, invariant, not_invariant, basic_induction }
Functions
static nir_loop_variable * get_loop_var (nir_ssa_def *value, loop_info_state *state)
static bool init_loop_def (nir_ssa_def *def, void *void_init_loop_state)
static bool init_loop_block (nir_block *block, loop_info_state *state, bool in_control_flow)
static bool is_var_alu (nir_loop_variable *var)
static bool is_var_constant (nir_loop_variable *var)
static bool is_var_phi (nir_loop_variable *var)
static bool mark_invariant (nir_ssa_def *def, loop_info_state *state)
static void compute_invariance_information (loop_info_state *state)
static bool compute_induction_information (loop_info_state *state)
static bool initialize_ssa_def (nir_ssa_def *def, void *void_state)
static bool ends_in_break (nir_block *block)
static bool find_loop_terminators (loop_info_state *state)
static int32_t get_iteration (nir_op cond_op, nir_const_value *initial, nir_const_value *step, nir_const_value *limit)
static bool test_iterations (int32_t iter_int, nir_const_value *step, nir_const_value *limit, nir_op cond_op, unsigned bit_size, nir_alu_type induction_base_type, nir_const_value *initial, bool limit_rhs, bool invert_cond)
static int calculate_iterations (nir_const_value *initial, nir_const_value *step, nir_const_value *limit, nir_loop_variable *alu_def, nir_alu_instr *cond_alu, bool limit_rhs, bool invert_cond)
static void find_trip_count (loop_info_state *state)
static bool force_unroll_array_access (loop_info_state *state, nir_shader *ns, nir_deref_var *variable)
static bool force_unroll_heuristics (loop_info_state *state, nir_shader *ns, nir_block *block)
static void get_loop_info (loop_info_state *state, nir_function_impl *impl)
static loop_info_state * initialize_loop_info_state (nir_loop *loop, void *mem_ctx, nir_function_impl *impl)
static void process_loops (nir_cf_node *cf_node, nir_variable_mode indirect_mask)
void nir_loop_analyze_impl (nir_function_impl *impl, nir_variable_mode indirect_mask)
Typedef Documentation
nir_basic_induction_var
typedef struct nir_basic_induction_var nir_basic_induction_var
Enumeration Type Documentation
nir_loop_variable_type
enum nir_loop_variable_type
Enumerator
undefined
invariant
not_invariant
basic_induction
Function Documentation
calculate_iterations()
static int calculate_iterations (nir_const_value * initial, nir_const_value * step, nir_const_value * limit, nir_loop_variable * alu_def, nir_alu_instr * cond_alu, bool limit_rhs, bool invert_cond) static
References nir_loop_variable::def, get_iteration(), nir_op_info::input_types, nir_alu_type_get_base_type(), nir_op_infos, nir_src_bit_size(), nir_type_int, nir_type_uint, nir_alu_instr::op, nir_op_info::output_type, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and test_iterations().
Referenced by find_trip_count().
compute_induction_information()
static bool compute_induction_information (loop_info_state * state) static
References nir_basic_induction_var::alu_def, nir_basic_induction_var::alu_op, basic_induction, nir_loop_variable::def, nir_basic_induction_var::def_outside_loop, nir_phi_instr::dest, get_loop_var(), nir_loop_variable::in_control_flow, nir_loop_variable::in_loop, nir_loop_variable::ind, nir_basic_induction_var::invariant, is_var_alu(), is_var_constant(), is_var_phi(), nir_foreach_phi_src, nir_instr_type_load_const, nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, nir_ssa_def::parent_instr, loop_info_state::process_list, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_loop_variable::type, and nir_instr::type.
Referenced by get_loop_info().
compute_invariance_information()
static void compute_invariance_information (loop_info_state * state) static
References mark_invariant(), and loop_info_state::process_list.
Referenced by get_loop_info().
ends_in_break()
static bool ends_in_break (nir_block * block) inline static
References instr, nir_block::instr_list, nir_block_last_instr(), nir_instr_type_jump, nir_jump_break, and nir_instr::type.
Referenced by find_loop_terminators().
find_loop_terminators()
static bool find_loop_terminators (loop_info_state * state) static
References nir_loop::body, nir_loop_terminator::break_block, nir_if::condition, nir_loop_terminator::conditional_instr, nir_loop_terminator::continue_from_block, nir_loop_terminator::continue_from_then, ends_in_break(), foreach_list_typed_safe, nir_loop::info, loop_info_state::loop, nir_loop_terminator::loop_terminator_link, nir_loop_info::loop_terminator_list, nir_loop_terminator::nif, nir_if_last_else_block(), nir_if_last_then_block(), nir_instr_type_phi, nir_is_trivial_loop_if(), nir_ssa_def::parent_instr, nir_src::ssa, and nir_instr::type.
Referenced by get_loop_info().
find_trip_count()
static void find_trip_count (loop_info_state * state) static
References nir_basic_induction_var::alu_def, basic_induction, calculate_iterations(), nir_loop_variable::def, nir_basic_induction_var::def_outside_loop, get_loop_var(), nir_loop_variable::ind, nir_loop::info, nir_basic_induction_var::invariant, nir_loop_info::is_trip_count_known, is_var_constant(), nir_loop_info::limiting_terminator, loop_info_state::loop, nir_loop_info::loop_terminator_list, nir_instr_type_alu, nir_alu_instr::op, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_loop_info::trip_count, and nir_loop_variable::type.
Referenced by get_loop_info().
force_unroll_array_access()
static bool force_unroll_array_access (loop_info_state * state, nir_shader * ns, nir_deref_var * variable) static
References basic_induction, nir_deref::child, nir_variable::data, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_loop_info::force_unroll, get_loop_var(), nir_deref_array::indirect, loop_info_state::indirect_mask, nir_loop::info, loop_info_state::loop, nir_variable::nir_variable_data::mode, nir_deref_array_type_indirect, nir_deref_type_array, nir_src::ssa, nir_loop_info::trip_count, nir_loop_variable::type, nir_deref::type, and nir_deref_var::var.
Referenced by force_unroll_heuristics().
force_unroll_heuristics()
static bool force_unroll_heuristics (loop_info_state * state, nir_shader * ns, nir_block * block) static
References force_unroll_array_access(), instr, nir_intrinsic_instr::intrinsic, nir_foreach_instr, nir_instr_type_intrinsic, nir_intrinsic_infos, nir_intrinsic_info::num_variables, and nir_intrinsic_instr::variables.
Referenced by get_loop_info().
get_iteration()
static int32_t get_iteration (nir_op cond_op, nir_const_value * initial, nir_const_value * step, nir_const_value * limit) static
References nir_const_value::f32, nir_const_value::i32, span, and nir_const_value::u32.
Referenced by calculate_iterations().
get_loop_info()
static void get_loop_info (loop_info_state * state, nir_function_impl * impl) static
References nir_loop::body, compute_induction_information(), compute_invariance_information(), find_loop_terminators(), find_trip_count(), force_unroll_heuristics(), foreach_list_typed_safe, nir_function_impl::function, nir_loop::info, init_loop_block(), initialize_ssa_def(), instr, loop_info_state::loop, nir_loop_info::loop_terminator_list, nir_foreach_block, nir_foreach_block_in_cf_node, nir_foreach_instr, nir_foreach_ssa_def(), and nir_function::shader.
Referenced by process_loops().
get_loop_var()
static nir_loop_variable* get_loop_var (nir_ssa_def * value, loop_info_state * state) static
References nir_ssa_def::index, and loop_info_state::loop_vars.
Referenced by compute_induction_information(), find_trip_count(), force_unroll_array_access(), init_loop_def(), initialize_ssa_def(), and mark_invariant().
init_loop_block()
static bool init_loop_block (nir_block * block, loop_info_state * state, bool in_control_flow) static
References init_loop_state::in_control_flow, nir_loop::info, init_loop_def(), instr, loop_info_state::loop, nir_foreach_instr, nir_foreach_ssa_def(), nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_tex, and nir_loop_info::num_instructions.
Referenced by get_loop_info().
init_loop_def()
static bool init_loop_def (nir_ssa_def * def, void * void_init_loop_state) static
References get_loop_var(), nir_loop_variable::in_control_flow, init_loop_state::in_control_flow, nir_loop_variable::in_loop, nir_loop_variable::process_link, loop_info_state::process_list, and init_loop_state::state.
Referenced by init_loop_block().
initialize_loop_info_state()
static loop_info_state* initialize_loop_info_state (nir_loop * loop, void * mem_ctx, nir_function_impl * impl) static
References nir_loop::info, loop_info_state::loop, nir_loop_info::loop_terminator_list, loop_info_state::loop_vars, loop_info_state::process_list, and nir_function_impl::ssa_alloc.
Referenced by process_loops().
initialize_ssa_def()
static bool initialize_ssa_def (nir_ssa_def * def, void * void_state) static
References nir_loop_variable::def, get_loop_var(), nir_loop_variable::in_loop, nir_basic_induction_var::invariant, nir_instr_type_load_const, nir_ssa_def::parent_instr, nir_loop_variable::type, nir_instr::type, and undefined.
Referenced by get_loop_info().
is_var_alu()
static bool is_var_alu (nir_loop_variable * var) inline static
References nir_loop_variable::def, nir_instr_type_alu, nir_ssa_def::parent_instr, and nir_instr::type.
Referenced by compute_induction_information(), and mark_invariant().
is_var_constant()
static bool is_var_constant (nir_loop_variable * var) inline static
References nir_loop_variable::def, nir_instr_type_load_const, nir_ssa_def::parent_instr, and nir_instr::type.
Referenced by compute_induction_information(), and find_trip_count().
is_var_phi()
static bool is_var_phi (nir_loop_variable * var) inline static
References nir_loop_variable::def, nir_instr_type_phi, nir_ssa_def::parent_instr, and nir_instr::type.
Referenced by compute_induction_information().
mark_invariant()
static bool mark_invariant (nir_ssa_def * def, loop_info_state * state) inline static
References get_loop_var(), nir_loop_variable::in_loop, nir_basic_induction_var::invariant, is_var_alu(), nir_op_infos, not_invariant, nir_op_info::num_inputs, nir_alu_instr::op, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and nir_loop_variable::type.
Referenced by compute_invariance_information().
nir_loop_analyze_impl()
void nir_loop_analyze_impl (nir_function_impl * impl, nir_variable_mode indirect_mask)
References nir_function_impl::body, foreach_list_typed, nir_index_ssa_defs(), and process_loops().
Referenced by nir_metadata_require().
process_loops()
static void process_loops (nir_cf_node * cf_node, nir_variable_mode indirect_mask) static
References nir_loop::body, nir_if::else_list, foreach_list_typed, get_loop_info(), loop_info_state::indirect_mask, initialize_loop_info_state(), mem_ctx, nir_cf_node_get_function(), nir_if::then_list, and nir_cf_node::type.
Referenced by nir_loop_analyze_impl().
test_iterations()
static bool test_iterations (int32_t iter_int, nir_const_value * step, nir_const_value * limit, nir_op cond_op, unsigned bit_size, nir_alu_type induction_base_type, nir_const_value * initial, bool limit_rhs, bool invert_cond) static
References add_src(), nir_const_value::f32, nir_const_value::i32, nir_eval_const_opcode(), nir_op_infos, nir_type_float, nir_type_int, nir_type_uint, and nir_const_value::u32.
Referenced by calculate_iterations().