Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_gs_count_vertices.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static nir_intrinsic_instr * as_intrinsic (nir_instr *instr, nir_intrinsic_op op)
static nir_intrinsic_instr * as_set_vertex_count (nir_instr *instr)
int nir_gs_count_vertices (const nir_shader *shader)
If a geometry shader emits a constant number of vertices, return the number of vertices.
Function Documentation
as_intrinsic()
static nir_intrinsic_instr* as_intrinsic (nir_instr * instr, nir_intrinsic_op op) static
References nir_intrinsic_instr::intrinsic, nir_instr_type_intrinsic, and nir_instr::type.
Referenced by as_set_vertex_count().
as_set_vertex_count()
static nir_intrinsic_instr* as_set_vertex_count (nir_instr * instr) static
References as_intrinsic().
Referenced by nir_gs_count_vertices().
nir_gs_count_vertices()
int nir_gs_count_vertices (const nir_shader * shader)
If a geometry shader emits a constant number of vertices, return the number of vertices.
Otherwise, return -1 (unknown).
This only works if you've used nir_lower_gs_intrinsics() to do vertex counting at the NIR level.
References as_set_vertex_count(), nir_const_value::i32, instr, nir_foreach_function, nir_foreach_instr_reverse, nir_src_as_const_value(), and nir_intrinsic_instr::src.