Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_double_ops.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "c99_math.h"
Functions
static nir_ssa_def * set_exponent (nir_builder *b, nir_ssa_def *src, nir_ssa_def *exp)
static nir_ssa_def * get_exponent (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * get_signed_inf (nir_builder *b, nir_ssa_def *zero)
static nir_ssa_def * fix_inv_result (nir_builder *b, nir_ssa_def *res, nir_ssa_def *src, nir_ssa_def *exp)
static nir_ssa_def * lower_rcp (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_sqrt_rsq (nir_builder *b, nir_ssa_def *src, bool sqrt)
static nir_ssa_def * lower_trunc (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_floor (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_ceil (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_fract (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_round_even (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_mod (nir_builder *b, nir_ssa_def *src0, nir_ssa_def *src1)
static bool lower_doubles_instr (nir_alu_instr *instr, nir_lower_doubles_options options)
static bool nir_lower_doubles_impl (nir_function_impl *impl, nir_lower_doubles_options options)
bool nir_lower_doubles (nir_shader *shader, nir_lower_doubles_options options)
Function Documentation
fix_inv_result()
static nir_ssa_def* fix_inv_result (nir_builder * b, nir_ssa_def * res, nir_ssa_def * src, nir_ssa_def * exp) static
References get_signed_inf(), nir_imm_double(), and nir_imm_int().
Referenced by lower_rcp(), and lower_sqrt_rsq().
get_exponent()
static nir_ssa_def* get_exponent (nir_builder * b, nir_ssa_def * src) static
References nir_imm_int().
Referenced by lower_rcp(), lower_sqrt_rsq(), and lower_trunc().
get_signed_inf()
static nir_ssa_def* get_signed_inf (nir_builder * b, nir_ssa_def * zero) static
References nir_imm_int().
Referenced by fix_inv_result().
lower_ceil()
static nir_ssa_def* lower_ceil (nir_builder * b, nir_ssa_def * src) static
References nir_imm_double().
Referenced by lower_doubles_instr().
lower_doubles_instr()
static bool lower_doubles_instr (nir_alu_instr * instr, nir_lower_doubles_options options) static
References nir_ssa_def::bit_size, nir_instr::block, nir_block::cf_node, nir_builder::cursor, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, nir_dest::is_ssa, lower_ceil(), lower_floor(), lower_fract(), lower_mod(), lower_rcp(), lower_round_even(), lower_sqrt_rsq(), lower_trunc(), nir_before_instr(), nir_builder_init(), nir_cf_node_get_function(), nir_fmov_alu(), nir_instr_remove(), nir_lower_dceil, nir_lower_dfloor, nir_lower_dfract, nir_lower_dmod, nir_lower_drcp, nir_lower_dround_even, nir_lower_drsq, nir_lower_dsqrt, nir_lower_dtrunc, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_def::num_components, nir_alu_instr::op, nir_alu_instr::src, and nir_dest::ssa.
Referenced by nir_lower_doubles_impl().
lower_floor()
static nir_ssa_def* lower_floor (nir_builder * b, nir_ssa_def * src) static
References nir_imm_double().
Referenced by lower_doubles_instr().
lower_fract()
static nir_ssa_def* lower_fract (nir_builder * b, nir_ssa_def * src) static
Referenced by lower_doubles_instr().
lower_mod()
static nir_ssa_def* lower_mod (nir_builder * b, nir_ssa_def * src0, nir_ssa_def * src1) static
References nir_imm_double().
Referenced by lower_doubles_instr().
lower_rcp()
static nir_ssa_def* lower_rcp (nir_builder * b, nir_ssa_def * src) static
References fix_inv_result(), get_exponent(), nir_imm_double(), nir_imm_int(), and set_exponent().
Referenced by lower_doubles_instr().
lower_round_even()
static nir_ssa_def* lower_round_even (nir_builder * b, nir_ssa_def * src) static
References fract(), and nir_imm_double().
Referenced by lower_doubles_instr().
lower_sqrt_rsq()
static nir_ssa_def* lower_sqrt_rsq (nir_builder * b, nir_ssa_def * src, bool sqrt) static
References fix_inv_result(), get_exponent(), nir_imm_double(), nir_imm_int(), and set_exponent().
Referenced by lower_doubles_instr().
lower_trunc()
static nir_ssa_def* lower_trunc (nir_builder * b, nir_ssa_def * src) static
References get_exponent(), nir_imm_double(), and nir_imm_int().
Referenced by lower_doubles_instr().
nir_lower_doubles()
bool nir_lower_doubles (nir_shader * shader, nir_lower_doubles_options options)
References nir_foreach_function, and nir_lower_doubles_impl().
nir_lower_doubles_impl()
static bool nir_lower_doubles_impl (nir_function_impl * impl, nir_lower_doubles_options options) static
References instr, lower_doubles_instr(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_type_alu, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_doubles().
set_exponent()
static nir_ssa_def* set_exponent (nir_builder * b, nir_ssa_def * src, nir_ssa_def * exp) static
References nir_imm_int().
Referenced by lower_rcp(), and lower_sqrt_rsq().