Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_alu_to_scalar.c File Reference
Replaces nir_alu_instr operations with more than one channel used in the arguments with individual per-channel operations.
#include "nir.h"
#include "nir_builder.h"
Macros
#define LOWER_REDUCTION(name, chan, merge)
Functions
static void nir_alu_ssa_dest_init (nir_alu_instr *instr, unsigned num_components, unsigned bit_size)
static void lower_reduction (nir_alu_instr *instr, nir_op chan_op, nir_op merge_op, nir_builder *builder)
static bool lower_alu_instr_scalar (nir_alu_instr *instr, nir_builder *b)
static bool nir_lower_alu_to_scalar_impl (nir_function_impl *impl)
bool nir_lower_alu_to_scalar (nir_shader *shader)
Detailed Description
Replaces nir_alu_instr operations with more than one channel used in the arguments with individual per-channel operations.
Macro Definition Documentation
LOWER_REDUCTION
#define LOWER_REDUCTION (name, chan, merge)
Value:
case name##2: \
   case name##3: \
   case name##4: \
      lower_reduction(instr, chan, merge, b); \
      return true;
Referenced by lower_alu_instr_scalar().
Function Documentation
lower_alu_instr_scalar()
static bool lower_alu_instr_scalar (nir_alu_instr * instr, nir_builder * b) static
References nir_ssa_def::bit_size, nir_builder::cursor, nir_alu_dest::dest, nir_alu_instr::dest, nir_builder::exact, nir_alu_instr::exact, nir_op_info::input_sizes, nir_alu_instr::instr, nir_dest::is_ssa, nir_shader_compiler_options::lower_pack_half_2x16, nir_shader_compiler_options::lower_pack_snorm_2x16, nir_shader_compiler_options::lower_pack_snorm_4x8, nir_shader_compiler_options::lower_pack_unorm_2x16, nir_shader_compiler_options::lower_pack_unorm_4x8, LOWER_REDUCTION, nir_shader_compiler_options::lower_unpack_half_2x16, nir_alu_instr_create(), nir_alu_src_copy(), nir_alu_ssa_dest_init(), nir_before_instr(), nir_builder_instr_insert(), nir_channel(), nir_imm_int(), nir_instr_remove(), nir_op_infos, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_vec(), nir_ssa_def::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_shader::options, nir_alu_dest::saturate, nir_builder::shader, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_alu_src::swizzle, and nir_alu_dest::write_mask.
Referenced by nir_lower_alu_to_scalar_impl().
lower_reduction()
static void lower_reduction (nir_alu_instr * instr, nir_op chan_op, nir_op merge_op, nir_builder * builder) static
References nir_ssa_def::bit_size, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::exact, nir_op_info::input_sizes, nir_alu_instr::instr, nir_alu_instr_create(), nir_alu_src_copy(), nir_alu_ssa_dest_init(), nir_build_alu(), nir_builder_instr_insert(), nir_instr_remove(), nir_op_infos, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_alu_instr::op, nir_builder::shader, nir_alu_instr::src, nir_dest::ssa, nir_alu_src::swizzle, and nir_alu_dest::write_mask.
nir_alu_ssa_dest_init()
static void nir_alu_ssa_dest_init (nir_alu_instr * instr, unsigned num_components, unsigned bit_size) static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, nir_ssa_dest_init(), and nir_alu_dest::write_mask.
Referenced by lower_alu_instr_scalar(), and lower_reduction().
nir_lower_alu_to_scalar()
bool nir_lower_alu_to_scalar (nir_shader * shader)
References nir_foreach_function, and nir_lower_alu_to_scalar_impl().
nir_lower_alu_to_scalar_impl()
static bool nir_lower_alu_to_scalar_impl (nir_function_impl * impl) static
References instr, lower_alu_instr_scalar(), nir_builder_init(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_type_alu, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_alu_to_scalar().