Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_gs_intrinsics.c File Reference
Geometry Shaders can call EmitVertex()/EmitStreamVertex() to output an arbitrary number of vertices.
#include "nir.h"
#include "nir_builder.h"
Data Structures
struct state
Functions
static void rewrite_emit_vertex (nir_intrinsic_instr *intrin, struct state *state)
Replace emit_vertex intrinsics with:
static void rewrite_end_primitive (nir_intrinsic_instr *intrin, struct state *state)
Replace end_primitive with end_primitive_with_counter.
static bool rewrite_intrinsics (nir_block *block, struct state *state)
static void append_set_vertex_count (nir_block *end_block, struct state *state)
Add a set_vertex_count intrinsic at the end of the program (representing the final vertex count).
bool nir_lower_gs_intrinsics (nir_shader *shader)
Detailed Description
Geometry Shaders can call EmitVertex()/EmitStreamVertex() to output an arbitrary number of vertices.
However, the shader must declare the maximum number of vertices that it will ever output - further attempts to emit vertices result in undefined behavior according to the GLSL specification.
Drivers might use this maximum number of vertices to allocate enough space to hold the geometry shader's output. Some drivers (such as i965) need to implement "safety checks" which ensure that the shader hasn't emitted too many vertices, to avoid overflowing that space and trashing other memory.
The count of emitted vertices can also be useful in buffer offset calculations, so drivers know where to write the GS output.
However, for simple geometry shaders that emit a statically determinable number of vertices, this extra bookkeeping is unnecessary and inefficient. By tracking the vertex count in NIR, we allow constant folding/propagation and dead control flow optimizations to eliminate most of it where possible.
This pass introduces a new global variable which stores the current vertex count (initialized to 0), and converts emit_vertex/end_primitive intrinsics to their *_with_counter variants. emit_vertex is also wrapped in a safety check to avoid buffer overflows. Finally, it adds a set_vertex_count intrinsic at the end of the program, informing the driver of the final vertex count.
Function Documentation
append_set_vertex_count()
static void append_set_vertex_count (nir_block * end_block, struct state * state) static
Add a set_vertex_count intrinsic at the end of the program (representing the final vertex count).
References state::builder, nir_builder::cursor, nir_intrinsic_instr::instr, nir_after_block_before_jump(), nir_builder_instr_insert(), nir_intrinsic_instr_create(), nir_load_var(), nir_src_for_ssa(), nir_block::predecessors, nir_builder::shader, nir_intrinsic_instr::src, and state::vertex_count_var.
Referenced by nir_lower_gs_intrinsics().
nir_lower_gs_intrinsics()
bool nir_lower_gs_intrinsics (nir_shader * shader)
References append_set_vertex_count(), nir_function_impl::body, state::builder, nir_builder::cursor, nir_function_impl::end_block, nir_before_cf_list(), nir_builder_init(), nir_foreach_block_safe, nir_imm_int(), nir_local_variable_create(), nir_metadata_preserve(), nir_shader_get_entrypoint(), nir_store_var(), state::progress, rewrite_intrinsics(), and state::vertex_count_var.
rewrite_emit_vertex()
static void rewrite_emit_vertex (nir_intrinsic_instr * intrin, struct state * state) static
Replace emit_vertex intrinsics with:
if (vertex_count < max_vertices) { emit_vertex_with_counter vertex_count ... vertex_count += 1 }
References state::builder, nir_builder::cursor, nir_shader::info, nir_intrinsic_instr::instr, nir_before_instr(), nir_builder_instr_insert(), nir_imm_int(), nir_instr_remove(), nir_intrinsic_instr_create(), nir_load_var(), nir_pop_if(), nir_push_if(), nir_src_for_ssa(), nir_store_var(), state::progress, nir_builder::shader, nir_intrinsic_instr::src, and state::vertex_count_var.
Referenced by rewrite_intrinsics().
rewrite_end_primitive()
static void rewrite_end_primitive (nir_intrinsic_instr * intrin, struct state * state) static
Replace end_primitive with end_primitive_with_counter.
References state::builder, nir_builder::cursor, nir_intrinsic_instr::instr, nir_before_instr(), nir_builder_instr_insert(), nir_instr_remove(), nir_intrinsic_instr_create(), nir_load_var(), nir_src_for_ssa(), state::progress, nir_builder::shader, nir_intrinsic_instr::src, and state::vertex_count_var.
Referenced by rewrite_intrinsics().
rewrite_intrinsics()
static bool rewrite_intrinsics (nir_block * block, struct state * state) static
References instr, nir_intrinsic_instr::intrinsic, nir_foreach_instr_safe, nir_instr_type_intrinsic, rewrite_emit_vertex(), and rewrite_end_primitive().
Referenced by nir_lower_gs_intrinsics().