Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_liveness.c File Reference
#include "nir.h"
#include "nir_worklist.h"
#include "nir_vla.h"
Data Structures
struct live_ssa_defs_state
Functions
static bool index_ssa_def (nir_ssa_def *def, void *void_state)
static bool init_liveness_block (nir_block *block, struct live_ssa_defs_state *state)
static bool set_src_live (nir_src *src, void *void_live)
static bool set_ssa_def_dead (nir_ssa_def *def, void *void_live)
static bool propagate_across_edge (nir_block *pred, nir_block *succ, struct live_ssa_defs_state *state)
Propagates the live in of succ across the edge to the live out of pred.
void nir_live_ssa_defs_impl (nir_function_impl *impl)
static bool src_does_not_use_def (nir_src *src, void *def)
static bool search_for_use_after_instr (nir_instr *start, nir_ssa_def *def)
static bool nir_ssa_def_is_live_at (nir_ssa_def *def, nir_instr *instr)
bool nir_ssa_defs_interfere (nir_ssa_def *a, nir_ssa_def *b)
Function Documentation
index_ssa_def()
static bool index_ssa_def (nir_ssa_def * def, void * void_state) static
References nir_ssa_def::live_index, nir_instr_type_ssa_undef, live_ssa_defs_state::num_ssa_defs, nir_ssa_def::parent_instr, and nir_instr::type.
Referenced by nir_live_ssa_defs_impl().
init_liveness_block()
static bool init_liveness_block (nir_block * block, struct live_ssa_defs_state * state) static
References live_ssa_defs_state::bitset_words, nir_block::live_in, nir_block::live_out, nir_block_worklist_push_head(), and live_ssa_defs_state::worklist.
Referenced by nir_live_ssa_defs_impl().
nir_live_ssa_defs_impl()
void nir_live_ssa_defs_impl (nir_function_impl * impl)
References live_ssa_defs_state::bitset_words, nir_if::condition, if(), index_ssa_def(), init_liveness_block(), instr, nir_block::live_in, nir_block::live_out, nir_block_get_following_if(), nir_block_worklist_fini(), nir_block_worklist_init(), nir_block_worklist_is_empty(), nir_block_worklist_pop_head(), nir_block_worklist_push_tail(), nir_foreach_block, nir_foreach_instr, nir_foreach_instr_reverse, nir_foreach_src(), nir_foreach_ssa_def(), nir_instr_type_phi, nir_function_impl::num_blocks, live_ssa_defs_state::num_ssa_defs, nir_block::predecessors, propagate_across_edge(), set_src_live(), set_ssa_def_dead(), and live_ssa_defs_state::worklist.
Referenced by nir_metadata_require().
nir_ssa_def_is_live_at()
static bool nir_ssa_def_is_live_at (nir_ssa_def * def, nir_instr * instr) static
References nir_instr::block, nir_block::live_in, nir_ssa_def::live_index, nir_block::live_out, nir_ssa_def::parent_instr, and search_for_use_after_instr().
Referenced by nir_ssa_defs_interfere().
nir_ssa_defs_interfere()
bool nir_ssa_defs_interfere (nir_ssa_def * a, nir_ssa_def * b)
References nir_ssa_def::live_index, nir_ssa_def_is_live_at(), and nir_ssa_def::parent_instr.
Referenced by merge_nodes_interfere().
propagate_across_edge()
static bool propagate_across_edge (nir_block * pred, nir_block * succ, struct live_ssa_defs_state * state) static
Propagates the live in of succ across the edge to the live out of pred.
Phi nodes exist "between" blocks and all the phi nodes at the start of a block act "in parallel". When we propagate from the live_in of one block to the live out of the other, we have to kill any writes from phis and make live any sources.
Returns true if updating live out of pred added anything
References live_ssa_defs_state::bitset_words, nir_phi_instr::dest, instr, nir_dest::is_ssa, nir_block::live_in, nir_block::live_out, nir_foreach_instr, nir_foreach_phi_src, nir_instr_type_phi, NIR_VLA, set_src_live(), set_ssa_def_dead(), and nir_dest::ssa.
Referenced by nir_live_ssa_defs_impl().
search_for_use_after_instr()
static bool search_for_use_after_instr (nir_instr * start, nir_ssa_def * def) static
References exec_node_data, instr, exec_node::next, nir_foreach_src(), nir_instr::node, and src_does_not_use_def().
Referenced by nir_ssa_def_is_live_at().
set_src_live()
static bool set_src_live (nir_src * src, void * void_live) static
References nir_src::is_ssa, nir_ssa_def::live_index, and nir_src::ssa.
Referenced by nir_live_ssa_defs_impl(), and propagate_across_edge().
set_ssa_def_dead()
static bool set_ssa_def_dead (nir_ssa_def * def, void * void_live) static
References nir_ssa_def::live_index.
Referenced by nir_live_ssa_defs_impl(), and propagate_across_edge().
src_does_not_use_def()
static bool src_does_not_use_def (nir_src * src, void * def) static
References nir_src::is_ssa, and nir_src::ssa.
Referenced by search_for_use_after_instr().