Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_print.c File Reference
#include "nir.h"
#include "compiler/shader_enums.h"
#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
Data Structures
struct print_state
Functions
static void print_tabs (unsigned num_tabs, FILE *fp)
static void print_annotation (print_state *state, void *obj)
static void print_register (nir_register *reg, print_state *state)
static void print_register_decl (nir_register *reg, print_state *state)
static void print_ssa_def (nir_ssa_def *def, print_state *state)
static void print_ssa_use (nir_ssa_def *def, print_state *state)
static void print_src (nir_src *src, print_state *state)
static void print_reg_src (nir_reg_src *src, print_state *state)
static void print_reg_dest (nir_reg_dest *dest, print_state *state)
static void print_dest (nir_dest *dest, print_state *state)
static void print_alu_src (nir_alu_instr *instr, unsigned src, print_state *state)
static void print_alu_dest (nir_alu_dest *dest, print_state *state)
static void print_alu_instr (nir_alu_instr *instr, print_state *state)
static const char * get_var_name (nir_variable *var, print_state *state)
static void print_constant (nir_constant *c, const struct glsl_type *type, print_state *state)
static const char * get_variable_mode_str (nir_variable_mode mode)
static void print_var_decl (nir_variable *var, print_state *state)
static void print_var (nir_variable *var, print_state *state)
static void print_arg (nir_variable *var, print_state *state)
static void print_deref_var (nir_deref_var *deref, print_state *state)
static void print_deref_array (nir_deref_array *deref, print_state *state)
static void print_deref_struct (nir_deref_struct *deref, const struct glsl_type *parent_type, print_state *state)
static void print_deref (nir_deref_var *deref, print_state *state)
static void print_intrinsic_instr (nir_intrinsic_instr *instr, print_state *state)
static void print_tex_instr (nir_tex_instr *instr, print_state *state)
static void print_call_instr (nir_call_instr *instr, print_state *state)
static void print_load_const_instr (nir_load_const_instr *instr, print_state *state)
static void print_jump_instr (nir_jump_instr *instr, print_state *state)
static void print_ssa_undef_instr (nir_ssa_undef_instr *instr, print_state *state)
static void print_phi_instr (nir_phi_instr *instr, print_state *state)
static void print_parallel_copy_instr (nir_parallel_copy_instr *instr, print_state *state)
static void print_instr (const nir_instr *instr, print_state *state, unsigned tabs)
static int compare_block_index (const void *p1, const void *p2)
static void print_cf_node (nir_cf_node *node, print_state *state, unsigned tabs)
static void print_block (nir_block *block, print_state *state, unsigned tabs)
static void print_if (nir_if *if_stmt, print_state *state, unsigned tabs)
static void print_loop (nir_loop *loop, print_state *state, unsigned tabs)
static void print_cf_node (nir_cf_node *node, print_state *state, unsigned int tabs)
static void print_function_impl (nir_function_impl *impl, print_state *state)
static void print_function (nir_function *function, print_state *state)
static void init_print_state (print_state *state, nir_shader *shader, FILE *fp)
static void destroy_print_state (print_state *state)
void nir_print_shader_annotated (nir_shader *shader, FILE *fp, struct hash_table *annotations)
void nir_print_shader (nir_shader *shader, FILE *fp)
void nir_print_instr (const nir_instr *instr, FILE *fp)
Variables
static const char * sizes [] = { "error", "vec1", "vec2", "vec3", "vec4" }
Function Documentation
compare_block_index()
static int compare_block_index (const void * p1, const void * p2) static
References nir_block::index.
Referenced by print_block().
destroy_print_state()
static void destroy_print_state (print_state * state) static
References print_state::ht, and print_state::syms.
Referenced by nir_print_shader_annotated().
get_var_name()
static const char* get_var_name (nir_variable * var, print_state * state) static
References print_state::ht, print_state::index, nir_variable::name, and print_state::syms.
Referenced by print_arg(), print_var(), and print_var_decl().
get_variable_mode_str()
static const char* get_variable_mode_str (nir_variable_mode mode) static
References nir_var_global, nir_var_local, nir_var_param, nir_var_shader_in, nir_var_shader_out, nir_var_shader_storage, nir_var_shared, nir_var_system_value, and nir_var_uniform.
Referenced by print_var_decl().
init_print_state()
static void init_print_state (print_state * state, nir_shader * shader, FILE * fp) static
References print_state::fp, print_state::ht, print_state::index, print_state::shader, and print_state::syms.
Referenced by nir_print_shader_annotated().
nir_print_instr()
void nir_print_instr (const nir_instr * instr, FILE * fp)
References print_state::fp, and print_instr().
nir_print_shader()
void nir_print_shader (nir_shader * shader, FILE * fp)
References nir_print_shader_annotated().
nir_print_shader_annotated()
void nir_print_shader_annotated (nir_shader * shader, FILE * fp, struct hash_table * annotations)
References print_state::annotations, destroy_print_state(), foreach_list_typed, nir_shader::functions, nir_shader::globals, nir_shader::info, init_print_state(), nir_shader::inputs, nir_foreach_variable, nir_phi_builder_value::node, nir_shader::num_inputs, nir_shader::num_outputs, nir_shader::num_shared, nir_shader::num_uniforms, nir_shader::outputs, print_function(), print_register_decl(), print_var_decl(), nir_shader::registers, nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
Referenced by nir_print_shader().
print_alu_dest()
static void print_alu_dest (nir_alu_dest * dest, print_state * state) static
References nir_alu_dest::dest, print_state::fp, nir_dest::is_ssa, nir_register::num_components, print_dest(), nir_reg_dest::reg, nir_dest::reg, and nir_alu_dest::write_mask.
Referenced by print_alu_instr().
print_alu_instr()
static void print_alu_instr (nir_alu_instr * instr, print_state * state) static
References nir_alu_instr::dest, nir_alu_instr::exact, print_state::fp, nir_op_info::name, nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, print_alu_dest(), print_alu_src(), and nir_alu_dest::saturate.
Referenced by print_instr().
print_alu_src()
static void print_alu_src (nir_alu_instr * instr, unsigned src, print_state * state) static
References nir_alu_src::abs, print_state::fp, nir_src::is_ssa, nir_alu_src::negate, nir_alu_instr_channel_used(), nir_register::num_components, nir_ssa_def::num_components, print_src(), nir_reg_src::reg, nir_src::reg, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and nir_alu_src::swizzle.
Referenced by print_alu_instr().
print_annotation()
static void print_annotation (print_state * state, void * obj) static
References print_state::annotations.
Referenced by print_block(), and print_var_decl().
print_arg()
static void print_arg (nir_variable * var, print_state * state) static
References print_state::fp, get_var_name(), and nir_variable::type.
Referenced by print_function_impl().
print_block()
static void print_block (nir_block * block, print_state * state, unsigned tabs) static
References compare_block_index(), print_state::fp, nir_block::index, instr, nir_foreach_instr, nir_block::predecessors, print_annotation(), print_instr(), print_tabs(), and nir_block::successors.
Referenced by print_cf_node().
print_call_instr()
static void print_call_instr (nir_call_instr * instr, print_state * state) static
References nir_call_instr::callee, print_state::fp, nir_function::name, nir_call_instr::num_params, nir_call_instr::params, print_deref(), and nir_call_instr::return_deref.
Referenced by print_instr().
print_cf_node() [1/2]
static void print_cf_node (nir_cf_node * node, print_state * state, unsigned tabs) static
Referenced by print_function_impl(), print_if(), and print_loop().
print_cf_node() [2/2]
static void print_cf_node (nir_cf_node * node, print_state * state, unsigned int tabs) static
References print_block(), print_if(), print_loop(), and nir_cf_node::type.
print_constant()
static void print_constant (nir_constant * c, const struct glsl_type * type, print_state * state) static
References nir_constant::elements, nir_const_value::f32, nir_const_value::f64, print_state::fp, nir_constant::num_elements, nir_const_value::u32, nir_const_value::u64, and nir_constant::values.
Referenced by print_var_decl().
print_deref()
static void print_deref (nir_deref_var * deref, print_state * state) static
References nir_deref::child, nir_deref_var::deref, nir_deref::deref_type, nir_deref_type_array, nir_deref_type_struct, nir_deref_type_var, print_deref_array(), print_deref_struct(), print_deref_var(), and nir_deref::type.
Referenced by print_call_instr(), print_intrinsic_instr(), and print_tex_instr().
print_deref_array()
static void print_deref_array (nir_deref_array * deref, print_state * state) static
References nir_deref_array::base_offset, nir_deref_array::deref_array_type, print_state::fp, nir_deref_array::indirect, nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_deref_array_type_wildcard, and print_src().
Referenced by print_deref().
print_deref_struct()
static void print_deref_struct (nir_deref_struct * deref, const struct glsl_type * parent_type, print_state * state) static
References print_state::fp, and nir_deref_struct::index.
Referenced by print_deref().
print_deref_var()
static void print_deref_var (nir_deref_var * deref, print_state * state) static
References print_var(), and nir_deref_var::var.
Referenced by print_deref().
print_dest()
static void print_dest (nir_dest * dest, print_state * state) static
References nir_dest::is_ssa, print_reg_dest(), print_ssa_def(), nir_dest::reg, and nir_dest::ssa.
Referenced by print_alu_dest(), print_intrinsic_instr(), print_parallel_copy_instr(), print_phi_instr(), and print_tex_instr().
print_function()
static void print_function (nir_function * function, print_state * state) static
References print_state::fp, nir_parameter_in, nir_parameter_inout, nir_parameter_out, and print_function_impl().
Referenced by nir_print_shader_annotated().
print_function_impl()
static void print_function_impl (nir_function_impl * impl, print_state * state) static
References nir_function_impl::body, nir_function_impl::end_block, foreach_list_typed, print_state::fp, nir_function_impl::function, nir_block::index, nir_function_impl::locals, nir_function::name, nir_foreach_variable, nir_index_blocks(), nir_phi_builder_value::node, nir_function_impl::num_params, nir_function_impl::params, print_arg(), print_cf_node(), print_register_decl(), print_var_decl(), nir_function_impl::registers, and nir_function_impl::return_var.
Referenced by print_function().
print_if()
static void print_if (nir_if * if_stmt, print_state * state, unsigned tabs) static
References nir_if::condition, nir_if::else_list, foreach_list_typed, print_state::fp, nir_phi_builder_value::node, print_cf_node(), print_src(), print_tabs(), and nir_if::then_list.
Referenced by print_cf_node().
print_instr()
static void print_instr (const nir_instr * instr, print_state * state, unsigned tabs) static
References print_state::fp, nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, print_alu_instr(), print_call_instr(), print_intrinsic_instr(), print_jump_instr(), print_load_const_instr(), print_parallel_copy_instr(), print_phi_instr(), print_ssa_undef_instr(), print_tabs(), print_tex_instr(), and nir_instr::type.
Referenced by nir_print_instr(), and print_block().
print_intrinsic_instr()
static void print_intrinsic_instr (nir_intrinsic_instr * instr, print_state * state) static
References nir_intrinsic_instr::const_index, nir_intrinsic_instr::dest, print_state::fp, nir_intrinsic_info::has_dest, nir_intrinsic_info::index_map, nir_shader::inputs, nir_intrinsic_instr::intrinsic, nir_intrinsic_info::name, nir_foreach_variable, NIR_INTRINSIC_BASE, NIR_INTRINSIC_BINDING, NIR_INTRINSIC_COMPONENT, NIR_INTRINSIC_DESC_SET, nir_intrinsic_infos, NIR_INTRINSIC_INTERP_MODE, NIR_INTRINSIC_NUM_INDEX_FLAGS, NIR_INTRINSIC_RANGE, NIR_INTRINSIC_STREAM_ID, NIR_INTRINSIC_UCP_ID, NIR_INTRINSIC_WRMASK, nir_intrinsic_info::num_indices, nir_intrinsic_info::num_srcs, nir_intrinsic_info::num_variables, nir_shader::outputs, print_deref(), print_dest(), print_src(), print_state::shader, nir_intrinsic_instr::src, nir_shader::uniforms, and nir_intrinsic_instr::variables.
Referenced by print_instr().
print_jump_instr()
static void print_jump_instr (nir_jump_instr * instr, print_state * state) static
References print_state::fp, nir_jump_break, nir_jump_continue, nir_jump_return, and nir_jump_instr::type.
Referenced by print_instr().
print_load_const_instr()
static void print_load_const_instr (nir_load_const_instr * instr, print_state * state) static
References nir_ssa_def::bit_size, nir_load_const_instr::def, nir_const_value::f32, nir_const_value::f64, print_state::fp, nir_ssa_def::num_components, print_ssa_def(), nir_const_value::u32, nir_const_value::u64, and nir_load_const_instr::value.
Referenced by print_instr().
print_loop()
static void print_loop (nir_loop * loop, print_state * state, unsigned tabs) static
References nir_loop::body, foreach_list_typed, print_state::fp, nir_phi_builder_value::node, print_cf_node(), and print_tabs().
Referenced by print_cf_node().
print_parallel_copy_instr()
static void print_parallel_copy_instr (nir_parallel_copy_instr * instr, print_state * state) static
References nir_parallel_copy_instr::entries, print_state::fp, nir_foreach_parallel_copy_entry, print_dest(), and print_src().
Referenced by print_instr().
print_phi_instr()
static void print_phi_instr (nir_phi_instr * instr, print_state * state) static
References nir_phi_instr::dest, print_state::fp, nir_foreach_phi_src, print_dest(), print_src(), and nir_phi_instr::srcs.
Referenced by print_instr().
print_reg_dest()
static void print_reg_dest (nir_reg_dest * dest, print_state * state) static
References nir_reg_dest::base_offset, print_state::fp, nir_reg_dest::indirect, nir_register::num_array_elems, print_register(), print_src(), and nir_reg_dest::reg.
Referenced by print_dest().
print_reg_src()
static void print_reg_src (nir_reg_src * src, print_state * state) static
References nir_reg_src::base_offset, print_state::fp, nir_reg_src::indirect, nir_register::num_array_elems, print_register(), print_src(), and nir_reg_src::reg.
Referenced by print_src().
print_register()
static void print_register (nir_register * reg, print_state * state) static
References print_state::fp, nir_register::index, nir_register::is_global, and nir_register::name.
Referenced by print_reg_dest(), print_reg_src(), and print_register_decl().
print_register_decl()
static void print_register_decl (nir_register * reg, print_state * state) static
References nir_register::bit_size, print_state::fp, nir_register::is_packed, nir_register::num_array_elems, nir_register::num_components, print_register(), and sizes.
Referenced by nir_print_shader_annotated(), and print_function_impl().
print_src()
static void print_src (nir_src * src, print_state * state) static
References nir_src::is_ssa, print_reg_src(), print_ssa_use(), nir_src::reg, and nir_src::ssa.
Referenced by print_alu_src(), print_deref_array(), print_if(), print_intrinsic_instr(), print_parallel_copy_instr(), print_phi_instr(), print_reg_dest(), print_reg_src(), print_ssa_use(), and print_tex_instr().
print_ssa_def()
static void print_ssa_def (nir_ssa_def * def, print_state * state) static
References nir_ssa_def::bit_size, print_state::fp, nir_ssa_def::index, nir_ssa_def::name, nir_ssa_def::num_components, and sizes.
Referenced by print_dest(), print_load_const_instr(), and print_ssa_undef_instr().
print_ssa_undef_instr()
static void print_ssa_undef_instr (nir_ssa_undef_instr * instr, print_state * state) static
References nir_ssa_undef_instr::def, print_state::fp, and print_ssa_def().
Referenced by print_instr().
print_ssa_use()
static void print_ssa_use (nir_ssa_def * def, print_state * state) static
References print_state::fp, nir_ssa_def::index, nir_ssa_def::name, and print_src().
Referenced by print_src().
print_tabs()
static void print_tabs (unsigned num_tabs, FILE * fp) static
Referenced by print_block(), print_if(), print_instr(), and print_loop().
print_tex_instr()
static void print_tex_instr (nir_tex_instr * instr, print_state * state) static
References nir_tex_instr::component, nir_tex_instr::dest, print_state::fp, nir_tex_src_bias, nir_tex_src_comparator, nir_tex_src_coord, nir_tex_src_ddx, nir_tex_src_ddy, nir_tex_src_lod, nir_tex_src_ms_index, nir_tex_src_ms_mcs, nir_tex_src_offset, nir_tex_src_plane, nir_tex_src_projector, nir_tex_src_sampler_offset, nir_tex_src_texture_offset, nir_texop_lod, nir_texop_query_levels, nir_texop_samples_identical, nir_texop_tex, nir_texop_texture_samples, nir_texop_tg4, nir_texop_txb, nir_texop_txd, nir_texop_txf, nir_texop_txf_ms, nir_texop_txf_ms_mcs, nir_texop_txl, nir_texop_txs, nir_tex_instr::num_srcs, nir_tex_instr::op, print_deref(), print_dest(), print_src(), nir_tex_instr::sampler, nir_tex_instr::sampler_index, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_tex_instr::texture, and nir_tex_instr::texture_index.
Referenced by print_instr().
print_var()
static void print_var (nir_variable * var, print_state * state) static
References print_state::fp, and get_var_name().
Referenced by print_deref_var().
print_var_decl()
static void print_var_decl (nir_variable * var, print_state * state) static
References nir_variable::nir_variable_data::_volatile, nir_variable::nir_variable_data::binding, nir_variable::nir_variable_data::centroid, nir_variable::nir_variable_data::coherent, nir_variable::nir_variable_data::compact, nir_variable::constant_initializer, nir_variable::data, nir_variable::nir_variable_data::driver_location, print_state::fp, get_var_name(), get_variable_mode_str(), nir_variable::nir_variable_data::image, nir_variable::nir_variable_data::interpolation, nir_variable::nir_variable_data::invariant, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_var_shader_in, nir_var_shader_out, nir_var_shader_storage, nir_var_uniform, nir_variable::nir_variable_data::patch, print_annotation(), print_constant(), nir_variable::nir_variable_data::read_only, nir_variable::nir_variable_data::restrict_flag, nir_variable::nir_variable_data::sample, print_state::shader, nir_shader::stage, nir_variable::type, and nir_variable::nir_variable_data::write_only.
Referenced by nir_print_shader_annotated(), and print_function_impl().
Variable Documentation
sizes
const char* sizes[] = { "error", "vec1", "vec2", "vec3", "vec4" } static
Referenced by print_register_decl(), and print_ssa_def().