Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_locals_to_regs.c File Reference
#include "nir.h"
#include "nir_array.h"
Data Structures
struct locals_to_regs_state
Functions
static uint32_t hash_deref (const void *void_deref)
static bool derefs_equal (const void *void_a, const void *void_b)
static nir_register * get_reg_for_deref (nir_deref_var *deref, struct locals_to_regs_state *state)
static nir_src get_deref_reg_src (nir_deref_var *deref, nir_instr *instr, struct locals_to_regs_state *state)
static bool lower_locals_to_regs_block (nir_block *block, struct locals_to_regs_state *state)
static bool nir_lower_locals_to_regs_impl (nir_function_impl *impl)
bool nir_lower_locals_to_regs (nir_shader *shader)
Function Documentation
derefs_equal()
static bool derefs_equal (const void * void_a, const void * void_b) static
References nir_deref::child, nir_deref_var::deref, nir_deref_type_struct, and nir_deref_var::var.
Referenced by nir_lower_locals_to_regs_impl().
get_deref_reg_src()
static nir_src get_deref_reg_src (nir_deref_var * deref, nir_instr * instr, struct locals_to_regs_state * state) static
References add(), nir_reg_src::base_offset, nir_deref_array::base_offset, nir_deref::child, nir_load_const_instr::def, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_alu_dest::dest, nir_alu_instr::dest, get_reg_for_deref(), nir_reg_src::indirect, nir_deref_array::indirect, nir_alu_instr::instr, nir_load_const_instr::instr, nir_src::is_ssa, mul(), nir_alu_instr_create(), nir_deref_array_type_indirect, nir_deref_type_array, nir_instr_insert_before(), nir_load_const_instr_create(), nir_src_copy(), nir_ssa_dest_init(), nir_register::num_array_elems, nir_reg_src::reg, nir_src::reg, locals_to_regs_state::shader, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_deref::type, nir_const_value::u32, nir_load_const_instr::value, and nir_alu_dest::write_mask.
Referenced by lower_locals_to_regs_block().
get_reg_for_deref()
static nir_register* get_reg_for_deref (nir_deref_var * deref, struct locals_to_regs_state * state) static
References nir_register::bit_size, nir_deref::child, nir_variable::constant_initializer, nir_deref_var::deref, nir_deref::deref_type, hash_deref(), locals_to_regs_state::impl, nir_deref_type_array, nir_local_reg_create(), nir_register::num_array_elems, nir_register::num_components, locals_to_regs_state::regs_table, nir_deref::type, and nir_deref_var::var.
Referenced by get_deref_reg_src().
hash_deref()
static uint32_t hash_deref (const void * void_deref) static
References nir_deref::child, nir_deref_var::deref, deref, nir_deref_struct::index, nir_deref_type_struct, and nir_deref_var::var.
Referenced by get_reg_for_deref(), and nir_lower_locals_to_regs_impl().
lower_locals_to_regs_block()
static bool lower_locals_to_regs_block (nir_block * block, struct locals_to_regs_state * state) static
References nir_reg_src::base_offset, nir_reg_dest::base_offset, nir_ssa_def::bit_size, nir_variable::data, nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, get_deref_reg_src(), nir_reg_src::indirect, nir_reg_dest::indirect, nir_alu_instr::instr, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, nir_variable::nir_variable_data::mode, nir_alu_instr_create(), nir_dest_copy(), nir_foreach_instr_safe, nir_instr_insert_before(), nir_instr_remove(), nir_instr_type_intrinsic, nir_src_copy(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_var_local, nir_intrinsic_instr::num_components, locals_to_regs_state::progress, nir_reg_src::reg, nir_reg_dest::reg, nir_src::reg, nir_dest::reg, locals_to_regs_state::shader, nir_alu_src::src, nir_alu_instr::src, nir_intrinsic_instr::src, nir_dest::ssa, nir_deref_var::var, nir_intrinsic_instr::variables, and nir_alu_dest::write_mask.
Referenced by nir_lower_locals_to_regs_impl().
nir_lower_locals_to_regs()
bool nir_lower_locals_to_regs (nir_shader * shader)
References nir_foreach_function, nir_lower_locals_to_regs_impl(), and locals_to_regs_state::progress.
nir_lower_locals_to_regs_impl()
static bool nir_lower_locals_to_regs_impl (nir_function_impl * impl) static
References derefs_equal(), nir_function_impl::function, hash_deref(), locals_to_regs_state::impl, lower_locals_to_regs_block(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), locals_to_regs_state::progress, locals_to_regs_state::regs_table, locals_to_regs_state::shader, and nir_function::shader.
Referenced by nir_lower_locals_to_regs().