Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_clip_cull_distance_arrays.c File Reference
This pass combines separate clip and cull distance arrays into a single array that contains both.
#include "nir.h"
#include "nir_builder.h"
Functions
static unsigned get_unwrapped_array_length (nir_shader *nir, nir_variable *var)
Get the length of the clip/cull distance array, looking past any interface block arrays.
static void update_type (nir_variable *var, gl_shader_stage stage, unsigned length)
Update the type of the combined array (including interface block nesting).
static void rewrite_references (nir_instr *instr, nir_variable *combined, unsigned cull_offset)
Rewrite any clip/cull distances to refer to the new combined array.
static bool combine_clip_cull (nir_shader *nir, struct exec_list *vars, bool store_info)
bool nir_lower_clip_cull_distance_arrays (nir_shader *nir)
Detailed Description
This pass combines separate clip and cull distance arrays into a single array that contains both.
Clip distances come first, then cull distances. It also populates nir_shader_info with the size of the original arrays so the driver knows which are which.
Function Documentation
combine_clip_cull()
static bool combine_clip_cull (nir_shader * nir, struct exec_list * vars, bool store_info) static
References nir_variable::nir_variable_data::compact, nir_variable::data, get_unwrapped_array_length(), nir_shader::info, instr, nir_variable::nir_variable_data::location, nir_foreach_block, nir_foreach_function, nir_foreach_instr, nir_foreach_variable, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_variable::node, rewrite_references(), nir_shader::stage, and update_type().
Referenced by nir_lower_clip_cull_distance_arrays().
get_unwrapped_array_length()
static unsigned get_unwrapped_array_length (nir_shader * nir, nir_variable * var) static
Get the length of the clip/cull distance array, looking past any interface block arrays.
References nir_is_per_vertex_io(), nir_shader::stage, nir_variable::type, and type.
Referenced by combine_clip_cull().
nir_lower_clip_cull_distance_arrays()
bool nir_lower_clip_cull_distance_arrays (nir_shader * nir)
References combine_clip_cull(), nir_shader::inputs, nir_shader::outputs, and nir_shader::stage.
rewrite_references()
static void rewrite_references (nir_instr * instr, nir_variable * combined, unsigned cull_offset) static
Rewrite any clip/cull distances to refer to the new combined array.
References nir_deref_array::base_offset, nir_deref::child, nir_variable::data, nir_deref_var::deref, deref, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_instr_type_intrinsic, nir_variable::type, nir_instr::type, nir_deref::type, type, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by combine_clip_cull().
update_type()
static void update_type (nir_variable * var, gl_shader_stage stage, unsigned length) static
Update the type of the combined array (including interface block nesting).
References nir_is_per_vertex_io(), nir_variable::type, and type.
Referenced by combine_clip_cull().