Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_regs_to_ssa.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "nir_phi_builder.h"
#include "nir_vla.h"
Data Structures
struct regs_to_ssa_state
Functions
static bool rewrite_src (nir_src *src, void *_state)
static void rewrite_if_condition (nir_if *nif, struct regs_to_ssa_state *state)
static bool rewrite_dest (nir_dest *dest, void *_state)
static void rewrite_alu_instr (nir_alu_instr *alu, struct regs_to_ssa_state *state)
bool nir_lower_regs_to_ssa_impl (nir_function_impl *impl)
bool nir_lower_regs_to_ssa (nir_shader *shader)
Function Documentation
nir_lower_regs_to_ssa()
bool nir_lower_regs_to_ssa (nir_shader * shader)
References nir_foreach_function, nir_lower_regs_to_ssa_impl(), and nir_shader::registers.
nir_lower_regs_to_ssa_impl()
bool nir_lower_regs_to_ssa_impl (nir_function_impl * impl)
References nir_function_impl::function, instr, nir_block_get_following_if(), nir_foreach_block, nir_foreach_def, nir_foreach_dest(), nir_foreach_instr, nir_foreach_register, nir_foreach_register_safe, nir_foreach_src(), nir_index_local_regs(), nir_instr_type_alu, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), nir_phi_builder_add_value(), nir_phi_builder_create(), nir_phi_builder_finish(), NIR_VLA, nir_function_impl::num_blocks, nir_function_impl::reg_alloc, nir_function_impl::registers, rewrite_alu_instr(), rewrite_dest(), rewrite_if_condition(), rewrite_src(), regs_to_ssa_state::shader, nir_function::shader, and regs_to_ssa_state::values.
Referenced by nir_lower_regs_to_ssa(), nir_opt_if(), nir_opt_loop_unroll_impl(), and nir_opt_trivial_continues().
rewrite_alu_instr()
static void rewrite_alu_instr (nir_alu_instr * alu, struct regs_to_ssa_state * state) static
References nir_register::bit_size, nir_instr::block, nir_reg_dest::def_link, nir_alu_dest::dest, nir_alu_instr::dest, nir_register::index, nir_op_info::input_sizes, nir_alu_instr::instr, nir_dest::is_ssa, nir_register::name, nir_after_instr(), nir_alu_instr_create(), nir_foreach_src(), nir_instr_insert(), nir_op_infos, nir_phi_builder_value_get_block_def(), nir_phi_builder_value_set_block_def(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_phi_builder_value::num_components, nir_register::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_op_info::output_size, nir_reg_dest::reg, nir_dest::reg, rewrite_dest(), rewrite_src(), regs_to_ssa_state::shader, nir_alu_src::src, nir_alu_instr::src, nir_dest::ssa, nir_alu_src::swizzle, regs_to_ssa_state::values, and nir_alu_dest::write_mask.
Referenced by nir_lower_regs_to_ssa_impl().
rewrite_dest()
static bool rewrite_dest (nir_dest * dest, void * _state) static
References nir_register::bit_size, nir_instr::block, nir_reg_dest::def_link, nir_register::index, instr, nir_dest::is_ssa, nir_register::name, nir_phi_builder_value_set_block_def(), nir_ssa_dest_init(), nir_register::num_components, nir_reg_dest::parent_instr, nir_reg_dest::reg, nir_dest::reg, nir_dest::ssa, and regs_to_ssa_state::values.
Referenced by nir_lower_regs_to_ssa_impl(), and rewrite_alu_instr().
rewrite_if_condition()
static void rewrite_if_condition (nir_if * nif, struct regs_to_ssa_state * state) static
References nir_if::cf_node, nir_if::condition, nir_register::index, nir_src::is_ssa, nir_cf_node_prev(), nir_if_rewrite_condition(), nir_phi_builder_value_get_block_def(), nir_src_for_ssa(), nir_reg_src::reg, nir_src::reg, and regs_to_ssa_state::values.
Referenced by nir_lower_regs_to_ssa_impl().
rewrite_src()
static bool rewrite_src (nir_src * src, void * _state) static
References nir_instr::block, exec_node_data, nir_register::index, instr, nir_src::is_ssa, nir_instr_rewrite_src(), nir_instr_type_phi, nir_phi_builder_value_get_block_def(), nir_src_for_ssa(), nir_src::parent_instr, nir_phi_src::pred, nir_reg_src::reg, nir_src::reg, nir_instr::type, and regs_to_ssa_state::values.
Referenced by nir_lower_regs_to_ssa_impl(), and rewrite_alu_instr().