Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_var_copies.c File Reference
#include "nir.h"
#include "compiler/nir_types.h"
Functions
static nir_deref * deref_next_wildcard_parent (nir_deref *deref)
static void emit_copy_load_store (nir_intrinsic_instr *copy_instr, nir_deref_var *dest_head, nir_deref_var *src_head, nir_deref *dest_tail, nir_deref *src_tail, nir_shader *shader)
void nir_lower_var_copy_instr (nir_intrinsic_instr *copy, nir_shader *shader)
static bool lower_var_copies_impl (nir_function_impl *impl)
bool nir_lower_var_copies (nir_shader *shader)
Function Documentation
deref_next_wildcard_parent()
static nir_deref* deref_next_wildcard_parent (nir_deref * deref) static
References nir_deref::child, nir_deref_array::deref_array_type, nir_deref_array_type_wildcard, and nir_deref_type_array.
Referenced by emit_copy_load_store().
emit_copy_load_store()
static void emit_copy_load_store (nir_intrinsic_instr * copy_instr, nir_deref_var * dest_head, nir_deref_var * src_head, nir_deref * dest_tail, nir_deref * src_tail, nir_shader * shader) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref, nir_deref_array::deref_array_type, deref_next_wildcard_parent(), nir_intrinsic_instr::dest, nir_intrinsic_instr::instr, nir_src::is_ssa, nir_deref_array_type_direct, nir_deref_array_type_wildcard, nir_deref_var_clone(), nir_instr_insert_before(), nir_intrinsic_instr_create(), nir_ssa_dest_init(), nir_intrinsic_instr::num_components, nir_intrinsic_instr::src, nir_src::ssa, nir_dest::ssa, nir_deref::type, and nir_intrinsic_instr::variables.
Referenced by nir_lower_var_copy_instr().
lower_var_copies_impl()
static bool lower_var_copies_impl (nir_function_impl * impl) static
References nir_function_impl::function, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_foreach_block, nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_intrinsic, nir_lower_var_copy_instr(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and nir_function::shader.
Referenced by nir_lower_var_copies().
nir_lower_var_copies()
bool nir_lower_var_copies (nir_shader * shader)
References lower_var_copies_impl(), and nir_foreach_function.
nir_lower_var_copy_instr()
void nir_lower_var_copy_instr (nir_intrinsic_instr * copy, nir_shader * shader)
References nir_deref_var::deref, emit_copy_load_store(), nir_intrinsic_instr::intrinsic, and nir_intrinsic_instr::variables.
Referenced by lower_copies_to_load_store(), and lower_var_copies_impl().