Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_instr_set.c File Reference
#include "nir_instr_set.h"
#include "nir_vla.h"
Macros
#define HASH(hash, data) _mesa_fnv32_1a_accumulate((hash), (data))
Functions
static uint32_t hash_src (uint32_t hash, const nir_src *src)
static uint32_t hash_alu_src (uint32_t hash, const nir_alu_src *src, unsigned num_components)
static uint32_t hash_alu (uint32_t hash, const nir_alu_instr *instr)
static uint32_t hash_load_const (uint32_t hash, const nir_load_const_instr *instr)
static int cmp_phi_src (const void *data1, const void *data2)
static uint32_t hash_phi (uint32_t hash, const nir_phi_instr *instr)
static uint32_t hash_intrinsic (uint32_t hash, const nir_intrinsic_instr *instr)
static uint32_t hash_tex (uint32_t hash, const nir_tex_instr *instr)
static uint32_t hash_instr (const void *data)
bool nir_srcs_equal (nir_src src1, nir_src src2)
bool nir_alu_srcs_equal (const nir_alu_instr *alu1, const nir_alu_instr *alu2, unsigned src1, unsigned src2)
static bool nir_instrs_equal (const nir_instr *instr1, const nir_instr *instr2)
static bool src_is_ssa (nir_src *src, void *data)
static bool dest_is_ssa (nir_dest *dest, void *data)
static bool instr_can_rewrite (nir_instr *instr)
static nir_ssa_def * nir_instr_get_dest_ssa_def (nir_instr *instr)
static bool cmp_func (const void *data1, const void *data2)
struct set * nir_instr_set_create (void *mem_ctx)
This file defines functions for creating, destroying, and manipulating an "instruction set," which is an abstraction for finding duplicate instructions using a hash set.
void nir_instr_set_destroy (struct set *instr_set)
Destroys an instruction set.
bool nir_instr_set_add_or_rewrite (struct set *instr_set, nir_instr *instr)
Adds an instruction to an instruction set if it doesn't exist, or if it does already exist, rewrites all uses of it to point to the other already-inserted instruction.
void nir_instr_set_remove (struct set *instr_set, nir_instr *instr)
Removes an instruction from an instruction set, so that other instructions won't be merged with it.
Macro Definition Documentation
HASH
#define HASH (hash, data) _mesa_fnv32_1a_accumulate((hash), (data))
Referenced by hash_alu(), hash_alu_src(), hash_intrinsic(), hash_load_const(), hash_phi(), hash_src(), and hash_tex().
Function Documentation
cmp_func()
static bool cmp_func (const void * data1, const void * data2) static
References nir_instrs_equal().
Referenced by nir_instr_set_create().
cmp_phi_src()
static int cmp_phi_src (const void * data1, const void * data2) static
References nir_phi_src::pred.
Referenced by hash_phi().
dest_is_ssa()
static bool dest_is_ssa (nir_dest * dest, void * data) static
References nir_dest::is_ssa, and void.
Referenced by instr_can_rewrite().
hash_alu()
static uint32_t hash_alu (uint32_t hash, const nir_alu_instr * instr) static
References nir_op_info::algebraic_properties, nir_ssa_def::bit_size, nir_alu_dest::dest, nir_alu_instr::dest, HASH, hash_alu_src(), nir_op_infos, NIR_OP_IS_COMMUTATIVE, nir_ssa_alu_instr_src_components(), nir_ssa_def::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_instr::src, and nir_dest::ssa.
Referenced by hash_instr().
hash_alu_src()
static uint32_t hash_alu_src (uint32_t hash, const nir_alu_src * src, unsigned num_components) static
References nir_alu_src::abs, HASH, hash_src(), nir_alu_src::negate, nir_alu_src::src, and nir_alu_src::swizzle.
Referenced by hash_alu().
hash_instr()
static uint32_t hash_instr (const void * data) static
References hash_alu(), hash_intrinsic(), hash_load_const(), hash_phi(), hash_tex(), instr, nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_load_const, nir_instr_type_phi, nir_instr_type_tex, and nir_instr::type.
Referenced by nir_instr_set_create().
hash_intrinsic()
static uint32_t hash_intrinsic (uint32_t hash, const nir_intrinsic_instr * instr) static
References nir_ssa_def::bit_size, nir_intrinsic_instr::const_index, nir_intrinsic_instr::dest, nir_intrinsic_info::has_dest, HASH, nir_intrinsic_instr::intrinsic, nir_intrinsic_infos, nir_ssa_def::num_components, nir_intrinsic_info::num_indices, nir_intrinsic_info::num_variables, and nir_dest::ssa.
Referenced by hash_instr().
hash_load_const()
static uint32_t hash_load_const (uint32_t hash, const nir_load_const_instr * instr) static
References nir_ssa_def::bit_size, nir_load_const_instr::def, nir_const_value::f32, HASH, nir_ssa_def::num_components, and nir_load_const_instr::value.
Referenced by hash_instr().
hash_phi()
static uint32_t hash_phi (uint32_t hash, const nir_phi_instr * instr) static
References nir_instr::block, cmp_phi_src(), HASH, hash_src(), nir_phi_instr::instr, nir_foreach_phi_src, NIR_VLA, and nir_block::predecessors.
Referenced by hash_instr().
hash_src()
static uint32_t hash_src (uint32_t hash, const nir_src * src) static
References HASH, nir_src::is_ssa, and nir_src::ssa.
Referenced by hash_alu_src(), hash_phi(), and hash_tex().
hash_tex()
static uint32_t hash_tex (uint32_t hash, const nir_tex_instr * instr) static
References nir_tex_instr::component, nir_tex_instr::coord_components, HASH, hash_src(), nir_tex_instr::is_array, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, nir_tex_instr::num_srcs, nir_tex_instr::op, nir_tex_instr::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_tex_instr::texture, nir_tex_instr::texture_array_size, and nir_tex_instr::texture_index.
Referenced by hash_instr().
instr_can_rewrite()
static bool instr_can_rewrite (nir_instr * instr) static
References dest_is_ssa(), nir_intrinsic_info::flags, nir_foreach_dest(), nir_foreach_src(), nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, NIR_INTRINSIC_CAN_ELIMINATE, NIR_INTRINSIC_CAN_REORDER, nir_intrinsic_infos, nir_intrinsic_info::num_variables, nir_tex_instr::sampler, src_is_ssa(), nir_tex_instr::texture, and nir_instr::type.
Referenced by nir_instr_set_add_or_rewrite(), and nir_instr_set_remove().
nir_alu_srcs_equal()
bool nir_alu_srcs_equal (const nir_alu_instr * alu1, const nir_alu_instr * alu2, unsigned src1, unsigned src2)
References nir_alu_src::abs, nir_alu_src::negate, nir_srcs_equal(), nir_ssa_alu_instr_src_components(), nir_alu_src::src, nir_alu_instr::src, and nir_alu_src::swizzle.
Referenced by matching_mov(), nir_instrs_equal(), and nir_ssa_alu_instr_src_components().
nir_instr_get_dest_ssa_def()
static nir_ssa_def* nir_instr_get_dest_ssa_def (nir_instr * instr) static
References nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_load_const, nir_instr_type_phi, nir_instr_type_tex, and nir_instr::type.
Referenced by nir_instr_set_add_or_rewrite().
nir_instr_set_add_or_rewrite()
bool nir_instr_set_add_or_rewrite (struct set * instr_set, nir_instr * instr)
Adds an instruction to an instruction set if it doesn't exist, or if it does already exist, rewrites all uses of it to point to the other already-inserted instruction.
Returns 'true' if the uses of the instruction were rewritten.
References instr_can_rewrite(), nir_instr_get_dest_ssa_def(), nir_instr_type_alu, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_instr::type.
Referenced by cse_block(), and opt_gcm_impl().
nir_instr_set_create()
struct set* nir_instr_set_create (void * mem_ctx)
This file defines functions for creating, destroying, and manipulating an "instruction set," which is an abstraction for finding duplicate instructions using a hash set.
Note that the question of whether an instruction is actually a duplicate (e.g. whether it has any side effects) is handled transparently. The user can pass any instruction to nir_instr_set_add_or_rewrite() and nir_instr_set_remove(), and if the instruction isn't safe to rewrite or isn't supported, it's silently removed.Creates an instruction set, using a given ralloc mem_ctx
References cmp_func(), and hash_instr().
Referenced by nir_opt_cse_impl(), and opt_gcm_impl().
nir_instr_set_destroy()
void nir_instr_set_destroy (struct set * instr_set)
Destroys an instruction set.
Referenced by nir_opt_cse_impl(), and opt_gcm_impl().
nir_instr_set_remove()
void nir_instr_set_remove (struct set * instr_set, nir_instr * instr)
Removes an instruction from an instruction set, so that other instructions won't be merged with it.
References instr_can_rewrite().
Referenced by cse_block().
nir_instrs_equal()
static bool nir_instrs_equal (const nir_instr * instr1, const nir_instr * instr2) static
References nir_op_info::algebraic_properties, nir_ssa_def::bit_size, nir_instr::block, nir_tex_instr::component, nir_intrinsic_instr::const_index, nir_tex_instr::coord_components, nir_load_const_instr::def, nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, nir_const_value::f32, nir_intrinsic_info::has_dest, nir_phi_instr::instr, nir_intrinsic_instr::intrinsic, nir_tex_instr::is_array, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, nir_alu_srcs_equal(), nir_foreach_phi_src, nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, nir_intrinsic_infos, nir_op_infos, NIR_OP_IS_COMMUTATIVE, nir_srcs_equal(), nir_ssa_def::num_components, nir_intrinsic_instr::num_components, nir_intrinsic_info::num_indices, nir_op_info::num_inputs, nir_intrinsic_info::num_srcs, nir_tex_instr::num_srcs, nir_intrinsic_info::num_variables, nir_alu_instr::op, nir_tex_instr::op, nir_tex_instr::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_intrinsic_instr::src, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_dest::ssa, nir_tex_instr::texture, nir_tex_instr::texture_array_size, nir_tex_instr::texture_index, nir_instr::type, and nir_load_const_instr::value.
Referenced by cmp_func().
nir_srcs_equal()
bool nir_srcs_equal (nir_src src1, nir_src src2)
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by insert_mov(), nir_alu_srcs_equal(), nir_instrs_equal(), and resolve_parallel_copy().
src_is_ssa()
static bool src_is_ssa (nir_src * src, void * data) static
References nir_src::is_ssa, and void.
Referenced by instr_can_rewrite().