Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_move_vec_src_uses_to_dest.c File Reference
#include "nir.h"
Functions
static bool ssa_def_dominates_instr (nir_ssa_def *def, nir_instr *instr)
static bool move_vec_src_uses_to_dest_block (nir_block *block)
static bool nir_move_vec_src_uses_to_dest_impl (nir_shader *shader, nir_function_impl *impl)
bool nir_move_vec_src_uses_to_dest (nir_shader *shader)
Function Documentation
move_vec_src_uses_to_dest_block()
static bool move_vec_src_uses_to_dest_block (nir_block * block) static
References nir_alu_src::abs, nir_alu_dest::dest, nir_alu_instr::dest, exec_node_data, nir_alu_instr::instr, instr, nir_src::is_ssa, nir_dest::is_ssa, nir_alu_src::negate, nir_alu_instr_channel_used(), nir_foreach_instr, nir_foreach_use_safe, nir_instr_rewrite_src(), nir_instr_type_alu, nir_op_infos, nir_src_for_ssa(), nir_op_info::num_inputs, nir_alu_instr::op, nir_ssa_def::parent_instr, nir_alu_dest::saturate, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, ssa_def_dominates_instr(), swizzle(), and nir_alu_src::swizzle.
Referenced by nir_move_vec_src_uses_to_dest_impl().
nir_move_vec_src_uses_to_dest()
bool nir_move_vec_src_uses_to_dest (nir_shader * shader)
References nir_foreach_function, and nir_move_vec_src_uses_to_dest_impl().
nir_move_vec_src_uses_to_dest_impl()
static bool nir_move_vec_src_uses_to_dest_impl (nir_shader * shader, nir_function_impl * impl) static
References move_vec_src_uses_to_dest_block(), nir_foreach_block, nir_index_instrs(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and nir_metadata_require().
Referenced by nir_move_vec_src_uses_to_dest().
ssa_def_dominates_instr()
static bool ssa_def_dominates_instr (nir_ssa_def * def, nir_instr * instr) static
References nir_instr::block, nir_instr::index, nir_block_dominates(), and nir_ssa_def::parent_instr.
Referenced by move_vec_src_uses_to_dest_block().