Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_trivial_continues.c File Reference
#include "nir.h"
Functions
static bool instr_is_continue (nir_instr *instr)
static bool lower_trivial_continues_block (nir_block *block, nir_loop *loop)
static bool lower_trivial_continues_list (struct exec_list *cf_list, bool list_ends_at_loop_tail, nir_loop *loop)
bool nir_opt_trivial_continues (nir_shader *shader)
This simple pass gets rid of any "trivial" continues, i.e.
Function Documentation
instr_is_continue()
static bool instr_is_continue (nir_instr * instr) static
References nir_instr_type_jump, nir_jump_continue, and nir_instr::type.
Referenced by lower_trivial_continues_block().
lower_trivial_continues_block()
static bool lower_trivial_continues_block (nir_block * block, nir_loop * loop) static
References nir_block::cf_node, instr_is_continue(), nir_block_first_instr(), nir_block_last_instr(), nir_cf_node_prev(), nir_if_last_else_block(), nir_if_last_then_block(), nir_instr_remove(), nir_loop_first_block(), nir_lower_phis_to_regs_block(), and nir_cf_node::type.
Referenced by lower_trivial_continues_list().
lower_trivial_continues_list()
static bool lower_trivial_continues_list (struct exec_list * cf_list, bool list_ends_at_loop_tail, nir_loop * loop) static
References nir_loop::body, cf_node, nir_if::else_list, foreach_list_typed, lower_trivial_continues_block(), nir_loop_last_block(), and nir_if::then_list.
Referenced by nir_opt_trivial_continues().
nir_opt_trivial_continues()
bool nir_opt_trivial_continues (nir_shader * shader)
This simple pass gets rid of any "trivial" continues, i.e.
those that are at the tail of a loop where we can just delete the continue instruction and control-flow will naturally and harmlessly take us back to the top of the loop.
References lower_trivial_continues_list(), nir_foreach_function, nir_lower_regs_to_ssa_impl(), nir_metadata_none, and nir_metadata_preserve().