Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_load_const_to_scalar.c File Reference
Replaces vector nir_load_const instructions with a series of loads and a vec[234] to reconstruct the original vector (on the assumption that nir_lower_alu_to_scalar() will then be used to split it up).
#include "util/macros.h"
#include "nir.h"
#include "nir_builder.h"
Functions
static bool lower_load_const_instr_scalar (nir_load_const_instr *lower)
static bool nir_lower_load_const_to_scalar_impl (nir_function_impl *impl)
bool nir_lower_load_const_to_scalar (nir_shader *shader)
Detailed Description
Replaces vector nir_load_const instructions with a series of loads and a vec[234] to reconstruct the original vector (on the assumption that nir_lower_alu_to_scalar() will then be used to split it up).
This gives NIR a chance to CSE more operations on a scalar shader, when the same value was used in different vector contant loads.
Function Documentation
lower_load_const_instr_scalar()
static bool lower_load_const_instr_scalar (nir_load_const_instr * lower) static
References nir_ssa_def::bit_size, nir_instr::block, nir_block::cf_node, nir_builder::cursor, nir_load_const_instr::def, nir_const_value::f64, nir_load_const_instr::instr, nir_before_instr(), nir_builder_init(), nir_builder_instr_insert(), nir_cf_node_get_function(), nir_instr_remove(), nir_load_const_instr_create(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_vec(), nir_ssa_def::num_components, nir_builder::shader, nir_const_value::u32, and nir_load_const_instr::value.
Referenced by nir_lower_load_const_to_scalar_impl().
nir_lower_load_const_to_scalar()
bool nir_lower_load_const_to_scalar (nir_shader * shader)
References nir_foreach_function, and nir_lower_load_const_to_scalar_impl().
nir_lower_load_const_to_scalar_impl()
static bool nir_lower_load_const_to_scalar_impl (nir_function_impl * impl) static
References instr, lower_load_const_instr_scalar(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_type_load_const, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_load_const_to_scalar().