Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_64bit_packing.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static nir_ssa_def * lower_pack_64 (nir_builder *b, nir_ssa_def *src)
static nir_ssa_def * lower_unpack_64 (nir_builder *b, nir_ssa_def *src)
static bool lower_64bit_pack_impl (nir_function_impl *impl)
bool nir_lower_64bit_pack (nir_shader *shader)
Function Documentation
lower_64bit_pack_impl()
static bool lower_64bit_pack_impl (nir_function_impl * impl) static
References nir_builder::cursor, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, instr, lower_pack_64(), lower_unpack_64(), nir_before_instr(), nir_builder_init(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_alu, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_for_alu_src(), nir_alu_instr::op, and nir_dest::ssa.
Referenced by nir_lower_64bit_pack().
lower_pack_64()
static nir_ssa_def* lower_pack_64 (nir_builder * b, nir_ssa_def * src) static
References nir_channel().
Referenced by lower_64bit_pack_impl().
lower_unpack_64()
static nir_ssa_def* lower_unpack_64 (nir_builder * b, nir_ssa_def * src) static
Referenced by lower_64bit_pack_impl().
nir_lower_64bit_pack()
bool nir_lower_64bit_pack (nir_shader * shader)
References lower_64bit_pack_impl(), and nir_foreach_function.