Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_io_types.c File Reference
#include "nir.h"
#include "nir_builder.h"
Data Structures
struct lower_io_types_state
Functions
static nir_variable * get_new_var (struct lower_io_types_state *state, nir_variable *var, const struct glsl_type *deref_type, unsigned off)
static unsigned get_deref_offset (struct lower_io_types_state *state, nir_deref *tail, bool vs_in)
static bool lower_io_types_block (struct lower_io_types_state *state, nir_block *block)
static void lower_io_types_impl (nir_function_impl *impl, struct lower_io_types_state *state)
void nir_lower_io_types (nir_shader *shader)
Function Documentation
get_deref_offset()
static unsigned get_deref_offset (struct lower_io_types_state * state, nir_deref * tail, bool vs_in) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_struct::index, nir_deref_array_type_direct, nir_deref_type_array, nir_deref_type_struct, and nir_deref::type.
Referenced by lower_io_types_block().
get_new_var()
static nir_variable* get_new_var (struct lower_io_types_state * state, nir_variable * var, const struct glsl_type * deref_type, unsigned off) static
References nir_variable::data, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_variable::name, lower_io_types_state::new_ins, lower_io_types_state::new_outs, nir_foreach_variable, nir_var_shader_in, nir_var_shader_out, nir_variable_create(), nir_variable::node, and lower_io_types_state::shader.
Referenced by lower_io_types_block().
lower_io_types_block()
static bool lower_io_types_block (struct lower_io_types_state * state, nir_block * block) static
References nir_variable::data, nir_deref_var::deref, deref_type, get_deref_offset(), get_new_var(), instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::mode, nir_deref_var_create(), nir_foreach_instr, nir_instr_type_intrinsic, nir_var_shader_in, nir_var_shader_out, lower_io_types_state::shader, nir_shader::stage, nir_variable::type, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_io_types_impl().
lower_io_types_impl()
static void lower_io_types_impl (nir_function_impl * impl, struct lower_io_types_state * state) static
References lower_io_types_block(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_io_types().
nir_lower_io_types()
void nir_lower_io_types (nir_shader * shader)
References nir_shader::inputs, lower_io_types_impl(), lower_io_types_state::new_ins, lower_io_types_state::new_outs, nir_foreach_function, nir_shader::outputs, and lower_io_types_state::shader.