Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_control_flow.h File Reference
#include "nir.h"
Data Structures
struct nir_cf_list
Control flow motion.
Functions
void nir_cf_node_insert (nir_cursor cursor, nir_cf_node *node)
NIR Control Flow Modification.
static void nir_cf_node_insert_after (nir_cf_node *node, nir_cf_node *after)
puts a control flow node immediately after another control flow node
static void nir_cf_node_insert_before (nir_cf_node *node, nir_cf_node *before)
puts a control flow node immediately before another control flow node
static void nir_cf_node_insert_begin (struct exec_list *list, nir_cf_node *node)
puts a control flow node at the beginning of a list from an if, loop, or function
static void nir_cf_node_insert_end (struct exec_list *list, nir_cf_node *node)
puts a control flow node at the end of a list from an if, loop, or function
void nir_cf_extract (nir_cf_list *extracted, nir_cursor begin, nir_cursor end)
void nir_cf_reinsert (nir_cf_list *cf_list, nir_cursor cursor)
void nir_cf_delete (nir_cf_list *cf_list)
void nir_cf_list_clone (nir_cf_list *dst, nir_cf_list *src, nir_cf_node *parent, struct hash_table *remap_table)
static void nir_cf_list_extract (nir_cf_list *extracted, struct exec_list *cf_list)
static void nir_cf_node_remove (nir_cf_node *node)
removes a control flow node, doing any cleanup necessary
Function Documentation
nir_cf_delete()
void nir_cf_delete (nir_cf_list * cf_list)
References cleanup_cf_node(), foreach_list_typed, nir_cf_list::impl, and nir_cf_list::list.
Referenced by complex_unroll(), lower_returns_in_block(), lower_returns_in_if(), nir_cf_node_remove(), remove_after_cf_node(), and simple_unroll().
nir_cf_extract()
void nir_cf_extract (nir_cf_list * extracted, nir_cursor begin, nir_cursor end)
References nir_block::cf_node, cf_node, nir_cf_list::impl, nir_cf_list::list, nir_cf_node_get_function(), nir_cf_node_next(), nir_cursors_equal(), nir_metadata_none, nir_metadata_preserve(), nir_cf_node::node, nir_cf_node::parent, split_block_cursor(), and stitch_blocks().
Referenced by complex_unroll(), lower_returns_in_block(), lower_returns_in_if(), nir_cf_list_extract(), nir_cf_node_remove(), opt_peel_loop_initial_if(), predicate_following(), remove_after_cf_node(), and simple_unroll().
nir_cf_list_clone()
void nir_cf_list_clone (nir_cf_list * dst, nir_cf_list * src, nir_cf_node * parent, struct hash_table * remap_table)
References nir_block::cf_node, clone_cf_list(), fixup_phi_srcs(), nir_function_impl::function, nir_cf_list::impl, init_clone_state(), nir_cf_list::list, nir_block_create(), nir_cf_node::node, clone_state::ns, nir_cf_node::parent, and nir_function::shader.
Referenced by complex_unroll(), opt_peel_loop_initial_if(), and simple_unroll().
nir_cf_list_extract()
static void nir_cf_list_extract (nir_cf_list * extracted, struct exec_list * cf_list) inline static
References nir_after_cf_list(), nir_before_cf_list(), and nir_cf_extract().
Referenced by inline_functions_block(), and opt_constant_if().
nir_cf_node_insert()
void nir_cf_node_insert (nir_cursor cursor, nir_cf_node * node)
NIR Control Flow Modification.
This file contains various APIs that make modifying control flow in NIR, while maintaining the invariants checked by the validator, much easier. There are two parts to this:
Inserting control flow (ifs and loops) in various places, for creating IR either from scratch or as part of some lowering pass.
Taking existing pieces of the IR and either moving them around or deleting them.Control flow insertion. puts a control flow node where the cursor is
References block_ends_in_jump(), nir_block::cf_node, insert_non_block(), nir_handle_add_jump(), nir_cf_node::node, nir_cf_node::parent, split_block_cursor(), stitch_blocks(), nir_cf_node::type, and update_if_uses().
Referenced by nir_builder_cf_insert(), nir_cf_node_insert_after(), nir_cf_node_insert_before(), nir_cf_node_insert_begin(), nir_cf_node_insert_end(), and predicate_following().
nir_cf_node_insert_after()
static void nir_cf_node_insert_after (nir_cf_node * node, nir_cf_node * after) inline static
puts a control flow node immediately after another control flow node
References nir_after_cf_node(), and nir_cf_node_insert().
nir_cf_node_insert_before()
static void nir_cf_node_insert_before (nir_cf_node * node, nir_cf_node * before) inline static
puts a control flow node immediately before another control flow node
References nir_before_cf_node(), and nir_cf_node_insert().
nir_cf_node_insert_begin()
static void nir_cf_node_insert_begin (struct exec_list * list, nir_cf_node * node) inline static
puts a control flow node at the beginning of a list from an if, loop, or function
References nir_before_cf_list(), and nir_cf_node_insert().
nir_cf_node_insert_end()
static void nir_cf_node_insert_end (struct exec_list * list, nir_cf_node * node) inline static
puts a control flow node at the end of a list from an if, loop, or function
References nir_after_cf_list(), and nir_cf_node_insert().
Referenced by clone_if(), and clone_loop().
nir_cf_node_remove()
static void nir_cf_node_remove (nir_cf_node * node) inline static
removes a control flow node, doing any cleanup necessary
References nir_after_cf_node(), nir_before_cf_node(), nir_cf_delete(), and nir_cf_extract().
Referenced by complex_unroll(), dead_cf_block(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), opt_constant_if(), opt_peel_loop_initial_if(), and simple_unroll().
nir_cf_reinsert()
void nir_cf_reinsert (nir_cf_list * cf_list, nir_cursor cursor)
References nir_block::cf_node, foreach_list_typed_safe, nir_cf_list::list, nir_cf_node_next(), nir_cf_node_prev(), nir_cf_node::node, nir_cf_node::parent, split_block_cursor(), and stitch_blocks().
Referenced by complex_unroll(), inline_functions_block(), lower_returns_in_if(), move_cf_list_into_loop_term(), opt_constant_if(), opt_peel_loop_initial_if(), predicate_following(), and simple_unroll().