Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_repair_ssa.c File Reference
#include "nir.h"
#include "nir_phi_builder.h"
Data Structures
struct repair_ssa_state
Functions
static struct nir_phi_builder * prep_build_phi (struct repair_ssa_state *state)
static nir_block * get_src_block (nir_src *src)
static bool repair_ssa_def (nir_ssa_def *def, void *void_state)
bool nir_repair_ssa_impl (nir_function_impl *impl)
bool nir_repair_ssa (nir_shader *shader)
This pass can be used to repair SSA form in a shader.
Function Documentation
get_src_block()
static nir_block* get_src_block (nir_src * src) static
References nir_instr::block, exec_node_data, nir_instr_type_phi, nir_src::parent_instr, and nir_instr::type.
Referenced by repair_ssa_def().
nir_repair_ssa()
bool nir_repair_ssa (nir_shader * shader)
This pass can be used to repair SSA form in a shader.
Sometimes a transformation (such as return lowering) will have to make changes to a shader which, while still correct, break some of NIR's SSA invariants. This pass will insert ssa_undefs and phi nodes as needed to get the shader back into SSA that the validator will like.
References nir_foreach_function, nir_repair_ssa_impl(), and repair_ssa_state::progress.
nir_repair_ssa_impl()
bool nir_repair_ssa_impl (nir_function_impl * impl)
References repair_ssa_state::def_set, repair_ssa_state::impl, instr, nir_foreach_block, nir_foreach_instr_safe, nir_foreach_ssa_def(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), nir_phi_builder_finish(), repair_ssa_state::phi_builder, repair_ssa_state::progress, and repair_ssa_def().
Referenced by nir_lower_returns_impl(), and nir_repair_ssa().
prep_build_phi()
static struct nir_phi_builder* prep_build_phi (struct repair_ssa_state * state) static
References repair_ssa_state::def_set, repair_ssa_state::impl, nir_phi_builder_create(), nir_function_impl::num_blocks, repair_ssa_state::phi_builder, and repair_ssa_state::progress.
Referenced by repair_ssa_def().
repair_ssa_def()
static bool repair_ssa_def (nir_ssa_def * def, void * void_state) static
References nir_ssa_def::bit_size, nir_instr::block, repair_ssa_state::def_set, get_src_block(), nir_block::index, nir_block_dominates(), nir_foreach_use, nir_foreach_use_safe, nir_instr_rewrite_src(), nir_phi_builder_add_value(), nir_phi_builder_value_get_block_def(), nir_phi_builder_value_set_block_def(), nir_src_for_ssa(), nir_ssa_def::num_components, nir_ssa_def::parent_instr, and prep_build_phi().
Referenced by nir_repair_ssa_impl().