Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_search_helpers.h File Reference
#include "nir.h"
Functions
static bool __is_power_of_two (unsigned int x)
static bool is_pos_power_of_two (nir_alu_instr *instr, unsigned src, unsigned num_components, const uint8_t *swizzle)
static bool is_neg_power_of_two (nir_alu_instr *instr, unsigned src, unsigned num_components, const uint8_t *swizzle)
static bool is_zero_to_one (nir_alu_instr *instr, unsigned src, unsigned num_components, const uint8_t *swizzle)
static bool is_used_more_than_once (nir_alu_instr *instr)
static bool is_used_once (nir_alu_instr *instr)
static bool is_not_used_by_if (nir_alu_instr *instr)
Function Documentation
__is_power_of_two()
static bool __is_power_of_two (unsigned int x) inline static
Referenced by is_neg_power_of_two(), and is_pos_power_of_two().
is_neg_power_of_two()
static bool is_neg_power_of_two (nir_alu_instr * instr, unsigned src, unsigned num_components, const uint8_t * swizzle) inline static
References __is_power_of_two(), abs(), nir_const_value::i32, nir_op_info::input_types, nir_op_infos, nir_src_as_const_value(), nir_type_int, nir_alu_instr::op, nir_alu_src::src, and nir_alu_instr::src.
is_not_used_by_if()
static bool is_not_used_by_if (nir_alu_instr * instr) inline static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_ssa_def::if_uses, and nir_dest::ssa.
is_pos_power_of_two()
static bool is_pos_power_of_two (nir_alu_instr * instr, unsigned src, unsigned num_components, const uint8_t * swizzle) inline static
References __is_power_of_two(), nir_const_value::i32, nir_op_info::input_types, nir_op_infos, nir_src_as_const_value(), nir_type_int, nir_type_uint, nir_alu_instr::op, nir_alu_src::src, nir_alu_instr::src, and nir_const_value::u32.
is_used_more_than_once()
static bool is_used_more_than_once (nir_alu_instr * instr) inline static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_ssa_def::if_uses, nir_dest::ssa, and nir_ssa_def::uses.
is_used_once()
static bool is_used_once (nir_alu_instr * instr) inline static
References nir_alu_dest::dest, nir_alu_instr::dest, nir_ssa_def::if_uses, nir_dest::ssa, and nir_ssa_def::uses.
is_zero_to_one()
static bool is_zero_to_one (nir_alu_instr * instr, unsigned src, unsigned num_components, const uint8_t * swizzle) inline static
References nir_const_value::f32, nir_op_info::input_types, nir_op_infos, nir_src_as_const_value(), nir_type_float, nir_alu_instr::op, nir_alu_src::src, and nir_alu_instr::src.