Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_to_lcssa.c File Reference
#include "nir.h"
Data Structures
struct lcssa_state
Functions
static bool is_if_use_inside_loop (nir_src *use, nir_loop *loop)
static bool is_use_inside_loop (nir_src *use, nir_loop *loop)
static bool convert_loop_exit_for_ssa (nir_ssa_def *def, void *void_state)
static void convert_to_lcssa (nir_cf_node *cf_node, lcssa_state *state)
void nir_convert_loop_to_lcssa (nir_loop *loop)
Function Documentation
convert_loop_exit_for_ssa()
static bool convert_loop_exit_for_ssa (nir_ssa_def * def, void * void_state) static
References nir_ssa_def::bit_size, nir_loop::cf_node, nir_phi_instr::dest, nir_phi_instr::instr, is_if_use_inside_loop(), is_use_inside_loop(), lcssa_state::loop, nir_cf_node_next(), nir_foreach_if_use, nir_foreach_if_use_safe, nir_foreach_use, nir_foreach_use_safe, nir_if_rewrite_condition(), nir_instr_insert_before_block(), nir_instr_rewrite_src(), nir_instr_type_phi, nir_phi_instr_create(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_phi_src::node, nir_ssa_def::num_components, nir_phi_src::pred, nir_block::predecessors, lcssa_state::shader, nir_phi_src::src, nir_phi_instr::srcs, and nir_dest::ssa.
Referenced by convert_to_lcssa().
convert_to_lcssa()
static void convert_to_lcssa (nir_cf_node * cf_node, lcssa_state * state) static
References nir_loop::body, convert_loop_exit_for_ssa(), nir_if::else_list, foreach_list_typed, instr, lcssa_state::loop, nir_foreach_instr, nir_foreach_ssa_def(), nir_if::then_list, and nir_cf_node::type.
Referenced by nir_convert_loop_to_lcssa().
is_if_use_inside_loop()
static bool is_if_use_inside_loop (nir_src * use, nir_loop * loop) static
References nir_if::cf_node, nir_loop::cf_node, nir_block::index, nir_cf_node_next(), nir_cf_node_prev(), and nir_src::parent_if.
Referenced by convert_loop_exit_for_ssa().
is_use_inside_loop()
static bool is_use_inside_loop (nir_src * use, nir_loop * loop) static
References nir_instr::block, nir_loop::cf_node, nir_block::index, nir_cf_node_next(), nir_cf_node_prev(), and nir_src::parent_instr.
Referenced by convert_loop_exit_for_ssa().
nir_convert_loop_to_lcssa()
void nir_convert_loop_to_lcssa (nir_loop * loop)
References nir_loop::body, nir_loop::cf_node, convert_to_lcssa(), foreach_list_typed, nir_function_impl::function, lcssa_state::loop, nir_cf_node_get_function(), nir_metadata_block_index, nir_metadata_require(), lcssa_state::shader, and nir_function::shader.
Referenced by loop_prepare_for_unroll(), and opt_peel_loop_initial_if().