Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_to_source_mods.c File Reference
#include "nir.h"
Functions
static bool nir_lower_to_source_mods_block (nir_block *block)
static bool nir_lower_to_source_mods_impl (nir_function_impl *impl)
bool nir_lower_to_source_mods (nir_shader *shader)
Function Documentation
nir_lower_to_source_mods()
bool nir_lower_to_source_mods (nir_shader * shader)
References nir_foreach_function, and nir_lower_to_source_mods_impl().
nir_lower_to_source_mods_block()
static bool nir_lower_to_source_mods_block (nir_block * block) static
References nir_alu_src::abs, nir_alu_dest::dest, nir_alu_instr::dest, nir_ssa_def::if_uses, nir_op_info::input_types, nir_alu_instr::instr, instr, nir_src::is_ssa, nir_dest::is_ssa, nir_alu_src::negate, nir_alu_instr_channel_used(), nir_alu_type_get_base_type(), nir_foreach_instr, nir_foreach_use, nir_instr_remove(), nir_instr_rewrite_src(), nir_instr_type_alu, nir_op_infos, nir_type_float, nir_type_int, nir_op_info::num_inputs, nir_alu_instr::op, nir_op_info::output_type, nir_ssa_def::parent_instr, nir_alu_dest::saturate, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, nir_alu_src::swizzle, nir_instr::type, and nir_ssa_def::uses.
Referenced by nir_lower_to_source_mods_impl().
nir_lower_to_source_mods_impl()
static bool nir_lower_to_source_mods_impl (nir_function_impl * impl) static
References nir_foreach_block, nir_lower_to_source_mods_block(), nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_to_source_mods().