Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_idiv.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static bool convert_instr (nir_builder *bld, nir_alu_instr *alu)
static bool convert_impl (nir_function_impl *impl)
bool nir_lower_idiv (nir_shader *shader)
Function Documentation
convert_impl()
static bool convert_impl (nir_function_impl * impl) static
References convert_instr(), instr, nir_builder_init(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_type_alu, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and state::progress.
Referenced by nir_lower_idiv().
convert_instr()
static bool convert_instr (nir_builder * bld, nir_alu_instr * alu) static
References bf, nir_builder::cursor, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, nir_dest::is_ssa, nir_before_instr(), nir_imm_int(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_for_alu_src(), nir_alu_instr::op, and nir_dest::ssa.
Referenced by convert_impl().
nir_lower_idiv()
bool nir_lower_idiv (nir_shader * shader)
References convert_impl(), nir_foreach_function, and state::progress.