Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_remove_phis.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static nir_alu_instr * get_parent_mov (nir_ssa_def *ssa)
static bool matching_mov (nir_alu_instr *mov1, nir_ssa_def *ssa)
static bool remove_phis_block (nir_block *block, nir_builder *b)
static bool remove_phis_impl (nir_function_impl *impl)
bool nir_opt_remove_phis (nir_shader *shader)
Function Documentation
get_parent_mov()
static nir_alu_instr* get_parent_mov (nir_ssa_def * ssa) static
References nir_instr_type_alu, nir_alu_instr::op, nir_ssa_def::parent_instr, and nir_instr::type.
Referenced by matching_mov(), and remove_phis_block().
matching_mov()
static bool matching_mov (nir_alu_instr * mov1, nir_ssa_def * ssa) static
References get_parent_mov(), and nir_alu_srcs_equal().
Referenced by remove_phis_block().
nir_opt_remove_phis()
bool nir_opt_remove_phis (nir_shader * shader)
References nir_foreach_function, and remove_phis_impl().
remove_phis_block()
static bool remove_phis_block (nir_block * block, nir_builder * b) static
References nir_builder::cursor, nir_phi_instr::dest, get_parent_mov(), instr, nir_dest::is_ssa, matching_mov(), nir_after_phis(), nir_fmov_alu(), nir_foreach_instr_safe, nir_foreach_phi_src, nir_imov_alu(), nir_instr_remove(), nir_instr_type_phi, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_def::num_components, nir_alu_instr::op, nir_alu_instr::src, and nir_dest::ssa.
Referenced by remove_phis_impl().
remove_phis_impl()
static bool remove_phis_impl (nir_function_impl * impl) static
References nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and remove_phis_block().
Referenced by nir_opt_remove_phis().