Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_patch_vertices.c File Reference
#include "nir_builder.h"
Functions
void nir_lower_tes_patch_vertices (nir_shader *tes_nir, unsigned patch_vertices)
Function Documentation
nir_lower_tes_patch_vertices()
void nir_lower_tes_patch_vertices (nir_shader * tes_nir, unsigned patch_vertices)
References nir_builder::cursor, nir_intrinsic_instr::dest, nir_builder::impl, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_before_instr(), nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_imm_int(), nir_instr_remove(), nir_instr_type_intrinsic, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_dest::ssa.