Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_undef.c File Reference
Handles optimization of operations involving ssa_undef.
#include "nir.h"
#include "nir_builder.h"
Functions
static bool opt_undef_csel (nir_alu_instr *instr)
Turn conditional selects between an undef and some other value into a move of that other value (on the assumption that the condition's going to be choosing the defined value).
static bool opt_undef_vecN (nir_builder *b, nir_alu_instr *alu)
Replace vecN(undef, undef, ...) with a single undef.
static bool opt_undef_store (nir_intrinsic_instr *intrin)
Remove any store intrinsics whose value is undefined (the existing value is a fine representation of "undefined").
bool nir_opt_undef (nir_shader *shader)
Detailed Description
Handles optimization of operations involving ssa_undef.
Function Documentation
nir_opt_undef()
bool nir_opt_undef (nir_shader * shader)
References nir_builder::impl, instr, nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_foreach_instr_safe, nir_instr_type_alu, nir_instr_type_intrinsic, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), opt_undef_csel(), opt_undef_store(), and opt_undef_vecN().
opt_undef_csel()
static bool opt_undef_csel (nir_alu_instr * instr) static
Turn conditional selects between an undef and some other value into a move of that other value (on the assumption that the condition's going to be choosing the defined value).
This reduces work after if flattening when each side of the if is defining a variable.
References nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, nir_src::is_ssa, nir_dest::is_ssa, nir_alu_src_copy(), nir_instr_rewrite_src(), nir_instr_type_ssa_undef, nir_alu_instr::op, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and nir_instr::type.
Referenced by nir_opt_undef().
opt_undef_store()
static bool opt_undef_store (nir_intrinsic_instr * intrin) static
Remove any store intrinsics whose value is undefined (the existing value is a fine representation of "undefined").
References nir_intrinsic_instr::instr, nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_instr_remove(), nir_instr_type_ssa_undef, nir_ssa_def::parent_instr, nir_intrinsic_instr::src, nir_src::ssa, and nir_instr::type.
Referenced by nir_opt_undef().
opt_undef_vecN()
static bool opt_undef_vecN (nir_builder * b, nir_alu_instr * alu) static
Replace vecN(undef, undef, ...) with a single undef.
References nir_builder::cursor, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, nir_src::is_ssa, nir_dest::is_ssa, nir_before_instr(), nir_dest_bit_size(), nir_instr_type_ssa_undef, nir_op_infos, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_undef(), nir_ssa_def::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_dest::ssa, and nir_instr::type.
Referenced by nir_opt_undef().