Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_gcm.c File Reference
#include "nir.h"
#include "nir_instr_set.h"
Data Structures
struct gcm_block_info
struct gcm_state
Enumerations
enum { GCM_INSTR_PINNED = (1 << 0), GCM_INSTR_SCHEDULED_EARLY = (1 << 1), GCM_INSTR_SCHEDULED_LATE = (1 << 2), GCM_INSTR_PLACED = (1 << 3) }
Functions
static void gcm_build_block_info (struct exec_list *cf_list, struct gcm_state *state, unsigned loop_depth)
static bool gcm_pin_instructions_block (nir_block *block, struct gcm_state *state)
static void gcm_schedule_early_instr (nir_instr *instr, struct gcm_state *state)
Schedules an instruction early.
static bool gcm_schedule_early_src (nir_src *src, void *void_state)
Update an instructions schedule for the given source.
static void gcm_schedule_late_instr (nir_instr *instr, struct gcm_state *state)
Schedules an instruction late.
static bool gcm_schedule_late_def (nir_ssa_def *def, void *void_state)
Schedules the instruction associated with the given SSA def late.
static void gcm_place_instr (nir_instr *instr, struct gcm_state *state)
Places an instrution back into the program.
static bool gcm_place_instr_def (nir_ssa_def *def, void *state)
static bool opt_gcm_impl (nir_function_impl *impl, bool value_number)
bool nir_opt_gcm (nir_shader *shader, bool value_number)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GCM_INSTR_PINNED
GCM_INSTR_SCHEDULED_EARLY
GCM_INSTR_SCHEDULED_LATE
GCM_INSTR_PLACED
Function Documentation
gcm_build_block_info()
static void gcm_build_block_info (struct exec_list * cf_list, struct gcm_state * state, unsigned loop_depth) static
References gcm_state::blocks, nir_loop::body, nir_if::else_list, foreach_list_typed, nir_block::index, gcm_block_info::loop_depth, and nir_if::then_list.
Referenced by opt_gcm_impl().
gcm_pin_instructions_block()
static bool gcm_pin_instructions_block (nir_block * block, struct gcm_state * state) static
References nir_intrinsic_info::flags, GCM_INSTR_PINNED, gcm_schedule_early_instr(), instr, gcm_state::instrs, nir_foreach_instr_safe, nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, NIR_INTRINSIC_CAN_ELIMINATE, NIR_INTRINSIC_CAN_REORDER, nir_intrinsic_infos, nir_texop_lod, nir_texop_tex, and nir_texop_txb.
Referenced by opt_gcm_impl().
gcm_place_instr()
static void gcm_place_instr (nir_instr * instr, struct gcm_state * state) static
Places an instrution back into the program.
The earlier passes of GCM simply choose blocks for each instruction and otherwise leave them alone. This pass actually places the instructions into their chosen blocks.
To do so, we use a standard post-order depth-first search linearization algorithm. We walk over the uses of the given instruction and ensure that they are placed and then place this instruction. Because we are working on multiple blocks at a time, we keep track of the last inserted instruction per-block in the state structure's block_info array. When we insert an instruction in a block we insert it before the last instruction inserted in that block rather than the last instruction inserted globally.
References nir_instr::block, gcm_state::blocks, GCM_INSTR_PINNED, GCM_INSTR_PLACED, gcm_place_instr_def(), nir_block::index, instr, nir_block::instr_list, gcm_block_info::last_instr, nir_block_last_instr(), nir_foreach_ssa_def(), nir_instr_next(), nir_instr_type_jump, nir_instr_type_phi, nir_instr::node, nir_instr::pass_flags, and nir_instr::type.
Referenced by gcm_place_instr_def(), gcm_schedule_late_instr(), and opt_gcm_impl().
gcm_place_instr_def()
static bool gcm_place_instr_def (nir_ssa_def * def, void * state) static
References gcm_place_instr(), and nir_foreach_use.
Referenced by gcm_place_instr().
gcm_schedule_early_instr()
static void gcm_schedule_early_instr (nir_instr * instr, struct gcm_state * state) static
Schedules an instruction early.
This function performs a recursive depth-first search starting at the given instruction and proceeding through the sources to schedule instructions as early as they can possibly go in the dominance tree. The instructions are "scheduled" by updating their instr->block field.
References nir_instr::block, GCM_INSTR_PINNED, GCM_INSTR_SCHEDULED_EARLY, gcm_schedule_early_src(), gcm_schedule_late_instr(), gcm_state::impl, gcm_state::instr, instr, nir_foreach_src(), nir_start_block(), and nir_instr::pass_flags.
Referenced by gcm_pin_instructions_block(), gcm_schedule_early_src(), and opt_gcm_impl().
gcm_schedule_early_src()
static bool gcm_schedule_early_src (nir_src * src, void * void_state) static
Update an instructions schedule for the given source.
This function is called iteratively as we walk the sources of an instruction. It ensures that the given source instruction has been scheduled and then update this instruction's block if the source instruction is lower down the tree.
References nir_instr::block, gcm_schedule_early_instr(), nir_block::index, gcm_state::instr, instr, nir_src::is_ssa, nir_ssa_def::parent_instr, and nir_src::ssa.
Referenced by gcm_schedule_early_instr().
gcm_schedule_late_def()
static bool gcm_schedule_late_def (nir_ssa_def * def, void * void_state) static
Schedules the instruction associated with the given SSA def late.
This function works by first walking all of the uses of the given SSA definition, ensuring that they are scheduled, and then computing the LCA (least common ancestor) of its uses. It then schedules this instruction as close to the LCA as possible while trying to stay out of loops.
References nir_instr::block, gcm_state::blocks, nir_if::cf_node, gcm_schedule_late_instr(), nir_block::index, gcm_block_info::loop_depth, nir_cf_node_prev(), nir_dominance_lca(), nir_foreach_if_use, nir_foreach_phi_src, nir_foreach_use, nir_instr_type_phi, nir_ssa_def::parent_instr, and nir_instr::type.
Referenced by gcm_schedule_late_instr().
gcm_schedule_late_instr()
static void gcm_schedule_late_instr (nir_instr * instr, struct gcm_state * state) static
Schedules an instruction late.
This function performs a depth-first search starting at the given instruction and proceeding through its uses to schedule instructions as late as they can reasonably go in the dominance tree. The instructions are "scheduled" by updating their instr->block field.
The name of this function is actually a bit of a misnomer as it doesn't schedule them "as late as possible" as the paper implies. Instead, it first finds the lates possible place it can schedule the instruction and then possibly schedules it earlier than that. The actual location is as far down the tree as we can go while trying to stay out of loops.
References GCM_INSTR_PINNED, GCM_INSTR_SCHEDULED_LATE, gcm_place_instr(), gcm_schedule_late_def(), nir_foreach_ssa_def(), and nir_instr::pass_flags.
Referenced by gcm_schedule_early_instr(), gcm_schedule_late_def(), and opt_gcm_impl().
nir_opt_gcm()
bool nir_opt_gcm (nir_shader * shader, bool value_number)
References nir_foreach_function, and opt_gcm_impl().
opt_gcm_impl()
static bool opt_gcm_impl (nir_function_impl * impl, bool value_number) static
References gcm_state::blocks, nir_function_impl::body, exec_node_data, foreach_list_typed, foreach_list_typed_safe, gcm_build_block_info(), gcm_pin_instructions_block(), gcm_place_instr(), gcm_schedule_early_instr(), gcm_schedule_late_instr(), gcm_state::impl, gcm_state::instr, gcm_state::instrs, nir_foreach_block, nir_instr_remove(), nir_instr_set_add_or_rewrite(), nir_instr_set_create(), nir_instr_set_destroy(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), nir_function_impl::num_blocks, exec_node::prev, and exec_list::tail_sentinel.
Referenced by nir_opt_gcm().