Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_gather_info.c File Reference
#include "main/mtypes.h"
#include "nir.h"
Functions
static void set_io_mask (nir_shader *shader, nir_variable *var, int offset, int len)
static void mark_whole_variable (nir_shader *shader, nir_variable *var)
Mark an entire variable as used.
static unsigned get_io_offset (nir_deref_var *deref)
static bool try_mask_partial_io (nir_shader *shader, nir_deref_var *deref)
Try to mark a portion of the given varying as used.
static void gather_intrinsic_info (nir_intrinsic_instr *instr, nir_shader *shader)
static void gather_tex_info (nir_tex_instr *instr, nir_shader *shader)
static void gather_info_block (nir_block *block, nir_shader *shader)
void nir_shader_gather_info (nir_shader *shader, nir_function_impl *entrypoint)
Function Documentation
gather_info_block()
static void gather_info_block (nir_block * block, nir_shader * shader) static
References gather_intrinsic_info(), gather_tex_info(), instr, nir_foreach_instr, nir_instr_type_call, nir_instr_type_intrinsic, and nir_instr_type_tex.
Referenced by nir_shader_gather_info().
gather_intrinsic_info()
static void gather_intrinsic_info (nir_intrinsic_instr * instr, nir_shader * shader) static
References BITFIELD64_BIT, nir_variable::data, nir_shader::info, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::location, mark_whole_variable(), nir_variable::nir_variable_data::mode, nir_system_value_from_intrinsic(), nir_var_shader_in, nir_var_shader_out, nir_shader::stage, try_mask_partial_io(), nir_variable::type, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by gather_info_block().
gather_tex_info()
static void gather_tex_info (nir_tex_instr * instr, nir_shader * shader) static
References nir_shader::info, nir_texop_tg4, and nir_tex_instr::op.
Referenced by gather_info_block().
get_io_offset()
static unsigned get_io_offset (nir_deref_var * deref) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_array_type_indirect, nir_deref_type_array, and nir_deref::type.
Referenced by try_mask_partial_io().
mark_whole_variable()
static void mark_whole_variable (nir_shader * shader, nir_variable * var) static
Mark an entire variable as used.
Caller must ensure that the variable represents a shader input or output.
References nir_variable::nir_variable_data::compact, nir_variable::data, nir_is_per_vertex_io(), set_io_mask(), nir_shader::stage, nir_variable::type, and type.
Referenced by gather_intrinsic_info().
nir_shader_gather_info()
void nir_shader_gather_info (nir_shader * shader, nir_function_impl * entrypoint)
References gather_info_block(), nir_shader::info, nir_foreach_block, nir_foreach_variable, nir_shader::stage, type, and nir_shader::uniforms.
set_io_mask()
static void set_io_mask (nir_shader * shader, nir_variable * var, int offset, int len) static
References BITFIELD64_BIT, nir_variable::data, nir_variable::nir_variable_data::fb_fetch_output, nir_shader::info, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_var_shader_in, nir_var_shader_out, nir_variable::nir_variable_data::patch, nir_variable::nir_variable_data::read_only, nir_variable::nir_variable_data::sample, and nir_shader::stage.
Referenced by mark_whole_variable(), and try_mask_partial_io().
try_mask_partial_io()
static bool try_mask_partial_io (nir_shader * shader, nir_deref_var * deref) static
Try to mark a portion of the given varying as used.
Caller must ensure that the variable represents a shader input or output.
If the index can't be interpreted as a constant, or some other problem occurs, then nothing will be marked and false will be returned.
References nir_variable::nir_variable_data::compact, nir_variable::data, get_io_offset(), nir_is_per_vertex_io(), set_io_mask(), nir_shader::stage, nir_variable::type, type, and nir_deref_var::var.
Referenced by gather_intrinsic_info().