Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_cse.c File Reference
#include "nir_instr_set.h"
Functions
static bool cse_block (nir_block *block, struct set *instr_set)
static bool nir_opt_cse_impl (nir_function_impl *impl)
bool nir_opt_cse (nir_shader *shader)
Function Documentation
cse_block()
static bool cse_block (nir_block * block, struct set * instr_set) static
References nir_block::dom_children, instr, nir_foreach_instr, nir_foreach_instr_safe, nir_instr_remove(), nir_instr_set_add_or_rewrite(), nir_instr_set_remove(), nir_block::num_dom_children, and copy_prop_var_state::progress.
Referenced by nir_opt_cse_impl().
nir_opt_cse()
bool nir_opt_cse (nir_shader * shader)
References nir_foreach_function, and nir_opt_cse_impl().
nir_opt_cse_impl()
static bool nir_opt_cse_impl (nir_function_impl * impl) static
References cse_block(), nir_instr_set_create(), nir_instr_set_destroy(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), nir_metadata_require(), and nir_start_block().
Referenced by nir_opt_cse().