Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_wpos_center.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "program/prog_instruction.h"
Functions
static void update_fragcoord (nir_builder *b, nir_intrinsic_instr *intr, const bool for_sample_shading)
This pass adds <0.5, 0.5> to all uses of gl_FragCoord.
static bool lower_wpos_center_block (nir_builder *b, nir_block *block, const bool for_sample_shading)
bool nir_lower_wpos_center (nir_shader *shader, const bool for_sample_shading)
Function Documentation
lower_wpos_center_block()
static bool lower_wpos_center_block (nir_builder * b, nir_block * block, const bool for_sample_shading) static
References nir_deref::child, nir_variable::data, nir_deref_var::deref, instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_foreach_instr, nir_instr_type_intrinsic, nir_var_shader_in, update_fragcoord(), nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_lower_wpos_center().
nir_lower_wpos_center()
bool nir_lower_wpos_center (nir_shader * shader, const bool for_sample_shading)
References nir_builder::impl, lower_wpos_center_block(), nir_builder_init(), nir_foreach_block, nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and nir_shader::stage.
update_fragcoord()
static void update_fragcoord (nir_builder * b, nir_intrinsic_instr * intr, const bool for_sample_shading) static
This pass adds <0.5, 0.5> to all uses of gl_FragCoord.
Run before nir_lower_io().
For a more full featured pass, consider using nir_lower_wpos_ytransform(), which can handle pixel center integer / half integer, and origin lower left / upper left transformations.
This simple pass is primarily intended for use by Vulkan drivers on hardware which provides an integer pixel center. Vulkan mandates that the pixel center must be half-integer, and also that the coordinate system's origin must be upper left. This means that there's no need for a uniform - we can always just add a constant. In the case that sample shading is enabled, Vulkan expects FragCoord to include sample positions.
References nir_builder::cursor, nir_intrinsic_instr::dest, nir_intrinsic_instr::instr, nir_dest::is_ssa, nir_after_instr(), nir_channel(), nir_imm_float(), nir_imm_vec4(), nir_load_system_value(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses_after(), nir_ssa_def::parent_instr, and nir_dest::ssa.
Referenced by lower_wpos_center_block().