Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_system_values.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static bool convert_block (nir_block *block, nir_builder *b)
static bool convert_impl (nir_function_impl *impl)
bool nir_lower_system_values (nir_shader *shader)
Function Documentation
convert_block()
static bool convert_block (nir_block * block, nir_builder * b) static
References nir_builder::cursor, nir_variable::data, nir_intrinsic_instr::dest, nir_shader::info, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_variable::nir_variable_data::location, nir_shader_compiler_options::lower_cs_local_index_from_id, nir_variable::nir_variable_data::mode, nir_after_instr(), nir_build_imm(), nir_channel(), nir_foreach_instr_safe, nir_imm_int(), nir_instr_remove(), nir_instr_type_intrinsic, nir_intrinsic_from_system_value(), nir_load_system_value(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_var_system_value, nir_shader::options, nir_builder::shader, nir_dest::ssa, nir_const_value::u32, nir_deref_var::var, nir_intrinsic_instr::variables, and nir_shader_compiler_options::vertex_id_zero_based.
Referenced by convert_impl().
convert_impl()
static bool convert_impl (nir_function_impl * impl) static
References lower_returns_state::builder, convert_block(), nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_system_values().
nir_lower_system_values()
bool nir_lower_system_values (nir_shader * shader)
References convert_impl(), nir_foreach_function, and nir_shader::system_values.