Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_int64.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static nir_ssa_def * lower_imul64 (nir_builder *b, nir_ssa_def *x, nir_ssa_def *y)
static nir_ssa_def * lower_isign64 (nir_builder *b, nir_ssa_def *x)
static void lower_udiv64_mod64 (nir_builder *b, nir_ssa_def *n, nir_ssa_def *d, nir_ssa_def **q, nir_ssa_def **r)
static nir_ssa_def * lower_udiv64 (nir_builder *b, nir_ssa_def *n, nir_ssa_def *d)
static nir_ssa_def * lower_idiv64 (nir_builder *b, nir_ssa_def *n, nir_ssa_def *d)
static nir_ssa_def * lower_umod64 (nir_builder *b, nir_ssa_def *n, nir_ssa_def *d)
static nir_ssa_def * lower_imod64 (nir_builder *b, nir_ssa_def *n, nir_ssa_def *d)
static nir_ssa_def * lower_irem64 (nir_builder *b, nir_ssa_def *n, nir_ssa_def *d)
static nir_lower_int64_options opcode_to_options_mask (nir_op opcode)
static nir_ssa_def * lower_int64_alu_instr (nir_builder *b, nir_alu_instr *alu)
static bool lower_int64_impl (nir_function_impl *impl, nir_lower_int64_options options)
bool nir_lower_int64 (nir_shader *shader, nir_lower_int64_options options)
Function Documentation
lower_idiv64()
static nir_ssa_def* lower_idiv64 (nir_builder * b, nir_ssa_def * n, nir_ssa_def * d) static
References lower_udiv64_mod64(), and nir_imm_int().
Referenced by lower_int64_alu_instr().
lower_imod64()
static nir_ssa_def* lower_imod64 (nir_builder * b, nir_ssa_def * n, nir_ssa_def * d) static
References lower_udiv64_mod64(), nir_imm_int(), and nir_imm_int64().
Referenced by lower_int64_alu_instr().
lower_imul64()
static nir_ssa_def* lower_imul64 (nir_builder * b, nir_ssa_def * x, nir_ssa_def * y) static
Referenced by lower_int64_alu_instr().
lower_int64_alu_instr()
static nir_ssa_def* lower_int64_alu_instr (nir_builder * b, nir_alu_instr * alu) static
References lower_idiv64(), lower_imod64(), lower_imul64(), lower_irem64(), lower_isign64(), lower_udiv64(), lower_umod64(), nir_op_infos, nir_ssa_for_alu_src(), nir_op_info::num_inputs, and nir_alu_instr::op.
Referenced by lower_int64_impl().
lower_int64_impl()
static bool lower_int64_impl (nir_function_impl * impl, nir_lower_int64_options options) static
References nir_ssa_def::bit_size, nir_builder::cursor, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::instr, instr, nir_dest::is_ssa, lower_int64_alu_instr(), nir_before_instr(), nir_builder_init(), nir_foreach_block, nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_alu, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_alu_instr::op, opcode_to_options_mask(), state::progress, and nir_dest::ssa.
Referenced by nir_lower_int64().
lower_irem64()
static nir_ssa_def* lower_irem64 (nir_builder * b, nir_ssa_def * n, nir_ssa_def * d) static
References lower_udiv64_mod64(), and nir_imm_int().
Referenced by lower_int64_alu_instr().
lower_isign64()
static nir_ssa_def* lower_isign64 (nir_builder * b, nir_ssa_def * x) static
References nir_imm_int().
Referenced by lower_int64_alu_instr().
lower_udiv64()
static nir_ssa_def* lower_udiv64 (nir_builder * b, nir_ssa_def * n, nir_ssa_def * d) static
References lower_udiv64_mod64().
Referenced by lower_int64_alu_instr().
lower_udiv64_mod64()
static void lower_udiv64_mod64 (nir_builder * b, nir_ssa_def * n, nir_ssa_def * d, nir_ssa_def ** q, nir_ssa_def ** r) static
References nir_bany(), nir_build_imm(), nir_if_phi(), nir_imm_int(), nir_pop_if(), nir_push_if(), NIR_TRUE, nir_ssa_def::num_components, and nir_const_value::u32.
Referenced by lower_idiv64(), lower_imod64(), lower_irem64(), lower_udiv64(), and lower_umod64().
lower_umod64()
static nir_ssa_def* lower_umod64 (nir_builder * b, nir_ssa_def * n, nir_ssa_def * d) static
References lower_udiv64_mod64().
Referenced by lower_int64_alu_instr().
nir_lower_int64()
bool nir_lower_int64 (nir_shader * shader, nir_lower_int64_options options)
References lower_int64_impl(), nir_foreach_function, and state::progress.
opcode_to_options_mask()
static nir_lower_int64_options opcode_to_options_mask (nir_op opcode) static
References nir_lower_divmod64, nir_lower_imul64, and nir_lower_isign64.
Referenced by lower_int64_impl().