Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_peephole_select.c File Reference
#include "nir.h"
#include "nir_control_flow.h"
Functions
static bool block_check_for_allowed_instrs (nir_block *block, unsigned *count, bool alu_ok)
static bool nir_opt_peephole_select_block (nir_block *block, nir_shader *shader, unsigned limit)
static bool nir_opt_peephole_select_impl (nir_function_impl *impl, unsigned limit)
bool nir_opt_peephole_select (nir_shader *shader, unsigned limit)
Function Documentation
block_check_for_allowed_instrs()
static bool block_check_for_allowed_instrs (nir_block * block, unsigned * count, bool alu_ok) static
References nir_variable::data, nir_alu_dest::dest, nir_alu_instr::dest, nir_ssa_def::if_uses, instr, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, nir_variable::nir_variable_data::mode, nir_foreach_instr, nir_foreach_use, nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_load_const, nir_instr_type_phi, nir_var_shader_in, nir_var_uniform, nir_alu_instr::op, nir_alu_dest::saturate, nir_dest::ssa, nir_block::successors, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by nir_opt_peephole_select_block().
nir_opt_peephole_select()
bool nir_opt_peephole_select (nir_shader * shader, unsigned limit)
References nir_foreach_function, and nir_opt_peephole_select_impl().
nir_opt_peephole_select_block()
static bool nir_opt_peephole_select_block (nir_block * block, nir_shader * shader, unsigned limit) static
References nir_ssa_def::bit_size, block_check_for_allowed_instrs(), nir_block::cf_node, nir_if::cf_node, nir_if::condition, nir_alu_dest::dest, nir_alu_instr::dest, nir_phi_instr::dest, nir_alu_instr::instr, nir_phi_instr::instr, instr, nir_block::instr_list, nir_ssa_def::name, nir_alu_instr_create(), nir_cf_node_is_first(), nir_cf_node_prev(), nir_cf_node_remove(), nir_foreach_instr_safe, nir_foreach_phi_src, nir_if_first_else_block(), nir_if_first_then_block(), nir_if_last_else_block(), nir_if_last_then_block(), nir_instr_insert_before(), nir_instr_remove(), nir_instr_type_phi, nir_src_copy(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_ssa_def::num_components, nir_alu_src::src, nir_alu_instr::src, nir_phi_instr::srcs, nir_dest::ssa, nir_alu_src::swizzle, nir_cf_node::type, and nir_alu_dest::write_mask.
Referenced by nir_opt_peephole_select_impl().
nir_opt_peephole_select_impl()
static bool nir_opt_peephole_select_impl (nir_function_impl * impl, unsigned limit) static
References nir_function_impl::function, nir_foreach_block_safe, nir_metadata_none, nir_metadata_preserve(), nir_opt_peephole_select_block(), and nir_function::shader.
Referenced by nir_opt_peephole_select().