Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_loop_unroll.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "nir_control_flow.h"
#include "nir_loop_analyze.h"
Macros
#define LOOP_UNROLL_LIMIT 26
Functions
static void loop_prepare_for_unroll (nir_loop *loop)
static void get_first_blocks_in_terminator (nir_loop_terminator *term, nir_block **first_break_block, nir_block **first_continue_block)
static void simple_unroll (nir_loop *loop)
Unroll a loop where we know exactly how many iterations there are and there is only a single exit point.
static void move_cf_list_into_loop_term (nir_cf_list *lst, nir_loop_terminator *term)
static nir_cursor get_complex_unroll_insert_location (nir_cf_node *node, bool continue_from_then)
static void complex_unroll (nir_loop *loop, nir_loop_terminator *unlimit_term, bool limiting_term_second)
Unroll a loop with two exists when the trip count of one of the exits is unknown.
static bool is_loop_small_enough_to_unroll (nir_shader *shader, nir_loop_info *li)
static bool process_loops (nir_shader *sh, nir_cf_node *cf_node, bool *innermost_loop)
static bool nir_opt_loop_unroll_impl (nir_function_impl *impl, nir_variable_mode indirect_mask)
bool nir_opt_loop_unroll (nir_shader *shader, nir_variable_mode indirect_mask)
Macro Definition Documentation
LOOP_UNROLL_LIMIT
#define LOOP_UNROLL_LIMIT 26
Referenced by is_loop_small_enough_to_unroll().
Function Documentation
complex_unroll()
static void complex_unroll (nir_loop * loop, nir_loop_terminator * unlimit_term, bool limiting_term_second) static
Unroll a loop with two exists when the trip count of one of the exits is unknown.
If continue_from_then is true, the loop is repeated only when the "then" branch of the if is taken; otherwise it is repeated only when the "else" branch of the if is taken.
For example, if the input is:
 loop {
    ...phis/condition...
    if condition {
       ...then instructions...
    } else {
       ...continue instructions...
       break
    }
    ...body...
 }
And the iteration count is 3, and unlimit_term->continue_from_then is true, then the output will be:
 ...condition...
 if condition {
    ...then instructions...
    ...body...
    if condition {
       ...then instructions...
       ...body...
       if condition {
          ...then instructions...
          ...body...
       } else {
          ...continue instructions...
       }
    } else {
       ...continue instructions...
    }
 } else {
    ...continue instructions...
 }
References nir_loop_terminator::break_block, nir_if::cf_node, nir_loop::cf_node, nir_loop_terminator::continue_from_block, nir_loop_terminator::continue_from_then, exec_node_data, get_complex_unroll_insert_location(), get_first_blocks_in_terminator(), nir_loop::info, nir_loop_info::limiting_terminator, nir_cf_list::list, loop_prepare_for_unroll(), move_cf_list_into_loop_term(), nir_loop_terminator::nif, nir_after_block(), nir_after_cf_node(), nir_before_block(), nir_before_cf_node(), nir_block_last_instr(), nir_cf_delete(), nir_cf_extract(), nir_cf_list_clone(), nir_cf_node_prev(), nir_cf_node_remove(), nir_cf_reinsert(), nir_instr_remove(), nir_is_trivial_loop_if(), nir_loop_first_block(), nir_loop_last_block(), nir_cf_node::parent, nir_loop_info::trip_count, and nir_cf_node::type.
Referenced by process_loops().
get_complex_unroll_insert_location()
static nir_cursor get_complex_unroll_insert_location (nir_cf_node * node, bool continue_from_then) static
References nir_after_block(), nir_before_cf_node(), nir_if_last_else_block(), nir_if_last_then_block(), and nir_cf_node::type.
Referenced by complex_unroll().
get_first_blocks_in_terminator()
static void get_first_blocks_in_terminator (nir_loop_terminator * term, nir_block ** first_break_block, nir_block ** first_continue_block) static
References nir_loop_terminator::continue_from_then, nir_loop_terminator::nif, nir_if_first_else_block(), and nir_if_first_then_block().
Referenced by complex_unroll(), and simple_unroll().
is_loop_small_enough_to_unroll()
static bool is_loop_small_enough_to_unroll (nir_shader * shader, nir_loop_info * li) static
References nir_loop_info::force_unroll, LOOP_UNROLL_LIMIT, nir_shader_compiler_options::max_unroll_iterations, nir_loop_info::num_instructions, nir_shader::options, and nir_loop_info::trip_count.
Referenced by process_loops().
loop_prepare_for_unroll()
static void loop_prepare_for_unroll (nir_loop * loop) static
References nir_loop::cf_node, nir_block_last_instr(), nir_cf_node_next(), nir_convert_loop_to_lcssa(), nir_instr_remove(), nir_instr_type_jump, nir_jump_continue, nir_loop_first_block(), nir_loop_last_block(), nir_lower_phis_to_regs_block(), nir_instr::type, and type.
Referenced by complex_unroll(), and simple_unroll().
move_cf_list_into_loop_term()
static void move_cf_list_into_loop_term (nir_cf_list * lst, nir_loop_terminator * term) static
References nir_loop_terminator::break_block, nir_loop_terminator::continue_from_block, nir_after_block(), nir_block_last_instr(), nir_cf_reinsert(), and nir_instr_remove().
Referenced by complex_unroll().
nir_opt_loop_unroll()
bool nir_opt_loop_unroll (nir_shader * shader, nir_variable_mode indirect_mask)
References nir_foreach_function, and nir_opt_loop_unroll_impl().
nir_opt_loop_unroll_impl()
static bool nir_opt_loop_unroll_impl (nir_function_impl * impl, nir_variable_mode indirect_mask) static
References nir_function_impl::body, foreach_list_typed_safe, nir_function_impl::function, nir_lower_regs_to_ssa_impl(), nir_metadata_block_index, nir_metadata_loop_analysis, nir_metadata_require(), process_loops(), and nir_function::shader.
Referenced by nir_opt_loop_unroll().
process_loops()
static bool process_loops (nir_shader * sh, nir_cf_node * cf_node, bool * innermost_loop) static
References nir_loop::body, complex_unroll(), nir_if::else_list, foreach_list_typed_safe, nir_loop::info, is_loop_small_enough_to_unroll(), nir_loop_info::is_trip_count_known, nir_loop_info::limiting_terminator, nir_loop_info::loop_terminator_list, nir_loop_terminator::nif, simple_unroll(), nir_if::then_list, nir_loop_info::trip_count, and nir_cf_node::type.
Referenced by nir_opt_loop_unroll_impl().
simple_unroll()
static void simple_unroll (nir_loop * loop) static
Unroll a loop where we know exactly how many iterations there are and there is only a single exit point.
Note here we can unroll loops with multiple theoretical exits that only have a single terminating exit that we always know is the "real" exit.
loop {
    ...instrs...
}
And the iteration count is 3, the output will be:
...instrs... ...instrs... ...instrs...
References nir_loop_terminator::break_block, nir_if::cf_node, nir_loop::cf_node, nir_loop_terminator::continue_from_block, get_first_blocks_in_terminator(), nir_loop::info, nir_loop_info::limiting_terminator, loop_prepare_for_unroll(), nir_loop_info::loop_terminator_list, nir_loop_terminator::nif, nir_after_block(), nir_after_cf_node(), nir_before_block(), nir_before_cf_node(), nir_block_last_instr(), nir_cf_delete(), nir_cf_extract(), nir_cf_list_clone(), nir_cf_node_remove(), nir_cf_reinsert(), nir_instr_remove(), nir_is_trivial_loop_if(), nir_loop_first_block(), nir_loop_last_block(), nir_cf_node::parent, and nir_loop_info::trip_count.
Referenced by process_loops().