Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_indirect_derefs.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static void emit_load_store (nir_builder *b, nir_intrinsic_instr *orig_instr, nir_deref_var *deref, nir_deref *tail, nir_ssa_def **dest, nir_ssa_def *src)
static void emit_indirect_load_store (nir_builder *b, nir_intrinsic_instr *orig_instr, nir_deref_var *deref, nir_deref *arr_parent, int start, int end, nir_ssa_def **dest, nir_ssa_def *src)
static bool deref_has_indirect (nir_deref_var *deref)
static bool lower_indirect_block (nir_block *block, nir_builder *b, nir_variable_mode modes)
static bool lower_indirects_impl (nir_function_impl *impl, nir_variable_mode modes)
bool nir_lower_indirect_derefs (nir_shader *shader, nir_variable_mode modes)
Lowers indirect variable loads/stores to direct loads/stores.
Function Documentation
deref_has_indirect()
static bool deref_has_indirect (nir_deref_var * deref) static
References nir_deref::child, nir_deref_var::deref, nir_deref_array::deref_array_type, nir_deref_array_type_indirect, and nir_deref_type_array.
Referenced by lower_indirect_block().
emit_indirect_load_store()
static void emit_indirect_load_store (nir_builder * b, nir_intrinsic_instr * orig_instr, nir_deref_var * deref, nir_deref * arr_parent, int start, int end, nir_ssa_def ** dest, nir_ssa_def * src) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref, nir_deref_array::deref_array_type, emit_load_store(), nir_deref_array::indirect, nir_src::is_ssa, nir_deref_array_type_direct, nir_deref_array_type_indirect, nir_if_phi(), nir_imm_int(), nir_pop_if(), nir_push_else(), nir_push_if(), NIR_SRC_INIT, and nir_src::ssa.
Referenced by emit_load_store().
emit_load_store()
static void emit_load_store (nir_builder * b, nir_intrinsic_instr * orig_instr, nir_deref_var * deref, nir_deref * tail, nir_ssa_def ** dest, nir_ssa_def * src) static
References nir_deref_array::base_offset, nir_ssa_def::bit_size, nir_deref::child, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_intrinsic_instr::dest, emit_indirect_load_store(), nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_deref_array_type_indirect, nir_deref_type_array, nir_deref_var_clone(), nir_intrinsic_instr_create(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_intrinsic_instr::src, nir_dest::ssa, nir_deref::type, and nir_intrinsic_instr::variables.
Referenced by emit_indirect_load_store(), and lower_indirect_block().
lower_indirect_block()
static bool lower_indirect_block (nir_block * block, nir_builder * b, nir_variable_mode modes) static
References nir_variable::nir_variable_data::compact, nir_builder::cursor, nir_variable::data, nir_deref_var::deref, deref_has_indirect(), nir_intrinsic_instr::dest, emit_load_store(), nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_variable::nir_variable_data::mode, nir_before_instr(), nir_foreach_instr_safe, nir_instr_remove(), nir_instr_type_intrinsic, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), state::progress, nir_intrinsic_instr::src, nir_src::ssa, nir_dest::ssa, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by lower_indirects_impl().
lower_indirects_impl()
static bool lower_indirects_impl (nir_function_impl * impl, nir_variable_mode modes) static
References state::builder, lower_indirect_block(), nir_builder_init(), nir_foreach_block_safe, nir_metadata_none, nir_metadata_preserve(), and state::progress.
Referenced by nir_lower_indirect_derefs().
nir_lower_indirect_derefs()
bool nir_lower_indirect_derefs (nir_shader * shader, nir_variable_mode modes)
Lowers indirect variable loads/stores to direct loads/stores.
The pass works by replacing any indirect load or store with an if-ladder that does a binary search on the array index.
References lower_indirects_impl(), nir_foreach_function, and state::progress.