Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_tex.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static void project_src (nir_builder *b, nir_tex_instr *tex)
static bool lower_offset (nir_builder *b, nir_tex_instr *tex)
static nir_ssa_def * get_texture_size (nir_builder *b, nir_tex_instr *tex)
static void lower_rect (nir_builder *b, nir_tex_instr *tex)
static nir_ssa_def * sample_plane (nir_builder *b, nir_tex_instr *tex, int plane)
static void convert_yuv_to_rgb (nir_builder *b, nir_tex_instr *tex, nir_ssa_def *y, nir_ssa_def *u, nir_ssa_def *v)
static void lower_y_uv_external (nir_builder *b, nir_tex_instr *tex)
static void lower_y_u_v_external (nir_builder *b, nir_tex_instr *tex)
static void lower_yx_xuxv_external (nir_builder *b, nir_tex_instr *tex)
static void replace_gradient_with_lod (nir_builder *b, nir_ssa_def *lod, nir_tex_instr *tex)
static void lower_gradient_cube_map (nir_builder *b, nir_tex_instr *tex)
static void lower_gradient_shadow (nir_builder *b, nir_tex_instr *tex)
static void saturate_src (nir_builder *b, nir_tex_instr *tex, unsigned sat_mask)
static nir_ssa_def * get_zero_or_one (nir_builder *b, nir_alu_type type, uint8_t swizzle_val)
static void swizzle_result (nir_builder *b, nir_tex_instr *tex, const uint8_t swizzle[4])
static void linearize_srgb_result (nir_builder *b, nir_tex_instr *tex)
static bool nir_lower_tex_block (nir_block *block, nir_builder *b, const nir_lower_tex_options *options)
static bool nir_lower_tex_impl (nir_function_impl *impl, const nir_lower_tex_options *options)
bool nir_lower_tex (nir_shader *shader, const nir_lower_tex_options *options)
Function Documentation
convert_yuv_to_rgb()
static void convert_yuv_to_rgb (nir_builder * b, nir_tex_instr * tex, nir_ssa_def * y, nir_ssa_def * u, nir_ssa_def * v) static
References nir_tex_instr::dest, nir_const_value::f32, nir_build_imm(), nir_channel(), nir_imm_float(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), and nir_dest::ssa.
Referenced by lower_y_u_v_external(), lower_y_uv_external(), and lower_yx_xuxv_external().
get_texture_size()
static nir_ssa_def* get_texture_size (nir_builder * b, nir_tex_instr * tex) static
References nir_builder::cursor, nir_tex_instr::dest, nir_tex_instr::dest_type, nir_tex_instr::instr, nir_tex_instr::is_array, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, nir_before_instr(), nir_builder_instr_insert(), nir_deref_var_clone(), nir_imm_int(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_tex_instr_create(), nir_tex_instr_dest_size(), nir_tex_src_lod, nir_texop_txs, nir_type_int, nir_tex_instr::op, nir_tex_instr::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_builder::shader, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_dest::ssa, nir_tex_instr::texture, and nir_tex_instr::texture_index.
Referenced by lower_gradient_cube_map(), lower_gradient_shadow(), lower_rect(), and saturate_src().
get_zero_or_one()
static nir_ssa_def* get_zero_or_one (nir_builder * b, nir_alu_type type, uint8_t swizzle_val) static
References nir_const_value::f32, nir_build_imm(), nir_type_float, and nir_const_value::u32.
Referenced by swizzle_result().
linearize_srgb_result()
static void linearize_srgb_result (nir_builder * b, nir_tex_instr * tex) static
References nir_builder::cursor, nir_tex_instr::dest, nir_tex_instr::dest_type, nir_tex_instr::instr, nir_dest::is_ssa, nir_after_instr(), nir_alu_type_get_base_type(), nir_channel(), nir_imm_float(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses_after(), nir_swizzle(), nir_tex_instr_dest_size(), nir_type_float, nir_ssa_def::parent_instr, and nir_dest::ssa.
Referenced by nir_lower_tex_block().
lower_gradient_cube_map()
static void lower_gradient_cube_map (nir_builder * b, nir_tex_instr * tex) static
References nir_tex_instr::dest, get_texture_size(), nir_dest::is_ssa, M, nir_channel(), nir_fdot(), nir_imm_float(), nir_swizzle(), nir_tex_instr_src_index(), nir_tex_src_coord, nir_tex_src_ddx, nir_tex_src_ddy, nir_texop_txd, nir_tex_instr::op, replace_gradient_with_lod(), nir_tex_instr::sampler_dim, nir_tex_src::src, nir_tex_instr::src, and nir_src::ssa.
Referenced by nir_lower_tex_block().
lower_gradient_shadow()
static void lower_gradient_shadow (nir_builder * b, nir_tex_instr * tex) static
References nir_tex_instr::dest, get_texture_size(), nir_tex_instr::is_shadow, nir_dest::is_ssa, nir_channels(), nir_fdot(), nir_tex_instr_src_index(), nir_tex_src_ddx, nir_tex_src_ddy, nir_texop_txd, nir_ssa_def::num_components, nir_tex_instr::op, replace_gradient_with_lod(), nir_tex_instr::sampler_dim, nir_tex_src::src, nir_tex_instr::src, and nir_src::ssa.
Referenced by nir_lower_tex_block().
lower_offset()
static bool lower_offset (nir_builder * b, nir_tex_instr * tex) static
References nir_tex_instr::coord_components, nir_builder::cursor, nir_tex_instr::instr, nir_tex_instr::is_array, nir_src::is_ssa, nir_before_instr(), nir_channel(), nir_instr_rewrite_src(), nir_src_for_ssa(), nir_tex_instr_remove_src(), nir_tex_instr_src_index(), nir_tex_instr_src_type(), nir_tex_src_coord, nir_tex_src_offset, nir_type_float, nir_tex_instr::sampler_dim, nir_tex_src::src, nir_tex_instr::src, and nir_src::ssa.
Referenced by nir_lower_tex_block().
lower_rect()
static void lower_rect (nir_builder * b, nir_tex_instr * tex) static
References nir_tex_instr::coord_components, get_texture_size(), nir_tex_instr::instr, nir_instr_rewrite_src(), nir_src_for_ssa(), nir_ssa_for_src(), nir_tex_src_coord, nir_tex_instr::num_srcs, nir_tex_instr::sampler_dim, nir_tex_src::src, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by nir_lower_tex_block().
lower_y_u_v_external()
static void lower_y_u_v_external (nir_builder * b, nir_tex_instr * tex) static
References convert_yuv_to_rgb(), nir_builder::cursor, nir_tex_instr::instr, nir_after_instr(), nir_channel(), and sample_plane().
Referenced by nir_lower_tex_block().
lower_y_uv_external()
static void lower_y_uv_external (nir_builder * b, nir_tex_instr * tex) static
References convert_yuv_to_rgb(), nir_builder::cursor, nir_tex_instr::instr, nir_after_instr(), nir_channel(), and sample_plane().
Referenced by nir_lower_tex_block().
lower_yx_xuxv_external()
static void lower_yx_xuxv_external (nir_builder * b, nir_tex_instr * tex) static
References convert_yuv_to_rgb(), nir_builder::cursor, nir_tex_instr::instr, nir_after_instr(), nir_channel(), and sample_plane().
Referenced by nir_lower_tex_block().
nir_lower_tex()
bool nir_lower_tex (nir_shader * shader, const nir_lower_tex_options * options)
References nir_foreach_function, and nir_lower_tex_impl().
nir_lower_tex_block()
static bool nir_lower_tex_block (nir_block * block, nir_builder * b, const nir_lower_tex_options * options) static
References instr, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, linearize_srgb_result(), lower_gradient_cube_map(), lower_gradient_shadow(), lower_offset(), lower_rect(), nir_lower_tex_options::lower_rect, nir_lower_tex_options::lower_rect_offset, nir_lower_tex_options::lower_srgb, nir_lower_tex_options::lower_txd_cube_map, nir_lower_tex_options::lower_txd_shadow, nir_lower_tex_options::lower_txf_offset, nir_lower_tex_options::lower_txp, lower_y_u_v_external(), nir_lower_tex_options::lower_y_u_v_external, lower_y_uv_external(), nir_lower_tex_options::lower_y_uv_external, lower_yx_xuxv_external(), nir_lower_tex_options::lower_yx_xuxv_external, nir_foreach_instr_safe, nir_instr_type_tex, nir_tex_instr_is_query(), nir_texop_txd, nir_texop_txf, nir_tex_instr::op, project_src(), nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_lower_tex_options::saturate_r, nir_lower_tex_options::saturate_s, saturate_src(), nir_lower_tex_options::saturate_t, swizzle_result(), nir_lower_tex_options::swizzle_result, nir_lower_tex_options::swizzles, and nir_tex_instr::texture_index.
Referenced by nir_lower_tex_impl().
nir_lower_tex_impl()
static bool nir_lower_tex_impl (nir_function_impl * impl, const nir_lower_tex_options * options) static
References lower_returns_state::builder, nir_builder_init(), nir_foreach_block, nir_lower_tex_block(), nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_tex().
project_src()
static void project_src (nir_builder * b, nir_tex_instr * tex) static
References nir_tex_instr::coord_components, nir_builder::cursor, nir_tex_instr::instr, nir_tex_instr::is_array, nir_before_instr(), nir_channel(), nir_instr_rewrite_src(), nir_src_for_ssa(), nir_ssa_for_src(), nir_tex_instr_remove_src(), nir_tex_instr_src_index(), nir_tex_instr_src_size(), nir_tex_src_comparator, nir_tex_src_coord, nir_tex_src_projector, nir_tex_instr::num_srcs, nir_tex_src::src, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by nir_lower_tex_block().
replace_gradient_with_lod()
static void replace_gradient_with_lod (nir_builder * b, nir_ssa_def * lod, nir_tex_instr * tex) static
References nir_tex_instr::coord_components, nir_tex_instr::dest, nir_tex_instr::dest_type, nir_tex_instr::instr, nir_tex_instr::is_array, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, nir_builder_instr_insert(), nir_deref_var_clone(), nir_instr_remove(), nir_src_copy(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_tex_instr_create(), nir_tex_src_ddx, nir_tex_src_ddy, nir_tex_src_lod, nir_texop_txl, nir_ssa_def::num_components, nir_tex_instr::num_srcs, nir_tex_instr::op, nir_tex_instr::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_builder::shader, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_dest::ssa, nir_tex_instr::texture, and nir_tex_instr::texture_index.
Referenced by lower_gradient_cube_map(), and lower_gradient_shadow().
sample_plane()
static nir_ssa_def* sample_plane (nir_builder * b, nir_tex_instr * tex, int plane) static
References nir_tex_instr::coord_components, nir_tex_instr::dest, nir_tex_instr::dest_type, nir_tex_instr::instr, nir_dest::is_ssa, nir_alu_type_get_base_type(), nir_builder_instr_insert(), nir_deref_var_clone(), nir_imm_int(), nir_src_copy(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_tex_instr_create(), nir_tex_instr_dest_size(), nir_tex_src_coord, nir_tex_src_plane, nir_texop_tex, nir_type_float, nir_tex_instr::op, nir_tex_instr::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_builder::shader, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_dest::ssa, nir_tex_instr::texture, and nir_tex_instr::texture_index.
Referenced by lower_y_u_v_external(), lower_y_uv_external(), and lower_yx_xuxv_external().
saturate_src()
static void saturate_src (nir_builder * b, nir_tex_instr * tex, unsigned sat_mask) static
References nir_tex_instr::coord_components, nir_builder::cursor, get_texture_size(), nir_tex_instr::instr, nir_tex_instr::is_array, nir_before_instr(), nir_channel(), nir_imm_float(), nir_instr_rewrite_src(), nir_src_for_ssa(), nir_ssa_for_src(), nir_tex_src_coord, nir_vec(), nir_tex_instr::num_srcs, nir_tex_instr::sampler_dim, nir_tex_src::src, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by nir_lower_tex_block().
swizzle_result()
static void swizzle_result (nir_builder * b, nir_tex_instr * tex, const uint8_t swizzle[4]) static
References nir_tex_instr::component, nir_builder::cursor, nir_tex_instr::dest, nir_tex_instr::dest_type, get_zero_or_one(), nir_tex_instr::instr, nir_dest::is_ssa, nir_after_instr(), nir_channel(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses_after(), nir_swizzle(), nir_tex_instr_dest_size(), nir_texop_tg4, nir_vec(), nir_tex_instr::op, nir_ssa_def::parent_instr, and nir_dest::ssa.
Referenced by nir_lower_tex_block().