Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_two_sided_color.c File Reference
#include "nir.h"
#include "nir_builder.h"
Data Structures
struct lower_2side_state
Macros
#define MAX_COLORS 2 /* VARYING_SLOT_COL0/COL1 */
Functions
static nir_variable * create_input (nir_shader *shader, unsigned drvloc, gl_varying_slot slot)
static nir_ssa_def * load_input (nir_builder *b, nir_variable *in)
static int setup_inputs (lower_2side_state *state)
static bool nir_lower_two_sided_color_block (nir_block *block, lower_2side_state *state)
static void nir_lower_two_sided_color_impl (nir_function_impl *impl, lower_2side_state *state)
void nir_lower_two_sided_color (nir_shader *shader)
Macro Definition Documentation
MAX_COLORS
#define MAX_COLORS 2 /* VARYING_SLOT_COL0/COL1 */
Function Documentation
create_input()
static nir_variable* create_input (nir_shader * shader, unsigned drvloc, gl_varying_slot slot) static
References nir_variable::data, nir_variable::nir_variable_data::driver_location, nir_variable::nir_variable_data::index, nir_shader::inputs, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_variable::name, nir_var_shader_in, nir_variable::node, nir_shader::num_inputs, and nir_variable::type.
Referenced by setup_inputs().
load_input()
static nir_ssa_def* load_input (nir_builder * b, nir_variable * in) static
References nir_variable::data, nir_intrinsic_instr::dest, nir_variable::nir_variable_data::driver_location, nir_intrinsic_instr::instr, nir_builder_instr_insert(), nir_imm_int(), nir_intrinsic_instr_create(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_intrinsic_instr::num_components, nir_builder::shader, nir_intrinsic_instr::src, and nir_dest::ssa.
Referenced by nir_lower_two_sided_color_block().
nir_lower_two_sided_color()
void nir_lower_two_sided_color (nir_shader * shader)
References nir_foreach_function, nir_lower_two_sided_color_impl(), setup_inputs(), and nir_shader::stage.
nir_lower_two_sided_color_block()
static bool nir_lower_two_sided_color_block (nir_block * block, lower_2side_state * state) static
References lower_2side_state::b, lower_2side_state::back, lower_2side_state::colors, lower_2side_state::colors_count, nir_builder::cursor, nir_variable::data, nir_intrinsic_instr::dest, nir_variable::nir_variable_data::driver_location, lower_2side_state::front, nir_intrinsic_instr::instr, instr, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, load_input(), nir_before_instr(), nir_foreach_instr_safe, nir_instr_type_intrinsic, nir_src_as_const_value(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_intrinsic_instr::src, and nir_dest::ssa.
Referenced by nir_lower_two_sided_color_impl().
nir_lower_two_sided_color_impl()
static void nir_lower_two_sided_color_impl (nir_function_impl * impl, lower_2side_state * state) static
References lower_2side_state::b, nir_builder_init(), nir_foreach_block, nir_lower_two_sided_color_block(), nir_metadata_block_index, nir_metadata_dominance, and nir_metadata_preserve().
Referenced by nir_lower_two_sided_color().
setup_inputs()
static int setup_inputs (lower_2side_state * state) static
References lower_2side_state::back, lower_2side_state::colors, lower_2side_state::colors_count, create_input(), nir_variable::data, lower_2side_state::front, nir_shader::inputs, nir_variable::nir_variable_data::location, nir_foreach_variable, and lower_2side_state::shader.
Referenced by nir_lower_two_sided_color().