Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_constant_initializers.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static bool deref_apply_constant_initializer (nir_deref_var *deref, void *state)
static bool lower_const_initializer (struct nir_builder *b, struct exec_list *var_list)
bool nir_lower_constant_initializers (nir_shader *shader, nir_variable_mode modes)
Function Documentation
deref_apply_constant_initializer()
static bool deref_apply_constant_initializer (nir_deref_var * deref, void * state) static
References nir_load_const_instr::def, nir_load_const_instr::instr, nir_builder_instr_insert(), nir_deref_get_const_initializer_load(), nir_store_deref_var(), and nir_builder::shader.
Referenced by lower_const_initializer().
lower_const_initializer()
static bool lower_const_initializer (struct nir_builder * b, struct exec_list * var_list) static
References nir_function_impl::body, nir_deref::child, nir_builder::cursor, nir_deref_var::deref, deref, deref_apply_constant_initializer(), nir_deref::deref_type, nir_builder::impl, nir_before_cf_list(), nir_deref_foreach_leaf(), nir_deref_type_var, nir_foreach_variable, nir_deref::type, and nir_deref_var::var.
Referenced by nir_lower_constant_initializers().
nir_lower_constant_initializers()
bool nir_lower_constant_initializers (nir_shader * shader, nir_variable_mode modes)
References nir_shader::globals, nir_builder::impl, nir_function_impl::locals, lower_const_initializer(), nir_builder_init(), nir_foreach_function, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_preserve(), nir_shader_get_entrypoint(), nir_var_global, nir_var_local, nir_var_shader_out, nir_var_system_value, nir_shader::outputs, and nir_shader::system_values.