Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_loop_analyze.h File Reference
#include "nir.h"
Functions
static bool contains_other_jump (nir_cf_node *node, nir_instr *expected_jump)
static bool nir_is_trivial_loop_if (nir_if *nif, nir_block *break_block)
Function Documentation
contains_other_jump()
static bool contains_other_jump (nir_cf_node * node, nir_instr * expected_jump) inline static
References nir_if::else_list, foreach_list_typed_safe, instr, nir_block_last_instr(), nir_foreach_instr, nir_instr_type_jump, nir_if::then_list, nir_instr::type, and nir_cf_node::type.
Referenced by nir_is_trivial_loop_if().
nir_is_trivial_loop_if()
static bool nir_is_trivial_loop_if (nir_if * nif, nir_block * break_block) inline static
References nir_if::cf_node, contains_other_jump(), nir_block_last_instr(), nir_instr_type_jump, nir_jump_break, nir_instr::type, and type.
Referenced by complex_unroll(), find_loop_terminators(), and simple_unroll().