Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir.c File Reference
#include "nir.h"
#include "nir_control_flow_private.h"
#include <assert.h>
Data Structures
struct foreach_ssa_def_state
struct visit_dest_indirect_state
Functions
nir_shader * nir_shader_create (void *mem_ctx, gl_shader_stage stage, const nir_shader_compiler_options *options, shader_info *si)
static nir_register * reg_create (void *mem_ctx, struct exec_list *list)
nir_register * nir_global_reg_create (nir_shader *shader)
creates a register, including assigning it an index and adding it to the list
nir_register * nir_local_reg_create (nir_function_impl *impl)
void nir_reg_remove (nir_register *reg)
void nir_shader_add_variable (nir_shader *shader, nir_variable *var)
Adds a variable to the appropriate list in nir_shader.
nir_variable * nir_variable_create (nir_shader *shader, nir_variable_mode mode, const struct glsl_type *type, const char *name)
creates a variable, sets a few defaults, and adds it to the list
nir_variable * nir_local_variable_create (nir_function_impl *impl, const struct glsl_type *type, const char *name)
creates a local variable and adds it to the list
nir_function * nir_function_create (nir_shader *shader, const char *name)
creates a function and adds it to the shader's list of functions
void nir_src_copy (nir_src *dest, const nir_src *src, void *mem_ctx)
void nir_dest_copy (nir_dest *dest, const nir_dest *src, nir_instr *instr)
void nir_alu_src_copy (nir_alu_src *dest, const nir_alu_src *src, nir_alu_instr *instr)
void nir_alu_dest_copy (nir_alu_dest *dest, const nir_alu_dest *src, nir_alu_instr *instr)
static void cf_init (nir_cf_node *node, nir_cf_node_type type)
nir_function_impl * nir_function_impl_create_bare (nir_shader *shader)
creates a function_impl that isn't tied to any particular function
nir_function_impl * nir_function_impl_create (nir_function *function)
nir_block * nir_block_create (nir_shader *shader)
static void src_init (nir_src *src)
nir_if * nir_if_create (nir_shader *shader)
nir_loop * nir_loop_create (nir_shader *shader)
static void instr_init (nir_instr *instr, nir_instr_type type)
static void dest_init (nir_dest *dest)
static void alu_dest_init (nir_alu_dest *dest)
static void alu_src_init (nir_alu_src *src)
nir_alu_instr * nir_alu_instr_create (nir_shader *shader, nir_op op)
creates an instruction with default swizzle/writemask/etc.
nir_jump_instr * nir_jump_instr_create (nir_shader *shader, nir_jump_type type)
nir_load_const_instr * nir_load_const_instr_create (nir_shader *shader, unsigned num_components, unsigned bit_size)
nir_intrinsic_instr * nir_intrinsic_instr_create (nir_shader *shader, nir_intrinsic_op op)
nir_call_instr * nir_call_instr_create (nir_shader *shader, nir_function *callee)
nir_tex_instr * nir_tex_instr_create (nir_shader *shader, unsigned num_srcs)
void nir_tex_instr_remove_src (nir_tex_instr *tex, unsigned src_idx)
nir_phi_instr * nir_phi_instr_create (nir_shader *shader)
nir_parallel_copy_instr * nir_parallel_copy_instr_create (nir_shader *shader)
nir_ssa_undef_instr * nir_ssa_undef_instr_create (nir_shader *shader, unsigned num_components, unsigned bit_size)
nir_deref_var * nir_deref_var_create (void *mem_ctx, nir_variable *var)
nir_deref_array * nir_deref_array_create (void *mem_ctx)
nir_deref_struct * nir_deref_struct_create (void *mem_ctx, unsigned field_index)
nir_deref_var * nir_deref_var_clone (const nir_deref_var *deref, void *mem_ctx)
static nir_deref_array * deref_array_clone (const nir_deref_array *deref, void *mem_ctx)
static nir_deref_struct * deref_struct_clone (const nir_deref_struct *deref, void *mem_ctx)
nir_deref * nir_deref_clone (const nir_deref *deref, void *mem_ctx)
static bool deref_foreach_leaf_build_recur (nir_deref_var *deref, nir_deref *tail, nir_deref_foreach_leaf_cb cb, void *state)
static bool deref_foreach_leaf_copy_recur (nir_deref_var *deref, nir_deref *tail, nir_deref_foreach_leaf_cb cb, void *state)
bool nir_deref_foreach_leaf (nir_deref_var *deref, nir_deref_foreach_leaf_cb cb, void *state)
This function iterates over all of the possible derefs that can be created with the given deref as the head.
nir_load_const_instr * nir_deref_get_const_initializer_load (nir_shader *shader, nir_deref_var *deref)
nir_function_impl * nir_cf_node_get_function (nir_cf_node *node)
static nir_cursor reduce_cursor (nir_cursor cursor)
bool nir_cursors_equal (nir_cursor a, nir_cursor b)
static bool add_use_cb (nir_src *src, void *state)
static bool add_ssa_def_cb (nir_ssa_def *def, void *state)
static bool add_reg_def_cb (nir_dest *dest, void *state)
static void add_defs_uses (nir_instr *instr)
void nir_instr_insert (nir_cursor cursor, nir_instr *instr)
Insert a NIR instruction at the given cursor.
static bool src_is_valid (const nir_src *src)
static bool remove_use_cb (nir_src *src, void *state)
static bool remove_def_cb (nir_dest *dest, void *state)
static void remove_defs_uses (nir_instr *instr)
void nir_instr_remove (nir_instr *instr)
void nir_index_local_regs (nir_function_impl *impl)
void nir_index_global_regs (nir_shader *shader)
static bool visit_alu_dest (nir_alu_instr *instr, nir_foreach_dest_cb cb, void *state)
static bool visit_intrinsic_dest (nir_intrinsic_instr *instr, nir_foreach_dest_cb cb, void *state)
static bool visit_texture_dest (nir_tex_instr *instr, nir_foreach_dest_cb cb, void *state)
static bool visit_phi_dest (nir_phi_instr *instr, nir_foreach_dest_cb cb, void *state)
static bool visit_parallel_copy_dest (nir_parallel_copy_instr *instr, nir_foreach_dest_cb cb, void *state)
bool nir_foreach_dest (nir_instr *instr, nir_foreach_dest_cb cb, void *state)
static bool nir_ssa_def_visitor (nir_dest *dest, void *void_state)
bool nir_foreach_ssa_def (nir_instr *instr, nir_foreach_ssa_def_cb cb, void *state)
static bool visit_src (nir_src *src, nir_foreach_src_cb cb, void *state)
static bool visit_deref_array_src (nir_deref_array *deref, nir_foreach_src_cb cb, void *state)
static bool visit_deref_src (nir_deref_var *deref, nir_foreach_src_cb cb, void *state)
static bool visit_alu_src (nir_alu_instr *instr, nir_foreach_src_cb cb, void *state)
static bool visit_tex_src (nir_tex_instr *instr, nir_foreach_src_cb cb, void *state)
static bool visit_intrinsic_src (nir_intrinsic_instr *instr, nir_foreach_src_cb cb, void *state)
static bool visit_phi_src (nir_phi_instr *instr, nir_foreach_src_cb cb, void *state)
static bool visit_parallel_copy_src (nir_parallel_copy_instr *instr, nir_foreach_src_cb cb, void *state)
static bool visit_dest_indirect (nir_dest *dest, void *_state)
bool nir_foreach_src (nir_instr *instr, nir_foreach_src_cb cb, void *state)
nir_const_value * nir_src_as_const_value (nir_src src)
bool nir_src_is_dynamically_uniform (nir_src src)
Returns true if the source is known to be dynamically uniform.
static void src_remove_all_uses (nir_src *src)
static void src_add_all_uses (nir_src *src, nir_instr *parent_instr, nir_if *parent_if)
void nir_instr_rewrite_src (nir_instr *instr, nir_src *src, nir_src new_src)
void nir_instr_move_src (nir_instr *dest_instr, nir_src *dest, nir_src *src)
void nir_if_rewrite_condition (nir_if *if_stmt, nir_src new_src)
void nir_instr_rewrite_dest (nir_instr *instr, nir_dest *dest, nir_dest new_dest)
void nir_ssa_def_init (nir_instr *instr, nir_ssa_def *def, unsigned num_components, unsigned bit_size, const char *name)
void nir_ssa_dest_init (nir_instr *instr, nir_dest *dest, unsigned num_components, unsigned bit_size, const char *name)
void nir_ssa_def_rewrite_uses (nir_ssa_def *def, nir_src new_src)
static bool is_instr_between (nir_instr *start, nir_instr *end, nir_instr *between)
void nir_ssa_def_rewrite_uses_after (nir_ssa_def *def, nir_src new_src, nir_instr *after_me)
uint8_t nir_ssa_def_components_read (nir_ssa_def *def)
nir_block * nir_block_cf_tree_next (nir_block *block)
nir_block * nir_block_cf_tree_prev (nir_block *block)
nir_block * nir_cf_node_cf_tree_first (nir_cf_node *node)
nir_block * nir_cf_node_cf_tree_last (nir_cf_node *node)
nir_block * nir_cf_node_cf_tree_next (nir_cf_node *node)
nir_if * nir_block_get_following_if (nir_block *block)
nir_loop * nir_block_get_following_loop (nir_block *block)
void nir_index_blocks (nir_function_impl *impl)
static bool index_ssa_def_cb (nir_ssa_def *def, void *state)
void nir_index_ssa_defs (nir_function_impl *impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
unsigned nir_index_instrs (nir_function_impl *impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
nir_intrinsic_op nir_intrinsic_from_system_value (gl_system_value val)
gl_system_value nir_system_value_from_intrinsic (nir_intrinsic_op intrin)
Function Documentation
add_defs_uses()
static void add_defs_uses (nir_instr * instr) static
References add_reg_def_cb(), add_ssa_def_cb(), add_use_cb(), nir_foreach_dest(), nir_foreach_src(), and nir_foreach_ssa_def().
Referenced by nir_instr_insert().
add_reg_def_cb()
static bool add_reg_def_cb (nir_dest * dest, void * state) static
References nir_reg_dest::def_link, nir_register::defs, instr, nir_dest::is_ssa, nir_reg_dest::parent_instr, nir_reg_dest::reg, and nir_dest::reg.
Referenced by add_defs_uses().
add_ssa_def_cb()
static bool add_ssa_def_cb (nir_ssa_def * def, void * state) static
References nir_instr::block, nir_block::cf_node, nir_ssa_def::index, instr, nir_cf_node_get_function(), and nir_function_impl::ssa_alloc.
Referenced by add_defs_uses().
add_use_cb()
static bool add_use_cb (nir_src * src, void * state) static
References instr, nir_src::is_ssa, nir_src::parent_instr, nir_reg_src::reg, nir_src::reg, nir_src::ssa, nir_src::use_link, nir_register::uses, and nir_ssa_def::uses.
Referenced by add_defs_uses().
alu_dest_init()
static void alu_dest_init (nir_alu_dest * dest) static
References nir_alu_dest::dest, dest_init(), nir_alu_dest::saturate, and nir_alu_dest::write_mask.
Referenced by nir_alu_instr_create().
alu_src_init()
static void alu_src_init (nir_alu_src * src) static
References nir_alu_src::abs, nir_alu_src::negate, nir_alu_src::src, src_init(), and nir_alu_src::swizzle.
Referenced by nir_alu_instr_create().
cf_init()
static void cf_init (nir_cf_node * node, nir_cf_node_type type) static
References nir_cf_node::node, nir_cf_node::parent, type, and nir_cf_node::type.
Referenced by nir_block_create(), nir_function_impl_create_bare(), nir_if_create(), and nir_loop_create().
deref_array_clone()
static nir_deref_array* deref_array_clone (const nir_deref_array * deref, void * mem_ctx) static
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref, nir_deref_array::deref_array_type, nir_deref_array::indirect, nir_deref_array_create(), nir_deref_array_type_indirect, nir_deref_clone(), nir_src_copy(), ret(), and nir_deref::type.
Referenced by nir_deref_clone().
deref_foreach_leaf_build_recur()
static bool deref_foreach_leaf_build_recur (nir_deref_var * deref, nir_deref * tail, nir_deref_foreach_leaf_cb cb, void * state) static
References nir_deref::child, nir_deref_var::deref, nir_deref_array_type_direct, nir_deref_type_array, nir_deref_type_struct, NIR_SRC_INIT, and nir_deref::type.
Referenced by deref_foreach_leaf_copy_recur().
deref_foreach_leaf_copy_recur()
static bool deref_foreach_leaf_copy_recur (nir_deref_var * deref, nir_deref * tail, nir_deref_foreach_leaf_cb cb, void * state) static
References nir_deref::child, nir_deref_var::deref, deref_foreach_leaf_build_recur(), nir_deref::deref_type, nir_deref_type_array, nir_deref_type_struct, and nir_deref_type_var.
Referenced by nir_deref_foreach_leaf().
deref_struct_clone()
static nir_deref_struct* deref_struct_clone (const nir_deref_struct * deref, void * mem_ctx) static
References nir_deref::child, nir_deref_struct::deref, nir_deref_struct::index, nir_deref_clone(), nir_deref_struct_create(), ret(), and nir_deref::type.
Referenced by nir_deref_clone().
dest_init()
static void dest_init (nir_dest * dest) static
References nir_reg_dest::base_offset, nir_reg_dest::indirect, nir_dest::is_ssa, nir_reg_dest::reg, and nir_dest::reg.
Referenced by alu_dest_init(), nir_intrinsic_instr_create(), nir_phi_instr_create(), and nir_tex_instr_create().
index_ssa_def_cb()
static bool index_ssa_def_cb (nir_ssa_def * def, void * state) static
References nir_ssa_def::index.
Referenced by nir_index_ssa_defs().
instr_init()
static void instr_init (nir_instr * instr, nir_instr_type type) static
References nir_instr::block, nir_instr::node, nir_instr::type, and type.
Referenced by nir_alu_instr_create(), nir_call_instr_create(), nir_intrinsic_instr_create(), nir_jump_instr_create(), nir_load_const_instr_create(), nir_parallel_copy_instr_create(), nir_phi_instr_create(), nir_ssa_undef_instr_create(), and nir_tex_instr_create().
is_instr_between()
static bool is_instr_between (nir_instr * start, nir_instr * end, nir_instr * between) static
References nir_instr::block, and nir_instr_prev().
Referenced by nir_ssa_def_rewrite_uses_after().
nir_alu_dest_copy()
void nir_alu_dest_copy (nir_alu_dest * dest, const nir_alu_dest * src, nir_alu_instr * instr)
References nir_alu_dest::dest, nir_alu_instr::instr, nir_dest_copy(), nir_alu_dest::saturate, and nir_alu_dest::write_mask.
Referenced by insert_mov().
nir_alu_instr_create()
nir_alu_instr* nir_alu_instr_create (nir_shader * shader, nir_op op)
creates an instruction with default swizzle/writemask/etc.
with NULL registers
References alu_dest_init(), alu_src_init(), nir_alu_instr::dest, nir_alu_instr::instr, instr, instr_init(), nir_instr_type_alu, nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, and nir_alu_instr::src.
Referenced by clone_alu(), construct_value(), emit_copy(), get_deref_reg_src(), insert_mov(), lower_alu_instr_scalar(), lower_instr(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_reduction(), nir_build_alu(), nir_fmov_alu(), nir_function_impl_add_variable(), nir_imov_alu(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_opt_peephole_select_block(), nir_replace_instr(), place_phi_read(), rename_variables(), and rewrite_alu_instr().
nir_alu_src_copy()
void nir_alu_src_copy (nir_alu_src * dest, const nir_alu_src * src, nir_alu_instr * instr)
References nir_alu_src::abs, nir_alu_instr::instr, nir_alu_src::negate, nir_src_copy(), nir_alu_src::src, and nir_alu_src::swizzle.
Referenced by construct_value(), insert_mov(), lower_alu_instr_scalar(), lower_reduction(), and opt_undef_csel().
nir_block_cf_tree_next()
nir_block* nir_block_cf_tree_next (nir_block * block)
References nir_block::cf_node, nir_cf_node_cf_tree_first(), nir_cf_node_next(), nir_if_first_else_block(), nir_if_last_else_block(), nir_if_last_then_block(), nir_cf_node::parent, and nir_cf_node::type.
Referenced by nir_cf_node_cf_tree_next().
nir_block_cf_tree_prev()
nir_block* nir_block_cf_tree_prev (nir_block * block)
References nir_block::cf_node, nir_cf_node_cf_tree_last(), nir_cf_node_prev(), nir_if_first_else_block(), nir_if_first_then_block(), nir_if_last_then_block(), nir_cf_node::parent, and nir_cf_node::type.
nir_block_create()
nir_block* nir_block_create (nir_shader * shader)
References cf_init(), nir_block::cf_node, nir_block::dom_frontier, nir_block::imm_dom, nir_block::instr_list, nir_block::predecessors, and nir_block::successors.
Referenced by nir_cf_list_clone(), nir_function_impl_add_variable(), nir_function_impl_create_bare(), nir_if_create(), nir_loop_create(), split_block_beginning(), and split_block_end().
nir_block_get_following_if()
nir_if* nir_block_get_following_if (nir_block * block)
References nir_block::cf_node, nir_cf_node_is_last(), nir_cf_node_next(), nir_cf_node::node, and nir_cf_node::type.
Referenced by dead_cf_block(), init_block(), move_comparisons(), nir_copy_prop_impl(), nir_live_ssa_defs_impl(), and nir_lower_regs_to_ssa_impl().
nir_block_get_following_loop()
nir_loop* nir_block_get_following_loop (nir_block * block)
References nir_block::cf_node, nir_cf_node_is_last(), nir_cf_node_next(), nir_cf_node::node, and nir_cf_node::type.
Referenced by dead_cf_block().
nir_call_instr_create()
nir_call_instr* nir_call_instr_create (nir_shader * shader, nir_function * callee)
References nir_call_instr::callee, nir_call_instr::instr, instr, instr_init(), nir_instr_type_call, nir_call_instr::num_params, nir_function::num_params, nir_call_instr::params, and nir_call_instr::return_deref.
Referenced by clone_call(), and nir_function_impl_add_variable().
nir_cf_node_cf_tree_first()
nir_block* nir_cf_node_cf_tree_first (nir_cf_node * node)
References nir_if_first_then_block(), nir_loop_first_block(), nir_start_block(), and nir_cf_node::type.
Referenced by nir_block_cf_tree_next().
nir_cf_node_cf_tree_last()
nir_block* nir_cf_node_cf_tree_last (nir_cf_node * node)
References nir_if_last_else_block(), nir_impl_last_block(), nir_loop_last_block(), and nir_cf_node::type.
Referenced by nir_block_cf_tree_prev().
nir_cf_node_cf_tree_next()
nir_block* nir_cf_node_cf_tree_next (nir_cf_node * node)
References nir_block_cf_tree_next(), nir_cf_node_next(), and nir_cf_node::type.
nir_cf_node_get_function()
nir_function_impl* nir_cf_node_get_function (nir_cf_node * node)
References nir_cf_node::parent, and nir_cf_node::type.
Referenced by add_ssa_def_cb(), global_to_local(), insert_phi_undef(), loop_is_dead(), lower_doubles_instr(), lower_load_const_instr_scalar(), nir_block_dominates(), nir_cf_extract(), nir_convert_loop_to_lcssa(), nir_dominance_lca(), nir_function_impl_add_variable(), nir_handle_add_jump(), nir_handle_remove_jump(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_ssa_def_init(), and process_loops().
nir_cursors_equal()
bool nir_cursors_equal (nir_cursor a, nir_cursor b)
References nir_cursor::block, nir_cursor::option, and reduce_cursor().
Referenced by nir_cf_extract(), nir_cursor_current_block(), and predicate_following().
nir_deref_array_create()
nir_deref_array* nir_deref_array_create (void * mem_ctx)
References nir_deref_array::base_offset, nir_deref::child, nir_deref_array::deref, deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_deref_array::indirect, nir_deref_array_type_direct, nir_deref_type_array, and src_init().
Referenced by clone_deref_array(), deref_array_clone(), nir_function_impl_add_variable(), specialize_wildcards(), and split_var_copy_instr().
nir_deref_clone()
nir_deref* nir_deref_clone (const nir_deref * deref, void * mem_ctx)
References nir_deref_var::deref, nir_deref_array::deref, nir_deref_struct::deref, deref_array_clone(), deref_struct_clone(), nir_deref::deref_type, nir_deref_type_array, nir_deref_type_struct, nir_deref_type_var, and nir_deref_var_clone().
Referenced by deref_array_clone(), deref_struct_clone(), load_from_deref_entry_value(), and nir_deref_var_clone().
nir_deref_foreach_leaf()
bool nir_deref_foreach_leaf (nir_deref_var * deref, nir_deref_foreach_leaf_cb cb, void * state)
This function iterates over all of the possible derefs that can be created with the given deref as the head.
It then calls the provided callback with a full deref for each one.
The deref passed to the callback will be allocated on the stack. You will need to make a copy if you want it to hang around.
References nir_deref_var::deref, deref, and deref_foreach_leaf_copy_recur().
Referenced by lower_const_initializer().
nir_deref_get_const_initializer_load()
nir_load_const_instr* nir_deref_get_const_initializer_load (nir_shader * shader, nir_deref_var * deref)
References nir_deref_array::base_offset, nir_deref::child, nir_variable::constant_initializer, nir_deref_var::deref, nir_deref_array::deref, nir_deref_array::deref_array_type, nir_deref::deref_type, nir_constant::elements, nir_deref_array_type_direct, nir_deref_type_array, nir_deref_type_struct, nir_load_const_instr_create(), nir_deref::type, nir_load_const_instr::value, nir_constant::values, and nir_deref_var::var.
Referenced by deref_apply_constant_initializer().
nir_deref_struct_create()
nir_deref_struct* nir_deref_struct_create (void * mem_ctx, unsigned field_index)
References nir_deref::child, nir_deref_struct::deref, deref, nir_deref::deref_type, nir_deref_struct::index, and nir_deref_type_struct.
Referenced by clone_deref_struct(), deref_struct_clone(), nir_function_impl_add_variable(), specialize_wildcards(), and split_var_copy_instr().
nir_deref_var_clone()
nir_deref_var* nir_deref_var_clone (const nir_deref_var * deref, void * mem_ctx)
References nir_deref::child, nir_deref_var::deref, nir_deref_clone(), nir_deref_var_create(), ret(), nir_deref::type, and nir_deref_var::var.
Referenced by convert_deref_to_param_deref(), emit_copy_load_store(), emit_load_store(), get_texture_size(), load_from_deref_entry_value(), nir_copy_deref_var(), nir_deref_clone(), nir_load_deref_var(), nir_store_deref_var(), replace_gradient_with_lod(), sample_plane(), and split_var_copy_instr().
nir_deref_var_create()
nir_deref_var* nir_deref_var_create (void * mem_ctx, nir_variable * var)
References nir_deref::child, nir_deref_var::deref, deref, nir_deref::deref_type, nir_deref_type_var, nir_variable::type, nir_deref::type, and nir_deref_var::var.
Referenced by clone_deref_var(), emit_copies(), inline_functions_block(), lower_io_types_block(), nir_copy_var(), nir_deref_var_clone(), nir_function_impl_add_variable(), nir_load_var(), nir_store_var(), and specialize_wildcards().
nir_dest_copy()
void nir_dest_copy (nir_dest * dest, const nir_dest * src, nir_instr * instr)
References nir_reg_dest::base_offset, nir_reg_dest::indirect, nir_dest::is_ssa, nir_src_copy(), nir_reg_dest::reg, and nir_dest::reg.
Referenced by lower_instr(), lower_locals_to_regs_block(), nir_alu_dest_copy(), nir_dest_bit_size(), nir_instr_rewrite_dest(), and nir_lower_io_block().
nir_foreach_dest()
bool nir_foreach_dest (nir_instr * instr, nir_foreach_dest_cb cb, void * state)
References nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, nir_instr::type, visit_alu_dest(), visit_intrinsic_dest(), visit_parallel_copy_dest(), visit_phi_dest(), and visit_texture_dest().
Referenced by add_defs_uses(), instr_can_rewrite(), nir_foreach_src(), nir_foreach_ssa_def(), nir_lower_regs_to_ssa_impl(), nir_lower_ssa_defs_to_regs_block(), remove_defs_uses(), and sweep_block().
nir_foreach_src()
bool nir_foreach_src (nir_instr * instr, nir_foreach_src_cb cb, void * state)
References foreach_ssa_def_state::cb, visit_dest_indirect_state::cb, nir_foreach_dest(), nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, visit_dest_indirect_state::state, nir_instr::type, visit_alu_src(), visit_dest_indirect(), visit_intrinsic_src(), visit_parallel_copy_src(), visit_phi_src(), and visit_tex_src().
Referenced by add_defs_uses(), gcm_schedule_early_instr(), instr_can_rewrite(), move_comparisons(), nir_live_ssa_defs_impl(), nir_lower_regs_to_ssa_impl(), nir_opt_dce_impl(), propagate_invariant_instr(), remove_defs_uses(), rewrite_alu_instr(), search_for_use_after_instr(), and sweep_block().
nir_foreach_ssa_def()
bool nir_foreach_ssa_def (nir_instr * instr, nir_foreach_ssa_def_cb cb, void * state)
References foreach_ssa_def_state::cb, nir_foreach_dest(), nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, nir_ssa_def_visitor(), and nir_instr::type.
Referenced by add_defs_uses(), cleanup_cf_node(), convert_to_lcssa(), gcm_place_instr(), gcm_schedule_late_instr(), get_loop_info(), init_loop_block(), loop_is_dead(), nir_index_ssa_defs(), nir_live_ssa_defs_impl(), nir_repair_ssa_impl(), and resolve_registers_block().
nir_function_create()
nir_function* nir_function_create (nir_shader * shader, const char * name)
creates a function and adds it to the shader's list of functions
References nir_shader::functions, nir_function::impl, nir_function::name, nir_function::node, nir_function::num_params, nir_function::params, nir_function::return_type, and nir_function::shader.
Referenced by clone_function(), nir_builder_init_simple_shader(), and nir_function_impl_add_variable().
nir_function_impl_create()
nir_function_impl* nir_function_impl_create (nir_function * function)
References nir_variable::data, nir_function_impl::function, nir_variable::nir_variable_data::location, nir_variable::nir_variable_data::mode, nir_function_impl_create_bare(), nir_var_param, nir_function_impl::num_params, nir_function_impl::params, nir_function_impl::return_var, and nir_variable::type.
Referenced by nir_builder_init_simple_shader(), and nir_function_impl_add_variable().
nir_function_impl_create_bare()
nir_function_impl* nir_function_impl_create_bare (nir_shader * shader)
creates a function_impl that isn't tied to any particular function
References nir_function_impl::body, cf_init(), nir_block::cf_node, nir_function_impl::cf_node, nir_function_impl::end_block, nir_function_impl::function, nir_function_impl::locals, nir_block_create(), nir_metadata_none, nir_cf_node::node, nir_function_impl::num_params, nir_function_impl::params, nir_cf_node::parent, nir_block::predecessors, nir_function_impl::reg_alloc, nir_function_impl::registers, nir_function_impl::return_var, nir_function_impl::ssa_alloc, nir_block::successors, and nir_function_impl::valid_metadata.
Referenced by clone_function_impl(), nir_function_impl_add_variable(), and nir_function_impl_create().
nir_global_reg_create()
nir_register* nir_global_reg_create (nir_shader * shader)
creates a register, including assigning it an index and adding it to the list
References nir_register::index, nir_register::is_global, nir_shader::reg_alloc, reg_create(), and nir_shader::registers.
nir_if_create()
nir_if* nir_if_create (nir_shader * shader)
References cf_init(), nir_block::cf_node, nir_if::cf_node, nir_if::condition, nir_if::else_list, nir_block_create(), nir_cf_node::node, nir_cf_node::parent, src_init(), and nir_if::then_list.
Referenced by clone_if(), nir_function_impl_add_variable(), nir_push_if(), and predicate_following().
nir_if_rewrite_condition()
void nir_if_rewrite_condition (nir_if * if_stmt, nir_src new_src)
References nir_if::condition, nir_src::parent_if, src_add_all_uses(), src_is_valid(), and src_remove_all_uses().
Referenced by convert_loop_exit_for_ssa(), copy_prop_src(), nir_ssa_def_rewrite_uses(), nir_ssa_def_rewrite_uses_after(), and rewrite_if_condition().
nir_index_blocks()
void nir_index_blocks (nir_function_impl * impl)
References nir_foreach_block, nir_metadata_block_index, nir_function_impl::num_blocks, and nir_function_impl::valid_metadata.
Referenced by nir_metadata_require(), and print_function_impl().
nir_index_global_regs()
void nir_index_global_regs (nir_shader * shader)
References foreach_list_typed, nir_shader::reg_alloc, and nir_shader::registers.
nir_index_instrs()
unsigned nir_index_instrs (nir_function_impl * impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
References instr, nir_foreach_block, and nir_foreach_instr.
Referenced by nir_move_vec_src_uses_to_dest_impl().
nir_index_local_regs()
void nir_index_local_regs (nir_function_impl * impl)
References foreach_list_typed, nir_function_impl::reg_alloc, and nir_function_impl::registers.
Referenced by inline_function_impl(), and nir_lower_regs_to_ssa_impl().
nir_index_ssa_defs()
void nir_index_ssa_defs (nir_function_impl * impl)
The indices are applied top-to-bottom which has the very nice property that, if A dominates B, then A->index <= B->index.
References index_ssa_def_cb(), instr, nir_foreach_block, nir_foreach_instr, nir_foreach_ssa_def(), and nir_function_impl::ssa_alloc.
Referenced by inline_function_impl(), and nir_loop_analyze_impl().
nir_instr_insert()
void nir_instr_insert (nir_cursor cursor, nir_instr * instr)
Insert a NIR instruction at the given cursor.
Note: This does not update the cursor.
References add_defs_uses(), nir_instr::block, nir_cursor::block, nir_cursor::instr, nir_block::instr_list, nir_block_last_instr(), nir_cursor_after_block, nir_cursor_after_instr, nir_cursor_before_block, nir_cursor_before_instr, nir_handle_add_jump(), nir_instr_type_jump, nir_instr::node, nir_cursor::option, nir_instr::type, and void.
Referenced by add_parallel_copy_to_end_of_block(), emit_copies(), nir_after_cf_list(), nir_builder_instr_insert(), nir_instr_insert_after(), nir_instr_insert_after_block(), nir_instr_insert_after_cf(), nir_instr_insert_after_cf_list(), nir_instr_insert_before(), nir_instr_insert_before_block(), nir_instr_insert_before_cf(), nir_instr_insert_before_cf_list(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_phi_builder_finish(), nir_phi_builder_value_get_block_def(), nir_ssa_undef(), place_phi_read(), predicate_following(), and rewrite_alu_instr().
nir_instr_move_src()
void nir_instr_move_src (nir_instr * dest_instr, nir_src * dest, nir_src * src)
References NIR_SRC_INIT, nir_src::parent_instr, src_add_all_uses(), src_is_valid(), and src_remove_all_uses().
Referenced by lower_sampler(), and nir_tex_instr_remove_src().
nir_instr_remove()
void nir_instr_remove (nir_instr * instr)
References nir_instr::block, nir_handle_remove_jump(), nir_instr_type_jump, nir_instr::node, remove_defs_uses(), nir_instr::type, and nir_jump_instr::type.
Referenced by cleanup_cf_node(), complex_unroll(), constant_fold_alu_instr(), constant_fold_intrinsic_instr(), convert_block(), copy_prop_vars_block(), cse_block(), inline_functions_block(), instr_remove_cursor(), load_from_ssa_entry_value(), loop_prepare_for_unroll(), lower_64bit_pack_impl(), lower_alu_instr_scalar(), lower_copies_to_load_store(), lower_doubles_instr(), lower_indirect_block(), lower_instr(), lower_int64_impl(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_reduction(), lower_returns_in_block(), lower_store_output_to_scalar(), lower_trivial_continues_block(), lower_var_copies_impl(), lower_vec_to_movs_block(), move_cf_list_into_loop_term(), nir_instr_insert_after_cf_list(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_lower_tes_patch_vertices(), nir_lower_to_source_mods_block(), nir_opt_conditional_discard_block(), nir_opt_dce_impl(), nir_opt_peephole_select_block(), nir_replace_instr(), opt_constant_if(), opt_gcm_impl(), opt_undef_store(), remove_dead_var_writes(), remove_dead_writes(), remove_phis_block(), rename_variables(), replace_gradient_with_lod(), resolve_parallel_copy(), resolve_registers_block(), rewrite_emit_vertex(), rewrite_end_primitive(), rewrite_ssa_def(), simple_unroll(), and split_var_copies_block().
nir_instr_rewrite_dest()
void nir_instr_rewrite_dest (nir_instr * instr, nir_dest * dest, nir_dest new_dest)
References nir_reg_dest::def_link, nir_register::defs, nir_ssa_def::if_uses, nir_reg_dest::indirect, instr, nir_dest::is_ssa, nir_dest_copy(), nir_reg_dest::parent_instr, nir_reg_dest::reg, nir_dest::reg, src_add_all_uses(), src_remove_all_uses(), nir_dest::ssa, and nir_ssa_def::uses.
Referenced by lower_vec_to_movs_block(), rewrite_ssa_def(), and try_coalesce().
nir_instr_rewrite_src()
void nir_instr_rewrite_src (nir_instr * instr, nir_src * src, nir_src new_src)
References nir_src::parent_instr, src_add_all_uses(), src_is_valid(), and src_remove_all_uses().
Referenced by calc_sampler_offsets(), constant_fold_deref(), convert_loop_exit_for_ssa(), copy_prop_alu_src(), copy_prop_src(), isolate_phi_nodes_block(), lower_fddy(), lower_interp_var_at_offset(), lower_intrinsic(), lower_offset(), lower_rect(), lower_sampler(), move_vec_src_uses_to_dest_block(), nir_lower_to_source_mods_block(), nir_ssa_def_rewrite_uses(), nir_ssa_def_rewrite_uses_after(), nir_tex_instr_remove_src(), normalize_cubemap_coords_block(), opt_undef_csel(), project_src(), repair_ssa_def(), rewrite_src(), saturate_src(), and try_coalesce().
nir_intrinsic_from_system_value()
nir_intrinsic_op nir_intrinsic_from_system_value (gl_system_value val)
Referenced by convert_block().
nir_intrinsic_instr_create()
nir_intrinsic_instr* nir_intrinsic_instr_create (nir_shader * shader, nir_intrinsic_op op)
References nir_intrinsic_instr::dest, dest_init(), nir_intrinsic_instr::instr, instr, instr_init(), nir_intrinsic_instr::intrinsic, nir_instr_type_intrinsic, nir_intrinsic_infos, nir_intrinsic_info::num_srcs, nir_intrinsic_instr::src, and src_init().
Referenced by append_set_vertex_count(), clone_intrinsic(), emit_copies(), emit_copy_load_store(), emit_load_store(), load_clipdist_input(), load_input(), lower_atomic(), lower_bitmap(), lower_clip_fs(), lower_instr(), lower_interpolate_at(), lower_load(), lower_load_input_to_scalar(), lower_store(), lower_store_output_to_scalar(), nir_copy_deref_var(), nir_copy_var(), nir_function_impl_add_variable(), nir_load_barycentric(), nir_load_deref_var(), nir_load_system_value(), nir_load_var(), nir_opt_conditional_discard_block(), nir_store_deref_var(), nir_store_var(), rewrite_emit_vertex(), rewrite_end_primitive(), split_var_copy_instr(), and store_clipdist_output().
nir_jump_instr_create()
nir_jump_instr* nir_jump_instr_create (nir_shader * shader, nir_jump_type type)
References nir_jump_instr::instr, instr, instr_init(), nir_instr_type_jump, nir_jump_instr::type, and type.
Referenced by clone_jump(), nir_function_impl_add_variable(), nir_jump(), and predicate_following().
nir_load_const_instr_create()
nir_load_const_instr* nir_load_const_instr_create (nir_shader * shader, unsigned num_components, unsigned bit_size)
References nir_load_const_instr::def, nir_load_const_instr::instr, instr, instr_init(), nir_instr_type_load_const, and nir_ssa_def_init().
Referenced by clone_load_const(), constant_fold_alu_instr(), construct_value(), get_deref_reg_src(), lower_instr(), lower_load_const_instr_scalar(), nir_build_imm(), nir_deref_get_const_initializer_load(), and nir_function_impl_add_variable().
nir_local_reg_create()
nir_register* nir_local_reg_create (nir_function_impl * impl)
References nir_register::index, nir_register::is_global, nir_function_impl::reg_alloc, reg_create(), and nir_function_impl::registers.
Referenced by create_reg_for_ssa_def(), get_reg_for_deref(), lower_vec_to_movs_block(), and resolve_parallel_copy().
nir_local_variable_create()
nir_variable* nir_local_variable_create (nir_function_impl * impl, const struct glsl_type * type, const char * name)
creates a local variable and adds it to the list
References nir_variable::data, nir_function_impl::function, nir_variable::nir_variable_data::mode, nir_variable::name, nir_function_impl_add_variable(), nir_var_local, nir_function::shader, nir_variable::type, and type.
Referenced by lower_returns_in_block(), nir_function_impl_add_variable(), and nir_lower_gs_intrinsics().
nir_loop_create()
nir_loop* nir_loop_create (nir_shader * shader)
References nir_loop::body, cf_init(), nir_block::cf_node, nir_loop::cf_node, nir_block_create(), nir_cf_node::node, nir_cf_node::parent, nir_block::predecessors, and nir_block::successors.
Referenced by clone_loop(), nir_function_impl_add_variable(), and nir_push_loop().
nir_parallel_copy_instr_create()
nir_parallel_copy_instr* nir_parallel_copy_instr_create (nir_shader * shader)
References nir_parallel_copy_instr::entries, nir_parallel_copy_instr::instr, instr, instr_init(), and nir_instr_type_parallel_copy.
Referenced by add_parallel_copy_to_end_of_block(), isolate_phi_nodes_block(), and nir_function_impl_add_variable().
nir_phi_instr_create()
nir_phi_instr* nir_phi_instr_create (nir_shader * shader)
References nir_phi_instr::dest, dest_init(), nir_phi_instr::instr, instr, instr_init(), nir_instr_type_phi, and nir_phi_instr::srcs.
Referenced by clone_phi(), convert_loop_exit_for_ssa(), lower_phis_to_scalar_block(), nir_function_impl_add_variable(), nir_if_phi(), and nir_phi_builder_value_get_block_def().
nir_reg_remove()
void nir_reg_remove (nir_register * reg)
References nir_register::node.
Referenced by global_to_local().
nir_shader_add_variable()
void nir_shader_add_variable (nir_shader * shader, nir_variable * var)
Adds a variable to the appropriate list in nir_shader.
References nir_variable::data, nir_shader::globals, nir_shader::inputs, nir_variable::nir_variable_data::mode, nir_var_all, nir_var_global, nir_var_local, nir_var_param, nir_var_shader_in, nir_var_shader_out, nir_var_shader_storage, nir_var_shared, nir_var_system_value, nir_var_uniform, nir_variable::node, nir_shader::outputs, nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
Referenced by nir_variable_create().
nir_shader_create()
nir_shader* nir_shader_create (void * mem_ctx, gl_shader_stage stage, const nir_shader_compiler_options * options, shader_info * si)
References nir_shader::functions, nir_shader::globals, nir_shader::info, nir_shader::inputs, nir_shader::num_inputs, nir_shader::num_outputs, nir_shader::num_shared, nir_shader::num_uniforms, nir_shader::options, nir_shader::outputs, nir_shader::reg_alloc, nir_shader::registers, nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
Referenced by nir_builder_init_simple_shader(), and nir_shader_clone().
nir_src_as_const_value()
nir_const_value* nir_src_as_const_value (nir_src src)
References nir_src::is_ssa, nir_instr_type_load_const, nir_ssa_def::parent_instr, nir_src::ssa, nir_instr::type, and nir_load_const_instr::value.
Referenced by constant_fold_intrinsic_instr(), dead_cf_block(), find_output_in_block(), is_neg_power_of_two(), is_pos_power_of_two(), is_zero_to_one(), nir_gs_count_vertices(), nir_lower_two_sided_color_block(), and opt_peel_loop_initial_if().
nir_src_copy()
void nir_src_copy (nir_src * dest, const nir_src * src, void * mem_ctx)
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, nir_src_copy(), nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by deref_array_clone(), emit_copy(), get_deref_reg_src(), lower_atomic(), lower_instr(), lower_interpolate_at(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_store(), nir_alu_src_copy(), nir_dest_bit_size(), nir_dest_copy(), nir_opt_conditional_discard_block(), nir_opt_peephole_select_block(), nir_src_copy(), replace_gradient_with_lod(), and sample_plane().
nir_src_is_dynamically_uniform()
bool nir_src_is_dynamically_uniform (nir_src src)
Returns true if the source is known to be dynamically uniform.
Otherwise it returns false which means it may or may not be dynamically uniform but it can't be determined.
References nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_instr_type_intrinsic, nir_instr_type_load_const, nir_ssa_def::parent_instr, nir_src::ssa, and nir_instr::type.
nir_ssa_def_components_read()
uint8_t nir_ssa_def_components_read (nir_ssa_def * def)
References exec_node_data, nir_alu_instr_channel_used(), nir_foreach_use, nir_instr_type_alu, nir_op_infos, nir_ssa_def::num_components, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_instr::src, and nir_alu_src::swizzle.
Referenced by copy_prop_vars_block(), and load_from_ssa_entry_value().
nir_ssa_def_init()
void nir_ssa_def_init (nir_instr * instr, nir_ssa_def * def, unsigned num_components, unsigned bit_size, const char * name)
References nir_ssa_def::bit_size, nir_instr::block, nir_block::cf_node, nir_ssa_def::if_uses, nir_ssa_def::index, instr, nir_ssa_def::name, nir_cf_node_get_function(), nir_ssa_def::num_components, nir_ssa_def::parent_instr, nir_function_impl::ssa_alloc, and nir_ssa_def::uses.
Referenced by nir_load_const_instr_create(), nir_ssa_dest_init(), and nir_ssa_undef_instr_create().
nir_ssa_def_rewrite_uses()
void nir_ssa_def_rewrite_uses (nir_ssa_def * def, nir_src new_src)
References nir_src::is_ssa, nir_foreach_if_use_safe, nir_foreach_use_safe, nir_if_rewrite_condition(), nir_instr_rewrite_src(), and nir_src::ssa.
Referenced by constant_fold_alu_instr(), convert_block(), convert_instr(), convert_yuv_to_rgb(), copy_prop_vars_block(), dest_replace_ssa_with_reg(), emit_wpos_adjustment(), isolate_phi_nodes_block(), lower_64bit_pack_impl(), lower_alu_instr_scalar(), lower_color(), lower_doubles_instr(), lower_indirect_block(), lower_instr(), lower_int64_impl(), lower_load_const_instr_scalar(), lower_load_input_to_scalar(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), lower_reduction(), lower_texcoord(), lower_vec_to_movs_block(), nir_instr_set_add_or_rewrite(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_lower_ssa_defs_to_regs_block(), nir_lower_tes_patch_vertices(), nir_lower_two_sided_color_block(), nir_opt_peephole_select_block(), nir_replace_instr(), opt_constant_if(), opt_undef_vecN(), remove_phis_block(), rename_variables(), replace_gradient_with_lod(), replace_ssa_def_uses(), and rewrite_ssa_def().
nir_ssa_def_rewrite_uses_after()
void nir_ssa_def_rewrite_uses_after (nir_ssa_def * def, nir_src new_src, nir_instr * after_me)
References is_instr_between(), nir_src::is_ssa, nir_foreach_if_use_safe, nir_foreach_use_safe, nir_if_rewrite_condition(), nir_instr_rewrite_src(), nir_ssa_def::parent_instr, and nir_src::ssa.
Referenced by copy_prop_vars_block(), linearize_srgb_result(), lower_load_sample_pos(), swizzle_result(), and update_fragcoord().
nir_ssa_def_visitor()
static bool nir_ssa_def_visitor (nir_dest * dest, void * void_state) inline static
References foreach_ssa_def_state::cb, foreach_ssa_def_state::client_state, nir_dest::is_ssa, and nir_dest::ssa.
Referenced by nir_foreach_ssa_def().
nir_ssa_dest_init()
void nir_ssa_dest_init (nir_instr * instr, nir_dest * dest, unsigned num_components, unsigned bit_size, const char * name)
References nir_dest::is_ssa, nir_ssa_def_init(), and nir_dest::ssa.
Referenced by __clone_dst(), construct_value(), convert_loop_exit_for_ssa(), emit_copy_load_store(), emit_load_store(), get_deref_reg_src(), get_texture_size(), isolate_phi_nodes_block(), load_clipdist_input(), load_input(), lower_bitmap(), lower_color(), lower_instr(), lower_interpolate_at(), lower_load_input_to_scalar(), lower_locals_to_regs_block(), lower_phis_to_scalar_block(), nir_alu_ssa_dest_init(), nir_build_alu(), nir_fmov_alu(), nir_if_phi(), nir_imov_alu(), nir_load_barycentric(), nir_load_deref_var(), nir_load_system_value(), nir_load_var(), nir_lower_io_block(), nir_lower_phis_to_regs_block(), nir_opt_peephole_select_block(), nir_phi_builder_value_get_block_def(), nir_replace_instr(), rename_variables(), replace_gradient_with_lod(), rewrite_alu_instr(), rewrite_dest(), and sample_plane().
nir_ssa_undef_instr_create()
nir_ssa_undef_instr* nir_ssa_undef_instr_create (nir_shader * shader, unsigned num_components, unsigned bit_size)
References nir_ssa_undef_instr::def, nir_ssa_undef_instr::instr, instr, instr_init(), nir_instr_type_ssa_undef, and nir_ssa_def_init().
Referenced by clone_ssa_undef(), insert_phi_undef(), nir_function_impl_add_variable(), nir_phi_builder_value_get_block_def(), nir_ssa_undef(), rename_variables(), and replace_ssa_def_uses().
nir_system_value_from_intrinsic()
gl_system_value nir_system_value_from_intrinsic (nir_intrinsic_op intrin)
Referenced by gather_intrinsic_info().
nir_tex_instr_create()
nir_tex_instr* nir_tex_instr_create (nir_shader * shader, unsigned num_srcs)
References nir_tex_instr::dest, dest_init(), nir_tex_instr::instr, instr, instr_init(), nir_instr_type_tex, nir_tex_instr::num_srcs, nir_tex_instr::sampler, nir_tex_instr::sampler_index, nir_tex_src::src, nir_tex_instr::src, src_init(), nir_tex_instr::texture, nir_tex_instr::texture_array_size, and nir_tex_instr::texture_index.
Referenced by clone_tex(), get_texture_size(), lower_bitmap(), lower_color(), nir_function_impl_add_variable(), replace_gradient_with_lod(), and sample_plane().
nir_tex_instr_remove_src()
void nir_tex_instr_remove_src (nir_tex_instr * tex, unsigned src_idx)
References nir_tex_instr::instr, nir_instr_move_src(), nir_instr_rewrite_src(), NIR_SRC_INIT, nir_tex_instr::num_srcs, nir_tex_src::src, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by lower_offset(), nir_tex_instr_src_index(), and project_src().
nir_variable_create()
nir_variable* nir_variable_create (nir_shader * shader, nir_variable_mode mode, const struct glsl_type * type, const char * name)
creates a variable, sets a few defaults, and adds it to the list
References nir_variable::data, nir_variable::nir_variable_data::interpolation, nir_variable::nir_variable_data::mode, nir_variable::name, nir_shader_add_variable(), nir_var_shader_in, nir_var_shader_out, nir_var_uniform, nir_variable::nir_variable_data::read_only, nir_shader::stage, nir_variable::type, and type.
Referenced by create_uniform(), get_new_var(), get_texcoord(), get_transform(), lower_impl(), and nir_function_impl_add_variable().
reduce_cursor()
static nir_cursor reduce_cursor (nir_cursor cursor) static
References nir_instr::block, nir_cursor::block, nir_block::cf_node, nir_cursor::instr, nir_block::instr_list, nir_cf_node_prev(), nir_cursor_after_block, nir_cursor_after_instr, nir_cursor_before_block, nir_cursor_before_instr, nir_instr_next(), nir_instr_prev(), nir_cursor::option, and nir_cf_node::type.
Referenced by nir_cursors_equal().
reg_create()
static nir_register* reg_create (void * mem_ctx, struct exec_list * list) static
References nir_register::bit_size, nir_register::defs, nir_register::if_uses, nir_register::is_packed, nir_register::name, nir_register::node, nir_register::num_array_elems, nir_register::num_components, and nir_register::uses.
Referenced by nir_global_reg_create(), and nir_local_reg_create().
remove_def_cb()
static bool remove_def_cb (nir_dest * dest, void * state) static
References nir_reg_dest::def_link, nir_dest::is_ssa, nir_dest::reg, and void.
Referenced by remove_defs_uses().
remove_defs_uses()
static void remove_defs_uses (nir_instr * instr) static
References nir_foreach_dest(), nir_foreach_src(), remove_def_cb(), and remove_use_cb().
Referenced by nir_instr_remove().
remove_use_cb()
static bool remove_use_cb (nir_src * src, void * state) static
References src_is_valid(), nir_src::use_link, and void.
Referenced by remove_defs_uses().
src_add_all_uses()
static void src_add_all_uses (nir_src * src, nir_instr * parent_instr, nir_if * parent_if) static
References nir_register::if_uses, nir_ssa_def::if_uses, nir_reg_src::indirect, nir_src::is_ssa, nir_src::parent_if, nir_src::parent_instr, nir_reg_src::reg, nir_src::reg, src_is_valid(), nir_src::ssa, nir_src::use_link, nir_register::uses, and nir_ssa_def::uses.
Referenced by nir_if_rewrite_condition(), nir_instr_move_src(), nir_instr_rewrite_dest(), and nir_instr_rewrite_src().
src_init()
static void src_init (nir_src * src) inline static
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, nir_reg_src::reg, and nir_src::reg.
Referenced by alu_src_init(), nir_deref_array_create(), nir_if_create(), nir_intrinsic_instr_create(), and nir_tex_instr_create().
src_is_valid()
static bool src_is_valid (const nir_src * src) static
References nir_src::is_ssa, nir_reg_src::reg, nir_src::reg, and nir_src::ssa.
Referenced by nir_if_rewrite_condition(), nir_instr_move_src(), nir_instr_rewrite_src(), remove_use_cb(), src_add_all_uses(), and src_remove_all_uses().
src_remove_all_uses()
static void src_remove_all_uses (nir_src * src) static
References nir_reg_src::indirect, nir_src::is_ssa, nir_src::reg, src_is_valid(), and nir_src::use_link.
Referenced by nir_if_rewrite_condition(), nir_instr_move_src(), nir_instr_rewrite_dest(), and nir_instr_rewrite_src().
visit_alu_dest()
static bool visit_alu_dest (nir_alu_instr * instr, nir_foreach_dest_cb cb, void * state) static
References nir_alu_dest::dest, and nir_alu_instr::dest.
Referenced by nir_foreach_dest().
visit_alu_src()
static bool visit_alu_src (nir_alu_instr * instr, nir_foreach_src_cb cb, void * state) static
References nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_src::src, nir_alu_instr::src, and visit_src().
Referenced by nir_foreach_src().
visit_deref_array_src()
static bool visit_deref_array_src (nir_deref_array * deref, nir_foreach_src_cb cb, void * state) static
References nir_deref_array::deref_array_type, nir_deref_array::indirect, nir_deref_array_type_indirect, and visit_src().
Referenced by visit_deref_src().
visit_deref_src()
static bool visit_deref_src (nir_deref_var * deref, nir_foreach_src_cb cb, void * state) static
References nir_deref::child, nir_deref_var::deref, nir_deref::deref_type, nir_deref_type_array, and visit_deref_array_src().
Referenced by visit_intrinsic_src(), and visit_tex_src().
visit_dest_indirect()
static bool visit_dest_indirect (nir_dest * dest, void * _state) static
References visit_dest_indirect_state::cb, nir_reg_dest::indirect, nir_dest::is_ssa, nir_dest::reg, and visit_dest_indirect_state::state.
Referenced by nir_foreach_src().
visit_intrinsic_dest()
static bool visit_intrinsic_dest (nir_intrinsic_instr * instr, nir_foreach_dest_cb cb, void * state) static
References nir_intrinsic_instr::dest, nir_intrinsic_info::has_dest, nir_intrinsic_instr::intrinsic, and nir_intrinsic_infos.
Referenced by nir_foreach_dest().
visit_intrinsic_src()
static bool visit_intrinsic_src (nir_intrinsic_instr * instr, nir_foreach_src_cb cb, void * state) static
References nir_intrinsic_instr::intrinsic, nir_intrinsic_infos, nir_intrinsic_info::num_srcs, nir_intrinsic_info::num_variables, nir_intrinsic_instr::src, nir_intrinsic_instr::variables, visit_deref_src(), and visit_src().
Referenced by nir_foreach_src().
visit_parallel_copy_dest()
static bool visit_parallel_copy_dest (nir_parallel_copy_instr * instr, nir_foreach_dest_cb cb, void * state) static
References nir_foreach_parallel_copy_entry.
Referenced by nir_foreach_dest().
visit_parallel_copy_src()
static bool visit_parallel_copy_src (nir_parallel_copy_instr * instr, nir_foreach_src_cb cb, void * state) static
References nir_foreach_parallel_copy_entry, and visit_src().
Referenced by nir_foreach_src().
visit_phi_dest()
static bool visit_phi_dest (nir_phi_instr * instr, nir_foreach_dest_cb cb, void * state) static
References nir_phi_instr::dest.
Referenced by nir_foreach_dest().
visit_phi_src()
static bool visit_phi_src (nir_phi_instr * instr, nir_foreach_src_cb cb, void * state) static
References nir_foreach_phi_src, and visit_src().
Referenced by nir_foreach_src().
visit_src()
static bool visit_src (nir_src * src, nir_foreach_src_cb cb, void * state) static
References foreach_ssa_def_state::cb, nir_reg_src::indirect, nir_src::is_ssa, and nir_src::reg.
Referenced by visit_alu_src(), visit_deref_array_src(), visit_intrinsic_src(), visit_parallel_copy_src(), visit_phi_src(), and visit_tex_src().
visit_tex_src()
static bool visit_tex_src (nir_tex_instr * instr, nir_foreach_src_cb cb, void * state) static
References nir_tex_instr::num_srcs, nir_tex_instr::sampler, nir_tex_src::src, nir_tex_instr::src, nir_tex_instr::texture, visit_deref_src(), and visit_src().
Referenced by nir_foreach_src().
visit_texture_dest()
static bool visit_texture_dest (nir_tex_instr * instr, nir_foreach_dest_cb cb, void * state) static
References nir_tex_instr::dest.
Referenced by nir_foreach_dest().