Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_metadata.c File Reference
#include "nir.h"
Macros
#define NEEDS_UPDATE(X) ((required & ~impl->valid_metadata) & (X))
Functions
void nir_metadata_require (nir_function_impl *impl, nir_metadata required,...)
requests that the given pieces of metadata be generated
void nir_metadata_preserve (nir_function_impl *impl, nir_metadata preserved)
dirties all but the preserved metadata
Macro Definition Documentation
NEEDS_UPDATE
#define NEEDS_UPDATE (X) ((required & ~impl->valid_metadata) & (X))
Referenced by nir_metadata_require().
Function Documentation
nir_metadata_preserve()
void nir_metadata_preserve (nir_function_impl * impl, nir_metadata preserved)
dirties all but the preserved metadata
References nir_foreach_function, nir_metadata_check_validation_flag(), nir_metadata_not_properly_reset, nir_metadata_set_validation_flag(), and nir_function_impl::valid_metadata.
Referenced by combine_clip_cull(), convert_impl(), inline_function_impl(), lower_64bit_pack_impl(), lower_bitmap_impl(), lower_clip_fs(), lower_clip_vs(), lower_drawpixels_impl(), lower_impl(), lower_indirects_impl(), lower_io_types_impl(), lower_phis_to_scalar_impl(), lower_var_copies_impl(), lower_wpos_ytransform_impl(), nir_cf_extract(), nir_convert_from_ssa_impl(), nir_copy_prop_impl(), nir_function_impl_add_variable(), nir_handle_add_jump(), nir_handle_remove_jump(), nir_lower_alu_to_scalar_impl(), nir_lower_atomics(), nir_lower_constant_initializers(), nir_lower_doubles_impl(), nir_lower_global_vars_to_local(), nir_lower_gs_intrinsics(), nir_lower_io_impl(), nir_lower_io_to_temporaries(), nir_lower_load_const_to_scalar_impl(), nir_lower_locals_to_regs_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_returns_impl(), nir_lower_tes_patch_vertices(), nir_lower_tex_impl(), nir_lower_to_source_mods_impl(), nir_lower_two_sided_color_impl(), nir_lower_vars_to_ssa_impl(), nir_lower_vec_to_movs_impl(), nir_lower_wpos_center(), nir_move_vec_src_uses_to_dest_impl(), nir_opt_constant_folding_impl(), nir_opt_copy_prop_vars(), nir_opt_cse_impl(), nir_opt_dce_impl(), nir_opt_if(), nir_opt_move_comparisons(), nir_opt_peephole_select_impl(), nir_opt_trivial_continues(), nir_opt_undef(), nir_remove_dead_variables(), nir_repair_ssa_impl(), normalize_cubemap_coords_impl(), opt_dead_cf_impl(), opt_gcm_impl(), propagate_invariant_impl(), remove_phis_impl(), split_var_copies_impl(), and sweep_impl().
nir_metadata_require()
void nir_metadata_require (nir_function_impl * impl, nir_metadata required, ...)
requests that the given pieces of metadata be generated
References NEEDS_UPDATE, nir_calc_dominance_impl(), nir_index_blocks(), nir_live_ssa_defs_impl(), nir_loop_analyze_impl(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_loop_analysis, and nir_function_impl::valid_metadata.
Referenced by loop_is_dead(), nir_calc_dominance_impl(), nir_convert_from_ssa_impl(), nir_convert_loop_to_lcssa(), nir_function_impl_add_variable(), nir_lower_locals_to_regs_impl(), nir_lower_regs_to_ssa_impl(), nir_lower_vars_to_ssa_impl(), nir_move_vec_src_uses_to_dest_impl(), nir_opt_cse_impl(), nir_opt_loop_unroll_impl(), nir_repair_ssa_impl(), and opt_gcm_impl().