Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_normalize_cubemap_coords.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static bool normalize_cubemap_coords_block (nir_block *block, nir_builder *b)
This file implements a NIR lowering pass to perform the normalization of the cubemap coordinates to have the largest magnitude component be -1.0 or 1.0.
static bool normalize_cubemap_coords_impl (nir_function_impl *impl)
bool nir_normalize_cubemap_coords (nir_shader *shader)
Function Documentation
nir_normalize_cubemap_coords()
bool nir_normalize_cubemap_coords (nir_shader * shader)
References nir_foreach_function, and normalize_cubemap_coords_impl().
normalize_cubemap_coords_block()
static bool normalize_cubemap_coords_block (nir_block * block, nir_builder * b) static
This file implements a NIR lowering pass to perform the normalization of the cubemap coordinates to have the largest magnitude component be -1.0 or 1.0.
This is based on the old GLSL IR based pass by Eric.
References abs(), nir_tex_instr::coord_components, nir_builder::cursor, nir_tex_instr::instr, instr, nir_before_instr(), nir_channel(), nir_foreach_instr, nir_instr_rewrite_src(), nir_instr_type_tex, nir_src_for_ssa(), nir_ssa_for_src(), nir_tex_instr_src_size(), nir_tex_src_coord, nir_ssa_def::num_components, nir_tex_instr::num_srcs, nir_tex_instr::sampler_dim, nir_tex_src::src, nir_tex_instr::src, and nir_tex_src::src_type.
Referenced by normalize_cubemap_coords_impl().
normalize_cubemap_coords_impl()
static bool normalize_cubemap_coords_impl (nir_function_impl * impl) static
References nir_builder_init(), nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and normalize_cubemap_coords_block().
Referenced by nir_normalize_cubemap_coords().