Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_search.c File Reference
#include <inttypes.h>
#include "nir_search.h"
Data Structures
struct match_state
struct bitsize_tree
Typedefs
typedef struct bitsize_tree bitsize_tree
Functions
static bool match_expression (const nir_search_expression *expr, nir_alu_instr *instr, unsigned num_components, const uint8_t *swizzle, struct match_state *state)
static bool src_is_type (nir_src src, nir_alu_type type)
Check if a source produces a value of the given type.
static bool match_value (const nir_search_value *value, nir_alu_instr *instr, unsigned src, unsigned num_components, const uint8_t *swizzle, struct match_state *state)
static bitsize_tree * build_bitsize_tree (void *mem_ctx, struct match_state *state, const nir_search_value *value)
static unsigned bitsize_tree_filter_up (bitsize_tree *tree)
static void bitsize_tree_filter_down (bitsize_tree *tree, unsigned size)
static nir_alu_src construct_value (const nir_search_value *value, unsigned num_components, bitsize_tree *bitsize, struct match_state *state, nir_instr *instr, void *mem_ctx)
nir_alu_instr * nir_replace_instr (nir_alu_instr *instr, const nir_search_expression *search, const nir_search_value *replace, void *mem_ctx)
Variables
static const uint8_t identity_swizzle [] = { 0, 1, 2, 3 }
Typedef Documentation
bitsize_tree
typedef struct bitsize_tree bitsize_tree
Function Documentation
bitsize_tree_filter_down()
static void bitsize_tree_filter_down (bitsize_tree * tree, unsigned size) static
References bitsize_tree::common_size, bitsize_tree::dest_size, bitsize_tree::is_dest_sized, bitsize_tree::num_srcs, bitsize_tree::src_size, and bitsize_tree::srcs.
Referenced by nir_replace_instr().
bitsize_tree_filter_up()
static unsigned bitsize_tree_filter_up (bitsize_tree * tree) static
References bitsize_tree::common_size, bitsize_tree::dest_size, bitsize_tree::is_dest_sized, bitsize_tree::is_src_sized, bitsize_tree::num_srcs, bitsize_tree::src_size, and bitsize_tree::srcs.
Referenced by nir_replace_instr().
build_bitsize_tree()
static bitsize_tree* build_bitsize_tree (void * mem_ctx, struct match_state * state, const nir_search_value * value) static
References nir_search_value::bit_size, bitsize_tree::common_size, bitsize_tree::dest_size, expr(), nir_op_info::input_types, bitsize_tree::is_dest_sized, bitsize_tree::is_src_sized, nir_alu_type_get_type_size(), nir_op_infos, nir_search_value_constant, nir_search_value_expression, nir_search_value_variable, nir_src_bit_size(), nir_op_info::num_inputs, bitsize_tree::num_srcs, nir_search_expression::opcode, nir_op_info::output_type, nir_alu_src::src, bitsize_tree::src_size, nir_search_expression::srcs, bitsize_tree::srcs, nir_search_value::type, nir_search_variable::variable, and match_state::variables.
Referenced by nir_replace_instr().
construct_value()
static nir_alu_src construct_value (const nir_search_value * value, unsigned num_components, bitsize_tree * bitsize, struct match_state * state, nir_instr * instr, void * mem_ctx) static
References nir_alu_src::abs, nir_search_constant::d, nir_search_constant::data, nir_load_const_instr::def, nir_alu_dest::dest, nir_alu_instr::dest, bitsize_tree::dest_size, nir_alu_instr::exact, expr(), nir_const_value::f32, nir_const_value::f64, match_state::has_exact_alu, nir_search_constant::i, nir_const_value::i32, nir_const_value::i64, identity_swizzle, nir_op_info::input_sizes, nir_alu_instr::instr, nir_load_const_instr::instr, nir_search_variable::is_constant, nir_ssa_def::name, nir_alu_src::negate, nir_alu_instr_create(), nir_alu_src_copy(), nir_instr_insert_before(), nir_load_const_instr_create(), nir_op_infos, nir_search_value_constant, nir_search_value_expression, nir_search_value_variable, nir_src_for_ssa(), NIR_SRC_INIT, nir_ssa_dest_init(), nir_type_bool32, nir_type_float, nir_type_int, nir_type_uint, nir_op_info::num_inputs, nir_alu_instr::op, nir_search_expression::opcode, nir_op_info::output_size, nir_alu_dest::saturate, nir_alu_src::src, nir_alu_instr::src, nir_search_expression::srcs, bitsize_tree::srcs, nir_dest::ssa, nir_alu_src::swizzle, nir_search_value::type, nir_search_constant::type, nir_search_constant::u, nir_const_value::u32, nir_const_value::u64, nir_load_const_instr::value, nir_search_variable::variable, match_state::variables, match_state::variables_seen, and nir_alu_dest::write_mask.
Referenced by nir_replace_instr().
match_expression()
static bool match_expression (const nir_search_expression * expr, nir_alu_instr * instr, unsigned num_components, const uint8_t * swizzle, struct match_state * state) static
References nir_op_info::algebraic_properties, nir_search_value::bit_size, nir_ssa_def::bit_size, nir_search_expression::cond, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::exact, match_state::has_exact_alu, nir_search_expression::inexact, match_state::inexact_match, nir_dest::is_ssa, match_value(), nir_op_infos, NIR_OP_IS_COMMUTATIVE, nir_op_info::num_inputs, nir_alu_instr::op, nir_search_expression::opcode, nir_op_info::output_size, nir_alu_dest::saturate, nir_search_expression::srcs, nir_dest::ssa, nir_search_expression::value, and match_state::variables_seen.
Referenced by match_value(), and nir_replace_instr().
match_value()
static bool match_value (const nir_search_value * value, nir_alu_instr * instr, unsigned src, unsigned num_components, const uint8_t * swizzle, struct match_state * state) static
References nir_alu_src::abs, nir_search_value::bit_size, nir_ssa_def::bit_size, nir_search_variable::cond, nir_search_constant::d, nir_search_constant::data, nir_load_const_instr::def, nir_const_value::f32, nir_const_value::f64, identity_swizzle, if(), nir_op_info::input_sizes, nir_search_variable::is_constant, nir_src::is_ssa, match_expression(), nir_alu_src::negate, nir_instr_type_alu, nir_instr_type_load_const, nir_op_infos, NIR_SEARCH_MAX_VARIABLES, nir_search_value_constant, nir_search_value_expression, nir_search_value_variable, nir_src_bit_size(), nir_type_bool32, nir_type_float, nir_type_int, nir_type_invalid, nir_type_uint, nir_alu_instr::op, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, src_is_type(), nir_src::ssa, nir_alu_src::swizzle, nir_search_value::type, nir_search_variable::type, nir_search_constant::type, nir_instr::type, nir_search_constant::u, nir_const_value::u32, nir_const_value::u64, nir_load_const_instr::value, nir_search_variable::variable, match_state::variables, and match_state::variables_seen.
Referenced by match_expression().
nir_replace_instr()
nir_alu_instr* nir_replace_instr (nir_alu_instr * instr, const nir_search_expression * search, const nir_search_value * replace, void * mem_ctx)
References nir_ssa_def::bit_size, bitsize_tree_filter_down(), bitsize_tree_filter_up(), build_bitsize_tree(), construct_value(), nir_alu_dest::dest, nir_alu_instr::dest, match_state::has_exact_alu, match_state::inexact_match, nir_alu_instr::instr, nir_dest::is_ssa, match_expression(), nir_alu_instr_create(), nir_instr_insert_before(), nir_instr_remove(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_ssa_def::num_components, nir_alu_instr::src, nir_dest::ssa, swizzle(), match_state::variables_seen, and nir_alu_dest::write_mask.
src_is_type()
static bool src_is_type (nir_src src, nir_alu_type type) static
Check if a source produces a value of the given type.
Used for satisfying 'a' constraints.
References nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_alu_type_get_base_type(), nir_instr_type_alu, nir_instr_type_intrinsic, nir_op_infos, nir_type_bool, nir_type_invalid, nir_alu_instr::op, nir_op_info::output_type, nir_ssa_def::parent_instr, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_instr::type, and type.
Referenced by match_value().
Variable Documentation
identity_swizzle
const uint8_t identity_swizzle[] = { 0, 1, 2, 3 } static
Referenced by construct_value(), and match_value().