Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_phis_to_scalar.c File Reference
#include "nir.h"
Data Structures
struct lower_phis_to_scalar_state
Functions
static bool should_lower_phi (nir_phi_instr *phi, struct lower_phis_to_scalar_state *state)
Determines if the given phi node should be lowered.
static bool is_phi_src_scalarizable (nir_phi_src *src, struct lower_phis_to_scalar_state *state)
static bool lower_phis_to_scalar_block (nir_block *block, struct lower_phis_to_scalar_state *state)
static bool lower_phis_to_scalar_impl (nir_function_impl *impl)
bool nir_lower_phis_to_scalar (nir_shader *shader)
A pass that lowers vector phi nodes to scalar.
Function Documentation
is_phi_src_scalarizable()
static bool is_phi_src_scalarizable (nir_phi_src * src, struct lower_phis_to_scalar_state * state) static
References nir_variable::data, nir_intrinsic_instr::intrinsic, nir_src::is_ssa, nir_variable::nir_variable_data::mode, nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_load_const, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_op_infos, nir_var_shader_in, nir_var_uniform, nir_alu_instr::op, nir_op_info::output_size, nir_ssa_def::parent_instr, should_lower_phi(), nir_phi_src::src, nir_src::ssa, nir_instr::type, nir_deref_var::var, and nir_intrinsic_instr::variables.
Referenced by should_lower_phi().
lower_phis_to_scalar_block()
static bool lower_phis_to_scalar_block (nir_block * block, struct lower_phis_to_scalar_state * state) static
References nir_ssa_def::bit_size, lower_phis_to_scalar_state::dead_ctx, nir_alu_dest::dest, nir_alu_instr::dest, nir_phi_instr::dest, nir_alu_instr::instr, nir_phi_instr::instr, instr, lower_phis_to_scalar_state::mem_ctx, nir_alu_instr_create(), nir_block_last_instr(), nir_foreach_instr, nir_foreach_instr_safe, nir_foreach_phi_src, nir_instr_insert_after(), nir_instr_insert_after_block(), nir_instr_insert_before(), nir_instr_remove(), nir_instr_type_jump, nir_instr_type_phi, nir_phi_instr_create(), nir_src_copy(), nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), nir_ssa_dest_init(), nir_phi_src::node, nir_ssa_def::num_components, nir_phi_src::pred, should_lower_phi(), nir_alu_src::src, nir_alu_instr::src, nir_phi_src::src, nir_phi_instr::srcs, nir_dest::ssa, nir_alu_src::swizzle, nir_instr::type, and nir_alu_dest::write_mask.
Referenced by lower_phis_to_scalar_impl().
lower_phis_to_scalar_impl()
static bool lower_phis_to_scalar_impl (nir_function_impl * impl) static
References lower_phis_to_scalar_state::dead_ctx, lower_phis_to_scalar_block(), lower_phis_to_scalar_state::mem_ctx, nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and lower_phis_to_scalar_state::phi_table.
Referenced by nir_lower_phis_to_scalar().
nir_lower_phis_to_scalar()
bool nir_lower_phis_to_scalar (nir_shader * shader)
A pass that lowers vector phi nodes to scalar.
This pass loops through the blocks and lowers looks for vector phi nodes it can lower to scalar phi nodes. Not all phi nodes are lowered. For instance, if one of the sources is a non-scalarizable vector, then we don't bother lowering because that would generate hard-to-coalesce movs.
References lower_phis_to_scalar_impl(), and nir_foreach_function.
should_lower_phi()
static bool should_lower_phi (nir_phi_instr * phi, struct lower_phis_to_scalar_state * state) static
Determines if the given phi node should be lowered.
The only phi nodes we will scalarize at the moment are those where all of the sources are scalarizable.
The reason for this comes down to coalescing. Since phi sources can't swizzle, swizzles on phis have to be resolved by inserting a mov right before the phi. The choice then becomes between movs to pick off components for a scalar phi or potentially movs to recombine components for a vector phi. The problem is that the movs generated to pick off the components are almost uncoalescable. We can't coalesce them in NIR because we need them to pick off components and we can't coalesce them in the backend because the source register is a vector and the destination is a scalar that may be used at other places in the program. On the other hand, if we have a bunch of scalars going into a vector phi, the situation is much better. In this case, if the SSA def is generated in the predecessor block to the corresponding phi source, the backend code will be an ALU op into a temporary and then a mov into the given vector component; this move can almost certainly be coalesced away.
References nir_phi_instr::dest, is_phi_src_scalarizable(), nir_foreach_phi_src, nir_ssa_def::num_components, lower_phis_to_scalar_state::phi_table, and nir_dest::ssa.
Referenced by is_phi_src_scalarizable(), and lower_phis_to_scalar_block().