Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_phi_builder.c File Reference
#include "nir_phi_builder.h"
#include "nir/nir_vla.h"
Data Structures
struct nir_phi_builder
struct nir_phi_builder_value
Macros
#define NEEDS_PHI ((nir_ssa_def *)(intptr_t)-1)
Functions
struct nir_phi_builder * nir_phi_builder_create (nir_function_impl *impl)
struct nir_phi_builder_value * nir_phi_builder_add_value (struct nir_phi_builder *pb, unsigned num_components, unsigned bit_size, const BITSET_WORD *defs)
void nir_phi_builder_value_set_block_def (struct nir_phi_builder_value *val, nir_block *block, nir_ssa_def *def)
nir_ssa_def * nir_phi_builder_value_get_block_def (struct nir_phi_builder_value *val, nir_block *block)
static int compare_blocks (const void *_a, const void *_b)
void nir_phi_builder_finish (struct nir_phi_builder *pb)
Macro Definition Documentation
NEEDS_PHI
#define NEEDS_PHI ((nir_ssa_def *)(intptr_t)-1)
Referenced by nir_phi_builder_add_value(), and nir_phi_builder_value_get_block_def().
Function Documentation
compare_blocks()
static int compare_blocks (const void * _a, const void * _b) static
References nir_block::index.
Referenced by nir_phi_builder_finish().
nir_phi_builder_add_value()
struct nir_phi_builder_value* nir_phi_builder_add_value (struct nir_phi_builder * pb, unsigned num_components, unsigned bit_size, const BITSET_WORD * defs)
References nir_phi_builder_value::bit_size, nir_phi_builder::blocks, nir_phi_builder_value::builder, nir_phi_builder_value::defs, nir_block::dom_frontier, nir_function_impl::end_block, if(), nir_phi_builder::impl, nir_block::index, nir_phi_builder::iter_count, NEEDS_PHI, nir_phi_builder_value::node, nir_phi_builder::num_blocks, nir_phi_builder_value::num_components, nir_phi_builder_value::phis, nir_phi_builder::values, nir_phi_builder::W, and nir_phi_builder::work.
Referenced by nir_lower_regs_to_ssa_impl(), nir_lower_vars_to_ssa_impl(), and repair_ssa_def().
nir_phi_builder_create()
struct nir_phi_builder* nir_phi_builder_create (nir_function_impl * impl)
References nir_phi_builder::blocks, nir_function_impl::function, nir_phi_builder::impl, nir_phi_builder::iter_count, nir_foreach_block, nir_metadata_block_index, nir_metadata_dominance, nir_phi_builder::num_blocks, nir_function_impl::num_blocks, nir_phi_builder::shader, nir_function::shader, nir_function_impl::valid_metadata, nir_phi_builder::values, nir_phi_builder::W, and nir_phi_builder::work.
Referenced by nir_lower_regs_to_ssa_impl(), nir_lower_vars_to_ssa_impl(), and prep_build_phi().
nir_phi_builder_finish()
void nir_phi_builder_finish (struct nir_phi_builder * pb)
References nir_instr::block, compare_blocks(), exec_node_data, foreach_list_typed, nir_phi_instr::instr, instr, nir_before_block(), nir_instr_insert(), nir_instr_type_phi, nir_phi_builder_value_get_block_def(), nir_src_for_ssa(), NIR_VLA, nir_instr::node, nir_phi_src::node, nir_phi_builder::num_blocks, nir_phi_src::pred, nir_block::predecessors, nir_phi_src::src, nir_phi_instr::srcs, nir_instr::type, and nir_phi_builder::values.
Referenced by nir_lower_regs_to_ssa_impl(), nir_lower_vars_to_ssa_impl(), and nir_repair_ssa_impl().
nir_phi_builder_value_get_block_def()
nir_ssa_def* nir_phi_builder_value_get_block_def (struct nir_phi_builder_value * val, nir_block * block)
References nir_phi_builder_value::bit_size, nir_instr::block, nir_function_impl::body, nir_phi_builder_value::builder, nir_ssa_undef_instr::def, nir_phi_builder_value::defs, nir_phi_instr::dest, nir_block::imm_dom, nir_phi_builder::impl, nir_block::index, nir_ssa_undef_instr::instr, nir_phi_instr::instr, NEEDS_PHI, nir_before_cf_list(), nir_instr_insert(), nir_phi_instr_create(), nir_ssa_dest_init(), nir_ssa_undef_instr_create(), nir_instr::node, nir_phi_builder_value::num_components, nir_phi_builder_value::phis, nir_phi_builder::shader, and nir_dest::ssa.
Referenced by nir_phi_builder_finish(), rename_variables(), repair_ssa_def(), rewrite_alu_instr(), rewrite_if_condition(), and rewrite_src().
nir_phi_builder_value_set_block_def()
void nir_phi_builder_value_set_block_def (struct nir_phi_builder_value * val, nir_block * block, nir_ssa_def * def)
References nir_phi_builder_value::defs, and nir_block::index.
Referenced by rename_variables(), repair_ssa_def(), rewrite_alu_instr(), and rewrite_dest().