Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_clone.c File Reference
#include "nir.h"
#include "nir_control_flow.h"
Data Structures
struct clone_state
Functions
static void init_clone_state (clone_state *state, struct hash_table *remap_table, bool global, bool allow_remap_fallback)
static void free_clone_state (clone_state *state)
static void * _lookup_ptr (clone_state *state, const void *ptr, bool global)
static void add_remap (clone_state *state, void *nptr, const void *ptr)
static void * remap_local (clone_state *state, const void *ptr)
static void * remap_global (clone_state *state, const void *ptr)
static nir_register * remap_reg (clone_state *state, const nir_register *reg)
static nir_variable * remap_var (clone_state *state, const nir_variable *var)
nir_constant * nir_constant_clone (const nir_constant *c, nir_variable *nvar)
nir_variable * nir_variable_clone (const nir_variable *var, nir_shader *shader)
static nir_variable * clone_variable (clone_state *state, const nir_variable *var)
static void clone_var_list (clone_state *state, struct exec_list *dst, const struct exec_list *list)
static nir_register * clone_register (clone_state *state, const nir_register *reg)
static void clone_reg_list (clone_state *state, struct exec_list *dst, const struct exec_list *list)
static void __clone_src (clone_state *state, void *ninstr_or_if, nir_src *nsrc, const nir_src *src)
static void __clone_dst (clone_state *state, nir_instr *ninstr, nir_dest *ndst, const nir_dest *dst)
static nir_deref * clone_deref (clone_state *state, const nir_deref *deref, nir_instr *ninstr, nir_deref *parent)
static nir_deref_var * clone_deref_var (clone_state *state, const nir_deref_var *dvar, nir_instr *ninstr)
static nir_deref_array * clone_deref_array (clone_state *state, const nir_deref_array *darr, nir_instr *ninstr, nir_deref *parent)
static nir_deref_struct * clone_deref_struct (clone_state *state, const nir_deref_struct *dstr, nir_instr *ninstr, nir_deref *parent)
static nir_alu_instr * clone_alu (clone_state *state, const nir_alu_instr *alu)
static nir_intrinsic_instr * clone_intrinsic (clone_state *state, const nir_intrinsic_instr *itr)
static nir_load_const_instr * clone_load_const (clone_state *state, const nir_load_const_instr *lc)
static nir_ssa_undef_instr * clone_ssa_undef (clone_state *state, const nir_ssa_undef_instr *sa)
static nir_tex_instr * clone_tex (clone_state *state, const nir_tex_instr *tex)
static nir_phi_instr * clone_phi (clone_state *state, const nir_phi_instr *phi, nir_block *nblk)
static nir_jump_instr * clone_jump (clone_state *state, const nir_jump_instr *jmp)
static nir_call_instr * clone_call (clone_state *state, const nir_call_instr *call)
static nir_instr * clone_instr (clone_state *state, const nir_instr *instr)
static nir_block * clone_block (clone_state *state, struct exec_list *cf_list, const nir_block *blk)
static void clone_cf_list (clone_state *state, struct exec_list *dst, const struct exec_list *list)
static nir_if * clone_if (clone_state *state, struct exec_list *cf_list, const nir_if *i)
static nir_loop * clone_loop (clone_state *state, struct exec_list *cf_list, const nir_loop *loop)
static void fixup_phi_srcs (clone_state *state)
void nir_cf_list_clone (nir_cf_list *dst, nir_cf_list *src, nir_cf_node *parent, struct hash_table *remap_table)
static nir_function_impl * clone_function_impl (clone_state *state, const nir_function_impl *fi)
nir_function_impl * nir_function_impl_clone (const nir_function_impl *fi)
static nir_function * clone_function (clone_state *state, const nir_function *fxn, nir_shader *ns)
nir_shader * nir_shader_clone (void *mem_ctx, const nir_shader *s)
Function Documentation
__clone_dst()
static void __clone_dst (clone_state * state, nir_instr * ninstr, nir_dest * ndst, const nir_dest * dst) static
References __clone_src(), add_remap(), nir_reg_dest::base_offset, nir_ssa_def::bit_size, clone_deref(), deref, nir_reg_dest::indirect, nir_dest::is_ssa, nir_ssa_def::name, nir_ssa_dest_init(), nir_ssa_def::num_components, nir_reg_dest::reg, nir_dest::reg, remap_reg(), and nir_dest::ssa.
Referenced by clone_alu(), clone_intrinsic(), clone_phi(), and clone_tex().
__clone_src()
static void __clone_src (clone_state * state, void * ninstr_or_if, nir_src * nsrc, const nir_src * src) static
References nir_reg_src::base_offset, nir_reg_src::indirect, nir_src::is_ssa, nir_reg_src::reg, nir_src::reg, remap_local(), remap_reg(), and nir_src::ssa.
Referenced by __clone_dst(), clone_alu(), clone_deref_array(), clone_if(), clone_intrinsic(), and clone_tex().
_lookup_ptr()
static void* _lookup_ptr (clone_state * state, const void * ptr, bool global) inline static
References clone_state::allow_remap_fallback, clone_state::global_clone, and clone_state::remap_table.
Referenced by remap_global(), remap_local(), remap_reg(), and remap_var().
add_remap()
static void add_remap (clone_state * state, void * nptr, const void * ptr) static
References clone_state::remap_table.
Referenced by __clone_dst(), clone_block(), clone_function(), clone_load_const(), clone_register(), clone_ssa_undef(), and clone_variable().
clone_alu()
static nir_alu_instr* clone_alu (clone_state * state, const nir_alu_instr * alu) static
References __clone_dst(), __clone_src(), nir_alu_src::abs, nir_alu_dest::dest, nir_alu_instr::dest, nir_alu_instr::exact, nir_alu_instr::instr, nir_alu_src::negate, nir_alu_instr_create(), nir_op_infos, clone_state::ns, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_dest::saturate, nir_alu_src::src, nir_alu_instr::src, nir_alu_src::swizzle, and nir_alu_dest::write_mask.
Referenced by clone_instr().
clone_block()
static nir_block* clone_block (clone_state * state, struct exec_list * cf_list, const nir_block * blk) static
References add_remap(), nir_block::cf_node, cf_node, clone_cf_list(), clone_instr(), clone_phi(), exec_node_data, instr, nir_block::instr_list, nir_foreach_instr, nir_instr_insert_after_block(), nir_instr_type_phi, and nir_cf_node::type.
Referenced by clone_cf_list().
clone_call()
static nir_call_instr* clone_call (clone_state * state, const nir_call_instr * call) static
References nir_call_instr::callee, clone_deref_var(), nir_call_instr::instr, nir_call_instr_create(), clone_state::ns, nir_call_instr::num_params, nir_call_instr::params, remap_global(), and nir_call_instr::return_deref.
Referenced by clone_instr().
clone_cf_list()
static void clone_cf_list (clone_state * state, struct exec_list * dst, const struct exec_list * list) static
References clone_block(), clone_if(), clone_loop(), and foreach_list_typed.
Referenced by clone_block(), clone_function_impl(), clone_if(), clone_loop(), and nir_cf_list_clone().
clone_deref()
static nir_deref * clone_deref (clone_state * state, const nir_deref * deref, nir_instr * ninstr, nir_deref * parent) static
References clone_deref_array(), clone_deref_struct(), nir_deref_array::deref, nir_deref_struct::deref, nir_deref::deref_type, nir_deref_type_array, and nir_deref_type_struct.
Referenced by __clone_dst(), clone_deref_array(), clone_deref_struct(), and clone_deref_var().
clone_deref_array()
static nir_deref_array* clone_deref_array (clone_state * state, const nir_deref_array * darr, nir_instr * ninstr, nir_deref * parent) static
References __clone_src(), nir_deref_array::base_offset, nir_deref::child, clone_deref(), nir_deref_array::deref, nir_deref_array::deref_array_type, nir_deref_array::indirect, nir_deref_array_create(), nir_deref_array_type_indirect, and nir_deref::type.
Referenced by clone_deref().
clone_deref_struct()
static nir_deref_struct* clone_deref_struct (clone_state * state, const nir_deref_struct * dstr, nir_instr * ninstr, nir_deref * parent) static
References nir_deref::child, clone_deref(), nir_deref_struct::deref, nir_deref_struct::index, nir_deref_struct_create(), and nir_deref::type.
Referenced by clone_deref().
clone_deref_var()
static nir_deref_var* clone_deref_var (clone_state * state, const nir_deref_var * dvar, nir_instr * ninstr) static
References nir_deref::child, clone_deref(), nir_deref_var::deref, nir_deref_var_create(), remap_var(), and nir_deref_var::var.
Referenced by clone_call(), clone_intrinsic(), and clone_tex().
clone_function()
static nir_function* clone_function (clone_state * state, const nir_function * fxn, nir_shader * ns) static
References add_remap(), nir_function::name, nir_function_create(), clone_state::ns, nir_function::num_params, nir_function::params, and nir_function::return_type.
Referenced by nir_shader_clone().
clone_function_impl()
static nir_function_impl* clone_function_impl (clone_state * state, const nir_function_impl * fi) static
References nir_function_impl::body, clone_cf_list(), clone_reg_list(), clone_var_list(), clone_variable(), fixup_phi_srcs(), nir_function_impl::locals, nir_function_impl_create_bare(), clone_state::ns, nir_function_impl::num_params, nir_function_impl::params, clone_state::phi_srcs, nir_function_impl::reg_alloc, nir_function_impl::registers, nir_function_impl::return_var, and nir_function_impl::valid_metadata.
Referenced by nir_function_impl_clone(), and nir_shader_clone().
clone_if()
static nir_if* clone_if (clone_state * state, struct exec_list * cf_list, const nir_if * i) static
References __clone_src(), nir_if::cf_node, clone_cf_list(), nir_if::condition, nir_if::else_list, nir_cf_node_insert_end(), nir_if_create(), clone_state::ns, and nir_if::then_list.
Referenced by clone_cf_list().
clone_instr()
static nir_instr* clone_instr (clone_state * state, const nir_instr * instr) static
References clone_alu(), clone_call(), clone_intrinsic(), clone_jump(), clone_load_const(), clone_ssa_undef(), clone_tex(), nir_alu_instr::instr, nir_call_instr::instr, nir_intrinsic_instr::instr, nir_tex_instr::instr, nir_load_const_instr::instr, nir_jump_instr::instr, nir_ssa_undef_instr::instr, nir_instr_type_alu, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, nir_instr_type_load_const, nir_instr_type_parallel_copy, nir_instr_type_phi, nir_instr_type_ssa_undef, nir_instr_type_tex, and nir_instr::type.
Referenced by clone_block().
clone_intrinsic()
static nir_intrinsic_instr* clone_intrinsic (clone_state * state, const nir_intrinsic_instr * itr) static
References __clone_dst(), __clone_src(), clone_deref_var(), nir_intrinsic_instr::const_index, nir_intrinsic_instr::dest, nir_intrinsic_info::has_dest, nir_intrinsic_instr::instr, nir_intrinsic_instr::intrinsic, nir_intrinsic_infos, nir_intrinsic_instr_create(), clone_state::ns, nir_intrinsic_instr::num_components, nir_intrinsic_info::num_srcs, nir_intrinsic_info::num_variables, nir_intrinsic_instr::src, and nir_intrinsic_instr::variables.
Referenced by clone_instr().
clone_jump()
static nir_jump_instr* clone_jump (clone_state * state, const nir_jump_instr * jmp) static
References nir_jump_instr_create(), clone_state::ns, and nir_jump_instr::type.
Referenced by clone_instr().
clone_load_const()
static nir_load_const_instr* clone_load_const (clone_state * state, const nir_load_const_instr * lc) static
References add_remap(), nir_ssa_def::bit_size, nir_load_const_instr::def, nir_load_const_instr_create(), clone_state::ns, nir_ssa_def::num_components, and nir_load_const_instr::value.
Referenced by clone_instr().
clone_loop()
static nir_loop* clone_loop (clone_state * state, struct exec_list * cf_list, const nir_loop * loop) static
References nir_loop::body, nir_loop::cf_node, clone_cf_list(), nir_cf_node_insert_end(), nir_loop_create(), and clone_state::ns.
Referenced by clone_cf_list().
clone_phi()
static nir_phi_instr* clone_phi (clone_state * state, const nir_phi_instr * phi, nir_block * nblk) static
References __clone_dst(), nir_phi_instr::dest, foreach_list_typed, nir_phi_instr::instr, nir_instr_insert_after_block(), nir_phi_instr_create(), nir_phi_src::node, clone_state::ns, nir_src::parent_instr, clone_state::phi_srcs, nir_phi_src::src, nir_phi_instr::srcs, and nir_src::use_link.
Referenced by clone_block().
clone_reg_list()
static void clone_reg_list (clone_state * state, struct exec_list * dst, const struct exec_list * list) static
References clone_register(), foreach_list_typed, and nir_register::node.
Referenced by clone_function_impl(), and nir_shader_clone().
clone_register()
static nir_register* clone_register (clone_state * state, const nir_register * reg) static
References add_remap(), nir_register::bit_size, nir_register::defs, nir_register::if_uses, nir_register::index, nir_register::is_global, nir_register::is_packed, nir_register::name, clone_state::ns, nir_register::num_array_elems, nir_register::num_components, and nir_register::uses.
Referenced by clone_reg_list().
clone_ssa_undef()
static nir_ssa_undef_instr* clone_ssa_undef (clone_state * state, const nir_ssa_undef_instr * sa) static
References add_remap(), nir_ssa_def::bit_size, nir_ssa_undef_instr::def, nir_ssa_undef_instr_create(), clone_state::ns, and nir_ssa_def::num_components.
Referenced by clone_instr().
clone_tex()
static nir_tex_instr* clone_tex (clone_state * state, const nir_tex_instr * tex) static
References __clone_dst(), __clone_src(), clone_deref_var(), nir_tex_instr::component, nir_tex_instr::coord_components, nir_tex_instr::dest, nir_tex_instr::dest_type, nir_tex_instr::instr, nir_tex_instr::is_array, nir_tex_instr::is_new_style_shadow, nir_tex_instr::is_shadow, nir_tex_instr_create(), clone_state::ns, nir_tex_instr::num_srcs, nir_tex_instr::op, nir_tex_instr::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_tex_instr::texture, nir_tex_instr::texture_array_size, and nir_tex_instr::texture_index.
Referenced by clone_instr().
clone_var_list()
static void clone_var_list (clone_state * state, struct exec_list * dst, const struct exec_list * list) static
References clone_variable(), foreach_list_typed, and nir_variable::node.
Referenced by clone_function_impl(), and nir_shader_clone().
clone_variable()
static nir_variable* clone_variable (clone_state * state, const nir_variable * var) static
References add_remap(), nir_variable_clone(), and clone_state::ns.
Referenced by clone_function_impl(), and clone_var_list().
fixup_phi_srcs()
static void fixup_phi_srcs (clone_state * state) static
References clone_state::phi_srcs, remap_local(), and remap_reg().
Referenced by clone_function_impl(), and nir_cf_list_clone().
free_clone_state()
static void free_clone_state (clone_state * state) static
References clone_state::remap_table.
Referenced by nir_function_impl_clone(), and nir_shader_clone().
init_clone_state()
static void init_clone_state (clone_state * state, struct hash_table * remap_table, bool global, bool allow_remap_fallback) static
References clone_state::allow_remap_fallback, clone_state::global_clone, clone_state::phi_srcs, and clone_state::remap_table.
Referenced by nir_cf_list_clone(), nir_function_impl_clone(), and nir_shader_clone().
nir_cf_list_clone()
void nir_cf_list_clone (nir_cf_list * dst, nir_cf_list * src, nir_cf_node * parent, struct hash_table * remap_table)
References nir_block::cf_node, clone_cf_list(), fixup_phi_srcs(), nir_function_impl::function, nir_cf_list::impl, init_clone_state(), nir_cf_list::list, nir_block_create(), nir_cf_node::node, clone_state::ns, nir_cf_node::parent, and nir_function::shader.
Referenced by complex_unroll(), opt_peel_loop_initial_if(), and simple_unroll().
nir_constant_clone()
nir_constant* nir_constant_clone (const nir_constant * c, nir_variable * nvar)
References nir_constant::elements, nir_constant::num_elements, and nir_constant::values.
Referenced by nir_variable_clone().
nir_function_impl_clone()
nir_function_impl* nir_function_impl_clone (const nir_function_impl * fi)
References clone_function_impl(), free_clone_state(), nir_function_impl::function, init_clone_state(), clone_state::ns, and nir_function::shader.
Referenced by inline_functions_block().
nir_shader_clone()
nir_shader* nir_shader_clone (void * mem_ctx, const nir_shader * s)
References clone_function(), clone_function_impl(), clone_reg_list(), clone_var_list(), foreach_list_typed, free_clone_state(), nir_function_impl::function, nir_shader::functions, nir_shader::globals, nir_function::impl, nir_shader::info, init_clone_state(), nir_shader::inputs, nir_foreach_function, nir_shader_create(), clone_state::ns, nir_shader::num_inputs, nir_shader::num_outputs, nir_shader::num_shared, nir_shader::num_uniforms, nir_shader::options, nir_shader::outputs, nir_shader::reg_alloc, nir_shader::registers, remap_global(), nir_shader::shared, nir_shader::stage, nir_shader::system_values, and nir_shader::uniforms.
nir_variable_clone()
nir_variable* nir_variable_clone (const nir_variable * var, nir_shader * shader)
References nir_variable::constant_initializer, nir_variable::data, nir_variable::interface_type, nir_variable::name, nir_constant_clone(), nir_variable::num_state_slots, nir_variable::state_slots, and nir_variable::type.
Referenced by clone_variable().
remap_global()
static void* remap_global (clone_state * state, const void * ptr) static
References _lookup_ptr().
Referenced by clone_call(), and nir_shader_clone().
remap_local()
static void* remap_local (clone_state * state, const void * ptr) static
References _lookup_ptr().
Referenced by __clone_src(), and fixup_phi_srcs().
remap_reg()
static nir_register* remap_reg (clone_state * state, const nir_register * reg) static
References _lookup_ptr(), and nir_register::is_global.
Referenced by __clone_dst(), __clone_src(), and fixup_phi_srcs().
remap_var()
static nir_variable* remap_var (clone_state * state, const nir_variable * var) static
References _lookup_ptr(), and nir_variable_is_global().
Referenced by clone_deref_var().