Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_dead_cf.c File Reference
#include "nir.h"
#include "nir_control_flow.h"
Functions
static void remove_after_cf_node (nir_cf_node *node)
static void opt_constant_if (nir_if *if_stmt, bool condition)
static bool cf_node_has_side_effects (nir_cf_node *node)
static bool def_not_live_out (nir_ssa_def *def, void *state)
static bool loop_is_dead (nir_loop *loop)
static bool dead_cf_block (nir_block *block)
static bool ends_in_jump (nir_block *block)
static bool dead_cf_list (struct exec_list *list, bool *list_ends_in_jump)
static bool opt_dead_cf_impl (nir_function_impl *impl)
bool nir_opt_dead_cf (nir_shader *shader)
Function Documentation
cf_node_has_side_effects()
static bool cf_node_has_side_effects (nir_cf_node * node) static
References nir_intrinsic_info::flags, instr, nir_intrinsic_instr::intrinsic, nir_foreach_block_in_cf_node, nir_foreach_instr, nir_instr_type_call, nir_instr_type_intrinsic, nir_instr_type_jump, NIR_INTRINSIC_CAN_ELIMINATE, nir_intrinsic_infos, nir_jump_return, and type.
Referenced by loop_is_dead().
dead_cf_block()
static bool dead_cf_block (nir_block * block) static
References nir_loop::cf_node, nir_if::condition, loop_is_dead(), nir_block_get_following_if(), nir_block_get_following_loop(), nir_cf_node_remove(), nir_src_as_const_value(), opt_constant_if(), and nir_const_value::u32.
Referenced by dead_cf_list().
dead_cf_list()
static bool dead_cf_list (struct exec_list * list, bool * list_ends_in_jump) static
References nir_loop::body, nir_block::cf_node, dead_cf_block(), nir_if::else_list, ends_in_jump(), exec_node_data, foreach_list_typed, nir_block::instr_list, exec_node::next, nir_cf_node_next(), nir_cf_node::node, remove_after_cf_node(), and nir_if::then_list.
Referenced by opt_dead_cf_impl().
def_not_live_out()
static bool def_not_live_out (nir_ssa_def * def, void * state) static
References nir_block::live_in, and nir_ssa_def::live_index.
Referenced by loop_is_dead().
ends_in_jump()
static bool ends_in_jump (nir_block * block) static
References instr, nir_block::instr_list, nir_block_last_instr(), nir_instr_type_jump, and nir_instr::type.
Referenced by dead_cf_list().
loop_is_dead()
static bool loop_is_dead (nir_loop * loop) static
References nir_loop::cf_node, cf_node_has_side_effects(), def_not_live_out(), nir_block::imm_dom, instr, nir_block::instr_list, nir_block_first_instr(), nir_cf_node_get_function(), nir_cf_node_next(), nir_cf_node_prev(), nir_foreach_instr, nir_foreach_ssa_def(), nir_instr_type_phi, nir_metadata_dominance, nir_metadata_live_ssa_defs, nir_metadata_require(), and type.
Referenced by dead_cf_block().
nir_opt_dead_cf()
bool nir_opt_dead_cf (nir_shader * shader)
References nir_foreach_function, and opt_dead_cf_impl().
opt_constant_if()
static void opt_constant_if (nir_if * if_stmt, bool condition) static
References nir_if::cf_node, nir_phi_instr::dest, nir_if::else_list, instr, nir_block::instr_list, nir_dest::is_ssa, nir_after_cf_node(), nir_block_last_instr(), nir_cf_list_extract(), nir_cf_node_next(), nir_cf_node_remove(), nir_cf_reinsert(), nir_foreach_instr_safe, nir_foreach_phi_src, nir_if_last_else_block(), nir_if_last_then_block(), nir_instr_remove(), nir_instr_type_jump, nir_instr_type_phi, nir_src_for_ssa(), nir_ssa_def_rewrite_uses(), remove_after_cf_node(), nir_dest::ssa, nir_if::then_list, and nir_instr::type.
Referenced by dead_cf_block().
opt_dead_cf_impl()
static bool opt_dead_cf_impl (nir_function_impl * impl) static
References nir_function_impl::body, dead_cf_list(), nir_metadata_none, and nir_metadata_preserve().
Referenced by nir_opt_dead_cf().
remove_after_cf_node()
static void remove_after_cf_node (nir_cf_node * node) static
References nir_after_cf_node(), nir_cf_delete(), nir_cf_extract(), nir_cf_node_is_last(), and nir_cf_node_next().
Referenced by dead_cf_list(), and opt_constant_if().