Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_global_to_local.c File Reference
#include "nir.h"
Functions
static bool global_to_local (nir_register *reg)
bool nir_opt_global_to_local (nir_shader *shader)
Function Documentation
global_to_local()
static bool global_to_local (nir_register * reg) static
References nir_instr::block, nir_block::cf_node, nir_if::cf_node, nir_register::index, instr, nir_register::is_global, nir_cf_node_get_function(), nir_foreach_def, nir_foreach_if_use, nir_foreach_use, nir_reg_remove(), nir_register::node, nir_function_impl::reg_alloc, and nir_function_impl::registers.
Referenced by nir_opt_global_to_local().
nir_opt_global_to_local()
bool nir_opt_global_to_local (nir_shader * shader)
References foreach_list_typed_safe, global_to_local(), and nir_shader::registers.