Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_opt_copy_propagate.c File Reference
#include "nir.h"
#include <main/imports.h>
Functions
static bool is_move (nir_alu_instr *instr)
SSA-based copy propagation.
static bool is_vec (nir_alu_instr *instr)
static bool is_swizzleless_move (nir_alu_instr *instr)
static bool copy_prop_src (nir_src *src, nir_instr *parent_instr, nir_if *parent_if, unsigned num_components)
static bool copy_prop_alu_src (nir_alu_instr *parent_alu_instr, unsigned index)
static bool copy_prop_dest (nir_dest *dest, nir_instr *instr)
static bool copy_prop_deref_var (nir_instr *instr, nir_deref_var *deref_var)
static bool copy_prop_instr (nir_instr *instr)
static bool copy_prop_if (nir_if *if_stmt)
static bool nir_copy_prop_impl (nir_function_impl *impl)
bool nir_copy_prop (nir_shader *shader)
Function Documentation
copy_prop_alu_src()
static bool copy_prop_alu_src (nir_alu_instr * parent_alu_instr, unsigned index) static
References copy_prop_src(), nir_reg_src::indirect, nir_alu_instr::instr, is_move(), nir_src::is_ssa, is_vec(), nir_alu_instr_channel_used(), nir_instr_rewrite_src(), nir_instr_type_alu, nir_src_for_ssa(), nir_alu_instr::op, nir_ssa_def::parent_instr, nir_src::reg, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_alu_src::swizzle, and nir_instr::type.
Referenced by copy_prop_instr().
copy_prop_deref_var()
static bool copy_prop_deref_var (nir_instr * instr, nir_deref_var * deref_var) static
References nir_deref::child, copy_prop_src(), nir_deref_var::deref, deref, nir_deref_array::deref_array_type, nir_deref_array::indirect, nir_deref_array_type_indirect, nir_deref_type_array, and copy_prop_var_state::progress.
Referenced by copy_prop_instr().
copy_prop_dest()
static bool copy_prop_dest (nir_dest * dest, nir_instr * instr) static
References copy_prop_src(), nir_reg_dest::indirect, nir_dest::is_ssa, and nir_dest::reg.
Referenced by copy_prop_instr().
copy_prop_if()
static bool copy_prop_if (nir_if * if_stmt) static
References nir_if::condition, and copy_prop_src().
Referenced by nir_copy_prop_impl().
copy_prop_instr()
static bool copy_prop_instr (nir_instr * instr) static
References copy_prop_alu_src(), copy_prop_deref_var(), copy_prop_dest(), copy_prop_src(), nir_alu_dest::dest, nir_alu_instr::dest, nir_intrinsic_instr::dest, nir_tex_instr::dest, nir_phi_instr::dest, nir_intrinsic_info::has_dest, nir_intrinsic_instr::intrinsic, nir_dest::is_ssa, nir_foreach_phi_src, nir_instr_type_alu, nir_instr_type_intrinsic, nir_instr_type_phi, nir_instr_type_tex, nir_intrinsic_infos, nir_op_infos, nir_tex_instr_src_size(), nir_ssa_def::num_components, nir_intrinsic_instr::num_components, nir_op_info::num_inputs, nir_intrinsic_info::num_srcs, nir_tex_instr::num_srcs, nir_intrinsic_info::num_variables, nir_alu_instr::op, copy_prop_var_state::progress, nir_tex_instr::sampler, nir_intrinsic_instr::src, nir_tex_src::src, nir_tex_instr::src, nir_intrinsic_info::src_components, nir_dest::ssa, nir_tex_instr::texture, nir_instr::type, and nir_intrinsic_instr::variables.
Referenced by nir_copy_prop_impl().
copy_prop_src()
static bool copy_prop_src (nir_src * src, nir_instr * parent_instr, nir_if * parent_if, unsigned num_components) static
References nir_if::condition, nir_reg_src::indirect, nir_src::is_ssa, is_swizzleless_move(), nir_if_rewrite_condition(), nir_instr_rewrite_src(), nir_instr_type_alu, nir_src_for_ssa(), nir_ssa_def::num_components, nir_ssa_def::parent_instr, nir_src::reg, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, and nir_instr::type.
Referenced by copy_prop_alu_src(), copy_prop_deref_var(), copy_prop_dest(), copy_prop_if(), and copy_prop_instr().
is_move()
static bool is_move (nir_alu_instr * instr) static
SSA-based copy propagation.
References nir_alu_src::abs, nir_alu_instr::dest, nir_src::is_ssa, nir_alu_src::negate, nir_alu_instr::op, nir_alu_dest::saturate, nir_alu_src::src, and nir_alu_instr::src.
Referenced by copy_prop_alu_src(), and is_swizzleless_move().
is_swizzleless_move()
static bool is_swizzleless_move (nir_alu_instr * instr) static
References nir_alu_instr::dest, is_move(), is_vec(), nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_src::src, nir_alu_instr::src, nir_src::ssa, nir_alu_src::swizzle, and nir_alu_dest::write_mask.
Referenced by copy_prop_src().
is_vec()
static bool is_vec (nir_alu_instr * instr) static
References nir_alu_src::abs, nir_src::is_ssa, nir_alu_src::negate, nir_op_infos, nir_op_info::num_inputs, nir_alu_instr::op, nir_alu_src::src, and nir_alu_instr::src.
Referenced by copy_prop_alu_src(), and is_swizzleless_move().
nir_copy_prop()
bool nir_copy_prop (nir_shader * shader)
References nir_copy_prop_impl(), nir_foreach_function, and copy_prop_var_state::progress.
nir_copy_prop_impl()
static bool nir_copy_prop_impl (nir_function_impl * impl) static
References copy_prop_if(), copy_prop_instr(), instr, nir_block_get_following_if(), nir_foreach_block, nir_foreach_instr, nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and copy_prop_var_state::progress.
Referenced by nir_copy_prop().