Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_returns.c File Reference
#include "nir.h"
#include "nir_builder.h"
#include "nir_control_flow.h"
Data Structures
struct lower_returns_state
Functions
static bool lower_returns_in_cf_list (struct exec_list *cf_list, struct lower_returns_state *state)
static void predicate_following (nir_cf_node *node, struct lower_returns_state *state)
static bool lower_returns_in_loop (nir_loop *loop, struct lower_returns_state *state)
static bool lower_returns_in_if (nir_if *if_stmt, struct lower_returns_state *state)
static bool lower_returns_in_block (nir_block *block, struct lower_returns_state *state)
bool nir_lower_returns_impl (nir_function_impl *impl)
bool nir_lower_returns (nir_shader *shader)
Function Documentation
lower_returns_in_block()
static bool lower_returns_in_block (nir_block * block, struct lower_returns_state * state) static
References nir_function_impl::body, lower_returns_state::builder, lower_returns_state::cf_list, nir_block::cf_node, nir_builder::cursor, nir_builder::impl, nir_jump_instr::instr, nir_cf_list::list, lower_returns_state::loop, nir_after_block(), nir_after_cf_list(), nir_before_cf_list(), nir_before_cf_node(), nir_block_last_instr(), nir_cf_delete(), nir_cf_extract(), nir_cf_node_next(), NIR_FALSE, nir_imm_int(), nir_instr_remove(), nir_instr_type_jump, nir_jump(), nir_jump_break, nir_jump_return, nir_local_variable_create(), nir_start_block(), nir_store_var(), NIR_TRUE, nir_block::predecessors, lower_returns_state::return_flag, nir_instr::type, and nir_jump_instr::type.
Referenced by lower_returns_in_cf_list().
lower_returns_in_cf_list()
static bool lower_returns_in_cf_list (struct exec_list * cf_list, struct lower_returns_state * state) static
References lower_returns_state::cf_list, foreach_list_typed_reverse_safe, lower_returns_in_block(), lower_returns_in_if(), and lower_returns_in_loop().
Referenced by lower_returns_in_if(), lower_returns_in_loop(), and nir_lower_returns_impl().
lower_returns_in_if()
static bool lower_returns_in_if (nir_if * if_stmt, struct lower_returns_state * state) static
References lower_returns_state::cf_list, nir_if::cf_node, nir_if::else_list, lower_returns_state::has_predicated_return, lower_returns_state::loop, lower_returns_in_cf_list(), nir_after_cf_list(), nir_after_cf_node(), nir_cf_delete(), nir_cf_extract(), nir_cf_reinsert(), predicate_following(), and nir_if::then_list.
Referenced by lower_returns_in_cf_list().
lower_returns_in_loop()
static bool lower_returns_in_loop (nir_loop * loop, struct lower_returns_state * state) static
References nir_loop::body, nir_loop::cf_node, lower_returns_state::has_predicated_return, lower_returns_state::loop, lower_returns_in_cf_list(), and predicate_following().
Referenced by lower_returns_in_cf_list().
nir_lower_returns()
bool nir_lower_returns (nir_shader * shader)
References nir_foreach_function, and nir_lower_returns_impl().
nir_lower_returns_impl()
bool nir_lower_returns_impl (nir_function_impl * impl)
References nir_function_impl::body, lower_returns_state::builder, lower_returns_state::cf_list, lower_returns_state::has_predicated_return, lower_returns_state::loop, lower_returns_in_cf_list(), nir_builder_init(), nir_metadata_none, nir_metadata_preserve(), nir_repair_ssa_impl(), and lower_returns_state::return_flag.
Referenced by nir_lower_returns().
predicate_following()
static void predicate_following (nir_cf_node * node, struct lower_returns_state * state) static
References lower_returns_state::builder, lower_returns_state::cf_list, nir_if::cf_node, nir_if::condition, nir_builder::cursor, nir_if::else_list, nir_jump_instr::instr, nir_cf_list::list, lower_returns_state::loop, nir_after_cf_list(), nir_after_cf_node(), nir_after_cf_node_and_phis(), nir_before_cf_list(), nir_cf_extract(), nir_cf_node_insert(), nir_cf_reinsert(), nir_cursors_equal(), nir_if_create(), nir_instr_insert(), nir_jump_break, nir_jump_instr_create(), nir_load_var(), nir_src_for_ssa(), lower_returns_state::return_flag, nir_builder::shader, and nir_if::then_list.
Referenced by lower_returns_in_if(), and lower_returns_in_loop().