Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
nir_lower_bitmap.c File Reference
#include "nir.h"
#include "nir_builder.h"
Functions
static nir_variable * get_texcoord (nir_shader *shader)
static void lower_bitmap (nir_shader *shader, nir_builder *b, const nir_lower_bitmap_options *options)
static void lower_bitmap_impl (nir_function_impl *impl, const nir_lower_bitmap_options *options)
void nir_lower_bitmap (nir_shader *shader, const nir_lower_bitmap_options *options)
Function Documentation
get_texcoord()
static nir_variable* get_texcoord (nir_shader * shader) static
References nir_variable::data, nir_shader::inputs, nir_variable::nir_variable_data::location, nir_foreach_variable, nir_var_shader_in, and nir_variable_create().
Referenced by lower_bitmap().
lower_bitmap()
static void lower_bitmap (nir_shader * shader, nir_builder * b, const nir_lower_bitmap_options * options) static
References nir_tex_instr::coord_components, nir_tex_instr::dest, nir_tex_instr::dest_type, get_texcoord(), nir_shader::info, nir_intrinsic_instr::instr, nir_tex_instr::instr, nir_builder_instr_insert(), nir_channel(), nir_intrinsic_instr_create(), nir_load_var(), nir_src_for_ssa(), nir_ssa_dest_init(), nir_tex_instr_create(), nir_tex_src_coord, nir_texop_tex, nir_type_float, nir_tex_instr::op, nir_lower_bitmap_options::sampler, nir_tex_instr::sampler_dim, nir_tex_instr::sampler_index, nir_intrinsic_instr::src, nir_tex_src::src, nir_tex_instr::src, nir_tex_src::src_type, nir_dest::ssa, nir_lower_bitmap_options::swizzle_xxxx, and nir_tex_instr::texture_index.
Referenced by lower_bitmap_impl().
lower_bitmap_impl()
static void lower_bitmap_impl (nir_function_impl * impl, const nir_lower_bitmap_options * options) static
References nir_function_impl::body, nir_builder::cursor, nir_function_impl::function, lower_bitmap(), nir_before_cf_list(), nir_builder_init(), nir_metadata_block_index, nir_metadata_dominance, nir_metadata_preserve(), and nir_function::shader.
Referenced by nir_lower_bitmap().
nir_lower_bitmap()
void nir_lower_bitmap (nir_shader * shader, const nir_lower_bitmap_options * options)
References lower_bitmap_impl(), nir_shader_get_entrypoint(), and nir_shader::stage.