Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_exec_draw.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/compiler.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/state.h"
#include "main/vtxfmt.h"
#include "vbo_context.h"
#include "vbo_noop.h"
Functions
static void vbo_exec_debug_verts (struct vbo_exec_context *exec)
static GLuint vbo_copy_vertices (struct vbo_exec_context *exec)
Copy zero, one or two vertices from the current vertex buffer into the temporary "copy" buffer.
static void vbo_exec_bind_arrays (struct gl_context *ctx)
static void vbo_exec_vtx_unmap (struct vbo_exec_context *exec)
Unmap the VBO.
void vbo_exec_vtx_map (struct vbo_exec_context *exec)
Map the vertex buffer to begin storing glVertex, glColor, etc data.
void vbo_exec_vtx_flush (struct vbo_exec_context *exec, GLboolean keepUnmapped)
Execute the buffer and save copied verts.
Function Documentation
vbo_copy_vertices()
static GLuint vbo_copy_vertices (struct vbo_exec_context * exec) static
Copy zero, one or two vertices from the current vertex buffer into the temporary "copy" buffer.
This is used when a single primitive overflows a vertex buffer and we need to continue the primitive in a new vertex buffer. The temporary "copy" buffer holds the vertices which need to get copied from the old buffer to the new one.
References _mesa_prim::begin, vbo_exec_copied_vtx::buffer, vbo_exec_context::buffer_map, vbo_exec_context::copied, _mesa_prim::count, vbo_exec_context::ctx, dd_function_table::CurrentExecPrimitive, gl_context::Driver, GLuint, vbo_exec_context::prim, vbo_exec_context::prim_count, PRIM_OUTSIDE_BEGIN_END, _mesa_prim::start, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_vtx_flush().
vbo_exec_bind_arrays()
static void vbo_exec_bind_arrays (struct gl_context * ctx) static
References gl_vertex_program_state::_Current, gl_vertex_array::_ElementSize, _mesa_set_varying_vp_inputs(), vbo_exec_context::arrays, vbo_exec_context::attrptr, vbo_exec_context::attrsz, vbo_exec_context::attrtype, vbo_exec_context::buffer_map, gl_vertex_array::BufferObj, vbo_exec_context::bufferobj, vbo_exec_context::ctx, vbo_context::currval, gl_context::DriverFlags, vbo_context::exec, gl_vertex_array::Format, get_program_mode(), GLuint, gl_program::info, vbo_exec_context::inputs, gl_vertex_array::Integer, MAP_INTERNAL, vbo_context::map_vp_arb, vbo_context::map_vp_none, gl_buffer_object::Mappings, MAT_ATTRIB_MAX, gl_driver_flags::NewArray, gl_context::NewDriverState, gl_buffer_mapping::Offset, gl_buffer_mapping::Pointer, gl_vertex_array::Ptr, gl_vertex_array::Size, gl_vertex_array::StrideB, gl_vertex_array::Type, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_MAT_FRONT_AMBIENT, VBO_ATTRIB_POS, vbo_attrtype_to_integer_flag(), vbo_context(), vbo_exec_context::vertex, vbo_exec_context::vertex_size, gl_context::VertexProgram, VP_ARB, VP_NONE, and vbo_exec_context::vtx.
Referenced by vbo_exec_vtx_flush().
vbo_exec_debug_verts()
static void vbo_exec_debug_verts (struct vbo_exec_context * exec) static
References _mesa_lookup_prim_by_nr(), _mesa_prim::begin, _mesa_prim::count, _mesa_index_buffer::count, _mesa_prim::end, GLuint, _mesa_prim::mode, vbo_exec_context::prim, vbo_exec_context::prim_count, _mesa_prim::start, vbo_exec_context::vert_count, vbo_exec_context::vertex_size, vbo_exec_context::vtx, and _mesa_prim::weak.
Referenced by vbo_exec_vtx_flush().
vbo_exec_vtx_flush()
void vbo_exec_vtx_flush (struct vbo_exec_context * exec, GLboolean keepUnmapped)
Execute the buffer and save copied verts.
Parameters
keep_unmapped if true, leave the VBO unmapped when we're done.
References _mesa_update_state(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::copied, vbo_exec_context::ctx, vbo_context::draw_prims, vbo_exec_context::max_vert, gl_context::NewState, vbo_exec_copied_vtx::nr, vbo_exec_context::prim, vbo_exec_context::prim_count, vbo_compute_max_verts(), vbo_context(), vbo_copy_vertices(), vbo_exec_bind_arrays(), vbo_exec_debug_verts(), vbo_exec_vtx_map(), vbo_exec_vtx_unmap(), vbo_exec_context::vert_count, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_End(), vbo_exec_FlushVertices_internal(), and vbo_exec_wrap_buffers().
vbo_exec_vtx_map()
void vbo_exec_vtx_map (struct vbo_exec_context * exec)
Map the vertex buffer to begin storing glVertex, glColor, etc data.
References _mesa_error(), _mesa_install_exec_vtxfmt(), _mesa_using_noop_vtxfmt(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::buffer_used, dd_function_table::BufferData, vbo_exec_context::bufferobj, vbo_exec_context::ctx, gl_context::Driver, gl_context::Exec, MAP_INTERNAL, dd_function_table::MapBufferRange, MESA_MAP_NOWAIT_BIT, gl_buffer_object::Size, VBO_VERT_BUFFER_SIZE, vbo_exec_context::vtx, vbo_exec_context::vtxfmt, and vbo_exec_context::vtxfmt_noop.
Referenced by vbo_exec_begin_vertices(), and vbo_exec_vtx_flush().
vbo_exec_vtx_unmap()
static void vbo_exec_vtx_unmap (struct vbo_exec_context * exec) static
Unmap the VBO.
This is called before drawing.
References vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::buffer_used, vbo_exec_context::bufferobj, vbo_exec_context::ctx, gl_context::Driver, dd_function_table::FlushMappedBufferRange, MAP_INTERNAL, gl_buffer_object::Mappings, vbo_exec_context::max_vert, gl_buffer_mapping::Offset, dd_function_table::UnmapBuffer, VBO_VERT_BUFFER_SIZE, and vbo_exec_context::vtx.
Referenced by vbo_exec_vtx_flush().