Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_split_inplace.c File Reference
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/enums.h"
#include "main/glformats.h"
#include "vbo_split.h"
Data Structures
struct split_context
Macros
#define MAX_PRIM 32
Functions
static void flush_vertex (struct split_context *split)
static struct _mesa_prim * next_outprim (struct split_context *split)
static void update_index_bounds (struct split_context *split, const struct _mesa_prim *prim)
static GLuint get_max_vertices (struct split_context *split, const struct _mesa_prim *prim)
static void split_prims (struct split_context *split)
void vbo_split_inplace (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits *limits)
Macro Definition Documentation
MAX_PRIM
#define MAX_PRIM 32
Referenced by next_outprim().
Function Documentation
flush_vertex()
static void flush_vertex (struct split_context * split) static
References gl_array_attrib::_DrawArrays, _mesa_sizeof_type(), gl_context::Array, split_context::array, _mesa_index_buffer::count, split_context::ctx, split_context::draw, gl_context::DriverFlags, split_context::dstprim, split_context::dstprim_nr, GLuint, split_context::ib, split_context::max_index, split_context::min_index, gl_driver_flags::NewArray, gl_context::NewDriverState, _mesa_index_buffer::ptr, _mesa_prim::start, and _mesa_index_buffer::type.
Referenced by next_outprim(), and split_prims().
get_max_vertices()
static GLuint get_max_vertices (struct split_context * split, const struct _mesa_prim * prim) static
References GLuint, split_context::limit, split_context::max_index, split_context::min_index, and _mesa_prim::start.
Referenced by split_prims().
next_outprim()
static struct _mesa_prim* next_outprim (struct split_context * split) static
References split_context::dstprim, split_context::dstprim_nr, flush_vertex(), MAX_PRIM, and split_context::prim.
Referenced by split_prims().
split_prims()
static void split_prims (struct split_context * split) static
References split_context::array, _mesa_prim::base_instance, _mesa_prim::begin, _mesa_prim::count, _mesa_index_buffer::count, split_context::ctx, split_context::draw, _mesa_prim::end, flush_vertex(), get_max_vertices(), GLuint, split_context::ib, _mesa_prim::indexed, split_context::limits, _mesa_prim::mode, next_outprim(), split_context::nr_prims, gl_shared_state::NullBufferObj, _mesa_prim::num_instances, _mesa_index_buffer::obj, split_context::prim, _mesa_index_buffer::ptr, gl_context::Shared, split_prim_inplace(), _mesa_prim::start, _mesa_index_buffer::type, update_index_bounds(), and vbo_split_copy().
Referenced by vbo_split_inplace().
update_index_bounds()
static void update_index_bounds (struct split_context * split, const struct _mesa_prim * prim) static
References _mesa_prim::count, split_context::max_index, split_context::min_index, and _mesa_prim::start.
Referenced by split_prims().
vbo_split_inplace()
void vbo_split_inplace (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits * limits)
References split_context::array, split_context::ctx, split_context::draw, split_context::ib, split_context::limit, split_context::limits, split_context::max_index, split_limits::max_indices, split_limits::max_verts, split_context::min_index, split_context::nr_prims, split_context::prim, and split_prims().
Referenced by vbo_split_prims().