Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo.h File Reference
#include <stdbool.h>
#include "main/glheader.h"
Data Structures
struct _mesa_prim
struct _mesa_index_buffer
struct split_limits
Typedefs
typedef void(* vbo_draw_func) (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *tfb_vertcount, unsigned stream, struct gl_buffer_object *indirect)
typedef void(* vbo_indirect_draw_func) (struct gl_context *ctx, GLuint mode, struct gl_buffer_object *indirect_data, GLsizeiptr indirect_offset, unsigned draw_count, unsigned stride, struct gl_buffer_object *indirect_params, GLsizeiptr indirect_params_offset, const struct _mesa_index_buffer *ib)
Functions
GLboolean _vbo_CreateContext (struct gl_context *ctx)
void _vbo_DestroyContext (struct gl_context *ctx)
void _vbo_InvalidateState (struct gl_context *ctx, GLbitfield new_state)
void vbo_initialize_exec_dispatch (const struct gl_context *ctx, struct _glapi_table *exec)
Initialize the dispatch table with the VBO functions for drawing.
void vbo_initialize_save_dispatch (const struct gl_context *ctx, struct _glapi_table *exec)
Initialize the dispatch table with the VBO functions for display list compilation.
void vbo_exec_FlushVertices (struct gl_context *ctx, GLuint flags)
If inside glBegin()/glEnd(), it should assert(0).
void vbo_save_SaveFlushVertices (struct gl_context *ctx)
GLboolean vbo_save_NotifyBegin (struct gl_context *ctx, GLenum mode)
Called when a glBegin is getting compiled into a display list.
void vbo_save_NewList (struct gl_context *ctx, GLuint list, GLenum mode)
void vbo_save_EndList (struct gl_context *ctx)
void vbo_save_BeginCallList (struct gl_context *ctx, struct gl_display_list *list)
void vbo_save_EndCallList (struct gl_context *ctx)
void vbo_split_prims (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits *limits)
GLboolean vbo_all_varyings_in_vbos (const struct gl_vertex_array *arrays[])
GLboolean vbo_any_varyings_in_vbos (const struct gl_vertex_array *arrays[])
void vbo_rebase_prims (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw)
static int vbo_sizeof_ib_type (GLenum type)
void vbo_delete_minmax_cache (struct gl_buffer_object *bufferObj)
void vbo_get_minmax_indices (struct gl_context *ctx, const struct _mesa_prim *prim, const struct _mesa_index_buffer *ib, GLuint *min_index, GLuint *max_index, GLuint nr_prims)
Compute min and max elements for nr_prims.
void vbo_use_buffer_objects (struct gl_context *ctx)
Tell the VBO module to use a real OpenGL vertex buffer object to store accumulated immediate-mode vertex data.
void vbo_always_unmap_buffers (struct gl_context *ctx)
If this function is called, all VBO buffers will be unmapped when we flush.
void vbo_set_draw_func (struct gl_context *ctx, vbo_draw_func func)
void vbo_set_indirect_draw_func (struct gl_context *ctx, vbo_indirect_draw_func func)
void vbo_bind_arrays (struct gl_context *ctx)
Examine the enabled vertex arrays to set the exec->array.inputs[] values.
size_t vbo_count_tessellated_primitives (GLenum mode, GLuint count, GLuint num_instances)
Figure out the number of transform feedback primitives that will be output considering the drawing mode, number of vertices, and instance count, assuming that no geometry shading is done and primitive restart is not used.
void vbo_try_prim_conversion (struct _mesa_prim *p)
In some degenarate cases we can improve our ability to merge consecutive primitives.
bool vbo_can_merge_prims (const struct _mesa_prim *p0, const struct _mesa_prim *p1)
Helper function for determining if two subsequent glBegin/glEnd primitives can be combined.
void vbo_merge_prims (struct _mesa_prim *p0, const struct _mesa_prim *p1)
If we've determined that p0 and p1 can be merged, this function concatenates p1 onto p0.
void vbo_sw_primitive_restart (struct gl_context *ctx, const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, struct gl_buffer_object *indirect)
Handle primitive restart in software.
void GLAPIENTRY _es_Color4f (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void GLAPIENTRY _es_Normal3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_MultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
void GLAPIENTRY _es_Materialfv (GLenum face, GLenum pname, const GLfloat *params)
void GLAPIENTRY _es_Materialf (GLenum face, GLenum pname, GLfloat param)
void GLAPIENTRY _es_VertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _es_VertexAttrib1f (GLuint indx, GLfloat x)
void GLAPIENTRY _es_VertexAttrib1fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
void GLAPIENTRY _es_VertexAttrib2fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_VertexAttrib3fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib4fv (GLuint indx, const GLfloat *values)
Typedef Documentation
vbo_draw_func
typedef void(* vbo_draw_func) (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *tfb_vertcount, unsigned stream, struct gl_buffer_object *indirect)
vbo_indirect_draw_func
typedef void(* vbo_indirect_draw_func) (struct gl_context *ctx, GLuint mode, struct gl_buffer_object *indirect_data, GLsizeiptr indirect_offset, unsigned draw_count, unsigned stride, struct gl_buffer_object *indirect_params, GLsizeiptr indirect_params_offset, const struct _mesa_index_buffer *ib)
Function Documentation
_es_Color4f()
void GLAPIENTRY _es_Color4f (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
Referenced by vbo_sizeof_ib_type().
_es_Materialf()
void GLAPIENTRY _es_Materialf (GLenum face, GLenum pname, GLfloat param)
References vbo_Materialfv().
Referenced by vbo_sizeof_ib_type().
_es_Materialfv()
void GLAPIENTRY _es_Materialfv (GLenum face, GLenum pname, const GLfloat * params)
References vbo_Materialfv().
Referenced by vbo_sizeof_ib_type().
_es_MultiTexCoord4f()
void GLAPIENTRY _es_MultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
Referenced by vbo_sizeof_ib_type().
_es_Normal3f()
void GLAPIENTRY _es_Normal3f (GLfloat x, GLfloat y, GLfloat z)
Referenced by vbo_sizeof_ib_type().
_es_VertexAttrib1f()
void GLAPIENTRY _es_VertexAttrib1f (GLuint indx, GLfloat x)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib1fv()
void GLAPIENTRY _es_VertexAttrib1fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib2f()
void GLAPIENTRY _es_VertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib2fv()
void GLAPIENTRY _es_VertexAttrib2fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib3f()
void GLAPIENTRY _es_VertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib3fv()
void GLAPIENTRY _es_VertexAttrib3fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib4f()
void GLAPIENTRY _es_VertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib4fv()
void GLAPIENTRY _es_VertexAttrib4fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_vbo_CreateContext()
GLboolean _vbo_CreateContext (struct gl_context * ctx)
References _ae_create_context(), _math_init_eval(), gl_context::aelt_context, gl_context::API, API_OPENGL_COMPAT, CALLOC_STRUCT, for(), GLuint, init_generic_currval(), init_legacy_currval(), init_mat_currval(), vbo_context::map_vp_arb, vbo_context::map_vp_none, MAT_ATTRIB_MAX, VBO_ATTRIB_MAT_FRONT_AMBIENT, gl_context::vbo_context, vbo_draw_indirect_prims(), vbo_exec_init(), vbo_save_init(), and vbo_set_indirect_draw_func().
_vbo_DestroyContext()
void _vbo_DestroyContext (struct gl_context * ctx)
References _ae_destroy_context(), gl_context::aelt_context, gl_context::API, API_OPENGL_COMPAT, gl_vertex_array::BufferObj, vbo_context::currval, GLuint, VBO_ATTRIB_MAX, gl_context::vbo_context, vbo_context(), vbo_exec_destroy(), and vbo_save_destroy().
_vbo_InvalidateState()
void _vbo_InvalidateState (struct gl_context * ctx, GLbitfield new_state)
References vbo_exec_invalidate_state().
vbo_all_varyings_in_vbos()
GLboolean vbo_all_varyings_in_vbos (const struct gl_vertex_array * arrays[])
References GLuint.
vbo_always_unmap_buffers()
void vbo_always_unmap_buffers (struct gl_context * ctx)
If this function is called, all VBO buffers will be unmapped when we flush.
Otherwise, if a simple command like glColor3f() is called and we flush, the current VBO may be left mapped.
References vbo_exec_context::begin_vertices_flags, vbo_context::exec, FLUSH_STORED_VERTICES, and vbo_context().
Referenced by vbo_sizeof_ib_type().
vbo_any_varyings_in_vbos()
GLboolean vbo_any_varyings_in_vbos (const struct gl_vertex_array * arrays[])
References GLuint.
vbo_bind_arrays()
void vbo_bind_arrays (struct gl_context * ctx)
Examine the enabled vertex arrays to set the exec->array.inputs[] values.
These will point to the arrays to actually use for drawing. Some will be user-provided arrays, other will be zero-stride const-valued arrays. Note that this might set the _NEW_VARYING_VP_INPUTS dirty flag so state validation must be done after this call.
References _mesa_update_state(), vbo_exec_context::array, DRAW_ARRAYS, vbo_context::exec, gl_context::NewState, recalculate_input_bindings(), vbo_exec_context::recalculate_inputs, vbo_exec_context::validating, vbo_context(), and vbo_draw_method().
Referenced by vbo_draw_arrays(), vbo_draw_transform_feedback(), vbo_sizeof_ib_type(), vbo_validated_drawarraysindirect(), vbo_validated_drawelementsindirect(), vbo_validated_drawrangeelements(), vbo_validated_multidrawarraysindirect(), vbo_validated_multidrawarraysindirectcount(), vbo_validated_multidrawelements(), vbo_validated_multidrawelementsindirect(), and vbo_validated_multidrawelementsindirectcount().
vbo_can_merge_prims()
bool vbo_can_merge_prims (const struct _mesa_prim * p0, const struct _mesa_prim * p1)
Helper function for determining if two subsequent glBegin/glEnd primitives can be combined.
This is only possible for GL_POINTS, GL_LINES, GL_TRIANGLES and GL_QUADS. If we return true, it means that we can concatenate p1 onto p0 (and discard p1).
References _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::begin, _mesa_prim::count, _mesa_prim::end, _mesa_prim::mode, _mesa_prim::num_instances, and _mesa_prim::start.
Referenced by merge_prims(), try_vbo_merge(), vbo_merge_prims(), and vbo_sizeof_ib_type().
vbo_count_tessellated_primitives()
size_t vbo_count_tessellated_primitives (GLenum mode, GLuint count, GLuint num_instances)
Figure out the number of transform feedback primitives that will be output considering the drawing mode, number of vertices, and instance count, assuming that no geometry shading is done and primitive restart is not used.
This is used by driver back-ends in implementing the PRIMITIVES_GENERATED and TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN queries. It is also used to pre-validate draw calls in GLES3 (where draw calls only succeed if there is enough room in the transform feedback buffer for the result).
Referenced by vbo_sizeof_ib_type().
vbo_delete_minmax_cache()
void vbo_delete_minmax_cache (struct gl_buffer_object * bufferObj)
References gl_buffer_object::MinMaxCache, and vbo_minmax_cache_delete_entry().
Referenced by vbo_get_minmax_cached(), and vbo_sizeof_ib_type().
vbo_exec_FlushVertices()
void vbo_exec_FlushVertices (struct gl_context * ctx, GLuint flags)
If inside glBegin()/glEnd(), it should assert(0).
Otherwise, if FLUSH_STORED_VERTICES bit in flags is set flushes any buffered vertices, if FLUSH_UPDATE_CURRENT bit is set updates __struct gl_contextRec::Current and gl_light_attrib::Material
Note that the default T&L engine never clears the FLUSH_UPDATE_CURRENT bit, even after performing the update.
Parameters
flags bitmask of FLUSH_STORED_VERTICES, FLUSH_UPDATE_CURRENT
References gl_context::Driver, vbo_context::exec, FLUSH_UPDATE_CURRENT, dd_function_table::NeedFlush, vbo_context(), and vbo_exec_FlushVertices_internal().
vbo_get_minmax_indices()
void vbo_get_minmax_indices (struct gl_context * ctx, const struct _mesa_prim * prim, const struct _mesa_index_buffer * ib, GLuint * min_index, GLuint * max_index, GLuint nr_prims)
Compute min and max elements for nr_prims.
References minmax_cache_key::count, _mesa_prim::count, GLuint, _mesa_prim::start, and vbo_get_minmax_index().
Referenced by vbo_sizeof_ib_type().
vbo_initialize_exec_dispatch()
void vbo_initialize_exec_dispatch (const struct gl_context * ctx, struct _glapi_table * exec)
Initialize the dispatch table with the VBO functions for drawing.
References gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, gl_extensions::ARB_draw_elements_base_vertex, gl_context::Extensions, vbo_exec_DrawArrays(), vbo_exec_DrawArraysIndirect(), vbo_exec_DrawArraysInstanced(), vbo_exec_DrawArraysInstancedBaseInstance(), vbo_exec_DrawElements(), vbo_exec_DrawElementsBaseVertex(), vbo_exec_DrawElementsIndirect(), vbo_exec_DrawElementsInstanced(), vbo_exec_DrawElementsInstancedBaseInstance(), vbo_exec_DrawElementsInstancedBaseVertex(), vbo_exec_DrawElementsInstancedBaseVertexBaseInstance(), vbo_exec_DrawRangeElements(), vbo_exec_DrawRangeElementsBaseVertex(), vbo_exec_DrawTransformFeedback(), vbo_exec_DrawTransformFeedbackInstanced(), vbo_exec_DrawTransformFeedbackStream(), vbo_exec_DrawTransformFeedbackStreamInstanced(), vbo_exec_EvalMesh1(), vbo_exec_EvalMesh2(), vbo_exec_MultiDrawArraysIndirect(), vbo_exec_MultiDrawArraysIndirectCount(), vbo_exec_MultiDrawElements(), vbo_exec_MultiDrawElementsBaseVertex(), vbo_exec_MultiDrawElementsIndirect(), vbo_exec_MultiDrawElementsIndirectCount(), and vbo_exec_Rectf().
vbo_initialize_save_dispatch()
void vbo_initialize_save_dispatch (const struct gl_context * ctx, struct _glapi_table * exec)
Initialize the dispatch table with the VBO functions for display list compilation.
References _save_OBE_DrawArrays(), _save_OBE_DrawElements(), _save_OBE_DrawElementsBaseVertex(), _save_OBE_DrawRangeElements(), _save_OBE_MultiDrawElements(), _save_OBE_MultiDrawElementsBaseVertex(), and _save_OBE_Rectf().
vbo_merge_prims()
void vbo_merge_prims (struct _mesa_prim * p0, const struct _mesa_prim * p1)
If we've determined that p0 and p1 can be merged, this function concatenates p1 onto p0.
References _mesa_prim::count, _mesa_prim::end, and vbo_can_merge_prims().
Referenced by merge_prims(), try_vbo_merge(), and vbo_sizeof_ib_type().
vbo_rebase_prims()
void vbo_rebase_prims (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw)
References gl_array_attrib::_DrawArrays, _mesa_error_no_memory(), ADD_POINTERS, gl_extensions::ARB_draw_elements_base_vertex, gl_context::Array, _mesa_prim::basevertex, _mesa_index_buffer::count, gl_context::Driver, gl_context::DriverFlags, gl_context::Extensions, GLuint, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, gl_buffer_object::Name, gl_driver_flags::NewArray, gl_context::NewDriverState, gl_shared_state::NullBufferObj, _mesa_index_buffer::obj, gl_buffer_mapping::Pointer, gl_vertex_array::Ptr, _mesa_index_buffer::ptr, gl_context::Shared, gl_buffer_object::Size, _mesa_prim::start, gl_vertex_array::StrideB, _mesa_index_buffer::type, and dd_function_table::UnmapBuffer.
vbo_save_BeginCallList()
void vbo_save_BeginCallList (struct gl_context * ctx, struct gl_display_list * list)
References gl_display_list::Flags, vbo_save_context::replay_flags, vbo_context::save, and vbo_context().
vbo_save_EndCallList()
void vbo_save_EndCallList (struct gl_context * ctx)
References gl_dlist_state::CallDepth, gl_context::ListState, vbo_save_context::replay_flags, vbo_context::save, vbo_context(), and VBO_SAVE_FALLBACK.
vbo_save_EndList()
void vbo_save_EndList (struct gl_context * ctx)
References _mesa_install_save_vtxfmt(), _mesa_prim::count, dd_function_table::CurrentSavePrimitive, vbo_save_context::dangling_attr_ref, gl_context::Driver, _mesa_prim::end, gl_context::ListState, gl_dlist_state::ListVtxfmt, vbo_save_context::prim, vbo_save_context::prim_count, PRIM_OUTSIDE_BEGIN_END, vbo_context::save, _mesa_prim::start, vbo_context(), vbo_save_SaveFlushVertices(), vbo_save_unmap_vertex_store(), vbo_save_context::vert_count, vbo_save_context::vertex_size, and vbo_save_context::vertex_store.
vbo_save_NewList()
void vbo_save_NewList (struct gl_context * ctx, GLuint list, GLenum mode)
References _save_reset_counters(), _save_reset_vertex(), alloc_prim_store(), alloc_vertex_store(), vbo_save_context::buffer_ptr, gl_context::Driver, vbo_save_context::prim_store, vbo_context::save, dd_function_table::SaveNeedFlush, vbo_context(), vbo_save_map_vertex_store(), vbo_save_context::vertex_store, and void.
vbo_save_NotifyBegin()
GLboolean vbo_save_NotifyBegin (struct gl_context * ctx, GLenum mode)
Called when a glBegin is getting compiled into a display list.
Updating of ctx->Driver.CurrentSavePrimitive is already taken care of.
References _mesa_install_save_vtxfmt(), _mesa_prim::base_instance, _mesa_prim::begin, _mesa_prim::count, gl_context::Driver, _mesa_prim::end, GLuint, _mesa_prim::is_indirect, _mesa_prim::mode, _mesa_prim::no_current_update, _mesa_prim::num_instances, vbo_save_context::out_of_memory, _mesa_prim::pad, vbo_save_context::prim, vbo_save_context::prim_count, vbo_save_context::prim_max, vbo_context::save, dd_function_table::SaveNeedFlush, _mesa_prim::start, vbo_context(), VBO_SAVE_PRIM_MODE_MASK, VBO_SAVE_PRIM_NO_CURRENT_UPDATE, VBO_SAVE_PRIM_WEAK, vbo_save_context::vert_count, vbo_save_context::vtxfmt, vbo_save_context::vtxfmt_noop, and _mesa_prim::weak.
Referenced by _save_OBE_DrawArrays(), _save_OBE_DrawElementsBaseVertex(), and _save_OBE_Rectf().
vbo_save_SaveFlushVertices()
void vbo_save_SaveFlushVertices (struct gl_context * ctx)
References _save_compile_vertex_list(), _save_copy_to_current(), _save_reset_counters(), _save_reset_vertex(), dd_function_table::CurrentSavePrimitive, gl_context::Driver, vbo_save_context::prim_count, PRIM_MAX, vbo_context::save, dd_function_table::SaveNeedFlush, vbo_context(), and vbo_save_context::vert_count.
Referenced by vbo_save_EndList().
vbo_set_draw_func()
void vbo_set_draw_func (struct gl_context * ctx, vbo_draw_func func)
References vbo_context::draw_prims, and vbo_context().
Referenced by vbo_sizeof_ib_type().
vbo_set_indirect_draw_func()
void vbo_set_indirect_draw_func (struct gl_context * ctx, vbo_indirect_draw_func func)
References vbo_context::draw_indirect_prims, and vbo_context().
Referenced by _vbo_CreateContext(), and vbo_sizeof_ib_type().
vbo_sizeof_ib_type()
static int vbo_sizeof_ib_type (GLenum type) inline static
References _es_Color4f(), _es_Materialf(), _es_Materialfv(), _es_MultiTexCoord4f(), _es_Normal3f(), _es_VertexAttrib1f(), _es_VertexAttrib1fv(), _es_VertexAttrib2f(), _es_VertexAttrib2fv(), _es_VertexAttrib3f(), _es_VertexAttrib3fv(), _es_VertexAttrib4f(), _es_VertexAttrib4fv(), _mesa_prim::count, GLuint, GLushort, _mesa_prim::num_instances, p0, p1, vbo_always_unmap_buffers(), vbo_bind_arrays(), vbo_can_merge_prims(), vbo_count_tessellated_primitives(), vbo_delete_minmax_cache(), vbo_get_minmax_indices(), vbo_merge_prims(), vbo_set_draw_func(), vbo_set_indirect_draw_func(), vbo_sw_primitive_restart(), vbo_try_prim_conversion(), vbo_use_buffer_objects(), and x.
Referenced by vbo_get_minmax_index(), vbo_sw_primitive_restart(), and vbo_validated_multidrawelements().
vbo_split_prims()
void vbo_split_prims (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits * limits)
References _mesa_index_buffer::count, split_limits::max_indices, split_limits::max_verts, vbo_split_copy(), and vbo_split_inplace().
vbo_sw_primitive_restart()
void vbo_sw_primitive_restart (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, struct gl_buffer_object * indirect)
Handle primitive restart in software.
This function breaks up calls into the driver so primitive restart support is not required in the driver.
References _mesa_error(), _mesa_primitive_restart_index(), ADD_POINTERS, _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::count, sub_primitive::count, _mesa_index_buffer::count, vbo_context::draw_prims, gl_context::Driver, find_sub_primitives(), GLuint, _mesa_prim::indirect_offset, _mesa_prim::is_indirect, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, sub_primitive::max_index, sub_primitive::min_index, gl_buffer_object::Name, _mesa_prim::num_instances, _mesa_index_buffer::obj, gl_buffer_mapping::Pointer, _mesa_index_buffer::ptr, gl_buffer_object::Size, _mesa_prim::start, sub_primitive::start, _mesa_index_buffer::type, dd_function_table::UnmapBuffer, vbo_context(), and vbo_sizeof_ib_type().
Referenced by vbo_sizeof_ib_type().
vbo_try_prim_conversion()
void vbo_try_prim_conversion (struct _mesa_prim * p)
In some degenarate cases we can improve our ability to merge consecutive primitives.
For example: glBegin(GL_LINE_STRIP); glVertex(1); glVertex(1); glEnd(); glBegin(GL_LINE_STRIP); glVertex(1); glVertex(1); glEnd(); Can be merged as a GL_LINES prim with four vertices.
This function converts 2-vertex line strips/loops into GL_LINES, etc.
References _mesa_prim::count, and _mesa_prim::mode.
Referenced by merge_prims(), try_vbo_merge(), and vbo_sizeof_ib_type().
vbo_use_buffer_objects()
void vbo_use_buffer_objects (struct gl_context * ctx)
Tell the VBO module to use a real OpenGL vertex buffer object to store accumulated immediate-mode vertex data.
This replaces the malloced buffer which was created in vb_exec_vtx_init() below.
References _mesa_align_free(), _mesa_error(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, dd_function_table::BufferData, vbo_exec_context::bufferobj, gl_context::Driver, vbo_context::exec, GLuint, IMM_BUFFER_NAME, dd_function_table::NewBufferObject, gl_shared_state::NullBufferObj, gl_context::Shared, vbo_context(), VBO_VERT_BUFFER_SIZE, and vbo_exec_context::vtx.
Referenced by vbo_sizeof_ib_type().