Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_exec_array.c File Reference
#include <stdio.h>
#include "main/arrayobj.h"
#include "main/glheader.h"
#include "main/context.h"
#include "main/state.h"
#include "main/api_validate.h"
#include "main/dispatch.h"
#include "main/varray.h"
#include "main/bufferobj.h"
#include "main/enums.h"
#include "main/macros.h"
#include "main/transformfeedback.h"
#include "vbo_context.h"
Functions
static void check_array_data (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint attrib, GLuint j)
Check that element 'j' of the array has reasonable data.
static void unmap_array_buffer (struct gl_context *ctx, struct gl_vertex_array_object *vao, GLuint attrib)
Unmap the buffer object referenced by given array, if mapped.
static void check_draw_elements_data (struct gl_context *ctx, GLsizei count, GLenum elemType, const void *elements, GLint basevertex)
Examine the array's data for NaNs, etc.
static void check_draw_arrays_data (struct gl_context *ctx, GLint start, GLsizei count)
Check array data, looking for NaNs, etc.
static void print_draw_arrays (struct gl_context *ctx, GLenum mode, GLint start, GLsizei count)
Print info/data for glDrawArrays(), for debugging.
static void recalculate_input_bindings (struct gl_context *ctx)
Set the vbo->exec->inputs[] pointers to point to the enabled vertex arrays.
void vbo_bind_arrays (struct gl_context *ctx)
Examine the enabled vertex arrays to set the exec->array.inputs[] values.
static void vbo_draw_arrays (struct gl_context *ctx, GLenum mode, GLint start, GLsizei count, GLuint numInstances, GLuint baseInstance)
Helper function called by the other DrawArrays() functions below.
static void GLAPIENTRY vbo_exec_Rectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
Execute a glRectf() function.
static void GLAPIENTRY vbo_exec_EvalMesh1 (GLenum mode, GLint i1, GLint i2)
static void GLAPIENTRY vbo_exec_EvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
static void GLAPIENTRY vbo_exec_DrawArrays (GLenum mode, GLint start, GLsizei count)
Called from glDrawArrays when in immediate mode (not display list mode).
static void GLAPIENTRY vbo_exec_DrawArraysInstanced (GLenum mode, GLint start, GLsizei count, GLsizei numInstances)
Called from glDrawArraysInstanced when in immediate mode (not display list mode).
static void GLAPIENTRY vbo_exec_DrawArraysInstancedBaseInstance (GLenum mode, GLint first, GLsizei count, GLsizei numInstances, GLuint baseInstance)
Called from glDrawArraysInstancedBaseInstance when in immediate mode.
static void vbo_validated_drawrangeelements (struct gl_context *ctx, GLenum mode, GLboolean index_bounds_valid, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex, GLuint numInstances, GLuint baseInstance)
Map GL_ELEMENT_ARRAY_BUFFER and print contents.
static void GLAPIENTRY vbo_exec_DrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
Called by glDrawRangeElementsBaseVertex() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
Called by glDrawRangeElements() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
Called by glDrawElements() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
Called by glDrawElementsBaseVertex() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawElementsInstanced (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei numInstances)
Called by glDrawElementsInstanced() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawElementsInstancedBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei numInstances, GLint basevertex)
Called by glDrawElementsInstancedBaseVertex() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawElementsInstancedBaseInstance (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei numInstances, GLuint baseInstance)
Called by glDrawElementsInstancedBaseInstance() in immediate mode.
static void GLAPIENTRY vbo_exec_DrawElementsInstancedBaseVertexBaseInstance (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei numInstances, GLint basevertex, GLuint baseInstance)
Called by glDrawElementsInstancedBaseVertexBaseInstance() in immediate mode.
static void vbo_validated_multidrawelements (struct gl_context *ctx, GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount, const GLint *basevertex)
Inner support for both _mesa_MultiDrawElements() and _mesa_MultiDrawRangeElements().
static void GLAPIENTRY vbo_exec_MultiDrawElements (GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount)
static void GLAPIENTRY vbo_exec_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount, const GLsizei *basevertex)
static void vbo_draw_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj, GLuint stream, GLuint numInstances)
static void GLAPIENTRY vbo_exec_DrawTransformFeedback (GLenum mode, GLuint name)
Like DrawArrays, but take the count from a transform feedback object.
static void GLAPIENTRY vbo_exec_DrawTransformFeedbackStream (GLenum mode, GLuint name, GLuint stream)
static void GLAPIENTRY vbo_exec_DrawTransformFeedbackInstanced (GLenum mode, GLuint name, GLsizei primcount)
static void GLAPIENTRY vbo_exec_DrawTransformFeedbackStreamInstanced (GLenum mode, GLuint name, GLuint stream, GLsizei primcount)
static void vbo_validated_drawarraysindirect (struct gl_context *ctx, GLenum mode, const GLvoid *indirect)
static void vbo_validated_multidrawarraysindirect (struct gl_context *ctx, GLenum mode, const GLvoid *indirect, GLsizei primcount, GLsizei stride)
static void vbo_validated_drawelementsindirect (struct gl_context *ctx, GLenum mode, GLenum type, const GLvoid *indirect)
static void vbo_validated_multidrawelementsindirect (struct gl_context *ctx, GLenum mode, GLenum type, const GLvoid *indirect, GLsizei primcount, GLsizei stride)
static void GLAPIENTRY vbo_exec_DrawArraysIndirect (GLenum mode, const GLvoid *indirect)
Like [Multi]DrawArrays/Elements, but they take most arguments from a buffer object.
static void GLAPIENTRY vbo_exec_DrawElementsIndirect (GLenum mode, GLenum type, const GLvoid *indirect)
static void GLAPIENTRY vbo_exec_MultiDrawArraysIndirect (GLenum mode, const GLvoid *indirect, GLsizei primcount, GLsizei stride)
static void GLAPIENTRY vbo_exec_MultiDrawElementsIndirect (GLenum mode, GLenum type, const GLvoid *indirect, GLsizei primcount, GLsizei stride)
static void vbo_validated_multidrawarraysindirectcount (struct gl_context *ctx, GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
static void vbo_validated_multidrawelementsindirectcount (struct gl_context *ctx, GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
static void GLAPIENTRY vbo_exec_MultiDrawArraysIndirectCount (GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
static void GLAPIENTRY vbo_exec_MultiDrawElementsIndirectCount (GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)
void vbo_initialize_exec_dispatch (const struct gl_context *ctx, struct _glapi_table *exec)
Initialize the dispatch table with the VBO functions for drawing.
void GLAPIENTRY _mesa_DrawArrays (GLenum mode, GLint first, GLsizei count)
The following functions are only used for OpenGL ES 1/2 support.
void GLAPIENTRY _mesa_DrawArraysInstanced (GLenum mode, GLint first, GLsizei count, GLsizei primcount)
void GLAPIENTRY _mesa_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
void GLAPIENTRY _mesa_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
void GLAPIENTRY _mesa_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
void GLAPIENTRY _mesa_DrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
void GLAPIENTRY _mesa_MultiDrawElementsEXT (GLenum mode, const GLsizei *count, GLenum type, const GLvoid **indices, GLsizei primcount)
void GLAPIENTRY _mesa_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei *count, GLenum type, const GLvoid **indices, GLsizei primcount, const GLint *basevertex)
void GLAPIENTRY _mesa_DrawTransformFeedback (GLenum mode, GLuint name)
Function Documentation
_mesa_DrawArrays()
void GLAPIENTRY _mesa_DrawArrays (GLenum mode, GLint first, GLsizei count)
The following functions are only used for OpenGL ES 1/2 support.
And some aren't even supported (yet) in ES 1/2.
References vbo_exec_DrawArrays().
_mesa_DrawArraysInstanced()
void GLAPIENTRY _mesa_DrawArraysInstanced (GLenum mode, GLint first, GLsizei count, GLsizei primcount)
References vbo_exec_DrawArraysInstanced().
_mesa_DrawElements()
void GLAPIENTRY _mesa_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
References vbo_exec_DrawElements().
_mesa_DrawElementsBaseVertex()
void GLAPIENTRY _mesa_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex)
References vbo_exec_DrawElementsBaseVertex().
_mesa_DrawRangeElements()
void GLAPIENTRY _mesa_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices)
References vbo_exec_DrawRangeElements().
_mesa_DrawRangeElementsBaseVertex()
void GLAPIENTRY _mesa_DrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex)
References vbo_exec_DrawRangeElementsBaseVertex().
_mesa_DrawTransformFeedback()
void GLAPIENTRY _mesa_DrawTransformFeedback (GLenum mode, GLuint name)
References vbo_exec_DrawTransformFeedback().
_mesa_MultiDrawElementsBaseVertex()
void GLAPIENTRY _mesa_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei * count, GLenum type, const GLvoid ** indices, GLsizei primcount, const GLint * basevertex)
References vbo_exec_MultiDrawElementsBaseVertex().
_mesa_MultiDrawElementsEXT()
void GLAPIENTRY _mesa_MultiDrawElementsEXT (GLenum mode, const GLsizei * count, GLenum type, const GLvoid ** indices, GLsizei primcount)
References vbo_exec_MultiDrawElements().
check_array_data()
static void check_array_data (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint attrib, GLuint j) static
Check that element 'j' of the array has reasonable data.
Map VBO if needed. For debugging purposes; not normally used.
References ADD_POINTERS, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_context::Driver, gl_array_attributes::Enabled, IS_INF_OR_NAN, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, gl_buffer_object::Name, gl_buffer_mapping::Pointer, gl_array_attributes::Ptr, gl_buffer_object::Size, gl_array_attributes::Size, gl_vertex_buffer_binding::Stride, gl_array_attributes::Type, and gl_vertex_array_object::VertexAttrib.
Referenced by check_draw_elements_data().
check_draw_arrays_data()
static void check_draw_arrays_data (struct gl_context * ctx, GLint start, GLsizei count) static
Check array data, looking for NaNs, etc.
Referenced by vbo_exec_DrawArrays(), vbo_exec_DrawArraysInstanced(), and vbo_exec_DrawArraysInstancedBaseInstance().
check_draw_elements_data()
static void check_draw_elements_data (struct gl_context * ctx, GLsizei count, GLenum elemType, const void * elements, GLint basevertex) static
Examine the array's data for NaNs, etc.
For debug purposes; not normally used.
References ADD_POINTERS, gl_context::Array, check_array_data(), gl_context::Driver, GLuint, GLushort, gl_vertex_array_object::IndexBufferObj, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Size, unmap_array_buffer(), dd_function_table::UnmapBuffer, and gl_array_attrib::VAO.
Referenced by vbo_exec_DrawRangeElementsBaseVertex().
print_draw_arrays()
static void print_draw_arrays (struct gl_context * ctx, GLenum mode, GLint start, GLsizei count) static
Print info/data for glDrawArrays(), for debugging.
References gl_context::Array, gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_context::Driver, gl_array_attributes::Enabled, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Name, gl_array_attributes::Ptr, gl_array_attributes::Size, gl_buffer_object::Size, gl_vertex_buffer_binding::Stride, dd_function_table::UnmapBuffer, gl_array_attrib::VAO, and gl_vertex_array_object::VertexAttrib.
Referenced by vbo_exec_DrawArrays(), vbo_exec_DrawArraysInstanced(), and vbo_exec_DrawArraysInstancedBaseInstance().
recalculate_input_bindings()
static void recalculate_input_bindings (struct gl_context * ctx) static
Set the vbo->exec->inputs[] pointers to point to the enabled vertex arrays.
This depends on the current vertex program/shader being executed because of whether or not generic vertex arrays alias the conventional vertex arrays. For arrays that aren't enabled, we set the input[attrib] pointer to point at a zero-stride current value "array".
References _mesa_set_varying_vp_inputs(), gl_vertex_array_object::_VertexAttrib, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_context::Array, vbo_exec_context::array, vbo_context::currval, gl_context::DriverFlags, vbo_context::exec, get_program_mode(), GLuint, vbo_exec_context::inputs, MAT_ATTRIB_MAX, gl_driver_flags::NewArray, gl_context::NewDriverState, gl_array_attrib::VAO, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_MAT_FRONT_AMBIENT, VBO_ATTRIB_POS, vbo_context(), gl_vertex_array_object::VertexAttrib, VP_ARB, and VP_NONE.
Referenced by vbo_bind_arrays().
unmap_array_buffer()
static void unmap_array_buffer (struct gl_context * ctx, struct gl_vertex_array_object * vao, GLuint attrib) static
Unmap the buffer object referenced by given array, if mapped.
References gl_vertex_array_object::BufferBinding, gl_array_attributes::BufferBindingIndex, gl_vertex_buffer_binding::BufferObj, gl_context::Driver, gl_array_attributes::Enabled, MAP_INTERNAL, dd_function_table::UnmapBuffer, and gl_vertex_array_object::VertexAttrib.
Referenced by check_draw_elements_data().
vbo_bind_arrays()
void vbo_bind_arrays (struct gl_context * ctx)
Examine the enabled vertex arrays to set the exec->array.inputs[] values.
These will point to the arrays to actually use for drawing. Some will be user-provided arrays, other will be zero-stride const-valued arrays. Note that this might set the _NEW_VARYING_VP_INPUTS dirty flag so state validation must be done after this call.
References _mesa_update_state(), vbo_exec_context::array, DRAW_ARRAYS, vbo_context::exec, gl_context::NewState, recalculate_input_bindings(), vbo_exec_context::recalculate_inputs, vbo_exec_context::validating, vbo_context(), and vbo_draw_method().
Referenced by vbo_draw_arrays(), vbo_draw_transform_feedback(), vbo_sizeof_ib_type(), vbo_validated_drawarraysindirect(), vbo_validated_drawelementsindirect(), vbo_validated_drawrangeelements(), vbo_validated_multidrawarraysindirect(), vbo_validated_multidrawarraysindirectcount(), vbo_validated_multidrawelements(), vbo_validated_multidrawelementsindirect(), and vbo_validated_multidrawelementsindirectcount().
vbo_draw_arrays()
static void vbo_draw_arrays (struct gl_context * ctx, GLenum mode, GLint start, GLsizei count, GLuint numInstances, GLuint baseInstance) static
Helper function called by the other DrawArrays() functions below.
This is where we handle primitive restart for drawing non-indexed arrays. If primitive restart is enabled, it typically means splitting one DrawArrays() into two.
References _mesa_flush(), _mesa_prim::base_instance, _mesa_prim::begin, _mesa_prim::count, DEBUG_ALWAYS_FLUSH, vbo_context::draw_prims, _mesa_prim::end, _mesa_prim::is_indirect, MESA_DEBUG_FLAGS, _mesa_prim::mode, _mesa_prim::num_instances, _mesa_prim::start, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_draw_transform_feedback(), vbo_exec_DrawArrays(), vbo_exec_DrawArraysInstanced(), and vbo_exec_DrawArraysInstancedBaseInstance().
vbo_draw_transform_feedback()
static void vbo_draw_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj, GLuint stream, GLuint numInstances) static
References _mesa_all_varyings_in_vbos(), _mesa_flush(), _mesa_validate_DrawTransformFeedback(), gl_constants::AlwaysUseGetTransformFeedbackVertexCount, gl_context::Array, _mesa_prim::base_instance, _mesa_prim::begin, gl_context::Const, DEBUG_ALWAYS_FLUSH, vbo_context::draw_prims, gl_context::Driver, _mesa_prim::end, dd_function_table::GetTransformFeedbackVertexCount, _mesa_prim::is_indirect, MESA_DEBUG_FLAGS, _mesa_prim::mode, _mesa_prim::num_instances, gl_array_attrib::VAO, vbo_bind_arrays(), vbo_context(), and vbo_draw_arrays().
Referenced by vbo_exec_DrawTransformFeedback(), vbo_exec_DrawTransformFeedbackInstanced(), vbo_exec_DrawTransformFeedbackStream(), and vbo_exec_DrawTransformFeedbackStreamInstanced().
vbo_exec_DrawArrays()
static void GLAPIENTRY vbo_exec_DrawArrays (GLenum mode, GLint start, GLsizei count) static
Called from glDrawArrays when in immediate mode (not display list mode).
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawArrays(), check_draw_arrays_data(), MESA_VERBOSE, print_draw_arrays(), vbo_draw_arrays(), and VERBOSE_DRAW.
Referenced by _mesa_DrawArrays(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawArraysIndirect()
static void GLAPIENTRY vbo_exec_DrawArraysIndirect (GLenum mode, const GLvoid * indirect) static
Like [Multi]DrawArrays/Elements, but they take most arguments from a buffer object.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawArraysIndirect(), MESA_VERBOSE, vbo_validated_drawarraysindirect(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawArraysInstanced()
static void GLAPIENTRY vbo_exec_DrawArraysInstanced (GLenum mode, GLint start, GLsizei count, GLsizei numInstances) static
Called from glDrawArraysInstanced when in immediate mode (not display list mode).
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawArraysInstanced(), check_draw_arrays_data(), MESA_VERBOSE, print_draw_arrays(), vbo_draw_arrays(), and VERBOSE_DRAW.
Referenced by _mesa_DrawArraysInstanced(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawArraysInstancedBaseInstance()
static void GLAPIENTRY vbo_exec_DrawArraysInstancedBaseInstance (GLenum mode, GLint first, GLsizei count, GLsizei numInstances, GLuint baseInstance) static
Called from glDrawArraysInstancedBaseInstance when in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawArraysInstanced(), gl_context::Array, check_draw_arrays_data(), gl_context::Driver, GLuint, GLushort, gl_vertex_array_object::IndexBufferObj, MAP_INTERNAL, dd_function_table::MapBufferRange, MESA_VERBOSE, print_draw_arrays(), gl_buffer_object::Size, dd_function_table::UnmapBuffer, gl_array_attrib::VAO, vbo_draw_arrays(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawElements()
static void GLAPIENTRY vbo_exec_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices) static
Called by glDrawElements() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElements(), MESA_VERBOSE, vbo_validated_drawrangeelements(), and VERBOSE_DRAW.
Referenced by _mesa_DrawElements(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawElementsBaseVertex()
static void GLAPIENTRY vbo_exec_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex) static
Called by glDrawElementsBaseVertex() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElements(), MESA_VERBOSE, vbo_validated_drawrangeelements(), and VERBOSE_DRAW.
Referenced by _mesa_DrawElementsBaseVertex(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawElementsIndirect()
static void GLAPIENTRY vbo_exec_DrawElementsIndirect (GLenum mode, GLenum type, const GLvoid * indirect) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElementsIndirect(), MESA_VERBOSE, vbo_validated_drawelementsindirect(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawElementsInstanced()
static void GLAPIENTRY vbo_exec_DrawElementsInstanced (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLsizei numInstances) static
Called by glDrawElementsInstanced() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElementsInstanced(), MESA_VERBOSE, vbo_validated_drawrangeelements(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawElementsInstancedBaseInstance()
static void GLAPIENTRY vbo_exec_DrawElementsInstancedBaseInstance (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLsizei numInstances, GLuint baseInstance) static
Called by glDrawElementsInstancedBaseInstance() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElementsInstanced(), MESA_VERBOSE, vbo_validated_drawrangeelements(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawElementsInstancedBaseVertex()
static void GLAPIENTRY vbo_exec_DrawElementsInstancedBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLsizei numInstances, GLint basevertex) static
Called by glDrawElementsInstancedBaseVertex() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElementsInstanced(), MESA_VERBOSE, vbo_validated_drawrangeelements(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawElementsInstancedBaseVertexBaseInstance()
static void GLAPIENTRY vbo_exec_DrawElementsInstancedBaseVertexBaseInstance (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLsizei numInstances, GLint basevertex, GLuint baseInstance) static
Called by glDrawElementsInstancedBaseVertexBaseInstance() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawElementsInstanced(), MESA_VERBOSE, vbo_validated_drawrangeelements(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawRangeElements()
static void GLAPIENTRY vbo_exec_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices) static
Called by glDrawRangeElements() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), MESA_VERBOSE, vbo_exec_DrawRangeElementsBaseVertex(), and VERBOSE_DRAW.
Referenced by _mesa_DrawRangeElements(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawRangeElementsBaseVertex()
static void GLAPIENTRY vbo_exec_DrawRangeElementsBaseVertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex) static
Called by glDrawRangeElementsBaseVertex() in immediate mode.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_DrawRangeElements(), _mesa_warning(), gl_context::Array, check_draw_elements_data(), GLuint, gl_vertex_array_object::IndexBufferObj, MESA_VERBOSE, gl_buffer_object::Name, gl_array_attrib::VAO, vbo_validated_drawrangeelements(), VERBOSE_DRAW, and void.
Referenced by _mesa_DrawRangeElementsBaseVertex(), vbo_exec_DrawRangeElements(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawTransformFeedback()
static void GLAPIENTRY vbo_exec_DrawTransformFeedback (GLenum mode, GLuint name) static
Like DrawArrays, but take the count from a transform feedback object.
Parameters
mode GL_POINTS, GL_LINES, GL_TRIANGLE_STRIP, etc.
name the transform feedback object User still has to setup of the vertex attribute info with glVertexPointer, glColorPointer, etc. Part of GL_ARB_transform_feedback2.
References _mesa_debug(), _mesa_enum_to_string(), _mesa_lookup_transform_feedback_object(), MESA_VERBOSE, vbo_draw_transform_feedback(), and VERBOSE_DRAW.
Referenced by _mesa_DrawTransformFeedback(), and vbo_initialize_exec_dispatch().
vbo_exec_DrawTransformFeedbackInstanced()
static void GLAPIENTRY vbo_exec_DrawTransformFeedbackInstanced (GLenum mode, GLuint name, GLsizei primcount) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_lookup_transform_feedback_object(), MESA_VERBOSE, vbo_draw_transform_feedback(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawTransformFeedbackStream()
static void GLAPIENTRY vbo_exec_DrawTransformFeedbackStream (GLenum mode, GLuint name, GLuint stream) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_lookup_transform_feedback_object(), MESA_VERBOSE, vbo_draw_transform_feedback(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_DrawTransformFeedbackStreamInstanced()
static void GLAPIENTRY vbo_exec_DrawTransformFeedbackStreamInstanced (GLenum mode, GLuint name, GLuint stream, GLsizei primcount) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_lookup_transform_feedback_object(), MESA_VERBOSE, vbo_draw_transform_feedback(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_EvalMesh1()
static void GLAPIENTRY vbo_exec_EvalMesh1 (GLenum mode, GLint i1, GLint i2) static
References _mesa_error().
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_EvalMesh2()
static void GLAPIENTRY vbo_exec_EvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2) static
References _mesa_error().
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_MultiDrawArraysIndirect()
static void GLAPIENTRY vbo_exec_MultiDrawArraysIndirect (GLenum mode, const GLvoid * indirect, GLsizei primcount, GLsizei stride) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_MultiDrawArraysIndirect(), GLuint, MESA_VERBOSE, vbo_validated_multidrawarraysindirect(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_MultiDrawArraysIndirectCount()
static void GLAPIENTRY vbo_exec_MultiDrawArraysIndirectCount (GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_MultiDrawArraysIndirectCount(), GLuint, MESA_VERBOSE, vbo_validated_multidrawarraysindirectcount(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_MultiDrawElements()
static void GLAPIENTRY vbo_exec_MultiDrawElements (GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount) static
References _mesa_validate_MultiDrawElements(), and vbo_validated_multidrawelements().
Referenced by _mesa_MultiDrawElementsEXT(), and vbo_initialize_exec_dispatch().
vbo_exec_MultiDrawElementsBaseVertex()
static void GLAPIENTRY vbo_exec_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount, const GLsizei * basevertex) static
References _mesa_validate_MultiDrawElements(), and vbo_validated_multidrawelements().
Referenced by _mesa_MultiDrawElementsBaseVertex(), and vbo_initialize_exec_dispatch().
vbo_exec_MultiDrawElementsIndirect()
static void GLAPIENTRY vbo_exec_MultiDrawElementsIndirect (GLenum mode, GLenum type, const GLvoid * indirect, GLsizei primcount, GLsizei stride) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_MultiDrawElementsIndirect(), GLuint, MESA_VERBOSE, vbo_validated_multidrawelementsindirect(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_MultiDrawElementsIndirectCount()
static void GLAPIENTRY vbo_exec_MultiDrawElementsIndirectCount (GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride) static
References _mesa_debug(), _mesa_enum_to_string(), _mesa_validate_MultiDrawElementsIndirectCount(), GLuint, MESA_VERBOSE, vbo_validated_multidrawelementsindirectcount(), and VERBOSE_DRAW.
Referenced by vbo_initialize_exec_dispatch().
vbo_exec_Rectf()
static void GLAPIENTRY vbo_exec_Rectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2) static
Execute a glRectf() function.
References ASSERT_OUTSIDE_BEGIN_END.
Referenced by vbo_initialize_exec_dispatch().
vbo_initialize_exec_dispatch()
void vbo_initialize_exec_dispatch (const struct gl_context * ctx, struct _glapi_table * exec)
Initialize the dispatch table with the VBO functions for drawing.
References gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, gl_extensions::ARB_draw_elements_base_vertex, gl_context::Extensions, vbo_exec_DrawArrays(), vbo_exec_DrawArraysIndirect(), vbo_exec_DrawArraysInstanced(), vbo_exec_DrawArraysInstancedBaseInstance(), vbo_exec_DrawElements(), vbo_exec_DrawElementsBaseVertex(), vbo_exec_DrawElementsIndirect(), vbo_exec_DrawElementsInstanced(), vbo_exec_DrawElementsInstancedBaseInstance(), vbo_exec_DrawElementsInstancedBaseVertex(), vbo_exec_DrawElementsInstancedBaseVertexBaseInstance(), vbo_exec_DrawRangeElements(), vbo_exec_DrawRangeElementsBaseVertex(), vbo_exec_DrawTransformFeedback(), vbo_exec_DrawTransformFeedbackInstanced(), vbo_exec_DrawTransformFeedbackStream(), vbo_exec_DrawTransformFeedbackStreamInstanced(), vbo_exec_EvalMesh1(), vbo_exec_EvalMesh2(), vbo_exec_MultiDrawArraysIndirect(), vbo_exec_MultiDrawArraysIndirectCount(), vbo_exec_MultiDrawElements(), vbo_exec_MultiDrawElementsBaseVertex(), vbo_exec_MultiDrawElementsIndirect(), vbo_exec_MultiDrawElementsIndirectCount(), and vbo_exec_Rectf().
vbo_validated_drawarraysindirect()
static void vbo_validated_drawarraysindirect (struct gl_context * ctx, GLenum mode, const GLvoid * indirect) static
References _mesa_flush(), DEBUG_ALWAYS_FLUSH, vbo_context::draw_indirect_prims, gl_context::DrawIndirectBuffer, MESA_DEBUG_FLAGS, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_exec_DrawArraysIndirect().
vbo_validated_drawelementsindirect()
static void vbo_validated_drawelementsindirect (struct gl_context * ctx, GLenum mode, GLenum type, const GLvoid * indirect) static
References _mesa_flush(), gl_context::Array, _mesa_index_buffer::count, DEBUG_ALWAYS_FLUSH, vbo_context::draw_indirect_prims, gl_context::DrawIndirectBuffer, gl_vertex_array_object::IndexBufferObj, MESA_DEBUG_FLAGS, _mesa_index_buffer::obj, _mesa_index_buffer::ptr, _mesa_index_buffer::type, gl_array_attrib::VAO, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_exec_DrawElementsIndirect().
vbo_validated_drawrangeelements()
static void vbo_validated_drawrangeelements (struct gl_context * ctx, GLenum mode, GLboolean index_bounds_valid, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex, GLuint numInstances, GLuint baseInstance) static
Map GL_ELEMENT_ARRAY_BUFFER and print contents.
For debugging. Inner support for both _mesa_DrawElements and _mesa_DrawRangeElements. Do the rendering for a glDrawElements or glDrawRangeElements call after we've validated buffer bounds, etc.
References _mesa_flush(), gl_context::Array, _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::begin, _mesa_prim::count, _mesa_index_buffer::count, DEBUG_ALWAYS_FLUSH, _mesa_prim::draw_id, vbo_context::draw_prims, _mesa_prim::end, gl_vertex_array_object::IndexBufferObj, _mesa_prim::indexed, _mesa_prim::is_indirect, MESA_DEBUG_FLAGS, _mesa_prim::mode, _mesa_prim::num_instances, _mesa_index_buffer::obj, _mesa_prim::pad, _mesa_index_buffer::ptr, _mesa_prim::start, _mesa_index_buffer::type, gl_array_attrib::VAO, vbo_bind_arrays(), vbo_context(), and _mesa_prim::weak.
Referenced by vbo_exec_DrawElements(), vbo_exec_DrawElementsBaseVertex(), vbo_exec_DrawElementsInstanced(), vbo_exec_DrawElementsInstancedBaseInstance(), vbo_exec_DrawElementsInstancedBaseVertex(), vbo_exec_DrawElementsInstancedBaseVertexBaseInstance(), and vbo_exec_DrawRangeElementsBaseVertex().
vbo_validated_multidrawarraysindirect()
static void vbo_validated_multidrawarraysindirect (struct gl_context * ctx, GLenum mode, const GLvoid * indirect, GLsizei primcount, GLsizei stride) static
References _mesa_flush(), DEBUG_ALWAYS_FLUSH, vbo_context::draw_indirect_prims, gl_context::DrawIndirectBuffer, MESA_DEBUG_FLAGS, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_exec_MultiDrawArraysIndirect().
vbo_validated_multidrawarraysindirectcount()
static void vbo_validated_multidrawarraysindirectcount (struct gl_context * ctx, GLenum mode, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride) static
References _mesa_flush(), DEBUG_ALWAYS_FLUSH, vbo_context::draw_indirect_prims, gl_context::DrawIndirectBuffer, MESA_DEBUG_FLAGS, gl_context::ParameterBuffer, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_exec_MultiDrawArraysIndirectCount().
vbo_validated_multidrawelements()
static void vbo_validated_multidrawelements (struct gl_context * ctx, GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount, const GLint * basevertex) static
Inner support for both _mesa_MultiDrawElements() and _mesa_MultiDrawRangeElements().
This does the actual rendering after we've checked array indexes, etc.
References _mesa_error(), _mesa_flush(), gl_context::Array, _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::begin, _mesa_prim::count, _mesa_index_buffer::count, DEBUG_ALWAYS_FLUSH, _mesa_prim::draw_id, vbo_context::draw_prims, _mesa_prim::end, gl_vertex_array_object::IndexBufferObj, _mesa_prim::indexed, _mesa_prim::is_indirect, MESA_DEBUG_FLAGS, _mesa_prim::mode, _mesa_prim::num_instances, _mesa_index_buffer::obj, _mesa_prim::pad, _mesa_index_buffer::ptr, _mesa_prim::start, _mesa_index_buffer::type, gl_array_attrib::VAO, vbo_bind_arrays(), vbo_context(), vbo_sizeof_ib_type(), and _mesa_prim::weak.
Referenced by vbo_exec_MultiDrawElements(), and vbo_exec_MultiDrawElementsBaseVertex().
vbo_validated_multidrawelementsindirect()
static void vbo_validated_multidrawelementsindirect (struct gl_context * ctx, GLenum mode, GLenum type, const GLvoid * indirect, GLsizei primcount, GLsizei stride) static
References _mesa_flush(), gl_context::Array, _mesa_index_buffer::count, DEBUG_ALWAYS_FLUSH, vbo_context::draw_indirect_prims, gl_context::DrawIndirectBuffer, gl_vertex_array_object::IndexBufferObj, MESA_DEBUG_FLAGS, _mesa_index_buffer::obj, _mesa_index_buffer::ptr, _mesa_index_buffer::type, gl_array_attrib::VAO, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_exec_MultiDrawElementsIndirect().
vbo_validated_multidrawelementsindirectcount()
static void vbo_validated_multidrawelementsindirectcount (struct gl_context * ctx, GLenum mode, GLenum type, GLintptr indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride) static
References _mesa_flush(), gl_context::Array, _mesa_index_buffer::count, DEBUG_ALWAYS_FLUSH, vbo_context::draw_indirect_prims, gl_context::DrawIndirectBuffer, gl_vertex_array_object::IndexBufferObj, MESA_DEBUG_FLAGS, _mesa_index_buffer::obj, gl_context::ParameterBuffer, _mesa_index_buffer::ptr, _mesa_index_buffer::type, gl_array_attrib::VAO, vbo_bind_arrays(), and vbo_context().
Referenced by vbo_exec_MultiDrawElementsIndirectCount().