Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_split_copy.c File Reference
#include <stdio.h>
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/imports.h"
#include "main/glformats.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "vbo_split.h"
#include "vbo.h"
Data Structures
struct copy_context
Used for vertex-level splitting of indexed buffers.
Macros
#define ELT_TABLE_SIZE 16
#define MAX_PRIM 32
Functions
static GLuint attr_size (const struct gl_vertex_array *array)
static GLboolean check_flush (struct copy_context *copy)
Starts returning true slightly before the buffer fills, to ensure that there is sufficient room for any remaining vertices to finish off the prim:
static void dump_draw_info (struct gl_context *ctx, const struct gl_vertex_array **arrays, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index)
Dump the parameters/info for a vbo->draw() call.
static void flush (struct copy_context *copy)
static void begin (struct copy_context *copy, GLenum mode, GLboolean begin_flag)
Called at begin of each primitive during replay.
static GLuint elt (struct copy_context *copy, GLuint elt_idx)
Use a hashtable to attempt to identify recently-emitted vertices and avoid re-emitting them.
static void end (struct copy_context *copy, GLboolean end_flag)
Called at end of each primitive during replay.
static void replay_elts (struct copy_context *copy)
static void replay_init (struct copy_context *copy)
static void replay_finish (struct copy_context *copy)
Free up everything allocated during split/replay.
void vbo_split_copy (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, vbo_draw_func draw, const struct split_limits *limits)
Split VBO into smaller pieces, draw the pieces.
Macro Definition Documentation
ELT_TABLE_SIZE
#define ELT_TABLE_SIZE 16
Referenced by elt(), flush(), and vbo_split_copy().
MAX_PRIM
#define MAX_PRIM 32
Referenced by end().
Function Documentation
attr_size()
static GLuint attr_size (const struct gl_vertex_array * array) static
References _mesa_sizeof_type(), GLuint, gl_vertex_array::Size, and gl_vertex_array::Type.
Referenced by replay_init().
begin()
static void begin (struct copy_context * copy, GLenum mode, GLboolean begin_flag) static
Called at begin of each primitive during replay.
References _mesa_prim::begin, copy_context::dstprim, copy_context::dstprim_nr, GLuint, _mesa_prim::mode, _mesa_prim::num_instances, and copy_context::prim.
Referenced by replay_elts().
check_flush()
static GLboolean check_flush (struct copy_context * copy) static
Starts returning true slightly before the buffer fills, to ensure that there is sufficient room for any remaining vertices to finish off the prim:
References copy_context::dstbuf_nr, copy_context::dstbuf_size, copy_context::dstelt_nr, copy_context::dstelt_size, copy_context::dstprim, copy_context::dstprim_nr, and _mesa_prim::mode.
Referenced by elt(), and end().
dump_draw_info()
static void dump_draw_info (struct gl_context * ctx, const struct gl_vertex_array ** arrays, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index) static
Dump the parameters/info for a vbo->draw() call.
References _mesa_prim::count, GLuint, _mesa_prim::mode, copy_context::nr_prims, and _mesa_prim::start.
Referenced by flush().
elt()
static GLuint elt (struct copy_context * copy, GLuint elt_idx) static
Use a hashtable to attempt to identify recently-emitted vertices and avoid re-emitting them.
References copy_context::array, _mesa_prim::basevertex, check_flush(), copy_context::dstbuf, copy_context::dstbuf_nr, copy_context::dstelt, copy_context::dstelt_nr, copy_context::dstptr, ELT_TABLE_SIZE, GLuint, copy_context::in, IS_INF_OR_NAN, copy_context::nr_varying, copy_context::out, copy_context::prim, gl_vertex_array::Size, copy_context::size, copy_context::src_ptr, copy_context::srcelt, gl_vertex_array::StrideB, gl_vertex_array::Type, copy_context::varying, copy_context::vert_cache, and copy_context::vertex_size.
Referenced by replay_elts().
end()
static void end (struct copy_context * copy, GLboolean end_flag) static
Called at end of each primitive during replay.
References check_flush(), _mesa_prim::count, copy_context::dstelt_nr, copy_context::dstprim, copy_context::dstprim_nr, _mesa_prim::end, flush(), MAX_PRIM, copy_context::prim, and _mesa_prim::start.
Referenced by loopback_prim(), replay_elts(), and vbo_save_playback_vertex_list().
flush()
static void flush (struct copy_context * copy) static
References gl_array_attrib::_DrawArrays, gl_context::Array, _mesa_index_buffer::count, copy_context::ctx, copy_context::draw, gl_context::DriverFlags, copy_context::dstarray_ptr, copy_context::dstbuf, copy_context::dstbuf_nr, copy_context::dstelt_nr, copy_context::dstib, copy_context::dstprim, copy_context::dstprim_nr, copy_context::dstptr, dump_draw_info(), ELT_TABLE_SIZE, GLuint, copy_context::in, gl_driver_flags::NewArray, gl_context::NewDriverState, copy_context::vert_cache, and void.
Referenced by end(), and replay_elts().
replay_elts()
static void replay_elts (struct copy_context * copy) static
References _mesa_prim::begin, begin(), _mesa_prim::count, copy_context::dstprim_nr, elt(), _mesa_prim::end, end(), flush(), GLuint, _mesa_prim::mode, copy_context::nr_prims, copy_context::prim, split_prim_inplace(), _mesa_prim::start, and void.
Referenced by vbo_split_copy().
replay_finish()
static void replay_finish (struct copy_context * copy) static
Free up everything allocated during split/replay.
References copy_context::array, gl_vertex_array::BufferObj, copy_context::ctx, gl_context::Driver, copy_context::dstbuf, copy_context::dstelt, GLuint, copy_context::ib, MAP_INTERNAL, copy_context::nr_varying, _mesa_index_buffer::obj, copy_context::translated_elt_buf, dd_function_table::UnmapBuffer, and copy_context::varying.
Referenced by vbo_split_copy().
replay_init()
static void replay_init (struct copy_context * copy) static
References gl_vertex_array::_ElementSize, ADD_POINTERS, copy_context::array, copy_context::attr, attr_size(), gl_vertex_array::BufferObj, _mesa_index_buffer::count, copy_context::ctx, gl_vertex_array::Doubles, gl_context::Driver, copy_context::dstarray, copy_context::dstarray_ptr, copy_context::dstbuf, copy_context::dstbuf_size, copy_context::dstelt, copy_context::dstelt_nr, copy_context::dstelt_size, copy_context::dstib, copy_context::dstptr, gl_vertex_array::Format, GLuint, GLushort, copy_context::ib, gl_vertex_array::Integer, copy_context::limits, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, split_limits::max_indices, split_limits::max_vb_size, split_limits::max_verts, gl_vertex_array::Normalized, copy_context::nr_varying, gl_shared_state::NullBufferObj, _mesa_index_buffer::obj, gl_buffer_mapping::Pointer, gl_vertex_array::Ptr, _mesa_index_buffer::ptr, gl_context::Shared, gl_buffer_object::Size, gl_vertex_array::Size, copy_context::size, copy_context::src_ptr, copy_context::srcelt, gl_vertex_array::StrideB, copy_context::translated_elt_buf, gl_vertex_array::Type, _mesa_index_buffer::type, copy_context::varying, and copy_context::vertex_size.
Referenced by vbo_split_copy().
vbo_split_copy()
void vbo_split_copy (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, vbo_draw_func draw, const struct split_limits * limits)
Split VBO into smaller pieces, draw the pieces.
References copy_context::array, copy_context::ctx, copy_context::draw, ELT_TABLE_SIZE, GLuint, copy_context::ib, copy_context::in, copy_context::limits, copy_context::nr_prims, copy_context::prim, replay_elts(), replay_finish(), replay_init(), and copy_context::vert_cache.
Referenced by split_prims(), and vbo_split_prims().