Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_noop.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/dlist.h"
#include "main/eval.h"
#include "vbo/vbo_noop.h"
Functions
static void GLAPIENTRY _mesa_noop_EdgeFlag (GLboolean b)
GLvertexformat no-op functions.
static void GLAPIENTRY _mesa_noop_Indexf (GLfloat f)
static void GLAPIENTRY _mesa_noop_Indexfv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_FogCoordfEXT (GLfloat a)
static void GLAPIENTRY _mesa_noop_FogCoordfvEXT (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Normal3f (GLfloat a, GLfloat b, GLfloat c)
static void GLAPIENTRY _mesa_noop_Normal3fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Color4f (GLfloat a, GLfloat b, GLfloat c, GLfloat d)
static void GLAPIENTRY _mesa_noop_Color4fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Color3f (GLfloat a, GLfloat b, GLfloat c)
static void GLAPIENTRY _mesa_noop_Color3fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_MultiTexCoord1fARB (GLenum target, GLfloat a)
static void GLAPIENTRY _mesa_noop_MultiTexCoord1fvARB (GLenum target, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_MultiTexCoord2fARB (GLenum target, GLfloat a, GLfloat b)
static void GLAPIENTRY _mesa_noop_MultiTexCoord2fvARB (GLenum target, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_MultiTexCoord3fARB (GLenum target, GLfloat a, GLfloat b, GLfloat c)
static void GLAPIENTRY _mesa_noop_MultiTexCoord3fvARB (GLenum target, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_MultiTexCoord4fARB (GLenum target, GLfloat a, GLfloat b, GLfloat c, GLfloat d)
static void GLAPIENTRY _mesa_noop_MultiTexCoord4fvARB (GLenum target, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_SecondaryColor3fEXT (GLfloat a, GLfloat b, GLfloat c)
static void GLAPIENTRY _mesa_noop_SecondaryColor3fvEXT (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_TexCoord1f (GLfloat a)
static void GLAPIENTRY _mesa_noop_TexCoord1fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_TexCoord2f (GLfloat a, GLfloat b)
static void GLAPIENTRY _mesa_noop_TexCoord2fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_TexCoord3f (GLfloat a, GLfloat b, GLfloat c)
static void GLAPIENTRY _mesa_noop_TexCoord3fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_TexCoord4f (GLfloat a, GLfloat b, GLfloat c, GLfloat d)
static void GLAPIENTRY _mesa_noop_TexCoord4fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib1fNV (GLuint index, GLfloat x)
static void GLAPIENTRY _mesa_noop_VertexAttrib1fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib2fNV (GLuint index, GLfloat x, GLfloat y)
static void GLAPIENTRY _mesa_noop_VertexAttrib2fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib3fNV (GLuint index, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY _mesa_noop_VertexAttrib3fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib4fNV (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY _mesa_noop_VertexAttrib4fvNV (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib1fARB (GLuint index, GLfloat x)
static void GLAPIENTRY _mesa_noop_VertexAttrib1fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib2fARB (GLuint index, GLfloat x, GLfloat y)
static void GLAPIENTRY _mesa_noop_VertexAttrib2fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib3fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z)
static void GLAPIENTRY _mesa_noop_VertexAttrib3fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_VertexAttrib4fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
static void GLAPIENTRY _mesa_noop_VertexAttrib4fvARB (GLuint index, const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Materialfv (GLenum face, GLenum pname, const GLfloat *params)
static void GLAPIENTRY _mesa_noop_Vertex2fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Vertex3fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Vertex4fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_Vertex2f (GLfloat a, GLfloat b)
static void GLAPIENTRY _mesa_noop_Vertex3f (GLfloat a, GLfloat b, GLfloat c)
static void GLAPIENTRY _mesa_noop_Vertex4f (GLfloat a, GLfloat b, GLfloat c, GLfloat d)
static void GLAPIENTRY _mesa_noop_EvalCoord1f (GLfloat a)
static void GLAPIENTRY _mesa_noop_EvalCoord1fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_EvalCoord2f (GLfloat a, GLfloat b)
static void GLAPIENTRY _mesa_noop_EvalCoord2fv (const GLfloat *v)
static void GLAPIENTRY _mesa_noop_EvalPoint1 (GLint a)
static void GLAPIENTRY _mesa_noop_EvalPoint2 (GLint a, GLint b)
static void GLAPIENTRY _mesa_noop_ArrayElement (GLint elem)
static void GLAPIENTRY _mesa_noop_Begin (GLenum mode)
static void GLAPIENTRY _mesa_noop_End (void)
static void GLAPIENTRY _mesa_noop_PrimitiveRestartNV (void)
void _mesa_noop_vtxfmt_init (GLvertexformat *vfmt)
Build a vertexformat of functions that are no-ops.
GLboolean _mesa_using_noop_vtxfmt (const struct _glapi_table *dispatch)
Is the given dispatch table using the no-op functions?
Function Documentation
_mesa_noop_ArrayElement()
static void GLAPIENTRY _mesa_noop_ArrayElement (GLint elem) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Begin()
static void GLAPIENTRY _mesa_noop_Begin (GLenum mode) static
Referenced by _mesa_noop_vtxfmt_init(), and _mesa_using_noop_vtxfmt().
_mesa_noop_Color3f()
static void GLAPIENTRY _mesa_noop_Color3f (GLfloat a, GLfloat b, GLfloat c) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Color3fv()
static void GLAPIENTRY _mesa_noop_Color3fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Color4f()
static void GLAPIENTRY _mesa_noop_Color4f (GLfloat a, GLfloat b, GLfloat c, GLfloat d) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Color4fv()
static void GLAPIENTRY _mesa_noop_Color4fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EdgeFlag()
static void GLAPIENTRY _mesa_noop_EdgeFlag (GLboolean b) static
GLvertexformat no-op functions.
Used in out-of-memory situations.
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_End()
static void GLAPIENTRY _mesa_noop_End (void) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EvalCoord1f()
static void GLAPIENTRY _mesa_noop_EvalCoord1f (GLfloat a) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EvalCoord1fv()
static void GLAPIENTRY _mesa_noop_EvalCoord1fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EvalCoord2f()
static void GLAPIENTRY _mesa_noop_EvalCoord2f (GLfloat a, GLfloat b) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EvalCoord2fv()
static void GLAPIENTRY _mesa_noop_EvalCoord2fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EvalPoint1()
static void GLAPIENTRY _mesa_noop_EvalPoint1 (GLint a) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_EvalPoint2()
static void GLAPIENTRY _mesa_noop_EvalPoint2 (GLint a, GLint b) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_FogCoordfEXT()
static void GLAPIENTRY _mesa_noop_FogCoordfEXT (GLfloat a) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_FogCoordfvEXT()
static void GLAPIENTRY _mesa_noop_FogCoordfvEXT (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Indexf()
static void GLAPIENTRY _mesa_noop_Indexf (GLfloat f) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Indexfv()
static void GLAPIENTRY _mesa_noop_Indexfv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Materialfv()
static void GLAPIENTRY _mesa_noop_Materialfv (GLenum face, GLenum pname, const GLfloat * params) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord1fARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord1fARB (GLenum target, GLfloat a) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord1fvARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord1fvARB (GLenum target, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord2fARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord2fARB (GLenum target, GLfloat a, GLfloat b) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord2fvARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord2fvARB (GLenum target, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord3fARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord3fARB (GLenum target, GLfloat a, GLfloat b, GLfloat c) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord3fvARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord3fvARB (GLenum target, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord4fARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord4fARB (GLenum target, GLfloat a, GLfloat b, GLfloat c, GLfloat d) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_MultiTexCoord4fvARB()
static void GLAPIENTRY _mesa_noop_MultiTexCoord4fvARB (GLenum target, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Normal3f()
static void GLAPIENTRY _mesa_noop_Normal3f (GLfloat a, GLfloat b, GLfloat c) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Normal3fv()
static void GLAPIENTRY _mesa_noop_Normal3fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_PrimitiveRestartNV()
static void GLAPIENTRY _mesa_noop_PrimitiveRestartNV (void) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_SecondaryColor3fEXT()
static void GLAPIENTRY _mesa_noop_SecondaryColor3fEXT (GLfloat a, GLfloat b, GLfloat c) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_SecondaryColor3fvEXT()
static void GLAPIENTRY _mesa_noop_SecondaryColor3fvEXT (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord1f()
static void GLAPIENTRY _mesa_noop_TexCoord1f (GLfloat a) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord1fv()
static void GLAPIENTRY _mesa_noop_TexCoord1fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord2f()
static void GLAPIENTRY _mesa_noop_TexCoord2f (GLfloat a, GLfloat b) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord2fv()
static void GLAPIENTRY _mesa_noop_TexCoord2fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord3f()
static void GLAPIENTRY _mesa_noop_TexCoord3f (GLfloat a, GLfloat b, GLfloat c) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord3fv()
static void GLAPIENTRY _mesa_noop_TexCoord3fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord4f()
static void GLAPIENTRY _mesa_noop_TexCoord4f (GLfloat a, GLfloat b, GLfloat c, GLfloat d) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_TexCoord4fv()
static void GLAPIENTRY _mesa_noop_TexCoord4fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Vertex2f()
static void GLAPIENTRY _mesa_noop_Vertex2f (GLfloat a, GLfloat b) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Vertex2fv()
static void GLAPIENTRY _mesa_noop_Vertex2fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Vertex3f()
static void GLAPIENTRY _mesa_noop_Vertex3f (GLfloat a, GLfloat b, GLfloat c) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Vertex3fv()
static void GLAPIENTRY _mesa_noop_Vertex3fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Vertex4f()
static void GLAPIENTRY _mesa_noop_Vertex4f (GLfloat a, GLfloat b, GLfloat c, GLfloat d) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_Vertex4fv()
static void GLAPIENTRY _mesa_noop_Vertex4fv (const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib1fARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib1fARB (GLuint index, GLfloat x) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib1fNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib1fNV (GLuint index, GLfloat x) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib1fvARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib1fvARB (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib1fvNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib1fvNV (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib2fARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib2fARB (GLuint index, GLfloat x, GLfloat y) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib2fNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib2fNV (GLuint index, GLfloat x, GLfloat y) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib2fvARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib2fvARB (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib2fvNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib2fvNV (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib3fARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib3fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib3fNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib3fNV (GLuint index, GLfloat x, GLfloat y, GLfloat z) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib3fvARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib3fvARB (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib3fvNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib3fvNV (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib4fARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib4fARB (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib4fNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib4fNV (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib4fvARB()
static void GLAPIENTRY _mesa_noop_VertexAttrib4fvARB (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_VertexAttrib4fvNV()
static void GLAPIENTRY _mesa_noop_VertexAttrib4fvNV (GLuint index, const GLfloat * v) static
Referenced by _mesa_noop_vtxfmt_init().
_mesa_noop_vtxfmt_init()
void _mesa_noop_vtxfmt_init (GLvertexformat * vfmt)
Build a vertexformat of functions that are no-ops.
These are used in out-of-memory situations when we have no VBO to put the vertex data into.
References _mesa_CallList(), _mesa_CallLists(), _mesa_noop_ArrayElement(), _mesa_noop_Begin(), _mesa_noop_Color3f(), _mesa_noop_Color3fv(), _mesa_noop_Color4f(), _mesa_noop_Color4fv(), _mesa_noop_EdgeFlag(), _mesa_noop_End(), _mesa_noop_EvalCoord1f(), _mesa_noop_EvalCoord1fv(), _mesa_noop_EvalCoord2f(), _mesa_noop_EvalCoord2fv(), _mesa_noop_EvalPoint1(), _mesa_noop_EvalPoint2(), _mesa_noop_FogCoordfEXT(), _mesa_noop_FogCoordfvEXT(), _mesa_noop_Indexf(), _mesa_noop_Indexfv(), _mesa_noop_Materialfv(), _mesa_noop_MultiTexCoord1fARB(), _mesa_noop_MultiTexCoord1fvARB(), _mesa_noop_MultiTexCoord2fARB(), _mesa_noop_MultiTexCoord2fvARB(), _mesa_noop_MultiTexCoord3fARB(), _mesa_noop_MultiTexCoord3fvARB(), _mesa_noop_MultiTexCoord4fARB(), _mesa_noop_MultiTexCoord4fvARB(), _mesa_noop_Normal3f(), _mesa_noop_Normal3fv(), _mesa_noop_PrimitiveRestartNV(), _mesa_noop_SecondaryColor3fEXT(), _mesa_noop_SecondaryColor3fvEXT(), _mesa_noop_TexCoord1f(), _mesa_noop_TexCoord1fv(), _mesa_noop_TexCoord2f(), _mesa_noop_TexCoord2fv(), _mesa_noop_TexCoord3f(), _mesa_noop_TexCoord3fv(), _mesa_noop_TexCoord4f(), _mesa_noop_TexCoord4fv(), _mesa_noop_Vertex2f(), _mesa_noop_Vertex2fv(), _mesa_noop_Vertex3f(), _mesa_noop_Vertex3fv(), _mesa_noop_Vertex4f(), _mesa_noop_Vertex4fv(), _mesa_noop_VertexAttrib1fARB(), _mesa_noop_VertexAttrib1fNV(), _mesa_noop_VertexAttrib1fvARB(), _mesa_noop_VertexAttrib1fvNV(), _mesa_noop_VertexAttrib2fARB(), _mesa_noop_VertexAttrib2fNV(), _mesa_noop_VertexAttrib2fvARB(), _mesa_noop_VertexAttrib2fvNV(), _mesa_noop_VertexAttrib3fARB(), _mesa_noop_VertexAttrib3fNV(), _mesa_noop_VertexAttrib3fvARB(), _mesa_noop_VertexAttrib3fvNV(), _mesa_noop_VertexAttrib4fARB(), _mesa_noop_VertexAttrib4fNV(), _mesa_noop_VertexAttrib4fvARB(), and _mesa_noop_VertexAttrib4fvNV().
Referenced by vbo_exec_vtx_init(), and vbo_save_api_init().
_mesa_using_noop_vtxfmt()
GLboolean _mesa_using_noop_vtxfmt (const struct _glapi_table * dispatch)
Is the given dispatch table using the no-op functions?
References _mesa_noop_Begin().
Referenced by vbo_exec_vtx_map().