Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_exec_api.c File Reference
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/context.h"
#include "main/macros.h"
#include "main/vtxfmt.h"
#include "main/dlist.h"
#include "main/eval.h"
#include "main/state.h"
#include "main/light.h"
#include "main/api_arrayelt.h"
#include "main/api_validate.h"
#include "main/dispatch.h"
#include "util/bitscan.h"
#include "vbo_context.h"
#include "vbo_noop.h"
#include "vbo_attrib_tmp.h"
Macros
#define IMM_BUFFER_NAME 0xaabbccdd
ID/name for immediate-mode VBO.
#define ATTR_UNION(A, N, T, C, V0, V1, V2, V3)
This macro is used to implement all the glVertex, glColor, glTexCoord, glVertexAttrib, etc functions.
#define ERROR(err) _mesa_error(ctx, err, __func__)
#define TAG(x) vbo_##x
Functions
static void vbo_reset_all_attr (struct vbo_exec_context *exec)
static void vbo_exec_wrap_buffers (struct vbo_exec_context *exec)
Close off the last primitive, execute the buffer, restart the primitive.
static void vbo_exec_vtx_wrap (struct vbo_exec_context *exec)
Deal with buffer wrapping where provoked by the vertex buffer filling up, as opposed to upgrade_vertex().
static void vbo_exec_copy_to_current (struct vbo_exec_context *exec)
Copy the active vertex's values to the ctx->Current fields.
static void vbo_exec_copy_from_current (struct vbo_exec_context *exec)
Copy current vertex attribute values into the current vertex.
static void vbo_exec_wrap_upgrade_vertex (struct vbo_exec_context *exec, GLuint attr, GLuint newSize)
Flush existing data, set new attrib size, replay copied vertices.
static void vbo_exec_fixup_vertex (struct gl_context *ctx, GLuint attr, GLuint newSize, GLenum newType)
This is when a vertex attribute transitions to a different size.
static void vbo_exec_begin_vertices (struct gl_context *ctx)
Called upon first glVertex, glColor, glTexCoord, etc.
static void GLAPIENTRY vbo_Materialfv (GLenum face, GLenum pname, const GLfloat *params)
Execute a glMaterial call.
static void vbo_exec_FlushVertices_internal (struct vbo_exec_context *exec, GLboolean unmap)
Flush (draw) vertices.
static void GLAPIENTRY vbo_exec_EvalCoord1f (GLfloat u)
static void GLAPIENTRY vbo_exec_EvalCoord2f (GLfloat u, GLfloat v)
static void GLAPIENTRY vbo_exec_EvalCoord1fv (const GLfloat *u)
static void GLAPIENTRY vbo_exec_EvalCoord2fv (const GLfloat *u)
static void GLAPIENTRY vbo_exec_EvalPoint1 (GLint i)
static void GLAPIENTRY vbo_exec_EvalPoint2 (GLint i, GLint j)
static void GLAPIENTRY vbo_exec_Begin (GLenum mode)
Called via glBegin.
static void try_vbo_merge (struct vbo_exec_context *exec)
Try to merge / concatenate the two most recent VBO primitives.
static void GLAPIENTRY vbo_exec_End (void)
Called via glEnd.
static void GLAPIENTRY vbo_exec_PrimitiveRestartNV (void)
Called via glPrimitiveRestartNV()
static void vbo_exec_vtxfmt_init (struct vbo_exec_context *exec)
void vbo_use_buffer_objects (struct gl_context *ctx)
Tell the VBO module to use a real OpenGL vertex buffer object to store accumulated immediate-mode vertex data.
void vbo_always_unmap_buffers (struct gl_context *ctx)
If this function is called, all VBO buffers will be unmapped when we flush.
void vbo_exec_vtx_init (struct vbo_exec_context *exec)
void vbo_exec_vtx_destroy (struct vbo_exec_context *exec)
void vbo_exec_FlushVertices (struct gl_context *ctx, GLuint flags)
If inside glBegin()/glEnd(), it should assert(0).
static void vbo_reset_attr (struct vbo_exec_context *exec, GLuint attr)
Reset the vertex attribute by setting its size to zero.
void GLAPIENTRY _es_Color4f (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void GLAPIENTRY _es_Normal3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_MultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
void GLAPIENTRY _es_Materialfv (GLenum face, GLenum pname, const GLfloat *params)
void GLAPIENTRY _es_Materialf (GLenum face, GLenum pname, GLfloat param)
static void VertexAttrib4f_nopos (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
A special version of glVertexAttrib4f that does not treat index 0 as VBO_ATTRIB_POS.
void GLAPIENTRY _es_VertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _es_VertexAttrib1f (GLuint indx, GLfloat x)
void GLAPIENTRY _es_VertexAttrib1fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
void GLAPIENTRY _es_VertexAttrib2fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_VertexAttrib3fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib4fv (GLuint indx, const GLfloat *values)
Macro Definition Documentation
ATTR_UNION
#define ATTR_UNION (A, N, T, C, V0, V1, V2, V3)
This macro is used to implement all the glVertex, glColor, glTexCoord, glVertexAttrib, etc functions.
Parameters
A attribute index
N attribute size (1..4)
T type (GL_FLOAT, GL_DOUBLE, GL_INT, GL_UNSIGNED_INT)
C cast type (fi_type or double)
V0,V1,v2,V3 attribute value
ERROR
#define ERROR (err) _mesa_error(ctx, err, __func__)
Referenced by VertexAttrib1fARB(), VertexAttrib1fvARB(), VertexAttrib2fARB(), VertexAttrib2fvARB(), VertexAttrib3fARB(), VertexAttrib3fvARB(), VertexAttrib4f_nopos(), VertexAttrib4fARB(), VertexAttrib4fvARB(), VertexAttribI1i(), VertexAttribI1ui(), VertexAttribI2i(), VertexAttribI2iv(), VertexAttribI2ui(), VertexAttribI2uiv(), VertexAttribI3i(), VertexAttribI3iv(), VertexAttribI3ui(), VertexAttribI3uiv(), VertexAttribI4i(), VertexAttribI4iv(), VertexAttribI4ui(), VertexAttribI4uiv(), VertexAttribL1d(), VertexAttribL1dv(), VertexAttribL2d(), VertexAttribL2dv(), VertexAttribL3d(), VertexAttribL3dv(), VertexAttribL4d(), and VertexAttribL4dv().
IMM_BUFFER_NAME
#define IMM_BUFFER_NAME 0xaabbccdd
ID/name for immediate-mode VBO.
Referenced by vbo_exec_vtx_destroy(), and vbo_use_buffer_objects().
TAG
#define TAG (x) vbo_##x
Function Documentation
_es_Color4f()
void GLAPIENTRY _es_Color4f (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
Referenced by vbo_sizeof_ib_type().
_es_Materialf()
void GLAPIENTRY _es_Materialf (GLenum face, GLenum pname, GLfloat param)
References vbo_Materialfv().
Referenced by vbo_sizeof_ib_type().
_es_Materialfv()
void GLAPIENTRY _es_Materialfv (GLenum face, GLenum pname, const GLfloat * params)
References vbo_Materialfv().
Referenced by vbo_sizeof_ib_type().
_es_MultiTexCoord4f()
void GLAPIENTRY _es_MultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
Referenced by vbo_sizeof_ib_type().
_es_Normal3f()
void GLAPIENTRY _es_Normal3f (GLfloat x, GLfloat y, GLfloat z)
Referenced by vbo_sizeof_ib_type().
_es_VertexAttrib1f()
void GLAPIENTRY _es_VertexAttrib1f (GLuint indx, GLfloat x)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib1fv()
void GLAPIENTRY _es_VertexAttrib1fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib2f()
void GLAPIENTRY _es_VertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib2fv()
void GLAPIENTRY _es_VertexAttrib2fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib3f()
void GLAPIENTRY _es_VertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib3fv()
void GLAPIENTRY _es_VertexAttrib3fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib4f()
void GLAPIENTRY _es_VertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
_es_VertexAttrib4fv()
void GLAPIENTRY _es_VertexAttrib4fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init(), and vbo_sizeof_ib_type().
try_vbo_merge()
static void try_vbo_merge (struct vbo_exec_context * exec) static
Try to merge / concatenate the two most recent VBO primitives.
References _mesa_prim::begin, _mesa_prim::end, vbo_exec_context::prim, vbo_exec_context::prim_count, vbo_can_merge_prims(), vbo_merge_prims(), vbo_try_prim_conversion(), and vbo_exec_context::vtx.
Referenced by vbo_exec_End().
vbo_always_unmap_buffers()
void vbo_always_unmap_buffers (struct gl_context * ctx)
If this function is called, all VBO buffers will be unmapped when we flush.
Otherwise, if a simple command like glColor3f() is called and we flush, the current VBO may be left mapped.
References vbo_exec_context::begin_vertices_flags, vbo_context::exec, FLUSH_STORED_VERTICES, and vbo_context().
Referenced by vbo_sizeof_ib_type().
vbo_exec_Begin()
static void GLAPIENTRY vbo_exec_Begin (GLenum mode) static
Called via glBegin.
References _mesa_error(), _mesa_update_state(), _mesa_valid_prim_mode(), _mesa_valid_to_render(), vbo_exec_context::attrsz, _mesa_prim::base_instance, _mesa_prim::begin, gl_context::BeginEnd, _mesa_prim::count, vbo_exec_context::ctx, gl_context::CurrentClientDispatch, dd_function_table::CurrentExecPrimitive, DRAW_BEGIN_END, gl_context::Driver, _mesa_prim::end, gl_context::Exec, vbo_context::exec, _mesa_prim::indexed, _mesa_prim::is_indirect, _mesa_prim::mode, gl_context::NewState, _mesa_prim::num_instances, gl_context::OutsideBeginEnd, _mesa_prim::pad, vbo_exec_context::prim, vbo_exec_context::prim_count, gl_context::Save, _mesa_prim::start, vbo_context(), vbo_draw_method(), vbo_exec_FlushVertices_internal(), vbo_exec_context::vert_count, vbo_exec_context::vertex_size, vbo_exec_context::vtx, and _mesa_prim::weak.
Referenced by vbo_exec_PrimitiveRestartNV(), and vbo_exec_vtxfmt_init().
vbo_exec_begin_vertices()
static void vbo_exec_begin_vertices (struct gl_context * ctx) static
Called upon first glVertex, glColor, glTexCoord, etc.
References vbo_exec_context::begin_vertices_flags, gl_context::Driver, vbo_context::exec, FLUSH_UPDATE_CURRENT, dd_function_table::NeedFlush, vbo_context(), and vbo_exec_vtx_map().
vbo_exec_copy_from_current()
static void vbo_exec_copy_from_current (struct vbo_exec_context * exec) static
Copy current vertex attribute values into the current vertex.
References vbo_exec_context::attrptr, vbo_exec_context::attrsz, vbo_exec_context::attrtype, vbo_exec_context::ctx, vbo_context::currval, gl_vertex_array::Ptr, VBO_ATTRIB_MAX, VBO_ATTRIB_POS, vbo_context(), and vbo_exec_context::vtx.
Referenced by vbo_exec_wrap_upgrade_vertex().
vbo_exec_copy_to_current()
static void vbo_exec_copy_to_current (struct vbo_exec_context * exec) static
Copy the active vertex's values to the ctx->Current fields.
References gl_vertex_array::_ElementSize, _mesa_update_color_material(), _NEW_CURRENT_ATTRIB, _NEW_LIGHT, gl_current_attrib::Attrib, vbo_exec_context::attrptr, vbo_exec_context::attrsz, vbo_exec_context::attrtype, BITFIELD64_BIT, gl_light_attrib::ColorMaterialEnabled, vbo_exec_context::ctx, gl_context::Current, vbo_context::currval, gl_vertex_array::Doubles, vbo_exec_context::enabled, gl_vertex_array::Integer, gl_context::Light, gl_context::NewState, gl_vertex_array::Ptr, gl_vertex_array::Size, gl_vertex_array::Type, VBO_ATTRIB_COLOR0, VBO_ATTRIB_MAT_BACK_INDEXES, VBO_ATTRIB_MAT_FRONT_AMBIENT, VBO_ATTRIB_POS, vbo_attrtype_to_double_flag(), vbo_attrtype_to_integer_flag(), vbo_context(), and vbo_exec_context::vtx.
Referenced by vbo_exec_FlushVertices_internal(), and vbo_exec_wrap_upgrade_vertex().
vbo_exec_End()
static void GLAPIENTRY vbo_exec_End (void) static
Called via glEnd.
References _mesa_error(), _mesa_flush(), _mesa_prim::begin, gl_context::BeginEnd, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, _mesa_prim::count, vbo_exec_context::ctx, gl_context::CurrentClientDispatch, DEBUG_ALWAYS_FLUSH, _mesa_prim::end, gl_context::Exec, vbo_context::exec, MESA_DEBUG_FLAGS, _mesa_prim::mode, gl_context::OutsideBeginEnd, vbo_exec_context::prim, vbo_exec_context::prim_count, PRIM_OUTSIDE_BEGIN_END, _mesa_prim::start, try_vbo_merge(), vbo_context(), vbo_exec_vtx_flush(), VBO_MAX_PRIM, vbo_exec_context::vert_count, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_PrimitiveRestartNV(), and vbo_exec_vtxfmt_init().
vbo_exec_EvalCoord1f()
static void GLAPIENTRY vbo_exec_EvalCoord1f (GLfloat u) static
References vbo_exec_context::active_sz, vbo_exec_copied_vtx::buffer, vbo_exec_context::copied, vbo_exec_context::ctx, vbo_exec_context::eval, vbo_context::exec, vbo_exec_eval1_map::map, vbo_exec_context::map1, vbo_exec_context::recalculate_maps, vbo_exec_eval1_map::sz, VBO_ATTRIB_TEX7, vbo_context(), vbo_exec_do_EvalCoord1f(), vbo_exec_eval_update(), vbo_exec_fixup_vertex(), vbo_exec_context::vertex, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord1fv(), vbo_exec_EvalPoint1(), and vbo_exec_vtxfmt_init().
vbo_exec_EvalCoord1fv()
static void GLAPIENTRY vbo_exec_EvalCoord1fv (const GLfloat * u) static
References vbo_exec_EvalCoord1f().
Referenced by vbo_exec_vtxfmt_init().
vbo_exec_EvalCoord2f()
static void GLAPIENTRY vbo_exec_EvalCoord2f (GLfloat u, GLfloat v) static
References vbo_exec_context::active_sz, gl_eval_attrib::AutoNormal, vbo_exec_copied_vtx::buffer, vbo_exec_context::copied, vbo_exec_context::ctx, gl_context::Eval, vbo_exec_context::eval, vbo_context::exec, vbo_exec_eval2_map::map, vbo_exec_context::map2, vbo_exec_context::recalculate_maps, vbo_exec_eval2_map::sz, VBO_ATTRIB_NORMAL, VBO_ATTRIB_TEX7, vbo_context(), vbo_exec_do_EvalCoord2f(), vbo_exec_eval_update(), vbo_exec_fixup_vertex(), vbo_exec_context::vertex, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord2fv(), vbo_exec_EvalPoint2(), and vbo_exec_vtxfmt_init().
vbo_exec_EvalCoord2fv()
static void GLAPIENTRY vbo_exec_EvalCoord2fv (const GLfloat * u) static
References vbo_exec_EvalCoord2f().
Referenced by vbo_exec_vtxfmt_init().
vbo_exec_EvalPoint1()
static void GLAPIENTRY vbo_exec_EvalPoint1 (GLint i) static
References vbo_exec_context::ctx, gl_context::Eval, gl_eval_attrib::MapGrid1u1, gl_eval_attrib::MapGrid1u2, gl_eval_attrib::MapGrid1un, and vbo_exec_EvalCoord1f().
Referenced by vbo_exec_vtxfmt_init().
vbo_exec_EvalPoint2()
static void GLAPIENTRY vbo_exec_EvalPoint2 (GLint i, GLint j) static
References vbo_exec_context::ctx, gl_context::Eval, gl_eval_attrib::MapGrid2u1, gl_eval_attrib::MapGrid2u2, gl_eval_attrib::MapGrid2un, gl_eval_attrib::MapGrid2v1, gl_eval_attrib::MapGrid2v2, gl_eval_attrib::MapGrid2vn, and vbo_exec_EvalCoord2f().
Referenced by vbo_exec_vtxfmt_init().
vbo_exec_fixup_vertex()
static void vbo_exec_fixup_vertex (struct gl_context * ctx, GLuint attr, GLuint newSize, GLenum newType) static
This is when a vertex attribute transitions to a different size.
For example, we saw a bunch of glTexCoord2f() calls and now we got a glTexCoord4f() call. We promote the array from size=2 to size=4.
Parameters
newSize size of new vertex (number of 32-bit words).
References vbo_exec_context::active_sz, vbo_exec_context::attrptr, vbo_exec_context::attrsz, vbo_exec_context::attrtype, gl_context::Driver, vbo_context::exec, FLUSH_STORED_VERTICES, GLuint, dd_function_table::NeedFlush, vbo_context(), vbo_exec_wrap_upgrade_vertex(), vbo_get_default_vals_as_union(), and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord1f(), and vbo_exec_EvalCoord2f().
vbo_exec_FlushVertices()
void vbo_exec_FlushVertices (struct gl_context * ctx, GLuint flags)
If inside glBegin()/glEnd(), it should assert(0).
Otherwise, if FLUSH_STORED_VERTICES bit in flags is set flushes any buffered vertices, if FLUSH_UPDATE_CURRENT bit is set updates __struct gl_contextRec::Current and gl_light_attrib::Material
Note that the default T&L engine never clears the FLUSH_UPDATE_CURRENT bit, even after performing the update.
Parameters
flags bitmask of FLUSH_STORED_VERTICES, FLUSH_UPDATE_CURRENT
References gl_context::Driver, vbo_context::exec, FLUSH_UPDATE_CURRENT, dd_function_table::NeedFlush, vbo_context(), and vbo_exec_FlushVertices_internal().
vbo_exec_FlushVertices_internal()
static void vbo_exec_FlushVertices_internal (struct vbo_exec_context * exec, GLboolean unmap) static
Flush (draw) vertices.
Parameters
unmap - leave VBO unmapped after flushing?
References vbo_exec_copy_to_current(), vbo_exec_vtx_flush(), vbo_reset_all_attr(), vbo_exec_context::vert_count, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_Begin(), and vbo_exec_FlushVertices().
vbo_exec_PrimitiveRestartNV()
static void GLAPIENTRY vbo_exec_PrimitiveRestartNV (void) static
Called via glPrimitiveRestartNV()
References _mesa_error(), PRIM_OUTSIDE_BEGIN_END, vbo_exec_Begin(), and vbo_exec_End().
Referenced by vbo_exec_vtxfmt_init().
vbo_exec_vtx_destroy()
void vbo_exec_vtx_destroy (struct vbo_exec_context * exec)
References _mesa_align_free(), vbo_exec_context::arrays, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, gl_vertex_array::BufferObj, vbo_exec_context::bufferobj, vbo_exec_context::ctx, gl_context::Driver, IMM_BUFFER_NAME, MAP_INTERNAL, gl_buffer_object::Name, dd_function_table::UnmapBuffer, and vbo_exec_context::vtx.
Referenced by vbo_exec_destroy().
vbo_exec_vtx_init()
void vbo_exec_vtx_init (struct vbo_exec_context * exec)
References _mesa_align_malloc(), _mesa_noop_vtxfmt_init(), vbo_exec_context::active_sz, vbo_exec_context::arrays, vbo_exec_context::attrsz, vbo_exec_context::attrtype, vbo_exec_context::begin_vertices_flags, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, gl_vertex_array::BufferObj, vbo_exec_context::bufferobj, vbo_exec_context::ctx, vbo_context::currval, vbo_exec_context::enabled, FLUSH_UPDATE_CURRENT, GLuint, vbo_exec_context::inputs, gl_shared_state::NullBufferObj, gl_context::Shared, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_MAX, VBO_ATTRIB_POS, vbo_context(), vbo_exec_vtxfmt_init(), VBO_VERT_BUFFER_SIZE, vbo_exec_context::vertex_size, vbo_exec_context::vtx, and vbo_exec_context::vtxfmt_noop.
Referenced by vbo_exec_init().
vbo_exec_vtx_wrap()
static void vbo_exec_vtx_wrap (struct vbo_exec_context * exec) static
Deal with buffer wrapping where provoked by the vertex buffer filling up, as opposed to upgrade_vertex().
References vbo_exec_copied_vtx::buffer, vbo_exec_context::buffer_ptr, vbo_exec_context::copied, vbo_exec_context::max_vert, vbo_exec_copied_vtx::nr, vbo_exec_wrap_buffers(), vbo_exec_context::vert_count, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
vbo_exec_vtxfmt_init()
static void vbo_exec_vtxfmt_init (struct vbo_exec_context * exec) static
References _ae_ArrayElement(), _es_VertexAttrib1f(), _es_VertexAttrib1fv(), _es_VertexAttrib2f(), _es_VertexAttrib2fv(), _es_VertexAttrib3f(), _es_VertexAttrib3fv(), _es_VertexAttrib4f(), _es_VertexAttrib4fv(), _mesa_CallList(), _mesa_CallLists(), gl_context::API, API_OPENGLES2, vbo_exec_context::ctx, vbo_exec_Begin(), vbo_exec_End(), vbo_exec_EvalCoord1f(), vbo_exec_EvalCoord1fv(), vbo_exec_EvalCoord2f(), vbo_exec_EvalCoord2fv(), vbo_exec_EvalPoint1(), vbo_exec_EvalPoint2(), vbo_exec_PrimitiveRestartNV(), vbo_Materialfv(), and vbo_exec_context::vtxfmt.
Referenced by vbo_exec_vtx_init().
vbo_exec_wrap_buffers()
static void vbo_exec_wrap_buffers (struct vbo_exec_context * exec) static
Close off the last primitive, execute the buffer, restart the primitive.
This is called when we fill a vertex buffer before hitting glEnd.
References _mesa_prim::begin, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::copied, _mesa_prim::count, vbo_exec_context::ctx, dd_function_table::CurrentExecPrimitive, gl_context::Driver, _mesa_prim::end, GLuint, _mesa_prim::mode, vbo_exec_copied_vtx::nr, vbo_exec_context::prim, vbo_exec_context::prim_count, _mesa_prim::start, vbo_exec_vtx_flush(), vbo_exec_context::vert_count, and vbo_exec_context::vtx.
Referenced by vbo_exec_vtx_wrap(), and vbo_exec_wrap_upgrade_vertex().
vbo_exec_wrap_upgrade_vertex()
static void vbo_exec_wrap_upgrade_vertex (struct vbo_exec_context * exec, GLuint attr, GLuint newSize) static
Flush existing data, set new attrib size, replay copied vertices.
This is called when we transition from a small vertex attribute size to a larger one. Ex: glTexCoord2f -> glTexCoord4f. We need to go back over the previous 2-component texcoords and insert zero and one values.
References vbo_exec_context::attrptr, vbo_exec_context::attrsz, vbo_exec_context::attrtype, BITFIELD64_BIT, vbo_exec_copied_vtx::buffer, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::copied, COPY_SZ_4V, vbo_exec_context::ctx, vbo_context::currval, vbo_exec_context::enabled, GLuint, vbo_exec_context::max_vert, vbo_exec_copied_vtx::nr, gl_vertex_array::Ptr, VBO_ATTRIB_MAX, vbo_compute_max_verts(), vbo_context(), vbo_exec_copy_from_current(), vbo_exec_copy_to_current(), vbo_exec_wrap_buffers(), vbo_reset_all_attr(), vbo_exec_context::vert_count, vbo_exec_context::vertex, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_fixup_vertex().
vbo_Materialfv()
static void GLAPIENTRY vbo_Materialfv (GLenum face, GLenum pname, const GLfloat * params) static
Execute a glMaterial call.
Note that if GL_COLOR_MATERIAL is enabled, this may be a (partial) no-op.
References gl_light_attrib::_ColorMaterialBitmask, _mesa_error(), ALL_MATERIAL_BITS, gl_context::API, API_OPENGL_COMPAT, BACK_MATERIAL_BITS, gl_light_attrib::ColorMaterialEnabled, gl_context::Const, vbo_exec_context::ctx, FRONT_MATERIAL_BITS, gl_context::Light, MAT_ATTR, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_INDEXES, MAT_BIT_BACK_SHININESS, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_INDEXES, MAT_BIT_FRONT_SHININESS, MAT_BIT_FRONT_SPECULAR, gl_constants::MaxShininess, VBO_ATTRIB_MAT_BACK_AMBIENT, VBO_ATTRIB_MAT_BACK_DIFFUSE, VBO_ATTRIB_MAT_BACK_EMISSION, VBO_ATTRIB_MAT_BACK_INDEXES, VBO_ATTRIB_MAT_BACK_SHININESS, VBO_ATTRIB_MAT_BACK_SPECULAR, VBO_ATTRIB_MAT_FRONT_AMBIENT, VBO_ATTRIB_MAT_FRONT_DIFFUSE, VBO_ATTRIB_MAT_FRONT_EMISSION, VBO_ATTRIB_MAT_FRONT_INDEXES, VBO_ATTRIB_MAT_FRONT_SHININESS, and VBO_ATTRIB_MAT_FRONT_SPECULAR.
Referenced by _es_Materialf(), _es_Materialfv(), and vbo_exec_vtxfmt_init().
vbo_reset_all_attr()
static void vbo_reset_all_attr (struct vbo_exec_context * exec) static
References vbo_exec_context::enabled, vbo_reset_attr(), vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_FlushVertices_internal(), and vbo_exec_wrap_upgrade_vertex().
vbo_reset_attr()
static void vbo_reset_attr (struct vbo_exec_context * exec, GLuint attr) static
Reset the vertex attribute by setting its size to zero.
References vbo_exec_context::active_sz, vbo_exec_context::attrsz, vbo_exec_context::attrtype, and vbo_exec_context::vtx.
Referenced by vbo_reset_all_attr().
vbo_use_buffer_objects()
void vbo_use_buffer_objects (struct gl_context * ctx)
Tell the VBO module to use a real OpenGL vertex buffer object to store accumulated immediate-mode vertex data.
This replaces the malloced buffer which was created in vb_exec_vtx_init() below.
References _mesa_align_free(), _mesa_error(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, dd_function_table::BufferData, vbo_exec_context::bufferobj, gl_context::Driver, vbo_context::exec, GLuint, IMM_BUFFER_NAME, dd_function_table::NewBufferObject, gl_shared_state::NullBufferObj, gl_context::Shared, vbo_context(), VBO_VERT_BUFFER_SIZE, and vbo_exec_context::vtx.
Referenced by vbo_sizeof_ib_type().
VertexAttrib4f_nopos()
static void VertexAttrib4f_nopos (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) static
A special version of glVertexAttrib4f that does not treat index 0 as VBO_ATTRIB_POS.
References ATTRF, vbo_exec_context::ctx, ERROR, MAX_VERTEX_GENERIC_ATTRIBS, and VBO_ATTRIB_GENERIC0.
Referenced by _es_VertexAttrib1f(), _es_VertexAttrib1fv(), _es_VertexAttrib2f(), _es_VertexAttrib2fv(), _es_VertexAttrib3f(), _es_VertexAttrib3fv(), _es_VertexAttrib4f(), and _es_VertexAttrib4fv().