Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_exec.c File Reference
#include "main/api_arrayelt.h"
#include "main/glheader.h"
#include "main/mtypes.h"
#include "main/vtxfmt.h"
#include "vbo_context.h"
Functions
void vbo_exec_init (struct gl_context *ctx)
void vbo_exec_destroy (struct gl_context *ctx)
void vbo_exec_invalidate_state (struct gl_context *ctx, GLbitfield new_state)
Really want to install these callbacks to a central facility to be invoked according to the state flags.
size_t vbo_count_tessellated_primitives (GLenum mode, GLuint count, GLuint num_instances)
Figure out the number of transform feedback primitives that will be output considering the drawing mode, number of vertices, and instance count, assuming that no geometry shading is done and primitive restart is not used.
void vbo_try_prim_conversion (struct _mesa_prim *p)
In some degenarate cases we can improve our ability to merge consecutive primitives.
bool vbo_can_merge_prims (const struct _mesa_prim *p0, const struct _mesa_prim *p1)
Helper function for determining if two subsequent glBegin/glEnd primitives can be combined.
void vbo_merge_prims (struct _mesa_prim *p0, const struct _mesa_prim *p1)
If we've determined that p0 and p1 can be merged, this function concatenates p1 onto p0.
Function Documentation
vbo_can_merge_prims()
bool vbo_can_merge_prims (const struct _mesa_prim * p0, const struct _mesa_prim * p1)
Helper function for determining if two subsequent glBegin/glEnd primitives can be combined.
This is only possible for GL_POINTS, GL_LINES, GL_TRIANGLES and GL_QUADS. If we return true, it means that we can concatenate p1 onto p0 (and discard p1).
References _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::begin, _mesa_prim::count, _mesa_prim::end, _mesa_prim::mode, _mesa_prim::num_instances, and _mesa_prim::start.
Referenced by merge_prims(), try_vbo_merge(), vbo_merge_prims(), and vbo_sizeof_ib_type().
vbo_count_tessellated_primitives()
size_t vbo_count_tessellated_primitives (GLenum mode, GLuint count, GLuint num_instances)
Figure out the number of transform feedback primitives that will be output considering the drawing mode, number of vertices, and instance count, assuming that no geometry shading is done and primitive restart is not used.
This is used by driver back-ends in implementing the PRIMITIVES_GENERATED and TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN queries. It is also used to pre-validate draw calls in GLES3 (where draw calls only succeed if there is enough room in the transform feedback buffer for the result).
Referenced by vbo_sizeof_ib_type().
vbo_exec_destroy()
void vbo_exec_destroy (struct gl_context * ctx)
References _ae_destroy_context(), gl_context::aelt_context, vbo_context::exec, vbo_context(), and vbo_exec_vtx_destroy().
Referenced by _vbo_DestroyContext().
vbo_exec_init()
void vbo_exec_init (struct gl_context * ctx)
References _ae_create_context(), gl_context::aelt_context, vbo_exec_context::ctx, dd_function_table::CurrentExecPrimitive, gl_context::Driver, vbo_context::exec, dd_function_table::NeedFlush, PRIM_OUTSIDE_BEGIN_END, vbo_context(), vbo_exec_invalidate_state(), and vbo_exec_vtx_init().
Referenced by _vbo_CreateContext().
vbo_exec_invalidate_state()
void vbo_exec_invalidate_state (struct gl_context * ctx, GLbitfield new_state)
Really want to install these callbacks to a central facility to be invoked according to the state flags.
That will have to wait for a mesa rework:
References _ae_invalidate_state(), _NEW_ARRAY, _NEW_EVAL, _NEW_PROGRAM, vbo_exec_context::array, vbo_exec_context::eval, vbo_context::exec, vbo_exec_context::recalculate_inputs, vbo_exec_context::recalculate_maps, vbo_exec_context::validating, and vbo_context().
Referenced by _vbo_InvalidateState(), and vbo_exec_init().
vbo_merge_prims()
void vbo_merge_prims (struct _mesa_prim * p0, const struct _mesa_prim * p1)
If we've determined that p0 and p1 can be merged, this function concatenates p1 onto p0.
References _mesa_prim::count, _mesa_prim::end, and vbo_can_merge_prims().
Referenced by merge_prims(), try_vbo_merge(), and vbo_sizeof_ib_type().
vbo_try_prim_conversion()
void vbo_try_prim_conversion (struct _mesa_prim * p)
In some degenarate cases we can improve our ability to merge consecutive primitives.
For example: glBegin(GL_LINE_STRIP); glVertex(1); glVertex(1); glEnd(); glBegin(GL_LINE_STRIP); glVertex(1); glVertex(1); glEnd(); Can be merged as a GL_LINES prim with four vertices.
This function converts 2-vertex line strips/loops into GL_LINES, etc.
References _mesa_prim::count, and _mesa_prim::mode.
Referenced by merge_prims(), try_vbo_merge(), and vbo_sizeof_ib_type().