Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_exec_eval.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/macros.h"
#include "math/m_eval.h"
#include "main/dispatch.h"
#include "vbo_exec.h"
Functions
static void clear_active_eval1 (struct vbo_exec_context *exec, GLuint attr)
static void clear_active_eval2 (struct vbo_exec_context *exec, GLuint attr)
static void set_active_eval1 (struct vbo_exec_context *exec, GLuint attr, GLuint dim, struct gl_1d_map *map)
static void set_active_eval2 (struct vbo_exec_context *exec, GLuint attr, GLuint dim, struct gl_2d_map *map)
void vbo_exec_eval_update (struct vbo_exec_context *exec)
void vbo_exec_do_EvalCoord1f (struct vbo_exec_context *exec, GLfloat u)
void vbo_exec_do_EvalCoord2f (struct vbo_exec_context *exec, GLfloat u, GLfloat v)
Function Documentation
clear_active_eval1()
static void clear_active_eval1 (struct vbo_exec_context * exec, GLuint attr) static
References vbo_exec_context::eval, vbo_exec_eval1_map::map, and vbo_exec_context::map1.
Referenced by vbo_exec_eval_update().
clear_active_eval2()
static void clear_active_eval2 (struct vbo_exec_context * exec, GLuint attr) static
References vbo_exec_context::eval, vbo_exec_eval2_map::map, and vbo_exec_context::map2.
Referenced by vbo_exec_eval_update().
set_active_eval1()
static void set_active_eval1 (struct vbo_exec_context * exec, GLuint attr, GLuint dim, struct gl_1d_map * map) static
References vbo_exec_context::eval, vbo_exec_eval1_map::map, vbo_exec_context::map1, and vbo_exec_eval1_map::sz.
Referenced by vbo_exec_eval_update().
set_active_eval2()
static void set_active_eval2 (struct vbo_exec_context * exec, GLuint attr, GLuint dim, struct gl_2d_map * map) static
References vbo_exec_context::eval, vbo_exec_eval2_map::map, vbo_exec_context::map2, and vbo_exec_eval2_map::sz.
Referenced by vbo_exec_eval_update().
vbo_exec_do_EvalCoord1f()
void vbo_exec_do_EvalCoord1f (struct vbo_exec_context * exec, GLfloat u)
Vertex – EvalCoord1f is a noop if this map not enabled:
References _math_horner_bezier_curve(), vbo_exec_context::attrptr, vbo_exec_context::attrsz, COPY_SZ_4V, gl_1d_map::du, vbo_exec_context::eval, GLuint, vbo_exec_eval1_map::map, vbo_exec_context::map1, gl_1d_map::Order, gl_1d_map::Points, vbo_exec_eval1_map::sz, gl_1d_map::u1, VBO_ATTRIB_TEX7, and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord1f().
vbo_exec_do_EvalCoord2f()
void vbo_exec_do_EvalCoord2f (struct vbo_exec_context * exec, GLfloat u, GLfloat v)
Vertex – EvalCoord2f is a noop if this map not enabled:
References _math_de_casteljau_surf(), _math_horner_bezier_surf(), vbo_exec_context::attrptr, vbo_exec_context::attrsz, gl_eval_attrib::AutoNormal, COPY_SZ_4V, vbo_exec_context::ctx, gl_2d_map::du, gl_2d_map::dv, gl_context::Eval, vbo_exec_context::eval, fi_type::f, GLuint, vbo_exec_eval2_map::map, vbo_exec_context::map2, gl_2d_map::Points, vbo_exec_eval2_map::sz, gl_2d_map::u1, gl_2d_map::Uorder, gl_2d_map::v1, VBO_ATTRIB_NORMAL, VBO_ATTRIB_TEX7, gl_2d_map::Vorder, and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord2f().
vbo_exec_eval_update()
void vbo_exec_eval_update (struct vbo_exec_context * exec)
References clear_active_eval1(), clear_active_eval2(), vbo_exec_context::ctx, gl_context::Eval, vbo_exec_context::eval, gl_context::EvalMap, GLuint, gl_evaluators::Map1Color4, gl_eval_attrib::Map1Color4, gl_eval_attrib::Map1Normal, gl_evaluators::Map1Normal, gl_evaluators::Map1Texture1, gl_evaluators::Map1Texture2, gl_evaluators::Map1Texture3, gl_evaluators::Map1Texture4, gl_eval_attrib::Map1TextureCoord1, gl_eval_attrib::Map1TextureCoord2, gl_eval_attrib::Map1TextureCoord3, gl_eval_attrib::Map1TextureCoord4, gl_evaluators::Map1Vertex3, gl_eval_attrib::Map1Vertex3, gl_eval_attrib::Map1Vertex4, gl_evaluators::Map1Vertex4, gl_eval_attrib::Map2Color4, gl_evaluators::Map2Color4, gl_eval_attrib::Map2Normal, gl_evaluators::Map2Normal, gl_evaluators::Map2Texture1, gl_evaluators::Map2Texture2, gl_evaluators::Map2Texture3, gl_evaluators::Map2Texture4, gl_eval_attrib::Map2TextureCoord1, gl_eval_attrib::Map2TextureCoord2, gl_eval_attrib::Map2TextureCoord3, gl_eval_attrib::Map2TextureCoord4, gl_evaluators::Map2Vertex3, gl_eval_attrib::Map2Vertex3, gl_eval_attrib::Map2Vertex4, gl_evaluators::Map2Vertex4, vbo_exec_context::recalculate_maps, set_active_eval1(), set_active_eval2(), VBO_ATTRIB_COLOR0, VBO_ATTRIB_FIRST_MATERIAL, VBO_ATTRIB_NORMAL, VBO_ATTRIB_POS, and VBO_ATTRIB_TEX0.
Referenced by vbo_exec_EvalCoord1f(), and vbo_exec_EvalCoord2f().