Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_split.h File Reference
#include "vbo.h"
Functions
GLboolean split_prim_inplace (GLenum mode, GLuint *first, GLuint *incr)
void vbo_split_inplace (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits *limits)
void vbo_split_copy (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, vbo_draw_func draw, const struct split_limits *limits)
Split VBO into smaller pieces, draw the pieces.
Function Documentation
split_prim_inplace()
GLboolean split_prim_inplace (GLenum mode, GLuint * first, GLuint * incr)
Referenced by replay_elts(), and split_prims().
vbo_split_copy()
void vbo_split_copy (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, vbo_draw_func draw, const struct split_limits * limits)
Split VBO into smaller pieces, draw the pieces.
References copy_context::array, copy_context::ctx, copy_context::draw, ELT_TABLE_SIZE, GLuint, copy_context::ib, copy_context::in, copy_context::limits, copy_context::nr_prims, copy_context::prim, replay_elts(), replay_finish(), replay_init(), and copy_context::vert_cache.
Referenced by split_prims(), and vbo_split_prims().
vbo_split_inplace()
void vbo_split_inplace (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits * limits)
References split_context::array, split_context::ctx, split_context::draw, split_context::ib, split_context::limit, split_context::limits, split_context::max_index, split_limits::max_indices, split_limits::max_verts, split_context::min_index, split_context::nr_prims, split_context::prim, and split_prims().
Referenced by vbo_split_prims().