Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_minmax_index.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/varray.h"
#include "main/macros.h"
#include "main/sse_minmax.h"
#include "x86/common_x86_asm.h"
#include "util/hash_table.h"
Data Structures
struct minmax_cache_key
struct minmax_cache_entry
Functions
static uint32_t vbo_minmax_cache_hash (const struct minmax_cache_key *key)
static bool vbo_minmax_cache_key_equal (const struct minmax_cache_key *a, const struct minmax_cache_key *b)
static void vbo_minmax_cache_delete_entry (struct hash_entry *entry)
static GLboolean vbo_use_minmax_cache (struct gl_buffer_object *bufferObj)
void vbo_delete_minmax_cache (struct gl_buffer_object *bufferObj)
static GLboolean vbo_get_minmax_cached (struct gl_buffer_object *bufferObj, GLenum type, GLintptr offset, GLuint count, GLuint *min_index, GLuint *max_index)
static void vbo_minmax_cache_store (struct gl_context *ctx, struct gl_buffer_object *bufferObj, GLenum type, GLintptr offset, GLuint count, GLuint min, GLuint max)
static void vbo_get_minmax_index (struct gl_context *ctx, const struct _mesa_prim *prim, const struct _mesa_index_buffer *ib, GLuint *min_index, GLuint *max_index, const GLuint count)
Compute min and max elements by scanning the index buffer for glDraw[Range]Elements() calls.
void vbo_get_minmax_indices (struct gl_context *ctx, const struct _mesa_prim *prims, const struct _mesa_index_buffer *ib, GLuint *min_index, GLuint *max_index, GLuint nr_prims)
Compute min and max elements for nr_prims.
Function Documentation
vbo_delete_minmax_cache()
void vbo_delete_minmax_cache (struct gl_buffer_object * bufferObj)
References gl_buffer_object::MinMaxCache, and vbo_minmax_cache_delete_entry().
Referenced by vbo_get_minmax_cached(), and vbo_sizeof_ib_type().
vbo_get_minmax_cached()
static GLboolean vbo_get_minmax_cached (struct gl_buffer_object * bufferObj, GLenum type, GLintptr offset, GLuint count, GLuint * min_index, GLuint * max_index) static
References minmax_cache_key::count, minmax_cache_entry::max, minmax_cache_entry::min, gl_buffer_object::MinMaxCache, gl_buffer_object::MinMaxCacheDirty, gl_buffer_object::MinMaxCacheHitIndices, gl_buffer_object::MinMaxCacheMissIndices, gl_buffer_object::Mutex, minmax_cache_key::offset, gl_buffer_object::Size, minmax_cache_key::type, USAGE_DISABLE_MINMAX_CACHE, gl_buffer_object::UsageHistory, vbo_delete_minmax_cache(), vbo_minmax_cache_delete_entry(), vbo_minmax_cache_hash(), and vbo_use_minmax_cache().
Referenced by vbo_get_minmax_index().
vbo_get_minmax_index()
static void vbo_get_minmax_index (struct gl_context * ctx, const struct _mesa_prim * prim, const struct _mesa_index_buffer * ib, GLuint * min_index, GLuint * max_index, const GLuint count) static
Compute min and max elements by scanning the index buffer for glDraw[Range]Elements() calls.
If primitive restart is enabled, we need to ignore restart indexes when computing min/max.
References _mesa_primitive_restart_index(), _mesa_uint_array_min_max(), gl_array_attrib::_PrimitiveRestart, gl_context::Array, minmax_cache_key::count, gl_context::Driver, GLuint, GLushort, if(), MAP_INTERNAL, dd_function_table::MapBufferRange, _mesa_index_buffer::obj, _mesa_index_buffer::ptr, gl_buffer_object::Size, _mesa_prim::start, _mesa_index_buffer::type, dd_function_table::UnmapBuffer, vbo_get_minmax_cached(), vbo_minmax_cache_store(), and vbo_sizeof_ib_type().
Referenced by vbo_get_minmax_indices().
vbo_get_minmax_indices()
void vbo_get_minmax_indices (struct gl_context * ctx, const struct _mesa_prim * prims, const struct _mesa_index_buffer * ib, GLuint * min_index, GLuint * max_index, GLuint nr_prims)
Compute min and max elements for nr_prims.
References minmax_cache_key::count, _mesa_prim::count, GLuint, _mesa_prim::start, and vbo_get_minmax_index().
Referenced by vbo_sizeof_ib_type().
vbo_minmax_cache_delete_entry()
static void vbo_minmax_cache_delete_entry (struct hash_entry * entry) static
Referenced by vbo_delete_minmax_cache(), and vbo_get_minmax_cached().
vbo_minmax_cache_hash()
static uint32_t vbo_minmax_cache_hash (const struct minmax_cache_key * key) static
Referenced by vbo_get_minmax_cached(), and vbo_minmax_cache_store().
vbo_minmax_cache_key_equal()
static bool vbo_minmax_cache_key_equal (const struct minmax_cache_key * a, const struct minmax_cache_key * b) static
References minmax_cache_key::count, minmax_cache_key::offset, and minmax_cache_key::type.
Referenced by vbo_minmax_cache_store().
vbo_minmax_cache_store()
static void vbo_minmax_cache_store (struct gl_context * ctx, struct gl_buffer_object * bufferObj, GLenum type, GLintptr offset, GLuint count, GLuint min, GLuint max) static
References _mesa_debug(), minmax_cache_key::count, minmax_cache_entry::key, MALLOC_STRUCT, minmax_cache_entry::max, minmax_cache_entry::min, gl_buffer_object::MinMaxCache, gl_buffer_object::Mutex, minmax_cache_key::offset, minmax_cache_key::type, vbo_minmax_cache_hash(), vbo_minmax_cache_key_equal(), and vbo_use_minmax_cache().
Referenced by vbo_get_minmax_index().
vbo_use_minmax_cache()
static GLboolean vbo_use_minmax_cache (struct gl_buffer_object * bufferObj) static
References gl_buffer_mapping::AccessFlags, MAP_USER, gl_buffer_object::Mappings, USAGE_ATOMIC_COUNTER_BUFFER, USAGE_DISABLE_MINMAX_CACHE, USAGE_PIXEL_PACK_BUFFER, USAGE_SHADER_STORAGE_BUFFER, USAGE_TEXTURE_BUFFER, USAGE_TRANSFORM_FEEDBACK_BUFFER, and gl_buffer_object::UsageHistory.
Referenced by vbo_get_minmax_cached(), and vbo_minmax_cache_store().