Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_primitive_restart.c File Reference
#include "main/imports.h"
#include "main/bufferobj.h"
#include "main/macros.h"
#include "main/varray.h"
#include "vbo.h"
#include "vbo_context.h"
Data Structures
struct sub_primitive
Macros
#define UPDATE_MIN2(a, b) (a) = MIN2((a), (b))
#define UPDATE_MAX2(a, b) (a) = MAX2((a), (b))
#define IB_INDEX_READ(TYPE, INDEX) (((const GL##TYPE *) elements)[INDEX])
#define SCAN_ELEMENTS(TYPE)
Functions
static struct sub_primitive * find_sub_primitives (const void *elements, unsigned element_size, unsigned start, unsigned end, unsigned restart_index, unsigned *num_sub_prims)
Scan the elements array to find restart indexes.
void vbo_sw_primitive_restart (struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, struct gl_buffer_object *indirect)
Handle primitive restart in software.
Macro Definition Documentation
IB_INDEX_READ
#define IB_INDEX_READ (TYPE, INDEX) (((const GL##TYPE *) elements)[INDEX])
SCAN_ELEMENTS
#define SCAN_ELEMENTS (TYPE)
Value:
sub_prims[scan_num].min_index = (GL##TYPE) 0xffffffff; \
   sub_prims[scan_num].max_index = 0; \
   for (i = start; i < end; i++) { \
      scan_index = IB_INDEX_READ(TYPE, i); \
      if (scan_index == restart_index) { \
         if (cur_count > 0) { \
            assert(scan_num < max_prims); \
            sub_prims[scan_num].start = cur_start; \
            sub_prims[scan_num].count = cur_count; \
            scan_num++; \
            sub_prims[scan_num].min_index = (GL##TYPE) 0xffffffff; \
            sub_prims[scan_num].max_index = 0; \
         } \
         cur_start = i + 1; \
         cur_count = 0; \
      } \
      else { \
         UPDATE_MIN2(sub_prims[scan_num].min_index, scan_index); \
         UPDATE_MAX2(sub_prims[scan_num].max_index, scan_index); \
         cur_count++; \
      } \
   } \
   if (cur_count > 0) { \
      assert(scan_num < max_prims); \
      sub_prims[scan_num].start = cur_start; \
      sub_prims[scan_num].count = cur_count; \
      scan_num++; \
   }
Referenced by find_sub_primitives().
UPDATE_MAX2
#define UPDATE_MAX2 (a, b) (a) = MAX2((a), (b))
UPDATE_MIN2
#define UPDATE_MIN2 (a, b) (a) = MIN2((a), (b))
Function Documentation
find_sub_primitives()
static struct sub_primitive* find_sub_primitives (const void * elements, unsigned element_size, unsigned start, unsigned end, unsigned restart_index, unsigned * num_sub_prims) static
Scan the elements array to find restart indexes.
Return an array of struct sub_primitive to indicate how to draw the sub-primitives are delineated by the restart index.
References GLuint, SCAN_ELEMENTS, and sub_primitive::start.
Referenced by vbo_sw_primitive_restart().
vbo_sw_primitive_restart()
void vbo_sw_primitive_restart (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib, struct gl_buffer_object * indirect)
Handle primitive restart in software.
This function breaks up calls into the driver so primitive restart support is not required in the driver.
References _mesa_error(), _mesa_primitive_restart_index(), ADD_POINTERS, _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::count, sub_primitive::count, _mesa_index_buffer::count, vbo_context::draw_prims, gl_context::Driver, find_sub_primitives(), GLuint, _mesa_prim::indirect_offset, _mesa_prim::is_indirect, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Mappings, sub_primitive::max_index, sub_primitive::min_index, gl_buffer_object::Name, _mesa_prim::num_instances, _mesa_index_buffer::obj, gl_buffer_mapping::Pointer, _mesa_index_buffer::ptr, gl_buffer_object::Size, _mesa_prim::start, sub_primitive::start, _mesa_index_buffer::type, dd_function_table::UnmapBuffer, vbo_context(), and vbo_sizeof_ib_type().
Referenced by vbo_sizeof_ib_type().