Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_context.h File Reference
VBO builder module datatypes and definitions.
#include "vbo.h"
#include "vbo_attrib.h"
#include "vbo_exec.h"
#include "vbo_save.h"
#include "main/macros.h"
Data Structures
struct vbo_context
Functions
static struct vbo_context * vbo_context (struct gl_context *ctx)
static enum vp_mode get_program_mode (struct gl_context *ctx)
Return VP_x token to indicate whether we're running fixed-function vertex transformation, an NV vertex program or ARB vertex program/shader.
static void vbo_draw_method (struct vbo_context *vbo, gl_draw_method method)
This is called by glBegin, glDrawArrays and glDrawElements (and variations of those calls).
static GLboolean vbo_attrtype_to_integer_flag (GLenum format)
Return if format is integer.
static GLboolean vbo_attrtype_to_double_flag (GLenum format)
static const fi_type * vbo_get_default_vals_as_union (GLenum format)
Return default component values for the given format.
static unsigned vbo_compute_max_verts (const struct vbo_exec_context *exec)
Compute the max number of vertices which can be stored in a vertex buffer, given the current vertex size, and the amount of space already used.
Detailed Description
VBO builder module datatypes and definitions.
Author
Keith Whitwell
Function Documentation
get_program_mode()
static enum vp_mode get_program_mode (struct gl_context * ctx) inline static
Return VP_x token to indicate whether we're running fixed-function vertex transformation, an NV vertex program or ARB vertex program/shader.
References gl_vertex_program_state::_Current, gl_vertex_program_state::_TnlProgram, gl_context::VertexProgram, VP_ARB, and VP_NONE.
Referenced by recalculate_input_bindings(), vbo_bind_vertex_list(), and vbo_exec_bind_arrays().
vbo_attrtype_to_double_flag()
static GLboolean vbo_attrtype_to_double_flag (GLenum format) inline static
Referenced by vbo_exec_copy_to_current().
vbo_attrtype_to_integer_flag()
static GLboolean vbo_attrtype_to_integer_flag (GLenum format) inline static
Return if format is integer.
The immediate mode commands only emit floats for non-integer types, thus everything else is integer.
Referenced by _playback_copy_to_current(), vbo_bind_vertex_list(), vbo_exec_bind_arrays(), and vbo_exec_copy_to_current().
vbo_compute_max_verts()
static unsigned vbo_compute_max_verts (const struct vbo_exec_context * exec) inline static
Compute the max number of vertices which can be stored in a vertex buffer, given the current vertex size, and the amount of space already used.
References vbo_exec_context::buffer_used, VBO_VERT_BUFFER_SIZE, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_vtx_flush(), and vbo_exec_wrap_upgrade_vertex().
vbo_context()
static struct vbo_context* vbo_context (struct gl_context * ctx) static
References gl_context::vbo_context.
Referenced by _playback_copy_to_current(), _save_compile_vertex_list(), _save_copy_from_current(), _save_copy_to_current(), _save_copy_vertices(), _save_current_init(), _save_End(), _save_OBE_DrawArrays(), _save_OBE_DrawElementsBaseVertex(), _save_OBE_DrawRangeElements(), _save_reset_counters(), _save_reset_vertex(), _save_upgrade_vertex(), _save_vtxfmt_init(), _save_wrap_buffers(), _save_wrap_filled_vertex(), _vbo_DestroyContext(), alloc_vertex_store(), dlist_fallback(), init_generic_currval(), init_legacy_currval(), init_mat_currval(), recalculate_input_bindings(), save_fixup_vertex(), vbo_always_unmap_buffers(), vbo_bind_arrays(), vbo_bind_vertex_list(), vbo_draw_arrays(), vbo_draw_indirect_prims(), vbo_draw_transform_feedback(), vbo_exec_Begin(), vbo_exec_begin_vertices(), vbo_exec_bind_arrays(), vbo_exec_copy_from_current(), vbo_exec_copy_to_current(), vbo_exec_destroy(), vbo_exec_End(), vbo_exec_EvalCoord1f(), vbo_exec_EvalCoord2f(), vbo_exec_fixup_vertex(), vbo_exec_FlushVertices(), vbo_exec_init(), vbo_exec_invalidate_state(), vbo_exec_vtx_flush(), vbo_exec_vtx_init(), vbo_exec_wrap_upgrade_vertex(), vbo_save_BeginCallList(), vbo_save_destroy(), vbo_save_EndCallList(), vbo_save_EndList(), vbo_save_fallback(), vbo_save_init(), vbo_save_NewList(), vbo_save_NotifyBegin(), vbo_save_playback_vertex_list(), vbo_save_SaveFlushVertices(), vbo_set_draw_func(), vbo_set_indirect_draw_func(), vbo_sw_primitive_restart(), vbo_use_buffer_objects(), vbo_validated_drawarraysindirect(), vbo_validated_drawelementsindirect(), vbo_validated_drawrangeelements(), vbo_validated_multidrawarraysindirect(), vbo_validated_multidrawarraysindirectcount(), vbo_validated_multidrawelements(), vbo_validated_multidrawelementsindirect(), and vbo_validated_multidrawelementsindirectcount().
vbo_draw_method()
static void vbo_draw_method (struct vbo_context * vbo, gl_draw_method method) inline static
This is called by glBegin, glDrawArrays and glDrawElements (and variations of those calls).
When we transition from immediate mode drawing to array drawing we need to invalidate the array state.
glBegin/End builds vertex arrays. Those arrays may look identical to glDrawArrays arrays except that the position of the elements may be different. For example, arrays of (position3v, normal3f) vs. arrays of (normal3f, position3f). So we need to make sure we notify drivers that arrays may be changing.
References gl_array_attrib::_DrawArrays, gl_context::Array, vbo_exec_context::array, vbo_exec_context::ctx, DRAW_ARRAYS, DRAW_BEGIN_END, DRAW_DISPLAY_LIST, gl_array_attrib::DrawMethod, gl_context::DriverFlags, vbo_context::exec, vbo_exec_context::inputs, vbo_save_context::inputs, gl_driver_flags::NewArray, gl_context::NewDriverState, vbo_context::save, and vbo_exec_context::vtx.
Referenced by vbo_bind_arrays(), vbo_exec_Begin(), and vbo_save_playback_vertex_list().
vbo_get_default_vals_as_union()
static const fi_type* vbo_get_default_vals_as_union (GLenum format) inline static
Return default component values for the given format.
The return type is an array of fi_types, because that's how we declare the vertex storage : floats , integers or unsigned integers.
Referenced by save_fixup_vertex(), and vbo_exec_fixup_vertex().