Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_save_api.c File Reference
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/context.h"
#include "main/dlist.h"
#include "main/enums.h"
#include "main/eval.h"
#include "main/macros.h"
#include "main/api_validate.h"
#include "main/api_arrayelt.h"
#include "main/vtxfmt.h"
#include "main/dispatch.h"
#include "main/state.h"
#include "util/bitscan.h"
#include "vbo_context.h"
#include "vbo_noop.h"
#include "vbo_attrib_tmp.h"
Macros
#define VBO_BUF_ID 12345
#define ERROR(err) _mesa_compile_error(ctx, err, __func__);
#define ATTR_UNION(A, N, T, C, V0, V1, V2, V3)
#define TAG(x) _save_##x
#define MAT(ATTR, N, face, params)
Functions
static GLuint _save_copy_vertices (struct gl_context *ctx, const struct vbo_save_vertex_list *node, const fi_type *src_buffer)
static struct vbo_save_vertex_store * alloc_vertex_store (struct gl_context *ctx)
static void free_vertex_store (struct gl_context *ctx, struct vbo_save_vertex_store *vertex_store)
fi_type * vbo_save_map_vertex_store (struct gl_context *ctx, struct vbo_save_vertex_store *vertex_store)
void vbo_save_unmap_vertex_store (struct gl_context *ctx, struct vbo_save_vertex_store *vertex_store)
static struct vbo_save_primitive_store * alloc_prim_store (struct gl_context *ctx)
static void _save_reset_counters (struct gl_context *ctx)
static void merge_prims (struct _mesa_prim *prim_list, GLuint *prim_count)
For a list of prims, try merging prims that can just be extensions of the previous prim.
static void convert_line_loop_to_strip (struct vbo_save_context *save, struct vbo_save_vertex_list *node)
Convert GL_LINE_LOOP primitive into GL_LINE_STRIP so that drivers don't have to worry about handling the _mesa_prim::begin/end flags.
static void _save_compile_vertex_list (struct gl_context *ctx)
Insert the active immediate struct onto the display list currently being built.
static void _save_wrap_buffers (struct gl_context *ctx)
This is called when we fill a vertex buffer before we hit a glEnd().
static void _save_wrap_filled_vertex (struct gl_context *ctx)
Called only when buffers are wrapped as the result of filling the vertex_store struct.
static void _save_copy_to_current (struct gl_context *ctx)
static void _save_copy_from_current (struct gl_context *ctx)
static void _save_upgrade_vertex (struct gl_context *ctx, GLuint attr, GLuint newsz)
Called when we increase the size of a vertex attribute.
static void save_fixup_vertex (struct gl_context *ctx, GLuint attr, GLuint sz)
This is called when the size of a vertex attribute changes.
static void _save_reset_vertex (struct gl_context *ctx)
Reset the current size of all vertex attributes to the default value of 0.
static void GLAPIENTRY _save_Materialfv (GLenum face, GLenum pname, const GLfloat *params)
Save a glMaterial call found between glBegin/End.
static void dlist_fallback (struct gl_context *ctx)
static void GLAPIENTRY _save_EvalCoord1f (GLfloat u)
static void GLAPIENTRY _save_EvalCoord1fv (const GLfloat *v)
static void GLAPIENTRY _save_EvalCoord2f (GLfloat u, GLfloat v)
static void GLAPIENTRY _save_EvalCoord2fv (const GLfloat *v)
static void GLAPIENTRY _save_EvalPoint1 (GLint i)
static void GLAPIENTRY _save_EvalPoint2 (GLint i, GLint j)
static void GLAPIENTRY _save_CallList (GLuint l)
static void GLAPIENTRY _save_CallLists (GLsizei n, GLenum type, const GLvoid *v)
GLboolean vbo_save_NotifyBegin (struct gl_context *ctx, GLenum mode)
Called when a glBegin is getting compiled into a display list.
static void GLAPIENTRY _save_End (void)
static void GLAPIENTRY _save_Begin (GLenum mode)
static void GLAPIENTRY _save_PrimitiveRestartNV (void)
static void GLAPIENTRY _save_OBE_Rectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
static void GLAPIENTRY _save_OBE_DrawArrays (GLenum mode, GLint start, GLsizei count)
static void GLAPIENTRY _save_OBE_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
static void GLAPIENTRY _save_OBE_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
static void GLAPIENTRY _save_OBE_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
static void GLAPIENTRY _save_OBE_MultiDrawElements (GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount)
static void GLAPIENTRY _save_OBE_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount, const GLint *basevertex)
static void _save_vtxfmt_init (struct gl_context *ctx)
void vbo_initialize_save_dispatch (const struct gl_context *ctx, struct _glapi_table *exec)
Initialize the dispatch table with the VBO functions for display list compilation.
void vbo_save_SaveFlushVertices (struct gl_context *ctx)
void vbo_save_NewList (struct gl_context *ctx, GLuint list, GLenum mode)
void vbo_save_EndList (struct gl_context *ctx)
void vbo_save_BeginCallList (struct gl_context *ctx, struct gl_display_list *dlist)
void vbo_save_EndCallList (struct gl_context *ctx)
static void vbo_destroy_vertex_list (struct gl_context *ctx, void *data)
static void vbo_print_vertex_list (struct gl_context *ctx, void *data, FILE *f)
static void _save_current_init (struct gl_context *ctx)
Called during context creation/init.
void vbo_save_api_init (struct vbo_save_context *save)
Initialize the display list compiler.
Macro Definition Documentation
ATTR_UNION
#define ATTR_UNION (A, N, T, C, V0, V1, V2, V3)
Value:
do {                                                            \
   struct vbo_save_context *save = &vbo_context(ctx)->save;     \
                                                                \
   if (save->active_sz[A] != N)                                 \
      save_fixup_vertex(ctx, A, N);                             \
                                                                \
   {                                                            \
      C *dest = (C *)save->attrptr[A];                          \
      if (N>0) dest[0] = V0;                                    \
      if (N>1) dest[1] = V1;                                    \
      if (N>2) dest[2] = V2;                                    \
      if (N>3) dest[3] = V3;                                    \
      save->attrtype[A] = T;                                    \
   }                                                            \
                                                                \
   if ((A) == 0) {                                              \
      GLuint i;                                                 \
                                                                \
      for (i = 0; i < save->vertex_size; i++)                   \
         save->buffer_ptr[i] = save->vertex[i];                 \
                                                                \
      save->buffer_ptr += save->vertex_size;                    \
                                                                \
      if (++save->vert_count >= save->max_vert)                 \
         _save_wrap_filled_vertex(ctx);                         \
   }                                                            \
} while (0)
ERROR
#define ERROR (err) _mesa_compile_error(ctx, err, __func__);
MAT
#define MAT (ATTR, N, face, params)
Value:
do {                                                    \
   if (face != GL_BACK)                                 \
      MAT_ATTR( ATTR, N, params ); /* front */          \
   if (face != GL_FRONT)                                \
      MAT_ATTR( ATTR + 1, N, params ); /* back */       \
} while (0)
Referenced by _save_Materialfv().
TAG
#define TAG (x) _save_##x
VBO_BUF_ID
#define VBO_BUF_ID 12345
Referenced by alloc_vertex_store().
Function Documentation
_save_Begin()
static void GLAPIENTRY _save_Begin (GLenum mode) static
References _mesa_compile_error(), vbo_save_context::ctx, and void.
Referenced by _save_PrimitiveRestartNV(), and _save_vtxfmt_init().
_save_CallList()
static void GLAPIENTRY _save_CallList (GLuint l) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_CallLists()
static void GLAPIENTRY _save_CallLists (GLsizei n, GLenum type, const GLvoid * v) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_compile_vertex_list()
static void _save_compile_vertex_list (struct gl_context * ctx) static
Insert the active immediate struct onto the display list currently being built.
References _mesa_dlist_alloc_aligned(), _save_copy_vertices(), _save_reset_counters(), alloc_prim_store(), alloc_vertex_store(), vbo_save_vertex_list::attrsz, vbo_save_context::attrsz, vbo_save_vertex_list::attrtype, vbo_save_context::attrtype, vbo_save_vertex_store::buffer, vbo_save_context::buffer, vbo_save_vertex_list::buffer_offset, vbo_save_context::buffer_ptr, convert_line_loop_to_strip(), vbo_save_context::copied, vbo_save_vertex_list::count, vbo_save_vertex_list::current_data, vbo_save_vertex_list::current_size, gl_dlist_state::CurrentList, vbo_save_vertex_list::dangling_attr_ref, vbo_save_context::dangling_attr_ref, DLIST_DANGLING_REFS, vbo_save_vertex_list::enabled, vbo_save_context::enabled, gl_context::Exec, gl_context::ExecuteFlag, gl_display_list::Flags, gl_context::ListState, merge_prims(), _mesa_prim::mode, _mesa_prim::no_current_update, vbo_save_copied_vtx::nr, vbo_save_context::opcode_vertex_list, vbo_save_context::out_of_memory, vbo_save_vertex_list::prim, vbo_save_context::prim, vbo_save_vertex_list::prim_count, vbo_save_context::prim_count, vbo_save_vertex_list::prim_store, vbo_save_context::prim_store, vbo_save_vertex_store::refcount, vbo_save_primitive_store::refcount, vbo_context::save, vbo_save_vertex_store::used, vbo_save_primitive_store::used, VBO_ATTRIB_POS, vbo_context(), vbo_loopback_vertex_list(), VBO_SAVE_BUFFER_SIZE, vbo_save_map_vertex_store(), VBO_SAVE_PRIM_SIZE, vbo_save_unmap_vertex_store(), vbo_save_context::vert_count, vbo_save_vertex_list::vertex_size, vbo_save_context::vertex_size, vbo_save_vertex_list::vertex_store, vbo_save_context::vertex_store, and vbo_save_vertex_list::wrap_count.
Referenced by _save_End(), _save_wrap_buffers(), dlist_fallback(), and vbo_save_SaveFlushVertices().
_save_copy_from_current()
static void _save_copy_from_current (struct gl_context * ctx) static
References vbo_save_context::attrptr, vbo_save_context::attrsz, BITFIELD64_BIT, vbo_save_context::current, vbo_save_context::enabled, vbo_context::save, VBO_ATTRIB_POS, and vbo_context().
Referenced by _save_upgrade_vertex().
_save_copy_to_current()
static void _save_copy_to_current (struct gl_context * ctx) static
References vbo_save_context::attrptr, vbo_save_context::attrsz, vbo_save_context::attrtype, BITFIELD64_BIT, vbo_save_context::current, vbo_save_context::currentsz, vbo_save_context::enabled, vbo_context::save, VBO_ATTRIB_POS, and vbo_context().
Referenced by _save_upgrade_vertex(), dlist_fallback(), and vbo_save_SaveFlushVertices().
_save_copy_vertices()
static GLuint _save_copy_vertices (struct gl_context * ctx, const struct vbo_save_vertex_list * node, const fi_type * src_buffer) static
References vbo_save_copied_vtx::buffer, vbo_save_context::copied, _mesa_prim::count, _mesa_prim::end, GLuint, _mesa_prim::mode, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, vbo_context::save, _mesa_prim::start, vbo_context(), and vbo_save_context::vertex_size.
Referenced by _save_compile_vertex_list().
_save_current_init()
static void _save_current_init (struct gl_context * ctx) static
Called during context creation/init.
References gl_dlist_state::ActiveAttribSize, gl_dlist_state::ActiveMaterialSize, vbo_save_context::current, gl_dlist_state::CurrentAttrib, gl_dlist_state::CurrentMaterial, vbo_save_context::currentsz, GLuint, gl_context::ListState, MAT_ATTRIB_MAX, vbo_context::save, VBO_ATTRIB_FIRST_MATERIAL, VBO_ATTRIB_GENERIC15, VBO_ATTRIB_LAST_MATERIAL, VBO_ATTRIB_POS, and vbo_context().
Referenced by vbo_save_api_init().
_save_End()
static void GLAPIENTRY _save_End (void) static
References _mesa_install_save_vtxfmt(), _save_compile_vertex_list(), vbo_save_context::copied, _mesa_prim::count, vbo_save_context::ctx, dd_function_table::CurrentSavePrimitive, gl_context::Driver, _mesa_prim::end, gl_context::ListState, gl_dlist_state::ListVtxfmt, vbo_save_copied_vtx::nr, vbo_save_context::out_of_memory, vbo_save_context::prim, vbo_save_context::prim_count, vbo_save_context::prim_max, PRIM_OUTSIDE_BEGIN_END, vbo_context::save, _mesa_prim::start, vbo_context(), vbo_save_context::vert_count, and vbo_save_context::vtxfmt_noop.
Referenced by _save_PrimitiveRestartNV(), and _save_vtxfmt_init().
_save_EvalCoord1f()
static void GLAPIENTRY _save_EvalCoord1f (GLfloat u) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_EvalCoord1fv()
static void GLAPIENTRY _save_EvalCoord1fv (const GLfloat * v) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_EvalCoord2f()
static void GLAPIENTRY _save_EvalCoord2f (GLfloat u, GLfloat v) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_EvalCoord2fv()
static void GLAPIENTRY _save_EvalCoord2fv (const GLfloat * v) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_EvalPoint1()
static void GLAPIENTRY _save_EvalPoint1 (GLint i) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_EvalPoint2()
static void GLAPIENTRY _save_EvalPoint2 (GLint i, GLint j) static
References vbo_save_context::ctx, dlist_fallback(), and gl_context::Save.
Referenced by _save_vtxfmt_init().
_save_Materialfv()
static void GLAPIENTRY _save_Materialfv (GLenum face, GLenum pname, const GLfloat * params) static
Save a glMaterial call found between glBegin/End.
glMaterial calls outside Begin/End are handled in dlist.c.
References _mesa_compile_error(), gl_context::Const, vbo_save_context::ctx, MAT, gl_constants::MaxShininess, VBO_ATTRIB_MAT_FRONT_AMBIENT, VBO_ATTRIB_MAT_FRONT_DIFFUSE, VBO_ATTRIB_MAT_FRONT_EMISSION, VBO_ATTRIB_MAT_FRONT_INDEXES, VBO_ATTRIB_MAT_FRONT_SHININESS, and VBO_ATTRIB_MAT_FRONT_SPECULAR.
Referenced by _save_vtxfmt_init().
_save_OBE_DrawArrays()
static void GLAPIENTRY _save_OBE_DrawArrays (GLenum mode, GLint start, GLsizei count) static
References _ae_map_vbos(), _ae_unmap_vbos(), _mesa_compile_error(), _mesa_is_valid_prim_mode(), _mesa_update_state(), vbo_save_context::count, vbo_save_context::ctx, vbo_save_context::out_of_memory, vbo_context::save, vbo_context(), vbo_save_NotifyBegin(), VBO_SAVE_PRIM_NO_CURRENT_UPDATE, and VBO_SAVE_PRIM_WEAK.
Referenced by vbo_initialize_save_dispatch().
_save_OBE_DrawElements()
static void GLAPIENTRY _save_OBE_DrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices) static
References _save_OBE_DrawElementsBaseVertex().
Referenced by _save_OBE_DrawRangeElements(), and vbo_initialize_save_dispatch().
_save_OBE_DrawElementsBaseVertex()
static void GLAPIENTRY _save_OBE_DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex) static
References _ae_map_vbos(), _ae_unmap_vbos(), _mesa_compile_error(), _mesa_error(), _mesa_is_valid_prim_mode(), _mesa_update_state(), ADD_POINTERS, vbo_save_context::ctx, GLuint, GLushort, MAP_INTERNAL, gl_buffer_object::Mappings, vbo_save_context::out_of_memory, gl_buffer_mapping::Pointer, vbo_context::save, vbo_context(), vbo_save_NotifyBegin(), VBO_SAVE_PRIM_NO_CURRENT_UPDATE, and VBO_SAVE_PRIM_WEAK.
Referenced by _save_OBE_DrawElements(), and vbo_initialize_save_dispatch().
_save_OBE_DrawRangeElements()
static void GLAPIENTRY _save_OBE_DrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices) static
References _mesa_compile_error(), _mesa_is_valid_prim_mode(), _save_OBE_DrawElements(), vbo_save_context::ctx, vbo_save_context::out_of_memory, vbo_context::save, and vbo_context().
Referenced by vbo_initialize_save_dispatch().
_save_OBE_MultiDrawElements()
static void GLAPIENTRY _save_OBE_MultiDrawElements (GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount) static
Referenced by vbo_initialize_save_dispatch().
_save_OBE_MultiDrawElementsBaseVertex()
static void GLAPIENTRY _save_OBE_MultiDrawElementsBaseVertex (GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount, const GLint * basevertex) static
Referenced by vbo_initialize_save_dispatch().
_save_OBE_Rectf()
static void GLAPIENTRY _save_OBE_Rectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2) static
References vbo_save_context::ctx, vbo_save_NotifyBegin(), and VBO_SAVE_PRIM_WEAK.
Referenced by vbo_initialize_save_dispatch().
_save_PrimitiveRestartNV()
static void GLAPIENTRY _save_PrimitiveRestartNV (void) static
References _save_Begin(), _save_End(), vbo_save_context::ctx, dd_function_table::CurrentSavePrimitive, and gl_context::Driver.
Referenced by _save_vtxfmt_init().
_save_reset_counters()
static void _save_reset_counters (struct gl_context * ctx) static
References vbo_save_vertex_store::buffer, vbo_save_primitive_store::buffer, vbo_save_context::buffer, vbo_save_context::buffer_ptr, vbo_save_context::dangling_attr_ref, vbo_save_context::max_vert, vbo_save_context::prim, vbo_save_context::prim_count, vbo_save_context::prim_max, vbo_save_context::prim_store, vbo_context::save, vbo_save_vertex_store::used, vbo_save_primitive_store::used, vbo_context(), VBO_SAVE_BUFFER_SIZE, VBO_SAVE_PRIM_SIZE, vbo_save_context::vert_count, vbo_save_context::vertex_size, and vbo_save_context::vertex_store.
Referenced by _save_compile_vertex_list(), dlist_fallback(), vbo_save_NewList(), and vbo_save_SaveFlushVertices().
_save_reset_vertex()
static void _save_reset_vertex (struct gl_context * ctx) static
Reset the current size of all vertex attributes to the default value of 0.
This signals that we haven't yet seen any per-vertex commands such as glNormal3f() or glTexCoord2f().
References vbo_save_context::active_sz, vbo_save_context::attrsz, vbo_save_context::enabled, vbo_context::save, vbo_context(), and vbo_save_context::vertex_size.
Referenced by dlist_fallback(), vbo_save_NewList(), and vbo_save_SaveFlushVertices().
_save_upgrade_vertex()
static void _save_upgrade_vertex (struct gl_context * ctx, GLuint attr, GLuint newsz) static
Called when we increase the size of a vertex attribute.
For example, if we've seen one or more glTexCoord2f() calls and now we get a glTexCoord3f() call. Flush existing data, set new attrib size, replay copied vertices.
References _save_copy_from_current(), _save_copy_to_current(), _save_wrap_buffers(), vbo_save_context::attrptr, vbo_save_context::attrsz, vbo_save_context::attrtype, BITFIELD64_BIT, vbo_save_copied_vtx::buffer, vbo_save_context::buffer, vbo_save_context::buffer_ptr, vbo_save_context::copied, COPY_SZ_4V, vbo_save_context::current, vbo_save_context::currentsz, vbo_save_context::dangling_attr_ref, vbo_save_context::enabled, GLuint, vbo_save_context::max_vert, vbo_save_copied_vtx::nr, vbo_context::save, vbo_save_vertex_store::used, VBO_ATTRIB_MAX, VBO_ATTRIB_POS, vbo_context(), VBO_SAVE_BUFFER_SIZE, vbo_save_context::vert_count, vbo_save_context::vertex, vbo_save_context::vertex_size, and vbo_save_context::vertex_store.
Referenced by save_fixup_vertex().
_save_vtxfmt_init()
static void _save_vtxfmt_init (struct gl_context * ctx) static
References _ae_ArrayElement(), _save_Begin(), _save_CallList(), _save_CallLists(), _save_End(), _save_EvalCoord1f(), _save_EvalCoord1fv(), _save_EvalCoord2f(), _save_EvalCoord2fv(), _save_EvalPoint1(), _save_EvalPoint2(), _save_Materialfv(), _save_PrimitiveRestartNV(), vbo_context::save, vbo_context(), and vbo_save_context::vtxfmt.
Referenced by vbo_save_api_init().
_save_wrap_buffers()
static void _save_wrap_buffers (struct gl_context * ctx) static
This is called when we fill a vertex buffer before we hit a glEnd().
We TODO – If no new vertices have been stored, don't bother saving it.
References _save_compile_vertex_list(), _mesa_prim::base_instance, _mesa_prim::begin, _mesa_prim::count, _mesa_prim::end, _mesa_prim::is_indirect, _mesa_prim::mode, _mesa_prim::no_current_update, _mesa_prim::num_instances, _mesa_prim::pad, vbo_save_context::prim, vbo_save_context::prim_count, vbo_save_context::prim_max, vbo_context::save, _mesa_prim::start, vbo_context(), vbo_save_context::vert_count, and _mesa_prim::weak.
Referenced by _save_upgrade_vertex(), and _save_wrap_filled_vertex().
_save_wrap_filled_vertex()
static void _save_wrap_filled_vertex (struct gl_context * ctx) static
Called only when buffers are wrapped as the result of filling the vertex_store struct.
References _save_wrap_buffers(), vbo_save_copied_vtx::buffer, vbo_save_context::buffer_ptr, vbo_save_context::copied, vbo_save_context::max_vert, vbo_save_copied_vtx::nr, vbo_context::save, vbo_context(), vbo_save_context::vert_count, and vbo_save_context::vertex_size.
alloc_prim_store()
static struct vbo_save_primitive_store* alloc_prim_store (struct gl_context * ctx) static
References CALLOC_STRUCT, vbo_save_primitive_store::refcount, vbo_save_primitive_store::used, and void.
Referenced by _save_compile_vertex_list(), and vbo_save_NewList().
alloc_vertex_store()
static struct vbo_save_vertex_store* alloc_vertex_store (struct gl_context * ctx) static
References _mesa_error(), _mesa_install_save_vtxfmt(), vbo_save_vertex_store::buffer, dd_function_table::BufferData, vbo_save_vertex_store::bufferobj, CALLOC_STRUCT, gl_context::Driver, dd_function_table::NewBufferObject, vbo_save_context::out_of_memory, vbo_save_vertex_store::refcount, vbo_context::save, vbo_save_vertex_store::used, VBO_BUF_ID, vbo_context(), VBO_SAVE_BUFFER_SIZE, and vbo_save_context::vtxfmt_noop.
Referenced by _save_compile_vertex_list(), and vbo_save_NewList().
convert_line_loop_to_strip()
static void convert_line_loop_to_strip (struct vbo_save_context * save, struct vbo_save_vertex_list * node) static
Convert GL_LINE_LOOP primitive into GL_LINE_STRIP so that drivers don't have to worry about handling the _mesa_prim::begin/end flags.
See https://bugs.freedesktop.org/show_bug.cgi?id=81174
References _mesa_prim::begin, vbo_save_context::buffer, vbo_save_context::buffer_ptr, _mesa_prim::count, vbo_save_vertex_list::count, _mesa_prim::end, GLuint, _mesa_prim::mode, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, _mesa_prim::start, vbo_save_vertex_store::used, vbo_save_context::vert_count, vbo_save_context::vertex_size, and vbo_save_context::vertex_store.
Referenced by _save_compile_vertex_list().
dlist_fallback()
static void dlist_fallback (struct gl_context * ctx) static
References _mesa_install_save_vtxfmt(), _save_compile_vertex_list(), _save_copy_to_current(), _save_reset_counters(), _save_reset_vertex(), _mesa_prim::count, vbo_save_context::dangling_attr_ref, gl_context::Driver, gl_context::ListState, gl_dlist_state::ListVtxfmt, vbo_save_context::out_of_memory, vbo_save_context::prim, vbo_save_context::prim_count, vbo_context::save, dd_function_table::SaveNeedFlush, _mesa_prim::start, vbo_context(), vbo_save_context::vert_count, and vbo_save_context::vtxfmt_noop.
Referenced by _save_CallList(), _save_CallLists(), _save_EvalCoord1f(), _save_EvalCoord1fv(), _save_EvalCoord2f(), _save_EvalCoord2fv(), _save_EvalPoint1(), and _save_EvalPoint2().
free_vertex_store()
static void free_vertex_store (struct gl_context * ctx, struct vbo_save_vertex_store * vertex_store) static
References vbo_save_vertex_store::buffer, and vbo_save_vertex_store::bufferobj.
Referenced by vbo_destroy_vertex_list().
merge_prims()
static void merge_prims (struct _mesa_prim * prim_list, GLuint * prim_count) static
For a list of prims, try merging prims that can just be extensions of the previous prim.
References GLuint, vbo_can_merge_prims(), vbo_merge_prims(), and vbo_try_prim_conversion().
Referenced by _save_compile_vertex_list().
save_fixup_vertex()
static void save_fixup_vertex (struct gl_context * ctx, GLuint attr, GLuint sz) static
This is called when the size of a vertex attribute changes.
For example, after seeing one or more glTexCoord2f() calls we get a glTexCoord4f() or glTexCoord1f() call.
References _save_upgrade_vertex(), vbo_save_context::active_sz, vbo_save_context::attrptr, vbo_save_context::attrsz, vbo_save_context::attrtype, GLuint, vbo_context::save, vbo_context(), and vbo_get_default_vals_as_union().
vbo_destroy_vertex_list()
static void vbo_destroy_vertex_list (struct gl_context * ctx, void * data) static
References vbo_save_vertex_list::current_data, free_vertex_store(), vbo_save_vertex_list::prim_store, vbo_save_vertex_store::refcount, vbo_save_primitive_store::refcount, vbo_save_vertex_list::vertex_store, and void.
Referenced by vbo_save_api_init().
vbo_initialize_save_dispatch()
void vbo_initialize_save_dispatch (const struct gl_context * ctx, struct _glapi_table * exec)
Initialize the dispatch table with the VBO functions for display list compilation.
References _save_OBE_DrawArrays(), _save_OBE_DrawElements(), _save_OBE_DrawElementsBaseVertex(), _save_OBE_DrawRangeElements(), _save_OBE_MultiDrawElements(), _save_OBE_MultiDrawElementsBaseVertex(), and _save_OBE_Rectf().
vbo_print_vertex_list()
static void vbo_print_vertex_list (struct gl_context * ctx, void * data, FILE * f) static
References _mesa_lookup_prim_by_nr(), _mesa_prim::begin, vbo_save_vertex_store::bufferobj, _mesa_prim::count, vbo_save_vertex_list::count, _mesa_prim::end, GLuint, _mesa_prim::mode, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, _mesa_prim::start, vbo_save_vertex_list::vertex_size, vbo_save_vertex_list::vertex_store, void, and _mesa_prim::weak.
Referenced by vbo_save_api_init().
vbo_save_api_init()
void vbo_save_api_init (struct vbo_save_context * save)
Initialize the display list compiler.
Called during context creation.
References _mesa_dlist_alloc_opcode(), _mesa_noop_vtxfmt_init(), _save_current_init(), _save_vtxfmt_init(), vbo_save_context::arrays, vbo_save_context::ctx, GLuint, vbo_save_context::inputs, vbo_save_context::opcode_vertex_list, VBO_ATTRIB_MAX, vbo_destroy_vertex_list(), vbo_print_vertex_list(), vbo_save_playback_vertex_list(), and vbo_save_context::vtxfmt_noop.
Referenced by vbo_save_init().
vbo_save_BeginCallList()
void vbo_save_BeginCallList (struct gl_context * ctx, struct gl_display_list * dlist)
References gl_display_list::Flags, vbo_save_context::replay_flags, vbo_context::save, and vbo_context().
vbo_save_EndCallList()
void vbo_save_EndCallList (struct gl_context * ctx)
References gl_dlist_state::CallDepth, gl_context::ListState, vbo_save_context::replay_flags, vbo_context::save, vbo_context(), and VBO_SAVE_FALLBACK.
vbo_save_EndList()
void vbo_save_EndList (struct gl_context * ctx)
References _mesa_install_save_vtxfmt(), _mesa_prim::count, dd_function_table::CurrentSavePrimitive, vbo_save_context::dangling_attr_ref, gl_context::Driver, _mesa_prim::end, gl_context::ListState, gl_dlist_state::ListVtxfmt, vbo_save_context::prim, vbo_save_context::prim_count, PRIM_OUTSIDE_BEGIN_END, vbo_context::save, _mesa_prim::start, vbo_context(), vbo_save_SaveFlushVertices(), vbo_save_unmap_vertex_store(), vbo_save_context::vert_count, vbo_save_context::vertex_size, and vbo_save_context::vertex_store.
vbo_save_map_vertex_store()
fi_type* vbo_save_map_vertex_store (struct gl_context * ctx, struct vbo_save_vertex_store * vertex_store)
References vbo_save_vertex_store::buffer, vbo_save_vertex_store::bufferobj, gl_context::Driver, MAP_INTERNAL, dd_function_table::MapBufferRange, gl_buffer_object::Size, and vbo_save_vertex_store::used.
Referenced by _save_compile_vertex_list(), vbo_save_NewList(), and vbo_save_playback_vertex_list().
vbo_save_NewList()
void vbo_save_NewList (struct gl_context * ctx, GLuint list, GLenum mode)
References _save_reset_counters(), _save_reset_vertex(), alloc_prim_store(), alloc_vertex_store(), vbo_save_context::buffer_ptr, gl_context::Driver, vbo_save_context::prim_store, vbo_context::save, dd_function_table::SaveNeedFlush, vbo_context(), vbo_save_map_vertex_store(), vbo_save_context::vertex_store, and void.
vbo_save_NotifyBegin()
GLboolean vbo_save_NotifyBegin (struct gl_context * ctx, GLenum mode)
Called when a glBegin is getting compiled into a display list.
Updating of ctx->Driver.CurrentSavePrimitive is already taken care of.
References _mesa_install_save_vtxfmt(), _mesa_prim::base_instance, _mesa_prim::begin, _mesa_prim::count, gl_context::Driver, _mesa_prim::end, GLuint, _mesa_prim::is_indirect, _mesa_prim::mode, _mesa_prim::no_current_update, _mesa_prim::num_instances, vbo_save_context::out_of_memory, _mesa_prim::pad, vbo_save_context::prim, vbo_save_context::prim_count, vbo_save_context::prim_max, vbo_context::save, dd_function_table::SaveNeedFlush, _mesa_prim::start, vbo_context(), VBO_SAVE_PRIM_MODE_MASK, VBO_SAVE_PRIM_NO_CURRENT_UPDATE, VBO_SAVE_PRIM_WEAK, vbo_save_context::vert_count, vbo_save_context::vtxfmt, vbo_save_context::vtxfmt_noop, and _mesa_prim::weak.
Referenced by _save_OBE_DrawArrays(), _save_OBE_DrawElementsBaseVertex(), and _save_OBE_Rectf().
vbo_save_SaveFlushVertices()
void vbo_save_SaveFlushVertices (struct gl_context * ctx)
References _save_compile_vertex_list(), _save_copy_to_current(), _save_reset_counters(), _save_reset_vertex(), dd_function_table::CurrentSavePrimitive, gl_context::Driver, vbo_save_context::prim_count, PRIM_MAX, vbo_context::save, dd_function_table::SaveNeedFlush, vbo_context(), and vbo_save_context::vert_count.
Referenced by vbo_save_EndList().
vbo_save_unmap_vertex_store()
void vbo_save_unmap_vertex_store (struct gl_context * ctx, struct vbo_save_vertex_store * vertex_store)
References vbo_save_vertex_store::buffer, vbo_save_vertex_store::bufferobj, gl_context::Driver, dd_function_table::FlushMappedBufferRange, MAP_INTERNAL, gl_buffer_object::Mappings, gl_buffer_mapping::Offset, gl_buffer_object::Size, dd_function_table::UnmapBuffer, and vbo_save_vertex_store::used.
Referenced by _save_compile_vertex_list(), vbo_save_EndList(), and vbo_save_playback_vertex_list().