Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_context.c File Reference
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/api_arrayelt.h"
#include "main/bufferobj.h"
#include "math/m_eval.h"
#include "vbo.h"
#include "vbo_context.h"
Functions
static GLuint check_size (const GLfloat *attr)
static void init_array (struct gl_context *ctx, struct gl_vertex_array *cl, unsigned size, const void *pointer)
Helper for initializing a vertex array.
static void init_legacy_currval (struct gl_context *ctx)
Set up the vbo->currval arrays to point at the context's current vertex attributes (with strides = 0).
static void init_generic_currval (struct gl_context *ctx)
static void init_mat_currval (struct gl_context *ctx)
static void vbo_draw_indirect_prims (struct gl_context *ctx, GLuint mode, struct gl_buffer_object *indirect_data, GLsizeiptr indirect_offset, unsigned draw_count, unsigned stride, struct gl_buffer_object *indirect_params, GLsizeiptr indirect_params_offset, const struct _mesa_index_buffer *ib)
GLboolean _vbo_CreateContext (struct gl_context *ctx)
void _vbo_InvalidateState (struct gl_context *ctx, GLbitfield new_state)
void _vbo_DestroyContext (struct gl_context *ctx)
void vbo_set_draw_func (struct gl_context *ctx, vbo_draw_func func)
void vbo_set_indirect_draw_func (struct gl_context *ctx, vbo_indirect_draw_func func)
Function Documentation
_vbo_CreateContext()
GLboolean _vbo_CreateContext (struct gl_context * ctx)
References _ae_create_context(), _math_init_eval(), gl_context::aelt_context, gl_context::API, API_OPENGL_COMPAT, CALLOC_STRUCT, for(), GLuint, init_generic_currval(), init_legacy_currval(), init_mat_currval(), vbo_context::map_vp_arb, vbo_context::map_vp_none, MAT_ATTRIB_MAX, VBO_ATTRIB_MAT_FRONT_AMBIENT, gl_context::vbo_context, vbo_draw_indirect_prims(), vbo_exec_init(), vbo_save_init(), and vbo_set_indirect_draw_func().
_vbo_DestroyContext()
void _vbo_DestroyContext (struct gl_context * ctx)
References _ae_destroy_context(), gl_context::aelt_context, gl_context::API, API_OPENGL_COMPAT, gl_vertex_array::BufferObj, vbo_context::currval, GLuint, VBO_ATTRIB_MAX, gl_context::vbo_context, vbo_context(), vbo_exec_destroy(), and vbo_save_destroy().
_vbo_InvalidateState()
void _vbo_InvalidateState (struct gl_context * ctx, GLbitfield new_state)
References vbo_exec_invalidate_state().
check_size()
static GLuint check_size (const GLfloat * attr) static
References F, and GLuint.
Referenced by init_legacy_currval().
init_array()
static void init_array (struct gl_context * ctx, struct gl_vertex_array * cl, unsigned size, const void * pointer) static
Helper for initializing a vertex array.
References gl_vertex_array::_ElementSize, gl_vertex_array::BufferObj, gl_vertex_array::Format, gl_shared_state::NullBufferObj, gl_vertex_array::Ptr, gl_context::Shared, gl_vertex_array::Size, gl_vertex_array::StrideB, and gl_vertex_array::Type.
Referenced by init_generic_currval(), init_legacy_currval(), and init_mat_currval().
init_generic_currval()
static void init_generic_currval (struct gl_context * ctx) static
References gl_current_attrib::Attrib, gl_context::Current, vbo_context::currval, GLuint, init_array(), VBO_ATTRIB_GENERIC0, and vbo_context().
Referenced by _vbo_CreateContext().
init_legacy_currval()
static void init_legacy_currval (struct gl_context * ctx) static
Set up the vbo->currval arrays to point at the context's current vertex attributes (with strides = 0).
References gl_current_attrib::Attrib, check_size(), gl_context::Current, vbo_context::currval, GLuint, init_array(), and vbo_context().
Referenced by _vbo_CreateContext().
init_mat_currval()
static void init_mat_currval (struct gl_context * ctx) static
References gl_material::Attrib, vbo_context::currval, GLuint, init_array(), gl_context::Light, MAT_ATTRIB_BACK_INDEXES, MAT_ATTRIB_BACK_SHININESS, MAT_ATTRIB_FRONT_INDEXES, MAT_ATTRIB_FRONT_SHININESS, MAT_ATTRIB_MAX, gl_light_attrib::Material, VBO_ATTRIB_MAT_FRONT_AMBIENT, and vbo_context().
Referenced by _vbo_CreateContext().
vbo_draw_indirect_prims()
static void vbo_draw_indirect_prims (struct gl_context * ctx, GLuint mode, struct gl_buffer_object * indirect_data, GLsizeiptr indirect_offset, unsigned draw_count, unsigned stride, struct gl_buffer_object * indirect_params, GLsizeiptr indirect_params_offset, const struct _mesa_index_buffer * ib) static
References _mesa_error(), _mesa_prim::begin, _mesa_prim::draw_id, vbo_context::draw_prims, gl_context::DrawIndirectBuffer, _mesa_prim::end, _mesa_prim::indexed, _mesa_prim::indirect_offset, _mesa_prim::is_indirect, _mesa_prim::mode, and vbo_context().
Referenced by _vbo_CreateContext().
vbo_set_draw_func()
void vbo_set_draw_func (struct gl_context * ctx, vbo_draw_func func)
References vbo_context::draw_prims, and vbo_context().
Referenced by vbo_sizeof_ib_type().
vbo_set_indirect_draw_func()
void vbo_set_indirect_draw_func (struct gl_context * ctx, vbo_indirect_draw_func func)
References vbo_context::draw_indirect_prims, and vbo_context().
Referenced by _vbo_CreateContext(), and vbo_sizeof_ib_type().