Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_split.c File Reference
#include "main/glheader.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "vbo_split.h"
#include "vbo.h"
Functions
GLboolean split_prim_inplace (GLenum mode, GLuint *first, GLuint *incr)
void vbo_split_prims (struct gl_context *ctx, const struct gl_vertex_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits *limits)
Function Documentation
split_prim_inplace()
GLboolean split_prim_inplace (GLenum mode, GLuint * first, GLuint * incr)
Referenced by replay_elts(), and split_prims().
vbo_split_prims()
void vbo_split_prims (struct gl_context * ctx, const struct gl_vertex_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits * limits)
References _mesa_index_buffer::count, split_limits::max_indices, split_limits::max_verts, vbo_split_copy(), and vbo_split_inplace().