Mesa Source Code Documentation
core | glapi | glsl | nir | vbo | math | swrast | swrast_setup | tnl | tnl_dd | gbm | i965
vbo_save_loopback.c File Reference
#include <stdio.h>
#include "main/context.h"
#include "main/glheader.h"
#include "main/enums.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/dispatch.h"
#include "glapi/glapi.h"
#include "vbo_context.h"
Data Structures
struct loopback_attr
Typedefs
typedef void(* attr_func) (struct gl_context *ctx, GLint target, const GLfloat *)
Functions
static void VertexAttrib1fvNV (struct gl_context *ctx, GLint target, const GLfloat *v)
static void VertexAttrib2fvNV (struct gl_context *ctx, GLint target, const GLfloat *v)
static void VertexAttrib3fvNV (struct gl_context *ctx, GLint target, const GLfloat *v)
static void VertexAttrib4fvNV (struct gl_context *ctx, GLint target, const GLfloat *v)
static void loopback_prim (struct gl_context *ctx, const GLfloat *buffer, const struct _mesa_prim *prim, GLuint wrap_count, GLuint vertex_size, const struct loopback_attr *la, GLuint nr)
static void loopback_weak_prim (struct gl_context *ctx, const struct _mesa_prim *prim)
void vbo_loopback_vertex_list (struct gl_context *ctx, const GLfloat *buffer, const GLubyte *attrsz, const struct _mesa_prim *prim, GLuint prim_count, GLuint wrap_count, GLuint vertex_size)
Variables
static attr_func vert_attrfunc [4]
Typedef Documentation
attr_func
typedef void(* attr_func) (struct gl_context *ctx, GLint target, const GLfloat *)
Function Documentation
loopback_prim()
static void loopback_prim (struct gl_context * ctx, const GLfloat * buffer, const struct _mesa_prim * prim, GLuint wrap_count, GLuint vertex_size, const struct loopback_attr * la, GLuint nr) static
References _mesa_lookup_prim_by_nr(), _mesa_prim::begin, _mesa_prim::count, _mesa_prim::end, end(), loopback_attr::func, GLuint, _mesa_prim::mode, _mesa_prim::start, loopback_attr::sz, loopback_attr::target, and VBO_ATTRIB_POS.
Referenced by vbo_loopback_vertex_list().
loopback_weak_prim()
static void loopback_weak_prim (struct gl_context * ctx, const struct _mesa_prim * prim) static
References _mesa_prim::begin, dd_function_table::CurrentExecPrimitive, gl_context::Driver, _mesa_prim::end, and VBO_SAVE_PRIM_WEAK.
Referenced by vbo_loopback_vertex_list().
vbo_loopback_vertex_list()
void vbo_loopback_vertex_list (struct gl_context * ctx, const GLfloat * buffer, const GLubyte * attrsz, const struct _mesa_prim * prim, GLuint prim_count, GLuint wrap_count, GLuint vertex_size)
References loopback_attr::func, GLuint, loopback_prim(), loopback_weak_prim(), loopback_attr::sz, loopback_attr::target, VBO_ATTRIB_MAX, VBO_SAVE_PRIM_WEAK, and vert_attrfunc.
Referenced by _save_compile_vertex_list(), and vbo_save_loopback_vertex_list().
VertexAttrib1fvNV()
static void VertexAttrib1fvNV (struct gl_context * ctx, GLint target, const GLfloat * v) static
References gl_context::Exec.
VertexAttrib2fvNV()
static void VertexAttrib2fvNV (struct gl_context * ctx, GLint target, const GLfloat * v) static
References gl_context::Exec.
VertexAttrib3fvNV()
static void VertexAttrib3fvNV (struct gl_context * ctx, GLint target, const GLfloat * v) static
References gl_context::Exec.
VertexAttrib4fvNV()
static void VertexAttrib4fvNV (struct gl_context * ctx, GLint target, const GLfloat * v) static
References gl_context::Exec.
Variable Documentation
vert_attrfunc
attr_func vert_attrfunc[4] static
Initial value:
= {
   VertexAttrib1fvNV,
   VertexAttrib2fvNV,
   VertexAttrib3fvNV,
   VertexAttrib4fvNV
}
Referenced by vbo_loopback_vertex_list().